### ISSUE TITLE
Your index.m3u list dont work  with simple.tv

### ISSUE THREAD

**Issue by hayatiptv** [iptv-org/iptv#1000]
your index.m3u list works good with country on vlc  bat not with simple tv on kodi only list country but no channels. please update

**Comment by freearhey** [comment]
Have you tried one of the alternative playlists?

https://iptv-org.github.io/iptv/index.country.m3u (grouped by country)
https://iptv-org.github.io/iptv/index.category.m3u (grouped by category)
https://iptv-org.github.io/iptv/index.language.m3u (grouped by language)

**Comment by hayatiptv** [comment]
sorry with vlc oke but not on kodi with simple tv no list

**Comment by freearhey** [comment]
I'm sorry, but I still don't get it, have you tried using one of the playlists above?

**Comment by kdrmame** [comment]
teşekürler
