### ISSUE TITLE
分发给更多 用户

### ISSUE THREAD

**Issue by kalicsv** [iptv-org/iptv#1002]
The important idea of my question is to make Ip connection and play it in the browser

**Comment by kalicsv** [comment]
> The important idea of my question is to make Ip connection and play it in the browser
The first command line operation I did was mainly to import and play TV on storage Ip.

**Comment by freearhey** [comment]
You can already watch IPTV through a browser using web players like these: https://github.com/iptv-org/awesome-iptv#web
