### ISSUE TITLE
Add: Global News (TW)

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#10035]
### Channel ID

GlobalNews.tw

### Stream URL

https://m.youtube.com/watch?v=B7Zp3d6xXWw

### Notes

Fullspeed TV plz

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://youtube.com/c/%E5%AF%B0%E5%AE%87%E6%96%B0%E8%81%9E%E9%A0%BB%E9%81%93/live

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://youtube.com/c/%E5%AF%B0%E5%AE%87%E6%96%B0%E8%81%9E%E9%A0%BB%E9%81%93/live (offline)
<img width="833" alt="image" src="https://user-images.githubusercontent.com/7253922/232238489-7acd5258-3239-45e4-b199-73213db6df22.png">

**Comment by kaikyoofers** [comment]
> http://free.fullspeed.tv/iptv-query?streaming-ip=https://youtube.com/c/%E5%AF%B0%E5%AE%87%E6%96%B0%E8%81%9E%E9%A0%BB%E9%81%93/live (offline)
> <img width="833" alt="image" src="https://user-images.githubusercontent.com/7253922/232238489-7acd5258-3239-45e4-b199-73213db6df22.png">
> 

Its because free fullspeed shutdown

**Comment by kaikyoofers** [comment]
> http://free.fullspeed.tv/iptv-query?streaming-ip=https://youtube.com/c/%E5%AF%B0%E5%AE%87%E6%96%B0%E8%81%9E%E9%A0%BB%E9%81%93/live (offline)
> <img width="833" alt="image" src="https://user-images.githubusercontent.com/7253922/232238489-7acd5258-3239-45e4-b199-73213db6df22.png">
> 

New url: http://ythls.onrender.com/channel/UCp2f7tGJGN6R9Muxipem8Nw.m3u8
