### ISSUE TITLE
Reclassify EWTN under the religious section

### ISSUE THREAD

**Issue by pgiffuni** [iptv-org/iptv#10039]
### Describe your issue

Minor issue, in the Colombia playlist I see:
EWTN el Canal Católico (720p) [Not 24/7]

Please note that this is a Catholic channel so it should belong to the Religious section.
At least I would find it easier there.

While here, if you could add RetroPlus3 to the Colombia playlist (movies section), it would be nice.

Huge thanks for maintaining these lists!

**Comment by LaneSh4d0w** [comment]
I'll take a look over the database see if this channel is named or not. Then i'll take a look over the playlists to see if it's correctly identified as is.

**Comment by LaneSh4d0w** [comment]
Fix has been deployed on the database, should be reflected on next playlist update.

**Comment by Alstruit** [comment]
> ### Describe your issue
> Minor issue, in the Colombia playlist I see: EWTN el Canal Católico (720p) [Not 24/7]
> 
> Please note that this is a Catholic channel so it should belong to the Religious section. At least I would find it easier there.
> 
> While here, if you could add RetroPlus3 to the Colombia playlist (movies section), it would be nice.
> 
> Huge thanks for maintaining these lists!

Please make a seperate request for RetroPlus3.
Marking as resolved. iptv-org/database#1103
