### ISSUE TITLE
Replace: AMC East

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#10038]
### Broken Link

https://bcovlive-a.akamaihd.net/ebf15ff84e98490e8b00209ed77c77f5/us-east-1/6240731308001/playlist.m3u8

### What happened to the stream?

Not loading

### Notes

Nothing: geo-blocked? (from Canada)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Alstruit** [comment]
Closing in favor #10476

**Comment by AntiPontifex** [comment]
Thanks for fixing it.
