### ISSUE TITLE
Add: AYV TV [SL]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10032]
### Channel ID

AYVTV.sl

### Stream URL

https://1219373429.rsc.cdn77.org/live/stream-1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Not quite sure what this is ... but it sure isn't AYV TV that's being streamed.

**Comment by Carlinhos027** [comment]
> It is mate. AYV Channel 33:
https://ayvnews.com/

**Comment by Carlinhos027** [comment]
> Not quite sure what this is ... but it sure isn't AYV TV that's being streamed.

It is mate. AYV Channel 33:
https://ayvnews.com/
