### ISSUE TITLE
Add: TVC

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#10049]
### Channel ID

TVC.ec

### Stream URL

https://d6op0qag07k4o.cloudfront.net/hls/tvc_480.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://d6op0qag07k4o.cloudfront.net/hls/tvc.m3u8
