### ISSUE TITLE
Add: RTS

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#10047]
### Channel ID

RTS.ec

### Stream URL

https://d6op0qag07k4o.cloudfront.net/hls/rts_480.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://d6op0qag07k4o.cloudfront.net/hls/rts.m3u8
