### ISSUE TITLE
Replace: Animax (720p)

### ISSUE THREAD

**Issue by baliebox4916** [iptv-org/iptv#10059]
### Broken Link

https://cdn.us195.jpnettv.live/jptv/janimax_720/playlist.m3u8

### What happened to the stream?

Displays a message asking to renew subscription

### Notes

I Cant Seem to Find a Stream Other Than This

But This is the Chance for us to Finally Have a Proper English Sub of Animax (IE a REAL Anime Channel)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Apart of waiting, we can't do much.

**Comment by AzeemHadzrie** [comment]
Still works on my side, using VLC.

**Comment by baliebox4916** [comment]
Yeah Its Fixed Now
