### ISSUE TITLE
Record TV

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#10055]
### Channel ID

RecordTV.br

### Stream URL

https://cdn.jmvstream.com/w/LVW-10842/LVW10842_513N26MDBL/chunklist.m3u8

### Notes

Valid

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Which Record channel? The national feed?

**Comment by darrencycheung** [comment]
National standard feed

**Comment by freearhey** [comment]
https://cdn.jmvstream.com/w/LVW-10842/LVW10842_513N26MDBL/chunklist.m3u8
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/7253922/232238519-2d75fd2b-fb21-4e76-a160-a994d9bde5ff.png">

**Comment by kaikyoofers** [comment]
I dont think this is the right RecordTV

**Comment by freearhey** [comment]
https://cdn.jmvstream.com/w/LVW-10842/LVW10842_513N26MDBL/chunklist.m3u8
<img width="785" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/5f85e388-0b7d-4bde-8588-0e076731ecce">
