### ISSUE TITLE
Add: Izabal TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#10085]
### Channel ID

IzabalTV.gt

### Stream URL

https://edge1o.live.opencaster.com/caster/prBnCDnEGEkE.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Sadly we can't deal with Opencaster links. Closing.
