### ISSUE TITLE
Please add indonesian subtitle

### ISSUE THREAD

**Issue by ardhiciu** [iptv-org/iptv#1009]
Please add some movie channel like hbo with indonesian subtitle..

**Comment by freearhey** [comment]
You mean HBO Asia? https://hboasia.com/HBO/en-id

**Comment by null2264** [comment]
I've been search for the source of movie channels such as Fox or HBO, i did found some and added it to this repo at one point but the source keep changing... I'll keep searching but right now its almost impossible to find reliable source.
Oh yeah, MNCNow have one before it blocked the link from public...
