### ISSUE TITLE
Add: Blue Sky TV

### ISSUE THREAD

**Issue by Playe4** [iptv-org/iptv#10109]
### Channel ID

BlueSkyTV.gr

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Added for next release.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/861169502d1e8d6e9de628a930170308b7d0353a/streams/gr.m3u#L34-L35
