### ISSUE TITLE
Add:TRT

### ISSUE THREAD

**Issue by Playe4** [iptv-org/iptv#10104]
### Channel ID

TRTTV.gr

### Notes

broadcast_area: Greece
languages: Greek
is_nsfw: false
launched: 5 February 1990

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Added for next release.
