### ISSUE TITLE
Add: Syros TV1

### ISSUE THREAD

**Issue by Playe4** [iptv-org/iptv#10112]
### Channel ID

SyrosTV1.gr

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Added for next release.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/gr.m3u#L192-L193
