### ISSUE TITLE
Raj News Malayalam HD 

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#10128]
### Channel ID

RajNewsMalayalam.in

### Stream URL

https://www.youtube.com/watch?v=Xtm0_LGYmIs&ab_channel=RajNewsMalayalam

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://www.youtube.com/@RajNewsMalayalamOnline/live

**Comment by Manipulativemachan** [comment]
Any idea how to get ylivestream links? Like the one below?

https://rajnewsmalayalam.ylivestream.com/rajnewsmalayalam/index.m3u8

**Comment by Manipulativemachan** [comment]
> http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCfPag4Qmnif6fw25HEIqF6w/live

Why this is not working anymore?

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCfPag4Qmnif6fw25HEIqF6w/live (offline)
<img width="810" alt="image" src="https://user-images.githubusercontent.com/7253922/232238547-aa8cf38c-d7a2-4bc9-8938-fa78ba283171.png">

https://rajnewsmalayalam.ylivestream.com/rajnewsmalayalam/index.m3u8
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/7253922/232238560-6105697e-ad3d-43ea-a9a0-d0b4327740af.png">
