### ISSUE TITLE
Add: Fox 5 New York (WNYW)

### ISSUE THREAD

**Issue by Arkina1234** [iptv-org/iptv#10120]
### Channel ID

Fox Affiliate

### Stream URL

https://foxvideo.akamaized.net/fast/wnyw/index.m3u8?ad_env=1&_fw_ae=1bca1f19874e40b3675ef125882715a5&_fw_did=43e6834d-5e32-4516-959c-ba35e960e17e&_fw_seg=&_fw_us_privacy=1---&_fw_vcid2=516429%3A43e6834d-5e32-4516-959c-ba35e960e17e&ad=fw_prod&ad.csid=foxnow%2Fwebdesktop%2Flive%2Ffox&ad.flags=+slcb+sltp+qtcb+emcr+fbad+dtrd+vicb&ad.prof=516429%3Ayospace_foxnow_webdesktop_live&cdn=ak&exp=1667921066&fnl-affiliate=WNYW&fs-affiliate=WNYW&traceid=watch-b7ba17804ebf9fc0&yo.ac=true&yo.pdt=true&yo.ug=10013&hdnts=exp=1667921127~acl=/*~hmac=a6e90bad9596dce3291118de5a9c7ba30cc713bc6ed872a0fadeb556fd859b6b&headerbidding=%26_fw_is_lat%3D0

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Please see #9265. Closing as duplicate
