### ISSUE TITLE
Add: Naftemporiki TV

### ISSUE THREAD

**Issue by Playe4** [iptv-org/iptv#10121]
### Channel ID

NaftemporikiTV.gr

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Added for next release: please close.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/gr.m3u#L176-L177
