### ISSUE TITLE
Add: Euro TV

### ISSUE THREAD

**Issue by Playe4** [iptv-org/iptv#10142]
### Channel ID

EuroTV.gr

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by ztreamhd** [comment]
EuroChannel (720p): http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/eurochannel

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be added next update.
