### ISSUE TITLE
Add: Ioannina TV

### ISSUE THREAD

**Issue by Playe4** [iptv-org/iptv#10146]
### Channel ID

IoanninaTV.gr

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by ztreamhd** [comment]
Check this out, it might work only on Greece
rtmp://eco.streams.ovh:1935/ioanninatv/live

**Comment by AntiPontifex** [comment]
Already on list: under Ionian Channel. Please close.
