### ISSUE TITLE
Add: Flash TV

### ISSUE THREAD

**Issue by Playe4** [iptv-org/iptv#10144]
### Channel ID

Flash-TV.gr

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by ztreamhd** [comment]
Flash TV (720p): http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/flashtvgr
