### ISSUE TITLE
Replace: Replace PTV Sports please

### ISSUE THREAD

**Issue by SoulReaper1996** [iptv-org/iptv#10147]
### Broken Link

http://103.81.104.118/hls/stream11.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Ctgbdkd** [comment]
Not working

**Comment by Easyfiv3** [comment]
https://github.com/iptv-org/iptv/issues/10792

**Comment by freearhey** [comment]
Closed in favor of #10792
