### ISSUE TITLE
Add: ITV

### ISSUE THREAD

**Issue by Shuggy999** [iptv-org/iptv#10164]
### Channel ID

ITV.uk

### Stream URL

https://cdnuk001.broadcastcdn.net/KUK-ITV-107/tracks-v1a1/mono.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://cdnuk001.broadcastcdn.net/KUK-ITV-107/tracks-v1a1/index.m3u8
