### ISSUE TITLE
Add: Channel 4

### ISSUE THREAD

**Issue by Shuggy999** [iptv-org/iptv#10169]
### Channel ID

Channel4.uk

### Stream URL

https://cdnuk001.broadcastcdn.net/KUK-CHANNEL4/tracks-v1a1/mono.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by eklins** [comment]
http://prox.x86.co.uk/index.php/https://cdnuk001.broadcastcdn.net/KUK-CHANNEL4/tracks-v1a1/mono.m3u8

**Comment by Alstruit** [comment]
https://cdnuk001.broadcastcdn.net/KUK-CHANNEL4/tracks-v1a1/index.m3u8
