### ISSUE TITLE
Replace: BBC World News

### ISSUE THREAD

**Issue by applecuckoo** [iptv-org/iptv#10174]
### Broken Link

http://ott-cdn.ucom.am/s24/index.m3u8

### What happened to the stream?

Constantly interrupts/lagging

### Notes

Occasionally comes up with a testcard, audio glitches. I will update with a video clip if I can catch it happening.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by darrencycheung** [comment]
http://198.16.64.10:8278/bbcnews_twn/playlist.m3u8?tid=ME2E9411781394117813&ct=19225&tsum=ffaa2caa60183eec89d730ed80b336d1

**Comment by Alstruit** [comment]
Links looks fine, closing.
