### ISSUE TITLE
Some Iranian channels like Radio Javan and Iran International are filtered in Iran, please fix it.

### ISSUE THREAD

**Issue by Kinggmahdi** [iptv-org/iptv#10176]
### Broken Link

https://stream.rjtv.tv/live/smil:rjtv.smil/playlist.m3u8

### What happened to the stream?

Not loading

### Notes

Some Iranian channels like Radio Javan and Iran International are filtered in Iran, please fix it.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Alstruit** [comment]
Please read the Contributing Guide.
