### ISSUE TITLE
Add: Dave

### ISSUE THREAD

**Issue by Shuggy999** [iptv-org/iptv#10170]
### Channel ID

Dave.uk

### Stream URL

https://cdnuk001.broadcastcdn.net/KUK-DAVEJAVU/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by eklins** [comment]
http://prox.x86.co.uk/index.php/https://cdnuk001.broadcastcdn.net/KUK-DAVEJAVU/index.m3u8

**Comment by Shuggy999** [comment]
Thank you for the replies on my threads.
Is there anyway to add these URLs to the main _"uk.m3u"_ script?

**Comment by Alstruit** [comment]
Already Exists, closing.

**Comment by smeilet** [comment]
NOT email send to me
________________________________
Von: Alstruit ***@***.***>
Gesendet: Donnerstag, 24. November 2022 22:23 Uhr
An: iptv-org/iptv ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [iptv-org/iptv] Add: Dave (Issue #10170)


Closed #10170<https://github.com/iptv-org/iptv/issues/10170> as completed.
