### ISSUE TITLE
Add: TVR 1

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#10239]
### Channel ID

TVR1.ro

### Stream URL

https://mn-nl.mncdn.com/tvr1_hd_live/smil:tvr1_hd_live.smil/index.m3u8

### Notes

#DIGI

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
By deduction : 

TVR2 : https://mn-nl.mncdn.com/tvr2_test/smil:tvr2_test.smil/playlist.m3u8
TVR3 : https://mn-nl.mncdn.com/tvr3_test/smil:tvr3_test.smil/index.m3u8

**Comment by Smark223** [comment]
Also:

TVR2: https://mn-nl.mncdn.com/tvr2_hd_live/smil:tvr2_hd_live.smil/index.m3u8
TVR3: https://mn-nl.mncdn.com/tvr3_hd_live/smil:tvr3_hd_live.smil/index.m3u8

**Comment by LaneSh4d0w** [comment]
> Also:
> 
> TVR2: https://mn-nl.mncdn.com/tvr2_hd_live/smil:tvr2_hd_live.smil/index.m3u8 TVR3: https://mn-nl.mncdn.com/tvr3_hd_live/smil:tvr3_hd_live.smil/index.m3u8

These ones don't seem to answer, the ones I've linked above are the ones that TVR actively uses.

**Comment by Smark223** [comment]
> > Also:
> > TVR2: https://mn-nl.mncdn.com/tvr2_hd_live/smil:tvr2_hd_live.smil/index.m3u8 TVR3: https://mn-nl.mncdn.com/tvr3_hd_live/smil:tvr3_hd_live.smil/index.m3u8
> 
> These ones don't seem to answer properly (empty m3u), the ones I've linked above are the ones that TVR actively uses.

Ah ok, thanks. I hadn't realised.
