### ISSUE TITLE
Add: Canal 3 [GT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10260]
### Channel ID

Canal3.gt

### Stream URL

https://dslvfq5ee0geu.cloudfront.net/hls/canal3_360.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Included in next update: thank you.
