### ISSUE TITLE
Add: Full Channel [GT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10266]
### Channel ID

FullChannel.gt

### Stream URL

https://cdn.streamhispanatv.net:3845/live/fullchannelgtlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Duplicate of #10084; please close.
