### ISSUE TITLE
Add: Telemax [GT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10269]
### Channel ID

Telemax.gt

### Stream URL

https://cdn.streamhispanatv.net:3824/live/telemaxlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Duplicate of #10091; please close.
