### ISSUE TITLE
Add: Telecosta [GT] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10268]
### Channel ID

Telecosta.gt

### Stream URL

https://tv91.hostingnuclear.com:19360/telecosta/telecosta.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Not 24/7 ?

**Comment by AntiPontifex** [comment]
Included in next update: thank you.
