### ISSUE TITLE
Add: Unica TV [GT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10273]
### Channel ID

UnicaTV.gt

### Stream URL

https://cdn.streamhispanatv.net:3642/live/unicatvlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Duplicate stream; please close.
