### ISSUE TITLE
Add: NW Info [TG]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10276]
### Channel ID

NWInfo.tg

### Stream URL

https://hls.newworldtv.com/nw-info/video/live.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream doesn't work
