### ISSUE TITLE
Add: Tunevision [GT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10272]
### Channel ID

Tunevision.gt

### Stream URL

https://cdn.streamhispanatv.net:3852/live/tunevisionlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Duplicate of #10093; will be included in future gt.m3u update. Please close.
