### ISSUE TITLE
Add: Televisiete [GT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10270]
### Channel ID

Televisiete.gt

### Stream URL

https://dslvfq5ee0geu.cloudfront.net/hls/canal7_360.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://dslvfq5ee0geu.cloudfront.net/hls/canal7.m3u8

**Comment by AntiPontifex** [comment]
Included in next update: thank you.
