### ISSUE TITLE
Add: Vision TV [GT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10274]
### Channel ID

VisionTV.gt

### Stream URL

https://cdn.streamhispanatv.net:3076/live/visiontvlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Duplicate stream; will be on gt.m3u in future update.
