### ISSUE TITLE
Add: TN 23 [GT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10271]
### Channel ID

TN23.gt

### Stream URL

https://dslvfq5ee0geu.cloudfront.net/hls/canal23_360.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://dslvfq5ee0geu.cloudfront.net/hls/canal23.m3u8

**Comment by AntiPontifex** [comment]
Duplicate of #1002; please close.
