### ISSUE TITLE
Add: Excelsior TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#10275]
### Channel ID

ExcelsiorTV.mx

### Stream URL

https://youtu.be/7aswTQAb3Og

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://youtube.com/c/excelsiortv/live

**Comment by AntiPontifex** [comment]
Thanks
