### ISSUE TITLE
Add: MVM Noticias

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#10285]
### Channel ID

MVMNoticias.mx

### Stream URL

https://dish.akamaized.net/Content/HLS_HLS_CLR/Live/channel(mvs)/variant.m3u8

### Notes

?Uncertain about stream?

Geo-blocked?

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by makionter** [comment]
Has encontrado el resto de transmisiones?

**Comment by R4IN2007** [comment]
Geo-blocked 
Mexico VPN IP works
Sirve muy bien
![Screenshot_20240127_205203_Chrome](https://github.com/iptv-org/iptv/assets/83226646/93c5576d-6f06-401a-9c1c-2a76459716b4)
