### ISSUE TITLE
Replace: Rewind TV (WPIX)

### ISSUE THREAD

**Issue by Sophgirl41** [iptv-org/iptv#10291]
### Broken Link

http://v-ny.theus6tv.duckdns.org/hls/11.4/playlist.m3u8

### What happened to the stream?

Other

### Possible Replacement

http://v-ny.theus6tv.duckdns.org/hls/11.4/playlist.m3u8

### Notes

Stream quite working 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Not linked to @MapGuy11 , backend issue over the stream.

**Comment by LaneSh4d0w** [comment]
Channel went back, closing this.
