### ISSUE TITLE
Add: Enlace [CR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10298]
### Channel ID

Enlace.cr

### Stream URL

https://11554-1.b.cdn13.com/LiveHTTPOrigin/live/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already in list.
