### ISSUE TITLE
Add: HOY Infotainment Channel

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#10292]
### Channel ID

HOYInfotainmentChannel.hk

### Stream URL

_https://hoytv-live-stream.hoy.tv/ch78/index-fhd.m3u8_

### Notes

New channel
To be launched on Nov 21st
m3u8 plz
https://kbysradio.files.wordpress.com/2022/10/mmexport1666072168305.png?w=1100
I hope uc6 icable m3u8 and other related

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by darrencycheung** [comment]
https://m.youtube.com/watch?v=FEOQ034fH_4

**Comment by darrencycheung** [comment]
https://m.youtube.com/watch?v=S4nCX07bV-o

**Comment by darrencycheung** [comment]
http://epg.i-cable.com/new/images/epgMobileIcon/002.png?ts=1998160755

**Comment by darrencycheung** [comment]
The stream link is geo-blocked

**Comment by darrencycheung** [comment]
Please help me!

**Comment by Alstruit** [comment]
I would advise against spamming further requests. It will be added, please be patient.
