### ISSUE TITLE
Add: Anexion TV [CR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10297]
### Channel ID

AnexionTV.cr

### Stream URL

https://liveingesta119.cdnmedia.tv/trivision36live/dvrlive-1500/chunklist.m3u8?DVR

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Included in the next update: thank you.
