### ISSUE TITLE
Add: Oldies Hits [CR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10306]
### Channel ID

OldiesHits.cr

### Stream URL

https://video01.logicahost.com.br/oldieshits/oldieshits/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Duplicate of #9919: please close.
