### ISSUE TITLE
Add: Los Santos TV [CR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10304]
### Channel ID

LosSantosTV.cr

### Stream URL

https://lstv.duckdns.org:449/hls/lstv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Duplicate of #9915: please close.
