### ISSUE TITLE
Add: Sarapiqui TV [CR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10308]
### Channel ID

SarapiquiTV.cr

### Stream URL

https://lstv.duckdns.org:449/hls/stv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Duplicate of #9923: please close.
