### ISSUE TITLE
Add: Guatuso TV [CR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10303]
### Channel ID

GuatusoTV.cr

### Stream URL

https://5cf4a2c2512a2.streamlock.net/8162/8162/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Duplicate of #9914: please close.

**Comment by smeilet** [comment]
Hello
Please not Email send to me
Thanks

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
