### ISSUE TITLE
Add: HBTV TicaVision [CR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10301]
### Channel ID

HBTVTicaVision.cr

### Stream URL

https://62fc643fbf1aa.streamlock.net/HBTV/HBTV/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Included in the next update: thank you.
