### ISSUE TITLE
Add: San Vito Television [CR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10307]
### Channel ID

SanVitoTelevision.cr

### Stream URL

https://stmv.streamingvip.click/sanvitotv/sanvitotv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Duplicate of #9922: please close.
