### ISSUE TITLE
Add: IQ Channel [CR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10302]
### Channel ID

IQChannel.cr

### Stream URL

https://rtmp.info/iqtv/envivo/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Included in the next update: thank you.
