### ISSUE TITLE
Add: Luz Naciente TV [CR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10305]
### Channel ID

LuzNacienteTV.cr

### Stream URL

https://vdo.luznacientetv.com:3555/live/luznacientetvlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Duplicate of #9916: please close.
