### ISSUE TITLE
Add: Zee News

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#10300]
### Channel ID

ZeeNews.in

### Stream URL

https://d233nwklwv8p4.cloudfront.net/out/v1/860cb318d23a4c64b58c9d625281170c/index_3.m3u8

### Notes

Zee Business
https://d8gy12azhr71i.cloudfront.net/out/v1/45be109c5b4f44319e882da947377364/index_3.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://d233nwklwv8p4.cloudfront.net/out/v1/860cb318d23a4c64b58c9d625281170c/index_3.m3u8
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/7253922/232244715-116911de-5f53-417b-abe7-c716275bcba0.png">
