### ISSUE TITLE
Add: TV Cuatro 4.2

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#10314]
### Channel ID

TVCuatro42.mx

### Stream URL

https://5f2c1b0d880e5.streamlock.net/tv42/smil:tv42.smil/chunklist_w1716445737_b2428000_sleng.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://5f2c1b0d880e5.streamlock.net/tv42/smil:tv42.smil/playlist.m3u8
