### ISSUE TITLE
Add: Al Jazeera English Cloudfront m3u8

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#10310]
### Channel ID

AlJazeeraEnglish.qa

### Notes

Cloudfront m3u8 plz
Amazonaws

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Al Jazeera English already exists and works. Closing.

**Comment by smeilet** [comment]
Hello
Please not Email send to me
Thanks

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
