### ISSUE TITLE
Add: TV Cuatro 4.3

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#10315]
### Channel ID

TVCuatro43.mx

### Stream URL

https://5f1af61612fb5.streamlock.net/tv43/smil:tv43.smil/chunklist_w121612537_b2428000_sleng.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://5f1af61612fb5.streamlock.net/tv43/smil:tv43.smil/playlist.m3u8
