### ISSUE TITLE
 News 12 IPTV Channels

### ISSUE THREAD

**Issue by Pjryb90** [iptv-org/iptv#1031]
Seems like the ones that work aren’t streaming smoothly. Any way to fix that?

**Comment by freearhey** [comment]
Could you specify which country we are talking about? 

The fact is that the channels called "News 12" are present in multiple playlists.

**Comment by Pjryb90** [comment]
New Jersey and tri-State area. (West Chester, Bronx, Brooklyn, and Connecticut is what I’ve seen.)

**Comment by Pjryb90** [comment]
That’s in the US by the way.

**Comment by freearhey** [comment]
We can't influence the quality of the broadcast in any way, but if some other variant appears, we will add it to the playlist.

**Comment by Pjryb90** [comment]
What are the chances another variant appears?

**Comment by freearhey** [comment]
I don't know.

**Comment by Pjryb90** [comment]
How about channels from the Philippines? Any available in your lists?

**Comment by freearhey** [comment]
@Pjryb90 Here's a list of all playlists sorted by country: https://github.com/iptv-org/iptv#playlists-by-country

**Comment by Pjryb90** [comment]
10 channels from that country then correct?

**Comment by freearhey** [comment]
Correct

**Comment by bermufine** [comment]
Please
Can you add more m3u8 code channels from Democratic Republic of Congo (DRC)
Like:
Pstv
Ctv
Digital-congo 
Rtmc 1 & 2
Heritage tv
Nyota tv
Antenne A
Rtga
Kin24
CCTV
Congoweb tv
Congo world tv
Tele 50
B-one tv
And so more......

**Comment by themak1985** [comment]
The News 12 channels work fine for me @freearhey - The streams are HD - I could see how someone with limited bandwidth would have issues. I think this issue can be closed.
