### ISSUE TITLE
Fix: INEZ.fi

### ISSUE THREAD

**Issue by las-pen** [iptv-org/iptv#10321]
### Describe your issue

The stream works just fine, yet the bot is constantly reporting it to be in error. https://inezsecondary.digitacdn.net/live/_definst_/inez/amlst:inezlive.amlst/master.m3u8

**Comment by kaikyoofers** [comment]
It is a error
![Screenshot_20221114-100458_Chrome](https://user-images.githubusercontent.com/67206080/201667806-09f080d4-ec22-4579-8c0e-c4abfa30cfd3.jpg)

**Comment by LaneSh4d0w** [comment]
Works for me.

**Comment by las-pen** [comment]
Tested with VPN. Seems it's Geo-Blocked nowadays.
