### ISSUE TITLE
Please Add more Cricket Channels

### ISSUE THREAD

**Issue by SoulReaper1996** [iptv-org/iptv#10323]
### Channel ID

InternationalCricket

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Please read the [contributing guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md) before posting an issue or a PR.
