### ISSUE TITLE
Redesign the new feature release

### ISSUE THREAD

**Issue by kalicsv** [iptv-org/iptv#1032]
My problem is that it is a bit slow to use your country's network. After all, we are in China. We will make another IP distribution to broadcast TV and distribute it to me! Thank you!

**Comment by kalicsv** [comment]
My problem is that it is a bit slow to use your country's network. After all, we are in China. We will make another IP distribution to broadcast TV and distribute it to me! Thank you!




---Original---

**Comment by freearhey** [comment]
This repository only contains links to public television broadcasts. We do not control the broadcasts themselves in any way and cannot influence their quality.

**Comment by kalicsv** [comment]
Upstream, when will the new features merge? When should it be released and how should it be operated?




---Original---

**Comment by kalicsv** [comment]
All right, thank you. At the same time, we will create a better future together. We will cooperate and maintain a win-win situation. At the same time, we also thank you for your support and efforts. Thank you for your patience.




---Original---
