### ISSUE TITLE
Add: Tele Yucatan

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#10333]
### Channel ID

XHSTTDT.mx

### Stream URL

https://5ca3e84a76d30.streamlock.net/teleyucatan/videoteleyucatan/chunklist_w1209952025.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MTEvMTMvMjAyMiA5OjQ3OjMwIFBNJmhhc2hfdmFsdWU9ZWYwaWtROGc3aUwvY09UYkdyVjN6QT09JnZhbGlkbWludXRlcz0xMCZpZD0%3D

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=http://conceptoweb-studio.com/radio/video/trecevision/

**Comment by AntiPontifex** [comment]
Thank you, Lane.
