### ISSUE TITLE
Add: XHPBZCTDT.mx

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#10343]
### Channel ID

XHPBZCTDT.mx

### Stream URL

https://5d0d1d7a6be9e.streamlock.net/envivo/puecom/chunklist_w966595294.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
L134-L135 mx.m3u
