### ISSUE TITLE
Misidentified: History East

### ISSUE THREAD

**Issue by ilikenwf** [iptv-org/iptv#10350]
### Broken Link

https://bk7l2w4nlx53-hls-live.5centscdn.com/HISTORY/961ac1c875f5884f31bdd177365ef1e3.sdp/playlist.m3u8

### What happened to the stream?

Shows the wrong channel

### Notes

Appears listed as "History (Best Of)" elsewhere. This isn't the live TV channel, and thus shows incorrect EPG info from the EPG repo as well. Right now it is airing some Ancient Aliens spinoff...

I have not yet located an alternative for the actual History channel, but this one needs renamed to "Best Of" or whatever the real name is.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by benevenstanciano** [comment]
I think the channel is called History Classics. It's available on the History Channel's website for free.

**Comment by TKList** [comment]
History Mashup

**Comment by ilikenwf** [comment]
Makes sense, it would be nice to rename it if possible...I'm using a modified xteve right now to handle this and other lists without duplication issues with the id hashes, and while I could internally rename it, adjusting it here and on the EPG would be better.

**Comment by freearhey** [comment]
Link removed from playlist.
