### ISSUE TITLE
Add: Canal Pro

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#10367]
### Channel ID

CanaPro.py

### Stream URL

https://youtu.be/zVTV72Pgn8U?list=TLGGUxgFOZ-9n04xNjExMjAyMg

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UC1Oj-Sh9iWR3wOg7C6W9kmQ/live
