### ISSUE TITLE
Add: Senado TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#10370]
### Channel ID

SenadoTV.py

### Stream URL

https://youtu.be/b7clP1AZxjs

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/SenadoTVpy/live
