### ISSUE TITLE
Add: CN TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#10382]
### Channel ID

CNTV.pe

### Stream URL

https://tv.inka.net.pe/cntv/tracks-v1a1/mono.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://tv.inka.net.pe/cntv/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thanks, Lane.
