### ISSUE TITLE
Add: west coast big 4 TV feeds.

### ISSUE THREAD

**Issue by playxx** [iptv-org/iptv#10383]
### Channel ID

KPIX...

### Notes

Anyone has current west coast big 4 feeds?

The old list at: 
https://github.com/iptv-org/iptv/pull/6938
is not working anymore.
eg. 
CBS KPIX : http://51.161.118.146:8080/ISG03_CBS_SAN_FRANCISCO_CA_KPIX/video.m3u8, etc.
thanks.

### Please confirm the following

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
KPIX is available through LocalBTV, <html><body>
162 | 1080p | CBS | San Francisco | CA | KPIX-TV | 5.1 | English |   | https://www.nicepng.com/png/full/443-4431727_cbs-logo-png.png | Local
