### ISSUE TITLE
Add: Mexico Travel Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#10391]
### Channel ID

MexicoTravelChannel.mx

### Stream URL

https://5ca9af4645e15.streamlock.net/mexicotravel/videomexicotravel/chunklist_w2125866842.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MTEvMTQvMjAyMiA4OjAwOjMzIFBNJmhhc2hfdmFsdWU9Z0V1RG9LejBmV0dDRXJibm5POTRjZz09JnZhbGlkbWludXRlcz0xMCZpZD0%3D

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://conceptoweb-studio.com/radio/video/mexicotravel/

**Comment by AntiPontifex** [comment]
Thanks for the correction.
