### ISSUE TITLE
Add: FCTV Public Channel 13

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#10408]
### Channel ID

FCTVPublicChannel13.us

### Stream URL

https://reflect-falmouth.cablecast.tv/live-17/live/live.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://reflect-falmouth.cablecast.tv/live-17/live/live.m3u8
