### ISSUE TITLE
Add: RT en Español

### ISSUE THREAD

**Issue by saidma** [iptv-org/iptv#10413]
### Channel ID

RTenEspanol.ru

### Stream URL

https://odysee.com/@ActualidadRT:9/rt_transmision_en_vivo:e

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
https://cdn.odysee.live/content/9f638b94d11d879726ae55dd5a0923621b96a45b/master.m3u8
