### ISSUE TITLE
Add: RTS [EC]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10423]
### Channel ID

RTS.ec

### Stream URL

https://d6op0qag07k4o.cloudfront.net/hls/rts.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Duplicate of #10047; please close.
