### ISSUE TITLE
Add: TVC [EC]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10424]
### Channel ID

TVC.ec

### Stream URL

https://d6op0qag07k4o.cloudfront.net/hls/tvc.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Duplicate of #10049; please close.
