### ISSUE TITLE
Add: Canal Capital [CO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10421]
### Channel ID

CanalCapital.co

### Stream URL

https://play.cdn.enetres.net/C99D9A0676F3401589C768D47D31605C021/021/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Duplicate of #9906: please close.
