### ISSUE TITLE
Update Romanian chanels please

### ISSUE THREAD

**Issue by Boston27** [iptv-org/iptv#1042]

**Comment by freearhey** [comment]
What exactly is wrong with the current playlist?

**Comment by Boston27** [comment]
Its all good  you do an great job !But  for example the news channel Digi
24 its not working anymore .... And its an very good Chanel for the people
who are not in Romania !
If not can you please to check for another channels like  Antena1. , Pro tv
, Kanal D  all Romanians very good channels!
Thank you very for all and respect for your job !!! God bless you!

**Comment by freearhey** [comment]
Duplicate #762

**Comment by willrock74** [comment]
Hrllo, you are doing a good job and thank you, however, I would like to look at the list of channels below....
if you can add channels: ANTENA 1, PROTV, KANAL D, PRIMA TV...


[romanian channel list 2020.txt](https://github.com/iptv-org/iptv/files/4335198/romanian.channel.list.2020.txt)

**Comment by bordesti968** [comment]
Hello you done good job 🍺🍺🍺🍺 how can i get the list??

**Comment by Andrei1997vlaad** [comment]
Nu îmi merge ProTV    am in cercat niste coduri    de  la voi dar nu fuctioneaza
