### ISSUE TITLE
Add: SoriTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#10438]
### Channel ID

SoriTV.pe

### Stream URL

https://cadenasurrtv.com/hls/stream/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Doesn't work for now. Not 24/7 ?

**Comment by AntiPontifex** [comment]
It was working when i tested it: so likely not 24/7, Lane. Whoops.
