### ISSUE TITLE
Add: SEO TV Deportes [BO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10443]
### Channel ID

SEOTVDeportes.bo

### Stream URL

https://seo.tv.bo/tv/DEPX.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
This one is streaming Music right now.

**Comment by AntiPontifex** [comment]
Will be in next update: please close.

**Comment by Alstruit** [comment]
Shouldn't it be https://live.seo.tv.bo/live/5SEO.m3u8 ?
