### ISSUE TITLE
Add: Canal 2 [CO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10445]
### Channel ID

Canal2.co

### Stream URL

https://video13.virtualtronics.com/streamer/canal2.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Included in the next update: thank you.
