### ISSUE TITLE
Add: Canal Cartagena [CO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10446]
### Channel ID

CanalCartagena.co

### Stream URL

https://edge.teveo.com.co/live/AeAAAgAlAANrA1IAyADIQCAAAAAAAAAAAmN5-m6wVnhmAAAA/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://q-s-l4n3sh4d0w.onrender.com/iptv-query?streaming-ip=https://teveo.com.co/player/AcAAAgAlAANrA1IAyADIQCAAAAAAAAAA.js

**Comment by LaneSh4d0w** [comment]
Not 24/7 ("Esta en el senal Online, ahora somos fuera del aire" with one of their presenters announcing.)

**Comment by AntiPontifex** [comment]
Duplicate of #9815: please close.
