### ISSUE TITLE
Add: CNC Medellin [CO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10447]
### Channel ID

CNCMedellin.co

### Stream URL

http://cncmedellin.ddns.net:1935/canalcnc/canalcnc_360p/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Included in the next update: thank you.
