### ISSUE TITLE
Add: CNC Monteria [CO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10448]
### Channel ID

CNCMonteria.co

### Stream URL

https://cloud28.vsgtech.co:3932/live/cncmonterialive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
I've seen a few "vsgtech" streams pop off here. Is it a big streaming company ?

I don't know if @sguinetti or @thetucan1 has the answer to that question;

**Comment by LaneSh4d0w** [comment]
Doesn't seem to work for now.

**Comment by LaneSh4d0w** [comment]
Another stream it wants to pop off is this one : https://cloud28.vsgtech.co:3932/stream/play.m3u8

**Comment by LaneSh4d0w** [comment]
My bad, seems I had a restricted connection. Works for me.

**Comment by AntiPontifex** [comment]
Duplicate of #9819: please close.
