### ISSUE TITLE
Add: SEO TV [BO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10440]
### Channel ID

SEOTV.bo

### Stream URL

https://seo.tv.bo/tv/SEOX.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Will be in next update: please close.
