### ISSUE TITLE
Replace: 8 Mont Blanc

### ISSUE THREAD

**Issue by aeolai1** [iptv-org/iptv#10453]
### Broken Link

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/tv8montblanc-wizdeo

### What happened to the stream?

Not loading

### Possible Replacement

https://www.dailymotion.com/cdn/live/video/x71o73v.m3u8?sec=LFtxI_BCdZRPgAj4gUJaupKPV3K1GZJ9QvUxlmcW_SBex8auA6zu062OyCypoXw_uTtfOCAmKgjdQ44BeF34Cg&dmTs=755518&dmV1st=9C87253E1D729419982423FC2C395C3E&progressive=1

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x71o73v

**Comment by LaneSh4d0w** [comment]
For now they don't seem to stream anything, that might be why nothing works.

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/tv8montblanc

**Comment by freearhey** [comment]
https://www.dailymotion.com/cdn/live/video/x71o73v.m3u8?sec=LFtxI_BCdZRPgAj4gUJaupKPV3K1GZJ9QvUxlmcW_SBex8auA6zu062OyCypoXw_uTtfOCAmKgjdQ44BeF34Cg&dmTs=755518&dmV1st=9C87253E1D729419982423FC2C395C3E&progressive=1 (offline)
<img width="825" alt="image" src="https://user-images.githubusercontent.com/7253922/232242245-4e4dbf07-1163-4b39-85e4-c8b9c78aadec.png">

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x71o73v (offline)
<img width="642" alt="image" src="https://user-images.githubusercontent.com/7253922/232242265-8e2f8c24-2c6a-4022-8f1f-3bc8bae5f4b2.png">

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/tv8montblanc (offline)
<img width="635" alt="image" src="https://user-images.githubusercontent.com/7253922/232242290-da4ce3b1-d1ec-45de-93a0-acc23038a1dc.png">

Broken link removed from playlist.
