### ISSUE TITLE
Add: Canal 12 Posadas

### ISSUE THREAD

**Issue by Arnaldo-dev** [iptv-org/iptv#10464]
### Channel ID

Canal12Posadas.ar

### Stream URL

https://g4.vxral-hor.transport.edge-access.net/a05/ngrp:c12_live01-100129_all/c12_live01-100129_720p.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Dead stream: please close.
