### ISSUE TITLE
Jeem tv, Baraem (AR)

### ISSUE THREAD

**Issue by Aladdin00** [iptv-org/iptv#1046]
Hi.
I would appreacite if you could add these two Arabic Kids channels. I added the logos to be sure:
Jeem TV.
![jeemtv_logo](https://user-images.githubusercontent.com/62308532/76897352-416beb80-689c-11ea-82c7-18519c067e3e.jpeg)
And
Baraem.
![logo_baraem](https://user-images.githubusercontent.com/62308532/76897477-7c6e1f00-689c-11ea-9241-25a0da3b8d4c.jpg)

Thank you in advance(I have been looking for these two channels with no luck).

**Comment by themak1985** [comment]
They are pretty hard to find - seems like Al Jazeera shuts the streams down shortly after they go up. If you find a site broadcasting it - let us know.

**Comment by freearhey** [comment]
Closed in favor #1956

**Comment by peeeps** [comment]
> Hi.
> I would appreacite if you could add these two Arabic Kids channels. I added the logos to be sure:
> Jeem TV.
> ![jeemtv_logo](https://user-images.githubusercontent.com/62308532/76897352-416beb80-689c-11ea-82c7-18519c067e3e.jpeg)
> And
> Baraem.
> ![logo_baraem](https://user-images.githubusercontent.com/62308532/76897477-7c6e1f00-689c-11ea-9241-25a0da3b8d4c.jpg)
> 
> Thank you in advance(I have been looking for these two channels with no luck).

hia
