### ISSUE TITLE
Add: La Tele Tuya [VE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10461]
### Channel ID

LaTeleTuya.ve

### Stream URL

https://vcp4.myplaytv.com/tlt-ve/tltve-291022.stream/.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Added: will be in next release. Please close.
