### ISSUE TITLE
Replace: AMC East

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#10476]
### Broken Link

https://bcovlive-a.akamaihd.net/ebf15ff84e98490e8b00209ed77c77f5/us-east-1/6240731308001/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://bcovlive-a.akamaihd.net/b3ed62003de946c896f4f541b908376e/us-east-1/6240731308001/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Thanks for the stream: will be included in my next update (or before).
