### ISSUE TITLE
CDN Deportes (RD)

### ISSUE THREAD

**Issue by duzthn** [iptv-org/iptv#10473]
### Channel ID

cdndeportes.com.do

### Stream URL

https://dacastmmd.mmdlive.lldns.net/dacastmmd/98c5ff12adca4abc9921e8e54f115092/chunklist_b4628000.m3u8?p=79&s=1669248040&e=1669248640&h=494ab5463f32f3232ef48160bb30a725

### Notes

https://cdndeportes.com.do/en-vivo/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://playback.dacast.com/content/access?contentId=2c659e044a58572e056cceed234a70cb-live-f56d3109-2db5-9cea-8919-d572074daf59&provider=universe
