### ISSUE TITLE
Replace: IFC East

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#10475]
### Broken Link

https://bcovlive-a.akamaihd.net/070ffdaa203f439cacbf0d45a1ddb356/us-east-1/6240731308001/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://bcovlive-a.akamaihd.net/045bd3b615254da880c3db79b2e42fd0/us-east-1/6240731308001/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Thanks for the stream: will be included in my next update (or before).
