### ISSUE TITLE
Add: Canal 45 [ES] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10486]
### Channel ID

Canal45.es

### Stream URL

https://live.yowi.tv/58b79e6a71f5459d5fc9/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
