### ISSUE TITLE
Add: Télé Culturelle Médias TCM-TV

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#10483]
### Channel ID

TeleCulturelleMedias.ca

### Stream URL

http://teleculturelle.com/

### Notes

Tv Channel in Montréal Québec Canada about Culture

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
could be tokenized

Detected
https://backend.dna-delivery.com/router/v2/10001f6b-63ee-4e8d-9aa7-71b9c44a40a3/content/stream.castr.com%2F631f9bb9ecbe28ce6910385a%2Flive_79b37a4032dd11ed85c9d9bece7b557e%2Findex.m3u8

masterManifest	
https://stream.castr.com/631f9bb9ecbe28ce6910385a/live_79b37a4032dd11ed85c9d9bece7b557e/index.m3u8
mediaManifest	
https://stream.castr.com/631f9bb9ecbe28ce6910385a/live_79b37a4032dd11ed85c9d9bece7b557e/tracks-v1a1/mono.m3u8

referrer	 playable in streamlink
https://player.castr.com/live_79b37a4032dd11ed85c9d9bece7b557e

**Comment by AntiPontifex** [comment]
Links do not work: could someone please look at this.

**Comment by freearhey** [comment]
https://stream.castr.com/631f9bb9ecbe28ce6910385a/live_79b37a4032dd11ed85c9d9bece7b557e/index.m3u8 (offline)
<img width="763" alt="image" src="https://user-images.githubusercontent.com/7253922/232244799-8ba1a561-72a5-43dc-9e1a-32a6577feb84.png">

**Comment by Sphinxroot** [comment]
Kodi
#EXTINF:-1,Tele Culturelle
https://stream.castr.com/631f9bb9ecbe28ce6910385a/live_79b37a4032dd11ed85c9d9bece7b557e/index.m3u8|Referer=https://player.castr.com/live_79b37a4032dd11ed85c9d9bece7b557e

VLC
#EXTINF:-1,Tele Culturelle
#EXTVLCOPT:http-referrer=https://player.castr.com/live_79b37a4032dd11ed85c9d9bece7b557e
https://stream.castr.com/631f9bb9ecbe28ce6910385a/live_79b37a4032dd11ed85c9d9bece7b557e/index.m3u8
