### ISSUE TITLE
A lot of Indonesian channel get 403 (I'm using ott navigator) 

### ISSUE THREAD

**Issue by NaufalF22** [iptv-org/iptv#10499]
### Broken Link

https://iptv-org.github.io/iptv/languages/ind.m3u

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
We were warned about DENS.tv changing lots of channels, we haven't checked out yet.
