### ISSUE TITLE
Add: RecordTV Europa [PT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10498]
### Channel ID

RecordTVEuropa.pt

### Stream URL

https://live-recordeuropa.visioncdn.com/live/recordeuropa/master.m3u8

### Notes

(Geo-blocked): Only available in UK, Ireland, Switzerland, Italy, Vatican City and San Marino.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Dead link.

**Comment by freearhey** [comment]
https://live-recordeuropa.visioncdn.com/live/recordeuropa/master.m3u8 (offline)
<img width="502" alt="image" src="https://user-images.githubusercontent.com/7253922/232244888-d9f83f6a-19a4-42c0-abe5-3ec127aff248.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/861169502d1e8d6e9de628a930170308b7d0353a/streams/pt.m3u#L98-L99
