### ISSUE TITLE
Add: Goiena Eus [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10497]
### Channel ID

GoienaEus.es

### Stream URL

https://zuzenean.goienamedia.eus/goiena-telebista.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
