### ISSUE TITLE
Add: Canal Nubeh TV [VE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10509]
### Channel ID

CanalNubehTV.ve

### Stream URL

https://vcp.myplaytv.com/nubehtv/nubehtv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be added for the next update.
