### ISSUE TITLE
Add: Malysh TV

### ISSUE THREAD

**Issue by SuperWillow** [iptv-org/iptv#10502]
### Channel ID

MalyshTV.ru

### Stream URL

???

### Notes

Я ненавижу Супергероев, добавьте хотя-бы закрытый Малыш ТВ, а то я не хочу смотреть всякое говно, такое как Супер Зак, Школьный автобус Гордон и так далее.

Ну плейлист для закрытого телеканала Малыш ТВ хотя-бы!

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Уважаемые операторы. С 1 апреля 2022 года телеканал "Малиш" больше не будет распространяться компанией "Ред Медиа" на территории Российской Федерации. Также меняется технологическая схема доставки сигнала. Для обеспечения бесперебойного вещания канала в ваших сетях в ближайшее время, пожалуйста, свяжитесь с нашим отделом продаж по адресу: info@malishtv.com .

**Comment by SuperWillow** [comment]
> Уважаемые операторы. С 1 апреля 2022 года телеканал "Малыш" больше не будет распространяться компанией "Ред Медиа" на территории Российской Федерации. Также меняется технологическая схема доставки сигнала. Для обеспечения бесперебойного вещания канала в ваших сетях в ближайшее время, пожалуйста, свяжитесь с нашим отделом продаж по адресу: [info@malishtv.com](mailto:info@malishtv.com) .
> 
> trad
> 
> Dear operators. Starting from April 1, 2022, the Malish TV channel will no longer be distributed by Red Media company on the territory of the Russian Federation. The technological scheme of signal delivery is also changing. To ensure uninterrupted broadcast of the channel in your networks in the near future, please contact our sales department at: [info@malishtv.com](mailto:info@malishtv.com) .
> 
> It seems the channel has shut itself down from Russia. Though the only way to get the channel is _apparently_ asking them to open a stream for us.

Damn СуперГерои! It's not Super Zach, it's Viking Legends >:(

**Comment by SuperWillow** [comment]
> Уважаемые операторы. С 1 апреля 2022 года телеканал "Малыш" больше не будет распространяться компанией "Ред Медиа" на территории Российской Федерации. Также меняется технологическая схема доставки сигнала. Для обеспечения бесперебойного вещания канала в ваших сетях в ближайшее время, пожалуйста, свяжитесь с нашим отделом продаж по адресу: [info@malishtv.com](mailto:info@malishtv.com) .
> 
> trad
> 
> Dear operators. Starting from April 1, 2022, the Malish TV channel will no longer be distributed by Red Media company on the territory of the Russian Federation. The technological scheme of signal delivery is also changing. To ensure uninterrupted broadcast of the channel in your networks in the near future, please contact our sales department at: [info@malishtv.com](mailto:info@malishtv.com) .
> 
> It seems the channel has shut itself down from Russia. Though the only way to get the channel is _apparently_ asking them to open a stream for us.

Too bad. It's time add Чижик them >:(
