### ISSUE TITLE
Replace: Mega [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10516]
### Broken Link

http://186.67.117.178:8081/play/a00x

### What happened to the stream?

Not loading

### Possible Replacement

https://unlimited1-cl-isp.dps.live/mega/mega.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Thank you for the stream; it will be included in the next cl.m3u update.
