### ISSUE TITLE
Add: 5TV Argentina [AR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10518]
### Channel ID

5TVArgentina.ar

### Stream URL

http://www.coninfo.net:1935/tvcinco/live1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list; please close.
