### ISSUE TITLE
Add: Cantina TV [VE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10510]
### Channel ID

CantinaTV.ve

### Stream URL

https://vcp.myplaytv.com/cantinatv/cantinatv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be added in the next update.
