### ISSUE TITLE
Add: Canal 2 Jujuy [AR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10519]
### Channel ID

Canal2Jujuy.ar

### Stream URL

http://api.new.livestream.com/accounts/679322/events/3782013/live.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list; please close.
