### ISSUE TITLE
Replace: Fox News

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#10526]
### Broken Link

http://trn03.tulix.tv/AsEAeOtIxz/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

http://gameplay.p2sweb.me:80/live/3543653/35436567/203641.m3u8

### Notes

International one

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
http://gameplay.p2sweb.me/live/3543653/35436567/203641.m3u8 (offline)
<img width="503" alt="image" src="https://user-images.githubusercontent.com/7253922/232260325-0c9ca2a8-cff4-415d-86df-d60d070310b9.png">

**Comment by freearhey** [comment]
Closed in favor of #11702
