### ISSUE TITLE
Add: Senal Urbana [AR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10523]
### Channel ID

SenalUrbana.ar

### Stream URL

https://videosenlared.fullstreaming.ar:3560/live/senialurbanalive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream; it will be included in the next ar.m3u update.
