### ISSUE TITLE
Add: Phoneix InfoNews (YouTube)

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#10529]
### Channel ID

PhoneixInfoNews.hk

### Stream URL

https://m.youtube.com/watch?v=xyyvJ_KgTlg

### Notes

Fullspeed plz

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Carlinhos027** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/@phoenixtv1916/live

**Comment by kaikyoofers** [comment]
https://ythls.onrender.com/channel/UCd9dPMYgV9-IQaZG491TaRw.m3u8 New url

**Comment by kaikyoofers** [comment]
@freearhey
