### ISSUE TITLE
Add: TIV Television [AR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10522]
### Channel ID

TIVTelevision.ar

### Stream URL

https://inliveserver.com:1936/14044/14044/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream; it will be included in the next ar.m3u update.
