### ISSUE TITLE
Add: Canal SCN [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10539]
### Channel ID

CanalSCN.cl

### Stream URL

https://live.tvcontrolcp.com:1936/sancarlostv/sancarlostv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
