### ISSUE TITLE
Replace: Canal Latino [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10538]
### Broken Link

https://hd.chileservidores.cl:1936/latina/latina/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://live.chileservidores.com:8081/latina/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Thank you for the replacement stream: it will be added for the next update.
