### ISSUE TITLE
There An URL/s For Playback?

### ISSUE THREAD

**Issue by cheznewa** [iptv-org/iptv#1053]
this is an question :::: there an url (or more url) with a feature for playback with a specified date, for example :::: if i watch this url from 2018/04/04 20:00:00 to 2018/04/05 08:00:00 in case if i missed

this question is with from https://github.com/wolonggl/China-Telecom-IPTV-list (chinese) where you can playback with playseek option but no work

and if there no feature "tampis" is good if a new url with feature.

Sick/Newa

**Comment by freearhey** [comment]
Unfortunately we don't have the possibility to add records for 8000 channels. But if you find any solution, let us know and we will publish it here.
