### ISSUE TITLE
Add: Aysen TV [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10534]
### Channel ID

AysenTV.cl

### Stream URL

http://v1.tustreaming.cl/aysentv/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be added in the next release.
