### ISSUE TITLE
Add: RT News (Rumble)

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#10530]
### Channel ID

RT.ru

### Stream URL

https://rumble-foxo.cdn.rumble.cloud/live/hr6yv36f/slot-30/ngrp:srak-wx8r_all/playlist.m3u8

### Notes

Optional m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3aef7cdbc4c159c043152f434a750bf4d63d837d/streams/ru.m3u#L638-L639
