### ISSUE TITLE
Add: Campo Abierto TV [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10535]
### Channel ID

CampoAbiertoTV.cl

### Stream URL

https://v1.tustreaming.cl:19360/campoabierto/campoabierto.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
