### ISSUE TITLE
Add: Canal 2 San Antonio [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10537]
### Channel ID

Canal2SanAntonio.cl

### Stream URL

https://unlimited1-cl-isp.dps.live/canal2/canal2.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
