### ISSUE TITLE
Add: Evavision [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10548]
### Channel ID

Evavision.cl

### Stream URL

https://stmv1.zcastbr.com/evevision/evevision/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.
