### ISSUE TITLE
Add: EGM Channel [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10545]
### Channel ID

EGMChannel.cl

### Stream URL

https://paneltv.online:1936/8186/8186/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.
