### ISSUE TITLE
Add: Contivision [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10542]
### Channel ID

Contivision.cl

### Stream URL

https://unlimited2-cl-isp.dps.live/cm/cm.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
