### ISSUE TITLE
Add: Exprezion TV [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10549]
### Channel ID

ExprezionTV.cl

### Stream URL

https://srv3.zcast.com.br/expreszion/expreszion/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be added in the next release.
