### ISSUE TITLE
Add: CDR [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10540]
### Channel ID

CDR.cl

### Stream URL

https://tv.streaming-chile.com:19360/mescibar/mescibar.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
