### ISSUE TITLE
Add: Cultura Online [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10544]
### Channel ID

CulturaOnline.cl

### Stream URL

https://v1.tustreaming.cl:19360/culturaonline/culturaonline.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
