### ISSUE TITLE
Add: Kanade [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10554]
### Channel ID

Kanade.cl

### Stream URL

https://stream.wowlymedia.com/hls/kanade/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
