### ISSUE TITLE
Add: Pichilemu TV [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10559]
### Channel ID

PichilemuTV.cl

### Stream URL

https://5ff3d9babae13.streamlock.net/8028/8028/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the link: it will be included in the next release.
