### ISSUE TITLE
Add: Juntos TV [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10553]
### Channel ID

JuntosTV.cl

### Stream URL

https://video.juntostvchile.cl:8879/hls/web-jntv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
