### ISSUE TITLE
Add: Hito Cero Television [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10551]
### Channel ID

HitoCeroTelevision.cl

### Stream URL

https://5ff3d9babae13.streamlock.net/8018/8018/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.
