### ISSUE TITLE
Add: Galactika Media [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10550]
### Channel ID

GalactikaMedia.cl

### Stream URL

https://oracle.streaminghd.cl/galactika/galactika/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream does not work: please close.
