### ISSUE TITLE
Add: Maulevision [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10557]
### Channel ID

Maulevision.cl

### Stream URL

https://makestreaming.online:3061/hybrid/play.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
