### ISSUE TITLE
Add: La Chilena TV [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10555]
### Channel ID

LaChilenaTV.cl

### Stream URL

https://vdochile.com:3134/hybrid/play.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
