### ISSUE TITLE
Japan NHK World TV in Chinese audio language

### ISSUE THREAD

**Issue by dscythegeo** [iptv-org/iptv#1055]
Japan NHK World TV has live streaming in Chinese audio, website links as below:

https://www3.nhk.or.jp/nhkworld/zh/live/

Request to add it to playlist for "Japan" country

**Comment by Nintendocustom** [comment]
This is the link to the stream:
https://nhkw-zh-hlscomp.akamaized.net/8thz5iufork8wjip/playlist.m3u8

**Comment by dscythegeo** [comment]
Thanks for the direct link, hope it will be added into the index.country/language/category playlist in the future.

**Comment by freearhey** [comment]
Done.

**Comment by dscythegeo** [comment]
Thank you and very appreciate your hard work and fast respond.
