### ISSUE TITLE
Add: UCV TV [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10567]
### Channel ID

UCVTV.cl

### Stream URL

https://unlimited2-cl-isp.dps.live/ucvtv2/ucvtv2.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Under UCV3TV.cl - please close.
