### ISSUE TITLE
Add: Restaurando Vidas Internacional [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10561]
### Channel ID

RestaurandoVidasInternacional.cl

### Stream URL

http://v2.tustreaming.cl/restaurandovidastv/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Link does not work: geo-blocked? (in Canada)
