### ISSUE TITLE
Add: Temuco Television [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10563]
### Channel ID

TemucoTelevision.cl

### Stream URL

https://tv.streaming-chile.com:19360/temucotelevision/temucotelevision.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
