### ISSUE TITLE
Add: TV Costa [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10564]
### Channel ID

TVCosta.cl

### Stream URL

https://tv.tvcontrolcp.com:1936/costatv1/costatv1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be added in the next release.
