### ISSUE TITLE
Replace: TVO San Vicente [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10566]
### Broken Link

https://unlimited2-cl-movistar.dps.live/tvo/tvo.smil/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://5e3483cba9114.streamlock.net/8014/8014/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Thank you for the replacement: works fine.
