### ISSUE TITLE
Add: TV Elqui [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10565]
### Channel ID

TVElqui.cl

### Stream URL

https://paneltv.online:1936/8056/8056/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
