### ISSUE TITLE
Add: PlanetaTV Music [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10560]
### Channel ID

PlanetaTVMusic.cl

### Stream URL

https://scl.edge.grupoz.cl/music/live/music.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.
