### ISSUE TITLE
Replace: Vida TV [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10570]
### Broken Link

http://45.161.188.242:88/vidatv/index.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

http://181.224.64.2:89/vidatv/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Already included: please close.
