### ISSUE TITLE
Add: Vision TV [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10571]
### Channel ID

VisionTV.cl

### Stream URL

https://5cf4a2c2512a2.streamlock.net:443/8184/8184/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank yo for the stream; it will be added in the next release.
