### ISSUE TITLE
Add: Zapping Music [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10579]
### Channel ID

ZappingMusic.cl

### Stream URL

https://zmlive.zappingtv.com/zm-free/zm.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.
