### ISSUE TITLE
Add: Voz de Poder Television [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10577]
### Channel ID

VozdePoderTelevision.cl

### Stream URL

https://v1.tustreaming.cl:19360/vozdepoder/vozdepoder.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream; it will be included in the next release.
