### ISSUE TITLE
Add: Viwix TV Series [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10575]
### Channel ID

ViwixTVSeries.cl

### Stream URL

https://s2.tvdatta.com:3402/hybrid/play.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already included: please close.
