### ISSUE TITLE
Add: Wowly [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10578]
### Channel ID

Wowly.cl

### Stream URL

https://stream.wowlymedia.com/hls/stream/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
