### ISSUE TITLE
Add: La 2 Canarias [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10589]
### Channel ID

La2Canarias.es

### Stream URL

https://rtvelivestream.akamaized.net/rtvesec/can/la2_can_main_dvr.m3u8

### Notes

(Geo-blocked)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Can confirm it goes through 403 Forbidden when getting access to TS files, however it can successfully gather stream data.

**Comment by AntiPontifex** [comment]
Dead link
