### ISSUE TITLE
Broken: 

### ISSUE THREAD

**Issue by Hafidzgtg** [iptv-org/iptv#10581]
### Broken Link

https://iptv-org.github.io/iptv/regions/asia.m3u

### What happened to the stream?

Not loading

### Notes

hello... I can't watch HBO Asian...

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by eklins** [comment]
HBO Asia can try either one of this:
http://w.nasvpn.xyz:8080/live/saya/saya/7868.ts

http://50.7.220.74:8278/hbohd_twn/playlist.m3u8?ct=19225&tid=ME9E5260921952609219&tsum=a904cd480db106670befb11d14149fce

http://198.16.64.10:8278/hbohd_twn/playlist.m3u8?tid=ME9E5260921952609219&ct=19225&tsum=a904cd480db106670befb11d14149fce

**Comment by LaneSh4d0w** [comment]
1st one is a xtream-codes server, not allowed.

the 2 others are tokened and will simply go off air after some time. not reliable.

**Comment by Hafidzgtg** [comment]
I am also the same..

**Comment by Pich1685** [comment]
http://50.7.220.74:8278/hbohd_twn/playlist.m3u8?ct=19225&tid=ME9E5260921952609219&tsum=a904cd480db106670befb11d14149fce

This link work for me

**Comment by Hafidzgtg** [comment]
> http://50.7.220.74:8278/hbohd_twn/playlist.m3u8?ct=19225&tid=ME9E5260921952609219&tsum=a904cd480db106670befb11d14149fce
> 
> Tautan ini berfungsi untuk saya

How ?
![IMG_20221223_161653](https://user-images.githubusercontent.com/50311982/209308515-2f2e41a0-cd3b-4240-a38e-f411d44752e4.jpg)

**Comment by Hafidzgtg** [comment]
It works.. but it's Chinese subtitles.. not Indonesian
http://198.16.64.10:8278/hbohd_twn/playlist.m3u8?tid=ME9E5260921952609219&ct=19225&tsum=a904cd480db106670befb11d14149fce

http://50.7.220.74:8278/hbohd_twn/playlist.m3u8?ct=19225&tid=ME9E5260921952609219&tsum=a904cd480db106670befb11d14149fce

**Comment by Pich1685** [comment]
yeah, it's CN subtitles. But the movie did not speak in CN.

**Comment by Hafidzgtg** [comment]
Yes, I want subtitle Indonesia... Another HBO doesn't exist subtitle Indonesia....
