### ISSUE TITLE
Add: La 2 Catalunya [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10588]
### Channel ID

La2Catalunya.es

### Stream URL

https://rtvelivestream.akamaized.net/rtvesec/cat/la2_cat_main_dvr.m3u8

### Notes

(Geo-blocked)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Works from my French IP.

**Comment by AntiPontifex** [comment]
Geo-blocked here
