### ISSUE TITLE
Add: Antena 7 [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10585]
### Channel ID

Antena7.do

### Stream URL

https://d3qhvst5vzq4y9.cloudfront.net/hls/antena7.m3u8

### Notes

(Not 24/7)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be added in the next update.
