### ISSUE TITLE
Add: Zona Play TV [CL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10580]
### Channel ID

ZonaPlayTV.cl

### Stream URL

https://paneltv.online:1936/8100/8100/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next update.
