### ISSUE TITLE
Add: Telemicro [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10586]
### Channel ID

Telemicro.do

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://livestream.com/accounts/27456795/events/10633780/player

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Added as an alternate stream: thank you.
