### ISSUE TITLE
Add: Neox TV

### ISSUE THREAD

**Issue by Hannaplus4** [iptv-org/iptv#10582]
### Channel ID

NeoxTV.ar

### Stream URL

https://streamcasthd.com:19360/sonicaargentina/sonicaargentina.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream; it will be added in the next release.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/ar.m3u#L295-L296
