### ISSUE TITLE
Replace: NHK World live

### ISSUE THREAD

**Issue by kukalikuk** [iptv-org/iptv#10593]
### Broken Link

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCSPEjw8F2nQDtmUKPFNF7_A/live

### What happened to the stream?

Not loading

### Possible Replacement

https://nhkwlive-xjp.akamaized.net/hls/live/2003458/nhkwlive-xjp-en/index_1M.m3u8

### Notes

NHK World live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://nhkwlive-xjp.akamaized.net/hls/live/2003458/nhkwlive-xjp-en/index_1M.m3u8
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/7253922/232261061-435e66b1-6b4b-4c29-8a95-4cbbc79b6528.png">

**Comment by freearhey** [comment]
Broken link removed from playlist.
