### ISSUE TITLE
Teletica Canal 7

### ISSUE THREAD

**Issue by jafusv** [iptv-org/iptv#10606]
### Channel ID

Teletica7.cr

### Stream URL

http://app1299.xyz/show/?id=69&name=COSTA%20RICA

### Notes

Can we please add teletica?

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
it's an Xtream-Codes protocol : http://magmas5.com:8000/live/malotv/gratis/125905.m3u8

**Comment by garabit** [comment]
In https://github.com/iptv-org/iptv/commit/48b88735ea05a5e73140a0aa2e0660890ac2b984#diff-7d387527c3d22a423e0fce2f1d12d32e35ca65a4ddfc800f333443d92835de45 this channel was deleted, even though the corresponding link first stated here https://github.com/iptv-org/iptv/issues/6449 still works.

**Comment by freearhey** [comment]
Closed in favor of #12967
