### ISSUE TITLE
Add: TIVA TV [PR - Puerto Rico]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#10605]
### Channel ID

WRUADT1.us

### Stream URL

https://link.frontlayer.com/services/hls2/fl496518/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/pr.m3u#L40-L43
