### ISSUE TITLE
Add: KBS WORLD (With English Subtitles) [KR]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#10604]
### Channel ID

KBSWorld.kr

### Stream URL

https://kbsworld-ott.akamaized.net/hls/live/2002341/kbsworld/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AstaFatherSatan** [comment]
This seems like a good addition! Link is working flawless and the English captions really help with the k-dramas when there on!

**Comment by Dr-Sauce** [comment]
@AntiPontifex Also add these. Some links are broken or missing.

Sbs: [http://www.hwado.net/webtv/public/31.php ](http://www.hwado.net/webtv/public/31.php)
mbc: [https://tinyurl.com/2p9npbnz ](https://tinyurl.com/2p9npbnz)
channel A: http://mytv.dothome.co.kr/ch/catv/212.php

**Comment by AntiPontifex** [comment]
I haven't touched kr.m3u yet, but I'll attempt to add these if no one else wants too. :)

**Comment by AntiPontifex** [comment]
This is already on the list under: KBS World (720p); I'll add English subtitles to the entry to make it clearer.

**Comment by AntiPontifex** [comment]
Channel A is already listed; the missing SBS and MBC channels seem geo-restricted or tokenized. Hopefully, someone else will be able to help you. I tried. :(

**Comment by R4IN2007** [comment]
SBS m3u8 is Tokenized

**Comment by AntiPontifex** [comment]
Zut!

**Comment by skykhmer** [comment]
Thank you for show me KBS World Link

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/kr.m3u#L114-L115
