### ISSUE TITLE
Add: CRTV [CM]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10615]
### Channel ID

CRTV.cm

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://dailymotion.com/video/x7o9p4a

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
