### ISSUE TITLE
Add: RCN Mas [CO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10613]
### Channel ID

RCNMas.co

### Stream URL

https://rcntv-rcnmas-1-us.plex.wurl.tv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
