### ISSUE TITLE
Replace: America TV [AR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10619]
### Broken Link

https://raw.githubusercontent.com/MachineSystems/archived_m3u8/main/america_hls.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://dai.google.com/linear/hls/pa/event/OY2i_lL4SMyXE5Zaj4ULEg/stream/82fa76c3-5664-42b1-870a-15ae30eb6f6f:BRU/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Both streams do not work: please close.

**Comment by LaneSh4d0w** [comment]
These streams only work if you have a referrer set up. Only a selected number of players that support the #EXTVLCOPT header can read those.

These streams **do** work, but you just don't have the player for it.

**Comment by AntiPontifex** [comment]
Copy that: but for the most part, case closed.
