### ISSUE TITLE
Add: TV Africa [GH] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10618]
### Channel ID

TVAfrica.gh

### Stream URL

http://africatv.live.net.sa:1935/live/africatv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://africatv.live.net.sa:1935/live/africatv/playlist.m3u8
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/7253922/232244978-6b668dcf-02bc-453e-895e-60b397e18b3f.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3aef7cdbc4c159c043152f434a750bf4d63d837d/streams/sd.m3u#L2-L3
