### ISSUE TITLE
Add: Canal 2 International [CM]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10614]
### Channel ID

Canal2International.cm

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://dailymotion.com/video/x7v9nky

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream does not work: please close.
