### ISSUE TITLE
Url change

### ISSUE THREAD

**Issue by netmaxgr** [iptv-org/iptv#1062]
Hello Mister @freearhey .Please update "Netmax" url with my last n most stable url:

http://netmaxlive.tk:8080/live/live/playlist.m3u8

**Comment by freearhey** [comment]
Feel free to update the playlist yourself. If you do not know how to do it, you can read this article: https://flaviocopes.com/how-to-make-first-github-pull-request/

**Comment by netmaxgr** [comment]
Okay,i did it! @freearhey
