### ISSUE TITLE
Replace: Televisa Del Golfo [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10627]
### Broken Link

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCQ08tNTPiBn44c975S81ftg/live

### What happened to the stream?

Not loading

### Possible Replacement

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/@televisadelgolfof/live

### Notes

Not 24/7

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/@televisadelgolfof/live (offline)
<img width="677" alt="image" src="https://user-images.githubusercontent.com/7253922/232245257-394da5ba-d52f-4511-aee8-d79c3d93e6ef.png">

Broken link removed from playlist.
