### ISSUE TITLE
Add: BTN TV [RW]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10621]
### Channel ID

BTNTV.rw

### Stream URL

https://tv.livebcm.com:3844/live/btntvrwandalive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://tv.livebcm.com:3844/live/btntvrwandalive.m3u8
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/7253922/232245000-fb754493-c964-4207-b079-69383a71531b.png">
