### ISSUE TITLE
Replace: Televisa Aguascalientes [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10623]
### Broken Link

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UC5ZtV3bu3bjSuOLoA6oCFIg/live

### What happened to the stream?

Not loading

### Possible Replacement

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/@televisaguascalients/live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Stream does not work: please close.

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/@televisaguascalients/live (offline)
<img width="692" alt="image" src="https://user-images.githubusercontent.com/7253922/232245146-2dbfd4fd-95d1-4779-87a6-530a606da3fc.png">

Broken link removed from playlist.
