### ISSUE TITLE
Add: Arryadia [MA]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10622]
### Channel ID

Arryadia.ma

### Stream URL

https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/arriadia/hls_snrt/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by UltraHDR** [comment]
Already in https://github.com/iptv-org/iptv/blob/master/streams/ma.m3u#L13
