### ISSUE TITLE
Add: Televisa del Bajio [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10624]
### Channel ID

TelevisaDelBajio.mx

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/@televisadelbajio/live

### Notes

(Not 24/7)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream does not work: please close.

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/@televisadelbajio/live (offline)
<img width="668" alt="image" src="https://user-images.githubusercontent.com/7253922/232245210-5d9f5b35-9d22-46ac-9525-de08279a5d68.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/mx_televisa.m3u#L6-L7
