### ISSUE TITLE
Replace: Televisa Morelos [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10630]
### Broken Link

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCcC9ykApQrgl4UxbKg2U4zw/live

### What happened to the stream?

Not loading

### Possible Replacement

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/@televisamorelos/live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/@televisamorelos/live (offline)

Broken link removed from playlist.
