### ISSUE TITLE
Replace: Televisa Sonora [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10636]
### Broken Link

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCyzWMHGS7bs0sot6KZk5EZg/live

### What happened to the stream?

Not loading

### Possible Replacement

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/@TelevisaSonoraOficial/live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/@TelevisaSonoraOficial/live (offline)

Broken link removed from playlist.

**Comment by albghost** [comment]
m3u8 sports europe?
