### ISSUE TITLE
Replace: Televisa News Mexico [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10631]
### Broken Link

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCUsm-fannqOY02PNN67C0KA/live

### What happened to the stream?

Not loading

### Possible Replacement

https://channel04-notusa.akamaized.net/hls/live/2029754-b/event01/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://channel04-notusa.akamaized.net/hls/live/2029754-b/event01/index.m3u8
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/7253922/232245362-e1ca520f-61db-418f-914d-7cf6fb670f68.png">

**Comment by freearhey** [comment]
Broken link removed from playlist.
