### ISSUE TITLE
Replace: Televisa San Luis Potosi [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10634]
### Broken Link

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCaRuyaHshLdq462E9_pLzdA/live

### What happened to the stream?

Not loading

### Possible Replacement

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/@TELEVISASANLUISPOTOSIOFICIAL/live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/@TELEVISASANLUISPOTOSIOFICIAL/live (offline)

Broken link removed from playlist.
