### ISSUE TITLE
Replace: Televisa Queretaro [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10633]
### Broken Link

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UC9QNz6VS3gGz55dzxAQtgtA/live

### What happened to the stream?

Not loading

### Possible Replacement

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/@NQueretaro/live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/@NQueretaro/live (offline)

Broken link removed from playlist.
