### ISSUE TITLE
Add: N+ Bajio [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10637]
### Channel ID

NPlusBajio.mx

### Stream URL

https://channel07-notusa.akamaized.net/hls/live/2036971-b/event01/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by R4IN2007** [comment]
Link Works👍
![20221203_212925](https://user-images.githubusercontent.com/83226646/205472875-1b03c095-2093-4bf9-92b7-046de57d1f70.jpg)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/mx.m3u#L102-L103
