### ISSUE TITLE
Add: News 24 [NP]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10641]
### Channel ID

News24.np

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/user/news24tvchannel/live

### Notes

(Not 24/7)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/user/news24tvchannel/live (offline)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/np.m3u#L12-L13
