### ISSUE TITLE
Add: KGTF-DT1 (PBS Guam) [US]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10644]
### Channel ID

KGTFDT1.us

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/user/pbsguam/live

### Notes

(Not 24/7)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by LaneSh4d0w** [comment]
Most certainly news only.

**Comment by kaikyoofers** [comment]
Maybe not, i once saw it air pbs kids

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/user/pbsguam/live (offline)

**Comment by kaikyoofers** [comment]
> http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/user/pbsguam/live (offline)

https://ythls.onrender.com/channel/UCaVp5oNNuIZVU7qqhSX0LGQ.m3u8

You are welcome :)
