### ISSUE TITLE
Add: La Red TV [UY] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10649]
### Channel ID

LaRedTV.uy

### Stream URL

https://stm1.rootuy.xyz:19360/sdredtv/sdredtv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
This stream has already been added: please close.
