### ISSUE TITLE
Replace: free.fullspeed Mexican streams

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#10646]
### Broken Link

all

### What happened to the stream?

Not loading

### Possible Replacement

Lane?

### Notes

Practically all of these streams are no longer loading. Help would be appreciated: thank you.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
It's due to the replacement by YouTube of the "/channel/*ID*" URL to "@channelID"

**Comment by AntiPontifex** [comment]
I substituted as you suggested: still nothing.

**Comment by LaneSh4d0w** [comment]
Which stream are you thinking of ?

**Comment by AntiPontifex** [comment]
Just try and substitute one and you'll see what I mean.

**Comment by Sphinxroot** [comment]
use channel_id  other than using channel name

ex:
Nmas
https://www.youtube.com/@nmas/

https://www.youtube.com/channel/UCUsm-fannqOY02PNN67C0KA/live

Naming have changed but not the ID

**Comment by AntiPontifex** [comment]
I think I'll let someone more "in the know" to tackle these changes. Thanks, Lane.

**Comment by kaikyoofers** [comment]
All of televisa links

**Comment by AntiPontifex** [comment]
If you can figure out the replacement streams, I'll update them. Thanks for pursuing this.

**Comment by kaikyoofers** [comment]
Televisa News Mexico: https://channel04-notusa.akamaized.net/hls/live/2029754-b/event01/index.m3u8

**Comment by AntiPontifex** [comment]
Replaced: thank you. Will be added next update.
