### ISSUE TITLE
Add: Alpha HD

### ISSUE THREAD

**Issue by Playe4** [iptv-org/iptv#10665]
### Channel ID

AlphaTVHD.gr

### Notes

country: Greece
broadcast area: Greece
languages: Greek
is nsfw: false
launched: 6 July 2016
website: https://www.alphatv.gr/
Logo: 
![Alpha_HD](https://user-images.githubusercontent.com/117739628/205883615-8add9d1a-ca27-44ce-a3cd-af0a2ac22a0b.png)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Smark223** [comment]
Already in the playlist

http://alphatvlive.siliconweb.com/1/Y2Rsd1lUcUVoajcv/UVdCN25h/hls/live/playlist.m3u8
