### ISSUE TITLE
Add: NU9VE - NUEVE [México | MX]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#10672]
### Channel ID

ElNu9ve.mx / Nueve.mx

### Stream URL

https://linear-352.frequency.stream/352/hls/master/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next update.

**Comment by GiovanniSebastian** [comment]
Any link for Canal 5 or BitMe?

**Comment by R4IN2007** [comment]
> Any link for Canal 5 or BitMe?

No, Couldn't Find Any Link For Canal 5 or BitMe

You Could Try To Find The Links Here. That's Where This Link Is From 
https://github.com/ALAN1714RAM/Lista/blob/main/lista%20genial%202.m3u8

**Comment by DavidTerrassa** [comment]
Hello

**Comment by DavidTerrassa** [comment]
Hello

**Comment by GiovanniSebastian** [comment]
OK, Thank you so much!!

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/mx.m3u#L40-L41
