### ISSUE TITLE
Add: RFD-TV

### ISSUE THREAD

**Issue by Arkina1234** [iptv-org/iptv#10673]
### Channel ID

RFDTV.us

### Stream URL

https://rfdtv-jw.cdn.vustreams.com/live/7cba1a3b-318a-4097-8492-374478370b91/live.isml/7cba1a3b-318a-4097-8492-374478370b91.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by freearhey** [comment]
https://rfdtv-jw.cdn.vustreams.com/live/7cba1a3b-318a-4097-8492-374478370b91/live.isml/7cba1a3b-318a-4097-8492-374478370b91.m3u8
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/7253922/232245852-a129c90f-9332-4093-8572-01f6532949bd.png">
