### ISSUE TITLE
Add: NBC 11 Atlanta GA * 11Alive *

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#10671]
### Channel ID

WXIADT1.us

### Stream URL

https://livevideo.tegnadigital.com/wxia/v1/master/f9c1bf9ffd6ac86b6173a7c169ff6e3f4efbd693/WXIA/elvs/live.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Dead link: geo-blocked?

**Comment by R4IN2007** [comment]
> Dead link: geo-blocked?

Stream Link Works Fine For Me 
![Screenshot_20221206-154914_Chrome](https://user-images.githubusercontent.com/83226646/206030731-77eb1995-dcb2-466e-a791-5855f705799a.jpg)

**Comment by AntiPontifex** [comment]
Doesn't work for me: must be geo-blocked. Thanks for confirming.

**Comment by missjane63** [comment]
Yes, it is geoblocked, I tested, it works in US not elsewhere

**Comment by LaneSh4d0w** [comment]
Geo indeed.

**Comment by freearhey** [comment]
https://livevideo.tegnadigital.com/wxia/v1/master/f9c1bf9ffd6ac86b6173a7c169ff6e3f4efbd693/WXIA/elvs/live.m3u8
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/7253922/232245815-6187f4a1-d0ad-42c0-8238-b919b0d9aafc.png">
