### ISSUE TITLE
Add: CNN Brasil

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#10670]
### Channel ID

CNNBrasil.br

### Stream URL

http://170.82.200.38:8080/cnn_brasil/tracks-v1a1/mono.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
http://170.82.200.38:8080/cnn_brasil/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by kaikyoofers** [comment]
@darrencycheung xtream code streams are not allowed
