### ISSUE TITLE
Add: Canal 11 (Guatemala)

### ISSUE THREAD

**Issue by ELProductions** [iptv-org/iptv#10692]
### Channel ID

chapintv.com

### Notes

Please add Canal 11 (Guatemala) (previously known as Teleonce). Thanks!

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Geo-blocked here.
