### ISSUE TITLE
Add: RTL Germany [DE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10694]
### Channel ID

RTLGermany.de

### Stream URL

https://s6.hopslan.com/rtlu111/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
