### ISSUE TITLE
Add: Afrique Media [CM]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10691]
### Channel ID

AfriqueMedia.cm

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x5dk3kj

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
