### ISSUE TITLE
Add: HOY TV Optional m3u8

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#10696]
### Channel ID

HOYTV.hk

### Stream URL

http://media.hkopentv.com/m3u8/archive/channel2.m3u8

### Notes

Found on some app

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Simply redirects here : http://media.fantv.hk/m3u8/archive/channel2.m3u8

**Comment by darrencycheung** [comment]
http://61.10.0.102/m3u8/archive/channel2.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/hk.m3u#L19-L20
