### ISSUE TITLE
Add: Locomotion TV

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#10690]
### Channel ID

LocomotionTV.do

### Stream URL

http://51.222.85.85:81/hls/loco/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Not 24/7, will check later when it'll work.

**Comment by AntiPontifex** [comment]
404'ed here, Lane.
