### ISSUE TITLE
Add: Sport 1 [DE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10695]
### Channel ID

Sport1.de

### Stream URL

https://oz.sport1.de/api/ottv1/2/livestream/view/sport2.m3u8

### Notes

(Geo-blocked)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream. Legal stream, Lane?

**Comment by LaneSh4d0w** [comment]
Legal stream for this one.

**Comment by Carlinhos027** [comment]
> Legal stream for this one.

[https://tv.sport1.de/live/sport1](url)

**Comment by LaneSh4d0w** [comment]
That's what i'm saying, the stream *is* legal. Quite rare for these kind of websites.
