### ISSUE TITLE
Add: CRTV News [CM]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10693]
### Channel ID

CRTVNews.cm

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x8csy6e

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
