### ISSUE TITLE
Add: MTV Lebanon

### ISSUE THREAD

**Issue by LaneSh4d0w** [iptv-org/iptv#10703]
### Channel ID

MTVLebanon.lb

### Stream URL

https://live.3cd.io/v1/broadcast/one/playlist.m3u8

### Notes

@UltraHDR New output from the VODLive API.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by UltraHDR** [comment]
https://live.3cd.io/v1/broadcast/mtv/playlist.m3u8 also works
