### ISSUE TITLE
Replace: MTV Japan

### ISSUE THREAD

**Issue by harrykieu** [iptv-org/iptv#10704]
### Broken Link

https://iptv-org.github.io/iptv/languages/jpn.m3u

### What happened to the stream?

Not loading

### Notes

The stream is not working for a long time,

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by eklins** [comment]
https://stream01.willfonk.com/live_playlist.m3u8?cid=CS325&r=FHD&ccode=JP&m=d0:20:20:04:35:cc&t=0d6938cb3dcf4b79848bc1753a59daf1

**Comment by harrykieu** [comment]
> https://stream01.willfonk.com/live_playlist.m3u8?cid=CS325&r=FHD&ccode=JP&m=d0:20:20:04:35:cc&t=0d6938cb3dcf4b79848bc1753a59daf1

This is M-ON channel, not MTV.

**Comment by AstaFatherSatan** [comment]
Stop sharing my sub

**Comment by AstaFatherSatan** [comment]
@LaneSh4d0w please fix this...

**Comment by AstaFatherSatan** [comment]
I don't want to have to post a pic of my damn box to prove the point

**Comment by AstaFatherSatan** [comment]
Ty

**Comment by LaneSh4d0w** [comment]
> Edit: Thank you for doing this, and so quick. I'm sorry you have to deal with this. I appreciate the help a lot dude. I don't want to have to post a pic of my damn box to prove the point

Sadly once one knows... it can't be stopped. Dropped the revision history so that the link can't be seen.

**Comment by AstaFatherSatan** [comment]
Ty
