### ISSUE TITLE
Add: Allgau TV [DE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10707]
### Channel ID

AllgauTV.de

### Stream URL

https://stream01.welocal.stream/stream/fhd-allgaeutv_25679/ngrp:stream_all/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already included: please close.
