### ISSUE TITLE
Add: DW English (YouTube)

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#10705]
### Channel ID

DWEnglish.de

### Stream URL

https://www.youtube.com/watch?v=ammKkVgtIHw

### Notes

Fullspeed 
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/dwnews/live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/dwnews/live (offline)
<img width="623" alt="image" src="https://user-images.githubusercontent.com/7253922/232216483-22a139b3-ee5b-4248-9453-dd1af26e6bdd.png">

https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/de.m3u#L78-L79

**Comment by kaikyoofers** [comment]
> http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/dwnews/live (offline) <img alt="image" width="623" src="https://user-images.githubusercontent.com/7253922/232216483-22a139b3-ee5b-4248-9453-dd1af26e6bdd.png">
> 
> https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/de.m3u#L78-L79

Youtube Version: https://ythls.onrender.com/channel/UCknLrEdhRCp1aegoMqRaCZg.m3u8
