### ISSUE TITLE
Add: Donna TV

### ISSUE THREAD

**Issue by Smark223** [iptv-org/iptv#10700]
### Channel ID

DonnaTV.it

### Stream URL

https://streaming.softwarecreation.it/DonnaTv/DonnaTv/playlist.m3u8

### Notes

EPG available at https://www.superguidatv.it/programmazione-canale/oggi/guida-programmi-tv-donnatv/464/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Smark223** [comment]
@AntiPontifex I've close this as requested but I can't see the channel in the Italy playlist

**Comment by AntiPontifex** [comment]
It's in it.m3u in the latest update: honest!
