### ISSUE TITLE
Add: SR Fernsehen [DE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10719]
### Channel ID

SRFernsehen.de

### Stream URL

https://s4.hopslan.com/srfernsehen/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by LaneSh4d0w** [comment]
Bunch of hopslan links... never heard that one lol
