### ISSUE TITLE
Add: Augsburg TV [DE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10718]
### Channel ID

AugsburgTV.de

### Stream URL

https://stream02.welocal.stream/stream/fhd-augsburgtv_104951/ngrp:stream_all/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
