### ISSUE TITLE
Add: Nick Germany [DE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10729]
### Channel ID

NickGermany.de

### Stream URL

https://s6.hopslan.com/nick/index.m3u8

### Notes

In Germany, Nickelodeon is a free-to-air channel.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Does not work: geo-blocked?
