### ISSUE TITLE
Add: BR Fernsehen Sud [DE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10728]
### Channel ID

BRFernsehenSud.de

### Stream URL

https://brcdn.vo.llnwd.net/br/fs/bfs_sued/hls/int/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.
