### ISSUE TITLE
Add: n-tv [DE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10724]
### Channel ID

ntv.de

### Stream URL

https://s6.hopslan.com/ntvv/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
