### ISSUE TITLE
Add: WDR 1 Live [DE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10726]
### Channel ID

WDR1Live.de

### Stream URL

https://wdrfsww247.akamaized.net/hls/live/2009628/wdr_msl4_fs247ww/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.
