### ISSUE TITLE
Add: TV Berlin [DE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10725]
### Channel ID

TVBerlin.de

### Stream URL

https://live2.telvi.de/hls/tvberlin.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
