### ISSUE TITLE
Add: TVA [DE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10727]
### Channel ID

TVA.de

### Stream URL

https://tvaktuellr.iptv-playoutcenter.de/tvaktuellr/tvaktuellr.stream_1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.
