### ISSUE TITLE
Fix: Logo Channel ID: "PromarTV.ve"

### ISSUE THREAD

**Issue by juliosalas4d** [iptv-org/iptv#10735]
### Describe your issue

Good afternoon.
First of all I want to apologize if this is not the way to report this bug.
I want to inform you that the Logo of the channel ID: "PromarTV.ve", is wrong.
The correct logo is: "https://es.wikipedia.org/wiki/Promar_TV#/media/Archivo:Promar_Television.png"

Tank you...

Buenas tardes.
Primero que nada quiero disculparme si esta no es la vía para reportar este error.
Quiero informar que el Logo del canal ID: "PromarTV.ve", está errado.
El logo correcto es: "https://es.wikipedia.org/wiki/Promar_TV#/media/Archivo:Promar_Television.png".

Gracias...

**Comment by LaneSh4d0w** [comment]
Fix has been implemented by @freearhey , can safely be closed. Thank you for reporting it.

**Comment by juliosalas4d** [comment]
Thnk you...
