### ISSUE TITLE
Add: ServusTV [AT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10738]
### Channel ID

ServusTV.at

### Stream URL

https://s6.hopslan.com/servus2/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be added next release.
