### ISSUE TITLE
Add: N1 Bosnia & Herzegovina [BA]

### ISSUE THREAD

**Issue by unitedcloud** [iptv-org/iptv#10731]
### Channel ID

N1BosniaHerzegovina.ba

### Stream URL

https://best-str.umn.cdn.united.cloud/stream?stream=sp1400&sp=n1info&channel=n1bos&u=n1info&p=n1Sh4redSecre7iNf0

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
DMCAd.
