### ISSUE TITLE
Add: RTL Tele Luxembourg [LU]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10742]
### Channel ID

RTLTeleLuxembourg.lu

### Stream URL

https://live-edge.rtl.lu/channel1/smil:channel1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
