### ISSUE TITLE
Add: M4 Sport [HU]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10746]
### Channel ID

M4Sport.hu

### Stream URL

https://c201-node61-cdn.connectmedia.hu/110304/5fcf89df43eaeebc4b785fc5b851bff6/63947e81/index.m3u8

### Notes

(Not 24/7)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Dead link.
