### ISSUE TITLE
Add: ACTV [BE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10741]
### Channel ID

ACTV.be

### Stream URL

https://tvlocales-live.freecaster.com/95d2f733-1bc2-4bd5-9b96-c53ed3fc450f/95d2f733-1bc2-4bd5-9b96-c53ed3fc450f.isml/master.m3u8

### Notes

(Geo-blocked)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Hard to check, but thank you for the stream: it will be added next release.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/be.m3u#L2-L3
