### ISSUE TITLE
Add: Duna TV [HU]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10748]
### Channel ID

DunaTV.hu

### Stream URL

https://c201-node61-cdn.connectmedia.hu/110303/ce9cfaf3261a0809ce44844ae5a33f0b/63947fb2/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already added: please close.
