### ISSUE TITLE
Add: TeleBarn [CH]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10743]
### Channel ID

TeleBarn.ch

### Stream URL

https://klive.kaltura.com/env/cluster-1-d.live.nvp1/live/hls/p/1719221/e/1_obr1n222/tl/main/st/0/t/V5aB4vl7IdB41mCbZmUxNA/index-s32.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be added next release.
