### ISSUE TITLE
Add: Duna World [HU]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10749]
### Channel ID

DunaWorld.hu

### Stream URL

https://c201-node61-cdn.connectmedia.hu/110306/86f065aae3f8371bd19e5a15ffc62c15/63948002/index.m3u8

### Notes

(Not 24/7)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already added: please close.
