### ISSUE TITLE
Add: TV Eger [HU]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10750]
### Channel ID

TVEger.hu

### Stream URL

http://stream.tveger.hu:8010/live.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be added next release.
