### ISSUE TITLE
Add: Kapos TV [HU]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10751]
### Channel ID

KaposTV.hu

### Stream URL

https://cloudfront63.lexanetwork.com:1344/relay01/livestream004.sdp/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already added: please close.
