### ISSUE TITLE
Replace: Love Nature

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#10760]
### Broken Link

https://bamus-eng-roku.amagi.tv/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://d18dyiwu97wm6q.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/LoveNature4K2-prod/playlist.m3u8

### Notes

Emergency replace

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Thank you for the correction: it will be included in the next release.

**Comment by freearhey** [comment]
https://d18dyiwu97wm6q.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/LoveNature4K2-prod/playlist.m3u8
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/7253922/232247159-57652796-43cc-45b9-9ebb-feb0346f6837.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1c494c6a39b765de57e0c5794e72a86d59516fb0/streams/us_samsung.m3u#L58-L59
