### ISSUE TITLE
Add: LoveWorld Persia [NG]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10766]
### Channel ID

LoveWorldPersia.ng

### Stream URL

https://bus-asia-east-1-cimzmgnuu-cdn.sa.metacdn.com/live/ngrp:lxp22_main_all_transcode/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by dalaohuniu** [comment]
ok good
