### ISSUE TITLE
Add: TV Fatima [PT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10773]
### Channel ID

TVFatima.pt

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCOAjX8pc2fY1S5AqsXvZywg/live

### Notes

(Not 24/7)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCOAjX8pc2fY1S5AqsXvZywg/live (offline)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/pt.m3u#L82-L85
