### ISSUE TITLE
Add: Max TV [CH]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10771]
### Channel ID

MaxTV.ch

### Stream URL

https://katapy.hs.llnwd.net/dieutvwza1/DIEUTVLIVE/smil:dieutv.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream for Dieu TV, not Max TV: please close.

**Comment by dalaohuniu** [comment]
good idea
