### ISSUE TITLE
Add: Kanal 9 [CH]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10770]
### Channel ID

Kanal9.ch

### Stream URL

https://edge20.vedge.infomaniak.com/livecast/ik:livesd2/manifest.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Smark223** [comment]
Already in the playlist but tvg-id is missing

**Comment by AntiPontifex** [comment]
tvg-ids now added: please close
