### ISSUE TITLE
Add: Auftanken TV [CH]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10772]
### Channel ID

AuftankenTV.ch

### Stream URL

https://tvhosa-pez0315.sctv.ch/http_adaptive_streaming/HFAPHLAAMJJLFJDG.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
404ed - geo-blocked?
