### ISSUE TITLE
Add: ABC News Albania [AL]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10777]
### Channel ID

ABCNewsAlbania.al

### Stream URL

https://tv2.abcnews.al/live/abcnews/playlist.m3u8

### Notes

(Not 24/7)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.

**Comment by dalaohuniu** [comment]
thankyou

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/al.m3u#L18-L19
