### ISSUE TITLE
Add: 7D7 [EE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10774]
### Channel ID

7D7.ee

### Stream URL

https://d7tv.pp.ua/hls/d7tv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.

**Comment by freearhey** [comment]
https://d7tv.pp.ua/hls/d7tv.m3u8
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/7253922/232247711-cdfe9548-e85e-4986-80c7-7c3048632dd5.png">
