### ISSUE TITLE
Add: Geo Entertainment

### ISSUE THREAD

**Issue by naqviking** [iptv-org/iptv#10789]
### Channel ID

GeoEntertainment.pk

### Stream URL

https://harpalgeo.tv/live/

### Notes

**plzz add this channel plzz Thanku**

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
https://jk3lz82elw79-hls-live.5centscdn.com/harPalGeo/955ad3298db330b5ee880c2c9e6f23a0.sdp/playlist.m3u8
