### ISSUE TITLE
Add: Senzi [SK] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10786]
### Channel ID

Senzi.sk

### Stream URL

http://lb.streaming.sk/senzi/stream/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
On list: please close.
