### ISSUE TITLE
Add: TV Reduta [SK] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10785]
### Channel ID

TVReduta.sk

### Stream URL

https://5ca49f2417d90.streamlock.net/live/reduta/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
On list: please close.
