### ISSUE TITLE
Add: TV LocAll [SK] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10787]
### Channel ID

TVLocAll.sk

### Stream URL

http://tv.geniusnet.sk:8081/localltv/pl.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.
