### ISSUE TITLE
Add: TV Raj [SK] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10784]
### Channel ID

TVRaj.sk

### Stream URL

https://ottst05.flexitv.sk/2827-tv-pc.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.
