### ISSUE TITLE
Add: Rapsodia TV [RO] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10782]
### Channel ID

RapsodiaTV.ro

### Stream URL

http://92.86.248.141:8080/ram/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already added: please close.
