### ISSUE TITLE
Add: JOJ Plus [SK] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10783]
### Channel ID

JOJPlus.sk

### Stream URL

https://nn.geo.joj.sk/live/hls/jojplus-540.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Smark223** [comment]
Already in playlist but tvg-id is missing

**Comment by AntiPontifex** [comment]
Already on list: please close.
