### ISSUE TITLE
Add: OK Kiel [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10781]
### Channel ID

OKKiel.de

### Stream URL

https://live-cdn.oksh.de/play/hls/kieltv/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
