### ISSUE TITLE
Add: JenaTV [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10780]
### Channel ID

JenaTV.de

### Stream URL

https://stream4.sehradar.de/jenatv/ngrp:livestream_all/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next update.
