### ISSUE TITLE
Replace: Toei Channel

### ISSUE THREAD

**Issue by LunaticKingdom** [iptv-org/iptv#10790]
### Broken Link

https://cdnv148.cloudrsst.com/jptv/toa_540/playlist.m3u8

### What happened to the stream?

Not loading

### Notes

Channel of Toei content (animation/tokusatsu), would be really useful to have it back.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by cloud90** [comment]
is on now this channel

**Comment by freearhey** [comment]
Broken link removed from playlist.
