### ISSUE TITLE
PTV SPORTS 

### ISSUE THREAD

**Issue by Easyfiv3** [iptv-org/iptv#10792]
### Broken Link

http://103.81.104.118/hls/stream11.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

http://208.86.19.13:81/6100.stream/index.m3u8

### Notes

PTV SPORTS 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by arsalankhan994** [comment]
still not working

**Comment by freearhey** [comment]
http://208.86.19.13:81/6100.stream/index.m3u8 (offline)
<img width="345" alt="image" src="https://user-images.githubusercontent.com/7253922/232260348-81dd819b-a064-4653-8509-907297526815.png">

**Comment by mehtab150** [comment]
How to watch live match ind vs pak
