### ISSUE TITLE
Add: ITV +1 [UK]

### ISSUE THREAD

**Issue by ExperiencersInternational** [iptv-org/iptv#10795]
### Channel ID

ITV1Plus1.uk

### Stream URL

https://cdnuk001.broadcastcdn.net/KUK-ITVPLUS1/tracks-v1a1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by eklins** [comment]
http://prox.x86.co.uk/index.php/https://cdnuk001.broadcastcdn.net/KUK-ITVPLUS1/tracks-v1a1/playlist.m3u8

**Comment by freearhey** [comment]
http://prox.x86.co.uk/index.php/https://cdnuk001.broadcastcdn.net/KUK-ITVPLUS1/tracks-v1a1/playlist.m3u8
<img width="749" alt="image" src="https://user-images.githubusercontent.com/7253922/232247812-286e6449-23f2-40ca-a244-98c3daaafc5c.png">

https://cdnuk001.broadcastcdn.net/KUK-ITVPLUS1/tracks-v1a1/playlist.m3u8
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/7253922/232247793-2e2d806a-880b-4d11-8e25-dd419d26581e.png">

**Comment by freearhey** [comment]
https://cdnuk001.broadcastcdn.net/KUK-ITVPLUS1/tracks-v1a1/playlist.m3u8 (Offline)
<img width="545" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/b07c6bd4-855f-40d4-9e1d-514e92613571">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/uk.m3u#L109-L110
