### ISSUE TITLE
Add: More4 [UK]

### ISSUE THREAD

**Issue by ExperiencersInternational** [iptv-org/iptv#10796]
### Channel ID

More4.uk

### Stream URL

https://cdnuk001.broadcastcdn.net/KUK-MORE4/tracks-v1a1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by eklins** [comment]
http://prox.x86.co.uk/index.php/https://cdnuk001.broadcastcdn.net/KUK-MORE4/tracks-v1a1/playlist.m3u8

**Comment by freearhey** [comment]
http://prox.x86.co.uk/index.php/https://cdnuk001.broadcastcdn.net/KUK-MORE4/tracks-v1a1/playlist.m3u8
<img width="735" alt="image" src="https://user-images.githubusercontent.com/7253922/232247868-060ed15b-dce4-41e5-b7a3-af3a43dc0ce2.png">

https://cdnuk001.broadcastcdn.net/KUK-MORE4/tracks-v1a1/playlist.m3u8
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/7253922/232247861-70a66109-d884-4b8c-85ad-d7e7eb0706d0.png">

**Comment by freearhey** [comment]
https://cdnuk001.broadcastcdn.net/KUK-MORE4/tracks-v1a1/playlist.m3u8 (Offline)
<img width="530" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/50db5578-bd84-4c65-a54f-f7fc4c66d73f">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/uk.m3u#L143-L144
