### ISSUE TITLE
Add: Cartoon Network Japan (カートゥーン ネットワーク)

### ISSUE THREAD

**Issue by ironboy36** [iptv-org/iptv#10807]
### Channel ID

CartoonNetworkJapan.jp

### Notes

I don't have the Stream URL, sorry!

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://code.vthanhtivi.pw/getlink/jptv/noeD-Yf5Rph09MTEByH-Xw==/playlist.m3u8
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/7253922/233872365-9d1f5ce8-21db-4b88-91f0-7bab9f25fc28.png">

http://rip.hidari.moe/get/jptv/get.php?id=noeD-Yf5Rph09MTEByH-Xw==
<img width="791" alt="image" src="https://user-images.githubusercontent.com/7253922/233872387-cc8e21e8-2740-46fb-b48e-d348b040fce3.png">

**Comment by dantheman121** [comment]
> https://code.vthanhtivi.pw/getlink/jptv/noeD-Yf5Rph09MTEByH-Xw==/playlist.m3u8 <img alt="image" width="1413" src="https://user-images.githubusercontent.com/7253922/233872365-9d1f5ce8-21db-4b88-91f0-7bab9f25fc28.png">
> 
> http://rip.hidari.moe/get/jptv/get.php?id=noeD-Yf5Rph09MTEByH-Xw== <img alt="image" width="791" src="https://user-images.githubusercontent.com/7253922/233872387-cc8e21e8-2740-46fb-b48e-d348b040fce3.png">

The second one is offline
