### ISSUE TITLE
Replace: 24/7 Retro

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#10818]
### Broken Link

http://hlsdpi-cdn-chqtx02.totalstream.net/dpilive/247retro/ret/dai/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

no idea

### Notes

Please fix this when you can.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
hun is this the one ? https://www.getafteritmedia.com/retro-live-feed

https://bcovlive-a.akamaihd.net/5e531be3ed6c41229b2af2d9bffba88d/us-east-1/6183977686001/playlist.m3u8

**Comment by AntiPontifex** [comment]
Actually, the station has gone off the air (just found out). Target for removal please.
