### ISSUE TITLE
Add: Korean Central Television (조선중앙텔레비죤)

### ISSUE THREAD

**Issue by ironboy36** [iptv-org/iptv#10816]
### Channel ID

KCTV.kp

### Stream URL

https://www.twitch.tv/kctv_elufa

### Notes

It's a Twitch broadcast in 810p format.
It is a Television broadcast from North Korea.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/kp.m3u#L2-L3
