### ISSUE TITLE
Replace: VTV2 (Vietnam)

### ISSUE THREAD

**Issue by ZXArkin** [iptv-org/iptv#10814]
### Broken Link

https://vips-livecdn.fptplay.net/hda1/vtv2_vhls.smil/chunklist_b5000000.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://livecdn.fptplay.net/sevent/vtv2_vhls.smil/chunklist_b5000000.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
https://livecdn.fptplay.net/sevent/vtv2_vhls.smil/playlist.m3u8 but 403 on French IP. Certainly geo-blocked.

**Comment by freearhey** [comment]
https://livecdn.fptplay.net/sevent/vtv2_vhls.smil/chunklist_b5000000.m3u8 (offline)
<img width="521" alt="image" src="https://user-images.githubusercontent.com/7253922/232247404-3dc55df9-a63f-4b41-83da-2ead321ba674.png">

Broken link removed from playlist.
