### ISSUE TITLE
Replace: KBSWorld.kr

### ISSUE THREAD

**Issue by Abaddon1980** [iptv-org/iptv#10811]
### Broken Link

https://iptv-org.github.io/iptv/countries/kr.m3u

### What happened to the stream?

Not loading

### Possible Replacement

https://kbsworld-ott.akamaized.net/hls/live/2002341/kbsworld/master.m3u8

### Notes

I'm sorry. I'm not sure how to get the broken link from the playlist. I just started learning how to do all this recently. I know KBS World is located in the South Korean playlist. Someone changed the previous link to a non working link with vietnamese subs but it doesn't work. Thank you for trying to fix this. And thank you for all your hard work in helping maintain this site. 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
It's in there, though it's only keeping one link against all the others.

**Comment by rochiemac17** [comment]
Hopefully KBS World will be back soon. 🙏🙏🙏🙏

**Comment by jbcooter** [comment]
is there a working kbs world link? if not, I might be able to find a source.

**Comment by Abaddon1980** [comment]
Kbs world doesn't work for me. I use Tivimate and entered it into the playlist section but I only realized later that tivimate doesn't do separate streams. So I took the stream I located (https://kbsworld-ott.akamaized.net/hls/live/2002341/kbsworld/master.m3u8) and stuck it in VLC. It's a hassle whenever I want to watch something switching from app to app. But least it works. Whatever you can do I'd greatly appreciate it.
