### ISSUE TITLE
Replace: VTV3 (Vietnam)

### ISSUE THREAD

**Issue by ZXArkin** [iptv-org/iptv#10813]
### Broken Link

https://vips-livecdn.fptplay.net/hda1/vtv3hd_vhls.smil/chunklist_b5000000.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://livecdn.fptplay.net/sevent/vtv3hd_vhls.smil/chunklist_b5000000.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://livecdn.fptplay.net/sevent/vtv3hd_vhls.smil/chunklist_b5000000.m3u8 (offline)
<img width="544" alt="image" src="https://user-images.githubusercontent.com/7253922/232247356-4b7fd576-ed10-41dc-bc18-6fb43b3ec4cc.png">

Broken link removed from playlist.
