### ISSUE TITLE
Tailoring the list

### ISSUE THREAD

**Issue by P0987654321** [iptv-org/iptv#1082]
I use Smart STB on an LG TV. A popular way to watch channels. 

Normally channels are grouped by an upper index which is what you are trying to do. However, the list as it currently is appears only as long 8,000 list with no tier 1 categories.
ALBANIA > Channel 1, Channel 2, 
UK > Channel 1, Channel 2 etc.. 

Thanks

**Comment by freearhey** [comment]
Did you try this playlist: https://iptv-org.github.io/iptv/index.country.m3u

**Comment by P0987654321** [comment]
Thanks for the better list but it still just displays not as a nested list but a long single list (but clearer names)

Thanks

**Comment by freearhey** [comment]
Can you give an example of a playlist that shows up okay for you?

**Comment by P0987654321** [comment]
Maybe its just Smart STB (LT TV App)

It has an intro screen which look sliced this 




It then moves to an EPG like this.. and done well the Sort, Favourite and Move links should work. 

It’s very very good. 

At the moment your links just move straight to the second screen with 6000 channels, no search etc.. 

Thanks

**Comment by freearhey** [comment]
First, the image is not displayed. Secondly, if you want us to make any changes to the playlists you need to provide an example of a playlist that normally shows up on your TV, otherwise we will not be able to help you.
