### ISSUE TITLE
Add: Jednotka, Dvojka, Markíza and Dajto [SK] and CNN Prima News [CZ]

### ISSUE THREAD

**Issue by Jakubicek222** [iptv-org/iptv#10849]
### Channel ID

Jednotka.sk, Dvojka.sk, Markiza.sk, MarkizaDajto.sk, CNNPrimaNews,cz

### Stream URL

http://213.81.133.133:8080/jednotka/index.m3u8, http://213.81.133.133:8080/dvojka/index.m3u8, http://83.167.253.107/hdmi1_ext, http://213.81.133.133:8080/dajto/index.m3u8, https://prima-ott-live.ssl.cdn.cra.cz/channels/prima_cnn/playlist/cze/live_hq.m3u8?offsetSeconds=0&url=0

### Notes

**Quality of the streams:**
**Jednotka: **960p
**Dvojka: **960p
**Markíza: **720p
**Dajto: **960p
**CNN Prima News: **576p

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
IMPORTANT: an issue without a valid channel ID or containing a request for more than one channel will be closed immediately

Please close.

**Comment by Calokifilm** [comment]
it's not working again
