### ISSUE TITLE
Add MBC5 "moroccan" channel 

### ISSUE THREAD

**Issue by saidma** [iptv-org/iptv#10846]
### Channel ID

MBC5.ae

### Notes

Although the channel is financed by the UAE, its original programs are produced in Morocco and aimed at the Moroccan public. I propose to add it to the Morocco group

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://shls-mbc5-prod-dub.shahid.net/out/v1/2720564b6a4641658fdfb6884b160da2/index.m3u8

**Comment by saidma** [comment]
> https://shls-mbc5-prod-dub.shahid.net/out/v1/2720564b6a4641658fdfb6884b160da2/index.m3u8
> 
> We'll need to wait for the bot to consider it is online :
> 
> https://github.com/iptv-org/iptv/blob/c0360a2ebdeb2559f8659ac317f622e29ba7a0ad/streams/ae.m3u#L90-L91

Thank you!
