### ISSUE TITLE
Add: First Channel [GE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10851]
### Channel ID

FirstChannel.ge

### Stream URL

https://tv.cdn.xsg.ge/gpb-1tv/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by LaneSh4d0w** [comment]
https://github.com/iptv-org/iptv/blob/c0360a2ebdeb2559f8659ac317f622e29ba7a0ad/streams/ge.m3u#L2-L3
