### ISSUE TITLE
Add: Gospel Cartoon [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10855]
### Channel ID

GospelCartoon.br

### Stream URL

https://stmv1.srvif.com/gospelcartoon/gospelcartoon/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next update.
