### ISSUE TITLE
Add: ISTV [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10856]
### Channel ID

ISTV.br

### Stream URL

https://cdn.jmvstream.com/w/LVW-9883/LVW9883_lFcfKysrHF/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
