### ISSUE TITLE
Add: TVCG MNE [ME]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10853]
### Channel ID

TVCGMNE.me

### Stream URL

https://cdn3.rtcg.me:1936/cgsat/smil:cgsat.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the release.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/me.m3u#L10-L17
