### ISSUE TITLE
Add: TV Difusora Sao Luis [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10859]
### Channel ID

TVDifusoraSaoLuis.br

### Stream URL

https://stream.amsolution.net.br:8443/live/60ce4ae4b9d4c/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
