### ISSUE TITLE
Add: Imedi TV [GE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10850]
### Channel ID

ImediTV.ge

### Stream URL

https://tv.cdn.xsg.ge/imedihd/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/ge.m3u#L18-L19
