### ISSUE TITLE
Replace: Televizija TV7 [ME]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10854]
### Broken Link

http://109.123.70.27:1935/tehnikatv777/tehnikatv777/index.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://5a1178b42cc03.streamlock.net/tehnikatv777/tehnikatv777/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next update.

**Comment by freearhey** [comment]
https://5a1178b42cc03.streamlock.net/tehnikatv777/tehnikatv777/playlist.m3u8
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/7253922/232261081-3201f8e8-e5dd-4728-82a7-057282fd54b9.png">
