### ISSUE TITLE
Add: TV Mackenzie [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10866]
### Channel ID

TVMackenzie.br

### Stream URL

https://player.internetaovivo.com:8443/live_tvmackenzieabr/tvmackenzieabr/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
