### ISSUE TITLE
Add: TV Universal [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10862]
### Channel ID

TVUniversal.br

### Stream URL

https://644398c.ha.azioncdn.net/primary/tvuniversal_480p.sdp/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
