### ISSUE TITLE
Add: BYU TV

### ISSUE THREAD

**Issue by Arkina1234** [iptv-org/iptv#10865]
### Channel ID

BYUTV.us

### Stream URL

https://content.uplynk.com/channel/2bb01dbf7c9b425db6854a4e45a57af8.m3u8?exp=1672322568&drm_optional=1&cid=2bb01dbf7c9b425db6854a4e45a57af8&rn=227352725&tc=1&ct=c&sig=037e56be674afc63b222e054d6ffb1be2544a777848a5220e6c6a88f7e07b4be

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by robocopz** [comment]
US geo and I think it expires on 12/29/22

**Comment by AntiPontifex** [comment]
Thanks for that: will be deleted.

**Comment by freearhey** [comment]
https://content.uplynk.com/channel/2bb01dbf7c9b425db6854a4e45a57af8.m3u8?exp=1672322568&drm_optional=1&cid=2bb01dbf7c9b425db6854a4e45a57af8&rn=227352725&tc=1&ct=c&sig=037e56be674afc63b222e054d6ffb1be2544a777848a5220e6c6a88f7e07b4be (offline)
<img width="829" alt="image" src="https://user-images.githubusercontent.com/7253922/232247966-cf4e6ab5-2a9e-405c-a44b-9338ff956f4d.png">

**Comment by Sphinxroot** [comment]
https://content.uplynk.com/channel/2f29cb20fcb74f68a85c38b99ca384bc.m3u8
