### ISSUE TITLE
Add: TV Tropical [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10867]
### Channel ID

TVTropical.br

### Stream URL

https://59f2354c05961.streamlock.net:1443/portaldatropical/_definst_/portaldatropical/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
