### ISSUE TITLE
Add: Public TV [IN]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10868]
### Channel ID

PublicTV.in

### Stream URL

https://livestream.knowtable.xyz:5443/show/streams/Publictv_adaptive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://livestream.knowtable.xyz:5443/show/streams/Publictv_adaptive.m3u8
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/7253922/232248009-2941d770-343e-40c6-a993-d6530b480bf6.png">
