### ISSUE TITLE
Add: TV Sul Bahia [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10861]
### Channel ID

TVSulBahia.br

### Stream URL

http://live.cdn.upx.com/00046/myStream.sdp/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
