### ISSUE TITLE
Add: Markíza [SK]

### ISSUE THREAD

**Issue by Jakubicek222** [iptv-org/iptv#10876]
### Channel ID

Markiza.sk

### Stream URL

http://83.167.253.107/hdmi1_ext

### Notes

Quality of the stream is already in 1280x720. The stream was in 640x360 quality.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by Jakubicek222** [comment]
Ok

**Comment by freearhey** [comment]
http://83.167.253.107/hdmi1_ext
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/7253922/232248318-d9bc746c-09e8-41d5-a0bd-5d930045c61c.png">
