### ISSUE TITLE
Add: Encuentro [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10874]
### Channel ID

Encuentro.ar

### Stream URL

https://538d0bde28ccf.streamlock.net/live-cont.ar/encuentro/.m3u8

### Notes

(Not 24/7)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
