### ISSUE TITLE
Add: DajTo [SK]

### ISSUE THREAD

**Issue by Jakubicek222** [iptv-org/iptv#10879]
### Channel ID

MarkizaDajto.sk

### Stream URL

http://213.81.133.133:8080/dajto/index.m3u8

### Notes

The stream is in quality 1706x960.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by freearhey** [comment]
http://213.81.133.133:8080/dajto/index.m3u8
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/7253922/232248226-5ca28975-91cf-4cd9-af38-bde0cd9de484.png">
