### ISSUE TITLE
Add: Jednotka [SK]

### ISSUE THREAD

**Issue by Jakubicek222** [iptv-org/iptv#10877]
### Channel ID

Jednotka.sk

### Stream URL

http://213.81.133.133:8080/jednotka/index.m3u8

### Notes

The stream is in quality 1706x960.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
