### ISSUE TITLE
Add: Shoptime [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10871]
### Channel ID

Shoptime.br

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/@shoptime/live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
