### ISSUE TITLE
Add: SIC TV [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10872]
### Channel ID

SICTV.br

### Stream URL

https://parecisfmlive.brasilstream.com.br/hls/parecisfmlive/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
