### ISSUE TITLE
Add: RTVE 24h (YouTube)

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#10870]
### Channel ID

Canal24Horas.es

### Stream URL

https://m.youtube.com/watch?v=xR-4NDFsYNk

### Notes

Fullspeed 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Carlinhos027** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/@rtvenoticias/live

**Comment by Carlinhos027** [comment]
This one is more stable: https://ztnr.rtve.es/ztnr/1694255.m3u8
