### ISSUE TITLE
Add: Dvojka [SK]

### ISSUE THREAD

**Issue by Jakubicek222** [iptv-org/iptv#10878]
### Channel ID

Dvojka.sk

### Stream URL

http://213.81.133.133:8080/dvojka/index.m3u8

### Notes

The stream is in quality 1706x960.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://213.81.133.133:8080/dvojka/index.m3u8
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/7253922/232248182-1d4f9b25-2819-4efc-bfeb-11ca632dcfc4.png">
