### ISSUE TITLE
Add: TVT [SK]

### ISSUE THREAD

**Issue by Jakubicek222** [iptv-org/iptv#10881]
### Channel ID

TVT.sk

### Stream URL

http://5ca49f2417d90.streamlock.net/live/turzovka/playlist.m3u8

### Notes

The stream is in quality 864x496.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
