### ISSUE TITLE
Add: CNN Prima News [CZ]

### ISSUE THREAD

**Issue by Jakubicek222** [iptv-org/iptv#10883]
### Channel ID

CNNPrimaNews.cz

### Stream URL

https://prima-ott-live.ssl.cdn.cra.cz/channels/prima_cnn/playlist/cze/live_hq.m3u8?offsetSeconds=0&url=0

### Notes

The stream is in quality 1024x576.
No Geo-block

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by freearhey** [comment]
Duplicate of #10768

**Comment by freearhey** [comment]
Closed in favor of #10768
