### ISSUE TITLE
Add: Jojko [SK]

### ISSUE THREAD

**Issue by Jakubicek222** [iptv-org/iptv#10880]
### Channel ID

Jojko.sk

### Stream URL

https://st01-1.iptv.joj.sk/104-tv-pc.mpd

### Notes

The stream is in quality 1920x1080. The stream is from platform names JOJ Play

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
