### ISSUE TITLE
Add: Mňau TV [CZ]

### ISSUE THREAD

**Issue by Jakubicek222** [iptv-org/iptv#10882]
### Channel ID

MnauTV.cz

### Stream URL

https://5ca49f2417d90.streamlock.net/mnau/livestream/chunklist_w1495048646.m3u8

### Notes

The stream is in quality 1920x1080.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next update.

**Comment by Jakubicek222** [comment]
ok
