### ISSUE TITLE
Add: GEN

### ISSUE THREAD

**Issue by thelmagali** [iptv-org/iptv#10890]
### Channel ID

Gen.py

### Stream URL

https://q-s-l4n3sh4d0w-usw.onrender.com/iptv-query?streaming-ip=https://www.desdepylabs.com/External/tvaccion/gentv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Same issue than Hei.

**Comment by LaneSh4d0w** [comment]
https://q-s-l4n3sh4d0w-usw.onrender.com/iptv-query?streaming-ip=https://www.desdepylabs.com/External/tvaccion/gentv
