### ISSUE TITLE
Add: Hei now

### ISSUE THREAD

**Issue by thelmagali** [iptv-org/iptv#10891]
### Channel ID

Hei.py

### Stream URL

https://q-s-l4n3sh4d0w-usw.onrender.com/iptv-query?streaming-ip=https://www.desdepylabs.com/External/tvaccion/heitv

### Notes

PR to add the channel to the database: https://github.com/iptv-org/database/issues/1552

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
![image](https://user-images.githubusercontent.com/30985701/208487244-a3f79dbd-731f-458c-bf17-881d81875baa.png)

Needs a session token. I'm actually working on a streamlink plugin for PyLabs / DesdeParaguay.

**Comment by LaneSh4d0w** [comment]
work in progress... to be pushed on the usw version of Q-S when it's done

for now I've put the base, need some fixes here and there : https://q-s-l4n3sh4d0w-usw.onrender.com/iptv-query?streaming-ip=https://www.desdepylabs.com/External/tvaccion/ (channel you find)

**Comment by LaneSh4d0w** [comment]
Q-S USW is being updated, tested it carefully and it should work.

**Comment by LaneSh4d0w** [comment]
https://q-s-l4n3sh4d0w-usw.onrender.com/iptv-query?streaming-ip=https://www.desdepylabs.com/External/tvaccion/heitv

**Comment by thelmagali** [comment]
Amazing @LaneSh4d0w, thanks!
