### ISSUE TITLE
Add: SPLTV

### ISSUE THREAD

**Issue by oussamame07** [iptv-org/iptv#10901]
### Channel ID

spltv.tn

### Stream URL

https://livetest.spl-tv.com/hls/stream.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by UltraHDR** [comment]
It is here https://github.com/iptv-org/iptv/blob/master/streams/tn.m3u#L24
