### ISSUE TITLE
Replace: TV1000

### ISSUE THREAD

**Issue by Subhan8115** [iptv-org/iptv#10918]
#10917 

### Broken Link

https://okkotv-live.cdnvideo.ru/channel/TV1000_HD.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://okkotv-live.cdnvideo.ru/channel/TV1000_HD.m3u8
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/7253922/232261110-fbae55bf-55ec-435c-9f51-995168880266.png">
