### ISSUE TITLE
Add: Euronews English YT

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#10910]
### Channel ID

EuronewsEnglish.fr

### Stream URL

https://m.youtube.com/watch?v=pykpO5kQJ98

### Notes

Fullspeed 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/fr_euronews.m3u#L4-L9
