### ISSUE TITLE
Add: Mega TV

### ISSUE THREAD

**Issue by thelmagali** [iptv-org/iptv#10911]
### Channel ID

MegaTV.py

### Stream URL

https://streannlivemegacadena.cachefly.net/Protected/sp=1;dirmatch=true;ip=181.94.231.56/72f562a872f8e1ac8cbab5c330c0baad9279ff30ec35f7b7de8d788e6cf7cc58/megacadena1/megacadena1/chunks.m3u8

### Notes

It's token-protected.

Also, this is the issue to add it to the database: https://github.com/iptv-org/database/issues/1568

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Sorry only seen that one now, 

https://ott3.streann.com/loadbalancer/services/public/channels-secure/5e62b96e2cdcfac2dd8885dd/playlist.m3u8
https://rds3.desdeparaguay.net/mov780/mov780.stream/playlist.m3u8
https://rds3.desdeparaguay.net/movlatina/movlatina.stream/playlist.m3u8
https://rds3.desdeparaguay.net/movcanal100/movcanal100.stream/playlist.m3u8
https://rds3.desdeparaguay.net/movromance/movromance.stream/playlist.m3u8

**Comment by freearhey** [comment]
https://ott3.streann.com/loadbalancer/services/public/channels-secure/5e62b96e2cdcfac2dd8885dd/playlist.m3u8
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/7253922/232248495-59be83d8-072e-4283-bd33-ba769bb34ebc.png">
