### ISSUE TITLE
Add: 5 Días [PY]

### ISSUE THREAD

**Issue by thelmagali** [iptv-org/iptv#10923]
### Channel ID

5DiasTV.py

### Stream URL

https://www.youtube.com/watch?v=U2KO1TFcpO8&ab_channel=5D%C3%8DASTELEVISI%C3%93N

### Notes

This is the issue to add the channel to the DB: https://github.com/iptv-org/database/issues/1575

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Carlinhos027** [comment]
http://free.fullspeed.tv/iptv-query?stream-ip=https://youtube.com/@5diastelevision284/live

**Comment by LaneSh4d0w** [comment]
Can't be used now, as dct disabled the YouTube node.

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://youtube.com/@5diastelevision284/live (offline)
