### ISSUE TITLE
Broken: VenusMedia.py

### ISSUE THREAD

**Issue by thelmagali** [iptv-org/iptv#10927]
### Broken Link

https://rds3gen.desdeparaguay.net/venusmedia/venusmedia/.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://www.desdepylabs.com/External/video/venusmedia

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
https://q-s-l4n3sh4d0w-usw.onrender.com/iptv-query?streaming-ip=https://www.desdepylabs.com/External/video/venusmedia

**Comment by LaneSh4d0w** [comment]
Should work now.

**Comment by LaneSh4d0w** [comment]
(of course, the service has reached its overload so now i'll need to wait until January to reload it)

**Comment by LaneSh4d0w** [comment]
the original rds3gen link still works for me nonetheless. Could have been a temporary shutdown.

**Comment by LaneSh4d0w** [comment]
Venus has been added with the free.fullspeed.tv link. Closing this.
