### ISSUE TITLE
Add: Latele [PY]

### ISSUE THREAD

**Issue by thelmagali** [iptv-org/iptv#10922]
### Channel ID

Latele.py

### Stream URL

https://q-s-l4n3sh4d0w-usw.onrender.com/iptv-query\?streaming-ip\=https://www.desdepylabs.com/External/tvaccion/latele

### Notes

streamlink https://q-s-l4n3sh4d0w-usw.onrender.com/iptv-query\?streaming-ip\=https://www.desdepylabs.com/External/tvaccion/latele best

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
iptv-org/iptv#10899

**Comment by LaneSh4d0w** [comment]
> #10899

Yep, added that one since I've seen that channel pop off the Desdepylabs channels, for now can't do much since my servers have reached their load for the month. dct has updated its free.fullspeed, maybe he's added the new plugins too, must check.

**Comment by LaneSh4d0w** [comment]
> > #10899
> 
> Yep, added that one since I've seen that channel pop off the Desdepylabs channels, for now can't do much since my servers have reached their load for the month. dct has updated its free.fullspeed today, maybe he's added the new plugins too, must check.

Yep, can confirm dct has my new plugin, works perfectly fine on free.fullspeed.tv :)

**Comment by LaneSh4d0w** [comment]
Merged, closing this.
