### ISSUE TITLE
Add: Azteca Valle - KRGV 5.2 (Weslaco, TX)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#10929]
### Channel ID

KRGVDT2.us

### Stream URL

https://stream.krgv.com/krgv-english/krgv-somos.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next update.

**Comment by LaneSh4d0w** [comment]
https://stream.krgv.com/krgv-english/krgv-english.smil/playlist.m3u8 (not 24/7)

**Comment by LaneSh4d0w** [comment]
Watch out for the confusion, this is channel *5.3* being streamed, per https://www.krgv.com/azteca-valle.

Azteca isn't streamed on their servers, though Hechos, a subsidiary from Azteca, is streamed.
