### ISSUE TITLE
Replace: BS TV Tokyo

### ISSUE THREAD

**Issue by 72888hshu** [iptv-org/iptv#10931]
### Broken Link

http://cdn.us195.jpnettv.live:1935/jptv

### What happened to the stream?

Not loading

### Notes

Return error 403 Forbidden
![image](https://user-images.githubusercontent.com/48046222/209308506-7e25d8d5-e148-4b89-8ac4-a6cdaa3e7a80.png)
 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
I knew those links wouldn't last long enough, sadly the sources for Japanese channels are quite low. Only the "mov3.co" links, operating from China still works well, maybe because the host is compliant with the channels being distributed.

**Comment by freearhey** [comment]
Broken link removed from playlist.
