### ISSUE TITLE
Add: The Ohio Channel (WVIZ DT-2)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#10932]
### Channel ID

WVIZDT2.us

### Stream URL

https://5ebe6889de541.streamlock.net/live/stream_10/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by freearhey** [comment]
https://5ebe6889de541.streamlock.net/live/stream_10/playlist.m3u8
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/7253922/232248671-c13d93e6-6b86-403f-805a-7cb750a28270.png">
