### ISSUE TITLE
Add: GPB Knowledge (US GEO-BLOCKED) [Only For Georgia Residents]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#10939]
### Channel ID

*N/A*

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://api.new.livestream.com/accounts/30060031/events/9303760/

### Notes

There some few problems especially with the *http://free.fullspeed.tv/iptv-query?streaming-ip=* add-on but the m3u8 link work.  
Stream Screenshot:
![Screenshot_20221223-090128_VLC](https://user-images.githubusercontent.com/83226646/209356825-af4ce5df-1cfa-4a62-a2b9-fdaae355c854.jpg)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
Loads for me in brazil

**Comment by LaneSh4d0w** [comment]
works for me
