### ISSUE TITLE
Add: Puruwa TV [EC]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10937]
### Channel ID

PuruwaTV.ec

### Stream URL

https://mediacp.us:8081/8054/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
