### ISSUE TITLE
Add: ABC 5 - KRGV 5.1 (Weslaco, TX)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#10930]
### Channel ID

KRGVDT1.us

### Stream URL

https://stream.krgv.com/krgv-english/krgv-english.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Geo-blocked (from Canada); thank you for the stream. It will be included in the next update.

**Comment by freearhey** [comment]
https://stream.krgv.com/krgv-english/krgv-english.smil/playlist.m3u8
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/7253922/232248624-c8951bff-4d43-49e2-ba09-c42b820028e9.png">
