### ISSUE TITLE
Add: Ecuador TV [EC]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10935]
### Channel ID

EcuadorTV.ec

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://vimeo.com/783833058

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
