### ISSUE TITLE
Add: TV Chile [CL]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10946]
### Channel ID

TVChile.cl

### Stream URL

https://mdstrm.com/live-stream-playlist/533adcc949386ce765657d7c.m3u8

### Notes

Geo-blocked

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
