### ISSUE TITLE
Add: LN24 [BE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10947]
### Channel ID

LN24.be

### Stream URL

https://live.digiteka.com/1/bEg0RmFLb1JMYXRI/dGhqbmIw/hls/live/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/be.m3u#L24-L25
