### ISSUE TITLE
Add: GPB Create (US GEO-BLOCKED) [Only For Georgia Residents]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#10940]
### Channel ID

*N/A*

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://api.new.livestream.com/accounts/6264/events/8860817

### Notes

This is Connected To Issue #10939 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
Loads for me in brazil

**Comment by LaneSh4d0w** [comment]
works for me too

**Comment by R4IN2007** [comment]
```*503 Service Temporarily Unavailable*```
