### ISSUE TITLE
Add: KVEA-DT1 (Telemundo 52 LA) [US]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10949]
### Channel ID

KVEADT1.us

### Stream URL

https://nbculocallive.akamaized.net/hls/live/2037084/losangeles/stream6/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Dead link: geo-blocked?

**Comment by freearhey** [comment]
https://nbculocallive.akamaized.net/hls/live/2037084/losangeles/stream6/master.m3u8 (offline)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/0b298909973cc68f0251bc000213982f45427bcf/streams/us_local.m3u#L726-L727

**Comment by R4IN2007** [comment]
Link works

**Comment by R4IN2007** [comment]
> https://nbculocallive.akamaized.net/hls/live/2037084/losangeles/stream6/master.m3u8 (offline)

![Screenshot_20240704_132932_Chrome](https://github.com/iptv-org/iptv/assets/83226646/e358f1ec-9820-4133-a672-4636055be52a)
NOT 24/7?
