### ISSUE TITLE
Add: Canal 66 Mexicali (XHILA-TDT)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#10943]
### Channel ID

XHILATDT.mx

### Stream URL

https://60417ddeaf0d9.streamlock.net:443/canal66/smil:canal66.smil/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MTIvMjMvMjAyMiA2OjAwOjUzIEFNJmhhc2hfdmFsdWU9SksxczEvV3BPcFBjYmR5Tmk1WkduQT09JnZhbGlkbWludXRlcz01JmlkPQ==

### Notes

The m3u8 Link Is Tokenized or Not but stream works very fine
Stream Screenshot:
![Screenshot_20221223-094227_VLC](https://user-images.githubusercontent.com/83226646/209362281-f2fee990-cd74-47d2-b249-e902eee2f03a.jpg)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Could be a Conceptoweb iframe.

http://free.fullspeed.tv/iptv-query?streaming-ip=https://conceptoweb-studio.com/radio/video/canal66/

**Comment by freearhey** [comment]
https://60417ddeaf0d9.streamlock.net/canal66/smil:canal66.smil/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MTIvMjMvMjAyMiA2OjAwOjUzIEFNJmhhc2hfdmFsdWU9SksxczEvV3BPcFBjYmR5Tmk1WkduQT09JnZhbGlkbWludXRlcz01JmlkPQ== (offline)
<img width="824" alt="image" src="https://user-images.githubusercontent.com/7253922/232248706-2db418ea-74cc-4faa-b6ee-220cdceee77d.png">

http://free.fullspeed.tv/iptv-query?streaming-ip=https://conceptoweb-studio.com/radio/video/canal66/ (offline)
<img width="711" alt="image" src="https://user-images.githubusercontent.com/7253922/232248723-474435f1-1c12-499a-87b7-563c08fc6ddb.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/mx.m3u#L214-L215
