### ISSUE TITLE
Add: Newsy

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#10954]
### Channel ID

Newsy.us

### Stream URL

https://linear-460.frequency.stream/dist/vix/460/hls/master/playlist.m3u8

### Notes

Optional

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you: added for next release.

**Comment by PopeyeTheSai10r** [comment]
> Now has changed name to Scripps News

You should open an issue with this information at https://github.com/iptv-org/database/issues/new/choose
