### ISSUE TITLE
Add: Al Jazeera English

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#10953]
### Channel ID

AlJazeeraEnglish.qa

### Stream URL

https://d1cy85syyhvqz5.cloudfront.net/v1/master/7b67fbda7ab859400a821e9aa0deda20ab7ca3d2/aljazeeraLive/AJE/index.m3u8

### Notes

Optional

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by 40ZqTYY4ag3tAO4hdlxR1** [comment]
Please remove the free.fullspeed.tv link
Use the offical Al Jazeera CDN 

https://live-hls-web-aje.getaj.net/AJE/index.m3u8

free.fullspeed.tv keeps on getting rate limited by YT and slammed by the the ~~hundreds~~ ~~thousands~~ ~~millions~~ billions of requests from people who use the iptv-org playlist https://github.com/iptv-org/iptv/discussions/5395
