### ISSUE TITLE
Add: Digi 24 HD

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#10952]
### Channel ID

Digi24HD.ro

### Stream URL

https://dai.google.com/linear/hls/pb/event/OQfdjUhHSDSlb1fJVzehsQ/stream/471b902a-fc87-4626-b5b6-ca848f470149:SIN2/master.m3u8

### Notes

Must-have

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by ovidiuux** [comment]
*https://edge-ar.rcs-rds.ro/digi24ar/hd.m3u8, e mai simplă adresa asta

**Comment by LaneSh4d0w** [comment]
> *https://edge-ar.rcs-rds.ro/digi24ar/hd.m3u8, e mai simplă adresa asta

nu este un playlist adaptiv, https://edge-ar.rcs-rds.ro/digi24ar/index.m3u8

**Comment by AntiPontifex** [comment]
Thank you: added for next release.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/ro.m3u#L26-L27
