### ISSUE TITLE
Add: Zu TV (Radio ZU)

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#10951]
### Channel ID

ZUTV.ro

### Stream URL

https://www.hlsrundle-stream-iptv.gq/api/hls/zutv.m3u8

### Notes

This streaming address is hosted by me before the Zu TV (Radio ZU) channel streaming address with token. I will keep these servers alive for a while, I also work on many other TV stations that have token streaming. Currently due to limited time, severe requirements, **is only available in a program such as VLC Player**. If I have support I will continue to work to improve it.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by adinaveh** [comment]
Thank you.

**Comment by AntiPontifex** [comment]
Again, thank you: will be included in the next release.
