### ISSUE TITLE
Add: Euronews Romania

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#10950]
### Channel ID

EuronewsRomania.ro

### Stream URL

https://www.hlsrundle-stream-iptv.gq/api/hls/euronews.m3u8

### Notes

This streaming address is hosted by me after the Euronews Romania channel streaming address with token. I will keep these servers alive for a while, I also work on many other TV stations that have token streaming. Currently due to limited time, severe requirements, **this WEB address is only available in a program** such as VLC Player. If I have support I will continue to work to improve it.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for taking these lengths to make this stream available: it will be included in the next release.
