### ISSUE TITLE
Add: RUV 2 [IS]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10964]
### Channel ID

RUV2.is

### Stream URL

https://ruvlive.akamaized.net/out/v1/2ff7673de40f419fa5164498fae89089/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.

**Comment by Smark223** [comment]
RUV2 is not already in the list

**Comment by AntiPontifex** [comment]
It is on my pull request: so, yes it is.

**Comment by Smark223** [comment]
> It is on my pull request: so, yes it is.

Apologies. Still fairly new to this. I should have checked.

**Comment by AntiPontifex** [comment]
Not a problem: input is always welcomed. ;)
