### ISSUE TITLE
Replace: Dreiko TV | DreikoTV.pa (Re-bump)

### ISSUE THREAD

**Issue by EnerGeekTeam** [iptv-org/iptv#10969]
### Broken Link

https://stmv3.voxtvhd.com.br/dreikotv/dreikotv/playlist.m3u8

### What happened to the stream?

Other

### Possible Replacement

https://cloudvideo.servers10.com:8081/8242/index.m3u8

### Notes

Link provided by DreikoTV's owner on personal conversation. Older link is saying that it's stream got updated and on February it'll stop working.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Thank you for telling us. PR is on its way for those channels.

**Comment by AntiPontifex** [comment]
Added: thank you.

**Comment by EnerGeekTeam** [comment]
Re-replace.

New link provided by Dreiko TV's owner: https://tv.fullhd-streaming.com:3807/live/dreikotvlive.m3u8

**Comment by EnerGeekTeam** [comment]
@AntiPontifex Mentioned because Dreiko changed yet again their m3u8.

**Comment by EnerGeekTeam** [comment]
Also @Carlinhos027 and @BellezaEmporium
