### ISSUE TITLE
Replace: Telenica Canal 8 (tn8) from Nicaragua

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#10968]
### Broken Link

http://138.117.4.70:8075/channel8/playlist.m3u8

### What happened to the stream?

Shows the wrong channel

### Possible Replacement

https://60417ddeaf0d9.streamlock.net/tn8/videotn8/chunklist_w624799796.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Thank you: added.
