### ISSUE TITLE
Replace: Canal 6 from Nicaragua

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#10967]
### Broken Link

http://138.117.4.70:8075/channel6/playlist.m3u8

### What happened to the stream?

Shows the wrong channel

### Possible Replacement

https://stream-01.nyc.dailymotion.com/sec(3LGBMbo2Zno2o8YrbIxOft3zOysrEd8LmwPNkiUR5Ms5beKIxsUlA9MNSb9TX1n6)/dm/3/x7nngbi/s/live-1.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Does not work.

**Comment by josepedro770** [comment]
Streaming link has changed:

https://stream-03.nyc.dailymotion.com/sec(3LGBMbo2Zno2o8YrbIxOfr-YcE8OpKCfi0MUX0ns02I-JOh-GrQ7CwuB2xpF6ZT_)/dm/3/x7nngbi/s/live-1.m3u8

It is available from https://canal6.com.ni/en-vivo/

**Comment by AntiPontifex** [comment]
That link is already on the list. Thank you anyway, please close.
