### ISSUE TITLE
Add: Canal 4 [Televisa Guadalajara] | (MX)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#10966]
### Channel ID

TelevisaGuadalajara.mx (XHG-TDT - Canal 4 Guadalajara)

### Stream URL

https://linear-402.frequency.stream/402/hls/master/playlist.m3u8

### Notes

YouTube Stream Link: https://free.fullspeed.tv/iptv-query?streaming-ip=https://youtube.com/@televisaguadalajara

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you: added for next release.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/mx.m3u#L100-L101
