### ISSUE TITLE
Replace: B1.ro (B1)

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#10976]
### Broken Link

https://stream.adunity.com/b1/b1.m3u8

### What happened to the stream?

Displays a message asking to renew subscription

### Possible Replacement

https://www.hlsrundle-stream-iptv.gq/api/hls/b1.m3u8

### Notes

This streaming address is **hosted by me** after the B1 România channel streaming address with token. I will keep these servers alive for a while, [I also work on many other TV stations that have token streaming.](https://github.com/ovidiuux/RundleTV-API/blob/main/ro.json) Currently due to limited time, severe requirements, **some channels** only available in a program such as VLC Player, but this can be used anywhere (HTML5, VLC, Mobile, Chrome, etc)  If I have support I will continue to work to improve it.  

It takes a maximum of 2-3 seconds to redirect you to the original streaming link provided by B1, with token.
_This link provides you token stream url by redirect._

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Again, thank you for taking these measures for the community.

**Comment by LaneSh4d0w** [comment]
I believe I know from where you get the link, but it seems the token is IP-locked. Using your URL doesn't seem to work on my side, although getting the link myself from https://www.b1tv.ro/wp-json/strawberry/v1/live works.

**Comment by ovidiuux** [comment]
> I believe I know from where you get the link, but it seems the token is IP-locked. Using your URL doesn't seem to work on my side, although getting the link myself from https://www.b1tv.ro/wp-json/strawberry/v1/live works.

Yes, this is where the source is. I forgot to pass the ip address. I will solve it soon, now I am trying to host UTV.ro

**Comment by LaneSh4d0w** [comment]
Should be pretty straight-forward for UTV, the token given on the URL should still work

**Comment by ovidiuux** [comment]
It's all right

**Comment by LaneSh4d0w** [comment]
Can confirm it works from the player, also works perfectly from the API. Nice work !
