### ISSUE TITLE
Replace: Ecuavisa from Ecuador

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#10973]
### Broken Link

https://mdstrm.com/live-stream-playlist/603ea23f928cc5255563012c.m3u8

### What happened to the stream?

Shows the wrong channel

### Possible Replacement

https://www.ecuavisa.com/envivo

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
https://mdstrm.com/live-stream-playlist/629fb071305b11082bce64e5.m3u8 but offline

**Comment by AntiPontifex** [comment]
Thank you: fixed.
