### ISSUE TITLE
Replace: Speranța TV

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#10979]
### Broken Link

http://play.streamkit.tv/content/channel/sperantatv/live/sperantatv.player.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://www.hlsrundle-stream-iptv.gq/api/hls/sperantatv.m3u8

### Notes

This streaming address is **hosted by me**. I will keep these servers alive for a while, [I also work on many other TV stations that have token streaming.](https://github.com/ovidiuux/RundleTV-API/blob/main/ro.json) Currently due to limited time, severe requirements, **some channels** only available in a program such as VLC Player. If I have support I will continue to work to improve it.  

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Thank you, as always: added.
