### ISSUE TITLE
Replace: EnerGeek Radio | EnerGeekRadio.cl

### ISSUE THREAD

**Issue by EnerGeekTeam** [iptv-org/iptv#10970]
### Broken Link

no link provided

### What happened to the stream?

Other

### Possible Replacement

https://stream.wifiexpert.cl/energeek/radio/playlist.m3u8

### Notes

Playlist didn't have link updated.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Can you confirm that, right now, the Radio is streaming what's being streamed on Energeek Animate ? Seems I see the same content for now.

**Comment by EnerGeekTeam** [comment]
At least at the moment it is, this because we're having a temporal alliance with another channel called TV Costa.

**Comment by LaneSh4d0w** [comment]
> At least at the moment it is, this because we're having a temporal alliance with another channel called TV Costa.

OK, changes are onboard, waiting for approval.
