### ISSUE TITLE
Replace: KanalD.ro

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#10978]
### Broken Link

https://stream1.kanald.ro/iphone/index.m3u8

### What happened to the stream?

Other

### Possible Replacement

https://stream1.kanald.ro/iphone/knd-live_low/index.m3u8

### Notes

The path to the .m3u8 segment file has been changed, this address is obtained from KanalD.ro
Thanks ,) 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Thank you: fixed.

**Comment by LaneSh4d0w** [comment]
Adaptive is https://stream1.kanald.ro/iphone/knd-live.m3u8
