### ISSUE TITLE
Add: Trinitas TV RO

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#10977]
### Channel ID

TrinitasTV.ro

### Stream URL

https://www.hlsrundle-stream-iptv.gq/api/hls/trinitastv.m3u8

### Notes

This streaming address is **hosted by me** I will keep these servers alive for a while, [I also work on many other TV stations that have token streaming.](https://github.com/ovidiuux/RundleTV-API/blob/main/ro.json) Currently due to limited time, severe requirements only available in a program such as VLC Player. If I have support I will continue to work to improve it.  

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you again, sir. Added.

**Comment by Badea19** [comment]
Salut Ovi, nu merge url tau , am incercat in tivimate. Daca poti sa i faci un update iti mulțumesc!
