### ISSUE TITLE
Replace: MoozRo

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#10980]
### Broken Link

https://rtmp.digitalbroadcast.ro/moozro/moozro.m3u8

### What happened to the stream?

Other

### Possible Replacement

https://www.hlsrundle-stream-iptv.gq/api/hls/moozro.m3u8

### Notes

This address is hosted by myself and is a reproduction (rebroadcast) for MoozRo where use in any streaming reference (reffer, cors, headers, origins) is allowed. (can be used in VLC, HTML5, Mobile, Chromecast, ...). I will keep these servers alive for a while, [I also work on many other TV stations that have token streaming.](https://github.com/ovidiuux/RundleTV-API/blob/main/ro.json) Currently due to limited time, severe requirements, **some channels** only available in a video player program such as VLC Player. If I have support I will continue to work to improve it.  

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Thank you again: added for next release.

**Comment by LaneSh4d0w** [comment]
I propose adding this one as the primary link, as the other one works with a referer.
