### ISSUE TITLE
Add: Antena 1

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#10981]
### Channel ID

Antena1.ro

### Stream URL

https://www.hlsrundle-stream-iptv.gq/api/hls/antena1.m3u8

### Notes

The content in the streaming address is **hosted by me** and I will **keep this server alive as long as I can**. I need support to support these servers After some contributions to iptv-org for Romania IPTV, I added the Romanian generalist channel, Antena 1, **PROTV is coming soon**. [I also work on many other TV stations that have token streaming.](https://github.com/ovidiuux/RundleTV-API/blob/main/ro.json) Currently due to limited time, severe requirements, **some channels** only available in a video player program such as VLC Player. 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you: added for next release.

**Comment by LaneSh4d0w** [comment]
Ah well, seems you've already found out how that works. Amazing !

**Comment by ovidiuux** [comment]
> Ah well, seems you've already found out how that works. Amazing !

UPDATE: https://hlsrundle-stream-iptv.gq/api/hls/antena1.m3u8 are now Adaptive Streaming, redirect from ivm.antenaplay.ro

**Comment by LaneSh4d0w** [comment]
> > Ah well, seems you've already found out how that works. Amazing !
> 
> UPDATE: https://hlsrundle-stream-iptv.gq/api/hls/antena1.m3u8 are now Adaptive Streaming, redirect from ivm.antenaplay.ro
> 

Perfect, hope my script did help a bit :)
