### ISSUE TITLE
Add: TV1 RTM

### ISSUE THREAD

**Issue by anomusopreker** [iptv-org/iptv#10984]
### Channel ID

TV1

### Stream URL

https://d25tgymtnqzu8s.cloudfront.net/smil:tv1/chunklist_b4596000_slENG.m3u8?id=1

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://d25tgymtnqzu8s.cloudfront.net/smil:tv1/manifest.mpd
