### ISSUE TITLE
Add: PRO TV

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#10998]
### Channel ID

ProTV.ro

### Stream URL

https://www.hlsrundle-stream-iptv.gq/api/hls/protv.m3u8

### Notes

The content in the streaming address is **hosted by me** and I will **keep this server alive as long as I can**. I need support to support these servers After some contributions to iptv-org for Romania IPTV, I added the Romanian generalist channel, PRO TV and Antena 1, **more is coming soon**. [I also work on many other TV stations that have token streaming.](https://github.com/ovidiuux/RundleTV-API) Currently due to limited time, severe requirements, **some channels** only available in a video player program such as VLC Player. 

[Launch PRO TV in  HTML5](https://rundle-live.vercel.app/live/protv)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you, sir: added.

**Comment by LaneSh4d0w** [comment]
Nice work @ovidiuux , if you want I can privately give you the base code I have for AntenaPlay channels, it used a certain flaw in ZuTVs live channel.

**Comment by ovidiuux** [comment]
> Nice work @ovidiuux , if you want I can privately give you the base code I have for AntenaPlay channels, it used a certain flaw in ZuTVs live channel.

Hi 👋

I have already created a main base where I have over 60+ Romanian channels. He wants to diversify, not to have only one provider, and of course I would like this code base for Antena channels. I am running on Vercel with NodeJS using NEXT.js 13 with Edge Functions to host these files.

**Comment by LaneSh4d0w** [comment]
> > Nice work @ovidiuux , if you want I can privately give you the base code I have for AntenaPlay channels, it used a certain flaw in ZuTVs live channel.
> 
> Hi 👋
> 
> I have already created a main base where I have over 60+ Romanian channels. He wants to diversify, not to have only one provider, and of course I would like this code base for Antena channels. I am running on Vercel with NodeJS using NEXT.js 13 with Edge Functions to host these files.

Sure, let me send you a collaboration invite for the repository.

**Comment by Rfy29** [comment]
> Good job @ovidiuux, if you want I can privately give you the base code I have for the AntenaPlay channels, it used a certain defect in the live channel at ZuTVs.
Hi, I want it too if you don't mind

**Comment by Rfy29** [comment]
> Buna treaba@ovidiuux, daca vrei iti pot da in privat codul de baza pe care il am pentru canalele AntenaPlay, a folosit un anumit defect in canalul live la ZuTVs.

**Comment by Rfy29** [comment]
Hi, I want too if you don't mind

**Comment by daeongithub** [comment]
Is this ever going to be added back?
