### ISSUE TITLE
Add: Hamburg 1 [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10999]
### Channel ID

Hamburg1.de

### Stream URL

https://hamburg1-jw.cdn.vustreams.com/live/09120205-afa3-4048-a965-318eb0cacffc/live.isml/.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you: added for next release.
