### ISSUE TITLE
Add: TV 1 [BG]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11007]
### Channel ID

TV1.bg

### Stream URL

https://tv1.cloudcdn.bg:8081/stream.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/bg.m3u#L44-L45
