### ISSUE TITLE
Add: OK-TV Ludwigshafen [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11001]
### Channel ID

OKTVLudwigshafen.de

### Stream URL

https://s.ok54.de/oklu/livestream/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
