### ISSUE TITLE
Add: Expressen TV [SE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11008]
### Channel ID

ExpressenTV.se

### Stream URL

https://cdn0-03837-liveedge0.dna.ip-only.net/03837-liveedge0/smil:03837-tx2/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.

**Comment by freearhey** [comment]
https://cdn0-03837-liveedge0.dna.ip-only.net/03837-liveedge0/smil:03837-tx2/playlist.m3u8
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/7253922/232248812-d3b1651b-f236-4973-9d6f-f9a2f0cfa95f.png">
