### ISSUE TITLE
Add: TV Mittelrhein [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11005]
### Channel ID

TVMittelrhein.de

### Stream URL

https://live2.telvi.de/hls/tvm_hd720.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
