### ISSUE TITLE
Add: Rennsteig TV [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11004]
### Channel ID

RennsteigTV.de

### Stream URL

http://wowza.telvi.de/rennsteigtv/stream_720p/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
