### ISSUE TITLE
Add: L-TV [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11000]
### Channel ID

LTV.de

### Stream URL

https://live2.telvi.de/hls/l-tv_s1.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be added for the next release.
