### ISSUE TITLE
Add: TV Ingolstadt [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11006]
### Channel ID

TVIngolstadt.de

### Stream URL

https://stream01.welocal.stream/stream/fhd-tvingolstadt_44349/ngrp:stream_all/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
