### ISSUE TITLE
Add: TFM [SN]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11019]
### Channel ID

TFM.sn

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/telefutursmedias

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/telefutursmedias (offline)
