### ISSUE TITLE
Add: P-TV [AT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11023]
### Channel ID

PTV.at

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/ptv_vienna

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the link: it will be included in the next release.
