### ISSUE TITLE
Add: ServusTV [AT] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11029]
### Channel ID

ServusTV.at

### Stream URL

https://stv-live.akamaized.net/hls/live/2031011/lingeoSTVATwebPri/master.m3u8

### Notes

Geo-blocked

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Dead link.
