### ISSUE TITLE
Add: WW TV [DE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11026]
### Channel ID

WWTV.de

### Stream URL

https://live2.telvi.de/hls/wwtv_hd720.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the link: it will be added next release.
