### ISSUE TITLE
Add: TV 1 Oberosterreich [AT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11022]
### Channel ID

TV1Oberosterreich.at

### Stream URL

https://streaming10.huberwebmedia.at/LiveApp/streams/238985177034727564068269_adaptive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.
