### ISSUE TITLE
Add: Volksmusik TV [DE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11027]
### Channel ID

VolksmusikTV.de

### Stream URL

https://vmtv.iptv-playoutcenter.de/vmtv/vmtv1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
