### ISSUE TITLE
Add: Sachsen Fernsehen Vogtland [DE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11025]
### Channel ID

SachsenFernsehenVogtland.de

### Stream URL

http://vogtland.iptv-playoutcenter.de/vogtland/vogtlandfernsehen.stream_1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the link: it will be added next release.
