### ISSUE TITLE
Add: PTV [PH]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11021]
### Channel ID

PTV.ph

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/peoples-television-incorporated

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/peoples-television-incorporated (offline)
