### ISSUE TITLE
Add: Welt der Wunder TV [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11028]
### Channel ID

WeltderWunderTV.de

### Stream URL

https://wdw.iptv-playoutcenter.de/wdw/wdw1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.
