### ISSUE TITLE
Add: QVC Germany [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11033]
### Channel ID

QVCGermany.de

### Stream URL

https://d2mn03dhv5o3g8.cloudfront.net/live/qvcde_main_clean/bitrate1.isml/3/prog_index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
