### ISSUE TITLE
Add: More Than Sports TV [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11032]
### Channel ID

MoreThanSportsTV.de

### Stream URL

https://mts1.iptv-playoutcenter.de/mts/mts-web/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
