### ISSUE TITLE
Add: MDR Fernsehen Sachsen [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11034]
### Channel ID

MDRFernsehenSachsen.de

### Stream URL

https://mdrtvsnhls.akamaized.net/hls/live/2016928/mdrtvsn/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Geo-Blocked (in Canada). Thank you for the stream: it will be included in the next update.
