### ISSUE TITLE
Add: MDR Fernsehen Sachsen-Anhalt [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11035]
### Channel ID

MDRFernsehenSachsenAlhalt.de

### Stream URL

https://mdrtvsahls.akamaized.net/hls/live/2016879/mdrtvsa/index.m3u8

### Notes

Geo-blocked

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Geo-blocked (in Canada). Thank you for the stream: it will be included in the next update.
