### ISSUE TITLE
Add: DASDING 90.8 [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11030]
### Channel ID

DASDING908.de

### Stream URL

https://swrdasdingvr-hls.akamaized.net/hls/live/2018681/dasdingvr/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
