### ISSUE TITLE
Add: MDR Fernsehen Thuringen [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11036]
### Channel ID

MDRFernsehenThuringen.de

### Stream URL

https://mdrtvthhls.akamaized.net/hls/live/2016880/mdrtvth/index.m3u8

### Notes

Geo-blocked

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Geo-blocked (in Canada). Thank you for the stream: it will be included in the next release.
