### ISSUE TITLE
Add: Rockland TV [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11037]
### Channel ID

RocklandTV.de

### Stream URL

https://live.creacast.com/rockland-radio/smil:rockland-radio.smil/playlist.m3u8

### Notes

Geo-blocked

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Geo-blocked (in Canada)? Thank you for the stream: it will be included in the next release.
