### ISSUE TITLE
Add: Sonnenklar TV

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11038]
### Channel ID

SonnenklarTV.de

### Stream URL

http://edge0751-05mx1.flex-cdn.net/5aa69cf6f508dc63fb212f76fc955c22a8ec7e49804ec35e2e94/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
