### ISSUE TITLE
Add: EWTN Germany [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11031]
### Channel ID

EWTNGermany.de

### Stream URL

https://cdn3.wowza.com/1/ZUkxSDBrZHlMbjVn/ZkhNRFNZ/hls/live/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
