### ISSUE TITLE
Add: SWR Fernsehen Rheinland-Pfalz [DE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11040]
### Channel ID

SWRFernsehenRheinlandPfalz.de

### Stream URL

https://swrrpd-hls.akamaized.net/hls/live/2018676/swrrpd/master.m3u8

### Notes

Geo-blocked

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Geo-blocked (in Canada). Thank you for the stream: it will be included in the next release.
