### ISSUE TITLE
Add: Shamshad TV [AF]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11048]
### Channel ID

ShamshadTV.af

### Stream URL

https://5a1178b42cc03.streamlock.net/shamshadtelevision/shamshadtelevision/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://5a1178b42cc03.streamlock.net/shamshadtelevision/shamshadtelevision/playlist.m3u8
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/7253922/232253820-c479497a-d370-4b47-984a-be91c62e1dea.png">

**Comment by freearhey** [comment]
https://5a1178b42cc03.streamlock.net/shamshadtelevision/shamshadtelevision/playlist.m3u8 (offline)
<img width="652" alt="image" src="https://user-images.githubusercontent.com/7253922/233809955-c22ebb3f-7e9a-440c-97ec-3b0ea6dfa53e.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/af.m3u#L26-L27
