### ISSUE TITLE
Add: Best Cable Peru [PE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11047]
### Channel ID

BestCablePeru.pe

### Stream URL

https://ca2.inka.net.pe/bestcable/index.m3u8

### Notes

Sports: https://ca2.inka.net.pe/bestcablesports/index.m3u8
Music: https://ca2.inka.net.pe/bestcablemusic/index.m3u8
Cumbia: https://ca2.inka.net.pe/mascumbiatvonline/index.m3u8
Hatun TV: https://ca2.inka.net.pe/bestcablehatuntv/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you very much for the streams: they will be added next release.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/pe.m3u#L22-L23
