### ISSUE TITLE
Add: M4TV [AT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11041]
### Channel ID

M4TV.at

### Stream URL

https://streaming.m4tv.at/live/m4tv.stream/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
