### ISSUE TITLE
Add: Antena 21 [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11042]
### Channel ID

Antena21,do

### Stream URL

https://d3qhvst5vzq4y9.cloudfront.net/hls/canal21.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
