### ISSUE TITLE
Add: Televisora de Oriente [VE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11057]
### Channel ID

TelevisoradeOriente.ve

### Stream URL

https://cloud.streamingconnect.tv/hls/tvo/tvo.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/ve.m3u#L41-L42
