### ISSUE TITLE
Add: TV 2 Syd [DK]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11058]
### Channel ID

TV2Syd.dk

### Stream URL

https://cdn-lt-live.tvsyd.dk/env/cluster-1-e.live.nvp1/live/hls/p/1956351/e/0_e9slj9wh/tl/main/st/0/t/rFEtaqAbdhUFGef_BNF4WQ/index-s33.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.

**Comment by freearhey** [comment]
https://cdn-lt-live.tvsyd.dk/env/cluster-1-e.live.nvp1/live/hls/p/1956351/e/0_e9slj9wh/tl/main/st/0/t/rFEtaqAbdhUFGef_BNF4WQ/index-s33.m3u8
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/7253922/232254143-ec38ae9a-4f20-4254-afa3-59cf81ab37ea.png">
