### ISSUE TITLE
Add: Tele Antillas [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11059]
### Channel ID

TeleAntillas.do

### Stream URL

https://tunzilla.com/http://51.81.106.157:8084/hls/tantillas.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
