### ISSUE TITLE
Replace: Telecuracao

### ISSUE THREAD

**Issue by Boxiet** [iptv-org/iptv#11053]
### Broken Link

https://streannlivecariflix.cachefly.net/cariflix1/cariflix1/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://telecuracao.com/

### Notes

Working stream is using embedded video from: https://ott3.streann.com/a334590e-3519-4224-a4c8-4c2e58a6f644

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Thank you for the notification; found a stream, but needs verifying.

**Comment by LaneSh4d0w** [comment]
https://ott3.streann.com/loadbalancer/services/public/channels/5ed71e232cdc24a3d08cd6de/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you, Lane. Duplicate stream: please close.

**Comment by Boxiet** [comment]
Still not working guys.

**Comment by AntiPontifex** [comment]
You'll have to wait until my pull request is merged. Until then...

**Comment by freearhey** [comment]
https://ott3.streann.com/loadbalancer/services/public/channels/5ed71e232cdc24a3d08cd6de/playlist.m3u8 (offline)
<img width="755" alt="image" src="https://user-images.githubusercontent.com/7253922/232261148-4799b6a5-97ea-4552-b35b-f84948a08ac3.png">
