### ISSUE TITLE
Add: VTV Can Tho

### ISSUE THREAD

**Issue by nguyenthienminh** [iptv-org/iptv#11052]
### Channel ID

VTVCanTho.vn

### Stream URL

https://sgn-vtt-002-livecdn-vthn-vnd.vieon.vn/9c749012c53ec207f68f84667bfed720/1672474511017/vtc/live/hd_vtv_cantho/playlist.m3u8

### Notes

Replaces VTV6 because VTV6 closed down on October 10th, 2022. Don't know if it will break or not in the future. Also, I got the link from [here](https://vieon.vn/truyen-hinh-truc-tuyen/vtv-can-tho/), official link

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Sounds like the middle part is changing over time. Unless we have a plugin that gets it all the time... it'll be complicated.

The vietnam IPs I have are way too slow to even access VieON, so it'll be complicated to judge over that.

**Comment by nguyenthienminh** [comment]
It doesn't actually change over time. I tried accessing it right now (16 hours later) and the stream link still works.

**Comment by LaneSh4d0w** [comment]
https://vips-livecdn.fptplay.net/hda1/vtvcantho_vhls.smil/playlist.m3u8 as adaptive, let me check with a Vietnamese IP since this one also returns a 403.

**Comment by LaneSh4d0w** [comment]
The FPTPlay link works with a Vietnamese IP, not the VieON one.

**Comment by freearhey** [comment]
https://5a1178b42cc03.streamlock.net/shamshadtelevision/shamshadtelevision/playlist.m3u8 (offline)

https://vips-livecdn.fptplay.net/hda1/vtvcantho_vhls.smil/playlist.m3u8 (offline)

**Comment by nguyenthienminh** [comment]
Here's another link that works (for the meantime): https://vips-livecdn.fptplay.net/hda1/vtvcantho_vhls.smil/chunklist_b2500000.m3u8

**Comment by freearhey** [comment]
https://vips-livecdn.fptplay.net/hda1/vtvcantho_vhls.smil/chunklist_b2500000.m3u8 (offline)
<img width="587" alt="image" src="https://user-images.githubusercontent.com/7253922/232262062-0b0ef87f-8aa7-4458-a42d-289db7fe3c91.png">

**Comment by nguyenthienminh** [comment]
The stream still plays correctly though. 
![image](https://user-images.githubusercontent.com/86407326/232262473-a6ee23e1-5ec0-4447-88eb-6975d54e2e29.png)
