### ISSUE TITLE
Add: WFMZ

### ISSUE THREAD

**Issue by Arkina1234** [iptv-org/iptv#11051]
### Channel ID

WFMZDT1.us

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Arkina1234** [comment]
https://www.wfmzplus.com/

**Comment by LaneSh4d0w** [comment]
dunno why it disappeared, reinstated it in PR.
