### ISSUE TITLE
Add: Vepaco TV [VE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11056]
### Channel ID

Vepaco.ve

### Stream URL

https://cloud.streamingconnect.tv/hls/vepacotv/vepacotv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/ve.m3u#L56-L57
