### ISSUE TITLE
Add: Maimon TV Canal 3 [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11060]
### Channel ID

MaimonTVCanal3.do

### Stream URL

https://ss3.domint.net:3138/mtv_str/maimon/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Geo-blocked (from Canada)? Thank you for the stream: it will be included in the next release.

**Comment by Dra1922** [comment]
https://iptv-org.github.io/iptv/countries/ar.m3u
