### ISSUE TITLE
Add: Telealtura [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11064]
### Channel ID

Telealtura.do

### Stream URL

https://pacific.direcnode.com:3250/live/telealturalive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
