### ISSUE TITLE
Add: Senales TV [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11063]
### Channel ID

SenalesTV.do

### Stream URL

https://live.teledom.info:4000/live/senalestvlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
