### ISSUE TITLE
Add: Telever [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11069]
### Channel ID

Telever.do

### Stream URL

https://megastreamm.com:3484/live/televerlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
