### ISSUE TITLE
Add: Telesistema [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11061]
### Channel ID

Telesistema.do

### Stream URL

https://tunzilla.com/http://51.81.93.239:8084/hls/tsistemas.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
