### ISSUE TITLE
Add: Mun2TV [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11065]
### Channel ID

Mun2TV.do

### Stream URL

https://play.amelbasoluciones.co:3309/live/mun2tvlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
