### ISSUE TITLE
Add: Telecanal 12 [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11067]
### Channel ID

Telecanal12.do

### Stream URL

https://cdn4.hostlagarto.com:8081/static/telecanal12/chunks.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
