### ISSUE TITLE
Add: Nexxo TV [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11066]
### Channel ID

NexxoTV.do

### Stream URL

https://cdn3.streamgato.us:3938/live/nexxotvlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
