### ISSUE TITLE
Add: Chinola TV [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11062]
### Channel ID

ChinolaTV.do

### Stream URL

https://cdn3.streamgato.us:3434/live/chinolatvlive.m3u8?DVR

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
