### ISSUE TITLE
Add: TVS [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11068]
### Channel ID

TVS.do

### Stream URL

http://cm.hostlagarto.com:8081/Tvstv/TvstvHD.myStream/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
