### ISSUE TITLE
Add: TNI Canal51 [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11070]
### Channel ID

TNICanal51.do

### Stream URL

https://ss5.domint.net:3188/tni_str/tni51/playlist.m3u8

### Notes

Not 24/7

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
