### ISSUE TITLE
Add: Television A1 [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11073]
### Channel ID

TelevisionA1.do

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/1a1_live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
