### ISSUE TITLE
Add: Televida [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11072]
### Channel ID

Televida.do

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/televidaenvivo

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will included in the next release.
