### ISSUE TITLE
Add: TRA 2 [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11071]
### Channel ID

TRA2.do

### Stream URL

https://live.teledom.info:3242/live/teleradiohdlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
