### ISSUE TITLE
Add: NHK World Premium [JP]

### ISSUE THREAD

**Issue by ZXArkin** [iptv-org/iptv#11084]
### Channel ID

NHKWorldPremium.jp

### Stream URL

https://nhkwlive-pre-in.webcdn.stream.ne.jp/hls/live/nhkwlive-pre/index_1M.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by freearhey** [comment]
Duplicate of #10955
