### ISSUE TITLE
Add: TF1 (France)

### ISSUE THREAD

**Issue by jo-a11y** [iptv-org/iptv#11100]
### Channel ID

tf1.fr

### Notes

TF1 is the the most watched TV channel in Europe.

It would be nice if it were possible to add the other channels of the TF1 group: TF1, TMC, TFX and TF1 Séries Films

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Links to legal streams?

**Comment by jo-a11y** [comment]
TF1 broadcasts these programs for free at this address
https://www.tf1.fr/tf1/direct but it is geographically blocked.
A few weeks ago the channel was present in the iptv-org links.

Le mer. 4 janv. 2023 à 08:05, AntiPontifex ***@***.***> a
écrit :

**Comment by jo-a11y** [comment]
TF1 broadcasts these programs for free at this address https://www.tf1.fr/tf1/direct but it is geographically blocked.
A few weeks ago the channel was present in the iptv-org links.

**Comment by LaneSh4d0w** [comment]
Well they change the links a lot for TF1, not for the other streams as far as I've seen.

FR : Ils changent beaucoup de liens pour TF1 mais pas les autres de ce que j'ai vu

**Comment by LaneSh4d0w** [comment]
try this : https://live-tf1-das-secure.cdn-0.diff.tf1.fr/out/v1/98f48bb09cf04832a076ef2aa2f3394d/index.mpd

**Comment by LaneSh4d0w** [comment]
Alt https://tf1-hls-live-cdn1.tf1.fr/out/v1/c2e382be3aa2486e8753747e7bb6157e/index.m3u8
