### ISSUE TITLE
Add: Cowboy Channel

### ISSUE THREAD

**Issue by Arkina1234** [iptv-org/iptv#11109]
### Channel ID

CowboyChannel.us

### Stream URL

https://rfdtv-jw.cdn.vustreams.com/live/e72bcb8b-2e76-49d6-99e9-c09d224e8bdf/live.isml/e72bcb8b-2e76-49d6-99e9-c09d224e8bdf.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be added for the next release.

**Comment by freearhey** [comment]
https://rfdtv-jw.cdn.vustreams.com/live/e72bcb8b-2e76-49d6-99e9-c09d224e8bdf/live.isml/e72bcb8b-2e76-49d6-99e9-c09d224e8bdf.m3u8
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/7253922/232254276-04af23f1-57a1-41ec-b473-f135912c6d04.png">
