### ISSUE TITLE
Add: TFX (FRANCE)

### ISSUE THREAD

**Issue by jo-a11y** [iptv-org/iptv#11102]
### Channel ID

TFX.fr

### Notes

The channel live link : https://www.tf1.fr/tfx/direct

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://live-tfx-das.cdn-0.diff.tf1.fr/video/gTus58EzLk8NNiAEcFH8zQ/1672867306/out/v1/233038e4d07f4416a0eb8598f241d9ea/index.mpd

**Comment by LaneSh4d0w** [comment]
Alt https://tfx-hls-live-cdn1.tf1.fr/out/v1/818e38d791854222b71a950791fb7002/index.m3u8

**Comment by AntiPontifex** [comment]
Thank you, Lane. Added for next release.
