### ISSUE TITLE
Add: TMC (France)

### ISSUE THREAD

**Issue by jo-a11y** [iptv-org/iptv#11101]
### Channel ID

TMC.fr

### Notes

The channel live link : https://www.tf1.fr/tmc/direct

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Links to legal streams?

**Comment by LaneSh4d0w** [comment]
https://live-tmc-das.cdn-0.diff.tf1.fr/video/-nxaJD-iJ6alxOvjtbIpqQ/1672867265/out/v1/39e5bad5774f42fd8941edff13ff5072/index.mpd

**Comment by LaneSh4d0w** [comment]
Alt https://tmc-hls-live-cdn1.tf1.fr/out/v1/982927d0b5d24bd58ac42184b10c63d7/index.m3u8
