### ISSUE TITLE
Add: Film Box

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#11118]
### Channel ID

FilmBoxPremiumRomania.ro

### Stream URL

http://94.230.240.17:8080/film_box/index.m3u8

### Notes

24/7. 
http://94.230.240.17:8080/film_box/tracks-v1a1/mono.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by ovidiuux** [comment]
Or: http://94.230.240.17:8080/film_box/tracks-v1a1/mono.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by freearhey** [comment]
http://94.230.240.17:8080/film_box/index.m3u8
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/7253922/232254351-3dc3b1d2-c9cb-4ce1-ab88-846e6c362a4f.png">
