### ISSUE TITLE
Add: Big brother vip Albania live

### ISSUE THREAD

**Issue by Protege16** [iptv-org/iptv#11124]
### Channel ID

Digitalb.al

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/bigbrothervipalbb
