### ISSUE TITLE
Add: Rock TV

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#11123]
### Channel ID

RockTV.ro

### Stream URL

https://tv.broadcasting.ro/memfs/85c83a80-4f71-4f2d-a8d6-43f676896bcb.m3u8

### Notes

From RockTV website

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by ovidiuux** [comment]
you forgot that

**Comment by JohnyGR22** [comment]
Broken link
