### ISSUE TITLE
Replace: Virgin Radio TV 

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#11121]
### Broken Link

https://live2-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(ew)/index.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://live3.msr.cdn.mediaset.net/content/dash_d0_clr_vos/live/channel(ew)/manifest.mpd

### Notes

From Virgin Radio TV.it website

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Not sure if Virgin Radio is permitted: I'll let others chime in.

**Comment by LaneSh4d0w** [comment]
not sure about this one either.

**Comment by freearhey** [comment]
https://live3.msr.cdn.mediaset.net/content/dash_d0_clr_vos/live/channel(ew)/manifest.mpd (error 403)
<img width="269" alt="image" src="https://user-images.githubusercontent.com/7253922/232261221-4ab26a56-b880-42bc-a074-bb71a39d9f22.png">
