### ISSUE TITLE
Add: EtosoTV

### ISSUE THREAD

**Issue by mrdannyarmstrong** [iptv-org/iptv#11127]
### Channel ID

ETSO-WTV

### Stream URL

https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1673083500/ei/DOa4Y4kek6fWAoWHgsgP/ip/92.205.15.128/id/b1WNdKXHxDk.1/source/yt_live_broadcast/requiressl/yes/hfr/1/playlist_duration/30/manifest_duration/30/maudio/1/vprv/1/go/1/pacing/0/nvgoi/1/keepalive/yes/fexp/24007246/dover/11/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cplaylist_duration%2Cmanifest_duration%2Cmaudio%2Cvprv%2Cgo%2Citag%2Cplaylist_type/sig/AOq0QJ8wRQIhAPjfm48EiOM6CVF5b2Gmm9R4TkDep_kmtpyNX2Iz97N-AiAS_qhDy6oC2En5qAnP3CRtRiP-z7xMs-1SxPfJ7LX6HQ%3D%3D/file/index.m3u8

### Notes

Esperanto TV Station

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Where is this channel located geographically?

**Comment by mrdannyarmstrong** [comment]
Stream down nevermind
