### ISSUE TITLE
Replace: VIU TV 6 [Hong Kong]

### ISSUE THREAD

**Issue by lawange** [iptv-org/iptv#11139]
### Broken Link

https://live.astradamy.com/viutv6/index.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://live.astradamy.com/viutv6/index.m3u8
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/7253922/232261291-e9df65eb-3686-4d04-b07f-b32bb549452a.png">
