### ISSUE TITLE
Add: MagicTV.ro

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#11134]
### Channel ID

MagicTV.ro

### Stream URL

https://tv.broadcasting.ro/memfs/925f90db-5c88-4190-a53d-5163cdffe6f4.m3u8

### Notes

From magictv website

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the link: it will be included in the next release.
