### ISSUE TITLE
Add: UTV.ro

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#11144]
### Channel ID

UTV.ro

### Stream URL

https://hlsrundle-stream-iptv.gq/api/hls/utv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by LaneSh4d0w** [comment]
Works for me, nice job !

**Comment by ovidiuux** [comment]
> Works for me, nice job !

For https://balancer.......ro/streamer.php?&key=00000000000000000000000000000000
It works anyway, there is no need to send a request to /make_key.php

**Comment by freearhey** [comment]
https://hlsrundle-stream-iptv.gq/api/hls/utv.m3u8
<img width="376" alt="image" src="https://user-images.githubusercontent.com/7253922/232146306-52c938b3-a3fe-4ca4-ba0a-d3cdd6dfff6a.png">

https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/ro.m3u#L89-L90
