### ISSUE TITLE
Replace: Telearuba Link

### ISSUE THREAD

**Issue by Boxiet** [iptv-org/iptv#11143]
### Broken Link

http://cdn.setar.aw:1935/Telearuba/smil:telearuba.smil/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://telearuba.aw/watchlive

### Notes

Channel is not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Thank you for the replacement stream: it will be included in the next release.

**Comment by LaneSh4d0w** [comment]
The website provided gives this resource : https://cdn01.setar.aw/Telearuba/telearuba/playlist.m3u8

**Comment by freearhey** [comment]
https://cdn01.setar.aw/Telearuba/telearuba/playlist.m3u8 (offline)
<img width="400" alt="image" src="https://user-images.githubusercontent.com/7253922/232261335-88bacdd1-b66a-4654-a004-422c6b961edb.png">
