### ISSUE TITLE
Replace: Yonhap News TV

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#11149]
### Broken Link

http://mytv.dothome.co.kr/ch/catv/216.php

### What happened to the stream?

Not loading

### Possible Replacement

https://wms211-kortv.akamaized.net/a_live/34402987/smil:20ch211.smil/chunklist_b2500000.m3u8

### Notes

Must be replaced

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
https://wms211-kortv.akamaized.net/a_live/34402987/smil:20ch211.smil/master.m3u8 adaptive

**Comment by freearhey** [comment]
The broken link has been removed.

The new link is broadcasting some other channel:

https://wms211-kortv.akamaized.net/a_live/34402987/smil:20ch211.smil/master.m3u8
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/7253922/232210274-1cddeae4-38b0-4572-b570-d3f01c07aabc.png">
