### ISSUE TITLE
Clarification needed about the tvg-language attribute

### ISSUE THREAD

**Issue by ksl1989** [iptv-org/iptv#1115]
In the [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md) is says of the `tvg-language` attribute:

> Channel language. The name of the language must conform to the standard ISO 639-1 (optional)

But actually I see all lists use the English name of the language, not the codes defined in the ISO 639-1 standard. E.g. the ISO 639-1 code for English is `en`, but English channels are defined as `tvg-language="English"`, not `tvg-language="en"`.

So I would like to ask:

1. Are the lists wrong or the guide wrong? Should it say "the English name of the languages in the ISO 639-1 standard"? If so how do you decide the which name is valid when a language is known by more than one English name (e.g. Spanish/Castilian)? Note the the names of the languages in the [linked Wikipedia article](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) may not be exactly the same as the the [official list](https://www.loc.gov/standards/iso639-2/php/English_list.php). The same language being known by different names is the reason for having standard codes.
2. Is using ISO 639-1 part of some standard for IPTV m3u lists? I couldn't find any standard. If no, why use it? ISO 639-3 would be more appropriate has it includes more languages. E.g. 639-1 only includes the macrolanguage Chinese, while 639-3 has Mandarin and Cantonese. "Chinese" isn't very useful in this case since these languages aren't mutually intelligible.
3. Is repeating the attribute allowed? Some channels broadcast in more than one language, and for Chinese channels it makes sense to define as both Chinese and as the language/'lect actually spoken.

**Comment by freearhey** [comment]
This attribute is used primarily to automatically sort channels by language. And since there really is no standard, ISO 639-1 was chosen as the most popular one. To simplify the process, it was decided to specify "ISO language name" instead of its code. And you're right, maybe it's better to write "the English name of the languages in the ISO 639-1 standard."

As for replacing ISO 639-1 with ISO 639-3, I have nothing against it.

**Comment by ksl1989** [comment]
Alright, so if I understand correctly you're not actually using ISO 639-1 codes, just using it as a handy list of language names. That's okay, I just wanted that to be clear.

Since you're not using the standard codes, replacing 639-1 for -3 makes no difference for the language names already used (the English name for the languages is the same) but it would allow for specifying more languages. I suggest you do this. (Most languages that aren't in -1 will have relatively few speakers and probably no TV channel, but the Chinese case is tricky and it would be good to have Mandarin, Cantonese and Hokkien as choices).

That leaves the question, is defining multiple languages supported?

**Comment by freearhey** [comment]
At the moment, you can only specify one `tvg-language` attribute and only one language in the channel description. But as an option, we can simply specify languages via semicolon, like so: 

```
... tvg-language="English;Chinese" ...
```

**Comment by ksl1989** [comment]
Okay, if the semicolon format is supported that will do.

**Comment by themak1985** [comment]
Super interesting conversation - thanks for kicking it off @ksl1989. I have some concerns with using ISO 639-3. Take a look at Arabic - it splits it off into 20~ languages - most are mutually intelligible with each other (or a large subsection).

A much smaller example is that there are about 6 channels that are a form of Aramaic and there are 3 639-3 language codes that are mutually intelligible. They would need to be in all 3.

With all the flexibility you get with 639-3, you get even more complexity. 639-1 has 184 languages - 639-3 has over 500.  

As for the semicolon - I think that's great. Not sure if that would affect how grouping is handled in the main all language playlist. I could also see this being helpful for channels from non-english speaking countries that broadcast english language and subtitle in their native language - there are a lot of those. I am sure this would apply to other languages, but I could see the english language playlist exploding. Right now - I have been labeling many channels that broadcast in english but subtitle in Arabic as Arabic, as that is the intended audience. Some Japanese Anime channels, subtitled in Vietnamese, as Vietnamese as that is the intended audience. 

Maybe one way to get around all this is the following:

- Adopt 639-3 codes for all existing 639-1 languages in repository.
- On an adhoc basis include some 639-3 languages for inclusion after community review and discussion.  (Keep an ongoing list somewhere)
-Use semicolon for adding multiple languages but criteria for additional languages is limited to: Language Family (Chinese; Yue Chinese), Mutually Intelligible (Kurdish; Northern Kurdish; Southern Kurdish) (Hindi; Urdu), or broadcasts audio or subtitles 50% or more in another language (Arabic; English) (Arabic; Hindi)

As I wrote this, I wondered, how would Hindi speakers feel about channels targeted to Arabic audiences on their language playlist, or Urdu which is essentially the same language but spoken in Pakistan and uses a different writing system. 

Lots to think about.

**Comment by ksl1989** [comment]
It's good to see there is interest in this issue. Let me start with the two specific examples mentioned:
* Arabic — it is true there are dozens of Arabic variants in 639-3 but all languages in 639-1 still exist. The corresponding 639-3 code for 639-1's `ar`, Arabic,  is `ara`, Arabic. I see no need to stop using "Arabic" as the language for these channels if that's how most speakers refer to the language and that's the language the channels present themselves as broadcasting. In fact I don't expect many channels to be in a language that isn't available in 639-1. Just because there are hundreds more languages available (many of them dead), it doesn't mean we need to define the language as narrowly as possible.
* Aramaic — There are 5 forms of living Aramaic in 639-3 and 0 in 639-1 (3 in 639-2). If we are to use a standard, any standard, there is no good solution here, but 639-3 doesn't make things worse here, if anything it makes it better by giving more options (or as bad, as those aren't good options).

As for subtitled channels, I think for the most part we should define the language as that of the intended audience. If a channel, say an Arabic channel, is _entirely_ in English with Arabic subtitles I think it's reasonable to add English as language, but it would have to be a situation in which an English speaker would understand every programme, there would no non-English content, and that means to do this you would need to know the channel well. I don't expect there would be many channels like this, so I don't think the English playlist would "explode".

The points I'm trying to make are:
1. If we are to use a standard, ISO 639-3 is preferable to 639-1 since is has more languages, while including all in 639-1.
2. It is true it can be confusing to know what language name to use, especially for people who are not used to this kind of thing (not to go into technical linguistic details and discussions of what counts as a language). So an ad hoc list is also perfectly fine, as long as it's clear where this list is. I think it's appropriate to just take the language names from 639-1 and add as needed. Users who need new languages added can open and issue.

Since the language codes aren't actually being used — which is what the standards actually define — it doesn't matter if there is a standard being followed or not, we just need a clear list of languages to pick from and, preferably, the option to pick more than one.

**Comment by freearhey** [comment]
I think it's worth explaining why ISO standard is used in the first place. 

First of all, ISO standard is needed to maintain correspondence between the language specified in the `tvg-language` attribute and the file name in which the given channel should be placed.

```js
tvg-language="Arabic" // => languages/ar.m3u
```

What to specify in the `tvg-language` attribute does not matter in this case. It can be either the English name of the language or any of the codes (ISO 639-1/2/3). The name of the language was chosen only because it is easier to read and can also be used to sort channels in IPTV players. 

So there is no difficulty in starting to use the ISO 639-3 standard, except that we will need to update scripts before doing so or playlists will just stop being generated. And as soon as I have time for that, I will definitely do it.

**Comment by ksl1989** [comment]
Reading your explanation it seems all than need to be done is to amend the scripts to use the three-letter ISO 639-3 code rather than the two-letter ISO 639-1 one. E.g.:

```
tvg-language="Arabic" // => languages/ara.m3u
```

rather than


```
tvg-language="Arabic" // => languages/ar.m3u
```

This is allow for languages that aren't in 639-1 without changing anything in the lists. But be sure to make it clear the names used should be the English language name from the [official code table](https://iso639-3.sil.org/code_tables/639/data) because some of the names aren't exactly obvious. E.g. Taiwanese Hokkien (often just called Taiwanese) is "Min Nan Chinese" on this list, since they consider it a variant of Min Nan. I know of at least one channel in Hakka and Hokkien and of course many in Cantonese — a good number of them already here, that's my main reason for starting this discussion.

Also, @freearhey, I would like you to confirm if the semicolon separated format is already supported or if it is something you would like to add.

**Comment by freearhey** [comment]
@ksl1989 The semicolon in the `tvg-language` attribute is not supported at this time, but I plan to make the necessary changes as soon as I have free time.

**Comment by freearhey** [comment]
Done.
