### ISSUE TITLE
Add: Guaymate TV [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11158]
### Channel ID

GuaymateTV.do

### Stream URL

https://5790d294af2dc.streamlock.net:443/8100/8100/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Will check this streamlock for more channels.

Available [here}(https://github.com/iptv-org/iptv/discussions/5190) are several channels from LATAM.

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by guaymatetv** [comment]
https://glb.bozztv.com/glb/ssh101/guaymatetv/index.m3u8  SALUDO LIDE POR FABOR CABIA ELIN   DE GUAYMATE TV  ESTE EL NUEVO POR FV

**Comment by guaymatetv** [comment]
> ### Identificación del canal
> GuaymateTV.do
> 
> ### URL de transmisión
> https://5790d294af2dc.streamlock.net:443/8100/8100/playlist.m3u8
> 
> ### Notas
> _Sin respuesta_
> 
> ### Por favor confirme lo siguiente
> * [x] He leído [la Guía de contribución](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

https://glb.bozztv.com/glb/ssh101/guaymatetv/index.m3u8  SALUDO LIDE POR FABOR CABIA ELIN   DE GUAYMATE TV  ESTE EL NUEVO POR FV

**Comment by guaymatetv** [comment]
https://ssh101stream.ssh101.com/akamaissh101/ssh101/guaymatetv/playlist.m3u8

**Comment by zasleynicole-ux** [comment]
https://live20.bozztv.com/akamaissh101/ssh101/guaymatetv/playlist.m3u8
