### ISSUE TITLE
Add: La Voz de Maria [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11159]
### Channel ID

LaVozdeMaria.do

### Stream URL

https://uni01rtmp.tulix.tv/playout2multi9/lavozdemaria.stream/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
