### ISSUE TITLE
Add: Activa TV [BO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11165]
### Channel ID

ActivaTV.bo

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/activatvhn43

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
