### ISSUE TITLE
Add: Abya Yala TV [BO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11164]
### Channel ID

AbyaYalaTV.bo

### Stream URL

https://master.tucableip.com/abyayalatv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
