### ISSUE TITLE
Add: Ceacom [BO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11167]
### Channel ID

Ceacom.bo

### Stream URL

https://cloud2.streaminglivehd.com:1936/ceacom/ceacom/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream does not work: geo-blocked?
