### ISSUE TITLE
Add: Cadena A [BO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11163]
### Channel ID

CadenaA.bo

### Stream URL

https://5e50264bd6766.streamlock.net/cadenaa/videocadenaa/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
