### ISSUE TITLE
Add: Erbol [BO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11169]
### Channel ID

Erbol.bo

### Stream URL

https://cloud2.streaminglivehd.com:1936/8182/8182/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
