### ISSUE TITLE
Add: TeleAragua [VE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11162]
### Channel ID

TeleAragua.ve

### Stream URL

http://45.173.198.59:8080/hls/nginx3.m3u8?tla

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/ve.m3u#L35-L36
