### ISSUE TITLE
Add: CVC [BO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11168]
### Channel ID

CVC.bo

### Stream URL

https://5d00db0e0fcd5.streamlock.net/7034/7034/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
