### ISSUE TITLE
Add: TV OFF [BO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11177]
### Channel ID

TVOFF.bo

### Stream URL

https://videohd.sistemareal.com:3290/live/tvoffhdlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream does not work: geo-blocked?

**Comment by freearhey** [comment]
https://videohd.sistemareal.com:3290/live/tvoffhdlive.m3u8 (offline)
<img width="425" alt="image" src="https://user-images.githubusercontent.com/7253922/232254480-770db837-4d57-4c38-82c0-7f473687d4f4.png">
