### ISSUE TITLE
Add: FTV [BO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11171]
### Channel ID

FTV.bo

### Stream URL

https://master.tucableip.com//ftv/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
