### ISSUE TITLE
Add: F10 HD [BO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11170]
### Channel ID

F10HD.bo

### Stream URL

https://video.live.com.bo:3253/live/f10hdlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream does not work: geo-blocked?

**Comment by freearhey** [comment]
https://video.live.com.bo:3253/live/f10hdlive.m3u8
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/7253922/232254401-6c20c30d-b84a-48d9-8e26-7198d45090b7.png">
