### ISSUE TITLE
Add: MegaTV [BO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11173]
### Channel ID

MegaTV.bo

### Stream URL

https://solo.disfrutaenlared.com:1936/tvcbba/tvcbba/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
