### ISSUE TITLE
Add: Red Uno Santa Cruz [BO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11176]
### Channel ID

RedUnoSantaCruz.bo

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x825whp

### Notes

La Paz: http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x828xvr
Cochabamba: http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x827j2y

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
