### ISSUE TITLE
Add: TV HD Tropical [BO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11179]
### Channel ID

TVHDTropical.bo

### Stream URL

https://cloud3.streaminglivehd.com:1936/8068/8068/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream does not work: geo-blocked?

**Comment by freearhey** [comment]
https://cloud3.streaminglivehd.com:1936/8068/8068/playlist.m3u8
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/7253922/232254463-425605b3-b929-40af-9711-cbcd29c56182.png">
