### ISSUE TITLE
Add: TV Latina [BO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11178]
### Channel ID

TVLatina.bo

### Stream URL

https://master.tucableip.com/live/tvlatinamontero/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/bo.m3u#L50-L51
