### ISSUE TITLE
Create TV Eastern Time (US)

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#11180]
### Channel ID

WLIWDT2.us

### Notes

If you can't find it. Try find another channel ID for eastern time.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Actual stream links?

**Comment by spotanjo3** [comment]
Yes

**Comment by AntiPontifex** [comment]
I meant could you provide a stream link.

**Comment by spotanjo3** [comment]
No. Only I found one was from Los Angele link. I dont want that. I prefer the eastern tome.
