### ISSUE TITLE
Add: Canal 4 [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11187]
### Channel ID

Canal4.es

### Stream URL

https://limited35.todostreaming.es/live/mitjans-livestream1.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
