### ISSUE TITLE
Add channel 

### ISSUE THREAD

**Issue by ala146** [iptv-org/iptv#1118]
Hello Sir;

I thank you for these wonderful links, but there are channels that are not present, such as the German channel ZDF and the American channels OSN, Showtime, HBO and FOX Move and Yemeni channels such as Yemen Shabab, Suhail channel, Al-Saeed, Yemen and Aden ... I hope to add these channels because they are important  Very thank you
Added on IPTV links and updated IPTV links after adding channels

**Comment by Nintendocustom** [comment]
I hope it helps you:
https://zdf-hls-01.akamaized.net/hls/live/2002460/de/high/master.m3u8

**Comment by ala146** [comment]
Hello sir 

The link does not work I hope you can add these channels in the previous links 

ZDF

https://iptv-org.github.io/iptv/germany /de.m3u

Also, I hope to add these channels


CNN America, Showtime, HBO,  Fox movie 

And in the m3u movie channels link there are not many american channels for advice please add new links and update

**Comment by freearhey** [comment]
**German:**
- [x] ZDF
https://github.com/iptv-org/iptv/blob/6da3b46f3b9f7ecc5d23feda8c4efee0100eba49/channels/de.m3u#L354-L355

**American:**
- [ ] OSN
- [ ] Showtime
- [ ] HBO
- [ ] FOX Movies

**Yemeni:**
- [ ] Yemen Shabab
- [ ] Suhail channel
- [ ] Al-Saeed
- [x] Yemen TV
https://github.com/iptv-org/iptv/blob/6da3b46f3b9f7ecc5d23feda8c4efee0100eba49/channels/ye.m3u#L6-L7
- [ ] Aden

**Comment by cyb3rm4n** [comment]
Is there full US HBO channel streams?

US package:
HBO
HBO2
HBO Signature
HBO Family
HBO Comedy
HBO Zone

**Comment by hishamalswaidi02** [comment]
My friend, I hope you add Netflix and OSN channels

**Comment by freearhey** [comment]
Closed in favor #1947, #1946 and #1942
