### ISSUE TITLE
Add: Canal 24 Horas Catalunya [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11186]
### Channel ID

Canal24HorasCatalunya.es

### Stream URL

https://ztnr.rtve.es/ztnr/4952053.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
