### ISSUE TITLE
Add: Eurolatina TV [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11188]
### Channel ID

EurolatinaTV.es

### Stream URL

https://media2.streambrothers.com:1936/8150/8150/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
