### ISSUE TITLE
Add: Canal 24 Horas Canarias [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11185]
### Channel ID

Canal24HorasCanarias.es

### Stream URL

https://ztnr.rtve.es/ztnr/5473142.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
