### ISSUE TITLE
Add: Betis TV [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11183]
### Channel ID

BetisTV.es

### Stream URL

https://betistv-live.flumotion.com/baRbyXGgBv0ttVZ3LKnILA/1673452034/betistv/live_all/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream does not work: geo-blocked?
