### ISSUE TITLE
Add: Biosfera TV [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11184]
### Channel ID

BiosferaTV.es

### Stream URL

https://tvdatta.com:3021/live/biosferatvlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the link: it will be included in the next release.
