### ISSUE TITLE
Add: Mar TV [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11194]
### Channel ID

MarTV.es

### Stream URL

http://iptv.services.everywan.net:8080/martv-web/video.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
