### ISSUE TITLE
Add: Navarra TV [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11195]
### Channel ID

NavarraTV.es

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/NavarraTelevision

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
