### ISSUE TITLE
Add: Negocios TV [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11196]
### Channel ID

NegociosTV.es

### Stream URL

https://streaming013.gestec-video.com/hls/negociostv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
