### ISSUE TITLE
Add: Nesting TV [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11197]
### Channel ID

NestingTV.es

### Stream URL

https://service.webvideocore.net/CL1olYogIrDWvwqiIKK7eHbBxDyYany25g-L4QOVH5_l5daXY9tfEZPDJS0YHgpW/a_53fwbvrz8js4.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
