### ISSUE TITLE
Add: Radio Rutas del Peru [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11199]
### Channel ID

RadioRutasdelPeru.es

### Stream URL

https://tv.portalexpress.es:3731/live/deimertvlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream does not work.
