### ISSUE TITLE
Add: La Sexta [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11192]
### Channel ID

LaSexta.es

### Stream URL

https://atres-live.atresmedia.com/5a83810efbdf16d080a31065624b07d0664a3926_ES_1673439570_1673468310/h264/live/lasexta/master.m3u8

### Notes

Geo-blocked

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Link does not work.
