### ISSUE TITLE
Add: La Ocho TV [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11191]
### Channel ID

LaOchoTV.es

### Stream URL

https://streaming004.gestec-video.com/hls/8TV.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
