### ISSUE TITLE
Add: PTV [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11198]
### Channel ID

PTV.es

### Stream URL

https://streamer.zapitv.com/PTV-malaga/index.m3u8

### Notes

Córdoba: https://streamer.zapitv.com/PTV_CORDOBA/index.m3u8
Sevilla: https://streamer.zapitv.com/PTV_sevilla/index.m3u8
Granada: https://streamer.zapitv.com/PTV-granada/index.m3u8
Linares: https://streamer.zapitv.com/ptv-linarez/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the streams: they will be included in the next release.
