### ISSUE TITLE
Add: Sony Movies *Sony Movie Channel* (US) | [Klowdtv]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#11208]
### Channel ID

SonyMovies.us

### Stream URL

http://n1.klowdtv.net/live1/smc_720p/chunks.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Legal stream?

**Comment by kaikyoofers** [comment]
Its by sony, i think so.

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by kaikyoofers** [comment]
Also, replace the link with http://n1.klowdtv.net/live1/smc_720p/playlist.m3u8

**Comment by freearhey** [comment]
http://n1.klowdtv.net/live1/smc_720p/playlist.m3u8
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/7253922/232255084-cb162f7d-bfa3-4605-8637-4376fd3b9cd7.png">

**Comment by spotanjo3** [comment]
Dead. Please relink ?

**Comment by R4IN2007** [comment]
Well that's odd still the new url works but it wouldn't be shared here then.

**Comment by spotanjo3** [comment]
Try post here and I can see if it works on my VLC player in my desktop before import to android tv.
