### ISSUE TITLE
Add: Cine Sony (US) | [Klowdtv]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#11209]
### Channel ID

CineSony.us

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Legal stream?

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/us_klowdtv.m3u#L6-L7
