### ISSUE TITLE
Add: Telecija [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11201]
### Channel ID

Telecija.es

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/telecija

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
