### ISSUE TITLE
Add: Sal Television [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11200]
### Channel ID

SalTelevision.es

### Stream URL

https://cloudvideo.servers10.com:8081/8254/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
