### ISSUE TITLE
Add: Cadena 103.TV [AR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11221]
### Channel ID

Cadena103.ar

### Stream URL

http://arcast.net:1935/cadena103/cadena103/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
