### ISSUE TITLE
Add: 5R TV [AR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11220]
### Channel ID

5RTV.ar

### Stream URL

http://api.new.livestream.com/accounts/22636012/events/8242619/live.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
