### ISSUE TITLE
Add: TV Beltrão

### ISSUE THREAD

**Issue by bilufe** [iptv-org/iptv#11223]
### Channel ID

TVBeltrao.br

### Stream URL

https://5cf4a2c2512a2.streamlock.net/tvbeltrao/tvbeltrao/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
