### ISSUE TITLE
Un-Playable Channel : SONYSABHD

### ISSUE THREAD

**Issue by Rahul-157** [iptv-org/iptv#11230]
### Broken Link

http://indo51.gcdn.co/hindi-SONYSABHD/playlist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Broken link removed from playlist.
