### ISSUE TITLE
Add: AcademiaTV [EC]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11242]
### Channel ID

AcademiaTV.ec

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://livestream.com/accounts/30417243/events/9529139/player

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
