### ISSUE TITLE
Add: Canal 6 Nacional [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11249]
### Channel ID

Canal6Nacional.mx

### Stream URL

https://mdstrm.com/live-stream-playlist/5f2d9d6ff17144074bd8a284.m3u8

### Notes

Monterrey: https://mdstrm.com/live-stream-playlist/57b4dbf5dbbfc8f16bb63ce1.m3u8
Milenio: https://mdstrm.com/live-stream-playlist/610178c7db32a4112d994650.m3u8
Laguna: https://mdstrm.com/live-stream-playlist/57bf686a61ff39e1085d43e1.m3u8
Guadalajara: https://mdstrm.com/live-stream-playlist/5c54d38ca392a5119bb0aa0d.m3u8
Puebla: https://mdstrm.com/live-stream-playlist/5d56ed29c92dd106ff01543b.m3u8
Bajio: https://mdstrm.com/live-stream-playlist/5d4b0fec848918070128c8cb.m3u8
Saltillo: https://mdstrm.com/live-stream-playlist/5d5d51a4e9a40e25f4a0332c.m3u8
CDJuarez: https://mdstrm.com/live-stream-playlist/5d9e440d675235586a92be7f.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the streams: they will be included in the next release.
