### ISSUE TITLE
Add: Milenio Television [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11248]
### Channel ID

MilenioTelevision.mx

### Stream URL

https://mdstrm.com/live-stream-playlist/610178c7db32a4112d994650.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the link: it will be included in the next release.
