### ISSUE TITLE
Add: Oromar TV [EC]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11244]
### Channel ID

OromarTV.ec

### Stream URL

https://stream.oromartv.com:8082/hls/oromartv_hi/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
