### ISSUE TITLE
Add: Aprende TV [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11246]
### Channel ID

AprendeTV.mx

### Stream URL

https://dgtve-usso.streaming.media.azure.net/3d809128-ebfd-46dd-9e45-155625dc7459/141960bb-137e-425e-8f41-5094612f7df4.ism/manifest(format=m3u8-aapl).m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream does not work.

**Comment by kaikyoofers** [comment]
Works for me.

**Comment by AntiPontifex** [comment]
Still nothing on my end (geo-blocked?).

**Comment by kaikyoofers** [comment]
Maybe geoblocked to Latin America
