### ISSUE TITLE
Add: HappyChannel.ro

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#11240]
### Channel ID

HappyChannel.ro

### Stream URL

https://rundle.deta.dev/hls/LIVE$HappyChannel/6.m3u8/Level(19012010)?start=LIVE&end=END

### Notes

24/7

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by LaneSh4d0w** [comment]
Accepted, will be added with PR #11269
