### ISSUE TITLE
Add: Ingenio TV [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11247]
### Channel ID

IngenioTV.mx

### Stream URL

https://dgtve-usso.streaming.media.azure.net/f6d9bfec-5e3d-48fb-b42a-d2a233e261ce/ca87097a-e200-4702-b523-2dc1b6bbc40f.ism/manifest(format=m3u8-aapl).m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream does not work.

**Comment by kaikyoofers** [comment]
Stream does work.
