### ISSUE TITLE
Replace: AT-X

### ISSUE THREAD

**Issue by LunaticKingdom** [iptv-org/iptv#11245]
### Broken Link

https://sub.neetball.net/live/neet.m3u8

### What happened to the stream?

Not loading

### Notes

Japanese anime channel, not loading.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Works on my side.

**Comment by freearhey** [comment]
https://sub.neetball.net/live/neet.m3u8 (offline)
<img width="286" alt="image" src="https://user-images.githubusercontent.com/7253922/232260448-3c330cbb-a54f-4167-8151-0cedff9d8700.png">

Closed in favor of #11749
