### ISSUE TITLE
Add: Telemar Campeche [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11254]
### Channel ID

TelemarCampeche.mx

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://dailymotion.com/telemarcampeche

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
