### ISSUE TITLE
Add: Canal 26 [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11253]
### Channel ID

Canal26.mx

### Stream URL

https://60417ddeaf0d9.streamlock.net/telemetrika3/telemetrika3.smil/.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
