### ISSUE TITLE
Add: TVMas [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11251]
### Channel ID

TVMas.mx

### Stream URL

https://5ca9af4645e15.streamlock.net/rtv/videortv/.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
