### ISSUE TITLE
Add: TV Cuatro 4.1 [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11255]
### Channel ID

TVCuatro41.mx

### Stream URL

https://5f1af61612fb5.streamlock.net/tv4/tv4.smil/.m3u8

### Notes

4.2: https://5f2c1b0d880e5.streamlock.net/tv42/tv42.smil/.m3u8
4.3: https://5f1af61612fb5.streamlock.net/tv43/tv43.smil/.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the streams: they will be included in the next release.
