### ISSUE TITLE
Add: Ciudad Magazine [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11257]
### Channel ID

CiudadMagazine.ar

### Stream URL

https://live-01-07-ciudad.vodgc.net/live-01-07-ciudad.vodgc.net/index.m3u8

### Notes

Geo-blocked

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
