### ISSUE TITLE
Add: XHSPR-TDT1 (Canal Catorce) [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11252]
### Channel ID

XHSPRTDT1.mx

### Stream URL

https://60ed5b6d0df78.streamlock.net:1936/segundo/segundo/.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
