### ISSUE TITLE
Add: Sintesis TV [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11250]
### Channel ID

SintesisTV.mx

### Stream URL

https://free.fullspeed.tv/iptv-query?streaming-ip=https://twitch.tv/sintesis_tv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream does not work.
