### ISSUE TITLE
Add: Canal 9 Televida [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11258]
### Channel ID

Canal9Televida.ar

### Stream URL

https://unlimited1-us.dps.live/televidaar/televidaar.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
