### ISSUE TITLE
Add: CB TV Michoacan [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11262]
### Channel ID

CBTVMichoacan.mx

### Stream URL

https://5ca3e84a76d30.streamlock.net/cbtv/videocbtv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
