### ISSUE TITLE
Replace: ProTV.ro

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#11267]
### Broken Link

https://hlsrundle-stream-iptv.gq/api/hls/protv.m3u8

### What happened to the stream?

Other

### Possible Replacement

https://rundle.deta.dev/hls/LIVE$ProTV.ro/6.m3u8/Level(19012010)?start=LIVE&end=END

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Stream does not work.

**Comment by ovidiuux** [comment]
> Stream does not work.

Opps, now working.

**Comment by AntiPontifex** [comment]
Still does not work: geo-blocked?

**Comment by LaneSh4d0w** [comment]
Welp, redirects to an Xtream-Codes server, sadly, we do not accept those here.

**Comment by freearhey** [comment]
https://rundle.deta.dev/hls/LIVE$ProTV.ro/6.m3u8/Level(19012010)?start=LIVE&end=END (offline)
<img width="628" alt="image" src="https://user-images.githubusercontent.com/7253922/232254768-f068845e-16fc-4fbd-be30-f1e0f2224b70.png">

Broken link removed from playlist.
