### ISSUE TITLE
Add: CorTV [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11263]
### Channel ID

CorTV.mx

### Stream URL

https://stream.oursnetworktv.com/latin/encoder29/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
