### ISSUE TITLE
Add: RCG TV 3 [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11261]
### Channel ID

RCGTV3.mx

### Stream URL

https://5caf24a595d94.streamlock.net:1937/stream56/stream56/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
