### ISSUE TITLE
Add: TVMAXCBA [AR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11278]
### Channel ID

TVMAXCBA.ar

### Stream URL

https://panel.dattalive.com/8106/8106/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
