### ISSUE TITLE
Add: IP Noticias [AR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11275]
### Channel ID

IPNoticias.ar

### Stream URL

https://d1nmqgphjn0y4.cloudfront.net/live/ip/live.isml/5ee6e167-1167-4a85-9d8d-e08a3f55cff3.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
