### ISSUE TITLE
Add: Unirio TV [AR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11279]
### Channel ID

UnirioTV.ar

### Stream URL

https://5f700d5b2c46f.streamlock.net:443/uniriotv/uniriotv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
