### ISSUE TITLE
Add: Garage TV [AR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11273]
### Channel ID

GarageTV.ar

### Stream URL

http://186.0.233.76:1935/Garage/smil:garage.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream did not work.

**Comment by Carlinhos027** [comment]
> Stream did not work.

Works for me lol
