### ISSUE TITLE
Add: Pakapaka [AR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11276]
### Channel ID

Pakapaka.ar

### Stream URL

https://5fb24b460df87.streamlock.net/live-cont.ar/pakapaka/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
