### ISSUE TITLE
Add: T5 Satelital [AR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11271]
### Channel ID

T5Satelital.ar

### Stream URL

https://tv.t5satelital.com/tvhls/streamcorrientes.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
