### ISSUE TITLE
Add: ABEMA Anime

### ISSUE THREAD

**Issue by BellezaEmporium** [iptv-org/iptv#11289]
### Channel ID

ABEMAAnime.jp

### Stream URL

https://neetball.net/live/test3.m3u8

### Notes

Through Neetball 3rd test stream.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Put here as i'm quite unsure about the stream itself. I don't know how to read Kanji characters, lol.
