### ISSUE TITLE
Add: Sula TV [HN]

### ISSUE THREAD

**Issue by elvinag6** [iptv-org/iptv#11280]
### Channel ID

Sula TV (HN)

### Stream URL

https://sulatv1.ddns.net/hls/live/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by LaneSh4d0w** [comment]
Streamtest gave a positive answer : https://streamtest.in/logs/https-sulatv1-ddns-net-hls-live-index-m3u8, accepted.

**Comment by elvinag6** [comment]
favor cambiar link m3u8 https://livestreamhd.us/sulatv/live/playlist.m3u8
