### ISSUE TITLE
Add: Antena 1 HD (Romanian)

### ISSUE THREAD

**Issue by ohfanta** [iptv-org/iptv#11286]
### Channel ID

Antena1.ro

### Stream URL

https://rundle.deta.dev/hls/LIVE$Antena1/6.m3u8/Level(19012010)?start=LIVE&end=END

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.

**Comment by LaneSh4d0w** [comment]
PR #11269 is made to add it.
