### ISSUE TITLE
Add: Telesur Camana [PE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11299]
### Channel ID

TelesurCamana.pe

### Stream URL

https://1667517699.rsc.cdn77.org/hls/camana.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
