### ISSUE TITLE
Add: Nuestra TV Lima [PE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11298]
### Channel ID

NuestraTVLima.pe

### Stream URL

 http://free.fullspeed.tv/iptv-query?streaming-ip=https://twitch.tv/nuestratvlima

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Does not work
