### ISSUE TITLE
Replace: Boomerang Southeast Asia

### ISSUE THREAD

**Issue by boomboom4100** [iptv-org/iptv#11294]
### Broken Link

https://livecdn.fptplay.net/hda3/boomerang_vhls.smil/chunklist.m3u8

### What happened to the stream?

Not loading

### Notes

Boomerang Southeast Asia not loading at all. Found in PH playlist.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Does not work

**Comment by LaneSh4d0w** [comment]
This link won't work because AFAIK this server (for hda links) works only if you're located in Vietnam.
