### ISSUE TITLE
Add: Canal E [PE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11297]
### Channel ID

CanalE.pe

### Stream URL

https://stream.plixitv.live/westv/westv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.

**Comment by LaneSh4d0w** [comment]
https://github.com/iptv-org/iptv/blob/c8711c9aa9f0ca67778c4c0bc3401b89fa2c18d9/streams/pe.m3u#L330-L331
