### ISSUE TITLE
Add: Cajamarca TV [PE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11296]
### Channel ID

CajamarcaTV.pe

### Stream URL

https://ca2.inka.net.pe/cajamarcatv/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
