### ISSUE TITLE
Add: Canal9 Toliman [GT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11301]
### Channel ID

Canal9Toliman.gt

### Stream URL

https://cdn.streamhispanatv.net:3237/live/canal9tvgtlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
