### ISSUE TITLE
Add: Canal Peniel [GT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11300]
### Channel ID

CanalPeniel.gt

### Stream URL

https://cdn.streamhispanatv.net:3840/live/penielfamlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
