### ISSUE TITLE
Add: Comarca TV [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11309]
### Channel ID

ComarcaTV.ar

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://twitch.tv/comarca_tv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Does not work
