### ISSUE TITLE
Add: TeleJunin [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11305]
### Channel ID

TeleJunin.ar

### Stream URL

https://videostream.shockmedia.com.ar:19360/telejunin/telejunin.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
