### ISSUE TITLE
Add: Telearte [GT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11302]
### Channel ID

Telearte.gt

### Stream URL

https://cdn.streamhispanatv.net:3771/live/teleartegtlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream does not work: geo-blocked?
