### ISSUE TITLE
Add: Canal 40 Cauecte [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11306]
### Channel ID

Canal40Cauecte.ar

### Stream URL

https://canalsj.kozow.com/canal40/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
