### ISSUE TITLE
Add: Canal 4 Esquel [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11307]
### Channel ID

Canal4Esquel.ar

### Stream URL

https://stream.arcast.com.ar/canal4esquel/canal4esquel/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
