### ISSUE TITLE
Add: Cadena VIVO [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11304]
### Channel ID

CadenaVIVO.ar

### Stream URL

https://stmv1.voxtvhd.com.br/cadenavivo/cadenavivo/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
