### ISSUE TITLE
Add: Red Vision Radio [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11315]
### Channel ID

RedVisionRadio.ar

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://twitch.tv/redvisionradiotv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release
