### ISSUE TITLE
Add: TV40 [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11319]
### Channel ID

TV40.ar

### Stream URL

 http://free.fullspeed.tv/iptv-query?streaming-ip=https://twitch.tv/tv40argentina

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
