### ISSUE TITLE
Add: Demos Radio Visual [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11310]
### Channel ID

DemosRadioVisual.ar

### Stream URL

https://panel.dattalive.com/8066/8066/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
