### ISSUE TITLE
Add: Televideo Regional [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11318]
### Channel ID

TelevideoRegional.ar

### Stream URL

https://inliveserver.com:1936/8050_1/8050_1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
