### ISSUE TITLE
Add: El Histonauta TV [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11311]
### Channel ID

ElHistonautaTV.ar

### Stream URL

https://stmv1.cnarlatam.com/elhistonauta/elhistonauta/playlist.m3u8

### Notes

Other channels from the same server without ID:

Aventuras TV: https://stmv1.cnarlatam.com/mundotv/mundotv/playlist.m3u8
Xtrema Animal: https://stmv1.cnarlatam.com/xtremaanimal/xtremaanimal/playlist.m3u8
TechScience 365: https://stmv1.cnarlatam.com/techscience365/techscience365/playlist.m3u8
EBV: https://stmv1.cnarlatam.com/buenvivirtv/buenvivirtv/playlist.m3u8
Te lo cuento y que: https://stmv1.cnarlatam.com/telocuento/telocuento/playlist.m3u8
AstroNet: https://stmv1.cnarlatam.com/astronet/astronet/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the streams: they will be included in the next release.
