### ISSUE TITLE
Add: Senillosa TV [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11316]
### Channel ID

SenillosaTV.ar

### Stream URL

https://stmv1.srvstm.com/senillosa/senillosa/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
