### ISSUE TITLE
Add: Quatro TV [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11313]
### Channel ID

QuatroTV.ar

### Stream URL

https://stream.arcast.live/quatro/quatro/playlist.m3u8

### Notes

Not 24/7

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Does not work
