### ISSUE TITLE
Add: X24 [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11321]
### Channel ID

X24.ar

### Stream URL

http://srv1.zcast.com.ar/x24hd/x24hd/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
