### ISSUE TITLE
Add: Canal 9 Comodoro Rivadavia [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11322]
### Channel ID

Canal9ComodoroRivadavia.ar

### Stream URL

https://live.canalnueve.tv/canal.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Actually AZM TV; thank you for the stream. It will be included in the next release.
