### ISSUE TITLE
Add: SBT Rio Grande [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11327]
### Channel ID

SBTRioGrande.br

### Stream URL

https://cdn.jmvstream.com/w/LVW-10801/LVW10801_Xvg4R0u57n/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
