### ISSUE TITLE
Add: Rede Mais [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11326]
### Channel ID

RedeMais.br

### Stream URL

https://5a0c3936c25c8.streamlock.net/8010/8010/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release
