### ISSUE TITLE
Add: RBTV [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11324]
### Channel ID

RBTV.br

### Stream URL

https://5cf4a2c2512a2.streamlock.net/rbtv/rbtv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
