### ISSUE TITLE
Fix: Media cannot be loaded on Ubuntu 22

### ISSUE THREAD

**Issue by mohannadjamal** [iptv-org/iptv#11325]
### Describe your issue

I get the error: The media could not be loaded, either because the server or network failed or because the format is not supported. when using the application on Ubuntu, but works fine on Windows

**Comment by ExperiencersInternational** [comment]
Your issue doesn't describe what application you're using.

**Comment by LaneSh4d0w** [comment]
And it's less likely to be a URL issue, but more of an player/environment codec issue. Closing.
