### ISSUE TITLE
Add: Canal 38 [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11323]
### Channel ID

Canal38.br

### Stream URL

https://cdn.jmvstream.com/w/LVW-8503/LVW8503_d0V5oduFlK/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by freearhey** [comment]
https://cdn.jmvstream.com/w/LVW-8503/LVW8503_d0V5oduFlK/playlist.m3u8
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/7253922/232255287-eafdc085-013b-4931-82b5-4b379910e49b.png">
