### ISSUE TITLE
Add: Thunder Sports [HN]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11344]
### Channel ID

ThunderSports.hn

### Stream URL

https://emisoras.hn:8081/tsh/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/hn.m3u#L70-L71
