### ISSUE TITLE
Add: Waldivision Internacional [HN]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11343]
### Channel ID

WaldivisionInternacional.hn

### Stream URL

https://videoserver.ideskhn.com:3863/live/waldivisionlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Does not work.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/hn.m3u#L82-L83
