### ISSUE TITLE
seems three channel from nz is down

### ISSUE THREAD

**Issue by isblue01** [iptv-org/iptv#1134]
i tried several ip, all down from those location,weird is that i first found it's down from matt huisman's url like 7 days ago,
 like this one for example: http://i.mjh.nz/au/Brisbane/tvh-tv.m3u8
since i can't view its source code, and other links like three channel here works ok,i didn't take it seriously, but now, why it's all down....why there is a delaying if it's closed by the owner? or something  beyond my knowledge happened?

**Comment by freearhey** [comment]
At the moment the Three channel is working as usual, so I think it was just a temporary shutdown.

**Comment by gfwfuckoff** [comment]
down again for couple days😂

**Comment by freearhey** [comment]
Unfortunately, there's nothing I can do about it right now. But as soon as there is a working version, we will add it to the playlist.

**Comment by gfwfuckoff** [comment]
thx anyway
