### ISSUE TITLE
Add: Salvacion TV [PR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11347]
### Channel ID

SalvacionTV.pr

### Stream URL

https://stream.eleden.com/livesalvatv/ngrp:livesalvatv_all/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/pr.m3u#L18-L19
