### ISSUE TITLE
Add: TV Clube [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11355]
### Channel ID

TVClube.br

### Stream URL

https://5c483b9d1019c.streamlock.net/8186/8186/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
