### ISSUE TITLE
Add: TV Liberdade [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11356]
### Channel ID

TVLiberdade.br

### Stream URL

https://srv1.paineldevideo.com/liberdaderadioetv/liberdaderadioetv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
