### ISSUE TITLE
Add: TV Interlagos [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11359]
### Channel ID

TVInterlagos.br

### Stream URL

https://v8.ciclano.io:1443/tvinterlagos/_definst_/tvinterlagos/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
