### ISSUE TITLE
Add: VTV 4

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#11353]
### Channel ID

VTV4.vn

### Stream URL

https://nvzoftzsvflivcf.vcdn.com.vn/vtv4/vtv4@mid.m3u8

### Notes

Valid

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by LaneSh4d0w** [comment]
there's "high, mid, low" as available parameters... thing is i can't seem to get the adaptive playlist out of it.

**Comment by LaneSh4d0w** [comment]
https://nvzoftzsvflivcf.vcdn.com.vn/vtv3/vtv3@high.m3u8
https://nvzoftzsvflivcf.vcdn.com.vn/vtv2/vtv2@high.m3u8
https://nvzoftzsvflivcf.vcdn.com.vn/vtv1/vtv1@high.m3u8

are actually the same stream.

**Comment by vuminhngocpt** [comment]
Thanks

**Comment by freearhey** [comment]
https://nvzoftzsvflivcf.vcdn.com.vn/vtv4/vtv4@mid.m3u8
<img width="423" alt="image" src="https://user-images.githubusercontent.com/7253922/232146052-24264f75-420d-4e1b-8740-9c7b765fc3b3.png">

https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/vn.m3u#L68-L69
