### ISSUE TITLE
Add: Beats Radio [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11361]
### Channel ID

BeatsRadio.ar

### Stream URL

https://videostream.shockmedia.com.ar:19360/cincotv/cincotv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
This is actually for Cinco TV, which is also not in the database. Thank you for the stream: it will be added for the next release. Please change the title of this entry to Cinco TV.
