### ISSUE TITLE
Add: SBT Para [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11369]
### Channel ID

SBTPara.br

### Stream URL

https://streaming.portaltvparaense.com.br/hls/rtp.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
