### ISSUE TITLE
Add: Cartoonito Argentina [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11364]
### Channel ID

CartoonitoArgentina.ar

### Stream URL

https://playout.cdn.cartoonnetwork.com.br/playout_04/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://github.com/iptv-org/iptv/blob/e3223b0e86d6c48d869303c4b9c2fd169359f7f4/streams/br.m3u#L45-L46

Wrong naming but is already here.
