### ISSUE TITLE
Add: Adult Swim Rick & Morty 24/7

### ISSUE THREAD

**Issue by greenmr** [iptv-org/iptv#11375]
### Channel ID

AdultSwimRickandMorty.us

### Stream URL

http://adultswim-vodlive.cdn.turner.com/live/rick-and-morty/stream.m3u8

### Notes

I've been using this url for several years without issue

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://github.com/iptv-org/iptv/blob/c8711c9aa9f0ca67778c4c0bc3401b89fa2c18d9/streams/us_adultswim.m3u#L38-L39

**Comment by ShragSirGirly** [comment]
Could you please find the main adult swim broadcast :3
