### ISSUE TITLE
Add: Amazon Sat [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11371]
### Channel ID

AmazonSat.br

### Stream URL

https://amazonsat.brasilstream.com.br/hls/amazonsat/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
