### ISSUE TITLE
Add: EIT

### ISSUE THREAD

**Issue by EsperantaInterretaTelevido** [iptv-org/iptv#11373]
### Channel ID

EIT-WTV

### Stream URL

https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1674254926/ei/7sXKY66qEbL5gAe1gofgCw/ip/92.205.15.128/id/jvDRXDVj84I.1/source/yt_live_broadcast/requiressl/yes/tx/24276399/txs/24276394%2C24276395%2C24276396%2C24276397%2C24276398%2C24276399/hfr/1/playlist_duration/30/manifest_duration/30/maudio/1/vprv/1/go/1/pacing/0/nvgoi/1/keepalive/yes/fexp/24007246/dover/11/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cplaylist_duration%2Cmanifest_duration%2Cmaudio%2Cvprv%2Cgo%2Citag%2Cplaylist_type/sig/AOq0QJ8wRgIhAPMVFYxn8wd_uophJvLEV8PJYYaq2a4EqTKFjf6tyMCxAiEAxHExf10FnUjtPgNTpVkAM-i1K5N1TC9pnI4jqoHSucg%3D/file/index.m3u8

### Notes

Website: https://esperantainterretatelevido.github.io/
Alt link: https://youtube.com/embed/c_7-jtpbJf4
Not 24/7 only airs from 6 am - 9 pm EST
Located in the USA

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Thank you for proposing your channel to us. Will check the different links.

**Comment by EsperantaInterretaTelevido** [comment]
I just updated the yt link and the m3u8 link

**Comment by EsperantaInterretaTelevido** [comment]
> Thank you for proposing your channel to us. Will check the different links.
> 
> Live stream (EIT-WTV) : https://hls.youtb.workers.dev/channel/UCjrwSXcZ3gPYzVrQcHX-pdw.m3u8 (once it's online)

Also language is in Esperanto
