### ISSUE TITLE
Kalaignar News

### ISSUE THREAD

**Issue by Syednoormohamed** [iptv-org/iptv#11378]
### Broken Link

http://103.199.160.85/Content/kalaignarseithikal/Live/Channel(KalaignarSeithikal)/index.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://www.youtube.com/watch?v=wSK1OoA58vk

### Notes

It was broken. I have share youtube live stream link

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
https://www.youtube.com/channel/UCcVF2Fth-qEA4T1Lhn3CgKg/live
or
https://hls.youtb.workers.dev/channel/UCcVF2Fth-qEA4T1Lhn3CgKg.m3u8

**Comment by Syednoormohamed** [comment]
> https://www.youtube.com/channel/UCcVF2Fth-qEA4T1Lhn3CgKg/live or https://hls.youtb.workers.dev/channel/UCcVF2Fth-qEA4T1Lhn3CgKg.m3u8

Thanks
