### ISSUE TITLE
Replace: TV Vila Real [BR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11370]
### Broken Link

https://cdn.jmvstream.com/w/LVW-10842/LVW10842_513N26MDBL/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://cdn.jmvstream.com/w/LVW-10841/LVW10841_mT77z9o2cP/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Fixed: thank you.
