### ISSUE TITLE
Add: TVSud.ro

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#11386]
### Channel ID

TVSud.ro

### Stream URL

https://stream.leetweb.ro/WebRTCApp/streams/118334672595255049029831.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Regional stream from the Oltenia region, from Municipiul Târgu Jiu, Județul Gorj
