### ISSUE TITLE
Replace: MoozRo.ro

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#11387]
### Broken Link

https://hlsrundle-stream-iptv.gq/api/hls/moozro.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://rundle.deta.dev/hls/LIVE$MoozRo/6.m3u8/Level(19012010)?start=LIVE&end=END

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://rundle.deta.dev/hls/LIVE$MoozRo/6.m3u8/Level(19012010)?start=LIVE&end=END
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/7253922/232254826-64988274-8480-4e28-8b59-43b6a9af5981.png">

**Comment by freearhey** [comment]
Broken link removed from playlist.
