### ISSUE TITLE
Replace: MoozDance.ro

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#11388]
### Broken Link

https://rtmp.digitalbroadcast.ro/moozdance/moozdance.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://rundle.deta.dev/hls/LIVE$MoozDance/6.m3u8/Level(19012010)?start=LIVE&end=END

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://rtmp.digitalbroadcast.ro/moozdance/moozdance.m3u8
<img width="788" alt="image" src="https://user-images.githubusercontent.com/7253922/232254900-0053a692-3adf-41ae-b278-10456d4e42e7.png">
