### ISSUE TITLE
Replace: MoozHits.ro

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#11389]
### Broken Link

https://rtmp.digitalbroadcast.ro/moozhits/moozhits.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://rundle.deta.dev/hls/LIVE$MoozHits/6.m3u8/Level(19012010)?start=LIVE&end=END

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by ovidiuux** [comment]
> I see you're dealing with the headers. Do you think you could make these kind of links work : #EXTINF:-1 tvg-id="Canal21Huancayo.pe",Canal 21 Huancayo #EXTVLCOPT:http-origin=http://opencaster.com/ https://edge1o.live.opencaster.com/caster/ztCaDbjyCrwa.m3u8
> 
> It's a bit fancier since it needs an origin to work, instead of a referrer.

https://rundle.deta.dev/hls/LIVE$Canal21Huancayo.pe/6.m3u8/Level(19012010)?start=LIVE&end=END.

But also .ts files are protected with http-origin.
I need to make a proxy on cloudflare workers.
deta.dev don't support proxy.

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-logo="https://i.imgur.com/Dgsw1ef.jpg" group-title="",MoozHits
https://rtmp.digitalbroadcast.ro/moozhits/moozhits.m3u8|Referer=https://mooz.tv/live-ro/#MoozHits
#EXTINF:-1 tvg-logo="https://i.imgur.com/mmz4e3b.jpg" group-title="",MoozDance
https://rtmp.digitalbroadcast.ro/moozdance/moozdance.m3u8|Referer=https://mooz.tv/live-ro/#MoozDance
#EXTINF:-1 tvg-logo="https://i.imgur.com/TzWfn41.png" group-title="",MoozRo
https://rtmp.digitalbroadcast.ro/moozro/moozro.m3u8|Referer=https://mooz.tv/live-ro/#MoozRo

or use 
#EXTVLCOPT:http-referrer=

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/ro.m3u#L43-L45
<img width="784" alt="image" src="https://user-images.githubusercontent.com/7253922/232210540-81ef6876-eed0-469b-94bd-4be9772c15c2.png">
