### ISSUE TITLE
NP channel request

### ISSUE THREAD

**Issue by nepalicana** [iptv-org/iptv#1139]
@iptv-org thank you for sharing the huge playlist to community. I’m from Nepal and see that u don’t have much of the channels of the country. I have an access to IPTV (www.nettv.com.np) in which most of the channels are free to watch but requires login and the playlists is nimblesession encrypted. Do u think it could be useful? If u need the login credentials, please let me know. Thanks.

**Comment by freearhey** [comment]
This is great that you want to help, but we only add publicly accessible broadcasts to this repository that do not require authorization. But anyway, thank you for your support.
