### ISSUE TITLE
Remove: AlfaOmegaTV.ro 

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#11390]
### Broken Link

http://s5.alfaomega.tv:1935/alfaomega/smil:alfaomegatv/playlist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
![image](https://user-images.githubusercontent.com/30985701/213919679-62cb5d80-7657-4c2f-ab9f-c846afd3fc6b.png)

Works for me
