### ISSUE TITLE
Add: ProArena.ro

### ISSUE THREAD

**Issue by ovidiuux** [iptv-org/iptv#11404]
### Channel ID

ProArena.ro

### Stream URL

https://rundle.deta.dev/hls/LIVE$PROArena/6.m3u8/Level(19012010)?start=LIVE&end=END

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
403

**Comment by ovidiuux** [comment]
> 403

Yes, you have accessed the direct link here.

I disabled some url and domains via REFERRER but it is working. I also noticed activity in the Xtream-Codes players and stopped streaming there, plus I stopped for those who were restreaming.

We made this "protection" to prevent overloading, we also brought Cache-Control and more 307 redirects and IP control for too many requests.

**Comment by ovidiuux** [comment]
Try playing this address in VLC.

**Comment by LaneSh4d0w** [comment]
Works using MPC-HC.
