### ISSUE TITLE
Add: Musavision [DO] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11407]
### Channel ID

Musavision.do

### Stream URL

https://soportedvb.click:3827/live/musavisiontvlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://soportedvb.click:3827/live/musavisiontvlive.m3u8
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/7253922/232255320-334f7e50-ef0c-4fc7-9e20-d2c0d2a66724.png">
