### ISSUE TITLE
Add: NewsNation India

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#11412]
### Channel ID

NewsNation.in

### Stream URL

https://livetv-channels.b-cdn.net/8017/chunklist0.m3u8

### Notes

Must-have channel

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
https://livetv-channels.b-cdn.net/8017/playlist.m3u8

**Comment by freearhey** [comment]
https://livetv-channels.b-cdn.net/8017/playlist.m3u8
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/7253922/232255332-d9016f50-0b58-4808-88e7-fb23e8bfbf37.png">

**Comment by freearhey** [comment]
https://livetv-channels.b-cdn.net/8017/playlist.m3u8 (wrong channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/in.m3u#L507-L508
