### ISSUE TITLE
Add: using this link inpect site

### ISSUE THREAD

**Issue by ajunkdha** [iptv-org/iptv#11413]
### Channel ID

Indo

### Stream URL

Nope

### Notes

https://www.indihometv.com/tv/live#

use this link, unload it

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Please read the [Contribution Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md) before submitting an issue.
