### ISSUE TITLE
Add: Memorias TV [CO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11425]
### Channel ID

MemoriasTV.co

### Stream URL

https://mediacp.us:8081/8002/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://mediacp.us:8081/8002/index.m3u8
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/7253922/232255347-7f350870-62e5-4ca4-90ce-7124eae549fe.png">
