### ISSUE TITLE
Add: Oasis TV [CO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11428]
### Channel ID

OasisTV.co

### Stream URL

https://5e85d90130e77.streamlock.net/6020/6020/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/co.m3u#L70-L71
