### ISSUE TITLE
Add: Suram TV [CO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11429]
### Channel ID

SuramTV.co

### Stream URL

https://livetv.305streamhd.com:3111/live/suramtvlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/co.m3u#L80-L81
