### ISSUE TITLE
Add: 7 La Rioja [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11434]
### Channel ID

7LaRioja.es

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/7rioja

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by OckhamOdyssey** [comment]
Error 403

**Comment by Carlinhos027** [comment]
> Error 403

Works for me. So I think is geo-blocked.

**Comment by LaneSh4d0w** [comment]
Works for me

**Comment by trincowski** [comment]
> > Error 403
> 
> Works for me. So I think is geo-blocked.

It's not blocked but the service making the link between you and dailymotion is rate limited. It will give an error sometimes.
