### ISSUE TITLE
Add: TV Teuta (and possibly TV Boin)

### ISSUE THREAD

**Issue by lindon-c** [iptv-org/iptv#11439]
### Channel ID

TVTeuta.me

### Stream URL

https://ub1doy938d.gjirafa.net/live/dCynrjRK8sEsrYu0zDtDg8l4KaXbFpXl/zty1gq1080/index.m3u8

### Notes

This m3u link seems to require updating throughout the day (it is for TV Teuta). TV Boin has a live page on its website (https://tvboin.com/live/) but it appears it is under construction. This is more so me having wishful thinking that someone else maybe has an m3u for this site to legally stream it. Both sites are from Montenegro. (p.s. I could not find the channel ID for TV Boin).

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
The "gjjrafa.net" links AFAIK change over time.

**Comment by lindon-c** [comment]
Yes, it does change over time. I was not sure if bots possibly existed to consistently pull the information as needed, for it comes from the same page (https://tvteuta.com/live-tv/) but the m3u link changes.

> The "gjjrafa.net" links AFAIK change over time.

**Comment by freearhey** [comment]
https://teutastream.com/tvteuta/tracks-v1a1/mono.m3u8
<img width="788" alt="image" src="https://user-images.githubusercontent.com/7253922/234038411-4f39f352-3554-47d9-a2c6-7166612d55dd.png">
