### ISSUE TITLE
Replace: Albanian Channels

### ISSUE THREAD

**Issue by lindon-c** [iptv-org/iptv#11438]
### Broken Link

http://93.157.62.180/TopNews/index.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://dmxleo.dailymotion.com/cdn/manifest/video/x6inuzo.m3u8?auth=1674829532-2562-rib8kqu1-5fbe237d7639ba7f61aec60ee9777bc2fkBMZotSL24uqhYhmm8aYu8kwGYcJYCA1-6KJrTk2U0LY29638KzlbXg_dwJ0CsRu4GGcav6a1D77LkQGJkF5eBUBK63KC1aHJJqvc4H0782YmK_VcrepZ2bh31jeBjHhhBP6lzAKhSfsom618AancRaR2xkC7OzW--9oMAfJwbapp-dR-3Tno8o94jkAyNv43Z8659CSdNS4cwHxQbokoby3JR2Ci9MddYIsrbpgjVtt65tqTb6PLSOHZ0vu_fl2TyvEjdQrCUEzb1QQGjWHpN0Gb3O1m4sLnrDd9xFLi0LovK8fXkISievZHdeTwc1e27cmi5iidZG8mVLyCWjEFb4yM3bXfn0uORlEZlHvJ1ha-QFAmFaX6YEqzCUu0QOir2bpy-7k0JFxJLIB3SN6WdvSd0gQBmUJv8ELCXKk4D-Tol8Rzz8wm_ikVDTqOyJcceZpxSBxZ1OHVnrfHQooD39pPj2ZS8RZJJNhwEwxPETrVaivF201Wt54UTUGC-t0tBXxp_2SSVqVIZG4k6WQLNOEskId7XeAiBuIpmwzsaUD-Nbldqcji71JegZm_L4FIQ2bnSFQbzAQ_N2-VY4LQsp9iQIofTOAv7JnyrqrX-jAyXX_QxUdUnJMul_K1iN3GSWhFKp1NklX5kYhJK3q4mzEoyOH3_s_MbIBiPLDvupe5NDGxI1zFpn0bCQZm3lhRmopAP5PJMZE0_APLq0WYGyQJ0j3VAubsVLYxyC2Rif2XpN_1a3ikkmiCAAxV7ked8zmH4dU46GRU5ZzKYrZjB6YX1sXIAsK_JqfZhCh1v15P1nm5K5TyD7O1SnV1q9fg3GKRY4D7q8kDHsI0JTlpj12U8lILdec8cKNgsZMA-Q33_fMqFfdGPdmib64YstPl-HWGd6jxuY_DyphxGhdXfRaqQ-HI4UKahMZuctT1EBhUj1iXyeqpyLQni0i32JOhKSXw-6zqbR9Trcizf7aMhDiANLqJK2lobBKDwR3mtR3kkj0N5vdRpFOqQlSdVbdPJOTVpD3rYtOaxDTt50F9EolgnCMaVfMlnpBMusbwkpAwl4WX75vbjxcmwNl-Q3uyaUXLpSfibbTYimDFIrzOmIwNCy2ayf1Tgrye2Hn6ap9DqfxXFyjPaaEpcS4Dv3fHG_W2u3nsd0Y0pmV3jT24N75BaR6pIyfTKJ511Y5xa-z2gGVScGN_oHpMrwaHzcWy-33yIOXO1hRqMwOZ3nT1g&bs=1&cookie_sync_ab_gk=1&reader_gdpr_flag=0&reader_gdpr_consent=&gdpr_binary_consent=opt-out&gdpr_comes_from_infopack=0&reader_us_privacy=1---

### Notes

If the above replacement link is not correct, this could be it: https://stream-03.nyc.dailymotion.com/sec(Rt6MMB82ZLcHsd-t3Q1irSOzLNj8v3SpAYiTdlqrW-xU7Vg0YgjQlxRV8j4XfmHZ)/dm/3/x6inuzo/s/live-1.m3u8

The link here in the notes seems to require updating every once in a while because the m3u seems to change after some time.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by kaikyoofers** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/dy4TXNUDSdWyS39
