### ISSUE TITLE
Replace: RTK 1-4

### ISSUE THREAD

**Issue by lindon-c** [iptv-org/iptv#11440]
### Broken Link

http://stream1.rtkit.com:1935/rtk1stream/rtk1.stream/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://ub1doy938d.gjirafa.net/live/Gfsqdsr7FewrYClU3ACEGZvCHktt2wse/zykxzq1080/index.m3u8

### Notes

rtk1 correct link:
https://ub1doy938d.gjirafa.net/live/Gfsqdsr7FewrYClU3ACEGZvCHktt2wse/zykxzq1080/index.m3u8

rtk2 broken link:
http://stream1.rtkit.com:1935/rtk2stream/rtk2.stream/playlist.m3u8

correct link:
https://ub1doy938d.gjirafa.net/live/Gfsqdsr7FewrYClU3ACEGZvCHktt2wse/zykxz01080/index.m3u8

rtk3 broken link:
http://stream1.rtkit.com:1935/rtk3stream/rtk3.stream/playlist.m3u8

correct link:
https://ub1doy938d.gjirafa.net/live/Gfsqdsr7FewrYClU3ACEGZvCHktt2wse/zykxzk1080/index.m3u8

rtk4 broken link:
http://stream1.rtkit.com:1935/rtk4stream/rtk4.stream/playlist.m3u8

correct link:
https://ub1doy938d.gjirafa.net/live/Gfsqdsr7FewrYClU3ACEGZvCHktt2wse/zykxgt1080/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://ub1doy938d.gjirafa.net/live/Gfsqdsr7FewrYClU3ACEGZvCHktt2wse/zykxzq1080/index.m3u8
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/7253922/232255695-0ecd0f3d-e758-4cf1-b40f-3da626651c55.png">

**Comment by freearhey** [comment]
Broken link removed from playlist.
