### ISSUE TITLE
Replace: Tokyo MX1 (480p)

### ISSUE THREAD

**Issue by ZXArkin** [iptv-org/iptv#11447]
### Broken Link

http://redlabmcdn.s.llnwi.net/nv02/ryowa8hd/index.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

none

### Notes

Loading slow but is an error can't watch it
Using Potplayer but can't watch because is given an error.
Thank you!
![image](https://user-images.githubusercontent.com/21299971/214774337-1557de97-e616-4a6f-a4ae-dc90f53eb076.png)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by ZXArkin** [comment]
Some mirror sever of Neetball here is a link:
https://neetball.net/live/test2.m3u8 (Tokyo MX)

**Comment by LaneSh4d0w** [comment]
I had added it but I guess it was deleted by mistake once again...

**Comment by freearhey** [comment]
http://redlabmcdn.s.llnwi.net/nv02/ryowa8hd/index.m3u8
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/7253922/232261407-205c14a5-37c3-4672-ae4b-06cb771a07b2.png">
