### ISSUE TITLE
Add: Ardeal TV [Romania Regional TV]

### ISSUE THREAD

**Issue by BellezaEmporium** [iptv-org/iptv#11444]
### Channel ID

ArdealTV.ro

### Stream URL

https://rtsp.me/embed/yZ9ED27Q/

### Notes

Tokened stream, token is linked to IP.
@ovidiuux maybe ?

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by ovidiuux** [comment]
Hmm. Interesting that a few days ago I worked on this. So if you inspect the page you can see <script src="https://...rtspe.me/...yZ9ED27Q.js?time=16....."/>
Just replace ".js" with ".m3u8" and it will work perfectly.

But the problem part is that when I want to send the client IP it is not present. Probably the IP address via proxy, it's done in PHP their website and I don't know how they get their IP address. 

And the even more problematic part. The server provided by deta.dev (https://deta.sh) is provided by AWS and the IP address from the server is provided.

**Comment by ovidiuux** [comment]
But I could fix it, read directly .m3u8 and re-streaming to re-streaming ;) 

Yeeeeeeees, the same IP is dynamic and changes with every request.  And basically the link will be invalid.

**Comment by LaneSh4d0w** [comment]
> Hmm. Interesting that a few days ago I worked on this. So if you inspect the page you can see <script src="https://...rtspe.me/...yZ9ED27Q.js?time=16....."/> Just replace ".js" with ".m3u8" and it will work perfectly.
> 
> But the problem part is that when I want to send the client IP it is not present. Probably the IP address via proxy, it's done in PHP their website and I don't know how they get their IP address.
> 
> And the even more problematic part. The server provided by deta.dev (https://deta.sh) is provided by AWS and the IP address from the server is provided.

You won't need the client IP I believe, unless they've put it in between the hostname and stream name

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/ro.m3u#L153-L154
