### ISSUE TITLE
Replace: Paramount Comedy Russia

### ISSUE THREAD

**Issue by christiangriffin** [iptv-org/iptv#11450]
### Broken Link

https://iptv-org.github.io/iptv/countries/ru.m3u

### What happened to the stream?

Not loading

### Notes

The channel seems to be starting but after some minutes the channel isn't working and it shows the "playback error" message. If you need a streaming of *Paramount Comedy Russia* there are some websites that offer (for free and legally) the live streaming of it.
*oVeGo*: http://ovego.tv/publ/live_tv/razvlekatelnye/paramount_comedy/7-1-0-1188)
*Onlinetv.one* : https://onlinetv.one/paramount-comedy-online.php

I hope you can fix this channel and thank you for your beautiful IPTV lists  :-) 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
https://nl2.justv.org:8080/hls/comedy/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MS8yNy8yMDIzIDEwOjA3OjI4IEFNJmhhc2hfdmFsdWU9a0kwNk1GMStWaFJDV2FjUzFjZWFXZz09JnZhbGlkbWludXRlcz0xNDQwMDAwMDAwMA==

Will depend on the wmsAuthSign... if it's IP-locked sadly we can't do much.

**Comment by albghost** [comment]
m3u8 sports europe?

**Comment by albghost** [comment]
m3u8 sports europe?
