### ISSUE TITLE
Digi24 RO

### ISSUE THREAD

**Issue by DjRoberto69** [iptv-org/iptv#11452]
### Channel ID

Digi24 HD

### Stream URL

https://edge-ar.rcs-rds.ro/digi24ar/hd.m3u8

Digi24 SD

### Stream URL

https://edge-ar.rcs-rds.ro/digi24ar/hq.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://github.com/iptv-org/iptv/blob/c7ab439f8bbb51b349fbb5eb2f5c6aa859177b59/streams/ro.m3u#L26-L27
