### ISSUE TITLE
Islamic Channel

### ISSUE THREAD

**Issue by rmkhalfay** [iptv-org/iptv#11464]
### Channel ID
Islamic Channel

### Stream URL

https://www.youtube.com/watch?v=7NmtXFWrNn0

### Notes

Kindly provide the m3u string / link for the free channel LIVE on https://www.youtube.com/watch?v=7NmtXFWrNn0 which will work with IPTV player

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://youtube.com/@TheIslamicChannelOfficial/live

Not 24/7

**Comment by rmkhalfay** [comment]
Sir

Thank you

But this link does not work on my iptv player

**Comment by kaikyoofers** [comment]
Its because the channel is not live right now

**Comment by rmkhalfay** [comment]
I checked this channel is live now but not working with iptv player like perfect player

**Comment by kaikyoofers** [comment]
https://ythls.onrender.com/channel/UC7Bo58sBtX5u738_B-6josg.m3u8

**Comment by rmkhalfay** [comment]
Channel not seen now; Please advise new link or check the link
