### ISSUE TITLE
Islam Channel 

### ISSUE THREAD

**Issue by rmkhalfay** [iptv-org/iptv#11465]
### Channel ID

Islam Channel English

### Stream URL

https://watch.islamchannel.tv/live/

### Notes

Kindly provide the m3u link / string which will work with any IPTV player for https://watch.islamchannel.tv/live/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
https://live.islamchannel.tv/islamtv_english/live.m3u8

**Comment by kaikyoofers** [comment]
Also its already in the UK playlist, just the bot set it to timeout so it wont appear

**Comment by rmkhalfay** [comment]
Many many thanks this works

**Comment by rmkhalfay** [comment]
Link not working

**Comment by kaikyoofers** [comment]
> Link not working

New link: https://live.islamchannel.tv/live7/islamtv_english/bitrate1.isml/playlist.m3u8
