### ISSUE TITLE
Add: SerTV [PA]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11476]
### Channel ID

SerTV.pa

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x81cvsk

### Notes

Not 24/7.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/pa.m3u#L26-L27
