### ISSUE TITLE
Add: Cultura Online [CL]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11479]
### Channel ID

CulturaOnline.cl

### Stream URL

https://v1.tustreaming.cl:19360/culturaonline/culturaonline.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
Works for me.

**Comment by Carlinhos027** [comment]
> Works for me.

And for me too, but it's already on streams/cl.m3u

**Comment by kaikyoofers** [comment]
Oh ok.
