### ISSUE TITLE
Add: TV Cancao Nova Portugal [PT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11495]
### Channel ID

TVCancaoNovaPortugal.pt

### Stream URL

https://5c65286fc6ace.streamlock.net/cancaonova/CancaoNova/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://5c65286fc6ace.streamlock.net/cancaonova/CancaoNova/playlist.m3u8
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/7253922/232255588-9b4a301f-ccf8-4f79-b76b-7ac3fc109214.png">
