### ISSUE TITLE
Add: RTP Memoria [PT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11494]
### Channel ID

RTPMemoria.pt

### Stream URL

https://streaming-live.rtp.pt/liverepeater/smil:rtpmem.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://streaming-live.rtp.pt/liverepeater/smil:rtpmem.smil/playlist.m3u8
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/7253922/232255566-b0795924-bcb6-4a57-bae3-45cc1cdc3f77.png">
