### ISSUE TITLE
Add: CM El Canal de la Musica [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11506]
### Channel ID

CMElCanaldelaMusica.ar

### Stream URL

http://g5.vxral-slo.transport.edge-access.net/a09/ngrp:CM_CanaldelaMusica-100044_all/Playlist.m3u8

### Notes

Iphone agent

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Toei79** [comment]
error, other you share give same result.
