### ISSUE TITLE
Add: Telemax [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11514]
### Channel ID

Telemax.do

### Stream URL

https://cdn2.streamgato.us/telemax/telemax/playlist.m3u8

### Notes

Disappeared from the playlist

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/do.m3u#L292-L293
