### ISSUE TITLE
Add: TV Venezuela [VE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11510]
### Channel ID

TVVenezuela.ve

### Stream URL

https://vp01-tvviptv.delivery.fuugo.com/ngrp:vp01-TVV_IPTV-50e217f2_all/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
No data

**Comment by LaneSh4d0w** [comment]
though there's Venezolana de Television : http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/player/video/x828i6j
