### ISSUE TITLE
Add: Resplandor TV [DO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11515]
### Channel ID

ResplandorTV.do

### Stream URL

https://ss2.domint.net:3100/rtv_str/rvision/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/do.m3u#L296-L297
