### ISSUE TITLE
Add: help with radio stations

### ISSUE THREAD

**Issue by Toei79** [iptv-org/iptv#11524]
### Channel ID

rcn

### Stream URL

https://us-b4-p-e-cg11-audio.cdn.mdstrm.com/live-audio-aw/632c9ae6660fef03fe3855fe/playlist.m3u8?listeningSessionID=63aa937c0098b48b_3108909_6QYJUEVZ__0000007WCiE&downloadSessionID=0&aid=6271a4d5d206c3172f3c9a9c&dnt=true&uid=9MJp0syQTSvKQAGHbX6RP3Ld4pUr2TQZ&sid=6DQRqJbw96naLuGMG0QEgsCTC8lMLcxN&pid=gk2RaQFVjpsHrHxsjmHD2kQFm3BqVh7L&ref=www.lamega.com.co&es=us-b4-p-e-cg11-audio.cdn.mdstrm.com&ote=1675318570536&ot=fvN8BDFVFLevKhTxXlLIVg&proto=https&pz=us&cP=128000&awCollectionId=6271a4d5d206c3172f3c9a9c&aw_0_1st.playerId=appName&liveId=632c9ae6660fef03fe3855fe&referer=https%3A%2F%2Fwww.lamega.com.co%2F&propertyName=appName&propertyType=web-app&propertyVersion=v0.0.200

### Notes

wondering if any advice with those, previously i used to get links from those stations with idm aka internet download manager, but not longer, they change from radioworld i guess to this

https://us-b4-p-e-cg11-audio.cdn.mdstrm.com/live-audio-aw/632c9ae6660fef03fe3855fe/playlist.m3u8?listeningSessionID=63aa937c0098b48b_3108909_6QYJUEVZ__0000007WCiE&downloadSessionID=0&aid=6271a4d5d206c3172f3c9a9c&dnt=true&uid=9MJp0syQTSvKQAGHbX6RP3Ld4pUr2TQZ&sid=6DQRqJbw96naLuGMG0QEgsCTC8lMLcxN&pid=gk2RaQFVjpsHrHxsjmHD2kQFm3BqVh7L&ref=www.lamega.com.co&es=us-b4-p-e-cg11-audio.cdn.mdstrm.com&ote=1675318570536&ot=fvN8BDFVFLevKhTxXlLIVg&proto=https&pz=us&cP=128000&awCollectionId=6271a4d5d206c3172f3c9a9c&aw_0_1st.playerId=appName&liveId=632c9ae6660fef03fe3855fe&referer=https%3A%2F%2Fwww.lamega.com.co%2F&propertyName=appName&propertyType=web-app&propertyVersion=v0.0.200

and sucks expire links its not way to tune on other devices, its anyway to extract radio links?
kinda off topic because radios not here but. i can get a hand here maybe

 thanks for help

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
RCN Colombia : https://mdstrm.com/audio/632c9ae6660fef03fe3855fe/live.m3u8

**Comment by Toei79** [comment]
> RCN Colombia : https://mdstrm.com/audio/632c9ae6660fef03fe3855fe/live.m3u8

How you do it? I need do same with other radios there thanks

I'm dont give ne that one

**Comment by Toei79** [comment]
> RCN Colombia : https://mdstrm.com/audio/632c9ae6660fef03fe3855fe/live.m3u8

I going to try same link estructure and using xxx number in others, maybe?

**Comment by LaneSh4d0w** [comment]
> > RCN Colombia : https://mdstrm.com/audio/632c9ae6660fef03fe3855fe/live.m3u8
> 
> I going to try same link estructure and using xxx number in others, maybe?

Same structure, but different identifier. It's clearly visible once you have one of the mdstrm server links. (just look before the playlist.m3u8)

**Comment by Toei79** [comment]
> > > RCN Colombia : https://mdstrm.com/audio/632c9ae6660fef03fe3855fe/live.m3u8
> > 
> > 
> > I going to try same link estructure and using xxx number in others, maybe?
> 
> Same structure, but different identifier. It's clearly visible once you have one of the mdstrm server links. (just look before the playlist.m3u8)

What about this  one,  its same company other station, but I get one named chunks.m3u8 no playlist  doesn't work
https://www.lafm.com.co/

**Comment by LaneSh4d0w** [comment]
https://mdstrm.com/audio/632c9b23d1dcd7027f32f7fe/live.m3u8

**Comment by Toei79** [comment]
> https://mdstrm.com/audio/632c9b23d1dcd7027f32f7fe/live.m3u8

Thanks looks like tricky. I need refresh page then I get right one next after it shows chunks one

**Comment by LaneSh4d0w** [comment]
A trick, if you get through the network inspector, filter for "medias" only, and wait before you click on the play button that everything is set up inside the developer panel. Once it's done, click on it, the first link should be one of these.

**Comment by Toei79** [comment]
thanks man for the trick! im going to check those

**Comment by LaneSh4d0w** [comment]
Yes

**Comment by Toei79** [comment]
i dont get any from here, its normal? i just get the chunks with idm

https://sunguide.info/cameras-map-service/
