### ISSUE TITLE
Add: KBS World

### ISSUE THREAD

**Issue by jbcooter** [iptv-org/iptv#11521]
### Channel ID

KBSWorld.kr

### Stream URL

https://kbsworld-ott.akamaized.net/hls/live/2002341/kbsworld/master.m3u8

### Notes

this links works

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by jbcooter** [comment]
still working and just needs to be added to the Korean m3u. thanks!

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/kr.m3u#L114-L115

**Comment by tsjiang2017** [comment]
Did you have KBS chinese broadcasting url?
