### ISSUE TITLE
Üniversite TV (720p) [Not 24/7]

### ISSUE THREAD

**Issue by Emirify** [iptv-org/iptv#11550]
### Broken Link

https://5be5d840359c6.streamlock.net/unitv/unitv/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://vdo.digitalbox.xyz:3986/live/unitvlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://vdo.digitalbox.xyz:3986/live/unitvlive.m3u8
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/7253922/232255661-8f818036-637b-41d1-8a04-8266565ecea2.png">
