### ISSUE TITLE
Add: D5tv [FR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11561]
### Channel ID

D5tv.fr

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/D5tv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Smark223** [comment]
Also http://live.creacast.com/d5tv/smil:d5tv.smil/playlist.m3u8
