### ISSUE TITLE
Add: Regio90 TV [NL]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11570]
### Channel ID

Regio90TV.nl

### Stream URL

https://ms2.mx-cd.net/dtv-02/260-2403096/Regio90TV.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/nl.m3u#L118-L119
