### ISSUE TITLE
Add: DTV Oss & Bernheze [NL]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11572]
### Channel ID

DTVOssBernheze.nl

### Stream URL

https://rrr.sz.xlcdn.com/?account=dtvmaasland&file=dtv1&type=live&service=wowza&protocol=https&output=playlist.m3u8

### Notes

Den Bosch: https://rrr.sz.xlcdn.com/?account=dtvmaasland&file=dtv2&type=live&service=wowza&protocol=https&output=playlist.m3u8

Uden: https://rrr.sz.xlcdn.com/?account=dtvmaasland&file=dtv3&type=live&service=wowza&protocol=https&output=playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/nl.m3u#L30-L31
