### ISSUE TITLE
Add: Siris TV [NL]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11571]
### Channel ID

SirisTV.nl

### Stream URL

https://cdn.streammy.events/siris/playout/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/nl.m3u#L176-L177
