### ISSUE TITLE
Broken: CCTV-15

### ISSUE THREAD

**Issue by nguyenthienminh** [iptv-org/iptv#11594]
### Broken Link

http://116.199.5.52:8114/00000000/index.m3u8?Fsv_CMSID=&Fsv_SV_PARAM1=0&Fsv_ShiftEnable=0&Fsv_ShiftTsp=0&Fsv_chan_hls_se_idx=54&Fsv_cid=0&Fsv_ctype=LIVES&Fsv_ctype=LIVES&Fsv_filetype=1&Fsv_otype=1&Fsv_otype=1&Fsv_rate_id=0&FvSeid=5abd1660af1babb4&Pcontent_id=&Provider_id=

### What happened to the stream?

Not loading

### Notes

This is the CCTV-15 stream, and apparently the IP is knocked completely offline.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by eklins** [comment]
http://hwrr.jx.chinamobile.com:8080/PLTV/88888888/224/3221225641/index.m3u8

**Comment by nguyenthienminh** [comment]
It's a working link, so that's good enough.

> http://hwrr.jx.chinamobile.com:8080/PLTV/88888888/224/3221225641/index.m3u8

**Comment by freearhey** [comment]
http://hwrr.jx.chinamobile.com:8080/PLTV/88888888/224/3221225641/index.m3u8 (offline)
<img width="592" alt="image" src="https://user-images.githubusercontent.com/7253922/232261448-8a09366d-cdda-4848-b13e-e23b3c88923b.png">

**Comment by nguyenthienminh** [comment]
The stream still plays correctly though. 
![image](https://user-images.githubusercontent.com/86407326/232261757-7304b438-7a3f-4fc1-acfc-639f2147191e.png)

**Comment by freearhey** [comment]
Broken link removed from playlist.
