### ISSUE TITLE
Fox 15 West Texas Abilene TX (KXVA) (1080p)

### ISSUE THREAD

**Issue by Talydaria** [iptv-org/iptv#11597]
### Broken Link

http://rplayer.surge.sh/?url=https%3A%2F%2Flivevideo01.myfoxzone.com%2Fhls%2Flive%2F2017381%2Fnewscasts%2Flive.m3u8

### What happened to the stream?

Not loading

### Notes

Cannot load http://rplayer.surge.sh/?url=https%3A%2F%2Flivevideo01.myfoxzone.com%2Fhls%2Flive%2F2017381%2Fnewscasts%2Flive.m3u8HTTP response code:0 This might be a CORS issue, consider installing Allow-Control-Allow-Origin Chrome Extension
61.609 | A network error occurred: manifestLoadError

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://livevideo01.myfoxzone.com/hls/live/2017381/elvs/live.m3u8
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/7253922/232255840-99ff078e-fefb-46c7-b1ab-d926b63a6d2d.png">

**Comment by freearhey** [comment]
Broken link removed from playlist.
