### ISSUE TITLE
Replace: Fox 43 Harrisburg PA (WPMT) (1080p)

### ISSUE THREAD

**Issue by Talydaria** [iptv-org/iptv#11598]
### Broken Link

http://rplayer.surge.sh/?url=https%3A%2F%2Flivevideo01.fox43.com%2Fhls%2Flive%2F2011656%2Fnewscasts%2Flive.m3u8

### What happened to the stream?

Not loading

### Notes

Cannot load http://rplayer.surge.sh/?url=https%3A%2F%2Flivevideo01.fox43.com%2Fhls%2Flive%2F2011656%2Fnewscasts%2Flive.m3u8HTTP response code:0 This might be a CORS issue, consider installing Allow-Control-Allow-Origin Chrome Extension
561.684 | A network error occurred: manifestLoadError

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
https://livevideo01.fox43.com/hls/live/2011656/elvs/live.m3u8

**Comment by freearhey** [comment]
https://livevideo01.fox43.com/hls/live/2011656/elvs/live.m3u8
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/7253922/232255858-d388a0e2-446c-427f-86d9-1fbfe0aa237b.png">

**Comment by freearhey** [comment]
Broken link removed from playlist.
