### ISSUE TITLE
Replace: Fox 54.1 Huntsville (1080p)

### ISSUE THREAD

**Issue by Talydaria** [iptv-org/iptv#11599]
### Broken Link

http://rplayer.surge.sh/?url=https%3A%2F%2Flivevideo01.rocketcitynow.com%2Fhls%2Flive%2F2011659%2Fnewscasts%2Flive.m3u8

### What happened to the stream?

Not loading

### Notes

Cannot load http://rplayer.surge.sh/?url=https%3A%2F%2Flivevideo01.rocketcitynow.com%2Fhls%2Flive%2F2011659%2Fnewscasts%2Flive.m3u8HTTP response code:0 This might be a CORS issue, consider installing Allow-Control-Allow-Origin Chrome Extension
667.044 | A network error occurred: manifestLoadError

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
https://livevideo01.rocketcitynow.com/hls/live/2011659/elvs/live.m3u8

**Comment by freearhey** [comment]
https://livevideo01.rocketcitynow.com/hls/live/2011659/elvs/live.m3u8
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/7253922/232255868-0e7bc533-fc0a-4614-9b4e-69c83e769651.png">

**Comment by freearhey** [comment]
Broken link removed from playlist.
