### ISSUE TITLE
Replace: Fox 61 News Hartford CT (WTIC-TV) (1080p)

### ISSUE THREAD

**Issue by Talydaria** [iptv-org/iptv#11600]
### Broken Link

http://rplayer.surge.sh/?url=https%3A%2F%2Flivevideo01.fox61.com%2Fhls%2Flive%2F2011658%2Fnewscasts%2Flive.m3u8

### What happened to the stream?

Not loading

### Notes

Cannot load http://rplayer.surge.sh/?url=https%3A%2F%2Flivevideo01.fox61.com%2Fhls%2Flive%2F2011658%2Fnewscasts%2Flive.m3u8HTTP response code:0 This might be a CORS issue, consider installing Allow-Control-Allow-Origin Chrome Extension
709.905 | A network error occurred: manifestLoadError

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
The link is inside the URL : https://livevideo01.fox61.com/hls/live/2011658/newscasts/live.m3u8

**Comment by LaneSh4d0w** [comment]
Switched to https://livevideo.tegnadigital.com/wtic/v1/master/f9c1bf9ffd6ac86b6173a7c169ff6e3f4efbd693/WTIC/elvs/live.m3u8

**Comment by freearhey** [comment]
https://livevideo.tegnadigital.com/wtic/v1/master/f9c1bf9ffd6ac86b6173a7c169ff6e3f4efbd693/WTIC/elvs/live.m3u8
https://livevideo01.fox61.com/hls/live/2011658/elvs/live.m3u8
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/7253922/232255890-b51c1032-2759-4c00-ba3c-0b8dc74068bd.png">

**Comment by freearhey** [comment]
Broken link removed from playlist.
