### ISSUE TITLE
Add: Serbian PINK channels 

### ISSUE THREAD

**Issue by MihailoMikazz** [iptv-org/iptv#11604]
### Channel ID

https://github.com/iptv-org/database

### Notes

Hello, I'm new here, but it seems I can't find Serbian PINK channels. Can someone add them? Thanks! you're the best!

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Quite difficult to find around here.
