### ISSUE TITLE
Add: El SelloTV Madariaga

### ISSUE THREAD

**Issue by Tuyusero** [iptv-org/iptv#11606]
### Channel ID

ElSelloTVMadariaga.ar

### Stream URL

https://5f700d5b2c46f.streamlock.net:443/elsellotv/elsellotv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/ar.m3u#L251-L252
