### ISSUE TITLE
Broken: Game Show Network East (720p) [Not 24/7]

### ISSUE THREAD

**Issue by nabeelr** [iptv-org/iptv#11608]
### Broken Link

http://n1.klowdtv.net/live2/gsn_720p/chunks.m3u8

### What happened to the stream?

Constantly interrupts/lagging

### Possible Replacement

As per @MapGuy11 https://cdn.klowdtv.net/803B48A/n1.klowdtv.net/live2/gsn_720p/playlist.m3u8 seems to be a good replacement.

### Notes

Constantly freezes.

I don't know of a replacement, but wanted to put it on the radar.

Thanks!

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
still work http://n1.klowdtv.net/live2/gsn_720p/playlist.m3u8 but buffering a bit

**Comment by nabeelr** [comment]
Seems to exhibit the same problem on my end.

**Comment by MapGuy11** [comment]
I recommend using their CDN it's much much faster: https://cdn.klowdtv.net/803B48A/n1.klowdtv.net/live2/gsn_720p/chunks.m3u8

**Comment by nabeelr** [comment]
@MapGuy11 's stream works great! We should add this to the list, to replace the existing entry.
