### ISSUE TITLE
Add: Leman Bleu [CH] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11616]
### Channel ID

LemanBleu.ch

### Stream URL

https://naxoo.vedge.infomaniak.com/livecast/ik:naxoo/manifest.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://naxoo.vedge.infomaniak.com/livecast/ik:naxoo/manifest.m3u8 (offline)
<img width="482" alt="image" src="https://user-images.githubusercontent.com/7253922/232255928-b534af32-3858-4f59-838a-8cff61187fdd.png">

**Comment by Sphinxroot** [comment]
http://livevideo.infomaniak.com/streaming/livecast/naxoo/playlist.m3u8
