### ISSUE TITLE
Add: Bel RTL [BE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11613]
### Channel ID

BelRTL.be

### Stream URL

https://bel-live-hls.akamaized.net/hls/live/2038650/BEL-Live-HLS/master20220524-HLS_1800.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://bel-live-hls.akamaized.net/hls/live/2038650/BEL-Live-HLS/master.m3u8
