### ISSUE TITLE
Replace: Euronews Albania

### ISSUE THREAD

**Issue by lindon-c** [iptv-org/iptv#11634]
### Broken Link

https://hls.youtb.workers.dev/channel/UChR-A__NS_C5kHDWj3PeAhw.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Broken link removed from playlist.
