### ISSUE TITLE
Add: Exodus TV [SI]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11637]
### Channel ID

ExodusTV.si

### Stream URL

https://584943999.r.worldssl.net/584943999/_definst_/vzivo/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://584943999.r.worldssl.net/584943999/_definst_/vzivo/playlist.m3u8
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/7253922/232256089-f8c6f260-cc6d-491d-bc17-aab7832e89d3.png">
