### ISSUE TITLE
Replace: TV Apollon

### ISSUE THREAD

**Issue by lindon-c** [iptv-org/iptv#11635]
### Broken Link

https://live.apollon.tv/Apollon-WEB/video.m3u8?token=tnt3u76re30d2

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://live.apollon.tv/Apollon-WEB/video.m3u8?token=tnt3u76re30d2
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/7253922/232261526-bce4137d-2d95-47fe-a611-d9252a141423.png">
