### ISSUE TITLE
Add: Nopola News [FI]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11647]
### Channel ID

NopolaNews.fi

### Stream URL

https://virta2.nopolanews.fi:8443/live/smil:Stream1.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://virta2.nopolanews.fi:8443/live/smil:Stream1.smil/playlist.m3u8
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/7253922/232256169-70670627-4f2a-4ea5-8305-c3a43550fe66.png">
