### ISSUE TITLE
Broken: C8 [FR] on Tizen OS (Samsung TV)

### ISSUE THREAD

**Issue by IDrissAitHafid** [iptv-org/iptv#11641]
### Broken Link

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/C8TV

### What happened to the stream?

Not loading

### Notes

I am uncertain if the issue lies with the player, as I have tried multiple players on my Samsung TV but C8 france channel is not loading on all of them. However, when I play the same channel using VLC player on my laptop, it works perfectly. 

If it is just a player issue, can someone recommend a better player that I can find on Samsung Tizen TV?

Thank you!

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
https://github.com/iptv-org/iptv/discussions/5395#discussioncomment-4876658

**Comment by Sphinxroot** [comment]
if you have your own list you can use dailymotion link  as https://www.dailymotion.com/video/x5gv5rr#tab_embed.m3u8  vlc only

**Comment by IDrissAitHafid** [comment]
@Sphinxroot thanks for the link! but I don't have the issue on VLC! I have it on my TV and this link didn't work too.

**Comment by LaneSh4d0w** [comment]
Sadly the issue is way too precise to be something linked to our streams. I believe it's a lack of support from the player, and AFAIK Televizo is also available on TVs.

I have it on mine, and i'm quite OK with it (it even has the built-in EPG that grabs the info from iptv-org/epg)

**Comment by IDrissAitHafid** [comment]
@LaneSh4d0w thanks for the explanation. 
unfortunately, I didn't find Televizo on my TV.

**Comment by freearhey** [comment]
Broken link removed from playlist.
