### ISSUE TITLE
Add: dlaCiebie.tv [PL]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11645]
### Channel ID

dlaCiebietv.pl

### Stream URL

http://94.246.128.53:1935/tv/dlaCiebieTv/playlist.m3u8

### Notes

Alt: https://6034e09794f07.streamlock.net/tv/dlaCiebieTv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://94.246.128.53:1935/tv/dlaCiebieTv/playlist.m3u8 (offline)
<img width="383" alt="image" src="https://user-images.githubusercontent.com/7253922/232256138-5e73db33-2df3-42e7-8384-7132040c8cca.png">

https://6034e09794f07.streamlock.net/tv/dlaCiebieTv/playlist.m3u8 (offline)
<img width="480" alt="image" src="https://user-images.githubusercontent.com/7253922/232256156-060ee7c7-1de6-4cb5-bb67-fcd6b9c7a268.png">
