### ISSUE TITLE
Add: Navahang TV [FI]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11646]
### Channel ID

NavahangTV.fi

### Stream URL

http://51.210.227.130/hls/stream.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://51.210.227.130/hls/stream.m3u8 (offline)
<img width="290" alt="image" src="https://user-images.githubusercontent.com/7253922/232208055-69b55880-91f1-4b04-a378-27a288ad53a8.png">

**Comment by freearhey** [comment]
Closed in favor of #11771
