### ISSUE TITLE
Albania

### ISSUE THREAD

**Issue by ardian1970** [iptv-org/iptv#11653]
### Channel ID

Alb tring digitalb

### Stream URL

http://venomtt.com:8000/get.php?username=aGHGd1Qq&password=n7Ucxnp&type=m3u_plus&output=ts

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
We do not accept Xtream-Codes server streams in here.
