### ISSUE TITLE
Add: Kohavision [XK]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11666]
### Channel ID

Kohavision.xk

### Stream URL

https://ub1doy938d.gjirafa.net/live/Gfsqdsr7FewrYClU3ACEGZvCHktt2wse/yt1q1x.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/xk.m3u#L12-L13
