### ISSUE TITLE
Add: Cancionero TV [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11679]
### Channel ID

CancioneroTV.es

### Stream URL

http://89.140.229.4/hls1/cancionero.m3u8

### Notes

Not 24/7

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://89.140.229.4/hls1/cancionero.m3u8
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/7253922/232256285-767936db-6e4d-4b27-b005-dd8ff6e23e3e.png">
