### ISSUE TITLE
Fix: PTV Sports not working 

### ISSUE THREAD

**Issue by zahidashraf789** [iptv-org/iptv#11675]
### Describe your issue

PTV Sports not playing 
Please solve this

**Comment by Saqib050** [comment]
Same problem not loading please replace the link

**Comment by freearhey** [comment]
Please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=%F0%9F%9B%A0+broken+stream&template=-----broken-stream.yml&title=Broken%3A+
