### ISSUE TITLE
Add: Cordoba TV [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11677]
### Channel ID

CordobaTV.es

### Stream URL

https://cloudvideo.servers10.com:8081/8020/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://cloudvideo.servers10.com:8081/8020/index.m3u8
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/7253922/232256226-5ef5fcf1-efbc-4020-a5ff-46c3750c78f7.png">
