### ISSUE TITLE
Add: Fuel TV

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#11685]
### Channel ID

FUELTV.at

### Stream URL

https://fueltv-fueltv-2-gb.samsung.wurl.com/manifest/playlist.m3u8

### Notes

Must-have

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://fueltv-fueltv-2-gb.samsung.wurl.com/manifest/playlist.m3u8 (offline)
<img width="471" alt="image" src="https://user-images.githubusercontent.com/7253922/233810973-28aebae1-6971-4b60-bdc7-b694a3d01fbb.png">
