### ISSUE TITLE
Add: America Television [PE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11687]
### Channel ID

AmericaTelevision.pe

### Stream URL

https://prepublish.f.qaotic.net/a07/americahls-100056/playlist_720p.m3u8

### Notes

Iphone ref

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
América is Argentinian.

**Comment by Carlinhos027** [comment]
> América is Argentinian.
There's another different channel in Peru. 
https://es.m.wikipedia.org/wiki/Am%C3%A9rica_Televisi%C3%B3n_(Per%C3%BA)

**Comment by BellezaEmporium** [comment]
Yes, but the link you've given is the link to the Argentinian channel.

**Comment by Carlinhos027** [comment]
> Yes, but the link you've given is the link to the Argentinian channel.

True. Mistake, sorry :S
