### ISSUE TITLE
Replace: Fox News Channel

### ISSUE THREAD

**Issue by throwawaycodergit** [iptv-org/iptv#11702]
### Broken Link

http://trn03.tulix.tv/AsEAeOtIxz/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://s1.ustv247.live/hls/fxhd=EFMSDJMFKlmzdlkdzslmslssjimznMIJZDM.m3u8

### Notes

Source: https://tv.ustvgo.live/fox-news-live/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by MapGuy11** [comment]
TOKENED

**Comment by throwawaycodergit** [comment]
It appears that USTVGO is back. There are many other streams that can be added as well, but I don't have time to add them all here.  Just view the site above ;)

**Comment by MapGuy11** [comment]
> It appears that USTVGO is back. There are many other streams that can be added as well, but I don't have time to add them all here. Just view the site above ;)

They token their streams so we are unable to keep them running.

**Comment by throwawaycodergit** [comment]
> They token their streams so we are unable to keep them running.

Oh, that's a shame. Sorry, I didn't realize. The same link appeared in two different sessions, so I assumed it would work. They also seem to mirror it on twitch, but that probably wouldn't work either.

**Comment by throwawaycodergit** [comment]
@MapGuy11 
It appears that the link has changed and no longer appears to be tokened.

https://s1.ustv247.live/hls/foxnews.m3u8

Would this new link work and if so, should a new issue be opened for the new link?

**Comment by freearhey** [comment]
https://s1.ustv247.live/hls/fxhd=EFMSDJMFKlmzdlkdzslmslssjimznMIJZDM.m3u8 (offline)
<img width="564" alt="image" src="https://user-images.githubusercontent.com/7253922/232261571-38e5a607-4145-4d84-8a10-67e5af1d3c37.png">

**Comment by throwawaycodergit** [comment]
Update:
It seems like there's a new link, but it gives a 403 error:
https://watch.ustvgo.live/live/foxnews_tv.m3u8

Maybe it's something like a referrer issue?  It came from [this page](https://ustvgo.live/fox-news-live/), so maybe any necessary headers can be obtained from there.

**Comment by samueler2016** [comment]
New replacements?

**Comment by beigexperience** [comment]
lol they've started directly streaming on twitch

**Comment by Hammargren85** [comment]
Replacement please. 
The blurry one gives me nausea
