### ISSUE TITLE
Add: UTV [CZ]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11707]
### Channel ID

UTV.cz

### Stream URL

http://vysilani.zaktv.cz/broadcast/hls/utv/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/cz.m3u#L45-L46
