### ISSUE TITLE
Add: Sardegna Uno [IT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11714]
### Channel ID

SardegnaUno.it

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/sardegna1

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/sardegna1 (offline)

**Comment by azgaresncf** [comment]
i will add this channel on a repo
