### ISSUE TITLE
Add: Rock TV [RO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11726]
### Channel ID

RockTV.ro

### Stream URL

https://tv.broadcasting.ro/memfs/8a3d88be-1464-4380-8b8f-ea7e5bf62663.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/ro.m3u#L127-L128
