### ISSUE TITLE
Add: Kiss TV [RO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11725]
### Channel ID

KissTV.ro

### Stream URL

https://tv.broadcasting.ro/memfs/a629c031-2170-4ee9-a36d-87a891aa3131.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/ro.m3u#L119-L120
