### ISSUE TITLE
Add: Radio Televizija Banovina [HR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11728]
### Channel ID

RadioTelevizijaBanovina.hr

### Stream URL

https://pool.alter-media.hr:1936/live/myStream/playlist.m3u8?DVR

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://pool.alter-media.hr:1936/live/myStream/playlist.m3u8?DVR
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/7253922/232256359-668396ac-d2b5-4847-bf82-f3b31da1697b.png">
