### ISSUE TITLE
Replace: OTV [HR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11727]
### Broken Link

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x654gen

### What happened to the stream?

Not loading

### Possible Replacement

https://stream.agatin.hr:3559/live/otvlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://stream.agatin.hr:3559/live/otvlive.m3u8
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/7253922/232256346-24879cfd-cb32-42fc-a91f-d7f564945ad9.png">

**Comment by freearhey** [comment]
Broken link removed from playlist.
