### ISSUE TITLE
Add: Realitatea Plus [RO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11723]
### Channel ID

RealitateaPlus.ro

### Stream URL

https://edge.realitatea.net/realitatea/plus_fq/playlist.m3u8

### Notes

Star: https://streamx.realitatea.net/realitatea/star_md/playlist.m3u8
Sportiva: https://streamx.realitatea.net/realitatea/sportiva_md/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/ro.m3u#L63-L64
