### ISSUE TITLE
Add: Magic TV [RO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11724]
### Channel ID

MagicTV.ro

### Stream URL

https://tv.broadcasting.ro/memfs/925f90db-5c88-4190-a53d-5163cdffe6f4.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/ro.m3u#L129-L130
