### ISSUE TITLE
Please add CNN USA

### ISSUE THREAD

**Issue by ishobayo** [iptv-org/iptv#1173]
Please add CNN USA

**Comment by SileC** [comment]
http://ott-cdn.ucom.am/s27/index.m3u8

**Comment by freearhey** [comment]
Done.
https://github.com/iptv-org/iptv/blob/c83fbd1e3f153dd179ef4152648d0840ec09d5fc/channels/us.m3u#L912-L915

**Comment by ishobayo** [comment]
I'll try that out by copying http://ott-cdn.ucom.am/s27/index.m3u8 into my portal url - Smart STB

**Comment by SileC** [comment]
Added to iptv list but works only in GSE.
