### ISSUE TITLE
Add: Telefe Rosario

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#11736]
### Channel ID

TelefeRosario.ar

### Stream URL

https://rosario.mitelefe.com/vivo

### Notes

With Token

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/2d7cdb838a6f2e796d3affa9f6b4b6473f5b411f/streams/ar.m3u#L525-L526
