### ISSUE TITLE
Add: Telefe Santa Fe

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#11739]
### Channel ID

TelefeSantaFe.ar

### Stream URL

https://santafe.mitelefe.com/vivo

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f50b24bd4ba83099f0c7d22b7e25e27f850f51ae/streams/ar.m3u#L569-L570
