### ISSUE TITLE
Add: TV Sonce [MK]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11732]
### Channel ID

TVSonce.mk

### Stream URL

https://media2.streambrothers.com:1936/8142/8142/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://media2.streambrothers.com:1936/8142/8142/playlist.m3u8
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/7253922/232256379-cf4d22de-f447-4910-b389-d7579bd18508.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/4c11bb7d16bbbf13b5b9c56c7a6db326ccd61d24/streams/mk.m3u#L10-L11
