### ISSUE TITLE
Add: TV Vega [SK]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11745]
### Channel ID

TVVega.sk

### Stream URL

http://88.212.7.11/live/test_tv_vega_web_player/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://88.212.7.11/live/test_tv_vega_web_player/playlist.m3u8
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/7253922/232256451-85a07232-8a26-4fb8-88ac-3e630d339d0d.png">
