### ISSUE TITLE
Add: TV Romana [SK]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11747]
### Channel ID

TVRomana.sk

### Stream URL

http://88.212.7.11/live/test_tv_romana_web_player/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Jakubicek222** [comment]
Ty cigan vyjebany
