### ISSUE TITLE
Replace: ATX

### ISSUE THREAD

**Issue by MediaProductions** [iptv-org/iptv#11749]
### Broken Link

https://sub.neetball.net/live/neet.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

all are offline that can find

### Notes

https://sub2.neetball.net/live/neet.m3u8 
http://51.79.193.108:8080/hls/j00052/index.m3u8
http://51.79.193.108:8080/hlsok/j00052/index.m3u8

the links go all unfortunately no longer I hope the ATX goes soon again  and unfortunately you can not find a stream at the moment.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by ZXArkin** [comment]
Here is new link here:
https://code.vthanhtivi.pw/getlink/jptv/107/playlist.m3u8
Thank you!
AT-X 1080p (Sub)

**Comment by ZXArkin** [comment]
https://neetball.net/live/neet.m3u8
Another AT-X link

**Comment by rifaaftarizky** [comment]
> Here is new link here: https://code.vthanhtivi.pw/getlink/jptv/107/playlist.m3u8 Thank you! AT-X 1080p (Sub)

can u refresh link or anything for this new link? i check this is offline stream. thx

**Comment by cloud90** [comment]
broken?

**Comment by Koukun020** [comment]
New Link: https://code.vthanhtivi.pw/getlink/jptv2/107/playlist.m3u8

**Comment by cloud90** [comment]
@kaoru-1  now work! thanks @Koukun020

**Comment by cloud90** [comment]
re broken!!! help me

**Comment by freearhey** [comment]
https://code.vthanhtivi.pw/getlink/jptv2/107/playlist.m3u8
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/7253922/232256517-3e75b78c-e0a5-4243-a670-ed0f29444f4b.png">
