### ISSUE TITLE
Add: TVT [SK]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11746]
### Channel ID

TVT.sk

### Stream URL

http://5ca49f2417d90.streamlock.net/live/turzovka/playlist.m3u8

### Notes

Alt: http://80.94.54.11/live/turzovka/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://5ca49f2417d90.streamlock.net/live/turzovka/playlist.m3u8
http://80.94.54.11/live/turzovka/playlist.m3u8
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/7253922/232256470-eab1db26-0158-4b3d-b86a-112443902383.png">
