### ISSUE TITLE
Add: BTV [SK]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11743]
### Channel ID

BTV.sk

### Stream URL

https://fs3.kabelko.sk/9011/index.m3u8?token=btv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://fs3.kabelko.sk/9011/index.m3u8?token=btv
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/7253922/232256430-4c53d08a-c2f7-4aae-b130-d29b3c27cf4e.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3aef7cdbc4c159c043152f434a750bf4d63d837d/streams/sk.m3u#L62-L63
