### ISSUE TITLE
Replace: [France] TMC broken stream

### ISSUE THREAD

**Issue by benoithamet** [iptv-org/iptv#11757]
### Broken Link

https://tmc-hls-live-cdn1.tf1.fr/out/v1/982927d0b5d24bd58ac42184b10c63d7/index.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
#EXTINF:-1 ,tmc (no sound in ts)
https://origin2.live.salto.fr/pool_u81ytesz/tmc/saltohda/hls_long_enc_tmc/NA/vyMqwiI/index.m3u8
#EXTINF:-1 ,tmc
https://s13.tntendirect.com/tmc/live/playlist.m3u8

**Comment by benoithamet** [comment]
Seems the tntdirect.com link is not very reliable; it has been working for a little less than 2 days and now it is random
I understand there may be client limit on server side but I don't have such issue with other streams

**Comment by freearhey** [comment]
https://origin2.live.salto.fr/pool_u81ytesz/tmc/saltohda/hls_long_enc_tmc/NA/vyMqwiI/index.m3u8 (offline)
<img width="682" alt="image" src="https://user-images.githubusercontent.com/7253922/232261775-66cd7a1c-77d1-473c-af71-04d620f90d8d.png">

https://s13.tntendirect.com/tmc/live/playlist.m3u8 (offline)
<img width="361" alt="image" src="https://user-images.githubusercontent.com/7253922/232261784-b3a82a7a-1f24-4046-aacd-0a5d57e53130.png">

Broken link removed from playlist.
