### ISSUE TITLE
Replace: [France] TF1 broken stream

### ISSUE THREAD

**Issue by benoithamet** [iptv-org/iptv#11754]
### Broken Link

https://tf1-hls-live-cdn1.tf1.fr/out/v1/c2e382be3aa2486e8753747e7bb6157e/index.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
#EXTINF:-1 ,TF1 (No Load)
https://origin2.live.salto.fr/pool_u81ytesz/tf1/saltohda/hls_long_enc_tf1/NA/vyMqwiI/index.m3u8
#EXTINF:-1 ,TF1
https://s14.tntendirect.com/tf1/live/playlist.m3u8

**Comment by BellezaEmporium** [comment]
The Salto links I believe won't be useful as the website will close pretty soon.

**Comment by benoithamet** [comment]
Seems the tntdirect.com link is not very reliable; it has been working for a little less than 2 days and now it is random
I understand there may be client limit on server side but I don't have such issue with other streams

**Comment by BellezaEmporium** [comment]
The new link in fr.m3u should work now.

**Comment by xpierroz** [comment]
however the sound doesn't work

**Comment by BellezaEmporium** [comment]
No issues on my side.

**Comment by benoithamet** [comment]
tested with VLAN, Kodi and NextPVR and have the same issue: no sound

**Comment by BellezaEmporium** [comment]
Tested with MPC-HC & the DASH/HLS player extension : no issues on my side.

**Comment by xpierroz** [comment]
sound doesn't work when there's a france football match for some reason

**Comment by freearhey** [comment]
https://origin2.live.salto.fr/pool_u81ytesz/tf1/saltohda/hls_long_enc_tf1/NA/vyMqwiI/index.m3u8 (offline)
<img width="655" alt="image" src="https://user-images.githubusercontent.com/7253922/232261613-57e6ae44-8093-4a7d-a3f7-2916e13927a4.png">

https://s14.tntendirect.com/tf1/live/playlist.m3u8 (offline)
<img width="344" alt="image" src="https://user-images.githubusercontent.com/7253922/232261629-b8eaffa5-d71c-45e5-9f85-7e4ba1119fee.png">

**Comment by freearhey** [comment]
Broken link removed from playlist.
