### ISSUE TITLE
Replace: [France] TF1 Series Films broken stream

### ISSUE THREAD

**Issue by benoithamet** [iptv-org/iptv#11756]
### Broken Link

https://tsf-hls-live-cdn1.tf1.fr/out/v1/0326aeefae1a405c9a9732d6f80a66df/index.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
#EXTINF:-1 ,TF1 Series (no sound in ts)
https://origin2.live.salto.fr/pool_u81ytesz/tf1sf/saltohda/hls_long_enc_tf1sf/NA/vyMqwiI/index.m3u8
#EXTINF:-1 ,TF1 Series
https://s12.tntendirect.com/hd1/live/playlist.m3u8

**Comment by benoithamet** [comment]
Seems the tntdirect.com link is not very reliable; it has been working for a little less than 2 days and now it is random
I understand there may be client limit on server side but I don't have such issue with other streams

**Comment by freearhey** [comment]
https://origin2.live.salto.fr/pool_u81ytesz/tf1sf/saltohda/hls_long_enc_tf1sf/NA/vyMqwiI/index.m3u8 (offline)
<img width="690" alt="image" src="https://user-images.githubusercontent.com/7253922/232261724-abd7d691-58fd-4a01-b366-151fb7d9f78c.png">

https://s12.tntendirect.com/hd1/live/playlist.m3u8 (offline)
<img width="361" alt="image" src="https://user-images.githubusercontent.com/7253922/232261732-c749badf-e11e-4c40-8967-24283d48bbb8.png">

Broken link removed from playlist.
