### ISSUE TITLE
Replace: [France] TFX broken stream

### ISSUE THREAD

**Issue by benoithamet** [iptv-org/iptv#11755]
### Broken Link

https://tfx-hls-live-cdn1.tf1.fr/out/v1/818e38d791854222b71a950791fb7002/index.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
#EXTINF:-1 ,TFX (no sound in ts)
https://origin2.live.salto.fr/pool_u81ytesz/tfx/saltohda/hls_long_enc_tfx/NA/vyMqwiI/index.m3u8
#EXTINF:-1 ,TFX
https://s14.tntendirect.com/nt1/live/playlist.m3u8

**Comment by benoithamet** [comment]
Seems the tntdirect.com link is not very reliable; it has been working for a little less than 2 days and now it is random
I understand there may be client limit on server side but I don't have such issue with other streams

**Comment by freearhey** [comment]
https://origin2.live.salto.fr/pool_u81ytesz/tfx/saltohda/hls_long_enc_tfx/NA/vyMqwiI/index.m3u8 (offline)
<img width="656" alt="image" src="https://user-images.githubusercontent.com/7253922/232261687-66d20979-614d-467f-9357-22cb2d65f3cb.png">

https://s14.tntendirect.com/nt1/live/playlist.m3u8 (offline)
<img width="356" alt="image" src="https://user-images.githubusercontent.com/7253922/232261697-aa1caf4d-e7b6-47fc-b0ed-db94c08b9e72.png">
