### ISSUE TITLE
AP1, Himalaya, Image Channel, NTV

### ISSUE THREAD

**Issue by nepalicana** [iptv-org/iptv#1177]
**Country of the channel: NEPAL**

**Channel Name: AP1 HD**

**Channel Language: NEPALI**

**Additional Information (optional): NEPALI ENTERTAINMENT CHANNEL**

**Country of the channel: NEPAL**

**Channel Name: AVENUES KHABAR**

**Channel Language: NEPALI**

**Additional Information (optional): NEPALI NEWS**

**Country of the channel: NEPAL**

**Channel Name: HIMALAYA TV**

**Channel Language: NEPALI**

**Additional Information (optional): NEPALI ENTERTAINMENT CHANNEL**

**Country of the channel: NEPAL**

**Channel Name: IMAGE CHANNEL**

**Channel Language: NEPALI**

**Additional Information (optional): NEPALI ENTERTAINMENT CHANNEL**

**Country of the channel: NEPAL**

**Channel Name: SAGARMATHA TV**

**Channel Language: NEPALI**

**Additional Information (optional): NEPALI NEWS & ENTERTAINMENT CHANNEL**

**Comment by nepalicana** [comment]
Any chances of getting these channels?

**Comment by freearhey** [comment]
Closed in favor #1963
