### ISSUE TITLE
Add: TV Cultura Nacional [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11793]
### Channel ID

TVCulturaNacional.br

### Stream URL

https://d28367vmhj4ljz.cloudfront.net/out/v1/f26e176ce67244de862cd9b21d823934/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://d28367vmhj4ljz.cloudfront.net/out/v1/f26e176ce67244de862cd9b21d823934/index.m3u8
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/7253922/232256679-b0088c24-8fdf-44ca-af7c-1635b5fccc95.png">
