### ISSUE TITLE
Add: C8 [FR]

### ISSUE THREAD

**Issue by Cerisedesbois** [iptv-org/iptv#11794]
### Channel ID

C8.fr

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
https://www.dailymotion.com/video/x5gv5rr though since free.fullspeed.tv is down...

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/fr_groupecanalplus.m3u#L2-L3

**Comment by Sphinxroot** [comment]
#EXTINF:0,10. C8
http://livetv.ktv.zone/10/play.m3u8

#EXTINF:-1,c8
http://www.callofliberty.fr/stream/C8/master.m3u8
