### ISSUE TITLE
Add: T7 [RS]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11797]
### Channel ID

T7.rs

### Stream URL

https://ub1doy938d.gjirafa.net/live/6rgklscjRSjkIb3cFcFiyCmOrcQ7AWeB/yzg0yt.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fraudiay79** [comment]
All the gjirafa.net are pointless as the URL changes every few days.
