### ISSUE TITLE
Add: Zico TV [RS]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11798]
### Channel ID

ZicoTV.rs

### Stream URL

https://ub1doy938d.gjirafa.net/live/rcBFeREIqcMkNthqI6YCr3Riss97l2MC/y1k0kk.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/rs.m3u#L106-L107
