### ISSUE TITLE
Add: BS11 (Eleven) [JP]

### ISSUE THREAD

**Issue by ZXArkin** [iptv-org/iptv#11808]
### Channel ID

BS11.jp

### Stream URL

https://code.vthanhtivi.pw/getlink/jptv/157/playlist.m3u8

### Notes

I found at this link can be watch it :)
Thank you

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Uses some link from YoiTV (a free program for japanese TV).

I don't quite know how that would work, since it's heavily tokenized.

**Comment by freearhey** [comment]
https://code.vthanhtivi.pw/getlink/jptv/157/playlist.m3u8 (offline)
<img width="403" alt="image" src="https://user-images.githubusercontent.com/7253922/232256853-0cb90ad1-11a4-4b2b-90b7-1f7423fea2be.png">
