### ISSUE TITLE
Add: Sintesis TV [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11802]
### Channel ID

SintesisTV.mx

### Stream URL

http://free.fullspeed.tv/query?url=https://www.twitch.tv/sintesis_tv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://free.fullspeed.tv/query?url=https://www.twitch.tv/sintesis_tv (offline)
