### ISSUE TITLE
Add: SQCS Canal4 [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11801]
### Channel ID

SQCSCanal4.mx

### Stream URL

https://5fa5de1a545ae.streamlock.net/8026/8026/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://5fa5de1a545ae.streamlock.net/8026/8026/playlist.m3u8 (offline)
<img width="454" alt="image" src="https://user-images.githubusercontent.com/7253922/232256724-99bb08e2-7c45-4cb2-ba27-d83def38310e.png">

**Comment by Carlinhos027** [comment]
New link: https://5fa5de1a545ae.streamlock.net/4982/4982/playlist.m3u8

**Comment by freearhey** [comment]
https://5fa5de1a545ae.streamlock.net/4982/4982/playlist.m3u8
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/7253922/235307411-30f72fd9-fa97-433e-ae38-ec5dfbca15b7.png">

**Comment by freearhey** [comment]
https://5fa5de1a545ae.streamlock.net/4982/4982/playlist.m3u8 (Offline)
<img width="465" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/784d2cce-5bdf-4046-bffe-433af88cd895">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/mx.m3u#L122-L123
