### ISSUE TITLE
Replace: Alsharqiya News 

### ISSUE THREAD

**Issue by samg80** [iptv-org/iptv#11818]
### Broken Link

https://5d94523502c2d.streamlock.net/alsharqiyalive/mystream/playlist.m3u8

### What happened to the stream?

Constantly interrupts/lagging

### Possible Replacement

https://www.alsharqiya.com/en/sharqiya-news-live/39846ee7-9408-4c75-88af-98c9eb8c3335

### Notes

Alsharqiya and alsharqiya news bot use the same link 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
#EXTINF:-1 ,AlSharqiya Live https://www.alsharqiya.com/en/sharqiya-live/08c6f77d-4975-4281-822b-65eef2cbf70e
https://5d94523502c2d.streamlock.net/home/mystream/playlist.m3u8
#EXTINF:-1 ,AlSharqiya News Live https://www.alsharqiya.com/en/sharqiya-news-live/39846ee7-9408-4c75-88af-98c9eb8c3335
https://5d94523502c2d.streamlock.net/alsharqiyalive/mystream/playlist.m3u8
