### ISSUE TITLE
Replace: aliraqiya News

### ISSUE THREAD

**Issue by samg80** [iptv-org/iptv#11819]
### Broken Link

https://iptv-org.github.io/iptv/index.country.m3u

### What happened to the stream?

Not loading

### Possible Replacement

https://imn.iq/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
Seem Offline No MediaManifest On

Entertainment
https://cdn.catiacast.video/abr/8d2ffb0aba244e8d9101a9488a7daa05/playlist.m3u8

NEWS
https://cdn.catiacast.video/abr/78054972db7708422595bc96c6e024ac/playlist.m3u8
