### ISSUE TITLE
Add: Tatlises TV [TR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11825]
### Channel ID

TatlisesTV.tr

### Stream URL

https://waw1.artiyerelmedya.net/tatlisestv/bant1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by adinaveh** [comment]
https://live.artidijitalmedya.com/artidijital_tatlisestv/tatlisestv/playlist.m3u8
