### ISSUE TITLE
Replace: NRT

### ISSUE THREAD

**Issue by samg80** [iptv-org/iptv#11820]
### Broken Link

https://iptv-org.github.io/iptv/index.country.m3u

### What happened to the stream?

Stuck at a single frame

### Possible Replacement

https://www.nrttv.com/streamNRT.aspx

### Notes

NRT is stuck on a cartoon show that never ends 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by kaikyoofers** [comment]
URL: https://media.streambrothers.com:1936/8226/8226/playlist.m3u8
