### ISSUE TITLE
Add: Catholic TV [US]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11838]
### Channel ID

CatholicTV.us

### Stream URL

https://catholictvhd-lh.akamaized.net/hls/live/2043390/CTVLiveHD/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://catholictvhd-lh.akamaized.net/hls/live/2043390/CTVLiveHD/master.m3u8
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/7253922/232257882-aa3c6b92-24ed-4235-a3cc-c42eae26ebfd.png">
