### ISSUE TITLE
Add: Paradise TV [IT] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11831]
### Channel ID

ParadiseTV.it

### Stream URL

https://tsw.streamingwebtv24.it:1936/paradisetv/paradisetv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/it.m3u#L611-L612
