### ISSUE TITLE
Add: Padre Pio TV [IT] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11830]
### Channel ID

PadrePioTV.it

### Stream URL

https://600f07e114306.streamlock.net/PadrePioTV/livestream/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/it.m3u#L351-L352
