### ISSUE TITLE
Add: TVT [PL]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11837]
### Channel ID

TVT.pl

### Stream URL

https://live.streamtvt.pl/LiveAppStreamTVT/streams/853271271313930867905724.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://live.streamtvt.pl/LiveAppStreamTVT/streams/853271271313930867905724.m3u8
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/7253922/232257873-60946e1f-17f1-440e-a014-0a58cb18e972.png">
