### ISSUE TITLE
Add: BRT 1 [CY]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11835]
### Channel ID

BRT1.cy

### Stream URL

https://sc-kuzeykibrissmarttv.ercdn.net/brt1hd/bant1/playlist.m3u8

### Notes

BRT 2: https://sc-kuzeykibrissmarttv.ercdn.net/brt2hd/bant1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/cy.m3u#L52-L55
