### ISSUE TITLE
Replace: aljadeedtv

### ISSUE THREAD

**Issue by moh1122** [iptv-org/iptv#11844]
### Broken Link

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/aljadeedtv

### What happened to the stream?

Not loading

### Possible Replacement

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/aljadeedtv

### Notes

I would love if this channel will be back online

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
free.fullspeed.tv is currently offline though dct is actually looking for solutions. we'll see.

**Comment by moh1122** [comment]
Thank you for your quick response, please let me know once its fixed

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/aljadeedtv (offline)

Broken link removed from playlist.
