### ISSUE TITLE
Replace: MTV Lebanon

### ISSUE THREAD

**Issue by moh1122** [iptv-org/iptv#11842]
### Broken Link

https://1537084837.rsc.cdn77.org/1537084837/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://1537084837.rsc.cdn77.org/1537084837/playlist.m3u8

### Notes

It was working yesterday and today its not working anymore any clue?

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
The one after works.

**Comment by BellezaEmporium** [comment]
https://live.3cd.io/v1/broadcast/mtv/playlist.m3u8

**Comment by moh1122** [comment]
thank you really appreaciated

**Comment by moh1122** [comment]
Hello
This one stopped working today also:
https://live.3cd.io/v1/broadcast/mtv/playlist.m3u8

**Comment by BellezaEmporium** [comment]
Maybe a maintenance since it's the CDN77 server that's affected.

**Comment by moh1122** [comment]
Thank you for your quick reply.
Its working for about 30 sec then cutting how to troubleshoot?

**Comment by BellezaEmporium** [comment]
> Thank you for your quick reply. Its working for about 30 sec then cutting how to troubleshoot?

Look with your browser's network inspector, and you should see 404 on the .ts files, meaning the flux doesn't come in. Though the playlist exists.

**Comment by moh1122** [comment]
im running "https://live.3cd.io/v1/broadcast/mtv/playlist.m3u8" on VLC not on a browser

**Comment by BellezaEmporium** [comment]
In this case, look on "Tools -> Messages", you should see a pop-up opening. Move the info level from "0 (errors)" to "4 (debug)"

**Comment by moh1122** [comment]
Ive realized its working normally on media player and not anymore on VLC btw it was working normally on VLC is there any media player you recommend for Android TV

**Comment by BellezaEmporium** [comment]
It's slowly coming back it seems.

**Comment by moh1122** [comment]
Getting this 

http error: local stream 1 error: Cancellation (0x8)
adaptive error: Failed to create demuxer 0000000000000000 Unknown
http error: local stream 1 error: Cancellation (0x8)

**Comment by moh1122** [comment]
Today it stopped working for both links

**Comment by freearhey** [comment]
https://live.3cd.io/v1/broadcast/mtv/playlist.m3u8
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/7253922/232257904-665a2564-53b1-4b52-b778-7aa8cd2833e0.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1c494c6a39b765de57e0c5794e72a86d59516fb0/streams/lb.m3u#L22-L24

**Comment by lq707904686** [comment]
亲爱的[姓名]，

非常感谢您向我发送 IPTV 流的链接。我真的很感激！我很高兴查看内容并了解它所提供的内容。

此致敬意
[你的名字]

Aleksandr Statciuk ***@***.***> 于2023年4月16日周日 10:50写道：

**Comment by RayRaytheGrape** [comment]
Not working for me here in the U.S. this link might be a fix: https://hms.pfs.gdn/stream/mtv.m3u8

**Comment by RayRaytheGrape** [comment]
Broken again
