### ISSUE TITLE
Replace: One Channel (GR)

### ISSUE THREAD

**Issue by TheOneChannelFan** [iptv-org/iptv#11855]
### Broken Link

https://streaming.onetv.gr/show/onetv_hd720/index.m3u8

### What happened to the stream?

Other

### Possible Replacement

https://video-weaver.vie02.hls.ttvnw.net/v1/playlist/CrYFk7h3MvfrG4YVDBexQWgiKjwRxTACBm-LMkLTO7ygRCKmJn2n6LZAbtkeg3h14FKnOB1-eRSorTo8H996IcnAtQ1doG5hlN73wYeiC0GPcG_o8rAMtG9gdrKKP36eS81CApmR2SQqNzIPL5f558nMmLvJ59w-aZKGbfm9KhAheHVEWv_pYaZgnHy-LYmrrDV0OiwqHOrdVPBUeHDeDVuB2avRqxgUXtMF30AHfgo7iznq0PEI4r4hILj0yf-jbklK-x9AvtAR8sJTFOr4Zo_YPAm4ujeKr8a1zfnOBql0oXPNAEEkpTZ9E3bqojRWRqcV8PNzYO910ot3Gpoosh22HRG8NcfRUQraWWGscNQBDbGUJTMFEmt8EUDiu0UxxvTdKuYLT7SPOCOzqFoFR4CcbDAMjEqRo0JlnIjEHZKcBumrbI947zz6wXf6xWuEac6TJyaOqEagLYbv0DQqM0I_KapcCvB3iUF1UyWoIPzyA8__7H3fawNwvYJu0gwNCFLvvAa1LesHYUvId2e0-sgCo-KlZb1bAMQKxwCehB54hcU2-bKfQpq1y9ZVTrsVqZqqfL1s-8-WPDJDBR9XR1t8FD6hUvGfvLPN9x0H30qJznAhEPynbpAncg1IJ-MftHThnjow38xEIiaIa7gXllPUWSO2wnS00O3qrsIPZvOKe2reAJ8fKavvviLUyWaZPN-oYGwgCN9rwdy_q58gn3fQ40BGnkhAK0V9Ovk8vGTwVQDD71gJiOElfCYgsqDRmXfayDLl3Wns7zAoy0cQ9h-fYVEn8mAuX0zPPM2NEm5Cr3yVC1gv2VBgPyZSLrZbvXRPBO9XyygzV_TeKvgV2KIkS3eyWAn0eqkm8XmAu7NLZkrMXP6QAvhX4fKNOZQqGUKg18ZVFz3g8dV5NTBa0qJcA3PP9y0e1hoMKcY72SoxsPKkLzg4IAEqCWV1LXdlc3QtMjCUBg.m3u8

### Notes

First The Problem Of The Old Stream It Ended 2/3 Weeks Ago Second For The New Stream I Know Its Long

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
or you can pipe this link through Streamlink : https://www.twitch.tv/onechanneltv

**Comment by freearhey** [comment]
https://video-weaver.vie02.hls.ttvnw.net/v1/playlist/CrYFk7h3MvfrG4YVDBexQWgiKjwRxTACBm-LMkLTO7ygRCKmJn2n6LZAbtkeg3h14FKnOB1-eRSorTo8H996IcnAtQ1doG5hlN73wYeiC0GPcG_o8rAMtG9gdrKKP36eS81CApmR2SQqNzIPL5f558nMmLvJ59w-aZKGbfm9KhAheHVEWv_pYaZgnHy-LYmrrDV0OiwqHOrdVPBUeHDeDVuB2avRqxgUXtMF30AHfgo7iznq0PEI4r4hILj0yf-jbklK-x9AvtAR8sJTFOr4Zo_YPAm4ujeKr8a1zfnOBql0oXPNAEEkpTZ9E3bqojRWRqcV8PNzYO910ot3Gpoosh22HRG8NcfRUQraWWGscNQBDbGUJTMFEmt8EUDiu0UxxvTdKuYLT7SPOCOzqFoFR4CcbDAMjEqRo0JlnIjEHZKcBumrbI947zz6wXf6xWuEac6TJyaOqEagLYbv0DQqM0I_KapcCvB3iUF1UyWoIPzyA8__7H3fawNwvYJu0gwNCFLvvAa1LesHYUvId2e0-sgCo-KlZb1bAMQKxwCehB54hcU2-bKfQpq1y9ZVTrsVqZqqfL1s-8-WPDJDBR9XR1t8FD6hUvGfvLPN9x0H30qJznAhEPynbpAncg1IJ-MftHThnjow38xEIiaIa7gXllPUWSO2wnS00O3qrsIPZvOKe2reAJ8fKavvviLUyWaZPN-oYGwgCN9rwdy_q58gn3fQ40BGnkhAK0V9Ovk8vGTwVQDD71gJiOElfCYgsqDRmXfayDLl3Wns7zAoy0cQ9h-fYVEn8mAuX0zPPM2NEm5Cr3yVC1gv2VBgPyZSLrZbvXRPBO9XyygzV_TeKvgV2KIkS3eyWAn0eqkm8XmAu7NLZkrMXP6QAvhX4fKNOZQqGUKg18ZVFz3g8dV5NTBa0qJcA3PP9y0e1hoMKcY72SoxsPKkLzg4IAEqCWV1LXdlc3QtMjCUBg.m3u8 (offline)

Broken link removed from playlist.
