### ISSUE TITLE
Replace: CNN International Europe

### ISSUE THREAD

**Issue by eurohunter** [iptv-org/iptv#11869]
### Broken Link

https://cnn-cnninternational-1-de.samsung.wurl.com/manifest/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://cnn-cnninternational-1-eu.rakuten.wurl.tv/playlist.m3u8

### Notes

#EXTINF:-1 tvg-id="CNNInternationalEurope.us",CNN International Europe (720p)
https://cnn-cnninternational-1-eu.rakuten.wurl.tv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1c494c6a39b765de57e0c5794e72a86d59516fb0/streams/uk_rakuten.m3u#L2-L3
