### ISSUE TITLE
Add: Ici Radio-Canada Télé Acadie (CBAFT-DT) [CA]

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#11889]
### Channel ID

CBAFTDT.ca

### Stream URL

https://rcavlive.akamaized.net/hls/live/704014/cancbaft/master_3000.m3u8

### Notes

Official link for ICI R-C Télé Acadie from their official platform tou.tv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Closed in favor of #11911
