### ISSUE TITLE
Back tntendirect.com but with "wmsAuthSign"

### ISSUE THREAD

**Issue by cheznewa** [iptv-org/iptv#1189]
the streams from tntendirect.com work but the prefix change from https://s3. https://s7. nothing to change tntendirect.com/(channelname)/playlist.m3u8 with the option where he down IS ::::::::::::::::::::: ?wmsAuthSign=(string)
the website using recaptcha, please verify if we have the same string

**Comment by freearhey** [comment]
Do you suggest we update all links from tntendirect.com every time wmsAuthSign changes? Do I understand you correctly?

**Comment by cheznewa** [comment]
I'm afraid it's unique by IP address.

**Comment by freearhey** [comment]
So what exactly are you suggesting?

**Comment by cheznewa** [comment]
Not Sure the string is unique per ip address and usage

**Comment by cheznewa** [comment]
I'd like you to check the string if it's different than :::::::::::::::::: wmsAuthSign=c2VydmVyX3RpbWU9NC8xNS8yMDIwIDE6NDQ6NDUgUE0maGFzaF92YWx1ZT1QbmxGcUpYbzVsOXoxNW00WXJnT25RPT0mdmFsaWRtaW51dGVzPTMw for me

**Comment by Nintendocustom** [comment]
c2VydmVyX3RpbWU9NC8xNS8yMDIwIDE6NDQ6NDUgUE0maGFzaF92YWx1ZT1QbmxGcUpYbzVsOXoxNW00WXJnT25RPT0mdmFsaWRtaW51dGVzPTMw = server_time=4/15/2020 1:44:45 PM&hash_value=PnlFqJXo5l9z15m4YrgOnQ==&validminutes=30
https://www.base64decode.org/

**Comment by cheznewa** [comment]
Ho No! tntendirect added a system to expire the auth, i'm sorry for the france, there no more issue subject to tntendirect, except if change the system noauth, all regrets :(
