### ISSUE TITLE
Add: Ici Radio-Canada Télé Est du Québec (CJBR-DT) [CA]

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#11894]
### Channel ID

CJBRDT.ca

### Stream URL

https://rcavlive.akamaized.net/hls/live/704024/cancjbr/master_3000.m3u8

### Notes

Official link for ICI R-C Télé Est du Québec from their official platform tou.tv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://rcavlive.akamaized.net/hls/live/704024/cancjbr/master_3000.m3u8 (offline)
<img width="518" alt="image" src="https://user-images.githubusercontent.com/7253922/232258191-f4e82e9f-8238-4234-a60d-1cea16a2f90a.png">

**Comment by Time-Pare** [comment]
Work on VLC, Geo-restricted to Canada. 
![cjbr](https://user-images.githubusercontent.com/86069942/232329546-c77745fd-5970-4cae-b3f9-84a791ecd147.PNG)
