### ISSUE TITLE
Add: Ici Radio-Canada Télé Colombie-Britannique - Yukon (CBUFT-DT) [CA]

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#11892]
### Channel ID

CBUFTDT.ca

### Stream URL

https://rcavlive.akamaized.net/hls/live/704017/cancbuft/master_3000.m3u8

### Notes

Official link for ICI R-C Télé C-B - Yukon from their official platform tou.tv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://rcavlive.akamaized.net/hls/live/704017/cancbuft/master_3000.m3u8 (offline)
<img width="525" alt="image" src="https://user-images.githubusercontent.com/7253922/232258142-736c6ea8-9f6f-4bd7-8591-3c7bb5e7440c.png">

**Comment by Time-Pare** [comment]
Working on VLC, Geo-restricted to Canada.
![cbuft](https://user-images.githubusercontent.com/86069942/232312949-281abf70-83f9-4dbe-af16-a5f82cadbfd8.PNG)
