### ISSUE TITLE
Add: Ici Radio-Canada Télé Alberta (CBXFT-DT) [CA]

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#11891]
### Channel ID

CBXFTDT.ca

### Stream URL

https://rcavlive.akamaized.net/hls/live/704020/cancbxft/master_3000.m3u8

### Notes

Official link for ICI R-C Télé Alberta from their official platform tou.tv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://rcavlive.akamaized.net/hls/live/704020/cancbxft/master_3000.m3u8 (offline)
<img width="529" alt="image" src="https://user-images.githubusercontent.com/7253922/232258131-cab78855-8b30-43fa-8707-538058396b49.png">

**Comment by Time-Pare** [comment]
On my side, all the links for Radio-Canada works on VLC. They are probably just geo-blocked on your side but definitely not offline.
