### ISSUE TITLE
Add: Ici Radio-Canada Télé Québec (CBVT-DT) [CA]

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#11908]
### Channel ID

CBVTDT.ca

### Stream URL

https://rcavlive.akamaized.net/hls/live/664045/cancbvt/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://rcavlive.akamaized.net/hls/live/664045/cancbvt/master.m3u8 (offline)
<img width="486" alt="image" src="https://user-images.githubusercontent.com/7253922/232258381-0af7df8b-e111-438f-a4a8-b5b3d58ef94b.png">

**Comment by Time-Pare** [comment]
Work on VLC, Geo-Restricted to Canada.
![CBVT](https://user-images.githubusercontent.com/86069942/232264685-308c01b8-cef3-4a63-9ef1-e7dfab07db51.PNG)
