### ISSUE TITLE
Add: Ici Radio-Canada Télé Manitoba (CBWFT-DT) [CA]

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#11902]
### Channel ID

CBWFTDT.ca

### Stream URL

https://rcavlive.akamaized.net/hls/live/704018/cancbwft/master_3000.m3u8

### Notes

Official link for ICI R-C Télé Manitoba from their official platform tou.tv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Master would be https://rcavlive.akamaized.net/hls/live/704018/cancbwft/master.m3u8

GEO to Canada.

**Comment by freearhey** [comment]
https://rcavlive.akamaized.net/hls/live/704018/cancbwft/master_3000.m3u8 (offline)
<img width="531" alt="image" src="https://user-images.githubusercontent.com/7253922/232258297-3ecf7c60-da57-4174-9182-2168ee13a5ae.png">

https://rcavlive.akamaized.net/hls/live/704018/cancbwft/master.m3u8 (offline)
<img width="493" alt="image" src="https://user-images.githubusercontent.com/7253922/232258289-471de633-a004-47df-b71e-679a0dcbf380.png">

**Comment by Time-Pare** [comment]
Master work on VLC, Geo-Restricted to Canada.
![cbwft](https://user-images.githubusercontent.com/86069942/232329768-ba1730e6-6ab3-49da-9b9f-6419c3cc4730.PNG)
