### ISSUE TITLE
Add: Add: Ici Radio-Canada Télé Estrie (CKSH-DT) [CA]

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#11901]
### Channel ID

CKSHDT.ca

### Stream URL

https://rcavlive.akamaized.net/hls/live/704016/cancksh/master_3000.m3u8

### Notes

Official link for ICI R-C Télé Estrie from their official platform tou.tv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Master would be https://rcavlive.akamaized.net/hls/live/704016/cancksh/master.m3u8

GEO to Canada.

**Comment by freearhey** [comment]
https://rcavlive.akamaized.net/hls/live/704016/cancksh/master_3000.m3u8
<img width="528" alt="image" src="https://user-images.githubusercontent.com/7253922/232258263-3ce9f2cf-2103-47c3-9d4c-3e0eabe07c4b.png">

https://rcavlive.akamaized.net/hls/live/704016/cancksh/master.m3u8
<img width="486" alt="image" src="https://user-images.githubusercontent.com/7253922/232258257-4292d6e6-edc0-4bc2-9e9f-ef4b81caed3b.png">

**Comment by Time-Pare** [comment]
Master work on VLC, Geo-Restricted to Canada.
![cksh](https://user-images.githubusercontent.com/86069942/232329653-28e35874-b9e0-48f6-a999-4ff64a1fee3b.PNG)
