### ISSUE TITLE
Add: Ici Radio-Canada Télé Ontario (CBLFT-DT) [CA]

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#11906]
### Channel ID

CBLFTDT.ca

### Stream URL

https://rcavlive.akamaized.net/hls/live/704022/cancblft/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://rcavlive.akamaized.net/hls/live/704022/cancblft/master.m3u8 (offline)
<img width="484" alt="image" src="https://user-images.githubusercontent.com/7253922/232258345-a2a19854-9ffe-4635-9e8a-56d22a509553.png">

**Comment by Time-Pare** [comment]
Work on VLC, Geo-Restricted to Canada.
![CBLFT](https://user-images.githubusercontent.com/86069942/232329911-b9bcdc10-6834-43fd-8efa-7d208d306c9f.PNG)
