### ISSUE TITLE
Broken Link: CNBC Europe

### ISSUE THREAD

**Issue by eurohunter** [iptv-org/iptv#11904]
### Broken Link

http://ott-cdn.ucom.am/s65/index.m3u8

### What happened to the stream?

Not loading

### Notes

Channel ID: CNBCEurope.uk
The link does not seem to work. I have tried it for a few days. Tested from Albania and Netherlands (NL with VPN).

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Smark223** [comment]
Seems to be working for me at the moment, from the UK

**Comment by eurohunter** [comment]
Thank you for checking. Currently, the Broadcast Area for this channel is shown as "r/EUR". I hope someone else from a different European location can check it so that we can determine how widely accessible the link is throughout Europe.

**Comment by eurohunter** [comment]
Actually, I tested it again, and it seems to be working now. Maybe it is not a 24/7 link, but it does work. I will be closing this issue.
