### ISSUE TITLE
Add: Ici Radio-Canada Télé Ottawa - Gatineau (CBOFT-DT) [CA]

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#11907]
### Channel ID

CBOFTDT.ca

### Stream URL

https://rcavlive.akamaized.net/hls/live/664046/cancboft/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://rcavlive.akamaized.net/hls/live/664046/cancboft/master.m3u8 (offline)
<img width="493" alt="image" src="https://user-images.githubusercontent.com/7253922/232258360-099833a7-19ed-41a0-ba54-595f9fd0b1c2.png">

**Comment by Time-Pare** [comment]
Work on VLC, Geo-Restricted to Canada.
![cboft](https://user-images.githubusercontent.com/86069942/232329970-1c85ada4-4f1c-4b95-bf0d-675e06c5d474.PNG)
