### ISSUE TITLE
Add: Ici Radio-Canada Télé Mauricie - Centre-du-Québec (CKTM-DT) [CA]

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#11903]
### Channel ID

CKTMDT.ca

### Stream URL

https://rcavlive.akamaized.net/hls/live/704021/cancktm/master_3000.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Master would be https://rcavlive.akamaized.net/hls/live/704021/cancktm/master.m3u8

GEO to Canada.

**Comment by freearhey** [comment]
https://rcavlive.akamaized.net/hls/live/704021/cancktm/master_3000.m3u8 (offline)
<img width="521" alt="image" src="https://user-images.githubusercontent.com/7253922/232258319-351d1cfd-f462-40fa-aba0-923d7da2e710.png">

https://rcavlive.akamaized.net/hls/live/704021/cancktm/master.m3u8 (offline)
<img width="480" alt="image" src="https://user-images.githubusercontent.com/7253922/232258314-88cdf4c5-0033-4ca3-8f27-48680fce1115.png">

**Comment by Time-Pare** [comment]
Master work on VLC, Geo-Restricted to Canada.
![cktm](https://user-images.githubusercontent.com/86069942/232329848-0ebce3d2-1d51-45f0-ab84-76ac6cc5f5d2.PNG)
