### ISSUE TITLE
Add: Ici Radio-Canada Télé Saguenay - Lac-St-Jean (CKTV-DT) [CA]

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#11909]
### Channel ID

CKTVDT.ca

### Stream URL

https://rcavlive.akamaized.net/hls/live/704023/cancktv/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://rcavlive.akamaized.net/hls/live/704023/cancktv/master.m3u8 (offline)
<img width="480" alt="image" src="https://user-images.githubusercontent.com/7253922/232258395-c8d9aa33-394e-4676-bede-c275d961c852.png">

**Comment by Time-Pare** [comment]
Work on VLC, Geo-Restricted to Canada.
![CKTV](https://user-images.githubusercontent.com/86069942/232264611-24c64b9e-f0a3-44bb-9035-c11dced1172e.PNG)
