### ISSUE TITLE
Add: Ici Radio-Canada Télé Saskatchewan (CBKFT-DT) [CA]

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#11910]
### Channel ID

CBKFTDT.ca

### Stream URL

https://rcavlive.akamaized.net/hls/live/704019/cancbkft/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://rcavlive.akamaized.net/hls/live/704019/cancbkft/master.m3u8 (offline)
<img width="488" alt="image" src="https://user-images.githubusercontent.com/7253922/232258411-a977c406-a583-4c97-8d63-64ba2f289603.png">

**Comment by Time-Pare** [comment]
Work on VLC, Geo-Restricted to Canada.
![cbkft](https://user-images.githubusercontent.com/86069942/232264477-9b4c56fb-f5e4-411b-a6a1-96f7fb92b259.PNG)
