### ISSUE TITLE
Add: Ici Radio-Canada Télé Terre-Neuve-et-Labrador (CBAFT-DT) [CA]

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#11911]
### Channel ID

CBAFTDT.ca

### Stream URL

https://rcavlive.akamaized.net/hls/live/704014/cancbaft/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://rcavlive.akamaized.net/hls/live/704014/cancbaft/master.m3u8 (offline)
<img width="501" alt="image" src="https://user-images.githubusercontent.com/7253922/232258428-1aaa063e-26ea-4021-8189-d4bc24419268.png">

**Comment by Time-Pare** [comment]
Sorry for the duplicate links. 

Works on VLC, Geo-Restricted to Canada. 
![cbaft](https://user-images.githubusercontent.com/86069942/232330105-51313f27-15f0-4b34-8502-1f7139de893d.PNG)
