### ISSUE TITLE
List Free Iptv Brazil

### ISSUE THREAD

**Issue by Ramys** [iptv-org/iptv#1191]
https://gist.github.com/Ramys/071d842389841e7b978a2c76475c1aae

https://gist.github.com/Ramys/375032f60714e822272a4adff259a125

Please add this to the project.

Thank You!

**Comment by freearhey** [comment]
I don't know about the others, but none of the channels in this playlist work for me.

**Comment by Ramys** [comment]
Make a test with the Vlc average player, it will work normally..

**Comment by SileC** [comment]
First user It's one connection only. If you're the lucky one.
![2E301BE6-FDCA-481A-B96B-D533D333B030](https://user-images.githubusercontent.com/23043824/79411736-9f5e2280-7f71-11ea-85e2-1c01f80668e1.jpeg)

**Comment by exodiver** [comment]
Don't recommend you add those links. These are from hacked user account of paid iptv stream service and don't last more than a few days.

**Comment by rogerio957** [comment]
ola amigo Ramys venho por este meio agradecer pelo seu trabalho se dedica com gosto a esta tecnologia que eu tambem gosto tenho o aplicativo Iptv extreme para mim um dos melhores informo que o repositorio que contem 115.000 canais ilimitados a maioria funciona eu pergunto os canais Portugueses exemplo sportv1 ,cines nunca funcionaram apenas tem um problema todos os canais trava apenas 5 segundos amigo Ramys um abraço um bom domingo fique com Deus
