### ISSUE TITLE
Add: Islam Channel Urdu

### ISSUE THREAD

**Issue by pieshop6** [iptv-org/iptv#11921]
### Channel ID

IslamChannelUrdu.uk

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
Link: https://live-islamtv-urdu.simplestreamcdn.com/live7/islamtv_urdu/bitrate1.isml/live.m3u8
