### ISSUE TITLE
Add: TV 9 Gujarati

### ISSUE THREAD

**Issue by pieshop6** [iptv-org/iptv#11926]
### Channel ID

TV9Gujarati.in

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/in.m3u#L705-L706
