### ISSUE TITLE
Add: Star Kentrikis Elladas [GR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11946]
### Channel ID

StarKentrikisElladas.gr

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/LAMIASTARGR

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by iptvnikolas** [comment]
Not working
