### ISSUE TITLE
"Formatted playlists" commits are removing some additional languages

### ISSUE THREAD

**Issue by ksl1989** [iptv-org/iptv#1195]
See for example https://github.com/iptv-org/iptv/commit/38b75b4d39a3c75851475363611e72a0054c35d1#diff-f9f2eb0b79feda259986a6638de17cf4 or https://github.com/iptv-org/iptv/commit/6335fccc5356abb7d0d20482548b819483e86717#diff-f9f2eb0b79feda259986a6638de17cf4 . "Yue Chinese" and "Mandarin Chinese" are removed.

At first I thought it was removing all additional languages, but for 澳門-MACAU `tvg-language="Chinese;Yue Chinese;Portuguese"` is changed into `tvg-language="Chinese;Portuguese"`, so Portuguese and Chinese are being retained.

As a result no list for Mandarin Chinese or Cantonese (Yue Chinese) is created.

**Comment by freearhey** [comment]
Okay, I'll try to figure out what the problem is as soon as I have some free time.

**Comment by freearhey** [comment]
Fixed in: https://github.com/iptv-org/iptv/commit/4e4b9ea77ae22139699e24a66ded17f023f261cb 
Now all languages should be taken into account when generating playlists.

**Comment by ksl1989** [comment]
Thanks, I'll re-add the additional languages to the Macau list soon.
