### ISSUE TITLE
Add: Thessalia TV [GR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11950]
### Channel ID

ThessaliaTV.gr

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/thessaliatv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/thessaliatv (offline)
