### ISSUE TITLE
Add: Exodus TV [SI] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11968]
### Channel ID

ExodusTV.si

### Stream URL

https://584943999.r.worldssl.net/584943999/_definst_/vzivo/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
https://584943999.r.worldssl.net/584943999/vzivo/playlist.m3u8
