### ISSUE TITLE
Add: Iniyan TV

### ISSUE THREAD

**Issue by sunilaravinds** [iptv-org/iptv#11960]
### Channel ID

Iniyan Tv

### Stream URL

https://server1.thewebworld.in:3114/live/iniyantvlive.m3u8

### Notes

its 24 hrs christian music channel located in Chennai,Tamil Nadu, India 
m3u8 link for viewers Multiple and Adaptive Bitrate : https://server1.thewebworld.in:3114/multi_live/play.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Is it your channel ? If that's the case, thank you for proposing it to us.

**Comment by sunilaravinds** [comment]
Yes, thankyou for adding
