### ISSUE TITLE
TV Streaming

### ISSUE THREAD

**Issue by Knrd2** [iptv-org/iptv#1197]
Is it somehow possible to stream directly on the TV ? 
Thanks

**Comment by SileC** [comment]
You need iptv player in tv and send link to player.

**Comment by Knrd2** [comment]
Ok, i did that. But i cannot connect to some channels i could connect via Laptop, do you know why? Is it a difference if i add the URL or upload a file ?

**Comment by exodiver** [comment]
> Ok, i did that. But i cannot connect to some channels i could connect via Laptop, do you know why? Is it a difference if i add the URL or upload a file ?

Probably some HTTP headers in the m3u8 file to prevent the channel from being play on an app. Nothing you can do.

**Comment by SileC** [comment]
That depends on player you use. Maybe smartiptv cannot play them. Best experience I had is with GSEIPTV and Kodi which can play any link type. But you need Android tv to upload directly or any other box (Android, firestick, apple, kodi). Firestick (4K or not) is very fast and remote can control also the TV (volume, power) but you need some tinkering to add what you need (lots of programs can be sideloaded).

**Comment by rmkhalfay** [comment]
Use perfect player

**Comment by jlapitan** [comment]
apple tv also has lots of different iptv players, i am using this - https://apps.apple.com/ae/app/flex-iptv/id1182930255 which supports iphone and ipad as well

**Comment by freearhey** [comment]
By the way, we have a separate list of apps to view IPTV: https://github.com/iptv-org/awesome-iptv#apps
