### ISSUE TITLE
Replace: Cartoon Network: West TVE Feed

### ISSUE THREAD

**Issue by asteriskgithub999** [iptv-org/iptv#11973]
### Broken Link

https://tve-live-lln.warnermediacdn.com/hls/live/2023180/toonwest/slate/VIDEO_0_3564000.m3u8

### What happened to the stream?

Not loading

### Notes

I don’t have a replacement, and am in uk. Let me know if it’s blocked here

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by aarubui** [comment]
Fixed by #12101

**Comment by BellezaEmporium** [comment]
Should be fixed when PR #12101 will be merged.
