### ISSUE TITLE
Broken: Mision ELTV

### ISSUE THREAD

**Issue by giezimanuel** [iptv-org/iptv#11971]
### Broken Link

https://tunzilla.com/http://abielito.ddns.net:8080/live/misioneltv/index.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://paz.sytes.net:5443/live/streams/misioneltv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://paz.sytes.net:5443/live/streams/misioneltv.m3u8
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/7253922/232258465-6a77929d-c20b-4e79-9801-e2e51b8e45e2.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1c494c6a39b765de57e0c5794e72a86d59516fb0/streams/do.m3u#L276-L277

Broken link removed from playlist.
