### ISSUE TITLE
ALL NYC locals offline - WCBS WNBC WNYW WABC WPIX

### ISSUE THREAD

**Issue by richmNYC** [iptv-org/iptv#11998]
### Broken Link

http://v-ny.theus6tv.duckdns.org/hls/11.1/playlist.m3u8

### What happened to the stream?

Not loading

### Notes

http://v-ny.theus6tv.duckdns.org/hls/2.1/playlist.m3u8
http://v-ny.theus6tv.duckdns.org/hls/4.1/playlist.m3u8
http://v-ny.theus6tv.duckdns.org/hls/5.1/playlist.m3u8
http://v-ny.theus6tv.duckdns.org/hls/7.1/playlist.m3u8
http://v-ny.theus6tv.duckdns.org/hls/11.1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
It is known, the backend server has got a new authentication way this service does not handle yet.

**Comment by richmNYC** [comment]
Any alternatives that use another mechanism and/or server(s)?

**Comment by BellezaEmporium** [comment]
> Any alternatives that use another mechanism and/or server(s)?

Sadly no.

**Comment by richmNYC** [comment]
If there's anything I can do to help figure out, i would be glad to assist.
