### ISSUE TITLE
Add: Canal TRO + [CO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12005]
### Channel ID

CanalTROPlus.co

### Stream URL

http://181.129.186.36:8089/play/a04u/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Server has cut off.
