### ISSUE TITLE
Add: Telefe Noticias [US/AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12007]
### Channel ID

TelefeNoticias.us

### Stream URL

https://siloh-mcdn.plutotv.net/lilo/production/LATAM/Telefe/master.m3u8

### Notes

This channel is from Argentina but it's on US playlist.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
this CDN doesn't seem to lock on my part, but yep, if it's used, it may be locked quite a bit after.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f50b24bd4ba83099f0c7d22b7e25e27f850f51ae/streams/ar.m3u#L571-L572
