### ISSUE TITLE
Add: Reuters TV [US]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12022]
### Channel ID

ReutersTV.us

### Stream URL

https://reuters-reutersnow-1-us.plex.wurl.tv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://reuters-reutersnow-1-us.plex.wurl.tv/playlist.m3u8
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/7253922/232258775-614dc4d5-e96f-4ab2-b1a8-c2580c831a4f.png">
