### ISSUE TITLE
Replace: Turner Network channels (US)

### ISSUE THREAD

**Issue by SkylerDaKat** [iptv-org/iptv#12026]
### Broken Link

https://iptv-org.github.io/IPTV/index.m3u

### What happened to the stream?

Shows looped video

### Notes

[](url) https://github.com/iptv-org/database/issues/2986 
All the info on link

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by SkylerDaKat** [comment]
if there is any missing information I need to fill out, please tell me. I apologize in advance.

**Comment by SkylerDaKat** [comment]
So small update:
The issue seems to affect only (most of) west and east channels.
Channels like BBC 4 or BBC America work fine on their own.

**Comment by BellezaEmporium** [comment]
1) Please precise the impacted channels.
2) If those are concerning the "broadcastcdn.net", mostly UK channels, we are aware of it, though we do not have replacement links yet.

**Comment by SkylerDaKat** [comment]
from what I see it affects Cartoon Network and Adult Swim (US East and West channels). (there could be more but I haven't seen them yet as I only used these two mostly)

**Comment by BellezaEmporium** [comment]
> from what I see it affects Cartoon Network and Adult Swim (US East and West channels). (there could be more but I haven't seen them yet as I only used these two mostly)

I'll consider it's the whole Turner Network pack of channels.

**Comment by SkylerDaKat** [comment]
Mhm :<

**Comment by lcreed** [comment]
I can confirm there is a major issue with TCM east and west.  They play briefly before freezing

**Comment by BellezaEmporium** [comment]
Will take a check today.

**Comment by BellezaEmporium** [comment]
Could you take a look at https://tve.cdn.turner.com/live/tcmeast/stream.m3u8 please ?

**Comment by BellezaEmporium** [comment]
OK https://tve-live-ctl.warnermediacdn.com/hls/live/2023186/tcmeast/noslate/VIDEO_1_5128000.m3u8 this should work

**Comment by lcreed** [comment]
None of these TCM links are working for me.  Aren't they the same ones that were there before?

**Comment by SkylerDaKat** [comment]
> None of these TCM links are working for me. Aren't they the same ones that were there before?

They work fine for me,
But if you mean the ones from the playlist itself, they haven't updated it yet.
If you ARE using those updated links above, It may be an ISP/geolocation/VPN issue

**Comment by BellezaEmporium** [comment]
> None of these TCM links are working for me. Aren't they the same ones that were there before?

I am referring to the ones in this comment, and yes, with a VPN in the US (Florida) they work on my side.

Could be a GEO issue.

**Comment by TKList** [comment]
They don't work. They play for a few seconds only. They used to work. It is all warnermediacdn streams. CNN, Comedy Central, TBS, TCM, TNT and TruTV

**Comment by SkylerDaKat** [comment]
> They don't work. They play for a few seconds only. They used to work. It is all warnermediacdn streams. CNN, Comedy Central, TBS, TCM, TNT and TruTV

In this thread, there's an TCM link that works,
As for the rest, it's being fixed.
Comedy central, MTV, Nickelodeon (including nicktoons, teen Nick, Nick jr) and other Viacom/Paramount owned channel don't work at all and should be brought to attention if it hasn't already

**Comment by TKList** [comment]
VIDEO_1 streams give a CORS Error. Nothing works.

**Comment by SkylerDaKat** [comment]
> VIDEO_1 streams give a CORS Error. Nothing works.

Try using a VPN
Preferably one that is closest to the east or west

**Comment by aarubui** [comment]
> OK https://tve-live-ctl.warnermediacdn.com/hls/live/2023186/tcmeast/noslate/VIDEO_1_5128000.m3u8 this should work https://tve-live-ctl.warnermediacdn.com/hls/live/2023187/tcmwest/noslate/VIDEO_1_5128000.m3u8
> 
> As for Adult Swim, take a check up the "de_adultswim.m3u" playlist, those are what I have on my side.

These `tve-live-ctl` ones are fine but the [tve-live-lln.warnermediacdn.com](https://tve-live-lln.warnermediacdn.com/hls/live/2023180/toonwest/slate/VIDEO_0_3564000.m3u8) ones are returning cached and outdated versions of the playlist (consequence: looped video). And there's no consistency with the cached versions either. I'd get one from 200 seconds ago, then 3000 seconds ago, then the 200 seconds ago one again.

**Comment by aarubui** [comment]
Thanks. Changing from `tve-live-lln` to `tve-live-ctl` did the trick.

**Comment by TKList** [comment]
I'm from the USA, what is a VPN help?

**Comment by SkylerDaKat** [comment]
> I'm from the USA, what is a VPN going to help?

Well some broadcasts are different depending on your geolocation


> Thanks. Changing from `tve-live-lln` to `tve-live-ctl` did the trick.

@TKList use this method, it worked for me with cartoon network

**Comment by TKList** [comment]
Nope, didn't help.

**Comment by lcreed** [comment]
Interesting.  I normally vpn into a DFW or houston server (mullvad) and both TCM east and west used to work fine.  Now they time out/freeze after 10 seconds or so.  I switched vpn to ATL and east is working again.

Thank you!!!

**Comment by aarubui** [comment]
> VIDEO_1 streams give a CORS Error. Nothing works.

You’re probably the only one using these links with a player that checks CORS. So you’ll need to give us information regarding that for us to help.

**Comment by TKList** [comment]
What players don't check?

**Comment by lcreed** [comment]
> What players don't check?

What are you using?  It works for me in VLC and SMPlayer

**Comment by TKList** [comment]
playerjs and clappr by jsdelivr

**Comment by BellezaEmporium** [comment]
> playerjs and clappr by jsdelivr

This is the usual behaviour I guess. Anything HTTPS will do a CORS error if the wanted origins do not match the CORS Controlled domains.

**Comment by lcreed** [comment]
TCM east was working but now I'm getting 
![image](https://user-images.githubusercontent.com/734957/230747113-c062f460-8b8a-4d16-a0fb-9418360b8864.png)
(url)

**Comment by lcreed** [comment]
tcm west is still working from a vpn host based in LA

**Comment by SkylerDaKat** [comment]
I've been watching cartoon network and adult swim for a few hours now, changing the lln to ctl worked amazing on both channels, tysm <3

**Comment by RT5666** [comment]
TBS East always stops after 9 seconds or so. Loops the same programming section again and again and will not play live stream at all. TNT does the same thing.

**Comment by BellezaEmporium** [comment]
The PR is made to fix this.
