### ISSUE TITLE
Add: Rede Brasil [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12023]
### Channel ID

RedeBrasil.br

### Stream URL

https://5cf4a2c2512a2.streamlock.net/rbtv/rbtv/.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://5cf4a2c2512a2.streamlock.net/rbtv/rbtv/.m3u8
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/7253922/232258800-fc90b07c-f4b7-42d3-9f98-2d38bf454cc3.png">
