### ISSUE TITLE
AO channel TPA1 not being added to the playlists

### ISSUE THREAD

**Issue by ksl1989** [iptv-org/iptv#1204]
My PR for the Angolan channel TPA1 (https://github.com/iptv-org/iptv/commit/08dc5bfd497ec587aaba2b0f1c0c78605b8d91a3) was merged over a day ago but it's not showing on any of the playlists generated on iptv-org.github.io.

**Comment by freearhey** [comment]
This happened because the `EXTINF` tag did not contain `#` at the beginning.

https://github.com/iptv-org/iptv/blob/08dc5bfd497ec587aaba2b0f1c0c78605b8d91a3/channels/ao.m3u#L2

I have already fixed it (https://github.com/iptv-org/iptv/commit/742e3925e15db35a64511178b3b9dd27e905c27e)

**Comment by ksl1989** [comment]
Thanks, I should have noticed that.
