### ISSUE TITLE
Add: RAVE-Z TV

### ISSUE THREAD

**Issue by theraveztv** [iptv-org/iptv#12059]
### Channel ID

RAVE-Z TV

### Stream URL

https://raveztv.page.link/stream

### Notes

#EXTINF:-1 tvg-id="RAVE-Z " tvg-logo="https://i.ibb.co/Jnq9SXQ/rave-pn5w.png" group-title="Undefined",RAVE-Z TV 8K (4320p)
https://raveztv.page.link/stream

link are dynamic and actively monitored

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Thank you for proposing your channel to us.

From which country do you stream ? It'll help us place the stream to the correct place.

**Comment by theraveztv** [comment]
thanks for replies it do really means alot.

can i give a updates? because i do 3 stream and i missnamed it,
thanks :)



#EXTINF:-1 tvg-id="RAVE-ONE " tvg-logo="https://i.ibb.co/Jnq9SXQ/rave-pn5w.png" group-title="Entertainment",RAVE-ONE TV 8K (4320p)
https://raveztv.page.link/stream

**Comment by theraveztv** [comment]
thanks for replies it do really means alot.

can i give a updates? because i do 3 stream and i missnamed it,
thanks :)

#EXTINF:-1 tvg-id="RAVE-ONE " tvg-logo="https://i.ibb.co/Jnq9SXQ/rave-pn5w.png" group-title="Entertainment",RAVE-ONE TV 8K (4320p)
https://raveztv.page.link/stream

**Comment by theraveztv** [comment]
thanks for replies it do really means alot.

can i give a updates? because i do 3 stream and i missnamed it,
thanks :)

#EXTINF:-1 tvg-id="RAVE-ONE " tvg-logo="https://i.ibb.co/Jnq9SXQ/rave-pn5w.png" group-title="Entertainment",RAVE-ONE TV 8K (4320p)
https://raveztv.page.link/stream

**Comment by theraveztv** [comment]
thanks for replies it do really means alot.

can i give a updates? because i do 3 stream and i missnamed it,
thanks :)

#EXTINF:-1 tvg-id="RAVE-ONE " tvg-logo="https://i.ibb.co/Jnq9SXQ/rave-pn5w.png" group-title="Entertainment",RAVE-ONE TV 8K (4320p)
https://raveztv.page.link/stream

**Comment by theraveztv** [comment]
thanks for replies it do really means alot.

can i give a updates? because i do 3 stream and i missnamed it,
thanks :)

#EXTINF:-1 tvg-id="RAVE-ONE " tvg-logo="https://i.ibb.co/Jnq9SXQ/rave-pn5w.png" group-title="Entertainment",RAVE-ONE TV 8K (4320p)
https://raveztv.page.link/stream

**Comment by theraveztv** [comment]
thanks for replies it do really means alot.

can i give a updates? because i do 3 stream and i missnamed it,
thanks :)

#EXTINF:-1 tvg-id="RAVE-ONE " tvg-logo="https://i.ibb.co/Jnq9SXQ/rave-pn5w.png" group-title="Entertainment",RAVE-ONE TV 8K (4320p)
https://raveztv.page.link/stream

**Comment by theraveztv** [comment]
thanks for replies it do really means alot.

can i give a updates? because i do 3 stream and i missnamed it,
thanks :)

#EXTINF:-1 tvg-id="RAVE-ONE " tvg-logo="https://i.ibb.co/Jnq9SXQ/rave-pn5w.png" group-title="Entertainment",RAVE-ONE TV 8K (4320p)
https://raveztv.page.link/stream

**Comment by theraveztv** [comment]
thanks for replies it do really means alot.

can i give a updates? because i do 3 stream and i missnamed it,
thanks :)

#EXTINF:-1 tvg-id="RAVE-ONE " tvg-logo="https://i.ibb.co/Jnq9SXQ/rave-pn5w.png" group-title="Entertainment",RAVE-ONE TV 8K (4320p)
https://raveztv.page.link/stream

**Comment by theraveztv** [comment]
thanks for replies it do really means alot.

can i give a updates? because i do 3 stream and i missnamed it,
thanks :)

#EXTINF:-1 tvg-id="RAVE-ONE " tvg-logo="https://i.ibb.co/Jnq9SXQ/rave-pn5w.png" group-title="Entertainment",RAVE-ONE TV 8K (4320p)
https://raveztv.page.link/stream

**Comment by theraveztv** [comment]
thanks for replies it do really means alot.

can i give a updates? because i do 3 stream and i missnamed it,
thanks :)

#EXTINF:-1 tvg-id="RAVE-ONE " tvg-logo="https://i.ibb.co/Jnq9SXQ/rave-pn5w.png" group-title="Entertainment",RAVE-ONE TV 8K (4320p)
https://raveztv.page.link/stream

**Comment by BellezaEmporium** [comment]
You can put the 3 streams, yes.

**Comment by theraveztv** [comment]
hi,just wondering does the stream has been added to database?

**Comment by theraveztv** [comment]
hi,just wondering does the stream has been added to database?
thanks

**Comment by theraveztv** [comment]
hi,just wondering does the stream has been added to database?
thanks

**Comment by BellezaEmporium** [comment]
I think it has been added to the database yes. Next step is to add it in our playlists.

**Comment by theraveztv** [comment]
good night,so the channel was declined or what?,is there something that i can do?,is the channel rejected because DMCA or what,sorry askin because i just don't know about github thing,and just wanna provide something to watch,thanks

**Comment by theraveztv** [comment]
good night,so the channel was declined permanently or what?,is there something that i can do?,is the channel rejected because DMCA or what,sorry askin because i just don't know about github thing,and just wanna provide something to watch,thanks

**Comment by freearhey** [comment]
@theraveztv For your request to be accepted, it must contain a valid channel ID. The full list of supported channels can be found here: https://iptv-org.github.io/ 

If you can't find the channel you want in the list, please let us know through this [form](https://github.com/iptv-org/database/issues/new?assignees=&labels=channels%3Aadd&template=channels_add.yml&title=Add%3A+).
