### ISSUE TITLE
Add: 3 Plus [AL_TRING]

### ISSUE THREAD

**Issue by eurohunter** [iptv-org/iptv#12050]
### Channel ID

3Plus.al

### Stream URL

https://mfe01.tring.al/delta/106/out/u/896_3.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by arkan601** [comment]
> ### Channel ID
> 3Plus.al
> 
> ### Stream URL
> https://mfe01.tring.al/delta/106/out/u/896_3.m3u8
> 
> ### Notes
> _No response_
> 
> ### Please confirm the following
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)
