### ISSUE TITLE
Add: ABC News Albania [AL_TRING]

### ISSUE THREAD

**Issue by eurohunter** [iptv-org/iptv#12070]
### Channel ID

ABCNewsAlbania.al

### Stream URL

https://mfe01.tring.al/delta/105/out/u/650_1.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by albghost** [comment]
hello, do you have any TRING SPORTS CHANNEL?

**Comment by eurohunter** [comment]
> hello, do you have any TRING SPORTS CHANNEL?

Sorry, I could not find any Tring sports channels.

**Comment by albghost** [comment]
can you find arena sports channels or dazn italy& germany
