### ISSUE TITLE
please please please fix adult swim it is on an infinite loop: 

### ISSUE THREAD

**Issue by luffy209** [iptv-org/iptv#12088]
### Broken Link

https://tve-live-lln.warnermediacdn.com/hls/live/2023185/aswest/noslate/VIDEO_3_1928000.m3u8

### What happened to the stream?

Shows looped video

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by nelsonjesudas** [comment]
So are cartoon network, tnt, tbs, & Tru. 
I think it's the source, since I can't even get the trials on their websites to work.

**Comment by nelsonjesudas** [comment]
So are cartoon network, tnt, tbs, & Tru. 
I think it's the source, since I can't even get the trials on their websites to work.

**Comment by BellezaEmporium** [comment]
Possibly linked to #12026

**Comment by BellezaEmporium** [comment]
You may check the de_adultswim.m3u streams, as they're the ones I have right now (US VPN to Florida)
