### ISSUE TITLE
Replace: Ecuavisa.ec

### ISSUE THREAD

**Issue by jonathanguartan** [iptv-org/iptv#12084]
### Broken Link

https://livestreamcdn.net:444/Alientoenvivo/Alientoenvivo.smil/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://mdstrm.com/live-stream-playlist/603ea23f928cc5255563012c.m3u8

### Notes

No response

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Toei79** [comment]
asking for referrer

**Comment by freearhey** [comment]
https://mdstrm.com/live-stream-playlist/603ea23f928cc5255563012c.m3u8 (offline)
<img width="542" alt="image" src="https://user-images.githubusercontent.com/7253922/232258839-270f6911-9a19-48aa-bb75-12f012c97e6d.png">
