### ISSUE TITLE
Add: persiana sports

### ISSUE THREAD

**Issue by Goldiefresh** [iptv-org/iptv#12111]
### Channel ID

Persianasports.ir

### Stream URL

https://stream.live12.ir/hls2/persiana.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Is this an official stream ? Kind of weird to use sort of pirated sport streams.

**Comment by Goldiefresh** [comment]
I wasn't aware it was a pirated sports stream. Please ignore if it is.

**Comment by trancer1994** [comment]
The stream, according to the official site, persiana.live, is: 

http://51.254.225.27/hls/stream.m3u8
but it doesn't work at the moment.
