### ISSUE TITLE
Add: irib Varzesh 

### ISSUE THREAD

**Issue by Goldiefresh** [iptv-org/iptv#12112]
### Channel ID

VarzeshTV.ir

### Stream URL

https://af.ayas.ir/hls2/varzeshtv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/ir.m3u#L54-L57
