### ISSUE TITLE
Add: TVC Benin [BJ]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12118]
### Channel ID

TVCBenin.bj

### Stream URL

https://live.tvcbenin.com/BENIN/TVC.stream/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://live.tvcbenin.com/BENIN/TVC.stream/playlist.m3u8
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/7253922/232258904-9ae01877-7f37-43e2-8fab-50fbcff751e0.png">
