### ISSUE TITLE
Add: FX Life [GR]

### ISSUE THREAD

**Issue by Playe4** [iptv-org/iptv#12115]
### Channel ID

FXLife.gr

### Notes

Categories: Series
Is NSFW: False
Languages: English, Greek
Broadcast Area: Greece
Country: Greece
Website: FXChannel.gr
Owners: The Walt Disney Company
Launched: March 15, 2023

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Carlinhos027** [comment]
To request to add a new channel to the database please open a new issue here: https://github.com/iptv-org/database/issues/
