### ISSUE TITLE
Add: MyAutoDJ TV [US]

### ISSUE THREAD

**Issue by myautodj** [iptv-org/iptv#12128]
### Channel ID

MyAutoDJTV.us

### Stream URL

https://video.myautodj.com:3932/hybrid/play.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Thank you for proposing your channel to us.
