### ISSUE TITLE
Failed to render the following pins (roughly translated)

### ISSUE THREAD

**Issue by 1llqqhh** [iptv-org/iptv#12122]
### Channel ID

🇨🇳 China

### Stream URL

https://iptv-org.github.io/iptv/countries/cn.m3u

### Notes

在渲染下列pin时失败了

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
As far as the translator understood, you can't watch certain channels. Please precise which ones.
