### ISSUE TITLE
Add: Hidabroot [IL]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12134]
### Channel ID

Hidabroot.il

### Stream URL

https://cdn.cybercdn.live/HidabrootIL/Live97/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://cdn.cybercdn.live/HidabrootIL/Live97/playlist.m3u8
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/7253922/232258931-3344f564-0dc0-44fa-884e-9f0a5113434c.png">
