### ISSUE TITLE
Add: Wedding TV [IT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12139]
### Channel ID

WeddingTV.it

### Stream URL

https://stream.cp.ets-sistemi.it:1936/profservtv/profservtv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://stream.cp.ets-sistemi.it:1936/profservtv/profservtv/playlist.m3u8
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/7253922/232258969-7c5b8b2f-ea14-4433-994c-898c732fbd9f.png">
