### ISSUE TITLE
Add: Well TV [IT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12140]
### Channel ID

WellTV.it

### Stream URL

https://5f22d76e220e1.streamlock.net/canale5/canale5/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://5f22d76e220e1.streamlock.net/canale5/canale5/playlist.m3u8
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/7253922/232258977-b641d4f1-7bb8-4b17-a21f-034494f86965.png">
