### ISSUE TITLE
Add: ZeeBusiness

### ISSUE THREAD

**Issue by dhruvjgandhi** [iptv-org/iptv#12151]
### Channel ID

ZeeBusiness.in

### Stream URL

https://d8gy12azhr71i.cloudfront.net/out/v1/45be109c5b4f44319e882da947377364/index_5.m3u8

### Notes

#EXTINF:1,ZeeBusiness
https://d8gy12azhr71i.cloudfront.net/out/v1/45be109c5b4f44319e882da947377364/index_5.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://d8gy12azhr71i.cloudfront.net/out/v1/45be109c5b4f44319e882da947377364/index_5.m3u8
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/7253922/232258994-040b65e9-71b2-4e64-96e7-7d5e82750baa.png">
