### ISSUE TITLE
Add: Antenna 2 [IT]

### ISSUE THREAD

**Issue by BellezaEmporium** [iptv-org/iptv#12150]
### Channel ID

Antenna2TV.it

### Stream URL

https://58f12ffd2447a.streamlock.net/Antenna2/livestream/playlist.m3u8

### Notes

Found out while lurking on the internet.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/it.m3u#L451-L452
