### ISSUE TITLE
Replace:  Bosnian Channels

### ISSUE THREAD

**Issue by TurboPing** [iptv-org/iptv#12160]
### Broken Link

https://iptv-org.github.io/iptv/languages/bos.m3u

### What happened to the stream?

Not loading

### Notes

I get following logs from VLC:

- [ ] VLC cannot open media address 'https://bhrtstream.bhtelecom.ba/bhrtportal.m3u8'. Please refer to the error log for details.
- [ ] VLC cannot open media address 'https://balkanmedia.dynu.net/hls/tv5web.m3u8'. Please refer to the error log for details.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by benevenstanciano** [comment]
The first link is geo-blocked, so if you're not in BH or VPN to that location, you won't be able to watch.
