### ISSUE TITLE
Add: OTV

### ISSUE THREAD

**Issue by TurboPing** [iptv-org/iptv#12182]
### Channel ID

OTV.hr

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/hr.m3u#L29-L30
