### ISSUE TITLE
Add: BNTV

### ISSUE THREAD

**Issue by TurboPing** [iptv-org/iptv#12196]
### Channel ID

BNTV.ba

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/ba.m3u#L6-L7
