### ISSUE TITLE
Add: Trinidad and Tobago Television (TTT)

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#12227]
### Channel ID

TTT.tt

### Notes

Original request: iptv-org/iptv-org.github.io#1187

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by trancer1994** [comment]
Timeshift (international feed, didn't realise this until I got the URL): https://cdn005.tegotv.com/liveabr/Live_TV~TTT~TTT~Foreign/playlist_dvr_timeshift-0-7200.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9NC8xNS8yMDIzIDU6MTU6MzAgUE0maGFzaF92YWx1ZT1IVGltTG5PZGtzemdYQm5HdE9TazZnPT0mdmFsaWRtaW51dGVzPTEyMCZpZD0xODUyNTM5OTE0MA==
No timeshift, still international feed: https://cdn005.tegotv.com/liveabr/Live_TV~TTT~TTT~Foreign/playlist_dvr.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9NC8xNS8yMDIzIDU6MTU6MzAgUE0maGFzaF92YWx1ZT1IVGltTG5PZGtzemdYQm5HdE9TazZnPT0mdmFsaWRtaW51dGVzPTEyMCZpZD0xODUyNTM5OTE0MA==
Domestic stream: https://cdn005.tegotv.com/liveabr/Live_TV~TTT~TTT/playlist_dvr.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9NC8xNS8yMDIzIDU6MTU6MzAgUE0maGFzaF92YWx1ZT1IVGltTG5PZGtzemdYQm5HdE9TazZnPT0mdmFsaWRtaW51dGVzPTEyMCZpZD0xODUyNTM5OTE0MA==

**Comment by freearhey** [comment]
https://cdn005.tegotv.com/liveabr/Live_TV~TTT~TTT/playlist_dvr.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9NC8xNS8yMDIzIDU6MTU6MzAgUE0maGFzaF92YWx1ZT1IVGltTG5PZGtzemdYQm5HdE9TazZnPT0mdmFsaWRtaW51dGVzPTEyMCZpZD0xODUyNTM5OTE0MA==
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/7253922/232244076-88988a72-142b-4bcf-a52d-adf9a370133c.png">

**Comment by freearhey** [comment]
https://cdn005.tegotv.com/liveabr/Live_TV~TTT~TTT/playlist_dvr.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9NC8xNS8yMDIzIDU6MTU6MzAgUE0maGFzaF92YWx1ZT1IVGltTG5PZGtzemdYQm5HdE9TazZnPT0mdmFsaWRtaW51dGVzPTEyMCZpZD0xODUyNTM5OTE0MA== (offline)
<img width="833" alt="image" src="https://user-images.githubusercontent.com/7253922/233811607-5ae93f5e-95b7-4565-9411-c0aee1b2e16c.png">
