### ISSUE TITLE
Add: Synergy TV

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#12228]
### Channel ID

SynergyTV.tt

### Notes

Original request: iptv-org/iptv-org.github.io#1189

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
https://tegostream.com/tv?channel=259

tokenized stream
