### ISSUE TITLE
Add: Lolly Kids

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#12222]
### Channel ID

LollyKids.uk

### Notes

Original request: #5439

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
http://45.225.95.170:8000/play/a0ei/index.m3u8 LATAM
