### ISSUE TITLE
German List Connection Problems and Channel List Request

### ISSUE THREAD

**Issue by adleronur** [iptv-org/iptv#1224]
**What's wrong?**
I have never watched ZDF channel using by ott player. And most of german channels are broken.
**Country of the channel:**
german
**Channel Name:**
deu.m3u
**Broken Link:**
https://iptv-org.github.io/iptv/languages/deu.m3u
**Additional Information (optional):**
If you dont mind, you can add bellow channal from astra 19.2 satellite to that list:

10744 H | 22000 5/6(ARD Digital) | Tagesschau 24One (ARD)ARTE DeutschPhoenix
-- | -- | --
10773 H | 22000 3/4(HD+) | QVC Deutschland HDHSE 24 HDNickelodeon Deutschland HDN 24 HDAnixe HD SerieQVC Deutschland HDHSE 24 HDSES 75 (HD+ Info Card)Sophia TVGenius Plus TV
-- | -- | --
10803 H | 22000 3/4(BetaDigital) | Disney Channel Deutschland HD HSE 24 Extra HD1-2-3.TV HDDeluxe MusicQVC 2 Deutschland HD Sport 1 HD Deutschland Disney Channel Austria HDDeluxe Music HD Austria
-- | -- | --
10832 H | 22000 2/3 | RTL HD DeutschlandVox HD DeutschlandN-TV HDRTL 2 HD Deutschland
-- | -- | --
10891 H | 22000 2/3(ARD Digital) | RBB Brandenburg HDRBB Berlin HDMDR Fernsehen Sachsen HDMDR Fernsehen Sachsen-Anhalt HDMDR Fernsehen Thüringen HDHR Fernsehen HD
-- | -- | --
10964 H | 22000 2/3(SES Astra) | TLC HD DeutschlandZee One HD DeutschlandSparhandy TV 2 HDMTV HD DeutschlandChannel 21 HDQVC Style HDTLC HD AustriaMTV HD Austria
-- | -- | --
11053 H | 22000 2/3(ARD Digital) | Tagesschau 24 HDOne HD (ARD)SR Fernsehen HD
-- | -- | --
11347 V | 22000 2/3 | 3 Sat HDKiKa HD (06-21)ZDFinfo HD
-- | -- | --
11362 H | 22000 2/3(ZDF Vision) | ZDF HDZDF Neo HD
-- | -- | --
11464 H | 22000 2/3 | Sat.1 HD DeutschlandPro 7 HD DeutschlandKabel 1 HD DeutschlandKabel eins HD AustriaSixx HD DeutschlandProSieben MAXX HD DeutschlandSixx HD Austria
-- | -- | --
11494 H | 22000 2/3(ARD Digital) | Das Erste HDARTE Deutsch HDSüdwest Fernsehen Baden-Württemberg HDSudwest Fernsehen Rheinland-Pfalz HD
-- | -- | --
11553 H | 22000 2/3(Beta Digital) | Augsburg TV HDMünchen TV HDRFO HD (18-24)TV Allgäu HD (18-24)INTV HD (18-24)Lokal TV Portal HD
-- | -- | --
11582 H | 22000 2/3 | Bayerisches Fernsehen Süd HDBayerisches Fernsehen Nord HDNDR Fernsehen Niedersachsen HDNDR Fernsehen Mecklenburg-Vorpommern HDNDR Fernsehen HamburgNDR Fernsehen Schleswig-Holstein HDPhoenix HD
-- | -- | --
11612 H | 22000 5/6 | TRT TürkR1 (Russkij Perwyj)Yol TV HDPeretz InternationalDomashnij Telekanal InternationalREN TV International5 Kanal InternationalNTV MirTV Centr InternationalSTS International8 Kanal International RussiaTV Rus
-- | -- | --
12188 H | 27500 3/4(Mediengruppe RTL) | RTL DeutschlandRTL (Regional NRW 18:00-18:30)RTL (Bremen & Land Niedersachsen 18:00-18:30)RTL FS (TV Bayern Live) (Saturdays 17:45 to 18:45 CET)RTL HH SH (Hansestadt Hamburg/Schleswig Holstein 18:00-18:30)RTL 2 DeutschlandSuper RTL DeutschlandVox DeutschlandRTL NitroRTLplus DeutschlandN-TVToggo Plus
-- | -- | --

https://www.myproduksiyon.com/astra-uydusu-kanal-frekans-listesi-2018-guncel/

Thank you in advance for you help...

**Comment by SileC** [comment]
Then use a different player. I tried RTL, VOX IN GSE and IPTVSMARTERS and they work OK.

**Comment by freearhey** [comment]
Just checked this playlist via Elmedia Video Player, VLC Player and streamtest.io and everything works as usual everywhere.

As for adding new channels, it would be better to create a separate issue for that.

**Comment by adleronur** [comment]
> Then use a different player. I tried RTL, VOX IN GSE and IPTVSMARTERS and they work OK.

Hi, How did you use IPTVSMARTERS without Username ve password information? 
Can you explain how they work?

**Comment by adleronur** [comment]
I tried VLC player on pc and it works.
But LG smart tv is not worked via ss player, smart ip tv... I am getting crazy. Why LG has ZDF/VOX/Pro7/RTL, ony... Das erste HD works w/o problem :(((((

**Comment by SileC** [comment]
It's not the LG TV problem, it's as player app that is not adjusted for LG. I have channels that work ok oh GSE iPhone but not on GSE firestick4k.

**Comment by adleronur** [comment]
Can you give Username and password info for login of IPTV Smarters Player ?
