### ISSUE TITLE
afghanestan channels

### ISSUE THREAD

**Issue by amirh123123** [iptv-org/iptv#1228]
**Country of the channel:**afghanestan

**Channel Name:**

for this adress
https://www.lyngsat.com/freetv/Afghanistan.html
**Channel Language:**

**Additional Information (optional):**

**Comment by amirh123123** [comment]
language persian

**Comment by freearhey** [comment]
We already have a playlist with Afghan channels: 
https://iptv-org.github.io/iptv/countries/af.m3u

If you want us to add any specific channels, please specify their exact name.
