### ISSUE TITLE
Add: Alanwar TV

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#12282]
### Channel ID

AlanwarTV.kw

### Notes

Original request: iptv-org/iptv-org.github.io#1317

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
https://www.al-anwar.tv/

https://alanwar.tv/
http://80.online-tv.biz:25461/live/AlanwatTV/Tvliv/4.m3u8
blocked 

https://anwartv2.com/ ?

**Comment by sabah1973** [comment]
http://152.89.61.251:25461/live/Alanwartv/Sngiraq/18.m3u8
