### ISSUE TITLE
tajikistan channels

### ISSUE THREAD

**Issue by amirh123123** [iptv-org/iptv#1229]
**Country of the channel:**tajikistan

**Channel Name:**

this address
https://www.lyngsat.com/freetv/Tajikistan.html

**Channel Language:**tajik

**Additional Information (optional):**

**Comment by freearhey** [comment]
Tojikiston https://github.com/iptv-org/iptv/blob/6c9aa8e95ee4ade1be68c8686e632f17797d0052/channels/tj.m3u#L2-L3

**Comment by freearhey** [comment]
Closed in favor #1964
