### ISSUE TITLE
Add: DZRJ-DTV (RJ DigiTV)

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#12318]
### Channel ID

RJTV.ph

### Notes (optional)

Original request: iptv-org/iptv-org.github.io#1263

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
seem to only stream from https://www.facebook.com/RJDigiTV/


 https://www.facebook.com/RJDigiTV/videos/1414621629302087/
