### ISSUE TITLE
Add: One News

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#12312]
### Channel ID

OneNews.ph

### Notes (optional)

Original request: iptv-org/iptv-org.github.io#1251

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
https://www.youtube.com/@OneNewsPH/streams
not 24/7
https://www.youtube.com/channel/UCzEAC4xGrhpShopTYgBhGJA/live
