### ISSUE TITLE
Add: Light TV

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#12316]
### Channel ID

LightTV.ph

### Notes (optional)

Original request: iptv-org/iptv-org.github.io#1259

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
https://www.zoe.com.ph/

https://www.youtube.com/@NewsLight/streams
not 24/7
https://www.youtube.com/channel/UCOtXw8ibTdHZxJTLrZ9GDXw/live
