### ISSUE TITLE
Add: ITV

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#12337]
### Channel ID

ITV1.uk

### Stream URL (optional)

https://cdnuk001.broadcastcdn.net/KUK-ITV001/playlist.m3u8

### Notes (optional)

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/7253922/232261031-c5412cf5-e21e-43c6-884c-84ca4a3f0319.png">

Original request: #10493

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by DJ1999-max** [comment]
Stream is locked.

**Comment by takethis2165** [comment]
don't work for me

**Comment by freearhey** [comment]
https://cdnuk001.broadcastcdn.net/KUK-ITV001/playlist.m3u8 (Offline)
<img width="443" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/ec778cef-2843-42ea-8190-c3b9726b88f0">
