### ISSUE TITLE
Add: Trans7 [ID]

### ISSUE THREAD

**Issue by BaksoKeras** [iptv-org/iptv#12356]
### Channel ID

Trans7.id

### Stream URL (optional)

https://www.trans7.co.id/live-streaming

### Notes (optional)

The old link is broken

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/054755c94c020e348ff808e5f93578d15e3cf033/streams/id.m3u#L233-L234
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/7253922/232312623-7e727735-5a03-4145-a06f-67c1262087e5.png">
