### ISSUE TITLE
Add: AT-X

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#12352]
### Channel ID

ATX.jp

### Stream URL (optional)

https://code.vthanhtivi.pw/getlink/jptv2/107/playlist.m3u8

### Notes (optional)

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/7253922/232256517-3e75b78c-e0a5-4243-a670-ed0f29444f4b.png">

Original request: #11749

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://code.vthanhtivi.pw/getlink/jptv2/107/playlist.m3u8 (offline)
<img width="416" alt="image" src="https://user-images.githubusercontent.com/7253922/233808765-8acf7f89-e2ae-4a45-8a1b-2d0e0b59faa7.png">

**Comment by freearhey** [comment]
https://code.vthanhtivi.pw/getlink/jptv/Nxk7xMmj7dV7iq_k08p2fQ==/playlist.m3u8
<img width="788" alt="image" src="https://user-images.githubusercontent.com/7253922/233873130-adf3af4d-396d-4310-8500-0c2c415d94f3.png">

http://rip.hidari.moe/get/jptv/get.php?id=X4_3qVMPUBpZMqO_hX4vBw==
<img width="787" alt="image" src="https://user-images.githubusercontent.com/7253922/233873149-094f5609-f165-43a3-933b-83a79ce081e5.png">

**Comment by conanjimmy** [comment]
How do I use this link？？？ @freearhey

**Comment by freearhey** [comment]
All the links are dead and have already been removed from the playlist.
