### ISSUE TITLE
Add: CBC Vancouver (CBUT-DT) [CA]

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#12364]
### Channel ID

CBUTDT.ca

### Stream URL (optional)

https://cbcrclinear-tor.akamaized.net/hls/live/2042768/CBCRCLINEAR_TOR_14/master5.m3u8

### Notes (optional)

Official link from CBC Gem
Reported offline on Streamtest but work on VLC, might be Geo-Restricted to Canada.
![cbut](https://user-images.githubusercontent.com/86069942/232346898-e400b1d3-1f2a-4efe-83d7-a7672dafbf00.PNG)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by zzo38** [comment]
This stream (and the other CBC television streams) no longer work as far as I can tell, although they worked a month ago.
