### ISSUE TITLE
Android application

### ISSUE THREAD

**Issue by anas-darai** [iptv-org/iptv#1237]
Hello,
I programmed the Android app to run iptv wonderfully and amazingly, I focused on making the list view look beautiful and easy to use.
I have added to the application several features such as quality change, search, export, and even modification of channels.
I hope you like the application, thank you for your services
![KgTv Player_Screenshot_2020 04 21_17 24 47](https://user-images.githubusercontent.com/51852391/79897899-e2991500-83f9-11ea-8bd0-45bd0d3b5c87.jpg)
![KgTv Player_Screenshot_2020 04 21_17 26 07](https://user-images.githubusercontent.com/51852391/79897905-e3ca4200-83f9-11ea-8c01-8e50b7e0e703.jpg)
![KgTv Player_Screenshot_2020 04 21_17 43 53](https://user-images.githubusercontent.com/51852391/79897907-e4fb6f00-83f9-11ea-9901-d2dadba1c37e.jpg)
![KgTv Player_Screenshot_2020 04 21_17 58 59](https://user-images.githubusercontent.com/51852391/79897909-e5940580-83f9-11ea-8c31-1fb44c68be21.jpg)

The application is in Google Play
https://play.google.com/store/apps/details?id=tk.kgtv

**Comment by freearhey** [comment]
We have a separate repository with a list of IPTV players: https://github.com/iptv-org/awesome-iptv#apps and you can add a link to your application to it.
