### ISSUE TITLE
Add: Apsara TV11 [KH]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12387]
### Channel ID

ApsaraTV11.kh

### Stream URL (optional)

http://203.176.130.123:8989/live/apsaratv_480k.stream/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://203.176.130.123:8989/live/apsaratv_480k.stream/playlist.m3u8
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/7253922/232532517-1cd1d175-fcdf-4519-b625-ba9b0dfe3a9d.png">
