### ISSUE TITLE
Itv1 stream broken

### ISSUE THREAD

**Issue by MrMussa** [iptv-org/iptv#12389]
### Broken Link

https://expereiencersinternational.github.io/tvsetup/config

### What happened to the stream?

Not loading

### Notes (optional)

Itv1 does not need to be replaced, it needs to just be rebooted constantly every few days, weeks even.

![Screenshot_20230418_000845_IPTV Player](https://user-images.githubusercontent.com/129394688/232614560-2e8d09e9-0a15-4492-b6ad-60db85e781e4.jpg)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Couldn't find specified link in the repo: https://github.com/search?q=repo%3Aiptv-org%2Fiptv+https%3A%2F%2Fexpereiencersinternational.github.io%2Ftvsetup%2Fconfig&type=code

**Comment by MrMussa** [comment]
Hello. It is: https://expereiencersinternational.github.io/tvsetup/config.

I hope this helps. Itv1 and several other ITV channels, except STV, do not
work, even with a vpn set to the UK; because for the channels to work, they
need to have the VPN on.

Without it, the channels do not work.

Regards.

Mussa

**Comment by MrMussa** [comment]
Links for stations that do not work in the m3u8 stream are:

KUK-ITV1
KUK-FOUR
KUK-FIVE
KUK-ITV1+1
KUK-CITV
KUK-ITV2
KUK-BBC NEWS

These are some of the channels that do not work at the moment. If you know
someone who would fix this, then that would be great.

I am aware of what you are able to do, hence I am not writing this out of
conjecture.




Mussa
