### ISSUE TITLE
Add: ETV [TH]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12381]
### Channel ID

ETV.th

### Stream URL (optional)

http://150.95.66.20:1935/live/livestream/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://150.95.66.20:1935/live/livestream/playlist.m3u8
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/7253922/232476028-1a745b7c-6a2e-47eb-8f33-4e01d355f811.png">
