### ISSUE TITLE
Add: CTV 9 [KH]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12382]
### Channel ID

CTV9.kh

### Stream URL (optional)

http://203.176.130.123:8989/live/ctv9hd.stream/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://203.176.130.123:8989/live/ctv9hd.stream/playlist.m3u8
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/7253922/232476354-6b47a18c-02d7-4fed-bbec-8d2d89600c67.png">
