### ISSUE TITLE
Broken: Urbancrist TV #10030

### ISSUE THREAD

**Issue by giezimanuel** [iptv-org/iptv#12388]
### Broken Link

https://5790d294af2dc.streamlock.net/8160/8160/chunklist_w841352619.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

https://paz.sytes.net:5443/live/streams/urbancristv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Couldn't find specified link in the repo.
