### ISSUE TITLE
Add: Afrique Media [CM]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12386]
### Channel ID

AfriqueMedia.cm

### Stream URL (optional)

https://cloud.odysee.live/content/fe06b3cdc9412e359368b2455b6ea5e93856e382/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://cloud.odysee.live/content/fe06b3cdc9412e359368b2455b6ea5e93856e382/master.m3u8 (offline)
<img width="675" alt="image" src="https://user-images.githubusercontent.com/7253922/232531400-aa7fba3d-bb4d-4c24-82ac-5d11f07f6796.png">

**Comment by Sphinxroot** [comment]
https://www.youtube.com/channel/UCOBMhI7TtRLTAGpcTjNvYCw/live

**Comment by azgaresncf** [comment]
https://ythls.onrender.com/channel/UCOBMhI7TtRLTAGpcTjNvYCw.m3u8
