### ISSUE TITLE
Add: Hang Meas HDTV [KH]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12383]
### Channel ID

HangMeasHDTV.kh

### Stream URL (optional)

http://167.99.72.244:1935/hm_hdtv/_definst_/smil:HMHDTV.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://167.99.72.244:1935/hm_hdtv/_definst_/smil:HMHDTV.smil/playlist.m3u8
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/7253922/232476622-55ef6532-256a-40b9-af63-61d6826dcc80.png">
