### ISSUE TITLE
Add: Prva Srpska TV [RS]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12399]
### Channel ID

PrvaSrpskaTV.rs

### Stream URL (optional)

http://14.202.204.202:8000/play/a00i/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://14.202.204.202:8000/play/a00i/index.m3u8
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/7253922/233096549-7d382548-971c-4166-8bf0-b068c0ff7f8e.png">
