### ISSUE TITLE
Add: HRT 1 [HR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12398]
### Channel ID

HRT1.hr

### Stream URL (optional)

https://webtvstream.bhtelecom.ba/hls9/hrt1_1200.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://webtvstream.bhtelecom.ba/hls9/hrt1_1200.m3u8
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/7253922/233096056-49be69b1-a7bb-4cdd-b8ec-6141c2c6f911.png">
