### ISSUE TITLE
Broken:  TCM channel(s) on IPTV language.eng Playlist

### ISSUE THREAD

**Issue by GithubDaveW** [iptv-org/iptv#12390]
### Broken Link

https://tve-live-lln.warnermediacdn.com/hls/live/2023187/tcmwest/noslate/VIDEO_1_5128000.m3u8

### What happened to the stream?

Shows looped video

### Notes (optional)

The loop begins 5 to 30 secs after the channel opens and repeats the same 5 to 30 sec video repeatedly. 
I am not confident if the specific channel playlist link that I gave above is correct (or how to access it?).  If it helps, this "TCM West" channel is from the Playlist:  https://iptv-org.github.io/iptv/languages/eng.m3u (under the category of "Classic;Movies" in the Tivimate Premium Player).   I am having the same looping problem with TCM Channel on two different Android TV boxes.  Finally, note that TCM East is the same channel as TCM West (but is broadcast 3 hours earlier), and is having the same looping problem.  The broken link for TCM East is exactly the same as the one provided for TCM West above, except that the segment "/tcmwest/" reads "/tcmeast/" in the channel link.  However, I can send a different Broken Link request for TCM East - if you desire?   A gracious TY for any help that you can provide (and for all that you do)! 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Couldn't find specified link in the repo: https://github.com/search?q=repo%3Aiptv-org%2Fiptv+https%3A%2F%2Ftve-live-lln.warnermediacdn.com%2Fhls%2Flive%2F2023187%2Ftcmwest%2Fnoslate%2FVIDEO_1_5128000.m3u8&type=code

**Comment by GithubDaveW** [comment]
Hi Clips, TY for responding.  Please forgive my ignorance, but I do not know how or where I would apply the suggestion that you made. I have an IPTV player called Tivimate (Premium).  To get the GitHub (English) IPTV channels that I have, I inserted this one link in my Tivimate Player;  https://iptv-org.github.io/iptv/languages/eng.m3u This one link provides me with (or delivers) 1,816 (English Language) IPTV channels to my IPTV Player (Tivimate).    My player does not show me (or give me access to) the individual channel links when I select an individual channel.  To acquire the broken link address for the TCM channel that I placed on the GitHub website (https://tve-live-lln.warnermediacdn.com/hls/live/2023187/tcmwest/noslate/VIDEO_1_5128000.m3u8 ) - I had to open the TCM West channel on an external player (MX Player), and then look in the detailed video information properties on the MX Player to acquire this link.   That is to say, my IPTV Player (Tivimate) does not give me any access to individual channel links (to even see them, let alone change them).  I can read this TCM individual channel link from the external (MX) Player, but it provides no facility for me to change the channel link (or make the modification that you suggested).   Also, even if I could make this change in the external (MX) channel player, this would not change the channel link that my IPTV Player (Tivimate) tries to connect to every time I select the TCM channel on my IPTV Player.   Therefore, (repeating my first paragraph) I have no idea how or where I could make the change that you suggested.   Do you have any further ideas, instructions or suggestions? A final note:  I am wondering if it might be possible for GitHub to make the change that you suggested – for the TCM channels – when the individual channel links are downloaded as part of multi-channel packages?.  If so, their making this one change could possibly fix this TCM channel(s) looping problem for all users.  Just a thought.     In any case, many thanks for your responding, and TY in advance for any further help or suggestions that you may provide. Dave W.   Sent from Mail for Windows From: clips519Sent: April 17, 2023 6:42 PMTo: iptv-org/iptvCc: GithubDaveW; AuthorSubject: Re: [iptv-org/iptv] Broken: TCM channel(s) on IPTV language.eng Playlist (Issue #12390) some one had a thread on this you just change the lln to ctlhttps://tve-live-ctl.warnermediacdn.com/hls/live/2023187/tcmwest/noslate/VIDEO_1_5128000.m3u8that works for me no loop—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by clips519** [comment]
I use tivimate to sounds like you use the link to it I do it with m3u8 file so I can customize what channels I want and edit if needed so ya u might have to wait till they update it easy change  you don't know how to use note pad to do it?

**Comment by GithubDaveW** [comment]
Hi Clips, It sounds like we have similar setups.  I “customize” the channels that I want (about 80) from the entire package (of about 1816 english channels) by placing the ones that I like in the “Favorites” category, but other than that I don’t know how to customize the channels that I want (or to edit them).   I don’t know how to use Notepad to make changes or edit (and I didn’t even know it was possible).   My Tivimate is on an Android Box (or actually, on 2 different Android boxes), but (pardon my ignorance) but I had the impression that Notepad was (only) a Windows program? Can you either explain the customizing or editing process please, or send me a link to a webpage with the instructions Clips? And, do you think it will fix the problem when Github does an update?, and how long do you expect it will take until they do such an update?   Thanks again Clips,Dave. Sent from Mail for Windows From: clips519Sent: April 17, 2023 8:15 PMTo: iptv-org/iptvCc: GithubDaveW; AuthorSubject: Re: [iptv-org/iptv] Broken: TCM channel(s) on IPTV language.eng Playlist (Issue #12390) I use tivimate to sounds like you use the link to it I do it with m3u8 file so I can customize what channels I want and edit if needed so ya u might have to wait till they update it easy change you don't know how to use note pad to do it?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by GithubDaveW** [comment]
Freeaerhey,  Thank-you for responding.  I am sorry, but due to my limitations of understanding about how all of this works, I am not sure what your message meant.  If you "could not find the link that I specified in the repo", it may be because I did not send you the right broken link.   It was a struggle for me to send any specific channel link (as I don't know where to find them), so I sent the only channel link that I could find - hoping that it was what you needed.  However, I assure you that the TCM West channel is part of the English language github Playlist package, and that it is looping.   If I understand correctly, you "closed this as not planned"  (at the end of your previous communication), but I don't know what that means either.  In any case, I am still having the same problem.  Is there any further info that I could send you to help rectify this problem?   If yes - could you also please tell me where to obtain the info that you need (if it isn't obvious)?  TYVM in advance for any reply(s).

**Comment by GithubDaveW** [comment]
Dear Freeaerhey,  Thank-you for responding.  I am sorry, but due to my limitations of understanding about how all of this works, I am not sure what your message meant.  If you "could not find the link that I specified in the repo", it may be because I did not send you the right broken link.   It was a struggle for me to send any specific channel link (as I don't know where to find them), so I sent the only channel link that I could find - hoping that it was what you needed.  However, I assure you that the TCM West channel is part of the English language github Playlist package, and that it is looping.   If I understand correctly, you "closed this as not planned"  (at the end of your previous communication), but I don't know what that means either.  In any case, I am still having the same problem.  Is there any further info that I could send you to help rectify this problem?   If yes - could you also please tell me where to obtain the info that you need (if it isn't obvious)?  TYVM in advance for any reply(s). Sent from Mail for Windows From: Aleksandr StatciukSent: April 17, 2023 7:37 PMTo: iptv-org/iptvCc: GithubDaveW; AuthorSubject: Re: [iptv-org/iptv] Broken: TCM channel(s) on IPTV language.eng Playlist (Issue #12390) Closed #12390 as not planned.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by clips519** [comment]
no clue when they update stuff and same with the android boxes 2 of em weird lol  but ya you download the m3u8 from here say usa one then you  open it with note pad on computer  then u will see all the channels info u can  remove what u dont want  even change the logos  and the epg codes if its wrong then when your all done  doing w.e it is u need to do  i use  snapdrop to send the m3u8 to my android box then add it to the playlist  pretty easy to do wish i could show ya some how  if you got discord or something let me know
