### ISSUE TITLE
Add: TV Jūrmala [LV]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/iptv#12405]
### Channel ID

TVJurmala.lv

### Stream URL (optional)

https://air.star.lv/TV_Jurmala_multistream/tracks-v1a1/mono.m3u8

### Notes (optional)

Seen in https://jurmala.tv/tiesraide/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
https://air.star.lv/TV_Jurmala_multistream/index.m3u8
