### ISSUE TITLE
Broken:  TCM East Channel

### ISSUE THREAD

**Issue by GithubDaveW** [iptv-org/iptv#12409]
### Broken Link

https://tve-live-lln.warnermediacdn.com/hls/live/2023186/tcmeast/noslate/VIDEO_1_5128000.m3u8

### What happened to the stream?

Shows looped video

### Notes (optional)

This (TCM East) channel is one of the channels in the Github IPTV "languanges/eng.m3u" playlist.  One member suggested that if the "lln" in the broken channel link (shown above) is simply changed to "ctl" , this will stop the looping.   By whatever means, can someone please address and stop this looping on this TCM channel?  (Note that the same looping problem is occurring on the TCM West channel - fixable by the same minor change in the channel link, where "lln" is changed to "ctl").  Many thanks for any initiative taken.   

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Broken link removed from playlists.
