### ISSUE TITLE
Add: Shemaroo Marathi Bana (IN)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#12406]
### Channel ID

ShemarooMarathiBana.in

### Stream URL (optional)

https://livetv-channels.b-cdn.net/8042/chunklist0.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://livetv-channels.b-cdn.net/8042/chunklist0.m3u8
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/7253922/233164687-da3dbde3-d09a-4d0a-9c9f-8a5158e10967.png">
