### ISSUE TITLE
Broken: VTV Belarus

### ISSUE THREAD

**Issue by DzuyCuong** [iptv-org/iptv#12449]
### Broken Link

http://178.124.179.122:8088/VTV/index.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by DzuyCuong** [comment]
http://178.124.179.122:8088/VTV/index.m3u8

**Comment by BellezaEmporium** [comment]
Works for me.

**Comment by Carlinhos027** [comment]
> Works for me.
> 
> ![image](https://user-images.githubusercontent.com/30985701/233776928-be89c1aa-2418-47b5-8ca7-5c1f4346c8e1.png)

Also works for me.

**Comment by DJ1999-max** [comment]
Look like channel is freezing.

**Comment by BellezaEmporium** [comment]
in case the IP is changing : http://radio.tvs.by:8088/VTV/index.m3u8
