### ISSUE TITLE
Romanian m3u update channels 

### ISSUE THREAD

**Issue by AndreiB85** [iptv-org/iptv#1244]
**Country of the channel:**
Romanian 

**Channel Name:**
Acasă Tv
Prima Tv
B1 Tv
Antena 1
Andrena 2
Antena star 

**Channel Language:**

**Additional Information (optional):**

**Comment by AndreiB85** [comment]
https://iptv-org.github.io/iptv/languages/ron.m3u
Hi, 

I want to thank you this website for the amazing m3u iptv, all channels working, and I am so pleased.
But can be possible, please an update with the channels above? That will be Amazing, in this away it will be all the important CHANNEL in Romania.
Thank you again....

**Comment by freearhey** [comment]
Closed in favor #1957
