### ISSUE TITLE
Broken: 

### ISSUE THREAD

**Issue by MrMussa** [iptv-org/iptv#12444]
### Broken Link

https://expereiencersinternational.github.io/tvsetup/config

### What happened to the stream?

Not loading

### Notes (optional)

Hello.

I have opened a new issue at GitHub. I hope it will be resolved soon.

Channels not showing from the UK as at 07:25 UTC include, but are not
limited to:

KUK-ITV1
KUK-FOUR
KUK-FIVE
KUK-ITV1+1
KUK-CITV
KUK-ITV2
KUK-BBCNEWS
KUK-YESTERDAY
KUK-ITV3
KUK-ITV4
KUK-SKYNEWS
KUK-STV
KUK-STV+1
KUK-CBEEBIES
KUK-CITV
 
Mussa

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by MrMussa** [comment]
Additional channels:

KUK-BBC003
KUK-BBC004

**Comment by MrMussa** [comment]
Additional channels:

KUK-CBBC

**Comment by MrMussa** [comment]
Hello.

What should I use? Who do I contact, as well?

**Comment by MrMussa** [comment]
You told us expressly that should we encounter the same problem, we should
open a new issue as it is already closed. Please assist.

Regards.

Mussa

**Comment by ExperiencersInternational** [comment]
In my report, I simply just used the broadcastcdn links replacing the text after KUK- with XXXXX to signify that it's a problem with the service

**Comment by MrMussa** [comment]
Ok, say if I have a problem with some of the services, I have to write:
'KUK-FOURXXXXXX'. Is that it? Feedback would be appreciated.


Mussa0

**Comment by ExperiencersInternational** [comment]
Don't include the FOUR part, not needed
