### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by MrMussa** [iptv-org/iptv#12448]
### Broken Link

https://expereiencersinternational.github.io/tvsetup/config

### What happened to the stream?

Not loading

### Notes (optional)

https://experiencersinternational.github.io/tvsetup/config.m3u

Hello.

Channels not showing from the UK as at 07:55 UTC include, but are not
limited to:

KUK-ITV1
KUK-FOUR
KUK-FIVE
KUK-ITV1+1
KUK-CITV
KUK-ITV2
KUK-BBCNEWS
KUK-YESTERDAY
KUK-ITV3
KUK-ITV4
KUK-SKYNEWS

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by MrMussa** [comment]
Guys, this is not a duplicate. The channels do not work. Please fix.

**Comment by BellezaEmporium** [comment]
Wrong repository.

**Comment by MrMussa** [comment]
What do you mean?

**Comment by BellezaEmporium** [comment]
This is @iptv-org/iptv. The repository you are targeting is not endorsed by us.

**Comment by MrMussa** [comment]
Ok, I get it now. If I have any questions, who do I address it to? And what
is the right repository to address this issue?

**Comment by BellezaEmporium** [comment]
Since you are targeting @ExperiencersInternational, better ask through the repositories that are maintained by this user directly.

**Comment by ExperiencersInternational** [comment]
@BellezaEmporium to be fair, I did add whether there are related issues here to my broken channel reports, since we're more likely to get a solution here

![Screenshot_2023-04-22-15-58-42-990_com microsoft emmx](https://user-images.githubusercontent.com/56035537/233792015-5cbfc471-c2d4-43ca-a9d9-a389399780fb.jpg)

The main problem is just linking my main m3u link, it doesn't exactly tell someone which channels do / don't work, since you're handing someone a list of 135 channels or so, not knowing which ones are actually broken.

**Comment by BellezaEmporium** [comment]
> @BellezaEmporium to be fair, I did add whether there are related issues here to my broken channel reports, since we're more likely to get a solution here
> 
> ![Screenshot_2023-04-22-15-58-42-990_com microsoft emmx](https://user-images.githubusercontent.com/56035537/233792015-5cbfc471-c2d4-43ca-a9d9-a389399780fb.jpg)
> 
> The main problem is just linking my main m3u link, it doesn't exactly tell someone which channels do / don't work, since you're handing someone a list of 135 channels or so, not knowing which ones are actually broken.

Fair enough. If someone had an issue here then indeed it is relevant to check out. 
Giving out the whole repository as an "broken stream" when it is not referring to ours is something else.
