### ISSUE TITLE
Broken: STV / STV+1

### ISSUE THREAD

**Issue by ExperiencersInternational** [iptv-org/iptv#12446]
### Broken Link

https://csm-e-stv.tls1.yospace.com/csm/live/139900483.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

+1 link: https://csm-e-stv.tls1.yospace.com/csm/live/181023311.m3u8

Channel no longer loads when trying to play it, and navigating to the link shows a content not found error 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by trancer1994** [comment]
STV (not sure if there are two different streams for east and west, or if there is just one): https://csm-e-stv-eb.tls1.yospace.com/csm/live/139900483.m3u8?yo.l=true&yo.ls=2,3,4,5,6&yo.p=3&ref=a1c9d4c18ab942e779c3b0fb86ebf4fdbcf81cad3cfc56b066c275621098fc84&s=web-stv1-west&yo.so=0&yo.po=2&yo.pm=true&ru=https%3A%2F%2Fplayer.stv.tv%2Flive%2F
STV +1: https://csm-e-ces1aeuw1live102-0ad3dd531b3c30bf5.tls1.yospace.com/csm/live/181023311.m3u8?yo.l=true&yo.ls=2,3,4,5,6&yo.p=3&ref=a1c9d4c18ab942e779c3b0fb86ebf4fdbcf81cad3cfc56b066c275621098fc84&s=web-stv-plus-1&yo.so=0&yo.po=2&yo.pm=true&ru=https%3A%2F%2Fplayer.stv.tv%2Flive%2Fstv-plus-1&yo.oh=Y3NtLWUtc3R2LWViLnRsczEueW9zcGFjZS5jb20=

Notes: You may be able to get more accurate links than me. Also the links I pasted you seem to be for STV West. Not sure about STV East, or if there even is one.

**Comment by ExperiencersInternational** [comment]
I honestly don't know much about STV regions, but the priority is getting it restored. I'll fix it on my repository, but we'll have to wait and see when they get implemented here.

**Comment by BellezaEmporium** [comment]
> STV (not sure if there are two different streams for east and west, or if there is just one): https://csm-e-stv-eb.tls1.yospace.com/csm/live/139900483.m3u8?yo.l=true&yo.ls=2,3,4,5,6&yo.p=3&ref=a1c9d4c18ab942e779c3b0fb86ebf4fdbcf81cad3cfc56b066c275621098fc84&s=web-stv1-west&yo.so=0&yo.po=2&yo.pm=true&ru=https%3A%2F%2Fplayer.stv.tv%2Flive%2F STV +1: https://csm-e-ces1aeuw1live102-0ad3dd531b3c30bf5.tls1.yospace.com/csm/live/181023311.m3u8?yo.l=true&yo.ls=2,3,4,5,6&yo.p=3&ref=a1c9d4c18ab942e779c3b0fb86ebf4fdbcf81cad3cfc56b066c275621098fc84&s=web-stv-plus-1&yo.so=0&yo.po=2&yo.pm=true&ru=https%3A%2F%2Fplayer.stv.tv%2Flive%2Fstv-plus-1&yo.oh=Y3NtLWUtc3R2LWViLnRsczEueW9zcGFjZS5jb20=
> 
> Notes: You may be able to get more accurate links than me. Also the links I pasted you seem to be for STV West. Not sure about STV East, or if there even is one.

Just shortening it to https://csm-e-stv-eb.tls1.yospace.com/csm/live/181023311.m3u8?yo.l=true&yo.ls=2,3,4,5,6&yo.p=3  / https://csm-e-stv-eb.tls1.yospace.com/csm/live/139900483.m3u8?yo.l=true&yo.ls=2,3,4,5,6&yo.p=3 

works as good as having long links

**Comment by Delitants** [comment]
Anyone have a fresh link?
