### ISSUE TITLE
M3u Adult 

### ISSUE THREAD

**Issue by AndreiB85** [iptv-org/iptv#1245]
**Country of the channel:**
Gay

**Channel Name:**
Adult 

**Channel Language:**

**Additional Information (optional):**
Some m3u link's for gay adult channels if is possible. 
Thank you.

**Comment by freearhey** [comment]
Could you clarify the channel names?

**Comment by AndreiB85** [comment]
https://www.gotgayporn.com/videos/6336/i-love-it-rough/?utm_source=PBWeb&utm_medium=PBWeb&utm_campaign=PBWeb

https://m.boyfriendtv.com/videos/454372/casting-couch-392---andy-star-marcos-oliveira/?utm_source=awn&utm_medium=tgp&utm_campaign=cpc

https://www.pornhub.com/view_video.php?viewkey=ph5e7ec99a1a5d7&utm_source=PBWeb&utm_medium=PT&utm_campaign=PBWeb

Any will be fine... 

Thank

**Comment by freearhey** [comment]
Sorry, but we only collect links to IPTV channels in this repository, not to individual videos.
