### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by MrMussa** [iptv-org/iptv#12450]
### Broken Link

https://expereiencersinternational.github.io/tvsetup/config

### What happened to the stream?

Not loading

### Notes (optional)

Itv 1 still not working. Please assist.
![Screenshot_20230422_135656_IPTV Player](https://user-images.githubusercontent.com/129394688/233780120-d1375566-e76c-4f0c-a5e2-bb2f9af4bf26.jpg)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by ExperiencersInternational** [comment]
@MrMussa, using my config.m3u link is literally not going to help

I'm filing a separate more descriptive post.

**Comment by ExperiencersInternational** [comment]
https://github.com/iptv-org/iptv/issues/12457#issue-1679519212

Hopefully more descriptive!
