### ISSUE TITLE
Add: ITV1 +1 [UK]

### ISSUE THREAD

**Issue by ExperiencersInternational** [iptv-org/iptv#12459]
### Channel ID

ITV1Plus1.uk

### Stream URL (optional)

https://cdnuk001.broadcastcdn.net/KUK-ITVPLUS1/tracks-v1a1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by DJ1999-max** [comment]
403 Unauthorized

**Comment by ExperiencersInternational** [comment]
@DJ1999-max it is geo restricted

**Comment by freearhey** [comment]
https://cdnuk001.broadcastcdn.net/KUK-ITVPLUS1/tracks-v1a1/playlist.m3u8
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/7253922/233786281-d197c021-d875-47d4-8c0f-ae6e0a5b1ff4.png">
