### ISSUE TITLE
fluxus iptv

### ISSUE THREAD

**Issue by amirh123123** [iptv-org/iptv#1247]
**Country of the channel:**many countries

**Channel Name:**

fluxus playlist in this address
https://m3uplaylist.download/free-iptv-m3u-playlists
**Channel Language
many languages

**Additional Information (optional):**

**Comment by freearhey** [comment]
If you have working links to channels which are not yet in the playlists, feel free to add them yourself. If you don't know how to do it, here's a guide: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md

**Comment by SimplyXH** [comment]
It says error 403 or something and i cant open the pastebin links for the iptv channels.
