### ISSUE TITLE
Mandarin and Cantonese playlists not displayed on README

### ISSUE THREAD

**Issue by ksl1989** [iptv-org/iptv#1249]
`https://iptv-org.github.io/iptv/languages/yue.m3u` & `https://iptv-org.github.io/iptv/languages/cmn.m3u` exist but can't be found on this repo's README file.

(I'm creating an issue because I think this is scripted, otherwise I'd just make a PR.)

**Comment by freearhey** [comment]
Thank you again for bringing this to my attention.

I hope this time I was able to solve this problem completely.
