### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by marvelap** [iptv-org/iptv#1250]
Thank you very much for the contribution of the Colombian channels

**Comment by marvelap** [comment]
Thank you very much for the contribution of the Colombian channels

**Comment by unikpc** [comment]
i usually buy iptv channels online but guy service is great, please try and organise the channels as groups. by viewing by each country 
because i tried followed it the way it was design but no avail.
you tried my friend keep it up. how i wish i could.

**Comment by SileC** [comment]
The use the category link. https://iptv-org.github.io/iptv/index.category.m3u (grouped by category)

**Comment by freearhey** [comment]
@unikpc If you have any problems with using playlists it is better to create a separate issue for this and describe your problem in detail there.

@marvelap You're welcome!

**Comment by marvelap** [comment]
Thanks to you for all the collaboration and lists, it is a good contribution
