### ISSUE TITLE
Add: Komala TV [SE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12513]
### Channel ID

KomalaTV.se

### Stream URL (optional)

https://live.tvkomala.com/live/komala/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/se.m3u#L12-L13
