### ISSUE TITLE
Add: Foursquare TV [NG]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12520]
### Channel ID

FoursquareTV.ng

### Stream URL (optional)

https://webstreaming-3.viewmedia.tv/web_033/Stream/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by azgaresncf** [comment]
![image](https://user-images.githubusercontent.com/50982832/234199114-a03a36dc-8009-4f1e-852e-658c6f900e27.png)
Not geo-blocked, 576p
