### ISSUE TITLE
Add: KXXV-DT1

### ISSUE THREAD

**Issue by bugdaboss** [iptv-org/iptv#12533]
### Channel ID

KXXVDT1.us

### Stream URL (optional)

https://content-ause1-up-1.uplynk.com/channel/9d4e02c9c3544c269d32e6b316792c8f/d.m3u8?v=2&ad=live&m.sound=normal&pos=midroll&expand=ad_live&m.sound=normal&m.playback=click&ad.sz=1x1000&ad.cust_params=fname=live2&categories=&refdomain=wwitv.com&iframed=1&pxconfig=web-live&bidders=publica&player_width=1280&player_height=720&ip=[Insert_IP]&ua=[Insert_UA]&ad.url=https://wwitv.com/&pbs=2e8c496351374cfeb8369c6e6be2c277

### Notes (optional)

https://streamtest.in/logs/https-content-ause1-up-1-uplynk-com-channel-9d4e02c9c3544c269d32e6b316792c8f-d-m3u8-v-2-ad-live-m-sound-normal-pos-midroll-exp

https://streamtest.in/logs/https-content-ause1-up-1-uplynk-com-channel-9d4e02c9c3544c269d32e6b316792c8f-d-m3u8-v-2-ad-live-m-sound-normal-pos-midroll-exp-6054b306-a880-459b-b45e-b5c442864803

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://content-ause1-up-1.uplynk.com/channel/9d4e02c9c3544c269d32e6b316792c8f/d.m3u8?v=2&ad=live&m.sound=normal&pos=midroll&expand=ad_live&m.sound=normal&m.playback=click&ad.sz=1x1000&ad.cust_params=fname=live2&categories=&refdomain=wwitv.com&iframed=1&pxconfig=web-live&bidders=publica&player_width=1280&player_height=720&ip=[Insert_IP]&ua=[Insert_UA]&ad.url=https://wwitv.com/&pbs=2e8c496351374cfeb8369c6e6be2c277 (offline)
<img width="845" alt="image" src="https://user-images.githubusercontent.com/7253922/234276573-12765980-9f49-4c76-95c7-9dd9f1fa3a8b.png">

**Comment by BellezaEmporium** [comment]
https://content.uplynk.com/channel/9d4e02c9c3544c269d32e6b316792c8f.m3u8

**Comment by bugdaboss** [comment]
this is not 24/7 btw, im pretty sure it says "we will be back shortly" in between the programs that they do

**Comment by BellezaEmporium** [comment]
> this is not 24/7 btw, im pretty sure it says "we will be back shortly" in between the programs that they do

Indeed, it is news only for this one.
