### ISSUE TITLE
Add: Boomerang France [FR]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/iptv#12559]
### Channel ID

BoomerangFrance.fr

### Stream URL (optional)

http://51.81.185.2/BOOMERANG/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by SMM2LevelsIn30Seconds** [comment]
that url, plus the whole site doesn't work, dude

**Comment by BellezaEmporium** [comment]
> that url, plus the whole site doesn't work, dude

Necro'ing a 3-year post. Of course.
