### ISSUE TITLE
Add: Arena Sport Premium 2

### ISSUE THREAD

**Issue by pukozs75** [iptv-org/iptv#12554]
### Channel ID

ArenaSport2PremiumSerbia.rs

### Stream URL (optional)

http://82.118.0.14:8000/play/5110/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://82.118.0.14:8000/play/5110/index.m3u8
<img width="328" alt="image" src="https://user-images.githubusercontent.com/7253922/234402105-b43e43cf-9669-46fa-8f94-3567920489d8.png">

**Comment by Carlinhos027** [comment]
Offline
