### ISSUE TITLE
Add: Eurosport 1 France [FR]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/iptv#12557]
### Channel ID

Eurosport1France.fr

### Stream URL (optional)

http://195.201.107.83:8888/4/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Carlinhos027** [comment]
DMCA'd: https://github.com/iptv-org/iptv/issues/1831

Please, check the blocklist before adding a channel: https://github.com/iptv-org/database/blob/master/data/blocklist.csv

**Comment by DJ1999-max** [comment]
I will be careful.
