### ISSUE TITLE
Add: TV6 Lithuania [LT]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/iptv#12552]
### Channel ID

TV6Lithuania.lt

### Stream URL (optional)

http://88.216.83.245/tv6/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://88.216.83.245/tv6/index.m3u8
<img width="785" alt="image" src="https://user-images.githubusercontent.com/7253922/234341710-c0162772-4500-42fc-a9a9-9470aefdea47.png">
