### ISSUE TITLE
Disney Channel

### ISSUE THREAD

**Issue by Nintendocustom** [iptv-org/iptv#1256]
**Channel Name:**
Disney Channel
**Country of the channel:** **Channel Language:**
- [ ] France - French
- [ ] Spain - Spanish
- [ ] Italy - Italian
- [ ] Israel - Hebrew
- [ ] Latin America - Spanish, Portuguese(only in the Brazilian feed of the channel), English (via SAP audio track)
- [ ] Japan - Japanese
- [ ] Scandinavia - Danish, Swedish, Norwegian
- [ ] Thailand - Thai
- [ ] Poland - Polish
- [ ] Russia - Russian
- [ ] Greece - Greek
- [ ] Croatia(subs only)
- [ ] Serbia(subs only)
- [ ] Romania - Romanian
- [ ] Netherlands - Dutch
- [ ] Czech Republic - Czech
- [ ] Hungary - Hungarian
- [ ] Portugal - Portuguese
- [ ] Korea - Korean
- [x] Bulgaria - Bulgarian
- [x] Turkey - Turkish
- [x] Vietnam(only subs)
- [X] Disney Channel International
**Additional Information (optional):**
I already found this link; http://ott.artmott.com/DisneyChannel/tracks-v1a1/mono.m3u8

**Comment by freearhey** [comment]
Closed in favor #1942
