### ISSUE TITLE
Add: TiJi [FR]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/iptv#12561]
### Channel ID

TiJi.fr

### Stream URL (optional)

https://shls-tiji-tv-prod-dub.shahid.net/out/v1/98f46736bd8c4404b67e4b7a38cc8976/index.m3u8

### Notes (optional)

This one is working.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by rochelryu** [comment]
have you new Tiji FR ?

**Comment by DJ1999-max** [comment]
> have you new Tiji FR ?

No.

**Comment by rochelryu** [comment]
@DJ1999-max ok, have you any french comic in hls or dash stream ?
i research j-one, teletoon_plus, boomerang, disney_junior, disney_channel, cartoon_network, tiji and other animation.
