### ISSUE TITLE
Add: Nicktoons [AF]

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#12573]
### Channel ID

NicktoonsAfrica.za

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by dantheman121** [comment]
@freearhey i added the right id go check

**Comment by freearhey** [comment]
Duplicate of #12283
