### ISSUE TITLE
Add: Trans TV [ID]

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#12571]
### Channel ID

TransTV.id

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/d12b34e5cb0963ad1ddf9b835fee35d854451b63/streams/id.m3u#L235-L238
