### ISSUE TITLE
Add: Boing [ES]

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#12579]
### Channel ID

BoingSpain.es

### Notes (optional)

ES is the short form for spain

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/es.m3u#L52-L53
