### ISSUE TITLE
Broken: Smile TV [GR]

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#12586]
### Broken Link

https://s1.cystream.net/live/smile/playlist.m3u8 

### What happened to the stream?

Other

### Notes (optional)

I have my vpn set to greece and it still says i need a vpn

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://s1.cystream.net/live/smile/playlist.m3u8
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/7253922/234440844-2d6d7d42-5b6d-4b09-b4fd-47b80c21dced.png">
