### ISSUE TITLE
Add: MBC3 [AE]

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#12584]
### Channel ID

MBC3.ae

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/d12b34e5cb0963ad1ddf9b835fee35d854451b63/streams/ae.m3u#L76-L79
