### ISSUE TITLE
Remove: kanal Disney

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#12581]
### Your full legal name

Dantheman121

### Are you the copyright holder or authorized to act on the copyright owner's behalf?

No.

### Please describe the nature of your copyright ownership or authorization to act on the owner's behalf.

It closed in 2022

### Please provide a detailed description of the original copyrighted work that has allegedly been infringed. If possible, include a URL to where it is posted online.

N/A

### What content should be removed? Please specify the URL for each item or, if it is an entire file, the file's URL.

N/A

### Any additional information we need to know?

It closed in november 2022

### Please confirm the following

- [X] I have read and understand iptv-org's [Legal Statement](https://github.com/iptv-org/iptv#legal)

**Comment by freearhey** [comment]
Please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=%F0%9F%9B%A0+broken+stream&template=-----broken-stream.yml&title=Broken%3A+

**Comment by DJ1999-max** [comment]
But replaced new channel.
