### ISSUE TITLE
Add: hbo{hu}

### ISSUE THREAD

**Issue by erich1997** [iptv-org/iptv#12629]
### Channel ID

HBOHungary.hu

### Stream URL (optional)

http://194.76.186.33:8000/play/a03n/98355712.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://194.76.186.33:8000/play/a03n/98355712.m3u8 (offline)
<img width="375" alt="image" src="https://user-images.githubusercontent.com/7253922/235232515-211ef012-3354-4e88-a5cf-780573ab4e0f.png">

**Comment by BellezaEmporium** [comment]
> http://194.76.186.33:8000/play/a03n/98355712.m3u8 (offline) <img alt="image" width="375" src="https://user-images.githubusercontent.com/7253922/235232515-211ef012-3354-4e88-a5cf-780573ab4e0f.png">

http://194.76.186.33:8000/play/a03n/index.m3u8

**Comment by freearhey** [comment]
http://194.76.186.33:8000/play/a03n/index.m3u8
<img width="788" alt="image" src="https://user-images.githubusercontent.com/7253922/235234654-9a3dcfc5-be1c-4c00-a29d-442b1e514ee5.png">
