### ISSUE TITLE
Add: Ryan And Friends (Roku)

### ISSUE THREAD

**Issue by LPhilip1999** [iptv-org/iptv#12625]
### Channel ID

RyanAndFriends.us

### Notes (optional)

Please adding Ryan And Friends channel via The Roku Channel, thanks.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/4d53216fcefa93de70f3072c89f3b2a7fc73eec1/streams/au_samsung.m3u#L14-L15
https://github.com/iptv-org/iptv/blob/4d53216fcefa93de70f3072c89f3b2a7fc73eec1/streams/nz_samsung.m3u#L70-L71
