### ISSUE TITLE
Add: Knowledge Network [CA]

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#12633]
### Channel ID

KnowledgeNetwork.ca

### Notes (optional)

Knowledge Kids Is a British columbia tv channel

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3f5b98de81f03534350581c7382b38b498af4010/streams/ca.m3u#L108-L109

**Comment by dantheman121** [comment]
@freearhey will the stream work for me i am from canada

**Comment by freearhey** [comment]
it should if it does not please report it using this form https://github.com/iptv-org/iptv/issues/new?assignees=&labels=%F0%9F%9B%A0+broken+stream&template=-----broken-stream.yml&title=Broken%3A+

**Comment by ScaredySquirrelOfficial** [comment]
It doesn't work, there's no sound

https://d1wal6k3d7ssin.cloudfront.net/out/v1/ea91db0906c847a4931b46a9ec36e77b/index.m3u8

**Comment by Brunisky14** [comment]
@freearhey where my knowledge kids/knowledge network m3u?
