### ISSUE TITLE
Add: M2 [HU]

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#12636]
### Channel ID

M2.hu

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by erich1997** [comment]
https://c401-node61-cdn.connectmedia.hu/110302/4e214365f82b9ec04bce8e238982f7d9/644d776d/index.m3u8

**Comment by freearhey** [comment]
https://c401-node61-cdn.connectmedia.hu/110302/4e214365f82b9ec04bce8e238982f7d9/644d776d/index.m3u8 (offline)
<img width="790" alt="image" src="https://user-images.githubusercontent.com/7253922/235330328-56a3cdd4-c28d-41a8-9020-c5b520fdbbf5.png">

**Comment by erich1997** [comment]
https://c401-node61-cdn.connectmedia.hu/110302/c570ab0c2ff76caabc2fcad710247c5b/644e7bb0/index.m3u8?v=5iip:86.126.224.65

**Comment by freearhey** [comment]
https://c401-node61-cdn.connectmedia.hu/110302/c570ab0c2ff76caabc2fcad710247c5b/644e7bb0/index.m3u8?v=5iip:86.126.224.65 (offline)
<img width="832" alt="image" src="https://user-images.githubusercontent.com/7253922/235358829-9acc3aba-98db-4fa9-925e-bf6bbda2514f.png">

**Comment by erich1997** [comment]
on vlc work fine

**Comment by freearhey** [comment]
I get a 404 error with vlc

<img width="277" alt="image" src="https://user-images.githubusercontent.com/7253922/235360415-534239bf-0bc8-44e3-b6a4-abfd524884ae.png">

**Comment by dantheman121** [comment]
how to i rip m3u8 link from site

**Comment by erich1997** [comment]
http://194.76.186.33:8000/play/a00x/index.m3u8

**Comment by freearhey** [comment]
http://194.76.186.33:8000/play/a00x/index.m3u8
<img width="790" alt="image" src="https://user-images.githubusercontent.com/7253922/235466179-e9ff3411-d83f-4655-ae77-a6662ea1712e.png">

**Comment by dantheman121** [comment]
> http://194.76.186.33:8000/play/a00x/index.m3u8
> <img alt="image" width="790" src="https://user-images.githubusercontent.com/7253922/235466179-e9ff3411-d83f-4655-ae77-a6662ea1712e.png">

Its showing this:

![](https://fightthenewdrug.org/wp-content/uploads/video/screenshot.png)

**Comment by freearhey** [comment]
http://194.76.186.33:8000/play/a00x/index.m3u8
<img width="787" alt="image" src="https://user-images.githubusercontent.com/7253922/236592130-5a64e651-3344-4f88-831e-0a593c110e36.png">

Tested in VLC player.

**Comment by dantheman121** [comment]
> http://194.76.186.33:8000/play/a00x/index.m3u8 <img alt="image" width="787" src="https://user-images.githubusercontent.com/7253922/236592130-5a64e651-3344-4f88-831e-0a593c110e36.png">
> 
> Tested in VLC player.

It says playback failed
