### ISSUE TITLE
Add: super one hd (hu)

### ISSUE THREAD

**Issue by erich1997** [iptv-org/iptv#12642]
### Channel ID

SuperOne.hu

### Stream URL (optional)

http://84.17.61.203:8086/udp/238.2.25.83:1234

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://84.17.61.203:8086/udp/238.2.25.83:1234 (Offline)
<img width="342" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/92aa4b90-f80e-4c72-bf58-8f8f466df4d2">

**Comment by erich1997** [comment]
i dont have any link

**Comment by erich1997** [comment]
https://epg.pw/stream/411929e6b8607e37dc0ce8b37fa4b3785496f82ef9ff2e0796a6977e97964235.m3u8

**Comment by freearhey** [comment]
https://epg.pw/stream/411929e6b8607e37dc0ce8b37fa4b3785496f82ef9ff2e0796a6977e97964235.m3u8
![image translated](https://github.com/iptv-org/iptv/assets/7253922/38c3884a-51ba-4193-b9cd-50cd6268349c)

**Comment by erich1997** [comment]
i want close i open new
