### ISSUE TITLE
Add: hbo 3 (hu)

### ISSUE THREAD

**Issue by erich1997** [iptv-org/iptv#12640]
### Channel ID

HBO3Hungary.hu

### Stream URL (optional)

http://194.76.186.33:8000/play/a02o/13796890.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://194.76.186.33:8000/play/a02o/13796890.m3u8 (offline)
<img width="390" alt="image" src="https://user-images.githubusercontent.com/7253922/235357464-f9710790-2107-4887-a8f9-4f1693bdfa0f.png">

**Comment by erich1997** [comment]
http://194.76.186.33:8000/play/a02o/22353564.m3u8

**Comment by erich1997** [comment]
![Képernyőkép 2023-04-30 172203](https://user-images.githubusercontent.com/85035390/235358255-9abf7138-569a-4d31-b4fa-9b078cd7c9af.png)

**Comment by freearhey** [comment]
http://194.76.186.33:8000/play/a02o/22353564.m3u8 (offline)
<img width="375" alt="image" src="https://user-images.githubusercontent.com/7253922/235358610-57b53083-045c-453e-9448-dc68a1509265.png">

**Comment by erich1997** [comment]
http://194.76.186.33:8000/play/a02o/index.m3u8

**Comment by freearhey** [comment]
http://194.76.186.33:8000/play/a02o/index.m3u8
<img width="788" alt="image" src="https://user-images.githubusercontent.com/7253922/235466323-d411c624-60f5-4c79-8ffe-952516353017.png">
