### ISSUE TITLE
Add: Isibo TV [RW]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12667]
### Channel ID

IsiboTV.rw

### Stream URL (optional)

https://tv.livebcm.com:3192/live/isibotvlive.m3u8

### Notes (optional)

480p / Not 24/7

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://tv.livebcm.com:3192/live/isibotvlive.m3u8
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/7253922/235778396-a58a2715-c8cc-41a6-888e-77077c962030.png">
