### ISSUE TITLE
Add: EBS Kids [KR]

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#12671]
### Channel ID

EBSKids.kr

### Notes (optional)

The current stream doesnt work because i get a 403 error in vlc

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/99952c7dd2180c2533c16f381797add250960e19/streams/kr.m3u#L58-L59

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/7253922/235757823-da927619-08d3-4e70-b050-5d14c715fd5b.png">
