### ISSUE TITLE
Broken: Mazhavil Manorama

### ISSUE THREAD

**Issue by zcraber** [iptv-org/iptv#12681]
### Broken Link

http://14.199.164.20:4001/play/a0kd/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

![image](https://user-images.githubusercontent.com/61133303/236019725-0ce2270e-b316-4404-acd1-0817a96e0ce1.png)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/29463d83142617315131dbf052e4e45d142568da/streams/in.m3u#L178-L179
