### ISSUE TITLE
Broken:  Kalaignar Murasu

### ISSUE THREAD

**Issue by zcraber** [iptv-org/iptv#12684]
### Broken Link

http://103.199.160.85/Content/kalaignarmurasu/Live/Channel(KalaignarMurasu)/index.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/b8c1759b70eb0511606ba512b3a8f6948a0d7c1a/streams/in.m3u#L142-L143
