### ISSUE TITLE
Add: Sal Television [ES]

### ISSUE THREAD

**Issue by BellezaEmporium** [iptv-org/iptv#12680]
### Channel ID

SalTelevision.es

### Stream URL (optional)

https://cloudvideo.servers10.com:8081/8254/index.m3u8

### Notes (optional)

From Andalucia. Starting to put the LATAM / ES channels from the discussion here.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/229d5b1107079b1a1cd614b8adbfc6bc8f7cd42b/streams/es.m3u#L382-L383
