### ISSUE TITLE
Add: Tele 13 [Chile]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#12698]
### Channel ID

*N/A*

### Stream URL (optional)

https://unlimited1-cl-isp.dps.live/t13/t13.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Carlinhos027** [comment]
Valid for alt link. Thanks!

**Comment by freearhey** [comment]
https://unlimited1-cl-isp.dps.live/t13/t13.smil/playlist.m3u8 (Offline)
<img width="416" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/15ea7397-9560-4629-9e15-4e0e7c796631">
