### ISSUE TITLE
Broken: Knowledge Kids

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#12697]
### Broken Link

i don't have one

### What happened to the stream?

Not loading

### Notes (optional)

i live in bc and its saying i need to be in canada

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
It's simply geo-blocked, meaning you need a VPN or a proxy connected in Canada to watch it.
