### ISSUE TITLE
Add: Zee Uttar Pradesh/Uttarakhand (India)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#12696]
### Channel ID

ZeeUttarPradeshUttarakhand.in

### Stream URL (optional)

https://livetv-channels.b-cdn.net/8076/chunklist0.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
https://livetv-channels.b-cdn.net/8076/playlist.m3u8
