### ISSUE TITLE
poland channels

### ISSUE THREAD

**Issue by amirh123123** [iptv-org/iptv#1270]
**Country of the channel:**poland

**Channel Name:**

4fun
4fun dance
4fun gold
**Channel Language:**polish

**Additional Information (optional):**
genre music

**Comment by boomski** [comment]
added to the PL playlist:

#EXTINF:-1` tvg-id="" tvg-name="" tvg-language="Polish" tvg-logo="https://i.imgur.com/c59VWgF.jpg" group-title="Music",4FUN TV
https://stream.4fun.tv:8888/hls/4f_high/index.m3u8

**Comment by freearhey** [comment]
Closed in favor #1965

**Comment by Rguanchez** [comment]
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Polish" tvg-logo="https://camo.githubusercontent.com/8a4acc793b242b4a893776b433c0c50759c7a5122c389264897d14bfc928efc8/68747470733a2f2f692e696d6775722e636f6d2f5a4557486531422e706e67" group-title="Music",4FUN Dance
https://cdn-nvm-chicago.lolokoko.tv/4fundance.stream/chunks.m3u8
