### ISSUE TITLE
Add: Madaniyat [KG] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12707]
### Channel ID

Madaniyat.kg

### Stream URL (optional)

http://onlinetv.ktrk.kg:1935/live/myStream5/playlist.m3u8

### Notes (optional)

576p

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/ae54389bbbe2cc8350172f5d21d0c7bbcb77b69d/streams/kg.m3u#L4-L5
