### ISSUE TITLE
Broken: Kairali We

### ISSUE THREAD

**Issue by zcraber** [iptv-org/iptv#12715]
### Broken Link

http://103.199.161.254/Content/we/Live/Channel(We)/index.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/c22e58fa474bdb805fcfda119a59d32fbfbefeae/streams/in.m3u#L144-L145
