### ISSUE TITLE
Add: Alyaum Channel [SY] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12721]
### Channel ID

AlyaumChannel.sy

### Stream URL (optional)

https://ikomg1.s.llnwi.net/alyaum-tv/alyaum-tv.m3u8

### Notes (optional)

720p

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by UltraHDR** [comment]
Thanks but it's in https://github.com/iptv-org/iptv/blob/master/streams/ae.m3u
