### ISSUE TITLE
Add:  Palestine Al Yawm [LB]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12725]
### Channel ID

PalestineAlYawm.lb

### Stream URL (optional)

https://live.paltodaytv.com/paltv/live/playlist.m3u8

### Notes (optional)

480p

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/ae54389bbbe2cc8350172f5d21d0c7bbcb77b69d/streams/ps.m3u#L40-L41
