### ISSUE TITLE
Broken: Space Shower TV

### ISSUE THREAD

**Issue by BoiledCabbage66** [iptv-org/iptv#12733]
### Broken Link

https://code.vthanhtivi.pw/getlink/jptv/P86mGOvGtsJuOiIBozlSTA==/playlist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1042d971c8ab2325ab56d62340ea4eaaad38a2f0/streams/jp.m3u#L124-L125

**Comment by freearhey** [comment]
https://code.vthanhtivi.pw/getlink/jptv/P86mGOvGtsJuOiIBozlSTA==/playlist.m3u8
<img width="789" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/d58acadc-ad87-403d-b331-1f616947cca8">
