### ISSUE TITLE
Broken: CNN

### ISSUE THREAD

**Issue by mjdbb1** [iptv-org/iptv#12730]
### Broken Link

https://16live00.akamaized.net/CNN/index.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by clips519** [comment]
https://tve-live-lln.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_0_3564000.m3u8

**Comment by mjdbb1** [comment]
> https://tve-live-lln.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_0_3564000.m3u8

Is this working for anyone?  Not working for me.

**Comment by freearhey** [comment]
https://tve-live-lln.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_0_3564000.m3u8
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/7253922/236734508-e59b4322-53ec-4166-9ffe-698e6af27f9f.png">

**Comment by clips519** [comment]
It works don't know why not for him

**Comment by mjdbb1** [comment]
Very weird.  Can't get it to work regardless of app, device, or IP address.

**Comment by BellezaEmporium** [comment]
> Very weird. Can't get it to work regardless of app, device, or IP address.

They might have exerced IP-ranged bans on enemy countries (on the US point of view).

**Comment by yerffejytnac** [comment]
Broken for me now in the states, something happened today as it worked perfectly fine yesterday. 

![image](https://github.com/iptv-org/iptv/assets/2856292/ea095196-8845-4578-b2e3-7682ccfb1767)

**Comment by clips519** [comment]
it seems anything warner media  needs to be changed from tve-live-lln to tve-live-ctl to work

**Comment by yerffejytnac** [comment]
Hmm, the ctl based link stopped working this morning for me. Anyone else?

**Comment by BellezaEmporium** [comment]
Moved to "live-media-aka.warnercdn.com" and all HLS links were disabled in the same moment. Only protected links work now.

**Comment by hypermug1** [comment]
Found a stream https://d30x5vsa85tvmd.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-7y561g9sa9uht/index.m3u8?ads.device_did=%7BPSID%7D&ads.device_dnt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.consent=%7BTC_STRING%7D

**Comment by jhedfors** [comment]
Working CNN US (CNN.us) link:
https://turnerlive.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_3_1464000.m3u8
