### ISSUE TITLE
Broken: TNT East

### ISSUE THREAD

**Issue by mjdbb1** [iptv-org/iptv#12731]
### Broken Link

https://16live00.akamaized.net/TNT/index.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by clips519** [comment]
https://tve-live-ctl.warnermediacdn.com/hls/live/2023168/tnteast/slate/VIDEO_0_3564000.m3u8

**Comment by mjdbb1** [comment]
> https://tve-live-ctl.warnermediacdn.com/hls/live/2023168/tnteast/slate/VIDEO_0_3564000.m3u8

Is this working for anyone?  Not working for me.

**Comment by clips519** [comment]
it works iam watching it now basketball

**Comment by mjdbb1** [comment]
> it works iam watching it now basketball

Weird.  Can't get it to work in VLC or Emby.  Including with and without VPN.

**Comment by clips519** [comment]
ya thats weird do you make your own list with notepad? just replace the link i use this  

#EXTINF:-1 tvg-id="TNTEast.us" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/TNT_Logo_2016.svg/512px-TNT_Logo_2016.svg.png" group-title="",TNT East 
https://tve-live-ctl.warnermediacdn.com/hls/live/2023168/tnteast/slate/VIDEO_0_3564000.m3u8

**Comment by freearhey** [comment]
https://tve-live-ctl.warnermediacdn.com/hls/live/2023168/tnteast/slate/VIDEO_0_3564000.m3u8 (geo-blocked)
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/7253922/236734776-350e56df-f728-47ee-a18f-4a3ced8295f2.png">

**Comment by mjdbb1** [comment]
Well, I don't get it.  Can't get it to work for me regardless of app, device, or IP address.

**Comment by takethis2165** [comment]
it works great with vlc

**Comment by fearlesschicken** [comment]
Broken for some time now

**Comment by rp121** [comment]
> https://tve-live-ctl.warnermediacdn.com/hls/live/2023168/tnteast/slate/VIDEO_0_3564000.m3u8 (geo-blocked) <img alt="image" width="1418" src="https://user-images.githubusercontent.com/7253922/236734776-350e56df-f728-47ee-a18f-4a3ced8295f2.png">

This stream link is dead
