### ISSUE TITLE
Broken: Amrita TV [IN]

### ISSUE THREAD

**Issue by zcraber** [iptv-org/iptv#12746]
### Broken Link

http://103.199.161.254/Content/amrita/Live/Channel(Amrita)/index.m3u8

### What happened to the stream?

I see visual artifacts

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/a685960eac0744af1d3a11416c19dab63d7d7c8f/streams/in.m3u#L20-L21
