### ISSUE TITLE
Broken: Asianet Middle East [IN]

### ISSUE THREAD

**Issue by zcraber** [iptv-org/iptv#12752]
### Broken Link

http://14.199.164.20:4001/play/a0k6/index.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/a685960eac0744af1d3a11416c19dab63d7d7c8f/streams/in.m3u#L54-L55
