### ISSUE TITLE
Add: Tokyo MX2

### ISSUE THREAD

**Issue by ZXArkin** [iptv-org/iptv#12781]
### Channel ID

TokyoMX2.jp

### Stream URL (optional)

https://code.vthanhtivi.pw/getlink/jptv/u6-t-I0UVIdrkCYJzXFkpg==/playlist.m3u8

### Notes (optional)

![TOKYO MX 2 (v2)_20230510_183946 720](https://github.com/iptv-org/iptv/assets/21299971/7cc838ac-75b0-47e1-8bb7-c35f7d0797c6)
2nd link:
http://rip.hidari.moe/get/jptv/get.php?id=u6-t-I0UVIdrkCYJzXFkpg==

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
1) Cloudflare server behind this, not sure it'll stay for a long period, as they do not condone streaming through their servers.
2) Weird server, from a "free japanese TV" service. DNS ns1432.ztomy.com

**Comment by freearhey** [comment]
https://code.vthanhtivi.pw/getlink/jptv/u6-t-I0UVIdrkCYJzXFkpg==/playlist.m3u8
<img width="569" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/6bfaaae2-bb21-4926-8424-cc9111879f90">

https://github.com/iptv-org/iptv/blob/48637ae9d05d4d73cfed0b1eccaf8368945d1bc6/streams/jp.m3u#L50-L51
