### ISSUE TITLE
Broken: AT-X (JP)

### ISSUE THREAD

**Issue by solo489** [iptv-org/iptv#12794]
### Broken Link

ATX.jp

### What happened to the stream?

I see visual artifacts

### Notes (optional)

Turn off the subtitles.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Computershik73** [comment]
Very slow connection even with good internet speed. Cannot watch all Japanese streams.
Though Neetball streams worked well, but they are now unavailable (require a password)

**Comment by Johelectrix09** [comment]
Mine was actually ok and also I just refreshed it on VLC

**Comment by Johelectrix09** [comment]
After you removed these channels obviously you're gonna look for alternate
streams right??
