### ISSUE TITLE
Broken: CNN US 

### ISSUE THREAD

**Issue by markosjal** [iptv-org/iptv#12797]
### Broken Link

https://tve-live-lln.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_0_3564000.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

As of a few days ago no longer loads. 

This also applies to
https://tve-live-lln.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_1_3564000.m3u8
https://tve-live-lln.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_2_3564000.m3u8
https://tve-live-lln.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_3_3564000.m3u8
https://tve-live-lln.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_4_3564000.m3u8
https://16live00.akamaized.net/CNN/index.m3u8

The stitcher link listed at  https://iptv-org.github.io/?q=cnn is NOT a live CNN feed  
(https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5421f71da6af422839419cb3/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5421f71da6af422839419cb3&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=209&terminate=false&userId=)

Is not a REAL CNN stream is is like CNN highlights

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
The playlists do not contain this link: https://github.com/search?q=repo%3Aiptv-org%2Fiptv+https%3A%2F%2Ftve-live-lln.warnermediacdn.com%2Fhls%2Flive%2F586495%2Fcnngo%2Fcnn_slate%2FVIDEO_0_3564000.m3u8&type=code

**Comment by devenator** [comment]
> The playlists do not contain this link: https://github.com/search?q=repo%3Aiptv-org%2Fiptv+https%3A%2F%2Ftve-live-lln.warnermediacdn.com%2Fhls%2Flive%2F586495%2Fcnngo%2Fcnn_slate%2FVIDEO_0_3564000.m3u8&type=code

But all the other links:

#EXTINF:-1 tvg-id="CNN.us",CNN
https://16live00.akamaized.net/CNN/index.m3u8
#EXTINF:-1 tvg-id="CNN.us",CNN USA (720p)
https://tve-live-ctl.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_0_3564000.m3u8
#EXTINF:-1 tvg-id="CNN.us",CNN USA (480p)
https://tve-live-ctl.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_2_1964000.m3u8
#EXTINF:-1 tvg-id="CNN.us",CNN USA (360p)
https://tve-live-ctl.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_3_1464000.m3u8
#EXTINF:-1 tvg-id="CNN.us",CNN USA (360p)
https://tve-live-ctl.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_4_1064000.m3u8
