### ISSUE TITLE
iran channels

### ISSUE THREAD

**Issue by amirh123123** [iptv-org/iptv#1279]
**Country of the channel:**iran

**Channel Name:**

mbc persia
persiana5
varzesh4
poker tv
**Channel Language:**persian

**Additional Information (optional):**

**Comment by boomski** [comment]
Poker TV en Persiana are already in the fr.m3u playlist (Persiana is a Persian broadcast news station based in Paris, France and Dubai.)
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Persian" tvg-logo="https://i.imgur.com/X9U6AqK.png" group-title="",Persiana 1
http://51.15.229.209/hls/stream.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Persian" tvg-logo="https://i.imgur.com/rioc5XV.jpg" group-title="",Persiana 2 Cinema
http://51.15.193.156/hls/stream.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Persian" tvg-logo="https://i.imgur.com/rioc5XV.jpg" group-title="",Persiana 3 Junior
http://51.158.74.129/hls/stream.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Persian" tvg-logo="https://i.imgur.com/rioc5XV.jpg" group-title="",Persiana 4 Iranian
http://51.158.97.214/hls/stream.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Persian" tvg-logo="https://i.imgur.com/rioc5XV.jpg" group-title="",Persiana 5 Documentary
http://163.172.174.60/hls/stream.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Persian" tvg-logo="https://i.imgur.com/rioc5XV.jpg" group-title="",Persiana 6 Music
http://163.172.147.113/hls/stream.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Persian" tvg-logo="https://i.imgur.com/43gYR8Y.png" group-title="",Poker TV Arabia
http://51.15.193.127/hls/stream.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/43gYR8Y.png" group-title="",Poker TV France
http://51.15.254.60/hls/stream.m3u8

**Comment by boomski** [comment]
varzesh4 
#EXTINF:-1 tvg-logo="https://i.imgur.com/f1e6M2L.png"Varzesh TV 4
http://163.172.138.186/hls/stream.m3u8

**Comment by amirh123123** [comment]
please add this channels
ava family
ava serials
navahang
20tv
30tv
xo tv

**Comment by Sphinxroot** [comment]
navahang = tv(.)navahang(.)com  http://163.172.134.85/hls/stream.m3u8

manny stream on those
sepehr(.)irib(.)ir/
www(.)imvbox(.)tv/

**Comment by eye2eyeam** [comment]
Add Gem film

**Comment by themak1985** [comment]
Saving these links here, if still working tomorrow, will add.

**Based in Iran**
AVA Family http://51.210.199.5/hls/stream.m3u8
AVA Series http://51.210.199.4/hls/stream.m3u8
GEM TV https://d2e40kvaojifd6.cloudfront.net/stream/gem_tv/playlist_1920x1080_4500k.m3u8
IRIB Varzesh https://livetv.persianleague.com/live/varzesh1245/chunks.m3u8

**Based in France**
Persiana Family: http://51.210.199.19/hls/stream.m3u8
Persiana Cinema: http://51.210.199.15/hls/stream.m3u8
Persiana Junior: http://51.210.199.18/hls/stream.m3u8
Persiana Iranian: http://51.210.199.22/hls/stream.m3u8
Persiana Technology: http://51.210.199.25/hls/stream.m3u8
Persiana Documentary: http://51.210.199.23/hls/stream.m3u8
Persiana Music: http://51.210.199.24/hls/stream.m3u8
Persiana Billboard: http://51.210.199.10/hls/stream.m3u8
Persiana Nostalgia: http://51.210.199.20/hls/stream.m3u8
Persiana Classic: http://163.172.138.186/hls/stream.m3u8
Persiana Comedy: http://51.210.199.27/hls/stream.m3u8
Persiana Action: http://51.158.106.105/hls/stream.m3u8
4 Kurd: http://51.210.199.28/hls/stream.m3u8
4 Turk: http://51.210.199.28/hls/stream.m3u8
4 Turk Billboard: http://51.210.199.30/hls/stream.m3u8

20tv, 30tv, xo tv, and poker tv are defunct channels.

**Comment by themak1985** [comment]
Added: https://github.com/iptv-org/iptv/commit/49c255d54c40e96e6d87a2348fbe650702bad3e4
https://github.com/iptv-org/iptv/commit/744356ac9af8f7b4dd42b22bc393f91761c430cb

**Comment by FILMOVIEONE** [comment]
Does anyone have a link to the online streaming of Cine Film tv?

**Comment by Nostradamus1973** [comment]
Good morning,
Can someone please provide the m3u8 for Gem TV?
Every source I have is secondary and can only provide the current day's token, meaning I have to look daily for streams.
Thank you and have a nice day.

**Comment by ebiduli** [comment]
شبکه tv8 در ماهواره یاهست اظافه شود در صورت امکان با تشکر
