### ISSUE TITLE
Broken: whole Turner set of channels

### ISSUE THREAD

**Issue by SkylerDaKat** [iptv-org/iptv#12804]
### Broken Link

https://tve-live-ctl.warnermediacdn.com/hls/live/2023167/tooneast/slate/VIDEO_0_3564000.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

I accidentally put an extra 0 on the last one, mb

the issue with this thing is that it doesn't work at all, the screen is all black 
and when I try to put it in a video player it gives me an error message

*edited by BellezaEmporium : issue now generalised to the whole set of channels from the Turner network*

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by SkylerDaKat** [comment]
I tried using a VPN but it didn't work either

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/5f226944bdd72a1274eda45f28d0d751c3e0203a/streams/us.m3u#L204-L205

**Comment by folcabol77** [comment]
both links are not working as well:
#EXTINF:-1 tvg-id="TCMTurnerClassicMoviesEast.us" tvg-name="TCM (Turner Classic Movies) (East)" tvg-country="US" tvg-language="English" tvg-logo="https://i.imgur.com/sbrSfhC.jpg" group-title="Classic",TCM (Turner Classic Movies) (East) [Geo-blocked]
https://tve-live-ctl.warnermediacdn.com/hls/live/2023186/tcmeast/noslate/VIDEO_1_5128000.m3u8
#EXTINF:-1 tvg-id="TCMTurnerClassicMoviesWest.us" tvg-name="TCM (Turner Classic Movies) (West)" tvg-country="US" tvg-language="English" tvg-logo="https://i.imgur.com/sbrSfhC.jpg" group-title="Classic",TCM (Turner Classic Movies) (West) [Geo-blocked]
https://tve-live-ctl.warnermediacdn.com/hls/live/2023187/tcmwest/noslate/VIDEO_1_5128000.m3u8

**Comment by folcabol77** [comment]
@freearhey  still not working

**Comment by BellezaEmporium** [comment]
I believe they moved to other servers + MPD. Basically, it is now unavailable if you don't have the keys to decrypt the stream.

**Comment by BellezaEmporium** [comment]
That's what I've thought. They've disabled the HLS links (gone 404)

**Comment by SkylerDaKat** [comment]
> That's what I've thought. They've disabled the HLS links (gone 403)

That sucks qwq

**Comment by BellezaEmporium** [comment]
![image](https://github.com/iptv-org/iptv/assets/30985701/c12fce82-ec3e-4b76-9278-28dd0988d2b1)

Managed to catch the URL that decrypts the streams too, but doesn't work outside of the website.

**Comment by SkylerDaKat** [comment]
Oh? How does that work-

**Comment by BellezaEmporium** [comment]
> Oh? How does that work-

This is a program that's used to download (and supposedly play ?) streams, including Widevine streams, as long as you have the necessary to decrypt the data.

So far i'm playing with it to see how it works.

**Comment by SkylerDaKat** [comment]
> > Oh? How does that work-
> 
> This is a program that's used to download (and supposedly play ?) streams, including Widevine streams, as long as you have the necessary to decrypt the data, it's using FFMPEG.
> 
> So far i'm playing with it to see how it works.

That's actually really cool, 
Also wish you luckk

**Comment by folcabol77** [comment]
Hi,
Can you look up both TCM east and west links as well? They both have the same problem:
[https://tve-live-ctl.warnermediacdn.com/hls/live/2023186/tcmeast/noslate/VIDEO_1_5128000.m3u8](url)
[https://tve-live-ctl.warnermediacdn.com/hls/live/2023187/tcmwest/noslate/VIDEO_1_5128000.m3u8](url)

**Comment by SkylerDaKat** [comment]
> Hi, Can you look up both TCM east and west links as well? They both have the same problem: [https://tve-live-ctl.warnermediacdn.com/hls/live/2023186/tcmeast/noslate/VIDEO_1_5128000.m3u8](url) [https://tve-live-ctl.warnermediacdn.com/hls/live/2023187/tcmwest/noslate/VIDEO_1_5128000.m3u8](url)

Read the title-
They already know xd

**Comment by 27hectormanuel** [comment]
> ![image](https://user-images.githubusercontent.com/30985701/238180564-c12fce82-ec3e-4b76-9278-28dd0988d2b1.png)
> 
> Managed to catch the URL that decrypts the streams too, but doesn't work outside of the website.

What's the website with cable login for cartoon network?

**Comment by Metroid2023** [comment]
Hello! I'm Metroid2023! Try changing cti to aka.

**Comment by folcabol77** [comment]
> Metroid2023

did you try it because it does not work

**Comment by Metroid2023** [comment]
Yeah! I tried all of them, and it's still not working! I thought it would work for you all.

**Comment by SkylerDaKat** [comment]
> Hello! I'm Metroid2023! Try changing ctl to aka.

CTL works but it's apparently encrypted now, they found what decrypts it but they haven't said anything yet so gotta wait qwp

**Comment by BellezaEmporium** [comment]
> > Hello! I'm Metroid2023! Try changing ctl to aka.
> 
> CTL works but it's apparently encrypted now, they found what decrypts it but they haven't said anything yet so gotta wait qwp

So far i've tried a few things but it didn't seem to work.

**Comment by Metroid2023** [comment]
Is there a way to decrypt this?

**Comment by SkylerDaKat** [comment]
> > > Hello! I'm Metroid2023! Try changing ctl to aka.
> > 
> > 
> > CTL works but it's apparently encrypted now, they found what decrypts it but they haven't said anything yet so gotta wait qwp
> 
> So far i've tried a few things but it didn't seem to work.

*Cry* seems like it's over, just like the Viacom channels QwQ isn't it?

**Comment by Metroid2023** [comment]
> they have moved their turner network streams cdn to https://turnerlive.warnermediacdn.com
> 
> working streams cn east: https://turnerlive.warnermediacdn.com/hls/live/2023167/tooneast/slate/VIDEO_0_3564000.m3u8 cn west: https://turnerlive.warnermediacdn.com/hls/live/2023180/toonwest/slate/VIDEO_0_3564000.m3u8 as east: https://turnerlive.warnermediacdn.com/hls/live/2023183/aseast/noslate/VIDEO_1_5128000.m3u8 as west: https://turnerlive.warnermediacdn.com/hls/live/2023185/aswest/noslate/VIDEO_1_5128000.m3u8
> 
> please update

Yay! Thank you very much! It worked!

**Comment by justAuser2** [comment]
TCM east confirmed as working: https://turnerlive.warnermediacdn.com/hls/live/2023186/tcmeast/noslate/VIDEO_1_5128000.m3u8

**Comment by BellezaEmporium** [comment]
> they have moved their turner network streams cdn to https://turnerlive.warnermediacdn.com
> 
> working streams cn east: https://turnerlive.warnermediacdn.com/hls/live/2023167/tooneast/slate/VIDEO_0_3564000.m3u8 cn west: https://turnerlive.warnermediacdn.com/hls/live/2023180/toonwest/slate/VIDEO_0_3564000.m3u8 as east: https://turnerlive.warnermediacdn.com/hls/live/2023183/aseast/noslate/VIDEO_1_5128000.m3u8 as west: https://turnerlive.warnermediacdn.com/hls/live/2023185/aswest/noslate/VIDEO_1_5128000.m3u8
> 
> please update

confirmed. all good.

**Comment by SkylerDaKat** [comment]
I do have a question,
Why is boomerang not available <.< Just curious

**Comment by JerkyHockey** [comment]
your forgetting TBS, TNT and TruTV

**Comment by JerkyHockey** [comment]
is this geo-blocked by any chance???

**Comment by SkylerDaKat** [comment]
> your forgetting TBS, TNT and TruTV

Every channel has a link except boomerang

**Comment by SuperstationWTF** [comment]
> > your forgetting TBS, TNT and TruTV
> 
> Just replace the tve-live-ctl subdomain for turnerlive Working Streams: TNT East: https://turnerlive.warnermediacdn.com/hls/live/2023168/tnteast/slate/VIDEO_0_3564000.m3u8 TNT West: https://turnerlive.warnermediacdn.com/hls/live/2023170/tntwest/slate/VIDEO_0_3564000.m3u8 TBS East: https://turnerlive.warnermediacdn.com/hls/live/2023172/tbseast/slate/VIDEO_0_3564000.m3u8 TBS West: https://turnerlive.warnermediacdn.com/hls/live/2023174/tbswest/slate/VIDEO_0_3564000.m3u8 TruTV East: https://turnerlive.warnermediacdn.com/hls/live/2023176/trueast/slate/VIDEO_0_3564000.m3u8 TruTV West: https://turnerlive.warnermediacdn.com/hls/live/2023178/truwest/slate/VIDEO_0_3564000.m3u8

Thanks, replying to get updates. Missed AEW last night, but they do put highlights on their Youtube channel.

**Comment by BellezaEmporium** [comment]
Normally the "VIDEO_xxxxx" are found from the master being "master_ww_de" or "master_ww_ph"

ww meaning Widevine, and "de"/"ph" being Desktop/Phone

**Comment by darkmaster420** [comment]
> Normally the "VIDEO_xxxxx" are found from the master being "master_wv_de" or "master_wv_ph"
> 
> wv meaning Widevine, and "de"/"ph" being Desktop/Phone
> 
> so in this case the master should be "master_de" or "master_ph"


And where can we find the master?

**Comment by Admi9838** [comment]
How do i add the channels to a iptv app?

**Comment by spotanjo3** [comment]
> they have moved their turner network streams cdn to https://turnerlive.warnermediacdn.com
> 
> working streams cn east: https://turnerlive.warnermediacdn.com/hls/live/2023167/tooneast/slate/VIDEO_0_3564000.m3u8 cn west: https://turnerlive.warnermediacdn.com/hls/live/2023180/toonwest/slate/VIDEO_0_3564000.m3u8 
> 
> please update

They no longer work anymore. 

> > your forgetting TBS, TNT and TruTV
> 
> Just replace the tve-live-ctl subdomain for turnerlive Working Streams: TNT East: https://turnerlive.warnermediacdn.com/hls/live/2023168/tnteast/slate/VIDEO_0_3564000.m3u8 TNT West: https://turnerlive.warnermediacdn.com/hls/live/2023170/tntwest/slate/VIDEO_0_3564000.m3u8 TBS East: https://turnerlive.warnermediacdn.com/hls/live/2023172/tbseast/slate/VIDEO_0_3564000.m3u8 TBS West: https://turnerlive.warnermediacdn.com/hls/live/2023174/tbswest/slate/VIDEO_0_3564000.m3u8 TruTV East: https://turnerlive.warnermediacdn.com/hls/live/2023176/trueast/slate/VIDEO_0_3564000.m3u8 TruTV West: https://turnerlive.warnermediacdn.com/hls/live/2023178/truwest/slate/VIDEO_0_3564000.m3u8

They works fine, thank you.

**Comment by djfearless** [comment]
they stop working again

**Comment by BellezaEmporium** [comment]
TNT East: https://turnerlive.warnermediacdn.com/hls/live/2023168/tnteast/slate/VIDEO_0_3564000.m3u8
TNT West: https://turnerlive.warnermediacdn.com/hls/live/2023170/tntwest/slate/VIDEO_0_3564000.m3u8
TBS East: https://turnerlive.warnermediacdn.com/hls/live/2023172/tbseast/slate/VIDEO_0_3564000.m3u8
TBS West: https://turnerlive.warnermediacdn.com/hls/live/2023174/tbswest/slate/VIDEO_0_3564000.m3u8
TruTV East: https://turnerlive.warnermediacdn.com/hls/live/2023176/trueast/slate/VIDEO_0_3564000.m3u8
TruTV West: https://turnerlive.warnermediacdn.com/hls/live/2023178/truwest/slate/VIDEO_0_3564000.m3u8
CNN https://turnerlive.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_0_3564000.m3u8
TCM https://turnerlive.warnermediacdn.com/hls/live/2023186/tcmeast/noslate/VIDEO_1_5128000.m3u8

all of those works for me, US IP.

**Comment by BellezaEmporium** [comment]
Cartoon Network however doesn't. That's the only channel I know that doesn't.
