### ISSUE TITLE
Add: Беларусь 3 [Not 24/7]

### ISSUE THREAD

**Issue by Emilselimli** [iptv-org/iptv#12809]
### Channel ID

Belarus3.by

### Stream URL (optional)

https://ngtrk.dc.beltelecom.by/ngtrk/smil:belarus3.smil/playlist.m3u8

### Notes (optional)

Belarus 3 please added

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f5365559e217acd3c352b0ffe54b5d95a9eb3ff6/streams/by.m3u#L2-L3
