### ISSUE TITLE
Broken: Cartoon network and possibly every turner network channels

### ISSUE THREAD

**Issue by SkylerDaKat** [iptv-org/iptv#12800]
### Broken Link

https://tve-live-ctl.warnermediacdn.com/hls/live/2023167/tooneast/slate/VIDEO_0_35640000.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

It's dead, the channel doesn't load, and TBS isn't either.
Not even stuttering, just all black

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
The playlists do not contain this link: https://github.com/search?q=repo%3Aiptv-org%2Fiptv+https%3A%2F%2Ftve-live-ctl.warnermediacdn.com%2Fhls%2Flive%2F2023167%2Ftooneast%2Fslate%2FVIDEO_0_35640000.m3u8&type=code

**Comment by SkylerDaKat** [comment]
It's still an issue cuz the playlist doesn't load CN, TCM, TBS, TruTV unless this was a DMCA takedown-
