### ISSUE TITLE
Irish Channels

### ISSUE THREAD

**Issue by Brandon14irl** [iptv-org/iptv#1280]
**Country of the channel:** Ireland

**Channel Name:**
RTE 1
RTE 2
Virgin Media 1
Virgin Media 2
Virgin Media 3
RTE Jr
RTE News Now

**Channel Language:**
English

**Additional Information (optional):**

**Comment by Nintendocustom** [comment]
RTE 1
http://stream-7b694ce7e.nmbs.top/m3u/Uk/3dfb505ffe.m3u8
RTE 2
http://stream-7b694ce7e.nmbs.top/m3u/Uk/6ec2e0716f.m3u8
RTE Jr
http://stream-7b694ce7e.nmbs.top/m3u/Uk/5aea738548.m3u8
RTE News Now
http://stream-7b694ce7e.nmbs.top/m3u/Uk/7770080c80.m3u8

**Comment by freearhey** [comment]
RTE News Now https://github.com/iptv-org/iptv/blob/6c9aa8e95ee4ade1be68c8686e632f17797d0052/channels/ie.m3u#L4-L5

**Comment by freearhey** [comment]
Closed in favor #1966
