### ISSUE TITLE
Broken: 

### ISSUE THREAD

**Issue by Admi9838** [iptv-org/iptv#12814]
### Broken Link

https://tve-live-ctl.warnermediacdn.com/hls/live/2023167/tooneast/slate/VIDEO_0_3564000.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Cartoon Network East TVE 
Cartoon Network West TVE
Adult Swim East
Adult Swim West

**All STREAMS ARE DOWN**

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
Known, will close this to focus on https://github.com/iptv-org/iptv/issues/12804
