### ISSUE TITLE
Broken: TBS West

### ISSUE THREAD

**Issue by jhedfors** [iptv-org/iptv#12812]
### Broken Link

https://tve-live-ctl.warnermediacdn.com/hls/live/2023174/tbswest/slate/VIDEO_0_3564000.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
Known, will close this to focus on https://github.com/iptv-org/iptv/issues/12804
