### ISSUE TITLE
Broken: TNT West (720p) [Geo-blocked]

### ISSUE THREAD

**Issue by jhedfors** [iptv-org/iptv#12811]
### Broken Link

https://tve-live-ctl.warnermediacdn.com/hls/live/2023170/tntwest/slate/VIDEO_0_3564000.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
Known, will close this to focus on https://github.com/iptv-org/iptv/issues/12804
