### ISSUE TITLE
Add: Nicktoons Scandinavia [NL]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/iptv#12849]
### Channel ID

NicktoonsScandinavia.nl

### Stream URL (optional)

http://89.254.128.5:22280/nicktoons/video.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by cr0op** [comment]
not to necropost but thank you for adding nicktoons scandinavia. it's probably the only good feed of that network left.

**Comment by nighty11x** [comment]
Does anyone have a updated stream url?
