### ISSUE TITLE
Add: Latvijas Radio 1 [LV]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/iptv#12846]
### Channel ID

LatvijasRadio1.lv

### Stream URL (optional)

https://60766ff53d5e6.streamlock.net/liveVLR1/mp4:LR1.mp4/playlist.m3u8

### Notes (optional)

Stream works!

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
We do not add radio broadcasts to playlists.

`LatvijasRadio1.lv` will be removed from the database during the next update (https://github.com/iptv-org/database/issues/3717).
