### ISSUE TITLE
Add: Nick HD, MTV and Comedy Central USA

### ISSUE THREAD

**Issue by JerkyHockey** [iptv-org/iptv#12853]
### Channel ID

MTV&Comedy&NickEast.us

### Notes (optional)

Please add one of the these networks
• Nickelodeon HD (East) USA
• MTV HD (East) USA 
Comedy Central HD (East) USA
Must be m3u8 Working Links! Thx

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by JerkyHockey** [comment]
idk what the id is, plus I’m new here so yeah..

**Comment by BellezaEmporium** [comment]
Please make 1 request / channel, following these [guidelines](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#issue-reporting-guidelines)

**Comment by JerkyHockey** [comment]
Ok

**Comment by JerkyHockey** [comment]
WAIT! NVM i found these links right here
MTV HD:https://content-ause1.uplynk.com/channel/aba50cebb8f84fbead72cf7d26217a36/e.m3u8?ct=c&ad.locationDesc=vcbs_mtv_desktop_web_live&ad.cust_params=_fw_ae%3Da016e7e3817eec54180fba6a64ae6616%26_vmn_ar%3Dtrue&expand=simulcast_unified_standard&ad.kv=fms_userid,7123f0e6-8e5c-4e23-a0f5-3f62aeeec8c2,_fw_ae,a016e7e3817eec54180fba6a64ae6616,_vmn_ar,true,_fw_vcid2,7123f0e6-8e5c-4e23-a0f5-3f62aeeec8c2,fms_vcid2type,userid&exp=1684276309&rn=1661393017&cid=aba50cebb8f84fbead72cf7d26217a36&tc=1&sig=7126fddc67fda9cf9323acee9db4c135da8ea8093b11966db5724c47090fc8fa&pbs=c86aae29157541bf8c8f52dd1fc4f263
Comedy Central East: https://content-ause2-up-1.uplynk.com/channel/ceb8d6e35fca432f9f32f4f1f4a822b8/c.m3u8?ct=c&ad.locationDesc=vcbs_comedycentral_desktop_web_live&ad.cust_params=_fw_ae%3Da016e7e3817eec54180fba6a64ae6616%26_vmn_ar%3Dtrue&expand=simulcast_unified_standard&ad.kv=fms_userid,9ced60b0-bf5d-4b69-aacc-ac188122c87b,_fw_ae,a016e7e3817eec54180fba6a64ae6616,_vmn_ar,true,_fw_vcid2,9ced60b0-bf5d-4b69-aacc-ac188122c87b,fms_vcid2type,userid&exp=1684276758&rn=853902125&cid=ceb8d6e35fca432f9f32f4f1f4a822b8&tc=1&sig=8dda470d430da015bb9979cb1f6db9a1ecdfc69d52bcb0e7cf2097958b6d7019&pbs=e26eb848ce6d403cafea57451b6d8adc
I just couldnt find nick, must login to provider if have one if im missing something let me know
