### ISSUE TITLE
Broken: Animax

### ISSUE THREAD

**Issue by snfergy** [iptv-org/iptv#12851]
### Broken Link

https://redlabmcdn.s.llnwi.net/nv02/bs14hd/index.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f5365559e217acd3c352b0ffe54b5d95a9eb3ff6/streams/jp.m3u#L2-L3
