### ISSUE TITLE
Broken: AT-X

### ISSUE THREAD

**Issue by snfergy** [iptv-org/iptv#12852]
### Broken Link

http://rip.hidari.moe/get/jptv/get.php?id=X4_3qVMPUBpZMqO_hX4vBw==

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by snfergy** [comment]
Seems to be intermittent on whether it loads or not. Can't pinpoint any reason in particular.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f5365559e217acd3c352b0ffe54b5d95a9eb3ff6/streams/jp.m3u#L4-L5

**Comment by kaikyoofers** [comment]
"*Broken*:AT-X"

**Comment by Keyzro** [comment]
yeah it seems like every link going threw hidari.moe isn't working might be dead site.

**Comment by snfergy** [comment]
![image](https://github.com/iptv-org/iptv/assets/46796917/1afc365f-419f-4a26-aad2-4e12e1489dd7)
Seems to be working again at the moment.

**Comment by zhabi** [comment]
![image](https://github.com/iptv-org/iptv/assets/17227439/fc0516e5-6135-49f9-a68d-a0bfac6d8bc8)
seems because of the quata limitation?
