### ISSUE TITLE
problem with channel

### ISSUE THREAD

**Issue by asmita85** [iptv-org/iptv#1289]
not working blocked after few second of playing

Algeria

Samira Tv

**Broken Link:**
https://iptv-org.github.io/iptv/languages/ara.m3u

**Additional Information (optional):**

**Comment by Sphinxroot** [comment]
SamiraTV
http://95.170.215.109/hls/m3u8/SamiraTV-Backup.m3u8  tested and working

**Comment by SileC** [comment]
It plays 27 sec. and freezes. If restarted shows same sequence of 27 sec.

**Comment by Sphinxroot** [comment]
ok yes ive seen  sorry ,   might have problem whit the stream  ,only thing i get from the web site is http://41.111.166.173:8081/live/SAMIRA_TV/chunks.m3u8  but nothing come out  

event on casasat its only a replay  on the live feed  and youtube got a lot of replay over there
