### ISSUE TITLE
Broken: Various PBS Create Streams

### ISSUE THREAD

**Issue by baliebox4916** [iptv-org/iptv#12902]
### Stream Title

PBS Create Tallahasse FL (WFSU-TV3) and PBS 58 Create (KLCS-DT3) (Los Angeles CA)

### Playlist Link

https://iptv-org.github.io/iptv/categories/education.m3u

### What happened to the stream?

Not loading

### Notes (optional)

Used to Work But Now Both Create Streams Wont Load

I Know One is Geoblocked and i Live in Canada But the Other One Used to Work Fine But Now it Doesn't

I Used to Love Watching Bob Ross on Here When i Would go to Bed Back a Few Years Ago and i Really Miss It

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by clips519** [comment]
ya hard to get pbs ones in canada i can only get the pbs ket ones u know there is channels on pluto or samsung that are nothing but bob ross all day?

**Comment by baliebox4916** [comment]
i dont just watch bob ross, i also like the cooking and traveling shows on create as well

**Comment by BellezaEmporium** [comment]
All of those are geo-blocked and I believe those were on the last HLS streams to be still available.

Maybe those were DRMd.
