### ISSUE TITLE
Add: Waar Tv

### ISSUE THREAD

**Issue by Halliiz** [iptv-org/iptv#12901]
### Channel ID

WaarTV.iq

### Notes (optional)

Waar Tv is a kurdish channel can you add it please.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Halliiz** [comment]
Yes, it’s the right channel can you add it please?

Le 17 mai 2023 à 19:44, fraudiay79 ***@***.***> a écrit :

﻿

https://ca-rt.onetv.app/Waar/index-0.m3u8

**Comment by kaikyoofers** [comment]
I will add it
