### ISSUE TITLE
Add: RTL Zwee (LUX)

### ISSUE THREAD

**Issue by arecki2** [iptv-org/iptv#12919]
### Channel ID

RTLZwee.lu

### Stream URL (optional)

https://live-edge.rtl.lu/channel2/smil:channel2.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by vbHeiko** [comment]
It's geo-blocked ("this content is accessible from Grand Duchy of Luxembourg only")
- Tested from germany.

**Comment by arecki2** [comment]
Hmmm, it played nicely before 5pm yesterday, and again at the moment (9:28am), showing AtHomeTV at both times 🤔

**Comment by Smark223** [comment]
Correct. They geo-block Champions League coverage and maybe a few other things but it's mostly unrestricted.

**Comment by vbHeiko** [comment]
Tested from germany.Tested from germany.

**Comment by DJ1999-max** [comment]
We have link: https://iptv-org.github.io/?q=RTL%20Zw
