### ISSUE TITLE
Add: A News from Turkey

### ISSUE THREAD

**Issue by arecki2** [iptv-org/iptv#12916]
### Channel ID

ANews.tr

### Stream URL (optional)

https://trkvz-live.ercdn.net/anewshd/anewshd.m3u8

### Notes (optional)

English-language news channel from Turkey.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
https://www.youtube.com/channel/UC-LRBEUet4xX2fRB3JitFxg/live

https://yt.onrender.com/ = dont work

**Comment by freearhey** [comment]
https://trkvz-live.ercdn.net/anewshd/anewshd.m3u8 (Offline)
<img width="378" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/75ee14ba-fc0e-469f-8ef6-af15f2ba7e01">
