### ISSUE TITLE
Add: A Haber (Turkey)

### ISSUE THREAD

**Issue by arecki2** [iptv-org/iptv#12917]
### Channel ID

AHaber.tr

### Stream URL (optional)

https://trkvz-live.ercdn.net/ahaberhd/ahaberhd.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
https://www.youtube.com/channel/UCKQhfw-lzz0uKnE1fY1PsAA/live

https://yt.onrender.com/  dont work

**Comment by freearhey** [comment]
https://trkvz-live.ercdn.net/ahaberhd/ahaberhd.m3u8 (Offline)
<img width="391" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/71b178f6-21c2-4fae-8901-232b058da56a">

**Comment by freearhey** [comment]
Closed in favor of #12920
