### ISSUE TITLE
Broken:  NHK BS1 (480p)

### ISSUE THREAD

**Issue by snfergy** [iptv-org/iptv#12924]
### Stream Title

NHK BS1 (480p)

### Playlist Link

https://redlabmcdn.s.llnwi.net/nv02/bs01hd/index.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
https://redlabmcdn.s.llnwi.net/nv02/bs01hd/manifest.mpd
