### ISSUE TITLE
Broken: BS11

### ISSUE THREAD

**Issue by BoiledCabbage66** [iptv-org/iptv#12929]
### Stream Title

BS11

### Playlist Link

https://iptv-org.github.io/iptv/countries/jp.m3u

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/ae54389bbbe2cc8350172f5d21d0c7bbcb77b69d/streams/jp.m3u#L6-L7
