### ISSUE TITLE
Add: Canal 11 (PT)

### ISSUE THREAD

**Issue by Parsifaladas** [iptv-org/iptv#12922]
### Channel ID

Canal11.pt

### Please confirm the following

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
https://www.youtube.com/channel/UCMfEEaNYYX5w6nbvccTCHhg/live  not 24/7

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/pt.m3u#L80-L81
