### ISSUE TITLE
Add: A Haber (TUR) via YouTube

### ISSUE THREAD

**Issue by arecki2** [iptv-org/iptv#12920]
### Channel ID

AHaber.tr

### Stream URL (optional)

https://yt.onrender.com/channel/UCKQhfw-lzz0uKnE1fY1PsAA

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Carlinhos027** [comment]
https://ythls.onrender.com/channel/UCKQhfw-lzz0uKnE1fY1PsAA.m3u8

**Comment by arecki2** [comment]
Thanks for correction, I'm new to that service.
