### ISSUE TITLE
Broken: the whole Japan playlist is broken

### ISSUE THREAD

**Issue by ChiFungLam** [iptv-org/iptv#12935]
### Stream Title

all Japan channels are broken

### Playlist Link

https://iptv-org.github.io/iptv/countries/jp.m3u

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by ChiFungLam** [comment]
> If you're not afraid of popups & stuff, mov3.co has a few Japanese channels. These used to be listed in this playlist. Some were carried kinda by itself, others were set up through russian social network Odnoklassniki.
> 
> I'm just looking at them to save you from trouble 🙂: mov3.co/en and mov3.co/ja all have a dozen links essentially pointing to the same stream, just duplicated into several addresses: http://main1.mov3.co/hls/main.m3u8 http://main2.mov3.co/hls/main.m3u8 http://main3.mov3.co/hls/main.m3u8 ... http://main9.mov3.co/hls/main.m3u8
> 
> They all carry Nippon TV aka NIttele at the moment. They both have a sort of schedule updated daily so I guess that's the streaming schedule for this channel.
> 
> However, mov3.co main page, without extensions, gives us more goodness - links to streams of 7 terrestrial TV channels from Tokyo. Direct stream URLs at present are:
> 
> https://ntv4.mov3.co/hls/ntv.m3u8 - Nippon TV https://fujitv3.mov3.co/hls/fujitv.m3u8 - Fuji TV, but currently it's just a blank PotPlayer window with a playback failed message XD https://tbs3.mov3.co/hls/tbs.m3u8 - TBS https://nhk3.mov3.co/hls/nhk.m3u8 - NHK G (often identifies as JOAK-DTV around 19:00 UTC) TV Tokyo, TV Asahi and Tokyo MX run through Odnoklassniki.
> 
> These streams often suffer from issues. Sometimes audio drops out like crazy. Some channels look as if streamed at 360p or worse despite really in 540p. And sometimes playback of the station at the source goes AWOL, like mentioned with Fuji TV above.
> 
> Well, that's the best option we have now for Japanese TV...
> 
> UPDATE, perhaps only just roughly related to the above: looks like NTV News 24 stream (https://n24-cdn-live.ntv.co.jp/ch01/index.m3u8) has some SSL issues 🙄

Thanks a lot. Can use it while fixing the Japanese playlist.

**Comment by cherry0804** [comment]
TV Asahi

> If you're not afraid of popups & stuff, mov3.co has a few Japanese channels. These used to be listed in this playlist. Some were carried kinda by itself, others were set up through russian social network Odnoklassniki.
> 
> I'm just looking at them to save you from trouble 🙂: mov3.co/en and mov3.co/ja all have a dozen links essentially pointing to the same stream, just duplicated into several addresses: http://main1.mov3.co/hls/main.m3u8 http://main2.mov3.co/hls/main.m3u8 http://main3.mov3.co/hls/main.m3u8 ... http://main9.mov3.co/hls/main.m3u8
> 
> They all carry Nippon TV aka NIttele at the moment. They both have a sort of schedule updated daily so I guess that's the streaming schedule for this channel.
> 
> However, mov3.co main page, without extensions, gives us more goodness - links to streams of 7 terrestrial TV channels from Tokyo. Direct stream URLs at present are:
> 
> https://ntv4.mov3.co/hls/ntv.m3u8 - Nippon TV https://fujitv3.mov3.co/hls/fujitv.m3u8 - Fuji TV, but currently it's just a blank PotPlayer window with a playback failed message XD https://tbs3.mov3.co/hls/tbs.m3u8 - TBS https://nhk3.mov3.co/hls/nhk.m3u8 - NHK G (often identifies as JOAK-DTV around 19:00 UTC) TV Tokyo, TV Asahi and Tokyo MX run through Odnoklassniki.
> 
> These streams often suffer from issues. Sometimes audio drops out like crazy. Some channels look as if streamed at 360p or worse despite really in 540p. And sometimes playback of the station at the source goes AWOL, like mentioned with Fuji TV above.
> 
> Well, that's the best option we have now for Japanese TV...
> 
> UPDATE, perhaps only just roughly related to the above: looks like NTV News 24 stream (https://n24-cdn-live.ntv.co.jp/ch01/index.m3u8) has some SSL issues 🙄

TV Asahi mov3.co is down.
Is there any other way to watch?

**Comment by scapehips** [comment]
https://jpnews-video.com/iptv/ has many. Inspect to get m3u8 urls (i couldn't play them successfully myself, they require login)

**Comment by ChiFungLam** [comment]
> https://jpnews-video.com/iptv/ has many. Inspect to get m3u8 urls (i couldn't play them successfully myself, they require login)

none of those work for me... may need VPN to work :'-(

**Comment by scapehips** [comment]
Some streams are Willfonk, and some are Redlab. Use inspect to open the developer tools and go to the Network tab to see what the stream is. Also, Redlab ones don't work at the moment but I was able to view some Willfonk streams.

for example https://jpnews-video.com/iptv/BS朝日/3/ worked for me yesterday but https://jpnews-video.com/iptv/BS朝日/1/ didn't

**Comment by scapehips** [comment]
> > https://jpnews-video.com/iptv/ has many. Inspect to get m3u8 urls (i couldn't play them successfully myself, they require login)
> 
> none of those work for me... may need VPN to work :'-(

Oh and I forgot. You need this extension for the video streams to work ((it says on the website to install this) https://chrome.google.com/webstore/detail/cross-domain-cors/mjhpgnbimicffchbodmgfnemoghjakai/related?hl=ja

**Comment by ChiFungLam** [comment]
> > > https://jpnews-video.com/iptv/ has many. Inspect to get m3u8 urls (i couldn't play them successfully myself, they require login)
> > 
> > 
> > none of those work for me... may need VPN to work :'-(
> 
> Oh and I forgot. You need this extension for the video streams to work (it says on the website to install this) https://chrome.google.com/webstore/detail/cross-domain-cors/mjhpgnbimicffchbodmgfnemoghjakai/related?hl=ja

Oh... it works... some can play after install this, thanks.

**Comment by arecki2** [comment]
Can we add CORS support to the IPTV M3U playlists, and to VLC & any IPTV software? Or is it already done? So that these channels could be added to the playlists out there?

**Comment by ChiFungLam** [comment]
> Can we add CORS support to the IPTV M3U playlists, and to VLC & any IPTV software? Or is it already done? So that these channels could be added to the playlists out there?

may be this should be the job of IPTV software. I am using Tivimate on Smart TV/Android phone (and tablet), not sure it already has this feature or not.

**Comment by HimmelIIDX** [comment]
> TV Asahi
> 
> > If you're not afraid of popups & stuff, mov3.co has a few Japanese channels. These used to be listed in this playlist. Some were carried kinda by itself, others were set up through russian social network Odnoklassniki.
> > I'm just looking at them to save you from trouble 🙂: mov3.co/en and mov3.co/ja all have a dozen links essentially pointing to the same stream, just duplicated into several addresses: http://main1.mov3.co/hls/main.m3u8 http://main2.mov3.co/hls/main.m3u8 http://main3.mov3.co/hls/main.m3u8 ... http://main9.mov3.co/hls/main.m3u8
> > They all carry Nippon TV aka NIttele at the moment. They both have a sort of schedule updated daily so I guess that's the streaming schedule for this channel.
> > However, mov3.co main page, without extensions, gives us more goodness - links to streams of 7 terrestrial TV channels from Tokyo. Direct stream URLs at present are:
> > https://ntv4.mov3.co/hls/ntv.m3u8 - Nippon TV https://fujitv3.mov3.co/hls/fujitv.m3u8 - Fuji TV, but currently it's just a blank PotPlayer window with a playback failed message XD https://tbs3.mov3.co/hls/tbs.m3u8 - TBS https://nhk3.mov3.co/hls/nhk.m3u8 - NHK G (often identifies as JOAK-DTV around 19:00 UTC) TV Tokyo, TV Asahi and Tokyo MX run through Odnoklassniki.
> > These streams often suffer from issues. Sometimes audio drops out like crazy. Some channels look as if streamed at 360p or worse despite really in 540p. And sometimes playback of the station at the source goes AWOL, like mentioned with Fuji TV above.
> > Well, that's the best option we have now for Japanese TV...
> > UPDATE, perhaps only just roughly related to the above: looks like NTV News 24 stream (https://n24-cdn-live.ntv.co.jp/ch01/index.m3u8) has some SSL issues 🙄
> 
> TV Asahi mov3.co is down. Is there any other way to watch?

Also TV Tokyo in mov3.co is down, Is there any Alternative? 


> > > https://jpnews-video.com/iptv/ has many. Inspect to get m3u8 urls (i couldn't play them successfully myself, they require login)
> > 
> > 
> > none of those work for me... may need VPN to work :'-(
> 
> Oh and I forgot. You need this extension for the video streams to work (it says on the website to install this) https://chrome.google.com/webstore/detail/cross-domain-cors/mjhpgnbimicffchbodmgfnemoghjakai/related?hl=ja

Already try it but didn't work even i already try with extension

**Comment by solo489** [comment]
Are the streams fixed yet?

**Comment by HimmelIIDX** [comment]
> Are the streams fixed yet?

Not yet. Still waiting alternative for TV Tokyo since Redlab still broken and mov3.co is taken down.

**Comment by Johelectrix09** [comment]
After you remove those channels do you think obviously you're gonna look on
other streams??

**Comment by mj17shAlice** [comment]
> > TV Asahi
> > > If you're not afraid of popups & stuff, mov3.co has a few Japanese channels. These used to be listed in this playlist. Some were carried kinda by itself, others were set up through russian social network Odnoklassniki.
> > > I'm just looking at them to save you from trouble 🙂: mov3.co/en and mov3.co/ja all have a dozen links essentially pointing to the same stream, just duplicated into several addresses: http://main1.mov3.co/hls/main.m3u8 http://main2.mov3.co/hls/main.m3u8 http://main3.mov3.co/hls/main.m3u8 ... http://main9.mov3.co/hls/main.m3u8
> > > They all carry Nippon TV aka NIttele at the moment. They both have a sort of schedule updated daily so I guess that's the streaming schedule for this channel.
> > > However, mov3.co main page, without extensions, gives us more goodness - links to streams of 7 terrestrial TV channels from Tokyo. Direct stream URLs at present are:
> > > https://ntv4.mov3.co/hls/ntv.m3u8 - Nippon TV https://fujitv3.mov3.co/hls/fujitv.m3u8 - Fuji TV, but currently it's just a blank PotPlayer window with a playback failed message XD https://tbs3.mov3.co/hls/tbs.m3u8 - TBS https://nhk3.mov3.co/hls/nhk.m3u8 - NHK G (often identifies as JOAK-DTV around 19:00 UTC) TV Tokyo, TV Asahi and Tokyo MX run through Odnoklassniki.
> > > These streams often suffer from issues. Sometimes audio drops out like crazy. Some channels look as if streamed at 360p or worse despite really in 540p. And sometimes playback of the station at the source goes AWOL, like mentioned with Fuji TV above.
> > > Well, that's the best option we have now for Japanese TV...
> > > UPDATE, perhaps only just roughly related to the above: looks like NTV News 24 stream (https://n24-cdn-live.ntv.co.jp/ch01/index.m3u8) has some SSL issues 🙄
> > 
> > 
> > TV Asahi mov3.co is down. Is there any other way to watch?
> 
> Also TV Tokyo in mov3.co is down, Is there any Alternative?
> 
> > > > https://jpnews-video.com/iptv/ has many. Inspect to get m3u8 urls (i couldn't play them successfully myself, they require login)
> > > 
> > > 
> > > none of those work for me... may need VPN to work :'-(
> > 
> > 
> > Oh and I forgot. You need this extension for the video streams to work (it says on the website to install this) https://chrome.google.com/webstore/detail/cross-domain-cors/mjhpgnbimicffchbodmgfnemoghjakai/related?hl=ja
> 
> Already try it but didn't work even i already try with extension

Try global proxy.

**Comment by carbonatedturtle** [comment]
It's so disappointing to see that this playlist has been totally gutted, and even the few channels that are left don't all work. My wife is Japanese and she really enjoyed being able to watch Japanese TV again after moving to Canada, so hopefully everything eventually comes back.

**Comment by dchengmu** [comment]
we need a solution please

**Comment by olstern01** [comment]
https://jpnews-video.com is down :'( the only choices I have now is the playlist here or mov3.co. Thankfully the playlist works on Chrome after allowing insecure content on the site settings.

**Comment by AnthonyChuc1996** [comment]
Please add AT-X Anime Channel, Toei channel back on playlist, please it's been awhile.
