### ISSUE TITLE
Add: DraftKings Network [US]

### ISSUE THREAD

**Issue by LPhilip1999** [iptv-org/iptv#12943]
### Channel ID

DraftKingsNetwork.us

### Stream URL (optional)

https://dknation.draftkings.com/pages/draftkings-network

### Notes (optional)

This is the 24/7 video livestream of DraftKings Network, but need an direct m3u8 link please

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by theadder** [comment]
Seems to be it:

https://stream-us-east-1.getpublica.com/playlist.m3u8?network_id=5078

**Comment by trancer1994** [comment]
https://stream-us-east-1.getpublica.com/playlist.m3u8?network_id=5078&live=1&avod=1&site_page=https%3A%2F%2Fdraftkings.com&site_name=DraftKings&content_lang=en&content_cat=IAB1-7&content_genre=Sports&hls_marker=1

**Comment by R4IN2007** [comment]
https://draftkings-sgrewind.streamguys1.com/sgrewind/DraftKings_StreamGuys_SRT/playlist.m3u8
