### ISSUE TITLE
Broken:  TOKYO MX 1 Question

### ISSUE THREAD

**Issue by DaveS43** [iptv-org/iptv#12940]
### Stream Title

TOKYO MX 1

### Playlist Link

https://movie.mcas.jp/mcas/mx1_2/chunklist.m3u

### What happened to the stream?

Other

### Notes (optional)

All I see is this photo (rougly translates to "MM Casting, preparing for delivery"

Same with https://movie.mcas.jp/mcas/mx1_2/master.m3u8

Resulting in: https://ibb.co/XD98DSG

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by DaveS43** [comment]
Tried several times, I finally got to watch some for about an hour, then it switched to the same message above (It seems it keeps switching between live tv to that message, odd)

**Comment by BellezaEmporium** [comment]
This is the "free" MX Casting stream for both TMX 1 and 2.

The 2nd aims to be casting way more because MX1 is broadcasting more copyrighted content than the 2nd channel.

When it says "ready for delivery", it's simply copyright protection.

**Comment by vbHeiko** [comment]
For me the stream is not broken - the 
program is just [Not 24/7]
and the "broken stream " label isn't correct.

**Comment by DaveS43** [comment]
Thanks
