### ISSUE TITLE
Add: JTV (Indonesian TV channel)

### ISSUE THREAD

**Issue by xx1182** [iptv-org/iptv#12944]
### Channel ID

JTV.jav

### Stream URL (optional)

https://m.vidio.com/live/9713-jtv

### Notes (optional)

I have no clue, but, I was very high and learned that Javanese is a language, technically JTV is in Javanese; also the Indonesian.m3u(by language) contains a JTV but it's like not the main one(+1, +2 ecc) and is not up 24/7

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
https://app-etslive-2.vidio.com/live/9713/master.m3u8?auth=+Token

**Comment by isaffathir** [comment]
https://live-production.secureswiftcontent.com/exp=1685340079~acl=/hls-p/ingest_9713_*/*~hmac=ed71bf6612c1a7d84eb7303baabbbcf67b0fe208e5578cc9d565b07e9b78b843/hls-p/ingest_9713_720p/index.m3u8
