### ISSUE TITLE
Add: CNN International 

### ISSUE THREAD

**Issue by jhedfors** [iptv-org/iptv#12942]
### Channel ID

CNNInternational.us

### Stream URL (optional)

https://d30x5vsa85tvmd.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-7y561g9sa9uht/index.m3u8

### Notes (optional)

But that this is different from CNN US.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by jhedfors** [comment]
Alternate stream:
https://cnn-cnninternational-1-eu.rakuten.wurl.tv/playlist.m3u8

**Comment by LPhilip1999** [comment]
![Screenshot_2023-05-20-09-44-35-74_013dba30cae4674f6b0947ea3c272499](https://github.com/iptv-org/iptv/assets/107766357/d533953e-6409-4641-bcff-389bc298eea5)
@jhedfors  I saw it that this is Europe feed of CNNi.

**Comment by freearhey** [comment]
https://iptv-org.github.io/?q=CNNInternational
