### ISSUE TITLE
Add: Fox Sports [US]

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#12946]
### Channel ID

FoxSports.us

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
We cannot add this channel to the playlist due to claims of the copyright holder.

https://github.com/iptv-org/database/blob/b9bd3ed0bd93cb8a755ed1cf1468f9f566211ba0/data/blocklist.csv#L387
