### ISSUE TITLE
Broken: ERT World stream is actually a relay by someone in the US; here's a link to ERT World:

### ISSUE THREAD

**Issue by arecki2** [iptv-org/iptv#12952]
### Stream Title

ERT World (1080p)

### Playlist Link

https://cbd537474fbad4634b64787657ff6456.msvdn.net/ertworld/ert_world_main/mainabr/playlist_dvr.m3u8

### What happened to the stream?

Shows the wrong channel

### Notes (optional)

The listed http://wpso.com:1936/hls/wzra.m3u8 stream does relay some ERT content but interrupts it with some local US advertising. The stream link I provide has been taken from ERT's official streaming platform, curiously named ERTflix, and is not geoblocked.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
Works for me.
