### ISSUE TITLE
Broken: Adult Swim

### ISSUE THREAD

**Issue by kagc** [iptv-org/iptv#12961]
### Stream Title

Adult Swim East (720p)

### Playlist Link

https://iptv.org.github.io/iptv/languages/eng.m3u

### What happened to the stream?

Not loading

### Notes (optional)

It's both Adult Swim East (720p) and Adult Swim West (720p) and the corresponding Cartoon Network East TVE Feed (720p) and Cartoon Network West TVE Feed (720p) channels, for over a week now.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by SkylerDaKat** [comment]
Alternate links were found in #12804 just scroll down a little, you'll find the adult swim channels there, still looking for the rest, hope this helps

**Comment by kagc** [comment]
> Alternate links were found in #12804 just scroll down a little, you'll find the adult swim channels there, still looking for the rest, hope this helps

Thank you so much, they work perfectly!

**Comment by kagc** [comment]
> > > Alternate links were found in #12804 just scroll down a little, you'll find the adult swim channels there, still looking for the rest, hope this helps
> > 
> > Thank you so much, they work perfectly!
> No problem!
> 
> (P.S. I recommend you shut down this ticket)

Thanks, sorry about that. For some reason I thought the comment also closed it, but it's closed now.

**Comment by SkylerDaKat** [comment]
> > > > Alternate links were found in #12804 just scroll down a little, you'll find the adult swim channels there, still looking for the rest, hope this helps
> > > 
> > > 
> > > Thank you so much, they work perfectly!
> > > No problem!
> > 
> > 
> > (P.S. I recommend you shut down this ticket)
> 
> Thanks, sorry about that. For some reason I thought the comment also closed it, but it's closed now.

Lol no need to apologize, was just saying,
Have a great day!
