### ISSUE TITLE
Add: Teletica Costa Rica

### ISSUE THREAD

**Issue by mariorgonzalezo22** [iptv-org/iptv#12967]
### Channel ID

Teletica7.cr

### Notes (optional)

Hi, I would like to request to add teletica channel 7 from costa rica

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
Referer=https://bradmax.com

geoblocked
https://cdn01.teletica.com/TeleticaLiveStreamCR/Stream/playlist_dvr.m3u8  - 403

https://6zklxk9bdw9b-hls-live.5centscdn.com/TeleticaLiveStreamCR/d072c3a8dde8622c607ecd258fd628e8.sdp/playlist_dvr.m3u8 = 403

**Comment by BellezaEmporium** [comment]
https://cdn01.teletica.com/TeleticaLiveStream/Stream/TeleticaLiveStream/Stream7live1/chunks_dvr.m3u8 Works if you use the referer given above.
