### ISSUE TITLE
Add: VoA TV [US]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12965]
### Channel ID

VoATV.us

### Stream URL (optional)

https://voa-ingest.akamaized.net/dash/live/2033875/tvmc06/manifest.mpd

### Notes (optional)

1080p

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LPhilip1999** [comment]
I see it that the broadcast feed of VOA was from the Africa continent.

Alternate HLS stream for VOA TV Africa: https://voa-ingest.akamaized.net/hls/live/2033874/tvmc06/playlist.m3u8
