### ISSUE TITLE
Add: Kurdistan channel

### ISSUE THREAD

**Issue by Kurdishiptv** [iptv-org/iptv#12972]
### Channel ID

iptv-org.github.io

### Stream URL (optional)

https://github.com/BotanAtomic/Kurdistan-TV/blob/master/canal.txt

### Notes (optional)

Hello, a tab for Kurdish channels is missing you can add a tab in languages ​​for Kurdish language and a tab for countries for Kurdistan

I found a mu3 list which may be useful to you :
https://github.com/BotanAtomic/Kurdistan-TV/blob/master/canal.txt

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by zaxozaxo121314-blip** [comment]
https://github.com/BotanAtomic/Kurdistan-TV/blob/master/canal.txt
