### ISSUE TITLE
Add: NTN24 [CO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#12976]
### Channel ID

NTN24.co

### Stream URL (optional)

https://ythls.onrender.com/channel/UCEJs1fTF3KszRJGxJY14VrA.m3u8

### Notes (optional)

720p

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://ythls.onrender.com/channel/UCEJs1fTF3KszRJGxJY14VrA.m3u8 (Offline)
<img width="499" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/80e3f394-eaeb-4696-a7ab-0d7fc812fbc2">

**Comment by azgaresncf** [comment]
https://www.dailymotion.com/player/metadata/video/x7w4okl?embedder=https%3A%2F%2Fwww.ntn24.com%2F&geo=1&player-id=xd8pw&locale=fr&dmV1st=&dmTs=&is_native_app=0 
?
