### ISSUE TITLE
Broken: Stêrk TV

### ISSUE THREAD

**Issue by Kurdishiptv** [iptv-org/iptv#12986]
### Stream Title

SterkTV (1080p) [Not 24/7]

### Playlist Link

https://602ccc850c9bb.streamlock.net/sterktv/smil:sterk.smil/playlist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
<img width="1412" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/d3b979c0-5884-4328-a0a1-95fa6157b6d3">

**Comment by Kurdishiptv** [comment]
Test

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/ae54389bbbe2cc8350172f5d21d0c7bbcb77b69d/streams/be.m3u#L46-L47

**Comment by Kurdishiptv** [comment]
This don’t work : https://602ccc850c9bb.streamlock.net/sterktv/smil:sterk.smil/playlist.m3u8
