### ISSUE TITLE
Add: Shamshad

### ISSUE THREAD

**Issue by Kurdishiptv** [iptv-org/iptv#12992]
### Channel ID

ShamshadTV.af

### Stream URL (optional)

https://5a1178b42cc03.streamlock.net/shamshadtelevision/shamshadtelevision/chunklist_w153395850.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
https://5a1178b42cc03.streamlock.net/shamshadtelevision/shamshadtelevision/index.m3u8 adaptive
