### ISSUE TITLE
Add: CBS Sports Golazo Network [US]

### ISSUE THREAD

**Issue by genvara** [iptv-org/iptv#13007]
### Channel ID

CBSSportsGolazoNetwork.us

### Notes (optional)

I don't have the stream URLs, however the channel is being broadcast in the following services:

https://www.cbssports.com/watch/cbs-sports-golazo-network

https://pluto.tv/en/live-tv/golazo-network

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by elvinag6** [comment]
> ### Channel ID
> CBSSportsGolazoNetwork.us
> 
> ### Stream URL (optional)
> _No response_
> 
> ### Notes (optional)
> I don't have the stream URLs, however the channel is being broadcast in the following services:
> 
> https://www.cbssports.com/watch/cbs-sports-golazo-network
> 
> https://pluto.tv/en/live-tv/golazo-network
> 
> ### Please confirm the following
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

M3U8
https://dai.google.com/linear/hls/pa/event/7f3Wv6f7QEKfQna22jHqLQ/stream/3bdb10c8-adce-4595-bd06-0aa9cd2c2c51:MRN2/master.m3u8

**Comment by azgaresncf** [comment]
tokened stream...

**Comment by valmnt** [comment]
> updated link https://dai.google.com/linear/hls/pa/event/GxrCGmwST0ixsrc_QgB6qw/stream/827909c2-5f00-4b54-bd1d-c0c718491de3:TUL/master.m3u8

Not working

**Comment by Sphinxroot** [comment]
might be not 24/7

#EXTINF:-1 tvg-logo="" group-title="",Golazo Network
https://dai.google.com/linear/hls/event/GxrCGmwST0ixsrc_QgB6qw/master.m3u8

#EXTINF:-1 tvg-logo="" group-title="",Golazo Network
https://i.mjh.nz/PlutoTV/63a0e33a45264d000850ed7e-alt.m3u8

**Comment by valmnt** [comment]
> https://dai.google.com/linear/hls/event/GxrCGmwST0ixsrc_QgB6qw/master.m3u8

It works !

**Comment by azgaresncf** [comment]
ah oui, merci !

> > https://dai.google.com/linear/hls/event/GxrCGmwST0ixsrc_QgB6qw/master.m3u8
> 
> It works !

**Comment by reecepsteward** [comment]
Dead link. Update.
