### ISSUE TITLE
Some sorting info for Unsorted playlist.

### ISSUE THREAD

**Issue by cyb3rm4n** [iptv-org/iptv#1300]
I know some channel countries from Unsorted.m3u playlist, here it is:
ABC NEWS - US
CBS News - US (link's broken)
Create & Craft TV - UK
Realitalia TV - Italy
TVM3 - Switzerland 
Voice Of America - US
Матч! - Russia
СТБ - Ukraine
78 канал - Russia
8 канал - Russia
TV BRICS - Russia
Hit Muscic Channel - Hungary
M1 Classic - Ukraine
M1 Hits - Ukraine
M1 Hip-Hop - Ukraine
Red Bulll TV - International.
Ulto TV - Russia

More channels - soon.

**Comment by freearhey** [comment]
So you can help us sort the channels into the appropriate playlists 👍

If you don't know exactly how to do it, here's a guide: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#sort-channels-by-country
