### ISSUE TITLE
Broken: Algerian Channel Not Working

### ISSUE THREAD

**Issue by udemws** [iptv-org/iptv#13008]
### Stream Title

Ennahar Tv Echourouk Tv

### Playlist Link

https://iptv-org.github.io/iptv/index.dz.m3u

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by udemws** [comment]
the fix not working for me can you try it please

**Comment by UltraHDR** [comment]
The github.io links refreshes every night. You can use https://raw.githubusercontent.com/iptv-org/iptv/master/streams/dz.m3u directly until it updates.

**Comment by freearhey** [comment]
@UltraHDR Since we can no longer use GitHub Actions the playlists are no longer updated daily. Until a replacement is found I try to post updates manually at least once a week, but there is no exact schedule anymore.

**Comment by udemws** [comment]
even if i use your url github  or i play the playlist with my computer not working

**Comment by UltraHDR** [comment]
The file works with VLC. The player needs to support the "#EXTVLCOPT:http-referrer=" feature. What player are you using?

**Comment by udemws** [comment]
i'am using vlc and nothing work. i have my file contain exemple this Channel and using vlc and nothing happen when i satrt to read it
<img width="613" alt="Capture d’écran 2023-05-29 211335" src="https://github.com/iptv-org/iptv/assets/134815517/8e665c16-6154-4b5e-b852-d349733d84e5">
<img width="471" alt="Capture d’écran 2023-05-29" src="https://github.com/iptv-org/iptv/assets/134815517/b9fd1d37-ae80-4f82-9619-09c82dabe540">

**Comment by UltraHDR** [comment]
Try watching it via the websites, otherwise you need a VPN
https://www.ennaharonline.com/live/
https://www.echoroukonline.com/live
https://www.echoroukonline.com/live-news
