### ISSUE TITLE
Broken: UAFirst.ua

### ISSUE THREAD

**Issue by DzuyCuong** [iptv-org/iptv#13013]
### Stream Title

UA: Перший

### Playlist Link

https://suspilne-online.netlify.app/suspilne.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
This link is not in the playlists.
