### ISSUE TITLE
Está caído el enlace, se busca por favor win sports +, pero pocos enlaces lo tienen, éste es uno de esos pero sigue caído Broken: 

### ISSUE THREAD

**Issue by Canner47** [iptv-org/iptv#13015]
### Stream Title

Win sports + caído 

### Playlist Link

http://181.236.192.254:8000/playlist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
Este caso fue repuestando en asunto https://github.com/iptv-org/iptv/issues/2301
