### ISSUE TITLE
Add: TV Osaka

### ISSUE THREAD

**Issue by solo489** [iptv-org/iptv#13016]
### Channel ID

TVOsaka.jp

### Stream URL (optional)

https://iptv-org.github.io/iptv/countries/jp.m3u

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Duplicate of #13014
