### ISSUE TITLE
Japanese channels! 

### ISSUE THREAD

**Issue by jokerq8** [iptv-org/iptv#1303]
**Country of the channel:**
Japan

**Channel Name:**

Fuji TV
TV Tokyo
Nippon TV
TV Asahi
NHK
TV Japan
TX Network

**Channel Language:**
Japanese 

**Additional Information (optional):**

Please make my dream true before I die lol, 
And big thanks for all great job u do guys.

**Comment by kimbrasil** [comment]
> **Country of the channel:**
> Japan
> 
> **Channel Name:**
> 
> Fuji TV
> TV Tokyo
> Nippon TV
> TV Asahi
> NHK
> TV Japan
> TX Network
> 
> **Channel Language:**
> Japanese
> 
> **Additional Information (optional):**
> 
> Please make my dream true before I die lol,
> And big thanks for all great job u do guys.

They don't provide official feeds and Japan have solid policies for copyrights, probably you'll need to subscribe for IPTV providers, a few of them are legal.

**Comment by jokerq8** [comment]
> > **Country of the channel:**
> > Japan
> > **Channel Name:**
> > Fuji TV
> > TV Tokyo
> > Nippon TV
> > TV Asahi
> > NHK
> > TV Japan
> > TX Network
> > **Channel Language:**
> > Japanese
> > **Additional Information (optional):**
> > Please make my dream true before I die lol,
> > And big thanks for all great job u do guys.
> 
> They don't provide official feeds and Japan have solid policies for copyrights, probably you'll need to subscribe for IPTV providers, a few of them are legal.

Thx for your reply.. So sad.

**Comment by freearhey** [comment]
TV Tokyo:
https://github.com/iptv-org/iptv/blob/aaaecae7eab3233e10e190de0bc7cab0f331481e/channels/jp.m3u#L26-L27

NHK World Japan:
https://github.com/iptv-org/iptv/blob/aaaecae7eab3233e10e190de0bc7cab0f331481e/channels/jp.m3u#L14-L15

**Comment by freearhey** [comment]
Closed in favor #1938

**Comment by Animenosekai** [comment]
> > **Country of the channel:**
> > Japan
> > **Channel Name:**
> > Fuji TV
> > TV Tokyo
> > Nippon TV
> > TV Asahi
> > NHK
> > TV Japan
> > TX Network
> > **Channel Language:**
> > Japanese
> > **Additional Information (optional):**
> > Please make my dream true before I die lol,
> > And big thanks for all great job u do guys.
> 
> They don't provide official feeds and Japan have solid policies for copyrights, probably you'll need to subscribe for IPTV providers, a few of them are legal.

One of them is legal in Europe, JSTV. But they have like a single 50€ plan with only one channel that isn't even a Japanese Channel, just a broadcasting of programs they have bought.
