### ISSUE TITLE
Broken: ca.m3u | Disney Channel Canada

### ISSUE THREAD

**Issue by semihofc** [iptv-org/iptv#13036]
### Stream Title

Disney Channel Canada

### Playlist Link

https://github.com/iptv-org/iptv/issues/6331#issue-1123617609

### What happened to the stream?

Not loading

### Notes (optional)

Doesnt work anymore

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
The link is no longer in the playlist.
