### ISSUE TITLE
Broken: TV Tokyo

### ISSUE THREAD

**Issue by lankkypants** [iptv-org/iptv#13055]
### Broken Link

http://redlabmcdn.s.llnwi.net/nv02/ryowa6hd/index.m3u8

### What happened to the stream?

Other

### Notes (optional)

The channel has been removed from the playlist, is there any way to put it back on?

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
We will of course put it back on the playlist as soon as there is a working link to the stream.
