### ISSUE TITLE
Add: LNK [LT]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/iptv#13057]
### Channel ID

LNK.lt

### Stream URL (optional)

http://88.216.83.245/lnk/index.m3u8

### Notes (optional)

Stream Works!

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Zorklis** [comment]
Broken?

**Comment by DJ1999-max** [comment]
Right now is broken.
