### ISSUE TITLE
Add: NickToons East [US]

### ISSUE THREAD

**Issue by JerkyHockey** [iptv-org/iptv#13067]
### Channel ID

NicktoonsEast.us

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
dupicate of https://github.com/iptv-org/iptv/issues/13035

**Comment by JerkyHockey** [comment]
found it! 

NickToons East [
](https://p-dynaman.movetv.com/manifest/619/widevine/master.m3u8?account_status=active&billing_zip=33809&brand=sling&device_model=Chrome&device_name=browser&location_zip=33809&os_name=Chromium%20OS&os_version=14816.131.0&qvt=https%3A//cbd46b77.cdn.cms.movetv.com/playermetadata/sling/v1/api/channels/1233cf02e4764aa8a04bf5eef4b05618/current/schedule.qvt&subscriber_id=ce12b6d2-389a-11ee-ad0b-0e21bd08a531&support_mode=false&playback_delay=53&client_session_id=cf13a22a-0dfd-4261-971e-fbebe886989a&dma=539)

**Comment by JerkyHockey** [comment]
https://p-dynaman.movetv.com/manifest/619/widevine/master.m3u8?account_status=active&billing_zip=33809&brand=sling&device_model=Chrome&device_name=browser&location_zip=33809&os_name=Chromium%20OS&os_version=14816.131.0&qvt=https%3A//cbd46b77.cdn.cms.movetv.com/playermetadata/sling/v1/api/channels/1233cf02e4764aa8a04bf5eef4b05618/current/schedule.qvt&subscriber_id=ce12b6d2-389a-11ee-ad0b-0e21bd08a531&support_mode=false&playback_delay=53&client_session_id=cf13a22a-0dfd-4261-971e-fbebe886989a&dma=539
