### ISSUE TITLE
Broken: LRT Lituanica [LT]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/iptv#13070]
### Broken Link

https://lituanica-dvr.lrt.lt/lrt-ndvr/hls/lituanica_720p/index.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by DJ1999-max** [comment]
> https://github.com/iptv-org/iptv/blob/480d016c5c829534603d68560740775455b80898/streams/lt.m3u#L4-L5

Yes, it moved to new stream.

**Comment by Sphinxroot** [comment]
https://www.lrt.lt/mediateka/tiesiogiai/lrt-lituanica
https://2828893a06d840908e93dd6445500984.dlvr1.net/lituanica/master.m3u8

**Comment by DJ1999-max** [comment]
> https://github.com/iptv-org/iptv/blob/480d016c5c829534603d68560740775455b80898/streams/lt.m3u#L4-L5

But wait since March 2023, channel has starting airing HD (1080p), but only internet.

**Comment by DJ1999-max** [comment]
> https://www.lrt.lt/mediateka/tiesiogiai/lrt-lituanica https://2828893a06d840908e93dd6445500984.dlvr1.net/lituanica/master.m3u8

No need, but need remove, the old link and fix to 1080p.
