### ISSUE TITLE
Add: beIN Sports 1 France

### ISSUE THREAD

**Issue by Kurdishiptv** [iptv-org/iptv#13074]
### Channel ID

beINSports1France.fr

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
We cannot add the channel to the playlist due to claims of the copyright holder: https://github.com/iptv-org/database/blob/master/data/blocklist.csv#L35
