### ISSUE TITLE
Add: Discovery ID

### ISSUE THREAD

**Issue by Valchrist23** [iptv-org/iptv#13076]
### Channel ID

Discovery ID 

### Notes (optional)

hey guys, can someone help me. 
I found some live streams but they have the audio and video separated in 2 urls however i dont know how to join them.

these are the 2 urls:

Discovery ID
https://food-dlvr-ott.akamaized.net/primary/3/d31abde936de4fa884fbd91054dacad3/index_14.m3u8
https://food-dlvr-ott.akamaized.net/primary/3/d31abde936de4fa884fbd91054dacad3/index_11_0.m3u8

If anyone is interested i found these streams in this web page:

https://mhdtvworld.me/channel/english/

Discovery ID URL
https://mhdtvworld.me/live/investigation-discovery-discplus/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by djancukers** [comment]
create m3u file on gist or other

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="eng",NAME="English",AUTOSELEC T=YES,DEFAULT=YES,URI="https://food-dlvr-ott.akamaized.net/primary/3/d31abde936de4fa884fbd91054dacad3/index_11_0.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2000000,AUDIO="URI"
https://food-dlvr-ott.akamaized.net/primary/3/d31abde936de4fa884fbd91054dacad3/index_14.m3u8


the end is like this
https://gist.githubusercontent.com/djancukers/d8a829b269d93ed5e4604e158318faa1/raw/a6ae1ba1a4b3b30ee957607493a4646d9652613b/Discovery_ID.m3u
