### ISSUE TITLE
Broken: Aniplus

### ISSUE THREAD

**Issue by rizkidewanto** [iptv-org/iptv#13085]
### Broken Link

http://210.210.155.37/dr9445/h/h02/index.m3u8

### What happened to the stream?

Stuck at a single frame

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f243f612c1b8dbed3a3903a0b70136188a4b364c/streams/sg.m3u#L2-L3

**Comment by rizkidewanto** [comment]
![image](https://github.com/iptv-org/iptv/assets/46876786/7a1806b2-cd11-450b-9674-bd6fd2de423b)
It stuck at this frame
