### ISSUE TITLE
Add MBC 5

### ISSUE THREAD

**Issue by saidma** [iptv-org/iptv#1310]
**Country of the channel:**
Morocco 
UAE

**Channel Name:**
MBC 5

**Channel Language:**
Arabic

**Additional Information (optional):**

The channel is based in the United Arab Emirates (a subsidiary of MBC) but its TV programs are aimed at the Maghreb public. 
Link: 
https://shahid.mbc.net/ar/livestream/MBC5/livechannel-387937

**Comment by freearhey** [comment]
The channel is already on the playlist:
https://github.com/iptv-org/iptv/blob/1076413ecd41bebb26572cc11e03ebb99244eb3e/channels/ae.m3u#L124-L125
