### ISSUE TITLE
Broken: Music On!

### ISSUE THREAD

**Issue by Hanamino** [iptv-org/iptv#13106]
### Broken Link

http://rip.hidari.moe/get/jptv/get.php?id=6eHaPTJd0NoBEwN6E9jArw==

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Thanks for the report! The broken link has been removed from the playlist.

**Comment by Johelectrix09** [comment]
ouch I thought they just closed it I enjoyed it for a while 😞😞
