### ISSUE TITLE
Broken: W14DK-D 14.7 Heartland Channel

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#13115]
### Broken Link

https://2-fss-2.streamhoster.com/pl_118/amlst:204972-3078008/playlist.m3u8

### What happened to the stream?

No sound

### Notes (optional)

https://github.com/iptv-org/iptv/blob/488bb091188a2c6132b2c3aacda5728f6fd2bf9f/streams/us.m3u#L910-L911

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
#EXTINF:-1 ,Heartland Channel 14.7
https://2-fss-2.streamhoster.com/pl_118/amlst:204972-3078008/playlist.m3u8

work here
