### ISSUE TITLE
Broken: The Heartland Network

### ISSUE THREAD

**Issue by poltom30** [iptv-org/iptv#13113]
### Broken Link

https://bcovlive-a.akamaihd.net/1ad942d15d9643bea6d199b729e79e48/us-east-1/6183977686001/playlist.m3u8

### What happened to the stream?

Stuck at a single frame

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/bf0130e6d1ab313b2d9611cebc46a36abf572bbf/streams/us.m3u#L408-L409
