### ISSUE TITLE
Most Algerian channels don't work

### ISSUE THREAD

**Issue by saidma** [iptv-org/iptv#1311]
**What's wrong?**
Most Algerian channels don't work
Also missing the official tv channels

**Country of the channels:** 
Algeria 

**Channel Name:**
https://www.lyngsat.com/freetv/Algeria.html

**Broken Link:**

**Additional Information (optional):**

**Comment by freearhey** [comment]
Thank you for noticing! 

I've already removed all the broken links, but as soon as a replacement appears we will add them back.
