### ISSUE TITLE
Broken: W14DK-D 14.7 Heartland Channel

### ISSUE THREAD

**Issue by poltom30** [iptv-org/iptv#13114]
### Broken Link

https://2-fss-2.stream/playlist.m3u8

### What happened to the stream?

Other

### Notes (optional)

No sound at all.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
The broadcast doesn't work for me at all:
<img width="269" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/76db784e-e2df-4ad7-872d-2c07601e69b8">

**Comment by poltom30** [comment]
Its working (with VLC, MX Player, Wuffy) but without audio.

Sent from Yahoo Mail on Android 
 
  On H, jún. 5, 2023 at 20:17, Aleksandr ***@***.***> wrote:   


The broadcast doesn't work for me at all:
