### ISSUE TITLE
Fix:Channel name is not standard 频道名称不标准

### ISSUE THREAD

**Issue by jiehu0992** [iptv-org/iptv#13129]
### Describe your issue

https://iptv-org.github.io/iptv/index.nsfw.m3u I noticed that the Chinese channel names in it are very non-standard and confusing. The same channel has English, Chinese, and the same channel in Chinese The variety of channel names has brought great trouble to sorting and storing. For example, the standard name of "JiangsuSatelliteTV.cn" should be "Jiangsu Satellite TV", but there are channels in the form of "JiangsuSatelliteTV.cn", "JiangsuSatelliteTV", "JiangsuSatelliteTV", " JiangsuSatellite tv.cn" "Jiangsu TV", "Jiangsu", "Jiangsu Satellite Channel"...
https://iptv-org.github.io/iptv/index.nsfw.m3u  我注意到里面的中文频道名称非常不标准，并且很混乱，同一频道，有英文的，有中文的，有同一频道中文频道名称多样化的，给整理入库带来了非常大的麻烦，如“JiangsuSatelliteTV.cn”标准名称应该为“江苏卫视”，但里面却存在形如“JiangsuSatelliteTV.cn”、“JiangsuSatelliteTV”、“JiangsuSatellite tv.cn”"江苏台"、“江苏”、“江苏卫星频道”……

**Comment by freearhey** [comment]
I found only one link in this playlist to `JiangsuSatelliteTV.cn` and it has a Chinese name:

https://iptv-org.github.io/iptv/index.nsfw.m3u
```
#EXTINF:-1 tvg-id="JiangsuSatelliteTV.cn" tvg-logo="https://i.imgur.com/CA4F1rv.png" group-title="Undefined",江苏卫视 (1080p)
http://39.134.115.163:8080/PLTV/88888910/224/3221225702/index.m3u8
```

Also all names for Chinese channels are taken from [streams/cn.m3u](https://github.com/iptv-org/iptv/blob/master/streams/cn.m3u) file in which they are only in Chinese:

https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/cn.m3u#L288-L309
