### ISSUE TITLE
Broken: Kapamilya Channel

### ISSUE THREAD

**Issue by sandinoleal** [iptv-org/iptv#13122]
### Broken Link

https://ythls.onrender.com/channel/UCstEtN0pgOmCf02EdXsGChw.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Broken: "Kapamilya Channel" FROM CATEGORY COUNTRY PHILIPPINES IS NOT LOADING

the link: https://ythls.onrender.com/channel/UCstEtN0pgOmCf02EdXsGChw.m3u8   is broken, it should be gotten the new m3u8 link from the next public working source

https://youtu.be/doxsUEc4_z4

https://www.youtube.com/watch?v=doxsUEc4_z4

<iframe width="560" height="315" src="https://www.youtube.com/embed/doxsUEc4_z4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
The link indeed does not work although the broadcast is live.

<img width="401" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/6c0798ef-a9fc-4f0b-8b13-a2dee56bb1dc">

https://www.youtube.com/watch?v=doxsUEc4_z4
<img width="1122" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/b070ae4e-c87a-4b8a-ac84-770a046b23e3">


https://github.com/iptv-org/iptv/blob/48637ae9d05d4d73cfed0b1eccaf8368945d1bc6/streams/ph.m3u#L14-L15

**Comment by Sphinxroot** [comment]
i get geoblocked  stream

**Comment by freearhey** [comment]
I couldn't get the stream to start either via the US VPN or the Filipino one

**Comment by LPhilip1999** [comment]
@freearhey It's a Kapamilya Online Live, the online streaming service from ABS-CBN, and can be shown on YouTube and Facebook

**Comment by sandinoleal** [comment]
Yes, it is thrickey, question: why even though it is a public streaming in
youtube and it is watchable  outside from the Philippines, why It cannot
been converted to m3u8 for being used in IPTV list?
