### ISSUE TITLE
Add: Canal de Las Estrellas | [MX]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#13149]
### Channel ID

LasEstrellas.mx

### Stream URL (optional)

https://channel01-onlymex.akamaized.net/hls/live/2022749/event01/index.m3u8

### Notes (optional)

Stream works fine with a México VPN IP
![Screenshot_20230610_132945_VLC](https://github.com/iptv-org/iptv/assets/83226646/1aef307b-7f1f-430f-b377-2b9860e7f9c3)
So the Vix.com linear link might be International 
Linear Version:
![Screenshot_20230610_133636_VLC](https://github.com/iptv-org/iptv/assets/83226646/238ce126-eae7-466d-812c-5fd31e940ffa)
https://linear-416.frequency.stream/416/hls/master/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
International : https://channel01-notusa.akamaized.net/hls/live/2022749/event01/index.m3u8

**Comment by R4IN2007** [comment]
Just removing (onlymex) from the link works fine for me in the US

**Comment by BellezaEmporium** [comment]
> Just removing (onlymex) from the link works fine for me in the US

Works too.

**Comment by R4IN2007** [comment]
http://190.61.102.67:2000/play/a00g/index.m3u8
![Screenshot_20230611_124918_VLC](https://github.com/iptv-org/iptv/assets/83226646/dde87345-d2e1-45ef-bcf7-8c1fe792655d)

**Comment by evllz** [comment]
Tried different options, unable to stream from California, US

**Comment by r4inIsBack** [comment]
> Tried different options, unable to stream from California, US

Not possible to watch in California especially in the US. Did you tried using a VPN using a MX IP?
