### ISSUE TITLE
Search engine?

### ISSUE THREAD

**Issue by piranna** [iptv-org/iptv#1314]
Could it be possible to create a search engine? A pure client-side web app that filter the channels would be enough. As a plus, a button to download the list of the channels that match the query :-)

Side note: is the data available as JSON, or would it make sense? That would make it easier to do... but if the m3u8 files can be parsed, it could be done on the fly too.

**Comment by freearhey** [comment]
I created a list of all channels in JSON format: https://iptv-org.github.io/iptv/channels.json
More details: https://github.com/iptv-org/iptv#for-developers

I hope this helps.

**Comment by piranna** [comment]
Great! :-D

**Comment by freearhey** [comment]
By the way, here is an app by @detroitenglish that allows you to combine multiple playlists into a new one: https://channelizer.tv/

**Comment by piranna** [comment]
> By the way, here is an app by @detroitenglish that allows you to combine multiple playlists into a new one: [channelizer.tv](https://channelizer.tv/)

That looks nice, thank you :-)
