### ISSUE TITLE
Broken: VarzeshTV.ir

### ISSUE THREAD

**Issue by barfin** [iptv-org/iptv#13147]
### Broken Link

http://cdn1.live.irib.ir:1935/channel-live/smil:varzesh/playlist.m3u8

### What happened to the stream?

Shows looped video

### Notes (optional)

the second link is also broken but the third one is good
basically these two are bad links and should be removed:
~~#EXTINF:-1 tvg-id="VarzeshTV.ir",Varzesh (1080p)~~
~~http://cdn1.live.irib.ir:1935/channel-live/smil:varzesh/playlist.m3u8~~
~~#EXTINF:-1 tvg-id="VarzeshTV.ir",VARZESH (1080p)~~
~~http://cdn1.live.irib.ir:1935/live-channels/smil:varzesh/playlist.m3u8~~

and this is the good link and should stay:
#EXTINF:-1 tvg-id="VarzeshTV.ir",Varzesh
https://af.ayas.ir/hls2/varzeshtv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
AFAIK, from Yandex's rough translation it seems it was intentionally locked ? Message seems to say "We are not able to show you the current content due to copyright issues."

**Comment by barfin** [comment]
> AFAIK, from rough translation it seems it was intentionally locked ? Message seems to say "It is currently not possible to broadcast this network based on copyright laws."

Yes thats what it says, i couldnt get it to work with any ip, iranian or not

**Comment by BellezaEmporium** [comment]
> > AFAIK, from rough translation it seems it was intentionally locked ? Message seems to say "It is currently not possible to broadcast this network based on copyright laws."
> 
> Yes thats what it says, i couldnt get it to work with any ip, iranian or not

The working link says "Welcome to Ayas TV", though I have no information whatsoever on this provider or host. Is it a governmental organisation, or owned by third parties who seems to (kind of) counter the restrictions ?
