### ISSUE TITLE
Broken: EMT Media TV [US]

### ISSUE THREAD

**Issue by LPhilip1999** [iptv-org/iptv#13153]
### Broken Link

https://mediaplatform.streamingmediahosting.com/p/14135/sp/1413500/playManifest/entryId/0_lkq7fay8/format/applehttp/protocol/https/uiConfId/6710347/a.m3u8?referrer=aHR0cHM6Ly9lbXRtZWRpYXR2LmNvbQ==&playSessionId=85851bc0-fd37-a365-4004-da87b1d0035e

### What happened to the stream?

Not loading

### Notes (optional)

Live stream of EMT Media TV is not working until now. Please kindly re-check to https://emtmediatv.com/watch-live-tv/ then inspect element to the new HLS stream. Thank you.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
This link has already been removed from the playlist.

**Comment by LPhilip1999** [comment]
Please @freearhey but need the new HLS link to EMT Media TV
