### ISSUE TITLE
Add: Ecuavisa | [Ecuador]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#13152]
### Channel ID

Ecuavisa.ec

### Stream URL (optional)

https://mdstrm.com/live-stream-playlist/6089d0a7f61e11081f8c832a.m3u8

### Notes (optional)

Stream works fine with a EC VPN IP
![Screenshot_20230610_142928_Chrome](https://github.com/iptv-org/iptv/assets/83226646/ebf1b550-25f4-414d-a3da-c343e7d56c40)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
works with a French IP (for now)
