### ISSUE TITLE
Add:  Canal 22 | [MX]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#13151]
### Channel ID

Canal22Nacional.mx

### Stream URL (optional)

https://5fc584f3f19c9.streamlock.net/canal22/smil:canal22.smil/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9My8yNC8yMDIzIDg6MTI6MTQgUE0maGFzaF92YWx1ZT1QTUJuUHAraFpxTVdJNGViWFUyVjVnPT0mdmFsaWRtaW51dGVzPTUmaWQ9

### Notes (optional)

Stream works fine with México VPN IP
![Screenshot_20230610_141121_Chrome](https://github.com/iptv-org/iptv/assets/83226646/d1194b3e-12f9-47b6-ba4b-bfffebbf8260)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Conceptoweb ? The issue is that the token changes.
