### ISSUE TITLE
Broken: Dreiko TV | DreikoTV.pa

### ISSUE THREAD

**Issue by EnerGeekTeam** [iptv-org/iptv#13163]
### Broken Link

https://tv.fullhd-streaming.com:3807/live/dreikotvlive.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Dreiko TV owner announced he changed stream url.

New URLs are:
- https://cloudvideo.servers10.com:8081/8138/index.m3u8
- https://wifiexpert-1.energeek.cl/dreikotv/canal-1/playlist.m3u8 (acts as backup)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://wifiexpert-1.energeek.cl/dreikotv/canal-1/playlist.m3u8 (no image, only sound)
<img width="786" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/1ec24147-74bf-4b65-92a9-2a63689a478c">
