### ISSUE TITLE
Channel Request

### ISSUE THREAD

**Issue by Siam0097** [iptv-org/iptv#1317]
# India 
## 2.SAB TV ( Hindi )
# America 
## 1.Disney XD  ( English )

Please add these chanels

**Comment by yitxyitx** [comment]
![download](https://user-images.githubusercontent.com/64719403/80898418-d8d1b480-8d0b-11ea-8413-bd57c934275f.png)
![ad](https://user-images.githubusercontent.com/64719403/80898420-da9b7800-8d0b-11ea-8723-a722950093e7.jpg)
Please add those philippine channels. Much appreciated

**Comment by Siam0097** [comment]
Will this channels be add?

**Comment by freearhey** [comment]
If there is a link to a working channel stream, we will of course add it to the playlist.
