### ISSUE TITLE
Broken: Avang TV

### ISSUE THREAD

**Issue by Weirdo1312** [iptv-org/iptv#13184]
### Broken Link

http://appavang.flashmediacast.com:1935/Appavang/livestream/chunklist_w913855439.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

The official and working link (not geo-blocked and accessible in Iran):
https://hls.avang.live/hls/stream.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by barfin** [comment]
also for some reason this channel doesn't show up in persian language category
