### ISSUE TITLE
Add:  Canal 5 | [MX]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#13188]
### Channel ID

Canal5.mx

### Stream URL (optional)

http://190.61.102.67:2000/play/a038/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Lucoasan** [comment]
They should add Azteca 7 from Mexico too

**Comment by GiovanniSebastian** [comment]
And this link: https://dcs3-live.mp.lura.live/server/podserve/0reOeoiedmKNcBD7/manifest.m3u8?gam_stream_id=[[STREAMID]]&encp=YZ2LKuFd32ZZFdwjDh_Alg:_KKGfYtryX6kjNf6iNpDsQkSTSgVlfwNnsCI8ivDDRLtSwy77-1VM9S9q6vqwYE-h1qNeRDGMG6O0IN6rmxlymsLEW4ZJuS8Kb20oEWzX0Ip4hU6lPChsBhxvlRs7tiVEdy_j_tMb_fOlTkr9tUhNBpHxt5R0H-duGF0eBtDdRWN7hA5H4OR2NwIyuM32VeglCJcccCEcf0IiXk0V7RJtdqceLZ57rQucCmiMhtWAdq2odSiwXnKSC4nxxPeVQ0Dv_EKJjUYX8b4c2zJsv_KsR6reLNd8dr0TZR2FEzGwHG0saQEAK6_yjAu65mtA_OssVXiodO-e4tBYbltsWkNMzz-lvKuf8FWy_YH6b-UHXG5l9XN0McmPtL_GucFCK58aAzOKvcR-rU59NsYTs6VGoY6j3CCYNJ5A97-R1HFBmSlG8dJaoVZB6tXGsMw4deE5z9Qzi5xNKYmwWkGVtTMmr07DxSQ0EIxkrQFPRwIahvGD5-DGNrjCFZMvJHl5o_slaZnBlHL3WFb1F9xHyKmAL0QHHJVPmVnLK53QKLm8uCyLhSe-TOB1vHaTnR5d6I0dcuM7FYNe68CEIpKFnTUzZ6PrdYVEaNHbdT2QsNjUu1J3f_DmUKXOQc-ebNTve_EaWAzEpClmKkJn7qjr0a0YGpmVQPrMuXJZxBRQDuIf6Fkp_2yRefulQNJghJFcB8wUJ-5fDi2xoX8CMGpsyR7vOvshyH8Tt3p6xNP-e-wvyIRYfEzZ1eyRzInRkRLR4-jVoZqixjhr84iYJBRl0nM2HFg-RloYIKWyYoRTRUSWwv94TX8sDS16BqJGZk6nCb-Rwbtz7vBJvYuyjFAfAgwVYbIsFU4nBO1yPsv9SpCIfOjte2RJdGHfYwGl75VJS2XXkMFIFxhubXb27iXnIbdUuydzkuHYjCW6jEnksFeY1tZjc4yftz2suTpDNkAzbE5oUnDaAY-LMpD0Yi9vi5USeTCVzXJokj3624Ss8mop0M&anvtrid=f2a0b45dde58659b6299860a9cf38e4e&anvauth=tb=0~te=1689646869~sgn=d90ee7cdacd59c7a3f2a713714c2b09d4787a1961d223ed784762d5350a32cbf&t=1689646779

Original Source: https://nicelinks.webcindario.com/
