### ISSUE TITLE
Add: BandaMax | [MX]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#13189]
### Channel ID

Bandamax.mx

### Stream URL (optional)

http://190.61.102.67:2000/play/a08h/index.m3u8

### Notes (optional)

Stream works fine only a little low quality 
![Screenshot_20230611_125521_Chrome](https://github.com/iptv-org/iptv/assets/83226646/5b82f0a3-f1ec-4d07-8800-d3364d52c1e3)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Astra panel

Playlist : http://190.61.102.67:2000/playlist.m3u8
