### ISSUE TITLE
Add: Italia 7 | [Italy]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#13199]
### Channel ID

Italia7.it

### Stream URL (optional)

https://streaming.softwarecreation.it/Italia7/Italia7/playlist.m3u8

### Notes (optional)

Stream works fine 

![Screenshot_20230611_190847_Chrome](https://github.com/iptv-org/iptv/assets/83226646/2a520188-cf7d-408f-a3ed-f6ef120cdeb6)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by R4IN2007** [comment]
Another Italia7 m3u8 link
https://sportitaliaamd.akamaized.net/video_0/ITALIA_7/hls/9B42C4E8F0359D3888FF7E429FCE1485811E4E83/index.m3u8
![Screenshot_20230613_171646_Chrome](https://github.com/iptv-org/iptv/assets/83226646/74b6ea35-33dc-42fa-8c00-a86ab78c7a84)

**Comment by kaikyoofers** [comment]
> Another Italia7 m3u8 link https://sportitaliaamd.akamaized.net/video_0/ITALIA_7/hls/9B42C4E8F0359D3888FF7E429FCE1485811E4E83/index.m3u8 ![Screenshot_20230613_171646_Chrome](https://user-images.githubusercontent.com/83226646/245622953-74b6ea35-33dc-42fa-8c00-a86ab78c7a84.jpg)

That link does not work, it is tokened
