### ISSUE TITLE
Broken: TN8 Nicaragua

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#13211]
### Broken Link

https://60417ddeaf0d9.streamlock.net/tn8/videotn8/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://www.tn8.tv/en-vivo/

### Notes (optional)

With Token

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
streamlink pipe https://conceptoweb-studio.com/radio/video/tn8/

send to kodi addon as well

token 10m ip hash

**Comment by BellezaEmporium** [comment]
> 

Note that only my fork of streamlink has a plugin for conceptoweb. The original source doesn't.
