### ISSUE TITLE
pueden añadir canal red

### ISSUE THREAD

**Issue by jesusvlc** [iptv-org/iptv#13222]
### Channel ID

canal red tv 

### Stream URL (optional)

https://canalred.tv/

### Notes (optional)

pueden añadir canal red nose sacar la m3u de youtube. Muchas gracias

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by ztreamhd** [comment]
Canal Red no emite en directo en su página web, y lo hace muy de vez en cuando a través de su canal de YouTube. De todas maneras, supongo que si quieres tener un enlace a los directos de este canal, podrías conseguirlo de esta manera:

``#EXTINF:-1,tvg-id="CanalRed.es" tvg-name="Canal Red [Not 24/7]" tvg-logo="https://canalred.tv/wp-content/uploads/2023/02/logo-canal-red.svg" group-title="Política",Canal Red [Not 24/7]
https://ythls.onrender.com/channel/UC3PhLH0Rj2e_-0hNvwTLxGA.m3u8``

Saludos.
