### ISSUE TITLE
Broken: TF1 (fr.m3u)

### ISSUE THREAD

**Issue by pokemaster974** [iptv-org/iptv#13224]
### Broken Link

https://live-tf1-hls-dai.cdn-1.diff.tf1.fr/out/v1/c2e382be3aa2486e8753747e7bb6157e/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

```
Failed to resolve hostname live-tf1-hls-dai.cdn-1.diff.tf1.fr: The name does not resolve for the supplied parameters
https://live-tf1-hls-dai.cdn-1.diff.tf1.fr/out/v1/c2e382be3aa2486e8753747e7bb6157e/index.m3u8: I/O error
```

For information, the owner (TF1 group) have made changes about their flux.
Softwares like captvty cannot record their channels anymore.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
> ### Broken Link
> 
> https://live-tf1-hls-dai.cdn-1.diff.tf1.fr/out/v1/c2e382be3aa2486e8753747e7bb6157e/index.m3u8
> ### What happened to the stream?
> 
> Not loading
> ### Possible Replacement (optional)
> 
> _No response_
> ### Notes (optional)
> 
> ```
> Failed to resolve hostname live-tf1-hls-dai.cdn-1.diff.tf1.fr: The name does not resolve for the supplied parameters
> https://live-tf1-hls-dai.cdn-1.diff.tf1.fr/out/v1/c2e382be3aa2486e8753747e7bb6157e/index.m3u8: I/O error
> ```
> 
> For information, the owner (TF1 group) have made changes about their flux. Softwares like captvty cannot record their channels anymore.
> ### Please confirm the following
> 
>     * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

They began implementing a JWT token way of functioning across their sensitive APIs. Now, they enforced the need to have an account in order to get the link, and you only can get the DASH url, nothing else. They've dropped the last servers that still had HLS in order to push their last streaming validation system (which needs the previously mentioned JWT token). Basically, unless you rely on illegal sources, it's a RIP.

**Comment by Sphinxroot** [comment]
#EXTINF:-1 ,TF1
#EXTVLCOPT:http-referrer=http://www.callofliberty.fr/tv/1-TF1/1-TF1.php
http://www.callofliberty.fr/stream/TF1/manifest.m3u8

Kodi 
#EXTINF:-1 ,TF1
http://www.callofliberty.fr/stream/TF1/manifest.m3u8|Referer=http://www.callofliberty.fr/tv/1-TF1/1-TF1.php
