### ISSUE TITLE
Philippine Movie Channels: Cinema One, Cinema One Global and Viva TV

### ISSUE THREAD

**Issue by yitxyitx** [iptv-org/iptv#1322]
![2](https://user-images.githubusercontent.com/64719403/80908123-f3188c00-8d25-11ea-8c1c-992822225dd1.jpg)
![1](https://user-images.githubusercontent.com/64719403/80908127-f7dd4000-8d25-11ea-986f-6142f94672ac.png)
![3](https://user-images.githubusercontent.com/64719403/80908128-fca1f400-8d25-11ea-9eaa-8e1e74156c6c.jpg)

**Country of the channel:**

**Channel Name:** Cinema One, Cinema One Global  and Viva TV

**Channel Language:** Tagalog-Filipino

**Additional Information (optional):** Movie Channels in Philippines

**Comment by freearhey** [comment]
Closed in favor #1967

**Comment by arielguevarra868-tech** [comment]
No comment

**Comment by arielguevarra868-tech** [comment]
No comment

**Comment by arielguevarra868-tech** [comment]
Very good
