### ISSUE TITLE
Broken: All AL_Tring channels

### ISSUE THREAD

**Issue by eurohunter** [iptv-org/iptv#13239]
### Broken Link

https://mfe01.tring.al/delta/106/out/u/896_3.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Looks like Tring removed access to their channels:

#EXTINF:-1 tvg-id="3Plus.al",3 Plus (1080p)
https://mfe01.tring.al/delta/106/out/u/896_3.m3u8
#EXTINF:-1 tvg-id="ABCNewsAlbania.al",ABC News Albania (720p)
https://mfe01.tring.al/delta/105/out/u/650_1.m3u8
#EXTINF:-1 tvg-id="BubbleTV.al",Bubble TV
https://mfe01.tring.al/delta/106/out/u/1118_3.m3u8
#EXTINF:-1 tvg-id="Kanali7.al",Kanali 7 (576p)
https://mfe01.tring.al/delta/105/out/u/581_1.m3u8
#EXTINF:-1 tvg-id="LivingHD.al",Living HD (720p)
https://mfe01.tring.al/delta/106/out/u/894_1.m3u8
#EXTINF:-1 tvg-id="RTSH1.al",RTSH 1 (540p)
https://mfe01.tring.al/delta/105/out/u/643_1.m3u8
#EXTINF:-1 tvg-id="Teve1.xk",Tëvë1
https://mfe01.tring.al/delta/105/out/u/694_1.m3u8
#EXTINF:-1 tvg-id="TringClassic.al",Tring Classic
https://mfe01.tring.al/delta/106/out/u/1114_3.m3u8
#EXTINF:-1 tvg-id="TringCollection.al",Tring Collection
https://mfe01.tring.al/delta/106/out/u/1117_3.m3u8
#EXTINF:-1 tvg-id="TringFantasy.al",Tring Fantasy
https://mfe01.tring.al/delta/106/out/u/1115_3.m3u8
#EXTINF:-1 tvg-id="TringFantasy.al",Tring Fantasy (SD)
https://mfe01.tring.al/delta/106/out/u/1116_3.m3u8
#EXTINF:-1 tvg-id="TringNovelas.al",Tring Novelas (720p)
https://mfe01.tring.al/delta/106/out/u/1126_3.m3u8
#EXTINF:-1 tvg-id="TringSuper.al",Tring Super (1080p)
https://mfe01.tring.al/delta/106/out/u/890_1.m3u8
#EXTINF:-1 tvg-id="TringTring.al",Tring Tring (1080p)
https://mfe01.tring.al/delta/106/out/u/898_3.m3u8
#EXTINF:-1 tvg-id="VizionPlus.al",Vizion Plus
https://mfe01.tring.al/delta/105/out/u/618_13.m3u8
#EXTINF:-1 tvg-id="VizionPlus.al",Vizion Plus
https://mfe01.tring.al/delta/105/out/u/619_13.m3u8
#EXTINF:-1 tvg-id="VizionPlus.al",Vizion Plus
https://mfe01.tring.al/delta/105/out/u/621_13.m3u8
#EXTINF:-1 tvg-id="VizionPlus.al",Vizion Plus
https://mfe01.tring.al/delta/105/out/u/622_13.m3u8
#EXTINF:-1 tvg-id="ZjarrTV.al",Zjarr TV
https://mfe01.tring.al/delta/106/out/u/284_1.m3u8
#EXTINF:-1 tvg-id="ZjarrTV.al",Zjarr TV (alt)
https://mfe01.tring.al/delta/106/out/u/285_1.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by dantheman121** [comment]
wdym? its working just fine for me

**Comment by BellezaEmporium** [comment]
You might be talking about the newly added channels, as those do not work.
