### ISSUE TITLE
Rename: Adithya TV to Adithya Music

### ISSUE THREAD

**Issue by AadithyanRaju** [iptv-org/iptv#13236]
### Stream URL

https://ythls.onrender.com/channel/UCNApqoVYJbYSrni4YsbXzyQ.m3u8

### Channel ID

AdithyaTV.in

### Notes (optional)

Adithya TV is a comedy channel.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
The link already has this ID.
