### ISSUE TITLE
Add: Canal Pro [PY]

### ISSUE THREAD

**Issue by thelmagali** [iptv-org/iptv#13247]
### Channel ID

CanalPro.py

### Stream URL (optional)

https://usher.ttvnw.net/api/channel/hls/canalpropy.m3u8?acmb=e30%3D&allow_source=true&fast_bread=true&p=7499409&play_session_id=da23be2e5a33c05cae7788eec013101f&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=6c3262287ffa56cf613ad7259fec02473a6c88bf&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22canalpropy%22%2C%22channel_id%22%3A913322166%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%22858814f4396c9508%22%2C%22expires%22%3A1686944983%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22site%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3Anull%2C%22user_ip%22%3A%22181.94.231.8%22%2C%22version%22%3A2%7D&transcode_mode=cbr_v2&cdm=wv&player_version=1.20.0

### Notes (optional)

The URL was taken from this twitch channel: https://www.twitch.tv/canalpropy

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
well, since the majority of the servers that hosted the projects are down, here's mine 

http://mc-qs.lanesh4d0w.tech/iptv-query?streaming-ip=https://twitch.tv/canalpropy
