### ISSUE TITLE
Add: T7 [XK]

### ISSUE THREAD

**Issue by eurohunter** [iptv-org/iptv#13241]
### Channel ID

T7.xk

### Stream URL (optional)

https://ub1doy938d.gjirafa.net/live/dCynrjRK8sEsrYu0zDtDg8l4KaXbFpXl/yzg0yt.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Carlinhos027** [comment]
Link doesn't work

**Comment by eurohunter** [comment]
Apparently, it has changed. The new link is:
https://ub1doy938d.gjirafa.net/live/Gfsqdsr7FewrYClU3ACEGZvCHktt2wse/yzg0yt.m3u8

I wonder if it changes constantly

**Comment by eurohunter** [comment]
Apparently, the website keeps changing the link for this channel. The link won't work.
