### ISSUE TITLE
Add: Gen [PY] 

### ISSUE THREAD

**Issue by thelmagali** [iptv-org/iptv#13248]
### Channel ID

Gen.py

### Stream URL (optional)

https://copacogen.desdeparaguay.net/gentv/gentv_py_baja/playlist.m3u8?k=49b1057aed3a0c22b3375a8edf1adc19a4a22fc7692f2cc38693b9a4e4b64ccd&exp=1686944340

### Notes (optional)

Stream URL taken from their website: https://www.gen.com.py/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://copacogen.desdeparaguay.net/gentv/gentv_py_baja/playlist.m3u8?k=49b1057aed3a0c22b3375a8edf1adc19a4a22fc7692f2cc38693b9a4e4b64ccd&exp=1686944340
![image translated (1)](https://github.com/iptv-org/iptv/assets/7253922/f8bb0185-2503-41f5-a718-39df22915c08)

**Comment by BellezaEmporium** [comment]
https://github.com/BellezaEmporium/streamlink/blob/master/src/streamlink/plugins/desdeparaguay.py
