### ISSUE TITLE
Add: super one hd {hu)

### ISSUE THREAD

**Issue by erich1997** [iptv-org/iptv#13267]
### Channel ID

SuperOne.hu 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
https://tv.livechannels.xyz:30443/iptv/superone/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Ni8xOC8yMDIzIDg6MjY6NTggUE0maGFzaF92YWx1ZT1rOWVzbG1iamVzK3RtL3oxb0VZRGpnPT0mdmFsaWRtaW51dGVzPTYw

**Comment by erich1997** [comment]
http://84.17.61.203:8086/udp/238.2.25.83:1234
