### ISSUE TITLE
Broken: Talk TV not working

### ISSUE THREAD

**Issue by EpicYann10** [iptv-org/iptv#13271]
### Broken Link

https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00738-newsuk-talkradiotv-ono/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

The channel is not working, it was working yesterday.

it should be easy to find a new m3u link as you can watch it live on thier website
https://watch.talk.tv/live/1153

### Please confirm the following

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Broken link removed from playlist.

**Comment by EpicYann10** [comment]
I found a new link:
https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1687289371/ei/u6mRZLiKFq-sxN8Pq-i_sAY/ip/5.42.130.255/id/p7jawJD0DQM.1/source/yt_live_broadcast/requiressl/yes/tx/24698583/txs/24698582%2C24698583%2C24698584%2C24698585%2C24698586%2C24698587%2C24698588/hfr/1/playlist_duration/30/manifest_duration/30/maxh/4320/maudio/1/siu/1/spc/qEK7B8Yl9IWvvJIQfYvfmoIHDmMy7B571OCpanbXyUMBxkLIoaP50k8/vprv/1/go/1/pacing/0/nvgoi/1/keepalive/yes/fexp/24007246/beids/24350017/dover/11/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cplaylist_duration%2Cmanifest_duration%2Cmaxh%2Cmaudio%2Csiu%2Cspc%2Cvprv%2Cgo%2Citag%2Cplaylist_type/sig/AOq0QJ8wRQIhAP24n2I46y9-6rRNKpPAkrC9QDCbokyvpjLPUZDKHRx4AiB5z5-rc7sIhmlGe0pJf1GefQremdlj3-wjVd3hDHo5GQ%3D%3D/file/index.m3u8

**Comment by fotvnetwork** [comment]
YouTube feed
https://ythls.onrender.com/channel/UCm0yTweyAa0PwEIp0l3N_gA.m3u8
