### ISSUE TITLE
Broken: TVes (pe_opencaster.m3u)

### ISSUE THREAD

**Issue by CleanUpThoseLinks** [iptv-org/iptv#13273]
### Broken Link

https://rundle.deta.dev/hls/LIVE$TVes.ve/6.m3u8/Level(19012010)?end=END&start=LIVE

### What happened to the stream?

Not loading

### Notes (optional)

"Service No Longer Available" according to website.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by GiovanniSebastian** [comment]
https://ls.tves.gob.ve/hls/tves.m3u8
