### ISSUE TITLE
Broken: France - TF1

### ISSUE THREAD

**Issue by benoithamet** [iptv-org/iptv#13274]
### Broken Link

https://live-tf1-hls-dai.cdn-1.diff.tf1.fr/out/v1/c2e382be3aa2486e8753747e7bb6157e/index.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
FR : Ca va être compliqué au vu de la situation (nouveaux changements sur l'API - JWT requis pour se connecter au stream).

EN : It's going to be complicated due to the current situation (new API changes - JWT required to connect to the stream).

**Comment by Sphinxroot** [comment]
https://github.com/iptv-org/iptv/issues/13224
