### ISSUE TITLE
Broken: Disney Channel Japan

### ISSUE THREAD

**Issue by IseyJay** [iptv-org/iptv#13275]
### Broken Link

https://redlabmcdn.s.llnwi.net/jp01/bs13hd/tracks-v1a1/mono.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
The link has already been removed from the playlist.
