### ISSUE TITLE
Broken: NHK World Premium [JP]

### ISSUE THREAD

**Issue by LPhilip1999** [iptv-org/iptv#13288]
### Broken Link

https://nhkwlive-pre-in.webcdn.stream.ne.jp/hls/live/nhkwlive-pre/index_1M.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

There's a not loading as of this time.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by robocopz** [comment]
https://cdn.skygo.mn/live/disk1/NHK_World_Premium/HLSv3-FTA/NHK_World_Premium.m3u8
