### ISSUE TITLE
Rename: EnerGeekAnimate.cl (old) to CCPRadio.cl | CCP Radio

### ISSUE THREAD

**Issue by JustSammyV** [iptv-org/iptv#13289]
### Stream URL

https://wifiexpert-1.energeek.cl/energeek/canal-3/playlist.m3u8

### Correct ID

EnerGeekAnimate.cl

### Notes (optional)

Hello, i am one of the managers over at EnerGeek @EnerGeekTeam @EnerGeekTV .

EnerGeek Animate has been discontinued and completely restructured to a new channel called CCP Radio.
Along with a change of logo which i leave a link aswell https://cdn.energeek.cl/imgs/CCPRadio.jpg

Thanks.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
This link is not in our playlists.

If you want to add a new link please use this [form](https://github.com/iptv-org/iptv/issues/new?assignees=&labels=channel+request&projects=&template=------channel-request.yml&title=Add%3A+).

If you only want to update the name of the channel, you can do it by leaving a request [here](https://github.com/iptv-org/database/issues/new?assignees=&labels=channels%3Aedit&projects=&template=channels_edit.yml&title=Edit%3A+).
