### ISSUE TITLE
Broken: no working in china

### ISSUE THREAD

**Issue by okFancy** [iptv-org/iptv#13285]
### Broken Link

https://iptv-org.github.io/iptv/index.m3u

### What happened to the stream?

Not loading

### Notes (optional)

hello, no working in china.  I am using VLC to test

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
What's not working ? The chinese channels or the playlist URL itself ?
