### ISSUE TITLE
Add: Alalam News Channel Syria [SY]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#13292]
### Channel ID

AlalamNewsChannelSyria.sy

### Stream URL (optional)

https://live2.presstv.ir/live/alam/Playlist.m3u8

### Notes (optional)

576p

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by UltraHDR** [comment]
Already in https://github.com/iptv-org/iptv/blob/master/streams/ir.m3u#L6
