### ISSUE TITLE
Add: WAPA-DT1

### ISSUE THREAD

**Issue by LivingBuzzard55** [iptv-org/iptv#13296]
### Channel ID

WAPADT1.us

### Stream URL (optional)

https://live.field59.com/wapa/wapa1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LivingBuzzard55** [comment]
please remove from united states and add to puerto rico since wapa is a puerto rico channel

**Comment by BellezaEmporium** [comment]
WAPA (WTIN in satellite) is a Telemundo-affiliated antenna in San Juan, Puerto Rico. Since it is owned by the US for PR, it is put as an US channel (country of origin).

**Comment by idanny76** [comment]
The stream is currently not working. Is there a new streaming link?

**Comment by zimbababo** [comment]
@Carlinhos027  Good Morning ✌️ Do you have an updated 2024 for WAPA-DT1? My regards from Texas.

**Comment by LivingBuzzard55** [comment]
@zimbababo Yes

http://streamsy.online:2999/Jaley1990/L6KomjzBxv/127

**Comment by zimbababo** [comment]
> @zimbababo Yes
> 
> http://streamsy.online:2999/Jaley1990/L6KomjzBxv/127

@Carlinhos027 I put the .m3u8 at the end but didn't open in my IPTV player. I was trying to put my mother in law Super Chef Celebrities.

**Comment by idanny76** [comment]
> @zimbababo Try without the .m3u8 and with another iptv player

Try https://site.naicom.com/

**Comment by zimbababo** [comment]
> @zimbababo Try without the .m3u8 and with another iptv player



> @zimbababo Try without the .m3u8 and with another iptv player

Thank you very much is working now. Have a nice evening.

**Comment by zimbababo** [comment]
> > @zimbababo Try without the .m3u8 and with another iptv player
> 
> Try https://site.naicom.com/

Thank you very much is working now. Have a nice evening. ✌️
