### ISSUE TITLE
Add: CCPRadio.cl | CCP Radio

### ISSUE THREAD

**Issue by JustSammyV** [iptv-org/iptv#13294]
### Channel ID

CCPRadio.cl

### Stream URL (optional)

https://wifiexpert-1.energeek.cl/energeek/canal-3/playlist.m3u8

### Notes (optional)

From issue [database/#4057](https://github.com/iptv-org/database/issues/4057) and #13289 .

This is the only working link for CCPRadio.cl (formerly known as EnerGeekAnimate.cl)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Thank you for the updates. We will take care of it ASAP.
