### ISSUE TITLE
Fix: Puerto Rico Channels in United States Playlist

### ISSUE THREAD

**Issue by LivingBuzzard55** [iptv-org/iptv#13298]
### Describe your issue

Move the following channels from United States Playlist to Puerto Rico Playlist
These channels may be confused with us channels because Puerto Rico is a territory of United States.
Name                       TVG-ID
WKAQ-DT1              WKAQDT1.us
WKAQ-DT2              WKAQDT2.us
WKAQ-DT3              WKAQDT3.us
WAPA-DT1               WAPADT1.us
WAPA-DT2               WAPADT2.us
WAPA-DT3               WAPADT3.us
WORA-DT2              WORADT2.us
WIPR-DT1                 WIPRDT1.us
WIPR-DT2                 WIPRDT2.us
WRUA-DT1                WRUADT1.us
WORO-DT1                WORODT1.us
WSBS-DT1                 WSBSDT1.us
WMTJ-DT1                 WMTJDT1.us

**Comment by freearhey** [comment]
> All channel data is taken from the [iptv-org/database](https://github.com/iptv-org/database) repository. If you find any errors please open a new [issue](https://github.com/iptv-org/database/issues) there.

https://github.com/iptv-org/iptv#database
