### ISSUE TITLE
MAC address is not activated!

### ISSUE THREAD

**Issue by Knrd2** [iptv-org/iptv#1330]
Everything was working fine until today. When i check the siptv homepage it says: MAC address is not activated!
Do you know why? Do i have to pay for it now?

**Comment by freearhey** [comment]
Please specify which channel we are talking about.

**Comment by Knrd2** [comment]
Its no specific channel. Its more about the initial configuration on https://siptv.eu/mylist/, when i send the request after filling out the MAC address and pasting the playlist https://iptv-org.github.io/iptv/index.country.m3u as a file, i receive an error message that my MAC address is not activated.

**Comment by freearhey** [comment]
I personally do not know why this error occurred, but I suspect that it has nothing to do with this repository.

But maybe someone else has faced this and can help you.

**Comment by Jariix** [comment]
Hi, yes you are right. You have to pay for it. After the seven days free test you should pay around 5,49€ per Mac address. Follow the activation [link](https://siptv.app/activation/)
