### ISSUE TITLE
Channel removal

### ISSUE THREAD

**Issue by Aladdin00** [iptv-org/iptv#1333]
Hi.
I want to edit the channel list so I can have a family  friendly IPTV.(No adult channels).
I'm somewhat inexperienced in this, so can someone help with this. I know how to edit an m3u file but not URL:s like the one used in this.

**Comment by freearhey** [comment]
You can download any of playlists on your computer, simply by opening a link to it in browser.

**Comment by Aladdin00** [comment]
Thank you for the info.
I was trying on my phone so no wonder it didn't work😂
