### ISSUE TITLE
Add: rtl (hu)

### ISSUE THREAD

**Issue by erich1997** [iptv-org/iptv#13348]
### Channel ID

RTLHungary.hu

### Stream URL (optional)

http://195.189.62.141:8000/play/a01v/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Astra link.

Playlist : http://195.189.62.141:8000/playlist.m3u8
