### ISSUE TITLE
Broken: ACS Network | ACSNetwork.pr

### ISSUE THREAD

**Issue by JustSammyV** [iptv-org/iptv#13351]
### Broken Link

https://vdo2.streamgato.us:3273/live/acsnetworktvlive.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://5790d294af2dc.streamlock.net/acsnetwork/acsnetwork/playlist.m3u8

### Notes (optional)

Owner announced the change for his channel.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://vdo2.streamgato.us:3273/live/acsnetworktvlive.m3u8
<img width="1416" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/ab2ad68b-ea47-47d1-afab-4a67aa22823e">

https://5790d294af2dc.streamlock.net/acsnetwork/acsnetwork/playlist.m3u8 (Offline)
<img width="539" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/58254154-7539-4004-b527-49a895de652f">

**Comment by JustSammyV** [comment]
Re-checked and verified that the streamlock link is online and streamgato is offline.

**Comment by JustSammyV** [comment]
@freearhey

**Comment by freearhey** [comment]
Both links are working for me at the moment.

**Comment by freearhey** [comment]
Closed in favor of #13386
