### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by luken55** [iptv-org/iptv#1336]
When selecting my stream, there doesn’t appear to be any sound?

**Comment by Nintendocustom** [comment]
which channel?

**Comment by luken55** [comment]
I’ve selected a fair few now... 

Is there also a way to have it show uk/ English channels first?

**Comment by luken55** [comment]
Sky channels are not working for me either?

**Comment by luken55** [comment]
That being said, now I’ve discovered being able to select using countries, I’ve lost the sky channels?

**Comment by freearhey** [comment]
@luken55 So what is the problem right now and which channel is it?

**Comment by luken55** [comment]
Okay so discovered if I just quit KODI and went back in to it the sound works, but I had sky channels that to be fair were not working anyway but that was on the build that didn’t include the option to have the channels set out by country. That’s the build I have now so I can select uk or American tv however sky channels are not in the uk folder? Where are they, and will they be working? Will you be Adding my sports channels like sky sports?

**Comment by freearhey** [comment]
@luken55 I assure you as soon as we have link to working Sky Sports stream we will add it to the playlist. 

You can follow the updates here: https://github.com/iptv-org/iptv/issues/871
