### ISSUE TITLE
Add: Nickelodeon East

### ISSUE THREAD

**Issue by whyiyeet** [iptv-org/iptv#13384]
### Channel ID

NickelodeonEast.us

### Notes (optional)

i am in wisconsin and wanna watch nickelodeon in the usa

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Duplicate of #13035

**Comment by whyiyeet** [comment]
jesus. if theres a duplicate you might need t do something
