### ISSUE TITLE
Broken:  NickelodeonFrance.fr 

### ISSUE THREAD

**Issue by whyiyeet** [iptv-org/iptv#13381]
### Broken Link

https://ythls.onrender.com/channel/UCeGvSi1Tb8OV78ue3_tux1A.m3u8

### What happened to the stream?

Other

### Notes (optional)

it keeps saying cant open mrl on vlc

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
yes offline   might have been a promo  or could go back anytime 

other nick are online
https://www.youtube.com/results?search_query=nickelodeon&sp=EgJAAQ%253D%253D

**Comment by whyiyeet** [comment]
man i dont think it is. i scrolled all the way down and there is none in the french language @Sphinxroot

**Comment by Sphinxroot** [comment]
french offline for now   might come back later who know
