### ISSUE TITLE
Broken: Canal Dos [CO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#13391]
### Broken Link

http://131.221.42.25:1935/streaming/canal2/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://canaldos.internetinalambrico.com.co:1936/live/canal2.stream/playlist.m3u8

### Notes (optional)

720p
Takes a while to load but it works 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by diegogaitanmerkas** [comment]
http://131.221.41.94/hls/canal2.m3u8
