### ISSUE TITLE
Add: Investigation Discovery India

### ISSUE THREAD

**Issue by Valchrist23** [iptv-org/iptv#13399]
### Channel ID

InvestigationDiscoveryIndia.in

### Notes (optional)

Hello team.

I found some live streams but they have the audio and video separated in 2 urls however i don't know how to join them.

these are the 2 urls:

video URL:
https://food-dlvr-ott.akamaized.net/primary/3/d31abde936de4fa884fbd91054dacad3/index_14.m3u8

Audio URL:
https://food-dlvr-ott.akamaized.net/primary/3/d31abde936de4fa884fbd91054dacad3/index_11_0.m3u8

If its helpful, this is the webpage where i found this stream

https://mhdtvworld.me/channel/english/

Thanks so much in advance

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Carlinhos027** [comment]
DMCA'd:
https://github.com/iptv-org/database/blob/master/data/blocklist.csv#L449
