### ISSUE TITLE
Broken: MoniTV [CO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#13392]
### Broken Link

https://servers.amelbasoluciones.co:19360/monitv/monitv.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://servers.amelbasoluciones.co:19360/monitvlive/monitvlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
Don't hesitate in looking over the big LATAM channel discussion we have, in case there's more links :)
