### ISSUE TITLE
Add: Asonga TV [GQ]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#13408]
### Channel ID

AsongaTV.gq

### Notes (optional)

#EXTVLCOPT:http-referrer=https://player.castr.com/live_e887acc04f7f11edb82e9f05583e4727
https://stream.castr.com/5ec1843635bd933ad25fe22e/live_e887acc04f7f11edb82e9f05583e4727/index.m3u8

1080p

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
kodi
https://stream.castr.com/5ec1843635bd933ad25fe22e/live_e887acc04f7f11edb82e9f05583e4727/index.m3u8|Referer=https://player.castr.com/live_e887acc04f7f11edb82e9f05583e4727


vlc
#EXTVLCOPT:http-referrer=https://player.castr.com/live_e887acc04f7f11edb82e9f05583e4727
https://stream.castr.com/5ec1843635bd933ad25fe22e/live_e887acc04f7f11edb82e9f05583e4727/index.m3u8
