### ISSUE TITLE
EPG guides broken http://195.154.221.171/epg/

### ISSUE THREAD

**Issue by iluso75** [iptv-org/iptv#1340]
**What's wrong?**
URL http://195.154.221.171/epg/ is given this error message: 
_"Forbidden
You don't have permission to access /epg/ on this server.

Apache/2.4.7 (Ubuntu) Server at 195.154.221.171 Port 80"_

Thanks

**Comment by freearhey** [comment]
Thank you for noticing! 

I just deleted all the links to this IP. As soon as there's a replacement, I'll add it right away.
