### ISSUE TITLE
Add: Reporter TV HD

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#13410]
### Channel ID

ReporterTV.in

### Stream URL (optional)

https://www.youtube.com/live/ZmFcWY1PDJo?feature=share

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
https://ythls.onrender.com/channel/UCFx1nseXKTc1Culiu3neeSQ.m3u8

**Comment by Manipulativemachan** [comment]
> https://ythls.onrender.com/channel/UCFx1nseXKTc1Culiu3neeSQ.m3u8

Showing error.

**Comment by kaikyoofers** [comment]
> > https://ythls.onrender.com/channel/UCFx1nseXKTc1Culiu3neeSQ.m3u8
> 
> Showing error.

Works for me.![Screenshot_20230703-115057_Chrome.jpg](https://github.com/iptv-org/iptv/assets/67206080/8e0e009c-665b-42ca-9a1c-932e4b5b81b4)

**Comment by Sphinxroot** [comment]
https://ythls.onrender.com/channel/UCFx1nseXKTc1Culiu3neeSQ.m3u8  working @Manipulativemachan  might be the player you use ?  here kodi and vlc work
