### ISSUE TITLE
Broken: CaracolTV.co in .co list

### ISSUE THREAD

**Issue by nomadmzl** [iptv-org/iptv#13424]
### Broken Link

https://mdstrm.com/live-stream-playlist/574463697b9817cf0886fc17.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

This channel is broken.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by kaikyoofers** [comment]
If stream link is accessed in browser, website says " This content is not available. Enjoy all the productions we have in our Caracol Play catalog and entertainment news at 'caracol's website'"

**Comment by Sphinxroot** [comment]
geoblocked  now  403 Forbidden
https://mdstrm.com/live-stream/574463697b9817cf0886fc17?enablejsapi=1&%20autoplay=true

**Comment by nomadmzl** [comment]
Source: https://www.caracoltv.com/senal-vivo

**Comment by BellezaEmporium** [comment]
Not broken, but geo-restricted to Colombian citizens only.
There's a few "unrestricted" Caracol channels from some LATAM Astra servers, like this one : #EXTINF:-1,Caracol-6012
http://181.78.24.67:8010/play/a02p/index.m3u8
