### ISSUE TITLE
Broken: CNN En Espanol

### ISSUE THREAD

**Issue by nomadmzl** [iptv-org/iptv#13425]
### Broken Link

http://209.91.213.10:8088/play/a014

### What happened to the stream?

Not loading

### Notes (optional)

in news stream

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
https://cnnespanol.cnn.com/en-vivo/
GEO + DMR

https://www.youtube.com/watch?v=fpkLCyxaKYs
GEO

**Comment by nomadmzl** [comment]
"[handleDRMTokenAuth] Token service response failed | Content blocked due to location"

**Comment by BellezaEmporium** [comment]
#EXTINF:-1,CNN Español-6019
http://181.78.24.67:8010/play/a03p/index.m3u8
