### ISSUE TITLE
Broken: Comedy - SoloUP.cl

### ISSUE THREAD

**Issue by nomadmzl** [iptv-org/iptv#13426]
### Broken Link

https://paneltv.online:1936/8116/8116/playlist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Carlinhos027** [comment]
Is working for me

**Comment by nomadmzl** [comment]
Maybe
