### ISSUE TITLE
Add: RANS Entertainment

### ISSUE THREAD

**Issue by antosatriani** [iptv-org/iptv#13449]
### Channel ID

RANSEntertainment.id

### Stream URL (optional)

https://app-etslive-2.vidio.com/live/8241/master.m3u8

### Notes (optional)

1080p

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://app-etslive-2.vidio.com/live/8241/master.m3u8 (offline)
<img width="389" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/fcb41aa5-c7b3-4562-8671-d305263478ad">
