### ISSUE TITLE
Broken:  NTV-Belarus

### ISSUE THREAD

**Issue by DzuyCuong** [iptv-org/iptv#13446]
### Broken Link

https://cdn-cache01.voka.tv/live/6.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
There is no such link in our playlists.
