### ISSUE TITLE
Add: TET [UA] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#13447]
### Channel ID

TET.ua

### Stream URL (optional)

http://31.43.48.248:7000/ch7/video.m3u8

### Notes (optional)

1080p

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by PopeyeTheSai10r** [comment]
The stream works fine for about 2 minutes and then it freezes.

![Capture](https://github.com/iptv-org/iptv/assets/107763146/b2cdb560-a800-40ed-a578-aca1c0b691ee)
