### ISSUE TITLE
Broken: JORX-DTV [JP]

### ISSUE THREAD

**Issue by solo489** [iptv-org/iptv#13444]
### Broken Link

https://tbs2.mov3.co/hls/tbs.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by ZXArkin** [comment]
Use replace to "tbs3" on the link here this: "https://tbs3.mov3.co/hls/tbs.m3u8"
