### ISSUE TITLE
Add: Blue Sky TV [GR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#13456]
### Channel ID

BlueSkyTV.gr

### Stream URL (optional)

https://cdn1.smart-tv-data.com/bluesky/bluesky-live/playlist.m3u8

### Notes (optional)

576p

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by trincowski** [comment]
@freearhey @PopeyeTheSai10r Something went wrong with the PR related to this task, the link included was the one for Attica TV, not this one.

**Comment by Carlinhos027** [comment]
> @freearhey @PopeyeTheSai10r Something went wrong with the PR related to this task, the link included was the one for Attica TV, not this one.

I know. I solved it on my PR:
https://github.com/iptv-org/iptv/pull/13495/commits/bf3b3f1762bf63256326afcfc4fd218d75fd9338#diff-afc67920841d39e454d20eccc2dd40b1441484cbad6662e46f74bcfa4fd30b5cL35

**Comment by iptvnikolas** [comment]
Different TV stations
