### ISSUE TITLE
Add:  SkyComedy.uk

### ISSUE THREAD

**Issue by whyiyeet** [iptv-org/iptv#13453]
### Channel ID

SkyComedy.uk

### Notes (optional)

i wanna watch sky comedy

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
DMCAd. We won't provide links for this channel, or this group of channels, as we have recieved a claim from Sky UK some time ago.
