### ISSUE TITLE
Add: Horee!

### ISSUE THREAD

**Issue by antosatriani** [iptv-org/iptv#13451]
### Channel ID

Horee.id

### Stream URL (optional)

https://app-etslive-2.vidio.com/live/6397/master.m3u8

### Notes (optional)

1080p

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://app-etslive-2.vidio.com/live/6397/master.m3u8 (offline)
<img width="393" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/e563e268-87f4-4c63-ba47-4314b017bb31">

**Comment by antosatriani** [comment]
Ya, I know Sir. Actually all the streaming url from domain vidio.com is online, but required to passing via http header referrer. May be next time someone can fix this, or find another stream url
