### ISSUE TITLE
Add: Kids TV [GR] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#13461]
### Channel ID

KidsTV.gr

### Stream URL (optional)

http://65.108.62.57:8080/live/kidshd.m3u8

### Notes (optional)

480p

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by PopeyeTheSai10r** [comment]
This stream was buffering when I tried it.

**Comment by freearhey** [comment]
http://65.108.62.57:8080/live/kidshd.m3u8 (shows the same image all the time)

<img width="1195" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/6df04c21-2bdc-44b9-8af1-4ef4c433abf6">

**Comment by iptvnikolas** [comment]
Now, however, he does not display this image, that is, he plays other childish things. But it's a good idea to add it to the "Kids" category. Thanks.
