### ISSUE TITLE
Broken: ATV Sur (PE)

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#13467]
### Broken Link

https://d3txgn7b0ej9cy.cloudfront.net/atv/8bcf2b35a573163055a95e18c0c35226.sdp/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://d3txgn7b0ej9cy.cloudfront.net/atv/8bcf2b35a573163055a95e18c0c35226.sdp/atv/atvsur1/chunks.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://d3txgn7b0ej9cy.cloudfront.net/atv/8bcf2b35a573163055a95e18c0c35226.sdp/playlist.m3u8 (works)
<img width="1392" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/325206c0-dac9-419e-8ec8-4a45c27dfb66">
