### ISSUE TITLE
Broken: Best Cable Mas Cumbia (pe)

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#13475]
### Broken Link

https://ca2.inka.net.pe/mascumbiatvonline/index.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://ca2.inka.net.pe/best-MasCum-0100210011/tracks-v1a1/mono.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Kahute** [comment]
Very good
