### ISSUE TITLE
Add: beIN Sports Xtra

### ISSUE THREAD

**Issue by PiirateCat** [iptv-org/iptv#13488]
### Channel ID

beINSPORTSXTRA.us

### Stream URL (optional)

https://bein-xtra-bein.amagi.tv/playlist1080p.m3u8

### Notes (optional)

Geo-Blocked

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
http://stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/5df975e2b27cf5000921c102livestitch/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=%7BTARGETOPT%7D&deviceId=%7BPSID%7D&advertisingId=%7BPSID%7D&us_privacy=1YNY&samsung_app_domain=%7BAPP_DOMAIN%7D&samsung_app_name=%7BAPP_NAME%7D&profileLimit=&profileFloor=&embedPartner=samsung-tvplus&profilesFromStream=true

Pluto Feed

**Comment by BellezaEmporium** [comment]
DMCAd. https://github.com/iptv-org/database/blob/master/data/blocklist.csv l92.

We won't provide further support for those links.

**Comment by freearhey** [comment]
@BellezaEmporium There is no such channel in the blocklist. On line 92 is the channel `beINSportsXtra1.qa`.

https://github.com/iptv-org/database/blob/master/data/blocklist.csv#L92

**Comment by BellezaEmporium** [comment]
Hmm... For me it was the same channel, but who knows. I don't know if the US channel broadcasts such copyrighted content.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f50b24bd4ba83099f0c7d22b7e25e27f850f51ae/streams/us_stirr.m3u#L8-L9
