### ISSUE TITLE
Broken: TV9 Bangla

### ISSUE THREAD

**Issue by sunny125094** [iptv-org/iptv#13487]
### Broken Link

https://vidcdn.vidgyor.com/tv9bangla-origin/live/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Whenever I try to play TV9 Bangla on kodi, it shows "Playback Failed: One or more items failed to play, check log for more information"

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-id="",TV9 Bangla
https://dyjmyiv3bp2ez.cloudfront.net/pub-iotv9banaen8yq/liveabr/playlist.m3u8

2 lives
https://www.youtube.com/@TV9BanglaLive
