### ISSUE TITLE
Rename: 2M

### ISSUE THREAD

**Issue by Zarh** [iptv-org/iptv#13507]
### Stream URL

https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/2m_monde/hls_video_ts_tuhawxpiemz257adfc/2m_monde.m3u8

### Correct ID

2MInternational.ma

### Notes (optional)

Hi, 

"2M monde" disapeared from Maghreb list : https://iptv-org.github.io/iptv/regions/maghreb.m3u

Maghreb is Morocco+Algeria+Tunisia

Thank you

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
The channel now has a wider region "Arab world" in our [database](https://github.com/iptv-org/database), so it is included in the https://iptv-org.github.io/iptv/regions/arab.m3u instead.
