### ISSUE TITLE
Broken: Foro TV

### ISSUE THREAD

**Issue by brokenstream** [iptv-org/iptv#13514]
### Broken Link

https://ythls.onrender.com/channel/UCUsm-fannqOY02PNN67C0KA.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-id="",https://www.nmas.com.mx/foro-tv
https://channel02-notusa.akamaized.net/hls/live/2023914/event01/index.m3u8

**Comment by Carlinhos027** [comment]
> #EXTINF:-1 tvg-id="",https://www.nmas.com.mx/foro-tv https://channel02-notusa.akamaized.net/hls/live/2023914/event01/index.m3u8
> 
> seem that youtube dev worker aint working anymore

Worked for me this morning lol
