### ISSUE TITLE
Broken: Excélsior TV

### ISSUE THREAD

**Issue by brokenstream** [iptv-org/iptv#13513]
### Broken Link

https://ythls.onrender.com/channel/UClqo4ZAAZ01HQdCTlovCgkA.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://ythls.onrender.com/channel/UClqo4ZAAZ01HQdCTlovCgkA.m3u8
<img width="1407" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/94bde05f-88d2-4a29-b973-8385acc98101">
