### ISSUE TITLE
Broken: Canal 66 Mexicali

### ISSUE THREAD

**Issue by brokenstream** [iptv-org/iptv#13511]
### Broken Link

https://ythls.onrender.com/channel/UCgu4v4HAioB0N5K6aq_H-WQ.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://5f1af61612fb5.streamlock.net/canal66/smil:canal66.smil/w718414097.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://5f1af61612fb5.streamlock.net/canal66/smil:canal66.smil/w718414097.m3u8 (offline)
<img width="580" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/a4b9e4b7-b072-4da8-84e9-da744951b63f">

**Comment by Sphinxroot** [comment]
https://5f1af61612fb5.streamlock.net/canal66/smil:canal66.smil/playlist.m3u8?wmsAuthSign= TOKEN

streamlink pipe : https://conceptoweb-studio.com/radio/video/canal66/

**Comment by brokenstream** [comment]
#13653
