### ISSUE TITLE
Request for following Uganda channels

### ISSUE THREAD

**Issue by blindspot1** [iptv-org/iptv#1352]
**Country of the channel:**
UGANDA

**Channel Names:*

NBS TV (English)
NTV Uganda (English)
BBS TV (Luganda)
Sanyuka TV (Luganda)

Thanks in advance!

**Comment by Sphinxroot** [comment]
NBS english (iF link dont change everyday ... )

https://live.vimeocdn.com/1589053367-0x58538fff9d01cab36e78c61d8a00c840c4438d15/b9c71d1d-abe2-4a18-9c57-a3a7ce0b1a0b/hls.m3u8

https://live.vimeocdn.com/1589053367-0x58538fff9d01cab36e78c61d8a00c840c4438d15/b9c71d1d-abe2-4a18-9c57-a3a7ce0b1a0b/chunklist_b2056000.m3u8

https://live.vimeocdn.com/1589053367-0x58538fff9d01cab36e78c61d8a00c840c4438d15/b9c71d1d-abe2-4a18-9c57-a3a7ce0b1a0b/chunklist_b728000.m3u8

https://live.vimeocdn.com/1589053367-0x58538fff9d01cab36e78c61d8a00c840c4438d15/b9c71d1d-abe2-4a18-9c57-a3a7ce0b1a0b/chunklist_b416000.m3u8

NTV
youtube(.)com/watch?v=9dpwX5yXgmo

BBS TV (Luganda) # bbstv(.)ug 403 forbidden /live/ 404 not found

Sanyuka TV (Luganda) sanyukatv(.)nbs(.)ug (GEO or Video Down)

**Comment by freearhey** [comment]
Closed in favor #1971
