### ISSUE TITLE
Add: Sky Racing 2 Australia 

### ISSUE THREAD

**Issue by Goldiefresh** [iptv-org/iptv#13528]
### Channel ID

SkyRacing2.au

### Stream URL (optional)

https://skylivetab-new.akamaized.net/hls/live/2038781/sky2/index.m3u8

### Notes (optional)

Geo-blocked 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
All the links given by this person so far are working, but all geo-blocked to Australia.
