### ISSUE TITLE
Broken: ARY Digital [PK]

### ISSUE THREAD

**Issue by uyseeer** [iptv-org/iptv#13538]
### Broken Link

https://arydigital.aryzap.com/101647b94a234edb1d8be0996ebedc9e/6459fa3c/v1/0183ea2408f90b8ed5941a38bc72/0183ea24302d0b8ed5941a38bc75/main.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
https://arydigital.aryzap.com/26f8ef1333bc08175bed840a31f3f087/64b579ee/v1/0183ea2408f90b8ed5941a38bc72/0183ea24302d0b8ed5941a38bc75/main.m3u8

**Comment by PopeyeTheSai10r** [comment]
> https://arydigital.aryzap.com/26f8ef1333bc08175bed840a31f3f087/64b579ee/v1/0183ea2408f90b8ed5941a38bc72/0183ea24302d0b8ed5941a38bc75/main.m3u8

Not loading for me. Do you know if it is Geo-locked or Not 24/7?

**Comment by Sphinxroot** [comment]
# https://live.arydigital.tv/

changing 

https://arydigital.aryzap.com/0c70d7a5ddc2f1f5f35cff8ddf064363/64c2f588/v1/0183ea2408f90b8ed5941a38bc72/0183ea24302d0b8ed5941a38bc75/main.m3u8

**Comment by freearhey** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/14245
