### ISSUE TITLE
Add: ESPN

### ISSUE THREAD

**Issue by jd530** [iptv-org/iptv#13534]
### Channel ID

ESPN.us

### Notes (optional)

Please USA channel espn

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
We cannot add the channel to the playlist due to claims of the copyright holder: https://github.com/github/dmca/blob/master/2020/09/2020-09-16-dfl.md
