### ISSUE TITLE
Broken: Cartoon Network East 

### ISSUE THREAD

**Issue by Frdesul** [iptv-org/iptv#13533]
### Broken Link

https://thetvapp.to/tv/cartoon-network-live-stream/

### What happened to the stream?

Not loading

### Notes (optional)

I am from Latinoamerican and my stream broken saying:
"Could not play video. There was a problem trying to load the video. Error code: hls:networkError_manifestLoadError"

any solution?

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Our playlists do not include this link.
