### ISSUE TITLE
Broken: Colors Cineplex

### ISSUE THREAD

**Issue by uyseeer** [iptv-org/iptv#13555]
### Broken Link

https://prod-sports-north-gm.jiocinema.com/bpk-tv/Colors_Cineplex_voot_MOB/Fallback/index.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Removed in #13653
