### ISSUE TITLE
Add: Animax asia

### ISSUE THREAD

**Issue by zaikuto** [iptv-org/iptv#13550]
### Channel ID

AnimaxAsia.sg

### Stream URL (optional)

http://tvmienphi.tv/live-tv/xem-kenh-animax-truc-tuyen.html

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/a6f53e1a98b2c4a6efc069689f46c1c8dc19bd2a/streams/vn_fptplay.m3u#L2-L7
