### ISSUE TITLE
Broken: 	 RTS 1

### ISSUE THREAD

**Issue by DzuyCuong** [iptv-org/iptv#13556]
### Broken Link

https://tv.liveott.online/RTS_1.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Carlinhos027** [comment]
Working for me in Spain
