### ISSUE TITLE
Add: DreikoTV.pa | Dreiko TV (mirror stream, CL datacenter)

### ISSUE THREAD

**Issue by JustSammyV** [iptv-org/iptv#13564]
### Channel ID

DreikoTV.pa

### Stream URL (optional)

https://wifiexpert-1.energeek.cl/dreikotv/canal-1/playlist.m3u8

### Notes (optional)

This stream is being mirrored from Dreiko TV's official source to our streaming server located on WifiExpert's datacenter, so it can be more accesible to Latin American people.

![image](https://github.com/iptv-org/iptv/assets/137475335/68252e59-d43f-47bd-ac09-2cd68ab0a45e)

Ping from WifiExpert datacenter:
![image](https://github.com/iptv-org/iptv/assets/137475335/88e4eaf7-47d3-4703-8d0e-28e1abb1d691)

Ping from CloudVideo Servers10:
![image](https://github.com/iptv-org/iptv/assets/137475335/170fc3b8-d391-4b31-b552-79c4860c3f3e)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by b4zz4** [comment]
New URL
https://cloudvideo.servers10.com:8081/8096/tracks-v1a1/mono.m3u8
