### ISSUE TITLE
TVG-Country=

### ISSUE THREAD

**Issue by Jariix** [iptv-org/iptv#1359]
Hi everyone, 
i Import the language playlist and found two extra groups (TVG-Country= and a github group). The first one with an arabic channel *MBC5* and the github group with german and other languages. Is this a common problem? 
Thank you in advance.

**Comment by Jariix** [comment]
The 2nd group named: Github - Index.language. It has 302 channels.

**Comment by freearhey** [comment]
Sorry, but I have no idea what you're talking about.

**Comment by Jariix** [comment]
I'm using smart Iptv app and iptv extreme pro. Both are showing the list differently. The smart Iptv app is showing extra group called (Github - Index.language). This group has 302 channels most of them are german and the rest ist a mix of languages. The iptv extreme app is not showing this group but it is showing a big folder with the 302 channels and then the subfolders with the languages.

**Comment by freearhey** [comment]
Okay, I think I figured out what the problem might be. One of the playlists had a symbol missing, but I've already fixed it and the extra group should disappear tomorrow after the daily update.
