### ISSUE TITLE
Add: CBeebies

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13631]
### Channel ID

cbeebies.uk

### Stream URL (optional)

https://vs-hls-pushb-uk-live.akamaized.net/x=3/i=urn:bbc:pips:service:cbeebies_hd/t=3840/v=pv14/b=5070016/main.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/ac41fd2241027d925a2980d70d49d0d9850806d5/streams/uk_bbc.m3u#L236-L243

**Comment by Rguanchez** [comment]
Is CBeebies sign off BBC Four Sign on
