### ISSUE TITLE
Add: Pop Max 

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13630]
### Channel ID

popmax.uk

### Stream URL (optional)

https://live-sonybebanjo.simplestreamcdn.com/live8/popmax/bitrate1.isml/live.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/ac41fd2241027d925a2980d70d49d0d9850806d5/streams/uk.m3u#L143-L146
