### ISSUE TITLE
Broken: ABC News [AL]

### ISSUE THREAD

**Issue by eurohunter** [iptv-org/iptv#13656]
### Broken Link

https://tv2.abcnews.al/live/abcnews/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

The live stream on the official site is a YouTube link, so it doesn't have an .m3u8 file.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
https://www.youtube.com/channel/UCBvv5xYXNHa5XjecBC2-odA/live

**Comment by Sphinxroot** [comment]
#EXTINF:-1,ABC
http://79.106.90.124:5151/live/abcnewsott/playlist.m3u8
