### ISSUE TITLE
Broken: Zjarr TV [AL]

### ISSUE THREAD

**Issue by eurohunter** [iptv-org/iptv#13654]
### Broken Link

https://content.jwplatform.com/live/broadcast/hiynhSaw.m3u8

### What happened to the stream?

Stuck at a single frame

### Possible Replacement (optional)

https://cdn.jwplayer.com/live/events/r2qgHu7W.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
# https://zjarr.tv/live/
code : 304
https://content.jwplatform.com/live/broadcast/hiynhSaw.mpd
https://livecdn.euw1-0005.jwplive.com/live/sites/sLGVyWpR/media/hiynhSaw/live.isml/.mpd

working
https://cdn.jwplayer.com/live/events/r2qgHu7W.m3u8
