### ISSUE TITLE
Broken: RTSH Channels [AL]

### ISSUE THREAD

**Issue by eurohunter** [iptv-org/iptv#13655]
### Broken Link

http://edge01eu.ekranet.com:80/rtshhd_low/index.m3u8

### What happened to the stream?

Shows looped video

### Notes (optional)

All RTSH links show looped videos:
#EXTINF:-1 tvg-id="RTSH1.al",RTSH 1 (780p) [Not 24/7]
http://edge01eu.ekranet.com:80/rtshhd_low/index.m3u8
#EXTINF:-1 tvg-id="RTSH2.al",RTSH 2 (720p) [Not 24/7]
http://edge01eu.ekranet.com:80/rtsh2hd1/index.m3u8
#EXTINF:-1 tvg-id="RTSH24.al",RTSH 24 (720p) [Not 24/7]
http://edge01eu.ekranet.com:80/rtsh24/index.m3u8
#EXTINF:-1 tvg-id="RTSH3.al",RTSH 3 (720p) [Not 24/7]
http://edge01eu.ekranet.com:80/rtsh3hd1/index.m3u8
#EXTINF:-1 tvg-id="RTSHFilm.al",RTSH Film (576p) [Not 24/7]
http://edge01eu.ekranet.com:80/rtshfilm1/index.m3u8
#EXTINF:-1 tvg-id="RTSHSport.al",RTSH Sport (720p) [Not 24/7] 
http://edge01eu.ekranet.com:80/rtshsport_240p/index.m3u8
#EXTINF:-1 tvg-id="RTSHShqip.al",RTSH Shqip (576p) [Not 24/7]
http://edge01eu.ekranet.com/rtshshqip1/index.m3u8
#EXTINF:-1 tvg-id="RTSHMuzike.al",RTSH Muzikë (720p) [Not 24/7]
http://edge01eu.ekranet.com/rtshmsicweb/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
# https://tv.rtsh.al/
https://tvlive.rtsh.dev/live/rtsh_11mob1/playlist.m3u8
https://tvlive.rtsh.dev/live/rtsh_2ott/playlist.m3u8
https://tvlive.rtsh.dev/live/rtsh3ott/playlist.m3u8
https://tvlive.rtsh.dev/live/rtsh_24_ott/playlist.m3u8
https://tvlive.rtsh.dev/live/rtsh_sport_ott11/playlist.m3u8
https://tvlive.rtsh.dev/live/rtsh_shkolle_ott/playlist.m3u8
https://tvlive.rtsh.dev/live/rtsh_femije_ott/playlist.m3u8
https://tvlive.rtsh.dev/live/rtsh_agro_ott/playlist.m3u8
https://tvlive.rtsh.dev/live/rtsh_muzike_mob/playlist.m3u8
https://tvlive.rtsh.dev/live/rtsh_film_ott/playlist.m3u8
https://tvlive.rtsh.dev/live/rtsh_shqip_ott/playlist.m3u8
https://tvlive.rtsh.dev/live/rtsh_kuvendi_ott/playlist.m3u8
https://tvlive.rtsh.dev/live/rtsh_korca_ott/playlist.m3u8
https://tvlive.rtsh.dev/live/rtsh_gjirokastra_ott/playlist.m3u8
https://tvlive.rtsh.dev/live/rtsh_kukesi_ott_p2/playlist.m3u8
https://tvlive.rtsh.dev/live/rtsh_plus_ott/playlist.m3u8

no mediaManifest Found  seem offline m3u8 empty

**Comment by eurohunter** [comment]
Yes, those links on the official site have been offline for about a year. The newly added links come from a different source but still don't seem to work. they show old looped videos.

**Comment by Sphinxroot** [comment]
try those 

RTSH 1
http://79.106.90.124:5151/live/rtsh1ott/playlist.m3u8?
RTSH 2HD
http://79.106.90.124:5151/live/rtsh2/playlist.m3u8?
RTSH 24HD
http://79.106.90.124:5151/live/rtsh24/playlist.m3u8?
RTSH SHQIP HD
http://79.106.90.124:5151/live/rtshshqip/playlist.m3u8?
RTSH FILM HD
http://79.106.90.124:5151/live/rtshfilmott/playlist.m3u8?
RTS SPORT
http://79.106.90.124:5151/live/rtshsport/playlist.m3u8?

playing whit the naming might get you lucky

**Comment by Lanabubullima** [comment]
![Uploading zYIsBvQKPKI.jpg…]()
