### ISSUE TITLE
Update Sports Channel in Sports Category

### ISSUE THREAD

**Issue by SharyRajpoot** [iptv-org/iptv#1365]
This is the Pakistani sports channels which you have added in-country Pakistan list but not in the category sport list so update this channels on sports category as well.

#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://upload.wikimedia.org/wikipedia/en/e/e4/PTV_Sports.png" group-title="",PTV Sports
http://95.211.211.168/live/ptvsports2002/playlist.m3u8

**Comment by freearhey** [comment]
Done.
