### ISSUE TITLE
talktv old link dead

### ISSUE THREAD

**Issue by jamie-203** [iptv-org/iptv#13660]
### Channel ID

TalkTV.uk

### Stream URL (optional)

https://watch.talk.tv/live?autoplay=true

### Notes (optional)

Old links all dead

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by trancer1994** [comment]
https://live-talktv-ssai.simplestreamcdn.com/v1/master/82267e84b9e5053b3fd0ade12cb1a146df74169a/talktv-live/index.m3u8?ads.ip=51.19.253.115&ads.app_bundle=&ads.app_store_url=&ads.content_id=46eb91fe-2bbd-11ee-b979-020f80c0527e&ads.content_title=The+Independent+Republic+of+Mike+Graham&ads.gdpr_consent=CPvnjIAPvnjIAAGABCENDNCgAAAAAH_AAAwIAAASRALMFSYAgKEspBaQMIoQQgQgCUiAUBEFAILQAIAECgoSVgELIIEAKAQAUgQEhxAQiQCAACCAJAgABACwQKCACAQAAgAAAAAAEQAICACwEAAABAJAAACAAEAwgiAAAhDAgIICCQFgAAAAIJDAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAWCABACaAFLALOAwIJAFAAQAU0AqABigDWBQCAACgAVABCACkAK0AYQBCACOAFfAL8AbYA8QB6gFiAMIAYyGgCADLAIwAawA6ocACAWkRAGAB8AMsAjABrADqgMjEgAQFiCoAYAywCOAMjFgAQC0jIAYAywCOAMjGgAQEnDoAoBigD7ALtAZGA0QeARAAUACoAHwATQApACTAFaARkAjgBXwC0gF-ANsAeIA9QCxAGMkAAIAzSEAcAMQApQBlAGKAWUAyMBohEAaACoAJoAkwCMgEcAK-AWkAvwBnADxAJOATEAsQkABAGaSgCgAIAA-AKMAxQDIyYBEAIQATQApAB4AEmAK0AjIBHACmgFfALSAX4AzgBtgDxALEAYyUABAB_AIOUgCAH2AScAu0BkZUAaACoAHwAQgAmgB4AEmAK0AjgBXwDbAHiAWIAxk.YAAAAAAAAAAA&ads.gdpr=1&ads.us_privacy=&ads.platform=web&ads.app_version=unknown&ads.os_type=web&ads.app_version_key=unknown&ads.device_id=&ads.ifa_type=ifa_type&ads.site_id=22942

**Comment by Smark223** [comment]
Or just https://live-talktv-ssai.simplestreamcdn.com/v1/master/82267e84b9e5053b3fd0ade12cb1a146df74169a/talktv-live/index.m3u8

**Comment by freearhey** [comment]
Closed in favor of #13680
