### ISSUE TITLE
Broken: Crime 360

### ISSUE THREAD

**Issue by brokenstream** [iptv-org/iptv#13665]
### Broken Link

https://aenetworks-crime360-1.samsung.wurl.com/manifest/playlist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by twodragon** [comment]
https://c9747bb6.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/U2Ftc3VuZ19DcmltZTM2MF9ITFM/playlist.m3u8

is true channel ?

**Comment by twodragon** [comment]
#13759
