### ISSUE TITLE
Broken: Bounce XL

### ISSUE THREAD

**Issue by brokenstream** [iptv-org/iptv#13667]
### Broken Link

https://c217322ca48e4d1e98ab33fe41a5ed01.mediatailor.us-east-1.amazonaws.com/v1/master/04fd913bb278d8775298c26fdca9d9841f37601f/Samsung_BounceXL/playlist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by R4IN2007** [comment]
Linear Version works https://linear-434.frequency.stream/434/hls/master/playlist.m3u8

**Comment by spotanjo3** [comment]
> Linear Version works https://linear-434.frequency.stream/434/hls/master/playlist.m3u8

It's working fine for Bounce XL and CC for hearing impaired too. Thanks.

**Comment by spotanjo3** [comment]
It doesnt worked. Your link is working fine:

https://aegis-cloudfront-1.tubi.video/22eea4e9-00a6-427c-92dd-57e78cc160dc/playlist.m3u8
