### ISSUE TITLE
Broken: AMC All Weddings

### ISSUE THREAD

**Issue by brokenstream** [iptv-org/iptv#13662]
### Broken Link

https://amc-allweddings-1-us.samsung.wurl.tv/playlist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by twodragon** [comment]
https://d85lu9l3axp7b.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-49b4g6287mnav/playlist.m3u8
All We Weddings TV
