### ISSUE TITLE
Broken: EDGEsport

### ISSUE THREAD

**Issue by brokenstream** [iptv-org/iptv#13668]
### Broken Link

https://edgesport-samsungus.amagi.tv/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

There is another broken link for the same channel:

#EXTINF:-1 tvg-id="EDGEsport.uk",EDGEsport (US) (720p)
https://img-edgesport.samsung.wurl.com/manifest/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by twodragon** [comment]
https://edgesport-samsunguk.amagi.tv/playlist.m3u8

**Comment by brokenstream** [comment]
#13795
