### ISSUE TITLE
HI .SIR PAKISTANI TV

### ISSUE THREAD

**Issue by tiziano20** [iptv-org/iptv#1367]
**Country of the channel:** PAKISTANI TV CHANELLS 

**Channel Name:**
 BOL TV ,ARY TV,MADNI TV,AAJ ENTERTANMENT ARY DIGITAL ,GEO KAHANI, APLUS TV,GNN TV HAM TV

**Channel Language:**
URDO

**Additional Information (optional):**

**Comment by Nintendocustom** [comment]
MADNI TV
http://stream-7b694ce7e.nmbs.top/m3u/Pakistan/3a84163b35.m3u8
GEO KAHANI
http://stream-7b694ce7e.nmbs.top/m3u/Pakistan/b7fbbce234.m3u8

**Comment by tiziano20** [comment]
hi sir i use ottplayer same vls player.there not working his link.please where use this link? thanks
    Il sabato 16 maggio 2020, 22:54:24 CEST, Nintendocustom <notifications@github.com> ha scritto:  
 
 


MADNI TV
http://stream-7b694ce7e.nmbs.top/m3u/Pakistan/3a84163b35.m3u8
GEO KAHANI
http://stream-7b694ce7e.nmbs.top/m3u/Pakistan/b7fbbce234.m3u8

**Comment by freearhey** [comment]
Closed in favor #1973
