### ISSUE TITLE
Broken: Shout! Factory TV

### ISSUE THREAD

**Issue by brokenstream** [iptv-org/iptv#13677]
### Broken Link

https://shout-factory.samsung.wurl.com/manifest/playlist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by eklins** [comment]
https://shoutfactory-localnow.amagi.tv/playlist.m3u8

http://shoutfactory-redbox.amagi.tv/playlist.m3u8
