### ISSUE TITLE
Broken: ION

### ISSUE THREAD

**Issue by brokenstream** [iptv-org/iptv#13673]
### Broken Link

https://scripps-ion-1-us.samsung.wurl.tv/playlist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by R4IN2007** [comment]
Vizio version still works https://scripps-ion-1-us.vizio.wurl.tv/playlist.m3u8 and same with the  linear version https://linear-432.frequency.stream/432/hls/master/playlist.m3u8

**Comment by LPhilip1999** [comment]
To @R4IN2007, Can I also the Linear Version stream of Pocket Watch and Ryan and Friends channels via Roku please?

 https://ryanandfriends-roku.amagi.tv/playlist.m3u8

https://pocketwatch-roku.amagi.tv/playlist.m3u8

**Comment by spotanjo3** [comment]
Dead.
