### ISSUE TITLE
Add: Disney channel Hindi

### ISSUE THREAD

**Issue by Salar7860** [iptv-org/iptv#13684]
### Channel ID

Disney.in

### Stream URL (optional)

http://stream-7b694ce7e.nmbs.top/m3u/Kids/c86abe8bd6.m3u8

### Notes (optional)

Please add the channel “Disney channel hindi” to the playlist, I have attached an m3u8 link.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Salar7860** [comment]
Wdym it’s not planned, I’m requesting a channel.

**Comment by freearhey** [comment]
> IMPORTANT: an issue without a valid channel ID or containing a request for more than one channel will be closed immediately

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel

**Comment by JohnMathews223** [comment]
> ### Channel ID
> Disney.in
> 
> ### Stream URL (optional)
> http://stream-7b694ce7e.nmbs.top/m3u/Kids/c86abe8bd6.m3u8
> 
> ### Notes (optional)
> Please add the channel “Disney channel hindi” to the playlist, I have attached an m3u8 link.
> 
> ### Please confirm the following
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

Is it possible to play the channel using the stream url on my pc instead of in an iptv playlist
