### ISSUE TITLE
Pakistan Channel: ARY Digital, HUM TV and Geo Entertainment Missing‼️

### ISSUE THREAD

**Issue by fahad2006ary** [iptv-org/iptv#1369]
Pakistan
ARY Digital, Hum TV, Geo Entertainment
Urdu

**Additional Information (optional):**

**Comment by Nintendocustom** [comment]
ARY Digital
http://stream-7b694ce7e.nmbs.top/m3u/Pakistan/91c5a880fa.m3u8
HUM TV
http://stream-7b694ce7e.nmbs.top/m3u/Pakistan/410c124a10.m3u8
Geo Entertainment
http://stream-7b694ce7e.nmbs.top/m3u/Pakistan/87e4b5ce2f.m3u8

**Comment by shafiquecbl** [comment]
These links are not working. Can you please provide https links for the above channels and PTV Sports and ASports?

**Comment by uzair567C** [comment]
all pakistani chanels

https://iptv-org.github.io/iptv/countries/pk.m3u

**Comment by Zainee007** [comment]
> all pakistani chanels
> 
> https://iptv-org.github.io/iptv/countries/pk.m3u

Half are not working, mainly sports

**Comment by wantedbrother625** [comment]
ptv sports not working other also not working can anofy give me a valid link

**Comment by adilkhanreal** [comment]
Where to get the new working links?
