### ISSUE TITLE
Add: Prima Cool (CZ)

### ISSUE THREAD

**Issue by Jakubicek222** [iptv-org/iptv#13701]
### Channel ID

PrimaCool.cz

### Stream URL (optional)

http://st02.lab.cho01.iptv.grapesc.cz/60-tv-stb.m3u8

### Notes (optional)

![image](https://github.com/iptv-org/iptv/assets/106910269/22053b9b-ad8e-486f-9fec-5ea413d37ebe)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by democratia1987-source** [comment]
Not Working.
