### ISSUE TITLE
Add: Fuji TV

### ISSUE THREAD

**Issue by inklingboi08** [iptv-org/iptv#13717]
### Channel ID

JOCXDTV.jp

### Stream URL (optional)

https://fujitv4.mov3.co/hls/fujitv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://fujitv4.mov3.co/hls/fujitv.m3u8
<img width="1420" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/e1cccbb1-7682-4b7b-b574-673de8bd1402">
