### ISSUE TITLE
Add: ATV+ HD (Perú) [Linear Version of ATV+]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#13715]
### Channel ID

ATVPlus.pe

### Stream URL (optional)

https://linear-258.frequency.stream/dist/vix/258/hls/master/playlist.m3u8

### Notes (optional)

(Linear Version & Streaming on VIX.com a spanish televisa-univision site) Might be geo-blocked or geo-locked because by removing /dist/vix/ the m3u8 link stops working #13703 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Removing "/dist/vix" doesn't remove anything, it's due to the fact that this channel is only available for ViX users (and this distributor in extent), meaning that it won't work outside of that distributor. Frequency has multiple ways of working.

**Comment by freearhey** [comment]
https://linear-258.frequency.stream/dist/vix/258/hls/master/playlist.m3u8
<img width="1399" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/db2638ad-1ee4-44e6-8574-6f187ecc6534">
