### ISSUE TITLE
Requesting an Arabic channel 

### ISSUE THREAD

**Issue by ayoodi** [iptv-org/iptv#1371]
**Country of the channel:**

Egypt , Middle East

**Channel Name:**

Maspero Zaman

**Channel Language:**

Arabic

**Additional Information (optional):**

This channel is usually under Nilesat

**Comment by ayoodi** [comment]
If you can kindly add it to the Arabic category or by country I would really appreciate it

**Comment by MoonSyria** [comment]
Maspero Zaman

http://161.35.215.36:9000/live/joba/joba/7.m3u8

**Comment by ayoodi** [comment]
Salams, 
Thank you for responding back to my request, I tried to paste the link into one of my IPTV apps and it didn't work, I also tried VLC. can you please double check the link, or let me know if there is a new one ? 
    On Saturday, July 18, 2020, 04:56:47 PM CDT, MoonSyria <notifications@github.com> wrote:  
 
 


Maspero Zaman

http://161.35.215.36:9000/live/joba/joba/7.m3u8

**Comment by freearhey** [comment]
Closed in favor #1947
