### ISSUE TITLE
Add: JOCX-DTV

### ISSUE THREAD

**Issue by solo489** [iptv-org/iptv#13718]
### Channel ID

JOCX-DTV.jp

### Stream URL (optional)

https://redlabmcdn.s.llnwi.net/nv02/ryowa7hd/index.mpd

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Duplicate of #13717
