### ISSUE TITLE
Add: Canal 12 Libertad (Stream from Opencaster.com)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#13719]
### Channel ID

*N/A*

### Stream URL (optional)

https://edge1o.live.opencaster.com/caster/qapbrjbqhosG.m3u8

### Notes (optional)

Stream URL is from opencaster.com
https://opencaster.com/canal12libertad

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Origin-locked to https://opencaster.com
Unless you put a proxy putting the origin on each request, or you use streamlink/kodi, it won't work on basic players.
