### ISSUE TITLE
Add: Islam Channel Urdu

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13728]
### Channel ID

islamchannelurdu.uk

### Stream URL (optional)

https://live-islamtv-urdu.simplestreamcdn.com/live7/islamtv_urdu/bitrate1.isml/bitrate1-audio_0=128000-video=2406976.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/0c0b13dbb1f6a9e4bacad0626d92e6123e994934/streams/uk.m3u#L95-L96
