### ISSUE TITLE
Add: IPlusTV

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13727]
### Channel ID

iplustv.in

### Stream URL (optional)

https://live.we2live.in/iplustv/iplustv/chunklist_w1045197576.m3u8

### Notes (optional)

Add IPlusTv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/0c0b13dbb1f6a9e4bacad0626d92e6123e994934/streams/in.m3u#L316-L317
