### ISSUE TITLE
Broken: Ary QTV

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#13733]
### Broken Link

https://aryqtv.aryzap.com/24591444d352c03d824757bbf5a60d7d/6459fab3/v1/0183ea2a0eec0b8ed5941a38bc76/0183ea2a4e470b8ed5aa4d793457/main.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://aryqtv.aryzap.com/859af40a1493997e1ea86c1054773823/64cfef73/v1/0183ea2a0eec0b8ed5941a38bc76/0183ea2a4e470b8ed5aa4d793457/ARYQTVH264_720p.m3u8

### Notes (optional)

Original request: #13731

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by twodragon** [comment]
https://aryqtv.aryzap.com/859af40a1493997e1ea86c1054773823/64cfef73/v1/0183ea2a0eec0b8ed5941a38bc76/0183ea2a4e470b8ed5aa4d793457/main.m3u8 (for 1080p)

**Comment by freearhey** [comment]
https://aryqtv.aryzap.com/859af40a1493997e1ea86c1054773823/64cfef73/v1/0183ea2a0eec0b8ed5941a38bc76/0183ea2a4e470b8ed5aa4d793457/ARYQTVH264_720p.m3u8 (offline)

**Comment by freearhey** [comment]
Closed in favor of #14246
