### ISSUE TITLE
Add: Ary QTV

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13731]
### Channel ID

aryqtv.pk

### Stream URL (optional)

https://aryqtv.aryzap.com/859af40a1493997e1ea86c1054773823/64cfef73/v1/0183ea2a0eec0b8ed5941a38bc76/0183ea2a4e470b8ed5aa4d793457/ARYQTVH264_720p.m3u8

### Notes (optional)

ARY QTV,[[1]](https://en.wikipedia.org/wiki/ARY_Qtv#cite_note-1) formerly known as Quran Television (QTV), is a Pakistani television channel with a [Sunni Islam](https://en.wikipedia.org/wiki/Sunni_Islam) belief, that produces programs mainly having focus on the [Ahlesunnat wal Jamaat](https://en.wikipedia.org/wiki/Barelvi).[[2]](https://en.wikipedia.org/wiki/ARY_Qtv#cite_note-:0-2) [QTV](https://en.wikipedia.org/wiki/QTV_(ARY)) is part of the [ARY Digital Network](https://en.wikipedia.org/wiki/ARY_Digital_Network) of Pakistan.[[3]](https://en.wikipedia.org/wiki/ARY_Qtv#cite_note-3)

The channel has shows featuring well-known scholars such as [Pir Muhammad Alauddin Siddiqui](https://en.wikipedia.org/wiki/Pir_Muhammad_Alauddin_Siddiqui), Saqib Iqbal Shami, [Muhammad Raza Saqib Mustafai](https://en.wikipedia.org/wiki/Muhammad_Raza_Saqib_Mustafai), Shaykh Hassan Haseeb Ur Rehman, Dr. Muhammad [Tahir-ul-Qadri](https://en.wikipedia.org/wiki/Tahir-ul-Qadri), Dr. Umar Al-Qadri, Mufti Abu Baqr, Mufti Muhammad Akmal, Mufti Shahid, Mufti Sohail Raza Amjadi, Mufti Muhammad Aamir, Muhammad Ajmal Raza Qadri.[[2]](https://en.wikipedia.org/wiki/ARY_Qtv#cite_note-:0-2) Other shows include [Qur'an](https://en.wikipedia.org/wiki/Qur%27an) teachings, [hadith](https://en.wikipedia.org/wiki/Hadith), talk shows, question-and-answer shows, [Qawwali](https://en.wikipedia.org/wiki/Qawwali) music and [Na`at](https://en.wikipedia.org/wiki/Na%60at) poetry

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Closed in favor of #13733
