### ISSUE TITLE
Add: Rotana Khalijia

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13732]
### Channel ID

RotanaKhalijia.sa

### Stream URL (optional)

https://dai.google.com/linear/hls/pa/event/Ow9HolmDThGX9-D9EOdrHw/stream/d5ad4212-803f-47da-854e-d50b9c227ad3:BRU/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Master link : https://dai.google.com/linear/hls/pa/event/Ow9HolmDThGX9-D9EOdrHw/master.m3u8

**Comment by UltraHDR** [comment]
Already here https://github.com/iptv-org/iptv/blob/d5d680e0128ea636fd63db78c3f2a669f6254554/streams/sa.m3u#L113
