### ISSUE TITLE
Add: Rotana Drama 

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13743]
### Channel ID

RotanaDrama.sa

### Stream URL (optional)

https://rotanastudios-rotanadrama-1-eu.xiaomi.wurl.tv/807905e439854b6ace3651e884e1fac6.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/71f1761a72f9eb7646eac62f0a494731f685b56e/streams/sa.m3u#L106-L109
