### ISSUE TITLE
Add: Rotana Cinema Egypt

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13741]
### Channel ID

RotanaCinemaEgypt.eg

### Stream URL (optional)

https://dai.google.com/linear/hls/pa/event/3nre1M54SiWmGzcTHQlLDA/stream/3350ee51-c84b-44a7-9bf8-3d06c92e6481:BRU/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
https://dai.google.com/linear/hls/event/3nre1M54SiWmGzcTHQlLDA/master.m3u8 and shows 401.

**Comment by twodragon** [comment]
> https://dai.google.com/linear/hls/event/3nre1M54SiWmGzcTHQlLDA/master.m3u8 and shows 401.

@BellezaEmporium  plase test this link 
https://dai.google.com/linear/hls/pa/event/3nre1M54SiWmGzcTHQlLDA/stream/cd17ab23-3e2b-4eb8-bed8-3bf593e9ecae:GRQ/master.m3u8

**Comment by BellezaEmporium** [comment]
> > https://dai.google.com/linear/hls/event/3nre1M54SiWmGzcTHQlLDA/master.m3u8 and shows 401.
> 
> @BellezaEmporium plase test this link https://dai.google.com/linear/hls/pa/event/3nre1M54SiWmGzcTHQlLDA/stream/cd17ab23-3e2b-4eb8-bed8-3bf593e9ecae:GRQ/master.m3u8

This one goes through, but 400s when interrogating Rotana's servers. I guess it's normal.

**Comment by twodragon** [comment]
https://dai.google.com/linear/hls/pa/event/3nre1M54SiWmGzcTHQlLDA/stream/cd17ab23-3e2b-4eb8-bed8-3bf593e9ecae:GRQ/master.m3u8

> > > https://dai.google.com/linear/hls/event/3nre1M54SiWmGzcTHQlLDA/master.m3u8 and shows 401.
> > 
> > 
> > @BellezaEmporium plase test this link https://dai.google.com/linear/hls/pa/event/3nre1M54SiWmGzcTHQlLDA/stream/cd17ab23-3e2b-4eb8-bed8-3bf593e9ecae:GRQ/master.m3u8
> 
> This one goes through, but 400s when interrogating Rotana's servers. I guess it's normal.

new link :) https://shls-masr2-ak.akamaized.net/out/v1/c39c0ecbcbdb46e890e91106776397a8/index.m3u8

**Comment by freearhey** [comment]
https://shls-masr2-ak.akamaized.net/out/v1/c39c0ecbcbdb46e890e91106776397a8/index.m3u8
<img width="1438" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/2d19b18e-e389-4f18-87b0-31bc47ceffe5">
