### ISSUE TITLE
Add: Sky News Arabia

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13748]
### Channel ID

SkyNewsArabia.ae

### Stream URL (optional)

https://stream.skynewsarabia.com/hls/sna_720.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Not that keen on adding this one, as Sky UK's legal team doesn't really like their channels wandering around.

**Comment by Kasyas2011** [comment]
https://stream.skynewsarabia.com/hls/sna_720.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/71f1761a72f9eb7646eac62f0a494731f685b56e/streams/ae.m3u#L136-L139
