### ISSUE TITLE
Add: Baraem

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13744]
### Channel ID

baraem.qr

### Stream URL (optional)

https://tv.ipslow.com/tv233_www.elahmad.com_baraem/tracks-v1a1/mono.m3u8?token=2fec1f0d00dbdee6a7de4941ac63bb7ddbac5d47-b899e94f14166485fe05c86b895c1faa-1691335069-1691324269

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
404

**Comment by Kasyas2011** [comment]
Not found
