### ISSUE TITLE
Add: Pluto Tv Sabrina

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13749]
### Channel ID

PlutoTVSabrina.us

### Stream URL (optional)

https://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/v2/stitch/hls/channel/5d94a5451754e6a4298d1059/3063648/playlist.m3u8?terminate=false&sid=48305b30-3457-11ee-a7d3-62ebfdfffccb&deviceDNT=0&deviceLat=55.805&deviceLon=-4.2899&deviceModel=web&deviceVersion=115.0.1901&gdpr=1&gdprConsent=CPwEhz_PwEh0uAcABBENDRCgALCAAEJAACiQIcgZ5C5ETWlDKPh9A_s0WYAHVlwQAeAiCgCBACAFCAAAIAYABCAgoAQAACACOAAAIAIAAAIEAAAEQEAAQAAAAAFAAAAAgAAIIABAAAEAAAAAAAIAgAQAAAAAAAAREAAAiAgAAkKEQEAAQAAQAAAAgIAAAAAEAgMAAAAAQAIAAAAAAgAAAAAAAAIIcgBgCpETQFAKOhNAHEUCIAQVhAQAKAiCACBAAAECAAAIAYAFCAggAAAAAAAOAAAIAAAAAAAAAAEAEAAQAAAAABAAAAAAAAIAABAAAEAAAAAAAAAgAAAAAAAAAAQAAAAgQhAAAIEQEAAQAAQAAAAgAAAAAAAAAMAAAAAAAAAAAAAAgAAAAAAAAICAQBWAAaABgAGgAQgAuADAAJIAWABaAC-AHIAdAA_ACMAE4AKEAWgBbgDCAMQAZYA0ADYAHKAQABBACMgEeASAAogBSAC5AGqAOIAhIBTQDMgGgAN4AhsBF4CoAF7gL_AYoAxsBkADcwHMAOhAdSA8wKASAAVACcAKAAVAA9ACKAFIALwArQBwAEIAI6ASuAroCvgJaAYyA04BtYDqgwBsAA0AJwAoABYAD0AIgARwAmABPgC2ALgAcwBDACJAFIAK0AZQA4ABzwFeAV8A3gB1AENgIvASIAloBjIDJAGeCADIABgASQAnACgAFgAPQAiABHACYAE8ALYAc4BDAESAKQAVoAygBwADngK8Ar4BvAENgIvASIAloBjIDJBQAoAFgATAAuACOAFIAMoAcEBXgFfAN4AzwVABACGMAEAAsACYAI4AUgA4ICvAK-AbwBngyACAEMcAvgAMAA8ADAANAAgABgAEkALAAtABeADoAI0ATQBOAChAFoAW4AvADCAGUANgAbgA5QCBAIIAQgAjABHACQAFEAKQAXIA1QBxAEJAJwAU0ArIBmQDQAH6AQ2At4Be4C_wGIgMUAY2AyABuYDmAHQgPMAeyPAIAAKgBOAFAAKgAegBFACkAK0AcABK4CugK-AfwBLQDGQGnANrgdSB1RAAqAAcAFgATYAvgDCAKQAW4A1QBxAEJAJwAVkAzIB-gFtALeAXuAxQBkADPAG5gOYIgCAAVADgAJXAV0BXwD-AJaAbXA6kDqiQBMAAwAFwAWAA5ACaAF8AQgApABqgEJAIwAU0ArIBmQDeAJaAUmAywBnhKAgAAsADIAHAAiABMAC4AGKAQwBEgCOAFGALcA6gCLwEiALzAgCUAUgAHAAaABAADAAJIAWABaADIAHQARgAmwBeAGEAMoAbIA3gDlAIAAggBCACMAEgAJYAUQApABqgDiAIQAS0ApoBWQDAgGZANAAfoBGoC9wF_gMUAZ4A3MBzADoYHUgdUA8wqAMgBOAFAAKgAigCtAJXAV0BXwEtALWAYyAyABpwDawA.dhAACEgAAAAA&includeExtendedEvents=true&appName=web&DRMCapabilities=widevine&deviceId=12f098a5-ecdd-44d5-bba9-9b918c4f1913&appVersion=7.4.2-50c72df610dfe1b89e4c5110547c8da17584191d&deviceType=web&deviceMake=edge-chromium&jwt=eyJhbGciOiJIUzI1NiIsImtpZCI6Ijc3YTBjYzBlLTkwMTAtNDRhNy1iNmJjLTBhNjcyZDIxODU3MSIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSUQiOiI0ODMwNWIzMC0zNDU3LTExZWUtYTdkMy02MmViZmRmZmZjY2IiLCJjbGllbnRJUCI6IjgwLjE4OS4xNzIuMTM1IiwiY2l0eSI6IkdsYXNnb3ciLCJwb3N0YWxDb2RlIjoiRzQ2IiwiY291bnRyeSI6IkdCIiwiZG1hIjowLCJhY3RpdmVSZWdpb24iOiJHQiIsImRldmljZUxhdCI6NTUuODA1LCJkZXZpY2VMb24iOi00LjI4OTksInByZWZlcnJlZExhbmd1YWdlIjoiZW4iLCJkZXZpY2VUeXBlIjoid2ViIiwiZGV2aWNlVmVyc2lvbiI6IjExNS4wLjE5MDEiLCJkZXZpY2VNYWtlIjoiZWRnZS1jaHJvbWl1bSIsImRldmljZU1vZGVsIjoid2ViIiwiYXBwTmFtZSI6IndlYiIsImFwcFZlcnNpb24iOiI3LjQuMi01MGM3MmRmNjEwZGZlMWI4OWU0YzUxMTA1NDdjOGRhMTc1ODQxOTFkIiwiY2xpZW50SUQiOiIxMmYwOThhNS1lY2RkLTQ0ZDUtYmJhOS05YjkxOGM0ZjE5MTMiLCJjbUF1ZGllbmNlSUQiOiIiLCJpc0NsaWVudEROVCI6ZmFsc2UsInVzZXJJRCI6IiIsImxvZ0xldmVsIjoiREVGQVVMVCIsInRpbWVab25lIjoiRXVyb3BlL0xvbmRvbiIsInNlcnZlclNpZGVBZHMiOmZhbHNlLCJlMmVCZWFjb25zIjpmYWxzZSwiZmVhdHVyZXMiOnsiaXNTdGl0Y2hlckVrcyI6dHJ1ZSwibXVsdGlQb2RBZHMiOnsiZW5hYmxlZCI6dHJ1ZX19LCJkcm0iOnsibmFtZSI6IndpZGV2aW5lIiwibGV2ZWwiOiJMMyJ9LCJpc3MiOiJib290LnBsdXRvLnR2Iiwic3ViIjoicHJpOnYxOnBsdXRvOmRldmljZXM6R0I6TVRKbU1EazRZVFV0WldOa1pDMDBOR1ExTFdKaVlUa3RPV0k1TVRoak5HWXhPVEV6IiwiYXVkIjoiKi5wbHV0by50diIsImV4cCI6MTY5MTQxMjM5NywiaWF0IjoxNjkxMzI1OTk3LCJqdGkiOiIzMTU4NzhmMC02NjM1LTRiNTAtOWJkYi0zOTM2ZTQzNDZhNmYifQ.eH8cHOUP-uQbpW8kyPIjSFfXrKhTt_JlRN_bv2P3lqo&CMCD=mtp%3D30300%2Cot%3Dm%2Csf%3Dh%2Csid%3D%220a714193-880f-4f38-b4b7-002d1bdca03c%22

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by nabeelr** [comment]
Where did you get that link from?

It didn't seem to work for me, but this link did: 
https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5d94a5451754e6a4298d1059/master.m3u8?advertisingId=channel&appName=rokuchannel&appVersion=1.0&bmodel=bm1&channel_id=channel&content=channel&content_rating=ROKU_ADS_CONTENT_RATING&content_type=livefeed&coppa=false&deviceDNT=1&deviceId=channel&deviceMake=rokuChannel&deviceModel=web&deviceType=rokuChannel&deviceVersion=1.0&embedPartner=rokuChannel&genre=ROKU_ADS_CONTENT_GENRE&is_lat=1&platform=web&rdid=channel&studio_id=viacom&tags=ROKU_CONTENT_TAGS

**Comment by Ghani201** [comment]
From Pluto TV

**Comment by Ghani201** [comment]
From Pluto TV

**Comment by freearhey** [comment]
Offline
