### ISSUE TITLE
Add: Rotana Comedy

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13740]
### Channel ID

rotanacomedy.sa

### Stream URL (optional)

https://dai.google.com/linear/hls/pa/event/cH1Es-kjT9yxOW7P5ZUGTw/stream/5b3a6bb8-fb1c-4eb3-bf1f-140ca9393a9c:GRQ/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
https://dai.google.com/linear/hls/event/cH1Es-kjT9yxOW7P5ZUGTw/master.m3u8 and shows 401.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/71f1761a72f9eb7646eac62f0a494731f685b56e/streams/sa.m3u#L102-L105
