### ISSUE TITLE
Add: Geo News

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13746]
### Channel ID

geonews.pk

### Stream URL (optional)

https://jk3lz82elw79-hls-live.5centscdn.com/GEONEWS/3500ba09d0538297440ca620c9dd46bf.sdp/GEONEWS/Backup1/chunks.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/71f1761a72f9eb7646eac62f0a494731f685b56e/streams/pk.m3u#L55-L56
