### ISSUE TITLE
Add: Dennis And Gnasher

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13750]
### Channel ID

dennisandgnasher.uk

### Stream URL (optional)

https://3c64981fc45348a5b3a8a83aef2c9cb7.mediatailor.us-east-1.amazonaws.com/v1/manifest/0fb304b2320b25f067414d481a779b77db81760d/RakutenTV-eu_DennisandGnasher/04557f0d-6c8f-4db8-8f72-b6c5e9eb29e3/2.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
https://beanostudios-dennis-and-gnasher-1-eu.rakuten.wurl.tv/playlist.m3u8
