### ISSUE TITLE
Add: Iqra TV

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13756]
### Channel ID

IqraTV.uk

### Stream URL (optional)

https://cdn5.iqsat.net/iqb/b5b9977ca31beabec903ba7b34e1c198.sdp/chunks.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/71f1761a72f9eb7646eac62f0a494731f685b56e/streams/uk.m3u#L85-L86
