### ISSUE TITLE
Add: Sky News

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13752]
### Channel ID

SkyNews.uk

### Stream URL (optional)

https://linear021-gb-hls1-prd-ak.cdn.skycdp.com/Content/HLS_001_sd/Live/channel(skynews)/09_hd30.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Not that keen on adding this one, as Sky UK's legal team doesn't really like their channels wandering around.

**Comment by Kasyas2011** [comment]
😎

**Comment by freearhey** [comment]
https://linear021-gb-hls1-prd-ak.cdn.skycdp.com/Content/HLS_001_sd/Live/channel(skynews)/09_hd30.m3u8 (offline)
<img width="772" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/ed439ff2-b21a-46c7-88fe-181d1c1445ba">
