### ISSUE TITLE
Add: Beano TV

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13751]
### Channel ID

BeanoTV.uk

### Stream URL (optional)

https://a5b4bacecd47433dad06d3189fc7422e.mediatailor.us-east-1.amazonaws.com/v1/manifest/04fd913bb278d8775298c26fdca9d9841f37601f/RakutenTV-eu_BeanoTV/b1f233d5-847c-437d-aa4f-f73e67a85323/2.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
https://beanostudios-beanotv-1-eu.rakuten.wurl.tv/playlist.m3u8
