### ISSUE TITLE
Broken: TV Trwam (POL)

### ISSUE THREAD

**Issue by arecki2** [iptv-org/iptv#13767]
### Broken Link

https://rd.insyscd.net/trwamtv.live/cl01/out/u/trwam.mpd

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://rd.insyscd.net/trwamtv.live/live/eds/tv-trwam/dash_fta/tv-trwam.mpd

### Notes (optional)

Changed link; video quality upgraded to 576p.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
hls, if needed : https://rd.insyscd.net/trwamtv.live/live/eds/tv-trwam/hls_fta/tv-trwam.m3u8
