### ISSUE TITLE
Broken: ABC me! [AU]

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#13765]
### Broken Link

https://abc-iview-mediapackagestreams-2.akamaized.net/out/v1/6e1cc6d25ec0480ea099a5399d73bc4b/index.m3u8

### What happened to the stream?

Shows looped video

### Notes (optional)

it shows cant stream outside australia

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by dantheman121** [comment]
it sohws a 7 second video saying "can't stream outside australia"

**Comment by BellezaEmporium** [comment]
it's because it's geo-blocked.

**Comment by dantheman121** [comment]
but i have vpn set to australia

**Comment by freearhey** [comment]
works fine from outside australia without a vpn

https://abc-iview-mediapackagestreams-2.akamaized.net/out/v1/6e1cc6d25ec0480ea099a5399d73bc4b/index.m3u8
<img width="786" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/8c8950db-39fa-442f-96e0-c3c9a79ceb29">

**Comment by dantheman121** [comment]
@freearhey thats abc news not abc me
