### ISSUE TITLE
Add: Fuji TV (JPN)

### ISSUE THREAD

**Issue by arecki2** [iptv-org/iptv#13769]
### Channel ID

JOCXDTV.jp

### Stream URL (optional)

https://fujitv4.mov3.co/hls/fujitv.m3u8

### Notes (optional)

Looks like mov3.co is back; was down a few months ago when I last checked.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by inklingboi08** [comment]
Should I delete my request so yours doesn't get deleted as a duplicate?

**Comment by BellezaEmporium** [comment]
They've leveled up in video quality, quite interesting.

**Comment by arecki2** [comment]
Yeah, glad to see them back :) however, something has changed, and it's quite strange... Fuji, Nippon TV, and all the channels streamed through odnoklaZZniki 🇷🇺💀 are working fine, whereas for NHK, I'm seeing the following error in browser console:

Access to XMLHttpRequest at 'https://nhk4.mov3.co/hls/nhk.m3u8' from origin 'http://mov3.co' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

http://mov3.co/ja/nhk/

BTW what happened to streams sourced from YouTube? They're no longer being added to the playlists on the front page 🙄

**Comment by BellezaEmporium** [comment]
> Yeah, glad to see them back :) however, something has changed, and it's quite strange... Fuji, Nippon TV, and all the channels streamed through odnoklaZZniki 🇷🇺💀 are working fine, whereas for NHK, I'm seeing the following error in browser console:
> 
> Access to XMLHttpRequest at 'https://nhk4.mov3.co/hls/nhk.m3u8' from origin 'http://mov3.co' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> 
> http://mov3.co/ja/nhk/
> 
> BTW what happened to streams sourced from YouTube? They're no longer being added to the playlists on the front page 🙄

Link you've referenced gives a 404 Not Found.

As for the YT channels, my server and ythls went down.

**Comment by yellowykids** [comment]
Works! Thanks. Now I can feel the full Japan drug power!❤️
