### ISSUE TITLE
Add: BBC Three HD (720p) [Geo-blocked]

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13771]
### Channel ID

BBCThree.uk

### Stream URL (optional)

https://vs-cmaf-pushb-uk-live.akamaized.net/x=3/i=urn:bbc:pips:service:bbc_three_hd/iptv_hd_abr_v1.mpd

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Ghani201** [comment]
Which Is Better BBC 3 Or Mbc3

**Comment by Kasyas2011** [comment]
Access Denied
You don't have permission to access "http://vs-cmaf-pushb-uk-

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/71f1761a72f9eb7646eac62f0a494731f685b56e/streams/uk_bbc.m3u#L192-L199
