### ISSUE TITLE
English Cooking Channels

### ISSUE THREAD

**Issue by pcfanatic** [iptv-org/iptv#1377]
Would **LOVE** a collection of food channels, like:

1. Food Network US
2. Food Network CA
3. Food Network UK
4. Cooking Channel US
5. Good Food
6. Cooking Channel CA
7. SBS Food
8. The Food Channel

Thank you so much for the IPTV project. The channels that you've managed to upload are more than we could ever ask for! Keep up the good work! ;)

**Comment by pcfanatic** [comment]
Any update on this? :)

**Comment by freearhey** [comment]
Food Network and Cooking Channel cannot be added to the playlist due to claims of the copyright holder. More details here: iptv-org/iptv: Issue #1831

**Comment by freearhey** [comment]
Closed in favor #1942 and #1945
