### ISSUE TITLE
Add: CBBC

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13778]
### Channel ID

cbbc.uk

### Stream URL (optional)

http://vs-hls-pushb-uk-live.akamaized.net/x=3/i=urn:bbc:pips:service:cbbc_hd/mobile_wifi_main_sd_abr_v2_akamai_hls_live_http.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/71f1761a72f9eb7646eac62f0a494731f685b56e/streams/uk_bbc.m3u#L228-L231
