### ISSUE TITLE
Add: KBS Korea (KOR) via YouTube

### ISSUE THREAD

**Issue by arecki2** [iptv-org/iptv#13776]
### Channel ID

KBSKorea.kr

### Stream URL (optional)

https://ythls.onrender.com/video/OxQQsIvJTTU.m3u8

### Notes (optional)

This is a different channel from KBS World. It runs general programming in Korean for expats (although at the moment it's a special emergency newscast on Typhoon Khanun, which is about to hit Korea tonight UTC).

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by arecki2** [comment]
Yeah, for some reason it fails to play in VLC, and ythls fails on it too... But it does play fine on YT, although DVR does not work, so maybe that's what complicates things...

**Comment by BellezaEmporium** [comment]
> Yeah, for some reason it fails to play in VLC, and ythls fails on it too... But it does play fine on YT, although DVR does not work, so maybe that's what complicates things...

It's because KBS Korea might be geo-blocked.
