### ISSUE TITLE
Broken: wbit tv 10

### ISSUE THREAD

**Issue by ki4nhs** [iptv-org/iptv#13772]
### Broken Link

https://livevideo01.wbir.com/hls/live/2016515/newscasts/live-2000.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by twodragon** [comment]
https://livevideo.tegnadigital.com/wbir/v1/master/f9c1bf9ffd6ac86b6173a7c169ff6e3f4efbd693/WBIR/elvs/live.m3u8
is true channel ?

**Comment by BellezaEmporium** [comment]
https://livevideo01.wbir.com/hls/live/2016515/elvs/live.m3u8

**Comment by ki4nhs** [comment]
Thank you ! Do you happen to have links for wvlt and wate in knoxville as well?

**Comment by ki4nhs** [comment]
Those links worked ..they're actually 10 News 2 ..which is a constant rerun of the news. I was also looking for the live wbir channel

**Comment by freearhey** [comment]
https://livevideo01.wbir.com/hls/live/2016515/newscasts/live-2000.m3u8
<img width="435" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/afbe796e-57f5-4e9a-85bb-818cff60f119">
