### ISSUE TITLE
Add: open tv hybrid 1 

### ISSUE THREAD

**Issue by Goldiefresh** [iptv-org/iptv#13780]
### Channel ID

Add: open tv hybrid 1

### Stream URL (optional)

https://opentvlive1.siliconweb.com/opentvliveabr/openlatin/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
As we don't have much information on this channel : Where does it comes from ? Does it streams football all the time ? What's the main programmation of this channel ?

**Comment by Goldiefresh** [comment]
Hello. Greek channel open tv have the rights to Brazil and Argentina football. Those three links I sent show live football when it's on and repeats of matches when no live matches on. Links taken from this website "https://www.tvopen.gr/live" click on "Live football matches of the Argentina-Brazil championship" at bottom of page.

Sent from Proton Mail mobile

-------- Original Message --------
