### ISSUE TITLE
Add: open tv hybrid 3

### ISSUE THREAD

**Issue by Goldiefresh** [iptv-org/iptv#13782]
### Channel ID

OpenTV.gr

### Stream URL (optional)

https://opentvlive1.siliconweb.com/opentvliveabr/openlatin3/playlist.m3u8

### Notes (optional)

South American football 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
The link does not show OpenTV:

<img width="1410" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/9d0b9fa9-6ab2-46c4-aff7-0e90947dff44">

And there is already a correct link in the playlist:

https://github.com/iptv-org/iptv/blob/71f1761a72f9eb7646eac62f0a494731f685b56e/streams/gr.m3u#L140-L141
<img width="1405" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/ebaee0b5-a51d-4335-a0cd-3bb5cd16c2cc">
