### ISSUE TITLE
Add: Discovery CZ [CZ]

### ISSUE THREAD

**Issue by Jakubicek222** [iptv-org/iptv#13798]
### Channel ID

DiscoveryChannelCzechRepublic.cz

### Stream URL (optional)

http://88.212.7.11/live/test_discovery_hd_hevc/playlist.m3u8

### Notes (optional)

![image](https://github.com/iptv-org/iptv/assets/106910269/513434c1-c567-43b8-815b-89fde4acf205)
name this channel in playlist Discovery CZ

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Sorry, but we cannot add the channel to the playlist due to claims of the copyright holder: https://github.com/iptv-org/iptv/issues/1831

**Comment by bubulka14** [comment]
Hi,please link to nova spot 1 and BBC Earth
Thank you

**Comment by sleduj-tv** [comment]
No links
