### ISSUE TITLE
Add: Rotana Kids

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13791]
### Channel ID

rotanakids.sa

### Stream URL (optional)

https://shls-rotanakids-prod-dub.shahid.net/out/v1/df6e0eb3cdc4410b98209aafc8677cef/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by UltraHDR** [comment]
Please search if the URL exists before creating an issue. Thanks

**Comment by Ghani201** [comment]
Ok
