### ISSUE TITLE
English Documentary Channels

### ISSUE THREAD

**Issue by pcfanatic** [iptv-org/iptv#1379]
If you by any chance could add any of these channels to the playlist, it would be great! (Think it could use a few more documentary channels. ;))

1. Animal Planet
2. BBC Earth
3. Crime & Investigation Network (US & UK)
4. Discovery Channel (US & UK)
5. Discovery Family (US)
6. Discovery Life (US)
7. Discovery Science (US & UK)
8. Discovery History (UK)
9. Discovery Turbo (UK)
10. National Geographic Adventure (Singapore)
11. Investigation Discovery (US)

Thanks again!

**Comment by pcfanatic** [comment]
Any update on this? :)

**Comment by freearhey** [comment]
Animal Planet, Investigation Discovery and all Discovery channels cannot be added to the playlist due to claims of the copyright holder. More details here: #1831

**Comment by freearhey** [comment]
Closed in favor #1943 and #1942
