### ISSUE TITLE
Add: AT-X (JPN)

### ISSUE THREAD

**Issue by ZXArkin** [iptv-org/iptv#13793]
### Channel ID

ATX.jp

### Stream URL (optional)

http://194.233.72.249:8080/AT-X/index.m3u8

### Notes (optional)

![AT-X_20230705_202525 551](https://github.com/iptv-org/iptv/assets/21299971/794c1cd4-fbe4-4b35-8a16-45127953ff65)
This is test AT-X channel JP without subs
720 Quality

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by vthanhtivi** [comment]
Switch the link to http://194.233.72.249:8080/AT-X/index.m3u8

**Comment by kdhh357** [comment]
链接已经改了

**Comment by ZXArkin** [comment]
Link change here:
http://194.233.72.249:8080/AT-X/index.m3u8

**Comment by misaka10843** [comment]
> http://194.233.72.249:8080/AT-X/index.m3u8 <img alt="image" width="1044" src="https://user-images.githubusercontent.com/7253922/266038138-618ce789-d63e-47bf-a81c-4da7f8cd25ac.png">

looks like the link is 502
