### ISSUE TITLE
Broken: Gulli Girl

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13807]
### Broken Link

http://188.40.68.167/russia/gulli_girl/playlist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
There is no such link in the repository.
