### ISSUE TITLE
Sports Channels

### ISSUE THREAD

**Issue by pcfanatic** [iptv-org/iptv#1380]
Country: United Kingdom

1. beIN Sports UK
2. BT Sport UK
3. Eurosport UK
4. Sky Sports UK

Country: United States

1. beIN Sports US
2. ESPN2 US
3. ESPN3 US
4. ESPN+ US
5. ESPNU US
6. SEC Network
7. Fight Network
8. Fight Tyme
9. NBA TV US
10. NFL Network
11. PAC-12 Network
12. WWE Network

**Comment by nasser-81** [comment]
No update soon here?

**Comment by pcfanatic** [comment]
Any update on this? :)

**Comment by freearhey** [comment]
ESPN2 US: https://github.com/iptv-org/iptv/blob/8636ab33efbacb32255b40c6ce0297fad6a72031/channels/us.m3u#L412-L413
ESPN U: https://github.com/iptv-org/iptv/blob/8636ab33efbacb32255b40c6ce0297fad6a72031/channels/us.m3u#L416-L417

**Comment by freearhey** [comment]
Eurosport cannot be added to the playlist due to claims of the copyright holder. More details here: #1831

**Comment by freearhey** [comment]
Closed in favor #1943 and #1942

**Comment by Kanaryam** [comment]
Türkçe beın sport iptv m3u8 varmı

**Comment by YacineSat77** [comment]
Where Can I get HTTPS IPTV not http

**Comment by guylolol54** [comment]
> 

try televisio but its only for android and google tv

**Comment by Glynis1** [comment]
Please can you give me a url to watch the lpga free -  in can’t find it on any golf channels.  Thanks very much.

**Comment by cold360** [comment]
I suppose we're not getting these any time soon? Domain expired for espn2
