### ISSUE TITLE
Broken: Markíza

### ISSUE THREAD

**Issue by Jakubicek222** [iptv-org/iptv#13801]
### Broken Link

http://83.167.253.107/hdmi1_ext

### What happened to the stream?

Other

### Possible Replacement (optional)

http://83.167.253.107/hdmi1_ext

### Notes (optional)

On this stream working Kino Barrandov (Czechia)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Same links.
