### ISSUE TITLE
Broken: M1 Hungary 

### ISSUE THREAD

**Issue by eleminity** [iptv-org/iptv#13809]
### Broken Link

https://iptv-org.github.io/iptv/countries/hu.m3u

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://hirado.hu/elo/m1

### Notes (optional)

First time posting so apologies if not following correct procedure. M1 had been working fine until two days ago. The original free-to-air source stream is still working fine https://hirado.hu/elo/m1 so I think the M3U just has an outdated link now? 

Amazing work btw thank you to everyone for maintaining this resource!

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
https://c401-node62-cdn.connectmedia.hu/110301/d64799395046e00016946e0fddc20977/64d7973a/index.m3u8 ?

**Comment by R4IN2007** [comment]
here some M1 Live m3u8's
https://nettv.flynet.hu/live/m1hd.m3u8

M1
http://194.76.186.33:8000/play/a00w/index.m3u8

M1 HD
http://194.76.186.33:8000/play/a024/index.m3u8
