### ISSUE TITLE
Add: Qatar TV

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13808]
### Channel ID

qatartv.qr

### Stream URL (optional)

https://qatartv.akamaized.net/hls/live/2026573/qtv1/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
https://github.com/iptv-org/iptv/blob/d5d680e0128ea636fd63db78c3f2a669f6254554/streams/qa.m3u#L31C1-L32

**Comment by Ghani201** [comment]
Thank You For Adding It BellezaEmporium

**Comment by Ghani201** [comment]
And UltraHDR

**Comment by Ghani201** [comment]
Now I Am Adding Qatar TV 2
