### ISSUE TITLE
Add: Gulli France

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13814]
### Channel ID

gulli.fr

### Stream URL (optional)

https://origin2-6play.live.6cloud.fr/pool_rnpls9by/gulli/sixplaysd/hls_short_q2hyb21h_gulli/NA/aVWvbjp/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Audio only.

**Comment by ALittleAnt4161** [comment]
> Audio only.

https://origin2-6play.live.6cloud.fr/pool_rnpls9by/gulli/sixplaysd/hls_short_q2hyb21h_gulli/index.m3u8
