### ISSUE TITLE
Broken: iFilm Persian

### ISSUE THREAD

**Issue by IchDu21** [iptv-org/iptv#13819]
### Broken Link

https://live1.presstv.ir/live/ifilmfa.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://live.aionet.ir/hls/ifilm/ifilm_540/index.m3u8

### Notes (optional)

(540p)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
Adaptive : https://live.aionet.ir/hls/ifilm/ifilm.m3u8
