### ISSUE TITLE
Add: IRIB Mostanad (540p)

### ISSUE THREAD

**Issue by IchDu21** [iptv-org/iptv#13817]
### Channel ID

IRIBMostanad.ir

### Stream URL (optional)

https://live.aionet.ir/hls/mostanad/mostanad_540/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Adaptive : https://live.aionet.ir/hls/mostanad/mostanad.m3u8
