### ISSUE TITLE
Add: IRIB Amouzesh (540p)

### ISSUE THREAD

**Issue by IchDu21** [iptv-org/iptv#13815]
### Channel ID

AmouzeshTV.ir

### Stream URL (optional)

https://live.aionet.ir/hls/amoozesh/amoozesh_540/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Adaptive : https://live.aionet.ir/hls/amoozesh/amoozesh.m3u8
