### ISSUE TITLE
Add: IRIB1

### ISSUE THREAD

**Issue by IchDu21** [iptv-org/iptv#13812]
### Channel ID

IRIB1.ir

### Stream URL (optional)

https://live.aionet.ir/hls/tv1/tv1_480/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Adaptive : https://live.aionet.ir/hls/tv1/tv1.m3u8
