### ISSUE TITLE
Add: IRIB Pooya & Nahal (540p)

### ISSUE THREAD

**Issue by IchDu21** [iptv-org/iptv#13822]
### Channel ID

PooyaTV.ir

### Stream URL (optional)

https://live.aionet.ir/hls/pooya/pooya_540/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by dantheman121** [comment]
it's 100% streamable
