### ISSUE TITLE
Add: IRIB Tamasha (540p)

### ISSUE THREAD

**Issue by IchDu21** [iptv-org/iptv#13820]
### Channel ID

Tamasha.ir

### Stream URL (optional)

https://live.aionet.ir/hls/tamasha/tamasha_540/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Adaptive : https://live.aionet.ir/hls/tamasha/tamasha.m3u8
