### ISSUE TITLE
Add: IRIB Salamat (540p)

### ISSUE THREAD

**Issue by IchDu21** [iptv-org/iptv#13821]
### Channel ID

SalamatTV.ir

### Stream URL (optional)

https://live.aionet.ir/hls/salamat/salamat_540/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Adaptive : https://live.aionet.ir/hls/salamat/salamat.m3u8
