### ISSUE TITLE
Add: Islam Channel 

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13839]
### Channel ID

islamchannel.uk

### Stream URL (optional)

https://live.islamchannel.tv/live7/islamtv_english/bitrate1.isml/bitrate1-audio_0=128000-video=2406976.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/54ab739b12bb53e42e72eacfeec1a7097d42b7d8/streams/uk.m3u#L93-L94

**Comment by Ghani201** [comment]
Thank You For Adding The m3u8 Sir

**Comment by freearhey** [comment]
@Ghani201 I've already [asked](https://github.com/iptv-org/iptv/issues/13771#issuecomment-1673700601) you to use the repository search before posting a request. If you post another duplicate I will have to block you for spamming.

https://github.com/search?q=repo%3Aiptv-org%2Fiptv+islamchannel.uk&type=code
https://github.com/iptv-org/iptv/blob/54ab739b12bb53e42e72eacfeec1a7097d42b7d8/streams/uk.m3u#L93-L94

**Comment by Ghani201** [comment]
Ok
