### ISSUE TITLE
Add: GEM TV

### ISSUE THREAD

**Issue by IchDu21** [iptv-org/iptv#13846]
### Channel ID

GEMTV.ir

### Stream URL (optional)

https://hd.90minlive.online/live/gemtv/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9OC8xMy8yMDIzIDk6MzY6NTcgQU0maGFzaF92YWx1ZT1HelU5RHVKcThoN3NEOHFMejNIUDlBPT0mdmFsaWRtaW51dGVzPTU=

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1d16dd3a9812d17f971213b4614bb8894c1cfdc6/streams/ir.m3u#L194-L195

**Comment by Nostradamus1973** [comment]
Good Morning,

Does anyone have a working link for Gem TV?

Thank you and have a nice day.

**Comment by SoCraftHDYT** [comment]
Is there a working link now?
