### ISSUE TITLE
Add: GEM Travel

### ISSUE THREAD

**Issue by IchDu21** [iptv-org/iptv#13849]
### Channel ID

GEMTravel.ir

### Stream URL (optional)

https://hd.90minlive.online/live/gemtravel/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9OC8xMy8yMDIzIDk6Mzk6NTggQU0maGFzaF92YWx1ZT1pZmlSVFJzdllMQzZzaUdQR2VnWUFRPT0mdmFsaWRtaW51dGVzPTU=

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1d16dd3a9812d17f971213b4614bb8894c1cfdc6/streams/ir.m3u#L200-L201
