### ISSUE TITLE
Add: Bahrain International

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13841]
### Channel ID

bahraininternational.bh

### Stream URL (optional)

https://5c7b683162943.streamlock.net/live/ngrp:bahraininternational_all/chunklist_w1242013554_b1700000.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/54ab739b12bb53e42e72eacfeec1a7097d42b7d8/streams/bh.m3u#L2-L3
