### ISSUE TITLE
Add: GEM Food

### ISSUE THREAD

**Issue by IchDu21** [iptv-org/iptv#13851]
### Channel ID

GEMFood.ir

### Stream URL (optional)

https://hd.90minlive.online/live/gemfood/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9OC8xMy8yMDIzIDk6NDI6MDIgQU0maGFzaF92YWx1ZT0zbVVOSGdvOVRHeWw1T1JLWWg1QmdBPT0mdmFsaWRtaW51dGVzPTU=

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1d16dd3a9812d17f971213b4614bb8894c1cfdc6/streams/ir.m3u#L204-L205
