### ISSUE TITLE
Add: Nova TV

### ISSUE THREAD

**Issue by dicheto** [iptv-org/iptv#13858]
### Channel ID

NovaTV.bg

### Stream URL (optional)

https://e121-ts.cdn.bg/ntv/fls/ntv_2.stream/chunklist.m3u8?at=7bf529fdfa842f0fc8537a96abd3bf8e

### Notes (optional)

Country: Bulgaria
Language: Bulgaria
Category: News/Entertainment

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Carlinhos027** [comment]
DMCA'd:
https://github.com/iptv-org/database/blob/master/data/blocklist.csv#L526

**Comment by dicheto** [comment]
What does Blocklist mean?

**Comment by dicheto** [comment]
I dont understand you. NovaTV is not N1! If NovaTV is banned, Nova News needs to be banned too.
