### ISSUE TITLE
Add: NovaNews 

### ISSUE THREAD

**Issue by dicheto** [iptv-org/iptv#13859]
### Channel ID

NovaNews.bg

### Stream URL (optional)

https://e121-ts.cdn.bg/ntv/fls/NNHD.stream/chunklist.m3u8?at=7bf529fdfa842f0fc8537a96abd3bf8e

### Notes (optional)

Category: News

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Offline.

<img width="704" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/ebae85a3-b7f0-4342-8223-0d505d226c75">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/e59ea3338191f73f36f59296b5d8b17c6830a234/streams/bg.m3u#L66-L67
