### ISSUE TITLE
Broken: Gem Junior

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13864]
### Broken Link

https://hd.90minlive.online/live/gemjunior/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9OC8xMy8yMDIzIDk6NDQ6NTkgQU0maGFzaF92YWx1ZT1xNFNTaEhadVVTeDJEOG1LUUZzV1lRPT0mdmFsaWRtaW51dGVzPTU=

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://hd.90minlive.online/live/gemjunior/chunks.m3u8?nimblesessionid=309188&wmsAuthSign=c2VydmVyX3RpbWU9OC8xMy8yMDIzIDEyOjI3OjI3IFBNJmhhc2hfdmFsdWU9VTZvQkpxcG4ySUpGSjJiTDJLMmdIUT09JnZhbGlkbWludXRlcz01

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by IchDu21** [comment]
This stream does not work as well...

**Comment by freearhey** [comment]
There is no such link in the repository.
