### ISSUE TITLE
Add: Hum News (720p)

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13865]
### Channel ID

humnews.pk

### Stream URL (optional)

https://ythls.onrender.com/channel/UC0Um3pnZ2WGBEeoA3BX2sKw.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/e59ea3338191f73f36f59296b5d8b17c6830a234/streams/pk.m3u#L63-L64
