### ISSUE TITLE
ATV Avrupa

### ISSUE THREAD

**Issue by berkayakciger** [iptv-org/iptv#13877]
### Channel ID

	 ATVAvrupa.tr

### Stream URL (optional)

https://ythls.onrender.com/channel/UCUVZ7T_kwkxDOGFcDlFI-hg.m3u8

### Notes (optional)

ATV-Avrupa

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by twodragon** [comment]
http://nimplus3.bozztv.com/atvavrupa/atvavrupa/playlist.m3u8 [geo-blocked]
