### ISSUE TITLE
Add: Al Jazeera Mubasher

### ISSUE THREAD

**Issue by Ghani201** [iptv-org/iptv#13878]
### Channel ID

aljazeeramubasher.qa

### Stream URL (optional)

https://live-hls-web-ajm.getaj.net/AJM/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
I warned you: https://github.com/iptv-org/iptv/issues/13839#issuecomment-1676108624

https://github.com/iptv-org/iptv/blob/e59ea3338191f73f36f59296b5d8b17c6830a234/streams/qa.m3u#L23-L24
