### ISSUE TITLE
Add: Aaj Tak

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#13881]
### Channel ID

AajTak.in

### Stream URL (optional)

https://feeds.intoday.in/aajtak/api/aajtakhd/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://feeds.intoday.in/aajtak/api/aajtakhd/master.m3u8
<img width="1397" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/5e632e93-224a-4384-a678-c3bc1d29e2c6">
