### ISSUE TITLE
Add: NHK General TV (JPN) (News Only) [Not 24/7]

### ISSUE THREAD

**Issue by arecki2** [iptv-org/iptv#13890]
### Channel ID

NHKGeneralTV.jp

### Stream URL (optional)

https://newssimul-stream.nhk.jp/hls/live/2010561/nhknewssimul/master-512k.m3u8

### Notes (optional)

I know this stream used to be featured in the playlists here but for some reason it's missing now. However, it is still used, active during NHK newscasts & special events only, such as now relaying NHK General TV's emergency format of hourly news, local studio opt-outs, and weather maps in-between, as Typhoon Lan is about to make landfall in a few hours.

As previously, during breaks between newscasts, I suppose the stream still goes off-air.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
This is a simulcast of their NHK News system. A sort of 24/7 stream.

Adaptive : https://newssimul-stream.nhk.jp/hls/live/2010561/nhknewssimul/master.m3u8

Though I can confirm (from another stream) that NHK G also streams the same content.

![nhkg](https://github.com/iptv-org/iptv/assets/30985701/2ae9bee9-bfe1-4f47-a292-e51f72f90615)

**Comment by arecki2** [comment]
We'll see whether it does go off after this morning show or not

They do blank out some content though, as mentioned, specifically off-the-topic of the day (a typhoon in this case, but in the past these were other severe weather events as well as national elections).

![image](https://github.com/iptv-org/iptv/assets/18574440/14e6214b-16ee-4db5-b6e9-a18316aff29d)
