### ISSUE TITLE
Add: NHK World Premium (JPN) (News only) [Not 24/7]

### ISSUE THREAD

**Issue by arecki2** [iptv-org/iptv#13892]
### Channel ID

NHKWorldPremium.jp

### Stream URL (optional)

https://cdn.nhkworld.jp/www11/nhkworld-tv/pre/hlscomp.m3u8

### Notes (optional)

This is the official output from NHK World Premium they allow to watch for free overseas, as normally it's a paid channel.

All broadcasts are news only.

Looks like it carries slightly less content than the NHK News stream I requested earlier today, but it's in better picture quality (720p), and it shows nice landscapes of Tokyo outside of broadcast hours ;) rather than shutting down completely.

Stream schedule: https://www3.nhk.or.jp/nhkworld/ja/premiumlive/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Though I believe this is the classic NHK World channel. Premium is a cable-only channel. It *was* broadcasted until the link became well-known. It was removed shortly. The real Premium channel has the "NHK" watermarked logo on the top left part of the screen.
