### ISSUE TITLE
Add: Weathernews (JPN) via YouTube

### ISSUE THREAD

**Issue by arecki2** [iptv-org/iptv#13893]
### Channel ID

Weathernews.jp

### Stream URL (optional)

https://ythls.onrender.com/channel/UCNsidkYpIAQ4QaufptQBPHQ.m3u8

### Notes (optional)

Let's try them 😼

I've just learned that they change streams for their TV broadcasts on YouTube every 3 hours, so even with additional streams they occasionally activate (such as now during Typhoon Lan), the YT API should manage to pick the correct feed in most cases 😜

Otherwise, an advantage over the two streams that already are in the database is that the YT broadcasts are in 1080p (vs 720p).

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Well, we can call this one "WNI Streams". We do have the original stream, from MX Casting.
