### ISSUE TITLE
Add: Diema Family

### ISSUE THREAD

**Issue by dicheto** [iptv-org/iptv#13920]
### Channel ID

DiemaFamily.bg

### Stream URL (optional)

http://new-pro.tv:8080/99622282/etbVXafU6f/28156

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Sorry, but we cannot add the channel to the playlist due to claims of the copyright holder: https://github.com/iptv-org/iptv/issues/6486
