### ISSUE TITLE
Add: Nick JR

### ISSUE THREAD

**Issue by dicheto** [iptv-org/iptv#13928]
### Channel ID

NickJrBulgaria.bg

### Stream URL (optional)

http://new-pro.tv:8080/99622282/etbVXafU6f/179001

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by dantheman121** [comment]
access is denied
