### ISSUE TITLE
Add: Kino Nova

### ISSUE THREAD

**Issue by dicheto** [iptv-org/iptv#13926]
### Channel ID

KinoNova.bg

### Stream URL (optional)

http://new-pro.tv:8080/99622282/etbVXafU6f/178997

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Carlinhos027** [comment]
Xtream codes are not allowed on here.

**Comment by dicheto** [comment]
> Xtream codes are not allowed on here.

It's not written in the contributing guide and it is working?

**Comment by freearhey** [comment]
@Carlinhos027 @dicheto is right, there is no mention in the [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md) that Xtream links are not allowed.

**Comment by freearhey** [comment]
@dicheto The link doesn't work.

**Comment by Carlinhos027** [comment]
> @Carlinhos027 @dicheto is right, there is no mention in the [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md) that Xtream links are not allowed.

Xtream codes are illegal streams.

**Comment by freearhey** [comment]
Sorry, but we cannot add the channel to the playlist due to claims of the copyright holder: https://github.com/iptv-org/iptv/issues/6486
