### ISSUE TITLE
Add: MSNBC (USA)

### ISSUE THREAD

**Issue by chris202020202020** [iptv-org/iptv#13969]
### Channel ID

MSNBC.us

### Notes (optional)

please add m3u link for msnbc (USA)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Duplicate of https://github.com/iptv-org/iptv-org.github.io/issues/505
