### ISSUE TITLE
Broken: Meth TV [LK] 

### ISSUE THREAD

**Issue by abubakar1981** [iptv-org/iptv#13966]
### Broken Link

https://ythls.onrender.com/channel/UC7kBHRaynsJMB6JcooGLTmA.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
For a link that wasn't even added on the playlists ?
