### ISSUE TITLE
CNBC (USA)

### ISSUE THREAD

**Issue by chris202020202020** [iptv-org/iptv#13968]
### Channel ID

CNBC.us

### Notes (optional)

add m3u link for cnbc (USA)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Duplicate of https://github.com/iptv-org/iptv-org.github.io/issues/975
