### ISSUE TITLE
CW Channel on US

### ISSUE THREAD

**Issue by renanbastos93** [iptv-org/iptv#1397]
work not this channel I guess it is CW Channel
https://github.com/iptv-org/iptv/blob/986b2324b831ec55c01197e4b31d68ce0f29ba93/channels/us.m3u#L299

**Comment by renanbastos93** [comment]
I found this link: http://iptv8.premium-stv.com:2052/live/SOURCEUSAPRO1d/687616d9712@/1793.m3u8

**Comment by freearhey** [comment]
@renanbastos93 If you want, you can add a link to the channel in playlist yourself. Just read this guide before you do it: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#add-channel

**Comment by freearhey** [comment]
Closed in favor #1942
