### ISSUE TITLE
Arabic channels down

### ISSUE THREAD

**Issue by jad222** [iptv-org/iptv#1400]
**What's wrong?**
Many of arab channels goes down
**Country of the channel:**
Lebanon, Egypt .....
**Channel Name:**
MTV Lebanon
CBC
Cartoon Network
**Broken Link:**

http://95.170.215.109:80/hls/m3u8/CNArabica-Backup.m3u8
http://95.170.215.109/hls/CBC-Backup-M.m3u8
http://livecdnh2.tvanywhere.ae/hls/cap_brd_cen/index.m3u8
http://livecdnh3.tvanywhere.ae/hls/MTVLbnHD/index.m3u8
**Additional Information (optional):**
it seems like all links from this server broken tvanywhere.ae
so many arabic channel down :(

**Comment by freearhey** [comment]
Thank you for noticing! I deleted all the broken links.

**Comment by Link4K** [comment]
tvanywhere.ae works with UAE vpn

**Comment by freearhey** [comment]
@Link4K So these links are geo-blocked?

**Comment by Link4K** [comment]
Yes, tvanywhere.ae is now geo-blocked.
http://95.170.215 is down

**Comment by jad222** [comment]
I tried UAE vpn and didn't work eather @Link4K
