### ISSUE TITLE
Broken: Replace Sd feed of Manorama News with HD

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#14007]
### Broken Link

http://103.199.161.254/Content/manoramanews/Live/Channel(ManoramaNews)/index.m3u8

### What happened to the stream?

Other

### Possible Replacement (optional)

https://www.youtube.com/watch?v=tgBTspqA5nY

### Notes (optional)

There is already an hd live stream of this channel in youtube. that'd be idea if it can be replaced.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment]
https://ythls.onrender.com/channel/UCP0uG-mcMImgKnJz-VjJZmQ.m3u8

**Comment by freearhey** [comment]
http://103.199.161.254/Content/manoramanews/Live/Channel(ManoramaNews)/index.m3u8
<img width="788" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/90308a85-a6ba-452d-b383-9d5fa52f24f8">

**Comment by freearhey** [comment]
Closed in favor of #14179
