### ISSUE TITLE
Broken: MRTV NRC

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#14004]
### Broken Link

http://183.89.246.119:8881/play/a07o/index.m3u8

### What happened to the stream?

Stuck at a single frame

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by arecki2** [comment]
Guess it's working fine atm... although all it's showing is colour bars & a 1kHz test tone - although I'm hearing it continuously 😜

**Comment by R4IN2007** [comment]
Stream works fine and here's there twitch stream for MRTV NRC
https://mrtv.gov.mm/mm/live-stream (www.twitch.tv/channelmrt)
