### ISSUE TITLE
Broken: EBS 1TV

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#14039]
### Broken Link

https://ebsonair.ebs.co.kr/ebs1familypc/familypc1m/playlist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by arecki2** [comment]
OK for me.

**Comment by sunyuanzhe** [comment]
It's Not Working For Me

**Comment by arecki2** [comment]
Could it be that The Great Firewall decided to brick those Korean schoolchildren's shows as submersive content? 👺
