### ISSUE TITLE
Add: match 4(hu)

### ISSUE THREAD

**Issue by erich1997** [iptv-org/iptv#14034]
### Channel ID

Match4.hu

### Stream URL (optional)

http://194.76.186.33:8000/play/a04d/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://194.76.186.33:8000/play/a04d/index.m3u8
<img width="790" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/5233415b-bc9d-426c-83e0-b18900d48e92">
