### ISSUE TITLE
Broken: PBS Phoenix AZ (KAET)

### ISSUE THREAD

**Issue by OmarLopez18** [iptv-org/iptv#14040]
### Broken Link

https://kaetdt.lls.pbs.org/out/v1/259f25e61b3d47ce8a7e2339a00c5561/index.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Carlinhos027** [comment]
It seems the link is Geo-blocked

**Comment by OmarLopez18** [comment]
@Carlinhos027 Sadly that is not the case. I'm local to that area. It appears they have change from using m3u8 to mpd format to for users to watch their stream from the pbs website.
