### ISSUE TITLE
Broken: TVB Jade (翡翠台) (Cantonese Subtitles)

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#14045]
### Broken Link

http://23.237.10.66:16106/

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
There is no such link in the repository.
