### ISSUE TITLE
Add: MotorTrend Fast TV

### ISSUE THREAD

**Issue by AudioNutz** [iptv-org/iptv#14057]
### Channel ID

FastTV.us

### Stream URL (optional)

https://3fa797d5.wurl.com/manifest/f36d25e7e52f1ba8d7e56eb859c636563214f541/T05PX01vdG9yVHJlbmRGYXN0VFZfSExT/b5e5e0e2-12b3-4312-93c9-c0a7c50b41ca/4.m3u8

### Notes (optional)

A free stream from MotorTrend TV

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
https://3fa797d5.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/T05PX01vdG9yVHJlbmRGYXN0VFZfSExT/playlist.m3u8


T05PX01vdG9yVHJlbmRGYXN0VFZfSExT = ONO_MotorTrendFastTV_HLS
