### ISSUE TITLE
Lebanese channels 

### ISSUE THREAD

**Issue by asa-sal** [iptv-org/iptv#1405]
Hi 
I am wondering if possible to restore the Lebanese channels please

Thank You

**Comment by jad222** [comment]
It would be awesome if you can bring back other Arab channels also ❤️

**Comment by freearhey** [comment]
@asa-sal Please provide channel names

**Comment by sinoel** [comment]
Arabic aljadeed LDC LBC is Not working why?
Can u fix it please?

**Comment by hawrazsabr** [comment]
Please i need all kurdish channel?

**Comment by asa-sal** [comment]
https://iptv-org.github.io/iptv/countries/lb.m3
Arabic aljadeed LDC LBC NBN OTV MTV...
Thank You

**Comment by freearhey** [comment]
@hawrazsabr If you want your request to be seen by the rest of the community, you'd better create a separate issue for it here: https://github.com/iptv-org/iptv/issues/new/choose

**Comment by freearhey** [comment]
Closed in favor #1431
