### ISSUE TITLE
Add: Animax Revival

### ISSUE THREAD

**Issue by JustSammyV** [iptv-org/iptv#14056]
### Channel ID

AnimaxRevival.cl (issue [#4829](https://github.com/iptv-org/database/issues/4829) on /database)

### Stream URL (optional)

https://streaming.zappix.live:3062/live/animaxlive.m3u8

### Notes (optional)

Sourced from administrators public chat on Telegram @AnimaxLA 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BellezaEmporium** [comment]
Waiting for the necessary changes to be done on /database before doing any PR.
