### ISSUE TITLE
Broken: TV3 Malaysia from my.m3u

### ISSUE THREAD

**Issue by e0406370** [iptv-org/iptv#14063]
### Broken Link

https://live-sg1.global.ssl.fastly.net/live-hls/tonton1.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://www.livetvmalaysia.online/2019/04/tv3.html

### Notes (optional)

Unable to access the TV3 stream through iptv player android app, while other links such as TV1 and TV2 in the m3u8 file are functioning correctly.
Any guidance or support provided would be greatly appreciated.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by theadder** [comment]
Every site I found is using:

https://live-streams-ssai-01.tonton.com.my/live/2dd2b7cd-1b34-4871-b669-57b5c9beca23/live.isml/.m3u8

**Comment by BellezaEmporium** [comment]
> Every site I found is using:
> 
> https://live-streams-ssai-01.tonton.com.my/live/2dd2b7cd-1b34-4871-b669-57b5c9beca23/live.isml/.m3u8

works for me.
