### ISSUE TITLE
Add: Tokyo MX1 (JPN)

### ISSUE THREAD

**Issue by chris202020202020** [iptv-org/iptv#14076]
### Channel ID

TokyoMX1.jp

### Notes (optional)

Yes I Would Like Some New Stream URLs For Tokyo MX1

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1d16dd3a9812d17f971213b4614bb8894c1cfdc6/streams/jp.m3u#L46-L49
