### ISSUE TITLE
Broken: SBS UBC

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#14082]
### Broken Link

http://59.23.231.102:1935/live/UBCstream/playlist.m3u8

### What happened to the stream?

Constantly interrupts/lagging

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Alstruit** [comment]
That is the server problem. Nothing we can do.
