### ISSUE TITLE
Broken: SBS TJB

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#14084]
### Broken Link

http://1.245.74.5:1935/live/tv/.m3u8

### What happened to the stream?

Constantly interrupts/lagging

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Alstruit** [comment]
That is the server problem. Nothing we can do.
