### ISSUE TITLE
Broken: SBS KBC

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#14083]
### Broken Link

http://119.200.131.11:1935/KBCTV/tv/playlist.m3u8

### What happened to the stream?

Constantly interrupts/lagging

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by ztreamhd** [comment]
Official page has this stream: 
`#EXTINF:-1 tvg-id="KBCTV.kr",SBS KBC (KBC 광주방송) (1080p)`
`https://vod.ikbc.co.kr/KBCTV/tv/playlist.m3u8`

**Comment by sunyuanzhe** [comment]
This one still having the same problem

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: ztreamhd ***@***.***>
发送时间: Tuesday, August 29, 2023 6:58:58 PM
收件人: iptv-org/iptv ***@***.***>
抄送: sunyuanzhe ***@***.***>; Author ***@***.***>
主题: Re: [iptv-org/iptv] Broken: SBS KBC (Issue #14083)


Official page has this stream:
#EXTINF:-1 tvg-id="KBCTV.kr",SBS KBC (KBC 광주방송) (1080p)
https://vod.ikbc.co.kr/KBCTV/tv/playlist.m3u8
