### ISSUE TITLE
Rename: Channel 7 (1080p)

### ISSUE THREAD

**Issue by Soponwit19997** [iptv-org/iptv#14099]
### Stream URL

https://live-cdn-hwc.ch7.com/livech7hd/HD_1080?vhost=streaming-hwc.ch7.com

### Correct ID

Channel7.th

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
There is no such link in the playlists.
