### ISSUE TITLE
Add: can you please add mbc 2 

### ISSUE THREAD

**Issue by Karam15464** [iptv-org/iptv#14094]
### Channel ID

MBC2.ae

### Stream URL (optional)

http://www.elahmad.com/tv/mobiletv/glarb.php?id=mbc2_tv_1

### Notes (optional)

Can you please add it   

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
That link is tokenized. Please see #13753
