### ISSUE TITLE
Add VIVA TV RUSSIA

### ISSUE THREAD

**Issue by vasilyevmichail** [iptv-org/iptv#1409]
**Country of the channel:**
Russia

**Channel Name:**
VIVA TV RUSSIA

**Channel Language:**
Russian

**Additional Information (optional):**

Logo:   https://i.imgur.com/qCLICfC.jpg
URL :   https://hls.myvideocontent.ru/hls2/vivarussia/index.m3u8

**Comment by freearhey** [comment]
If you want you can add a channel to the playlist yourself. 

If you don't know exactly how to do it, here's a guide: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#add-channel

**Comment by vasilyevmichail** [comment]
I have an error when I try push to master branch:

https://vasilyevmichail@github.com/iptv-org/iptv: git-receive-pack not permitted

Can you do it to help me ?

#EXTINF:-1 tvg-id="viva-tv" tvg-name="VIVA TV" tvg-language="Russian" tvg-logo="https://i.imgur.com/qCLICfC.jpg" group-title="Music",VIVA TV
https://hls.myvideocontent.ru/hls2/vivarussia/index.m3u8
