### ISSUE TITLE
Broken: Temple University TV

### ISSUE THREAD

**Issue by FpFan65** [iptv-org/iptv#14096]
### Broken Link

https://templeuni.secure.footprint.net/egress/bhandler/templeuni/streama/manifest.m3u8

### What happened to the stream?

Other

### Possible Replacement (optional)

https://livestream.telvue.com/templeuni1/f7b44cfafd5c52223d5498196c8a2e7b.sdp/playlist.m3u8

### Notes (optional)

Updated Stream

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
The replacement is already on the playlist: 
https://github.com/iptv-org/iptv/blob/72d8fba38a5588115eef86fa09031a8781be847f/streams/us.m3u#L957-L958
