### ISSUE TITLE
Rename: NBT 2HD (720p)

### ISSUE THREAD

**Issue by Soponwit19997** [iptv-org/iptv#14102]
### Stream URL

https://cdn6.giprimetime.info/feed/202306140918/chnbt/index.m3u8

### Correct ID

NBT2HD.th

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
There is no such link in the playlists.
