### ISSUE TITLE
links down

### ISSUE THREAD

**Issue by baraa47** [iptv-org/iptv#1410]
Al Arabiya
Al Arabiya Al Hadath
some of Lebanon and syria playlists aren't working

**Comment by freearhey** [comment]
I have both channels working fine.
<img width="766" alt="Captura de pantalla 2020-05-23 a las 18 07 24" src="https://user-images.githubusercontent.com/7253922/82733963-488dfa80-9d20-11ea-9583-7938b24a89b7.png">
<img width="762" alt="Captura de pantalla 2020-05-23 a las 18 06 13" src="https://user-images.githubusercontent.com/7253922/82733962-475ccd80-9d20-11ea-83db-086c8bc8c411.png">

**Comment by CHJ85** [comment]
@baraa47 A VPN always does the trick 😀

**Comment by baraa47** [comment]
yea i just figured out that turkey blocked alarabiya website and the channel's link is from the main website that's why it's not working anymore in turkey

**Comment by hawrazsabr** [comment]
Hello i need kurdish channel ?
