### ISSUE TITLE
Broken: SBS TBC (TBC 대구방송) (540p)

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#14108]
### Broken Link

https://tistory3.daumcdn.net/tistory/2864460/skin/images/Public_8.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Hey guys, I found this link on https://github.com/iptv-org/iptv/blob/master/streams/kr.m3u is either working or not working when I'm using an UrbanVPN in order to switch it to South Korea when I'm using VLC media player despite my South Korean friend claims this link is working probably it was encrypted or unencrypted.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Alstruit** [comment]
It works fine on my vpn. No referrer or user agent needed.

**Comment by AVGCFan1995** [comment]
Hey @Alstruit @freearhey, where to find the livestream links for EBS America since it's hard-to-find nowadays.

Here's the link.

https://github.com/orgs/iptv-org/discussions/1423
