### ISSUE TITLE
Add: Amarin TV (720p)

### ISSUE THREAD

**Issue by Soponwit19997** [iptv-org/iptv#14105]
### Channel ID

AmarinTV.th

### Stream URL (optional)

https://cdn6.goprimetime.info/feed/202306140918/chamarin/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://cdn6.goprimetime.info/feed/202306140918/chamarin/index.m3u8
<img width="1401" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/61f1d130-613e-4271-9c0f-b92fa4b6edd7">
