### ISSUE TITLE
Add: MCOT HD (720p)

### ISSUE THREAD

**Issue by Soponwit19997** [iptv-org/iptv#14104]
### Channel ID

MCOTHD.th

### Stream URL (optional)

https://cdn6.goprimetime.info/feed/202306140918/chmcothd/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://cdn6.goprimetime.info/feed/202306140918/chmcothd/index.m3u8
<img width="1407" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/c077d150-6f0e-43cb-921b-6c28fa672104">
