### ISSUE TITLE
Rename: JKN 18 (576p)

### ISSUE THREAD

**Issue by Soponwit19997** [iptv-org/iptv#14103]
### Stream URL

https://cdn6.giprimetime.info/feed/202306140918/newtv/index.m3u8

### Correct ID

JKN18.th

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
There is no such link in the playlists.
