### ISSUE TITLE
Broken: Every joj.sk stream is down

### ISSUE THREAD

**Issue by tapinko** [iptv-org/iptv#14110]
### Broken Link

https://github.com/iptv-org/iptv/blob/master/streams/sk_joj.m3u

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Carlinhos027** [comment]
Not all. Just the "https://st01-1.iptv.joj.sk/" links.

**Comment by Alstruit** [comment]
#14124
