### ISSUE TITLE
Add: XHGV-TDT (MX)

### ISSUE THREAD

**Issue by chris202020202020** [iptv-org/iptv#14117]
### Channel ID

XHGVTDT.mx

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/2ec4b73736605d30bb1bbfd09146af88fd2a0015/streams/mx.m3u#L208-L209
