### ISSUE TITLE
Broken: Canal 5 (MX)

### ISSUE THREAD

**Issue by chris202020202020** [iptv-org/iptv#14120]
### Broken Link

http://190.61.102.67:2000/play/a038/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Replacement For A Broken Stream To A New Stream For Canal 5 (MX) Please

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
The link has been removed from the playlist.
