### ISSUE TITLE
Broken: RIK2 Cyprus

### ISSUE THREAD

**Issue by ROBGagn** [iptv-org/iptv#14139]
### Broken Link

http://l6.cloudskep.com/rikcy/rik2/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Token needed...
Same issue with RIK 1 and HD. May happen in the future with ANT1 Cyprus, Sigma and Omega.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by iptvnikolas** [comment]
http://l6.cloudskep.com/tvb6/rik2-1/mpeg.2ts

**Comment by JohnyGR22** [comment]
Broken. Any update?
