### ISSUE TITLE
Broken: RIK1 Cyprus

### ISSUE THREAD

**Issue by ROBGagn** [iptv-org/iptv#14138]
### Broken Link

http://l6.cloudskep.com/rikcy/rik1/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Token needed...
Same issue with RIK 2 and HD, Alpha TV Cyprus. May happen in the future with ANT1 Cyprus, Sigma and Omega.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by iptvnikolas** [comment]
http://l6.cloudskep.com/tvb6/rik1-1/mpeg.2ts
