### ISSUE TITLE
Broken: Alpha TV Cyprus

### ISSUE THREAD

**Issue by ROBGagn** [iptv-org/iptv#14137]
### Broken Link

http://l4.cloudskep.com/alphacyp/acy/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Token now needed...
Same issue with RIK 1, 2 and HD. May happen in the future with RIK Sat, ANT1 Cyprus, Sigma and Omega.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by iptvnikolas** [comment]
Works properly

**Comment by iptvnikolas** [comment]
It works fine on my vpn. No referrer or user agent needed.

**Comment by ROBGagn** [comment]
Hello,

Which VPN are you using ? I tried
http://l4.cloudskep.com/alphacyp/acy/playlist.m3u8 with Private VPN and
Nord VPN and it's not working.

Regards,

Robert

**Comment by freearhey** [comment]
http://l4.cloudskep.com/alphacyp/acy/playlist.m3u8
<img width="375" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/510e72d3-f86f-41d3-baea-a99bba520fc5">
