### ISSUE TITLE
Add: Food Network Italy

### ISSUE THREAD

**Issue by giovannivetere** [iptv-org/iptv#14145]
### Channel ID

FoodNetworkItaly.it

### Stream URL

https://sbshdlu5-lh.akamaihd.net/i/sbshdl_6@1000854/master.m3u8

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
Offline
<img width="498" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/5ed11011-05f5-45df-a87b-6e285b86c3fe">
