### ISSUE TITLE
Broken: RIK HD Cyprus

### ISSUE THREAD

**Issue by ROBGagn** [iptv-org/iptv#14140]
### Broken Link

http://l6.cloudskep.com/rikcy/rikhd/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Token needed...
Same issue with RIK 1 and 2. May happen in the future with ANT1 Cyprus, Sigma and Omega.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by iptvnikolas** [comment]
http://l6.cloudskep.com/tvb6/rikhd1/mpeg.2ts

**Comment by ROBGagn** [comment]
Thanks for the link. This one is only 720p not 1080p as on the cybc
website...

**Comment by JohnyGR22** [comment]
Broken.
Any update?
