### ISSUE TITLE
Add: Azteca 7 Mexico City (MX)

### ISSUE THREAD

**Issue by chris202020202020** [iptv-org/iptv#14146]
### Channel ID

Azteca7MexicoCity.mx

### Stream URL

https://stream-us-east-1.getpublica.com/playlist.m3u8

### Label

Geo-blocked

### Notes (optional)

new stream link for Azteca 7 Mexico City please

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
Sorry, but we cannot add the channel to the playlist due to claims of the copyright holder: https://github.com/github/dmca/blob/master/2020/09/2020-09-16-dfl.md
