### ISSUE TITLE
Issues with Croatian channels 

### ISSUE THREAD

**Issue by aussiecroat** [iptv-org/iptv#1415]
These are not working on my tv app but work on my phone. Why is that ? Any ideas ? Can these channels be checked ?
**Channel Name:**
Hrt 1, Hrt 2, Hrt 3, Hrt 4, RTL, RTL Hrvatska

**Croatian**

**Additional Information (optional):**

**Comment by freearhey** [comment]
@aussiecroat All channels in the playlist are labeled "NO KODI" which means they should work everywhere except Kodi Media Player. So just try to use some other app on the TV if possible.
