### ISSUE TITLE
remove XXX channels to be opt out?

### ISSUE THREAD

**Issue by x5engine** [iptv-org/iptv#1416]
Hello guys,

can you remove the XXX adult channels and make this opt-out.

we have family and children watching so we don't want them to see anything not good.

this can be in another branch or repo or even another link/ list?

this is very important thanks.

I don't want to fork this and remove it myself since I want to have the latest changes.

thanks

**Comment by freearhey** [comment]
If you want, you can choose a playlist for a certain category here: https://github.com/iptv-org/iptv#playlists-by-category

Or you can create your own playlist from all available ones, for example through this app: https://channelizer.tv/

**Comment by x5engine** [comment]
very nice thank you but would it stay updated

**Comment by hawrazsabr** [comment]
Hi, please i want kurdish channel

**Comment by freearhey** [comment]
@x5engine All playlists in the [list](https://github.com/iptv-org/iptv#playlists-by-category) are automatically updated every day.

**Comment by opm0** [comment]
XXX channels shouldn't be in the country/language playlists IMO.

**Comment by freearhey** [comment]
@opm0 why?

**Comment by opm0** [comment]
XXX channels on TV providers are always opt-in and kept separate or hidden. That kind of content in general is usually separated from other content on the internet. I don't think most people going through channels in a language are interested in finding the XXX channels in that language, or that people who are interested in finding those channels wouldn't just use the XXX playlist.

**Comment by freearhey** [comment]
@opm0 in that case, it's also reasonable to remove the music and fashion channels from 
country/language playlists.

**Comment by opm0** [comment]
None of what I said applies to music or fashion channels.

**Comment by freearhey** [comment]
@opm0 okay, I guess I misunderstood what you had to say.

**Comment by x5engine** [comment]
@freearhey he has a very good point! most people want to watch channels with their family and also on any website or iptv provider there is a warning and requirement to check to opt in or out of the XXX channels! so this is very serious! so just put the adult channels in their own playlist and let us enjoy this great repo please thanks

**Comment by freearhey** [comment]
@x5engine The fact is, this repository is not a service. We only collect and store links to broadcasts and do not filter channels that get into playlists in any way. So if you want to remove some channels from your playlist, you better do it yourself.

**Comment by x5engine** [comment]
Sure on it ;)

**Comment by xbyubryan** [comment]
i love xxx channels very much!

**Comment by rrjanbiah** [comment]
I see that this is addressed except for the category playlist. IMHO, that too can be branched out.
