### ISSUE TITLE
Add: France 3 Picardie

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#14168]
### Channel ID

France3Picardie.fr

### Stream URL

http://livetv.ktv.zone/230/play.m3u8

### Label

None

### Notes (optional)

Source: https://github.com/iptv-org/iptv-org.github.io/issues/1369

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Picardie -> Hauts-de-France.
Fusion with the Nord-Pas-de-Calais

**Comment by freearhey** [comment]
If I understand correctly in this region there are two channels one of which is "France 3 Picardie".

https://www.france.tv/france-3/hauts-de-france/
<img width="619" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/9992d02b-76b7-4db7-9ee4-e1f254cc3365">

**Comment by BellezaEmporium** [comment]
> If I understand correctly in this region there are two channels one of which is "France 3 Picardie".
> 
> https://www.france.tv/france-3/hauts-de-france/
> <img width="619" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/9992d02b-76b7-4db7-9ee4-e1f254cc3365">
> 

Yep
