### ISSUE TITLE
Channel Keeps Refreshing Before Stopping Connection

### ISSUE THREAD

**Issue by pcfanatic** [iptv-org/iptv#1418]
Country: United States

Channels affected: Tastemade, Edge Sports

Problem: The channels have connection but they keep refreshing when the channels automatically change resolution and they eventually stop connecting altogether. (Links could possibly have a problem?)

**Comment by freearhey** [comment]
I have both channels working fine.

**Comment by hawrazsabr** [comment]
Please just i need a kurdish channel...
-- 
Sent from Gmail Mobile
