### ISSUE TITLE
Broken: Better Life Nature Channel (USA)

### ISSUE THREAD

**Issue by StarryWindy** [iptv-org/iptv#14181]
### Broken Link

https://uni5rtmp.tulix.tv/betternature/betternature/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://tgn.bozztv.com/betterlife/betternature/betternature/index.m3u8

### Notes (optional)

Apparently this channel has switched servers, because one other link is also down:
https://uni10rtmp.tulix.tv/betternature/betternature.stream/playlist.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
BozzTV = Tulix :)
