### ISSUE TITLE
Add: N1 (Bosnia and Herzegovina)

### ISSUE THREAD

**Issue by svgaming234** [iptv-org/iptv#14184]
### Channel ID

N1BosniaHerzegovina.ba

### Stream URL

https://best-str.umn.cdn.united.cloud/stream?stream=sp1400&sp=n1info&channel=n1bos&u=n1info&p=n1Sh4redSecre7iNf0&player=m3u8

### Label

None

### Notes (optional)

This is the Bosnian version of the N1 channel however Slovenian, Croatian and Serbian versions also exist.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by kaikyoofers** [comment]
@freearhey DMCA'd https://github.com/iptv-org/iptv/issues/6486
Please close.

**Comment by svgaming234** [comment]
Alright, will close. This should be mentioned in the contributor guide IMO
