### ISSUE TITLE
Add: N1 (Croatia)

### ISSUE THREAD

**Issue by svgaming234** [iptv-org/iptv#14182]
### Channel ID

N1Croatia.hr

### Stream URL

https://best-str.umn.cdn.united.cloud/stream?stream=sp1400&sp=n1info&channel=n1hrv&u=n1info&p=n1Sh4redSecre7iNf0&player=m3u8

### Label

None

### Notes (optional)

This is the Croatian version of the N1 channel and should be declared as such. There are also Slovenian, Serbian and Bosnian versions to my knowledge but there may be more.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by kaikyoofers** [comment]
@freearhey DMCA'd https://github.com/iptv-org/iptv/issues/6486
Please close.

**Comment by svgaming234** [comment]
Alright, will close. This should be mentioned in the contributor guide IMO
