### ISSUE TITLE
Add: Show Turk | (Turkey)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#14194]
### Channel ID

ShowTurk.tr

### Stream URL

https://showturk.blutv.com/blutv_showturk2/live.m3u8

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Benedek012** [comment]
Not working,please help
