### ISSUE TITLE
Broken: tvri sport Indonesia 

### ISSUE THREAD

**Issue by Goldiefresh** [iptv-org/iptv#14205]
### Broken Link

http://118.97.50.107/Content/HLS/Live/Channel(TVRI4)/index.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

http://wpc.d1627.nucdn.net/80D1627/o-tvri/Content/HLS/Live/Channel(TVRI4)/index.m3u8

### Notes (optional)

Official link taken from http://klik.tvri.go.id/ Old one is dead. 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
The replacement is already on the playlist: 
https://github.com/iptv-org/iptv/blob/6e9d978ead1203b51751cbfc902ea7ec8b57fc25/streams/id.m3u#L468-L469
