### ISSUE TITLE
Add: TLC Turkey

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#14204]
### Channel ID

TLCTurkey.tr

### Stream URL

https://tlc.blutv.com/blutv_tlc_live/live.m3u8

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
Sorry, but we cannot add the channel to the playlist due to claims of the copyright holder: https://github.com/iptv-org/iptv/issues/1831

**Comment by bnyusuf31-lab** [comment]
New link https://dogus.daioncdn.net/tlc/tlc.m3u8?ce=3&app=1aca0aa1-06e3-41ff-a8e5-38d7df475469
