### ISSUE TITLE
Add:  Ekotürk | (Turkey)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#14200]
### Channel ID

Ekoturk.tr

### Stream URL

https://ekoturk.blutv.com/blutv_ekoturk2/live.m3u8

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Benedek012** [comment]
Not working
