### ISSUE TITLE
Fix: 

### ISSUE THREAD

**Issue by ravipchandran82** [iptv-org/iptv#14206]
### Describe your issue

Hi,  Most of the channels are not playing in the below URL https://iptv-org.github.io/iptv/languages/tam.m3u
shows the error that "IPTV channel encountered error.  retry this channel in few min or report the IPTV about this"

**Comment by freearhey** [comment]
Just checked and I have most of the links working fine. If some specific links don't work for you, you can report them via this [form](https://github.com/iptv-org/iptv/issues/new?assignees=&labels=broken+stream&projects=&template=---broken-stream.yml&title=Broken%3A+).
