### ISSUE TITLE
Broken: M6 (France)

### ISSUE THREAD

**Issue by Skyost** [iptv-org/iptv#14219]
### Broken Link

https://raw.githubusercontent.com/Sphinxroot/HSL/main/M6.m3u8

### What happened to the stream?

Other

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by trancer1994** [comment]
The link I get when I go to the page and stream it is https://origin-18cd60dea8190528.live.6cloud.fr/out/v1/c6026ef524a94be1a8fc834731d88a7a/dash_short_cenc10_m6_hdeindex.mpd

**Comment by Skyost** [comment]
@trancer1994 I was talking about this one :

![image](https://github.com/iptv-org/iptv/assets/3882599/61d0e684-6083-4acd-87c4-ff0dd5461cde)

**Comment by iptvnikolas** [comment]
Both live streams are working.

**Comment by Skyost** [comment]
The 1080p link works for me, but definitely not the other one.
