### ISSUE TITLE
Broken: LRT Lituanica

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/iptv#14216]
### Broken Link

https://lituanica-dvr.lrt.lt/lrt-ndvr/hls/lituanica_720p/index.m3u8

### What happened to the stream?

Other

### Possible Replacement (optional)

https://lituanica.lrt.lt/lituanica/master.m3u8

### Notes (optional)

Channel link no more worked.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
The replacement is already on the playlist: 
https://github.com/iptv-org/iptv/blob/6e9d978ead1203b51751cbfc902ea7ec8b57fc25/streams/lt.m3u#L8-L9

**Comment by Zorklis** [comment]
> The replacement is already on the playlist:
> 
> https://github.com/iptv-org/iptv/blob/6e9d978ead1203b51751cbfc902ea7ec8b57fc25/streams/lt.m3u#L8-L9

Doesn't work

**Comment by DJ1999-max** [comment]
> > The replacement is already on the playlist:
> > https://github.com/iptv-org/iptv/blob/6e9d978ead1203b51751cbfc902ea7ec8b57fc25/streams/lt.m3u#L8-L9
> 
> Doesn't work

Please check your internet!
