### ISSUE TITLE
Unsorted channels

### ISSUE THREAD

**Issue by Jariix** [iptv-org/iptv#1421]
Hi everyone, there are about 200 channels in the languages list, that are not sorted to a certain language. It would be great if you check it.

**Comment by freearhey** [comment]
@Jariix you can also take part in sorting the channels by language. If you don't know exactly how to do it, here's a little guide: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#sort-channels-by-language

**Comment by Jariix** [comment]
I will try to sort all unsorted german and arabic channels.

**Comment by Jariix** [comment]
I sorted the german channels in the Language playlist. I will check for mistakes and then send it to you.
Should send the m3u file or just the code.

**Comment by Nintendocustom** [comment]
Just make a pull request
