### ISSUE TITLE
Broken: TV8

### ISSUE THREAD

**Issue by metinjakupi** [iptv-org/iptv#14229]
### Broken Link

https://iptv-org.github.io/iptv/languages/tur.m3u

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
I have https://tv8-live.daioncdn.net/tv8/tv8.m3u8 but even this link doesn't work. The issue is that the Daion host waits for the SID and other kind of parameters to be put on the .ts files and that's not what happens.
