### ISSUE TITLE
Country list Request

### ISSUE THREAD

**Issue by Jariix** [iptv-org/iptv#1422]
Hello, can you keep the single country list uncategorized? Just the channels in an alphabetical order.

**Comment by freearhey** [comment]
Yeah, it's possible to do that.

Could you give some reason why it should be done?

**Comment by Jariix** [comment]
The categories are sadly off. So you find a news channel under music and vice versa.

**Comment by freearhey** [comment]
Could you give a specific example?

**Comment by Jariix** [comment]
For example in germanys list Folx TV is a music channel in the news category. München TV is listed as an music channel but it is not.

**Comment by freearhey** [comment]
I just double-checked everything and all the categories are sort of right. And the channels you named don't have a category at all.

We're talking about the same playlist: https://iptv-org.github.io/iptv/countries/de.m3u, right?

**Comment by Jariix** [comment]
No I'm talking about the list of Germany alone .
https://iptv-org.github.io/iptv/countries/de.m3u

**Comment by freearhey** [comment]
Do you realize that it's the same playlist?

**Comment by Jariix** [comment]
Oh sorry 😂. Very weird, maybe it is my player that messes every thing up.

**Comment by Jariix** [comment]
Do you have the categories in Germany list as groups or favorites? I think the smart Iptv app can not recognize other favorites but only groups.

**Comment by freearhey** [comment]
If a channel has a category in its description, it will also be in playlists sorted by country.
