### ISSUE TITLE
Broken: EBS Yoyo

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#14227]
### Broken Link

https://raw.githubusercontent.com/etag2000/IPTV/YTlive/ebcyoyo.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Not found

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
https://ythls.onrender.com/channel/UCiWRSesvSYmY7YOyz0tv_zQ.m3u8
