### ISSUE TITLE
Add: TV Nova Pula (Croatia)

### ISSUE THREAD

**Issue by svgaming234** [iptv-org/iptv#14221]
### Channel ID

TVNova.hr

### Stream URL

https://stream.agatin.hr:3727/live/tvnovalive.m3u8

### Label

None

### Notes (optional)

Shoudn't be confused with Nova TV. They have similar names but are independent channels owned by different companies.
Nova TV is a Croatian national TV channel, but TV Nova Pula is a small local TV channel for the Istrian area.  
[TV Nova Pula website](https://tvnova.hr/)  
[Nova TV website](https://novatv.dnevnik.hr/)  

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by YesTrustMe** [comment]
The file isn't picking up any streams even with a VPN: https://stream.agatin.hr:3727/live/tvnovalive.m3u8

**Comment by svgaming234** [comment]
Stream is working for me.  
![Screenshot_20230916-110345](https://github.com/iptv-org/iptv/assets/100072489/fcd9e0de-d18c-4dc7-91ba-181055200cea). 
Perhaps it
