### ISSUE TITLE
Add: Telemundo 52

### ISSUE THREAD

**Issue by Jesus584-pixel** [iptv-org/iptv#14224]
### Channel ID

KVEA(Spanish).us

### Stream URL

https://ddy1.webdicdn.lol:443/ddy1/premium131/tracks-v1a1/mono.m3u8

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Tokened.

**Comment by jacobmils** [comment]
Not working, or I need help.
