### ISSUE TITLE
Broken: Skai TV

### ISSUE THREAD

**Issue by iptvnikolas** [iptv-org/iptv#14239]
### Broken Link

https://skai-live-back.siliconweb.com/media/cambria4/index.m3u8

### What happened to the stream?

Constantly interrupts/lagging

### Possible Replacement (optional)

http://skai-live-back.siliconweb.com/media/cambria4/index.m3u8

### Notes (optional)

This one works normally but keeps crashing. 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
I must say that simply changing "http" to "https" won't change much as it's still the same endpoint. If the source is lagging, it is because there might be an issue on 3 sides : either the host has bandwidth problems, either the source stream has issues or your internet is lagging.

**Comment by iptvnikolas** [comment]
Alpha doesn't play, Star doesn't even, not even Open, Skai plays but after a second it crashes.

**Comment by BellezaEmporium** [comment]
That's very weird. They work smoothly on my side.

**Comment by iptvnikolas** [comment]
To be fair, they don't work at all. Only Skai plays hard and gets cut after a second.
