### ISSUE TITLE
Broken: Alpha TV

### ISSUE THREAD

**Issue by iptvnikolas** [iptv-org/iptv#14236]
### Broken Link

https://alphatvlive.siliconweb.com/1/Y2Rsd1lUcUVoajcv/UVdCN25h/hls/live/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

http://alphatvlive.siliconweb.com/1/Y2Rsd1lUcUVoajcv/UVdCN25h/hls/live/playlist.m3u8

### Notes (optional)

This particular live stream has been on and off for years, but it's very tedious.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
I don't consider it "broken". It's simply due to the fact that the company hosting this stream might have the same issues as the Skai one.
