### ISSUE TITLE
Broken: TRT

### ISSUE THREAD

**Issue by iptvnikolas** [iptv-org/iptv#14231]
### Broken Link

https://www.hellasnet.tv/rest.live.hn/trt2/playlist.m3u8  

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://www.hellasnet.tv/rest2.live.hn/u2r.trt/playlist.m3u8

### Notes (optional)

The previous live stream had been shut down since late April, and has had this live stream ever since.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
The broken link has been removed and the replacement is already on the playlist:
https://github.com/iptv-org/iptv/blob/24d43bbd79c62a9497b42470c76add1fed2fc778/streams/gr.m3u#L205-L206
