### ISSUE TITLE
Broken: Star Channel

### ISSUE THREAD

**Issue by iptvnikolas** [iptv-org/iptv#14237]
### Broken Link

https://livestar.siliconweb.com/media/star1/star1mediumhd.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

http://livestar.siliconweb.com/media/star1/star1.m3u8

### Notes (optional)

The previous one you have has been running since February.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Let's keep it "encrypted" : https://livestar.siliconweb.com/media/star1/star1.m3u8

**Comment by iptvnikolas** [comment]
Don't keep it encrypted.

**Comment by BellezaEmporium** [comment]
> Don't keep it encrypted.

Where's the issue in using "https" instead of using "http" ?

**Comment by iptvnikolas** [comment]
They don't work at all

**Comment by BellezaEmporium** [comment]
> They don't work at all

May I know which player you're using in order to watch your streams ? It works perfectly fine from my side.

![image](https://github.com/iptv-org/iptv/assets/30985701/4ace36ac-1994-4cb5-a7e3-622cdbf10509)

**Comment by iptvnikolas** [comment]
It's bothering me "Error 404".

**Comment by BellezaEmporium** [comment]
> It's bothering me "Error 404".

This is an odd situation. If I understand well, you only can access http links, but not https links ?

**Comment by iptvnikolas** [comment]
YES

**Comment by BellezaEmporium** [comment]
OK, sounds legitimate to me, but it's rather disturbing as it's the first time I see this kind of issue pop up.

If you do not mind testing a few fixups : https://www.thewindowsclub.com/https-sites-are-not-opening-browser and test one or few https links afterwards.

**Comment by iptvnikolas** [comment]
Unfortunately, the same thing happens again.

**Comment by BellezaEmporium** [comment]
> Unfortunately, the same thing happens again.

Well, i'll accept the http links as-is then.

**Comment by iptvnikolas** [comment]
Okay.
