### ISSUE TITLE
Broken: Open TV

### ISSUE THREAD

**Issue by iptvnikolas** [iptv-org/iptv#14238]
### Broken Link

https://liveopencloud.siliconweb.com/1/ZlRza2R6L2tFRnFJ/eWVLSlQx/hls/live/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

http://liveopencloud.siliconweb.com/1/ZlRza2R6L2tFRnFJ/eWVLSlQx/hls/live/playlist.m3u8

### Notes (optional)

This particular one is to operate from August 2022. 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
I don't see where's the issue here, i'm sorry.

**Comment by iptvnikolas** [comment]
The live stream of the open channel has to work from the summer of 2022 and since then it has been working with that link.
