### ISSUE TITLE
Add Disney Junior USA Eastern and Pacific

### ISSUE THREAD

**Issue by CarlGamerPro** [iptv-org/iptv#14230]
Eastern:
http://aanax.com:8080/argoni150Con/Hbtsfwqiybmcz/8608

Pacific:
http://us1-external-sources.iptvserver.tv/kkkrkDp2a9KNwAwGzpb/QT94uK5NNQw4r4Qs/513

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-add-a-new-stream-link-to-a-playlists
