### ISSUE TITLE
Broken: Alfa Dramas

### ISSUE THREAD

**Issue by iptvnikolas** [iptv-org/iptv#14232]
### Broken Link

https://www.hellasnet.tv/rest.live.hn/ws.alf/playlist.m3u8  

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://www.hellasnet.tv/rest2.live.hn/w2r.alf/playlist.m3u8

### Notes (optional)

This live stream has been down since early May and has had this live stream ever since.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
The broken link has been removed and the replacement is already on the playlist: 
https://github.com/iptv-org/iptv/blob/24d43bbd79c62a9497b42470c76add1fed2fc778/streams/gr.m3u#L18-L19
