### ISSUE TITLE
Broken: Irida TV

### ISSUE THREAD

**Issue by iptvnikolas** [iptv-org/iptv#14233]
### Broken Link

https://www.hellasnet.tv/rest.live.hn/ws.iri/playlist.m3u8  

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://www.hellasnet.tv/rest2.live.hn/w2r.iri/playlist.m3u8

### Notes (optional)

Since Easter of this year, this particular live stream has stopped and since then he has been playing with this live stream.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
The broken link has already been removed from the playlist.

Closed in favor of https://github.com/iptv-org/iptv/issues/14249
