### ISSUE TITLE
Arabic Channels 

### ISSUE THREAD

**Issue by iptvchecker** [iptv-org/iptv#1423]
Mostly Arabic channels are not working.

- Rotana channels are not found or not working.
- Nile Drama, etc not found or not working
- Al-Resalah and other Islamic channels are not working

**Comment by freearhey** [comment]
- [x] Rotana
https://github.com/iptv-org/iptv/blob/928492ca9395828993ba71313f8d09b1a357de8c/channels/sa.m3u#L48-L59
- [x] Nile Drama
https://github.com/iptv-org/iptv/blob/928492ca9395828993ba71313f8d09b1a357de8c/channels/eg.m3u#L36-L37
- [x] Al-Resalah
https://github.com/iptv-org/iptv/blob/928492ca9395828993ba71313f8d09b1a357de8c/channels/sa.m3u#L14-L15

**Comment by iptvchecker** [comment]
I copied all the links in the provided URLs. I have included them in my local test file. They are all broken. No channel works!
This attached file has all the Arabic channels that I tested. They were/used to work for several months until they stopped working few weeks back. I am including this file in case you'd want to utilize.
Thanks

    On Tuesday, May 26, 2020, 11:28:52 AM UTC, Aleksandr Statciuk <notifications@github.com> wrote:  
 
 

   
   -  Rotana   
https://github.com/iptv-org/iptv/blob/928492ca9395828993ba71313f8d09b1a357de8c/channels/sa.m3u#L48-L59
   -  Nile Drama   
https://github.com/iptv-org/iptv/blob/928492ca9395828993ba71313f8d09b1a357de8c/channels/eg.m3u#L36-L37
   -  Al-Resalah   
https://github.com/iptv-org/iptv/blob/928492ca9395828993ba71313f8d09b1a357de8c/channels/sa.m3u#L14-L15

**Comment by freearhey** [comment]
I have all these links working fine, here are some examples:
<img width="775" alt="Captura de pantalla 2020-05-27 a las 0 41 15" src="https://user-images.githubusercontent.com/7253922/82953150-ef89c500-9fb2-11ea-9248-14757d6ba1f6.png">
<img width="774" alt="Captura de pantalla 2020-05-27 a las 0 42 47" src="https://user-images.githubusercontent.com/7253922/82953223-0f20ed80-9fb3-11ea-92b0-6c83d25d1878.png">

So I don't know how else I can help you.

**Comment by iptvchecker** [comment]
I guess there is very little you can do if they work for you! 

First, I very much appreciate the great work you're doing, seriously. I have shared your links with several of my friends and family that were paying tons of money to get the same links from other paid sources. :) Thank you again.

What client are you using? It's strange that everything was working until recently! Not sure if these ips are blocked coming into my ISP or even my country!

I will check using different proxies and other clients like VLC and let you know.

Keep up the great work :)

     On Tuesday, May 26, 2020, 10:43:58 PM GMT+1, Aleksandr Statciuk <notifications@github.com> wrote:  
 
 


I have all these links working fine, here are some examples:



So I don't know how else I can help you.

**Comment by freearhey** [comment]
I checked all this channels only in Elmedia Video Player.
