### ISSUE TITLE
Broken: Aigaio TV

### ISSUE THREAD

**Issue by iptvnikolas** [iptv-org/iptv#14242]
### Broken Link

https://tna5.bozztv.com/aigaiotv1/index.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://250weu.bozztv.com/ssh101/ssh101/aigaiotv/playlist.m3u8

### Notes (optional)

It's the hundredth time in a month that the live stream link has changed.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by iptvnikolas** [comment]
Take a picture from there.
``

**Comment by iptvnikolas** [comment]
![IMG_20230917_174635](https://github.com/iptv-org/iptv/assets/144067588/116d7790-79ac-4c4f-a359-30927e2add76)

**Comment by freearhey** [comment]
The replacement is already on the playlist:
https://github.com/iptv-org/iptv/blob/51256252445021c32ff995b9435c5b332bcfa3a9/streams/gr.m3u#L14-L15
