### ISSUE TITLE
Add: PLP

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#14248]
### Channel ID

PLP.gr

### Stream URL

https://www.hellasnet.tv/rest2.live.hn/w2r.plp/playlist.m3u8

### Quality

None

### Label

None

### Notes (optional)

Original request: #14235

<img width="789" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/76ec4823-f764-4fbe-8695-232173b7342c">

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by iptvnikolas** [comment]
226p
