### ISSUE TITLE
Add: The Weather Channel HD

### ISSUE THREAD

**Issue by JerkyHockey** [iptv-org/iptv#14250]
### Channel ID

TheWeatherChannel.us

### Channel Name

The Weather Channel

### Stream URL

https://twcprod-live.twc-tv.com/v1/manifest/b4d4d63a49309cc5140171fb2e92485c31be1e9e/DSP_6228e4760505741a116f1ba2_twcprod-live/6bf09ce5-366b-463c-b67e-c4b799f73c3f/4.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
Sorry, but we cannot add the channel to the playlist due to claims of the copyright holder: https://github.com/iptv-org/iptv/issues/9729
