### ISSUE TITLE
Broken: Better Health TV

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#14260]
### Broken Link

https://uni10rtmp.tulix.tv/betterhealth/betterhealth.stream/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Original request: #14186

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
replacement : https://tgn.bozztv.com/betterlife/betterhealth/betterhealth/index.m3u8

**Comment by freearhey** [comment]
The replacement is already on the playlist: 
https://github.com/iptv-org/iptv/blob/72d8fba38a5588115eef86fa09031a8781be847f/streams/us.m3u#L182-L183
