### ISSUE TITLE
Broken: 

### ISSUE THREAD

**Issue by AmeerHamza65445** [iptv-org/iptv#14264]
### Broken Link

https://iptv-org.github.io/iptv/countries/in.m3u

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://iptv-org.github.io/iptv/countries/in.m3u

### Notes (optional)

Colors,Dhamal channels playback not available

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Instead of pointing the entire playlist as an issue, please isolate only the concerned broken stream.
