### ISSUE TITLE
Add: IDX Channel

### ISSUE THREAD

**Issue by antosatriani** [iptv-org/iptv#14270]
### Channel ID

IDXChannel.id

### Channel Name

IDX Channel

### Stream URL

http://vod.linknetott.swiftcontent.com/Content/HLS/Live/Channel(ch389)/index.m3u8

### Quality

720p

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
http://vod.linknetott.swiftcontent.com/Content/HLS/Live/Channel(ch389)/index.m3u8 (offline)
<img width="603" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/6fc347c1-1804-46ff-8cd2-b9574ec29367">
