### ISSUE TITLE
Add: Citra Drama

### ISSUE THREAD

**Issue by antosatriani** [iptv-org/iptv#14274]
### Channel ID

CitraDrama.id

### Channel Name

Citra Drama

### Stream URL

http://vod.linknetott.swiftcontent.com/Content/HLS/Live/Channel(ch378)/index.m3u8

### Quality

720p

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
<img width="607" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/1a10367a-73e7-4083-8d67-ded288ace13b">

**Comment by kaikyoofers** [comment]
@freearhey i do think that the stream url is geoblocked to indonesia along with these https://github.com/iptv-org/iptv/issues/14270 https://github.com/iptv-org/iptv/issues/14272
