### ISSUE TITLE
Add: Horee

### ISSUE THREAD

**Issue by antosatriani** [iptv-org/iptv#14272]
### Channel ID

Horee.id

### Channel Name

Horee!

### Stream URL

http://vod.linknetott.swiftcontent.com/Content/HLS/Live/Channel(ch375)/index.m3u8

### Quality

720p

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
<img width="605" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/d57a5249-c6c1-413d-82b8-52426f18ef22">
