### ISSUE TITLE
Broken: Cyprus RIK HD in 1080p

### ISSUE THREAD

**Issue by ROBGagn** [iptv-org/iptv#14278]
### Broken Link

http://l6.cloudskep.com/tvb6/rikhd1/mpeg.2ts

### What happened to the stream?

Other

### Possible Replacement (optional)

https://am3.cloudskep.com/rikcy/rikhd/l6/rikhd_fhd/chunks.m3u8?nimblesessionid=31368225&wmsAuthSign=c2VydmVyX3RpbWU9OS8xOC8yMDIzIDExOjQzOjE1IFBNJmhhc2hfdmFsdWU9K25YRDJtbm1ZOWZvN3IwWFl5bzlHZz09JnZhbGlkbWludXRlcz0zMA==

### Notes (optional)

Please give us a working RIK HD in 1080p as it is on the channel website (http://cybc.com.cy). The actual link is in 720p. It will probably need a token to be working unless you can find another link.
Thank you.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
http://l6.cloudskep.com/tvb6/rikhd1/mpeg.2ts
<img width="791" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/b54f862f-f2a3-4c3c-88ac-fdb26c8a5ea8">
