### ISSUE TITLE
Add: UTRK Balastan

### ISSUE THREAD

**Issue by ztreamhd** [iptv-org/iptv#14284]
### Channel ID

Balastan.kg

### Channel Name

УТРК Баластан

### Stream URL

https://64e5ed58c00d4.streamlock.net/live/smil:balastan.smil/playlist.m3u8

### Quality

272p

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/4bebf925def85115f7a03b17975d8705a924a7c1/streams/kg.m3u#L4-L5
