### ISSUE TITLE
Broken: All ATV channels from Peru dont work anymore

### ISSUE THREAD

**Issue by Undisclosed-Information** [iptv-org/iptv#14295]
### Broken Link

https://iptv-org.github.io/iptv/countries/pe.m3u

### What happened to the stream?

Not loading

### Notes (optional)

Broken channels:

- ATV
- https://d3krdjs7is1y42.cloudfront.net/ATVpe/df13ed57843877b21ad969184ab6888f.sdp/playlist.m3u8

- ATV Sur
- https://d3krdjs7is1y42.cloudfront.net/ATVSur/f05b236d4a4d43b3987d6f5ed5686d6e.sdp/playlist.m3u8

- ATV+ Noticias
- https://d3krdjs7is1y42.cloudfront.net/ATVmas/74ee4169b59e6f987ae3d77317309109.sdp/playlist.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Carlinhos027** [comment]
Maybe Geoblocked?

**Comment by JustSammyV** [comment]
From Chile, geoblocked.
![image](https://github.com/iptv-org/iptv/assets/137475335/995a5811-c29e-4989-b1b7-46d92ac466b2)

**Comment by Undisclosed-Information** [comment]
ATV+ is available to me from this playlist:

https://linear-258.frequency.stream/dist/vix/258/hls/master/playlist.m3u8

**Comment by BellezaEmporium** [comment]
Can confirm it's GEO also on my side.

**Comment by freearhey** [comment]
All three links are working fine at the moment.

https://d3krdjs7is1y42.cloudfront.net/ATVpe/df13ed57843877b21ad969184ab6888f.sdp/playlist.m3u8
<img width="792" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/5366b83f-9216-4d93-b726-bc913abe0992">

https://d3krdjs7is1y42.cloudfront.net/ATVSur/f05b236d4a4d43b3987d6f5ed5686d6e.sdp/playlist.m3u8
<img width="791" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/d16e2004-6c0d-43de-8773-0b4ea2f95ece">

https://d3krdjs7is1y42.cloudfront.net/ATVmas/74ee4169b59e6f987ae3d77317309109.sdp/playlist.m3u8
<img width="790" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/3e525934-b122-4a64-8f98-5b1189a50964">

**Comment by BellezaEmporium** [comment]
> All three links are working fine at the moment.
> 
> https://d3krdjs7is1y42.cloudfront.net/ATVpe/df13ed57843877b21ad969184ab6888f.sdp/playlist.m3u8
> <img width="792" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/5366b83f-9216-4d93-b726-bc913abe0992">
> 
> https://d3krdjs7is1y42.cloudfront.net/ATVSur/f05b236d4a4d43b3987d6f5ed5686d6e.sdp/playlist.m3u8
> <img width="791" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/d16e2004-6c0d-43de-8773-0b4ea2f95ece">
> 
> https://d3krdjs7is1y42.cloudfront.net/ATVmas/74ee4169b59e6f987ae3d77317309109.sdp/playlist.m3u8
> <img width="790" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/3e525934-b122-4a64-8f98-5b1189a50964">

It does work, but they have certain moments in time in which they geo-restrict their streams it seems. Or it was a simple test at that time.
