### ISSUE TITLE
Broken: Hatun TV (PE)

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#14299]
### Broken Link

https://mi.godo.net.pe/Best00Hatum-0032101002/index.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://mi.godo.net.pe/Best00Hatum-0032101002/tracks-v1a1/mono.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://mi.godo.net.pe/Best00Hatum-0032101002/index.m3u8 (working)
<img width="1429" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/44e23bde-8020-4949-b5f8-84493361b3f6">
