### ISSUE TITLE
Broken: MBC Ulsan (울산 MBC) (540p)

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#14305]
### Broken Link

https://5ddfd163bd00d.streamlock.net/nHDTV/nHDTV/playlist.m3u8

### What happened to the stream?

Constantly interrupts/lagging

### Notes (optional)

Hey mods, I found the link that is barely working since the livestream link was lasted from one or two minutes to five-to-six minutes per video. Will someone will replace the livestream link with a different one please.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
https://5ddfd163bd00d.streamlock.net:443/nHDTV/nHDTV/playlist.m3u8

that's the link I have from the official MBC source. Sadly, if their source isn't stable, we can't do much.

**Comment by trancer1994** [comment]
@BellezaEmporium Can you re-invite me to the Discord, please? I think I must've left by accident or something because it's no longer in my list of servers.
