### ISSUE TITLE
Broken: PBO Digital (720p) [Not 24/7]

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#14303]
### Broken Link

https://ythls.onrender.com/channel/UCgR0st4ZLABi-LQcWNu3wnQ.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://customer-gllhkkbamkskdl1p.cloudflarestream.com/eyJhbGciOiJSUzI1NiIsImtpZCI6ImI3YmIwODNmMDhkNmQ5NWExZjIzZWE3ZWRhOWY4NTZhIn0.eyJzdWIiOiJhYTQyNzBjODhkOTY2Mzg4ZDI3YmEyOWI2Mzc0YWQ3NiIsImtpZCI6ImI3YmIwODNmMDhkNmQ5NWExZjIzZWE3ZWRhOWY4NTZhIiwiZXhwIjoxNjk1NDUwNDgyLCJhY2Nlc3NSdWxlcyI6W3sidHlwZSI6ImlwLmdlb2lwLmNvdW50cnkiLCJhY3Rpb24iOiJibG9jayIsImNvdW50cnkiOlsiUlUiLCJCWSJdfV19.ebJa_5QJysie0kYiWzRVRGe639MiN93qEPzsnP4EzLtnMmYLIjfkcjA4u5GW_nN7xJ7UBUp_jGmjjbkxDlGm6JRO4Nnutu7aIDNEjrsVaj-zhL335LZNRoXhK56bOaLiyxaUXA2zfyw0B7fpZecbLwbMZCGhF-VxcAl_s4i3qw5K-z9IWAcoY9PsEuQNq6uhvF3PqPshegGpMUqueQBGvsdsmIiKPUnrT_sK6ZbAjL7yQrGc6Ul5XtEcMVd0yhox7CPM2HG8-xCIr6OFlc9_3EEX5sJ6prmIUYZgkm1_gWftX4gUrnTJIuZg9usSzI2RMHwxoOu0fyOvtTC_QSC0Yg/manifest/stream_t1_r480001.m3u8?CMCD=cid%3D%221695407367439%22%2Cmtp%3D8100%2Cot%3Dm%2Csf%3Dh%2Csid%3D%22bc0f0f8a-c34c-4f65-83f9-6c79e9c623d4%22

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://ythls.onrender.com/channel/UCgR0st4ZLABi-LQcWNu3wnQ.m3u8 (working)
<img width="792" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/0b986902-a674-49a8-bedb-7a50d6b71b35">
