### ISSUE TITLE
Broken: Best Cable Mas Cumbia (720p)

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#14300]
### Broken Link

https://mi.godo.net.pe/best-MasCum-0102210011/index.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://mi.godo.net.pe/best-MasCum-0102210011/tracks-v1a1/mono.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://mi.godo.net.pe/best-MasCum-0102210011/index.m3u8 (working)
<img width="1426" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/27a42d68-9741-4a49-ac1c-b4d0c1f4afcd">
