### ISSUE TITLE
Broken: Best Cable Sports Perú (720p)

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#14301]
### Broken Link

https://mi.godo.net.pe/Best-sport-00000x111/index.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://mi.godo.net.pe/Best-sport-00000x111/tracks-v1a1/mono.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://mi.godo.net.pe/Best-sport-00000x111/index.m3u8 (working)
<img width="1433" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/4273eaba-dd46-4f0a-97da-6af0bc5988a0">
