### ISSUE TITLE
Add: SBS TV

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#14304]
### Channel ID

HLSQDTV.kr

### Channel Name

SBS TV

### Stream URL

https://aqstream.com/sbs/SBS-Stream-4

### Quality

None

### Label

None

### Notes (optional)

Hey mods!? Did you find any livestream links for SBS TV which is owned by Seoul Broadcasting System (SBS)? While many SBS TV's regional feeds are very easy to find but the said couldn't be the same for SBS TV making the livestreaming links harder-to-find nowadays.

Here's the dead links for SBS TV and other few regional feeds that was mislabel as SBS which is taken from 韩国.txt.

https://github.com/wcb1969/iptv/blob/main/%E9%9F%A9%E5%9B%BD.txt

SBS, http://221.157.125.239:1935/live/psike/playlist.m3u8
SBS, http://183.99.22.189:9981/stream/channelid/1124346476
SBS, http://220.95.92.160:9981/stream/channelid/1445999617
SBS, https://apichvod19.seezntv.com/OTM/10550_M.m3u8?AdaptiveType=HLS&SessionID=3438d7e9-3e70-43b1-9fe6-b8290cd25403
SBS, http://itskoi.dothome.co.kr/sbs.php?id=S01
SBS, http://ye23.win/iptv/sbs5.1.php?id=S01
SBS, http://han.ddkdxmkj.com/api/sbs.php?id=1

Here's the link that is working now. But if unknown that the link is working on VLC media player?
https://aqstream.com/sbs/SBS-Stream-4

Here's the logo.
![Seoul_Broadcasting_System_logo svg](https://github.com/iptv-org/iptv/assets/143818591/17e2dc15-4624-46bb-ae1a-4c1ed8f21cae)

BTW, did you find any alternative livestream links for SBS TV yet.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by AVGCFan1995** [comment]
Hey Freearhey, did you find the livestream links for SBS TV yet!

**Comment by freearhey** [comment]
No.
