### ISSUE TITLE
Broken: Best Cable Music (720p)

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#14302]
### Broken Link

https://mi.godo.net.pe/best-Music-00112000050/index.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://mi.godo.net.pe/best-Music-00112000050/tracks-v1a1/mono.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://mi.godo.net.pe/best-Music-00112000050/index.m3u8 (working)
<img width="1429" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/901ddad9-d21f-4e5e-bc74-f5b04913578d">
