### ISSUE TITLE
Add: Saudi Thaqafiya TV

### ISSUE THREAD

**Issue by CasperMcFadden95** [iptv-org/iptv#14316]
### Channel ID

SaudiThaqafiyaTV.sa

### Channel Name

Saudi Thaqafiya TV

### Stream URL

https://thaqafeyyah-ak.akamaized.net/out/v1/f6851f68ada94f82ae6b64a441eb5ab1/index.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by kaikyoofers** [comment]
May need to wait until the database issue gets approved and closes.
