### ISSUE TITLE
Arabic Channel 

### ISSUE THREAD

**Issue by sinoel** [iptv-org/iptv#1431]
**What's wrong?**
Lebanon  Channel are Not working like al jadeed MTV LDC LBC....
**Country of the channel:**
Lebanon 
**Channel Name:**
Al jadeed MTV LDC LBC...
**Broken Link:**

**Additional Information (optional):**

**Comment by asa-sal** [comment]
@freearhey thx you for your effort but we still missing 3 main channels
MTV
AL JADEED
NBN

Thank you in advance

**Comment by freearhey** [comment]
@asa-sal I'm aware of that and that's why this issue isn't closed yet.

**Comment by freearhey** [comment]
- [ ] Al Jadeed 
- [x] MTV
https://github.com/iptv-org/iptv/blob/171ee2b1fe2ac528892ec278113235abdd246395/channels/lb.m3u#L24-L25
- [ ] LDC
- [x] LBC
https://github.com/iptv-org/iptv/blob/171ee2b1fe2ac528892ec278113235abdd246395/channels/lb.m3u#L18-L21
- [ ] NBN

**Comment by jadkik** [comment]
The links here seem to  work still: [Pastebin 1](https://pastebin.com/M9NrWjix) and [Pastebin 2](https://pastebin.com/0aGGXXpy) under `LBC HD` (LBC and LDC have been mixed up here and elsewhere before) and `Aljaded` (also `Mtv lebanon`). 

Couldn't find NBN there.

I think they were extracted from the El Ahmad website.

**Comment by Ziad-84** [comment]
I have tested the following channels' links on this page and on the Pastebin files (1 and 2) provided by jadkik and they are still not working:
Sama, Lana, Lana plus, Syria Drama, LBC, LDC, MTV, Aljadeed

**Comment by jadkik** [comment]
How likely is it that someone is watching this repo and taking down links that show up here? Has it happened before?

The links I posted were working fine just a few days ago and they had been working for weeks prior to that.

**Comment by Ziad-84** [comment]
Is it possible to make an m3u8 link from YouTube link?I tried but it didn't work

**Comment by Ziad-84** [comment]
> How likely is it that someone is watching this repo and taking down links that show up here? Has it happened before?
> 
> The links I posted were working fine just a few days ago and they had been working for weeks prior to that.

Is it possible to make an m3u8 link from YouTube link?I tried but it didn't work

**Comment by jadkik** [comment]
> Is it possible to make an m3u8 link from YouTube link?I tried but it didn't work

Unrelated to this issue.

But anyway, you could try to use [youtube-dl](https://github.com/ytdl-org/youtube-dl) or [NewPipe](https://github.com/TeamNewPipe/NewPipeExtractor) to get m3u8 links (or similar) and use some iptv tools/scripts to generate a proper m3u playlist for them. But there is no way you will be able to generate a "fixed" link that would be suitable for this repo or that you could write to a file and re-use.

**Comment by freearhey** [comment]
@jadkik If the broadcast isn't official, it's definitely possible that someone is tracking the links that way. 

So if you think it might break any rules, it's best not to publish such links here.

**Comment by asa-sal** [comment]
@freearhey  Any update about the test streaming for the LB channels ?
Thx for your efforts

**Comment by freearhey** [comment]
@asa-sal Sorry, but I didn't understand the question.

**Comment by asa-sal** [comment]
@freearhey most of the LB channels disconnect after a short time sometime( 40 seconds till max 2 minutes ) anything we should be doing about that ?
I am not sure if this website will help you http://www.elahmad.com/tv/Webtv/Arabian.htm#Lebanon

Thank you

**Comment by freearhey** [comment]
@asa-sal It would be great if you could create a separate issue and specify which channels you are talking about.

**Comment by Ziad-84** [comment]
Almost all Lebanese and Syrian channels are not working

**Comment by asa-sal** [comment]
All the main channels has been removed or not working

**Comment by hachemal** [comment]
Links for NewTV seems to be workign fine today on elahmad website.
can anyone help tell me how to extract the m3u or the source from the page?

**Comment by jadkik** [comment]
@hachemal You can use browsermobproxy, configure Firefox/Chrome to use it, dump the requests as HAR, open the HAR file in chrome/firefox dev tools, and look for "m3u8" or "smil" in the URL or filter by media in the network tab.

(elahmad tries to prevent you from opening dev tools while you're on the page, and you might find some local proxies that can be easier to use than browsermobproxy)

**Comment by themak1985** [comment]
Still no NBN, but added LB channels via #1600

**Comment by freearhey** [comment]
Added
