### ISSUE TITLE
Broken: Game Show Network East (720p) [Loading and glitching on HLS Player from my school laptop]

### ISSUE THREAD

**Issue by tvongsaly4592** [iptv-org/iptv#14324]
### Broken Link

https://cdn.klowdtv.net/803B48A/n1.klowdtv.net/live2/gsn_720p/playlist.m3u8

### What happened to the stream?

Constantly interrupts/lagging

### Notes (optional)

Constantly loads and glitches.

I don't know of a replacement, but wanted to put it on the radar.

Thanks!

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by benevenstanciano** [comment]
It is stable for me, currently.

**Comment by freearhey** [comment]
It works fine for me, too.
