### ISSUE TITLE
Add: Vivid Red [NSFW]

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#14344]
### Channel ID (required)

VividRed.us

### Stream URL (required)

http://85.11.144.9:4222/VividTVEurope?token=test

### Quality

576p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
I'm used to seeing watermarks from Vivid and its subsidiaries. This iteration doesn't seem to have any. I do not know if it's intentional or it's not the correct channel ID.

**Comment by BellezaEmporium** [comment]
Funnily enough, had to check again to see it was correct.
