### ISSUE TITLE
Broken: DD National

### ISSUE THREAD

**Issue by deepanshu-dev** [iptv-org/iptv#14349]
### Broken Link

http://103.199.161.254/Content/ddnational/Live/Channel(DDNational)/index.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
I have it loading but with a lot of artifacts:

<img width="632" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/f6f46449-d5b4-44bb-a547-f05da4d4eb93">
