### ISSUE TITLE
Add: 24

### ISSUE THREAD

**Issue by blanc6** [iptv-org/iptv#14357]
### Channel ID (required)

24.sk

### Channel Name

:24

### Stream URL (required)

https://n16.stv.livebox.sk/stv-tv/35c19095b6c1a308ecb9466b1355ca69/stv3.smil/chunklist_b5251072.m3u8

### Quality

None

### Label

None

### Notes

slovak 24/7 news channel
https://www.rtvs.sk/televizia/live-24

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://n16.stv.livebox.sk/stv-tv/35c19095b6c1a308ecb9466b1355ca69/stv3.smil/chunklist_b5251072.m3u8
![image translated (1)](https://github.com/iptv-org/iptv/assets/7253922/db7be0ad-d886-4441-aa11-bb2146be3e3e)
