### ISSUE TITLE
Add: TA3

### ISSUE THREAD

**Issue by blanc6** [iptv-org/iptv#14356]
### Channel ID (required)

TA3.sk

### Channel Name

TA3

### Stream URL (required)

https://n14.stv.livebox.sk/ta3/f26faa3bc0822f9533812b900da76800/1.smil/chunklist_b2691072.m3u8

### Quality

None

### Label

None

### Notes

slovak 24/7 news channel
www.ta3.com

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://n14.stv.livebox.sk/ta3/f26faa3bc0822f9533812b900da76800/1.smil/chunklist_b2691072.m3u8
![image translated](https://github.com/iptv-org/iptv/assets/7253922/f901dadb-b3cc-43ab-84b7-aa27eaff152b)
