### ISSUE TITLE
Add: 

### ISSUE THREAD

**Issue by ramazansancar** [iptv-org/iptv#14364]
### Channel ID (required)

4UTV.tr

### Channel Name

4U TV

### Stream URL (required)

https://hls.4utv.live/hls/stream.m3u8

### Quality

720p

### Label

None

### Notes

This channel does not broadcast for Turkey. Can you arrange it for Iran?

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/c51e869d9f3e4d32ac1185d53a3451cb966ceb08/streams/ir.m3u#L2-L3

**Comment by ramazansancar** [comment]
> https://github.com/iptv-org/iptv/blob/c51e869d9f3e4d32ac1185d53a3451cb966ceb08/streams/ir.m3u#L2-L3

It needs to be removed for Turkey. @freearhey
