### ISSUE TITLE
Add: Diktyo TV [GR]

### ISSUE THREAD

**Issue by BellezaEmporium** [iptv-org/iptv#14379]
### Channel ID (required)

DiktyoTV.gr

### Channel Name

Diktyo TV (Δίκτυο Τηλεόραση)

### Stream URL (required)

https://5d00db0e0fcd5.streamlock.net/7322/7322/playlist.m3u8

### Quality

576p

### Label

None

### Notes

Greek local channel from Serrès, Greece.
Needs [database entry](https://github.com/iptv-org/database/issues/5609) to be approved.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/a7890b73917f1e4bd60e22ea57710f6d0237330a/streams/gr.m3u#L59-L60
