### ISSUE TITLE
Broken: AjmanTV.ae

### ISSUE THREAD

**Issue by CasperMcFadden95** [iptv-org/iptv#14380]
### Broken Link

https://dacastmmd.mmdlive.lldns.net/dacastmmd/d3e9fc3b874a46159ce3724d802e3f8d/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://dacastmmd.mmdlive.lldns.net/dacastmmd/8eb0e912b49142d7a01d779c9374aba9/index.m3u8

### Notes (optional)

https://www.ajmantv.com stream is tokenized and should be removed

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Replacement link : https://dacastmmd.mmdlive.lldns.net/dacastmmd/8eb0e912b49142d7a01d779c9374aba9/index.m3u8

**Comment by CasperMcFadden95** [comment]
Thanks @BellezaEmporium 
Requested addition with https://github.com/iptv-org/iptv/issues/14384
