### ISSUE TITLE
Add:  10 Peach Australia 

### ISSUE THREAD

**Issue by Goldiefresh** [iptv-org/iptv#14389]
### Channel ID (required)

10Peach.au

### Channel Name

10 Peach

### Stream URL (required)

https://i.mjh.nz/10peach-nsw.m3u8

### Quality

720p

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Stream link : 410 Gone

**Comment by Goldiefresh** [comment]
Apologies the wrong links were uploaded for all the 10 network channels. Iv edited them to the correct ones from 10play.
