### ISSUE TITLE
Add: sky open +1 New Zealand 

### ISSUE THREAD

**Issue by Goldiefresh** [iptv-org/iptv#14391]
### Channel ID (required)

SkyOpenPlus1.nz

### Channel Name

Sky open +1

### Stream URL (required)

https://linear-p.media.skyone.co.nz/primeplus1.clear.m3u8

### Quality

576p

### Label

Geo-blocked

### Notes

Sky open the new name for free to air channel prime New Zealand. 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
On 17 August 2023, it was announced that Prime would change its name to Sky Open on 23 August 2023.

We'll need to reflect those changes on our database.
