### ISSUE TITLE
Broken: NHK Educational TV (540p) [Not 24/7]

### ISSUE THREAD

**Issue by sxflynn** [iptv-org/iptv#14394]
` #EXTINF:-1 tvg-id="NHKEducationalTV.jp" tvg-logo="https://i.imgur.com/WxtftlO.png" group-title="Education",NHK Educational TV (540p) [Not 24/7]
http://202.60.106.14:8080/1302/playlist.m3u8`

This channel is broken. It is listed in the playlist and does not play when you try.

These other related channels are also broken:

* NHK BS1
* NHK BSP
* NHK G

**Comment by Alstruit** [comment]
All links seem to work now especially NHK E.
https://streamtest.in/logs/http-202-60-106-14-8080-1302-playlist-m3u8-1391ebf1-8776-46f8-bc03-7d3c75fc789a
https://streamtest.in/logs/https-nhk4-mov3-co-hls-nhk-m3u8-6fe8ebc6-4b81-4739-9433-8a271d68d76e
https://streamtest.in/logs/http-203-162-235-41-12091-68597b48-4759-45e5-ae68-dfe1cb9b4a15
https://streamtest.in/logs/http-203-162-235-41-25104-a25b9e0d-0799-4422-b01f-7ba1d73c8686
https://streamtest.in/logs/http-203-162-235-41-14093-a9e87a91-c060-42f5-8656-ea897626fcab
https://streamtest.in/logs/http-203-162-235-41-20099
