### ISSUE TITLE
Add: First Channel News

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#14401]
### Channel ID (required)

FirstChannelNews.am

### Stream URL (required)

https://amtv1-2.livestreamingcdn.com/am3abr/index.m3u8

### Quality

1080p

### Label

None

### Notes

Source: https://www.1lurer.am/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
i get this also https://amtvusdvr.tulix.tv/am3abr/index.m3u8
