### ISSUE TITLE
Add: Ioannina TV

### ISSUE THREAD

**Issue by iptvnikolas** [iptv-org/iptv#14402]
### Channel ID (required)

IoanninaTV.gr

### Channel Name

Ioannina TV

### Stream URL (required)

https://raw.githubusercontent.com/iptvnikolas/Nikki-TVM3U8/main/ioanninatv.m3u8

### Quality

1080p

### Label

Not 24/7

### HTTP User Agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 Edge/12.246 HTTP Referrer

### HTTP Referrer

https://nick.gr/itv/

### Notes

The live stream is my fair share and I highly recommend you watch it.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
the ovh link work  on kodi without the user agent or referer  ,but only 480p

**Comment by iptvnikolas** [comment]
I probably put it in lie 1080p...
