### ISSUE TITLE
Hello please can anyone here tell me how i can write the right link for m3u8 with user agent in Android admin panel 

### ISSUE THREAD

**Issue by dali20161** [iptv-org/iptv#1440]
here tell me how i can write the right link for m3u8 with user agent in Android admin panel...i habe weite like this but dont work please i need help
![20200518_041618](https://user-images.githubusercontent.com/63991660/82969254-8795a780-9fcf-11ea-8045-98f7fe392436.jpg)

**Comment by Sphinxroot** [comment]
as exemple :  try ->  .m3u8|User-Agent=VLC

you might try this one     |User-Agent=stream

in some case  link need |Referer=(URLHERE)  and |X-Forwarded-For=(IP ADRESSHERE)

but the link you posted look like a account  /LIVE/Name/Pass/ .. might be already offline  ... not tested

**Comment by themak1985** [comment]
Closing this issue, feel free to reopen if you still need help.
