### ISSUE TITLE
Macedonia has changed its logo.

### ISSUE THREAD

**Issue by iptvnikolas** [iptv-org/iptv#14418]
### Describe your issue

And this is it: https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Makedonia_TV_2023.svg/400px-Makedonia_TV_2023.svg.png

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
> All channel data is taken from the [iptv-org/database](https://github.com/iptv-org/database) repository. If you find any errors please open a new [issue](https://github.com/iptv-org/database/issues) there.

https://github.com/iptv-org/iptv?tab=readme-ov-file#database
