### ISSUE TITLE
Broken: TUDN | (US)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#14419]
### Broken Link

https://unidfp-nlds141.global.ssl.fastly.net/nlds/univisionnow/udn2/as/live/udn2_hd_pc.m3u8?t1=

### What happened to the stream?

Not loading

### Possible Replacement (optional)

https://unidfp-nlds135.global.ssl.fastly.net/nlds/univisionnow/udn/as/live/udn_hd_pc.m3u8?t1=

### Notes (optional)

Broken Link and there's a error when trying to watch on Chrome 
![Screenshot_20231013_180352_Chrome](https://github.com/iptv-org/iptv/assets/83226646/20441368-07df-413b-b808-38be5cb802c7)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Managed to find a web proxy that could confirm the replacement link works. Otherwise, says 405 Not Allowed.
