### ISSUE TITLE
XXX category snuck in in safe list

### ISSUE THREAD

**Issue by rrjanbiah** [iptv-org/iptv#14415]
### Describe your issue

Ihttps://iptv-org.github.io/iptv/index.m3u has XXX category 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
Thanks for the report. Channel description has been corrected.

After the next update, both channels should disappear from the playlist

**Comment by rrjanbiah** [comment]
Thank you

**Comment by Amirshahra** [comment]
Hello, I want a sexy IPTV address.

در تاریخ شنبه ۱۴ اکتبر ۲۰۲۳،‏ ۱۴:۱۳ R. Rajesh Jeba Anbiah <
***@***.***> نوشت:
