### ISSUE TITLE
Add: ORT

### ISSUE THREAD

**Issue by iptvnikolas** [iptv-org/iptv#14416]
### Channel ID (required)

ORT.gr

### Channel Name

ORT

### Stream URL (required)

https://eu1.vectromdigital.com:1936/ort/ort/playlist.m3u8

### Quality

480p

### Label

Not 24/7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Seems that this channel doesn't stream in a 24/7 basis. Will check and approve tomorrow if working.

**Comment by iptvnikolas** [comment]
Yes

**Comment by freearhey** [comment]
<img width="1390" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/96024049-3ef7-4ca5-9398-0f0b43512d09">

**Comment by BellezaEmporium** [comment]
Yep, works for me too.
