### ISSUE TITLE
24 News Pakistan

### ISSUE THREAD

**Issue by zubair6472** [iptv-org/iptv#14428]
### Broken Link

https://ythls.onrender.com/channel/UCcmpeVbSSQlZRvHfdC-CRwg.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

not working fix it

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
alt https://ythlsgo.onrender.com/channel/UCcmpeVbSSQlZRvHfdC-CRwg.m3u8
