### ISSUE TITLE
Paigham Tv Urdu

### ISSUE THREAD

**Issue by zubair6472** [iptv-org/iptv#14429]
### Broken Link

https://ythls.onrender.com/channel/UCi-vOBG7Jgk_nKAG1Zd0R5g.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

not working 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
alt https://ythlsgo.onrender.com/channel/UCi-vOBG7Jgk_nKAG1Zd0R5g.m3u8
