### ISSUE TITLE
Broken: Al ghad channel 

### ISSUE THREAD

**Issue by akayed82** [iptv-org/iptv#14427]
### Broken Link

https://ythls.onrender.com/channel/UCH4UNKBHSNwstan99YDoCVg.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Looks like the entire [YouTube HLS](https://github.com/abskmj/youtube-hls-m3u8) is down at the moment.

**Comment by BellezaEmporium** [comment]
alt  https://ythlsgo.onrender.com/channel/UCH4UNKBHSNwstan99YDoCVg.m3u8
