### ISSUE TITLE
Add: Al Saudiya Alaan

### ISSUE THREAD

**Issue by CasperMcFadden95** [iptv-org/iptv#14434]
### Channel ID (required)

AlSaudiyaAlaan.sa

### Channel Name

Al Saudiya Alaan

### Stream URL (required)

https://edge.taghtia.com/sa/17.m3u8

### Quality

1080p

### Label

None

### Notes

Requires https://github.com/iptv-org/database/issues/6482

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
Closed in favor of #14436

**Comment by CasperMcFadden95** [comment]
> Closed in favor of #14436

Thanks! Nice Catch!
