### ISSUE TITLE
Add: TTV

### ISSUE THREAD

**Issue by BellezaEmporium** [iptv-org/iptv#14444]
### Channel ID (required)

TTV.pl

### Stream URL (required)

https://cdn-global.lolokoko.tv/TTV.stream/playlist.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
Blocked: https://github.com/iptv-org/iptv/issues/1831
