### ISSUE TITLE
Add: Private TV [NSFW]

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#14447]
### Channel ID (required)

PrivateTV.nl

### Stream URL (required)

http://149.62.183.194:9293/play/a07t

### Quality

576p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
+1 https://cdn-global.lolokoko.tv/Private.stream/playlist.m3u8
