### ISSUE TITLE
Add: Silk [NSFW]

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#14459]
### Channel ID (required)

Silk.ru

### Stream URL (required)

http://live-1.otcnet.ru/shelkhdmts/index.m3u8

### Quality

1080p

### Label

Geo-blocked

### Notes

<img width="1412" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/048cccdd-3c9e-4b34-9d9d-3bf0c9cf41e8">

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
403

**Comment by freearhey** [comment]
Added a label.

**Comment by BellezaEmporium** [comment]
Confirmed GEO, with my IP I get X-Deny-Reason: wrong_country

**Comment by Volas171** [comment]
![image](https://github.com/iptv-org/iptv/assets/60143910/c0381070-9194-448a-b3b5-cb9797c632e0)
very GEO.

**Comment by BellezaEmporium** [comment]
Managed to actually get it to work (Ukrainian IP in Kiev)
