### ISSUE TITLE
Add: Playboy TV [NSFW]

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#14460]
### Channel ID (required)

PlayboyTV.us

### Stream URL (required)

http://190.11.225.124:5000/live/playboy_hd/playlist.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by tozfek** [comment]
this issue should be deleted since it 1) violates github code of conduct and rules 2) is the first search result in google. 

I also recommend purging all adult streams from your git history to avoid being flagged as containing sexually explicit content.

**Comment by tozfek** [comment]
@BellezaEmporium
