### ISSUE TITLE
Add: ABJ TV [ZW]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#14463]
### Channel ID (required)

ABJTV.zw

### Channel Name

ABJ TV

### Stream URL (required)

https://ythlsgo.onrender.com/channel/UC82ZYZirnzkJ4Spek8Z8T6w.m3u8

### Quality

1080p

### Label

Not 24/7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Can't check it for now, as it's disabled for the moment.

**Comment by freearhey** [comment]
`ythls.onrender.com` is no longer active: https://github.com/iptv-org/iptv/issues/14427#issuecomment-1763288061

Alternative link:
https://ythlsgo.onrender.com/channel/UC82ZYZirnzkJ4Spek8Z8T6w.m3u8
