### ISSUE TITLE
missing channels

### ISSUE THREAD

**Issue by Basma87** [iptv-org/iptv#1447]
please in egypt playlist there were many channels that were working perfectly and now they are deleted please review them and add them again to the list 

channels are :
cbc
cbc drama
dmc
dmc drama
al nahar
al nahara drama 
al kahera wal nas
al kahera wal nas 2
cartoon network arabic

these what i can remeber now .

**Comment by freearhey** [comment]
We only delete links that stop working. This is exactly what happened in this situation. 

If you want you can double-check it yourself: https://github.com/iptv-org/iptv/commit/3e75496acc08b203f4755971f1f772353c5144b0#diff-1637e4636cb6ac7a8d0ba2f1189fb5d0 (deleted links are marked in red)

**Comment by Basma87** [comment]
isn't there any way to make them work again ??

**Comment by freearhey** [comment]
We have no control over the broadcasts. This repository contains only links to streams.

**Comment by Basma87** [comment]
Thanks for help
