### ISSUE TITLE
Broken: all Polish TVP streams from hbblivetv.v3.tvp.pl

### ISSUE THREAD

**Issue by theqkash** [iptv-org/iptv#14473]
### Broken Link

http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpbialystok

### What happened to the stream?

Not loading

### Notes (optional)

All following links are dead and currently there is no replacement. They've moved it to tokenized streams.

http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpbialystok
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpbydgoszcz
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpgdansk
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpgorzow
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpkatowice
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpkielce
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpkrakow
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvplodz
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvplublin
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpolsztyn
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpopole
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvppoznan
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvprzeszow
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpszczecin
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpwarszawa
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpwroclaw
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpinfo

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Weirdly enough, some of those still work for me.

**Comment by theqkash** [comment]
Lol yeah, they fixed is yesterday, as this is polish national media and this become fixed after elections which happened on sunday... But it wasn't working for month or so with official statement that it become available only on official site with tokens enabled...

Sorry for bothering then.

**Comment by bkuhls** [comment]
Do the streams still work for you? Here they give
```
$ nslookup hbbtvlive.v3.tvp.pl

** server can't find hbbtvlive.v3.tvp.pl: NXDOMAIN
```

**Comment by BellezaEmporium** [comment]
Nope, doesn't work for me either.
