### ISSUE TITLE
Broken: BBC  America, IFC East, Sundance East

### ISSUE THREAD

**Issue by GitHub-User101** [iptv-org/iptv#14470]
### Broken Link

https://bcovlive-a.akamaihd.net/c9bf201b06694453bb29282f97191f58/us-east-1/6240731308001/playlist.m3u8

### What happened to the stream?

Shows looped video

### Notes (optional)

IFC East
https://bcovlive-a.akamaihd.net/045bd3b615254da880c3db79b2e42fd0/us-east-1/6240731308001/playlist.m3u8

Sundance East
https://bcovlive-a.akamaihd.net/4d972ec6f41241f2b4286f8bdcc8dae9/us-east-1/6240731308001/playlist.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by spotanjo3** [comment]
IFC is dead.
