### ISSUE TITLE
Add: Blaze.uk

### ISSUE THREAD

**Issue by CasperMcFadden95** [iptv-org/iptv#14480]
### Channel ID (required)

Blaze.uk

### Channel Name

Blaze

### Stream URL (required)

https://live.blaze.tv/live7/blaze/bitrate1.isml/live.m3u8

### Quality

720p

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Geo.
