### ISSUE TITLE
Edit: Aire de Santa Fe

### ISSUE THREAD

**Issue by BellezaEmporium** [iptv-org/iptv#14484]
### Stream URL (required)

https://ythlsgo.onrender.com/channel/UCr7TYJVXSe3_rVILo-F8Xhg.m3u8

### Channel ID

AiredeSantaFe.ar

### Channel Name

Aire de Santa Fe

### Quality

1080p

### Label

None

### Notes

Replacement offered above.

Replaces https://sc1.stweb.tv/airedigital/live/playlist.m3u8 (doesn't work)
Another replacement link is https://unlimited1-us.dps.live/airedesantafetv/airedesantafetv.smil/playlist.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
There is no such link in the playlist: https://github.com/search?q=repo%3Aiptv-org%2Fiptv+https%3A%2F%2Fythlsgo.onrender.com%2Fchannel%2FUCr7TYJVXSe3_rVILo-F8Xhg.m3u8&type=code

If you want to add a new link, it is better to use this [form](https://github.com/iptv-org/iptv/issues/new?assignees=&labels=streams%3Aadd&projects=&template=-----streams_add.yml&title=Add%3A+).
