### ISSUE TITLE
keshet12(Israel News)

### ISSUE THREAD

**Issue by abormze** [iptv-org/iptv#14481]
### Channel ID (required)

Keshet12.il

### Channel Name

keshet12

### Stream URL (required)

https://isralive.tv/?page=keshet12

### Quality

720p

### Label

None

### HTTP Referrer

https://isralive.tv/?page=keshet12

### Notes

I want to start the channel with m3u8 and thx you

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Direct link is tokened : https://mako-streaming.akamaized.net/direct/hls/live/2033791/k12dvr/index.m3u8. Might be possible to call a certain API endpoint in order to get this link.

**Comment by abormze** [comment]
Thank you, the link works. Can we create a simple script for the channel, the main link above?

**Comment by abormze** [comment]
you can give me php to kan 11

https://www.livehdtv.net/kan-11-live-stream-israel/2/

I will be thankful to you, my friend

**Comment by BellezaEmporium** [comment]
https://kan11b.media.kan.org.il/hls/live/2096972/2096972/playlist.m3u8

**Comment by BellezaEmporium** [comment]
If however you were talking about the Educational channel : 

https://kan23.media.kan.org.il/hls/live/2024691/2024691/master.m3u8

**Comment by abormze** [comment]
Thank you my friend, I would have liked it php stream like this https://www.livehdtv.net/streams/channel12.php

**Comment by BellezaEmporium** [comment]
> Thank you my friend, I would have liked it php stream like this https://www.livehdtv.net/streams/channel12.php

Those are direct links, it should be better than the PHP stream, to be honest.

**Comment by abormze** [comment]
i know friends but i need it php if you can help me
