### ISSUE TITLE
Add: 

### ISSUE THREAD

**Issue by ChuFta** [iptv-org/iptv#14489]
### Channel ID (required)

ArenaSport1Croatia.hr

### Stream URL (required)

http://xtream.supermagicx.com:25461/get.php?username=skyspeed8&password=qJT3bKF0uv&type=m3u

### Quality

1080p

### Label

None

### Notes

i dont know much about iptv, but i found this link that contains many croatian, serbian, bosnian channels and it would be nice if it were added, i put ArenaSport1Croatia.hr for channel because it not just 1 channel but many

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ChuFta** [comment]
i also found this file
https://d.tousecurity.com/wp-content/plugins/download-attachments/includes/download.php?id=17965

**Comment by ChuFta** [comment]
this one contains many exyu channels and channel from all around the world but some streams dont work
http://lionboxiptv.xyz/get.php?username=protoniom1201&password=wMLkbzV8dXCC&type=m3u

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/master/FAQ.md#why-dont-you-accept-links-to-xtream-codes-server

**Comment by ChuFta** [comment]
> https://github.com/iptv-org/iptv/blob/master/FAQ.md#why-dont-you-accept-links-to-xtream-codes-server

what about the other links

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-distinguish-a-link-to-an-xtream-codes-server-from-a-regular-one
