### ISSUE TITLE
Add: 3AW [AU] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#14494]
### Channel ID (required)

3AW.au

### Channel Name

3AW Melbourne

### Stream URL (required)

https://3awlive.akamaized.net/hls/live/2032295/3AW/index.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
https://3awlive.akamaized.net/hls/live/2032295/3AW/index.m3u8 Adaptive
