### ISSUE TITLE
Broken: FOX 32 Chicago IL (WFLD) (720p)

### ISSUE THREAD

**Issue by Skates1616** [iptv-org/iptv#14498]
### Broken Link

https://lnc-wfld.tubi.video/index.m3u8

### What happened to the stream?

Other

### Notes (optional)

Wrong channel is being streamed, Fox LiveNow is streaming instead of FOX 32 (WFLD).

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Not the wrong channel. If you're familiar with how the channels provide their stream online, rare are the ones that provide an local stream (like Stremium/LocalBTV). They use their platforms (often Anvato/Lura or Tubi) to stream either news or certain local documentaries.

![snapshot](https://github.com/iptv-org/iptv/assets/30985701/8578985a-c413-45cd-84a4-15f42b221fb0)
