### ISSUE TITLE
Broken: Baby Shark TV (1080p)

### ISSUE THREAD

**Issue by giomgan1994** [iptv-org/iptv#14495]
### Broken Link

https://fc2f8d2d3cec45bb9187e8de15532838.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Roku_BabySharkTV/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Baby Shark TV is gone wrong connection please tell us now.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Used to redirect to ts files in https://newidco-babysharktv-1-us.roku.wurl.tv/playlist.m3u8
