### ISSUE TITLE
Add: viaplay xtra

### ISSUE THREAD

**Issue by Goldiefresh** [iptv-org/iptv#14503]
### Channel ID (required)

ViaplayXtra.uk

### Channel Name

Viaplay xtra 

### Stream URL (required)

https://i.mjh.nz/SamsungTVPlus/GBBB4300001NX.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Redirects to https://d3j7ofexbkp7q4.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-bl5ti7t9yiazp-ssai-prd/master.m3u8
