### ISSUE TITLE
Six Channel Is Working In France

### ISSUE THREAD

**Issue by cheznewa** [iptv-org/iptv#1450]
**Country of the channel:**

France

**Channel Name:**

https://news.cgtn.com/resource/live/french/cgtn-f.m3u8 CGTN Francais
http://ott-cdn.ucom.am/s30/index.m3u8 FTV (Fashion)
http://ott-cdn.ucom.am/s49/index.m3u8?fluxustv.m3u8 MCM Top
http://ott-cdn.ucom.am/s35/index.m3u8?fluxustv.m3u8 Mezzo
http://ott-cdn.ucom.am/s35/04.m3u8 Mezzo
**Channel Language:**
French

**Additional Information (optional):**
I To 5000 Commit Back For Check If The France Have One Day Passed The 100 Channels, And Check The Channel Is Work, So Four Begin By http://ott-cdn.ucom.am/ Working And CGTN Is Working Too.

**Comment by freearhey** [comment]
If you want, you can add channels to the playlist yourself. 

If you don't know how to do that, here's a guide: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#add-channel

**Comment by anassbouadil** [comment]
Thank you

Anass Bouadil.

Le 29 mai 2020 à 08:21, Aleksandr Statciuk <notifications@github.com> a écrit :

﻿

If you want, you can add channels to the playlist yourself.

If you don't know how to do that, here's a guide: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#add-channel
