### ISSUE TITLE
Add: TUDN 

### ISSUE THREAD

**Issue by Goldiefresh** [iptv-org/iptv#14502]
### Channel ID (required)

TUDNMexico.mx

### Channel Name

TUDN 

### Stream URL (required)

https://i.mjh.nz/SamsungTVPlus/USBD1700016X9.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Redirects to https://dc0yy1cy2mqs1.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-cmi4c1ko7cgug/playlist.m3u8
