### ISSUE TITLE
Add: Imagen TV

### ISSUE THREAD

**Issue by jesusvlc** [iptv-org/iptv#14517]
### Channel ID (required)

ImagenTV.mx

### Channel Name

Imagen TV

### Stream URL (required)

https://ythlsgo.onrender.com/channel/UCl5JKSQsl-_WSU1rz7_BCJA.m3u8

### Quality

None

### Label

None

### Notes

hola pueden agregar este canal? . Gracias es de mexico.

https://m.youtube.com/watch?v=6we2wbLexUw&embeds_referring_euri=https%3A%2F%2Fphotocall.tv%2F&source_ve_path=MjM4NTE&feature=emb_title

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ztreamhd** [comment]
Proper stream links would be `https://ythlsgo.onrender.com/channel/UCl5JKSQsl-_WSU1rz7_BCJA.m3u8` or `https://ythlsgo.onrender.com/video/6we2wbLexUw.m3u8` but the YTHLS page seems not to be working right now. I don't know if someone else has an alternative for YouTube streams though.

**Comment by freearhey** [comment]
`ythlsgo.onrender.com` is down at the moment, the broadcast itself is online:

https://www.youtube.com/watch?v=6we2wbLexUw
<img width="937" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/7f980f31-d9b1-4fad-894f-8146c9da15c3">
