### ISSUE TITLE
Channel streams

### ISSUE THREAD

**Issue by mofouly** [iptv-org/iptv#1452]
So i just tried some of the m3u files in VLC, and noticed that a lot of the channels have a like a "time" to watch them. Some of them are like 24seconds, 1 minute, etc. But as soon as that time expires, the channel stops streaming anything. I'm wondering if this is because of the token being used, or is there something else i'm missing here?

Thanks
![Capture](https://user-images.githubusercontent.com/25626947/83302959-37cf0000-a1ca-11ea-9ba0-8d3946f3b38c.PNG)

**Comment by freearhey** [comment]
Yes, you're right. As it turned out, some of the broadcasts work in demo mode and stop working after a minute. 

Unfortunately, the only thing we can do is remove such links. But as soon as there is a working version, we will return them.

**Comment by CHJ85** [comment]
VLC is not gonna work for this stuff.
As far as IPTV, VLC is only being used for testing.
I suggest you use something like Kodi for instance.

**Comment by mofouly** [comment]
> 
> 
> VLC is not gonna work for this stuff.
> As far as IPTV, VLC is only being used for testing.
> I suggest you use something like Kodi for instance.

Sorry, I should have mentioned that i did test this on my TV  with the smart IPTV [app ](https://siptv.eu/about/) and i was experiencing the same issue. In my opinion the issue isn't really resolved...

**Comment by freearhey** [comment]
@mofouly All non-working links were removed from playlists and, unfortunately, there's nothing else we can do in this situation.

But if you need help finding a link to specific channels, it is better to create a separate [issue](https://github.com/iptv-org/iptv/issues/new?assignees=&labels=channel+request&template=channel-request.md&title=).
