### ISSUE TITLE
Broken: Free to air DD & News 18 channels of India

### ISSUE THREAD

**Issue by ls-milkyway** [iptv-org/iptv#14544]
### Broken Link

https://ythlsgo.onrender.com/channel/UCWk-7Yosyvzln9ZzJg8BvVg.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Hi!

Many links under country->India have stopped working? **It Seems the problem is with "https://ythlsgo.onrender.com"**
 
**For example the DD channels:**

`DDBharati.in	https://i.imgur.com/4tfUIEo.png	Undefined			DD Bharati (1080p) [Not 24/7]	https://ythlsgo.onrender.com/channel/UCIAnlTV3O9NYWMI-DwYZaWg.m3u8

DDIndia.in	https://i.imgur.com/45uptR8.png	Undefined			DD India (1080p) [Not 24/7]	https://ythlsgo.onrender.com/channel/UCGDQNvybfDDeGTf4GtigXaw.m3u8

DDKashir.in	https://i.imgur.com/1EI4LOf.png	Undefined			DD Kashir (1080p) [Not 24/7]	https://ythlsgo.onrender.com/channel/UCOqU-HfQxoyImaCW2tCDxJA.m3u8

DDKisan.in	https://i.imgur.com/x56WJEa.png	Undefined			DD Kisan (1080p) [Not 24/7]	https://ythlsgo.onrender.com/channel/UCnDfmcUyhgJp6xC1LmBLfUg.m3u8

DDNews.in	https://i.imgur.com/H4f9R7n.png	News			DD News (1080p) [Not 24/7]	https://ythlsgo.onrender.com/channel/UCKwucPzHZ7zCUIf7If-Wo1g.m3u8

DDPunjabi.in	https://i.imgur.com/WVtl6n2.png	Undefined			DD Punjabi (1080p) [Not 24/7]	https://ythlsgo.onrender.com/channel/UC8GYp35wJTN2ituJr0y-7AQ.m3u8

DDSports.in	https://i.imgur.com/J2Ky5OO.png	Sports			DD Sports (576p)	http://103.199.161.254/Content/ddsports/Live/Channel(DDSPORTS)/index.m3u8

DDUrdu.in	https://i.imgur.com/OiQPS34.png	Undefined			DD Urdu (720p) [Not 24/7]	https://ythlsgo.onrender.com/channel/UCu9Fj9QRAg26ZY9DhF8HSrQ.m3u8

DDUttarPradesh.in	https://i.imgur.com/oKsUqBs.png	Undefined			DD Uttar Pradesh (720p) [Not 24/7]	https://ythlsgo.onrender.com/channel/UCxtPipsf2nUZ9xM33TPe93Q.m3u8

DDUttarakhand.in	https://i.imgur.com/GzBsbos.png	Undefined			DD Uttarakhand (480p) [Not 24/7]	https://ythlsgo.onrender.com/channel/UCx55tefMzKkaA0uDmj9g2XA.m3u8
`
**& News 18 channels:**

`News18BiharJharkhand.in	https://i.imgur.com/FQ3zDZE.png	News			News18 Bihar Jharkhand (1080p)	https://ythlsgo.onrender.com/channel/UC531MlZA5LUbeGwEN_zcppw.m3u8

News18India.in	https://i.imgur.com/5VLCwbt.png	News			News18 India (720p) [Not 24/7]	https://ythlsgo.onrender.com/channel/UCPP3etACgdUWvizcES1dJ8Q.m3u8

News18PunjabHaryanaHimachal.in	https://i.imgur.com/iWpFxF7.png	News			News18 Punjab/Haryana/Himachal (720p) [Not 24/7]	https://ythlsgo.onrender.com/channel/UC-crZTQNRzZgzyighTKF0nQ.m3u8

News18Rajasthan.in	https://i.imgur.com/Y7c0omK.png	News			News18 Rajasthan (1080p) [Not 24/7]	https://ythlsgo.onrender.com/channel/UC7FlLbNo66YsCEAPuJITiNg.m3u8

News18Urdu.in	https://i.imgur.com/8xnwMRR.png	News			News18 Urdu (720p) [Not 24/7]	https://ythlsgo.onrender.com/channel/UC9IQhNgS43lmUdU-KdGyb0A.m3u8

News18UttarPradeshUttarakhand.in	https://i.imgur.com/VcwkEDM.png	News			News18 Uttar Pradesh Uttarakhand [Not 24/7]	https://ythlsgo.onrender.com/channel/UCafYgzpyw7aIUYOLjjADu7w.m3u8`

**Plus many more channels.**

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ls-milkyway** [comment]
Seems service https://ythls.onrender.com is also down ...hmm I understand we need to create a service using a cloud provider (as per https://github.com/abskmj/youtube-hls-m3u8) .Any suggestion for both the provider and it's plan best suited for this purpose.

**Comment by BellezaEmporium** [comment]
![image](https://github.com/iptv-org/iptv/assets/30985701/5f25a42a-cc52-4154-b592-04266e8cd2f5)
Seems like it.

**Comment by ls-milkyway** [comment]
> ![image](https://user-images.githubusercontent.com/30985701/278808324-5f25a42a-cc52-4154-b592-04266e8cd2f5.png) Seems like it.

Extension name please?? Kindly suggest/correct the urls by a pull request.

**Comment by BellezaEmporium** [comment]
> > ![image](https://user-images.githubusercontent.com/30985701/278808324-5f25a42a-cc52-4154-b592-04266e8cd2f5.png) Seems like it.
> 
> Extension name please?? Kindly suggest/correct the urls by a pull request.

Personal implementation, that I cannot share for evident request flooding issues (plan doesn't permit me to do so)

**Comment by ls-milkyway** [comment]
> > > ![image](https://user-images.githubusercontent.com/30985701/278808324-5f25a42a-cc52-4154-b592-04266e8cd2f5.png) Seems like it.
> > 
> > 
> > Extension name please?? Kindly suggest/correct the urls by a pull request.
> 
> Personal implementation, that I cannot share for evident request flooding issues (plan doesn't permit me to do so)

https://github.com/orgs/iptv-org/discussions/1527

**Comment by ghostrider022** [comment]
https://ythlsgo.onrender.com/channel/UC8GYp35wJTN2ituJr0y-7AQ.m3u8

Not working kindly fix it.

**Comment by BellezaEmporium** [comment]
https://ythls.armelin.one/channel/UC8GYp35wJTN2ituJr0y-7AQ.m3u8

**Comment by ghostrider022** [comment]
This also not working

**Comment by BellezaEmporium** [comment]
Simply because they're not on-air right now.
