### ISSUE TITLE
Broken: Bloomberg TV+ UHD (2160p)

### ISSUE THREAD

**Issue by keatre** [iptv-org/iptv#14550]
### Broken Link

https://bloomberg-bloombergtv-1-es.samsung.wurl.com/manifest/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

VLC reports: access error: HTTP 404 error

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
ERR_SSL_UNRECOGNIZED_NAME_ALERT|
 TLS handshake error: A TLS fatal alert has been received.
 
 Probably moved somewhere

**Comment by BellezaEmporium** [comment]
https://bloomberg-bloombergtv-1.ono.wurl.com/manifest/playlist.m3u8 ?

**Comment by CasperMcFadden95** [comment]
https://i.mjh.nz/SamsungTVPlus/ always has the latest links
