### ISSUE TITLE
Add: Visit-X TV [NL] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#14552]
### Channel ID (required)

VisitXTV.nl

### Channel Name

Visit-X TV

### Stream URL (required)

https://stream.visit-x.tv/vxtv/live/playlist.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Thought we had it. How odd.
