### ISSUE TITLE
Add: Windrush [BO]

### ISSUE THREAD

**Issue by imlinky** [iptv-org/iptv#14553]
### Channel ID (required)

Windrush.bo

### Channel Name

Windrush

### Stream URL (required)

https://cablemor.andremor.dev/live/Windrush/index.m3u8

### Quality

720p

### Label

Not 24/7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
![image](https://github.com/iptv-org/iptv/assets/5430116/5ac88702-98e5-479f-9a4b-8c6735382aa4)
Showing heavily buffering 6 second video to me. Not 24/7 at best

**Comment by BellezaEmporium** [comment]
Not 24/7 : Nos vemos el proximo viernes - We'll see you next Friday

**Comment by Dum4G** [comment]
added a label
