### ISSUE TITLE
Add: Bollywood HD

### ISSUE THREAD

**Issue by CasperMcFadden95** [iptv-org/iptv#14559]
### Channel ID (required)

BollywoodHD.ro

### Channel Name

Bollywood HD

### Stream URL (required)

https://shls-live-ak.akamaized.net/out/v1/fb7b452f58f2412a9ae26b22dd30bd6b/index.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Isn't a Russian broadcast, it's in English
