### ISSUE TITLE
Broken: Ávila TV (And other channels of Venezuela)

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#14555]
### Broken Link

https://cdn.odysee.live/content/9fc00ad00fd8b0f08ab11f2324c82ffd713c3cb6/master.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

This links of Odysee don't works.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Replace "cdn" by "cloud", and add a referer pointing to https://odysee.com/
