### ISSUE TITLE
if it possible to Add this channels for Algerien 

### ISSUE THREAD

**Issue by hassuni** [iptv-org/iptv#1461]
Hi All,
if it possible to Add this channels for Algerien 
http://www.htatv.com/

**Comment by themak1985** [comment]
@hassuni problem with the algerian channels - they all have tokens/hash that expire. 
#758 and #863 are examples.

**Comment by freearhey** [comment]
Ennahar TV https://github.com/iptv-org/iptv/blob/9469726770fb436f1e75030bd24e495d49f97ebc/channels/dz.m3u#L2-L3

**Comment by freearhey** [comment]
Closed in favor #1961 and #1939
