### ISSUE TITLE
add Channel of Wuxi City in China

### ISSUE THREAD

**Issue by zhanglianbo35** [iptv-org/iptv#1466]
**Country of the channel:**

China

**Channel Name:**

 listed in below

**Channel Language:**
Chinese 

**Additional Information (optional):**
add these channel in below

#EXTM3U
#EXTINF:-1 ,无锡都市资讯
http://live-wx.wifiwx.com/wxtv3/sd/live.m3u8
#EXTINF:-1 ,无锡经济
http://live-wx.wifiwx.com/wxtv5/sd/live.m3u8
#EXTINF:-1 ,无锡生活
http://live-wx.wifiwx.com/wxtv4/sd/live.m3u8
#EXTINF:-1 ,无锡新闻综合
http://live-wx.wifiwx.com/wxtv1/sd/live.m3u8
#EXTINF:-1 ,无锡娱乐
http://live-wx.wifiwx.com/wxtv2/sd/live.m3u8

**Comment by freearhey** [comment]
I don't have any links working.
<img width="608" alt="Captura de pantalla 2020-06-01 a las 12 39 45" src="https://user-images.githubusercontent.com/7253922/83396702-0d1cbb80-a405-11ea-9233-88859cfd149b.png">

**Comment by zhanglianbo35** [comment]
in my home internet, they can display
