### ISSUE TITLE
name truncated in json file

### ISSUE THREAD

**Issue by zhanglianbo35** [iptv-org/iptv#1467]
**What's wrong?**
 truncated in https://iptv-org.github.io/iptv/channels.json  "name":"CCTV中国中央电视台-12 社会与法"
**Country of the channel:**
China
**Channel Name:**
"CCTV中国中央电视台-12 社会与法"
**Broken Link:**

update name to "CCTV中国中央电视台-12 社会与法制"
**Additional Information (optional):**

**Comment by freearhey** [comment]
Thank you for your help. I already updated the channel name.
