### ISSUE TITLE
Channel request

### ISSUE THREAD

**Issue by jj2132001** [iptv-org/iptv#1484]
Hi guys any way TLC in English can be added?

Appreciate the help.

**Comment by CHJ85** [comment]
I'm not gonna create a pull request, so feel free to do that yourself. Here's TLC East:
http://live.highstream.club/live/TLC/chunks.m3u8
Logo: https://i.imgur.com/0vKqQfa.png

**Comment by freearhey** [comment]
@CHJ85 This link doesn't work:
<img width="317" alt="Captura de pantalla 2020-06-16 a las 13 29 22" src="https://user-images.githubusercontent.com/7253922/84763814-755ac800-afd5-11ea-9b4a-eb998281cdf5.png">

**Comment by CHJ85** [comment]
Yes it does. It's offline a couple hours a day. Only during paid programming and when there's nothing on though.

**Comment by freearhey** [comment]
TLC cannot be added to the playlist due to claims of the copyright holder. More details here: #1831
