### ISSUE TITLE
working link for djing hot hot hot missing,remain one dead

### ISSUE THREAD

**Issue by gfwfuckoff** [iptv-org/iptv#1486]
there was a duplicated one before，one working ok，one not，the one left now only playing a loop video，Never playing any edm ,just a official djing channel advertisement looping all the time，can u get the working one back?Thx!

**Comment by freearhey** [comment]
we have no control over the broadcasts, so the only thing I can do in this situation is to remove the broken channels from the playlist.

**Comment by gfwfuckoff** [comment]
thx anyway! guess the right one being removed due to duplicated channel?previous one works ok，if mistakenly removed，could u find it?whoops!maybe i can get it later，iptvmate.com have the right link，give me a sec😁，but be ware that pls don't remove the working one and instead  left the dead one if duplicated links for 1 channel  happens 😂

**Comment by SileC** [comment]
https://www.djing.com/tv/h-01-fta.m3u8

**Comment by gfwfuckoff** [comment]
https://www.djing.com/tv/h-01-fta.m3u8
just find it too ，pls replace with this one ，thx!

**Comment by freearhey** [comment]
@SileC this broadcast lasts less than a minute and then breaks.

**Comment by SileC** [comment]
All links I found are now in loop. Probably issue can be closed until they start working again

**Comment by freearhey** [comment]
Closed in favor #1975
