### ISSUE TITLE
Lebanon channels

### ISSUE THREAD

**Issue by grasshopper860** [iptv-org/iptv#1488]
**What's wrong?**please fix freezing and missing channle (al jadadeed) 

**Country of the channel:**Lebanon

**Channel Name:**

**Broken Link:**
https://iptv-org.github.io/iptv/countries/lb.m3u

**Additional Information (optional):**

**Comment by freearhey** [comment]
Duplicate #1431

**Comment by hachemal** [comment]
all Lebanese channels work for less than a minute and then disconnect.

**Comment by Ziad-84** [comment]
> all Lebanese channels work for less than a minute and then disconnect.

Lebanese and Syrian
