### ISSUE TITLE
Lebanese Channels

### ISSUE THREAD

**Issue by asa-sal** [iptv-org/iptv#1489]
**What's wrong?**
Some channels are  disconnect after a short time sometime( 40 seconds till max 2 minutes )

**Country of the channel:**
Lebanese Channels
https://iptv-org.github.io/iptv/countries/lb.m3u 

**Channel Name:**
Futur Tv, LBC International, MTV Lebanon, Otv

**Broken Link:**
http://178.132.3.162:88/Future_TV/video.m3u8?token=test
http://51.15.3.161:8080/LDC/index.m3u8?token=test
http://178.132.3.162:88/MTV_Lebanon/video.m3u8?token=test
http://178.132.3.162:88/OTV/video.m3u8?token=test

**Additional Information (optional):**
I am not sure if this website will help you http://www.elahmad.com/tv/Webtv/Arabian.htm#Lebanon

**Comment by freearhey** [comment]
I already removed these channels from the playlists: https://github.com/iptv-org/iptv/commit/dd908e1b17dff29924e60cbcd95a4bf47197ff09 

Tomorrow they should disappear from the rest of the files as well.
