### ISSUE TITLE
Add: Samira TV

### ISSUE THREAD

**Issue by CasperMcFadden95** [iptv-org/iptv#14919]
### Channel ID (required)

SamiraTV.dz

### Channel Name

Samira TV

### Stream URL (required)

https://raw.githubusercontent.com/ipstreet312/freeiptv/master/ressources/dzflix/samira.m3u8

### Quality

576p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Why? You just pull requested it today

**Comment by CasperMcFadden95** [comment]
My mistake. sorry. Thankyou!
