### ISSUE TITLE
Iraqi channel request

### ISSUE THREAD

**Issue by PazuzuBabel** [iptv-org/iptv#1494]
Iraq

Al summaria

Arabic

Official stream can be found [here](https://www.alsumaria.tv/live/video)

**Comment by muaztakrouri** [comment]
**Livestream Link**
https://cllive.itworkscdn.net/alsumariatvlive/token=nva=1591993825~dirs=1~hash=0d45f8ff24b4829cac087/sumariamob.smil/playlist_1080p.m3u8

**Channel Logo**
https://www.alsumaria.tv/uploadImages/ProgramsImages/Channels-L-1-636916940695846700.png

**Channel Country**
Iraq

**Channel Language**
Arabic

**Comment by freearhey** [comment]
@muaztakrouri The link no longer works.
<img width="317" alt="Captura de pantalla 2020-06-13 a las 17 30 28" src="https://user-images.githubusercontent.com/7253922/84571409-9afc8d00-ad9b-11ea-8d69-9a95a9e763c0.png">

**Comment by Nintendocustom** [comment]
> **Livestream Link**
> https://cllive.itworkscdn.net/alsumariatvlive/token=nva=1591993825~dirs=1~hash=0d45f8ff24b4829cac087/sumariamob.smil/playlist_1080p.m3u8
> 
> **Channel Logo**
> https://www.alsumaria.tv/uploadImages/ProgramsImages/Channels-L-1-636916940695846700.png
> 
> **Channel Country**
> Iraq
> 
> **Channel Language**
> Arabic
@muaztakrouri 
Where is the link from?

**Comment by muaztakrouri** [comment]
@Nintendocustom 
I've got the link from the channel official site:
https://www.alsumaria.tv/live/video
But then I realized that the link is kind of encrypted and the **Token, hash** values is changing frequently.

**Comment by themak1985** [comment]
Yes - thats the issue with sumaria - the token and hash values change often.

**Comment by Nintendocustom** [comment]
I finally had some time to look at the stream and I made a PR with a working link.

**Comment by Nintendocustom** [comment]
@themak1985 I can look at your links too!

**Comment by themak1985** [comment]
@Nintendocustom thanks for your help with this. There are a lot that I compiled in #758
