### ISSUE TITLE
channels request 

### ISSUE THREAD

**Issue by AndreiB85** [iptv-org/iptv#1495]
**Country of the channel:**
Romanian 

**Channel Name:**
Prima Tv 
Acasă Tv 
B1 Tv
Antena1 
Antena Star 

**Channel Language:**
Romanian 

**Additional Information (optional):**
Can be possible, please any update for the Romanian m3u playlist with the following channels up 👆. 
Please I am begging, I am trying to get them from different sources nophing works. 
Thank you, 
AndreiB

**Comment by harika532** [comment]
good man

**Comment by pedritostia** [comment]
Country: Cuba
Channel names:
Cubavisión
Canal Habana
Canal Educativo
Canal Educativo 2
Canal Caribe
Canal Clave
Multivision
Telerebelde

Channel Language: Spanish

Additional Information:
There is no m3u list for Cuba or any cuban channels. Please add them if possible.

**Comment by freearhey** [comment]
Duplicate #1244
