### ISSUE TITLE
Add: Love Nature 4K

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#14955]
### Channel ID (required)

LoveNature4K.ca

### Stream URL (required)

https://d18dyiwu97wm6q.cloudfront.net/playlist.m3u8

### Quality

2160p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
adaptive https://d18dyiwu97wm6q.cloudfront.net/playlist.m3u8
