### ISSUE TITLE
Add: TV Rodopi

### ISSUE THREAD

**Issue by iptvnikolas** [iptv-org/iptv#14978]
### Channel ID (required)

TVRodopi.gr

### Channel Name

TV Rodopi

### Stream URL (required)

https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/TVRodopi.m3u8

### Quality

720p

### Label

Not 24/7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Will check later on (when stream will be available).

**Comment by iptvnikolas** [comment]
Rodopi TV the day before yesterday at noon that I was watching had a stream available. Why doesn't he have it today?

**Comment by BellezaEmporium** [comment]
As you've indicated, the channel isn't 24/7, meaning it has a specific schedule. It might only stream on certain times.

**Comment by freearhey** [comment]
> Can not find channel

https://github.com/azgaresncf/strm2hls/blob/main/streams/TVRodopi.m3u8#L1C1-L1C21

**Comment by iptvnikolas** [comment]
Now it works normally.
