### ISSUE TITLE
Add: Univision LATAM

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#14974]
### Channel ID (required)

UnivisionPanregional.mx

### Channel Name

Univision Latinoamérica

### Stream URL (required)

https://linear-424.frequency.stream/dist/vix/424/hls/master/playlist.m3u8

### Quality

None

### Label

None

### Notes

This is Latin America version of Univision not to be confused with the Univision In in US

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by shelomito12** [comment]
https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_fastly.m3u

**Comment by R4IN2007** [comment]
> https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_fastly.m3u

Latin American Version of Univision not the USA Version.
