### ISSUE TITLE
Add:  Korean Central Television

### ISSUE THREAD

**Issue by goliv04053** [iptv-org/iptv#14973]
### Channel ID (required)

KoreanCentralTelevision.kp

### Channel Name

 Korean Central Television

### Stream URL (required)

https://tv.nknews.org/tvdash/stream.mpd

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/08bb02872a9a4f41e7791966040fe1a767cb43c3/streams/kp.m3u#L2-L3
