### ISSUE TITLE
kurdish Channel Request

### ISSUE THREAD

**Issue by hawrazsabr** [iptv-org/iptv#1498]
**Country of the channel:**
Iraq

**Channel Name:**
Iraqia Kurdish
WAAR TV HD
Korek TV
NRT TV HD
Kurdsat News HD
Ava Media TV
Kurd Channel TV
NRT 4

**Channel Language:**
Kurdish

**Additional Information (optional):**
Please Add this Channel and this is frequency Channel from (NileSat 7W) :

Iraqia Kurdish
https://www.lyngsat.com/tvchannels/iq/Iraqia-Kurdish.html

WAAR TV HD
https://www.lyngsat.com/tvchannels/iq/Waar-TV.html

Korek TV
https://www.lyngsat.com/tvchannels/iq/Korek-TV.html

NRT TV HD
https://www.lyngsat.com/tvchannels/iq/NRT.html

Kurdsat News HD
https://www.lyngsat.com/tvchannels/iq/Kurdsat-News.html

AVA Media TV
https://www.lyngsat.com/tvchannels/iq/Ava-TV.html

Kurd Channel TV
https://www.lyngsat.com/tvchannels/iq/Kurd-Channel.html

NRT 4
https://www.lyngsat.com/tvchannels/iq/NRT-4.html

**Comment by themak1985** [comment]
- [ ] Iraqia Kurdish
Found no streams.
- [ ] WAAR TV HD
https://waarmedia.com/en/live/ - tokenized link source.
- [ ] Korek TV
https://www.youtube.com/c/KorekTV no livestream source found.
- [ ] NRT TV HD
https://nrttv.com/streamNRT.aspx streams do not seem to be working. 
- [X] Kurdsat News HD
Already in IQ Playlist
- [ ] Ava Media TV
https://ok.ru/live/1590498696864 We cannot use ok.ru links - they're tokenized
- [X] Kurd Channel TV
#1869 - https://server5.ikomg.com/hls/kurd.m3u8 from https://www.kurdch.tv/?page_id=216
- [ ] NRT 4
https://nrttv.com/streamNRT.aspx 4 not found.

**Comment by freearhey** [comment]
Closed in favor #1955
