### ISSUE TITLE
Win Sport + aqui

### ISSUE THREAD

**Issue by Canner47** [iptv-org/iptv#15000]
Win Sport + aqui
http://181.78.24.67:8010/play/a05w/index.m3u8

_Originally posted by @ElMakia in https://github.com/iptv-org/iptv/issues/2301#issuecomment-1769725690_
            Se cayó nuevamente, me ayudas, gracias!

**Comment by Alstruit** [comment]
https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#contributing-guide

**Comment by Andreslm1** [comment]
Bro está caído

**Comment by DaniJay10** [comment]
no sirve
