### ISSUE TITLE
Add: Skai BUP

### ISSUE THREAD

**Issue by iptvnikolas** [iptv-org/iptv#15005]
### Channel ID (required)

SkaiBUP.gr

### Channel Name

Skai BUP

### Stream URL (required)

https://cdn.nclr.eu/hls/SkaiSD_src.m3u8

### Quality

720p

### Label

Not 24/7

### Timeshift

0

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by komhsgr** [comment]
Σοβαρέψου ρε Νικο οτι βλακεια και ανοησια βρισκεις στο internet το πασάρεις εδώ. Μια με το twitch link μια με αυτα τα links.

**Comment by iptvnikolas** [comment]
Κόμη τι φταίω τα βρίσκω στις ιστοσελίδες των καναλιών.
