### ISSUE TITLE
Broken: (BACK ONLINE)

### ISSUE THREAD

**Issue by frank773-lol** [iptv-org/iptv#15007]
### Broken Link

http://203.162.235.41:14093

### What happened to the stream?

Not loading

### Notes (optional)

The stream worked earlier today, but then I tested it again and I got an error, which has never happened to me.

(I used VLC)
(last time i checked, it's still on the repository)

UPDATE: IT'S BACK ONLINE
### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Carlinhos027** [comment]
Could you please specify the channel and/or playlist that link belongs to? Thx.

**Comment by frank773-lol** [comment]
Update: it's back online, i don't know what happened, but it works now
