### ISSUE TITLE
Add: Fox News Channel (144p)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15003]
### Channel ID (required)

FoxNewsChannel.us

### Channel Name

Fox News Channel

### Stream URL (required)

http://247preview.foxnews.com/hls/live/2020027/fncv3preview/primary.m3u8

### Quality

None

### Label

None

### Notes

Only main Fox News m3u8

Better Resolution (Not Official link)
http://38.96.178.201:80/live/FOXNEWS/index.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
The one I have is this : http://247.foxnews.com/hls/live/2003586/FNCHLSv3/primary.m3u8

**Comment by spotanjo3** [comment]
Better resolution quality please ?
