### ISSUE TITLE
Add: Jenny For You [NSFW]

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#15014]
### Channel ID (required)

JennyForYou.us

### Stream URL (required)

https://59ec5453559f0.streamlock.net/jennyforyou/jennyforyou/playlist.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by iptvnikolas** [comment]
Seems like a weird channel.
