### ISSUE TITLE
Arabic channels not working or missing! 

### ISSUE THREAD

**Issue by iptvchecker** [iptv-org/iptv#1501]
**What's wrong?**

- Very few channels are working whether on Flex IPTV, VLC or IINA players!
I can search for Rotana channels and try to play them. Only Rotana Kids work! This tells me that something "is" wrong with the rest of the channels.

The developer wrote to me, in a email that he uses ElMedia player and that all the channels work fine using that player! Unless the format of the m3u8 has changed to play on ElMedia player, all the channels should work everywhere!

- Nile channels are messing.
**Country of the channel:**

**Channel Name:**
Nile Drama, etc are missing

**Broken Link:**

https://iptv-org.github.io/iptv/languages/ara.m3u  (All rotana channels except for Kids!)
**Additional Information (optional):**

**Comment by 0x41mmarVM** [comment]
All Rotana channels are working for me, as do the majority of the channels in 
https://iptv-org.github.io/iptv/languages/ara.m3u
And yes, m3u8 should play anywhere, which means either it’s a freak temporary issue or there’s something wrong on your end. 
Try taking the channel m3u8 URL from the list and opening it in a browser, see what you get.

I couldn’t find a stream for Nile channels online with a quick google. If you can find one point it out and it will be added.

**Comment by freearhey** [comment]
I have this playlist working fine, too.

**Comment by iptvchecker** [comment]
What player do you use? This is very strange! Why would Rotana classic, and others work for you, and only Rotana kids shows here! I am including the error messages!

<img width="1365" alt="Screen Shot 2020-06-11 at 10 33 41 PM" src="https://user-images.githubusercontent.com/56801539/84547781-bf9d2a00-acf3-11ea-85c1-1a94e9379774.png">

**Comment by iptvchecker** [comment]
You closed the ticket. What about the missing channels for Nile drama and others?

**Comment by iptvchecker** [comment]
The problem is not with the players, any of them! It's the IP address that is downloading the playlist. I opened Rotana cinema link from (https://iptv-org.github.io/iptv/languages/ara.m3u), which is (https://rotana.hibridmedia.com/rotana/cinema_dabr/playlist.m3u8). The hosting site says "Forbidden" to download. This happens on my regular firefox browser and TOR browser. If I keep changing the IP address for the Tor browser, eventually I am able to download the sub-list. But obviously because my media player is not connected to one of those cleared countries, the media does not play!

If you have control over the hosting sites, for the playlists, please inform them not to block access to the hosted media, or it's useless! 

Any thoughts?

<img width="809" alt="Screen Shot 2020-06-12 at 3 26 13 PM" src="https://user-images.githubusercontent.com/56801539/84550997-be6ffb00-acfb-11ea-977d-2414e7f395d9.png">
)

**Comment by 0x41mmarVM** [comment]
The links come directly from the websites of the tv channels, so the link you tested comes from https://rotana.net/live/ 
If geoblocking is implemented, it's Rotana Cinema that implemented it. No one associated with this project will be able to help with that. 
And on that note, if you can find a free online stream for Nile channels, start a ticket with the link, and the lovely people maintaining this project will probably add it.

**Comment by freearhey** [comment]
@iptvchecker I use VLC Player, Elmedia Video Player and streamtest.in for tests.

If you want help finding a working broadcast of Nile Drama, it is better to create a separate [issue](https://github.com/iptv-org/iptv/issues/new?assignees=&labels=channel+request&template=channel-request.md&title=).
