### ISSUE TITLE
Add: Meclis TV - TR

### ISSUE THREAD

**Issue by ramazansancar** [iptv-org/iptv#15010]
### Channel ID (required)

MeclisTV.tr

### Channel Name

Meclis TV

### Stream URL (required)

 https://meclistv-live.ercdn.net/meclistv/meclistv.m3u8

### Quality

720p

### Label

None

### Notes

Source: https://tv.tbmm.gov.tr/

Channel ID Request: https://github.com/iptv-org/database/issues/7536

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/611cc9b242fd7d1cea753cb643f6e968a19136e6/streams/tr.m3u#L354-L355
