### ISSUE TITLE
Nepali channels are not working

### ISSUE THREAD

**Issue by bedbyaspokhrel** [iptv-org/iptv#1502]
Hello all nepali only one channel is working others are not working
.

**Comment by freearhey** [comment]
I just checked the links in the playlist and they're all working fine now.
<img width="720" alt="Captura de pantalla 2020-06-12 a las 16 28 47" src="https://user-images.githubusercontent.com/7253922/84507728-f3635a00-acc9-11ea-934b-627512494a21.png">
