### ISSUE TITLE
Aljazeera Documentary

### ISSUE THREAD

**Issue by muaztakrouri** [iptv-org/iptv#1503]
**Country of the channel:**
Qatar

**Channel Name:**
al jazeera documentary

**Channel Language:**
Arabic

**Channel Stream Link**
https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1591991919/ei/D4rjXqfCEZqL1wKD-ZyIBQ/ip/88.253.22.67/id/Hk6W2D9Ykg8.0/source/yt_live_broadcast/requiressl/yes/hfr/1/playlist_duration/30/manifest_duration/30/maudio/1/gcr/tr/vprv/1/go/1/keepalive/yes/dover/11/itag/0/playlist_type/DVR/sparams/expire,ei,ip,id,source,requiressl,hfr,playlist_duration,manifest_duration,maudio,gcr,vprv,go,itag,playlist_type/sig/AOq0QJ8wRQIgdSSoai_PU2_ytfs6Zvd0y_lLL9DQTyUHpQnhhsYesEkCIQDk2sx1oDvYiHrxT5jHtK8b4dod7mAvNAAucT8NCpoy8w==/file/index.m3u8

**Channel Logo**
https://upload.wikimedia.org/wikipedia/en/thumb/e/e6/Al_Jazeera_Doc.png/150px-Al_Jazeera_Doc.png

**Comment by muaztakrouri** [comment]
**Updated Streaming link**
https://live-hls-web-ajd.getaj.net/AJD/01.m3u8

**Comment by freearhey** [comment]
@muaztakrouri This is what I see on this link:
<img width="720" alt="Captura de pantalla 2020-06-13 a las 17 36 13" src="https://user-images.githubusercontent.com/7253922/84571544-8240a700-ad9c-11ea-971c-61d1e75b3552.png">
and after 40 seconds the broadcast is completely turned off.

**Comment by muaztakrouri** [comment]
@freearhey 

I've retested the link and still working but maybe the streaming is limited to certain regions,

**Tested Location:** Turkey

![image](https://user-images.githubusercontent.com/26604385/84571648-3b06e600-ad9d-11ea-8479-fd4cc4e7982d.png)

**Comment by freearhey** [comment]
@muaztakrouri You're probably right. But in this case we also cannot add it to the playlist because we do not add geoblocked broadcasts.
