### ISSUE TITLE
Add: qatar

### ISSUE THREAD

**Issue by Terolil** [iptv-org/iptv#15048]
### Channel ID (required)

AlJazeeraMubasher.qa

### Channel Name

Aljazeera mubashar (live)

### Stream URL (required)

https://live-hls-web-ajm.getaj.net/AJM/index.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dd1ba11dc97bbf677ed3e11d0664b0fef3751ab/streams/qa.m3u#L16-L17
