### ISSUE TITLE
Add: Canal 44 Chihuahua (Alternative ?)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15056]
### Channel ID (required)

XHICCHTDT.mx

### Channel Name

Canal 44 Chihuahua

### Stream URL (required)

https://5e50264bd6766.streamlock.net/canal442/videocanal442/playlist.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/dd07d8760e88bedd57602e996da8f3a09ce4ccb8/streams/mx.m3u#L44-L45
