### ISSUE TITLE
Add: jordan

### ISSUE THREAD

**Issue by Terolil** [iptv-org/iptv#15051]
### Channel ID (required)

AmmanTV.jo

### Channel Name

Amman TV

### Stream URL (required)

https://ammantv-live.ercdn.net/ammantvhd/ammantvhd.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dd1ba11dc97bbf677ed3e11d0664b0fef3751ab/streams/jo.m3u#L15-L16
