### ISSUE TITLE
Add: Saudi arabia

### ISSUE THREAD

**Issue by Terolil** [iptv-org/iptv#15052]
### Channel ID (required)

QuranTV.sa

### Channel Name

Makkah

### Stream URL (required)

https://edge.taghtia.com/sa/7.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/056e5d93fb161cf2a3439f1fd90cabe249b794e9/streams/sa.m3u#L10-L11
