### ISSUE TITLE
Broken: NHK G(576p/Tokyo 720p) NHK BS1, NHK BSP, NHK E

### ISSUE THREAD

**Issue by NERDINDIE** [iptv-org/iptv#15058]
### Broken Link

https://iptv-org.github.io/iptv/index.m3u

### What happened to the stream?

Not loading

### Notes (optional)

This also happens in the Japanese playlist as well.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
![image](https://github.com/iptv-org/iptv/assets/5430116/4d438eac-07ae-4f2f-8362-e7224847dba3)

**Comment by Dum4G** [comment]
https://github.com/luongz/iptv-jp

They ask "to not to steal" so I personally won't.

**Comment by FFSMNRK** [comment]
Odd, all the NHK links are working fine on my end. 

In any case, thanks for the alt, Dum4G :)
