### ISSUE TITLE
Broken: ythls

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#15059]
### Broken Link

https://github.com/iptv-org/iptv/blob/master/streams/us_ythls.m3u

### What happened to the stream?

Not loading

### Notes (optional)

@allanf181

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by allanf181** [comment]
I found the problem
![image](https://github.com/iptv-org/iptv/assets/14101716/24fe7a7f-6034-4b18-ad0b-841491c65bd1)

**Comment by allanf181** [comment]
Even over the limit they're still working, is there a specific channel that isn't working?

**Comment by Dum4G** [comment]
I tested with https://ythls.armelin.one/channel/UCVEaAWKfv7fE1c-ZuBs7TKQ.m3u8 and https://ythls.armelin.one/channel/UCFzJjgVicCtFxJ5B0P_ei8A.m3u8

2nd is indeed working now

**Comment by Dum4G** [comment]
Is there some kind of protection applied on your side? For the last few days I'm getting error 403 even for the channels that previously worked @allanf181

**Comment by allanf181** [comment]
It's probably geoblocked at the location you're accessing, or close to it, the check is done on the cloudflare server, you can find out the location at https://ythls.armelin.one/cdn-cgi/trace

**Comment by Dum4G** [comment]
every channel I tested is accesible from the YT itself. Does that matter?

**Comment by allanf181** [comment]
It should work then, because if you can access it where you are, you should be able to access it on the cloudflare server, unless the server has been redirected to another one in the region due to some problem, then there's not much you can do until the server comes back.
