### ISSUE TITLE
Add: jordan

### ISSUE THREAD

**Issue by Terolil** [iptv-org/iptv#15050]
### Channel ID (required)

JordanTV.jo

### Channel Name

Royal Jordan TV 

### Stream URL (required)

https://jrtv-live.ercdn.net/jordanhd/jordanhd.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dd1ba11dc97bbf677ed3e11d0664b0fef3751ab/streams/jo.m3u#L27-L28
