### ISSUE TITLE
Urban Revolution TV

### ISSUE THREAD

**Issue by ea5iva** [iptv-org/iptv#1505]
**Country of the channel:**
SPAIN

**Channel Name:**
URBAN REVOLUTION TV (shown in some IPTV Listings as uRV TV)

**Channel Language:**
SPANISH

**Additional Information (optional):**
WEB: www.urbanrevolution.es
STREAM: https://www.urbanrevolution.es:444/live/5e6d8470a3832/index.m3u8

LOGO: ![logourbanrevolution](https://user-images.githubusercontent.com/66835149/84512648-91562500-acc8-11ea-8f8a-c0d61d5b2600.png)

**Comment by freearhey** [comment]
Done.
