### ISSUE TITLE
Broken: MBC Bollywood

### ISSUE THREAD

**Issue by MysticBlueZ** [iptv-org/iptv#15066]
### Broken Link

https://shls-mbcdramaksa-ak.akamaized.net/out/v1/a79c9d7ef2a64a54a64d5c4567b3462a/index.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Geo-blocked

**Comment by MysticBlueZ** [comment]
Can it be added without Geo-blocked?

**Comment by Dum4G** [comment]
Give it a try
http://175.107.244.52:4457/play/a060/index.m3u8

**Comment by MysticBlueZ** [comment]
Yup it works. But it seems a bit laggy it dosen't have full screen

**Comment by MysticBlueZ** [comment]
Wait, is it done?

**Comment by Dum4G** [comment]
Did anything I can. There's no other source that is currently know and even my suggestion is not 24/7

**Comment by MysticBlueZ** [comment]
Oh. That's fair enough
