### ISSUE TITLE
Broken: ARY News

### ISSUE THREAD

**Issue by katarighe** [iptv-org/iptv#15064]
### Broken Link

https://ythls.armelin.one/channel/UCMmpLL2ucRHAXbNHiCPyIyg.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Recivied "ParserError: Expected" when accessing the channel.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Seems to work now.

**Comment by katarighe** [comment]
@BellezaEmporium When tuned in it says that I got UnrecognizedInputFornatExecption.

**Comment by BellezaEmporium** [comment]
> @BellezaEmporium When tuned in, it says that I got UnrecognizedInputFornatExecption.
> 
> I am using a streamer that is compatible with M3U playlists.

Maybe your player does not support redirections. The ythls server interrogates YouTube's API to retrieve the live manifest and then gives it back to the end user with a redirection to said content.

**Comment by Dum4G** [comment]
Tried returned stream and got this
![image](https://github.com/iptv-org/iptv/assets/5430116/15f53f5a-1965-45fd-8bef-f4421d0999c9)
However it works if I get to the YT page

**Comment by katarighe** [comment]
@Dum4G Yes, I can normally access the YT page of that stream, but the issue is that an error appears when accessing the stream.

**Comment by BellezaEmporium** [comment]
![image](https://github.com/iptv-org/iptv/assets/30985701/0004a7a9-d0fa-406a-a1ef-e0b8516fc6db)
Then I definitely don't know.
