### ISSUE TITLE
Add: Sport [KG]

### ISSUE THREAD

**Issue by gohoski** [iptv-org/iptv#15068]
### Channel ID (required)

Sport.kg

### Stream URL (required)

https://64e5ed58c00d4.streamlock.net/live/smil:sport.smil/playlist.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/dd07d8760e88bedd57602e996da8f3a09ce4ccb8/streams/kg.m3u#L14-L15

**Comment by gohoski** [comment]
> https://github.com/iptv-org/iptv/blob/dd07d8760e88bedd57602e996da8f3a09ce4ccb8/streams/kg.m3u#L14-L15

KTRKSport.kg has been deleted from the iptv-org/database because it was an old duplicate of Sport.kg. Please add this stream to Sport.kg
