### ISSUE TITLE
Toonami Aftermath East

### ISSUE THREAD

**Issue by TimeLion724** [iptv-org/iptv#15079]
### Describe your issue

Toonami Aftermath East has been removed from the animation playlist and replaced with Toonami Aftermath Movies, Can you please bring back Toonami Aftermath East!

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Toonami Aftermath East EST
http://api.toonamiaftermath.com:3000/est/playlist.m3u8

Toonami Aftermath West PST
http://api.toonamiaftermath.com:3000/pst/playlist.m3u8

Toonami Aftermath Movies
http://api.toonamiaftermath.com:3000/movies/playlist.m3u8

Toonami Aftermath Radio
http://api.toonamiaftermath.com:3000/radio/playlist.m3u8

Snickelodeon East EST
http://api.toonamiaftermath.com:3000/snick-est/playlist.m3u8

Snickelodeon West PST
http://api.toonamiaftermath.com:3000/snick-pst/playlist.m3u8

MTV 97
http://api.toonamiaftermath.com:3000/mtv97/playlist.m3u8

**Comment by TimeLion724** [comment]
Hey, those links do not work on the player I am using.

I am using Televizo Android App on my Google Chrome Cast

**Comment by BellezaEmporium** [comment]
https://asp1.toonamiaftermath.com/livehttporigin/est/xGljs0-hK0nSt-playlist.m3u8
https://asp6.toonamiaftermath.com/livehttporigin/movies/xGljs0-PPFNSt-playlist.m3u8
https://asp6.toonamiaftermath.com/livehttporigin/radio/xGljs0-TaFXce-playlist.m3u8
https://asp1.toonamiaftermath.com/livehttporigin/est/xGljs0-HCyNTs-playlist.m3u8?streamDelay=180
