### ISSUE TITLE
Add: Georgian Times TV [GE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#15088]
### Channel ID (required)

GeorgianTimesTV.ge

### Channel Name

Georgian Times TV

### Stream URL (required)

https://tbs01-edge11.itdc.ge/gttv/index.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Can't confirm edge11, however edge17 works

**Comment by Dum4G** [comment]
https://github.com/iptv-org/iptv/pull/15093/commits/39f8dac2dbdec3b335f9e25d901c015366253e43
