### ISSUE TITLE
Add: Meteo24.tv [GE] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#15089]
### Channel ID (required)

Meteo24tv.ge

### Channel Name

Meteo24.tv

### Stream URL (required)

https://tbs01-edge17.itdc.ge/smartnet/index.m3u8?chan=smartnet

### Quality

1080p

### Label

Not 24/7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
https://github.com/iptv-org/iptv/pull/15093/commits/7acda7f4381fa22d509800270024c1ea7fee8cdb
