### ISSUE TITLE
Add: CBC SPORT AZ

### ISSUE THREAD

**Issue by muradimanbayli** [iptv-org/iptv#15097]
### Channel ID (required)

CBCSport.az

### Channel Name

CBC Sport Az

### Stream URL (required)

https://mn-nl.mncdn.com/cbcsports_live/cbcsports/chunklist.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Cannot confirm this works, sadly. Will try with an Azerbaijan IP.

**Comment by royalclilov3-lang** [comment]
Salam hər vaxtınız xeyir olsun CBC SPORT HD İPTV ORGDA YOXDUR

**Comment by royalclilov3-lang** [comment]
> Salam hər vaxtınız xeyir olsun CBC SPORT HD 1080p × 10920 İPTV ORGDA YOXDUR
