### ISSUE TITLE
Add: CBS Mixible (ET)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15094]
### Channel ID (required)

Mixible.us

### Channel Name

Mixible

### Stream URL (required)

https://dai.google.com/linear/hls/event/xrVrJYTmTfitfXBQfeZByQ/master.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/cf830b68c6a5c5385a7fdc4494396244eb7a4330/streams/us_stirr.m3u#L52-L53
