### ISSUE TITLE
Edit: AZTV

### ISSUE THREAD

**Issue by muradimanbayli** [iptv-org/iptv#15096]
### Stream URL (required)

https://str.yodacdn.net/aztv/tracks-v1a1/mono.m3u8

### Channel ID

AzTV.az

### Channel Name

Az TV

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by muradimanbayli** [comment]
@freearhey why did you close the issue? the current link for AZ TV is not working, and the link which I share is working here is my prof 
<img width="624" alt="image" src="https://github.com/iptv-org/iptv/assets/4321030/3ee76f98-ef91-4e38-87b9-cf6a85246046">
<img width="1788" alt="image" src="https://github.com/iptv-org/iptv/assets/4321030/83e10700-23c1-4b3f-b57f-239d6d40324d">

**Comment by freearhey** [comment]
This form is created to edit the description of existing links. To add a new link to the playlist use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=streams%3Aadd&projects=&template=-----streams_add.yml&title=Add%3A+
