### ISSUE TITLE
Broken: Cartoon Network West TVE Feed (720p) [Geo-Blocked]

### ISSUE THREAD

**Issue by Metroid2023** [iptv-org/iptv#15107]
### Broken Link

https://turnerlive.warnermediacdn.com/hls/live/2023180/toonwest/slate/VIDEO_0_3564000.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

This stream has been broken since a week ago.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
If this one's broken, then maybe all of the Turner feeds are... x)

**Comment by Smark223** [comment]
Cartoon Network East still working for me. As are TNT, TBS, tru TV and adult swim West

**Comment by TKList** [comment]
Seems like only Toon West is not working. Strange
Does it work for anyone?

**Comment by Metroid2023** [comment]
Cartoon Network East is Working
Cartoon Network West Not Working
Adult Swim East is Working
Adult Swim West is Working
Thesis are the only one's that I know.
