### ISSUE TITLE
Add:new stream link into the playlist

### ISSUE THREAD

**Issue by msmid1711** [iptv-org/iptv#15117]
### Channel ID (required)

PBSKidsEasternCentral.us

### Channel Name

PBS Kids Eastern/Central

### Stream URL (required)

https://2-fss-2.streamhoster.com/pl_140/amlst:200914-1298290/playlist.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/111fd65fe9bc0e1cec9b20c893f91534d544f087/streams/us_pbs.m3u#L18-L19
