### ISSUE TITLE
Kurdish/iraq Channel Request

### ISSUE THREAD

**Issue by hawrazsabr** [iptv-org/iptv#1511]
**Country of the channel:**
Iraq

**Channel Name:**
Iraqia Kurdish
WAAR TV HD
Korek TV
NRT TV HD
Kurdsat News HD
Ava Media TV
Kurd Channel TV
NRT 4

**Channel Language:**
Kurdish

**Additional Information (optional):**
Please add these channels.🤗

**Comment by freearhey** [comment]
Duplicate #1498
