### ISSUE TITLE
Broken: PBS Kids Eastern/Central

### ISSUE THREAD

**Issue by msmid1711** [iptv-org/iptv#15118]
### Broken Link

https://livestream.pbskids.org/out/v1/1e3d77b418ad4a819b3f4c80ac0373b5/est.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by what-a** [comment]
Unfortunately, all PBS Kids dedicated streams are currently down:
PBS Kids Alaska (1080p)
PBS Kids Eastern/Central (1080p)
PBS Kids Hawaii (1080p)
PBS Kids Mountain (1080p)
PBS Kids Pacific (1080p)
