### ISSUE TITLE
Add: SSC 1 Saudi Arabia 

### ISSUE THREAD

**Issue by Goldiefresh** [iptv-org/iptv#15120]
### Channel ID (required)

SSC1HD.sa

### Channel Name

SSC 1 

### Stream URL (required)

https://af.ayassport.ir/hls2/ssc1.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Nod3820** [comment]
not working

**Comment by Acengrays** [comment]
Not working😭

**Comment by Goldiefresh** [comment]
This playlist of publicly available free sports channels has the free to air channels SSC 1, SSC 4, and SSC extra

https://bit.ly/3Qj2eLD
