### ISSUE TITLE
Add: UTRK [KG]

### ISSUE THREAD

**Issue by gohoski** [iptv-org/iptv#15148]
### Channel ID (required)

UTRK.kg

### Channel Name

УТРК

### Stream URL (required)

https://st2.mediabay.tv/KG_KTRK-UTRK/index.m3u8

### Quality

480p

### Label

Not 24/7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
https://st2.mediabay.tv/KG_KTRK-UTRK/index.m3u8 ?

Wonder if it takes info from there...

**Comment by gohoski** [comment]
> https://st2.mediabay.tv/KG_KTRK-UTRK/index.m3u8 ?
> 
> Wonder if it takes info from there...

OH sorry, didn't realise there was a stream that doesn't require a token. Changed it
