### ISSUE TITLE
Add: FNX - First Nations Experience

### ISSUE THREAD

**Issue by Metroid2023** [iptv-org/iptv#15146]
### Channel ID (required)

KVCRDT2.us

### Channel Name

FNX

### Stream URL (required)

https://castus-vod-dev.s3.amazonaws.com/vod_clients/kvcr/live/ch1/video.m3u8

### Quality

None

### Label

Geo-blocked

### HTTP Referrer

https://fnx.org/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
FNX.us should be KVCRDT2.us

**Comment by Metroid2023** [comment]
I changed it.
