### ISSUE TITLE
Add: SNN TV

### ISSUE THREAD

**Issue by katarighe** [iptv-org/iptv#15142]
### Channel ID (required)

SNNTV.ir

### Channel Name

SNN TV

### Stream URL (required)

https://live2.snn.ir/hls/snn.m3u8

### Quality

480p

### Label

Not 24/7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Not 24/7 ?

**Comment by katarighe** [comment]
@BellezaEmporium I think 24/7

**Comment by BellezaEmporium** [comment]
> @BellezaEmporium I think 24/7

Didn't seem to work at night for me. (404 Not Found)

**Comment by katarighe** [comment]
@BellezaEmporium What should I do right now.

I will try to investigate this matter. 

If this can not be solved , I guess you can close this as not planned.

**Comment by BellezaEmporium** [comment]
> @BellezaEmporium What should I do right now.
> 
> I will try to investigate this matter further. 
> 
> If this can not be solved , I guess you can close this as not planned. 

I'll do the necessary.

**Comment by katarighe** [comment]
@BellezaEmporium OK, that is the offical link that I retrieved from their website.

**Comment by katarighe** [comment]
@BellezaEmporium OK, that is the offical link that I retrieved from their website.
