### ISSUE TITLE
Bug in streams/it.m3u

### ISSUE THREAD

**Issue by Tamburasca** [iptv-org/iptv#15152]
### Describe your issue

There seems to be an erroneous record in https://github.com/iptv-org/iptv/blob/master/streams/it.m3u
Python module ipytv is not capable to read it, likely owing to this line

#EXTINF:-1 tvg-id="",TV UNO (240p)
http://ftp.tiscali.it/francescovernata/TVUNO/monoscopioTvUNOint-1.wmv
?

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/iptv/issues/15177
