### ISSUE TITLE
Add: Pars TV

### ISSUE THREAD

**Issue by katarighe** [iptv-org/iptv#15158]
### Channel ID (required)

ParsTV.ir

### Channel Name

Pars TV

### Stream URL (required)

https://livestream.5centscdn.com/parstvbkup/a442df07ca95af01bed2009df48bca5c.sdp/playlist.m3u8?md5=WOD667bo6lUOjMCSwFxJXA&expires=1700917558

### Quality

720p

### Label

Not 24/7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://livestream.5centscdn.com/parstvbkup/a442df07ca95af01bed2009df48bca5c.sdp/playlist.m3u8?md5=WOD667bo6lUOjMCSwFxJXA&expires=1700917558 (offline)
<img width="831" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/cd9a2796-3c6a-466f-9ed6-9370c8ad6861">
