### ISSUE TITLE
Add New Language Category: Malayalam

### ISSUE THREAD

**Issue by surjithctly** [iptv-org/iptv#1515]
I see many Malayalam language channels in this list. I would love to see a category for this language. 

**List of Free Malayalam Channels:** 

- Amrita
- Asianet News
- DD Malayalam
- Flowers TV
- JaiHind
- Janam
- Kappa
- Kairali
- Kairali News
- Kaumudy
- Kerala Vision
- Mangalam
- Manorama News
- Mathrubhumi News
- Mazhavil Manorama
- Media One
- Reporter
- Safari
- Twenty Four
- Victers
- We

**Comment by freearhey** [comment]
Playlists for all languages are generated automatically based on the channel description and currently channels from this list have a different language (mainly Hindi). 

But if you think the description contains an error, you can fix it yourself. Just read this guide before  you do: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#sort-channels-by-language

**Comment by surjithctly** [comment]
Okay. Created a pull request #1517

**Comment by freearhey** [comment]
Done.
