### ISSUE TITLE
Dashes and internal playlists

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#15156]
### Describe your issue

Either check is misbehaving or some unwanted edition was approved
https://github.com/iptv-org/iptv/actions/runs/6992148929/job/19023422878#step:9:12

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
Fixed.

The dash was in the name of the channel in https://github.com/iptv-org/iptv/issues/15146
