### ISSUE TITLE
Add: Pars TV

### ISSUE THREAD

**Issue by katarighe** [iptv-org/iptv#15173]
### Channel ID (required)

ParsTV.ir

### Channel Name

Pars TV

### Stream URL (required)

https://livestream.5centscdn.com/parstvbkup/a442df07ca95af01bed2009df48bca5c.sdp/playlist.m3u8

### Quality

720p

### Label

None

### Notes

Updated the latest stream.
In case of any difficulties, please go to: https://parstv.tv/golive/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
403
