### ISSUE TITLE
Edit: Hala London

### ISSUE THREAD

**Issue by katarighe** [iptv-org/iptv#15172]
### Stream URL (required)

https://halaldn.cdn.mangomolo.com/halavd/smil:halavd.stream.smil/playlist.m3u8

### Channel ID

HalaLondon.uk

### Channel Name

Hala London

### Quality

720p

### Label

None

### Notes

New stream link: 'https://halalondon-live.ercdn.net/halalondon/halalondon.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
To add a new link to a playlist please use this form: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=streams%3Aadd&projects=&template=-----streams_add.yml&title=Add%3A+
