### ISSUE TITLE
I try to play with VLC player，How to set up different channels?

### ISSUE THREAD

**Issue by bbhxwl** [iptv-org/iptv#1518]
How to set up different channels?

I use VLC to enter the following URL, only 1 channel, CCTV1

https://iptv-org.github.io/iptv/languages/cmn.m3u

**Comment by SileC** [comment]
there are 176 channels 
Link to some players https://github.com/iptv-org/awesome-iptv

**Comment by freearhey** [comment]
It's weird, my VLC shows all the channels:
<img width="720" alt="Captura de pantalla 2020-06-16 a las 13 32 46" src="https://user-images.githubusercontent.com/7253922/84764286-23ff0880-afd6-11ea-9a5a-3024645c1455.png">
But as it was written above, you can use any of other players that support IPTV playlists.
