### ISSUE TITLE
Add: Kerala Vision News 

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#15186]
### Channel ID (required)

KeralaVisionNews.in

### Channel Name

Kerala Vision News

### Stream URL (required)

https://www.youtube.com/channel/UCuo69XR8nCP4Ss8ko_5Xbuw

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/e6aa75fa82663bee59008c39b2fdbb22a4eb0cb6/streams/us_ythls.m3u#L640-L641
