### ISSUE TITLE
Fix JOTX-DTV

### ISSUE THREAD

**Issue by solo489** [iptv-org/iptv#15190]
### Describe your issue

http://203.162.235.41:19098

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Isn't broken
![image](https://github.com/iptv-org/iptv/assets/5430116/41a8d34b-21a0-4a72-9d0d-7fa2cdb85164)
