### ISSUE TITLE
Some mistakes in Japanese channels

### ISSUE THREAD

**Issue by Yonagi04** [iptv-org/iptv#15206]
### Describe your issue

The title of channels don't match the program on channel. For example, a channel's title is "TBS(720p)", but it is TV Asahi.
And other Japanese channels has this problem.
<img width="1280" alt="image" src="https://github.com/iptv-org/iptv/assets/124041066/7698d871-89f6-43d5-a3c3-ab886e95d65b">

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Feel free to contribute your fixes according to our https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md
