### ISSUE TITLE
Broken: Most of Japanese streams

### ISSUE THREAD

**Issue by DimitarCC** [iptv-org/iptv#15203]
### Broken Link

http://203.162.235.41:24103

### What happened to the stream?

Not loading

### Notes (optional)

Most of the japanese streams are broken since they redirect to 203.162.235.41 which seems no longer available.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
It's just way to far away from regions outside of Asia to load

![image](https://github.com/iptv-org/iptv/assets/5430116/b2bc33ef-7801-4487-a022-a2bf66f7caa9)

**Comment by DimitarCC** [comment]
It was working last week and now not...
So its a different problem that arise recently 😉

**Comment by Dum4G** [comment]
Unfortunately we can't guarantee 24/7 availability of streams provided in every country across the globe. If you know any alternative source that is suitable for the playlist feel free to contribute your fixes according to our [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)
