### ISSUE TITLE
Add: MV Lao TV

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#15213]
### Channel ID (required)

MVLaoTV.la

### Stream URL (required)

https://edge6a.v2h-cdn.com/mvlao/mvlao.stream/playlist.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Very long wait time but works.
