### ISSUE TITLE
Broken: GEM TV (576p)

### ISSUE THREAD

**Issue by chrizkayriko** [iptv-org/iptv#15210]
It seems, that GEM TV doesn't work anymore, is there any way to fix it?

**Comment by Jitterdoomer** [comment]
https://github.com/iptv-org/iptv/issues/9364
Please refer to that link. That channel was a leftover from the Dens.TV stream. The other GEM (not to be confused with the Persian channel) was also dead and Geo-blocked outside of Hong Kong.
