### ISSUE TITLE
Broken: Many Indonesia Channel was Broken in Via VLC 

### ISSUE THREAD

**Issue by Arya165** [iptv-org/iptv#15226]
### Broken Link

https://iptv-org.github.io/iptv/countries/id.m3u

### What happened to the stream?

Other

### Notes (optional)

Many Indonesian channels are damaged and difficult to access via VLC, such as SCTV, Indosiar, ANTV, TVOne, my favorite Net TV, and many more.
![Screenshot (6)](https://github.com/iptv-org/iptv/assets/152945593/2dc1c094-1d5b-4043-ac44-d2ed0b97aa16)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by aditaufik1978-eng** [comment]
https://github.com/iptv-org/iptv/issues/15226#issue-2025235980

**Comment by aditaufik1978-eng** [comment]
https://github.com/iptv-org/iptv/issues/15226#issue-2025235980
