### ISSUE TITLE
Broken: NET, ANTV, METRO TV, SCTV, Indosiar Not working Syalalalala 😊

### ISSUE THREAD

**Issue by Arya165** [iptv-org/iptv#15225]
### Broken Link

https://iptv-org.github.io/iptv/countries/id.m3u

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://ythls.armelin.one/channel/UC1-ATnDVEwKT6-0aEeJ2ibA.m3u8
<img width="788" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/da4f24e0-931b-4324-a9d6-fbb163a9c448">

https://ythls.armelin.one/channel/UCzl0OrB3-ehunyotIQvK77A.m3u8
<img width="783" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/24bb0ccd-ff75-4a17-b981-ff6a637e80fb">

**Comment by Arya165** [comment]
ANTV, SCTV And Indosiar have still Link Broken Streaming Bro 😁

**Comment by q-onkbalaph175** [comment]
request indonesia
