### ISSUE TITLE
Add: NHK BSP4K

### ISSUE THREAD

**Issue by ZXArkin** [iptv-org/iptv#15247]
### Channel ID (required)

NHKBSP4K.jp

### Channel Name

NHK BSP4K

### Stream URL (required)

http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=bs01&isp=10&bind=0&uin=159413&playseek=0

### Quality

1080p

### Label

None

### Notes

NHK BSP4K (aka NHK BS Premium)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Stevyb** [comment]
This stream is not working anymore (NHK BSP4K)
