### ISSUE TITLE
Rotana Channels

### ISSUE THREAD

**Issue by A-S-H-E-E** [iptv-org/iptv#15259]
### Describe your issue

All the channels who start with the name Rotana don’t work.
Can you resolve it please ?

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by A-S-H-E-E** [comment]
I used a VPN and it's worked, is it possible to work without VPN ?

**Comment by freearhey** [comment]
Works without any VPN:
https://github.com/iptv-org/iptv/blob/f26adbe07a4371eb1592534b0461992e6def9899/streams/sa.m3u#L100-L101
<img width="1387" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/4da44c84-84fc-45cc-a34b-8d6a4014f55d">

**Comment by A-S-H-E-E** [comment]
> Works without any VPN:
> 
> https://github.com/iptv-org/iptv/blob/f26adbe07a4371eb1592534b0461992e6def9899/streams/sa.m3u#L100-L101
> 
> <img width="1387" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/4da44c84-84fc-45cc-a34b-8d6a4014f55d">

I'm currently in France and whithout a VPN it doesn't work 
![image](https://github.com/iptv-org/iptv/assets/117389791/4218711a-5e40-44fb-a152-ffb20a44e04c) ![image](https://github.com/iptv-org/iptv/assets/117389791/2cd94f10-f130-4973-9f65-08c67a15d026)
