### ISSUE TITLE
Add: Alpha TV Cyprus

### ISSUE THREAD

**Issue by euangeliakaphale** [iptv-org/iptv#15257]
### Channel ID (required)

AlphaTVCyprus.cy

### Channel Name

Alpha TV Cyprus

### Stream URL (required)

http://l4.cloudskep.com/alphatmp/acy/playlist.m3u8

### Quality

720p

### Label

Geo-blocked

### HTTP User Agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 Edge/12.246 HTTP Referrer

### HTTP Referrer

http://player.cloudskep.com/alphatmp/alphacy

### Notes

The channel is back live.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
http://l4.cloudskep.com/alphatmp/acy/playlist.m3u8
