### ISSUE TITLE
Broken: Reelz Channel | (US) No longer works

### ISSUE THREAD

**Issue by tobycth3** [iptv-org/iptv#15260]
No longer works

_Originally posted by @TKList in https://github.com/iptv-org/iptv/issues/7664#issuecomment-1590472427_

**Comment by freearhey** [comment]
https://bcovlive-a.akamaihd.net/c733a9aa448a4a44a10c527c6f5bf7a4/us-east-1/5245389775001/playlist.m3u8
<img width="1397" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/c3484cfe-9584-4c97-aa37-82eee34e3c1a">

**Comment by tobycth3** [comment]
That URL doesn't actually work, it just plays the same 17 second clip in a loop

**Comment by R4IN2007** [comment]
Link looks like it expired

**Comment by DPressedNotBothered** [comment]
Is there any chance for an updated working link? TIA

**Comment by industrystandard1** [comment]
Can confirm, no longer works, it is of the utmost importance that a replacement comes along.
