### ISSUE TITLE
Add: Kanal 7 Baltics (Latvia)

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/iptv#15305]
### Channel ID (required)

Kanal7Baltics.lv

### Channel Name

Kanal 7 Baltics (Latvia)

### Stream URL (required)

http://89.254.128.5:22280/duo7_hd/index.m3u8

### Quality

1080p

### Label

None

### HTTP Referrer

http://89.254.128.5:22280/

### Notes

And need remove this stream in id:Kanal7.ee, because is not a same.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
Closed in favor of #15337
