### ISSUE TITLE
Add: ProSieben [DE]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/iptv#15301]
### Channel ID (required)

ProSieben.de

### Channel Name

ProSieben

### Stream URL (required)

http://85.187.13.40:18000/ProSieben

### Quality

576p

### Label

None

### HTTP Referrer

http://85.187.13.40:18000/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by DJ1999-max** [comment]
Is working and is not a fake.

**Comment by Felix1710** [comment]
can you find other channels too?
