### ISSUE TITLE
Add: Cartoon Network Scandinavia

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/iptv#15300]
### Channel ID (required)

CartoonNetworkScandinavia.uk

### Channel Name

Cartoon Network

### Stream URL (required)

http://89.254.128.5:22280/cartoon_network/index.m3u8

### Quality

576p

### Label

None

### HTTP Referrer

http://89.254.128.5:22280/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by dantheman121** [comment]
doesn't work keeps loading

**Comment by DJ1999-max** [comment]
> doesn't work keeps loading

You using VPN.

**Comment by Plus018** [comment]
Welp

**Comment by M3UDay** [comment]
> > doesn't work keeps loading
> 
> You using VPN.

It won't open even though I don't use VPN

**Comment by M3UDay** [comment]
> > doesn't work keeps loading
> 
> You using VPN.

It won't open even though I don't use VPN

**Comment by jyle635** [comment]
> > > doesn't work keeps loading
> > 
> > 
> > You using VPN.
> 
> It won't open even though I don't use VPN

Why do you need to vpn?

**Comment by jyle635** [comment]
I'm getting a error that it takes a little too long to respond and i do not have vpn Turned on
