### ISSUE TITLE
Broken: BS TBS

### ISSUE THREAD

**Issue by pavlikmac** [iptv-org/iptv#15325]
### Broken Link

http://203.162.235.41:26105

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Appears to be [working](https://streamtest.in/logs/http-203-162-235-41-26105-729e5495-fe4b-45a6-beba-b38100f982ea).
