### ISSUE TITLE
Add: IRIB Omid

### ISSUE THREAD

**Issue by katarighe** [iptv-org/iptv#15320]
### Channel ID (required)

IRIBOmid.ir

### Channel Name

IRIB Omid

### Stream URL (required)

https://lb-cdn.sepehrtv.ir/securelive3/omidsd/omidsd.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Tokenized 403
