### ISSUE TITLE
Add: IRIB UHD

### ISSUE THREAD

**Issue by katarighe** [iptv-org/iptv#15321]
### Channel ID (required)

IRIBUHD.ir

### Channel Name

IRIB UHD

### Stream URL (required)

https://lb-cdn.sepehrtv.ir/securelive3/uhd/uhd.m3u8

### Quality

2160p

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Tokenized 403
