### ISSUE TITLE
Add: Polsat News

### ISSUE THREAD

**Issue by TestNintendo** [iptv-org/iptv#15331]
### Channel ID (required)

PolsatNews.pl

### Channel Name

Polsat News

### Stream URL (required)

https://cdn-main.lolokoko.tv/PolsatNews.stream/playlist.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by marry92** [comment]
Hey, where to find more links from lolokoko.tv? I see it's a great provider, e.g. links to Eleven Sports PL (1,2,3,4) would be great. Cheers.

**Comment by TestNintendo** [comment]
Hello!
Unfortunately you have to type the channel name manually. The format is: "ChannelName.stream".
For example, if you want to watch TVN, but the link looks like this:
https://cdn-main.lolokoko.tv/PolsatNews.stream/playlist.m3u8
you have to replace "PolsatNews.stream" with "TVN.stream".
This works on Polish TV channels only.
Enjoy!

**Comment by marry92** [comment]
Hello, thanks for the reply! Sadly  some channes cannot be found by this approach (e.g. Eleven Sports). If someone has the links for it, would be awesome to share with us.

**Comment by NagraniaTelewizji** [comment]
Hello, TestNintendo, Where is 4FUN TV lolokoko tv links
