### ISSUE TITLE
Add: IFC | (US)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15349]
### Channel ID (required)

IFCEast.us

### Channel Name

IFC East

### Stream URL (required)

https://bcovlive-a.akamaihd.net/7304338dca7a4c91b8f0504de0342687/us-east-1/6240731308001/playlist.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by spotanjo3** [comment]
It works fine. Thank you!

**Comment by spotanjo3** [comment]
Its dead now.

**Comment by hijuuijj** [comment]
> ### Channel ID (required)
> IFCEast.us
> 
> ### Channel Name
> IFC East
> 
> ### Stream URL (required)
> https://bcovlive-a.akamaihd.net/7304338dca7a4c91b8f0504de0342687/us-east-1/6240731308001/playlist.m3u8
> 
> ### Quality
> 1080p
> 
> ### Label
> None
> 
> ### Timeshift
> _No response_
> 
> ### HTTP User Agent
> _No response_
> 
> ### HTTP Referrer
> _No response_
> 
> ### Notes
> _No response_
> 
> ### Contributing Guide
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

Any working IFC link?

**Comment by hijuuijj** [comment]
> IFCEast.us
> https://bcovlive-a.akamaihd.net/7304338dca7a4c91b8f0504de0342687/us-east-1/6240731308001/playlist.m3u8

Any working IFC link?

**Comment by R4IN2007** [comment]
Link changes.

**Comment by hijuuijj** [comment]
> Link changes.

I know, that's why I'm asking if you know the new link, but I assume you don't.
