### ISSUE TITLE
Add: AstraMarket(shop)

### ISSUE THREAD

**Issue by ilias2024k** [iptv-org/iptv#15353]
### Channel ID (required)

.

### Channel Name

AstraMarket

### Stream URL (required)

https://eu1.vectromdigital.com:1936/astramarket/astramarket/playlist.m3u8

### Quality

480p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ilias2024k** [comment]
@Dum4G the channel hasnt got an id.

**Comment by Dum4G** [comment]
> @Dum4G the channel hasnt got an id.

You should provide as much info as you can by using a strict template and following our [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#contributing-guide). The process is semi-automated in both database and main repos
