### ISSUE TITLE
Add: Pax TV

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#15367]
### Channel ID (required)

PaxTV.pe

### Channel Name

Pax TV

### Stream URL (required)

http://vivo.paxtvmovil.org/out/v1/6657a374459f4821b404e16161c98588/playlist_768x432_1200k.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
http://vivo.paxtvmovil.org/out/v1/6657a374459f4821b404e16161c98588/playlist_768x432_1200k.m3u8 (offline)
<img width="725" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/fa1550c5-0489-42d3-b4ae-576a7572b50e">
