### ISSUE TITLE
Add: Hatun TV

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#15360]
### Channel ID (required)

HatunTV.pe

### Channel Name

Hatun TV

### Stream URL (required)

https://mi.godo.net.pe/Best00Hatum-0032101002/tracks-v1a1/mono.m3u8?remote=190.64.92.146&token=43f579418469b06d9ecfa8b5b6d86b052f9401af-d3735fb03e62aae2da5132ee4238c778-1702933460-1702922660

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://mi.godo.net.pe/Best00Hatum-0032101002/tracks-v1a1/mono.m3u8?remote=190.64.92.146&token=43f579418469b06d9ecfa8b5b6d86b052f9401af-d3735fb03e62aae2da5132ee4238c778-1702933460-1702922660 (offline)
<img width="829" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/bd131732-6f94-4c37-a1d2-7ffd18f9eb38">
