### ISSUE TITLE
Add: Best Cable Mas Cumbia

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#15361]
### Channel ID (required)

BestCableMasCumbia.pe

### Channel Name

Best Cable Mas Cumbia

### Stream URL (required)

https://mi.godo.net.pe/best-MasCum-0102210011/tracks-v1a1/mono.m3u8?remote=190.64.92.146&token=4f0d78cc628e19bbd5d5628e0c94b2deb6733b1a-5e40e1f478c56c9940f48fd405a21558-1702933407-1702922607

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by JustSammyV** [comment]
![image](https://github.com/iptv-org/iptv/assets/137475335/567c75f8-70cc-478c-b878-21ef199713d7)
geo-blocked (chile)

**Comment by BellezaEmporium** [comment]
Here's what I have : 

Best Cable Hatun : https://tv.inka.net.pe/bestcablehatuntv/index.m3u8
Best Cable Music : https://tv.inka.net.pe/bestcablemusic/index.m3u8

**Comment by BellezaEmporium** [comment]
@sguinetti does https://dattassd.com/player/index.php?puerto=19360&rtmp=mascumbiatvonline&stream=mascumbiatvonline works for you ? I get a "timed out".

**Comment by JustSammyV** [comment]
> does https://dattassd.com/player/index.php?puerto=19360&rtmp=mascumbiatvonline&stream=mascumbiatvonline works for you ? I get a "timed out".

works for me. 
![image](https://github.com/iptv-org/iptv/assets/137475335/32b18848-8c36-4c15-8fe1-f2a5fceebf7b)

**Comment by BellezaEmporium** [comment]
Interesting, then maybe it blocks my browser or country.

**Comment by JustSammyV** [comment]
> Interesting, then maybe it blocks my browser or country.
> 
> EDIT : Works using a VPN set to Chile... Odd.

best guess is that it's blocked to LATAM-only.

**Comment by freearhey** [comment]
https://mi.godo.net.pe/best-MasCum-0102210011/tracks-v1a1/mono.m3u8?remote=190.64.92.146&token=4f0d78cc628e19bbd5d5628e0c94b2deb6733b1a-5e40e1f478c56c9940f48fd405a21558-1702933407-1702922607 (offline)
<img width="833" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/16ec5f1d-b1dc-4a7f-9ae2-e1da87bc0d29">

**Comment by sguinetti** [comment]
> https://dattassd.com/player/index.php?puerto=19360&rtmp=mascumbiatvonline&stream=mascumbiatvonline

This stream don't works for me. CORS error.
