### ISSUE TITLE
Add: Gaunda Punjab TV

### ISSUE THREAD

**Issue by katarighe** [iptv-org/iptv#15371]
### Channel ID (required)

GaundaPunjabTV.in

### Channel Name

Gaunda Punjab TV

### Stream URL (required)

http://start.agmediachandigarh.com/gaundapunjab/tv/playlist.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Already Exists:
https://github.com/iptv-org/iptv/blob/0ad2ff2f25785f32dde3aea3dbbbfbe3e742f073/streams/ca.m3u#L12-L13
