### ISSUE TITLE
Add: Polsat News 2

### ISSUE THREAD

**Issue by DenysMath** [iptv-org/iptv#15380]
### Channel ID (required)

PolsatNews2.pl

### Channel Name

Polsat News 2

### Stream URL (required)

https://cdn-main.lolokoko.tv/PolsatNews2.stream/playlist.m3u8

### Quality

576p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by marry92** [comment]
Hey, where to find more links from lolokoko.tv? I see it's a great provider. E.g. links to Eleven Sports PL (1,2,3,4) would be great. Cheers.
