### ISSUE TITLE
希望添加这三个邯郸频道

### ISSUE THREAD

**Issue by imlaoyou2333** [iptv-org/iptv#1539]
country : CHINA
lang : ZH-CN      CN
NAME  邯郸新闻综合
http://live.hd.hdbs.cn/video/s10001-hdxwpd/index.m3u8
NAME 邯郸公共
http://live.hd.hdbs.cn/video/s10001-hdggpd/index.m3u8
NAME 邯郸科技教育
http://live.hd.hdbs.cn/video/s10001-hdkjpd/index.m3u8

**Comment by freearhey** [comment]
Added.
