### ISSUE TITLE
Add: AXN(Indonesia)

### ISSUE THREAD

**Issue by antosatriani** [iptv-org/iptv#15422]
### Channel ID (required)

AXN.id

### Channel Name

AXN (Indonesia)

### Stream URL (required)

http://vod.linknetott.swiftcontent.com/Content/HLS/Live/Channel%28ch332%29/index.m3u8

### Quality

720p

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
@antosatriani would you be kind to share us a screenshot of those streams playing for you?

**Comment by antosatriani** [comment]
Of course.. this is a screenshot from  my player. And also work fine to other iptv stream from vod.linknetott.swiftcontent.com
![Screenshot_2024-01-07-13-06-16-38_df198e732186825c8df26e3c5a10d7cd](https://github.com/iptv-org/iptv/assets/134463236/c26de2ac-ffd3-4abb-b241-2982dd888050)
