### ISSUE TITLE
Add: Radio Lola

### ISSUE THREAD

**Issue by Sanzerz** [iptv-org/iptv#15420]
### Channel ID (required)

RadioLolaTV.rs

### Channel Name

Radio Lola

### Stream URL (required)

https://peer2.tdiradio.com/static/streaming-playlists/hls/7c3ea8d3-49dc-4e1b-8b1e-dc6fab71f5cf/0.m3u8

### Quality

720p

### Label

Not 24/7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://peer2.tdiradio.com/static/streaming-playlists/hls/7c3ea8d3-49dc-4e1b-8b1e-dc6fab71f5cf/0.m3u8 (offline)
<img width="729" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/457b8531-5ff1-4b45-ac69-873d90db153a">

**Comment by Dum4G** [comment]
![image](https://github.com/iptv-org/iptv/assets/5430116/90c879ac-861b-4978-b426-9eeaec498f7e)
not 24/7

**Comment by Dum4G** [comment]
![Uploading image.png…]()
not 24/7
