### ISSUE TITLE
Broken: WUSA 9, CBS 9

### ISSUE THREAD

**Issue by PIRATKING** [iptv-org/iptv#15442]
### Broken Link

https://livevideo01.wusa9.com/hls/live/2015498/newscasts/live.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Fails to load in vlc or other iptv clients

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by clips519** [comment]
https://video.tegnaone.com/live/wusa/v1/manifest/f9c1bf9ffd6ac86b6173a7c169ff6e3f4efbd693/WUSA-2/6f4e4256-1dc5-426e-817d-aa49223536ea/3.m3u8
