### ISSUE TITLE
Add: NickToons Turkey 

### ISSUE THREAD

**Issue by xekcxekc** [iptv-org/iptv#15446]
### Channel ID (required)

Nicktoons.tr

### Channel Name

NickToons Turkey

### Stream URL (required)

http://12.troya.one:34000/ch2484/mono.m3u8?token=xekec.wGWRcUA-X8M8KuIndfmxbQlVmEPQI5-Ush-dDjk_BPiZzRQ-eek0GE2tExu3KotP

### Quality

576p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Is it a stream that belongs to you ? User and token beginning looks similar.

Thing is, if the token changes, it's going to be hard to keep up with.
