### ISSUE TITLE
Broken: Korean Central Television (KCTV) (576p)

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#15445]
### Broken Link

https://tv.nknews.org/tvdash/stream.mpd

### What happened to the stream?

Not loading

### Notes (optional)

Hey, guys! I found the livestream link for Korean Central Television (KCTV) (576p) is currently dead but of course this is due to the link was full of bugs and glitches as well as both the audio and video was not sync together for strange reasons. I hope someone will repair it along with the widescreen version of the said North Korean channel too. 

Here's the images of KCTV which contains glitchy images and the logo too.

![Logo_of_the_Korean_Central_Television](https://github.com/iptv-org/iptv/assets/143818591/4a6a7f99-4c86-48c1-a2b5-41a01f96874d)
![vlcsnap-2023-12-05-18h07m41s446](https://github.com/iptv-org/iptv/assets/143818591/73513cf3-0d89-4b94-99bd-80c2b1307570)
![vlcsnap-2023-12-05-07h36m32s666](https://github.com/iptv-org/iptv/assets/143818591/e82b8dc8-c6ef-453d-8730-f502aafe6f29)
![vlcsnap-2023-12-05-07h36m58s211](https://github.com/iptv-org/iptv/assets/143818591/94aaaa4b-ff25-4e49-9d05-ca79e4b1c758)
![vlcsnap-2023-12-05-07h37m06s406](https://github.com/iptv-org/iptv/assets/143818591/0b4687a8-bcb8-4370-81ef-ff7df1903e23)
![vlcsnap-2023-12-05-07h37m24s932](https://github.com/iptv-org/iptv/assets/143818591/c0a5f372-a61b-4e46-b6a3-05af117bb71c)
![vlcsnap-2023-12-05-07h37m29s044](https://github.com/iptv-org/iptv/assets/143818591/8622f627-aefe-4328-9baa-7839b2d32967)
![vlcsnap-2023-12-06-07h39m50s584](https://github.com/iptv-org/iptv/assets/143818591/803ea4ee-f465-4ec7-801c-9f06ca63c865)
![vlcsnap-2023-12-08-18h00m16s929](https://github.com/iptv-org/iptv/assets/143818591/e59e7f1a-9c9f-44d6-a3a0-6a75e34520f3)
![vlcsnap-2023-12-11-18h01m26s340](https://github.com/iptv-org/iptv/assets/143818591/9330f5e6-9a41-4bfb-ba64-c651b0ccce8e)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by AVGCFan1995** [comment]
> Works perfectly fine on my side. Maybe a satellite transmission issue.
> 
> ![image](https://private-user-images.githubusercontent.com/30985701/293369072-139e8c70-0e9f-4ac6-a018-4ea83bb73454.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NzkwNzIsIm5iZiI6MTcwMzg3ODc3MiwicGF0aCI6Ii8zMDk4NTcwMS8yOTMzNjkwNzItMTM5ZThjNzAtMGU5Zi00YWM2LWEwMTgtNGVhODNiYjczNDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDE5MzkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMDViNjZjOWUwYzk1Y2FkZGRhM2ViNTAxMWQ5NDE4ODg5ZWU1MGFhNWM4NjA1NDhjOTc3Y2EyNzc0MTc5ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aqzJ_zbSwmM3zOArVVvu-OZ8_NGM1c0AYCXr39qlRbY) ![image](https://private-user-images.githubusercontent.com/30985701/293369106-7f836710-a08e-4eb5-9352-075a0086f28e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NzkwNzIsIm5iZiI6MTcwMzg3ODc3MiwicGF0aCI6Ii8zMDk4NTcwMS8yOTMzNjkxMDYtN2Y4MzY3MTAtYTA4ZS00ZWI1LTkzNTItMDc1YTAwODZmMjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDE5MzkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMTU1MDYzNDY4OGQ3NTBmMGJjNjU4Mzk0NTIxOGQ0OTczNzZkZGEzMzZlZjVhZjE2ZDUyMGZmZTVlYjdlYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D2g2kqAQeqbtpFSOac9KBzkI8rvP9IIc5_Xvp9RUmUU)

But there's the problem because it's not working on VLC media player anymore.

**Comment by BellezaEmporium** [comment]
Need to add an specific user-agent.
