### ISSUE TITLE
Broken: Lao Star

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#15455]
### Broken Link

https://ctrl.laotv.la/live/LaoStar/index.m3u8

### What happened to the stream?

Constantly interrupts/lagging

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by sunyuanzhe** [comment]
malimar TV offered a live tv from al laotian channel for premium service,wuold you please add it to this?

**Comment by sunyuanzhe** [comment]
I used potplayer and there is no sound on it.

**Comment by Dum4G** [comment]
![image](https://github.com/iptv-org/iptv/assets/5430116/f26bf0de-61c2-44e2-846d-c36a22a63a50)
Back online and has a sound in VLC
