### ISSUE TITLE
Add: 312 Kino

### ISSUE THREAD

**Issue by gohoski** [iptv-org/iptv#15457]
### Channel ID (required)

312Kino.kg

### Channel Name

312 Кино

### Stream URL (required)

http://176.126.166.43:1935/live/312kino/playlist.m3u8

### Quality

406p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
404

**Comment by gohoski** [comment]
> 404

It seems that 312 decided to celebrate New Year's Eve by breaking the Kino stream, yesterday it was working completely fine

**Comment by gohoski** [comment]
Seems to be back online!
