### ISSUE TITLE
Russian channels are constantly interrupted and are unstable

### ISSUE THREAD

**Issue by rusyaka84** [iptv-org/iptv#15470]
### Broken Link

https://iptv-org.github.io/iptv/languages/rus.m3u

### What happened to the stream?

Constantly interrupts/lagging

### Notes (optional)

Russian channels are constantly interrupted and work unstable. Some don't work at all. For example RTR.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by rusyaka84** [comment]
Nothing changed.
All movie channels are interrupted. Channel Россия1 does not work at all

**Comment by Dum4G** [comment]
Make sure your player of choice is using up to date playlist, I have removed around 50 dead streams overnight. We aren't content providers. Some sources may be unstable, broadcasted from further distanced regions or simply unavailable outside of Russia. If you have problems with any channel in particular please create a separate issue for each one so we could figure something out. Россия 1 does work for me
![image](https://github.com/iptv-org/iptv/assets/5430116/7dba7787-f392-4463-b0b8-d9b6edd50125)
