### ISSUE TITLE
Edit: AT-X/BS11 (JP)

### ISSUE THREAD

**Issue by solo489** [iptv-org/iptv#15474]
### Stream URL (required)

. 

### Channel ID

 ATX.jp/BS11.jp

### Quality

None

### Label

None

### Notes

Are there any primehome links to AT-X and or BS11?

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
http://asia.vthanhtivi.pw/AT-X/index.m3u8
http://asia.vthanhtivi.pw/BS11/index.m3u8 ?
