### ISSUE TITLE
Add: Aqlvoy [UZ]

### ISSUE THREAD

**Issue by gohoski** [iptv-org/iptv#15489]
### Channel ID (required)

Aqlvoy.uz

### Stream URL (required)

http://gohoski.fvds.ru:3000/mediabay/645/playlist.m3u8

### Quality

480p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by FARUHLI** [comment]
не работает :  
http://gohoski.fvds.ru:3000/mediabay/645/playlist.m3u8
