### ISSUE TITLE
Can you fix these two channels

### ISSUE THREAD

**Issue by Daniel0292** [iptv-org/iptv#15483]
### Describe your issue

Sports 18 hd and Sony sports ten 1 hd please fix these two channels and add star sports select 1 hd and star sports select 2 hd

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Sports 10 kind of works, needs to reattempt connection multiple times
![image](https://github.com/iptv-org/iptv/assets/5430116/3497f261-f64b-46b7-9113-2fd75b7acfdd)
