### ISSUE TITLE
More epg's avaiable

### ISSUE THREAD

**Issue by snowgard-thai** [iptv-org/iptv#1548]
The epg's from http://epg.streamstv.me/ work to for germay & austria. And it can be used without the .gz ending, so that android iptv players like IPTV Smarters Pro can read the file.

http://epg.streamstv.me/epg/guide-germany.xml insteed of http://epg.streamstv.me/epg/guide-germany.xml.gz

http://epg.streamstv.me/epg/guide-austria.xml insteed of http://epg.streamstv.me/epg/guide-austria.xml.gz

You done a great work!!!!

Thank you!!!
snowgard

**Comment by freearhey** [comment]
I don't know exactly what the problem is, but both links don't work in GSE Smart IPTV app.

**Comment by adamo331** [comment]
> The epg's from http://epg.streamstv.me/ work to for germay & austria. And it can be used without the .gz ending, so that android iptv players like IPTV Smarters Pro can read the file.
> 
> http://epg.streamstv.me/epg/guide-germany.xml insteed of http://epg.streamstv.me/epg/guide-germany.xml.gz
> 
> http://epg.streamstv.me/epg/guide-austria.xml insteed of http://epg.streamstv.me/epg/guide-austria.xml.gz
> 
> You done a great work!!!!
> 
> Thank you!!!
> snowgard

This epg is no more up to date you can check here http://epg.streamstv.me/epg/ last update for most epg was on march
