### ISSUE TITLE
Updating IDs in database does not reflect to the new one

### ISSUE THREAD

**Issue by Alstruit** [iptv-org/iptv#15485]
### Describe your issue

Changing old IDs in the database to the new one does not get updated on the update CI.

Examples from the change:
iptv-org/database#8931
iptv-org/database#8918

New Ids:
[Manual Update](https://github.com/iptv-org/iptv/pull/15484/files#diff-7d387527c3d22a423e0fce2f1d12d32e35ca65a4ddfc800f333443d92835de45)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Wasn't that always the case? If you like really reimplement tvg-id you have to manually replace it in epg and playlists. At some point we had 450+ warnings of misssleading tvg-ids here and manually fixed them
