### ISSUE TITLE
Request kurdish TV Channel

### ISSUE THREAD

**Issue by hawrazsabr** [iptv-org/iptv#1549]
Country of the channel:
Iraq

Channel Name:
Iraqia Kurdish
WAAR TV HD
Korek TV
NRT TV HD
Kurdsat News HD
Ava Media TV
Kurd Channel TV
NRT 4

Channel Language:
Kurdish

Additional Information (optional):
Please add these channels.🤗

**Comment by themak1985** [comment]
@hawrazsabr once is enough.
@freearhey this is a duplicate of #1498 #1511 - you can close those if you would like.

**Comment by hawrazsabr** [comment]
@themak1985 you right, i deleted #1511
Thanks.
