### ISSUE TITLE
Broken: Reelz Channel | (US) No longer works

### ISSUE THREAD

**Issue by industrystandard1** [iptv-org/iptv#15508]
### Broken Link

https://bcovlive-a.akamaihd.net/c733a9aa448a4a44a10c527c6f5bf7a4/us-east-1/5245389775001/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

https://github.com/iptv-org/iptv/issues/15260

>That URL doesn't actually work, it just plays the same 17 second clip in a loop

>Link looks like it expired

Every time this gets brought up the issue gets "closed". It is clear to everyone that used Reelz that the stream is down at this point. There have been no updated links. No response. When are we getting a new stream?

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/master/FAQ.md#my-favorite-channel-is-not-on-the-playlist
