### ISSUE TITLE
Broken: Aqlvoy

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#15506]
### Broken Link

http://gohoski.fvds.ru:3000/mediabay/645/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

it worked eariler and now it stopped for some reason. i just wanted to watch ttlb in uzbek

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
@gohoski

**Comment by Dum4G** [comment]
![image](https://github.com/iptv-org/iptv/assets/5430116/5f3584a7-abfd-45f6-ad77-5297768570aa)
Not 24/7
