### ISSUE TITLE
Broken: Cartoon Network East TVE Feed (720p) [Geo-Blocked] [Not 24/7]

### ISSUE THREAD

**Issue by Metroid2023** [iptv-org/iptv#15513]
### Broken Link

https://turnerlive.warnermediacdn.com/hls/live/2023167/tooneast/slate/VIDEO_0_3564000.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

I just found this out today.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by JerkyHockey** [comment]
I wish there was a new link for this channel honestly:/

**Comment by Metroid2023** [comment]
> I wish there was a new link for this channel honestly:/

Me too!
