### ISSUE TITLE
Channels: WBTV (from Tubi)

### ISSUE THREAD

**Issue by GitHub-User101** [iptv-org/iptv#15512]
WBTV Watchlist (Geo)
https://live-news-manifest.tubi.video/live-news-manifest/csm/extlive/tubiprd01,WBD-Watch-List.m3u8

WBTV Keeping It Real (Geo)
https://live-news-manifest.tubi.video/live-news-manifest/csm/extlive/tubiprd01,WBD-Keeping-It-Real.m3u8

WBTV All Together (Geo)
https://live-news-manifest.tubi.video/live-news-manifest/csm/extlive/tubiprd01,WBD-All-Together-Now.m3u8

WBTV At the Movies (Geo)
https://live-news-manifest.tubi.video/live-news-manifest/csm/extlive/tubiprd01,WBD-At-The-Movies.m3u8

WBTV Crime scenes (Geo)
https://live-news-manifest.tubi.video/live-news-manifest/csm/extlive/tubiprd01,WBD-Crime-Scenes.m3u8

WBTV Supernatural (Geo)
https://live-news-manifest.tubi.video/live-news-manifest/csm/extlive/tubiprd01,WBD-Supernatural.m3u8

WBTV How To (Geo)
https://live-news-manifest.tubi.video/live-news-manifest/csm/extlive/tubiprd01,WBD-How-To.m3u8

WBTV Mysteries (Geo)
https://live-news-manifest.tubi.video/live-news-manifest/csm/extlive/tubiprd01,WBD-Mysteries.m3u8

WBTV Love and Marriage (Geo)
https://live-news-manifest.tubi.video/live-news-manifest/csm/extlive/tubiprd01,WBD-Love-Marriage.m3u8

WBTV Family Rules (Geo)
https://live-news-manifest.tubi.video/live-news-manifest/csm/extlive/tubiprd01,WBD-Family-Rules.m3u8

WBTV Slice of Life (Geo)
https://live-news-manifest.tubi.video/live-news-manifest/csm/extlive/tubiprd01,WBD-Slice-Life.m3u8

WBTV Welcome Home (Geo)
https://live-news-manifest.tubi.video/live-news-manifest/csm/extlive/tubiprd01,WBD-Welcome-Home.m3u8

WBTV Paws and Claws (Geo)
https://live-news-manifest.tubi.video/live-news-manifest/csm/extlive/tubiprd01,WBD-Paws-Claws.m3u8

WBTV Sweet Escapes (Geo)
https://live-news-manifest.tubi.video/live-news-manifest/csm/extlive/tubiprd01,WBD-Sweet-Escapes.m3u8

**Comment by Dum4G** [comment]
Thanks for the contrubution!
