### ISSUE TITLE
Add: Enlace (US)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15519]
### Channel ID (required)

KTBNDT4.us

### Channel Name

TBN Enlace

### Stream URL (required)

https://tbn-jw.cdn.vustreams.com/live/enlace/live.isml/playlist.m3u8

### Quality

None

### Label

None

### Notes

These isn't a Channel ID for this Channel and the quality might 720p or 1080p

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Isn't it Costariccan stream for different timezone?

**Comment by R4IN2007** [comment]
I don't know, it's doesn't show the same shows as the costariccan stream maybe it's different timezone? 

https://www.enlace.org/horario/

https://www.ontvtonight.com/guide/listings/channel/1707850655/tbn-enlace-usa.html

**Comment by Dum4G** [comment]
I will assign it to KTBNDT4.us because it has a known guide in the database

**Comment by R4IN2007** [comment]
Ok
