### ISSUE TITLE
Minor Typo Edit for EWTN Africa - Asia

### ISSUE THREAD

**Issue by LPhilip1999** [iptv-org/iptv#15523]
### Describe your issue

This is an minor typo edit, can i request to change channel name from "EWTN Africa Asia" to "EWTN Africa - Asia" please?

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Unfortunately the use of Hyphen is not allowed by markdown rules used by IPTV bot. It's a technical limitation

**Comment by LPhilip1999** [comment]
@Dum4G but you can edit the stream description with Channel Name instead?
