### ISSUE TITLE
Add: Karibeña (720p) [Not 24/7]

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#15524]
### Channel ID (required)

Karibeña.Pe

### Channel Name

Karibeña

### Stream URL (required)

https://iptv-c9-x-m-mck9-video.cusac.online:50050/karibena/tracks-a1/index.fmp4.m3u8

### Quality

None

### Label

None

### Notes

The current transmission link belongs to another channel of the same company. Place the one I sent you in its place and put the first link mentioned (https://streamtv.onliv3.online:1936/karibtv/karibtv/playlist.m3u8) separately under the name "Karibeña TV1". Thank you

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by sguinetti** [comment]
I think that the old stream is a new channel of Peru but not of the seame company. It would be useful to keep the old stream under a new id (TV1.pe).

**Comment by Dum4G** [comment]
May still be related to Karibeña but I will create TV Uno entry in database, even if it's self-made channel of Onliv3
https://wa.me/message/GKPBK7JQ55EGC1?src=qr
![image](https://github.com/iptv-org/iptv/assets/5430116/6b0a04c0-4740-4ff9-aa1c-dfa5ddd2c2d5)

**Comment by BellezaEmporium** [comment]
https://iptv-c9-x-m-mck9-video.cusac.online:50050/karibena/index.fmp4.m3u8
