### ISSUE TITLE
Broken: A-TX

### ISSUE THREAD

**Issue by mocaprid** [iptv-org/iptv#15534]
### Broken Link

http://jp.vthanhnetwork.com/AT-X/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

It's been like 2 or 3 days stream is dead

### Contributing Guide

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by kdhh357** [comment]
The server is down, please wait for the developer to fix it.

**Comment by Dum4G** [comment]
It was worth to wait for it
![image](https://github.com/iptv-org/iptv/assets/5430116/40e1cf1e-2414-42bd-8b4e-00d5375581a3)

**Comment by mocaprid** [comment]
> It was worth to wait for it ![image](https://private-user-images.githubusercontent.com/5430116/296444999-40e1cf1e-2414-42bd-8b4e-00d5375581a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNTIzNzgsIm5iZiI6MTcwNTE1MjA3OCwicGF0aCI6Ii81NDMwMTE2LzI5NjQ0NDk5OS00MGUxY2YxZS0yNDE0LTQyYmQtOGI0ZS0wMGQ1Mzc1NTgxYTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTNUMTMyMTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQ5MjY3Yjg3NjJmNzE2YzZhMjAyZTRmNzI5OGI2ZDE4MTUxMWVhMzU4NDBlZWJmYzg0ODBiMDMxODFiZDIzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WTWuRPoQ71vlr0Ooq0yxjVLiVFobzNId-3INlMz6w1Y)

Thankyou very much! also noticed Tokyo MX's 720p channel is back as well
