### ISSUE TITLE
Add: WYPL TV18 - The Library Channel

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15547]
### Channel ID (required)

WYPLTV18.us

### Channel Name

The Library Channel TV18

### Stream URL (required)

https://reflect-memphis.cablecast.tv/live-2/live/live.m3u8

### Quality

360p

### Label

None

### Notes

https://reflect-memphis.cablecast.tv/CablecastPublicSite/watch/1?channel=1 not https://www.memphislibrary.org/wypl/programs-tv/stream/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
https://reflect-memphis.cablecast.tv/live-2/live/live.m3u8
