### ISSUE TITLE
Broken: M6 (France)

### ISSUE THREAD

**Issue by garelp** [iptv-org/iptv#15543]
### Broken Link

https://shls-m6-france-prod-dub.shahid.net/out/v1/c8a9f6e000cd4ebaa4d2fc7d18c15988/index.m3u8

### What happened to the stream?

Other

### Notes (optional)

Audio and video are completely out of sync.

Can we find another steam for M6 ?

Thanks.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
then we will probably have to use KTV :')
``http://livetv.ktv.zone/7/play.m3u8``

**Comment by azgaresncf** [comment]
it has also align issues
![image](https://github.com/iptv-org/iptv/assets/50982832/c503711a-b673-4e90-8072-088d404fa449)

**Comment by BellezaEmporium** [comment]
> then we will probably have to use KTV :') `http://livetv.ktv.zone/8/play.m3u8`

M6 also exists in Switzerland, though the only difference is in the ads ("Publicité suisse", longer bumpers)

**Comment by azgaresncf** [comment]
> > then we will probably have to use KTV :') `http://livetv.ktv.zone/8/play.m3u8`
> 
> M6 also exists in Switzerland, though the only difference is in the ads ("Publicité suisse", longer bumpers)

Yeah !

**Comment by garelp** [comment]
Except this one http://livetv.ktv.zone/8/play.m3u8 is not M6 but France 5 :-)

**Comment by garelp** [comment]
The right one for M6 is http://livetv.ktv.zone/8/play.m3u8

**Comment by BellezaEmporium** [comment]
> Except this one http://livetv.ktv.zone/8/play.m3u8 is not M6 but France 5 :-)

you've copied and pasted the same link twice :)

**Comment by garelp** [comment]
Indeed.. this is the correct one anyway ;-)  I confirm http://livetv.ktv.zone/8/play.m3u8 is M6
