### ISSUE TITLE
Request for Improved Parental Controls on GitHub Playlists

### ISSUE THREAD

**Issue by orionp13** [iptv-org/iptv#15541]
### Describe your issue

Dear,

I am writing to highlight a concern with parental control on GitHub, specifically regarding the accessibility of adult content. My child bypassed our parental controls using explicit playlists available on GitHub. This loophole is concerning, as GitHub is an essential site we do not wish to block entirely.

I kindly request the implementation of stricter parental controls for such content. This will help protect children from inappropriate material and assist parents in ensuring a safer online environment for their kids.

Thank you for addressing this important issue.

Sincerely,
orionp

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Unfortunately, Github has never been intended with age restricted content in mind. None of the sides (Github included) track where and how it is accessed from. The FOSS content on Github is provided openly and without any restrictions by it's nature. My only suggestion is to use some parent control software on your PC or even your router that detects "adult" requests whether those are typed or blocks any content where "adult" terminology or slang is being used. And even then it may be flawed, finding free IPTV/streaming source for bypassing parental control is on itself a bright idea that won't be easy to catch by any rule preset.

**Comment by akonitx** [comment]
Hi, i don't know how to contact developers of this repo, so i'm writing here. But I'm sure that someone has iptv playlist with nsfw, can someone share the file or better the link at taraschorny10@gmail.com?
