### ISSUE TITLE
Add: Taiwan Plus TV

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15551]
### Channel ID (required)

TaiwanPlusTV.tw

### Channel Name

Taiwan Plus TV

### Stream URL (required)

https://bcovlive-a.akamaihd.net/rce33d845cb9e42dfa302c7ac345f7858/ap-northeast-1/6282251407001/playlist.m3u8

### Quality

1080p

### Label

None

### Notes

I don't if the quality is 720p or 1080p

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
It's 1080p.

**Comment by zhouxinghong** [comment]
can not play. Has it expired?
