### ISSUE TITLE
Broken: ToeiChannel

### ISSUE THREAD

**Issue by okonomitarou** [iptv-org/iptv#15567]
### Broken Link

http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=cs27

### What happened to the stream?

No sound

### Notes (optional)

There is no problem with the video,
but there is no sound at all.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
seems fixed now
