### ISSUE TITLE
Add: NBSD Board Meeting TV

### ISSUE THREAD

**Issue by bbb2204** [iptv-org/iptv#15566]
### Channel ID (required)

NBSDbm.us

### Channel Name

NBSD Board Meeting TV

### Stream URL (required)

https://www.youtube.com/watch?v=l9tsSeT8fAE

### Quality

720p

### Label

None

### Timeshift

none

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
1. There's no channel in database that goes with that id or that name in the database. Please go to database repository, propose to add one and get your approval first. 
2. I'm not seeing any broadcasts from them since 2022. Are you sure they're streaming?
