### ISSUE TITLE
Virus!! Trojan:HTML/Brocoiner.N!lib

### ISSUE THREAD

**Issue by manginoeu** [iptv-org/iptv#1557]
**What's wrong?**
Two channels from the playlist contain a virus Trojan:HTML/Brocoiner.N!lib
**Country of the channel:**
Germany and ..?
**Channel Name:**
TVA Ostbayern & Radio Capital TV
**Broken Link:**

**Additional Information (optional):**
Trojan:HTML/Brocoiner.N!lib ....

TVA Ostbayern
containerfile: C:\Users\Public\NPVR-data\media\channels\TVA Ostbayern.png
file: C:\Users\Public\NPVR-data\media\channels\TVA Ostbayern.png->(SCRIPT0006)

Radio Capital TV
containerfile: C:\Users\Public\NPVR-data\media\channels\Radio Capital TV.png
file: C:\Users\Public\NPVR-data\media\channels\Radio Capital TV.png->(SCRIPT0006)

**Comment by freearhey** [comment]
Sorry, but could you be more specific. 

If you're referring to specific broadcast, it is better if you provide a link to it in this repository.

**Comment by manginoeu** [comment]
I don't know exactly, but it's just three (TVA Ostbayern) and two (Radio Capital TV) channels:
https://iptv-org.github.io/iptv/index.country.m3u (grouped by country)

**Comment by freearhey** [comment]
Could you then specify how exactly you checked these channels?

**Comment by manginoeu** [comment]
Windows Security/**Windows Defender**: Each time the NextPVR v.5 (only **wwwroot**, client NextPVR not work) program is started, resp. when browsing between channels, that is, **each time the channel is changed**.

**Comment by freearhey** [comment]
And it only gives a warning on these 2 channels? Have you tried to run any other channels?

**Comment by manginoeu** [comment]
Yes, a warning it only gives a these 2 channels. Even if I switch to any channel!! :-(

**Comment by freearhey** [comment]
This is very strange. The playlist contains dozens of links to the same server and if these channels are infected then the rest of them should generate a warning too.

Unfortunately, I cannot personally check these and other links on my computer, but if someone can help and double-check everything it would be great.

**Comment by Nintendocustom** [comment]
I think the problem is the logo: https://www.firstonetv.live/images/logos/de/TVA.png

**Comment by Sphinxroot** [comment]
tested  it on virus total  only 1 came whit malware  .. the best thing is to use another logo and hosted it on imgur .. problem solved :)

**Comment by freearhey** [comment]
The link to the logo has been removed.

I didn't find any other links to the same domain in the repository. But if you suspect any other links, be sure to let me know.
