### ISSUE TITLE
Broken: Smithsonian 

### ISSUE THREAD

**Issue by TKList** [iptv-org/iptv#15571]
### Broken Link

https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg01553-blueantmediaasi-smithsoniannz-samsungnz/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

The other link for it also doesn't work. 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
http debug: x-amzn-requestid: "LOR34PDYPKWOTOZDBTQRN6FONCL3L4VZCVD25PUK5AIV2K3ZEA7C4O4EGVPLMQV26BSQA76WX5IAGOKWKJGIVCY"
http debug: x-amzn-errortype: "ObjectNotFoundException"
