### ISSUE TITLE
Arabic channels request

### ISSUE THREAD

**Issue by TheTBO** [iptv-org/iptv#1558]
Thank you for the great work.
When I started there was a wider variety of Arabic channels specifically Egyptian and Sudanese TV stations that are no longer available, it seem like the source is no longer available. 
I wonder if it's possible to find alternate sources.
P.S. I would love to help as much as I can

**Comment by freearhey** [comment]
Could you specify channel names?

**Comment by TheTBO** [comment]
To name a few.
CBC
Al Nahar
dmc
Sudania 24
Alhayat

**Comment by MoonSyria** [comment]
CBC
#EXTINF:-1, tvg-id="CBC Sofra ARB" tvg-logo="https://i.imgur.com/qmhfPpd.png" tvg-name="CBC Sofra"  group-title="General",CBC Sofra
http://51.159.21.231:2052/live/SOURCEARABPRO22/31136@38606/2356.m3u8

Al Nahar =  Ennahar
#EXTINF:-1, tvg-id="EPG N/A" tvg-logo="Logo N/A" tvg-name="Ennahar TV"  group-title="General",Ennahar TV
http://numidiatv-live.dzsecurity.net:8081/entv/EnnaharTV/playlist.m3u8

Alhayat
#EXTINF:-1, tvg-id="EPG N/A" tvg-logo="Logo N/A" tvg-name="Al Hayat"  group-title="General",Al Hayat
http://media.islamexplained.com:1935/live/_definst_mp4:ahme.stream_360p/playlist.m3u8

**Comment by TheTBO** [comment]
CN Arabia
#EXTINF:0 tvg-country="" tvg-logo="" group-title="Undefined",CN Arabia
http://37.235.38.131:4000/play/a02l/index.m3u8

Al Nahar Drama
#EXTINF:0 tvg-country="EG" tvg-logo="https://www.1arablive.com/livetv/assets/images/1525633972.png" group-title="Undefined",Al Nahar Drama
http://178.132.3.162:88/Al_Nahar_Drama/video.m3u8

**Comment by MoonSyria** [comment]
> CN Arabia
> #EXTINF:0 tvg-country="" tvg-logo="" group-title="Undefined",CN Arabia
> http://37.235.38.131:4000/play/a02l/index.m3u8
> 
> Al Nahar Drama
> #EXTINF:0 tvg-country="EG" tvg-logo="https://www.1arablive.com/livetv/assets/images/1525633972.png" group-title="Undefined",Al Nahar Drama
> http://178.132.3.162:88/Al_Nahar_Drama/video.m3u8

This link is broken!
http://178.132.3.162:88/Al_Nahar_Drama/video.m3u8
It is not working

**Comment by freearhey** [comment]
Al Hayat: https://github.com/iptv-org/iptv/blob/304c9886268d94602ad5c074247b2097d868794d/channels/eg.m3u#L6-L7

**Comment by freearhey** [comment]
Closed in favor #1947 and #1977
