### ISSUE TITLE
Add: PeruvianRadioTV.pe

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#15583]
### Channel ID (required)

PeruvianRadioTV.pe

### Stream URL (required)

https://vdo.grupolimalive.com:3399/stream/play.m3u8

### Quality

None

### Label

None

### Notes

The stream is renamed PeruvianRTV. It is not clear if this is its commercial name.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
I see "Peru Shumac"
