### ISSUE TITLE
Add: RajawaliTV.id

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#15592]
### Channel ID (required)

RajawaliTV.id

### Stream URL (required)

http://iptvid.my.id/hmm/Gaboleh/gasukatugas123/rtv.m3u8

### Quality

None

### Label

None

### Notes

https://github.com/iptv-org/iptv/issues/15565

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Ripped from IndihomeTV, a legit source, however it might seem to leak an username and password off it. Haven't checked but the URL might hint us.

**Comment by FlcristPony** [comment]
I commented yesterday on my issue, but the link isn't working anymore with `You're banned by admin`. Can someone look for another working link?

**Comment by BellezaEmporium** [comment]
> I commented yesterday on my issue, but the link isn't working anymore with `You're banned by admin` message. Can someone look for another working link?

Indeed.

~ wrong certificate
~ indonesian message saying "You have been banned by admin, please follow the rules"
