### ISSUE TITLE
Please, please, pretty please ad Digi24 RO

### ISSUE THREAD

**Issue by mariafbb** [iptv-org/iptv#1559]
**Country of the channel:**

Romania

**Channel Name:**

Digi24

**Channel Language:**
romanian

**Additional Information (optional):**

**Comment by isayful346** [comment]
https://m.digi24.ro/live/digi24

**Comment by freearhey** [comment]
Done.
https://github.com/iptv-org/iptv/blob/fcb92abcb04c9f735f7cd4c9c214a5b833ae0b20/channels/ro.m3u#L154-L155

**Comment by mariafbb** [comment]
It's not working for me. Can you update please the list from the first page ? 
I don't know how else to ad it to my TV?

**Comment by mariafbb** [comment]
Thank you, thank you, thank you for helping me out

**Comment by DjRoberto69** [comment]
Digi24 HD

### Stream URL

https://edge-ar.rcs-rds.ro/digi24ar/hd.m3u8

Digi24 SD

### Stream URL

https://edge-ar.rcs-rds.ro/digi24ar/hq.m3u8
