### ISSUE TITLE
Add: Azteca Guatemala

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15594]
### Channel ID (required)

AztecaGuatemala.gt

### Channel Name

Azteca Guate

### Stream URL (required)

https://ch1-tva.duin.dev/hls/stream.m3u8

### Quality

1080p

### Label

None

### Notes

Is this by any chance 360p? If not, change it
^looks kinda 1080p -ish

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ztreamhd** [comment]
It is indeed 1080p. In fact, the URL you posted is adaptive, with `https://ch1-tva.duin.dev/hls/0/stream.m3u8` being the 1080p version and so on until `https://ch1-tva.duin.dev/hls/3/stream.m3u8` which is the 360p version. (432p and 720p versions are also available).

**Comment by BellezaEmporium** [comment]
Second stream : https://ch2-tva.duin.dev/hls/stream.m3u8
