### ISSUE TITLE
Broken: NHK E 

### ISSUE THREAD

**Issue by BillNye465** [iptv-org/iptv#15607]
### Broken Link

http://jp.vthanhnetwork.com/NHK_E/index.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by dantheman121** [comment]
you need vpn set to japan or else it won't work

**Comment by LastExile16** [comment]
I'm in Japan, but the link still doesn't work.
