### ISSUE TITLE
Broken stream: 🇨🇮 Ivory Coast	

### ISSUE THREAD

**Issue by Duckinu69** [iptv-org/iptv#15609]
### Broken Link

https://iptv-org.github.io/iptv/countries/ci.m3u

### What happened to the stream?

Not loading

### Notes (optional)
90% of streaming sources ain't working 
The main national channels ain't work example RT1, NCI.

Please add: A+ & Lifetv

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Are you watching from 🇨🇮? Looks like RT1 and RT3 is geo-blocked, RT2 is working just fine

**Comment by Duckinu69** [comment]
I've try all the VPN incl 🇨🇮 VPN address RTI & NCI ain't working.

Funny thing it was working fine 2 weeks ago

**Comment by Duckinu69** [comment]
Indeed NCI is working now thank you

**Comment by fraudiay79** [comment]
They are currently blocked due to the CAF African Cup of Nations tournament.

**Comment by Duckinu69** [comment]
Possibly to add A+ is part of ivoirian channel.

Here more info about that channel: [Wiki](https://fr.m.wikipedia.org/wiki/A%2B_(cha%C3%AEne_de_t%C3%A9l%C3%A9vision))
