### ISSUE TITLE
Broken: NHK E

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#15616]
### Broken Link

http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=gd02

### What happened to the stream?

Other

### Notes (optional)

it says in japanese that i need vpn set to japanese i think and i do have vpn set to jp

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
[Working.](https://streamtest.in/logs/http-cdns-jp-primehome-com-8000-zhongying-live-playlist-m3u8-cid-gd02-abb61f6e-9c9e-49ba-848e-417e82a6c68f)
