### ISSUE TITLE
Broken: AT-X

### ISSUE THREAD

**Issue by solo489** [iptv-org/iptv#15610]
### Broken Link

http://asia.vthanhnetwork.com/AT-X/index.m3u8

### What happened to the stream?

Constantly interrupts/lagging

### Notes (optional)

Replace http://asia.vthanhnetwork.com/AT-X/index.m3u8 with a primehome.m3u link.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
This host doesn't have AT-X.
