### ISSUE TITLE
Broken: MAVTV

### ISSUE THREAD

**Issue by xemles** [iptv-org/iptv#15617]
### Broken Link

https://mavtv-mavtvglobal-1-se.samsung.wurl.tv/playlist.m3u8

### What happened to the stream?

Other

### Notes (optional)

It's the wrong channel, this is MAVTV Select (MAVTVSelect.us) this also applies to all its alternatives in the _samsung lists:

https://mavtv-mavtvglobal-1-se.samsung.wurl.tv/playlist.m3u8 (this is the one in the broken link field)
https://mavtv-mavtvglobal-1-ie.samsung.wurl.tv/playlist.m3u8
https://mavtv-mavtvglobal-1-nz.samsung.wurl.tv/playlist.m3u8
https://mavtv-mavtvglobal-1-be.samsung.wurl.tv/playlist.m3u8
https://mavtv-mavtvglobal-1-nl.samsung.wurl.tv/playlist.m3u8
https://mavtv-mavtvglobal-1-in.samsung.wurl.tv/playlist.m3u8
https://mavtv-1-ca.samsung.wurl.tv/playlist.m3u8
https://mavtv-mavtvglobal-1-lu.samsung.wurl.tv/playlist.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
So every link is dead right? None of them work for me

**Comment by Sphinxroot** [comment]
#EXTINF:-1 ,MAV Select CANADA
https://d70mb4nkspm3g.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-vvwqo3j029lz0/playlist.m3u8
#EXTINF:-1 ,MAV Select USA
https://d3h07n6l1exhds.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-0z2yyo4dxctc7/playlist.m3u8

#EXTINF:-1,MAVTV Motor Sports UK
https://amg00378-maverickenterta-mavtv-smn-gb-samsung-rakuten-ozity.amagi.tv/playlist/amg00378-maverickenterta-mavtv-smn-gb-samsung-rakuten/playlist.m3u8
#EXTINF:-1,MAVTV Motor Sports IN
https://84f081227bc1418984b9e3dcaa985b2b.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-in_MAVTVMotorSportsNetwork/playlist.m3u8

**Comment by BellezaEmporium** [comment]
> #EXTINF:-1 ,MAV Select CANADA https://d70mb4nkspm3g.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-vvwqo3j029lz0/playlist.m3u8 #EXTINF:-1 ,MAV Select USA https://d3h07n6l1exhds.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-0z2yyo4dxctc7/playlist.m3u8
> 
> #EXTINF:-1,MAVTV Motor Sports UK https://amg00378-maverickenterta-mavtv-smn-gb-samsung-rakuten-ozity.amagi.tv/playlist/amg00378-maverickenterta-mavtv-smn-gb-samsung-rakuten/playlist.m3u8 #EXTINF:-1,MAVTV Motor Sports IN https://84f081227bc1418984b9e3dcaa985b2b.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-in_MAVTVMotorSportsNetwork/playlist.m3u8

Second one is a simple redirect to https://mavtv-mavtvglobal-1-in.samsung.wurl.tv/playlist.m3u8.

**Comment by Dum4G** [comment]
@BellezaEmporium @xemles @Alstruit? Which links work and which don't?

**Comment by BellezaEmporium** [comment]
> @BellezaEmporium @xemles @Alstruit? Which links work and which don't?

Well they're all working but they're showing diff channels

**Comment by Dum4G** [comment]
Can you handle this? For me almost none of them work even with VPN

**Comment by BellezaEmporium** [comment]
Yep, they've shut them all except the IN version. The ones Sphinx have given are working fine. The last one is a redirect of the IN version.
