### ISSUE TITLE
Broken: TVT.tg

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#15639]
### Broken Link

http://109.235.69.40:8000/streamshls/channel_20/index.m3u8

### What happened to the stream?

Shows looped video

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Seems like their server is... rather like a private one gone public for no reason lol. Some other channels are showing someone working or the outside of an apartment. Odd.
