### ISSUE TITLE
Cuban Channels

### ISSUE THREAD

**Issue by pedritostia** [iptv-org/iptv#1563]
**Country of the channel:**

Cuba

**Channel Name:**

Cubavisión
Canal Habana
Canal Educativo
Canal Educativo 2
Canal Caribe
Canal Clave
Multivision
Telerebelde
**Channel Language:**
Spanish

**Additional Information (optional):**
There is no m3u list for Cuba or any cuban channels. Please add them if possible.

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-logo="http://www.lyngsat-stream.com/logo/tv/cc/cubavision_internacional.png" tvg-id="" group-title="CUBA" ,Cubavisión Internacional 
https://cdn.teveo.cu/live/video/Hqp6Hb4Vq2GFNeGj/ngrp:gppfydfzpSUn9Udy.stream/chunklist_b1728000.m3u8

#EXTINF:-1 tvg-logo="https://i.imgur.com/G5KYULo.png" tvg-id="833" group-title="CUBA" ,TV Martí 
https://ocb-lh.akamaihd.net/i/ocb_mpls_tvmc1@383606/master.m3u8

seem to be satelite ch only not mutch stream around

**Comment by pedritostia** [comment]
Nope, there are streams on the cuban websites for these channels.

I believe this one has them all: http://www.tvcubana.icrt.cu

**Comment by freearhey** [comment]
Closed in favor #1979
