### ISSUE TITLE
Add: Hope Channel Inter-America

### ISSUE THREAD

**Issue by LPhilip1999** [iptv-org/iptv#15637]
### Channel ID (required)

HopeChannelInterAmerica.us

### Channel Name

Hope Channel Inter-America

### Stream URL (required)

https://videodelivery.net/75bc18929102141938b334b01793ca3e/manifest/video.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Not loading for me @BellezaEmporium @Alstruit

**Comment by LPhilip1999** [comment]
@Dum4G, For me it's working with Hope Channel Inter-America Spanish streaming.
![Screenshot_2024-01-25-12-52-41-46_013dba30cae4674f6b0947ea3c272499](https://github.com/iptv-org/iptv/assets/107766357/f66cda02-0c13-4340-b61d-90983a933692)

**Comment by BellezaEmporium** [comment]
Might be GEO

**Comment by Dum4G** [comment]
So the user agent might be needed?

**Comment by LPhilip1999** [comment]
> Might be GEO
> 
> EDIT : Tried with a VPN set to Miami, nothing goes in. Might be Not 24/7.
> 
> EDIT2 : Works with my PC browser (Firefox)

I'm using the Televizo app aswell and it works the stream

**Comment by Dum4G** [comment]
Very interesting behavior from VLC
adaptive debug: Retrieving https://videodelivery.net:443/d0686a27636b6c83f3f19c80e749bac1/video/1080/init.mp4?p=eyJ0eXBlIjoiaW5pdCIsInZpZGVvSUQiOiJkMDY4NmEyNzYzNmI2YzgzZjNmMTljODBlNzQ5YmFjMSIsIm93bmVySUQiOjEwMTQ5NzUyLCJjcmVhdG9ySUQiOiJoY29yZzo1S3ZFWVhKZllEMCIsInVzZVZPRE9URkUiOmZhbHNlLCJmcm9tTWV6emFuaW5lIjpmYWxzZSwidHJhY2siOiIxIiwicmVuZGl0aW9uIjoiMTA4MDAwMSIsIm11eGluZyI6IjE5MjAiLCJsaXZlU291cmNlSUQiOiI1ZGMwMTk1MWZhMGI5YTU3OTk3ZThiZTVjYzUwYjI5YiJ9&s=Gm_CgTvDn31AFcK6wp84PMKzwp18cMKuwobDpcKEDnfCnw98w73DocKhw4vCgRQx
http debug: :status: "404"

**Comment by Sphinxroot** [comment]
# https://en.hopechannelinteramerica.org/streaming
# https://embed.jetstream.studio/embed/jsl:UP9KAdlVrm8mEDC2iV7x
#EXTINF:-1 tvg-id="HopeChannelInterAmerica.us",Hope Channel Inter-America
https://videodelivery.net/5dc01951fa0b9a57997e8be5cc50b29b/manifest/video.m3u8

**Comment by LPhilip1999** [comment]
@Sphinxroot that is a English language stream for Hope Channel Inter-America

> # https://en.hopechannelinteramerica.org/streaming
> # https://embed.jetstream.studio/embed/jsl:UP9KAdlVrm8mEDC2iV7x
> #EXTINF:-1 tvg-id="HopeChannelInterAmerica.us",Hope Channel Inter-America https://videodelivery.net/5dc01951fa0b9a57997e8be5cc50b29b/manifest/video.m3u8

**Comment by Sphinxroot** [comment]
# https://hopechannelinteramerica.org/streaming
# https://embed.jetstream.studio/embed/jsl:EC0Mq0i6HJU6IZ49d0as
https://videodelivery.net/75bc18929102141938b334b01793ca3e/manifest/video.m3u8

audio segmented

work in kodi
