### ISSUE TITLE
Broken: tviafrica

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#15632]
### Broken Link

https://video-auth4.iol.pt/live_tvi_africa/live_tvi_africa/edge_servers/tviafrica-480p/playlist.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
![image](https://github.com/iptv-org/iptv/assets/30985701/e808571a-fb8e-4ee2-a4ad-f3592bac95a7)
