### ISSUE TITLE
Add: Esperanza TV [US]

### ISSUE THREAD

**Issue by LPhilip1999** [iptv-org/iptv#15636]
### Channel ID (required)

EsperanzaTV.us

### Channel Name

Esperanza TV

### Stream URL (required)

https://videodelivery.net/a23831aa01c4a0fd802360b889ea96ed/manifest/video.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Not loading for me @BellezaEmporium @Alstruit

**Comment by LPhilip1999** [comment]
@Dum4G, for me it's working with Esperanza TV stream.
![Screenshot_2024-01-25-12-53-49-68_013dba30cae4674f6b0947ea3c272499](https://github.com/iptv-org/iptv/assets/107766357/4444f5d4-9309-4f33-89ab-4b7a2b238a61)

**Comment by BellezaEmporium** [comment]
File answers but nothing goes through. Not 24/7 ?

**Comment by LPhilip1999** [comment]
> File answers but nothing goes through. Not 24/7 ?
> 
> EDIT : Works from my PC browser (Firefox)

I'm using the Televizo app and it works the stream

**Comment by BellezaEmporium** [comment]
Maybe an user-agent is needed.
