### ISSUE TITLE
Request Channel List

### ISSUE THREAD

**Issue by hawrazsabr** [iptv-org/iptv#1564]
**Country of the channel:**
Iraq

**Channel Name:**
Iraqia Kurdish
WAAR TV HD
Korek TV
NRT TV HD
Kurdsat News HD
Ava Media TV
Kurd Channel TV
NRT 4

**Channel Language:**
Kurdish

**Additional Information (optional):**
There is no m3u list for Iraq channels. Please add them if possible.

**Comment by freearhey** [comment]
The playlist for the Iraqi channels is already in place: https://iptv-org.github.io/iptv/countries/iq.m3u

**Comment by hawrazsabr** [comment]
Ok but all channel from here not all of them from this PlayList you given me.

**Comment by freearhey** [comment]
That's why this issue is still open.

**Comment by hawrazsabr** [comment]
Thanks.

**Comment by freearhey** [comment]
Duplicate #1498
