### ISSUE TITLE
Broken: Cartoon Network (RU)

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#15653]
### Broken Link

http://135.181.115.81/russia/cartoon/playlist.m3u8

### What happened to the stream?

No sound

### Notes (optional)

there is no sound pls fix it

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Resolved on it's own
