### ISSUE TITLE
Arabic syrian channels

### ISSUE THREAD

**Issue by darkspook1** [iptv-org/iptv#1566]
**What's wrong?**
a lot of the Arabic channels are not working anymore
**Country of the channel:**
Syria
**Channel Name:**
Lana Plus
Lana TV
Sama 

**Country of the channel:**
Lebanon
**Channel Name:**
AL Jadeed
LBC
NBN

Could you please update their links?? 
thanks a lot in advance

**Comment by darkspook1** [comment]
Country of the channel:
Egypt, their were deleted from the List, could you pls add them again?
Channel Name:
CBC
CBC Drama
Alhayat TV
CBC Sofra
DMC Drama
ON Drama
ON E

**Comment by Alfeen** [comment]
a lot of the Arabic channels are not working anymore Syrian channels 
Lana Plus
Lana TV
Sama
Lebanon channel 
AL Jadeed
LBC
NBN
LDC
MTV
Egyptian channel 
CBC
CBC Drama
Alhayat TV
CBC Sofra
DMC Drama
ON Drama
ON E
And more

**Comment by MoonSyria** [comment]
I fixed some channels

Sama TV (I tested it in VLC)

#EXTINF:-1, tvg-id="Samaa TV ARB" tvg-logo="https://i.imgur.com/PAP6jnu.jpg" tvg-name="Sama TV"  group-title="Drama",Sama TV
http://192.34.153.37:7777/SamaTV_HD/SamaTV_HD.m3u8?user=sgls540839&session=975c9804735080aef315ce8df9077e820df0c4f96fae2f1d7c0f8772c4f2024f&hlsid=HTTP_ID_1&starttime=20200504T202449.771384

OTV
#EXTINF:-1, tvg-id="OTV Lebanon ARB" tvg-logo="https://i.imgur.com/Cq0IXMb.jpg" tvg-name="OTV"  group-title="General",OTV
https://svs.itworkscdn.net/otvlebanonlive/otv.smil/playlist_406p.m3u8

LBC
#EXTINF:-1, tvg-id="LBC ARB" tvg-logo="https://i.imgur.com/YPR45yP.png" tvg-name="LBC"  group-title="General",LBC
https://rotana.hibridmedia.com/rotana/lbc_dabr/playlist.m3u8

MTV 
#EXTINF:-1, tvg-id="MTV Lebanon ARB" tvg-logo="https://i.imgur.com/6R1jFJO.jpg" tvg-name="MTV"  group-title="General",MTV
http://51.178.43.32:25461/live/tdn/44119572164/10146728.m3u8

Lana TV
http://51.81.80.6:25461/live/zeko/zeko/28.m3u8

Alhayat TV
https://wowzaprod140-i.akamaihd.net/hls/live/750788/cdb837ca/playlist.m3u8

#EXTINF:-1, tvg-id="Al Jadeed Lebanon ARB" tvg-logo="https://i.imgur.com/qtQQJQc.png" tvg-name="Al Jadeed"  group-title="General",Al Jadeed
http://watch.teledunet.com:25461/live/tdn/23614613767/10146727.m3u8

CBC Sofra
#EXTINF:-1, tvg-id="CBC Sofra ARB" tvg-logo="https://i.imgur.com/qmhfPpd.png" tvg-name="CBC Sofra"  group-title="General",CBC Sofra
http://51.159.21.231:2052/live/SOURCEARABPRO22/31136@38606/2356.m3u8

Additional channel for Kids (Koky Kids)
#EXTINF:-1, tvg-id="Koky Kids" tvg-logo="https://i.imgur.com/cla9w5J.jpg" tvg-name="Koky Kids"  group-title="Kids",Koky Kids
http://51.159.21.231:2052/live/SOURCEARABPRO22/31136@38606/2416.m3u8

**Comment by darkspook1** [comment]
@freearhey would you please add these channels?

**Comment by themak1985** [comment]
@darkspook1 I cleaned up some of the code and created pull requests #1600 #1601 
Thanks @MoonSyria for the links.

**Comment by freearhey** [comment]
Channels added. Thanks to @MoonSyria and @themak1985

**Comment by Ghani201** [comment]
Channel Name DMC Kids
Country Egypt
Website xxx Please Update M3u8 For DMC Kids Please
