### ISSUE TITLE
Add: Hope Channel Inter-America (English)

### ISSUE THREAD

**Issue by LPhilip1999** [iptv-org/iptv#15668]
### Channel ID (required)

HopeChannelInterAmericaEnglish.us

### Channel Name

Hope Channel Inter-America (English)

### Stream URL (required)

https://videodelivery.net/5dc01951fa0b9a57997e8be5cc50b29b/manifest/video.m3u8

### Quality

1080p

### Label

None

### Notes

This is the English Language broadcast feed for Hope Channel Inter-America.
![Screenshot_2024-01-26-18-37-40-24_013dba30cae4674f6b0947ea3c272499](https://github.com/iptv-org/iptv/assets/107766357/175f2c16-3e49-4c82-b50c-da63e201e0f9)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
https://en.hopechannelinteramerica.org/streaming
https://embed.jetstream.studio/embed/jsl:UP9KAdlVrm8mEDC2iV7x
#EXTINF:-1 tvg-id="HopeChannelInterAmerica.us",Hope Channel Inter-America
https://videodelivery.net/5dc01951fa0b9a57997e8be5cc50b29b/manifest/video.m3u8
