### ISSUE TITLE
Add: Hope Channel Philippines [PH]

### ISSUE THREAD

**Issue by LPhilip1999** [iptv-org/iptv#15669]
### Channel ID (required)

Hope Channel Philippines

### Channel Name

HopeChannelPhilippines.ph

### Stream URL (required)

https://customer-x8zydurm357k8j9p.cloudflarestream.com/e9a0f1b659e4a6052fa798846914a4f7/manifest/video.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
# https://hopetv.ph/watch
# https://embed.jetstream.studio/embed/jsl:7A1swL7Fhlh
https://customer-x8zydurm357k8j9p.cloudflarestream.com/e9a0f1b659e4a6052fa798846914a4f7/manifest/video.m3u8
