### ISSUE TITLE
Add: INC TV (Philippine Channel)

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15665]
### Channel ID (required)

INCTV.ph

### Channel Name

INC TV (720p)

### Stream URL (required)

https://199211.global.ssl.fastly.net/643cc12aa824db4374021c8c/live_95f6ac80dd6511ed9d08b12be56ae55e/index.m3u8

### Quality

720p

### Label

Geo-blocked

### Timeshift

0

### Notes

Philippine Channel

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Please add the necessary info into https://github.com/iptv-org/database according to [Contributing Guide](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md). An automated addition won't work without proper id and channel info

**Comment by user8387884** [comment]
done
