### ISSUE TITLE
Add: MV Lao TV

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#15662]
### Channel ID (required)

MVLaoTV.la

### Stream URL (required)

https://n-edge-1-th.v2h-cdn.com/mvlao/mvlao/playlist.m3u8

### Quality

None

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Duplicate of https://github.com/iptv-org/iptv/issues/15597
