### ISSUE TITLE
Broken: PIE Channel (1080p) (Not 24/7)

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15667]
### Broken Link

https://ythls.armelin.one/channel/UCAxAaFQnH5IK_ZTwiQWV-9A.m3u8

### What happened to the stream?

Other

### Notes (optional)

Channel Shutdown At January 1, 2024

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
You seem to use an extremely outdated playlist considering the link you have provided
