### ISSUE TITLE
Edit: TokyoMX1

### ISSUE THREAD

**Issue by solo489** [iptv-org/iptv#15663]
### Stream URL (required)

http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=gd08

### Channel ID

JOMX.jp

### Channel Name

Tokyo MX

### Quality

576p

### Label

None

### Notes

It changed back to its recent stream https://mcas-eqms-mx1-live.hls.davlive.stream.ne.jp/mt/master/340fcd590451b1e7d0034b85b5175ddaf05454/EQMS_MX1/master.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
? Most certainly due to quality bump.

**Comment by Dum4G** [comment]
it broadcasts exactly in 544p which corresponds to the data in the playlist
