### ISSUE TITLE
Broken: Thrill

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15666]
### Broken Link

http://210.210.155.37/qwr9ew/s/s34/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

I think it's geo-blocked, when i open the channel, it skips to another channel

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Retrieving http://210.210.155.37:80/session/bd76c772-bc7b-11ee-99f7-807f93b50d88/qwr9ew/s/s34/20230913T052700-02-42480994.ts
http debug: outgoing request: GET /session/bd76c772-bc7b-11ee-99f7-807f93b50d88/qwr9ew/s/s34/20230913T052700-02-42480994.ts HTTP/1.1 Host: 210.210.155.37:80 Accept: */* Accept-Language: ru User-Agent: VLC/3.0.20 LibVLC/3.0.20 Accept-Encoding: deflate, gzip Cache-Control: no-cache 
http debug: incoming response: HTTP/1.1 404 Not Found Content-Length: 0 Date: Fri, 26 Jan 2024 18:50:14 GMT Access-Control-Allow-Origin: *
