### ISSUE TITLE
Edit:  HITS (576p) [Geo-Blocked]

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15679]
### Stream URL (required)

 http://vip.tvgiganten.com:2095/play/live.php?mac=10:27:be:0d:20:96&stream=144024&extension=m3u8

### Channel ID

HITS.HD.sg

### Channel Name

HITS

### Quality

1080p

### Label

None

### Timeshift

0

### Notes

channel skipping like thrill (Cignal Feed)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by user8387884** [comment]
the link does not require vpn

**Comment by Dum4G** [comment]
That link won't work for everyone as it contains viewer specific data and wasn't meant to be used across the world
