### ISSUE TITLE
Broken: Cartoon Network (UK)

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#15677]
### Broken Link

http://89.254.128.5:22280/cartoon_network/index.m3u8

### What happened to the stream?

Other

### Notes (optional)

the bumpers are in another language and i don't understand

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Bumpers are in Indonesian I believe, rest is in English.

**Comment by Dum4G** [comment]
tvg-id is CartoonNetworkScandinavia.uk
The stream is from Riga

**Comment by Dum4G** [comment]
I see no problem here, if you're not satisfied with area of broadcast or the language specified you can submit your edit the database or propose a PR for a channel rename
