### ISSUE TITLE
Add: Hope Channel New Zealand [NZ]

### ISSUE THREAD

**Issue by LPhilip1999** [iptv-org/iptv#15670]
### Channel ID (required)

HopeChannelNewZealand.nz

### Channel Name

Hope Channel New Zealand

### Stream URL (required)

https://dacastmmd.mmdlive.lldns.net/dacastmmd/e46cdf99f97b45e597a5a608b908a44a/chunklist_b4628000.m3u8?p=79&s=1706264308&e=1706264428&h=07c5201225173fd086097bf0491ca37b

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
this one seem to have a token

**Comment by Irylek** [comment]
HOW THE HECK THIS STREAM STILL WORKS LMAOOOO
