### ISSUE TITLE
Add: A2Z Channel 11 (Filipino)

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15680]
### Channel ID (required)

A2Z.ph

### Channel Name

A2Z

### Stream URL (required)

http://vip.tvgiganten.com:2095/play/live.php?mac=10:27:be:0d:20:96&stream=143964&extension=m3u8

### Quality

480p

### Label

None

### Timeshift

0

### Notes

Channel never added into this playlist before

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
That link won't work for everyone as it contains viewer specific data and wasn't meant to be used across the world
