### ISSUE TITLE
EPG on Argentina Channels 

### ISSUE THREAD

**Issue by MrCoolAndroid** [iptv-org/iptv#1568]
**Is your feature request related to a problem? Please describe.**
Is not related to a problem

**Describe the solution you'd like**
I would like to contribute a EPG for Argentina Channels, just change channels name like those of the EPG, I would like to contribute

**Describe alternatives you've considered**
Maybe my EPG will not fit with the channels, then you should search for one working or I can mantain it

**Additional context**
None

**Comment by freearhey** [comment]
If you have a link to a working EPG for Argentina channels and you want to add it to playlist then feel free to do so. 

If you don't know how to do it then here are the guide: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#add-epg-source

**Comment by MrCoolAndroid** [comment]
Thanks
