### ISSUE TITLE
Add: TokyoMX1

### ISSUE THREAD

**Issue by solo489** [iptv-org/iptv#15689]
### Channel ID (required)

JOMXDTV.jp

### Channel Name

Tokyo MX

### Stream URL (required)

http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=gd08

### Quality

576p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
https://github.com/iptv-org/iptv/blob/a70665586d285b281dd9f064c2827f7b5dd77512/streams/jp_primehome.m3u#L108-L109
