### ISSUE TITLE
Broken:  LRT Lituanica [LT]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/iptv#15684]
### Broken Link

https://lituanica.lrt.lt/lituanica/master.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Channel have new link: https://stream-live.lrt.lt/lituanica/stream03/streamPlaylist.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Yet another stream that works in everything but VLC? @BellezaEmporium @Alstruit

**Comment by BellezaEmporium** [comment]
> Yet another stream that works in everything but VLC? @BellezaEmporium @Alstruit 

Works in browser, as for VLC have to test

**Comment by Sphinxroot** [comment]
# https://www.lrt.lt/mediateka/tiesiogiai/lrt-lituanica
https://stream-live.lrt.lt/lituanica/master.m3u8
