### ISSUE TITLE
Add: AMC East | (US)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15696]
### Channel ID (required)

AMCEast.us

### Channel Name

AMC East

### Stream URL (required)

http://170.254.18.106/AMC/mono.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Note: Found more channels in there are not from the US but some are.

#EXTINF:-0, AXN
http://170.254.18.106/AXN/mono.m3u8

#EXTINF:-0, BET
http://170.254.18.106/BET/mono.m3u8

#EXTINF:-0, Bravo
http://170.254.18.106/BRAVO/mono.m3u8

#EXTINF:-0, Bounce
http://170.254.18.106/BOUNCE/mono.m3u8

#EXTINF:-0, Cinemax
http://170.254.18.106/CINEMAX/mono.m3u8

#EXTINF:-0, Comedy Central
http://170.254.18.106/COMEDY_CENTRAL/mono.m3u8

#EXTINF:-0, Discovery
http://170.254.18.106/DISCOVERY/mono.m3u8

#EXTINF:-0, Food Network
http://170.254.18.106/FOOD/mono.m3u8

#EXTINF:-0, GSN - (50/50)
http://170.254.18.106/GSN/mono.m3u8

#EXTINF:-0, Hallmark 
http://170.254.18.106/HALLMARK/mono.m3u8

#EXTINF:-0, HBO2
http://170.254.18.106/HBO2/mono.m3u8

#EXTINF:-0, HBO Family
http://170.254.18.106/HBO_FAMILY/mono.m3u8

#EXTINF:-0, HBO Mundi
http://170.254.18.106/HBO_MUNDI/mono.m3u8

#EXTINF:-0, HBO Pop
http://170.254.18.106/HBO_POP/mono.m3u8

#EXTINF:-0, HBO Xtreme
http://170.254.18.106/HBO_XTREME/mono.m3u8

#EXTINF:-0, History
http://170.254.18.106/HISTORY/mono.m3u8

#EXTINF:-0, Lifetime
http://170.254.18.106/LIFETIME/mono.m3u8

#EXTINF:-0, Magnolia Network (DIY Network)
http://170.254.18.106/MAGNOLIA/mono.m3u8

#EXTINF:-0, MeTV South Florida
http://170.254.18.106/ME_TV/mono.m3u8

#EXTINF:-0, MTV
http://170.254.18.106/MTV/mono.m3u8

#EXTINF:-0, NatGeo
http://170.254.18.106/NAT_GEO/mono.m3u8

#EXTINF:-0, Paramount Network
http://170.254.18.106/PARAMOUNT/mono.m3u8

#EXTINF:-0, USA? (SyFy)
http://170.254.18.106/USA/mono.m3u8

#EXTINF:-0, TBS
http://170.254.18.106/TBS/mono.m3u8

#EXTINF:-0, TCM
http://170.254.18.106/TCM/mono.m3u8

#EXTINF:-0, TLC
http://170.254.18.106/TLc/mono.m3u8

#EXTINF:-0, TNT
http://170.254.18.106/TNT/mono.m3u8

#EXTINF:-0, TELEHIT* MUSICA
http://170.254.18.106/TELEHIT/mono.m3u8

#EXTINF:-0, TruTV
http://170.254.18.106/TRUTV/mono.m3u8

#EXTINF:-0, USA
http://170.254.18.106/USA/mono.m3u8

#EXTINF:-0, VH1
http://170.254.18.106/VH1/mono.m3u8

**Comment by cometstyles** [comment]
you a-hoels do realise that you keep getting legitimate links  blocked/taken off by sharing them here right? once they leak the  people who run them kill them off completely or token them. not just these but every otehr listed on your site, most will be dead within a month or 2,  i knew some that ran for 3-4 years before being posted here and gone within a month.

**Comment by rushereeeeee** [comment]
@R4IN2007 there down already 😢
