### ISSUE TITLE
Add: Teleislas News – Raizal TV

### ISSUE THREAD

**Issue by cesarcorreag** [iptv-org/iptv#15699]
### Channel ID (required)

Raizal TV.es

### Channel Name

Raizal TV es

### Stream URL (required)

https://5ab772334c39c.streamlock.net/live-teleislas/_definst_/teleislas/chunklist_w540993111.m3u8

### Quality

None

### Label

None

### HTTP User Agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0

### HTTP Referrer

https://teleislas.gov.co/

### Notes

Teleislas News – Raizal TV: la señal de la comunidad de San Andrés Providencia y Santa Catalina

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Please add the necessary info into https://github.com/iptv-org/database according to [Contributing Guide](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md). An automated addition won't work without proper id and channel info
