### ISSUE TITLE
Add: TokyoMX1

### ISSUE THREAD

**Issue by solo489** [iptv-org/iptv#15700]
### Channel ID (required)

TokyoMX.jp

### Channel Name

Tokyo MX

### Stream URL (required)

http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=gd08

### Quality

None

### Label

None

### Notes

Please add it back on the playlist, I see nothing wrong with it.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
It is in the playlist
https://github.com/iptv-org/iptv/blob/cd84a26b9cd22514107bf66a79c9537bad0efc0d/streams/jp_primehome.m3u#L108-L109

**Comment by Dum4G** [comment]
It's currently using https://mcas-eqms-mx1-live.hls.davlive.stream.ne.jp/mt/master/340f27cd590451b1e7d0034b85b5175ddaf05454/EQMS_MX1/master.m3u8 which is also a decent link and maybe even the same source

**Comment by BellezaEmporium** [comment]
> It's currently using https://mcas-eqms-mx1-live.hls.davlive.stream.ne.jp/mt/master/340f27cd590451b1e7d0034b85b5175ddaf05454/EQMS_MX1/master.m3u8 which is also a decent link and maybe even the same source

Filtered stream, as MX Casting cuts the commercials and certain programs.

**Comment by solo489** [comment]
That's the problem of that stream, the jp_primehome.m3u stream works better.
