### ISSUE TITLE
Add: BBC First (Poland)

### ISSUE THREAD

**Issue by TestNintendo** [iptv-org/iptv#15704]
### Channel ID (required)

BBCFirst.pl

### Channel Name

BBC First (Poland)

### Stream URL (required)

https://cdn-main.lolokoko.tv/BBCHD.stream/playlist.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by fraudiay79** [comment]
I guess these will now be down in about a weeks time
