### ISSUE TITLE
Add: Fashion Finds / QVC 5 (QVC+ | HSN+)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15717]
### Channel ID (required)

FashionFinds.us

### Channel Name

Fashion Finds

### Stream URL (required)

https://qvc-amd-live.akamaized.net/hls/live/2034113/lsqvc5us/master.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Other channels lefted
#EXTINF:-0, Everyday Refresh / QVC 6 (QVC+ | HSN+)
https://qvc-amd-live.akamaized.net/hls/live/2034113/lsqvc6us/med.m3u8

#EXTINF:-0, QVC West
https://qvc-amd-live.akamaized.net/hls/live/2034113/lsqvc1uswest/med.m3u8

#EXTINF:-0, HSH West
https://qvc-amd-live.akamaized.net/hls/live/2034113/lshsn1uswest/med.m3u8

**Comment by Dum4G** [comment]
> Other channels lefted #EXTINF:-0, Everyday Refresh / QVC 6 (QVC+ | HSN+) https://qvc-amd-live.akamaized.net/hls/live/2034113/lsqvc6us/med.m3u8
> 
> #EXTINF:-0, QVC West https://qvc-amd-live.akamaized.net/hls/live/2034113/lsqvc1uswest/med.m3u8
> 
> #EXTINF:-0, HSH West https://qvc-amd-live.akamaized.net/hls/live/2034113/lshsn1uswest/med.m3u8

Are those having tvg-id?

**Comment by R4IN2007** [comment]
> > Other channels lefted #EXTINF:-0, Everyday Refresh / QVC 6 (QVC+ | HSN+) https://qvc-amd-live.akamaized.net/hls/live/2034113/lsqvc6us/med.m3u8
> > #EXTINF:-0, QVC West https://qvc-amd-live.akamaized.net/hls/live/2034113/lsqvc1uswest/med.m3u8
> > #EXTINF:-0, HSH West https://qvc-amd-live.akamaized.net/hls/live/2034113/lshsn1uswest/med.m3u8
> 
> Are those having tvg-id?

No
