### ISSUE TITLE
Add: Aggregator of TV channels from CIS countries (ru) based on your database

### ISSUE THREAD

**Issue by zloi-user** [iptv-org/iptv#15710]
### Channel ID (required)

playlist.md

### Channel Name

playlist

### Stream URL (required)

http://50na50.net/IPTV-list.m3u

### Quality

None

### Label

None

### Notes

Playlist update within an hour, non-working ones are deleted and new ones are added (tested in Moldova)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Idk if we can make use of it (some sources gonna die quickly if it gets indexed here) but anyway большое спасибо

**Comment by Dum4G** [comment]
I can move this to discussions if you wish so

**Comment by zloi-user** [comment]
> I can move this to discussions if you wish so

ok
