### ISSUE TITLE
Add: CBS (WTSP-DT) USA

### ISSUE THREAD

**Issue by JerkyHockey** [iptv-org/iptv#15719]
### Channel ID (required)

WTSPDT1.us

### Channel Name

CBS WTSPDT

### Stream URL (required)

https://cbsplaylistserver.aws.syncbak.com/mpl/20160401/859169/5743360/media.m3u8?request_token=qvU7-FK2v-GKFp6gT19Ca6OGg-7v2h3rb7CH8dJb24xGNa9SybZzeslmzXfSuKr8yvmFHpHArbAEAylrbjN8plkYyR_E_ONwoEO5VbCnWRbPltjgakUcV3v7Ap37IjAJykCk5YrCty_Hx7AsXhusoGCdNFX5UwEk7oT3u6_r2xG4QXk&CMCD=mtp%3D9500%2Cot%3Dm%2Csf%3Dh%2Csid%3D%224e546942-2006-495c-a946-06b8f3a0faca%22

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by JerkyHockey** [comment]
btw this is a cbs station in Tampa Bay, FL so yes it’s the actual stream so it’s in America not much info

**Comment by Dum4G** [comment]
surprisingly still alive

**Comment by TKList** [comment]
News only, not network, it looks like.

**Comment by JerkyHockey** [comment]
I checked it's not... I mean you 100% sure??

**Comment by JerkyHockey** [comment]
cause basically I got the stream from Paramount+ I checked and it was the actual stream.. that's werid

**Comment by TKList** [comment]
we shall see

**Comment by JerkyHockey** [comment]
![IMG_0753](https://github.com/iptv-org/iptv/assets/125172679/704bd2b5-b2bc-4927-b6b7-5f42ab4f542a)
Looks like it’s the actual stream ig..

**Comment by TKList** [comment]
Yup, thanks

**Comment by JerkyHockey** [comment]
Np man

**Comment by thepiratekitty** [comment]
oh… welp…

**Comment by ztnrf** [comment]
ya,,, its stopped now:(

**Comment by R4IN2007** [comment]
Works again

**Comment by TKList** [comment]
Stopped working

**Comment by R4IN2007** [comment]
?
![Screenshot_20240322_160156_Chrome](https://github.com/iptv-org/iptv/assets/83226646/63c1853b-2bb6-4eb8-b289-93a2f2e3b130)

**Comment by TKList** [comment]
LOL, just started working again. Thanks.

**Comment by rushereeeeee** [comment]
It’s probably because people watch the stream too much, probably because of March Madness or smth idk.. sometimes there’s gonna be too much traffic

**Comment by R4IN2007** [comment]
> It’s probably because people watch the stream too much, probably because of March Madness or smth idk.. sometimes there’s gonna be too much traffic

Yeah too much traffic because of March Madness.

**Comment by rushereeeeee** [comment]
it works fine on Stremium
![IMG_2783](https://github.com/iptv-org/iptv/assets/125172679/0fefa2a9-1f00-4bbe-8871-4b6d2a30557c)

**Comment by rushereeeeee** [comment]
sometimes I use stremium to bypass the traffic

**Comment by rushereeeeee** [comment]
Nvm I just noticed it wasnt wtsp

**Comment by rushereeeeee** [comment]
But still I have another backup link for CBS if you guys want it by any chance

**Comment by Spainguy77** [comment]
> But still I have another backup link for CBS if you guys want it by any chance

Sure, would appreciate a working link

**Comment by PR0XYCU8E** [comment]
doesn't work anymore

**Comment by rushereeeeee** [comment]
Idk. It still does for me apparently. Werid

**Comment by PR0XYCU8E** [comment]
it didn't work for me because the website's either banned or geo locked in france. just hse a vpn

**Comment by PR0XYCU8E** [comment]
use*

**Comment by rushereeeeee** [comment]
Oh its geo blocked cause it was ripped from Paramount+, I might get banned on their service for ripping their stuff, but enjoy it while it lasts

**Comment by rushereeeeee** [comment]
Yes it’s USA only* forgot to mention
