### ISSUE TITLE
Add: HSN

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15714]
### Channel ID (required)

HSN.us

### Channel Name

HSN

### Stream URL (required)

https://qvc-amd-live.akamaized.net/hls/live/2034113/lshsn1us/master.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
https://github.com/iptv-org/iptv/blob/16ed7e8819ff5df000ac31bc5bd1090603f70e99/streams/us.m3u#L1137

**Comment by Sphinxroot** [comment]
here what i got

#EXTINF:-1 tvg-id="",HSN
https://qvc-amd-live.akamaized.net/hls/live/2034113/lshsn1us/master.m3u8
#EXTINF:-1 tvg-id="",HSN2
https://qvc-amd-live.akamaized.net/hls/live/2034113/lshsn2us/master.m3u8
#EXTINF:-1 tvg-id="",QVC
https://qvc-amd-live.akamaized.net/hls/live/2034113/lsqvc1us/master.m3u8
#EXTINF:-1 tvg-id="",QVC 2
https://qvc-amd-live.akamaized.net/hls/live/2034113/lsqvc2us/master.m3u8
#EXTINF:-1 tvg-id="",QVC 3
https://qvc-amd-live.akamaized.net/hls/live/2034113/lsqvc3us/master.m3u8
#EXTINF:-1 tvg-id="",In The Kitchen
https://qvc-amd-live.akamaized.net/hls/live/2034113/lsqvc4us/master.m3u8
#EXTINF:-1 tvg-id="",Fashion Finds
https://qvc-amd-live.akamaized.net/hls/live/2034113/lsqvc5us/master.m3u8
#EXTINF:-1 tvg-id="",Everyday Refresh
https://qvc-amd-live.akamaized.net/hls/live/2034113/lsqvc6us/master.m3u8
