### ISSUE TITLE
Add: RTL Super

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15726]
### Channel ID (required)

RTLSuper.de

### Channel Name

RTL Super

### Stream URL (required)

http://livetv.ktv.zone/55/play.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by fraudiay79** [comment]
As always @R4IN2007 , thank you for killing off links that had been working for a while.

**Comment by FORSIZERO** [comment]
not work
