### ISSUE TITLE
Edit: Uncion TV

### ISSUE THREAD

**Issue by elvinag6** [iptv-org/iptv#15722]
### Channel ID (required)

UncionTV.us

### Channel Name

Uncion TV

### Stream URL (required)

https://livestreamhd.us/unciontv/live/playlist.m3u8

### Quality

1080p

### Label

None

### Timeshift

-6

### Notes

favor cambiar link m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
![image](https://github.com/iptv-org/iptv/assets/5430116/9ab968a1-4cf7-4f24-bb65-28da28c87ae5)
