### ISSUE TITLE
Add: RMC Story

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15731]
### Channel ID (required)

RMCStory.fr

### Channel Name

RMC Story

### Stream URL (required)

http://livetv.ktv.zone/25/play.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Best thing would be to put them into a single file named ch_knet.m3u to make sure they're all in it.

**Comment by R4IN2007** [comment]
Ok
