### ISSUE TITLE
Broken: Vietnamese channels using VThanhTivi 

### ISSUE THREAD

**Issue by kevle1** [iptv-org/iptv#15738]
### Broken Link

https://code.vthanhtivi.pw/getlink/tv360/jVDsoVLo5bOadF85xoCADA/1703112695/2/playlist.m3u8

### What happened to the stream?

Displays a message asking to renew subscription

### Notes (optional)

Streams in the [Vietnam playlist](https://github.com/iptv-org/iptv/blob/master/streams/vn.m3u) using `https://code.vthanhtivi.pw/getlink/tv360` as the source display a "Token is invalid or expired" message. 

https://github.com/search?q=repo%3Aiptv-org%2Fiptv+https%3A%2F%2Fcode.vthanhtivi.pw%2Fgetlink%2Ftv360&type=code

This occurs for:
- VTV 1,2,3,4,7,8,9
- VTV5 Tây Nguyên
- VTV Can Tho
- SCTV 6

URLs:
```
https://code.vthanhtivi.pw/getlink/tv360/ZgVzbvEDMkaZYK0hy5QBwQ/1703136086/232/playlist.m3u8
https://code.vthanhtivi.pw/getlink/tv360/jVDsoVLo5bOadF85xoCADA/1703112695/2/playlist.m3u8
https://code.vthanhtivi.pw/getlink/tv360/61Wz3kqiSswVJelJ341e_Q/1703112695/3/playlist.m3u8
https://code.vthanhtivi.pw/getlink/tv360/BCG35YDyyWW5Jtah0tlteQ/1703112695/4/playlist.m3u8
https://code.vthanhtivi.pw/getlink/tv360/QAbMGHDrIJQuFqBbDa4t5g/1703112695/108/playlist.m3u8
https://code.vthanhtivi.pw/getlink/tv360/D4tk_f8t_O_x_licrC6w6A/1703112695/207/playlist.m3u8
https://code.vthanhtivi.pw/getlink/tv360/9LzwDV0P_2EWifJDyjfIfg/1703112695/6/playlist.m3u8
https://code.vthanhtivi.pw/getlink/tv360/TlwS1PT59qPMHSJnBVNFWw/1703112695/115/playlist.m3u8
https://code.vthanhtivi.pw/getlink/tv360/M0He0D8y0BUpoPHcz-Is-A/1703112695/8/playlist.m3u8
https://code.vthanhtivi.pw/getlink/tv360/-VlG3Kl34fpGmcj0OpXJXw/1703112695/98/playlist.m3u8
```

![image](https://github.com/iptv-org/iptv/assets/36955177/d6ace72b-47e0-4606-a125-d3df8e9c9af4)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by user8387884** [comment]
same goes for me but says The given key 'en' was not present in the dictionary.
![Screenshot 2024-01-31 212905](https://github.com/iptv-org/iptv/assets/88836122/47617f95-834c-4542-bf68-bfd77c5f3a5d)
