### ISSUE TITLE
Upgrade Actions to Node 20.

### ISSUE THREAD

**Issue by BellezaEmporium** [iptv-org/iptv#15734]
### Describe your issue

![image](https://github.com/iptv-org/iptv/assets/30985701/ab48cc9b-7f7b-4375-8d6b-275ccb7a1ac7)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by guaymatetv** [comment]
https://glb.bozztv.com/glb/ssh101/guaymatetv/index.m3u8 GUAYMATE TV
