### ISSUE TITLE
Add: In The Box

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15742]
### Channel ID (required)

inthebox.vn

### Channel Name

In The Box

### Stream URL (required)

http://fpt.vthanhtivi.pw/In_The_Box/mpegts

### Quality

1080p

### Label

Geo-blocked

### Notes

vietnam channel, english sound, viet subtitles

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
![image](https://github.com/iptv-org/iptv/assets/5430116/83dbc784-e000-413d-8095-775f97f66fa0)
