### ISSUE TITLE
Add: Cinemax Asia?

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15757]
### Channel ID (required)

CinemaxAsia

### Channel Name

Cinemax Asia

### Stream URL (required)

http://fpt.vthanhtivi.pw/cinemax/index.m3u8

### Quality

None

### Label

None

### Notes

Don't know which id is for this channel

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
there's none yet. It's Vietnamese broadcast

**Comment by Dum4G** [comment]
@R4IN2007 please submit a new entry in database for vietnamese stream
