### ISSUE TITLE
Add: ANTV HD

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15754]
### Channel ID (required)

AnNinhTV.vn

### Channel Name

ANTV HD

### Stream URL (required)

https://liveh34.vtvcab.vn/hls/ONANTV_CL/04.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Please make sure that tvg-id is taken from https://iptv-org.github.io/ and exists, otherwise I may reject your submission

**Comment by Dum4G** [comment]
https://github.com/iptv-org/iptv/blob/742b9c77f05db936552214a00fe9511312e310a1/streams/vn.m3u#L2-L3
