### ISSUE TITLE
Add: KBS World (LAOS FEED)

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15750]
### Channel ID (required)

KBSWorld.kr

### Channel Name

KBS World HD

### Stream URL (required)

https://ctrl.laotv.la/live/KBS/index.m3u8

### Quality

1080p

### Label

None

### Notes

LAO-TV

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Any main differences between this stream and the KBS original stream ? Timeshift maybe ?

**Comment by user8387884** [comment]
how about this? : 
https://e4.endpoint.cdn.sctvonline.vn/hls/kbsworld/index.m3u8

**Comment by BellezaEmporium** [comment]
> how about this? : https://e4.endpoint.cdn.sctvonline.vn/hls/kbsworld/index.m3u8

Seems like it needs a specific referer.
