### ISSUE TITLE
Add: Update XEIPNTDT.mx stream URL

### ISSUE THREAD

**Issue by edvega** [iptv-org/iptv#15763]
### Channel ID (required)

XEIPNTDT.mx

### Channel Name

Canal Once

### Stream URL (required)

https://vivo.canaloncelive.tv/alivepkgr3/ngrp:cepro_all/playlist.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
https://github.com/iptv-org/iptv/blob/742b9c77f05db936552214a00fe9511312e310a1/streams/mx.m3u#L222-L223
