### ISSUE TITLE
Edit: Pokemon Kids TV Japanese is now Geo-Blocked

### ISSUE THREAD

**Issue by BoxxyDEV** [iptv-org/iptv#15766]
### Stream URL (required)

https://ythls.armelin.one/channel/UCH0JJtRn2syic5xxavMKQ4Q.m3u8

### Channel ID

PokemonKidsTVJapanese.jp

### Channel Name

Pokemon Kids TV Japanese

### Quality

None

### Label

Geo-blocked

### Notes

this link now only seems to work in Japan. Tested with proton tried Australia, & USA seems like its region locked now and only works when I VPN into Japan. it doesn't matter too much as this is just mirror of a [youtube live stream](https://www.youtube.com/watch?v=dwnIvUR9MwE)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Works in France too.

**Comment by Dum4G** [comment]
Not stable but it works
