### ISSUE TITLE
Add: La Capi TV

### ISSUE THREAD

**Issue by b4zz4** [iptv-org/iptv#15788]
### Channel ID (required)

LaCapi.TV

### Channel Name

La Capi TV

### Stream URL (required)

http://play.lacapi.tv/canal.m3u8

### Quality

720p

### Label

Animation, Vlog, Español

### HTTP Referrer

https://play.lacapi.tv/

### Notes

They are cartoons that I am developing, movies and short films free or public domain

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
![image](https://github.com/iptv-org/iptv/assets/5430116/998764c4-95b7-4315-b7eb-275d8f6fa365)
Please add your channel into https://github.com/iptv-org/database so we could add it here

**Comment by Dum4G** [comment]
Closing for now. If you manage to make it a publicaly available stream just edit this issue and ask to reopen

**Comment by b4zz4** [comment]
Hi, fix the mistakes.

**Comment by Dum4G** [comment]
Link provided doesn't work for me, even with refferer
![image](https://github.com/iptv-org/iptv/assets/5430116/98f6c73b-6bb9-4568-a838-f039b5e2eae6)

**Comment by b4zz4** [comment]
It works for me, won't it be the cache?

http://play.lacapi.tv/canal.m3u8?random

**Comment by Dum4G** [comment]
same story

**Comment by b4zz4** [comment]
tested in vlc or other player?

**Comment by Dum4G** [comment]
in vlc

**Comment by b4zz4** [comment]
please try again

**Comment by Dum4G** [comment]
Got it working, but still this is not what we considering a channel. You must run an actual stream on some server that will show your videos in schedule, as if it was on TV. We do not accept playlists here
