### ISSUE TITLE
Add: TODAY All Day (YouTube)

### ISSUE THREAD

**Issue by Hans5958** [iptv-org/iptv#15797]
### Channel ID (required)

TODAYAllDay.us

### Channel Name

TODAY All Day

### Stream URL (required)

https://ythls.armelin.one/channel/UChDKyKQ59fYz3JO2fl0Z6sg.m3u8

### Quality

720p

### Label

None

### Notes

Should I add the "Channel Name" even it is already listed on the database?

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
The way you name the channel will be shown in the playlist despite available entry in database

**Comment by Sphinxroot** [comment]
https://www.youtube.com/@TODAY/streams  Not 24/7

https://www.today.com/allday
https://mt.ssai-oneapp.nbcuni.com/Content/CMAF_OL1-CTR-4s/Live/channel(todayallday)/master.mpd?mt.config=nbcnews-atp-dash-linear-4s-generic

https://9f6bc946ffc84f39ba7761ec18f6d85f.mediatailor.us-east-1.amazonaws.com/v1/tracking/7f34bf1814de6fddce84b1e6c296b7a70243b88f/nbcnews-atp-dash-linear-4s-generic/133683bc-dbb2-46f2-b5d9-b22e8680f3e3

https://api.lightboxcdn.com/z9gd/44095/www.today.com/jsonp/z?cb=1707261114302&dre=l&callback=jQuery1124018460751165204514_1707261114292&_=1707261114293

epg
https://www.nbcnews.com/bentoapi/broadcastSchedules
