### ISSUE TITLE
Add: TV Puls

### ISSUE THREAD

**Issue by TestNintendo** [iptv-org/iptv#15792]
### Channel ID (required)

TVPuls.pl

### Channel Name

TV Puls

### Stream URL (required)

https://cdn-main.lolokoko.tv/TVPuls.stream/playlist.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
Sorry it’s wrong link

**Comment by TestNintendo** [comment]
but the issue is already closed
