### ISSUE TITLE
Add: HBO Asia

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15791]
### Channel ID (required)

HBOAsiaHD.sg

### Channel Name

HBO Asia HD

### Stream URL (required)

http://fpt.vthanhtivi.pw/hbo/index.m3u8

### Quality

1080p

### Label

None

### Timeshift

0

### Notes

PLEASE ADD IT TO PHILIPPINES, INDONESIA, AND MALAYSIA

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
![image](https://github.com/iptv-org/iptv/assets/5430116/8da1c247-4e32-432a-b656-343158e490a6)
Isn't that Vietnamese broadcast?
For availability changes make an edit request in https://github.com/iptv-org/database
Stream is already present in playlist
https://github.com/iptv-org/iptv/blob/6a1567b5389779a1225ec26793b7c29ad7e9c54f/streams/vn_vthanhtivi.m3u#L6-L7
