### ISSUE TITLE
Add: WNBC-DT

### ISSUE THREAD

**Issue by JerkyHockey** [iptv-org/iptv#15795]
### Channel ID (required)

WNBC.us

### Channel Name

WNBC (NBC 4 New York)

### Stream URL (required)

 https://v4.thetvapp.to/hls/WNBCDT1.m3u8?token=3eRHky9upA2BUHockx7LGw&expires=1707199535

### Quality

480p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by PR0XYCU8E** [comment]
doesn't work even with vpn for me
