### ISSUE TITLE
Update Urdu Language Channels in Language Category

### ISSUE THREAD

**Issue by SharyRajpoot** [iptv-org/iptv#1579]
In your repo. there are some channels that are wrong categorized like they are the same in actual but put on a different category.
like in the Pashto Language contains most of Urdu channels so need to update this as well.
I'm here leaving the source code again as I did before, just copy-paste on your side as you are owner/editor who can edit these files here on Github.
REMEMBER: From Pashto to the Urdu language

I took the data from
https://iptv-org.github.io/iptv/languages/undefined.m3u

#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/SrDafTA.jpg" tvg-country="PK" tvg-url="" group-title="",8X Music
https://playlive.goonj.pk/8xmweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/OA762pM.png" tvg-country="PK" tvg-url="" group-title="",Aaj Entertainment
https://playlive.goonj.pk/aajentweb_360p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/shVEz5N.jpg" tvg-country="PK" tvg-url="" group-title="",Aaj News
https://playlive.goonj.pk/aajnewsweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/HXLqT5G.jpg" tvg-country="PK" tvg-url="" group-title="",Aplus
https://playlive.goonj.pk/aplusweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/dOIqvce.jpg" tvg-country="PK" tvg-url="" group-title="",BOL Entertainment
https://playlive.goonj.pk/bolentweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/W2s0lGP.png" tvg-country="PK" tvg-url="" group-title="",BOL News
https://playlive.goonj.pk/bolweb_360p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/iqbsKgG.png" tvg-country="PK" tvg-url="" group-title="",BOL News
https://playlive.goonj.pk/bolweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/CePUeX6.jpg" tvg-country="PK" tvg-url="" group-title="",Dawn News
https://playlive.goonj.pk/dawnnewsweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/eL2pmZL.jpg" tvg-country="PK" tvg-url="" group-title="",Dunya
https://playlive.goonj.pk/dunyanewsweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/a5qvq5J.jpg" tvg-country="PK" tvg-url="" group-title="",Express Entertainment
https://playlive.goonj.pk/expressentweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/q85u7XS.jpg" tvg-country="PK" tvg-url="" group-title="",Film World
https://playlive.goonj.pk/filmworldweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/HKCvQAC.jpg" tvg-country="PK" tvg-url="" group-title="",Filmax
https://playlive.goonj.pk/filmaxweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/CkJpbom.jpg" tvg-country="PK" tvg-url="" group-title="",Geo Entertainment
https://playlive.goonj.pk/geoentweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/arBu6Kj.jpg" tvg-country="PK" tvg-url="" group-title="",Geo News
https://playlive.goonj.pk/geonewsweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/GRiJjs4.jpg" tvg-country="PK" tvg-url="" group-title="",Jalwa
https://playlive.goonj.pk/jalwaweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/ybHC32I.jpg" tvg-country="PK" tvg-url="" group-title="",Lahore News
https://playlive.goonj.pk/lahorenewsweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/5iaUgYc.jpg" tvg-country="PK" tvg-url="" group-title="",LTN Family
https://playlive.goonj.pk/ltnweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/Ig0hIeI.jpg" tvg-country="PK" tvg-url="" group-title="",Madani TV
https://playlive.goonj.pk/madnitvweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/XSMb4er.jpg" tvg-country="PK" tvg-url="" group-title="",Makkah Live
https://playlive.goonj.pk/makkahweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/4ZMTA9d.jpg" tvg-country="PK" tvg-url="" group-title="",Neo News
https://playlive.goonj.pk/neonewsweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/YjypzhE.jpg" tvg-country="PK" tvg-url="" group-title="",News One
https://playlive.goonj.pk/aajentweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://upload.wikimedia.org/wikipedia/en/e/e4/PTV_Sports.png" tvg-country="PK" tvg-url="" group-title="Sport",PTV Sports
http://95.211.211.168/live/ptvsports2002/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/XX1UPVL.jpg" tvg-country="PK" tvg-url="" group-title="",Public News
https://playlive.goonj.pk/publicnewsweb_480p/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="https://i.imgur.com/DXn57cB.jpg" tvg-country="PK" tvg-url="" group-title="",Samaa TV
https://playlive.goonj.pk/samaaweb_480p/index.m3u8

----------------------------------------------------------
You need to place this list inside Language > Urdu
https://iptv-org.github.io/iptv/languages/urd.m3u

**Comment by freearhey** [comment]
If you want to make any changes to your playlists, you can do so yourself by creating a pull request. Just read this guide before doing so: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#sort-channels-by-language
