### ISSUE TITLE
Add: Telemundo Corpus Christi (K22JA-D1) 47.1

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15793]
### Channel ID (required)

TelemundoCorpusChristi.us

### Channel Name

Telemundo Corpus Christi

### Stream URL (required)

https://content.uplynk.com/channel/b6a96ed39d694ae1b738faa98cf7dd3f.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Yesidpm** [comment]
Agregar rcn Colombia
