### ISSUE TITLE
Add: Nickelodeon Asia

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15808]
### Channel ID (required)

Nickelodeon.id

### Channel Name

Nickelodeon Asia

### Stream URL (required)

http://152.89.62.76:8880/48msk050022/92297813/60344

### Quality

576p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
![image](https://github.com/iptv-org/iptv/assets/5430116/d3cbf2a6-0080-4d87-abb4-6ca3ab15213d)
