### ISSUE TITLE
Add: Nick Jr HD

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15809]
### Channel ID (required)

NickJrAsiaHD.id

### Channel Name

Nick Jr Asia HD

### Stream URL (required)

http://152.89.62.76:8880/48msk050022/92297813/60481

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by thepiratekitty** [comment]
@Dum4G

**Comment by Dum4G** [comment]
Indeed it is
![image](https://github.com/iptv-org/iptv/assets/5430116/00b1d82b-6875-41b4-853c-1297f439f6ea)
