### ISSUE TITLE
Add: MTV 90s Asia

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15803]
### Channel ID (required)

MTV90s.ph

### Channel Name

MTV 90's

### Stream URL (required)

https://code.vthanhtivi.pw/getlink/eazie/243116/playlist.m3u8

### Quality

576p

### Label

None

### Notes

ph version without the cignal feed

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ozgurkazancci** [comment]
This is not MTV 90s. It's a fake stream.

**Comment by Rguanchez** [comment]
Este Es FALSO

**Comment by Rguanchez** [comment]
Is FAKE

**Comment by Rguanchez** [comment]
fake?
