### ISSUE TITLE
Add: TRT World Asia HD

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15804]
### Channel ID (required)

TRTWorldHD.tr

### Channel Name

TRT World HD (English)

### Stream URL (required)

https://tv-trtworld.live.trt.com.tr/master.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
https://github.com/iptv-org/iptv/blob/5a38430e58784e5222fa706dca2ecb5acc53556e/streams/tr.m3u#L422-L423
