### ISSUE TITLE
Add: Comedy Central [USA]

### ISSUE THREAD

**Issue by thepiratekitty** [iptv-org/iptv#15802]
### Channel ID (required)

ComedyCentral.us

### Channel Name

Comedy Central East

### Stream URL (required)

http://170.254.18.106/COMEDY_CENTRAL/mono.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by thepiratekitty** [comment]
Also credits for R4IN2007 for the streams

**Comment by Dum4G** [comment]
The stream kicks me out after 10s, is it worthy?

**Comment by Dum4G** [comment]
@BellezaEmporium @Alstruit

**Comment by BellezaEmporium** [comment]
Flussonic host, works OK for me so far.

**Comment by thepiratekitty** [comment]
No it works fine for me?

**Comment by thepiratekitty** [comment]
anyways I’ll find more streams later

**Comment by R4IN2007** [comment]
Found the main stream for Comedy Central
They change from content.uplynk.com to dai.google.com

Comedy Central | (US)
https://dai.google.com/linear/hls/event/BAO5IIgoQ7SKbSH_ww-rkA/master.m3u8

If needed
MTV | (US)
https://dai.google.com/linear/hls/event/sD3A_DrQSgW6Y7NnVl5ioQ/master.m3u8

BET | (US)
https://dai.google.com/linear/hls/event/5lqWhJiPQHiu4MdsBs_Uvw/master.m3u8

VH1  | (US)
https://dai.google.com/linear/hls/event/1y0cp2AXQQSHpFOs8LjCUA/master.m3u8

Paramount Network | (US)
https://dai.google.com/linear/hls/event/_P1-pj5tRB2p-LniOQUhUg/master.m3u8

**Comment by fraudiay79** [comment]
Paramount and MTV are already down. Thanks @R4IN2007, you killed another source. You are the best!!!

**Comment by thepiratekitty** [comment]
Something bads about to happen… oh no

**Comment by spotanjo3** [comment]
http://170.254.18.106/COMEDY_CENTRAL/mono.m3u8 works but it didnt have closed captioning.

Do you have another one that enable with closed captioning ? I checked and Comedy Central supports hearing impaired, indeed.

**Comment by rushereeeeee** [comment]
No sadly

**Comment by spotanjo3** [comment]
That sucks. I found one through iIPTV provider with a link m3u8 and it has a closed captioning. I dont understand why this one doesn't.

**Comment by rushereeeeee** [comment]
ya sure it will work tho?

**Comment by rushereeeeee** [comment]
It’s the only one we have for now

**Comment by R4IN2007** [comment]
http://38.96.178.201:80/live/ComedyCentral/index.m3u8 Thiz one had Closed Captions but it's dead now.

**Comment by R4IN2007** [comment]
Got one that has CC's working in VLC.
![Screenshot_20240415_135633_VLC](https://github.com/iptv-org/iptv/assets/83226646/a242be64-7198-4a0d-88ea-fee448d9278c)

**Comment by spotanjo3** [comment]
Oh no, its dead already.
