### ISSUE TITLE
Add: Relevant TV Israel

### ISSUE THREAD

**Issue by adinaveh** [iptv-org/iptv#15807]
### Channel ID (required)

RelevantTV.il

### Channel Name

Relevant TV

### Stream URL (required)

https://6180c994cb835402.mediapackage.eu-west-1.amazonaws.com/out/v1/06e44cd7f7e0445fbd669f279c997fd4/index.mpd

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Please add your channel into https://github.com/iptv-org/database so we could add it here
