### ISSUE TITLE
Broken: HiperconectadosTV.cl

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#15816]
### Broken Link

https://mediacpstreamchile.com:1936/hiperconectados/hiperconectados/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Updated link: https://stmv5.voxtvhd.com.br/hiperconectados/hiperconectados/playlist.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
I'm approvin removal. Please readd the channel in a new issue
