### ISSUE TITLE
Broken: Memorias TV

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#15813]
### Broken Link

https://mediacp.us:8081/8002/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Updated link: https://stmv6.voxtvhd.com.br/memoriastv/memoriastv/playlist.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
I'm approvin removal. Please readd the channel in a new issue
