### ISSUE TITLE
Add: Deutsche Welle Asia??? (maybe)

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15810]
### Channel ID (required)

dw.us

### Channel Name

Deutsche Welle Asia

### Stream URL (required)

https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/stream05/streamPlaylist.m3u8

### Quality

1080p

### Label

Geo-blocked

### Notes

found on a philippine website called: PHCorner, although the souce post is now private or deleted

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Would tend to say that's the classical DW English stream.

**Comment by BellezaEmporium** [comment]
https://github.com/iptv-org/iptv/blob/5a38430e58784e5222fa706dca2ecb5acc53556e/streams/de.m3u#L86-L87
