### ISSUE TITLE
Broken: Audio Dungeon | (US)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15824]
### Broken Link

https://content.uplynk.com/channel/5688add7ce704ce1a27ab62bb44044b9.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

https://stream-us-east-1.getpublica.com/playlist.m3u8?network_id=2580
found this and is working fine
![image](https://github.com/iptv-org/iptv/assets/83226646/c8ae9983-0769-4cb4-8a9e-a4e406a57825)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
I'm approvin removal. Please readd the channel in a new issue
