### ISSUE TITLE
Add: Bein Sports 1 Philippines

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15839]
### Channel ID (required)

beINSports1.ph

### Channel Name

Bein Sports 1

### Stream URL (required)

https://ctrl.laotv.la/live/Bsport1/index.m3u8

### Quality

1280p

### Label

None

### Notes

would say

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
😔
https://github.com/iptv-org/database/blob/9f24fa13c1bee9504d5dd19606761807f197acc8/data/blocklist.csv#L117
