### ISSUE TITLE
Broken: Iranian channels

### ISSUE THREAD

**Issue by TwistedA** [iptv-org/iptv#15831]
### Broken Link

https://iptv-org.github.io/iptv/countries/ir.m3u

### What happened to the stream?

Not loading

### Notes (optional)

Almost all of the 136 channels in Iranian channels are broken im not asking for them to be fixed or anything just wanted to inform u about this and ty for making this :)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by arash12100** [comment]
Hi
Please the broken link for Iran International and Persiana Nostalgia🙏🙏🙏
