### ISSUE TITLE
Add: Audio Dungeon

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15832]
### Channel ID (required)

AudioDungeon.us

### Channel Name

Audio Dungeon

### Stream URL (required)

https://stream-us-east-1.getpublica.com/playlist.m3u8?network_id=2580

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
@R4IN2007 @BellezaEmporium Does it play in VLC? Endlessly trying to load a chunk for me, possibly fails to play ads

**Comment by BellezaEmporium** [comment]
Same. Answers but it doesn't get through.

**Comment by R4IN2007** [comment]
yeah about that. i was trying play this ottera m3u8 in VLC and it doesn't load but if played in browser works?
![image](https://github.com/iptv-org/iptv/assets/83226646/9e3e83c7-21f9-4346-a1d9-960bd126210c)

**Comment by R4IN2007** [comment]
https://www.distro.tv/live/dungeon-tv/
https://watch.plex.tv/live-tv/channel/dungeon-tv-2

https://epg.provider.plex.tv/library/parts/5e20b730f2f8d5003d739db7-6216723e2c2627c068e73ad4.m3u8?includeAllStreams=1&X-Plex-Product=Plex+Mediaverse&X-Plex-Token=JUQPi3yyPdKYmvfHzQ_U
![image](https://github.com/iptv-org/iptv/assets/83226646/89666280-b4a5-473f-ab8d-f5ff18ea5db3)

**Comment by BellezaEmporium** [comment]
> https://www.distro.tv/live/dungeon-tv/ https://watch.plex.tv/live-tv/channel/dungeon-tv-2
> 
> https://epg.provider.plex.tv/library/parts/5e20b730f2f8d5003d739db7-6216723e2c2627c068e73ad4.m3u8?includeAllStreams=1&X-Plex-Product=Plex+Mediaverse&X-Plex-Token=JUQPi3yyPdKYmvfHzQ_U ![image](https://private-user-images.githubusercontent.com/83226646/303916370-89666280-b4a5-473f-ab8d-f5ff18ea5db3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NTI4MDQsIm5iZiI6MTcwNzY1MjUwNCwicGF0aCI6Ii84MzIyNjY0Ni8zMDM5MTYzNzAtODk2NjYyODAtYjRhNS00NzNmLWFiOGQtZjVmZjE4ZWE1ZGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDExNTUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMGE1YWRiMmZiYjZjNjM3NzYyYjdjMjY0NzhlZDhlN2RlZjk3Nzg1NmYxNDdkMzkwYWJkNzc4Y2E5Yzc5OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IFEdWD3zGMfGmCJ-rAYPgsTnbllTivtpqcfatoZ5S5g)

Tokened with anonymous auth at each access to plex.tv
