### ISSUE TITLE
Add: Bridezillas Runtime | (UK)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15830]
### Channel ID (required)

Bridezillas.uk

### Channel Name

Bridezillas

### Stream URL (required)

https://run-br-uk.otteravision.com/run/br_uk/br_uk_720.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
![image](https://github.com/iptv-org/iptv/assets/5430116/5875f97b-798d-4e15-a185-1c4e8c569c8a)

**Comment by R4IN2007** [comment]
Oops I cut off the .m3u8
