### ISSUE TITLE
Add: bTV

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#15849]
### Channel ID (required)

bTV.bg

### Channel Name

bTV HD

### Stream URL (required)

https://vd5.bweb.bg/live/XXT69hpRDqs59AAJTmOKsA/1707808028/61065646.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
403, possibly xstream codes

**Comment by R4IN2007** [comment]
https://btvplus.bg/live/
m3u8 link changes
