### ISSUE TITLE
Add: MYX

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15840]
### Channel ID (required)

 MyxPhilippines.ph

### Channel Name

MYX Philippines 

### Stream URL (required)

 https://myxnola-abscbn-ono.amagi.tv/index.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by user8387884** [comment]
bilis naman

**Comment by BellezaEmporium** [comment]
I have a doubt. Is it https://en.wikipedia.org/wiki/Myx_(American_TV_channel) (being in Amagi) as in MyxUSA.us

Or is it a **specific** Filipino stream as in https://en.wikipedia.org/wiki/Myx / MyxPhilippines.ph ?

Both of them are maintained by ABS/CBN.
