### ISSUE TITLE
Broken: Some channel broken after update of ipstreet312/freeiptv

### ISSUE THREAD

**Issue by TheBlackReverand** [iptv-org/iptv#15843]
Hello,

The git repo [ipstreet312/freeiptv](https://github.com/ipstreet312/freeiptv/tree/master) have change to use an all.m3u file.

The link for channel Gulli on file https://github.com/iptv-org/iptv/blob/master/streams/fr.m3u is down.

The new URL is https://raw.githubusercontent.com/ipstreet312/freeiptv/master/ressources/rtlm6/directmaster/gullihd.m3u8

I can generate PR but don't have ability to create branch.

Maybe more channel down.

Regards.

**Comment by TheBlackReverand** [comment]
I start a fork with update branch
https://github.com/TheBlackReverand/iptv/tree/feature/update-fr

**Comment by Dum4G** [comment]
Can't verify Tf1 for now. As of Gulli you can create two issues. One to remove curent broken stream and another one to add new link

**Comment by MapGuy11** [comment]
It's tokenized I don't believe it will work as I am getting a 403 error.

**Comment by TheBlackReverand** [comment]
Thanks.

I create issues for Gulli but TF1 not work again.

I don't known where I can find m3u8 URL but If someone have tuto on it I'm interrested.

for now I close this issues.

Regards
