### ISSUE TITLE
Add: In The Box

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15853]
### Channel ID (required)

inthebox.vn

### Channel Name

In The Box (ViettelTV)

### Stream URL (required)

 https://ott3.khanggtivi.xyz/source/bmktv09/698374/tv360/aDRvYzJrNW0xR0RmeHRvR3A1dUNDZVM3SHZMai9uVWNCQW1SOVdhL1VaUHo0YWNwcmszUDBUb2ducHlPUjl6RUVacmlOUWx4SDNrbjJVK3BiL29hYURWckFPazhNM2dYWTBKbEhzWjBEMGM9/2.m3u8?live=235

### Quality

1080p

### Label

None

### Notes

please  note that the m3u url is owned by: https://www.vthanhnetwork.com/tivi-online and found source by this: https://khanggtivi.xyz/xem-truyen-hinh/bmktv09/698374/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
![image](https://github.com/iptv-org/iptv/assets/5430116/aaf78fa3-e33e-47c9-8f69-f53b83333582)

**Comment by user8387884** [comment]
> ![image](https://private-user-images.githubusercontent.com/5430116/304375321-aaf78fa3-e33e-47c9-8f69-f53b83333582.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjMzMjEsIm5iZiI6MTcwNzgyMzAyMSwicGF0aCI6Ii81NDMwMTE2LzMwNDM3NTMyMS1hYWY3OGZhMy1lMzNlLTQ3YzktOGY2OS1mNTNiODMzMzM1ODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTNUMTExNzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmNiNGQwMWNmZmM2MzgyY2JhYzRjMWNlODZiZTA4NDhlYmQ5MGJjYmE2ZTYxMTkxMTFkNzlkMTg4ZmIwYTFjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mDt39On00r33y1xe90PKGNRdJeChRb76dXC6-N604KI)

just remove the index.m3u8

**Comment by user8387884** [comment]
its working for mine
