### ISSUE TITLE
TF1 channel not working

### ISSUE THREAD

**Issue by Abdi-Arslene** [iptv-org/iptv#15855]
### Describe your issue

Hello guys, 
So i noticed that TF1 channel from France is not working anymore. Can you do something to fix that ? 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Related to https://github.com/iptv-org/iptv/issues/15843. If you want to report broken stream for removal use "Broken stream" template
