### ISSUE TITLE
Add: Stup- I mean Happy Kids

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15854]
### Channel ID (required)

HappyKidsHD.m3u

### Channel Name

Happy Kids (INTHEBOX.VN)

### Stream URL (required)

 https://ott3.khanggtivi.xyz/source/bmktv09/698374/tv360/aDRvYzJrNW0xR0RmeHRvR3A1dUNDZVM3SHZMai9uVWNCQW1SOVdhL1VaUHo0YWNwcmszUDBUb2ducHlPUjl6RUVacmlOUWx4SDNrbjJVK3BiL29hYURWckFPazhNM2dYWTBKbEhzWjBEMGM9/2.m3u8?live=212

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
![image](https://github.com/iptv-org/iptv/assets/5430116/7408d9f5-7b15-4ca0-adc2-f0200543ceec)
