### ISSUE TITLE
Broken: TF1 stream broken in ch_knet.m3u file

### ISSUE THREAD

**Issue by TheBlackReverand** [iptv-org/iptv#15859]
### Broken Link

http://livetv.ktv.zone/3/play.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by KevinPfeiffer** [comment]
I have the same problem with Arte FR, also on ch_knet.m3u.

**Comment by huguesdelamure** [comment]
Sorry guys, but streams were not intended to be public, they fixed the issue few days ago : https://lafibre.info/k-net-fibre/k-net-en-redressement-judiciaire-012024-et-cessation-de-paiement-122023/msg1055842/#msg1055842

**Comment by BellezaEmporium** [comment]
Streams removed.
