### ISSUE TITLE
Add: Animax

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15856]
### Channel ID (required)

animaxhd.vn

### Channel Name

Animax HD

### Stream URL (required)

 https://ott3.khanggtivi.xyz/source/bmktv09/698374/quocte/vstv209/index.m3u8

### Quality

1080p

### Label

Geo-blocked

### Notes

go use vpn, i think you used your ip too long

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Simple redir to something else : http://fpt.vthanhtivi.pw/animax/index.m3u8
