### ISSUE TITLE
Fox News (GSE only) no longer available 

### ISSUE THREAD

**Issue by UTC-John** [iptv-org/iptv#1586]
**What's wrong? Fox News has gone missing

**Country of the channel: USA

**Channel Name: Fox News (GSE Only)

**Broken Link:**

**Additional Information (optional): It had been working beautifully but it has suddenly disappeared. It is / was the only channel I watched. It would start but quick hand at 3:06 pm ET for the clock on the screen.

**Comment by SileC** [comment]
Stuck in a loop from today. Need new link.

**Comment by freearhey** [comment]
Closed in favor #1942
