### ISSUE TITLE
Add: Add Gulli FR

### ISSUE THREAD

**Issue by TheBlackReverand** [iptv-org/iptv#15861]
### Channel ID (required)

Gulli.fr

### Channel Name

Gulli

### Stream URL (required)

https://origin2-6play.live.6cloud.fr/pool_rnpls9by/gulli/sixplaysd/hls_short_q2hyb21h_gulli/index.m3u8

### Quality

540p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
https://github.com/iptv-org/iptv/blob/5770fca4f420b29bbec34dc12f60e97337c6667d/streams/fr_groupem6.m3u#L3
