### ISSUE TITLE
Add: Pingviins [LV]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/iptv#15872]
### Channel ID (required)

Pingviins.lv

### Channel Name

Pingvīns

### Stream URL (required)

https://void.greenhosting.ru/PingvinsLV_Mpeg4/index.m3u8

### Quality

576p

### Label

None

### Notes

Stream link was removed due remove LoloTV.lv, and need's back.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Geo-blocked to Latvia only

**Comment by Dum4G** [comment]
It wasn't
https://github.com/iptv-org/iptv/blob/62883ff60e76c78a2f2ae92e985eb2d38cdc326e/streams/lv.m3u#L14-L15
Needs rather proper tvg-id and name in pl itself

**Comment by DJ1999-max** [comment]
Ok...
