### ISSUE TITLE
Add: Puls 2

### ISSUE THREAD

**Issue by TestNintendo** [iptv-org/iptv#15879]
### Channel ID (required)

Puls2.pl

### Channel Name

Puls 2

### Stream URL (required)

https://cdn-main.lolokoko.tv/TVPuls2.stream/playlist.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by campones** [comment]
the whole domain  is timing out now.
