### ISSUE TITLE
American/Canadian channel additions

### ISSUE THREAD

**Issue by Theitfixer85** [iptv-org/iptv#1587]
**Country of the channel:**
USA
Canada

**Channel Name:**
ABC Eastern/New York eg WABC-TV
Fox Eastern (not local news actual fox network) 
GSN (Game show network) (USA or Canada) 
CTV (Canada) (CTV1 and CTV2) 

**Channel Language:**
English

**Comment by Sphinxroot** [comment]
ctv news = segmented stream from : https://www.ctvnews.ca/live?autoPlay=true
ctv 1  and 2 = Choose your TV service provider to get access to live streaming and more 
content. will be surely fragmented or expirable link 

ABC (ABC7) NewYork .. from site  tokenized stream

found this one working
#EXTINF:-1 tvg-logo="https://cloudfront-us-east-1.images.arcpublishing.com/raycom/HJ3SAXRMNFAHXOFIRVYCQBIOGM.jpg" group-title="",ABC (ABC7)
https://d2nt5wxzqbe1ad.cloudfront.net/out/raycom-wwsb1-hls/live.m3u8

abc news from site = geo

**Comment by Theitfixer85** [comment]
> ctv news = segmented stream from : https://www.ctvnews.ca/live?autoPlay=true
> ctv 1 and 2 = Choose your TV service provider to get access to live streaming and more
> content. will be surely fragmented or expirable link
> 
> ABC (ABC7) NewYork .. from site tokenized stream
> 
> found this one working
> #EXTINF:-1 tvg-logo="https://cloudfront-us-east-1.images.arcpublishing.com/raycom/HJ3SAXRMNFAHXOFIRVYCQBIOGM.jpg" group-title="",ABC (ABC7)
> https://d2nt5wxzqbe1ad.cloudfront.net/out/raycom-wwsb1-hls/live.m3u8
> 
> abc news from site = geo

Hi thanks for the Abc7 link - I will check it out throughout the day to make sure it's stable and correct channel but it is working 

CTV I was looking for CTV1 not the news sorry and since I'm not in Canada can't be geo locked (for convenience) 

Thanks for looking for me

**Comment by Theitfixer85** [comment]
I can confirm that the ABC link provided is ABC7 Sarasota Florida WWSB

Would be good if someone also had ABC7 New York WABC-TV

**Comment by Sphinxroot** [comment]
here a couple more  byt sorry didnt find new york yet

#EXTINF:-1,United States: ABC 10 Miami FL (WPLG)
http://190.80.3.28/ABC/ABC.isml/index.m3u8
#EXTINF:-1,United States: ABC 2 Baton Rouge LA (WBRZ-HD)
http://cms-wowza.lunabyte.io/wbrz-live-1/_definst_/smil:wbrz-live.smil/chunklist_b1300000.m3u8
#EXTINF:-1,United States: ABC 2 Baton Rouge LA (WBRZ-HD)
http://cms-wowza.lunabyte.io/wbrz-live-1/_definst_/smil:wbrz-live.smil/chunklist_b1300000.m3u8
#EXTINF:-1,United States: ABC 7 Sarasota FL (WWSB)
https://d2nt5wxzqbe1ad.cloudfront.net/out/raycom-wwsb1-hls/live.m3u8
#EXTINF:-1,United States: ABC 9 Chattanooga TN (WTVC)
http://wxintribune-lh.akamaihd.net/i/WXINTribune_1@120151/master.m3u8
#EXTINF:-1,United States: ABC 9 Orlando FL (WFTV-HD)
http://svc-lvanvato-cxtv-wftv.cmgvideo.com/wftv/2564k/index.m3u8
#EXTINF:-1,United States: ABC News Digital 1
https://abclive1-lh.akamaihd.net/i/abc_live01@423395/master.m3u8
#EXTINF:-1,United States: ABC News Digital 10
https://abclive1-lh.akamaihd.net/i/abc_live10@420897/master.m3u8
#EXTINF:-1,United States: ABC News Digital 2
https://abclive1-lh.akamaihd.net/i/abc_live02@423396/master.m3u8
#EXTINF:-1,United States: ABC News Digital 3
https://abclive1-lh.akamaihd.net/i/abc_live03@423397/master.m3u8
#EXTINF:-1,United States: ABC News Digital 4
https://abclive1-lh.akamaihd.net/i/abc_live04@423398/master.m3u8
#EXTINF:-1,United States: ABC News Digital 5
https://abclive1-lh.akamaihd.net/i/abc_live05@423399/master.m3u8
#EXTINF:-1,United States: ABC News Digital 6
https://abclive1-lh.akamaihd.net/i/abc_live06@423400/master.m3u8
#EXTINF:-1,United States: ABC News Digital 7
https://abclive1-lh.akamaihd.net/i/abc_live07@423401/master.m3u8
#EXTINF:-1,United States: ABC News Digital 8
https://abclive1-lh.akamaihd.net/i/abc_live08@423402/master.m3u8
#EXTINF:-1,United States: ABC News Digital 9
https://abclive1-lh.akamaihd.net/i/abc_live09@420891/master.m3u8

**Comment by Theitfixer85** [comment]
> http://svc-lvanvato-cxtv-wftv.cmgvideo.com/wftv/2564k/index.m3u8

Thanks I tested these
ABC 10 doesn't work for me - might be geo locked
ABC 7 as mentioned before is good
ABC 9 Chattanooga I think is already in the us m3u and is poor quality and I think just has local news rather than network programming
ABC 9 Orlando FL doesn't work for me

**Comment by Sphinxroot** [comment]
for ctv news : 
http://pe-ak-lp01a-9c9media.akamaized.net/live/News1BNNDigi/p/dash/00000001/1bba52dc66e4c68e/manifest.mpd

but since im using kodi ..  i have to put this is  in a .strm file  in \userdata\playlists\video  .. to work 

file : CTVNews.strm 

Code:
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
http://pe-ak-lp01a-9c9media.akamaized.net/live/News1BNNDigi/p/dash/00000001/1bba52dc66e4c68e/manifest.mpd

other thing i do for some stream that cant be added to kodi  , i use firefox whit the plugin cast to kodi from any device over the local network

**Comment by Theitfixer85** [comment]
> for ctv news :
> http://pe-ak-lp01a-9c9media.akamaized.net/live/News1BNNDigi/p/dash/00000001/1bba52dc66e4c68e/manifest.mpd
> 
> but since im using kodi .. i have to put this is in a .strm file in \userdata\playlists\video .. to work
> 
> file : CTVNews.strm
> 
> Code:
> #KODIPROP:inputstreamaddon=inputstream.adaptive
> #KODIPROP:inputstream.adaptive.manifest_type=mpd
> http://pe-ak-lp01a-9c9media.akamaized.net/live/News1BNNDigi/p/dash/00000001/1bba52dc66e4c68e/manifest.mpd
> 
> other thing i do for some stream that cant be added to kodi , i use firefox whit the plugin cast to kodi from any device over the local network

Looks like this channel may only work with software playback - hardware playback on my phone gives a very choppy picture but might just be my phone 

I'm not looking for news channels though just the main network channels - in CTV case this is CTV1 and CTV2

Thanks for looking though

**Comment by freearhey** [comment]
Closed in favor #1942 and #1941
