### ISSUE TITLE
Add: AMC [USA]

### ISSUE THREAD

**Issue by crak3rjack** [iptv-org/iptv#15889]
### Channel ID (required)

AMC.us

### Stream URL (required)

http://170.254.18.106/AMC/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Could be AMCWest.us

**Comment by spotanjo3** [comment]
Its dead.
