### ISSUE TITLE
Add: BRAVO [USA]

### ISSUE THREAD

**Issue by crak3rjack** [iptv-org/iptv#15891]
### Channel ID (required)

BRAVO.us

### Stream URL (required)

http://170.254.18.106/BRAVO/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by spotanjo3** [comment]
Its dead. New link please?
