### ISSUE TITLE
Add: HBO XTREME [USA]

### ISSUE THREAD

**Issue by crak3rjack** [iptv-org/iptv#15898]
### Channel ID (required)

HBOXtream.us

### Stream URL (required)

http://170.254.18.106/HBO_XTREME/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by fraudiay79** [comment]
I don't trust these 'contributors' with no real GitHub history that start providing links for paid/subscription channels. Please stop submitting channels that might get this repo get taken down.
