### ISSUE TITLE
Add: HBO 2 [USA]

### ISSUE THREAD

**Issue by crak3rjack** [iptv-org/iptv#15895]
### Channel ID (required)

HBO2.us

### Stream URL (required)

http://170.254.18.106/HBO2/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by spotanjo3** [comment]
Its in Spanish. X_X
