### ISSUE TITLE
Add: BET [USA]

### ISSUE THREAD

**Issue by crak3rjack** [iptv-org/iptv#15890]
### Channel ID (required)

BET.us

### Stream URL (required)

http://170.254.18.106/BET/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by spotanjo3** [comment]
Its not working. New link please?
