### ISSUE TITLE
Add: COOKING CHANNEL [USA]

### ISSUE THREAD

**Issue by crak3rjack** [iptv-org/iptv#15893]
### Channel ID (required)

CookingChannel.us

### Stream URL (required)

http://170.254.18.106/COOKING/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by rushereeeeee** [comment]
bro your going to kill off these streams, good job
