### ISSUE TITLE
Add: HBO FAMILY [USA]

### ISSUE THREAD

**Issue by crak3rjack** [iptv-org/iptv#15896]
### Channel ID (required)

HBOFamily.us

### Stream URL (required)

http://170.254.18.106/HBO_FAMILY/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by user8387884** [comment]
does not load.

**Comment by user8387884** [comment]
@Dum4G

**Comment by Dum4G** [comment]
![image](https://github.com/iptv-org/iptv/assets/5430116/fb3936f0-e1b3-432d-b317-9feadc8f928c)

Disconnects me after a while

**Comment by spotanjo3** [comment]
It's working but its not in English. Its in Spanish.
