### ISSUE TITLE
Add: HBO MUNDI [USA]

### ISSUE THREAD

**Issue by crak3rjack** [iptv-org/iptv#15897]
### Channel ID (required)

HBOMundi.us

### Stream URL (required)

http://170.254.18.106/HBO_MUNDI/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
HBO Mudi & Xtreme ain't from the US.
Latin America streams?
