### ISSUE TITLE
Add: LIFETIME [USA]

### ISSUE THREAD

**Issue by crak3rjack** [iptv-org/iptv#15901]
### Channel ID (required)

Lifetime.us

### Stream URL (required)

http://170.254.18.106/LIFETIME/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Lifetime but it's from somewhere else.
