### ISSUE TITLE
Add: YES NETWORK [USA]

### ISSUE THREAD

**Issue by crak3rjack** [iptv-org/iptv#15906]
### Channel ID (required)

YesNetwork.us

### Stream URL (required)

https://dfwlive-v1-c2p1-sponsored.akamaized.net/Content/HLS.cps/Live/channel(YESOM-1000287.dfw.720)/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by lrm864** [comment]
DirecTV and DRM. You're getting nowhere.

**Comment by lrm864** [comment]
> Even if it wasn't DRM'd, that's actually their stream for YES National which doesn't have any Yankees, Nets or Liberty games.

Exactly. OM means Out of Market.
