### ISSUE TITLE
Discovery Channel

### ISSUE THREAD

**Issue by BogartDabid** [iptv-org/iptv#15910]
### Channel ID (required)

DiscoveryChannel.ph

### Channel Name

Discovery Channel

### Stream URL (required)

http://38.96.178.201:80/live/Discovery/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by maddixmhn** [comment]
not working
