### ISSUE TITLE
Disney XD

### ISSUE THREAD

**Issue by BogartDabid** [iptv-org/iptv#15912]
### Channel ID (required)

DisneyXDEast.us

### Channel Name

Disney XD

### Stream URL (required)

http://38.96.178.201:80/live/DisneyXD/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Changed to DisneyXDEast.us.

**Comment by spotanjo3** [comment]
No CC for hearing impaired. My mom's cable have this and showing CC enable for hearing impaired.

**Comment by Adrian322462** [comment]
Link Doesnt work anymore
