### ISSUE TITLE
Disney Channel

### ISSUE THREAD

**Issue by BogartDabid** [iptv-org/iptv#15911]
### Channel ID (required)

DisneyChannelEast.us

### Channel Name

Disney Channel

### Stream URL (required)

http://38.96.178.201/live/Disney/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Changed to DisneyChannelEast.us.

**Comment by Adrian322462** [comment]
> ### Channel ID (required)
> 
> DisneyChannelEast.us
> 
> ### Channel Name
> 
> Disney Channel
> 
> ### Stream URL (required)
> 
> http://38.96.178.201/live/Disney/index.m3u8
> 
> ### Quality
> 
> None
> 
> ### Label
> 
> None
> 
> ### Timeshift
> 
> _No response_
> 
> ### HTTP User Agent
> 
> _No response_
> 
> ### HTTP Referrer
> 
> _No response_
> 
> ### Notes
> 
> _No response_
> 
> ### Contributing Guide
> 
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)



> ### Channel ID (required)
> 
> DisneyChannelEast.us
> 
> ### Channel Name
> 
> Disney Channel
> 
> ### Stream URL (required)
> 
> http://38.96.178.201/live/Disne/index.m3u8
> 
> ### Quality
> 
> None
> 
> ### Label
> 
> None
> 
> ### Timeshift
> 
> _No response_
> 
> ### HTTP User Agent
> 
> _No response_
> 
> ### HTTP Referrer
> 
> _No response_
> 
> ### Notes
> 
> _No response_
> 
> ### Contributing Guide
> 
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Adrian322462** [comment]
Hey Need To Update the M3U URL 
http://38.96.178.201/live/Disney/index.m3u8
This One is Slow please make it Reliable and fast again for Streaming thank you i really appreciate it
My internet speed is Fast but the live is slowing down.

**Comment by mikkaelmlo432** [comment]
I need the Disney Channel Latin America M3U Link URL to Watch

**Comment by Ricky5655** [comment]
Fix Disney channel and change it into English
