### ISSUE TITLE
OVER: CAF African Cup of Nations tournament.

### ISSUE THREAD

**Issue by Duckinu69** [iptv-org/iptv#15914]
Now the African nation is over RTI1 still ain't available.

And you please add A+ channel     

They are currently blocked due to the CAF African Cup of Nations tournament.

_Originally posted by @fraudiay79 in https://github.com/iptv-org/iptv/issues/15609#issuecomment-1916075343_

**Comment by Dum4G** [comment]
>RTI1 still ain't available.
https://github.com/iptv-org/iptv/blob/cda366847260178c6a74977a1ae2762e71cc027b/streams/ci.m3u#L31-L32
![image](https://github.com/iptv-org/iptv/assets/5430116/1af198dd-a4fa-4434-a3f2-94f536ec2bea)

**Comment by fraudiay79** [comment]
It's working from the US. It may be geoblocked for your location
