### ISSUE TITLE
Add: BBC Arabic

### ISSUE THREAD

**Issue by awahid252** [iptv-org/iptv#15926]
### Channel ID (required)

BBCNewsArabic.uk

### Channel Name

BBC News Arabic

### Stream URL (required)

https://ythls.armelin.one/channel/UCelk6aHijZq-GJBBB9YpReA.m3u8

### Quality

1080p

### Label

None

### Notes

need the m3u8 for this live stream, please

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
https://ythls.armelin.one/channel/UCelk6aHijZq-GJBBB9YpReA.m3u8 @awahid252

**Comment by awahid252** [comment]
Thanks @Dum4G but unfortunately it is not working.do you have an alternative one?

**Comment by Dum4G** [comment]
Nope, unless you host query-streamlink for yourself. Armelin sometimes work and sometimes doesn't
