### ISSUE TITLE
Add: HGTV Philippines

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15924]
### Channel ID (required)

hgtv.ph

### Channel Name

HGTV

### Stream URL (required)

https://raw.githubusercontent.com/mimipipi22/lalajo/main/hgtv.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by rushereeeeee** [comment]
Discovery Channels are DCMA'd
