### ISSUE TITLE
Broken: YTV(jp)

### ISSUE THREAD

**Issue by okonomitarou** [iptv-org/iptv#15928]
### Broken Link

http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=gx04

### What happened to the stream?

No sound

### Notes (optional)

Sound is coming out, but the Left and Right balance is not correct. 

Rch sound is Low.
Best Regard.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
That's the server's problem. Nothing we can do.
