### ISSUE TITLE
None of the Medcom Panama channels work

### ISSUE THREAD

**Issue by Lucoasan** [iptv-org/iptv#15921]
### Describe your issue

The channels: Telemetro, RPC, Oye TV, Cabina RPC Radio, Cabina Telemetro Radio and Cabina Caliente radio don't work in the lists 
They are TV channels from Panama
The official site of the channels is this: https://go.medcom.com.pa/

### Contributing Guide

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Lucoasan** [comment]
Did they remove the channels instead of replacing them? What a pity

**Comment by Carlinhos027** [comment]
> Did they remove the channels instead of replacing them? What a pity

We can't add Dailymotion links, so we can't replace them for now.
