### ISSUE TITLE
Add: CINEMAX [USA]

### ISSUE THREAD

**Issue by crak3rjack** [iptv-org/iptv#15933]
### Channel ID (required)

Cinemax.us

### Stream URL (required)

https://live.tv247us.com/tv247/cinemaxus.m3u8|Referer=https://tv247.us

### Quality

None

### Label

None

### HTTP Referrer

https://tv247.us

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by rushereeeeee** [comment]
Not a M3U8 Streamlink

**Comment by crak3rjack** [comment]
@dtngfan85 done & thanks!

**Comment by rushereeeeee** [comment]
Oh
