### ISSUE TITLE
Broken: AniplusAsia.sg

### ISSUE THREAD

**Issue by ZendreiPlays117** [iptv-org/iptv#15936]
### Broken Link

https://code.vthanhtivi.pw/getlink/eazie/241430/playlist.m3u8

### What happened to the stream?

Other

### Notes (optional)

What are you up to this time? 

https://github.com/iptv-org/iptv/assets/67860120/a84d87e5-940d-408e-b543-dff8ef4c94b1

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by cloud90** [comment]
https://en.gdplayertv.top/live-tv/aniplus/

**Comment by BellezaEmporium** [comment]
> https://en.gdplayertv.top/live-tv/aniplus

Middleware, using DENS's protected streams : https://idx.iptvfreemium.com/denslokal/h/h114/S4/mnf.m3u8?app_type=web&userid=lite&chname=ANIPLUS_HD

Way of doing it : 
https://en.gdplayertv.top/get_token/ & https://en.gdplayertv.top/hls/?tv=aniplus&bypass=0&token=*token*
