### ISSUE TITLE
Broken: TF1 Channel not working [FR]

### ISSUE THREAD

**Issue by megu01s** [iptv-org/iptv#15934]
### Broken Link

https://iptv-org.github.io/iptv/countries/fr.m3u

### What happened to the stream?

Not loading

### Notes (optional)

Hello !
its been more than an week, some french channels stopped working…
Channels : TF1 ; TF1 Serie Film

if you could fix it please :(

thank you !

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by campones** [comment]
are they even in the playlist?  I don't see them
