### ISSUE TITLE
Add: TV5 Monde Asie

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15944]
### Channel ID (required)

 TV5MondeAsia.fr

### Channel Name

TV5 Monde Asia (Asie)

### Stream URL (required)

https://ott.tv5monde.com/Content/HLS/Live/channel(seasie)/variant.m3u8

### Quality

1080p

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by user8387884** [comment]
@Dum4G

**Comment by Dum4G** [comment]
![image](https://github.com/iptv-org/iptv/assets/5430116/c01e6326-4f15-49e1-ba8d-a171d6b341b2)

**Comment by user8387884** [comment]
> ![image](https://private-user-images.githubusercontent.com/5430116/308313806-c01e6326-4f15-49e1-ba8d-a171d6b341b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTA2MzcsIm5iZiI6MTcwOTExMDMzNywicGF0aCI6Ii81NDMwMTE2LzMwODMxMzgwNi1jMDFlNjMyNi00ZjE1LTQ5ZTEtYmE4ZC1hMTcxZDZiMzQxYjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDg1MjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGYwNTVjMDBiMTEzYWY3NmEwNzIwM2JmOTRiM2E0OTgwMzUzOWQ4M2NlYThmYmIwOWEwMWNkZmNkZDdhNmExMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Zvn3_1HxD5i-TUzMajB4f9rcqmiWy4mrM-AbV6pHJs0)

its working on vlc, your using it on browser
![Screenshot 2024-02-28 165309](https://github.com/iptv-org/iptv/assets/88836122/dd8a9c85-4a00-4732-a28d-eb81b9425083)
