### ISSUE TITLE
Broken: Gem.sg 

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#15943]
### Broken Link

https://code.vthanhtivi.pw/getlink/eazie/242918/playlist.m3u8

### What happened to the stream?

Other

### Notes (optional)

tricked us by an low quality image 
![Screenshot 2024-02-21 192047](https://github.com/iptv-org/iptv/assets/88836122/e4930f46-c285-493a-b62b-405329c2dc3b)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
http://103.77.172.5:5000/vod/haha.mp4/index.m3u8
Haha indeed
