### ISSUE TITLE
Broken: Ýaşlyk (406p)

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#15961]
### Broken Link

https://alpha.tv.online.tm/legacyhls/ch002.m3u8

### What happened to the stream?

I see visual artifacts

### Notes (optional)

Hey, mods! I found the video resolution quality became very rotted and grainy over the time someone will repair the links please.

Here's the images.

![vlcsnap-2024-02-18-22h27m50s850](https://github.com/iptv-org/iptv/assets/143818591/dd5f09ed-667e-40f7-9f4e-5f0b209c714b)
![vlcsnap-2024-02-18-22h30m43s971](https://github.com/iptv-org/iptv/assets/143818591/6888cc72-442f-43e1-9da2-2639c19abf4d)
![vlcsnap-2024-02-18-22h44m26s565](https://github.com/iptv-org/iptv/assets/143818591/430d8d11-6540-4eb3-9743-c202c584fa74)
![vlcsnap-2024-02-18-22h44m52s561](https://github.com/iptv-org/iptv/assets/143818591/de07e44f-b96d-43f6-b23a-f120abbf86fe)
![vlcsnap-2024-02-18-22h45m04s140](https://github.com/iptv-org/iptv/assets/143818591/52ce98af-522d-4708-847b-a28d7a4b0db6)
![vlcsnap-2024-02-22-23h02m00s632](https://github.com/iptv-org/iptv/assets/143818591/2be198d5-2c30-4afc-a896-61cad16b9346)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
It's the only available stream afaik. It's not a borked stream per-se, simply the quality of the program,

**Comment by AVGCFan1995** [comment]
> It's the only available stream afaik. It's not a borked stream per-se, simply the quality of the program,
> 
> (in fact, that seems to be the official stream given by the Turkmen government)

But how long the video quality needs to be fixed.
