### ISSUE TITLE
Broken: TVRI World (720p)

### ISSUE THREAD

**Issue by rchltmedia-codeviewer** [iptv-org/iptv#15969]
### Broken Link

http://wpc.d1627.nucdn.net/80D1627/o-tvri/Content/HLS/Live/Channel(TVRI3)/index.m3u8

### What happened to the stream?

Shows looped video

### Notes (optional)

this streaming link is outdated
new: https://ott-balancer.tvri.go.id/live/eds/TVRIWorld/hls/TVRIWorld.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Don't see any loop on the broken link & new link might be for a different channel?

**Comment by BellezaEmporium** [comment]
> Don't see any loop on the broken link & new link might be for a different channel?

The loop isn't really one. It's a program that cuts, and when you refresh, it's the same bit than comes back.

**Comment by R4IN2007** [comment]
Oh
