### ISSUE TITLE
Add: Télé Sahel

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#15979]
### Channel ID (required)

TeleSahel.ne

### Stream URL (required)

https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/tele_sahel/hls_video/hdntl-_-ZXhwPTE3MDkxMjQxMDl+YWNsPSUyZmxpdmUlMmZyYW1kaXNrJTJmdGVsZV9zYWhlbCUyZmhsc192aWRlbyUyZip+aG1hYz1hOTZhY2ZiYjE2YmM5MmIyYjlkMzVjZmUyZWE2NzlkYjBiOTcyNjViZDM1ZDMzZDViMzJlZWQ3ZjhlYTgwZjMw/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by sunyuanzhe** [comment]
what is a tokenized_link

**Comment by Dum4G** [comment]
a link that will work only at specific time only for specific user only for specific IP or device
