### ISSUE TITLE
Seek long-term Iptv source, monthly payment,,, Malaysia channel request

### ISSUE THREAD

**Issue by citvisionc** [iptv-org/iptv#1599]
Hi there I'm from Malaysia is there any body can provide the source below? Long term provide ,,whatsapp +601159239702
**Country***
Malaysia

**Channel Name:**
<
MY: ADITHYA
MY: AEC HD
MY: ANIMAL PLANET HD
MY: ANIMAX
MY: AOD 351 HD
MY: AOD 352 HD
MY: AOD 353 HD
MY: AOD 354 HD
MY: AOD 355 HD
MY: ASTRO ARENA HD
MY: ASTRO ASSP 2 HD
MY: ASTRO ASSP 3 HD
MY: ASTRO ASSP 4 HD
MY: ASTRO ASSP HD
MY: ASTRO AWANI
MY: ASTRO CERIA HD
MY: ASTRO CRICKET
MY: ASTRO HELLO
MY: ASTRO NAURA
MY: ASTRO OASIS HD
MY: ASTRO PRIMA HD
MY: ASTRO RIA HD
MY: ASTRO RUGBY PASS TV
MY: ASTRO WARNA HD
MY: AXN HD
MY: BBC News HD
MY: beIN Sports
MY: beIN Sports MAX
MY: BLOOMBERG TV
MY: BOLLYONE HD
MY: CARTOON NTWK HD
MY: CCTV4 HD
MY: CELESTIAL HD
MY: CGTN
MY: CHUTTI TV
MY: CINEMAX HD
MY: CNA HD
MY: CNN HD
MY: COLORS HD
MY: COLORS TAMIL
MY: COMEDY CENTRAL
MY: Crime+ Investigation HD
MY: CTI ASIA
MY: Discovery ASIA
MY: Discovery Channel HD
MY: Discovery Science HD
MY: Disney Channel HD
MY: Disney JUNIOR
MY: Disney XD HD
MY: DMAX HD
MY: DW HD
MY: eGG Network
MY: EUROSPORT HD
MY: FOOD NTWK HD
MY: FOX Action Movies
MY: FOX Family Movies
MY: FOX HD
MY: FOX SPORTS 2 HD
MY: FOX SPORTS 3 HD
MY: FRANCE24 HD
MY: GO SHOP 2
MY: GO SHOP GAAYA
MY: GO SHOP RUUMA
MY: GOLF Channel HD
MY: HBO HD
MY: HGTV HD
MY: History HD
MY: HITS HD
MY: HITS Movies HD
MY: HUA HEE DAI HD
MY: iQIYI HD
MY: KALAIGNAR
MY: KBS World HD
MY: KIX HD
MY: KPLUS HD
MY: MTV
MY: NAT GEO HD
MY: NAT GEO People
MY: Nick Junior
MY: nickelodeon HD
MY: Oh!K HD
MY: ONE HD
MY: QUAN JIA HD
MY: SHUANG XING HD
MY: SKY NEWS HD
MY: STAR VIJAY HD
MY: SUN MUSIC
MY: SUN TV HD
MY: TV ALHIJRAH
MY: TV1
MY: TV2
MY: TV3
MY: TVB CLASSIC
MY: TVB E-NEWS
MY: TVB XING HE HD
MY: tvN Movies
MY: VINMEEN HD
MY: WARNER TV
MY: WLT JADE
MY: WWE Network
MY: XIAO TAI YANG HD

**Channel Language:**

**Additional Information (optional):**

**Comment by citvisionc** [comment]
I wanted to have my Malaysia iptv restream platform, I had already subscri my AND servers ,If the stream source you are parsing comes with own traffic, I can transfer the cost of the server to you, just make sure u the provided source that you provide are updated regularly.

**Comment by cartoonchannelfans** [comment]
我也想要！

**Comment by bedbyaspokhrel** [comment]
i also want

**Comment by LaneSh4d0w** [comment]
Big channel list here, thanks for being that precise about the Malaysian channels.

I'll take a look when available.

- [ ] MY: ADITHYA
- [ ] MY: AEC HD
- [ ] MY: ANIMAL PLANET HD
- [ ] MY: ANIMAX
- [ ] MY: AOD 351 HD
- [ ] MY: AOD 352 HD
- [ ] MY: AOD 353 HD
- [ ] MY: AOD 354 HD
- [ ] MY: AOD 355 HD
- [ ] MY: ASTRO ARENA HD
- [ ] MY: ASTRO ASSP 2 HD
- [ ] MY: ASTRO ASSP 3 HD
- [ ] MY: ASTRO ASSP 4 HD
- [ ] MY: ASTRO ASSP HD
- [ ] MY: ASTRO AWANI
- [ ] MY: ASTRO CERIA HD
- [ ] MY: ASTRO CRICKET
- [ ] MY: ASTRO HELLO
- [ ] MY: ASTRO NAURA
- [ ] MY: ASTRO OASIS HD
- [ ] MY: ASTRO PRIMA HD
- [ ] MY: ASTRO RIA HD
- [ ] MY: ASTRO RUGBY PASS TV
- [ ] MY: ASTRO WARNA HD
- [ ] MY: AXN HD
- [ ] MY: BBC News HD
- [ ] MY: beIN Sports
- [ ] MY: beIN Sports MAX
- [ ] MY: BLOOMBERG TV
- [ ] MY: BOLLYONE HD
- [ ] MY: CARTOON NTWK HD
- [ ] MY: CCTV4 HD
- [ ] MY: CELESTIAL HD
- [ ] MY: CGTN
- [ ] MY: CHUTTI TV
- [ ] MY: CINEMAX HD
- [ ] MY: CNA HD
- [ ] MY: CNN HD
- [ ] MY: COLORS HD
- [ ] MY: COLORS TAMIL
- [ ] MY: COMEDY CENTRAL
- [ ] MY: Crime+ Investigation HD
- [ ] MY: CTI ASIA
- [ ] MY: Discovery ASIA
- [ ] MY: Discovery Channel HD
- [ ] MY: Discovery Science HD
- [ ] MY: Disney Channel HD
- [ ] MY: Disney JUNIOR
- [ ] MY: Disney XD HD
- [ ] MY: DMAX HD
- [ ] MY: DW HD
- [ ] MY: eGG Network
- [ ] MY: EUROSPORT HD
- [ ] MY: FOOD NTWK HD
- [ ] MY: FOX Action Movies
- [ ] MY: FOX Family Movies
- [ ] MY: FOX HD
- [ ] MY: FOX SPORTS 2 HD
- [ ] MY: FOX SPORTS 3 HD
- [ ] MY: FRANCE24 HD
- [ ] MY: GO SHOP 2
- [ ] MY: GO SHOP GAAYA
- [ ] MY: GO SHOP RUUMA
- [ ] MY: GOLF Channel HD
- [ ] MY: HBO HD
- [ ] MY: HGTV HD
- [ ] MY: History HD
- [ ] MY: HITS HD
- [ ] MY: HITS Movies HD
- [ ] MY: HUA HEE DAI HD
- [ ] MY: iQIYI HD
- [ ] MY: KALAIGNAR
- [ ] MY: KBS World HD
- [ ] MY: KIX HD
- [ ] MY: KPLUS HD
- [ ] MY: MTV
- [ ] MY: NAT GEO HD
- [ ] MY: NAT GEO People
- [ ] MY: Nick Junior
- [ ] MY: nickelodeon HD
- [ ] MY: Oh!K HD
- [ ] MY: ONE HD
- [ ] MY: QUAN JIA HD
- [ ] MY: SHUANG XING HD
- [ ] MY: SKY NEWS HD
- [ ] MY: STAR VIJAY HD
- [ ] MY: SUN MUSIC
- [ ] MY: SUN TV HD
- [ ] MY: TV ALHIJRAH
- [ ] MY: TV1
- [ ] MY: TV2
- [ ] MY: TV3
- [ ] MY: TVB CLASSIC
- [ ] MY: TVB E-NEWS
- [ ] MY: TVB XING HE HD
- [ ] MY: tvN Movies
- [ ] MY: VINMEEN HD
- [ ] MY: WARNER TV
- [ ] MY: WLT JADE
- [ ] MY: WWE Network
- [ ] MY: XIAO TAI YANG HD

**Comment by freearhey** [comment]
ANIMAL PLANET HD, Discovery ASIA, Discovery Channel HD, Discovery Science HD, DMAX HD, EUROSPORT HD, FOOD NTWK HD and HGTV HD cannot be added to the playlist due to claims of the copyright holder. More details here: #1831

**Comment by freearhey** [comment]
ANIMAX https://github.com/iptv-org/iptv/blob/858878c95251fd99c78792c40fcf604b2802bfec/channels/jp.m3u#L2-L3

**Comment by freearhey** [comment]
Closed in favor #1949, #1982, #1983, #1976, #1942, #1934, #1991 and #1992

**Comment by zwna27** [comment]
i wanna too
