### ISSUE TITLE
Broken: None of the channels on the Polish list works.

### ISSUE THREAD

**Issue by TP4ndaHD** [iptv-org/iptv#16015]
### Broken Link

https://iptv-org.github.io/iptv/languages/pol.m3u | https://iptv-org.github.io/iptv/countries/pl.m3u

### What happened to the stream?

Displays a message asking to renew subscription

### Notes (optional)

Please update list, thanks

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Name channels or the source

**Comment by BellezaEmporium** [comment]
Seems to be the "lolokoko.tv" streams.

**Comment by BellezaEmporium** [comment]
AFAIK change the "cdn-main" links to "cdn-nvm-chicago"

**Comment by V-SGFX** [comment]
![lolokoko](https://github.com/iptv-org/iptv/assets/8970799/9f91cc85-6d7a-44b2-8392-c325ddf3b176)
Ops.
