### ISSUE TITLE
Broken: Stingray

### ISSUE THREAD

**Issue by Delitants** [iptv-org/iptv#16016]
### Broken Link

https://lotus.stingray.com/manifest/ose-107ads-montreal/live/master.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

All Stingray links are dead.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by trancer1994** [comment]
I also want to see a fix to the Stingray channels.

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500016NH_20231024T231840SQUARE.png_20231024231841.png" group-title="United States" ,Stingray Today's K-Pop
https://i.mjh.nz/SamsungTVPlus/USBD3500016NH.m3u8
#EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500025GS_20231024T231759SQUARE.png_20231024231801.png" group-title="United States" ,Stingray DJAZZ
https://i.mjh.nz/SamsungTVPlus/USBD3500025GS.m3u8
#EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500024YB_20231024T231727SQUARE.png_20231024231728.png" group-title="United States" ,Qello Concerts by Stingray
https://i.mjh.nz/SamsungTVPlus/USBD3500024YB.m3u8
#EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD35000128A_20231024T231824SQUARE.png_20231024231825.png" group-title="United States" ,Stingray Smooth Jazz
https://i.mjh.nz/SamsungTVPlus/USBD35000128A.m3u8
#EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD350002623_20231024T231756SQUARE.png_20231024231757.png" group-title="United States" ,Stingray Classica
https://i.mjh.nz/SamsungTVPlus/USBD350002623.m3u8
#EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500009Y3_20231024T231843SQUARE.png_20231024231844.png" group-title="United States" ,Stingray Today's Latin Pop
https://i.mjh.nz/SamsungTVPlus/USBD3500009Y3.m3u8
#EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500017CE_20231024T231821SQUARE.png_20231024231822.png" group-title="United States" ,Stingray Romance Latino
https://i.mjh.nz/SamsungTVPlus/USBD3500017CE.m3u8
#EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500011J3_20231024T231803SQUARE.png_20231024231804.png" group-title="United States" ,Stingray Easy Listening
https://i.mjh.nz/SamsungTVPlus/USBD3500011J3.m3u8
#EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500008IJ_20231024T231806SQUARE.png_20231024231807.png" group-title="United States" ,Stingray Flashback 70s
https://i.mjh.nz/SamsungTVPlus/USBD3500008IJ.m3u8
#EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3300022QK_20231024T231818SQUARE.png_20231024231819.png" group-title="United States" ,Stingray Remember the 80s
https://i.mjh.nz/SamsungTVPlus/USBD3300022QK.m3u8
#EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD35000149S_20231024T231815SQUARE.png_20231024231816.png" group-title="United States" ,Stingray Nothin' But 90s
https://i.mjh.nz/SamsungTVPlus/USBD35000149S.m3u8
#EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD35000180U_20231024T231753SQUARE.png_20231024231754.png" group-title="United States" ,Stingray Classic Rock
https://i.mjh.nz/SamsungTVPlus/USBD35000180U.m3u8
#EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500010MT_20231114T233507SQUARE.png_20231114233508.png" group-title="United States" ,Stingray Hip Hop
https://i.mjh.nz/SamsungTVPlus/USBD3500010MT.m3u8
#EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3300021KV_20231129T022255SQUARE.png_20231129022256.png" group-title="United States" ,Stingray Hot Country
https://i.mjh.nz/SamsungTVPlus/USBD3300021KV.m3u8
#EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500022DN_20231114T233419SQUARE.png_20231114233420.png"  group-title="United States" ,Stingray Greatest Hits
https://i.mjh.nz/SamsungTVPlus/USBD3500022DN.m3u8
#EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500013DG_20231024T231827SQUARE.png_20231024231828.png"  group-title="United States" ,Stingray Spa
https://i.mjh.nz/SamsungTVPlus/USBD3500013DG.m3u8

#EXTINF:-1 tvg-logo="https://provider-static.plex.tv/epg/cms/production/90f3fa8c-fe2b-4716-8fa9-62cf90940c68/Stingray_CMusic_logo_light.png" group-title="USA" ,Stingray CMusic
https://i.mjh.nz/Plex/5e20b730f2f8d5003d739db7-62fbf197c67d52bddf74cc87.m3u8
#EXTINF:-1 tvg-logo="https://provider-static.plex.tv/epg/cms/production/c01ebda0-1d80-4935-ad6a-a5d3c3ef108e/Stingray-Naturescape_Logo_Lightrdx.png" group-title="USA" ,Stingray Naturescape
https://i.mjh.nz/Plex/5e20b730f2f8d5003d739db7-60d324f59adce5002c41dbc5.m3u8
#EXTINF:-1 tvg-logo="https://provider-static.plex.tv/epg/cms/production/05ec736a-4fe4-4d71-9f6d-e4c1d8f9fbcf/9831_HS_Plex_Launch-assets_Channel-Logo_1500x1000_V01-Light-Vert.png" group-title="USA" ,Stingray Holidayscapes
https://i.mjh.nz/Plex/5e20b730f2f8d5003d739db7-654eb862dde2222e8ba551f1.m3u8
#EXTINF:-1 tvg-logo="https://provider-static.plex.tv/epg/cms/production/84bbc4c9-ab36-47c0-88f8-d2d2e67f657a/Soul_Storm.png" group-title="USA" ,Stingray Soul Storm
https://i.mjh.nz/Plex/5e20b730f2f8d5003d739db7-61aaa17a784a2161d3caf801.m3u8

**Comment by brokenstream** [comment]
Xumo's channels still work as well:
https://lotus.stingray.com/manifest/ose-107ads-montreal/xumo-redbox/master.m3u8

**Comment by Delitants** [comment]
None of these links work, plays empty stream.

**Comment by Sphinxroot** [comment]
https://www.xumo.com/-/media/xumo/supportv2/xumo_channel_lineup_3pg_1_16_2024.pdf
file:///C:/Users/SphinxLaboratory/Downloads/full%20list%20of%20Xumo%20Play.pdf

#EXTINF:-1,Stingray Classic Rock
https://dbrb49pjoymg4.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod_default_xumo-ams-aws/master.m3u8?ads.xumo_channelId=99991119
#EXTINF:-1,Stingray Hit list
https://dbrb49pjoymg4.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod_default_xumo-ams-aws/master.m3u8?ads.xumo_channelId=99991117
#EXTINF:-1,Stingray Remember the 80s
https://dbrb49pjoymg4.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod_default_xumo-ams-aws/master.m3u8?ads.xumo_channelId=99991742
#EXTINF:-1,Stingray Greatest Holiday Hits
https://dbrb49pjoymg4.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod_default_xumo-ams-aws/master.m3u8?ads.xumo_channelId=99991120
#EXTINF:-1,Stingray Soul Storm Christmas
https://dbrb49pjoymg4.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod_default_xumo-ams-aws/master.m3u8?ads.xumo_channelId=99991121
#EXTINF:-1,Stingray Hot Country Christmas
https://dbrb49pjoymg4.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod_default_xumo-ams-aws/master.m3u8?ads.xumo_channelId=99991118
#EXTINF:-1,Stingray Naturescape
https://d2vv1kwm3dofeu.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod_default_xumo-ams-aws/master.m3u8?ads.xumo_channelId=99991252

**Comment by Sphinxroot** [comment]
https://www.xumo.com/-/media/xumo/supportv2/xumo_channel_lineup_3pg_1_16_2024.pdf
https://www.xumo.com/-/media/xumo/supportv2/full-list-of-xumo-play.pdf

#EXTINF:-1,Stingray Classic Rock
https://dbrb49pjoymg4.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod_default_xumo-ams-aws/master.m3u8?ads.xumo_channelId=99991119
#EXTINF:-1,Stingray Hit list
https://dbrb49pjoymg4.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod_default_xumo-ams-aws/master.m3u8?ads.xumo_channelId=99991117
#EXTINF:-1,Stingray Remember the 80s
https://dbrb49pjoymg4.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod_default_xumo-ams-aws/master.m3u8?ads.xumo_channelId=99991742
#EXTINF:-1,Stingray Greatest Holiday Hits
https://dbrb49pjoymg4.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod_default_xumo-ams-aws/master.m3u8?ads.xumo_channelId=99991120
#EXTINF:-1,Stingray Soul Storm Christmas
https://dbrb49pjoymg4.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod_default_xumo-ams-aws/master.m3u8?ads.xumo_channelId=99991121
#EXTINF:-1,Stingray Hot Country Christmas
https://dbrb49pjoymg4.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod_default_xumo-ams-aws/master.m3u8?ads.xumo_channelId=99991118
#EXTINF:-1,Stingray Naturescape
https://d2vv1kwm3dofeu.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod_default_xumo-ams-aws/master.m3u8?ads.xumo_channelId=99991252

**Comment by Sphinxroot** [comment]
> None of these links work in the US (VLC). Works outside. Urban Beats is missing.

rebrand as  Hip-Hop/R&B
https://music.stingray.com/en/CA/channels/033/urban-beats

**Comment by Delitants** [comment]
> #EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500016NH_20231024T231840SQUARE.png_20231024231841.png" group-title="United States" ,Stingray Today's K-Pop https://i.mjh.nz/SamsungTVPlus/USBD3500016NH.m3u8 #EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500025GS_20231024T231759SQUARE.png_20231024231801.png" group-title="United States" ,Stingray DJAZZ https://i.mjh.nz/SamsungTVPlus/USBD3500025GS.m3u8 #EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500024YB_20231024T231727SQUARE.png_20231024231728.png" group-title="United States" ,Qello Concerts by Stingray https://i.mjh.nz/SamsungTVPlus/USBD3500024YB.m3u8 #EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD35000128A_20231024T231824SQUARE.png_20231024231825.png" group-title="United States" ,Stingray Smooth Jazz https://i.mjh.nz/SamsungTVPlus/USBD35000128A.m3u8 #EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD350002623_20231024T231756SQUARE.png_20231024231757.png" group-title="United States" ,Stingray Classica https://i.mjh.nz/SamsungTVPlus/USBD350002623.m3u8 #EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500009Y3_20231024T231843SQUARE.png_20231024231844.png" group-title="United States" ,Stingray Today's Latin Pop https://i.mjh.nz/SamsungTVPlus/USBD3500009Y3.m3u8 #EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500017CE_20231024T231821SQUARE.png_20231024231822.png" group-title="United States" ,Stingray Romance Latino https://i.mjh.nz/SamsungTVPlus/USBD3500017CE.m3u8 #EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500011J3_20231024T231803SQUARE.png_20231024231804.png" group-title="United States" ,Stingray Easy Listening https://i.mjh.nz/SamsungTVPlus/USBD3500011J3.m3u8 #EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500008IJ_20231024T231806SQUARE.png_20231024231807.png" group-title="United States" ,Stingray Flashback 70s https://i.mjh.nz/SamsungTVPlus/USBD3500008IJ.m3u8 #EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3300022QK_20231024T231818SQUARE.png_20231024231819.png" group-title="United States" ,Stingray Remember the 80s https://i.mjh.nz/SamsungTVPlus/USBD3300022QK.m3u8 #EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD35000149S_20231024T231815SQUARE.png_20231024231816.png" group-title="United States" ,Stingray Nothin' But 90s https://i.mjh.nz/SamsungTVPlus/USBD35000149S.m3u8 #EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD35000180U_20231024T231753SQUARE.png_20231024231754.png" group-title="United States" ,Stingray Classic Rock https://i.mjh.nz/SamsungTVPlus/USBD35000180U.m3u8 #EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500010MT_20231114T233507SQUARE.png_20231114233508.png" group-title="United States" ,Stingray Hip Hop https://i.mjh.nz/SamsungTVPlus/USBD3500010MT.m3u8 #EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3300021KV_20231129T022255SQUARE.png_20231129022256.png" group-title="United States" ,Stingray Hot Country https://i.mjh.nz/SamsungTVPlus/USBD3300021KV.m3u8 #EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500022DN_20231114T233419SQUARE.png_20231114233420.png" group-title="United States" ,Stingray Greatest Hits https://i.mjh.nz/SamsungTVPlus/USBD3500022DN.m3u8 #EXTINF:-1 tvg-logo="https://tvpnlogopus.samsungcloud.tv/platform/image/sourcelogo/vc/00/02/34/USBD3500013DG_20231024T231827SQUARE.png_20231024231828.png" group-title="United States" ,Stingray Spa https://i.mjh.nz/SamsungTVPlus/USBD3500013DG.m3u8
> 
> #EXTINF:-1 tvg-logo="https://provider-static.plex.tv/epg/cms/production/90f3fa8c-fe2b-4716-8fa9-62cf90940c68/Stingray_CMusic_logo_light.png" group-title="USA" ,Stingray CMusic https://i.mjh.nz/Plex/5e20b730f2f8d5003d739db7-62fbf197c67d52bddf74cc87.m3u8 #EXTINF:-1 tvg-logo="https://provider-static.plex.tv/epg/cms/production/c01ebda0-1d80-4935-ad6a-a5d3c3ef108e/Stingray-Naturescape_Logo_Lightrdx.png" group-title="USA" ,Stingray Naturescape https://i.mjh.nz/Plex/5e20b730f2f8d5003d739db7-60d324f59adce5002c41dbc5.m3u8 #EXTINF:-1 tvg-logo="https://provider-static.plex.tv/epg/cms/production/05ec736a-4fe4-4d71-9f6d-e4c1d8f9fbcf/9831_HS_Plex_Launch-assets_Channel-Logo_1500x1000_V01-Light-Vert.png" group-title="USA" ,Stingray Holidayscapes https://i.mjh.nz/Plex/5e20b730f2f8d5003d739db7-654eb862dde2222e8ba551f1.m3u8 #EXTINF:-1 tvg-logo="https://provider-static.plex.tv/epg/cms/production/84bbc4c9-ab36-47c0-88f8-d2d2e67f657a/Soul_Storm.png" group-title="USA" ,Stingray Soul Storm https://i.mjh.nz/Plex/5e20b730f2f8d5003d739db7-61aaa17a784a2161d3caf801.m3u8

All links are 404 now.
