### ISSUE TITLE
Hongkong and Macao are not country.

### ISSUE THREAD

**Issue by feiyihx** [iptv-org/iptv#16024]
### Describe your issue

You may argue with Taiwan, but Hong Kong and Macao are not countries. They are Special Administrative Regions of the People's Republic of China. So, would you please move them under the China category as regions? Thank you.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
We're strictly following [ISO 3166](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes), independantly from country sovereignity. If you need a combined playlist we may consider creating a regional one
