### ISSUE TITLE
Broken: lolokoko streams

### ISSUE THREAD

**Issue by TestNintendo** [iptv-org/iptv#16045]
### Broken Link

https://cdn-main.lolokoko.tv/BBCHD.stream/playlist.m3u8 https://cdn-main.lolokoko.tv/CBeebies.stream/playlist.m3u8 https://cdn-main.lolokoko.tv/Polsat.stream/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

looks like some of the links haven't been updated
pro tip: please check in the Polish list for all "cdn-main.lolokoko.tv" links and replace them with "cdn-nvm-chicago.lolokoko.tv"

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by campones** [comment]
Pinging cdn-main.lolokoko.tv [64.18.131.133] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

**Comment by Dum4G** [comment]
Update your playlist

**Comment by TestNintendo** [comment]
it wasn't very helpful at all...

**Comment by NagraniaTelewizji** [comment]
Help TestNintendo

![317818170-c9e0fba1-e710-4634-90d9-459874af8ecc](https://github.com/iptv-org/iptv/assets/159693744/8f6c01d7-07d5-498c-a0ef-510ead705df4)

All streams Lolokoko.tv on song o no o no... and photo!!!!.

**Comment by TestNintendo** [comment]
open a new issue

**Comment by NagraniaTelewizji** [comment]
cdn-nvm-chicago.lolokoko.tv -> cdn-main.lolokoko.tv

**Comment by campones** [comment]
guys, the domain , (well rather ip) that I still had working are down since today. I get a picture like above

if anyone can share me privately working stream address I would apreciate greatly. thanks 

djionut@gmx.fr
