### ISSUE TITLE
Add: FOX Sports 1 (USA)

### ISSUE THREAD

**Issue by Ins0lenceWill0w** [iptv-org/iptv#16043]
### Channel ID (required)

FoxSports1.us

### Channel Name

FOX Sports 1

### Stream URL (required)

http://livex.pop-app.live/s4n/poplive/ch339/playlist.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ragetraxx** [comment]
Not working
