### ISSUE TITLE
Add: FOX Sports 2 (USA)

### ISSUE THREAD

**Issue by Ins0lenceWill0w** [iptv-org/iptv#16044]
### Channel ID (required)

FoxSports2.us

### Channel Name

FOX Sports 2

### Stream URL (required)

http://livex.pop-app.live/s4n/poplive/ch326/playlist.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by AAMBIENTT** [comment]
Nonfunctional.
