### ISSUE TITLE
Add: FXX (USA)

### ISSUE THREAD

**Issue by Ins0lenceWill0w** [iptv-org/iptv#16046]
### Channel ID (required)

FXXEast.us

### Channel Name

FXX

### Stream URL (required)

http://livex.pop-app.live/s4n/poplive/ch523/playlist.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by rushereeeeee** [comment]
Link is broken ya got another one?
![Uploading IMG_1966.png…]()

**Comment by Armond452Alt** [comment]
label:rejected:broken_link
