### ISSUE TITLE
Add: ION Television (USA)

### ISSUE THREAD

**Issue by Ins0lenceWill0w** [iptv-org/iptv#16052]
### Channel ID (required)

IONTVEast.us

### Channel Name

ION Television

### Stream URL (required)

http://livex.pop-app.live/s4n/poplive/ch565/playlist.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by spotanjo3** [comment]
dead
