### ISSUE TITLE
Add: History Channel (USA)

### ISSUE THREAD

**Issue by Ins0lenceWill0w** [iptv-org/iptv#16051]
### Channel ID (required)

HistoryEast.us

### Channel Name

History Channel

### Stream URL (required)

http://livex.pop-app.live/s4n/poplive/ch215/playlist.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by spotanjo3** [comment]
Its dead
