### ISSUE TITLE
Add: Univision East (USA)

### ISSUE THREAD

**Issue by Ins0lenceWill0w** [iptv-org/iptv#16067]
### Channel ID (required)

UnivisionEast.us

### Channel Name

Univision East

### Stream URL (required)

http://livex.pop-app.live/s4n/poplive/ch328/playlist.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Mmh... Just US links huh?
There a whole list also missed some as well + MX Channels and Latin America Channels

#EXTINF:-0, TUDN | US
http://livex.pop-app.live/s4n/poplive/ch302/playlist.m3u8

#EXTINF:-0, NBC KPRC2 HOUSTON
http://livex.pop-app.live/s4n/poplive/ch309/playlist.m3u8

#EXTINF:-0, NBA TV
http://livex.pop-app.live/s4n/poplive/ch310/playlist.m3u8

#EXTINF:-0, ESPN DEPORTES
http://livex.pop-app.live/s4n/poplive/ch311/playlist.m3u8

#EXTINF:-0, FOX 26 KRIV HOUSTON
http://livex.pop-app.live/s4n/poplive/ch312/playlist.m3u8

#EXTINF:-0, ESPN
http://livex.pop-app.live/s4n/poplive/ch313/playlist.m3u8

#EXTINF:-0, Bravo
http://livex.pop-app.live/s4n/poplive/ch316/playlist.m3u8

#EXTINF:-0, ESPN
http://livex.pop-app.live/s4n/poplive/ch319/playlist.m3u8

#EXTINF:-0, ESPN3
http://livex.pop-app.live/s4n/poplive/ch320/playlist.m3u8

#EXTINF:-0, Fox Sports
http://livex.pop-app.live/s4n/poplive/ch321/playlist.m3u8

#EXTINF:-0, Fox Sports 2
http://livex.pop-app.live/s4n/poplive/ch322/playlist.m3u8

#EXTINF:-0, HGTV
http://livex.pop-app.live/s4n/poplive/ch323/playlist.m3u8

#EXTINF:-0, CBS Sports Network
http://livex.pop-app.live/s4n/poplive/ch325/playlist.m3u8

#EXTINF:-0, FS2
http://livex.pop-app.live/s4n/poplive/ch326/playlist.m3u8

#EXTINF:-0, Telemundo
http://livex.pop-app.live/s4n/poplive/ch327/playlist.m3u8

#EXTINF:-0, Univision
http://livex.pop-app.live/s4n/poplive/ch328/playlist.m3u8

#EXTINF:-0, NBC Sports Chicago
http://livex.pop-app.live/s4n/poplive/ch331/playlist.m3u8

#EXTINF:-0, NFL Network
http://livex.pop-app.live/s4n/poplive/ch332/playlist.m3u8

#EXTINF:-0, CBS
http://livex.pop-app.live/s4n/poplive/ch333/playlist.m3u8

#EXTINF:-0, TBS
http://livex.pop-app.live/s4n/poplive/ch334/playlist.m3u8

#EXTINF:-0, NBC Golf
http://livex.pop-app.live/s4n/poplive/ch335/playlist.m3u8

#EXTINF:-0, MLB Network
http://livex.pop-app.live/s4n/poplive/ch336/playlist.m3u8

#EXTINF:-0, TNT
http://livex.pop-app.live/s4n/poplive/ch337/playlist.m3u8

#EXTINF:-0, Fox Sports
http://livex.pop-app.live/s4n/poplive/ch338/playlist.m3u8

#EXTINF:-0, FS1
http://livex.pop-app.live/s4n/poplive/ch339/playlist.m3u8

#EXTINF:-0, ABC
http://livex.pop-app.live/s4n/poplive/ch340/playlist.m3u8

#EXTINF:-0, USA
http://livex.pop-app.live/s4n/poplive/ch341/playlist.m3u8

#EXTINF:-0, History | US
http://livex.pop-app.live/s4n/poplive/ch342/playlist.m3u8

#EXTINF:-0, History
http://livex.pop-app.live/s4n/poplive/ch349/playlist.m3u8

#EXTINF:-0, Caracol TV
http://livex.pop-app.live/s4n/poplive/ch350/playlist.m3u8

#EXTINF:-0, Antena3 Internacional
http://livex.pop-app.live/s4n/poplive/ch351/playlist.m3u8

#EXTINF:-0, Discovery h&h
http://livex.pop-app.live/s4n/poplive/ch352/playlist.m3u8

#EXTINF:-0, STARZ Kids & Family
http://livex.pop-app.live/s4n/poplive/ch500/playlist.m3u8

#EXTINF:-0,
http://livex.pop-app.live/s4n/poplive/ch503/playlist.m3u8

#EXTINF:-0, FX
http://livex.pop-app.live/s4n/poplive/ch505/playlist.m3u8

#EXTINF:-0, Sony Channel
http://livex.pop-app.live/s4n/poplive/ch506/playlist.m3u8

#EXTINF:-0, NatGeo Wild
http://livex.pop-app.live/s4n/poplive/ch508/playlist.m3u8

#EXTINF:-0, National Geographic
http://livex.pop-app.live/s4n/poplive/ch509/playlist.m3u8

#EXTINF:-0, Golden Plus+
http://livex.pop-app.live/s4n/poplive/ch511/playlist.m3u8

#EXTINF:-0, Nickelodeon
http://livex.pop-app.live/s4n/poplive/ch512/playlist.m3u8

#EXTINF:-0, NickToons
http://livex.pop-app.live/s4n/poplive/ch513/playlist.m3u8

#EXTINF:-0,
http://livex.pop-app.live/s4n/poplive/ch514/playlist.m3u8

#EXTINF:-0, HBO Family
http://livex.pop-app.live/s4n/poplive/ch515/playlist.m3u8

#EXTINF:-0, HBO+
http://livex.pop-app.live/s4n/poplive/ch516/playlist.m3u8

#EXTINF:-0, HBO Signature
http://livex.pop-app.live/s4n/poplive/ch517/playlist.m3u8

#EXTINF:-0, FXX
http://livex.pop-app.live/s4n/poplive/ch523/playlist.m3u8

#EXTINF:-0, Discovery h&h
http://livex.pop-app.live/s4n/poplive/ch524/playlist.m3u8

#EXTINF:-0, Discovery ID
http://livex.pop-app.live/s4n/poplive/ch525/playlist.m3u8

#EXTINF:-0, Discovery Family
http://livex.pop-app.live/s4n/poplive/ch526/playlist.m3u8

#EXTINF:-0, TLC
http://livex.pop-app.live/s4n/poplive/ch527/playlist.m3u8

#EXTINF:-0, MotorTrend 
http://livex.pop-app.live/s4n/poplive/ch528/playlist.m3u8

#EXTINF:-0,
http://livex.pop-app.live/s4n/poplive/ch529/playlist.m3u8

#EXTINF:-0, HBO Family
http://livex.pop-app.live/s4n/poplive/ch530/playlist.m3u8

#EXTINF:-0,
http://livex.pop-app.live/s4n/poplive/ch531/playlist.m3u8

#EXTINF:-0,
http://livex.pop-app.live/s4n/poplive/ch533/playlist.m3u8

#EXTINF:-0, GSN
http://livex.pop-app.live/s4n/poplive/ch535/playlist.m3u8

#EXTINF:-0, Paramount Network
http://livex.pop-app.live/s4n/poplive/ch544/playlist.m3u8

#EXTINF:-0, Cartoonito
http://livex.pop-app.live/s4n/poplive/ch545/playlist.m3u8

#EXTINF:-0,
http://livex.pop-app.live/s4n/poplive/ch546/playlist.m3u8

#EXTINF:-0, Afizzionados
http://livex.pop-app.live/s4n/poplive/ch548/playlist.m3u8

#EXTINF:-0, AMC
http://livex.pop-app.live/s4n/poplive/ch549/playlist.m3u8

#EXTINF:-0, Babyfirst
http://livex.pop-app.live/s4n/poplive/ch550/playlist.m3u8

#EXTINF:-0,
http://livex.pop-app.live/s4n/poplive/ch553/playlist.m3u8

#EXTINF:-0, BitMe
http://livex.pop-app.live/s4n/poplive/ch555/playlist.m3u8

#EXTINF:-0, Turbo
http://livex.pop-app.live/s4n/poplive/ch556/playlist.m3u8

#EXTINF:-0, METV
http://livex.pop-app.live/s4n/poplive/ch557/playlist.m3u8

#EXTINF:-0, Travel Channel
http://livex.pop-app.live/s4n/poplive/ch558/playlist.m3u8

#EXTINF:-0, OXYGEN
http://livex.pop-app.live/s4n/poplive/ch560/playlist.m3u8

#EXTINF:-0, Bounce
http://livex.pop-app.live/s4n/poplive/ch561/playlist.m3u8

#EXTINF:-0, Win Sports+
http://livex.pop-app.live/s4n/poplive/ch562/playlist.m3u8

#EXTINF:-0, Grit
http://livex.pop-app.live/s4n/poplive/ch563/playlist.m3u8

#EXTINF:-0, ION TELEVISION
http://livex.pop-app.live/s4n/poplive/ch565/playlist.m3u8

#EXTINF:-0, OWN
http://livex.pop-app.live/s4n/poplive/ch566/playlist.m3u8

#EXTINF:-0, Lifetime
http://livex.pop-app.live/s4n/poplive/ch567/playlist.m3u8

#EXTINF:-0, AZ Corazon
http://livex.pop-app.live/s4n/poplive/ch570/playlist.m3u8

#EXTINF:-0, ESPN SEC Network
http://livex.pop-app.live/s4n/poplive/ch571/playlist.m3u8

#EXTINF:-0, B1G Network
http://livex.pop-app.live/s4n/poplive/ch572/playlist.m3u8

#EXTINF:-0, ESPN ACCN
http://livex.pop-app.live/s4n/poplive/ch573/playlist.m3u8

#EXTINF:-0,
http://livex.pop-app.live/s4n/poplive/ch574/playlist.m3u8

**Comment by rushereeeeee** [comment]
FXX has sadly been broken or has been DRM protected :( but others work fine tho

**Comment by R4IN2007** [comment]
FXX works fine shouldn't be any problem which is weird.

**Comment by rushereeeeee** [comment]
One problem about it is that the stream doesn't work for apple devices. It works fine on my fire stick tho

**Comment by rushereeeeee** [comment]
@R4IN2007 all links are forbidden

**Comment by shelomito12** [comment]
https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_fastly.m3u
