### ISSUE TITLE
Add: 9X TASHAN

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#16084]
### Channel ID (required)

9XTashan.in

### Channel Name

9X Tashan

### Stream URL (required)

https://amg01281-9xmediapvtltd-9xtashan-samsungin-xz1sd.amagi.tv/playlist/amg01281-9xmediapvtltd-9xtashan-samsungin/playlist.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by trancer1994** [comment]
Here's the file I was able to get https://livegeoroueu.akamaized.net/28072023/smil:9xtashan.smil/playlist.m3u8?dw=60&hdnts=st=1709389113~exp=1709403513~acl=!*/28072023/smil:9xtashan.smil/*!/payload/9xm_5_21691719_NA_IN_NA_9xm_1037/*~hmac=80567424a2aad463945866d84f46a636cb98c0f155394f21fd66bc2b15846335&ud=1037_9xm_21691719_live_-1_-1&b=100-2500 But on VLC it doesn't work

Or go to the official site and rip the URL from there https://www.9xtashan.in/live/
