### ISSUE TITLE
Bangladeshi 🇧🇩 channels need to be updated

### ISSUE THREAD

**Issue by iriyasat** [iptv-org/iptv#1608]
**Country of the channel:**
Bangladesh

https://www.lyngsat.com/packages/Akash-DTH.html

**Channel Name:**
All The channels need to be updated

**Channel Language:**
Bangla

**Additional Information (optional):**

The channels in Bangladesh is out of date. Please add this channels

**Comment by iriyasat** [comment]
#EXTINF:-1,WoW: Gazi Tv
https://itpolly.iptv.digijadoo.net/live/gazi_tv/chunks.m3u8
#EXTINF:-1,WoW: Maasranga
https://itpolly.iptv.digijadoo.net/live/maasranga/chunks.m3u8
#EXTINF:-1,Asian TV
https://itpolly.iptv.digijadoo.net/live/asian_tv/chunks.m3u8
#EXTINF:-1,ATN Bangla
https://itpolly.iptv.digijadoo.net/live/atn_bangla/chunks.m3u8
#EXTINF:-1,ATN News
https://itpolly.iptv.digijadoo.net/live/atn_news/chunks.m3u8
#EXTINF:-1,Banglavision TV
https://itpolly.iptv.digijadoo.net/live/bangla_vision/chunks.m3u8
#EXTINF:-1,Boishakhi TV
https://itpolly.iptv.digijadoo.net/live/boishakhi_tv/chunks.m3u8
#EXTINF:-1,BTV World
https://itpolly.iptv.digijadoo.net/live/btv_world/chunks.m3u8
#EXTINF:-1,Channel 9
https://itpolly.iptv.digijadoo.net/live/channel_9/chunks.m3u8
#EXTINF:-1,Channel 24
https://itpolly.iptv.digijadoo.net/live/channel_24/chunks.m3u8
#EXTINF:-1,Channel I
https://itpolly.iptv.digijadoo.net/live/channel_i/chunks.m3u8
#EXTINF:-1,DBC News
https://itpolly.iptv.digijadoo.net/live/dbc_news/chunks.m3u8
#EXTINF:-1,Deepto TV
https://itpolly.iptv.digijadoo.net/live/deepto_tv/chunks.m3u8
#EXTINF:-1,Desh TV
https://itpolly.iptv.digijadoo.net/live/desh_tv/chunks.m3u8
#EXTINF:-1,Duronto TV
https://itpolly.iptv.digijadoo.net/live/duronto_tv/chunks.m3u8
#EXTINF:-1,Ekattor TV
https://itpolly.iptv.digijadoo.net/live/ekattor_tv/chunks.m3u8
#EXTINF:-1,Ekushey TV
https://itpolly.iptv.digijadoo.net/live/ekushey_tv/chunks.m3u8
#EXTINF:-1,Independent TV
https://itpolly.iptv.digijadoo.net/live/independent_tv/chunks.m3u8
#EXTINF:-1,Jamuna TV https://iptv.live
https://itpolly.iptv.digijadoo.net/live/jamuna_tv/chunks.m3u8
#EXTINF:-1,NTV
https://itpolly.iptv.digijadoo.net/live/ntv/chunks.m3u8
#EXTINF:-1,Nagorik TV
https://itpolly.iptv.digijadoo.net/live/nagorik_tv/chunks.m3u8
#EXTINF:-1,RTV
https://itpolly.iptv.digijadoo.net/live/rtv/playlist.m3u8
#EXTINF:-1,SA TV
https://itpolly.iptv.digijadoo.net/live/sa_tv/playlist.m3u8
#EXTINF:-1,Somoy News
https://itpolly.iptv.digijadoo.net/live/somoy_news/chunks.m3u8
#EXTINF:-1,Colors Bangla
https://itpolly.iptv.digijadoo.net/live/colors_bangla_hd/playlist.m3u8

**Comment by freearhey** [comment]
CGTN https://github.com/iptv-org/iptv/blob/858878c95251fd99c78792c40fcf604b2802bfec/channels/cn.m3u#L114-L115

**Comment by freearhey** [comment]
Discovery Turbo India, Discovery Science India, Discovery Channel India, Discovery Kids Southeast Asia, TLC HD India and Animal Planet India cannot be added to the playlist due to claims of the copyright holder. More details here: #1831

**Comment by freearhey** [comment]
B4U Music https://github.com/iptv-org/iptv/blob/858878c95251fd99c78792c40fcf604b2802bfec/channels/in.m3u#L70-L71
Mastiii https://github.com/iptv-org/iptv/blob/858878c95251fd99c78792c40fcf604b2802bfec/channels/in.m3u#L260-L261
NDTV 24x7 https://github.com/iptv-org/iptv/blob/858878c95251fd99c78792c40fcf604b2802bfec/channels/in.m3u#L288-L289
WION https://github.com/iptv-org/iptv/blob/858878c95251fd99c78792c40fcf604b2802bfec/channels/in.m3u#L414-L415
Zee Bollywood https://github.com/iptv-org/iptv/blob/858878c95251fd99c78792c40fcf604b2802bfec/channels/in.m3u#L420-L421
Zee TV https://github.com/iptv-org/iptv/blob/858878c95251fd99c78792c40fcf604b2802bfec/channels/in.m3u#L424-L425

**Comment by freearhey** [comment]
Closed in favor #1980, #1949, #1973, #1943, #1942 and #1934

**Comment by MonuMia1** [comment]
Star Sports Select 2 HD m3u8 links please
