### ISSUE TITLE
Add: RMC Découverte

### ISSUE THREAD

**Issue by OverStyleFR** [iptv-org/iptv#16100]
### Channel ID (required)

RMCDecouverte.fr

### Channel Name

RMC Découverte

### Stream URL (required)

http://s2.callofliberty.fr/direct/RMCDECOUVERTE/manifest.m3u8

### Quality

1080p

### Label

None

### HTTP Referrer

http://callofliberty.fr/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Pointing our playlist as a "stream source" doesn't work.

**Comment by BellezaEmporium** [comment]
http://s2.callofliberty.fr/direct/RMCDECOUVERTE/manifest.m3u8

Referer:http://callofliberty.fr/

**Comment by OverStyleFR** [comment]
How i can get the M3U file for this channel ?
http://callofliberty.fr/tv/24-RMCDECOUVERTE/24-RMCDECOUVERTE.php?09:11_10:08_Les_derniers_secrets_d_Egypte_10:08_10:12_Mission_r%C3%A9paration

**Comment by BellezaEmporium** [comment]
The playlist basically covers the work for you. It does the job from behind. Seems to be some backend shenanigan.

**Comment by OverStyleFR** [comment]
I don't very understand, i'm new about this. How can i watch this channel so ? @BellezaEmporium

**Comment by OverStyleFR** [comment]
> http://s2.callofliberty.fr/direct/RMCDECOUVERTE/manifest.m3u8
> 
> Referer:http://callofliberty.fr/

The link doesn't work 
![image](https://github.com/iptv-org/iptv/assets/94577363/d958c701-269e-41d2-bb0b-623b7433f50d)

**Comment by BellezaEmporium** [comment]
![image](https://github.com/iptv-org/iptv/assets/30985701/2d9d1f03-acd5-478b-8724-e266aa45d73b)
Works for me.

**Comment by OverStyleFR** [comment]
> ![image](https://private-user-images.githubusercontent.com/30985701/310260018-2d9d1f03-acd5-478b-8724-e266aa45d73b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Njg1ODMsIm5iZiI6MTcwOTY2ODI4MywicGF0aCI6Ii8zMDk4NTcwMS8zMTAyNjAwMTgtMmQ5ZDFmMDMtYWNkNS00NzhiLTg3MjQtZTI2NmFhNDVkNzNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDE5NTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjY2Q1MWI1YWZkZmY2MzEyYzk0OTJkMGQzMDEyM2I3ODIzMmFmMWE4YzEwM2I1MmIwN2VlNGMzNzI1MjdhMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7NMJ1LWlR7slLD3sjDuDkL34X1Man-6VmRXAJYAiZI0) Works for me.

What's the command Line ?

**Comment by OverStyleFR** [comment]
I use Threadfin for IPTV on plex.
There is with no buffer :
![image](https://github.com/iptv-org/iptv/assets/94577363/42206806-c15a-4149-994b-6ed77ea2f4e4)

And with buffer VLC :
![image](https://github.com/iptv-org/iptv/assets/94577363/f0e729f4-2040-45ed-a3ca-3f34ae18db21)

And with buffer FFmpeg :
![image](https://github.com/iptv-org/iptv/assets/94577363/956b4b27-f1c7-4ae5-b45a-2e595d07a197)

**Comment by BellezaEmporium** [comment]
Well, maybe the EXTVLCOPT pattern isn't recognized by threadfin.

**Comment by OverStyleFR** [comment]
> Well, maybe the EXTVLCOPT pattern isn't recognized by threadfin.

And VLC ? Not work on VLC too

**Comment by BellezaEmporium** [comment]
Also needs user-agent set to a web browser, ex Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0

**Comment by OverStyleFR** [comment]
> Also needs user-agent set to a web browser, ex Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0
> 

How I can set this on threadfin?

**Comment by BellezaEmporium** [comment]
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0
