### ISSUE TITLE
Add: TNT East

### ISSUE THREAD

**Issue by InsolenceWillow** [iptv-org/iptv#16105]
### Channel ID (required)

TNTEast.us

### Channel Name

TNT East

### Stream URL (required)

http://170.254.18.106/TNT/index.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by givemefreetv** [comment]
Hasn't worked in the last several days.

**Comment by InsolenceWillow** [comment]
> Hasn't worked in the last several days.

Here, use this.
http://fl2.moveonjoy.com/TNT/index.m3u8
