### ISSUE TITLE
Broken: MTV Germany

### ISSUE THREAD

**Issue by bomberzx** [iptv-org/iptv#16120]
### Broken Link

https://0d26a00dfbb1.airspace-cdn.cbsivideo.com/mtvg18ef/master/mtvg18ef.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Not working on the official website either: https://www.mtv.de/live/0h9eak

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by bomberzx** [comment]
I found a working stream, still requires a german vpn
https://0d26a00dfbb1.airspace-cdn.cbsivideo.com/mtvg18ef/master/master_5000.m3u8

**Comment by BellezaEmporium** [comment]
Can confirm https://0d26a00dfbb1.airspace-cdn.cbsivideo.com/mtvg18ef/master/master_5000.m3u8 works with a German VPN.
