### ISSUE TITLE
Add: Tigo Sports Costa Rica

### ISSUE THREAD

**Issue by hackriel** [iptv-org/iptv#16123]
### Channel ID (required)

TigoSports.cr

### Channel Name

Tigo Sports Costa Rica

### Stream URL (required)

https://drqskz1ihsia2.cloudfront.net/out/v1/e30fab906b3a4dd396239b592a0ff5a1/index.m3u8

### Quality

None

### Label

None

### HTTP User Agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

### HTTP Referrer

https://www.tigosports.cr

### Notes

No response

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Geo-blocked to Costa Rica.

**Comment by R4IN2007** [comment]
very geo-blocked protected indeed.
Trying also with a VPN
![Screenshot_20240307_124132_Chrome](https://github.com/iptv-org/iptv/assets/83226646/de823b36-3811-4856-b2a9-70eb5480a6a8)

**Comment by hackriel** [comment]
Any of you who can get an alternative signal?

**Comment by R4IN2007** [comment]
Topic of Tigo Sports there were one from ViX maybe linear? I don't know which signal of Tigo Sports is this.
https://linear-556.frequency.stream/mt/studio/556/hls/master/playlist.m3u8
![Screenshot_20240307_132116_Chrome](https://github.com/iptv-org/iptv/assets/83226646/b4c353c1-f199-48e1-ab21-865dfe2e3d21)

**Comment by hackriel** [comment]
Hello, thank you for your quick response. This is the version of the country "Guatemala". I'm looking for the "Costa Rica" version, it's different programming.

**Comment by Dum4G** [comment]
@hackriel please share a screenshot of this stream working in VLC at least for you

**Comment by BellezaEmporium** [comment]
yep, if it works for you we could say that's a heavy geo-block, but still works for the concerned people.

**Comment by hackriel** [comment]
UPDATE

**Comment by Dum4G** [comment]
So we can't just open it in VLC and custom players right?

**Comment by BellezaEmporium** [comment]
We can't load it, I'm 99% sure you need an account to load this video out. (the Tts might be the key here).

**Comment by BellezaEmporium** [comment]
Removed the tts token as it contains personal information (email and IP logged in).
