### ISSUE TITLE
Add: Canal 10 Durango (XHA-TDT)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#16147]
### Channel ID (required)

Canal10Durango.mx

### Channel Name

Canal 10 Durango

### Stream URL (required)

https://5e50264bd6766.streamlock.net/canal10durango/videocanal10durango/playlist.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
403

**Comment by R4IN2007** [comment]
![Screenshot_20240309_121359_Chrome](https://github.com/iptv-org/iptv/assets/83226646/da69ab19-dc94-494a-8616-b57ec9e8b0b9)
Working fine in Browser & VLC

**Comment by Dum4G** [comment]
also geoblocked from me
