### ISSUE TITLE
Add: El Sonorense

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#16148]
### Channel ID (required)

ElSonorense.mx

### Channel Name

El Sonorense

### Stream URL (required)

https://s5.mexside.net:1936/elsonorense/elsonorense/playlist.m3u8

### Quality

1080p

### Label

Not 24/7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
404

**Comment by R4IN2007** [comment]
Odd. Maybe it's offline, It was working fine yesterday maybe not 24/7?
![Screenshot_20240309_120958_Web Video Caster](https://github.com/iptv-org/iptv/assets/83226646/53e3507c-be07-4ad5-9f3b-48f75720745c)

**Comment by BellezaEmporium** [comment]
Maybe do they only stream at specific times ?

**Comment by R4IN2007** [comment]
Stream was working yesterday whole day maybe 12 hours in the afternoon?

**Comment by R4IN2007** [comment]
Might not be 24/7 and also stream for it's different days.
![Screenshot_20240312_062707_Chrome](https://github.com/iptv-org/iptv/assets/83226646/a62ebee6-e06b-4e1d-a9bc-08ee256b11d7)

**Comment by BellezaEmporium** [comment]
Works, added quality and Not 24/7 tag.
