### ISSUE TITLE
Add: Nayarit Comunica

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#16149]
### Channel ID (required)

NayaritComunica.mx

### Channel Name

Nayarit Comunica

### Stream URL (required)

https://live.iplanay.gob.mx/hls/nayarittv.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
not24/7?

**Comment by R4IN2007** [comment]
Don't think so?
![Screenshot_20240309_121757_Chrome](https://github.com/iptv-org/iptv/assets/83226646/37399481-2cec-40f5-aabe-04bc996aafeb)

**Comment by Dum4G** [comment]
geoblocked from me
