### ISSUE TITLE
Add: AT-X (jp, 720p)

### ISSUE THREAD

**Issue by Jacksonzwang** [iptv-org/iptv#16140]
### Channel ID (required)

ATX.jp

### Channel Name

AT-X

### Stream URL (required)

https://neetball.net/live/neet3.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by solo489** [comment]
It's showing the wrong channel.

**Comment by Jacksonzwang** [comment]
> It's showing the wrong channel.

I doubled check the content, actually it's still at-x, unlike other channel, the at-x doesn't always display tv logo, you can open it on the hour or half o'clock, and it will show at-x logo.

**Comment by Majinkensword** [comment]
No longer works...

**Comment by Jacksonzwang** [comment]
> No longer works...

Well, actually this m3u8 source has subdomain like [sub.neetball.net](https://sub.neetball.net/live/) (sometimes also has [sub2.neetball.net](https://sub2.neetball.net/live/)).
When you view these links through web browser, it will shown the directory view when it can be accessed, then you can view the tv program with the link which ends up with `.m3u8`
However, the availability totally depends on the person who publish this source, and it's not always playing at-x, sometimes it's Tokyo MX 1, sometimes it's TV Tokyo...
