### ISSUE TITLE
Add: Pac-12 | (US)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#16141]
### Channel ID (required)

None

### Stream URL (required)

https://p12n.pac-12.com/v1/master/b6988789cc420a523cc8393d9c7e629c76fece84/p12n_2019_11/index.m3u8

### Quality

None

### Label

None

### Notes

m3u8 needs User Agent ; I forgot if the channel name was Pac-12 Network or Pac-12 Arizona.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
what user agent?

**Comment by BellezaEmporium** [comment]
The only open stream I see is https://v-emt.pac-12.com/ucla4/index.m3u8

Made for special occasion.

**Comment by lrm864** [comment]
> The only open stream I see is https://v-emt.pac-12.com/ucla4/index.m3u8 / https://v-emt.pac-12.com/v1/master/b6988789cc420a523cc8393d9c7e629c76fece84/v-emt/ucla4/index.m3u8?ads.caid=1709845200-2339786&ads.csid=vodnetwork&ads.device=desktop&ads.deviceos=web&ads.fwvcid2=786f5871-dcd2-11ee-b279-6f02c9064210&ads.p12sid=786f5870-dcd2-11ee-b279-6f02c9064210
> 
> Made for special occasion.

Yeah, the free streams is what you're going to get. The paid channels, even though you don't really see a token per se, is actually tokened. Playing in stuff like VLC won't work. Playing inside of the original web browser and computer the stream came from will work.

**Comment by Dum4G** [comment]
unless proven to be otherwise

**Comment by R4IN2007** [comment]
> what user agent?

Late reply...
 
Chromebook Samsung
Mozilla/5.0 (X11;  CrOS x86_64 14816.131.5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
