### ISSUE TITLE
Broken: (XHZHZ-TDT) Canal 24 SIZART - Zacatecas

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#16142]
### Broken Link

https://5ca9af4645e15.streamlock.net/zacatecas/videozacatecas/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

https://5f2c1b0d880e5.streamlock.net/zacatecas/videozacatecas/playlist.m3u8
Link changed
![Screenshot_20240307_141025_Chrome](https://github.com/iptv-org/iptv/assets/83226646/caa5472e-7d6c-46eb-af8a-7c67654f2a1a)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
you can add new link as a new channel right away
