### ISSUE TITLE
FIX: TF1

### ISSUE THREAD

**Issue by Rodri200906** [iptv-org/iptv#16159]
### Channel ID (required)

TF1.fr

### Channel Name

TF1

### Stream URL (required)

https://raw.githubusercontent.com/BG47510/sniftv/main/bouy/t1.m3u8

### Quality

720p

### Label

Geo-blocked

### HTTP Referrer

https://github.com/BG47510/sniftv/tree/main

### Notes

I Test this link and she works ! Test by yourselves. (On a IPTV Player)
![2024_03_10_13 19 21](https://github.com/iptv-org/iptv/assets/131870845/78722acc-c530-4480-963e-d8a60ac129a1)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Uses official sources, works for me. GEO to Europe.

**Comment by Felix1710** [comment]
Im in France and it still don't work

**Comment by Rodri200906** [comment]
Because this link is not configure. But you can try this one . "https://raw.githubusercontent.com/Paradise-91/ParaTV/main/streams/tf1plus/tf1.m3u8" Just replace TF1 by TMC or TFX

**Comment by Felix1710** [comment]
Thats run! THX
