### ISSUE TITLE
YouTube streams broken

### ISSUE THREAD

**Issue by rodrigost23** [iptv-org/iptv#16156]
### Describe your issue

Streams to YouTube channels with "https://ythls.armelin.one" are not working. According to the [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md), we could use a service like [abskmj/youtube-hls-m3u8](https://github.com/abskmj/youtube-hls-m3u8) to stream YouTube channels.

The URL in that repo is https://ythls-v2.onrender.com/ instead. Maybe all streams should be replaced by this URL? 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by user8387884** [comment]
i dont think thats right even i replaced "https://ythls.armelin.one/" with "https://ythls-v2.onrender.com/"
![Screenshot 2024-03-10 140452](https://github.com/iptv-org/iptv/assets/88836122/fe349c32-e0cf-4efa-bf36-eca490d8f7d3)

**Comment by brokenstream** [comment]
Both of the URLs are working fine for me, but about half of the channels I've tried don't work on either of them. More likely it's the streams themselves that are either offline, need a new link, or may not even exist anymore.

**Comment by rodrigost23** [comment]
I tried the first one yesterday and it wasn't even returning the error json for offline streams, just no connection at all. Maybe it was a temporary issue, because now it's working.

**Comment by BellezaEmporium** [comment]
Everything works on my side, might have been some maintenance.

**Comment by ramazansancar** [comment]
Same issue @BellezaEmporium @rodrigost23 @brokenstream @user8387884 

![image](https://github.com/user-attachments/assets/5849aaa9-42bb-4a32-9252-750cb0b64cb8)

Check here: 
```url
https://ythls.armelin.one/channel/UCmMPdW0rtbEI_XyIsMlMnqg.m3u8
```
