### ISSUE TITLE
Broken: jp_primehome.m3u

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#16168]
### Broken Link

https://github.com/iptv-org/iptv/blob/master/streams/jp_primehome.m3u

### What happened to the stream?

Constantly interrupts/lagging

### Notes (optional)

Hey, mods! Some Japanese livestream links became very laggy nowadays especially on several livestream links such as Disney Channel (Japan), TV Tokyo, Tokyo MX 1, BS Nippon TV and several Japanese TV channels too. But how long needs to be fixed.

BTW, what is Prime Home means anyway?

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
It might depend where the streams are being played? Played in vlc & browser works fine with no lag.

**Comment by AVGCFan1995** [comment]
> It might depend where the streams are being played? Played in vlc & browser works fine with no lag.
Thanks for the question! But what is "Prime Home" is?

**Comment by R4IN2007** [comment]
> > It might depend where the streams are being played? Played in vlc & browser works fine with no lag.
> 
> Thanks for the question! But what is "Prime Home" means?

I have no idea. Doing some research and there little bit talk about it but no information on what's is Prime Home

**Comment by BellezaEmporium** [comment]
Chinese provider of Japanese channels for diasporas.

**Comment by Dum4G** [comment]
Nothing we can do about it. Asian channels tend to be streamed from Eastern servers that have latency way too big to be played somewhere else
