### ISSUE TITLE
Add: Nick Jr. (VISION+)

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#16164]
### Channel ID (required)

nickjrhd.id

### Channel Name

ID| Nick. Jr 

### Stream URL (required)

http://198.16.100.90:8278/Nickjr/playlist.m3u8?tid=MFCF1347936613479366&ct=19249&tsum=547e162f9338962a46e76507dbf7d1e4

### Quality

720p

### Label

None

### Notes

Note: removing "tid=MFCF1347936613479366&ct=19249&tsum=547e162f9338962a46e76507dbf7d1e4" will make the stream unstable

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Basically it's tokened.

**Comment by user8387884** [comment]
Dum4g approved the other one... @BellezaEmporium

**Comment by user8387884** [comment]
https://github.com/iptv-org/iptv/issues/16166
