### ISSUE TITLE
Add: Telefe | Argentina

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#16169]
### Channel ID (required)

Telefe.ar

### Channel Name

Telefe

### Stream URL (required)

(https://mitelefe.com/Api/Videos/GetSourceUrl/694564/0/HLS / https://ssl.cloud.telefe.com/Api/Videos/GetSourceUrl/694564/0/HLS)

### Quality

480p

### Label

Geo-blocked

### Notes

Stream URL works fine like a m3u8
Argentina IP Needed to watch
![Screenshot_20240311_174550_VLC](https://github.com/iptv-org/iptv/assets/83226646/4d42a565-549a-4914-bd11-94ae5329df63)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by LondonX** [comment]
Your stream url is malformed!
Which makes the json in `streams.json` has no url
`{"channel":"Telefe.ar","timeshift":null,"http_referrer":null,"user_agent":null}`

**Comment by Plus018** [comment]
https://mitelefe.com/Api/Videos/GetSourceUrl/694564/0/HLS https://ssl.cloud.telefe.com/Api/Videos/GetSourceUrl/694564/0/HLS doesn’t work

**Comment by R4IN2007** [comment]
> https://mitelefe.com/Api/Videos/GetSourceUrl/694564/0/HLS https://ssl.cloud.telefe.com/Api/Videos/GetSourceUrl/694564/0/HLS doesn’t work

"Geo-blocked". Only works using Argentina IP VPN

**Comment by Criis8787** [comment]
any idea where to find without vpn requires ?
