### ISSUE TITLE
Add: CBeebies Asia

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#16166]
### Channel ID (required)

CBeebiesAsia.uk

### Channel Name

CBeebies Asia

### Stream URL (required)

http://198.16.100.90:8278/Cbeebies/playlist.m3u8?tid=ME5E7901951779019517&ct=19225&tsum=03bb5bab7f669081444ce37cda408b8d

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by zhou2117** [comment]
CBeebiesAsia?
