### ISSUE TITLE
Broken: Channels That have the link "http://vod.linknetott.swiftcontent.com"

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#16165]
### Broken Link

http://vod.linknetott.swiftcontent.com/Content/HLS/Live/Channel(ch309)/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Stream Expired on unknown date

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
It's one of Indonesia IP Only m3u8s?
Yeah those are 403 Geo-blocked
The streams are works fine

**Comment by Dum4G** [comment]
> It's one of Indonesia IP Only m3u8s? Yeah those are 403 Geo-blocked The streams are working fine

Can you show me those streams still work fine somewhere?

**Comment by R4IN2007** [comment]
> > It's one of Indonesia IP Only m3u8s? Yeah those are 403 Geo-blocked The streams are working fine
> 
> Can you show me those streams still work fine somewhere?

Kinda choppy because of the VPN
Just to be clear that it works with mobile data then WIFI on Mobile?
VLC:
![Screenshot_20240316_181531_VLC](https://github.com/iptv-org/iptv/assets/83226646/85e0e667-d7de-4ece-bdb9-19e1d989552a)

**Comment by R4IN2007** [comment]
> > > It's one of Indonesia IP Only m3u8s? Yeah those are 403 Geo-blocked The streams are working fine
> > 
> > 
> > Can you show me those streams still work fine somewhere?
> 
> Kinda choppy because of the VPN Just to be clear that it works with mobile data then WIFI on Mobile? (It runs better) Channel: Paramount Network VLC: ![Screenshot_20240316_181531_VLC](https://private-user-images.githubusercontent.com/83226646/313435379-85e0e667-d7de-4ece-bdb9-19e1d989552a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MzQxNjIsIm5iZiI6MTcxMDYzMzg2MiwicGF0aCI6Ii84MzIyNjY0Ni8zMTM0MzUzNzktODVlMGU2NjctZDdkZS00ZWNlLWJkYjktMTllMWQ5ODk1NTJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDAwMDQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYTQxNDhlM2E5ZGI5YzA2MGM5ODNiYjQ1OWIyZjE1MzIwYWQ0YTdlMTg5YmRkZmM2NzBhYjQxNzUwZDhlYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VjkHkBqJzCys7wXeq-fFW8BkuW6PuHKra3ki-VGmz9Y)

http://vod.linknetott.swiftcontent.com/Content/HLS/Live/Channel(ch320)/index.m3u8
![Screenshot_20240316_185522_VLC](https://github.com/iptv-org/iptv/assets/83226646/a390fc73-3850-4542-b72c-81488fb766f5)

http://vod.linknetott.swiftcontent.com/Content/HLS/Live/Channel(ch329)/index.m3u8
![Screenshot_20240316_190047_VLC](https://github.com/iptv-org/iptv/assets/83226646/0d8bb159-243a-4d61-9bb6-62f81f51b22f)

**Comment by rodlian** [comment]
VPN negara mana yang harus saya gunakan? saya berada di Indonesia tapi tidak dapat memutar link itu.
