### ISSUE TITLE
Add: MTV Hits?

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#16180]
### Channel ID (required)

N/A

### Channel Name

MTV HITS

### Stream URL (required)

http://45.88.92.3:80/tr3_MTVHits_SD/index.m3u8?token=test

### Quality

None

### Label

None

### Notes

Some problems here and there but works.
Don't know what country does the m3u8 belongs. (Note: The problem with the stream its the streamer protection 403 token it will play and it will stop when it reached 20 - 30 seconds of stream play and it will automatically go back to normal and repeat)

![Screenshot_20240314_134735_Chrome](https://github.com/iptv-org/iptv/assets/83226646/1f0b3a5b-b23a-48f6-a01f-3ebbb8e88cae)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
What's the point of stream limited in time?
