### ISSUE TITLE
Add: Sport TV1

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#16181]
### Channel ID (required)

SportTV1.pt

### Channel Name

Sport TV1

### Stream URL (required)

http://213.13.16.138/shls/LIVE%24SPORTTV1_HD/index.m3u8?device=TVOS_Live&start=LIVE&end=END

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by trancer1994** [comment]
Is this the official URL or a restreamer?

**Comment by Goldiefresh** [comment]
You can replace the number 1 in the above URL before the _ to 2 or 3 for sport tv 2 and 3 or just remove the number 1 altogether for sport tv x
