### ISSUE TITLE
Add: BBC America East

### ISSUE THREAD

**Issue by InsolenceWillow** [iptv-org/iptv#16194]
### Channel ID (required)

BBCAmericaEast.us

### Channel Name

BBC America East

### Stream URL (required)

https://bcovlive-a.akamaihd.net/4e7f273ae0a04ad6b7d2e543df61e362/us-west-2/6240731308001/playlist.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
[us-west-2](https://bcovlive-a.akamaihd.net/4e7f273ae0a04ad6b7d2e543df61e362/us-west-2/6240731308001/playlist.m3u8)

Are you sure it's East?

**Comment by BellezaEmporium** [comment]
![image](https://github.com/iptv-org/iptv/assets/30985701/344f6082-9fde-4297-9394-d2e3decd464f)

At that show time, it was one of the Rambos.

**Comment by Hammargren85** [comment]
Is it this channel "https://www.bbcamerica.com/schedule??tz=ET&from=2024-03-19"
I think is is an antic road show right now But the series Bones starts soon.

**Comment by R4IN2007** [comment]
That's West alright

**Comment by InsolenceWillow** [comment]
It's from the official live stream, and I'm in the east coast! I thought it was east!
