### ISSUE TITLE
Broken: all us pop app streams

### ISSUE THREAD

**Issue by rushereeeeee** [iptv-org/iptv#16197]
### Broken Link

http://livex.pop-app.live/s4n/poplive/ch560/playlist.m3u8

### What happened to the stream?

Other

### Notes (optional)

It’s all the streams that are completely broken

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Something that is already 6 months old decided to stop working
