### ISSUE TITLE
Argentinian channels

### ISSUE THREAD

**Issue by znc0** [iptv-org/iptv#1620]
**Country of the channel:**
Argentina

**Channel Name:**
Telefe Rosario: http://telefewhitehls-lh.akamaihd.net/i/whitelist_hls@302302/master.m3u8
Telefe Santa Fe: http://telefecanal13hls-lh.akamaihd.net/i/Canal13_SantaFe@399238/master.m3u8
Canal 2 Misiones: http://nd106.republicaservers.com/canal2misiones.mp4
Canal 11 Lapacho: http://stream2.livestreamingservices.com:1935/tvcanal11/tvcanal11/index.m3u8
FTC Canal 3 Formosa: https://stmv1.srvif.com/agenfor/agenfor/playlist.m3u8 
Canal 9 Televida Mendoza: https://5b3050bb1b2d8.streamlock.net/viviloendirecto2/canal9/.m3u8
América Tucúman: http://45.6.4.50:50601/America_Tucuman/video.m3u8
Canal 3 La Pampa: https://5975e06a1f292.streamlock.net:4443/c3lapampa/ngrp:c3lapampa_all/.m3u8
TSN Necochea: https://59c5c86e10038.streamlock.net/8130/8130/playlist.m3u8
Canal de la Ciudad: https://g3.mc-hor.transport.edge-access.net/a08/ngrp:gcba_video4-100042_all/Playlist.m3u8
Ciudad Magazine: https://g1.mc-slo.transport.edge-access.net/a10/ngrp:magazine_live01-100083_all/Playlist.m3u8

**Channel Language:**
Spanish

**Comment by Nintendocustom** [comment]
Please make a pull request

**Comment by themak1985** [comment]
**Working & Added**

#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Spanish" tvg-logo="" group-title="Local",Telefe Rosario
http://telefewhitehls-lh.akamaihd.net/i/whitelist_hls@302302/master.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Spanish" tvg-logo="" group-title="Local",Canal 2 Misiones
http://nd106.republicaservers.com/canal2misiones.mp4
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Spanish" tvg-logo="" group-title="Local",Canal 9 Televida Mendoza
https://5b3050bb1b2d8.streamlock.net/viviloendirecto2/canal9/.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Spanish" tvg-logo="" group-title="Local",América Tucúman
http://45.6.4.50:50601/America_Tucuman/video.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Spanish" tvg-logo="" group-title="Local",Canal 3 La Pampa
https://5975e06a1f292.streamlock.net:4443/c3lapampa/ngrp:c3lapampa_all/.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="" group-title="Local",TSN Necochea
https://59c5c86e10038.streamlock.net/8130/8130/playlist.m3u8

**Not Working**
@znc0 find working links and I will add. Note, these requests should really come in the form of a pull request. 

#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Spanish" tvg-logo="" group-title="Local",Telefe Santa Fe
http://telefecanal13hls-lh.akamaihd.net/i/Canal13_SantaFe@399238/master.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Spanish" tvg-logo="" group-title="Local",Canal 11 Lapacho
http://stream2.livestreamingservices.com:1935/tvcanal11/tvcanal11/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="" group-title="Local",FTC Canal 3 Formosa
https://stmv1.srvif.com/agenfor/agenfor/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Spanish" tvg-logo="Local" group-title="",Canal de la Ciudad
https://g3.mc-hor.transport.edge-access.net/a08/ngrp:gcba_video4-100042_all/Playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Spanish" tvg-logo="Local" group-title="",Ciudad Magazine
https://g1.mc-slo.transport.edge-access.net/a10/ngrp:magazine_live01-100083_all/Playlist.m3u8

**Comment by martinez-x25** [comment]
Telefe santa fe y telefe rosario no andan
