### ISSUE TITLE
Add: TVMu.id

### ISSUE THREAD

**Issue by singkie** [iptv-org/iptv#16202]
### Channel ID (required)

TVMu.id

### Stream URL (required)

https://e.siar.us/live/tvmu.m3u8

### Quality

720p

### Label

Not 24/7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Either not 24/7, either it needs a referrer that we do not have.

Right now, answers 404 with : 

```
<!DOCTYPE html>
<html>
<head>
<title>Broadcastindo Media Server</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Broadcastindo Media Server</h1>
<p><a href="http://broadcastindo.com/">broadcastindo.com</a><br/>
</body>
</html>
```

**Comment by singkie** [comment]
@BellezaEmporium i will check again on another time

**Comment by Dum4G** [comment]
Got it working in VLC as is
![image](https://github.com/iptv-org/iptv/assets/5430116/241ff07b-a3a0-4cee-98ca-c40c87b755ba)

**Comment by BellezaEmporium** [comment]
Works for me too. Was a not 24/7.
