### ISSUE TITLE
Add: Zarok TV

### ISSUE THREAD

**Issue by ozgurkazancci** [iptv-org/iptv#16204]
### Channel ID (required)

ZarokTV.tr

### Channel Name

Zarok TV

### Stream URL (required)

https://zindikurmanci.zaroktv.com.tr/hls/stream.m3u8

### Quality

720p

### Label

None

### Notes

Zarok TV is the Kurdish Kids' satellite TV channel broadcasting 24/7, via Turksat 3A/4A satellite.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Seems to be in playlist
