### ISSUE TITLE
Add:  NatureTime 

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#16205]
### Channel ID (required)

NatureTime.es

### Channel Name

 NatureTime

### Stream URL (required)

https://shls-live-ak.akamaized.net/out/v1/b06a89a463764d3688cda337d40dc5bf/index.m3u8

### Quality

None

### Label

None

### Notes

There's no id for the channel but shares it's epg in iptv-org.github.io
EPG?: https://shahid.mbc.net/en/livestream/nature-time/livechannel-999399

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by CasperMcFadden95** [comment]
https://shls-live-ak.akamaized.net/out/v1/b06a89a463764d3688cda337d40dc5bf/index.m3u8 is the adaptive stream

**Comment by Dum4G** [comment]
need to create ID first to proceed

**Comment by Dum4G** [comment]
>There's no id for the channel

I didn't check that claim
