### ISSUE TITLE
Broken: AT-X (JP)

### ISSUE THREAD

**Issue by solo489** [iptv-org/iptv#16210]
### Broken Link

https://neetball.net/live/neet3.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Jacksonzwang** [comment]
well, seems that it is broken currently☹️

**Comment by BellezaEmporium** [comment]
Neetball seems to be a bit more careful, after the addition to our playlists, on the bandwidth that comes into their servers, which probably is the reason why they're frequently down. Either this, or the main source they have is having severe issues.

**Comment by BellezaEmporium** [comment]
Neet1 (TokyoMX1) works for now
Neet2 (Fuji TV) works too.
Might only be AT-X that works weirdly.
