### ISSUE TITLE
Indians TV channels is not loaded

### ISSUE THREAD

**Issue by nitingit7** [iptv-org/iptv#16219]
### Describe your issue

Channels is not working, and please add some Indian channels too.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by nitingit7** [comment]
@Dum4G 

Is it fixed?

**Comment by Dum4G** [comment]
Tell me what's broken first. I don't buy into nothing works thing
