### ISSUE TITLE
Broken: All jp_primehome.m3u streams

### ISSUE THREAD

**Issue by solo489** [iptv-org/iptv#16215]
### Broken Link

http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=bs07

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by LuaProgram** [comment]
Same issue for me. Also all of the https://ythls.armelin.one streams don't work

**Comment by user8387884** [comment]
they work on my side. maybe because its geo-blocked.
![Screenshot 2024-03-23 104229](https://github.com/iptv-org/iptv/assets/88836122/8d27af16-2b4f-451e-9a63-bffadd58f4f3)

**Comment by Dum4G** [comment]
![image](https://github.com/iptv-org/iptv/assets/5430116/123ab1f2-5696-40d5-884c-84ebc2d6190e)
source recovered
