### ISSUE TITLE
Broken: SPOTV And SPOTV2 Korean

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#16224]
### Broken Link

https://bcovlive-a.akamaihd.net/99545824f51f4c1592b35314c6ece3b0/ap-northeast-1/6271486521001/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

broken link
im trying to find other links

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by user8387884** [comment]
@Dum4G

**Comment by ind33deda** [comment]
It would be fixed soon

**Comment by ind33deda** [comment]
I think, i put a stream link with a different feed 🤦‍♂️

**Comment by ind33deda** [comment]
But it's okay
