### ISSUE TITLE
Add: Cartoon Network HD SEA

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#16222]
### Channel ID (required)

CartoonNetwork.ph

### Channel Name

Cartoon Network Asia FHD

### Stream URL (required)

http://198.16.100.90:8278/Cn/playlist.m3u8?tid=MCDC2144535021445350&ct=19225&tsum=32569c846de798e3502372d35d00773f

### Quality

1080p

### Label

Geo-blocked

### Timeshift

-1

### Notes

Geoblocked: Japan, Philippines (buffering a little)
![Screenshot 2024-03-23 111453](https://github.com/iptv-org/iptv/assets/88836122/bfef97e3-d302-4f6c-b110-08972fb7988f)
![Screenshot 2024-03-23 111632](https://github.com/iptv-org/iptv/assets/88836122/f136d3b2-6000-4919-85ab-727e85efd572)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by user8387884** [comment]
@Dum4G

**Comment by ind33deda** [comment]
![2754605F-0168-406B-A150-E912E8A47E32](https://github.com/iptv-org/iptv/assets/164004041/6b248a8f-9d1f-4503-973d-7ae604a7f41e)

Didn't work?

**Comment by baldi0899** [comment]
I found working one https://cdn2.skygo.mn/live/disk1/Cartoon_Network/HLS-FTA/Cartoon_Network.m3u8

**Comment by jyle635** [comment]
When I open the file It was a video file but It did not play it because there is something wrong I don't know what was the Problem

**Comment by jyle635** [comment]
> I found working one https://cdn2.skygo.mn/live/disk1/Cartoon_Network/HLS-FTA/Cartoon_Network.m3u8

When I open the file It was a video file but It did not play it because there is something wrong I don't know what was the Problem

**Comment by baldi0899** [comment]
> > I found working one https://cdn2.skygo.mn/live/disk1/Cartoon_Network/HLS-FTA/Cartoon_Network.m3u8
> 
> When I open the file It was a video file but It did not play it because there is something wrong I don't know what was the Problem

It Working for me, what's issue
