### ISSUE TITLE
Add: SPOTV Asia

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#16225]
### Channel ID (required)

SPOTV.kr

### Channel Name

SPOTV HD

### Stream URL (required)

http://202.150.161.68/spotv1/index.m3u8

### Quality

720p

### Label

None

### Timeshift

-1

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
SPOTV2
http://202.150.161.68/spotv2/index.m3u8

**Comment by ind33deda** [comment]
Done

**Comment by Jatpur** [comment]
kontol
