### ISSUE TITLE
Add: BBC News Asia Pacific (720p)

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#16230]
### Channel ID (required)

BBCNewsAsiaPacific.jp

### Channel Name

BBC News Asia Pacific

### Stream URL (required)

http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=cs15

### Quality

720p

### Label

None

### Notes

I found the Japanese feed of BBC News Asia Pacific but some shows and news that contains Japanese voice-overs and subtitles. I hope you should add it on https://github.com/iptv-org/iptv/blob/master/streams/jp_primehome.m3u.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
https://github.com/iptv-org/iptv/blob/03b2ad6394121e843b4512b16b2da9745768f3c5/streams/uk.m3u#L26-L27
