### ISSUE TITLE
7/8 TV Bulgaria

### ISSUE THREAD

**Issue by ta4opleven** [iptv-org/iptv#1623]
**Country of the channel:**
Bulgaria
**Channel Name:**
7/8 TV
**Channel Language:**
Bulgarian
**Additional Information (optional):**
#EXTINF:-1,7/8 TV
https://ms2.sedemosmi.tv/live/index.m3u8
https://ms1.sedemosmi.tv/live/index.m3u8

**Comment by freearhey** [comment]
@ta4opleven If you want to add some channels to the playlist you can do it yourself, just read this guide before: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#add-channel
