### ISSUE TITLE
Add: FuboSportsNetwork.us

### ISSUE THREAD

**Issue by singkie** [iptv-org/iptv#16237]
### Channel ID (required)

FuboSportsNetwork.us

### Stream URL (required)

http://cdnmax.pro/live/S45C43U81V36R5/5ZS04ERNG2DCVPWG/96261.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
xtream code (https://cdnmax.pro/S45C43U81V36R5/5ZS04ERNG2DCVPWG/96261) usually these go down when expired
