### ISSUE TITLE
Add: Reuters TV

### ISSUE THREAD

**Issue by codeautoplay** [iptv-org/iptv#16246]
### Channel ID (required)

ReutersTV.us

### Channel Name

Reuters TV

### Stream URL (required)

https://news.codeautoplay.workers.dev/?codeby=nd&channel=reuters

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Can't confirm working in VLC @BellezaEmporium @Alstruit

**Comment by BellezaEmporium** [comment]
https://amg00453-reuters-amg00453c1-xumo-us-2073.playouts.now.amagi.tv/reuters-reuters-hls/playlist.m3u8

**Comment by Sphinxroot** [comment]
xumo
