### ISSUE TITLE
Add: AKTV.id

### ISSUE THREAD

**Issue by singkie** [iptv-org/iptv#16247]
### Channel ID (required)

AKTV.id

### Stream URL (required)

https://e.siar.us/live/aktv.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ind33deda** [comment]
![D393806A-C9EF-46A8-92EC-41694D91FE30](https://github.com/iptv-org/iptv/assets/164004041/7bc0db00-806f-4b71-99f4-19e773c7f0df)
Not geo-blocked, it's fine
