### ISSUE TITLE
Add: BBC News (North America)

### ISSUE THREAD

**Issue by codeautoplay** [iptv-org/iptv#16245]
### Channel ID (required)

BBCNewsNorthAmerica.uk

### Channel Name

BBC News (North America)

### Stream URL (required)

https://d2vnbkvjbims7j.cloudfront.net/containerA/LTN/playlist.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
https://d2vnbkvjbims7j.cloudfront.net/containerA/LTN/playlist.m3u8

**Comment by spotanjo3** [comment]
Its dead.. with EN subtitles.
