### ISSUE TITLE
Remove: CBeebies Latin America

### ISSUE THREAD

**Issue by cysjunk** [iptv-org/iptv#16252]
This channel has been closed since 2017. 
"On 13 April 2017, the localised CBeebies feed for Latin America ceased operations along with BBC Earth and BBC Entertainment." ([Wikipedia](https://en.wikipedia.org/wiki/CBeebies))

**Comment by Alstruit** [comment]
Database issue. Please make an issue over [there](https://github.com/iptv-org/database).
