### ISSUE TITLE
Broken: Ada TV (Turkish)

### ISSUE THREAD

**Issue by murtisoft** [iptv-org/iptv#16256]
### Broken Link

https://edge1.socialsmart.tv/adatv/bant1/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Replacement: https://yayin1.canlitv.day/live/kibrisadatv.stream/playlist.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ind33deda** [comment]
fixed
