### ISSUE TITLE
Broken: A Para (Turkish)

### ISSUE THREAD

**Issue by murtisoft** [iptv-org/iptv#16255]
### Broken Link

https://ythls.armelin.one/channel/UCzrGg6iyRDuUSnO0cQ5oLcA.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Replacement: https://trkvz-live.ercdn.net/aparahd/aparahd.m3u8?st=K8yWkgSY8zfYUIsBXH3Iiw&e=1711638338

Not sure if you guys accept links with parameters like this.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
The replacement is tokenized.
