### ISSUE TITLE
Add: CBBC HD

### ISSUE THREAD

**Issue by cysjunk** [iptv-org/iptv#16268]
### Channel ID (required)

CBBCHD.uk

### Channel Name

CBBC HD

### Stream URL (required)

http://83.97.18.189:4206/bysid/6972

### Quality

1080p

### Label

Not 24/7

### Notes

Doesn't work during off-air hours (19:00 to 07:00 GMT)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by cysjunk** [comment]
This is not an Xtreme Codes link. It has no username or password attached to it.

**Comment by kaikyoofers** [comment]
@Carlinhos027 will the bot add this, im asking this because i didnt see anything from the bot lately, i can add it myself

**Comment by kaikyoofers** [comment]
Hold up nevermind

**Comment by Carlinhos027** [comment]
> Hold up nevermind

Bot doesn't work on database.
