### ISSUE TITLE
Add: CBeebies (Poland)

### ISSUE THREAD

**Issue by cysjunk** [iptv-org/iptv#16263]
### Channel ID (required)

CBeebies.pl

### Channel Name

CBeebies (Poland)

### Stream URL (required)

http://muka03.wanicelife.com:8880/3ca7153n01/sdfr34r34/33386

### Quality

576p

### Label

None

### Notes

Stream closes after one minute of playback

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
xtream code link

**Comment by Rguanchez** [comment]
http://185.236.229.62:9981/play/a06s
