### ISSUE TITLE
Broken: Lolokoko streams

### ISSUE THREAD

**Issue by cysjunk** [iptv-org/iptv#16262]
### Broken Link

All links that start with https://cdn-nvm-chicago.lolokoko.tv/

### What happened to the stream?

Other

### Notes (optional)

All lolokoko.tv streams currently showing this image with no additional context given
![vlcsnap-2024-03-28-13h10m17s199](https://github.com/iptv-org/iptv/assets/89982841/c9e0fba1-e710-4634-90d9-459874af8ecc)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Rguanchez** [comment]
Yeah

**Comment by Rguanchez** [comment]
![image](https://github.com/iptv-org/iptv/assets/163064733/c58688a0-4edb-4ba1-916b-e2dab4cf4f72)

**Comment by user8387884** [comment]
must be a fake stream

**Comment by BellezaEmporium** [comment]
I *know* how to fix them, but this would reveal another server that they could close. I guess it's bye bye.

**Comment by cysjunk** [comment]
> I _know_ how to fix them, but this would reveal another server that they could close. I guess it's bye bye.

Would you be able to message me with the fix?

**Comment by BellezaEmporium** [comment]
> > I _know_ how to fix them, but this would reveal another server that they could close. I guess it's bye bye.
> 
> Would you be able to message me with the fix?

I'm afraid I cannot.

**Comment by cysjunk** [comment]
> > > I _know_ how to fix them, but this would reveal another server that they could close. I guess it's bye bye.
> > 
> > 
> > Would you be able to message me with the fix?
> 
> I'm afraid I cannot.

It's alright.

**Comment by uqlel** [comment]
This issue was closed, but the issue persists, I mentioned this on [this issue](https://github.com/iptv-org/iptv/issues/16284). The solution for me is to remove the streams from lolokoko

**Comment by NagraniaTelewizji** [comment]
Jak naprawić sygnał

aby mieć wszystkie kanały to zmień cdn-nvm-chicago.lolokoko.tv na cdn-main.lolokoko.tv 

Wszystko będzie Ci działać.

**Comment by NagraniaTelewizji** [comment]
To Have all Poland channels, change cdn-nvm-chicago.lolokoko.tv to cdn-main.lolokoko.tv

All Channels on working

**Comment by campones** [comment]
I notice it's loading much faster. probably their servers are being heavily hitted ..  this explains that

**Comment by uqlel** [comment]
Someone added [pl-lolokoko.m3u file](https://github.com/iptv-org/iptv/blob/master/streams/pl_lolokoko.m3u) to the repo, and it works perfectly, when will it be merged with the main pl.m3u file though?

**Comment by BellezaEmporium** [comment]
> Someone added [pl-lolokoko.m3u file](https://github.com/iptv-org/iptv/blob/master/streams/pl_lolokoko.m3u) to the repo, and it works perfectly, when will it be merged with the main pl.m3u file though?

When it's a single Host having multiple channels, in order for us to better maintain the playlists, we separate them in an other playlist. Though this doesn't mean it's not in the PL playlist (on the generated file)

**Comment by uqlel** [comment]
So it will be in the playlist at 12am ETC, right?

**Comment by xcbly** [comment]
thanks

**Comment by PolandTV** [comment]
cdn-main.lolokoko.tv streams is 403 forbidden

**Comment by cysjunk** [comment]
cdn.lolokoko.tv also seems to be broken. I opened the link in my browser and it gave me a 500 error. 
I did find another CDN they were using but I'm not sure if I should send it just in case it gets pulled down like these ones did.

**Comment by uqlel** [comment]
Well, you can add it, its better than nothing, right? It can help some people and we will just keep searching for new ones if it gets taken down

**Comment by campones** [comment]
if you do that you know already that within a week it will be disabled.  right?

**Comment by NagraniaTelewizji** [comment]
lolokoko.tv streams is 403 forbidden

**Comment by uqlel** [comment]
Maybe, maybe not, the first one was working for a long time AFAIK. These channels are the ones people enjoy the most and its mostly terrestrial TV which anyone can receive, so not being able to stream it as M3U IPTV sucks.

**Comment by BellezaEmporium** [comment]
Better not add them, i've seen they've been actively checking the repo and putting down any links that comes public.

**Comment by uqlel** [comment]
If they don't want to make it public they should just add authentication and not play with us, smh.

**Comment by campones** [comment]
hello I' m interested in knowing the new ip/hostname that is valid because the former one is dead for a couple of days.

djionut@gmx.fr   

thank you
