### ISSUE TITLE
Why are all these US channels listed in the code (Disney plus, food channel, etc) but when I download and view the channel list there’s barely any American shows?

### ISSUE THREAD

**Issue by bluetoo55** [iptv-org/iptv#1626]
In this [update](https://github.com/iptv-org/iptv/commit/f12cd24aa7a4ebd4c0f59bb161e1f98cfd46f39f) back In April it has a ton of normal cable channels listed and I have none of them

**Comment by bluetoo55** [comment]
In this  back In April it has a ton of normal cable channels listed and I have none of them

**Comment by exodiver** [comment]
Those are stolen links from iptv provider users.

**Comment by freearhey** [comment]
The code you're referring to is out of date. 

The fact is that GitHub stores not only the latest version of each file, but also all its previous versions.
