### ISSUE TITLE
Add: Quran Tv Live Urdu 

### ISSUE THREAD

**Issue by 420Voidz** [iptv-org/iptv#16275]
### Channel ID (required)

QuranTvLiveUrdu

### Channel Name

Quran Tv Live Urdu

### Stream URL (required)

https://video-weaver.yto01.hls.ttvnw.net/v1/playlist/CsIFwTNTl1sRMkPH3tl5-2ahFvpQ8X6uwY9u_Kqo8qSMbEjO6nUUhUA-ubELEtuuaiQSVWqg-Tzo5MMk0tpokRCTQFWQVB1x2h8bEL2QVT-OLqv8Pml09AEaMyqbpJGtbxFbXfNn8U6GAKzciGxkqVRczx6rATKuobZaz_772EnjWx-Kjwgg1Q0p3fr2R3aL3TBm0aj00fF7rOaKVx2d6P141ZwVEM3URNPv7SFhqtf749L66I63Z98u3qmWUYEV_QEAA6GbamLAkyTx6vozyvbQByTK614zuy3B3qh22KGNTNCD5YmphjRn3ul5gwLzIipXm7I_GxdbY5heaEE6U9ZFiNBc__Rh7YM5vIcnA_VWn3zA5IQgy_7QwhSD95a6ZokJJr5fzdTCwUlBFjlbJ8uefLrcWxSNA_p5aAvlf6RyxxcHvlqUwdRrcXKhSNoFI56i4c3z1Qr9DSykYISrD5AVJM1DeH6mEPPgTIuQp5pGXZ7BsoCBi33Ndt7YVYCfjoKYZAbak_31BcOxPCyXQYYimc2YHda6eKD96La0NLpa1jKOlHCEYX0KQd98hz9HUrnLJWvAZ6ow-HAKjcD0fBvgJ_a9sPaEp5wzp9zibOu6rleZut9IhHM-Z_jL--nbdLKLMNtW3VLJ_2ozTPaIW7Ns4d3XbH801MXmRWaN5wEriuJcomVwOzawE2gi2r0Xbwy_9mlxPWvI9iUchdjhvIvQY9BaY0PPc01p6zlhJXSHJekwn4QQvaQaOi92HMOEb3yMdrGgmXdlk0ZVuVm-pn_1fHN9afOK2p4059eO2DF20GzCEbWTjy2vLnVU9R0t3jBSUhac3d0mKkRsdrRzUDd25cRmRuIZLKGzhGgQdGdjGNH3kmjm2cns1zQM5rE_MYMmHpIN2KViZMqpzlbuXX_sdEkoC2Bnomcxe1ZQDfbd3mUYMhoM32UYtK8zexgDpMrBIAEqCXVzLWVhc3QtMjCGCQ.m3u8

### Quality

720p

### Label

Not 24/7 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Tokenized Link. Not acceptable.
