### ISSUE TITLE
Add: BBC ALBA HD 

### ISSUE THREAD

**Issue by cysjunk** [iptv-org/iptv#16270]
### Channel ID (required)

BBCALBAHD.uk

### Channel Name

BBC ALBA HD

### Stream URL (required)

http://83.97.18.189:4224/bysid/8927

### Quality

1080p

### Label

None

### Notes

Confirmed working as of 28 March 2024:
![vlcsnap-2024-03-28-21h19m31s234](https://github.com/iptv-org/iptv/assets/89982841/f956756a-1c01-46c8-a4de-0fca4e09dd99)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by user8387884** [comment]
how is that considered as xtream codes when there is no user and pass
