### ISSUE TITLE
Add: hbo

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#16288]
### Channel ID (required)

HBOAsiaHD.sg

### Channel Name

HBO

### Stream URL (required)

 https://z88.ubtvfans.com/live/rx1/332/e5efbdc49c26d46e0559df52a8a03d19/index.m3u8

### Quality

1080p

### Label

Geo-blocked

### Notes

sorry for the invalid id

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ind33deda** [comment]
tokenized link?
