### ISSUE TITLE
Broken: All channels from cdn-nvm-chicago.lolokoko.tv

### ISSUE THREAD

**Issue by uqlel** [iptv-org/iptv#16284]
### Broken Link

All from cdn-nvm-chicago.lolokoko.tv

### What happened to the stream?

Shows looped video

### Notes (optional)

It shows an looped video with this frame 
![Screenshot_20240330_074457_VLC](https://github.com/iptv-org/iptv/assets/59146379/0f182039-a0de-47f1-8026-f5fdd3ac4fd5)
and [this song](https://www.youtube.com/watch?v=t6-cCh9bTG4) in background. I tested a few from Polish/Poland channels. It seems that most of them use this domain and show this. I've tried to connect from VPN in Poland and an Polish residental IP.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by campones** [comment]
I ll  miss  redlight

**Comment by Alstruit** [comment]
#16262

**Comment by uqlel** [comment]
Oh right, it was resolved but the channels are still in the playlists (perhaps not merged or smth) but is there a possibility to get more up-to-date playlists

**Comment by Alstruit** [comment]
> Oh right, it was resolved but the channels are still in the playlists (perhaps not merged or smth) but is there a possibility to get more up-to-date playlists

All changes are reflected every midnight UTC.
