### ISSUE TITLE
Broken: TVP and Polsat channels (PL)

### ISSUE THREAD

**Issue by WlloX** [iptv-org/iptv#16296]
### Broken Link

Https://iptv-org.github.io/iptv/countries/pl.m3u

### What happened to the stream?

Other

### Notes (optional)

So basically, these channels (and a few others) get a image of a crossed out thief while "Capone - Oh no" plays in the backgrond
Preview below.
![Screenshot_20240331-183959](https://github.com/iptv-org/iptv/assets/88002838/56f229bc-f23e-4514-8fc8-86f8754e2cdc)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by WlloX** [comment]
I have collected a list of the channels:
- Disney Junior
- Disney XD
- BBC First 
- Nick Jr.
- Nuta TV
- Polo TV
- All of the Polsat Channels
- Puls 2
- Stopklatka TV
- TV Puls
- TV Trwam
- All of TVP
-

**Comment by Alstruit** [comment]
#16284,#16262
