### ISSUE TITLE
Add: Hare Krsna TV

### ISSUE THREAD

**Issue by codeautoplay** [iptv-org/iptv#16294]
### Channel ID (required)

HareKrsnaTV.in

### Channel Name

Hare Krsna TV

### Stream URL (required)

https://shemaroo.codeautoplay.workers.dev/?codeby=nd&channel=harekrsnatv

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Please make sure to test your wrapper in VLC. For some reason it doesn't work when your link is used but direct links obtained do work

**Comment by Dum4G** [comment]
I do test in VLC and it errors me this

main debug: resolving shemaroo.codeautoplay.workers.dev ...
gnutls debug: TLS handshake: Resource temporarily unavailable, try again.
main error: TLS session handshake timeout
main error: connection error: Resource temporarily unavailable
main error: TLS session handshake timeout
main error: connection error: Resource temporarily unavailable

In browser playlist file retuns as usual

**Comment by peligro22** [comment]
Xxx

**Comment by Sphinxroot** [comment]
https://cdn.live.shemaroome.com/harekrsnatv/smil:harekrsnatvadp.smil/playlist.m3u8?hdnts=st=1712966464~exp=1712977264~acl=*~data=testdata~hmac=+TOKEN
