### ISSUE TITLE
Broken: Al-Iman TV (Indonesia)

### ISSUE THREAD

**Issue by singkie** [iptv-org/iptv#16306]
### Broken Link

https://tv.rodja.live/aliman/ngrp:HD_all/playlist.m3u8

### What happened to the stream?

Other

### Notes (optional)

removed

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ind33deda** [comment]
it's not removed yet, that means channel aren't added
