### ISSUE TITLE
Add: AXN (Mandarin Chinese Subtitles)

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#16315]
### Channel ID (required)

AXN.sg

### Channel Name

AXN HD (Mandarin Chinese Subtitles)

### Stream URL (required)

https://z88.ubtvfans.com/live/rx1/1066/917914fbe52d479116c9ab03e3045dca/index.m3u8

### Quality

1080p

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ind33deda** [comment]
the stream link its just a token

**Comment by user8387884** [comment]
what?? dum4g approved the hbo one

**Comment by ind33deda** [comment]
weird, i think dum4g allows these stream links that are tokenized

**Comment by user8387884** [comment]
gonna wait for DUM4G To respond if he will approve or not

**Comment by ind33deda** [comment]
nvm, stream plays fine in vietnsm
![Screenshot_20240403-164415](https://github.com/iptv-org/iptv/assets/164004041/20d998cd-c92e-4e5b-9b46-634317d37ed8)

**Comment by R4IN2007** [comment]
Stream URL isn't tokenized

**Comment by ind33deda** [comment]
I'll open this pull request
