### ISSUE TITLE
Add: hd tvn

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#16316]
### Channel ID (required)

tvNAsia.hk

### Channel Name

tvN (台湾版)

### Stream URL (required)

https://z88.ubtvfans.com/live/rx3/2288/6e627b4e8a65eec3773d6f8a33c9648d/index.m3u8

### Quality

1080p

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ind33deda** [comment]
tokenized link lol

**Comment by user8387884** [comment]
bruh

**Comment by user8387884** [comment]
also does this link nhave "token=" on it?

**Comment by ind33deda** [comment]
probably theyre got rejected because tokenized stream link

**Comment by Sphinxroot** [comment]
no token  (720p)
