### ISSUE TITLE
Add: TV Ra Tim Bum 

### ISSUE THREAD

**Issue by Avjuniorluciano** [iptv-org/iptv#16324]
### Channel ID (required)

TVRaTimBum.br

### Channel Name

TV Ra Tim Bum 

### Stream URL (required)

http://esrv.cc:80/eduardo002/72836392/31514.ts

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by user8387884** [comment]
xtream code.

**Comment by ind33deda** [comment]
not approved
