### ISSUE TITLE
Add: Polsat

### ISSUE THREAD

**Issue by TestNintendo** [iptv-org/iptv#16321]
### Channel ID (required)

Polsat.pl

### Channel Name

Polsat

### Stream URL (required)

https://cdn-main.lolokoko.tv/Polsat.stream/playlist.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by user8387884** [comment]
What???? Lolokoko channel  is fixed?

**Comment by olstern01** [comment]
Doesn't work anymore. Sad

**Comment by TestNintendo** [comment]
thanks for the info
