### ISSUE TITLE
Add: TV Globo Nordeste 

### ISSUE THREAD

**Issue by Avjuniorluciano** [iptv-org/iptv#16333]
### Channel ID (required)

TV Globo Nordeste

### Channel Name

TVGloboNordeste.br

### Stream URL (required)

http://server1.s3rv3r.club:25461/live/GNOl5wd4jd/fv19nHiwPr/121.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Xtream code!
(http://server1.s3rv3r.club:25461/GNOl5wd4jd/fv19nHiwPr/121)
