### ISSUE TITLE
Broken: WCIUDT5.us

### ISSUE THREAD

**Issue by TKList** [iptv-org/iptv#16332]
### Broken Link

https://2-fss-1.streamhoster.com/pl_122/206858-4412976-1/chunklist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Not found

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Appears to be [working](https://streamtest.in/logs/https-2-fss-1-streamhoster-com-pl_122-206858-4412976-1-chunklist-m3u8)
