### ISSUE TITLE
Fix the issues of Malaysia EPG

### ISSUE THREAD

**Issue by alexliyu7352** [iptv-org/iptv#1633]
I found that your Malaysia EPG website is no longer valid.(https://freeview.github.io/iptv/epg/tv.xml)
I have found a new EPG website with Malaysian EPG on it, and it is updated daily.(Of course, the above also includes EPG in Hong Kong, Taiwan, UK and other regions)

https://epg.pm

There is an XMLTV address at the bottom of this website page, updated daily.

Hope to replace the lapsed Malaysian EPG address.

**Comment by freearhey** [comment]
@alexliyu7352 If you want to update the EPG link you can do so yourself, just read this guide before doing so: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#add-epg-source
