### ISSUE TITLE
Add: Cartoon Network

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#16338]
### Channel ID (required)

CartoonNetworkAsia.sg

### Channel Name

Cartoon Network HD+

### Stream URL (required)

https://cdn1.skygo.mn/live/disk1/Cartoon_Network/HLS-FTA/Cartoon_Network.m3u8

### Quality

1080p

### Label

Geo-blocked

### Timeshift

-2

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by user8387884** [comment]
wont send the cartoonito one

**Comment by cysjunk** [comment]
Please do send the Cartoonito one

**Comment by user8387884** [comment]
the link is dead

**Comment by user8387884** [comment]
https://cdn1.skygo.mn/live/disk1/Cartoonito/HLS-FTA/Cartoonito.m3u8
link dead on 1/1/24

**Comment by mamosa14** [comment]
I have found Cartoonito , it works under the name Bommerang. https://cdn1.skygo.mn/live/disk1/Boomerang/HLS-FTA/Boomerang.m3u8

**Comment by user8387884** [comment]
bruh

**Comment by R4IN2007** [comment]
Remember that **THESE!** might go down soon.

**Comment by user8387884** [comment]
not planned

**Comment by spotanjo3** [comment]
No English subtitle. :(

**Comment by baldi0899** [comment]
I found working stream https://cdn2.skygo.mn/live/disk1/Cartoon_Network/HLS-FTA/Cartoon_Network.m3u8

**Comment by spotanjo3** [comment]
VLC Player show no closed captioning .

**Comment by baldi0899** [comment]
> VLC Player show no closed captioning .

No, no need for captions

**Comment by baldi0899** [comment]
And if it don't work, you're weak

**Comment by spotanjo3** [comment]
> > VLC Player show no closed captioning .
> 
> No, no need for captions

Pardon me? Did you forgot or something? What about hearing impaired or deaf people? 💔😢

**Comment by baldi0899** [comment]
What you talking about,

**Comment by spotanjo3** [comment]
What ? You dont get it do you ? Hearing impaired people ? Deaf people ? Not subtitle. A closed captioning. (CC). What ?

You said no caption need but are you aware that there are deaf and hard of hearing or hearing impaired exists in the world that would appreciate to read the captioning?

**Comment by baldi0899** [comment]
I meant there are no SUBTITLES in the link you play the stream in

**Comment by baldi0899** [comment]
How are you this dumb

**Comment by spotanjo3** [comment]
Never mind. I found other link that have a closed captioning thank you very
much and its not nice to say dumb 😢🤷🏼‍♂️🤦🏻‍♂️

**Comment by noreplywavetv-eng** [comment]
Not working

**Comment by 2026TVPlus** [comment]
I will try to stream Cartoon Network, Poland version tho.
