### ISSUE TITLE
Channel 8 kurdish

### ISSUE THREAD

**Issue by mamosa14** [iptv-org/iptv#16347]
### Channel ID (required)

Channel8.iq

### Channel Name

Channel 8 Kurdish

### Stream URL (required)

https://live.channel8.com/Channel8-Kurdish/index.fmp4.m3u8

### Quality

1080p

### Label

None

### Notes

Channel 8 works but it need to bypass the Security check

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by olstern01** [comment]
Doesn't work on my end.

**Comment by mamosa14** [comment]
I get that m3u8 file from original source https://channel8.com/english/live-tv it works on a browser but not on vlc player …

**Comment by olstern01** [comment]
Yes it seems that because of Cloudflare, when the m3u8 link is added to a IPTV player it returns "Error: Forbidden". Still looking for a solution.

**Comment by olstern01** [comment]
Sorry I couldn't figure out how to solve this. Maybe other people can help.

**Comment by Sphinxroot** [comment]
referrer:https://channel8.com/english/live-tv
#EXTINF:-1 , CHANNEL8 (1080p) (ADAPTATIVE)  -take about 20sec to load (kodi)-  10sec VLC
https://live.channel8.com/Channel8-Kurdish/index.fmp4.m3u8
#EXTINF:-1 , CHANNEL8  (360p) (No Audio)
https://live.channel8.com/Channel8-Kurdish/tracks-v1/index.fmp4.m3u8
#EXTINF:-1 , CHANNEL8  (720p) (No Audio)
https://live.channel8.com/Channel8-Kurdish/tracks-v3/index.fmp4.m3u8
#EXTINF:-1 , CHANNEL8 (1080p) (No Audio)
https://live.channel8.com/Channel8-Kurdish/tracks-v4/index.fmp4.m3u8
#EXTINF:-1 , CHANNEL8 (Audio Only)
https://live.channel8.com/Channel8-Kurdish/tracks-a1/index.fmp4.m3u8

**Comment by mamosa14** [comment]
unfortunately it doesn't work for med on vlc or my samsung tv

**Comment by ProPontifex** [comment]
I just submitted a database entry for this channel; hopefully, this will help push it along.

**Comment by olstern01** [comment]
Still not working in VLC or an IPTV Player (I used IPTVnator).
