### ISSUE TITLE
IglgroupTv

### ISSUE THREAD

**Issue by Iglgroupplay** [iptv-org/iptv#16348]
### Stream URL (required)

https://vd01.streaminghd.net.ar:3049/hybrid/play.m3u8

### Channel ID

IglgroupTv.ar

### Channel Name

IglgroupTv

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Iglgroupplay** [comment]
Donde lo realizo

**Comment by Carlinhos027** [comment]
> Donde lo realizo

Aquí mismo. Abre una nueva solicitud y elige "add stream" en vez de edit.

**Comment by Iglgroupplay** [comment]
Luego que debo hacer, disculpa mi ignorancia

**Comment by Iglgroupplay** [comment]
me indicaron que duplique el ticket ,

**Comment by Iglgroupplay** [comment]
@tomer @rblopes

**Comment by Iglgroupplay** [comment]
IglgroupTv #16348 Update
