### ISSUE TITLE
Broken: Caracol (No sound)

### ISSUE THREAD

**Issue by Torresmi9294** [iptv-org/iptv#16352]
### Broken Link

http://stream.flynetwifi.com:1935/live/mobile-062/playlist.m3u8

### What happened to the stream?

No sound

### Notes (optional)

No sound but picture is fine.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
There was audio before?

**Comment by Sphinxroot** [comment]
https://www.youtube.com/c/noticiascaracol/live  same or not  ?  geoblocked

**Comment by picoluna1969** [comment]
16352

Op za 13 apr 2024 om 02:23 schreef Sphinx ***@***.***>:

**Comment by R4IN2007** [comment]
> https://www.youtube.com/c/noticiascaracol/live same or not ? geoblocked

News Channel of Caracol, completely different

**Comment by Alstruit** [comment]
#16453
