### ISSUE TITLE
Add: USA NETWORK EAST

### ISSUE THREAD

**Issue by Albert1226** [iptv-org/iptv#16359]
### Channel ID (required)

USANetworkEast.us

### Channel Name

USA Network East

### Stream URL (required)

https://epg.pw/stream/2fcf6ccf3ea06ee148d6829dd34cc45609014f8aa76281a1cff3ed679651172d.ctv

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Xtream Code?
(http://23232.top/play/live.php?mac=00:1A:79:C6:37:1B&stream=45466&extension=ts)
Short-en url from the **.ctv** https://7pal.short.gy/usanetwork
Found here:https://raw.githubusercontent.com/kgasaz/4kuhd/master/sports-channels-4k.m3u
