### ISSUE TITLE
Add: Lotus

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#16356]
### Channel ID (required)

LotusTV.mo

### Channel Name

Lotus Macau HD

### Stream URL (required)

https://cdn1.skygo.mn/live/disk1/Lotus/HLS-FTA/Lotus.m3u8

### Quality

1080p

### Label

Not 24/7

### Timeshift

0

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by voxel-im** [comment]
not geoblocked
