### ISSUE TITLE
Add: Iglgroup Tv

### ISSUE THREAD

**Issue by Iglgroupplay** [iptv-org/iptv#16350]
### Channel ID (required)

IglgroupTv.ar

### Channel Name

IglgroupTv

### Stream URL (required)

https://vd01.streaminghd.net.ar:3049/hybrid/play.m3u8

### Quality

720p

### Label

None

### Notes

IglgroupTv 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Duplicate of https://github.com/iptv-org/iptv/issues/16329

**Comment by Iglgroupplay** [comment]
@BellezaEmporium  Quien me debe aprovar el Url..

**Comment by Iglgroupplay** [comment]
#16350 Update

**Comment by BellezaEmporium** [comment]
![image](https://github.com/iptv-org/iptv/assets/30985701/6578c967-e592-415e-8960-10e7601f22dd)
Still image right now.

**Comment by Iglgroupplay** [comment]
Stream en Linea

**Comment by BellezaEmporium** [comment]
Indeed, works now.

**Comment by Iglgroupplay** [comment]
@BellezaEmporium Who else should approve so that it appears on the IPTV list (.ar)

**Comment by BellezaEmporium** [comment]
It's all good, once it's closed it's on.
