### ISSUE TITLE
Broken: Bandamax

### ISSUE THREAD

**Issue by Albert1226** [iptv-org/iptv#16357]
### Broken Link

https://linear-400.frequency.stream/mt/studio/400/hls/master/playlist.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Linear signals of VIX+ México from TelevisaUnivision aren't working or not online
Here's a list of them.

#EXTINF:-4, Univision LATAM (Panregional)
https://linear-424.frequency.stream/mt/studio/424/hls/master/playlist.m3u8

#EXTINF:-4, Golden Edge
https://linear-407.frequency.stream/mt/studio/407/hls/master/playlist.m3u8

#EXTINF:-4, Golden Plus
https://linear-410.frequency.stream/mt/studio/410/hls/master/playlist.m3u8

#EXTINF:-4, Golden Premier
https://linear-411.frequency.stream/mt/studio/411/hls/master/playlist.m3u8

#EXTINF:-4, Afizzionados
https://linear-348.frequency.stream/mt/studio/348/hls/master/playlist.m3u8

#EXTINF:-4, De Pelicula
https://linear-354.frequency.stream/mt/studio/354/hls/master/playlist.m3u8

#EXTINF:-4, Adrenalina Sports Network
https://linear-393.frequency.stream/mt/studio/393/hls/master/playlist.m3u8

#EXTINF:-4, BandaMax
https://linear-400.frequency.stream/mt/studio/400/hls/master/playlist.m3u8

#EXTINF:-4, bitMe
https://linear-401.frequency.stream/mt/studio/401/hls/master/playlist.m3u8

#EXTINF:-4, De Pelicula Plus+
https://linear-404.frequency.stream/mt/studio/404/hls/master/playlist.m3u8

#EXTINF:-4, Distrito Comedia
https://linear-405.frequency.stream/mt/studio/405/hls/master/playlist.m3u8

#EXTINF:-4, Las Estrellas -1 Hora
https://linear-414.frequency.stream/mt/studio/414/hls/master/playlist.m3u8

#EXTINF:-4, Las Estrellas -2 Horas
https://linear-415.frequency.stream/mt/studio/415/hls/master/playlist.m3u8

#EXTINF:-4, Las Estrellas LATAM
https://linear-416.frequency.stream/mt/studio/416/hls/master/playlist.m3u8

#EXTINF:-4, Telehit
https://linear-417.frequency.stream/mt/studio/417/hls/master/playlist.m3u8

#EXTINF:-4, Telehit Musica
https://linear-418.frequency.stream/mt/studio/418/hls/master/playlist.m3u8

#EXTINF:-4, Telehit Musica Plus
https://linear-419.frequency.stream/mt/studio/419/hls/master/playlist.m3u8

#EXTINF:-4, Unicable
https://linear-423.frequency.stream/mt/studio/423/hls/master/playlist.m3u8

#EXTINF:-4, Tlnovelas
https://linear-421.frequency.stream/mt/studio/421/hls/master/playlist.m3u8

#EXTINF:-4, Televisa Guadalajara
https://linear-402.frequency.stream/mt/studio/402/hls/master/playlist.m3u8

#EXTINF:-4, Televisa Monterrey
https://linear-403.frequency.stream/mt/studio/403/hls/master/playlist.m3u8

**Comment by R4IN2007** [comment]
Don't think this has any backups for Bandamax
https://m3ukodi.com/iptv/m3ukodiplus.php

**Comment by R4IN2007** [comment]
Bandamax linear stream works again!
![Screenshot_20240413_015846_Chrome](https://github.com/iptv-org/iptv/assets/83226646/ed6d5e6d-130a-43ec-ab63-f17cc4218692)

**Comment by Puler2381** [comment]
> Linear signals of VIX+ México from TelevisaUnivision aren't working or not online
> Here's a list of them.
> 
> #EXTINF:-4, Univision LATAM (Panregional)
> https://linear-424.frequency.stream/mt/studio/424/hls/master/playlist.m3u8
> 
> #EXTINF:-4, Golden Edge
> https://linear-407.frequency.stream/mt/studio/407/hls/master/playlist.m3u8
> 
> #EXTINF:-4, Golden Plus
> https://linear-410.frequency.stream/mt/studio/410/hls/master/playlist.m3u8
> 
> #EXTINF:-4, Golden Premier
> https://linear-411.frequency.stream/mt/studio/411/hls/master/playlist.m3u8
> 
> #EXTINF:-4, Afizzionados
> https://linear-348.frequency.stream/mt/studio/348/hls/master/playlist.m3u8
> 
> #EXTINF:-4, De Pelicula
> https://linear-354.frequency.stream/mt/studio/354/hls/master/playlist.m3u8
> 
> #EXTINF:-4, Adrenalina Sports Network
> https://linear-393.frequency.stream/mt/studio/393/hls/master/playlist.m3u8
> 
> #EXTINF:-4, BandaMax
> https://linear-400.frequency.stream/mt/studio/400/hls/master/playlist.m3u8
> 
> #EXTINF:-4, bitMe
> https://linear-401.frequency.stream/mt/studio/401/hls/master/playlist.m3u8
> 
> #EXTINF:-4, De Pelicula Plus+
> https://linear-404.frequency.stream/mt/studio/404/hls/master/playlist.m3u8
> 
> #EXTINF:-4, Distrito Comedia
> https://linear-405.frequency.stream/mt/studio/405/hls/master/playlist.m3u8
> 
> #EXTINF:-4, Las Estrellas -1 Hora
> https://linear-414.frequency.stream/mt/studio/414/hls/master/playlist.m3u8
> 
> #EXTINF:-4, Las Estrellas -2 Horas
> https://linear-415.frequency.stream/mt/studio/415/hls/master/playlist.m3u8
> 
> #EXTINF:-4, Las Estrellas LATAM
> https://linear-416.frequency.stream/mt/studio/416/hls/master/playlist.m3u8
> 
> #EXTINF:-4, Telehit
> https://linear-417.frequency.stream/mt/studio/417/hls/master/playlist.m3u8
> 
> #EXTINF:-4, Telehit Musica
> https://linear-418.frequency.stream/mt/studio/418/hls/master/playlist.m3u8
> 
> #EXTINF:-4, Telehit Musica Plus
> https://linear-419.frequency.stream/mt/studio/419/hls/master/playlist.m3u8
> 
> #EXTINF:-4, Unicable
> https://linear-423.frequency.stream/mt/studio/423/hls/master/playlist.m3u8
> 
> #EXTINF:-4, Tlnovelas
> https://linear-421.frequency.stream/mt/studio/421/hls/master/playlist.m3u8
> 
> #EXTINF:-4, Televisa Guadalajara
> https://linear-402.frequency.stream/mt/studio/402/hls/master/playlist.m3u8
> 
> #EXTINF:-4, Televisa Monterrey
> https://linear-403.frequency.stream/mt/studio/403/hls/master/playlist.m3u8
> 
> There's no response from the link or they are completely dead.
> (Están muertos los links para estos canales)

**Comment by Puler2381** [comment]
> ### Broken Link
> 
> https://linear-400.frequency.stream/mt/studio/400/hls/master/playlist.m3u8
> 
> ### What happened to the stream?
> 
> Not loading
> 
> ### Notes (optional)
> 
> _No response_
> 
> ### Contributing Guide
> 
> - [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

Spn

**Comment by Puler2381** [comment]
> ### Broken Link
> 
> https://linear-400.frequency.stream/mt/studio/400/hls/master/playlist.m3u8
> 
> ### What happened to the stream?
> 
> Not loading
> 
> ### Notes (optional)
> 
> _No response_
> 
> ### Contributing Guide
> 
> - [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

Spain
