### ISSUE TITLE
Add: PancTv.PE 

### ISSUE THREAD

**Issue by leoneljimenez40** [iptv-org/iptv#16354]
### Channel ID (required)

PancTv.Pe

### Channel Name

PANC TV PERU

### Stream URL (required)

https://vidistream.ddns.net/hls/peru.play.m3u8

### Quality

1080p

### Label

None

### Timeshift

-5

### Notes

PANC TV PERU formato variado, entretenimiento 24 horas al dia, 7 dias a la semana. Transmite desde (lima-peru)

![logo panc tv peru](https://github.com/iptv-org/iptv/assets/111053893/231b5a93-fffe-4305-b78e-bb5ff5f75c80)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
#16305

**Comment by R4IN2007** [comment]
Hay un Canal con el mismo nombre pero es de Argentina.
![Screenshot_20240411_092125_Chrome](https://github.com/iptv-org/iptv/assets/83226646/6eee3e8e-e91a-4bbf-9a2e-b1398761fa85)
No lo puden a agregar porque no hay un epg-id para el canal y estan confundido.
https://iptv-org.github.io/?q=Panc
