### ISSUE TITLE
Broken: ATV Sur

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#16364]
### Broken Link

https://d3krdjs7is1y42.cloudfront.net/ATVSur/f05b236d4a4d43b3987d6f5ed5686d6e.sdp/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

ATV Sur is in the pe.m3u file.

Possible replacement: https://alba-pe-atv-atvsur.stream.mediatiquestream.com/tracks-v2a1/mono.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
404

**Comment by Alstruit** [comment]
Fixed: https://alba-pe-atv-atvsur.stream.mediatiquestream.com/index.m3u8
