### ISSUE TITLE
Broken: lolokoko.tv is Broken... Again !

### ISSUE THREAD

**Issue by rickeymandraque** [iptv-org/iptv#16366]
### Broken Link

All links start with https://cdn-nvm-london.lolokoko.tv/

### What happened to the stream?

Other

### Notes (optional)

Like #16015 , #16045 and #16262 , cdn-nvm-london.lolokoko.tv is down, so not really down, the stream is actually redirected.
Less than 20 hours after the update was published, lolokoko.tv changed the address.

Edit: I found the new server.
I don't know if it's a good idea to publish the new server, I think he has set up a script/bot which monitors the publications of iptvg-org and which automatically generates a migration upon detection.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by prolix-pl** [comment]
lolokoko.tv is taken down

they displaying only this on streams
![image](https://github.com/iptv-org/iptv/assets/148585325/9cd32b09-511d-40ea-a802-0626bc7c9db3)

**Comment by PolandTV** [comment]
> ### Broken Link
> All links start with https://cdn-nvm-london.lolokoko.tv/
> 
> ### What happened to the stream?
> Other
> 
> ### Notes (optional)
> Like #16015 , #16045 and #16262 , cdn-nvm-london.lolokoko.tv is down, so not really down, the stream is actually redirected. Less than 20 hours after the update was published, lolokoko.tv changed the address.
> 
> Edit: I found the new server. I don't know if it's a good idea to publish the new server, I think he has set up a script/bot which monitors the publications of iptvg-org and which automatically generates a migration upon detection.
> 
> ### Contributing Guide
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

You will send me a new server lolokoko.tv in a private message?

**Comment by rickeymandraque** [comment]
> You will send me a new server lolokoko.tv in a private message?

I don't think this is possible.
I'm in the process of building some tools that will be more than useful for this playlist.


To be continued...

**Comment by REV937** [comment]
Hi, anyone can send me a new lolokoko server name please ? especially PolandTV and  rickeymandraque 
Thanks in advance

**Comment by rickeymandraque** [comment]
> Hi, anyone can send me a new lolokoko server name please ? especially PolandTV and rickeymandraque Thanks in advance

Wait for it ;)
I'm working on it now.
there is already an address that has leaked, so I can reveal it soon... but not just any way.

**Comment by REV937** [comment]
Mate I've been reading this forum for a long time and you're right too. I just registered today. I still don't know how to send you a PM on this forum and show you something.

**Comment by rickeymandraque** [comment]
> Mate I've been reading this forum for a long time and you're right too. I just registered today. I still don't know how to send you a PM on this forum and show you something.

it's not against you. no worries. :)
I prefer to share it with the whole community even if I am not Polish.

**Comment by REV937** [comment]
Rickey and did you get new  address ?

**Comment by CrowVip** [comment]
Nie ma tutaj opcji PM i nie ma możliwości skontaktować się z kimkolwiek. Macie już może nowy adres ?

**Comment by rickeymandraque** [comment]
> Nie ma tutaj opcji PM i nie ma możliwości skontaktować się z kimkolwiek. Macie już może nowy adres ?

Mam więcej niż jeden serwer i mam też mnóstwo informacji...
Wiem, że to długo, ale proszę o dużo cierpliwości.

Gwoli wyjaśnienia, tworzę własne narzędzia i kiedy zaczynałem, nie wiedziałem, na co się natknę...

Dodatkowo planuję opublikować te narzędzia poza adresami kanałów, więc musi to pozostać legalne i pozbawione błędów.

Ale nie martw się, nowe adresy zostaną przesłane i znajdziesz je tutaj.

English :

I have more than just one server and I also have a lot of information...
I know it's long but I ask for a lot of patience please.

For the small explanation, I create my own tools and when I started I didn't know what I was going to come across...

In addition, I plan to publicly publish these tools in addition to the channel addresses so it must remain legal and without bugs.

But don't worry, the new addresses will be communicated and you will find them right here.

**Comment by R4IN2007** [comment]
The new cdn-****-london.lolokoko.tv have been found!

**Comment by CrowVip** [comment]
How can I get a new address from you?

**Comment by R4IN2007** [comment]
> How can I get a new address from you?

cdn-notpub

**Comment by CrowVip** [comment]
I already had this address. There is no other address ?

**Comment by R4IN2007** [comment]
As of right now there no other address except for that one.

**Comment by REV937** [comment]
@ [R4IN2007

DON'T post here lokoko links, because they're ban by DMCA after 2 days !! 
and in this way you screw up whole system.

**Comment by KubaGitHub2002** [comment]
lolokoko.tv may change the link: the stream is called cdn-????-????.lolokoko.tv ban on DMCA after other days.

**Comment by KubaGitHub2002** [comment]
lolokoko.tv change the link: the stream is called cdn-????-????.lolokoko.tv ban by DMCA after other days.

**Comment by KubaGitHub2002** [comment]
lolokoko.tv change the link: the stream is called cdn-????-????.lolokoko.tv! because they're  ban by DMCA after other days.

**Comment by KubaGitHub2002** [comment]
lolokoko.tv changes the link: the stream is called cdn-????-????.lolokoko.tv! because they're ban by DMCA after other days.

**Comment by CrowVip** [comment]
If not here, where to give this address? There is no option to send a private message here.

**Comment by marry92** [comment]
Can someone write here a subdomain, without the lolokoko.tv part? just the subdomain and we will find the rest.. maybe this will prevent bots from detecting..
If not or if you have any other information, please write to me: mrski92@gmail.com

**Comment by REV937** [comment]
@ Kuba,  can you allow comments to be added on your website or contact you in some way? (Blogger not working)
Also if do you know the beginning of the new link you provided "????-????" then  can you send it to me please "xyv668@gmail.com" Thank you in advance

**Comment by REV937** [comment]
@CrowVip  "If not here, where to give this address? ".
Easy just post your email.

**Comment by motylrtb** [comment]
Hi,
I will be very grateful if you send the subdomain to the following address: motylrtb@wp.pl Thanks
