### ISSUE TITLE
Broken: ATV.pe

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#16362]
### Broken Link

https://d3krdjs7is1y42.cloudfront.net/ATVpe/df13ed57843877b21ad969184ab6888f.sdp/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Possible replacement: https://alba-pe-atv-atv.stream.mediatiquestream.com/tracks-v2a1/mono.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Adaptive https://alba-pe-atv-atv.stream.mediatiquestream.com/index.m3u8

**Comment by taxbluesman** [comment]
ese link ya funciona, antes habian mas canales de PERU, tendran una lista de los demas?

**Comment by taxbluesman** [comment]
> Adaptive https://alba-pe-atv-atv.stream.mediatiquestream.com/index.m3u8

funciona

**Comment by taxbluesman** [comment]
> ### Broken Link
> https://d3krdjs7is1y42.cloudfront.net/ATVpe/df13ed57843877b21ad969184ab6888f.sdp/playlist.m3u8
> 
> ### What happened to the stream?
> Not loading
> 
> ### Notes (optional)
> Possible replacement: https://alba-pe-atv-atv.stream.mediatiquestream.com/tracks-v2a1/mono.m3u8
> 
> ### Contributing Guide
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

hola Pedro tendras una lista de canales peruanos actualizados al 2025
