### ISSUE TITLE
Broken: ATV +

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#16363]
### Broken Link

https://linear-258.frequency.stream/dist/vix/258/hls/master/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Possible replacement: https://alba-pe-atv-atvmas.stream.mediatiquestream.com/tracks-v2a1/mono.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Linear streams are down

**Comment by R4IN2007** [comment]
Looks like that ATV+ was removed from VIX and linear stream isn't working for that channel anymore.

**Comment by Alstruit** [comment]
Fixed: https://alba-pe-atv-atvmas.stream.mediatiquestream.com/index.m3u8
