### ISSUE TITLE
Add: KBS Kids

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#16361]
### Channel ID (required)

KBSKids.kr

### Channel Name

KBS Kids

### Stream URL (required)

https://kbsnkids.gscdn.kbs.co.kr/kbsnkids-02/kbsnkids-02_sd.m3u8?Expires=1713076634&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9rYnNua2lkcy5nc2Nkbi5rYnMuY28ua3Iva2JzbmtpZHMtMDIva2JzbmtpZHMtMDJfc2QubTN1OCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxMzA3NjYzNH19fV19&Signature=L4xPfkeTYRIomDpJKXzLfOpxE5IsFIBSXdngH~iRzjIAlHBuQWs47dIwYGaqjDE28NjLMVSh~yNQlCugDc6FEaU7ghS3bTvLYeat9Qiqir15VtzVA7r9VQejs9hsczHNEeTKfEN1UUJ5laYgMHd8pn-37IgGhsBxjtkU34qXKzmgv92~xrr9ESryqfCvlS5vaTsg4l1gRAbdV3nngVkP56g4MIICOPB-xDY-B0Rcd2pkTec4NwV5RM9MUKSeW3dKLyItBJoOpzoRz47XwB-samTR0MEhCdEyHrYs7iyjCq1tmEL6d77Yh6evLEJOEUg0uLkLS-6Tc0EzWUPUnSEluw__&Key-Pair-Id=APKAICDSGT3Y7IXGJ3TA

### Quality

None

### Label

None

### Notes

I just found the livestream link for KBS Kids which is very working on VLC media player but I'm not sure what is the video resolution quality but is it either 360p, 480p, 576p, 720p, 1080p, 1280p or 2160p.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by user8387884** [comment]
Tokenlized Link Lol

**Comment by AVGCFan1995** [comment]
> Tokenlized Link Lol

What is a tokenized link means?
