### ISSUE TITLE
Add: RP TV

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#16373]
### Channel ID (required)

RPTV.ph

### Channel Name

RPTV HD

### Stream URL (required)

https://qp-pldt-live-grp-03-prod.akamaized.net/out/u/cnnph_qp.m3u8

### Quality

1080p

### Label

Not 24/7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by user8387884** [comment]
One sports? no.

**Comment by user8387884** [comment]
might do: philippines_cignalplay

**Comment by MAXBURAOT** [comment]
Dead Link
