### ISSUE TITLE
Add: JapanimTV [New channel]

### ISSUE THREAD

**Issue by rickeymandraque** [iptv-org/iptv#16374]
### Channel ID (required)

JapanimTV.be

### Channel Name

JapanimTV

### Stream URL (required)

https://foxkidstv.be:3369/stream/play.m3u8

### Quality

1080p

### Label

Not 24/7

### Notes

I feel like it's a community channel.
there is no Channel ID so I suggest `JapanimTV.be` or `Japanim.tv`.

There is no official logo, so I propose the logo of the Facebook page `https://static-cdn.jtvnw.net/jtv_user_pictures/6b97e19f-4243-4d48-b794-ff8cf54d795f-profile_image-300x300.png`

The language is French.
There is no EPG.
The official website is: `https://foxkidstv.be/broadcaster/japanimtv/stream/player`

Json :
```json

{
	"id":"JapanimTV.be",
	"name":"Japanim TV",
	"alt_names":[
		
	],
	"network":null,
	"owners":[
		
	],
	"country":"BE",
	"subdivision":null,
	"city":null,
	"broadcast_area":[
	],
	"languages":[
		"fra"
	],
	"categories":[
		"animation",
	],
	"is_nsfw":false,
	"launched":null,
	"closed":null,
	"replaced_by":null,
	"website":"https://foxkidstv.be/broadcaster/japanimtv/stream/player",
	"logo":"https://static-cdn.jtvnw.net/jtv_user_pictures/6b97e19f-4243-4d48-b794-ff8cf54d795f-profile_image-300x300.png"
}
```

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by user8387884** [comment]
i feel like the channel is pretty fake

**Comment by user8387884** [comment]
@Dum4G

**Comment by rickeymandraque** [comment]
> i feel like the channel is pretty fake

I don't know, the fact remains that I have been watching this channel for 1 month, cuts are rare.
I hesitated for a long time before proposing it.
I found a shoutcast webradio associated with this project that has existed at least since 2012.

**Comment by ProPontifex** [comment]
I just submitted a database entry for this request to move this one along: approve or deny as you will.

**Comment by Alstruit** [comment]
Closing in favor #16374.

**Comment by trieuiv** [comment]
stream: https://live-tv-channels.org/watch/japanim-tv
