### ISSUE TITLE
Broken: Almost all of Hong Kong livestream links went dead.

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#16376]
### Broken Link

https://live.astradamy.com/viutv6/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

@BellezaEmporium Just like TVB Jade, almost every livestream links from [Hong Kong SAR, China](https://github.com/iptv-org/iptv/blob/master/streams/hk.m3u) went dead but did you archive any livestream links from agit.ai because the site went dead now.

Likewise, other livestream links from Hong Kong SAR, China went dead for the same reasons.

Creation TV (720p) [Not 24/7] *taken care*

HKIBC *taken care*

HKSTV (香港衛視) (720p) [Not 24/7]
https://al-pull2.hkatv.vip/live/hktv20210929.m3u8

HOY TV (1080p) [Geo-blocked] *taken care*

i-Cable News Channel (有線新聞台) (1080p) [Geo-blocked] *taken care*

J2 (1080p)
http://r.jdshipin.com/Nr5jq

Phoenix Chinese Channel (鳳凰衛視中文) (1080p)
https://playtv-live.ifeng.com/live/06OLEGEGM4G_tv1.m3u8

Phoenix InfoNews Channel (鳳凰衛視資訊) (1080p)
https://playtv-live.ifeng.com/live/06OLEEWQKN4_tv1.m3u8

RTHK (港台電視31) (1080p) [Geo-blocked]
https://cdn.hklive.tv/xxxx/31/index.m3u8

RTHK (港台電視32) (1080p) [Geo-blocked]
https://cdn.hklive.tv/xxxx/32/index.m3u8

RTHK TV 33 (港台電視33) (720p)
https://live.astradamy.com/hk33/index.m3u8

TVB Finance and Sport Channel (720p)
https://cdn.hklive.tv/xxxx/85/index.m3u8

TVB Finance Sports & Information Channel (720p)
https://tvp22.sky4k.top/index2.php

TVB J2
https://j3.lhlh.app/mv.m3u8

TVB J2 (720p)
https://cdn.hklive.tv/xxxx/82/index.m3u8

TVB J2 (720p)
https://live.astradamy.com/tvbj2/index.m3u8

TVB Jade (翡翠台) (720p)
https://cdn.hklive.tv/xxxx/81/index.m3u8

TVB Jade (翡翠台) (720p)
https://live.astradamy.com/tvbfc/index.m3u8

TVB News Channel (720p)
https://cdn.hklive.tv/xxxx/83/index.m3u8

TVB News Channel (720p)
https://tvp22.sky4k.top/index1.php

TVB Pearl (珍珠台) (1080p) [Geo-blocked]
https://cdn.hklive.tv/xxxx/84/index.m3u8

TVB Pearl (珍珠台) (720p)
https://live.astradamy.com/tvbpearl/index.m3u8

ViuTV (1080p) [Geo-blocked]
https://cdn.hklive.tv/xxxx/99/index.m3u8

ViuTVsix
http://61.238.6.49:8000/bysid/96

ViuTVsix (1080p) [Geo-blocked]
https://cdn.hklive.tv/xxxx/96/index.m3u8

ViuTVsix (720p)
https://live.astradamy.com/viutv6/index.m3u8

凤凰中文 (1080p)
http://183.250.157.35:8880/tsfile/live/1000_1.m3u8

凤凰中文 (720p)
http://php.17186.eu.org/phtv/fhzw.m3u8

凤凰资讯 (720p)
http://php.17186.eu.org/phtv/fhzx.m3u8

无线新闻 (720p)
http://r.jdshipin.com/CkuBd

i-Cable 24-hour News Channel (720p)
https://uc6.i-cable.com/live_freedirect/freehd209_h.live/playlist.m3u8

鳳凰衛視資訊台HD (720p) [Not 24/7]
http://117.169.120.138:8080/live/fhzixun/.m3u8

TVB Jade
https://edge6a.v2h-cdn.com/jade/jade.stream/chunklist.m3u8

Can you replace the dead links with new livestream links that was taking from IPTV channels or agit.ai please?

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by AVGCFan1995** [comment]
Hey, @denilsonsa, @tomer and @Daniel15! The mods are not responding to my question about almost all of the Hong Kong livestream links was dead since they can't fix it at all!

**Comment by BellezaEmporium** [comment]
Once i'll get time i'll take a check at it.

**Comment by BellezaEmporium** [comment]
Creation TV is https://cdn.deepcore.online/hlsme/ctv_hk.m3u8

**Comment by BellezaEmporium** [comment]
HKIBC (Hoy International Business Channel) - GEOBLOCKED HK https://hoytv-live-stream.hoy.tv/ch76/va2-index.m3u8

**Comment by AVGCFan1995** [comment]
> HKIBC (Hoy International Business Channel | HOY 國際財經台) - GEOBLOCKED HK https://hoytv-live-stream.hoy.tv/ch76/va2-index.m3u8 / https://hoytv-live-stream.hoy.tv/ch76/index-fhd.m3u8 ![image](https://private-user-images.githubusercontent.com/30985701/328133463-9a2434df-4522-4f86-9f50-f6fdfa2642f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTA0MjMsIm5iZiI6MTcxNDk5MDEyMywicGF0aCI6Ii8zMDk4NTcwMS8zMjgxMzM0NjMtOWEyNDM0ZGYtNDUyMi00Zjg2LTlmNTAtZjZmZGZhMjY0MmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDEwMDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NWNkNTQxZGM5NmRjYzNjNDAwZDMwOTdhNjU4NzNjNDllZTVkNjUxZTI3ODM4Yjg3N2UyMjkyNTYzNTJiM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OHjSI7MvMhTUHqo_72qPeIbntUHE_JIoAAyXI2zuUag) HOY TV - GEOBLOCKED HK https://hoytv-live-stream.hoy.tv/ch77/index-fhd.m3u8 ![image](https://private-user-images.githubusercontent.com/30985701/328133693-404eb341-5a71-4215-986c-50c342bc636c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTA0MjMsIm5iZiI6MTcxNDk5MDEyMywicGF0aCI6Ii8zMDk4NTcwMS8zMjgxMzM2OTMtNDA0ZWIzNDEtNWE3MS00MjE1LTk4NmMtNTBjMzQyYmM2MzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDEwMDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZmYxYjdkMmYxM2E4NmEzOGQ0ODNmYjI5MzA0MjZmNjU0MWE5OTZkMGIwNTgzMzk4ZjhmNzYxMzY4MTg4YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mEH2zrjseUHkBfBNZrPkCX9hoyZgdAZDGAOV0GmUgXg) i-Cable News Ch. - GEOBLOCKED HK https://hoytv-live-stream.hoy.tv/ch78/index-fhd.m3u8 ![image](https://private-user-images.githubusercontent.com/30985701/328133775-d90c9493-7ac7-44c0-b062-3cb731039d44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTA0MjMsIm5iZiI6MTcxNDk5MDEyMywicGF0aCI6Ii8zMDk4NTcwMS8zMjgxMzM3NzUtZDkwYzk0OTMtN2FjNy00NGMwLWIwNjItM2NiNzMxMDM5ZDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDEwMDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MTU3MzI4ZjE5OGYxNTU1NzNjMDE5YmExYTU5ZmIzMGU3YTY5NDJkZjMyYjc3OTBlMDM1YjdlYzlmNTRlNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bKxvCB5AGQSZB3m0MGT5FNcG2JVp6RKRIsPPUHTQZ6A)

Did you archive any livestream links from agit.ai such as TVB Jade, TVB Pearl, ViuTV, ViuTV Six and other TV Channels too?

**Comment by BellezaEmporium** [comment]
Do you mean the https://edge6a.v2h-cdn.com/ streams ? There's a Google cache result leading to those.

**Comment by BellezaEmporium** [comment]
ViuTV is geo-blocked & has DRM. Specific request needs to be made in order to get it.
