### ISSUE TITLE
Add: Panc TV Perú

### ISSUE THREAD

**Issue by panctvtucuman** [iptv-org/iptv#16386]
### Channel ID (required)

PancTVPeru.pe

### Channel Name

Panc TV Peru

### Stream URL (required)

https://panel.host-live.com/80010/80010/chunklist_w1244945356.m3u8

### Quality

1080p

### Label

None

### Timeshift

-5

### HTTP User Agent

https://panel.host-live.com:2020/public/80010

### HTTP Referrer

https://panel.host-live.com:2020/public/80010

### Notes

 El canal de televisión digital Panc TV Perù , ubicado en la provincia de Lima en el departamento Lima, se destaca por ofrecer una programación variada y entretenida que abarca desde noticias locales hasta eventos culturales y deportivos de la región. Con un enfoque en la comunidad local, este canal busca mantener informados a sus televidentes sobre los acontecimientos relevantes y promover el desarrollo y la identidad de la zona. Además, podría ofrecer espacios dedicados a la promoción del turismo y la difusión de tradiciones y costumbres locales.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by PopeyeTheSai10r** [comment]
`PeruPanc.pe` needs to be added to [Database](https://github.com/iptv-org/database)

**Comment by ProPontifex** [comment]
No longer works (from Canada); geo-blocked?

**Comment by panctvtucuman** [comment]
nueva url:  https://panel.host-live.com/ 80010/80010/chunklist_
w1244945356.m3u8
<https://panel.host-live.com/80010/80010/chunklist_w1244945356.m3u8>

**Comment by ProPontifex** [comment]
I cannot seem to find the homepage for the Peruvian version of Panc TV: all I can find is the homepage for the version from Argentina (same thing?).

**Comment by safarifazel29** [comment]
Hello

**Comment by panctvtucuman** [comment]
no es lo mismo hay que agregar un canal nuevo

**Comment by ProPontifex** [comment]
Database entry submitted; still fairly bare bones if anyone else wants to flesh it out, be my guest.

**Comment by Alstruit** [comment]
Closing in favor #16785

**Comment by panctvtucuman** [comment]
Hola le pasamos la nueva URL de (PANC TV PERU)

https://tv.streamcasthd.com:3260/live/pancperulive.m3u8

Desde ya muchas gracias
