### ISSUE TITLE
Add: Music+

### ISSUE THREAD

**Issue by qrde-pl** [iptv-org/iptv#16382]
### Channel ID (required)

MusicPlus.pl

### Channel Name

Music+

### Stream URL (required)

https://hugh.cdn.rumble.cloud/live/4gf18j5s/slot-79/3fqc-ohua/chunklist_DVR.m3u8

### Quality

1080p

### Label

None

### Timeshift

Yes

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by PopeyeTheSai10r** [comment]
Offline or Geo-blocked.

**Comment by qrde-pl** [comment]
> Offline or Geo-blocked.

Sorry, m3u8 has been changed, new one is https://hugh.cdn.rumble.cloud/live/4gf18j5s/slot-79/3fqc-ohua/chunklist_DVR.m3u8
Sorry I can't check if it's geo blocked
