### ISSUE TITLE
Broken: Streams/sv_flynet.m3u

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#16384]
### Broken Link

https://github.com/iptv-org/iptv/blob/master/streams/sv_flynet.m3u

### What happened to the stream?

Not loading

### Notes (optional)

All streams are unavailable to play and on browser its giving a ***403 Forbidden***
![Screenshot_20240416_180355_Chrome](https://github.com/iptv-org/iptv/assets/83226646/1086a1c5-cc4e-4297-8768-fd29f456ee27)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by rickeymandraque** [comment]
Hello,
After taking out my CIA hacker tools, infiltrating the site administrator's house, hiding for a week a day ( yes, i'm very cleaver ! ) in the boss's gardener's dog and stealing the root login I can give you the new address !

`http://stream.flynetwifi.com:1936`

...
Ok... Why are you looking at me like that ? 
...
Ok, ok ... No, I'm kidding, I just tried the port above and it worked (first try ! ).
That's what I would have done as an IT technician to have peace for a while before implementing a solution.

**Comment by JOSUE12SV** [comment]
Hola, no funciona esta lista nuevamente, no se si pueden actualizarla.. Y si es posible, se los agradecere
