### ISSUE TITLE
Add: One Sports HD

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#16389]
### Channel ID (required)

 OneSports.ph

### Channel Name

One Sports FHD

### Stream URL (required)

 https://qp-pldt-live-grp-05-prod.akamaized.net/out/u/onesports_qp.m3u8

### Quality

1080p

### Label

Not 24/7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by fraudiay79** [comment]
You do realize that posting links for subscription channels here means these links will be dead in a matter or days?

**Comment by user8387884** [comment]
Bruh

**Comment by R4IN2007** [comment]
Channels from the Philippines?

**Comment by fotvnetwork** [comment]
> You do realize that posting links for subscription channels here means these links will be dead in a matter or days?

They will

**Comment by user8387884** [comment]
> > You do realize that posting links for subscription channels here means these links will be dead in a matter or days?
> 
> They (the provider) might do that soon

Then how are all these links exposed/at risk on phcorner.net????

**Comment by R4IN2007** [comment]
Satellite than cable being from Cignal.
They won't die but the link will changed

**Comment by babiwi** [comment]
Hahaha. How are the cp links that you are highly sharing in iptvorg? Is it working? This guy just registered here to fork an iptv playlist. What a nutjob. Get a life leecher from a forum site. We know who you are

**Comment by R4IN2007** [comment]
Well, The Cignal m3u8s links are Dead.
![Screenshot_20240508_182304_Chrome](https://github.com/iptv-org/iptv/assets/83226646/a008b786-e7b1-429e-b9be-363baedd0ad9)
Here's a small list of channel links that I had
`#EXTINF:-4, HBO Signature HD (Cignal TV)
https://qp-pldt-live-grp-01-prod.akamaized.net/out/u/hbosighd_qp.m3u8
#EXTINF:-4, Cinemax HD (Cignal TV)
https://qp-pldt-live-grp-01-prod.akamaized.net/out/u/cinemaxhd_qp.m3u8
#EXTINF:-4, PBA Rush HD (Cignal TV)
https://qp-pldt-live-grp-01-prod.akamaized.net/out/u/pbarushhd_qp.m3u8
#EXTINF:-4, HBO HD (Cignal TV)
https://qp-pldt-live-grp-03-prod.akamaized.net/out/u/hbohd_qp.m3u8
#EXTINF:-4, One News HD (Cignal TV)
https://qp-pldt-live-grp-10-prod.akamaized.net/out/u/onenewshd_qp.m3u8
#EXTINF:-4, HBO Hits HD (Cignal TV)
https://qp-pldt-live-grp-09-prod.akamaized.net/out/u/hbohitshd_qp.m3u8
#EXTINF:-4, HITS HD (Cignal TV)
https://qp-pldt-live-grp-08-prod.akamaized.net/out/u/hitshd_qp.m3u8
#EXTINF:-4, BBC Earth HD (Cignal TV)
https://qp-pldt-live-grp-10-prod.akamaized.net/out/u/bbcearthhd_qp.m3u8
#EXTINF:-4, HBO Family HD (Cignal TV)
https://qp-pldt-live-grp-03-prod.akamaized.net/out/u/hbofamilyhd_qp.m3u8
#EXTINF:-4, Premier Football HD (Cignal TV)
https://qp-pldt-live-grp-06-prod.akamaized.net/out/u/premierfootballhd_qp.m3u8
#EXTINF:-4, DreamWorks [English] HD (Cignal TV)
https://qp-pldt-live-grp-02-prod.akamaized.net/out/u/dreamworkshd_qp.m3u8
#EXTINF:-4, Tap Movies HD (Cignal TV)
https://qp-pldt-live-grp-06-prod.akamaized.net/out/u/tapmovieshd_qp.m3u8
#EXTINF:-4, KIX HD (Cignal TV)
https://qp-pldt-live-grp-06-prod.akamaized.net/out/u/kixhd_qp.m3u8
#EXTINF:-4, HGTV HD (Cignal TV)
https://qp-pldt-live-grp-08-prod.akamaized.net/out/u/hgtvhd_qp.m3u8
#EXTINF:-4, Food Network HD (Cignal TV)
https://qp-pldt-live-grp-09-prod.akamaized.net/out/u/foodnetworkhd_qp.m3u8
#EXTINF:-4, BeIN Sports 1 HD (Cignal TV)
https://qp-pldt-live-grp-02-prod.akamaized.net/out/u/beinsports1hd_qp.m3u8
#EXTINF:-4, BeIN Sports 3 HD (Cignal TV)
https://qp-pldt-live-grp-01-prod.akamaized.net/out/u/beinsports3hd_qp.m3u8
#EXTINF:-4, Premier Sports HD (Cignal TV)
https://qp-pldt-live-grp-03-prod.akamaized.net/out/u/premiersportshd_qp.m3u8
#EXTINF:-4, One Sports (Cignal TV)
https://qp-pldt-live-grp-05-prod.akamaized.net/out/u/onesports_qp.m3u8
#EXTINF:-4, One News (Cignal TV)
https://qp-pldt-live-grp-04-prod.akamaized.net/out/u/onenews_qp.m3u8
#EXTINF:-4, One PH (Cignal TV)
https://qp-pldt-live-grp-04-prod.akamaized.net/out/u/oneph_qp.m3u8
#EXTINF:-4, AXN (Cignal TV)
https://qp-pldt-live-grp-06-prod.akamaized.net/out/u/axn_qp.m3u8
#EXTINF:-4, Lifetime (Cignal TV)
https://qp-pldt-live-grp-09-prod.akamaized.net/out/u/lifetime_qp.m3u8
#EXTINF:-4, BuKo (Cignal TV)
https://qp-pldt-live-grp-10-prod.akamaized.net/out/u/buko_qp.m3u8
#EXTINF:-4, PTV (Cignal TV)
https://qp-pldt-live-grp-02-prod.akamaized.net/out/u/ptv_qp.m3u8
#EXTINF:-4, TV5 (Cignal TV)
https://qp-pldt-live-grp-02-prod.akamaized.net/out/u/tv5_qp.m3u8
#EXTINF:-4, IBC 13 (Cignal TV)
https://qp-pldt-live-grp-10-prod.akamaized.net/out/u/ibc13_qp.m3u8
#EXTINF:-4, Pinoy Box Office (Cignal TV)
https://qp-pldt-live-grp-08-prod.akamaized.net/out/u/pinoyboxoffice_qp.m3u8
#EXTINF:-4, Celestial Movies Pinoy (Cignal TV)
https://qp-pldt-live-grp-01-prod.akamaized.net/out/u/celestialmoviespinoy_qp.m3u8
#EXTINF:-4, Thrill (Cignal TV)
https://qp-pldt-live-grp-06-prod.akamaized.net/out/u/thrill_qp.m3u8
#EXTINF:-4, HITS Movies (Cignal TV)
https://qp-pldt-live-grp-06-prod.akamaized.net/out/u/hitsmovies_qp.m3u8
#EXTINF:-4, Paramount Network (Cignal TV)
https://qp-pldt-live-grp-09-prod.akamaized.net/out/u/paramount_qp.m3u8
#EXTINF:-4, Asian Food Network (Cignal TV)
https://qp-pldt-live-grp-05-prod.akamaized.net/out/u/asianfoodnetwork_qp.m3u8
#EXTINF:-4, Travel Channel (Cignal TV)
https://qp-pldt-live-grp-08-prod.akamaized.net/out/u/travelchannel_qp.m3u8
#EXTINF:-4, TLC (Cignal TV)
https://qp-pldt-live-grp-08-prod.akamaized.net/out/u/tlc_qp.m3u8
#EXTINF:-4, BBC Lifestyle (Cignal TV)
https://qp-pldt-live-grp-09-prod.akamaized.net/out/u/bbclifestyle_qp.m3u8
#EXTINF:-4, Animax (Cignal TV)
https://qp-pldt-live-grp-05-prod.akamaized.net/out/u/animax_qp.m3u8
#EXTINF:-4, Cartoonito (Cignal TV)
https://qp-pldt-live-grp-03-prod.akamaized.net/out/u/boomerang_qp.m3u8
#EXTINF:-4, Moonbug (Cignal TV)
https://qp-pldt-live-grp-06-prod.akamaized.net/out/u/moonbugkids_qp.m3u8
#EXTINF:-4, MPTV (Cignal TV)
https://qp-pldt-live-grp-09-prod.akamaized.net/out/u/mptv_qp.m3u8
#EXTINF:-4, Viva Cinema (Cignal TV)
https://qp-pldt-live-grp-06-prod.akamaized.net/out/u/vivacinema_qp.m3u8
#EXTINF:-4, SARI-SARI (Cignal TV)
https://qp-pldt-live-grp-10-prod.akamaized.net/out/u/sarisari_qp.m3u8
#EXTINF:-4, Tap TV (Cignal TV)
https://qp-pldt-live-grp-06-prod.akamaized.net/out/u/taptv_qp.m3u8
#EXTINF:-4, HITS Now (Cignal TV)
https://qp-pldt-live-grp-09-prod.akamaized.net/out/u/hitsnow_qp.m3u8
#EXTINF:-4, Lotus Macau (Cignal TV)
https://qp-pldt-live-grp-05-prod.akamaized.net/out/u/lotusmacau_qp.m3u8
#EXTINF:-4, TVUP (Cignal TV)
https://qp-pldt-live-grp-09-prod.akamaized.net/out/u/tvup_qp.m3u8
#EXTINF:-4, DepEd TV (Cignal TV)
https://qp-pldt-live-grp-04-prod.akamaized.net/out/u/depedtv_qp.m3u8
#EXTINF:-4, Knowledge Channel (Cignal TV)
https://qp-pldt-live-grp-03-prod.akamaized.net/out/u/knowledgechannel_qp.m3u8
#EXTINF:-4, National Geographic (Cignal TV)
https://qp-pldt-live-grp-08-prod.akamaized.net/out/u/nationalgeographic_qp.m3u8
#EXTINF:-4, Animal Planet (Cignal TV)
https://qp-pldt-live-grp-02-prod.akamaized.net/out/u/animalplanet_qp.m3u8
#EXTINF:-4, tvN (Cignal TV)
https://qp-pldt-live-grp-01-prod.akamaized.net/out/u/tvn_qp.m3u8
#EXTINF:-4, GEM (Cignal TV)
https://qp-pldt-live-grp-09-prod.akamaized.net/out/u/gem_qp.m3u8
#EXTINF:-4, Arirang (Cignal TV)
https://qp-pldt-live-grp-01-prod.akamaized.net/out/u/arirang_qp.m3u8`

**Comment by MAXBURAOT** [comment]
Dead Link

**Comment by Elesio08** [comment]
Sinong marunong mag covert ng mpd link to m3u link. Meron kasi akong mga link cignal play pero naka mpd link

**Comment by kashmir6942** [comment]
edi bat nakakalat ang cignal play mpd sa phc? realize it

**Comment by kashmir6942** [comment]
absolute shame, we powerful https://phcorner.org/threads/2530875/
