### ISSUE TITLE
Broken: Caracol [geo-blocked] Link now broken even with vpn

### ISSUE THREAD

**Issue by Torresmi9294** [iptv-org/iptv#16383]
### Broken Link

https://mdstrm.com/live-stream-playlist/574463697b9817cf0886fc17.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Was able to watch with VPN now won't load anymore.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Here u go. Works using VPN
https://mdstrm.com/live-stream-playlist/574463697b9817cf0886fc17/master.m3u8 (https://mdstrm.com/live-stream-playlist/574463697b9817cf0886fc17.m3u8)
it's working through gdai- (dai.google.com)
Just use master.m3u8
![Screenshot_20240416_190004_VLC](https://github.com/iptv-org/iptv/assets/83226646/04a408cc-573b-4bfc-959a-10e031863bf2)
