### ISSUE TITLE
Add:  PremierSports.ph

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#16392]
### Channel ID (required)

 PremierSports.ph

### Channel Name

Premier Sports

### Stream URL (required)

https://qp-pldt-live-grp-03-prod.akamaized.net/out/u/premiersportshd_qp.m3u8

### Quality

1080p

### Label

Geo-blocked

### Notes

website only for philippines

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Doesn't *seem* to be Geo-blocked for me, I can access the channel just fine (with some difficulties on the buffering)

**Comment by MAXBURAOT** [comment]
Dead Link
