### ISSUE TITLE
Add: Tv Famypanc

### ISSUE THREAD

**Issue by panctvtucuman** [iptv-org/iptv#16399]
### Channel ID (required)

TvFamypanc.Es

### Channel Name

Tv Famypanc

### Stream URL (required)

https://vidistream.ddns.net/hls/espana.play.m3u8

### Quality

720p

### Label

None

### Timeshift

+2

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ProPontifex** [comment]
Geo-blocked? (from Canada)

**Comment by Dum4G** [comment]
https://github.com/iptv-org/iptv/pull/16424

**Comment by panctvtucuman** [comment]
nueva url enlace streaming https://panel.host-live.com:19360/8042/8042.m3u8

![famypanc tv](https://github.com/user-attachments/assets/e8ee460e-9a1f-4e6d-ae4b-2fde0899fb16)
