### ISSUE TITLE
Add: Cartoonito SD

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#16391]
### Channel ID (required)

no id yet (cartoonito.ph)

### Channel Name

Cartoonito SD

### Stream URL (required)

https://qp-pldt-live-grp-03-prod.akamaized.net/out/u/boomerang_qp.m3u8

### Quality

360p

### Label

None

### HTTP Referrer

https://cignalplay.com/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by MAXBURAOT** [comment]
Dead Link
