### ISSUE TITLE
Add: HBO Signature Phillippines

### ISSUE THREAD

**Issue by user8387884** [iptv-org/iptv#16390]
### Channel ID (required)

no id yet (HBOSigHD.ph)

### Channel Name

HBO Signature 

### Stream URL (required)

https://qp-pldt-live-grp-01-prod.akamaized.net/out/u/hbosighd_qp.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by MAXBURAOT** [comment]
Dead Link
