### ISSUE TITLE
Broken: AMCPlus.us

### ISSUE THREAD

**Issue by sbm8o** [iptv-org/iptv#16403]
### Broken Link

https://bcovlive-a.akamaihd.net/ba853de442c140b7b3dc020001597c0a/us-east-1/6245817279001/playlist.m3u8

### What happened to the stream?

Shows looped video

### Notes (optional)

The channel is configured in my player using the English playlist https://iptv-org.github.io/iptv/languages/eng.m3u ::

#EXTINF:-1 tvg-id="AMCPlus.us" tvg-logo="https://i.imgur.com/abtANyj.png" group-title="Entertainment",AMC+ (1080p)
https://bcovlive-a.akamaihd.net/ba853de442c140b7b3dc020001597c0a/us-east-1/6245817279001/playlist.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by TKList** [comment]
Where is ShudderTV located?

**Comment by R4IN2007** [comment]
On here nowhere but amcplus has it.

**Comment by TKList** [comment]
Thanks
