### ISSUE TITLE
Broken: BBCAmericaEast.us

### ISSUE THREAD

**Issue by sbm8o** [iptv-org/iptv#16404]
### Broken Link

https://bcovlive-a.akamaihd.net/4e7f273ae0a04ad6b7d2e543df61e362/us-west-2/6240731308001/playlist.m3u8

### What happened to the stream?

Shows looped video

### Notes (optional)

Using it in my player via the English playlist :: https://iptv-org.github.io/iptv/languages/eng.m3u

#EXTINF:-1 tvg-id="BBCAmericaEast.us" tvg-logo="https://i.imgur.com/pTiiPz0.png" group-title="Undefined",BBC America East (720p)
https://bcovlive-a.akamaihd.net/4e7f273ae0a04ad6b7d2e543df61e362/us-west-2/6240731308001/playlist.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by spotanjo3** [comment]
https://bcovlive-a.akamaihd.net/4e7f273ae0a04ad6b7d2e543df61e362/us-west-2/6240731308001/playlist.m3u8 isnt working. If you watched it less than 10 seconds then it stopped. I am looking for west, not east.
