### ISSUE TITLE
Broken: Newsmax (Country playlist)

### ISSUE THREAD

**Issue by sero323** [iptv-org/iptv#16405]
### Broken Link

https://newsmax-plex.amagi.tv/hls/amagi_hls_data_plexAAAAA-newsmax-plex/CDN/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Newsmax not working when using the country playlist....
https://iptv-org.github.io/iptv/index.country.m3u

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
https://amg00217-newsmax-newsmax-zeasn-022k9.amagi.tv/playlist.m3u8
https://newsmax-klowdtv.amagi.tv/playlist.m3u8 though this is geo.
