### ISSUE TITLE
Add: PancTV.pe

### ISSUE THREAD

**Issue by panctvtucuman** [iptv-org/iptv#16400]
### Channel ID (required)

PancTV.pe

### Channel Name

Panc Tv

### Stream URL (required)

https://vidistream.ddns.net/hls/peru.play.m3u8

### Quality

1080p

### Label

None

### Timeshift

-5

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
#16386
