### ISSUE TITLE
Broken: Telemundo US

### ISSUE THREAD

**Issue by danny516x** [iptv-org/iptv#16418]
### Broken Link

https://iptv-org.github.io/iptv/index.m3u

### What happened to the stream?

Not loading

### Notes (optional)

Any alternative? 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Which link, the sv_flynet.m3u or the content.uplynk link? Both works
Looks like that [http://stream.flynetwifi.com:1936] stream alternative or whatever doesn't work anymore. But still works without it.

Both airing El Señor De Los Cielos right now!!
https://content.uplynk.com/channel/b6a96ed39d694ae1b738faa98cf7dd3f.m3u8
![Screenshot_20240423_215155_Kiwi Browser](https://github.com/iptv-org/iptv/assets/83226646/3a0c46bc-f94e-444f-968a-afd4bc9dc29e)

http://168.227.22.18:1936/live/mobile-040/playlist.m3u8
![Screenshot_20240423_215223_Kiwi Browser](https://github.com/iptv-org/iptv/assets/83226646/6aed75cb-bffe-41ee-9817-5b10bfac1014)

**Comment by R4IN2007** [comment]
Here this one coming from TV25. It's has Closed Captions https://cdn.igocast.com/wkrp_channel1_hls/wkrp_channel1_master.m3u8

**Comment by R4IN2007** [comment]
All Three links work as of right now.
