### ISSUE TITLE
Broken: Canal + France

### ISSUE THREAD

**Issue by Pixel-exe** [iptv-org/iptv#16419]
### Broken Link

http://hls-m007.live-lv3.canalplus-cdn.net/live/disk/canalplusclair-hd/hls-ios-fhd-clair/canalplusclair-hd.m3u8 

### What happened to the stream?

Other

### Notes (optional)

ERROR
The requested URL could not be retrieved
The following error was encountered while trying to retrieve the URL: http://hls-m007.live-lv3.canalplus-cdn.net/live/disk/canalplusclair-hd/hls-ios-fhd-clair/canalplusclair-hd.m3u8

Unable to determine IP address from host name hls-m007.live-lv3.canalplus-cdn.net

The DNS server returned:

Name Error: The domain name does not exist.
This means that the cache was not able to resolve the hostname presented in the URL. Check if the address is correct.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
http://hls-m007.live-cft.canalplus-cdn.net/live/disk/canalplusclair-hd/hls-ios-fhd-clair/canalplusclair-hd.m3u8
