### ISSUE TITLE
Broken: M6 from France is broken

### ISSUE THREAD

**Issue by octavioj** [iptv-org/iptv#16415]
### Broken Link

https://shls-m6-france-prod-dub.shahid.net/out/v1/c8a9f6e000cd4ebaa4d2fc7d18c15988/index.m3u8

### What happened to the stream?

Shows looped video

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by campones** [comment]
prob just a bug

**Comment by jcn50** [comment]
Just to clarify: the stream is the exact same scene, that is looping forever~ so **the stream is broken**. 
I suspect that M6 stopped their agreement with Shahid (in Dubaï, UAE).

**Comment by octavioj** [comment]
Thank you. So probably there is no fix for this. Oh well. Thank you for looking into it.
