### ISSUE TITLE
Broken: All Streams from sv_flynet.m3u are broken

### ISSUE THREAD

**Issue by Karl1602** [iptv-org/iptv#16420]
### Broken Link

http://stream.flynetwifi.com:1936/live/mobile-142/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

[0368df00] http stream error: cannot resolve stream.flynetwifi.com: Host desconocido.
[0368df00] access stream error: HTTP connection failure
[0368df00] main stream error: cannot resolve stream.flynetwifi.com port 1936 : Host desconocido.
[0368df00] http stream error: cannot connect to stream.flynetwifi.com:1936

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
http://168.227.22.18:1935/live/mobile-142/playlist.m3u8

/shrug/

**Comment by BellezaEmporium** [comment]
http://isp.flynetwifi.com:1935/live/mobile-142/playlist.m3u8

**Comment by Karl1602** [comment]
The server stream.flynetwifi.com was replaced by isp.flynetwifi.com [168.227.22.18]
the port is 1935
But all the connections throw error 403
[03e3df00] access stream error: HTTP 403 error
[03e3df00] http stream error: error: HTTP/1.1 403 Forbidden

something changed in the HTTP LINK, I don't know if is GEO-BLOCKED, or it needs USER/PW, or change the structure.
:(

**Comment by BellezaEmporium** [comment]
![image](https://github.com/iptv-org/iptv/assets/30985701/3c440e86-3f37-4d40-b0b0-734601cbb662)

It's because you're most certainly switching on "https".

**Comment by JOSUE12SV** [comment]
Hello, notice that I've had that problem too... No channel is working, they are as if they were down

**Comment by R4IN2007** [comment]
Was working fine in the morning.
![Screenshot_20240425_192456_Chrome](https://github.com/iptv-org/iptv/assets/83226646/4a1c36f1-df07-424d-8480-028f40046cee)

**Comment by JOSUE12SV** [comment]
Yes, maybe in the morning with the solution that the user provided, it worked correctly, since the afternoon, it didn't work anymore

**Comment by wacoss** [comment]
A new way to see fly net wifi?

**Comment by R4IN2007** [comment]
A smokescreen similar to lolokokoTV
Warning users that are their links are in **[illegal retransmissions]** iptvs and being used for bad intentions. So no more netfly 😔

![Screenshot_20240426_164917_Chrome](https://github.com/iptv-org/iptv/assets/83226646/95c3b74f-ea38-4ef4-af49-a9d8e700bbd8)

**Comment by BellezaEmporium** [comment]
In some way, it forces them to protect their streams. Not a bad outcome in the end.

**Comment by R4IN2007** [comment]
Well, it time for me to find another way to Telemundo.

**Comment by wacoss** [comment]
> Well, it time for me to find another way to Telemundo.

Telemundo: https://content.uplynk.com/channel/b6a96ed39d694ae1b738faa98cf7dd3f.m3u8

**Comment by Karl1602** [comment]
anyone who can make a VPN to "EL Salvador", try it, it may be that instead of GEO_BLOCK they are sending the loop video.

**Comment by JesserGx** [comment]
hello guys, another way to see universal tv? cinecanal? tnt and hbo latino?
i cant find another server flynetwifi
