### ISSUE TITLE
Broken: MTV DE

### ISSUE THREAD

**Issue by morganland** [iptv-org/iptv#16429]
### Broken Link

https://0d26a00dfbb1.airspace-cdn.cbsivideo.com/mtvg18ef/master/master_5000.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
No need to remove. It's Geo-blocked for the region of Germany it doesn't works anywhere outside of Germany.
![Screenshot_20240426_211306_Chrome](https://github.com/iptv-org/iptv/assets/83226646/68892d7c-0086-4a5b-99a9-dc8a9d52c78b)
