### ISSUE TITLE
Add: Afrosport Nigeria 

### ISSUE THREAD

**Issue by Goldiefresh** [iptv-org/iptv#16422]
https://newproxy3.vidivu.tv/vidivu_afrosport/index.m3u8?token=0ad3f508a8d9dbab04e0a0134a21b57223da693f-af85cd7b0b94ef1673723afbe550fd87-1705256555-1705170155&remote=no_check_ip

Iv been using this stream since November and token has never changed.

**Comment by ProPontifex** [comment]
Created database entry to move this one along.
