### ISSUE TITLE
Add: Cartoon Network

### ISSUE THREAD

**Issue by Jerick120** [iptv-org/iptv#16421]
### Channel ID (required)

CartoonNetwork.in

### Channel Name

Cartoon Network

### Stream URL (required)

https://amg01448-samsungin-cartoonnw-samsungin-1y8kz.amagi.tv/playlist/amg01448-samsungin-cartoonnw-samsungin/playlist.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Broken stream, it's on repeat.

**Comment by Sphinxroot** [comment]
https://amg01448-samsungin-cartoonnw-samsungin-1y8kz.amagi.tv/playlist/amg01448-samsungin-cartoonnw-samsungin/playlist.m3u8

**Comment by BellezaEmporium** [comment]
Can confirm @Sphinxroot 's link work.

**Comment by Omar2014isa** [comment]
Sorry doesnt work from @Sphinxroot on my ipad

**Comment by adn4n99** [comment]
Doesnt work.

**Comment by hiremathandanayya99-dot** [comment]
Do not working
