### ISSUE TITLE
Add: CBeebies

### ISSUE THREAD

**Issue by codeautoplay** [iptv-org/iptv#16434]
### Channel ID (required)

CBeebies.uk

### Channel Name

CBeebies

### Stream URL (required)

https://news.codeautoplaycdn1.workers.dev/?codeby=nd&channel=cbeebies

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
BBC Four?

**Comment by Rguanchez** [comment]
CBeebies Sign off BBC Four Sign On
