### ISSUE TITLE
Add: BBC News

### ISSUE THREAD

**Issue by codeautoplay** [iptv-org/iptv#16430]
### Channel ID (required)

BBCNews.uk

### Channel Name

BBC News

### Stream URL (required)

https://news.codeautoplaycdn1.workers.dev/?codeby=nd&channel=bbc%20news

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by OrchidLuna** [comment]
There's also Akamai source that I use for a long time on my [live•page](https://lauraorchid.link): https://vs-hls-push-ww-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_news_channel_hd/mobile_wifi_main_sd_abr_v2.m3u8 😃

**Comment by Alstruit** [comment]
Xstreams server?

**Comment by Sphinxroot** [comment]
302 from https://signal2.livingabroad.tv/auth/+token

**Comment by Alstruit** [comment]
Better one exists. Closing.
