### ISSUE TITLE
Arabic/News 2 Channels stopped working

### ISSUE THREAD

**Issue by Vel-San** [iptv-org/iptv#1644]
**What's wrong?**

Channels not working/Stopped working recently (They were working about a week ago)

**Country of the channel:**

- Lebanon/Arabic Category/News

**Channel Name:**

- Al-Jadeed
- MTV Lebanon

**Broken Link:**

http://watch.teledunet.com:25461/live/tdn/23614613767/10146727.m3u8 ( Al Jadeed )

http://51.178.43.32:25461/live/tdn/44119572164/10146728.m3u8 ( MTV )

**Additional Information (optional):**

- LBCi (International) shows duplicated, also there is a normal LBC (non-international) that doesn't work either.

**Comment by darkspook1** [comment]
Al Jadeed is not working yet! would please try to find a working link!

**Comment by Vel-San** [comment]
@darkspook1 You can still find Al-Jadeed streams online. I watched it today, but the links in this repo aren't working anymore.
