### ISSUE TITLE
Add: BBC Parliament

### ISSUE THREAD

**Issue by codeautoplay** [iptv-org/iptv#16450]
### Channel ID (required)

BBCParliament.uk

### Channel Name

BBC Parliament

### Stream URL (required)

https://other.codeautoplaycdn1.workers.dev/?codeby=nd&channel=bbc%20parliament

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
filmon  redirect  ...

**Comment by BellezaEmporium** [comment]
Gets a 403 Forbidden just after 15 seconds of watchtime.
