### ISSUE TITLE
Broken: Antena 7 (Dominican Republic)

### ISSUE THREAD

**Issue by ELProductions** [iptv-org/iptv#16451]
### Broken Link

https://alba-do-antena7-antena7.stream.mediatiquestream.com/index.m3u8

### What happened to the stream?

Other

### Notes (optional)

The stream link stopped working and i need a new one.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
403 Cloudfront Error Geo-blocked
**Only Dominican Republic IP can view this**
Any IP that isn't from the Dominican Republic can't watch.
