### ISSUE TITLE
Broken: Zee Bihar Jharkhand

### ISSUE THREAD

**Issue by Alstruit** [iptv-org/iptv#16456]
### Broken Link

https://news.codeautoplay.workers.dev/?codeby=nd&channel=zeebiharjharkhand

### What happened to the stream?

Not loading

### Notes (optional)

Undo #16410

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by codeautoplay** [comment]
fixed. Working fine

**Comment by Sphinxroot** [comment]
Adaptative link have token

# https://zeenews.india.com/hindi/india/bihar-jharkhand/live-tv
#EXTINF:-1 tvg-id="",Zee Bihar Jharkhand (720p)
https://d3vmwjy7v49lo5.cloudfront.net/index_4.m3u8
#EXTINF:-1 tvg-id="",Zee Bihar Jharkhand (480p)
https://d3vmwjy7v49lo5.cloudfront.net/index_3.m3u8
#EXTINF:-1 tvg-id="",Zee Bihar Jharkhand (360p)
https://d3vmwjy7v49lo5.cloudfront.net/index_2.m3u8
#EXTINF:-1 tvg-id="",Zee Bihar Jharkhand (240p)
https://d3vmwjy7v49lo5.cloudfront.net/index_1.m3u8


every link from this site can be used as the exemple

all adaptative link will change over time

**Comment by Sphinxroot** [comment]
@Alstruit  @BellezaEmporium @Dum4G  what you think about all those 302 redirect  whit token

i like direct link tho    302 usefull  if proper coded

**Comment by Alstruit** [comment]
> Adaptative link have token
> 
> # https://zeenews.india.com/hindi/india/bihar-jharkhand/live-tv
> #EXTINF:-1 tvg-id="",Zee Bihar Jharkhand (720p) https://d3vmwjy7v49lo5.cloudfront.net/index_4.m3u8 #EXTINF:-1 tvg-id="",Zee Bihar Jharkhand (480p) https://d3vmwjy7v49lo5.cloudfront.net/index_3.m3u8 #EXTINF:-1 tvg-id="",Zee Bihar Jharkhand (360p) https://d3vmwjy7v49lo5.cloudfront.net/index_2.m3u8 #EXTINF:-1 tvg-id="",Zee Bihar Jharkhand (240p) https://d3vmwjy7v49lo5.cloudfront.net/index_1.m3u8
> 
> every link from this site can be used as the exemple
> 
> all adaptative link will change over time

Could create an adaptive m3u8 so long as the link doesn't change.

**Comment by codeautoplay** [comment]
the link is working fine (using token). why removed.
