### ISSUE TITLE
Edit: Rename OberlausitzTV.de and Move from Germany to Austria

### ISSUE THREAD

**Issue by TVGarden** [iptv-org/iptv#16458]
### Stream URL (required)

https://h056.video-stream-hosting.de/easycast8-live/_definst_/mp4:livestreamhd4/playlist.m3u8?ref=

### Channel ID

OberlausitzTV.de

### Channel Name

OberlausitzTV.de

### Quality

1080p

### Label

None

### Notes

I've noticed an issue with the current listing of **OberlausitzTV.de**. The stream is operational and functions correctly, however, the name and country assignment appear to be incorrect.

**Current Details:**

- ID: OberlausitzTV.de
- Name: Oberlausitz TV
- Country: Germany
- File: de.m3u

**Proposed Changes:**

- New ID: steiermark-tv.at
- New Name: Steiermark TV
- New Country: Austria
- Correct File: at.m3u

**Additional Details:**

Website: https://www.steiermark-tv.at/
Language: German

Appreciate your help with this!

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
That is a database issue. Have a look over at [iptv-org/database](https://github.com/iptv-org/database).
