### ISSUE TITLE
Broken: Cortinilla anti piratería FlyNet 

### ISSUE THREAD

**Issue by Avelarsin** [iptv-org/iptv#16452]
### Broken Link

http://168.227.22.18:1935/live/mobile-142/playlist.m3u8

### What happened to the stream?

Shows looped video

### Notes (optional)

Todas las transmisiones de FlyNet muestran una Cortinilla de advertencia sobre la pirateria
![Screenshot_20240426_162123](https://github.com/iptv-org/iptv/assets/168108009/4c5509cf-00ea-4245-8cb0-18003bae5864)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Entonces no más flynet 😔

**Comment by Karl1602** [comment]
anyone who can make a VPN to "EL Salvador", try it, it may be that instead of GEO_BLOCK they are sending the loop video.

**Comment by Avelarsin** [comment]
> quien pueda hacer una VPN a «EL Salvador», pruébalo, puede ser que en lugar de GEO_BLOCK estén enviando el video en bucle.

Probaré haber sí es eso

**Comment by Avelarsin** [comment]
> quien pueda hacer una VPN a «EL Salvador», pruébalo, puede ser que en lugar de GEO_BLOCK estén enviando el video en bucle.

Actualizando, no es geo bloqueo, ya intenté desde El Salvador y lo mismo
