### ISSUE TITLE
Broken: Repretel Canal 11 (Costa Rica)

### ISSUE THREAD

**Issue by ELProductions** [iptv-org/iptv#16460]
### Broken Link

https://alba-cr-repretel-c11.stream.mediatiquestream.com/index.m3u8

### What happened to the stream?

Constantly interrupts/lagging

### Notes (optional)

It is glitching and not working properly and needs a new stream link.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Can't be dealt with since it's the official stream you're talking about here.

**Comment by km147** [comment]
Its working fine for me
