### ISSUE TITLE
Add: KBS Kids

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#16464]
### Channel ID (required)

KBSKids.kr

### Channel Name

KBS Kids

### Stream URL (required)

http://mytv.dothome.co.kr/ch/catv/6.php

### Quality

480p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
https://kbsnkids.gscdn.kbs.co.kr/kbsnkids-02/kbsnkids-02_sd.m3u8?Expires=1714736608&Policy=+Token

**Comment by Alstruit** [comment]
Token issued expires in 2 days. Not bad.
