### ISSUE TITLE
Add: NBC East (WMAQ-DT1)

### ISSUE THREAD

**Issue by rushereeeeee** [iptv-org/iptv#16478]
### Channel ID (required)

WMAQDT1.us

### Channel Name

NBC East (WMAQ)

### Stream URL (required)

http://143.244.60.30/NBC_EAST/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by jpf48** [comment]
This stream is no longer working for me as of today. Anyone know why?

**Comment by Yodoma** [comment]
Any update with an updated link?
