### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by vishveshjain** [iptv-org/iptv#16473]
### Broken Link

https://d3dxf2v5wg5rcy.cloudfront.net/out/v1/349f643193e347609b16671d8e0bfb4a/index.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Addressed in #16470
