### ISSUE TITLE
Add: World

### ISSUE THREAD

**Issue by cysjunk** [iptv-org/iptv#16474]
### Channel ID (required)

WorldChannel.us

### Channel Name

World Channel

### Stream URL (required)

https://world.lls.pbs.org/index.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
???
https://iptv-org.github.io/channels/us/WorldChannel
https://iptv-org.github.io/channels/us/PBSWorld
