### ISSUE TITLE
Add: ABC East (WOLO-DT1)

### ISSUE THREAD

**Issue by rushereeeeee** [iptv-org/iptv#16479]
### Channel ID (required)

WOLODT1.us

### Channel Name

ABC East (WOLO)

### Stream URL (required)

http://143.244.60.30/ABC_EAST/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Spainguy77** [comment]
Can anyone help with finding a playlist of the US networks  - abc, cbs, nbc, fox - with adaptive streams? I'm confined mostly to mobile internet and don't have enough data to run the higher resolutions. Thanks
