### ISSUE TITLE
Broken: Nickelodeon Australia

### ISSUE THREAD

**Issue by mavijavi5124** [iptv-org/iptv#16471]
### Broken Link

http://c0.cdn.trinity-tv.net/stream/7tsewn83ddjifz69us9je7eftbm5nuausb4dsvz9g5aydin9672n734qbb9jgcfpiqtpwudvs9dpi2udjc3eh4h462eie5azjmfbfgfjeqfuhjmmgx9zuj736ijg7nffhf8rviq5svkgxbp639y9nfgc.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
![Screenshot_20240430_091455_Chrome](https://github.com/iptv-org/iptv/assets/83226646/f1e18969-dbe2-4f8d-bec2-cbd347590b6d)

**Comment by mavijavi5124** [comment]
showing this screen:
![sweet](https://github.com/iptv-org/iptv/assets/166801153/642966b6-5fe9-46ce-ba9d-9d649ee8d60a)

**Comment by R4IN2007** [comment]
Well, That's strange.

**Comment by voxel79** [comment]
here:
http://portal.magic8kip.tv:80/play/live.php?mac=00:1A:79:c6:20:7d&stream=752176&extension=ts&play_token=pBZyGpJHCb
