### ISSUE TITLE
Broken: LA Channels

### ISSUE THREAD

**Issue by JesserGx** [iptv-org/iptv#16475]
### Broken Link

http://stream.flynetwifi.com:1935/live/mobile-064/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

hello guys, list of channels not working: 
http://stream.flynetwifi.com:1935/live/mobile-064/playlist.m3u8
http://stream.flynetwifi.com:1935/live/mobile-026/playlist.m3u8
http://stream.flynetwifi.com:1935/live/mobile-123/playlist.m3u8
http://stream.flynetwifi.com:1935/live/mobile-123/playlist.m3u8
http://stream.flynetwifi.com:1935/live/mobile-123/playlist.m3u8
http://stream.flynetwifi.com:1935/live/mobile-141/playlist.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by rushereeeeee** [comment]
goodbye netfly 😔
![Uploading IMG_4458.jpeg…]()

**Comment by R4IN2007** [comment]
Didn't they already remove "sv_flynet.m3u" this channels don't appear anymore.
https://github.com/iptv-org/iptv/issues/16420
https://github.com/iptv-org/iptv/issues/16452

**Comment by rushereeeeee** [comment]
yea tbh

**Comment by BellezaEmporium** [comment]
Already removed due to issue #16420, PR in #16453
