### ISSUE TITLE
Add: Fox News Channel

### ISSUE THREAD

**Issue by codeautoplay** [iptv-org/iptv#16481]
### Channel ID (required)

FoxNewsChannel.us

### Channel Name

Fox News Channel

### Stream URL (required)

https://news.codeautoplaycdn1.workers.dev/?codeby=nd&channel=foxnewschannel

### Quality

None

### Label

None

### HTTP Referrer

https://www.livenewsmag.com/

### Notes

Use referrer (  #EXTVLCOPT:http-referrer=https://www.livenewsmag.com/  )

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Toei79** [comment]
no works for me.

**Comment by Alstruit** [comment]
403 Error

**Comment by Alstruit** [comment]
Hmm screen looks zoomed in after using referrer

**Comment by Sphinxroot** [comment]
https://1028107998.rsc.cdn77.org/pHIBfOvMk4nCBKauMp-I9A==,1715217515/ls-54548-2/index.m3u8

**Comment by Toei79** [comment]
no working either, looks like they do something. blocked or something
