### ISSUE TITLE
Add: Fox Business Network

### ISSUE THREAD

**Issue by codeautoplay** [iptv-org/iptv#16483]
### Channel ID (required)

FoxBusinessNetwork.us

### Channel Name

Fox Business Network

### Stream URL (required)

https://news.codeautoplaycdn1.workers.dev/?codeby=nd&channel=foxbusiness

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
https://1329918864.rsc.cdn77.org/fu9qXHBGnZ7yQiISUfVWsw==,1715212037/ls-54548-1/index.m3u8
