### ISSUE TITLE
Broken: Sony BBC Earth HD (1080p)

### ISSUE THREAD

**Issue by githubuser45566** [iptv-org/iptv#16486]
### Broken Link

http://103.81.104.118/hls/stream5.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

VLC is unable to open the MRL 'http://103.81.104.118/hls/stream5.m3u8'.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by queazified** [comment]
can verify that the link has died, the ip probably changed at some point
