### ISSUE TITLE
Add: FOX East (WFXT-DT1)

### ISSUE THREAD

**Issue by rushereeeeee** [iptv-org/iptv#16480]
### Channel ID (required)

WFXTDT1.us

### Channel Name

FOX East (WFXT)

### Stream URL (required)

http://143.244.60.30/FOX_EAST/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
At least the rest hasn't been found only being a small list 🙃
![Screenshot_20240501_211853_QuickEdit](https://github.com/iptv-org/iptv/assets/83226646/c36b99b8-43b3-4542-ac13-aa2e8b688197)

**Comment by voxel79** [comment]
> At least the rest hasn't been found only being a small list 🙃 ![Screenshot_20240501_211853_QuickEdit](https://private-user-images.githubusercontent.com/83226646/327294316-c36b99b8-43b3-4542-ac13-aa2e8b688197.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxODY0NDksIm5iZiI6MTcxNTE4NjE0OSwicGF0aCI6Ii84MzIyNjY0Ni8zMjcyOTQzMTYtYzM2Yjk5YjgtNDNiMy00NTQyLWFjMTMtYWEyZThiNjg4MTk3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE2MzU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NDE2OGE4ZmUzOTVjMWFkMDIwMDlkMDZkMzUzY2NkOTRkOTJiYmRlY2Q4MmM2NDJjZGY0YTI2ZTE0MmVkZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cAGXzrZYCQJt642qYz1VHOXu1ZfscU4_67BmkX1ehTU)

I crave this PLEASE email me

**Comment by voxel79** [comment]
hold on I think this is a leak? not sure
http://143.244.60.30/NICKTOONS/index.m3u8

**Comment by voxel79** [comment]
LOL I HIT A GOLD MINE THANK YOU
