### ISSUE TITLE
Broken: Sony Ten sports 2 

### ISSUE THREAD

**Issue by dcostayuron13** [iptv-org/iptv#16496]
### Broken Link

https://dai.google.com/linear/hls/event/LK-ik89MQIi_pWBbg74KNQ/master.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
403 error. Maybe geo-blocked?
