### ISSUE TITLE
Add: ERT Music

### ISSUE THREAD

**Issue by idfan92** [iptv-org/iptv#16506]
### Channel ID (required)

ERTMusic.gr

### Channel Name

ERT Music

### Stream URL (required)

https://ertflix.s.llnwi.net/ertlive/music/default/index.mpd

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
https://github.com/iptv-org/iptv/issues/16526#issuecomment-2103584716

**Comment by Dum4G** [comment]
@trancer1994 please help us check if this source works in Greece using VLC

**Comment by trancer1994** [comment]
What source?
________________________________

**Comment by Dum4G** [comment]
@trancer1994 https://ertflix.s.llnwi.net/ertlive/music/default/index.mpd

**Comment by freearhey** [comment]
https://ertflix.s.llnwi.net/ertlive/music/default/index.mpd (offline)

<img width="415" alt="image" src="https://github.com/user-attachments/assets/8b71f4de-38f8-44a9-a9ca-ffee008acf8e">
