### ISSUE TITLE
Add: AngienetTV (Peru)

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#16507]
### Channel ID (required)

AngienetTV.pe

### Stream URL (required)

https://servilive.com:3354/stream/play.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
404, Not 24/7?

**Comment by ProPontifex** [comment]
Link dead
