### ISSUE TITLE
Add: ERT Eurovision Channel

### ISSUE THREAD

**Issue by idfan92** [iptv-org/iptv#16504]
### Channel ID (required)

ERTEurovisionChannel.gr

### Channel Name

ERT Eurovision Channel

### Stream URL (required)

https://ertflix.s.llnwi.net/ertlive/eurovision/default/index.mpd

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
https://github.com/iptv-org/iptv/issues/16526#issuecomment-2103584716

**Comment by km147** [comment]
Doesn't work for me with and without VPN
