### ISSUE TITLE
Add: ERT Kids

### ISSUE THREAD

**Issue by idfan92** [iptv-org/iptv#16505]
### Channel ID (required)

ERTKids.gr

### Channel Name

ERT Kids

### Stream URL (required)

https://ertflix.s.llnwi.net/ertlive/kids/default/index.mpd

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
https://github.com/iptv-org/iptv/issues/16526#issuecomment-2103584716

**Comment by freearhey** [comment]
https://ertflix.s.llnwi.net/ertlive/kids/default/index.mpd (offline)

<img width="395" alt="image" src="https://github.com/user-attachments/assets/6cb3a786-b67f-4b72-9755-e31ace4c8f36">
