### ISSUE TITLE
Broken: Karibena

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#16515]
### Broken Link

https://iptv-c9-x-m-mck9-video.cusac.online:50050/karibena/index.fmp4.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
The link is nowhere.
