### ISSUE TITLE
Israel Channels Broken

### ISSUE THREAD

**Issue by arrafz** [iptv-org/iptv#1652]
**What's wrong?**
url can't be opened
**Country of the channel:**
Israel
**Channel Name:**
Reshet 13 רשת
**Broken Link:**

https://reshet-live-il.ctedgecdn.net/13tv-desktop/r13.m3u8
**Additional Information (optional):**

**Comment by freearhey** [comment]
Thank you for noticing! I removed a broken link from the playlist.
