### ISSUE TITLE
Add: TV5Monde Europe (new stream)

### ISSUE THREAD

**Issue by idfan92** [iptv-org/iptv#16525]
### Channel ID (required)

TV5MondeEurope.fr

### Channel Name

TV5Monde Europe

### Stream URL (required)

https://ertflix.s.llnwi.net/ertlive/tv5/default/index.mpd

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
https://github.com/iptv-org/iptv/issues/16526#issuecomment-2103584716

**Comment by freearhey** [comment]
https://ertflix.s.llnwi.net/ertlive/tv5/default/index.mpd (offline)

<img width="385" alt="image" src="https://github.com/user-attachments/assets/da0aada7-ceeb-4448-a0a5-90ca2b128f5b">
