### ISSUE TITLE
Add: RIK Sat (new stream)

### ISSUE THREAD

**Issue by idfan92** [iptv-org/iptv#16527]
### Channel ID (required)

RIKSat.cy

### Channel Name

RIK Sat

### Stream URL (required)

https://ertflix.s.llnwi.net/ertlive/rik/default/index.mpd

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
https://github.com/iptv-org/iptv/issues/16526#issuecomment-2103584716

**Comment by km147** [comment]
doesn't work for me with greece vpn

**Comment by freearhey** [comment]
https://ertflix.s.llnwi.net/ertlive/rik/default/index.mpd (offline)

<img width="388" alt="image" src="https://github.com/user-attachments/assets/d914dfa4-5db7-4c12-ac18-c00479c488c5">
