### ISSUE TITLE
Add: DW English (new stream)

### ISSUE THREAD

**Issue by idfan92** [iptv-org/iptv#16526]
### Channel ID (required)

DWEnglish.de

### Channel Name

DW English

### Stream URL (required)

https://ertflix.s.llnwi.net/ertlive/dw/default/index.mpd

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by CasperMcFadden95** [comment]
Thanks for your contribution but the stream doesn't work for me.

**Comment by Sphinxroot** [comment]
https://www.insomnia.gr/forums/topic/827106-ertflix-links/

**Comment by vishveshjain** [comment]
Try following stream link:
https://ythls.armelin.one/channel/UCknLrEdhRCp1aegoMqRaCZg.m3u8

**Comment by freearhey** [comment]
https://ertflix.s.llnwi.net/ertlive/dw/default/index.mpd (offline)

<img width="387" alt="image" src="https://github.com/user-attachments/assets/5fbb8719-908b-43e3-aa64-90418427f5ba">
