### ISSUE TITLE
Israel 12 

### ISSUE THREAD

**Issue by arrafz** [iptv-org/iptv#1653]
**Country of the channel:**

Israel

**Channel Name:**

Keshet 12
**Channel Language:**
Hebrew

**Additional Information (optional):**

**Comment by bertperrisor** [comment]
@arrafz This channel has a stream that expires every 1 day. (https://keshethlslive-i.akamaihd.net/hls/live/512033/CH2LIVE_HIGH/index.m3u8?as=1&hdnea=st%3D1598857923%7Eexp%3D1598858823%7Eacl%3D%2F*%7Ehmac%3D2076b88c426f5de39778bcd6ad7eaab6f6064bbc88a64badd4d52d73595aaca5)

I can host a redirection from my proxy which can guarantee the streams availability 24/7.

**Comment by freearhey** [comment]
Closed in favor #1969
