### ISSUE TITLE
Add: USM TV

### ISSUE THREAD

**Issue by OrchidLuna** [iptv-org/iptv#16537]
### Channel ID (required)

USMTV.id

### Stream URL (required)

https://63b2dc7196c38.streamlock.net:1937/usmtv/myStream/playlist.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ProPontifex** [comment]
Link dead (geo-blocked)?

**Comment by OrchidLuna** [comment]
Possibly, thanks for checking tho
