### ISSUE TITLE
Add: Telenorba 

### ISSUE THREAD

**Issue by Lilolabja** [iptv-org/iptv#16547]
### Channel ID (required)

Telenorba.it

### Channel Name

Telenorba

### Stream URL (required)

http://stream2.xdevel.com/video2s976570-2303/stream/playlist_dvr.m3u8

### Quality

1080p

### Label

None

### Notes

This is an Italian Local Broadcaster. 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Lilolabja** [comment]
No this is a different channel of the Norba group.

**Comment by ProPontifex** [comment]
I just submitted a database entry to move this one along.
