### ISSUE TITLE
Add: TV 8,5

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#16556]
### Channel ID (required)

TV85.tr

### Channel Name

TV 8.5

### Stream URL (required)

http://bozztv.com/gin-dvrfl05/gin-tv8_5/index.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Benedek012** [comment]
Please help,Meltem TV,BRT 3,TvDen,TV1 Kayseri, Thank you,please answer.

**Comment by R4IN2007** [comment]
> Please help,Meltem TV,BRT 3,TvDen,TV1 Kayseri, Thank you,please answer.

@Benedek012 Signal for Meltem TV is down
https://www.meltemtv.com.tr/canli-yayin

BRT3? or Kibris BRT3 - http://bozztv.com/gin-36bay3/gt-kibrisbrt3/index.m3u8 <- BRT2 HD 
www.elahmad.com/tv/gin.php?id=kibrisbrt3

tvDEN? - http://canli.tvden.com.tr/hls/live.m3u8

TV1 Kayseri* Can't be found

**Comment by ProPontifex** [comment]
I _just_ took care TV 8.5; there seems to be, however, at least 3(?) other requests in this submission. I'll attempt to work through them piece by piece.

**Comment by ProPontifex** [comment]
BRT 2 submitted

**Comment by ProPontifex** [comment]
The last two streams (BRT3 and tvDEN) are broken

**Comment by Alstruit** [comment]
Hmm. Appears to be already added.
