### ISSUE TITLE
Add: AlanyaPostaTV

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#16553]
### Channel ID (required)

AlanyaPostaTV.tr

### Channel Name

Alanya Posta TV

### Stream URL (required)

https://api-tv3.yayin.com.tr/postatv/postatv/playlist.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ProPontifex** [comment]
Submitted under IPTV
