### ISSUE TITLE
Add: TV8 International

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#16560]
### Channel ID (required)

TV8International.tr

### Channel Name

TV8 Int

### Stream URL (required)

http://bozztv.com/gin-dvrfl05/gin-tv8int/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ProPontifex** [comment]
Request submitted
