### ISSUE TITLE
Broken: TVR Info

### ISSUE THREAD

**Issue by AlbertROTV** [iptv-org/iptv#16568]
### Broken Link

https://mn-nl.mncdn.com/tvrinfo/tvrinfo_mjuypp/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

https://tvr-tvrinfo.cdn.zitec.com/live/tvrinfo/main.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by queazified** [comment]
geoblocked
