### ISSUE TITLE
Broken: (Germany) Das Erste: no sound?

### ISSUE THREAD

**Issue by Baumhausbanane123e** [iptv-org/iptv#16564]
### Broken Link

https://derste247liveint.akamaized.net/hls/live/662735/daserste_int/master.m3u8

### What happened to the stream?

No sound

### Notes (optional)

Hello,
I wanted to use the iptv Links in my iptv setup and came across an isue:
I downloaded all from germany, but when playing "Das Erste", I get no sound?
I tried on my Jellyfin Server, aswell as locally with VLC. Is that just me?

Thanks in advance!

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
The sound is working fine now
