### ISSUE TITLE
Broken: TVR Cultural

### ISSUE THREAD

**Issue by AlbertROTV** [iptv-org/iptv#16569]
### Broken Link

https://mn-nl.mncdn.com/tvr_cultural/tvrcultural/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

https://tvr-tvrcultural.cdn.zitec.com/live/tvrcultural/main.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by queazified** [comment]
geoblocked
