### ISSUE TITLE
Add: BioskopIndonesia.id

### ISSUE THREAD

**Issue by singkie** [iptv-org/iptv#16562]
### Channel ID (required)

BioskopIndonesia.id

### Stream URL (required)

https://cdn01-telkomsel-01.akamaized.net/Content/HLS/Live/channel(41d51f9f-8855-e625-012f-304a1f0eb538)/index.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
probably geo-blocked
