### ISSUE TITLE
Add: TVR Sport (new link)

### ISSUE THREAD

**Issue by AlbertROTV** [iptv-org/iptv#16570]
### Channel ID (required)

TVRSport.ro

### Channel Name

TVR Sport

### Stream URL (required)

https://tvr-tvrsport.cdn.zitec.com/live/tvrsport/main.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by queazified** [comment]
geoblocked to romania, but can confirm the link is working.
![image](https://github.com/iptv-org/iptv/assets/122835476/ea7ffa73-de8b-4bad-84a9-1ad3b9af42b5)

**Comment by azgaresncf** [comment]
thanks for this info :D
