### ISSUE TITLE
Broken: jp_primehome.m3u at 4:55 AM (JST)

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#16582]
### Broken Link

https://github.com/iptv-org/iptv/blob/master/streams/jp_primehome.m3u

### What happened to the stream?

Stuck at a single frame

### Notes (optional)

@BellezaEmporium Hey, mods! I found out the fact that many Japanese livestream links at PRIMEHOME that got stuck at a single frame which is used very often but it's starts at 4:55 AM (JST) most likely due to the technical glitches and among other issues causes the footage for the last five minutes or so went missing especially the Japanese feeds of both Cartoon Network and Disney Channel because of this.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
I see no issues whatsoever...
