### ISSUE TITLE
Broken:  ET NOW

### ISSUE THREAD

**Issue by Arjun-S05** [iptv-org/iptv#16583]
### Broken Link

https://pubads.g.doubleclick.net/ssai/event/pJrzNyDoT_K_GwYQsijTsQ/master.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Tried it from Indian IP.
The other link: https://etnowweblive.akamaized.net/hls/live/2034678/ETNOWMSL4/chunklist_2.m3u8 is also not working

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
https://damso2e2yhynu.cloudfront.net/master.m3u8 try this with an Indian IP.

**Comment by BellezaEmporium** [comment]
https://dai.google.com/ssai/event/ZBBu7nCkQE2fNkDxXdWwIA/master.m3u8 too.

**Comment by BellezaEmporium** [comment]
![snapshot](https://github.com/iptv-org/iptv/assets/30985701/0c871525-978b-49b5-84c6-b305e15871fe)

Tested with an IP pointing in Mumbai, India.

**Comment by Arjun-S05** [comment]
Both are working fine.

Thank you :)
