### ISSUE TITLE
Edit: Alsumaria

### ISSUE THREAD

**Issue by sabah1973** [iptv-org/iptv#16588]
### Channel ID (required)

Alsumaria.iq

### NSFW

None

### Notes

https://live.kwikmotion.com/alsumariatvlive/sumariamob.smil/sumariapublish/live_source/hdntl=exp=1716063883~acl=%2falsumariatvlive%2fsumariamob.smil%2f*~data=hdntl~hmac=185b390a403daf9c0386fdeff7b5d40adee1ff8e01deb323ecc990f3bdc67b86/chunks.m3u8

**Comment by ProPontifex** [comment]
Link no longer works
