### ISSUE TITLE
Broken: Kairali News 

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#16587]
### Broken Link

https://ythls.armelin.one/channel/UCkCWitaToNG1_lR-Si1oMrg.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Please find the youtube live link of the same channel below.

https://www.youtube.com/live/wq0ecjkN3G8?si=Asu8Wef3gtgG9zZ5

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
https://ythls.armelin.one/channel/UCnEvxaWfVL91XIYuyQRO5QA.m3u8
