### ISSUE TITLE
Add: Sky Weather

### ISSUE THREAD

**Issue by queazified** [iptv-org/iptv#16581]
### Channel ID (required)

SkyWeather.uk

### Channel Name

Sky Weather

### Stream URL (required)

http://late-bird-1612.livetube.eu.org/SkyWeather/index.m3u8?token=9TEQXsK2lKdyI3

### Quality

1080p

### Label

None

### Notes

I am hosting this myself, and I will keep this channel enabled as long as I can.
![image](https://github.com/iptv-org/iptv/assets/122835476/6c8b44a3-1122-4a0b-9ace-386beedfd4c5)

### Contributing Guide

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
If it's yours, then it's not available for streaming.

403 Unauthorized - Streamer protection system doesn't allow you to watch this content.

**Comment by cold360** [comment]
yeah still not working

**Comment by ProPontifex** [comment]
I submitted a request #12244 for this channel to be added to the database; hopefully, this will push this one along.
