### ISSUE TITLE
Broken: CR some channel broken

### ISSUE THREAD

**Issue by miguelcr1982** [iptv-org/iptv#16597]
### Broken Link

https://iptv-org.github.io/iptv/countries/cr.m3u

### What happened to the stream?

Not loading

### Notes (optional)

Please update

Canal 2 
https://alba-cr-repretel-c2.stream.mediatiquestream.com/tracks-v1a1/mono.m3u8

Canal 4 720
https://alba-cr-repretel-c4.stream.mediatiquestream.com/720p.m3u8

Canal 6 720
https://alba-cr-repretel-c6.stream.mediatiquestream.com/720p.m3u8

Canal 11 720
https://alba-cr-repretel-c11.stream.mediatiquestream.com/720p.m3u8

 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Canal 2
https://alba-cr-repretel-c2.stream.mediatiquestream.com/index.m3u8

Canal 4
https://alba-cr-repretel-c4.stream.mediatiquestream.com/index.m3u8

Canal 6 
https://alba-cr-repretel-c6.stream.mediatiquestream.com/index.m3u8

Canal 11
https://alba-cr-repretel-c11.stream.mediatiquestream.com/index.m3u8

**Comment by Dum4G** [comment]
@miguelcr1982 @BellezaEmporium please confirm if those links geo-blocked or dead at this point. Access Denied under multiple VPNs

**Comment by miguelcr1982** [comment]
Indeed, the links only work in Costa Rica. I tested with VPNs in Mexico, the USA, and Spain, and all were blocked.

**Comment by Dum4G** [comment]
May you show a screenshot of them working for you in VLC as of now?

**Comment by miguelcr1982** [comment]
Sure!

Canal 2
https://alba-cr-repretel-c2.stream.mediatiquestream.com/index.m3u8
![image](https://github.com/iptv-org/iptv/assets/55470883/02145e62-f18c-4213-be34-22c0ae24aad1)

Canal 4
https://alba-cr-repretel-c4.stream.mediatiquestream.com/index.m3u8
![image](https://github.com/iptv-org/iptv/assets/55470883/b0565e17-ddd2-4426-b3cf-c3fe4d5b1fc7)

Canal 6
https://alba-cr-repretel-c6.stream.mediatiquestream.com/index.m3u8
![image](https://github.com/iptv-org/iptv/assets/55470883/d6a53d6e-ba98-43a3-abb7-a5552ec7df1d)

Canal 11
https://alba-cr-repretel-c11.stream.mediatiquestream.com/index.m3u8
![image](https://github.com/iptv-org/iptv/assets/55470883/29eca877-49aa-4dbf-a2df-c0b8cfeb2246)
