### ISSUE TITLE
Broken: Zee News Malayalam

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#16592]
### Broken Link

https://d1vd9xhq6jlm48.cloudfront.net/out/v1/71fcc57c8fe74c5b938451bc2435a93e/index_4.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Url of the live feed is attached below.

https://zeenews.india.com/malayalam/live-tv

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
https://03nwj0csy5.execute-api.ap-south-1.amazonaws.com/prod/cf-token?cb=514646

Result to be attached in this : https://d1ty2af03alkwd.cloudfront.net/index.m3u8

**Comment by codeautoplay** [comment]
https://news.codeautoplay.workers.dev/?codeby=nd&channel=zeemalayalam
