### ISSUE TITLE
Add: Flowers Tv USA

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#16605]
### Channel ID (required)

flowerstv.us

### Channel Name

Flowers TV USA

### Stream URL (required)

https://mhdmaxtv.com/live/flowers-tv-usa/

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
https://yuppmedtaorire.akamaized.net/v1/master/a0d007312bfd99c47f76b77ae26b1ccdaae76cb1/flowers_nim_https/050522/flowers/playlist.m3u8
