### ISSUE TITLE
Broken:  CN Japan

### ISSUE THREAD

**Issue by mavijavi5124** [iptv-org/iptv#16609]
### Broken Link

http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=cs25

### What happened to the stream?

Stuck at a single frame

### Notes (optional)

CN Constantly buffering as well

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Works for me.

**Comment by mavijavi5124** [comment]
> Works for me.
works for me now as well it was laggy like a few hours ago
