### ISSUE TITLE
Add:  Vismaya News

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#16604]
### Channel ID (required)

Vismayanews.in

### Channel Name

Vismaya News

### Stream URL (required)

https://www.youtube.com/watch?v=VLPSPs-VsW8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
https://ythls.armelin.one/channel/UCoOQDJS5K6v3g__qPcullxg.m3u8
