### ISSUE TITLE
Broken: C5N

### ISSUE THREAD

**Issue by xzonix** [iptv-org/iptv#16607]
### Broken Link

https://ythls.armelin.one/channel/UCFgk2Q2mVO1BklRQhSv6p0w.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

I have a link for this channel:
https://anym3u8player.com/youtube.php/id/664b91b904658.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Both links work for me ? I don't know where's the issue.
