### ISSUE TITLE
Broken: +MasMediaTV.es Spain Channels ^Needs refixing

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#16608]
### Broken Link

https://iptv-org.github.io/iptv/countries/es.m3u

### What happened to the stream?

Not loading

### Notes (optional)

All channels under https://spa-ha-p004.cdn. from MasMediaTV are down and need to be fix and also the the number in the link can be changed for it to work again range 1 to 5 (p001,p002,p003,p004,p005) and also I found a large list from MasMediaTV using p005
https://pastebin.ai/raw/9barffpovi

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
later

**Comment by Dum4G** [comment]
@R4IN2007 please check if it works for you now

**Comment by R4IN2007** [comment]
Some channels work...

Real Madrid ES
![Screenshot_20240703_105655_Chrome](https://github.com/iptv-org/iptv/assets/83226646/d81ad755-2489-4a8e-948c-bf7ff3be2e51)

AMC Dark
![Screenshot_20240703_110024_Chrome](https://github.com/iptv-org/iptv/assets/83226646/dfca8de0-f88d-492d-bdb0-29b784056f1a)

Calle 13 Universal
![Screenshot_20240703_110117_Chrome](https://github.com/iptv-org/iptv/assets/83226646/00b684f1-3f18-4cb9-a389-d46554cc8ed6)

**Comment by R4IN2007** [comment]
Yeah

**Comment by R4IN2007** [comment]
![Screenshot_20240703_110438_Chrome](https://github.com/iptv-org/iptv/assets/83226646/b96733af-8c68-465f-b381-9c73985a44a6)
![Screenshot_20240703_110556_Chrome](https://github.com/iptv-org/iptv/assets/83226646/8a15f191-743c-417b-b82a-d8d6a1a4c867)
![Screenshot_20240703_110916_Chrome](https://github.com/iptv-org/iptv/assets/83226646/87b09d81-4608-4932-b92f-8bc0c2334b0e)
![Screenshot_20240703_111337_Chrome](https://github.com/iptv-org/iptv/assets/83226646/dd939557-ffca-4e4d-af8e-eb6c831be0bf)
![Screenshot_20240703_111534_Chrome](https://github.com/iptv-org/iptv/assets/83226646/c49aea20-f7bc-4da2-875a-fd0006b9555b)
![Screenshot_20240703_111647_Chrome](https://github.com/iptv-org/iptv/assets/83226646/8137adc1-4ce5-412a-85dd-838bd237aee0)

**Comment by R4IN2007** [comment]
![Screenshot_20240703_111902_VLC](https://github.com/iptv-org/iptv/assets/83226646/2f584c8b-38e8-49b4-8f2b-5a1c74317b01)
No video & audio delays

**Comment by starhip48** [comment]
> https://pastebin.ai/raw/9barffpovi

does anyone have t3l3c1nc0 m3u8?

**Comment by MusicaFM** [comment]
Le han puesto token a los m3u8 y mpd de +Media

**Comment by R4IN2007** [comment]
Muchos cambian de url no tienen mpd drm
