### ISSUE TITLE
Lebanon Channels

### ISSUE THREAD

**Issue by darkspook1** [iptv-org/iptv#1660]
please add the following channels because the current links aren't working anymore...

#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Arabic" tvg-logo="https://i.imgur.com/YPR45yP.png" group-title="General",LBC International
http://51.15.3.161:8080/LDC/index.m3u8?token=test&checkedby:iptvcat.com

#EXTINF:-1 tvg-id="LBC ARB" tvg-name="LBC ARB" tvg-language="Arabic" tvg-logo="https://rotana.net/assets/themes/TriTheme/images/channels/lbc.png" group-title="General",LBC
http://178.132.3.162:88/LBC_SAT/video.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Arabic" tvg-logo="https://i.imgur.com/6R1jFJO.jpg" group-title="General",MTV
http://178.132.3.162:88/MTV_Lebanon/video.m3u8?token=test&checkedby:iptvcat.com

**Comment by Vel-San** [comment]
#1644
