### ISSUE TITLE
Add: Darshana TV

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#16611]
### Channel ID (required)

darshanatv.in

### Channel Name

Darshana TV

### Stream URL (required)

https://mhdmaxtv.com/live/darshana-tv/

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
https://mhdmaxtv.me/yupp/tv.php?c=darshanatv
w/ referer : https://mhdmaxtv.me/yupp/play.php?watch=darshanatv

**Comment by Manipulativemachan** [comment]
Not able to find m3u links fo the same

**Comment by R4IN2007** [comment]
https://livegeoroueu.akamaized.net/290723/smil:darshanatv1.smil/playlist.m3u8?hdnts=st=1716416636~exp=1716420236~acl=!*/290723/smil:darshanatv1.smil/*!yuppTVCom_61_-1_c4fa6dbada104e94_US_166.194.158.45/payload/yuppTVCom_61_-1_c4fa6dbada104e94_US_166.194.158.45/*~hmac=2586df49a8b1b4f96cc9693f87c9168e4d455ae2d6ab7d4d655aa5f7e65fd178&amp;ads.app_bundle=&amp;ads.app_store_url=&amp;ads.content_livestream=1&amp;ads.language=MAL&amp;ads.content_genre=ENT&amp;ads.channel=3354&amp;ads.channel_name=DarshanaTV&amp;ads.network_name=yupptv&amp;ads.user=0

Tokenized I guess?

**Comment by BellezaEmporium** [comment]
Yup.

**Comment by BellezaEmporium** [comment]
![image](https://github.com/iptv-org/iptv/assets/30985701/ec0dd68a-7bff-4fab-8858-7ae66ef3272e)

**Comment by ProPontifex** [comment]
So....closed?
