### ISSUE TITLE
Broken: TlnovelasMexico.mx

### ISSUE THREAD

**Issue by xemles** [iptv-org/iptv#16617]
### Broken Link

https://linear-421.frequency.stream/mt/studio/421/hls/master/playlist.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
let me know if its the same https://www.twitch.tv/tn_4400

**Comment by R4IN2007** [comment]
Stream got dmca'd by twitch. It's gone

**Comment by R4IN2007** [comment]
Some streams actually still live longer and some don't. Maybe because it was shared here especially knowing that twitch removed dmca content under 24-hrs and how this repo has multiple dmca complaints no wonder it went down.
