### ISSUE TITLE
Add new stream link previous is broken

### ISSUE THREAD

**Issue by AreArjane** [iptv-org/iptv#16612]
### Channel ID (required)

MedMuzik.tr

### Channel Name

 Med Muzik

### Stream URL (required)

https://med-musik.icdndhcp.com/live3/live3.m3u8

### Quality

None

### Label

None

### Notes

Line 252 of tr

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by mamosa14** [comment]
https://med-musik.icdndhcp.com/live3/live3.m3u8

**Comment by AreArjane** [comment]
This link working but there is broken one on channel

**Comment by ProPontifex** [comment]
Just submitted working link

**Comment by Alstruit** [comment]
Closing in favor #16752
