### ISSUE TITLE
Add:Drishya TV 

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#16610]
### Channel ID (required)

Drishyatv.in

### Channel Name

Drishya TV

### Stream URL (required)

https://play.google.com/store/apps/details?id=com.drishyatvm.skystream&hl=en_US

### Quality

None

### Label

None

### Notes

Only able to find the Play Store link of the channel. Can someone find the streaming link for the same?

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ProPontifex** [comment]
Link no longer works
