### ISSUE TITLE
Broken link should be changed 

### ISSUE THREAD

**Issue by AreArjane** [iptv-org/iptv#16628]
### Broken Link

http://137.74.205.201/medmuzik/MedStream/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Line 252 on tr.m3

MedMuzik.tr

this should be added instead: 

https://med-musik.icdndhcp.com/live3/live3.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
It has already been added (line 500).
```
#EXTINF:-1 tvg-id="MedMuzik.tr",Med Muzik (720p)
https://med-musik.icdndhcp.com/live3/live3.m3u8
```
