### ISSUE TITLE
Broken: PBS Kids Hawaii

### ISSUE THREAD

**Issue by mavijavi5124** [iptv-org/iptv#16621]
### Broken Link

https://livestream.pbskids.org/out/v1/19d1d62bf61b4aea9ec20f83b6450a4e/hast.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by InsolenceWillow** [comment]
I found a working one, maybe this'll replace the stream! https://khetdt.lls.pbs.org/out/v1/7ec7903413294b72bb64f83963d8ea9b/index.m3u8
