### ISSUE TITLE
Broken: Bukedde TV2

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#16623]
### Broken Link

https://stream.hydeinnovations.com/bukedde2flussonic/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

![屏幕截图 2024-05-25 205515](https://github.com/iptv-org/iptv/assets/142400045/57b1c41b-8f52-4ac6-abcf-b1e551f272de)
I checked streams under https://stream.hydeinnovations.com but the stream link for them might work or might not 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
![Screenshot_20240525_145414_VLC](https://github.com/iptv-org/iptv/assets/83226646/667e73e4-77a8-4166-ab5f-c1c9f76b190c)
It's fine in VLC
