### ISSUE TITLE
Add: UBC TV

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#16620]
### Channel ID (required)

UBCTV.ug

### Stream URL (required)

http://197.239.30.29/readymedia/stream/ubc/20-hls/live-media.m3u8

### Quality

621p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Host is streams.readymedia.moderntv.cloud
