### ISSUE TITLE
Only 1st stream in m3u

### ISSUE THREAD

**Issue by Weegley** [iptv-org/iptv#16629]
### Describe your issue

Channel have 4 streams, but only 1, different in each place, gets into m3u8
Example: 
https://iptv-org.github.io/?q=sts.ru - first in list gets into m3u
https://iptv-org.github.io/iptv/countries/ru.m3u - same channel, but other stream. also only 1.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
That is chosen by the highest quality of the stream and is not a bug. If there is a broken stream, report it in a new issue.
