### ISSUE TITLE
Add: Disney Junior PL

### ISSUE THREAD

**Issue by mavijavi5124** [iptv-org/iptv#16622]
### Channel ID (required)

DisneyJunior.pl

### Channel Name

Disney Junior Poland

### Stream URL (required)

https://cdn-notpub-london.lolokoko.tv/disneyjunior.stream/chunks.m3u8

### Quality

576p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by GuyInCanada** [comment]
all the lolokoko links are dead, again.

**Comment by mavijavi5124** [comment]
> all the lolokoko links are dead, again.

Still works for me
