### ISSUE TITLE
Add: APN

### ISSUE THREAD

**Issue by codeautoplay** [iptv-org/iptv#16634]
### Channel ID (required)

APN.in

### Channel Name

APN

### Stream URL (required)

https://cdn.smartstream.video/smartstream-us/apnnews/apnnews/chunks.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Video stopped? m3u8 works
