### ISSUE TITLE
Broken: Some channels on https://iptv-org.github.io/iptv/countries/ma.m3u

### ISSUE THREAD

**Issue by Konzkripted** [iptv-org/iptv#16635]
### Broken Link

https://iptv-org.github.io/iptv/countries/ma.m3u

### What happened to the stream?

Not loading

### Notes (optional)

None of these chnnaels work on the Morocco playlist unfortunately :( Please can you help restore this, many thanks!

1. Al Aoula AlAoula.ma
2. Al Aoula Laayoune AlAoulaLaayoune.ma
3. Arryadia (https://iptv-org.github.io/channels/ma/Arryadia)
4. Athaqafia Athaqafia.ma
5. Al Maghribia (https://iptv-org.github.io/channels/ma/AlMaghribia)
6. Tamazight TV (https://iptv-org.github.io/channels/ma/TamazightTV)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by manoflorida** [comment]
#EXTINF:0 tvg-id="" tvg-logo="http://snrtlive.ma/sites/all/themes/snrtlive/images/alaoula.png" group-title="", AlAoula Tv
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
#EXTVLCOPT:http-referrer=https://snrtlive.ma/
https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/al_aoula_inter/hls_snrt/al_aoula_inter.m3u8

**Comment by EA3H** [comment]
Any updates on a fix in particular the Al Aoula channel? 

Appreciate the effort in getting this resolved.

**Comment by jkhamlichi** [comment]
Unfortunatly the channels still not working. manoflorida workaround works on VLC but still having problems on iOS & Android.

**Comment by Mo606606** [comment]
Any Update 🫣

**Comment by manoflorida** [comment]
Hey I don’t know how to pull a request and change the list so if someone know how to he can change it with this code

#EXTINF:0 tvg-id="AlAoula.ma" tvg-logo="http://snrtlive.ma/sites/all/themes/snrtlive/images/alaoula.png" group-title="MOROCCO", AlAoula Tv
#EXTVLCOPT:http-referrer=https://snrtlive.ma/
https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/al_aoula_inter/hls_snrt/al_aoula_inter.m3u8
#EXTINF:0 tvg-id="AlMaghribia.ma" tvg-logo="http://snrtlive.ma/sites/all/themes/snrtlive/images/almaghribia.png" group-title="MOROCCO",Al Maghribia
http://cdnamd-hls-globecast.akamaized.net/live/ramdisk/al_maghribia_snrt/hls_snrt/al_maghribia_snrt.m3u8
#EXTINF:0 tvg-id="ext" tvg-logo="http://snrtlive.ma/sites/all/themes/snrtlive/images/laayoune.png" group-title="MOROCCO", Al Aoula Laayoune
#EXTVLCOPT:http-referrer=https://snrtlive.ma/
https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/al_aoula_laayoune/hls_snrt/index.m3u8
#EXTINF:0 tvg-id="Arryadia.ma" tvg-logo="http://snrtlive.ma/sites/all/themes/snrtlive/images/arriyadia.png" group-title="MOROCCO", Arryadia
#EXTVLCOPT:http-referrer=https://snrtlive.ma/
https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/arriadia/hls_snrt/index.m3u8
#EXTINF:0 tvg-id="Arrabiaa.ma" tvg-logo="http://snrtlive.ma/sites/all/themes/snrtlive/images/attakafiya.png" group-title="MOROCCO", Arrabiaa
#EXTVLCOPT:http-referrer=https://snrtlive.ma/
https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/arrabiaa/hls_snrt/index.m3u8
#EXTINF:0 tvg-id="Assadissa.ma" tvg-logo="http://snrtlive.ma/sites/all/themes/snrtlive/images/assadissa.png" group-title="MOROCCO", Assadissa
#EXTVLCOPT:http-referrer=https://snrtlive.ma/
https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/assadissa/hls_snrt/index.m3u8
#EXTINF:0 tvg-id="AlThamenahTamazight.ma" tvg-logo="http://snrtlive.ma/sites/all/themes/snrtlive/images/tamazight.png" group-title="MOROCCO",Tamazight
#EXTVLCOPT:http-referrer=https://snrtlive.ma/
https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/tamazight_tv8_snrt/hls_snrt/index.m3u8
It’s working fine.

**Comment by azgaresncf** [comment]
i will add it later

**Comment by Konzkripted** [comment]
> Hey I don’t know how to pull a request and change the list so if someone know how to he can change it with this code
> 
> #EXTINF:0 tvg-id="AlAoula.ma" tvg-logo="http://snrtlive.ma/sites/all/themes/snrtlive/images/alaoula.png" group-title="", AlAoula Tv #EXTVLCOPT:http-referrer=https://snrtlive.ma/ https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/al_aoula_inter/hls_snrt/al_aoula_inter.m3u8 #EXTINF:0 tvg-id="AlMaghribia.ma" tvg-logo="http://snrtlive.ma/sites/all/themes/snrtlive/images/almaghribia.png" group-title="",Al Maghribia http://cdnamd-hls-globecast.akamaized.net/live/ramdisk/al_maghribia_snrt/hls_snrt/al_maghribia_snrt.m3u8 #EXTINF:0 tvg-id="ext" tvg-logo="http://snrtlive.ma/sites/all/themes/snrtlive/images/laayoune.png" group-title="", Al Aoula Laayoune #EXTVLCOPT:http-referrer=https://snrtlive.ma/ https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/al_aoula_laayoune/hls_snrt/index.m3u8 #EXTINF:0 tvg-id="Arryadia.ma" tvg-logo="http://snrtlive.ma/sites/all/themes/snrtlive/images/arriyadia.png" group-title="", Arryadia #EXTVLCOPT:http-referrer=https://snrtlive.ma/ https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/arriadia/hls_snrt/index.m3u8 #EXTINF:0 tvg-id="Arrabiaa.ma" tvg-logo="http://snrtlive.ma/sites/all/themes/snrtlive/images/attakafiya.png" group-title="", Arrabiaa #EXTVLCOPT:http-referrer=https://snrtlive.ma/ https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/arrabiaa/hls_snrt/index.m3u8 #EXTINF:0 tvg-id="Assadissa.ma" tvg-logo="http://snrtlive.ma/sites/all/themes/snrtlive/images/assadissa.png" group-title="", Assadissa #EXTVLCOPT:http-referrer=https://snrtlive.ma/ https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/assadissa/hls_snrt/index.m3u8 #EXTINF:0 tvg-id="AlThamenahTamazight.ma" tvg-logo="http://snrtlive.ma/sites/all/themes/snrtlive/images/tamazight.png" group-title="",Tamazight #EXTVLCOPT:http-referrer=https://snrtlive.ma/ https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/tamazight_tv8_snrt/hls_snrt/index.m3u8 It’s working fine.

Thanks, but how do I use this? I entered the m3u8 links as channels with m3u4u but it still doesn't work

**Comment by Dum4G** [comment]
Already merged as it seems
