### ISSUE TITLE
Broken: TeleSUR

### ISSUE THREAD

**Issue by Cicindis** [iptv-org/iptv#16647]
### Broken Link
https://github.com/LaneSh4d0w/IPTV_Exception/raw/master/channels/ve/telesur.m3u8

### What happened to the stream?
Not loading

### Notes (optional)
Valid link: https://cdnesmain.telesur.ultrabase.net/mbliveMain/hd/playlist.m3u8 (edit: doesnt work anymore)

### Contributing Guide
* [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Cicindis** [comment]
Can this be tagged as broken stream?

**Comment by BellezaEmporium** [comment]
Works for me.

**Comment by Cicindis** [comment]
No links work for me in TV(ParserException error) nor in my PC player, even the one that I linked earlier as valid doesn't work anymore for me at least.

**Comment by azgaresncf** [comment]
This one (**https://cdnesmain.telesur.ultrabase.net/mbliveMain/hd/playlist.m3u8**) works better.

**Comment by BellezaEmporium** [comment]
Yep, this is the HD version only. My playlist was adaptive.

**Comment by azgaresncf** [comment]
> Yep, this is the HD version only. My playlist was adaptive.
Oh okay, that's why.
