### ISSUE TITLE
Add: WNJU-DT1 (Telemundo 47)

### ISSUE THREAD

**Issue by cold360** [iptv-org/iptv#16646]
### Channel ID (required)

WNJUDT1.us

### Channel Name

Telemundo New York

### Stream URL (required)

https://content.uplynk.com/channel/b6a96ed39d694ae1b738faa98cf7dd3f.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by sharklatan** [comment]
CCTV CAMERA 

![IMG_6055](https://github.com/user-attachments/assets/95a264c9-9508-4c92-9c07-277f5cdfacb2)

**Comment by R4IN2007** [comment]
Yeah

> CCTV CAMERA
> 
> ![IMG_6055](https://private-user-images.githubusercontent.com/5210221/358891070-95a264c9-9508-4c92-9c07-277f5cdfacb2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NDg4NDksIm5iZiI6MTcyNTU0ODU0OSwicGF0aCI6Ii81MjEwMjIxLzM1ODg5MTA3MC05NWEyNjRjOS05NTA4LTRjOTItOWMwNy0yNzdmNWNkZmFjYjIuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDE1MDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YzNmMWYyYWUwMGNiODFmNDUxMTVkNmEzOTc2MzljZTMwNTNhMmNiMTllYTYzNTBhMjQ3NTlkYTdjMDVmNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hsCT7bHFJjDST_2wDp7uDXu8GtiJITM1Pd4Tm04CAlY)

Yeah, The Telemundo K22JA Stream changes over time to random cctv streams or Scripps News
