### ISSUE TITLE
Broken: channels from the country category — Bangladesh

### ISSUE THREAD

**Issue by Abdullak-Ak52** [iptv-org/iptv#16644]
### Broken Link

https://iptv-org.github.io/iptv/countries/bd.m3u

### What happened to the stream?

Not loading

### Notes (optional)

So many channels are not working

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Please specify channels that are not working
