### ISSUE TITLE
Add: CMT

### ISSUE THREAD

**Issue by shiawasevip** [iptv-org/iptv#16645]
### Channel ID (required)

CMTEast.us

### Channel Name

CMT

### Stream URL (required)

http://209.126.107.163:1234/stream/dtvcomplete/cmthd/master.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by cold360** [comment]
dumbfuck keeps removing the stream every 12 hours

**Comment by shiawasevip** [comment]
stream gone again
