### ISSUE TITLE
Broken: RT en Español

### ISSUE THREAD

**Issue by Cicindis** [iptv-org/iptv#16649]
### Broken Link
https://rt-esp.rttv.com/dvr/rtesp/playlist.m3u8 / 
https://rt-esp.rttv.com/live/rtesp/playlist.m3u8

### What happened to the stream?
Gets more buffered/paused over time

### Contributing Guide
* [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
https://rt-esp.rttv.com/live/rtesp/playlist.m3u8

**Comment by Cicindis** [comment]
Can this be tagged as broken stream?
