### ISSUE TITLE
Add:  News Malayalam 24/7

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#16650]
### Channel ID (required)

NewsMalayalam24/7.in

### Channel Name

News Malayalam 24/7

### Stream URL (required)

https://www.youtube.com/watch?v=o-X_8l4PyLA

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
![image](https://github.com/iptv-org/iptv/assets/50982832/f22f9bc5-a8ad-4b75-acb2-39c49dab7f84)

**Comment by Manipulativemachan** [comment]
https://www.youtube.com/watch?v=n8IC_vb417s 

Find this link

**Comment by R4IN2007** [comment]
https://ythls.armelin.one/channel/UCXp6JTdq7-WwBK09S7SzmxQ.m3u8

**Comment by ProPontifex** [comment]
Just submitted

**Comment by Dum4G** [comment]
Properly sbmitted in https://github.com/iptv-org/iptv/issues/16776
