### ISSUE TITLE
Broken: CGTN

### ISSUE THREAD

**Issue by Cicindis** [iptv-org/iptv#16655]
### Broken Link
https://dai.google.com/linear/hls/event/r4sa-f6GSN2XIvzKv5jVng/master.m3u8

### What happened to the stream?
In web it loads but not in player Edit: only IPTV player

### Notes (optional)
Valid link: https://news.cgtn.com/resource/live/english/cgtn-news.m3u8

### Contributing Guide
* [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
In VLC Works.

**Comment by Cicindis** [comment]
I stand corrected, in multimedia players it does work, but, and this I should have specified, in IPTV players, at least in OTT TV, TiviMate and IPTV Pro, it perpetually stops at 0% buffered until it errors.
