### ISSUE TITLE
Broken TVP 1 and TVP 2

### ISSUE THREAD

**Issue by kisiel999** [iptv-org/iptv#1666]
**What's wrong?**

**Country of the channel:Poland**

**Channel Name:TVP 1 and TVP 2**

**Broken Link:**
http://54.38.52.108/hls/kurwatvp1.m3u8
http://54.38.52.108/hls/kurwatvp2.m3u8

**Additional Information (optional):**
Not working on the VLC.

**Comment by freearhey** [comment]
Links removed.
