### ISSUE TITLE
Restore TNT East (720p) [Geo-blocked]   It was replaced with a different TNT channel that is 1080

### ISSUE THREAD

**Issue by moonbairn** [iptv-org/iptv#16666]
### Channel ID (required)

tvg-id="TNTEast.us"

### Channel Name

TNT East (720p) [Geo-blocked]

### Stream URL (required)

https://turnerlive.warnermediacdn.com/hls/live/2023168/tnteast/slate/VIDEO_0_3564000.m3u8

### Quality

720p

### Label

None

### Notes

#EXTINF:-1 tvg-id="TNTEast.us" tvg-country="US" tvg-language="English;Spanish" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/TNT_Logo_2016.svg/512px-TNT_Logo_2016.svg.png" group-title="General",TNT East (720p) [Geo-blocked]
https://tve-live-lln.warnermediacdn.com/hls/live/2023168/tnteast/slate/VIDEO_0_3564000.m3u8

was removed and replaced with:

#EXTINF:-1 tvg-id="TNTEast.us" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/TNT_Logo_2016.svg/512px-TNT_Logo_2016.svg.png" group-title="General",TNT
http://170.254.18.106/TNT/index.m3u8

The problem for me is that the new TNT is 1080 and my internet connection is rate-limited so I'd rather have the 720 stream restored.  Added bonus is that the TNT East (720p) [Geo-blocked] channel doesn't have commercials (same as with TNT West (720p) [Geo-blocked] which is still included in your new US-General playlist)

You can also just leave the new TNTEast.us 1080 for those who prefer 1080.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
The 720p stream (https://tve-live-lln.warnermediacdn.com/hls/live/2023168/tnteast/slate/VIDEO_0_3564000.m3u8) don't works (403 Forbidden).

**Comment by Alstruit** [comment]
Geo-blocked to US only.

**Comment by Alstruit** [comment]
Closing in favor #16798.
