### ISSUE TITLE
Add: MTV Live (USA)

### ISSUE THREAD

**Issue by InsolenceWillow** [iptv-org/iptv#16663]
### Channel ID (required)

MTVLive.us

### Channel Name

MTV Live

### Stream URL (required)

https://fl2.moveonjoy.com/MTV_LIVE/index.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
**Copyrighted stream.**
