### ISSUE TITLE
Add: Disney Junior Mexico

### ISSUE THREAD

**Issue by mavijavi5124** [iptv-org/iptv#16668]
### Channel ID (required)

Disneyjunior.mx (no id yet)

### Channel Name

Disney Junior Mexico

### Stream URL (required)

http://budtvlight.com:25461/live/jaime/3DbdkaKhwZEd/159129.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Xtream-codes server. We do not allow those.
