### ISSUE TITLE
Add: MTV Classic (USA)

### ISSUE THREAD

**Issue by InsolenceWillow** [iptv-org/iptv#16662]
### Channel ID (required)

MTVClassicEast.us

### Channel Name

MTV Classic

### Stream URL (required)

https://fl2.moveonjoy.com/MTV_CLASSIC/index.m3u8

### Quality

360p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
**Copyrighted stream.**
