### ISSUE TITLE
Add: CNN Prima News

### ISSUE THREAD

**Issue by olstern01** [iptv-org/iptv#16667]
### Channel ID (required)

CNNPrimaNews.cz

### Channel Name

CNN Prima News

### Stream URL (required)

https://prima-ott-live-sec.ssl.cdn.cra.cz/szqq5iK0_3VSay0nM2xi-g==,1717313523/channels/prima_cnn/playlist-live_lq.m3u8

### Quality

360p

### Label

None

### Notes

I don't know if the link is temporary. But I tried it in VLC and it works.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Tokenized link
