### ISSUE TITLE
Add: mtvU (USA)

### ISSUE THREAD

**Issue by InsolenceWillow** [iptv-org/iptv#16664]
### Channel ID (required)

mtvU.us

### Channel Name

mtvU

### Stream URL (required)

https://fl2.moveonjoy.com/MTV_U/index.m3u8

### Quality

480p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by rushereeeeee** [comment]
I also found more stuff through this that mostly include  US Channels

#EXTINF:-1 tvg-id="FXX.us" FXX East
http://fl2.moveonjoy.com/FXX/index.m3u8

#EXTINF:-1 tvg-id="SECNetwork.us" SEC Network
http://fl2.moveonjoy.com/SEC_NETWORK/index.m3u8

#EXTINF:-1 tvg-id="GolfChannel.us" NBC Golf
http://fl2.moveonjoy.com/GOLF_CHANNEL/index.m3u8

#EXTINF:-1 tvg-id="Freeform.us" Freeform East
http://fl2.moveonjoy.com/FREE_FORM/index.m3u8

(This list isn’t done yet but I founded more which I’ll add soon ^-^)

**Comment by InsolenceWillow** [comment]
Oh Wow, Thank You!

**Comment by rushereeeeee** [comment]
Np man ;) I’m gonna creating the list so check this thread for updates

**Comment by InsolenceWillow** [comment]
I Found Some More Too:

Disney Channel East: http://fl2.moveonjoy.com/DISNEY_CHANNEL/index.m3u8
DisneyJr East: http://fl2.moveonjoy.com/DISNEY_JR/index.m3u8
DisneyXD East: http://fl2.moveonjoy.com/DISNEY_XD/index.m3u8
ABC East (WOLO) (Columbia): http://fl2.moveonjoy.com/ABC_EAST/index.m3u8
TLC East: http://fl2.moveonjoy.com/TLC/index.m3u8
HBO East: http://fl2.moveonjoy.com/HBO/index.m3u8
HBO2 East: http://fl2.moveonjoy.com/HBO_2/index.m3u8
HBO Comedy East: http://fl2.moveonjoy.com/HBO_COMEDY/index.m3u8
HBO Family East: http://fl2.moveonjoy.com/HBO_FAMILY/index.m3u8
HBO Zone East: http://fl2.moveonjoy.com/HBO_ZONE/index.m3u8
Starz East: http://fl2.moveonjoy.com/STARZ/index.m3u8
Starz Encore East: http://fl2.moveonjoy.com/STARZ_ENCORE/index.m3u8
Starz Comedy East: http://fl2.moveonjoy.com/STARZ_COMEDY/index.m3u8
Starz Encore Action: http://fl2.moveonjoy.com/STARZ_ENCORE_ACTION/index.m3u8
Starz Encore Westerns: http://fl2.moveonjoy.com/STARZ_ENCORE_WESTERNS/index.m3u8
Showtime East: http://fl2.moveonjoy.com/SHOWTIME/index.m3u8
Showtime 2 East: http://fl2.moveonjoy.com/SHOWTIME_2/index.m3u8
Showtime Extreme East: http://fl2.moveonjoy.com/SHOWTIME_EXTREME/index.m3u8
Showtime Next East: http://fl2.moveonjoy.com/SHOWTIME_NEXT/index.m3u8
Showtime Women East: http://fl2.moveonjoy.com/SHOWTIME_WOMEN/index.m3u8
Cinemax East: http://fl2.moveonjoy.com/CINEMAX_EAST/index.m3u8
Cartoon Network / [adult swim]: http://fl2.moveonjoy.com/CARTOON_NETWORK/index.m3u8
BBC America: http://fl2.moveonjoy.com/BBC_AMERICA/index.m3u8
Lifetime East: http://fl2.moveonjoy.com/LIFETIME/index.m3u8
Lifetime Movie Network: http://fl2.moveonjoy.com/LIFETIME_MOVIE_NETWORK/index.m3u8
BET Her East: http://fl2.moveonjoy.com/BET_HER/index.m3u8
BET Soul: http://fl2.moveonjoy.com/BET_SOUL/index.m3u8
BET Gospel: http://fl2.moveonjoy.com/BET_GOSPEL/index.m3u8

**Comment by rushereeeeee** [comment]
SICKKK

**Comment by InsolenceWillow** [comment]
Do You Have Discord? I Can Send You The Whole Entire List On There That I've Got!

**Comment by rushereeeeee** [comment]
I have a discord now, ateam_149sdddd

**Comment by BogartDabid** [comment]
You have a animal planet m3u8 and animax

**Comment by BogartDabid** [comment]
Kindly send to me bro my discord is gab0768

**Comment by BogartDabid** [comment]
Please send to me bro🥺

**Comment by BogartDabid** [comment]
> Do You Have Discord? I Can Send You The Whole Entire List On There That I've Got!

I have discord bro this

 gab0768

Thank you in advance bro

**Comment by Metroid2023** [comment]
Cool! I can't find TeenNick anywhere.

**Comment by azgaresncf** [comment]
**Copyrighted streams.**

**Comment by InsolenceWillow** [comment]
> **Copyrighted streams.**

Isn't that the point?

**Comment by spotanjo3** [comment]
http://fl3.moveonjoy.com/STARZ_ENCORE/index.m3u8 is dead
