### ISSUE TITLE
Add: Dream TV

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#16670]
### Channel ID (required)

DreamTV.mn

### Channel Name

Dream TV

### Stream URL (required)

https://cdn1.skygo.mn/live/disk1/Dreambox/HLS-FTA/Dreambox.m3u8

### Quality

None

### Label

None

### Notes

Hey, guys! I found the livestream link in months regarding about Dream TV since it's working now since this link hasn't updated in [nine months ago](https://github.com/iptv-org/iptv/blob/master/streams/mn.m3u).

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
It is either not 24/7 or it is bugged, but I will add it to the repo.
![dream](https://github.com/iptv-org/iptv/assets/50982832/41bc6126-1cd7-49f8-b756-85f7b85cefef)
