### ISSUE TITLE
Broken: MRTV (720p)

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#16671]
### Broken Link

https://5a13fe32ef748.streamlock.net/mmplay/mrtv/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

@BellezaEmporium Hey, mods! The livestream link for MRTV was dead about a few weeks ago along many Burmese livestream channels went dead too.

BTW, is the audio track from MRTV livestream links was either sync or out of sync very often?

https://mrtv.gov.mm/en/live-stream

https://www.myanmartvchannels.com/mrtv.html

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by pattaya007** [comment]
i found this problem also for a while,do you have other stream for myanmar tv,i have some to discuss with you,contact me!

**Comment by Sphinxroot** [comment]
https://www.twitch.tv/livestreamingmrtv

**Comment by AVGCFan1995** [comment]
> i found this problem also for a while,do you have other stream for myanmar tv,i have some to discuss with you,contact me!

Sorry for the delay but did you find any good quality livestream links for MRTV and other Burmese TV channels since many of them almost dead nowadays.

Here's the dead livestream links that mostly related to 183.89.246.119:8881, 5a13fe32ef748.streamlock.net and /foreveralive1-a.akamaihd.net.

5 Plus (480p)
http://183.89.246.119:8881/play/a07w/index.m3u8
5 Plus (480p)
https://5a13fe32ef748.streamlock.net/mmplay/5plus/playlist.m3u8
Channel 7 (480p)
http://183.89.246.119:8881/play/a07v/index.m3u8
Channel 7 (480p)
https://5a13fe32ef748.streamlock.net/mmplay/channel7/playlist.m3u8
Channel 9 (480p)
http://183.89.246.119:8881/play/a07y/index.m3u8
Channel K (480p)
http://183.89.246.119:8881/play/a080/index.m3u8
Channel K (480p)
https://5a13fe32ef748.streamlock.net/mmplay/channel9/playlist.m3u8
Education Channel (480p)
http://183.89.246.119:8881/play/a07s/index.m3u8
Fortune TV (480p)
http://183.89.246.119:8881/play/a082/index.m3u8
Mahar Bawdi TV (480p)
https://foreveralive1-a.akamaihd.net/327fbb9692d74b8a9fd35e75359fa826/ap-southeast-1/6057949479001/playlist.m3u8
MITV (480p)
http://183.89.246.119:8881/play/a07r/index.m3u8
MITV (480p)
https://5a13fe32ef748.streamlock.net/mmplay/mitv/playlist.m3u8
MN TV (480p)
http://183.89.246.119:8881/play/a07x/index.m3u8
MRTV (720p)
https://5a13fe32ef748.streamlock.net/mmplay/mrtv/playlist.m3u8
MRTV 4 (480p)
http://183.89.246.119:8881/play/a07u/index.m3u8
MRTV 4 (480p)
https://5a13fe32ef748.streamlock.net/mmplay/mrtv-4/playlist.m3u8
MRTV Entertainment (480p)
http://183.89.246.119:8881/play/a07t/index.m3u8
MRTV Entertainment (480p)
https://5a13fe32ef748.streamlock.net/mmplay/mrtv-entertainment/playlist.m3u8
MRTV Farmers (480p)
http://183.89.246.119:8881/play/a07p/index.m3u8
MRTV News (1080p)
http://183.89.246.119:8881/play/a07m/index.m3u8
MRTV NRC (480p)
http://183.89.246.119:8881/play/a07o/index.m3u8
MRTV Parliament (480p)
http://183.89.246.119:8881/play/a07n/index.m3u8
MRTV Parliament (480p)
https://5a13fe32ef748.streamlock.net/mmplay/hluttaw/playlist.m3u8
MRTV Sports (480p)
http://183.89.246.119:8881/play/a07q/index.m3u8
MWD (480p)
http://183.89.246.119:8881/play/a07z/index.m3u8
YTV (480p)
http://183.89.246.119:8881/play/a081/index.m3u8

The only Burmese livestream links are still alive as of 2024.

Channel K (720p)
https://l1-xl1.myanmarnet.com/relay/channelk/ch1/stream.m3u8
Mahar TV (720p)
https://tv.mahar.live/mahar/website.stream/playlist.m3u8
MCS (720p)
https://l1-xl1.myanmarnet.com/relay2/mcs/ch1/stream.m3u8
MN TV (720p)
https://l1-xl1.myanmarnet.com/relay/mntv/ch1/stream.m3u8

**Comment by AVGCFan1995** [comment]
> https://www.twitch.tv/livestreamingmrtv

Yes, I know but the livestream link can be flawed most likely due to the audio was entirely out of sync earlier but if you pay attention between the audio and the footage.

**Comment by pattaya007** [comment]
actually you can watch many myanmar tv online,like mymanmartvchannels.com,pyoneplay.com or even mrtv.gov.mm,recently i found an app called myanmar cast,it has many tv channels,what's more,it changes tv streaming number by nations,i try to cracked the stream address and found it is quite difficult,i hope you can have some ways out.

**Comment by AVGCFan1995** [comment]
> actually you can watch many myanmar tv online,like mymanmartvchannels.com,pyoneplay.com or even mrtv.gov.mm,recently i found an app called myanmar cast,it has many tv channels,what's more,it changes tv streaming number by nations,i try to cracked the stream address and found it is quite difficult,i hope you can have some ways out.

Thanks for the info, pattaya007. Can you update the livestream links from [Myanmar](https://github.com/iptv-org/iptv/blob/master/streams/mm.m3u) in order to remove 183.89.246.119:8881, 5a13fe32ef748.streamlock.net and foreveralive1-a.akamaihd.net links please because there's all dead.

**Comment by BellezaEmporium** [comment]
https://*snip*/iptv-query?url=https://www.twitch.tv/livestreamingmrtv works OK on my part (so far)

**Comment by pattaya007** [comment]
streamlock.net back to life today,wow!

**Comment by BellezaEmporium** [comment]
> actually you can watch many myanmar tv online,like mymanmartvchannels.com,pyoneplay.com or even mrtv.gov.mm,recently i found an app called myanmar cast,it has many tv channels,what's more,it changes tv streaming number by nations,i try to cracked the stream address and found it is quite difficult,i hope you can have some ways out.

After a first check, the iptv link given inside the APK is... a ton of images.

**Comment by BellezaEmporium** [comment]
Talking about this ? 

http://l1-xl1.myanmarnet.com/relay/mntv/ch1/stream.m3u8
