### ISSUE TITLE
Add TV Regionalna (ZGZM) (Poland, polish channel)

### ISSUE THREAD

**Issue by kisiel999** [iptv-org/iptv#1667]
**Country of the channel: Poland**

**Channel Name: TV Regionalna (ZGZM)**

**Channel Language: polish**

**Additional Information (optional):**
https://tvreg.klemit.net/regionalna/stream/index.m3u8
The name "TV Regionalna" is very general, I wrote ZGZM.

**Comment by freearhey** [comment]
Added.
