### ISSUE TITLE
Add regional TVP channels

### ISSUE THREAD

**Issue by kisiel999** [iptv-org/iptv#1668]
**Country of the channel:Poland**

**Channel Names:

- TVP3 Białystok, 
- TVP3 Bydgoszcz, 
- TVP3 Gdańsk, 
- TVP3 Gorzów, 
- TVP3 Katowice, 
- TVP3 Kielce, 
- TVP3 Kraków, 
- TVP3 Lublin, 
- TVP3 Łódź, 
- TVP3 Olsztyn, 
- TVP3 Opole, 
- TVP3 Poznań, 
- TVP3 Rzeszów, 
- TVP3 Szczecin, 
- TVP3 Warszawa, 
- TVP3 Wrocław

**

**Channel Language:all polish**

**Additional Information (optional):
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpbialystok
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpbydgoszcz
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpgdansk
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpgorzow
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpkatowice
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpkielce
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpkrakow
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvplodz
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvplublin
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpolsztyn
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpopole
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvppoznan
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvprzeszow
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpszczecin
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpwarszawa
http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpwroclaw
**

**Comment by freearhey** [comment]
@kisiel999 Thank you for your help! All channels were added to the playlist.
