### ISSUE TITLE
Add: TVP3 Warszawa

### ISSUE THREAD

**Issue by Irylek** [iptv-org/iptv#16683]
### Channel ID (required)

TVP3Warszawa.pl

### Channel Name

TVP3 Warszawa

### Stream URL (required)

https://cdndai.pl/tvp3warszawasd/index.m3u8

### Quality

576p

### Label

None

### Timeshift

0

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
**Copyrighted stream.**
