### ISSUE TITLE
Add: СТБ

### ISSUE THREAD

**Issue by DzuyCuong** [iptv-org/iptv#16686]
### Channel ID (required)

STB.ua

### Channel Name

СТБ

### Stream URL (required)

http://85.223.221.130:8000/play/a09q

### Quality

576p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
**Doesn't work + probably copyrighted stream.**
