### ISSUE TITLE
Broken: Cartoon Network Russia

### ISSUE THREAD

**Issue by iamdelickkk** [iptv-org/iptv#16689]
broken url  - 404 error
new url - `http://stream01.vnet.am/Kinosemya/mono.m3u8`

**Comment by azgaresncf** [comment]
**Copyrighted stream.**

**Comment by azgaresncf** [comment]
nvm, i didn't see the vnet.m3u8 file :')

**Comment by noreplywavetv-eng** [comment]
Not working anymore 😭
