### ISSUE TITLE
Add: Pop Max +1

### ISSUE THREAD

**Issue by shiawasevip** [iptv-org/iptv#16688]
### Channel ID (required)

PopMaxPlus1.uk

### Channel Name

Pop Max +1

### Stream URL (required)

http://84.203.199.198:9981/stream/channel/81e8c23c5fdf0f63f32fd461d4374368

### Quality

480p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
**Copyrighted stream**.
