### ISSUE TITLE
Add: Disney Junior (Poland)

### ISSUE THREAD

**Issue by TestNintendo** [iptv-org/iptv#16680]
### Channel ID (required)

DisneyJunior.pl

### Channel Name

Disney Junior (Poland)

### Stream URL (required)

http://185.236.229.62:9981/play/a06n

### Quality

576p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Irylek** [comment]
That is Nick Jr. Poland.

**Comment by mavijavi5124** [comment]
yeah this is Not CBeebies poland

**Comment by TestNintendo** [comment]
sorry, i fixed the description

**Comment by mavijavi5124** [comment]
> sorry, i fixed the description

This is Disney Jr. btw not Nick Jr.

**Comment by TestNintendo** [comment]
description fixed again

**Comment by azgaresncf** [comment]
**Copyrighted stream.**

**Comment by TestNintendo** [comment]
> **Copyrighted stream.**

if the channel isn't in the blacklist, i think it's fine

**Comment by azgaresncf** [comment]
> > **Copyrighted stream.**
> 
> if the channel isn't in the blacklist, i think it's fine

okay I take it back
