### ISSUE TITLE
Add: Pop UK

### ISSUE THREAD

**Issue by shiawasevip** [iptv-org/iptv#16687]
### Channel ID (required)

Pop.uk

### Channel Name

Pop UK

### Stream URL (required)

http://84.203.199.198:9981/stream/channel/b19fe2c520d3f786cc7dcc99634d384f?profile=webtv-vp8-vorbis-webm

### Quality

480p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by mavijavi5124** [comment]
not working "Failed to start playback" in pot player and your input cant be opened in VLC

**Comment by shiawasevip** [comment]
> not working "Failed to start playback" in pot player and your input cant be opened in VLC

edited

**Comment by shiawasevip** [comment]
ah alright, didnt see it in the blocklist
