### ISSUE TITLE
Broken: POP Max

### ISSUE THREAD

**Issue by PenTick** [iptv-org/iptv#16690]
### Broken Link

https://live-sonybebanjo.simplestreamcdn.com/live8/popmax/bitrate1.isml/live.m3u8

### What happened to the stream?

Shows looped video

### Notes (optional)

It keeps looping the end of a Playmobil promo and a Total Dramarama promo. And when the TDR promo is almost done, it loops back to the Playmobil promo.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by PenTick** [comment]
Now the stream is full on dead.

**Comment by queazified** [comment]
> Now the stream is full on dead.

Makes sense as the POP Max channel was delisted from channels in the UK
