### ISSUE TITLE
Add: Disney Jr. East

### ISSUE THREAD

**Issue by mavijavi5124** [iptv-org/iptv#16699]
### Channel ID (required)

DisneyJuniorEast.us

### Channel Name

Disney Jr.

### Stream URL (required)

https://fl2.moveonjoy.com/DISNEY_JR/index.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BogartDabid** [comment]
You have a DreamWorks bro and Animal Planet?

**Comment by Metroid2023** [comment]
Animal Planet is blocked.

**Comment by mavijavi5124** [comment]
> You have a DreamWorks bro and Animal Planet?

i dont have DreamWorks And Animal Planet

**Comment by azgaresncf** [comment]
**Copyrighted stream.**
