### ISSUE TITLE
Add: Nick Jr. (East) [USA]

### ISSUE THREAD

**Issue by Metroid2023** [iptv-org/iptv#16695]
### Channel ID (required)

NickJrEast.us

### Channel Name

Nick Jr. East [USA]

### Stream URL (required)

https://fl2.moveonjoy.com/NICK_JR/index.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
**Copyrighted stream.**
