### ISSUE TITLE
Are MPD streams desirable?

### ISSUE THREAD

**Issue by kisiel999** [iptv-org/iptv#1669]
Can I add MPD streams on a request channel?

**Comment by freearhey** [comment]
As long as the stream is played in VLC player there should be no problems.

**Comment by kisiel999** [comment]
@freearhey 
Ok, try in VLC this Polish religious channel stream. TV TRWAM
https://trwamtv.live.rd.insyscd.net/cl01/out/u/trwam.mpd

**Comment by freearhey** [comment]
@kisiel999 doesn't work for me

**Comment by Nintendocustom** [comment]
Try this one: https://trwamtv.live.rd.insyscd.net/cl01/out/u/trwam.m3u8

**Comment by freearhey** [comment]
@Nintendocustom it does not work either

**Comment by Nintendocustom** [comment]
I think this is a VLC problem because it's working on streamtest.in but I found a solution for this:

https://trwamtv.live.e57-po.insyscd.net/cl01/out/u/trwam_1.m3u8
https://trwamtv.live.e57-po.insyscd.net/cl01/out/u/trwam_2.m3u8 
https://trwamtv.live.e57-po.insyscd.net/cl01/out/u/trwam_3.m3u8

**Comment by kisiel999** [comment]
@Nintendocustom teach me how to change mpd stream to m3u8

**Comment by bertperrisor** [comment]
Why do you test streams on VLC @freearhey ? There are far more capable IPTV streams out there which can play MPD (MPEG Dash) streams and M3U8 at the same time. Also not all streams can be played just simply by passing the M3U8 links, some needing extra headers like Referer due to source protection.

**Comment by freearhey** [comment]
@bertperrisor If you know another cross-platform free player with support of IPTV streams that is known all over the world please let me know. And yes, VLC player also supports custom headers.

**Comment by exodiver** [comment]
> @Nintendocustom teach me how to change mpd stream to m3u8

You can't unless you are restreaming  the mpd stream yourself or the original provider has embedded m3u8 stream inside the mpd stream.
