### ISSUE TITLE
Add: Disney XD East

### ISSUE THREAD

**Issue by mavijavi5124** [iptv-org/iptv#16698]
### Channel ID (required)

DisneyXDEast.us

### Channel Name

Disney XD

### Stream URL (required)

https://fl2.moveonjoy.com/DISNEY_XD/index.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
**Copyrighted stream.**
