### ISSUE TITLE
Add: Disney Channel East

### ISSUE THREAD

**Issue by mavijavi5124** [iptv-org/iptv#16697]
### Channel ID (required)

DisneyChannelEast.us

### Channel Name

Disney Channel

### Stream URL (required)

https://fl2.moveonjoy.com/DISNEY_CHANNEL/index.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
**Copyrighted stream.**
