### ISSUE TITLE
Add: Cartoon Network (East) [USA]

### ISSUE THREAD

**Issue by Metroid2023** [iptv-org/iptv#16694]
### Channel ID (required)

CartoonNetworkEast.us

### Channel Name

Cartoon Network (East) [USA]

### Stream URL (required)

https://fl2.moveonjoy.com/CARTOON_NETWORK/index.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Metroid2023** [comment]
Not working anymore!

**Comment by Metroid2023** [comment]
It's working again.

**Comment by azgaresncf** [comment]
**Copyrighted stream.**

**Comment by M3UDay** [comment]
Your link is redirecting to https://84.17.40.25/CARTOON_NETWORK/index.m3u8.But the post inside is linked to https://fl6.moveonjoy.com/CARTOON_NETWORK/index.m3u8

**Comment by yellowykids** [comment]
It stopped working

**Comment by BlurnSox** [comment]
> It stopped working
It is?

**Comment by BlurnSox** [comment]
ok now it’s not working

**Comment by jsemtobias** [comment]
stopped working a few days ago:( hope it returns

**Comment by BlurnSox** [comment]
maybe it got dmca striked

**Comment by FlixOnJoy** [comment]
guys, moj shut down. They don't work anymore
