### ISSUE TITLE
Add: FXX East (USA)

### ISSUE THREAD

**Issue by rushereeeeee** [iptv-org/iptv#16691]
### Channel ID (required)

FXX.us

### Channel Name

FXX East

### Stream URL (required)

http://fl2.moveonjoy.com/FXX/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
**Copyrighted stream.**

**Comment by spotanjo3** [comment]
Let you know that it didnt work. Change it to fl3 and it works for me.
