### ISSUE TITLE
Add: FX East (USA)

### ISSUE THREAD

**Issue by rushereeeeee** [iptv-org/iptv#16692]
### Channel ID (required)

FXEast.us

### Channel Name

FX East

### Stream URL (required)

http://fl2.moveonjoy.com/FX/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
**Copyrighted stream.**
