### ISSUE TITLE
Add: Freeform East (USA)

### ISSUE THREAD

**Issue by rushereeeeee** [iptv-org/iptv#16693]
### Channel ID (required)

Freeform.us

### Channel Name

Freeform East

### Stream URL (required)

http://fl2.moveonjoy.com/FREE_FORM/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
**Copyrighted stream.**

**Comment by jnjustice** [comment]
Can anyone clarify why this stream was not added but others with from moveonjoy have been and are still listed? Just wondering what makes Free Form special...

**Comment by rushereeeeee** [comment]
some idiot making some drama :/

**Comment by azgaresncf** [comment]
> Can anyone clarify why this stream was not added but others with from moveonjoy have been and are still listed? Just wondering what makes Free Form special...

It was 4 months ago. I've kinda' change my point of view about these "copyrighted streams" but I just forgot to add it.

**Comment by rushereeeeee** [comment]
mhm ok

**Comment by daeongithub** [comment]
Anyone got a new link? This one just got blocked.

**Comment by daeongithub** [comment]
NEW LINK FOR FREEFORM https://tvpass.org/live/FreeformEast/hd

**Comment by myanalogdiary** [comment]
The link https://fl3.moveonjoy.com/FREE_FORM/index.m3u8 streams CBN channel and not FreeForm!
I need an .m3u8 solution for a Samsung Tizen TV.

**Comment by daeongithub** [comment]
> The link https://fl3.moveonjoy.com/FREE_FORM/index.m3u8 streams CBN channel and not FreeForm! I need an .m3u8 solution for a Samsung Tizen TV.

Just use the link I posted
