### ISSUE TITLE
Add: NINJA [RU]

### ISSUE THREAD

**Issue by TaurerMedia** [iptv-org/iptv#16704]
### Channel ID (required)

ninja.ru

### Channel Name

NINJA

### Stream URL (required)

https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/3.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
**Copyrighted stream.**
