### ISSUE TITLE
Animax asia or japan or with subs

### ISSUE THREAD

**Issue by Rahinebezzy** [iptv-org/iptv#1670]
IF anyone can help im looking for animax iptv link of any of the following:

ANIMAX ASIA/Animax japan/animax with subs/

all or any will help

**Comment by freearhey** [comment]
Done.
https://github.com/iptv-org/iptv/blob/c321151ad2cfe3b5d771e9e5b673d48015fea01a/channels/jp.m3u#L30-L35

**Comment by Petirking** [comment]
How to use this
