### ISSUE TITLE
Add: Groovezzo

### ISSUE THREAD

**Issue by TaurerMedia** [iptv-org/iptv#16702]
### Channel ID (required)

groovezzo.ru

### Channel Name

Groovezzo

### Stream URL (required)

https://nl1.live-stream.plus.taurer.org:443/pbuPAuthGp/MDTTv32fbk/7.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Xtream url

**Comment by ProPontifex** [comment]
Link dead....geo-blocked?

**Comment by Dum4G** [comment]
@Alstruit this looks very sketchy, I temporarily reopen those case in case miracles happen and this indeed official account

**Comment by R4IN2007** [comment]
https://github.com/TaurerMedia/TaurerPlus/blob/main/Master-M3U8/taurer-master.m3u8 / https://github.com/TaurerMedia/TaurerPlus/blob/main/Master-M3U8/master.m3u8. Link changed and the new one is here. https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/27.m3u8

**Comment by ProPontifex** [comment]
Just submitted database entry #12331
