### ISSUE TITLE
Add: KidsPlanet [RU]

### ISSUE THREAD

**Issue by TaurerMedia** [iptv-org/iptv#16707]
### Channel ID (required)

kidsplanet.ru

### Channel Name

KidsPlanet

### Stream URL (required)

https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/4.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
**Copyrighted stream.**
