### ISSUE TITLE
Add: RRTV Europe [RU]

### ISSUE THREAD

**Issue by TaurerMedia** [iptv-org/iptv#16705]
### Channel ID (required)

rrtv.ru

### Channel Name

RRTV Europe

### Stream URL (required)

https://nl1.live-stream.plus.taurer.org:443/pbuPAuthGp/MDTTv32fbk/6.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
**Copyrighted stream.**
