### ISSUE TITLE
Add: World-1 [RU]

### ISSUE THREAD

**Issue by TaurerMedia** [iptv-org/iptv#16706]
### Channel ID (required)

world1.ru

### Channel Name

World-1

### Stream URL (required)

https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/7.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
**Copyrighted stream.**
