### ISSUE TITLE
Add: Quality HD [RU]

### ISSUE THREAD

**Issue by TaurerMedia** [iptv-org/iptv#16709]
### Channel ID (required)

qualityhd.ru

### Channel Name

Quality HD

### Stream URL (required)

https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/6.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
**Copyrighted stream.**

**Comment by ProPontifex** [comment]
What is this channel titled in Cyrillic?
