### ISSUE TITLE
Add: Криминал и Полиция (Criminal And Police) [RU]

### ISSUE THREAD

**Issue by TaurerMedia** [iptv-org/iptv#16703]
### Channel ID (required)

criminalpolice.ru

### Channel Name

Криминал и Полиция

### Stream URL (required)

https://nl1.live-stream.plus.taurer.org:443/pbuPAuthGp/MDTTv32fbk/5.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
**Copyrighted stream.**
