### ISSUE TITLE
Broken: Sony yay

### ISSUE THREAD

**Issue by kunani1** [iptv-org/iptv#16715]
### Broken Link

https://dai.google.com/linear/hls/event/GPY7RqOrSkmKJ8z1GbVNhg/master.m3u8

### What happened to the stream?

Other

### Notes (optional)

404. That’s an error.

That’s all we know.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by queazified** [comment]
That means the stream no longer exists
