### ISSUE TITLE
Add: KBS World to South Korea Playlist 

### ISSUE THREAD

**Issue by Kenotic** [iptv-org/iptv#16712]
### Channel ID (required)

KBSWorld.kr

### Channel Name

KBS World

### Stream URL (required)

https://kbsworld-ott.akamaized.net/hls/live/2002341/kbsworld/master.m3u8

### Quality

None

### Label

None

### Notes

I see this channel in the Korean Language playlist but not seem to be in the Country's one. Can it be in both?

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
720p
