### ISSUE TITLE
Add: HBO 2 East [USA]

### ISSUE THREAD

**Issue by Metroid2023** [iptv-org/iptv#16717]
### Channel ID (required)

HBO2East.us

### Channel Name

HBO 2 East [USA]

### Stream URL (required)

https://fl2.moveonjoy.com/HBO_2/index.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
**Copyrighted stream.**
