### ISSUE TITLE
Lebanon Channels

### ISSUE THREAD

**Issue by darkspook1** [iptv-org/iptv#1672]
would you please add the following channels:

Al Jadeed
http://localhd.tv:8081/north7/north7/2128

NBN TV
http://localhd.tv:8081/north7/north7/1874

**Comment by freearhey** [comment]
Feel free to add the channels yourself, just read this guide beforehand: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#add-channel

**Comment by darkspook1** [comment]
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Arabic" tvg-logo="https://i.imgur.com/qtQQJQc.png" group-title="General",Al Jadeed
http://localhd.tv:8081/north7/north7/2128

#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Arabic" tvg-logo="https://nbntv.me/wp-content/uploads/2018/07/nbnlogo-f.png" group-title="News",NBN
http://localhd.tv:8081/north7/north7/1874

you mean like this?
