### ISSUE TITLE
Pbtv

### ISSUE THREAD

**Issue by Ang3l-max** [iptv-org/iptv#16722]
### Channel ID (required)

PlayboyTV.us

### Channel Name

Play Boy tv

### Stream URL (required)

http://190.11.225.124:5000/live/playboy_hd/playlist.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
> Adult/XXX channels are no longer allowed on the repository, and that's not PlayboyTV.us, it's Playboy TV Latin America.

It is also like a copyrighted stream.

**Comment by BellezaEmporium** [comment]
Since January 30th, 2024, NSFW channels aren't allowed in our playlists. See https://github.com/iptv-org/iptv/issues/15723 for the explanation.

**Comment by tozfek** [comment]
please delete this issue as well as it comes up in github as one of the top results and still contains the adult stream
