### ISSUE TITLE
Add: PSJTV

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/iptv#16733]
### Channel ID (required)

PSJTV.id

### Channel Name

PSJTV

### Stream URL (required)

https://play.accolamedia.id/accola/psj.stream/playlist.m3u8

### Quality

1080p

### Label

None

### Notes

Ref #16561

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
It's saying it's already been added.

**Comment by BellezaEmporium** [comment]
https://github.com/iptv-org/iptv/blob/77ee532de7a83987f8681d1faa372197bf5dae02/streams/id.m3u#L162-L163

**Comment by ProPontifex** [comment]
Whoops. Sry Belleza
