### ISSUE TITLE
Add: WIPR-DT1 (Not Geoblocked)

### ISSUE THREAD

**Issue by ghost** [iptv-org/iptv#16734]
### Channel ID (required)

WIPRDT1.pr

### Channel Name

WIPR

### Stream URL (required)

https://cprdp.pr/hls/stream/index.m3u8?tkn=3130025789

### Quality

None

### Label

None

### Notes

Its not Geoblocked while I was doing research on this.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
It's been 3 days since WIPR were changing their streaming m3u8 link

**Comment by azgaresncf** [comment]
it is working 
![working](https://github.com/iptv-org/iptv/assets/50982832/ac59bf72-f080-45c1-be98-5642c39b4a9b)

**Comment by R4IN2007** [comment]
Works without the tkn in the back of the link.
https://cprdp.pr/hls/stream/index.m3u8
