### ISSUE TITLE
NBC universo east

### ISSUE THREAD

**Issue by Urfavoritrat** [iptv-org/iptv#16736]
### Channel ID (required)

NBCUniverso.us

### Channel Name

NBC universo east 

### Stream URL (required)

https://photocalltv.site/uf8q/la?ch=universo_east
When you click on the link you will have to click on international channels and then click on NBC and then click on Universo and that’s how you get the channel

**Comment by Urfavoritrat** [comment]
When you click the link go to International channels And click on NBC and then Universo and then that is how you get the channel

**Comment by R4IN2007** [comment]
Won't work. Already tried to get stream url and its drm to NBC Peacock. Photocall uses some sort of script I guess.
https://live-oneapp-prd.akamaized.net/Content/CMAF_OL1-CTR-4s/Live/channel(universo-east)/master.mpd

**Comment by Urfavoritrat** [comment]
Why do I have to download the link so I can use it

**Comment by Urfavoritrat** [comment]
Does this work Beacuse it wants me to download and I tryed to open Universo on my pc on photo call and it disappeared and when I clicked on the link it is making me download it

**Comment by R4IN2007** [comment]
> Does this work Beacuse it wants me to download and I tryed to open Universo on my pc on photo call and it disappeared and when I clicked on the link it is making me download it

Yes it works, like I said it's drm but try opening it up vlc because opening it in browser it will make you download it. Photocall redirects users back to the main page just not the stream it's a only time use only.

**Comment by Urfavoritrat** [comment]
So is it safe to download

**Comment by Urfavoritrat** [comment]
the universo channel works now it will 
dissapear for a little  bit and will come back
