### ISSUE TITLE
Add: 

### ISSUE THREAD

**Issue by mac-donal** [iptv-org/iptv#16735]
### Channel ID (required)

tig

### Channel Name

tv onli

### Stream URL (required)

https://testphp07.alwaysdata.net/.m3u8 

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by NotjaphyrbotTV** [comment]
All the information seems wrong. Can you fix it?
