### ISSUE TITLE
Telemundo international 

### ISSUE THREAD

**Issue by Urfavoritrat** [iptv-org/iptv#16737]
### Channel ID (required)

Telemundointernacional.us

### Channel Name

Telemundo international 

### Stream URL (required)

https://photocalltv.site/h3ct/l3?ch=telemundo

### Quality

None

### Label

None

### Notes

When you click on the link click on international channels then scroll down to Telemundo and then click on it and select international and if you were in the United States and you want to use it, you need VPN

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
https://nbculocallive.akamaized.net/hls/live/2037499/puertorico/stream1/master.m3u8
https://live-oneapp-prd.akamaized.net/Content/CMAF_OL1-CTR-4s/Live/channel(kvea)/master.mpd
https://live-oneapp-prd.akamaized.net/Content/CMAF_OL1-CTR-4s/Live/channel(WNJU)/master.mpd

**Comment by ProPontifex** [comment]
Just submitted
