### ISSUE TITLE
Broken: Music+

### ISSUE THREAD

**Issue by TestNintendo** [iptv-org/iptv#16744]
### Broken Link

https://hugh.cdn.rumble.cloud/live/4gf18j5s/slot-79/3fqc-ohua/chunklist_DVR.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

The channel has shut down on June 2nd, 2024.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Needs to be written in database.
