### ISSUE TITLE
Add: Markiza (SK)

### ISSUE THREAD

**Issue by Jakubicek222** [iptv-org/iptv#16741]
### Channel ID (required)

Markiza.sk

### Channel Name

Markíza (1080p)

### Stream URL (required)

http://88.212.7.10/live/test_markiza_25p/playlist.m3u8

### Quality

1080p

### Label

None

### Timeshift

0

### Notes

it working 5 years

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by AF-HAF-KARTOGRAF** [comment]
Markíza has like Markíza Klasik and Markíza Krimi m3u8 on cdnsk003.panaccess, but Dajto and Doma not: https://cdnsk003.panaccess.com/local/Markiza/index.m3u8

**Comment by jarkoacjak** [comment]
Nefunguje

**Comment by janicdajan-sk** [comment]
> Markíza has like Markíza Klasik and Markíza Krimi m3u8 on cdnsk003.panaccess, but Dajto and Doma not: https://cdnsk003.panaccess.com/local/Markiza/index.m3u8

do you have the adresses for klasik and krimi?
Thank you
