### ISSUE TITLE
Add: JOJ (SK)

### ISSUE THREAD

**Issue by Jakubicek222** [iptv-org/iptv#16742]
### Channel ID (required)

TVJOJ.sk

### Channel Name

JOJ (1080p)

### Stream URL (required)

https://live.cdn.joj.sk/live/andromeda/joj-1080.m3u8

### Quality

1080p

### Label

None

### Timeshift

0

### Notes

its official link from joj website

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Also some other JOJ Channels

Wau
https://live.cdn.joj.sk/live/andromeda/wau-1080.m3u8

Plus
https://live.cdn.joj.sk/live/andromeda/plus-1080.m3u8

Jojko
https://live.cdn.joj.sk/live/andromeda/jojko-1080.m3u8

Family
https://live.cdn.joj.sk/live/andromeda/family-1080.m3u8

Cinema
https://live.cdn.joj.sk/live/andromeda/cinema-1080.m3u8

**Comment by Jakubicek222** [comment]
Extras working bro
https://live.cdn.joj.sk/live/andromeda/cs_history-1080.m3u8
https://live.cdn.joj.sk/live/andromeda/cs_film-1080.m3u8
https://live.cdn.joj.sk/live/andromeda/cs_mystery-1080.m3u8

**Comment by azgaresncf** [comment]
thanks guys

**Comment by jarkoacjak** [comment]
Joj Šport 2 https://live.cdn.joj.sk/live/andromeda/joj_sport2-1080.m3u8
