### ISSUE TITLE
Broken: Canal 5

### ISSUE THREAD

**Issue by luisenick** [iptv-org/iptv#16743]
### Broken Link

«https://channel05.akamaized.net/hls/live/2033783/event01/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

The channel is in the country México, the general list https://iptv-org.github.io/iptv/countries/mx.m3u

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
and this stream isn't working as well:
https://linear-351.frequency.stream/mt/studio/351/hls/master/playlist.m3u8

**Comment by R4IN2007** [comment]
Link changed I guess but other channels coming from izzi tv MX works like Foro, Las Estrellas, Nueve, N+ (Nmas)

**Comment by luisenick** [comment]
and does anyone know if there is a solution or if the content will no longer be able to be played?

**Comment by R4IN2007** [comment]
La canal de estrellas todavía si funciona. No más sirve con dirección de ip [México] y no tan bien sirve con un vpn.
Nada sirve para Canal 5 MX
https://channel01-onlymex.akamaized.net/hls/live/2022749/event01/index.m3u8
![Screenshot_20240918_223356_Chrome](https://github.com/user-attachments/assets/65f539d8-f8de-4827-a2ec-6f4145c6538c)

**Comment by R4IN2007** [comment]
Hay lista de reproducción de Astras que contiene el canal, pero no se en que cuáles.
