### ISSUE TITLE
Edit: TVExitos.do

### ISSUE THREAD

**Issue by grinfelds** [iptv-org/iptv#16746]
### Stream URL (required)

https://streaming.grupomediosdelnorte.com:19360/tvexitos/tvexitos.m3u8

### Channel ID

TVExitos.do

### Channel Name

TVExitos

### Quality

720p

### Label

None

### Notes

new logo link https://grupomediosdelnorte.com/iptv/tvexitos.png

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Is the referrer necessary ? I've seen an indication of one on Ecovision, though I've managed to load the stream without it.

**Comment by grinfelds** [comment]
Sorry, I didn't understand very well.
I use an online translator to read and write to him.

Streaming with the provider streamgato.us were disincorporated and we
currently use our own streaming server
streaming.grupomediosdelnorte.com

On our website https://grupomediosdelnorte.com/canales/ you can see
the channels that belong to us.
Thank you so much.
