### ISSUE TITLE
Add: AT-X (jp, 720p)

### ISSUE THREAD

**Issue by olstern01** [iptv-org/iptv#16751]
### Channel ID (required)

ATX.jp

### Channel Name

AT-X

### Stream URL (required)

https://neetball.net/live/neet3.m3u8

### Quality

720p

### Label

None

### Notes

It still works. If it suddenly doesn't work, please don't be hasty to remove it, try waiting for a day or two and it will work again. Here is the evidence on VLC. 

![Screenshot 2024-06-13 060645](https://github.com/iptv-org/iptv/assets/47495790/d34c6826-c116-416c-9363-a32ff582c27d)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Hmm somewhat problematic stream. Whenever added, it will be suspciously be broken.

**Comment by olstern01** [comment]
Maybe when that happens, it's because there's something wrong on their side. I don't think it's because it was added to the playlist. Some other channels are like that too, like Indonesian channels like Kompas TV and Metro TV. Sometimes works, sometimes doesn't. In the end, what matters is that the stream still works right? 
Because it's redundant to re-add a still working channel again and again, let's wait for longer this time, like maybe a month or two months. If at that time the stream is still broken, then maybe the stream is permanently broken and we can remove it.
