### ISSUE TITLE
Add: Cartoon Network Russia

### ISSUE THREAD

**Issue by seregafullman** [iptv-org/iptv#16754]
### Channel ID (required)

CartoonNetwork.ru

### Channel Name

Cartoon Network Russia

### Stream URL (required)

http://stream01.vnet.am/Kinosemya/mono.m3u8

### Quality

576p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ProPontifex** [comment]
Just added request
