### ISSUE TITLE
Add: Nickelodeon CIS

### ISSUE THREAD

**Issue by seregafullman** [iptv-org/iptv#16755]
### Channel ID (required)

NickelodeonCIS.ru

### Channel Name

Nickelodeon CIS

### Stream URL (required)

https://bkm.beetv.kz/btv/live/hls/000000499.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Irylek** [comment]
works.

**Comment by Dum4G** [comment]
Please confirm again @seregafullman @Irylek

**Comment by Irylek** [comment]
still works. i confirm

**Comment by Irylek** [comment]
this is nickelodeon global in hd quality with audio russia

**Comment by Irylek** [comment]
also, it has a 3 hour catchup

**Comment by Dum4G** [comment]
Lol, geo-blocked in Russia, works in Poland

**Comment by BellezaEmporium** [comment]
404 Not Found. Tested both in France & Poland.

**Comment by kaikyoofers** [comment]
404 in Brazil

**Comment by Dum4G** [comment]
Link is dead as of now
