### ISSUE TITLE
Add: Nick Jr. (Russia)

### ISSUE THREAD

**Issue by seregafullman** [iptv-org/iptv#16756]
### Channel ID (required)

NickJr.ru

### Channel Name

Nick Jr. (Russia)

### Stream URL (required)

https://bkm.beetv.kz/btv/live/hls/000000449.m3u8

### Quality

576p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by mavijavi5124** [comment]
Stream not working

**Comment by seregafullman** [comment]
> Stream not working

![image](https://github.com/iptv-org/iptv/assets/140471115/0efb01f4-868c-4c20-bbcd-5409c303e61e)

**Comment by mavijavi5124** [comment]
> Author

it says your input cant be working for me

**Comment by mavijavi5124** [comment]
![YOUR INPUT](https://github.com/iptv-org/iptv/assets/166801153/1a48954f-1ec6-4f63-95bf-4a65d3ed704d)

**Comment by seregafullman** [comment]
> ![YOUR INPUT](https://private-user-images.githubusercontent.com/166801153/339204628-1a48954f-1ec6-4f63-95bf-4a65d3ed704d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTEyNjAsIm5iZiI6MTcxODI1MDk2MCwicGF0aCI6Ii8xNjY4MDExNTMvMzM5MjA0NjI4LTFhNDg5NTRmLTFlYzYtNGY2My05NWJmLTRhNjVkM2VkNzA0ZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMzU2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGUzYTkxN2I1MmVlNDYyZGM3MTgxNWJkMjliZjk2ZWI0YTNmNWYzZDUwMzEzODFlOWRkOWU0YWFkY2FlMDU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fHxS9vrJQ-p-gZkbjIMAdjXJA4vuNmGfzlzgM2CU6Co)

I'll look for a new stream

**Comment by mavijavi5124** [comment]
Alright

**Comment by seregafullman** [comment]
> Alright

check this https://a5.pokaz.me/qxOGx2kPSxKPL1sU9JA_ug/210/1718269072/index.m3u8

**Comment by mavijavi5124** [comment]
Nope still not working Failed to start playback in PotPlayer

**Comment by seregafullman** [comment]
> Нет, по-прежнему не работает Не удалось начать воспроизведение в PotPlayer

check now https://bkm.beetv.kz/btv/live/hls/000000449.m3u8

**Comment by mavijavi5124** [comment]
> Ref

Stream Works

**Comment by ProPontifex** [comment]
Just submitted

**Comment by Dum4G** [comment]
404 for me
