### ISSUE TITLE
Add: Nicktoons CIS

### ISSUE THREAD

**Issue by seregafullman** [iptv-org/iptv#16757]
### Channel ID (required)

NicktoonsCIS.ru

### Channel Name

Nicktoons CIS

### Stream URL (required)

https://stream01.vnet.am/Boomerang/mono.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
https://github.com/iptv-org/iptv/blob/1a5284199cba2ee3dd1f8e4b614fea30fb2ac674/streams/am_vnet.m3u#L14-L15
