### ISSUE TITLE
Broken: Cartoon Network Russia

### ISSUE THREAD

**Issue by seregafullman** [iptv-org/iptv#16753]
### Broken Link

http://bkm.beetv.kz/btv/live/hls/000000015.m3u8 

### New Link https://stream01.vnet.am/Kinosemya/tracks-v1a1/mono.m3u8

M3u8 File https://mega.nz/file/d7RHHAZJ#qV2WyG7YMIhw48NKnIIdL08v-oN2X5IIE_xcjcFmvjc
### New Link 2 https://ge.streamsport.net:8080/hls/cn/chunks.m3u8?nimblesessionid=635109&wmsAuthSign=c2VydmVyX3RpbWU9Ni8xMy8yMDI0IDM6Mzk6MjIgQU0maGFzaF92YWx1ZT0xeXU1dFo2U3RLbTdERFpUUzNqbnR3PT0mdmFsaWRtaW51dGVzPTYwJmlkPSZjaGVja2lwPXRydWU=
M3u8 File https://mega.nz/file/0i5SxTgB#MasgB-57rMT6oVDIxNHJy_Qs0SNyN62qXQsZR0neBiU
### New Link 3 
https://ser1.musical.uz/cartonnet_web/tracks-v1a1/mono.m3u8?remote=45.142.215.123&token=0bf1b73b0fd35d4aff78141e8a8372d42a5f059c-e168801a7439f130e7b4599bc58d19e0-1718260632-1718249832

M3u8 File https://mega.nz/file/QjAmlDaA#DekE5cam1fNWcTAQgY4oDoVGNNllTJV7iNSvYqPb9hI
### What happened to the stream?

Not loading

### Notes (optional)

the stream is not working the site is not working HTTP ERROR 404 I've been trying to log in since yesterday and it doesn't work

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Broken link works
![Screenshot_20240612_204953_Chrome](https://github.com/iptv-org/iptv/assets/83226646/8e4b9ea4-7236-4f2e-8dfe-3d6a9db2bef2)

New Link 2 doesn't work

**Comment by seregafullman** [comment]
> Broken link works ![Screenshot_20240612_204953_Chrome](https://private-user-images.githubusercontent.com/83226646/339180804-8e4b9ea4-7236-4f2e-8dfe-3d6a9db2bef2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDQxMDcsIm5iZiI6MTcxODI0MzgwNywicGF0aCI6Ii84MzIyNjY0Ni8zMzkxODA4MDQtOGU0YjllYTQtNzIzNi00ZjJlLThkZmUtM2Q2YTlkYjJiZWYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAxNTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNzk4YTdmYjI5NWIyMTNlMTVlNDI2NDRkNDFiYWMxMjI5ZGJiZGI2ZmRiNDllYTFhMTU4N2U1ZWNmNDhjMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K9qGsWybbwKHijs5yzI7sTnumRJhtrIzZ-jyDJjp-ig)
> 
> New Link 2 doesn't work

I do not know from Russia the link does not work

**Comment by seregafullman** [comment]
> Broken link works ![Screenshot_20240612_204953_Chrome](https://private-user-images.githubusercontent.com/83226646/339180804-8e4b9ea4-7236-4f2e-8dfe-3d6a9db2bef2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDQxMDcsIm5iZiI6MTcxODI0MzgwNywicGF0aCI6Ii84MzIyNjY0Ni8zMzkxODA4MDQtOGU0YjllYTQtNzIzNi00ZjJlLThkZmUtM2Q2YTlkYjJiZWYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAxNTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNzk4YTdmYjI5NWIyMTNlMTVlNDI2NDRkNDFiYWMxMjI5ZGJiZGI2ZmRiNDllYTFhMTU4N2U1ZWNmNDhjMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K9qGsWybbwKHijs5yzI7sTnumRJhtrIzZ-jyDJjp-ig)
> 
> New Link 2 doesn't work

![image](https://github.com/iptv-org/iptv/assets/140471115/c2c66c21-3309-44b8-9d91-f5d65808a187)

**Comment by seregafullman** [comment]
> Broken link works ![Screenshot_20240612_204953_Chrome](https://private-user-images.githubusercontent.com/83226646/339180804-8e4b9ea4-7236-4f2e-8dfe-3d6a9db2bef2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDQyMDEsIm5iZiI6MTcxODI0MzkwMSwicGF0aCI6Ii84MzIyNjY0Ni8zMzkxODA4MDQtOGU0YjllYTQtNzIzNi00ZjJlLThkZmUtM2Q2YTlkYjJiZWYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAxNTgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYTFkZDY1ODg2MzkyZTExNmVkOTA2NzllODJmZTcwZTYwZWQzNTRjNzhkMzU1ZmNkMjNmMmRkNTVmMGNiYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0xKoP2kcmxAXvbjqNLX0kfdYY7wnm7b3H72qLQP69lY)
> 
> New Link 2 doesn't work



> Broken link works ![Screenshot_20240612_204953_Chrome](https://private-user-images.githubusercontent.com/83226646/339180804-8e4b9ea4-7236-4f2e-8dfe-3d6a9db2bef2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDQyMDEsIm5iZiI6MTcxODI0MzkwMSwicGF0aCI6Ii84MzIyNjY0Ni8zMzkxODA4MDQtOGU0YjllYTQtNzIzNi00ZjJlLThkZmUtM2Q2YTlkYjJiZWYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAxNTgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYTFkZDY1ODg2MzkyZTExNmVkOTA2NzllODJmZTcwZTYwZWQzNTRjNzhkMzU1ZmNkMjNmMmRkNTVmMGNiYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0xKoP2kcmxAXvbjqNLX0kfdYY7wnm7b3H72qLQP69lY)
> 
> New Link 2 doesn't work

The VLS player also does not launch http://bkm.beetv.kz/btv/live/hls/000000015.m3u8

**Comment by seregafullman** [comment]
> Broken link works ![Screenshot_20240612_204953_Chrome](https://private-user-images.githubusercontent.com/83226646/339180804-8e4b9ea4-7236-4f2e-8dfe-3d6a9db2bef2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDQ5MTYsIm5iZiI6MTcxODI0NDYxNiwicGF0aCI6Ii84MzIyNjY0Ni8zMzkxODA4MDQtOGU0YjllYTQtNzIzNi00ZjJlLThkZmUtM2Q2YTlkYjJiZWYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAyMTAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YWY4NmMzMjYwZjBmYWYxMjg5ZWE5MDQyYzNjZjczZDEyMDFjN2UxZjJmYmQxNGYyOWIxODBkMmI5NjhiMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v_40yR3am3GzpzgWXrLbpTbAwvfUcEk8lmNjutvIZkI)
> 
> New Link 2 doesn't work

video of the work https://mega.nz/file/F7YUjBwD#khSTfpmgkCk1wijmoyL-3y9gVHfRgLR-ExtPOHAKKXM

**Comment by seregafullman** [comment]
> That's strange it's works in the US but not in Russia? Maybe this link is Geo-blocked, this is why it works for you https://ge.streamsport.net:8080/hls/cn/chunks.m3u8?nimblesessionid=635109&wmsAuthSign=c2VydmVyX3RpbWU9Ni8xMy8yMDI0IDM6Mzk6MjIgQU0maGFzaF92YWx1ZT0xeXU1dFo2U3RLbTdERFpUUzNqbnR3PT0mdmFsaWRtaW51dGVzPTYwJmlkPSZjaGVja2lwPXRydWU=
> 
> > > Broken link works ![Screenshot_20240612_204953_Chrome](https://private-user-images.githubusercontent.com/83226646/339180804-8e4b9ea4-7236-4f2e-8dfe-3d6a9db2bef2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDQ5MTYsIm5iZiI6MTcxODI0NDYxNiwicGF0aCI6Ii84MzIyNjY0Ni8zMzkxODA4MDQtOGU0YjllYTQtNzIzNi00ZjJlLThkZmUtM2Q2YTlkYjJiZWYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAyMTAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YWY4NmMzMjYwZjBmYWYxMjg5ZWE5MDQyYzNjZjczZDEyMDFjN2UxZjJmYmQxNGYyOWIxODBkMmI5NjhiMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v_40yR3am3GzpzgWXrLbpTbAwvfUcEk8lmNjutvIZkI)
> > > New Link 2 doesn't work
> > 
> > 
> > video of the work https://mega.nz/file/F7YUjBwD#khSTfpmgkCk1wijmoyL-3y9gVHfRgLR-ExtPOHAKKXM

The link included HTTP A But not HTTPS

**Comment by seregafullman** [comment]
> > That's strange it's works in the US but not in Russia? Maybe this link is Geo-blocked, this is why it works for you https://ge.streamsport.net:8080/hls/cn/chunks.m3u8?nimblesessionid=635109&wmsAuthSign=c2VydmVyX3RpbWU9Ni8xMy8yMDI0IDM6Mzk6MjIgQU0maGFzaF92YWx1ZT0xeXU1dFo2U3RLbTdERFpUUzNqbnR3PT0mdmFsaWRtaW51dGVzPTYwJmlkPSZjaGVja2lwPXRydWU=
> > > > Broken link works ![Screenshot_20240612_204953_Chrome](https://private-user-images.githubusercontent.com/83226646/339180804-8e4b9ea4-7236-4f2e-8dfe-3d6a9db2bef2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDQ5MTYsIm5iZiI6MTcxODI0NDYxNiwicGF0aCI6Ii84MzIyNjY0Ni8zMzkxODA4MDQtOGU0YjllYTQtNzIzNi00ZjJlLThkZmUtM2Q2YTlkYjJiZWYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAyMTAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YWY4NmMzMjYwZjBmYWYxMjg5ZWE5MDQyYzNjZjczZDEyMDFjN2UxZjJmYmQxNGYyOWIxODBkMmI5NjhiMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v_40yR3am3GzpzgWXrLbpTbAwvfUcEk8lmNjutvIZkI)
> > > > New Link 2 doesn't work
> > > 
> > > 
> > > video of the work https://mega.nz/file/F7YUjBwD#khSTfpmgkCk1wijmoyL-3y9gVHfRgLR-ExtPOHAKKXM
> 
> The link included HTTP A But not HTTPS

Http link dont work https link work
