### ISSUE TITLE
Add: Cartoon Network (Russia)

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/iptv#16766]
### Channel ID (required)

CartoonNetwork.ru

### Channel Name

Cartoon Network (Russia)

### Stream URL (required)

http://stream01.vnet.am/Kinosemya/mono.m3u8

### Quality

576p

### Label

None

### Notes

From #16754

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Dup of #16754

**Comment by M3UDay** [comment]
No sound
