### ISSUE TITLE
Broken: Realitatea Star

### ISSUE THREAD

**Issue by AlbertROTV** [iptv-org/iptv#16761]
### Broken Link

https://streamx.realitatea.net/realitatea/star_md/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

New stream link: https://stream.realitatea.net/realitatea/star_fq/playlist.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by queazified** [comment]
not sure if that link is working, if that link isn't, here is a hd version:
https://stream.realitatea.net/realitatea/star_md/playlist.m3u8
