### ISSUE TITLE
Broken: Boomerang Thailand

### ISSUE THREAD

**Issue by mavijavi5124** [iptv-org/iptv#16768]
### Broken Link

https://cdn6.goprimetime.info/feed/eI5rczhSQpWBcgOtqRLNWw/chboomberang/index.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by DenysMath** [comment]
This stream is not broken.
![Screenshot_2024-06-14-13-34-07-599_com android chrome](https://github.com/iptv-org/iptv/assets/150218575/62afcbf6-489d-4483-8d6b-b58bcc983738)

**Comment by mavijavi5124** [comment]
For some reason it says "Your input cant be opened

**Comment by mavijavi5124** [comment]
i tested with Thailand IP As well

**Comment by mavijavi5124** [comment]
update: works

**Comment by Mavijak** [comment]
Update: works on mobile
