### ISSUE TITLE
Add: Sky News Weather

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/iptv#16777]
### Channel ID (required)

SkyNewsWeather.uk

### Channel Name

Sky News Weather

### Stream URL (required)

http://late-bird-1612.livetube.eu.org/SkyWeather/index.m3u8?token=9TEQXsK2lKdyI3

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by azgaresncf** [comment]
Already added.

**Comment by Dum4G** [comment]
https://github.com/iptv-org/iptv/blob/90726670435ade217893a9bfa4b56bf4755d51c4/streams/uk.m3u#L173-174

**Comment by TKList** [comment]
No https?

**Comment by Dum4G** [comment]
Works without https

**Comment by TKList** [comment]
Not when auto upgrade connections to HTTPS
