### ISSUE TITLE
Add: AfroSport Nigeria

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/iptv#16779]
### Channel ID (required)

AfroSportNigeria.ng

### Channel Name

AfroSport Nigeria

### Stream URL (required)

https://newproxy3.vidivu.tv/vidivu_afrosport/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Works without the token
https://newproxy3.vidivu.tv/vidivu_afrosport/index.m3u8 (?token=null)
![Screenshot_20240614_214821_Chrome](https://github.com/iptv-org/iptv/assets/83226646/dba596d4-2610-478a-834d-a7f10fd7277b)

**Comment by ProPontifex** [comment]
Edited; thanks
