### ISSUE TITLE
Add: News Malayalam 24x7

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/iptv#16776]
### Channel ID (required)

NewsMalayalam24x7.in

### Channel Name

News Malayalam 24x7

### Stream URL (required)

https://ythls.armelin.one/channel/UCXp6JTdq7-WwBK09S7SzmxQ.m3u8

### Quality

None

### Label

None

### Notes

Should take care of #16650

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Incorrect label:
"News Malayalam"

**Comment by Dum4G** [comment]
It's news malayalam 24x7, very recent channel, not in our db yet
![image](https://github.com/iptv-org/iptv/assets/5430116/aa48c718-2994-4ba3-86a7-abac77ed0f1b)
