### ISSUE TITLE
Add: Panc TV Peru

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/iptv#16785]
### Channel ID (required)

PancTVPeru.pe

### Channel Name

Panc TV Peru

### Stream URL (required)

https://panel.host-live.com/80010/80010/chunklist_w1244945356.m3u8

### Quality

1080p

### Label

None

### Notes

Trying to complete #16386

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by panctvtucuman** [comment]
Hola le pasamos la nueva URL de (PANC TV PERU)

https://tv.streamcasthd.com:3260/live/pancperulive.m3u8

Desde ya muchas gracias
