### ISSUE TITLE
Edit: Freeform East

### ISSUE THREAD

**Issue by rushereeeeee** [iptv-org/iptv#16783]
### Stream URL (required)

http://fl2.moveonjoy.com/FREE_FORM/index.m3u8

### Channel ID

Freeform.us

### Channel Name

Freeform East 

### Quality

None

### Label

None

### Notes

yall made a mistake in the US playlist.

its currently set to:(http://fl2.moveonjoy.com/CARTOON_NETWORK/index.m3u8) 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
They mistaken Cartoon Network as Freeform

**Comment by rushereeeeee** [comment]
yeah…

**Comment by myanalogdiary** [comment]
The link https://fl3.moveonjoy.com/FREE_FORM/index.m3u8 streams CBN channel and not FreeForm!
