### ISSUE TITLE
Update HK Playlist

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#16788]
Update Hong Kong Playlist
Add the new found links to the playlist
Here's a list of found HK Channels
https://pastebin.ai/ugvmm1dkxh
*Couldn't open a pull request 

EPG-ID's:https://iptv-org.github.io/?q=country:HK

**Comment by kaikyoofers** [comment]
@R4IN2007 redirects to https://error.zapi.eu.org/m3u8/index.m3u8 in Brazil "The program source does not exist or has expired"

**Comment by R4IN2007** [comment]
Channels stopped working
