### ISSUE TITLE
Add: All Polish Channels (I guess xD)

### ISSUE THREAD

**Issue by Irylek** [iptv-org/iptv#16782]
### Channel ID (required)

all-channels.pl

### Stream URL (required)

http://185.236.229.62:9981/playlist.m3u8

### Quality

1080p

### Label

None

### Timeshift

0

### Notes

Was messing with the Disney Junior stream link today. And, i found the whole list lol. ez (i counted 229 channels on this list.)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Well there's this one but that will work too. 
https://cdn-notpub-london.lolokoko.tv/disneyjunior.stream/chunks.m3u8

http://185.236.229.62:9981/play/a06n (Astra)

**Comment by Irylek** [comment]
@R4IN2007 actually, i converted your last link (http://185.236.229.62:9981/play/a06n) to this "http://185.236.229.62:9981/playlist.m3u8" and it works. so now, we have all the channels.

**Comment by R4IN2007** [comment]
That's good a Astra with 229 Polish Channels

> @R4IN2007 actually, i converted your last link (http://185.236.229.62:9981/play/a06n) to this "http://185.236.229.62:9981/playlist.m3u8" and it works. so now, we have all the channels.

**Comment by Dum4G** [comment]
This entire playlist will likely die if we make it publically indexed. Use it till it lasts

**Comment by campones** [comment]
good job

**Comment by wkurw** [comment]
Works perfect.

**Comment by duzers** [comment]
and not work.

**Comment by hacus1** [comment]
Will you share this link in m3u format?

**Comment by danio991** [comment]
> @R4IN2007 actually, i converted your last link (http://185.236.229.62:9981/play/a06n) to this "http://185.236.229.62:9981/playlist.m3u8" and it works. so now, we have all the channels.

When playing channels on iptv,iptv pro,or televizo it takes time to load or buffering should not be so what is wrong with the links and m3u list at you also is like this

**Comment by danio991** [comment]
When playing channels on iptv,iptv pro,or televizo it takes time to load or buffering should not be so what is wrong with the links and m3u list at you also is like this

**Comment by hacus1** [comment]
> When playing channels on iptv,iptv pro,or televizo it takes time to load or buffering should not be so what is wrong with the links and m3u list at you also is like this

the only thing is that m3u8 doesn't work at all in the applications you mentioned - which ones are the best to watch on Spart TV to make it smooth?
Or what other solution do you recommend?
On one IPTV app it works so that it cuts non-stop. Can you give me some advice? Can we write in Polish?

**Comment by wkurw** [comment]
> > When playing channels on iptv,iptv pro,or televizo it takes time to load or buffering should not be so what is wrong with the links and m3u list at you also is like this
> 
> the only thing is that m3u8 doesn't work at all in the applications you mentioned - which ones are the best to watch on Spart TV to make it smooth?
> Or what other solution do you recommend?
> On one IPTV app it works so that it cuts non-stop. Can you give me some advice? Can we write in Polish?

Ja do ogladania tv uzywam Kodi na xbox one. Mam zainstalowana wtyczke, ktora ma duze mozliwosci konfiguracji. Zwiekszylem nieco bufor i korzystalem z timeshift +1 minuta. Z minutowym opoznieniem ale dzialalo perfekt. Dwa dni temu jak wlaczylem kodi juz tak dobrze nie dzialala ta lista. Czesto po timeshifcie kanal nie idzie odpauzowac. Ale takie sa uroki darmowych list m3u. Lepsze sa Stalker portale, czyli symulowanie decodera iptv z adresem MAC ktory ma zaladowane juz kanaly z konkretnego serwera.

**Comment by danio991** [comment]
Też mam kodi,jak skonfigurować kodi dodać wtyczkę jakąś czy tylko dodać listę m3u8?Co oprócz kodi,apka splication na android tv box i android smartfon i tablet?Prócz ipvt pro ipvt lub telewizo co polecacie

I also have codes, how to configure codes and add a plugin or just add a list of m3u8? What besides Kodi,Apka Splication for Android TV Box and Android Smartphone and Tablet? In addition to IPvt Pro (IPvt) or TV (which you recommend)

**Comment by danio991** [comment]
MAM TV BOX X98H PRO PIXEL 3 AIRCREAN PIXEL.TABLET TO SAMSUNG GALAXY FE SM-X510 10,9 I SMARTFON SM-S911B

**Comment by Y713Y** [comment]
some channels are not working properly

**Comment by kokosekwindows** [comment]
nie działa nie polecam

**Comment by MP3FileSenderAndroidTV** [comment]
bro does it run on Kodi

**Comment by partiid** [comment]
> bro does it run on Kodi

It does run on Kodi but the channels don't work anyways

**Comment by lukec85** [comment]
None of these channels work. I am able to load the playlist on both IPTV Smarters Pro and Tivi but I get a playback error 403 everytime I try to load a channel. I would love to be able to watch polish TV here in the states 🙁

Is there another .m3u8 playlist? Where can I find more. Thank you

**Comment by Dawca-nereK** [comment]
Poproszę o uaktualnienie bo nic nie działa

**Comment by winc111** [comment]
Lista jest , epg jest lecz tv nie działa connection failed! Czy jest szansa na jakąś rekonstrukcję 🤔

**Comment by danio991** [comment]
Error loading channels: server connection error

Use M3U or XSPF playlist

Stream URL (required)

http://185.236.229.62:9981/playlist.m3u8
@R4IN2007 actually, i converted your last link (http://185.236.229.62:9981/play/a06n) to this "http://185.236.229.62:9981/playlist.m3u8" and it works. so now, we have all the channels.

What's going on why I can't open it
These links worked on both H96Max and H96Max players, but now they don't work, showing an error

**Comment by danio991** [comment]
> Jest taki, ale to też zadziała. https://cdn-notpub-london.lolokoko.tv/disneyjunior.stream/chunks.m3u8
> 
> [http://185.236.229.](http://185.236.229.62:9981/play/a06n)62:9981/play/a06n (Astra)

These links worked on both H96Max and H96Max players, but now they don't work, showing an error

**Comment by danio991** [comment]
Poproszę o aktualizacja adresu IP ipvt lub stream playlist polish m3u m3u8 bo nic nie dziala

Please update your IP IP address, ipvt or streamlist polish m3u m3u8 because nothing works

**Comment by danio991** [comment]
> Popros o uaktualnienie bo nic nie czyny

Link playlist stream nie działa proszę uaktualnić listę stream m3u8 m3u

**Comment by campones** [comment]
> > Please update as it does nothing
> 
> Stream playlist link is not working please update m3u8 m3u stream list

it's dead for over  a year, stop spamming

**Comment by danio991** [comment]
> Żaden z tych kanałów nie działa. Jestem w stanie załadować listę odtwarzania zarówno na IPTV Smarters Pro, jak i Tivi, ale za każdym razem, gdy próbuję załadować kanał, otrzymuję błąd odtwarzania 403. Chciałbym móc oglądać polską telewizję tutaj w stanach 🙁
> 
> Czy istnieje kolejna .m3u8 playlista? Gdzie znajdę więcej? Dziękuję

> None of these channels are working. I can load the playlist on both IPTV Smarters Pro and Tivi, but every time I try to load a channel, I get a 403 playback error. I’d love to be able to watch Polish TV here in the States 🙁
> 
> Is there another .m3u8 playlist? Where can I find more? Thank you

Request for a .m3u8 playlist on GitHub – IP address, list of IPs, m3u, m3u8 – as it’s giving a 403 error or the list is missing from the service

**Comment by kokosekwindows** [comment]
i would really reccommend updating this, none of the channels worked, we need something that works.

**Comment by winc111** [comment]
> i would really reccommend updating this, none of the channels worked, we need something that works.

It was working even at began of World Cup then stopped one day only few channels working still

**Comment by kokosekwindows** [comment]
> > i would really reccommend updating this, none of the channels worked, we need something that works.
> 
> It was working even at began of World Cup then stopped one day only few channels working still

but are there chances to update this?

**Comment by winc111** [comment]
I’m a user just like you, not an admin. Someone there makes those lists, but because it’s free, it almost always goes down eventually 🤷‍♂️. It’s fine when you're just testing apps to see if they work—it’s a simple m3u list, but in my experience, it’s never permanent. If you want to try a paid one, I can recommend a basic starter list. I used to have one for emergencies; it had about 122 channels and was paid monthly or quarterly.”

**Comment by kokosekwindows** [comment]
> I’m a user just like you, not an admin. Someone there makes those lists, but because it’s free, it almost always goes down eventually 🤷‍♂️. It’s fine when you're just testing apps to see if they work—it’s a simple m3u list, but in my experience, it’s never permanent. If you want to try a paid one, I can recommend a basic starter list. I used to have one for emergencies; it had about 122 channels and was paid monthly or quarterly.”

I areleady have 3339 channels with movies, but no Polsat 1.

**Comment by winc111** [comment]
Then you need to get another supplier, most likely concentrate on polish content not general .

I always shrink the list of so also it helps to app working flawlessly

**Comment by kokosekwindows** [comment]
> Then you need to get another supplier, most likely concentrate on polish content not general .
> 
> I always shrink the list of so also it helps to app working flawlessly

But its does work flawlessly theres nothing wrong with it.
