### ISSUE TITLE
Broken: TV Pública (TVP) (1080p) [Not 24/7]

### ISSUE THREAD

**Issue by trancer1994** [iptv-org/iptv#16791]
### Broken Link

https://cntlnk-main-edge-access.secure.footprint.net/entrypoint/c7_vivo01_dai_source-20001_all.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Hi,

TV Publica Argentina's stream is not working, and indeed when I try to launch it with Firefox it says it can't connect to the server, meaning the site it's hosted on is itself down. The stream URL doesn't work in VLC either.

New stream (you'll need to extract the m3u8 I believe): https://www.tvpublica.com.ar/vivo/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
https://cntlnk-main-edge-access.dlt.qwilted-cds.cqloud.com/entrypoint/c7_vivo01_dai_source-20001_all.m3u8
Same link but (access.secure.footprint.net) with (dlt.qwilted-cds.cqloud.com)
