### ISSUE TITLE
LOLOKOKO down again

### ISSUE THREAD

**Issue by Irylek** [iptv-org/iptv#16799]
### Broken Link

https://cdn-notpub-london.lolokoko.tv/13ulica.stream/chunks.m3u8

### What happened to the stream?

Shows looped video

### Notes (optional)

again there is this thief. you guys should NEVER trust lolokoko.
![Przechwytywanie](https://github.com/iptv-org/iptv/assets/98583165/86f838d0-b146-4d89-b03a-f151c15f161e)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Closing in favor of these issues.
Thanks.

**Comment by GuyInCanada** [comment]
Those were only up for as long as they were because the links weren't posted here.
They get posted here, and then a day or two later, they're dead.

**Comment by campones** [comment]
they also closed another one today, no idea if this was posted here.   not getting a video loop though, just a 403 forbidden

**Comment by mavijavi5124** [comment]
rip again

**Comment by ales04** [comment]
Does anyone know from what provider are these links?
