### ISSUE TITLE
Add: TNT East

### ISSUE THREAD

**Issue by Alstruit** [iptv-org/iptv#16798]
### Channel ID (required)

TNTEast.us

### Channel Name

TNT East

### Stream URL (required)

https://raw.githubusercontent.com/Alstruit/adaptive-streams/alstruit-10_23_us/streams/us/TNTEast.us.m3u8

### Quality

720p

### Label

Geo-blocked

### Notes

From #16666. Adaptive version

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Link already exists https://github.com/iptv-org/iptv/blob/ecffde6424edeed1f2c860296f7d045a55e9df0c/streams/us.m3u#L824-L825
