### ISSUE TITLE
Add: 

### ISSUE THREAD

**Issue by MrRorls12** [iptv-org/iptv#16793]
### Channel ID (required)

XilamTV.fr

### Channel Name

XilamTV

### Stream URL (required)

https://i.mjh.nz/SamsungTVPlus/FRBA3300018I9.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
https://xilam-animation-1-fr.samsung.wurl.tv/playlist.m3u8
