### ISSUE TITLE
Please let me know if you can add this channel!

### ISSUE THREAD

**Issue by jaketheb8** [iptv-org/iptv#16806]
### Channel ID (required)

IslandLuckTV.bs

### Channel Name

Island Luck TV

### Stream URL (required)

https://cdn-edge1.streamcomedia.com/abr_islandluck-ott/abr-islandluck-ott_streams/playlist.m3u8

### Quality

None

### Label

None

### Notes

Please let me know if you can add this channel, I have many recommendations to add!

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
You got very lucky, I've got the link

**Comment by jaketheb8** [comment]
> You got very lucky, I've got the link

Thank you bro! Do you think you can add it for me? I have a bunch of channels I wanna add, and how do you find that link for next time?

**Comment by Dum4G** [comment]
Well, this time it was easy because the link was right in the players code set as an argument. Pure luck to take it that easily. This channel is named Island Luck TV btw, will be available in Bahamas playlist

**Comment by jaketheb8** [comment]
> Well, this time it was easy because the link was right in the players code set as an argument. Pure luck to take it that easily. This channel is named Island Luck TV btw, will be available in Bahamas playlist

I appreciate your help guy thank you, this literally is my first day of doing this stuff so I have no clue what I'm doing
