### ISSUE TITLE
Broken: UniMasEast.us

### ISSUE THREAD

**Issue by LondonX** [iptv-org/iptv#16813]
### Broken Link

https://unidfp-nlds164.global.ssl.fastly.net/nlds/univisionnow/unimas_east2/as/live/unimas_east2_hd_pc.m3u8?t1=

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Missing Token! Those channels don't have a Token.
![Screenshot_20240618_150025_Chrome](https://github.com/iptv-org/iptv/assets/83226646/56bc0d58-da39-4373-ba3d-c732f6c05184)
https://unidfp-nlds164.global.ssl.fastly.net/nlds/univisionnow/unimas_east2/as/live/unimas_east2_hd_pc.m3u8?t1=test_token

**Comment by Dum4G** [comment]
> https://unidfp-nlds164.global.ssl.fastly.net/nlds/univisionnow/unimas_east2/as/live/unimas_east2_hd_pc.m3u8?t1=test_token

Please confirm if it still works 
![image](https://github.com/iptv-org/iptv/assets/5430116/d6aeb3a1-75e5-487e-a9b5-01edef3d5466)

**Comment by R4IN2007** [comment]
> > https://unidfp-nlds164.global.ssl.fastly.net/nlds/univisionnow/unimas_east2/as/live/unimas_east2_hd_pc.m3u8?t1=test_token
> 
> Please confirm if it still works @R4IN2007 ![image](https://private-user-images.githubusercontent.com/5430116/342888167-d6aeb3a1-75e5-487e-a9b5-01edef3d5466.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NDc3NTIsIm5iZiI6MTcxOTQ0NzQ1MiwicGF0aCI6Ii81NDMwMTE2LzM0Mjg4ODE2Ny1kNmFlYjNhMS03NWU1LTQ4N2UtYTliNS0wMWVkZWYzZDU0NjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMDAxNzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGM3ZDBhOGMyYTc3YjgyYTdhYmI1YjI2ZDc0ZmU4NmY5YTEyMjg0YzAxMDRiMWVjY2I5OGU4NGIzNmRiYTVmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1LwpMw3mlEokHt4_pDor3v3VJzs7vo3eIt3iVG76fDU)

It's Geo-blocked, Only works in the US
![Screenshot_20240626_191805_Chrome](https://github.com/iptv-org/iptv/assets/83226646/d30ca4b9-c2b4-4450-ad76-0f1eec284edf)

**Comment by R4IN2007** [comment]
I don't know if the other univision channels work by replacing "?t1" with "?t1=test_token"
