### ISSUE TITLE
Add: ALL TVP3 CHANNELS

### ISSUE THREAD

**Issue by Irylek** [iptv-org/iptv#16816]
### Channel ID (required)

TVP3.pl

### Stream URL (required)

https://cdndai.pl/tvp3warszawasd/index.m3u8 https://cdndai.pl/tvp3lublinsd/index.m3u8 https://cdndai.pl/tvp3bialystoksd/index.m3u8 https://cdndai.pl/tvp3bydgoszczsd/index.m3u8 https://cdndai.pl/tvp3gdansksd/index.m3u8 https://cdndai.pl/tvp3katowicesd/index.m3u8 https://cdndai.pl/tvp3kielcesd/index.m3u8 https://cdndai.pl/tvp3krakowsd/index.m3u8 https://cdndai.pl/tvp3lodzsd/index.m3u8 https://cdndai.pl/tvp3olsztynsd/index.m3u8 https://cdndai.pl/tvp3opolesd/index.m3u8 https://cdndai.pl/tvp3poznansd/index.m3u8 https://cdndai.pl/tvp3rzeszowsd/index.m3u8 https://cdndai.pl/tvp3szczecinsd/index.m3u8 https://cdndai.pl/tvp3wroclawsd/index.m3u8

### Quality

576p

### Label

None

### Notes

taken from https://irylek.github.io/tv

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
thank you, one more channel added (TVP 3 Gorzów Wielkopolski)
