### ISSUE TITLE
Channels search website

### ISSUE THREAD

**Issue by ahmadissa** [iptv-org/iptv#1681]
I have put together a simple website to search TV channels by name, country and category 
(based on https://iptv-org.github.io/iptv/channels.json)

https://iptvchannels.web.app/

Please feel free to add it to your Readme page or send me any suggestions

**Comment by freearhey** [comment]
@ahmadissa we have a separate repository for this, you can add your link there: https://github.com/iptv-org/awesome-iptv

**Comment by kisiel999** [comment]
Add players on a website @ahmadissa

**Comment by ahmadissa** [comment]
@freearhey  Thanks will do that
@kisiel999 good idea, I will implement this asap
