### ISSUE TITLE
Add: La Que Buena Atlanta

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#16829]
### Channel ID (required)

LaQueBuenaAtlanta.us

### Channel Name

La Que Buena Atlanta

### Stream URL (required)

https://streamyes.alsolnet.com/quebuenaatlanta/live/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ProPontifex** [comment]
Just submitted a database request #12381
