### ISSUE TITLE
Broken: CN Asia

### ISSUE THREAD

**Issue by mavijavi5124** [iptv-org/iptv#16825]
### Broken Link

https://cdn1.skygo.mn/live/disk1/Cartoon_Network/HLS-FTA/Cartoon_Network.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Cartoonito Asia also seems to be broken
t

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by AircheckerArchives** [comment]
link still works.
