### ISSUE TITLE
Add: Disney Channel Latin America

### ISSUE THREAD

**Issue by mavijavi5124** [iptv-org/iptv#16826]
### Channel ID (required)

DisneyChannelLatinAmerica.ar

### Channel Name

Disney Channel Latin America

### Stream URL (required)

http://168.181.122.234:8000/play/a038/index.m3u8

### Quality

480p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ProPontifex** [comment]
Just submitted a database request to move this one along #12368
