### ISSUE TITLE
Add some french channel

### ISSUE THREAD

**Issue by iptv-test** [iptv-org/iptv#1682]
Hello every one hope you are doing well 
So I have some 3 french channels to add and i'm here to ask you to test them and see if they are working for you too,  if so , can you add them if you don't mind

w9 :  http://reds.ppdn.tn/iptv/ch220?code=460134681098246&key=27998
tf1 :  http://reds.ppdn.tn/iptv/ch207?code=460134681098246&key=52033
m6 :  http://reds.ppdn.tn/iptv/ch208?code=460134681098246&key=57261
Thanks and have a nice day/night

**Comment by freearhey** [comment]
These links don't work for me. Tested in VLC and Elmedia Video Player.

**Comment by iptv-test** [comment]
i tested them on vlc they work well for me
i'm gonna re check

**Comment by iptv-test** [comment]
https://www.mediafire.com/file/k1c8xgw18dzgwe6/2020-08-11+17-56-47.mkv/file
here is a video that shows they are working for me

**Comment by kisiel999** [comment]
This is a tokened stream.

**Comment by Sphinxroot** [comment]
try these if not geo then its good  working in kodi maybe not in other app  just remove  |User-Agent=VLC to try

#EXTINF:-1 tvg-id="France" tvg-name="W9 FR" tvg-logo="https://i.imgur.com/iLW5G7x.png" group-title="France",W9 (OPT-2)
http://stream-e30453a4b.nmbs.top/m3u/France/a2ba967eb8.m3u8|User-Agent=VLC


#EXTINF:-1 tvg-id="France" tvg-name="TF1 FR" tvg-logo="https://i.ibb.co/M8GjLmy/TF1.png" group-title="France",TF1
https://tf1-hls-live-ssl.tf1.fr/tf1/1/hls/live_2328.m3u8

#EXTINF:-1 tvg-id="France" tvg-name="TF1 Series" tvg-logo="https://i.ibb.co/41Dt9TY/TF1Serie.png" group-title="France;Movies",TF1 Series/films
https://tsf-hls-live-ssl.tf1.fr/tsf/1/hls/live_2328.m3u8


#EXTINF:-1 tvg-id="France" tvg-logo="https://i.imgur.com/FNonACy.png" group-title="France",M6
http://51.15.3.161:8080/M6/index.m3u8?token=test

#EXTINF:-1 tvg-id="France" tvg-name="M6 FR" tvg-logo="https://i.imgur.com/FNonACy.png" group-title="France",M6 (OPT-2)
http://stream-e30453a4b.nmbs.top/m3u/France/c1f5830564.m3u8|User-Agent=VLC

#EXTINF:-1 tvg-id="France" tvg-name="M6 Music" tvg-logo="https://i.imgur.com/ILg9C6Z.png" group-title="France",M6 MUSIC
http://stream-e30453a4b.nmbs.top/m3u/France/001f2f04bd.m3u8|User-Agent=VLC

**Comment by freearhey** [comment]
TF1: https://github.com/iptv-org/iptv/blob/c321151ad2cfe3b5d771e9e5b673d48015fea01a/channels/fr.m3u#L130-L131

**Comment by freearhey** [comment]
Closed in favor #1939
