### ISSUE TITLE
Univision west 

### ISSUE THREAD

**Issue by Urfavoritrat** [iptv-org/iptv#16832]
### Channel ID (required)

Univision.us

### Channel Name

Univision west 

### Stream URL (required)

https://deporte.lat/847291/uv.php?ch=univision_west

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by shelomito12** [comment]
https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_fastly.m3u
