### ISSUE TITLE
Add: Disney Channel Poland

### ISSUE THREAD

**Issue by mavijavi5124** [iptv-org/iptv#16838]
### Channel ID (required)

DisneyChannel.pl

### Channel Name

Disney Channel PL

### Stream URL (required)

http://185.236.229.62:9981/play/a07d

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Works but very long delay.
