### ISSUE TITLE
Broken:  Bangladesh Channels

### ISSUE THREAD

**Issue by Ox3rror** [iptv-org/iptv#16846]
### Broken Link

https://iptv-org.github.io/iptv/countries/bd.m3u

### What happened to the stream?

Not loading

### Notes (optional)

Here's the list of channels not working. Ex: Shomoy tv, channel 24, Channel I, Independent tv. Basically most of the channels are broken, shows black screen. 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-id="",Shomoy tv
https://ythls.armelin.one//channel/UCxHoBXkY88Tb8z1Ssj6CWsQ.m3u8

#EXTINF:-1 tvg-id="",Independent tv
https://ythls.armelin.one//channel/UCATUkaOHwO9EP_W87zCiPbA.m3u8

#EXTINF:-1 tvg-id="",channel 24
https://ythls.armelin.one//channel/UCHLqIOMPk20w-6cFgkA90jw.m3u8

#EXTINF:-1 tvg-id="",Channel I
https://ythls.armelin.one//channel/UC8NcXMG3A3f2aFQyGTpSNww.m3u8

i guest all of those have changed
https://us170.jagobd.com:447/
