### ISSUE TITLE
Cloud.odysee.live is not working

### ISSUE THREAD

**Issue by Mr-Poyetas** [iptv-org/iptv#16844]
### Describe your issue

Streams from this page are not working, several others do

https://github.com/iptv-org/iptv/assets/143344104/c89c299d-77bf-430b-b1b7-3f8c53bf4e5c

Trying to access the link from a browser displays a 403 error instead of a Download window

![image](https://github.com/iptv-org/iptv/assets/143344104/775f9175-e23b-416b-8bf0-97dcfcffbf4f)

Streamtest shows the stream as offline

![image](https://github.com/iptv-org/iptv/assets/143344104/f05824bc-9875-440b-9140-4cf06f9fde67)

Any help is appreciated

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Odysee stream works only in main site but doesn't work.
https://odysee.com/@ActualidadRT:9/rt_transmision_en_vivo:e

**Comment by BellezaEmporium** [comment]
https://cloud.odysee.live/content/9f638b94d11d879726ae55dd5a0923621b96a45b/master.m3u8
Referer: https://odysee.com/

**Comment by Mr-Poyetas** [comment]
I can't make it work, I'm closing this issue. Thanks.
