### ISSUE TITLE
Telefe.ar has malformed stream

### ISSUE THREAD

**Issue by LondonX** [iptv-org/iptv#16856]
### Describe your issue

The stream added in iptv-org/iptv#16169 has malformed url

> Stream URL (required)
> (https://mitelefe.com/Api/Videos/GetSourceUrl/694564/0/HLS / https://ssl.cloud.telefe.com/Api/Videos/GetSourceUrl/694564/0/HLS)

Which makes the json in [streams.json](https://iptv-org.github.io/api/streams.json) has no `url`
`{"channel":"Telefe.ar","timeshift":null,"http_referrer":null,"user_agent":null}`

### Contributing Guide

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
Remove c \ it will look like this here I’m helping u https://mitelefe.com/Api/Videos/GetSourceUrl/694564/0/HLS

**Comment by Plus018** [comment]
I know how

**Comment by Plus018** [comment]
Let me test

**Comment by Plus018** [comment]
![IMG_2233](https://github.com/user-attachments/assets/feda8a41-069f-4896-a4aa-1e6a804ef0c0)

**Comment by Plus018** [comment]
This one is offline

**Comment by guaymatetv** [comment]
https://glb.bozztv.com/glb/ssh101/guaymatetv/index.m3u8
