### ISSUE TITLE
Add: Disney Channel Poland

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/iptv#16857]
### Channel ID (required)

DisneyChannel.pl

### Channel Name

Disney Channel Poland

### Stream URL (required)

http://185.236.229.62:9981/play/a07d

### Quality

1080p

### Label

None

### Notes

Completing request #16838

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by TestNintendo** [comment]
Duplicate of #16838.
