### ISSUE TITLE
Broken: TCM East missing?

### ISSUE THREAD

**Issue by plissken1138** [iptv-org/iptv#16855]
### Broken Link

there is no link?

### What happened to the stream?

Other

### Notes (optional)

Link to the channel vanished completely.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Removed because of DMCA
https://github.com/iptv-org/iptv/pull/16840
