### ISSUE TITLE
Unable to connect to the Singapore channel server

### ISSUE THREAD

**Issue by beisongc** [iptv-org/iptv#1685]
**What's wrong?**
Unable to connect to the Singapore channel server

**Country of the channel:**
Singapore channel

**Channel Name:**
Channel 8, Channel 5, Channel U

**Broken Link:**
https://d34e90s3s13i7n.cloudfront.net/hls/ch8ctv/master.m3u8
https://dlau142f16b92.cloudfront.net/hls/ch5ctv/master.m3u8
https://d3inlz9elsutjl.cloudfront.net/hls/chuctv/master.m3u8

**Additional Information (optional):**

**Comment by exodiver** [comment]
The links are not longer broken. Just test with VLC, Mediaplayer Classic and tvimate.

**Comment by freearhey** [comment]
I still don't have those links working. Tested in VLC and Elmedia Video Player.

**Comment by beisongc** [comment]
Still not working, tested in PotPlayer.

**Comment by exodiver** [comment]
> PotPlayer.

Interesting, are you playing from the link from Singapore or with a vpn connection to singapore?

**Comment by beisongc** [comment]
1. playing from Malaysia
2. with VPN US
3. with VPN Netherlands
4. with VPN Japan
all not working, only the Channel NewsAsia is working.

Must SG IP or ?

**Comment by exodiver** [comment]
VLC:
[img]https://i.imgur.com/KQdvSsz.png[/img]

**Comment by exodiver** [comment]
> 1. playing from Malaysia
> 2. with VPN US
> 3. with VPN Netherlands
> 4. with VPN Japan
>    all not working, only the Channel NewsAsia is working.
> 
> Must SG IP or ?

That could be the reason. Let me connect to my oversea vpn.

**Comment by exodiver** [comment]
Ok, try with the overseas vpn and it did not work. Pretty much the singapore links (from the mewatch apps) are geo-restricted to singapore, besides Channel Newsasia (which is taken from the Channel Newsasia website)

**Comment by beisongc** [comment]
> Ok, try with the overseas vpn and it did not work. Pretty much the singapore links (from the mewatch apps) are geo-restricted to singapore, besides Channel Newsasia (which is taken from the Channel Newsasia website)

oic, thank you very much for your test and reply.

**Comment by exodiver** [comment]
No problem. It is heartening that someone out there still appreciate Singaporean tv channels.

**Comment by bertperrisor** [comment]
@exodiver If you want to know why it's no longer working:

1. Cloudfront is no longer being used to stream their media - its akamaized now.
2. Mewatch now has a DRM protection, so viewing the streams is impossible to use their streams. Astro On The Go used to do the same for M3U8 streams before now they use MPEG DASH streams.

Unless someone is illegally restreaming the content via TVHeadend or something, then no one can view Mewatch contents other than logging in to the app itself. 

Please see my comment in https://github.com/iptv-org/iptv/issues/1697#issuecomment-679180394 in @beisongc 's issue
