### ISSUE TITLE
Add: 

### ISSUE THREAD

**Issue by Gonzkin1** [iptv-org/iptv#16854]
### Channel ID (required)

TyCSportHD.ar

### Channel Name

TyC Sports HD

### Stream URL (required)

rtmp://sl100tb.cxnlive.com/live/tyc.stream

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Doesn't work in France. Geo ?

**Comment by queazified** [comment]
![image](https://github.com/iptv-org/iptv/assets/122835476/5d32f07e-6a2c-4a6f-8add-aa13c823fee9)
stream does not work in argentina

**Comment by Sphinxroot** [comment]
https://github.com/sesteva/m3u/blob/master/argentina.txt  10years old  link
