### ISSUE TITLE
Broken: univision houston

### ISSUE THREAD

**Issue by Urfavoritrat** [iptv-org/iptv#16867]
### Broken Link

https://unidfp-nlds145.global.ssl.fastly.net/nlds/univisionnow/univision_hou2/as/live/univision_hou2_hd_pc.m3u8?t1=

### What happened to the stream?

Not loading

### Notes (optional)

not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Related to all streams cutting off. Seems like Univision cut all of their possible endpoints due to the current sporting events.
