### ISSUE TITLE
Broken: univision panregional

### ISSUE THREAD

**Issue by Urfavoritrat** [iptv-org/iptv#16865]
### Broken Link

https://linear-424.frequency.stream/mt/studio/424/hls/master/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

when i tried to open it it said the the website could not be found

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by shelomito12** [comment]
https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_fastly.m3u

**Comment by Urfavoritrat** [comment]
> https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_fastly.m3u

the link dont work
