### ISSUE TITLE
Broken: Ten Cricket

### ISSUE THREAD

**Issue by thesangoLK** [iptv-org/iptv#16864]
### Broken Link

https://bpcdn.dialog.lk/bpk-tv/Ch065/output/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

anyone has an idea for play this stream. 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
No longer exists.
