### ISSUE TITLE
Add: Disney XD Poland

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/iptv#16878]
### Channel ID (required)

DisneyXD.pl

### Channel Name

Disney XD Poland

### Stream URL (required)

http://178.219.128.68:64888/DISNXD

### Quality

576p

### Label

None

### Notes

Submitting request #16841

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by TestNintendo** [comment]
Duplicate of #16841.
Close the issue ASAP.
