### ISSUE TITLE
Broken: Disney Junior (Poland)

### ISSUE THREAD

**Issue by TestNintendo** [iptv-org/iptv#16888]
### Broken Link

http://185.236.229.62:9981/play/a06n

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by TestNintendo** [comment]
nevermind

**Comment by giomgan1994** [comment]
What happened?

**Comment by TestNintendo** [comment]
i created an issue by accident
