### ISSUE TITLE
Broken: Las Estrellas Latin America 

### ISSUE THREAD

**Issue by julio16101** [iptv-org/iptv#16884]
### Broken Link

https://channel01.akamaized.net/hls/live/2022749/event01/index.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
https://www.lasestrellas.tv/las-estrellas-en-vivo-livestream

La página que estás buscando probablemente ya no existe o está temporalmente deshabilitada
