### ISSUE TITLE
Broken: unicable mexico

### ISSUE THREAD

**Issue by Urfavoritrat** [iptv-org/iptv#16881]
### Broken Link

https://linear-423.frequency.stream/mt/studio/423/hls/master/playlist.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Program stopped on 2024-06-20. Most certainly due to the current cup.
