### ISSUE TITLE
Add: Canal+ Sport (czech)

### ISSUE THREAD

**Issue by Piccaakak** [iptv-org/iptv#16899]
### Channel ID (required)

CanalPlusSport1.cz

### Channel Name

Canal+ Sport

### Stream URL (required)

http://78.130.250.2:8023/play/a02v/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by olstern01** [comment]
This stream lags really bad for me on VLC.

**Comment by Piccaakak** [comment]
Yes, but this link is from czech provider maybe. in full hd quality and 60 fps!

**Comment by olstern01** [comment]
![Screenshot 2024-06-29 061525](https://github.com/iptv-org/iptv/assets/47495790/e1c8bf2e-21da-48f2-8dd8-d0cd6ecc0d14)

The Channel ID should be CanalPlusSport1.cz , not CanalPlusSport.cz
