### ISSUE TITLE
Add: ČT24 (czech)

### ISSUE THREAD

**Issue by Piccaakak** [iptv-org/iptv#16898]
### Channel ID (required)

CT24.cz

### Channel Name

ČT24

### Stream URL (required)

http://88.212.7.10/live/test_ct24_hevc/playlist.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by olstern01** [comment]
The stream is very slow on my end. Is it fast on yours?

**Comment by Piccaakak** [comment]
yes

**Comment by olstern01** [comment]
I tried it again. It loads fast this time. Noice.

**Comment by olstern01** [comment]
According to https://iptv-org.github.io/ , CT24's Channel ID is CT24.cz , not CT24.cs .

![Screenshot 2024-06-28 155509](https://github.com/iptv-org/iptv/assets/47495790/6a2c611a-834a-4ee3-9376-1f5ce0b13ae8)

Please edit the Channel ID of this issue and other issues you've created to the correct Channel ID. That way the collaborators will approve your issues faster. You can refer to https://iptv-org.github.io/ for reference.
