### ISSUE TITLE
Add: Kilisuci TV

### ISSUE THREAD

**Issue by rizi136** [iptv-org/iptv#16891]
### Channel ID (required)

KilisuciTV.id

### Channel Name

Kilisuci TV

### Stream URL (required)

https://5bf7b725107e5.streamlock.net/kstv/kstv/playlist.m3u8

### Quality

360p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by rizi136** [comment]
![Screenshot_2024-06-26_142441](https://github.com/iptv-org/iptv/assets/173884781/5e36869b-e6d2-47d1-ad1b-0f5ae55e6ae1)

**Comment by rizi136** [comment]
![Screenshot_2024-06-26_143040](https://github.com/iptv-org/iptv/assets/173884781/79fab135-2de4-492a-a6f5-14b1a34e1fc2)

**Comment by Alstruit** [comment]
Merging on #16887.
