### ISSUE TITLE
Add:  Univision east

### ISSUE THREAD

**Issue by Urfavoritrat** [iptv-org/iptv#16909]
### Channel ID (required)

Univision.us

### Channel Name

Univision east

### Stream URL (required)

https://www.telegratishd.com/univision-en-vivo.html

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by shelomito12** [comment]
https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_fastly.m3u
