### ISSUE TITLE
Add: CT Sport (CZ)

### ISSUE THREAD

**Issue by DenysMath** [iptv-org/iptv#16900]
### Channel ID (required)

CTSport.cz

### Channel Name

ČT Sport

### Stream URL (required)

http://88.212.7.10/live/test_ctsport_25p/playlist.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by VlastikYoutubeKo** [comment]
Quality is 720p, not 1080p.

**Comment by DenysMath** [comment]
> Quality is 720p, not 1080p.

Thanks!
