### ISSUE TITLE
Edit: ANIMESTATION

### ISSUE THREAD

**Issue by MattGames123** [iptv-org/iptv#16902]
### Stream URL (required)

 https://ssh101-fl.bozztv.com/ssh101/livestreamingtv/index.m3u8

### Channel ID

ANIMESTATION.ar

### Channel Name

ANIMESTATION

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by olstern01** [comment]
Is there a reason why this issue is still open?

**Comment by MattGames123** [comment]
they haven't added the stream link to the database m3u

**Comment by kaikyoofers** [comment]
Guessing the bot is down, should i add this myself?

**Comment by MattGames123** [comment]
there's also an EPG guide on the site (not the stream link) but i think having a functioning stream works too.

**Comment by olstern01** [comment]
I checked iptv.org, turns out this channel has no existing stream link. Maybe instead of edit stream, you should've add new stream instead.

**Comment by MattGames123** [comment]
just saying because it has an entry but no stream link

**Comment by olstern01** [comment]
Yes, I mean maybe if you add new stream instead of edit, if it's approved the bot will add it to the playlist automatically. The bot can't do it because this is for editing description to existing channel that already has a stream link, not adding a new stream link. Should I open a new issue for you? Or maybe @kaikyoofers can add it through PR.

**Comment by MattGames123** [comment]
maybe, depending on which is easier.

Em sex., 5 de jul. de 2024 19:57, olstern01 ***@***.***>
escreveu:

**Comment by olstern01** [comment]
Okay, I've opened a new issue here:

https://github.com/iptv-org/iptv/issues/16960

Waiting for approval.

**Comment by kaikyoofers** [comment]
Me doing a PR is easier

**Comment by kaikyoofers** [comment]
and maybe faster too

**Comment by olstern01** [comment]
Okay, you can do the PR. After it's merged, I'll close the issue.

**Comment by kaikyoofers** [comment]
https://github.com/iptv-org/iptv/pull/16961

**Comment by olstern01** [comment]
Noice.
