### ISSUE TITLE
ZoomTV Kurdish

### ISSUE THREAD

**Issue by mamosa14** [iptv-org/iptv#16901]
### Channel ID (required)

ZoomNews.us

### Channel Name

Zoom TV Kurdish

### Stream URL (required)

https://live.zoomnews.info/live/Zoom_playlist.m3u8

### Quality

720p

### Label

None

### HTTP Referrer

https://zoomnews.info/

### Notes

ZoomTV Kurdish , it brodcast News And Documentary

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
@Carlinhos027 @ProPontifex please help with this one

**Comment by ProPontifex** [comment]
Done: actually called Zoom News fwiw
