### ISSUE TITLE
Broken: MBCBollywood.ae

### ISSUE THREAD

**Issue by CasperMcFadden95** [iptv-org/iptv#16912]
### Broken Link

https://shls-mbcdramaksa-ak.akamaized.net/out/v1/a79c9d7ef2a64a54a64d5c4567b3462a/index.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by mavijavi5124** [comment]
What is this channel

**Comment by BellezaEmporium** [comment]
MBC Drama KSA but was normally another channel behind that host.

All Shahid channels are getting ditched right now, as they're preparing for integration of Samsung TV + in Middle East.

**Comment by CasperMcFadden95** [comment]
There's another link in ae.m3u that works. I just want to remove this broken link.
