### ISSUE TITLE
All https://i.mjh.nz/SamsungTVPlus

### ISSUE THREAD

**Issue by TKList** [iptv-org/iptv#16934]
### Broken Link

https://i.mjh.nz/SamsungTVPlus/GBBA33000540B.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Not Found

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by werimail** [comment]
Solved: Look at: https://github.com/matthuisman/slyguy.addons/issues/784#issue-2385752881

**Comment by Dum4G** [comment]
Very good catch

**Comment by Dum4G** [comment]
> Solved: Look at: [matthuisman/slyguy.addons#784 (comment)](https://github.com/matthuisman/slyguy.addons/issues/784#issue-2385752881)

Very good catch. Thank you
