### ISSUE TITLE
Add: TRK Nadiya/Novy Channel

### ISSUE THREAD

**Issue by lime360** [iptv-org/iptv#16935]
### Channel ID (required)

TRKNadiya.ua

### Channel Name

ТРК Надія

### Stream URL (required)

http://178.217.215.57/mob/mystream.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
https://github.com/iptv-org/iptv/blob/312c70949ae146c1fc47bfc874302e712179d1c4/streams/ua.m3u#L138-L139

**Comment by lime360** [comment]
> https://github.com/iptv-org/iptv/blob/312c70949ae146c1fc47bfc874302e712179d1c4/streams/ua.m3u#L138-L139

i didn't know that the stream has an alternate link
