### ISSUE TITLE
Broken: Fox news channel

### ISSUE THREAD

**Issue by CringeArab** [iptv-org/iptv#16940]
### Broken Link

https://news.codeautoplaycdn1.workers.dev/?channel=foxnewschannel&codeby=nd

### What happened to the stream?

Other

### Notes (optional)

the channel works only in the morning according to European time, closer to the middle and at the end of the day there is just constant loading in the player.  When we try to access the link, we see what is in the screenshot.  Is this a problem with my VPN or something else?
![Screenshot](https://github.com/iptv-org/iptv/assets/168850586/c4285fb4-10b7-4120-806c-b4103591a302)

EDIT: most likely there is a limit on the number of requests on the site

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Maybe it's worth to put Not 24/7 tag on the stream if it's working at times

**Comment by Dum4G** [comment]
I think it would be better to remove this source as unreliable

**Comment by Dum4G** [comment]
This link is not part of playlist

**Comment by codeautoplay** [comment]
> > Maybe it's worth to put Not 24/7 tag on the stream if it's working at times
> 
> this is a problem with the stream, not the channel, the channel works 24/7 but apparently the stream is hosted by cloudflare worker free, which has a request limit of up to 50

Cloudflare worker free plan support 100000 requests/day  , its getting more than 200000 requests / day , that why problem

**Comment by InsolenceWillow** [comment]
> > I think it would be better to remove this source as unreliable
> 
> it would be nice to find a replacement for it, otherwise [I searched and never found anything](https://github.com/iptv-org/iptv/issues/16959)

I Think This Is A Good Stream: http://fl2.moveonjoy.com/FOX_News_Channel/index.m3u8

**Comment by InsolenceWillow** [comment]
> > > > I think it would be better to remove this source as unreliable
> > > 
> > > 
> > > it would be nice to find a replacement for it, otherwise [I searched and never found anything](https://github.com/iptv-org/iptv/issues/16959)
> > 
> > 
> > I Think This Is A Good Stream: http://fl2.moveonjoy.com/FOX_News_Channel/index.m3u8
> 
> I love you. Will you add this stream yourself or should I do it?

I'll Do It If You Want!

**Comment by InsolenceWillow** [comment]
#17015

**Comment by codeautoplay** [comment]
> @codeautoplay Can you create multiple accounts for cloudflare worker for example using a temp-mail for each channel? I could do it but I don't have the source code

but managing it will be problem as cf now sending otp on login. let me trying something new , (ex - https://github.com/iptv-org/iptv/issues/17016  )
