### ISSUE TITLE
Edit: colombia

### ISSUE THREAD

**Issue by DIEGOGARCIA601050** [iptv-org/iptv#16948]
### Stream URL (required)

https://iptv-org.github.io/iptv/subdivisions/ca-bc.m3u

### Channel Name

rtve.es

### Quality

None

### Label

None

### HTTP User Agent

Linux

### Notes

rtve.es is a Spanish channel, rtve.es it is not a Colombian channel

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Database issue (IF ANY)
