### ISSUE TITLE
Boston WFXT 25

### ISSUE THREAD

**Issue by 150King** [iptv-org/iptv#16942]
### Describe your issue

Audio has been choppy for a while

http://143.244.60.30/FOX_EAST/index.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
No problems using Chrome but it starts having problems in vlc.

**Comment by Dum4G** [comment]
Can't reproduce now

**Comment by R4IN2007** [comment]
Audio is fine now
![Screenshot_20240711_173357_VLC](https://github.com/user-attachments/assets/0ef8181f-c6b3-4428-af08-3963185d3a41)

**Comment by spotanjo3** [comment]
> ### Describe your issue
> 
> Audio has been choppy for a while
> 
> http://143.244.60.30/FOX_EAST/index.m3u8
> ### Contributing Guide
> 
>     * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

Thats New York. Wrong channel.
