### ISSUE TITLE
Add: Sony SAB

### ISSUE THREAD

**Issue by codeautoplay** [iptv-org/iptv#16958]
### Channel ID (required)

SonySAB.in

### Channel Name

Sony SAB

### Stream URL (required)

https://s.codeautoplay.workers.dev/?codeby=nd&channel=sabhd

### Quality

None

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
but does it work in vlc?

**Comment by Dum4G** [comment]
@BellezaEmporium

**Comment by Sphinxroot** [comment]
You don't have permission to access http://tataplaymt.slivcdn.com/hls/live/2011749/SABHD/hdntl=exp=1720987224%7eacl= ................token /master_3500.m3u8
