### ISSUE TITLE
Broken: TRT1 - Turkey

### ISSUE THREAD

**Issue by icedemon34** [iptv-org/iptv#16955]
### Broken Link

https://d1u68oyra9spme.cloudfront.net/master.m3u8

### What happened to the stream?

Shows looped video

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by devingDev** [comment]
It keeps repeating the same ~1 minute for me so doesn't work either.
https://d1u68oyra9spme.cloudfront.net/master.m3u8
Same link. Other links under that one don't work at all.
https://github.com/iptv-org/iptv/blob/master/streams/tr.m3u#L389

**Comment by ghokun** [comment]
This one works https://tv-trt1-dai.medya.trt.com.tr/master.m3u8

**Comment by devingDev** [comment]
> This one works https://tv-trt1-dai.medya.trt.com.tr/master.m3u8

Are you using a turkish VPN? Because for me this does not play.
As I said the ones below don't work which also has the link you posted

#EXTINF:-1 tvg-id="TRT1.tr",TRT 1 (1080p) [Geo-blocked]
https://tv-trt1-dai.medya.trt.com.tr/master.m3u8

it even says geoblocked :(

Is there a simple free vpn that works for this because mine does not have turkey vpn and they probably block vpns anyway so..

**Comment by ghokun** [comment]
> > This one works [tv-trt1-dai.medya.trt.com.tr/master.m3u8](https://tv-trt1-dai.medya.trt.com.tr/master.m3u8)
> 
> Are you using a turkish VPN? Because for me this does not play. As I said the ones below don't work which also has the link you posted
> 
> #EXTINF:-1 tvg-id="TRT1.tr",TRT 1 (1080p) [Geo-blocked] [tv-trt1-dai.medya.trt.com.tr/master.m3u8](https://tv-trt1-dai.medya.trt.com.tr/master.m3u8)
> 
> it even says geoblocked :(
> 
> Is there a simple free vpn that works for this because mine does not have turkey vpn and they probably block vpns anyway so..

No, watching from NL without any VPN.

**Comment by devingDev** [comment]
Interesting... now it works(?) 
I tried yesterday to no avail none of those links worked and the top one kept repeating the same 1 minute over and over.
Weird

**Comment by ghokun** [comment]
> Interesting... now it works(?) I tried yesterday to no avail none of those links worked and the top one kept repeating the same 1 minute over and over (which it still does, just tested now). Weird

If you tried to watch eurocup, they blocked it during the match.
