### ISSUE TITLE
Add: Sony Pix

### ISSUE THREAD

**Issue by codeautoplay** [iptv-org/iptv#16956]
### Channel ID (required)

SonyPix.in

### Channel Name

Sony Pix

### Stream URL (required)

https://s.codeautoplay.workers.dev/?codeby=nd&channel=sonypixhd

### Quality

None

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
You don't have permission to access http://tataplaymt.slivcdn.com/hls/live/2011748/PIXHD/hdntl=exp=1720987224%7eacl=Token....../master_3500.m3u8
