### ISSUE TITLE
Add: Sony BBC Earth

### ISSUE THREAD

**Issue by codeautoplay** [iptv-org/iptv#16957]
### Channel ID (required)

SonyBBCEarth.in

### Channel Name

Sony BBC Earth

### Stream URL (required)

https://s.codeautoplay.workers.dev/?codeby=nd&channel=sonybbcearth

### Quality

None

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
You don't have permission to access http://tataplaymt.slivcdn.com/hls/live/2011907/SonyBBCEarthHD/hdntl=exp=1720987224%7eacl=TOKEN....../master_3500.m3u8
