### ISSUE TITLE
Add: TRT 4K

### ISSUE THREAD

**Issue by CasperMcFadden95** [iptv-org/iptv#16963]
### Channel ID (required)

TRT4K.tr

### Stream URL (required)

https://mn-nl.mncdn.com/blutv_trt4k/live.m3u8

### Quality

2160p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ramazansancar** [comment]
Thanks @CasperMcFadden95. I'm checked.

**Comment by manueldev** [comment]
Is this link still active? I get a 404 error.

**Comment by BellezaEmporium** [comment]
Seems to have been removed. Rather odd.

**Comment by xcfgn** [comment]
the link is from a paid service called blutv maybe thats why

**Comment by ramazansancar** [comment]
It was a link belonging to BluTV, which is entered into the system with a paid membership serving in Turkey. Due to changes in the stream connection structure, many blutv m3u8 broadcast links have become inoperable. @manueldev @BellezaEmporium @xcfgn
