### ISSUE TITLE
SG Channel unable to connect to the server

### ISSUE THREAD

**Issue by beisongc** [iptv-org/iptv#1696]
**What's wrong?**
SG Channel unable to connect to the server.

**Country of the channel:**
Singapore

**Channel Name:**
Channel 8 
Channel 5

**Broken Link:**
Channel 8: https://d34e90s3s13i7n.cloudfront.net/hls/ch8ctv/master.m3u8
Channel 5: https://dlau142f16b92.cloudfront.net/hls/ch5ctv/master.m3u8

**Additional Information (optional):**
I subscribe Windscribe SG VPN and able to watch Channel 8 yesterday, but today can't connect again, can someone help to test the link is ok or not? SG Channel block the VPN or ?
Channel U is able to connect, just Channel 8 and Channel 5 unable.

**Comment by freearhey** [comment]
@beisongc Thank you for reporting this. I already deleted all the non-working links from the playlist.
