### ISSUE TITLE
Add: :Šport (SK)

### ISSUE THREAD

**Issue by DenysMath** [iptv-org/iptv#16986]
### Channel ID (required)

Sport.sk

### Channel Name

:Šport

### Stream URL (required)

http://88.212.7.10/live/test_rtvs_sport_hevc/playlist.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Piccaakak** [comment]
ok už jsem nic neposílej akorát ten link zničíš jo? a budeme mít po srandě
