### ISSUE TITLE
Add: :24 (SK)

### ISSUE THREAD

**Issue by DenysMath** [iptv-org/iptv#16985]
### Channel ID (required)

24.sk

### Channel Name

:24

### Stream URL (required)

http://88.212.7.10/live/test_trojka_25p/playlist.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by DenysMath** [comment]
Also stream links for Jednotka
http://88.212.7.10/live/test_jednotka_25p/playlist.m3u8
and Dvojka
http://88.212.7.10/live/test_dvojka_25p/playlist.m3u8

**Comment by sleduj-tv** [comment]
Ty kokot prijebany! Pockaj, ked ta schytim pod krk. Potom budes mat po srande
