### ISSUE TITLE
Cloudflare TV m3u8 link changed (fix: remove live. from it)

### ISSUE THREAD

**Issue by lolwhenlifegivesyoulemons** [iptv-org/iptv#1698]
**What's wrong?**
Channel is broken
**Country of the channel:**
US
**Channel Name:**
CloudflareTV
**Broken Link:**
https://live.cloudflare.tv/hls/live.m3u8

**Additional Information (optional):**
Fix by removing the 'live.' part since they have changed subdomains

**Comment by freearhey** [comment]
Thank you for the report.
