### ISSUE TITLE
Add: TV4 (Poland) (.MPD)

### ISSUE THREAD

**Issue by Irylek** [iptv-org/iptv#17007]
### Channel ID (required)

TV4.pl

### Channel Name

TV4

### Stream URL (required)

https://live-ipla-e1-82.pluscdn.pl/t3/24180/0/dash_rel_mp/63212030/live.mpd

### Quality

576p

### Label

None

### Timeshift

3 hours

### Notes

Need to work with dash.js.
Stream is working at https://irylek.github.io/stream/tv4.html

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
It actualy does but shows some old segment
