### ISSUE TITLE
Add: Nickelodeon.es

### ISSUE THREAD

**Issue by joaquinito2070** [iptv-org/iptv#17017]
### Channel ID (required)

Nickelodeon.es

### Channel Name

Nickelodeon

### Stream URL (required)

http://185.189.225.150:85/nickelodeon/index.m3u8

### Quality

None

### Label

None

### Notes

Please add Nickelodeon, add It quickly, because tomorrow I will watch Kids Choice Awards 2024, and I don't have paid TV subscription to watch it.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by InsolenceWillow** [comment]
I Don't Think They'll Add That If You Don't Have The Stream Link!

**Comment by joaquinito2070** [comment]
Added stream link

**Comment by InsolenceWillow** [comment]
Okay, That Should Work Then!
