### ISSUE TITLE
Broken: Comedy Central (US)

### ISSUE THREAD

**Issue by rushereeeeee** [iptv-org/iptv#17011]
### Broken Link

http://170.254.18.106/COMEDY_CENTRAL/index.m3u8

### What happened to the stream?

Other

### Notes (optional)

Possible Replacement:
http://fl3.moveonjoy.com/Comedy_Central/index.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by JaphyDoesGithub** [comment]
Works
