### ISSUE TITLE
Add: FOX News Channel (USA)

### ISSUE THREAD

**Issue by InsolenceWillow** [iptv-org/iptv#17015]
### Channel ID (required)

FoxNewsChannel.us

### Channel Name

FOX News Channel

### Stream URL (required)

http://fl2.moveonjoy.com/FOX_News_Channel/index.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Fixed ID. Will be added.

**Comment by JohnTCarter1** [comment]
The stream went down yesterday afternoon. Any chance to fix it or add something of equal quality? Thank you in advance.

**Comment by gaixixon** [comment]
You may try this:
[http://streamsy.online:2999/live/juanv/04bodwaga0/267.m3u8](url)

**Comment by Nostradamus1973** [comment]
> http://streamsy.online:2999/live/juanv/04bodwaga0/267.m3u8

Good Afternoon,
That link is dead. Any chance you have an updated link?
Thank you and have a nice day.
