### ISSUE TITLE
Add: Newsmax TV

### ISSUE THREAD

**Issue by codeautoplay** [iptv-org/iptv#17016]
### Channel ID (required)

NewsmaxTV.us

### Channel Name

Newsmax TV

### Stream URL (required)

https://newsmax.codeautoplaycdn2.workers.dev/

### Quality

None

### Label

Geo-blocked

### Notes

Tested in ott navigator , this also on cloudflare worker but applied something new to fix rate limit issue

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by codeautoplay** [comment]
> Isn't vercel.app limited to [150k requests](https://vercel.com/docs/limits/overview#:~:text=from%20Vercel%20KV.-,First%20150%2C000,-100%2C000%20Requests)? Or do you have a paid plan?

this is redirect to cloudflare worker , so i don't think any problem of limit will be there. let's see

**Comment by Dum4G** [comment]
Can't confirm it working in VLC and SimpleTV, is it geo-blocked?

**Comment by codeautoplay** [comment]
> Can't confirm it working in VLC and SimpleTV, is it geo-blocked?

No its not geo-blocked , also its only working on some selected players only like ott navigator , tivimate due to vercel. Edit the link to https://newsmax.codeautoplaycdn2.workers.dev it will support all players

**Comment by Dum4G** [comment]
![image](https://github.com/user-attachments/assets/6fa1a1f9-c25e-4a1d-8cdb-027d8095f492)
works in browser tho

**Comment by BellezaEmporium** [comment]
![image](https://github.com/user-attachments/assets/600d0d9c-ffe6-46c8-9499-adf8d44beb31)

**Comment by TvK0d1** [comment]
> ### Channel ID (required)
> 
> NewsmaxTV.us
> ### Channel Name
> 
> Newsmax TV
> ### Stream URL (required)
> 
> https://newsmax-nd.vercel.app
> ### Quality
> 
> None
> ### Label
> 
> None
> ### Timeshift
> 
> _No response_
> ### HTTP User Agent
> 
> _No response_
> ### HTTP Referrer
> 
> _No response_
> ### Notes
> 
> Tested in ott navigator , this also on cloudflare worker but applied something new to fix rate limit issue
> ### Contributing Guide
> 
>     * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

Hi,

Could you please creat a .dev link for newsnationnow issue https://github.com/orgs/iptv-org/discussions/478#discussion-5592822

**Comment by codeautoplay** [comment]
> > ### Channel ID (required)
> > NewsmaxTV.us
> > ### Channel Name
> > Newsmax TV
> > ### Stream URL (required)
> > https://newsmax-nd.vercel.app
> > ### Quality
> > None
> > ### Label
> > None
> > ### Timeshift
> > _No response_
> > ### HTTP User Agent
> > _No response_
> > ### HTTP Referrer
> > _No response_
> > ### Notes
> > Tested in ott navigator , this also on cloudflare worker but applied something new to fix rate limit issue
> > ### Contributing Guide
> > ```
> > * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)
> > ```
> 
> Hi,
> 
> Could you please create a .dev link for newsnationnow?
> 
> issue https://github.com/orgs/iptv-org/discussions/478#discussion-5592822
> 
> Thanks

https://github.com/iptv-org/iptv/issues/17067

**Comment by codeautoplay** [comment]
any update

**Comment by BellezaEmporium** [comment]
I'm waiting to see if someone else has something to say to it. Works for me in browser, though I'm awaiting validation of others.

**Comment by Dum4G** [comment]
>https://newsmax.codeautoplaycdn2.workers.dev/ it will support all players

**Comment by BellezaEmporium** [comment]
> > https://newsmax.codeautoplaycdn2.workers.dev/ it will support all players
> 
> I wasn't able to validate this in VLC, can only reject for now but maybe someone is luckier than me

![image](https://github.com/user-attachments/assets/e077c64d-416c-48b4-9c21-9338fcbb5b31)
Works for me on VLC

**Comment by Dum4G** [comment]
So it is geo-blocked, doesn't work for me without VPN
