### ISSUE TITLE
Add: Tigo Sports Guatemala

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#17032]
### Channel ID (required)

TigoSports.gt

### Channel Name

Tigo Sports (Guatemala)

### Stream URL (required)

https://cnm-tsl.otteravision.com/cnm/tsl/tsl.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
The "l" in "tsl" is what bothers me. Should it be "TIGO Sports LATAM ?

**Comment by R4IN2007** [comment]
> The "l" in "tsl" is what bothers me. Should it be "TIGO Sports LATAM ?

It's under the name of Tigo Sports Latino in Canela.TV
https://www.canela.tv/linear/tigo-sports-latino

**Comment by R4IN2007** [comment]
> > The "l" in "tsl" is what bothers me. Should it be "TIGO Sports LATAM ?
> 
> It's under the name of Tigo Sports Latino in Canela.TV https://www.canela.tv/linear/tigo-sports-latino

Maybe this is a US or International version of Tigo Sports Guatemala?

**Comment by BellezaEmporium** [comment]
> > The "l" in "tsl" is what bothers me. Should it be "TIGO Sports LATAM ?
> 
> It's under the name of Tigo Sports Latino in Canela.TV https://www.canela.tv/linear/tigo-sports-latino

Seems like it. Maybe the main Tigo Sports stream.

**Comment by Dum4G** [comment]
So? @BellezaEmporium @R4IN2007

**Comment by BellezaEmporium** [comment]
> So? @BellezaEmporium @R4IN2007 

Works, but needs to be renamed "TIGO Sports Latino"

**Comment by Dum4G** [comment]
Can't find enough evidence that Latino variant in general exists, source currently shows black screen. I'll take closer look at it's content when it gets back online

**Comment by BellezaEmporium** [comment]
https://www.canela.tv/linear/tigo-sports-latino

**Comment by Dum4G** [comment]
![image](https://github.com/user-attachments/assets/4c9fce3e-0d02-4330-aed6-c18398f117da)
![image](https://github.com/user-attachments/assets/5bd2bd51-f68c-4906-8b36-4553c6579a50)
Confirm this stream to belong to Guateamala

**Comment by Vini2112** [comment]
Habrá uno nuevo ?
