### ISSUE TITLE
Add: MeTV Toons

### ISSUE THREAD

**Issue by InsolenceWillow** [iptv-org/iptv#17034]
### Channel ID (required)

WAAYDT8.us

### Channel Name

MeTV Toons

### Stream URL (required)

https://d3m10mlzdolmch.cloudfront.net/v1/master/840a24ccd7c75076211d060179b3ad0c64fdc6ca/metv_toon_nr/0d1dbf29e64e47bc991796cc24fbeb97/index.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Official stream? How about MeTV.

**Comment by R4IN2007** [comment]
![Screenshot_20240719_020745_Chrome](https://github.com/user-attachments/assets/76bda662-8d97-431a-86ae-694a8239d086)

**Comment by FORSIZERO** [comment]
work
Timeshift - 1

**Comment by trancer1994** [comment]
Is the stream linked here the official one for Metv Toons?

**Comment by R4IN2007** [comment]
> Is the stream linked here the official one for Metv Toons?

24/7? Yeah. Don't know if this just MeTV Toons or a Free to air verison MeTV Toons.

**Comment by InsolenceWillow** [comment]
> Official stream? How about MeTV.

MeTV: http://fl2.moveonjoy.com/ME_TV/index.m3u8

**Comment by GiovanniSebastian** [comment]
Any Link for MeTV Plus?

**Comment by InsolenceWillow** [comment]
> Any Link for MeTV Plus?

It's Not Even On Any IPTV I Found, So No...

**Comment by GiovanniSebastian** [comment]
Oh my Goodness, they already published it. Gracias Totales!!

**Comment by dougtechdude** [comment]
Is there any official MeTV Toons streaming URL?

**Comment by Mrpickle30** [comment]
Would like me tv toons but stopped working

**Comment by BellezaEmporium** [comment]
Talking about MeTV Toons ?

The only thing I can say, it's tokened.
![image](https://github.com/user-attachments/assets/fb955c3d-53af-43c1-b71a-74311865f6b7)

**Comment by Mrpickle30** [comment]
What does that mean tokened I am new just learning

**Comment by BellezaEmporium** [comment]
> What does that mean tokened I am new just learning

A token, in this particular case, means that the stream in question needs a kind of authentication in order to access said stream. It can be in form of a parameter inside the URL (like Akamai), or in a form of a cookie (in some other platforms).

**Comment by mony766** [comment]
Hello !

My name is Monica34 I just want to know  
that what's the name of the yours iptv 
provider to the channel Metv Toons.
I would really like to know.
Email address is:
mony.nyberg766@gmail.com

Best Regard From Monica34.

**Comment by aceray50** [comment]
This MeTV Toons should work, here's a link:
https://v1.thetvapp.to/hls/metv-toons/tracks-v1a1/mono.m3u8

**Comment by aceray50** [comment]
> Is there any official MeTV Toons streaming URL?

Yes, here it is:
https://v1.thetvapp.to/hls/metv-toons/tracks-v1a1/mono.m3u8

**Comment by Mrpickle30** [comment]
Was great for a little while was short lived

**Comment by dougtechdude** [comment]
> Was great for a little while was short lived

It's back online again

**Comment by R4IN2007** [comment]
Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
</Error>

**Comment by spotanjo3** [comment]
I would like to have METV TOONS link also.

**Comment by Brunisky14** [comment]
do i get metv toons link m3u now

**Comment by LithuanianBoi40** [comment]
Oh man give us m3u link using via usb

**Comment by spotanjo3** [comment]
Here it is: https://tvpass.org/playlist.m3u and open notepad for MeTV toons m3u8.

**Comment by LithuanianBoi40** [comment]
And work

**Comment by LithuanianBoi40** [comment]
Thank you for it

**Comment by spotanjo3** [comment]
> Thank you for it
 No problem.  😁

**Comment by LithuanianBoi40** [comment]
What write in notepad code I don't know

**Comment by LithuanianBoi40** [comment]
Will work?

**Comment by LithuanianBoi40** [comment]
It's Not Working

**Comment by spotanjo3** [comment]
Yes, it’s working. Just right-click the m3u8 file, open it with Notepad, and you’ll see a list. I tested it, and it works.

**Comment by LithuanianBoi40** [comment]
Give me file where find I don't know

**Comment by spotanjo3** [comment]
Learn. It is very easy. I will give you an instruction. Download it then find the file and use your mouse to right-click the m3u8 file and open it with Notepad. You will have the list.

**Comment by LithuanianBoi40** [comment]
Okay then give me?

**Comment by spotanjo3** [comment]
Okay.. 

#EXTINF:-1 tvg-id="metv-toons-wjlp2-new-jersey" tvg-name="MeTV Toons (WJLP2) New Jersey" group-title="Live",MeTV Toons (WJLP2) New Jersey
https://tvpass.org/live/metv-toons/hd

**Comment by LithuanianBoi40** [comment]
I tried but It show this error what solution to fix this i tried and will show you my notepad 

![Image](https://github.com/user-attachments/assets/3f60f400-8cc0-4250-9ba3-76f4d78f38a5)

![Image](https://github.com/user-attachments/assets/935cd277-94cd-479b-840a-4d7824dcd421)

**Comment by spotanjo3** [comment]
No, you have to make a notepad for it but you are newbie.. Just forget it. Too hard for you.

Do this:

You can use VLC player.. Go to Media-Open Network stream then put https://tvpass.org/live/metv-toons/hd and click Play.

**Comment by LithuanianBoi40** [comment]
Please help me I don't know

**Comment by spotanjo3** [comment]
Open VLC Player and on the top left - Click to Media-Open Network stream then copy and paste https://tvpass.org/live/metv-toons/hd and click Play.

That is not too hard.

**Comment by spotanjo3** [comment]
Or you can go to Open Network Stream and click File to find the file and click play.

**Comment by LithuanianBoi40** [comment]
but i show this error in vlc media player

**Comment by spotanjo3** [comment]
Show me

**Comment by LithuanianBoi40** [comment]
Sure, here you go!

**Comment by spotanjo3** [comment]
No. Show me what you are trying to do.

**Comment by LithuanianBoi40** [comment]
@spotanjo3 can you give me metv toons cloud front link instead of tvpass

**Comment by LithuanianBoi40** [comment]
Url

**Comment by spotanjo3** [comment]
I’m sorry, but there’s no way to get a URL from Toons MeTV at all, only TVPass. If you’re not sure how to use it, then I’m running out of options. I tried to explain it as simply as possible, and it’s pretty easy.

**Comment by dtngfan85** [comment]
There is no replacement cloudfront URL. That URL from 2024 was from a subscription service called Frndlytv who now protects their streams after people started posting them out in the open and submitting them to repositories that are on the radar of the rights holders that have sent multiple DMCA takedowns to this repository, including WBD where MeTV Toons sources most of its cartoons.

If the tvpass watermark annoys you that much, then pay for subscription to one of the legitimate services that have the rights to stream it, or use an antenna and watch it over the air:
https://www.metvtoons.com/wheretowatch/
