### ISSUE TITLE
Teleonce WLII

### ISSUE THREAD

**Issue by JaphyDoesGithub** [iptv-org/iptv#17031]
### Broken Link

https://univision-live.cdn.vustreams.com/live/ce88b839-6376-4494-a2ee-83d66bc7cfc1/live.isml/ce88b839-6376-4494-a2ee-83d66bc7cfc1.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

I'm not too sure if there is a replacment for this

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Stream down.

**Comment by TrptplayerPR** [comment]
Working link:

[https://customer-gllhkkbamkskdl1p.cloudflarestream.com/eyJhbGciOiJSUzI1NiIsImtpZCI6ImI3YmIwODNmMDhkNmQ5NWExZjIzZWE3ZWRhOWY4NTZhIn0.eyJzdWIiOiIyNGEyMzFhMzU0YjYyNzc3OTk4ZTdjZjQ5ODQ4MjI3MyIsImtpZCI6ImI3YmIwODNmMDhkNmQ5NWExZjIzZWE3ZWRhOWY4NTZhIiwiZXhwIjoxNzIxMzAyOTIxLCJhY2Nlc3NSdWxlcyI6W3sidHlwZSI6ImlwLmdlb2lwLmNvdW50cnkiLCJhY3Rpb24iOiJibG9jayIsImNvdW50cnkiOlsiUlUiLCJCWSJdfV19.kmGgz__wwV7wDZcLyouP17jrjj98-vAqgZPSz27_95eJ8IrvWhH0D2u-HeLdJHlaod2GCk_T59VeWKINWtQtHxWnBVbUw4zaN5GIf8o_RsxxCm6trdDg_KAXHrNBWXqyYnuMis-ISvkyQX8upSETzfIY4Q3VJqhVSw0otf7SXfQ3salumb-rfFO4Pu6FbW6wIfAhLLAAH5uKh2Ysb3zmIhERXL6h3DflFDZ17PddryBS5IAFof2zEI7Y0T0P_EmGUbSWX0s7gAYT94lq_avshfvGI8-4WmhVhmENno_BUVsmJpNWV5yew835T80JZafGGse6b1ox4iqyzzAj2whimw/manifest/video.m3u8](url)

**Comment by JaphyDoesGithub** [comment]
> Working link:
> 
> [https://customer-gllhkkbamkskdl1p.cloudflarestream.com/eyJhbGciOiJSUzI1NiIsImtpZCI6ImI3YmIwODNmMDhkNmQ5NWExZjIzZWE3ZWRhOWY4NTZhIn0.eyJzdWIiOiIyNGEyMzFhMzU0YjYyNzc3OTk4ZTdjZjQ5ODQ4MjI3MyIsImtpZCI6ImI3YmIwODNmMDhkNmQ5NWExZjIzZWE3ZWRhOWY4NTZhIiwiZXhwIjoxNzIxMzAyOTIxLCJhY2Nlc3NSdWxlcyI6W3sidHlwZSI6ImlwLmdlb2lwLmNvdW50cnkiLCJhY3Rpb24iOiJibG9jayIsImNvdW50cnkiOlsiUlUiLCJCWSJdfV19.kmGgz__wwV7wDZcLyouP17jrjj98-vAqgZPSz27_95eJ8IrvWhH0D2u-HeLdJHlaod2GCk_T59VeWKINWtQtHxWnBVbUw4zaN5GIf8o_RsxxCm6trdDg_KAXHrNBWXqyYnuMis-ISvkyQX8upSETzfIY4Q3VJqhVSw0otf7SXfQ3salumb-rfFO4Pu6FbW6wIfAhLLAAH5uKh2Ysb3zmIhERXL6h3DflFDZ17PddryBS5IAFof2zEI7Y0T0P_EmGUbSWX0s7gAYT94lq_avshfvGI8-4WmhVhmENno_BUVsmJpNWV5yew835T80JZafGGse6b1ox4iqyzzAj2whimw/manifest/video.m3u8](url)

I get a 404 error

**Comment by esterlingero** [comment]
> Working link:
> 
> [https://customer-gllhkkbamkskdl1p.cloudflarestream.com/eyJhbGciOiJSUzI1NiIsImtpZCI6ImI3YmIwODNmMDhkNmQ5NWExZjIzZWE3ZWRhOWY4NTZhIn0.eyJzdWIiOiIyNGEyMzFhMzU0YjYyNzc3OTk4ZTdjZjQ5ODQ4MjI3MyIsImtpZCI6ImI3YmIwODNmMDhkNmQ5NWExZjIzZWE3ZWRhOWY4NTZhIiwiZXhwIjoxNzIxMzAyOTIxLCJhY2Nlc3NSdWxlcyI6W3sidHlwZSI6ImlwLmdlb2lwLmNvdW50cnkiLCJhY3Rpb24iOiJibG9jayIsImNvdW50cnkiOlsiUlUiLCJCWSJdfV19.kmGgz__wwV7wDZcLyouP17jrjj98-vAqgZPSz27_95eJ8IrvWhH0D2u-HeLdJHlaod2GCk_T59VeWKINWtQtHxWnBVbUw4zaN5GIf8o_RsxxCm6trdDg_KAXHrNBWXqyYnuMis-ISvkyQX8upSETzfIY4Q3VJqhVSw0otf7SXfQ3salumb-rfFO4Pu6FbW6wIfAhLLAAH5uKh2Ysb3zmIhERXL6h3DflFDZ17PddryBS5IAFof2zEI7Y0T0P_EmGUbSWX0s7gAYT94lq_avshfvGI8-4WmhVhmENno_BUVsmJpNWV5yew835T80JZafGGse6b1ox4iqyzzAj2whimw/manifest/video.m3u8](url)

Link not working.

**Comment by R4IN2007** [comment]
Link changes

**Comment by TrptplayerPR** [comment]
> Link changes

It seems so. It was working yesterday.

**Comment by JaphyDoesGithub** [comment]
I hope there is a replacement link because I watch Teleonce
