### ISSUE TITLE
Add: The Nudu KBPX-LD3

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#17035]
### Channel ID (required)

KBPXLD3.us

### Channel Name

Nudu

### Stream URL (required)

https://d1p0bzoad08w6e.cloudfront.net/encode/nudu.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by FORSIZERO** [comment]
Work +
