### ISSUE TITLE
Broken: Oriental TV

### ISSUE THREAD

**Issue by rawde90** [iptv-org/iptv#17030]
### Broken Link

https://paz.sytes.net:5443/live/streams/orientaltv.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
stream player is 404 https://orientaltv.com.do/
