### ISSUE TITLE
Add: 30A Ridiculous TV

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/iptv#17046]
### Channel ID (required)

30ARidiculousTV.us

### Channel Name

30A Ridiculous TV

### Stream URL (required)

https://30a-tv.com/feeds/720p/63.m3u8

### Quality

720p

### Label

None

### HTTP Referrer
https://30a-tv.com/30a/funny-crazy-videos/ 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
if i add HTTP Referrer=https://30a-tv.com/30a/funny-crazy-videos/  it work  ,otherwise it dont load for me

**Comment by ProPontifex** [comment]
Please do then Sphinx and thanks.
