### ISSUE TITLE
Broken: Two TVK channels went offline!

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#17048]
### Broken Link

https://live.kh.malimarcdn.com/live/tvk.stream/playlist.m3u8

### What happened to the stream?

Stuck at a single frame

### Notes (optional)

@BellezaEmporium

Hey, guys! I found both livestream links for both TVK and TVK 2 went offline not only because of the technical problems but it happens on its [own website](http://www.tvk.gov.kh/) too!

[TVK (720p)](https://live.kh.malimarcdn.com/live/tvk.stream/playlist.m3u8)

[TVK 2 (720p)](https://live.kh.malimarcdn.com/live/tvk2.stream/playlist.m3u8)

Here's the image.
![vlcsnap-2024-07-21-20h56m05s131](https://github.com/user-attachments/assets/9bac7bdc-5f5a-4898-a135-bfec4bfe7dfb)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Back online
