### ISSUE TITLE
Broken: 	 101tv Axarquia

### ISSUE THREAD

**Issue by rawde90** [iptv-org/iptv#17059]
### Broken Link

https://streaming101tv.es/hls/webaxarquia.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
https://www.101tv.es/directo-axarquia-almijara/
Fuera de línea 
https://www.streaming101tv.es:19360/axarquia/axarquia.m3u8
