### ISSUE TITLE
Broken: Zona Music TV

### ISSUE THREAD

**Issue by rawde90** [iptv-org/iptv#17061]
### Broken Link

https://srv.panelcast.net/zonatv2023/zonatv2023/playlist.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
https://zonamusictvcr.wixsite.com/misitio

https://acceso.radiosportstv.online:3022/stream/play.m3u8

**Comment by sn02** [comment]
https://acceso.radiosportstv.online:3022/live/zonamusictvcrlive.m3u8

Player: https://zonamusictvcr-wixsite-com.filesusr.com/html/5330ac_0b39de8977133e6d308398af86839cbe.html
