### ISSUE TITLE
Broken: Telemedellin

### ISSUE THREAD

**Issue by rawde90** [iptv-org/iptv#17065]
### Broken Link

https://d3cglye48cl6m2.cloudfront.net/out/v1/37d85e2ab37c4873aed6849fe74e78b8/index.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
https://telemedellin.tv/senal-en-vivo/

https://liveingesta119.cdnmedia.tv/tvtelemedellinlive/smil:rtmp01.smil/playlist.m3u8?DVR

**Comment by Toei79** [comment]
i guess its not playing.  i cant get playing telecafe and teleantioquia both are from liveingesta too, stream links are the same, but not play  even with referral

**Comment by Sphinxroot** [comment]
in
https://player.instantvideocloud.net/assets/ivc-player.js

you will find
http://live10.cdnmedia.tv/telemedellintvlive/smil:dvrlive.smil/playlist.m3u8

geoIpReferrer="https://player.instantvideocloud.net"

but its
Referrer Policy strict-origin-when-cross-origin


tryed but aint working

**Comment by BellezaEmporium** [comment]
they've did a mistake.

it's "https://player.instantvideocloud.net/" basically, with the additional slash.

**Comment by Toei79** [comment]
im using slash but cant play  with other colombian channels same referrer
