### ISSUE TITLE
Add: NewsNation

### ISSUE THREAD

**Issue by codeautoplay** [iptv-org/iptv#17067]
### Channel ID (required)

NewsNationEast.us

### Channel Name

NewsNation

### Stream URL (required)

https://news.codeautoplayserver1.workers.dev/?codeby=nd&channel=newsnation

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by TvK0d1** [comment]
> ### Channel ID (required)
> 
> NewsNationEast.us
> ### Channel Name
> 
> NewsNation
> ### Stream URL (required)
> 
> https://news.codeautoplayserver1.workers.dev/?codeby=nd&channel=newsnation
> ### Quality
> 
> None
> ### Label
> 
> None
> ### Timeshift
> 
> _No response_
> ### HTTP User Agent
> 
> _No response_
> ### HTTP Referrer
> 
> _No response_
> ### Notes
> 
> _No response_
> ### Contributing Guide
> 
>     * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

Great thank you!

**Comment by InsolenceWillow** [comment]
Here's Another NewsNation Stream: http://fl2.moveonjoy.com/NEWS_NATION/index.m3u8
