### ISSUE TITLE
Add: Citytv Bogota

### ISSUE THREAD

**Issue by rawde90** [iptv-org/iptv#17066]
### Channel ID (required)

CitytvBogota.co

### Channel Name

Citytv Bogota

### Stream URL (required)

http://sore-bead-hardware.glitch.me/?channel=canalcitytv

### Quality

None

### Label

None

### HTTP Referrer

https://www.youtube.com/@canalcitytv/streams

### Notes

Php que convierte las transmisiones en vivo de youtube en url m3u8, no funciona en todos los reproductores, probada en las apps iptv#, iptvdelux

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
http://suspended-website.com/f/  ...

YT = https://www.youtube.com/channel/UCv5Oy_TJFvGKXjeNzzJE_PQ/live

**Comment by rawde90** [comment]
> http://suspended-website.com/f/ ...
> 
> YT = https://www.youtube.com/channel/UCv5Oy_TJFvGKXjeNzzJE_PQ/live

Debido a que el servidor gratuito no permitia la conexion directa con las transmisiones de youtube cree un nuevo proyecto en python para que se pueda reproducir por este link http://sore-bead-hardware.glitch.me/?channel=canalcitytv

**Comment by R4IN2007** [comment]
https://ythls-v3.onrender.com/channel/UCv5Oy_TJFvGKXjeNzzJE_PQ.m3u8

**Comment by BellezaEmporium** [comment]
https://ythls.armelin.one/video/fzyvVBzAeBI.m3u8
