### ISSUE TITLE
Broken: Turf Movil

### ISSUE THREAD

**Issue by rawde90** [iptv-org/iptv#17064]
### Broken Link

https://janus.tvturf.cl/playlist/stream.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
https://tvturf.cl/

https://tvturf4.janus.cl/playlist/stream.m3u8?d=w&id= +token

**Comment by BellezaEmporium** [comment]
@Sphinxroot try without adding anything next to id... ;)
