### ISSUE TITLE
Broken: Tu Kanal

### ISSUE THREAD

**Issue by rawde90** [iptv-org/iptv#17063]
### Broken Link

http://45.33.63.98/hls/abdi.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
https://tukanal.tv/en-vivo/

https://envivo.tukanal.tv/hls/abdi.m3u8

**Comment by freearhey** [comment]
http://45.33.63.98/hls/abdi.m3u8
<img width="792" alt="image" src="https://github.com/user-attachments/assets/592f0f88-c5f8-46f7-a8f5-ac045c67fcb5">
