### ISSUE TITLE
Add some more Tamil and Canadian channels!

### ISSUE THREAD

**Issue by AS27-pro** [iptv-org/iptv#1706]
Add some more Tamil and Canadian channels! For the Tamil channels add Sun tv, Vijay tv, Colours tamil, Zee tamil and Tamilone. For the Canadian channels add CP24, CTV, CITY tv, HGTV and Cottage Life. By the way, the Tamil channels are Indian.

**Comment by sathi2** [comment]
I am in agreement and also Colours tamil and Zee tamil channels
