### ISSUE TITLE
Broken: TeleOnce PR

### ISSUE THREAD

**Issue by luiski90** [iptv-org/iptv#17073]
### Broken Link

https://univision-live.cdn.vustreams.com/live/ce88b839-6376-4494-a2ee-83d66bc7cfc1/live.isml/ce88b839-6376-4494-a2ee-83d66bc7cfc1.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Remplazar por: https://player.restream.io/?token=4c57ad65917d4802a65ba18911e366cf 

Extraído de: https://cdn.teleonce.com/en-vivo/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by JaphyDoesGithub** [comment]
¿Creaste el enlace o fue directamente del sitio web oficial?

**Comment by JaphyDoesGithub** [comment]
Ahora esta offline, no es 24/7.

**Comment by JaphyDoesGithub** [comment]
> Ahora esta offline, no es 24/7.

Ahora esta online, no sé qué le pasa.

**Comment by JaphyDoesGithub** [comment]
no es 24/7

**Comment by luiski90** [comment]
Del sitio oficial del canal

**Comment by luiski90** [comment]
> ¿Creaste el enlace o fue directe del sitio web oficial?

Del sitio oficial del canal

**Comment by JaphyDoesGithub** [comment]
> > ¿Creaste el enlace o fue directe del sitio web oficial?
> 
> Del sitio oficial del canal

No funciona siempre y tiene token que significa que no va funcionar para siempre

**Comment by luiski90** [comment]
> > > ¿Creaste el enlace o fue directe del sitio web oficial?
> > 
> > 
> > Del sitio oficial del canal
> 
> No hay función siempre y tiene token que significa que no hay función para siempre

Ese link de transmisión creo que toca modificarlo en .m3u8, anteriormente había alguien aquí que modificaba los links de restream.io por eso lo compartí para ver si alguien lo podía modificar

**Comment by knglrk** [comment]
Encontré este enlace de vídeo buscando en el código web de Teleonce.com

Enlace : 

https://customer-gllhkkbamkskdl1p.cloudflarestream.com/eyJhbGciOiJSUzI1NiIsImtpZCI6ImI3YmIwODNmMDhkNmQ5NWExZjIzZWE3ZWRhOWY4NTZhIn0.eyJzdWIiOiJiNmNiYjcxMDFiMzZhZjVhMzU4MzY4OGJlNWFhZjkwNiIsImtpZCI6ImI3YmIwODNmMDhkNmQ5NWExZjIzZWE3ZWRhOWY4NTZhIiwiZXhwIjoxNzIyNjgxMTU2LCJhY2Nlc3NSdWxlcyI6W3sidHlwZSI6ImlwLmdlb2lwLmNvdW50cnkiLCJhY3Rpb24iOiJibG9jayIsImNvdW50cnkiOlsiUlUiLCJCWSJdfV19.hQT2Sv2C58TnFiU-J_QABnpz5GWIeu2Bd0gv-gJ3TbHnO2djfsRD2vk4VPIE4NeuNYzhyE8xYmEqoChWNpZ9QoZTLB3rR02Ae1O9yn6tnQtqYv_ZKP7kfGeBty1F6Z5GRaVKj2rUgYgVudHZ3snf9nEpcEilG7r-rraV8MLQJXWjsYmekf3lhxqj1rawlZtzouxqi8rtO9OCh8osWmMVC9nD3VIYXrZmPpjFhJ19uEwlvYPrrlB-YjnWa3uvv6Ye6TflOV6_ljdiwExsxPF1tf_GrtXw6bIhZ3yVD0M6rgiJ22FVRKWWP4KhRoGsJjVfLtomKnngUITqnLU7T4lTDQ/manifest/video.m3u8

el video funciona pero tienes que refrescar manualmente el stream cada vez que el canal cambia de programa.
