### ISSUE TITLE
Broken: Franceinfo [FR]

### ISSUE THREAD

**Issue by OlivierArgentieri** [iptv-org/iptv#17074]
### Broken Link

https://raw.githubusercontent.com/pshanmu3/dailymotion_to_m3u8/main/FranceInfo.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

I found this one as a replacement using github search syntax

https://raw.githubusercontent.com/LeBazarDeBryan/XTVZ_/main/Stream/Live/franceinfo.m3u8

But i don't think this match your requirements

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
https://live-b.cf.dmcdn.net/sec2(hVkhUwZJuGQQ-ULsq_NjRw_vq3DVRI58_madK4vkPbNpgjrgHL6gAaGai8xZ6DVlxsQLtLC8uC-Oz0AO98St4HvPaec5EtJTaf4nFzXW3pA)/dm/3/x4rdeu6/d/live-720.m3u8#cell=lcfb
```

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by km147** [comment]
This works: https://simulcast-p.ftven.fr/ZXhwPTE3MjIwODcwODB+YWNsPSUyZip+aG1hYz1mM2MwNGI4OGIwOWQ3ZjI2ZmYxODMwZTRhNDNlMWVmMjZlYmQ1ZDZhNGQ0M2EwYjI5YmNjMzk1YTE2MDA1YmZj/simulcast/France_Info/hls_monde_frinfo/index.m3u8?hdnea=exp=1722066080~acl=%2f*~hmac=b04f57d41ea16d59967f5d1111d14fe2e78d68dc699a18c13195f82e64fa83cb
