### ISSUE TITLE
METV streams Broken: 403 Forbidden 

### ISSUE THREAD

**Issue by TKList** [iptv-org/iptv#17078]
### Broken Link

https://d3m10mlzdolmch.cloudfront.net/v1/master/840a24ccd7c75076211d060179b3ad0c64fdc6ca/metv_nr_rt/ec1a82ca1e6b438daf35445bfbec9ad8/index.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by GuyInCanada** [comment]
yeah, looks like all the Frndly TV streams are down

side note, only the domain (d3m10mlzdolmch.cloudfront.net) was changed.

**Comment by Kevin-W-23** [comment]
Will the streams be back up in the near future? I cannot get MeTV Toons over the air so this was a great way to watch it
