### ISSUE TITLE
Add: Tempus Stream - Canal Meteorológico en México 

### ISSUE THREAD

**Issue by mediadesignpn** [iptv-org/iptv#17072]
### Channel ID (required)

TempusStream1

### Channel Name

Tempus Stream

### Stream URL (required)

https://video1.getstreamhosting.com:2000/tunein/8116/v/m3u8

### Quality

1080p

### Label

None

### HTTP Referrer

https://tempusstream.com

### Notes

Único canal enfocado a información Meteorológica en México, Pronósticos del tiempo de Coahuila, Nuevo León y Tamaulipas.

Mantente informado siempre sobre las condiciones del tiempo con nuestra señal.
https://tempusstream.com

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
A weather forecast channel para las ciudades de México.

**Comment by mediadesignpn** [comment]
Asi es, ahora por lo pronto es los estados de Coahuila, Nuevo Leon y Tamaulipas.

**Comment by mediadesignpn** [comment]
@R4IN2007 @tomer @rblopes Hola, disculpen se puede añadir el canal a su lista de favor.

**Comment by Plus018** [comment]
This is tempura stream

**Comment by Plus018** [comment]
This is tempura stream

**Comment by Plus018** [comment]
It’s tempura stream

**Comment by Plus018** [comment]
https://mdstrm.com/live-stream-playlist/60b578b060947317de7b57ac.m3u8

**Comment by Plus018** [comment]
Adn 40.

**Comment by Plus018** [comment]
https://d24sa4vr9gvjv.cloudfront.net/index.m3u8

**Comment by Plus018** [comment]
canal once

**Comment by R4IN2007** [comment]
^Off-Topic Not Related
