### ISSUE TITLE
Broken: MeTV Toons 403 error

### ISSUE THREAD

**Issue by Kevin-W-23** [iptv-org/iptv#17081]
### Broken Link

https://d3m10mlzdolmch.cloudfront.net/v1/master/840a24ccd7c75076211d060179b3ad0c64fdc6ca/metvplus_nr_rt/00ff704f1eef4845a59227cf31705a01/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

When I try to play MeTV Toons, it doesn't load at all despite it working yesterday. I get the error:

Your input can't be opened
VLC is unable to open the MRL 'https://d3m10mlzdolmch.cloudfront.net/v1/master/840a24ccd7c75076211d060179b3ad0c64fdc6ca/metvplus_nr_rt/00ff704f1eef4845a59227cf31705a01/index.m3u8'. 403 error

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ramazansancar** [comment]
Duplicate https://github.com/iptv-org/iptv/issues/17078

**Comment by Mrpickle30** [comment]
Will it be able to get a m3u8 again for me toons highly doubt it

**Comment by ramazansancar** [comment]
If you can provide the website of the broadcaster, I can find the broadcast link. @Mrpickle30

**Comment by Mrpickle30** [comment]
Yes I had those links I just wanted to know if there's a fresh one out there 

⁣Get BlueMail for Android ​
