### ISSUE TITLE
Add: srinsankara tv yupp tv free channel

### ISSUE THREAD

**Issue by TvK0d1** [iptv-org/iptv#17090]
### Channel ID (required)

https://www.yupptv.com/yupptvnew/channels/sri-sankara-tamil/live/embed

### Channel Name

Sri Sankara

### Stream URL (required)

https://y.codeautoplayserver1.workers.dev/?codeby=nd&channel=sri-sankara-kannada
### Quality

None

### Label

None

### Notes

@codeautoplay, Could you please be so kind as to build a .dev page for this channel as its a free channel but has time tokens?

Thanks

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by codeautoplay** [comment]
https://y.codeautoplayserver1.workers.dev/?codeby=nd&channel=sri-sankara-kannada

**Comment by TvK0d1** [comment]
> https://y.codeautoplayserver1.workers.dev/?codeby=nd&channel=sri-sankara-kannada

Thank you so much!

**Comment by TvK0d1** [comment]
HI, the links seem to no longer work. 

Could someone please fix this? in addition @codeautoplay seems to have disabled all the workers.dev pages he created got mutiple channels. 

thanks

**Comment by BellezaEmporium** [comment]
![image](https://github.com/user-attachments/assets/2ebfc690-abe7-4026-b2af-beec09196e1e)

**Comment by Brunisky14** [comment]
i need ric plus m3u
