### ISSUE TITLE
Broken: sports-cctv5+/cctv-5（1080p）/cctv-16（1080p）

### ISSUE THREAD

**Issue by LiveGhost** [iptv-org/iptv#17093]
### Broken Link

https://iptv-org.github.io/iptv/categories/sports.m3u

### What happened to the stream?

Constantly interrupts/lagging

### Notes (optional)

https://iptv-org.github.io/iptv/categories/sports.m3u
cctv5+/cctv-5（1080p）/cctv-16（1080p）can not play

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by tarra-ws** [comment]
Does it work now?

**Comment by tarra-ws** [comment]
It doesn't work right now

**Comment by LiveGhost** [comment]
> It doesn't work right now



> Does it work now?
No, it doesn't work.

**Comment by BellezaEmporium** [comment]
#17071

**Comment by Plus018** [comment]
Use iptv smart player to work

**Comment by Plus018** [comment]
And download that link

**Comment by Plus018** [comment]
and it will show if it’s wrong or not

**Comment by Plus018** [comment]
its on app store
