### ISSUE TITLE
Add: Longhorn Network

### ISSUE THREAD

**Issue by telanus** [iptv-org/iptv#17108]
### Channel ID (required)

LonghornNetwork.us

### Channel Name

Longhorn Network

### Stream URL (required)

https://dice-live-us.akamaized.net/hls/live/2026324/266392-274451/exchange266392hdeuz_266392_0-5572/chunklist.m3u8?hdntl=exp=1722450474~acl=%2f*~id=0bb4f726-732a-4483-a334-86de6e732ddc~data=hdntl,dWlkPW55bmhhSHwxODBmNGI5Yy1hYjM4LTRmMzgtOWJmOS04YTdmMDEyMGYzYjcmaXA9MTY5LjAuMTIuMjQmZXhwPTE3MjI0NTA1MDMmZWlkPTI2NjM5MiZjaWQ9ZGNlLmxvbmdob3JucyZvaWQ9MzY3~hmac=b116f13e185f872717a0a39d3784299f5f0a9eccf54ce11ef312911dc0d7a27a

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by InsolenceWillow** [comment]
That Stream Expires

**Comment by BellezaEmporium** [comment]
Wasn't the Longhorn Network cut after the PAC12 shutdown btw ?

**Comment by InsolenceWillow** [comment]
> Wasn't the Longhorn Network cut after the PAC12 shutdown btw ?

It's Was Actually ESPN That Got Rid Of The Program!
![Screenshot_20240730-162828_kindlephoto-14366803](https://github.com/user-attachments/assets/291d5d78-5fd1-4f60-b157-5398804267c2)

**Comment by R4IN2007** [comment]
Longhorn became a streaming service with live 24/7 streaming channel still owned by ESPN.
Channel won't be on cable anymore.

https://watch.longhornnetwork.com/home
• Longhorn Network
• Longhorn 24/7

**Comment by R4IN2007** [comment]
This might be its streaming service channel LHN 24/7
https://watch.longhornnetwork.com/live/266392.
