### ISSUE TITLE
Add: 

### ISSUE THREAD

**Issue by diegogaitanmerkas** [iptv-org/iptv#17106]
### Channel ID (required)

CanalDos.co

### Channel Name

Canal Dos

### Stream URL (required)

http://131.221.41.94/hls/canal2.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Resolved IP http://streaming.cableytv.com/hls/canal2.m3u8
