### ISSUE TITLE
Broken: IRIB TV1, IRIB TV2, IRIB TV3 Is Broken Link...

### ISSUE THREAD

**Issue by Arya165** [iptv-org/iptv#17109]
### Broken Link

https://iptv-org.github.io/iptv/countries/ir.m3u

### What happened to the stream?

Not loading

### Notes (optional)

Maybe you can try this link below... Who knows can be penetrated by using VLC
https://tv1.ir/live = IRIB TV1
https://sepehrtv.ir/live/tv2 = IRIB TV2
https://sepehrtv.ir/live/tv3 = IRIB TV3 (But only in the country of Iran)

I've tried the old link (the one above) it but still can't.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
They've secured all of their links with a token.

As an example, to check IRIB TV1, you need to go to https://sepehrapi.sepehrtv.ir/v3/channels/?key=tv1&include_media_resources=true&include_details=true

You need an authorization which is basically... an OAuth token based on the computer (HMAC hash).

**Comment by arash12100** [comment]
Please the broken link for Iran International and Persiana Nostalgia
