### ISSUE TITLE
Broken: TV3, TV9, TV8 and Tv Okey Malaysia is Broken and Not Streamed in VLC

### ISSUE THREAD

**Issue by Arya165** [iptv-org/iptv#17110]
### Broken Link

https://iptv-org.github.io/iptv/countries/my.m3u

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
Tv9 in

**Comment by Plus018** [comment]
Tv9 works
