### ISSUE TITLE
Broken: AdriaMusicTelevision.de and possibly other streams from cdne.folxplay.tv

### ISSUE THREAD

**Issue by pr0nitcheff** [iptv-org/iptv#17115]
### Broken Link

https://cdne.folxplay.tv/folx-trz/streams/ch-1/master.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

I detected a couple of broken streams while browsing through the de.m3u playlist.
At the moment at least two of the streams hosted by https://cdne.folxplay.tv/ fail to load (access from Germany, possibly geo-blocked?) with VLC media player. When trying to start the stream VLC displays a "system error". 
Streamtest.in confirmed the links to be offline(screenshot below).
![grafik](https://github.com/user-attachments/assets/4352e2c1-e380-4364-8905-76bb1939ce96)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
Now use IPTV smart pro app in App Store it will work because it’s online.

**Comment by Plus018** [comment]
Iptv smart player.
