### ISSUE TITLE
Broken: National Geographic Finland

### ISSUE THREAD

**Issue by gitr656** [iptv-org/iptv#17114]
### Broken Link

https://live-fi.tvkaista.net/national-geographic/live.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Stream works if it is opened with https://live-fi.tvkaista.net/national-geographic/live.m3u8?src=videojs

Channel ID : NationalGeographic.fi

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
@TVKaista might answer that inquiry.

**Comment by mamosa14** [comment]
Try This 
https://live-fi.tvkaista.net/national-geographic/live.m3u8?src=videojs&timestamp=2024-08-05-18-47

**Comment by Plus018** [comment]
That comment is right u can watch

**Comment by Plus018** [comment]
Go watch
