### ISSUE TITLE
Add: arte.fr

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#17116]
### Channel ID (required)

arte.fr

### Channel Name

Arte

### Stream URL (required)

https://artesimulcast.akamaized.net/hls/live/2031003/artelive_fr/index.m3u8

### Quality

720p

### Label

Geo-blocked

### Notes

from https://github.com/iptv-org/iptv/pull/17112/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Can confirm it works for France.

**Comment by BellezaEmporium** [comment]
![image](https://github.com/user-attachments/assets/16d3049b-ade0-46e1-97d7-efa2b9d57ae1)

**Comment by Aksel1984** [comment]
#EXTM3U

#EXTINF:-1 group-title="Info FR" tvg-name="Euronews (FR)",Euronews (FR)
https://viamotionhsi.netplus.ch/live/eds/euronews/browser-HLS8/euronews.m3u8

#EXTINF:-1 group-title="Institutionnel FR" tvg-name="Assemblée nationale (Direct)",Assemblée nationale (Direct)
http://assemblee-nationale.akamaized.net/live/live36/stream36.m3u8

#EXTINF:-1 group-title="Monaco / FR" tvg-name="Monaco Info",Monaco Info
https://webtvmonacoinfo.mc/live/prod_720/index.m3u8

#EXTINF:-1 group-title="Culture / FR" tvg-name="ARTE (FR)",ARTE (FR)
https://artesimulcast.akamaized.net/hls/live/2031003/artelive_fr/index.m3u8
