### ISSUE TITLE
Add: Disney Channel Poland

### ISSUE THREAD

**Issue by MavijaviGit** [iptv-org/iptv#17124]
### Channel ID (required)

DisneyChannel.pl

### Channel Name

Disney Channel Poland

### Stream URL (required)

http://109.233.89.170/Disney_Channel/mono.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by michryd-ip** [comment]
Not work
