### ISSUE TITLE
Broken: eNews Channel Africa

### ISSUE THREAD

**Issue by telanus** [iptv-org/iptv#17136]
### Broken Link

http://185.59.221.131:8081/live/enca/playlist.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
Fixed

**Comment by telanus** [comment]
> Fixed

VLC is unable to open the MRL 'http://185.59.221.131:8081/live/enca/playlist.m3u8'. Check the log for details.

**Comment by telanus** [comment]
> Hey it’s fixed go watch

Still a no-show for me. And running the link in Firefox says forbidden 🙈

**Comment by Plus018** [comment]
Safari

**Comment by Plus018** [comment]
Works

**Comment by telanus** [comment]
Tested it with Streamtest, and it also says off-line

**Comment by Plus018** [comment]
No streamtest in said online

**Comment by sunyuanzhe** [comment]
i've tested all streams under the host http://185.59.221.131:8081 which is all says access is forbidden
