### ISSUE TITLE
Add: ERTU 1

### ISSUE THREAD

**Issue by MohamedAsaad1** [iptv-org/iptv#17131]
### Channel ID (required)

ERTU1.eg

### Channel Name

ERTU 1

### Stream URL (required)

https://www.dailymotion.com/cdn/live/video/x856hbh.m3u8?sec=9vSsiUOJ8a7kbWMNXFepsEe6r3dHhC2Tchb059y_ozBph6e6_uynPzMGwE7jFfTJ&dmTs=564260&dmV1st=34048c79-30a8-4360-a956-3e718b976feb

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Tokenized.
