### ISSUE TITLE
Please add more Tamil channels!

### ISSUE THREAD

**Issue by AS27-pro** [iptv-org/iptv#1715]
**Country of the channel:**
India
**Channel Name:**
Sun tv, Vijay TV/Star Vijay, Colours Tamil, Zee tamil and Tamilone. 
**Channel Language:**
Tamil

There are some links for Tamil channels on these websites: https://indo24live.blogspot.com/2019/02/tv.html?m=1 and https://gist.github.com/virajkanwade/2f8506fee2857a71dca9.

**Comment by Ragaven007** [comment]
All links are dead bro.
