### ISSUE TITLE
Add: Starz East (US)

### ISSUE THREAD

**Issue by boogabooga841** [iptv-org/iptv#17153]
### Channel ID (required)

StarzEast.us

### Channel Name

Starz East

### Stream URL (required)

http://fl2.moveonjoy.com/STARZ/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
You forgot the other STARZ channels the encore ones.

**Comment by ILIKECATS187** [comment]
I suggest you keep those for yourself and even delete them has it will just bring heat onto this repo which I REPEAT IS RESERVED FOR FREE TO AIR CHANNELS ONLY ... dunno how all these new members are posting Piracy now but it use to be not allowed for YEARS on here and now few bad apples are burning all the links here
