### ISSUE TITLE
Add: MGM+ Hits East (US)

### ISSUE THREAD

**Issue by boogabooga841** [iptv-org/iptv#17164]
### Channel ID (required)

MGMPlusHitsEast.us

### Channel Name

MGM+ Hits East

### Stream URL (required)

http://fl2.moveonjoy.com/EPIX_HITS/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ctiptv** [comment]
This is actually MGM+ Hits.

**Comment by halfrun** [comment]
http://fl6.moveonjoy.com/NFL_2/index.m3u8

**Comment by R4IN2007** [comment]
ESPN CHANNELS?

**Comment by ctiptv** [comment]
Looks like NFL GamePass on DAZN, but I'm not sure.

**Comment by R4IN2007** [comment]
> http://fl6.moveonjoy.com/NFL_2/index.m3u8

Link don't work

**Comment by ctiptv** [comment]
It did last night during the Football game.

**Comment by R4IN2007** [comment]
> It did last night during the Football game.

Link works now maybe it just always works when football games doing on.
![Screenshot_20240810_144416_Chrome](https://github.com/user-attachments/assets/a5db4143-a091-47c1-9311-9c099a2533af)

**Comment by ctiptv** [comment]
I'm not sure what those channels are. Earlier they covered a couple of the NFL games. There is a few football games on now and they have 2 different baseball games on and a few of the NFL network.

**Comment by ctiptv** [comment]
Correction, 9 is showing the Bengals game.

**Comment by R4IN2007** [comment]
> Correction, 9 is showing the Bengals game.

It's has 9 Different Channels some are restreming the games.

NFL_1 -
NFL_2 -
NFL_3 - FOX5 Atlanta, GA (WAGA-DT1)
NFL_4 - NFL Network [NO AUDIO]
NFL_5 -
NFL_6 -
NFL_7 -
NFL_8 - NFL Network [With Audio]
NFL_9 -

**Comment by ctiptv** [comment]
It is up to 15 right now with a couple not working. I've checked up to 20.

11 - Event hasn't started yet

14 - Event hasn't started yet

15 - CTV (960x540)

**Comment by R4IN2007** [comment]
Any similar ones for NBA or MLB?

**Comment by ctiptv** [comment]
I didn't know about those. The NFL channels were showing 2 different Baseball games earlier.

**Comment by R4IN2007** [comment]
Maybe there all connected together

**Comment by ctiptv** [comment]
Probably. Let me know if you find the regular ESPN or SEC Network. Those 2 have died for me.

**Comment by R4IN2007** [comment]
> Any similar ones for NBA or MLB? Nevermind, Found Them. MLB_1 - TBS MLB_2 - MLB_3 - TBS https://fl2.moveonjoy.com/MLB_3/index.m3u8

NBA_1 - NBC 4 New York, NY (WNBC-DT1)
NBA_2 -
NBA_3 - 
NBA_4 -
NBA_5 -
NBA_6 - 
NBA_7 - Sling NBA League Pass
NBA_8 -
NBA_9 -
NBA_10 -
NBA_11 -
NBA_12 - Event has not started yet, Stay tuned
NBA_13 - 
NBA_14 -
NBA_15 -
https://fl5.moveonjoy.com/NBA_1/index.m3u8

**Comment by R4IN2007** [comment]
> Probably. Let me know if you find the regular ESPN or SEC Network. Those 2 have died for me.

I remembered this version of ESPN but I feel like this one won't work neither.
http://143.244.60.30/ESPN/manifest.m3u8

**Comment by ctiptv** [comment]
Yea, it's dead. Must have been the same source as the one fl2 was using. They both died at the same time. I'm still looking.

**Comment by R4IN2007** [comment]
Yea I think all the ones that hosted ESPN are dead especially there was one that wasn't even leaked & tokened and its also down. It was two 2 that I had.

**Comment by ctiptv** [comment]
Do you have the Canadian Sports channels? Is there a way to send direct messages on here? I have some things you might not.

**Comment by R4IN2007** [comment]
> Do you have the Canadian Sports channels? Is there a way to send direct messages on here? I have some things you might not.

The only ones will be TSN. Not SportsNets Ontario.

**Comment by halfrun** [comment]
MOVIES
#EXTINF:-1 tvg-id="CRAVE.ca" tvg-name="CRAVE 2"
http://fl2.moveonjoy.com/CRAVE_2/index.m3u8
#EXTINF:-1 tvg-id="CRAVE.ca" tvg-name="CRAVE 3"
http://fl3.moveonjoy.com/CRAVE_3/index.m3u8
#EXTINF:-1 tvg-id="CRAVE.ca" tvg-name="CRAVE 4"
http://fl2.moveonjoy.com/CRAVE_4/index.m3u8

**Comment by ctiptv** [comment]
I watched a little Baseball today.

1 - TBS (Shows MLB Games on Tuesdays)
http://fl2.moveonjoy.com/MLB_1/index.m3u8
http://fl4.moveonjoy.com/MLB_1/index.m3u8

2 - FS1 (MLB on FOX)
http://fl2.moveonjoy.com/MLB_2/index.m3u8
http://fl4.moveonjoy.com/MLB_2/index.m3u8

3 - TBS (Shows MLB Games on Tuesdays)
http://fl2.moveonjoy.com/MLB_3/index.m3u8
http://fl4.moveonjoy.com/MLB_3/index.m3u8

4 - No hits - I believe to be MLB Extra Innings
http://fl2.moveonjoy.com/MLB_4/index.m3u8
http://fl4.moveonjoy.com/MLB_4/index.m3u8

5 - No hits - I believe to be MLB Extra Innings
http://fl2.moveonjoy.com/MLB_5/index.m3u8
http://fl4.moveonjoy.com/MLB_5/index.m3u8

6 - MLB Extra Innings
http://fl2.moveonjoy.com/MLB_6/index.m3u8
http://fl4.moveonjoy.com/MLB_6/index.m3u8

7 - MLB Extra Innings
http://fl2.moveonjoy.com/MLB_7/index.m3u8
http://fl4.moveonjoy.com/MLB_7/index.m3u8

8 - MLB Extra Innings
http://fl2.moveonjoy.com/MLB_8/index.m3u8
http://fl4.moveonjoy.com/MLB_8/index.m3u8

9 - MLB Extra Innings
http://fl2.moveonjoy.com/MLB_9/index.m3u8
http://fl4.moveonjoy.com/MLB_9/index.m3u8

10 - MLB Extra Innings
http://fl2.moveonjoy.com/MLB_10/index.m3u8
http://fl4.moveonjoy.com/MLB_10/index.m3u8

11 - MLB Extra Innings
http://fl2.moveonjoy.com/MLB_11/index.m3u8
http://fl4.moveonjoy.com/MLB_11/index.m3u8

12 - No hits - I believe to be MLB Extra Innings
http://fl2.moveonjoy.com/MLB_12/index.m3u8
http://fl4.moveonjoy.com/MLB_12/index.m3u8

13 - No hits - I believe to be MLB Extra Innings
http://fl2.moveonjoy.com/MLB_13/index.m3u8
http://fl4.moveonjoy.com/MLB_13/index.m3u8

14 - MLB Extra Innings
http://fl2.moveonjoy.com/MLB_14/index.m3u8
http://fl4.moveonjoy.com/MLB_14/index.m3u8

15 - MLB Extra Innings
http://fl2.moveonjoy.com/MLB_15/index.m3u8
http://fl4.moveonjoy.com/MLB_15/index.m3u8

16  -  NO HITS YET
http://fl2.moveonjoy.com/MLB_16/index.m3u8
http://fl4.moveonjoy.com/MLB_16/index.m3u8


NFL 1 & 2 are DAZN. Showed both NFL Games today.

**Comment by ILIKECATS187** [comment]
I suggest you keep those for yourself and even delete them has it will just bring heat onto this repo which I REPEAT IS RESERVED FOR FREE TO AIR CHANNELS ONLY ... dunno how all these new members are posting Piracy now but it use to be not allowed for YEARS on here and now few bad apples are burning all the links here

**Comment by R4IN2007** [comment]
> I suggest you keep those for yourself and even delete them has it will just bring heat onto this repo which I REPEAT IS RESERVED FOR FREE TO AIR CHANNELS ONLY ... dunno how all these new members are posting Piracy now but it use to be not allowed for YEARS on here and now few bad apples are burning all the links here

People like sharing these types of urls and don't know that these shouldn't be leaked.

**Comment by spotanjo3** [comment]
And found that MGM+ HITS

https://fl2.moveonjoy.com/EPIX_2/index.m3u8 and https://fl2.moveonjoy.com/EPIX_HITS/index.m3u8 are the same links 


Where is actually EPIX 2 correct link ? MGM+ HITS (EPIX 2) link is missing
