### ISSUE TITLE
Please add more Canadian channels!

### ISSUE THREAD

**Issue by AS27-pro** [iptv-org/iptv#1716]
**Country of the channel:**
Canada 
**Channel Name:**
CP24, CTV, CITYTV, HGTV and Cottage Life.
**Channel Language:**
English

**Comment by freearhey** [comment]
HGTV could not be added to the playlist due to claims of the copyright holder. More details here: #1831

**Comment by freearhey** [comment]
Closed in favor #1941

**Comment by Brunisky14** [comment]
@freearhey can i tfo quebec m3u8 please?

**Comment by freearhey** [comment]
@Brunisky14 I can't help you with that.
