### ISSUE TITLE
Add: MGM+ Marquee (US)

### ISSUE THREAD

**Issue by boogabooga841** [iptv-org/iptv#17163]
### Channel ID (required)

MGMPlusMarquee.us

### Channel Name

MGM+ Marquee

### Stream URL (required)

http://fl2.moveonjoy.com/EPIX_DRIVE_IN/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ctiptv** [comment]
This is actually MGM+ Marquee. You probably shouldn't be posting these streams in public. Just my opinion...

**Comment by plissken1138** [comment]
this link is now streaming "the grio"... channel I guess

**Comment by ctiptv** [comment]
It's the right channel. Showing Bull Durham right now. Very choppy now for me.

**Comment by plissken1138** [comment]
> It's the right channel. Showing Bull Durham right now. Very choppy now for me.

this is what i'm getting

![image](https://github.com/user-attachments/assets/8e788937-f36c-48c2-93e6-689226e28cee)

bull durham was on the link added as MGM+ Hits East, which is in fact MGM+ Marquee

**Comment by spotanjo3** [comment]
MGM+ Marquee USA link please?
