### ISSUE TITLE
Buffering 

### ISSUE THREAD

**Issue by arminhammer12** [iptv-org/iptv#1718]
**What's wrong?** every 1 min or two the channel buffers

**Country of the channel:** all channels from this link "https://iptv-org.github.io/iptv/index.m3u"

**Channel Name:** all channels 

**Broken Link:**

**Additional Information (optional):**

Every channel every source channels buffer, otherwise no issues.

**Comment by exodiver** [comment]
Sir, I think you better be specific with which channels is buffering.

**Comment by arminhammer12** [comment]
CNN, Disney Channel, ESPN, FXX movie Channel, Hallmark etc. I can attach a video of me switching channels and all of them buffer after 1-2 mins of watching.

My internet connect is not an issue because I have 1000mbps upload and download.

-Armin Ibrahimovic

On Sep 5, 2020, at 9:49 PM, Claypot_King <notifications@github.com> wrote:

﻿

Sir, I think you better be specific with which channels is buffering.

**Comment by exodiver** [comment]
Please upload the video.

**Comment by arminhammer12** [comment]
Please use this link to view the video, 
https://share.icloud.com/photos/0jKbGD7rtqAYvvNYszKaI-qqQ#Harrisonburg

**Comment by exodiver** [comment]
Might you want to share us a screenshoot of the url of playlist you are using? 

I don't think that there is a FXM channel streaming link being shared in this page, at the present moment. 

In the past, there was one that was shared but that was the thailand edition, which was not a very good link as it has a pretty low number of connection allowed (taken from a pirated IPTV site)

**Comment by arminhammer12** [comment]
I am using this url, 
https://iptv-org.github.io/iptv/countries/us.m3u
--

**Comment by freearhey** [comment]
@arminhammer12 Please provide the name of the specific channel that is not working and the player you are using so we can help you.
