### ISSUE TITLE
Add: DMC Egypt

### ISSUE THREAD

**Issue by ussr2020** [iptv-org/iptv#17186]
### Channel ID (required)

DMC.eg

### Channel Name

DMC

### Stream URL (required)

https://freechannelsonly.xyz:2083/live/u7JewhWwuWkS/BRBRyWDNUEr6/20.m3u8

### Quality

None

### Label

None

### Notes

Not Geoblocked But can work better in countries more than others.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by GuyInCanada** [comment]
Xtream codes aren't allowed.

**Comment by ussr2020** [comment]
> Xtream codes aren't allowed.

Oh my bad
