### ISSUE TITLE
Broken: News Malayalam 24/7

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#17196]
### Broken Link

https://ythls.armelin.one/channel/UCXp6JTdq7-WwBK09S7SzmxQ.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

The channel started new live streaming on youtube with a new youtube channel. attaching the new youtube channel live streaming link below.

https://www.youtube.com/watch?v=_3qmC6X7loE

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
I don't like the new concept, looks like they want to change links often

**Comment by Sphinxroot** [comment]
https://ythls.armelin.one/channel/UCJ9kujSGs8dQE6_pjOggSZQ.m3u8

**Comment by Manipulativemachan** [comment]
Yes.
 
> strange behavior no live is visible on channel https://www.youtube.com/channel/UCJ9kujSGs8dQE6_pjOggSZQ/live

But channel is working on this website. https://newsmalayalam.com/videos/live

**Comment by R4IN2007** [comment]
> https://ythls.armelin.one/channel/UCJ9kujSGs8dQE6_pjOggSZQ.m3u8
> 
> strange behavior no live is visible on channel https://www.youtube.com/channel/UCJ9kujSGs8dQE6_pjOggSZQ/live

https://ythls.armelin.one/video/_3qmC6X7loE.m3u8

**Comment by Alstruit** [comment]
[This reference might be helpful.](https://github.com/abskmj/youtube-hls-m3u8?tab=readme-ov-file#for-a-youtube-channel)

**Comment by R4IN2007** [comment]
Channel isn't live

**Comment by Manipulativemachan** [comment]
Not working again. All youtbe hls are not working.

**Comment by Dum4G** [comment]
![image](https://github.com/user-attachments/assets/10c15163-3f69-4623-be03-9a6798a92d9f)
