### ISSUE TITLE
Add this Channels Please 

### ISSUE THREAD

**Issue by leXx1414** [iptv-org/iptv#1720]
**Country of the channel:** USA

**Channel Name:** Discovery channel, Fox, HBO, The CW, National Geographic 

**Channel Language:** English 

**Additional Information (optional):** Can you Add This channels ? I'm looking forward to your actions

**Comment by boxnurman** [comment]
Can you Add This channels ?
#EXTINF:-1 tvg-id="fatwatv.id" tvg-name="Fatwa TV" tvg-language="Indonesian" tvg-logo="https://dewanfatwa.com/wp-content/uploads/tumb-Fatwa.png" group-title="Religious",Fatwa TV
http://e1.dewanfatwa.com/fatwa1.m3u8

#EXTINF:-1 tvg-id="fatwatv.id" tvg-name="Fatwa TV" tvg-language="Indonesian" tvg-logo="https://dewanfatwa.com/wp-content/uploads/tumb-Fatwa.png" tvg-country="ID" group-title="Religious",Fatwa TV
http://e1.dewanfatwa.com/fatwa1.m3u8

**Comment by DUVVI** [comment]
indian TELUGU channels please

**Comment by themak1985** [comment]
See #1831 for more information.
