### ISSUE TITLE
Add: WBIR 10 Knoxville News

### ISSUE THREAD

**Issue by ctiptv** [iptv-org/iptv#17211]
### Channel ID (required)

WBIRDT1.us

### Stream URL (required)

https://livevideo01.wbir.com/hls/live/2016515/elvs/live.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ki4nhs** [comment]
That is the 24 hr wbir news 2 channel not the dt wbir
