### ISSUE TITLE
Add: it.m3u

### ISSUE THREAD

**Issue by paoloandrea** [iptv-org/iptv#17236]
### Channel ID (required)

it.m3u

### Channel Name

Italian Channels

### Stream URL (required)

https://github.com/Tundrak/IPTV-Italia/blob/main/iptvitaplus.m3u

### Quality

None

### Label

Geo-blocked

### Notes

Here a good number of works channel
https://github.com/Tundrak/IPTV-Italia/blob/main/iptvitaplus.m3u

Can update che it.m3u?

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Please make a PR instead and follow the contributing guide.
