### ISSUE TITLE
Add: Top Gear (IT)

### ISSUE THREAD

**Issue by mirctendo** [iptv-org/iptv#17245]
### Channel ID (required)

PlutoTVTopGear.it

### Channel Name

Pluto TV Top Gear

### Stream URL (required)

https://stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/64c109a4798def0008a6e03e/master.m3u8?advertisingId={PSID}&appVersion=unknown&deviceDNT={TARGETOPT}&deviceId={PSID}&deviceLat=0&deviceLon=0&deviceMake=samsung&deviceModel=samsung&deviceType=samsung-tvplus&deviceVersion=unknown&embedPartner=samsung-tvplus&profileFloor=&profileLimit=&samsung_app_domain={APP_DOMAIN}&samsung_app_name={APP_NAME}&us_privacy=1YNY

### Quality

None

### Label

None

### HTTP Referrer

https://pluto.tv/it/live-tv/64c109a4798def0008a6e03e

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
Fixed

**Comment by Dum4G** [comment]
@ProPontifex @Carlinhos027 not in db yet

**Comment by Dum4G** [comment]
Not in DB. Please make a request here https://github.com/iptv-org/database/issues/new?assignees=&labels=channels%3Aadd&projects=&template=__channels_add.yml&title=Add%3A+
