### ISSUE TITLE
Add: WVCU-LP 97.7

### ISSUE THREAD

**Issue by jayc3-cmyk** [iptv-org/iptv#17259]
### Channel ID (required)

WVCULP.us

### Channel Name

WVCU-LP Concord University Radio The Cure 97.7

### Stream URL (required)

https://video1.getstreamhosting.com:1936/8152/8152/playlist.m3u8

### Quality

1080p

### Label

None

### Timeshift

0

### HTTP User Agent

None

### HTTP Referrer

None

### Notes

WVCU-LP is a variety radio station on 97.7 FM broadcasting from the top of Concord University in Mercer County, West Virginia.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
No sound coming

**Comment by R4IN2007** [comment]
> No sound coming

There's is sound

**Comment by ProPontifex** [comment]
Just added a database entry for this

**Comment by jayc3-cmyk** [comment]
If https://video1.getstreamhosting.com:1936/8152/8152/chunklist_w1338928393.m3u8 doesn't work, idk what will.
