### ISSUE TITLE
Broken: Channels from a063 to a06t don't work on PL playlist

### ISSUE THREAD

**Issue by ithobbistpl** [iptv-org/iptv#17251]
### Broken Link

http://185.236.229.62:9981/play/a06j

### What happened to the stream?

Not loading

### Notes (optional)

So yes, I thought that after a06j, my fav channel didn't worked today, it could be whole a06 category of channels that doesn't work. Apparently no. TVNs work, a060-a062 channels work as well. No idea why is it like that. Pls fix it asap if possible. 

PS: please guys consider separate playlist for people with slower than 1mbps internet, because I've realized recently that these days may be back for me for a while. Y'know, 1024x576 + 1mbps bitrate copies. If that will be too big for 1mbps, then drop to 480p or consider hevc/av1 codec, if it's even possible to stream in that through VLC. But that's just idea.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
![image](https://github.com/user-attachments/assets/d378b157-3764-4d84-9295-fe2237403420)
works now
