### ISSUE TITLE
Broken: Newsmax TV (US)

### ISSUE THREAD

**Issue by boogabooga841** [iptv-org/iptv#17252]
### Broken Link

https://newsmax.codeautoplaycdn2.workers.dev/

### What happened to the stream?

Not loading

### Notes (optional)

codeautoplay streams as it was with fox news channel stop working closer to the middle of the day due to a large number of requests to cloudflare worker
![Screenshot_20240814-223025_Chrome](https://github.com/user-attachments/assets/d966709e-4824-461b-add0-a184ad3949a0)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
It’s now fixed u can go.

**Comment by Plus018** [comment]
Go watch here without glitching https://nmxlive.akamaized.net/hls/live/529965/Live_1/index.m3u8

**Comment by Plus018** [comment]
Well I helped?

**Comment by Plus018** [comment]
So maybe when u click ur link u posted it. Works install iptv smart player in app store
