### ISSUE TITLE
Broken: CNBC (US)

### ISSUE THREAD

**Issue by boogabooga841** [iptv-org/iptv#17254]
### Broken Link

http://fl3.moveonjoy.com/CNBC/index.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by xamjunk** [comment]
Hello.I have confirmed that the link was reactivated before it was removed 3 weeks ago.
Please reactivate it.
