### ISSUE TITLE
MBC group stopped working- thank you guys

### ISSUE THREAD

**Issue by hfareh-tv** [iptv-org/iptv#1726]
**What's wrong?**
MBC channels all stopped working except mbc3
**Country of the channel:**
Soudi Arabia
**Channel Name:**
MBC1, MBC2, MB3, MBC4, MBC5, MBC Action, MBC Drama.
**Broken Link:**

**Additional Information (optional):**
It was working until yesterday.

**Comment by aliali1983** [comment]
How do I get the link of MBC channels

**Comment by x5engine** [comment]
What's happening?why?
