### ISSUE TITLE
Broken: Czech stations - CT1, CT2, etc

### ISSUE THREAD

**Issue by gregbert42** [iptv-org/iptv#17263]
### Broken Link

http://88.212.7.10/live/test_ct1_25p/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

All the main czech stations appear to be broken.
IP address appears down

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
Ok that’s correct u need another one

**Comment by Plus018** [comment]
Try something that is different

**Comment by gregbert42** [comment]
> Try something that is different

Not sure what you are suggesting. My other streams work fine. This is the one that doesn’t. And there are no alternatives that I know about.

**Comment by werimail** [comment]
Hi guys, by playing around with the IP address I found out that the streams can be accessed with the following (small) change: Replace the first part `http://88.212.7.10/...` with `http:/ /88.212.7.11/...` then the streams should run again. At least it worked for me. Please try it out and give a short feedback.

Thanks and greetings Weri

**Comment by gregbert42** [comment]
> Hi guys, by playing around with the IP address I found out that the streams can be accessed with the following (small) change: Replace the first part `http://88.212.7.10/...` with `http:/ /88.212.7.11/...` then the streams should run again. At least it worked for me. Please try it out and give a short feedback.
> 
> Thanks and greetings Weri

I appreciate the suggestion - but it didnt work for me. same problem.
e.g., http://88.212.7.11/live/test_ct1_25p/playlist.m3u8

Any chance that these are just being geoblocked?

**Comment by Goldiefresh** [comment]
> > Hi guys, by playing around with the IP address I found out that the streams can be accessed with the following (small) change: Replace the first part `http://88.212.7.10/...` with `http:/ /88.212.7.11/...` then the streams should run again. At least it worked for me. Please try it out and give a short feedback.
> > Thanks and greetings Weri
> 
> I appreciate the suggestion - but it didnt work for me. same problem. e.g., http://88.212.7.11/live/test_ct1_25p/playlist.m3u8
> 
> Any chance that these are just being geoblocked?

I can confirm ip change works in m3u player but not on chrome browser same as old link. Tested CT sport and also rtvs sport Slovakia and working perfect.

**Comment by Plus018** [comment]
10 and 11 doesn’t work

**Comment by gregbert42** [comment]
> > > Hi guys, by playing around with the IP address I found out that the streams can be accessed with the following (small) change: Replace the first part `http://88.212.7.10/...` with `http:/ /88.212.7.11/...` then the streams should run again. At least it worked for me. Please try it out and give a short feedback.
> > > Thanks and greetings Weri
> > 
> > 
> > I appreciate the suggestion - but it didnt work for me. same problem. e.g., http://88.212.7.11/live/test_ct1_25p/playlist.m3u8
> > Any chance that these are just being geoblocked?
> 
> I can confirm ip change works in m3u player but not on chrome browser same as old link. Tested CT sport and also rtvs sport Slovakia and working perfect.

I can confirm that: "http://88.212.7.11/live/test_ctsport_25p/playlist.m3u8" does not work for me in VLC, whereas channels that do not rely on 88.212.7.x do work.

I am located on the east coast of the US.

**Comment by Plus018** [comment]
It works

**Comment by Plus018** [comment]
It works just the sound not the screen I think http://88.212.7.10/live/test_ct1_25p/playlist.m3u8

**Comment by Plus018** [comment]
http://88.212.7.11/live/test_ct1_25p/playlist.m3u8 It’s works just a sound

**Comment by Plus018** [comment]
http://88.212.7.11/live/test_ct2_25p/playlist.m3u8

**Comment by Plus018** [comment]
It works just a sound

**Comment by gregbert42** [comment]
@Plus018  - it would be great if you can offer more information. It works in what app? Where are you located roughly (country)? And it would also be great if you could respond in one comment vs a bunch of serial comments.

here is what i discovered:
I can wget "http://88.212.7.11/live/test_ct2_25p/playlist.m3u8" and get the playlist
I can then open that file, and get the 12345678.ts list (obviously the exact file changes over time)
then I can wget "http://88.212.7.11/live/test_ct2_25p/12345678.ts" to get the TS file, and I can play the TS file in vlc - but its only a short clip

what does NOT work:

Using VLC to open a network stream and directly play either:
http://88.212.7.11/live/test_ct2_25p/playlist.m3u8
or
http://88.212.7.11/live/test_ct2_25p/12345678.ts

It also does not work on channels-dvr to modify the file to reference 88.212.7.11 instead of 88.212.7.10

@Goldiefresh  - you mentioned that it works in m3u player. I am not sure what app this is. I've just been using VLC.

**Comment by Plus018** [comment]
Update the cz m3u

**Comment by BellezaEmporium** [comment]
change the IP to 88.212.15.27

**Comment by Plus018** [comment]
http://88.212.15.27/live/test_ct1_25p/playlist.m3u8

**Comment by Plus018** [comment]
http://88.212.15.27/live/test_ct2_25p/playlist.m3u8

**Comment by Plus018** [comment]
https://apps.apple.com/us/app/iptv-smarters-xtream-iptv/id1573898785

**Comment by Plus018** [comment]
http://88.212.15.27/live/test_Ct_Sport_25p/playlist.m3u8

**Comment by Plus018** [comment]
http://88.212.7.11/live/test_ctsport_25p/playlist.m3u8

**Comment by Plus018** [comment]
http://88.212.15.27/live/test_ct24_hevc/playlist.m3u8

**Comment by gregbert42** [comment]
@BellezaEmporium  @Alstruit  - all that was "fixed" was just removing the streams, rather than changing the IP address as per above. I dont think this is what was intended.
