### ISSUE TITLE
Broken: TV Canaria

### ISSUE THREAD

**Issue by joaquinito2070** [iptv-org/iptv#17264]
### Broken Link

https://streaming.noumm.es/noumm_live/televisioncanaria/master.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Not working anymore.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Somewhere in there : https://cdnapi.codev8.net/apicloud/v1.0/public/iframe/8d417032-64cb-4f1e-9042-c97e05501eed

Tokenized.

**Comment by Plus018** [comment]
No sorry but it’s a shutdown

**Comment by Plus018** [comment]
We found it here go watch https://ythls.armelin.one/channel/UCTQrUTmzCWIfG6h4EVCdOCQ.m3u8

**Comment by Alstruit** [comment]
Requires Header:
"https://cdnapi.codev8.net/"
