### ISSUE TITLE
BFMTV (Vertical)

### ISSUE THREAD

**Issue by cheznewa** [iptv-org/iptv#1727]
**Country of the channel:**
France

**Channel Name:**
BFMTV

**Channel ID:**
BFMTVVertical.fr

**Channel Language:**
French

**Additional Information (optional):**
BFMTV Has A First World Vertical Channel Stream.

**Comment by freearhey** [comment]
Closed in favor #1939

**Comment by AntiPontifex** [comment]
I posted an update to fr.m3u with this channel (fairly certain) - until it gets approved, it won't show up.
