### ISSUE TITLE
Broken: TNT (Russia)

### ISSUE THREAD

**Issue by nikitabaev71** [iptv-org/iptv#17272]
### Broken Link

http://ott-cdn.ucom.am/s19/index.m3u8

### What happened to the stream?

Stuck at a single frame

### Notes (optional)

i dont know
![image](https://github.com/user-attachments/assets/ae38078f-58e0-49d3-87be-cbf5b7ed4182)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
Fixed
