### ISSUE TITLE
Add: TV One (US)

### ISSUE THREAD

**Issue by boogabooga841** [iptv-org/iptv#17274]
### Channel ID (required)

TVOne.us

### Channel Name

TV One

### Stream URL (required)

http://fl2.moveonjoy.com/TV_ONE/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by picoluna1969** [comment]
Thx

Op ma 19 aug. 2024 19:45 schreef boogabooga841 ***@***.***>:

**Comment by ILIKECATS187** [comment]
I suggest you keep those for yourself and even delete them has it will just bring heat onto this repo which I REPEAT IS RESERVED FOR FREE TO AIR CHANNELS ONLY ... dunno how all these new members are posting Piracy now but it use to be not allowed for YEARS on here and now few bad apples are burning all the links here

**Comment by ILIKECATS187** [comment]
I dont know wtf you talking about phillipine and forums 

you sound crazy unwell and racist AF total cognitive dissonance I WONT TAKE THREATS FROM YOU IS THAT CLEAR  ........ check the description of the REPO you fucking tard ... FREE TO AIR TV not piracy this has been around for years no issues until people like you and Dum4 started showing up......
