### ISSUE TITLE
ReAdd: Fox News Channel

### ISSUE THREAD

**Issue by AmedKurdistan** [iptv-org/iptv#17283]
### Channel ID (required)

FoxNewsChannel.us

### Channel Name

Fox News Channel

### Stream URL (required)

http://fl2.moveonjoy.com/FOX_News_Channel/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ILIKECATS187** [comment]
PIRACY send this to fox already..


delete this channels pleaase 


iptv-org ALWAYS been for FREE TO AIR TV ..... dunno why new members keep posting this shit 

remember Geonsey before you from free2tv well hes in jail and if yall dont stop same with you
