### ISSUE TITLE
Broken: NBC Chicago WMAQ-DT1

### ISSUE THREAD

**Issue by Rodsan09** [iptv-org/iptv#17288]
### Broken Link

http://143.244.60.30/NBC_EAST/index.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by InsolenceWillow** [comment]
A Possible Replacement!

http://fl1.moveonjoy.com/NBC_EAST/index.m3u8

**Comment by Plus018** [comment]
Offline

**Comment by SuperstationWTF** [comment]
> > A Possible Replacement!
> > http://fl1.moveonjoy.com/NBC_EAST/index.m3u8
> 
> Change fl1 to fl2

Thank you. I  appreciate your contributions.

**Comment by Plus018** [comment]
Alr http://fl2.moveonjoy.com/NBC_EAST/index.m3u8

**Comment by InsolenceWillow** [comment]
http://fl5.moveonjoy.com/NBC_EAST/index.m3u8 Works Too

**Comment by InsolenceWillow** [comment]
Honestly who cares, as long as someone has it available online, I'm good!
