### ISSUE TITLE
Add: TNT HD (RU)

### ISSUE THREAD

**Issue by boogabooga841** [iptv-org/iptv#17282]
### Channel ID (required)

TNTHD.ru

### Channel Name

TNT HD

### Stream URL (required)

http://91.205.199.3/tnthd/index.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
It’s closed

**Comment by Plus018** [comment]
It’s not working ima do something

**Comment by BellezaEmporium** [comment]
Resolved IP https://s3.merlive.am/tnthd/index.m3u8

**Comment by Plus018** [comment]
BELLLZA ITS CLOSED ANOTHER ONE

**Comment by BellezaEmporium** [comment]
> BELLLZA ITS CLOSED ANOTHER ONE

If I approve, it's that it works on my side.

**Comment by Plus018** [comment]
Another link now.

**Comment by Plus018** [comment]
So these links u comment doesn’t work.

**Comment by Plus018** [comment]
If I try iptv smart player

**Comment by Plus018** [comment]
It’s doesn’t work.

**Comment by Plus018** [comment]
No they will check if it’s working or not.

**Comment by Plus018** [comment]
Try web stream?

**Comment by Plus018** [comment]
Huh? Vic where can I do?

**Comment by Plus018** [comment]
![IMG_2231](https://github.com/user-attachments/assets/1a36fa88-5c48-495f-8571-45488b198d8b)

**Comment by Plus018** [comment]
Where can I install vlc.

**Comment by Plus018** [comment]
Let me try VLC APP

**Comment by Plus018** [comment]
It doesn’t have in App Store what app to install.

**Comment by Plus018** [comment]
Tell me

**Comment by Plus018** [comment]
Let me try moscow

**Comment by Plus018** [comment]
It doesn’t work in moscow
![Uploading IMG_2232.jpeg…]()

**Comment by Plus018** [comment]
Shut up i can’t find it use tnt Russian thing

**Comment by Plus018** [comment]
Use this http://ott-cdn.ucom.am/s19/index.m3u8

**Comment by Plus018** [comment]
And it will work

**Comment by Plus018** [comment]
What is ur favorite Russian tv?

**Comment by Plus018** [comment]
https://tv.mail.ru/online/pervij/

**Comment by Plus018** [comment]
Shut up

**Comment by Plus018** [comment]
No trolling

**Comment by Plus018** [comment]
Shut up

**Comment by Plus018** [comment]
Look I tried to access without vpn and it doesn’t work 
![Uploading IMG_2234.jpeg…]()

**Comment by Plus018** [comment]
I tried to 
![IMG_2234](https://github.com/user-attachments/assets/a3be5476-3026-407b-ae65-4c51a7722dbe)

**Comment by Plus018** [comment]
Should vpn works to get out of geo blocked or use vlc app on iPhone which apps u install in vlc

**Comment by Plus018** [comment]
![IMG_2235](https://github.com/user-attachments/assets/99a9b83c-4d91-42d6-8025-4b17c1020d27)
Gg

**Comment by Plus018** [comment]
Vpn doesn’t work

**Comment by Plus018** [comment]
Ugh

**Comment by Plus018** [comment]
Which vlc app u install in App Store

**Comment by Plus018** [comment]
Do u use Samsung or iPhone?

**Comment by Plus018** [comment]
Did it now what?

**Comment by Plus018** [comment]
I did download vlc

**Comment by Plus018** [comment]
Do I download linked file

**Comment by Plus018** [comment]
Let  me try again

**Comment by Plus018** [comment]
This one it get out

**Comment by Plus018** [comment]
It doesn’t work bellza

**Comment by Plus018** [comment]
![IMG_2237](https://github.com/user-attachments/assets/0c3af596-cc5b-4f85-bd85-87ebed175e4d)
![IMG_2236](https://github.com/user-attachments/assets/4817500a-0828-449a-8523-e8b920ed4b93) this one doesn’t work it got me out

**Comment by Plus018** [comment]
Vlc doesn’t work and the link was blocked so geo blocked is hard to bypass

**Comment by Plus018** [comment]
Android we have?

**Comment by Plus018** [comment]
Huh?

**Comment by Plus018** [comment]
That can’t be access?

**Comment by Plus018** [comment]
Like I don’t wanna go.

**Comment by Plus018** [comment]
It has no internet

**Comment by Plus018** [comment]
North Korea is bad

**Comment by Plus018** [comment]
The bot closed it
