### ISSUE TITLE
WTF with the piracy

### ISSUE THREAD

**Issue by ILIKECATS187** [iptv-org/iptv#17284]
### Describe your issue

why the fuck does this repo which for years was about FREE TO AIR Channels is now all about piracy ?!?! wtf please remove the members who post piracy and cable channels it goes against the ethos of the repo ... its literally in the description ........

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by GuyInCanada** [comment]
Why are you such a downer?

**Comment by ILIKECATS187** [comment]
> IFUCKCATS187 I am against pirated and copyrighted streams!!! also he: ![markup_352](https://private-user-images.githubusercontent.com/177620802/359646259-f9d0ade7-4ffa-44fa-af53-c2a7e4dd3531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxOTIyNTcsIm5iZiI6MTcyNDE5MTk1NywicGF0aCI6Ii8xNzc2MjA4MDIvMzU5NjQ2MjU5LWY5ZDBhZGU3LTRmZmEtNDRmYS1hZjUzLWMyYTdlNGRkMzUzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQyMjEyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjllN2U1MTViNjRlNWU3YWRmNTNiYTVjM2UxMWRmMWZlZTQzOWNiNmIzYTAyMzY4ZTlkODRiMTI4MDAyMzI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z0TtEP_OZO15Zti3tuB0vdrzHPRLTjRuSe20DE9Z08A)

you were literally in that conversation where i posted that channel to get it taken down .... you know that lol you were literally in that thread you moron !

**Comment by ILIKECATS187** [comment]
love watching this burn ! ! ! hahahahahaha yall might as well take the whole repo down !
