### ISSUE TITLE
Broken: Animax.jp

### ISSUE THREAD

**Issue by pizzadeliverymen** [iptv-org/iptv#17287]
### Broken Link

http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=bs15

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by olstern01** [comment]
All of Primehome's streams are currently down unfortunately.

**Comment by olstern01** [comment]
It works now. Thank goodness.
