### ISSUE TITLE
Just want to clear up some inaccurate comments said about me.

### ISSUE THREAD

**Issue by tvlinks** [iptv-org/iptv#17286]
Just let me respond to this -- I am Geonsey and while F2V TV is long defunct, I am not in jail. In fact, I have a legit Roku app that is doing just fine with licensed content. As far as IPTV-ORG being Free-to-Air, well, that's not quite right (free-to-air is a term about broadcasting over antenna, not streaming) and, well, that's a debate for another day. You are serving an alternative community of streamers with links that are not quite 100% legit (I know 'cause I do my research as part of my app development, and I am also not here to debate that), but this group is not going anywhere, that's evident. Just wanted to respond to inaccurate comments about me, I hope that clears things up. All the best to you all. -G. 

              PIRACY send this to fox already..
http://212.102.60.231:80 is the actual source and from a cable company in Miami which have been notified 

delete this channels pleaase 

iptv-org ALWAYS been for FREE TO AIR TV ..... dunno why new members keep posting this shit 

remember Geonsey before you from free2tv well hes in jail

_Originally posted by @ILIKECATS187 in https://github.com/iptv-org/iptv/issues/17283#issuecomment-2299693025_

**Comment by ILIKECATS187** [comment]
youre an idiot i know you not in jail but been looking for your ass and you just outed yourself !

**Comment by tvlinks** [comment]
> you outed yourself awesome ! :)
> 
> but yeah im just here to burn everything and everyone !

Outed? lol... I have nothing to hide. I am not proud to admit mistakes and move on to my successes lol.
