### ISSUE TITLE
Broken: TokyoMX2

### ISSUE THREAD

**Issue by txfs19260817** [iptv-org/iptv#17293]
### Broken Link

https://mcas-eqms-mx1-live.hls.davlive.stream.ne.jp/mt/master/340f27cd590451b1e7d0034b85b5175ddaf05454/EQMS_MX2/master.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
Sorry we can’t do it it’s a shutdown
