### ISSUE TITLE
Add: Univision Atlanta (WUVG)

### ISSUE THREAD

**Issue by InsolenceWillow** [iptv-org/iptv#17298]
### Channel ID (required)

WUVGDT1.us

### Channel Name

Univision Atlanta (WUVG)

### Stream URL (required)

https://unidfp-nlds161.global.ssl.fastly.net/nlds/univisionnow/univision_atl2/as/live/univision_atl2_hd_pc.m3u8?t1=test_token

### Quality

720p

### Label

Geo-blocked

### HTTP Referrer

https://tv.univision.com/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
403 UNAUTHORIZED

**Comment by R4IN2007** [comment]
Don't care if there leaked are not but Link changes and also more security
`` 403 UNAUTHORIZED FOR ALL UNIVISION FASTLY.NET CHANNELS``
#EXTINF:-4, Unimas West
https://unidfp-nlds158.global.ssl.fastly.net/nlds/univisionnow/unimas_west2/as/live/unimas_west2_hd_pc.m3u8?t1=null

#EXTINF:-4, Univision East
https://unidfp-nlds155.global.ssl.fastly.net/nlds/univisionnow/univision_east2/as/live/univision_east2_hd_pc.m3u8?t1=null

#EXTINF:-4, Univision West
https://unidfp-nlds151.global.ssl.fastly.net/nlds/univisionnow/univision_west2/as/live/univision_west2_hd_pc.m3u8?t1=null

#EXTINF:-4, Univision 23 Miami FL (WLTV-DT1)
https://unidfp-nlds163.global.ssl.fastly.net/nlds/univisionnow/univision_mia2/as/live/univision_mia2_hd_pc.m3u8?t1=null

#EXTINF:-4, Univision 34 Atlanta (WUVG-DT1)
https://unidfp-nlds161.global.ssl.fastly.net/nlds/univisionnow/univision_atl2/as/live/univision_atl2_hd_pc.m3u8?t1=null

#EXTINF:-4, Univision 45 Houston (KXLN-DT1)
https://unidfp-nlds145.global.ssl.fastly.net/nlds/univisionnow/univision_hou2/as/live/univision_hou2_hd_pc.m3u8?t1=null

#EXTINF:-4, Univision 66 Chicago (WGBO-DT1)
https://unidfp-nlds154.global.ssl.fastly.net/nlds/univisionnow/univision_chi2/as/live/univision_chi2_hd_pc.m3u8?t1=null

#EXTINF:-4, Galavison East
https://unidfp-nlds159.global.ssl.fastly.net/nlds/univisionnow/galavision_east/as/live/galavision_east_hd_pc.m3u8?t1=

#EXTINF:-4, Galavison West
https://unidfp-nlds159.global.ssl.fastly.net/nlds/univisionnow/galavision_west/as/live/galavision_west_hd_pc.m3u8?t1=

**Comment by R4IN2007** [comment]
Channels are back as dai.google.com again!

**Comment by Plus018** [comment]
No.

**Comment by Plus018** [comment]
These links are offline streams

**Comment by Toei79** [comment]
too much headache about those honestly .  last lesss of two months

**Comment by R4IN2007** [comment]
> These links are offline streams

There Geo-blocked and 403 Unauthorized for people who ripped their streams from main site.

**Comment by R4IN2007** [comment]
> too much headache about those honestly . last lesss of two months

Yeah...

Unimas East
https://dai.google.com/linear/hls/event/EGOkHfP3QliognmK9maivw/master.m3u8

Galavison East
https://dai.google.com/linear/hls/event/4SHc_fddRJKEQ6UG_mtpjQ/master.m3u8

Univision East
https://dai.google.com/linear/hls/event/MpRfxL7YRce-hMKhzSB7Ow/master.m3u8

TUDN: NULL

**Comment by Toei79** [comment]
thanks for sharing the solution. 
last time i guess it was added word token and fix it.

if you have  an idea its easier.

**Comment by R4IN2007** [comment]
> thanks for sharing the solution. last time i guess it was added word token and fix it.
> 
> if you have an idea its easier.
> 
> i read your comment about dai.google.com but its all that i can know , thanks for sharing men
> 
> how you found it? so all their channels are on dai.google.com? only thing those are sd no hd

``https://tv.univision.com/channels`` Just the East Channels Only and Univision Streaming Channels

Link might change / It's Depends... ``https://dai.google.com/linear/hls/event/[_]/master.m3u8``

**Comment by Plus018** [comment]
Well u guys are wrong they shut down

**Comment by Toei79** [comment]
> Well u guys are wrong they shut down

Unidfp?

**Comment by Plus018** [comment]
Yes.

**Comment by Plus018** [comment]
unidfp doesn’t work

**Comment by Toei79** [comment]
> > thanks for sharing the solution. last time i guess it was added word token and fix it.
> > if you have an idea its easier.
> > i read your comment about dai.google.com but its all that i can know , thanks for sharing men
> > how you found it? so all their channels are on dai.google.com? only thing those are sd no hd
> 
> `https://tv.univision.com/channels` Just the East Channels Only and Univision Streaming Channels
> 
> Link might change / It's Depends... `https://dai.google.com/linear/hls/event/[_]/master.m3u8`
> 
> Fútbol https://dai.google.com/linear/hls/event/JgYgVMW8Szinkmm7dchlmQ/master.m3u8
> 
> Despierta América https://dai.google.com/linear/hls/event/oLZnojGrQ02TM-L5EeTuwA/master.m3u8
> 
> Novelas Channel https://dai.google.com/linear/hls/event/4VaHBXfJSYihkeo7w_T0Qw/master.m3u8
> 
> Delicioso (Cocina Channel) https://dai.google.com/linear/hls/event/P-z5VMsOQxmXTpZLaDC6Pg/master.m3u8
> 
> ^The rest of the Univision Streaming Channels.

Novelas on its novelas 5 minutos one?

**Comment by R4IN2007** [comment]
> > > thanks for sharing the solution. last time i guess it was added word token and fix it.
> > > if you have an idea its easier.
> > > i read your comment about dai.google.com but its all that i can know , thanks for sharing men
> > > how you found it? so all their channels are on dai.google.com? only thing those are sd no hd
> > 
> > 
> > `https://tv.univision.com/channels` Just the East Channels Only and Univision Streaming Channels
> > Link might change / It's Depends... `https://dai.google.com/linear/hls/event/[_]/master.m3u8`
> > Fútbol https://dai.google.com/linear/hls/event/JgYgVMW8Szinkmm7dchlmQ/master.m3u8
> > Despierta América https://dai.google.com/linear/hls/event/oLZnojGrQ02TM-L5EeTuwA/master.m3u8
> > Novelas Channel https://dai.google.com/linear/hls/event/4VaHBXfJSYihkeo7w_T0Qw/master.m3u8
> > Delicioso (Cocina Channel) https://dai.google.com/linear/hls/event/P-z5VMsOQxmXTpZLaDC6Pg/master.m3u8
> > ^The rest of the Univision Streaming Channels.
> 
> Novelas on its novelas 5 minutos one?

Yeah, Novelas en 5minutos 👍

**Comment by R4IN2007** [comment]
> unidfp didn't "shutdown", they just blocked the workaround where you can supply a fake token, now it only works with the dai.google.com redirects, but don't be surprised if they shut that down too as google now offers a way for broadcasters to require tokens for that too.
> 
> Yes Univision and UniMas are free over the air in some markets, but streaming those channels via their official player requires a subscription to a Pay TV provider or a $11.99/month subscription to Univision Now.

< Isn't that YouTubeTV, Sling, Fubo, DirecTV type of work?

**Comment by R4IN2007** [comment]
> > unidfp didn't "shutdown", they just blocked the workaround where you can supply a fake token, now it only works with the dai.google.com redirects, but don't be surprised if they shut that down too as google now offers a way for broadcasters to require tokens for that too.
> > Yes Univision and UniMas are free over the air in some markets, but streaming those channels via their official player requires a subscription to a Pay TV provider or a $11.99/month subscription to Univision Now.
> 
> < Isn't that YouTubeTV, Sling, Fubo, DirecTV type of work?

???
![Screenshot_20240823_201727_Web Video Caster](https://github.com/user-attachments/assets/f9f91b34-de9c-42e3-ac1d-77f178378d52)

**Comment by InsolenceWillow** [comment]
> > too much headache about those honestly . last lesss of two months
> 
> Yeah...
> 
> Unimas East https://dai.google.com/linear/hls/event/EGOkHfP3QliognmK9maivw/master.m3u8
> 
> Galavison East https://dai.google.com/linear/hls/event/4SHc_fddRJKEQ6UG_mtpjQ/master.m3u8
> 
> Univision East https://dai.google.com/linear/hls/event/MpRfxL7YRce-hMKhzSB7Ow/master.m3u8
> 
> TUDN: https://dai.google.com/linear/hls/event/LKaz-eTgQvawHshATl-Qdw/master.m3u8

I've downloaded the Univision stream and uploaded it through Github, and it seems that it gives me this as the master link!
https://unidfp-nlds155.global.ssl.fastly.net/linear/hls/event/MpRfxL7YRce-hMKhzSB7Ow/master.m3u8?hdnea=[token]&fsrc=player (Link doesn't work unless you fill "[token]" with a working token)

**Comment by InsolenceWillow** [comment]
> > > too much headache about those honestly . last lesss of two months
> > 
> > 
> > Yeah...
> > Unimas East https://dai.google.com/linear/hls/event/EGOkHfP3QliognmK9maivw/master.m3u8
> > Galavison East https://dai.google.com/linear/hls/event/4SHc_fddRJKEQ6UG_mtpjQ/master.m3u8
> > Univision East https://dai.google.com/linear/hls/event/MpRfxL7YRce-hMKhzSB7Ow/master.m3u8
> > TUDN: https://dai.google.com/linear/hls/event/LKaz-eTgQvawHshATl-Qdw/master.m3u8
> 
> I've downloaded the Univision stream and uploaded it through Github, and it seems that it gives me this as the master link! [https://unidfp-nlds155.global.ssl.fastly.net/linear/hls/event/MpRfxL7YRce-hMKhzSB7Ow/master.m3u8?hdnea=[token]&fsrc=player](https://unidfp-nlds155.global.ssl.fastly.net/linear/hls/event/MpRfxL7YRce-hMKhzSB7Ow/master.m3u8?hdnea=%5Btoken%5D&fsrc=player) (Link doesn't work unless you fill "[token]" with a working token)

So they pretty much still use unidfp as their stream, but dai.google.com is the link that they grab the token with automatically, so I'd suggest you use the dai.google.com streams!
