### ISSUE TITLE
Broken: Univision Streams

### ISSUE THREAD

**Issue by LivingBuzzard55** [iptv-org/iptv#17299]
### Broken Link

https://unidfp-nlds155.global.ssl.fastly.net/nlds/univisionnow/univision_east2/as/live/univision_east2_hd_pc.m3u8?t1=test_token

### What happened to the stream?

Other

### Notes (optional)

also galavision east and unimas east streams are broken

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
So here is the problem I need to find the real one

**Comment by Plus018** [comment]
But sorry I can’t it’s offlline

**Comment by Plus018** [comment]
U can’t access it only u pay the website u will watch. Click watch now.

**Comment by Plus018** [comment]
Univisionnow.com

**Comment by InsolenceWillow** [comment]
Bro, my Xfinity Auto-login Won't Work... 😭

**Comment by R4IN2007** [comment]
> Bro, my Xfinity Auto-login Won't Work... 😭

Might not for FIOS as well...

**Comment by BellezaEmporium** [comment]
https://unidfp-nlds154.global.ssl.fastly.net/nlds/univisionnow/univision_chi2/as/live/univision_chi2_hd_pc.m3u8?t1=

**Comment by BellezaEmporium** [comment]
Basically you would need to get the publish point in "path" to get the channels.

There's a "publish point" parameter that's a part of the DAI link, if that can help.

**Comment by Toei79** [comment]
https://tv.univision.com/service/publishpoint?type=channel&id=*id*&format=json&callback=getHTML5PublishPointCallback
here give an error 

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
