### ISSUE TITLE
Broken: MTV Pride

### ISSUE THREAD

**Issue by telanus** [iptv-org/iptv#17297]
### Broken Link

http://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/stitch/hls/channel/664225a1b18d700008e8bc76/master.m3u8?appName=web&appVersion=unknown&clientTime=0&deviceDNT=0&deviceId=2c7b17fa-35fc-11ef-a031-2b5d494037a2&deviceMake=Chrome&deviceModel=web&deviceType=web&deviceVersion=unknown&includeExtendedEvents=false&serverSideAds=false&sid=8d548418-d5af-444e-8c10-34ce23fda8a5

### What happened to the stream?

Not loading

### Notes (optional)

VLC is unable to open the MRL 'http://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/stitch/hls/channel/664225a1b18d700008e8bc76/master.m3u8?appName=web&appVersion=unknown&clientTime=0&deviceDNT=0&deviceId=2c7b17fa-35fc-11ef-a031-2b5d494037a2&deviceMake=Chrome&deviceModel=web&deviceType=web&deviceVersion=unknown&includeExtendedEvents=false&serverSideAds=false&sid=8d548418-d5af-444e-8c10-34ce23fda8a5'. Check the log for details.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
Sorry I can’t find what country is it

**Comment by telanus** [comment]
> Sorry I can’t find what country is it

https://raw.githubusercontent.com/iptv-org/iptv/master/streams/ca_pluto.m3u

**Comment by Plus018** [comment]
Sorry we can’t do it it’s sus
