### ISSUE TITLE
Add:Fox News Channel

### ISSUE THREAD

**Issue by Plus018** [iptv-org/iptv#17301]
### Channel ID (required)

FoxNewsChannel.us

### Channel Name

Fox News Channel

### Stream URL (required)

http://247preview.foxnews.com/hls/live/2020027/fncv3preview/primary.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Already in Playlist. Please Close
https://github.com/iptv-org/iptv/blob/24c483ac9a133718150413647c981f1ca09bc01f/streams/us.m3u#L339
