### ISSUE TITLE
Add: HITTV

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#17300]
### Channel ID (required)

HITTV.es

### Channel Name

Hit Tv

### Stream URL (required)

http://185.189.225.149/HitTV/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Don't care if there leaked are not but Link changes and also more security
`` 403 UNAUTHORIZED FOR ALL UNIVISION FASTLY.NET CHANNELS``
#EXTINF:-4, Unimas West
https://unidfp-nlds158.global.ssl.fastly.net/nlds/univisionnow/unimas_west2/as/live/unimas_west2_hd_pc.m3u8?t1=null

#EXTINF:-4, Univision East
https://unidfp-nlds155.global.ssl.fastly.net/nlds/univisionnow/univision_east2/as/live/univision_east2_hd_pc.m3u8?t1=null

#EXTINF:-4, Univision West
https://unidfp-nlds151.global.ssl.fastly.net/nlds/univisionnow/univision_west2/as/live/univision_west2_hd_pc.m3u8?t1=null

#EXTINF:-4, Univision 23 Miami FL (WLTV-DT1)
https://unidfp-nlds163.global.ssl.fastly.net/nlds/univisionnow/univision_mia2/as/live/univision_mia2_hd_pc.m3u8?t1=null

#EXTINF:-4, Univision 34 Atlanta (WUVG-DT1)
https://unidfp-nlds161.global.ssl.fastly.net/nlds/univisionnow/univision_atl2/as/live/univision_atl2_hd_pc.m3u8?t1=null

#EXTINF:-4, Univision 45 Houston (KXLN-DT1)
https://unidfp-nlds145.global.ssl.fastly.net/nlds/univisionnow/univision_hou2/as/live/univision_hou2_hd_pc.m3u8?t1=null

#EXTINF:-4, Univision 66 Chicago (WGBO-DT1)
https://unidfp-nlds154.global.ssl.fastly.net/nlds/univisionnow/univision_chi2/as/live/univision_chi2_hd_pc.m3u8?t1=null

#EXTINF:-4, Galavison East
https://unidfp-nlds159.global.ssl.fastly.net/nlds/univisionnow/galavision_east/as/live/galavision_east_hd_pc.m3u8?t1=

#EXTINF:-4, Galavison West
https://unidfp-nlds159.global.ssl.fastly.net/nlds/univisionnow/galavision_west/as/live/galavision_west_hd_pc.m3u8?t1=

**Comment by Plus018** [comment]
Correct I approve.
