### ISSUE TITLE
Add: viju History (RU)

### ISSUE THREAD

**Issue by boogabooga841** [iptv-org/iptv#17319]
### Channel ID (required)

vijuHistory.ru

### Channel Name

viju History

### Stream URL (required)

https://stream2.cinerama.uz/1046/tracks-v1a1/mono.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
https://stream2.cinerama.uz/1046/index.m3u8

Flussonic.
