### ISSUE TITLE
Most of MBC channels are not working

### ISSUE THREAD

**Issue by Ziad-84** [iptv-org/iptv#1731]
**Country of the channel:**
UAE

**Channel Name:**
MBC Group

**Channel Language:**
Arabic

**Additional Information (optional):**
MBC1, MBC4 and MBC5 at least are not working

**Comment by jad222** [comment]
MBC 2, MBC ACTION also!

**Comment by aliali1983** [comment]
How do I get the link of MBC channels

**Comment by x5engine** [comment]
What's happening? Why?

MBC Masr and all mbc related channels don't work anymore for a good while now

Any alternative??

**Comment by jad222** [comment]
They coming back soon, tomorrow u will find the mbc channels back :)

**Comment by aliali1983** [comment]
Do i need to download new url or m3u file
Or just wait.

**Comment by jad222** [comment]
Just wait buddy , you don't need to do anything.

**Comment by x5engine** [comment]
Can't wait ☺️ thank you so much

**Comment by Ziad-84** [comment]
> Just wait buddy , you don't need to do anything.

Thank you for your efforts. MBC2, MBC4 and MBC5 are working again, we are still waiting for MBC1.

**Comment by jad222** [comment]
@Ziad-84 now i added mbc1 we will wait to @freearhey to merge :)

**Comment by Ziad-84** [comment]
> @Ziad-84 now i added mbc1 we will wait to @freearhey to merge :)

You are the best Bro ;) if you can get a link to MBC1 with higher quality that would be perfect

**Comment by x5engine** [comment]
Amazing work 👍

**Comment by samimasad** [comment]
i believe there is still problem with mbc after getting iptv-org neck online

**Comment by jad222** [comment]
@samimasad All mbc channels work fine!
I added Mbc iraq - masr 1 - masr 2 now and u will see it tomorrow!

**Comment by jad222** [comment]
@freearhey all mbc channels works fine u can close this issue if u like to do it

**Comment by samimasad** [comment]
> @samimasad All mbc channels work fine!
> I added Mbc iraq - masr 1 - masr 2 now and u will see it tomorrow!

somehow the pull requests are not getting merged for the last 11 days or so , any idea what is going on?

**Comment by DrGogu** [comment]
Hello friends.  MBC channels were working until today afternoon (CT time USA) and now they are not working anymore!! Is it only me or do you guys have the same issue?

**Comment by DrGogu** [comment]
Working now.  Ok to close.  Thx.
