### ISSUE TITLE
Add: Muz-Tv (RU)

### ISSUE THREAD

**Issue by Plus018** [iptv-org/iptv#17335]
### Channel ID (required)

MuzTv.ru 

### Channel Name

Muz Tv

### Stream URL (required)

https://streaming.televizor-24-tochka.ru/live/618.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/fb1cb7a89ac83615a9dc3e6ab23dc4328164b9b0/streams/ru_televizor-24.m3u#L46-L47
