### ISSUE TITLE
Add: TNT HD (RU) 

### ISSUE THREAD

**Issue by Plus018** [iptv-org/iptv#17338]
### Channel ID (required)

TNTHD.ru

### Channel Name

TNT HD

### Stream URL (required)

http://91.205.199.3/tnthd/index.m3u8

### Quality

1080p

### Label

Geo-blocked

### Notes

To access use https://apps.apple.com/us/app/iptv-smarters-xtream-iptv/id1573898785

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/fb1cb7a89ac83615a9dc3e6ab23dc4328164b9b0/streams/ru.m3u#L262-L263
