### ISSUE TITLE
Add: Russia 1

### ISSUE THREAD

**Issue by Plus018** [iptv-org/iptv#17339]
### Channel ID (required)

Russia1.ru

### Channel Name

Russia 1

### Stream URL (required)

http://s18209.cdn.ngenix.net/hls/CH_R04_ROSSIA1/playlist.m3u8

### Quality

720p

### Label

None

### Notes

Works for xtreme code

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/fb1cb7a89ac83615a9dc3e6ab23dc4328164b9b0/streams/ru_s18209.m3u#L20-L21
