### ISSUE TITLE
Add: 360 News

### ISSUE THREAD

**Issue by Plus018** [iptv-org/iptv#17337]
### Channel ID (required)

360News.ru

### Channel Name

360 news

### Stream URL (required)

https://live-vgtrksmotrim.cdnvideo.ru/vgtrksmotrim/smotrim-live-03-srt.smil/playlist.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/fb1cb7a89ac83615a9dc3e6ab23dc4328164b9b0/streams/ru_smotrim.m3u#L4-L5
