### ISSUE TITLE
Broken: Muz-TV (RU)

### ISSUE THREAD

**Issue by boogabooga841** [iptv-org/iptv#17332]
### Broken Link

https://edge02.odtv.az/o5/muztv/playlist.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://edge02.odtv.az/o5/muztv/playlist.m3u8
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/fab14ad0-af87-4649-aaca-dbe54d9af818">
