### ISSUE TITLE
Channel issue

### ISSUE THREAD

**Issue by drosario2323** [iptv-org/iptv#1733]
**dominican republic:**

**Color vision**

The channel is not working. Could you please add more channels from dominican republic or tell me how to do it?. Thanks

**Comment by Sphinxroot** [comment]
hello  .. color vision are now streaming from dailymotion 

you can get the streaming link from them as m3u8 link  but they will change offten  the part bettwen (  )

https://www.dailymotion.com/video/x7v13mt
https://stream-01.nyc.dailymotion.com/sec(0HE75RGSqqnhnSdEMl12ZUPaqogVaocIgqmGA6SzqOI)/dm/3/x7v13mt/s/live-3.m3u8

https://www.dailymotion.com/video/x7gy059
https://stream-01.nyc.dailymotion.com/sec(O-7bth6lxCIslucX64-RY6ADe4YQgKLHnE0TZRppIvI)/dm/3/x7gy059/d/live-4.m3u8

if you dont want to handle changing those link nearly everyday .. you can use kodi  whit the addon dailymotion 
and use plugin://plugin.video.dailymotion_com/?mode=playVideo&url=  in your m3u files

as exemple:
#EXTINF:-1 tvg-logo="https://colorvision.com.do/wp-content/uploads/2018/10/LOGO-HD-full.png" group-title="",Color Visión
plugin://plugin.video.dailymotion_com/?mode=playVideo&url=x7v13mt 

so you dont have to change the m3u8 link anymore until they change streaming link 

hope it help :)

**Comment by drosario2323** [comment]
Sorry for asking. I am using perfect player to stream. I tried with the link you gave me and. I couldnt use it.  Thanks for your help.

**Comment by Sphinxroot** [comment]
yep tested in perfect player and many link dont work  in it  that why i use kodi instead

**Comment by drosario2323** [comment]
Do you know how to use at perfect player?. Or add it at the dominican republic m3u list posted?

**Comment by Sphinxroot** [comment]
this app is not working good for me so i barely use it .. i got ton of link that isnt working in it .. i use kodi for most of my iptv  see my git for more :)

**Comment by drosario2323** [comment]
Thanks. The issue for me is that perfect player is easier to use for my parents and they love that channel.

**Comment by drosario2323** [comment]
I check the m3u DO list and the channel is gone.. could somebody help with that? This is the web page:
https://colorvision.com.do

Thanks

**Comment by I-Cat** [comment]
It won't work in perfect player because it's not an .m3u8 try adding the 8 at the end of the link. The 8 stands for UTF8 encoded.

**Comment by I-Cat** [comment]
> I check the m3u DO list and the channel is gone.. could somebody help with that? This is the web page:
> https://colorvision.com.do
> 
> Thanks

Up

**Comment by Sphinxroot** [comment]
![channel](https://user-images.githubusercontent.com/47762050/93562628-6842d180-f954-11ea-80a0-ec91af1bca98.png)
as i said they now stream from dailymotion

create  CV9.m3u8 with a txt file and put it in your github folder and link to it 

#EXTM3U 
#EXT-X-VERSION:3 
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000 
https://stream-04.nyc.dailymotion.com/sec(O-7bth6lxCIslucX64-RY6ADe4YQgKLHnE0TZRppIvI)/dm/3/x7gy059/d/live-4.m3u8


note that the link will change over the time so you will need to change it ,this part is a token link -> (O-7bth6lxCIslucX64-RY6ADe4YQgKLHnE0TZRppIvI)

**Comment by freearhey** [comment]
Closed in favor #1984
