### ISSUE TITLE
Add: Pobeda (RU) No geo blocked

### ISSUE THREAD

**Issue by Plus018** [iptv-org/iptv#17336]
### Channel ID (required)

Pobeda.ru

### Channel Name

Pobeda

### Stream URL (required)

https://streaming.skynetconnect.online/live/43.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
NTV HD TO WATCH HERE https://tv.mail.ru/online/ntv/

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/fb1cb7a89ac83615a9dc3e6ab23dc4328164b9b0/streams/ru_televizor-24.m3u#L61-L63
