### ISSUE TITLE
Add: Russia 24

### ISSUE THREAD

**Issue by Plus018** [iptv-org/iptv#17340]
### Channel ID (required)

Russia24.ru

### Channel Name

Russia24

### Stream URL (required)

https://streaming.televizor-24-tochka.ru/live/30.m3u8

### Quality

None

### Label

None

### Notes

Works for xtreme code

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/fb1cb7a89ac83615a9dc3e6ab23dc4328164b9b0/streams/ru_televizor-24.m3u#L75-L76
