### ISSUE TITLE
Add: W9 (FR)

### ISSUE THREAD

**Issue by Rodri200906** [iptv-org/iptv#17356]
### Channel ID (required)

W9.fr

### Channel Name

W9

### Stream URL (required)

https://iptv.frembed.pro/live/A6B56AC724C0686C98984A5A92CA1DC1/79.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Xtreme code, Not Accepted.
