### ISSUE TITLE
Broken: 3832 HCH (720p) [Not 24/7] Honduras

### ISSUE THREAD

**Issue by MemTheBun** [iptv-org/iptv#17354]
### Broken Link

https://hch.tv

### What happened to the stream?

Not loading

### Notes (optional)

Kodi one or more items failed to play

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
@Alstruit Hey use this as a replacement from ssh101-bozztv.com
https://ssh101-fl.bozztv.com/ssh101/hchtvenvivo/playlist.m3u8

**Comment by km147** [comment]
Confirmed this comment above actually is a working replacement for a broken link
@Alstruit Hey use this as a replacement from ssh101-bozztv.com
https://ssh101-fl.bozztv.com/ssh101/hchtvenvivo/playlist.m3u8
