### ISSUE TITLE
Add: NewsNation East (US)

### ISSUE THREAD

**Issue by boogabooga841** [iptv-org/iptv#17351]
### Channel ID (required)

NewsNationEast.us

### Channel Name

NewsNation East

### Stream URL (required)

http://cord-cutter.net:8080/live/j3McKd/673709/161450.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
We do not accept Xtream-Codes playlists.
![image](https://github.com/user-attachments/assets/858df1f0-a23f-4621-b25d-e878fb69c6fa)
