### ISSUE TITLE
Broken: Priamyi (UA)

### ISSUE THREAD

**Issue by boogabooga841** [iptv-org/iptv#17366]
### Broken Link

http://portal.ott.pink/watch/14/video.m3u8?geo=auto&token=CFEADF9789D77A45B3B359EE168CCCA6

### What happened to the stream?

Other

### Notes (optional)

Tokenized link

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ztreamhd** [comment]
You can use either this link `https://ythls.armelin.one/video/-9FO57Sk_oY.m3u8`; this other one `https://ythls.armelin.one/channel/UCH9H_b9oJtSHBovh94yB5HA.m3u8`; or this last one `http://iptv.prosto.tv:7000/ch24/video.m3u8` but this one won't let you watch the stream for longer than 5 or 10 minutes.
