### ISSUE TITLE
Add: NewsNation East

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/iptv#17375]
### Channel ID (required)

NewsNationEast.us

### Channel Name

NewsNation East

### Stream URL (required)

http://212.102.60.231/NEWS_NATION/index.m3u8

### Quality

720p

### Label

None

### Notes

Try to complete #17362

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by fdezwonders** [comment]
@boogabooga841
> but links does not work because cloudflare firewall blocks me.

That is on purpose. DLHD do not want you using their streams for free, and so they block any outside access of the stream except for their own IP addresses and the website itself. I don't think there is a way to bypass it.
> http://212.102.60.231/NEWS_NATION/index.m3u8

Just use that URL, works fine.

**Comment by Irylek** [comment]
> ~I tried to find a stream for Newsnation (US) and found the site https://dlhd.so/stream/stream-292.php~
> 
> ~I managed to get a m3u8 link to a stream,~
> 
> ~https://webhdrunns.mizhls.ru/lb/premium292/index.m3u8~ ~or~ ~https://ddy5.mizhls.ru/ddy5/premium292/tracks-v1a1/mono.m3u8~
> 
> ~but links does not work because cloudflare firewall blocks me. What could be the reason? User agent? VPN? Refer needed? I just don't understand all this. Or do we still need a token?~
> 
> > http://212.102.60.231/NEWS_NATION/index.m3u8
> 
> ~this can definitely replace this link, if not then~ let's add this one

try using headers for dlhd.so :)

**Comment by fdezwonders** [comment]
@Irylek gotta be honest, have no idea how to do that
