### ISSUE TITLE
SNRT Channels Not Functioning on Most Applications

### ISSUE THREAD

**Issue by saidma** [iptv-org/iptv#17378]
Hello. The channels of the moroccan SNRT group haven't been working on most applications for months due to some change. None of the channels work on VLC, KODI, Chrome, Smart IPTV Android TV... However, they do work on the OTT Navigator app on Android TV. It's very strange because they work fine on the official website snrtlive.ma and they are not geo-blocked, as the programming can be viewed abroad for free.

**Affected channels**:

AlAoulaEurope.ma
AlAoulaLaayoune.ma
AlMaghribia.ma
Arryadia.ma
Assadissa.ma
Athaqafia.ma
TamazightTV.ma

**Location**: France

SMART IPTV 
![IMG_20240830_003940](https://github.com/user-attachments/assets/17f0d4b7-2920-455a-817b-22ffe29efd12)
OTT NAVIGATOR
![IMG_20240830_003605](https://github.com/user-attachments/assets/661a33c9-2d59-4b1b-bead-56d97f46d4a0)

**Comment by BellezaEmporium** [comment]
> all streams with the domain `cdnamd-hls-globecast.akamaized.net` died for some reason

These streams aren't dead. They need a referer in order to work.

https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/al_aoula_inter/hls_snrt/al_aoula_inter.m3u8
Referer : https://snrtlive.ma/

**Comment by saidma** [comment]
> > all streams with the domain `cdnamd-hls-globecast.akamaized.net` died for some reason
> 
> These streams aren't dead. They need a referer to work.
> 
> https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/al_aoula_inter/hls_snrt/al_aoula_inter.m3u8 Referer : https://snrtlive.ma/

But that doesn't fully explain why the links do work in the OTT NAVIGATOR app and not in most other apps. The lists are the same. I didn't add anything to the links

**Comment by saidma** [comment]
> all streams with the domain `cdnamd-hls-globecast.akamaized.net` died for some reason

I tested this link works:
https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/2m_monde/hls_video_ts_tuhawxpiemz257adfc/2m_monde.m3u8

**Comment by BellezaEmporium** [comment]
> > > all streams with the domain `cdnamd-hls-globecast.akamaized.net` died for some reason
> > 
> > 
> > These streams aren't dead. They need a referer to work.
> > https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/al_aoula_inter/hls_snrt/al_aoula_inter.m3u8 Referer : https://snrtlive.ma/
> 
> But that doesn't fully explain why the links do work in the OTT NAVIGATOR app and not in most other apps. The lists are the same. I didn't add anything to the links

It's most certainly because they do not support the "EXTVLCOPT" header.

**Comment by saidma** [comment]
Exactly. I hadn't realized that an issue #12345 had already been opened about this same problem.

**Comment by R4IN2007** [comment]
Access Denied on Chrome.

**Comment by BellezaEmporium** [comment]
If you want to try using 'Smart IPTV', you would need to move the referer as such :

From:
```
#EXTINF:-1, some site
#EXTVLCOPT:http-referrer=https://example.com/
https://example.com/example.m3u
```
To:
```
#EXTINF:-1 user-agent="Some/User:Agent", some site
https://example.com/example.m3u
```

**Comment by saidma** [comment]
In VLC under Windows, the EXTVCOPT property works. In Smart IPTV, none of the properties mentioned on the official page work. I'm closing the issue.

**Comment by saidma** [comment]
In VLC under Windows, the EXTVCOPT property works. In Smart IPTV, none of the properties mentioned on the official page work.


#EXTINF:0 user-agent="User Agent", referer="Referer", My Channel
http://channel_URL
#EXTINF:0,My Channel
http://channel_URL|User-agent=User Agent
#EXTINF:0,My Channel
http://channel_URL|Referer=Referer
#EXTINF:0,My Channel
http://channel_URL|Referrer=Referrer

I'm closing the issue.
