### ISSUE TITLE
Broken: EnerGeek.cl | EnerGeek Señal 1

### ISSUE THREAD

**Issue by EnerGeekTeam** [iptv-org/iptv#17371]
### Broken Link

https://wifiexpert-1.energeek.cl/energeek/canal-1/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Link has been updated. New link: https://streaming-cl.sh1ny.space/memfs/e8a8e789-170b-4de4-a33b-90a9a475ce65.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Gracias por los nuevos urls, Thanks you!!!
