### ISSUE TITLE
Add: C-SPAN

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/iptv#17382]
### Channel ID (required)

CSPAN.us

### Channel Name

C-SPAN

### Stream URL (required)

http://143.244.60.97/C-SPAN/index.m3u8

### Quality

720p

### Label

None

### Notes

Trying to complete #

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Dup #17380

**Comment by ProPontifex** [comment]
DOH!
