### ISSUE TITLE
Add: CNN en Español

### ISSUE THREAD

**Issue by idk17461** [iptv-org/iptv#17398]
### Channel ID (required)

CNNenEspanol.us

### Channel Name

CNN en Español

### Stream URL (required)

http://168.197.196.98:9981/stream/channelid/438380873

### Quality

None

### Label

Not 24/7

### Notes

Cant watch the stream in browser, It starts a download instead, so its recommended a video/stream player (example: VLC)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by idk17461** [comment]
?

**Comment by R4IN2007** [comment]
WBD DMCA'D Can't be added. / No se puede agregar por un DMCA de WBD.

**Comment by idk17461** [comment]
I guess its geoblocked? I dont understand much

**Comment by R4IN2007** [comment]
`protect copyright holders from online theft` Unauthorized content because WBD owns this.

**Comment by idk17461** [comment]
I closed the issue, thanks for telling me
