### ISSUE TITLE
Add: ALL TVP CHANNELS FROM VOD.TVP.PL

### ISSUE THREAD

**Issue by Irylek** [iptv-org/iptv#17397]
### Channel ID (required)

TVP.pl

### Stream URL (required)

https://irylek.ct8.pl/stream/alfatvp https://irylek.ct8.pl/stream/belsat https://irylek.ct8.pl/stream/tvp1hd https://irylek.ct8.pl/stream/tvp2hd https://irylek.ct8.pl/stream/tvp3warszawahd https://irylek.ct8.pl/stream/tvpabc https://irylek.ct8.pl/stream/tvpabc2 https://irylek.ct8.pl/stream/tvpdokument https://irylek.ct8.pl/stream/tvphistoria https://irylek.ct8.pl/stream/tvphistoria2 https://irylek.ct8.pl/stream/tvpinfo https://irylek.ct8.pl/stream/tvpkultura https://irylek.ct8.pl/stream/tvpkultura2 https://irylek.ct8.pl/stream/tvpnauka https://irylek.ct8.pl/stream/tvppolonia https://irylek.ct8.pl/stream/tvprozrywka https://irylek.ct8.pl/stream/tvpsport https://irylek.ct8.pl/stream/tvpwilno https://irylek.ct8.pl/stream/tvpworld

### Quality

1080p

### Label

Geo-blocked

### Timeshift

30 minutes or 15 minutes.

### Notes

Basically, i am using vod.tvp.pl api to do this:

1. a user plays the url on vlc
2. my script requests a hls link from the api
3. extracts the temporary m3u8 from the json response
4. redirecting to the m3u8 (because of cors policy)
5. the stream starts playing

https://irylek.ct8.pl/stream/alfatvp
https://irylek.ct8.pl/stream/belsat
https://irylek.ct8.pl/stream/tvp1hd
https://irylek.ct8.pl/stream/tvp2hd
https://irylek.ct8.pl/stream/tvp3warszawahd
https://irylek.ct8.pl/stream/tvpabc
https://irylek.ct8.pl/stream/tvpabc2
https://irylek.ct8.pl/stream/tvpdokument
https://irylek.ct8.pl/stream/tvphistoria
https://irylek.ct8.pl/stream/tvphistoria2
https://irylek.ct8.pl/stream/tvpinfo
https://irylek.ct8.pl/stream/tvpkultura
https://irylek.ct8.pl/stream/tvpkultura2
https://irylek.ct8.pl/stream/tvpnauka
https://irylek.ct8.pl/stream/tvppolonia
https://irylek.ct8.pl/stream/tvprozrywka
https://irylek.ct8.pl/stream/tvpsport
https://irylek.ct8.pl/stream/tvpwilno
https://irylek.ct8.pl/stream/tvpworld

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
All tokenized!!!

**Comment by Irylek** [comment]
> Is it that difficult to create a PR yourself?

i dont know what youre talking about.

**Comment by Irylek** [comment]
> All tokenized!!!

thats the point. it is being generated! the token lasts for 12-24 hours. everytime you open the stream it will generate a new token.

**Comment by Irylek** [comment]
example:

i opened the stream and i got this: 
https://rsdt-waw1601-228.tvp.pl/token/video/live/71345993/20240831/2297666664/Poprtc2eF6cQlTlywQMGl_bVD5clVH4oMNq5AktVCPVgrDtjvvQck_heSAkxz04Pp-t8TETKT3OkdtTpfH5xv-mGyMt7xZ_SMCpwHx3zsb-hXDY9sxYEA8VA5qmMzdJ6OT4mAsNTqplMofetood7L-W0zJJJSES4gfr9Z7oqf5M/156/master.m3u8

i opened the stream again and this time got this: https://rsdt-waw1501-228.tvp.pl/token/video/live/71345993/20240831/2297666664/uHsTeLqCBlAcXmVmD3oXCohsPzJEyuMtMjDb5JLfC6otVR5ZB3D_nUJhwD9AHV93cIwTVnOX5Lmfv1TaudERdJumShZjXSlVAjJbrwL8WJpFTF_5s-ORZRyk5o7Cdh7-XQpAjwRrR-dY98bpJ1oerQw-FNR_zN56n_8ELaxkV6I/156/master.m3u8

**Comment by Irylek** [comment]
i dont know what is the issue in restarting the channel (is like 5-10 seconds) + who would normally watch it 24/7?

**Comment by Irylek** [comment]
i dont know what is the problem of restarting the channel in 5-10 seconds?

**Comment by Irylek** [comment]
then its your problem lmao.

**Comment by Irylek** [comment]
okej aktualnie kłócisz się że masz kliknąć 2 razy w stream co 24 godziny. a tak wogule jak spisz mordo?

**Comment by Irylek** [comment]
then translate it

**Comment by R4IN2007** [comment]
> > All tokenized!!!
> 
> thats the point. it is being generated! the token lasts for 12-24 hours. everytime you open the stream it will generate a new token.

Tak więc, technicznie rzecz biorąc, jeśli m3u8 zawier token, działa tylko przez 12–24 godziny, ale skrypt, gdy upłynie czas, wygeneruje kolejny token lub będę musiał poczekać, aż upłynie czas na wygenerowanie kolejnego tokena, co oznacza, że ​​ja można z niego skorzystać raz, nie trzeba za każdym razem wklejać adresu URL? Hope this a good translation.

**Comment by Irylek** [comment]
nie trzeba. po prostu odpalasz streama znowu.

**Comment by R4IN2007** [comment]
> nie trzeba. po prostu odpalasz streama znowu.

Oh OK, thanks

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-add-a-new-stream-link-to-a-playlists

**Comment by mikeS24A** [comment]
> then translate it

ignoruj ​​idiotów.  I think your method to refresh the tokens is genius. I tried connecting to the streams today and notice they are down.  I hope they can return.  If not, would you be willing to share the script .... perhaps I can stand up a backup server?
