### ISSUE TITLE
Broken: HCH.HN

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#17402]
### Broken Link

https://rpn3.bozztv.com/ssh101/ssh101/hchtvenvivo/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Not working, Possible replacement (https://ssh101-fl.bozztv.com/ssh101/hchtvenvivo/playlist.m3u8)
![Screenshot_20240831_200653_Chrome](https://github.com/user-attachments/assets/ae0f1aac-e457-4caf-ab53-1aa75ba6c940) https://github.com/iptv-org/iptv/issues/17354 @Alstruit 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
https://sh101-fl.bozztv.com/ssh101/hchtvenvivo/playlist.m3u8
