### ISSUE TITLE
Broken: NickToons Scanidavia

### ISSUE THREAD

**Issue by jayc3-cmyk** [iptv-org/iptv#17401]
### Broken Link

http://89.254.128.5:22280/nicktoons/video.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

There isn't a point to be honest. All it is is just not loading. Stuck on black screen. Also no audio.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Not Working. Yeah no point of having it in the playlist
