### ISSUE TITLE
Broken: Nickelodeon East (US)

### ISSUE THREAD

**Issue by WindooowsX** [iptv-org/iptv#17416]
### Broken Link

http://143.244.60.30/NICKELODEON/index.m3u8

### What happened to the stream?

Other

### Notes (optional)

Stream works, but is now Nickelodeon Greece.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Odd from it being the US Version to the Nickelodeon Greece.
