### ISSUE TITLE
indian channels by language plese

### ISSUE THREAD

**Issue by DUVVI** [iptv-org/iptv#1741]
**Country of the channel:**

**Channel Name:**

**Channel Language:**

**Additional Information (optional):**

**Comment by themak1985** [comment]
@DUVVI - My suggestion for you is to use the https://iptv-org.github.io/iptv/index.language.m3u file and using your IPTV platform, hide the languages you are not interested in. This would include, for example, hindi channels that are broadcasted outside of India.
