### ISSUE TITLE
Add: Hype Visual Radio to Music Channels Category

### ISSUE THREAD

**Issue by gc2400** [iptv-org/iptv#17411]
### Channel ID (required)

HypeVisualRadio

### Channel Name

Hype Visual Radio

### Stream URL (required)

https://streammix.alsolnet.com/hyperadio/live/playlist.m3u8

### Quality

720p

### Label

None

### HTTP Referrer

https://www.hyperadio.nl/

### Notes

Music Channel

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ProPontifex** [comment]
Just added a database entry #13426
