### ISSUE TITLE
Add: Canal de la Ciudad (Argentina)

### ISSUE THREAD

**Issue by idk17461** [iptv-org/iptv#17418]
### Channel ID (required)

CanaldelaCiudad.ar

### Channel Name

Canal de la Ciudad

### Stream URL (required)

http://168.197.196.98:82/stream/channelid/1330348835?profile=pass

### Quality

360p

### Label

Not 24/7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
Sorry this stream is broken

**Comment by Plus018** [comment]
https://ythls.armelin.one/channel/UCOV_Vx1baZJY9Tfvgm-UI3w.m3u8

**Comment by Plus018** [comment]
But it’s blocked so use https://apps.apple.com/us/app/iptv-smarters-xtream-iptv/id1573898785

**Comment by Plus018** [comment]
Due to the lack of information available it’s not closed pls find the new one

**Comment by Plus018** [comment]
It’s geo blocked let me tell u now it got un geo blocked

**Comment by Dum4G** [comment]
![image](https://github.com/user-attachments/assets/1d3e2300-1e2a-4301-bf03-8ef05b89c1a0)

**Comment by Dum4G** [comment]
![image](https://github.com/user-attachments/assets/c853e22d-5d0a-413e-8cd9-fdcaed6fd944)

**Comment by Alstruit** [comment]
Tvheadend links are generally spotty at best.
