### ISSUE TITLE
Change: "neetballs" AT-X link it's been dead for 2 years 

### ISSUE THREAD

**Issue by Jakcel** [iptv-org/iptv#17415]
### Channel ID (required)

ATX.jp

### Channel Name

AT-X

### Stream URL (required)

https://code.vthanhtivi.pw/getlink/jptv2/107/playlist.m3u8

### Quality

1080p

### Label

None

### Notes

As of 2024 I can tell if the 2023 link from issues still works or just remove neetballs version all together 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
https://code.vthanhtivi.pw/stre  am/jptv2/107/playlist.m3u8

**Comment by Jakcel** [comment]
If it's a invalid link the get rid of it in the app I literally said it doesn't fking work
