### ISSUE TITLE
Broken: Vision Latina Panamá 

### ISSUE THREAD

**Issue by KobayashiSan507** [iptv-org/iptv#17424]
### Broken Link

https://5940924978228.streamlock.net/8095/8095/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

The channel can be viewed without problems on its website https://visionlatinapanama.com/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
https://visionlatinapanama.com/

**Comment by 0799522954** [comment]
a8724809d562a20edde1f234656e749f449dce75

**Comment by R4IN2007** [comment]
https://dacastmmd.mmdlive.lldns.net/dacastmmd/c1275185f4a8493a85c63390cfc93dad/index.m3u8
Now as dacast!! - New URL
![Screenshot_20240904_155356_Chrome](https://github.com/user-attachments/assets/e7edd862-6207-47a4-bd20-391c63bd01bb)
