### ISSUE TITLE
Add: Unserding

### ISSUE THREAD

**Issue by microraptor** [iptv-org/iptv#17427]
### Channel ID (required)

Unserding.de

### Channel Name

Unserding

### Stream URL (required)

https://srde.akamaized.net/hls/live/2031842/visualradio-unserding/index.m3u8

### Quality

720p

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by DenysMath** [comment]
> blocked everywhere except germany? i guess
> 
> ![image](https://private-user-images.githubusercontent.com/180005008/364755772-4db1ea21-c339-4451-9414-16f436f4a4fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2ODEyODgsIm5iZiI6MTcyNTY4MDk4OCwicGF0aCI6Ii8xODAwMDUwMDgvMzY0NzU1NzcyLTRkYjFlYTIxLWMzMzktNDQ1MS05NDE0LTE2ZjQzNmY0YTRmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QwMzQ5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmUyN2RmYzZkMjZjNTAxZjI2Yzk4M2IwZjdhNjBmOGM5NTY5YTU5NTk3YjViZjI3YjZiMGYxMmI3MGZhMjM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PiAUZSkE0lmifKFBr4itXYyg2YEEdGbFEh1Me7OgriE) ![image](https://private-user-images.githubusercontent.com/180005008/364755881-2593c1ce-65c5-4d9e-a60c-6286d584788f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2ODEyODgsIm5iZiI6MTcyNTY4MDk4OCwicGF0aCI6Ii8xODAwMDUwMDgvMzY0NzU1ODgxLTI1OTNjMWNlLTY1YzUtNGQ5ZS1hNjBjLTYyODZkNTg0Nzg4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QwMzQ5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzgwZjcwOTg4OTU5YTVlZGI1ZGUwMDQ1MTM5NDM4NTY0ZDE1Y2Q1MzhiNjYzZDgwYTUzZDFlYzRmZmQxM2Y0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ljLqdRteOrhpjLF8VvbhtqKZy5VLv27YG_gfsed3gKk)

What's the site on the first screenshot?

**Comment by Toei79** [comment]
i tried with streamlink and free proxy and nada.

**Comment by Dum4G** [comment]
![image](https://github.com/user-attachments/assets/e1d0c2d4-8a71-4132-b58f-daf2f2c366a0)
