### ISSUE TITLE
it works I think it’s closed now

### ISSUE THREAD

**Issue by Plus018** [iptv-org/iptv#17426]
### Broken Link

https://ythls.armelin.one/channel/UCOV_Vx1baZJY9Tfvgm-UI3w.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

It’s broken it doesn’t work to watch update the ar.M3u remove broken streams

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Works fine?
Outta nowhere it becomes geo-blocked when using Indoor WIFI!!!
![Screenshot_20240904_145147_Chrome](https://github.com/user-attachments/assets/7f226f84-3ff6-47d3-b35a-f984997257f2)
