### ISSUE TITLE
Broken: Q-Music (1080p)

### ISSUE THREAD

**Issue by sn02** [iptv-org/iptv#17421]
### Broken Link

https://dpp-streamlive-plain.medialaancdn.be/qmusic/plain/hls.m3u8

### What happened to the stream?

Shows looped video

### Notes (optional)

New URL:
https://live-video.dpgmedia.net/f1d26a28c95485cc/out/v1/5f60a245c110454fba652900ecf30ea2/index.m3u8

If possible please also change the name to "_Qmusic (Belgium)_" to differentiate from the sister channel with the same name in the Netherlands.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
It works

**Comment by sn02** [comment]
No. It's a loop. Exactly 1 minute 32 seconds long. (You can fast forward in VLC.)

If you open the very same broke URL in VLC you get an loop with the clock displaying "17:05".
The same URL in SMplayer giving me an other loop where the clock shows 14:00". (1min 40sec loop)

**Comment by Sphinxroot** [comment]
no loop here

#EXTVLCOPT:http-referrer=https://qmusic.be/

kodi= https://live-video.dpgmedia.net/f1d26a28c95485cc/out/v1/5f60a245c110454fba652900ecf30ea2/index.m3u8|Referer=https://qmusic.be/

**Comment by Plus018** [comment]
Wrong it’s offline new pls

**Comment by Plus018** [comment]
Now it’s back online enjoy

**Comment by Plus018** [comment]
These stream link u Sent it’s a computer and u sent another one which is the studio. Here is. The new without carefull https://dpp-qmusicnl-live.akamaized.net/streamx/QmusicNL.m3u8

**Comment by Plus018** [comment]
https://dpp-qmusicbe-live.akamaized.net/streamx/QmusicBE
.m3u8

**Comment by Plus018** [comment]
The live-video.dpgmedia.net/live.akamaized.net/streamx/QmusicBE.m3u8

**Comment by Plus018** [comment]
https://live-video.dpgmedia.net/f1d26a28c95485cc/out/v1/5f60a245c110454fba652900ecf30ea2/index.m3u8 Which is a studio

**Comment by Plus018** [comment]
https://live-video.dpgmedia.net/f1d26a28c95485cc/out/v1/5f60a245c110454fba652900ecf30ea2/index.m3u8 Here without?

**Comment by Plus018** [comment]
Qmusicbe/index.m3u8

**Comment by Plus018** [comment]
https://live-video.dpgmedia.net/f1d26a28c95485cc/out/v1/5f60a245c110454fba652900ecf30ea2/index.m3u8

**Comment by Plus018** [comment]
https://live-video.dpgmedia.net/f1d26a28c95485cc/out/v1/5f60a245c110454fba652900ecf30ea2/Playlist.m3u8

**Comment by Plus018** [comment]
https://live-video.dpgmedia.net/f1d26a28c95485cc/out/v1/5f60a245c110454fba652900ecf30ea2/index.m3u8

**Comment by Plus018** [comment]
I think it works

**Comment by Plus018** [comment]
These u comment works
