### ISSUE TITLE
Broken: TV Trwam

### ISSUE THREAD

**Issue by Irylek** [iptv-org/iptv#17429]
### Broken Link

https://rd.insyscd.net/trwamtv.live/live/eds/tv-trwam/dash_fta/tv-trwam.mpd

### What happened to the stream?

Not loading

### Notes (optional)

use this instead:
https://live-ch1.trwam.cf.insyscd.net/out/v1/b99041a282774d4a8fe84a54243af5de/trwamtv-live-ch1.mpd
(it doesnt have token, the b99041a282..... isn't a token i am sure)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Works
![Screenshot_20240905_145034_VLC](https://github.com/user-attachments/assets/7dbe79e6-a662-41ce-b21c-9c92bd69fe63)

**Comment by freearhey** [comment]
The first link doesn't work in VLC either.

But the second one (https://live-ch1.trwam.cf.insyscd.net/out/v1/b99041a282774d4a8fe84a54243af5de/trwamtv-live-ch1.mpd) plays normally:

<img width="789" alt="image" src="https://github.com/user-attachments/assets/abc9924c-8067-4d9a-810c-55002664ac91">
