### ISSUE TITLE
Add: Parlamentsfernsehen 1

### ISSUE THREAD

**Issue by microraptor** [iptv-org/iptv#17428]
### Channel ID (required)

Parlamentsfernsehen1.de

### Channel Name

Parlamentsfernsehen 1

### Stream URL (required)

https://bttv-live-z.r53.cdn.tv1.eu/13014bundestag-hk1/_definst_/live/video/hk1_de.smil/playlist.m3u8

### Quality

1080p

### Label

Geo-blocked

### Notes

This source has higher quality than the already existing source "https://cldf-hlsgw.r53.cdn.tv1.eu/1000153copo/hk1.m3u8" (both streams seem to be geo-blocked). This is also the official source used on the website and is already used here for Parlamentsfernsehen 2, 3 and 4.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Works fine in the US.
