### ISSUE TITLE
Add: Himalaya TV

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#17434]
### Channel ID (required)

HimalayaTV.np

### Stream URL (required)

http://103.213.31.243:8081/livepull/ottHIMALAYA480.stream/playlist.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
Nah sorry it’s a music
