### ISSUE TITLE
Broken: Enfoque Digital tv 

### ISSUE THREAD

**Issue by Plus018** [iptv-org/iptv#17430]
### Broken Link

https://5eaccbab48461.streamlock.net:1936/8074/8074/playlist.m3u8

### What happened to the stream?

Not working
### Notes (optional)

![IMG_1519](https://github.com/user-attachments/assets/3f9385aa-a24e-447c-a38e-ce8d464d5afe)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
The reason why it started an earthquake in 06:12am

**Comment by Plus018** [comment]
A 5.5 magnitude started in chile

**Comment by Plus018** [comment]
5.7 magnitude is argentina.

**Comment by R4IN2007** [comment]
Plus is from Russia. Hey. Re&@tard Streams works there's nothing wrong with the URL. It's Streaming Prince of Bel-Air
![Screenshot_20240906_143119_Chrome](https://github.com/user-attachments/assets/40e7547a-6d29-49c7-b94b-031eba0b2310)

**Comment by guaymatetv** [comment]
https://glb.bozztv.com/glb/ssh101/guaymatetv/index.m3u8

**Comment by guaymatetv** [comment]
https://glb.bozztv.com/glb/ssh101/guaymatetv/index.m3u8
