### ISSUE TITLE
Add: ČT Decko with ČT art (CZ)

### ISSUE THREAD

**Issue by DenysMath** [iptv-org/iptv#17431]
### Channel ID (required)

CTDecko.cz

### Channel Name

ČT:D/ČT art

### Stream URL (required)

http://88.212.15.27/live/ct_art_avc_25p/playlist.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plus018** [comment]
http://88.212.15.27/live/ct_decko_avc_25p/playlist.m3u8

**Comment by Plus018** [comment]
Give me a sec

**Comment by Plus018** [comment]
http://88.212.7.10/live/test_ct-art/25p/playlist.m3u8

**Comment by Plus018** [comment]
http://88.212.15.27/live/ct_art_hevc_25p/playlist.m3u8

**Comment by Plus018** [comment]
It’s a ct decko http://88.212.15.27/live/ct_art_avc_25p/playlist.m3u8 not ct art

**Comment by DenysMath** [comment]
ČT Decko: 06:00-20:00 CET
ČT art: 20:00-06:00 CET

**Comment by Calokifilm** [comment]
The Website appears to be broken for some reason
