### ISSUE TITLE
Add: NBC West (San Diego)

### ISSUE THREAD

**Issue by rushereeeeee** [iptv-org/iptv#17445]
### Channel ID (required)

KNSDDT1.us

### Channel Name

NBC West (San Diego)

### Stream URL (required)

https://nbculocallive.akamaized.net/hls/live/2037098/sandiego/stream1/master.m3u8

### Quality

1080p

### Label

Not 24/7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Not that bad of quality 👍
![Screenshot_20240908_201950_Chrome](https://github.com/user-attachments/assets/b8045316-5257-4f08-ab07-c09ac8e58cd6)
