### ISSUE TITLE
Add: NBC East (Philadelphia)

### ISSUE THREAD

**Issue by rushereeeeee** [iptv-org/iptv#17444]
### Channel ID (required)

WCAUDT1.us

### Channel Name

(WCAUDT1) NBC East

### Stream URL (required)

https://nbculocallive.akamaized.net/hls/live/2035366/philadelphia/stream2/master.m3u8

### Quality

720p

### Label

None

### Notes

Backup link (Washington DC)
https://nbculocallive.akamaized.net/hls/live/2037099/washingtondc/stream1/master.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
404
