### ISSUE TITLE
Broken: AT-X

### ISSUE THREAD

**Issue by okonomitarou** [iptv-org/iptv#17440]
### Broken Link

https://neetball.net/live/neet3.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

I can't see AT-X. 
Thank you for your cooperation.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Not 24/7

**Comment by BellezaEmporium** [comment]
Please note that Neet's streams were always meant to be "test streams", as they're managed by an independent group.

**Comment by okonomitarou** [comment]
Does the fact that it is a test stream mean that the server is likely to crash?

**Comment by Dum4G** [comment]
See you in 2025, neetball
