### ISSUE TITLE
Add: NFL Redzone

### ISSUE THREAD

**Issue by jayc3-cmyk** [iptv-org/iptv#17457]
### Channel ID (required)

NFLRedzone.us

### Channel Name

NFL Redzone

### Stream URL (required)

https://v10.thetvapp.to/hls/NFLRedZone/tracks-v1a1/mono.m3u8?token=c3VoR0RxQjNWN3JXWHdNTnFkb2hhalVGQm1yVWY5WkxUNE1XOVppRg%3D%3D

### Quality

720p

### Label

None

### Timeshift

-4

### HTTP Referrer

https://v10.thetvapp.to/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by fdezwonders** [comment]
@jayc3-cmyk This link is tokenized, which means it expires in ~6hrs from when you first get the link.

**Comment by R4IN2007** [comment]
Urls from https://thetvapp.to/tv/ are tokenized! No luck from taking these. Token works under 1 minute to 6 hours.

**Comment by aceray50** [comment]
> ### Channel ID (required)
> NFLRedzone.us
> 
> ### Channel Name
> NFL Redzone
> 
> ### Stream URL (required)
> https://v10.thetvapp.to/hls/NFLRedZone/tracks-v1a1/mono.m3u8?token=c3VoR0RxQjNWN3JXWHdNTnFkb2hhalVGQm1yVWY5WkxUNE1XOVppRg%3D%3D
> 
> ### Quality
> 720p
> 
> ### Label
> None
> 
> ### Timeshift
> -4
> 
> ### HTTP User Agent
> _No response_
> 
> ### HTTP Referrer
> https://v10.thetvapp.to/
> 
> ### Notes
> _No response_
> 
> ### Contributing Guide
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

This code is no good: https://v10.thetvapp.to/hls/NFLRedZone/tracks-v1a1/mono.m3u8?token=c3VoR0RxQjNWN3JXWHdNTnFkb2hhalVGQm1yVWY5WkxUNE1XOVppRg%3D%3D

Try this, works for me: https://v1.thetvapp.to/hls/NFLRedZone/tracks-v1a1/mono.m3u8
