### ISSUE TITLE
Broken: Adult Swim East (720p) [Geo-blocked]

### ISSUE THREAD

**Issue by nikcec** [iptv-org/iptv#17475]
### Broken Link

https://turnerlive.warnermediacdn.com/hls/live/2023183/aseast/noslate/VIDEO_1_5128000.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Neither the East and the West (https://turnerlive.warnermediacdn.com/hls/live/2023185/aswest/noslate/VIDEO_1_5128000.m3u8) version are working

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Not 24/7. Still works.
