### ISSUE TITLE
El líder

### ISSUE THREAD

**Issue by deni858** [iptv-org/iptv#17478]
### Channel ID (required)

https://mdstrm.com/live-stream-playlist/6287fda8ea3b8b397d1ca2ed.m3u8

### Channel Name

Canal 5

### Stream URL (required)

https://mdstrm.com/live-stream-playlist/6287fda8ea3b8b397d1ca2ed.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Stream already in Playlist
https://github.com/iptv-org/iptv/blob/94763ebca3eb11cdcac8a17423c8648add8412c2/streams/hn.m3u#L20-L21
