### ISSUE TITLE
Broken: NASA TV Media (720p)

### ISSUE THREAD

**Issue by telanus** [iptv-org/iptv#17479]
### Broken Link

https://ntv2.akamaized.net/hls/live/2013923/NASA-NTV2-HLS/master.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us.m3u

Stream is no longer active currently displaying this:

![Screenshot_20240911_222444](https://github.com/user-attachments/assets/76192e16-07b1-4575-9e07-f43c58f37c69)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by telanus** [comment]
Same with:
#EXTINF:-1 tvg-id="NASATVPublic.us",NASA TV Public (720p)
https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8
#EXTINF:-1 tvg-id="NASATVUHD.us",NASA TV UHD (2160p)
https://endpnt.com/hls/nasa4k60/playlist.m3u8

**Comment by fdezwonders** [comment]
Yeah, NASA TV shut down in favor is plus.nasa.gov.

**Comment by R4IN2007** [comment]
NASA stopped streaming and started the streaming service for their shows & events only.
https://youtu.be/yVcxTCNsFHQ?si=faxLxmo1HUfLwGfn
