### ISSUE TITLE
Broken: pls update bbc persian  not work

### ISSUE THREAD

**Issue by gigplus** [iptv-org/iptv#17492]
### Broken Link

https://iptv-org.github.io/iptv/languages/fas.m3u

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by arash12100** [comment]
Please add Iran International and Persia Nostalgia...
These networks are not working
