### ISSUE TITLE
Add: ABC News Albania

### ISSUE THREAD

**Issue by ghost** [iptv-org/iptv#17531]
### Channel ID (required)

ABCNews.al

### Channel Name

ABC News

### Stream URL (required)

https://eu5cdn.overotm.com/abr_ovh003/abc_netup/playlist.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Currently stuck at the same chunk
