### ISSUE TITLE
Add: MEGOGO Sport UA

### ISSUE THREAD

**Issue by ghost** [iptv-org/iptv#17548]
### Channel ID (required)

MEGOGOSport.ua

### Channel Name

MEGOGO Sport

### Stream URL (required)

http://de.seetv.cc/play/1001/996DA9781004412/video.m3u8

### Quality

1080p

### Label

Not 24/7

### Notes

Database entry [#13551](https://github.com/iptv-org/database/issues/13551)

![image](https://github.com/user-attachments/assets/27b4371f-421a-40ac-8ee5-f9859c69bfeb)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Leaked link from a paid service
![image](https://github.com/user-attachments/assets/bc2db235-67f7-44ce-9fef-92d4a6604c9e)

**Comment by R4IN2007** [comment]
The redirect is to a Flussonic panel
