### ISSUE TITLE
Add: Dokusat

### ISSUE THREAD

**Issue by microraptor** [iptv-org/iptv#17544]
### Channel ID (required)

Dokusat.de

### Channel Name

Dokusat

### Stream URL (required)

https://muc3.iptv-playoutcenter.de/dokusat/dokusat1/playlist.m3u8

### Quality

1080p

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Works for me, maybe not geo-blocked

**Comment by BellezaEmporium** [comment]
Works for me too.

**Comment by microraptor** [comment]
Doesn't work on https://streamtest.in/ so I thought it is perhaps geo-blocked to German speaking countries or Europe
