### ISSUE TITLE
Broken: Fox News Channel

### ISSUE THREAD

**Issue by Cringe-Arab** [iptv-org/iptv#17553]
### Broken Link

http://stream1.cinerama.uz/1252/tracks-v1a1/mono.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

EDIT: Nwm it still lags

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Toei79** [comment]
no sound.

**Comment by richaardvark** [comment]
Works fine for me, sound and all ✅

Not that I would ever want to watch that channel... 🤢🤮😝

🫏🇺🇲✨

**Comment by richaardvark** [comment]
> It works now but tomorrow, closer to midday, the image will start to lag and the sound will disappear. I don't even know what this could be connected with

Hmm interesting. Maybe too much traffic for their server? Maybe try [this one](https://turnerlive.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_0_3564000.m3u8) instead? 😄😋

**Comment by Toei79** [comment]
Criptonyte lol

**Comment by Dum4G** [comment]
works fine now
