### ISSUE TITLE
Broken: nci channel

### ISSUE THREAD

**Issue by Sylquaza** [iptv-org/iptv#17554]
### Broken Link

https://pixa.cdn.easybroadcast.fr/nci/nci.isml/master.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Pro0183** [comment]
https://pixa.cdn.easybroadcast.fr/nci/nci.isml/index.m3u8

**Comment by Sylquaza** [comment]
Peut on le mettre sur le lien maitre ? Le mettre à jour ?
