### ISSUE TITLE
Add: GUAYMATETV

### ISSUE THREAD

**Issue by guaymatetv** [iptv-org/iptv#17562]
### Channel ID (required)

GuaymateTV.do

### Channel Name

Guaymate TV

### Stream URL (required)

https://glb.bozztv.com/glb/ssh101/guaymatetv/index.m3u8 

### Quality

1080p

### Label

Not 24/7

### Notes

¡Mira Guaymate TV aquí mismo de forma gratuita en
![EL CAFE DE LA TERDE (1)](https://github.com/user-attachments/assets/076c2017-b5b6-47fb-a4a2-f04b5a50e6fc)
!
Guaymate TV es un canal de televisión de República Dominicana que ofrece una programación variada y entretenida para toda la familia. Desde noticias y deportes hasta programas de entretenimiento y música, Guaymate TV tiene algo para todos. Disfruta de la mejor programación en alta definición y mantente informado con las últimas noticias locales e internacionales. ¡No te pierdas los programas más populares y los eventos más importantes del país en Guaymate TV!

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Toei79** [comment]
vaya es el mismo guaymatetv! supongo un amigo dominicano me pidio su canal hace como 7 meses. he like watching it , its from there !

**Comment by GUAYMATE71** [comment]
> vaya es el mismo guaymatetv! Supongo que un amigo dominicano me pidió su canal hace como 7 meses. A él le gusta verlo, ¡es de ahí!

SI MANITO ESTE MINUEVO  LINK DE MICANAL POR FOR CABIA LO POR ESTE  DILE ATU AMIGO QUE ESTE MI NUEVO LINK https://glb.bozztv.com/glb/ssh101/guaymatetv/index.m3u8

**Comment by R4IN2007** [comment]
Hey @BellezaEmporium They want the URL of the supposed channel of guaymate TV to be changed.
This (https://5790d294af2dc.streamlock.net/8100/8100/playlist.m3u8) to this (https://glb.bozztv.com/glb/ssh101/guaymatetv/index.m3u8)

**Comment by BellezaEmporium** [comment]
> Hey @BellezaEmporium They want the URL of the supposed channel of guaymate TV to be changed.
> This (https://5790d294af2dc.streamlock.net/8100/8100/playlist.m3u8) to this (https://glb.bozztv.com/glb/ssh101/guaymatetv/index.m3u8)

The bot detects that change actually

**Comment by R4IN2007** [comment]
> > Hey @BellezaEmporium They want the URL of the supposed channel of guaymate TV to be changed.
> > This (https://5790d294af2dc.streamlock.net/8100/8100/playlist.m3u8) to this (https://glb.bozztv.com/glb/ssh101/guaymatetv/index.m3u8)
> 
> The bot detects that change actually

Oh ok, good to know.

**Comment by GUAYMATE71** [comment]
https://glb.bozztv.com/glb/ssh101/guaymatetv/index.m3u8

**Comment by guaymatetv** [comment]
https://ssh101stream.ssh101.com/akamaissh101/ssh101/guaymatetv/playlist.m3u8

**Comment by guaymatetv** [comment]
> > Hey [@BellezaEmporium](https://github.com/BellezaEmporium) They want the URL of the supposed channel of guaymate TV to be changed.
> > This (https://5790d294af2dc.streamlock.net/8100/8100/playlist.m3u8) to this (https://glb.bozztv.com/glb/ssh101/guaymatetv/index.m3u8)
> 
> The bot detects that change actually

https://ssh101stream.ssh101.com/akamaissh101/ssh101/guaymatetv/playlist.m3u8

**Comment by guaymatetv** [comment]
https://ssh101stream.ssh101.com/akamaissh101/ssh101/guaymatetv/playlist.m3u8

**Comment by guaymatetv** [comment]
> > vaya es el mismo guaymatetv! Supongo que un amigo dominicano me pidió su canal hace como 7 meses. A él le gusta verlo, ¡es de ahí!
> 
> SI MANITO ESTE MINUEVO LINK DE MICANAL POR FOR CABIA LO POR ESTE DILE ATU AMIGO QUE ESTE MI NUEVO LINK https://ssh101stream.ssh101.com/akamaissh101/ssh101/guaymatetv/playlist.m3u8
