### ISSUE TITLE
Add: Myanmar Music

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#17560]
### Channel ID (required)

MyanmarMusic.mm

### Channel Name

Myanmar Music

### Stream URL (required)

https://l1-xl1.myanmarnet.com/relay/music/ch1/stream_hi/index.m3u8

### Quality

None

### Label

Not 24/7

### Notes

I just found this livestream link from a different website, but it works very fine.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Returns 404 to me @AVGCFan1995

**Comment by Dum4G** [comment]
![image](https://github.com/user-attachments/assets/d33d0bbe-cb8a-4002-827b-a8eeb9c69ec4)
ok not 24/7

**Comment by Dum4G** [comment]
Not in DB. Please make a request here https://github.com/iptv-org/database/issues/new?assignees=&labels=channels%3Aadd&projects=&template=__channels_add.yml&title=Add%3A+
