### ISSUE TITLE
But they changed it

### ISSUE THREAD

**Issue by Pro0183** [iptv-org/iptv#17566]
### Broken Link

https://l1-xl1.myanmarnet.com/relay/music/ch1/stream_hi/index.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Channel works

**Comment by Pro0183** [comment]
I think it’s some language I don’t know

**Comment by Dum4G** [comment]
Not in playlist
