### ISSUE TITLE
Broken: Lasa Tv

### ISSUE THREAD

**Issue by Pro0183** [iptv-org/iptv#17567]
### Broken Link

https://tvfile.lasatv.cn/nmip-media/channellive/channel104335/playlist.m3u8

### What happened to the stream?

Stuck at a single frame

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
@sunyuanzhe @Pro0183 Pro0183please confirm if works now

**Comment by Sphinxroot** [comment]
http://www.lasatv.cn/cms/tv  

https://tvfile.lasatv.cn/nmip-media/channellive/channel104335/playlist.m3u8
https://tvfile.lasatv.cn/nmip-media/channellive/channel101894/playlist.m3u8
https://tvfile.lasatv.cn/nmip-media/channellive/channel103157/playlist.m3u8

i get 403 forbidden 

Geoblocked ?

**Comment by Pro0183** [comment]
I got u
