### ISSUE TITLE
Add: Almost all the livestream links from Myanmar was restored.

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#17561]
### Channel ID (required)

5Plus.mm

### Channel Name

5 Plus

### Stream URL (required)

https://5a13fe32ef748.streamlock.net/mmplay/5plus/playlist.m3u8

### Quality

480p

### Label

None

### Notes

@BellezaEmporium @grinfelds @luisenick @pesekcuy Hey, guys! I found out that seven livestream links from 5a13fe32ef748.streamlock.net was restored and it was still online while other livestream channels such as 183.89.246.119:8881 and foreveralive1-a.akamaihd.net remains dead now.  And the I think why is 5a13fe32ef748.streamlock.net for several weeks and months which it causes by technical difficulties and not a shutdown. However, the other ten livestream channels from Myanmar like Channel 9, Education Channel, Fortune TV, Mahar Bawdi TV, MRTV Farmers, MRTV News, MRTV NRC, MRTV Sports, MWD, and YTV remains dead and it's harder to find the livestreams on different websites.

#EXTINF:-1 tvg-id="5Plus.mm",5 Plus (480p)
https://5a13fe32ef748.streamlock.net/mmplay/5plus/playlist.m3u8

#EXTINF:-1 tvg-id="Channel7.mm",Channel 7 (480p)
https://5a13fe32ef748.streamlock.net/mmplay/channel7/playlist.m3u8

#EXTINF:-1 tvg-id="MyanmarInternationalTV.mm",MITV (480p)
https://5a13fe32ef748.streamlock.net/mmplay/mitv/playlist.m3u8

#EXTINF:-1 tvg-id="MRTV.mm",MRTV (720p)
https://5a13fe32ef748.streamlock.net/mmplay/mrtv/playlist.m3u8

#EXTINF:-1 tvg-id="MRTV4.mm",MRTV 4 (480p)
https://5a13fe32ef748.streamlock.net/mmplay/mrtv-4/playlist.m3u8

#EXTINF:-1 tvg-id="MRTVEntertainment.mm",MRTV Entertainment (480p)
https://5a13fe32ef748.streamlock.net/mmplay/mrtv-entertainment/playlist.m3u8

#EXTINF:-1 tvg-id="MRTVParliament.mm",MRTV Parliament (480p)
https://5a13fe32ef748.streamlock.net/mmplay/hluttaw/playlist.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by luisenick** [comment]
hola amigo esos canales no son de mi pais, el reporte que yo realice es de un canal mexicano, el canal 5 de la empresa televisa
Hello friend, those channels are not from my country, the report that I made is from a Mexican channel, channel 5 of the "televisa" company

**Comment by AVGCFan1995** [comment]
> hola amigo esos canales no son de mi pais, el reporte que yo realice es de un canal mexicano, el canal 5 de la empresa televisa Hello friend, those channels are not from my country, the report that I made is from a Mexican channel, channel 5 of the "televisa" company

Yes, I know but why is the Mexican channel, channel 5 was remove just because the livestream link was not working any more or something.

**Comment by R4IN2007** [comment]
It was all televisa/TelevisaUnivision affiliate channels. Only Nu9ve - Nueve, ForoTV & Nmas+ were removed as well because it was Geo-blocked and also url was Access Denied and removing -notusa/-onlymex would removed the Geo-blocked access but now the would work using vpn using México IP but some would display an error of [Invaild URL] for the official link
Screenshot:
![Screenshot_20240918_222423_Chrome](https://github.com/user-attachments/assets/0b4fd2e9-9249-41ab-9642-76fbfbd4c49b)
