### ISSUE TITLE
I think they changed it to Indian version of 5 hd 

### ISSUE THREAD

**Issue by Pro0183** [iptv-org/iptv#17565]
### Broken Link

https://5a13fe32ef748.streamlock.net/mmplay/5plus/playlist.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Working

**Comment by Pro0183** [comment]
BRO

**Comment by Pro0183** [comment]
![Uploading IMG_1607.jpeg…]()

**Comment by Pro0183** [comment]
![IMG_1607](https://github.com/user-attachments/assets/b9afd320-f15f-4a5a-b212-172442ff997e)

**Comment by R4IN2007** [comment]
![Screenshot_20240922_174054_Chrome](https://github.com/user-attachments/assets/4f32dd0c-b24c-4214-a373-02fe3c79d2ce)
