### ISSUE TITLE
Add: BRTV Kaku Childrens Channe

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#17563]
### Channel ID (required)

BRTVKakuChildrensChannel.cn

### Stream URL (required)

http://222.173.9.81/00/SNM/CHANNEL00000661/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
@sunyuanzhe please confirm if works now

**Comment by freearhey** [comment]
http://222.173.9.81/00/SNM/CHANNEL00000661/index.m3u8 (offline)

<img width="431" alt="image" src="https://github.com/user-attachments/assets/fe9b69ac-6059-49b4-a37e-ab898211d814">
