### ISSUE TITLE
Add: RTB.bf

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#17574]
### Channel ID (required)

RTB.bf

### Stream URL (required)

https://edge20.vedge.infomaniak.com/livecast/ik:rtblive1_8/manifest.m3u8

### Quality

None

### Label

Not 24/7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Please show us a screenshot from VLC when it works. Wasn't able to load the stream multiple times

**Comment by Sphinxroot** [comment]
403 geo

**Comment by BellezaEmporium** [comment]
Infomaniak servers rarely take time to answer requests. Stream's not 24/7 for sure. 404 Not Found on my side.

**Comment by sunyuanzhe** [comment]
![vlcsnap-2024-10-15-10h37m45s831](https://github.com/user-attachments/assets/a50b8f15-4c7b-4c68-b276-e77a0812fb00)
