### ISSUE TITLE
Broken: NCI

### ISSUE THREAD

**Issue by Sylquaza** [iptv-org/iptv#17571]
### Broken Link

https://pixa.cdn.easybroadcast.fr/nci/nci.isml/index.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sylquaza** [comment]
Bonjour, le lien ne fonctionne plus merci pour votre action

**Comment by Pro0183** [comment]
https://pixa.cdn.easybroadcast.fr/nci/nci.isml/Playlist.m3u8
