### ISSUE TITLE
Broken: NoticiasCaracolAhora.co

### ISSUE THREAD

**Issue by cerels** [iptv-org/iptv#17573]
#EXTINF:-1 tvg-id="NoticiasCaracolAhora.co",Noticias Caracol Ahora (720p) [Not 24/7]
https://ythls.armelin.one/channel/UC2Xq2PK-got3Rtz9ZJ32hLQ.m3u8
 this is link is broken, the proper link is in https://mdstrm.com/live-stream-playlist/632391734be92a791e2750e6.m3u8
and it should be in co.m3u

**Comment by BellezaEmporium** [comment]
Changed recently.
