### ISSUE TITLE
Broken: NHL Network

### ISSUE THREAD

**Issue by Rinbusts** [iptv-org/iptv#17582]
### Broken Link

https://lnc-nhl.tubi.video/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Crashes player when trying to open, no other nhl channels appear when they should.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Goldiefresh** [comment]
Here's the same channel from a different source. 

https://nhl-firetv.amagi.tv/playlist.m3u8

**Comment by R4IN2007** [comment]
https://lnc-nhl.tubi.video/playlist.m3u8 - link offline

**Comment by vtjapes** [comment]
> Here's the same channel from a different source.
> 
> https://nhl-firetv.amagi.tv/playlist.m3u8

This is not NHL Network by the way.  It's just an NHL streaming channel playing the same videos over and over.
