### ISSUE TITLE
TVP CHANGED SOMETHING IN THE API!!!! - irylek.ct8.pl

### ISSUE THREAD

**Issue by Irylek** [iptv-org/iptv#17581]
### Broken Link

https://irylek.ct8.pl/stream/...

### What happened to the stream?

Not loading

### Notes (optional)

tvp vod changed something in the api. the stream can be down for a few minutes to few days. PLEASE BE PATIENT OKAY???

I will post updates here

20.09.2024 - 22:10 (UTC)

I am not sure but the api may require a token???

22.09.2024 - 16:25 (UTC)

I've just realized that something changed in the response of the API. No token is needed. Will bring it back at soon as possible.

**Comment by Irylek** [comment]
@Dum4G just realized that they just changed the response XD the channels should be back in 10 minutes.

**Comment by Irylek** [comment]
they are back! i am closing this issue

**Comment by Dum4G** [comment]
Great luck! Congratulations
