### ISSUE TITLE
Channels are hanging ever since I use this playlist

### ISSUE THREAD

**Issue by ithobbistpl** [iptv-org/iptv#17588]
### Buffering...

I don't know if it's just me, but I literally celebrated every day channels didn't just hanged and ruined my records. I blame it partially on VLC, because I know it just turns off playing when there is corruption, whatever if it's a video file or a TV channel, while f.e. MPC-HC can go on with that corrupted file. But it's annoying. Channel buffers bit too much -> channel turns off -> record stops, very often in most important part.

I honestly had same issue with other iptv streams with polish channels, so maybe it's fault of my internet (even if it tries really well to download that jumping bitrate from 10mbps to 40mbps even sometimes, at least that's how much data is beign downloaded, because on VLC it often says it's actually something between 3-15 mbps).

I still wanted to write about it, because it's so annoying. And the fact I once left VLC on and it recorded 1hour 23 minutes proves, that whatsoever it's not really fault of my intel core i3+intel HD graphics laptop (altough may be, as VLC turned into a wright mode and it recorded a record despite audio didn't worked at the playback and very often video freezed during recording; but anyways both usage of GPU and CPU is medium, and it jumps to 100 when I play 2 channels at once and have a browser in the background), and the fact very often it can record easily 12-30 minutes without an issue and without that weird state of VLC, but even today it loads few seconds, and off. Few seconds, and off. Few minutes, and off.

I think it really may be a fact that the channels are in original bitrate from a source, and my internet therefore lags trying to keep up, but it is indeed so annoying. Especially it's annoying, when TV channel shows a screen with subtitles that doesn;t move, and it turns off at that. That may be problem of the servers, but I don't see anyone else complaining really. But it is in fact weird, because TVN24 have s#!t bitrate like on satellite, and it still hangs a lot.

That's my whole issue really.  And also - if not VLC, then what? On Windows I had MPC-HC, but it doesnt record. And now on Linux I don't see anything else for a TV stream. YouTube with 1440p videos lag less, than iptv streams for me, and I'm bit tired.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
While we hear your concerns, we have nothing to do with the streams hanging. We only do an indexing job, nothing more.
