### ISSUE TITLE
Add: STAR HD

### ISSUE THREAD

**Issue by Pro0183** [iptv-org/iptv#17594]
### Channel ID (required)

StarChannel.gr

### Channel Name

STAR HD

### Stream URL (required)

http://livestar.siliconweb.com/starvod/star4/star4.m3u8

### Quality

None

### Label

Non geo blocked

### Notes

The coded height is 540 the coded width is 960 but here it’s none geo blocked
![IMG_1608](https://github.com/user-attachments/assets/d4620a8d-685a-4384-8c0d-4e4715de0114)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
http://livestar.siliconweb.com/starvod/star4/star4.m3u8 1080p.
