### ISSUE TITLE
Add: STAR

### ISSUE THREAD

**Issue by Pro0183** [iptv-org/iptv#17593]
### Channel ID (required)

StarChannelInternational.gr

### Channel Name

STAR International

### Stream URL (required)

https://livestar.siliconweb.com/starvod/star_int/star_int.m3u8

### Quality

720p

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
https://livestar.siliconweb.com/starvod/star_int/star_int.m3u8 1080p
