### ISSUE TITLE
Add: CNN US

### ISSUE THREAD

**Issue by Pro0183** [iptv-org/iptv#17596]
### Channel ID (required)

CNN.us

### Channel Name

CNN

### Stream URL (required)

http://162.246.20.30/mastervip/lista.php?id=1548

### Quality

720p

### Label

DONT KNOW

### Notes

The width is 1280P

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Xtream-Codes.
