### ISSUE TITLE
Add: BEIN SPORT 3 TR

### ISSUE THREAD

**Issue by Pro0183** [iptv-org/iptv#17597]
### Channel ID (required)

BEINSPORTS3.TR

### Channel Name

BEIN SPORTS 3 TR

### Stream URL (required)

http://6rlnsawt.tvclub.xyz/iptv/N6RW2X3HSTZFDP/6821/index.m3u8

### Quality

720p

### Label

DONT KNOW

### Notes

The width is 1280P

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Xtream-Codes & DMCAd channel. Two in a row.
