### ISSUE TITLE
Add: mtv club eu

### ISSUE THREAD

**Issue by Pro0183** [iptv-org/iptv#17591]
### Channel ID (required)

MTVCLUB.eu

### Channel Name

MTV club

### Stream URL (required)

http://34900a7f.megogo.xyz/iptv/N452PD2NQGMCCD/558/index.m3u8

### Quality

576p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Russian IPTV system that takes off tokens pretty quickly.

**Comment by Plan018** [comment]
It’s done it broke

**Comment by Plan018** [comment]
http://34900a7f.megogo.xyz/iptv/N452PD2NQGMCCD/558/index.m3u8

**Comment by dacarkys** [comment]
Hi, an error appears. Could you please try to fix it? Thanks in advance.
