### ISSUE TITLE
Broken: Fox32

### ISSUE THREAD

**Issue by R4736** [iptv-org/iptv#17602]
### Broken Link

https://lnc-wfld.tubi.video/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Fox32 link has been down a few days.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plan018** [comment]
https://nhl-firetv.amagi.tv/index.m3u8

**Comment by Plan018** [comment]
Idt it works but I can’t do it

**Comment by jnjustice** [comment]
@brokenstream I actually posted about this here too https://github.com/orgs/iptv-org/discussions/1914

It appears Tubi changed the URL format unless the app is different but I saw what I commented on their website in the network requests.
