### ISSUE TITLE
Add: gongyoung shopping 720P

### ISSUE THREAD

**Issue by Plan018** [iptv-org/iptv#17603]
### Channel ID (required)

GongYoung.kr 

### Channel Name

GONGYOUNG SHOPPING 

### Stream URL (required)

https://etv.publichs.com/live5.stream/playlist.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Already in Playlist.
https://github.com/iptv-org/iptv/blob/993e2b6c404377ef0401117989d682bf9624e651/streams/kr.m3u#L62-L63
