### ISSUE TITLE
Broken: telecentro ar

### ISSUE THREAD

**Issue by Plan018** [iptv-org/iptv#17619]
### Broken Link

https://stream-gtlc.telecentro.net.ar/hls/telemaxhls/0/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

They are offline

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Not telecentro. Wrong channel
