### ISSUE TITLE
Add: kurir 

### ISSUE THREAD

**Issue by Plan018** [iptv-org/iptv#17614]
### Channel ID (required)

Kurir.rs

### Channel Name

Kurir

### Stream URL (required)

https://static.am.mediaoutcast.com/storage/nQJnjJkO/nQJnjJkO/stream/O68x4o8g/720p/720p.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Plan018** [comment]
Don’t know it’s Latin https://nxt.plus:8443/live/jesus01/jesus01/16909.m3u8

**Comment by Plan018** [comment]
Don’t know the channel name it’s from usa 	https://2-fss-2.streamhoster.com/pl_138/201660-1270634-1/playlist.m3u8

**Comment by Plan018** [comment]
From us i think I don’t know the channel name http://30a-tv.com/music.m3u8

**Comment by Plan018** [comment]
From Austria https://bitcdn-kronehit.bitmovin.com/v2/hls/playlist.m3u8

**Comment by Plan018** [comment]
https://59959724487e3.streamlock.net/stream/live/playlist.m3u8?fluxustv.m3u8

**Comment by Plan018** [comment]
Augs Burg tv de https://augsburgtv.iptv-playoutcenter.de/augsburgtv/augsburgtv.stream_1/playlist.m3u8

**Comment by Plan018** [comment]
Wow tv http://cdn.elsalvadordigital.com:1935/wowtv/wowtv/playlist.m3u8

**Comment by Plan018** [comment]
http://amdlive.ctnd.com.edgesuite.net/arirang_1ch/smil:arirang_1ch/playlist.m3u8

**Comment by Plan018** [comment]
Korea

**Comment by Plan018** [comment]
http://12channel.bonus-tv.ru/cdn/12channel/playlist_hdhigh.m3u8

**Comment by Plan018** [comment]
http://wms.shared.streamshow.it/visualradio/mp4:visualradio/chunklist.m3u8 Visual radio us

**Comment by Plan018** [comment]
Cna 	http://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_4.m3u8

**Comment by Plan018** [comment]
https://donelfantastic.github.io/live/optusSportAu1.m3u8 Sport au 1

**Comment by Plan018** [comment]
It was abc 7 http://41.205.93.154/ABC/index.m3u8

**Comment by Plan018** [comment]
http://41.205.93.154/BBCTWO/index.m3u8 BBC TWO

**Comment by Plan018** [comment]
http://41.205.93.154/NBA/index.m3u8

**Comment by Plan018** [comment]
http://41.205.93.154/HISTORY/index.m3u8 Us

**Comment by Plan018** [comment]
http://41.205.93.154/FOXBUSINESS/index.m3u8

**Comment by Plan018** [comment]
https://twcprod-live.twc-tv.com/v1/manifest/b4d4d63a49309cc5140171fb2e92485c31be1e9e/DSP_6228e4760505741a116f1ba2_twcprod-live/6bf09ce5-366b-463c-b67e-c4b799f73c3f/4.m3u8

**Comment by Plan018** [comment]
Weather news?

**Comment by Plan018** [comment]
https://mako-streaming.akamaized.net/stream/hls/live/2033791/k12dvr/profile/2/hdntl=exp=1678643062~acl=%2f*~data=hdntl~hmac=18c79b0af2b2719de95b2a0adb22904c97558548be9d2e7185eb045805a10abd/profileManifest.m3u8?_uid=9eb5dcb7-bbf0-4cf6-87d0-73127c4116b6&rK=a2

**Comment by Plan018** [comment]
12 gr

**Comment by Plan018** [comment]
http://162.19.37.133:8080/play/live.php?mac=00:1A:79:B2:CB:FA&stream=131368&extension=ts

**Comment by Plan018** [comment]
http://162.19.37.133:8080/play/live.php?mac=00:1A:79:B2:CB:FA&stream=131368&extension=ts It’s just Musique donce

**Comment by Plan018** [comment]
https://rpn3.bozztv.com/dvrfl07/ushba90/index.m3u8 Try vlc or extreme code

**Comment by Plan018** [comment]
From Korea https://stream01.willfonk.com/live_playlist.m3u8?cid=BS241&r=FHD&ccode=JP&m=d0:20:20:04:35:cc&t=0d6938cb3dcf4b79848bc1753a59daf1

**Comment by Plan018** [comment]
https://racingvic-i.akamaized.net/hls/live/598695/racingvic/index1500.m3u8

**Comment by Plan018** [comment]
http://143.244.60.30/HBO/index.m3u8

**Comment by Plan018** [comment]
https://ais-sa1.streamon.fm/7647_48k.aac?uuid=nv8sbvc1

**Comment by Plan018** [comment]
https://csm-e-eb.csm.tubi.video/csm/extlive/tubiprd01,Cloudfront-KMBC.m3u8

**Comment by Plan018** [comment]
https://linear-59.frequency.stream/dist/plex/59/hls/master/playlist.m3u8

**Comment by Plan018** [comment]
https://cvtv.cvalley.net/hls/KMBCMeTV/KMBCMeTV.m3u8

**Comment by Plan018** [comment]
Filename	https://cdn.jmvstream.com/w/LVW-10801/LVW10801_Xvg4R0u57n/playlist.m3u8?ManoTV

**Comment by Plan018** [comment]
https://cdn-5.nxplay.com.br/GLOBO_SP_TK/index.m3u8

**Comment by Plan018** [comment]
https://stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/619e4a3518d6970008bebc95/master.m3u8?deviceDNT=%7B%7D&deviceType=%7B%7D&deviceMake=%7B%7D&deviceModel=%7B%7D&deviceVersion=unknown&deviceId=%7B%7D&appVersion=unknown

**Comment by Plan018** [comment]
![](https://crossproxy.yushuf98.workers.dev/?a=https://noxlive11.xyz/cdn/bein-sports-1-1727123376954.jpeg)

**Comment by Plan018** [comment]
https://crossproxy.yushuf98.workers.dev/?a=https://noxlive11.xyz/cdn/bein-sports-1-1727123376954.jpeg)

**Comment by BellezaEmporium** [comment]
You know, Plus018, there's no need to create multiple accounts to ask for channels.

**Comment by Plan018** [comment]
PLAN

**Comment by Plan018** [comment]
http://45.32.115.103/live/livestream/index.m3u8?checkedby:iptvcat.com

**Comment by Plan018** [comment]
https://raigeneric3-live.akamaized.net/hls/live/619174/raigeneric3/raigeneric3/playlist.m3u8?auth=daEb7aXaAbPdnc4bEbYbrbDchbua.ald4bz-bLl7J8-c0-JjAuxFo&aifp=V001 Non geo blocked

**Comment by Plan018** [comment]
https://stream1.freetv.fun/893840fd7b46528717f4f90cb37bde95455239ad7879a5860838530bca5f793e.m3u8

**Comment by Plan018** [comment]
Use VLC it’s cctv 17 found it

**Comment by Plan018** [comment]
Update the cn.m3u

**Comment by Plan018** [comment]
https://main-x.lvnv.serverlinq.online/play/jYiXTwtWZoijW95R2o8L8UT1ZgLkG8MiE8HjBhaCngeDFlJXFJb5Qp66fZPVTGvF

**Comment by Plan018** [comment]
Off air use VLC wait until 8p u can watch but 6am u can’t watch u have to wait https://main-x.lvnv.serverlinq.online/play/jYiXTwtWZoijW95R2o8L8UT1ZgLkG8MiE8HjBhaCngeDFlJXFJb5Qp66fZPVTGvF

**Comment by Plan018** [comment]
http://170791852445882761.ofkp0923.xyz/play/5TVA3R9NK3/BJUXCPbtEKh/882761.ts?Billybob.has.had.shits.smarter.than.you.guys! Albania news 24 hd

**Comment by Plan018** [comment]
http://185.236.229.131:8000/play/5TVA3R9NK3/BJUXCPbtEKh/882761.ts?Billybob.has.had.shits.smarter.than.you.guys!&token=H0EMV0RQRl8UA1tVVlVQXlJQWwZQCFZQBAJRAVteVABWBQJVVApdBAdDFRZAFkBdBw48WFASDVwNBVEOUhQXRhcGFmleXEZfFFILBgZXABpKQRdYWVUVXgQAVA9QDQQCXVZIFEdRAEcMQw0FBVMFGkpBBklAVUUKVFs5XAZOXFABQV5YQlQISRQOV2tXB19ZCAdBCxYBFUgXXhVIQQJbRggPSBRVURAXVxVcFgkMR1QKT0FSW0VZEEdORAJBeXkRSEEBTkNdChZfDlcWCUBGS0RPQVhHb0UBRkMUXQJVUEFGWUYGFRRGCFcZZldcDFxdBRcKXlpDFV4XBEQUQVVaXQ0XC0RoSA0BFFsbAAJXBwFEHg==Use vlc it’s Albania news 24 hd

**Comment by Plan018** [comment]
https://ythls.armelin.one/channel/UCxA_zZwALQMmVMSZyLKC-Nw.m3u8

**Comment by Plan018** [comment]
VLC

**Comment by Plan018** [comment]
http://cord-cutter.net:[8080/25464931](tel:8080/25464931)/30585186/57264 
VLC

**Comment by Plan018** [comment]
VLC http://cord-cutter.net:%5B8080/25464931%5Dtel:8080/25464931/30585186/57264

**Comment by Plan018** [comment]
https://cdnjkt4.transvision.co.id:1004/live/master/3/4028c6856c3db2cc016cd6e9c5992395/manifest.mpd

**Comment by Plan018** [comment]
Vlc

**Comment by Plan018** [comment]
http://authxplus-2.xyz:2082/live/Tourobox1-APhnnJ6sQS/7nAiGmzfNG/131.m3u8

**Comment by Plan018** [comment]
Use vlc

**Comment by Plan018** [comment]
https://d35j504z0x2vu2.cloudfront.net/v1/master/0bc8e8376bd8417a1b6761138aa41c26c7309312/bein-sports-xtra-en-espanol/playlist.m3u8

**Comment by Plan018** [comment]
http://200.189.113.201/hls/tve.m3u8

**Comment by Plan018** [comment]
https://d1ei8ofhgfmkac.cloudfront.net/app-19518-1306/ngrp:QoZfNjsg_all/chunklist_w906337043_b6256000.m3u8

**Comment by Plan018** [comment]
Euronews Serbia 24/7

**Comment by Plan018** [comment]
https://d1ei8ofhgfmkac.cloudfront.net/app-19518-1306/ngrp:QoZfNjsg_all/chunklist_w906337043_b6256000.m3u8 Fine euronews Serbia 24/7
