### ISSUE TITLE
Add canal 2 El Salvador 

### ISSUE THREAD

**Issue by KarenU04** [iptv-org/iptv#17625]
Add canal 2 El Salvador

**Comment by R4IN2007** [comment]
Already in Playlist
https://github.com/iptv-org/iptv/blob/df9fc51dcbbc6433a08fc640c97649c83526417d/streams/sv.m3u#L6-L7

**Comment by KarenU04** [comment]
Gracias muy amable

**Comment by Dum4G** [comment]
![image](https://github.com/user-attachments/assets/0da6ceb0-3f64-441c-bfd0-08be95dd428c)

**Comment by R4IN2007** [comment]
Hey @Dum4G do you know how to get m3u8 url or file from a Mac address?

**Comment by KarenU04** [comment]
![IMG_2646](https://github.com/user-attachments/assets/66f790e1-1a8e-4788-b7fe-72f2f4d35bc7)  verificar canal 2 El Salvador  dejo de funcionar https://telecorporacion-es.cdn.vustreams.com/live/d3e259fa-736d-46b0-b1c9-71caf946ace9/live.isml/live.m3u8

**Comment by R4IN2007** [comment]
> ![IMG_2646](https://private-user-images.githubusercontent.com/183173941/386923699-66f790e1-1a8e-4788-b7fe-72f2f4d35bc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NzE5MzksIm5iZiI6MTczMTg3MTYzOSwicGF0aCI6Ii8xODMxNzM5NDEvMzg2OTIzNjk5LTY2Zjc5MGUxLTFhOGUtNDc4OC1iN2ZlLTcyZjJmNGQzNWJjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxOTI3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWViZThlMTdlN2Y0ODMzN2JhYmJhZGQyMzJhODQ3ZTlhZDc5NTc5MjM1YzVlZWE4NzY5NWVkNWNlM2YyMjZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Y3ftB6fqF1nyQNKAeVncc9G9CfZB-5Kxh9j8YMX3jA4) verificar canal 2 El Salvador dejo de funcionar https://telecorporacion-es.cdn.vustreams.com/live/d3e259fa-736d-46b0-b1c9-71caf946ace9/live.isml/live.m3u8

![Screenshot_20241117_132704_Chrome](https://github.com/user-attachments/assets/869a87c7-22c3-4278-9d93-cd7b4af599d0)
