### ISSUE TITLE
Add: the Latin version cartoon 

### ISSUE THREAD

**Issue by Plan018** [iptv-org/iptv#17620]
### Channel ID (required)

No

### Channel Name

I don’t know 

### Stream URL (required)

 https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5f6df6293a12e10007017396/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5f6df6293a12e10007017396&deviceLat=-23.5475&deviceLon=-46.6361&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=BR&serverSideAds=false&sid=731&terminate=false&userId

### Quality

360p

### Label

Not 24/7

### Notes

But rewind it it’s gonna be live 24/7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Irylek** [comment]
seems tokenized. it has those deviceId, deviceLat and DeviceLon but idk.

**Comment by Toei79** [comment]
what country its this pluto one? see differents maybe in argentina.

**Comment by R4IN2007** [comment]
Keep hearing the word  "você" so It might be from Pluto TV Latin (Brazil Version)

**Comment by R4IN2007** [comment]
Already in Playlist? and also has wrong tvg-id
Actual id (AvidamodernadeRocko.br) if not maybe it's US Version of it.
Channel Name: Eng rocko modern life [Nickelodeon] / Br: A Vida Moderna de Rocko
![Screenshot_20240927_104643_Chrome](https://github.com/user-attachments/assets/dce235a6-5e24-481c-b0b1-ec69427706d9)
