### ISSUE TITLE
Broken: Telemundo East

### ISSUE THREAD

**Issue by alexmdty** [iptv-org/iptv#17623]
### Broken Link

https://cdn.igocast.com/wkrp_channel1_hls/wkrp_channel1_master.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Maybe your internet signal because it works fine.
