### ISSUE TITLE
Broken: Mega TV 720P [Geo Blocked]

### ISSUE THREAD

**Issue by trancer1994** [iptv-org/iptv#17639]
### Broken Link

https://c98db5952cb54b358365984178fb898a.msvdn.net/live/S86713049/gonOwuUacAxM/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Mega TV from Greece won't work on VLC even though it says geoblocked. The problem turned out to be with the link itself though, not the geoblocking. Firefox said it couldn't find the file at the link specified in the playlist. So here is the link to the live stream for Mega TV from their website. I need someone to rip the m3u8 file out of the page since the stream detector which is normally very good at these things won't do it. https://www.megatv.com/live/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
they now use web socket streaming 

https://lb.cdn.vindral.com/api/v2/connect/?channelId=alteregomedia_megatv1_ci_6cc490c7-e5c6-486b-acf0-9bb9c20fa670

host
ams4-edge-01.cdn.vindral.com
origin
https://embed.vindral.com


not sure where to go next

**Comment by griptvlive** [comment]
I am doing my best to find a link for Mega
