### ISSUE TITLE
Broken: All the JOJ channels are broken

### ISSUE THREAD

**Issue by trancer1994** [iptv-org/iptv#17640]
### Broken Link

Multiple

### What happened to the stream?

Not loading

### Notes (optional)

I'm sorry to open a new issue again, however this time it's about the Joj channels from Slovakia. They are all broken, they don't work in VLC, and just like the megatv.gr issue the links don't work in Firefox either, they all just point to firefox cannot find the file at *insert URL*. 

The broken links, for context, are (extracted from the playlist):
#EXTINF:-1 tvg-id="JOJ24.sk" tvg-logo="https://i.imgur.com/Tv12wOd.png" group-title="News",JOJ24 (1080p)
https://live.cdn.joj.sk/live/andromeda/joj_news-1080.m3u8
#EXTINF:-1 tvg-id="JOJCinema.sk" tvg-logo="https://i.imgur.com/5Auduch.png" group-title="Movies",JOJ Cinema (1080p)
https://live.cdn.joj.sk/live/andromeda/cinema-1080.m3u8
#EXTINF:-1 tvg-id="JOJFamily.sk" tvg-logo="https://i.imgur.com/k1COMHi.png" group-title="Family",JOJ Family (1080p)
https://live.cdn.joj.sk/live/andromeda/family-1080.m3u8
#EXTINF:-1 tvg-id="JOJPlus.sk" tvg-logo="https://i.imgur.com/1LHa0EI.png" group-title="Entertainment",JOJ Plus (1080p)
https://live.cdn.joj.sk/live/andromeda/plus-1080.m3u8
#EXTINF:-1 tvg-id="JOJSport.sk" tvg-logo="https://i.imgur.com/KirqaU4.png" group-title="Sports",JOJ Šport (1080p)
https://live.cdn.joj.sk/live/andromeda/joj_sport-1080.m3u8
#EXTINF:-1 tvg-id="JOJWAU.sk" tvg-logo="https://i.imgur.com/j51uAjL.png" group-title="Entertainment",JOJ WAU (1080p)
https://live.cdn.joj.sk/live/andromeda/wau-1080.m3u8
#EXTINF:-1 tvg-id="Jojko.sk" tvg-logo="https://i.imgur.com/JBB1n1Z.png" group-title="Kids",Jojko (1080p)
https://live.cdn.joj.sk/live/andromeda/jojko-1080.m3u8

The link to Joj at least, from which you need to rip the new m3u8 URL from (plays in firefox but the one ithe stream detector gives me doesn't work and points to a 404) is https://media.joj.sk/embed/EMkFULcpYQH?autoplay=1
The rest of them can be found on https://live.joj.sk/

Cheers, and sorry for the workload. 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by trancer1994** [comment]
Firefox brings up a 404 when I try to go to the second link with it, the one with the referer. Do Codi links work on browsers?

________________________________

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-id="JOJ24.sk" tvg-logo="https://i.imgur.com/Tv12wOd.png" group-title="News",JOJ24 (720p)
https://live.cdn.joj.sk/live/andromeda/joj_news-720.m3u8|Referer=https://media.joj.sk/
#EXTINF:-1 tvg-id="JOJCinema.sk" tvg-logo="https://i.imgur.com/5Auduch.png" group-title="Movies",JOJ Cinema (720p)
https://live.cdn.joj.sk/live/andromeda/cinema-720.m3u8|Referer=https://media.joj.sk/
#EXTINF:-1 tvg-id="JOJFamily.sk" tvg-logo="https://i.imgur.com/k1COMHi.png" group-title="Family",JOJ Family (720p)
https://live.cdn.joj.sk/live/andromeda/family-720.m3u8|Referer=https://media.joj.sk/
#EXTINF:-1 tvg-id="JOJPlus.sk" tvg-logo="https://i.imgur.com/1LHa0EI.png" group-title="Entertainment",JOJ Plus (720p)
https://live.cdn.joj.sk/live/andromeda/plus-720.m3u8|Referer=https://media.joj.sk/
#EXTINF:-1 tvg-id="JOJSport.sk" tvg-logo="https://i.imgur.com/KirqaU4.png" group-title="Sports",JOJ Šport (720p)
https://live.cdn.joj.sk/live/andromeda/joj_sport-720.m3u8|Referer=https://media.joj.sk/
#EXTINF:-1 tvg-id="JOJWAU.sk" tvg-logo="https://i.imgur.com/j51uAjL.png" group-title="Entertainment",JOJ WAU (720p)
https://live.cdn.joj.sk/live/andromeda/wau-720.m3u8|Referer=https://media.joj.sk/
#EXTINF:-1 tvg-id="Jojko.sk" tvg-logo="https://i.imgur.com/JBB1n1Z.png" group-title="Kids",Jojko (720p)
https://live.cdn.joj.sk/live/andromeda/jojko-720.m3u8|Referer=https://media.joj.sk/

#EXTINF:-1 tvg-id="" tvg-logo="https://i.imgur.com/cXzdnhJ.jpeg" group-title="",JOJ S VAMI  (720p)
https://live.cdn.joj.sk/live/andromeda/joj-720.m3u8|Referer=https://media.joj.sk/

**Comment by Sphinxroot** [comment]
if your browser dont handle referer  it wont work

**Comment by trancer1994** [comment]
Ok.
________________________________

**Comment by jarkoacjak** [comment]
Joj Šport 2: https://live.cdn.joj.sk/live/andromeda/joj_sport2-1080.m3u8
