### ISSUE TITLE
Broken: MTV Lebanon

### ISSUE THREAD

**Issue by elietannoury98** [iptv-org/iptv#17648]
Hello, [this link](https://github.com/iptv-org/iptv/blob/ced15680283c5613a5a84b97ace1f69acd69902a/streams/lb.m3u#L24) provided for MTV Lebanon is not working anymore, any plans to update it?

**Comment by griptvlive** [comment]
It is closed thanks to the developments that are happening with the country (probably if you follow the news you understand what I'm saying)

**Comment by RayRaytheGrape** [comment]
Can't even find the channel now
