### ISSUE TITLE
Broken: RTI LA 3

### ISSUE THREAD

**Issue by Sylquaza** [iptv-org/iptv#17666]
### Broken Link

https://www.enovativecdn.com/rticdn/smil:rti3.smil/playlist.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Carlinhos027** [comment]
This channel is Geo-blocked, but it works.
