### ISSUE TITLE
Broken: RTI2

### ISSUE THREAD

**Issue by Sylquaza** [iptv-org/iptv#17665]
### Broken Link

https://www.enovativecdn.com/rticdn/smil:rti2.smil/playlist.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Carlinhos027** [comment]
Working for me...
Maybe is Not 24/7.

![Screenshot_20241005_132121](https://github.com/user-attachments/assets/3b202257-9dac-4dd8-aead-88d8f9b100f4)
