### ISSUE TITLE
Broken: RTI1

### ISSUE THREAD

**Issue by Sylquaza** [iptv-org/iptv#17664]
### Broken Link

https://www.enovativecdn.com/rticdn/smil:rti1.smil/playlist.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Carlinhos027** [comment]
Works for me...
