### ISSUE TITLE
IMPORTANT: I think you guys should remove TVP1 / TVP Sport temporary.

### ISSUE THREAD

**Issue by Irylek** [iptv-org/iptv#17674]
Like, i don't want to the repository deleted AGAIN, but the TVP have license to play "UEFA: Premier League", and i think you know where i am going to. Basically it was DMCA takedown as seen here: https://github.com/iptv-org/iptv/issues/6973 , but they started playing it at the moment as seen in the screenshots.

![vlcsnap-2024-10-02-22h45m52s874](https://github.com/user-attachments/assets/ad65656b-86f6-47e1-a2f1-5a2ce8c50f72)
![vlcsnap-2024-10-02-22h50m26s248](https://github.com/user-attachments/assets/0ee41148-c1da-4413-b620-3ed2be992451)

Btw looks like the stream from me (thats starts with irylek.ct8.pl/stream/...) are affected. the stream from orange dont have license to play it online so they just display this screen:

![vlcsnap-2024-10-02-22h54m23s844](https://github.com/user-attachments/assets/e4fbc8ca-df04-4405-8198-e77af7898d53)

so yeah, maybe im wrong, maybe not but you guys should check it out.

**Comment by BellezaEmporium** [comment]
If they do retransmit such content, then we won't have any choice but to add them onto the blocklist, and thus, be blocked from being ever added back.

**Comment by BellezaEmporium** [comment]
Decision has been taken to add them into the blocklist, from what has been seen.

**Comment by BellezaEmporium** [comment]
Thank you for the heads-up @Irylek , we've made the necessary changes.

**Comment by Irylek** [comment]
> Thank you for the heads-up @Irylek , we've made the necessary changes.

np
