### ISSUE TITLE
Broken: Healing Center TV (ZM)

### ISSUE THREAD

**Issue by telanus** [iptv-org/iptv#17673]
### Broken Link

https://dcunilive258-lh.akamaihd.net/i/dclive_1@348579/master.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Checked their website, and their live stream is now behind a login, that offer a subscription.

EDIT: Had a look at the "free" stream, they offer, and it seems like a promo for their paid streams, and is tied to the login 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
https://pvqybrzodz24-hls-live.5centscdn.com/6164_push_2338_002/3ee2c5e549a41b2a1b5f2fd3789e38a3.sdp/playlist.m3u8?
