### ISSUE TITLE
Broken: MTV Germany

### ISSUE THREAD

**Issue by stormcore24** [iptv-org/iptv#17680]
### Broken Link

https://0d26a00dfbb1.airspace-cdn.cbsivideo.com/mtvg18ef/master/master_5000.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Doesn't work on their website either and it seems they have taken away: https://www.mtv.de/live/0h9eak

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Maybe the with the US version. Paramount stopped MTV from streaming online.
``Fastly error: unknown domain: 0d26a00dfbb1.airspace-cdn.cbsivideo.com. Please check that this domain has been added to a service.

Details: cache-fra-etou8220028-FRA (146.75.121.188)``

**Comment by Heckie75** [comment]
MTV Germany (https://0d26a00dfbb1.airspace-cdn.cbsivideo.com/mtvg18ef/master/master_5000.m3u8) and also Nickelodeon Germany (https://0d26a00dfbb1.airspace-cdn.cbsivideo.com/nick1999/master/nick1999.m3u8) is not available anymore.
