### ISSUE TITLE
Add: CTN

### ISSUE THREAD

**Issue by sunminghua1975** [iptv-org/iptv#17683]
### Channel ID (required)

CTN.kh

### Stream URL (required)

http://live.happywatch99.com/livehd10/02587745dbd71d978954203d7ec78497.sdp/playlist.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Seems to be retransmitting a stream, and i believe it got on a whoopsie here. (loss of signal)

![image](https://github.com/user-attachments/assets/aabb6946-e7f5-4218-8e5e-5441cbff2cb5)
