### ISSUE TITLE
Add: HealingCenterTV.zm

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#17693]
### Channel ID (required)

HealingCenterTV.zm

### Stream URL (required)

https://pvqybrzodz24-hls-live.5centscdn.com/6164_push_2338_002/3ee2c5e549a41b2a1b5f2fd3789e38a3.sdp/playlist.m3u8

### Quality

None

### Label

None

### Notes

https://github.com/iptv-org/iptv/issues/17673

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Carlinhos027** [comment]
Doesn't work for me lol

**Comment by Dum4G** [comment]
My bad, link updated
