### ISSUE TITLE
Broken: Canal 9 Resistencia

### ISSUE THREAD

**Issue by idk17461** [iptv-org/iptv#17706]
### Broken Link

http://201.217.245.41:8081/testmelucas/canal9/playlist.m3u8

### What happened to the stream?

Other

### Notes (optional)

Shows 404 error instead of the stream

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Creo que este no es pero es de 9Link
http://coninfo.net:1935/9linklivert/smil:9linkmultibr.smil/playlist.m3u8
