### ISSUE TITLE
Add: MRTV4

### ISSUE THREAD

**Issue by sunminghua1975** [iptv-org/iptv#17707]
### Channel ID (required)

MRTV4.mm

### Channel Name

MRTV 4

### Stream URL (required)

https://pplive.comquas.com:5443/LiveApp/streams/w3g3EYjBtqgJ1677679288037.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Channel 7 is https://pplive.comquas.com:5443/LiveApp/streams/CLcBFN71NkF61709008601656.m3u8

မဟာဗောဓိ is https://pplive.comquas.com:5443/LiveApp/streams/rHEBIW7pjQLU1677679374164.m3u8
