### ISSUE TITLE
Add: NHK E

### ISSUE THREAD

**Issue by Alstruit** [iptv-org/iptv#17718]
### Channel ID (required)

NHKEducationalTV.jp

### Channel Name

NHK E

### Stream URL (required)

https://vnpt.nekocdn.xyz/d074504f-ca7a-467e-a67c-a91e69461775.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Worked at first, then my antivirus flagged it as "potentially malicious -> file download"

**Comment by spotanjo3** [comment]
Isnt working at all.

I am looking for NHK WORLD ENGLISH in 4m. Not 2m because alots of pixels if road bike moved faster.
