### ISSUE TITLE
Add: TV Asahi

### ISSUE THREAD

**Issue by Alstruit** [iptv-org/iptv#17716]
### Channel ID (required)

JOEXDTV.jp

### Channel Name

TV Asahi

### Stream URL (required)

https://vnpt.nekocdn.xyz/0fc25793-9d0a-459d-b645-46254bd89616.m3u8

### Quality

720p

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Not working.

**Comment by olstern01** [comment]
Works for me.

![スクリーンショット 2024-10-11 061648](https://github.com/user-attachments/assets/7d46c608-7b1e-4e8b-acb2-174ee34192f2)

**Comment by Sphinxroot** [comment]
{"code":404,"message":"File not found","details":["/0fc25793-9d0a-459d-b645-46254bd89616.m3u8"]}

**Comment by BellezaEmporium** [comment]
Works for me now.
