### ISSUE TITLE
Broken: Many Japanese Primehome livestream channels went offline!

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#17712]
### Broken Link

https://github.com/iptv-org/iptv/blob/master/streams/jp_primehome.m3u

### What happened to the stream?

Not loading

### Notes (optional)

@BellezaEmporium @denilsonsa @Sphinxroot Hey, guys! I found the livestream links from [Japanese Primehome TV channels](https://github.com/iptv-org/iptv/blob/master/streams/jp_primehome.m3u) went offline due to the technical difficulties but how long it needs to be fixed!

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by tasnovafink3** [comment]
yvde

**Comment by BellezaEmporium** [comment]
That is out of our scope.

**Comment by denilsonsa** [comment]
You should stop directly mentioning people in the issue. You're just spamming them for no good reason.

**Comment by AVGCFan1995** [comment]
> You should stop directly mentioning people in the issue. You're just spamming them for no good reason.

Okay sorry about that!

**Comment by AVGCFan1995** [comment]
> That is out of our scope.

What does that mean?

**Comment by BellezaEmporium** [comment]
> > That is out of our scope.
> 
> What does that mean?

That we can't do much about those links, apart from replacing them (which would be difficult concerning the country we're talking of) or wait for them to come back.

**Comment by olstern01** [comment]
![スクリーンショット 2024-10-11 060845](https://github.com/user-attachments/assets/96507043-0ad6-461c-8ed4-fa804b63dc9c)

JP Primehome's streams are now tokenized.

Is there are way to solve this?

**Comment by Sphinxroot** [comment]
add &isp=7  at end of link

dont work
#EXTINF:-1 tvg-id="JOAYDTV.jp",ABC (544p)
http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=gx02

working
#EXTINF:-1 tvg-id="JOAYDTV.jp",ABC (544p)
http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=gx02&isp=7

**Comment by olstern01** [comment]
> add &isp=7 at end of link
> 
> dont work #EXTINF:-1 tvg-id="JOAYDTV.jp",ABC (544p) http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=gx02
> 
> working #EXTINF:-1 tvg-id="JOAYDTV.jp",ABC (544p) http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=gx02&isp=7

Confirmed working. Thank you very much!

**Comment by AVGCFan1995** [comment]
> ![スクリーンショット 2024-10-11 060845](https://private-user-images.githubusercontent.com/47495790/375570560-96507043-0ad6-461c-8ed4-fa804b63dc9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDk1NTUsIm5iZiI6MTcyODcwOTI1NSwicGF0aCI6Ii80NzQ5NTc5MC8zNzU1NzA1NjAtOTY1MDcwNDMtMGFkNi00NjFjLThlZDQtZmE4MDRiNjNkYzljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA1MDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZDlkMzhhZjhlMWZjMTg4NTc1NjIyZWFhZDAxNzIzZmExNGM4MDczZmVmODQ3MmU3MDE5NjM3YWMzMzMxZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RwAQIc59GY4Bwpceqki4BVXeOcjVxK_7gCVyGB7jpPU)
> 
> JP Primehome's streams are now tokenized, except channels with 1080p resolution like Toei Channel, and Takarazuka Sky Stage.
> 
> Is there are way to solve this?

Don't forget about Channel Ginga since it has a 1080p resolution and it works on VLC media player just like both aforementioned Japanese TV channels.

**Comment by AVGCFan1995** [comment]
> add &isp=7 at end of link

I fix those [Japanese Primehome livestream links](https://github.com/iptv-org/iptv/commit/5b6e12b1840f3aa6e456d8eedbdc61153ee0ba3c#diff-f7cadd491683687eb8fc4459d6bb702e3e1142d7006e096a75b1a265acb5cc39R23), [BellezaEmporium](https://github.com/BellezaEmporium)!

**Comment by BellezaEmporium** [comment]
> add &isp=7  at end of link
> 
> dont work
> #EXTINF:-1 tvg-id="JOAYDTV.jp",ABC (544p)
> http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=gx02
> 
> working
> #EXTINF:-1 tvg-id="JOAYDTV.jp",ABC (544p)
> http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=gx02&isp=7 

Well done.

**Comment by olstern01** [comment]
> > add &isp=7 at end of link
> 
> I fix those [Japanese Primehome livestream links](https://github.com/iptv-org/iptv/commit/5b6e12b1840f3aa6e456d8eedbdc61153ee0ba3c#diff-f7cadd491683687eb8fc4459d6bb702e3e1142d7006e096a75b1a265acb5cc39R23), [BellezaEmporium](https://github.com/BellezaEmporium)!

Your commit gave me this warning on my end.

![スクリーンショット 2024-10-12 154840](https://github.com/user-attachments/assets/1c7046b3-d8e5-4680-8459-4286d91da471)

**Comment by BellezaEmporium** [comment]
This is normal. Our master branch is protected of any "bad" commits/merges. You'll need 2 approvals from us in order to merge the pull request.

**Comment by olstern01** [comment]
> This is normal. Our master branch is protected of any "bad" commits/merges. You'll need 2 approvals from us in order to merge the pull request.

It should've appeared here, but I didn't see @AVGCFan1995 's PR.

![スクリーンショット 2024-10-12 163546](https://github.com/user-attachments/assets/4185c453-8e56-454f-bb91-2ec85cf1b16c)

**Comment by BellezaEmporium** [comment]
> > This is normal. Our master branch is protected of any "bad" commits/merges. You'll need 2 approvals from us in order to merge the pull request.
> 
> It should've appeared here, but I didn't see @AVGCFan1995 's PR.
> 
> ![スクリーンショット 2024-10-12 163546](https://github.com/user-attachments/assets/4185c453-8e56-454f-bb91-2ec85cf1b16c)
> 

That's because he hasn't submitted a pull request (yet)

**Comment by Alstruit** [comment]
PR: #17723

**Comment by AVGCFan1995** [comment]
> > > This is normal. Our master branch is protected of any "bad" commits/merges. You'll need 2 approvals from us in order to merge the pull request.
> > 
> > 
> > It should've appeared here, but I didn't see @AVGCFan1995 's PR.
> > ![スクリーンショット 2024-10-12 163546](https://private-user-images.githubusercontent.com/47495790/375947674-4185c453-8e56-454f-bb91-2ec85cf1b16c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjYxNjUsIm5iZiI6MTcyODcyNTg2NSwicGF0aCI6Ii80NzQ5NTc5MC8zNzU5NDc2NzQtNDE4NWM0NTMtOGU1Ni00NTRmLWJiOTEtMmVjODVjZjFiMTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA5Mzc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NTQwZTllM2IyODk5MWQwNDE0NjcyNDg5ODliZDgzZDk2ZDZjOWZlNzQzNDhlNTY4MTM1ZWI5ZDlmZTFiMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.23kpRw9Eivnse4KB3V6gVbWWrezMvhXPRSbQLJC8BBg)
> 
> That's because he hasn't submitted a pull request (yet)

Okay sorry about that!

**Comment by AVGCFan1995** [comment]
> > > add &isp=7 at end of link
> > 
> > 
> > I fix those [Japanese Primehome livestream links](https://github.com/iptv-org/iptv/commit/5b6e12b1840f3aa6e456d8eedbdc61153ee0ba3c#diff-f7cadd491683687eb8fc4459d6bb702e3e1142d7006e096a75b1a265acb5cc39R23), [BellezaEmporium](https://github.com/BellezaEmporium)!
> 
> @AVGCFan1995 Your commit gave me this warning on my end. You need to open a PR on the iptv master branch repo.
> 
> ![スクリーンショット 2024-10-12 154840](https://private-user-images.githubusercontent.com/47495790/375941845-1c7046b3-d8e5-4680-8459-4286d91da471.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjQ0NDUsIm5iZiI6MTcyODcyNDE0NSwicGF0aCI6Ii80NzQ5NTc5MC8zNzU5NDE4NDUtMWM3MDQ2YjMtZDhlNS00NjgwLTg0NTktNDI4NmQ5MWRhNDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA5MDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZGI5YjhlMTYzZmVmMTEzNTQ2YjVkNGY0NmY3ODQ1ZWEwMDNhMTE3NTdjMThhNTZhMGM1MzhhYjFiMDMxZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H2u706Ldn__pwd0ei7b7ZTmMbq961xLXvhWxQcX-i0g)

But I'm sorry but I was unable to post a comment on [this link](https://github.com/iptv-org/iptv/pull/17723) as I believe Alstruit blocked me or something?

**Comment by BellezaEmporium** [comment]
> > > > add &isp=7 at end of link
> > > 
> > > 
> > > I fix those [Japanese Primehome livestream links](https://github.com/iptv-org/iptv/commit/5b6e12b1840f3aa6e456d8eedbdc61153ee0ba3c#diff-f7cadd491683687eb8fc4459d6bb702e3e1142d7006e096a75b1a265acb5cc39R23), [BellezaEmporium](https://github.com/BellezaEmporium)!
> > 
> > @AVGCFan1995 Your commit gave me this warning on my end. You need to open a PR on the iptv master branch repo.
> > 
> > ![スクリーンショット 2024-10-12 154840](https://private-user-images.githubusercontent.com/47495790/375941845-1c7046b3-d8e5-4680-8459-4286d91da471.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjQ0NDUsIm5iZiI6MTcyODcyNDE0NSwicGF0aCI6Ii80NzQ5NTc5MC8zNzU5NDE4NDUtMWM3MDQ2YjMtZDhlNS00NjgwLTg0NTktNDI4NmQ5MWRhNDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA5MDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZGI5YjhlMTYzZmVmMTEzNTQ2YjVkNGY0NmY3ODQ1ZWEwMDNhMTE3NTdjMThhNTZhMGM1MzhhYjFiMDMxZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H2u706Ldn__pwd0ei7b7ZTmMbq961xLXvhWxQcX-i0g)
> 
> But I'm sorry but I was unable to post a comment on [this link](https://github.com/iptv-org/iptv/pull/17723) as I believe Alstruit blocked me or something?

If you were blocked, you wouldn't be able to comment on any repos in this organisation at all.

**Comment by AVGCFan1995** [comment]
> > > > > add &isp=7 at end of link
> > > > 
> > > > 
> > > > I fix those [Japanese Primehome livestream links](https://github.com/iptv-org/iptv/commit/5b6e12b1840f3aa6e456d8eedbdc61153ee0ba3c#diff-f7cadd491683687eb8fc4459d6bb702e3e1142d7006e096a75b1a265acb5cc39R23), [BellezaEmporium](https://github.com/BellezaEmporium)!
> > > 
> > > 
> > > @AVGCFan1995 Your commit gave me this warning on my end. You need to open a PR on the iptv master branch repo.
> > > ![スクリーンショット 2024-10-12 154840](https://private-user-images.githubusercontent.com/47495790/375941845-1c7046b3-d8e5-4680-8459-4286d91da471.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjQ0NDUsIm5iZiI6MTcyODcyNDE0NSwicGF0aCI6Ii80NzQ5NTc5MC8zNzU5NDE4NDUtMWM3MDQ2YjMtZDhlNS00NjgwLTg0NTktNDI4NmQ5MWRhNDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA5MDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZGI5YjhlMTYzZmVmMTEzNTQ2YjVkNGY0NmY3ODQ1ZWEwMDNhMTE3NTdjMThhNTZhMGM1MzhhYjFiMDMxZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H2u706Ldn__pwd0ei7b7ZTmMbq961xLXvhWxQcX-i0g)
> > 
> > 
> > But I'm sorry but I was unable to post a comment on [this link](https://github.com/iptv-org/iptv/pull/17723) as I believe Alstruit blocked me or something?
> 
> If you were blocked, you wouldn't be able to comment on any repos in this organisation at all.

Yes, I know but there's the text that says, "You can't perform this action at this time." but does that mean Alstruit blocked me due to the amount of tagging users too many times in a row?

**Comment by BellezaEmporium** [comment]
> > > > > > add &isp=7 at end of link
> > > > > 
> > > > > 
> > > > > I fix those [Japanese Primehome livestream links](https://github.com/iptv-org/iptv/commit/5b6e12b1840f3aa6e456d8eedbdc61153ee0ba3c#diff-f7cadd491683687eb8fc4459d6bb702e3e1142d7006e096a75b1a265acb5cc39R23), [BellezaEmporium](https://github.com/BellezaEmporium)!
> > > > 
> > > > 
> > > > @AVGCFan1995 Your commit gave me this warning on my end. You need to open a PR on the iptv master branch repo.
> > > > ![スクリーンショット 2024-10-12 154840](https://private-user-images.githubusercontent.com/47495790/375941845-1c7046b3-d8e5-4680-8459-4286d91da471.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjQ0NDUsIm5iZiI6MTcyODcyNDE0NSwicGF0aCI6Ii80NzQ5NTc5MC8zNzU5NDE4NDUtMWM3MDQ2YjMtZDhlNS00NjgwLTg0NTktNDI4NmQ5MWRhNDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA5MDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZGI5YjhlMTYzZmVmMTEzNTQ2YjVkNGY0NmY3ODQ1ZWEwMDNhMTE3NTdjMThhNTZhMGM1MzhhYjFiMDMxZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H2u706Ldn__pwd0ei7b7ZTmMbq961xLXvhWxQcX-i0g)
> > > 
> > > 
> > > But I'm sorry but I was unable to post a comment on [this link](https://github.com/iptv-org/iptv/pull/17723) as I believe Alstruit blocked me or something?
> > 
> > If you were blocked, you wouldn't be able to comment on any repos in this organisation at all.
> 
> Yes, I know but there's the text that says, "You can't perform this action at this time." but does that mean Alstruit blocked me due to the amount of tagging users too many times in a row?

It's also possible that someone in the organisation has put restrictions in who can answer PRs. We have been victim of fake accounts posting random "free tv, watch here" stuff recently.

**Comment by Chaewonblight** [comment]
Ik this is completed and stuff but how can I access only MTV Japan? I came to watch only this channel in the Primehome list, missed so many countdowns last Thursday. How can I access this again? Please tell me here or dm pls

**Comment by Chaewonblight** [comment]
Down again

**Comment by BellezaEmporium** [comment]
![Image](https://github.com/user-attachments/assets/69b3e31d-9f43-486d-82a5-a8955b831610)

isp=8

**Comment by Chaewonblight** [comment]
Tried playing in the ISPs and some die in meantime

**Comment by Chaewonblight** [comment]
Are the tokenized links still working?
