### ISSUE TITLE
Broken: https://rakuten-topfree-1-eu.rakuten.wurl.tv/playlist.m3u8

### ISSUE THREAD

**Issue by TKList** [iptv-org/iptv#17719]
### Broken Link

https://rakuten-topfree-1-eu.rakuten.wurl.tv/playlist.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
https://0145451975a64b35866170fd2e8fa486.mediatailor.eu-west-1.amazonaws.com/v1/master/0547f18649bd788bec7b67b746e47670f558b6b2/production-LiveChannel-5987/master.m3u8

**Comment by BellezaEmporium** [comment]
Stream is protected (AES-128 key needed on load, provided by said link). They're starting to protect all of the streams.

**Comment by gcqmkm02** [comment]
最近日本テレビ全部が見えないです。理由はなんですか？
