### ISSUE TITLE
Add: Nippon TV

### ISSUE THREAD

**Issue by Alstruit** [iptv-org/iptv#17717]
### Channel ID (required)

JOAXDTV.jp

### Channel Name

Nippon TV

### Stream URL (required)

https://vnpt.nekocdn.xyz/427b3914-a2b4-401b-b5ed-706158d73908.m3u8

### Quality

720p

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Not working.

**Comment by telanus** [comment]
> Not working.

Works for me:
![Screenshot_20241010_235127](https://github.com/user-attachments/assets/d5d9a41b-30fb-4dec-a98c-9d19f3d7557a)

**Comment by Sphinxroot** [comment]
{"code":404,"message":"File not found","details":["/427b3914-a2b4-401b-b5ed-706158d73908.m3u8"]}

**Comment by BellezaEmporium** [comment]
Works for me now.
