### ISSUE TITLE
Add: Laotian TV channels

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#17711]
### Channel ID (required)

LNTV1.la

### Channel Name

LNTV 1

### Stream URL (required)

https://laotv.la/2VDd47sroTATI1VX8

### Quality

None

### Label

None

### Notes

@BellezaEmporium @denilsonsa Hey, guys! I found the livestream links for Laotian TV channels from Lao TV app since these livestream channels are long dead about many months ago. But I'm not sure it works on VLC media player or any streaming software but still. But how to download these livestream links from the Lao TV app?

BTW, here's the links.

[LNTV 1](https://laotv.page.link/2VDd47sroTATI1VX8)

[Lao PSTV](https://laotv.page.link/uFcnXyzCPWTMmkcn6)

[VTE 9](https://laotv.page.link/9qpS56SLVZqqxYDz5)

[MV Lao](https://laotv.page.link/UtyQtQovB8VBMFmM7)

[Lao ESTV](https://laotv.page.link/rxGxgisxfbnvWENE7)

[LNTV 3](https://laotv.page.link/vxdvVXKyjuNROWHV9)

[Dramas TV](https://laotv.page.link/c4zeYv8UjZktKHho7)

[Genz TV](https://laotv.page.link/ugjP5dfWuvUgx9pk8)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by nazrulink3** [comment]
VXSD

**Comment by tasnovafink3** [comment]
Add TV channels

➤►
### 📺📱 [🔴 ➤►𝗪𝗔𝗧𝗖𝗛👉   2024 Full Movi𝚎  Available Onlin𝚎 ▶️](https://cutt.ly/WeY2ABI3)

### 📺📱 [🔴 ➤►𝗪𝗔𝗧𝗖𝗛👉   2024 Full Movi𝚎  Available Onlin𝚎▶️](https://cutt.ly/WeY2ABI3)

### 📺📱 [🔴 ➤►𝗪𝗔𝗧𝗖𝗛👉   2024 Full Movi𝚎  Available Onlin𝚎▶️](https://cutt.ly/WeY2ABI3)

➤►

▶️

➤►


➤►

▶️[![MOVIE](https://cdn.wrytin.com/images/wrytup/r/1024/best-websites-to-watch-free-movies-online-top-10-jxr6uqtt.jpeg)](https://cutt.ly/WeY2ABI3)

➤►

➤►

▶️

➤►

### 📺📱 [🔴 ➤►𝗪𝗔𝗧𝗖𝗛👉     2024 Full Movi𝚎  Available Onlin𝚎 ▶️](https://cutt.ly/WeY2ABI3)

### 📺📱 [🔴 ➤►𝗪𝗔𝗧𝗖𝗛👉     2024 Full Movi𝚎  Available Onlin𝚎▶️](https://cutt.ly/WeY2ABI3)

### 📺📱 [🔴 ➤►𝗪𝗔𝗧𝗖𝗛👉    2024 Full Movi𝚎  Available Onlin𝚎▶️](https://cutt.ly/WeY2ABI3)

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

### 📺📱 [🔴 ➤►𝗪𝗔𝗧𝗖𝗛👉     2024 Full Movi𝚎  Available Onlin𝚎 ▶️](https://cutt.ly/WeY2ABI3)

### 📺📱 [🔴 ➤►𝗪𝗔𝗧𝗖𝗛👉     2024 Full Movi𝚎  Available Onlin𝚎▶️](https://cutt.ly/WeY2ABI3)

### 📺📱 [🔴 ➤►𝗪𝗔𝗧𝗖𝗛👉    2024 Full Movi𝚎  Available Onlin𝚎▶️](https://cutt.ly/WeY2ABI3)

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

### 📺📱 [🔴 ➤►𝗪𝗔𝗧𝗖𝗛👉     2024 Full Movi𝚎  Available Onlin𝚎 ▶️](https://cutt.ly/WeY2ABI3)

### 📺📱 [🔴 ➤►𝗪𝗔𝗧𝗖𝗛👉     2024 Full Movi𝚎  Available Onlin𝚎▶️](https://cutt.ly/WeY2ABI3)

### 📺📱 [🔴 ➤►𝗪𝗔𝗧𝗖𝗛👉    2024 Full Movi𝚎  Available Onlin𝚎▶️](https://cutt.ly/WeY2ABI3)

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

### 📺📱 [🔴 ➤►𝗪𝗔𝗧𝗖𝗛👉     2024 Full Movi𝚎  Available Onlin𝚎 ▶️](https://cutt.ly/WeY2ABI3)

### 📺📱 [🔴 ➤►𝗪𝗔𝗧𝗖𝗛👉     2024 Full Movi𝚎  Available Onlin𝚎▶️](https://cutt.ly/WeY2ABI3)

### 📺📱 [🔴 ➤►𝗪𝗔𝗧𝗖𝗛👉    2024 Full Movi𝚎  Available Onlin𝚎▶️](https://cutt.ly/WeY2ABI3)

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

### 📺📱 [🔴 ➤►    2024 Full Movi𝚎  Available Onlin𝚎]

### 📺📱 [🔴 ➤►    2024 Full Movi𝚎  Available Onlin𝚎]

### 📺📱 [🔴 ➤►    2024 Full Movi𝚎  Available Onlin𝚎]

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

### 📺📱 [🔴 ➤►    2024 Full Movi𝚎  Available Onlin𝚎]

### 📺📱 [🔴 ➤►    2024 Full Movi𝚎  Available Onlin𝚎]

### 📺📱 [🔴 ➤►    2024 Full Movi𝚎  Available Onlin𝚎]

▶️

➤►

➤►

▶️

➤►

▶️

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

▶️

➤►

➤►

### 📺📱 [🔴 ➤►𝗪𝗔𝗧𝗖𝗛👉   2024 Full Movi𝚎  Available Onlin𝚎 ▶️](https://cutt.ly/WeY2ABI3)

### 📺📱 [🔴 ➤►𝗪𝗔𝗧𝗖𝗛👉   2024 Full Movi𝚎  Available Onlin𝚎▶️](https://cutt.ly/WeY2ABI3)

### 📺📱 [🔴 ➤►𝗪𝗔𝗧𝗖𝗛👉   2024 Full Movi𝚎  Available Onlin𝚎▶️](https://cutt.ly/WeY2ABI3)

➤►

➤►

▶️

➤►

➤►

[![MOVIE](https://cdn.wrytin.com/images/wrytup/r/1024/best-websites-to-watch-free-movies-online-top-10-jxr6uqtt.jpeg)](https://cutt.ly/WeY2ABI3)

▶️


ytuty

**Comment by AVGCFan1995** [comment]
Hey, @Sphinxroot! How to download the livestream links from Lao TV but how it's going to work?!

**Comment by Sphinxroot** [comment]
use web dev tool  / network tab

i see 
.mpd expirable + token

**Comment by AVGCFan1995** [comment]
> use web dev tool / network tab
> 
> i see .mpd expirable + token

What does that mean?

**Comment by Sphinxroot** [comment]
it depend on the browser you use ... firefox  as i use   tools tab - browser tool - web developer tool   -- network tab  you will see all requested link

i see in https://laotv.la/live.html?id=37464E56FA2F478BBDF2D0023E3D1A69

https://ctrl.laotv.la/tokenlive/LaoESTV/manifest.mpd?va=1728688488&token=XXXXXXXXXX

they use to be in m3u8 https://github.com/search?q=laotv.la&type=code

try them but im sure they are dead or geo  none seem to work

**Comment by AVGCFan1995** [comment]
> it depend on the browser you use ... firefox as i use tools tab - browser tool - web developer tool -- network tab (crtl+Shifr+i )you will see all requested link
> 
> i see in https://laotv.la/live.html?id=37464E56FA2F478BBDF2D0023E3D1A69
> 
> https://ctrl.laotv.la/tokenlive/LaoESTV/manifest.mpd?va=1728688488&token=XXXXXXXXXX
> 
> they use to be in m3u8 https://github.com/search?q=laotv.la&type=code
> 
> try them but im sure they are dead or geo none seem to work

Did you finally download the livestream links from Laotian TV channels or maybe not?

**Comment by sunminghua1975** [comment]
Does Anybody have a stream for TVLAO channel as well as laotian regional channel?

**Comment by sunyuanzhe** [comment]
I Think This will help you to record a MPD Stream(in Chinese):https://github.com/geniuszxy/N_m3u8DL-RE

**Comment by AVGCFan1995** [comment]
> I Think This will help you to record a MPD Stream(in Chinese):https://github.com/geniuszxy/N_m3u8DL-RE

Thanks for showing the link but how it's going to work now.

**Comment by sunyuanzhe** [comment]
Genz TV:https://laotv.nkcentral.group/live/laotv2/index.m3u8

**Comment by AVGCFan1995** [comment]
> Genz TV:https://laotv.nkcentral.group/live/laotv2/index.m3u8

Yeah, but what about Lao National TV1, Lao National TV3, Lao Star, MV Lao TV, Lao Public Security TV, and Lao ESTV since these Laotian livestreams' channels are very hard-to-find nowadays.

**Comment by sunyuanzhe** [comment]
streams under the host https://livesd.us.malimarcdn.com are all having changing token,is anybody to wrote a php script for getting tokens begins with ?verify=
