### ISSUE TITLE
Broken: Star Channel 3

### ISSUE THREAD

**Issue by Alstruit** [iptv-org/iptv#17722]
### Broken Link

http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=bs28&isp=7

### What happened to the stream?

Other

### Notes (optional)

Channel closed on May 31 2024

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by jomarhost** [comment]
Hello maam and sir may i request also to add
STAR TV PHILIPPINES. (COUNTRY PHILIPPINES ) on your list
https://www.livereacting.com/tools/hls-player-embed?url=https%3A%2F%2F1a-1791.com%2Flive%2Fd0t27del%2Fslot-133%2Fh7ws-57lv_1080p%2Fchunklist_DVR.m3u8

Thank you very much hope you grant this request
