### ISSUE TITLE
Broken: Kids Station

### ISSUE THREAD

**Issue by juney2008** [iptv-org/iptv#17724]
### Broken Link

http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=cs07

### What happened to the stream?

Not loading

### Notes (optional)

I believe there are other Japanese TV channels that do not load too like TV Tokyo for example.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by telanus** [comment]
It should be fixed: https://github.com/iptv-org/iptv/commit/e3bcf437c0894701afacf516f6d84126921da3e1

**Comment by juney2008** [comment]
Oh alright, I've tried out the prime room file and it works now!
