### ISSUE TITLE
Broken: JP stream link various channels are down

### ISSUE THREAD

**Issue by hex645** [iptv-org/iptv#17725]
### Broken Link

https://iptv-org.github.io/iptv/countries/jp.m3u

### What happened to the stream?

Not loading

### Notes (optional)

I use this link for watching japanese channels but various channels arent working and from what I saw the primehome version got updated but i dont know the link for it as i normally type it out on VLC for both pc and android tv and ive tried putting languages/countries before the jp primehome bit.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Specify exact channels or source please

**Comment by hex645** [comment]
How do i do this? Sorry im new to all this

**Comment by hex645** [comment]
> Specify exact channels or source please

https://github.com/iptv-org/iptv/blob/master/streams/jp.m3u

This the source i think
