### ISSUE TITLE
Broken: Fuji TV (540p)

### ISSUE THREAD

**Issue by telanus** [iptv-org/iptv#17729]
### Broken Link

https://fujitv4.mov3.co/hls/fujitv.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Looks like the stream stopped/offline:

![image](https://github.com/user-attachments/assets/75cf4e4b-456e-4d31-911e-49f6382140bc)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
![image](https://github.com/user-attachments/assets/5c0bfb2b-1b06-4e37-9774-af08fbf42153)
