### ISSUE TITLE
Add: Virgin Media One

### ISSUE THREAD

**Issue by CasperMcFadden95** [iptv-org/iptv#17735]
### Channel ID (required)

VirginMediaOne.ie

### Channel Name

Virgin Media One

### Stream URL (required)

https://live-virginmedia.simplestreamcdn.com/s3/rewrite/virgin_one/index.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by CasperMcFadden95** [comment]
Already exists

**Comment by Goldiefresh** [comment]
You can change the number in the url to two three and four to access the other virgin channels. 

https://live-virginmedia.simplestreamcdn.com/s3/rewrite/virgin_two/index.m3u8
