### ISSUE TITLE
Add: Channel 7

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#17744]
### Channel ID (required)

Channel7.mm

### Stream URL (required)

https://pplive.comquas.com:5443/LiveApp/streams/CLcBFN71NkF61709008601656.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://pplive.comquas.com:5443/LiveApp/streams/CLcBFN71NkF61709008601656.m3u8 (offline)

<img width="631" alt="image" src="https://github.com/user-attachments/assets/1eb7e572-1a19-4b59-8ba3-f8f30ca25fbb">

**Comment by sunyuanzhe** [comment]
This stream works for a while but it's currently unavailable

**Comment by sunyuanzhe** [comment]
The stream now works
