### ISSUE TITLE
Add: A2Z Channel Source

### ISSUE THREAD

**Issue by NIELKHRISTIAN** [iptv-org/iptv#17743]
### Channel ID (required)

A2Z.ph

### Channel Name

A2Z

### Stream URL (required)

https://wag.ika.lat/stream/944313137​

### Quality

None

### Label

Not 24/7

### Notes

https://phcorner.net/threads/ph-tv-source-or-something-eh.2113867/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
[https://wag.ika.lat/stream/944313137​](https://wag.ika.lat/stream/944313137%E2%80%8B)
<img width="620" alt="image" src="https://github.com/user-attachments/assets/5cc83e8b-d0d0-4a8a-b174-35197adb59c1">
