### ISSUE TITLE
Broken: Almost all japanese channels streams are broken

### ISSUE THREAD

**Issue by nao120** [iptv-org/iptv#17742]
### Broken Link

https://iptv-org.github.io/iptv/countries/jp.m3u

### What happened to the stream?

Not loading

### Notes (optional)

So almost all national and BS channels are broken and dont load at all, i dont know how this happened but it has been going for a week now, hopefully a fix soon 
the channels that no longer work are:
ABC 
Animax 
AT-X
all NHK channels 
Disney Junior 
Disney Channel
Fuji TV 
Fuji TV NEXT
SUN TV 
Tokyo MX1
Tokyo MX2
TV Asahi
TV Osaka 
TV Tokyo
WOWOW Cinema 
WOWOW Live
WOWOW Prime
Family Gekijo 
Fishing Vision

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by olstern01** [comment]
JP Primehome's channels has been fixed three days ago. Try using the new playlist. As for AT-X, neetball's streams has stopped working for a while, so it has been removed from the playlist.

**Comment by nao120** [comment]
seems it started breaking again

**Comment by ucf0709** [comment]
seems it started breaking again

**Comment by alwaysahiro** [comment]
Not working at all except for a news and shopping channels. Can anyone assist with fixing?
