### ISSUE TITLE
Broken: Nippon TV (720p)

### ISSUE THREAD

**Issue by olstern01** [iptv-org/iptv#17746]
### Broken Link

https://vnpt.nekocdn.xyz/427b3914-a2b4-401b-b5ed-706158d73908.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

JP Primehome's TV Asahi and Nippon TV streams didn't appear in the jp.m3u playlist, and nekocdn's streams are unreliable, so if JP Primehome's streams appear again in the playlist, that would be great.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Stevyb** [comment]
In August 2024 jp.m3u had 112 channels now only 61 channels !
Where can I make a request for specific extra channels ?

**Comment by Stevyb** [comment]
Is it possible to add the channel NHK G Osaka ?
