### ISSUE TITLE
Broken: Tokushoutsu

### ISSUE THREAD

**Issue by freelancerage** [iptv-org/iptv#17756]
### Broken Link

https://amg00163-shoutfactory-tokushoutsu-dmr-c1irg.amagi.tv/playlist/amg00163-shoutfactory-tokushoutsu-dmr/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Replace with another working stream:

http://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/stitch/hls/channel/5c3f8f12a93c2d61b9990a4e/master.m3u8?appName=web&appVersion=unknown&clientTime=0&deviceDNT=0&deviceId=6c2c73e3-30d3-11ef-9cf5-e9ddff8ff496&deviceMake=Chrome&deviceModel=web&deviceType=web&deviceVersion=unknown&includeExtendedEvents=false&serverSideAds=false&sid=8a88f013-2601-41bd-9070-75701edcf852

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/0f0b221787bde0eba30ca6c773a25822257ec976/streams/us_pluto.m3u#L752-L753

**Comment by spotanjo3** [comment]
dead
