### ISSUE TITLE
Add: viju+ Premiere

### ISSUE THREAD

**Issue by Cringe-Arab** [iptv-org/iptv#17753]
### Channel ID (required)

vijuPlusPremiere.ru

### Channel Name

viju+ Premiere

### Stream URL (required)

http://77.235.1.17/vip_premier/index.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by voxelish** [comment]
"not available"????????????????????
