### ISSUE TITLE
Broken: Buzzr (1080p)

### ISSUE THREAD

**Issue by freelancerage** [iptv-org/iptv#17755]
### Broken Link

https://buzzrota-web.amagi.tv/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Replace with another working stream:

https://buzzr-samsungus.amagi.tv/playlist.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/0f0b221787bde0eba30ca6c773a25822257ec976/streams/us_samsung.m3u#L14-L15
