### ISSUE TITLE
Add: Xinjiang TV3(Burqin TV2 Relay)

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#17761]
### Channel ID (required)

XinjiangTV3.cn

### Stream URL (required)

https://st-video.xjmty.com/fs/livedit/e55abfa37af26e19/8ce9971c2177b3dd.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://st-video.xjmty.com/fs/livedit/e55abfa37af26e19/8ce9971c2177b3dd.m3u8

<img width="1410" alt="image" src="https://github.com/user-attachments/assets/0384fb6d-7dee-42fc-b583-2301df26786c">
