### ISSUE TITLE
Broken: NCI

### ISSUE THREAD

**Issue by Sylquaza** [iptv-org/iptv#17766]
### Broken Link

https://pixa.cdn.easybroadcast.fr/nci/nci.isml/Playlist.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-id="",NCI (1080p)
#EXTVLCOPT:http-referrer=https://www.nci.ci/direct
https://cdnapisec.kaltura.com/p/5571652/sp/5571652/playManifest/entryId/1_no7nfr0h/deliveryProfileId/672/protocol/https/format/applehttp/a.m3u8

#EXTINF:-1 tvg-id="",NCI (1080p)
#EXTVLCOPT:http-referrer=https://www.nci.ci/direct
https://pixa.cdn.easybroadcast.fr/nci/nci.isml/nci-audio_fre=128000-video=2500000.m3u8

#EXTINF:-1 tvg-id="",NCI (360p)
#EXTVLCOPT:http-referrer=https://www.nci.ci/direct
https://pixa.cdn.easybroadcast.fr/nci/nci.isml/nci-audio_fre=128000-video=1000000.m3u8

#EXTINF:-1 tvg-id="",NCI (180p)
#EXTVLCOPT:http-referrer=https://www.nci.ci/direct
https://pixa.cdn.easybroadcast.fr/nci/nci.isml/nci-audio_fre=128000-video=350000.m3u8


Kodi
#EXTINF:-1 tvg-id="",NCI (1080p)
https://cdnapisec.kaltura.com/p/5571652/sp/5571652/playManifest/entryId/1_no7nfr0h/deliveryProfileId/672/protocol/https/format/applehttp/a.m3u8|Referer=https://www.nci.ci/direct

adaptative have token   dont want to work with referer 
https://pixa.cdn.easybroadcast.fr/nci/nci.isml/.m3u8?token=

#EXTINF:-1 tvg-id="",NCI (1080p)
https://pixa.cdn.easybroadcast.fr/nci/nci.isml/nci-audio_fre=128000-video=2500000.m3u8|Referer=https://www.nci.ci/direct

#EXTINF:-1 tvg-id="",NCI (360p)
https://pixa.cdn.easybroadcast.fr/nci/nci.isml/nci-audio_fre=128000-video=1000000.m3u8|Referer=https://www.nci.ci/direct

#EXTINF:-1 tvg-id="",NCI (180p)
https://pixa.cdn.easybroadcast.fr/nci/nci.isml/nci-audio_fre=128000-video=350000.m3u8|Referer=https://www.nci.ci/direct

**Comment by freearhey** [comment]
Fixed in #17824
