### ISSUE TITLE
Add: Yunnan TV Metropolitan Channel

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#17804]
### Channel ID (required)

YunnanTVMetropolitanChannel.cn

### Stream URL (required)

http://enlen.vip:4022/udp/239.200.200.12:8844

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
http://enlen.vip:4022/udp/239.200.200.12:8844 (offline)
