### ISSUE TITLE
Add: Yunnan TV Entertainment Channel

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#17800]
### Channel ID (required)

YunnanTVEntertainmentChannel.cn

### Stream URL (required)

http://enlen.vip:4022/udp/239.200.200.13:8848

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
http://enlen.vip:4022/udp/239.200.200.13:8848 (offline)

<img width="346" alt="image" src="https://github.com/user-attachments/assets/c7a0d64f-4b03-442a-859d-e1479564e5cc">
