### ISSUE TITLE
Broken: Music Japan (more info)

### ISSUE THREAD

**Issue by TheRealMiRRoRMaN** [iptv-org/iptv#17818]
### Broken Link

http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=cs06&isp=7

### What happened to the stream?

Not loading

### Notes (optional)

I saw something about "can't reproduce" i use OTT Navigator with Bluestacks, its always worked fine but now it's saying:

"403 access denied (incorrect key?) contact your provider"

I'm hoping you guys can fix it, maybe hit me up on IM here? Please help. 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by jasonnguyen2606** [comment]
It’s already done. There’s nothing we can do. So please stop spamming.

**Comment by TheRealMiRRoRMaN** [comment]
its not working here, any advice? i didn't mean to spam, i'm just looking for a solution.

**Comment by TheRealMiRRoRMaN** [comment]
> PR was merged need to wait about 24 hours.

what does that mean? I tried putting in the latest playlist and then music japan has just disappeared?

**Comment by R4IN2007** [comment]
Shut the f**k up about this already
