### ISSUE TITLE
Broken: Music Japan

### ISSUE THREAD

**Issue by TheRealMiRRoRMaN** [iptv-org/iptv#17812]
### Broken Link

http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=cs06&isp=7

### What happened to the stream?

Not loading

### Notes (optional)

I hope you guys can fix this, because I need my fix. 

Thank you in advance!

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
https://github.com/iptv-org/iptv/pull/17796/files
