### ISSUE TITLE
Broken: most Japan channels

### ISSUE THREAD

**Issue by ChiFungLam** [iptv-org/iptv#17810]
### Broken Link

https://iptv-org.github.io/iptv/countries/jp.m3u

### What happened to the stream?

Not loading

### Notes (optional)

Nost channel return 404 and tested with Japan VPN, give same result.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by jasonnguyen2606** [comment]
Please refer to this issue from the link below since this is duplicated from the one we have before.
https://github.com/iptv-org/iptv/issues/17762
