### ISSUE TITLE
Broken: Most japanese channel

### ISSUE THREAD

**Issue by okonomitarou** [iptv-org/iptv#17823]
### Broken Link

https://github.com/iptv-org/iptv/blob/master/streams/jp_primehome.m3u

### What happened to the stream?

Not loading

### Notes (optional)

Even if you access the corrected address, 
it will not play.

Best regards,

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by dm-25** [comment]
先週中頃から殆どの日本のチャンネルが見られ無くなってます。たまに見れても直ぐに止まり見れなくなります　何が起きたのか分かりません
