### ISSUE TITLE
Broken: A2Z

### ISSUE THREAD

**Issue by freelancerage** [iptv-org/iptv#17839]
### Broken Link

https://tv-noyzkie.serv00.net/streams/A2Z.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Error 404
Object Not Found
Dead link

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
https://wag.ika.lat/stream/944313137​
