### ISSUE TITLE
Add: AXN Southeast Asia

### ISSUE THREAD

**Issue by freelancerage** [iptv-org/iptv#17837]
### Channel ID (required)

AXN.ph

### Channel Name

AXN Southeast Asia

### Stream URL (required)

https://wag.ika.lat/stream/2084767267

### Quality

1080p

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by xykt-fix** [comment]
XTREAM CODE!!!!
