### ISSUE TITLE
Add: Rock Action

### ISSUE THREAD

**Issue by freelancerage** [iptv-org/iptv#17836]
### Channel ID (required)

ROCKAction.sg

### Channel Name

Rock Action Southeast Asia

### Stream URL (required)

https://wag.ika.lat/stream/507371538

### Quality

1080p

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by km147** [comment]
looks like a pirate link to me
