### ISSUE TITLE
Seeking for TV Tokyo

### ISSUE THREAD

**Issue by HernandoR** [iptv-org/iptv#1783]
**Country of the channel: Japan

**Channel Name:  TV Tokyo

**Channel Language: Japanese

**Additional Information (optional):**

**Comment by SileC** [comment]
You can add it
#EXTINF:-1 tvg-logo="https://i.imgur.com/vgEnHX6.png" group-title="Japan",TV Tokyo
http://203.162.235.41:16908

**Comment by themak1985** [comment]
Added.
