### ISSUE TITLE
Add: GTV HD

### ISSUE THREAD

**Issue by freelancerage** [iptv-org/iptv#17838]
### Channel ID (required)

GTV.ph

### Channel Name

GTV HD

### Stream URL (required)

https://wag.ika.lat/stream/872206966

### Quality

1080p

### Label

Not 24/7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by hossainhridoy** [comment]
No working 😔
