### ISSUE TITLE
Edit: AXN Central US

### ISSUE THREAD

**Issue by freelancerage** [iptv-org/iptv#17845]
### Stream URL (required)

https://streamer1.nexgen.bz/AXN/index.m3u8 

### Channel ID

AXNCentralAmerica.us

### Channel Name

AXN Central US

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Isn't stream already in Playlist?
https://github.com/iptv-org/iptv/blob/977d9784f5ce06a18e6ee0060e0eb8c2495fdbd3/streams/bz_nexgen.m3u#L2-L3
