### ISSUE TITLE
Broken: TamazightTV in ma.m3u

### ISSUE THREAD

**Issue by Ya563** [iptv-org/iptv#17847]
### Broken Link

https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/tamazight_tv8_snrt/hls_snrt/index.m3u8

### What happened to the stream?

Other

### Notes (optional)

The TamazightTV m3u link in the Moroccan m3u list (ma.m3u) is broken; I get an error; both when trying to access the link from my smart TV and from my internet browser.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
all stream from https://snrtlive.ma/  now have token

https://cdn-globecast.akamaized.net/live/eds/tamazight_tv8_snrt/hls_snrt_token/index.m3u8?hdnea=st=xxxxxxxxxxxxxxxxxxx

**Comment by Ya563** [comment]
I do not understand, I'm not technical, but both the link in my original post and both links in your comment do not work for me: they all say 'Access denied'. I do not understand why this issue has been closed?
