### ISSUE TITLE
Broken: AXN Indonesia

### ISSUE THREAD

**Issue by freelancerage** [iptv-org/iptv#17844]
### Broken Link

http://vod.linknetott.swiftcontent.com/Content/HLS/Live/Channel(ch332)/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

403 Forbidden
Dead link

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by tpadev** [comment]
Is this channel allow in the playlist ? As far as I know the AXN is one of the channel in premium tv service ?
