### ISSUE TITLE
Add: Star Movies HD

### ISSUE THREAD

**Issue by freelancerage** [iptv-org/iptv#17842]
### Channel ID (required)

StarMoviesHD.in

### Channel Name

Star Movies HD

### Stream URL (required)

http://republikadobiolo.ottb.xyz/423927909736/655788392083/1116488

### Quality

None

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Xtream url, stream not allowed
