### ISSUE TITLE
Broken: SMNI News Channel

### ISSUE THREAD

**Issue by freelancerage** [iptv-org/iptv#17850]
### Broken Link

https://ythls.armelin.one/channel/UCNaQMcnWvx95j7OG3217IMg.m3u8 

### What happened to the stream?

Not loading

### Notes (optional)

Dead link

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
dont seem to have a live stream https://rumble.com/user/smninews/livestreams
