### ISSUE TITLE
Broken: MSNBC

### ISSUE THREAD

**Issue by Split181** [iptv-org/iptv#17865]
### Broken Link

http://fl2.moveonjoy.com/MSNBC/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Main playlist:  https://iptv-org.github.io/iptv/index.m3u

Broken link:    http://fl2.moveonjoy.com/MSNBC/index.m3u8

This link has been broken for over a week.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by simminecrafter** [comment]
I found a working link for MSNBC HERE:
http://67.220.74.90:25461/18736836/73683618/1710

**Comment by Split181** [comment]
Hi simminecrafter

I had no luck with the link that you provided.
Cheers
