### ISSUE TITLE
Broken: A+ Ivory

### ISSUE THREAD

**Issue by RhymeInspectah** [iptv-org/iptv#17866]
### Broken Link

http://69.64.57.208/atv/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Hi,
RTI 1 & 2 loads correctly with VPN for re-geo-location,
but A+Ivoire (Ivory Coast Channel) seems broken...
Someone has a clue for a new stream link ?
Regards

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sylquaza** [comment]
Je confirme que ça ne fonctionne pas

**Comment by BellezaEmporium** [comment]
Connection refused, even with a VPN in Ghana.

**Comment by BellezaEmporium** [comment]
![image](https://github.com/user-attachments/assets/c5dde6b5-5c81-4f26-83c6-1f9a9b9ac821)
well, it went back on its own.

**Comment by RhymeInspectah** [comment]
I confirm today its works with VPN (on Nigerian exit).
I close.
Thanks to all

**Comment by rochelryu** [comment]
Not Work Actually
