### ISSUE TITLE
Add: Local KREM-TV (CBS SPOKANE) Station

### ISSUE THREAD

**Issue by simminecrafter** [iptv-org/iptv#17871]
### Channel ID (required)

KREMDT1.us

### Channel Name

KREM-DT1

### Stream URL (required)

https://cbsplaylistserver.aws.syncbak.com/mpl/20160401/865666/5743360/media.m3u8?request_token=Z1-ZrI8l37vCBmH6YKlQZNFcvAXYiLJN8c0K9gQTvqeAS2QJAdKCNfJi781AV_GZ0FiNd9AuyH162KN25KKJ1iwvz5KrioIJ6D1yPHrvpZ68JmiHTY6U93wIgD_NiMxFXxR_tw_MCi_hka74r9ng6aLxngs2p8TTSlCW71SMmjHsk4wN7kcHLDtoRtcivA&CMCD=mtp%3D111600%2Cot%3Dm%2Csf%3Dh%2Csid%3D%22ac2d9503-527a-4258-a660-a8841776bd7c%22

### Quality

1080p

### Label

Geo Restricted To USA

### Timeshift

-7

### Notes

I found this link while Subscribed to Paramount+ and took the M3U8 file directly from the service. I handed it over to Dish Network's New IPTV stream as well, they accepted it. I was hoping you would as well. Ive tested it after unsubbing from Paramount for 9 months and its still working great! I believe its the Primary link and therefore will not expire!

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
I have my doubts to anything syncbak-related, those are tokenized. The request token isn't indefinite.

**Comment by BellezaEmporium** [comment]
By the way : https://github.com/iptv-org/iptv/issues/15719#issuecomment-1936828024

**Comment by simminecrafter** [comment]
> I have my doubts to anything syncbak-related, those are tokenized. The request token isn't indefinite.

After looking at their TOS i see what you mean about it tracking who has access to that token. However im also suprised they havent gotten me on 2 things. Using their token outside my contract (breaking TOS) and Using the stream OUTSIDE of Paramount Plus itself (also against their TOS). But, i bet they dont care since i been enjoying it 9 months without P+ so far.

**Comment by simminecrafter** [comment]
Any updates as to if this is going live at all?

**Comment by BellezaEmporium** [comment]
Well I wouldn't personally approve it as it might contain a personal token. If it's seen around it might be an instant flag.

**Comment by rushereeeeee** [comment]
I actually did the same thing with the WTSP-DT stream

**Comment by BellezaEmporium** [comment]
> I actually did the same thing with the WTSP-DT stream

While I might not have checked all pull requests concerning the matter, I suggest not to give such links. With the host possibly checking in leaked tokens.

**Comment by rushereeeeee** [comment]
yeah… :/ really not the best idea.. ik
