### ISSUE TITLE
DMCA takedown 2024-10-29-oledistribution.rtf

### ISSUE THREAD

**Issue by Daniel15** [iptv-org/iptv#17874]
@iptv-org/core I received a DMCA takedown notice "2024-10-29-oledistribution", however the notice doesn't say which content to remove. It just links to `https://iptv-org.github.io/iptv/index.category.m3u`. I'm going to reply to GitHub and ask for clarification.

**Comment by BellezaEmporium** [comment]
Information is telling me they're the operators behind A+E, History, Universal Channel, Lifetime, E!, CNBC, Dreamworks Channel, Telemundo, USA Network, IVC and AXN in all of Latin America. Safe bet is to remove them all.

**Comment by freearhey** [comment]
The attachment actually contains the name of the channel, it's `Sony Channel(Movies)`.

<details>

<summary>Email from GitHub</summary>

> Hi iptv-org,
> 
> I'm contacting you on behalf of GitHub because we've received a DMCA takedown notice regarding the following content:
> 
> https://iptv-org.github.io/iptv/index.category.m3u
> 
> We're giving you 1 business day to make the changes identified in the following notice:
> 
> https://enterprise.githubsupport.com/attachments/token/1NzULKSuy7NYczQDXTKP6bqUA/?name=2024-10-29-oledistribution.rtf
> 
> If you need to remove specific content from your repository, simply making the repository private or deleting it via a commit won't resolve the alleged infringement. Instead, you must follow these instructions to remove the content from your repository's history, even if you don't think it's sensitive:
> 
> https://docs.github.com/articles/remove-sensitive-data
> 
> Once you've made changes, please reply to this message and let us know. If you don't tell us that you've made changes within the next 1 business day, we'll need to disable the entire repository according to our GitHub DMCA Takedown Policy:
> 
> https://docs.github.com/articles/dmca-takedown-policy/
> 
> If you believe your content on GitHub was mistakenly disabled by a DMCA takedown request, you have the right to contest the takedown by submitting a counter notice, as described in our DMCA Takedown Policy.
> 
> PLEASE NOTE: It is important that you reply to this message within 1 business day to tell us whether you've made changes. If you do not, the repository will be disabled.

</details>

<details>

<summary>Notice</summary>

> We, MarkScan, have been duly authorized by OLE DISTRIBUTION, (Referred as "Our Client") to issue this notice to you under the provisions the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, and the Online Copyright Infringement Liability Limitation Act (OCILLA), a part of the Digital Millennium Copyright Act 1998 (DMCA) whereunder the service providers are to be held strictly liable for the acts of their users are required to cease access to the copyright material, immediately upon being put to notice of the infringement.
> 
> Our Client is the owner of the following copyright work(s), hereinafter referred to as "copyright work(s)":
> 
> Sony Channel(Movies)
> 
> Documentary proof to show that the copyright work(s) belong(s) to our client can be accessed on:  
> https://www.oledistribution.com/.
> 
> We have found material on your website which infringes the copyright of our client in the above works. The infringing material comprises the above-mentioned Television Movies title. Below is/are the URL(s) on which the infringing material can be accessed (hereinafter infringing material(s)):
> 
> https://iptv-org.github.io/iptv/index.category.m3u
> 
> Below are the steps for playing online content from an M3U playlist using a web-based player. The example utilized here leverages the functionality provided by [private]
> 
> Instructions:
> 
> 1. Website Access: Navigate to the online IPTV player at: [private]
> 
> [private]
> 
> 2. Playlist URL: Locate the designated field for entering the playlist URL. This field is labelled "IPTV Playlist URL".
> 
> 3. URL Input: Provide the URL of desired M3U playlist. The example playlist used here is: https://iptv-org.github.io/iptv/index.category.m3u.
> 
> [private]
> 
> 4. Playlist Loading: Upon entering the URL, click the designated button (“Watch”) to initiate the process of loading the playlist content.
> 
> 5. Channel Selection: The web player displays the available channels or content items within the playlist. Select the specific channel (Cine Sony) or item you wish to play.
> 
> [private]
> 
> 6. Playback: After selecting the desired channel/item, playback should commence automatically.
> 
> [private]
> 
> We understand in good faith & belief that the use of the copyright work(s) described above in the infringing material(s) of which the URL(s) have been provided above, is not authorized by the copyright owner, its agent(s), or the law.
> 
> We hereby request you to immediately remove and /or disable access to the infringing material(s) from your website.
> 
> We, under penalty of perjury, state that the information in this Notice is accurate, and state that we are authorized to act on behalf of our client who is the exclusive owner of the copyright that is being infringed. We further declare that the information in this is correct to the best of our belief.
> 
> DIGITAL SIGNATURE FOR COPYRIGHT CLAIM  
> [private]  
> MarkScan  
> Email: [private]  
> [private]  
> Ph: [private], Website: www.markscan.co.in.
> 
> 
> COPYRIGHT OWNERS:  
> OLE DISTRIBUTION.
> 
> Regards,  
> MarkScan [private]  

</details>

**Comment by freearhey** [comment]
I have notified GitHub that all links to the channel have been removed from the repository.
