### ISSUE TITLE
Broken: Some Mongolian livestream channels either went dead or tokenized?

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#17879]
### Broken Link

https://cdn1.skygo.mn/live/disk1/Ekh_Oron/HLS-FTA/Ekh_Oron.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

@BellezaEmporium @Sphinxroot Hey, guys! I found seven Mongolian livestream channels went either died or got tokenized just like Japan Primehome channels most likely due to the technical problems or something.

1. [Central TV](https://cdn1.skygo.mn/live/disk1/Ekh_Oron/HLS-FTA/Ekh_Oron.m3u8) (1080p)
2. [Dream TV](https://cdn1.skygo.mn/live/disk1/Dreambox/HLS-FTA/Dreambox.m3u8) (1080p)
3. [ETV](https://cdn1.skygo.mn/live/disk1/ETV/HLS-FTA/ETV.m3u8) (1080p)
4. [MovieBox](https://cdn1.skygo.mn/live/disk1/Moviebox/HLS-FTA/Moviebox.m3u8) (1080p)
5. [ONTV](https://cdn1.skygo.mn/live/disk1/ONTV/HLS-FTA/ONTV.m3u8) (1080p)
6. [TV8](https://cdn1.skygo.mn/live/disk1/TV8HD/HLS-FTA/TV8HD.m3u8) (1080p)
7. [UBS](https://cdn1.skygo.mn/live/disk1/UBSHD/HLS-FTA/UBSHD.m3u8) (1080p)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by GiovanniSebastian** [comment]
Change "cdn1" to "cdn3"

**Comment by km147** [comment]
None of those new links 1 - 7 you say you've found don't actually work, even with Mongolian VPN 
But changing the URL from cdn1 to cdn3 as suggested -  all work!

**Comment by AVGCFan1995** [comment]
> Change "cdn1" to "cdn3"

Yes, it's working now!
