### ISSUE TITLE
Broken: Telehit (576p)

### ISSUE THREAD

**Issue by San24543** [iptv-org/iptv#17882]
### Broken Link

https://linear-417.frequency.stream/mt/studio/417/hls/master/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

No response

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by km147** [comment]
You're referring to Telehit Mexico - Confirmed stream is down with & without VPN

**Comment by San24543** [comment]
Yes, It has been down 6 months ago

**Comment by km147** [comment]
All their videos, as well as their m3u8 on their website are all reporting 'JW error code 232011'
