### ISSUE TITLE
Broken: ATN News channel

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#17880]
### Broken Link

https://d10rltuy0iweup.cloudfront.net/ATNNEWS/myStream/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

the stream for ATN News channel on website Doesn't work and the offical stream gets the request blocked error,could you please find the new stream link for ATN News channel？
![屏幕截图 2024-10-30 154538](https://github.com/user-attachments/assets/d9f08218-4e9d-4d5f-9a81-f5399fec81b5)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by km147** [comment]
Their website presents a blank content - Looks like a WordPress Inclusion error [jwp-video n="1"] - No sign of any Live content

**Comment by Alstruit** [comment]
[Appears to be working fine.](https://streamtest.in/logs/https-d10rltuy0iweup-cloudfront-net-atnnews-mystream-playlist-m3u8-215d33ec-c165-4f0f-ac38-f64645e7fc04)
