### ISSUE TITLE
Broken: Telehit Música (Mexico)(576p)

### ISSUE THREAD

**Issue by San24543** [iptv-org/iptv#17886]
### Broken Link

https://linear-418.frequency.stream/mt/studio/418/hls/master/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

This stream has been down 6 months ago

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Can this be use as a replacement link?
https://streamer1.nexgen.bz/TELEHIT/index.m3u8
It's Telehit Musica
