### ISSUE TITLE
files for tvg-id that aren't empty

### ISSUE THREAD

**Issue by SmalltalkJava** [iptv-org/iptv#1788]
**Is your feature request related to a problem? Please describe.**
No,  I only use TV guide so it would be nice to have files that only include tvg-id entries that have an id.  That way I will only have channels that are on TV Guide.com

**Describe the solution you'd like**
I would like a file for English channels that  tvg-id equal to some value.  I imagine it would be nice for other languages.

**Describe alternatives you've considered**
I tried to manually edit the english file, but there are about 400 lines and only 50 of them have Id's.  that is a lot of manual line by line editing.

**Additional context**

**Comment by bertperrisor** [comment]
This is very trivial - no one has ever asked just because they don't want channels that don't have guide.

Anyway there are only 49 channels with guides 
```
$ cat eng.m3u | grep EXTINF | grep -v "tvg-id=\"\"" | wc -l
      49
```
Now that you can find the line numbers for these channels, the manual work can be significantly reduced:
```
$ cat eng.m3u | grep EXTINF | grep -v "tvg-id=\"\"" -n
```

**Comment by freearhey** [comment]
@SmalltalkJava Could you please explain how you download an EPG from tvguide.com? which app are you using?
