### ISSUE TITLE
Add: MTV Lebanon

### ISSUE THREAD

**Issue by Riverrock83** [iptv-org/iptv#17898]
### Channel ID (required)

MTV Lebanon

### Channel Name

MTV Lebanon

### Stream URL (required)

https://live.3cd.io/v1/broadcast/mtv/playlist.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
Please confirm in which player and country does it work for you

**Comment by luutuyen2k9** [comment]
![894_003](https://github.com/user-attachments/assets/0bb043fb-e69b-4466-be55-dc011f4dea66)
stream link does not work
