### ISSUE TITLE
Broken: All Adult Swim show streams

### ISSUE THREAD

**Issue by TanteRegenbogen** [iptv-org/iptv#17890]
### Broken Link

https://adultswim-vodlive.cdn.turner.com/live/metalocalypse/stream_de.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

The following channels wont load anymore:

https://adultswim-vodlive.cdn.turner.com/live/aqua-teen/stream_de.m3u8

https://adultswim-vodlive.cdn.turner.com/live/black-jesus/stream_de.m3u8

https://adultswim-vodlive.cdn.turner.com/live/channel-5/stream_de.m3u8

https://adultswim-vodlive.cdn.turner.com/live/DREAM-CORP-LLC/stream_de.m3u8

https://adultswim-vodlive.cdn.turner.com/live/infomercials/stream_de.m3u8

https://adultswim-vodlive.cdn.turner.com/live/lsotl/stream_de.m3u8

https://adultswim-vodlive.cdn.turner.com/live/metalocalypse/stream_de.m3u8

https://adultswim-vodlive.cdn.turner.com/live/off-the-air/stream_de.m3u8

https://adultswim-vodlive.cdn.turner.com/live/primal/stream_de.m3u8

https://adultswim-vodlive.cdn.turner.com/live/rick-and-morty/stream_de.m3u8

https://adultswim-vodlive.cdn.turner.com/live/robot-chicken/stream_de.m3u8

https://adultswim-vodlive.cdn.turner.com/live/samurai-jack/stream_de.m3u8

https://adultswim-vodlive.cdn.turner.com/live/eric-andre/stream_de.m3u8

https://adultswim-vodlive.cdn.turner.com/live/venture-bros/stream_de.m3u8

https://adultswim-vodlive.cdn.turner.com/live/ypf/stream_de.m3u8

![screenshot00000](https://github.com/user-attachments/assets/71241853-11c2-4018-a272-c52cf23c1935)

Despite saying [Geo-blocked] it worked fine before.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Appears to be program issue. All links provided are working fine.
