### ISSUE TITLE
Broken: CNN International

### ISSUE THREAD

**Issue by TKList** [iptv-org/iptv#17900]
### Broken Link

https://cnn-cnninternational-1-eu.rakuten.wurl.tv/playlist.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Yodoma** [comment]
Found a link online that works: https://turnerlive.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_0_3564000.m3u8

**Comment by TKList** [comment]
Thanks, but that is CNN not CNNI

**Comment by oldbrowang** [comment]
Here is one. 
https://stream1.cinerama.uz/1259/tracks-v1a1/mono.m3u8
But the quality is low.

**Comment by alexupit** [comment]
> Here is one. https://stream1.cinerama.uz/1259/tracks-v1a1/mono.m3u8 But the quality is low.

Decent quality 576i SD. Thank you!

**Comment by Smark223** [comment]
> Thanks, but that is CNN not CNNI

This is the International version

[](https://turnerlive.warnermediacdn.com/hls/live/586497/cnngo/cnni/VIDEO_0_3564000.m3u8)

**Comment by luutuyen2k9** [comment]
Stream didn't play on VLC, but the stream link tested on mpv and it plays

> Found a link online that works: https://turnerlive.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_0_3564000.m3u8

**Comment by luutuyen2k9** [comment]
Stream didn't play on VLC, but the stream link was tested on mpv and it plays

> This is the International version
> 
> https://turnerlive.warnermediacdn.com/hls/live/586497/cnngo/cnni/VIDEO_0_3564000.m3u8

**Comment by freelancerage** [comment]
Is CNN allowed to be added back?

**Comment by freearhey** [comment]
> Is CNN allowed to be added back?

Unfortunately, no.

https://github.com/iptv-org/iptv/issues/16839

**Comment by Yodoma** [comment]
Please be advised that MarkScan Entertainment, has been associated with several controversies on false copyright claims. They're an Indian company headquartered in New Delhi.

https://www.reddit.com/r/youtube/comments/yfnnmz/who_is_this_markscan_entertainment/
https://www.youtube.com/watch?v=k4rKkIRnE-M
https://www.youtube.com/watch?v=2nqtqIzgu1Y
https://www.youtube.com/watch?v=ZyJNMSG16XQ
https://www.youtube.com/playlist?list=PLjkF4hJYomBOSjpBQf1TzvZ3fHIiym0d4
https://www.youtube.com/results?search_query=Markscan+enforcement

although
https://markscan.co.in/mediascan/
https://transparencyreport.google.com/copyright/reporters/43177?request_by_owner=size:10;org:43177;p:MTpBTExfVElNRTozOjQzMTc3OjEwOjEwOjIw&lu=request_by_owner

**Comment by alexpitro** [comment]
Does anyone have new links for CNN and CNNi? The CNN stream link posted here does not show live content anymore. It shows a very old news and every time you start it, it starts with the same content, like a vod and the CNNi stream does not work at all. Only the SD cinerama link seems to be still working.

**Comment by alexpitro** [comment]
I found a working stream for CNN, HD, which seems to be stable:
https://rtmp2.livenewsof.com/livenewsof.com/qJbteqvER7/1.m3u8

For CNN International, SD quality only, but very stable and longtime working:
https://stream1.cinerama.uz/1259/tracks-v1a1/mono.m3u8

Bonus, if anyone is interested, Fox News HD:
https://rtmp2.livenewsof.com/livenewsof.com/qJbteqvER7/5.m3u8

**Comment by alexupit** [comment]
CNN USA (HD, stable):
https://rtmp2.livenewsof.com/livenewsof.com/qJbteqvER7/1.m3u8

CNN International (SD, stable):
https://stream1.cinerama.uz/1259/index.m3u8

BONUS:
Fox News (HD, stable):
https://rtmp2.livenewsof.com/livenewsof.com/qJbteqvER7/5.m3u8
