### ISSUE TITLE
Broken: Most JP channels can be fixed by merging this file

### ISSUE THREAD

**Issue by chugor** [iptv-org/iptv#17909]
### Broken Link

https://iptv-org.github.io/iptv/countries/jp.m3u

### What happened to the stream?

Not loading

### Notes (optional)

https://github.com/luongz/iptv-jp/blob/main/jp.m3u

These links inside are working, how about we merge these link to bring back JP channels

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by otus01** [comment]
Apparently those links are a no go.

https://github.com/iptv-org/iptv/issues/17868#issuecomment-2441217183
