### ISSUE TITLE
Add: MTV Live (International)

### ISSUE THREAD

**Issue by San24543** [iptv-org/iptv#17917]
### Channel ID (required)

MTVLive.uk

### Channel Name

MTV Live (International)

### Stream URL (required)

http://207.248.2.195:8000/play/a01e

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by km147** [comment]
Doesn't work & doesn't look legit

**Comment by San24543** [comment]
maybe replace it: http://190.102.246.93:9005/play/a01p
