### ISSUE TITLE
Broken: JORX-DTV (Didn't load, shows 404 or ERR_NAME_NOT_RESOLVED in the dev console...)

### ISSUE THREAD

**Issue by WhaleStudiosDev** [iptv-org/iptv#17922]
### Broken Link

https://tbs4.mov3.co/hls/tbs.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Kindly please update the link from https://tbs4.mov3.co/hls/tbs.m3u8 to https://tbs5.mov3.co/hls/tbs.m3u8 on JORX-DTV if you can. Thanks.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Link is stuck at a single frame.

**Comment by WhaleStudiosDev** [comment]
It just unfreezed when I checked the next day.

**Comment by BellezaEmporium** [comment]
It came back indeed.
