### ISSUE TITLE
Add: Blaze TV

### ISSUE THREAD

**Issue by trancer1994** [iptv-org/iptv#17923]
### Channel ID (required)

BlazeTV.us

### Channel Name

Blaze TV

### Stream URL (required)

https://photocall.site/m3dr/if?if=pl&ch=blazetv

### Quality

None

### Label

None

### Notes

I know this channel I'm adding is already here, but it's here under the wrong channel name ("Blaze Live" instead of "Blaze TV") (this is the US channel, not the UK one) and the stream we have for it only plays about ten seconds on VLC before stopping. This stream, unfortunately, is from an external site (photocalltv.site). The URL for it is hidden behind a redirect https://photocall.site/m3dr/if?if=pl&ch=blazetv which takes you to the photocall.tv homepage. Once you're there, click "Internacionales" then "Blazetv (Estados Unidos"). The page will then load, and once you're there and it's all loaded, click the play button. Note: You must use Croam or Edge, and if you use Croam you must install the HLS Player extension first, as Croam does not seem to natively support HLS playback (I tried on Edge but got the same error, but the extension I need only installs on Croam, and the channel will not work on Firefox). The reason I haven't put an m3u8 URL in the stream URL box is because unless I'm doing something wrong, the extension I'm using to detect the stream URLs isn't working on that channel. Can you try to extract the stream URL for me? To make it even worse the page doesn't seem to support dev tools, as pressing F12 to open it closes the page, stops the stream and just takes me back to the homepage (it has a disabledevtools.js script hidden within its source code), so if you want to extract the URL you'll have to do it by another method. I'm sorry this is so complicated but it's all I've got. Or you could go to Blaze TV's website https://subscribe.blazetv.com/ (I think it's a subscription channel though but the photocall thing gives you the stream you would get if you were subscribed). 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
The on photocall it the plutoTV version
https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5e46fba0c43b0d00096e5ac1/master.m3u8?deviceId=0&deviceVersion=0&appVersion=0&deviceType=0&deviceMake=0&sid=784a4549-3f77-4b84-e9ad-8ee28d11b090&deviceDNT=0&deviceModel=0

**Comment by R4IN2007** [comment]
BrazeLive and BrazeTV are both Blaze+ channels
