### ISSUE TITLE
Add: Telehit (Mexico)(1080p)

### ISSUE THREAD

**Issue by San24543** [iptv-org/iptv#17920]
### Channel ID (required)

TeleHit.mx

### Channel Name

Telehit

### Stream URL (required)

http://45.175.139.194:8000/play/62

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by km147** [comment]
This stream is proving very unreliable for me - could be a temporary problem. I'll monitor and report back in a week
