### ISSUE TITLE
Add: Rocky Mountain PBS Kids

### ISSUE THREAD

**Issue by jayc3-cmyk** [iptv-org/iptv#17926]
### Channel ID (required)

RMPBSKids.us

### Channel Name

RMpbs Kids

### Stream URL (required)

https://dce3793146fef017.mediapackage.us-west-2.amazonaws.com/out/v1/55cdf73af7894775ba6de8f57482b66a/CMAF_HLS/index.m3u8

### Quality

576p

### Label

None

### Timeshift

-7

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
No sound

**Comment by jayc3-cmyk** [comment]
Weird. It worked for me.

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-id="",https://www.rmpbs.org/live/pbs-kids
https://dce3793146fef017.mediapackage.us-west-2.amazonaws.com/out/v1/55cdf73af7894775ba6de8f57482b66a/CMAF_HLS/index.m3u8

**Comment by km147** [comment]
That most recent URL includes the Audio Track and works perfectly - whereas index_1.m3u8 excludes it

**Comment by R4IN2007** [comment]
Are others PBS Channels are Geo Location DRM???
I have some working PBS Channels

**Comment by Syashanurshahana** [comment]
> ### Channel ID (required)
> RMPBSKids.us
> 
> ### Channel Name
> RMpbs Kids
> 
> ### Stream URL (required)
> https://dce3793146fef017.mediapackage.us-west-2.amazonaws.com/out/v1/55cdf73af7894775ba6de8f57482b66a/CMAF_HLS/index.m3u8
> 
> ### Quality
> 576p
> 
> ### Label
> None
> 
> ### Timeshift
> -7
> 
> ### HTTP User Agent
> _No response_
> 
> ### HTTP Referrer
> _No response_
> 
> ### Notes
> _No response_
> 
> ### Contributing Guide
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)
