### ISSUE TITLE
Add: Telehit Musica (Mexico)(1080p)

### ISSUE THREAD

**Issue by San24543** [iptv-org/iptv#17921]
### Channel ID (required)

TelehitMusica.mx

### Channel Name

Telehit Musica

### Stream URL (required)

http://190.60.42.86:8000/play/a02x/index.m3u8

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
https://srdiegoiptvfast.alwaysdata.net/pagtv/telelatino/236.m3u8
TELEHIT MUSICA PLUS
