### ISSUE TITLE
Broken: Clarity 4k

### ISSUE THREAD

**Issue by Majinkensword** [iptv-org/iptv#17937]
### Broken Link

https://d6s2o8so4wk28.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-2vzmnn0zl3exh-prod/amgclarity4k/playlist.m3u8

### What happened to the stream?

Shows looped video

### Notes (optional)

Not sure if it's just me but I noticed looped video of the horses the entire 2 days now.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by zwanski2019** [comment]
the scream cut off?

**Comment by Majinkensword** [comment]
> the scream cut off?

No, looping video... play like 20-30 seconds, then repeats continuously.
