### ISSUE TITLE
Broken: Game Show Network (East) - KlowdTV

### ISSUE THREAD

**Issue by JakeStorm-Dev** [iptv-org/iptv#17932]
### Broken Link

https://cdn.klowdtv.net/803B48A/n1.klowdtv.net/live2/gsn_720p/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Still looking into this but the folks at KlowdTV may not know it's down yet.  It was fine about a week ago but has stopped connecting.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by GiovanniSebastian** [comment]
Delete "cdn.klowdtv.net/803B48A/"

**Comment by rushereeeeee** [comment]
Your probably using the wrong link

**Comment by rushereeeeee** [comment]
http://n1.klowdtv.net/live2/gsn_720p/chunks.m3u8

**Comment by tvongsaly4592** [comment]
> Contributor

Edge couldn't reach that page on my iPhone and not loading on PC.

**Comment by rushereeeeee** [comment]
Outdated

**Comment by tvongsaly4592** [comment]
[](https://streamer1.nexgen.bz/GSN/index.m3u8) This stream works. But no captions are available on the stream.

**Comment by rushereeeeee** [comment]
Wait nvm cause that one doesn’t have any captions

**Comment by tvongsaly4592** [comment]
> Wait nvm cause that one doesn’t have any captions

New link with captions! Add the a- before the cdn.klowdtv.com/live2/gsn_720p/playlist.m3u8 and it becomes [cdn.klowdtv.com/live2/gsn_720p/playlist.m3u8](https://a-cdn.klowdtv.com/live2/gsn_720p/playlist.m3u8]

**Comment by rizqherisk48** [comment]
(BREAKING) https://a-cdn.klowdtv.com/live2/gsn_720p/playlist.m3u8 This streaming site is down! Or is there a problem, guys? We need your help!

**Comment by tvongsaly4592** [comment]
> (BREAKING) https://a-cdn.klowdtv.com/live2/gsn_720p/playlist.m3u8 This streaming site is down! Or is there a problem, guys? We need your help!

It's still working for me.

<img width="511" height="287" alt="Image" src="https://github.com/user-attachments/assets/24691b2a-3d9f-4c0b-a6c5-785ca24850d8" />
