### ISSUE TITLE
Broken:  canal 2 El Salvador 

### ISSUE THREAD

**Issue by KarenU04** [iptv-org/iptv#17948]
### Broken Link

https://telecorporacion-es.cdn.vustreams.com/live/d3e259fa-736d-46b0-b1c9-71caf946ace9/live.isml/live.m3u8

### What happened to the stream?

Other

### Notes (optional)

![IMG_2646](https://github.com/user-attachments/assets/2673e17f-8492-446f-901b-78afd8185264)
Dejó de funcionar canal 2 El Salvador por favor verificar 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://telecorporacion-es.cdn.vustreams.com/live/d3e259fa-736d-46b0-b1c9-71caf946ace9/live.isml/live.m3u8
<img width="1428" alt="image" src="https://github.com/user-attachments/assets/4a9a1378-4869-43c5-b788-e2079b47788e">

**Comment by hijuuijj** [comment]
Looking for Canal 4

**Comment by Urfavoritrat** [comment]
It’s not 24/7
