### ISSUE TITLE
Broken : MTV Live (USA)

### ISSUE THREAD

**Issue by San24543** [iptv-org/iptv#17941]
### Broken Link

https://fl5.moveonjoy.com/MTV_LIVE/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Replace with another working stream::

https://fl2.moveonjoy.com/MTV_LIVE/index.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Alstruit** [comment]
Appears to be working now.

**Comment by San24543** [comment]
this steam is broken

**Comment by San24543** [comment]
another stream doesn't have sound
