### ISSUE TITLE
Add: Animax (1080p)

### ISSUE THREAD

**Issue by gnaniippuyo** [iptv-org/iptv#17943]
### Channel ID (required)

Animax.ph

### Channel Name

Animax

### Stream URL (required)

http://202.57.43.60:8443/live/5748aabe4c9d661afbd7f4068248f664/125.m3u8

### Quality

1080p

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Xtream??

**Comment by luutuyen2k9** [comment]
link is geo-blocked, maybe it didn't work outside philppines
also it's a xtream code server link?
