### ISSUE TITLE
Broken: canal 12 El Salvador 

### ISSUE THREAD

**Issue by KarenU04** [iptv-org/iptv#17949]
### Broken Link

https://alba-sv-c12-c12.stream.mediatiquestream.com/original.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Revisar no funciona mal 12 El Salvador 
![IMG_2647](https://github.com/user-attachments/assets/ace9f4c8-2290-4fb9-a52c-102e234cb531)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Syashanurshahana** [comment]
> ### Broken Link
> https://alba-sv-c12-c12.stream.mediatiquestream.com/original.m3u8
> 
> ### What happened to the stream?
> Not loading
> 
> ### Notes (optional)
> Revisar no funciona mal 12 El Salvador ![IMG_2647](https://private-user-images.githubusercontent.com/183173941/386923980-ace9f4c8-2290-4fb9-a52c-102e234cb531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTY1MDUsIm5iZiI6MTczMTg1NjIwNSwicGF0aCI6Ii8xODMxNzM5NDEvMzg2OTIzOTgwLWFjZTlmNGM4LTIyOTAtNGZiOS1hNTJjLTEwMmUyMzRjYjUzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxNTEwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjEyMGQ2NzUyZjgwOWNmYjUwZTZmODIwZmFhNGE3YjkxMGEwNWI4OTRmYTNjNzZhY2RlY2EwOTJhZDc1NWU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fyuHuQZnoR0t02JsQmVG1WQZaeTU0r0bFvj5T-nc0ZY)
> 
> ### Contributing Guide
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Syashanurshahana** [comment]
> > ### Broken Link
> > https://alba-sv-c12-c12.stream.mediatiquestream.com/original.m3u8
> > ### What happened to the stream?
> > Not loading
> > ### Notes (optional)
> > Revisar no funciona mal 12 El Salvador ![IMG_2647](https://private-user-images.githubusercontent.com/183173941/386923980-ace9f4c8-2290-4fb9-a52c-102e234cb531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTY1MDUsIm5iZiI6MTczMTg1NjIwNSwicGF0aCI6Ii8xODMxNzM5NDEvMzg2OTIzOTgwLWFjZTlmNGM4LTIyOTAtNGZiOS1hNTJjLTEwMmUyMzRjYjUzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxNTEwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjEyMGQ2NzUyZjgwOWNmYjUwZTZmODIwZmFhNGE3YjkxMGEwNWI4OTRmYTNjNzZhY2RlY2EwOTJhZDc1NWU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fyuHuQZnoR0t02JsQmVG1WQZaeTU0r0bFvj5T-nc0ZY)
> > ### Contributing Guide
> > 
> > * [x]   I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Syashanurshahana** [comment]
> ### Broken Link
> https://alba-sv-c12-c12.stream.mediatiquestream.com/original.m3u8
> 
> ### What happened to the stream?
> Not loading
> 
> ### Notes (optional)
> Revisar no funciona mal 12 El Salvador ![IMG_2647](https://private-user-images.githubusercontent.com/183173941/386923980-ace9f4c8-2290-4fb9-a52c-102e234cb531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTY3NDMsIm5iZiI6MTczMTg1NjQ0MywicGF0aCI6Ii8xODMxNzM5NDEvMzg2OTIzOTgwLWFjZTlmNGM4LTIyOTAtNGZiOS1hNTJjLTEwMmUyMzRjYjUzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxNTE0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODMxMTQxYTg0NTlkYjRiZmM0N2UzZjVlYmMxZTRjNWRjNTgwM2JiYjhlNGI0YmQ2Mjc3YWIzMGUxYWFkNzgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wFpgEHXZp3GuN5yVJS7qvsxE4-3_wMnFUPujWXAPnhw)
> 
> ### Contributing Guide
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Syashanurshahana** [comment]
@Syashanurshahana 
Issue: ➕ I`
[-----streams_add.yml.txt](https://github.com/user-attachments/files/17791049/-----streams_add.yml.txt)
`

**Comment by luiski90** [comment]
Este canal está funcionando perfectamente con el mismo link, sólo que tienes mal escrito la última palabra que termina con .m3u8 en vez de original.m3u8 debes cambiarlo a index.m3u8 osea quedaría así: 
https://alba-sv-c12-c12.stream.mediatiquestream.com/index.m3u8 por eso te lanzaba ese error

**Comment by KarenU04** [comment]
Gracias muy amable

**Comment by Maguz0** [comment]
YO TENGO UN PEQUEÑO DETALLE ES ESTE 

<img width="1262" height="715" alt="Image" src="https://github.com/user-attachments/assets/41affe11-b1f6-448e-9fa4-1365f69666fa" />
