### ISSUE TITLE
Broken: Cbeebies HD

### ISSUE THREAD

**Issue by Westh977** [iptv-org/iptv#17946]
### Broken Link

https://vs-cmaf-pushb-uk-live.akamaized.net/x=4/i=urn:bbc:pips:service:cbeebies_hd/iptv_hd_abr_v1.mpd

### What happened to the stream?

Not loading

### Notes (optional)

Hello, This Stream Is Not Working Can Someone Find A New Link Please

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BlindWanda** [comment]
Cbeebies HD works perfectly fine.

![cbeebieshd](https://github.com/user-attachments/assets/e7fb966d-4344-46f5-87a4-4b9b65d7b917)

**Comment by Westh977** [comment]
it's still doesnt work

**Comment by Alstruit** [comment]
Geo-blocked to UK closing.
