### ISSUE TITLE
Add: TV4 FHD

### ISSUE THREAD

**Issue by Irylek** [iptv-org/iptv#17956]
### Channel ID (required)

TV4.pl

### Channel Name

TV4

### Stream URL (required)

 https://lb2-e2-32.pluscdn.pl/ch/1502601/309/dash/e25c2c93/live.mpd

### Quality

1080p

### Label

Geo-blocked

### Timeshift

3 minutes

### Notes

grabbed from cda.pl/tv, no drm.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Works for me... wonder why the "geo".
