### ISSUE TITLE
Add: Polsat FHD

### ISSUE THREAD

**Issue by Irylek** [iptv-org/iptv#17955]
### Channel ID (required)

Polsat.pl

### Channel Name

Polsat

### Stream URL (required)

https://lb2-e2-19.pluscdn.pl/ch/1502600/308/dash/20a18c30/live.mpd

### Quality

1080p

### Label

Geo-blocked

### Timeshift

3 minutes

### Notes

grabbed from cda.pl/tv, seems to not have any drm.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Worked for me... so i wonder why the geo.

**Comment by GiovanniSebastian** [comment]
Geo-blocked in Chile

**Comment by BellezaEmporium** [comment]
Sounds good to me then.
