### ISSUE TITLE
Add: 

### ISSUE THREAD

**Issue by ChhunKuySreng** [iptv-org/iptv#17961]
### Channel ID (required)

BTVNews.kh

### Channel Name

BTV News

### Stream URL (required)

https://live-evg2.tv360.metfone.com.kh/livetest/bayontest.stream/playlist.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by AVGCFan1995** [comment]
@ChhunKuySreng Whoa, I didn't notice there's a Cambodian user on GitHub especially among the livestreaming community.

**Comment by luutuyen2k9** [comment]
I can confirm this stream link seems to be working and plays fine
![image](https://github.com/user-attachments/assets/fa5a3083-1c35-46a7-b0e4-04fce3177bde)
