### ISSUE TITLE
Broken: 4 Mongolian(MN) MNB Stations Broken - New URLs

### ISSUE THREAD

**Issue by km147** [iptv-org/iptv#17968]
### Broken Link

https://live.mnb.mn/live/mnb_sport.stream/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

MNB Sport 
Old URL https://live.mnb.mn/live/mnb_sport.stream/playlist.m3u8
New URL: https://live.mnb.mn/hls/mnb_sport.stream.m3u8

MNB World
Old URL https://live.mnb.mn/live/mnb_world.stream/playlist.m3u8
New: https://live.mnb.mn/hls/mnb_world.stream.m3u8

MNB Mongoliin Medee
Old https://live.mnb.mn/live/mn2.stream/playlist.m3u8
New: https://live.mnb.mn/hls/mnb.stream.m3u8

MNB
Old https://live3.mnb.mn/live/mnb.stream/playlist.m3u8
New: https://live.mnb.mn/hls/mn2.stream.m3u8

Further reference
https://www.mnb.mn/live/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/fe1cb18d6d3a0cded696ab7c0ed32e53d3d21230/streams/mn.m3u#L28-L31

https://github.com/iptv-org/iptv/blob/fe1cb18d6d3a0cded696ab7c0ed32e53d3d21230/streams/mn.m3u#L24-L25

https://github.com/iptv-org/iptv/blob/fe1cb18d6d3a0cded696ab7c0ed32e53d3d21230/streams/mn.m3u#L36-L37
