### ISSUE TITLE
Broken: Spain Channels

### ISSUE THREAD

**Issue by gala-vine** [iptv-org/iptv#17964]
### Broken Link

https://iptv-org.github.io/iptv/countries/es.m3u

### What happened to the stream?

Other

### Notes (optional)

Aragon TV stream appears to be Euronews Spain only or different stream completely to the free (directo) stream on their official website https://www.aragontelevision.es/directo .

update with m3u below please.
https://cartv-streaming.aranova.es/hls/live/aragontv_canal1.m3u8

can the Spanish channels for Spain only be checked please.. claims there's 340 channels yet i can see the occasional russian/eastern european channel in there... also some of the channels don't work maybe due to geoblock but not listed as so..

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
AragonTV Int?
