### ISSUE TITLE
Broken: 8TV.my

### ISSUE THREAD

**Issue by kamleong** [iptv-org/iptv#17967]
### Broken Link

https://live-streams-ssai-01.tonton.com.my/live/a884c33b-6b11-4433-8bf9-a8899939e224/live.isml/.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

https://github.com/iptv-org/iptv/blob/master/streams/my.m3u

#EXTINF:-1 tvg-id="8TV.my",8TV (1080p) [Geo-blocked]
https://live-streams-ssai-01.tonton.com.my/live/a884c33b-6b11-4433-8bf9-a8899939e224/live.isml/.m3u8

#EXTINF:-1 tvg-id="TV3.my",TV3 [Geo-blocked]
https://live-streams-ssai-01.tonton.com.my/live/2dd2b7cd-1b34-4871-b669-57b5c9beca23/live.isml/.m3u8

#EXTINF:-1 tvg-id="TV3.my",TV3 (Malaysia) [Geo-blocked]
https://tonton-live-ssai.akamaized.net/live/2dd2b7cd-1b34-4871-b669-57b5c9beca23/cmaf.isml/.m3u8

#EXTINF:-1 tvg-id="TV9.my",TV9 (720p) [Geo-blocked]
https://live-sg1.global.ssl.fastly.net/live-hls/tonton4.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by gohkh0825** [comment]
https://raw.githubusercontent.com/gohkh0825/-TV-/refs/heads/main/m3u/my.m3u
