### ISSUE TITLE
Add: Sukan RTM

### ISSUE THREAD

**Issue by wanfir** [iptv-org/iptv#17969]
### Channel ID (required)

SukanRTM.my

### Channel Name

Sukan RTM

### Stream URL (required)

https://d25tgymtnqzu8s.cloudfront.net/smil:sukan/playlist.m3u8?id=4

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by luutuyen2k9** [comment]
Sukan RTM exists in the iptv-org/iptv repository
https://github.com/iptv-org/iptv/blob/5c03c94185631f8530beccc7a3c1416b73bca4e8/streams/my.m3u#L32-L33
