### ISSUE TITLE
Broken: Game Show Network East (720p) 

### ISSUE THREAD

**Issue by tvongsaly4592** [iptv-org/iptv#17972]
### Broken Link

https://cdn.klowdtv.net/803B48A/n1.klowdtv.net/live2/gsn_720p/playlist.m3u8

### What happened to the stream?

Other

### Notes (optional)

Stream is not loading on PC and shows an "403- Forbidden message" on iOS
Any fixes to this or an possible replacement link?
![IMG_5791](https://github.com/user-attachments/assets/472a7345-d37f-4d9a-95ec-fe0292fa5ebe)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Remove "cdn.klowdtv.net/803B48A/" from the url

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/c2ff4f0aafd1525e0983d4d05b0c7bbab53a653e/streams/us_klowdtv.m3u#L36-L37
