### ISSUE TITLE
Broken: Canal 79 Mar del Plata (AR) Broken & 3 New URLs

### ISSUE THREAD

**Issue by km147** [iptv-org/iptv#17971]
### Broken Link

https://streamconex.com:1936/mardelplata/mardelplata/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

UPDATE: 4 New URLs

Canal 79 Mar del Plata
Old https://streamconex.com:1936/mardelplata/mardelplata/playlist.m3u8
New https://streamconex.com:19360/mardelplata/mardelplata.m3u8

Canal 79 La Costa
Old https://streamconex.com:1936/lacosta/lacosta/playlist.m3u8
New https://streamconex.com:19360/lacosta/lacosta.m3u8

Canal 79 Puan
Old https://streamconex.com:1936/puan/puan/playlist.m3u8
New https://streamconex.com:19360/puan/puan.m3u8

Canal 79 Santa Clara del Mar
Old https://streamconex.com:1936/santaclara/santaclara/playlist.m3u8
New https://streamconex.com:19360/santaclara-1/santaclara-1.m3u8

Ref: https://canal79tv.com.ar/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Canal 79 Santa Clara del Mar Old and New are not working
