### ISSUE TITLE
Are there EPGs for the main m3u with all the channels?

### ISSUE THREAD

**Issue by IzMichael** [iptv-org/iptv#1797]
How can I have an EPG when I use the main m3u with all the channels? (The `https://iptv-org.github.io/iptv/index.m3u` link)

**Comment by Daniel15** [comment]
Some channels have an EPG, but not all of them. For the missing EPGs, pull requests can be sent to add the EPG URLs to the playlist. Documentation on how to do so is in [the CONTRIBUTING.md file](https://github.com/iptv-org/iptv/blob/d1d51f0f2283836bc70ff7578d9344c4f4ef4e53/.github/CONTRIBUTING.md#add-epg-source).
