### ISSUE TITLE
Add: CW (New York)

### ISSUE THREAD

**Issue by rushereeeeee** [iptv-org/iptv#17987]
### Channel ID (required)

WPIXDT1.us

### Channel Name

CW (WPIX)

### Stream URL (required)

https://tx2.nexgen.bz/WPIX/index.m3u8

### Quality

480p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by voxelish** [comment]
yooooooo long time no see rusher, shoot me an email if you see this :)

**Comment by rushereeeeee** [comment]
yoooooooooo ^^
