### ISSUE TITLE
Broken: FOX East (WFXT) (720p)

### ISSUE THREAD

**Issue by tvongsaly4592** [iptv-org/iptv#17982]
### Broken Link

http://143.244.60.30/FOX_EAST/index.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by rushereeeeee** [comment]
FOX (WSVN) - Miami, FL 
https://tx2.nexgen.bz/FOX/index.m3u8
