### ISSUE TITLE
Add: MLB Network

### ISSUE THREAD

**Issue by rushereeeeee** [iptv-org/iptv#17989]
### Channel ID (required)

MLBNetwork.us

### Channel Name

MLB Network

### Stream URL (required)

https://tx2.nexgen.bz/MLB/index.m3u8

### Quality

480p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by hoops2007** [comment]
No sound
