### ISSUE TITLE
Add: Nickelodeon

### ISSUE THREAD

**Issue by rushereeeeee** [iptv-org/iptv#17992]
### Channel ID (required)

NickelodeonEast.us

### Channel Name

Nickelodeon East

### Stream URL (required)

https://tx2.nexgen.bz/NICKELODEON/index.m3u8

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Irylek** [comment]
works for me in 720p!
