### ISSUE TITLE
Add: MSNBC

### ISSUE THREAD

**Issue by rushereeeeee** [iptv-org/iptv#17990]
### Channel ID (required)

MSNBC.us

### Channel Name

MSNBC

### Stream URL (required)

https://tx1.nexgen.bz/MSNBC/index.m3u8

### Quality

480p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by olg857** [comment]
Seems its on channel 5052
