### ISSUE TITLE
Add: CNBC (Europe)

### ISSUE THREAD

**Issue by rushereeeeee** [iptv-org/iptv#17994]
### Channel ID (required)

CNBCEurope.uk

### Channel Name

CNBC Europe/World

### Stream URL (required)

https://amg01079-nbcuuk-amg01079c1-samsung-es-1261.playouts.now.amagi.tv/playlist/amg01079-nbcuukfast-cnbcpe-samsunges/playlist.m3u8

### Quality

1080p

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by luutuyen2k9** [comment]
It must be geoblocked or something?
![image](https://github.com/user-attachments/assets/cfdb3305-83d8-48c2-b80f-08e6987c2dd3)

**Comment by rushereeeeee** [comment]
Works fine in the US
