### ISSUE TITLE
Add: WTVF-DT1

### ISSUE THREAD

**Issue by tvongsaly4592** [iptv-org/iptv#17999]
### Channel ID (required)

WTVFDT1.us

### Channel Name

NewsChannel 5 Network

### Stream URL (required)

https://apollo.production-public.tubi.io/live/ac-wtvf2.m3u8

### Quality

1080p

### Label

None

### Timeshift

_+0_

### Notes

_Does this channel exist already or not? If not, the channel is in Nashville, Tennessee._

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/9c6d3ec88198a9518d601628eb72daf1805fa742/streams/us_tubi.m3u#L126-L127
