### ISSUE TITLE
Add: PNN TV

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#18001]
### Channel ID (required)

PNN.kh

### Stream URL (required)

http://live.happywatch99.com/livehd8/9ae2181e02142f4cfbc32b177eb2258d.sdp/playlist.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by queazified** [comment]
Livestream now dead or geo-blocked.
