### ISSUE TITLE
Broken: Euronews

### ISSUE THREAD

**Issue by Jeder321** [iptv-org/iptv#18019]
### Broken Link

https://rakuten-euronews-10-be.samsung.wurl.tv/playlist.m3u8

### What happened to the stream?

Other

### Notes (optional)

French stream instead of English, while listed as EuronewsEnglish.fr

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by joaquinito2070** [comment]
We will fix it.
