### ISSUE TITLE
adding new channels

### ISSUE THREAD

**Issue by southerndream56** [iptv-org/iptv#1801]
Hi,
Could you please add 4 Zambian channels in the „AFRICAN“ group,
ZNBC 1,ZNBC2,ZNBC3 and ZNBC 4?
Here are the links for LIVE streaming:

https://www.znbc.co.zm/live-tv-stream
https://www.znbc.co.zm/tv2-live-streaming
https://www.znbc.co.zm/tv3/live-tv-stream
https://www.znbc.co.zm/live-tv4

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-logo="https://www.znbc.co.zm/wp-content/uploads/2018/10/cropped-ZNBC-logo-192x192.png" group-title="",TV1
https://dcunilive159-lh.akamaihd.net/i/dclive_1@1013574/master.m3u8

#EXTINF:-1 tvg-logo="https://www.znbc.co.zm/wp-content/uploads/2018/10/cropped-ZNBC-logo-192x192.png" group-title="", TV2
https://dcunilive135-lh.akamaihd.net/i/dclive_1@149239/master.m3u8
Seem Offline ,I get The Link But nothing Show Up

TV3 Seem Deleted From Site

#EXTINF:-1 tvg-logo="https://www.znbc.co.zm/wp-content/uploads/2018/10/cropped-ZNBC-logo-192x192.png" group-title="",TV4
https://dcunilive258-lh.akamaihd.net/i/dclive_1@348579/master.m3u8

**Comment by southerndream56** [comment]
Thanks so much...great.

**Comment by themak1985** [comment]
Unfortunately those links are expiring. Need permanent links in order to update.

**Comment by Sphinxroot** [comment]
in kodi whit playlistloader TV1 And TV4 are ok only TV2 now  need the whole link so it expire

**Comment by themak1985** [comment]
[Added TV1 and TV4](https://github.com/iptv-org/iptv/commit/5da28884558b09c41a0f84498a7adddc9b344982), Cannot add TV2, TV3. Please open a new issue when you find new streams.
