### ISSUE TITLE
Upset

### ISSUE THREAD

**Issue by AlanDinkle** [iptv-org/iptv#1802]
Most of them don't work in China(›´ω`‹ )

**Comment by chromer030** [comment]
GFW

**Comment by AlanDinkle** [comment]
> GFW

yeah。。。

**Comment by chromer030** [comment]
@AlanDinkle 
Use https://github.com/v2fly/v2ray-core/

**Comment by AlanDinkle** [comment]
> @AlanDinkle 
> Use https://github.com/v2fly/v2ray-core/

Emm... it's an app or something special used in another app?
But thanks anyway~

**Comment by AlanDinkle** [comment]
> @AlanDinkle 
> Use https://github.com/v2fly/v2ray-core/

Honestly I never talk to anyone in GitHub，may I know if you're Chinese ?
