### ISSUE TITLE
Broken: CTN (CTN.us)

### ISSUE THREAD

**Issue by LPhilip1999** [iptv-org/iptv#18028]
### Broken Link

https://ctntv.getstreamhosting.com:1936/CTNTV/CTNTV/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

This link is now broken, I have found the new HLS stream url:
https://hls-live-media-gc.cdn01.net/mpegts/232076_1523529/InUEqGaigvm3LvGrljsaHg/1733430941/media_mpegts_0.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
The local sides have change as well?

**Comment by LPhilip1999** [comment]
All of them yes.

> The local sides have change as well?

**Comment by LPhilip1999** [comment]
Update: stream is broken because I think is tokenized
