### ISSUE TITLE
Add: STAR Channel (Finland)

### ISSUE THREAD

**Issue by enzotime** [iptv-org/iptv#18031]
### Channel ID (required)

STARChannel.fi

### Channel Name

STAR Channnel

### Stream URL (required)

https://live-fi.tvkaista.net/star-channel/live.m3u8?hd=true

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/5c03c94185631f8530beccc7a3c1416b73bca4e8/streams/fi.m3u#L45-L46
