### ISSUE TITLE
Broken: canal 4 el salvador buffering

### ISSUE THREAD

**Issue by herman293** [iptv-org/iptv#18035]
### Broken Link

https://telecorporacion-es.cdn.vustreams.com/live/9c79f472-bb4d-4ab8-848f-eb613f3b1f96/live.isml/live.m3u8

### What happened to the stream?

Constantly interrupts/lagging

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
No broken url added to the issue and other issues was for channel 2 (canal 2)  not channel 4 (canal 4)

**Comment by R4IN2007** [comment]
```Broken Link```
https://telecorporacion-es.cdn.vustreams.com/live/9c79f472-bb4d-4ab8-848f-eb613f3b1f96/live.isml/live.m3u8
```NEW LINK```
https://telecorporacion-es.cdn.vustreams.com/live/5d245474-cad2-47bc-b605-ad04c619247d/live.isml/live.m3u8

**Comment by herman293** [comment]
Thank you. I just tried the new link, CH 4 still not working. Can it be fixed?

**Comment by R4IN2007** [comment]
> Thank you. I just tried the new link, CH 4 still not working. Can it be fixed?

![Screenshot_20241207_165700_Chrome](https://github.com/user-attachments/assets/d34cc8f2-5938-45ba-8070-a1ac71810b9a)
Funciona bien donde estoy amigo, creo que es un error de internet?

**Comment by herman293** [comment]
You can see the ch but it stutters, lags, buffers for seconds. Is this the only link available to watch ch´s from El Salvador, or is there another one out there?
Thank you!

**Comment by tony021280** [comment]
nesecitamos la url de canal 4 de sv

**Comment by R4IN2007** [comment]
Necesita cuenta para tcsgo+ para sacar ahora
