### ISSUE TITLE
Broken: GMA TV

### ISSUE THREAD

**Issue by laleeroy** [iptv-org/iptv#18036]
### Broken Link

https://ythls.armelin.one/channel/UCKL5hAuzgFQsyrsQKgU0Qng.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Sometimes GMA does play for certain period of time (certain show) but most of the time, it doesn't, I also tried using vpn and GMA play but after changing to different channel and changing it back to GMA it won't play again, tested with 2 different ISP and 1 Data for my sim still having the same error.

TV5 doesn't seem to work now, before it was working perfectly fine

![Screenshot_20241206-081804_Sparkle_TV](https://github.com/user-attachments/assets/05587e99-6463-4f10-bd26-92e57750deeb)
![Screenshot_20241206-081745_Sparkle_TV](https://github.com/user-attachments/assets/dbea881f-e446-4cc6-b9ef-f40ceeafa8cf)
![Screenshot_20241206-081726_Sparkle_TV](https://github.com/user-attachments/assets/46ea195d-1739-470e-b5b2-5b7cff451b61)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Cignal token the qp-pldt-live-grp-01-prod.akamaized.net with drm protection & key MPD

**Comment by laleeroy** [comment]
Im noob about this, but found a site that contains lots of Filipino contents, maybe you guys can add it?

https://iptv-libre.pages.dev/#

**Comment by gelo678** [comment]
> Im noob about this, but found a site that contains lots of Filipino contents, maybe you guys can add it?
> 
> https://iptv-libre.pages.dev/#

it's not possible, as the streams uses the .mpd format with clearkey drm tokens (also mostly from cignal). iirc, only .m3u8/.mpd links without any drm tokens are allowed to be added to iptv-org playlists.

additionally, these wag.ika.lat links (ex: https://wag.ika.lat/stream/872206966) aren't meant to be shared on other sites, as they are often taken down quickly once the owner becomes aware of them (most likely from phcorner lol).

hopefully tv5_qp.m3u8 comes back tho, and yes regarding gma (kapuso stream, which is from us_ythls.m3u) some shows are geo-blocked to other countries, therefore you're experiencing the error. try using a vpn server from philippines in that case.

**Comment by freearhey** [comment]
Closed in favor https://github.com/iptv-org/iptv/issues/18109, https://github.com/iptv-org/iptv/issues/18110, https://github.com/iptv-org/iptv/issues/18111
