### ISSUE TITLE
Seeking for TV France

### ISSUE THREAD

**Issue by NicksQ69** [iptv-org/iptv#1803]
**Country of the channel:**
France

**Channel Name:**
RMC Découverte
L'Equipe

**Channel Language:**
French

**Comment by Sphinxroot** [comment]
#EXTINF:-1  tvg-logo="https://i.ibb.co/bvhBK1y/LEquipe-21.png" group-title="France",L'Equipe 21
http://cdn.webtv4.cdnfr.orange.fr/hs/HALO3/hls/equipe21-850463/hls/index.m3u8

LEquipe 21 FR GEO To France
https://www.dailymotion.com/video/x2lefik

#EXTINF:-1 tvg-logo="https://i.imgur.com/FVrOYXe.jpg" group-title="",RMC Decouverte
http://cdn.webtv4.cdnfr.orange.fr/hs/HALO3/hls/rmcdecouverte-850466/hls/index.m3u8


si ta besoin de plus regarde sur mon git jai une playlist hybride sous kodi

**Comment by themak1985** [comment]
See #1868. Added.
