### ISSUE TITLE
Add: Alphabet Lore TV HD [UK]

### ISSUE THREAD

**Issue by Two928** [iptv-org/iptv#18038]
### Channel ID (required)

AlphabetLoreTVHD.uk

### Channel Name

Alphabet Lore TV HD

### Stream URL (required)

https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8

### Quality

1080p

### Label

Geo-blocked

### Notes

it a test channel for alphabet lore tv hd by ftv 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Two928** [comment]
go now

**Comment by voxelish** [comment]
stupid thing i have ever seen in my entire life
