### ISSUE TITLE
Request for following Uganda channels

### ISSUE THREAD

**Issue by blindspot1** [iptv-org/iptv#1804]
Country of the channel:
UGANDA

*Channel Names:

NBS TV (English)
NTV Uganda (English)
BBS TV (Luganda)
Sanyuka TV (Luganda)

Thanks in advance!

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-logo="https://nbs.ug/wp-content/uploads/2019/08/cropped-NBS-TV-Favicon-192x192.png" group-title="",NBS LIVE
https://1488970645.rsc.cdn77.org/live/myStream/playlist.m3u8
https://1488970645.rsc.cdn77.org/live/myStream/chunklist_w259270777.m3u8

NTV LIVE
https://www.youtube.com/watch?v=_zx11RXodWM

BBS TV (Luganda)
http://www.bbstv.ug/
403 Forbidden

Sanyuka TV (Luganda)
https://sanyukatv.ug/
No Live on Site

**Comment by freearhey** [comment]
Closed in favor #1971

**Comment by donmafia3** [comment]
Update for Uganda channel please coz most channels are not working
