### ISSUE TITLE
Add: DD Girnar

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#18059]
### Channel ID (required)

DDGirnar.in

### Stream URL (required)

https://d3eyhgoylams0m.cloudfront.net/v1/manifest/93ce20f0f52760bf38be911ff4c91ed02aa2fd92/ed7bd2c7-8d10-4051-b397-2f6b90f99acb/4a7a0c8a-c58d-43d6-baff-13492d67bf3e/2.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Unable to resolve origin prefix after interpolation.

**Comment by sunyuanzhe** [comment]
i'be updated this request.
