### ISSUE TITLE
Add: NTV Cambodia

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#18052]
### Channel ID (required)

NTV.kh

### Stream URL (required)

http://43.252.18.195:5080/LiveApp/streams/ntvhd.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by luutuyen2k9** [comment]
![image](https://github.com/user-attachments/assets/7600f338-6064-48bb-a118-dea11c3f9060)
Stream link got 404'd
