### ISSUE TITLE
Broken: Yanbian TV1 and Yanbian TV2

### ISSUE THREAD

**Issue by AVGCFan1995** [iptv-org/iptv#18055]
### Broken Link

https://live.ybtvyun.com/video/s10006-ff4eb5dba33d/index.m3u8

### What happened to the stream?

Shows looped video

### Notes (optional)

@BellezaEmporium @Sphinxroot Hey, guys! I found two livestream channels suffers from looping the same video over and over again most likely due to the technical problems or something.

YBTV-1
https://live.ybtvyun.com/video/s10006-ff4eb5dba33d/index.m3u8

YBTV-2
https://live.ybtvyun.com/video/s10006-e9c6f9e4d53b/index.m3u8

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
https://live.ybtvyun.com/video/s10016-ca5bdbc3f06d/index.m3u8

https://live.ybtvyun.com/video/s10016-6d4fe23a90b3/index.m3u8

(mentioning us won't make us come faster)

**Comment by BellezaEmporium** [comment]
I gave you the fixed links for both channels.

**Comment by AVGCFan1995** [comment]
> https://live.ybtvyun.com/video/s10016-ca5bdbc3f06d/index.m3u8
> 
> https://live.ybtvyun.com/video/s10016-6d4fe23a90b3/index.m3u8
> 
> (mentioning us won't make us come faster)

Oh wait, thanks for showing the better livestream links to me!

**Comment by AVGCFan1995** [comment]
> I gave you the fixed links for both channels.

What about 延边卫视 since this [livestream link](http://live.ybtvyun.com/video/s10006-44f040627ca1/index.m3u8?zjild) keep showing the same footage over and over again.

**Comment by BellezaEmporium** [comment]
https://live.ybtvyun.com/video/s10016-5adcf2b11d0d/index.m3u8
