### ISSUE TITLE
Add: Shanghai Education Television Station

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#18061]
### Channel ID (required)

ShanghaiEducationTelevisionStation.cn

### Stream URL (required)

http://223.166.234.114:7777/tsfile/live/1033_1.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment]
Nice finding, I reckon the "tsfile" kind of links...

**Comment by BellezaEmporium** [comment]
https://github.com/iptv-org/iptv/blob/7b3c71d5f598e3b67604e9bb5101942712a137f8/streams/cn_cctv.m3u#L8-L9
