### ISSUE TITLE
Add: DD Meghalaya

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#18066]
### Channel ID (required)

DDMeghalaya.in

### Stream URL (required)

https://d3eyhgoylams0m.cloudfront.net/v1/manifest/93ce20f0f52760bf38be911ff4c91ed02aa2fd92/ed7bd2c7-8d10-4051-b397-2f6b90f99acb/dafc23f6-c3d9-44d7-8d31-27aa80efe0b7/2.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by kokroo** [comment]
@sunyuanzhe Is there a link for DD Kashir?
