### ISSUE TITLE
4u tv

### ISSUE THREAD

**Issue by bombolini** [iptv-org/iptv#18081]
### Describe your issue

Hello There,
Seems like 4U tv is not a Tourkiki channel.
tr.m3u-> #EXTINF:-1 tvg-id="4UTV.tr",4U TV (720p)

All the best
Bombolini

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
"4U TV: Television station in Mahmutlar, Türkiye" 
Source: https://www.google.com/search?q=4u+tv
