### ISSUE TITLE
Broken: Buzzr (1080p) 

### ISSUE THREAD

**Issue by freelancerage** [iptv-org/iptv#18097]
### Broken Link

https://buzzr-roku-us.amagi.tv/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Broken link. 

**Replace with:
https://buzzr-samsungus.amagi.tv/playlist.m3u8**

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/ef208fbda9c513245b183bc3ca6c31ea213f7b3b/streams/us_samsung.m3u#L14-L15
