### ISSUE TITLE
Add: Cartoon Network East

### ISSUE THREAD

**Issue by nightfallenxyz** [iptv-org/iptv#18102]
### Channel ID (required)

CartoonNetworkEast.us

### Channel Name

Cartoon Network East

### Stream URL (required)

https://84.17.40.25/CARTOON_NETWORK/index.m3u8

### Quality

1080p

### Label

Geo-blocked

### Notes

i THINK it works. Clicking the link brings you to the stream but my iptv player on my tv just loads for it. Maybe a issue with the player I’m using.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
Sorry, but we cannot add the channel to the playlist due to claims of the copyright holder: https://github.com/iptv-org/iptv/issues/16839

**Comment by BlurnSox** [comment]
doesn’t work anymore
