### ISSUE TITLE
Broken: Nexgen Channels

### ISSUE THREAD

**Issue by rushereeeeee** [iptv-org/iptv#18129]
### Broken Link

https://tx2.nexgen.bz/WPIX/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

channels starting with tx are down. The stream host prob took them down

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/18148
