### ISSUE TITLE
Add: Bang Bang

### ISSUE THREAD

**Issue by MaxWorld378** [iptv-org/iptv#18127]
### Channel ID (required)

BangBang.al

### Channel Name

Bang Bang

### Stream URL (required)

https://example.com/bangbang.m3u8

### Quality

None

### Label

None

### HTTP Referrer

digitalb.al

### Notes

![Bang_Bang_Albania](https://github.com/user-attachments/assets/7618a2fd-5b08-40c8-9abd-a64ce78316b4)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by km147** [comment]
Not a steam

**Comment by voxelish** [comment]
lmfaooooooooo
