### ISSUE TITLE
Broken: tele tchad

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#18126]
### Broken Link

https://strhlslb01.streamakaci.tv/str_tchad_tchad/str_tchad_multi/playlist.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

This stream used to work several months ago,today i've opened this stream which says 403 forbidden,is there any new stream for that?

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Carlinhos027** [comment]
https://webcast.streamakaci.com/tchad/

https://strhls.streamakaci.tv/str_tchad_tchad/str_tchad_multi/playlist.m3u8

The channel still broadcasting, but seems they protected the link somehow.

**Comment by Irylek** [comment]
not loading for me
