### ISSUE TITLE
Broken: MTV Classic East

### ISSUE THREAD

**Issue by freelancerage** [iptv-org/iptv#18123]
### Broken Link

https://fl5.moveonjoy.com/MTV_CLASSIC/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Not loading page. 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://fl5.moveonjoy.com/MTV_CLASSIC/index.m3u8
![image](https://github.com/user-attachments/assets/e41da90f-af0c-4a6d-b47a-cfa3182c1030)
