### ISSUE TITLE
Amount of channels do not match the repo .m3u file

### ISSUE THREAD

**Issue by Ya563** [iptv-org/iptv#18150]
### Describe your issue

Hello, on the homepage of this iptv repo, when I search for the country Morocco, it says it has 70 channels, 
![moroco](https://github.com/user-attachments/assets/3293ee81-13dc-40ac-9299-044f175f036b)

However, when I navigate to the ma.m3u file in this github repo (https://github.com/iptv-org/iptv/blob/master/streams/ma.m3u), it has nowhere near 70 channels in the raw file. Is this a bug? This m3u file should have 70 links right, why does it have so few links?

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
There is no error here. The links in the playlist (https://iptv-org.github.io/iptv/countries/ma.m3u) are grouped by countries where the channel is available, and in the repository (https://github.com/iptv-org/iptv/blob/master/streams/ma.m3u) by the country where it is broadcast from.
