### ISSUE TITLE
New URL at 10 Channel (Greece)

### ISSUE THREAD

**Issue by George210** [iptv-org/iptv#18165]
### Stream URL (required)

https://castor.streamthatvideo.co:8081/10channel/tracks-v1a1/mono.m3u8

### Channel ID

10Channel.gr

### Channel Name

10 Channel

### Quality

576p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
To add a new link to your playlist please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=streams%3Aadd&projects=&template=-----streams_add.yml&title=Add%3A+

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-add-a-new-stream-link-to-a-playlists

**Comment by George210** [comment]
This Channel already existed, is this not a matter of update?
Do I have to add new url stream??

**Comment by freearhey** [comment]
> Do I have to add new url stream??

Yes.
