### ISSUE TITLE
Edit: New URL for Aigaio TV | AigaioTV.gr | Greece

### ISSUE THREAD

**Issue by George210** [iptv-org/iptv#18167]
### Stream URL (required)

https://glb.bozztv.com/glb/ssh101/aigaiotv/index.m3u8

### Channel ID

AigaioTV.gr

### Channel Name

Aigaio TV

### Quality

360p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
To add a new link to your playlist please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=streams%3Aadd&projects=&template=-----streams_add.yml&title=Add%3A+

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-add-a-new-stream-link-to-a-playlists
