### ISSUE TITLE
Edit: New URL for ERTSports1.gr | ERT Sports 1 | Greece

### ISSUE THREAD

**Issue by George210** [iptv-org/iptv#18175]
### Stream URL (required)

http://hbbtvapp.ert.gr/stream.php/v/vid_ertsports_mpeg.2ts

### Channel ID

ERTSports1.gr

### Channel Name

ERT Sports 1

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
To add a new link to playlist please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=streams%3Aadd&projects=&template=-----streams_add.yml&title=Add%3A+

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-add-a-new-stream-link-to-a-playlists
