### ISSUE TITLE
Please fix KCTV North Korea

### ISSUE THREAD

**Issue by lonzasbro** [iptv-org/iptv#1817]
**What's wrong?**
it's broken
**Country of the channel:**
North Korea
**Channel Name:**
Korean Central Television (KCTV)
**Broken Link:**

`https://tv.nknews.org/tvhls/stream.m3u8`
**Additional Information (optional):**
new link: `https://tv.nknews.org/tvdash/stream.mpd`

**Comment by themak1985** [comment]
Confirmed broken, Updated code.
