### ISSUE TITLE
Edit: New URL for RealMusicTV.gr | Real Music TV | Greece

### ISSUE THREAD

**Issue by George210** [iptv-org/iptv#18178]
### Stream URL (required)

https://webtv.topwebhost.gr:3302/stream/play.m3u8

### Channel ID

RealMusicTV.gr

### Channel Name

Real Music TV

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
To add a new link to playlist please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=streams%3Aadd&projects=&template=-----streams_add.yml&title=Add%3A+

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-add-a-new-stream-link-to-a-playlists
