### ISSUE TITLE
Edit: New URL for  RedMusic.gr |  RedMusic | Greece

### ISSUE THREAD

**Issue by George210** [iptv-org/iptv#18179]
### Stream URL (required)

https://fr.crystalweb.net:1936/redmusic/redmusic/playlist.m3u8

### Channel ID

 RedMusic.gr

### Channel Name

 RedMusic

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
To add a new link to playlist please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=streams%3Aadd&projects=&template=-----streams_add.yml&title=Add%3A+

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-add-a-new-stream-link-to-a-playlists
