### ISSUE TITLE
Edit: New URL for  ERTNews.gr | ERT News | Greece

### ISSUE THREAD

**Issue by George210** [iptv-org/iptv#18171]
### Stream URL (required)

http://ertflix.s.llnwi.net/ertlive/ertnews/default/index.m3u8

### Channel ID

 ERTNews.gr

### Channel Name

ERT News

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
To add a new link to playlist please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=streams%3Aadd&projects=&template=-----streams_add.yml&title=Add%3A+

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-add-a-new-stream-link-to-a-playlists
