### ISSUE TITLE
Edit: New URL for BlueSkyTV.gr | Blue Sky TV | Greece

### ISSUE THREAD

**Issue by George210** [iptv-org/iptv#18187]
### Stream URL (required)

https://cdn5.smart-tv-data.com/bluesky/bluesky-live/playlist.m3u8

### Channel ID

BlueSkyTV.gr

### Channel Name

Blue Sky TV

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
To add a new link to playlist please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=streams%3Aadd&projects=&template=-----streams_add.yml&title=Add%3A+

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-add-a-new-stream-link-to-a-playlists
