### ISSUE TITLE
Edit: New URL for ANT1.gr | ANT1 | Greece

### ISSUE THREAD

**Issue by George210** [iptv-org/iptv#18186]
### Stream URL (required)

https://mcdn.antennaplus.gr/live/media0/Ant1/HLS/Ant1.m3u8

### Channel ID

ANT1.gr

### Channel Name

ANT1

### Quality

1080p

### Label

None

### Notes

Turn ANT1 to ANT1 HD please

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
To add a new link to playlist please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=streams%3Aadd&projects=&template=-----streams_add.yml&title=Add%3A+

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-add-a-new-stream-link-to-a-playlists
