### ISSUE TITLE
Add: New URL for MadWorld.gr | Mad World | Greece

### ISSUE THREAD

**Issue by George210** [iptv-org/iptv#18185]
### Channel ID (required)

MadWorld.gr

### Channel Name

Mad World

### Stream URL (required)

https://ellastvmax.better-than.tv/freetv/madworldtv/index.m3u8

### Quality

720p

### Label

None

### Notes

site url: https://mad.gr/mad-world/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by DaHype** [comment]
Any news? Not working. Thank you
