### ISSUE TITLE
Edit: Channel Closed 34100TV.gr | 34100 TV | Greece

### ISSUE THREAD

**Issue by George210** [iptv-org/iptv#18188]
### Stream URL (required)

https://s1.cystream.net/live/34100/playlist.m3u8

### Channel ID

34100TV.gr

### Channel Name

34100 TV

### Quality

None

### Label

None

### Notes

Channel Closed

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by km147** [comment]
Thank you very much for these additions as they have fixed some long standing issues

**Comment by freearhey** [comment]
To report a broken link please use this form: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=broken+stream&projects=&template=--broken-stream.yml&title=Broken%3A+

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-report-a-broken-stream

**Comment by George210** [comment]
I will write down the broken links, but where do I write the new Links???

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-add-a-new-stream-link-to-a-playlists
