### ISSUE TITLE
Add: AcheloosTV.gr

### ISSUE THREAD

**Issue by George210** [iptv-org/iptv#18197]
### Channel ID (required)

AcheloosTV.gr

### Channel Name

Acheloos TV

### Stream URL (required)

https://acheloostv.streamings.gr/live/stream/index.m3u8

### Quality

576p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/cf2033d2c728a64b69939fd90bf92aae91e082e6/streams/gr.m3u#L264-L265
