### ISSUE TITLE
Add: new url for 10Channel.gr

### ISSUE THREAD

**Issue by George210** [iptv-org/iptv#18196]
### Channel ID (required)

10Channel.gr

### Channel Name

10 Channel

### Stream URL (required)

https://tv.mediacp.eu:8081/10channel/index.m3u8

### Quality

360p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/cf2033d2c728a64b69939fd90bf92aae91e082e6/streams/gr.m3u#L4-L5
