### ISSUE TITLE
TV Kanagawa

### ISSUE THREAD

**Issue by Atekuro95** [iptv-org/iptv#1821]
**Country of the channel: Japan**

**Channel Name: TV Kanagawa**

**Channel ID: TVKanagawa.jp**

**Channel Language: Japanese**

**Additional Information (optional):**

**Comment by freearhey** [comment]
Closed in favor #1938

**Comment by LaneSh4d0w** [comment]
The only kind of link I've found is this : https://www.youtube.com/channel/UCtDEkfJlNHq_ONjQnsX5YeA

**Comment by LaneSh4d0w** [comment]
with programmation here ; https://www.tvk-yokohama.com/bangumi/ they work with a 28-hour system.

**Comment by freearhey** [comment]
Closed in favor of #12324
