### ISSUE TITLE
Add: VOX (Germany)

### ISSUE THREAD

**Issue by gajdaalbert98** [iptv-org/iptv#18220]
### Channel ID (required)

VOX.de

### Channel Name

VOX (Germany)

### Stream URL (required)

http://178.219.128.68:64888/VOX

### Quality

576p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by km147** [comment]
invalid or incomplete stream source - but it does play in VLC

**Comment by gajdaalbert98** [comment]
Worked for me

**Comment by gajdaalbert98** [comment]
![image](https://github.com/user-attachments/assets/0754ec00-8afd-4484-bc64-9289240cbfc6)
