### ISSUE TITLE
Add:    Caribbean Showtime TV 

### ISSUE THREAD

**Issue by radioguyana1** [iptv-org/iptv#18233]
Please can you add Caribbean Showtime TV to Guyana Playlist
https://streamer12.vdn.dstreamone.net/carishowtime/showtime/chunks.m3u8

Thanks..

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#how-to-add-a-new-stream-link-to-a-playlists
