### ISSUE TITLE
Hi L@@King for Canada & uk Channels

### ISSUE THREAD

**Issue by chrisjs777** [iptv-org/iptv#1827]
**Country of the channel:**

**Channel Name:**

**Channel Language:**

**Additional Information (optional):**

**Comment by freearhey** [comment]
Please provide the names of the channels you are looking for.

**Comment by yawelcuk** [comment]
CNN

**Comment by chrisjs777** [comment]
Looking for TSN. or any other with Formula 1 thanks chris

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by freearhey** [comment]
Closed in favor #1941
