### ISSUE TITLE
Channel request alerth alnabawi tv channel

### ISSUE THREAD

**Issue by mo7ebb** [iptv-org/iptv#1830]
**Country of the channel:**
Yemen

**Channel Name:**
 Alerth Alnabawi

**Channel Language:**
Arabic

**Additional Information (optional):**
Channel live stream link 
http://jascotvstreaming.com/alerth

Direct streaming link
http://82.212.74.2:8000/live/7307.m3u8

I just couldn’t figure out how to add it to the main playlist
Thank you

**Comment by themak1985** [comment]
Added.
