### ISSUE TITLE
DMCA Takedown Notice

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1831]
Today I received the following email from GitHub Support:

>Hi IPTV,
>
>I'm contacting you on behalf of GitHub because we've received a DMCA takedown notice regarding the following content:
>
>https://github.com/iptv-org/iptv
>
>We're giving you 1 business day to make the changes identified in the following notice:
>
>https://github.zendesk.com/attachments/token/k9lfsiwWTMg1CkAPpQ85GvzM7/?name=2020-12-17-Nagravision.rtf
>
>If you need to remove specific content from your repository, simply making the repository private or deleting it via a commit won't resolve the alleged infringement. Instead, you must follow these instructions to remove the content from your repository's history, even if you don't think it's sensitive:
>
>https://docs.github.com/articles/remove-sensitive-data
>
>Once you've made changes, please reply to this message and let us know. If you don't tell us that you've made changes within the next 1 business day, we'll need to disable the entire repository according to our GitHub DMCA Takedown Policy:
>
>https://docs.github.com/articles/dmca-takedown-policy/
>
>If you believe your content on GitHub was mistakenly disabled by a DMCA takedown request, you have the right to contest the takedown by submitting a counter notice, as described in our DMCA Takedown Policy.
>
>PLEASE NOTE: It is important that you reply to this message within 1 business day to tell us whether you've made changes. If you do not, the repository will be disabled.

The `2020-12-17-Nagravision.rtf` file linked to in the email contains the following:

>NAGRA Notice ID: DISC-20201115NEB36461
>Notice Date: November 15, 2020
>URL: https://iptv-org.github.io/iptv/categories/documentary.m3u
>Source: https://iptv-org.github.io/iptv/categories/documentary.m3u
>Domain: iptv-org.github.io
>
>Dear Sir, Madam,
>
>Nagravision SA (hereinafter "NAGRA") is a provider of secure solutions to protect content of the media and entertainment industry (see www.nagra.com). NAGRA has been engaged and authorized by Discovery Communications, LLC and its affiliates (collectively, "Discovery") to act on their behalf to protect and enforce Discovery’s copyrights and trademarks, whether registered or unregistered, associated with their television channels, including but not limited to Discovery,Discovery Channel,ID Investigation,ID Investigation Discovery,Discovery Family,Discovery Life,Discovery en Espanol,Familia Discovery,Discovery Science,Discovery Home and Health,Discovery Asia,Discovery Shed,Discovery Turbo Xtra,Discovery Theater,Discovery History,Discovery World,World Discovery,Discovery Civiliztion,Discovery Travel and Living,Discovery Historia,HGTV,Food Network,TLC,OWN,Oprah,Animal Planet,Trvl Channel,Motortrend,DIY Network,Cooking Channel,TVN,TVN Style,Tvn 7,TVN Turbo,TVN Fabula,TVN 24,Tvn 24 Bis,TVN Extra,TVN Warszawa,TVN Meteo,TTV,Fine Living,Living Channel,Quest,Quest Red,Focus,Frisbee,Giallo,K2,Nove,Real Time,DKiss,Asian Food Network,TV Norge,DMax,FEM,Vox,Mango,eve,foodtv,food tv,Eurosport,Eurosport 1,Eurosport 2,Fatafeat,GolfTV,Golf TV,HGTV (collectively, the "Channels"), from unauthorized distribution and streams online. This authorization includes:
>
>a.) Monitoring of the Web, pirate forums, major App stores and social media platforms (and other online distribution platforms) to find applications used to illegally distribute its Channels.
>
>b.) Monitoring data sharing platforms to find so-called "playlists" that contain links that can be used to illegally access Discovery Channels.
>
>c.) Sending takedown notices and letters to remove the infringing applications and playlists from such websites, pirate forums, app stores and social media platforms and data sharing platforms (and other online distribution platforms).
>
>NAGRA has evidence that the following URLs are infringing Discovery's rights by enabling users to illegally access the Channels, including the copyrighted materials therein.
>
>https://iptv-org.github.io/iptv/categories/documentary.m3u
>
>The sole purpose of these URLs is to grant unauthorized access to one or more of the Channels.
>
>We hereby demand that you immediately remove, disable access, or block access to the above-mentioned unauthorized and infringing URLs, and permanently cease all use of Discovery's intellectual property.
>
>This letter is an official notification under the principles of the Berne Convention ("BC"), Article 8 in the WIPO Copyright Treaty ("WTC"), Article 14 in The Electronic Commerce Directive ("ECD") and Section 512(c) of the Digital Millennium Copyright Act ("DMCA").
>
>By giving this notice and referring to the principles in the above mentioned legislations, we seek the removal of the aforementioned infringing material from your service. The purpose of this letter is to request that you immediately remove the infringing material.
>
>I have a good faith belief that use of the copyrighted materials described above as allegedly infringing is not authorized by the copyright owner, its agent, or the law.
>
>I swear, under penalty of perjury, that the information in this notification is accurate and that I am authorized to act on behalf of the owner of a right that is allegedly infringed.
>
>Please confirm within two business days of receipt of this letter that you have complied with the foregoing request.
>
>Nothing in this notification shall serve as a waiver of any rights or remedies of Discovery with respect to the alleged infringement, all of which are expressly reserved.
>
>We remain at your disposal for any query and thank you in advance for your cooperation in resolving this matter in a cooperative manner for the benefit of Discovery and the entire media and entertainment industry.
>
>Regards,
>
>[private]
>Nagravision SA  
>[private]

I'm already removing links to the channels mentioned in the letter from the repository, but I thought it was worth telling how everything works now.

**Comment by freearhey** [comment]
All links to the channels mentioned in the notice have been removed from the repository.  I also notified GitHub Support of this in my reply message.

**Comment by freearhey** [comment]
Got a response from GitHub Support:

> Thanks for letting us know you've made changes! We'll pass them along to the copyright holder and let you know if they have any other concerns.
>
>Thanks,
>
>GitHub Staff

**Comment by Daniel15** [comment]
Nagravision juts sent another DMCA message:

```
NAGRA Notice ID: DISC-20201201NEB42804  
Notice Date: December 1, 2020  
URL: https://iptv-org.github.io/iptv/countries/us.m3u  
Source: https://iptv-org.github.io/iptv/countries/us.m3u  
Domain: iptv-org.github.io

Dear Sir, Madam,

Nagravision SA (hereinafter "NAGRA") is a provider of secure solutions to protect content of the media and entertainment industry (see www.nagra.com). NAGRA has been engaged and authorized by Discovery Communications, LLC and its affiliates (collectively, "Discovery") to act on their behalf to protect and enforce Discovery’s copyrights and trademarks, whether registered or unregistered, associated with their television channels, including but not limited to Discovery,Discovery Channel,ID Investigation,ID Investigation Discovery,Discovery Family,Discovery Life,Discovery en Espanol,Familia Discovery,Discovery Science,Discovery Home and Health,Discovery Asia,Discovery Shed,Discovery Turbo Xtra,Discovery Theater,Discovery History,Discovery World,World Discovery,Discovery Civiliztion,Discovery Travel and Living,Discovery Historia,HGTV,Food Network,TLC,OWN,Oprah,Animal Planet,Trvl Channel,Motortrend,DIY Network,Cooking Channel,TVN,TVN Style,Tvn 7,TVN Turbo,TVN Fabula,TVN 24,Tvn 24 Bis,TVN Extra,TVN Warszawa,TVN Meteo,TTV,Fine Living,Living Channel,Quest,Quest Red,Focus,Frisbee,Giallo,K2,Nove,Real Time,DKiss,Asian Food Network,TV Norge,DMax,FEM,Vox,Mango,eve,foodtv,food tv,Eurosport,Eurosport 1,Eurosport 2,Fatafeat,GolfTV,Golf TV,HGTV (collectively, the "Channels"), from unauthorized distribution and streams online. This authorization includes:

a.) Monitoring of the Web, pirate forums, major App stores and social media platforms (and other online distribution platforms) to find applications used to illegally distribute its Channels.

b.) Monitoring data sharing platforms to find so-called "playlists" that contain links that can be used to illegally access Discovery Channels.

c.) Sending takedown notices and letters to remove the infringing applications and playlists from such websites, pirate forums, app stores and social media platforms and data sharing platforms (and other online distribution platforms).

NAGRA has evidence that the following URLs are infringing Discovery's rights by enabling users to illegally access the Channels, including the copyrighted materials therein.

https://iptv-org.github.io/iptv/countries/us.m3u

The sole purpose of these URLs is to grant unauthorized access to one or more of the Channels.

We hereby demand that you immediately remove, disable access, or block access to the above-mentioned unauthorized and infringing URLs, and permanently cease all use of Discovery's intellectual property.

This letter is an official notification under the principles of the Berne Convention ("BC"), Article 8 in the WIPO Copyright Treaty ("WTC"), Article 14 in The Electronic Commerce Directive ("ECD") and Section 512(c) of the Digital Millennium Copyright Act ("DMCA").

By giving this notice and referring to the principles in the above mentioned legislations, we seek the removal of the aforementioned infringing material from your service. The purpose of this letter is to request that you immediately remove the infringing material.

I have a good faith belief that use of the copyrighted materials described above as allegedly infringing is not authorized by the copyright owner, its agent, or the law.

I swear, under penalty of perjury, that the information in this notification is accurate and that I am authorized to act on behalf of the owner of a right that is allegedly infringed.

Please confirm within two business days of receipt of this letter that you have complied with the foregoing request.

Nothing in this notification shall serve as a waiver of any rights or remedies of Discovery with respect to the alleged infringement, all of which are expressly reserved.

We remain at your disposal for any query and thank you in advance for your cooperation in resolving this matter in a cooperative manner for the benefit of Discovery and the entire media and entertainment industry.

Regards,

[private]  
[private]  
Nagravision SA  
[private]
```

Is it possible there's still infringing content?

**Comment by freearhey** [comment]
@Daniel15 I just checked the file https://iptv-org.github.io/iptv/countries/us.m3u and did not find any of the channels mentioned in their list.

**Comment by freearhey** [comment]
@Daniel15 I guess the point is that this letter was prepared even before we received the first notice:

>Notice Date: December 1, 2020

**Comment by freearhey** [comment]
I just sent a response to GitHub Support pointing out that the links to these channels are no longer in the repository.

**Comment by freearhey** [comment]
Response from GitHub Support:

>Hello,
>
>Thanks for letting us know you've made the requested changes. We'll pass them along to the copyright holder and let you know if they have any other concerns.
>
>Thanks,
>GitHub Trust & Safety

**Comment by ExperiencersInternational** [comment]
@freearhey I noticed you made some changes yesterday due to this, you also need to remove Really

Comes under the same brand (Warner Media Discovery or something like that). Links for Really is broken rn anyways

**Comment by freearhey** [comment]
@ExperiencersInternational Yesterday's changes only applied to those channels that are already on the [blocklist](https://github.com/iptv-org/database/blob/master/data/blocklist.csv) and were listed in this notification: 
> Discovery,Discovery Channel,ID Investigation,ID Investigation Discovery,Discovery Family,Discovery Life,Discovery en Espanol,Familia Discovery,Discovery Science,Discovery Home and Health,Discovery Asia,Discovery Shed,Discovery Turbo Xtra,Discovery Theater,Discovery History,Discovery World,World Discovery,Discovery Civiliztion,Discovery Travel and Living,Discovery Historia,HGTV,Food Network,TLC,OWN,Oprah,Animal Planet,Trvl Channel,Motortrend,DIY Network,Cooking Channel,TVN,TVN Style,Tvn 7,TVN Turbo,TVN Fabula,TVN 24,Tvn 24 Bis,TVN Extra,TVN Warszawa,TVN Meteo,TTV,Fine Living,Living Channel,Quest,Quest Red,Focus,Frisbee,Giallo,K2,Nove,Real Time,DKiss,Asian Food Network,TV Norge,DMax,FEM,Vox,Mango,eve,foodtv,food tv,Eurosport,Eurosport 1,Eurosport 2,Fatafeat,GolfTV,Golf TV,HGTV

If some channel is not on the list, the rights holder can send us a request through this [form](https://github.com/iptv-org/iptv/issues/new?assignees=&labels=%E2%9D%8C+removal+request&template=--removal-request.yml&title=Remove%3A+) and we will add it there.
