### ISSUE TITLE
TF1, TMX, TFX and TF1 Séries Films Adaptive Links

### ISSUE THREAD

**Issue by xemles** [iptv-org/iptv#1838]
**What's wrong?**

Not really a broken stream, mostly an update for adaptive

**Country of the channel:**

France

**Channel Name:**

TF1
TMC
TFX
TF1 Séries Films

**Broken Link:**

TF1: https://tf1-hls-live-ssl.tf1.fr/tf1/1/hls/live_2328.m3u8
TMC: https://tmc-hls-live-ssl.tf1.fr/tmc/1/hls/live.m3u8
TFX: https://tfx-hls-live-ssl.tf1.fr/tfx/1/hls/live.m3u8
TF1 Séries Films: https://tsf-hls-live-ssl.tf1.fr/tsf/1/hls/live.m3u8

**Additional Information (optional):**

The other links work properly, but adaptive would make it better

**Comment by themak1985** [comment]
@xemles please submit a pull request and we will merge. Check out the **[contributing guide](https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md)** before submitting.

**Comment by xemles** [comment]
Done
