### ISSUE TITLE
Gulli

### ISSUE THREAD

**Issue by xemles** [iptv-org/iptv#1839]
**What's wrong?**

Channel out

**Country of the channel:**

France

**Channel Name:**

Gulli

**Broken Link:**

Gulli: https://gulli-hls-live.akamaized.net/gulli.isml/gulli-audio102_fre=64000-video=900000.m3u8

New link: https://d13anarbtxy8c5.cloudfront.net/6play/short/clr/gulli/sdindex.m3u8

**Additional Information (optional):**

**Comment by themak1985** [comment]
New Link Updated.
