### ISSUE TITLE
Add new playlists for region-locked streams

### ISSUE THREAD

**Issue by Daniel15** [iptv-org/iptv#1843]
For example, many Australian TV networks have official IPTV streams, however they're only viewable in Australia. I know the goal with this repository is to have freely available IPTV streams that are not region locked, however, what about having them in a separate file? In addition to the `au.m3u` file, there could be an `au-locked.m3u` (or similar name) containing all the streams that only work for Australian users. These would be filtered from the category lists (`eng.m3u`, `news.m3u`, etc).

**Comment by exodiver** [comment]
Matt Huisman maintains an excellent Australia and new Zealand playlist: 

https://www.matthuisman.nz/2017/07/australia-iptv-epg-files.html

Maybe you can take a look at that.

From what I know, freearhey do not favor adding geoblocked stream as he used an automated script to check whether the links are alive. Geoblocked streams often requires VPN or even some cases, access from dedicated host located in the country of origin, from his location, which would complicate his script by ten fold.

**Comment by themak1985** [comment]
Maintenance would be the biggest issue, instead of running a script that checks all the dead links, you would have to run a script and a VPN for each region.

**Comment by Daniel15** [comment]
That makes sense! Thanks.
