### ISSUE TITLE
SS IPTV app crushing

### ISSUE THREAD

**Issue by Astron85** [iptv-org/iptv#1847]
Excellent job!
I'm facing the following issue.
The index.country.m3u list works perfectly fine in the SS IPTV app on my LG TV but makes the SS IPTV app of my android TV box crush. More specifically, it loads the list and I'm able to play one or two channels but when I change to a third one the app becomes unresponsive and after 20 seconds it exists the app.
My android TV box is the Nokia Streaming Box 8000.
Not sure if it's an issue with the list or the box.
Please help!

**Comment by themak1985** [comment]
Hello, this issue should be handled with the developer of the app you mention. AFAIK there are no issues related to these playlists in particular making applications crash.

**Comment by Astron85** [comment]
Indeed the SS IPTV app developer has confirmed the Android TV version of the app is buggy at this point.
