### ISSUE TITLE
Czech Republic playlist - add more channels

### ISSUE THREAD

**Issue by martonky** [iptv-org/iptv#1848]
**Country of the channel:**
Czech Republic

**Channel Name:**
NOVA HD (Astra 3B (23.5°E) | 11876 MHz | H | 3/4 | 29900 | DVB-S2 / 8PSK)
NOVA 2 (Astra 3B (23.5°E) | 11973 MHz | V | 2/3 | 29900 | DVB-S2 / 8PSK)
Nova Cinema HD (Astra 3B (23.5°E) | 11876 MHz | H | 3/4 | 29900 | DVB-S2 / 8PSK)
Nova Action HD (Astra 3B (23.5°E) | 11876 MHz | H | 3/4 | 29900 | DVB-S2 / 8PSK)
Nova Gold (TV/MPEG4) | Astra 3B (23.5°E) | 11973 MHz | V | 2/3 | 29900 | DVB-S2 / 8PSK)
Prima HD (TV/MPEG4) | Astra 3B (23.5°E) | 11876 MHz | H | 3/4 | 29900 | DVB-S2 / 8PSK)
Prima PLUS HD (TV/MPEG4) | Astra 3B (23.5°E) | 12344 MHz | H | 2/3 | 29900 | DVB-S2 / 8PSK)
Prima KRIMI(TV/MPEG4) | Astra 3B (23.5°E) | 11876 MHz | H | 3/4 | 29900 | DVB-S2 / 8PSK)
Prima MAX HD(TV/MPEG4) | Astra 3B (23.5°E) | 11934 MHz | V | 3/4 | 27500 | DVB-S2 / 8PSK)
Prima COOL HD(TV/MPEG4) | Astra 3B (23.5°E) | 11876 MHz | H | 3/4 | 29900 | DVB-S2 / 8PSK)
Prima Love (TV/MPEG4) | Astra 3B (23.5°E) | 11934 MHz | V | 3/4 | 27500 | DVB-S2 / 8PSK)
Prima Zoom HD(TV/MPEG4) | Astra 3B (23.5°E) | 11934 MHz | V | 3/4 | 27500 | DVB-S2 / 8PSK)

**Channel Language:**

Czech Language

**Additional Information (optional):**

Hi guys, please, is it possible to add these channels to the Czech playlist? It will be wonderful. :)

**Comment by adahanu074** [comment]
@martonky is anyone working on this, if not can i ?

**Comment by themak1985** [comment]
> @martonky is anyone working on this, if not can i ?

@adahanu074 nobody is working on this so please do.

**Comment by freearhey** [comment]
Nova Action https://github.com/iptv-org/iptv/blob/858878c95251fd99c78792c40fcf604b2802bfec/channels/cz.m3u#L6-L7
Prima COOL https://github.com/iptv-org/iptv/blob/858878c95251fd99c78792c40fcf604b2802bfec/channels/cz.m3u#L12-L13
Prima Love https://github.com/iptv-org/iptv/blob/858878c95251fd99c78792c40fcf604b2802bfec/channels/cz.m3u#L14-L15

**Comment by freearhey** [comment]
Closed in favor #1988

**Comment by martonky** [comment]
Please, could you open this request? It is interesting for czech/slovak users.

**Comment by freearhey** [comment]
@martonky I just moved the list of all the channels to the new issue to make it easier to find. You can continue to follow them by the link: #1988
