### ISSUE TITLE
**Is your feature request related to a problem? Please describe.**

### ISSUE THREAD

**Issue by AlMalKii07** [iptv-org/iptv#1857]
**Is your feature request related to a problem? Please describe.**
We have about 100 issues submitted, mostly channel requests, some of them over a year old.

**Describe the solution you'd like**
I suggest closing channel requests that are not resolved within 30 days of the last comment or within 90 days of opening. 

**Additional context**
We would also want to update the readme.md file with this information. 

__Originally posted by @themak1985 in https://github.com/iptv-org/iptv/issues/1856__

**Comment by themak1985** [comment]
Duplicate of #1856
