### ISSUE TITLE
Saudi group channels (channel request)

### ISSUE THREAD

**Issue by mo7ebb** [iptv-org/iptv#1873]
**Country of the channel:**
Saudi Arabia 

**Channel Name:**
1- SBC 
2- Saudi 1
3- Thekrayat
4- Alekhbariya
5- alsunnah
6- alquran

**Channel Language:**
Arabic

**Additional Information (optional):**
All six channels are available for free streaming on this website

https://www.shashatcom.sa/en/channel

I just couldn't extract the m3u8 links
If someone can do it that'd be awesome

**Comment by themak1985** [comment]
Usually `https://cllive.itworkscdn.net/sbclive/token=nva=1609280006~dirs=1~hash=02633681a49bac577a029/sbc.smil/playlist.m3u8` would translate to 
`https://svs.itworkscdn.net/sbclive/sbc.smil/playlist.m3u8`
but that is not working - hopefully a developer can extract something that works.

**Comment by mo7ebb** [comment]
Anyone 👀

**Comment by LaneSh4d0w** [comment]
> Usually `https://cllive.itworkscdn.net/sbclive/token=nva=1609280006~dirs=1~hash=02633681a49bac577a029/sbc.smil/playlist.m3u8` would translate to
> `https://svs.itworkscdn.net/sbclive/sbc.smil/playlist.m3u8`
> but that is not working - hopefully a developer can extract something that works.

That's the token that's important here. Maybe there's a token verification.

**Comment by mo7ebb** [comment]
So there's no way around it?

**Comment by LaneSh4d0w** [comment]
> 
> 
> Usually `https://cllive.itworkscdn.net/sbclive/token=nva=1609280006~dirs=1~hash=02633681a49bac577a029/sbc.smil/playlist.m3u8` would translate to
> `https://svs.itworkscdn.net/sbclive/sbc.smil/playlist.m3u8`
> but that is not working - hopefully a developer can extract something that works.

It seems that they never changed their token, and that, indeed, this channel comes from their server. I think it LGTM.
All Saudi channels operated by the SBA seems to work that way.

**Comment by mo7ebb** [comment]
This link works "for now"

https://cllive.itworkscdn.net/sbclive/token=nva=1609554092~dirs=1~hash=06f7530e22c58869df5bc/sbc.smil/playlist.m3u8

**Comment by freearhey** [comment]
alsunnah https://github.com/iptv-org/iptv/blob/858878c95251fd99c78792c40fcf604b2802bfec/channels/sa.m3u#L14-L15
alquran https://github.com/iptv-org/iptv/blob/858878c95251fd99c78792c40fcf604b2802bfec/channels/sa.m3u#L8-L9

**Comment by freearhey** [comment]
Closed in favor #1989

**Comment by m5arish** [comment]
Hi, they added two sports channels can you please add them to the playlist 

https://www.aloula.sa/en/live/ksa-sports1
https://www.aloula.sa/en/live/ksa-sports2

**Comment by LaneSh4d0w** [comment]
Already added.

**Comment by m5arish** [comment]
> Already added.

The ones that are in the list currently are SD
This source provides them 1080 quality 
@Nintendocustom  successfully extracted streaming links from this website for the other channels. I hope he can do the same with those 2 new channels

**Comment by LaneSh4d0w** [comment]
https://github.com/iptv-org/iptv/blob/ef09b0545118528ee3ad288fddabd2e5057f1bf3/channels/sa.m3u#L68-L73

Those aren't SD AFAIK

**Comment by m5arish** [comment]
My bad, for some reason they’re not showing up on my iptv player.

**Comment by LaneSh4d0w** [comment]
> 
> 
> My bad, for some reason they’re not showing up on my iptv player.

Maybe redownload or refresh your player :)

**Comment by m5arish** [comment]
> > My bad, for some reason they’re not showing up on my iptv player.
> 
> Maybe redownload the playlist file or refresh your player :)

Thank you

**Comment by m5arish** [comment]
Ok I’m sorry, I refreshed and redownloaded the whole thing but still only seeing the SD ones ? 


#EXTINF:-1 tvg-id="KSASports1.sa" tvg-name="KSA Sports +1" tvg-country="SA" tvg-language="Arabic" tvg-logo="" group-title="Sports",KSA Sports +1http://45.92.69.131:8001/play/a00i#EXTINF:-1 tvg-id="KSASports1.sa" tvg-name="KSA Sports 1" tvg-country="SA" tvg-language="Arabic" tvg-logo="" group-title="Sports",KSA Sports 1http://45.92.69.131:8001/play/a00c#EXTINF:-1 tvg-id="KSASports1.sa"name="KSA Sports 2" tvg-country="SA" tvg-language="Arabic" tvg-logo="" group-title="Sports",KSA Sports 2http://45.92.69.131:8001/play/a00b

**Comment by Bakral24** [comment]
اريد رابط قناة lbci lebanon

**Comment by DevMuktary** [comment]
❤️
