### ISSUE TITLE
No Audio on CNBC Europe

### ISSUE THREAD

**Issue by theiamdude** [iptv-org/iptv#1878]
**What's wrong?**
No Audio
**Country of the channel:**
Unsorted
**Channel Name:**
CNBC
**Broken Link:**

http://ott-cdn.ucom.am/s65/index.m3u8
**Additional Information (optional):**
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="English" tvg-logo="https://i.imgur.com/53EgUZN.png" tvg-country="UNSORTED" tvg-url="" group-title="Unsorted",CNBC Europe
http://ott-cdn.ucom.am/s65/index.m3u8

**Comment by freearhey** [comment]
Closed in favor #1942
