### ISSUE TITLE
Denmark

### ISSUE THREAD

**Issue by 176-akj** [iptv-org/iptv#1881]
More channels Denmark
**Country of the channel:**

**Channel Name:**

**Channel Language:**

**Additional Information (optional):**

**Comment by exodiver** [comment]
Which channels from Denmark?

**Comment by 176-akj** [comment]
All Viasat and c- more channels
All tv3, tv4, tv5, tv6

tor. d. 31. dec. 2020 05.17 skrev Claypot_King <notifications@github.com>:

**Comment by jeune21** [comment]
Merci

**Comment by LaneSh4d0w** [comment]
Viasat and CMore are pay-to-watch channels, therefore can be seen legally only if you have got a subscription. Other ways are risky, as they can lead to DMCA Takedowns.

**Comment by tamil1809** [comment]
Good one

**Comment by freearhey** [comment]
tv4 https://github.com/iptv-org/iptv/blob/858878c95251fd99c78792c40fcf604b2802bfec/channels/se.m3u#L20-L21

**Comment by freearhey** [comment]
Closed in favor #1990 and #1951
