### ISSUE TITLE
romanian chanels 

### ISSUE THREAD

**Issue by vladalin2006** [iptv-org/iptv#1892]
**What's wrong?**

**romanian:**

**more chanels not work in special pro tv**

**Broken Link:**

**Additional Information (optional):**

**Comment by LaneSh4d0w** [comment]
To test : https://cmero-ott-live-sec.ssl.cdn.cra.cz/sow4SbuOpkrlJ7_rndQTzg==,1609687983/channels/cme-ro-voyo-news/playlist-live_lq.m3u8

**Comment by LaneSh4d0w** [comment]
Other channels need to be registered. API verification on site (for Pro TV).

**Comment by vladalin2006** [comment]
thx
