### ISSUE TITLE
Moving some channels from unsorted to "Chile"

### ISSUE THREAD

**Issue by LaneSh4d0w** [iptv-org/iptv#1893]
**Is your feature request related to a problem? Please describe.**
Not a problem, more of an organisation thing.

**Describe the solution you'd like**
Moving these channels (from unsorted.m3u) : 
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Spanish" tvg-logo="https://www.santiagotelevision.cl/imag/v1/icon/logoHeader.png" group-title="",STGO.TV (Universidad de Santiago - Chile)
https://stv.janus.cl/playlist/stream.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Spanish" tvg-logo="http://i.imgur.com/x3dL9pm.jpg" group-title="",Honorable Camara de Diputadas y Diputados (Governmiento de Chile)
https://camara.03.wl.cdnz.cl/camara19/live/playlist.m3u8

to cl.m3u8

Delete this channel : 

#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Spanish" tvg-logo="http://www.chileiptv.cl/img/logos/logo_15220774751.png" group-title="",Tendencias TV
https://v2.tustreaming.cl/tendenciastv/live1/index.m3u8 

It doesn't seem to work. (404 Not Found) on testings. (Maybe not an 24/7 stream ?)

**Comment by themak1985** [comment]
see #1894 - merged all chilean channels. will hold off on removing broken links as they seem to work sometimes.

**Comment by LaneSh4d0w** [comment]
Well done. 

I see some channels got "TuStreaming" in version 3. i'll try with Tendencias TV.
