### ISSUE TITLE
Many channels cannot be watched, they will LAG

### ISSUE THREAD

**Issue by changfranklin** [iptv-org/iptv#1909]
Dear All
Taiwan China channel has problems
Thank you for your contribution
But many Chinese channels will be delayed
Taiwan channel can't watch all
Can it be solved as soon as possible?

**Comment by LaneSh4d0w** [comment]
Hello there,

It could be many factors, to be honest. It could be server-sided, or client-sided.

What I'm saying is, the lags could be done by your connection bandwidth that isn't enough to stream channels properly.
Or it could simply be the server's bandwidth or stability that isn't good.

I do not have the time to test the channels yet, we will need more informations.

**Comment by themak1985** [comment]
Hi @changfranklin - i see what you mean, but unless an alternative link is provided, there is not much we can do.
