### ISSUE TITLE
Can't use the m3u link? It doesn't work..

### ISSUE THREAD

**Issue by cijayh** [iptv-org/iptv#1912]
**What's wrong?**
When I use the m3u link:
- https://iptv-org.github.io/iptv/index.m3u
- https://iptv-org.github.io/iptv/index.language.m3u

I get the message:
Portal connection error
Check your internet connection and portal url.

I've internet connection, that is not the problem. First the link worked for like 2 hours and then suddenly I've received that pop up message...?

**Broken Link:**
- https://iptv-org.github.io/iptv/index.m3u
- https://iptv-org.github.io/iptv/index.language.m3u

**Additional Information (optional):**
My device is: Formuler Z+

**Comment by themak1985** [comment]
Just tested both links @cijayh - no issues. No other reports either. Will monitor just in case.

**Comment by cijayh** [comment]
> Just tested both links @cijayh - no issues. No other reports either. Will monitor just in case.

The opened issue above has already been solved. Although thanks for your response.

Somehow my wifi connection wasn't working and I didn't plug any wired ethernet cable into the device. Therefore I had no internet connection whatsoever, thus the links I've been using were not available for me. I was able to use an ethernet cable and now the links are working. 

You can close the issue now. Thanks again.
