### ISSUE TITLE
Channel missing from united states

### ISSUE THREAD

**Issue by miles5600** [iptv-org/iptv#1913]
**Country of the channel:**
United states

**Channel Name:**
Disney xd and disney channel in 1440p or 1080p

**Channel Language:**
English

**Additional Information (optional):**

**Comment by themak1985** [comment]
Hello, channels are never missing. You can make requests, but you are better off if you contribute.
https://github.com/iptv-org/iptv/blob/2839a8da1a8dc4bf1845c1fb5b5a4f4c2a4327dd/.github/CONTRIBUTING.md

**Comment by miles5600** [comment]
So where can i find the disney xd en disney channel url? so i can put it into this one.

**Comment by LaneSh4d0w** [comment]
Disney XD : http://cdn.tv247.xyz/channel/disneyxd.m3u8
Disney Channel : http://cdn.tv247.xyz/channel/disney.m3u8

**Comment by miles5600** [comment]
It says error 404 not found

**Comment by LaneSh4d0w** [comment]
Site just went down indeed. Yesterday it was online.

**Comment by miles5600** [comment]
Ok i'll try to find more m3u url's

**Comment by miles5600** [comment]
I found: http://mytv.fun:8080/get.php?username=v209gunvd&password=on0k5orqk&type=m3u

**Comment by miles5600** [comment]
I found: http://mytv.fun:8080/get.php?username=v209gunvd&password=on0k5orqk&type=m3u

**Comment by freearhey** [comment]
Closed in favor #1942
