### ISSUE TITLE
viva tv no longer available?

### ISSUE THREAD

**Issue by gfwfuckoff** [iptv-org/iptv#1925]
hi all，a Russian music channel

**Comment by themak1985** [comment]
The link was dead, and the [current site that streams it](https://vk.com/video-177948463_456239215) is tokenizing the stream.

**Comment by freearhey** [comment]
Here's a new link:
https://github.com/iptv-org/iptv/blob/947179c461f4b69252a7ead47e359355ddfd3f5e/channels/ru.m3u#L456-L457
