### ISSUE TITLE
Macedonian Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1948]
List of requests for Macedonian channels from other issues:

- [ ] [1tv](https://1tv.mk/) (#501)
- [ ] [Alfa TV](https://alfa.mk/) (Алфа ТВ) (#501)
- [ ] [Kanal 5](https://kanal5.com.mk/) (Канал 5) (#501)
- [ ] [MRT 1](https://en.wikipedia.org/wiki/MRT_1) (#501)
- [ ] [MRT 2](https://en.wikipedia.org/wiki/MRT_2_(TV_channel)) (#501)
- [ ] [Televizija 24](https://24.mk/) (Телевизија 24) (#501)
- [ ] [Telma](https://telma.com.mk/) (Телма) (#501)
- [ ] [Sitel](https://sitel.com.mk/) (Сител) (#501)

**Comment by Sphinxroot** [comment]
https://webtv.a1.mk/ but no stream seem to work ... geo ?

MRT 1 (#501)
MRT 2 (#501)

note sure if token wmsAuthSign=  change everyday ...

#EXTINF:-1 ,MRT1 (http://play.mrt.com.mk/live/45
http://vod-c57.interspace.com/channel_abr/45/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9My8yOS8yMDIxIDc6Mjc6MzYgUE0maGFzaF92YWx1ZT1ON1JvTjNWUGpnWlUreUtYajFNaC9nPT0mdmFsaWRtaW51dGVzPTMwJmlkPTYwNjIyYTI4MmExN2I=

https://webtv.a1.mk/
https://vipottbpkstream.vip.hr/Content/onevip-hls/Live/Channel(MRT_1)/index.m3u8
 
#EXTINF:-1 ,MRT2 http://play.mrt.com.mk/live/42
http://vod-c57.interspace.com/channel_abr/42/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9My8yOS8yMDIxIDc6NDI6MTAgUE0maGFzaF92YWx1ZT1FNzBWNlBLdG1xamltVlpGakJRbWhRPT0mdmFsaWRtaW51dGVzPTMwJmlkPTYwNjIyZDkyNTQ4ODY=

https://webtv.a1.mk/
https://vipottbpkstream.vip.hr/Content/onevip-hls/Live/Channel(MRT_2)/index.m3u8

#EXTINF:-1 ,MP1 http://play.mrt.com.mk/live/47
http://vod-c57.interspace.com/channel_abr/47/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9My8yOS8yMDIxIDc6NDU6MjYgUE0maGFzaF92YWx1ZT0vZDRHdlZOb0Q4OWN6T1RkOHk5RlRBPT0mdmFsaWRtaW51dGVzPTMwJmlkPTYwNjIyZTU2ZDRkYmI=
#EXTINF:-1 ,MP2 http://play.mrt.com.mk/live/48
http://vod-c57.interspace.com/channel_abr/48/receiver/48_p2/chunks.m3u8?nimblesessionid=2852852&wmsAuthSign=c2VydmVyX3RpbWU9My8yOS8yMDIxIDc6MzY6NTQgUE0maGFzaF92YWx1ZT1FZyt4alMyV3ZWcktrTUovTGJHaFZnPT0mdmFsaWRtaW51dGVzPTMwJmlkPTYwNjIyYzU2MDQwMzk=

#EXTINF:-1 ,MP3 http://play.mrt.com.mk/live/49
http://vod-c57.interspace.com/channel_abr/49/receiver/49_p2/chunks.m3u8?nimblesessionid=2852914&wmsAuthSign=c2VydmVyX3RpbWU9My8yOS8yMDIxIDc6NDY6NTUgUE0maGFzaF92YWx1ZT1weGpGTHVucjJORUpYZ2xqS0R6K0NnPT0mdmFsaWRtaW51dGVzPTMwJmlkPTYwNjIyZWFmNzQyYzQ=
 
#EXTINF:-1 ,MRT Assembly Kanal http://play.mrt.com.mk/live/44
http://vod-c57.interspace.com/channel_abr/44/receiver/44_p4/chunks.m3u8?nimblesessionid=2852893&wmsAuthSign=c2VydmVyX3RpbWU9My8yOS8yMDIxIDc6NDM6MjMgUE0maGFzaF92YWx1ZT1xaiszb0JWTzFra05IaW84QW1ZTndnPT0mdmFsaWRtaW51dGVzPTMwJmlkPTYwNjIyZGRiZTYwY2Y=

#EXTINF:-1 ,MPT sat 2 http://play.mrt.com.mk/live/46
http://vod-c57.interspace.com/channel_abr/46/receiver/46_p4/chunks.m3u8?nimblesessionid=2852899&wmsAuthSign=c2VydmVyX3RpbWU9My8yOS8yMDIxIDc6NDQ6MzEgUE0maGFzaF92YWx1ZT1oeXIrdkl6WTZnT3RRWGF5ZFlRc2JRPT0mdmFsaWRtaW51dGVzPTMwJmlkPTYwNjIyZTFmODYyMWM=

#EXTINF:-1 ,MPT sat http://play.mrt.com.mk/live/50
http://vod-c57.interspace.com/channel_abr/50/receiver/50_p2/chunks.m3u8?nimblesessionid=2852927&wmsAuthSign=c2VydmVyX3RpbWU9My8yOS8yMDIxIDc6NDk6MDQgUE0maGFzaF92YWx1ZT1xeG1QK05mbUFnL0NyK0xOZ1RuMUdnPT0mdmFsaWRtaW51dGVzPTMwJmlkPTYwNjIyZjMwZWRmNmM=

#EXTINF:-1 ,MPT http://play.mrt.com.mk/live/43
http://vod-c57.interspace.com/channel_abr/43/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9My8yOS8yMDIxIDc6NDc6NDYgUE0maGFzaF92YWx1ZT00WlA0cC96bWVzNm5iU1QyMGV4U25RPT0mdmFsaWRtaW51dGVzPTMwJmlkPTYwNjIyZWUyYTBjZjg=


 
#EXTINF:-1 ,Telma (Телма) (#501) https://telma.com.mk/
https://webtv.a1.mk/
https://vipottbpkstream.vip.hr/Content/onevip-hls/Live/Channel(Telma)/index.m3u8

Sitel (Сител) (#501) https://sitel.com.mk/ 
https://webtv.a1.mk/
https://vipottbpkstream.vip.hr/Content/onevip-hls/Live/Channel(Sitel)/index.m3u8 
 
#EXTINF:-1 ,Kanal 5 (Канал 5) (#501) https://kanal5.com.mk/vozivo https://webtv.a1.mk/
https://vipottbpkstream.vip.hr/Content/onevip-hls/Live/Channel(Kanal_5)/index.m3u8


#EXTINF:-1 ,Televizija 24 (Телевизија 24) (#501) https://24.mk/zivo from source code but not working
http://89.205.123.195/Televizija24/playlist.m3u8

https://webtv.a1.mk/
https://vipottbpkstream.vip.hr/Content/onevip-hls/Live/Channel(TV_24)/index.m3u8
 
1tv (#501) https://1tv.mk/  live.1tv.mk page dont open 
 
#EXTINF:-1 ,Alfa TV (Алфа ТВ) (#501) https://alfa.mk/ live point to https://webtv.a1.mk/alfa
https://vipottbpkstream.vip.hr/Content/onevip-hls/Live/Channel(Alfa)/index.m3u8
