### ISSUE TITLE
Hungarian Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1952]
List of requests for Hungarian channels from other issues:

- [ ] DoQ (#718)
- [ ] Film Café Romania (#762)
- [ ] Minimax Romania (#762)
- [ ] Ozone TV (#718)
- [ ] Spektrum (#718)
- [ ] Spektrum Home (#718)

**Comment by exyanis** [comment]
HI ADD THIS PLAYLIST

#EXTM3U
#EXTINF:-1, M1
https://c201-node62-cdn.connectmedia.hu/1100/498232034cfcb769f7449dc2a732bab8/6068233f/index.m3u8?v=5i
#EXTINF:-1, M2
https://c202-node62-cdn.connectmedia.hu/1101/086e18451bee782e0d97d98e8d6fbf71/60682453/index.m3u8?v=5i
#EXTINF:-1, M3
https://stream9.nava.hu/m3_live_bdrm/_definst_/smil:m3_1080p_loop_nodrm.smil/chunklist_w72397576_b881072_slhun.m3u8?lb=b4bp7xeKAKovH1uDWU5XusWC%252FSZexs%252BJNLmxYvSb34kGup6SGRTTm5UkNNjfC62mmvYbuEqrt04E%250D%250AExer5ZNS%252FWN6JyMpY6GiuOU2osRulnM%252BgNsTWVD8z%252BLJt4imqAka%250D%250A&platform=web_embed&sessid=Z4gLTQezzXGgWvNkiypb5PkmR64U1aoH3lFII14l3Mp2dZ5OtLoKQQY7XOn943ns&type=m3u8
#EXTINF:-1, M5
https://c402-node61-cdn.connectmedia.hu/1105/9aea73a9363ac1a20f6446228b4118be/6068253b/index.m3u8?v=5i
#EXTINF:-1, DUNA
https://c202-node62-cdn.connectmedia.hu/1102/90b26d3dc4201bf14f003d5a82e6e2da/60682572/index.m3u8?v=5i
#EXTINF:-1, DUNA WORLD
https://c402-node62-cdn.connectmedia.hu/1103/a14af1f4f78fbf4e5ab63e9d17f5466a/6068259f/index.m3u8?v=5i
#EXTINF:-1, FEM 3
https://streaming.mytvback.com/stream/Nc8b6c6tUH4gh3GdRR-zFw/1617462698/channel016/stream.m3u8
#EXTINF:-1, RTL KLUB
https://stream.y5.hu/stream/stream_rtlklub/hls0/stream.m3u8
#EXTINF:-1, RTL KLUB HD
https://stream.y5.hu/stream/stream_rtlklub/hls1/stream.m3u8
#EXTINF:-1, RTL II
https://stream.y5.hu/stream/stream_rtl2/hls0/stream.m3u8
#EXTINF:-1, RTL II HD
https://stream.y5.hu/stream/stream_rtl2/hls1/stream.m3u8
#EXTINF:-1, COOL TV
https://stream.y5.hu/stream/stream_cool/hls0/stream.m3u8
#EXTINF:-1, COOL TV HD
https://stream.y5.hu/stream/stream_cool/hls1/stream.m3u8
#EXTINF:-1, RTL GOLD
https://stream.y5.hu/stream/stream_rtlgold/stream.m3u8
#EXTINF:-1, RTL +
https://stream.y5.hu/stream/stream_rtlp/stream.m3u8
#EXTINF:-1, RTL +
https://stream.y5.hu/stream/stream_filmp/hls0/stream.m3u8
#EXTINF:-1, RTL + HD
https://stream.y5.hu/stream/stream_filmp/hls1/stream.m3u8
#EXTINF:-1, FILM +
https://stream.y5.hu/stream/stream_filmp/hls0/stream.m3u8
#EXTINF:-1, FILM + HD
https://stream.y5.hu/stream/stream_filmp/hls1/stream.m3u8
#EXTINF:-1, SOROZAT+
https://stream.y5.hu/stream/stream_sorozatp/stream.m3u8
#EXTINF:-1, ATV
https://stream.atv.hu/atvlive/atvstream_2_aac/playlist.m3u8
#EXTINF:-1, HIR TV
https://streamjump2.mediaworld.gq/hirtv_delayed/00QMyEzMwEzM.m3u8
#EXTINF:-1, IZAURA TV
https://streaming.mytvback.com/stream/1aMW5tqyOFpH3swBdowx9Q/1617462678/channel040/stream-br1872000.m3u8
#EXTINF:-1, LIFE TV
https://streaming.mytvback.com/stream/2WVTzaaqRtQ3cZ02Qd7rPA/1617462690/channel043/stream-br572000.m3u8

**Comment by freearhey** [comment]
@exyanis Added via https://github.com/iptv-org/iptv/commit/cc2084b06f7dfe692b82eb5bfd8d114bf98cabdb and https://github.com/iptv-org/iptv/commit/d89447dc79e18740996320b5dd8cfdb458fda14e

**Comment by sniper8952** [comment]
Hi, I'm looking to a Hungary list with RTL Klub and ATV. Can someone add this to the list?

Thank You!
