### ISSUE TITLE
Tajik Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1964]
List of requests for Tajik channels from other issues:

- [ ] Badakhshon (#1229)
- [ ] Dushanbe HD (#1229)
- [ ] Jahonnamo (#1229)
- [ ] Khatlon (#1229)
- [ ] TMT (#1229)
- [ ] TV Bahoriston (#1229)
- [ ] TV Kulob (#1229)
- [ ] TV Safina (#1229)
- [ ] TV Sinamo (#1229)
- [ ] TV Sugd (#1229)

**Comment by MH140000** [comment]
hi. can you get m3u8 url from this website?
https://mediabay.tv/tv/110/Safina
