### ISSUE TITLE
Brazilian Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1968]
List of requests for Brazilian channels from other issues:

- [x] Rede Globo (#1337) (added via https://github.com/iptv-org/iptv/commit/5597503c661f1e04daf2c86064c1f673cb0828bf)
- [x] Rede Vida (#2577)

**Comment by free-the-web** [comment]
REDE GLOBO
               http://live.video.globo.com/h/1402196682759012345678915746027599876543210hM4EA1neMoQoIiUyVn1TNg/k/app/a/A/u/anyone/d/s/hls-globo-rj/playlist.m3u8

**Comment by freearhey** [comment]
@free-the-web Thanks.

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-logo="" group-title="",Trace Urban Inter
https://mj1b2xsspj.singularcdn.net.br/trace/urbanint/6/prog_index.m3u8
#EXTINF:-1 tvg-logo="" group-title="",Trace Sport Stars
https://mj1b2xsspj.singularcdn.net.br/trace/tss/6/prog_index.m3u8
#EXTINF:-1 tvg-logo="" group-title="",Trace Brazuca
https://mj1b2xsspj.singularcdn.net.br/trace/brazuca/6/prog_index.m3u8
#EXTINF:-1 tvg-logo="" group-title="",Trace Latina
https://mj1b2xsspj.singularcdn.net.br/trace/latina/6/prog_index.m3u8
#EXTINF:-1 tvg-logo="" group-title="",Trace toca
https://mj1b2xsspj.singularcdn.net.br/trace/toca/6/prog_index.m3u8

#EXTINF:-1 group-title="Variedade e Músicas" tvg-logo="http://i.imgur.com/U6Rgjqs.png",MTV
http://ug1upc1hgb.singularcdn.net.br/MTV_BR_HD/tracks-v2a1/mono.m3u8
#EXTINF:-1 group-title="Variedade e Músicas" tvg-logo="http://i.imgur.com/U6Rgjqs.png",MTV HD
http://ug1upc1hgb.singularcdn.net.br/MTV_BR_HD/tracks-v1a1/mono.m3u8


#EXTINF:-1 group-title="Infantil" tvg-logo="http://i.imgur.com/ZjLSLiY.png",Nickelodeon
http://ug1upc1hgb.singularcdn.net.br/NICK_BR_HD/tracks-v2a1/mono.m3u8
#EXTINF:-1 group-title="Infantil" tvg-logo="http://i.imgur.com/ZjLSLiY.png",Nickelodeon HD
http://ug1upc1hgb.singularcdn.net.br/NICK_BR_HD/tracks-v1a1/mono.m3u8
#EXTINF:-1 group-title="Infantil" tvg-logo="http://i.imgur.com/6vVmJJf.png",Nick Jr.
http://ug1upc1hgb.singularcdn.net.br/NICK_JR_BR_HD/tracks-v2a1/mono.m3u8
#EXTINF:-1 group-title="Infantil" tvg-logo="http://i.imgur.com/6vVmJJf.png",Nick Jr. HD
http://ug1upc1hgb.singularcdn.net.br/NICK_JR_BR_HD/tracks-v1a1/mono.m3u8
#EXTINF:-1 group-title="Filmes e Séries" tvg-logo="http://i.imgur.com/ZekUX7A.png",Comedy Central
http://ug1upc1hgb.singularcdn.net.br/CCLB_HD/tracks-v2a1/mono.m3u8
#EXTINF:-1 group-title="Filmes e Séries" tvg-logo="http://i.imgur.com/ZekUX7A.png",Comedy Central HD
http://ug1upc1hgb.singularcdn.net.br/CCLB_HD/tracks-v1a1/mono.m3u8


#EXTINF:-1 tvg-logo="https://upload.wikimedia.org/wikipedia/pt/d/dc/Logotipo_TNT_Sports.png" group-title="DEPORTES LATINOS", BR | TNT SPORTS 2
https://glxlmn026c.singularcdn.net.br/playout_02/playlist-720p.m3u8
#EXTINF:-1 tvg-logo="https://upload.wikimedia.org/wikipedia/pt/d/dc/Logotipo_TNT_Sports.png" group-title="DEPORTES LATINOS", BR | TNT SPORTS 3
https://glxlmn026c.singularcdn.net.br/playout_03/playlist-720p.m3u8
#EXTINF:-1 tvg-logo="https://upload.wikimedia.org/wikipedia/pt/d/dc/Logotipo_TNT_Sports.png" group-title="DEPORTES LATINOS", BR | TNT SPORTS 4
https://glxlmn026c.singularcdn.net.br/playout_04/playlist-720p.m3u8
#EXTINF:-1 tvg-logo="https://upload.wikimedia.org/wikipedia/pt/d/dc/Logotipo_TNT_Sports.png" group-title="DEPORTES LATINOS", BR | TNT SPORTS 5
https://glxlmn026c.singularcdn.net.br/playout_05/playlist-720p.m3u8

**Comment by freearhey** [comment]
@Sphinxroot Thanks for your help! All the links have been added to the playlist.

**Comment by LaneSh4d0w** [comment]
> 
> 
> #EXTINF:-1 tvg-logo="" group-title="",Trace Urban Inter
> https://mj1b2xsspj.singularcdn.net.br/trace/urbanint/6/prog_index.m3u8
> #EXTINF:-1 tvg-logo="" group-title="",Trace Sport Stars
> https://mj1b2xsspj.singularcdn.net.br/trace/tss/6/prog_index.m3u8
> #EXTINF:-1 tvg-logo="" group-title="",Trace Brazuca
> https://mj1b2xsspj.singularcdn.net.br/trace/brazuca/6/prog_index.m3u8
> #EXTINF:-1 tvg-logo="" group-title="",Trace Latina
> https://mj1b2xsspj.singularcdn.net.br/trace/latina/6/prog_index.m3u8
> #EXTINF:-1 tvg-logo="" group-title="",Trace toca
> https://mj1b2xsspj.singularcdn.net.br/trace/toca/6/prog_index.m3u8
> 
> #EXTINF:-1 group-title="Variedade e Músicas" tvg-logo="[http://i.imgur.com/U6Rgjqs.png",MTV](http://i.imgur.com/U6Rgjqs.png%22,MTV)
> http://ug1upc1hgb.singularcdn.net.br/MTV_BR_HD/tracks-v2a1/mono.m3u8
> #EXTINF:-1 group-title="Variedade e Músicas" tvg-logo="[http://i.imgur.com/U6Rgjqs.png",MTV](http://i.imgur.com/U6Rgjqs.png%22,MTV) HD
> http://ug1upc1hgb.singularcdn.net.br/MTV_BR_HD/tracks-v1a1/mono.m3u8
> 
> #EXTINF:-1 group-title="Infantil" tvg-logo="[http://i.imgur.com/ZjLSLiY.png",Nickelodeon](http://i.imgur.com/ZjLSLiY.png%22,Nickelodeon)
> http://ug1upc1hgb.singularcdn.net.br/NICK_BR_HD/tracks-v2a1/mono.m3u8
> #EXTINF:-1 group-title="Infantil" tvg-logo="[http://i.imgur.com/ZjLSLiY.png",Nickelodeon](http://i.imgur.com/ZjLSLiY.png%22,Nickelodeon) HD
> http://ug1upc1hgb.singularcdn.net.br/NICK_BR_HD/tracks-v1a1/mono.m3u8
> #EXTINF:-1 group-title="Infantil" tvg-logo="[http://i.imgur.com/6vVmJJf.png",Nick](http://i.imgur.com/6vVmJJf.png%22,Nick) Jr.
> http://ug1upc1hgb.singularcdn.net.br/NICK_JR_BR_HD/tracks-v2a1/mono.m3u8
> #EXTINF:-1 group-title="Infantil" tvg-logo="[http://i.imgur.com/6vVmJJf.png",Nick](http://i.imgur.com/6vVmJJf.png%22,Nick) Jr. HD
> http://ug1upc1hgb.singularcdn.net.br/NICK_JR_BR_HD/tracks-v1a1/mono.m3u8
> #EXTINF:-1 group-title="Filmes e Séries" tvg-logo="[http://i.imgur.com/ZekUX7A.png",Comedy](http://i.imgur.com/ZekUX7A.png%22,Comedy) Central
> http://ug1upc1hgb.singularcdn.net.br/CCLB_HD/tracks-v2a1/mono.m3u8
> #EXTINF:-1 group-title="Filmes e Séries" tvg-logo="[http://i.imgur.com/ZekUX7A.png",Comedy](http://i.imgur.com/ZekUX7A.png%22,Comedy) Central HD
> http://ug1upc1hgb.singularcdn.net.br/CCLB_HD/tracks-v1a1/mono.m3u8
> 
> #EXTINF:-1 tvg-logo="https://upload.wikimedia.org/wikipedia/pt/d/dc/Logotipo_TNT_Sports.png" group-title="DEPORTES LATINOS", BR | TNT SPORTS 2
> https://glxlmn026c.singularcdn.net.br/playout_02/playlist-720p.m3u8
> #EXTINF:-1 tvg-logo="https://upload.wikimedia.org/wikipedia/pt/d/dc/Logotipo_TNT_Sports.png" group-title="DEPORTES LATINOS", BR | TNT SPORTS 3
> https://glxlmn026c.singularcdn.net.br/playout_03/playlist-720p.m3u8
> #EXTINF:-1 tvg-logo="https://upload.wikimedia.org/wikipedia/pt/d/dc/Logotipo_TNT_Sports.png" group-title="DEPORTES LATINOS", BR | TNT SPORTS 4
> https://glxlmn026c.singularcdn.net.br/playout_04/playlist-720p.m3u8
> #EXTINF:-1 tvg-logo="https://upload.wikimedia.org/wikipedia/pt/d/dc/Logotipo_TNT_Sports.png" group-title="DEPORTES LATINOS", BR | TNT SPORTS 5
> https://glxlmn026c.singularcdn.net.br/playout_05/playlist-720p.m3u8

If you take off the "-720p" it becomes a working adaptive playlist

https://glxlmn026c.singularcdn.net.br/playout_01/playlist.m3u8 this one also works.

**Comment by ygorlv** [comment]
#EXTINF:-1 tvg-language="Portuguese" tvg-logo="https://upload.wikimedia.org/wikipedia/pt/1/1c/Logotipo_da_TV_Brasil.png" group-title="General",TV Brasil
https://edge-df-01.eduplay.rnp.br/media/ocp(r(iRGrcw)t(AAAAAAAAAAA)p(d(Dxg)k(Qdk)m(naXbjbTlDxrHlrlxKSNzig)n(a(3LDBWxJLACwHVOavx5cO4BC5lA2ZDpPC)s(HrY)'a(12ztgSdgu3rQqz6xH52ZjVZa)s(Pm8)))s(t(aTo)b(PTsuEXhXAScNjp6w9ssG70foQQQiZk9_8m0vsjgLJ_yzxGPuj8i57PEDMMA4cmTNsKda2B5oX-EEErouZ1HFyuG_AaUF86vlMJtsMkooySBOlQbVM33PgsYPQdea2BJafjjc-BWtPRlStfmQ939PXcd844pid2JY82J6JDM)'t(S2o)b(WaBWYarWoWCInKe38WSze3Q_-kYcqZf8MZQ)))/live_720_index.m3u8
#EXTINF:-1 tvg-language="Education" tvg-logo="https://pt.wikipedia.org/wiki/Ficheiro:TV_Escola.png" group-title="Education",TV Escola
https://edge-df-01.eduplay.rnp.br/media/ocp(r(iRGrcw)t(AAAAAAAAAAA)p(d(Dxg)k(Qdk)m(q-QQ9tbM1LVeQsn3AkKguw)n(a(3LDBWxJLACwHVOavx5cO4BC5lA2ZDpPC)s(HrY)'a(12ztgSdgu3rQqz6xH52ZjVZa)s(Pm8)))s(t(aTo)b(PTsuEXhXAScNjp6w9ssG70foQQQiZk9_8m0vsjgLJ_yzxGPuj8i57PEDMMA4cmTNsKda2B5oX-EEErouZ1HFyun9A4sJuqq-ZZ5UGE5w4A5Lmy-yARb69ZFORunwlRZIfiLswT_MExl8qv6So0l5XeVL4-xmSFY_zRNOMnli)'t(aik)b(-Btgu9O9bZDM7fy6b7p0dDTzGRSrl_Avj_oC)))/live_540_index.m3u8
#EXTINF:-1 tvg-language="Portuguese" tvg-logo="https://www.canalsaude.fiocruz.br/tools/images/logo-top.jpg" group-title="Science",Canal Saude
https://edge-sp-01.eduplay.rnp.br/media/ocp(r(iRGrcw)t(AAAAAAAAAAA)p(d(Dxg)k(Qdk)m(tLPEKTHspjtviFFScW-H0g)n(a(3LDBWxJLACwHVOavx5cO4BC5lA2ZDpPC)s(HrY)'a(12ztgSd3rXrQqz6xH52ZjVZa)s(Pm8)))s(t(aTo)b(PTsuEXhXAScNjp6w9ssG70foQQQiZk9_8m0vsjgLJ_yzxGPuj8i57PEDMMA4cmTNsKda2B5oX-EEErouZ1HFyun9AP0Ot72QCtp6GCxm4RkZsAfFZFrgq8ZOau7opR4sCTfu-B7lFTd4g8--0WJ_UddF1u5fW20dgA)'t(IS8)b(BTIuDlz4X2Smj64pkt2l8fxpviQqdb8)))/live_540_index.m3u8
#EXTINF:-1 tvg-language="Portuguese" tvg-logo="https://www.upf.br/Assets/img/logo.png" group-title="Local",UPFTV
https://edge-df-01.eduplay.rnp.br/media/ocp(r(iRGrcw)t(AAAAAAAAAAA)p(d(Dxg)k(Qdk)m(Zpw89V7JSRj33uzTBmvflA)n(a(3LDBWxJLACwHVOavx5cO4BC5lA2ZDpPC)s(HrY)'a(12ztgSdgu3rQqz6xH52ZjVZa)s(Pm8)))s(t(aTo)b(PTsuEXhXAScNjp6w9ssG70foQQQiZk9_8m0vsjgLJ_yzxGPuj8i57PEDMMA4cmTNsKda2B5oX-EEErouZ1HFyvnyAaUn8qvlMJtsMkooySBOlQbVM33PgsYPQdea2BUvej3szg6oEmxOu__mykl-Ud831Jp-clI-5BB-JDM)'t(S2o)b(WaBWYarWoWCInKe38WSze3Q_-kAUqZ79MZQ)))/live_768_index.m3u8
#EXTINF:-1 tvg-language="Portuguese" tvg-logo="https://www.upf.br/Assets/img/logo.png" group-title="Science",TV UFOP
https://edge-df-01.eduplay.rnp.br/media/ocp(r(iRGrcw)t(AAAAAAAAAAA)p(d(Dxg)k(Qdk)m(6pbmcjLXNoerDLdAhoXBxw)n(a(3LDBWxJLACwHVOavx5cO4BC5lA2ZDpPC)s(HrY)'a(12ztgSdgu3rQqz6xH52ZjVZa)s(Pm8)))s(t(aTo)b(PTsuEXhXAScNjp6w9ssG70foQQQiZk9_8m0vsjgLJ_yzxGPuj8i57PEDMMA4cmTNsKda2B5oX-EEErouZ1HFyuXyAosvuqvlMJtsMkooySBOlQbVM33PgsYPQdea2CdwV3jCwh3bEWxgkPO8qmBPQtt_5bUEV1Mi_2t1AjM)'t(S2o)b(WaBWYarWoWCInKe38WSze3Q_-kcUr5z4MZQ)))/live_720_index.m3u8
#EXTINF:-1 tvg-language="Portuguese" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/b/b9/UFOP_logo.gif" group-title="Science",TV UFOP
https://edge-df-01.eduplay.rnp.br/media/ocp(r(iRGrcw)t(AAAAAAAAAAA)p(d(Dxg)k(Qdk)m(6pbmcjLXNoerDLdAhoXBxw)n(a(3LDBWxJLACwHVOavx5cO4BC5lA2ZDpPC)s(HrY)'a(12ztgSdgu3rQqz6xH52ZjVZa)s(Pm8)))s(t(aTo)b(PTsuEXhXAScNjp6w9ssG70foQQQiZk9_8m0vsjgLJ_yzxGPuj8i57PEDMMA4cmTNsKda2B5oX-EEErouZ1HFyuXyAosvuqvlMJtsMkooySBOlQbVM33PgsYPQdea2CdwV3jCwh3bEWxgkPO8qmBPQtt_5bUEV1Mi_2t1AjM)'t(S2o)b(WaBWYarWoWCInKe38WSze3Q_-kcUr5z4MZQ)))/live_720_index.m3u8 
#EXTINF:-1 tvg-language="Portuguese" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Webysther_20160322_-_Logo_UnB_(sem_texto).svg/200px-Webysther_20160322_-_Logo_UnB_(sem_texto).svg.png" group-title="Science",UNBTV
https://edge-go-01.eduplay.rnp.br/media/ocp(r(iRGrcw)t(AAAAAAAAAAA)p(d(Dxg)k(Qdk)m(XavC51HboPDZJtji_e3szw)n(a(3LDBWxJLACwHVOavx5cO4BC5lA2ZDpPC)s(HrY)'a(12ztgSdjsnrQqz6xH52ZjVZa)s(Pm8)))s(t(aTo)b(PTsuEXhXAScNjp6w9ssG70foQQQiZk9_8m0vsjgLJ_yzxGPuj8i57PEDMMA4cmTNsKda2B5oX-EEErouZ1HFyuX9AbUB8KvlMJtsMkooySBOlQbVM33PgsYPQdea2BJ0ehzbwQ39JhRwi_LnomRVQOY02rJ-d2IH3hF-JDM)'t(S2o)b(WaBWYarWoWCInKe38WSze3Q_-kcVqJj_MZQ)))/live_1080_index.m3u8
#EXTINF:-1 tvg-language="Portuguese" tvg-logo="https://rd1.com.br/wp-content/uploads/2015/11/tv_aparecida.png" group-title="Religious",TV Aparecida
https://cdn.jmvstream.com/w/LVW-9716/LVW9716_HbtQtezcaw/playlist.m3u8
#EXTINF:-1 tvg-language="Portuguese" tvg-logo="https://rd1.com.br/wp-content/uploads/2019/12/20191220-tv-camara-e1576849495711.jpg" group-title="Legislative",TV Camara de Sao Paulo
https://cdn.jmvstream.com/w/LVW-8711/ngrp:LVW8711_tG0F3TEBDL_all/playlist.m3u8
#EXTINF:-1 tvg-language="Portuguese" tvg-logo="https://upload.wikimedia.org/wikipedia/pt/thumb/8/88/Logotipo_da_TV_Cidade_de_S%C3%A3o_Paulo.png/200px-Logotipo_da_TV_Cidade_de_S%C3%A3o_Paulo.png" group-title="Local",TV Cidade de Sao Paulo 
https://cast.cdnseguro.com:19360/8012/8012.m3u8
#EXTINF:-1 tvg-language="Portuguese,English" tvg-logo="https://d3kle7qwymxpcy.cloudfront.net/images/broadcasts/89/c1/17872/c300.png" group-title="Music",KISS TV
https://cast.cdnseguro.com:19360/8094/8094.m3u8
#EXTINF:-1 tvg-language="Portuguese" tvg-logo="https://www.rs21.com.br/wp-content/uploads/2016/01/logo-rede-seculo-21.jpg" group-title="Religious",Rede Seculo 21 
https://dhxt2zok2aqcr.cloudfront.net/live/rs21_360p614k/index.m3u8
#EXTINF:-1 tvg-language="Portuguese" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Loading_TV.svg/640px-Loading_TV.svg.png" group-title="Entertainment",Loading
https://akamai.gcp.br.cdn.booyah.live/hls/151073/34850987_1080.m3u8
#EXTINF:-1 tvg-language="Portuguese" tvg-logo="https://upload.wikimedia.org/wikipedia/pt/6/63/Logo-istv.png" group-title="Local",ISTV
https://cdn.jmvstream.com/w/LVW-9883/LVW9883_lFcfKysrHF/chunklist.m3u8
#EXTINF:-1 tvg-language="Portuguese" tvg-logo="http://tvunisantos.com.br/upload/612Logo%20TV%20Unisantos.JPG" group-title="Local",TV UniSantos
http://live.cdn.upx.com/7550/myStream.sdp/chunklist.m3u8?163fa4bccb4211dc8419e8cbdae3fba5
#EXTINF:-1 tvg-language="Portuguese" tvg-logo="https://logodownload.org/wp-content/uploads/2017/11/tv-cultura-logo-1.png" group-title="General",TV Cultura (720p)
https://stream-04.nyc.dailymotion.com/sec(RiWEtJG0nU_F5iuiUOWAlzg2xfgQxBpfJDYQdk6JdCk)/dm/3/x7wur7g/s/live-3.m3u8
#EXTINF:-1 tvg-language="Portuguese" tvg-logo="https://logodownload.org/wp-content/uploads/2017/11/tv-cultura-logo-1.png" group-title="General",TV Cultura (480p)
https://stream-04.nyc.dailymotion.com/sec(RiWEtJG0nU_F5iuiUOWAlzg2xfgQxBpfJDYQdk6JdCk)/dm/3/x7wur7g/s/live-2.m3u8
#EXTINF:-1 tvg-language="Portuguese" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/6/66/TVT.png" group-title="General",TVT
https://stream-01.nyc.dailymotion.com/sec(hq_e0q5VHX_FvDCk_Uz4G_eDoHni7jkWNR7bbLZDrv8)/dm/3/x6ph7x7/s/live-3.m3u8

**Comment by ygorlv** [comment]
#2577 RedeVida better image link https://cvd1.cds.ebtcvd.net/live-redevida/smil:redevida.smil/playlist.m3u8

**Comment by ygorlv** [comment]
#EXTINF:-1 tvg-country="BR" tvg-language="Portuguese" tvg-logo="https://upload.wikimedia.org/wikipedia/pt/2/22/Logotipo_da_NGT.png" group-ctitle="General",NGT
https://cdn.jmvstream.com/w/AVJ-9644/playlist/chunklist.m3u8

**Comment by Dum4G** [comment]
Cultura
https://origin-02.nxplay.com.br/TV_CULTURA_HD_PFZ/index.m3u8
Parana?
http://200.189.113.201/hls/tve.m3u8
