### ISSUE TITLE
Israeli Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1969]
List of requests for Israeli channels from other issues:

- [x] Keshet 12 (#1337, #1653) (added via https://github.com/iptv-org/iptv/commit/a618948ddf4bcbc6acadfa9acce8da56a913dc12)

**Comment by trancer1994** [comment]
The URL I was able to get for Keshet 12 from Israel is
https://keshethlslive-i.akamaihd.net/hls/live/512033/CH2LIVE_HIGH/index.m3u8?hdnea=st%3D1611065753%7Eexp%3D1611066653%7Eacl%3D%2F*%7Ehmac%3D200d347ce698dc013094bd5d1d16e2351b03e0812d1b222ba2f4e2d072316078

I'm not sure if it expires or not though.

**Comment by Nintendocustom** [comment]
doesn't expire: https://iptv--iptv.repl.co/Hebrew/keshet_12

**Comment by freearhey** [comment]
@Nintendocustom Thank you! Added.
