### ISSUE TITLE
Ugandan Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1971]
List of requests for Ugandan channels from other issues:

- [x] NBS TV (#1352) (added via https://github.com/iptv-org/iptv/commit/ddf7bd83527c8bcaaad5e5b36a1bd8b04d9031d3)

**Comment by trancer1994** [comment]
The only one I found is: 

NBS TV
https://readymedia.moderntv.cloud:8092/distribute/readymedia/NBSTV_stream_qb/5-20-hls/live.m3u8

This is so fun!

**Comment by freearhey** [comment]
@trancer1994 Added.
