### ISSUE TITLE
Lithuanian Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1974]
List of requests for Lithuanian channels from other issues:

- [x] LRT Lituanica (LTV) (#1481) (added via https://github.com/iptv-org/iptv/commit/fc57b7ced6bb493c37fe421816a49027ac132a16)

**Comment by trancer1994** [comment]
LRT Lituanica
https://lituanica-dvr.lrt.lt/lrt-ndvr/hls/lituanica_720p/index.m3u8

**Comment by freearhey** [comment]
@trancer1994 Added.

**Comment by ifrale** [comment]
Please add LRT HD - https://www.lrt.lt/mediateka/tiesiogiai/lrt-televizija

**Comment by trancer1994** [comment]
LRT HD
Seems to be tokenised but the stream I was able to find was
https://lrthd.lrt.lt/secure/lrt_hd/hls/G6NA4iY3yWJV5reiGbEYOA/1616202370/lrt_televizija.m3u8
