### ISSUE TITLE
International Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1975]
List of requests for International channels from other issues:

- [ ] DJing Hot Hot Hot (#1486)

**Comment by LaneSh4d0w** [comment]
They kinda shut down all their links I suppose. All links i'm testing are all redirecting to the same 17 second video advertising this channel.

**Comment by themak1985** [comment]
This channel no longer exists. They have changed their business model AFAIK. I think its safe to close.
