### ISSUE TITLE
Russian Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1985]
List of requests for Russian channels from other issues:

- [x] Match TV (Матч ТВ) (#1759) (added via https://github.com/iptv-org/iptv/commit/9ffd6e48c670b515f5950248e5f2f350fe8b264c)
- [x] Setanta Sports (Сетанта Спорт) (#1759)

**Comment by LaneSh4d0w** [comment]
Match TV : https://95-213-224-188.livesports24.online/ooomatch.m3u8

**Comment by freearhey** [comment]
@LaneSh4d0w Thank you!

**Comment by freearhey** [comment]
Both channels are currently on the playlist.
