### ISSUE TITLE
Turkish Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1986]
List of requests for Turkish channels from other issues:

- [ ] ATV Türkiye (#1782)
- [ ] ATV Avrupa (#1782)
- [x] Euro D (#1782)
- [x] Kanal D (#1782)
- [ ] [Kanal D Romania](https://www.lyngsat.com/tvchannels/tr/Kanal-D-Romania.html) (#762)
- [x] Show TV (#1782)
- [x] Show Türk (#1782)
- [x] TV 8 (#1782, #2267)

**Comment by trancer1994** [comment]
All of these streams are tokened in some way, I think.

**Comment by Kanaryam** [comment]
Beın sport iptv m3u8 varmı

**Comment by gonjumixproject** [comment]
TV 8 is tokened but i can share the others if you wish

**Comment by trancer1994** [comment]
Can the person who commented share the other channels, please?

**Comment by MH140000** [comment]
ATV Türkiye 
http://dvr3web.giniko.com/xml/atv-tv.plist
this is xml file, you can export live links with script anytime.

**Comment by MH140000** [comment]
ATV Türkiye 
http://mfe.cliptv.az/dash/ATV_Turk_HD.ism/playlist.mpd
