### ISSUE TITLE
Antigua and Barbuda Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1987]
List of requests for Antigua and Barbuda channels from other issues:

- [X] [ABS TV](https://www.lyngsat-stream.com/tvchannels/ag/ABS-TV.html) (#1810) (added via #2979)

**Comment by trancer1994** [comment]
The url I was able to find for ABS TV was https://usher.ttvnw.net/api/channel/hls/absliveantigua3.m3u8?allow_source=true&fast_bread=true&p=9443186&play_session_id=70edbe87dc46406747515c0c5fc35a6e&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=7451b38622b11a10c11f27ee267d119fd2e0c100&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22absliveantigua3%22%2C%22channel_id%22%3A492332740%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%225CD5pbfXbk25jbA4rW79MhwECuu8FNRe%22%2C%22expires%22%3A1611327080%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22embed%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3Anull%2C%22user_ip%22%3A%225.69.66.101%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.2.0

**Comment by LaneSh4d0w** [comment]
> 
> 
> The url I was able to find for ABS TV was <snip>

Twitch tokened stream.

**Comment by LaneSh4d0w** [comment]
This issue might be solved soon with #2833 's findings.

**Comment by LaneSh4d0w** [comment]
https://query-streamlink.lanesh4d0w.repl.co/iptv-query?streaming-ip=https://www.twitch.tv/absliveantigua3/
https://iptv--iptv.repl.co/streamlink?url=https://www.twitch.tv/absliveantigua3/
https://salvahe.co/headless?url=https://www.twitch.tv/absliveantigua3/

**Comment by freearhey** [comment]
@LaneSh4d0w If you manage to find a working link you can add it directly to the playlist. Just add a link to the issue in the description of the PR.

**Comment by LaneSh4d0w** [comment]
Well, I know they're streaming on Twitch, so this is the only known link for now.

**Comment by freearhey** [comment]
@LaneSh4d0w The link is fine, I've already added it to the playlist.

**Comment by LaneSh4d0w** [comment]
All good, I've edited OP, and now it is safe to close.
