### ISSUE TITLE
Taiwanese Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#1991]
List of requests for Taiwanese channels from other issues:

- [ ] CTI TV Asia (#1599)

**Comment by trancer1994** [comment]
CTI TV
https://www.youtube.com/embed/9pWXAEZ5NLs?autoplay=true

**Comment by happyeggchen** [comment]
hi,can most of the m3u8 source can be used in your player?I can only use 1 channel in Taiwan selection,by the way ,I'm using vlc on debian buster

**Comment by LaneSh4d0w** [comment]
> 
> 
> hi,can most of the m3u8 source can be used in your player?I can only use 1 channel in Taiwan selection,by the way ,I'm using vlc on debian buster

Either we have some unsorted Taiwanese channels, either some links are dead, and if it's that case, we'll have a look at it.

If I understood well, are you saying that only one channel in all the TW selection works ?

**Comment by happyeggchen** [comment]
> > 
> > 
> > hi,can most of the m3u8 source can be used in your player?I can only use 1 channel in Taiwan selection,by the way ,I'm using vlc on debian buster
> 
> Either we have some unsorted Taiwanese channels, either some links are dead, and if it's that case, we'll have a look at it.
> 
> If I understood well, are you saying that only one channel in all the TW selection works ?

yes, located in Shanghai,few of channels work.Im using chunghwa telecom( it's a Taiwan telecom company so not the problem of firewall) now.

**Comment by LaneSh4d0w** [comment]
> > > hi,can most of the m3u8 source can be used in your player?I can only use 1 channel in Taiwan selection,by the way ,I'm using vlc on debian buster
> > 
> > 
> > Either we have some unsorted Taiwanese channels, either some links are dead, and if it's that case, we'll have a look at it.
> > If I understood well, are you saying that only one channel in all the TW selection works ?
> 
> yes, located in Shanghai,few of channels work.Im using chunghwa telecom( it's a Taiwan telecom company so not the problem of firewall) now.

Interesting... Maybe some Taiwanese channels located in China might geolock Taiwanese people for reasons we know.

We'll need to see this into a deeper state. I personally do not have any Taiwanese VPN so it will be difficult trying to see if the link works.

**Comment by LaneSh4d0w** [comment]
This issue might be closed soon with #2833 's findings (they also seem to change the link quite often, use https://www.youtube.com/channel/UC5l1Yto5oOIgRXlI4p4VKbw/live instead).

**Comment by themak1985** [comment]
Added via #3025
