### ISSUE TITLE
Add: Bein sport Channels

### ISSUE THREAD

**Issue by darklight147** [iptv-org/iptv#1997]
Channel Name: Bein sport
Country: ALL middle east 
Language: English /Arabic
Notes (optional): maximum of 10 channels that stream mostly soccer and basketball, thank you

**Comment by LaneSh4d0w** [comment]
See #1956

**Comment by darklight147** [comment]
Oh i didnt notice, i hope they get added soone

**Comment by LaneSh4d0w** [comment]
Since they're paid channels, I doubt we will get a long-lasting stream, but we can still work on it :)
