### ISSUE TITLE
Fix: 8TV

### ISSUE THREAD

**Issue by dericliew** [iptv-org/iptv#2002]
***Channel Name:*** 8TV & NTV7
***Broken Link (from playlist):*** https://iptv-org.github.io/iptv/countries/my.m3u

***Possible Replacement (optional):*** xxx
***Notes (optional):*** xxx

**Comment by freearhey** [comment]
Replaced via https://github.com/iptv-org/iptv/commit/5cc332fb4b4ee9f130e95ccff2263872ee24b050

**Comment by dericliew** [comment]
Dear Aleksandr,

The m3u url is not working.

________________________________

**Comment by freearhey** [comment]
@dericliew I added them to the list.
