### ISSUE TITLE
Add: The CW

### ISSUE THREAD

**Issue by TmsKoncz** [iptv-org/iptv#2013]
***Channel Name:*** The CW
***Country:*** USA
***Language:*** EN (with EN subtitles, if possible)
***Notes (optional):*** xxx

**Comment by freearhey** [comment]
The channel is already on the playlist: https://github.com/iptv-org/iptv/blob/3bddbd2c704dfb8e3f59d3d9fbe301271d867edf/channels/us.m3u#L870-L871

**Comment by LaneSh4d0w** [comment]
Depending on the state, it's got different things. Maybe it's a state-specific CW he's asking ?

**Comment by Jeff-Le** [comment]
The CW channels aren't working. They state that the channels have a playback error on VLC or that the English file can't be loaded on Kodi.
