### ISSUE TITLE
Fix: Caribbean Channel

### ISSUE THREAD

**Issue by Boxiet** [iptv-org/iptv#2035]
***Channel Name:*** Telecuracao
***Broken Link (from playlist):*** http://api.streann.com:8080/loadbalancer-dev/services/public/channels/56992db2e4b045bf250ba13c/playlist.m3u8
--
***Possible Replacement (optional):*** https://telecuracao.com/
***Notes (optional):*** It's repeating still

**Comment by LaneSh4d0w** [comment]
No issues on my side.
![vlcsnap-2021-01-23-19h48m56s967](https://user-images.githubusercontent.com/30985701/105611200-20293500-5db4-11eb-83a0-9e7ed100c765.png)

The repeating might come from your bandwidth, the program trying to change definitions, or your video player having difficulties.

**Comment by LaneSh4d0w** [comment]
There you go : http://ott.streann.com:8080/loadbalancer/services/public/channels/5ed71e232cdc24a3d08cd6de/playlist.m3u8

**Comment by Boxiet** [comment]
Hi Sir,  Yes, this image stays in loop after 10 minutes. Look for the live channel on Telecuracao.com. that image is 1 year old. The logo of the channel is in Gold colors currently. Best regards, Betty From: LaneSh4d0wSent: Saturday, January 23, 2021 2:50 PMTo: iptv-org/iptvCc: Boxiet; AuthorSubject: Re: [iptv-org/iptv] Fix: Caribbean Channel (#2035) No issues on my side.The repeating might come from your bandwidth, the program trying to change definitions, or your video player having difficulties.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by LaneSh4d0w** [comment]
Please try the new link sent, this one should work.

**Comment by Boxiet** [comment]
Hi, That link is not working. Im playing via VLC and tivimate. It doesn’t include any channels  Sent from Mail for Windows 10 From: LaneSh4d0wSent: Saturday, January 23, 2021 3:06 PMTo: iptv-org/iptvCc: Boxiet; AuthorSubject: Re: [iptv-org/iptv] Fix: Caribbean Channel (#2035) Please try the new link sent, this one should work.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by LaneSh4d0w** [comment]
Just tested, it works for me. This is weird.

Attached is stream pics : 

![vlcsnap-2021-01-23-22h05m11s893](https://user-images.githubusercontent.com/30985701/105614075-312f7180-5dc7-11eb-8181-f4e7d8bbe3ed.png)
![vlcsnap-2021-01-23-22h05m22s738](https://user-images.githubusercontent.com/30985701/105614080-38ef1600-5dc7-11eb-97c6-35fc14eec096.png)

**Comment by Boxiet** [comment]
Great sir! Its working 100%But will your changes automatically merge to main project? Because its playing old link still after downloading iptvmaster.zip Many thanks!  From: LaneSh4d0wSent: Saturday, January 23, 2021 5:06 PMTo: iptv-org/iptvCc: Boxiet; AuthorSubject: Re: [iptv-org/iptv] Fix: Caribbean Channel (#2035) Just tested, it works for me. This is weird.Attached is stream pics :—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by LaneSh4d0w** [comment]
I'll let one of the collaborators answer this if merged.

Glad it works for you now.
