### ISSUE TITLE
Broken Channel

### ISSUE THREAD

**Issue by shuaibuubah** [iptv-org/iptv#2036]
Please fix the Africa Tv3 and Zee Cinema.

**Comment by freearhey** [comment]
Closed in favor #1958 and #1934

**Comment by freearhey** [comment]
Please use [this](https://github.com/iptv-org/iptv/issues/new?assignees=&labels=broken+stream&template=broken-stream.md&title=Replace%3A+xxx) form next time to report a broken channel.
