### ISSUE TITLE
Arewa 24

### ISSUE THREAD

**Issue by shuaibuubah** [iptv-org/iptv#2040]
***Channel Name:*** Arewa24
***Channel ID:** Arewa24.ng
***Country:*** Nigeria
***Language:*** Hausa
***Notes (optional):*** xxx

**Comment by LaneSh4d0w** [comment]
Use #1958 if you got channel requests.

**Comment by freearhey** [comment]
Closed in favor #1958

**Comment by freearhey** [comment]
Closed in favor of #12323
