### ISSUE TITLE
Is this meant to use guide data?

### ISSUE THREAD

**Issue by Darkwolf1515** [iptv-org/iptv#2067]
Sorry, very new to iptv, while the streams work just fine in Jellyfin, the only metadata they have is the Chanel logo png's, is this meant to be this way? Or am I missing something to add the proper guide metadata.

Thank you!

**Comment by LaneSh4d0w** [comment]
Hello,

If you are talking about EPG, please be aware that we do not have this for every channel, which might explain why you do not have guide metadata for some channels (the majority, in fact).
