### ISSUE TITLE
Baby TV México

### ISSUE THREAD

**Issue by luixiuno** [iptv-org/iptv#2079]
***Channel Name:*** BabyTV
***Country:*** America
***Language:*** Spanish
***Notes (optional):*** Mexican

**Comment by LaneSh4d0w** [comment]
Since BabyTV is from the US, please add your request to #1942

**Comment by freearhey** [comment]
Closed in favor #1943

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/e4d22b4d9e6151c4d25dfc74afcabc36147ea506/streams/us.m3u#L157-L158
