### ISSUE TITLE
[Announcement] New `tvg-country` attribute in channel descriptions

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#2086]
With the next update the attribute `tvg-country` will be added to the description of all channels, which will contain the code of the country in which the channel is broadcast:

<pre>
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="" <b>tvg-country="US"</b> group-title="",CNN
https://example.com/stream.m3u
</pre>

These changes should solve the problem when a channel is produced in one country and broadcasted in another and when sorted it is not placed in the playlist users expect to see it.

For example, as @data14a pointed out https://github.com/iptv-org/iptv/pull/2016#issuecomment-762867163, most Iranian channels are broadcasted from abroad (UK, Turkey), as a result, the channels do not get into Iranian playlist. Similar situation with channels that have several versions in different languages (Cartoon Network, BBC, FOX, ...) which usually end up in the playlist US or UK. It will also allow us to include geo-blocked broadcasts in the playlist if the correct country is specified in the attribute.

After the update, if a channel is broadcast in several countries, they can all be specified separated by semicolons:

<pre>
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="" <b>tvg-country="US;CA;MX"</b> group-title="",CNN
</pre>

Based on the `tvg-country` value, the channels will be put into the corresponding country playlists:

<a href="https://github.com/iptv-org/iptv#playlists-by-country"><img width="747" alt="Captura de pantalla 2021-01-30 a las 19 43 15" src="https://user-images.githubusercontent.com/7253922/106362360-6c83f000-6333-11eb-9779-0ae4e68469f7.png"></a>

During the update, the `tvg-country` attribute will automatically save the country code of the playlist where the channel is located at the moment.

If a channel is broadcast for an entire region, you can use short region codes to avoid listing all countries:

| Code | Description
|---|---
| [AFR](https://en.wikipedia.org/wiki/Africa)  | Africa
| [AMER](https://en.wikipedia.org/wiki/Americas) | Americas
| [APAC](https://en.wikipedia.org/wiki/Asia-Pacific) | Asia-Pacific
| [ASIA](https://en.wikipedia.org/wiki/Asia) | Asia
| [CARIB](https://en.wikipedia.org/wiki/Caribbean) | Caribbean
| [EMEA](https://en.wikipedia.org/wiki/Europe,_the_Middle_East_and_Africa) | Europe, Middle East and Africa
| [EUR](https://en.wikipedia.org/wiki/Europe) | Europe
| [LATAM](https://en.wikipedia.org/wiki/Latin_America) | Latin America
| [MENA](https://en.wikipedia.org/wiki/MENA) | Middle East and North Africa
| [MIDEAST](https://en.wikipedia.org/wiki/Middle_East) | Middle East
| [NORAM](https://en.wikipedia.org/wiki/North_America) | North America
| [NORD](https://en.wikipedia.org/wiki/Nordic_countries) | Nordics
| [OCE](https://en.wikipedia.org/wiki/Oceania) | Oceania
| [SAS](https://en.wikipedia.org/wiki/South_Asia) | South Asia
| [SSA](https://en.wikipedia.org/wiki/Sub-Saharan_Africa) | Sub-Saharan Africa

If you specify one of these codes, the channel will be added to the playlists of all countries from that region. Support for other regions may be added later.

If the channel is broadcast worldwide you can use the code `INT`:

<pre>
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="" tvg-logo="" <b>tvg-country="INT"</b> group-title="",CNN
</pre>

Within the `channels/` folder, channel will still be sorted by country of production and will only have to be represented in one of the files.

**IMPORTANT:** If you use the `channels.json` in your project, be prepared that after updating the `countries` property will be renamed to `countries` and will return an array.

Before:

```
{
    ...
    "country": {
      "code": "us",
      "name": "United States"
    },
    ...
}
```

After:

```
{
    ...
    "countries": [
        {
            "code": "us",
            "name": "United States"
        },
        {
            "code": "ca",
            "name": "Canada"
        },
    ]
    ...
}
```

**P.S.** This update will only go live if and when this post gets <del>10</del> **5** (updated February 7, 2021) or more likes, to make sure the core community reads and approves it.

**Comment by LaneSh4d0w** [comment]
Sounds good on the paper, but multiple constraints : 

- Some societies do not indicate in which country the channel is available.
- This adds something that will need to be put on in the contributing guide.
- This is a breaking change, by that I mean that people should be more vigilant in where the channels are (As an example : RT exists in Russia, in France, and in the US.)
- Be more clear on the tvg-country. If we put the french variant of Boomerang, do we need to put EVERY country in which Boomerang exists ? It's a bit weird.
- Some channels claim to be international, but are only available on certain satellites AFAIK.

**Comment by freearhey** [comment]
- During the update, the `tvg-country` attribute will automatically save the country code of the playlist where the channel is located at the moment. So in case it is not possible to find out the country in which the channel is broadcast, you can simply leave the default value.
- I will add a description of the attribute in the Contributing Guide.
- If more than one country is specified in the attribute, the channel will automatically be placed in the playlists of all those countries. So in the case of RT, it will be on all three playlists.
- Good point. I will soon add support for popular codes for different regions of the planet (such as MENA, AFR, etc.) and that should solve this problem. After that for the French version of Boomerang it would be enough to write "FR,BE,CH,AFR".

**Comment by HNJAMeindersma** [comment]
Big up from me for clarification on the whole produced/broadcast difference

**Comment by themak1985** [comment]
Hey  @freearhey  - sorry I have been out of it for the past couple weeks. 
I guess my question is, what is the desired outcome for the end user?
I use the language playlists because I find them most useful. Arabic & English in particular. So this change does not affect me. 

However, in the English playlist, there are at least 24 Bloomberg TV and variants, many are duplicates, I could see how this fix would move all the Bloomberg channels to US, but the tvg-attribute would be the country or region. The US playlist would have all the variants, but Bloomberg TV Asia would have tvg-country="APAC" or tvg-country="ASIA" (honestly I don't know any region channels that are only ASIA and not APAC) Bloomberg Australia would be tvg-country="Australia" or tvg-country="OCE"

MBC Iraq and MBC 5, both should be in the Saudi Arabia file, but would be tvg-country="Iraq" and tvg-country="Morocco" respectively.

Now here are the tricky ones. France 24 English and DW English. They broadcast to english language countries like the US, UK, and Australia which includes EUR, AMER, and OCE.  France 24 French (Original) also broadcasts to francophone countries in at least 4 regions.

Maybe some "regions" that are Francophone, Anglophone, Lusophone, Hispanophone, Arabophone, etc, would solve that issue. For example Al Jazeera (OG/Arabic) is a pan-arab news channel. It would be in qa.m3u but I am not sure how helpful it is to have tvg-country="MENA" that would include Turkey and Iran which only have minority populations that speak Arabic. 

Another example would be US channels that broadcast in spanish to latin american countries that speak spanish, but not those that speak portuguese, english, or dutch.

So I support the change, but with the understanding that there will be some complicated cases.

**Comment by freearhey** [comment]
@themak1985 I'm glad you are back)

First of all, you're right for language playlist users, nothing will change.

The main purpose of this update is to make the content of **country** playlists more predictable for users. So if a channel is officially available in some country it should end up in the playlist of that country. And I only mean playlists that go into `https://iptv-org.github.io/iptv/countries/...`. This does not mean that the playlist should have channels in the same language (we have separate playlists for this). 

At the same time, as you correctly pointed out, this will allow us to collect all versions of the same channel in one place and hopefully simplify our work too.

As for DW and France 24, Wikipedia states that they are broadcast worldwide, so in this case I guess it would be ok to specify the code `INT` for all versions. Same for Al Jazeera. But if in the end it turns out that the existing regional codes are not enough, we will of course add others.

And yes, we may not be able to properly sort all the channels at once, but at least now it will be possible to do.

**Comment by themak1985** [comment]
@freearhey DW and France 24 are broadcasted worldwide, but each channel variant is for a different market, usually language based. I personally wouldn't want every variant of every DW and F24 channel to appear in every country's playlist.

**Comment by themak1985** [comment]
Maybe adding these regions would help:
Using [this wikipedia article](https://en.wikipedia.org/wiki/List_of_languages_by_the_number_of_countries_in_which_they_are_recognized_as_an_official_language) as a source and using ISO 639-3 for code. I just put those with 5 or more countries for now, but can expand. I think these combined with your regions should cover all of our bases. 

Code | Description
-- | --
ENG | English Speaking Countries
FRA | French Speaking Countries
ARA | Arabic Speaking Countries
SPA | Spanish Speaking Countries
POR | Portuguese Speaking Countries
DEU | German Speaking Countries
RUS | Russian Speaking Countries
SWA | Swahili Speaking Countries

**Comment by freearhey** [comment]
@themak1985 Sorry, but I do not understand why you do not like the idea that all channels available in your country will be available in one playlist?

**Comment by themak1985** [comment]
@freearhey admittedly, there is some overlap, but let's say I want the UK playlist, that would give me all UK channels and all international channels that target english speaking countries (ENG), but it would exclude, for example, US/AU/NZ english channels that are not intended for international english speaking countries distribution. Of course the UK playlist would also include the EUR and EMEA (categories you proposed) channels.

**Comment by freearhey** [comment]
@themak1985 where do you propose to get info about the channel's target audience?

**Comment by themak1985** [comment]
I think we will have to rely on the knowledge of the community, information on the channel wiki pages, etc, but here are some guiding links I quickly found.

https://en.wikipedia.org/wiki/List_of_world_news_channels
https://logosfake.fandom.com/wiki/List_of_Pan-Hispanic_Atlansian_television_channels

**Comment by freearhey** [comment]
@themak1985 So in the case of PTV World, for example, we would have to specify the code "ENG" even though it is only broadcast in South Asia?

I propose to do so, I publish an update today/tomorrow and start gradually updating the description of channels marking international channels as "INT". Then when it will be clear how many such channels in the playlist and how much of a problem it is, we separately discuss adding new codes including the ones you suggested earlier. Agreed?

**Comment by themak1985** [comment]
@freearhey sorry if I am not doing a good job of explaining.

I just know there are about 20 channels off the top of my head that would be ARB, but would not fit in any of the categories you proposed and I don't know a single channel that would be in the ASIA, APAC, AMER categories (as proposed) for example. I am happy to go through and make every channel in the repository that broadcasts to multiple countries, but doesn't fit the regions proposed as INT if you would prefer, but that seems like a very time consuming process. 

I don't want to be difficult or hold up the process, so I agree to proceed and try out the system as proposed. Thanks again for all you do.

**Comment by freearhey** [comment]
@themak1985 In fact, I added all the regions directly from the "Broadcast Area" field of the channel description on Wikipedia. But that doesn't mean you have to use them. You can always specify a specific country code in the attribute if the channel broadcasts in that country. As I wrote earlier, regional codes are just a shorthand for a large list of countries.

And don't get me wrong, I'm very interested in your opinion, it's just hard for me to discuss how to improve something that doesn't work yet.

**Comment by themak1985** [comment]
@freearhey lets try it as you proposed and I can submit an issue for discussion for the language speaking country regions to be added as you prefer.
