### ISSUE TITLE
Al Jadeed

### ISSUE THREAD

**Issue by HosamAldin** [iptv-org/iptv#2097]
***Channel Name:*** Al Jadeed
***Country:*** Lebanese
***Language:*** AR
***Notes (optional):*** xxx

**Comment by themak1985** [comment]
@HosamAldin - Channel requests can only have one channel. Edited to be only one channel, you can submit another request for MTV

**Comment by jad222** [comment]
Applied pull req
https://github.com/iptv-org/iptv/pull/2098#issue-568513166

**Comment by freearhey** [comment]
Closed in favor #2347

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/7d1bf746b966d5279cd8e64964440c23f45042d0/channels/lb.m3u#L6-L7
