### ISSUE TITLE
Add: TV Zimbo

### ISSUE THREAD

**Issue by southerndream56** [iptv-org/iptv#2101]
***Channel Name:*** TV Zimbo
***Country:*** Angola
***Language:*** xxx
***Notes (optional):*** Could you please add new channel in the Angola group,here the link:         https://www.lyngsat-stream.com/tvchannels/ao/TV-Zimbo.html

**Comment by themak1985** [comment]
@southerndream56 I fixed your channel request for you - please be sure to fill out all the requested information next time.

**Comment by LaneSh4d0w** [comment]
Had provided TV Zimbo before, but I had issues with the livestream link changing over time.

**Comment by LaneSh4d0w** [comment]
https://api.new.livestream.com/accounts/29819666/events/9254936/broadcasts/217180542.m3u8

**Comment by themak1985** [comment]
Yeah, i've never been able to figure out how to bypass the vimeo livestream event style streams. They essentially create a new stream every X hours. https://vimeo.com/509238972 is an example - you can see on that channel, they have a new video created every 8 or so hours.

Lets see, maybe the link you provided will still work in 24hours.

**Comment by Sphinxroot** [comment]
If replay  broadcasts/"219581614".m3u8 will need to be changed over and over
#EXTINF:-1 ,TV Zimbo
http://api.new.livestream.com/accounts/29819666/events/9254936/broadcasts/219581614.m3u8

normaly If its realy a Live feed it should work  or the broadcaster have put live option off , but it aint working for some reason
#EXTINF:-1 ,TV Zimbo 
https://api.new.livestream.com/accounts/29819666/events/9254936/live.m3u8

**Comment by LaneSh4d0w** [comment]
Yes indeed, I had tried it and didn't work, but it seems that this still works for some reason...

**Comment by freearhey** [comment]
@Sphinxroot Thanks!

Channel added to playlist via https://github.com/iptv-org/iptv/commit/626aaabadb8c3a4ba9035ecbcd03acd0d5ef383e

**Comment by Tiago041** [comment]
<html>
<body>

https://sgn-cdn-video.vods2africa.com/Tv-Zimbo/index.fmp4.m3u8
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by BellezaEmporium** [comment]
> https://sgn-cdn-video.vods2africa.com/Tv-Zimbo/index.fmp4.m3u8

Weirdly enough this seems to be an official link, as the people behind that website have got a partnership with the Angolan government.
