### ISSUE TITLE
Add: 2M Monde - Higher Quality Version

### ISSUE THREAD

**Issue by kikar92** [iptv-org/iptv#2102]
***Channel Name:2M Monde
***Country:Morocco
***Language:arabic
***Notes (optional): 480p or 578p or 720p quality

thank you

**Comment by themak1985** [comment]
Only other link I found for this is https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/2m_monde/hls_video_ts/index.m3u8 - Max resolution seems to be 640x360.

**Comment by LaneSh4d0w** [comment]
> 
> 
> ***Channel Name:2M
> ***Country:Morocco
> ***Language:arabic
> ***Notes (optional): 480p or 578p or 720p quality
> 
> thank you

Not that easy to get the local version in HD. As far as I know, the "Société Nationale de Radiodiffusion Marocaine" has bumped their local channels in HD, but as far as I know, 2M Maroc hasn't been bumped.

**Comment by LaneSh4d0w** [comment]
> 
> 
> Only other link I found for this is https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/2m_monde/hls_video_ts/index.m3u8 - Max resolution seems to be 640x360.

Wrong version, this one is the one that's being distributed internationally. The one OP is speaking is the local version of the channel, targeted for Morrocan people.

**Comment by themak1985** [comment]
I understand that but we only have 2M Monde in our repository and they are asking for a better version of the channel we have - so maybe they want 2M Monde. @kikar92 let us know.

**Comment by LaneSh4d0w** [comment]
> I understand that but we only have 2M Monde in our repository and they are asking for a better version of the channel we have - so maybe they want 2M Monde. @kikar92 let us know.

Yup, that I know :) just wanted to clarify by saying he wanted the Morrocan version of this channel, not the international one.

**Comment by kikar92** [comment]
> 2M Monde

**Comment by kikar92** [comment]
> I understand that but we only have 2M Monde in our repository and they are asking for a better version of the channel we have - so maybe they want 2M Monde. @kikar92 let us know.

First thank you all for the help, and yes i want 2m monde if it better quality because this one it a potato quality

**Comment by kikar92** [comment]
> better quality version of the stream

yes, there is no program difference between 2m and 2M monde. i just one better quality anyone will be good for me

**Comment by kikar92** [comment]
yes, there is no program difference between 2m and 2M monde. i just one better quality anyone will be good for me

**Comment by themak1985** [comment]
@kikar92 I figured as much - thanks for the clarification. Hopefully someone will find a stream.

**Comment by LaneSh4d0w** [comment]
> @kikar92 I figured as much - thanks for the clarification. Hopefully someone will find a stream.

I'll try to sniff their application : my2M and see if I can get something out of it :)

**Comment by kikar92** [comment]
> > @kikar92 I figured as much - thanks for the clarification. Hopefully someone will find a stream.
> 
> I'll try to sniff their application : my2M and see if I can get something out of it :)

Thank you man hope it will work

**Comment by LaneSh4d0w** [comment]
The link that is available in my2M is this one : https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/2m_monde/hls_video_ts/2m_monde.m3u8

**Comment by kikar92** [comment]
> The link that is available in my2M is this one : https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/2m_monde/hls_video_ts/2m_monde.m3u8
> 
> ![image](https://user-images.githubusercontent.com/30985701/107436336-acb25200-6b2d-11eb-8665-f581495a9fec.png)

Mmh it 360p same one i use thank you for the help

**Comment by LaneSh4d0w** [comment]
I'm afraid that sadly we won't be able to get a better quality stream than this one (the official one to say at least).

**Comment by themak1985** [comment]
I think we can go ahead and close this issue for now. Please open a new issue or reopen this issue if anything changes.

**Comment by LaneSh4d0w** [comment]
Sorry to dump it back, but I've found out that even the satellite transmission does not seem to stream this channel in HD.

![image](https://user-images.githubusercontent.com/30985701/120940050-71124800-c71b-11eb-8edc-73914b297d64.png)
![image](https://user-images.githubusercontent.com/30985701/120940054-77082900-c71b-11eb-9959-3cc1ac96f8e8.png)

**Comment by kikar92** [comment]
Sorry just one last question, where this person found this quality
http://dimapro.cz:8080/live/KzilaUMFaY/lUE9wE6vqE/2360.m3u8
The problem that i can't use it because hes change it every week

**Comment by LaneSh4d0w** [comment]
> 
> 
> Sorry just one last question, where this person found this quality
> http://dimapro.cz:8080/live/KzilaUMFaY/lUE9wE6vqE/2360.m3u8
> The problem that i can't use it because hes change it every week

Same quality as the other versions.

**Comment by LaneSh4d0w** [comment]
http://dimapro.cz:8080/live/KzilaUMFaY/lUE9wE6vqE/2360.m3u8

![vlcsnap-2021-06-11-17h21m12s435](https://user-images.githubusercontent.com/30985701/121710030-708dfe80-cad9-11eb-9e96-afa3d4ae27ae.png)

https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/2m_monde/hls_video_ts/2m_monde.m3u8

![vlcsnap-2021-06-11-17h21m47s036](https://user-images.githubusercontent.com/30985701/121710105-869bbf00-cad9-11eb-8a46-4439f36bf935.png)


http://149.100.19.226:8001/play/2M_Maroc

![vlcsnap-2021-06-11-17h20m36s037](https://user-images.githubusercontent.com/30985701/121709948-5eac5b80-cad9-11eb-9f77-cff4e4e88211.png)

The DimaCZ host is simply a restream of the Nilesat stream.

**Comment by kikar92** [comment]
Mhh, This is `mine.`
![IMG_20210611_172656](https://user-images.githubusercontent.com/9077185/121711304-bdbea000-cada-11eb-83c3-30bdf87c55f1.jpg)
![IMG_20210611_172625](https://user-images.githubusercontent.com/9077185/121711528-fd858780-cada-11eb-9a50-45425b486a5f.jpg)
  
I think it the resultion but i can't change it

**Comment by LaneSh4d0w** [comment]
Weird, indeed. From my point of view, it's good.

![IMG_20210611_173917](https://user-images.githubusercontent.com/30985701/121712660-4722a200-cadc-11eb-81f9-44c19d72e554.jpg)

**Comment by kikar92** [comment]
No problem will work with this one thank you any way man for your fast reply 😉

**Comment by ahmedel3453** [comment]
m3u link 2m maroc HD

**Comment by imagesloads** [comment]
http://venolie.com/navo/view/p/2m.php

**Comment by AdamMRKS** [comment]
m3u pls

**Comment by BellezaEmporium** [comment]
> m3u pls

Secondary link is already in the repository : https://d2qh3gh0k5vp3v.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-n6pess5lwbghr/2M_ES.m3u8
