### ISSUE TITLE
Add: Arewa24

### ISSUE THREAD

**Issue by shuaibuubah** [iptv-org/iptv#2108]
**Channel Name:** Arewa24
**Country:** Nigeria
**Language:** Hausa
**External Link (optional):** 
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
You already have asked for this channel before. It was closed in the profit of another issue compiling all the wanted channels. Please look on the already open issues before opening a new one.

Reference : #1958

**Comment by freearhey** [comment]
Duplicate #2040
