### ISSUE TITLE
Zee Cinema

### ISSUE THREAD

**Issue by shuaibuubah** [iptv-org/iptv#2109]
**Channel Name:** Zee Cinema
**Channel ID:** ZeeCinema.in
**Country:** India
**Language:** Hindi/English
**External Link (optional):** xxx
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
This channel was already asked by someone else. Please look on the issues list before adding a new one here.

Reference : #1934

**Comment by freearhey** [comment]
Closed in favor #1934

**Comment by freearhey** [comment]
Closed in favor of #12322
