### ISSUE TITLE
Remove XXX category and create a separate playlist for XXX

### ISSUE THREAD

**Issue by NoNameFH** [iptv-org/iptv#2126]
Hi,

I have been using different player for the playlists and most of them are not able to block the xxx contents. So, it will be a good idea to put all of the XXX channels in a separate playlist and whoever needs it just add the list separately. In that way at least is a peace of mind that the kids will not accidently access the category from the list.

Thanks,

**Comment by freearhey** [comment]
You can use the SFW version of the playlist `https://iptv-org.github.io/iptv/index.sfw.m3u`

**Comment by NoNameFH** [comment]
Many Many Thanks :)
