### ISSUE TITLE
Propose: Add the SFW link on the README

### ISSUE THREAD

**Issue by LaneSh4d0w** [iptv-org/iptv#2133]
I've seen that the SFW playlist creation PR was merged, and so it should be good to put the playlist in the README.

**Comment by LaneSh4d0w** [comment]
Something like this for example, under the 3 playlists ;
``- `https://iptv-org.github.io/iptv/index.sfw.m3u` (Safe For Work (SFW) IPTV playlist.)``

**Comment by freearhey** [comment]
The link is already in the README: https://github.com/iptv-org/iptv#usage
