### ISSUE TITLE
All countries and all languages playlists create groups with multiple countries/languages

### ISSUE THREAD

**Issue by themak1985** [iptv-org/iptv#2136]
Not sure if this is a software thing or a code thing.
If you use:
https://iptv-org.github.io/iptv/index.country.m3u (grouped by country)
https://iptv-org.github.io/iptv/index.language.m3u (grouped by language)

Channels with multiple languages or countries/regions will be listed as separate groups. Not sure if this is intentional or not. AFAIK, individual country or language playlists include all the channels they should, it is just these mega playlists that are affected. Tried this using any different "iptv" apps and got the same result.

**Comment by freearhey** [comment]
I will look into it.

**Comment by freearhey** [comment]
@themak1985 I updated the code and now the extra groups should disappear.

**Comment by themak1985** [comment]
Confirmed, looks good. Thanks!
