### ISSUE TITLE
Propose: Select a single source of EPG

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#2139]
**What problem is this supposed to solve?**

At the moment, more than 80% of channels do not have `tvg-id` and `tvg-name`. This means that even if you have a valid channel program, in most cases you cannot use it without editing the playlist.

Right now we can specify a separate source for each country via the `x-tvg-url` attribute and copy the `tvg-id`/`tvg-name` from it:

```
#EXTM3U x-tvg-url="https://example.com/germany.epg.xml"
#EXTINF:-1 tvg-id="example.de" tvg-name="Example TV DE",Example TV
https://example.com/index.m3u8
...
```

But since the same channels are copied into dozens of other playlists we just can't use this link everywhere. As a result, in order to activate the program for all channels, the user must copy the EPG links from all playlists.

**What solution do I propose?**

The solution to this problem could be to select a single EPG source and take the IDs for all channels only from there. This way, in order to activate the program the user will only have to insert a single link to the EPG file in his player and open the playlist.

The main difficulty is that this source must have a program for most of the channels and countries in the playlist. So far I have found only two services that fit these requirements:

- [siptv.app](https://siptv.app/codes/)
- [epg.best](https://epg.best/available-channels)

Both services are paid, which is not ideal, but I do not see other options. If you know any similar services let me know.

In general, I would like to know where you get the program at the moment and how much acceptable, in your opinion, to use a paid service as a source of EPG for the project?

**What solutions have I also considered?**

Another solution would be to add a `tvg-url` attribute to the description of each channel and specify the link to the EPG specifically for that channel, like so:

```
#EXTINF:-1 tvg-id="example.de" tvg-name="Example TV" tvg-url="https://example.com/epg.xml",Example TV
https://example.com/index.m3u8
```

In this case we will not be tied to any source. But unfortunately as I know most players do not support this attribute and the user will still have to manually specify all the sources for each channel. Also in case the link to the EPG fails we will have to manually replace all channel tvg-id and tvg-name with new ones.

**Comment by LaneSh4d0w** [comment]
EPG.best as far as I know is a paid service, SIPTV might be good to use.

I've also put out https://github.com/epg-iptv/epg if you're interested in this.

**Comment by pcccw** [comment]
Single EPG source is pretty impractical. You need someone who has the time and cash to scrape all the tv guides around the world and compile it. Given the effort to do so, those who does tend to just make it a paid service to earn back some cash. 

Second, a single EPG source would be very huge. I maintain an epg source of about 500 channels and it is close to 20mb uncompressed for 3 day worth of EPG. I would imagine it would be larger for this site.

It would be more practical for contributors to contribute an EPG for their own country. And perhaps standardized tvg-id tag as it is common to have case where let say, a uk epg list conflict with a us epg list for common international channels like Cartoon Network, discovery, etc.

**Comment by freearhey** [comment]
@LaneSh4d0w Both services are paid.

At the link I see only a list of channels and config for WebGrab+. How exactly do you propose to use it?

**Comment by LaneSh4d0w** [comment]
@freearhey 
The work was based on the EPG source available on the AE playlist. (the "merge.zip" one) The XML playlists represents the different channels and the location of the EPG source online.

**Comment by freearhey** [comment]
@pcccw You are absolutely right, that's why in my suggestion I was talking about choosing a single EPG source, not a single file. As I know most services have the option to upload playlist and get the program only for those channels that are in it.

I also agree with you that we could create our own standard for tvg-id, I just thought someone might have done it already. For example, the services I mentioned earlier already have their own ID lists for most channels:
- https://siptv.app/codes/
- https://epg.best/available-channels

**Comment by freearhey** [comment]
@LaneSh4d0w So you're suggesting that people parse the program themselves?

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w So you're suggesting that people parse the program themselves?

I could try to parse the EPG for a week, and reload it every week. A script that scrapes the channels at their specific EPG source and writes the result in a XML file. Could be doable.

**Comment by themak1985** [comment]
Interesting - siptv.app provides a converter, it's not perfect, changes our attributes, but if people really needed a solution, that is a possibility for them. 

I would rather not default to a paid option like siptv.app or epg.best if there is a community developed option that meets my needs. 

I have not played with @LaneSh4d0w's repository, but maybe that is an approach - @LaneSh4d0w do you have an xml.gz file generated that we could test?

Lastly, we could choose to partner with some repos like 
https://github.com/Fazzani/grab (FR and ARAB epg)
https://github.com/qwerttvv/Beijing-IPTV (CN epg)
https://github.com/sunsettrack4/easyepg (DE,AT,CH,NL,PL,IE,SK,CZ,HU,RO,UK,US,CA)
https://github.com/mathewmeconry/TV7_EPG_Parser (IT, FR, DE)
https://github.com/harrygg/EPG (lots of EU channels)

Its imperfect, but just throwing it out as an idea.

**Comment by themak1985** [comment]
Also - I forgot, there is also https://m3u4u.com/ - they offer a free service - has many epg source, it's not perfect, but it is free, with an account.

**Comment by LaneSh4d0w** [comment]
> Interesting - siptv.app provides a converter, it's not perfect, changes our attributes, but if people really needed a solution, that is a possibility for them.
> 
> I would rather not default to a paid option like siptv.app or epg.best if there is a community developed option that meets my needs.
> 
> I have not played with @LaneSh4d0w's repository, but maybe that is an approach - @LaneSh4d0w do you have an xml.gz file generated that we could test?
> 
> Lastly, we could choose to partner with some repos like
> https://github.com/Fazzani/grab (FR and ARAB epg)
> https://github.com/qwerttvv/Beijing-IPTV (CN epg)
> https://github.com/sunsettrack4/easyepg (DE,AT,CH,NL,PL,IE,SK,CZ,HU,RO,UK,US,CA)
> https://github.com/mathewmeconry/TV7_EPG_Parser (IT, FR, DE)
> https://github.com/harrygg/EPG (lots of EU channels)
> 
> Its imperfect, but just throwing it out as an idea.

Not yet, but I plan to try to make one as soon as I can, as a testing EPG package.

**Comment by link8k** [comment]
https://play.google.com/store/apps/details?id=ru.iptvremote.android.iptv allows adding multiple EPG sources and combines them. That's what I use which solves this problem for me.

I think we should continue to use free/public epg. I like @LaneSh4d0w idea of merging them!

**Comment by freearhey** [comment]
Thank you all for your responses. I will try to find some other solution to this problem, until then everything remains the same.

**Comment by themak1985** [comment]
@freearhey are we using a new default source, I noticed in recent weeks many channels have that had blank epg info had their information populated, but I am not sure the source.

**Comment by freearhey** [comment]
@themak1985 let's just say I'm working on it. I decided to create a separate repository dedicated to [epg](https://github.com/iptv-org/epg), which could become such a source in the future. But since everything is still in beta at the moment, I decided not to announce it here and only update the id of those channels that didn't have them.

**Comment by LaneSh4d0w** [comment]
> 
> 
> @themak1985 let's just say I'm working on it. I decided to create a separate repository dedicated to [epg](https://github.com/iptv-org/epg), which could become such a source in the future. But since everything is still in beta at the moment, I decided not to announce it here and only update the id of those channels that didn't have them.

Can my EPG repository be of any help ? I think that you can try parsing my XMLs... if you got your own ways I can also try to look on the website and make a script to parse it.

**Comment by freearhey** [comment]
Thanks for the offer, but no help is needed yet.

**Comment by freearhey** [comment]
To continue this topic: https://github.com/iptv-org/epg/issues/2
