### ISSUE TITLE
index.country has many duplicates

### ISSUE THREAD

**Issue by vivazkote** [iptv-org/iptv#2140]
Hello! **index.country.m3u** is much bigger then **index.m3u** and has many duplicates with multi country tags, like:
_tvg-country="GE;EUR;ASIA;AMER"_

**Comment by freearhey** [comment]
That's the way it's supposed to be. Channels in this playlist are divided into groups by country, but, unfortunately, most players cannot group channels by `tvg-country` attribute. So we use the `group-title` attribute instead and insert the same link for each country:

<pre>
#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="GE;EUR;ASIA;AMER" <b>group-title="Afghanistan"</b>,1TV
https://tv.cdn.xsg.ge/gpb-1tv/tracks-v1a1/index.m3u8
...
#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="GE;EUR;ASIA;AMER" <b>group-title="Georgia"</b>,1TV
https://tv.cdn.xsg.ge/gpb-1tv/tracks-v1a1/index.m3u8
</pre>

**Comment by vivazkote** [comment]
exactly that channel is GE Georgia, and no way is Afganistan. thus is unwanted duplicate!

**Comment by freearhey** [comment]
The thing is that the attribute `tvg-country` contains a list of all the countries in which the channel is broadcast and according to the description on Wikipedia this channel is also broadcast in Afghanistan: https://en.wikipedia.org/wiki/First_Channel_(Georgian_TV_channel)
