### ISSUE TITLE
Propose: Allow adding YouTube links

### ISSUE THREAD

**Issue by link8k** [iptv-org/iptv#2158]
Some channels are only available on YouTube

Adding them to playlists requires specific player support but several apps support them.

```
#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="ARAB" tvg-language="English" tvg-logo="" group-title="News",Euronews (1080p)
https://www.youtube.com/EuronewsUSA/live
```

### The following players support YouTube:

- VLC
- https://play.google.com/store/apps/details?id=ru.iptvremote.android.iptv opens the link in the YouTube app
- Potentially more

### Creating smart links
YouTube has a feature that loads the latest live stream if the channel username/id is suffixed with /live . This reduces maintenance if the stream has been replaced.

https://www.youtube.com/EuronewsUSA **/live**

**Comment by LaneSh4d0w** [comment]
If we add this then a lot of other channels will be in it. Since YouTube tokenizes their stream (but do not seem to have a time limit it seems, compared to some other platforms), it will maybe be easier to maintain, and maybe also a lot better since Google has got servers almost everywhere, and you're sure not to lag in any.

**Comment by themak1985** [comment]
I like the idea, but there are some challenges - for one, we can't simply run a script to remove dead channels (or can we?). Second, that link you gave as an example is geolocked, so we would need to have clear standards. Lastly, if we expand to youtube, I don't see why we wouldn't expand to other platforms like Vimeo Livestream, ok.ru, and others.

I also wonder if we do go this approach if we should notate that it is non-traditional video source somehow in the name of the channel.

**Comment by LaneSh4d0w** [comment]
> I like the idea, but there are some challenges - for one, we can't simply run a script to remove dead channels (or can we?). Second, that link you gave as an example is geolocked, so we would need to have clear standards. Lastly, if we expand to youtube, I don't see why we wouldn't expand to other platforms like Vimeo Livestream, ok.ru, and others.
> 
> I also wonder if we do go this approach if we should notate that it is non-traditional video source somehow in the name of the channel.

It's simple to verify, but we should have youtube-dl ready to look after the playlists. We could make a script that summons it, verifies if YouTube answers with a playlist, and test it like any other playlist we got.

For OK.ru I suppose they have tokenized streams and I also suppose there's some kind of executable that does the job

**Comment by themak1985** [comment]
An alternative - we maintain a repository for liveproxy and maintain all those links there. This would also solve the tokenization issue.
https://github.com/back-to/liveproxy

**Comment by freearhey** [comment]
@link8k For me personally, the Euronews broadcast from YouTube immediately freezes when I try to watch it through VLC.

**Comment by hemzaberkane** [comment]
> @link8k For me personally, the Euronews broadcast from YouTube immediately freezes when I try to watch it through VLC.

its works good for me in vlc

**Comment by hemzaberkane** [comment]
> Some channels are only available on YouTube
> 
> Adding them to playlists requires specific player support but several apps support them.
> 
> ```
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-country="ARAB" tvg-language="English" tvg-logo="" group-title="News",Euronews (1080p)
> https://www.youtube.com/EuronewsUSA/live
> ```
> 
> ### The following players support YouTube:
> * VLC
> * https://play.google.com/store/apps/details?id=ru.iptvremote.android.iptv opens the link in the YouTube app
> * Potentially more
> 
> ### Creating smart links
> YouTube has a feature that loads the latest live stream if the channel username/id is suffixed with /live . This reduces maintenance if the stream has been replaced.
> 
> https://www.youtube.com/EuronewsUSA **/live**

i need an app can open the link !

**Comment by LaneSh4d0w** [comment]
> @link8k For me personally, the Euronews broadcast from YouTube immediately freezes when I try to watch it through VLC.
 
Weird, as far as I know they're 24/7

**Comment by freearhey** [comment]
I tried to run the Euronews stream through 3 different apps (VLC, Elmedia Video Player, GSE Smart IPTV) and it didn't work properly in any of them. 

In general I have nothing against YouTube broadcasts, but with the current support in players I think adding them to the playlist will cause more problems than benefits.

**Comment by LaneSh4d0w** [comment]
> I tried to run the Euronews stream through 3 different apps (VLC, Elmedia Video Player, GSE Smart IPTV) and it didn't work properly in any of them.
> 
> In general I have nothing against YouTube broadcasts, but with the current support in players I think adding them to the playlist will cause more problems than benefits.

I'll take a look once i'm available, might be something blocking on your side.

**Comment by link8k** [comment]
> An alternative - we maintain a repository for liveproxy and maintain all those links there. This would also solve the tokenization issue.
> https://github.com/back-to/liveproxy

I like this approach but think liveproxy is hard to setup and will result in a lot of issues being created

**Comment by link8k** [comment]
Thanks everyone for your responses. Maybe it's a good idea to park this and add it in the future once/if more players support it.

FYI: Currently I ran a script on my server to generate IP specific m3u8 links every 4 hours. The disadvantages of this approach is that YouTube rate limits the requests and it stops working.

```
echo '#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="English" tvg-logo="" tvg-country="FR" tvg-url="" group-title="English",France 24 English (YouTube)' >> playlist.m3u8;
streamlink https://www.youtube.com/user/france24english/live best --stream-url >> playlist.m3u8;
```

**Comment by LaneSh4d0w** [comment]
> I tried to run the EuronewsUSA stream through 3 different apps (VLC, Elmedia Video Player, GSE Smart IPTV) and it didn't work properly in any of them.
> 
> UPDATE: "euronews (en español)" (https://www.youtube.com/euronewses/live) stream works in VLC, but also does not work in other players.
> 
> In general I have nothing against YouTube broadcasts, but with the current support in players I think adding them to the playlist will cause more problems than benefits.

Your situation is weird... just tested and it worked for me : 
![image](https://user-images.githubusercontent.com/30985701/108251399-9e7cbb00-7157-11eb-8049-6d958ffbb051.png)

**Comment by LaneSh4d0w** [comment]
> 
> 
> Thanks everyone for your responses. Maybe it's a good idea to park this and add it in the future once/if more players support it.
> 
> FYI: Currently I ran a script on my server to generate IP specific m3u8 links every 4 hours. The disadvantages of this approach is that YouTube rate limits the requests and it stops working.
> 
> ```
> echo '#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="English" tvg-logo="" tvg-country="FR" tvg-url="" group-title="English",France 24 English (YouTube)' >> playlist.m3u8;
> streamlink https://www.youtube.com/user/france24english/live best --stream-url >> playlist.m3u8;
> ```

Yeah it's really difficult to get something in the long-term with YouTube, since you got rate limits and tokenization
