### ISSUE TITLE
Add: Rede Globo  - from BRAZIL

### ISSUE THREAD

**Issue by free-the-web** [iptv-org/iptv#2159]
**Channel Name:** Rede Globo
**Country:** Brazil   pt-br

[http://live.video.globo.com/h/1402196682759012345678915746027599876543210hM4EA1neMoQoIiUyVn1TNg/k/app/a/A/u/anyone/d/s/hls-globo-rj/playlist.m3u8](http://live.video.globo.com/h/1402196682759012345678915746027599876543210hM4EA1neMoQoIiUyVn1TNg/k/app/a/A/u/anyone/d/s/hls-globo-rj/playlist.m3u8)

**Comment by freearhey** [comment]
Closed in favor #1968
