### ISSUE TITLE
algerian channels

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#2163]
can you extract the m3u8 link of the algerians channels from the site : [https://www.htatv.com/](url)

**Comment by freearhey** [comment]
site no longer works
<img width="1440" alt="Captura de pantalla 2021-02-20 a las 14 54 02" src="https://user-images.githubusercontent.com/7253922/108594519-88574080-738b-11eb-8c15-3bfb51a83f5e.png">

**Comment by themak1985** [comment]
I fixed your link @hemzaberkane - but all those channels are tokenized, any m3u8 link we provide will expire in mere hours.
