### ISSUE TITLE
Fix: country list m3u broken

### ISSUE THREAD

**Issue by micha47259** [iptv-org/iptv#2165]
i have a big problem. i use the country m3u (https://iptv-org.github.io/iptv/index.country.m3u)  and since my last update there is chaos .. a few channels appear in near every country und a lot of wrongs channels are into the country list.. something must be broken ..
can you check and fix it please.. never had this issue before

**Comment by freearhey** [comment]
@micha47259 Which channels are you referring to exactly?

**Comment by micha47259** [comment]
ok i try

for example the channel Ada tv is in a lot of groups ..example germany , greece and many more.. also bloomberg , channel v 

it seems that the list are totally broken in some country.. did you change parameters ? never had this problem before 
also all arabic channels appear in evey arabic country ..example abu dhabi tv in iraq list... and also a lot more...



most terrible channel is ada tv in 70 % of the groups or bloomberg

**Comment by freearhey** [comment]
@micha47259 The duplicates should now disappear.
