### ISSUE TITLE
Add: Please Add More Tamil Channels

### ISSUE THREAD

**Issue by AS27-pro** [iptv-org/iptv#2170]
**Channel Name:** VijayTV/StarVijay and SunTV
**Country:** India 
**Language:** Tamil
**External Link (optional):** https://github.com/AsianPingu/Tamil-IPTV
**Notes (optional):** xxx

**Comment by freearhey** [comment]
Please read the [guide](https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#request-a-channel) before making a request.
