### ISSUE TITLE
Bein sport

### ISSUE THREAD

**Issue by zakinho99** [iptv-org/iptv#2175]
Hi everyone, thank you for the work you do.
bein sport channels are available?

**Comment by themak1985** [comment]
@zakinho99 please either edit and reopen your request to follow our [contributing guidelines](https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md) or submit a new request that follows our [contributing guidelines](https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md).
