### ISSUE TITLE
"Helpful Resources" links are linking to an old branch version. 

### ISSUE THREAD

**Issue by themak1985** [iptv-org/iptv#2177]
The link to the contributing guide at the bottom of issues and pull requests as well as in the sidebar under Helpful Resources is linking to an older version of the contributing guidelines and code of conduct. As I understand it, that needs to be changed in the settings.

**Comment by freearhey** [comment]
Fixed https://github.com/iptv-org/iptv/commit/a832d7bba36439c913cf17462994dd6f7da51da9
