### ISSUE TITLE
Africable TV

### ISSUE THREAD

**Issue by kone78** [iptv-org/iptv#2178]
Please can you add AFRICABLE TV a Channel from Mali, this is the link:
https://www.lyngsat.com/tvchannels/ml/Africable-TV.html
**Channel Name: AFRICABLE TV
**Channel ID:** AfricableTV.ml
**Country:** MALI
**Language:** FRENCH
**External Link (optional):https://www.lyngsat.com/tvchannels/ml/Africable-TV.html
**Notes (optional):** xxx

**Comment by freearhey** [comment]
Closed in favor #2190

**Comment by freearhey** [comment]
Closed in favor of #12321
