### ISSUE TITLE
RSI La 1

### ISSUE THREAD

**Issue by YacineBoussoufa** [iptv-org/iptv#2183]
**Channel Name:** RSI La1
**Channel ID:** RSILa1.ch
**Country:** Switzerland
**Language:** Italian
**External Link (optional):** https://www.rsi.ch/play/tv/live?tvLiveId=livestream_La1&channelTitle=la-1
**Notes (optional):** Link available only in Switzerland

**Comment by themak1985** [comment]
Unfortunately we cannot add geolocked streams. Hopefully someone will find one for you that isn't geolocked.

**Comment by freearhey** [comment]
Closed in favor #2222

**Comment by AntiPontifex** [comment]
Dead issue: please close.
