### ISSUE TITLE
RSI La 2

### ISSUE THREAD

**Issue by YacineBoussoufa** [iptv-org/iptv#2184]
**Channel Name:** RSI La2
**Channel ID:** RSILa2.ch
**Country:** Switzerland
**Language:** Italian
**External Link (optional):** https://www.rsi.ch/play/tv/live?tvLiveId=livestream_La2&channelTitle=la-2
**Notes (optional):** Link available only in Switzerland

**Comment by freearhey** [comment]
Closed in favor #2222

**Comment by AntiPontifex** [comment]
Dead issue: please close.
