### ISSUE TITLE
Add: VIVA TV RUSSIA

### ISSUE THREAD

**Issue by vasilyevmichail** [iptv-org/iptv#2185]
**Channel Name:** VIVA TV RUSSIA
**Country:** RUSSIA
**Language:** Russian
**External Link (optional):** http://195.9.195.19:8001/hls2/vivarussia/index.m3u8

#EXTINF:-1 tvg-id="viva-tv-russia" tvg-name="VIVA TV RUSSIA" tvg-country="RU" tvg-language="Russian" tvg-logo="https://i.imgur.com/qCLICfC.jpg" group-title="Music",VIVA TV RUSSIA (720p)
http://195.9.195.19:8001/hls2/vivarussia/index.m3u8

**Comment by freearhey** [comment]
Added via https://github.com/iptv-org/iptv/pull/2188
