### ISSUE TITLE
Add: Diema sport HD

### ISSUE THREAD

**Issue by Haroldyolo** [iptv-org/iptv#2187]
**Channel Name:** Diema sport HD
**Country:** Bulgaria
**Language:** Bulgarian
**External Link (optional):** xxx
**Notes (optional):** Sport Channel

**Comment by Haroldyolo** [comment]
No joy with finding this one then? :(

**Comment by TDLxC2S** [comment]
Try this

Diema Sport One : http://136.243.177.164/DIEMASPORT/playlist.m3u8

Diema Sport Two :
http://136.243.177.164/DIEMASPORT2/playlist.m3u8

**Comment by freearhey** [comment]
@TDLxC2S Thank you for your help! 

Both channels have been added to the playlist.

**Comment by Haroldyolo** [comment]
Both are dead now

**Comment by freearhey** [comment]
@Haroldyolo Yes, you're right. I've already removed those channels from the playlist, but as soon as there are working links we'll bring them back.

**Comment by LaneSh4d0w** [comment]
Found this, but I don't know if that'll work : https://njaqqa3dw3ntwkfr.ezcdn462.net:8443/hls/1nv8w.m3u8?s=FmrpXqGLCTEG0UjQT6WrFg&e=1618158331
