### ISSUE TITLE
Mistake in USA playlist

### ISSUE THREAD

**Issue by Magneticdud** [iptv-org/iptv#2189]
CBC (Canadian channel) is listed erronously as CBS

the line from the m3u:

`#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="US" tvg-language="English" tvg-logo="https://cbsnews2.cbsistatic.com/hub/i/r/2019/04/01/727e357a-a126-4138-a2c5-4d3222669d57/thumbnail/1200x630/795a64db6b16dd5a299672df438ad0b4/cbsn2-logo-1920x1080.jpg" tvg-url="" group-title="News",CBS News`
`https://cbcnewshd-f.akamaihd.net/i/cbcnews_1@8981/index_2500_av-p.m3u8`

as you can see from the URL, it's CBC and not CBS

**Comment by freearhey** [comment]
@Magneticdud Thank you for pointing that out! I moved the channel to the appropriate playlist.
