### ISSUE TITLE
BNN Bloomberg

### ISSUE THREAD

**Issue by DankMemeGuy** [iptv-org/iptv#2195]
**Channel Name:** BNN Bloomberg
**Country:** Canada
**Language:** English
**External Link (optional):** xxx
**Notes (optional):** xxx

**Comment by freearhey** [comment]
Closed in favor #1941

**Comment by Dum4G** [comment]
https://pe-ak-lp01a-9c9media.akamaized.net/live/News1BNNDigi/p/dash/00000001/1bba52dc66e4c68e/manifest.mpd

LUL

**Comment by SciFiDavey** [comment]
I don’t understand, does this mean I can watch Canada’s BNN BLOOMBERG or not and if so, how do I add it?

**Comment by bozzio83** [comment]
Is there a fix for this?
