### ISSUE TITLE
大家的都是非常卡顿的吗？

### ISSUE THREAD

**Issue by lawmankyo** [iptv-org/iptv#2196]
不管我们哪个国家的梯子都是卡顿，大家都都是这样的么？

**Comment by LaneSh4d0w** [comment]
> 
> 
> 不管我们哪个国家的梯子都是卡顿，大家都都是这样的么？

Are you talking about all the channels, or a specific set of channels ? 

Next time, please use a translator, or write your demand in English, please. Might have misunderstood your question due to an use of a translator.
