### ISSUE TITLE
Error when trying to perform the test

### ISSUE THREAD

**Issue by maycovilefort** [iptv-org/iptv#2202]
Error when trying to perform the test!
![image](https://user-images.githubusercontent.com/26335623/109424243-a9d6ae80-79c1-11eb-8553-acd1d9020668.png)

**Comment by freearhey** [comment]
Please check your version of Node.js. As far as I know [Intl.DisplayNames](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#browser_compatibility) support was added only in version 14.0.0.

**Comment by maycovilefort** [comment]
That was exactly the problem, **thanks**!
