### ISSUE TITLE
Add: TVN Panama

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#2204]
#EXTINF:-1 tvg-logo="https://img.streann.com/upload2/1600120466369.png", TVN HD
https://bcovlive-a.akamaihd.net/2f670e324b9b46bba7582e919ed90924/us-east-1/6058004209001/profile_0/chunklist_dvr.m3u8
#EXTINF:-1 tvg-logo="https://507go.tv/imagenes//taxonomy/term/15/logo.png", NEX CANAL 21
http://198.1.123.99:1935/live/myStream/chunklist_w508012443.m3u8

**Comment by freearhey** [comment]
Done.
