### ISSUE TITLE
CBS CHICAGO WBBM-TV 

### ISSUE THREAD

**Issue by nnadie9** [iptv-org/iptv#2214]
**Channel Name:CBS CHICAGO WBBM-TV 
**Country: USA
**Language:ENGLISH 
**External Link (optional):EXTINF:-1,US : CBS (WBBM– Chicago IL)
http://185.232.53.5:2086/arellano/kgtL965n2Y/90252
**Notes (optional):none

**Comment by freearhey** [comment]
Closed in favor #1942

**Comment by nnadie9** [comment]
Is it added ?

**Comment by freearhey** [comment]
@nnadie9 For now, the channel has been added to the list of other American channel requests, which you can see at the link: https://github.com/iptv-org/iptv/issues/1942. But as soon as a working link to its broadcast appears, it will be added to the playlist as well.
