### ISSUE TITLE
Add: Ishtar TV

### ISSUE THREAD

**Issue by MesopotamianGroyper** [iptv-org/iptv#2215]
**Channel Name:** Ishtar TV
**Country:** Iraq
**Language:** Assyrian/Arabic
**External Link (optional):** https://ishtartv.com/stream.html
**Notes (optional):** xxx

**Comment by freearhey** [comment]
The channel is already on the playlist:
https://github.com/iptv-org/iptv/blob/010ee8ed199ef12213985437e287512e591620a5/channels/iq.m3u#L48-L49
