### ISSUE TITLE
Add: KBSV/AssyriaSat

### ISSUE THREAD

**Issue by MesopotamianGroyper** [iptv-org/iptv#2216]
**Channel Name:** KBSV/AssyriaSat
**Country:** United States
**Language:** Assyrian/English
**External Link (optional):** https://www.betnahrain.org/
**Notes (optional):** xxx

**Comment by freearhey** [comment]
Added via https://github.com/iptv-org/iptv/commit/c9302905d07fcbba77f795d70cfc3e89a74a5295
