### ISSUE TITLE
Propose: Clarify Categories & Possibly Change or Add Categories

### ISSUE THREAD

**Issue by themak1985** [iptv-org/iptv#2224]
Some of the categories can be clearly understood by their name, others are open to interpretation. There are also numerous channels that don't fit into one of the categories we have. By defining the categories we have, we might not have to add categories like Nature, Drama, Horror, Art, Culture, Animals, Anime, Anthology, Science, Tech, etc

I am taking a first stab at defining these categories, but would like the community's input. 

Category | Definition
-- | -- 
Auto | Programming related to automobiles.
Business | Programming related to business. 
Classic | Programming is mostly from earlier decades. 
Comedy | Programming is mostly comedy. 
Documentary | Programming that depicts a person, real-world event, cultures, and/or nature.
Education | Programming is intended to be Educational.
Entertainment | **This can be so many things** 
Family | Programming that is considered "Family Friendly"
Fashion | Programming focused on fashion.  **could this be merged with lifestyle?**
Food | Programming related to food.
General | Provides a variety of different programming. **(is this correct?)**
Health | Programming related to health. **currently no channels listed as such**
History | Programming related to real historical events. 
Hobby | Programming related to hobbies such as: **???**
Kids | Programming targeted to children.
Legislative | Government programming specific to the operation of government.
Lifestyle | **This can be so many things, maybe broader Arts/Culture category is better?** 
Local | Channels that are targeted for a local area or region. 
Movies | Channels that only show movies.
Music | Programming is Music or Music related.
News | Programming is mostly News.
Quiz | Programming is mostly Quizzes and Game Shows
Religious | Religious Programming
Sci-Fi | Programming is mostly science fiction
Shop | Programming is for shopping
Sport | Programming is sports
Travel | Programming is travel related.
Weather | Programming is focused on weather.
XXX | Programming is adult oriented and x-rated
Other | No category assigned.

**Comment by LaneSh4d0w** [comment]
> 
> 
> Some of the categories can be clearly understood by their name, others are open to interpretation. There are also numerous channels that don't fit into one of the categories we have. By defining the categories we have, we might not have to add categories like Nature, Drama, Horror, Art, Culture, Animals, Anime, Anthology, Science, Tech, etc
> 
> I am taking a first stab at defining these categories, but would like the community's input.
> Category 	Definition
> Auto 	Programming related to automobiles.
> Business 	Programming related to business.
> Classic 	Programming is mostly from earlier decades.
> Comedy 	Programming is mostly comedy.
> Documentary 	Programming that depicts a person, real-world event, cultures, and/or nature.
> Education 	Programming is intended to be Educational.
> Entertainment 	**This can be so many things**
> Family 	Programming that is considered "Family Friendly"
> Fashion 	Programming focused on fashion. **could this be merged with lifestyle?**
> Food 	Programming related to food.
> General 	Provides a variety of different programming. **(is this correct?)**
> Health 	Programming related to health. **currently no channels listed as such**
> History 	Programming related to real historical events.
> Hobby 	Programming related to hobbies such as: **???**
> Kids 	Programming targeted to children.
> Legislative 	Government programming specific to the operation of government.
> Lifestyle 	**This can be so many things, maybe broader Arts/Culture category is better?**
> Local 	Channels that are targeted for a local area or region.
> Movies 	Channels that only show movies.
> Music 	Programming is Music or Music related.
> News 	Programming is mostly News.
> Quiz 	Programming is mostly Quizzes and Game Shows
> Religious 	Religious Programming
> Sci-Fi 	Programming is mostly science fiction
> Shop 	Programming is for shopping
> Sport 	Programming is sports
> Travel 	Programming is travel related.
> Weather 	Programming is focused on weather.
> XXX 	Programming is adult oriented and x-rated
> Other 	No category assigned.

Few things : 

Comedy and Entertainment sounds like the same thing.
Hobby is... well... a bit difficult to say. I don't know much "hobby" channels for the moment (apart from Chasse & Pêche in France as an example)
General is, as said, general programming. A "normal" programmation per se (some news, some tele-films, some documentaries, things adapted to everyone)

**Comment by Sphinxroot** [comment]
personaly i would put all xxx link in one  xxx.m3u  maybe add tag  of country  for them | FR   if needed

**Comment by themak1985** [comment]
What if we did the following:

Category | Definition
-- | -- 
Auto | Cars, Motorcycles, and other automobiles.
Animation | Anime, Cartoons, and similar.
Business | Business
Classic | Shows and Movies from earlier decades. 
Comedy | Comedy
Documentary | Provides record or report of history, people, animals, real-world event, & cultures.
Drama | Drama
Education | Educational
Food | Food
General | Variety of Programs
Horror | Horror
Kids | Programming that is considered "Family Friendly" or targeted to children.
Legislative | Specific to the operation of government.
Lifestyle | Health and fitness, tourism, leisure, fashion, decor, or pop culture.
Local | Targeted for a local area or region. 
Movies | Only Movies
Music | Music or Music related.
News | News
Quiz | Quizzes and Game Shows
Religious | Religious
Sci-Fi | Science Fiction
Shop | Shopping
Sport | Sports
Tech | Science and Technology
Weather | Weather
XXX | Adult or explicit. 
Other | No category fits.

Remove the following: 
Category | Reason for removal
-- | -- 
Fashion | Merge with lifestyle
Health | Merge with Lifestyle
History | Programming related to real historical events. 
Entertainment | Too vague.
Hobby | too vague
Family | Merge with kids.
Travel | merge with lifestyle

**Comment by freearhey** [comment]
I personally would prefer to keep the following:

Category | Definition | Examples
-- | -- | --
Fashion | Fashion-related channels‎ | FashionTV, World Fashion Channel, HDFashion & LifeStyle
History | Channels about history | Historia, History, H2, Viasat History
Entertainment | Channels with a variety of entertainment programs | TLC, MTV, BBC Entertainment
Hobby | Channels about fishing, hunting, etc. | Outdoor Channel, Охота и рыбалка, Рыболов
Family | Channels with family-oriented movies and shows | ABC family, JOJ Family, Fox Family Movies
Travel | Travel channels | Russian Travel Guide, Travel Channel, Travel XP

and add:

- Anime
- Crime
- Drama
- Horror

In general, I see no problem with having many categories, as long as each category contains at least a dozen channels from around the world. Or am I missing something?

**Comment by LaneSh4d0w** [comment]
*snip*

Few remarks :

-> Fashion is often seen as a way of life (as on dressing up, you can say it is a way of life, like anything), so I kind of wonder why we can't fusion it with Lifestyle.

-> History for me is OK
-> Entertainment, as said, is too vague. Movies are entertainment, TV Shows are entertainment etc etc... I think we should fusion it with "General". Adult entertainment goes to XXX.
-> Hobby is OK for me, as long as the definition keeps up with what you said.
-> Family for me is OK.
-> Travel for me is OK.

Anime is animation, which is also entertainment for me. I suppose we can keep it as is.
Crime/Drama/Horror ? I suppose those goes to movies or general if talking about TV shows related to this (I suppose you're referring to the A&E channels). Why not do a "Parental Advisory / General" section about that ?

**Comment by themak1985** [comment]
> In general, I see no problem with having many categories, as long as each category contains at least a dozen channels from around the world. Or am I missing something?

I guess I am thinking of the user experience and the idea of [Overchoice](https://en.wikipedia.org/wiki/Overchoice) but I am open to expanding and let the user filter, though I think we have to better define the categories.

- I still find entertainment to be an odd category. I would place MTV and TLC as lifestyle, and BBC Entertainment as General. 
- I am not sure what the difference between history and documentary is, most of the content on history channels are documentaries. Maybe we get rid of documentary and just do History and include documentaries in the description. 
- Maybe we also change hobby to Outdoor as a category, for all the outdoor, wildlife and nature channels. Outdoor is more intuitive than Hobby.

**Comment by freearhey** [comment]
@themak1985 As for the "Entertainment" and "Hobby" categories, you definitely convinced me. The same goes for adding the Lifestyle category and merging the History category with Documentary.

The only thing I would limit the Outdoor category to channels devoted to different types of outdoor activities, and channels about nature and animals I would put in the Documentary category.

As for merging the "Fashion" and "Lifestyle" categories, if you think it's necessary, let's do it.

The only thing I would still like to keep is "Family" and "Travel". Also, I think we still need to add categories:
- Anime
- Crime
- Drama
- Horror

P.S. Maybe you will make a draft of PR with a list of all the categories and their descriptions, and we'll discuss the rest of the details there?

**Comment by themak1985** [comment]
> P.S. Maybe you will make a draft of PR with a list of all the categories and their descriptions, and we'll discuss the rest of the details there?
 You got it 😄

**Comment by freearhey** [comment]
@AntiPontifex We do not add radio streams without video to the playlist. So if you see such links somewhere, let us know and we'll remove them.

**Comment by AntiPontifex** [comment]
Pardon me, but I'm just trying to understand these categories. Does Network IPTV (i.e. BBC, NBC, CBC) go in the General category? *confused*

**Comment by Dum4G** [comment]
Crime, Drama and Horror fall into Movies category. Anime and some other channels should fall into Cartoons category (Adult Swim and 2x2 were not meant for kids). I don't see Cooking category which is self-explainatory
