### ISSUE TITLE
Fix: TF1 (720p) French channel

### ISSUE THREAD

**Issue by jo-a11y** [iptv-org/iptv#2225]
***Channel Name: TF1 (720p)
***Broken Link (from playlist):
 _ https://iptv-org.github.io/iptv/index.language.m3u (grouped by language)
 _ https://iptv-org.github.io/iptv/index.country.m3u (grouped by country)

***Possible Replacement (optional): TF1 (HD) m3u lists "all channels" or "grouped" by category "
***Notes (optional): In the main m3u link "all channels" and in the m3u link https://iptv-org.github.io/iptv/index.category.m3u (grouped by category) : TF1 (HD) works fine.
I think there is just to recover the flow of these m3u to put the same in the m3u grouped by language or by country.

**Comment by trancer1994** [comment]
TF1 (720p) seems to be geolocked now outside France, as it's giving me a 403 error when accessing it from the UK. If TF1 (HD) works fine though you could replace it with that. I'm not sure what anyone else thinks, but that's personally what I've found for now.

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-id="TF1.fr" tvg-name="TF 1 FR" tvg-logo="https://i.ibb.co/M8GjLmy/TF1.png" group-title="",TF1  Dead Link
https://tf1-hls-live-ssl.tf1.fr/tf1/1/hls/live.m3u8

#EXTINF:-1 tvg-id="TF1.fr" tvg-name="TF 1 FR" tvg-logo="https://i.ibb.co/M8GjLmy/TF1.png" group-title="France",TF1 (720P)
https://tf1-hls-live-ssl.tf1.fr/tf1/1/hls/live_2328.m3u8

#EXTINF:-1 tvg-id="TF1.fr" tvg-name="TF 1 FR" tvg-logo="https://i.ibb.co/M8GjLmy/TF1.png" group-title="France",TF1 (OPT-2) (576p)
http://cdn.webtv4.cdnfr.orange.fr/hs/HALO3/hls/tech_tf1_ott_mobile-155120/hls/index.m3u8

**Comment by jo-a11y** [comment]
Do I have an action to do to help on my side?

The tf1.fr site is normally geolocated if you take the stream directly from here.

**Comment by freearhey** [comment]
Links updated.

**Comment by rojasjordi02-spec** [comment]
https://github.com/iptv-org/iptv/issues/new/choose
