### ISSUE TITLE
Add: Azam sports 2

### ISSUE THREAD

**Issue by shimbijt** [iptv-org/iptv#2229]
**Channel Name:** Azam Sports 2
**Country:** Tanzania
**Language:** Swahili&English
**External Link (optional):** xxx
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
Won't be easy. According to their Instagram (???), this is a satellite Pay-to-Watch TV service, with the only entrypoint being an app in which you need to log in to access their content.

**Comment by shimbijt** [comment]
> Won't be easy. According to their Instagram (???), this is a satellite Pay-to-Watch TV service, with the only entrypoint being an app in which you need to log in to access their content.

Sure i have even an Account, but I fail on how to Extract the links, Is it some kind of Man in the middle Attack?

**Comment by LaneSh4d0w** [comment]
> 
> 
> > Won't be easy. According to their Instagram (???), this is a satellite Pay-to-Watch TV service, with the only entrypoint being an app in which you need to log in to access their content.
> 
> Sure i have even an Account, but I fail on how to Extract the links, Is it some kind of Man in the middle Attack?

Probably some sort of SSL pinning being active.

**Comment by freearhey** [comment]
Added via https://github.com/iptv-org/iptv/commit/cbd8874bf2be22767d842102cdc5dd0e372daccd

**Comment by ahmedzooo** [comment]
Please add zbc2 and azam 1 and azam 2
