### ISSUE TITLE
Remove:  please delete these porn, thank you.

### ISSUE THREAD

**Issue by youhun00** [iptv-org/iptv#2234]
***Channel Name:*** /channels/cn.m3u

https://156zy.suyunbo.tv/***/playlist.m3u8

The videos under these domains are some adult videos, please delete these porn video links, thank you.

http://vip.yingshidaqian.com/****/index.m3u8

The videos under these domains are invalid videos, please delete these video links, thank you.

**Comment by freearhey** [comment]
@youhun00 Thank you for bringing this to our attention! All links have been removed.
