### ISSUE TITLE
Add: 广州综合频道

### ISSUE THREAD

**Issue by LimeZky** [iptv-org/iptv#2243]
**Channel Name:** 广州综合频道
**Country:** P.R.China
**Language:** Chinese
**External Link (optional):** https://www.gztv.com/tvfile/tv.html

**Comment by LaneSh4d0w** [comment]
It sounds like a tokened stream, but I didn't see the data move yet.

https://aplays.gztv.com/live/zhonghes.m3u8?txTime=604D302E&txSecret=fb38b34b90cd3faf7b269914f644ad9c

**Comment by Nintendocustom** [comment]
https://iptv--iptv.repl.co/Chinese/

**Comment by LaneSh4d0w** [comment]
> 
> 
> https://iptv--iptv.repl.co/Chinese/

Thanks for your implication, I tried but it doesn't seem to work.

I, however, found this : https://www.gztv.com/gztv/api/tv/zhonghe

**Comment by Sphinxroot** [comment]
it work in kodi 

#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="地方",广州综合
http://149.129.100.78/gztv.php?id=zhonghe
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="地方",广州南国都市
http://149.129.100.78/gztv.php?id=shenghuo
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="地方",广州新闻
http://149.129.100.78/gztv.php?id=xinwen
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="地方",广州竞赛
http://149.129.100.78/gztv.php?id=jingsai
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="地方",广州影视
http://149.129.100.78/gztv.php?id=yingshi
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="地方",广州法治
http://149.129.100.78/gztv.php?id=fazhi

more china channel here https://github.com/goolguy007/radioer/blob/cde67264e4a9029a54d7aa206f65215278a51169/TVradio.m3u

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-id="" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/yingyufudao.png" group-title="广东",广州南国都市
http://120.221.226.226/aplay.gztv.com/sec/shenghuos.m3u8
#EXTINF:-1 tvg-id="" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/yingyufudao.png" group-title="广东",广州影视
http://120.221.226.226/aplay.gztv.com/sec/yingshi.m3u8
#EXTINF:-1 tvg-id="" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/yingyufudao.png" group-title="广东",广州新闻
http://120.221.226.226/aplay.gztv.com/sec/xinwen.m3u8
#EXTINF:-1 tvg-id="" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/yingyufudao.png" group-title="广东",广州法治
http://120.221.226.226/aplay.gztv.com/sec/fazhi.m3u8
#EXTINF:-1 tvg-id="" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/yingyufudao.png" group-title="广东",广州竞赛
http://120.221.226.226/aplay.gztv.com/sec/jingsai.m3u8
#EXTINF:-1 tvg-id="" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/yingyufudao.png" group-title="广东",广州综合
http://120.221.226.226/aplay.gztv.com/sec/zhonghe.m3u8

**Comment by LaneSh4d0w** [comment]
> 
> 
> it work in kodi
> 
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="地方",广州综合
> http://149.129.100.78/gztv.php?id=zhonghe
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="地方",广州南国都市
> http://149.129.100.78/gztv.php?id=shenghuo
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="地方",广州新闻
> http://149.129.100.78/gztv.php?id=xinwen
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="地方",广州竞赛
> http://149.129.100.78/gztv.php?id=jingsai
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="地方",广州影视
> http://149.129.100.78/gztv.php?id=yingshi
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="地方",广州法治
> http://149.129.100.78/gztv.php?id=fazhi
> 
> more china channel here https://github.com/goolguy007/radioer/blob/cde67264e4a9029a54d7aa206f65215278a51169/TVradio.m3u

Those work for me too.

**Comment by LaneSh4d0w** [comment]
> 
> 
> #EXTINF:-1 tvg-id="" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/yingyufudao.png" group-title="广东",广州南国都市
> http://120.221.226.226/aplay.gztv.com/sec/shenghuos.m3u8
> #EXTINF:-1 tvg-id="" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/yingyufudao.png" group-title="广东",广州影视
> http://120.221.226.226/aplay.gztv.com/sec/yingshi.m3u8
> #EXTINF:-1 tvg-id="" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/yingyufudao.png" group-title="广东",广州新闻
> http://120.221.226.226/aplay.gztv.com/sec/xinwen.m3u8
> #EXTINF:-1 tvg-id="" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/yingyufudao.png" group-title="广东",广州法治
> http://120.221.226.226/aplay.gztv.com/sec/fazhi.m3u8
> #EXTINF:-1 tvg-id="" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/yingyufudao.png" group-title="广东",广州竞赛
> http://120.221.226.226/aplay.gztv.com/sec/jingsai.m3u8
> #EXTINF:-1 tvg-id="" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/yingyufudao.png" group-title="广东",广州综合
> http://120.221.226.226/aplay.gztv.com/sec/zhonghe.m3u8

Those ones do not, though.

**Comment by Nintendocustom** [comment]
@LaneSh4d0w try it again.

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w try it again.
> 
> 

It seems to answer. 👍 Tested with the last one and answered positive.

**Comment by freearhey** [comment]
Added via https://github.com/iptv-org/iptv/commit/c8f71ee3d2b1b213c70378ab3f83a62e51232334
