### ISSUE TITLE
Fix: xxx

### ISSUE THREAD

**Issue by exigente82** [iptv-org/iptv#2248]
***Channel Name:*** Rai Sport
***Broken Link (from playlist):*** https://everyrai-lh.akamaihd.net/i/raisportjolly1_1@177967/master.m3u8
***Possible Replacement (optional):*** xxx
***Notes (optional):*** xxx

**Comment by freearhey** [comment]
Broken link removed via https://github.com/iptv-org/iptv/commit/478ac68d5253506e81b7e4813be7244c76470522

Closed in favor #2173
