### ISSUE TITLE
Duplicated Rai News

### ISSUE THREAD

**Issue by exigente82** [iptv-org/iptv#2249]
On it.m3u, Rai News:

#EXTINF:-1 tvg-id="Rai News 24 IT" tvg-name="Rai News 24 IT" tvg-country="IT" tvg-language="Italian" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Rai_News_24.svg/1920px-Rai_News_24.svg.png" group-title="News",Rai News 24 (576p)
https://mediapolisevent.rai.it/relinker/relinkerServlet.htm?cont=0000001
#EXTINF:-1 tvg-id="RaiNews24.it" tvg-name="Rai News 24" tvg-country="IT" tvg-language="Italian" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Rai_News_24.svg/1920px-Rai_News_24.svg.png" group-title="News",Rai News 24 (576p)
https://rainews1-live.akamaized.net/hls/live/598326/rainews1/rainews1/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
Two different servers operating, that is why :)
