### ISSUE TITLE
Add: СТБ

### ISSUE THREAD

**Issue by srnjak** [iptv-org/iptv#2254]
I noticed, that channels from IP 188.35.9.11 are broken. One of them is СТБ.

***Channel Name:*** СТБ
***Broken Link (from playlist):*** ua.m3u
***Possible Replacement (optional):*** xxx
***Notes (optional):*** xxx

**Comment by freearhey** [comment]
@srnjak Thanks for the report! The broken link has already been removed from the playlist via https://github.com/iptv-org/iptv/commit/4a72045019365f3a2170314339911188413a954f. As soon as a working link appears, we'll bring the channel back.

**Comment by freearhey** [comment]
Closed in favor #2346
