### ISSUE TITLE
A2Z Channel 11

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#2255]
**Channel Name:** A2Z
**Channel ID:** A2ZChannel11.ph
**Country:** Philippines
**Language:** Tagalog
**External Link (optional):** xxx
**Notes (optional):** Free to air channel in the Philippines.

**Comment by freearhey** [comment]
Closed in favor #1967

**Comment by luke026** [comment]
Do u have of this url

**Comment by freearhey** [comment]
Closed in favor of #12319
