### ISSUE TITLE
DZRJ-DTV

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#2256]
**Channel Name:** RJ DigiTV
**Channel ID:** RJTV.ph
**Country:** Philippines
**Language:** Tagalog
**External Link (optional):** xxx
**Notes (optional):** Free to air channel in the Philippines.

**Comment by freearhey** [comment]
Closed in favor #1967

**Comment by LaneSh4d0w** [comment]
https://stream.rjtv.stream/live/smil:rjtv.smil/playlist.m3u8 ?

**Comment by freearhey** [comment]
Closed in favor of #12318
