### ISSUE TITLE
Aksyon TV International

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#2257]
**Channel Name:** AksyonTV International
**Channel ID:** AksyonTVInternational.ph
**Country:** Philippines
**Language:** Tagalog
**External Link (optional):** xxx
**Notes (optional):** Sister channel of Kapatid Channel

**Comment by freearhey** [comment]
Closed in favor #1967

**Comment by freearhey** [comment]
Closed in favor of #12317
