### ISSUE TITLE
Fix: J2 in yue language

### ISSUE THREAD

**Issue by CSUDerrick** [iptv-org/iptv#2259]
***Channel Name:***  J2
***Broken Link (from playlist):*** yue.m3u
***Possible Replacement (optional):*** xxx
***Notes (optional):*** xxx

**Comment by freearhey** [comment]
@CSUDerrick Thanks for the report. 

The link is replaced by https://github.com/iptv-org/iptv/commit/9843002c32f7b7b09722b56b06e8138025c6f8a0
