### ISSUE TITLE
Hallypop

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#2272]
**Channel Name:** GMA Hallypop/Hallypop Philippines
**Channel ID:** Hallypop.ph
**Country:** Philippines
**Language:** English/Korean
**External Link (optional):** xxx
**Notes (optional):** Free to air local version of Hallypop in the Philippines.

**Comment by freearhey** [comment]
Closed in favor #1967

**Comment by freearhey** [comment]
Closed in favor of #12315
