### ISSUE TITLE
Heart of Asia

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#2273]
**Channel Name:** Heart of Asia
**Channel ID:** HeartofAsiaChannel.ph
**Country:** Philippines
**Language:** Tagalog
**External Link (optional):** xxx
**Notes (optional):** Free to air channel in the Philippines.

**Comment by freearhey** [comment]
Closed in favor #1967

**Comment by freearhey** [comment]
Closed in favor of #12314
