### ISSUE TITLE
I Heart Movies

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#2274]
**Channel Name:** I Heart Movies
**Channel ID:** IHeartMovies.ph
**Country:** Philippines
**Language:** Tagalog
**External Link (optional):** xxx
**Notes (optional):** Free to air movie channel in the Philippines.

**Comment by freearhey** [comment]
Closed in favor #1967

**Comment by freearhey** [comment]
Closed in favor of #12313
