### ISSUE TITLE
One News

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#2275]
**Channel Name:** One News
**Channel ID:** OneNews.ph
**Country:** Philippines
**Language:** Tagalog
**External Link (optional):** xxx
**Notes (optional):** Free to air news channel in the Philippines.

**Comment by freearhey** [comment]
Closed in favor #1967

**Comment by amirattalla** [comment]
Please  motherfucker don’t send me any mails

**Comment by freearhey** [comment]
Closed in favor of #12312
