### ISSUE TITLE
Tech Storm

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#2276]
**Channel Name:** TechStorm
**Channel ID:** TechStorm.sg
**Country:** Singapore
**Language:** English
**External Link (optional):** xxx
**Notes (optional):** e-Sports/tech channel.

**Comment by freearhey** [comment]
Closed in favor #1983

**Comment by F640** [comment]
https://cdn-telkomsel-01.akamaized.net/Content/HLS/Live/channel(abe4ead2-1a88-4330-9f41-382fcf94bba2)/index.m3u8
Here is the link, but it's geo-blocked to Indonesia.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/198d0527f073c81119ccceaebdede8e79f542028/streams/sg.m3u#L28-L29
