### ISSUE TITLE
Add: arti tv

### ISSUE THREAD

**Issue by erkanaydemir** [iptv-org/iptv#2279]
**Channel Name:** Arti Tv
**Country:** TUR
**Language:** TUR
**External Link (optional):** https://artitv.tv/
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
https://www.youtube.com/watch?v=NGnjeruSar4

https://www.youtube.com/c/ArtiTv_Resmi/live

cant be added  exept if someone re stream the feed to .m3u8 stream

**Comment by freearhey** [comment]
Closed in favor #1946
