### ISSUE TITLE
Add: San Marino RTV

### ISSUE THREAD

**Issue by YacineBoussoufa** [iptv-org/iptv#2281]
**Channel Name:** San Marino RTV
**Country:** San Marino
**Language:** italian
**External Link (optional):** xxx
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
# https://www.sanmarinortv.sm/programmi/web-tv
#EXTINF:-1 tvg-id="sanmarinortv.sm" tvg-name="San Marino RTV" tvg-country="IT" tvg-language="Italian" tvg-logo="https://i.imgur.com/lJpOlLv.png" group-title="",San Marino RTV
https://d2hrvno5bw6tg2.cloudfront.net/smrtv-ch01/_definst_/smil:ch-01.smil/chunklist_b1692000_slita.m3u8
https://d2hrvno5bw6tg2.cloudfront.net/smrtv-ch01/_definst_/smil:ch-01.smil/playlist.m3u8
#EXTINF:-1 tvg-id="sanmarinortv.sm" tvg-name="San Marino RTV Sport" tvg-country="IT" tvg-language="Italian" tvg-logo="https://i.imgur.com/PGm944g.png" group-title="Sport",San Marino RTV Sport
https://d2hrvno5bw6tg2.cloudfront.net/smrtv-ch02/_definst_/smil:ch-02.smil/chunklist_b542000_slita_t64TUQoMzYwcCk=.m3u8
https://d2hrvno5bw6tg2.cloudfront.net/smrtv-ch02/_definst_/smil:ch-02.smil/playlist.m3u8

**Comment by freearhey** [comment]
Added via https://github.com/iptv-org/iptv/commit/38364c612a93a0e4dac9927bf0adfe711d9527f5

**Comment by fparri** [comment]
The Link for 'San Marino RTV Sport' has changed to:

https://d2hrvno5bw6tg2.cloudfront.net/smrtv-ch02/_definst_/smil:ch-02.smil/chunklist_b1692000_slita.m3u8ù

and the resolution is now 720p

**Comment by freearhey** [comment]
@fparri Thanks! Link replaced in #5487
