### ISSUE TITLE
Request ChannelsAdd: Brazil

### ISSUE THREAD

**Issue by tomasmaia2099** [iptv-org/iptv#2285]
**Channel Name:** Cartoon Network, Telecine, Syfy, Premiere, Sportv, Combat, Hbo, Fox Sports, Discovery Kids, Sony, Axn
**Country:** Brazil
**Language:** Portuguese Brazil
**External Link (optional):** xxx
**Notes (optional):** xxx

**Comment by freearhey** [comment]
Please read the [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel) next time before posting request.
