### ISSUE TITLE
Demande: identifiant et mot de passe

### ISSUE THREAD

**Issue by UlrichNguemkam** [iptv-org/iptv#2286]

**Comment by Sphinxroot** [comment]
quelle est ta demande reelement ?

**Comment by UlrichNguemkam** [comment]
L'application que j'utilise pour lire les liens et fichiers de type "m3u"
demande un nom d'utilisateur et un mot de passe pour se connecter au
serveur qui héberge de dit lien ou fichier.

Le ven. 26 mars 2021 à 06:53, Sphinxroot ***@***.***> a
écrit :

**Comment by Sphinxroot** [comment]
possiblement que justement cette application est payante ... alors je crois pas quil sois possible de t aider car si ta demande est d avoir un crack pour ton app cest pas la bonne place ... y a plein d application gratuite pour toute les sortes de platforme ...  pour simplement lire un fichier m3u  et ca malheuresement rien avoir avec ce git .. car ici cest des liens gratuit de streaming tv

**Comment by UlrichNguemkam** [comment]
Vous n'avez pas compris mon problème. Je ne veux pas un crack (c'est mal de
cracker une application). Déjà que c'est une application gratuite
Merci tout de même🙏

Le ven. 26 mars 2021 à 21:16, Sphinxroot ***@***.***> a
écrit :

**Comment by Sphinxroot** [comment]
alors eleborer un peu plus .. quelle est l application conserner .. car la je ne suis plus trop la problematique ... si je comprens bien ta une application gratuite et la liste m3u est egaelement gratuite mais ont te demande un login ?

**Comment by UlrichNguemkam** [comment]
L'application c'est "IPTV Smarters", elle est disponible sur toutes les
plates formes. Le lien m3u c'est celui du projet iptv-org/iptv.

Ci-joint le tutoriel de l'application

Le ven. 26 mars 2021 à 21:56, Sphinxroot ***@***.***> a
écrit :

**Comment by Sphinxroot** [comment]
ok iptv smarter pro est plutot utiliser pour ceux qui ont un abonnement a un service iptv  sois ok2 edges et ou plein d autres  la plus facile pour regarder en distant est d utiliser vlc  .. ouvrir un flux  reseau  et entrer https://raw.githubusercontent.com/iptv-org/iptv/master/index.m3u  ensuite choisir la station dans la liste de lecture

**Comment by UlrichNguemkam** [comment]
OK merci

Le ven. 26 mars 2021 à 23:05, Sphinxroot ***@***.***> a
écrit :
