### ISSUE TITLE
Brazil Request Channels

### ISSUE THREAD

**Issue by tomasmaia2099** [iptv-org/iptv#2293]
Country: Brazil
Language: Portuguese, Brazil

Channels List: Fox Sports, Sportv, Premiere, Cartoon Network, Syfy, Combate, AMC, HBO, Sony, Axn, Telecine, Discovery channel
Animal Planet,  Discovery Kids

cheers to all.

**Comment by freearhey** [comment]
Discovery channel, Animal Planet, Discovery Kids can not be added to the playlist due to claims of the rights holder (https://github.com/iptv-org/iptv/issues/1831)

**Comment by freearhey** [comment]
Closed in favor #1968 and #1942
