### ISSUE TITLE
Add: JapanTV #2

### ISSUE THREAD

**Issue by TDLxC2S** [iptv-org/iptv#2300]
**Channel Name:** 
WOWOW Cinefil
Animax ( Vietnamese Sub )
**Country:** Japan
**Language:** Japan
**External Link (optional):** 
Wowow Cinefil : http://203.162.235.41:16916
Animax ( Vietnamese Sub ) : https://livecdn.fptplay.net/hda3/animaxport_2000.stream/chunklist_b250000.m3u8
**Notes (optional):**

**Comment by freearhey** [comment]
Added via https://github.com/iptv-org/iptv/commit/431c99bedfb512c0e2b4ca0a8c4eb4d26c7adaaa
