### ISSUE TITLE
Add: Win Sports+

### ISSUE THREAD

**Issue by berserklegion** [iptv-org/iptv#2301]
**Channel Name:** win sports plus
**Country:** Colombia
**Language:** Spanish
**External Link (optional):** xxx
**Notes (optional):** There are 2 channels win sports ans win sports plus +

**Comment by berserklegion** [comment]
Would you mind to add the channel win sports + from Colombia, thanks

**Comment by LaneSh4d0w** [comment]
Looking at it.

**Comment by LaneSh4d0w** [comment]
It seems this channel is pay per view (Win Sports Mas) and satellite-only (Win Sports). It will be difficult to get something from it.

**Comment by berserklegion** [comment]
That's right this win sports + is paid, I though there would be any chance to get it 😪

**Comment by LaneSh4d0w** [comment]
Not saying there's no chance, but it will be sort of difficult. Nevertheless, I'll look at what I can do.

**Comment by berserklegion** [comment]
Cheers, I thank you for that, looking forward to it

**Comment by berserklegion** [comment]
Hi Lane, any news from this please?

**Comment by LaneSh4d0w** [comment]
> Hi Lane, any news from this please?

Searched for it, but no results for the moment. Since it's a pay-per-view service, i don't think we could see something coming from it.

**Comment by freearhey** [comment]
Added.

**Comment by Robertom230** [comment]
Anyone find it

**Comment by LaneSh4d0w** [comment]
> Anyone find it

http://181.236.192.254:8000/playlist.m3u8 | CO | Telebucaramanga Colombia

it's inside

**Comment by Robertom230** [comment]
I don’t have that

**Comment by Canner47** [comment]
Enlace completamente caído, roto, revisar por favor

**Comment by BellezaEmporium** [comment]
> Enlace completamente caído, roto, revisar por favor

Aqui : 

#EXTINF:-1,Win Sports HD
http://190.60.39.198:8000/play/a033/index.m3u8
#EXTINF:-1,Win Sports+ HD
http://190.60.39.198:8000/play/a0b6/index.m3u8

**Comment by Canner47** [comment]
Nuevamente caído, gracias

**Comment by BellezaEmporium** [comment]
> Nuevamente caído, gracias 

Hay Win+ aca : http://181.78.24.67:8010/playlist.m3u8

**Comment by ElMakia** [comment]
Win Sport + aqui
http://181.78.24.67:8010/play/a05w/index.m3u8

**Comment by Josephmunoz07** [comment]
Alguien con win + se cayó

**Comment by R4IN2007** [comment]
Ya encontré unos astra links que tiene los Canales de Win y de Win Sports / Win Sports+

**Comment by eriuus** [comment]
Podrias compartir el link actualizado

**Comment by Josephmunoz07** [comment]
Comparte link

**Comment by R4IN2007** [comment]
Este es de Win Sports
http://179.1.132.203:8000/play/a034/index.m3u8

**Comment by R4IN2007** [comment]
Win Sports+
http://186.148.163.18:8000/play/a043/index.m3u8

**Comment by R4IN2007** [comment]
A ver si todavía funcionan.
Los tuve durante un mes entero y los enlaces funcionaban bien.

**Comment by eriuus** [comment]
Gracias. sabes si es posible descargar la url m3u8 desde esta web?

https://tucanaldeportivo.com/winmas.php

**Comment by R4IN2007** [comment]
si pero me muestra un error
https://e11.ainakwalajeen.com:999/hls/winlive.m3u8?md5=hC5Xjv66oU9e8Qo2ilxYFA&expires=1700024349

**Comment by BellezaEmporium** [comment]
No puede funcionar en otra IP que no sea la tuya. Entonces, si deseas ver este canal, debes creer un enlace que se puede generar con su IP actual.

**Comment by BellezaEmporium** [comment]
https://ddy5.hlsjs.ru/ddy5/premium392/index.mpd (referer https://weblivehdplay.ru/) should give you Win Sports +

**Comment by eriuus** [comment]
Gracias por tu ayuda. Funciono!

**Comment by ElMakia** [comment]
Win Sport + SD= http://proiptvdigic.com:8080/pandconv3/HTVFuZ5PePNG/197666

Win Sport + HD= http://proiptvdigic.com:8080/pandconv3/HTVFuZ5PePNG/197667

Win Sport + 4K= http://proiptvdigic.com:8080/pandconv3/HTVFuZ5PePNG/197668

**Comment by Luifertecno** [comment]
Hola alguien sabe el link actual de Win Sport+

**Comment by Korsinemi** [comment]
Found this: **https://edge2.ttlpro.futbol/live/STbf43800c9e15d56.m3u8**
(on **https://tutlehd2.xyz/online.php?a=3305**)

**Comment by HOOBYAR** [comment]
Alguien puede tener la URL/Win+
Este es el canal que más debemos tener todos aquí

**Comment by eriuus** [comment]
Hola, puedes probar los siguientes:

http://emuligl.info:8080/live/CwcspkjCgzeZ/m5mknNRdkmc9/197668.m3u8
http://emuligl.info:8080/live/CwcspkjCgzeZ/m5mknNRdkmc9/241344.m3u8

**Comment by alicemsu** [comment]
I would like to get this channel...
https://ddy5.hlsjs.ru/ddy5/premium392/index.mpd
This link works, but it is too short.

**Comment by alicemsu** [comment]
This one also works but there is no sound.
http://186.148.163.18:8000/play/a043/index.m3u8

**Comment by DaniJay10** [comment]
THANK YOUUUUUUUUU

**Comment by BellezaEmporium** [comment]
> I would like to get this channel...
> https://ddy5.hlsjs.ru/ddy5/premium392/index.mpd
> This link works, but it is too short.

"Too short" in which way ? I know it works on my side.

**Comment by alicemsu** [comment]
> > I would like to get this channel...
> > https://ddy5.hlsjs.ru/ddy5/premium392/index.mpd
> > This link works, but it is too short.
> 
> "Too short" in which way ? I know it works on my side.

https://youtu.be/03ISeG5u9pQ

**Comment by BellezaEmporium** [comment]
Oh I see. You're referring to connection issues.

I can check for other links, though I don't think I'll get any better (or stable) links than this. I used to have an official Win Sports + link, but it went down a few months ago.

**Comment by alicemsu** [comment]
I would appreciate it if you found it. As I mentioned earlier, there is one with good video quality, but unfortunately, it has no sound. The one we wrote about has sound, but it cuts off too much.

**Comment by BellezaEmporium** [comment]
> I would appreciate it if you found it. As I mentioned earlier, there is one with good video quality, but unfortunately, it has no sound. The one we wrote about has sound, but it cuts off too much.

http://181.188.216.148:8001/play/a056 ?

**Comment by alicemsu** [comment]
> > I would appreciate it if you found it. As I mentioned earlier, there is one with good video quality, but unfortunately, it has no sound. The one we wrote about has sound, but it cuts off too much.
> 
> http://181.188.216.148:8001/play/a056 ?

It works perfectly, I can confirm. Greetings and thank you very much. It should be uploaded to the IPTV GitHub page. This channel is important for Colombian sports, but unfortunately, it is a paid service.

**Comment by Delta-Pxx** [comment]
Aun sigue funcionando sin ningún problema (audio y video) OK

--------> http://186.148.163.18:8000/play/a043/index.m3u8

**Comment by alicemsu** [comment]
> Aun sigue funcionando sin ningún problema (audio y video) OK
> 
> --------> http://186.148.163.18:8000/play/a043/index.m3u8

Previously, the audio was not working, but I noticed that it is now working perfectly. The link provided by BellezaEmporium has stopped working.

**Comment by BellezaEmporium** [comment]
Sadly that's the issue with Astra links. Both of them (mine and Delta's ones) are reliant on some person managing them. One filter and you can't watch them.

**Comment by alicemsu** [comment]
> > Aun sigue funcionando sin ningún problema (audio y video) OK
> > --------> http://186.148.163.18:8000/play/a043/index.m3u8
> 
> Previously, the audio was not working, but I noticed that it is now working perfectly. The link provided by BellezaEmporium has stopped working.

By the way, it seems that this depends on the type of program you use to stream the channel. "mytv.best" does not play the sound, so I highly recommend using SS IPTV on TVs.

**Comment by alicemsu** [comment]
> > Aun sigue funcionando sin ningún problema (audio y video) OK
> > --------> http://186.148.163.18:8000/play/a043/index.m3u8
> 
> Anteriormente, el audio no funcionaba, pero noté que ahora funciona perfectamente. El enlace proporcionado por BellezaEmporium ha dejado de funcionar.

By the way, regarding the sound issue, it seems that this depends on the type of program you use to transmit or produce the channel. In my case, I have a television and was using "mytv.best", and it didn't play the sound, so I highly recommend using "ss-iptv.com" on televisions as there is no sound problem. (If there is another application that surpasses sstv for LG TVs, please recommend it as well).

**Comment by alicemsu** [comment]
> > Aun sigue funcionando sin ningún problema (audio y video) OK
> > --------> http://186.148.163.18:8000/play/a043/index.m3u8
> 
> Previously, the audio was not working, but I noticed that it is now working perfectly. The link provided by BellezaEmporium has stopped working.

By the way, regarding the sound issue, it seems that this depends on the type of program you use to transmit or produce the channel. In my case, I have a television and was using "mytv.best", and it didn't play the sound, so I highly recommend using "ss-iptv.com" on televisions as there is no sound problem. (If there is another application that surpasses sstv for LG TVs, please recommend it as well).

**Comment by alicemsu** [comment]
> Sadly that's the issue with Astra links. Both of them (mine and Delta's) are reliant on some person managing them. One filter and you can't watch them.
> 
> P.S : just change 8001 to 8000.

I hope the link continues to work correctly, fortunately it hasn't had any issues so far and I'm watching the Copa America matches calmly. Greetings brother and have a good rest of the day.

**Comment by BellezaEmporium** [comment]
ES : Yo personalmente utilizo Televizo en mi pantalla, pero es un Android TV
EN : I personally use Televizo in my TV, but it's an Android TV.

As said earlier, a simple port change makes it work.

**Comment by alicemsu** [comment]
> ES : Yo personalmente utilizo Televizo en mi pantalla, pero es un Android TV EN : I personally use Televizo in my TV, but it's an Android TV.
> 
> As said earlier, a simple port change makes it work.

Thank you for the information, I just tested it and now it works correctly. 🙏

**Comment by alicemsu** [comment]
> Sadly that's the issue with Astra links. Both of them (mine and Delta's) are reliant on some person managing them. One filter and you can't watch them.
> 
> P.S : just change 8001 to 8000.

Thank you for the information, I just tested it and now it works correctly. 🙏

**Comment by Kiwev** [comment]
> > > Aun sigue funcionando sin ningún problema (audio y video) OK
> > > --------> http://186.148.163.18:8000/play/a043/index.m3u8
> > 
> > 
> > Previously, the audio was not working, but I noticed that it is now working perfectly. The link provided by BellezaEmporium has stopped working.
> 
> By the way, regarding the sound issue, it seems that this depends on the type of program you use to transmit or produce the channel. In my case, I have a television and was using "mytv.best", and it didn't play the sound, so I highly recommend using "ss-iptv.com" on televisions as there is no sound problem. (If there is another application that surpasses sstv for LG TVs, please recommend it as well).

How do you correctly connect this channel in SS IPTV? I'm trying with an "external playlist" and pasting the URL, but it isn't working. :(

**Comment by alicemsu** [comment]
EXTM3U
#EXTINF:-1 tvg-id="Win Sports+" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/8/8e/WinSportsPlusPremium.png/revision/latest?cb=20200225220524&path-prefix=es" group-title="General",Win Sports+
http://186.148.163.18:8000/play/a043/index.m3u8

**Comment by alicemsu** [comment]
@Kiwev You can create a file ending in .m3u and then select it from the application's webpage.

**Comment by alicemsu** [comment]
> EXTM3U #EXTINF:-1 tvg-id="Win Sports+" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/8/8e/WinSportsPlusPremium.png/revision/latest?cb=20200225220524&path-prefix=es" group-title="General",Win Sports+ http://186.148.163.18:8000/play/a043/index.m3u8

Go to this page https://ss-iptv.com/en/users/playlist. First, enter the code that you get from the application that is already on your TV. Then, select the .m3u file that I am providing and finally, save the changes and restart the application. The channel will be on the list.
![Screenshot_2024-07-09-13-39-44-795_com android chrome-edit](https://github.com/iptv-org/iptv/assets/106787183/dabec4b7-d1f8-4256-b1ae-635f05343ac4)

**Comment by Kiwev** [comment]
> EXTM3U
> #EXTINF:-1 tvg-id="Win Sports+" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/8/8e/WinSportsPlusPremium.png/revision/latest?cb=20200225220524&path-prefix=es" group-title="General",Win Sports+
> http://186.148.163.18:8000/play/a043/index.m3u8

You're a genius, thank you so much! <3<3<3<3<3<3<3<3

**Comment by alicemsu** [comment]
@BellezaEmporium Friend, do you have any links to Direct TV Sport that you can provide me? I have searched high and low for this channel and can't find anything. Thanks in advance.

**Comment by alicemsu** [comment]
I will leave two additional links in case some of the links that are currently functional fail in the future.

#EXTINF:-1 tvg-id="winsports" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/7/7b/Win_Sport_logo.png" group-title="General",Win Sport
http://181.78.71.5:4890/play/a02x/index.m3u8

#EXTINF:-1 tvg-id="winsports+" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/8/8e/WinSportsPlusPremium.png/revision/latest?cb=20200225220524&path-prefix=es" group-title="General",Win Sports+
http://181.78.6.106:45000/play/a014

**Comment by alicemsu** [comment]
I will leave two additional links in case some of the links that are currently functional fail in the future.

Win Sport HD (adaptive)
http://179.1.132.203:8000/play/a034/index.m3u8

Win Sports+ HD (1080)
http://181.78.6.106:45000/play/a014

**Comment by alicemsu** [comment]
> > @BellezaEmporiumAmigo, tienes algún link de DIRECTV Sports que me puedas facilitar? He buscado por todos lados este canal y no encuentro nada. Gracias de antemano.
> 
> No sé si tengo eso en mis listados, pero esto está empezando a estar fuera del tema.

Well, I hope I don't cause any inconvenience. I wish I could get it. Greetings.

**Comment by JesusGonzalez21** [comment]
Hello, does anyone know what happened with this -http://186.148.163.18:8000/play/a043/index.m3u8 yesterday it worked but today it doesn't work, help

**Comment by ferchinhp** [comment]
> I will leave two additional links in case some of the links that are currently functional fail in the future.
> 
> Win Sport HD (adaptive) http://179.1.132.203:8000/play/a034/index.m3u8
> 
> Win Sports+ HD (1080) http://181.78.6.106:45000/play/a014

Last week the + was ok. It's not working anymore. None of the links posted in the comments are working.
:(((((((

**Comment by iamsantii** [comment]
Hi, http://186.148.163.18:8000/play/a043/index.m3u8 is not working

**Comment by Danielmc9** [comment]
hola, http://186.148.163.18:8000/play/a043/index.m3u8 ya no esta disponible, alguien te tengo nuevo acceso por favor

**Comment by ferchinhp** [comment]
I've found a SD signal.
I don't know if I'm exaggerating, but I`ve encrypted the URL in order to prevent bots.
Just google "devglan text encryption" (first coincidence). Copy and paste this text in section "Text Decryption" (password below):

ledabXyNUbXgVEbcQg6GPM07IE52UGT3xPBiDNkmxLjxd/Pr6F8E0B5NAMkLu3pI

L0P4g4r4SuM4dr3

I hope someone can provide a HD signal

**Comment by becruza** [comment]
> It works correctly. http://186.148.163.18:8000/play/a043/index.m3u8

Any idea what is the source of this? Is it some iptv paid service? It worked flawlessly if I remember correctly, great quality almost no delay.

----------
Tienen idea de donde es este canal? Hasta donde recuerdo tenía buena calidad y no tanto delay (algunos segundos), si es algún servicio de iptv y mantiene esa calidad estoy interesado, gracias!

**Comment by BellezaEmporium** [comment]
> > It works correctly. http://186.148.163.18:8000/play/a043/index.m3u8
> 
> Any idea what is the source of this? Is it some iptv paid service? It worked flawlessly if I remember correctly, great quality almost no delay.
> 
> ----------
> Tienen idea de donde es este canal? Hasta donde recuerdo tenía buena calidad y no tanto delay (algunos segundos), si es algún servicio de iptv y mantiene esa calidad estoy interesado, gracias!

The IP was registered in the "TV Azteca Sucursal Colombia" pool of IPs. That might give you a clue.

**Comment by BellezaEmporium** [comment]
> I've found a SD signal. I don't know if I'm exaggerating, but I`ve encrypted the URL in order to prevent bots. Just google "devglan text encryption" (first coincidence). Copy and paste this text in section "Text Decryption" (password below):
> 
> ledabXyNUbXgVEbcQg6GPM07IE52UGT3xPBiDNkmxLjxd/Pr6F8E0B5NAMkLu3pI
> 
> L0P4g4r4SuM4dr3
> 
> I hope someone can provide a HD signal

http://186.190.231.179:8000/play/a05g/index.m3u8 lol

**Comment by ferchinhp** [comment]
> > I've found a SD signal. I don't know if I'm exaggerating, but I`ve encrypted the URL in order to prevent bots. Just google "devglan text encryption" (first coincidence). Copy and paste this text in section "Text Decryption" (password below):
> > ledabXyNUbXgVEbcQg6GPM07IE52UGT3xPBiDNkmxLjxd/Pr6F8E0B5NAMkLu3pI
> > L0P4g4r4SuM4dr3
> > I hope someone can provide a HD signal
> 
> http://186.190.231.179:8000/play/a05g/index.m3u8 lol

We love u 💘

**Comment by MarxistSoldier** [comment]
As of now, the last list is down. 
Could you please update it?

**Comment by DaniJay10** [comment]
> As of now, the last list is down. Could you please update it?

to me the http://186.190.231.179:8000/play/a05g/index.m3u8 works perfectametne although from time to time it crashes. I can also recommend that you look in telegram some version of MagisTv free of malware and you can also see it there. I got it from Crack Heros.

**Comment by Cosmic-R** [comment]
> > As of now, the last list is down. Could you please update it?
> 
> to me the http://186.190.231.179:8000/play/a05g/index.m3u8 works perfectametne although from time to time it crashes. I can also recommend that you look in telegram some version of MagisTv free of malware and you can also see it there. I got it from Crack Heros.

Unfortunately it seems it doesnt work anymore, last day i checked if it was still working was last Thursday, today Saturday its completely dead,

**Comment by spulido743** [comment]
Se cayó el día viernes, alguien por favor que nos ayude con una nueva ruta

**Comment by BellezaEmporium** [comment]
> I've found a SD signal. I don't know if I'm exaggerating, but I`ve encrypted the URL in order to prevent bots. Just google "devglan text encryption" (first coincidence). Copy and paste this text in section "Text Decryption" (password below):
> 
> ledabXyNUbXgVEbcQg6GPM07IE52UGT3xPBiDNkmxLjxd/Pr6F8E0B5NAMkLu3pI
> 
> L0P4g4r4SuM4dr3
> 
> I hope someone can provide a HD signal

I can confirm his link still works... not directly what he gave, but moving a bit further... ;)

**Comment by BellezaEmporium** [comment]
Here... i'll do like him.

JecaYQn47mh/KIsabIHS4y7I9Tc/2WK/Ewz9iVI146wwVzR6eVoWRm4Ed1X/Y0pB

N0_C0mPr3nD0_L4_Fr4sE

**Comment by spulido743** [comment]
Ese tampoco funciona

**Comment by BellezaEmporium** [comment]
![image](https://github.com/user-attachments/assets/5024ca7e-1df6-4518-a19b-916da7c43e7d)

**Comment by spulido743** [comment]
![imagen_2024-12-15_121456628](https://github.com/user-attachments/assets/0eff5656-8684-4bc5-8fac-dafcf11d880a)
![image](https://github.com/user-attachments/assets/c90d967b-e5e6-4339-919c-fe6acd0b3c6a)

ambas no responde el canal

**Comment by BellezaEmporium** [comment]
> ![imagen_2024-12-15_121456628](https://private-user-images.githubusercontent.com/118694265/395879750-0eff5656-8684-4bc5-8fac-dafcf11d880a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyODMyNzAsIm5iZiI6MTczNDI4Mjk3MCwicGF0aCI6Ii8xMTg2OTQyNjUvMzk1ODc5NzUwLTBlZmY1NjU2LTg2ODQtNGJjNS04ZmFjLWRhZmNmMTFkODgwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxNzE2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWYyNDkxMGQyNDE0NGJmYjcxNjg0YTM2M2E3NDk5ODcwNTY3NjRhNDcxYjljYmViYmRlYzI0MzU5YmUxNDk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vr1Juz2DA2Tjw7mrMRivFtNpDGvXpGUuOBfgGIBpiUw) ![image](https://private-user-images.githubusercontent.com/118694265/395879754-c90d967b-e5e6-4339-919c-fe6acd0b3c6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyODMyNzAsIm5iZiI6MTczNDI4Mjk3MCwicGF0aCI6Ii8xMTg2OTQyNjUvMzk1ODc5NzU0LWM5MGQ5NjdiLWU1ZTYtNDMzOS05MTljLWZlNmFjZDBiM2M2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxNzE2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmZlMjhjZmNkN2E2ZjlmMWZiN2I2MDc3ZWY1NDQyYTY3OGU1NDUwN2VjNGRiOGE5ZmQ3MTJmYzcxMjQzNzc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ydde8S1d8LWobpmh8Y55xpAkZ1wMbuawCGCuSIcTJIg)
> 
> ambas no responde el canal

Well it's quite precise, the link you're looking for is inside the playlist. There's multiple channels in it, including what you're looking for.

Otherwise you can try this : 

https://xyzdddd.mizhls.ru/lb/premium392/index.m3u8
Referer: https://cookiewebplay.xyz/

**Comment by spulido743** [comment]
Sorry, it didn't work for me. The channel is working in low quality, but from a different link.

**Comment by Cosmic-R** [comment]
> Here... i'll do like him.
> 
> JecaYQn47mh/KIsabIHS4y7I9Tc/2WK/Ewz9iVI146wwVzR6eVoWRm4Ed1X/Y0pB
> 
> N0_C0mPr3nD0_L4_Fr4sE

This one works but sadly its in SD and for some reason it buffers a lot

**Comment by BellezaEmporium** [comment]
![image](https://github.com/user-attachments/assets/ee440cbe-c47b-4356-a493-7babd19a36c2)
I don't know... lol.

**Comment by Cosmic-R** [comment]
i mean yeah it loads, that its on SD its not really an issue is that it buffers a lot, a smart tv with an app for iptv playlists sometimes it stops playing at all, and on an android and windows pc sometimes it just says the source cannot be opened/played and moves on to the next item in the playlist

so atleast on my end it buffers a lot, dunno about yours or other users

i mean yeah even then its better than nothing, maybe the server its being hosted on its getting overloaded ?

**Comment by ferchinhp** [comment]
> I've found a SD signal. I don't know if I'm exaggerating, but I`ve encrypted the URL in order to prevent bots. Just google "devglan text encryption" (first coincidence). Copy and paste this text in section "Text Decryption" (password below):
> 
> ledabXyNUbXgVEbcQg6GPM07IE52UGT3xPBiDNkmxLjxd/Pr6F8E0B5NAMkLu3pI
> 
> L0P4g4r4SuM4dr3
> 
> I hope someone can provide a HD signal

Found another one:

7dJVGUvakW7SqS8c/X4dD5Xfr1V75iLQyzbMJ/0m76/tmIOjEFgVhLDdKlJhoAW7

L0P4g4r4SuM4dr3Otr4V3z

**Comment by spulido743** [comment]
Don't you have one that's more stable? That one crashes occasionally

**Comment by santi8301** [comment]
hola una pregunta yo ya tengo el de win sporots+ este es miren el que tengo http://186.190.231.179:8000/play/a05g/index.m3u8 pero necesito ayuda por que nose como poner mis canales en iptv ayuda porfa

**Comment by spulido743** [comment]
Tienes que buscar un aplicación compatible con el dispositivo yo uso ssiptv, acá te dejo un video https://www.youtube.com/watch?v=JstT0YxIhDc

**Comment by santi8301** [comment]
necesito ayuda quien tiene la url de win sports+ es que tenia se daño

**Comment by DaniJay10** [comment]
> necesito ayuda quien tiene la url de win sports+ es que tenia se daño
> 

A veces dejan de funcionar por un tiempo y luego se reestablencen

**Comment by ferchinhp** [comment]
> I've found a SD signal. I don't know if I'm exaggerating, but I`ve encrypted the URL in order to prevent bots. Just google "devglan text encryption" (first coincidence). Copy and paste this text in section "Text Decryption" (password below):
> 
> ledabXyNUbXgVEbcQg6GPM07IE52UGT3xPBiDNkmxLjxd/Pr6F8E0B5NAMkLu3pI
> 
> L0P4g4r4SuM4dr3
> 
> I hope someone can provide a HD signal

Found anoother one (SD):

NSJuU/dnvE1zhN0H8D0ow+P8Eo09BZQox9oqUWFHP7P8OpaCqabtozLJ6Ooujynz
L0P4g4r4SuM4dr3Otr4V3z

**Comment by almelo123** [comment]
Win Sports SD: http://181.78.208.25:2600/play/a01f/index.m3u8

**Comment by almelo123** [comment]
Win+SD: 177.8.76.2:8000/play/a0as

**Comment by pcanon1024** [comment]
Completed list http://177.8.76.2:8000/playlist.m3u8

**Comment by R4IN2007** [comment]
A bunch of Win Sports+ astras go offline because of lack of management or
lots of people using all at once making it very saturated.
Se muere el canal por mucho saturación por mucha gente que lo usa y luego
también las listas astras tienen una falta de mantenimiento y por eso no
duran

**Comment by becruza** [comment]
> Completed list http://177.8.76.2:8000/playlist.m3u8

Hey, that's a good list you got there, may I ask where is this from? Just want to know in case it goes offline, is this a paid service?

**Comment by estebanramirez13** [comment]
> > Completed list http://177.8.76.2:8000/playlist.m3u8
> 
> Hey, that's a good list you got there, may I ask where is this from? Just want to know in case it goes offline, is this a paid service?

It’s not working for me. Is it working for you?

**Comment by becruza** [comment]
> > > Completed list http://177.8.76.2:8000/playlist.m3u8
> > 
> > 
> > Hey, that's a good list you got there, may I ask where is this from? Just want to know in case it goes offline, is this a paid service?
> 
> It’s not working for me. Is it working for you?

Is working right now, but it goes offline sometimes.

As said before I guess is the lack of maintenance, sometimes it works flawlessly, sometime it freezes.

**Comment by spulido743** [comment]
No sirve

**Comment by almelo123** [comment]
> No sirve

SD: 206.62.161.192:8000/play/a0di/index.m3u8
HD: 206.62.161.192:8000/play/a0h0/index.m3u8

**Comment by estebanramirez13** [comment]
no me sirvio

**Comment by almelo123** [comment]
SD 206.62.161.192:8000/play/a0di/index.m3u8
HD 206.62.161.192:8000/play/a0h0/index.m3u8

Anteponer a la dirección el http://

**Comment by estebanramirez13** [comment]
Hola. asi lo he probado y no me abre ninguna lista de canales en ss iptv. esta enlace necesita de algun proceso distinto a los otros enlaces de iptvs para usarse?

**Comment by R4IN2007** [comment]
Están todos saturados pero ando buscando nuevos lista para Win Sports+

**Comment by ferchinhp** [comment]
> Hola. asi lo he probado y no me abre ninguna lista de canales en ss iptv. esta enlace necesita de algun proceso distinto a los otros enlaces de iptvs para usarse?

Sí tiene la lista de canales: 206.62.161.192:8000/playlist.m3u
A veces se puede poner lento porque se saturan.

**Comment by elm3u** [comment]
> > ¿Alguien lo encontró?
> 
> http://181.236.192.254:8000/playlist.m3u8 | CO | Telebucaramanga Colombia (Movistar Colombia)
> 
> Esta dentro

hola si sirve la lista pero todos los canales estan sin audio

**Comment by elm3u** [comment]
> 206.62.161.192:8000/playlist.m3u

hola me salen todos los canales sin audio

**Comment by R4IN2007** [comment]
Estas listas todavia funcionan?

**Comment by BellezaEmporium** [comment]
> Estas listas todavia funcionan?

No, depiende de usuarios que tienen el programo Astra, un sistema de conversión satelito -> rtmp. Es como Tvheadend, pero solo por el satelito.

**Comment by Rayo-Dev10** [comment]
¿Algún héroe con un listado funcional?

**Comment by spulido743** [comment]
http://206.62.161.192:8000/play/a0hi/index.m3u8
http://206.62.161.192:8000/playlist.m3u

Ya no funciona ninguna ayuda 📲

**Comment by spulido743** [comment]
Hola algun listado de deportes que tenga win? 

http://177.8.76.2:8000/playlist.m3u8 este está caido

**Comment by almelo123** [comment]
> Hola algun listado de deportes que tenga win?
> 
> http://177.8.76.2:8000/playlist.m3u8 este está caido

intentar con: 104.238.222.251:8989/280080_.m3u8
poner el http:// al inicio

**Comment by rene26203-ctrl** [comment]
Hola algun listado de deportes que tenga win?

Hace ratos todas las listas de aqui estan caidas... 104.238.222.251:8989/280080_.m3u8 funciona, pero tiene retraso

**Comment by almelo123** [comment]
> Hola algun listado de deportes que tenga win?
> 
> Hace ratos todas las listas de aqui estan caidas... 104.238.222.251:8989/280080_.m3u8 funciona, pero tiene retraso

intentar con: 181.78.74.146:18000/play/a03g
recordar poner el http:// al inicio

**Comment by andresosky18** [comment]
no funciona :(

**Comment by Delta-Pxx** [comment]
**¡¡El ultimo link que se compartió sigue funcionando!!**

**Comment by Camilo2220099** [comment]
> > Hola algun listado de deportes que tenga win?
> > Hace ratos todas las listas de aqui estan caidas... 104.238.222.251:8989/280080_.m3u8 funciona, pero tiene retraso
> 
> intentar con: 181.78.74.146:18000/play/a03g recordar poner el http:// al inicio

Ya no funciona este

**Comment by WilkinsCoffeeArchives** [comment]
yo tengo uno

**Comment by Camilo2220099** [comment]
> yo tengo uno

Lo puede compartir por favor?

**Comment by WilkinsCoffeeArchives** [comment]
Si

**Comment by WilkinsCoffeeArchives** [comment]
https://github.com/iptv-org/iptv/issues/35219
aqui

**Comment by rene26203-ctrl** [comment]
Tenemos Win+ pero alguien tiene un listado de deportes? Con ESPN, Fox, Win, TyC Sports

Por favor compartir, se han tenido varios pero se han caído los listados

**Comment by WilkinsCoffeeArchives** [comment]
ESPN está bloqueado aquí

**Comment by almelo123** [comment]
intentar con: 190.60.37.118:4000/play/a0bw
recordar poner el http:// al inicio
