### ISSUE TITLE
Add: xxx

### ISSUE THREAD

**Issue by Tanvirdkg** [iptv-org/iptv#2306]
9XM #1608
 & TV #1608
 Aakaash Aath #1608 #1565
 ABP Ananda #1565
 airtel #1459
 AKD Calcutta News #1565
 ASIANET #1645
 ASIANET MOVIES #1645
 B4U Movies India #1608
 Bangla Talkies #1608 #1565
 Bangla Time TV #1565
 Cartoon Network India #854
 Channel 10 #1565
 Chutti TV #1599
 Colors kannada #1273
 Colors #1608
 Colors Bangla #1608 #1565
 Colors Cineplex #1608
 Colors Infinity #1608
 Colours Tamil #1715 #1599
 Dangal TV #1608
 DD Bangla #1565
 Dhoom Music #1565
 Dighvijay News 24x7 #1273
 Disney Channel India #709 #854
 Enterr 10 Bangla #1565
 High News #1565
 History TV 18 #1608
 Hungama TV #709 #854 #1317
 Jalsha Movies #1608 #1565
 jio #1459
 Kalaignar TV #1599
 Khushboo TV Bangla #1565
 Kolkata TV #1565
 Marvel HQ #854
 MTV India #1621
 News 18 Kannada #1273
 News 18 Bengali #1565
 NDTV Good Times #1608
 Nickelodeon India #1565
 One #1599
 Public Movies #1273
 Pogo #1608
 Rupasi Bangla #1608 #1565
 SAB TV #1317
 Sangeet Bangla #1608 #1565
 SURYA_TV #1645
 SET India #1608
 Sonic Nickelodeon #1565
 Sony Aath #1608 #1565
 Sony Max India #359 #1608
 Sony Max 2 #1608
 Sony Pix #1608
 Sony SAB TV India #1608
 Sony Six #1608
 Sony Ten 1 #1608
 Sony Ten 2 #1608
 Sony Ten 3 #1608
 Sony Yay! #1565
 Star Bharat India #1608
 Star Gold India #1608
 Star Jalsha #854 #1608 #1565
 Star Movies India #1608
 Star Plus India #1608
 Star Sports 1 #1608
 Star Sports 2 #1608
 Star Sports 3 #1608
 Star Sports Select HD1 #1608
 Star Sports Select HD2 #1608
 Star World India #1608
 Sun Bangla #1565
 Sun Music #1599
 Sun tv #1715 #1599
 Raj Musix Kannada #1273
 Tamilone #1715
 tatasky #1459
 TV9 Kannada #1273
 Travelxp HD #1608
 Vijay TV/Star Vijay #1715
 Zee 24 Ghanta #1565
 Zee Action #1608
 Zee Bangla #1608 #1565
 Zee Bangla Cinema #1608 #1565
 Zee Cinema Asia #1608 #2109
 Zee Cinema Middle East #2036
 Zee Kannada #1273
 Zee tamil #1715
 Zing Asia #1608
 Zoom #1608

**Comment by Sphinxroot** [comment]
9XM #1608 
#EXTINF:-1 tvg-logo="https://i.imgur.com/fD7wLka.jpg" group-title="MUSIC",9xM (480P)
http://d2q8p4pe5spbak.cloudfront.net/bpk-tv/9XM/9XM.isml/index.m3u8
#EXTINF:-1 tvg-logo="https://i.imgur.com/fD7wLka.jpg" group-title="MUSIC",9xM (480P)
http://d2q8p4pe5spbak.cloudfront.net/bpk-tv/9XM/9XM.isml/9XM-audio_208482_und=208000-video=877600.m3u8

ABP Ananda #1565 https://bengali.abplive.com/live-tv 
#EXTINF:-1 tvg-logo="https://cdn.abplive.com/logo/ananda_600x60_bg.png" group-title="New",ABP Ananda (720p)
https://d3pnfn2zxtq6km.cloudfront.net/out/v1/c77a35d9d4f74371a3cf0f214a9eb8c0/index.m3u8
https://d3pnfn2zxtq6km.cloudfront.net/out/v1/c77a35d9d4f74371a3cf0f214a9eb8c0/index_4.m3u8

AKD Calcutta News #1565 https://calcuttanews.tv/
#EXTINF:-1 tvg-logo="https://calcuttanews.tv/images/cnwotag.png" group-title="New",CN Live News (540p)
https://d39iawgzv3h0yo.cloudfront.net/out/v1/1ef4344a3b4a41908915d58ac7bd5e23/index.m3u8
https://d39iawgzv3h0yo.cloudfront.net/out/v1/1ef4344a3b4a41908915d58ac7bd5e23/index_14.m3u8


ASIANET #1645 https://www.asianetnews.com/live-tv
#EXTINF:-1 tvg-logo="https://static.asianetnews.com/v1/images/malayalam-live-tv.jpg" group-title="New",ASIANET News Live
https://vidcdn.vidgyor.com/asianet-origin/liveabr/playlist.m3u8
https://vidcdn.vidgyor.com/asianet-origin/liveabr/asianet-origin/live2/chunks.m3u8

#EXTINF:-1,Asianet News
http://103.199.161.254/Content/asianetnews/Live/Channel(Asianetnews)/index.m3u8

#EXTINF:-1 tvg-logo="https://static.asianetnews.com/v1/images/malayalam-live-tv.jpg" group-title="New",ASIANET News (Audio Only)
https://vidcdn.vidgyor.com/asianet-origin/audioonly/playlist.m3u8
https://vidcdn.vidgyor.com/asianet-origin/audioonly/chunks.m3u8

ASIANET https://hindi.asianetnews.com/live-tv
#EXTINF:-1 tvg-logo="https://static.asianetnews.com/v1/images/hindi-logo.png" group-title="New",Hindy Live
https://vidcdn.vidgyor.com/ibc24-origin/live1/playlist.m3u8
https://vidcdn.vidgyor.com/ibc24-origin/live1/chunks.m3u8

ASIANET https://bangla.asianetnews.com/live-tv
#EXTINF:-1 tvg-logo="https://static.asianetnews.com/v1/images/bangla_logo.png" group-title="New",Bangla Live
https://vidcdn.vidgyor.com/rplus-origin/rplusasianetlive/playlist.m3u8
https://vidcdn.vidgyor.com/rplus-origin/rplusasianetlive/rplus-origin/live1/chunks.m3u8

ASIANET https://tamil.asianetnews.com/live-tv
#EXTINF:-1 tvg-logo="https://static.asianetnews.com/v1/images/tamil_logo.png" group-title="New",Tamil Live
https://vidcdn.vidgyor.com/ptm-origin/aslive/playlist.m3u8
https://vidcdn.vidgyor.com/ptm-origin/aslive/chunks.m3u8

ASIANET https://kannada.asianetnews.com/live-tv
#EXTINF:-1 tvg-logo="https://static.asianetnews.com/v1/images/asianet_suvarna_news.png" group-title="New",Kannada News Live
https://vidcdn.vidgyor.com/suvarna-origin/liveabr/playlist.m3u8
https://vidcdn.vidgyor.com/suvarna-origin/liveabr/suvarna-origin/live1/chunks.m3u8


Dighvijay News 24x7 #1273 https://www.vijayavani.net/
#EXTINF:-1 tvg-logo="https://i.imgur.com/wdE7gxU.png" group-title="New",Dighvijay News
https://vidcdn.vidgyor.com/dighvijay-origin/liveabr/playlist.m3u8
https://vidcdn.vidgyor.com/dighvijay-origin/liveabr/dighvijay-origin/live1/chunks.m3u8


News 18 Kannada #1273 https://kannada.news18.com/live-tv/ 
#EXTINF:-1 tvg-logo="" group-title="New",News 18 Kannada
https://news18kannada-lh.akamaihd.net/i/n18kannada_1@372918/index_4_av-p.m3u8?sd=10&rebase=on

News 18 Bengali #1565 https://bengali.news18.com/live-tv/
#EXTINF:-1 tvg-logo="" group-title="New",News 18 Bengali
https://news18bangla-lh.akamaihd.net/i/n18bangla_1@2289/index_4_av-p.m3u8?sd=10&rebase=on

if needed :
all news 18 channel can be taken if /index_4_av-p.m3u8?sd=10&rebase=on is used it bypass the expirable token /master.m3u8 stream

https://hindi.news18.com/livetv/
https://news18india-lh.akamaihd.net/i/news18india_1@174951/index_4_av-p.m3u8?sd=10&rebase=on

https://punjab.news18.com/live-tv/
https://news18haryana-lh.akamaihd.net/i/n18punjabhimhar_1@349009/index_4_av-p.m3u8?sd=10&rebase=on

https://hindi.news18.com/livetv/news18-rajasthan/
https://news18rajasthan-lh.akamaihd.net/i/n18raj_1@175738/index_4_av-p.m3u8?sd=10&rebase=on

https://hindi.news18.com/livetv/news18-uttar-pradesh-uttarakhand/
https://news18up-lh.akamaihd.net/i/n18upuk_1@175735/index_4_av-p.m3u8?sd=10&rebase=on

https://hindi.news18.com/livetv/news18-madhya-pradesh-chhattisgarh/
https://news18mp-lh.akamaihd.net/i/n18mpcg_1@175737/index_4_av-p.m3u8?sd=10&rebase=on

https://hindi.news18.com/livetv/news18-bihar-jharkhand/
https://news18bihar-lh.akamaihd.net/i/n18biharjh_1@175736/index_4_av-p.m3u8?sd=10&rebase=on

https://gujarati.news18.com/
https://news18gujarati-lh.akamaihd.net/i/n18gujarat_1@370955/index_4_av-p.m3u8?sd=10&rebase=on

https://odia.news18.com/
https://etv-oriya.akamaized.net/i/n18odia_1@179753/index_4_av-p.m3u8?sd=10&rebase=on

https://urdu.news18.com/live-tv/
https://news18urdu-lh.akamaihd.net/i/n18urdu_1@373059/index_4_av-p.m3u8?sd=10&rebase=on

https://malayalam.news18.com/live-tv/
https://news18kerala-lh.akamaihd.net/i/n18kerala_1@526583/index_4_av-p.m3u8?sd=10&rebase=on

https://tamil.news18.com/live-tv/
https://news18tamil-lh.akamaihd.net/i/n18tamil_1@526595/index_4_av-p.m3u8?sd=10&rebase=on

https://assam.news18.com/live-tv/
https://news18assam-lh.akamaihd.net/i/n18assamne_1@526575/index_4_av-p.m3u8?sd=10&rebase=on

########

TV9 Kannada #1273 https://tv9kannada.com/live-tv
#EXTINF:-1 tvg-logo="https://d2jo35ozacw6sq.cloudfront.net/wp-content/uploads/2018/04/Tv9-Kannada.png" group-title="New",TV9 Kannada
https://vidcdn.vidgyor.com/tv9kannada-origin/live/playlist.m3u8
https://vidcdn.vidgyor.com/tv9kannada-origin/live/tv9kannada-origin/live1/chunks.m3u

other:most of the channel are on airtelxstream.in (login required) or yupptv (Token stream) or geo

**Comment by freearhey** [comment]
Closed in favor #1934

**Comment by freearhey** [comment]
@Sphinxroot Thanks!
