### ISSUE TITLE
Can someone crack this japan iptv service ?

### ISSUE THREAD

**Issue by YunomiSakura** [iptv-org/iptv#2311]
so okay , i have an license code from japannettv service called 'NewHome' , if have 74+ channel and 30 days VOD , i tried buy 1$ trial . So , i have it , but idk dumped to get Tv channel . Can someone dumped this ?

if u can crack , dm me in discord LuongSeno#7708

![Screenshot_20210330-191000.png](https://user-images.githubusercontent.com/76716526/112986334-8f901c00-918b-11eb-8cfe-210975a05c4f.png)

![Screenshot_20210330-191000.png](https://user-images.githubusercontent.com/76716526/112986358-97e85700-918b-11eb-919a-1d3d5c9d4e84.png)

![PicsArt_03-30-07.12.50.png](https://user-images.githubusercontent.com/76716526/112986643-f31a4980-918b-11eb-840e-ab2df9d53921.png)

**Comment by LaneSh4d0w** [comment]
> 
> 
> so okay , i have an license code from japannettv service called 'NewHome' , if have 74+ channel and 30 days VOD , i tried buy 1$ trial . So , i have it , but idk dumped to get Tv channel . Can someone dumped this ?
> 
> if u can crack , dm me in discord LuongSeno#7708

To be honest, I also have got that program, and you just need something like Fiddler or Charles to look after it. I could even see the login and register, only thing is it seems it is encrypted.
