### ISSUE TITLE
Fix: TV Tokyo

### ISSUE THREAD

**Issue by TheOneTold** [iptv-org/iptv#2313]
***Channel Name:*** TV Tokyo
***Broken Link (from playlist):*** http://redlabmcdn.s.llnwi.net/jp01/ryowa6/index.m3u8
***Possible Replacement (optional):*** xxx
***Notes (optional):***

**Comment by LaneSh4d0w** [comment]
It seems that all the Ryowa links got down, they answer but no audio/video output

**Comment by freearhey** [comment]
@TheOneTold Thanks for letting us know! The broken link has been removed. And as soon as a replacement appears, we will bring channel back.

**Comment by freearhey** [comment]
Closed in favor #1938

**Comment by LaneSh4d0w** [comment]
@freearhey You can put the Ryowa links again, seems they had a little outage, links are working again.

**Comment by freearhey** [comment]
Added via https://github.com/iptv-org/iptv/commit/c954ecadab446a2e21b3d9e3c059522e03063cb1

**Comment by Zero3K** [comment]
https://redlabmcdn.s.llnwi.net/nv02/ryowa6hd/playlist.m3u8 is down.
