### ISSUE TITLE
Fixing - JP channels

### ISSUE THREAD

**Issue by LaneSh4d0w** [iptv-org/iptv#2314]
Fuji TV : https://fujitv.mov3.co/hls/fujitv.m3u8
NHK General : https://nhk.mov3.co/hls/nhk.m3u8
NHK World : https://nhkwlive-ojp.akamaized.net/hls/live/2003459/nhkwlive-ojp-en/index.m3u8
NHK World (Second option) : https://nhkworld.webcdn.stream.ne.jp/www11/nhkworld-tv/global/2003458/live.m3u8
Nippon TV : https://ntv.mov3.co/hls/ntv.m3u8
Nippon News 24 : https://n24-cdn-live.ntv.co.jp/ch01/High.m3u8
Nippon News 24 (Second server) : https://n24-cdn-live-b.ntv.co.jp/ch01/High.m3u8
TBS : https://tbs.mov3.co/hls/tbs.m3u8

**Comment by freearhey** [comment]
Added via https://github.com/iptv-org/iptv/commit/ce05281d13a866ec25136f1c9035b22449a88ac6
