### ISSUE TITLE
Add: Marvel hq 

### ISSUE THREAD

**Issue by modhack2003** [iptv-org/iptv#2316]
**Channel Name:** Marvel hq
**Country:** india
**Language:** hindi
**External Link (optional):** xxx
**Notes (optional):** please 🥺

**Comment by freearhey** [comment]
Closed in favor #1942

**Comment by rupesh25358a** [comment]
Marvel HQ
https://feed.play.mv/live/10005200/niZoVrR2vD/master.m3u8

**Comment by freearhey** [comment]
@rupesh25358a Added via #4512
