### ISSUE TITLE
Remove:ALL STREAMS THAT you STEAL FROM IPTV-Free/Countries Repo !!!

### ISSUE THREAD

**Issue by Zhoro-111** [iptv-org/iptv#2317]
Here you goooo
https://github.com/iptv-org/iptv/commit/2ae4de8a6bd5f335d3baebbe2616583d016ae4c2

**Comment by Zhoro-111** [comment]
I spend alot of time searching,creating files and so on and you grab all what I have done with the biggest insolence!!??

**Comment by LaneSh4d0w** [comment]
???

If those links are available on the internet, there's no doubt you won't be the only person that finds those links. DMCAing publically available links, as long as you're not the copyright holder makes it really weird.

I don't quite see why this was made, but i'll let @freearhey or @themak1985 answer this.

**Comment by freearhey** [comment]
@Zhoro-111 If you want the links to channels you own to be removed from the repository, publish your DMCA notice with the names of channels, then send us a link to it and we will remove them from the playlist within one business day.

**Comment by pcccw** [comment]
Lol, his own repository is a fork of someone else repository.

**Comment by Sphinxroot** [comment]
wow ...  if you dont want youre  "WORK" getting everywhere dont publish it ,as soon as it get online  by the basis of free tv  ..as your git its named free-iptv  ...they get rogue and posted everywhere .. pastebin facebook github VK  they also  get added to kodi addon as well ...and so on  .. so are they free or exclusive ?  .. if they are free you should be glad that peoples use them .. sharring is carring !!.. if they are exclusive just put ur github private and add youre buddy in so only them can see them ..  manny peoples take link they want and make a fav list of it ... big deal ? personaly i do it for me and if peoples take them , use them well thankfull for that :) just my 2 cent   have a nice day

**Comment by Zhoro-111** [comment]
> @Zhoro-111 If you want the links to channels you own to be removed from the repository, publish your DMCA notice with the names of channels, then send us a link to it and we will remove them from the playlist within one business day.

I am not the owner of these channels of course,the label was by accident.I was just asking not to copy the others work and post it as yours.THAT'S ALL!!!

**Comment by Zhoro-111** [comment]
> Lol, his own repository is a fork of someone else repository.

Yes it is a fork but I contribute every day like it was mine,so nothing for LOL here.

**Comment by Zhoro-111** [comment]
> wow ... if you dont want youre "WORK" getting everywhere dont publish it ,as soon as it get online by the basis of free tv ..as your git its named free-iptv ...they get rogue and posted everywhere .. pastebin facebook github VK they also get added to kodi addon as well ...and so on .. so are they free or exclusive ? .. if they are free you should be glad that peoples use them .. sharring is carring !!.. if they are exclusive just put ur github private and add youre buddy in so only them can see them .. manny peoples take link they want and make a fav list of it ... big deal ? personaly i do it for me and if peoples take them , use them well thankfull for that :) just my 2 cent have a nice day

You saying nothing new,anyway I don't like the way being done copy/paste from another repo and post it like your thing.Anyway maybe I am wrong but I will let my repo owner speak about this.Ciao!

**Comment by Zhoro-111** [comment]
> wow ... if you dont want youre "WORK" getting everywhere dont publish it ,as soon as it get online by the basis of free tv ..as your git its named free-iptv ...they get rogue and posted everywhere .. pastebin facebook github VK they also get added to kodi addon as well ...and so on .. so are they free or exclusive ? .. if they are free you should be glad that peoples use them .. sharring is carring !!.. if they are exclusive just put ur github private and add youre buddy in so only them can see them .. manny peoples take link they want and make a fav list of it ... big deal ? personaly i do it for me and if peoples take them , use them well thankfull for that :) just my 2 cent have a nice day

Wow that was a very reasonable response!!! I see the idea of stealing is welcomed here.Have a nice day !!

**Comment by Sphinxroot** [comment]
https://github.com/search?q=Free-IPTV+%2F+Countries&type=code your hall of shame will explode  have fun .. LOL

**Comment by pcccw** [comment]
I don't see that any of the contributor are claiming that the list is their exclusive work or that anyone is making money from the list.

And Anyone realize that this guy's complain is that he is albanian and that he should be only one in the internet to maintain the list for albanian channels? 
If someone complied others list with albanian channel, it must have been stolen from him.

Come on, we are all experienced contributor who can roughly tell the origin of the links from its url.

If it looks it is from an official website or an app, chance are that the links has been shared in the internet way longer before any of us. 

If it looks like full of number and dots or some funny website name chance are the links were sniffed by people running wireshark n was first posted on forums frequently by hackers before it is posted elsewhere.

**Comment by Zhoro-111** [comment]
> I don't see that any of the contributor are claiming that the list is their exclusive work or that anyone is making money from the list.
> 
> And Anyone realize that this guy's complain is that he is albanian and that he should be only one in the internet to maintain the list for albanian channels?
> If someone complied others list with albanian channel, it must have been stolen from him.
> 
> Come on, we are all experienced contributor who can roughly tell the origin of the links from its url.
> 
> If it looks it is from an official website or an app, chance are that the links has been shared in the internet way longer before any of us.
> 
> If it looks like full of number and dots or some funny website name chance are the links were sniffed by people running wireshark n was first posted on forums frequently by hackers before it is posted elsewhere.

I am not saying that I own ALBANIAN channels,but the links he copied are the links I created (same Imgur link)and that's clear he copied.I don't know anything about full number and dots,apps or hacked you saying ( I am not familiar,just a new user that I joined GitHub 1 month ago and trying to help someone's repo that I don't even know who he is or how he looks like) but I know about bullshit you talking here.You wants to look stupid or what???

**Comment by LaneSh4d0w** [comment]
Anyway, let's close this discussion in a subject. Allegations of "owned channels" are false, and links that are being discussed are links that are available all around the Internet.

**Comment by Zhoro-111** [comment]
> Anyway, let's close this discussion in a subject. Allegations of "owned channels" are false, and links that are being discussed are links that are available all around the Internet.

If stealing the others work and post within GitHub is OK then I am sorry for the disturb created.

**Comment by LaneSh4d0w** [comment]
> 
> 
> > Anyway, let's close this discussion in a subject. Allegations of "owned channels" are false, and links that are being discussed are links that are available all around the Internet.
> 
> If stealing the others work and post within GitHub is OK then I am sorry for the disturb created.

By that, I meant that no "stealing" whatsoever can be verified.

Once a resource is on Internet, it's meant to stay forever. It could be said once, twice or 1000 times, it will still be the case.

**Comment by Zhoro-111** [comment]
> > > Anyway, let's close this discussion in a subject. Allegations of "owned channels" are false, and links that are being discussed are links that are available all around the Internet.
> > 
> > 
> > If stealing the others work and post within GitHub is OK then I am sorry for the disturb created.
> 
> By that, I meant that no "stealing" whatsoever can be verified.
> 
> Once a resource is on Internet, it's meant to stay forever. It could be said once, twice or 1000 times, it will still be the case.

Here is my PR history for Albania  list.Do you see from where he picked new streams he posted ?
https://github.com/Free-IPTV/Countries/commits/master/AL01_ALBANIA.m3u

**Comment by geonsey** [comment]
> wow ... if you dont want youre "WORK" getting everywhere dont publish it ,as soon as it get online by the basis of free tv ..as your git its named free-iptv ...they get rogue and posted everywhere .. pastebin facebook github VK they also get added to kodi addon as well ...and so on .. so are they free or exclusive ? .. if they are free you should be glad that peoples use them .. sharring is carring !!.. if they are exclusive just put ur github private and add youre buddy in so only them can see them .. manny peoples take link they want and make a fav list of it ... big deal ? personaly i do it for me and if peoples take them , use them well thankfull for that :) just my 2 cent have a nice day

Here here! I run the Free2View TV Project and I have nothing illegal in the playlists that are offered through my project. And, people share my stuff all the time, mostly without permission, but there's nothing in my playlists that would be exclusive or that people cannot use. So, to take ownership of your playlists is frankly unfair. Yes, if you're not intending to share these lists, then you're posting your stuff in the wrong place, and you should share them privately among people you know and trust. 

By the way, I am proud that people know my Project and that are sharing! All the power to FREE live streaming!

**Comment by LaneSh4d0w** [comment]
> > 
> > 
> > @Zhoro-111 If you want the links to channels you own to be removed from the repository, publish your DMCA notice with the names of channels, then send us a link to it and we will remove them from the playlist within one business day.
> 
> iptv-org!
> 
> This is the second warning within days to copy our work!
> 
> https://github.com/iptv-org/iptv/pull/2282#issuecomment-808138484
> 
> WE will not look for anything, because we have not simply stupidly copied the work of others!
> 
> **YOU will now pick out the carriers of OUR work and delete them and very quickly. If you have a problem, ask your scripts or crawler!!!**
> 
> Last time I explained how quickly and easily we can find people who are not in the mood for work and simply copy our work.
> 
> I'm just talking about tvg-logo = !!! imgur is very valuable here, provides a unique ID!
> 
> I will NOT repeat myself there. At the end of our repo the rules are very clear and these rules have now been violated for the second time!
> 
> There is currently ONLY ONE permit for non-private use and oh, that's clear in my rules. From now on, write these rules behind your ears.
> 
> At the moment there is only ONE permission for non-private use and ONLY the Linux Mint team has it.
> 
> For quite a few clowns here in the comments. Free ONLY means that it is free for private use, but it does not mean that you can do what you want with it. People who have problems following the rules should perhaps seek competent help!
> 
> **This repo is already known, because of a rule violation, it is NOT the first time!**
> 

1) If those resources weren't meant to be used by everyone, there's something very cool called "private repositories", i don't know if you knew that ?

2) The only "alledged" proof of work being took here is... imgur links ? I could've used this image, changed the URL and you would have thought I'm stealing it... absolutely irrelevant.

Again, here, if you love your images so much you don't want people to use it, fine. Make a list and we will change them.

But PUBLICALLY AVAILABLE RESOURCES aren't meant to be in the dark forever. Either you tell us which images need to be modified, either this discussion has got no sense to be continued.

**Comment by Free-IPTV** [comment]
Because of some other stupid comments, another reaction from me would be a waste of time. 

There are people everywhere who have problems complying with the rules, some "Klugscheisser" also at Github, is unfortunate!

https://github.com/Free-IPTV/Countries/blob/master/README.md

**Comment by Raspifan2020** [comment]
It's incredible, the next idiot to stupidly copy the work of Free-IPTV. How good that more and more people notice how dubious IPTV-ORG is!

https://github.com/iptv-org/iptv/pull/2320#pullrequestreview-626290818

**Comment by Zhoro-111** [comment]
@LaneSh4d0w 
1.Respect the repo rules.
2.You can try the other way too if you can't find new streams by yourself but be careful because I will still be able to notice that depending of the streams.
3.The thief already know the list of stolen links(so no need making a list)
4.Finaly you agree that links been stolen and you are ready to delete only a part (logo) LOL so pathetic!!
5.You are not on the position to close this discussion,you not been stolen.If for you has no sense,then stop replying.
6.....If you want more I can do that with pleasure because I have arguments.

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w 
> 1.Respect the repo rules.
> 2.You can try the other way too if you can't find new streams by yourself but be careful because I will still be able to notice that depending of the streams.
> 3.The thief already know the list of stolen links(so no need making a list)
> 4.Finaly you agree that links been stolen and you are ready to delete only a part (logo) LOL so pathetic!!
> 5.You are not on the position to close this discussion,you not been stolen.If for you has no sense,then stop replying.
> 6.....If you want more I can do that with pleasure because I have arguments.
> 
> 
> 
> 
> 

1) If I understand your repo rules, it's talking about the whole m3u files. Did we steal your entire m3u file ? Nope. Try again.

2) Don't worry, the streams I gather were found by me, myself, and I.

3) You've given us only one file. Be more precise.

4) Did I agree anything here ? Just said that if you are loving your pics (which is also stealing from the original TV company who designed it), then answer 3).

5) I maybe am not on the position to do so, but when something goes on and on for nonsense, there's no need to continue.

6) More arguments ? I could give you some too :

6.1) Tell me... do you love the fact that lots of people in here are passionnate about IPTV and the only goal is to gather all links available ? 

6.2) I'm pretty sure that almost 40% of the content of both repositories are entirely similar, with links we or you found first.

6.3) Then, in that case, why don't you put your repository in private ? No one will ever see your links anymore, and everyone will be happy. Just make a github website where you host your m3u files for the persons who like your repo to get them.

6.4) Shall I continue ?

**Comment by Zhoro-111** [comment]
> > @LaneSh4d0w
> > 1.Respect the repo rules.
> > 2.You can try the other way too if you can't find new streams by yourself but be careful because I will still be able to notice that depending of the streams.
> > 3.The thief already know the list of stolen links(so no need making a list)
> > 4.Finaly you agree that links been stolen and you are ready to delete only a part (logo) LOL so pathetic!!
> > 5.You are not on the position to close this discussion,you not been stolen.If for you has no sense,then stop replying.
> > 6.....If you want more I can do that with pleasure because I have arguments.
> 
> 1. If I understand your repo rules, it's talking about the whole m3u files. Did we steal your entire m3u file ? Nope. Try again.
> 2. Don't worry, the streams I gather were found by me, myself, and I.
> 3. You've given us only one file. Be more precise.
> 4. Did I agree anything here ? Just said that if you are loving your pics (which is also stealing from the original TV company who designed it), then answer 3).
> 5. I maybe am not on the position to do so, but when something goes on and on for nonsense, there's no need to continue.
> 6. More arguments ? I could give you some too :
> 
> 6.1) Tell me... do you love the fact that lots of people in here are passionnate about IPTV and the only goal is to gather all links available ?
> 
> 6.2) I'm pretty sure that almost 40% of the content of both repositories are entirely similar, with links we or you found first.
> 
> 6.3) Then, in that case, why don't you put your repository in private ? No one will ever see your links anymore, and everyone will be happy. Just make a github website where you host your m3u files for the persons who like your repo to get them.
> 
> 6.4) Shall I continue ?

Only one file ??!! If you have time to compare the unsorted list new entries with our new streams added last 3 weeks you can find what you looking for and what we are concerned.
6.1) Yes I love that fact.
6.2) Yes it's possible.
6.3) I can't decide that(not the owner) but as I know you can copy what you like and use it for private use,nothing against that since that's the purpose of sharing.
6.4)No need to continue because it will never end,but I would like to hear more from the thief that is hiding and letting you and others speak and defend a very clear dirt job.

**Comment by LaneSh4d0w** [comment]
> > > @LaneSh4d0w
> > > 1.Respect the repo rules.
> > > 2.You can try the other way too if you can't find new streams by yourself but be careful because I will still be able to notice that depending of the streams.
> > > 3.The thief already know the list of stolen links(so no need making a list)
> > > 4.Finaly you agree that links been stolen and you are ready to delete only a part (logo) LOL so pathetic!!
> > > 5.You are not on the position to close this discussion,you not been stolen.If for you has no sense,then stop replying.
> > > 6.....If you want more I can do that with pleasure because I have arguments.
> > 
> > 1. If I understand your repo rules, it's talking about the whole m3u files. Did we steal your entire m3u file ? Nope. Try again.
> > 2. Don't worry, the streams I gather were found by me, myself, and I.
> > 3. You've given us only one file. Be more precise.
> > 4. Did I agree anything here ? Just said that if you are loving your pics (which is also stealing from the original TV company who designed it), then answer 3).
> > 5. I maybe am not on the position to do so, but when something goes on and on for nonsense, there's no need to continue.
> > 6. More arguments ? I could give you some too :
> > 
> > 6.1) Tell me... do you love the fact that lots of people in here are passionnate about IPTV and the only goal is to gather all links available ?
> > 
> > 6.2) I'm pretty sure that almost 40% of the content of both repositories are entirely similar, with links we or you found first.
> > 
> > 6.3) Then, in that case, why don't you put your repository in private ? No one will ever see your links anymore, and everyone will be happy. Just make a github website where you host your m3u files for the persons who like your repo to get them.
> > 
> > 6.4) Shall I continue ?
> 
> Only one file ??!! If you have time to compare the unsorted list new entries with our new streams added last 3 weeks you can find what you looking for and what we are concerned.
> 6.1) Yes I love that fact.
> 6.2) Yes it's possible.
> 6.3) I can't decide that(not the owner) but as I know you can copy what you like and use it for private use,nothing against that since that's the purpose of sharing.
> 6.4)No need to continue because it will never end,but I would like to hear more from the thief that is hiding and letting you and others speak and defend a very clear dirt job. 

Well sir, we're on some good points in here. I'll let the others speak. And thanks for the talk.

**Comment by Sphinxroot** [comment]
Free legally receivable IPTV channels as .m3u for Kodi. :-)  >... OH MY ITS FREE !!! Are THEY ? Im Confused now ...LOL

THE FOLLOWING RULES MUST BE OBSERVED:

ONLY CREATE A FORK IF YOU WANT TO WORK WITH ME AND NOT ONLY TO ENRICH YOUR GITHUB ACCOUNT ->..can`t control that ... exepted if its private ...


ALL M3Us ARE INTENDED FOR PRIVATE USE ONLY ->.. private ??? FREE ??? ... Are you smokin bad weed ?


IT IS NOT ALLOWED TO SEND ME ILLGEGAL STREAMS VIA PULL REQUEST OR POST HERE IN MY REPO ->... this is the only one u can control btw  .. Better than nothing ..isnt ?


USE FOR COMMERCIAL PURPOSES IS NOT PERMITTED ->... can`t control that , your link are already in some free and paid APK file oupss!!

DISTRIBUTING OR POSTING MY LISTS IN FORUMS, HOMEPAGES OR IN SOCIAL NETWORKS IS NOT PERMITTED  ->...can`t control that nether .. its already everywhere ... event in the deepweb .. oh gezz ! 


None of these rule can`t be apply because , in plain sight and anyone that see it ,can take it

its like putting a jar of candy and mark free on it ,... then whining because the jar get empty ...


OH And I leave this here 

https://i.imgur.com/pXioQ15.png

plenty of evidence of you taking stuff from other ... in all youre pull request ...

https://github.com/Free-IPTV/Countries/commit/b146798c7f627443103aaeb815563636d4401802#diff-3d0bb4b9d2747041c032f580654351227a7e923307e31406c25f5df3eae0adb7

https://i.imgur.com/z8mJKwA.png

changing the pic for a imgur free open services does`nt give you the private use of it .. its online ...its go rogue ... period !!  deal whit it !



ALL This was  ...  April fool day  .. Right ?

**Comment by geonsey** [comment]
This group does a disservice for the cordcutting / m3u / free lists community. You are a red-assed baboon puffing your chest out like you 'own' the playlists. I run a community that enjoys the work, the exploration of new legal streams, and welcomes sharing with folks. None of us claims any ownership of anything. We all take responsibility, however, if there are copyright issues involved, and frankly there just isn't. So, if you don't want your stuff to get 'forked' or duplicated, or stolen, or whatever you want to consider breaking the rules, you don't need to put your stuff on gihub, or pastebin, or wherever your stuff may be compromised. These rules mean crap. Done.

**Comment by Gdfn8d6RWdbMpmu6kosQVmUiDMqBdz-XzoWmvHh** [comment]
> Because of some other stupid comments, another reaction from me would be a waste of time.
> 
> From now on I will only report every rule violation! The name of my repo is Free-IPTV and NOT Free-Copy!!!
> 
> There are people everywhere who have problems complying with the rules, some "Klugscheisser" also at Github, is unfortunate!
> 
> https://github.com/Free-IPTV/Countries/blob/master/README.md

more like 3 euro iptv lmao

**Comment by Gdfn8d6RWdbMpmu6kosQVmUiDMqBdz-XzoWmvHh** [comment]
> Because of some other stupid comments, another reaction from me would be a waste of time.
> 
> From now on I will only report every rule violation! The name of my repo is Free-IPTV and NOT Free-Copy!!!
> 
> There are people everywhere who have problems complying with the rules, some "Klugscheisser" also at Github, is unfortunate!
> 
> https://github.com/Free-IPTV/Countries/blob/master/README.md

1. You're charging 3 euros for access to a private repo. (LOL)
2. If you can't handle users forking your project (not against the rules) GitHub is not for you.

**Comment by Gdfn8d6RWdbMpmu6kosQVmUiDMqBdz-XzoWmvHh** [comment]
@Free-IPTV
> Because of some other stupid comments, another reaction from me would be a waste of time.
> 
> From now on I will only report every rule violation! The name of my repo is Free-IPTV and NOT Free-Copy!!!
> 
> There are people everywhere who have problems complying with the rules, some "Klugscheisser" also at Github, is unfortunate!
> 

1. You're charging 3 euro for access to a private repo. (LOL)
2. If you can't handle users forking (not against the rules) GitHub is not for you.

**Comment by Gdfn8d6RWdbMpmu6kosQVmUiDMqBdz-XzoWmvHh** [comment]
Actually, give him credit where it's due. Donate him 3 euro.  
But make an Alt & fork the repo public.

**Comment by Gdfn8d6RWdbMpmu6kosQVmUiDMqBdz-XzoWmvHh** [comment]
Actually, give him credit where it's due. Donate 3 euro.
But make an Alt & fork the repo public.

**Comment by Sphinxroot** [comment]
well let me say this ...

if peoples wanna pay for something that is free (and mostly stollen from other repo) i guest ... its not our concern .. we can`t fix stupid ... its  freedom of choice ..

all i see from him .. its jealousy .. childish reaction , lack of respect ,and useless drama  , who think he owns the internet ... peoples get disorganized nowaday ... 

a real leader does`nt need to proves that hes the best .. he help other getting better !

i dont think is repo will grow up whit a dictator mentality ... just my 2 cents

this is a great community of passionate peoples  ,that share time and link freely , that many use all over the world , and best of all 
Its really Free

**Comment by Zhoro-111** [comment]
This is my last comment here.
Don't call people that appreciate hard work (no thiefs,no blind scripts that grab others work even when logo is changed as a new file -->> what's your repo was doing) STUPID!!
THE ONLY THIEF CAUGHT LIVE WAS YOUR LEADER.
The reason we gone private is your repo and your dirty actions.
Do you imagine that all I have done lately it was from my smartphone and seeing someone taking all easily and posting as his own work ...THAT HURTS.
The only thing that has value on your comment is your ( 2 Cents) the rest is bla bla bla.Save those cents and give to ghost or someone else that need a ticket for the show.Peace and Long Life to all of you here.Ciao!!

**Comment by loucasal** [comment]
Perhaps @freearhey or one of the other maintainers would like to set the record straight on the ill-founded claims being made on this project by you know who... [linuxmint/hypnotix#124](https://github.com/linuxmint/hypnotix/issues/124#issuecomment-813491531)

**Comment by LaneSh4d0w** [comment]
To be honest, there's not even the need to continue, they've got their solution.

But well, that's life. We need a bit of everything to make a world.
