### ISSUE TITLE
Add: Tele Sahel [Niger]

### ISSUE THREAD

**Issue by LaneSh4d0w** [iptv-org/iptv#2319]
I call @Nintendocustom for his abilities with tokens.

Akamai token needs to be grabbed from here : https://token.kube.easybroadcast.fr/akamai
And the token recieved needs to be injected into this link : https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/tele_sahel/hls_video/index.m3u8 <- here.

**Comment by kone78** [comment]
Thanks very much, but this Channel not from Nigeria but from Niger
#EXTM3U
#EXTINF:0 type="stream" channelId="-1" group="MALI" logo="https://www.lyngsat.com/logo/tv/oo/ortm-1-ml.png", ORTM 1
https://mmsiptv.com/live/ortm/playlist.m3u8
#EXTINF:0 type="stream" channelId="-1" group="MALI" logo="https://www.lyngsat.com/logo/tv/aa/africable_tv.png", AFRICABLE
https://mmsiptv.com/live/africable/playlist.m3u8

**Comment by Nintendocustom** [comment]
Tele Sahel: https://iptv--iptv.repl.co/French/tele_sahel/

**Comment by freearhey** [comment]
Added via https://github.com/iptv-org/iptv/commit/5a47f463c57930fc6a34e5fedf833dab0eb99535
