### ISSUE TITLE
Looking for Mainichi Broadcasting System , Sun Television (JP)

### ISSUE THREAD

**Issue by YunomiSakura** [iptv-org/iptv#2321]
**Channel Name:** Mainichi Broadcasting System ( MBS ) , Sun Television
**Country:** Japan
**Language:** Japan
**External Link (optional):** xxx
**Notes (optional):** Pls add it fast

**Comment by freearhey** [comment]
Closed in favor #1938

**Comment by NicoNoHato** [comment]
http://122.155.180.8:5021/live/319
i got this one, but the quality is so bad..
