### ISSUE TITLE
link to be tested before added 

### ISSUE THREAD

**Issue by Sphinxroot** [iptv-org/iptv#2325]
some link to be tested , it work for me in kodi with the referer url only

# https://livenewschat.eu/
#EXTINF:-1, Canada CBC
https://ligma.cdn.livenewschat.eu/hls/cbc_live/index.m3u8|Referer=https://livenewschat.eu/canada/

#EXTINF:-1, bloomberg
https://iguana.cdn.livenewschat.eu/hls/bloomberg_live/index.m3u8|Referer=https://livenewschat.eu/business/

#EXTINF:-1, EURONEWS
https://iguana.cdn.livenewschat.eu/hls/euronews_live/index.m3u8|Referer=https://livenewschat.eu/euronews/

#EXTINF:-1, Free Speech TV
https://iguana.cdn.livenewschat.eu/hls/fstv_live/index.m3u8|Referer=https://livenewschat.eu/fstv/

#EXTINF:-1, MSNBC
https://gnome.cdn.livenewschat.eu/hls/msnbc_live/index.m3u8|Referer=https://livenewschat.eu/politics/

#EXTINF:-1, CNBC Stock Traders
https://iguana.cdn.livenewschat.eu/hls/cnbc_live/index.m3u8|Referer=https://livenewschat.eu/stocks/

#EXTINF:-1, CNN
https://iguana.cdn.livenewschat.eu/hls/cnnus_live/index.m3u8|Referer=https://livenewschat.eu/breaking-news/

#EXTINF:-1, CNN International
https://iguana.cdn.livenewschat.eu/hls/cnni_live/index.m3u8|Referer=https://livenewschat.eu/intl/

#EXTINF:-1, Twoon’s Room
https://iguana.cdn.livenewschat.eu/hls/twoon_live/index.m3u8|Referer=https://livenewschat.eu/twoon-room/

#EXTINF:-1, Al Jazeera
https://gnome.cdn.livenewschat.eu/hls/aljazeera_live/index.m3u8|Referer=https://livenewschat.eu/jazzyi/

#EXTINF:-1, France24 English
https://gnome.cdn.livenewschat.eu/hls/france24_hd/index.m3u8|Referer=https://livenewschat.eu/france/

#EXTINF:-1, CBS News
https://iguana.cdn.livenewschat.eu/hls/cbsn_hd/index.m3u8|Referer=https://livenewschat.eu/live-news-stream-1/

#EXTINF:-1, NBC News Now
https://iguana.cdn.livenewschat.eu/hls/nbcnews_hd/index.m3u8|Referer=https://livenewschat.eu/live-news-stream-2/

#EXTINF:-1, Sky News Live
https://gnome.cdn.livenewschat.eu/hls/skynews_hd/index.m3u8|Referer=https://livenewschat.eu/sky/

**Comment by LaneSh4d0w** [comment]
It's pretty funny how they react once you don't have the good referer link "You have bad PC."

**Comment by themak1985** [comment]
Does this work for anyone?

```
#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="" tvg-language="English" tvg-logo="" group-title="News",Canada CBC
#EXTVLCOPT:http-referrer=https://livenewschat.eu/canada/
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64)
https://ligma.cdn.livenewschat.eu/hls/cbc_live/index.m3u8
```

**Comment by LaneSh4d0w** [comment]
@themak1985 Let me see.

**Comment by LaneSh4d0w** [comment]
Doesn't work with VLC, but works with Streamlink (options : streamlink.exe "https://ligma.cdn.livenewschat.eu/hls/cbc_live/index.m3u8" --http-header "Referer=https://livenewschat.eu/canada/")

**Comment by freearhey** [comment]
@themak1985 For me, it doesn't work. Tested in VLC and Elmedia Video Player.

**Comment by LaneSh4d0w** [comment]
@Sphinxroot I'll try to see if I can manage to do something with those

**Comment by LaneSh4d0w** [comment]
@Sphinxroot (I also summon @Nintendocustom)

`const express = require("express");
const fetch = require('node-fetch');
const fs = require('fs');
const parser = require('iptv-playlist-parser');
const app = express();

const server = app.listen("8000");

var channels = [];

const playlist = fs.readFileSync(__dirname + "/base.m3u8", { encoding: 'utf-8' })
const result = parser.parse(playlist)

for(var i = 0; i < result.items.length; i++) {
  channels.push(result.items[i].url);
}


app.get("/", (req, res) => {
  for(var i = 0; i < channels.length; i++) {
    res.write('<p><a href="/stream/' + i + '">'+ channels[i] + '</a></p>')
  }
  res.end();
});

app.get('/stream/:id', (req, res) => {
  var id = req.params.id;

  const result = channels[id];
  const referer_and_url = result.split("|");
  const referer = referer_and_url[1].split('=');

  fetch(referer_and_url[0], {headers: {"Referer": referer[1]}})
  .then(response => {
    return response.text()
  })
  .then(result => {
    res.set('Content-Type', "application/vnd.apple.mpegurl")
    res.send(result);
  })
});


module.exports = app;`

**Comment by Sphinxroot** [comment]
those stream have strange behavior maybe the streaming network setting  .. i use mostly kodi for my TV ( because i can handle : youtube twitch dailymotion ect... )  and in some case i need to add |Referer= or  |User-Agent=  to get the stream working  , if i use .m3u8 alone it does`nt work   other stream that need a clue its the fox local channel that use  https://dcs-live.apis.anvato.net those token need to be cracked

**Comment by Nintendocustom** [comment]
The problem here is that the stream needs the referer header for the playlist and for the segments. VLC uses by default the referer header only for the playlist, which is wrong, but if you start VLC with  --adaptive-use-access it is playable. 
```
#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="" tvg-language="English" tvg-logo="" group-title="News",Canada CBC
#EXTVLCOPT:http-referrer=https://livenewschat.eu/canada/
https://ligma.cdn.livenewschat.eu/hls/cbc_live/index.m3u8
```
![image](https://user-images.githubusercontent.com/41170567/113496060-2b0bee80-94f6-11eb-8120-07d6467e9146.png)
