### ISSUE TITLE
Add: 2x2

### ISSUE THREAD

**Issue by PunyFlash** [iptv-org/iptv#2326]
**Channel Name:** 2x2
**Country:** Russia
**Language:** Russian
**External Link (optional):** http://178.163.98.224:81/udp/234.0.0.244:2000
**Notes (optional):** Category - Entertainment, Channel logo - https://i.ibb.co/DrvTgDc/2x2.png

**Comment by themak1985** [comment]
Added via c534f49d960242b86d78d57d8f292882a410d9b8
```
#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="RU" tvg-language="Russian" tvg-logo="https://i.ibb.co/DrvTgDc/2x2.png" group-title="",2x2
http://178.163.98.224:81/udp/234.0.0.244:2000
```
Thanks for the submission.
