### ISSUE TITLE
Fix: Tokyo MX 1 of Japan

### ISSUE THREAD

**Issue by shemugeorge1224** [iptv-org/iptv#2329]
Channel Name: Tokyo MX 1
Broken Link (from playlist):http://redlabmcdn.s.llnwi.net/jp01/ryowa8/index.m3u8
Notes (optional): It was working well lately, however after a few days it stopped airing; My player is PotPlayer
![image](https://user-images.githubusercontent.com/80572927/113484038-ec1b7000-94d8-11eb-8c6e-d933d8632f45.png)

**Comment by Sphinxroot** [comment]
yes vlc fail to open both

https://redlabmcdn.s.llnwi.net/jp01/ryowa8/index.m3u8

and kodi working only
https://redlabmcdn.s.llnwi.net/jp01/ryowa8/tracks-v1a1/mono.m3u8

**Comment by luke026** [comment]
I need pinoy channel like tfc channel pls help me iptv link

**Comment by LaneSh4d0w** [comment]
It's really weird, it seems it works from time to time now.

**Comment by LaneSh4d0w** [comment]
> 
> 
> yes vlc fail to open both
> 
> https://redlabmcdn.s.llnwi.net/jp01/ryowa8/index.m3u8
> 
> and kodi working only
> https://redlabmcdn.s.llnwi.net/jp01/ryowa8/tracks-v1a1/mono.m3u8

Works with streamlink too.

**Comment by YunomiSakura** [comment]
iptv in android did not work too

**Comment by LaneSh4d0w** [comment]
http://redlabmcdn.s.llnwi.net/jp01/ryowa6/tracks-v1a1/mono.m3u8

This link, for TV Tokyo, seems to work on VLC.

https://redlabmcdn.s.llnwi.net/jp01/ryowa8/tracks-v1a1/mono.m3u8

This link, for Tokyo MX 1 also works on VLC.

Both lag upon every 5 seconds...

**Comment by freearhey** [comment]
Links updated.

**Comment by letterfist** [comment]
Hello, this is an outdate topic

**Comment by letterfist** [comment]
https://github.com/orgs/iptv-org/discussions/202#discussioncomment-7067661
