### ISSUE TITLE
TFC Asia-Pacific

### ISSUE THREAD

**Issue by luke026** [iptv-org/iptv#2332]
**Channel Name:** tfc 
**Channel ID:** TheFilipinoChannelAsia.us
**Country:** phillipine
**Language:** tagalog
**External Link (optional):**tfc
**Notes (optional):** can u give this link in iptv ios

**Comment by freearhey** [comment]
Closed in favor #1967

**Comment by freearhey** [comment]
Closed in favor of #12309
