### ISSUE TITLE
xxx Request Channels all pinoy channel

### ISSUE THREAD

**Issue by luke026** [iptv-org/iptv#2333]
List of requests for XXX channels from other issues:

- [x] xxx

**Comment by LaneSh4d0w** [comment]
Be more precise. Is there any Pinoy channel in particular you would want ? And... isn't Pinoy the way we mention people the Filipino people living in the Phillipines ?

**Comment by luke026** [comment]
Yah i am pinoy

**Comment by Sphinxroot** [comment]
https://tfc.tv/#plans  account required  and mostly premium channel

**Comment by luke026** [comment]
Thank u. But channel only i need sir hmm can i ask about linked hbo max
