### ISSUE TITLE
Removal:  Telecaribe Deportes 2 [CO]

### ISSUE THREAD

**Issue by LaneSh4d0w** [iptv-org/iptv#2335]
-> Why remove Telecaribe Deportes 2 ? : It is the same stuff going over and over again, which isn't the real stream.

-> Discussion : Telecaribe also hosts their streams on their own website. It is Anvato-tokened, but... they left test-pages that permit us to take the generated token and use it.

**Comment by Sphinxroot** [comment]
if its the good one , its clearly free to view 

http://tv.10dailythings.com/channel/co/telecaribe-deportes-2

https://telecaribe-deportes.gcdn.anvato.net/hls/live/telecaribedeporteshd2/2196k/index.m3u8  no token there ...  isPrivate | false

**Comment by LaneSh4d0w** [comment]
No, I was saying that Telecaribe Deportes 2 had the same programme being shown on this link, instead of having something that changes over time. I went to see 5 times and there was some sort of carnival and stuff.
