### ISSUE TITLE
Fix: Tokyo MX1

### ISSUE THREAD

**Issue by YunomiSakura** [iptv-org/iptv#2336]
***Channel Name:*** Tokyo Mx 1
***Broken Link (from playlist):*** https://movie.mcas.jp/mcas/smil:mx1_prod.smil/master.m3u8
***Possible Replacement (optional):*** frozen
***Notes (optional):*** pls fix it

**Comment by LaneSh4d0w** [comment]
Not frozen. It's an official stream, which means that not everything is shown.

**Comment by freearhey** [comment]
At the moment the broadcast is working fine.
<img width="869" alt="Captura de pantalla 2021-04-05 a las 3 25 09" src="https://user-images.githubusercontent.com/7253922/113525621-8bfef980-95be-11eb-93ef-1d539cb6f431.png">
