### ISSUE TITLE
some greece channel list

### ISSUE THREAD

**Issue by exyanis** [iptv-org/iptv#2342]
#EXTM3U
#EXTINF:-1,Alert
https://itv.streams.ovh/ALEERT/ALEERT/playlist.m3u8
#EXTINF:-1,Alpha TV
https://alphalive-i.akamaihd.net/hls/live/682300/live/master.m3u8
#EXTINF:-1,ANT1
https://antennalivesp-lh.akamaihd.net/i/live_1@715138/master.m3u8
#EXTINF:-1,Axeloos
http://srv.viiideo.gr:1935/axeloos/live/playlist.m3u8
#EXTINF:-1,Baraza TV
https://eco.streams.ovh:443/BarazaTV/BarazaTV/playlist.m3u8
#EXTINF:-1,Baraza TV Classic Hits
https://eco.streams.ovh:443/BarazaClassic/BarazaClassic/playlist.m3u8
#EXTINF:-1,Baraza TV Greek Music Hits
https://eco.streams.ovh/BarazaTV/BarazarazaTV/BarazaTV/playlist.m3u8
#EXTINF:-1,Channel 9
http://176.9.123.140:1935/channel9/channel9/playlist.m3u8
#EXTINF:-1,Corfu TV
https://itv.streams.ovh/corfuchannel/corfuchannel/playlist.m3u8
#EXTINF:-1,Diktyo 1
https://www.hellasnet.tv/rest.live.hn/diktyo1r/playlist.m3u8
#EXTINF:-1,E TV
http://176.9.30.75:1935/live/epsilon/playlist.m3u8
#EXTINF:-1,Ena Channel
http://176.9.123.140:1935/1c/stream/master.m3u8
#EXTINF:-1,Eoe TV
https://live.cast-control.eu:443/organismos/organismos/playlist.m3u8
#EXTINF:-1,ERT World
http://wpso.com:1936/hls/wzra.m3u8
#EXTINF:-1,Fox Tv Greece
http://live.streams.ovh:1935/foxtv/foxtv/playlist.m3u8
#EXTINF:-1,Groovy
http://web.onair-radio.eu:1935/groovytv/groovytv/playlist.m3u8
#EXTINF:-1,Ionian TV
https://stream.ioniantv.gr/ionian/live_abr/playlist.m3u8
#EXTINF:-1,Irida TV
https://www.hellasnet.tv/rest.live.hn/ws.iri/playlist.m3u8
#EXTINF:-1,Kontra Channel
http://flashcloud.mediacdn.com/live/kontratv/playlist.m3u8
#EXTINF:-1,Krete TV
http://live.cretetv.gr:1935/cretetv/myStream/f1tv.m3u8
#EXTINF:-1,Magic TV GR
https://itv.streams.ovh/magictv/magictv/playlist.m3u8
#EXTINF:-1,Messinia TV (Webradio)
http://176.9.123.140:1935/messinia/messinia/master.m3u8
#EXTINF:-1,Mesogeios TV
http://176.9.123.140:1935/mesogeiostv/stream/master.m3u8
#EXTINF:-1,Montreal Greek TV
http://94.130.180.175:8081/live/greektv/playlist.m3u8
#EXTINF:-1,NG RADIO
http://live.streams.ovh:1935/NGradio/NGradio/playlist.m3u8
#EXTINF:-1,Play TV
http://web.onair-radio.eu:1935/Alpha-Host/Alpha-Host/playlist.m3u8
#EXTINF:-1,Pik Sat (Cyprus)
http://l3.cloudskep.com/cybcsat/abr/playlist.m3u8
#EXTINF:-1,,PLP
https://www.hellasnet.tv/rest.live.hn/ws.plp/playlist.m3u8
#EXTINF:-1,Reload Play
http://web.onair-radio.eu:1935/video/video/playlist.m3u8
#EXTINF:-1,Samiaki TV
http://live.cast-control.eu:1935/samiaki/samiaki/playlist.m3u8
#EXTINF:-1,Sigma TV
http://81.21.47.74/hls/live.m3u8
#EXTINF:-1,Start TV
https://live.cast-control.eu/StartMedia/StartMedia/playlist.m3u8
#EXTINF:-1,Top Channel
https://itv.streams.ovh/topchannel/topchannel/playlist.m3u8
#EXTINF:-1,TRT TV
https://www.hellasnet.tv/rest.live.hn/trt2/chunklist.m3u8
#EXTINF:-1,TV Creta
https://live.streams.ovh/tvcreta/tvcreta/chunklist.m3u8
#EXTINF:-1,TV Filopoli
http://live.streams.ovh:1935/tvfilopoli/tvfilopoli/playlist.m3u8
#EXTINF:-1,Vouli Tileorasi
https://streamer-cache.grnet.gr/parliament/parltv.sdp/master.m3u8
#EXTINF:-1,Wixlar
http://web.onair-radio.eu:1935/wixlar/wixlar/playlist.m3u8
#EXTINF:-1,WZra Kids TV
http://wpso.com:1936/hls/kidshd.m3u8
#EXTINF:-1 ,Xalastra TV
https://live.cast-control.eu:443/xalastratv/xalastratv/playlist.m3u8
#EXTINF:-1 ,Xplore TV
http://web.onair-radio.eu:1935/explorecy/explorecy/playlist.m3u8

**Comment by exyanis** [comment]
> #EXTM3U
> #EXTINF:-1,Alert
> https://itv.streams.ovh/ALEERT/ALEERT/playlist.m3u8
> #EXTINF:-1,Alpha TV
> https://alphalive-i.akamaihd.net/hls/live/682300/live/master.m3u8
> #EXTINF:-1,ANT1
> https://antennalivesp-lh.akamaihd.net/i/live_1@715138/master.m3u8
> #EXTINF:-1,Axeloos
> http://srv.viiideo.gr:1935/axeloos/live/playlist.m3u8
> #EXTINF:-1,Baraza TV
> https://eco.streams.ovh:443/BarazaTV/BarazaTV/playlist.m3u8
> #EXTINF:-1,Baraza TV Classic Hits
> https://eco.streams.ovh:443/BarazaClassic/BarazaClassic/playlist.m3u8
> #EXTINF:-1,Baraza TV Greek Music Hits
> https://eco.streams.ovh/BarazaTV/BarazarazaTV/BarazaTV/playlist.m3u8
> #EXTINF:-1,Channel 9
> http://176.9.123.140:1935/channel9/channel9/playlist.m3u8
> #EXTINF:-1,Corfu TV
> https://itv.streams.ovh/corfuchannel/corfuchannel/playlist.m3u8
> #EXTINF:-1,Diktyo 1
> https://www.hellasnet.tv/rest.live.hn/diktyo1r/playlist.m3u8
> #EXTINF:-1,E TV
> http://176.9.30.75:1935/live/epsilon/playlist.m3u8
> #EXTINF:-1,Ena Channel
> http://176.9.123.140:1935/1c/stream/master.m3u8
> #EXTINF:-1,Eoe TV
> https://live.cast-control.eu:443/organismos/organismos/playlist.m3u8
> #EXTINF:-1,ERT World
> http://wpso.com:1936/hls/wzra.m3u8
> #EXTINF:-1,Fox Tv Greece
> http://live.streams.ovh:1935/foxtv/foxtv/playlist.m3u8
> #EXTINF:-1,Groovy
> http://web.onair-radio.eu:1935/groovytv/groovytv/playlist.m3u8
> #EXTINF:-1,Ionian TV
> https://stream.ioniantv.gr/ionian/live_abr/playlist.m3u8
> #EXTINF:-1,Irida TV
> https://www.hellasnet.tv/rest.live.hn/ws.iri/playlist.m3u8
> #EXTINF:-1,Kontra Channel
> http://flashcloud.mediacdn.com/live/kontratv/playlist.m3u8
> #EXTINF:-1,Krete TV
> http://live.cretetv.gr:1935/cretetv/myStream/f1tv.m3u8
> #EXTINF:-1,Magic TV GR
> https://itv.streams.ovh/magictv/magictv/playlist.m3u8
> #EXTINF:-1,Messinia TV (Webradio)
> http://176.9.123.140:1935/messinia/messinia/master.m3u8
> #EXTINF:-1,Mesogeios TV
> http://176.9.123.140:1935/mesogeiostv/stream/master.m3u8
> #EXTINF:-1,Montreal Greek TV
> http://94.130.180.175:8081/live/greektv/playlist.m3u8
> #EXTINF:-1,NG RADIO
> http://live.streams.ovh:1935/NGradio/NGradio/playlist.m3u8
> #EXTINF:-1,Play TV
> http://web.onair-radio.eu:1935/Alpha-Host/Alpha-Host/playlist.m3u8
> #EXTINF:-1,Pik Sat (Cyprus)
> http://l3.cloudskep.com/cybcsat/abr/playlist.m3u8
> #EXTINF:-1,,PLP
> https://www.hellasnet.tv/rest.live.hn/ws.plp/playlist.m3u8
> #EXTINF:-1,Reload Play
> http://web.onair-radio.eu:1935/video/video/playlist.m3u8
> #EXTINF:-1,Samiaki TV
> http://live.cast-control.eu:1935/samiaki/samiaki/playlist.m3u8
> #EXTINF:-1,Sigma TV
> http://81.21.47.74/hls/live.m3u8
> #EXTINF:-1,Start TV
> https://live.cast-control.eu/StartMedia/StartMedia/playlist.m3u8
> #EXTINF:-1,Top Channel
> https://itv.streams.ovh/topchannel/topchannel/playlist.m3u8
> #EXTINF:-1,TRT TV
> https://www.hellasnet.tv/rest.live.hn/trt2/chunklist.m3u8
> #EXTINF:-1,TV Creta
> https://live.streams.ovh/tvcreta/tvcreta/chunklist.m3u8
> #EXTINF:-1,TV Filopoli
> http://live.streams.ovh:1935/tvfilopoli/tvfilopoli/playlist.m3u8
> #EXTINF:-1,Vouli Tileorasi
> https://streamer-cache.grnet.gr/parliament/parltv.sdp/master.m3u8
> #EXTINF:-1,Wixlar
> http://web.onair-radio.eu:1935/wixlar/wixlar/playlist.m3u8
> #EXTINF:-1,WZra Kids TV
> http://wpso.com:1936/hls/kidshd.m3u8
> #EXTINF:-1 ,Xalastra TV
> https://live.cast-control.eu:443/xalastratv/xalastratv/playlist.m3u8
> #EXTINF:-1 ,Xplore TV
> http://web.onair-radio.eu:1935/explorecy/explorecy/playlist.m3u8

#EXTINF:-1, ERT1
http://ert-live-bcbs15228.siliconweb.com/media/ert_1/ert_1.m3u8
#EXTINF:-1, ERT2
http://ert-live-bcbs15228.siliconweb.com/media/ert_2/ert_2.m3u8
#EXTINF:-1, ERT3
http://ert-live-bcbs15228.siliconweb.com/media/ert_3/ert_3.m3u8

**Comment by exyanis** [comment]
#EXTINF:-1, ERT1
http://ert-live-bcbs15228.siliconweb.com/media/ert_1/ert_1.m3u8
#EXTINF:-1, ERT2
http://ert-live-bcbs15228.siliconweb.com/media/ert_2/ert_2.m3u8
#EXTINF:-1, ERT3
http://ert-live-bcbs15228.siliconweb.com/media/ert_3/ert_3.m3u8

**Comment by freearhey** [comment]
@exyanis Most of the links are already on the playlist, and I added the rest.
