### ISSUE TITLE
Fix: Astro Supersports

### ISSUE THREAD

**Issue by sogalawson** [iptv-org/iptv#2344]
***Channel Name: Astro Supersport 1 to 4
***Broken Link (from playlist): Index and Malaysia 
***Possible Replacement (optional):*** xxx
***Notes (optional): Sorry but they don't still work

**Comment by Sphinxroot** [comment]
what player are you using ?

because they work  
https://i.imgur.com/57MvsfM.png

**Comment by sogalawson** [comment]
The IPTV pro app.

**Comment by freearhey** [comment]
@sogalawson The thing is that the links are not yet in the public playlist, tomorrow they should be updated.
