### ISSUE TITLE
Ukrainian Request Channels

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#2346]
List of requests for Ukrainian channels from other issues:

- [x] [СТБ](https://www.stb.ua/ru/) (#2254) (added via https://github.com/iptv-org/iptv/commit/9592ee40059af12d76851660e5a4ea0558be4c7f)

**Comment by Sphinxroot** [comment]
hope its the one 

#EXTINF:-1 tvg-logo="https://i.imgur.com/Av0pftd.png" group-title="Україна",СТБ
http://188.35.9.11:11021/j

**Comment by freearhey** [comment]
@Sphinxroot Thanks!
