### ISSUE TITLE
Lebanese Request Channels

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#2347]
List of requests for Lebanese channels from other issues:

- [x] [Al Jadeed](https://www.lyngsat.com/tvchannels/lb/Al-Jadeed.html) (#2097) (added via #2428)

**Comment by LaneSh4d0w** [comment]
http://146.59.230.10:8080/live/tdn/88164661328/10008.m3u8 ?

**Comment by freearhey** [comment]
@LaneSh4d0w It doesn't work for me.
<img width="397" alt="Captura de pantalla 2021-04-05 a las 20 21 37" src="https://user-images.githubusercontent.com/7253922/113603358-8819b880-964c-11eb-9964-8b33f8daa945.png">

**Comment by LaneSh4d0w** [comment]
Interesting,.. works on my side... possible geolock ?
![vlcsnap-2021-04-05-19h23m52s001](https://user-images.githubusercontent.com/30985701/113603638-76ccae00-9644-11eb-8f0e-ee6e6f4cc30d.png)

**Comment by LaneSh4d0w** [comment]
Now this link doesn't work. It is weird indeed. Let me see.

**Comment by jad222** [comment]
#2428 Fix
