### ISSUE TITLE
Broken Stream: TV Tokyo

### ISSUE THREAD

**Issue by x23323** [iptv-org/iptv#2363]
Channel Name: TV Tokyo
Broken Link (from playlist): JP
Notes (optional): Stream works but stops every now and then. I get a 403 forbidden error message. Same issue with the new Tokyo MX link.

**Comment by LaneSh4d0w** [comment]
One of the only reliable ways I could think is actually trying to use the ok.ru links. Thing is we would need to actually need to refresh streams a few times to make it work flawlessly I suppose.

**Comment by freearhey** [comment]
Closed in favor #1938
