### ISSUE TITLE
Add: xxx Pluto Channels for anime,Movies,Sports,news,Live Shows,ect(Sub section)

### ISSUE THREAD

**Issue by RetroGamer2020** [iptv-org/iptv#2369]
**Channel Name:** xxx
**Country:** xxx
**Language:** xxx
**External Link (optional):** xxx
**Notes (optional):** xxx

**Comment by RetroGamer2020** [comment]
Can u add more pluto based channels thanks(All Anime,movies,Sports,Live tv)

**Comment by freearhey** [comment]
Please read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel) next time before posting your request.
