### ISSUE TITLE
Greek channels

### ISSUE THREAD

**Issue by iikostas1** [iptv-org/iptv#2370]
check out this list..
https://github.com/free-greek-iptv/greek-iptv/blob/master/Greekstreamtv.m3u

**Comment by LaneSh4d0w** [comment]
Does this by any chance would mean you would like to see some channels ? :)

There is some available on the "gr" channels, if you want to take a look.

**Comment by freearhey** [comment]
Added via https://github.com/iptv-org/iptv/commit/d6a6410337546066e30e9a7931f8d89b6b93646e
