### ISSUE TITLE
121.130.84.30 Private Server!! Delete!!

### ISSUE THREAD

**Issue by futurehd71** [iptv-org/iptv#2374]
121.130.84.30 is a private server.
It may be a legal issue, so please delete it as soon as possible!!

**Comment by freearhey** [comment]
@futurehd71 If you want the links to channels you own to be removed from the repository, publish your DMCA notice with the names of channels, then send us a link to it and we will remove them from the playlist within one business day.

**Comment by freearhey** [comment]
Duplicate https://github.com/iptv-org/iptv/issues/2375
