### ISSUE TITLE
****** DMCA NOTICE !!!! ******* 

### ISSUE THREAD

**Issue by forestman71** [iptv-org/iptv#2375]
****** DMCA NOTICE !!!! *******

link URL : https://github.com/iptv-restream/iptv-channels

The M3U Channel-files below have copyright-related issues, so please take action to delete them
===============================
M3U File list 
-----------------------------------------------------
index.m3u
index.language.m3u
index.category.m3u
index.country.m3u
kr.m3u
===============================

#EXTINF:-1 tvg-id="ChannelAPlus.kr" tvg-name="ChannelAPlus" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C17141.png" tvg-url="" group-title="",ChannelAPlus
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C17141&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="ChunghwaTV.kr" tvg-name="Chunghwa TV" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C00544.png" tvg-url="" group-title="",Chunghwa TV
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C00544&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="JTBC.kr" tvg-name="JTBC" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C01582.png" tvg-url="" group-title="",JTBC
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C01582&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="JTBCGolf.kr" tvg-name="JTBC Golf" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C00588.png" tvg-url="" group-title="",JTBC Golf
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C00588&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="JTBCGolfSports.kr" tvg-name="JTBC Golf&Sports" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C00805.png" tvg-url="" group-title="",JTBC Golf&Sports
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C00805&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="JTBC2.kr" tvg-name="JTBC2" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C15741.png" tvg-url="" group-title="",JTBC2
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C15741&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="JTBC4.kr" tvg-name="JTBC4" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C22041.png" tvg-url="" group-title="",JTBC4
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C22041&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="MBN.kr" tvg-name="MBN" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C00708.png" tvg-url="" group-title="",MBN
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C00708&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="MBNPlus.kr" tvg-name="MBN Plus" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C17142.png" tvg-url="" group-title="",MBN Plus
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C17142&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="Mnet.kr" tvg-name="Mnet" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C00579.png" tvg-url="" group-title="",Mnet
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C00579&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="NickelodeonKorea.us" tvg-name="Nickelodeon Korea" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C43241.png" tvg-url="" group-title="",Nickelodeon Korea
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C43241&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="OtvN.kr" tvg-name="O tvN" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C01143.png" tvg-url="" group-title="",O tvN
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C01143&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="OGN.kr" tvg-name="OGN" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C00590.png" tvg-url="" group-title="",OGN
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C00590&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="Olive.kr" tvg-name="Olive" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C00575.png" tvg-url="" group-title="",Olive
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C00575&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="Onstyle.kr" tvg-name="Onstyle" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C01142.png" tvg-url="" group-title="",Onstyle
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C01142&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="SBSBiz.kr" tvg-name="SBS Biz" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C15846.png" tvg-url="" group-title="",SBS Biz
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C15846&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="TheKPOP.kr" tvg-name="The K-POP" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C43342.png" tvg-url="" group-title="",The K-POP
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C43342&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="TVChosun.kr" tvg-name="TV Chosun" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C01581.png" tvg-url="" group-title="",TV Chosun
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C01581&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="TVChosun2.kr" tvg-name="TV Chosun 2" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C00585.png" tvg-url="" group-title="",TV Chosun 2
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C00585&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="XtvN.kr" tvg-name="XtvN" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C01141.png" tvg-url="" group-title="",XtvN
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C01141&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="YonhapNewsTV.kr" tvg-name="YonhapNewsTV" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C01723.png" tvg-url="" group-title="",YonhapNewsTV
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C01723&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="YTN.kr" tvg-name="YTN" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C00593.png" tvg-url="" group-title="",YTN
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C00593&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="YTN2.kr" tvg-name="YTN2" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C01101.png" tvg-url="" group-title="",YTN2
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C01101&q=SD&apikey=cit1254678
#EXTINF:-1 tvg-id="YTNScience.kr" tvg-name="YTNScience" tvg-country="KR" tvg-language="" tvg-logo="http://image.tving.com/upload/cms/caic/CAIC1900/C15347.png" tvg-url="" group-title="",YTNScience
http://121.130.84.30:9999/klive/api/url.m3u8?m=url&s=tving&i=C15347&q=SD&apikey=cit1254678

**Comment by LaneSh4d0w** [comment]
???

Someone copied on someone here.
Why is it that the presentation looks absolutely the same as ours, especially the readme ? Just saying.

**Comment by freearhey** [comment]
@futurehd71 Please do some more research, this message is not a DMCA notice.
