### ISSUE TITLE
RMC Sport 1

### ISSUE THREAD

**Issue by Bianco05** [iptv-org/iptv#2378]
could you please see if it's possible to add this channel in the French list ? Thks

**Channel Name: RMC SPORT 1
**Channel ID: RMCSport1.fr
**Country: France
**Language: French
**External Link (optional):** xxx
**Notes (optional):** xxx

**Comment by freearhey** [comment]
Closed in favor #1939

**Comment by LaneSh4d0w** [comment]
Obvious issue close.
