### ISSUE TITLE
FIx : WGN 9

### ISSUE THREAD

**Issue by nnadie9** [iptv-org/iptv#2384]
***Channel Name:WGN 9
***Broken Link (from playlist):EXTINF:-1 tvg-id="WGN9Chicago.us" tvg-name="WGN9 (Chicago)" tvg-country="US" tvg-language="English" tvg-logo="" group-title="Local",WGN9 (Chicago) (720p)
https://cdn006.teleuptv.net/mBm5MQ50rA/playlist
***Possible Replacement (optional):*** xxx
***Notes (optional):*** xxx

**Comment by freearhey** [comment]
Thank you for reporting this. The broken link has already been removed from the playlist. As soon as a replacement is available, we will add the channel back.

**Comment by freearhey** [comment]
Closed in favor #1942
