### ISSUE TITLE
Fix: esAsturiasTV

### ISSUE THREAD

**Issue by gtrabanco** [iptv-org/iptv#2386]
***Channel Name:*** esAsturiasTV
***Broken Link (from playlist):*** es
***Possible Replacement (optional):*** https://5df8a678a3840.streamlock.net/8032/8032/chunklist_w450507485.m3u8
***Notes (optional):*** Not sure about the possible replacement, please check. The website were I got that link is: https://www.esasturias.tv/directo

**Comment by freearhey** [comment]
Link updated via https://github.com/iptv-org/iptv/commit/ccbf0102ffa34f63af5985862fe850f7a7956bdb
