### ISSUE TITLE
My submissions....

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#2392]
...are getting through I hope? I take it that no feedback means all things are well, or am I wrong?

**Comment by freearhey** [comment]
Sadly, but no, we didn't get anything. The thing is that in order for us to see your changes you have to make a "pull request" with them. And yes, if you send us your changes and they are approved, you will automatically be notified.

**Comment by LaneSh4d0w** [comment]
@AntiPontifex By looking at your GitHub, you indeed made some changes, but you haven't made a PR yet. What you need to do is simply make a pull request, making sure you compare iptv-org/iptv@master and, in your example, AntiPontifex/iptv@master.

**Comment by AntiPontifex** [comment]
I *think* I've resolved my error. Please provide feedback as soon as possible. Thank you both for your assistance :)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/pull/2398#issuecomment-817429809
