### ISSUE TITLE
Russian list

### ISSUE THREAD

**Issue by Sphinxroot** [iptv-org/iptv#2394]
#EXTINF:-1,mtv_dance HD
http://188.40.68.167/russia/mtv_dance/playlist.m3u8
#EXTINF:-1,mtv_hits
http://188.40.68.167/russia/mtv_hits/playlist.m3u8
#EXTINF:-1,gulli_girl
http://188.40.68.167/russia/gulli_girl/playlist.m3u8
#EXTINF:-1,moskva24 HD
http://188.40.68.167/russia/moskva24/playlist.m3u8
#EXTINF:-1,komediya
http://188.40.68.167/russia/komediya/playlist.m3u8
#EXTINF:-1,paramount
http://188.40.68.167/russia/paramount/playlist.m3u8
#EXTINF:-1,kinoseriya
http://188.40.68.167/russia/kinoseriya/playlist.m3u8
#EXTINF:-1,paramount_comedy
http://188.40.68.167/russia/paramount_comedy/playlist.m3u8
#EXTINF:-1,vip_comedy HD
http://188.40.68.167/russia/vip_comedy/playlist.m3u8
#EXTINF:-1,ani
http://188.40.68.167/russia/ani/playlist.m3u8
#EXTINF:-1,dorama
http://188.40.68.167/russia/dorama/playlist.m3u8
#EXTINF:-1,tiji
http://188.40.68.167/russia/tiji/playlist.m3u8
#EXTINF:-1,telekafe
http://188.40.68.167/russia/telekafe/playlist.m3u8
#EXTINF:-1,rutv
http://188.40.68.167/russia/rutv/playlist.m3u8
#EXTINF:-1,rtg HD
http://188.40.68.167/russia/rtg/playlist.m3u8
#EXTINF:-1,radost_moya
http://188.40.68.167/russia/radost_moya/playlist.m3u8
#EXTINF:-1,ocean
http://188.40.68.167/russia/ocean/playlist.m3u8
#EXTINF:-1,mir24
http://188.40.68.167/russia/mir24/playlist.m3u8
#EXTINF:0,fox
http://188.40.68.167/russia/fox_russia_sd/playlist.m3u8
#EXTINF:-1,jimjam
http://188.40.68.167/russia/jimjam/playlist.m3u8
#EXTINF:-1,disney
http://188.40.68.167/russia/disney/playlist.m3u8
#EXTINF:-1,avto24
http://188.40.68.167/russia/avto24/playlist.m3u8
#EXTINF:-1,mir_seriala
http://188.40.68.167/russia/mir_seriala/playlist.m3u8
#EXTINF:-1,moya_planeta
http://188.40.68.167/russia/moya_planeta/playlist.m3u8

**Comment by freearhey** [comment]
Added.
