### ISSUE TITLE
This week all Mediaset channels stopped working. 

### ISSUE THREAD

**Issue by exigente82** [iptv-org/iptv#2395]
Can anyone fix it? Thank you.

#EXTM3U
#EXTINF:-1 tvg-id="20Mediaset.it" tvg-name="20 Mediaset" tvg-country="IT" tvg-language="Italian" tvg-logo="https://upload.wikimedia.org/wikipedia/it/e/e4/20_Mediaset_-_Logo_2018.svg" group-title="",20 Mediaset
https://live3-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(lb)/index.m3u8
#EXTINF:-1 tvg-id="Canale5.it" tvg-name="Canale 5" tvg-country="IT" tvg-language="Italian" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/0/02/Canale_5_-_2018_logo.svg" group-title="",Canale 5
https://live3-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(C5)/index.m3u8
#EXTINF:-1 tvg-id="Cine34.it" tvg-name="Cine 34" tvg-country="IT" tvg-language="Italian" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/d/d7/Cine34_logo.svg" group-title="",Cine 34
https://live3-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(b6)/index.m3u8
#EXTINF:-1 tvg-id="Focus.it" tvg-name="Focus" tvg-country="IT" tvg-language="Italian" tvg-logo="https://upload.wikimedia.org/wikipedia/it/1/11/Focus_Logo.svg" group-title="",Focus
https://live3-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(fu)/index.m3u8
#EXTINF:-1 tvg-id="Iris.it" tvg-name="Iris" tvg-country="IT" tvg-language="Italian" tvg-logo="" group-title="",Iris
https://live3-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(ki)/index.m3u8
#EXTINF:-1 tvg-id="Italia1.it" tvg-name="Italia 1" tvg-country="IT" tvg-language="Italian" tvg-logo="" group-title="",Italia 1
https://live3-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(i1)/index.m3u8
#EXTINF:-1 tvg-id="Italia2.it" tvg-name="Italia 2" tvg-country="IT" tvg-language="Italian" tvg-logo="" group-title="",Italia 2
https://live3-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(i2)/index.m3u8
#EXTINF:-1 tvg-id="La5.it" tvg-name="La 5" tvg-country="IT" tvg-language="Italian" tvg-logo="" group-title="",La 5
https://live3-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(ka)/index.m3u8
#EXTINF:-1 tvg-id="MediasetExtra.it" tvg-name="Mediaset Extra" tvg-country="IT" tvg-language="Italian" tvg-logo="" group-title="",Mediaset Extra
https://live3-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(kq)/index.m3u8
#EXTINF:-1 tvg-id="Rete4.it" tvg-name="Rete 4" tvg-country="IT" tvg-language="Italian" tvg-logo="" group-title="",Rete 4
https://live3-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(r4)/index.m3u8
#EXTINF:-1 tvg-id="TGCom24.it" tvg-name="TGCom 24" tvg-country="IT" tvg-language="Italian" tvg-logo="" group-title="News",TGCom 24
https://live2-radio-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(kf)/index.m3u8
#EXTINF:-1 tvg-id="TopCrime.it" tvg-name="Top Crime" tvg-country="IT" tvg-language="Italian" tvg-logo="" group-title="",Top Crime
https://live3-radio-mediaset-it.akamaized.net/content/hls_h0_clr_vos/live/channel(lt)/index.m3u8

**Comment by LaneSh4d0w** [comment]
Take off the "-radio-" mention on the Mediaset links and it seems to respond. However, there might be a geolock.

**Comment by YacineBoussoufa** [comment]
Hi, from [what I have read](https://www.mediasetplay.mediaset.it/article/mediasetplay/mediasetplay/mediaset-play-infinity-nuova-piattaforma_SE000000000675_a21691) Mediaset has merged with Infinity (paid platform) for this reason they have most likely changed the links of their platforms and they have geolocked them.

**Comment by LaneSh4d0w** [comment]
> 
> 
> Hi, from [what I have read](https://www.mediasetplay.mediaset.it/article/mediasetplay/mediasetplay/mediaset-play-infinity-nuova-piattaforma_SE000000000675_a21691) Mediaset has merged with Infinity (paid platform) for this reason they have most likely changed the links of their platforms and they have geolocked them.

Indeed, this is what happened. I've made a PR that fixes the links and permits Italian users to use them again.

**Comment by freearhey** [comment]
Fixed via https://github.com/iptv-org/iptv/pull/2396

**Comment by exigente82** [comment]
Yes. I was referring to television channels and not radio stations.

After your explanations, I have tried a VPN different than ExpressVPN and it worked.

Rai Play does not work outside of Italy either but the links you have given us work without the need for a VPN.

Thanks for all.
