### ISSUE TITLE
Affing Sky Sport Germany

### ISSUE THREAD

**Issue by IchDu21** [iptv-org/iptv#24]
Hello please can You add Sky Sport Package from Germany (SkySport 1,2, Bundesliga, Austria...) ? Thanks You!

**Comment by freearhey** [comment]
- [ ] Sky Sport 1 
- [ ] Sky Sport 2 
- [x] Sky Sport Bundesliga
https://github.com/iptv-org/iptv/blob/6da3b46f3b9f7ecc5d23feda8c4efee0100eba49/channels/de.m3u#L380-L383
- [x] Sky Sport Austria
https://github.com/iptv-org/iptv/blob/6da3b46f3b9f7ecc5d23feda8c4efee0100eba49/channels/de.m3u#L378-L379

**Comment by freearhey** [comment]
We cannot add links to channels showing Bundesliga matches due to complaints from rights holders. More details here: https://github.com/github/dmca/blob/master/2020/09/2020-09-16-dfl.md
