### ISSUE TITLE
Propose: Add (optional) sub- and supra-national groupings/attributes

### ISSUE THREAD

**Issue by loucasal** [iptv-org/iptv#2400]
Currently the playlist by country is both very long and very uneven in group size.

It is likely that many users would benefit from being able to quickly aggregate sparsely populated groups and to break down the larger ones into more manageable subgroups.

Similarly, users who are more interested in a specific region would probably want a more detailed breakdown there, while a higher level of aggregation would be sufficient for them for other regions.

Obviously this can be customised by each individual user, but it would be more efficient if the main building blocks were provided at the source.

There are probably multiple ways to achieve these goals and I am not too sure whether extra attributes or higher/lower-level groups are the best way to go. I provide some suggestions below as a way to start the discussion - it is not an exhaustive list by any means. 

- To make it easier to aggregate countries, add a region attribute reusing the [region codes](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#supported-region-codes) already in use within the project, or, alternatively, nest the country groups within their respective continent.
- To make it easier to break down larger country groups (suggestion 1), add a target (or similar) attribute/subgrouping based on whether a channel broadcasts local, national or international content. E.g. think of BBC One Wales vs BBC News vs BBC World News.
- To make it easier to break down larger country groups (suggestion 2), add a network (or similar) attribute/subgrouping based on whether the channel belongs to a specific network/service. E.g. think of the Pluto TV set of channels available in different countries.

What do you think? Would there be any interest in any of the above?

**Comment by LaneSh4d0w** [comment]
Sounds interesting for people who wants to get a more detailed / very well structured IPTV playlist.

I would personnally see the playlist like this.

EXAMPLE : index.country.m3u

-> Country -> Region -> Type of channel (General, Entertainment...) -> Channel.
