### ISSUE TITLE
Mbc arabic 360p

### ISSUE THREAD

**Issue by Ahmedupp** [iptv-org/iptv#2403]
Hallo!!
 
I need to find the link for mbc1 the arabic channel but with 360p 

The one i found here is 1080.

**Comment by LaneSh4d0w** [comment]
It's an adaptive playlist, which means that it looks after the bandwidth of your connection and make the changes linked to this by increasing or decreasing the quality of your stream. Why is it needed to provide a 360p stream ?

**Comment by freearhey** [comment]
Done via https://github.com/iptv-org/iptv/commit/95c4c46aad08226f2dcc2150f4473aafe20b2e52
