### ISSUE TITLE
https://rotana.net/live-elressalah/

### ISSUE THREAD

**Issue by iptvchecker** [iptv-org/iptv#2404]
**Channel Name:** el-ressalah
**Country:** KSA
**Language:** Arabic
**External Link (optional):** https://rotana.net/live-elressalah/
**Notes (optional):** xxx

**Comment by iptvchecker** [comment]
El-Ressalah is not available in the list of Rotana.net list, although you can access it via https://rotana.net/live-elressalah/

**Comment by trancer1994** [comment]
The link I was able to get from the website was https://rotananet.hibridcdn.net/rotana/risala_abr/rotana/risala_360p/chunks.m3u8?p=50&s=1618316615&e=1618403015&cf=1618403015&h=926b63e5ea65d204149862d2bfe11fa6 but you can remove the tokens and it still works. So https://rotananet.hibridcdn.net/rotana/risala_abr/rotana/risala_360p/chunks.m3u8 It depends what source the links are from already though.

**Comment by freearhey** [comment]
Added via 6ed30280

**Comment by iptvchecker** [comment]
Thank you for adding this channel to sa.m3u. Can you, also add it to the list of Arabic channels under https://iptv-org.github.io/iptv/languages/ara.m3u. The category is Religion. There are other Rotana channels in this list too, so it helps to have them together!

**Comment by freearhey** [comment]
The channel will automatically be added to the `languages/ara.m3u` playlist during the daily update. So tomorrow it will already be there.

**Comment by iptvchecker** [comment]
Thanks!

**Comment by iptvchecker** [comment]
The Al-Resalah (originally from https://rotana.net/live-elressalah/), appears fine on the list of Arabic channels on ara.m3u. The sad news it is not working. The wait circle keeps spinning and that is it! 

Since it's part of the Rotana collection on IPTV-org, I noticed the these channels sometimes have two listings; one that spins and the other works. Only Rotana Comedy and Al-Resalah each have one listing that does not work!

It will be great if they're fixed, especially Al-Resalah, since it's Ramadan and usually it has good programs that my family likes to follow.

**Comment by freearhey** [comment]
@iptvchecker I have added some other options for Al-Resalah. I hope this helps, but unfortunately we have no control over the broadcast itself so I just can't guarantee their quality.

**Comment by LaneSh4d0w** [comment]
> 
> 
> The Al-Resalah (originally from https://rotana.net/live-elressalah/), appears fine on the list of Arabic channels on ara.m3u. The sad news it is not working. The wait circle keeps spinning and that is it!
> 
> Since it's part of the Rotana collection on IPTV-org, I noticed the these channels sometimes have two listings; one that spins and the other works. Only Rotana Comedy and Al-Resalah each have one listing that does not work!
> 
> It will be great if they're fixed, especially Al-Resalah, since it's Ramadan and usually it has good programs that my family likes to follow.

I'll get a check on that. Links don't seem to load on my side too.

Ramadan Mubarak to you and your family.

**Comment by iptvchecker** [comment]
Thank you for the Ramadan wishes, same to you if you observe!

It seems weird that they geoblock if you're coming from North America, which is the case when having Torbrowser exit in that region. The content is available on their website for free, and iptv if you're elsewhere in the world! IPTV-Org has a list of Rotana channels (3 Cinema channels, Drama, etc) that work fine anywhere in the World. Only Comedy and Al-Ressahal (both by Rotana and accessible over Torbrowser from their site with Exit nodes not in North America) but are not functioning using IPTV-Org links!

These channels are available 24/7 on the website.

**Comment by LaneSh4d0w** [comment]
Don't ask how and why, but it's blocked in France, but from a Tor exit node (Netherlands), it works.

https://rotananet.hibridcdn.net/rotana/risala_abr/rotana/risala_480p/chunks.m3u8

**Comment by LaneSh4d0w** [comment]
https://hiplayer.hibridcdn.net/p/rotana-risala

**Comment by iptvchecker** [comment]
This is interesting! Tor exist in France should be same!

https://rotananet.hibridcdn.net/rotana/risala_abr/rotana/risala_1080p/chunks.m3u8 (There are 5 different resolutions links from this url.) None of them work!

It seems that all the Rotana and other channels that work on IPTV-Org are coming from links with "shahid.net" in the URL. I am surprised why they'd be hosting all Rotana channels except for Al-Ressalah! Would it be possible to post a request on your github page to have them add that?

**Comment by LaneSh4d0w** [comment]
Shahid links for some : 

#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Arabic" tvg-logo="https://rotana.net/assets/themes/TriTheme-new/images/channels/cinema-egypt.png" group-title="",Rotana Cinema HD
https://shls-rotanacinema-egy-prod-dub.shahid.net/out/v1/c39c0ecbcbdb46e890e91106776397a8/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Arabic" tvg-logo="https://rotana.net/assets/themes/TriTheme/images/channels/cinema.png" group-title="",Rotana Cinema HD KSA
https://shls-rotanacinema-ksa-prod-dub.shahid.net/out/v1/6cee1c57ea7841e697eb15cefc98e0a6/index.m3u8
#EXTINF:-1 tvg-id="Rotana Classic ARB" tvg-name="Rotana Classic ARB" tvg-language="Arabic" tvg-logo="https://rotana.net/assets/themes/TriTheme/images/channels/classic.png" group-title="",Rotana Classic HD
https://shls-rotanaclassic-prod-dub.shahid.net/out/v1/4eebed211c8441228321b4f67a46c5a5/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Arabic" tvg-logo="https://rotana.net/assets/themes/TriTheme/images/channels/drama.png" group-title="",Rotana Drama HD
https://shls-rotanadrama-prod-dub.shahid.net/out/v1/20c617b40dc743589ecc9d08d9d3345d/index.m3u8
#EXTINF:-1 tvg-id="Rotana Khalijia ARB" tvg-name="Rotana Khalijia ARB" tvg-language="Arabic" tvg-logo="https://rotana.net/assets/themes/TriTheme/images/channels/khalijiat.png" group-title="",Rotana Khalijia HD
https://shls-rotanakhalijia-prod-dub.shahid.net/out/v1/a639fd49db684f1b8c063d398101a888/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Arabic" tvg-logo="https://rotana.net/assets/themes/TriTheme/images/channels/kids.png" group-title="",Rotana Kids
https://shls-rotanakids-prod-dub.shahid.net/out/v1/df6e0eb3cdc4410b98209aafc8677cef/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Arabic" tvg-logo="https://rotana.net/assets/themes/TriTheme-new/images/channels/music.png" group-title="",Rotana Music
https://shls-rotanamusic-prod-dub.shahid.net/out/v1/edfe0095261648908a3a931b72489f3f/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Arabic" tvg-logo="https://rotana.net/assets/themes/TriTheme-new/images/channels/hd.png" group-title="",Rotana+
https://shls-rotanaplus-prod-dub.shahid.net/out/v1/1fc6103458be480b96e6a574b00fe1c0/index.m3u8

**Comment by iptvchecker** [comment]
These are the Rotana channels that work without proxy. For example Comedy is not on this list. The Comedy one which is not from this server does not work without tor proxy! Not sure if someone can request them to host Comedy and Al-Resalah.

**Comment by Oklahoma1122** [comment]
#EXTINF:-1 tvg-id="exampletv.us" tvg-name="Example TV" tvg-language="English" tvg-logo="http://example.com/channel-logo.png" group-title="News",Example TV
http://example.com/stream.m3u8
