### ISSUE TITLE
Channel List of Kannada langauge is not working

### ISSUE THREAD

**Issue by maheshbisl** [iptv-org/iptv#2406]
Here are the Kannada Channels that are in your database.  All are from India.

Please fix in the file. channels/in.m3u

#EXTM3U

#EXTINF:-1 tvg-id="DighvijayNews24x7.in" tvg-name="Dighvijay News 24x7" tvg-country="IN" tvg-language="Kannada" tvg-logo="https://i.imgur.com/wdE7gxU.png" group-title="News", ದಿಗ್ವಿಜಯ ಸುದ್ದಿ Dighvijay
https://vidcdn.vidgyor.com/dighvijay-origin/liveabr/playlist.m3u8

#EXTINF:-1 tvg-id="KasthuriTV.in" tvg-name="Kasthuri TV" tvg-country="IN" tvg-language="Kannada" tvg-logo="https://en.wikipedia.org/wiki/Kasthuri_(TV_channel)#/media/File:Kasthuri-TV-logo.jpg" group-title="Entertainment", ಕಸ್ತೂರಿ ಕನ್ನಡ Kasthuri (576p)
http://103.199.161.254/Content/kasthuritv/Live/Channel(KasthuriTV)/index.m3u8

#EXTINF:-1 tvg-id="News18Kannada.in" tvg-name="News 18 Kannada" tvg-country="IN" tvg-language="Kannada" tvg-logo="https://static.kannada.news18.com/kannada/uploads/2020/03/Kannada1.png" group-title="News", ನ್ಯೂಸ್ ೧೮ ಕನ್ನಡ News 18
https://news18kannada-lh.akamaihd.net/i/n18kannada_1@372918/index_4_av-p.m3u8

#EXTINF:-1 tvg-id="PublicMusic.in" tvg-name="Public Music" tvg-country="IN" tvg-language="Kannada" tvg-logo="https://en.wikipedia.org/wiki/Public_Music#/media/File:Public_Music_Kannada_Channel_Logo.jpg" group-title="Music", ಪಬ್ಲಿಕ್ ಸಂಗೀತ Public Music (576p)
http://103.199.161.254/Content/publicmusic/Live/Channel(PublicMusic)/index.m3u8

#EXTINF:-1 tvg-id="SuvarnaNews24x7.in" tvg-name="Suvarna News 24×7" tvg-country="IN" tvg-language="Kannada" tvg-logo="https://en.wikipedia.org/wiki/Suvarna_News#/media/File:Suvarna_News_New_Logo.jpg" group-title="News", ಸುವರ್ಣ ಸುದ್ದಿ 24×7 Suvarna (360p)
https://vidcdn.vidgyor.com/suvarna-origin/liveabr/suvarna-origin/live1/playlist.m3u8

#EXTINF:-1 tvg-id="TV9Kannada.in" tvg-name="TV9 Kannada" tvg-country="IN" tvg-language="Kannada" tvg-logo="https://d2jo35ozacw6sq.cloudfront.net/wp-content/themes/tv9kannada/images/Tv9-Kannada-57x57.png" group-title="News",  ಟಿವಿ೯ ಕನ್ನಡ TV9 (720p)
https://vidcdn.vidgyor.com/tv9kannada-origin/live/playlist.m3u8

Thanks

**Comment by freearhey** [comment]
Done.

**Comment by maheshbisl** [comment]
Thanks Mate
