### ISSUE TITLE
Fix: beIN SPORTS XTRA

### ISSUE THREAD

**Issue by exigente82** [iptv-org/iptv#2409]
***Channel Name: beIN SPORTS XTRA
***Broken Link (from playlist): #EXTINF:-1 tvg-id="beINSPORTSXTRA.qa" tvg-name="beIN SPORTS XTRA" tvg-country="QA" tvg-language="" tvg-logo="http://images.pluto.tv/channels/5df975e2b27cf5000921c102/colorLogoPNG.png" tvg-url="https://raw.githubusercontent.com/Fazzani/grab/master/merge.zip" group-title="Sport",beIN SPORTS XTRA
http://plutotv.vo.llnwd.net/m/hlslive/bein.m3u8?chname=bein&pub=0

**Comment by freearhey** [comment]
Broken link removed. As soon as a working version appears, we will return the channel to the playlist.
