### ISSUE TITLE
Fix: another beIN SPORTS XTRA

### ISSUE THREAD

**Issue by exigente82** [iptv-org/iptv#2410]
***Channel Name: beIN SPORTS XTRA
***Broken Link (from playlist):#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="" tvg-language="" tvg-logo="" tvg-url="" group-title="",beIN SPORTS XTRA
https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5df975e2b27cf5000921c102/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=740&deviceId=5df975e2b27cf5000921c102&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false
***Notes (optional): I have created another issue about a broken link from beIN SPORTS XTRA but this other is simply a link that does not even have translation as a channel in the code. It is entered in the file but without application.

**Comment by freearhey** [comment]
Broken link removed. As soon as a working version appears, we will return the channel to the playlist.
