### ISSUE TITLE
Add: Barça TV

### ISSUE THREAD

**Issue by exigente82** [iptv-org/iptv#2412]
**Channel Name: Barça TV
**Country: Spain
**Language: There are versions in spanish, catalan and english

Category: Sport

Thank you.

**Comment by Dum4G** [comment]
Tokenized, works for 35 seconds and needs reconnecting
http://209.222.101.100:25461/tv/tv/78706

@LaneSh4d0w

**Comment by LaneSh4d0w** [comment]
@Dum4G I'll need you to give me the website where you had this link. I'm gonna look on it soon.

**Comment by Dum4G** [comment]
> @Dum4G I'll need you to give me the website where you had this link. I'm gonna look on it soon.

It was another Github repo and the only link that doesn't steal someone elses account

**Comment by LaneSh4d0w** [comment]
> 
> 
> Tokenized, works for 35 seconds and needs reconnecting
> http://209.222.101.100:25461/tv/tv/78706
> 
> Needs your magic server assisstance maybe @LaneSh4d0w
> 
> UPD: aaaand I almost got banned for abusing it, had 403 for a brief moment. Perhaps, we should stop target this channel as it's not publicaly available @freearhey

It actually redirects to another IP that hosts the stream and also gives the token.

**Comment by LaneSh4d0w** [comment]
#EXTINF:-1,USA Latin Barca TV
http://209.222.101.100:25461/dalvin/dalvin/61880

**Comment by Dum4G** [comment]
Can't open them in VLC. Overall it's bad idea to try sources that shady for a channel that is under paywall

**Comment by LaneSh4d0w** [comment]
Those links seems to redirect to another XTream-Codes server : http://89.248.173.197:25461

**Comment by LaneSh4d0w** [comment]
Last time I had checked those things, it wasn't using tokened stuff, it was weirder. Glad to see they're "improving"
#EXTINF:-1,BARCA TV
http://dimapro.cz:8080/KzilaUMFaY/lUE9wE6vqE/38455

**Comment by LaneSh4d0w** [comment]
Yes, for now i'll close this. If I happen to find a link, it'll be added.

**Comment by freearhey** [comment]
@LaneSh4d0w please don't close the threads until the request is fulfilled so that others can see them too.

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w please don't close the threads until the request is fulfilled so that others can see them too.

Noted.

**Comment by exigente82** [comment]
It is not a pay channel within Catalonia, like many other channels that are geolocated on "our" list.

Thank you.

**Comment by Dum4G** [comment]
> It is not a pay channel within Catalonia, like many other channels that are geolocated on "our" list.

If you can find any website that is broadcasting this channel for free let us know

**Comment by LaneSh4d0w** [comment]
> It is not a pay channel within Catalonia, like many other channels that are geolocated on "our" list.
> 
> Thank you.

Well actually apart from those Xtream servers I can't seem to find anything.
