### ISSUE TITLE
Add your playlist in my IPTV application

### ISSUE THREAD

**Issue by rootalc** [iptv-org/iptv#2415]
Hi, can i add links to your playlist to my IPTV application?
https://github.com/rootalc/astroncia_iptv/blob/master/README.en.md
Thanks.

**Comment by themak1985** [comment]
We use The Unlicense license, you are free to do whatever you would like. It means you are free to do as you please. @freearhey correct?

**Comment by freearhey** [comment]
Yes, of course.
