### ISSUE TITLE
Bolivian Red Uno

### ISSUE THREAD

**Issue by southerndream56** [iptv-org/iptv#2417]
Could you please try to add Bolivian 1.TV channel Red Uno to the list...  it is streaming on:
https://www.reduno.com.bo/senal-en-vivo
Thanks

**Comment by LaneSh4d0w** [comment]
Scripted tokenisation :

**Comment by LaneSh4d0w** [comment]
Ah wait, nevermind, it seems Streann are... dumb ?

Red Uno Bolivia (La Paz) : https://ott.streann.com/loadbalancer/services/public/channels/5ea9f2d22cdc31ce152b0090/playlist.m3u8

**Comment by freearhey** [comment]
Added via https://github.com/iptv-org/iptv/commit/dfc62c86fd52789f1b4dc15120affe31815348b5

**Comment by southerndream56** [comment]
Thanks for adding it to the list..
Any idea why it works with VLC media player and not on Smart TV ( it says stream error ) with the same line....

**Comment by LaneSh4d0w** [comment]
> Thanks for adding it to the list..
> Any idea why it works with VLC media player and not on Smart TV ( it says stream error ) with the same line....

Not having a Smart TV myself I cannot answer this question sorry. Do you go through some sort of IPTV application ?

**Comment by southerndream56** [comment]
Yes,through Smart IPTV app.
