### ISSUE TITLE
Hy can I have please on this playlist more Romanian channels on my playlist digi24  pro TV  tv1000 tvr1 hbo Romania  antena1   channels the playlist it'https://iptv-org.github.io/languages/Ron.m3u 

### ISSUE THREAD

**Issue by ADI34com** [iptv-org/iptv#2429]
**Channel Name:** xxx
**Country:** xxx
**Language:** xxx
**External Link (optional):** xxx
**Notes (optional):** xxx

**Comment by freearhey** [comment]
@ADI34com Please read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#add-or-replace-a-stream) before posting your request next time.
