### ISSUE TITLE
Modern Greek?

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#2431]
Frankly, I find this language option in the metadata rather excessive. Are there channels out there that are using Archaic or Koine Greek? I think Greek as a choice is sufficient. Just an opinion...

**Comment by freearhey** [comment]
We take the names of the languages from [ISO 639-3](https://iso639-3.sil.org/code_tables/639/data?title=&field_iso639_cd_st_mmbrshp_639_1_tid=94671&name_3=greek&field_iso639_element_scope_tid=All&field_iso639_language_type_tid=51&items_per_page=500) table.
