### ISSUE TITLE
Add: The Country Network

### ISSUE THREAD

**Issue by poltom30** [iptv-org/iptv#2432]
**Channel Name:** THE COUNTRY NETWORK
**Country:** USA
**Language:** ENGLISH
**External Link (optional):** https://watch.tcncountry.net/
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
https://ott.streann.com/loadbalancer/services/public/channels/5fac1ab92cdcdff351a7123c/playlist.m3u8

**Comment by poltom30** [comment]
thank you man!

**Comment by poltom30** [comment]
thank you!

would it be possible to add this channel to

https://iptv-org.github.io/iptv/index.m3u ?



Küldte a Windows 10 Posta

Feladó: LaneSh4d0w
Elküldve: 2021. április 20., kedd 13:18
Címzett: iptv-org/iptv
Másolatot kap: poltom30; Author
Tárgy: Re: [iptv-org/iptv] Add: xxx (#2432)

https://ott.streann.com/loadbalancer/services/public/channels/5fac1ab92cdcdff351a7123c/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
I don't have direct access to adding links in this repository. The only thing I can do is to ping @freearhey in this discussion. :)

**Comment by poltom30** [comment]
thanks!

**Comment by freearhey** [comment]
@LaneSh4d0w Feel free to make a pull request with this link, just read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#add-or-replace-a-stream) before you do it.

**Comment by poltom30** [comment]
Hi,

Please bring back this channel. 

Thank you!

Tom
