### ISSUE TITLE
WWE Channel

### ISSUE THREAD

**Issue by sogalawson** [iptv-org/iptv#2434]
**Channel Name: WWE CHANNEL 
**Country: USA & rest of the world
**Language: English 
**External Link (optional):** xxx
**Notes (optional):** xxx

**Comment by Oklahoma1122** [comment]
guard ARWorldTrackingConfiguration.isSupported else {
            fatalError("""
                ARKit is not available on this device. For apps that require ARKit
                for core functionality, use the `arkit` key in the key in the
                `UIRequiredDeviceCapabilities` section of the Info.plist to prevent
                the app from installing. (If the app can't be installed, this error
                can't be triggered in a production scenario.)
                In apps where AR is an additive feature, use `isSupported` to
                determine whether to show UI for launching AR experiences.
            """) // For details, see https://developer.apple.com/documentation/arkit
        }

        return true
    }
}

**Comment by freearhey** [comment]
Closed in favor #1942

**Comment by Central302** [comment]
close, WWE Network Has Been Added.
