### ISSUE TITLE
Propose: m3u to EPG data mapping

### ISSUE THREAD

**Issue by danduh** [iptv-org/iptv#2438]
Hello. 
Maybe I'm missing something, but I can't find the way to map channels from m3u to EPG data from xml.
none of the tvg-id="??" from m3u file is equal to <channel id="??"> in xml... 

Please advise.

**Comment by freearhey** [comment]
Hi. You are absolutely right, and I'm already working on it. And as soon as everything is ready, we will update all the IDs and post links to the corresponding programs.
