### ISSUE TITLE
Add: Animax + Aniplus ( Malaysian )

### ISSUE THREAD

**Issue by YunomiSakura** [iptv-org/iptv#2439]
**Channel Name:** Animax + Aniplus ( Malaysian Sub )
**Country:** Japan
**Language:** Japan , Malaysian
**External Link (optional):**
Aniplus : http://210.210.155.35/dr9445/h/h02/01.m3u8
Animax : http://210.210.155.35/dr9445/h/h144/01.m3u8
 http://210.210.155.35/dr9445/h/h02/01.m3u8
**Notes (optional):** 
1.Channel are geoblock ( need fake ip to India )
2.Logo : 
Aniplus : https://images.app.goo.gl/EN4bsBc6zy8CmYuy8
Animax : https://images.app.goo.gl/XsxyVFZwzqKwkdQF9

**Comment by LaneSh4d0w** [comment]
Channels are both working with an US IP.

![vlcsnap-2021-04-20-15h27m30s052](https://user-images.githubusercontent.com/30985701/115403709-f6ce4880-a1ec-11eb-9fe1-49c5a6c6d326.png)

![vlcsnap-2021-04-20-15h27m01s455](https://user-images.githubusercontent.com/30985701/115403688-f2a22b00-a1ec-11eb-9337-836922141b35.png)

**Comment by freearhey** [comment]
Done.
