### ISSUE TITLE
Add: KCTV

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#2457]
please can you extract a link of the nktv from this site 
https://multistre.am/elufatv/layout0/

**Comment by Sphinxroot** [comment]
sorry can`t do  since its a twitch channel 

but if you use kodi + the twitch + Playlistloader  you can use your own .m3u file  local or remote  and add this in it

# https://www.twitch.tv/elufatv
#EXTINF:-1 tvg-logo="https://i.imgur.com/yGudWOJ.jpg" group-title="",Elufatv (TWITCH)
plugin://plugin.video.twitch/?channel_id=638802386&amp;mode=play

the token is handle by the plugin so no more link to edit 

hope it help :)

**Comment by LaneSh4d0w** [comment]
I think we already have a link for the North Korean Central Television.

**Comment by hemzaberkane** [comment]
> sorry can`t do since its a twitch channel
> 
> but if you use kodi + the twitch + Playlistloader Addons ,you can use your own .m3u file local or remote and add this in it
> 
> # https://www.twitch.tv/elufatv
> #EXTINF:-1 tvg-logo="https://i.imgur.com/yGudWOJ.jpg" group-title="",Elufatv (TWITCH)
> plugin://plugin.video.twitch/?channel_id=638802386&mode=play
> 
> the token is handle by the plugin so no more link to edit
> 
> hope it help :)

I DONT KNOW HOW TO USE IT WITH KODI §

**Comment by hemzaberkane** [comment]
> I think we already have a link for the North Korean Central Television.
> 
> https://github.com/iptv-org/iptv/blob/master/channels/kp.m3u

ITS AN SD CHANNEL BUT THE LINK OF TWITCH IN HD

**Comment by LaneSh4d0w** [comment]
Well... Not sure about that one, but give this a try. Will be changed if the channel cuts : https://video-weaver.cdg02.hls.ttvnw.net/v1/playlist/Cv4E3yVmCwXfVZxGthWAkhlIomL1w2awm4Mph1Mv7nmgTU49niplHVWb2CPqZOI1gk9SCQ-VqrXRuofpoiX_sgaj8avzwZWe_ivoE6zQsAQj518kslLlccNHWdxQwn3HiX6nDWCg-Jfa05lYama7s17vhwYKS8oOjFl1rLnQ1TqwULhJ_DdIBcVk3W5qT7t59BQzBxJ6b5e28K0UH7Inf--Y37xM83KsxxSPcBimfgcaEE6jqd__Wnnw4VXbEIH_J-BvrM-49ZYUxEvet4Dt3HFL49kiNzx9rdbwnJOXmRcrcJmw65yoe2EC_-2jnxbjiAIoXc2lz4IKQffqQWOMY3LN2oqx7GBur4IotcfQXnDlfxID2RWPBVRyC3J-XiI2tN_tglRWxVoPi2sNrVJ0y_TKmWMzazEMbCJ8mUfMqk4cqUlBBxb7bYDxLnyIg_ytJZG9R4GJW1tWC1lmVMlnLshhaAZTG0lOK4893FBb5BgEj5_lnMhQd707XVo_fLIqK2a7zV0vwhNXbOfb9jpP_Ifwz1FN43QOwmiin8gLO7C46BNae_mgPpDEYQIU4lmf24_q8fltlyRHUC-JcbvWqJNvX9UUA9bpBzNXkImEkG3-JmPrLNZgQKguI8E4fvRTY4xmM5HyGihYxOwy-cHyCkM_ZxScyydAT1IYVFc3rWNlnC0x_fiq1ax1CcbG_I8d-v2i3U20kp0P91LSpkTAIyI38k3RJwjL5puh5f1Q13iZq-sR08a6XdJ6RQ_AjewDTP4SramlpVHG0NKLvysSWH0nBB1-VMmeXp-W7zdtoShihZUWTCVp0m56s6uwwchVb3TtCBMWuxhKACavXnEPdZ0SEOSVpoG3ogl1nBYbzBKHvykaDL8RnmUDaVIOFJntaA.m3u8

**Comment by LaneSh4d0w** [comment]
This might be your lucky day : https://pd0522db059.dmc.nico/hlsarchive/ht2_nicolive/nicolive-hamster-lv325642541_main_73ba741830494f1de51ee20a698796a990e59e2f111f422246261657bc6ca26d/master.m3u8?ht2_nicolive=anonymous-user-43933221243233.0wwa3em0bg_qt5xil_r3xa3stk81hq&start=0

**Comment by Dum4G** [comment]
Shady source but here it goes
http://119.77.96.184:1935/chn21/chn21/chunklist_w252131137.m3u8
![image](https://user-images.githubusercontent.com/5430116/119180070-77949480-ba78-11eb-8346-5548327d0d90.png)

**Comment by LaneSh4d0w** [comment]
I don't think that's the same KCTV haha

**Comment by Dum4G** [comment]
> I don't think that's the same KCTV haha

Yes, original request was Elufa TV

**Comment by LaneSh4d0w** [comment]
This issue might be resolved with #2833 's findings.

**Comment by LaneSh4d0w** [comment]
To test : 

https://query-streamlink.lanesh4d0w.repl.co/iptv-query?streaming-ip=https://www.twitch.tv/elufatv
https://iptv--iptv.repl.co/streamlink?url=https://www.twitch.tv/elufatv

**Comment by themak1985** [comment]
@LaneSh4d0w both links are good. Added #3024
