### ISSUE TITLE
Remove: All channels with http://182.216.142.247:9999

### ISSUE THREAD

**Issue by LaneSh4d0w** [iptv-org/iptv#2461]
Reason : they simply do not work anymore.

(this is not a DMCA request, can someone move that out)

**Comment by freearhey** [comment]
Links removed.

The DMCA notice does not apply to broken links.

**Comment by LaneSh4d0w** [comment]
Yes, that's what I wanted the mention DMCa removed from my request x)

**Comment by freearhey** [comment]
Now I see.
