### ISSUE TITLE
Spain List

### ISSUE THREAD

**Issue by Sphinxroot** [iptv-org/iptv#2470]
## Spain ##

#EXTINF:-1,#0 HD
http://185.228.155.93:8000/play/a02q/index.m3u8
#EXTINF:-1,#VAMOSHD
http://185.228.155.93:8000/play/a036/index.m3u8
#EXTINF:-1,AMC HD
http://185.228.155.93:8000/play/a021/index.m3u8
#EXTINF:-1,ANTENA 3 HD
http://185.228.155.93:8000/play/a022/index.m3u8
#EXTINF:-1,AXN HD
http://185.228.155.93:8000/play/a01k/index.m3u8
#EXTINF:-1,AXN WHITE HD
http://185.228.155.93:8000/play/a02y/index.m3u8
#EXTINF:-1,BLAZE
http://185.228.155.93:8000/play/a03b/index.m3u8
#EXTINF:-1,CALLE 13 HD
http://185.228.155.93:8000/play/a02f/index.m3u8
#EXTINF:-1,CANAL DECASA
http://185.228.155.93:8000/play/a034/index.m3u8
#EXTINF:-1,CANAL ODISEA
http://185.228.155.93:8000/play/a030/index.m3u8
#EXTINF:-1,CAZA Y PESCA
http://185.228.155.93:8000/play/a03a/index.m3u8
#EXTINF:-1,CAZAyPESCA HD
http://185.228.155.93:8000/play/a02r/index.m3u8
#EXTINF:-1,COMEDYCENTRALHD
http://185.228.155.93:8000/play/a02c/index.m3u8
#EXTINF:-1,COSMO HD
http://185.228.155.93:8000/play/a02b/index.m3u8
#EXTINF:-1,CRIMEN+INVES
http://185.228.155.93:8000/play/a03f/index.m3u8
#EXTINF:-1,CUATRO HD
http://185.228.155.93:8000/play/a023/index.m3u8
#EXTINF:-1,DAZN 1 HD
http://185.228.155.93:8000/play/a03q/index.m3u8
#EXTINF:-1,DAZN 2 HD
http://185.228.155.93:8000/play/a03r/index.m3u8
#EXTINF:-1,DISCOVERY
http://185.228.155.93:8000/play/a03d/index.m3u8
#EXTINF:-1,DISNEY CH HD
http://185.228.155.93:8000/play/a02p/index.m3u8
#EXTINF:-1,EUROSPORT1HD
http://185.228.155.93:8000/play/a02g/index.m3u8
#EXTINF:-1,FOX HD
http://185.228.155.93:8000/play/a01t/index.m3u8
#EXTINF:-1,FOX LIFE HD
http://185.228.155.93:8000/play/a028/index.m3u8
#EXTINF:-1,HISTORIA
http://185.228.155.93:8000/play/a03e/index.m3u8
#EXTINF:-1,HOLLYWOODHD
http://185.228.155.93:8000/play/a01w/index.m3u8
#EXTINF:-1,LA 1 HD
http://185.228.155.93:8000/play/a01p/index.m3u8
#EXTINF:-1,LA SEXTA HD
http://185.228.155.93:8000/play/a025/index.m3u8
#EXTINF:-1,LALIGATV BAR
http://185.228.155.93:8000/play/a033/index.m3u8
#EXTINF:-1,LALIGATV BAR
http://185.228.155.93:8000/play/a01m/index.m3u8
#EXTINF:-1,M. ACCI©N HD
http://185.228.155.93:8000/play/a01u/index.m3u8
#EXTINF:-1,M. Cine Espaæol
http://185.228.155.93:8000/play/a03g/index.m3u8
#EXTINF:-1,M. DEPORTES
http://185.228.155.93:8000/play/a032/index.m3u8
#EXTINF:-1,M. DEPORTES1HD
http://185.228.155.93:8000/play/a020/index.m3u8
#EXTINF:-1,M. DEPORTESHD
http://185.228.155.93:8000/play/a02h/index.m3u8
#EXTINF:-1,M. DRAMA HD
http://185.228.155.93:8000/play/a01v/index.m3u8
#EXTINF:-1,M. GOLF HD
http://185.228.155.93:8000/play/a02a/index.m3u8
#EXTINF:-1,M. LaLiga
http://185.228.155.93:8000/play/a035/index.m3u8
#EXTINF:-1,M. LaLiga 1 HD
http://185.228.155.93:8000/play/a01s/index.m3u8
#EXTINF:-1,M. LaLiga 2 HD
http://185.228.155.93:8000/play/a03h/index.m3u8
#EXTINF:-1,M. LaLiga 3 HD
http://185.228.155.93:8000/play/a03i/index.m3u8
#EXTINF:-1,M. LaLiga HD
http://185.228.155.93:8000/play/a01x/index.m3u8
#EXTINF:-1,M. SERIES HD
http://185.228.155.93:8000/play/a02l/index.m3u8
#EXTINF:-1,M.COMEDIA HD
http://185.228.155.93:8000/play/a01l/index.m3u8
#EXTINF:-1,M.ESTRENOSHD
http://185.228.155.93:8000/play/a038/index.m3u8
#EXTINF:-1,M.FORMULA1HD
http://185.228.155.93:8000/play/a01z/index.m3u8
#EXTINF:-1,M.LCAMPEON1
http://185.228.155.93:8000/play/a03j/index.m3u8
#EXTINF:-1,M.LCAMPEON2
http://185.228.155.93:8000/play/a03k/index.m3u8
#EXTINF:-1,M.LCAMPEONES
http://185.228.155.93:8000/play/a027/index.m3u8
#EXTINF:-1,M.Seriesmania HD
http://185.228.155.93:8000/play/a029/index.m3u8
#EXTINF:-1,NAT GEO HD
http://185.228.155.93:8000/play/a02i/index.m3u8
#EXTINF:-1,NG WILD HD
http://185.228.155.93:8000/play/a02o/index.m3u8
#EXTINF:-1,NICKELODEON
http://185.228.155.93:8000/play/a03c/index.m3u8
#EXTINF:-1,NICKELODEONHD
http://185.228.155.93:8000/play/a02e/index.m3u8
#EXTINF:-1,PLAYBOY TV
http://185.228.155.93:8000/play/a031/index.m3u8
#EXTINF:-1,SYFY HD
http://185.228.155.93:8000/play/a02t/index.m3u8
#EXTINF:-1,TCM HD
http://185.228.155.93:8000/play/a02m/index.m3u8
#EXTINF:-1,TELECINCO HD
http://185.228.155.93:8000/play/a024/index.m3u8
#EXTINF:-1,TNT HD
http://185.228.155.93:8000/play/a02n/index.m3u8
#EXTINF:-1,TOROS HD
http://185.228.155.93:8000/play/a02j/index.m3u8
#EXTINF:-1,VIAJAR HD
http://185.228.155.93:8000/play/a02v/index.m3u8

**Comment by freearhey** [comment]
Feel free to add links to the playlist yourself, just read the [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#add-or-replace-a-stream) before doing so. There is no need to post links to the issue.

**Comment by elmagodelanoche-tech** [comment]
> ## Spain
> #EXTINF:-1,#0 HD http://185.228.155.93:8000/play/a02q/index.m3u8 #EXTINF:-1,#VAMOSHD http://185.228.155.93:8000/play/a036/index.m3u8 #EXTINF:-1,AMC HD http://185.228.155.93:8000/play/a021/index.m3u8 #EXTINF:-1,ANTENA 3 HD http://185.228.155.93:8000/play/a022/index.m3u8 #EXTINF:-1,AXN HD http://185.228.155.93:8000/play/a01k/index.m3u8 #EXTINF:-1,AXN WHITE HD http://185.228.155.93:8000/play/a02y/index.m3u8 #EXTINF:-1,BLAZE http://185.228.155.93:8000/play/a03b/index.m3u8 #EXTINF:-1,CALLE 13 HD http://185.228.155.93:8000/play/a02f/index.m3u8 #EXTINF:-1,CANAL DECASA http://185.228.155.93:8000/play/a034/index.m3u8 #EXTINF:-1,CANAL ODISEA http://185.228.155.93:8000/play/a030/index.m3u8 #EXTINF:-1,CAZA Y PESCA http://185.228.155.93:8000/play/a03a/index.m3u8 #EXTINF:-1,CAZAyPESCA HD http://185.228.155.93:8000/play/a02r/index.m3u8 #EXTINF:-1,COMEDYCENTRALHD http://185.228.155.93:8000/play/a02c/index.m3u8 #EXTINF:-1,COSMO HD http://185.228.155.93:8000/play/a02b/index.m3u8 #EXTINF:-1,CRIMEN+INVES http://185.228.155.93:8000/play/a03f/index.m3u8 #EXTINF:-1,CUATRO HD http://185.228.155.93:8000/play/a023/index.m3u8 #EXTINF:-1,DAZN 1 HD http://185.228.155.93:8000/play/a03q/index.m3u8 #EXTINF:-1,DAZN 2 HD http://185.228.155.93:8000/play/a03r/index.m3u8 #EXTINF:-1,DISCOVERY http://185.228.155.93:8000/play/a03d/index.m3u8 #EXTINF:-1,DISNEY CH HD http://185.228.155.93:8000/play/a02p/index.m3u8 #EXTINF:-1,EUROSPORT1HD http://185.228.155.93:8000/play/a02g/index.m3u8 #EXTINF:-1,FOX HD http://185.228.155.93:8000/play/a01t/index.m3u8 #EXTINF:-1,FOX LIFE HD http://185.228.155.93:8000/play/a028/index.m3u8 #EXTINF:-1,HISTORIA http://185.228.155.93:8000/play/a03e/index.m3u8 #EXTINF:-1,HOLLYWOODHD http://185.228.155.93:8000/play/a01w/index.m3u8 #EXTINF:-1,LA 1 HD http://185.228.155.93:8000/play/a01p/index.m3u8 #EXTINF:-1,LA SEXTA HD http://185.228.155.93:8000/play/a025/index.m3u8 #EXTINF:-1,LALIGATV BAR http://185.228.155.93:8000/play/a033/index.m3u8 #EXTINF:-1,LALIGATV BAR http://185.228.155.93:8000/play/a01m/index.m3u8 #EXTINF:-1,M. ACCI©N HD http://185.228.155.93:8000/play/a01u/index.m3u8 #EXTINF:-1,M. Cine Espaæol http://185.228.155.93:8000/play/a03g/index.m3u8 #EXTINF:-1,M. DEPORTES http://185.228.155.93:8000/play/a032/index.m3u8 #EXTINF:-1,M. DEPORTES1HD http://185.228.155.93:8000/play/a020/index.m3u8 #EXTINF:-1,M. DEPORTESHD http://185.228.155.93:8000/play/a02h/index.m3u8 #EXTINF:-1,M. DRAMA HD http://185.228.155.93:8000/play/a01v/index.m3u8 #EXTINF:-1,M. GOLF HD http://185.228.155.93:8000/play/a02a/index.m3u8 #EXTINF:-1,M. LaLiga http://185.228.155.93:8000/play/a035/index.m3u8 #EXTINF:-1,M. LaLiga 1 HD http://185.228.155.93:8000/play/a01s/index.m3u8 #EXTINF:-1,M. LaLiga 2 HD http://185.228.155.93:8000/play/a03h/index.m3u8 #EXTINF:-1,M. LaLiga 3 HD http://185.228.155.93:8000/play/a03i/index.m3u8 #EXTINF:-1,M. LaLiga HD http://185.228.155.93:8000/play/a01x/index.m3u8 #EXTINF:-1,M. SERIES HD http://185.228.155.93:8000/play/a02l/index.m3u8 #EXTINF:-1,M.COMEDIA HD http://185.228.155.93:8000/play/a01l/index.m3u8 #EXTINF:-1,M.ESTRENOSHD http://185.228.155.93:8000/play/a038/index.m3u8 #EXTINF:-1,M.FORMULA1HD http://185.228.155.93:8000/play/a01z/index.m3u8 #EXTINF:-1,M.LCAMPEON1 http://185.228.155.93:8000/play/a03j/index.m3u8 #EXTINF:-1,M.LCAMPEON2 http://185.228.155.93:8000/play/a03k/index.m3u8 #EXTINF:-1,M.LCAMPEONES http://185.228.155.93:8000/play/a027/index.m3u8 #EXTINF:-1,M.Seriesmania HD http://185.228.155.93:8000/play/a029/index.m3u8 #EXTINF:-1,NAT GEO HD http://185.228.155.93:8000/play/a02i/index.m3u8 #EXTINF:-1,NG WILD HD http://185.228.155.93:8000/play/a02o/index.m3u8 #EXTINF:-1,NICKELODEON http://185.228.155.93:8000/play/a03c/index.m3u8 #EXTINF:-1,NICKELODEONHD http://185.228.155.93:8000/play/a02e/index.m3u8 #EXTINF:-1,PLAYBOY TV http://185.228.155.93:8000/play/a031/index.m3u8 #EXTINF:-1,SYFY HD http://185.228.155.93:8000/play/a02t/index.m3u8 #EXTINF:-1,TCM HD http://185.228.155.93:8000/play/a02m/index.m3u8 #EXTINF:-1,TELECINCO HD http://185.228.155.93:8000/play/a024/index.m3u8 #EXTINF:-1,TNT HD http://185.228.155.93:8000/play/a02n/index.m3u8 #EXTINF:-1,TOROS HD http://185.228.155.93:8000/play/a02j/index.m3u8 #EXTINF:-1,VIAJAR HD http://185.228.155.93:8000/play/a02v/index.m3u8
