### ISSUE TITLE
Todo los Canales Rumanos

### ISSUE THREAD

**Issue by popaionut24** [iptv-org/iptv#2472]
# EXTM3U
#EXTINF: -1, ANTENA TA
https://live7digi.antenaplay.ro/a1/a1_3000k.m3u8
#EXTINF: -1, DOCUBOX
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41590
#EXTINF: -1, DuckTv
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41591
#EXTINF: -1, TrinitasTv
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41592
#EXTINF: -1, vedete FilmBOX
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41595
#EXTINF: -1, familia FilmBOX
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41596
#EXTINF: -1, FilmBOX premium
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41597
#EXTINF: -1, NickJr
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41598
#EXTINF: -1, DigiSport 4
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41602
#EXTINF: -1, DigiWorld
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41605
#EXTINF: -1, DigiLife
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41606
#EXTINF: -1, DigiAnimalWorld
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41607
#EXTINF: -1, Utv
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41611
#EXTINF: -1, HappyHd
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41615
#EXTINF: -1, ZUtv
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41616
#EXTINF: -1, TNT
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41619
#EXTINF: -1, BBCearth
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41620
#EXTINF: -1, HBO2
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41625
#EXTINF: -1, HIT
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41626
#EXTINF: -1, ETNO
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41627
#EXTINF: -1, DigiSport 4
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41628
#EXTINF: -1, DigiSport 1
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41629
#EXTINF: -1, VH1
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41630
#EXTINF: -1, c ©
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41631
#EXTINF: -1, HoraTv
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41632
#EXTINF: -1, AgroTv
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41633
#EXTINF: -1, KanalD
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41634
#EXTINF: -1, Taraf
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41635
#EXTINF: -1, NG Wild
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41636
#EXTINF: -1, LookSport
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41637
#EXTINF: -1, ViasatNature
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41638
#EXTINF: -1, Calatorii
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41639
#EXTINF: -1, Digisport3
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41640
#EXTINF: -1, National Geografic
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41642
#EXTINF: -1, DigiSport2
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41643
#EXTINF: -1, Digi24
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41645
#EXTINF: -1, Diva
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41647
#EXTINF: -1, HBO
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41650
#EXTINF: -1, HBO3
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41651
#EXTINF: -1, FilmNow
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41652
#EXTINF: -1, rotire AXN
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41653
#EXTINF: -1, E
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41654
#EXTINF: -1, HBO2
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41667
#EXTINF: -1, Antena 1HD
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41671
#EXTINF: -1, TVRi
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41672
#EXTINF: -1, FilmNow
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41673
#EXTINF: -1, TVR1 HD
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41674
#EXTINF: -1, DigiSport1
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41675
#EXTINF: -1, DigiSport2
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41676
#EXTINF: -1, ProTv
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41677
#EXTINF: -1, FilmBOX extra HD
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41679
#EXTINF: -1, Prima Tv
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41680
#EXTINF: -1, B1
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41681
#EXTINF: -1, Eurosport 2
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41682
#EXTINF: -1, Look Sport +
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41684
#EXTINF: -1, National Geografic HD
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41685
#EXTINF: -1, PRO X
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41686
#EXTINF: -1, PRO2
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41688
#EXTINF: -1, HBO3
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41689
#EXTINF: -1, HBO
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41690
#EXTINF: -1, Cinemax
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41691
#EXTINF: -1, KanalD HD
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41692
#EXTINF: -1, NationalTv
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41693
#EXTINF: -1, Cinemax2
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41695
#EXTINF: -1, Cinemax
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41696
#EXTINF: -1, E Viasat
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41697
#EXTINF: -1, Istoria Viasat
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41698
#EXTINF: -1, Favorit
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41700
#EXTINF: -1, hit-uri MTV
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41701
#EXTINF: -1, MTV 80
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41702
#EXTINF: -1, MTV 90
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41703
#EXTINF: -1, club MTV
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41704
#EXTINF: -1, BOOMERANG
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41706
#EXTINF: -1, ZU TV
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41707
#EXTINF: -1, Nickelodeon
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41708
#EXTINF: -1, TeenNick
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41709
#EXTINF: -1, FishHunt
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41710
#EXTINF: -1, PRO X
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41712
#EXTINF: -1, TLC
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41713
#EXTINF: -1, C @
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41714
#EXTINF: -1, Disney JR
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41715
#EXTINF: -1, Cartoon Network
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41716
#EXTINF: -1, Disney Channel
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41717
#EXTINF: -1, EXO
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41718
#EXTINF: -1, Music Channel1
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41719
#EXTINF: -1, Kiss TV
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41720
#EXTINF: -1, Minimax
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41722
#EXTINF: -1, ROMANIA TV
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41723
#EXTINF: -1, REALITATEA plus
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41724
#EXTINF: -1, Eurosport2
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41725
#EXTINF: -1, Eurosport1
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41726
#EXTINF: -1, MARIA TV
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41727
#EXTINF: -1, Discovery Science
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41729
#EXTINF: -1, Paprika TV
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41730
#EXTINF: -1, Travel Mix
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41731
#EXTINF: -1, PRO 2
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41734
#EXTINF: -1, FILM Cafe
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41735
#EXTINF: -1, negru AXN
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41736
#EXTINF: -1, Cinema PRO
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41737
#EXTINF: -1, Antena1
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41738
#EXTINF: -1, Antena3
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41739
#EXTINF: -1, ???
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41740
#EXTINF: -1, AMC
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41741
#EXTINF: -1, Antena Stars
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41742
#EXTINF: -1, FilmBOX
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41743
#EXTINF: -1, PLUS N24
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41745
#EXTINF: -1, CUTIE DE LUPTA
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41589
#EXTINF: -1, CTV
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41586
#EXTINF: -1, Motor auto
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41584
#EXTINF: -1, CBS Reality
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41582
#EXTINF: -1, BOLLYWOOD
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41581
#EXTINF: -1, PRO TV International
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41580
#EXTINF: -1, TVR1
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41573
#EXTINF: -1, TVR2
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41572
#EXTINF: -1, TVR3
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41571
#EXTINF: -1, TV 1000
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41569
#EXTINF: -1, AXN
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41568
#EXTINF: -1, PRO Gold
http://live.yimp.cc:7779/pWVYIr2sBv/TpmnD4lemh/41567
#EXTINF: -1, HBO
http://mag.mtbox.hitv.one/GXJRFt6857/sxoDyY567/14604
#EXTINF: -1, + HBO GO LIVE ROMANIA
http://185.2.82.97:14010/sop.ts
#EXTINF: -1, HBO GO 2 LIVE --- // ---
http://185.2.82.97:14020/sop.ts
#EXTINF: -1, HBO GO 3 LIVE --- // ---
http://185.2.82.97:14030/sop.ts
#EXTINF: -1, CINEMAX
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14629
#EXTINF: -1, CINEMAX2
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/16558
#EXTINF: -1, MAGIC TV
https://fms-https1.mediadirect.ro/live3/_definst_/magictv.smil/playlist.m3u8?publisher=83
#EXTINF: -1, Canal 33
https://fms-https1.mediadirect.ro/live3/_definst_/canal33.smil/playlist.m3u8?publisher=83
#EXTINF: -1, Kiss TV
https://fms-https1.mediadirect.ro/live3/_definst_/kiss.smil/chunklist_w1251469938_b300000.m3u8?publisher=83
#EXTINF: -1, Pro TV HD
https://cmero-ott-live.ssl.cdn.cra.cz/channels/cme-ro-protv/playlist/rum/live_fullhd.m3u8
#EXTINF: -1, Pro X HD
https://cmero-ott-live.ssl.cdn.cra.cz/channels/cme-ro-prox/playlist/rum/live_fullhd.m3u8
#EXTINF: -1, Pro Cinema HD
https://cmero-ott-live.ssl.cdn.cra.cz/channels/cme-ro-procinema/playlist/rum/live_fullhd.m3u8
#EXTINF: -1, Pro 2 HD
https://cmero-ott-live.ssl.cdn.cra.cz/channels/cme-ro-pro2/playlist/rum/live_fullhd.m3u8
#EXTINF: -1, Pro Gold
https://cmero-ott-live.ssl.cdn.cra.cz/channels/cme-ro-progold/playlist/rum/live_fullhd.m3u8
#EXTINF: -1, Pro TV INTERNATIONAL
https://cmero-ott-live.ssl.cdn.cra.cz/channels/cme-ro-protv-international/playlist/rum/live_fullhd.m3u8
#EXTINF: -1, TV IASI LIFE
https://tv.streambox.ro/hls/itv/index.m3u8
#EXTINF: -1, TV NEAMT
rtmp: //82.208.140.3: 12800 / live / 1
#EXTINF: -1, VOYO NEWS
https://cmero-ott-live.ssl.cdn.cra.cz/channels/cme-ro-voyo-news/playlist/rum/live_fullhd.m3u8
#EXTINF: -1, RO | AMC
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14647
#EXTINF: -1, RO | Antena 1
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14636
#EXTINF: -1, RO | Antena 3
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14637
#EXTINF: -1, RO | B1
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14632
#EXTINF: -1, RO | Cartoon Network
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14631
#EXTINF: -1, RO | Cinemax 1
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14629
#EXTINF: -1, RO | Cinemax 2
http://nomorecable.xyz:80/Direct/919123/15692
#EXTINF: -1, RO | Da Vinci Learning
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14628
#EXTINF: -1, RO | DIGI 24
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14627
#EXTINF: -1, RO | Via?a DIGI
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14624
#EXTINF: -1, RO | DIGI Sport 1
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14623
#EXTINF: -1, RO | DIGI Sport 2
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14622
#EXTINF: -1, RO | DIGI Sport 3
http://nomorecable.xyz:80/Direct/919123/15702
#EXTINF: -1, RO | DIGI Sport 4
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14620
#EXTINF: -1, RO | LUMEA DIGI
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14619
#EXTINF: -1, RO | canal Disney
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14614
#EXTINF: -1, RO | Disney Jr.
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14613
#EXTINF: -1, RO | Etno
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14611
#EXTINF: -1, RO | Eurosport 1
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14609
#EXTINF: -1, RO | Eurosport 2
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14610
#EXTINF: -1, RO | Favorit TV
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14608
#EXTINF: -1, RO | Film Cafe
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14607
#EXTINF: -1, RO | HBO
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14604
#EXTINF: -1, RO | Istorie
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14603
#EXTINF: -1, RO | Kanal D
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14601
#EXTINF: -1, RO | Kiss TV
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14600
#EXTINF: -1, RO | Uite Plus
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14599
#EXTINF: -1, RO | Minimax
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14644
#EXTINF: -1, RO | Music Channel
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14597
#EXTINF: -1, RO | Nat Geo Wild
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14593
#EXTINF: -1, RO | National Geographic
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14596
#EXTINF: -1, RO | Televiziunea na?ionala
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14595
#EXTINF: -1, RO | Canal Paramount
http://nomorecable.xyz:80/Direct/919123/15750
#EXTINF: -1, RO | Prima TV
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14642
#EXTINF: -1, RO | PRO 2
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14635
#EXTINF: -1, RO | PRO X
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14640
#EXTINF: -1, RO | Cinema PRO
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14590
#EXTINF: -1, RO | PRO GOLD
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14648
#EXTINF: -1, RO | PRO TV
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14591
#EXTINF: -1, RO | Pro TV International
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14589
#EXTINF: -1, RO | Realitatea TV
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14641
#EXTINF: -1, RO | ROmania TV
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14587
#EXTINF: -1, RO | Sport
http://nomorecable.xyz:80/Direct/919123/15756
#EXTINF: -1, RO | Taraf
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14584
#EXTINF: -1, RO | Telekom 1
http://nomorecable.xyz:80/Direct/919123/15676
#EXTINF: -1, RO | Telekom 2
http://nomorecable.xyz:80/Direct/919123/15673
#EXTINF: -1, RO | Telekom 3
http://nomorecable.xyz:80/Direct/919123/15674
#EXTINF: -1, RO | Telekom 4
http://nomorecable.xyz:80/Direct/919123/15675
#EXTINF: -1, RO | TLC
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14616
#EXTINF: -1, RO | TNT
http://nomorecable.xyz:80/Direct/919123/15758
#EXTINF: -1, RO | TV1000
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14582
#EXTINF: -1, RO | TVR
http://nomorecable.xyz:80/Direct/919123/15763
#EXTINF: -1, RO | TVR1
http://nomorecable.xyz:80/Direct/919123/15764
#EXTINF: -1, RO | TVR2
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14580
#EXTINF: -1, RO | TVR3
http://nomorecable.xyz:80/Direct/919123/15766
#EXTINF: -1, RO | UTV
http://mag.mtbox.hitv.one:80/GXJRFt6857/sxoDyY567/14579
#EXTINF: -1, RO | VH1
http://nomorecable.xyz:80/Direct/919123/15768
#EXTINF: -1, RO | VH1 Classic
http://nomorecable.xyz:80/Direct/919123/15769
#EXTINF: -1, RO | ZU TV
http://nomorecable.xyz:80/Direct/919123/15773
#EXTINF: -1 tvg-logo = "https://i.imgur.com/z10bwPn.jpg" group-title = "ROMANIA", 7TV
https://play.streamkit.tv/content/channel/aseventv/live/aseventv.player.m3u8
#EXTINF: -1 tvg-logo = "https://i.imgur.com/MQ5PkKB.png" group-title = "ROMANIA", Aleph News
https://stream-aleph.m.ro/Aleph/ngrp:Alephnewsmain.stream_all/playlist.m3u8
#EXTINF: -1 tvg-id = "" tvg-name = "Antena Comedy" tvg-logo = "https://i.imgur.com/tH624pc.png" group-title = "ROMANIA", Antena Comedy
http://stream1.antenaplay.ro/live/smil:ComedyPlay.smil/playlist.m3u8
#EXTINF: -1 tvg-id = "" tvg-name = "Antena Cook and PLay" tvg-logo = "https://i.imgur.com/GZABUfW.png" group-title = "ROMANIA", Antena Cook si joaca
http://stream1.antenaplay.ro/live/smil:CookPlay.smil/chunklist_w904193915_b1000000.m3u8
#EXTINF: -1 tvg-id = "" tvg-name = "Antena Monden" tvg-logo = "https://i.imgur.com/6R5TLlc.png" group-title = "ROMANIA", Antena Monden
http://stream1.antenaplay.ro/live/smil:AntenaMonden.smil/playlist.m3u8
#EXTINF: -1 tvg-logo = "https://i.imgur.com/VQqgkzw.jpg" group-title = "ROMANIA", B1
http://stream.adunity.com/b1/b1.m3u8
#EXTINF: -1 tvg-id = "" tvg-name = "Bucovina TV" tvg-logo = "https://i.imgur.com/7QHdiTO.png" group-title = "ROMANIA", Bucovina TV
http://46.4.14.12:9999/btvsvlive/btvsvlive/playlist.m3u8
#EXTINF: -1 tvg-logo = "https://i.imgur.com/9tNRAX0.png" group-title = "ROMANIA", Canal 33
https://fms-https1.mediadirect.ro/live3/_definst_/canal33.smil/chunklist_w1456597134_b680000.m3u8
#EXTINF: -1 tvg-logo = "https://i.imgur.com/HUNixjy.png" group-title = "ROMANIA", CBN Family Romania
https://bcliveunivsecure-lh.akamaihd.net/i/iptv1_1@500579/master.m3u8
#EXTINF: -1 tvg-id = "" tvg-name = "Cornea TV" tvg-logo = "https://i.imgur.com/cn89fLa.jpg" group-title = "ROMANIA", Cornea TV
http://89.149.30.158:1935/CorneaTV/myStream/playlist.m3u8
#EXTINF: -1 tvg-id = "" tvg-name = "Cromtel TV - github.com/Free-IPTV" tvg-logo = "https://i.imgur.com/kNNRmS1.png" group-title = „ROMÂNIA”, Cromtel TV - github.com/Free-IPTV
http://webmobile.xdev.ro:81/tv7/playlist.m3u8?time=1463062060161
#EXTINF: -1 tvg-id = "" tvg-name = "EST TV" tvg-logo = "https://i.imgur.com/tP5cGl1.jpg" group-title = "ROMANIA", EST TV
http://89.38.8.130:39435
#EXTINF: -1 tvg-id = "" tvg-name = "H! T Music Channel Romania" tvg-logo = "https://i.imgur.com/VDl1q98.png" group-title = "ROMANIA", H! T Music Channel România
https://edge126.rcs-rds.ro/utvedge/musicchannelhq.stream/index.m3u8
#EXTINF: -1 tvg-id = "" tvg-name = "HD 365" tvg-logo = "https://i.imgur.com/DYdaxZ6.png" group-title = "ROMANIA", HD 365
https://netstreaming.eu:8080/hls/hd365.m3u8
#EXTINF: -1 tvg-id = "" tvg-name = "" tvg-logo = "https://i.imgur.com/PTsws8f.png" group-title = "ROMANIA", Iasi TV Life
http://webmobile.xdev.ro:81/tv24/playlist.m3u8?time=1464028219168
#EXTINF: -1 tvg-id = "" tvg-name = "Infinit TV" tvg-logo = "https://i.imgur.com/3OOmdCU.jpg" group-title = "ROMANIA", Infinit TV
http://webmobile.xdev.ro:81/tv6/playlist.m3u8
#EXTINF: -1 tvg-id = "" tvg-name = "Info HD" tvg-logo = "https://i.imgur.com/RiZA8Yu.png" group-title = "ROMANIA", Info HD
https://netstreaming.eu:8080/hls/InfoHd.m3u8
#EXTINF: -1 tvg-id = "" tvg-name = "Intermedia TV" tvg-logo = "https://i.imgur.com/jo5fei5.png" group-title = "ROMANIA", Intermedia TV
http://46.4.14.12:9999/intermedia1/playlist.m3u8
#EXTINF: -1 tvg-logo = "https://i.imgur.com/MwADEV2.png" group-title = "ROMANIA", Kapital TV
http://84.247.79.238:1935/kapital/kapital/kapital.stream/playlist.m3u8
#EXTINF: -1 tvg-id = "" tvg-name = "Lira TV" tvg-logo = "https://i.imgur.com/sC9ELuY.jpg" group-title = "ROMANIA", Lira TV
https://5d79ae45bc63b.streamlock.net/Liratv/Liratv/chunklist_w98704019.m3u8
#EXTINF: -1 tvg-logo = "https://i.imgur.com/g46c2Ht.png" group-title = "ROMANIA", Music Channel
https://edge126.rcs-rds.ro/utvedge/musicchannelhq.stream/playlist.m3u8
#EXTINF: -1 tvg-id = "" tvg-name = "Nasul TV" tvg-logo = "https://i.imgur.com/LJTcfxk.png" group-title = "ROMANIA", Nasul TV
https://5ab29cc78f681.streamlock.net/NasulTV/livestream/playlist.m3u8
#EXTINF: -1 tvg-logo = "https://i.imgur.com/aL6Mf8b.png" group-title = "ROMANIA", NEst TV
http://webmobile.xdev.ro:81/tv13/playlist.m3u8
#EXTINF: -1 tvg-id = "" tvg-name = "Nova TV Brasov" tvg-logo = "https://i.imgur.com/DYO1tVZ.png" group-title = "ROMANIA", Nova TV Brasov
http://novapress.ro:1935/live/nova/playlist.m3u8
#EXTINF: -1 tvg-id = "" tvg-name = "Prima TV" tvg-logo = "https://i.imgur.com/G03w5XQ.png" group-title = "ROMANIA", Prima TV
https://netstreaming.eu:8080/hls/unutv.m3u8
#EXTINF: -1 tvg-logo = "https://i.imgur.com/kWrneym.png" group-title = "ROMANIA", Profit
https://stream1.profit.ro:1945/profit/livestream/playlist.m3u8
#EXTINF: -1 tvg-logo = "https://i.imgur.com/Ae1Klb2.png" group-title = "ROMANIA", Realitatea TV
http://livestream.realitatea.net/livestream/liverealitatea.stream/playlist.m3u8
#EXTINF: -1 tvg-logo = "https://i.imgur.com/3LdXQxm.png" group-title = "ROMANIA", Somax TV
http://webmobile.xdev.ro:81/tv12/playlist.m3u8
#EXTINF: -1 tvg-logo = "https://i.imgur.com/o1WmDXf.png" group-title = "ROMANIA", Stele
http://stream1.antenaplay.ro/live/smil:ComedyPlay.smil/playlist.m3u8
#EXTINF: -1 tvg-logo = "https://i.imgur.com/o1WmDXf.png" group-title = "ROMANIA", Stars Direct
http://stream1.antenaplay.ro/live/smil:AntenaMonden.smil/playlist.m3u8
#EXTINF: -1 tvg-id = "" tvg-name = "TravelMix" tvg-logo = "https://i.imgur.com/MHTJwMo.jpg" group-title = "ROMANIA", TravelMix
http://89.38.8.131:39520
#EXTINF: -1 tvg-id = "" tvg-name = "TV SE" tvg-logo = "https://i.imgur.com/BoMnP5g.png" group-title = "ROMANIA", TV SE
http://89.38.8.130:39419
#EXTINF: -1 tvg-id = "" tvg-name = "TVPlus Suceava" tvg-logo = "https://i.imgur.com/6T7w975.png" group-title = "ROMANIA", TVPlus Suceava
http://85.186.146.34:8080
#EXTINF: -1 tvg-logo = "https://i.imgur.com/zFYfPjp.png" group-title = "ROMANIA", TVR Craiova
https://mn-nl.mncdn.com/tvrcraiova_new/smil:tvrcraiova_new.smil/chunklist_b4096000.m3u8
#EXTINF: -1 tvg-logo = "https://i.imgur.com/CJkyXtf.png" group-title = "ROMANIA", TVR International
https://mn-nl.mncdn.com/tvri_test/smil:tvri_test.smil/index.m3u8
#EXTINF: -1 tvg-id = "" tvg-name = "TVSat" tvg-logo = "https://i.imgur.com/CkKvogv.jpg" group-title = "ROMANIA", TVSat
http://89.38.8.130:39443
#EXTINF: -1 tvg-id = "" tvg-name = "" tvg-logo = "https://i.imgur.com/KGLHMyB.png" group-title = "ROMANIA", UTV
http://edge76.rcs-rds.ro/utvedge/utvlivehls/playlist.m3u8
#EXTINF: -1 tvg-id = "" tvg-name = "VP TV" tvg-logo = "https://i.imgur.com/xeXcscj.gif" group-title = "ROMANIA", VP TV
http://89.38.8.130:3943

**Comment by freearhey** [comment]
Feel free to add links to the playlist yourself, just read the [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#add-or-replace-a-stream) before doing so. There is no need to post links to the issue.
