### ISSUE TITLE
GTV

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#2476]
**Channel Name:** GTV
**Channel ID:** GTV.ph
**Country:** Philippines
**Language:** Tagalog
**External Link (optional):** xxx
**Notes (optional):** Free to air channel in the Philippines.

**Comment by freearhey** [comment]
Closed in favor #1967

**Comment by hazsmine** [comment]
Hi can i have the code for this specifiv channel? thank you

**Comment by freearhey** [comment]
Closed in favor of #12305
