### ISSUE TITLE
Jeepney TV

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#2481]
**Channel Name:** Jeepney TV
**Channel ID:** JeepneyTV.ph
**Country:** Philippines
**Language:** Tagalog
**External Link (optional):** xxx
**Notes (optional):** Classic shows channel in the Philippines.

**Comment by freearhey** [comment]
Closed in favor #1967

**Comment by freearhey** [comment]
Closed in favor of #12300
