### ISSUE TITLE
Metro Channel

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#2482]
**Channel Name:** Metro Channel
**Channel ID:** MetroChannel.ph
**Country:** Philippines
**Language:** Tagalog/English
**External Link (optional):** xxx
**Notes (optional):** Lifestyle channel in the Philippines.

**Comment by freearhey** [comment]
Closed in favor #1967

**Comment by freearhey** [comment]
Closed in favor of #12299
