### ISSUE TITLE
Sari Sari Channel

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#2483]
**Channel Name:** Sari-sari Channel
**Channel ID:** SariSariChannel.ph
**Country:** Philippines
**Language:** Tagalog
**External Link (optional):** xxx
**Notes (optional):** Classic shows channel in the Philippines.

**Comment by freearhey** [comment]
Closed in favor #1967

**Comment by freearhey** [comment]
Closed in favor of #12298
