### ISSUE TITLE
Solar Learning

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#2485]
**Channel Name:** Solar Learning
**Channel ID:** SolarLearning.ph
**Country:** Philippines
**Language:** Tagalog/English
**External Link (optional):** xxx
**Notes (optional):** Free to air learning channel in the Philippines.

**Comment by freearhey** [comment]
Closed in favor #1967

**Comment by freearhey** [comment]
Closed in favor of #12296
