### ISSUE TITLE
NBA TV Philippines

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#2490]
**Channel Name:** NBA TV Philippines
**Channel ID:** NBATVPhilippines.ph
**Country:** Philippines
**Language:** English
**External Link (optional):** xxx
**Notes (optional):** Philippine version of NBA TV.

**Comment by freearhey** [comment]
Closed in favor #1942

**Comment by freearhey** [comment]
Closed in favor of #12294
