### ISSUE TITLE
Add: TVM

### ISSUE THREAD

**Issue by ste9999** [iptv-org/iptv#2491]
**Channel Name:** TVM
**Country:** Malta
**Language:** Maltese/English
**External Link (optional):** https://www.tvm.com.mt/mt/tvmi/live/tvm/
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
https://live.23video.com/live/amlst:f2iiv5ap230aedvub2r6pshf8t:16966825-2ca040dbfeea9e5cb868.mp4/playlist.m3u8?referer=https%3A%2F%2Fwww.tvm.com.mt%2F&uuid=4a55150a-5e01-002c-b9e8-d4f29bcdba22

**Comment by freearhey** [comment]
Closed in favor #2506
