### ISSUE TITLE
Net TV

### ISSUE THREAD

**Issue by ste9999** [iptv-org/iptv#2494]
**Channel Name:** Net TV
**Country:** Malta
**Language:** Maltese/English 
**Website:** https://netondemand.mt/
**Notes (optional):** xxx

**Comment by trancer1994** [comment]
The link I found was https://netondemand.mt:8443/live/net/playlist.m3u8?DVR&tokenstarttime=1619440553&tokenendtime=1619483753&tokenhash=CDEsQJ5ZzaLPb8QAHEPwam6xqFwLX27CVxbIIoHiwnU= but it's tokened and hashed though.

**Comment by ste9999** [comment]
Hmm it’s not working?

**Comment by freearhey** [comment]
Closed in favor #2506

**Comment by LaneSh4d0w** [comment]
https://iptv-all.lanesh4d0w.codes/malta/net

Still needs a bit of work.

**Comment by LaneSh4d0w** [comment]
Server's having slight issues, will be back soon I hope.

**Comment by freearhey** [comment]
Closed in favor #7856
