### ISSUE TITLE
Fix: Adult Swim (1080p)

### ISSUE THREAD

**Issue by quvinh75** [iptv-org/iptv#2500]
Adult Swim (1080p) in the Entertainment category. It works but show nothing (black screen)

![adult swim (1080p) (27-04-2021 11-25-35 293)](https://user-images.githubusercontent.com/70810816/116185196-54ade380-a74b-11eb-8e38-37b8fb8ff912.jpg)

**Comment by LaneSh4d0w** [comment]
Actually it works, but it's an aquarium only... I do not know why WarnerMedia has got this stream.
