### ISSUE TITLE
Category for Bob ross channel is Painting

### ISSUE THREAD

**Issue by maheshbisl** [iptv-org/iptv#2502]
Hi,

In us.m3u, please set the group-title of 2 "Bob Ross" channels to "Painting" . The channel is about painting.

Regards,

**Comment by LaneSh4d0w** [comment]
> 
> 
> Hi,
> 
> In us.m3u, please set the group-title of 2 "Bob Ross" channels to "Painting" . The channel is about painting.
> 
> Regards,

Painting is an Hobby, so better classify it as an Hobby.

**Comment by maheshbisl** [comment]
Sure. Hobby is Okay.

Best regards,
Mahesh Bisl

**Comment by freearhey** [comment]
Done.
