### ISSUE TITLE
Add: localnow

### ISSUE THREAD

**Issue by heroku-miraheze** [iptv-org/iptv#2503]
**Channel Name:** localnow
**Country:** undefined
**Language:** undefined

https://www.apsattv.com/localnow.m3u is the m3u to add to iptv repository.

**Comment by freearhey** [comment]
Most of the links from this file are already in the playlist, they are just not sorted yet and are kept in `channels/unsorted.m3u` for now.

**Comment by heroku-miraheze** [comment]
These links is not available in unsorted.m3u. Please add it now, please.

**Comment by freearhey** [comment]
If any channels are missing from the playlist, feel free to add them yourself, just read the [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#add-or-replace-a-stream) carefully before doing so.

**Comment by heroku-miraheze** [comment]
#2511
