### ISSUE TITLE
Fix: GOL

### ISSUE THREAD

**Issue by exigente82** [iptv-org/iptv#2513]
**_Channel Name: GOL
**_Broken Link (from playlist): 

#EXTINF:-1 tvg-id="GOL.es" tvg-name="GOL" tvg-country="ES" tvg-language="" tvg-logo="" tvg-url="https://www.tdtchannels.com/epg/TV.xml" group-title="",GOL
https://api.goltelevision.com/api/v1/stream/live/stream.m3u8

**Comment by LaneSh4d0w** [comment]
It went geolocked.

**Comment by freearhey** [comment]
Added [Geo-blocked] label to link.
