### ISSUE TITLE
Fix: ATRESPLAYER

### ISSUE THREAD

**Issue by exigente82** [iptv-org/iptv#2514]
**_Channel Name: ATRESPLAYER
**_Broken Link (from playlist): #EXTINF:-1 tvg-id="Atresplayer1.es" tvg-name="Atresplayer 1" tvg-country="ES" tvg-language="" tvg-logo="" tvg-url="https://www.tdtchannels.com/epg/TV.xml" group-title="",Atresplayer 1
https://livestartover.atresmedia.com/eventos15/master.m3u8

**_Notes (optional): ATRESPLAYER is not a television channel. It is the web player of the ATRESMEDIA group for its different channels. I guess that's why the image looks black.

**Comment by freearhey** [comment]
Thank you for pointing that out. The link has already been removed from the playlist.
