### ISSUE TITLE
Fix: EuroLatina TV

### ISSUE THREAD

**Issue by exigente82** [iptv-org/iptv#2518]
I suppose that the official logo of this channel is not that of the Lidl supermarket chain:

#EXTINF:-1 tvg-id="EuroLatinaTV.es" tvg-name="EuroLatina TV" tvg-country="ES" tvg-language="Spanish" tvg-logo="https://graph.facebook.com/eurolatinatelevision/picture?width=320&height=320" group-title="Music",EuroLatina TV
https://limited1.todostreaming.es/live/eurolatina-livestream.m3u8

**Comment by LaneSh4d0w** [comment]
Indeed, the official picture is this one : https://www.eurolatinatv.com/wp-content/uploads/cropped-logo-eurolatina-220x220.png

**Comment by freearhey** [comment]
The logo has been replaced.
