### ISSUE TITLE
Fix: Github Actions

### ISSUE THREAD

**Issue by heroku-miraheze** [iptv-org/iptv#2521]
Error log 1:
Run git config user.name github-actions
[master bf46916] [Bot] Format playlists
 3 files changed, 3 insertions(+), 412 deletions(-)
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Required status check "lint" is expected.        
To https://github.com/iptv-org/iptv
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/iptv-org/iptv'
Error: Process completed with exit code 1.
Link 1:
https://github.com/iptv-org/iptv/actions/runs/797845746
Error log 2:
Run git config user.name github-actions
[master ea30244] [Bot] Format playlists
 1 file changed, 1 insertion(+), 408 deletions(-)
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Required status check "lint" is expected.        
To https://github.com/iptv-org/iptv
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/iptv-org/iptv'
Error: Process completed with exit code 1.
Link 2:
https://github.com/iptv-org/iptv/actions/runs/794408083

**Comment by LaneSh4d0w** [comment]
I suppose @freearhey forgot to add his lint script onto the bot's pushes.

**Comment by heroku-miraheze** [comment]
Use buddy.works instead and deploy it automatically to Netlify.

**Comment by freearhey** [comment]
Thanks for the report. Already fixed it.
