### ISSUE TITLE
Add: Canal 5 (XHGC-TV)

### ISSUE THREAD

**Issue by LaneSh4d0w** [iptv-org/iptv#2547]
**Channel Name:** XHGC-TV (Canal 5)
**Country:** Mexico
**Language:** Spanish
**External Link (optional):** https://cdn.vdosupreme.com/vdo.js?id=6gzf9nfdh3gafs8bfzm1 + https://4vs0ev185hsp00i8.ezcdn285.net:8443/hls/4kxnl.m3u8?s= *insert token the script above creates* &e=*insert timestamp of the token*
**Notes (optional):** Tokened stream.
Links I've gathered while looking at the way it works (use ad-block 'cause goddamn there's lots of ads) : https://wigistream.to/live/4kxnl (thing is it's "domain protected", to watch the stream you need to go there ->https://telegratis.org/canal-5/)

**Comment by LaneSh4d0w** [comment]
Additional info : the wigistream link miiiiight work if you use "Referer : https://telegratis.org/" as an HTTP header. Not tested but this is a theory I've found.

**Comment by MapGuy11** [comment]
I can add this through other means give me some time to get the link.

**Comment by MapGuy11** [comment]
Is Canal 5 from Tijuana ok? (XETV-TDT) 1080p 6.1.

**Comment by LaneSh4d0w** [comment]
> Is Canal 5 from Tijuana ok? (XETV-TDT) 1080p 6.1.

I do not know if this one is on the playlist, if it's not feel free to add it.

**Comment by MapGuy11** [comment]
Will do. It's the same I assume Canal 5 feed you are asking for.

**Comment by MapGuy11** [comment]
Here is the stream: https://streams.the6tv.duckdns.org:2443/locals/SanDiego/xetv-tdt.m3u8

**Comment by LaneSh4d0w** [comment]
> Here is the stream: https://streams.the6tv.duckdns.org:2443/locals/SanDiego/xetv-tdt.m3u8

Works for me.

**Comment by MapGuy11** [comment]
Pull request should have been accepted I am now going to close this.

**Comment by davidhs57** [comment]
Someone could solve this, they could give me the url in m3u format to be able to see this channel.  (Channel 5 of Mexico) would be very grateful

**Comment by Javiercuate0321** [comment]
> > Here is the stream: https://streams.the6tv.duckdns.org:2443/locals/SanDiego/xetv-tdt.m3u8
> are you sure because it dosen't work for me either
