### ISSUE TITLE
xteve config

### ISSUE THREAD

**Issue by samcro1967** [iptv-org/iptv#2565]
I have setup https://iptv-org.github.io/iptv/countries/us.m3u and https://iptv-org.github.io/epg/guides/tvtv.us.guide.xml in xteve.  The channels all show up in mapping, but have a red bar to their left.  In Jellyfin, the channels are not in the guide, but I can search for and find them, but they have no play button.

I do have Pluto.TV successfully setup in xteve and can watch them in Jellyfin.  The xpeg channel count in xteve is 341 which matches the number of channels from Pluto.tv.

Any ideas?

![image](https://user-images.githubusercontent.com/2319445/116824783-95de3300-ab51-11eb-9d50-00dac94b36ff.png)

**Comment by LaneSh4d0w** [comment]
Well to be honest the EPG is a kind of a work in progress, so the issue might be from there. Not using Jellyfin nor Xteve, maybe it's an no EPG ID issue or simply no channel name that matches the one above.
