### ISSUE TITLE
TV Canção Nova Rede

### ISSUE THREAD

**Issue by rrodrigofranco** [iptv-org/iptv#2577]
**Channel Name:** Canção Nova
**Channel ID:** TVCancaoNovaRede.br
**Country:** Brazil
**Language:** Portuguese
**External Link (optional):** xxx
**Notes (optional):** The Canção Nova and Rede Vida channel is broke, can you add a new link?

**Comment by trancer1994** [comment]
Cancao Nova
https://www.youtube.com/embed/raxjLTROFZ4?feature=oembed&rel=0&autoplay=1
Rede Vida
https://cvd1.cds.ebtcvd.net/live-redevida/smil:redevida.smil/playlist.m3u8

**Comment by rrodrigofranco** [comment]
Hello dude, I wanna a file .m3u8 that working on app SSIPTV and the Canção Nova for example is not working

**Comment by freearhey** [comment]
Closed in favor #1968

**Comment by Alstruit** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCVrKQMmA2ew9LFzeIDaOFgw/live
