### ISSUE TITLE
Azam Sports HD

### ISSUE THREAD

**Issue by ahmedzooo** [iptv-org/iptv#2728]
**Channel Name:**  azam sports 1
**Channel ID:** AzamSports1.tz
**Country:** Tanzania
**Language:** sawhili
**External Link (optional):** xxx
**Notes (optional):** 
Links on this site no work

**Comment by freearhey** [comment]
Closed in favor #2730

**Comment by ahmedzooo** [comment]
Not working this links

**Comment by freearhey** [comment]
Closed in favor of #12293
