### ISSUE TITLE
Add: 8TV

### ISSUE THREAD

**Issue by samleong123** [iptv-org/iptv#2729]
**Channel Name:**  8TV
**Country:** Malaysia , MY
**Language:** Chinese
**External Link (optional):** https://www.tonton.com.my/live/8tv
**Notes (optional):** This channel is already valid on here , but the server is located in Germany and our ISP in Malaysia providing a bad connection to Germany server(s). 
https://www.tonton.com.my/live/8tv
This is the link provided by 8TV official , after open it with IDM i get this m3u8 file :
https://stream-03.sg1.dailymotion.com/sec(g0FwEewAeL3w7b14lFp08jwawLYpzzZxEqQIMu8vkPg)/dm/3/x7a7ru1/s/live-2.m3u8
Since its server located in Singapore we have great latency and network quality to connect over Singapore Servers instead of Germany servers , please consider my feedback. Thanks so much

**Comment by samleong123** [comment]
Hi , i have a new method but this m3u8 stream is DRM/PlayReady encrypted , supported clients like TiviMate will worked for this , this is based on Telekom Malaysia unifi PlayTV server , refer to this repo : https://github.com/weareblahs/unifi-tv
Tested and its work for me , not sure one DRM key can used on multiple devices or multiple IP  , and not sure is there any geo-restriction (usually no since it designed for watching it anywhere including worldwide) 
For signing up , it seems to be able to use Facebook to sign up instead of using Malaysia local phone number so its should be able to sign up from anywhere

**Comment by Dum4G** [comment]
Please note that these links can be only accessed through a Widevine Server (for authorizing). Instructions below.
Note that the Widevine Server URL changes every 3-7 days, so you have to follow the steps below regularly if you want to continue using this playlist.

> https://github.com/weareblahs/unifi-tv

**Comment by samleong123** [comment]
> Please note that these links can be only accessed through a Widevine Server (for authorizing). Instructions below.
> Note that the Widevine Server URL changes every 3-7 days, so you have to follow the steps below regularly if you want to continue using this playlist.
> 
> > https://github.com/weareblahs/unifi-tv

Hmm so far tested for few days , never change the Widevine URL but its still working , will monitor for about 10 day and see is there any problem of Widevine URL

**Comment by samleong123** [comment]
> > Please note that these links can be only accessed through a Widevine Server (for authorizing). Instructions below.
> > Note that the Widevine Server URL changes every 3-7 days, so you have to follow the steps below regularly if you want to continue using this playlist.
> > > https://github.com/weareblahs/unifi-tv
> 
> Hmm so far tested for few days , never change the Widevine URL but its still working , will monitor for about 10 day and see is there any problem of Widevine URL

Monitored for more than 7 days , so far i never change the Widevine URL and its still working

**Comment by freearhey** [comment]
Already on the playlist:
https://github.com/iptv-org/iptv/blob/c67e79bd10606df02f51096e96f34367107fbaad/channels/my.m3u#L2-L3
