### ISSUE TITLE
Grab livingstream  channel url on website request

### ISSUE THREAD

**Issue by caten0** [iptv-org/iptv#2731]
Is there anyone can grabe livingstream  channel url on website?

vietnam
https://hplus.com.vn/xem-kenh-htv1-2631.html
http://tvzz.101vn.com/livetv-xem-tivi-kenh-bibitv-menu-vtv-vtc.html
http://vi.xemtivivip.com
https://vtv.vn/truyen-hinh-truc-tuyen/vtv1.htm
http://truyenhinhthanhhoa.vn/truyen-hinh/
https://phuthotv.vn/thoi-su/phat-huy-quyen-lam-chu-cua-nhan-dan-trong-cong-tac-bau-cu
http://thaibinhtv.vn/video

thai,lao,cambodia
https://www.malimar.tv/grids/LiveTV_Premium_CF?dashboard=HomeGrid

sg
https://www.starhubtvplus.com/guide?channelId=GLOBAL_228&programId=GLOBAL_TC0013615073

indonesia
https://www.vidio.com/live

**Comment by Dum4G** [comment]
Open those pages in Chrome
Press F12 and go to the Network tab
Play livestream
You'll see sonething like this
![image](https://user-images.githubusercontent.com/5430116/117466766-bea06700-af5b-11eb-88ce-16ff4b60f8db.png)
Find a link that has m3u, m3u8 or mpd in it. If there's a lot of random numbers and letters after the file link as shown on the picture that means your source is protected and any link to it won't last long. If you'll ever get some pure file link that works in VLC it can be submitted here

**Comment by trancer1994** [comment]
I could do the rest but the names of the channels don't seem to be in the pages when you open them, and they haven't been specified here, so I wouldn't know what channel I was providing the link for.

**Comment by LaneSh4d0w** [comment]
> 
> 
> https://hplus.com.vn/xem-kenh-htv1-2631.html = signKey Token Stream
> 
> http://tvzz.101vn.com/livetv-xem-tivi-kenh-bibitv-menu-vtv-vtc.html
> https://vtsstr1.tv24.vn/live/_definst_/smil:VTVcab8_SD.smil/chunklist.m3u8
> Streamtest = Offline
> 
> http://vi.xemtivivip.com/kenh-ha-noi-2-truc-tu = URL Incomplete
> 
> https://vtv.vn/truyen-hinh-truc-tuyen/vtv1.htm (1 to 9)
> 
> https://vtvgo-live-vtv.akamaized.net/vtv1/index.m3u8
> 
> https://vtvgo-live-vtv.akamaized.net/vtv2/index.m3u8
> 
> https://vtvgo-live-vtv.akamaized.net/vtv3/index.m3u8
> 
> https://vtvgo-live-vtv.akamaized.net/vtv4/index.m3u8
> 
> https://vtvgo-live-vtv.akamaized.net/vtv5/index.m3u8
> 
> https://vtvgo-live-vtv.akamaized.net/vtv5tnb/index.m3u8
> 
> https://vtvgo-live-vtv.akamaized.net/vtv5tn/index.m3u8
> 
> https://vtvgo-live-vtv.akamaized.net/vtv6/index.m3u8
> 
> https://vtvgo-live-vtv.akamaized.net/vtv7/index.m3u8
> 
> https://vtvgo-live-vtv.akamaized.net/vtv8/index.m3u8
> 
> https://vtvgo-live-vtv.akamaized.net/vtv9/index.m3u8
> 
> http://truyenhinhthanhhoa.vn/truyen-hinh/ = Token Stream
> https://truyenhinh.vnptvas.vn/live.m3u8?c=vstv208&q=high&type=tv&token=1111&time=1586395820&gcId=1532&userId=&deviceId=&deviceType=&location=NA&requestTime=1586309420781&pkg=pkg11
> 
> https://phuthotv.vn/thoi-su/phat-huy-quyen-lam-chu-cua-nhan-dan-trong-cong-tac-bau-cu = VOD
> https://phuthotv.vn/tv-video = Live Token Stream
> https://cdn.3ssoft.vn/live/phuthotv/phuthotv/index.m3u8?t=qRRpWU6kQqqmdIdxH34YAg&e=1620442604
> 
> http://thaibinhtv.vn/video = 1 Live Stream .. other are VOD
> http://cdn.tbtv.mediatech.vn/tbtvlive/tv1live.m3u8
> 
> http://cdn.tbtv.mediatech.vn/tbtvlive/tv1live_manifest.m3u8?vhost=__defaultVhost__
> 
> https://www.malimar.tv/
> 
> https://www.malimar.tv/grids/LiveTV_Free_Premium_Sponsors_CF?dashboard=HomeGrid
> OH MUANG LAO LIVE
> https://livefta.malimarcdn.com/ftaedge00/ohmuanglao.stream/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/ohmuanglao.stream/chunklist.m3u8
> TEA TV
> https://livefta.malimarcdn.com/ftaedge00/teatv.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/teatv.sdp/chunklist.m3u8
> GOOD IDEA TV USA
> https://livefta.malimarcdn.com/ftaedge00/gooditv.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/gooditv.sdp/chunklist.m3u8
> LAO MUSLIM TV
> https://livefta.malimarcdn.com/ftaedge00/ddtvlao.stream/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/ddtvlao.stream/chunklist.m3u8
> 
> https://www.malimar.tv/grids/LiveTV_Local_Channels_CF?dashboard=HomeGrid
> BRIAN TV
> https://livefta.malimarcdn.com/ftaedge00/briantv.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/briantv.sdp/chunklist.m3u8
> NING TV
> https://livefta.malimarcdn.com/ftaedge00/ningtv.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/ningtv.sdp/chunklist.m3u8
> AIR TV
> https://livefta.malimarcdn.com/ftaedge00/airtv.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/airtv.sdp/chunklist.m3u8
> DAO LANE XANG
> https://livefta.malimarcdn.com/ftaedge00/khaomwungmai.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/khaomwungmai.sdp/chunklist.m3u8
> LAO THAI TV
> https://livefta.malimarcdn.com/ftaedge00/laothaius.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/laothaius.sdp/chunklist.m3u8
> OY LAO TV
> https://livefta.malimarcdn.com/ftaedge00/oylaotv.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/oylaotv.sdp/chunklist.m3u8
> VATI LAO
> https://livefta.malimarcdn.com/ftaedge00/vatilaotv.stream/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/vatilaotv.stream/chunklist.m3u8
> HOUNG FA
> https://livefta.malimarcdn.com/ftaedge00/houngfa.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/houngfa.sdp/chunklist.m3u8
> DHAMMASAPHA TV
> https://livefta.malimarcdn.com/ftaedge00/dhammasapha.stream/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/dhammasapha.stream/chunklist.m3u8
> KHOMSANH TV
> https://livefta.malimarcdn.com/ftaedge00/lstv2.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/lstv2.sdp/chunklist.m3u8
> LAO HERITAGE ORGANIZATION
> https://livefta.malimarcdn.com/ftaedge00/laoheritagetv.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/laoheritagetv.sdp/chunklist.m3u8
> SUPREME MASTER TV
> https://lbs-us1.suprememastertv.com/720p.m3u8
> https://lbs-us1.suprememastertv.com/origin/720p/chunklist.m3u8
> PNTV
> https://livefta.malimarcdn.com/ftaedge00/pntv.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/pntv.sdp/chunklist.m3u8
> LONE SINH LAO TV
> https://livefta.malimarcdn.com/ftaedge00/lonesinhlao.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/lonesinhlao.sdp/chunklist.m3u8
> LAOS PLANET TV
> https://livefta.malimarcdn.com/ftaedge00/laosplanet.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/laosplanet.sdp/chunklist.m3u8
> LAO NET TV
> https://livefta.malimarcdn.com/ftaedge00/laonet.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/laonet.sdp/chunklist.m3u8
> LS TV 1
> https://livefta.malimarcdn.com/ftaedge00/laostv.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/laostv.sdp/chunklist.m3u8
> LOOK THOONG TV HD
> https://livefta.malimarcdn.com/ftaedge00/lookthoongtv.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/lookthoongtv.sdp/chunklist.m3u8
> UNIQUELY THAI
> https://livefta.malimarcdn.com/ftaedge00/uniquely.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/uniquely.sdp/chunklist.m3u8
> VANPHENH TV
> https://livefta.malimarcdn.com/ftaedge00/vanphenhtv.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/vanphenhtv.sdp/chunklist.m3u8
> SIENG KHAEN LAO TV
> https://livefta.malimarcdn.com/ftaedge00/vlctemple.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/vlctemple.sdp/chunklist.m3u8
> LAO CHAMPA TV 1
> https://livefta.malimarcdn.com/ftaedge00/laochampa1.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/laochampa1.sdp/chunklist.m3u8
> LAO CHAMPA TV 2
> https://livefta.malimarcdn.com/ftaedge00/laochampa2.stream/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/laochampa2.stream/chunklist.m3u8
> LAO CHAMPA TV 3
> https://livefta.malimarcdn.com/ftaedge00/laochampa3.stream/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/laochampa3.stream/chunklist.m3u8
> TEA TV
> https://livefta.malimarcdn.com/ftaedge00/teatv.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/teatv.sdp/chunklist.m3u8
> ISTV
> https://livefta.malimarcdn.com/ftaedge00/ichannel.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/ichannel.sdp/chunklist.m3u8
> NAT TV
> https://livefta.malimarcdn.com/ftaedge00/nat.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/nat.sdp/chunklist.m3u8
> LAO SV TV
> https://livefta.malimarcdn.com/ftaedge00/laosvtv.stream/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/laosvtv.stream/chunklist.m3u8
> VAJTSWV TXOJLUS
> https://livefta.malimarcdn.com/ftaedge00/vajtswv.stream/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/vajtswv.stream/chunklist.m3u8
> HMONG USA TV
> https://livefta.malimarcdn.com/ftaedge00/hmongusatv.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/hmongusatv.sdp/chunklist.m3u8
> CVA HMONG FRESNO
> https://livefta.malimarcdn.com/ftaedge00/cvabroadcasting.stream/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/cvabroadcasting.stream/chunklist.m3u8
> HMONG STAR TV
> https://livefta.malimarcdn.com/ftaedge00/hmongstartv.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/hmongstartv.sdp/chunklist.m3u8
> KHMER TV
> https://livefta.malimarcdn.com/ftaedge00/khmertv2020.stream/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/khmertv2020.stream/chunklist.m3u8
> TEA TV KHMER
> https://livefta.malimarcdn.com/ftaedge00/teatv2.sdp/playlist.m3u8
> https://livefta.malimarcdn.com/ftaedge00/teatv2.sdp/chunklist.m3u8
> 
> https://www.malimar.tv/grids/LiveTV_Premium_CF?dashboard=HomeGrid = Paid Sub
> 
> https://www.starhubtvplus.com/guide?channelId=GLOBAL_228&programId=GLOBAL_TC0013615073 = Login to watch
> 
> https://www.vidio.com/live = .mpd Token Stream

Vidio's live tokens are done here : https://www.vidio.com/live/204/tokens?type=dash

Just add them to make the stream.

**Comment by LaneSh4d0w** [comment]
I'll add those to my already existing script to permit you to watch them.

**Comment by LaneSh4d0w** [comment]
@Sphinxroot @caten0 : Please try https://iptv-all.lanesh4d0w.repl.co/indonesia/sctv

**Comment by caten0** [comment]
@LaneSh4d0w, Vlc player unable to open this link.

**Comment by caten0** [comment]
please continue
http://us.tvnet.gov.vn/kenh-truyen-hinh/1018/vtc16

**Comment by LaneSh4d0w** [comment]
> 
> 
> please continue
> http://us.tvnet.gov.vn/kenh-truyen-hinh/1018/vtc16

Tokened, adding it to my script.

**Comment by LaneSh4d0w** [comment]
Akamai fixed their redirection, but I've found out the SCTV link was Widevine encrypted in some sort.

**Comment by caten0** [comment]
http://118.107.85.13:1935/tvnet/smil:vtc16.smil/playlist.m3u8?vtcdigicomstarttime=1620545058&vtcdigicomendtime=1620631458&vtcdigicomhash=UNtWREeu_MsU1A2RgjLkC-HUa0OHmZHcbU5lt2n2uR8=

**Comment by Sphinxroot** [comment]
> http://118.107.85.13:1935/tvnet/smil:vtc16.smil/playlist.m3u8?vtcdigicomstarttime=1620545058&vtcdigicomendtime=1620631458&vtcdigicomhash=UNtWREeu_MsU1A2RgjLkC-HUa0OHmZHcbU5lt2n2uR8=

token stream that already changed 

best for you if you want .. its to use kodi whit VN addon http://repo.kodi.vn/

or using cast to kodi from firefox from any device  that support firefox  .. might work for chromecast  i cant tell i dont use chromecast

**Comment by caten0** [comment]
https://c44.com.au/watch/

https://dacastmmd.mmdlive.lldns.net/dacastmmd/008ee5897af64d96b1d303d11b683b6d/manifest.m3u8?p=79&s=1621092565&e=1621093165&h=3b2f18e464b65c5257119a401bef37d6

**Comment by LaneSh4d0w** [comment]
Launch this : https://playback.dacast.com/content/access?contentId=66b44df5-af42-8914-b5c9-801ec8062888-live-88fb56bf-c5c6-ff88-f4f7-6404234d4e9c&provider=universe&referrerToken=U2FsdGVkX1%20ihmS2k43o8qxS%20zNGhLG2JVn5vk2SSM1oQlgVVnUPYyWIvgV%20Isd6m%20eUf3cotgeQ4%20TocGP64bFmMd9nI5UBG2lPtHBFIZ2EHnKD0oCPc/HTPNLgI9sFulQ5Z9K8Mi2jSERo/4kjo/tXLj8FTb84tHYMIuwhwNLezb3d3ojcHaJ2eEK8IrF99fwFkVZouZPcNagUTFKkX6wUkkXL264T044AgGZFABWZtwbGdQ7V8JOUdtrsBONBoUZpXoOooFp8bYLm%20WSfDThc3TpLxlGzWaaneoVUAAY5QliMNx5XCWhWjpcARmpKJ/Sc2GZXOUW/jcpZOHVsLcv3q0ikfey1CrffzVErZmGGvWsFLt35%20lbiwmNvPPwkvBwklYPPZyxJ7Tvgr5J2sgRDN1bn0/eJT6rdACsCJtf5svZNc4isfW57RG%20WCSYnTIphx5s7aApb2fNOu0%208b9Kh894MM9tjrp4sMT/lx3Ju/6GP/FAQH3ANb8NkTKdaUC6b30M6T647jNdKlCHNuQTXRJkjaD9AJnguSLaKdCPAax%20V50BA14OTpfj8DdJFvaQ6bBEzCwSt18P5S56oWIluyqsZ3SyF5xZxSPLk0QzSvrroBbw%20zstJmEgolFLe6DW/zstrPRNRmkLjDmNyZyr%20TpRiO/cQdkAH8GBtpzdnae1AGXTfIS1RL9yxk0YFyCiExkjrrLbfoYU/jAzkccAFHGmLbtB2Ij8MyY0JGTRnnn/CppO3IfUH5pNH5z1z8Xgy9t/prpvu6w7WH5WbMTWTXnfq1CtLnEFAV9u02Uo=

and it will give you the correct link.

**Comment by LaneSh4d0w** [comment]
https://iptv-all.lanesh4d0w.repl.co/australia/ch44
