### ISSUE TITLE
Contribution: lyngsat link compilation and more

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#2738]
I managed to gather all tvchannel related links from Lyngsat and also make human readable variant that looks like so

> ae/Abu Dhabi Drama
ae/Abu Dhabi Sports 1
ae/Abu Dhabi Sports 2
ae/Abu Dhabi Sports 3
ae/Abu Dhabi Sports 4
ae/Abu Dhabi TV Europe
ae/Abu Dhabi TV
ae/Ajman TV
ae/Al Aan TV
...

You can now automate sorting by country and many more
have fun!

[LYNG1.zip](https://github.com/iptv-org/iptv/files/6445464/LYNG1.zip)

**Comment by Dum4G** [comment]
This is also a source with some great potential for automation
https://en.wikipedia.org/wiki/Category:Lists_of_television_channels_by_language

**Comment by heroku-miraheze** [comment]
@freearhey

**Comment by freearhey** [comment]
I personally don't know how this might help, but if you have your own solution you can suggest it through a pull request.

**Comment by LaneSh4d0w** [comment]
Could be useful if combined with a script that verifies the name of the channel being submitted and check on the Lyngsat text file to see if channel corresponds. A bot could then answer to the OP, saying where from which country he found it.
