### ISSUE TITLE
Add: Al-Resalah (1080p)

### ISSUE THREAD

**Issue by iptvchecker** [iptv-org/iptv#2749]
**Channel Name:** Al-Resalah (1080p)
**Country:** KSA
**Language:** Arabic
**External Link (optional):** xxx
**Notes (optional):** Please put this content back in the ara.m3u. This channel was put on the list few days back. It works without proxy. With a new update you removed it. I have saved the working ara.m3u file, which when tested works fine. I am including the removed content so you might want to put it back.

Thanks.
================
#EXTINF:-1 tvg-id="AlResalah.sa" tvg-name="Al-Resalah" tvg-country="SA" tvg-language="Arabic" tvg-logo="https://rotana.net/assets/themes/TriTheme-new/images/channels/resala.png" group-title="Religious",Al-Resalah (1080p)
https://shls-rotana-alresalah-prod-dub.shahid.net/out/v1/936b89606b5e48db8ca28caa40adc886/index.m3u8

**Comment by freearhey** [comment]
@iptvchecker I'm sorry, but what exactly is wrong with the other link to this channel?
https://github.com/iptv-org/iptv/blob/97a28b4366e9a2fa5fe0b9acb55463efca7bd39f/languages/ara.m3u#L173-L174

**Comment by iptvchecker** [comment]
The other channels links ONLY work if you're using a tor proxy, or in a region that it's not geo-blocked! This link worked, when you guys added it few days back, without having to go over tor proxy. I appreciate it if you can put it back. Thanks.

**Comment by freearhey** [comment]
Playlist updated. The link should reappear.

**Comment by iptvchecker** [comment]
I am re-opening the ticket, but not for al-resalah! But because it's the same issue and related to the Rotana set of channels!

It seems that someone has tried to clean the repeat channels names, not noticing that these channels have different URL Links. Now all the NOT geo-blocked channels are removed.

Please restore the channels from your most recent commit that had Multiple Rotana (Cinema, Comedy, Drama, etc!)

Please note the current ones as geo-blocked. The opened ones came from link based "shahid.net"

Thanks for your support.

**Comment by freearhey** [comment]
@iptvchecker Playlist updated, links should reappear tomorrow.

**Comment by htmldana** [comment]
> @iptvchecker I'm sorry, but what exactly is wrong with the other link to this channel?
> 
> https://github.com/iptv-org/iptv/blob/97a28b4366e9a2fa5fe0b9acb55463efca7bd39f/languages/ara.m3u#L173-L174

The link doesnt work on VLC, are there any softwares I can use on windows that work with it?
