### ISSUE TITLE
Fix: Region mixing script has been reverted for country playlists

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#2750]
It's easier to check on Lebanese playlist (lb) 

Only 26 channels are truly Lebanese, everything else is mixed because ARAB region is set.
An automated counter says we have 78 channels there but an automaticaly generated playlist only has the same 26 channels.

TL;DR Region mixing does work for counters only but doesn't actually mix channels into playlists

Occured on May 8 with a commit 
https://github.com/iptv-org/iptv/commit/84a3c45f89af2fd9f2b9677ec50652d3b56c6cec#diff-89c203c724c9843d9747b73b100994283e78948aa75b6c6ce8ff706b95789f35

**Comment by freearhey** [comment]
Fixed.
