### ISSUE TITLE
Fix: Stream quality check doesn't respect HLS streams

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#2751]
Can be seen in Family category among the others. Some channels are running at better quality than reported by bot

**Comment by freearhey** [comment]
Could you tell us exactly which channels we are talking about?

**Comment by Dum4G** [comment]
#EXTINF:-1 tvg-id="AMGTV.us" tvg-name="AMG TV" tvg-country="US" tvg-language="English" tvg-logo="http://amgtv.tv/wp-content/uploads/2019/11/new_amgtv_top.png" group-title="Family",AMG TV (480p)
https://2-fss-2.streamhoster.com/pl_138/201660-1270634-1/playlist.m3u8
![image](https://user-images.githubusercontent.com/5430116/117655655-08798f00-b1a0-11eb-8fde-d73b8aef6cea.png)
#EXTINF:-1 tvg-id="TVSFamilyChannel.us" tvg-name="TVS Family Channel" tvg-country="US" tvg-language="English" tvg-logo="https://i.imgur.com/iuQyJ7f.jpg" group-title="Family",TVS Family Channel (360p)
https://nrpus.bozztv.com/36bay2/gusa-TVSFamilyChannel/index.m3u8
![image](https://user-images.githubusercontent.com/5430116/117655753-26df8a80-b1a0-11eb-88dc-916ce9cdfb6c.png)
and more

**Comment by freearhey** [comment]
The thing is that the script doesn't load the link if it already has a resolution. 

Also, sometimes the response from the server can change within one day:

<img src="https://user-images.githubusercontent.com/7253922/117669843-03244080-b1b0-11eb-9fa7-93a12f0de66e.png" width="500" />

If you find any other errors in the playlists feel free to correct them, just read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md) before you do it.
