### ISSUE TITLE
Add: True Premier Football 2

### ISSUE THREAD

**Issue by sogalawson** [iptv-org/iptv#2752]
List of requests for XXX channels from other issues:

-  True Premier Football 2

Link: 
https://www.livedoomovie.com/02_PremierHD2_720p/chunklist.m3u8

**Comment by LaneSh4d0w** [comment]
403 Forbidden.

**Comment by sogalawson** [comment]
https://www.livedoomovie.com/02_PremierHD2_720p/chunklist.m3u8

**Comment by sogalawson** [comment]
When I paste it in my browser, it works. But when I click it here, 403 forbidden

**Comment by LaneSh4d0w** [comment]
In case that goes weird : https://iptv-all.lanesh4d0w.repl.co/thailand/truepremier-football2

**Comment by Sphinxroot** [comment]
https://sport.livedoomovie.com/02_PremierHD2_720p/chunklist.m3u8

**Comment by LaneSh4d0w** [comment]
Same thing

**Comment by Sphinxroot** [comment]
> Same thing

must be geoblocked for you 

https://i.imgur.com/DkcfhBY.png

**Comment by LaneSh4d0w** [comment]
> > Same thing
> 
> must be geoblocked for you 
> 
> https://i.imgur.com/DkcfhBY.png

Not a geoblock issue. It's the fact that it doesn't work if you click on the link, but if you slide it it works.

**Comment by Dum4G** [comment]
@sogalawson where have you found that link?

**Comment by sunta1204** [comment]
please upload channel True Premier Football 2 domain livedoomovie.com is error 403
