### ISSUE TITLE
Question: I need a write access in this repository.

### ISSUE THREAD

**Issue by heroku-miraheze** [iptv-org/iptv#2777]
Hello, i need a write access in this repository, to help pull requests, to commit m3u links, etc.

**Comment by heroku-miraheze** [comment]
@trancer1994

**Comment by heroku-miraheze** [comment]
@trancer1994 Please, give me a write access, please.

**Comment by freearhey** [comment]
If you want to help maintain this repository, you can do so via pull requests. If the changes do not break any rules, they will definitely be approved.
