### ISSUE TITLE
Test dailymotion stream  if it could be added to playlist

### ISSUE THREAD

**Issue by Sphinxroot** [iptv-org/iptv#2781]
Worked in VLC  might work for other apps  , but not working in kodi playlistloader addon

as exemple this is a french channel
#EXTINF:-1 tvg-id="" tvg-logo="https://i.imgur.com/aMZ8d6z.png" group-title="",CorsaireTV
https://www.dailymotion.com/video/x69bhnf#tab_embed.m3u8

https://i.imgur.com/ajoiab7.png

if it work just add  #tab_embed.m3u8  to any live stream From Dailymotion

**Comment by link8k** [comment]
This works because VLC has a extractor https://github.com/videolan/vlc/blob/master/share/lua/playlist/dailymotion.lua

The link is not a m3u8 playlist

This was already discussed for YouTube in https://github.com/iptv-org/iptv/issues/2158

**Comment by heroku-miraheze** [comment]
This link is not a m3u8 playlist.

**Comment by heroku-miraheze** [comment]
@trancer1994, please, close it now.

**Comment by Sphinxroot** [comment]
> This was already discussed for YouTube in #2158

im talking about dailymotion  and u sent youtube topic .. youtube   they are a pain because live stream link change over and over .. but those from dailymotion rarely change .. if you sniff the .m3u8 form it  you get a token that will change .. if some one wanna handle those link everytime it change .. but this trick might work only on vlc   maybe add (VLC) tag to it .. im just askin

**Comment by Dum4G** [comment]
I have tried your link in VLC and it has returned me https://www.dailymotion.com/cdn/live/video/x69bhnf.m3u8

I suppose we can easily convert any link into m3u8 by following the proper syntax

**Comment by Dum4G** [comment]
That's the official position from Dailymotion that dates back to 2019
https://stackoverflow.com/questions/54971469/get-url-from-dailymotion-for-livestream

I feel like tricky ways of fetching tokens won't last long or will require someone to constantly host and maintain a server like @LaneSh4d0w currently does.

**Comment by LaneSh4d0w** [comment]
Well I feel like those kind of tokens are done with scripts, so it would mean loading the scripts, understanding it, getting the secured token and changing it at least once every hour or so... it would mean "spying" the link and force reloading for the end-user.

**Comment by Sphinxroot** [comment]
as far as i know the link to the live stream  doesnt change or extremly rarely , exemple to view the live https://www.dailymotion.com/video/x69bhnf  , but to play it in vlc you add #tab_embed.m3u8 to it  and no token to add , vlc handle it,  so those link will be VLC only  , maybe add (VLC ONLY) tag to stream ,in kodi it work whit the plugin that handle the token other than that ,getting the m3u8 from it you will have the token that change over time .. in dailymotion you will have geoblocked stream as well , but there many good channel to look at
