### ISSUE TITLE
add distro tv channels

### ISSUE THREAD

**Issue by amirh123123** [iptv-org/iptv#2782]
please add distro tv channels in this url
https://www.distro.tv/live

**Comment by LaneSh4d0w** [comment]
I think a few of them are already in this playlist (World of Freesports as an example)

**Comment by freearhey** [comment]
@amirh123123 Next time, please read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel) first.
