### ISSUE TITLE
Mx Player Channels

### ISSUE THREAD

**Issue by APMOBILESTORE** [iptv-org/iptv#2786]
I builde Mxplayer M3U List
https://github.com/APMOBILESTORE/mxplayer_iptv_m3u_list

**Comment by LaneSh4d0w** [comment]
Thanks for the proposition, however you've also added the unsorted channels at the very end of this file. Make sure the file you've sent is in concordance with the topic of this issue.

**Comment by APMOBILESTORE** [comment]
I updated this list. Check now.

**Comment by freearhey** [comment]
We have a separate repository for publishing IPTV related links [iptv-org/awesome-iptv](https://github.com/iptv-org/awesome-iptv#providers)
