### ISSUE TITLE
Add: hta TV

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#2798]
**Country:** Algeria
**Language:** Arabic
**External Link (optional):** https://www.htatv.com/
**Notes (optional):** can't say that I'm really interested but this source offers plenty of Algerian channels in multiple resolutions up to 480p and 720p. Links seem to work even without token. Returns both chunks.m3u8 and playlist m3u8. Everyone with a spare time can fetch them easily. Isn't geoblocked

**Comment by Sphinxroot** [comment]
i know this site  but they have ?wmsAuthSign= token that seem to change over time  sadly  it will need to be updated

**Comment by Dum4G** [comment]
I mean it works in VLC completely without that part in it. I can try any channel for 15 minutes and report back

**Comment by Sphinxroot** [comment]
#1939  ok i tested Beur whitout token in kodi and it worked 

https://cdn02.hta.dz/abr_htatv/Beur_TV/htatv/Beur_TV_720p/chunks.m3u8

https://i.imgur.com/WBcec77.png

**Comment by Dum4G** [comment]
I decided to test it for longer period of time and it just buffered once
![image](https://user-images.githubusercontent.com/5430116/118547113-94238a80-b761-11eb-96ca-4533d0abefe9.png)

**Comment by Sphinxroot** [comment]
I know it off topic @Dum4G  take a look at this #2781 and tell me what you think  and its explicite to VLC apparently  maybe something can be done ...

**Comment by Dum4G** [comment]
That's the official position from Dailymotion that dates back to 2019
https://stackoverflow.com/questions/54971469/get-url-from-dailymotion-for-livestream

I feel like tricky ways of fetching tokens won't last long or will require someone to constantly host and maintain a server like @LaneSh4d0w currently does.

**Comment by Sphinxroot** [comment]
possible link:  _240p/chunks.m3u8  _360p/chunks.m3u8   some _720p/chunks.m3u8  =480p 

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/G60iJen.png" group-title="",AL ANIS TV
https://cdn02.hta.dz/abr_htatv/El_Fhama_TV/htatv/El_Fhama_TV_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/J6VmBuw.png" group-title="",Algérie TV3
https://cdn02.hta.dz/abr_htatv/A3_HD/htatv/A3_HD_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/n8httHt.png" group-title="",Algerie TV4
https://cdn02.hta.dz/abr_htatv/TV_4/htatv/TV_4_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/gXG15AX.png" group-title="",Algerie TV5
https://cdn02.hta.dz/abr_htatv/TV_5/htatv/TV_5_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/HYqJY6y.png" group-title="",ALGERIE TV6
https://cdn02.hta.dz/abr_htatv/TV_6_HD/htatv/TV_6_HD_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/oBRXuH2.png" group-title="",BAHIA TV
https://cdn02.hta.dz/abr_htatv/Bahia_TV/htatv/Bahia_TV_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/KQcT9cz.png" group-title="",Beur TV
https://cdn02.hta.dz/abr_htatv/Beur_TV/htatv/Beur_TV_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/FPmDhNH.png" group-title="",Canal Algérie
https://cdn02.hta.dz/abr_htatv/CANAL_ALGERIE/htatv/CANAL_ALGERIE_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/AXMayte.png" group-title="",Echorouk TV
https://cdn02.hta.dz/abr_htatv/Echorouk_TV_HD/htatv/Echorouk_TV_HD_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/IZTe4rk.png" group-title="",Echorouk NEWS
https://cdn02.hta.dz/abr_htatv/ECHOROUK_NEWS/htatv/ECHOROUK_NEWS_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/Bp00gMu.png" group-title="",EL BILAD
https://cdn02.hta.dz/abr_htatv/EL_BILAD/htatv/EL_BILAD_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/EoB4f6e.png" group-title="",El Djazair N1
https://cdn02.hta.dz/abr_htatv/El_Djazair_N1/htatv/El_Djazair_N1_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/OhTioAg.png" group-title="",El Djazairia One
https://cdn02.hta.dz/abr_htatv/EL_DJAZAIRIA_TV/htatv/EL_DJAZAIRIA_TV_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/Br7bAVR.png" group-title="",EL FADJR TV
https://cdn02.hta.dz/abr_htatv/EL_FADJR_TV_DZ/htatv/EL_FADJR_TV_DZ_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/fNLiJwK.png" group-title="",EL HAYAT TV
https://cdn02.hta.dz/abr_htatv/EL_HAYAT_TV_ALGERIE/htatv/EL_HAYAT_TV_ALGERIE_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/qd1sCE8.png" group-title="",El Heddaf TV
https://cdn02.hta.dz/abr_htatv/EL_HEDDAF_TV/htatv/EL_HEDDAF_TV_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/ta9o5qJ.png" group-title="",Ennahar TV
https://cdn02.hta.dz/abr_htatv/ENNAHAR_TV/htatv/ENNAHAR_TV_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/tFXvY71.png" group-title="",ENTV
https://cdn02.hta.dz/abr_htatv/PROGRAMME_NATIONAL/htatv/PROGRAMME_NATIONAL_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/WeGG33J.png" group-title="",Lina TV
https://cdn02.hta.dz/abr_htatv/Lina_TV/htatv/Lina_TV_720p/chunks.m3u8

#EXTINF:-1 tvg-id="samiratv.dz" tvg-name="SamiraTV" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/5C80xDT.png" group-title="",Samira TV
https://cdn02.hta.dz/abr_htatv/SamiraTV/htatv/SamiraTV_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/dYlAfFZ.png" group-title="",TV7 ELMAARIFA
https://cdn02.hta.dz/abr_htatv/TV7_ELMAARIFA/htatv/TV7_ELMAARIFA_720p/chunks.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="DZ" tvg-language="" tvg-logo="https://i.imgur.com/l7hw1W6.png" group-title="",TV8 EDHAKIRA
https://cdn02.hta.dz/abr_htatv/TV8_EDHAKIRA/htatv/TV8_EDHAKIRA_720p/chunks.m3u8

**Comment by LaneSh4d0w** [comment]
Excellent work @Sphinxroot . Last time I had checked they had enforced the tokens to make it work.
