### ISSUE TITLE
Add: Rotana Classic

### ISSUE THREAD

**Issue by iptvchecker** [iptv-org/iptv#2802]
**Channel Name:** Rotana Classic
**Country:** KSA
**Language:** Arabic
**External Link (optional):** rotana.net
**Notes (optional):** Please put back Rotana Classic coming from shahid.net/
There is a Rotana Classic channel that is Geo-Blocked. Please do the same that was done for Al-Resalah (1080p). Most-likely the not-geo-blocked channel was removed from a recent list, thinking the two entries were redundant!

**Comment by freearhey** [comment]
Resolved via https://github.com/iptv-org/iptv/commit/dd11f4f5ab14d277825141fa84b50232c7050603
