### ISSUE TITLE
Add: Rotana Comedy

### ISSUE THREAD

**Issue by iptvchecker** [iptv-org/iptv#2803]
**Channel Name:** Rotana Comedy
**Country:** KSA
**Language:** Arabic
**External Link (optional):** rotana.net
**Notes (optional):** Please put back Rotana Comedy coming from shahid.net/
There is a Rotana Comedy channel that is Geo-Blocked. Please do the same that was done for Al-Resalah (1080p). Most-likely the not-geo-blocked channel was removed from a recent list, thinking the two entries were redundant!

**Comment by freearhey** [comment]
Resolved via https://github.com/iptv-org/iptv/commit/dd11f4f5ab14d277825141fa84b50232c7050603

**Comment by iptvchecker** [comment]
One Comedy channel was added, but it's Geo-Blocked! Please try with the links from shahid.net as all the Rotana channels that work, come from that site, including Comedy.

**Comment by freearhey** [comment]
@iptvchecker we have no other links to the channel at this time.
