### ISSUE TITLE
Add: Rotana Drama

### ISSUE THREAD

**Issue by iptvchecker** [iptv-org/iptv#2804]
**Channel Name:** Rotana Drama
**Country:** KSA
**Language:** Arabic
**External Link (optional):** rotana.net
**Notes (optional):** Please put back Rotana Drama coming from shahid.net/
There is a Rotana Drama channel that is Geo-Blocked. Please do the same that was done for Al-Resalah (1080p). Most-likely the not-geo-blocked channel was removed from a recent list, thinking the two entries were redundant! 

It's helpful to tag Rotana channels coming from shahid.net as not-(Geo-Blocked)

**Comment by freearhey** [comment]
Resolved via https://github.com/iptv-org/iptv/commit/dd11f4f5ab14d277825141fa84b50232c7050603
