### ISSUE TITLE
cliptv.az is still a reliable source

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#2808]
The problem is that it streams in MPEG Dash so VLC freezes on quality switch attempts. Something that doesn't happen in SimpleTV, Televizo and other proper IPTV clients, so it's more like a VLC issue

**Comment by heroku-miraheze** [comment]
The problem is your player, NOT the server.

**Comment by LaneSh4d0w** [comment]
Why would it be a broken stream ? Were they deleted over time ?

**Comment by Dum4G** [comment]
May not be a proper tag but freearhey  has already removed many channels as "freezing after few secs"

**Comment by LaneSh4d0w** [comment]
It's because I, like Arhey, tend to use VLC when we're testing links, so indeed, if we see it doesn't work, we tend to take them off.

Maybe we should make sure the links work by testing it on 2 different players, what do you think @freearhey ?

**Comment by freearhey** [comment]
@LaneSh4d0w I agree, but I do not know what else player supports all platforms as well as VLC. If you find one, let me know.

**Comment by trancer1994** [comment]
Why are you using an illegal source for some streams anyway (cliptv.az)? That's only going to get you dmca'd.

**Comment by Dum4G** [comment]
> Why are you using an illegal source for some streams anyway (cliptv.az)? That's only going to get you dmca'd.

We use soooo many unverified sources that are coming directly from IP addressess or supposed to be seen on mobile/TV set devices. If we consider some truly libre practices this repo will mostly consist of European news channels

**Comment by trancer1994** [comment]
@Dum4g I don't mind links that are meant to be seen on tv sets or mobile devices, but it's mainly unofficial streams or re-streams that I have an issue with. For instance, I'm sure some of those cliptv.az channels have official streams somewhere. Some of the Azerbaijani channels for instance. Idman is one example I can think of. If I remember rightly that has a stream on its website, or maybe I'm confusing it with another tv channel.

**Comment by LaneSh4d0w** [comment]
I think those are already available on the internet. I'll make a list of the streamed channels and i'll see if I can find a correct alternative.

**Comment by trancer1994** [comment]
@LaneSh4d0w I meant the links to unofficial streams of channels where official streams already exist.

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w I meant the links to unofficial streams of channels where official streams already exist. 

Yes, i'm talking about official streams actually. If the official stream is a decent alternative, better stick to it.

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w So are you saying you would dump a non-decent stream that is actually from the site in favour of a more decent restream? 

I've said **if** the official stream is a better alternative. But that's the idea. In terms of stability we should see, but in terms of uptime it'll probably be better.

**Comment by LaneSh4d0w** [comment]
> 
> 
> @LaneSh4d0w I agree, but I do not know what else player supports all platforms as well as VLC. If you find one, let me know.

Test using MPC-HC : https://github.com/clsid2/mpc-hc/releases/tag/1.9.11.14

Open file, and add any cliptv.az stream on the "file" section. Seems to work for me. It uses youtube-dl to work.

**Comment by lrm864** [comment]
So let me clear up the big confusion. The ClipTV streams are legal. Those streams are official from the ClipTV service in Azerbaijan located here (Scroll down to see the channels):
https://cliptv.az
The company is an official IPTV company in the country of Azerbaijan:
https://ntrc.gov.az/en/category/iptv-operators
https://ntrc.gov.az/en/news/436
Yes, the streams are in the MPEG-Dash format known as .mpd. And yes, some players do have trouble playing .mpd streams like VLC for example, but other players such as Tivimate will have no issues as long as the stream is not DRM protected, which right now the ClipTV streams are not DRM protected.

**Comment by Dum4G** [comment]
Ehehe, let it be that way
