### ISSUE TITLE
Spain Channels

### ISSUE THREAD

**Issue by KingMorisco** [iptv-org/iptv#2813]
**Channel Name:** Movistar Package
**Country:** Spain
**Language:** Spanish
**External Link (optional):** xxx
**Notes (optional):** xxx

**Comment by manchego43** [comment]
Alguna lista de cabales tdt y autónomos por favor

**Comment by LaneSh4d0w** [comment]
Spanish channels... there's a lot of them haha ! I'll try to see.

**Comment by freearhey** [comment]
@KingMorisco Next time, please read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel) first.

**Comment by manchego43** [comment]
No se me ven estos programas en Android auto después de pagar pir ser pro.como lo puedo arreglar ?

Enviado de Samsung Mobile
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by LaneSh4d0w** [comment]
> 
> No se me ven estos programas en Android auto después de pagar pir ser pro.como lo puedo arreglar ?

Not sure I've understood you but you cannot see any Spanish stream after buying ?

You don't need to buy anything when watching these. Simply download some kind of app like the IPTV app by Alexander Sofronov or Televizo.

**Comment by manchego43** [comment]
Ya la tengo descargada y no seme ve en android auto

Enviado de Samsung Mobile
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by LaneSh4d0w** [comment]
You're trying to watch those channels in Android Auto... I don't think they can stream anything else than audio or Waze, those kind of stuff. Might be depending of the car, i don't know.
