### ISSUE TITLE
Add: Nick Jr Too

### ISSUE THREAD

**Issue by nickjrukfan** [iptv-org/iptv#2816]
**Channel Name:** Nick Jr Too
**Country:** Europe
**Language:** British English
**Notes (optional):** when will my requested channels be added?

**Comment by Dum4G** [comment]
When you understand that our community of volunteers will try to help you, but if a public link cannot be found, there is little we can do.

**Comment by Dum4G** [comment]
Here we go
#EXTINF:-1 tvg-id="uk.nickjrtoo" tvg-name="Nick Jr.Too" tvg-logo="http://neczbm.to/images/channels/NickJrToo.png" group-title="Kids",UK: Nick Jr.Too
http://46.105.112.116/?watch=EX/Nick_Jr_Too-uk

**Comment by 0845** [comment]
> Here we go
> #EXTINF:-1 tvg-id="nickjrtoo.uk" tvg-name="Nick Jr. Too" tvg-country="UK;IE" tvg-language="English" tvg-logo="http://neczbm.to/images/channels/NickJrToo.png" group-title="Kids",Nick Jr. Too
> http://46.105.112.116/?watch=EX/Nick_Jr_Too-uk
> 
> https://en.wikipedia.org/wiki/Nick_Jr._(British_and_Irish_TV_channel)

Remove these links pointing to other sources no need to be displaying them.
