### ISSUE TITLE
SBS TV link is down

### ISSUE THREAD

**Issue by D-Booty** [iptv-org/iptv#2828]
Trying to watch Australia's SBS . The link doesn't open in browser on Safari or Chrome. Can't open as a stream in VLC.

61. SBS TV [Geo-blocked] 
https://i.mjh.nz/au/Sydney/tv.320203000301.m3u8

**Comment by freearhey** [comment]
The link works, but only from Australia or via VPN.

![image](https://user-images.githubusercontent.com/7253922/118981449-032bf980-b983-11eb-8fbd-9b7e6ffefa0a.png)

That's why it's marked as `[Geo-blocked]`.
