### ISSUE TITLE
Streamlink sources thread

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#2833]
Please try this service not only in VLC but in every other player or IPTV client you use, preferably on Android and report back.

`
http://salvahe.co/iptv-query?url=https://www.youtube.com/c/kenyacitizentv/live`

So far it works in:
VLC v3.0.14
Elmedia Video Player v7.17 (freearhey)
Kodi Playlistloader addon (Sphinxroot)
IPTV Safronov? (LaneSh4d0w)
Televizo (Independent test)
OTT Navigator (Independent test)

Doesn't work in:
SimpleTV
http://jackal.surge.sh/ and other web clients
GSE Smart IPTV v2.3  (freearhey)
LazyIPTV (Independent test)

**UPD:** Doesn't work with https://www.youtube.com/EuronewsUSA/live

May be at least temporary solution to https://github.com/iptv-org/iptv/issues/2158, https://github.com/iptv-org/iptv/issues/2781 and https://github.com/iptv-org/iptv/issues/2729

**Comment by freearhey** [comment]
VLC v3.0.14 - works fine
Elmedia Video Player v7.17 - works fine
GSE Smart IPTV v2.3 - stream loads, but then the endless buffering starts

**Comment by Dum4G** [comment]
@brianmusundi you're probably watching those channels at least for an hour on a TV set, I'd like to see your thoughts on those two

http://salvahe.co/iptv-query?url=https://www.youtube.com/c/kenyacitizentv/live
http://salvahe.co/iptv-query?url=https://www.youtube.com/c/KTNKenya/live

**Comment by Sphinxroot** [comment]
Test those please 

#EXTINF:-1 tvg-logo="" group-title="",Radio MRG (Dailymotion)
http://salvahe.co/iptv-query?url=https://www.dailymotion.com/video/x69a2vh

#EXTINF:-1 tvg-logo="" group-title="",BTVStelevision (Twitch)
http://salvahe.co/iptv-query?url=https://www.twitch.tv/btvstelevision/


Working in kodi Playlistloader addon

**Comment by Dum4G** [comment]
> Test those please

Actually does work in VLC, also acts as a proxy server (Dailymotion is blocked for me) 🤯

**Comment by Sphinxroot** [comment]
> > Test those please
> 
> Actually does work in VLC, also acts as a proxy server (Dailymotion is blocked for me)

All Dailymotion or just this 1  .. might be geoblocked

**Comment by Dum4G** [comment]
> All Dailymotion or just this 1 .. might be geoblocked
It is entirely blocked in my country

**Comment by LaneSh4d0w** [comment]
Interesting...

**Comment by LaneSh4d0w** [comment]
Works on IPTV application (Android) with KCTV

#EXTINF:-1 tvg-logo="" group-title="",Korean Central Television (Twitch.tv / elufatv)
http://salvahe.co/iptv-query?url=https://www.twitch.tv/elufatv

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-logo="" group-title="",ChilledCat - 24/7 lofi beats to chill (DLive)
http://salvahe.co/iptv-query?url=https://dlive.tv/ChilledCat

it would be a major upgrade if its accepted   ... Youtube  Dailymotion Twich  Dlive  , 1k+ Channel could be added .. possibly other Services  as well  .. i have tested some Fox local with token but it doesnt work

**Comment by Dum4G** [comment]
> it would be a major upgrade if its accepted ...

Just to clarify. This is NOT commercial host from Santa Claus with fancy landing page. It's someone's private proxy that I accidentally found that probably runs on a single cheap VM until it is reasonable to run it. And it seems to be located far away from us. If it's gonna be approved it will only be used for emergency cases like Kenya playlist where official content providers and restreamers do not exist at all.

**Comment by LaneSh4d0w** [comment]
> > it would be a major upgrade if its accepted ...
> 
> Just to clarify. This is NOT commercial host from Santa Claus with fancy landing page. It's someone's private proxy that I accidentally found that probably runs on a single cheap VM until it is reasonable to run it. And it seems to be located far away from us. If it's gonna be approved it will only be used for emergency cases like Kenya playlist where official content providers and restreamers do not exist at all.

Best thing would be to simply get the scripts he does and re-host them to keep the original link safe and sound.

**Comment by Dum4G** [comment]
> Best thing would be to simply get the scripts he does and re-host them to keep the original link safe and sound.
It's running https://streamlink.github.io/index.html I guess

**Comment by LaneSh4d0w** [comment]
> 
> 
> > Best thing would be to simply get the scripts he does and re-host them to keep the original link safe and sound.
> 
> It's running https://streamlink.github.io/index.html I guess

I think I can manage something... Let me see.

**Comment by Nintendocustom** [comment]
https://iptv--iptv.repl.co/streamlink?url=
example:
https://iptv--iptv.repl.co/streamlink?url=https://www.twitch.tv/elufatv

**Comment by LaneSh4d0w** [comment]
You were faster than me for this one haha ! Well played.

**Comment by LaneSh4d0w** [comment]
Here's my version, in case of : 
https://query-streamlink.lanesh4d0w.repl.co/iptv-query?streaming-ip=
Example : 
https://query-streamlink.lanesh4d0w.repl.co/iptv-query?streaming-ip=https://dlive.tv/ChilledCat

**Comment by Dum4G** [comment]
Ok, now the only question remains: how long does those streams work before it needs to be restarted manually? We need someone to watch real YT or DM channel for an hour or so.

**Comment by LaneSh4d0w** [comment]
> Ok, now the only question remains: how long does those streams work before it needs to be restarted manually? We need someone to watch real YT or DM channel for an hour or so.

I know that Streamlink's quite viable when it Comes to using it on Windows as a standalone package, but yes, we still need to see how that works over time. I suggest to look at @Nintendocustom 's implementation first, then mine.

**Comment by brianmusundi** [comment]
> https://iptv--iptv.repl.co/streamlink?url=
> example:
> https://iptv--iptv.repl.co/streamlink?url=https://www.twitch.tv/elufatv

this works well with the Dailymotion links. It generates a m3u8 file if you open it directly on the browser. Let me test it out on a playlist
@Dum4G i could swap the tokenized links for these ones

**Comment by LaneSh4d0w** [comment]
> > https://iptv--iptv.repl.co/streamlink?url=
> > example:
> > https://iptv--iptv.repl.co/streamlink?url=https://www.twitch.tv/elufatv
> 
> this works well with the Dailymotion links. It generates a m3u8 file if you open it directly on the browser. Let me test it out on a playlist
> @Dum4G i could swap the tokenized links for these ones
> It works well with youtube as well

If you can, please watch those kind of links on a bigger amount of time (around an hour at least) just to see if those links still work over time.

**Comment by brianmusundi** [comment]
> > > https://iptv--iptv.repl.co/streamlink?url=
> > > example:
> > > https://iptv--iptv.repl.co/streamlink?url=https://www.twitch.tv/elufatv
> > 
> > 
> > this works well with the Dailymotion links. It generates a m3u8 file if you open it directly on the browser. Let me test it out on a playlist
> > @Dum4G i could swap the tokenized links for these ones
> > It works well with youtube as well
> 
> If you can, please watch those kind of links on a bigger amount of time (around an hour at least) just to see if those links still work over time.

Alright. I'll set up a playlist then let it run in the background.
The issue might be if the streamlink application runs for over an hour. The other links will play throughout aside from a channel or two that goes offline once in a while.

**Comment by LaneSh4d0w** [comment]
Exactly. That'll permit to see if our implementation's viable over time.

**Comment by brianmusundi** [comment]
So far I've seen a problem with only one link as at the moment.
https://iptv--iptv.repl.co/streamlink?url=https://www.dailymotion.com/video/x7l3lxv
It just won't load on vlc.

**Comment by LaneSh4d0w** [comment]
Geolocked

**Comment by Nintendocustom** [comment]
There is something I forgot to mention, if you pass the parameter quality, you can get different quality.
https://iptv--iptv.repl.co/streamlink?url=https://www.twitch.tv/elufatv&quality=worst
https://iptv--iptv.repl.co/streamlink?url=https://www.twitch.tv/elufatv&quality=best
https://iptv--iptv.repl.co/streamlink?url=https://www.twitch.tv/elufatv&quality=480p
https://iptv--iptv.repl.co/streamlink?url=https://www.twitch.tv/elufatv&quality=360p

**Comment by brianmusundi** [comment]
> Geolocked

Alright. That makes sense. All the rest of the links work. Let me send my playlist

**Comment by Dum4G** [comment]
> There is something I forgot to mention, if you pass the parameter quality, you can get different quality.

That's a risky option, at least for Twitch. Sometimes they offer streams in a single quality, it's pretty random

**Comment by brianmusundi** [comment]
[ke - Copy.txt](https://github.com/iptv-org/iptv/files/6526263/ke.-.Copy.txt)
here's my fixed playlist
@Dum4G

**Comment by LaneSh4d0w** [comment]
> > There is something I forgot to mention, if you pass the parameter quality, you can get different quality.
> 
> That's a risky option, at least for Twitch. Sometimes they offer streams in a single quality, it's pretty random

He said that you could, not that you should. Note that the option that works for every Twitch stream is "source"

**Comment by Dum4G** [comment]
> [ke - Copy.txt](https://github.com/iptv-org/iptv/files/6526263/ke.-.Copy.txt)
> here's my fixed playlist

Thx, I will push it soon as you report us how long does those links last before it needs to be reconnected

**Comment by LaneSh4d0w** [comment]
> 
> 
> [ke - Copy.txt](https://github.com/iptv-org/iptv/files/6526263/ke.-.Copy.txt)
> here's my fixed playlist
> @Dum4G
> Just rename to .m3u
> only link with issues is one. The KTN

Change
#EXTINF:-1 tvg-id="KTN NEWS TV Kenya" tvg-name="KTN NEWS" tvg-country="KE" tvg-language="English" tvg-logo="https://kenyatv.tech/wp-content/uploads/2020/11/unnamed.jpg" tvg-url="" group-title="Kenyan",KTN NEWS TV Kenya
https://iptv--iptv.repl.co/streamlink?url=https://www.youtube.com/user/standardgroupkenya

to 

#EXTINF:-1 tvg-id="KTN NEWS TV Kenya" tvg-name="KTN NEWS" tvg-country="KE" tvg-language="English" tvg-logo="https://kenyatv.tech/wp-content/uploads/2020/11/unnamed.jpg" tvg-url="" group-title="Kenyan",KTN NEWS TV Kenya
https://iptv--iptv.repl.co/streamlink?url=https://www.youtube.com/user/standardgroupkenya/live

**Comment by Dum4G** [comment]
Is KTN different from KTN News?

**Comment by LaneSh4d0w** [comment]
> 
> 
> Is KTN different from KTN News?

A possibility that one is a 24hr News programme, and that the other one is General programmation.

**Comment by brianmusundi** [comment]
> > [ke - Copy.txt](https://github.com/iptv-org/iptv/files/6526263/ke.-.Copy.txt)
> > here's my fixed playlist
> > @Dum4G
> > Just rename to .m3u
> > only link with issues is one. The KTN
> 
> Change
> #EXTINF:-1 tvg-id="KTN NEWS TV Kenya" tvg-name="KTN NEWS" tvg-country="KE" tvg-language="English" tvg-logo="https://kenyatv.tech/wp-content/uploads/2020/11/unnamed.jpg" tvg-url="" group-title="Kenyan",KTN NEWS TV Kenya
> https://iptv--iptv.repl.co/streamlink?url=https://www.youtube.com/user/standardgroupkenya
> 
> to
> 
> #EXTINF:-1 tvg-id="KTN NEWS TV Kenya" tvg-name="KTN NEWS" tvg-country="KE" tvg-language="English" tvg-logo="https://kenyatv.tech/wp-content/uploads/2020/11/unnamed.jpg" tvg-url="" group-title="Kenyan",KTN NEWS TV Kenya
> https://iptv--iptv.repl.co/streamlink?url=https://www.youtube.com/user/standardgroupkenya/live

hahhahaa how did I not notice I forgot to add /live.
Thanks for catching that

**Comment by LaneSh4d0w** [comment]
I'm actually researching some stuff on my host, please refrain from using it for the moment and use @Nintendocustom 's version.

**Comment by brianmusundi** [comment]
> Is KTN different from KTN News?

Yeah. They are owned by the same company but offer different content

**Comment by brianmusundi** [comment]
[ke.txt](https://github.com/iptv-org/iptv/files/6526314/ke.txt)

@Dum4G 
Fixed it. All links working
Also added a few more channels.
KTN will remain tokenized till I find a solution.
There are no issues with the stream so far.

**Comment by LaneSh4d0w** [comment]
I've took Nintendocustom's implementation into consideration, and added 2 things.

- quality
https://query-streamlink.lanesh4d0w.repl.co/iptv-query?streaming-ip=https://dlive.tv/ChilledCat&quality=best

- specific_header (in testing)
https://query-streamlink.lanesh4d0w.repl.co/iptv-query?streaming-ip=https://cdn.teveo.cu/live/video/vXykXvhUczkVP7R7/ngrp:9KJTMRBAm2BbnsYK.stream/playlist.m3u8&specifc_header="Referer: https//teveo.cu"

**Comment by brianmusundi** [comment]
So these links only work with IPTV players. They won't load on Roku.

**Comment by brianmusundi** [comment]
Does anyone know how to get a working IPTV player for Roku?
I've been running my tokenized links to watch tv via my roku channel.

**Comment by Dum4G** [comment]
There's many. Which model do you have?

**Comment by brianmusundi** [comment]
I'm using a Roku Premier

**Comment by Dum4G** [comment]
You can try casting from any of your old phones

**Comment by brianmusundi** [comment]
Sadly that wasn't an available option. That's why I went as far as creating my own channel

**Comment by Dum4G** [comment]
https://www.youtube.com/watch?v=P0O0uD1S6yI

**Comment by brianmusundi** [comment]
> https://www.youtube.com/watch?v=P0O0uD1S6yI

I already attempted this. It didn't work for me because I don't have a provider URL or username and password. It's for personal use and didn't want to pay monthly charges

**Comment by brianmusundi** [comment]
@nathanmuccino did you disable the server?

**Comment by LaneSh4d0w** [comment]
You meant Nintendocustom ?

**Comment by brianmusundi** [comment]
> You meant Nintendocustom ?

Yeah
My bad
I was typing in a rush and went for the first name that came up with the letter N.

**Comment by brianmusundi** [comment]
It's running again.
I don't know if the server goes offline if it's not used after an hour or something

**Comment by brianmusundi** [comment]
If you could show me, I can have it running on heroku for longer

**Comment by LaneSh4d0w** [comment]
I do not know much about how Heroku works, sorry !

**Comment by Dum4G** [comment]
If you use Kenyan hosting  we'll be able to watch KTN

**Comment by Nintendocustom** [comment]
I just added YouTube-dl in some minutes (https://iptv--iptv.repl.co/youtube_dl), it works like the Streamlink one (except for the quality option) and can be used as alternative.

**Comment by LaneSh4d0w** [comment]
> 
> 
> I just added YouTube-dl in some minutes (https://iptv--iptv.repl.co/youtube_dl), it works like the Streamlink one (except for the quality option) and can be used as alternative.

Amazing, try this too : https://streamlink.github.io/api.html#streamlink.Streamlink.set_option

We can add headers using this. It could reactivate some links we couldn't use due to referrer issues. I'm working on it too but i'm having slight issues into giving the options to Streamlink

**Comment by Nintendocustom** [comment]
@LaneSh4d0w It looks like you are working with flask. You could add a new parameter that works as json file.
At first getting the parameter and loading it as json:
`parameters = json.loads(request.values.get("params", []))`
and now passing the parameters and loading the stream:
```
s = streamlink.Streamlink()
for param in parameters:
    s.set_option(param, parameters[param])
    stream = s.streams(url)
```
Of course, don't forget the error handling!

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w It looks like you are working with flask. You could add a new parameter that works as json file.
> At first getting the parameter and loading it as json:
> `parameters = json.loads(request.values.get("params", []))`
> and now passing the parameters and loading the stream:
> ```
> s = streamlink.Streamlink()
> for param in parameters:
>     s.set_option(param, parameters[param])
>     stream = s.streams(url)
> ```
> Of course, don't forget the error handling!

Indeed, I'm gonna deal with that once I'll get finished with some background stuff. Thanks for the tips 👌

**Comment by LaneSh4d0w** [comment]
I think the Node implementation is less than a hassle to deal with... I think i'm gonna move my work into my iptv-all repl.

**Comment by andrew88saldivar** [comment]
Fr

**Comment by Dum4G** [comment]
@Nintendocustom have you enabled ustream plugin? I'm failing to play it in VLC
https://video.ibm.com/embed/23367184

**Comment by Nintendocustom** [comment]
@Dum4G everything is enabled, but the stream doesn't seem to have a manifest.

**Comment by LaneSh4d0w** [comment]
Stream info is given by a websocket.

**Comment by LaneSh4d0w** [comment]
Still testing stuff, but if you're unsure about the available qualities of a stream, you can just put "unsure" on the quality query. It will return all available occurences of the stream : 
https://query-streamlink.lanesh4d0w.repl.co/iptv-query?streaming-ip=https://www.twitch.tv/elufatv&quality=unsure

will give this : 

![image](https://user-images.githubusercontent.com/30985701/119276954-3b4e6900-bc1d-11eb-9dcf-2e5f898249f1.png)

**Comment by fotvnetwork** [comment]
Thank you for sharing

**Comment by bagushp** [comment]
http://salvahe.co/iptv-query?url=https://www.youtube.com/channel/.......
can't be used anymore, is there a solution?

**Comment by LaneSh4d0w** [comment]
> 
> 
> http://salvahe.co/iptv-query?url=https://www.youtube.com/channel/.......
> can't be used anymore (502 bad gateway), is there a solution?

You can use those links : 

https://iptv--iptv.repl.co/streamlink?url=xxxxxxxxx
https://query-streamlink.lanesh4d0w.repl.co/iptv-query?streaming-ip=xxxxxxxxxx

**Comment by bagushp** [comment]
> https://query-streamlink.lanesh4d0w.repl.co/iptv-query?streaming-ip=

Can used
thanks

**Comment by bagushp** [comment]
> 
> 
> > http://salvahe.co/iptv-query?url=https://www.youtube.com/channel/.......
> > can't be used anymore (502 bad gateway), is there a solution?
> 
> You can use those links :
> 
> https://iptv--iptv.repl.co/streamlink?url=xxxxxxxxx
> https://query-streamlink.lanesh4d0w.repl.co/iptv-query?streaming-ip=xxxxxxxxxx

Can used
thanks

**Comment by Nintendocustom** [comment]
I added @LaneSh4d0w's https://query-streamlink.lanesh4d0w.repl.co as backup in case my streamlink url is not working.

**Comment by LaneSh4d0w** [comment]
> 
> 
> I added @LaneSh4d0w's https://query-streamlink.lanesh4d0w.repl.co as backup in case my streamlink url is not working.

I also added, to the root of my server, a link to Nintendo's version.

@Nintendocustom By curiosity, are you using Node ?

**Comment by Dum4G** [comment]
Made by the same guy who holds his own Kenyan playlist and inspired me to use streamlink in the first place. Cool

**Comment by Nintendocustom** [comment]
No, I'm using Python.

**Comment by LaneSh4d0w** [comment]
> 
> 
> No, I'm using Python.

Ah okay, you might have a slightly different implementation than mine then indeed.

**Comment by keystroke3** [comment]
Oh, hey all. https://salvahe.co/ needed a facelift. I did not expect this tool to already be used. Yes, I did a whole remaster of the site. The query part will be up in a short while. If you have any questions or suggestions, send them to me.

**Comment by keystroke3** [comment]
Update made. You can now access the server in headless mode at  `https://salvahe.co/headless?url=`. I am glad to my tool is being used by other people. If you can buy me a coffee to keep the server up, that would be nice.
