### ISSUE TITLE
Propose: automatically move xxx category channels to the bottom of playlists

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#2836]
For every single file in this repo so playlists like fr (origin) and int literally didn't start from anal channel.
The change guarantees a bit more predictability of playlists since nobody wants to be missing out 80% of IPTV-org content with .sfw variants I guess.

**Comment by Sphinxroot** [comment]
maybe  have all XXX channel in 1 playlist  appart  of the country playlist could be  the solution

**Comment by LaneSh4d0w** [comment]
Well... it's tricky to do so. We could sort channels by their groups, (XXX would be at the bottom then), but it's against the original sorting that wants them to be ordered by their name.

**Comment by themak1985** [comment]
I have always wondered why we don't treat XXX like its own country - since there are so many requests for SFW versions.

**Comment by LaneSh4d0w** [comment]
Indeed, now that you mention it we're having lots of that. Since we have the .sfw variants, we're already, in a certain extent, treating it like a different thing. We're also doing it by country, so...

**Comment by themak1985** [comment]
> Indeed, now that you mention it we're having lots of that. Since we have the .sfw variants, we're already, in a certain extent, treating it like a different thing. We're also doing it by country, so...

And honestly does anyone thats consuming the content really care which country is broadcasting that content?

**Comment by LaneSh4d0w** [comment]
> > Indeed, now that you mention it we're having lots of that. Since we have the .sfw variants, we're already, in a certain extent, treating it like a different thing. We're also doing it by country, so...
> 
> And honestly does anyone thats consuming the content really care which country is broadcasting that content?

I don't think so
