### ISSUE TITLE
Add: hgtv

### ISSUE THREAD

**Issue by fcsapos** [iptv-org/iptv#2840]
**Channel Name:** hdtv
**Country:** USA
**Language:** English
**External Link (optional):** 
**Notes (optional):**

**Comment by LaneSh4d0w** [comment]
Not quite sure that a channel in the name of "HDTV" exists in the United States.

Please be more precise.

**Comment by MapGuy11** [comment]
HGTV?

**Comment by LaneSh4d0w** [comment]
Due to OP not answering our questions concerning this channel, i'll close this issue.

**Comment by freearhey** [comment]
HGTV channel is on the [blocklist](https://github.com/iptv-org/iptv/blob/master/scripts/blacklist.json) due to claims of rights holders (#1831) and we can't add it to the playlist anyway.
