### ISSUE TITLE
Add: TV Brasil

### ISSUE THREAD

**Issue by ygorlv** [iptv-org/iptv#2841]
**Channel Name:** TV Brasil
**Country:** Brazil
**Language:** Portuguese
**External Link (optional):** https://edge-df-01.eduplay.rnp.br/media/ocp(r(iRGrcw)t(AAAAAAAAAAA)p(d(Dxg)k(Qdk)m(naXbjbTlDxrHlrlxKSNzig)n(a(3LDBWxJLACwHVOavx5cO4BC5lA2ZDpPC)s(HrY)'a(12ztgSdgu3rQqz6xH52ZjVZa)s(Pm8)))s(t(aTo)b(PTsuEXhXAScNjp6w9ssG70foQQQiZk9_8m0vsjgLJ_yzxGPuj8i57PEDMMA4cmTNsKda2B5oX-EEErouZ1HFyuG_AaUF86vlMJtsMkooySBOlQbVM33PgsYPQdea2BJafjjc-BWtPRlStfmQ939PXcd844pid2JY82J6JDM)'t(S2o)b(WaBWYarWoWCInKe38WSze3Q_-kYcqZf8MZQ)))/live_720_index.m3u8
**Notes (optional):** tvg-logo="https://upload.wikimedia.org/wikipedia/pt/1/1c/Logotipo_da_TV_Brasil.png" group-title="General"

**Comment by Sphinxroot** [comment]
Este conteúdo não está disponível para a sua região. Geo and token stream

**Comment by ygorlv** [comment]
What a shame! I would like foreigners be allowed to watch it
