### ISSUE TITLE
Add: Loading

### ISSUE THREAD

**Issue by ygorlv** [iptv-org/iptv#2842]
**Channel Name:** Loading
**Country:** Brazil
**Language:** Portuguese
**External Link (optional):** https://akamai.gcp.br.cdn.booyah.live/hls/151073/34850987_1080.m3u8
**Notes (optional):** tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Loading_TV.svg/640px-Loading_TV.svg.png" group-title="Entertainment"

**Comment by Sphinxroot** [comment]
https://loading.com.br/ao-vivo/

Geo Stream

**Comment by MapGuy11** [comment]
Yup GEO Stream
