### ISSUE TITLE
Add: TV Cultura (720p)

### ISSUE THREAD

**Issue by ygorlv** [iptv-org/iptv#2843]
**Channel Name:** TV Cultura (720p)
**Country:** Brazil
**Language:** Portuguese
**External Link (optional):** https://stream-04.nyc.dailymotion.com/sec(RiWEtJG0nU_F5iuiUOWAlzg2xfgQxBpfJDYQdk6JdCk)/dm/3/x7wur7g/s/live-3.m3u8
**Notes (optional):** vg-logo="https://logodownload.org/wp-content/uploads/2017/11/tv-cultura-logo-1.png" group-title="General"

**Comment by Sphinxroot** [comment]
its a dailymotion geo stream and the token will change over time .. until we find a permanant  solution  it can`t be added 

but u can use it ,in your own playlist

in kodi 
#EXTINF:-1 tvg-logo="https://logodownload.org/wp-content/uploads/2017/11/tv-cultura-logo-1.png" group-title="",TV Cultura (DM)
plugin://plugin.video.dailymotion_com/?url=x7wur7g&mode=playLiveVideo

in VLC
https://www.dailymotion.com/video/x7wur7g#tab_embed.m3u8
