### ISSUE TITLE
Add: AmericaTeve

### ISSUE THREAD

**Issue by HeIp** [iptv-org/iptv#2852]
**Channel Name:** AmericaTeve
**Country:** UnitedStates
**Language:** Spanish
**External Link (optional):** https://www.americateve.com/contenidos/vivo.html or https://ssh101.com/detail.php?id=ACVTV
**Notes (optional):** 
Tried using this stream m3u8 to get it work :
https://tna5.bozztv.com/ACVTV/index.m3u8
Tried getting this m3u8 stream to work with the following :
https://tna5.bozztv.com/ACVTV/index.m3u8|if-modified-since=Thu, 18 Mar 2021 00:44:42 GMT&if-none-match="1a1-5bdc4e7b48da1-gzip"&!Sec-Fetch-Dest=empty&!Sec-Fetch-Mode=cors&!Sec-Fetch-Site=cross-site&!sec-ch-ua-mobile=?0&dnt=1&!Host=tna5.bozztv.com&!sec-ch-ua="Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"&origin=https=//ssh101.com&referer=https=//ssh101.com/&User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

I tried using custom headers and the user-agent header but did not load

**Comment by Sphinxroot** [comment]
https://www.americateve.com/contenidos/vivo.html = VOD Youtube  ,doesnt seem to have a live stream

https://tna5.bozztv.com/ACVTV/index.m3u8 = 404 Not Found and no manifest

https://www.americateve.com/teveo = Offline


test this 1 if its the good channel your lookin at 

#EXTINF:-1 tvg-id="" tvg-logo="https://static.americateve.com/adjuntos/179/imagenes/000/428/0000428704.png" group-title="",America TeVe
https://americateve-rokuus.amagi.tv/master.m3u8

**Comment by HeIp** [comment]
It appears they recently moved to the roku platform. Was not aware.
