### ISSUE TITLE
Telugu channel Request Channels

### ISSUE THREAD

**Issue by rerugant** [iptv-org/iptv#2855]
Please add telugu channels

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="" tvg-language="" tvg-logo="https://i.imgur.com/E6oLstJ.jpg" group-title="",TV9 Telugu
https://vidcdn.vidgyor.com/tv9telugu-origin/live/playlist.m3u8
https://vidcdn.vidgyor.com/tv9telugu-origin/live/tv9telugu-origin/live1/chunks.m3u8


plenty here https://www.tvhub.in/telugu/ but mostly from youtube  and other are on yupptv that require a login to view and some are geo

**Comment by LaneSh4d0w** [comment]
Please read the ![guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#issue-reporting-guidelines) before submitting a channel request.
