### ISSUE TITLE
Add: TVE (Spain) Channels

### ISSUE THREAD

**Issue by ygorlv** [iptv-org/iptv#2860]
**Channel Name:** TVE
**Country:** Spain
**Language:** Spanish
**External Link (optional):**https://www.rtve.es/directo
**Notes (optional):**

#EXTINF:-1 tvg-country="ES" tvg-language="Spanish" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Logo_TVE-1.svg/800px-Logo_TVE-1.svg.png" group-ctitle="General",TVE 1
https://rtvelivestream.akamaized.net/la1_main_dvr.m3u8
#EXTINF:-1 tvg-country="ES" tvg-language="Spanish" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Logo_TVE-24h.svg/800px-Logo_TVE-24h.svg.png" group-ctitle="News",TVE 24h
https://rtvelivestream.akamaized.net/24h_main_dvr_576.m3u8
#EXTINF:-1 tvg-country="ES" tvg-language="Spanish" tvg-logo="https://www.colegiosgrancanaria.com/cmsAdmin/uploads/o_1af9lcndtu2913p2r2m1v1m1qdaa.jpg" group-ctitle="General",RTVE Canarias
https://hlsliveamdgl7-lh.akamaihd.net/i/hlsdvrlive_1@303292/index_1500_av-p.m3u8?sd=10&rebase=on
#EXTINF:-1 tvg-country="ES" tvg-language="Spanish" tvg-logo="https://img2.rtve.es/i/?w=1600&i=1597942722171.jpg" group-ctitle="General",RTVE Catalunya
https://rtvelivestream.akamaized.net/la1_cat_main_dvr_360.m3u8

**Comment by heroku-miraheze** [comment]
What do you mean???

**Comment by LaneSh4d0w** [comment]
I'm taking all those channels into consideration, and I'll look at the available playlists to see if we already got those. If they do not appear, we'll add them.

**Comment by ygorlv** [comment]
Thanks. After your answer, I have checked the general list and realized that already are some of those links, but with different names (TVE 1 is called "La 1", for example). That's why I asked wrong, sorry.
Anyway, I think only "TVE Canarias" is not already added.
Also, I suggest adding "La 2" https://rtvelivestream-lvlt.rtve.es/la2_main_dvr_1080.m3u8

**Comment by LaneSh4d0w** [comment]
> 
> 
> Thanks. After your answer, I have checked the general list and realized that already are some of those links, but with different names (TVE 1 is called "La 1", for example). That's why I asked wrong, sorry.
> Anyway, I think only "TVE Canarias" is not already added.
> Also, I suggest adding "La 2" https://rtvelivestream-lvlt.rtve.es/la2_main_dvr_1080.m3u8

Thank you for those valuable suggestions. I'll correct the names if I find differences.

**Comment by ygorlv** [comment]
If you dont mind, I suggest review language and country of them, because I realized that I couldn't find it before because the absence of those informations

**Comment by LaneSh4d0w** [comment]
> 
> 
> Thanks. After your answer, I have checked the general list and realized that already are some of those links, but with different names (TVE 1 is called "La 1", for example). That's why I asked wrong, sorry.
> Anyway, I think only "TVE Canarias" is not already added.
> Also, I suggest adding "La 2" https://rtvelivestream-lvlt.rtve.es/la2_main_dvr_1080.m3u8

https://github.com/iptv-org/iptv/blob/7f5931356d3ba8f31a501750a5f4b04cd41cd50b/channels/es.m3u#L262-L277
