### ISSUE TITLE
Any korean of japanese channel with subtitles please

### ISSUE THREAD

**Issue by kikar92** [iptv-org/iptv#2861]
Hi,

Any one know Korean or japanese channels with arabic or English subtitles please 🥺

Thank you

**Comment by LaneSh4d0w** [comment]
As far as I know, there's one Animax channel that is reportedly having english subtitles, but I think that's all.

**Comment by ygorlv** [comment]
NHK World is mostly in English or subbed and GTN Typhome is EN subbed
