### ISSUE TITLE
Add: Algerians National and private tv 

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#2865]
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/9_picture.png" ,Algeria 1
https://cdn02.hta.dz/abr_htatv/PROGRAMME_NATIONAL/htatv/PROGRAMME_NATIONAL_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/4_picture.png" ,Canal Algérie
https://cdn02.hta.dz/abr_htatv/CANAL_ALGERIE/htatv/CANAL_ALGERIE_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/1_picture.png" ,A3 News
https://cdn02.hta.dz/abr_htatv/A3_HD/htatv/A3_HD_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/124_picture.png" , TV 4 Tamazighth
https://cdn02.hta.dz/abr_htatv/TV_4/htatv/TV_4_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/73_picture.png" ,TV 5 Quran
https://cdn02.hta.dz/abr_htatv/TV_5/htatv/TV_5_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/137_picture.png" ,Algeria 6
https://cdn02.hta.dz/abr_htatv/TV_6_HD/htatv/TV_6_HD_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/138_picture.png" , TV 7 El Maarifa
https://cdn02.hta.dz/abr_htatv/TV7_ELMAARIFA/htatv/TV7_ELMAARIFA_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/141_picture.png" ,TV 8 Edhakira
https://cdn02.hta.dz/abr_htatv/TV8_EDHAKIRA/htatv/TV8_EDHAKIRA_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/126_picture.png" , El Bilad
https://cdn02.hta.dz/abr_htatv/EL_BILAD/htatv/EL_BILAD_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/3_picture.png" ,Beur TV
https://cdn02.hta.dz/abr_htatv/Beur_TV/htatv/Beur_TV_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/6_picture.png" , Echorouk HD
https://cdn02.hta.dz/abr_htatv/Echorouk_TV_HD/htatv/Echorouk_TV_HD_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/7_picture.png" ,El Djazairia
https://cdn02.hta.dz/abr_htatv/EL_DJAZAIRIA_TV/htatv/EL_DJAZAIRIA_TV_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/8_picture.png" ,Ennahar News 
https://cdn02.hta.dz/abr_htatv/ENNAHAR_TV/htatv/ENNAHAR_TV_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/18_picture.png" ,Echorouk News
https://cdn02.hta.dz/abr_htatv/ECHOROUK_NEWS/htatv/ECHOROUK_NEWS_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/123_picture.png" ,Bahia TV Oran
https://cdn02.hta.dz/abr_htatv/Bahia_TV/htatv/Bahia_TV_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/129_picture.png" ,El Hayat
https://cdn02.hta.dz/abr_htatv/EL_HAYAT_TV_ALGERIE/htatv/EL_HAYAT_TV_ALGERIE_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/15_picture.png" ,El Heddaf Sport
https://cdn02.hta.dz/abr_htatv/EL_HEDDAF_TV/htatv/EL_HEDDAF_TV_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/140_picture.png" ,Lina TV
https://cdn02.hta.dz/abr_htatv/Lina_TV/htatv/Lina_TV_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/10_picture.png" ,Samira TV
https://cdn02.hta.dz/abr_htatv/SamiraTV/htatv/SamiraTV_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/132_picture.png" ,EL Aniss
https://cdn02.hta.dz/abr_htatv/El_Fhama_TV/htatv/El_Fhama_TV_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/139_picture.png" ,El Djazair N1
https://cdn02.hta.dz/abr_htatv/El_Djazair_N1/htatv/El_Djazair_N1_720p/chunks.m3u8
#EXTINF:-1  tvg-logo="https://hta.backoffice.easybroadcast.fr/channel/130_picture.png" ,El Fadjr SBA
https://cdn02.hta.dz/abr_htatv/EL_FADJR_TV_DZ/htatv/EL_FADJR_TV_DZ_720p/chunks.m3u8

**Comment by LaneSh4d0w** [comment]
Those channels were already added recently.
