### ISSUE TITLE
TV Pública

### ISSUE THREAD

**Issue by ygorlv** [iptv-org/iptv#2869]
**Channel Name:** TV Pública (TVP)
**Country:** Argentina
**Language:** Spanish
**Links:**
https://www.tvpublica.com.ar/
https://www.youtube.com/channel/UCs231K71Bnu5295_x0MB5Pg
https://www.lyngsat.com/tvchannels/ar/TV-Publica.html
**Notes (optional):**
#EXTINF:-1 tvg-country="AR" tvg-language="Spanish" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/0/0a/Logo_Televisi%C3%B3n_P%C3%BAblica_Argentina.png" group-title="General",TVP
https://cntlnk-main-edge-access.secure.footprint.net/b16/ngrp:c7_vivo01_dai_source-20001_all/c7_vivo01_dai_source-20001_360p.m3u8

**Comment by Sphinxroot** [comment]
https://www.tvpublica.com.ar/vivo
doesnt work  it need the referer to get the stream

kodi only 
https://cntlnk-main-edge-access.secure.footprint.net/b16/ngrp:c7_vivo01_dai_source-20001_all/c7_vivo01_dai_source-20001_1080p.m3u8|Referer=https://vmf.edge-apps.net/embed/live.php?streamname=c7live01-20034&autoplay=true

**Comment by Sphinxroot** [comment]
> @Sphinxroot Please, give me an contributor. #2880 #2839

im only a helper so please  dont ask me(no hard felling) .. its @freearhey  project and he will decide if you are allowed or not ,, and askin everytime wont grant you the access .. my guest .. the more you ask the less you get close to ..

**Comment by freearhey** [comment]
Closed in favor #3064
