### ISSUE TITLE
Add: El Nueve (Argentina)

### ISSUE THREAD

**Issue by ygorlv** [iptv-org/iptv#2870]
**Channel Name:** El Nueve
**Country:** Argentina
**Language:** Spanish
**External Link (optional):** xxx
**Notes (optional):** 
#EXTINF:-1 tvg-country="AR" tvg-language="Spanish" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/3/3a/Canal_9_2015.png" group-title="General",El Nueve
https://ar-elnueve-elnueve-dev-live.ned.media/v1/manifest/0194020089891d5a55b710bf160fa48239104953/ar-elnueve-elnueve/267ad625-97b2-4a34-afa9-0126aa015ee8/2.m3u8?iut=eyJwYXJhbXMiOnsiZXhwIjoxNjIxOTY3NzcyLCJzZXNzaW9uIjoiMTc3LjI3LjI1MS4yNDYiLCJ3aGl0ZWxpc3QiOlsiMTc3LjI3LjI1MS4yNDYiXX0sInNpZ25hdHVyZSI6ImU2OTUwYWI1ZmU1OTI2ZmIwOWZkM2Y4ZjI2YzYwMGM3MDI5NmYxNGMifQ%3D%3D

**Comment by LaneSh4d0w** [comment]
Keep it opened in case we find an alternative.

**Comment by LaneSh4d0w** [comment]
https://iptv-all.lanesh4d0w.repl.co/TESTING/argentina/elnueve

**Comment by freearhey** [comment]
Closed in favor #3064
