### ISSUE TITLE
Add: TV Ciudad (Uruguay)

### ISSUE THREAD

**Issue by ygorlv** [iptv-org/iptv#2871]
**Channel Name:** TV Ciudad
**Country:** Uruguay
**Language:** Spanish
**External Link (optional):** xxx
**Notes (optional):** 
#EXTINF:-1 tvg-country="UY" tvg-language="Spanish" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/f/f6/Tev%C3%A9_Ciudad.svg" group-title="General", TV Ciudad
https://vxlive.cdn.antel.net.uy/auth_livesignal_474,vxttoken=cGF0aFVSST0lMkZhdXRoX2xpdmVzaWduYWxfNDc0JTJGdnhmbXQlM0RobHMlMkYlMkEmZXhwaXJ5PTE2MjE5MDM2ODImcmFuZG9tPVR2V0VTODRTckUmYy1pcD0xNzcuMjcuMjUxLjI0Niw3YzhmODgxODk0YzMxNDkxYTYwZjUxODcyMWRmMmNmYjUzNWQwOWI2ZGE0NWI5YzA0OTMyNjgwOWYzOTQ0OTlh/vxfmt=hls/h_4e87ba91e00e1eff7a40be8574baa630/var3000000/playlist.m3u8

**Comment by heroku-miraheze** [comment]
Geolocked only at Uruguay.

**Comment by heroku-miraheze** [comment]
And also, protected tokens is not allowed.

**Comment by ygorlv** [comment]
Thank you for your answer. I live in Brazil and I could watch it with no problem on VLC yesterday, but since i'm not technician, I cant identify a protected token. Because of that I apologise
