### ISSUE TITLE
Add: Canal 10

### ISSUE THREAD

**Issue by ygorlv** [iptv-org/iptv#2872]
**Channel Name:** Canal 10
**Country:** Uruguay
**Language:** Spanish
**External Link (optional):** xxx
**Notes (optional):** 

#EXTINF:-1 tvg-country="UY" tvg-language="Spanish" tvg-logo="https://i.pinimg.com/originals/66/e9/06/66e906d27abd2a8378e43c95efabce3b.png" group-title="General", Canal 10
https://cdnw3.zetatv.com.uy/live_edge/_definst_/amlst:9/chunklist_w1728915025_b1800000.m3u8?token=4501493f-9f73-4b43-815d-0868fd666895

**Comment by Sphinxroot** [comment]
token stream  and website need a login to view https://www.canal10.com.uy/contenidos/vivo.html  sadly we can`t add it 

ive found this http://www.television-envivo.com/canal-10-uruguay-en-vivo.html  let me know if its the same channel if so it will be added 
https://edge3-hr.cvattv.com.ar/live/c5eds/Canal10_URU/verimatrix_rotating_FTA/Canal10_URU.m3u8
https://edge3-hr.cvattv.com.ar/live/c5eds/Canal10_URU/verimatrix_rotating_FTA/Canal10_URU-video=3000000.m3u8

**Comment by heroku-miraheze** [comment]
If the website requires login, sorry.

**Comment by LaneSh4d0w** [comment]
> 
> 
> token stream and website need a login to view https://www.canal10.com.uy/contenidos/vivo.html sadly we can`t add it
> 
> ive found this http://www.television-envivo.com/canal-10-uruguay-en-vivo.html let me know if its the same channel if so it will be added
> https://edge3-hr.cvattv.com.ar/live/c5eds/Canal10_URU/verimatrix_rotating_FTA/Canal10_URU.m3u8
> https://edge3-hr.cvattv.com.ar/live/c5eds/Canal10_URU/verimatrix_rotating_FTA/Canal10_URU-video=3000000.m3u8

This one works on my side.

**Comment by MapGuy11** [comment]
Streams Work For Me in The US. I would create a pull request. Use this one: 
https://edge3 hr.cvattv.com.ar/live/c5eds/Canal10_URU/verimatrix_rotating_FTA/Canal10_URU.m3u8 not the other.

**Comment by LaneSh4d0w** [comment]
#2908 solves this.
