### ISSUE TITLE
Add: Azteca 7

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#2874]
**Channel Name:** Azteca 7
**Country:** Mexico
**Language:** Spanish
**External Link (optional):** xxx
**Notes (optional):** xxx

**Comment by MapGuy11** [comment]
Azteca 7 From Tijuana: https://streams.the6tv.duckdns.org:2443/locals/SanDiego/xhtit.m3u8

If it works let me know.

**Comment by MapGuy11** [comment]
Added with #2891

**Comment by GiovanniSebastian** [comment]
It works very well, thank you very much.
