### ISSUE TITLE
Add: Unicanal

### ISSUE THREAD

**Issue by ygorlv** [iptv-org/iptv#2875]
**Channel Name:** Unicanal
**Country:** Paraguay
**Language:** Spanish
**External Link (optional):** http://45.55.127.106/live/unicanal_mid.m3u8
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
the channel is already in the playlist  

https://github.com/iptv-org/iptv/blob/master/channels/py.m3u

#EXTINF:-1 tvg-id="Unicanal.py" tvg-name="Unicanal" tvg-country="PY" tvg-language="Spanish" tvg-logo="https://i.imgur.com/cgTD2TW.png" group-title="",Unicanal
http://45.55.127.106/live/unicanal.m3u8

but both link give a black screen  not 24/7 ?
