### ISSUE TITLE
Add: NGT

### ISSUE THREAD

**Issue by ygorlv** [iptv-org/iptv#2884]
**Channel Name:** NGT
**Country:** Brazil
**Language:** Portuguese
**External Link (optional):** xxx
**Notes (optional):**
#EXTINF:-1 tvg-country="BR" tvg-language="Portuguese" tvg-logo="https://upload.wikimedia.org/wikipedia/pt/2/22/Logotipo_da_NGT.png" group-ctitle="General",NGT
https://cdn.jmvstream.com/w/AVJ-9644/playlist/chunklist.m3u8

**Comment by LaneSh4d0w** [comment]
This stream froze.
