### ISSUE TITLE
Add: Canal 1

### ISSUE THREAD

**Issue by jahirfiquitiva** [iptv-org/iptv#2890]
**Channel Name:** Canal 1
**Country:** Colombia
**Language:** Spanish
**External Link (optional):** https://canal1.com.co/senal-en-vivo

**Comment by LaneSh4d0w** [comment]
It's using MDSTRM, let me see if I can get something out of it.

**Comment by LaneSh4d0w** [comment]
Geolocked to Colombia : http://mdstrm.com/video/60886ed32431230884406e36.m3u8

**Comment by ygorlv** [comment]
Atempt from Brazil:

_access error: HTTP 403 error
http error: error: HTTP/1.1 403 Forbidden_

**Comment by jahirfiquitiva** [comment]
@LaneSh4d0w it kinda works but it shows a message saying that the current program cannot be watched via internet ... not sure if it's just the current program or the whole channel

**Comment by Sphinxroot** [comment]
could be token stream il check back later if something change
masterManifest
https://mdstrm.com/live-stream-playlist/5a5e1c2568b1910913db5fe2.m3u8
mediaManifest
https://us-b4-p-e-ft6.cdn.mdstrm.com/live-stream/5a5e1c2568b1910913db5fe2/publish/media_1000.m3u8

**Comment by LaneSh4d0w** [comment]
> 
> 
> could be token stream il check back later if something change
> masterManifest
> https://mdstrm.com/live-stream-playlist/5a5e1c2568b1910913db5fe2.m3u8
> mediaManifest
> https://us-b4-p-e-ft6.cdn.mdstrm.com/live-stream/5a5e1c2568b1910913db5fe2/publish/media_1000.m3u8

MDSTRM streams aren't tokened. the name that looks like a token is basically an identification for MDSTRM's streaming services. Link you provided works for me.

![vlcsnap-2021-05-26-10h09m58s899](https://user-images.githubusercontent.com/30985701/119625512-8da0ad00-be0a-11eb-8a0d-f2eedaa0a0b0.png)

**Comment by Dum4G** [comment]
> https://mdstrm.com/live-stream-playlist/5a5e1c2568b1910913db5fe2.m3u8

I just killed the link by watching it for a few minutes. Now it says
{"status":"ERROR","data":"GEO","message":"You are not allowed to watch this event: Geo Fencing Restriction"}

**Comment by LaneSh4d0w** [comment]
I think they got copyrighted content at a certain moment that they do not want to be shown outside Colombia.

**Comment by LaneSh4d0w** [comment]
> 
> 
> > https://mdstrm.com/live-stream-playlist/5a5e1c2568b1910913db5fe2.m3u8
> 
> I just killed the link by watching it for a few minutes. Now it says
> {"status":"ERROR","data":"GEO","message":"You are not allowed to watch this event: Geo Fencing Restriction"}

It's what I was thinking, they're simply playing between copyrighted content and some other stuff that they can show. Basically news is shown for everyone, and other stuff is between geo-blocked and public show.

**Comment by freearhey** [comment]
Closed in favor #2890
