### ISSUE TITLE
Add: COM Brasil

### ISSUE THREAD

**Issue by ygorlv** [iptv-org/iptv#2892]
**Channel Name:** COM Brasil
**Country:** Brazil
**Language:** Portuguese
**External Link (optional):** xxx
**Notes (optional):** 
#EXTINF:-1 tvg-country="BR" tvg-language="Portuguese" tvg-logo="https://combrasiltv.com.br/wp-content/uploads/2020/02/logo_site.png" group-title="Local",COM Brasil
https://596639ebdd89b.streamlock.net/8032/8032/chunklist_w863088034.m3u8

**Comment by Sphinxroot** [comment]
already in the playlist



#EXTINF:-1 tvg-id="COMBrazilTV.br" tvg-name="COM Brazil TV" tvg-country="BR" tvg-language="" tvg-logo="https://i.imgur.com/azTiRz2.jpg" group-title="",COM Brazil TV (720p)https://596639ebdd89b.streamlock.net/8032/8032/playlist.m3u8
