### ISSUE TITLE
Add: Caracol TV

### ISSUE THREAD

**Issue by jahirfiquitiva** [iptv-org/iptv#2893]
**Channel Name:** Caracol TV
**Country:** Colombia
**Language:** Spanish
**External Link (optional):** https://www.caracoltv.com/senal-vivo

**Comment by Sphinxroot** [comment]
Este contenido no esta disponible. Disfruta de todas las producciones que tenemos en nuestro catálogo de Caracol Play y las noticias de entretenimiento en www.caracoltv.com

**Comment by LaneSh4d0w** [comment]
Geolocked : https://mdstrm.com/live-stream-playlist/574463697b9817cf0886fc17.m3u8

**Comment by LaneSh4d0w** [comment]
An quick implementation using a SOCKS4 proxy : https://iptv-all.lanesh4d0w.repl.co/TESTING/Colombia/CaracolTelevision

**Comment by freearhey** [comment]
Closed in favor #3065
