### ISSUE TITLE
HELP ME : How to play dailymotion stream to Smart IPTV ? 

### ISSUE THREAD

**Issue by Djane** [iptv-org/iptv#2905]
Hello all
Could someone help me run or play the "Dailymotion" stream to SmartIPTV ?

#EXTINF:-1,LMTV
https://www.dailymotion.com/video/x7x1q78
#EXTINF:-1,Christ live Tv
https://www.dailymotion.com/video/x7liq2i

Regards,
Djane-Kate

**Comment by LaneSh4d0w** [comment]
@Sphinxroot Any idea ?

**Comment by LaneSh4d0w** [comment]
Personally, I would try those : 

#EXTINF:-1,LMTV
https://query-streamlink.lanesh4d0w.repl.co/iptv-query?streaming-ip=https://www.dailymotion.com/video/x7x1q78
#EXTINF:-1,Christ live Tv
https://query-streamlink.lanesh4d0w.repl.co/iptv-query?streaming-ip=https://www.dailymotion.com/video/x7liq2i

**Comment by Sphinxroot** [comment]
depend on tv model and app that can be in the store or uploaded to it .. some tv does other don`t ..  if nothing can be added ,  it might be a good idea to plug a device to the tv .. chromecast .. android box , firestick 4k .. mini pc beelink .. anything that have a hdmi port in fact will be ok

**Comment by Dum4G** [comment]
Use Kodi with Dailymotion plugin:
https://kodi.wiki/view/Add-on:DailyMotion.com

Your streams seem to be geoblocked

**Comment by Sphinxroot** [comment]
Both link work for me
Kodi
plugin://plugin.video.dailymotion_com/?url=(VIDEOID)&mode=playLiveVideo

VLC
(DM Link)#tab_embed.m3u8

**Comment by Djane** [comment]
Hello,
It working well. But sometimes it bugs and stopped
Thank you for you support dear @LaneSh4d0w

**Comment by LaneSh4d0w** [comment]
> 
> 
> Hello,
> It working well. But sometimes it bugs and stopped
> Thank you for you support dear @LaneSh4d0w

It might have some difficulties depending on many factors (could be your connection, Dailymotion stability issues or the channel itself), but glad to see that solution works out for you.

**Comment by Aby5us** [comment]
I cant do work this link, u have any idea
https://stream-01.nyc.dailymotion.com/sec(0HE75RGSqqnhnSdEMl12ZS4lwXkWfsYn1POBZD4r3qt47yVqwCv4bnFAaV2aqvlP)/dm/3/x7vyv0z/s/live-3.m3u8
