### ISSUE TITLE
Add: StockCharts TV

### ISSUE THREAD

**Issue by tilfizyawn** [iptv-org/iptv#2909]
```
#EXTINF:-1 tvg-id="" tvg-name=" tvg-country="US" tvg-language="English" tvg-logo="https://d.stockcharts.com/img/scc-logo-light.png" group-title="Business",StockCharts TV
```

https://livestream.com/accounts/19628359/events/7940975/player

@Nintendocustom
@LaneSh4d0w

Are you able to convert this link?

Thanks

**Comment by LaneSh4d0w** [comment]
I'll take care of that soon.

**Comment by LaneSh4d0w** [comment]
https://iptv-all.lanesh4d0w.repl.co/united-states/stockchartstv

**Comment by tilfizyawn** [comment]
Thanks it works! Can you add it please as it doesn't let me edit us.m3u

```
I get this error
3 additions, 1,273 deletions not shown because the diff is too large. Please use a local Git client to view these changes.```
