### ISSUE TITLE
Add: Roya TV (1080p)

### ISSUE THREAD

**Issue by tilfizyawn** [iptv-org/iptv#2910]
Hi, can you please add a higher quality version?

@Nintendocustom 
@LaneSh4d0w 

Thanks

```
#EXTINF:-1 tvg-id="Roya TV ARB" tvg-name="Roya TV ARB" tvg-country="JO" tvg-language="Arabic" tvg-logo="https://i.imgur.com/Sa2nBTP.png" group-title="General",Ro'ya TV (1080p)
```

```
curl -X POST https://roya.tv/api/livestream/ticket


{"data":{"secured_url":"https:\/\/roya-live.ercdn.net\/roya\/roya.m3u8?st=YjmdanxgQX5M7u87ItheHw&e=1622140889"}}
```

**Comment by Dum4G** [comment]
Is that exactly what you want?
https://weyyak-live.akamaized.net/weyyak_roya/index.m3u8

**Comment by tilfizyawn** [comment]
Thanks but that is only 720p

**Comment by LaneSh4d0w** [comment]
Noted. I'll check that out too.

**Comment by LaneSh4d0w** [comment]
Secured link I got gives me 403 Forbidden.

**Comment by LaneSh4d0w** [comment]
If you want to test by yourself : https://iptv-all.lanesh4d0w.repl.co/jordania/royatv

**Comment by tilfizyawn** [comment]
Doesn't work but thanks so much for trying!
