### ISSUE TITLE
Propose: Domain name

### ISSUE THREAD

**Issue by Daniel15** [iptv-org/iptv#2929]
I've got a domain name `iptv.party` that I'm not currently using... Should we use it for this project? Github Pages supports custom domain names.

**Comment by freearhey** [comment]
@Daniel15 I would not want to use any third-party domains, just not to confuse anyone (until at least the domain `iptv.org` is free 😄)

**Comment by LaneSh4d0w** [comment]
> 
> 
> @Daniel15 I would not want to use any third-party domains, just not to confuse anyone (until at least the domain `iptv.org` is free 😄)

iptv.org is taken by PBS haha
