### ISSUE TITLE
Question: I need to become an contributor

### ISSUE THREAD

**Issue by heroku-miraheze** [iptv-org/iptv#2932]
I have contributed much, so, give me please, an contributor, to help with Pull Requests, to merge, etc. @LaneSh4d0w

**Comment by LaneSh4d0w** [comment]
I am not in my rights to add someone here. If everyone thinks you can be added, you will be added. For now, just continue to contribute to this repository and maybe one day you will be one of us.

Spamming demands everytime won't make you have those rights faster. Refrain from doing so.

**Comment by freearhey** [comment]
@heroku-miraheze I've already asked you before not to spam https://github.com/iptv-org/iptv/pull/2839#issuecomment-848095983
