### ISSUE TITLE
Propose: to have Discussions enabled for discussions

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#2934]
pinned posts will no longer be needed and discussions won't dive in between requests
https://docs.github.com/en/discussions/quickstart

**Comment by LaneSh4d0w** [comment]
Interesting idea in fact.

Would make things a lot easier when it comes to long discussions such as this one.

**Comment by freearhey** [comment]
Done.

**Comment by Dum4G** [comment]
I'm not able to create a discussion @freearhey

**Comment by freearhey** [comment]
@Dum4G Try now.

**Comment by Dum4G** [comment]
The button is here. Please turn my issues https://github.com/iptv-org/iptv/issues/2780 https://github.com/iptv-org/iptv/issues/2833 https://github.com/iptv-org/iptv/issues/2732 into discussions, it's a one-click option for collaborators. Thank you

**Comment by LaneSh4d0w** [comment]
Tested for one, does it show for you ?

**Comment by Dum4G** [comment]
Yeah

**Comment by LaneSh4d0w** [comment]
Wonderful. See if you can still react.

@freearhey I was thinking about adding a "Tests" category, referencing links to test before adding them to the playlists. Since we are from all around the world, it can be a powerful way to know if we have geolocked / working (or non-working) links.

**Comment by Dum4G** [comment]
The only thing I can't do is to close my own discussion lol. Everything else is the same, I can edit them

**Comment by LaneSh4d0w** [comment]
Noted. I'll move those issues to discussions.

**Comment by LaneSh4d0w** [comment]
I moved the first three issues onto discussions. I did not move the fourth one since it was a contribution of yours and we do not have any implementation ideas for the moment.

Thanks for your proposal.

**Comment by freearhey** [comment]
@LaneSh4d0w Feel free to tweak the Discussions any way you want.

**Comment by Dum4G** [comment]
> I moved the first three issues onto discussions. I did not move the fourth one since it was a contribution of yours and we do not have any implementation ideas for the moment.

None of my ideas were implemented yet. This contrubution can be used for manual check in case somebody wants to
