### ISSUE TITLE
Cadena TV

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#2947]
**Channel Name:** Cadena TV Huancayo
**Country:** Peru
**Language:** Spanish
**External Link (optional):** https://www.cadenatv.com.pe/en-vivo/
**Notes (optional):** Channel with "strict-origin-when-cross-origin" policy from opencaster.

**Comment by freearhey** [comment]
Closed in favor #3063

**Comment by sguinetti** [comment]
The channel was added in pe.m3u
