### ISSUE TITLE
Auténtica TV

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#2948]
**Channel Name:** Auténtica TV (Tarapoto)
**Country:** Peru
**Language:** Spanish
**External Link (optional):** https://autenticatv.pe/
**Notes (optional):** Channel with "strict-origin-when-cross-origin" policy from opencaster. URL from https://www.opencaster.com/atmosfera-100-100 with m3u file from edge1o.live.opencaster.com.

**Comment by MapGuy11** [comment]
Sorry to say but this channel may be a lost cause.

**Comment by LaneSh4d0w** [comment]
> 
> 
> Sorry to say but this channel may be a lost cause.

I'm not quite sure about that. 2 options are available to us : 

- Either we manage to add the "Referer + Origin" headers with our available things
- If it gets over the stream, either "re-stream" the whole content from the available link we got (which is, i shall admit, a bit borderline in terms of legality)

**Comment by sguinetti** [comment]
For second point it's true, Peru indicates that broadcasting is covered by copyright law for up to 70 years after the transmission has been made.

**Comment by LaneSh4d0w** [comment]
> 
> 
> > If it gets over the stream, either "re-stream" the whole content from the available link we got (which is, i shall admit, a bit borderline in terms of legality)
> 
> For second point it's true, Indecopi indicates that broadcasting is covered by peruvian copyright law for up to 70 years after the transmission has been made.

And Indecopi's quite precise in how companies can stream and how ISPs can get access to re-streaming licensing.

Either way, I hope it's only the 1st case that we'll need.

**Comment by sguinetti** [comment]
This is the website if you are curious (http://www.opencaster.com/directory-0-1) and they have some shared links and that is transmitted on their service.

**Comment by sguinetti** [comment]
There is more info about this topic: https://github.com/streamlink/streamlink/issues/3443

**Comment by LaneSh4d0w** [comment]
Yup, I tried adding header support into my server, but I've got weird errors saying that I couldn't. I'll need to work more on it.

If @Nintendocustom manages to do it, you'll use his host (we got the same base, but different implementations).

**Comment by freearhey** [comment]
Closed in favor #3063

**Comment by sguinetti** [comment]
The channel was added in pe.m3u
