### ISSUE TITLE
Vía Altomayo TV

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#2952]
**Channel Name:** Vía Altomayo
**Country:** Peru
**Language:** Spanish
**External Link (optional):** https://www.viaaltomayotv.com/
**Notes (optional):** Channel with "strict-origin-when-cross-origin" policy from opencaster.

**Comment by LaneSh4d0w** [comment]
Got it working, need some tweaks to make it work correctly.

**Comment by sguinetti** [comment]
Thank you for help me. This is one of the strangest cases I know in this type of broadcasting. Opencaster streams can only be viewed from its iframe and not as a separate link. Anyway, if this proxy? is solved  (I'm not sure how to say it because I'm not an expert in this topic) and add channels like that, would be a breakthrough.

**Comment by freearhey** [comment]
Closed in favor #3063

**Comment by sguinetti** [comment]
The channel was added in pe.m3u
