### ISSUE TITLE
Question: why channels labeled CNN International still streams CNN US edition?

### ISSUE THREAD

**Issue by edgexyz** [iptv-org/iptv#2961]
Streaming urls like these:
`#EXTINF:-1 tvg-id="CNNInternational.us" tvg-name="CNN International" tvg-country="INT" tvg-language="English" tvg-logo="https://i.imgur.com/bD9jUgK.png" group-title="News",CNN International (720p)https://cnn-cnninternational-1-de.samsung.wurl.com/manifest/playlist.m3u8`, `
#EXTINF:-1 tvg-id="CNNInternational.us" tvg-name="CNN International" tvg-country="INT" tvg-language="English" tvg-logo="https://i.imgur.com/2BXCg0x.jpg" group-title="News",CNN International (720p)https://cnn-cnninternational-1-gb.samsung.wurl.com/manifest/playlist.m3u8`, and `
#EXTINF:-1 tvg-id="CNNInternationalHD.us" tvg-name="CNN International HD" tvg-country="US" tvg-language="" tvg-logo="" group-title="",CNN International HDhttps://cnn-cnninternational-1-gb.samsung.wurl.com/manifest/playlist_1280x720_3000k.m3u8`
Although these urls are labeled as CNN International, the content is US edition. ~~Is this the ip I'm using causing the problem?~~ I tried HK, TW, and US ip, and all of those are streaming the US edition

**Comment by LaneSh4d0w** [comment]
I suppose it's due to the fact that they do not have their specific programming over a certain period of time and CNN is just here to give them fillers.

**Comment by themak1985** [comment]
90% of the programming is the same - licensing is the reason the name is different. This is technically Samsung's TV Plus CNN feed for the UK.
