### ISSUE TITLE
Add: Disney channel thailand

### ISSUE THREAD

**Issue by epicmemer6** [iptv-org/iptv#2980]
**Channel Name:** Disney Channel Thailand
**Country:** Thailand
**Language:** Thai, English (some bumpers)
**Notes (optional):** Some IPTV posts might saying it's Disney XD thailand

**Comment by Dum4G** [comment]
https://www.livedoomovies.com/02_DisneyXD_720p/chunklist.m3u8

Does it work to you?

**Comment by MapGuy11** [comment]
2nd and 3rd work for me in the US.

**Comment by MapGuy11** [comment]
This isn't a US Channel it just works in the US. This is a Thailand version.

**Comment by epicmemer6** [comment]
The 1st stream is geoblocked (the reason I want the Thai feed is because I speak Thai as my native language)

**Comment by epicmemer6** [comment]
And the 3rd stream is asia

**Comment by Dum4G** [comment]
> And the 3rd stream is asia

Is that what you asked for?

**Comment by epicmemer6** [comment]
> > And the 3rd stream is asia
> 
> Is that what you asked for?

I wanted the Thai subfeed but I'd say you should add there's stream as well (but I am still hunting for the Thai)

**Comment by freearhey** [comment]
@MapGuy11 The thing is that the label is added to make it clear in which file you will need to add the channel, and since Disney is an American channel, it is `us.m3u`. The fact that the channel is for Thailand can be noted with the `tvg-country` attribute.

**Comment by freearhey** [comment]
Closed in favor #1942

**Comment by rupesh25358a** [comment]
Disney Channel Asia 
http://198.16.106.62:8278/streams/d/Disneyxd/playlist.m3u8
Disney Junior
http://198.16.106.62:8278/streams/d/Disneyjr/playlist.m3u8

**Comment by freearhey** [comment]
@rupesh25358a Added via #4512
