### ISSUE TITLE
i24NEWS Arabic

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#2986]
CAN ANY ONE EXTRACT THE M3U8 LINK OF THIS LIVE STREAM 
https://www.i24news.tv/ar/%D9%85%D8%A8%D8%A7%D8%B4%D8%B1

**Comment by LaneSh4d0w** [comment]
Making a PR for this one, needs some additional things to make it work flawlessly.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/198d0527f073c81119ccceaebdede8e79f542028/streams/il.m3u#L14-L15
