### ISSUE TITLE
French Polynesia Request Channels

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#2988]
List of requests for French Polynesia channels from other issues:

- [x] [TNTV](https://www.tntv.pf/direct/) (https://github.com/iptv-org/iptv/issues/1939#issuecomment-851803404) (added via #3896)

If you find a working link to a channel from the list you can add it directly to the playlist by making a pull request, just read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#add-or-replace-a-stream) before you do it.

**Comment by Sphinxroot** [comment]
Not 24/7 sadly 

TNTV has web broadcasting rights only for local broadcasts. We are sorry that we cannot broadcast international programs at this time. Your 100% fenua programs are available every day from 5 p.m. to 7 p.m.

**Comment by hemzaberkane** [comment]
i found this url working for me 
https://bcovlive-a.akamaihd.net/304fe71ee59a4d9692c5fa03548aa91a/us-west-2/5816339219001/profile_0/chunklist.m3u8

**Comment by Sphinxroot** [comment]
# https://www.tntv.pf/direct/
Stream  at 5 p.m. to 7 p.m.  French Polynesia is  UTC -10:00 

#EXTINF:-1 tvg-id="TNTV.pf" tvg-name="TNTV" tvg-country="PF" tvg-language="French" tvg-logo="https://i.imgur.com/NzDscwm.png" group-title="General",TNTV (720p) [Not 24/7]
https://bcovlive-a.akamaihd.net/304fe71ee59a4d9692c5fa03548aa91a/us-west-2/5816339219001/playlist.m3u8


#EXT-X-STREAM-INF:BANDWIDTH=2654208,CODECS="avc1.100.41,mp4a.40.2",RESOLUTION=1280x720
profile_0/chunklist.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1937408,CODECS="avc1.77.41,mp4a.40.2",RESOLUTION=960x540
profile_1/chunklist.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1118208,CODECS="avc1.77.31,mp4a.40.2",RESOLUTION=640x360
profile_2/chunklist.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=657408,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=480x270
profile_3/chunklist.m3u8
