### ISSUE TITLE
VZTV

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#2991]
**Channel Name:** VZTV
**Channel ID:** VZTV.pe
**Country:** Peru
**Language:** Spanish
**External Link (optional):** https://moyobamba.com/vztv/
**Notes (optional):** Not 24/7. Channel with "strict-origin-when-cross-origin" policy from opencaster. Iframe link: https://www.opencaster.com/abelhoyos3-100-100.

**Comment by freearhey** [comment]
Closed in favor #3063

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/cac2f96962f43fcec08d835b0878ed36307d4bbe/streams/pe.m3u#L330-L331
