### ISSUE TITLE
Add: Cartoon Network Thailand

### ISSUE THREAD

**Issue by epicmemer6** [iptv-org/iptv#2997]
**Channel Name:** Cartoon Network Thailand
**Country:** Thailand
**Language:** Thai
**External Link (optional):
**Notes (optional):** It's the Asian feed but thai

**Comment by freearhey** [comment]
@MapGuy11 "Cartoon Network Asia" is US channel according to this: https://www.lyngsat.com/tvchannels/us/Cartoon-Network-Asia.html

**Comment by freearhey** [comment]
Closed in favor #1942

**Comment by Dum4G** [comment]
@epicmemer6 https://htv-drm-live-cdn.fptplay.net/CDN-FPT02/CARTOON-SD-720p/playlist.m3u8

What language is this?

**Comment by Dum4G** [comment]
@epicmemer6 does it work for you?
http://160.119.77.117/iptv/sd-cartoonnetwork.stream/chunks.m3u8

**Comment by rupesh25358a** [comment]
http://198.16.106.62:8278/streams/d/Cn/playlist.m3u8
Cartoon network asia

**Comment by freearhey** [comment]
@rupesh25358a Added via #4512
