### ISSUE TITLE
Add: channel 9 israel 

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#3011]
please can you add this channel 
http://tv.ontivi.net/9-kanal-izrailtv.html

**Comment by Dum4G** [comment]
http://87.248.180.89:81/9/tracks-v1a1/mono.m3u8

**Comment by LaneSh4d0w** [comment]
Might get it with a little bit of tweaking : http://tv.ontivi.net/open?kes=e484fba1d68659963048def1cb0a36efFF185

**Comment by ipstreet312** [comment]
Hello @freearhey @hemzaberkane and All, please find below fresh complete list for Israeli channels (Arutz 20 & Keshet 12 alternative stable links especially with good logo size and formats) , regards 

#EXTINF:0 tvg-logo="https://i.ibb.co/fMMBKqc/kan11.png" group-title="|IL| ISRAEL",KAN 11
https://kan11.media.kan.org.il/hls/live/2024514/2024514/master.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/qBKNrv5/keshet.png" group-title="|IL| ISRAEL",KESHET 12
https://keshethlslive-lh.akamaihd.net/i/CH12CC_1@732426/index_2200_av.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/6PPHnBS/13.png" group-title="|IL| ISRAEL",RESHET 13
https://d18b0e6mopany4.cloudfront.net/out/v1/08bc71cf0a0f4712b6b03c732b0e6d25/index.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/vc6zbq4/20tvp.png" group-title="|IL| ISRAEL",ARUTZ 20
https://dvr.ch20-cdnwiz.com/hls/live_720/index.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/0cGcHCD/23.jpg" group-title="|IL| ISRAEL",HINUCHIT 23
https://kanlivep2event-i.akamaihd.net/hls/live/747600/747600/playlist.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/0VW9cqL/24.jpg" group-title="|IL| ISRAEL",MAKO 24
https://keshethlslive-lh.akamaihd.net/i/24live_1@195271/index_2200_av-b.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/1rSGfFw/N12n.png" group-title="|IL| ISRAEL",NEWS 12 Main - Nightly
http://keshethlslive-lh.akamaihd.net/i/c2n_1@195269/master.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/1rSGfFw/N12n.png" group-title="|IL| ISRAEL",NEWS 12 Feed - Events
http://keshethlslive-lh.akamaihd.net/i/c2nsec_1@195268/master.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/zP5vjLD/knesset.png" group-title="|IL| ISRAEL",HAKNESSET 99
https://contact.gostreaming.tv/Knesset/myStream/playlist.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/fMMBKqc/kan11.png" group-title="|IL| ISRAEL",KAN 11 (backup)
https://kanlivep2event-i.akamaihd.net/hls/live/747610/747610/master.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/qBKNrv5/keshet.png" group-title="|IL| ISRAEL",KESHET 12 (backup)
https://iptv--iptv.repl.co/Hebrew/keshet_12?m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/6PPHnBS/13.png" group-title="|IL| ISRAEL",RESHET 13 (backup)
https://d2xg1g9o5vns8m.cloudfront.net/out/v1/0855d703f7d5436fae6a9c7ce8ca5075/index.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/vc6zbq4/20tvp.png" group-title="|IL| ISRAEL",ARUTZ 20 (backup)
https://iptv.x-cloud.info:1443/Channel20/tracks-v1a1/mono.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/kq4XM0Y/ynet.png" group-title="|IL| ISRAEL",Y-NET NEWS
http://ynet-lh.akamaihd.net/i/ynet_1@123290/master.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/jzRyjBn/walla.png" group-title="|IL| ISRAEL",WALLA NEWS
https://live.wcdn.co.il/news/prog_index.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/2g7Sw4c/21.jpg" group-title="|IL| ISRAEL",SHOPPING 21
https://shoppingil-rewriter.vidnt.com/index.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/bJVPhHD/hidabroot.png" group-title="|IL| ISRAEL",HIDABROOT 97
https://stream71.shidur.net/htvlive2/_definst_/smil:live2.smil/chunklist.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/93bQz4t/kabalah.png" group-title="|IL| ISRAEL",KABBALAH 96
https://edge3.uk.kab.tv/live/tv66-heb-high/playlist.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/qBPwnB7/Arutz9.png" group-title="|IL| ISRAEL",ARUTZ 9 CH
http://87.248.180.89:81/9/tracks-v1a1/mono.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/qBPwnB7/Arutz9.png" group-title="|IL| ISRAEL",ARUTZ 9 CH (backup)
http://50.7.231.221:8081/185/index.m3u8?wmsAuthSign=okad
#EXTINF:0 tvg-logo="https://i.ibb.co/MG43H4H/hala.png" group-title="|IL| ISRAEL",PANET 30 HALA
http://gstream4.panet.co.il/edge_abr/halaTV/edge/halaTV/playlist.m3u8
#EXTINF:0 tvg-logo="https://i.ibb.co/fqTYrGY/33.png" group-title="|IL| ISRAEL",KAN 33 MAKAN
https://kanlivep2event-i.akamaihd.net/hls/live/747613/747613/master.m3u8

**Comment by freearhey** [comment]
@ipstreet312 Feel free to add links to the playlist yourself, just read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#add-or-replace-a-stream) before doing so.

**Comment by ipstreet312** [comment]
> @ipstreet312 Feel free to add links to the playlist yourself, just read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#add-or-replace-a-stream) before doing so.

thank you, changes done all the best i can. regards
