### ISSUE TITLE
Add: List of IRIB Channels

### ISSUE THREAD

**Issue by darkreaperboy** [iptv-org/iptv#3048]
**Country:** Iran
**Language:** Persian
**External Link (optional):** http://185.236.230.222:8000/playlist.m3u8
**Notes (optional):** List of persian channels

**Comment by LaneSh4d0w** [comment]
You forgot to add the channel name. The list isn't complete. Please make a complete issue.

**Comment by Dum4G** [comment]
This is an entire playlist of channels

**Comment by LaneSh4d0w** [comment]
Had ran into some sort of issue, reopening it.

**Comment by LaneSh4d0w** [comment]
It seems it's an... ASTRA Panel ?

**Comment by LaneSh4d0w** [comment]
Funny enough, those are IRIB-maintained satellite streams you had on this playlist.

All channels are signed by editor IRIB... I'm starting to think if it was, by any chance, badly secured Astra Satellite hosting servers...

**Comment by themak1985** [comment]
#3052
