### ISSUE TITLE
RTM TV 6

### ISSUE THREAD

**Issue by Kyzer85** [iptv-org/iptv#3054]
**Channel Name:** TV6
**Country:** Malaysia
**Language:** Malay
**External Link (optional):** https://rtmklik.rtm.gov.my/tv/6

**Comment by Sphinxroot** [comment]
Referer is required

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="" tvg-language="" tvg-logo="https://i.imgur.com/za2Uj4W.jpg" group-title="",TV6
https://rtm6.secureswiftcontent.com/Origin03/ngrp:RTM3/playlist.m3u8|Referer=https://rtmklik.rtm.gov.my/tv/6
#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="" tvg-language="" tvg-logo="https://i.imgur.com/za2Uj4W.jpg" group-title="",TV6 (1080p)
https://rtm6.secureswiftcontent.com/Origin03/ngrp:RTM3/chunklist_b4064000.m3u8|Referer=https://rtmklik.rtm.gov.my/tv/6
#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="" tvg-language="" tvg-logo="https://i.imgur.com/za2Uj4W.jpg" group-title="",TV6 (720p)
https://rtm6.secureswiftcontent.com/Origin03/ngrp:RTM3/chunklist_b2164000.m3u8|Referer=https://rtmklik.rtm.gov.my/tv/6

**Comment by freearhey** [comment]
@Sphinxroot You don't have to post links to channels here, you can add them directly to the playlist via pull request and just include a link to this issue in the description.

**Comment by freearhey** [comment]
Closed in favor #1982

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/198d0527f073c81119ccceaebdede8e79f542028/streams/my.m3u#L34-L35
