### ISSUE TITLE
Add: POP, Pop Max and Tiny Pop

### ISSUE THREAD

**Issue by SussyXD** [iptv-org/iptv#3062]
**Channel Name:** POP, Pop Max, Tiny Pop
**Country:** UK
**Language:** English
**External Link (optional):** xxx
**Notes (optional):** It is a free to air UK kids channel

**Comment by freearhey** [comment]
More than one channel in the request.

**Comment by SussyXD** [comment]
what does that mean?

**Comment by freearhey** [comment]
Here is a more accurate definition: https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel
