### ISSUE TITLE
Argentine Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#3064]
List of requests for Argentine channels from other issues:

- [x] El Nueve (#2870) Added With (#4044)
- [ ] [TVP](https://www.tvpublica.com.ar/) (#2869)

If you find a working link to a channel from the list you can add it directly to the playlist by making a pull request, just read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#add-or-replace-a-stream) before you do it.

**Comment by fotvnetwork** [comment]
El Nueve: 
https://www.elnueve.com.ar/en-vivo/
https://ar-elnueve-elnueve-live.ned.media/live.m3u8?iut=eyJwYXJhbXMiOnsiZXhwIjoxNjI1MzI0Nzk0LCJzZXNzaW9uIjoiMTAzLjEzNy4yMDYuMjM4Iiwid2hpdGVsaXN0IjpbIjEwMy4xMzcuMjA2LjIzOCJdfSwic2lnbmF0dXJlIjoiNzI0MGQ0ZDlkNjI5M2JkNTFjMjc0YmQ3OGQ3YzkyN2VkNDVmM2NlZiJ9

**Comment by MapGuy11** [comment]
@LaneSh4d0w this is working currently and it doesn't seem the token generation url has died yet: 
https://cdn88.theus6tv.tk/argentina/broadcast/el-nueve.m3u8

app.get("/argentina/broadcast/el-nueve.m3u8", function(req,res) {
    fetch("https://past-server.nedp.io/token/ar-elnueve-elnueve?rsk=18ec30e26053b2ca5a57f61afadb519f47c0d263")
        .then(response => response.json())
        .then(json => {
            res.setHeader('Content-Type', 'application/vnd.apple.mpegurl')
            res.redirect('https://ar-elnueve-elnueve-live.ned.media/live.m3u8?iut=' + json.token)
        })
});

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w this is working currently and it doesn't seem the token generation url has died yet: 
> https://cdn88.theus6tv.tk/argentina/broadcast/el-nueve.m3u8
> 
> app.get("/argentina/broadcast/el-nueve.m3u8", function(req,res) {
>     fetch("https://past-server.nedp.io/token/ar-elnueve-elnueve?rsk=18ec30e26053b2ca5a57f61afadb519f47c0d263")
>         .then(response => response.json())
>         .then(json => {
>             res.setHeader('Content-Type', 'application/vnd.apple.mpegurl')
>             res.redirect('https://ar-elnueve-elnueve-live.ned.media/live.m3u8?iut=' + json.token)
>         })
> });

Nice, thought that the RSK token would go.

**Comment by MapGuy11** [comment]
> > @LaneSh4d0w this is working currently and it doesn't seem the token generation url has died yet:
> > https://cdn88.theus6tv.tk/argentina/broadcast/el-nueve.m3u8
> > app.get("/argentina/broadcast/el-nueve.m3u8", function(req,res) {
> > fetch("https://past-server.nedp.io/token/ar-elnueve-elnueve?rsk=18ec30e26053b2ca5a57f61afadb519f47c0d263")
> > .then(response => response.json())
> > .then(json => {
> > res.setHeader('Content-Type', 'application/vnd.apple.mpegurl')
> > res.redirect('https://ar-elnueve-elnueve-live.ned.media/live.m3u8?iut=' + json.token)
> > })
> > });
> 
> Nice, thought that the RSK token would go.

Only tested it for like 10mins ,but I now with FOX in the states it's dead in 2mins.

**Comment by MapGuy11** [comment]
Removed the comment so the token doesn't go away making PR now.

**Comment by Toei79** [comment]
tvp have a youtube live

**Comment by LaneSh4d0w** [comment]
https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/user/TVPublicaArgentina/live

**Comment by LaneSh4d0w** [comment]
The other one is like America : https://vmf.edge-apps.net/embed/live.php?streamname=c7live01-20034&autoplay=true

Weird to get.

**Comment by Toei79** [comment]
that thing its good , herokuapp let use streamling online?

**Comment by LaneSh4d0w** [comment]
Yep, almost everything streamlink can decrypt can be used using the service above. If there's some issues, I can take care of those, since I host it.

There's an alternative that's in maintenance now, hoping it'll get back soon.

**Comment by freearhey** [comment]
Closed in favor #2869

**Comment by LaneSh4d0w** [comment]
El Nueve (in case of) : https://cdn.cvattv.com.ar/live/c3eds/Canal9/SA_Live_dash_enc_2A/Canal9.mpd
