### ISSUE TITLE
Add: xxx

### ISSUE THREAD

**Issue by kelo0003** [iptv-org/iptv#3066]
**Channel Name:** Channel 5 Mediacorp
**Country:** Singapore
**Language:** English
**External Link (optional):** xxx
**Notes (optional):** would like to see this mediacorp Channel

**Channel Name:** Channel 8 Mediacorp
**Country:** Singapore
**Language:** English
**External Link (optional):** xxx
**Notes (optional):** would like to see this mediacorp Channel

**Channel Name:** Channel U Mediacorp
**Country:** Singapore
**Language:** English
**External Link (optional):** xxx
**Notes (optional):** would like to see this mediacorp Channel

**Channel Name:** Channel Vasantham Mediacorp
**Country:** Singapore
**Language:** English
**External Link (optional):** xxx
**Notes (optional):** would like to see this mediacorp Channel

**Channel Name:** Channel Suria Mediacorp
**Country:** Singapore
**Language:** English
**External Link (optional):** xxx
**Notes (optional):** would like to see this mediacorp Channel

**Comment by freearhey** [comment]
More than one channel in the request.

**Comment by kelo0003** [comment]
Hi there sorry about that, I just discovered this and wasn’t sure if it was possible. Mainly mediacorp channel 5 I would like to see.

Sent from my iPhone XR

On 7 Jun 2021, at 11:44 PM, Aleksandr Statciuk ***@***.***> wrote:

﻿

More than one channel in the request.
