### ISSUE TITLE
Fix: Celestial Movies

### ISSUE THREAD

**Issue by kelo0003** [iptv-org/iptv#3067]
**_Channel Name:_** Celestial Movies
**_Broken Link (from playlist):_** http://50.7.161.82:8278/streams/d/Celestial/playlist.m3u8
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** Not working doesn’t load

**Comment by freearhey** [comment]
I don't see that link in any of the playlists. Could you point out the specific file in which you found it?

**Comment by kelo0003** [comment]
Under the Malaysia Category and in Movies section. Also HBO plays in Malaysia section but audio only no video.



Sent from my iPhone XR

On 7 Jun 2021, at 11:45 PM, Aleksandr Statciuk ***@***.***> wrote:

﻿

I don't see that link in any of the playlists. Could you point out the specific file in which you found it?

**Comment by freearhey** [comment]
In the Malaysian playlist I see only one link to the Celestial Movies channel and it works fine:
![image](https://user-images.githubusercontent.com/7253922/121034000-57bdda00-c7b5-11eb-8d3f-6f7fc096e6c3.png)

**Comment by kelo0003** [comment]
Okay, I will check it out again. In regards to the HBO channel in the malaysia section as well, why is it only playing audio, and no video?

Sent from my iPhone XR

On 7 Jun 2021, at 11:57 PM, Aleksandr Statciuk ***@***.***> wrote:

﻿

In the Malaysian playlist I see only one link to the Celestial Movies channel and it works fine:
[image]<https://user-images.githubusercontent.com/7253922/121034000-57bdda00-c7b5-11eb-8d3f-6f7fc096e6c3.png>

**Comment by freearhey** [comment]
It works fine for me
![image](https://user-images.githubusercontent.com/7253922/121035535-a6b83f00-c7b6-11eb-8eed-c0c543ab8e64.png)

**Comment by kelo0003** [comment]
Are you able to send the link?


Sent from my iPhone XR

On 8 Jun 2021, at 12:05 AM, Aleksandr Statciuk ***@***.***> wrote:

﻿

It works fine for me
[image]<https://user-images.githubusercontent.com/7253922/121035535-a6b83f00-c7b6-11eb-8eed-c0c543ab8e64.png>

**Comment by freearhey** [comment]
I used the link from the Malaysian playlist `https://iptv-org.github.io/iptv/countries/my.m3u`
