### ISSUE TITLE
Pop

### ISSUE THREAD

**Issue by SussyXD** [iptv-org/iptv#3076]
**Channel Name: POP
**Channel ID: Pop.uk
**Country: UK
**Language: English
**External Link (optional):
**Notes (optional): Free to air UK channel

**Comment by freearhey** [comment]
Closed in favor #1943

**Comment by UltraHDR** [comment]
http://hybridtv.ss7.tv/whitelabel/index.html?env=prd&platform=fvp&cid=sonykids&platformenv=prd&service=freeviewplay

**Comment by freearhey** [comment]
Closed in favor of #12292
