### ISSUE TITLE
Add: Loop Flashback

### ISSUE THREAD

**Issue by ygorlv** [iptv-org/iptv#3103]
**Channel Name:** Loop Flashback
**Country:** Unknown
**Language:** English
**External Link (optional):**
**Notes (optional):** 
#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="" tvg-language="English" tvg-logo="" group-title="Music",Loop Flashback
https://7b65d9c562ad41b4b6efeaf1f598093d.mediatailor.us-west-2.amazonaws.com/v1/manifest/6b8beeb9ed833d048c8c8155a25a28fe617c5474/like_yesterday_plex/fb3b0c92-916b-47c6-9ab4-1a69e525501f/5.m3u8

**Comment by Dum4G** [comment]
{"message":"Invalid sessionId [fb3b0c92-916b-47c6-9ab4-1a69e525501f]"}

**Comment by ygorlv** [comment]
It seems to be a tokened link :(
Today's link is https://7b65d9c562ad41b4b6efeaf1f598093d.mediatailor.us-west-2.amazonaws.com/v1/manifest/6b8beeb9ed833d048c8c8155a25a28fe617c5474/like_yesterday_plex/2185e1c9-feac-49f5-915a-a9dcb7847435/5.m3u8
I would like to add Plex channels available at https://app.plex.tv/desktop

**Comment by Dum4G** [comment]
Doesn't open in VLC. Obviously, we need a link to a source where you find those, so we could consider something

**Comment by ygorlv** [comment]
I found it at https://app.plex.tv/desktop

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-logo="https://static.12core.net/a3dab2ebc27b678fbdbaedc395cd2305.jpeg" group-title="Rad TV",Loop 80s
https://a500d902bdf94ea69ad343720add6036.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/80s_party_littlstar/master.m3u8

#EXTINF:-1 tvg-logo="https://static.12core.net/82523e6369472b5836a8b4c0a37e83cf.jpeg" group-title="Rad TV",Loop 90s
https://7626362bfa104137aded60d8d7e72ff5.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/90s_kids_littlstar/master.m3u8

#EXTINF:-1 tvg-logo="https://static.12core.net/fb8c7ba652305a8700924347d46dcdff.jpeg" group-title="Rad TV",Loop Beast
https://884a4c762d524aad88d463477402fb7d.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/beast_mode_littlstar/master.m3u8

#EXTINF:-1 tvg-logo="https://static.12core.net/2a347a69ef251082e125c7b15fc721a9.jpeg" group-title="Rad TV",Loop Bedroom
https://3bbe22c035b4409d80f997adc8ad33ee.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/bedroom_beats_littlstar/master.m3u8

#EXTINF:-1 tvg-logo="https://static.12core.net/d8d1f2a3ea03ed135a7873ff7c0ce161.jpeg" group-title="Rad TV",Loop Electronica
https://0bdf3efc906045538c63468aa2f86a96.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/electro_anthems_littlstar/master.m3u8

#EXTINF:-1 tvg-logo="https://static.12core.net/66b982a91d8b8f8383420675781139a1.jpeg" group-title="Rad TV",Loop Far Out
https://957d71ce01dc447384d3978d3cdc55d9.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/that_70s_channel_littlstar/master.m3u8

#EXTINF:-1 tvg-logo="https://static.12core.net/52a174e6787a4ade949c6f5903777cff.jpeg" group-title="Rad TV",Loop Flashback
https://ea86081fb9454be9b3b50037f9117024.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/like_yesterday_littlstar/master.m3u8

#EXTINF:-1 tvg-logo="https://static.12core.net/f6ec7f3aa3a5f36aa8fda7af47c56fdd.jpeg" group-title="Rad TV",Loop Hip Hop
https://e4d2547e0c8c492a883054acd48276be.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/hip_hop_bangers_littlstar/master.m3u8

#EXTINF:-1 tvg-logo="https://static.12core.net/6690e0eea179338fa1b79e01342a6cb8.jpeg" group-title="Rad TV",Loop Hottest
https://2e9a0ef101a14c2ebe97c713bc5340be.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/hottest_of_the_hot_v2_littlstar/master.m3u8

#EXTINF:-1 tvg-logo="https://static.12core.net/20b46f1a2777723aaa45db27e7389a93.jpeg" group-title="Rad TV",Latin x Loop
https://c3b9df023def467086d10677827171f8.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/latin_x_pop_littlstar/master.m3u8

#EXTINF:-1 tvg-logo="https://static.12core.net/2807d4ad6af0c5906229e9217fa631a2.jpeg" group-title="Rad TV",Loop Party
https://1d79349342334eb0bdeddd168b5c6e1a.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/party_littlstar/master.m3u8

#EXTINF:-1 tvg-logo="https://static.12core.net/6edcf875ec3ba823acec994ffd051633.jpeg" group-title="Rad TV",Loop R&amp;B
https://0cf4f660964046daa9e0b7b6467a4e84.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/hot_rnb_littlstar/master.m3u8

#EXTINF:-1 tvg-logo="https://static.12core.net/e21e0005af106ee7bebea46bb17b2e93.jpeg" group-title="Rad TV",Loop Synapse
https://2807722353b745629456a555257b16bc.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/neural_focused_littlstar/master.m3u8

#EXTINF:-1 tvg-logo="https://static.12core.net/c7c4962a327ba3a25ae0dcf17a3d4e06.jpeg" group-title="Rad TV",Loop Texas Tunes
https://2fb88e730c2647d69629c6f90b0b98b9.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/texas_sized_hits_littlstar/master.m3u8

#EXTINF:-1 tvg-logo="https://static.12core.net/2487e997c51436f8502ac737144954a7.jpeg" group-title="Rad TV",Loop TGIF
https://480e67fe68b64c35ae48b77192cb1fdf.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/friday_feels_littlstar/master.m3u8

#EXTINF:-1 tvg-logo="https://static.12core.net/5e4e6c6989bea49734411e5e708f6089.jpeg" group-title="Rad TV",Loop That's Hot
https://dccd6216f2c9471399015e69d64818cd.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/thats_hot_littlstar/master.m3u8

#EXTINF:-1 tvg-logo="https://static.12core.net/0c789462f6e85086d20ccc04da342567.jpeg" group-title="Rad TV",Loop Trending
https://3d26c463850c48c788975a9aad86c508.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/trending_littlstar/master.m3u8

#EXTINF:-1 tvg-logo="https://static.12core.net/63d5db69985110f57bd35c4cd22ee74a.jpeg" group-title="Rad TV",Loop Unwind
https://8c455e94c5ff44d0ada529dffef58ae5.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/unwind_littlstar/master.m3u8

#EXTINF:-1 tvg-logo="https://static.12core.net/43a4136e6bc3e153f68bb2dd200a6635.jpeg" group-title="Rad TV",Loop Yacht Rock
https://90a0d12cbaff4b959ea24bb8a3560adf.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/yacht_rock_littlstar/master.m3u8

**Comment by LaneSh4d0w** [comment]
>  #EXTINF:-1 tvg-logo="https://static.12core.net/a3dab2ebc27b678fbdbaedc395cd2305.jpeg" group-title="Rad TV",Loop 80s
> 
> https://a500d902bdf94ea69ad343720add6036.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/80s_party_littlstar/master.m3u8
> 
> #EXTINF:-1 tvg-logo="https://static.12core.net/82523e6369472b5836a8b4c0a37e83cf.jpeg" group-title="Rad TV",Loop 90s
> https://7626362bfa104137aded60d8d7e72ff5.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/90s_kids_littlstar/master.m3u8
> 
> #EXTINF:-1 tvg-logo="https://static.12core.net/fb8c7ba652305a8700924347d46dcdff.jpeg" group-title="Rad TV",Loop Beast
> https://884a4c762d524aad88d463477402fb7d.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/beast_mode_littlstar/master.m3u8
> 
> #EXTINF:-1 tvg-logo="https://static.12core.net/2a347a69ef251082e125c7b15fc721a9.jpeg" group-title="Rad TV",Loop Bedroom
> https://3bbe22c035b4409d80f997adc8ad33ee.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/bedroom_beats_littlstar/master.m3u8
> 
> #EXTINF:-1 tvg-logo="https://static.12core.net/d8d1f2a3ea03ed135a7873ff7c0ce161.jpeg" group-title="Rad TV",Loop Electronica
> https://0bdf3efc906045538c63468aa2f86a96.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/electro_anthems_littlstar/master.m3u8
> 
> #EXTINF:-1 tvg-logo="https://static.12core.net/66b982a91d8b8f8383420675781139a1.jpeg" group-title="Rad TV",Loop Far Out
> https://957d71ce01dc447384d3978d3cdc55d9.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/that_70s_channel_littlstar/master.m3u8
> 
> #EXTINF:-1 tvg-logo="https://static.12core.net/52a174e6787a4ade949c6f5903777cff.jpeg" group-title="Rad TV",Loop Flashback
> https://ea86081fb9454be9b3b50037f9117024.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/like_yesterday_littlstar/master.m3u8
> 
> #EXTINF:-1 tvg-logo="https://static.12core.net/f6ec7f3aa3a5f36aa8fda7af47c56fdd.jpeg" group-title="Rad TV",Loop Hip Hop
> https://e4d2547e0c8c492a883054acd48276be.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/hip_hop_bangers_littlstar/master.m3u8
> 
> #EXTINF:-1 tvg-logo="https://static.12core.net/6690e0eea179338fa1b79e01342a6cb8.jpeg" group-title="Rad TV",Loop Hottest
> https://2e9a0ef101a14c2ebe97c713bc5340be.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/hottest_of_the_hot_v2_littlstar/master.m3u8
> 
> #EXTINF:-1 tvg-logo="https://static.12core.net/20b46f1a2777723aaa45db27e7389a93.jpeg" group-title="Rad TV",Latin x Loop
> https://c3b9df023def467086d10677827171f8.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/latin_x_pop_littlstar/master.m3u8
> 
> #EXTINF:-1 tvg-logo="https://static.12core.net/2807d4ad6af0c5906229e9217fa631a2.jpeg" group-title="Rad TV",Loop Party
> https://1d79349342334eb0bdeddd168b5c6e1a.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/party_littlstar/master.m3u8
> 
> #EXTINF:-1 tvg-logo="https://static.12core.net/6edcf875ec3ba823acec994ffd051633.jpeg" group-title="Rad TV",Loop R&B
> https://0cf4f660964046daa9e0b7b6467a4e84.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/hot_rnb_littlstar/master.m3u8
> 
> #EXTINF:-1 tvg-logo="https://static.12core.net/e21e0005af106ee7bebea46bb17b2e93.jpeg" group-title="Rad TV",Loop Synapse
> https://2807722353b745629456a555257b16bc.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/neural_focused_littlstar/master.m3u8
> 
> #EXTINF:-1 tvg-logo="https://static.12core.net/c7c4962a327ba3a25ae0dcf17a3d4e06.jpeg" group-title="Rad TV",Loop Texas Tunes
> https://2fb88e730c2647d69629c6f90b0b98b9.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/texas_sized_hits_littlstar/master.m3u8
> 
> #EXTINF:-1 tvg-logo="https://static.12core.net/2487e997c51436f8502ac737144954a7.jpeg" group-title="Rad TV",Loop TGIF
> https://480e67fe68b64c35ae48b77192cb1fdf.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/friday_feels_littlstar/master.m3u8
> 
> #EXTINF:-1 tvg-logo="https://static.12core.net/5e4e6c6989bea49734411e5e708f6089.jpeg" group-title="Rad TV",Loop That's Hot
> https://dccd6216f2c9471399015e69d64818cd.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/thats_hot_littlstar/master.m3u8
> 
> #EXTINF:-1 tvg-logo="https://static.12core.net/0c789462f6e85086d20ccc04da342567.jpeg" group-title="Rad TV",Loop Trending
> https://3d26c463850c48c788975a9aad86c508.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/trending_littlstar/master.m3u8
> 
> #EXTINF:-1 tvg-logo="https://static.12core.net/63d5db69985110f57bd35c4cd22ee74a.jpeg" group-title="Rad TV",Loop Unwind
> https://8c455e94c5ff44d0ada529dffef58ae5.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/unwind_littlstar/master.m3u8
> 
> #EXTINF:-1 tvg-logo="https://static.12core.net/43a4136e6bc3e153f68bb2dd200a6635.jpeg" group-title="Rad TV",Loop Yacht Rock
> https://90a0d12cbaff4b959ea24bb8a3560adf.mediatailor.us-west-2.amazonaws.com/v1/master/6b8beeb9ed833d048c8c8155a25a28fe617c5474/yacht_rock_littlstar/master.m3u8

Make a PR about that mate, I'll have a look at it afterwards.

**Comment by Dum4G** [comment]
I can't open any of those in VLC and last time I miraculously succeeded it was providing just couple of ads

**Comment by ygorlv** [comment]
it's working fine here

**Comment by Dum4G** [comment]
Doesn't work in CZ, UA, RU. Works in US and BR. It's partially geo-blocked

**Comment by Dum4G** [comment]
```
#EXTINF:-1 tvg-ID="" tvg-name="" tvg-logo="https://i.imgur.com/62CjWTa.jpg" group-title="USA ROKU",Loop 80s
https://55e014b3437040d08777729c863a2097.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Roku_Loop80s/playlist.m3u8
#EXTINF:-1 tvg-ID="" tvg-name="" tvg-logo="https://i.imgur.com/62CjWTa.jpg" group-title="USA ROKU",Loop 90s
https://6eb959e10c2a4477a5b14100220c3c5f.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Roku_Loop90s/playlist.m3u8
#EXTINF:-1 tvg-ID="" tvg-name="" tvg-logo="https://i.imgur.com/62CjWTa.jpg" group-title="USA ROKU",Loop Country
https://053155d1274848ed85106dbf20adc283.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Roku_LoopCountry/playlist.m3u8
#EXTINF:-1 tvg-ID="" tvg-name="" tvg-logo="https://i.imgur.com/62CjWTa.jpg" group-title="USA ROKU",Loop Hip-Hop
https://5580b04771d94e5eb245830c5975eb77.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Roku_LoopHipHop/playlist.m3u8
#EXTINF:-1 tvg-ID="" tvg-name="" tvg-logo="https://i.imgur.com/62CjWTa.jpg" group-title="USA ROKU",Loop Hottest
https://a0da9e6a83bc4a739ceb39f81766fce0.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Roku_LoopHottest/playlist.m3u8
#EXTINF:-1 tvg-ID="" tvg-name="" tvg-logo="https://i.imgur.com/62CjWTa.jpg" group-title="USA ROKU",Loop Party
https://aa25f9002c724666a6e1e9402e78f94f.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Roku_LoopParty/playlist.m3u8



#EXTINF:-1,Hottest Loop
https://loop-hottest-1.roku.wurl.com/manifest/playlist.m3u8
#EXTINF:-1,Hip Hop Loop
https://loop-hip-hop-1.roku.wurl.com/manifest/playlist.m3u8
#EXTINF:-1,Country Loop
https://loop-country-1.roku.wurl.com/manifest/playlist.m3u8
#EXTINF:-1,80's Loop
https://loop-80s-1.roku.wurl.com/manifest/playlist.m3u8
#EXTINF:-1,90's Loop
https://loop-90s-1.roku.wurl.com/manifest/playlist.m3u8
#EXTINF:-1,Party Loop
https://loop-party-1.roku.wurl.com/manifest/playlist.m3u8
```

Globally available channels from Roku
