### ISSUE TITLE
Add: RedeTV (ES)

### ISSUE THREAD

**Issue by ygorlv** [iptv-org/iptv#3113]
**Channel Name:** RedeTV (ES)
**Country:** Brazil
**Language:** Portuguese
**External Link (optional):** https://www.espost.com.br/ao-vivo/
**Notes (optional):** 
#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="BR" tvg-language="Portuguese" tvg-logo="https://www.livetvnews.com.br/wp-content/uploads/2019/03/Logo-RedeTV.png" group-title="General",Rede TV! (ES)
https://hls.brasilstream.com.br/live/redetves/redetves/tracks-v1a1/mono.m3u8

**Comment by Dum4G** [comment]
You can make pull requests
