### ISSUE TITLE
Issues with the CNN International Stream 

### ISSUE THREAD

**Issue by kelo0003** [iptv-org/iptv#3114]
**_Channel Name:_** CNN International (720p)
**_Broken Link (from playlist):_** News
**_Possible Replacement (optional):_** CNN International Hong Kong Stream
**_Notes (optional):_** It works but has started to buffer a lot recently,
. I have checked my internet and it is fine. It seems to be the stream itself. Could you take a look into seeing if it can be fixed?

**Comment by freearhey** [comment]
Could you give me a link to the specific playlist you are using?

**Comment by kelo0003** [comment]
https://iptv-org.github.io/iptv/categories/news.m3u

Sent from my iPhone XR

On 11 Jun 2021, at 7:11 PM, Aleksandr Statciuk ***@***.***> wrote:

﻿

Could you give me a link to the specific playlist you are using?

**Comment by freearhey** [comment]
Both CNN links from this playlist work for me without any problems. So there's nothing I can do here, but maybe someone else has encountered this problem and will suggest some solution.
