### ISSUE TITLE
Tv Tokyo Real Channel and J-One (French Channel) !!!

### ISSUE THREAD

**Issue by OMWD1995** [iptv-org/iptv#312]
Hi Guys, I'm new here and I wanted to thank you for creating a repositery about free IPTV links, you GUYS are JUST AWESOME !!!!!

I've always been interested in Japanese Tvs alongside the french ones, about the japanese my favorite is Tv Tokyo however I've the feeling like the TV tokyo you've put isn't the right one it's  rather a Japanese Tv about Theater but I don't know why this link has been named 'Tv Tokyo' not only here but on many website the only website where I saw a person namming it perfectly is here: http://www.tv001.vip/read.php?tid=300 (Use Google Translate you'll find the same link but with a different title). The real Tv Tokyo channel can be found here: https://ok.ru/live/1005196156545 but I've never been able to extract the IPTV link and read it on VLC instead of their website. So if you guys can help with that thank you in advance !!!!

Also if you guys can add a french channel called J-One that would be perfect !!!!!

Thank You in advance,
Cheers, 
Warren

**Comment by freearhey** [comment]
Thanks for pointing out the error. I already corrected the name of the channel.

As for the TV Tokyo and J-One channels, so far I have not been able to find a link to their working public streams (except the one that you provided). But if something appears, I will certainly add them here.

**Comment by OMWD1995** [comment]
Hi guy, if this can find you you i've found a website (one of the few) which streams J-One, this one: http://channelstream.net/j-one.php !
Hope this helps, 
Cheers,
Warren

**Comment by freearhey** [comment]
@OMWD1995 The fact is that some broadcasts only work on predefined websites. And this is exactly the case.

**Comment by freearhey** [comment]
**French:**
- [ ] J-One

**Japan:**
- [ ] TV Tokyo

**Comment by boomski** [comment]
I found 2 links with Tokyo tv

#EXTINF:-1, Tokyo tv
https://cdn.jp.jpnettv.live/jptv/kanto_tv_tokyo_540/chunklist_w2006317319.m3u8
#EXTINF:-1, Tokyo mx
https://cdn.jp.jpnettv.live/jptv/kanto_tokyo_mx1_540/chunklist_w1401581135.m3u8

**Comment by freearhey** [comment]
Closed in favor #1939
