### ISSUE TITLE
Fix: SentTVGlobalNetwork.us

### ISSUE THREAD

**Issue by Tribalize** [iptv-org/iptv#3125]
**_Channel Name:_** xxx SentTVGlobalNetwork.us
**_Broken Link (from playlist):_** xxx https://nrpus.bozztv.com/36bay2/gusa-stgn/index.m3u8 (us.m3u)
**_Possible Replacement (optional):_** xxx none
**_Notes (optional):_** xxx could not find a replacement channel

**Comment by LaneSh4d0w** [comment]
https://rpn1.bozztv.com/36bay2/gusa-stgn/mono.m3u8 ...

**Comment by Tribalize** [comment]
thanks couldnt find the link
