### ISSUE TITLE
Fix: TVSMusicNetwork.us (us.m3u)

### ISSUE THREAD

**Issue by Tribalize** [iptv-org/iptv#3126]
**_Channel Name:_** xxx TVSMusicNetwork.us
**_Broken Link (from playlist):_** xxx https://nrpus.bozztv.com/36bay2/gusa-tvsmusic/tracks-v1a1/index.m3u8
**_Possible Replacement (optional):_** xxx none
**_Notes (optional):_** xxx could not find the channel listed or a replacement

**Comment by LaneSh4d0w** [comment]
https://rpn1.bozztv.com/36bay2/gusa-tvsmusic/tracks-v1a1/mono.m3u8 ...

**Comment by Tribalize** [comment]
thanks couldnt find a link for it
