### ISSUE TITLE
Fix: TVSTodayHomeEntertainmentNetwork.us

### ISSUE THREAD

**Issue by Tribalize** [iptv-org/iptv#3127]
**_Channel Name:_** xxx TVSTodayHomeEntertainmentNetwork.us
**_Broken Link (from playlist):_** xxx https://nrpus.bozztv.com/36bay2/gusa-TVSTodayHomeEntertainment/index.m3u8 (us.m3u)
**_Possible Replacement (optional):_** xxx none
**_Notes (optional):_** xxx this is a duplicate link. there are 2 listed for this channel. Corrected link is in a pull request

**Comment by LaneSh4d0w** [comment]
https://rpn1.bozztv.com/36bay2/gusa-TVSTodayHomeEntertainment/mono.m3u8 ...

**Comment by Tribalize** [comment]
i had similar link. but it was listed twice in the list. didnt know procedure on listing duplicates

`#EXTINF:-1 tvg-id="TVSTodayHomeEntertainmentNetwork.us" tvg-name="TVS Today Home Entertainment Network" tvg-country="US" tvg-language="English" tvg-logo="https://i.imgur.com/pXOyNEy.png" group-title="",TVS Today Home Entertainment Network (720p)
https://rpn1.bozztv.com/36bay2/gusa-TVSTodayHomeEntertainment/mono.m3u8
#EXTINF:-1 tvg-id="TVSTodayHomeEntertainmentNetwork.us" tvg-name="TVS Today Home Entertainment Network" tvg-country="US" tvg-language="English" tvg-logo="https://i.imgur.com/pXOyNEy.png" group-title="General",TVS Today Home Entertainment Network
https://rpn1.bozztv.com/36bay2/gusa-TVSTodayHomeEntertainment/tracks-v1a1/index-1623403745-now.m3u8`
