### ISSUE TITLE
Fix: TVSTravelNetwork.us

### ISSUE THREAD

**Issue by Tribalize** [iptv-org/iptv#3129]
**_Channel Name:_** TVSTravelNetwork.us
**_Broken Link (from playlist):_** https://nrpus.bozztv.com/36bay2/gusa-tvstravel/index.m3u8 (us.m3u)
**_Possible Replacement (optional):_** https://rpn1.bozztv.com/36bay2/gusa-moviemagictv/tracks-v1a1/mono.m3u8
**_Notes (optional):_** replacement link does not match tvg-id

**Comment by Dum4G** [comment]
You just forgot to place .us in the tvg-id, there's nothing else that doesn't match our guidelines for now. You can bring that link back

**Comment by Tribalize** [comment]
thanks. i thought it was there. i will add back

**Comment by LaneSh4d0w** [comment]
https://prn1.bozztv.com/36bay2/gusa-tvstravel/mono.m3u8 ...

**Comment by LaneSh4d0w** [comment]
I have given you all links you can use on each of them. Verify if they work for you (i've tested them), and simply change them on your already existing PR.

**Comment by Tribalize** [comment]
thanks couldnt find the link
