### ISSUE TITLE
New Links Updated Channels Al Kass Sports

### ISSUE THREAD

**Issue by step1975roma** [iptv-org/iptv#3139]
**Channel Name:** Alkass One
**Country:** Qatar
**Language:** Arabic
**External Link (optional):** http://www.elahmad.com/tv/m3u8/online_tv.m3u8?id=alkass1

**Channel Name:** Alkass Two
**Country:** Qatar
**Language:** Arabic
**External Link (optional):** http://www.elahmad.com/tv/m3u8/online_tv.m3u8?id=alkass2

**Channel Name:** Alkass Four
**Country:** Qatar
**Language:** Arabic
**External Link (optional):** http://www.elahmad.com/tv/m3u8/online_tv.m3u8?id=alkass4

**Channel Name:** Alkass Five
**Country:** Qatar
**Language:** Arabic
**External Link (optional):** http://www.elahmad.com/tv/m3u8/online_tv.m3u8?id=alkass5

**Channel Name:** Alkass Online
**Country:** Qatar
**Language:** Arabic
**External Link (optional):** http://www.elahmad.com/tv/m3u8/online_tv.m3u8?id=alkassonline

**Notes (optional):** These links also work on kodi
original urls are encrypted and don't work on kodi,

If there are missing other channels i have updates for you and let you know if you like....
Best regards, Goodbye.

**Comment by freearhey** [comment]
Please read the [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel) before posting your request next time.
