### ISSUE TITLE
Philippines

### ISSUE THREAD

**Issue by xtremetv** [iptv-org/iptv#314]
Please if possible can u add more Philippines channels like Cinema one, Tfc, Gma and more
really appreciate for your all work

**Comment by jlapitan** [comment]
@freearhey 

can you test this


#EXTM3U
#EXTINF:-1,PH: ABS CBN
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31750
#EXTINF:-1,PH: ABS CBN NEWS
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31749
#EXTINF:-1,PH: ANC
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31748
#EXTINF:-1,PH: ANIMAL PLANET
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31747
#EXTINF:-1,PH: ANIMAX
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31746
#EXTINF:-1,PH: ANIPLUS
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31745
#EXTINF:-1,PH: ASIA NEWS
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31744
#EXTINF:-1,PH: AXN
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31743
#EXTINF:-1,PH: BEIN SPORTS 1 HD
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31742
#EXTINF:-1,PH: BEIN SPORTS 2 HD
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31741
#EXTINF:-1,PH: BEIN SPORTS 3 HD
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31740
#EXTINF:-1,PH: BLUE ANT ENTER
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31739
#EXTINF:-1,PH: BLUE ANT EXT
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31738
#EXTINF:-1,PH: CARTOON NETWORK
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31737
#EXTINF:-1,PH: CLASSIC MOVIES
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31736
#EXTINF:-1,PH: COMEDY CENTRAL
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31735
#EXTINF:-1,PH: CRIME INVESTIGATION
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31734
#EXTINF:-1,PH: DISCOVERY ASIA WORLD
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31733
#EXTINF:-1,PH: DISNEY CH
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31732
#EXTINF:-1,PH: DISNEY JR
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31731
#EXTINF:-1,PH: DZMM TELERADYO
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31730
#EXTINF:-1,PH: EUROSPORT
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31729
#EXTINF:-1,PH: FIY
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31728
#EXTINF:-1,PH: FOOD NETWORK
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31727
#EXTINF:-1,PH: GMA LIFE TV
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/30213
#EXTINF:-1,PH: GMA NEWS TV
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/30212
#EXTINF:-1,PH: GMA PINOY TV
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/30211
#EXTINF:-1,PH: HISTORY
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31726
#EXTINF:-1,PH: HISTORY 2
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31725
#EXTINF:-1,PH: HITS
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31724
#EXTINF:-1,PH: LIFETIME CHANNEL
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31723
#EXTINF:-1,PH: LIVING ASIA
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31722
#EXTINF:-1,PH: MTV ASIA
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31721
#EXTINF:-1,PH: MTV LIVE
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31720
#EXTINF:-1,PH: NAT GEO
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31719
#EXTINF:-1,PH: NICK JR
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31718
#EXTINF:-1,PH: NICKELODEON
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31717
#EXTINF:-1,PH: SONY CH
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31716
#EXTINF:-1,PH: TELENOVELA
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31715
#EXTINF:-1,PH: THRILL
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31714
#EXTINF:-1,PH: TLC
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31713
#EXTINF:-1,PH: TRAVEL CH
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31712
#EXTINF:-1,PH: WARNER TV
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31711
#EXTINF:-1,PH:ASIAN FOOD CH
http://m3ulink.com:6969/gxxodmean1/FLA27hRT/31710

**Comment by jlapitan** [comment]
and this, not sure how to test 

#EXTINF:-1,Fox Sports Asia (Philippines) | HD
http://lotustv.be:80/2911/2911/159483
#EXTINF:-1,CNN PH | HD
http://lotustv.be:80/2911/2911/59121
#EXTINF:-1,TFC | HD
http://lotustv.be:80/2911/2911/88777
#EXTINF:-1,TFC | HD *
http://lotustv.be:80/2911/2911/59114
#EXTINF:-1,GMA LIFE | HD
http://lotustv.be:80/2911/2911/88779
#EXTINF:-1,GMA LIFE | HD*
http://lotustv.be:80/2911/2911/59110
#EXTINF:-1,GMA PINOY | HD
http://lotustv.be:80/2911/2911/88778
#EXTINF:-1,GMA PINOY | HD*
http://lotustv.be:80/2911/2911/59111
#EXTINF:-1,GMA NEWS INT | HD
http://lotustv.be:80/2911/2911/59109
#EXTINF:-1,PEOPLE'S TV | HD
http://lotustv.be:80/2911/2911/59119
#EXTINF:-1,INC TV | HD
http://lotustv.be:80/2911/2911/59120
#EXTINF:-1,UNTV | HD
http://lotustv.be:80/2911/2911/62908
#EXTINF:-1,UN TV | HD*
http://lotustv.be:80/2911/2911/59112
#EXTINF:-1,ABS - CBN | HD
http://lotustv.be:80/2911/2911/59116
#EXTINF:-1,ABS - DZMM | HD
http://lotustv.be:80/2911/2911/62905
#EXTINF:-1,ANC | HD *
http://lotustv.be:80/2911/2911/59122
#EXTINF:-1,ANC | HD
http://lotustv.be:80/2911/2911/62906

**Comment by xtremetv** [comment]
Tested in VLC nothing is working. 
I hope if u can find more links. 
Thanks 

Sunny
Xtreme Tv Service

**Comment by freearhey** [comment]
- [ ] Cinema One
- [x] TFC
https://github.com/iptv-org/iptv/blob/bf9883ed3c9088abf6612e662acaaec1e653f54a/channels/ph.m3u#L22-L23
- [x] GMA
https://github.com/iptv-org/iptv/blob/bf9883ed3c9088abf6612e662acaaec1e653f54a/channels/ph.m3u#L26-L29

**Comment by xtremetv** [comment]
Thank you so much for your hard work. 

Sunny
Xtreme Tv Service

**Comment by luke026** [comment]
Help me get url of kapamilya tfc abs cbn tv5 pls pls or a2z

**Comment by luke026** [comment]
How to wacthtfc  on iptv

**Comment by luke026** [comment]
Can i get linked tfc pls i cant open

**Comment by freearhey** [comment]
@luke026 For the rest of the community to see your request, it would be better to create a separate issue [here](https://github.com/iptv-org/iptv/issues/new?assignees=&labels=channel+request&template=channel-request.md&title=Add%3A+xxx). Just be sure to read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#contributing-guide) carefully before doing so.

**Comment by luke026** [comment]
How sir
