### ISSUE TITLE
Add: BBC ONE, ITV1, moroccan channels FHD

### ISSUE THREAD

**Issue by Yasszah** [iptv-org/iptv#3141]
Please i want Moroccan channels in **FHD**, i can't find, 
here is the website : **http://snrtlive.ma**  
                                 AND **https://2m.ma/fr** (only one here  channel here :**2M**)

And also, i can not find BBC One and ITV 1

If someone can help me please please please, im a moroccan who lives in China, i need to add the moroccan channels FHD to my ssiptv on my box, THANK YOU SO MUCH.

**Channel Name:** BBC ONE, ITV1, 2M monde, Al Aoula, Arryadia, Arrabiaa, Aflam, Assadissa, Tamazight, 
**Country:** UK, MOROCCO
**Language:** English, Arabic
**External Link (optional):** http://snrtlive.ma ___ https://2m.ma/fr
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
https://github.com/iptv-org/iptv/blob/master/channels/ma.m3u and https://github.com/iptv-org/iptv/blob/master/channels/uk.m3u

contains the channels you are mentioning.

**Comment by freearhey** [comment]
Please read the [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel).

**Comment by Yasszah** [comment]
Thank you, i saw them but the channels mentioned are not FULL HD. Still there is no BBC ONE or  ITV1 (only local bbcs exist and itv2 3 4)
