### ISSUE TITLE
New local CBS Stream

### ISSUE THREAD

**Issue by FpFan65** [iptv-org/iptv#3157]
**Channel Name:** CBS 2 (WCBS)
**Country:** US
**Language:** English
**External Link (optional):** https://streams.the6tv.duckdns.org:2443/locals/NewYorkCity/wcbs-dt1.m3u8
**Notes (optional):** Full Channel Simulcast

**Comment by MapGuy11** [comment]
Doesn't work.

**Comment by FpFan65** [comment]
This I believe is the actual stream that came from the one submitted, and
no longer working.  Might be a hosting issue, or they forgot to change out
that expiration string

https://v-ny.mybtv.net/event/545/768x432.m3u8?start_time=2021-05-29T19%3A45%3A00%2B00%3A00&end_time=2029-05-29T23%3A00%3A00%2B00%3A00&env=prd&uid=25110

If I should resubmit it through the website, I can do that as well.  The
one you have for WPHL is now broken too.  Let me go down the list, and get
you that proper link, and I'll submit it.

Butch Shomph
Riverside, CA

**Comment by fotvnetwork** [comment]
It is working as of now
