### ISSUE TITLE
New Local CBS Stream

### ISSUE THREAD

**Issue by FpFan65** [iptv-org/iptv#3159]
**Channel Name:** CBS 3 (KYW)
**Country:** US
**Language:** English
**External Link (optional):** https://streams.the6tv.duckdns.org:2443/locals/Philadelphia/kyw-dt1.m3u8
**Notes (optional):** Full Channel Simulcast

**Comment by MapGuy11** [comment]
Doesn't work.

**Comment by FpFan65** [comment]
Here is the working link for CBS Philadelphia. There is no sound at the
moment, hopefully that will change, but the is the proper stream:

https://v-pi.mybtv.net/event/321/768x432.m3u8?start_time=2021-05-29T19%3A45%3A00%2B00%3A00&end_time=2029-05-29T23%3A00%3A00%2B00%3A00&env=prd&uid=25110

Will be submitting the rest of the NYC and Philly locals today.
Seeking out the Atlanta Cluster.  The NYC event stream numbers end at 664.
Trying to guess what two letters they are using for Atlanta.  Perhaps you
cloud the able to take a crack at it in the future? (i just need the
letters and an even number to figure out the rest)

Butch Shomph
Riverside, CA

**Comment by MapGuy11** [comment]
The broadcaster doesn't want any links for Philadelphia, New York, and Eastern US cities available outside of their apps sorry.
