### ISSUE TITLE
Fix: GREEK Channel ANT1

### ISSUE THREAD

**Issue by Yasszah** [iptv-org/iptv#3161]
**_Channel Name:_** ANT 1
**_Broken Link (from playlist):_** https://antennalivesp-lh.akamaihd.net/i/live_1@715138/master.m3u8 
https://antennalivesp-lh.akamaihd.net/i/live_1@715138/index_800_av-p.m3u8

**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** Broadcaster of EURO 2020, if someone can please fix it as soon as possible, its where i watch the EURO games, thank you.

**Comment by Dum4G** [comment]
test
https://antennaamdnoenc.akamaized.net/ant1_akamai/abr/ant1prodabr/ant1prodstream_1080p/video.m3u8

**Comment by Yasszah** [comment]
The links were working these days fine (i live in china)
I use the links on ssiptv on my box, i can not use geoblocked links.
Please help me with some links of ANT 1 i can use even in China. 😔😔
Thank you.

**Comment by Dum4G** [comment]
We won't help you fast, unless some public link will be found which I doubt.
And even if we will playlists get updated every midnight by GMT time.
My advice is to find any other channel that streams Euro from here
https://iptv-org.github.io/iptv/categories/sports.m3u

**Comment by LaneSh4d0w** [comment]
Best bet would be to watch Romanian channel Look Sport, maybe they do put it. I've added Polsat Sports not so long ago, will add Canal + Sport Poland soon too.

**Comment by Yasszah** [comment]
Thank you guys for your responses and assistance. I will try with other channels hopefully they stream Euro.
Thank you again, have a good day guys.
