### ISSUE TITLE
New NBC Stream

### ISSUE THREAD

**Issue by FpFan65** [iptv-org/iptv#3163]
**Channel Name:** NBC 10 (WCAU)
**Country:** US
**Language:** English
**External Link (optional):** https://v-pi.mybtv.net/event/345/768x432.m3u8?start_time=2021-05-29T19%3A45%3A00%2B00%3A00&end_time=2029-05-29T23%3A00%3A00%2B00%3A00&env=prd&uid=25110
**Notes (optional):** Full Channel Simulcast

**Comment by MapGuy11** [comment]
400 Invalid Request

**Comment by MapGuy11** [comment]
The broadcaster doesn't want any links for Philadelphia, New York, and Eastern US cities available outside of their apps sorry.
