### ISSUE TITLE
New Backup Cozi TV Stream

### ISSUE THREAD

**Issue by FpFan65** [iptv-org/iptv#3164]
**Channel Name:** Cozi TV (East Coast Philly Feed)
**Country:** US
**Language:** English
**External Link (optional):** https://v-pi.mybtv.net/event/346/768x432.m3u8?start_time=2021-05-29T19%3A45%3A00%2B00%3A00&end_time=2029-05-29T23%3A00%3A00%2B00%3A00&env=prd&uid=25110
**Notes (optional):**

**Comment by MapGuy11** [comment]
400 Invalid Request

**Comment by MapGuy11** [comment]
The broadcaster doesn't want any links for Philadelphia, New York, and Eastern US cities available outside of their apps sorry.
