### ISSUE TITLE
New Local PBS Stream

### ISSUE THREAD

**Issue by FpFan65** [iptv-org/iptv#3165]
**Channel Name:** WHYY-DT1 12 PBS Philadelphia
**Country:** US
**Language:** English
**External Link (optional):** https://whyydt.lls.cdn.pbs.org/whyydt/6e441aa1-51ab-4ecd-a1dc-bc99da43c3ed/primary-1080p.m3u8
**Notes (optional):** Primary HD Stream

**Comment by MapGuy11** [comment]
Please give the adaptive link

**Comment by FpFan65** [comment]
https://whyydt.lls.cdn.pbs.org/whyydt/6e441aa1-51ab-4ecd-a1dc-bc99da43c3ed/primary.m3u8

**Comment by FpFan65** [comment]
Will give that one going forward with the others

**Comment by MapGuy11** [comment]
Please pull request.

**Comment by LaneSh4d0w** [comment]
Geo-locked.
