### ISSUE TITLE
Fix: ABC 15 (720p)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3169]
**_Channel Name:_** ABC 16 (720p)
**_Broken Link (from playlist):_** https://content.uplynk.com/61fb4f9811b64bddaf2cfb0e2e4a32db.m3u8
**_Possible Replacement (optional):_** Do not know.
**_Notes (optional):_** Channel is just a four-minute playback.

**Comment by trancer1994** [comment]
https://content.uplynk.com/channel/9064650abed74150861428b5fbb426cf.m3u8?v=2&ad=live&m.sound=normal&pos=midroll&expand=ad_live&m.sound=muted&m.playback=autoplay&ad.sz=1x1000&ad.cust_params=fname%3Dlive2%26categories%3D%26refdomain%3Dabc15.com%26iframed%3D0%26pxconfig%3Dweb-live%26bidders%3Dpublica%26player_width%3D1280%26player_height%3D720%26ip%3D[Insert_IP]%26ua%3D[Insert_UA]&ad.url=https%3A%2F%2Fwww.abc15.com%2F

**Comment by jkemp814** [comment]
Thank you for the response, but that seems to be the local ABC newscast. I was hoping for the ABC national channel, which I can't seem to find in any of the list.

**Comment by jkemp814** [comment]
That link does match what I posted. I guess that link doesn't carry the national content.

**Comment by jkemp814** [comment]
When I load the channel from San Francisco it does show the national broadcast during special events

**Comment by LaneSh4d0w** [comment]
> 
> 
> [https://content.uplynk.com/channel/9064650abed74150861428b5fbb426cf.m3u8?v=2&ad=live&m.sound=normal&pos=midroll&expand=ad_live&m.sound=muted&m.playback=autoplay&ad.sz=1x1000&ad.cust_params=fname%3Dlive2%26categories%3D%26refdomain%3Dabc15.com%26iframed%3D0%26pxconfig%3Dweb-live%26bidders%3Dpublica%26player_width%3D1280%26player_height%3D720%26ip%3D[Insert_IP]%26ua%3D[Insert_UA]&ad.url=https%3A%2F%2Fwww.abc15.com%2F](https://content.uplynk.com/channel/9064650abed74150861428b5fbb426cf.m3u8?v=2&ad=live&m.sound=normal&pos=midroll&expand=ad_live&m.sound=muted&m.playback=autoplay&ad.sz=1x1000&ad.cust_params=fname%3Dlive2%26categories%3D%26refdomain%3Dabc15.com%26iframed%3D0%26pxconfig%3Dweb-live%26bidders%3Dpublica%26player_width%3D1280%26player_height%3D720%26ip%3D%5BInsert_IP%5D%26ua%3D%5BInsert_UA%5D&ad.url=https%3A%2F%2Fwww.abc15.com%2F)

Can be trimmed to https://content.uplynk.com/channel/9064650abed74150861428b5fbb426cf.m3u8, however I'll need to check if this is the right one before changing it.

**Comment by jkemp814** [comment]
Yes, that is the right local newscast. But now the live local FOX 10 Phoenix channel. I must be looking for the regular FOX OTA channel.

**Comment by LaneSh4d0w** [comment]
I have https://content.uplynk.com/channel/9deaf22aaa33461f9cac22e030ed00ec.m3u8

**Comment by jkemp814** [comment]
https://www.abc15.com/live

**Comment by jkemp814** [comment]
Okay, that link you posted, they do not stream like the OTA channel, thank you both. I'll close this.
