### ISSUE TITLE
New Irish Channels

### ISSUE THREAD

**Issue by 129612231-scripts** [iptv-org/iptv#3170]
**Channel Name:** Virgin Media One
**Country:** Ireland (IE)
**Language:** English
**External Link (optional):** http://iptvnow.me:8080/dindin-3505/RAp0L4nWBm/1143.ts
**Notes (optional):** Stutters Sometimes

**Comment by LaneSh4d0w** [comment]
Duplicate of #1966, closed in that favor.

**Comment by 129612231-scripts** [comment]
Yes, None of the channels there have been added.
