### ISSUE TITLE
Add: Stadium

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3182]
**Channel Name:** Stadium
**Country:** USA
**Language:** English
**External Link (optional):** https://bcovlive-a.akamaihd.net/e64d564b9275484f85981d8c146fb915/us-east-1/5994000126001/profile_0/2f305439821a4609adfc325e18854e67/chunklist_ssaiV.m3u8
**Notes (optional):** Located in Phoenix, AZ - https://en.wikipedia.org/wiki/KDVD-LD

**Comment by Sphinxroot** [comment]
https://watchstadium.com/live/

they have also temporary live stream 

masterManifest | https://bcovlive-a.akamaihd.net/e64d564b9275484f85981d8c146fb915/us-east-1/5994000126001/8036529875f74c81b5f50851bffbc421/playlist_ssaiM.m3u8
-- | --
mediaManifest | https://bcovlive-a.akamaihd.net/e64d564b9275484f85981d8c146fb915/us-east-1/5994000126001/profile_0/a5097377a0ac4d2bb16c8ddc6f4b72ed/chunklist_ssaiV.m3u8



chunklist_ssaiV.m3u8 dont load for me on kodi or vlc  but  playlist_ssaiM.m3u8 does

**Comment by Tribalize** [comment]
stadium is in the list already.

**Comment by jkemp814** [comment]
I was hoping of getting the local Phoenix channel Stadium. Using https://titantv.com guild it shows something different. When opening the web channel, it is also different from the OTA channel. When the other Stadum channel is back online I will settle for that.

**Comment by jkemp814** [comment]
Okay, I'll close this. Seems my TV guide is two hours behind.
