### ISSUE TITLE
Fix: UniMas (KFSF)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3184]
**_Channel Name:_** UniMAS
**_Broken Link (from playlist):_** https://streams.the6tv.duckdns.org:2443/locals/BayArea/kfsf-dt1.m3u8
**_Possible Replacement (optional):_**
**_Notes (optional):_** Channel was working consistantly

**Comment by Sphinxroot** [comment]
close in favor of #3191
