### ISSUE TITLE
Fix: &Flix

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3185]
**_Channel Name:_** &Flix
**_Broken Link (from playlist):_** https://y5w8j4a9.ssl.hwcdn.net/andflixhd/tracks-v1a1/index.m3u8
**_Possible Replacement (optional):_**
**_Notes (optional):_** VLC is unable to open the MRL 'https://y5w8j4a9.ssl.hwcdn.net/andflixhd/tracks-v1a1/index.m3u8'

**Comment by Sphinxroot** [comment]
everything is working fine https://i.imgur.com/ptjscSx.png

**Comment by LaneSh4d0w** [comment]
I think i'll change this link to an adaptive one.
