### ISSUE TITLE
Fix: Bonce TV

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3187]
**_Channel Name:_** Bounce TV
**_Broken Link (from playlist):_** https://seswa.bonce.tv/hls/bonceswa_720p2628kbs/index.m3u8
**_Possible Replacement (optional):_**
**_Notes (optional):_** Bonce TV should actully be named Bounce TV. Stream plays

**Comment by Sphinxroot** [comment]
actualy not  see here https://bonce.tv/  and  bounce tv also exist https://www.bouncetv.com/  not the same  channel   ..so naming is correct

**Comment by LaneSh4d0w** [comment]
Both channels exist. No naming issues found.
