### ISSUE TITLE
Fix: ABC 15 (720)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3188]
**_Channel Name:_** ABC 15
**_Broken Link (from playlist):_** https://content.uplynk.com/61fb4f9811b64bddaf2cfb0e2e4a32db.m3u8
**_Possible Replacement (optional):_** https://content.uplynk.com/channel/9deaf22aaa33461f9cac22e030ed00ec.m3u8
**_Notes (optional):_** Current stream is a four-minute playback.

**Comment by Sphinxroot** [comment]
thank for the report   .. link have been changed
