### ISSUE TITLE
Fix: Univision (KDTV)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3189]
**_Channel Name:_** Univision
**_Broken Link (from playlist):_** https://streams.the6tv.duckdns.org:2443/locals/BayArea/kfsf-dt2.m3u8
**_Possible Replacement (optional):_**
**_Notes (optional):_** VLC just skips right pass the channel list to next channel

**Comment by Sphinxroot** [comment]
close in favor of #3191
