### ISSUE TITLE
Fix: Univision Philadelphia (WUVP)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3190]
**_Channel Name:_** Univision
**_Broken Link (from playlist):_** https://cdn23-phl.the6tv.duckdns.org:2443/the6tv-philadelphia/the6tv-2Geyj4U8De/index.m3u8
**_Possible Replacement (optional):_**
**_Notes (optional):_** VLC just skips right pass channel.

**Comment by Sphinxroot** [comment]
close in favor of #3191
