### ISSUE TITLE
Fix: ion TV (KKPX)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3191]
**_Channel Name:_** Ion TV
**_Broken Link (from playlist):_** https://streams.the6tv.duckdns.org:2443/locals/BayArea/kkpx-dt1.m3u8
**_Possible Replacement (optional):_**
**_Notes (optional):_** VLC just skips pass to next working channel

**Comment by Sphinxroot** [comment]
the6tv.duckdns.org  could have problem for now   adding #3190 #3189 #3184

**Comment by LaneSh4d0w** [comment]
> 
> 
> the6tv.duckdns.org could have problem for now adding #3190 #3189 #3184

This server is maintained by @MapGuy11 , adding him to the discussion.

**Comment by MapGuy11** [comment]
> > the6tv.duckdns.org could have problem for now adding #3190 #3189 #3184
> 
> This server is maintained by @MapGuy11 , adding him to the discussion.
@LaneSh4d0w sorry there was huge tree damage and the power has been out for over 8 hours it is suspected to be on 12:00 EST.

**Comment by MapGuy11** [comment]
> > the6tv.duckdns.org could have problem for now adding #3190 #3189 #3184
> 
> This server is maintained by @MapGuy11 , adding him to the discussion.
@LaneSh4d0w sorry there was huge tree damage and the power has been out for over 8 hours it is suspected to be on 12:00 EST.

**Comment by MapGuy11** [comment]
@LaneSh4d0w sorry there was huge tree damage and the power has been out for over 8 hours it is suspected to be on 12:00 EST. This is very unusual especially in the dead of summer.

**Comment by LaneSh4d0w** [comment]
@MapGuy11 No problem.

**Comment by LaneSh4d0w** [comment]
Deleted duplicate messages

**Comment by jkemp814** [comment]
I thought that maybe the case. Those channels were normally rock solid.

**Comment by MapGuy11** [comment]
> I thought that maybe the case. Those channels were normally rock solid.

I try my best!

**Comment by MapGuy11** [comment]
We now have power after more than 24 hours!
