### ISSUE TITLE
Add: Bandnews

### ISSUE THREAD

**Issue by ygorlv** [iptv-org/iptv#3199]
**Channel Name:** Bandnews
**Country:** Brazil
**Language:** Portuguese
**External Link (optional):** https://bandnewstv.band.uol.com.br/aovivo/
**Notes (optional):** https://play.google.com/store/apps/details?id=com.agrega.bandnews

**Comment by fotvnetwork** [comment]
https://evpp.mm.uol.com.br/geob_band/bandnewstv/playlist.m3u8

**Comment by fotvnetwork** [comment]
It may be geo-locked

**Comment by ygorlv** [comment]
I think there is another blocking way, because it doenst work in VLC, even on my brazilian IP

**Comment by Sphinxroot** [comment]
no media Manifest found
