### ISSUE TITLE
Add: Arizona PBS Kids

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3200]
**Channel Name:** Arizona PBS Kids
**Country:** USA
**Language:** English
**External Link (optional):** https://livestream.pbskids.org/out/v1/00a3b9014fa54c40bee6ca68a104a8a4/mst.m3u8
**Notes (optional):** KAET-DT4, Phoenix, AZ (PBS Kids)

**Comment by lrm864** [comment]
This is just the Mountain feed, but this is the feed that Arizona PBS Kids is using:
https://livestream.pbskids.org/out/v1/00a3b9014fa54c40bee6ca68a104a8a4/mst.m3u8

**Comment by jkemp814** [comment]
You are correct. I will change the external link in the request.
