### ISSUE TITLE
Add: Futura

### ISSUE THREAD

**Issue by ygorlv** [iptv-org/iptv#3202]
**Channel Name:** Futura
**Country:** Brazil
**Language:** Portuguese
**External Link (optional):** https://canaisglobo.globo.com/futura
**Notes (optional):** group: Education

**Comment by Sphinxroot** [comment]
must be geo on site  no hls found

found this one try if its the correct channel 
https://tv.unisc.br/hls/test.m3u8

**Comment by ygorlv** [comment]
Thanks for your search! Apparently that's a affiliate channel that could be a good substitute, but right now it's offline.

**Comment by Dum4G** [comment]
https://canal1.proxy.tokplay.com.br/videos/event9/auto.m3u8
What do you think? @ygorlv

**Comment by Dum4G** [comment]
Both links are live and show the same atm of writing

**Comment by ygorlv** [comment]
> https://canal1.proxy.tokplay.com.br/videos/event9/auto.m3u8
> What do you think? @ygorlv

That's it!! Thanks! (where did you found it?!)

**Comment by Dum4G** [comment]
> (where did you found it?!)

We're not alone on Github
