### ISSUE TITLE
Add: ToloTV

### ISSUE THREAD

**Issue by A-Alizadeh** [iptv-org/iptv#3209]
**Channel Name:** Tolo TV
**Country:** Afghanistan
**Language:** AF
**External Link (optional):** https://www.darya.net/#!/
**Notes (optional):**

**Comment by Sphinxroot** [comment]
all 6 channels 

master.m3u8 have token and will play both video and sound 

media_0.m3u8 =720p no sound
media_1.m3u8 =480p no sound
media_2.m3u8 =240p no sound
media_3.m3u8 = sound only

**Comment by A-Alizadeh** [comment]
There would be no way to create a token system right?

**Comment by LaneSh4d0w** [comment]
> 
> 
> all 6 channels
> 
> master.m3u8 have token and will play both video and sound
> 
> media_0.m3u8 =720p no sound
> media_1.m3u8 =480p no sound
> media_2.m3u8 =240p no sound
> media_3.m3u8 = sound only

GET request to https://www.darya.net/api/1.0/stream?streamID=TOLOnews gets you the link you want.

**Comment by Dum4G** [comment]
https://github.com/taodicakhia/IPTV_Overworld/raw/master/channels/af/tolotv.m3u8
