### ISSUE TITLE
Add: ethipion tv

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#3210]
can you add the ethiopians channels from this site 
https://ethiov.com/live-channels

**Comment by Sphinxroot** [comment]
all Stream have   (   CustomIp=(your IP) + endtime= + hash=   )  =  token stream

**Comment by LaneSh4d0w** [comment]
https://video2b.vixtream.net/tv/v/amma

**Comment by LaneSh4d0w** [comment]
It would take some time but it's basically possible.

**Comment by LaneSh4d0w** [comment]
See https://iptv-all.lanesh4d0w.codes/TESTING/ethiopia/amhara-tv for a live example.

**Comment by freearhey** [comment]
Closed in favor #3900
