### ISSUE TITLE
Add: CNN (US)

### ISSUE THREAD

**Issue by fotvnetwork** [iptv-org/iptv#3217]
**Channel Name:** CNN
**Country:** US
**Language:** English
**External Link (optional):** http://hlss.goodgame.ru/hls/185257.m3u8
**Notes (optional):** Link grabbed from a streaming site called Freeintertv

**Comment by MapGuy11** [comment]
Both work with Web Browser Not VLC. Framerate is terrible.

**Comment by LaneSh4d0w** [comment]
> 
> 
> Both work with Web Browser Not VLC. Framerate is terrible.

With a bit of luck it could be solved by doing what @Dum4G did with the LiveDooMovie links. I'll make my tests and see if it works.

**Comment by Sphinxroot** [comment]
http://stream.tvtap.live:8081/live/us-cnn.stream/playlist.m3u8

**Comment by trancer1994** [comment]
Any of these should work. 

https://turnerlive.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/de/master.m3u8?hdnts=exp=1612621989~acl=/hls/live/586495/cnngo/*!/hls/live/586495-b/cnngo/*~id=ecd1c86a31f09e9ff023f310e9675d8b-1612621990~hmac=b5dcbb17b080ea169be0393fbc87b19f096576f985b0cec2a0dd5e9f4556df6d
https://tve-live-lln.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_0_3564000.m3u8
https://turnerlive.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_4_1064000.m3u8
https://turnerlive.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_3_1464000.m3u8
https://turnerlive.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_0_3564000.m3u8
https://cnnlive.warnermediacdn.com/hls/live/2006689-b/live0/stream.m3u8
https://cnnlive.warnermediacdn.com/hls/live/2006689-b/live0/stream_Layer7.m3u8

**Comment by MapGuy11** [comment]
https://cnnlive.warnermediacdn.com/hls/live/2006689-b/live0/stream_Layer7.m3u8
https://cnnlive.warnermediacdn.com/hls/live/2006689-b/live0/stream.m3u8
https://turnerlive.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/de/master.m3u8?hdnts=exp=1612621989~acl=/hls/live/586495/cnngo/*!/hls/live/586495-b/cnngo/*~id=ecd1c86a31f09e9ff023f310e9675d8b-1612621990~hmac=b5dcbb17b080ea169be0393fbc87b19f096576f985b0cec2a0dd5e9f4556df6d

^ Doesn't Work

**Comment by Dum4G** [comment]
https://1176700211.rsc.cdn77.org/OmhwddEDNGvIOgq0ZAX2Sg==,1624393062/1176700211/tracks-v1a1/mono.m3u8

**Comment by MapGuy11** [comment]
> https://1176700211.rsc.cdn77.org/OmhwddEDNGvIOgq0ZAX2Sg==,1624393062/1176700211/tracks-v1a1/mono.m3u8

Aren't these tokened?

**Comment by Dum4G** [comment]
> Aren't these tokened?

You tell us

**Comment by MapGuy11** [comment]
> > Aren't these tokened?
> 
> You tell us
> 
> 

It works currently but the letters and numbers before the equal sign and after the cdn url are normally the token.

**Comment by LaneSh4d0w** [comment]
I give this link a whopping 5 hours left

**Comment by Dum4G** [comment]
Isn't that great if it's true? Here's where I got it from and you'll probably figure out what to do with it
https://www.livenewsworld.com/watchcnnlivestream/

**Comment by Dum4G** [comment]
> I give this link a whopping 5 hours left

Actually died in 3 hours

**Comment by LaneSh4d0w** [comment]
> 
> 
> > I give this link a whopping 5 hours left
> 
> Actually died in 3 hours

Welp, was shorter than expected. Those links aren't made to stay sadly...

**Comment by MapGuy11** [comment]
> > > I give this link a whopping 5 hours left
> > 
> > 
> > Actually died in 3 hours
> 
> Welp, was shorter than expected. Those links aren't made to stay sadly...

That MSNBC link doesn't have a token maybe there is one for CNN

**Comment by LaneSh4d0w** [comment]
> 
> 
> > > > I give this link a whopping 5 hours left
> > > 
> > > 
> > > Actually died in 3 hours
> > 
> > 
> > Welp, was shorter than expected. Those links aren't made to stay sadly...
> 
> That MSNBC link doesn't have a token maybe there is one for CNN

Possibly... need to find how that works.

**Comment by Dum4G** [comment]
> That MSNBC link doesn't have a token maybe there is one for CNN

Many sources reffer to a link that returns 404, others are forbidden even with US VPN

**Comment by Dum4G** [comment]
@MapGuy11 you have to see this
https://raw.githubusercontent.com/HelmerLuzo/PlutoTV_HL/1b3169cb928a36ad24b6134a814ab2ed3932daad/tv/PlutoTV_TV_US.m3u

**Comment by LaneSh4d0w** [comment]
I think it's the original CNN. If I remember well, the one Pluto got is the International version.

**Comment by Dum4G** [comment]
> I think it's the original CNN. If I remember well, the one Pluto got is the International version.

I'm starting to assume we've got 3 different CNNs. The one on Pluto shows documentaries, other two live interviews

**Comment by LaneSh4d0w** [comment]
Hmm... probably.

**Comment by trancer1994** [comment]
The Pluto one I don't know what that is, but the one I linked to is the actual US CNN stream as pulled directly from the website. If you want I can also give you the CNN International feed from the same site.

**Comment by Dum4G** [comment]
> The Pluto one I don't know what that is, but the one I linked to is the actual US CNN stream as pulled directly from the website. If you want I can also give you the CNN International feed from the same site.

Can you play any in videoplayers?

**Comment by trancer1994** [comment]
> You may be able to play the cnn us and cnn international feeds in video players like VLC, but not sure about the Pluto feed as I haven't tried it.

**Comment by Dum4G** [comment]
> > You may be able to play the cnn us and cnn international feeds in video players like VLC, but not sure about the Pluto feed as I haven't tried it.

I couldn't get any of your links to work in VLC, even with user-agent. The first link has expired, others return a file in browser, but when VLC establishes a connection it drops immediately.

**Comment by trancer1994** [comment]
Hmm, weird. I'll try all the links I've given you and see what happens on my end. 

Ok so I've tried the third link which comes from turnerlive.warnermediacdn.com and that works fine in my version of VLC, so I'm assuming everything else from there works fine too. cnnlive.warnermediacdn.com I'm assuming also works fine since those links were also pulled from the website.

**Comment by LaneSh4d0w** [comment]
> 
> 
> Hmm, weird. I'll try all the links I've given you and see what happens on my end.
> 
> Ok so I've tried the third link which comes from turnerlive.warnermediacdn.com and that works fine in my version of VLC, so I'm assuming everything else from there works fine too. cnnlive.warnermediacdn.com I'm assuming also works fine since those links were also pulled from the website.

Sounds like it's geo-locked. Tried on mine, got the playlist then instantly cuts off.

**Comment by trancer1994** [comment]
My VLC isn't configured with any proxy though.

________________________________

**Comment by LaneSh4d0w** [comment]
Mine either, but this stream works only for the US.

**Comment by trancer1994** [comment]
But why is it still working for me if it's a geolocked stream and VLC is configured with no proxy?

**Comment by LaneSh4d0w** [comment]
> But why is it still working for me if it's a geolocked stream and VLC is configured with no proxy?

Aren't you American by any chance ?

**Comment by trancer1994** [comment]
No. I am from England.

________________________________

**Comment by LaneSh4d0w** [comment]
Then this is weird
