### ISSUE TITLE
Add: MSNBC

### ISSUE THREAD

**Issue by fotvnetwork** [iptv-org/iptv#3218]
**Channel Name:** MSNBC
**Country:** US
**Language:** English
**External Link (optional):** https://hls.goodgame.ru/manifest/185327_master.m3u8
**Notes (optional):** Link grabbed from a streaming site called Freeintertv

**Comment by MapGuy11** [comment]
Both work with Web Browser Not VLC. Framerate is terrible.

**Comment by Sphinxroot** [comment]
http://stream.tvtap.live:8081/live/us-msnbc.stream/playlist.m3u8

**Comment by trancer1994** [comment]
https://msnbc1.akamaized.net/hls/live/2021744-b/MSNBC0f2497d0/clear/hdntl=exp=1624105752~acl=%2f*~data=hdntl~hmac=9fb1bab29f38a27a900b23bb0e972f60357f4defa4b8bf1eeb015e7ebd3e202d/VIDEO_2_4926000.m3u8 might be tokened though
Or some others: 
https://msnbc1.akamaized.net/hls/live/2021744-b/MSNBC0f2497d0/clear/hdntl=exp=1624105752~acl=%2f*~data=hdntl~hmac=9fb1bab29f38a27a900b23bb0e972f60357f4defa4b8bf1eeb015e7ebd3e202d/master.m3u8
https://msnbc1.akamaized.net/hls/live/2021744/MSNBC0f2497d0/clear/master.m3u8
https://msnbc1.akamaized.net/hls/live/2021744-b/MSNBC0f2497d0/clear/hdntl=exp=1624105752~acl=%2f*~data=hdntl~hmac=9fb1bab29f38a27a900b23bb0e972f60357f4defa4b8bf1eeb015e7ebd3e202d/VIDEO_2_4926000.m3u8
https://msnbc1.akamaized.net/hls/live/2021744/MSNBC0f2497d0/clear/master.m3u8?hdnts=st=1624019349~exp=1624019469~acl=/hls/live/2021744/MSNBC0f2497d0/clear/*~hmac=5c94df3bdc72ada2b73a23e6ca94ec6eb5c7cf929385f35bbe64f11bf0765946 Some of these may be duplicates.

**Comment by MapGuy11** [comment]
https://msnbc1.akamaized.net/hls/live/2021744-b/MSNBC0f2497d0/clear/hdntl=exp=1624105752~acl=%2f*~data=hdntl~hmac=9fb1bab29f38a27a900b23bb0e972f60357f4defa4b8bf1eeb015e7ebd3e202d/master.m3u8
https://msnbc1.akamaized.net/hls/live/2021744/MSNBC0f2497d0/clear/master.m3u8
https://msnbc1.akamaized.net/hls/live/2021744/MSNBC0f2497d0/clear/master.m3u8?hdnts=st=1624019349~exp=1624019469~acl=/hls/live/2021744/MSNBC0f2497d0/clear/*~hmac=5c94df3bdc72ada2b73a23e6ca94ec6eb5c7cf929385f35bbe64f11bf0765946
^ Doesn't Work Others Do

**Comment by Dum4G** [comment]
http://1111296894.rsc.cdn77.org/LS-ATL-54548-10/tracks-v1a1/mono.m3u8

**Comment by MapGuy11** [comment]
> http://1111296894.rsc.cdn77.org/LS-ATL-54548-10/tracks-v1a1/mono.m3u8

Now this one doesn't have a token.
