### ISSUE TITLE
New Zealand Channel Request

### ISSUE THREAD

**Issue by caten0** [iptv-org/iptv#3222]
please add channel tvnz1, 2, duke
https://www.tvnz.co.nz/livetv

**Comment by MapGuy11** [comment]
TVNZ 1: https://d2ce82tpc3p734.cloudfront.net/v1/master/b1f4432f8f95be9e629d97baabfed15b8cacd1f8/TVNZ_1/master.m3u8
TVNZ 2: https://duoak7vltfob0.cloudfront.net/v1/master/b1f4432f8f95be9e629d97baabfed15b8cacd1f8/TVNZ_2/master.m3u8
TVNZ Duke: https://dayqb844napyo.cloudfront.net/v1/master/b1f4432f8f95be9e629d97baabfed15b8cacd1f8/TVNZ_Duke/master.m3u8

(NEED NEW ZELAND IP) 

CREATE PULL REQUEST WITH NOTICE TO THIS THREAD which would be #3222

**Comment by Dum4G** [comment]
@LaneSh4d0w do you have NZ vpn to check?

**Comment by LaneSh4d0w** [comment]
I got NordVPN, so I suppose yeah

**Comment by Dum4G** [comment]
@caten0 please confirm if those work

**Comment by LaneSh4d0w** [comment]
Using NZ IP : 
TVNZ1 : 
![vlcsnap-2021-07-20-22h00m04s705](https://user-images.githubusercontent.com/30985701/126387805-3d5bdac2-a538-464d-a9eb-d60d86bf6c3a.png)

**Comment by LaneSh4d0w** [comment]
Confirmed working for me @Dum4G
