### ISSUE TITLE
NBC Sports Philadelphia

### ISSUE THREAD

**Issue by MapGuy11** [iptv-org/iptv#3224]
**Channel Name:** NBC Sports Philadelphia
**Channel ID:** NBCSportsPhiladelphia.us
**Country:** US
**Language:** English
**External Link (optional):** http://stream.nbcsports.com/rsn/nbcs-philadelphia
**Notes (optional):** The stream has some weird encryption. There is also a plus feed if you can get it cool, but not that is ok. http://stream.nbcsports.com/rsn/nbcs-philadelphia-plus

**Comment by LaneSh4d0w** [comment]
Almost sure this has something to do with https://sp.auth.adobe.com/o/client/register?_=1624026856029 and https://sp.auth.adobe.com/o/client/token?_=1624026856253

**Comment by Dum4G** [comment]
Closed in favor of #3145

**Comment by AntiPontifex** [comment]
Dead issue: please close.
