### ISSUE TITLE
Fix: US ESPN 1 

### ISSUE THREAD

**Issue by Rayshub007** [iptv-org/iptv#3225]
US ESPN 1 has quit opening..

**_Channel Name:_** ESPN 1
**_Broken Link (from playlist):_** https://gma2.blab.email/fs2.m3u8
**_Possible Replacement (optional):_** N/a
**_Notes (optional):_** xxx

**Comment by jkemp814** [comment]
In VLC all four VLC channels remove themselves from the playlist from index.m3u and us.m3u playlist. You can watch them disappear one by one. I was literally watching the channel from the playlist screen. (small video screen to the left of the playlist)

**Comment by Rayshub007** [comment]
> In VLC all four VLC channels remove themselves from the playlist from index.m3u and us.m3u playlists. You can watch them disappear one by one. I was literally watching the channel from the playlist screen. (small video screen to the left of the playlist)

Yes, It was sad to see the channel disappear while watching, Disappeared on the worst time. I hope it gets fixed in an  hour

**Comment by jkemp814** [comment]
I switched to ustv24/7 in a browser. Open picture in picture and resize. Lower resolution though..

**Comment by Rayshub007** [comment]
I tried there as well, All others channels are working but ESPN. lol. I hope we get it through the Ghub

**Comment by jkemp814** [comment]
What's weird is the streams disappearing from the playlist. Did they send something in the stream to do that? I have never seen VLC do that.

**Comment by Rayshub007** [comment]
It even crashed my VLC couple of times when I tried to stream ESPN 1 never had that before.

**Comment by LaneSh4d0w** [comment]
I *think* I have ESPN on one of my Astra playlists. Will need to check again.

**Comment by jkemp814** [comment]
Where do I find Astra playlist? Is it merged into index.m3u?

**Comment by LaneSh4d0w** [comment]
Not yet, those are playlists I and Dum4G found on the Internet that are linked to Astra Satellites control panel. See discussion that talks about it
