### ISSUE TITLE
Fix: Box Hits Uk

### ISSUE THREAD

**Issue by brluk** [iptv-org/iptv#3237]
**_Channel Name:_** Box Hits UK
**_Broken Link (from playlist):_** http://csm-e.tm.yospace.com/csm/extlive/boxplus01,boxhits-desktop.m3u8?yo.up=http://boxtv-origin-elb.cds1.yospace.com/uploads/boxhits/
**_Possible Replacement (optional):_** n/a
**_Notes (optional):_**

**Comment by MapGuy11** [comment]
https://csm-e-boxplus.tls1.yospace.com/csm/extlive/boxplus01,boxhits-alldev.m3u8?yo.up=http://boxtv-origin-elb.cds1.yospace.com/uploads/boxhits/
