### ISSUE TITLE
Fix: The Box UK

### ISSUE THREAD

**Issue by brluk** [iptv-org/iptv#3238]
**_Channel Name:_** The Box UK
**_Broken Link (from playlist):_** http://csm-e.tm.yospace.com/csm/extlive/boxplus01,thebox-desktop.m3u8?yo.up=http://boxtv-origin-elb.cds1.yospace.com/uploads/thebox/
**_Possible Replacement (optional):_** n/a
**_Notes (optional):_**

**Comment by MapGuy11** [comment]
#3237

**Comment by Dum4G** [comment]
Different channel, loads infinitely if desktop is replaced with alldev
