### ISSUE TITLE
Fix: Kerrang UK

### ISSUE THREAD

**Issue by brluk** [iptv-org/iptv#3239]
**_Channel Name:_** Kerrang UK
**_Broken Link (from playlist):_** http://csm-e.tm.yospace.com/csm/extlive/boxplus01,kerrang-desktop.m3u8?yo.up=http://boxtv-origin-elb.cds1.yospace.com/uploads/kerrang/
**_Possible Replacement (optional):_** n/a
**_Notes (optional):_**

**Comment by LaneSh4d0w** [comment]
Basically we would need to get the data from http://boxtv-origin-elb.cds1.yospace.com/uploads/kerrang/

and reconstruct a playlist from it.

**Comment by Dum4G** [comment]
Geoblocked and encrypted now
http://www.boxplus.com/live-tv-guide/?channel=kerrang

**Comment by Sphinxroot** [comment]
http://stream.tvtap.live:8081/live/uk-kerrang.stream/playlist.m3u8  event tvtap doesnt give it anymore it get boomrang
