### ISSUE TITLE
Fix: MTV Live HD

### ISSUE THREAD

**Issue by brluk** [iptv-org/iptv#3240]
**_Channel Name:_** MTV Live HD
**_Broken Link (from playlist):_** http://us1-external-sources.iptvserver.tv:80/kkkrkDp2a9KNwAwGzpb/QT94uK5NNQw4r4Qs/737
**_Possible Replacement (optional):_** n/a
**_Notes (optional):_**

**Comment by Dum4G** [comment]
May not last for long
http://cdnx1.plusx.tv:8880/229/mono.m3u8?token=dawids162751365422222

**Comment by Dum4G** [comment]
http://rec2.distv.net:80/live/ibl/ibl/236.ts
