### ISSUE TITLE
NBC Sports Chicago

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#3242]
**Channel Name:** NBC Sports Chicago
**Country:** US
**Language:** English
**External Link (optional):** https://stream.nbcsports.com/rsn/nbcs-chicago
**Notes (optional)**

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/3145

**Comment by Central302** [comment]
No Longer Needed. I Close This Issuse
