### ISSUE TITLE
CBS East

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#3250]
**Channel Name:** CBS(Not CBSN)
**Country:** US
**Language:** English
**External Link (optional):** https://www.cbs.com/
**Notes (optional):** xxx

**Comment by Dum4G** [comment]
I'm gonna leave it here for tests

#EXTINF:-1 tvg-id="" tvg-logo="http://upload.wikimedia.org/wikipedia/en/thumb/e/ea/KMTV3.png/300px-KMTV3.png" group-title="USA/Canada",CBS 3 Omaha(KMTV)http://content.uplynk.com/channel/328d1434fb51476cb6567c74d5b2cc70.m3u8#EXTINF:-1 tvg-id="" tvg-logo="https://yt3.ggpht.com/vL9xupXA_mlmoorGfPCzYdsSBUdbOndg6rYU1NXVjt-bf8FaP9tkMa8EgeEcO5ytPjIartnfy8Qr" group-title="USA/Canada",CBS 4 Miami(WFOR)http://190.80.3.28/CBS/CBS.isml/index.m3u8#EXTINF:-1 tvg-id="" tvg-logo="http://static.boomtowncdn.com/wp-content/blogs.dir/161/files/2016/10/WRGB_CBS_6_News.svg_.png" group-title="USA/Canada",CBS 6 Albany (WRGB)https://content.uplynk.com/channel/bba3e7da884a49bba96341ecf5128f0f.m3u8#EXTINF:-1 tvg-id="" tvg-logo="http://mediaweb.kirotv.com/photo/2018/09/24/kiro7_header_logo_152x60_13118164_ver1.0.png" group-title="USA/Canada",CBS 7 Seattle(KIRO)http://svc-lvanvato-cxtv-kiro.cmgvideo.com:80/kiro/1864k/index.m3u8#EXTINF:-1 tvg-id="" tvg-logo="http://upload.wikimedia.org/wikipedia/en/thumb/6/69/WHIO-TV_Logo.png/285px-WHIO-TV_Logo.png" group-title="USA/Canada",CBS 7 Ohio WHIO)http://svc-lvanvato-cxtv-whio.cmgvideo.com:80/whio/2596k/index.m3u8#EXTINF:-1 tvg-id="" tvg-logo="http://upload.wikimedia.org/wikipedia/en/thumb/3/3d/WJAX-TV_logo.png/1920px-WJAX-TV_logo.png" group-title="USA/Canada",CBS 47 Jacksonville(WJAX)http://svc-lvanvato-cxtv-wjax.cmgvideo.com/wjax/2564k/index.m3u8#EXTINF:-1 tvg-id="" tvg-logo="http://upload.wikimedia.org/wikipedia/commons/f/f9/CBSN_channel_Logo.png" group-title="USA/Canada",CBSNhttps://cbsn-us-cedexis.cbsnstream.cbsnews.com/out/v1/55a8648e8f134e82a470f83d562deeca/master.m3u8#EXTINF:-1 tvg-id="" tvg-logo="http://upload.wikimedia.org/wikipedia/commons/f/f9/CBSN_channel_Logo.png" group-title="USA/Canada",CSBN New Yorkhttps://cbsn-ny-cedexis.cbsnstream.cbsnews.com/out/v1/ec3897d58a9b45129a77d67aa247d136/master.m3u8#EXTINF:-1 tvg-id="" tvg-logo="http://boston.cbslocal.com/wp-content/uploads/sites/3859903/2019/09/60h-BOS-white-stacked.png" group-title="USA/Canada",CBSN Bostonhttps://dai.google.com/linear/hls/event/26FJK7wRSo6RhPsK70XS_w/master.m3u8?iu=/4128/CBS.BOSTON.OTT#EXTINF:-1 tvg-id="" tvg-logo="http://minnesota.cbslocal.com/wp-content/uploads/sites/15909630/2019/12/60h-MINN-white-stacked.png" group-title="USA/Canada",CBSN Minnesotahttps://dai.google.com/linear/hls/event/zcWPVCfURNSPxeidcckQLA/master.m3u8?iu=/4128/CBS.MINN.OTT#EXTINF:-1 tvg-id="" tvg-logo="http://philadelphia.cbslocal.com/wp-content/uploads/sites/15116066/2012/03/30h-PHILLY-white-horizontal.png" group-title="USA/Canada",CBSN Phillyhttps://dai.google.com/linear/hls/event/Xu-ITJ2GTNGaxGn893mmWg/master.m3u8?iu=/4128/CBS.PHILLY.OTT#EXTINF:-1 tvg-id="" tvg-logo="http://losangeles.cbslocal.com/wp-content/uploads/sites/14984641/2019/09/60h-LA-white-stacked.png" group-title="USA/Canada",CBSN Los Angeleshttps://dai.google.com/linear/hls/event/TxSbNMu4R5anKrjV02VOBg/master.m3u8?iu=/4128/CBS.LA.OTT#EXTINF:-1 tvg-id="" tvg-logo="http://sanfrancisco.cbslocal.com/wp-content/uploads/sites/15116056/2019/11/60h-BAY-white-stacked.png" group-title="USA/Canada",CBSN Bay Areahttps://dai.google.com/linear/hls/event/VE8b4n-YStusEGv5Z2NmsQ/master.m3u8?iu=/4128/CBS.SF.OTT#EXTINF:-1 tvg-ID="CBC.News" tvg-logo="https://static.epg.best/ca/CBCNews.ca.png" group-title="USA/Canada",CBC Newshttps://livecbcdai-i.akamaihd.net/hls/live/567245/event2/CBCNN/master6.m3u8|X-Forwarded-For=24.37.42.20#EXTINF:-1  tvg-ID="CBC.CA" tvg-logo="https://static.epg.best/ca/CBC.ca.png" group-title="USA/Canada",CBC Ottawahttps://cbclivedai5-i.akamaihd.net/hls/live/567235/event2/CBOT/master5.m3u8|X-Forwarded-For=24.37.42.20#EXTINF:-1  tvg-ID="CBC.CA" tvg-logo="https://static.epg.best/ca/CBC.ca.png" group-title="USA/Canada",CBC Quebechttps://cbclivedai3-i.akamaihd.net/hls/live/566976/event2/CBMT/master5.m3u8|X-Forwarded-For=24.37.42.20#EXTINF:-1  tvg-ID="CBC.CA" tvg-logo="https://static.epg.best/ca/CBC.ca.png" group-title="USA/Canada",CBC Ontariohttps://cbclivedai5-i.akamaihd.net/hls/live/567235/event2/CBOT/master5.m3u8|X-Forwarded-For=24.37.42.20

**Comment by fotvnetwork** [comment]
From TVtap (it changes feeds, however):
http://stream.tvtap.live:8081/live/us-cbs.stream/chunks.m3u8

**Comment by MapGuy11** [comment]
> From TVtap (it changes feeds, however):
> http://stream.tvtap.live:8081/live/us-cbs.stream/chunks.m3u8

That is CBSN

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/3145

**Comment by Dum4G** [comment]
Not 24/7?
https://content.uplynk.com/channel/0123b306191a4307a31b9fb573213fd3.m3u8

**Comment by Central302** [comment]
It Looks Like No Way To add CBS(I Own Only mybtv m3u8). I Close This Issuse.
