### ISSUE TITLE
Main Sports m3u link is broken

### ISSUE THREAD

**Issue by yonescat** [iptv-org/iptv#3251]
**_Broken Link (from playlist):_https://iptv-org.github.io/iptv/categories/sport.m3u
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** xxx

**Comment by Dum4G** [comment]
We have rename Sport category to Sports a long time ago. Use https://iptv-org.github.io/iptv/categories/sports.m3u

**Comment by yonescat** [comment]
Great, please when you get the chance, update the link on the main GitHub page, for newbies like me.

Cheers,

**Comment by freearhey** [comment]
@yonescat The link on the home page has already been updated:

![image](https://user-images.githubusercontent.com/7253922/122767223-16482700-d2ab-11eb-80df-51ce7d866609.png)

**Comment by yonescat** [comment]
not on this page: https://github.com/iptv-restream/iptv-channels

![image](https://user-images.githubusercontent.com/12151614/122838254-942d2200-d2ed-11eb-8949-928954b1c86f.png)

**Comment by freearhey** [comment]
@yonescat we do not control this page
