### ISSUE TITLE
Fix: ESPN Links Broken

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3257]
**_Channel Name:_** ESPN
**_Broken Link (from playlist):_** https://gma2.blab.email/fs2.m3u8
**_Possible Replacement (optional):_**
**_Notes (optional):_** fs2.m3u8 for ESPN. None of the ESPN work.

**Comment by Dum4G** [comment]
Duplicate of https://github.com/iptv-org/iptv/issues/3225

**Comment by jkemp814** [comment]
I was trying to report those links still do not work. The ESPN link is also named fs2.m3u8

**Comment by jkemp814** [comment]
Your input can't be opened:
VLC is unable to open the MRL 'https://gma2.blab.email/fs2.m3u8'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'https://gma2.blab.email/espn2.m3u8'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'https://gma2.blab.email/espnews.m3u8'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'https://gma2.blab.email/espnu.m3u8'. Check the log for details.

**Comment by Dum4G** [comment]
I have updated those links today, but those will become available in generated playlists only at midnight. espnews.m3u8 is sadly a goner

**Comment by jkemp814** [comment]
Oh okay, thanks for responding.

**Comment by Kabouik** [comment]
It seems the new URLs are not all working though, ESPN fails for instance.
