### ISSUE TITLE
Fix: jp.m3u

### ISSUE THREAD

**Issue by shemugeorge1224** [iptv-org/iptv#3272]
According to https://github.com/iptv-org/iptv/issues/1938, Tokyo MX (The other one) and Sun TV is already listed but I don't see it in the .m3u

**Comment by LaneSh4d0w** [comment]
MX 2 and Sun ?

https://github.com/iptv-org/iptv/blob/848d154c67b07a6f11563d51e545e4576d2d05bf/channels/jp.m3u#L44-L45

Sun TV however doesn't seem to be there indeed.

**Comment by Dum4G** [comment]
http://122.155.180.8:5021/live/320

SunTV it seems. Can't be played in VLC

**Comment by Dum4G** [comment]
Tokyo MX (The other one) has never been listed and somehow only works in a browser for now

**Comment by LaneSh4d0w** [comment]
> 
> 
> http://122.155.180.8:5021/live/320
> 
> SunTV it seems. Can't be played in VLC

Indeed, stuttered audio

**Comment by Dum4G** [comment]
There's nothing we can do until public sources will be discovered. Closed in favor of 
https://github.com/iptv-org/iptv/issues/1938
