### ISSUE TITLE
Fix: AT-X

### ISSUE THREAD

**Issue by BlueDia411** [iptv-org/iptv#3273]
You Need to change AT-X streaming location because when I watch the AT-X on media player I'm using it says 
"Your input can't be opened 
VLC is unable to open the MRL 'https://sub2.neetball.net/live/neet.m3u8'."
i try to open neetball.net when i click link the first link i need to login first.

**_Channel Name:_** AT-X
**_Broken Link (from playlist):_** https://sub2.neetball.net/live/neet.m3u8
**_Possible Replacement (optional):_** https://sub2.neetball.net/live/cd1212.m3u8
**_Notes (optional):_** ~

**Comment by Dum4G** [comment]
Thanks for the contribution!

**Comment by BlueDia411** [comment]
> Thanks for the contribution! Maybe it was some temporary downtime since both links do work for me now

ah now i can access it again,
Thank you for the information
