### ISSUE TITLE
Dhinchaak Tv

### ISSUE THREAD

**Issue by movies4worlds** [iptv-org/iptv#3275]
**Channel Name:** xxx
**Country:** xxx
**Language:** xxx
**External Link (optional):** xxx
**Notes (optional):** xxx

**Comment by movies4worlds** [comment]
Plz add

**Comment by Dum4G** [comment]
Please follow the [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by movies4worlds** [comment]
Sir plzx add
