### ISSUE TITLE
Fix: ESPN

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3280]
**_Channel Name:_** ESPN
**_Broken Link (from playlist):_** http://164.68.124.111/fs2.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Stream just sits trying to connect, the other two streams work fine.

**Comment by Dum4G** [comment]
I'm starting to hate this source. ESPN1 works from a direct link that can be obtained from the m3u8, others do not play in VLC that way. I can't predict reliability of that source any longer. What would they do tomorrow to s***w us all?

**Comment by Dum4G** [comment]
I've got the direct link for ESPN1 but other channels do not work the same way. I can't tell how reliable the source would be in the coming days. What else would they do to scr*w us all?

**Comment by pvonmoradi** [comment]
ESPN 2 (http://164.68.124.111/espn2.m3u8) is also quite unstable.

**Comment by Apesbrain** [comment]
Just adding to the request. Maybe rename it to **espn.m3u8** just for consistency.  Thanks.

**Comment by Dum4G** [comment]
> Just adding to the request. Maybe rename it to **espn.m3u8** for consistency. Thanks.

Also returns an empty file sadly

**Comment by fotvnetwork** [comment]
http://stream2.grandma.fit/fs2.m3u8

**Comment by craftsman86** [comment]
That adress function
