### ISSUE TITLE
Add: Kurdsat

### ISSUE THREAD

**Issue by yonescat** [iptv-org/iptv#3283]
**Channel Name:** Kurdsat
**Country:** Iraq
**Language:** Kurdish
**External Link (optional):** https://www.lyngsat-stream.com/tvchannels/iq/Kurdsat.html
https://www.lyngsat-stream.com/tvchannels/iq/Kurdsat-News.html
**Notes (optional):** xxx

**Comment by Dum4G** [comment]
Check Iraqi playlist

**Comment by Sphinxroot** [comment]
closing channel are in Iraq playlist
