### ISSUE TITLE
Add: WCAT

### ISSUE THREAD

**Issue by shawnshyguy** [iptv-org/iptv#3289]
**Channel Name:** WCAT 3 / 15 / 22
**Country:** USA
**Language:** EN
**External Link (optional):**
 - index: https://www.wcat-tv.org/watch-wcat-live/
 - channel 3 m3u8: https://frontdoor.wcat-tv.org:8787/live/live.m3u8
 - channel 15 m3u8: https://edu-wcat.azureedge.net/live/live.m3u8 (seemingly not 24/7)
 - channel 22 m3u8: https://frontdoor.wcat-tv.org:8686/live/live.m3u8

**Notes (optional):**
Public broadcast channels for Winthrop, MA. Streams don't seem to want to play in VLC, but work in MPV. As noted, channel 15 doesn't seem to be 24/7.

**Comment by Sphinxroot** [comment]
all stream  work   both vlc and kodi  

channel 15  will get black screen until it broadcast live 

random Schedule of

Committee Meeting 
Weekly Newscast
other

**Comment by trancer1994** [comment]
Should we not close this? The m3u8 links have been given already but I guess they need to be added to us.m3u8.
