### ISSUE TITLE
Fix: Press TV English (720)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3294]
**_Channel Name:_** Press TV English (720)
**_Broken Link (from playlist):_** https://live.presstv.com/liveprs/smil:liveprs/playlist.m3u8
**_Possible Replacement (optional):_** https://live.presstv.ir/liveprs/smil:liveprs/chunklist_w1892862255_b644100_slen.m3u8
**_Notes (optional):_** FBI seized the presstv.com domain. It's now presstv.ir

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | https://live.presstv.ir/liveprs/smil:liveprs/playlist.m3u8
-- | --
mediaManifest | https://live.presstv.ir/liveprs/smil:liveprs/chunklist_w2032516952_b944100_slen.m3u8


</body>
</html>

**Comment by Sphinxroot** [comment]
https://french.presstv.ir/live
https://live1.presstv.ir/live/presstvfr/index.m3u8

**Comment by Sphinxroot** [comment]
close in favor of #3296
