### ISSUE TITLE
Fix: Дом Кино Премиум HD peers.tv

### ISSUE THREAD

**Issue by Ilia1** [iptv-org/iptv#3299]
Channel Name: Дом Кино Премиум HD
Broken Link (from playlist): http://msk3.peers.tv/streaming/dom_kino_premium/16/gvh1w/playlist.m3u8
Notes (optional): May be broken all peers.tv stream
Caption on the screenshot: dear viewer, to continue watching, install the peers.tv application or use the peers.tv portal
![Снимок экрана в 2021-06-25 17-31-58](https://user-images.githubusercontent.com/16576224/123425691-e4e99700-d5db-11eb-971e-d57ccaad84da.png)

**Comment by Dum4G** [comment]
I can "fix" it in a way that it will be broadcasted in 360p. That's the only reliable source I can find. Would you be satisfied?

**Comment by LaneSh4d0w** [comment]
> 
> 
> I can "fix" it in a way that it will be broadcasted in 360p. That's the only reliable source I can find. Would you be satisfied?

Your source contains a 720p HD stream that works fine too.
