### ISSUE TITLE
Fix: iptv-org.github.io links all 404

### ISSUE THREAD

**Issue by fearlesschicken** [iptv-org/iptv#3323]
All the iptv-org.github.io/iptv urls are now 404

**Comment by heroku-miraheze** [comment]
What do you mean?

**Comment by heroku-miraheze** [comment]
The links is working.

**Comment by heroku-miraheze** [comment]
#3326

**Comment by deal1949** [comment]
刚想说

**Comment by freearhey** [comment]
Investigating.

**Comment by freearhey** [comment]
Here's what I've found out so far.

GitHub moved all settings for GitHub Pages to a separate tab:
![image](https://user-images.githubusercontent.com/7253922/123636352-6d0ead00-d825-11eb-9127-f76624067255.png)

In the new tab it says that the GitHub Pages have been disabled and there's nothing else on this page.
![image](https://user-images.githubusercontent.com/7253922/123636489-9cbdb500-d825-11eb-974e-647d28d10e24.png)

**Comment by freearhey** [comment]
Solved.

For anyone who encounters the same problem. 

In order for the new Pages tab to display the settings, it is mandatory that `Organization Settings / Member Privileges / Pages creation` must be active.

![image](https://user-images.githubusercontent.com/7253922/123638127-78fb6e80-d827-11eb-857b-84f4d27c9880.png)

In this case, all settings should be displayed as before.

![image](https://user-images.githubusercontent.com/7253922/123638581-ffb04b80-d827-11eb-8378-ac95c62be0df.png)
