### ISSUE TITLE
Fox Business

### ISSUE THREAD

**Issue by Ulter32** [iptv-org/iptv#3335]
**Channel Name:** FOX Business Chnnel
**Country:** USA
**Language:** English
**External Link (optional):**
https://www.foxbusiness.com/
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | https://h3.ustvgo.la/FoxBusiness/myStream/chunks.m3u8?nimblesessionid=20625831&wmsAuthSign=c2VydmVyX3RpbWU9Ni8zMC8yMDIxIDY6NTM6MDQgQU0maGFzaF92YWx1ZT1WYkpFMEEzM3UxUk1zVnlUZTQ1cSt3PT0mdmFsaWRtaW51dGVzPTI0MA==
-- | --
mediaManifest | https://h3.ustvgo.la/FoxBusiness/myStream/chunks.m3u8?nimblesessionid=20625831&wmsAuthSign=c2VydmVyX3RpbWU9Ni8zMC8yMDIxIDY6NTM6MDQgQU0maGFzaF92YWx1ZT1WYkpFMEEzM3UxUk1zVnlUZTQ1cSt3PT0mdmFsaWRtaW51dGVzPTI0MA==
pageUrl | https://ustvgo.tv/fox-business-live-streaming-free/
referrer | https://ustvgo.tv/clappr.php?stream=FoxBusiness


</body>
</html>

but token so wmsAuthSign=  will change daily

**Comment by Dum4G** [comment]
http://www.freeintertv.com/view/id-2192 tokenized but I'm sure it can be obtained somehow

**Comment by LaneSh4d0w** [comment]
> 
> masterManifest 	https://h3.ustvgo.la/FoxBusiness/myStream/chunks.m3u8?nimblesessionid=20625831&wmsAuthSign=c2VydmVyX3RpbWU9Ni8zMC8yMDIxIDY6NTM6MDQgQU0maGFzaF92YWx1ZT1WYkpFMEEzM3UxUk1zVnlUZTQ1cSt3PT0mdmFsaWRtaW51dGVzPTI0MA==
> mediaManifest 	https://h3.ustvgo.la/FoxBusiness/myStream/chunks.m3u8?nimblesessionid=20625831&wmsAuthSign=c2VydmVyX3RpbWU9Ni8zMC8yMDIxIDY6NTM6MDQgQU0maGFzaF92YWx1ZT1WYkpFMEEzM3UxUk1zVnlUZTQ1cSt3PT0mdmFsaWRtaW51dGVzPTI0MA==
> pageUrl 	https://ustvgo.tv/fox-business-live-streaming-free/
> referrer 	https://ustvgo.tv/clappr.php?stream=FoxBusiness
> 
> but token so wmsAuthSign= will change daily

POST request to https://ustvgo.tv/data.php with query string "stream=FoxBusiness" gives you the link you have.

**Comment by trancer1994** [comment]
https://247preview.foxbusiness.com/hls/live/2020026/fbnv3preview/index.m3u8
Official feed from website

**Comment by Dum4G** [comment]
> https://247preview.foxbusiness.com/hls/live/2020026/fbnv3preview/index.m3u8
> Official feed from website

144p

**Comment by Dum4G** [comment]
https://247.foxbusiness.com/hls/live/2003756/FBNHLSv3/master.m3u8 exists but access denied

**Comment by Sphinxroot** [comment]
https://247preview.foxbusiness.com/hls/live/2020026/fbnv3preview/index.m3u8 load in vlc but not in kodi 


those load in kodi
https://247preview.foxbusiness.com/hls/live/2020026/fbnv3preview/primary_300.m3u8
https://247preview.foxbusiness.com/hls/live/2020026/fbnv3preview/primary_160.m3u8

those wont in kodi 
https://247preview.foxbusines.com/hls/live/2020027-b/fbnv3preview/backup_300.m3u8
https://247preview.foxbusines.com/hls/live/2020027-b/fbnv3preview/backup_160.m3u8

**Comment by Dum4G** [comment]
> POST request to https://ustvgo.tv/data.php with query string "stream=FoxBusiness" gives you the link you have.

Would you be kind to automate this for us? We're about to use 144p link without sound as an alternative and that is ridiculous

**Comment by LaneSh4d0w** [comment]
Once i'm finished with the work I have, sure.

**Comment by trancer1994** [comment]
Are you saying the link I posted doesn't have sound?

**Comment by trancer1994** [comment]
@Dum4G There's also this link from the same site https://247preview.foxbusiness.com/hls/live/2020026/fbnv3preview/primary_300.m3u8 or https://247preview.foxbusiness.com/hls/live/2020026/fbnv3preview/primary.m3u8, but it seems the best quality you'll get using those links is 300p. I think.

**Comment by Dum4G** [comment]
VLC offers me 144p and no sound on every link from index file. Let's wait for Laneshadow's solution

**Comment by trancer1994** [comment]
That's weird my links should have no sound, they came from the same source Fox News came from, which does have sound.

________________________________

**Comment by LaneSh4d0w** [comment]
https://iptv-all.lanesh4d0w.codes/united-states/foxbusiness

Forbidden on my side.

**Comment by Dum4G** [comment]
> Forbidden on my side.

Maybe you need to get nimblesession id

**Comment by LaneSh4d0w** [comment]
Let me see if I can take that.

**Comment by Dum4G** [comment]
Or maybe it knows that http referrer is different

**Comment by LaneSh4d0w** [comment]
It's a fixed referrer to USTVGO's clappr

**Comment by Sphinxroot** [comment]
720p

masterManifest
https://www.streamaway.net/us/fox-business/index.m3u8
mediaManifest
https://www.streamaway.net/us/fox-business/tracks-v1a1/mono.m3u8
mediaManifest 2
https://www.streamaway.net/us/fox-business/tracks-t4/mono.m3u8

referrer needed to work

referrer	
https://www.streamaway.net/english/Fox-business.php

**Comment by LaneSh4d0w** [comment]
Hmm... that won't be easy. Referrer links aren't the best to deal with, especially when it's linked to the M3U

**Comment by Sphinxroot** [comment]
on kodi not a problem but vlc its a pain , i think nintendo  have a clue i think he already talk about it

**Comment by Dum4G** [comment]
#EXTINF:-1 tvg-id="FBN" group-title="Lifestyle", FOX BUSINESS
#EXTVLCOPT:http-user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
#EXTVLCOPT:http-referrer="https://www.streamaway.net/english/Fox-business.php"
https://www.streamaway.net/us/fox-business/index.m3u8

That setup is the first thing I managed to do. No luck

**Comment by Dum4G** [comment]
In fact, it doesn't even play on the website to me, at least without proper VPN

**Comment by Sphinxroot** [comment]
in kodi 

https://i.imgur.com/dImQZ3n.png

#EXTINF:-1,Fox-business
https://www.streamaway.net/us/fox-business/index.m3u8|Referer=https://www.streamaway.net/english/Fox-business.php

**Comment by Dum4G** [comment]
@LaneSh4d0w maybe you can investigate a script that generates a token here
http://www.freeintertv.com/view/id-2192

**Comment by fotvnetwork** [comment]
Can you guys check this one:
http://loginto.live:80/trial31/DhphTBDC65/461

**Comment by Dum4G** [comment]
We don't approve temporal links. Every source should be more or less public and official

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/198d0527f073c81119ccceaebdede8e79f542028/streams/us.m3u#L468-L469

**Comment by LaneSh4d0w** [comment]
Flussonic Streaming Server block error.

**Comment by LaneSh4d0w** [comment]
https://247.foxbusiness.com/hls/live/2003756/FBNHLSv3/master.m3u8 geoblock

**Comment by Central302** [comment]
Official Stream is Useless, Even in US IP,
![458E2B0C-B15A-4845-9BA7-8C2143404059](https://user-images.githubusercontent.com/86145713/185724485-5c5450db-75b2-4305-a345-725be1e95383.jpeg)
