### ISSUE TITLE
Fix: CNN (newly added)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3343]
**_Channel Name:_** CNN
**_Broken Link (from playlist):_** http://stream.tvtap.live:8081/live/us-cnn.stream/playlist.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Newly added stream has no audio.

**Comment by jkemp814** [comment]
Video is rock solid. No audio.

**Comment by jkemp814** [comment]
The CNN stream is broadcasting CNN International now. No audio still. It was initially showing the U.S. stream when first streamed.

**Comment by Dum4G** [comment]
I have both audio and sound, doesn't see the word International anywhere
![image](https://user-images.githubusercontent.com/5430116/124104081-94a28700-da6a-11eb-9777-64d952a8a9ef.png)

**Comment by jkemp814** [comment]
Now I have both audio and video. Video sputtering in both VLC and FFplay, but much smoother in FFplay.

[hls @ 0x7f3684000b80] Skip ('#EXT-X-DISCONTINUITY')
[http @ 0x7f3684031e00] Opening 'http://stream.tvtap.live:8081/live/us-cnn.stream/l_193830391_17_298.ts?nimblesessionid=9546357730' for reading
[mpegts @ 0x7f368400ce80] DTS 1530 < 19351710 out of orderB f=0/0   
[hls @ 0x7f3684000b80] DTS 1530 < 19351710 out of order
[http @ 0x7f36840098c0] Opening 'http://stream.tvtap.live:8081/live/us-cnn.stream/chunks.m3u8?nimblesessionid=9546357730' for reading
[hls @ 0x7f3684000b80] Skip ('#EXT-X-VERSION:3')B sq=    0B f=1/1   
[hls @ 0x7f3684000b80] Cannot get correct #EXTINF value of segment http://stream.tvtap.live:8081/live/us-cnn.stream/l_193830391_209899_297.ts?nimblesessionid=9546357730, set to default value to 1ms.
[hls @ 0x7f3684000b80] Skip ('#EXT-X-DISCONTINUITY')
