### ISSUE TITLE
Fix: CNN (existing stream)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3344]
**_Channel Name:_** CNN
**_Broken Link (from playlist):_** http://54.251.134.121:1935/live/15273.sdp/02.m3u8
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** Other CNN will not connect. Tried then skips to next stream.

**Comment by jkemp814** [comment]
[tcp @ 0x7f47280045c0] Connection to tcp://54.251.134.121:1935 failed: Connection timed out
http://54.251.134.121:1935/live/15273.sdp/02.m3u8: Connection timed out
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0

**Comment by Dum4G** [comment]
That link is not even in US playlist. Where did you get this from?

**Comment by trancer1994** [comment]
Unable to connect to 54.251.134.121:1935
The remote host or network may be down.
Please try the request again.

**Comment by Dum4G** [comment]
Identified as CNN Phillipines by Google and since we have a replacement source for it, I'm closing this
