### ISSUE TITLE
Add: TLC

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3350]
**Channel Name:** TLC
**Country:** USA
**Language:** English
**External Link (optional):** [blacklisted]
**Notes (optional):** Works in both VLC and FFplay

**Comment by Dum4G** [comment]
Just send an entire bozztv playlist

**Comment by Dum4G** [comment]
Blacklisted https://github.com/iptv-org/iptv/blob/master/scripts/blacklist.json
