### ISSUE TITLE
Add: TruTV (West)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3353]
**Channel Name:** TruTV (West)
**Language:** English
**External Link (optional):** https://tve-live-lln.warnermediacdn.com/hls/live/2023178/truwest/slate/VIDEO_0_3564000.m3u8
**Notes (optional):** Works in both VLC and FFplay

**Comment by fotvnetwork** [comment]
temporary link:
http://loginto.live:80/trial31/DhphTBDC65/1138
