### ISSUE TITLE
Add: TruTV (East)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3354]
**Channel Name:** TruTV (East)
**Country:** USA
**Language:** English
**External Link (optional):** https://tve-live-lln.warnermediacdn.com/hls/live/2023176/trueast/slate/VIDEO_0_3564000.m3u8
**Notes (optional):** Works both in VLC and FFplay

**Comment by fotvnetwork** [comment]
temporary link:
http://loginto.live:80/trial31/DhphTBDC65/1139
