### ISSUE TITLE
Add: TNT (West)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3356]
**Channel Name:** TNT (West)
**Country:** USA
**Language:** English
**External Link (optional):** https://tve-live-lln.warnermediacdn.com/hls/live/2023170/tntwest/slate/VIDEO_0_3564000.m3u8
**Notes (optional):** Works in both VLC and FFplay

**Comment by fotvnetwork** [comment]
temporary link:
http://loginto.live:80/trial31/DhphTBDC65/1141
