### ISSUE TITLE
Be Junior

### ISSUE THREAD

**Issue by zupersponge** [iptv-org/iptv#3361]
**Channel Name:** beJunior
**Channel ID:** BeJunior.qa
**Country:** (Qatar?)
**Language:** Arabic & English
**External Link:** 
**Notes (optional):** Not found a link yet, I will respond to this thread if I find one. (if someone else has also requested this channel, you may close my thread)

**Comment by 129612231-scripts** [comment]
#EXTINF:-1 tvg-id="bejunior.tv" tvg-name="VIP AR: beIN Junior HD" tvg-logo="" group-title="BEIN MEDIA",VIP AR: beJunior HD
http://31.220.3.234:22461/crdavis447735@gmail.com/4zAWw3tj24/36821

I found it!

**Comment by LaneSh4d0w** [comment]
I confirm it's a Qatari channel. beJunior is linked to the beIN Media Group channels.

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/1956

**Comment by freearhey** [comment]
Closed in favor of #12291
