### ISSUE TITLE
Add: TCM (Turner Classic Movies)

### ISSUE THREAD

**Issue by MapGuy11** [iptv-org/iptv#3366]
**Channel Name:** TCM (Turner Classic Movies)
**Country:** USA
**Language:** English
**External Link (optional):** https://www.tcm.com/watchtcm/livestream
**Notes (optional):** East Preferably

**Comment by Dum4G** [comment]
https://ustv247.tv/turner-classic-movies/

**Comment by MapGuy11** [comment]
> https://ustv247.tv/turner-classic-movies/

I was wondering since it's a Turner network like CNN there is a TVE Stream

**Comment by Dum4G** [comment]
#EXTINF:-1 tvg-id="TurnerClassicMovies.us" tvg-name="TCM - East" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/TCM_logo.svg/320px-TCM_logo.svg.png" group-title="General" tvg-shift="-4",TCM - East
https://tve-live-lln.warnermediacdn.com/hls/live/572111/tcme/aes_slate/VIDEO_0_3564000.m3u8
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="TCM - West" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/TCM_logo.svg/320px-TCM_logo.svg.png" group-title="General" tvg-shift="-4",TCM - West
https://tve-live-lln.warnermediacdn.com/hls/live/572112/tcmw/aes_slate/VIDEO_0_3564000.m3u8

@MapGuy11

**Comment by MapGuy11** [comment]
@Dum4G 404 :(

**Comment by jkemp814** [comment]
#3403 #3405

**Comment by MapGuy11** [comment]
> #3403 #3405 

They both work thanks!
