### ISSUE TITLE
Fix: Telemundo 40 Arizona (720p)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3369]
**_Channel Name:_** Telemundo 40 Arizona (720p)
**_Broken Link (from playlist):_** https://ktazlive-lh.akamaihd.net/i/KTAZ_LIVE1@183609/master.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Doesn't connect. 
[https @ 0x7f7568001780] HTTP error 400 Bad Requestq=    0B f=0/0   
https://ktazlive-lh.akamaihd.net/i/KTAZ_LIVE1@183609/master.m3u8: Server returned 400 Bad Request

**Comment by MapGuy11** [comment]
How is this?
https://streams.the6tv.duckdns.org:2443/locals/Pheonix/ktaz-dt1.m3u8

**Comment by LaneSh4d0w** [comment]
> 
> 
> How is this?
> https://streams.the6tv.duckdns.org:2443/locals/Pheonix/ktaz-dt1.m3u8

Works for me.
![vlcsnap-2021-07-02-18h34m37s873](https://user-images.githubusercontent.com/30985701/124304573-2b9f3a00-db64-11eb-9612-c43386ca0d1c.png)

**Comment by jkemp814** [comment]
It works in FFplay but VLC skips to next channel in play list.

Here is the message output in VLC:

access error: HTTP 400 error
adaptive info: Changing stream format Unknown -> Unknown
adaptive info: Encountered discontinuity
mpeg4audio info: AAC channels: 1 samplerate: 22050
faad warning: decoded zero sample
main error: buffer deadlock prevented
qt warning: orphaned video window
pulse warning: starting late (-33378 us)
main warning: playback way too early (-151492): playing silence
vaapi_filters warning: Using SW chroma filter for 224x128 VAOP -> I420
avcodec info: Using NVIDIA VDPAU Driver Shared Library 455.45.01 Thu Nov 5 22:54:01 UTC 2020 for hardware decoding
ts warning: discontinuity received 0x1 instead of 0x4 (pid=0)
ts error: libdvbpsi error (PSI decoder): TS discontinuity (received 1, expected 4) for PID 0
ts warning: discontinuity received 0x0 instead of 0x4 (pid=4096)
ts error: libdvbpsi error (PSI decoder): TS discontinuity (received 0, expected 4) for PID 4096
ts warning: discontinuity received 0x2 instead of 0x5 (pid=0)
ts error: libdvbpsi error (PSI decoder): TS discontinuity (received 2, expected 5) for PID 0
ts warning: discontinuity received 0x0 instead of 0x4 (pid=4096)
ts error: libdvbpsi error (PSI decoder): TS discontinuity (received 0, expected 4) for PID 4096
mpeg4audio info: AAC channels: 2 samplerate: 22050

**Comment by LaneSh4d0w** [comment]
I don't think this issue is from MapGuy's part, I certainly think it's the server that hosts the channel that has some slight issues.

**Comment by jkemp814** [comment]
Oh, okay. I can still watch it.
