### ISSUE TITLE
Fix: 80s Loop (1080p)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3372]
**_Channel Name:_** Fix: 80s Loop (1080p)
**_Broken Link (from playlist):_** https://loop-80s-1.roku.wurl.com/manifest/playlist.m3u8
**_Possible Replacement (optional):_** https://afcfc395f1dd41bb8218453983e63b9f.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Roku_Loop80s-1/playlist.m3u8
**_Notes (optional):_** Doesn't connect
[tcp @ 0x7f0548004c40] Failed to resolve hostname loop-80s-1.roku.wurl.com: Name or service not known
https://loop-80s-1.roku.wurl.com/manifest/playlist.m3u8: Input/output error

**Comment by MapGuy11** [comment]
https://afcfc395f1dd41bb8218453983e63b9f.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Roku_Loop80s-1/playlist.m3u8

**Comment by MapGuy11** [comment]
@jkemp814 Just Create Pull Request I'll Approve

**Comment by Dum4G** [comment]
Weird, it can be found on the therokuchannel.roku.com still. I have added links like the one above from Roku origin yesterday, so probably it's in the playlist already

**Comment by jkemp814** [comment]
There are two 80s Loop in the playlist. East and West. How do I know which one is which?

**Comment by Dum4G** [comment]
It says east and west in the link itself and maybe I should specify that. They did something to 80s link but not every other channel

**Comment by jkemp814** [comment]
I see that now. But the original broken link doesn't have that. That's why I'm confused on which one gets updated.

**Comment by jkemp814** [comment]
I'll wait until the playlist update

**Comment by Dum4G** [comment]
> https://afcfc395f1dd41bb8218453983e63b9f.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Roku_Loop80s-1/playlist.m3u8

{"message":"failed to generate manifest: Unable to obtain template playlist. sessionId:[c19b15ed-c614-49dc-83e9-24fcd5c5171a]"}

**Comment by jkemp814** [comment]
It does play. But once in awhile it throws an error ststaing:

[https @ 0x7f082c015000] Cannot reuse HTTP connection for different host: loop-80s-2-us.roku.wurl.tv:-1 != afcfc395f1dd41bb8218453983e63b9f.mediatailor.us-east-1.amazonaws.com:-1

**Comment by Dum4G** [comment]
Great find. At least I can fix the main link now
