### ISSUE TITLE
Add: elnueve

### ISSUE THREAD

**Issue by l31N4D1zz1** [iptv-org/iptv#3373]
**Channel Name:** elnueve
**Country:** Argentina
**Language:** Español
**External Link (optional):** https://www.elnueve.com.ar/en-vivo/
**Notes (optional):** xxx

**Comment by Dum4G** [comment]
is iut something that changes daily? @LaneSh4d0w @Sphinxroot

**Comment by LaneSh4d0w** [comment]
Indeed @Dum4G

**Comment by Dum4G** [comment]
Have you given up on https://github.com/iptv-org/iptv/issues/2870#issuecomment-850651601?
@LaneSh4d0w

**Comment by LaneSh4d0w** [comment]
Yeah, even the IUT generation seems to be tokened.

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/3064
