### ISSUE TITLE
Fix: Absolute Reality by WEtv

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3374]
**_Channel Name:_** Absolute Reality by WEtv
**_Broken Link (from playlist):_** https://amc-absolutereality-1.plex.wurl.com/manifest/playlist.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Does not connect. There is another stream with similar name that does work.
Absolute Reality by WETV
https://amc-absolutereality-1.samsung.wurl.com/manifest/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
If I'm not mistaking, I think that link is already in the playlist.
