### ISSUE TITLE
Fix: Adult Swim

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3376]
**_Channel Name:_** Adult Swim
**_Broken Link (from playlist):_** http://adultswimhls-i.akamaihd.net/hls/live/238460/adultswim/main/1/master.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Does not connect.
[http @ 0x7fe96000efc0] HTTP error 404 Not FoundB sq=    0B f=0/0   
[hls @ 0x7fe960000b80] parse_playlist error Server returned 404 Not Found [http://adultswimhls-i.akamaihd.net/hls/live/238460/adultswim/main/1/master_Layer0.m3u8]

There is another stream that do connect that does work.
Adult Swim (1080p)
https://adultswimtv.warnermediacdn.com/hls/live/2007031/livestream/master.m3u8

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
