### ISSUE TITLE
Fix: Adventure Sports TV (360p)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3377]
**_Channel Name:_** Adventure Sports TV (360p)
**_Broken Link (from playlist):_** https://gizmeon.s.llnwi.net/channellivev3/live/master.m3u8?channel=275
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Does not connect.
[https @ 0x7fa33c001780] HTTP error 502 Bad Gatewayq=    0B f=0/0   
https://gizmeon.s.llnwi.net/channellivev3/live/master.m3u8?channel=275: Server returned 5XX Server Error reply

**Comment by LaneSh4d0w** [comment]
Works for me.

**Comment by Dum4G** [comment]
Works in VLC

**Comment by jkemp814** [comment]
Confirmed. Not sure what happen. Video resolution also 1280x534. (360p) in the title.
