### ISSUE TITLE
Fix: AFV (STIRR) (720p)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3378]
**_Channel Name:_** AFV (STIRR) (720p)
**_Broken Link (from playlist):_** https://dai.google.com/linear/hls/event/18_lZXPySFa5_GRVEbOX_A/master.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Does not connect.
[tls @ 0x7f0ad076f840] Error in the pull function.sq=    0B f=0/0   
[hls @ 0x7f0ad0000b80] Failed to open segment 133535 of playlist 0

**Comment by LaneSh4d0w** [comment]
Works for me.

**Comment by Dum4G** [comment]
Works in VLC
