### ISSUE TITLE
Fix: AFV Espanol

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3379]
**_Channel Name:_** AFV Espanol
**_Broken Link (from playlist):_** https://linear-46.frequency.stream/dist/46/hls/master/playlist.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Does not connect.
[tls @ 0x7f8730004600] Error in the pull function.sq=    0B f=0/0   
https://linear-46.frequency.stream/dist/46/hls/master/playlist.m3u8: Input/output error

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
