### ISSUE TITLE
Fix: MTV Hits Europe

### ISSUE THREAD

**Issue by brluk** [iptv-org/iptv#3383]
**_Channel Name:_** MTV Hits Europe
**_Broken Link (from playlist):_** http://188.40.68.167/russia/mtv_hits/playlist.m3u8
**_Possible Replacement (optional):_** blob:https://player.teleringa.com/202e89a4-cff3-4a7a-9afc-e12ca3e71714
**_Notes (optional):_** Since July 1st the actual link of this stream get off the air with color bars. I put other link witch streams the same channel, but don't know if you guys can put like .m3u8 stream. Hope this helps.

**Comment by Dum4G** [comment]
https://player.teleringa.com/202e89a4-cff3-4a7a-9afc-e12ca3e71714 shows 404

**Comment by brluk** [comment]
> https://player.teleringa.com/202e89a4-cff3-4a7a-9afc-e12ca3e71714 shows 404

Can you try this?
https://player.teleringa.com/embed/mpd.php?canal=MTV%20Hits&stream=/live/c2live/MTV_Hits/SA_Live_dash_enc_2A/MTV_Hits.mpd

**Comment by jkemp814** [comment]
FFplay shows:
https://player.teleringa.com/embed/mpd.php?canal=MTV%20Hits: Invalid data found when processing input

**Comment by Sphinxroot** [comment]
https://edge9-sl.cvattv.com.ar//live/c2live/MTV_Hits/SA_Live_dash_enc_2A/MTV_Hits.mpd

strict-origin-when-cross-origin

ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed

wont be easy

**Comment by LaneSh4d0w** [comment]
https://edge9-sl.cvattv.com.ar//live/c2live/MTV_Hits/SA_Live_dash_enc_2A/MTV_Hits.mpd

Answers to me with a stream, but no audio / video.

**Comment by Dum4G** [comment]
Closed in favor of #3457

**Comment by Dum4G** [comment]
Very interesting geoblocked source
https://ds-glb-linear-abematv.akamaized.net/preview/channel/mtv-hits/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
https://ds-glb-linear-abematv.akamaized.net/channel/mtv-hits/playlist.m3u8 Same here

**Comment by Dum4G** [comment]
They're blocking my VPN

**Comment by brluk** [comment]
Guys, I tried this link http://188.40.68.167/russia/mtv_hits/playlist.m3u8 and the channel started working again! 
So, for now, it is not necessary to make any changes to the link.

**Comment by LaneSh4d0w** [comment]
Indeed, it went back online.
