### ISSUE TITLE
Fix: All time (XUMO)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3388]
**_Channel Name:_** All time (XUMO)
**_Broken Link (from playlist):_** https://dai2.xumo.com/amagi_hls_data_xumo1212A-alltime/CDN/master.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Does not connect.
[https @ 0x7fe624001780] HTTP error 416 Requested Range Not Satisfiable
https://dai2.xumo.com/amagi_hls_data_xumo1212A-alltime/CDN/master.m3u8: Server returned 4XX Client Error, but not one of 40{0,1,3,4}

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
