### ISSUE TITLE
Fix: All Weddings by WEtv

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3389]
**_Channel Name:_** All Weddings by WEtv
**_Broken Link (from playlist):_** https://amc-allweddings-1.plex.wurl.com/manifest/playlist.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Does not connect.
[https @ 0x7f875434a300] HTTP error 403 Forbidden sq=    0B f=0/0   
[hls @ 0x7f8754000b80] Failed to open segment 1777696 of playlist 0

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
