### ISSUE TITLE
Fix: Am.'s Test Kitchen

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3390]
**_Channel Name:_** Am.'s Test Kitchen
**_Broken Link (from playlist):_** https://dai2.xumo.com/xumocdn/p=redbox&deviceid=&is_lat=&subp=RedboxdesktopWebWindows/amagi_hls_data_xumo1212A-redboxamericastestkitchen/CDN/playlist.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Does not connect.
[https @ 0x7fbbac001780] HTTP error 400 Bad Requestq=    0B f=0/0   
https://dai2.xumo.com/xumocdn/p=redbox: Server returned 400 Bad Request

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
