### ISSUE TITLE
Fix: AMC Presents

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3391]
**_Channel Name:_** AMC Presents
**_Broken Link (from playlist):_** https://amc-amcpresents-1.plex.wurl.com/manifest/playlist.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Does not connect.
[https @ 0x7eff08344800] HTTP error 403 Forbidden sq=    0B f=0/0   
[hls @ 0x7eff08000b80] Failed to open segment 1780125 of playlist 0

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
