### ISSUE TITLE
Fix: AutoMoto (Bumblebee)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3393]
**_Channel Name:_** AutoMoto (Bumblebee)
**_Broken Link (from playlist):_** https://stitcheraws.unreel.me/wse-node04.powr.com/live/5bf220fad5eeee0f5a40941a/playlist.m3u8
**_Possible Replacement (optional):_** https://stitcheraws.unreel.me/wse-node01.powr.com/live/5bf220fad5eeee0f5a40941a/playlist.m3u8
**_Notes (optional):_** Does not connect.
[tls @ 0x7f3e2c004640] Error in the pull function.sq=    0B f=0/0   
https://stitcheraws.unreel.me/wse-node04.powr.com/live/5bf220fad5eeee0f5a40941a/playlist.m3u8: Input/output error

**Comment by Sphinxroot** [comment]
https://stitcheraws.unreel.me/wse-node01.powr.com/live/5bf220fad5eeee0f5a40941a/playlist.m3u8

**Comment by jkemp814** [comment]
Works! Thanks.

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457, @Sphinxroot Consider making a PR for that, check #3457 and add the other links I've gathered.
