### ISSUE TITLE
Fix: AXN

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3394]
**_Channel Name:_** AXN
**_Broken Link (from playlist):_** http://136.243.177.164/AXN/playlist.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Does not connect.
http://136.243.177.164/AXN/playlist.m3u8: End of file

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
