### ISSUE TITLE
Fix: AXN [Indonesia]

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3395]
**_Channel Name:_** AXN [Indonesia]
**_Broken Link (from playlist):_** http://210.210.155.35/session/37ee409e-73b5-11e9-b657-a0899505893d/uq2663/h/h141/01.m3u8
**_Possible Replacement (optional):_**
**_Notes (optional):_** Does not connect.
[http @ 0x7fcf0800a100] HTTP error 404 Not FoundB sq=    0B f=0/0   
[hls @ 0x7fcf08000b80] Failed to open segment 45119893 of playlist 0
[hls @ 0x7fcf08000b80] Opening 'http://210.210.155.35/session/37ee409e-73b5-11e9-b657-a0899505893d/uq2663/h/h141/20210406T085912-01-45119894.ts' for reading

Never connects.

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
