### ISSUE TITLE
Fix: ABC 9 Orlando FL (WFTV-HD)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3397]
**_Channel Name:_** ABC 9 Orlando FL (WFTV-HD)
**_Broken Link (from playlist):_** https://svc-lvanvato-cxtv-wftv.cmgvideo.com/wftv/2564k/index.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Does not connect. Attemps.
[https @ 0x7f808c600c40] HTTP error 403 Forbidden sq=    0B f=0/0   
[hls @ 0x7f808c000b80] Failed to open segment 156623451 of playlist 0

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
