### ISSUE TITLE
Add: [adult swim] East(TV Simulcast)

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#3400]
**Channel Name:** [adult swim] East (TV Simulcast)
**Country:** USA
**Language:** English
**External Link (optional):** https://tve-live-lln.warnermediacdn.com/hls/live/2023183/aseast/noslate/VIDEO_3_1928000.m3u8
**Notes (optional):** Turner's CDN Source - USA Geoblocked - Not 24h (Because Not Including Cartoon Network Broadcast)

**Comment by Ulter32** [comment]
Checked Working in PotPlayer

**Comment by jkemp814** [comment]
Works in FFplay. Off air. Maybe [Not 24/7]?
