### ISSUE TITLE
Fix: 30A Investment Pitch

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3401]
**_Channel Name:_** 30A Investment Pitch
**_Broken Link (from playlist):_** https://www.30a-tv.com/InvPit.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Stream will not connect in VLC. FFplay play intro, then stops.

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
