### ISSUE TITLE
Add: [adult swim]West (TV Siumlcast)

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#3402]
**Channel Name:** [adult swim]West(TV Simulcast)
**Country:** USA
**Language:** English
**External Link (optional):** https://tve-live-lln.warnermediacdn.com/hls/live/2023185/aswest/noslate/VIDEO_3_1928000.m3u8
**Notes (optional):** Source from turner's CDN - USA IP ONLY - Not 24h(Not Including Cartoon Network Broadcast)

**Comment by jkemp814** [comment]
Works, but stream off-air. [Not-24/7]
