### ISSUE TITLE
Fix: Myrtle Beach - Grand Strand (720p)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3408]
**_Channel Name:_** Myrtle Beach - Grand Strand (720p)
**_Broken Link (from playlist):_** 
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Should we consider renaming to Beach TV (Myrtle Beach - Grand Strand (720p))

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
