### ISSUE TITLE
Fix: BabyFirst

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3412]
**_Channel Name:_** BabyFirst
**_Broken Link (from playlist):_** https://livecdn.fptplay.net/qnetlive/babyfirst_hls.smil/chunklist_b2500000.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** https://livecdn.fptplay.net/qnetlive/babyfirst_hls.smil/chunklist_b2500000.m3u8: Server returned 403 Forbidden (access denied)

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
