### ISSUE TITLE
Fix: Baeble

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3413]
**_Channel Name:_** Baeble
**_Broken Link (from playlist):_** https://dai2.xumo.com/amagi_hls_data_xumo1212A-redboxbaeble/CDN/playlist.m3u8?p=redbox&deviceid=&is_lat=&subp=RedboxdesktopWebWindows
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Stream will play in FFplay but not VLC.
Throws error:
[https @ 0x7f7a83d84a80] Cannot reuse HTTP connection for different host: live-content.xumo.com:-1 != dai2.xumo.com:-1

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
