### ISSUE TITLE
Fix: Bambu

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3414]
**_Channel Name:_** Bambu
**_Broken Link (from playlist):_** 
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Stream will not play. VLC or FFplay.

https://bambu-junctionus.cinedigm.com/midroll/amagi_hls_data_xumo-host-bambu-junction/CDN/playlist.m3u8?webstream: Invalid data found when processing input

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
