### ISSUE TITLE
Fix: Battery Pop

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3415]
**_Channel Name:_** Battery Pop
**_Broken Link (from playlist):_** https://dai2.xumo.com/amagi_hls_data_xumo1212A-redboxbatterypop/CDN/playlist.m3u8?p=redbox&deviceid=&is_lat=&subp=RedboxdesktopWebWindows
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Stream will not play in VLC, but does play in FFplay.

[https @ 0x7fb4949a2780] Cannot reuse HTTP connection for different host: live-content.xumo.com:-1 != hls-beacons.xumo.com:-1

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
