### ISSUE TITLE
Fix: Beast Mode (US)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3416]
**_Channel Name:_** Beast Mode (US)
**_Broken Link (from playlist):_** https://1f0e60dbce3043279c491fe51983361d.mediatailor.us-west-2.amazonaws.com/v1/manifest/6b8beeb9ed833d048c8c8155a25a28fe617c5474/beast_mode_plex/dedcdc71-f8ba-4371-9ed9-e5fb2a691485/5.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** 
[https @ 0x7f5a30001840] HTTP error 400 q=    0KB sq=    0B f=0/0   
https://1f0e60dbce3043279c491fe51983361d.mediatailor.us-west-2.amazonaws.com/v1/manifest/6b8beeb9ed833d048c8c8155a25a28fe617c5474/beast_mode_plex/dedcdc71-f8ba-4371-9ed9-e5fb2a691485/5.m3u8: Server returned 400 Bad Request

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
