### ISSUE TITLE
Fix: Beverly Hillbillies (STIRR) (720p)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3417]
**_Channel Name:_** Beverly Hillbillies (STIRR) (720p)
**_Broken Link (from playlist):_** https://dai.google.com/linear/hls/event/TEeUv9DbStyK8DyFmG3Cfw/master.m3u8
**_Possible Replacement (optional):_**
**_Notes (optional):_** Failed to open file 'https://dai.google.com/linear/hls/event/TEeUv9DbStyK8DyFmG3Cfw/master.m3u8' or configure filtergraph

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
