### ISSUE TITLE
Fix: Blaze Live (720p)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3420]
**_Channel Name:_** Blaze Live (720p)
**_Broken Link (from playlist):_** http://plutotv.vo.llnwd.net/m/hlslive/theblaze.m3u8?chname=theblaze&pub=0
**_Possible Replacement (optional):_** 
**_Notes (optional):_** [http @ 0x7fc0dc001780] HTTP error 400 Bad Requestsq=    0B f=0/0   
http://plutotv.vo.llnwd.net/m/hlslive/theblaze.m3u8?chname=theblaze: Server returned 400 Bad Request

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
