### ISSUE TITLE
Fix: BLOOMBERG TV HD

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3422]
**_Channel Name:_** BLOOMBERG TV HD
**_Broken Link (from playlist):_** https://mn-nl.mncdn.com/blutv_bloomberght/smil:bloomberght_sd.smil/chunklist_b2064000.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** https://mn-nl.mncdn.com/blutv_bloomberght/smil:bloomberght_sd.smil/chunklist_b2064000.m3u8lay in FFplay but not in VLC

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
