### ISSUE TITLE
Fix: Bloomberg TV US (720p)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3423]
**_Channel Name:_** Bloomberg TV US (720p)
**_Broken Link (from playlist):_** https://cdn-videos.akamaized.net/btv/desktop/akamai/us/live/primary.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** [https @ 0x7fbcd0001800] HTTP error 403 Forbidden sq=    0B f=0/0   
https://cdn-videos.akamaized.net/btv/desktop/akamai/us/live/primary.m3u8: Server returned 403 Forbidden (access denied)

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
