### ISSUE TITLE
Fix: Bloomberg TV US (720p) #2

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3424]
**_Channel Name:_** Bloomberg TV US (720p)
**_Broken Link (from playlist):_** https://ch.iptvmate.net/4ac2dd1a410b37e8357ae8bbac3264c5.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** [https @ 0x7fb6ec001780] HTTP error 403 Forbidden sq=    0B f=0/0   
https://ch.iptvmate.net/4ac2dd1a410b37e8357ae8bbac3264c5.m3u8: Server returned 403 Forbidden (access denied)

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
