### ISSUE TITLE
Fix: Bloomberg TV US Politics Live Event (720p)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3426]
**_Channel Name:_** Bloomberg TV US Politics Live Event (720p)
**_Broken Link (from playlist):_** https://liveproduseast.global.ssl.fastly.net/btv/desktop/us_politics.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** [https @ 0x7f1940001800] HTTP error 403 Forbidden sq=    0B f=0/0   
https://liveproduseast.global.ssl.fastly.net/btv/desktop/us_politics.m3u8: Server returned 403 Forbidden (access denied)

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
