### ISSUE TITLE
Fix: Boomerang

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3428]
**_Channel Name:_** Boomerang
**_Broken Link (from playlist):_** http://27.254.130.56:80/live01/ch18.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** [http @ 0x7eff5c008d80] HTTP error 404 Not FoundB sq=    0B f=0/0

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
