### ISSUE TITLE
Fix: Boomerang #2

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3429]
**_Channel Name:_** Boomerang
**_Broken Link (from playlist):_** https://livecdn.fptplay.net/qnetlive/boomerang_hls.smil/chunklist_b2500000.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Will play in FFplay but not in VLC

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
