### ISSUE TITLE
Fix: Boston 25 News (WFXT)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3430]
**_Channel Name:_** Boston 25 News (WFXT)
**_Broken Link (from playlist):_** https://svc-lvanvato-cxtv-wfxt.cmgvideo.com/wfxt/2564k/index.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_**
[https @ 0x7f3a78016040] HTTP error 403 Forbidden sq=    0B f=0/0
[hls @ 0x7f3a78000b80] Failed to open segment 159837934 of playlist 0

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
