### ISSUE TITLE
Fix: bspoketv HD

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3431]
**_Channel Name:_** bspoketv HD
**_Broken Link (from playlist):_** https://bspoketv.nexustreamer.com/distrotv-usa/master.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** [tls @ 0x7f23ec004600] Error in the pull function.sq=    0B f=0/0   
https://bspoketv.nexustreamer.com/distrotv-usa/master.m3u8: Input/output error

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
