### ISSUE TITLE
Fix: CBS 9 Washington DC (WUSA-HD) (720p)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3433]
**_Channel Name:_** CBS 9 Washington DC (WUSA-HD) (720p)
**_Broken Link (from playlist):_** https://wusa-lh.akamaihd.net/i/WUSA_Breaking_1@98930/master.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** [https @ 0x7f60389034c0] HTTP error 404 Not Found sq=    0B f=0/0

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
