### ISSUE TITLE
Fix: Cheddar (1080p)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3434]
**_Channel Name:_** Cheddar (1080p)
**_Broken Link (from playlist):_** http://plutotv.vo.llnwd.net/m/hlslive/cheddar.m3u8?chname=cheddar&pub=0
**_Possible Replacement (optional):_** 
**_Notes (optional):_** [http @ 0x7f319c001780] HTTP error 400 Bad Requestsq=    0B f=0/0   
http://plutotv.vo.llnwd.net/m/hlslive/cheddar.m3u8?chname=cheddar: Server returned 400 Bad Request

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
