### ISSUE TITLE
Fix: Cheddar News

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3437]
**_Channel Name:_** Cheddar News
**_Broken Link (from playlist):_** http://stitcher.pluto.tv/stitch/hls/channel/5268abcd0ce20a8472000114/master.m3u8?sid=web24157571521&deviceType=web&deviceMake=web&deviceVersion=1&deviceId=web24163643069&appVersion=5.2.7&deviceDNT=web&deviceModel=web
**_Possible Replacement (optional):_** 
**_Notes (optional):_** [tcp @ 0x7f2f1c004640] Failed to resolve hostname stitcher.pluto.tv: Name or service not known
http://stitcher.pluto.tv/stitch/hls/channel/5268abcd0ce20a8472000114/master.m3u8?sid=web24157571521: Input/output error

**Comment by Dum4G** [comment]
Works in VLC, what's your player?

**Comment by jkemp814** [comment]
VLC just ships right pass it.

**Comment by jkemp814** [comment]
I will also test in FFplay if it does play in VLC

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
