### ISSUE TITLE
Fix: Chive TV

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3438]
**_Channel Name:_** Chive TV
**_Broken Link (from playlist):_** https://dai2.xumo.com/amagi_hls_data_xumo1212A-redboxchive/CDN/playlist.m3u8?p=redbox&deviceid=&is_lat=&subp=RedboxdesktopWebWindows
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Will play in FFplay but not VLC

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
