### ISSUE TITLE
Fix: Circle

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3443]
**_Channel Name:_** Circle
**_Broken Link (from playlist):_** https://dai2.xumo.com/amagi_hls_data_xumo1212A-redboxcircletv/CDN/playlist.m3u8?p=redbox&deviceid=&is_lat=&subp=RedboxdesktopWebWindows
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Will play in FFplay but not in VLC
[https @ 0x7f84bc664780] Cannot reuse HTTP connection for different host: circle-xumo.amagi.tv:-1 != dai2.xumo.com:-1

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
