### ISSUE TITLE
Fix: Combat Go (1080p)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3444]
**_Channel Name:_** Combat Go (1080p)
**_Broken Link (from playlist):_** https://stream-us-east-1.getpublica.com/cl/59f740a5-3c7b-47bf-a845-27df203f8b2e/1280x720_2300000_4_false.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** [https @ 0x7f7648001800] HTTP error 400 Bad Requestq=    0B f=0/0   
https://stream-us-east-1.getpublica.com/cl/59f740a5-3c7b-47bf-a845-27df203f8b2e/1280x720_2300000_4_false.m3u8: Server returned 400 Bad Request

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
