### ISSUE TITLE
Fix: ConTV

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3446]
**_Channel Name:_** ConTV
**_Broken Link (from playlist):_** https://cinedigm.vo.llnwd.net/conssui/amagi_hls_data_xumo123-contv/CDN/1280x720_2108000/chunklist.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** [https @ 0x7fcd48019000] HTTP error 503 Service Unavailable f=0/0   
[hls @ 0x7fcd48000b80] Failed to open segment 20230 of playlist 0

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
