### ISSUE TITLE
Fix: CONtv Anime (XUMO) (1080p)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3447]
**_Channel Name:_** CONtv Anime (XUMO) (1080p)
**_Broken Link (from playlist):_** https://dai2.xumo.com/xumocdn/p=redbox&deviceid=&is_lat=&subp=RedboxdesktopWebLinux/amagi_hls_data_xumo-host-contvanime-junction/CDN/playlist.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** [https @ 0x7fe120001780] HTTP error 400 Bad Requestq=    0B f=0/0   
https://dai2.xumo.com/xumocdn/p=redbox: Server returned 400 Bad Request

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
