### ISSUE TITLE
Fix: Cooking Panda | Source 2

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3448]
**_Channel Name:_** Cooking Panda | Source 2
**_Broken Link (from playlist):_** https://api-ott-cookingpanda.ottera.tv/loggingmediaurlpassthrough/a.m3u8?version=12.5&id=901&partner=distro&device_id=8f68c53f-f16a-45dd-b3eb-939325b0385a&device_model=Web&device_width=632&device_height=356&us_privacy=0&gdpr=0&device_language=en&is_lat=0
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Will play in FFplay but not VLC

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
