### ISSUE TITLE
Fix: Dancestar TV

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3451]
**_Channel Name:_** Dancestar TV
**_Broken Link (from playlist):_** https://vcndstv.teleosmedia.com/stream/dstv/dstv/seglist_720p.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Will play in FFplay but not VLC

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
