### ISSUE TITLE
Fix: Decentric Media

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3452]
**_Channel Name:_** Decentric Media
**_Broken Link (from playlist):_** https://linear-68.frequency.stream/dist/localnow/68/hls/master/playlist.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** [tls @ 0x7f15400046c0] Error in the pull function.sq=    0B f=0/0   
https://linear-68.frequency.stream/dist/localnow/68/hls/master/playlist.m3u8: Input/output error

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
