### ISSUE TITLE
Fix: ESPN U (720p)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3454]
**_Channel Name:_** ESPN U (720p)
**_Broken Link (from playlist):_** http://164.68.124.111/espnu.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** http://164.68.124.111/espnu.m3u8: Invalid data found when processing input

**Comment by LaneSh4d0w** [comment]
Could you consider putting all the channels that need to be fixed into one single issue please ? The number of issues you've opened makes it difficult to trace every channel.

**Comment by LaneSh4d0w** [comment]
Closed in favor of #3457
