### ISSUE TITLE
[Fix/Change needed] US Channels

### ISSUE THREAD

**Issue by LaneSh4d0w** [iptv-org/iptv#3457]
Channels have been reported to not work properly by @jkemp814.

That's where we see that it really needs a fix and clean x)

Pull Requests that are giving fixes : #3458 (by @Dum4G)

Broken Streams : 
- [x] MTV Hits Europe (fixed on it's own)
- [ ] <s> ESPN U</s>
- [x] Docurama
- [x] Decentric Media (fixed on it's own)
- [x] Dancestar TV (twice)
- [ ] <s> Crime Story (STIRR Version)</s>
- [x] Cooking Panda (Source 2)  (fixed on it's own)
- [x] CONtv Anime (XUMO Version)
- [x] CONtv
- [x] Complex
- [ ] <s>Combat Go</s>
- [x] Circle
- [x] Cinemax
- [x] Cine Romantico (XUMO Version)
- [x] Cheddar (twice)
- [x] WUSA-HD (CBS 9 Washington DC)
- [x] CBC News
- [x] BSpokeTV
- [x] Boston 25 News (WFXT-TV)
- [x] Boomerang (twice)
- [x] Bon Appetit
- [x] Bloomberg TV US (4 times)
- [x] Bloomberg TV US Normal + Politics Live Event
- [x] Blaze Live (Pluto TV shut off their LLNWD server)
- [x] Black News Channel (twice) (XUMO Bad Request - replacement link : https://dai2.xumo.com/amagi_hls_data_xumo1212A-redboxblacknewschannel/CDN/playlist.m3u8)
- [ ] <s> Beverly Hillbillies (STIRR Version) (Google DAI - Server answers, but 404 Not Found on links)</s>
- [x] Beast Mode (Amazon AWS telling bad session ID, I think we got a few AWS links that match this pattern, to be fixed)
- [x] Battery Pop (XUMO going weird, replacement link : https://dai2.xumo.com/amagi_hls_data_xumo1212A-redboxbatterypop/CDN/playlist.m3u8)
- [ ] <s> Bambu (Server answers with invalid playlist)</s>
- [x] Baeble (XUMO going weird, replacement link : https://dai2.xumo.com/amagi_hls_data_xumo1212A-redboxbaeble/CDN/playlist.m3u8)
- [x] BabyFirst (access denied, replacement link is https://livecdn.fptplay.net/qnetlive/babyfirst_hls.smil/playlist.m3u8)
- [x] 30A TV
- [ ] <s>21 Jump Street (STIRR) (Google DAI - Server answers, but 404 Not Found on links)</s>
- [x] ABC 9 Orlando FL (Maybe @MapGuy11 can host this channel onto his proxy)
- [x] AXN (Indonesia) (Fails to connect)
- [x] AXN (0 Bytes playlist)
- [x] Automoto (Bumblebee) (Replacement link (found by @Sphinxroot : https://stitcheraws.unreel.me/wse-node01.powr.com/live/5bf220fad5eeee0f5a40941a/playlist.m3u8)
- [x] Architectural Digest (XUMO going weird, replacement link : https://dai2.xumo.com/amagi_hls_data_xumo1212A-redboxarchitecturaldigest/CDN/playlist.m3u8)
- [ ] <s>AMC Presents (Plex/Wurl version) (Server answers with playlist but 403 Forbidden when playing it)</s>
- [x] America's Test Kitchen (XUMO) (XUMO weird again, replacement link : https://dai2.xumo.com/amagi_hls_data_xumo1212A-redboxamericastestkitchen/CDN/playlist.m3u8)
- [x] AMC All Weddings (by WEtv) (Plex/Wurl version) (Server answers with playlist but 403 Forbidden when playing it)
- [ ] <s>All Time (XUMO) (0 byte playlist)</s>
- [x] AFV Spanish (404 Not Found)
- [x] Adult Swim (Replacement link given, and present on Dum4G PR)
- [x] AMC Absolute Reality (by WEtv) (Plex/Wurl version) (Replacement link given : https://amc-absolutereality-1.samsung.wurl.com/manifest/playlist.m3u8 (I think it's already in playlist))

Names to be changed

- [x] Key West - Florida Keys (Proposed change : Beach TV (Key West - Florida Keys))
- [x] Myrtle Beach - Grand Strand (Proposed change : Beach TV (Myrtle Beach - Grand Strand)
- [x] Panama City (Proposed change : Beach TV (Panama City)
- [x] Florida - Alabama (Proposed change : Beach TV (Florida - Alabama))

**Comment by trancer1994** [comment]
WUSA-HD seems to be https://livevideo01.wusa9.com/hls/live/2015498/newscasts/live.m3u8 but you might need to look on the website.

Boston 25 News (WFXT-TV) seems to be https://d2dy6pkj44n6e7.cloudfront.net/v1/session/77872db67918a151b697b5fbc23151e5765767dc/cmg_PROD_cmg-tv-10020_27d61a9c-67b2-4d7c-9486-626a6a071467_LE/in/cmg-wftxtv-hls-v3/live.m3u8 or https://d2dy6pkj44n6e7.cloudfront.net/v1/session/77872db67918a151b697b5fbc23151e5765767dc/cmg_PROD_cmg-tv-10020_27d61a9c-67b2-4d7c-9486-626a6a071467_LE/in/cmg-wftxtv-hls-v3/live.m3u8

30a tv = https://30a-tv.com/feeds/xodglobal/30atv.m3u8

ABC 9 Orlando FL is https://d3qm7vzp07vxse.cloudfront.net/v1/session/77872db67918a151b697b5fbc23151e5765767dc/cmg_PROD_cmg-tv-10070_fe1f5f6c-cd0b-4993-a4a4-6db66be4f313_LE/in/cmg-wftvtv-hls-v3/live.m3u8 or https://d3qm7vzp07vxse.cloudfront.net/v1/session/77872db67918a151b697b5fbc23151e5765767dc/cmg_PROD_cmg-tv-10070_fe1f5f6c-cd0b-4993-a4a4-6db66be4f313_LE/in/cmg-wftvtv-hls-v3/live.m3u8

**Comment by trancer1994** [comment]
CONtv Anime is https://contvanime.cinedigm.com/conapp-ssai/amagi_hls_data_xumo-host-contvanime-junction/CDN/playlist.m3u8
CONtv Bambu is https://bambu-junctionus.cinedigm.com/midroll/amagi_hls_data_xumo-host-bambu-junction/CDN/playlist.m3u8

**Comment by Dum4G** [comment]
> https://d2dy6pkj44n6e7.cloudfront.net/v1/session/77872db67918a151b697b5fbc23151e5765767dc/cmg_PROD_cmg-tv-10020_27d61a9c-67b2-4d7c-9486-626a6a071467_LE/in/cmg-wftxtv-hls-v3/live.m3u8 or https://d2dy6pkj44n6e7.cloudfront.net/v1/session/77872db67918a151b697b5fbc23151e5765767dc/cmg_PROD_cmg-tv-10020_27d61a9c-67b2-4d7c-9486-626a6a071467_LE/in/cmg-wftxtv-hls-v3/live.m3u8

Looks like the same link and it's broken now

**Comment by Dum4G** [comment]
OG 30a TV works as well, adding new link as alternate

**Comment by Dum4G** [comment]
> https://bambu-junctionus.cinedigm.com/midroll/amagi_hls_data_xumo-host-bambu-junction/CDN/playlist.m3u8

Zero byte file @trancer1994

**Comment by LaneSh4d0w** [comment]
Gets the playlist but doesn't get into stream

**Comment by MapGuy11** [comment]
@Dum4G No 404 errors on all the .ts files

**Comment by Dum4G** [comment]
I've seen at least 4 Bambu sources and all of them are currently down. We'll add this channel later

**Comment by LaneSh4d0w** [comment]
I've fabricated XUMO Amagi links, they answer both with a 0 byte playlist (Roku + Redbox)

**Comment by Dum4G** [comment]
To recheck later:
#EXTINF:-1 tvg-id="AXNIndonesia.us" tvg-name="AXN [Indonesia]" tvg-country="US" tvg-language="" tvg-logo="" group-title="",AXN Indonesia [Geo-blocked]
http://210.210.155.35/uq2663/h/h141/index.m3u8
#EXTINF:-1 tvg-id="FightSports.us" tvg-name="Fight Sports" tvg-country="US" tvg-language="English" tvg-logo="https://i.imgur.com/wB9CkPG.jpg" group-title="Sports",Fight Sports (576p)
http://210.210.155.35/uq2663/h/h05/index.m3u8

**Comment by LaneSh4d0w** [comment]
> 
> 
> To recheck later:
> #EXTINF:-1 tvg-id="AXNIndonesia.us" tvg-name="AXN [Indonesia]" tvg-country="US" tvg-language="" tvg-logo="" group-title="",AXN Indonesia [Geo-blocked]
> http://210.210.155.35/uq2663/h/h141/index.m3u8
> #EXTINF:-1 tvg-id="FightSports.us" tvg-name="Fight Sports" tvg-country="US" tvg-language="English" tvg-logo="https://i.imgur.com/wB9CkPG.jpg" group-title="Sports",Fight Sports (576p)
> http://210.210.155.35/uq2663/h/h05/index.m3u8

Tested something : http://210.210.155.66/uq2663/h/h05/index.m3u8 (403 Forbidden)
http://210.210.155.66/uq2663/h/h141/index.m3u8 (403 Forbidden)

**Comment by Dum4G** [comment]
Alternate CRIME Story without manifest from @Sphinxroot. Also having a shortage?
https://342189106f294f6da7687918228af833.mediatailor.us-east-1.amazonaws.com/v1/master/82ded7a88773aef3d6dd1fedce15ba2d57eb6bca/wse_powr_com_5f9ad508f47afc741c2526be/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
Metadata not found using provided request parameters

**Comment by Dum4G** [comment]
Links from trancer can be fixed in a way
https://d2dy6pkj44n6e7.cloudfront.net/v1/master/77872db67918a151b697b5fbc23151e5765767dc/cmg_PROD_cmg-tv-10020_27d61a9c-67b2-4d7c-9486-626a6a071467_LE/in/cmg-wftxtv-hls-v3/live.m3u8?aws.sessionId=

But valid session id is needed

**Comment by LaneSh4d0w** [comment]
> 
> 
> Links from trancer can be fixed in a way
> https://d2dy6pkj44n6e7.cloudfront.net/v1/master/77872db67918a151b697b5fbc23151e5765767dc/cmg_PROD_cmg-tv-10020_27d61a9c-67b2-4d7c-9486-626a6a071467_LE/in/cmg-wftxtv-hls-v3/live.m3u8?aws.sessionId=
> 
> But valid session id is needed

Actually, without the Session ID parameter, it works on my side.

![vlcsnap-2021-07-04-01h05m56s640](https://user-images.githubusercontent.com/30985701/124368713-0134a600-dc64-11eb-9155-64e86657fb5e.png)

**Comment by Dum4G** [comment]
https://svc-lvanvato-cxtv-kiro.cmgvideo.com/kiro/1864k/index.m3u8
https://svc-lvanvato-cxtv-wpxi.cmgvideo.com/wpxi/2564k/index.m3u8
https://svc-lvanvato-cxtv-whio.cmgvideo.com/whio/2596k/index.m3u8

Will be broken

**Comment by LaneSh4d0w** [comment]
https://svc-lvanvato-cxtv-kiro.cmgvideo.com/kiro/master.m3u8
https://svc-lvanvato-cxtv-wpxi.cmgvideo.com/wpxi/master.m3u8
https://svc-lvanvato-cxtv-whio.cmgvideo.com/whio/master.m3u8

;)

**Comment by Dum4G** [comment]
Drops connection to me

**Comment by jkemp814** [comment]
[https @ 0x7f4928016480] HTTP error 403 Forbidden sq=    0B f=0/0   
[hls @ 0x7f4928000b80] Failed to open segment 159844699 of playlist 0
[hls @ 0x7f4928000b80] Opening 'https://svc-lvanvato-cxtv-kiro.cmgvideo.com/kiro/1864k/FkDdkLtocLs/159844/segment_159844700.ts' for reading

**Comment by LaneSh4d0w** [comment]
> 
> 
> Drops connection to me

Indeed... maybe those are geolocked.

@MapGuy11 ?

**Comment by jkemp814** [comment]
[http @ 0x7f60a400d480] HTTP error 403 ForbiddenB sq=    0B f=0/0   
[hls @ 0x7f60a4000b80] Failed to open segment 159836559 of playlist 0
[hls @ 0x7f60a4000b80] Opening 'http://svc-lvanvato-cxtv-wpxi.cmgvideo.com/wpxi/904k/EIQK67f6Fxm/159836/segment_159836560.ts' for reading

**Comment by jkemp814** [comment]
[http @ 0x7f49d800d480] HTTP error 403 ForbiddenB sq=    0B f=0/0   
[hls @ 0x7f49d8000b80] Failed to open segment 159841766 of playlist 0
[hls @ 0x7f49d8000b80] Opening 'http://svc-lvanvato-cxtv-whio.cmgvideo.com/whio/1296k/pyfrWYeBSKm/159841/segment_159841767.ts' for reading

**Comment by LaneSh4d0w** [comment]
I see they're Anvato hosted / protected.

**Comment by LaneSh4d0w** [comment]
![image](https://user-images.githubusercontent.com/30985701/124368987-46a6a280-dc67-11eb-83c0-c1aaee9d718f.png)

**Comment by Dum4G** [comment]
Absolute Reality by WEtv OG link is up now

**Comment by jkemp814** [comment]
Bon Appetit is working now. There is another Bonappetit that needs to be renamed to Bon Appetit.

**Comment by Dum4G** [comment]
> https://svc-lvanvato-cxtv-kiro.cmgvideo.com/kiro/master.m3u8
> https://svc-lvanvato-cxtv-wpxi.cmgvideo.com/wpxi/master.m3u8
> https://svc-lvanvato-cxtv-whio.cmgvideo.com/whio/master.m3u8
> 
> ;)

Can we make those work in VLC?

**Comment by LaneSh4d0w** [comment]
That's possible... I'll need to look after the main links.
