### ISSUE TITLE
Add: Deluxe Lounge HD

### ISSUE THREAD

**Issue by diestro123** [iptv-org/iptv#3459]
**Channel Name:** Deluxe Lounge HD
**Country:** Germany
**Language:** English
**Notes (optional):** This channel was until a few weeks ago, but recently dissapear although still broadcasting.

**Comment by Dum4G** [comment]
https://d46c0ebf9ef94053848fdd7b1f2f6b90.mediatailor.eu-central-1.amazonaws.com/v1/master/81bfcafb76f9c947b24574657a9ce7fe14ad75c0/live-prod/9a087b26-8be4-11eb-a7de-bacfe1f83627/0/master.m3u8?uid=749544ec3d9a45d48c600d03cac91dfd&optout=0&vendor=philips&country=DE

Doesn't play in VLC but returns master file

**Comment by diestro123** [comment]
Works perfect in web browser for example. Thanks!

**Comment by jkemp814** [comment]
[https @ 0x7fbc94015a80] HTTP error 504 
[hls @ 0x7fbc94000b80] parse_playlist error Server returned 5XX Server Error reply [https://d46c0ebf9ef94053848fdd7b1f2f6b90.mediatailor.eu-central-1.amazonaws.com/v1/manifest/81bfcafb76f9c947b24574657a9ce7fe14ad75c0/live-prod/2e32f848-dbd7-458a-8198-9660221f53d1/0.m3u8]

[hls @ 0x7fbc94000b80] Empty segment [https://d46c0ebf9ef94053848fdd7b1f2f6b90.mediatailor.eu-central-1.amazonaws.com/v1/manifest/81bfcafb76f9c947b24574657a9ce7fe14ad75c0/live-prod/2e32f848-dbd7-458a-8198-9660221f53d1/0.m3u8]

[hls @ 0x7fbc94000b80] Empty segment [https://d46c0ebf9ef94053848fdd7b1f2f6b90.mediatailor.eu-central-1.amazonaws.com/v1/manifest/81bfcafb76f9c947b24574657a9ce7fe14ad75c0/live-prod/2e32f848-dbd7-458a-8198-9660221f53d1/3.m3u8]
Failed to open file 'https://d46c0ebf9ef94053848fdd7b1f2f6b90.mediatailor.eu-central-1.amazonaws.com/v1/master/81bfcafb76f9c947b24574657a9ce7fe14ad75c0/live-prod/9a087b26-8be4-11eb-a7de-bacfe1f83627/0/master.m3u8?uid=749544ec3d9a45d48c600d03cac91dfd' or configure filtergraph
