### ISSUE TITLE
Add: GEMTV

### ISSUE THREAD

**Issue by A-Alizadeh** [iptv-org/iptv#3468]
**Channel Name:** GEMTV
**Country:** IRAN
**Language:** FARSI
**External Link (optional):** http://ginikopersian.com/watch.php?id=548
**Notes (optional):** Login is required to access the steam (free). Once accessed there is a token system. I was hoping someone could help with that.

**Comment by jkemp814** [comment]
http://ginikopersian.com/watch.php?id=548: Invalid data found when processing input

**Comment by A-Alizadeh** [comment]
> http://ginikopersian.com/watch.php?id=548: Invalid data found when processing input

Works for me, as mentioned. You might need to register (free)

**Comment by MapGuy11** [comment]
https://d2e40kvaojifd6.cloudfront.net/stream/gem_tv/playlist.m3u8

**Comment by jkemp814** [comment]
[https @ 0x7f0fc8001780] HTTP error 403 Forbidden
https://d2e40kvaojifd6.cloudfront.net/stream/gem_tv/playlist.m3u8: Server returned 403 Forbidden (access denied)

**Comment by Sphinxroot** [comment]
giniko have token stream for most of it

work in kodi  referer needed
https://d2e40kvaojifd6.cloudfront.net/stream/gem_tv/playlist.m3u8|Referer=https://www.gemonline.tv/en-US/Live/Index?channelname=gemtv

you might try this

#EXTINF:-1 tvg-logo="https://www.gemonline.tv/Assets/channels-box/gemtv.png" group-title="GEM Online",Gem TV
#EXTVLCOPT:http-referrer=https://www.gemonline.tv/en-US/Live/Index?channelname=gemtv
https://d2e40kvaojifd6.cloudfront.net/stream/gem_tv/playlist.m3u8

**Comment by Dum4G** [comment]
![image](https://user-images.githubusercontent.com/5430116/124766451-9c1cd100-df3f-11eb-841b-e3509722d08e.png)
On website

**Comment by A-Alizadeh** [comment]
Doesn't work with exo player still.

**Comment by Sphinxroot** [comment]
on kodi it work 
https://i.imgur.com/xiM5MfN.png

**Comment by A-Alizadeh** [comment]
> on kodi it work
> https://i.imgur.com/xiM5MfN.png

Can you send your full m3u8 file please?

**Comment by LaneSh4d0w** [comment]
> 
> 
> giniko have token stream for most of it
> 
> work in kodi referer needed
> [https://d2e40kvaojifd6.cloudfront.net/stream/gem_tv/playlist.m3u8|Referer=https://www.gemonline.tv/en-US/Live/Index?channelname=gemtv](https://d2e40kvaojifd6.cloudfront.net/stream/gem_tv/playlist.m3u8%7CReferer=https://www.gemonline.tv/en-US/Live/Index?channelname=gemtv)
> 
> you might try this
> 
> #EXTINF:-1 tvg-logo="https://www.gemonline.tv/Assets/channels-box/gemtv.png" group-title="GEM Online",Gem TV
> #EXTVLCOPT:http-referrer=https://www.gemonline.tv/en-US/Live/Index?channelname=gemtv
> https://d2e40kvaojifd6.cloudfront.net/stream/gem_tv/playlist.m3u8

Confirmed working : 
![image](https://user-images.githubusercontent.com/30985701/124971479-84ba1280-e029-11eb-86b6-cf70dca914e5.png)

**Comment by Nostradamus1973** [comment]
Good morning,
Does anyone have an active Gem TV source? I know there are 720p & 480p versions floating around the internet, I would prefer the 720p, however, I'll gladly accept the 480p version as well.

Thank you and have a nice day.

**Comment by makianzad1-boop** [comment]
DOES ANYONE HAVE M3U URL FOR GEM TV THAT WORKS ! Much appreciated

**Comment by BellezaEmporium** [comment]
https://m3u.iranvids.com/gem-tv/output.m3u8

**Comment by esi8bitman** [comment]
Doesn't work ... I didn't find any source for gem tv or gem series
