### ISSUE TITLE
Add: NBC 5 (KSDK) 

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3469]
**Channel Name:** NBC 5 (KSDK)
**Country:** USA
**Language:** English
**External Link (optional):** https://livevideo01.ksdk.com/hls/live/2014965/newscasts/live.m3u8
**Notes (optional):** St. Louis, Missouri

Website: https://www.ksdk.com/
Stream URL: https://www.ksdk.com/watch

**Comment by jkemp814** [comment]
Not sure if that's the live feed. When I go back to it, it repeats what was on.

**Comment by jkemp814** [comment]
Just confirm it's a recent live stream. The next live stream won't be until 6:00AM. Will try and grab the stream then, not unless someone else knows how to find the live station. I'm sure there on the air.

**Comment by LaneSh4d0w** [comment]
Can confirm that link works for me.

![vlcsnap-2021-07-04-14h04m43s142](https://user-images.githubusercontent.com/30985701/124384295-ca48a980-dcd0-11eb-949f-d349d9517423.png)

**Comment by LaneSh4d0w** [comment]
There's a 7-minute delay between me and the actual live feed.

**Comment by jkemp814** [comment]
Thanks, that adaptive link bumped the resolution way up. I was concerned about 'newscast' being in the URL would the live station broadcast to not stream.
