### ISSUE TITLE
add ARD channel In Germany

### ISSUE THREAD

**Issue by chezsick** [iptv-org/iptv#347]
please add the channel ard in de.json, country :: germany
url ::::: https://daserstehdde-lh.akamaihd.net/i/daserstehd_de@629196/master.m3u8

**Comment by freearhey** [comment]
@chezsick Are you sure this is a live broadcast? I constantly see only just a screensaver.

**Comment by chezsick** [comment]
Yes Is A Broadcast From ARD
For Example, A Movie Passed In This Channel :::::::: https://mamot.fr/web/statuses/102254599876752449

**Comment by chezsick** [comment]
Heuuu No Is Fix Video :disappointed: Maybe Too Later?

**Comment by Chow89** [comment]
ARD aka Das Erste is already in the list https://github.com/iptv-org/iptv/blob/8d78fede0f166f9fb2c9da14a3873454d1096c59/channels/de.m3u#L46

**Comment by chezsick** [comment]
Im sorry ::: i no see because, is not write ard

**Comment by chezsick** [comment]
I Closing This Issue For A Screenshot Stream, URL From @Chow89 
![mpv-shot0001](https://user-images.githubusercontent.com/21131245/66004894-2c47ff80-e4aa-11e9-8380-f071b34b2ad0.jpg)
