### ISSUE TITLE
Add: Nine PBS

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3470]
**Channel Name:** Nine PBS
**Country:** USA
**Language:** English
**External Link (optional):** https://ketcdt.lls.cdn.pbs.org/ketcdt/0436e066-85c7-408b-a4fd-5b492ccb5fd8/primary.m3u8
**Notes (optional):** St. Louis, Missouri [Geo-blocked]

**Comment by asdfghiptvyde** [comment]
does not work

**Comment by asdfghiptvyde** [comment]
btw what is geo-blocked

**Comment by BellezaEmporium** [comment]
Necro'd a 4-years-old addition... locking.
