### ISSUE TITLE
Add: Fox 2 (KTVI)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3471]
**Channel Name:** Fox 2 (KTVI)
**Country:** USA
**Language:** English
**External Link (optional):** https://dcs-live.apis.anvato.net/server/play/xADY1WZSZodNcYGj/manifest.m3u8?encp=W6gAZ2M-FeKAx30p0O8SIg:vC_J05lAIy7HtzMpjJG2Qh9eqWmUM8WqeCLvju7tYtIeqWr1kgnqx5S2ztKw_AiJbwtb8I2uZErVP4kevuclowcEzrui3gjhZ8ZOyDcES5nuAtlutZMPTeY15dMIXXpX9Mbk3PpQkAJ7vr8obUFZCmoaJEh21IGm6OvQzmcQ_4S7-Yu-LDtSquNpQGBN10Upc87LXsLFBFOdbp7iCQBPisNrfdYtKciagnSlMZGMtnL7KSkTq_Hea5BdAFazMftB0GyMrPUD1yaBvTIo-NZ1DWbWEEHLtHwRv1O6kQMjKpzl1tep6eGVGlg0EJlXAk6NDx8Wt0qFPkSQGEDLsWAathVSbQ-w3ATzWg-EnR3pwkmx1_dOdt9T7SdUenJO62pe8GB4SjltRTEc9ugSlzx3dkMgANAUDleIwGHKHq5PicpvpvlY29VyGpFS0QS3aBShPPv9_HZxNq6BWK7IcST8BmMFf_Ko8LKxyUJoV3eRETTlCTvkswJrtSqsdkseREyF6SFm4nr6BbV2uUc9X0AN-T64plTDzeda6gBvlrYgDG6nwVG4E2rwm7a3yKdD8wSHDCxVcGDpJrafWSSkE0xXqvtCCEPKLJDAD0YPRYLlC4HW5Q_mDO7e14WSEhZWKFUCiElTScotlOt5xlZqFXvaQt_Z1Q9c1QURgFSbD8gEcjsldM_b_w2lG8HCoT_Wf6fKPZ_hHCgHaI7MxKGjBc_cE-4b7LkX-pNwoHNOfbrnIvI&anvtrid=w5741a7f7086a964192e9925a032b92b&anvauth=tb=0~te=1625369551~sgn=6e8a812adcc33126b33f92d55b52a03ce144720152b3a4fa690eda084e85a987&t=1625369461&_vpng=0
**Notes (optional):** St. Louis, Missouri - Throws 403 error. Is there any hope of getting around this?

Website:
https://fox2now.com/

Steam URL:
https://fox2now.com/on-air/live-streaming/

masterManifest:
https://dcs-live.apis.anvato.net/server/play/xADY1WZSZodNcYGj/rendition.m3u8?track=video-2&anvsid=i177602636-n434d50e0-6d6e-4e12-a92f-ea11aaf1616f&ts=1625412953&anvtrid=w5741a7fa36211a67c3824b82170cfe5

Thumbnail:
https://fox2now.com/wp-content/uploads/sites/14/2015/05/fox-2-news-2.jpeg?w=1280

urlFilename:
rendition

**Comment by Dum4G** [comment]
@LaneSh4d0w you've learned smth about Anvato links right?

**Comment by LaneSh4d0w** [comment]
Yup, there's a server permitting the token creation, and this creates the link we have above.

**Comment by LaneSh4d0w** [comment]
Wait... it seems it still works. Let me do something real quick.

**Comment by LaneSh4d0w** [comment]
Try https://iptv-all.lanesh4d0w.codes/united-states/ktvi-tv

**Comment by Dum4G** [comment]
![image](https://user-images.githubusercontent.com/5430116/126825985-7c99f667-9dbf-4564-8b32-090913ed26e6.png)

**Comment by LaneSh4d0w** [comment]
Yeah GitHub made shit and reverted a commit by itself, now it should work.

**Comment by Dum4G** [comment]
And now it works

**Comment by LaneSh4d0w** [comment]
Perfect, i'll let @jkemp814 test, and if everything good, it's good to push on our playlists !

**Comment by jkemp814** [comment]
It works, no errors. Low resolution, though.

**Comment by jkemp814** [comment]
Wow!, after some time it jumped to 1920x1080! Excellent.

**Comment by LaneSh4d0w** [comment]
Perfect, making a PR to add it.

**Comment by jkemp814** [comment]
Thank you, stream is steady and still going. That's my hometown news station, so it means a lot to me.

**Comment by subby2006** [comment]
@LaneSh4d0w I found an anvato token thing for fox 32 and fox livenow however they seem to be in a json format and something my kodi can't read. Is it possible if you could add those to your streamlink thing?

**Comment by LaneSh4d0w** [comment]
> 
> 
> @LaneSh4d0w I found an anvato token thing for fox 32 and fox livenow however they seem to be in a json format and something my kodi can't read. Is it possible if you could add those to your streamlink thing? I'll send you the token urls if you need them

Sure, just give me the token links (beginning by https://tkx.apis.anvato.net/rest/v2/mcp/video/) and i'll see what I can do with those.
