### ISSUE TITLE
Add: All Sports

### ISSUE THREAD

**Issue by fotvnetwork** [iptv-org/iptv#3473]
**Channel Name:** All Sports Television Network
**Country:** US
**Language:** English
**External Link (optional):** https://2-fss-2.streamhoster.com/pl_120/amlst:203932-1476320/playlist.m3u8
**Notes (optional):** Digital over-the-air sports channel. Source is from KGPT-CD: https://kgpttv26.com/stream-all-sports

**Comment by jkemp814** [comment]
It works. 

Only error:
[swscaler @ 0x7f11a0226d00] deprecated pixel format used, make sure you did set range correctly
