### ISSUE TITLE
Add: MTV 80's

### ISSUE THREAD

**Issue by brluk** [iptv-org/iptv#3477]
**Channel Name:** MTV 80's
**Country:** Russia 
**Language:** English
**External Link (optional):** http://mfe.cliptv.az/dash/VH1_Classic_SD.ism/playlist.mpd
**Notes (optional):** Add at Music category :)

**Comment by jkemp814** [comment]
It works, it buffers on my end. Tried several attempts at a new connection.

Input #0, dash, from 'http://mfe.cliptv.az/dash/VH1_Classic_SD.ism/playlist.mpd':
  Duration: N/A, start: 1625420494.359856, bitrate: N/A
  Program 0 
    Stream #0:0: Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p, 720x576 [SAR 1:1 DAR 5:4], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 1600000
      id              : video/bw1600000
    Stream #0:1: Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p, 480x360 [SAR 1:1 DAR 4:3], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 700000
      id              : video/bw700000
    Stream #0:2(rus): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 128000
      id              : audio/rus
[dash @ 0x7f9934000b80] No longer receiving stream_index 1

**Comment by brluk** [comment]
I try watch today via this link http://mfe.cliptv.az/dash/VH1_Classic_SD.ism/playlist.mpd and not working :( 
They shut down today.
