### ISSUE TITLE
Add: tvN

### ISSUE THREAD

**Issue by mushroom08** [iptv-org/iptv#3483]
Does anyone know of any link watch live Korea TV, only need SBS and tvN channel? Thanks

**Comment by Dum4G** [comment]
We have SBS already
https://github.com/iptv-org/iptv/blob/master/channels/kr.m3u

**Comment by mushroom08** [comment]
> We have SBS already
> https://github.com/iptv-org/iptv/blob/master/channels/kr.m3u

Yes, now only need tvN channel

**Comment by fotvnetwork** [comment]
http://50.7.161.82:8278/streams/d/TVN/playlist.m3u8
