### ISSUE TITLE
Add: CNN Espanol

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#3484]
**Channel Name:** CNN Espanol
**Country:** Mexico
**Language:** Spanish
**Website:** https://cnnespanol.cnn.com/cnnvenezuela/
**Stream URL (optional):** https://turnerlive.akamaized.net/hls/live/2006634/cnnespanol/master.m3u8?__b__=650

**Notes (optional):** Source from Turner's CDN - Original Site Says "Venezuela Only" But It Works With Mexico VPN

**Comment by heroku-miraheze** [comment]
https://turnerlive.akamaized.net/hls/live/2006634/cnnespanol/master.m3u8?__b__=650 is blocked globally, and working only in Latin American.

**Comment by Dum4G** [comment]
@LaneSh4d0w do you have Venezuela or Mexico VPN to check? Failed with Spanish and Mexico VPNs to me

**Comment by LaneSh4d0w** [comment]
> 
> 
> @LaneSh4d0w do you have Venezuela or Mexico VPN to check? Failed with Spanish and Mexico VPNs to me. I can confirm website is offering this link tho

Not quite sure about that, I can test with a proxy, give me a few seconds.
