### ISSUE TITLE
Fix: Auto-update dependencies

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#3493]
I think this log describes what happens better than me
https://github.com/iptv-org/iptv/runs/3024391239?check_suite_focus=true

**Comment by LaneSh4d0w** [comment]
well... the one after seems to have worked : 

![image](https://user-images.githubusercontent.com/30985701/125039631-009e7400-e097-11eb-9cd8-f2ae0576129e.png)

Might be a quack from GitHub's servers at a certain point in time.
