### ISSUE TITLE
Fix: BBC News

### ISSUE THREAD

**Issue by tinsae-ghilay** [iptv-org/iptv#3498]
**_Channel Name:_** BBC News
**_Broken Link (from playlist):_** http://1111296894.rsc.cdn77.org/LS-ATL-54548-11/tracks-v1a1/mono.m3u8
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** it stopped a couple of days ago

**Comment by Dum4G** [comment]
What playlist do you use?

**Comment by tinsae-ghilay** [comment]
> What playlist do you use?
The English pllaylist. And the BBC news lunks are all not working as of late. Only one was working for me until a week or so.

**Comment by Dum4G** [comment]
I'm not able to see this link neither in English or UK playlist. Are you updating your playlist daily from here?
https://iptv-org.github.io/iptv/languages/eng.m3u

**Comment by Dum4G** [comment]
Will take a look for existing links anyway

**Comment by tinsae-ghilay** [comment]
> Will take a look for existing links anyway

The link I have posted might be an old one. But I tried all of them yesterday and I couldnt get one that works. I will try all available links using different players today to eliminate posibility of player problem.

**Comment by tinsae-ghilay** [comment]
Ok so, The link below is the only one that is not Geo-Blocked and since I am out of the UK I think This would have been my only choice. but it is not working for me. tried it on Android (TV and Phone using different apps) on PC using Iptvnator and native (or add-on) firefox extension. its not working. BBC World news does work sometimes but it is a low resolution and it keeps buffering every few seconds. 
the link doesn't have an Extension so may be it not getting recognized as a video streaming link.
http://51.52.156.22:8888/http/004

**Comment by Dum4G** [comment]
Links from IP addresses tend to die sooner or later. We'll take a look if something public is available online and I'm sure there is, but we can't guarantee VPN won't be needed

**Comment by Dum4G** [comment]
Links from IP addresses tend to die sooner or later. We'll take a look if something public is available online and I'm sure there is, but we can't guarantee VPN won't be needed

**Comment by tinsae-ghilay** [comment]
thank you very much. there is one on newsmag but the link keeps changing every 4-6 hrs I think. it includes some kind of encrypted value and a 1000 rounded time in mills for 14:13:56 and 21:12:26 UTC of current date as far as I was able to deduct.

**Comment by Dum4G** [comment]
@LaneSh4d0w https://www.livenewsmag.com/bbc-news-uk-live-stream/ needs investigation and I won't close the issue for now

@tinsae-ghilay Thanks for your report. I have found just one source that works without VPN but it's in 480p and with a banner from broadcaster ss well as an alternate source that is also geo-blocked. In fact, all geo-blocked sources work just fine. You'll see those changes live when https://github.com/iptv-org/iptv/pull/3514 will be merged and midnight autoupdate will hapen

**Comment by LaneSh4d0w** [comment]
> 
> 
> @LaneSh4d0w https://www.livenewsmag.com/bbc-news-uk-live-stream/ needs investigation and I won't close the issue for now
> 
> @tinsae-ghilay Thanks for your report. I have found just one source that works without VPN but it's in 480p and with a banner from broadcaster as well as an alternate source that is also geo-blocked. In fact, all geo-blocked sources work just fine. If you find some great VPN deal or set up a UK server you're all good. You'll see those changes live when #3514 will be merged and midnight autoupdate will hapen

Edgy stuff : https://bbc.newscdn.org/MtZhgKtX_iJcbbKzprydlw==,1626023591/LS-ATL-54548-6/index.m3u8

It came from the player itself. i would need to reverse the JS to make it work. Might be lucky if the token doesn't change, the next part seems to be a timestamp, however I would rework all the way to the base to get the token logic.

**Comment by LaneSh4d0w** [comment]
@Dum4G say no more...

http://1111296894.rsc.cdn77.org/LS-ATL-54548-6/index.m3u8

It seems that it's this one now.

They've only moved the last bit.

-11 became -6

**Comment by tinsae-ghilay** [comment]
> @Dum4G say no more...
> 
> http://1111296894.rsc.cdn77.org/LS-ATL-54548-6/index.m3u8
> 
> ![vlcsnap-2021-07-11-15h40m17s665](https://user-images.githubusercontent.com/30985701/125197517-5113fe00-e25e-11eb-9912-3f1adc771143.png)
> 
> It seems that it's this one now.
> 
> They've only moved the last bit.
> 
> -11 became -6

Thanks alot! That worked.
