### ISSUE TITLE
Add: can you extract a m3u8 link of this radio 

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#3499]
radio jow algeria
https://jow.radio/jow-radio-live
http://jow.news/player/

**Comment by Dum4G** [comment]
https://ice.creacast.com/jowradio is enough to make it work in VLC

**Comment by LaneSh4d0w** [comment]
I confirm, that works.

**Comment by hemzaberkane** [comment]
> https://ice.creacast.com/jowradio is enough to make it work in VLC
> https://str0.creacast.com/jowradio

i wanna play it on tivimate player !

**Comment by Dum4G** [comment]
> i wanna play it on tivimate player !
Does it fail to play in it?

**Comment by hemzaberkane** [comment]
> > i wanna play it on tivimate player !
> 
> Does it fail to play in it?

yes

**Comment by LaneSh4d0w** [comment]
It seems that this radio does not stream all the time.

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-logo="https://i.imgur.com/DHo8stn.png" group-title="",jow radio
https://ice.creacast.com/jowradio
#EXTINF:-1 tvg-logo="https://i.imgur.com/QEsYJUP.png" group-title="",jow radio - Rap
https://ice.creacast.com/jowradio-jow_rap
#EXTINF:-1 tvg-logo="https://i.imgur.com/LFOfQqG.png" group-title="",jow radio - Rai
https://ice.creacast.com/jowradio-rai
#EXTINF:-1 tvg-logo="https://i.imgur.com/ZEbRl2E.png" group-title="",jow radio - Dini
https://ice.creacast.com/jowradio-diny
#EXTINF:-1 tvg-logo="https://i.imgur.com/mB5DDYP.png" group-title="",jow radio - North Africa
https://ice.creacast.com/jowradio-north_africa

Kodi  , Potplayer  , vlc   play them
