### ISSUE TITLE
Zilzal Classic

### ISSUE THREAD

**Issue by MesopotamianGroyper** [iptv-org/iptv#3509]
**Channel Name:** Zilzal Classic
**Channel ID:** ZilzalClassic.eg
**Country:** Egypt
**Language:** Arabic
**Website:** https://www.lyngsat.com/tvchannels/--/Zilzal-Classic.html
**Stream URL (optional):** xxx
**Notes (optional):** While the channel exists, I am not sure about its official website. If it is possible to add it, that would be great. If not, then fair enough. Thank you.

**Comment by Dum4G** [comment]
Can't find any source for the playlist. Meanwhile you can watch it here
https://tv.taghtia.com/en/watch/zilzal-classic

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/1947

**Comment by freearhey** [comment]
Closed in favor of #12290
