### ISSUE TITLE
Add: Surya TV

### ISSUE THREAD

**Issue by shahinms1** [iptv-org/iptv#3516]
**Channel Name:** Surya TV
**Country:** India
**Language:** Malayalam
**Website:** https://sunnetwork.in/Default.aspx?Lang=malayalam
**Stream URL (optional):** xxx
**Notes (optional):** There is a paid subscription app for Sun Network who is the owner of this channel. App name is Sun Next. Surya TV is available there.

**Comment by LaneSh4d0w** [comment]
This program is on YuppTV : https://catchup.yuppcdn.net/amazonv2/20/preview/suryasd/master/master.m3u8 (preview link)

Might be possible to have it somehow someway.

**Comment by shahinms1** [comment]
> This program is on YuppTV : https://catchup.yuppcdn.net/amazonv2/20/preview/suryasd/master/master.m3u8 (preview link)
> 
> Might be possible to have it somehow someway.

How can we generate links like this?

**Comment by LaneSh4d0w** [comment]
Those are on https://yupptv.com

Works for certain channels.
