### ISSUE TITLE
Add: Cartoon network

### ISSUE THREAD

**Issue by taimur45** [iptv-org/iptv#3544]
**Channel Name:** Cartoon network
**Country:** india
**Language:** Hindi
**Website:** 
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Dum4G** [comment]
#EXTINF:-1 group-title="Kids" tvg-logo="https://i.imgur.com/H3UGkci.png",Cartoon Network-Hindi 1
http://70.39.83.58:8278/cartoonnetworkhindikdin/playlist.m3u8
#EXTINF:-1 group-title="Kids" tvg-logo="https://i.imgur.com/H3UGkci.png",Cartoon Network-Hindi 2
http://103.153.39.34:8000/play/a04k/index.m3u8
