### ISSUE TITLE
Fix: Gunaz TV

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3545]
**_Channel Name:_** Gunaz TV
**_Broken Link (from playlist):_** http://gtv.live.cdn.bitgravity.com/gtv/live/feed03
**_Possible Replacement (optional):_** https://gtv.live-s.cdn.bitgravity.com/cdn-live/_definst_/gtv/live/multibitrate.smil/chunklist_w1484311239_b450000.m3u8
**_Notes (optional):_** Attempts to connect, but times out in VLC, FFplay, Kodi.

There is another channel in the us.m3u playlist with similar name.  (Günaz)  It does finally streams with no audio.

Website: http://gunaz.live/

Check other sites, it will not play there also. 

Gives 404 error on this site. (https://streema.com/tv/GunazTV)

Günaz Tv Canlı Yayını does play at this address: https://canlitv.com/gunaz-tv 

This site has a lot of channels: https://canlitv.com/tr

**Comment by Sphinxroot** [comment]
in kodi i have 

#EXTINF:-1,Load + Hang and Stop
https://gtv.live-s.cdn.bitgravity.com/cdn-live/_definst_/gtv/live/multibitrate.smil/playlist.m3u8

#EXTINF:-1,Load + Hang and Stop
https://gtv.live-s.cdn.bitgravity.com/cdn-live/_definst_/gtv/live/multibitrate.smil/chunklist_w296497813_b128000.m3u8

#EXTINF:-1,480p no sound
https://gtv.live-s.cdn.bitgravity.com/cdn-live/_definst_/gtv/live/multibitrate.smil/chunklist_w296497813_b300000.m3u8

#EXTINF:-1,272p have sound
https://gtv.live-s.cdn.bitgravity.com/cdn-live/_definst_/gtv/live/multibitrate.smil/chunklist_w296497813_b450000.m3u8

**Comment by Dum4G** [comment]
VLC is hanging because it fails to load the worst quality first. Since b300000 looks as horrible as 450000 you can replace the link in your next PR

**Comment by jkemp814** [comment]
Yeah, I think it's only 240p,and another on has no sound. 

Günaz Tv  in the playlist is the same channel. It's really should be named Günaz Tv Canlı izle. It does play but at low resolution also.

**Comment by Dum4G** [comment]
Both OG links from the playlist do work atm
