### ISSUE TITLE
Add: OTV Lebanon alternate source

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#3568]
**Channel Name:** OTV Lebanon
**Country:** Lebanon
**Language:** Arabic
**Website:** https://player.teleon.tv/en/channel/otv-lebanon
**Stream URL (optional):** xxx
**Notes (optional):** Until recently it was possible to watch it by following this link https://svs.itworkscdn.net/otvlebanonlive/otv.smil/playlist.m3u8 but looks like it's tokenized now. I found a website that is allowing to watch the source, so can we do something about it?

**Comment by Sphinxroot** [comment]
the only way i found to get it working is by using kodi 18.9 + the streamlink tester addon  in a playlist , it grab the token

plugin://plugin.video.streamlink-tester/?action=play&url=https://www.otv.com.lb/new-live.php

https://i.imgur.com/ZeC6mhE.png 1080p

**Comment by Sphinxroot** [comment]
unstable it go on and off
720p
#EXTINF:-1,OTV
http://62.182.82.104/OTV/index.m3u8?token=test
#EXTINF:-1,OTV
http://62.182.82.104/OTV/tracks-v1a1/mono.m3u8?token=test

**Comment by Sphinxroot** [comment]
http://azrotv.com/iphone/arabic/ch3/otv.php
referer needed
576p
http://teledunet.com:8080/live/azrotv/azrotv2021/10015.m3u8|Referer=http://azrotv.com/pyr/dnt/?id=10015

**Comment by Dum4G** [comment]
That's what we have, but this source is so inconsistent

**Comment by Dum4G** [comment]
Meanwhile I got a secret of Azro inclusivity and inconsistency: they use Stalker portals as a source and then try to tokenize it. Current Al Jadeed link is http://dimapro.cz:8080/live/KzilaUMFaY/lUE9wE6vqE/38295.m3u8

**Comment by LaneSh4d0w** [comment]
Watch out for those Azro links. As I was looking at the links the website went by, it seemed it tried to install something (the URL at least was saying "install"...), and my browser crashed while trying to load it (it tried to launch the debugger)

**Comment by Sphinxroot** [comment]
@Dum4G  this kind of link are xtream code  by someone who have a paid sub     host server / user name / password / stream (name or number)  i event see some that look like a real stream naming but there are`nt

if you can pull out the m3u its a paid or trial sub

USER NAME = EMAIL / RANDOM CARACTER / NAME  
HTTP HOST SERVER /get.php?username=(USER NAME)&password=(PASSWORD HERE)&type=m3u

**Comment by Sphinxroot** [comment]
> Watch out for those Azro links. As I was looking at the links the website went by, it seemed it tried to install something (the URL at least was saying "install"...), and my browser crashed while trying to load it (it tried to launch the debugger)

yes some stream from this site want you to install reproductor m3u8 chrome extension  .. if you are on chrome its a risk  .. i use firefox  whit adblock+ ghostery +no Script + and a cookies filtering   among 3 hsl  sniffer plugins + some greasemonkey script

**Comment by LaneSh4d0w** [comment]
>  @Dum4G  this kind of link are xtream code  by someone who have a paid sub     host server / user name / password / stream (name or number)  i event see some that look like a real stream naming but there are`nt
> 
> if you can pull out the m3u its a paid or trial sub
> 
> USER NAME = EMAIL / RANDOM CARACTER / NAME  
> HTTP HOST SERVER /get.php?username=(USER NAME)&password=(PASSWORD HERE)&type=m3u

I do have a program that looks after this stuff :) I can even spit the number of connections accepted and if the account is limited or not.

**Comment by LaneSh4d0w** [comment]
(by the way, don't try to access the root of the page (dimapro.cz;8080), it blacklists you.)

**Comment by LaneSh4d0w** [comment]
> 
> 
> @Dum4G this kind of link are xtream code by someone who have a paid sub host server / user name / password / stream (name or number) i event see some that look like a real stream naming but there are`nt
> 
> if you can pull out the m3u its a paid or trial sub
> 
> USER NAME = EMAIL / RANDOM CARACTER / NAME
> HTTP HOST SERVER /get.php?username=(USER NAME)&password=(PASSWORD HERE)&type=m3u

Your answer : 
![image](https://user-images.githubusercontent.com/30985701/126085046-b0b824ac-68c0-49a5-a91c-2a2970a35a07.png)

**Comment by tilfizyawn** [comment]
@Sphinxroot @LaneSh4d0w This can extract the m3u8. Maybe a repl can be created

curl -s 'https://www.otv.com.lb/new-live.php' | grep -Eo 'https://[^ >]+playlist.m3u8'

**Comment by LaneSh4d0w** [comment]
> @Sphinxroot @LaneSh4d0w This can extract the m3u8. Maybe a repl can be created
> 
> curl -s 'https://www.otv.com.lb/new-live.php' | grep -Eo 'https://[^ >]+playlist.m3u8'

Can handle that indeed.

I'm working on making an Ethiopian channel work, i'll try to work my way on this too.

**Comment by LaneSh4d0w** [comment]
@tilfizyawn @Sphinxroot @Dum4G See https://iptv-all.lanesh4d0w.codes/TESTING/lebanon/otv for a live example.

**Comment by tilfizyawn** [comment]
Thanks I added it in https://github.com/iptv-org/iptv/pull/3670

**Comment by LaneSh4d0w** [comment]
Then I assume it works fine, two seconds.

**Comment by Dum4G** [comment]
I'm satisfied. You guys are awesome
