### ISSUE TITLE
Music Choice

### ISSUE THREAD

**Issue by MapGuy11** [iptv-org/iptv#3581]
**Channel Name:** Music Choice - Group of Channels
**Country:** United States
**Language:** English
**Website:** https://webplayer.musicchoice.com/
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Dum4G** [comment]
Looks well tokenized
https://github.com/tummut/ITV/blob/67d4f52a889cac4727bccb555fd12421d029476b/Test

**Comment by MapGuy11** [comment]
> Looks well tokenized. Every naive link just not resolving to me
> https://github.com/tummut/ITV/blob/67d4f52a889cac4727bccb555fd12421d029476b/Test

Authentication Denied :(

**Comment by Dum4G** [comment]
A bit wrong info, that domain is the only one that responds and won't tell you if the channel exists https://edge.music-choice-chaina.top.comcast.net/mapguy

**Comment by LaneSh4d0w** [comment]
I don't really like this way of proceeding... but it seems someone has done a "token" generation for Music Choice : http://173.208.212.186/MusicChoice/token

It would mean channels would be like this :

https://edge.music-choice-chaina.top.comcast.net/streamwebvca1/VideoChannels/ROTFL121/*insert token*/playlist.m3u8?Platform=Web&AppName=MCMediaApp&AppVersion=1.8&Source=VCChainA&AssetID=VC_121&AssetType=VideoChannel&RegionID=1&IsPrimary=True&IsDR=False

**Comment by LaneSh4d0w** [comment]
http://173.208.212.186/MusicChoice/generate.php?id=ALTERNATIVE&source=1
http://173.208.212.186/MusicChoice/generate.php?id=BRITS-HITS&source=1
http://173.208.212.186/MusicChoice/generate.php?id=DANCE-EDM&source=1
http://173.208.212.186/MusicChoice/generate.php?id=HIP-HOP-AND-RANDB&source=1
http://173.208.212.186/MusicChoice/generate.php?id=HIT-LIST&source=1
http://173.208.212.186/MusicChoice/generate.php?id=INDIE&source=1
http://173.208.212.186/MusicChoice/generate.php?id=KIDZ-ONLY&source=1
http://173.208.212.186/MusicChoice/generate.php?id=METAL&source=1
http://173.208.212.186/MusicChoice/generate.php?id=MEXICANA&source=1
http://173.208.212.186/MusicChoice/generate.php?id=MUSIC-CHOICE-PLAY&source=1
http://173.208.212.186/MusicChoice/generate.php?id=MUSICA-URBANA&source=1
http://173.208.212.186/MusicChoice/generate.php?id=POP-AND-COUNTRY&source=1
http://173.208.212.186/MusicChoice/generate.php?id=POP-HITS&source=1
http://173.208.212.186/MusicChoice/generate.php?id=POP-LATINO&source=1
http://173.208.212.186/MusicChoice/generate.php?id=RANDB-SOUL&source=1
http://173.208.212.186/MusicChoice/generate.php?id=RAP&source=1
http://173.208.212.186/MusicChoice/generate.php?id=RAP-2K&source=1
http://173.208.212.186/MusicChoice/generate.php?id=ROCK&source=1
http://173.208.212.186/MusicChoice/generate.php?id=TEEN-BEATS&source=1
http://173.208.212.186/MusicChoice/generate.php?id=THROWBACK-JAMZ&source=1
http://173.208.212.186/MusicChoice/generate.php?id=TODAYS-COUNTRY&source=1
http://173.208.212.186/MusicChoice/generate.php?id=TODDLER-TUNES&source=1
http://173.208.212.186/MusicChoice/generate.php?id=TROPICALES&source=1
http://173.208.212.186/MusicChoice/generate.php?id=Y2K&source=1

**Comment by MapGuy11** [comment]
I wonder if they have the audio channels too.

**Comment by MapGuy11** [comment]
That Code Only Works for that channel so the php script it is.

**Comment by MapGuy11** [comment]
Maybe I will try to find the code to host it myself so it's atleast HTTPS.

**Comment by MapGuy11** [comment]
Seems the token's don't expire either!

**Comment by MapGuy11** [comment]
> Alternative : https://edge.music-choice-chaina.top.comcast.net/streamwebvca1/VideoChannels/ROTFL122/O0U9MTYyNzY1NjgyMztBPTE7Sz0wO1A9MDExMTA7Uz1lZThlNzJmZjcyNmI0NGE4MmQ1NjRlMGZjODEzNDE0ODE2MTgwNDJj/playlist.m3u8
> 
> Brits Hits : https://edge.music-choice-chaina.top.comcast.net/streamwebvca2/VideoChannels/ROTFL143/O0U9MTYyNzY1NjkyMjtBPTE7Sz0wO1A9MDExMTA7Uz0yMzYxNDY1MGIwZjU0YzVjMjVhMWEwNmY2NDYzNGE1ZGJkN2VhYWMx/playlist.m3u8
> 
> Mexicana : https://edge.music-choice-chaina.top.comcast.net/streamwebvca2/VideoChannels/ROTFL131/O0U9MTYyNzY1NzA0NTtBPTE7Sz0wO1A9MDExMTA7Uz00ZTI2M2IwZWRmOTg0ZjFiY2M5NDUyMDgwNjQ4NGI2NGQ2ZGU4OGUz/playlist.m3u8
> 
> Dance / EDM : https://edge.music-choice-chaina.top.comcast.net/streamwebvca1/VideoChannels/ROTFL127/O0U9MTYyNzY1NzE3MztBPTE7Sz0wO1A9MDExMTA7Uz1jYzZkYjM4MDlhNTc4Y2ZlMjc1NTUxOTc5ZTUwNGIwNTI0YTVjZDk1/playlist.m3u8
> 
> As examples.
> 
> 
> 
> http://173.208.212.186/MusicChoice/generate.php?id=ALTERNATIVE&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=BRITS-HITS&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=DANCE-EDM&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=HIP-HOP-AND-RANDB&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=HIT-LIST&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=INDIE&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=KIDZ-ONLY&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=METAL&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=MEXICANA&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=MUSIC-CHOICE-PLAY&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=MUSICA-URBANA&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=POP-AND-COUNTRY&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=POP-HITS&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=POP-LATINO&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=RANDB-SOUL&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=RAP&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=RAP-2K&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=ROCK&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=TEEN-BEATS&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=THROWBACK-JAMZ&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=TODAYS-COUNTRY&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=TODDLER-TUNES&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=TROPICALES&source=1
> http://173.208.212.186/MusicChoice/generate.php?id=Y2K&source=1
> 
> Just take the links that are in, and replace the "media" something to playlist.m3u8. And you got the links !

You have to use the php script because the links above expired. So the script must give you a new token every couple of hours

**Comment by LaneSh4d0w** [comment]
Just typed in Music Choice Comcast on Google, and this was one of the results that appeared to me.

**Comment by freearhey** [comment]
Closed in favor #3145

**Comment by sesudo** [comment]
> Alternative : https://edge.music-choice-chaina.top.comcast.net/streamwebvca1/VideoChannels/ROTFL122/O0U9MTYyNzY1NjgyMztBPTE7Sz0wO1A9MDExMTA7Uz1lZThlNzJmZjcyNmI0NGE4MmQ1NjRlMGZjODEzNDE0ODE2MTgwNDJj/playlist.m3u8
> 
> Brits Hits : https://edge.music-choice-chaina.top.comcast.net/streamwebvca2/VideoChannels/ROTFL143/O0U9MTYyNzY1NjkyMjtBPTE7Sz0wO1A9MDExMTA7Uz0yMzYxNDY1MGIwZjU0YzVjMjVhMWEwNmY2NDYzNGE1ZGJkN2VhYWMx/playlist.m3u8
> 
> Mexicana : https://edge.music-choice-chaina.top.comcast.net/streamwebvca2/VideoChannels/ROTFL131/O0U9MTYyNzY1NzA0NTtBPTE7Sz0wO1A9MDExMTA7Uz00ZTI2M2IwZWRmOTg0ZjFiY2M5NDUyMDgwNjQ4NGI2NGQ2ZGU4OGUz/playlist.m3u8
> 
> Dance / EDM : https://edge.music-choice-chaina.top.comcast.net/streamwebvca1/VideoChannels/ROTFL127/O0U9MTYyNzY1NzE3MztBPTE7Sz0wO1A9MDExMTA7Uz1jYzZkYjM4MDlhNTc4Y2ZlMjc1NTUxOTc5ZTUwNGIwNTI0YTVjZDk1/playlist.m3u8
> 
> As examples.
> 
> http://173.208.212.186/MusicChoice/generate.php?id=ALTERNATIVE&source=1 http://173.208.212.186/MusicChoice/generate.php?id=BRITS-HITS&source=1 http://173.208.212.186/MusicChoice/generate.php?id=DANCE-EDM&source=1 http://173.208.212.186/MusicChoice/generate.php?id=HIP-HOP-AND-RANDB&source=1 http://173.208.212.186/MusicChoice/generate.php?id=HIT-LIST&source=1 http://173.208.212.186/MusicChoice/generate.php?id=INDIE&source=1 http://173.208.212.186/MusicChoice/generate.php?id=KIDZ-ONLY&source=1 http://173.208.212.186/MusicChoice/generate.php?id=METAL&source=1 http://173.208.212.186/MusicChoice/generate.php?id=MEXICANA&source=1 http://173.208.212.186/MusicChoice/generate.php?id=MUSIC-CHOICE-PLAY&source=1 http://173.208.212.186/MusicChoice/generate.php?id=MUSICA-URBANA&source=1 http://173.208.212.186/MusicChoice/generate.php?id=POP-AND-COUNTRY&source=1 http://173.208.212.186/MusicChoice/generate.php?id=POP-HITS&source=1 http://173.208.212.186/MusicChoice/generate.php?id=POP-LATINO&source=1 http://173.208.212.186/MusicChoice/generate.php?id=RANDB-SOUL&source=1 http://173.208.212.186/MusicChoice/generate.php?id=RAP&source=1 http://173.208.212.186/MusicChoice/generate.php?id=RAP-2K&source=1 http://173.208.212.186/MusicChoice/generate.php?id=ROCK&source=1 http://173.208.212.186/MusicChoice/generate.php?id=TEEN-BEATS&source=1 http://173.208.212.186/MusicChoice/generate.php?id=THROWBACK-JAMZ&source=1 http://173.208.212.186/MusicChoice/generate.php?id=TODAYS-COUNTRY&source=1 http://173.208.212.186/MusicChoice/generate.php?id=TODDLER-TUNES&source=1 http://173.208.212.186/MusicChoice/generate.php?id=TROPICALES&source=1 http://173.208.212.186/MusicChoice/generate.php?id=Y2K&source=1
> 
> Just take the links that are in, and replace the "media" something to playlist.m3u8. And you got the links !

Can you add the rest of the Video Channels plzzz.???

**Comment by BellezaEmporium** [comment]
> > Alternative : https://edge.music-choice-chaina.top.comcast.net/streamwebvca1/VideoChannels/ROTFL122/O0U9MTYyNzY1NjgyMztBPTE7Sz0wO1A9MDExMTA7Uz1lZThlNzJmZjcyNmI0NGE4MmQ1NjRlMGZjODEzNDE0ODE2MTgwNDJj/playlist.m3u8
> > Brits Hits : https://edge.music-choice-chaina.top.comcast.net/streamwebvca2/VideoChannels/ROTFL143/O0U9MTYyNzY1NjkyMjtBPTE7Sz0wO1A9MDExMTA7Uz0yMzYxNDY1MGIwZjU0YzVjMjVhMWEwNmY2NDYzNGE1ZGJkN2VhYWMx/playlist.m3u8
> > Mexicana : https://edge.music-choice-chaina.top.comcast.net/streamwebvca2/VideoChannels/ROTFL131/O0U9MTYyNzY1NzA0NTtBPTE7Sz0wO1A9MDExMTA7Uz00ZTI2M2IwZWRmOTg0ZjFiY2M5NDUyMDgwNjQ4NGI2NGQ2ZGU4OGUz/playlist.m3u8
> > Dance / EDM : https://edge.music-choice-chaina.top.comcast.net/streamwebvca1/VideoChannels/ROTFL127/O0U9MTYyNzY1NzE3MztBPTE7Sz0wO1A9MDExMTA7Uz1jYzZkYjM4MDlhNTc4Y2ZlMjc1NTUxOTc5ZTUwNGIwNTI0YTVjZDk1/playlist.m3u8
> > As examples.
> > http://173.208.212.186/MusicChoice/generate.php?id=ALTERNATIVE&source=1 http://173.208.212.186/MusicChoice/generate.php?id=BRITS-HITS&source=1 http://173.208.212.186/MusicChoice/generate.php?id=DANCE-EDM&source=1 http://173.208.212.186/MusicChoice/generate.php?id=HIP-HOP-AND-RANDB&source=1 http://173.208.212.186/MusicChoice/generate.php?id=HIT-LIST&source=1 http://173.208.212.186/MusicChoice/generate.php?id=INDIE&source=1 http://173.208.212.186/MusicChoice/generate.php?id=KIDZ-ONLY&source=1 http://173.208.212.186/MusicChoice/generate.php?id=METAL&source=1 http://173.208.212.186/MusicChoice/generate.php?id=MEXICANA&source=1 http://173.208.212.186/MusicChoice/generate.php?id=MUSIC-CHOICE-PLAY&source=1 http://173.208.212.186/MusicChoice/generate.php?id=MUSICA-URBANA&source=1 http://173.208.212.186/MusicChoice/generate.php?id=POP-AND-COUNTRY&source=1 http://173.208.212.186/MusicChoice/generate.php?id=POP-HITS&source=1 http://173.208.212.186/MusicChoice/generate.php?id=POP-LATINO&source=1 http://173.208.212.186/MusicChoice/generate.php?id=RANDB-SOUL&source=1 http://173.208.212.186/MusicChoice/generate.php?id=RAP&source=1 http://173.208.212.186/MusicChoice/generate.php?id=RAP-2K&source=1 http://173.208.212.186/MusicChoice/generate.php?id=ROCK&source=1 http://173.208.212.186/MusicChoice/generate.php?id=TEEN-BEATS&source=1 http://173.208.212.186/MusicChoice/generate.php?id=THROWBACK-JAMZ&source=1 http://173.208.212.186/MusicChoice/generate.php?id=TODAYS-COUNTRY&source=1 http://173.208.212.186/MusicChoice/generate.php?id=TODDLER-TUNES&source=1 http://173.208.212.186/MusicChoice/generate.php?id=TROPICALES&source=1 http://173.208.212.186/MusicChoice/generate.php?id=Y2K&source=1
> > Just take the links that are in, and replace the "media" something to playlist.m3u8. And you got the links !
> 
> Can you add the rest of the Video Channels plzzz.???

http://173.208.212.186/MusicChoice/list.php

**Comment by sesudo** [comment]
Thx , but i mean the other Video Channels like MC 90s , MC 80s , MC Pop Latino , MC Family Hits  etc , MC have 30 video Channels und in the list are 24 ... Do you know the owner of http://173.208.212.186/MusicChoice/ ???

**Comment by BellezaEmporium** [comment]
No, as said before, it's the first website given to me while searching for the terms.

**Comment by Browningate** [comment]
Has anyone found an updated link for this? The http://173.208.212.186/MusicChoice/ path is now a dead end.

**Comment by zebloby-tech** [comment]
anyone has any links?

**Comment by Browningate** [comment]
> anyone has any links?

Still no results. The good news, however, is that Charter Spectrum is now including access (through official channels) on their lower-cost TV streaming plans, so you may not need the off-beat links any longer.
