### ISSUE TITLE
Fix: TMC

### ISSUE THREAD

**Issue by chopstiks** [iptv-org/iptv#3586]
**_Channel Name:_** TMC France
**_Broken Link (from playlist):_** https://tmc-hls-live-ssl.tf1.fr/tmc/1/hls/live_2328.m3u8
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** xxx

**Comment by LaneSh4d0w** [comment]
They're moving their links to token-protected DASH links, won't be easy to get.

**Comment by Sphinxroot** [comment]
MyTFI Channel


Sadly The Have Token Stream and 1080p stream
https://liveschauen.com/50-regarder-tf1-en-direct-et-en-ligne-tf1-direct-live-streaming.html



to be tested

#EXTINF:-1 tvg-id="TF1.fr" tvg-name="TF1 FR" tvg-logo="https://i.ibb.co/M8GjLmy/TF1.png" group-title="",TF1 (720p)
#EXTVLCOPT:http-referrer=https://www.streamaway.net/fr/TF1.php
https://www.streamaway.net/fra/tf1/tracks-v1a1/mono.m3u8

#EXTINF:-1 tvg-id="TF1SeriesFilms.fr" tvg-name="TF1 Séries Films FR" tvg-logo="https://i.ibb.co/41Dt9TY/TF1Serie.png" group-title="",TF1 Series/films  (720p)
#EXTVLCOPT:http-referrer=https://www.streamaway.net/fr/HD1-fr.php
https://www.streamaway.net/fra/hd1/mono.m3u8

#EXTINF:-1 tvg-id="TFX.fr" tvg-name="TFX FR" tvg-logo="https://i.imgur.com/LLbpKZh.png" group-title="",TFX  (720p)
#EXTVLCOPT:http-referrer=https://www.streamaway.net/fr/NT1-fr.php
https://www.streamaway.net/fra/nt1/mono.m3u8

#EXTINF:-1 tvg-id="TMC.fr" tvg-name="TMC FR" tvg-logo="https://i.ibb.co/XL20Y0z/TMC.png" group-title="",TMC (720p)
#EXTVLCOPT:http-referrer=https://www.streamaway.net/fr/TMC-fr.php
https://www.streamaway.net/fra/tmc/mono.m3u8



For Kodi only

#EXTINF:-1 tvg-id="TF1.fr" tvg-name="TF1 FR" tvg-logo="https://i.ibb.co/M8GjLmy/TF1.png" group-title="",TF1 (720p)
https://www.streamaway.net/fra/tf1/tracks-v1a1/mono.m3u8|Referer=https://www.streamaway.net/fr/TF1.php

#EXTINF:-1 tvg-id="TF1SeriesFilms.fr" tvg-name="TF1 Séries Films FR" tvg-logo="https://i.ibb.co/41Dt9TY/TF1Serie.png" group-title="",TF1 Series/films  (720p)
https://www.streamaway.net/fra/hd1/mono.m3u8|Referer=https://www.streamaway.net/fr/HD1-fr.php

#EXTINF:-1 tvg-id="TFX.fr" tvg-name="TFX FR" tvg-logo="https://i.imgur.com/LLbpKZh.png" group-title="",TFX  (720p)
https://www.streamaway.net/fra/nt1/mono.m3u8|Referer=https://www.streamaway.net/fr/NT1-fr.php

#EXTINF:-1 tvg-id="TMC.fr" tvg-name="TMC FR" tvg-logo="https://i.ibb.co/XL20Y0z/TMC.png" group-title="",TMC  (720p)
https://www.streamaway.net/fra/tmc/mono.m3u8|Referer=https://www.streamaway.net/fr/TMC-fr.p


LCI is Still Working but for how long

**Comment by LaneSh4d0w** [comment]
They're redirecting into some website... I think it's the same host than some Indian channels I have, let me see.

**Comment by LaneSh4d0w** [comment]
Confirmed, same host than the Indian ones, you can get the links at "https://bg-gledaitv.co" if I remember correctly.

**Comment by Dum4G** [comment]
#EXTINF:-1 tvg-id="TMC.fr" tvg-name="TMC FR" tvg-logo="https://i.ibb.co/XL20Y0z/TMC.png" group-title="",TMC (720p)
#EXTVLCOPT:http-referrer=https://www.streamaway.net/fr/TMC-fr.php
https://www.streamaway.net/fra/tmc/mono.m3u8

is forbidden for me, might be geo-blocked

**Comment by LaneSh4d0w** [comment]
TF1 appears to be http://185.93.1.39/FRCH_TF1_HD/playlist.m3u8
TF1 Séries Films appears to be http://cdn.gledaitv.co:2200/EX/TF1_Series_Films_HD-fr/playlist.m3u8?token=
TFX appears to be http://cdn.gledaitv.co:2200/EX/TFX-fr/playlist.m3u8?token=
The only one answering is TMC, and appears to be hiding under the streamaway.net name
http://cdn.gledaitv.co:2200/EX/TMC-fr/playlist.m3u8?token=

**Comment by LaneSh4d0w** [comment]
TF1 : https://tf1-das-live-ssl.tf1.fr/video/prrLwBjrOyKU11rMEv5bnA/1627066224/out/v1/192e289f861a43739091437725f9c2b1/index.mpd
TF1 Séries Films : https://hd1-das-live-ssl.tf1.fr/video/WRUXmvlI4jdob9XuDsmrTA/1627066687/out/v1/d025b4f9239b4ce1aa53d1a7692cba0a/index.mpd
TFX : https://nt1-das-live-ssl.tf1.fr/video/tYrUEEc4mZOLcvMAfE-VWQ/1627066590/out/v1/233038e4d07f4416a0eb8598f241d9ea/index.mpd
TMC : https://tmc-das-live-ssl.tf1.fr/video/oMfguffa0L_K9amMYEuQMg/1627066550/out/v1/39e5bad5774f42fd8941edff13ff5072/index.mpd

**Comment by LaneSh4d0w** [comment]
Fixed by last PRs.
