### ISSUE TITLE
Sony Max (Indian) Max time link always dead

### ISSUE THREAD

**Issue by awinashrkdf** [iptv-org/iptv#359]
Hello sir,
1st of all thanks for your wonderful and great work.
Actually it's a very small issue .Sony max(Indian) Max time link dead ...Please have a look on it.

http://103.77.252.58:8081/live/sonymax/chunks.m3u8

May be some alternative for this from your side

**Comment by freearhey** [comment]
Broken links removed. As soon as a working broadcast appears, we will return the channel back.

**Comment by freearhey** [comment]
- [ ] [Sony Max](https://www.sonymax.tv/en_SG/)
