### ISSUE TITLE
Add: Please find drm key (drm_license_url) for SG Channels : suria and vasantham !

### ISSUE THREAD

**Issue by bagushp** [iptv-org/iptv#3593]
Please find drm key (drm_license_url) for NEW suria and vasantham LINK !
i have checked this link in IPTV Checker v2.5 and Still Online status (green)
i have tried open in TiviMate, but cannot open because error "DrmSessionException"

**Channel Name:** Suria
**Country:** SG
**Language:** Malay
**Website:** https://www.mewatch.sg/channels/suria/97084 (VPN SG)
**Stream URL :** https://tglmp04.akamaized.net/out/v1/b200e885125f4787bd2329952ff28fa1/manifest.mpd

**Channel Name:** Vasantham
**Country:** SG
**Language:** Tamil
**Website:** https://www.mewatch.sg/channels/vasantham/97096 (VPN SG)
**Stream URL :** https://tglmp03.akamaized.net/out/v1/14eb6e921cae41298efaa4d9db0f2875/manifest.mpd

Thanks

**Comment by LaneSh4d0w** [comment]
https://www.mewatch.sg/api/authorization/anonymous?ff=idp%2Cldp%2Crpt%2Ccd&lang=en

Almost sure you'll need this.

**Comment by LaneSh4d0w** [comment]
Can't seem to have anything, it seems that it detects VPN.

**Comment by LaneSh4d0w** [comment]
Might be possible if you try going in, and catch a link that sounds like this : https://cdnapisec.kaltura.com/p/2082311/sp/46822833/playManifest/entryId/*insert_id*/format/applehttp/.m3u8?referrer=aHR0cHM6Ly93d3cubWV3YXRjaC5zZw==

**Comment by Sphinxroot** [comment]
http://101.127.128.44:9981/playlist/channels tested in kodi   .. cant tell for other player  and some are geo

**Comment by LaneSh4d0w** [comment]
> 
> 
> http://101.127.128.44:9981/playlist/channels 

TVHeadend endpoint : http://101.127.128.44:9981/extjs.html

Interesting there's also an EPG in this one.

**Comment by LaneSh4d0w** [comment]
![image](https://user-images.githubusercontent.com/30985701/126770774-afdbfd0c-9e17-4bcf-aab7-d777cd20e7c6.png)

For the links, tested with a Singapore VPN.

**Comment by caten0** [comment]
http://101.127.128.44:9981/stream/channel/074b5b58caa4032fb3cea403eef32c99?profile=pass

**Comment by caten0** [comment]
http://101.127.128.44:9981/stream/channel/074b5b58caa4032fb3cea403eef32c99?profile=pass

**Comment by badprogramshere** [comment]
> TVHeadend endpoint : http://101.127.128.44:9981/extjs.html
> Poor bandwidths on streams, however excellent quality (1080p)
> 
> Interesting there's also an EPG in this one.

Seems like the EPG is incorrect here - as of right now, it says that Asia Tonight is airing, when it's 2:45PM. The current program is Asia Now

**Comment by Dum4G** [comment]
Many of the links above are easy to fix, see the PR above. Channel U says we're failing DRM check and OKTO on 5 is currently broadcasts channel 5. OKTO on 5 ceased to exist since 2019 https://en.wikipedia.org/wiki/Okto
