### ISSUE TITLE
Fix: Nippon TV

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#3595]
**_Channel Name:_** Nippon TV
**_Broken Link (from playlist):_** http://redlabmcdn.s.llnwi.net/nv02/ryowa3hd/playlist.m3u8

**_Possible Replacement (optional):_** https://ntv.mov3.co/hls/ntv.m3u8
**_Notes (optional):_** All Ryowa Links Said "Protocol Disabled"

**Comment by LaneSh4d0w** [comment]
SSL Error : Certificate valid for ntv1.mov3.co, but not ntv.mov3.co

https://ntv1.mov3.co/hls/ntv.m3u8

**Comment by yuyuemolisha** [comment]
miss all

**Comment by LaneSh4d0w** [comment]
> 
> 
> **_Channel Name:_** Nippon TV
> **_Broken Link (from playlist):_** http://redlabmcdn.s.llnwi.net/nv02/ryowa3hd/playlist.m3u8
> 
> **_Possible Replacement (optional):_** https://ntv.mov3.co/hls/ntv.m3u8
> **_Notes (optional):_** All Ryowa Links Said "Protocol Disabled"

http://redlabmcdn.s.llnwi.net/nv01/ryowa3hd/playlist.m3u8 ? Might be geo-locked, since I have no info on my side.

**Comment by heroku-miraheze** [comment]
Is geo-locked. @LaneSh4d0w

**Comment by LaneSh4d0w** [comment]
http://redlabmcdn.s.llnwi.net/nv01/ryowa3hd/playlist.m3u8 using a Japanese VPN, it keeps telling me 503

I've retried the NV02, it sent me, in base64 "protocol disabled"

**Comment by LaneSh4d0w** [comment]
Same using a South Korean IP.
