### ISSUE TITLE
Fix: TRT 1 - Turkish TV

### ISSUE THREAD

**Issue by deetony** [iptv-org/iptv#3599]
**_Channel Name:_** TRT 1
**_Broken Link (from playlist):_** https://tv-trt1.live.trt.com.tr/master.m3u8
**_Possible Replacement (optional):_** https://tv-trt1.medya.trt.com.tr/master_720.m3u8
**_Notes (optional):_** xxx

**Comment by LaneSh4d0w** [comment]
Thanks for notifying. Fixing all the links.
