### ISSUE TITLE
Thailand Channel Requests

### ISSUE THREAD

**Issue by caten0** [iptv-org/iptv#3602]
please grab thai channel url from website on:
https://tv.trueid.net/live
https://tv.trueid.net/live/australia-network

**Comment by LaneSh4d0w** [comment]
https://tv.trueid.net/apis/home?lang=th&channelSlug=true4u (contains all channels IDs)

Need authorization : Basic MDJhNWI6YjAzNmM0Nw== (that's BasicAuth for you, Base64 encoded user:pass)

POST https://tv.trueid.net/apis/player

JSON = {"channelId":"*insert channel ID here*,"drm":"aes","lang":"th"}

You get a JSON in return, containing the freshly generated link.

There seem to be a lot of those into this website... it's going to be painful to reference them all.

**Comment by freearhey** [comment]
@caten0 Please read the [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel) next time before posting your request.
