### ISSUE TITLE
ESPN Deportes

### ISSUE THREAD

**Issue by brunochaves91** [iptv-org/iptv#3621]
**Channel Name: ESPN DEPORTES
**Country: US
**Language: Spanish
**Website:** xxx
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
Since I can't really define if it's a specific channel or not :

``#EXTINF:-1,ESPN 2 Latin Co
http://186.101.216.211:8000/play/a02k
#EXTINF:-1,ESPN 3 na
http://186.101.216.211:8000/play/a0cz
#EXTINF:-1,ESPN Co
http://186.101.216.211:8000/play/a02l
#EXTINF:-1,ESPNe
http://186.101.216.211:8000/play/a0e4
#EXTINF:-1,ESPn
http://186.101.216.211:8000/play/a0e3``

**Comment by Toei79** [comment]
question those where come from? that ip address ?
just want know its kind temporal i see several from those ip + structure channels  feels temporal channels.

**Comment by LaneSh4d0w** [comment]
Astra Control Panel type of channels. Astra is a satellite, so I suppose those are servers linked to the diffusion of those channels for the Astra satellite.

(the ones I've found might be unsecure IPs)

**Comment by Toei79** [comment]
> 
> 
> Astra Control Panel type of channels. Astra is a satellite, so I suppose those are servers linked to the diffusion of those channels for the Astra satellite.
> 
> (the ones I've found might be unsecure IPs)

okay so maybe those be temporal it be dead eventually?

what means insecure? for us? sorry im noob on this,

**Comment by LaneSh4d0w** [comment]
Those shouldn't be as temporal as Xtream-Codes servers are.

By unsecure I meant those aren't supposed to be in the wild, especially if
they're supposed to fuel the Astra satellites.

**Comment by Dum4G** [comment]
> okay so maybe those be temporal it be dead eventually?
Everything is temporal, even us :) Question is, for how long would it be freely available

**Comment by Toei79** [comment]
> 
> 
> > okay so maybe those be temporal it be dead eventually?
> 
> Everything is temporal, even us :) Question is, for how long would it be freely available

i know man.

i never touch iptv thing until i get fiber optic in my area , i was really lucky , before i deal with data cap by comcast.  1tb. now im free.

by nature of those channels , type of channels those be have a short period of life. 

i usually try check really old playlists so if i get something alive there it can be good , been for so long are a safe bet.

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/3145

**Comment by Dum4G** [comment]
Won't add due to DMCA notice we had

**Comment by freearhey** [comment]
https://github.com/github/dmca/blob/master/2020/09/2020-09-16-dfl.md
