### ISSUE TITLE
Add: KurdsatNews & Net TV

### ISSUE THREAD

**Issue by diaqad** [iptv-org/iptv#3624]
**Channel Name:**  Kurdsatnews
**Country:** Kurdistan, Iraq
**Language:** Kurdish
**Website:** https://kurdsatnews.com/
**Stream URL (optional):** https://kurdsatnews.com/Live.aspx
**Notes (optional):** xxx

---------

*Channel Name:** Net Tv
**Country:** Kurdistan, Iraq
**Language:** Kurdish
**Website:** http://live.netkurd.tv/live.aspx
**Stream URL (optional):** http://live.netkurd.tv/
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
# https://kurdsatnews.com/Live.aspx
#EXTINF:-1,Kurdsatnews
https://ikomg2.mmdlive.lldns.net/ikomg2/107b7df8f5444d778f349100739a09cd/manifest.m3u8

#EXTINF:-1,Kurdsatnews
https://ikomg2.mmdlive.lldns.net/ikomg2/107b7df8f5444d778f349100739a09cd/chunklist_b3128000.m3u8

not sure if /107b7df8f5444d778f349100739a09cd/ is token or not , will look back in 24hr if so


# http://live.netkurd.tv/live.aspx
#EXTINF:-1,Net TV
http://nettvstreampaid.flashmediacast.com:1935/nettvstreampaid/livestream/playlist.m3u8
#EXTINF:-1,Net TV
http://nettvstreampaid.flashmediacast.com:1935/nettvstreampaid/livestream/chunklist_w1997814403.m3u8

**Comment by diaqad** [comment]
Thank you som much!

**Comment by LaneSh4d0w** [comment]
> 
> # https://kurdsatnews.com/Live.aspx
> 
> #EXTINF:-1,Kurdsatnews
> https://ikomg2.mmdlive.lldns.net/ikomg2/107b7df8f5444d778f349100739a09cd/manifest.m3u8
> 
> #EXTINF:-1,Kurdsatnews
> https://ikomg2.mmdlive.lldns.net/ikomg2/107b7df8f5444d778f349100739a09cd/chunklist_b3128000.m3u8
> 
> not sure if /107b7df8f5444d778f349100739a09cd/ is token or not , will look back in 24hr if so
> # http://live.netkurd.tv/live.aspx
> 
> #EXTINF:-1,Net TV
> http://nettvstreampaid.flashmediacast.com:1935/nettvstreampaid/livestream/playlist.m3u8
> #EXTINF:-1,Net TV
> http://nettvstreampaid.flashmediacast.com:1935/nettvstreampaid/livestream/chunklist_w1997814403.m3u8

Looks like a channel ID to me.
