### ISSUE TITLE
Add: Gali Kurdistan TV & Speda TV & Sterk TV

### ISSUE THREAD

**Issue by diaqad** [iptv-org/iptv#3640]
**Channel Name:** Gali Kurdistan
**Country:** Kurdistan, Iraq
**Language:** Kurdish
**Website:** https://www.gksat.tv/
**Stream URL (optional):** http://gkhd.live/
**Notes (optional):** xxx

**Channel Name:** Speda TV
**Country:** Kurdistan, Iraq
**Language:** Kurdish
**Website:** http://speda.net/index.php/ku/
**Stream URL (optional):** http://speda.net/speda.html
**Notes (optional):** xxx

**Channel Name:** SterkTV
**Country:** Kurdistan
**Language:** Kurdish
**Website:** https://sterktv.net/
**Stream URL (optional):** https://sterktv.net/live/
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
#EXTINF:-1,Gali Kurdistan  [Not 24/7]
http://51.75.66.91:8080/gksat.mp4

#EXTINF:-1,Speda TV (720p)
http://liveshell.net:1935/live/speda084k/playlist.m3u8

#EXTINF:-1,SterkTV (720p)
https://602ccc850c9bb.streamlock.net/sterktv/smil:sterk.smil/playlist.m3u8

**Comment by diaqad** [comment]
Thank you, but Gali Kurdistan TV has no **sound**, can you fix it?
