### ISSUE TITLE
Suggestion to removing links from `http://190.2.154.164`

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#365]
I personally have never seen these links work, I always get only HTTP error 903.

But maybe it's just me so unlucky. Please let me know if everything works for you. And if you know, write the GMT time at which the broadcasts work for sure.

Here is a list of channels in question: https://github.com/iptv-org/iptv/search?q=http%3A%2F%2F190.2.154.164&unscoped_q=http%3A%2F%2F190.2.154.164

**Comment by garywhite207** [comment]
I saw them work once, then they stopped working completely and haven't come back up. Sadly, the links from http://185.246.209.109 also appear to have stopped working too.

**Comment by freearhey** [comment]
@garywhite207 You are right about http://185.246.209.109, links have already been deleted.

**Comment by boomski** [comment]
I Suggest we remove these links they are most of the time offline

**Comment by freearhey** [comment]
Ok, then I will try to remove all links in the near future and do PR.
