### ISSUE TITLE
Al Jadeed TV

### ISSUE THREAD

**Issue by Mhamadbhssein** [iptv-org/iptv#3659]
**Channel Name:** Al Jadeed TV
**Country:** Lebanon 
**Language:** Arabic 
**Website:** aljadeed.tv
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
Only Place ive found so far https://www.elahmad.com/tv/live/sl.php?id=aljadeed    
Cant pull it out for now  dash stream  .mpd + widevine  ..

**Comment by LaneSh4d0w** [comment]
Found a xtream-codes disguised stream : http://arabica.teledunet.com:8080/live/azrotv/azrotv2021/1148.m3u8

**Comment by Sphinxroot** [comment]
they come from http://azrotv.com/    and need #EXTVLCOPT:http-referrer=http://azrotv.com/pyr/dnt/?id=1148  but im not  tempted to add xtream-code here ...

**Comment by LaneSh4d0w** [comment]
Nope, better not. Was just telling that *it exists*

Le sam. 24 juil. 2021 à 12:29, Sphinxroot ***@***.***> a
écrit :

**Comment by Dum4G** [comment]
Closed in favor of #2347
