### ISSUE TITLE
SBS golf channel shows wrong channel

### ISSUE THREAD

**Issue by devhyunjae** [iptv-org/iptv#366]
![83](https://user-images.githubusercontent.com/12890257/65938073-ef095080-e45c-11e9-9375-54f1481201af.gif)

- when: click sbs golf channel
- then: shows jtbc golf channel
- expected: shows sbs golf channel

**Comment by boomski** [comment]
Yes, Channel name must be changed to JTBC Golf

**Comment by devhyunjae** [comment]
@boomski no mate. JTBC golf channel alreay exists. Need to show SBS golf

**Comment by freearhey** [comment]
Added through PR #389
