### ISSUE TITLE
Fix: HBO Malaysia

### ISSUE THREAD

**Issue by jdkeloth** [iptv-org/iptv#3662]
**_Channel is Name:_** HBO Malaysia 
**_Broken Link (from Malaysia Playlist):_** http://50.7.161.82:8278/streams/d/Hbo/playlist.m3u8
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** Was working yesterday and it is now down

**Comment by LaneSh4d0w** [comment]
![vlcsnap-2021-07-24-16h28m31s246](https://user-images.githubusercontent.com/30985701/126871600-ddfa5198-bc0a-47f1-ac5d-94b2c916db9c.png)

**Comment by jdkeloth** [comment]
Thanks for that, stream is now working
