### ISSUE TITLE
Fix: National Geographic Wild

### ISSUE THREAD

**Issue by jdkeloth** [iptv-org/iptv#3663]
**_Channel Name:_** National Geographic Wild
**_Broken Link (from United States playlist):_** http://50.7.161.82:8278/streams/d/Natgeowild/playlist.m3u8
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** Was working yesterday and now has stopped working

**Comment by LaneSh4d0w** [comment]
![vlcsnap-2021-07-24-16h27m40s406](https://user-images.githubusercontent.com/30985701/126871558-25ef82db-c987-4652-9bce-6806544dcd33.png)

**Comment by jdkeloth** [comment]
Thanks for fixing it. Stream is back but is buffering a lot.

**Comment by LaneSh4d0w** [comment]
Like any server, it can have his bad times :)
