### ISSUE TITLE
Fix: Celestial Movies [Malaysia]

### ISSUE THREAD

**Issue by jdkeloth** [iptv-org/iptv#3664]
**_Channel Name:_** Celestial Movies
**_Broken Link (from Malaysia playlist):_** http://210.210.155.35/qwr9ew/s/s33/index.m3u8
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** Was working a few days ago but is now not working

**Comment by Sphinxroot** [comment]
its back online  ... https://i.imgur.com/iElAuy0.png

**Comment by jdkeloth** [comment]
Thanks for that. I presume link still remains?

**Comment by jdkeloth** [comment]
Remains the same I mean
