### ISSUE TITLE
http://45.126.83.51/uq2663/h/h05/index.m3u8 is not Metro TV channel

### ISSUE THREAD

**Issue by hillz2** [iptv-org/iptv#367]
It's located under `iptv/channels/id.m3u` 
`http://45.126.83.51/uq2663/h/h05/index.m3u8` is not a link for `Metro TV` please get rid of it.

**Comment by boomski** [comment]
http://45.126.83.51/uq2663/h/h05/index.m3u8  is also dead , so must be removed

**Comment by freearhey** [comment]
@boomski strange, but this link works fo me. Only it shows Fight Sport channel (https://www.fightsports.tv/)

**Comment by boomski** [comment]
@freearhey  I tested the stream on http://streamtest.in then i get Error. when i tested it with vlc player it plays , but it is constantly buffering not a joy to watch

**Comment by freearhey** [comment]
@boomski http://streamtest.in also gives me "Done with error". But through VLC everything works fine for me, without any friezes.
