### ISSUE TITLE
Add: Ajman TV

### ISSUE THREAD

**Issue by tilfizyawn** [iptv-org/iptv#3671]
**Channel Name:** Ajman TV
**Country:** AE
**Language:** Arabic
**Website:** https://www.ajmantv.com/
**Stream URL (optional):** curl -s 'https://playback.dacast.com/content/access?contentId=116648_c_480929&provider=dacast' 

but requires extracting

```
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Arabic" tvg-logo="https://mk0ajmantvb4ih3ifdec.kinstacdn.com/wp-content/uploads/2019/07/logo_header_2-1.png" tvg-country="AE" group-title="",Ajman TV
```

**Comment by LaneSh4d0w** [comment]
On it.

**Comment by tilfizyawn** [comment]
Thanks

**Comment by LaneSh4d0w** [comment]
Took a bit longer because I've seen referrer tokens weren't useful, so I've cleaned my code on same instance.

There you go : https://iptv-all.lanesh4d0w.codes/saudiarabia/ajman

**Comment by tilfizyawn** [comment]
Thanks, but it didn't work for me. Maybe it's ip specific

**Comment by LaneSh4d0w** [comment]
Weird, it works on my side : 

![vlcsnap-2021-07-24-18h09m24s492](https://user-images.githubusercontent.com/30985701/126874438-4e37635c-7ee9-4c02-9221-c671648612ae.png)

**Comment by tilfizyawn** [comment]
It works now

**Comment by tilfizyawn** [comment]
Ajman is in AE BTW

https://www.almuradgroup.com/ajman-independent-studios/

**Comment by LaneSh4d0w** [comment]
Oops. I'm gonna rectify this. I thought about something else.

**Comment by LaneSh4d0w** [comment]
Wait a minute before using it : https://iptv-all.lanesh4d0w.codes/emirates/ajman

**Comment by tilfizyawn** [comment]
Thanks added
