### ISSUE TITLE
Channels missing

### ISSUE THREAD

**Issue by ITV4Free** [iptv-org/iptv#368]
CTV 24/7 News
CTV canada channels(toronto,ottawa,vancover,ect)

**Comment by freearhey** [comment]
- [x] CTV News
https://github.com/iptv-org/iptv/blob/030e60d9a06363e7b1bf30ea94b6195555acf563/channels/ca.m3u#L64-L65
- [ ] [CTV News  Toronto](https://toronto.ctvnews.ca/)
- [ ] [CTV News Ottawa](https://ottawa.ctvnews.ca/)
- [ ] [CTV News Vancouver](https://bc.ctvnews.ca/)

**Comment by freearhey** [comment]
Closed in favor #1941
