### ISSUE TITLE
Add: Persian Channels

### ISSUE THREAD

**Issue by MH140000** [iptv-org/iptv#3688]
List of requests for Persian channels from other issues:

https://github.com/iptv-org/iptv/discussions/3633
please add these channels to persian language
thanks.
If you find a working link to a channel from the list you can add it directly to the playlist by making a pull request, just read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#add-or-replace-a-stream) before you do it.

**Comment by MH140000** [comment]
Streams at https://github.com/iptv-org/iptv/discussions/3633 work well and many people RE STREAM them and sell them.

**Comment by Dum4G** [comment]
Bartar Tv - shows a few seconds chunk atm, isn't live stream
Channel One - token has expired

**Comment by MH140000** [comment]
yes. bartar tv isn't working but channel one is worked very good.
channel one:
https://2nbyjjx7y53k-hls-live.5centscdn.com/cls040317/0070c5b7ef083bdc8de09065c61a34d8.sdp/playlist.m3u8

**Comment by Dum4G** [comment]
I'm having error 401 on this one

**Comment by MH140000** [comment]
i test via vlc and with vpn and without vpn, it's work!

**Comment by MH140000** [comment]
If possible, please add channels faster. Profiteers have started selling these streams.

**Comment by Dum4G** [comment]
Azadi is not working in VLC, though you can get a playlist file if you bypass invalid certificate
