### ISSUE TITLE
Fix: BeIN sports arabic

### ISSUE THREAD

**Issue by oranjekikker** [iptv-org/iptv#3707]
**_Channel Name:_** beIN Sports 1
**_Broken Link (from playlist):_** languages/ara 
**_Notes (optional):_** all 10 BeIN Sports links are broken too.

**Comment by jadmust** [comment]
Channel Name: beIN Sports 
Broken Link (from playlist): languages/ara
Notes (optional): all 10 BeIN Sports links are broken too.
