### ISSUE TITLE
Add: HLN(640p, Lowest Bandwidth)

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#3713]
**Channel Name:** HLN(640p)
**Country:** USA
**Language:** English
**Website:** 
**Stream URL (optional):** https://turnerlive.warnermediacdn.com/hls/live/586496/cnngo/hln/VIDEO_3_1464000.m3u8
**Notes (optional):** Lowest Resolution of HLN(640p)

**Comment by MapGuy11** [comment]
PULL REQUEST THXS :)

**Comment by MapGuy11** [comment]
Will be Solved with #3717

**Comment by MapGuy11** [comment]
#3717
