### ISSUE TITLE
Add: [adult swim]Canada

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#3714]
**Channel Name:** [adult swim]Canada(24/7 Channel)
**Country:** Canada
**Language:** English
**Website:** xxx
**Stream URL (optional):** http://31.220.41.88:8081/live/us-cartoon.stream/playlist.m3u8?token=null
**Notes (optional):** Link said Cartoon Network US, But It Looks Like Shows [adult swim]Canada. 
Working in Pot Player and GSE Smart Player

**Comment by Dum4G** [comment]
It's looping one second chunk to me

**Comment by Central302** [comment]
Currently Working

**Comment by z0mbieslayer** [comment]
Reopening to see if anyone has a new source? Haven't been able to find one.
