### ISSUE TITLE
Add: Nick East

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#3715]
**Channel Name:** Nick East
**Country:** USA
**Language:** English
**Website:** 
**Stream URL (optional):** http://31.220.41.88:8081/live/us-nick.stream/playlist.m3u8
**Notes (optional):** Works in GSE Smart IPTV and Pot Player

**Comment by nickpythonluajava** [comment]
what's up with the subtitles?

**Comment by nickpythonluajava** [comment]
im gonna add this to my m3u playlist

**Comment by nickpythonluajava** [comment]
it doesnt work anymore apparently lol

**Comment by ironboy36** [comment]
Upload the playlist.m3u8)
