### ISSUE TITLE
Sony Ten 3 HD

### ISSUE THREAD

**Issue by shahidhasanzai** [iptv-org/iptv#3716]
Please Add sony ten 3 HD 1080p pixels channels , i will thankfull of you

**Comment by Dum4G** [comment]
#EXTINF:-1 tvg-logo="https://picon-13398.kxcdn.com/sonyten1in.jpg" group-title="Sports🏆" ,Sony Ten 1 HD
http://103.153.39.34:8000/play/a042/index.m3u8
#EXTINF:-1 tvg-logo="https://picon-13398.kxcdn.com/sonyten2in.jpg" group-title="Sports🏆",Sony Ten 2 HD
http://103.153.39.34:8000/play/a05r/index.m3u8
#EXTINF:-1 tvg-logo="https://picon-13398.kxcdn.com/sonyten3in.jpg" group-title="Sports🏆",Sony Ten 3 HD
http://103.153.39.34:8000/play/a049/index.m3u8

**Comment by shahidhasanzai** [comment]
stucking and stopping this link

**Comment by Dum4G** [comment]
Available on http://sony247channels.akamaized.net servers and is token protected. Whoever bypass this gets a cookie

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/1934
