### ISSUE TITLE
Add: Channel 5

### ISSUE THREAD

**Issue by badprogramshere** [iptv-org/iptv#3721]
**Channel Name:** Channel 5
**Country:** Singapore
**Language:** English
**Website:** mewatch.sg
**Stream URL (optional):** https://rest-as.ott.kaltura.com/api_v3/service/assetFile/action/playManifest/partnerId/147/assetId/316288/assetType/media/assetFileId/11719964/contextType/PLAYBACK/isAltUrl/False/a.m3u8
**Notes (optional):** 720p stream, no DRM. Seems that 1080p streams use 3 different types of DRM (Widevine, PlayReady, and FairPlay)

**Comment by Sphinxroot** [comment]
must be geo   403  but posted 1 https://github.com/iptv-org/iptv/issues/1983#issuecomment-887870080
