### ISSUE TITLE
Add: Channel 8

### ISSUE THREAD

**Issue by badprogramshere** [iptv-org/iptv#3722]
**Channel Name:** Channel 8
**Country:** Singapore
**Language:** Chinese
**Website:** mewatch.sg
**Stream URL (optional):** https://rest-as.ott.kaltura.com/api_v3/service/assetFile/action/playManifest/partnerId/147/assetId/260581/assetType/media/assetFileId/11719965/contextType/PLAYBACK/isAltUrl/False/a.m3u8
**Notes (optional):**

**Comment by Sphinxroot** [comment]
must be geo   i get 403

**Comment by LaneSh4d0w** [comment]
This was the kind of links I was expecting actually. Had talked to it on the other Singaporean discussion that if there was a Kaltura link, this could be the key.

Someone got into it. It's geo-locked to Singapore.
