### ISSUE TITLE
Add: Suria

### ISSUE THREAD

**Issue by badprogramshere** [iptv-org/iptv#3723]
**Channel Name:** Suria
**Country:** Singapore
**Language:** Malay
**Website:** mewatch.sg
**Stream URL (optional):** https://rest-as.ott.kaltura.com/api_v3/service/assetFile/action/playManifest/partnerId/147/assetId/237652/assetType/media/assetFileId/11719963/contextType/PLAYBACK/isAltUrl/False/a.m3u8
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
must be geo i get a 403

i posted some here https://github.com/iptv-org/iptv/issues/1983#issuecomment-887870080
