### ISSUE TITLE
Add: Canal 13

### ISSUE THREAD

**Issue by garabit** [iptv-org/iptv#3726]
**Channel Name:** Canal 13 Sinart
**Country:** Costa Rica
**Language:** Spanish
**Website:** https://costaricamedios.cr/envivo
**Stream URL (optional):** https://stream-03.nyc.dailymotion.com/sec(0HE75RGSqqnhnSdEMl12Zb2HJIphEv5GlmKxpQKnXyY)/dm/3/x7vh8g3/d/live-2.m3u8
**Notes (optional):** Another stream URL, perhaps of different image quality https://dai.ly/x7vh8g3

**Comment by LaneSh4d0w** [comment]
https://linkastream.co/headless?url=https://www.dailymotion.com/video/x7vh8g3
