### ISSUE TITLE
Teletica 7

### ISSUE THREAD

**Issue by garabit** [iptv-org/iptv#3732]
**Channel Name:** Teletica 7
**Country:** Costa Rica
**Language:** Spanish
**Website:** https://www.teletica.com/vivo?canal=teletica-7
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
Teletica  7 logo https://i.imgur.com/GeIK8rC.png

TN7 Meridiana logo  https://i.imgur.com/JLCBRNE.jpg

Stream On DM
https://www.dailymotion.com/video/x29e3wg

https://stream-03.nyc.dailymotion.com/sec(jlR0lJnpjfic8bXdlVDO59QcKQmJ3ErAy8vP3ViOIKs)/dm/3/x29e3wg/d/live-3.m3u8

channel name is a bit confusing

**Comment by garabit** [comment]
Perhaps it could be named as "Teletica Canal 7".

**Comment by LaneSh4d0w** [comment]
Geo-locked channel for me.

**Comment by freearhey** [comment]
It works for me.
![image](https://user-images.githubusercontent.com/7253922/128118513-a297a80e-9fe0-494d-aca3-f02d9d797c07.png)

**Comment by jkemp814** [comment]
Works here in the southwest also

**Comment by LaneSh4d0w** [comment]
Still nothing on my side, are they alternating between geo-lock and public programming ?

![image](https://user-images.githubusercontent.com/30985701/128150202-5aefa93d-1f1f-48ce-8a10-fa2e331530da.png)

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/3990
