### ISSUE TITLE
Add: Pennsylvania Cable Network

### ISSUE THREAD

**Issue by FpFan65** [iptv-org/iptv#3733]
PCN Pennsylvania Cable Net

**Channel Name:** PCN Pennsylvania Cable Net 
**Country:** US
**Language:** English
**Website:** bozztv.com
**Stream URL (optional):** https://bozztv.com/teleyupp/teleup-pcnhd/tracks-v2a1/mono.m3u8
**Notes (optional):** xxx

**Comment by MapGuy11** [comment]
Will be referenced (#3733)
