### ISSUE TITLE
Add: ABC 30 St. Louis (KDNL-TV)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3742]
**Channel Name:** ABC 30 St. Louis (KDNL-TV)
**Country:** US
**Language:** English
**Website:** https://abcstlouis.com/
**Stream URL (optional):** https://abcstlouis.com/watch
**Notes (optional):** https://content-ausc1.uplynk.com/31f2ce5c1e0f4fbe965cc07c8ab53ef9/e.m3u8?tc=1&exp=1627588599&rn=226041&ct=a&cid=31f2ce5c1e0f4fbe965cc07c8ab53ef9&sig=bac0306c3de156f6a04b59202adf556367c00970f896c6e58b4a3305b508f0f2&pbs=f5d8052221404fcf9baadf9dcf16f66b

Thumbnail
https://abcstlouis.com/resources/defaults/kdnl/large16x9.jpg

**Comment by LaneSh4d0w** [comment]
Link can be shortened to https://content.uplynk.com/31f2ce5c1e0f4fbe965cc07c8ab53ef9.m3u8

**Comment by LaneSh4d0w** [comment]
There's also a WDJT Webcam on this one : https://content.uplynk.com/b99c0de0d1614f3f8f5b0d7fbadcb47d.m3u8

**Comment by jkemp814** [comment]
WDJT-TV, virtual channel 58, is a CBS-affiliated television station licensed to Milwaukee, Wisconsin

**Comment by LaneSh4d0w** [comment]
Thing is I don't know if it's reliable to keep this, because I don't know if the signature or token is changed. The link generation is done on the backend. I don't think I can get the link from an endpoint or something.

**Comment by jkemp814** [comment]
That main channel is live-streaming a view of the White House

**Comment by jkemp814** [comment]
Okay, seems to lock on using the browser.

**Comment by LaneSh4d0w** [comment]
Aaaaah wait... I might have a solution, but not guaranteed it'll work. Let me see.

**Comment by jkemp814** [comment]
Also, I meant to mention something about the Firefox extension I use for checking links inside the browser. VLC might be listed in your mine-types. I remember deleting my handlers.json file and then restarting Firefox. It will create another one. VLC was listed in the mine-types on the General page near the bottom. There was no way to edit or clear out old entries. Firefox will ask what application 'Open with' if you need to restore any other types. I would remove the extension and after clearing the mine-types reinstall it. That may make it work. It will add an entry for DASH-HLS.

**Comment by LaneSh4d0w** [comment]
Just tested what I thought, can't seem to make it.

**Comment by MapGuy11** [comment]
They don't even have a news department so all the feed we are going to get the Sinclair national feed.
