### ISSUE TITLE
MTV Taiwan

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#3757]
**Channel Name:** MTV Taiwan
**Channel ID:** MTVTaiwan.tw
**Country:** Republic of China (Taiwan)
**Language:** Mandarin Chinese
**Website:** https://www.mtv.com.tw/
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/3145

**Comment by freearhey** [comment]
Closed in favor of #12289
