### ISSUE TITLE
Disney Junior Japan

### ISSUE THREAD

**Issue by nickjrukfan** [iptv-org/iptv#3762]
Could you Add Disney junior Japan? I really wanna see what programs are on the channel and I wanna see the japanese dubs of shows

**Channel Name:** Disney Junior Japan
**Channel ID:** DisneyJuniorJapan.jp
**Country:** Japan
**Language:** Japanese
**Website:** Disney.co.jp
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
The closest you'll get from now is the "Disney Junior on Disney Channel" satellite streams over night (the Ryowa links we got) (11 pm / 1 am UTC+2)

To get that one, unless the Ryowa server got it, we would need to rely on Xtream-Codes servers, and that's not the best choice AT ALL.

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/3145

**Comment by Alstruit** [comment]
Resolved #9032
