### ISSUE TITLE
http://ocb-lh.akamaihd.net/i/ocb_mpls_tvmc1@383606/master.m3u8 is not a Cuban channel

### ISSUE THREAD

**Issue by whippiii** [iptv-org/iptv#378]
Radio y Televisión Martí is broadcasted from the USA.

**Comment by freearhey** [comment]
Channels are sorted not by the country of the broadcast source, but by the countries in which they are broadcast. 

"Radio Televisión Martí...transmits news in Spanish to Cuba" (Source: https://en.wikipedia.org/wiki/Radio_y_Televisi%C3%B3n_Mart%C3%AD)
