### ISSUE TITLE
Fix: CBS News

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3824]
**_Channel Name:_** CBS News
**_Broken Link (from playlist):_** http://cbsnhls-i.akamaihd.net/hls/live/264710/cbsn_hlsprod_2/master.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** This is a 0:59 second video. Runs then stops. There are five of these channels already.  This one is at line 741 in the us.m3u playllist. It's not any of those uploaded recently.

**Comment by Sphinxroot** [comment]
https://www.cbsnews.com/live/

#EXTINF:-1 tvg-logo="https://i.imgur.com/Qu9NAwe.png" group-title="News",CBSN 1
https://dai.google.com/linear/hls/event/Sid4xiTQTkCT1SLu6rjUSQ/master.m3u8

#EXTINF:-1 tvg-logo="https://i.imgur.com/HbOrvOn.jpg" group-title="News",CBSN 2
https://cbsnewshd-lh.akamaihd.net/i/CBSNHD_7@199302/master.m3u8

#EXTINF:-1 tvg-logo="https://i.imgur.com/YCzf1jp.png" group-title="News",CBSN National
https://cbsn-us-cedexis.cbsnstream.cbsnews.com/out/v1/55a8648e8f134e82a470f83d562deeca/master.m3u8

**Comment by jkemp814** [comment]
Thanks, all three of those play nicely.

**Comment by jkemp814** [comment]
I just checked all three of those links are in the playlist.  Line: 744, 746, and 750. All titled CBS News. I will rename those and use the CBSN logo.

**Comment by jkemp814** [comment]
So do I just delete the channel I originally posted about? Or can one of you delete it?

**Comment by Dum4G** [comment]
If it won't fix itself within a fews days you can freely remove it

**Comment by MapGuy11** [comment]
Here you go: https://cbsn-us-cedexis.cbsnstream.cbsnews.com/out/v1/55a8648e8f134e82a470f83d562deeca/master.m3u8

**Comment by jkemp814** [comment]
That link is already in the playlist. I will delete the channel mentioned at the top. It's still only streaming for 0:59 seconds.

**Comment by MapGuy11** [comment]
@jkemp814 Sounds Good!

**Comment by MapGuy11** [comment]
@jkemp814  Can I close this then?

**Comment by jkemp814** [comment]
Yes

**Comment by jkemp814** [comment]
Sent change already

**Comment by MapGuy11** [comment]
Thanks All!
