### ISSUE TITLE
Add: UK Channels

### ISSUE THREAD

**Issue by pouyiouk** [iptv-org/iptv#3829]
**Channel Name:** Channel 4 Television Corporation
**Country:** United Kingdom
**Language:** English
**Website:** https://www.channel4.com/
**Notes (optional):** Channel 4 is comprised out of six(6) TV channels

- ALL 4

- E4

- Film4

- More4

- 4Music

- 4seven

Current channels require an account on channel 4 website, but overall are free to view. No paywall. Geo-blocked to UK, VPN needed.

**Comment by trancer1994** [comment]
All Four is the streaming service. It is not a channel in itself.

**Comment by freearhey** [comment]
Please read the [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel) next time before posting a request.
