### ISSUE TITLE
Add: itv4(akamai Link)

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#3830]
**Channel Name:** itv4
**Country:** UK
**Language:** English
**Website:** xxx
**Stream URL (optional):** http://sportportal1.akamaized.net/hls/live/702647/itvlive/ITV4PORTAL2/master_Main600.m3u8
**Notes (optional):**  akamai Link.

**Comment by LaneSh4d0w** [comment]
Adaptive link is http://sportportal1.akamaized.net/hls/live/702647/itvlive/ITV4PORTAL2/master.m3u8
