### ISSUE TITLE
The Weather Channel

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#3843]
**_Channel Name:_** The Weather Channel
**_Broken Link (from playlist):_
https://weather-lh.akamaihd.net/i/twc_1@92006/index_2400_av-b.m3u8?sd=10&rebase=on
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** 
When Access it via Browser, it Said "Access Denied"

**Comment by Sphinxroot** [comment]
try those 

https://weather.newscdn.org/QHbAAy288jWeaaIkhBGjvA==,1627884166/1253851229/tracks-v1a1/mono.m3u8
https://weather.newscdn.org/QHbAAy288jWeaaIkhBGjvA==,1627884166/1253851229/index.m3u8

https://weather.newscdn.org/KIK8GPfjqsp3o1hQ4CrKuQ==,1627881939/1253851229/tracks-v1a1/mono.m3u8
https://weather.newscdn.org/KIK8GPfjqsp3o1hQ4CrKuQ==,1627881939/1253851229/index.m3u8

**Comment by MapGuy11** [comment]
@Sphinxroot 410 GONE

**Comment by MapGuy11** [comment]
Could Be Fixed If Someone had a C Band Dish Pointed At 131W 3780 H

**Comment by MapGuy11** [comment]
Is anyone good at deciphering a url from an android app? I am trying but can't get a good grip. https://play.google.com/store/apps/details?id=com.weathergroup.twc&hl=en_US&gl=US

**Comment by MapGuy11** [comment]
Requests are coming from this Akamai server 104.114.74.136
