### ISSUE TITLE
How should we determine the country of the channel?

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#385]
Sorting options:

1. (current) At the moment, the country of the channel is set depending on where this channel is officially available (so-called "broadcast area"). That is, if a channel is broadcast, for example, from the UAE, but is accessible throughout the Middle East, it falls into the International playlist. The same situation is with all other channels that may be available outside the country of production.

2. Another way to sort the channels is to use the country in which the channel is produced. In this case, for example, BBC World News will be in the UK playlist, even though it is available worldwide.

3. The third option is to sort the channels by the country of the broadcast provider. That is, if the channel broadcasts ISPs from Armenia, then this broadcast only falls into the playlist of Armenia, even if the channel itself is German (for example, DW).

All these approaches have their pros and cons, so it would be great if you said which option you like the most.

And yes, if you have any other sorting option, let us know in the comments.

**Comment by boomski** [comment]
The most logic seems to me Option 2
https://www.lyngsat.com/index.html  could be useful website to determine from where the channel is broadcasted

**Comment by freearhey** [comment]
@boomski In my opinion, the second option now also seems more correct.

But if we really choose this option, then it’s probably worth discussing what we will do when the channel is registered in several countries, for example RT UK. According to information from the same LyngSat, this channel is simultaneously Russian and British (https://www.lyngsat.com/tvchannels/en/RT-UK.html). And this situation is not rare. Should we put it at once in both playlists, or just one? What do you think?

Also in this case, all channels from the International playlist will also need to be sorted by specific countries.

But in general, if no one appears in the coming days with a serious argument against, then I think we can start sorting everything according to the second option.

**Comment by boomski** [comment]
@freearhey  For the example you mentioned , I think the best solution for this is placing them in both playlists , then there will be no discussion in which playlist it belongs.

**Comment by freearhey** [comment]
@boomski I’m usually not a big fan of duplicating links, but in this case I think you're right, it will simplify our work a lot.

**Comment by exodiver** [comment]
How about for the real multinational channels with wide coverage, you grouped them according to the language?

**Comment by freearhey** [comment]
@exodiver What do you mean by "real multinational channel"? Could you give an example of such a channel?

**Comment by freearhey** [comment]
We really have channels that cannot be attached to any country (for example DJing, Red Bull TV and etc.). But I think we can just leave them in the International playlist.

**Comment by freearhey** [comment]
Well, since no one seems to be against the second option, then I think we can consider the issue resolved. Now all channels will be sorted only by the country in which the channel is produced. And as @boomski suggested, you can use the [LyngSat](https://www.lyngsat.com/index.html) website  to determine the country of most channels.

On this I am closing this thread, but feel free to open a new issue if you decide to add something.
