### ISSUE TITLE
Disney Channel Canada East

### ISSUE THREAD

**Issue by bolandnick18** [iptv-org/iptv#3853]
**Channel Name:** Disney Channel Canada
**Channel ID:** DisneyChannelCanadaEast.ca
**Country:** Canada
**Language:** English
**Website:** disneychannel.ca
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Dum4G** [comment]
Being asked since 2019. Closed in favor of https://github.com/iptv-org/iptv/issues/3145

**Comment by freearhey** [comment]
Closed in favor of #12286
