### ISSUE TITLE
*Broken Link for NHK BS1*

### ISSUE THREAD

**Issue by AZEK611** [iptv-org/iptv#3856]
**_Channel Name:_** NHK BS1
**_Broken Link (from playlist):_** http://redlabmcdn.s.llnwi.net/jp04/bs01hd/playlist.m3u8

**Comment by AZEK611** [comment]
**Notes:** 

Hi. Just watching the Olympics right now, but the BS1 feed is broken, and as a result, can’t be watched on my IPTV player on my Android TV.

Created this Github account to make this feed issue.

**Comment by Central302** [comment]
All Ryowa Links were said "Unauthorized",
