### ISSUE TITLE
Fix: TOKYO MX1

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#3859]
**_Channel Name:_** TOKYO MX1
**_Broken Link (from playlist):_** http://redlabmcdn.s.llnwi.net/jp04/ryowa8hd/playlist.m3u8
**_Possible Replacement (optional):_** https://neetball.net/live/test3.m3u8

All Ryowa Link said "403 Unauthorized"

**Comment by LaneSh4d0w** [comment]
Thing is this server is maintained by a group of people and they often move channels over time. Wonder if this channel is gonna stay or not.

**Comment by Dum4G** [comment]
That's TV Tokyo link
