### ISSUE TITLE
Fix: Astro Hua Hee under my.m3u

### ISSUE THREAD

**Issue by ayong881128** [iptv-org/iptv#3863]
unable to play at all

**_Channel Name:_** Astro Hua Hee Dai
**_Broken Link (from playlist):_** http://185.180.221.194:8278/streams/d/Huahee/playlist.m3u8
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** xxx

**Comment by LaneSh4d0w** [comment]
Found out it was a sort of Xtream Codes alternative behind this.

Root leading to a "z-dashboard" page, same for this one : 50.7.161.82:8278/streams/man/z-​dashboard.php (which is owned by an IPTV service). Both are from the Netherlands.

**Comment by Angel6211** [comment]
Astro Wah Lai Toi also unable to play at all
