### ISSUE TITLE
Fox Business(720p) channel 1074 in News Category

### ISSUE THREAD

**Issue by drnick2** [iptv-org/iptv#3864]
Constant looping then freezing the last 2 days, channel will play for approximately 50 seconds then freeze playing the same content if you reload the channel or return at a later time.

**_Channel Name:_** xxx
**_Broken Link (from playlist):_** xxx
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** xxx

**Comment by MapGuy11** [comment]
http://199.66.95.244:8080/1/1172/index.m3u8?token=test

**Comment by drnick2** [comment]
@MapGuy11 Thanks but the link crashes on VLC, Tried on several computers same results.

**Comment by MapGuy11** [comment]
> @MapGuy11 Thanks but the link crashes on VLC, Tried on several computers same results. 

I got IP banned from the service so I guess it's a lost cause.

**Comment by drnick2** [comment]
@MapGuy11  Thanks for trying!

**Comment by LaneSh4d0w** [comment]
> 
> 
> http://199.66.95.244:8080/1/1172/index.m3u8?token=test

![image](https://user-images.githubusercontent.com/30985701/127921250-a0fa68ad-8bd0-41b2-8124-324108664eb4.png)

**Comment by MapGuy11** [comment]
@LaneSh4d0w Yeah all of there services are now 403
