### ISSUE TITLE
Add: France 2

### ISSUE THREAD

**Issue by adeit** [iptv-org/iptv#3874]
**Channel Name:** France 2
**Country:** FR
**Language:** French
**Website:** xxx
**Stream URL (optional):** http://edge9.iptvnetwork.net/live/france2/playlist.m3u8
**Notes (optional):**
Same as already present France 3, France 4, France 5 :
#EXTINF:-1 tvg-id="France2.fr" tvg-name="France 2" tvg-country="FR" tvg-language="French" tvg-logo="" group-title="",France 2
http://edge9.iptvnetwork.net/live/france2/playlist.m3u8

**Comment by MapGuy11** [comment]
Working on it!

**Comment by MapGuy11** [comment]
#3881
