### ISSUE TITLE
Ethiopian Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#3900]
List of requests for Ethiopian channels from other issues:

- [x] [Addis TV](https://ethiov.com/single-channel/161) (#3210)
- [x] [Ahadu TV](https://ethiov.com/single-channel/143) (#3210)
- [x] [Amhara TV](https://ethiov.com/single-channel/113) (#3210)
- [x] [Arts TV](https://ethiov.com/single-channel/122) (#3210)
- [x] [EBC Zena](https://ethiov.com/single-channel/116) (#3210)
- [x] [ESAT](https://ethiov.com/single-channel/134) (#3210)
- [x] [ETV Mezinagna](https://ethiov.com/single-channel/119) (#3210)
- [x] [Fana TV](https://ethiov.com/single-channel/114) (#3210)
- [x] [OBN](https://ethiov.com/single-channel/126) (#3210)
- [x] [Walta TV](https://ethiov.com/single-channel/567) (#3210)

**Comment by LaneSh4d0w** [comment]
Taking care of those.

**Comment by LaneSh4d0w** [comment]
Amhara TV : https://iptv-all.lanesh4d0w.codes/ethiopia/amhara-tv

**Comment by LaneSh4d0w** [comment]
Ahadu TV : https://iptv-all.lanesh4d0w.codes/ethiopia/ahadu-tv
Arts TV : https://iptv-all.lanesh4d0w.codes/ethiopia/arts-tv
ETV Zena : https://iptv-all.lanesh4d0w.codes/ethiopia/etv-zena

**Comment by LaneSh4d0w** [comment]
Majority of their streams (apart from Amhara) coming from their servers do not answer on chunklist retrieval anymore.

**Comment by LaneSh4d0w** [comment]
ETV Mezinagna : https://iptv-all.lanesh4d0w.codes/ethiopia/etv-mezinagna
Fana TV : https://iptv-all.lanesh4d0w.codes/ethiopia/fana-tv
Walta TV : https://iptv-all.lanesh4d0w.codes/ethiopia/walta
OBN : https://iptv-all.lanesh4d0w.codes/ethiopia/obn

**Comment by LaneSh4d0w** [comment]
All channels are there. Can't tell if 24/7 streams or not. Right now Amhara and Fana are reported working, the rest are dormant.
