### ISSUE TITLE
Channel 4 

### ISSUE THREAD

**Issue by argooseargus** [iptv-org/iptv#3902]
**Channel Name:** Channel 4
**Country:** United Kingdom
**Language:** English
**Website:** https://www.channel4.com/
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by argooseargus** [comment]
@Sphinxroot @Dum4G 
Thanks!

**Comment by argooseargus** [comment]
> 
> 
> Work in Kodi
> #EXTINF:-1 tvg-logo="https://i.imgur.com/VrzRKUE.jpg" group-title="",Channel4 (480p)
> https://www.streamaway.net/scripts/filtv.php/playlist.m3u8?ch=2
> 
> universal
> #EXTINF:-1 tvg-logo="https://i.imgur.com/VrzRKUE.jpg" group-title="",Channel4 (440p)
> http://stream.tvtap.live:8081/live/channel4.stream/playlist.m3u8

Sorry to bother, but any chance you have E4 too?

**Comment by Sphinxroot** [comment]
I got 100 + of those i will add them when ive finished 

#EXTINF:-1 tvg-logo="https://i.imgur.com/WlpL3ju.jpg" group-title="",E4 (480p)
https://www.streamaway.net/scripts/filtv.php/playlist.m3u8?ch=65


#EXTINF:-1,E4  offline for now
http://stream.tvtap.live:8081/live/e4.stream/playlist.m3u8

**Comment by argooseargus** [comment]
Okay, thanks so much!

**Comment by Sphinxroot** [comment]
your welcome ;)

**Comment by LaneSh4d0w** [comment]
> 
> 
> Work in Kodi
> #EXTINF:-1 tvg-logo="https://i.imgur.com/VrzRKUE.jpg" group-title="",Channel4 (480p)
> https://www.streamaway.net/scripts/filtv.php/playlist.m3u8?ch=2
> 
> universal
> #EXTINF:-1 tvg-logo="https://i.imgur.com/VrzRKUE.jpg" group-title="",Channel4 (440p)
> http://stream.tvtap.live:8081/live/channel4.stream/playlist.m3u8

1st link redirects to https://edge-1288-ch-gv.filmon.com/live/2.high.stream/playlist.m3u8

**Comment by Sphinxroot** [comment]
> > Work in Kodi
> > #EXTINF:-1 tvg-logo="https://i.imgur.com/VrzRKUE.jpg" group-title="",Channel4 (480p)
> > https://www.streamaway.net/scripts/filtv.php/playlist.m3u8?ch=2
> > universal
> > #EXTINF:-1 tvg-logo="https://i.imgur.com/VrzRKUE.jpg" group-title="",Channel4 (440p)
> > http://stream.tvtap.live:8081/live/channel4.stream/playlist.m3u8
> 
> 1st link redirects to a Filmon TV stream, but is forbidden once launched with this : https://edge-1288-ch-gv.filmon.com/live/2.high.stream/playlist.m3u8

yes  for other player it wont work but  kodi in playlistloader  it wont redirect  or stop   normaly its 30sec preview  on filmon https://i.imgur.com/QSbzpaw.png

**Comment by freearhey** [comment]
Closed in favor #1943

**Comment by freearhey** [comment]
Closed in favor #7104
