### ISSUE TITLE
Nippon TV

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#3909]
**Channel Name:** Nippon TV
**Country:** JPN
**Language:** Japanese
**Website:** xxx
**Stream URL (optional):** http://itskoi.dothome.co.kr/jptv.php?id=kanto_nippon
**Notes (optional):** Found from Someone's Repository in Github and it Owns ALL OTA Channels (Not BS/CS)

**Comment by LaneSh4d0w** [comment]
Redirects to http://1.179.247.11:1935/jptv/kanto_nippon_540/chunklist.m3u8

**Comment by LaneSh4d0w** [comment]
By the way, found out that the Ryowa server had more channels that we haven't found.

NTV G+ http://redlabmcdn.s.llnwi.net/jp01/cs01/index.m3u8
GOLF NETWORK http://redlabmcdn.s.llnwi.net/jp01/cs03/index.m3u8
KIDS http://redlabmcdn.s.llnwi.net/jp01/cs04/index.m3u8
NECO http://redlabmcdn.s.llnwi.net/jp01/cs05/index.m3u8
WOWOW Cinema http://redlabmcdn.s.llnwi.net/jp01/cs07/index.m3u8

**Comment by wakaka212** [comment]
Hey guys,
Sorry to hijack the thread but, no major (except NHK G) channel is working anymore for me...
Did you guys find a fix? 
The links posted on this thread too seem dead now.
I would love to access to TV Asahi, Fuji TV, NHK BS1 in particular.... 
Thanks!

**Comment by Dum4G** [comment]
There's no fix, all major channels were available from one source that is now protected

**Comment by yormuiri** [comment]
By the way found :

TBS
http://1.179.247.11:1935/jptv/kanto_tbs_540/chunklist.m3u8
Fuji Tv
http://1.179.247.11:1935/jptv/kanto_fuji_540/chunklist.m3u8

**Comment by yormuiri** [comment]
2nd find
It seem the links are same cdn.mydhtv.com

Kanto
NHK E
http://1.179.247.11:1935/jptv/kanto_nhk_edu_540/chunklist.m3u8
NHK G 
http://1.179.247.11:1935/jptv/kanto_nhk_g_540/chunklist.m3u8
TV Asahi
http://1.179.247.11:1935/jptv/kanto_tv_asahi_540/chunklist.m3u8
TV Tokyo
http://1.179.247.11:1935/jptv/kanto_tv_tokyo_540/chunklist.m3u8
Tokyo MX1
http://1.179.247.11:1935/jptv/kanto_tokyo_mx1_540/chunklist.m3u8
NHK G (Kansai)
http://1.179.247.11:1935/jptv/kansi_nhk_g_540/chunklist.m3u8

Kansai
ABC
http://1.179.247.11:1935/jptv/kansi_abc_asahi_540/chunklist.m3u8
TV Osaka
http://1.179.247.11:1935/jptv/kansi_tv_osaka_540/chunklist.m3u8
Kansai TV
http://1.179.247.11:1935/jptv/kansi_tv_540/chunklist.m3u8
YTV
http://1.179.247.11:1935/jptv/kansi_yormiuri_540/chunklist.m3u8
MBS (Kansai)
http://1.179.247.11:1935/jptv/kansi_mbs_540/chunklist.m3u8

**Comment by wakaka212** [comment]
>  cdn.jpth10.jpnettv.live
Thank you for your research! 
Unfortunately, they won't play in my players (mpv and IINA). How did you get them to work?

**Comment by Central302** [comment]
Nice! @luongz 
Sun-TV(Kansai)
 http://1.179.247.11:1935/jptv/kansi_sun_tv_540/chunklist.m3u8

**Comment by luongz** [comment]
> Nice! @luongz 
> Sun-TV(Kansai)
>  http://1.179.247.11:1935/jptv/kansi_sun_tv_540/chunklist.m3u8

Not work.

**Comment by LaneSh4d0w** [comment]
> 
> 
> Nice! @luongz
> Sun-TV(Kansai)
> http://1.179.247.11:1935/jptv/kansi_sun_tv_540/chunklist.m3u8

Answers for me, not 24/7 (test card right now)

**Comment by LaneSh4d0w** [comment]
> 
> 
> 2nd find
> It seem the links are same cdn.mydhtv.com
> cdn.jpth10.jpnettv.live
> Kanto
> NHK E
> http://1.179.247.11:1935/jptv/kanto_nhk_edu_540/chunklist.m3u8
> NHK G
> http://1.179.247.11:1935/jptv/kanto_nhk_g_540/chunklist.m3u8
> TV Asahi
> http://1.179.247.11:1935/jptv/kanto_tv_asahi_540/chunklist.m3u8
> TV Tokyo
> http://1.179.247.11:1935/jptv/kanto_tv_tokyo_540/chunklist.m3u8
> Tokyo MX1
> http://1.179.247.11:1935/jptv/kanto_tokyo_mx1_540/chunklist.m3u8
> NHK G (Kansai)
> http://1.179.247.11:1935/jptv/kansi_nhk_g_540/chunklist.m3u8
> 
> Kansai
> ABC
> http://1.179.247.11:1935/jptv/kansi_abc_asahi_540/chunklist.m3u8
> TV Osaka
> http://1.179.247.11:1935/jptv/kansi_tv_osaka_540/chunklist.m3u8
> Kansai TV
> http://1.179.247.11:1935/jptv/kansi_tv_540/chunklist.m3u8
> 
> MBS (Kansai)
> http://1.179.247.11:1935/jptv/kansi_mbs_540/chunklist.m3u8

Nice find, IP CN=cdn.th11.jpnettv.live

**Comment by LaneSh4d0w** [comment]
TBS : http://1.179.247.11:1935/jptv/kanto_tbs_540/chunklist.m3u8

**Comment by Central302** [comment]
It Looks Like These Link are Broken Now ( Not Working)
