### ISSUE TITLE
Use GitHub Page instead of GitHub Raw to serve files

### ISSUE THREAD

**Issue by SukkaW** [iptv-org/iptv#391]
See https://stackoverflow.com/questions/8779197/how-to-link-files-directly-from-github-raw-github-com

**Comment by freearhey** [comment]
Okay. I have enabled GitHub Pages support in the repository. If you wish, you can already use links to it, for example: `https://iptv-org.github.io/iptv/index.m3u`

As for the links in the documentation, it will take a little longer to update.

**Comment by freearhey** [comment]
Done.
