### ISSUE TITLE
ABC 7 New York NY (WABC-TV)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3913]
**Channel Name:** ABC 7 New York NY (WABC-TV)
**Country:** US
**Language:** English
**Website:** https://abc7ny.com
**Stream URL (optional):** https://abc7ny.com/watch
**Notes (optional):** https://content.uplynk.com/ext/72750b711f704e4a94b5cfe6dc99f5e1/080421-wabc-ctv-eveningupdate-vid.m3u8

**Comment by MapGuy11** [comment]
How about a full schedule OTA Stream?

**Comment by MapGuy11** [comment]
Will Be Solved #3922
