### ISSUE TITLE
CBS 17 Raleigh NC  (WNCN)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3916]
**Channel Name:** CBS 17 Raleigh NC  (WNCN)
**Country:** US
**Language:** English
**Website:** https://www.cbs17.com
**Stream URL (optional):** https://www.cbs17.com/live/
**Notes (optional):** https://dcs-live.apis.anvato.net/server/play/vAQDK34hMD2YF3J0/manifest.m3u8?encp=h_7OSE2zT2036vf-nLa--Q:LsySOTyIpndCRmCPAOlOoJ1F3P6F54E-Zj8rqZbZWt3sRz0T8Q0XWB5lhfe5ZWeBdG6KHmde7LPFcEi_jnkasQO5L921CB8pi-Ay3_KALQvT2b5OoYNw0H3ynq30jEBXkcqgKBZQzEP2nwHMdgyQ_0LZCFTcdGSkxoYaGkkxrj3ApkBwDinoUgE8io4X450G6hhBB-1MlCtZtq0ZSz1ryCPIgBIs1OnH2uZH7C13VNHHGU2GsRjAdQkDfJwOk7rKNcN1UGL8NoZAebVsZzUekjuRcy_wpOsBSSlVJb3dEKSWFnGcSyqK2i5rZPA9mgkmmn9EUlyprko_hOBJ6i_87IQXXOSHuhxXYCPv_uK6BLPB5xVidfLZoNKcTyBk1ad5rnv1VeqIMJVf6gq4HoWfupyRg-s-BkIo70cZoLhbyeGOaohykztBM-vqMm7XFeP0GAFtaWurPhOD3afBTGGdjPwNuZAueUux2eMm0HJhfvlkPSfjJGOg2mMk2sAymN_7wwgk6noB6Qn3H1210wND7qr2kW6Gz51gbaa7IMYoe78zUN9Q51S6gZmqUa_iOrMNUOeYhWaCTJ0lnyrbhKyeRaUES9Rift8ojV7fp4vFZ70B4_qfMG9Z2NIyh-SkDcjP5JDYXOfr2wP__Cge2Kssd1cORB9mZXS8AFf6x1C5RWWP_dTnJkMl3AJKbn-RZZ1t1wZHvm3GFuU7y_bevWpAsN7Iiv5-0eq5cUTuuopuDdA&anvtrid=w5741a7fe6d13ebfe4ccf074445cf529&anvauth=tb=0~te=1628118124~sgn=f3083fe583be330de793bec3ce4699d0b4eb4f1ff6ce53f0e8b569f5d6497063&t=1628118034&_vpng=0

**Comment by Sphinxroot** [comment]
all https://dcs-live.apis.anvato.net/  have token and change daily   the  only way  , is to find another source or re-stream for those

**Comment by jkemp814** [comment]
oh, okay. The New York channel seems to play, but not sure if it's a program or not.
