### ISSUE TITLE
Fix: sum links in ir.m3u

### ISSUE THREAD

**Issue by MH140000** [iptv-org/iptv#3918]
Hi.
The https://www.telewebion.com website stream, contained in the ir.m3u file, does not play properly with all players. I think there is a need for an invitation tag at the top of the channel link.
source link:
https://www.telewebion.com/channels
I will include some sample links in ir.m3u below, please check:
#EXTINF:-1 tvg-id="IRIBTV1.ir" tvg-name="IRIB TV1" tvg-country="IR" tvg-language="Persian" tvg-logo="" group-title="",IRIB TV1 (720p)
https://sdm.telewebion.com/live/tv1/playlist.m3u8
#EXTINF:-1 tvg-id="IRIBTV2.ir" tvg-name="IRIB TV2" tvg-country="IR" tvg-language="Persian" tvg-logo="" group-title="",IRIB TV2 (576p)
https://sdm.telewebion.com/live/tv2/playlist.m3u8
#EXTINF:-1 tvg-id="IRIBTV3.ir" tvg-name="IRIB TV3" tvg-country="IR" tvg-language="Persian" tvg-logo="" group-title="",IRIB TV3 (480p)
https://sdw.telewebion.com/live/tv3/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
I also add that those channels are from the official sources. (if you look at the official IRIB website for TV1, the Telewebion link is the one being used)

**Comment by MH140000** [comment]
Does anyone have a way to solve the problem?
Is there no other source for irib streams?

**Comment by Dum4G** [comment]
Are you sure you're not using any VPN or proxy? telewebion is geo-blocked

**Comment by MH140000** [comment]
yes. i test with vpn and without it.

**Comment by LaneSh4d0w** [comment]
Telewebion links works for me, however they don't seem to be stable.

The official government-controlled links however, even if their quality is bad, works perfectly.
