### ISSUE TITLE
Australian channels not working

### ISSUE THREAD

**Issue by teejayen** [iptv-org/iptv#392]
The following channels are no longer working, and give an *Access Denied* response:

https://austchannel-live.akamaized.net/hls/live/2002729/austchannel-news/master1280x720.m3u8
https://austchannel-live.akamaized.net/hls/live/2002736/austchannel-sport/master1280x720.m3u8

**Comment by boomski** [comment]
Just tested them with VLC Player and the streams are working.

**Comment by teejayen** [comment]
Hmm.. wonder if it is due to geoblocking. Closing out regardless, thanks for testing.
