### ISSUE TITLE
WLS-TV

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#3921]
**Channel Name:** WLS-TV News
**Country:** USA
**Language:** English
**Website:** https://abc7chicago.com/watch/live/
**Stream URL (optional):** xxx
**Notes (optional):** Links Will Become Live News When They Airs Local News

(Sample m3u8 link)
https://content-ause2.uplynk.com/channel/d32affbc0d4f48ae8d3cdc4f4deab326/g.m3u8?rays=ihgfedc&tc=1&exp=1628156204352&rn=-869628384&ct=c&oid=aac37e2c66614e699fb189ab391084ff&eid=WLSwatch&ad.flex=0&ad.kv=station%2Cwls&platform=web&ad.tag=&ad.vast3=1&ad.v=2&ad.tfcd=0&ad.is_lat=0&ad.npa=0&ad.correlator=18888&ad=wls_live&ad.adUnit=/wls/abc7chicago.com/web/live-broadcast-news&ad.pp=otv-web-desktop&ad.description_url=https%3A//abc7chicago.com/watch/&ad.sz=640x480&ad.ppid=BC8700825B654F0FCF62465904E07177&ad.cust_params=accesslevel%3D0%26beacTyp%3Dssai%26isAuth%3D0%26aff%3Dwls%26lang%3Den%26ait%3Dssai%26chan%3Dmisc%26objid%3D%26isAutoplay%3D1%26isDnt%3D0%26isMute%3D0%26pgtyp%3Dwatch%26vdm%3Dlive%26plt%3Ddesktop%26stp%3Dvdms%26swid%3DBC8700825B654F0FCF62465904E07177%26dtci_yxbk%3D%26var%3D16x9%26vps%3D640x360%26noad%3D0%26refDomain%3Dhttps%253A//abc7chicago.com/watch/%26unid%3D&sig=10c62ae6bf2a1a9dba84425ad3a55dbdf0cec64890bb733884ecdb4ca5443ccb&pbs=bfb1f4e1988a42378b4aa1ce7b50d2b1

**Comment by Sphinxroot** [comment]
the problem with photocall  its act as a re-streaming  and url  change daily   ->  v9rw <- this part will  change everyday

**Comment by jkemp814** [comment]
They are live now, but it has to be played in the browser from that web site.

https://content-ausc2.uplynk.com/channel/d32affbc0d4f48ae8d3cdc4f4deab326/g.m3u8

**Comment by freearhey** [comment]
Closed in favor #3145
