### ISSUE TITLE
Some Anime Channel Always Broken after 1 Minute

### ISSUE THREAD

**Issue by lixorhaxz** [iptv-org/iptv#3929]
**_Channel Name:_** Animax Indonesia, Aniplus Malaysia
**_Broken Link (from playlist):_** from index.m3u
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** The channel Play correctly but after 1-2 mins it always disconnected/broken. 
On kodi it kick me from animax/Aniplus. if i want to reconnect again, it said "Playback Failed, One or more items failed to play, check the log for more information", if on my phone it said Disturbance playing channel. Please fix this, it really annoying
**_Device/OS:_** LibreELEC/Kodi and My Phone Redmi note 4x with IPTV App

**Comment by lixorhaxz** [comment]
Nickelodeon Pluto (720p) just work correctly, kodi not kicked me out

**Comment by Dum4G** [comment]
Can't confirm that behavior on Aniplus Malaysia, tested with VLC and it's not even buffering for me. The first link for Animax Indonesia is literally dead now and that's something I will fix

**Comment by lixorhaxz** [comment]
Hey @Dum4G 
Animax (Indonesia subs) still error after 1 minute
![Screenshot_2021-08-07-13-14-29-748_ru iptvremote android iptv](https://user-images.githubusercontent.com/47329758/128588969-899ff4a5-0a48-427b-9fd3-55a20348e463.png)
![Screenshot_2021-08-07-13-13-51-432_ru iptvremote android iptv](https://user-images.githubusercontent.com/47329758/128588970-379e426e-2b21-4cb1-9134-dc2e9de92e9d.png)

![Screenshot_2021-08-07-13-14-34-734_ru iptvremote android iptv](https://user-images.githubusercontent.com/47329758/128588967-c63cfa2c-c7eb-4f8d-9954-b36e505ac913.png)
