### ISSUE TITLE
Broken : Roku Version of Weathernation

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#3933]
**_Channel Name:_** Weathernation(Roku)
**_Broken Link (from playlist):_** https://weathernationtv.roku.wurl.com/manifest/playlist.m3u8
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** Not Working in GSE Smart Player

**Comment by MapGuy11** [comment]
![image](https://user-images.githubusercontent.com/43685307/128514120-0c1752b2-6344-479d-bfc5-3088b2a319d1.png)

**Comment by MapGuy11** [comment]
Did you fix it? Or is it still a problem

**Comment by Central302** [comment]
Fixed and It Looks Like Become Geoblocked to USA
