### ISSUE TITLE
Neither of the "The Weather Channel" are working.

### ISSUE THREAD

**Issue by msnoitall** [iptv-org/iptv#3935]
**The Weather Channel** xxx
***https://iptv-org.github.io/iptv/index.m3u** xxx
**_Possible Replacement (optional):_** xxx
**_Notes (optional): I hope that's the correct info. I'm sorry if it's not and I wasted your time. I really don't understand more of this than copy and paste and instant tv. Anyway, the weather channel # 8 and # 9 under category Weather stopped working a few weeks ago. It's my only source of tracking hurricanes at this point. I'd appreciate it if someone could look at it. And thank you (all) for making this entire project happen. Im fixed/ low income.** xxx

**Comment by MapGuy11** [comment]
It has been a running discussion here #3868

**Comment by MapGuy11** [comment]
@msnoitall DM me ,and I maybe be able to help you.

**Comment by MapGuy11** [comment]
@msnoitall Do you have a way I can contact you I maybe able to help you out. :D

**Comment by Dum4G** [comment]
Duplicate of https://github.com/iptv-org/iptv/issues/3843

**Comment by MapGuy11** [comment]
The other one I am closing

**Comment by msnoitall** [comment]
Yes, thank you, mapguy11. Same as my forum name followed by @aol.com . I just don't want a bot picking it up. :)
