### ISSUE TITLE
Balastan

### ISSUE THREAD

**Issue by 129612231-scripts** [iptv-org/iptv#3943]
**Channel Name:** Balastan (Баластан)
**Country:** Kyrgyzstan
**Language:** Kyrgyz
**Website:** http://www.ktrk.kg/balastan
**Stream URL (optional):**
**Notes (optional):**

**Comment by 129612231-scripts** [comment]
oh actually realised it records stuff illegally from sts kids. close this if you want

**Comment by LaneSh4d0w** [comment]
Their stream does not seem to be online too : http://onlinetv.ktrk.kg:1935/live/myStream6/playlist.m3u8

**Comment by 129612231-scripts** [comment]
i've tried using a kyrgyzstan vpn but all to no avail.

**Comment by boomski** [comment]
http://onlinetv.ktrk.kg:1935/live/myStream6/playlist.m3u8 > stream is back online (but not sure it's 24/7 online)
