### ISSUE TITLE
Channel Request: LocalNow Weather, Traffic, and News - Philadelphia, PA

### ISSUE THREAD

**Issue by FpFan65** [iptv-org/iptv#3945]
**Channel Name:** LocalNow Weather, Traffic, and News - Philadelphia, PA
**Country:** US
**Language:** English
**Website:** www.localnow.com
**Stream URL (optional):** https://prod.localnowapi.com/vod/api/v2/LiveStream/Playback/paPhiladelphia/index.m3u8
**Notes (optional):** xxx

**Comment by jkemp814** [comment]
How were you able to get the live stream address, if I can ask?

**Comment by FpFan65** [comment]
posted on another GitHub directory, Free2ViewTV.  Checked one out.  The one
difference in each is State and City.

**Comment by jkemp814** [comment]
I tried to guess that using Saint Louis, but it didn't work. When I saw the city and state in the address URL.

**Comment by FpFan65** [comment]
Spelling is case sensitive

https://prod.localnowapi.com/vod/api/v2/LiveStream/Playback/moStLouis/index.m3u8

**Comment by jkemp814** [comment]
Thanks, I see where I went wrong, I put the city first. Appreciate it.
