### ISSUE TITLE
Channel Request: LocalNow Weather, Traffic and News - Harrisburg, PA

### ISSUE THREAD

**Issue by FpFan65** [iptv-org/iptv#3946]
**Channel Name:** LocalNow Weather, Traffic and News - Harrisburg, PA
**Country:** US
**Language:** English
**Website:** www.localnow.com
**Stream URL (optional):** https://prod.localnowapi.com/vod/api/v2/LiveStream/Playback/paHarrisburg/index.m3u8
**Notes (optional):** xxx

**Comment by MapGuy11** [comment]
Will work on these thxs.

**Comment by Dum4G** [comment]
Geo-blocked and isn't playing in vlc, perhaps http-refferrer is needed

**Comment by MapGuy11** [comment]
Works on web browser and TiviMate 
![image](https://user-images.githubusercontent.com/43685307/128571989-7c9270d5-9f2e-4866-90c6-7e0da11ad008.png)

**Comment by jkemp814** [comment]
Works in Firefox extension
