### ISSUE TITLE
Fix: Rouge TV : incorrect classification

### ISSUE THREAD

**Issue by adeit** [iptv-org/iptv#3947]
Rouge TV is currently classified as XXX channel, but Rouge TV is a generalist channel

Current entry :
#EXTINF:-1 tvg-id="RougeTV.ch" tvg-name="Rouge TV" tvg-country="CH" tvg-language="French" tvg-logo="https://od.lk/s/MF8yMjYwNDgzMzhf/RougeTV_225x225.png" group-title="XXX",Rouge TV (720p)
http://event.vedge.infomaniak.com/livecast/event.stream/playlist.m3u8

Proposed entry :
#EXTINF:-1 tvg-id="RougeTV.ch" tvg-name="Rouge TV" tvg-country="CH" tvg-language="French" tvg-logo="https://od.lk/s/MF8yMjYwNDgzMzhf/RougeTV_225x225.png" group-title="",Rouge TV (720p)
http://event.vedge.infomaniak.com/livecast/event.stream/playlist.m3u8

**Comment by jkemp814** [comment]
I remember asking about this. I seen they were playing Red Bull TV at one point. But then.... They play porn after hours.

**Comment by Dum4G** [comment]
See https://github.com/iptv-org/iptv/discussions/3228
