### ISSUE TITLE
Add TMC

### ISSUE THREAD

**Issue by adeit** [iptv-org/iptv#3952]
**Channel Name:** TMC
**Country:** FR
**Language:** French
**Website:** xxx
**Stream URL (optional):** https://s6.tntendirect.com/tmc/live/playlist.m3u8
**Notes (optional):**
#EXTINF:-1 tvg-id="TMC.fr" tvg-name="TMC" tvg-country="FR" tvg-language="French" tvg-logo="" group-title="",TMC (720p)
https://s6.tntendirect.com/tmc/live/playlist.m3u8

**Comment by jkemp814** [comment]
Works from U.S.
