### ISSUE TITLE
Add TFX

### ISSUE THREAD

**Issue by adeit** [iptv-org/iptv#3953]
**Channel Name:** TFX
**Country:** FR
**Language:** French
**Website:** xxx
**Stream URL (optional):** https://s6.tntendirect.com/nt1/live/playlist.m3u8
**Notes (optional):**
#EXTINF:-1 tvg-id="TFX.fr" tvg-name="TFX" tvg-country="FR" tvg-language="French" tvg-logo="" group-title="",TFX (720p)
https://s6.tntendirect.com/nt1/live/playlist.m3u8

**Comment by jkemp814** [comment]
Works from U.S.
