### ISSUE TITLE
Add CSTAR

### ISSUE THREAD

**Issue by adeit** [iptv-org/iptv#3955]
**Channel Name:** CSTAR
**Country:** FR
**Language:** French
**Website:** xxx
**Stream URL (optional):** https://s6.tntendirect.com/d17/live/playlist.m3u8
**Notes (optional):**
#EXTINF:-1 tvg-id="CSTAR.fr" tvg-name="CSTAR" tvg-country="FR" tvg-language="French" tvg-logo="" group-title="",CSTAR (360p)
https://s6.tntendirect.com/d17/live/playlist.m3u8

**Comment by jkemp814** [comment]
Works from U.S.
