### ISSUE TITLE
Add TF1 Séries Films

### ISSUE THREAD

**Issue by adeit** [iptv-org/iptv#3956]
**Channel Name:** TF1 Séries Films
**Country:** FR
**Language:** French
**Website:** xxx
**Stream URL (optional):** https://s6.tntendirect.com/hd1/live/playlist.m3u8
**Notes (optional):**
#EXTINF:-1 tvg-id="TF1SeriesFilms.fr" tvg-name="TF1 Series Films" tvg-country="FR" tvg-language="French" tvg-logo="" group-title="",TF1 Series Films (360p)
https://s6.tntendirect.com/hd1/live/playlist.m3u8

**Comment by jkemp814** [comment]
Works from U.S.
