### ISSUE TITLE
Add L'EQUIPE

### ISSUE THREAD

**Issue by adeit** [iptv-org/iptv#3957]
**Channel Name:** L'EQUIPE
**Country:** FR
**Language:** French
**Website:** xxx
**Stream URL (optional):** https://s6.tntendirect.com/lequipe21/live/playlist.m3u8
**Notes (optional):**
#EXTINF:-1 tvg-id="LEQUIPE.fr" tvg-name="L EQUIPE" tvg-country="FR" tvg-language="French" tvg-logo="" group-title="",L EQUIPE (360p)
https://s6.tntendirect.com/lequipe21/live/playlist.m3u8

**Comment by jkemp814** [comment]
Works from U.S.
