### ISSUE TITLE
Add RMC Découverte

### ISSUE THREAD

**Issue by adeit** [iptv-org/iptv#3958]
**Channel Name:** RMC Découverte
**Country:** FR
**Language:** French
**Website:** xxx
**Stream URL (optional):** https://s6.tntendirect.com/rmcdecouverte/live/playlist.m3u8
**Notes (optional):**
#EXTINF:-1 tvg-id="RMCDecouverte.fr" tvg-name="RMC Decouverte" tvg-country="FR" tvg-language="French" tvg-logo="" group-title="",RMC Decouverte (720p)
https://s6.tntendirect.com/rmcdecouverte/live/playlist.m3u8

**Comment by jkemp814** [comment]
Works from U.S.
