### ISSUE TITLE
Add Chérie 25

### ISSUE THREAD

**Issue by adeit** [iptv-org/iptv#3959]
**Channel Name:** Chérie 25
**Country:** FR
**Language:** French
**Website:** xxx
**Stream URL (optional):** https://s6.tntendirect.com/cherie25/live/playlist.m3u8
**Notes (optional):**
#EXTINF:-1 tvg-id="Cherie25.fr" tvg-name="Cherie 25" tvg-country="FR" tvg-language="French" tvg-logo="" group-title="",Cherie 25 (360p)
https://s6.tntendirect.com/cherie25/live/playlist.m3u8

**Comment by jkemp814** [comment]
Works from U.S.
