### ISSUE TITLE
Add Arte

### ISSUE THREAD

**Issue by adeit** [iptv-org/iptv#3960]
**Channel Name:** Arte
**Country:** FR
**Language:** French
**Website:** xxx
**Stream URL (optional):** https://s6.tntendirect.com/arte/live/playlist.m3u8
**Notes (optional):**
#EXTINF:-1 tvg-id="Arte.fr" tvg-name="Arte" tvg-country="FR" tvg-language="French" tvg-logo="" group-title="",Arte (360p)
https://s6.tntendirect.com/arte/live/playlist.m3u8

**Comment by jkemp814** [comment]
Works from U.S.
