### ISSUE TITLE
Add BFMTV

### ISSUE THREAD

**Issue by adeit** [iptv-org/iptv#3961]
**Channel Name:** BFMTV
**Country:** FR
**Language:** French
**Website:** xxx
**Stream URL (optional):** https://s6.tntendirect.com/bmftv/live/playlist.m3u8
**Notes (optional):**
#EXTINF:-1 tvg-id="BFMTV.fr" tvg-name="BFMTV" tvg-country="FR" tvg-language="French" tvg-logo="" group-title="",BFMTV (360p)
https://s6.tntendirect.com/bmftv/live/playlist.m3u8

**Comment by jkemp814** [comment]
Works from U.S.
