### ISSUE TITLE
Remove: xxx

### ISSUE THREAD

**Issue by youhun00** [iptv-org/iptv#3968]
**_Channel Name:_** /channels/cn.m3u
**_DMCA Notice (link):_** https://156zy.suyunbo.tv/***/playlist.m3u8

The videos under these domains are some adult videos, please delete these porn video links, thank you.

I have previously submitted a deletion application and deleted related [links](https://github.com/iptv-org/iptv/issues/2234). But I don’t know when it will be updated again. Please manage to check whether the following local warehouses have not been deleted, so as not to reappear in the next update. Thank you.

**Comment by freearhey** [comment]
Thanks for the report! These links will be removed soon.
