### ISSUE TITLE
Wsbtv

### ISSUE THREAD

**Issue by OutApexed** [iptv-org/iptv#3971]
**Channel Name:** ABC Atlanta (WSB-TV)
**Country:** USA
**Language:** English
**Website:** xxx
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
https://d2rwx6gwduugne.cloudfront.net/v1/master/77872db67918a151b697b5fbc23151e5765767dc/cmg_PROD_cmg-tv-10010_183ec1c7-4183-4661-803b-3ed282ffb625_LE/in/cmg-wsbtvnow-hls-v3/live.m3u8

**Comment by jkemp814** [comment]
Works on my end.
