### ISSUE TITLE
Stöð 2

### ISSUE THREAD

**Issue by zupersponge** [iptv-org/iptv#3978]
**Channel Name:** Stöð 2
**Channel ID:** Stod2.is
**Country:** Iceland
**Language:** Icelandic
**Website:** stod2.is
**Stream URL (optional):**
**Notes (optional):**

**Comment by LaneSh4d0w** [comment]
DRM protected streams.

**Comment by 129612231-scripts** [comment]
Ah, right

**Comment by freearhey** [comment]
Closed in favor of #12284
