### ISSUE TITLE
NickToons Africa

### ISSUE THREAD

**Issue by nickjrukfan** [iptv-org/iptv#3980]
**Channel Name:** Nicktoons
**Channel ID:** NicktoonsAfrica.za
**Country:** Africa 
**Language:** English
**Website:** www.NickelodeonAfrica.com

**Comment by MapGuy11** [comment]
I don't know if this is Nick Africa
http://51.210.1.13:18000/nickelodeon/hls/playlist.m3u8

**Comment by Dum4G** [comment]
Closed in favor of #3145

**Comment by freearhey** [comment]
Closed in favor of #12283
