### ISSUE TITLE
Costa Rican Channel Requests

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#3990]
- [ ] Teletica Canal 7 (#3732)
- [x] Canal 2 (#3731)
- [x] Canal 4 (#3730)
- [x] Canal 11 (#3729)
- [x] Canal 6 (#3728)

If you find a working link to a channel from the list you can add it directly to the playlist by making a pull request, just read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#add-or-replace-a-stream) before you do it.

**Comment by freearhey** [comment]
Closed in favor #3732
