### ISSUE TITLE
ESPN (360p)

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#4001]
**_Channel Name:_** ESPN (360p)
**_Broken Link (from playlist):_ http://stream.tvtap.live:8081/live/espnusahd.stream/playlist.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** When the channel finally loads, it is playing the Sci-Fi channel with Spanish audio.

Line: 1281

**Comment by jkemp814** [comment]
Okay, an update. While letting the stream play, it suddenly pauses then start again with ESPN playing. It's very choppy thou.

**Comment by MapGuy11** [comment]
@jkemp814 Not trying to be rude but this is a FREE list. ESPN is one of the channels that cost most on a cable plan that we have this channel is amazing. We CANNOT control the providers that we find. Please use the uplynk url from ESPN thanks. These channels will be removed.

**Comment by jkemp814** [comment]
Okay, I understand.  Was pointing out the issue of when the tags are in sync, the falling channel may be the one showing. The end user will not know about the other one that is working.

**Comment by MapGuy11** [comment]
@jkemp814 Ok, I understand this pull fixes it #4003 let me know of anything wrong. Thanks Again :D

**Comment by jkemp814** [comment]
Man, I can agree. It's hard work, too. I try my best to contribute best I can, instead of just complaining while using a free list. For the last two months, I have been putting in work to help make the list look as professional as we can.

**Comment by MapGuy11** [comment]
@jkemp814 Awesome!
