### ISSUE TITLE
FXX

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#4013]
**Channel Name:** FXX
**Country:** USA
**Language:** English
**Website:** https://fxnow.fxnetworks.com/watch-live/fxx-east
**Stream URL (optional):** http://51.79.82.231:8080/US_FXX_EAST_USA/video.m3u8
**Notes (optional):** Working in Potplayer

**Comment by heroku-miraheze** [comment]
Paid channels are not allowed.

**Comment by Armond452Alt** [comment]
Add:label:rejected:broken_link
