### ISSUE TITLE
HBO(USA)

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#4014]
**Channel Name:** HBO East
**Country:** USA
**Language:** English
**Website:** http://51.79.82.231:8080/US_HBO_EAST/video.m3u8
**Stream URL (optional):** Working in PotPlayer
**Notes (optional):** xxx

**Comment by heroku-miraheze** [comment]
Paid channels are not allowed.

**Comment by spotanjo3** [comment]
HBO EAST Please ?
