### ISSUE TITLE
(Need A Test)WGHP-TV

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#4015]
**Channel Name:** WGHP-TV(FOX Network)
**Country:** USA
**Language:** English
**Website:** http://51.79.82.231:8080/US_DISNEY_XD_EAST_USA/video.m3u8
**Stream URL (optional):**
**Notes (optional):** Currently Unstable

**Comment by heroku-miraheze** [comment]
Paid channels are not allowed.
