### ISSUE TITLE
Animax Japan

### ISSUE THREAD

**Issue by mokonamodoki069** [iptv-org/iptv#4020]
**Channel Name:** xxx
**Country:** xxx
**Language:** xxx
**Website:** xxx
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by vbHeiko** [comment]
https://livecdn.fptplay.net/hda3/animaxport_2000.stream/playlist.m3u8
https://livecdn.fptplay.net/hda3/animaxport_hls.smil/playlist.m3u8

**Comment by jkemp814** [comment]
Can confirm both links play. Seems to be the same content. Alternate source is always good.

**Comment by jkemp814** [comment]
Both of these are already in the jp.m3u playlist. There are a total of 30 of them across multiple files.

> https://livecdn.fptplay.net/hda3/animaxport_2000.stream/playlist.m3u8 - Line 13
> https://livecdn.fptplay.net/hda3/animaxport_hls.smil/playlist.m3u8 - Line: 16
