### ISSUE TITLE
Aniplus Broken

### ISSUE THREAD

**Issue by Kaizaru** [iptv-org/iptv#4029]
**_Channel Name:_** Aniplus Malay Sub
**_Broken Link (from playlist):_** http://210.210.155.35/dr9445/h/h02/01.m3u8, http://210.210.155.35/dr9445/h/h02/01.m3u8, http://210.210.155.35/session/83bc2526-da69-11e8-881b-c81f66f89318/dr9445/h/h144/01.m3u 
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** Please fix 🙏 
![image](https://user-images.githubusercontent.com/87840041/128810983-6d3f18a4-d961-4bad-99b8-2bbe06a0f4fc.png)

**Comment by fotvnetwork** [comment]
http://playlist.urfan.web.id/dr9445/h/h02/01.m3u8

**Comment by Dum4G** [comment]
Where are you from? Works from OG link
![Screenshot_20210810-150603](https://user-images.githubusercontent.com/5430116/128864088-793babad-e7b8-422e-89bc-df667419a006.jpg)

**Comment by LaneSh4d0w** [comment]
This stream is geolocked to the Asian continent almost. I, with a French IP can't see it, so either OP is from Europe or the Americas, either there's a strict view on which country's allowed to access content.

**Comment by lixorhaxz** [comment]
> Where are you from @Kaizaru @lixorhaxz @joseph23pronton? Works from OG link for me. Please check the link from fotvnetwork
> ![Screenshot_20210810-150603](https://user-images.githubusercontent.com/5430116/128864088-793babad-e7b8-422e-89bc-df667419a006.jpg)
I from Indonesia

**Comment by Kaizaru** [comment]
> http://playlist.urfan.web.id/dr9445/h/h02/01.m3u8

![image](https://user-images.githubusercontent.com/87840041/129143042-c9b56a3f-11c1-4739-af88-44e532240643.png)
im from indonesia

**Comment by Kaizaru** [comment]
> http://playlist.urfan.web.id/dr9445/h/h02/01.m3u8

![image](https://user-images.githubusercontent.com/87840041/129143100-340928cd-02e0-4335-85d7-a0007cd9bcda.png)
im from indonesia

**Comment by MinePlayersPE** [comment]
Seemingly doesn't work with Indonesian IP, I can access it when using Cloudflare WARP to Singapore 🥴

**Comment by Dum4G** [comment]
>  Not sure why it doesn't work on my IP

What if you simply use Cloudflare DNS on your system?

**Comment by MinePlayersPE** [comment]
>What if you simply use Cloudflare DNS

Doesn't work, I specifically had to enable WARP/Cloudflare's VPN
