### ISSUE TITLE
SAB TV

### ISSUE THREAD

**Issue by sem2322** [iptv-org/iptv#4030]
**Channel Name:** SAB TV
**Country:** INDIA
**Language:** HINDI
**Website:** www.sonyliv.com
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by freearhey** [comment]
Already on the playlist:
https://github.com/iptv-org/iptv/blob/08ed6458a64757ffe24ad3047a878121ab8f93da/channels/in.m3u#L415-L416
