### ISSUE TITLE
Sportal.bg

### ISSUE THREAD

**Issue by boomski** [iptv-org/iptv#4031]
**Channel Name:** Sportal.bg
**Country:** Bulgaria
**Language:** Bulgarian
**Website:** https://sportal.bg/video-2021031416243499998
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
Have you ever seen the link move over time ?

I see there's a sort of ID linked to the video. I can manage to get the link I suppose, but if this link is made to change, i'll add a extra step to ensure that the link is always fresh and can be used.

**Comment by LaneSh4d0w** [comment]
I think the "at" token changes over time, hence the fact I wanted to know.

**Comment by LaneSh4d0w** [comment]
https://iptv-all.lanesh4d0w.codes/bulgaria/sportal-tv

Made sure the link was fresh all the time.

**Comment by LaneSh4d0w** [comment]
thing is... it's geo-locked from where the server's located.

**Comment by Dum4G** [comment]
Looks like I'm lucky to see so many things just fine. Link hasn't changed yet but I can't open yours

**Comment by LaneSh4d0w** [comment]
Yeah, seems that the server from where my app's being runned is blocked by Sportal.

**Comment by LaneSh4d0w** [comment]
Well, here's the code, for any person that can host it on a server. 

```
app.get("/bulgaria/sportal-tv", function(req,res) {
    fetch("https://sportal.bg/live")
        .then(response => response.text())
        .then(text => {
            var regex = new RegExp(/href="(.+?)" class="post__item"/)
            var results = regex.exec(text);
            fetch("https://sportal.bg" + results[1])
                .then(response => response.text())
                .then(result_text => {
                    res.setHeader('Content-Type', 'application/vnd.apple.mpegurl');
                    var regex2 = new RegExp(/file: '(.+?)'/)
                    var res2 = regex2.exec(result_text);
                    res.redirect(res2[1])
                })
        })
});

**Comment by Dum4G** [comment]
Link hasn't changed in 24h

**Comment by LaneSh4d0w** [comment]
Well then, it's good to push the link "as-is" and see how long i'll last.
