### ISSUE TITLE
sky sport

### ISSUE THREAD

**Issue by the-poor-gamer-124** [iptv-org/iptv#4037]
**Channel Name:** sky sport
**Country:** uk
**Language:** english
**Website:** https://www.skysports.com/
**Stream URL (optional):** dont have
**Notes (optional):** xxx

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/1943

**Comment by xenonianick** [comment]
Can i get the the repository for sky sports uk/premier league please?
