### ISSUE TITLE
Mazhavil Manorama HD

### ISSUE THREAD

**Issue by thepinkmanist** [iptv-org/iptv#4041]
**_Channel Name:_** Mazhavil Manorama HD
**_Broken Link (from playlist):_** xxx
**_Possible Replacement (optional):_** 
**_Notes (optional):_** It's available for free (Free To Air basis) Language: Malayalam

**Comment by MapGuy11** [comment]
Where is the broken Link from the Playlist? If this is a Channel Request Please Close and Open a Channel Request. 

THANKS!

**Comment by LaneSh4d0w** [comment]
This ? https://d3t34m8y8rh0vb.cloudfront.net/preview/mazhavilmanhd/2500.m3u8

**Comment by thepinkmanist** [comment]
> This ? https://d3t34m8y8rh0vb.cloudfront.net/preview/mazhavilmanhd/2500.m3u8 (that's a preview from YuppTV, only one looped video).

Yes this is it
