### ISSUE TITLE
Bangladeshi, Pakistani and Islamic relegious New Channel Request 

### ISSUE THREAD

**Issue by AhasanSheikhBangladeshi** [iptv-org/iptv#4042]
**Channel Name:** BTV(Bangladesh) 
Btv World (Bangladesh) Atn Bangla(Bangladesh), NTV(Bangladesh) RTV(Bangladesh) Banglavision(Bangladesh)  MY TV(Bangladesh) ATN News (Bangladesh) Channel i Europe (UK based Bangladeshi)  Somoy TV(Bangladesh)  Jamuna TV (bangladesh) NTV UK(UK based Bangladeshi) Madani Channel Bangla(Bangladesh) Iqra Bangla(Uk based Bangladeshi)  PTV Home(Pakistan)  PTV World(Pakistan)  PTV News(Pakistan)  ARY Qtv(Pakistan)  Hadi Tv 1(Pakistan/Iran) Hadi TV 2 (iraq/Malaysia/Pakistan)  Hadi tv 3(Iran) Hadi TV 4(Pakistan/Iran/Iraq) Hadi tv 5 (Iran/Africa) Paigaham TV(Pakistan) Madani Channel Urdu(Pakistan) Huda Tv(Saudi Arabia) 
**Country:**  Bangladesh,Pakistan,Iran,Saudi Arabia
**Language:** Bangla, English,Urdu,Farsi,Arabic,Indonesian,Malay,Pashto 
**Website:** xxx
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by freearhey** [comment]
Please read the [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel) before posting your next request.
