### ISSUE TITLE
HGTV, Discovery, Food Network

### ISSUE THREAD

**Issue by OutApexed** [iptv-org/iptv#4058]
**Channel Name:** HGTV, Discovery, Food Network
**Country:** USA
**Language:** English
**Website:** xxx
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by freearhey** [comment]
Unfortunately, we cannot add these channels to the playlist due to claims of copyright holders: #1831

And please read the [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel) before posting your request next time.
