### ISSUE TITLE
Sky Bundesliga

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#4065]
**Channel Name:** Sky Bundesliga 1
**Country:** UK, DE
**Language:** German
**Website:** xxx
**Stream URL (optional):** http://31.220.41.88:8081/live/de-skybundes1.stream/playlist.m3u8
http://185.97.150.19:8082/382
http://185.97.150.19:8082/2195
**Notes (optional):** AFK

**Comment by LaneSh4d0w** [comment]
1st one works but clunky stream. Seems unstable at first glance. 31.220.41.88 = stream.tvtap.live

2nd link works perfectly.
3rd link works perfectly too.

**Comment by LaneSh4d0w** [comment]
By digging a bit. 380 is Sky Sport 1, 381 is Sky Sport 2, 383 is Das Erste Deutschland
