### ISSUE TITLE
UBL HD

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4071]
**Channel Name:** **UBL HD**
**Country:** **India**
**Language:** **Malayalam**
**Website:** http://www.ubltv.com
**Stream URL (optional):** http://www.ubltv.com/d63d760d-09e4-4e15-b197-8fcff3bc1667
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | http://cloud.logicwebs.in:1935/ubl/ublchannel/playlist.m3u8
-- | --
mediaManifest | http://cloud.logicwebs.in:1935/ubl/ublchannel/chunklist_w377962218.m3u8

https://i.imgur.com/Je1JZlr.png

</body>
</html>

**Comment by Dum4G** [comment]
404

**Comment by Sphinxroot** [comment]
https://cdn.logicwebs.in/hls/ublhdkey.m3u8

**Comment by Sphinxroot** [comment]
toon of channel to pull out from here https://mhdtvworld.xyz/

**Comment by Niyasmkkv** [comment]
> toon of channel to pull out from here https://mhdtvworld.xyz/

That site is not working for me.

**Comment by Niyasmkkv** [comment]
> https://cdn.logicwebs.in/hls/ublhdkey.m3u8

Is this woking?

**Comment by Dum4G** [comment]
> Is this woking?

Quite well
![image](https://user-images.githubusercontent.com/5430116/129620452-0cd2ac6a-51e3-47e6-b73d-905660612bed.png)

**Comment by Niyasmkkv** [comment]
Not working for me on Kodi. Any idea why?

**Comment by Niyasmkkv** [comment]
> > Is this woking?
> 
> Quite well
> ![image](https://user-images.githubusercontent.com/5430116/129620452-0cd2ac6a-51e3-47e6-b73d-905660612bed.png)
> 
> 
> 
Which player is this? And how to make it work on kodi?

**Comment by Dum4G** [comment]
This is VLC, maybe Kodi needs some additional referrer, idk

**Comment by Niyasmkkv** [comment]
Is there anyway to get an kodi supported stream link

> This is VLC, maybe Kodi needs some additional referrer, idk

Is there anyway to get an kodi supported stream link?

**Comment by Niyasmkkv** [comment]
@Sphinxroot  can you add this channel to the list? It seems working.

**Comment by Sphinxroot** [comment]
for kodi use playlistloader  addons both version are available for 18.9 or matrix 19+

**Comment by Niyasmkkv** [comment]
can we update the channel and close this issue?

**Comment by Sphinxroot** [comment]
soon we will make a one piece PR for india and all request will be close at the same time ;-)

**Comment by Niyasmkkv** [comment]
> soon we will make a one piece PR for india and all request will be close at the same time ;

It will happen when?

**Comment by Niyasmkkv** [comment]
@LaneSh4d0w anything about this channel?
