### ISSUE TITLE
NTV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4072]
**Channel Name:** NTV UAE
**Channel ID:** NTV.ae
**Country:** UAE
**Language:** Malayalam
**Website:** http://www.ntvuae.tv/
**Stream URL (optional):** 
**Notes (optional):** xxx

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/4306

**Comment by freearhey** [comment]
Closed in favor of #12281
