### ISSUE TITLE
CBC Toronto

### ISSUE THREAD

**Issue by mememe0142** [iptv-org/iptv#4073]
**Channel Name:CBC Toronto
**Country:** Canada
**Language:English
**Website:** xxx
**Stream URL (optional):https://bozztv.com/teleyupp1/teleup-ydcl2V1MVC/playlist.m3u8
**Notes (optional):Stream is NOT working Please fix or Update. 

Thank You

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-logo="https://i.imgur.com/RulfaHI.png" group-title="News",CBC Toronto
https://cbclivedai1-i.akamaihd.net/hls/live/566940/event2/CBLT/master5.m3u8  but will be geo
