### ISSUE TITLE
Waar TV

### ISSUE THREAD

**Issue by TheRedEaglee** [iptv-org/iptv#4076]
**Channel Name:** Waar TV
**Country:** Iraq
**Language:** Kurdish
**Website:** https://waarmedia.com/
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
https://waarmedia.com/en/live/  Broadcast suspended

**Comment by LaneSh4d0w** [comment]
ok.ru link, seems to be "IP-generated" and therefore can't be used even on the services we got. Either you install streamlink manually on your PC and ask streamlink to get it from there, either you watch it directly from the same source.

**Comment by TheRedEaglee** [comment]
👍🏼
