### ISSUE TITLE
Med Muzîk TV

### ISSUE THREAD

**Issue by TheRedEaglee** [iptv-org/iptv#4077]
**Channel Name:** Med Muzîk TV
**Country:** Turkey
**Language:** Kurdish
**Website:** http://medmuzik.tv/
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | http://137.74.205.201/medmuzik/MedStream/playlist.m3u8
-- | --
mediaManifest | http://137.74.205.201/medmuzik/MedStream/chunklist_w2114709966.m3u8

http://medmuzik.tv/wp-content/uploads/2019/06/med_logo.png

</body>
</html>

**Comment by TheRedEaglee** [comment]
@freearhey I searched and I found that this channel it's already added but it seems bot not adding it to the Kurdish playlist.

**Comment by freearhey** [comment]
@TheRedEaglee To be included in the Kurdish playlist, the channel must have this language in the description.

**Comment by TheRedEaglee** [comment]
@freearhey As I know and as https://www.lyngsat.com/tvchannels/tr/Med-Muzik.html that this channel is Kurdish but located in Turkey, also I want to help in this project is there any discord server for this and if doesn't I suggest to open one so we can connect each other and have easier so slove issues.

**Comment by freearhey** [comment]
@TheRedEaglee I've already updated the channel description (https://github.com/iptv-org/iptv/pull/4087/files) and it should be on the Kurdish playlist by tomorrow.

And if you have any ideas or questions you can post them here: https://github.com/iptv-org/iptv/discussions

**Comment by TheRedEaglee** [comment]
@freearhey Thanks I will do.
