### ISSUE TITLE
Zagros TV

### ISSUE THREAD

**Issue by TheRedEaglee** [iptv-org/iptv#4078]
**Channel Name:** Zagros TV
**Country:** Iraq
**Language:** Kurdish, Arabic
**Website:** https://www.zagrosnews.net/
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | https://5a3ed7a72ed4b.streamlock.net/zagrostv/SMIL:myStream.smil/playlist.m3u8
-- | --
mediaManifest | https://5a3ed7a72ed4b.streamlock.net/zagrostv/SMIL:myStream.smil/chunklist_w431722005_b1700000_sleng_t64MTA4MHA=.m3u8

https://i.imgur.com/y9ua43j.png

</body>
</html>

**Comment by TheRedEaglee** [comment]
Already added and channel language it's only Arabic so not needed to add to Kurdish playlist.
