### ISSUE TITLE
TV Asahi

### ISSUE THREAD

**Issue by CorgiTech** [iptv-org/iptv#4079]
**Channel Name:** TV Asahi
**Country:** Japan
**Language:** Japanese
**Website:** https://www.tv-asahi.co.jp/
**Stream URL (optional):** xxx
**Notes (optional):** Nothing more than wishing you luck.

**Comment by LaneSh4d0w** [comment]
https://linkastream.co/headless?url=https://ok.ru/video/2473147047553

**Comment by CorgiTech** [comment]
> 
> 
> https://linkastream.co/headless?url=https://ok.ru/video/2473147047553

Service seems to be unavailable.

**Comment by LaneSh4d0w** [comment]
Yes, linkastream's offline for the time being, due to server issue.

**Comment by CorgiTech** [comment]
> 
> 
> Yes, linkastream's offline for the time being, due to server issue.
Seems like TV asahi is available there right? If so then I am at least glad to know whats currently happening with some channels.

**Comment by LaneSh4d0w** [comment]
https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://ok.ru/video/2473147047553

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/1938
