### ISSUE TITLE
Sky Sports News

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#4081]
**Channel Name:** Sky Sports News
**Country:** UK
**Language:** English
**Website:** https://www.skysports.com/watch/sky-sports-news
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-logo="http://static.epg.best/gb/SkySportsNews.uk.png" group-title="SPORTS",Sky Sports News
http://stream.tvtap.live:8081/live/skysportsnews.stream/playlist.m3u8

#EXTINF:-1 tvg-logo="https://static.epg.best/gb/SkySportsMainEvent.uk.png" group-title="SPORTS", Sky Sports MAIN EVENT
http://stream.tvtap.live:8081/live/skysports-maineventz.stream/playlist.m3u8

#EXTINF:-1 tvg-logo="https://static.epg.best/gb/SkySportsPremiereLeague.uk.png" group-title="SPORTS", Sky Sports Premier League
http://stream.tvtap.live:8081/live/skysports-premier-league.stream/playlist.m3u8

#EXTINF:-1 tvg-logo="https://i.imgur.com/dqUM1Kv.png" group-title="SPORTS", Sky Sports Football
http://stream.tvtap.live:8081/live/skysports-football.stream/playlist.m3u8

#EXTINF:-1 tvg-logo="https://static.epg.best/gb/SkySportsMix.uk.png" group-title="SPORTS",Sky Sports Mix
http://stream.tvtap.live:8081/live/skysportsmix.stream/playlist.m3u8

#EXTINF:-1 tvg-logo="http://195.154.221.171/picons/skysports4hduk.png" group-title="SPORTS", Sky Sports Golf
http://stream.tvtap.live:8081/live/skysports-the-open.stream/playlist.m3u8

#EXTINF:-1 tvg-logo="https://static.epg.best/gb/SkySportsF1.uk.png" group-title="SPORTS",Sky Sports F1
http://stream.tvtap.live:8081/live/skysportsf1.stream/playlist.m3u8

#EXTINF:-1 tvg-logo="https://i.imgur.com/FI6SzV9.png" group-title="SPORTS", Sky Sport Arena
http://stream.tvtap.live:8081/live/skysports-arena.stream/chunks.m3u8

#EXTINF:-1 tvg-logo="https://i.imgur.com/WMW6hQJ.jpg" group-title="SPORTS", Sky Sport Cricket
http://stream.tvtap.live:8081/live/skysports-cricket1.stream/playlist.m3u8

**Comment by Central302** [comment]
I Found All Sky Sports Channels are in Blacklist. I Close This Isuse
