### ISSUE TITLE
Two Channels Request : NowTV (Hong Kong) 331 & 332

### ISSUE THREAD

**Issue by rarealphacat** [iptv-org/iptv#4084]
Channel Name:** Now TV 332 News
Country:** Hong Kong
Language:** Cantonese
Website:** https://news.now.com/home/live

Channel Name:** Now TV 331 Live
Country:** Hong Kong
Language:** Cantonese
Website:** https://news.now.com/home/live331a

**Comment by Sphinxroot** [comment]
Now TV 331 Live (720p)
https://ewcdnsite04.nowe.com/session/09-2008f6193088b79d836740659dc70/Content/HLS/LIVE/Channel(HLS_CH331)/index.m3u8
https://ewcdnsite04.nowe.com/session/09-2008f6193088b79d836740659dc70/Content/HLS/LIVE/Channel(HLS_CH331)/Stream(03)/index.m3u8

Now TV 332 News (1080p)
https://ewcdnsite09.nowe.com/session/09-2a6fca582d05472e7ceb621f9ef6b/Content/HLS/LIVE/Channel(HLS_CH332N)/index.m3u8
https://ewcdnsite09.nowe.com/session/09-2a6fca582d05472e7ceb621f9ef6b/Content/HLS/LIVE/Channel(HLS_CH332N)/Stream(04)/index.m3u8

but not sure if  this part change over time  could be some kind of token
/session/09-2008f6193088b79d836740659dc70/
/session/09-2a6fca582d05472e7ceb621f9ef6b/

**Comment by freearhey** [comment]
Please read the [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel) before posting your request next time.
