### ISSUE TITLE
Asianet HD

### ISSUE THREAD

**Issue by thepinkmanist** [iptv-org/iptv#4091]
**Channel Name:** Asianet HD
**Country:** India
**Language:** Malayalam
**Website:** https://en.m.wikipedia.org/wiki/Asianet_(TV_channel)
**Stream URL (optional):** xxx
**Notes (optional):** Channel belongs to Star network

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/1934
