### ISSUE TITLE
Kairali News

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4101]
**Channel Name:** Kairali News
**Country:** India
**Language:** Malayalam
**Website:** https://www.kairalinewsonline.com/
**Stream URL (optional):** https://www.youtube.com/watch?v=ET5Y3H3Jusc
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UCkCWitaToNG1_lR-Si1oMrg/live

**Comment by Niyasmkkv** [comment]
> https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UCkCWitaToNG1_lR-Si1oMrg/live

Thanks for the work. But why nobdy is adding these channels?

**Comment by LaneSh4d0w** [comment]
I prefer seeing if that works before adding it.
