### ISSUE TITLE
Kannur One

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4107]
**Channel Name:** Kannur One
**Country:** India
**Language:** Malayalam
**Website:** http://kannurone.com/
**Stream URL (optional):** 
**Notes (optional):** Live stream is available on the website, not able to copy paste it here.

**Comment by LaneSh4d0w** [comment]
https://bnwdplewrp3a-hls-live.wmncdn.net/kannur1/d0dbe915091d400bd8ee7f27f0791303.sdp/playlist.m3u8
