### ISSUE TITLE
Kite Victers

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4108]
**Channel Name:** Kite Victers
**Country:** India
**Language:** Malayalam
**Website:** https://victers.kite.kerala.gov.in/pages/index.html
**Stream URL (optional):** :https://victers.kite.kerala.gov.in/cafc29ac-a62d-4e2d-b479-cb0f6c766bad
**Notes (optional):**

**Comment by LaneSh4d0w** [comment]
Do you appear to know if this stream URL is subject to changes ?

**Comment by Niyasmkkv** [comment]
I'm able to access it now and it's Kerala state's educational channel. And the link should be available all time.

**Comment by LaneSh4d0w** [comment]
Okay, I can't access the entrypoint you gave me, however I could access kerala.gov.in. Let me see.

**Comment by Niyasmkkv** [comment]
> Okay, I can't access the entrypoint you gave me, however I could access kerala.gov.in. Let me see.

Are you able to access this?

https://kite.kerala.gov.in/KITE/firstbell/

**Comment by LaneSh4d0w** [comment]
Doesn't seem. Charging indefinitely and then says that it couldn't answer it.

**Comment by LaneSh4d0w** [comment]
However, I got access to this : http://itschool.gov.in/victersdetails.php

**Comment by Niyasmkkv** [comment]
> However, I got access to this : http://itschool.gov.in/victersdetails.php and this http://victers.itschool.gov.in/ redirecting to http://kite.kerala.gov.in/ . Might be geo-locked

Try this.
https://www.onlinechannels.live/victers-channel/

**Comment by LaneSh4d0w** [comment]
> > However, I got access to this : http://itschool.gov.in/victersdetails.php and this http://victers.itschool.gov.in/ redirecting to http://kite.kerala.gov.in/ . Might be geo-locked
> 
> Try this.
> https://www.onlinechannels.live/victers-channel/

I can get access to this indeed. Gonna look at it soon.

**Comment by LaneSh4d0w** [comment]
https://932y4x26ljv8-hls-live.5centscdn.com/victers/tv.stream/victers/playlist.m3u8
