### ISSUE TITLE
Real News Kerala

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4109]
**Channel Name:** Real News Kerala
**Country:** India
**Language:** Malayalam
**Website:** https://realnewskerala.com/
**Stream URL (optional):** https://realnewskerala.com/live/
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
https://bk7l298nyx53-hls-live.5centscdn.com/realnews/e7dee419f91aa9e65939d3677fb9c4f5.sdp/playlist.m3u8
