### ISSUE TITLE
Pulari TV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4111]
**Channel Name:** Pulari TV
**Country:** India
**Language:** Malayalam
**Website:** https://pularitv.com/index.php
**Stream URL (optional):** :https://royalstarindia.co.in/ee3a5ab0-4103-4130-9ffe-21890137d3e9
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
https://royalstarindia.co.in/pularitv_hls/pularitv.m3u8
