### ISSUE TITLE
Safari TV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4112]
**Channel Name:** Safari Tv
**Country:** India
**Language:** Malayalam
**Website:** https://www.safaritvchannel.com/
**Stream URL (optional):** 
**Notes (optional):** Live stream is available on the website

**Comment by LaneSh4d0w** [comment]
https://j78dp346yq5r-hls-live.5centscdn.com/safari/live.stream/safari/live2/chunks.m3u8

**Comment by Niyasmkkv** [comment]
This stream seems working fine. When can we add this channel?
