### ISSUE TITLE
KCL TV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4113]
**Channel Name:** KCL TV
**Country:** India
**Language:** Malayalam
**Website:** http://kcltv.com/
**Stream URL (optional):** http://kcltv.livebox.co.in/livebox/player/?url=http://kcltv.livebox.co.in/kclhls/live.m3u8
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
http://kcltv.livebox.co.in/kclhls/live.m3u8
