### ISSUE TITLE
Kerala Vision News

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4114]
**Channel Name:** Kerala Vision News
**Country:** India
**Language:** Malayalam
**Website:** https://keralavisiontv.com/
**Stream URL (optional):** https://youtu.be/OmIQGinjmnY
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UCtSeMwydGw6mDSZaIUaJ5bw/live
