### ISSUE TITLE
M4TV Malayalam

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4117]
**Channel Name:** M4TV
**Country:** Australia
**Language:** Malayalam
**Website:** http://m4malayalam.tv/
**Stream URL (optional):** https://www.m4.live/
**Notes (optional):** Also available on https://mhdtvworld.xyz/

**Comment by Sphinxroot** [comment]
https://app.m4stream.live/mfourmalayalamhls/live.m3u8

**Comment by Niyasmkkv** [comment]
> https://app.m4stream.live/mfourmalayalamhls/live.m3u8

Not working on Kodi.

**Comment by Sphinxroot** [comment]
could be geo https://i.imgur.com/kfUxDVl.png

**Comment by Niyasmkkv** [comment]
Working on vlc for me though.

**Comment by Sphinxroot** [comment]
try it with playlistloader addons  kodi 18.9 or for matrix 19+  both work on it

**Comment by Niyasmkkv** [comment]
I will try with the mal playlist once yh channel is added to the list. Why does it taking time to add the channel?

**Comment by LaneSh4d0w** [comment]
Sound's off on my side. Working on VLC, adding it.
