### ISSUE TITLE
Surya TV 

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4118]
**Channel Name:** Surya TV
**Country:** India
**Language:** Malayalam
**Website:** https://sunnetwork.in/Default.aspx?Lang=malayalam
**Stream URL (optional):** https://mhdtvworld.xyz/live/surya-tv-hd/
**Notes (optional):** The current one has Sun Tv hd's link.

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | https://indo51.gcdn.co/MALYLAM-SuryaHD/index.m3u8
-- | --
mediaManifest | https://indo51.gcdn.co/MALYLAM-SuryaHD/tracks-v1a1/mono.m3u8
>

referrer |  https://mhdtvworld.xyz/jwplayer/?source=https%3A%2F%2Findo51.gcdn.co%2FMALYLAM-SuryaHD%2Findex.m3u8&id=70&type=mp4


</body>
</html>





</body>
</html>
