### ISSUE TITLE
Zee Keralam HD

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4119]
**Channel Name:** Zee Keralam
**Country:** India
**Language:** Malayalam
**Website:** https://zeekeralam.zee5.com/
**Stream URL (optional):** https://mhdtvworld.xyz/live/zee-keralam-hd/
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
Token Stream

https://z5ams.akamaized.net/zkeralamhd/index.m3u8?hdnts=st=  + ~exp= + ~acl= /*~hmac=   

<html><body>



pageUrl | https://mhdtvworld.xyz/live/zee-keralam-hd/
-- | --
referrer | https://saalamatv.fun/zee5/getplay.php?c=zkeralamhd




</body>
</html>

**Comment by LaneSh4d0w** [comment]
> 
> 
> Token Stream
> 
> https://z5ams.akamaized.net/zkeralamhd/index.m3u8?hdnts=st= + ~exp= + ~acl= /*~hmac=
> pageUrl 	https://mhdtvworld.xyz/live/zee-keralam-hd/
> referrer 	https://saalamatv.fun/zee5/getplay.php?c=zkeralamhd

https://f8e7y4c6.ssl.hwcdn.net/zkeralamhd/index.m3u8

Backup Link : https://y5w8j4a9.ssl.hwcdn.net/zkeralamhd/index.m3u8

**Comment by LaneSh4d0w** [comment]
@Sphinxroot if you appear to find more links going on "z5ams.akamaized.net", just try to replace host to either f8e7y4c6.ssl.hwcdn.net or y5w8j4a9.ssl.hwcdn.net

Those are also Zee-operated servers and you got a high chance of having it working. No token needed in those servers whatsoever.
