### ISSUE TITLE
Asianet Movies

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4120]
**Channel Name:** Asianet Movies
**Country:** India
**Language:** Malayalam
**Website:** Hotstar.com
**Stream URL (optional):** https://mhdtvworld.xyz/live/2579/
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
https://mhdtvworld.xyz/delta/planet/max.php?id=42350&e=.m3u8 with referer https://mhdtvworld.xyz/delta/planet/play.php?c=42350

However, same thing as the other one.

**Comment by Niyasmkkv** [comment]
> https://mhdtvworld.xyz/delta/planet/max.php?id=42350&e=.m3u8 (forget the referer thing)
> However, same thing as the other one, it doesn't seem to work well on this.

So was it from the apps or the website?

**Comment by LaneSh4d0w** [comment]
Website

**Comment by Niyasmkkv** [comment]
> Website

Any way to use the app's links? It has more channels.

**Comment by LaneSh4d0w** [comment]
I'll see that tomorrow.

**Comment by Sphinxroot** [comment]
masterManifest	
https://mhdtvstreams.in.net/redbox/MHDBOX.php?id=2893&e=.m3u8
mediaManifest	
https://mhdtvstreams.in.net/redbox/MHDBOX.php?id=2893&e=.m3u8
pageUrl	
https://mhdtvworld.xyz/live/2579/
referrer	
https://mhdtvstreams.in.net/redbox/play.php?c=2893

PHP File
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:3
#EXT-X-MEDIA-SEQUENCE:534
#EXTINF:1.2,
stream.php?stream=http://livezer0.hjkm.info:11991/vulcan/asianetmovies/l_12612183_37608420_534.ts&nimblesessionid=775558&wmsAuthSign=c2VydmVyX3RpbWU9OC8xNy8yMDIxIDk6MTc6NTggQU0maGFzaF92YWx1ZT1Sb205TXNLVmFRbjdINjI1UUhPSVZ3PT0mdmFsaWRtaW51dGVzPTI=
#EXT-X-DISCONTINUITY
#EXTINF:1.8,
stream.php?stream=http://livezer0.hjkm.info:11991/vulcan/asianetmovies/l_12612183_37609620_535.ts&nimblesessionid=775558&wmsAuthSign=c2VydmVyX3RpbWU9OC8xNy8yMDIxIDk6MTc6NTggQU0maGFzaF92YWx1ZT1Sb205TXNLVmFRbjdINjI1UUhPSVZ3PT0mdmFsaWRtaW51dGVzPTI=
#EXT-X-DISCONTINUITY
#EXTINF:0.6,
stream.php?stream=http://livezer0.hjkm.info:11991/vulcan/asianetmovies/l_12612183_37611420_536.ts&nimblesessionid=775558&wmsAuthSign=c2VydmVyX3RpbWU9OC8xNy8yMDIxIDk6MTc6NTggQU0maGFzaF92YWx1ZT1Sb205TXNLVmFRbjdINjI1UUhPSVZ3PT0mdmFsaWRtaW51dGVzPTI=
and so on

base64 wmsAuthSign=
server_time=8/17/2021 9:17:58 AM&hash_value=Rom9MsKVaQn7H625QHOIVw==&validminutes=2

**Comment by Niyasmkkv** [comment]
Not working.

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/1934
