### ISSUE TITLE
Butterfly HDTV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4123]
**Channel Name:** Butterfly HD TV
**Channel ID:** ButterflyHDTV.ae
**Country:** AE
**Language:** Malayalam
**Website:** https://www.butterflyhdtv.com/
**Stream URL (optional):** https://play.google.com/store/apps/details?id=com.butterflyhdtv.butterflyhd
**Notes (optional):** xxx

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/4306

**Comment by freearhey** [comment]
Closed in favor of #12279
