### ISSUE TITLE
CMT Canada

### ISSUE THREAD

**Issue by creeps125** [iptv-org/iptv#4127]
**Channel Name:** CMT 
**Channel ID:** CMTCanada.ca
**Country:** Canada
**Language:** English
**Website:** cmt.ca

**Comment by creeps125** [comment]
I am actually referring to the CANADIAN version of CMT, not the US one.

**Comment by LaneSh4d0w** [comment]
He deleted the mention of it because you already tell us with the issue that you're talking about that particular version.

**Comment by Dum4G** [comment]
https://www.corusent.com/contact-us/

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/1941

**Comment by freearhey** [comment]
Closed in favor of #12278
