### ISSUE TITLE
Garshom TV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4130]
**Channel Name:** Garshom TV
**Country:** UK
**Language:** Malayalam
**Website:** http://www.garshom.tv/
**Stream URL (optional):** http://www.garshom.tv/
**Notes (optional):** Stream is available on the website

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | http://og2qd3aal7an-hls-live.5centscdn.com/garshomtv/d0dbe915091d400bd8ee7f27f0791303.sdp/playlist.m3u8
-- | --
mediaManifest | http://og2qd3aal7an-hls-live.5centscdn.com/garshomtv/d0dbe915091d400bd8ee7f27f0791303.sdp/chunks.m3u8


</body>
</html>
