### ISSUE TITLE
Anand TV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4131]
**Channel Name:** Anand TV
**Country:** US
**Language:** Malayalam
**Website:** https://anandmedia.net/
**Stream URL (optional):** https://anandmedia.net/livetv
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | https://live-anandtv.anandmedia.net/anandtvapp/anandtv/index.m3u8
-- | --
mediaManifest | https://live-anandtv.anandmedia.net/anandtvapp/anandtv/tracks-v1a1/mono.m3u8


</body>
</html>
