### ISSUE TITLE
Add some stöd 2 channels

### ISSUE THREAD

**Issue by erginozcan1993** [iptv-org/iptv#4133]
**Channel Name:** Stod 2 Visir
**Country:** Iceland
**Language:** Icelandic
**Website:** http://www.visir.is
**Stream URL (optional):** https://sjonvarp.stod2.is/live/143
**Notes (optional):** It might be geo-blocked and using DRM

**Channel Name:** Stod 2 Sport Kynning
**Country:** Iceland
**Language:** Icelandic
**Website:** http://www.stod2.is
**Stream URL (optional):** https://sjonvarp.stod2.is/live/162
**Notes (optional):** It might be geo-blocked and using DRM

**Comment by Sphinxroot** [comment]
Playback is only allowed within EEA countries

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel
