### ISSUE TITLE
Update Malian tv Channels

### ISSUE THREAD

**Issue by kone78** [iptv-org/iptv#4137]
Update  tv Channels from Mali
#EXTM3U
#EXTINF:0 type="stream" channelId="-1" group="MALI" logo="https://www.lyngsat.com/logo/tv/oo/ortm-1-ml.png", ORTM 1
https://stream.mmsiptv.com/droid/ortm/playlist.m3u8
#EXTINF:0 type="stream" channelId="-1" group="MALI" logo="https://www.lyngsat.com/logo/tv/aa/africable_tv.png", AFRICABLE
https://stream.mmsiptv.com/droid/africable/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
404 Not Found on both of them.

**Comment by Dum4G** [comment]
Both play well for me
