### ISSUE TITLE
Fix: True Real (WIPXDT6)

### ISSUE THREAD

**Issue by stanloonabelike** [iptv-org/iptv#4138]
Hello so I was watching hoarders and it went off. it said stream ended and I use stremium so I would like this fixed asap

**Comment by LaneSh4d0w** [comment]
@MapGuy11 @jkemp814 I don't know if one of you got this channel.

**Comment by MapGuy11** [comment]
> @MapGuy11 @jkemp814 I don't know if one of you got this channel.

I do

**Comment by MapGuy11** [comment]
> 
> Hello so I was watching hoarders and it went off. it said stream ended and I use stremium so I would like this fixed asap

Still works.

**Comment by Dum4G** [comment]
Confirmed working atm
