### ISSUE TITLE
Sun News

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4139]
**Channel Name:** Sun News
**Country:** IN
**Language:** Tamil
**Website:** http://www.sunnewslive.in/
**Stream URL (optional):** https://www.youtube.com/watch?v=xnk9g38W_5w
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UCYlh4lH762HvHt6mmiecyWQ/live

**Comment by Niyasmkkv** [comment]
@LaneSh4d0w why those channels are not updated yet? how much time it will take?

**Comment by LaneSh4d0w** [comment]
A bot updates the publically available playlists at 2 AM (UTC+2).

**Comment by MapGuy11** [comment]
@LaneSh4d0w 403 error for me

**Comment by jkemp814** [comment]
Plays fine from southwest U.S.

**Comment by MapGuy11** [comment]
403. That’s an error.

Your client does not have permission to get URL /api/manifest/hls_playlist/expire/1629271722/ei/SmIcYdONGvX-xN8PhLChsAY/ip/54.217.146.158/id/xnk9g38W_5w.2/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir=yes;itag=140/sgovp/gir=yes;itag=137/hls_chunk_host/rr2---sn-q0c7rn76.googlevideo.com/playlist_duration/30/manifest_duration/30/vprv/1/playlist_type/DVR/mh/nz/mm/44/mn/sn-q0c7rn76/ms/lva/mv/u/mvi/2/pl/15/dover/11/keepalive/yes/fexp/24001373,24007246/mt/1629249219/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,vprv,playlist_type/sig/AOq0QJ8wRgIhAOZqHG5zpYlL5WCvD-tNVjwSs3iAY38qta7dFshr-01oAiEAy547N9Te35G4E2z5QDJVCOV4v4N6uncdjGEx5zLDguk=/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRAIgI5oem1XXoZ1ZN-Rvlh5T7qyRmvwOuP3vPkNN6vUIFzwCIBXmQb2BhX8dJkQUDRHIjNVhU0KDjVKwEmEWkrhxgydj/playlist/index.m3u8 from this server. That’s all we know.

**Comment by MapGuy11** [comment]
Btw 54.217.146.158 is not my IP address so I don't know where it got that.

**Comment by Sphinxroot** [comment]
i get 403  must be geo 
Flussonic Stream
http://185.246.209.207/TAMIL_SUN_NEWS_TAMIL/index.m3u8

YT  oki for me
