### ISSUE TITLE
Tunes 6

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4140]
**Channel Name:** Tunes 6
**Country:** IN
**Language:** Tamil
**Website:** Tunes6.com
**Stream URL (optional):** https://www.mxplayer.in/live-tv/tunes-6/selfie-request-30000000550204845-140
**Notes (optional):** xxx

**Comment by Dum4G** [comment]
https://m-c18-j2apps.s.llnwi.net/hls/3731.Tunes6.in.m3u8

Can't test if it works, I have Error 400 with Indian VPN. Geo-blocked

**Comment by Niyasmkkv** [comment]
Not working with Kodi, but works fine with VLC.
https://imgur.com/a/5xp5Oq9

**Comment by Niyasmkkv** [comment]
@Dum4G in Vlc once the video changes its resolution, there is no audio.

**Comment by Dum4G** [comment]
¯\_(ツ)_/¯

**Comment by Niyasmkkv** [comment]
https://m-c18-j2apps.s.llnwi.net/hls/3731.Tunes6.in.m3u8
