### ISSUE TITLE
Fix Sony Six,Sony Sab, Star Sports (India) 

### ISSUE THREAD

**Issue by shom13** [iptv-org/iptv#4142]
The channels listed above are in the playlist but are not playing any longer. They are in the country list under India.

**Comment by Sphinxroot** [comment]
Until we find the way to make those stream working in the list  ( MHDBOXx.php and max.php )

you can see  it here for now
https://mhdtvworld.xyz/?s=sony

https://mhdtvworld.xyz/live/star-sports-2-hd/ only 

but jtv/jiolivee.php link  play them in kodi with 2 addons

**Comment by shom13** [comment]
Thanks for the quick response

**Comment by LaneSh4d0w** [comment]
![image](https://user-images.githubusercontent.com/30985701/129877827-e022f6a4-987c-42b9-9acd-028ba53c91c2.png)
Sony Sab works for me.

**Comment by shom13** [comment]
> ![image](https://user-images.githubusercontent.com/30985701/129877827-e022f6a4-987c-42b9-9acd-028ba53c91c2.png)
> Sony Sab works for me.

Could you share how you got it to work, perhaps share the link, it doesnt work at all for me, it says not authorized when checking the link

**Comment by shom13** [comment]
Could you kindly share the link, as the link that i am using doent work with vlc for me at the moment

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-logo="http://cms.businesswireindia.com/Uploads/companyLogo/Sony_8348.jpg" group-title="",Sony Sab
http://208.115.215.42/Sony_Sab_HD/tracks-v1a1/mono.m3u8


#EXTINF:-1 tvg-logo="https://i.imgur.com/6a7pWRE.png" group-title="Sports",Sony Six HD
http://tvflix02.ddns.net//SPORTS__SONY_SIX_HD/video.m3u8
#EXTINF:-1 tvg-logo="https://i.imgur.com/6a7pWRE.png" group-title="Sports",Sony Six
http://84.17.41.7:80/sonysixhd/mono.m3u8

**Comment by LaneSh4d0w** [comment]
> #EXTINF:-1 tvg-logo="http://cms.businesswireindia.com/Uploads/companyLogo/Sony_8348.jpg" group-title="",Sony Sab
> http://208.115.215.42/Sony_Sab_HD/tracks-v1a1/mono.m3u8
> 
> 
> #EXTINF:-1 tvg-logo="https://i.imgur.com/6a7pWRE.png" group-title="Sports",Sony Six HD
> http://tvflix02.ddns.net//SPORTS__SONY_SIX_HD/video.m3u8
> #EXTINF:-1 tvg-logo="https://i.imgur.com/6a7pWRE.png" group-title="Sports",Sony Six
> http://84.17.41.7:80/sonysixhd/mono.m3u8

First one is exactly the one we have in the playlists.

**Comment by shom13** [comment]
Thank you so much for the quick response. I got sony six up and running, but sony sab is still not working with that link.

**Comment by shom13** [comment]
Ok so just checked, the link provided for sony sab works with a vpn. So its probably a region based thing, hence cant access from india

**Comment by freearhey** [comment]
Closed in favor #4311 and #4310

**Comment by nikhil96widhani** [comment]
> Ok so just checked, the link provided for sony sab works with a vpn. So its probably a region based thing, hence cant access from india

Hi which region vpn you are using?

**Comment by 19kaval** [comment]
Stra sports channel link
