### ISSUE TITLE
KCV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4143]
**Channel Name:** KCV
**Country:** IN
**Language:** Malayalam
**Website:** http://kcvonline.com/
**Stream URL (optional):** https://play.google.com/store/apps/details?id=com.app.KCVTV
**Notes (optional):** Stream is available on this app.

**Comment by Sphinxroot** [comment]
not sure if we can add them to list  .. i got more channel from the same host

#EXTINF:-1 tvg-logo="https://i.imgur.com/KP4qSJA.png" group-title="",KCV
http://198.144.149.82:8080/NOTV/KCVTV/index.m3u8?token=GTR

#EXTINF:-1 tvg-logo="https://i.imgur.com/7nAV9O7.png" group-title="",KCV Movies
http://198.144.149.82:8080/NOTV/KCVMOVIE/index.m3u8?token=GT

**Comment by Niyasmkkv** [comment]
Getting 403 for me.

**Comment by Niyasmkkv** [comment]
KCV works fine with VLC, But KCV movies showing invalid URL.

**Comment by Sphinxroot** [comment]
corrected retry :)

**Comment by Niyasmkkv** [comment]
Working fine now. Can we add these two the list?

**Comment by Niyasmkkv** [comment]
@Dum4G what about these channels?

**Comment by Niyasmkkv** [comment]
Can we add links like this?

**Comment by Dum4G** [comment]
Doesn't look like expiring token so we can give it a chance
