### ISSUE TITLE
Kannur Vision

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4144]
**Channel Name:** Kannur Vision
**Country:** IN
**Language:** Malayalam
**Website:** https://kannurvisionchannel.com/kv/
**Stream URL (optional):** https://kannurvisionchannel.com/kv/?page_id=2
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | https://stream.ufworldind.in/live/kvision/playlist.m3u8
-- | --
mediaManifest | https://stream.ufworldind.in/live/kvision/chunklist_w1371245545.m3u8


</body>
</html>

360p

**Comment by Niyasmkkv** [comment]
This channel was replaced by Kannur One. Now Kannur one is missing from the list.
