### ISSUE TITLE
Malabar News 

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4145]
**Channel Name:** Malabar News 
**Country:** IN
**Language:** Malayalam
**Website:** http://malabarnewschannel.com
**Stream URL (optional):** http://malabarnewschannel.com/newslive.html
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | http://cloud.logicwebs.in:1935/live/malabarnews/playlist.m3u8
-- | --
mediaManifest | http://cloud.logicwebs.in:1935/live/malabarnews/chunklist_w1886725382.m3u8


</body>
</html>

720p
