### ISSUE TITLE
Pravasi HD

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4146]
**Channel Name:** Pravasi HD
**Country:** IN
**Language:** Malayalam
**Website:** https://www.pravasichannel.com/
**Stream URL (optional):** https://mhdtvworld.xyz/0506375e-85a5-4383-b24f-75a096b010a7
**Notes (optional):** xxx

**Comment by Dum4G** [comment]
https://5ee50688d7b5d.streamlock.net:444/live/pravasi/playlist.m3u8
