### ISSUE TITLE
Kerala Vision

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4147]
**Channel Name:** Kerala Vision ST
**Country:** IN
**Language:** Malayalam
**Website:** https://www.lyngsat.com/tvchannels/in/Kerala-Vision.html
**Stream URL (optional):** https://mhdtvworld.xyz/07e40308-516e-4e74-8565-193f8c2bdc89
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
http://103.199.161.254/Content/keralvisionst/Live/Channel(KeralvisionST)/index.m3u8

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2174993,RESOLUTION=640x360
Stream(01)/index.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2685863,RESOLUTION=1024x576
Stream(02)/index.m3u8

**Comment by Niyasmkkv** [comment]
http://103.199.161.254/Content/keralavision/Live/Channel(Keralavision)/Stream(01)/index.m3u8

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/1934

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/198d0527f073c81119ccceaebdede8e79f542028/streams/in.m3u#L267-L268
