### ISSUE TITLE
Nee Cinema

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4149]
**Channel Name:** Nee Cinema
**Country:** IN
**Language:** Malayalam
**Website:** https://neestream.com/
**Stream URL (optional):** https://mhdtvworld.xyz/59d7c694-90a5-4a5f-90db-d60096dce40d
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
#EXTINF: -1 tvg-id="" tvg-name="Nee Cinema" tvg-logo="" group-title="MOVIES", Nee Cinema
https://live.neestream.com/neestream_01/nee_cinema/tracks-v1a1/mono.m3u8
