### ISSUE TITLE
Darshana TV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4150]
**Channel Name:** Darshana TV
**Country:** IN
**Language:** Malayalam
**Website:** http://www.darshanatv.in/
**Stream URL (optional):** https://mhdtvworld.xyz/1b38ceb5-c23d-4271-b0b9-0515ac42e4cb
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-logo="https://www.tvchannelpricelist.com/wp-content/uploads/channels-logo-300/darshana-tv-channel-logo-300x300.jpg",Darshana TV
https://streaming37.worldbbtv.com/hls/darshana.m3u8
