### ISSUE TITLE
Jeevan TV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4152]
**Channel Name:** Jeevan TV
**Country:** IN
**Language:** Malayalam
**Website:** http://jeevannewsonline.com/
**Stream URL (optional):** https://mhdtvworld.xyz/fcbb59e4-1e00-40a3-b854-a9655d8d53a4
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
allready in the list 



#EXTINF:-1 tvg-id="JeevanTV.in" tvg-name="Jeevan TV" tvg-country="IN" tvg-language="Hindi" tvg-logo="" group-title="",Jeevan TV (576p)
http://103.199.161.254/Content/jeevan/Live/Channel(Jeevan)/index.m3u8

**Comment by Niyasmkkv** [comment]
Channel language is Malayalam, showing in Hindi list.

**Comment by Sphinxroot** [comment]
https://i.imgur.com/vIxvz36.png  left is web site right it the link in kodi

**Comment by Niyasmkkv** [comment]
> allready in the list 
> 
> 
> 
> #EXTINF:-1 tvg-id="JeevanTV.in" tvg-name="Jeevan TV" tvg-country="IN" tvg-language="Hindi" tvg-logo="" group-title="",Jeevan TV (576p)
> http://103.199.161.254/Content/jeevan/Live/Channel(Jeevan)/index.m3u8
> 
> 

Need to make few changes, language should be Malayalam.

**Comment by Niyasmkkv** [comment]
@Dum4G  updated the logos with imgur links
