### ISSUE TITLE
Super Sport Cricket

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4154]
**Channel Name:** Super Sport Cricket
**Country:** SA
**Language:** English
**Website:** https://supersport.com/cricket
**Stream URL (optional):** https://cutt.ly/EQjHnWd
**Notes (optional):** xxx

**Comment by Niyasmkkv** [comment]
@LaneSh4d0w @Dum4G https://cutt.ly/EQjHnWd 
Is this working for you guys?

**Comment by Dum4G** [comment]
Surprosonhly yes. I'm not sure this link will stay for long, especially if many other users gonna watch it simultaneously

**Comment by Niyasmkkv** [comment]
I found few links like this for some criket channels.

**Comment by LaneSh4d0w** [comment]
Hmm... sounds like an Xtream codes / Flussonic server to me.

**Comment by Niyasmkkv** [comment]
Will close this then.
