### ISSUE TITLE
Polimer News

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4157]
**Channel Name:** Polimer News
**Country:** IN
**Language:** Tamil
**Website:** https://www.polimernews.com/dlive-tv
**Stream URL (optional):** https://www.youtube.com/watch?v=r44SqwmQ3Bo
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UC8Z-VjXBtDJTvq6aqkIskPg/live

Very interesting that lots of societies go through YouTube to stream their channel. At the same time, it's understandable, because it's free.
