### ISSUE TITLE
Puthiya Thalaimurai 

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4158]
**Channel Name:** PuthiyaThalaimurai 
**Country:** IN
**Language:** Tamil
**Website:**  http://www.puthiyathalaimurai.com
**Stream URL (optional):** https://www.youtube.com/watch?v=JddGlT64N2s
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UCmyKnNRH0wH-r8I-ceP-dsg/live
