### ISSUE TITLE
News 7 Tamil Prime

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4159]
**Channel Name:** News 7 Tamil Prime
**Country:** IN
**Language:** Tamil
**Website:** 
**Stream URL (optional):** https://www.youtube.com/watch?v=A7Qq-1lAax4
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
No stream coming from this channel.

**Comment by Niyasmkkv** [comment]
https://youtu.be/zZ17Xx_dHZw

**Comment by LaneSh4d0w** [comment]
https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UC2f4w_ppqHplvjiNaoTAK9w/live
