### ISSUE TITLE
News J

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4160]
**Channel Name:** News J
**Country:** IN
**Language:** Tamil
**Website:** xxx
**Stream URL (optional):** https://youtu.be/li7ij1vw2Mo
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UCsfh2Zb7-m4qzT8jLhK_Fzw
