### ISSUE TITLE
Sathiyam TV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4161]
**Channel Name:** Sathiyam TV
**Country:** IN
**Language:** Tamil
**Website:** https://www.sathiyam.tv
**Stream URL (optional):** https://youtu.be/ODb9krc7q-o
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UC2ziCMHFPWkFHjocUMXT__Q/live
