### ISSUE TITLE
Docustream

### ISSUE THREAD

**Issue by erginozcan1993** [iptv-org/iptv#4163]
**Channel Name:** Docustream
**Channel ID:** Docustream.nl
**Country:** UK
**Language:** English
**Website:** https://www.spiintl.com
**Stream URL (optional):** xxx
**Notes (optional):** Brand new channel in Samsung TV Plus

**Comment by Dum4G** [comment]
Closed in favor of #3145

**Comment by freearhey** [comment]
Closed in favor of #12276
