### ISSUE TITLE
Real TV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4166]
**Channel Name:** Real TV
**Country:** IN
**Language:** Malayalam
**Website:** xxx
**Stream URL (optional):** http://expressott.in/11939866-f675-43e1-82d8-ac76df920493
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | http://cloud.logicwebs.in:1935/realtv/realtv1/playlist.m3u8
-- | --
mediaManifest | http://cloud.logicwebs.in:1935/realtv/realtv1/chunklist_w1817369200.m3u8


</body>
</html>

<html><body>


referrer | http://expressott.in/live-tv/real-tv.html
-- | --



</body>
</html>

<html><body>


thumbnailUrl | http://expressott.in/uploads/tv_image/real-tv.jpg
-- | --



</body>
</html>
