### ISSUE TITLE
Dreamz

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4167]
**Channel Name:** Dreamz
**Country:** India
**Language:** Malayalam
**Website:** xxx
**Stream URL (optional):** http://expressott.in/6d2dc651-d89f-469d-b46b-6329a0e025b4
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | http://198.144.149.82:8080/NOTV/DREAMHD/index.m3u8?token=GTR
-- | --
mediaManifest | http://198.144.149.82:8080/NOTV/DREAMHD/tracks-v1a1/mono.m3u8?token=GTR


</body>
</html>

<html><body>


thumbnailUrl | http://expressott.in/uploads/tv_image/dream-hd.png
-- | --



</body>
</html>
