### ISSUE TITLE
Time Vision News

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4168]
**Channel Name:** Time Vision News
**Country:** IN
**Language:** Malayalam
**Website:** xxx
**Stream URL (optional):** http://expressott.in/e09c06ff-fbf4-46dc-a56f-ad4a872f1900
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | http://cloud.logicwebs.in:1935/timevision/timevision/playlist.m3u8
-- | --
mediaManifest | http://cloud.logicwebs.in:1935/timevision/timevision/chunklist_w1920777711.m3u8


</body>
</html>
<html><body>


referrer | http://expressott.in/live-tv/time-vision.html
-- | --



</body>
</html>
<html><body>


thumbnailUrl | http://expressott.in/uploads/tv_image/time-vision.jpg
-- | --



</body>
</html>
