### ISSUE TITLE
Relax TV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4169]
**Channel Name:** Relax TV
**Country:** IN
**Language:** Malayalam
**Website:** http://expressott.in/live-tv/relax-tv.html
**Stream URL (optional):** http://expressott.in/82e0e66b-4d5d-4c6b-870c-4b1d87330a9f
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | http://198.144.149.82:8080/NOTV/RELAXTV/index.m3u8?token=GTR
-- | --
mediaManifest | http://198.144.149.82:8080/NOTV/RELAXTV/tracks-v1a1/mono.m3u8?token=GTR


</body>
</html>

<html><body>


thumbnailUrl | http://expressott.in/uploads/tv_image/relax-tv.png
-- | --



</body>
</html>
