### ISSUE TITLE
Fox News

### ISSUE THREAD

**Issue by acuaroyale** [iptv-org/iptv#417]
Fox News preview feeds (256x144) lack audio, only working feed (mono.m3u8) dead. (US/News)

**Comment by boomski** [comment]
You are right , I found an alternative for the dead link 
https://1028107998.rsc.cdn77.org/ropX9D3FZnjYbQh30lr8dg==,1570305603/ls-54548-2/tracks-v1a1/mono.m3u8

And  I will make a pull request

**Comment by acuaroyale** [comment]
Alternative leads to 410 response status.

**Comment by boomski** [comment]
Hmm, I think they put a token in the url  that expires every, X Hours
https://1028107998.rsc.cdn77.org/P1lIQsIVkbzzNvylwq0FLQ==,1570316401/ls-54548-2/tracks-v1a1/mono.m3u8 , we look further for an alternative

**Comment by exodiver** [comment]
#EXTINF:-1,FOX News
https://1161275585.rsc.cdn77.org/LS-ATL-54548-4/tracks-v1a1/mono.m3u8

Hope it helps.

**Comment by freearhey** [comment]
@exodiver Thanks, it definitely helped!
