### ISSUE TITLE
M Sign Media

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4170]
**Channel Name:** M Sign Media
**Country:** IN
**Language:** Malayalam
**Website:** xxx
**Stream URL (optional):** http://expressott.in/7f7aa3f9-e9cb-4fcf-8de7-1416bc3c5da1
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | http://cloud.logicwebs.in:1935/msign/msignmedia/playlist.m3u8
-- | --
mediaManifest | http://cloud.logicwebs.in:1935/msign/msignmedia/chunklist_w2094641701.m3u8


</body>
</html>
<html><body>


referrer | http://expressott.in/live-tv/m-sign-media.html
-- | --



</body>
</html>

<html><body>


thumbnailUrl | http://expressott.in/uploads/tv_image/m-sign-media.PNG
-- | --



</body>
</html>
