### ISSUE TITLE
CBC Toronto {NOT GEO-BLOCKED BEFORE!}??

### ISSUE THREAD

**Issue by mememe0142** [iptv-org/iptv#4173]
xxx
**Channel Name:**CBC Toronto
**Country:** CA
**Language:** xxx
**Website:** xxx
**Stream URL (optional):** xxx
**Notes (optional):CBC Toronto {NOT GEO-BLOCKED BEFORE!}?? 
Why is it now Geo-blocked?

**Comment by Dum4G** [comment]
Previous source was unofficial, now we use an official stream that is offered on CBC Gem and supposed to be shown for Canadian viewers

**Comment by Sphinxroot** [comment]
there is 2 options  

1  vpn or proxy script

2 in kodi  you can trick the player in youre own m3u playlist as per exemple in playlistloader addon

by using ?|X-Forwarded-For= after the .m3u8   and find a Canadian ISP IP Address that fit for you and play the stream
