### ISSUE TITLE
Polimer TV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4176]
**Channel Name:** Polimer TV
**Country:** IN
**Language:** Tamil
**Website:** 
**Stream URL (optional):** http://cdn.asianetmobiletvplus.com/channels/polimertv_rpvpvdefkpxbafsouzockpitjldtogrr/chunks.m3u8
**Notes (optional):** Logo - https://i.imgur.com/FeLT0mK.jpg

**Comment by Dum4G** [comment]
You can start adding them via PR, you're doing good. tvg-id and tvg-name will fill themselves during the playlist generation. Don't forget to put `Closes https://github.com/iptv-org/iptv/issues/4149` like stings into description to close related requests automatically.
