### ISSUE TITLE
Canal RCN

### ISSUE THREAD

**Issue by dcuervog92** [iptv-org/iptv#4182]
**Channel Name:** Canal RCN
**Country:** CO
**Language:** Spanish
**Website:** http://www.canalrcn.com
**Stream URL (optional):** https://www.dailymotion.com/cdn/live/video/x7vyv0z.m3u8?sec=92MOLwNeefsP3yChf6Y1nDUsu4J8MjeGauhPC2yHK9VEuxCt1UtawiZ3EH1DN40edDVtgFVukZE4ALN-KjJmcQ
**Notes (optional):** The Dailymotion link uses a token that expires in 1 week.

**Comment by LaneSh4d0w** [comment]
Private stream, cannot be played.

If it comes back however, there it is : https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.dailymotion.com/video/x7vyv0z

**Comment by LaneSh4d0w** [comment]
Hmm... I made it work using a Colombian proxy, but it doesn't play anywhere else than in the RCN webpage. If you try directly from Dailymotion it'll say "Contenido privado". Testing some techniques.

**Comment by Toei79** [comment]
the proxy dont down speed?

**Comment by LaneSh4d0w** [comment]
> 
> 
> the proxy dont down speed?
> 
> it can be used wuth caracol too

Had upgraded to Fiber, can't really say it turns the speed down (the colombian proxy was quite fast to be honest)

It can be used, but for now I can't seem to know how to inject headers and/or referrers to Streamlink.

**Comment by LaneSh4d0w** [comment]
streamlink --http-proxy "socks4://181.78.23.35:5678" --http-header https://mdstrm.com/live-stream-playlist/574463697b9817cf0886fc17.m3u8 best

would be the one for Caracol.

**Comment by Toei79** [comment]
nice some way ignorant here, i mean ths proxy it be stop working eventually? 

how this works? i mean if data go through the proxy it need a good bandwith or its not?

other route 
daylimotion.

https://github.com/benmoose39/dailymotion_to_m3u

**Comment by Toei79** [comment]
idk if its normal but rcn on daylimotion its private you cant watch there just on the rcn webpage.

**Comment by LaneSh4d0w** [comment]
> 
> 
> nice some way ignorant here, i mean ths proxy it be stop working eventually?
> 
> how this works? i mean if data go through the proxy it need a good bandwith or its not?
> 
> other route
> daylimotion.
> 
> https://github.com/benmoose39/dailymotion_to_m3u

This proxy can be offline yes, I can give a pool of proxies and he picks the one that works I suppose.

How it works is that Streamlink will forward the request to the proxy, making the request for us. If it answers correctly, Streamlink will pick the playlist data, and the stream will be played, backed up by the proxy that is operating.

This program would work if the stream wasn't actually "private" from anywhere else than the RCN website.

**Comment by dcuervog92** [comment]
> > nice some way ignorant here, i mean ths proxy it be stop working eventually?
> > how this works? i mean if data go through the proxy it need a good bandwith or its not?
> > other route
> > daylimotion.
> > https://github.com/benmoose39/dailymotion_to_m3u
> 
> This proxy can be offline yes, I can give a pool of proxies and he picks the one that works I suppose.
> 
> How it works is that Streamlink will forward the request to the proxy, making the request for us. If it answers correctly, Streamlink will pick the playlist data, and the stream will be played, backed up by the proxy that is operating.
> 
> For the other option, I suppose this program would work if the stream wasn't actually "private" from anywhere else than the RCN website. What this program does I'm quite sure I could replicate it, but well, changing streams all the time is painful.

And adding a referrer? That simulates when I enter to the website.

**Comment by LaneSh4d0w** [comment]
> 
> 
> > > nice some way ignorant here, i mean ths proxy it be stop working eventually?
> > > how this works? i mean if data go through the proxy it need a good bandwith or its not?
> > > other route
> > > daylimotion.
> > > https://github.com/benmoose39/dailymotion_to_m3u
> > 
> > 
> > This proxy can be offline yes, I can give a pool of proxies and he picks the one that works I suppose.
> > How it works is that Streamlink will forward the request to the proxy, making the request for us. If it answers correctly, Streamlink will pick the playlist data, and the stream will be played, backed up by the proxy that is operating.
> > For the other option, I suppose this program would work if the stream wasn't actually "private" from anywhere else than the RCN website. What this program does I'm quite sure I could replicate it, but well, changing streams all the time is painful.
> 
> And adding a referrer? That simulates when I enter to the website.

It was the first thing I thought about, doesn't work.

**Comment by Toei79** [comment]
its anyway for get working links from here?

`https://www.chatytvgratishd.me/canal-caracol-tv-streaming-vivo/`

i able to get some but expire

**Comment by LaneSh4d0w** [comment]
> `https://www.chatytvgratishd.me/canal-caracol-tv-streaming-vivo/`

https://tna5.bozztv.com/c1mdrgsergaerg/index.m3u8

**Comment by Toei79** [comment]
thx there its other kind of there its posdibel get those there its rcn

thanks for the help

**Comment by LaneSh4d0w** [comment]
> 
> 
> thx there its other kind of there its posdibel get those there its rcn
> 
> thanks for the help

I miiiiight get the other Caracol if I manage to read the "wigistream.to" stream correctly.

As for RCN, i'll take a look.

**Comment by Toei79** [comment]
you able to play this one?

https://tna5.bozztv.com/c1mdrgsergaerg/index.m3u8

**Comment by LaneSh4d0w** [comment]
streamlink --http-header "Referer=https://ssh101.com/" https://tna5.bozztv.com/c2wdsegrtjtyk/index.m3u8 best

**Comment by LaneSh4d0w** [comment]
RCN is https://tna5.bozztv.com/r1esfergwrerg/index.m3u8 with referrer https://ssh101.com

**Comment by Toei79** [comment]
new using streamlink , referer that help to play it?

**Comment by LaneSh4d0w** [comment]
> 
> 
> new using streamlink , referer that help to play it?

Some streams are referrer-locked, meaning that you basically can only stream this content only if you came from the website that has it.

**Comment by LaneSh4d0w** [comment]
City TV Bogotà : https://tna5.bozztv.com/ctyserhehb/index.m3u8 with referrer https://ssh101.com/

**Comment by Toei79** [comment]
its anyway to get from here?

`https://canal1.com.co/senal-en-vivo`

its geo locked but i able to get a long link with idm

`https://us-b5-p-e-kj2.cdn.mdstrm.com/live-stream/5a5e1c2568b1910913db5fe2/publish/media_1000.m3u8?aid=5a1dafd63910b04010338038&uid=3hqvnlvj0I5Xz9kdihijVccFsHCQGjyH&sid=kCvR23GdwgTF0dt4fx1OLgP9fSbwEsNp&pid=4SHR4GOZyZfQ3bT6llWDtQwj50F8S1Th&ref=https%3A%2F%2Fcanal1.com.co%2F&without_cookies=false&dnt=true&es=us-b5-p-e-kj2.cdn.mdstrm.com&ote=1629578206426&ot=jFS2X5oGZWaK5jg8LlvRNQ&proto=https&pz=us`



![08-20-2021 (164336)](https://user-images.githubusercontent.com/79808610/130291542-32275ca0-d792-4289-88fd-d84db7cd392f.jpg)

its possible get from those others? i guess its another  one ssh01 but other one its different

**Comment by LaneSh4d0w** [comment]
> 
> 
> its anyway to get from here?
> 
> `https://canal1.com.co/senal-en-vivo`
> 
> its geo locked but i able to get a long link with idm
> 
> `https://us-b5-p-e-kj2.cdn.mdstrm.com/live-stream/5a5e1c2568b1910913db5fe2/publish/media_1000.m3u8?aid=5a1dafd63910b04010338038&uid=3hqvnlvj0I5Xz9kdihijVccFsHCQGjyH&sid=kCvR23GdwgTF0dt4fx1OLgP9fSbwEsNp&pid=4SHR4GOZyZfQ3bT6llWDtQwj50F8S1Th&ref=https%3A%2F%2Fcanal1.com.co%2F&without_cookies=false&dnt=true&es=us-b5-p-e-kj2.cdn.mdstrm.com&ote=1629578206426&ot=jFS2X5oGZWaK5jg8LlvRNQ&proto=https&pz=us`
> 
> ![08-20-2021 (164336)](https://user-images.githubusercontent.com/79808610/130291542-32275ca0-d792-4289-88fd-d84db7cd392f.jpg)
> 
> its possible get from those others? i guess its another one ssh01 but other one its different

Aaaaaah... Canal 1... their stream is between locked and unlocked. It *sometimes* works, *sometimes* doesn't. It's possible but needs a Colombian IP.

**Comment by Toei79** [comment]
maybe with proxy option? im watching with vpn but those links that i get not are working

**Comment by LaneSh4d0w** [comment]
It works using a proxy, sure, but I can't implement that for everyone, the API documentation for Streamlink concerning our way to work with Python is inexistant.

**Comment by Toei79** [comment]
oh i thought this can be like one with caracol you use before or its different structure?

**Comment by LaneSh4d0w** [comment]
https://mdstrm.com/live-stream-playlist/5a5e1c2568b1910913db5fe2.m3u8 is Canal 1. Thing is there's some geo-lock at certain hours, at certain programs. It basically unlocks itself... at news time as far as I've seen.

**Comment by LaneSh4d0w** [comment]
Teleantioquia : https://liveingesta118.cdnmedia.tv/teleantioquialive/smil:dvrlive.smil/playlist.m3u8?DVR with referer https://player.instantvideocloud.net/

**Comment by LaneSh4d0w** [comment]
> 
> 
> its anyway to get from here?
> 
> `https://canal1.com.co/senal-en-vivo`
> 
> its geo locked but i able to get a long link with idm
> 
> `https://us-b5-p-e-kj2.cdn.mdstrm.com/live-stream/5a5e1c2568b1910913db5fe2/publish/media_1000.m3u8?aid=5a1dafd63910b04010338038&uid=3hqvnlvj0I5Xz9kdihijVccFsHCQGjyH&sid=kCvR23GdwgTF0dt4fx1OLgP9fSbwEsNp&pid=4SHR4GOZyZfQ3bT6llWDtQwj50F8S1Th&ref=https%3A%2F%2Fcanal1.com.co%2F&without_cookies=false&dnt=true&es=us-b5-p-e-kj2.cdn.mdstrm.com&ote=1629578206426&ot=jFS2X5oGZWaK5jg8LlvRNQ&proto=https&pz=us`
> 
> ![08-20-2021 (164336)](https://user-images.githubusercontent.com/79808610/130291542-32275ca0-d792-4289-88fd-d84db7cd392f.jpg)
> 
> its possible get from those others? i guess its another one ssh01 but other one its different

https://tna5.bozztv.com/1uifbdsdsbsr/index.m3u8 with referer https://ssh101.com/

**Comment by LaneSh4d0w** [comment]
I'll add all the channels excepted for Canal 12 Valledupar, i'll let @dcuervog92 see if the alternate solution proposed to him works

**Comment by Toei79** [comment]
Canal Visión Dorada	https://movil.ejeserver.com/live/visiondorada.m3u8

this other colombia channel. working.

**Comment by dcuervog92** [comment]
> > `https://www.chatytvgratishd.me/canal-caracol-tv-streaming-vivo/`
> 
> https://tna5.bozztv.com/c1mdrgsergaerg/index.m3u8 with referer https://ssh101.com/
> 
> ![vlcsnap-2021-08-20-17h59m52s852](https://user-images.githubusercontent.com/30985701/130261088-28877ed6-b0d6-4ddc-a34a-b7da39c9dec6.png)

It doesn't work for me, how you did it?

> I'll add all the channels excepted for Canal 12 Valledupar, i'll let @dcuervog92 see if the alternate solution proposed to him works

Add it, and remember what I told you in the other topic, please.

**Comment by LaneSh4d0w** [comment]
> 
> 
> > > `https://www.chatytvgratishd.me/canal-caracol-tv-streaming-vivo/`
> > 
> > 
> > https://tna5.bozztv.com/c1mdrgsergaerg/index.m3u8 with referer https://ssh101.com/
> > ![vlcsnap-2021-08-20-17h59m52s852](https://user-images.githubusercontent.com/30985701/130261088-28877ed6-b0d6-4ddc-a34a-b7da39c9dec6.png)
> 
> It doesn't work for me, how you did it?
> 
> > I'll add all the channels excepted for Canal 12 Valledupar, i'll let @dcuervog92 see if the alternate solution proposed to him works
> 
> Add it, and remember what I told you in the other topic, please.

Stream might not work if you do not add the referrer. They're locked if you don't say to the server from where you came from. (the link on the right is the referrer link)

**Comment by dcuervog92** [comment]
> Stream might not work if you do not add the referrer. They're locked if you don't say to the server from where you came from. (the link on the right is the referrer link)

Same, it does not work with the referrer.

**Comment by LaneSh4d0w** [comment]
Ah yeah, it stopped working suddenly.

**Comment by LaneSh4d0w** [comment]
I've written this streamlink --http-header "Referer=https://ssh101.com/" https://tna5.bozztv.com/c1mdrgsergaerg/index.m3u8 best

And it seems to work
![vlcsnap-2021-08-21-00h09m19s438](https://user-images.githubusercontent.com/30985701/130298099-3d27d0d3-83c0-4d5c-9343-c3191c1c752d.png)

**Comment by LaneSh4d0w** [comment]
Links are on my PR.

If you wanna test : https://raw.githubusercontent.com/iptv-org/iptv/fde2aa5edcba3be52139e30f5e04fa389c4b214a/channels/co.m3u

**Comment by dcuervog92** [comment]
> I've written this streamlink --http-header "Referer=https://ssh101.com/" https://tna5.bozztv.com/c1mdrgsergaerg/index.m3u8 best
> 
> And it seems to work
> ![vlcsnap-2021-08-21-00h09m19s438](https://user-images.githubusercontent.com/30985701/130298099-3d27d0d3-83c0-4d5c-9343-c3191c1c752d.png)

Ahhh okay, you used the Streamlink program. I also used and it worked on my PC. But I tried in my TV and not, didn't worked.

**Comment by LaneSh4d0w** [comment]
> 
> 
> > I've written this streamlink --http-header "Referer=https://ssh101.com/" https://tna5.bozztv.com/c1mdrgsergaerg/index.m3u8 best
> > And it seems to work
> > ![vlcsnap-2021-08-21-00h09m19s438](https://user-images.githubusercontent.com/30985701/130298099-3d27d0d3-83c0-4d5c-9343-c3191c1c752d.png)
> 
> Ahhh okay, you used the Streamlink program. I also used and it worked on my PC. But I tried in my TV and not, didn't worked.

Weird... I believe that it's a player issue then. I know that in VLC, you can change the user agent, referrer and almost anything due to networking.

https://raw.githubusercontent.com/iptv-org/iptv/LaneSh4d0w-patch-1/channels/co.m3u

Maybe the player also understands the VLC options.

**Comment by dcuervog92** [comment]
> Weird... I believe that it's a player issue then. I know that in VLC, you can change the user agent, referrer and almost anything due to networking.
> 
> https://raw.githubusercontent.com/iptv-org/iptv/LaneSh4d0w-patch-1/channels/co.m3u
> 
> Maybe the player also understands the VLC options.

![image](https://i.ibb.co/vYcHnBk/20210820-174428.jpg)

Well, it worked on my Android TV, but not in Samsung TV. The IPTV player of the second one is a little limited. So let's not get complicated. Thank you again.

**Comment by LaneSh4d0w** [comment]
> 
> 
> > Weird... I believe that it's a player issue then. I know that in VLC, you can change the user agent, referrer and almost anything due to networking.
> > https://raw.githubusercontent.com/iptv-org/iptv/LaneSh4d0w-patch-1/channels/co.m3u
> > Maybe the player also understands the VLC options.
> 
> ![image](https://camo.githubusercontent.com/fe5c7d8554202377b73f156c85810de8a28f49c24ce76d6927e4c0654b06cd6e/68747470733a2f2f692e6962622e636f2f765963486e426b2f32303231303832302d3137343432382e6a7067)
> 
> Well, it worked on my Android TV, but not in Samsung TV. The IPTV player of the second one is a little limited. So let's not get complicated. Thank you again.

Perfect, at least it works somewhere :)

**Comment by Toei79** [comment]
it works for me.
all fine. it takes time to load but play fine.

i used on tvheadend then i play the listings on tivimate.
