### ISSUE TITLE
Boing France

### ISSUE THREAD

**Issue by heroku-miraheze** [iptv-org/iptv#4188]
**Channel Name:** Boing France
**Country:** France
**Language:** France
**Website:** boing.fr
**Stream URL (optional):** none
**Notes (optional):** none

**Comment by LaneSh4d0w** [comment]
I only have Boing Italia : 

https://live3.msf.cdn.mediaset.net/Content/dash_d0_clr_vos/live/channel(kb)/manifest.mpd / Widevine key = https://dijdiyansawte.cloudfront.net/smil?format=SMIL_M&auth=eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJtZWRpYXNldC1wcm9kL21lZGlhc2V0LXByb2QvYW5vbnltb3VzIiwiaXNzIjoiMSIsImV4cCI6MTYyOTQ2OTQxMSwiaWF0IjoxNjI5MzgzMDExMTQ5LCJqdGkiOiJjZmZjM2IzYS1iZTI1LTQ5ZWEtOWM5ZC05MGM1YzZiMDE4NmIiLCJkaWQiOiJtZWRpYXNldC1wcm9kIiwidW5tIjoiYW5vbnltb3VzIiwiY3R4Ijoie1widXNlck5hbWVcIiA6IFwibWVkaWFzZXQtcHJvZC9hbm9ueW1vdXNcIiwgXCJmYWxsYmFja1wiOiBcInRydWVcIixcInR5cGVcIjpcInVucmVnaXN0ZXJlZFwiLFwiYXR0cmlidXRlc1wiOnsgXCJhcHBOYW1lXCI6IFwid2ViXCIsIFwiaGFzaFwiOiBcIjIreU1TbGlwRjNHbFhyUXFDdUx4enYvQXlEVzh2cndUdE16YWFPMHo2TU09XCJ9fVxuIiwib2lkIjpudWxsfQ.LbNvW_ar3XhlVqhtlgFLTE_T_Q1DTXnNPGkGxrDkUXyUHSQSN2rDTadvDGa0GgFmO55fkgRcTi-nM9GyEmNMdTMssgjth7bFsU4y0NtBdPyKRst5YyEzl6hyhG9BxNoslcyAVQpKSsG0NSo7khgtEwoR52c1XJg2qYthDxI0ZEHHH6wLAliYboxfB7IDXDzkte0ug8u1cL3tEGw1c_GCMOfdnmBb5NoQkvDHoBxTyM79E-bBOszhV2QTe846Ga0h64HXn6kcl7L9J7HcJTIiIdWd1XBqaQSJ3dDvuOMp7S-3hM7GAfhMTy_dBWr-uE_JVZX0CRZPfqYBl5wnzuiKfw&formats=MPEG-DASH&assetTypes=HD,browser,widevine,geoIT%7CgeoNo:HD,browser,geoIT%7CgeoNo:HD,geoIT%7CgeoNo:SD,browser,widevine,geoIT%7CgeoNo:SD,browser,geoIT%7CgeoNo:SD,geoIT%7CgeoNo&balance=true&auto=true&tracking=true&delivery=Streaming&publicUrl=https:%2F%2Flink.theplatform.eu%2Fs%2FPR1GhC%2F_4ZqCt3e0MPJ
