### ISSUE TITLE
Portugal Channels

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#4189]
RTP AFRICA
RTP 1,2,3
TVI
SIC
CM TV
GLOBO
11 HD
SIC CARAS
SIC RADICAL
RTP Memória
BTV
SPORTING TV
ELEVEN SPORTS 1,2,3
CANAL PANDA
Eurosport 1, 2
Globo Premium HD
RTV
EURONEWS

Please ? Thanks.

**Comment by freearhey** [comment]
Please read the [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel) before posting your request next time.
