### ISSUE TITLE
Canal 12 Valledupar

### ISSUE THREAD

**Issue by dcuervog92** [iptv-org/iptv#4193]
**Channel Name:** Canal 12 Valledupar
**Country:** CO
**Language:** Spanish
**Website:** https://www.canal12valledupar.com/
**Stream URL (optional):** https://edge.teveo.com.co/live/AeAAAgAJAAFFA1IAyADIQCAAAAAAAAAAAmEfA5C1OxFRAAAA/playlist.m3u8
**Notes (optional):** Like another colombian channels, like Enlace TV and Telepetróleo (both, from Barrancabermeja, Santander). This also uses the Teveo streaming server.

**Comment by LaneSh4d0w** [comment]
Taking care of it. Worked with those Teveo links, I've seen how they were generated. Hope it's the same in this website.

**Comment by LaneSh4d0w** [comment]
Please try : https://iptv-all.lanesh4d0w.codes/colombia/canal-12-valledupar

**Comment by Dum4G** [comment]
works

**Comment by dcuervog92** [comment]
> Please try : https://iptv-all.lanesh4d0w.codes/colombia/canal-12-valledupar
> 
> Should normally work (from my local version)
> ![image](https://user-images.githubusercontent.com/30985701/130217973-7f5fb454-54d5-46a4-aa4c-8dc566e6bf4a.png)

Yeah, it works! Thank you so much.

**Comment by dcuervog92** [comment]
But I have a question. Those links works fine with Android TV, but doesn't work with OTT Player in LG webOS and Samsung Tizen TV. Is there a way they work?

**Comment by LaneSh4d0w** [comment]
Hmm... sounds like you might have the same problem as someone encountered some time ago.

Someone that had Perfect Player couldn't make it work. I needed to add a ".m3u8" as an entrypoint to make it work.

**Comment by dcuervog92** [comment]
> Hmm... sounds like you might have the same problem as someone encountered some time ago.
> 
> Someone that had Perfect Player couldn't make it work. I needed to add a ".m3u8" as an entrypoint to make it work.
> 
> EDIT : I've pushed a slight modification to the URL.
> 
> Tell me if this : https://iptv-all.lanesh4d0w.codes/colombia/canal-12-valledupar.m3u8 works.


On Android TV works fine

![image](https://i.ibb.co/GCK1tbw/20210820-123837.jpg)


But in Samsung TV, not.

![image](https://i.ibb.co/QYCH88b/20210820-123722.jpg)

**Comment by LaneSh4d0w** [comment]
Well... that's weird. Can't really control that. Not sure how that works.

**Comment by dcuervog92** [comment]
> Well... that's weird. Can't really control that. Not sure how that works. Maybe it doesn't like the redirections (which is mainly what my code does)
> 
> I suppose you can use some sort of live share or something to make it work.

Idk, I suppose that not always works with redirections. Because I have another link from other colombian channel (Telecaribe), and It works fine with OTT Player.

But it doesn't matter, at least open it on my tv. Although if you could add the .m3u8 for Enlace and Telepetróleo, I would appreciate you.

**Comment by LaneSh4d0w** [comment]
> 
> 
> > Well... that's weird. Can't really control that. Not sure how that works. Maybe it doesn't like the redirections (which is mainly what my code does)
> > I suppose you can use some sort of live share or something to make it work.
> 
> Idk, I suppose that not always works with redirections. Because I have another link from other colombian channel (Telecaribe), and It works fine with OTT Player.
> 
> But it doesn't matter, at least open it on my tv. Although if you could add the .m3u8 for Enlace and Telepetróleo, I would appreciate you.

Moved them on my side. Changing them on next PR.
