### ISSUE TITLE
TV5 Montería

### ISSUE THREAD

**Issue by dcuervog92** [iptv-org/iptv#4194]
**Channel Name:** TV5 Montería
**Country:** Colombia
**Language:** Spanish
**Website:** https://www.tv5monteria.com/
**Stream URL (optional):**
**Notes (optional):** The streaming uses OBS Studio. It's possible re-stream to hls?

**Comment by LaneSh4d0w** [comment]
Not online for the moment.

Base link -> https://obs.ninja/?view=zhWaHzM

Uses Websockets to communicate, stream ID zhWaHzM502703

**Comment by Toei79** [comment]
using tvheadend ffmeg maybe work?

**Comment by LaneSh4d0w** [comment]
> 
> 
> using tvheadend ffmeg maybe work?

Not quite sure that'll do the trick. It's working via a peer-to-peer technology, meaning it's got it's own plethora of ways to work.

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/3065

**Comment by LaneSh4d0w** [comment]
Has recently moved to teveo.com.co : http://free.fullspeed.tv/iptv-query?streaming-ip=https://teveo.com.co/player/AcAAAgAgAANmA1IAyADIUCAAAAAAAAAA.js
