### ISSUE TITLE
Janam TV 

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4197]
The link is not broken, but it's in 220p , there is a youtube stream for thee channel with 1080p.

**_Channel Name:_** Janam TV
**_Original Link (from playlist):_** https://vidcdn.vidgyor.com/janamtv-origin/liveabr/janamtv-origin/live3/playlist.m3u8
**_Replacement Link Proposed:_** https://youtu.be/_WK30gnY3_4
**_Notes (optional):_** xxx

**Comment by LaneSh4d0w** [comment]
We can definitely keep the first link as a replacement link for the stream.

For your replacement : https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UCNVkxRPqsBNejO6B9thG9Xw/live

**Comment by Niyasmkkv** [comment]
So which link can we update?

**Comment by LaneSh4d0w** [comment]
The original link can be changed to the Vidgyor link I've given, and the replacement link you're proposing can be added.
