### ISSUE TITLE
AD Chats

### ISSUE THREAD

**Issue by heroku-miraheze** [iptv-org/iptv#4199]
**Channel Name:** AD Chats
**Country:** Spain
**Language:** Spanish
**Website:** This channel does not have a website.
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
I don't know how you got that channel, but got absolutely no information about it.

**Comment by freearhey** [comment]
@heroku-miraheze Please add more info to the request (at least some link to the channel) so we can help you.

**Comment by Sphinxroot** [comment]
only place found with this mention https://apkcombo.com/spain-channel-info-tv/com.tvinfo.spain.channel/  apk dead btw

**Comment by LaneSh4d0w** [comment]
> 
> 
> only place found with this mention https://apkcombo.com/spain-channel-info-tv/com.tvinfo.spain.channel/ apk dead btw

Interesting, i'm gonna have a quick look at it.
