### ISSUE TITLE
Mazhavil Manorama SD

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4202]
**Channel Name:** Mazhavil Manorama SD
**Country:** IN
**Language:** Malayalam
**Website:** xxx
**Stream URL (optional):** http://cdn.asianetmobiletvplus.com/channels/mazhavil_wxjylngynrbeykzthdrhawtunzcuowsr/l_6568_47694648_7942.ts?nimblesessionid=24553390
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
http://cdn.asianetmobiletvplus.com/channels/mazhavil_wxjylngynrbeykzthdrhawtunzcuowsr/playlist.m3u8

Works if user-agent is stream.

**Comment by Niyasmkkv** [comment]
Working on Vlc. don't think it will work on Kodi since it's from Asainet.

**Comment by Niyasmkkv** [comment]
@LaneSh4d0w Try to get ACV, ACV Movies, Comx, JukeBox links if you can.

**Comment by heroku-miraheze** [comment]
@Niyasmkkv OK.

**Comment by LaneSh4d0w** [comment]
> 
> 
> @LaneSh4d0w Try to get ACV, ACV Movies, Comx, JukeBox links if you can.

Well, can't seem to have much luck for now concerning ACV.

**Comment by LaneSh4d0w** [comment]
http://cdn.asianetmobiletvplus.com/channels/95ef9473f8e0c8898d58b16300dbb7b5/playlist.m3u8

Asianet Medley, forbidden using browser, doesn't answer using User-Agent "stream".

**Comment by LaneSh4d0w** [comment]
@Niyasmkkv Managed to have Jukebox, that's all. Got some other ACV channels (Utsav / Utsav + / News) and that's all.

**Comment by Niyasmkkv** [comment]
I updated these links to the broken acv channels. These seems working.

**Comment by Niyasmkkv** [comment]
@LaneSh4d0w All these channels are working with Kodi. Can you find ADN Gold and Rosebowl too? The current links from the playlists are not supported on Kodi. But Jukebox and ACV Plus worked fine.

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w All these channels are working with Kodi. Can you find ADN Gold and Rosebowl too? The current links from the playlists are not supported on Kodi. But Jukebox and ACV Plus worked fine.

ADN Gold's already on the playlists.

Rosebowl... I've seen it, i'll need to check back.

**Comment by Niyasmkkv** [comment]
Rosebowl is also there in the playlist, i want to see if we can find some alternative links which supports kodi.

**Comment by LaneSh4d0w** [comment]
Took advantage of your PR to fix both ADN Gold and Rosebowl theorically by applying the same fixes than for the other channels, and made some modifications concerning some channels that weren't working anymore + some other stuff.

**Comment by Niyasmkkv** [comment]
> Took advantage of your PR to fix both ADN Gold and Rosebowl theorically by applying the same fixes than for the other channels, and made some modifications concerning some channels that weren't working anymore + some other stuff.

So hopefully with the latest playlist update, rosebowl and adn gold should play on kodi. Isn't it?

**Comment by LaneSh4d0w** [comment]
https://raw.githubusercontent.com/iptv-org/iptv/master/channels/in.m3u

Try by yourself :)

**Comment by Niyasmkkv** [comment]
It works like a charm, but I saw 2 ACV Jukebox. Is that an error or two different resolutions?

**Comment by Niyasmkkv** [comment]
This isn't fixed yet. Only Mazhavil Manorama HD is available on the list.

**Comment by LaneSh4d0w** [comment]
You've added Mazhavil Manorama in #4245. It'll be added on the daily playlists like the others at 2 am.

**Comment by Niyasmkkv** [comment]
> You've added Mazhavil Manorama in #4245. It'll be added on the daily playlists like the others at 2 am (UTC+2).

The channel isn't there in the Raw file.

**Comment by LaneSh4d0w** [comment]
![image](https://user-images.githubusercontent.com/30985701/130521576-b1d1d3b8-d3e3-4baf-94b3-d58fafa69dba.png)

**Comment by Niyasmkkv** [comment]
![image](https://user-images.githubusercontent.com/88939244/130521712-8f492fbb-4b14-457c-89fa-a5704e7e628f.png)

**Comment by Niyasmkkv** [comment]
It's in the codes. but not showing In kodi.

**Comment by LaneSh4d0w** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/88939244/130521712-8f492fbb-4b14-457c-89fa-a5704e7e628f.png)

Some Kodi services need manual refresh to get it. Which version have you got ?

**Comment by Niyasmkkv** [comment]
okay. i'm using 19.0 on windows.
