### ISSUE TITLE
Surya Music 

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4203]
**Channel Name:** Surya Music
**Country:** IN
**Language:** Malayalam
**Website:** xxx
**Stream URL (optional):** https://mhdtvworld.xyz/2d05f473-aa30-418d-b448-a227cc89b69e
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | https://indo51.gcdn.co/MALYLAM-SuryaMusic/index.m3u8
-- | --
mediaManifest | https://indo51.gcdn.co/MALYLAM-SuryaMusic/tracks-v1a1/mono.m3u8


</body>
</html>

**Comment by Niyasmkkv** [comment]
Not working.

**Comment by Niyasmkkv** [comment]
It is geo-blocked, works with vpn. not working in India. @Sphinxroot

**Comment by Niyasmkkv** [comment]
Working fine now.
