### ISSUE TITLE
Surya Movies

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4204]
**Channel Name:** Surya Movies
**Country:** IN
**Language:** Malayalam
**Website:** xxx
**Stream URL (optional):** https://mhdtvworld.xyz/5ac01aa8-4795-4b44-ad57-4aee005382bc
**Notes (optional):** xxx

**Comment by Dum4G** [comment]
https://catchup.yuppcdn.net/amazonv2/20/preview/suryamovies/master/master.m3u8
