### ISSUE TITLE
Kairali Arabia

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4212]
**Channel Name:** Kairali Arabia
**Country:** IN
**Language:** Malayalam
**Website:** xxx
**Stream URL (optional):** https://mhdtvworld.xyz/32ab2c8e-670e-450d-9410-991da8ab5d26
**Notes (optional):** xxx

**Comment by Niyasmkkv** [comment]
https://mhdtvworld.xyz/live/kairali-arabia/
https://mhdtvworld.xyz/72628b14-19fa-419a-a9c1-8fda7ed6c484

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | https://idvd.multitvsolution.com/idvo/kairaliarabia.m3u8
-- | --
mediaManifest | https://idvd.multitvsolution.com/idvo/kairaliarabia_540p/index.m3u8


</body>
</html>

**Comment by Niyasmkkv** [comment]
Logo - https://i.imgur.com/dp6BvWJ.png
