### ISSUE TITLE
Star Maa

### ISSUE THREAD

**Issue by varunfri** [iptv-org/iptv#4216]
**Channel Name:** Maa tv HD
**Country:** India
**Language:** Telugu
**Website:** https://www.hotstar.com/in/channels/star-maa
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
http://maatv-i.akamaihd.net/hls/live/569930/maatv/master_2000.m3u8 Geolocked to India

**Comment by varunfri** [comment]
It is not working Error 403

**Comment by varunfri** [comment]
http://watchindia.net:8880/live/60275/20486/933.ts 
it's playing but have more buffer

**Comment by LaneSh4d0w** [comment]
> 
> 
> http://watchindia.net:8880/live/60275/20486/933.ts
> it's playing but have more buffer

Xtream-Codes server. We're used to not take those links due to the fact that they do not last long, and if many users come in they block after a certain time.
