### ISSUE TITLE
One TV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4220]
**Channel Name:** One TV
**Country:** IN
**Language:** Malayalam
**Website:** xxx
**Stream URL (optional):*** http://137.59.86.218:1935/live/onetv/media_w439742991_11126.ts
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
http://137.59.86.218:1935/live/onetv/playlist.m3u8
