### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by dcuervog92** [iptv-org/iptv#4233]
**Channel Name:** Canal Zoom
**Channel ID:** Zoom.co
**Country:** Colombia
**Language:** Spanish
**Website:** https://www.zoomcanal.com.co
**Stream URL (optional):** https://15306896-8b0c-4319-a479-c29bef5aecbd.iaia.stream/15306896-8b0c-4319-a479-c29bef5aecbd/bcf7b3b2c575/playlist.m3u8
**Notes (optional):** Blocked for play on external player, also with referrer.

**Comment by Sphinxroot** [comment]
In Kodi it work

#EXTINF:1 ,masterManifest	
https://15306896-8b0c-4319-a479-c29bef5aecbd.iaia.stream/15306896-8b0c-4319-a479-c29bef5aecbd/bcf7b3b2c575/playlist.m3u8|Referer=https://playerembed.iaia.stream/
#EXTINF:1 ,mediaManifest	
https://15306896-8b0c-4319-a479-c29bef5aecbd.iaia.stream/15306896-8b0c-4319-a479-c29bef5aecbd/bcf7b3b2c575/chunklist.m3u8|Referer=https://playerembed.iaia.stream/

but unsure if this link is token

#EXTINF:-1  tvg-id="" tvg-name="" tvg-country="" tvg-language="" tvg-logo="https://i.imgur.com/azaIh2W.png" group-title="",Canal Zoom
#EXTVLCOPT:http-referrer=https://playerembed.iaia.stream/
https://15306896-8b0c-4319-a479-c29bef5aecbd.iaia.stream/15306896-8b0c-4319-a479-c29bef5aecbd/bcf7b3b2c575/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
> 
> 
> In Kodi it work
> 
> #EXTINF:1 ,masterManifest
> [https://15306896-8b0c-4319-a479-c29bef5aecbd.iaia.stream/15306896-8b0c-4319-a479-c29bef5aecbd/bcf7b3b2c575/playlist.m3u8|Referer=https://playerembed.iaia.stream/](https://15306896-8b0c-4319-a479-c29bef5aecbd.iaia.stream/15306896-8b0c-4319-a479-c29bef5aecbd/bcf7b3b2c575/playlist.m3u8%7CReferer=https://playerembed.iaia.stream/)
> #EXTINF:1 ,mediaManifest
> [https://15306896-8b0c-4319-a479-c29bef5aecbd.iaia.stream/15306896-8b0c-4319-a479-c29bef5aecbd/bcf7b3b2c575/chunklist.m3u8|Referer=https://playerembed.iaia.stream/](https://15306896-8b0c-4319-a479-c29bef5aecbd.iaia.stream/15306896-8b0c-4319-a479-c29bef5aecbd/bcf7b3b2c575/chunklist.m3u8%7CReferer=https://playerembed.iaia.stream/)
> 
> but unsure if this link is token
> 
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-country="" tvg-language="" tvg-logo="https://i.imgur.com/azaIh2W.png" group-title="",Canal Zoom
> #EXTVLCOPT:http-referrer=https://playerembed.iaia.stream/
> https://15306896-8b0c-4319-a479-c29bef5aecbd.iaia.stream/15306896-8b0c-4319-a479-c29bef5aecbd/bcf7b3b2c575/playlist.m3u8

Custom instantvideocloud / cdnvideo stream. Might manage something.

**Comment by LaneSh4d0w** [comment]
Doesn't seem to change, however if you're unsure, I can manage to add it on my server to always get a fresh stream.

https://15306896-8b0c-4319-a479-c29bef5aecbd.iaia.stream/15306896-8b0c-4319-a479-c29bef5aecbd/bcf7b3b2c575/playlist.m3u8 Referer = https://playerembed.iaia.stream/

**Comment by Sphinxroot** [comment]
this morning a little change
https://15306896-8b0c-4319-a479-c29bef5aecbd.iaia.stream/15306896-8b0c-4319-a479-c29bef5aecbd/bcf7b3b2c5751/playlist.m3u8

but chunk not
https://15306896-8b0c-4319-a479-c29bef5aecbd.iaia.stream/15306896-8b0c-4319-a479-c29bef5aecbd/bcf7b3b2c575/chunklist.m3u8

**Comment by LaneSh4d0w** [comment]
Yeah, better grab it with some script, and add referer on top of it. Let me see.

**Comment by LaneSh4d0w** [comment]
Try https://iptv-all.lanesh4d0w.codes/colombia/zoom with referer https://playerembed.iaia.stream/

**Comment by LaneSh4d0w** [comment]
Hmm... there's a weird issue that I can't put my hand on.
It works locally, but it doesn't work when being put on Vercel. However, made it work when... i logged the entries. Very weird.

**Comment by Dum4G** [comment]
500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED

**Comment by LaneSh4d0w** [comment]
Again ? Dang it, guess it doesn't like it at all !

**Comment by LaneSh4d0w** [comment]
Ah I know why : 
![image](https://user-images.githubusercontent.com/30985701/130604273-70b1ab16-d9d2-43dc-8147-92acb33cb02f.png)

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/3065

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/13d2f470b7e5b647c0d24d4b6897c651d4b52971/streams/co.m3u#L136-L137
