### ISSUE TITLE
Studio Yuva

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4234]
**Channel Name:** Studio One Yuva
**Country:** IN
**Language:** Telugu
**Website:** xxx
**Stream URL (optional):** https://youtu.be/zV2ndzKjGT4
**Notes (optional):** xxx

**Comment by fotvnetwork** [comment]
https://www.youtube.com/channel/UCqR2tCs8ufgAjRd6rn4a2wg/live

**Comment by LaneSh4d0w** [comment]
https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UCqR2tCs8ufgAjRd6rn4a2wg/live

thanks @fotvnetwork
