### ISSUE TITLE
Studio One Plus

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4235]
**Channel Name:** Studio One Plus
**Country:** IN
**Language:** Telugu
**Website:** xxx
**Stream URL (optional):** https://youtu.be/4BcPdYGwmIo
**Notes (optional):** xxx

**Comment by fotvnetwork** [comment]
https://www.youtube.com/channel/UCEoaVUxpFlmCxwRBy9yhb1Q/live

**Comment by LaneSh4d0w** [comment]
https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UCEoaVUxpFlmCxwRBy9yhb1Q/live
