### ISSUE TITLE
Animax Asia (english subs)

### ISSUE THREAD

**Issue by argooseargus** [iptv-org/iptv#4239]
**Channel Name:** Animax
**Country:** Not one definitive country, but Southeast Asia  
**Language:** Japanese (with English subs)
**Website:** https://www.animax-asia.com/
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/1938
