### ISSUE TITLE
http://maatv-i.akamaihd.net/hls/live/569930/maatv/master_2000.m3u8 Geolocked to India

### ISSUE THREAD

**Issue by varunfri** [iptv-org/iptv#4243]
http://maatv-i.akamaihd.net/hls/live/569930/maatv/master_2000.m3u8 Geolocked to India

_Originally posted by @LaneSh4d0w in https://github.com/iptv-org/iptv/issues/4216#issuecomment-903096087_

This given m3u8 is not geo blocked it is error 403 forbiden, bcz it is taken by php server 
we want ""GET,POST,OPTIONS"" are required and want to configure in php 
Plz get another link

**Comment by freearhey** [comment]
Duplicate #4216
