### ISSUE TITLE
KDOC-TV

### ISSUE THREAD

**Issue by creeps125** [iptv-org/iptv#4255]
**Channel Name:** KDOC-TV
**Country:** US (Los Angeles, CA)
**Language:** English
**Website:** kdoc.tv

**Comment by jkemp814** [comment]
[Not 24/7] (will follow up once it's live to get the manafest URL)

http://kdoc.tv/live-stream/

http://hwapps.streamingmediahosting.com/p/13863/html5/html5lib/v2.66/load.php?debug=false&lang=en&modules=Hlsjs%2CacCheck%2CacPreview%2Cbase64_decode%2Cbase64_encode%2Cclass%2CcontrolBarContainer%2CcurrentTimeLabel%2CdurationLabel%2CfullScreenBtn%2Cid3Tag%2Ckdark%2CkeyboardShortcuts%2CkgitGuard%2ClargePlayBtn%2CliveStream%2Clogo%2CmatchMedia%2CmoderationPlugin%2CmorePlugins%2CnativeBridge%2CplayPauseBtn%2Cpolyfill_Array_filter%2CqualitySettings%2CreportError%2Cscreenfull%2Cscrubber%2CsideBarContainer%2CsourceSelector%2CstatisticsPlugin%2Ctheme%2CtopBarContainer%2CunMuteOverlayButton%2Cutf8_encode%2CvolumeControl%7Cjquery.client%2Ccolor%2Ccookie%2Cdebouncedresize%2ChoverIntent%2CmessageBox%2CmwEmbedUtil%2CmwExtension%2CnaturalSize%7Cjquery.ui.core%2Cmouse%2Cposition%2Cslider%2Ctooltip%2CtouchPunch%2Cwidget%7Cmediawiki.Uri%2CUtilitiesTime%2CUtilitiesUrl%2Cclient%2CjqueryMsg%2Ckmenu%2Clanguage%2Cutil%7Cmediawiki.util.tmpl%7Cmw.EmbedPlayer%2CEmbedPlayerImageOverlay%2CEmbedPlayerKplayer%2CEmbedPlayerNative%2CEmbedPlayerNativeComponent%2CEmbedTypes%2CKAnalytics%2CKBaseButton%2CKBaseComponent%2CKBasePlugin%2CKBaseScreen%2CKBaseSmartContainer%2CKCuePoints%2CKDPMapping%2CKEntryLoader%2CKWidgetSupport%2CKalturaIframePlayerSetup%2CMediaElement%2CMediaPlayer%2CMediaPlayers%2CMediaSource%2CPlayerElement%2CPlayerElementFlash%2CPlayerElementHTML%2CPluginManager%7Cmw.MwEmbedSupport.style&pid=13863&pskwidgetpath=..%2Fkwidget-ps%2F&skin=no-theme&version=20201010T071954Z&*&protocol=http&cdn_cache=hw

**Comment by MapGuy11** [comment]
I have a 24/7 stream not to worry. Just on vaca.

**Comment by MapGuy11** [comment]
@jkemp814 @creeps125 Make pull request with this url. https://cdn87.theus6tv.tk/locals/SoCal/kdoc-dt1.m3u8

Please test

**Comment by Dum4G** [comment]
works
