### ISSUE TITLE
myTV KCOP Los Angeles

### ISSUE THREAD

**Issue by creeps125** [iptv-org/iptv#4256]
**Channel Name:** KCOP 13
**Country:** US (Los Angeles, CA)
**Language:** English
**Website:** foxla.com/my13

**Comment by jkemp814** [comment]
I know this is tokenized. Just posting some info on the link.

https://dcs-live.apis.anvato.net/server/play/vAQozBaC9R1Luz7b/manifest.m3u8?encp=CHrjJsASRryAZ9JkB_fvlg:6ReabWqlVA4FugUpCaJ3SS8na11kBk3i_PJsfiJRAI7QWQN54puSMvLegPjd6mw72S8fov45B87cvJkd6Aly7mVSw31J9OKA6667VDGzuNGtxjPPFVObBKgWZ64L3-mX88rxQiFkYuPyApQ-yUdsNCl8UVi4fCcncR2GsmTUKMGrrqqhaDfwncXkI0qTPNpVPMZEZvvLaDRhQf2rD_vFvce9n4HI92Nl6q0TT4OnKM0nJlM0BHOEY45v4ZzNhcxclTeQxTJBOJtLJsUFvYnq9DEWel-6eQh4dqPvSjNLhh1-Z4jRbtUnNhtmzh2_a5omLIpann4Okxg19rKbU3YgeF8sN6bdOUqV8IXpE-iWZZxeO2qD_ZaAhxBz-bZJgSnty6wpYfkCXRMK91I16YhRQsafQ2y_CDkKl0RBz1iDDXRRy1helglgzjkAqbIBN1AmFpZeNebXY1Q8o4f_QBQ5CGkVz2HVSZDqybzFLiHnlq1skKeMM-YEic_zlBo97_5YKk8D1_YB0iEf4DeGTFmR11IK45A_LmHjzDw0MBEBgYkbDXafSm2qKXBFFDE3tbqYcGt5A8220RYAg-AaCDBv8OFZ98yrWkEGFq4bAPzerXezXjIDB94Cbihd4s_BTk-QWPAKFmSjKDC_mw68gBeaQFu2XkKJDIJvBjv87aR_j29fdAHfpdHnLvc7XgozF-FtPjBOayK3SSynY7gSM7qXG9V1skYeLb4WuVrRQbFbQboeTmo4qDNZFzMF8Z7olEKZeWRWDgBSOWLWgJV7G1f4W4UVa4hYz0udmkQrrCKkSJYo_ghZy5YvfenGgkUdnDA6&anvtrid=wb768a311a72c209812461cf1ea99e28&anvauth=tb=0~te=1629812483~sgn=ee1ccb312458c82eaec0780760d2aa3f08bd7a47349444a68dd81bcc17468a7d&t=1629812393&_vpng=0

**Comment by MapGuy11** [comment]
I think I have 24/7 stream just on vaca.

**Comment by MapGuy11** [comment]
@jkemp814 @creeps125 Make pull request with this url. 
https://cdn87.theus6tv.tk/locals/SoCal/kcop-dt1.m3u8

Please test

**Comment by Dum4G** [comment]
Works
