### ISSUE TITLE
Fadak TV

### ISSUE THREAD

**Issue by Mennaruuk** [iptv-org/iptv#4262]
**Channel Name:** Fadak TV
**Country:** UK
**Language:** Arabic
**Website:** https://fadak.tv/
**Stream URL (optional):** https://youtu.be/tBAxOegumAs
**Notes (optional):** I couldn’t find any HLS links. They seem to primarily focus on YouTube.

**Comment by Sphinxroot** [comment]
https://www.youtube.com/channel/UCBgM-sKkB4ySrdiCsk0ikUA/live
