### ISSUE TITLE
Wesal TV

### ISSUE THREAD

**Issue by Mennaruuk** [iptv-org/iptv#4263]
**Channel Name:** Wesal TV
**Country:** KSA
**Language:** Arabic
**Website:** Best I could find is [Twitter](https://mobile.twitter.com/wesal_tv)
**Stream URL (optional):** 
**Notes (optional):**

**Comment by Sphinxroot** [comment]
http://tvwesal.com/livestream/

http://live.noorlive.com:1935/wesal/wesal1/playlist.m3u8

other site that have
http://live.noorlive.com:1935/wesal/wesal1/chunklist_w423364619.m3u8

but no MediaManifest pull out maybe not 24/7 if you look at  http://tvwesal.com/schedule/
