### ISSUE TITLE
Gemini TV

### ISSUE THREAD

**Issue by varunfri** [iptv-org/iptv#4275]
**Channel Name: Gemini Tv
**Channel ID:** GeminiTV.in
**Country:** India
**Language:** telugu
**Website:**https://sunnetwork.in/tv-channel-details.aspx?Channelid=4&channelname=GEMINI%20TV&LanguageID=2&Type=2
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Dum4G** [comment]
Probably has a secret link that looks like this

https://catchup.yuppcdn.net/amazonv2/20/preview/????/master/master.m3u8
https://www.yupptv.com/channels/gemini-tv/live

**Comment by freearhey** [comment]
Closed in favor of #4275
