### ISSUE TITLE
Azam Sports 1

### ISSUE THREAD

**Issue by tzniceguy** [iptv-org/iptv#4278]
**_Channel Name:_** AzamSports Hd
**_Broken Link (from playlist):_** http://1446000130.rsc.cdn77.org:80/1446000130/index.m3u8
*_Possible Replacement (optional):_** xxx
**_Notes (optional):_** Streaming Link appears to be changed

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/2730
