### ISSUE TITLE
Numidia TV

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#4296]
**Channel Name:** Numidia TV
**Country:** Algeria
**Language:** Arabic
**Links:**
https://www.facebook.com/numidiachannel
https://www.youtube.com/channel/UCZvLExKiOeUjbwAocZ7UVxg
https://www.instagram.com/numidiachannel/

https://github.com/iptv-org/iptv/issues/1461 (original request)

**Comment by Dum4G** [comment]
Hta.dz is tokenized now, we don't have all of those channels again. And Numidia is a satellite channel that I wasn't able to find since I started to contribute
