### ISSUE TITLE
Hungama TV

### ISSUE THREAD

**Issue by nikhil96widhani** [iptv-org/iptv#4298]
**Channel Name:** Hungama Tv
**Country:** India
**Language:** Hindi
**Website:** https://en.m.wikipedia.org/wiki/Hungama_TV
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Dum4G** [comment]
http://103.153.39.34:8000/play/a04l/index.m3u8

**Comment by LaneSh4d0w** [comment]
Was about to say it could have been https://live.hungama.com/linear/hungama-tv/playlist.m3u8 but it's a 403. Channel apparently belongs to Disney India, won't be easy to get apart from the others.

**Comment by LaneSh4d0w** [comment]
> 
> 
> http://103.153.39.34:8000/play/a04l/index.m3u8

and this is how in the space of a minute I just got brained lol

**Comment by nikhil96widhani** [comment]
Hi thanks for the quick update but the link doesn’t work. It streams for few seconds then buffers indefinitely or repeatedly so it’s unplayable.

please help with a woking link. Geoip blocked to india or not doesn't matter i can use vpn

**Comment by Dum4G** [comment]
What is your player? I'm quite sure that's the only reliable link we can find.

**Comment by nikhil96widhani** [comment]
> I'm adding an additional source that suddenly is working for me. That's everything I can help you with

Where did you add the source? Can you paste in the comments please and thank you

**Comment by Dum4G** [comment]
http://70.39.83.58:8278/hungamahindikdin/playlist.m3u8
