### ISSUE TITLE
Sony Six

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#4310]
**_Channel Name:_** Sony Six
**_Broken Link (from playlist):_** http://103.81.104.118/hls/stream10.m3u8
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** xxx

https://github.com/iptv-org/iptv/issues/4142 (original issue)

**Comment by Dum4G** [comment]
https://github.com/robiulhossain2/ARAFAT/blob/356d7c0c6f2a5b1ef9fa389bf2f5bfd5ca7b7d2d/ARAFAT.m3u

This is huge

**Comment by Niyasmkkv** [comment]
> https://github.com/robiulhossain2/ARAFAT/blob/356d7c0c6f2a5b1ef9fa389bf2f5bfd5ca7b7d2d/ARAFAT.m3u
> 
> This is huge @Niyasmkkv

Seems like a Bangladeshi list with some Indian channels. Will look in to it.

**Comment by Niyasmkkv** [comment]
It is not available now. Any other Indian list? @Dum4G

**Comment by Dum4G** [comment]
> It is not available now. Any other Indian list? @Dum4G

Do you use Telegram or Discord?

**Comment by Niyasmkkv** [comment]
> > It is not available now. Any other Indian list? @Dum4G
> 
> Do you use Telegram or Discord? @Niyasmkkv

Telegram

**Comment by Dum4G** [comment]
What's your nickname? @Niyasmkkv

**Comment by Niyasmkkv** [comment]
> What's your nickname? @Niyasmkkv

 @Dum4G syani123

**Comment by Niyasmkkv** [comment]
Let me know when you ping me there.

**Comment by Dum4G** [comment]
> Let me know when you ping me there.

sone

**Comment by rupesh25358a** [comment]
http://137.59.155.77:8088/hls/05sonysix.m3u8
this link works
