### ISSUE TITLE
Sony Sab

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#4311]
**_Channel Name:_** Sony Sab
**_Broken Link (from playlist):_** http://208.115.215.42/Sony_Sab_HD/playlist.m3u8
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** xxx

https://github.com/iptv-org/iptv/issues/4142 (original issue)

**Comment by Dum4G** [comment]
http://221.120.204.4/SONY-SAB-LOCKLE/index.m3u8

**Comment by nikhil96widhani** [comment]
> http://221.120.204.4/SONY-SAB-LOCKLE/index.m3u8

Do you have a non hd (sab tv)  link for this ? Both the channels are different and broadcast different shows. Thank you
