### ISSUE TITLE
ZooMoo Asia

### ISSUE THREAD

**Issue by DetectiveKamal** [iptv-org/iptv#4314]
**Channel Name:** Zoomoo Asia
**Channel ID:** ZooMooAsia.nz
**Country:** Asia
**Language:** English
**Website:** Zoomoo.com
**Stream URL (optional): https://m.vidio.com/live/6533-zoomoo
**Notes (optional):** There is Two audio tracks but the stream on vidio only has english

**Comment by LaneSh4d0w** [comment]
Need a subscription to have this program from Vidio.
