### ISSUE TITLE
Dabl

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#4323]
**Channel Name:** Dabl
**Country:** USA
**Language:** English
**Website:** https://www.dabl.com/
**Stream URL (optional):** 
**Notes (optional):** Dabl is one of OTA Sub Channel. also Dabl have Officical Stream(https://www.dabl.com/schedule)
 but it Will Expire only One Day.

**Comment by LaneSh4d0w** [comment]
I'll need to check using a proxy, 403 forbidden if schedule is seen from another country than the USA.

**Comment by Dum4G** [comment]
https://pluto.tv/en/live-tv/dabl

**Comment by Central302** [comment]
Direct Stream Link(dai.google)  is working. thanks!
