### ISSUE TITLE
Al Jazeera Arabic (480p)

### ISSUE THREAD

**Issue by Mennaruuk** [iptv-org/iptv#4333]
**_Channel Name:_** Al Jazeera Arabic (480p)
**_Broken Link (from playlist):_** http://ott-cdn.ucom.am/s69/index.m3u8
**_Possible Replacement (optional):_**
**_Notes (optional):_** I searched through alternative streams online, and many were either high quality or they're adaptive, none have exactly 480p.

**Comment by Dum4G** [comment]
#EXT-X-STREAM-INF:BANDWIDTH=6324320,RESOLUTION=1920x1080,CODECS="avc1.640028,mp4a.40.2"
https://live-hls-web-aja.getaj.net/AJA/01.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=6324320,RESOLUTION=1920x1080,CODECS="avc1.640028,mp4a.40.2"
https://live-hls-web-aja.getaj.net/AJA-b/01.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3120800,RESOLUTION=1280x720,CODECS="avc1.64001f,mp4a.40.2"
https://live-hls-web-aja.getaj.net/AJA/02.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3120800,RESOLUTION=1280x720,CODECS="avc1.64001f,mp4a.40.2"
https://live-hls-web-aja.getaj.net/AJA-b/02.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1831872,RESOLUTION=960x540,CODECS="avc1.64001f,mp4a.40.2"
https://live-hls-web-aja.getaj.net/AJA/03.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1831872,RESOLUTION=960x540,CODECS="avc1.64001f,mp4a.40.2"
https://live-hls-web-aja.getaj.net/AJA-b/03.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1013696,RESOLUTION=746x420,CODECS="avc1.64001e,mp4a.40.2"
https://live-hls-web-aja.getaj.net/AJA/04.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1013696,RESOLUTION=746x420,CODECS="avc1.64001e,mp4a.40.2"
https://live-hls-web-aja.getaj.net/AJA-b/04.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=813664,RESOLUTION=640x360,CODECS="avc1.64001e,mp4a.40.2"
https://live-hls-web-aja.getaj.net/AJA/05.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=813664,RESOLUTION=640x360,CODECS="avc1.64001e,mp4a.40.2"
https://live-hls-web-aja.getaj.net/AJA-b/05.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=428640,RESOLUTION=426x240,CODECS="avc1.640015,mp4a.40.2"
https://live-hls-web-aja.getaj.net/AJA/06.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=428640,RESOLUTION=426x240,CODECS="avc1.640015,mp4a.40.2"
https://live-hls-web-aja.getaj.net/AJA-b/06.m3u8

Here's any resolution you might want from our adaptive source
