### ISSUE TITLE
KLCS-DT2 

### ISSUE THREAD

**Issue by creeps125** [iptv-org/iptv#4335]
**Channel Name:** KLCS-DT2 PBS Kids
**Country:** USA (Los Angeles, CA)
**Language:** English
**Website:** klcs.org

**Comment by jkemp814** [comment]
https://watch.klcs.org/livestream/

https://klcsdt.lls.cdn.pbs.org/klcsdt/c39fde04-f0c0-4f41-b797-a2c14938238b/primary.m3u8

**Comment by jkemp814** [comment]
That link I posted is for the local PBS channel. Haven't been able to find a live stream of the PBS Kids channel in L.A. Only videos and program schedule. Main channel is [Geo blocked]

**Comment by LaneSh4d0w** [comment]
Create TV from the same KLCS group : https://d1mxoeplf1ak5a.cloudfront.net/index.m3u8 (geo-blocked)

**Comment by Dum4G** [comment]
I found some alternate link for PBS Kids, dunno where it is from, but content looks the same as in Arizona stream
https://livestream.pbskids.org/out/v1/1e3d77b418ad4a819b3f4c80ac0373b5/est.m3u8

**Comment by jkemp814** [comment]
I notice that link has 'est' in the URL. EST = Eastern Standard TIme. Even though the programming is the same there could be a time offset with the EPG, as much as three hours difference between L.A. and New York certain times of the year.

**Comment by what-a** [comment]
PBS Kids has 5 different streams to accommodate the 6 time zones in the US.
All are now available on IPTV-org.
![image](https://user-images.githubusercontent.com/88639906/150076140-dec1ff62-bac1-4420-8ebf-060fbb2d4bde.png)
