### ISSUE TITLE
ABC 5 Minneapolis MN (KSTP)

### ISSUE THREAD

**Issue by TannerBrunscheon** [iptv-org/iptv#4348]
**Channel Name:** ABC 5 Minneapolis MN (KSTP)
**Country:** USA
**Language:** English
**Website:** https://kstp.com/
**Stream URL (optional):** https://kstp.com/livevideo/
**Notes (optional):** Only remaining Minneapolis network of the big 4

**Comment by trancer1994** [comment]
https://dcs-live.apis.anvato.net/server/play/zA65M4DuXVnxibP0/manifest.m3u8?encp=SicurEeEAmioRswOppyuOA:OJ_rgKSkGcZ-N-LWPshTq9AmXLaTwnLEQdj-AI9W5I10ObDf4jJV9PLBXWzgKPkDKDPtsDM3ndRcHMV5At0Yl3KQ8QMTsRtOXgyiid-WnmMUsr5k0DDNDTMRLdoFpRStLgjMLolj_aVPAaTe_SyId7jd7unJi2OqlEh64fMyix_lwLqpXILZ2ndPRgWf0xFuZsQn_YaiV5ian1BxB9c3ejvCXD-EVG4aaV4Iwl6Ec_GiA4ub3e8vZTsRj_bPg761GZijzUERSnUik1KUeklrAKn0Lhg5raZU3_Z220oZZEhVtwvla1g82cZ-9HQRhvVpnA0nSsScMvc1n3ZohyVz9Khhq8W-emBvzrbpV3e3rKC3GLDldOZi8iGFMSCEVEkj38l7-GvwhFwDexxn0K5FuDr59RdGWe8giOk4iZ503prg7t3M1FfjushcggM70arQ3xFExCYaMo6WRtTj24NGKBVgCr8BhMjmxkbkGgDzRa2yl2ICLoWiJiB2ic_yXUI4_AvWbSZ3U-mG0afQK5iHBSiybCpDnm0r1alOhwUm-0NMzbykCrgV7Hq5HBbMSMJqAbrVpRe1aG4bIXg40nXvQq_t3-_VP2_G9fzSAhbFlVw6XqQC2ZzQ5BMP7QhXBsEXCgt6eyEKL0YWW3rgfumH9JmIj-eioZaheTL-TtPQaJrMjO71NN7vbKNcE0NU0ER8oWMPhDb5_-BUCni3psuSb3L2Vs7c8pc_CgBjeJ3sQns&anvtrid=wb768a31653de8e61b3a7114b7b099a6&anvauth=tb=0~te=1630521201~sgn=6050a7f7791c5f933a2095cddb841195c4091fba06e644b77912f53899a20310&t=1630521111&_vpng=0 I think it's tokened though. Or if you want it to use a vpn, https://dcs-live.apis.anvato.net/server/play/zA65M4DuXVnxibP0/manifest.m3u8?encp=SicurEeEAmioRswOppyuOA:OJ_rgKSkGcZ-N-LWPshTq9AmXLaTwnLEQdj-AI9W5I10ObDf4jJV9PLBXWzgKPkDKDPtsDM3ndRcHMV5At0Yl3KQ8QMTsRtOXgyiid-WnmMUsr5k0DDNDTMRLdoFpRStLgjMLolj_aVPAaTe_SyId7jd7unJi2OqlEh64fMyix_lwLqpXILZ2ndPRgWf0xFuZsQn_YaiV5ian1BxB9c3ejvCXD-EVG4aaV4Iwl6Ec_GiA4ub3e8vZTsRj_bPg761GZijzUERSnUik1KUeklrAKn0Lhg5raZU3_Z220oZZEhVtwvla1g82cZ-9HQRhvVpnA0nSsScMvc1n3ZohyVz9Khhq8W-emBvzrbpV3e3rKC3GLDldOZi8iGFMSCEVEkj38l7-GvwhFwDexxn0K5FuDr59RdGWe8giOk4iZ503prg7t3M1FfjushcggM70arQ3xFExCYaMo6WRtTj24NGKBVgCr8BhMjmxkbkGgDzRa2yl2ICLoWiJiB2ic_yXUI4_AvWbSZ3U-mG0afQK5iHBSiybCpDnm0r1alOhwUm-0NMzbykCrgV7Hq5HBbMSMJqAbrVpRe1aG4bIXg40nXvQq_t3-_VP2_G9fzSAhbFlVw6XqQC2ZzQ5BMP7QhXBsEXCgt6eyEKL0YWW3rgfumH9JmIj-eioZaheTL-TtPQaJrMjO71NN7vbKNcE0NU0ER8oWMPhDb5_-BUCni3psuSb3L2Vs7c8pc_CgBjeJ3sQns&anvtrid=wb768a31653de8e61b3a7114b7b099a6&anvauth=tb=0~te=1630521201~sgn=6050a7f7791c5f933a2095cddb841195c4091fba06e644b77912f53899a20310&t=1630521111&_vpng=1

**Comment by LaneSh4d0w** [comment]
https://tkx.apis.anvato.net/rest/v2/mcp/video/adstwR1j9Z7P8Ynm?anvack=rz93EA03Zenj1h23jMIYZC6DVMVQ8DMe&anvtrid=wb768a31e13aec031622ac1d86b622e0&rtyp=fp&X-Anvato-Adst-Auth=I7qsP9JrLijWpN4gVLQ1oD4PeOSiFhwbzOlZOQgn8WwMjw2cMA%2FSmb%2Bj1D2%2BQSAUs%2BVs%2F%2Bmu7U8sprQxrxOOPw%3D%3D

using this you get the tokened link that's right here : 
![image](https://user-images.githubusercontent.com/30985701/131974013-a9e90dd9-ba41-4446-8ed8-b36ee4c763e9.png)

**Comment by LaneSh4d0w** [comment]
and there you go : https://iptv-all.lanesh4d0w.codes/united-states/kstp-tv
