### ISSUE TITLE
Cartoon Network Nederland

### ISSUE THREAD

**Issue by DetectiveKamal** [iptv-org/iptv#4351]
**Channel Name:** Cartoon Network Netherlands
**Channel ID:** CartoonNetworkNetherlands.nl
**Country:** Netherlands
**Language:** Dutch
**Website:** cartoonnetwork.nl

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/3145

**Comment by freearhey** [comment]
Closed in favor of #12270
