### ISSUE TITLE
TV Tokyo

### ISSUE THREAD

**Issue by Username778** [iptv-org/iptv#4358]
**Channel Name: Tv Tokyo
**Country: Japan
**Language: Japan
**Website: 
**Stream URL (optional):
**Notes (optional):

**Comment by Dum4G** [comment]
We have BS TV Tokyo in the playlist

**Comment by LaneSh4d0w** [comment]
hmm... isn't that like the 4th or 5th time someone asks for a channel that's already on the Japanese Channel Requests issue ?

Closed in favor of issue #1938
