### ISSUE TITLE
CCTN 47

### ISSUE THREAD

**Issue by fotvnetwork** [iptv-org/iptv#4362]
**Channel Name:** CCTN
**Country:** Philippines
**Language:** Filipino/Cebuano
**Website:** http://cctn47.com/
**Stream URL (optional):** http://122.55.252.134:8443/live/bba5b536faeacb9b56a3239f1ee8e3b3/1.m3u8
**Notes (optional):** Catholic TV station from Cebu, Philippines

**Comment by jkemp814** [comment]
Black screen, can hear clear audio.

**Comment by LaneSh4d0w** [comment]
I'm trying to have the channel from its website, they do not seem to have kept their video.js files at the correct place x)

I have something that's named "./src/z.m3u8" but that can't be it, sounds like a placeholder.

**Comment by fotvnetwork** [comment]
I grabbed the link from its mobile app.

**Comment by Dum4G** [comment]
![image](https://user-images.githubusercontent.com/5430116/132104331-49d1d14f-c7e4-453d-9c08-ace1386aba90.png)

**Comment by LaneSh4d0w** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/5430116/132104331-49d1d14f-c7e4-453d-9c08-ace1386aba90.png)

Ah yes, image is on VLC, but not on the browser ext.

**Comment by Sphinxroot** [comment]
work in kodi 1080p

**Comment by MapGuy11** [comment]
![image](https://user-images.githubusercontent.com/43685307/132673570-ea88b12c-6e1c-4069-ae81-d0aa9628d536.png)

The link works the reason it's black is because it's a HEVC stream

**Comment by MapGuy11** [comment]
Here is the link from the Website: http://122.55.252.134:8443/live/bba5b536faeacb9b56a3239f1ee8e3b3/1.m3u8

**Comment by LaneSh4d0w** [comment]
Interesting how some channels prefer using the HEVC codec (it's indeed better because it compresses the video a lot, but not all of them supports it)
