### ISSUE TITLE
CLTV 36

### ISSUE THREAD

**Issue by fotvnetwork** [iptv-org/iptv#4363]
**Channel Name:** Central Luzon Television
**Country:** Philippines
**Language:** Filipino/Kapampangan
**Website:** http://cltv36.tv/
**Stream URL (optional):** https://tna5.bozztv.com/cltv36/index.m3u8
**Notes (optional):** TV station based in Pampanga, Philippines. The link is from ssh101, and it can use a referrer.

**Comment by LaneSh4d0w** [comment]
nice one !

referrer is https://ssh101.com/
