### ISSUE TITLE
TeleRadyo

### ISSUE THREAD

**Issue by fotvnetwork** [iptv-org/iptv#4364]
**Channel Name:** TeleRadyo
**Country:** Philippines
**Language:** Filipino
**Website:** https://tfc.tv/live/details/41725/teleradyo
**Stream URL (optional):** xx
**Notes (optional):** News channel

**Comment by LaneSh4d0w** [comment]
https://abscbn-ono.akamaized.net/midroll/amagi_hls_data_abscbnAAA-abscbn-teleradyo-oando/CDN/playlist.m3u8

**Comment by jkemp814** [comment]
Works on this end.

**Comment by jkemp814** [comment]
Is this considered ABS CBN TeleRadyo?

logo: https://i.imgur.com/dzjp0Lv.png

**Comment by fotvnetwork** [comment]
> Is this considered ABS CBN TeleRadyo?
> 
> logo: https://i.imgur.com/dzjp0Lv.png
> 
> Edit: I can see abs-cbn in the url, does DZMM apply to this channel, area?

It was known as DZMM TeleRadyo. It was later rebranded as simply TeleRadyo after its AM counterpart signed off last year because ABS-CBN's legislative franchise lapsed.

**Comment by jkemp814** [comment]
Okay, that explains why all the logos have all three names in them.

Here is one with just TeleRadyo: https://i.imgur.com/yxKb7yF.jpg?1

**Comment by jkemp814** [comment]
So this channel should be what language and county?

**Comment by fotvnetwork** [comment]
> This channel should be what language and county? PH, I hear English in the MyPillow commercial, lol
> 
> I added the channel to the us.m3u playlist for now

Is it the global feed? Here in Manila, they use the domestic feed and has local ads

**Comment by LaneSh4d0w** [comment]
They might simply stream the global streams for foreigners and the local stream for the others.

TFC requires either a login or a subscription to get access to other stuff.
