### ISSUE TITLE
Fix: Fuji TV

### ISSUE THREAD

**Issue by TheBlueToad** [iptv-org/iptv#4366]
**_Channel Name:_** Fuji TV
**_Broken Link (from playlist):_** https://fujitv.mov3.co/hls/fujitv.m3u8
**_Possible Replacement (optional):_** https://fujitv1.mov3.co/hls/fujitv.m3u8

**Comment by Dum4G** [comment]
![image](https://user-images.githubusercontent.com/5430116/132093764-84eaf075-1051-4aee-b7bd-a356560d3700.png)
Already is the case in our playlist. Use self-updatable links
