### ISSUE TITLE
TV5

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#4383]
**Channel Name:** TV5
**Channel ID:** TV5.ph
**Country:** Philippines
**Language:** Tagalog
**Website:** https://www.tv5.com.ph/
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by fotvnetwork** [comment]
TV5 used to have a livestream.

**Comment by freearhey** [comment]
Closed in favor #12269
