### ISSUE TITLE
Kapamilya Channel

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#4384]
**Channel Name:** Kapamilya Channel
**Country:** Philippines
**Language:** Tagalog
**Website:** https://ent.abs-cbn.com/articles-news/kapamilya-channel-livestream-12685
**Stream URL (optional):** xxx
**Notes (optional):** Replacement of ABS-CBN

**Comment by fotvnetwork** [comment]
Kapamilya Channel is on iWantTFC, but log-in credentials are needed.

**Comment by LaneSh4d0w** [comment]
https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UCstEtN0pgOmCf02EdXsGChw/live
