### ISSUE TITLE
ChileVisión

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#4385]
**Channel Name:** CHV/Chilevisión
**Country:** Chile
**Language:** Spanish
**Website:** https://www.chilevision.cl/
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
Untested should be geo

#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://i.imgur.com/xcEnijl.jpg" group-title="",Chilevisión [288p]
http://chv.movil.hls.ztreaming.com/chvmovil2/chilevision@140569/1.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://i.imgur.com/xcEnijl.jpg" group-title="",Chilevisión [480p]
http://live.hls.http.chv.ztreaming.com/chvhdtablet/chv-tablet.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://i.imgur.com/xcEnijl.jpg" group-title="",Chilevisión [720p]
http://live.hls.http.chv.ztreaming.com/chvhddesktop/chv-desktop.m3u8


or

http://iptvcanales.gq/index.php

Download a m3u list .. i selected ALL .. it give 1156 channels

Click "Activar Lista" of the m3u selected 

#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://i.imgur.com/xcEnijl.jpg" group-title="",Chilevisión [480p]
http://iptvcanales.gq/canales/live/243/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
> 
> 
> Untested should be geo
> 
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://i.imgur.com/xcEnijl.jpg" group-title="",Chilevisión [288p]
> http://chv.movil.hls.ztreaming.com/chvmovil2/chilevision@140569/1.m3u8
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://i.imgur.com/xcEnijl.jpg" group-title="",Chilevisión [480p]
> http://live.hls.http.chv.ztreaming.com/chvhdtablet/chv-tablet.m3u8
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://i.imgur.com/xcEnijl.jpg" group-title="",Chilevisión [720p]
> http://live.hls.http.chv.ztreaming.com/chvhddesktop/chv-desktop.m3u8
> 
> or
> 
> http://iptvcanales.gq/index.php
> 
> Download a m3u list .. i selected ALL .. it give 1156 channels
> 
> Click "Activar Lista" of the m3u selected
> 
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://i.imgur.com/xcEnijl.jpg" group-title="",Chilevisión [480p]
> http://iptvcanales.gq/canales/live/243/playlist.m3u8

Websites above didn't work, either backend issue or 404 not found.

For the IPTVCanales...

![image](https://user-images.githubusercontent.com/30985701/132179364-2318e27a-ace7-4d69-9010-666ce62b887e.png)

**Comment by LaneSh4d0w** [comment]
Geolocked https://mdstrm.com/live-stream-playlist/5c928b7f6d6f41084bdae898.m3u8

**Comment by Sphinxroot** [comment]
https://i.imgur.com/nPEblr5.png
i took the all.m3u

then a clicked activar lista and stream work

http://iptvcanales.gq/canales/live/243/playlist.m3u8
https://i.imgur.com/LXz8KA2.png

**Comment by LaneSh4d0w** [comment]
I must say that i'm pretty surprised that those channels are from legit sources.

(it makes a proxy between the end-user and the official source), and makes it possible to watch those channels from where we are.

**Comment by GiovanniSebastian** [comment]
> Geolocked https://mdstrm.com/live-stream-playlist/5c928b7f6d6f41084bdae898.m3u8

 I am from Chile, and this message appears with the link you attached: "status":"ERROR","data":"CLOSED_ACCESS","message":"You are not allowed to watch this event: Invalid Token"}

**Comment by LaneSh4d0w** [comment]
> 
> 
> > Geolocked https://mdstrm.com/live-stream-playlist/5c928b7f6d6f41084bdae898.m3u8
> 
> I am from Chile, and this message appears with the link you attached: "status":"ERROR","data":"CLOSED_ACCESS","message":"You are not allowed to watch this event: Invalid Token"}

Interesting... that's the one that comes from the Chilevision website.
