### ISSUE TITLE
Animax Asia (English Subs)

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#4386]
**Channel Name:** Animax Southeast Asia
**Country:** Southeast Asia
**Language:** Japanese (English Subs)
**Website:** https://www.animax-asia.com/
**Stream URL (optional):** https://feed.play.mv/live/10005200/isU48qPZqV/master.m3u8
**Notes (optional):** An outstanding debt from this repository ;) In this source are many Maldives / India / Asia channels. From here, i need NHK World Premium. If anyone finds it, let me know.

**Comment by LaneSh4d0w** [comment]
That link takes some time to load, but works.
