### ISSUE TITLE
DD News

### ISSUE THREAD

**Issue by nikhil96widhani** [iptv-org/iptv#4387]
**Channel Name:** DD News
**Country:** IN
**Language:** hindi
**Website:** https://ddnews.gov.in/
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by fotvnetwork** [comment]
https://www.youtube.com/channel/UCKwucPzHZ7zCUIf7If-Wo1g/live

**Comment by nikhil96widhani** [comment]
hi I know the YouTube but i cannot use it in my iptv on jellyfin. It has to be m3u8 link 
Thanks

**Comment by Sphinxroot** [comment]
test this 
#EXTINF:-1 tvg-logo="" group-title="",DD
https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UCKwucPzHZ7zCUIf7If-Wo1g/live

**Comment by nikhil96widhani** [comment]
> test this
> #EXTINF:-1 tvg-logo="" group-title="",DD
> https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UCKwucPzHZ7zCUIf7If-Wo1g/live

it works in vlc but not in jellyfin and weird that it shows no log as if it didn’t understand url. I might be able to make it work. May i know what is the source of the software deployed in herokuapp. I will like to deploy it on my own server

For now this link doesn’t work. If i can get m3u8 it will be helpful thanks

**Comment by fotvnetwork** [comment]
![Screenshot (22)](https://user-images.githubusercontent.com/58662510/132169422-148f1b85-03bb-42c9-a688-afa232dc7bf4.png)
Works on my end via browser ext

**Comment by nikhil96widhani** [comment]
Which extension you are using?

**Comment by fotvnetwork** [comment]
Reproductor M3U8 - HLS + DASH Player. It's on Chrome.

**Comment by Sphinxroot** [comment]
> > test this
> > #EXTINF:-1 tvg-logo="" group-title="",DD
> > https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UCKwucPzHZ7zCUIf7If-Wo1g/live
> 
> it works in vlc but not in jellyfin and weird that it shows no log as if it didn’t understand url. I might be able to make it work. May i know what is the source of the software deployed in herokuapp. I will like to deploy it on my own server
> 
> For now this link doesn’t work. If i can get m3u8 it will be helpful thank

see here https://github.com/iptv-org/iptv/discussions/3363  it use streamlink


and if you realy need plain m3u8   go to https://www.youtube.com/channel/UCKwucPzHZ7zCUIf7If-Wo1g/live  get in the source code and find https://manifest.googlevideo.com/  copy and paste the long url  that end by .m3u8 in your local m3u  becaue your ip will be in the link but you will have to grab it later becaue it expire after a hour

**Comment by nikhil96widhani** [comment]
Yes i have tried it but link expires every hour and therir is no way to generate permanent link.

**Comment by Sphinxroot** [comment]
i use kodi with the youtube addon  + the google (Youtube) api  

plugin://plugin.video.youtube/play/?channel_id=UCKwucPzHZ7zCUIf7If-Wo1g&live=1

in a m3u list in the playlistloader addons

you never have to change it again

**Comment by Sphinxroot** [comment]
try this in jellyfin in a m3u list https://www.youtube.com/watch?v=3s3o_72b6rg seem by the doc that it only handle direct stream and not channel or id

**Comment by LaneSh4d0w** [comment]
http://14.199.164.20:4001/play/a0ty/index.m3u8

**Comment by nikhil96widhani** [comment]
> test this
> #EXTINF:-1 tvg-logo="" group-title="",DD
> https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UCKwucPzHZ7zCUIf7If-Wo1g/live

I was able to use this with jellyfin finally. Next is i will try to deploy this app on my server so i can generate multiple links from youtube live

**Comment by nikhil96widhani** [comment]
> http://14.199.164.20:4001/play/a0ty/index.m3u8

This link only works for 1 second then stops

**Comment by Dum4G** [comment]
> http://14.199.164.20:4001/play/a0ty/index.m3u8

lasts for 20 secs like Xstream sources
