### ISSUE TITLE
Dream TV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4388]
**Channel Name:** Dream TV
**Country:** IN
**Language:** Malayalam
**Website:** xxx
**Stream URL (optional):** https://mhdtvworld.xyz/live/dream-tv/
**Notes (optional):** xxx

**Comment by Niyasmkkv** [comment]
Can you guys try this link as well? not working for me in vlc.

https://mhdtvworld.xyz/74a7d346-a3c6-4b5e-b780-77a1d8b7c3cf

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | https://cloudflare-cdn301.ottpro.in//dream_media//reedeem//playlist.m3u8
-- | --
mediaManifest | https://cloudflare-cdn301.ottpro.in//dream_media//reedeem//chunklist_w118157271.m3u8


</body>
</html>

logo https://mhdtvworld.xyz/wp-content/uploads/2021/09/dreamtv-1-90x135.webp

**Comment by Niyasmkkv** [comment]
> Can you guys try this link as well? not working for me in vlc.
> 
> https://mhdtvworld.xyz/74a7d346-a3c6-4b5e-b780-77a1d8b7c3cf

@Sphinxroot check this as well please.

**Comment by Sphinxroot** [comment]
> > Can you guys try this link as well? not working for me in vlc.
> > https://mhdtvworld.xyz/74a7d346-a3c6-4b5e-b780-77a1d8b7c3cf
> 
> @Sphinxroot check this as well please.

name please because this link give me 404

**Comment by Niyasmkkv** [comment]
> > > Can you guys try this link as well? not working for me in vlc.
> > > https://mhdtvworld.xyz/74a7d346-a3c6-4b5e-b780-77a1d8b7c3cf
> > 
> > 
> > @Sphinxroot check this as well please.
> 
> name please because this link give me 404

It is Raj Musix Malayalam from that website.
