### ISSUE TITLE
Romanian channel's

### ISSUE THREAD

**Issue by Boston27** [iptv-org/iptv#439]

**Comment by Boston27** [comment]
Sport channel's.thank you

**Comment by freearhey** [comment]
Could you be more precise and give the names of the channels?

**Comment by Boston27** [comment]
Channel Pro tv . Pro X . Kanal D .Paprika TV .Digi sport 1 !!!...
Thank you very much you are the best! Thank you again!

**Comment by Dakopocsfej** [comment]
Can you please update RO & HU channels   Attached below pic.
![30D94A52-F317-435A-9EAE-A274AAC886EE](https://user-images.githubusercontent.com/46407519/69504056-c4e18580-0f17-11ea-9c30-bd6e35e8eb6e.png)

**Comment by freearhey** [comment]
Pro X: https://github.com/iptv-org/iptv/blob/23c89a90963c778fed6576f2be276e0bc581aee7/channels/ro.m3u#L114-L117

**Comment by freearhey** [comment]
Duplicate #762

**Comment by willrock74** [comment]
Acasa Gold RO
AcasaTV.ro
AMC.ro
AnimalPlanet.ro
Antena1.ro
Boomerang.ro
CartoonNetwork.ro
ComedyCentralExtra.ro
Digi24.ro
DigiAnimalworld.ro
Digi Life RO
DigiSport1.ro
DigiSport2.ro
DigiSport3.ro
DigiSport4.ro
DigiWorld.ro
DiscoveryChannel.ro
DiscoveryID.ro
DiscoveryScience.ro
DisneyChannel.ro
EEntertainment.ro
Etno.ro
Eurosport1.ro
Eurosport2.ro
FashionTV.ro
Favorit.ro
FilmBox.ro
FilmBoxExtra.ro
FilmBoxFamily.ro
FilmBoxPlus.ro
FilmBoxPremium.ro
Filmcafe.ro
Film Now RO
FineLiving.ro
FishingHunting.ro
FoodTV.ro
HappyChannel.ro
HBO.ro
HBO2.ro
HBO3.ro
HistoryChannel.ro
HTMusic.ro
KanalD.ro
KissTV.ro
LookPlus.ro
Look Sport RO
Look Sport 2 RO
Look Sport 3 RO
Megamax.ro
Minimax.ro
MusicChannel.ro
Naşul TV RO
NatGeo.ro
NatGeoWild.ro
Naţional 24 Plus RO
NationalTV.ro
NauticalChannel.ro
NeptunTV.ro
Nickelodeon.ro
NickJr.ro
ParamountChannel.ro
PrimaTV.ro
Pro2.ro Pro 2 RO
ProCinema.ro
ProTV.ro
RealitateaTV.ro
RomaniaTv.ro
Sportro.ro
TarafTV.ro
TelekomSport1.ro
TelekomSport2.ro
TelekomSport3.ro
TelekomSport4.ro
TelekomSport5.ro
TelekomSport6.ro
TLC.ro
TNT.ro
TopShopTV.ro
TravelChannel.ro
TravelMix.ro
TV1000.ro
TVPaprika.ro
TVR1.ro
TVR2.ro
TVR3.ro
UTV.ro
ViasatExplore.ro
ViasatHistory.ro
ViasatNature.ro
ZUTV.ro ZU TV RO




Sorry, the channels above are not in the list provided by  freearhey
