### ISSUE TITLE
Imayam TV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4393]
**Channel Name:** Imayam
**Country:** IN
**Language:** Tamil
**Website:** xxx
**Stream URL (optional):** https://mhdtvworld.xyz/da177e2b-5e02-4453-83e7-f57bed067a8c
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | https://idvd.multitvsolution.com/idvo/imayamtv.m3u8
-- | --
mediaManifest | https://idvd.multitvsolution.com/idvo/imayamtv_540p/index.m3u8


</body>
</html>

https://i.imgur.com/CzdM0pg.png
