### ISSUE TITLE
Epic TV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4396]
**Channel Name:** Epic TV
**Country:** India
**Language:** Hindi
**Website:** xxx
**Stream URL (optional):** https://www.mxplayer.in/live-tv/epic-live-channel-2639epicin
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
https://m-c036-j2apps.s.llnwi.net/hls/2639.Epic.in.m3u8 from deduction

**Comment by Niyasmkkv** [comment]
> https://m-c036-j2apps.s.llnwi.net/hls/2639.Epic.in.m3u8

Not working on VLC for me

**Comment by LaneSh4d0w** [comment]
https://m-c03-j2apps.s.llnwi.net/hls/2639.Epic.in.m3u8

**Comment by Dum4G** [comment]
Error 400

**Comment by LaneSh4d0w** [comment]
I'll try looking back using an Indian IP later on.

**Comment by LaneSh4d0w** [comment]
https://m-c03-j2apps.s.llnwi.net/hls/2639.Epic.in.m3u8 is the one I have from MXPlayer.

**Comment by Niyasmkkv** [comment]
https://m-c03-j2apps.s.llnwi.net/hls/2639.Epic.in.m3u8 
this is working fine for me in VLC.

**Comment by Niyasmkkv** [comment]
Yup. Added to the list
