### ISSUE TITLE
Fix: https://iptv-org.github.io/iptv/countries/mu.m3u (Mauritius)

### ISSUE THREAD

**Issue by pgorr** [iptv-org/iptv#4399]
Hi, the link 

https://iptv-org.github.io/iptv/countries/mu.m3u 

is supposed to give Mauritian TV but is giving something else. Grateful for any assistance. 
pgorr

**Comment by freearhey** [comment]
By Mauritian TV do you mean this channel: https://www.lyngsat.com/tvchannels/mu/MBC-1.html?

**Comment by pgorr** [comment]
Yes, that’s the one. There is also MBC 2 in the related Channels at the bottom of the page. Thanks!

**Comment by freearhey** [comment]
Unfortunately we do not have working links to these channels at the moment, but as soon as they appear we will add them to the playlist.

**Comment by freearhey** [comment]
Closed in favor of #4403 and #4404

**Comment by pgorr** [comment]
Thank you for getting back to me. I will be checking on and off in case you guys are able to work it out. Thanks!
