### ISSUE TITLE
are this channels legal?

### ISSUE THREAD

**Issue by hakankoesekadam** [iptv-org/iptv#440]
Hi guys,

I did not had the chance to test the URL for Turkey so far. but I do wanna know whether this is legal or not. 

Can somebody give me an answer?

thank you guys and have a nice day.

thx for this repo!!!

best regards

Hakan

**Comment by freearhey** [comment]
Well, the legislation in different countries can be very different, and I do not know how in Turkey, but usually it is not forbidden to watch IPTV.

**Comment by hakankoesekadam** [comment]
hey freearhey,
thank you for your answer. usually there are channels like sky and bein sport which are known as pay tv.

Have a nice day :)

**Comment by kilisio** [comment]
@freearhey I am currently building a free android app and want to add these channels default on the app. Are there any legal restrictions to doing so? thanks for the great repo...

**Comment by freearhey** [comment]
@kilisio as I know there are no such thing, but I think it would be better to address this question in support of Google Play because they may have their own restrictions.

**Comment by kilisio** [comment]
@freearhey will do that... thanks again
