### ISSUE TITLE
MBC 1

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#4403]
**Channel Name:** MBC 1
**Channel ID:** MBC1.mu
**Country:** Mauritius
**Language:** French
**Link:** https://www.lyngsat.com/tvchannels/mu/MBC-1.html

**Comment by Sphinxroot** [comment]
only thing ive found so far  all other hang and stop


DAILY STREAMING Mauritius time
SAMACHAR @ 18H00
ZOURNAL KREOL @ 19:00
JOURNAL TELEVISE @ 19:30

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="" tvg-language="" tvg-logo="https://i.imgur.com/ro2uEdB.jpg" group-title="",MBC 1
https://webhls.mbconline.xyz/hls/stream1.m3u8

**Comment by LaneSh4d0w** [comment]
> 
> 
> only thing ive found so far all other hang and stop
> 
> DAILY STREAMING Mauritius time
> SAMACHAR @ 18H00
> ZOURNAL KREOL @ 19:00
> JOURNAL TELEVISE @ 19:30
> 
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-country="" tvg-language="" tvg-logo="https://i.imgur.com/ro2uEdB.jpg" group-title="",MBC 1
> https://webhls.mbconline.xyz/hls/stream1.m3u8

Same here, from the MBC website.

**Comment by freearhey** [comment]
Closed in favor #12266
