### ISSUE TITLE
no work tntendirect

### ISSUE THREAD

**Issue by chezsick** [iptv-org/iptv#441]
the channels stream name begin as https://s1.tntendirect.com dont work, and when go to website tntendirect.com (hyperlink disabled for valid reason) the stream is work inside this, i tested just TF1 not other, because, contain advertisement fake and scam is boring.

maybe update the url

thank to change, sick.

**Comment by freearhey** [comment]
Broken links I deleted. As soon as the replacement appears, we will return the channels back.
