### ISSUE TITLE
NHK General stuck buffering 

### ISSUE THREAD

**Issue by qoiz** [iptv-org/iptv#4435]
**_Channel Name:_** NHK General
**_Broken Link (from playlist):_** https://iptv-org.github.io/iptv/countries/jp.m3u
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** xxx

**Comment by jkemp814** [comment]
Line:38 NHK General TV
Line:39 https://nhk1.mov3.co/hls/nhk.m3u8

Runs smooth as butter from here. (1:00AM)

**Comment by MapGuy11** [comment]
![image](https://user-images.githubusercontent.com/43685307/132673125-ba03b967-1ab5-4ab9-9fc0-325a0ce6fda6.png)
Works fast CDN

**Comment by freearhey** [comment]
@qoiz Do you mean this buffering?
![vlcsnap-2021-09-09-20h58m08s733](https://user-images.githubusercontent.com/7253922/132738538-68523f3a-c157-416d-9f8e-49e2578e59a5.png)

**Comment by Dum4G** [comment]
Sometimes sources tend to temporarily freeze. Can't confirm this behaviour

**Comment by qoiz** [comment]
@freearhey Yes

**Comment by freearhey** [comment]
@qoiz Unfortunately we have no control over the quality of the broadcast, but if there is an alternative we will definitely add it to the playlist.
