### ISSUE TITLE
Fix: GTNTyphome.jp

### ISSUE THREAD

**Issue by fearlesschicken** [iptv-org/iptv#4446]
**_Channel Name:_** GTNTyphome.jp
**_Broken Link (from playlist):_** https://gorilla.gaki-no-tsukai.eu/hls/test.m3u8
**_Possible Replacement (optional):_** https://hamada.gaki-no-tsukai.eu:2087/hls/test.m3u8
**_Notes (optional):_** Url was recently changed

**Comment by LaneSh4d0w** [comment]
Making the change.
