### ISSUE TITLE
Janapriyam TV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4466]
**Channel Name:** Janapriyam TV
**Country:** IN
**Language:** Malayalam
**Website:** https://janapriyam.com/
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
from site 
https://cdn.janapriyam.in/janapriyam_jio/index.m3u8  no mediamanifest found

i also found this , but it dont seem to play on anything
https://jio.instream.ml/jio.php?c=Janapriyam_News&q=400&e=.m3u8

this is inside
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:3995
#EXT-X-TARGETDURATION:6
#EXTINF:6.000,
http://jiotv.live.cdn.jio.com/Janapriyam_News/Janapriyam_News_800-1631333382000.ts
#EXTINF:6.000,
http://jiotv.live.cdn.jio.com/Janapriyam_News/Janapriyam_News_800-1631333388000.ts
#EXTINF:6.000,
http://jiotv.live.cdn.jio.com/Janapriyam_News/Janapriyam_News_800-1631333394000.ts
#EXTINF:6.000,
http://jiotv.live.cdn.jio.com/Janapriyam_News/Janapriyam_News_800-1631333400000.ts
#EXTINF:6.000,
http://jiotv.live.cdn.jio.com/Janapriyam_News/Janapriyam_News_800-1631333406000.ts
#EXTINF:6.000,
http://jiotv.live.cdn.jio.com/Janapriyam_News/Janapriyam_News_800-1631333412000.ts
#EXTINF:6.000,
http://jiotv.live.cdn.jio.com/Janapriyam_News/Janapriyam_News_800-1631333418000.ts
#EXTINF:6.000,
http://jiotv.live.cdn.jio.com/Janapriyam_News/Janapriyam_News_800-1631333424000.ts
#EXTINF:6.000,
http://jiotv.live.cdn.jio.com/Janapriyam_News/Janapriyam_News_800-1631333430000.ts

and so on

all give 404
https://jio.instream.ml/j/ and u can browse folder upper

**Comment by Niyasmkkv** [comment]
https://jio.instream.ml/jio.php?c=Janapriyam_News&q=400&e=.m3u8
This one is working for me.

**Comment by Niyasmkkv** [comment]
@Sphinxroot can you try finding Raj Musix Malayalam form the above folder? I'm not able to access it.

**Comment by Sphinxroot** [comment]
> https://jio.instream.ml/jio.php?c=Janapriyam_News&q=400&e=.m3u8
> This one is working for me.

well lucky  if its work  , so its geo stream  ,, but strangely i can access the file  and i dont get forbidden  but nothing play on my side

for all other channel  , try by deduction  https://jio.instream.ml/jio.php?c=CHANNEL_NAME&q=400&e=.m3u8
or &q=800&e=.m3u8 

https://jio.instream.ml/jio.php?c=Raj_Music_Malayiam&q=400&e=.m3u8

https://jio.instream.ml/j/  if you can see channel naming here ,  it might work , i cant be sure since nothing play on my side

**Comment by Niyasmkkv** [comment]
![image](https://user-images.githubusercontent.com/88939244/132954203-9faef219-689e-464a-a4b5-3c3f4f03dfa7.png)
Getting 404.

**Comment by Niyasmkkv** [comment]
It's starnage that only that channel worked and others are showing error.

**Comment by Sphinxroot** [comment]
try https://jio.instream.ml/jio.php?c=Raj_Music_Malayalam&q=400&e=.m3u8

i can access the file 

#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:11581
#EXT-X-TARGETDURATION:6
#EXT-X-KEY:METHOD=AES-128,URI="streamit.php?id=0&key=Raj_Music_Malayalam/Raj_Music_Malayalam_400-1631378326000.key",IV=0x00000000000000000000017BD5B9C1F0
#EXTINF:6.000,
http://jiotv.live.cdn.jio.com/Raj_Music_Malayalam/Raj_Music_Malayalam_400-1631378812000.ts
#EXTINF:6.000,
http://jiotv.live.cdn.jio.com/Raj_Music_Malayalam/Raj_Music_Malayalam_400-1631378818000.ts
#EXTINF:6.000,
http://jiotv.live.cdn.jio.com/Raj_Music_Malayalam/Raj_Music_Malayalam_400-1631378824000.ts
#EXTINF:6.000,
http://jiotv.live.cdn.jio.com/Raj_Music_Malayalam/Raj_Music_Malayalam_400-1631378830000.ts
#EXTINF:6.000,
http://jiotv.live.cdn.jio.com/Raj_Music_Malayalam/Raj_Music_Malayalam_400-1631378836000.ts
#EXTINF:6.000,
http://jiotv.live.cdn.jio.com/Raj_Music_Malayalam/Raj_Music_Malayalam_400-1631378842000.ts

**Comment by Niyasmkkv** [comment]
it's not working for me on vlc.
