### ISSUE TITLE
all Malayalam channels playlist or m3u url link

### ISSUE THREAD

**Issue by kojo88** [iptv-org/iptv#4471]
**Channel Name:** Malayalam Channels
**Country:** xxx
**Language:** Malayalam
**Website:** xxx
**Stream URL (optional):** xxx

His Niyas.....could you please send a working m3u link for all Malayalam channels so that can use for my smart TV
Thanks

**Comment by Niyasmkkv** [comment]
@kojo88 https://iptv-org.github.io/iptv/languages/mal.m3u
here is the link. Try using VLC or Kodi with simple IPTV client.

**Comment by kojo88** [comment]
Thanks dear but asianet middle-east not working and also Asianet HD not shown

**Comment by Niyasmkkv** [comment]
> Thanks dear but asianet middle-east not working and also Asianet HD not shown

This is list includes mostly free to air channels. And don't expect any pay channels from this list. Even if there are few don't expect them to be there for a while. Middle East is working fine for me.

**Comment by kojo88** [comment]
Yes middle east is working now....if possible, can you please get all bein sports channels m3u?

**Comment by Dum4G** [comment]
Next time, please read our guides for channel requests and use search
