### ISSUE TITLE
Apollon TV

### ISSUE THREAD

**Issue by taodicakhia** [iptv-org/iptv#4501]
**_Channel Name:_** Apollon TV (Albania)
**_Broken Link (from playlist):_** http://185.80.224.14:1935/live/smil:web.smil/playlist.m3u8
**_Possible Replacement (optional):_** Query the stream from apollon.tv
**_Notes (optional):_** xxx

**Comment by trancer1994** [comment]
https://live.apollon.tv/Apollon-WEB/video.m3u8?token=tnt3u76re30d2
