### ISSUE TITLE
Chicago Version of LocalNow

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#4509]
**Channel Name:** Local Now(Chicago Version)
**Country:** USA - Chicago
**Language:** English
**Website:** xxx
**Stream URL (optional):** https://prod.localnowapi.com/vod/api/v2/LiveStream/Playback/ilChicago/index.m3u8
**Notes (optional):** Can you Add Chicago Version of Local Now?

**Comment by jkemp814** [comment]
https://du6zwf9bdczcq.cloudfront.net/video/OTT/hls/ilChicago_WeatherToday/1631453235/manifest.m3u8

**Comment by Dum4G** [comment]
> May also need http referrer to play in VLC

Does play for me as it is

**Comment by LaneSh4d0w** [comment]
Doesn't for me. 403 Forbidden

**Comment by Dum4G** [comment]
> Doesn't for me. 403 Forbidden

US VPN is needed

**Comment by LaneSh4d0w** [comment]
> 
> 
> > Doesn't for me. 403 Forbidden
> 
> US VPN is needed

Found out after, yes.
