### ISSUE TITLE
CBS 46 Atlanta, GA (WGCL-TV)

### ISSUE THREAD

**Issue by jmacie** [iptv-org/iptv#4517]
**_Channel:_** CBS 46 Atlanta, GA (WGCL-TV)
**_Country:_** USA
**_Playlist:_** https://iptv-org.github.io/iptv/countries/us.m3u 
**_Possible Replacement (optional):_** xxx
**_Notes:_** THX  :)

**Comment by jkemp814** [comment]
![snapshot](https://user-images.githubusercontent.com/12059343/133013944-cdafc8a2-8247-4382-836a-75b7a650a33d.jpg)

Locks right on, stream is smooth and audio is good.

**Comment by jmacie** [comment]
> ![snapshot](https://user-images.githubusercontent.com/12059343/133013944-cdafc8a2-8247-4382-836a-75b7a650a33d.jpg)
> 
> Locks right on, stream is smooth and audio is good. Also, that's a newscast channel. The stream will not broadcast live content until news hours. Maybe that's why it's being reported.

**Comment by jmacie** [comment]
No, CBS 46 Atlanta, GA.   WGCL-TV.  isn't working

**Comment by jkemp814** [comment]
I tried it in Firefox browser and VLC. Which player are you using?

**Comment by jmacie** [comment]
VLC

**Comment by jkemp814** [comment]
Are you seeing that stream of the down town area?

**Comment by jmacie** [comment]
NO, there is no entry for CBS 46 Atlanta in VLC at all. There was before but it didn't work, hence the broken link report

**Comment by jkemp814** [comment]
Yes, I notice that also. I'm in Kodi  and it does not show there either. I copied the list right from the us.m3u list in my editor I'm currently working in. It is  in the us.m3u file. The grouping has just changed recently.

**Comment by jkemp814** [comment]
Put this link in VLC under open network stream.

https://live.field59.com/wgcl/ngrp:wgcl1_all/playlist.m3u8

**Comment by jmacie** [comment]
Whatever this pic is it is not TV 46 CBS Atlanta, it is a still of Mercedes Benz stadium. CBS 46 is playing NCIS right now

**Comment by jkemp814** [comment]
Read my comment earlier. That is a newscast channel. Not live full schedule. It becomes live when the news is on. You have to put in a channel request for the live full schedule version. They do not stream that online. Someone would have to, rest ream it and provide the link.

**Comment by jkemp814** [comment]
That is also a live camera shot of the stadium. Notice the light blinking. It's not a still.

**Comment by jmacie** [comment]
Alright now I know, I was not informed. That placeholder is not on the stream though. I copied the new https://iptv-org.github.io/iptv/countries/us.m3u.        and CBS 46 Atklanta is not there, but it was before, just not functional, hence the reporting. Thanks for the info

**Comment by jkemp814** [comment]
There are quite a few not showing up in VLC or Kodi. May have something to do with the recent re-sorting of channels. New files being added. If you look in the us.m3u it is listed in there. Just not showing up in the index type files.

**Comment by jmacie** [comment]
Thanks for your time

**Comment by jkemp814** [comment]
That's the same list I use. But I edit directly in the actual files that make up that list. Indexes are compiled from other file list.
