### ISSUE TITLE
MBC2

### ISSUE THREAD

**Issue by ksmehra** [iptv-org/iptv#4541]
**_Channel Name:_** MBC2
**_Country:_** UAE
**_Broken Link (from playlist):_** https://shls-mbc2-prod-dub.shahid.net/out/v1/b4befe19798745fe986f5a9bfba62126/index.m3u8

**Comment by Mennaruuk** [comment]
`https://shls-mbc2-prod-dub.shahid.net/out/v1/b4befe19798745fe986f5a9bfba62126/index.m3u8`

**Comment by trancer1994** [comment]
It works for me.

**Comment by Mennaruuk** [comment]
> It works for me.

It's stuck on a minute-long video of _A Quiet Place_ no matter what time you stream the channel.
![image](https://user-images.githubusercontent.com/52135169/133503455-18e67ddc-7a50-4f39-8eda-fab7e3c984d6.png)

**Comment by LaneSh4d0w** [comment]
https://blogs.livehdchanel.live/mbc-222/index.m3u8

**Comment by ksmehra** [comment]
working well at RESOLUTION=1198x720
