### ISSUE TITLE
MBC Action (1080p)

### ISSUE THREAD

**Issue by ksmehra** [iptv-org/iptv#4542]
**_Channel Name:_** MBC Action (1080p)
**_Country:_** UAE
**_Broken Link (from playlist):_** https://shls-mbcaction-prod-dub.shahid.net/out/v1/68dd761538e5460096c42422199d050b/index.m3u8

**Comment by LaneSh4d0w** [comment]
https://blogs.livehdchanel.live/action2/index.m3u8

**Comment by ksmehra** [comment]
working well with RESOLUTION=1024x576

**Comment by LaneSh4d0w** [comment]
Perfect !
