### ISSUE TITLE
MBC Max (1080p)

### ISSUE THREAD

**Issue by ksmehra** [iptv-org/iptv#4543]
**_Channel Name:_** MBC Max (1080p)
**_Country:_** UAE
**_Broken Link (from playlist):_** https://shls-mbcmax-prod-dub.shahid.net/out/v1/13815a7cda864c249a88c38e66a2e653/index.m3u8

**Comment by Mennaruuk** [comment]
How about this? I’m on my phone, so I don’t know if this is 720p or 1080p:

‘https://shls-mbcmax-prod-dub.shahid.net/out/v1/13815a7cda864c249a88c38e66a2e653/index.m3u8’

**Comment by LaneSh4d0w** [comment]
![image](https://user-images.githubusercontent.com/30985701/133218754-8a6a50e9-f9cf-4fb3-8810-77b299964b39.png)

**Comment by ksmehra** [comment]
@LaneSh4d0w what player do you use?

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w what player do you use?

A Firefox extension named "Native MPEG-Dash + HLS Playback".

But on both this extension and VLC it's the same 1 minute video repeating.

**Comment by ksmehra** [comment]
indeed it is. i use iptvnator. was just curious what you're using. thx

**Comment by LaneSh4d0w** [comment]
https://blogs.livehdchanel.live/max/index.m3u8

**Comment by ksmehra** [comment]
working well @ RESOLUTION=1024x576
