### ISSUE TITLE
Fix: Rename "The CW Central PA" To "The CW Plus East"

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#4545]
Link:https://bozztv.com/teleyupp1/teleup-cw-whp/playlist.m3u8
They Aried NBC and MeTV Promos. In The MeTV Promo,MeTV Logo was Assigned to Johnstown・Altoona State Collage
(https://en.wikipedia.org/wiki/WJAC-TV)
![WJAC](https://user-images.githubusercontent.com/86145713/133170563-0295b808-fff6-4576-8b0a-da0216f07e37.PNG)

Also, The CW Plus East is Looks Like National Feed of CW(https://en.wikipedia.org/wiki/The_CW_Plus)

**Comment by Ulter32** [comment]
![Uploading C2584AAA-614F-45B6-900E-24CECFF03CB6.jpeg…]()

**Comment by Central302** [comment]
![IMG_3592](https://user-images.githubusercontent.com/86145713/133172626-85b853fa-b875-4482-9c11-74b682ae9889.JPG)
