### ISSUE TITLE
TV5 Soritor

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#4563]
**Channel Name:** TV5 Soritor
**Country:** Peru
**Language:** Spanish
**Website:** https://moyobamba.com/tv5soritor/
**Notes:** Opencaster streaming

**Comment by LaneSh4d0w** [comment]
Haven't I already added this channel before ?

**Comment by LaneSh4d0w** [comment]
Found out that Streamlink supported the origin header addition.

![image](https://user-images.githubusercontent.com/30985701/133400404-7c2571cb-c420-44af-b929-fba0871456bb.png)

**Comment by trancer1994** [comment]
https://edge1o.live.opencaster.com/caster/aEcjDGoqknpH.m3u8

**Comment by LaneSh4d0w** [comment]
> 
> 
> https://edge1o.live.opencaster.com/caster/aEcjDGoqknpH.m3u8

Origin-locked.

**Comment by sguinetti** [comment]
> Haven't I already added this channel before ?
> 
> EDIT : I think I had a "déjà vu" sensation. I've reckoned this channel without even having it. My bad.

I was creating a new issue to organize the new channels with Opencaster to #3063

**Comment by LaneSh4d0w** [comment]
Some stuff have changed, they moved all their channels to another website, most certainly they moved from Opencaster (recently it seems Opencaster had a sort of blackout, couldn't see any live channel).

**Comment by LaneSh4d0w** [comment]
https://live.obslivestream.com/tv5soritormux/index.m3u8
