### ISSUE TITLE
Canal 21 Huancayo

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#4567]
**Channel Name:** Canal 21 Huancayo
**Channel ID:** Canal21Huancayo.pe
**Country:** Peru
**Language:** Spanish
**Website:** https://canal21huancayo.com/en-vivo/
**Notes:** Opencaster streaming

**Comment by sguinetti** [comment]
I just see it. So the entry is:
Origin: https://www.opencaster.com
And set: https://query-streamlink-us.herokuapp.com/iptv-query?streaming-ip=https://edge1o.live.opencaster.com/caster/ztCaDbjyCrwa.m3u8

Is this right?

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w I just see it. So the entry is:
> Origin: https://www.opencaster.com
> And set: https://query-streamlink-us.herokuapp.com/iptv-query?streaming-ip=https://edge1o.live.opencaster.com/caster/ztCaDbjyCrwa.m3u8 OR https://query-streamlink-us.herokuapp.com/iptv-query?streaming-ip=http://www.opencaster.com/nicolezevallos98-100-100
> 
> Is this right?

It's a much more complex case tbh, if you manage to add origin before request being sent, the opencaster link alone is OK.

**Comment by sguinetti** [comment]
I tryed with:

#EXTINF:-1 tvg-id="Canal21Huancayo.pe" tvg-country="PE" tvg-language="Spanish" tvg-logo="https://graph.facebook.com/canal21huancayo/picture?width=320&height=320" group-title="Local",Canal 21 Huancayo
#EXTVLCOPT:http-referrer=https://opencaster.com/
https://edge1o.live.opencaster.com/caster/ztCaDbjyCrwa.m3u8

But, this metod not works.

**Comment by LaneSh4d0w** [comment]
> I tryed with:
> 
> #EXTINF:-1 tvg-id="Canal21Huancayo.pe" tvg-country="PE" tvg-language="Spanish" tvg-logo="https://graph.facebook.com/canal21huancayo/picture?width=320&height=320" group-title="Local",Canal 21 Huancayo
> #EXTVLCOPT:http-referrer=https://opencaster.com/
> https://edge1o.live.opencaster.com/caster/ztCaDbjyCrwa.m3u8
> 
> This code is created in m3u test file. But, this metod not works in VLC.

Yes, because it's origin-locked, not referrer-locked. VLC doesn't natively support it.

**Comment by sguinetti** [comment]
Yes, that would be complicated. What would you recommend for test this? I am planning to create a separate pe_opencaster file for future opencaster entries (like other from their website).

**Comment by LaneSh4d0w** [comment]
Sadly we can't deal with Opencaster links. Closing.
