### ISSUE TITLE
Milenia TV

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#4575]
**Channel Name:** Milenia TV
**Channel ID:** MileniaTVHD.pe
**Country:** Perú
**Language:** Spanish
**Website:** http://www.radiomileniaperu.com/mileniatv/
**Notes (optional):** Opencaster streaming

**Comment by Alstruit** [comment]
https://edge1o.live.opencaster.com/caster/djogxharyzrv.m3u8

**Comment by LaneSh4d0w** [comment]
Sadly we can't deal with Opencaster links. Closing.
