### ISSUE TITLE
cnbc down

### ISSUE THREAD

**Issue by jackitsdotcom** [iptv-org/iptv#458]
hello there,

looks like the following are both down. 
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://i.imgur.com/suuHr0I.png" group-title="Business",CNBC
https://1674331492.rsc.cdn77.org/LS-ATL-54548-14/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://i.imgur.com/suuHr0I.png" group-title="Business",CNBC
https://1674331492.rsc.cdn77.org/LS-ATL-54548-14/index.m3u8?fluxustv.m3u8

**Comment by freearhey** [comment]
You are right, the links are broken. I already deleted them from the playlist. But as soon as a replacement appears, we will return them back.

**Comment by boomski** [comment]
Try this one
https://1161275585.rsc.cdn77.org/LS-ATL-54548-14/tracks-v1a1/mono.m3u8

**Comment by freearhey** [comment]
@boomski this link works for me but the sound is not sync with the image

**Comment by boomski** [comment]
@freearhey yes, sound is maybe a liitle bit behind (max 2 seconds) , but this is the best i can find right now , its better then nothing , but if we find something better we can replace it

**Comment by boomski** [comment]
try this one , Looks better synced to me
http://71ad2a18.iptvbot.ru/iptv/UAVTALUW886L8G/962/index.m3u8

**Comment by freearhey** [comment]
the last link works fine.  I will add it to the playlist
