### ISSUE TITLE
ETV Telugu

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4585]
**Channel Name:** ETV Telugu
**Channel ID:** ETVTelugu.in
**Country:** IN
**Language:** Telugu
**Website:** xxx
**Stream URL (optional):** http://212.102.60.40:2200/R-EX/TELUGU_ETV_HD-in/index.m3u8?token=RED_vqojroBEF5bGJvXYRDdV3w==,1619774634.1743800549
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
Interesting how you got that token.

**Comment by Dum4G** [comment]
EX - token links are personal and usually die pretty fast

**Comment by freearhey** [comment]
Closed in favor #12263
