### ISSUE TITLE
Add one of the most important channels in the Czech Republic

### ISSUE THREAD

**Issue by andresgutice** [iptv-org/iptv#4588]
**Channels Names:**  Prima, Prima Cool, Prima Love, Prima Zoom, Prima Max, Prima Start
**Country:** Czechia
**Language:** Czech
**Website:** https://www.iprima.cz/
**Stream URL (optional):** xxx
**Notes (optional):** These are one of the most important channels in this country, it would be good if it is on the IPTV list

**Comment by freearhey** [comment]
Please read the [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel) before posting your next request.
