### ISSUE TITLE
[Help needed] Pixelated IPTV on Ubuntu (VLC) 

### ISSUE THREAD

**Issue by message** [iptv-org/iptv#459]
Hey guys, I think there is something wrong with my configuration for VLC client. I get pixelated IPTV with some video decoding noise I guess. It changes like every few frames and makes a stream unwatchable:
![Screenshot from 2019-10-08 15-03-09](https://user-images.githubusercontent.com/492026/66395341-d7434680-e9df-11e9-94ef-9aa903a121cd.png)

Maybe you have encountered such behavior before? Any tips?

**Comment by freearhey** [comment]
Could you clarify this happens with all channels in playlists or only with some?

**Comment by message** [comment]
@freearhey yeap, with all channels I've tried. I tried disabled and automatic hardware decoding in ffmpeg section of VLC. Same result.

BBC News:
![Screenshot from 2019-10-08 23-13-50](https://user-images.githubusercontent.com/492026/66429872-a126b680-ea21-11e9-814c-4ae3c7ff2a36.png)

**Comment by freearhey** [comment]
I personally have not encountered such a problem, but I think there is still someone who will help you.

**Comment by message** [comment]
Tried my other machine with 19.04 and everything works fine. Problem is occuring on Linux Mint 19.2 which is based on Ubuntu 18.04 LTS. I will try to test a few things. If there is no solution or comments to this issue within month or two, close the issue.
