### ISSUE TITLE
Medi1 tv channels have disappeared

### ISSUE THREAD

**Issue by saidma** [iptv-org/iptv#4601]
Medi1 tv channels have disappeared from the Moroccan, Arab and French lists

https://github.com/iptv-org/iptv/commit/ddfdeeb2076dff6dd0ce0c6dc66425c063cc9686

**Comment by Sphinxroot** [comment]
they are in here https://github.com/iptv-org/iptv/blob/master/channels/ma.m3u  line 38 to 43 

if you look the pull request 

deleted:
#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="MA" tvg-language="French" tvg-logo="https://i.imgur.com/MosTwQW.png" group-title="",Medi 1 TV (360p)
http://streaming.medi1tv.com/live/Medi1tvmaghreb.sdp/playlist.m3u8

added:
#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="MA" tvg-language="French" tvg-logo="" group-title="",Medi 1 TV Afrique
https://5f72f3a9b06b7.streamlock.net/live/smil:medi1fr.smil/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="MA" tvg-language="French;Arabic" tvg-logo="https://i.imgur.com/MosTwQW.png" group-title="",Medi 1 TV Maghreb
https://5f72f3a9b06b7.streamlock.net/live/smil:medi1tv.smil/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="MA" tvg-language="Arabic" tvg-logo="https://i.imgur.com/MosTwQW.png" group-title="",Medi 1 TV Arabic
https://5f72f3a9b06b7.streamlock.net/live/smil:medi1ar.smil/playlist.m3u8


and now in the list
#EXTINF:-1 tvg-id="Medi1TVAfrique.ma" tvg-country="MA" tvg-language="French" tvg-logo="" group-title="News",Medi 1 TV Afrique (1080p) [Offline]
https://5f72f3a9b06b7.streamlock.net/live/smil:medi1fr.smil/playlist.m3u8
#EXTINF:-1 tvg-id="Medi1TVArabic.ma" tvg-country="MA" tvg-language="Arabic" tvg-logo="https://i.imgur.com/MosTwQW.png" group-title="News",Medi 1 TV Arabic (1080p) [Offline]
https://5f72f3a9b06b7.streamlock.net/live/smil:medi1ar.smil/playlist.m3u8
#EXTINF:-1 tvg-id="Medi1TVMaghreb.ma" tvg-country="MA" tvg-language="French;Arabic" tvg-logo="https://i.imgur.com/MosTwQW.png" group-title="News",Medi 1 TV Maghreb (1080p) [Offline]
https://5f72f3a9b06b7.streamlock.net/live/smil:medi1tv.smil/playlist.m3u8

but all of them work

**Comment by saidma** [comment]
> they are in here https://github.com/iptv-org/iptv/blob/master/channels/ma.m3u line 38 to 43
> 
> if you look the pull request
> 
> deleted:
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-country="MA" tvg-language="French" tvg-logo="https://i.imgur.com/MosTwQW.png" group-title="",Medi 1 TV (360p)
> http://streaming.medi1tv.com/live/Medi1tvmaghreb.sdp/playlist.m3u8
> 
> added:
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-country="MA" tvg-language="French" tvg-logo="" group-title="",Medi 1 TV Afrique
> https://5f72f3a9b06b7.streamlock.net/live/smil:medi1fr.smil/playlist.m3u8
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-country="MA" tvg-language="French;Arabic" tvg-logo="https://i.imgur.com/MosTwQW.png" group-title="",Medi 1 TV Maghreb
> https://5f72f3a9b06b7.streamlock.net/live/smil:medi1tv.smil/playlist.m3u8
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-country="MA" tvg-language="Arabic" tvg-logo="https://i.imgur.com/MosTwQW.png" group-title="",Medi 1 TV Arabic
> https://5f72f3a9b06b7.streamlock.net/live/smil:medi1ar.smil/playlist.m3u8
> 
> and now in the list
> #EXTINF:-1 tvg-id="Medi1TVAfrique.ma" tvg-country="MA" tvg-language="French" tvg-logo="" group-title="News",Medi 1 TV Afrique (1080p) [Offline]
> https://5f72f3a9b06b7.streamlock.net/live/smil:medi1fr.smil/playlist.m3u8
> #EXTINF:-1 tvg-id="Medi1TVArabic.ma" tvg-country="MA" tvg-language="Arabic" tvg-logo="https://i.imgur.com/MosTwQW.png" group-title="News",Medi 1 TV Arabic (1080p) [Offline]
> https://5f72f3a9b06b7.streamlock.net/live/smil:medi1ar.smil/playlist.m3u8
> #EXTINF:-1 tvg-id="Medi1TVMaghreb.ma" tvg-country="MA" tvg-language="French;Arabic" tvg-logo="https://i.imgur.com/MosTwQW.png" group-title="News",Medi 1 TV Maghreb (1080p) [Offline]
> https://5f72f3a9b06b7.streamlock.net/live/smil:medi1tv.smil/playlist.m3u8
> 
> but all of them work

Yes. Channels do not appear in apps.  Someone has disabled the channels ([offline])

**Comment by Sphinxroot** [comment]
oki will change to not 27/7 maybe its the case

**Comment by saidma** [comment]
> oki will change to not 24/7 maybe its the case

I don't think that's the problem.  The channels still do not appear

**Comment by LaneSh4d0w** [comment]
They'll appear back at next update from the bot.

**Comment by saidma** [comment]
> oki will change to not 24/7 maybe its the case

I don't think that's the problem.  The channels still do not appear
![Screenshot_20210917_173350_org videolan vlc](https://user-images.githubusercontent.com/18542801/133815758-1fb9b0a3-3d46-4af9-8611-ce2496507c13.jpg)
