### ISSUE TITLE
Bang Bang 

### ISSUE THREAD

**Issue by WakeAP** [iptv-org/iptv#4607]
Channel Name: Bang Bang 
Country: Albanian 
Language: Shqip
Website: https://digitalb.al/

**Comment by Sphinxroot** [comment]
we can`t xtream-code inside

**Comment by Dum4G** [comment]
http://93.157.62.180/BangBang/index.m3u8

**Comment by Dum4G** [comment]
http://us.bestvideostreaming.is/8737/playlist.m3u8

**Comment by WakeAP** [comment]
Thank You
