### ISSUE TITLE
Add USA OTA and Kids Channels

### ISSUE THREAD

**Issue by Philblue7** [iptv-org/iptv#4611]
Can you add the following channels?:

- Antenna TV East
- Rewind TV East
- UniMas East
- V-me
- V-me Kids
- Primo TV

- Cartoon Network USA
- Cartoonito UK
- Boomerang USA
- Discovery Family USA
- Disney Junior USA
- Disney XD USA
- Nick Jr. USA
- Nicktoons USA
- TeenNick USA

**Comment by freearhey** [comment]
Please read the [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel) before posting your next request.

**Comment by cold360** [comment]
primo tv would be awesome lmao
