### ISSUE TITLE
WGN-TV

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#4613]
**Channel Name:** WGN Chicago News
**Country:** USA
**Language:** English
**Website:** https://wgntv.com/on-air/live-streaming/
**Stream URL (optional):** https://wgntv.com/on-air/live-streaming/
**Notes (optional):** Only Chicago Local News Feed.

**Comment by trancer1994** [comment]
https://dcs-live.apis.anvato.net/server/play/8AkZMW1F8omdfnE0/manifest.m3u8?encp=ADGoWbPjJ0hyzbWUN431OQ:A2W1rVks4LNkbRLQJ9iePfIJO94a8Yfzpn5brxxb44KxHSZJdJsia2Uy_YadKKSWFK-eK1mK0_XFf8J5CUrcfLCcPuL39OcVVxG40bTgh6sQsxJckS_58B3xTSfdE9FhMFHHnalNBOucZjqrGAzwwO8KEmYbIps9H7V5pz99EqAurDBbSJBRqrsnKaGPyplepxF5755ASYjDX7DkIwEaLoQeG0HlrAMFNNWgtzggpcRYdc5fQ1Lb42cAbijR0D-aGTF1GUQk0l4bU6xiB0GZ_GKuD1ocCG1l0VfSBxiZKKjSaIhY6xEb7RDgB0OcaVIi8RG1jDv7lV1Ue2CNi3Bfk2_MI3U1i7pUpXIoWKMZYdl9PmlklDF_qiQ6Q_GDa0ImxSYpH7XolxISEjQ4Qvyr_XcGteQV_sdPBIiVsUFLtumYn3xNv853965RrKqIJWOa2XFsMDNYexi-tzL0A91jtLPwgzpdPwYbf8kxieQX1EkMZWxqhqS-3af4OCJ_IeIoxSmCv8fnoM87OkQJchQ0Ba7cu2-Z2CqEkurZeZNVnM2Gh8cbsHPen8hsg4ChU9x6aqfQAxbheDG_Xyzc95Xz9rTYU220jZ02ZOVWlXRIGXSGuzOZa6XIiql4iu-_I5jv9hUxMwtdW6A4HOnyab4EXFr-nHXmHnkIkVz4M8p2-eFarikzsgqjrE5guZvVKL9-rmG9aDSacA8DM4jWkKs--Gkqd9vcnfFwi6oJarU3GL8&anvtrid=f6c4e71a7dfef2a547eef75894256073&anvauth=tb=0~te=1631980601~sgn=54f5ee88cf875337f895cd223a7e670a77e71070cfb79233bf3f743bb3cfeb13&t=1631980511&_vpng=0

Anvato link. May have to be streamlinked. Not sure.

**Comment by MapGuy11** [comment]
@trancer1994 Tokened

**Comment by MapGuy11** [comment]
@Central302 Try it out: https://cdn88.theus6tv.tk/united-states/wgn-tv-news.m3u8

**Comment by Central302** [comment]
This Link is Works. Thank You!

**Comment by MapGuy11** [comment]
#4624
