### ISSUE TITLE
Alanwar TV 2

### ISSUE THREAD

**Issue by Mennaruuk** [iptv-org/iptv#4615]
**Channel Name:** Al-Anwar 2
**Channel ID:** AlanwarTV2.kw
**Country:** KW
**Language:** Arabic
**Website:** https://anwartv2.com/
**Stream URL (optional):** https://player.castr.com/live_c043ce9040aa11ec94bb9191b5291a5e
**Notes (optional):** They have a livestream, ~~but it's tokenized.~~

**Comment by Mennaruuk** [comment]
Stream url: https://iframe.dacast.com/b/107085/c/491055

**Comment by Alstruit** [comment]
https://dacastmmd.mmdlive.lldns.net/dacastmmd/573db53ae58b429c8ec4d1d9563ab60f/playlist.m3u8

**Comment by freearhey** [comment]
Closed in favor #12262
