### ISSUE TITLE
Rewind TV East

### ISSUE THREAD

**Issue by Philblue7** [iptv-org/iptv#4617]
**Channel Name:** Rewind TV
**Country:** United States
**Language:** English
**Website:** https://rewindtv.com/
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by MapGuy11** [comment]
https://cdn87.theus6tv.tk/locals/NewYorkCity/wpix-dt4.m3u8

**Comment by Philblue7** [comment]
It works!

**Comment by MapGuy11** [comment]
#4626

**Comment by rosebud1974** [comment]
Hi,

I am new to m3u. I am trying to find a updated link for Rewind tv channel to add to my IPTV player. I appreciate the help.

**Comment by rosebud1974** [comment]
Hi,

I am new to m3u. I am trying to find a updated link for Rewind tv channel to add to my IPTV player. I was also wondering what happened to Catchy Comedy previously known as Decades it now says error playing channel. It is/was available on USA m3u.
I appreciate the help.
