### ISSUE TITLE
MBC 2

### ISSUE THREAD

**Issue by msaud** [iptv-org/iptv#4621]
**_Channel Name:_** MBC 2
**_Country:_** Not sure but it’s under the Arabic language 
**_Broken Link (from playlist):_** https://iptv-org.github.io/iptv/languages/ara.m3u
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** channel turns on but it goes in 1 min loop and it’s been stuck on the same loop for the past 2 weeks.  Similar to another MBC

**Comment by ksmehra** [comment]
correct, and there was a new link reported for this: https://blogs.livehdchanel.live/mbc-222/index.m3u8

and as of yesterday that new link has stopped working too

**Comment by LaneSh4d0w** [comment]
They moved to a Xtream-Codes service...

**Comment by ksmehra** [comment]
@LaneSh4d0w how do you play such a stream? im sorry, im new to this, just trying to get my way around

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w how do you play such a stream? im sorry, im new to this, just trying to get my way around

It's the same as other playlist files, but... it's not meant to stay long as far as we've seen.

**Comment by aboode13579** [comment]
so where can i watch it and mbc action and mbc max casue all of them wont work

**Comment by MohammedAlnuimi** [comment]
MBC it not working

**Comment by aboode13579** [comment]
> MBC it not working 

Why is there a way to fix it

**Comment by MohammedAlnuimi** [comment]
I don't have that or fix it
