### ISSUE TITLE
Antenna TV East

### ISSUE THREAD

**Issue by Philblue7** [iptv-org/iptv#4627]
**Channel Name:** Antenna TV East
**Country:** United States
**Language:** English
**Website:** https://antennatv.tv
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by what-a** [comment]
Antenna TV from Philadelphia PA is now on IPTV-org.
@MapGuy11 Another request we can close thanks to you!
![image](https://user-images.githubusercontent.com/88639906/150702459-707dec57-e31e-429b-be5b-d2830bfbc695.png)
