### ISSUE TITLE
mbc action

### ISSUE THREAD

**Issue by aowidat** [iptv-org/iptv#4633]
**Channel Name:** mbc action
**Country:** Saudi Arabia
**Language:** arabic
**Website:** https://www.mbc.net/channels/mbc-action
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by ksmehra** [comment]
mbc already present in the saudia arabia, uae and a couple other channels lists. currently its broken though. did you create this issue to report a broken link?

**Comment by aowidat** [comment]
> 
> 
> mbc already present in the saudia arabia, uae and a couple other channels lists. currently its broken though. did you create this issue to report a broken link?

it was in the list, but now not anymore. it did not know, it its broken, or just removed, i just can not find it in the new list.
