### ISSUE TITLE
RTP

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#4640]
RPT Madeira,RTP1 (480p),RPT2 (504p), RPT3 (504p)[Not 24/7] and África (504p) from Portugal have a problem. The message: An error occurred: UnrecognizedInputFormatException. Thank you.

**Comment by freearhey** [comment]
Try opening this playlist `https://iptv-org.github.io/iptv/countries/pt.m3u` in VLC player and run these channels that way.

**Comment by spotanjo3** [comment]
Strange. Açores works in VLC Player but not tivimate. I test other IPTV team of Acores works and different from yours working fine on tivimate.

**Comment by freearhey** [comment]
The thing is that all these links have custom user-agent in the playlist, which not all players use.
https://github.com/iptv-org/iptv/blob/569c149de31021741b5cdf32465dd2205e58c69e/channels/pt.m3u#L24-L26

**Comment by Dum4G** [comment]
Confirmed working in VLC

**Comment by spotanjo3** [comment]
Yeah. I dont used VLC for my Sony TV Android. I test it on my computer and confirmed working but I noticed some players worked fine and some don't. So I prefer TV Android only. Keep up the good work and thank you!

**Comment by Dum4G** [comment]
If you want Android TV recommendations I would suggest Televizo and OTT Navigator. Tbh I'm surprised that Tivimate ignores user-agents

**Comment by spotanjo3** [comment]
Yeah. I used OTT Navigator and that's why I said some works and dont dont. I liked Tivimate the more but I will test more on OTT Navigator. Thank you.
