### ISSUE TITLE
TVS

### ISSUE THREAD

**Issue by SonicPhoon** [iptv-org/iptv#4656]
**Channel Name:** TVS
**Country:** Malaysia
**Language:** Malay, Chinese, Iban, English
**Website:** https://tvstv.my
**Stream URL (optional):** xxx
**Notes (optional):** missing from Malaysia tv channel playlist

**Comment by Sphinxroot** [comment]
I need more info  please , to be sure of the channel requested

for now i got this
https://tvstv.my/live/
and
https://selangortv.my/

**Comment by jkemp814** [comment]
It's still there. Just flagged as offline.

#EXTINF:-1 tvg-id="TVS.my" tvg-country="MY" tvg-language="" tvg-logo="" group-title="",TVS (576p) [Offline]
https://agsplayback01.astro.com.my/CH1/master_AGS_TVS.m3u8

**Comment by Dum4G** [comment]
> It's still there. Just flagged as offline.

Shows 403 for me

**Comment by jkemp814** [comment]
Yes, same here. I was pointing out the reason it's not showing in the list is, it's flagged as offine.

**Comment by SonicPhoon** [comment]
welp
we can only pray for the returning of TVS

Meanwhile ViuTV6 (HK) also facing this problem too

**Comment by SonicPhoon** [comment]
topic close request
problem resolved
![Uploading Screenshot_2021-12-07-07-51-48-01_aa2f42c2af516ac152e4b8ad88b4154a.jpg…]()

**Comment by SonicPhoon** [comment]
Topic Close Request due to Problem Resolved
![Screenshot_2021-12-07-07-51-48-01_aa2f42c2af516ac152e4b8ad88b4154a](https://user-images.githubusercontent.com/91185587/144941362-21df8acb-763c-4a13-86fe-159cfede68ff.jpg)
