### ISSUE TITLE
Azam sports please

### ISSUE THREAD

**Issue by ahmedzooo** [iptv-org/iptv#4666]
**Channel Name:** Azam sports
**Country:** Tanzania
**Language:** Swahili
**Website:** azamtvmax.com
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Dum4G** [comment]
Closed in favor of https://github.com/iptv-org/iptv/issues/2730

**Comment by ahmedzooo** [comment]
Please i own for account for Azamtvmax.apk

**Comment by Dum4G** [comment]
I can move this issue to Discussions, but I can't guarantee you that we will be able to retrieve links from an app.
