### ISSUE TITLE
Ken TV

### ISSUE THREAD

**Issue by Niyasmkkv** [iptv-org/iptv#4669]
**Channel Name:** Ken TV
**Country:** India
**Language:** Malayalam
**Website:** 
**Stream URL (optional):** "KEN TV" http://www.uomotv.live/live-tv/ken-tv.html
**Notes (optional):** xxx

**Comment by Dum4G** [comment]
https://stream.ufworldind.in/kentvlive/smil:kentv.smil/chunklist_w1473302160_b456000_sleng.m3u8
