### ISSUE TITLE
Bloomberg TV+ (720p)

### ISSUE THREAD

**Issue by iumyidol** [iptv-org/iptv#4696]
**_Channel Name:_** Bloomberg TV+ (720p)
**_Country:_** US (probably)
**_Broken Link (from playlist):_** Business or Index, the channel just disappeared
**_Possible Replacement (optional):_** Bloomberg TV+ (2160p) but the resolution too high my machine can hardly support, and network
**_Notes (optional):_** The channel was there for a very long time and all of a sudden it just disappeared, please help me recover this or if anyone know an alternative link please let me know (only bb TV+, which has the stats as the side)

**Comment by Sphinxroot** [comment]
https://www.bloomberg.com/media-manifest/streams/phoenix-us.m3u8
#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=600000,RESOLUTION=640x360,CODECS="avc1.64001f,mp4a.40.2"
https://liveprodusphoenixeast.akamaized.net/USPhx-HD/Channel-TX-USPhx-AWS-virginia-1/Source-USPhx-16k-1-s6lk2-BP-07-06-mOzAf8ZuNC8_live.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3000000,RESOLUTION=1920x1080,CODECS="avc1.64002a,mp4a.40.2"
https://liveprodusphoenixeast.akamaized.net/USPhx-HD/Channel-TX-USPhx-AWS-virginia-1/Source-USPhx-16k-1-s6lk2-BP-07-02-81ykIWnsMsg_live.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2400000,RESOLUTION=1280x720,CODECS="avc1.640020,mp4a.40.2"
https://liveprodusphoenixeast.akamaized.net/USPhx-HD/Channel-TX-USPhx-AWS-virginia-1/Source-USPhx-16k-1-s6lk2-BP-07-03-0Yn1cQZHOtP_live.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1500000,RESOLUTION=1280x720,CODECS="avc1.640020,mp4a.40.2"
https://liveprodusphoenixeast.akamaized.net/USPhx-HD/Channel-TX-USPhx-AWS-virginia-1/Source-USPhx-16k-1-s6lk2-BP-07-04-jZwxsD5tnuA_live.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=400000,RESOLUTION=480x272,CODECS="avc1.64001e,mp4a.40.2"
https://liveprodusphoenixeast.akamaized.net/USPhx-HD/Channel-TX-USPhx-AWS-virginia-1/Source-USPhx-16k-1-s6lk2-BP-07-07-4Qr5sEpfNFG_live.m3u8


https://www.bloomberg.com/media-manifest/streams/us.m3u8

#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=1000000,RESOLUTION=1280x720,CODECS="avc1.4d4028,mp4a.40.2"
https://liveproduseast.akamaized.net/us/Channel-USTV-AWS-virginia-1/Source-USTV-1000-1_live.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=700000,RESOLUTION=640x360,CODECS="avc1.4d4028,mp4a.40.2"
https://liveproduseast.akamaized.net/us/Channel-USTV-AWS-virginia-1/Source-USTV-700-1_live.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=440000,RESOLUTION=480x270,CODECS="avc1.4d4028,mp4a.40.2"
https://liveproduseast.akamaized.net/us/Channel-USTV-AWS-virginia-1/Source-USTV-440-1_live.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=240000,RESOLUTION=320x180,CODECS="avc1.4d4028,mp4a.40.2"
https://liveproduseast.akamaized.net/us/Channel-USTV-AWS-virginia-1/Source-USTV-240-1_live.m3u8



to be tested  .. work here :)  hope it do

**Comment by Sphinxroot** [comment]
here a couple more to be added 
https://www.bloomberg.com/media-manifest/streams/asia.m3u8
https://www.bloomberg.com/media-manifest/streams/us-event.m3u8
https://liveproduseast.global.ssl.fastly.net/pol/Channel-POL-AWS-virginia-1/Source-POL-240-1_live.m3u8
https://liveproduseast.akamaized.net/us/Channel-USTV-AWS-virginia-1/Source-USTV-240-1_live.m3u8
https://www.bloomberg.com/media-manifest/streams/eu.m3u8
https://www.bloomberg.com/media-manifest/streams/aus.m3u8

**Comment by freearhey** [comment]
@iumyidol The channel should reappear in the next update.

**Comment by iumyidol** [comment]
The TV+ above does not work for me ... thanks anyway
