### ISSUE TITLE
Suggestion ::: Teletext

### ISSUE THREAD

**Issue by chezsick** [iptv-org/iptv#470]
Is possible to add teletext?

three possibility ::
1. add url teletext from image or url website teletext serivce
2. add script generator (in python?) teletext from website
3. add teletext inside repository (editor :: http://edit.tf)

sick.

**Comment by freearhey** [comment]
If I understand correctly, so that the player can display teletext, it must be part of the stream. At least I could not find a service that would provide teletext separately. Fix me if I am wrong.

**Comment by chezsick** [comment]
i think a player can't show teletext with iptv except if player receive analog tv, but i found example teletext service ::: ard :: https://www.ard-text.de/

but why not to
create a folder contain script (python or nodejs) to generate a teletext image that downloading website channel for information
OR
create a folder contain teletext by the community

**Comment by freearhey** [comment]
@chezsick could you provide some example of a teletext file?

**Comment by chezsick** [comment]
for me a teletext file is a image as .png or a .tti file examples ::::::: https://github.com/opless/teefax-mirror

the font for teletext is European Teletext :::::::: https://www.dafont.com/european-teletext.font

**Comment by freearhey** [comment]
@chezsick could you also say which app do you use to watch IPTV with teletext?

**Comment by chezsick** [comment]
nothing, and that no exist in my knowledge, but you don't want to add a folder? else you add url from teletext service of the channel.

**Comment by freearhey** [comment]
@chezsick so what's the point of teletext in this repository if it cannot be used with iptv playlists?
