### ISSUE TITLE
MMA TV & Humanity TV (Samsung / Alchemy)

### ISSUE THREAD

**Issue by robocopz** [iptv-org/iptv#4714]
Channel Name: MMA TV
Country: UK

Alchimie has changed all Samsung links. None of them works (mmatv, humanity, etc.)

https://alchimie-humanity-2-gb.samsung.wurl.com/manifest/playlist.m3u8
https://alchimie-mmatv-1-gb.samsung.wurl.com/manifest/playlist.m3u8

**Comment by jkemp814** [comment]
Added MMA TV to Local Now (us_localnow.m3u) US
