### ISSUE TITLE
Heroes & Icons East

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#4715]
**Channel Name:** Heroes and Icons
**Country:** USA
**Language:** English
**Website:** https://www.handitv.com/
**Stream URL (optional):** 
**Notes (optional):** This Channel is One of OTA Channel in USA

**Comment by LaneSh4d0w** [comment]
@MapGuy11 maybe, if you get this from where you are ?

**Comment by MapGuy11** [comment]
> @MapGuy11 maybe, if you get this from where you are ?

I'll see if I can get something.

**Comment by Central302** [comment]
It Looks Like No Way to This Stream. I Close This Issuse.
