### ISSUE TITLE
Dream TV

### ISSUE THREAD

**Issue by zupersponge** [iptv-org/iptv#4716]
**Channel Name:** Dream TV
**Channel ID:** DreamTV.mn
**Country:** Mongolia
**Language:** Mongolian
**Website:** https://www.facebook.com/DreamTVMongolia/
**Notes (optional):**

**Comment by LaneSh4d0w** [comment]
I'll need to check Facebook API to see if can always get the last stream.

**Comment by freearhey** [comment]
Closed in favor #12259
