### ISSUE TITLE
Star Sports Select 2 HD

### ISSUE THREAD

**Issue by MonuMia1** [iptv-org/iptv#4743]
Star Sports Select 2 HD m3u8 links please Thank You

**Channel Name:** Star Sports Select 2 HD
**Country:** INDIA
**Language:** English
**Website:** xxx
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment]
Please look after already made issues before making a new one.

Duplicate of #1992 (channel was already been asked before)
