### ISSUE TITLE
Broken : WPSG-TV

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#4753]
**_Channel Name:_** WPSG-TV
**_Country:_** USA
**_Broken Link (from playlist):_** https://cdn007.the6tv.duckdns.org:2443/the6tv-ota/h264/philadelphia/WPSG-DT1/playlist.m3u8
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** xxx
Link not Working via iPhone and GSE Smart Player.

**Comment by Dum4G** [comment]
![Screenshot_20210927-021622](https://user-images.githubusercontent.com/5430116/134827510-8e534fa6-9e2c-49f2-8c4b-be44935a1dbd.jpg)
VLC Mobile, Android

**Comment by Central302** [comment]
i'm sorry, but it Works Now. Thanks!
