### ISSUE TITLE
Broken : WPSG

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#4779]
**_Channel Name:_** WPSG-TV
**_Country:_** USA
**_Broken Link (from playlist):_** https://cdn007.the6tv.duckdns.org:2443/the6tv-ota/h264/philadelphia/WPSG-DT1/playlist.m3u8
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** xxx
Stream Down Again. Not Works in iPhone and GSE Player.

**Comment by Sphinxroot** [comment]
https://cwphilly.cbslocal.com/live/

https://cbsn-phi.cbsnstream.cbsnews.com/out/v1/5c9ad3e215984b0e9ad845b335216b72/master.m3u8

https://dai.google.com/linear/hls/event/R2Kw0uvnQIW7fUmOseurzA/master.m3u8
