### ISSUE TITLE
NBC 4 Los Angeles - Down

### ISSUE THREAD

**Issue by mmkogut** [iptv-org/iptv#4784]
**_Channel Name:_** NBC 4 Los Angeles
**_Country:_** US
**_Broken Link (from playlist):_** https://cdnapisec.kaltura.com/p/2630451/sp/2630451/playManifest/entryId/1_61e7x33e/deliveryProfileId/672/protocol/https/format/applehttp/a.m3u8 
**_Possible Replacement (optional):_** https://www.nbclosangeles.com/news/watch-the-nbc4-news/2273356/
**_Notes (optional):_** The provided link is their direct stream from their site, but is "only available during scheduled newscasts" (sub-optimal).

**Comment by mmkogut** [comment]
The link in the channels file is broken ("cdnapisec.kalture.com") and currently not working at anytime.

The NBC site I listed is a part-time alternative.

**Comment by LaneSh4d0w** [comment]
https://link.theplatform.com/s/Yh1nAC/y2SQ3OR9LVim?mbr=true&assetTypes=LegacyRelease&fwsitesection=ots_knbc_news&fwNetworkID=382114&pprofile=ots_desktop_html&sensitive=false&w=848&h=477&rnd=6906971&mode=LIVE&format=SMIL&tracking=false&formats=MPEG-DASH+widevine,M3U+appleHlsEncryption,M3U+none,MPEG-DASH+none,MPEG4,MP3&vpaid=script&schema=2.0&sdk=PDK+6.1.3

**Comment by mmkogut** [comment]
I believe this is a full functioning alternative:
https://cdn87.theus6tv.tk/locals/SoCal/knbc-dt1.m3u8

**Comment by LaneSh4d0w** [comment]
Very much possible, @MapGuy11 is behind this stream. Tagging him so that he can explain. With a bit of luck he might even get the one you're talking about.

**Comment by MapGuy11** [comment]
> I believe this is a full functioning alternative: https://cdn87.theus6tv.tk/locals/SoCal/knbc-dt1.m3u8

Yes this is live KNBC-DT1

**Comment by Sphinxroot** [comment]
From Site
Live video will be provided below during NBC4 News broadcasts
Program Note: Today in LA Weekend will stream here Saturday at 7 a.m.

**Comment by MapGuy11** [comment]
> From Site Live video will be provided below during NBC4 News broadcasts Program Note: Today in LA Weekend will stream here Saturday at 7 a.m.

Yes but they put the times on the stream normally. Or a test card.

**Comment by LaneSh4d0w** [comment]
The link that was given is the NBC *News* link. There's another NBC Live TV link, but you need an account to get it.

**Comment by MapGuy11** [comment]
This is what the stream is right now
![Uploading Screenshot_20210928-145926.png…]()

**Comment by mmkogut** [comment]
I editted channels/us.m3u to replace NBC 4 Los Angeles with MapGuy11's stream and created a pull request

**Comment by jkemp814** [comment]
We need to be careful, editing existing newscast streams in favor of live full schedule streams. A new channel should have been added. The existing newscast stream could have been fixed.

**Comment by LaneSh4d0w** [comment]
I could, but however it sounds like a pain in the *** to have the thing I wanted to have.

**Comment by mmkogut** [comment]
To be clear, 
The original stream was a full schedule OTA stream as well.
Newscast stream was only the half-way recommended fix I found until finding a better full 1:1 replacement fix.

If I overstepped, I do sincerely apologize.
It was just a channel I frequently used for where we live and was hurting without it.
