### ISSUE TITLE
KTLA5 and KCAL9 

### ISSUE THREAD

**Issue by madtom75** [iptv-org/iptv#479]
Hi I’m desperately looking for KTLA5 and KCAL9 IPTV, any help?

**Comment by freearhey** [comment]
- [x] KTLA5
https://github.com/iptv-org/iptv/blob/5d3093a8c51d12a9b2fd05e04c7aae67f9c36a77/channels/us.m3u#L1514-L1515
- [ ] KCAL 9 (KCAL-TV)

**Comment by freearhey** [comment]
Closed in favor #1942
