### ISSUE TITLE
Add geo-blocked broadcasts (continuation)

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#480]
First part: https://github.com/iptv-org/iptv/issues/379#issuecomment-540117333

**Comment by freearhey** [comment]
@DocSniper great idea to use TOR to bypass geo-blocking! 

For those who decide to implement such a check, you can find the source code of the current version of the script in `test/index.js`. Feel free to use it if needed.

**Comment by DocSniper** [comment]
@freearhey I hope the idea helps :-)

I don't know about JS, but with Wget and curl it's easy to use a proxy:
[https://ec.haxx.se/usingcurl-proxies.html](https://ec.haxx.se/usingcurl-proxies.html)
[https://www.gnu.org/software/wget/manual/html_node/Proxies.html#Proxies](https://www.gnu.org/software/wget/manual/html_node/Proxies.html#Proxies)
