### ISSUE TITLE
Prince Kids

### ISSUE THREAD

**Issue by WakeAP** [iptv-org/iptv#4806]
Channel Name: ART PRINCE KIDS 
Country: Kosovo 
Language: Albanian 
Website: https://artmotion.net/
Notes (optional): Please Add This Channel

**Comment by LaneSh4d0w** [comment]
Since Eutelsat 16A (16°E), 2020-08-25
Tring Digital: Prince Kids has left 11139.00MHz, pol.H (DVB-S2 SID:4718 PID:46[MPEG-4]/47 aac Albanian), it is no longer transmitted by satellite in Europe.
