### ISSUE TITLE
TV Cultura

### ISSUE THREAD

**Issue by lgissoni** [iptv-org/iptv#4825]
**Channel Name:** TV Cultura
**Channel ID:** TVCulturaNacional.br
**Country:** Brazil
**Language:** Portuguese
**Website:** https://cultura.uol.com.br/
**Stream URL (optional):** https://cultura.uol.com.br/aovivo/
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
https://www.dailymotion.com/video/x7wur7g private video
but this work
https://stream-03.nyc.dailymotion.com/sec(RiWEtJG0nU_F5iuiUOWAlwol97DHiBev0J_enXWldnQ)/dm/3/x7wur7g/s/live-3.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/198d0527f073c81119ccceaebdede8e79f542028/streams/br.m3u#L175-L176
