### ISSUE TITLE
CNN Brasil

### ISSUE THREAD

**Issue by lgissoni** [iptv-org/iptv#4826]
**Channel Name:** CNN Brasil
**Country:** Brazil
**Language:** Portuguese
**Website:** https://www.cnnbrasil.com.br/
**Stream URL (optional):** https://www.cnnbrasil.com.br/ao-vivo/
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
https://www.youtube.com/channel/UCvdwhh_fDyWccR42-rReZLw/live

**Comment by fershady** [comment]
https://www.youtube.com/c/CNNbrasil/live
