### ISSUE TITLE
Rede Globo SP

### ISSUE THREAD

**Issue by lgissoni** [iptv-org/iptv#4827]
**Channel Name:** Rede Globo SP
**Channel ID:** TVGloboSaoPaulo.br
**Country:** Brazil
**Language:** Portuguese
**Website:** https://redeglobo.globo.com/sao-paulo/
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by AntiPontifex** [comment]
Defunct: please close.

**Comment by freearhey** [comment]
Closed in favor #12256
