### ISSUE TITLE
TV Brasil

### ISSUE THREAD

**Issue by eltoncomp** [iptv-org/iptv#4830]
**Channel Name:** TV Brasil
**Country:** Brazil
**Language:** Portuguese
**Website:** https://tvbrasil.ebc.com.br
**Stream URL (optional):** https://play.ebc.com.br/tv/tv-brasil
**Notes (optional):** TV Brasil is the national public television of Brazil.

**Comment by Sphinxroot** [comment]
dailymotion  private geo video
