### ISSUE TITLE
TV Brasil 2

### ISSUE THREAD

**Issue by eltoncomp** [iptv-org/iptv#4831]
**Channel Name:** TV Brasil 2
**Country:** Brazil
**Language:** Portuguese
**Website:** https://tvbrasil.ebc.com.br
**Stream URL (optional):** https://play.ebc.com.br/tvs
**Notes (optional):** It is the secondary channel of TV Brasil (formerly it was the government channel NBR).

**Comment by Sphinxroot** [comment]
https://www.dailymotion.com/video/x7wur7g  private video  + geo

**Comment by eltoncomp** [comment]
http://origin-02.nxplay.com.br/TV_BRASIL_2/index.m3u8

**Comment by freearhey** [comment]
Closed in favor of #13141
