### ISSUE TITLE
TV Pública

### ISSUE THREAD

**Issue by lgissoni** [iptv-org/iptv#4833]
**_Channel Name:_** TV Pública
**_Country:_** Argentina
**_Broken Link (from playlist):_** https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/user/TVPublicaArgentina/live
**_Possible Replacement (optional):_** https://www.tvpublica.com.ar/vivo
**_Notes (optional):_** xxx

**Comment by Sphinxroot** [comment]
https://iptv.dc-team.com/query?url=https://www.youtube.com/user/TVPublicaArgentina/live

**Comment by taodicakhia** [comment]
> https://iptv.dc-team.com/query?url=https://www.youtube.com/user/TVPublicaArgentina/live

This is already in #4780, so you can close issue

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/198d0527f073c81119ccceaebdede8e79f542028/streams/ar.m3u#L293-L294
