### ISSUE TITLE
Add: 2M TV

### ISSUE THREAD

**Issue by Gitalifr** [iptv-org/iptv#4857]
**Channel Name:** 2M TV
**Country:** Morocco
**Language:** Arabic
**Website:** https://maroc2m.live/
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by freearhey** [comment]
Already in playlist:
https://github.com/iptv-org/iptv/blob/61abcf0241e1efd61d4c101e2985d251aad78524/channels/ma.m3u#L2-L3
