### ISSUE TITLE
Add :  Tele Maroc

### ISSUE THREAD

**Issue by Gitalifr** [iptv-org/iptv#4858]
**Channel Name:** Tele Maroc
**Country:** Morocco
**Language:** Arabic
**Website:** https://www.telemaroc.tv/liveTV
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by freearhey** [comment]
Already in playlist:
https://github.com/iptv-org/iptv/blob/61abcf0241e1efd61d4c101e2985d251aad78524/channels/ma.m3u#L48-L49
