### ISSUE TITLE
Assadissa

### ISSUE THREAD

**Issue by Gitalifr** [iptv-org/iptv#4859]
**Channel Name:** Assadissa
**Country:** Morocco
**Language:** Arabic
**Website:** http://www.assadissatv.ma/mobile/index.php?lang=fr
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Mennaruuk** [comment]
[Isn't Assadissa already added?](https://github.com/iptv-org/iptv/blob/master/channels/ma.m3u)
