### ISSUE TITLE
iFILM English

### ISSUE THREAD

**Issue by samg80** [iptv-org/iptv#4870]
**Channel Name:** **ifilm English**
**Country:** Iran
**Language:** Farsi (in dubbed or English subtitle)
**Website:** https://en.ifilmtv.ir/
**Stream URL (optional):** xxx
**Notes (optional):** I have the full iptv-org and indexed by country. I used to have the ifilm English channel but it has disappeared! I have updated the IPTV Client a few times and I do see this channel (and some other ones) missing.

**Comment by LaneSh4d0w** [comment]
https://live1.presstv.ir/live/ifilmen.m3u8 =)

**Comment by samg80** [comment]
I appreciate you all jumped on this so fast. I just removed the IPTV-Org link and added it again, I still do not see this channel!
I am on Kodi 19 Matrix for FireTV. 
Any recommendations? I am using PVR Simple Client.

**Comment by samg80** [comment]
Someone told me that the link will be updated tomorrow. Thank you all.

**Comment by LaneSh4d0w** [comment]
I'm the same person that told you it'll be there tomorrow. Right now, on the iFilm English stream, it seems that there's a glitch on the playlists. The Persian 2 went back online, it might only be a matter of time. Link is in the iq playlist, but we'll wait until it works again to reinstate it onto the playlists.

**Comment by Sphinxroot** [comment]
the adaptative 1 dont work for me

https://live1.presstv.ir/live/ifilmen_360p/index.m3u8
this one does

**Comment by LaneSh4d0w** [comment]
Got nothing on my side to be honest. Had like 1 second of stuttered audio then nothing.

**Comment by jkemp814** [comment]
https://live1.presstv.ir/live/ifilmen_360p/index.m3u8

[NULL @ 0x7f3a64601940] non-existing PPS 0 referenced    0B f=0/0   
[h264 @ 0x7f3a648d2a40] non-existing PPS 0 referenced
[h264 @ 0x7f3a648d2a40] decode_slice_header error
[h264 @ 0x7f3a648d2a40] no frame!

Just keep looping, trying to connect.

**Comment by jkemp814** [comment]
[hls @ 0x7fcff4000bc0] Cannot get correct #EXTINF value of segment https://live1.presstv.ir/live/ifilmen_360p/11983170.ts, set to default value to 1ms.

**Comment by Sphinxroot** [comment]
only the 360 load ive put network cache at 2k  but it buffer a bit over time
https://i.imgur.com/ijb9xts.png

#EXTINF:-1 ,ifilm English
https://live1.presstv.ir/live/ifilmen.m3u8 
#EXTINF:-1 ,ifilm English (360p)
https://live1.presstv.ir/live/ifilmen_360p/index.m3u8
#EXTINF:-1 ,ifilm English (240p)
https://live1.presstv.ir/live/ifilmen_360p/ifilmen_240p/index.m3u8
#EXTINF:-1 ,ifilm English (160p)
https://live1.presstv.ir/live/ifilmen_360p/ifilmen_160p/index.m3u8

**Comment by LaneSh4d0w** [comment]
There we go, adaptive seems to breath again. Changing its state to Not 24/7.

**Comment by samg80** [comment]
FYSA,
I still do not see the ifilm channel added back to the list.
I do see NRT is added but does not have a sound - I checked all the setting
and the channel is not on mute, other channels have sound.

**Comment by samg80** [comment]
I checked again just a few minutes ago, I still do not see the iFilm
channel.
Thank you

**Comment by LaneSh4d0w** [comment]
It's still down on latest testings.

**Comment by LaneSh4d0w** [comment]
![image](https://user-images.githubusercontent.com/30985701/136673103-d6fd6012-405d-4256-a9fe-8795af773d45.png)

Seems to work back again now.

**Comment by samg80** [comment]
I still don't see it.
Are you sure that is thee English version?
Look at the attached pic, I just took it.

**Comment by samg80** [comment]
Last check as of right now, channel is still missing

**Comment by samg80** [comment]
Is this channel going to be added back or the case is closed?
