### ISSUE TITLE
NRT TV

### ISSUE THREAD

**Issue by samg80** [iptv-org/iptv#4871]
**Channel Name:** NRT TV 
**Country:** Iraq
**Language:** Kurdish
**Website:** http://www.nrttv.com/#
**Stream URL (optional):** http://www.nrttv.com/streamNRT.aspx
**Notes (optional):** I have the full iptv-org and indexed by country. I used to have the NRT TV channel but it has disappeared! I have updated the IPTV Client a few times and I do see this channel (and some other ones) missing.

**Comment by TwanstCodess** [comment]
ززز
