### ISSUE TITLE
Imagen TV Rioja

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#4882]
**Channel Name:** Imagen TV
**Country:** PE
**Language:** Spanish
**Website:** Not yet
**Stream URL (optional):** Unknow (see below)
**Notes (optional):** Like Canal E, this channel have not a official web site. But this channel has a app: https://play.google.com/store/apps/details?id=imagen.tv3 for live tv. And social network: https://www.facebook.com/Imagen-TV-Canal-5-Rioja-104338684346756/

**Comment by Sphinxroot** [comment]
http://191.97.56.183:1935/imagentv/imagentv/playlist.m3u8 720p

**Comment by jkemp814** [comment]
> http://191.97.56.183:1935/imagentv/imagentv/playlist.m3u8 720p

it works

**Comment by sguinetti** [comment]
It works too.
