### ISSUE TITLE
Nickelodeon East

### ISSUE THREAD

**Issue by AriesTropixDev** [iptv-org/iptv#4901]
**_Channel Name:_** Nickelodeon East (360p)
**_Country:_** US
**_Broken Link (from playlist):_** http://31.220.41.88:8081/live/us-nick.stream/playlist.m3u8
**_Notes (optional):_** This has an HTTP header and from what I know hls players only supports HTTPS. So The Problem is More than Likely The HTTP Header.

**Comment by Central302** [comment]
![NickEastProf](https://user-images.githubusercontent.com/86145713/136035894-37c0915f-dad1-4f7a-aba4-1cc63fa23fc8.PNG)
Working on FireFox Extension and Pot Player and GSE Smart TV Via iPhone.

**Comment by trancer1994** [comment]
Works for me. 

Also, what is 31.220.41.88? Is it someone restreaming channels?

**Comment by Mennaruuk** [comment]
Works on VLC, but not on JWPlayer's stream tester.

**Comment by LaneSh4d0w** [comment]
> 
> 
> Works for me.
> 
> Also, what is 31.220.41.88? Is it someone restreaming channels?

stream.tvtap.live

**Comment by AriesTropixDev** [comment]
are they any online iptv players that could work with that?

**Comment by Mennaruuk** [comment]
> are they any online iptv players that could work with that?

http://stream-tester.jwplayer.com
