### ISSUE TITLE
TV Surymar

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#4914]
**Channel Name:** TV Surymar
**Channel ID:** TVSurymar.pe
**Country:** PE
**Language:** Spanish
**Website:** http://www.televisionsurymar.com/ (updated)
**Stream URL (optional):** Unknow (see below)
**Notes (optional):** This channel has a app for stream based of Opencaster: https://play.google.com/store/apps/details?id=radio.tvsurymar for live tv. And social network: https://m.facebook.com/televisionsurymar/

**Comment by sguinetti** [comment]
You are right, it only transmits some programs and I think that is no guarantee that this channel will work optimally.

**Comment by LaneSh4d0w** [comment]
Sadly we can't deal with Opencaster links. Closing.
