### ISSUE TITLE
Janapriyam TV

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#4918]
**_Channel Name:_** Janapriyam
**_Channel ID:_** JanapriyamTV.in
**_Country:_** IN
**_Broken Link (from playlist):_** https://jio.instream.ml/jio.php?c=Janapriyam_News&e=.m3u8&q=400
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** xxx

**Comment by LaneSh4d0w** [comment]
From their website : https://cdn.janapriyam.in/janapriyam_jio/index.m3u8

**Comment by freearhey** [comment]
Closed in favor #12254
