### ISSUE TITLE
Opinion of users needed: Should we add streams that not work in all apps?

### ISSUE THREAD

**Issue by boomski** [iptv-org/iptv#492]
We noticed that some of the stream we wanted to add do not work in all apps.

For example: https://rcnhd.cdn.net.co/live01/rcnhd_720p.m3u8
This URL  - we tested in VLC -> Stream is _**Not Working**_
                - Tested in Kodi 18.6  -> Stream is Working
                - Tested on https://streamtest.in/ -> Stream is Working
So with the stream itself is nothing wrong only on the vlc platform it does not want to play.
Should we add streams like this to the playlists and add something behind the channelname like [NO VLC] or should we not add such streams?

Would like to hear the opinion of other users.

**Comment by drezim2001** [comment]
I say add the streams. I plan on using a app different from VLC. My VLC is not play nice with EPG files.

**Comment by nathanmuccino** [comment]
Yes, I say add them with the 'No VLC' label

**Comment by freearhey** [comment]
@boomski Well then let's add such streams to playlists. But let it be only those links that do not work only in one application. Otherwise, we just get tired of checking everything. Okay?

**Comment by mehmetali82** [comment]
bazı yayınlar açılmıyor ben isterımkı hepsı açılsın türkıye şifrelı kanallarda olursa memnum olurum

**Comment by boomski** [comment]
@freearhey  Okay for me

**Comment by freearhey** [comment]
Well, then I'm closing this issue for now

**Comment by mehmetali82** [comment]
some publications do not open I would like to open all of them in turkey encrypted channels I would be glad

**Comment by freearhey** [comment]
@mehmetali82 I'm sorry, but I don’t understand how this is related to this topic? 

If you have any problems with the channels feel free to create a new issue and do not forget to specify channel names that do not work.
