### ISSUE TITLE
Nickelodeon East

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#4927]
**_Channel Name:_** Nickelodeon East (TVTap) 
**_Country:_** USA
**_Broken Link (from playlist):_** http://31.220.41.88:8081/live/us-nick.stream/playlist.m3u8
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** Link said "Forbidden".

**Comment by AriesTropixDev** [comment]
I have the same problem someone help him! Its something dealing with the HTTP Header.
