### ISSUE TITLE
BBC One

### ISSUE THREAD

**Issue by nandorj78** [iptv-org/iptv#4932]
Hi, could you please add BBC One to the UK list?

**Channel Name:** BBC One
**Country:** UK
**Language:** English
**Website:** https://www.bbc.co.uk/bbcone
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
http://93.190.139.35:8278/streams/d/bbc1_antik/playlist.m3u8

**Comment by Sphinxroot** [comment]
http://93.190.139.35:8278/streams/d/bbcworldnews_antik/playlist.m3u8

could be mixed  seem to be a tvtap clone or something else

and the tvtap link dont work anymore

**Comment by nandorj78** [comment]
Any news regarding this?
