### ISSUE TITLE
BBC Two

### ISSUE THREAD

**Issue by nandorj78** [iptv-org/iptv#4933]
Hi, could you please add BBC Two to the UK list?

**Channel Name:** BBC Two
**Country:** UK
**Language:** English
**Website:** https://www.bbc.co.uk/bbctwo
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
http://93.190.139.35:8278/streams/d/bbc2_antik/playlist.m3u8
