### ISSUE TITLE
Nickelodeon East

### ISSUE THREAD

**Issue by nickpythonluajava** [iptv-org/iptv#4952]
**Channel Name:** Nickelodeon East
**Channel ID:** NickelodeonEast.us
**Country:** United States Of America
**Language:** English
**Website:** https://nick.com
**Stream URL (optional):** xxx
**Notes (optional):** Other stream does not work (#4927)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/13d2f470b7e5b647c0d24d4b6897c651d4b52971/streams/us.m3u#L733-L734
