### ISSUE TITLE
Fajer TV 1

### ISSUE THREAD

**Issue by l-ben** [iptv-org/iptv#4976]
**Channel Name:** alfajer tv 1 
**Channel ID:** FajerTV1.ps
**Country:** palestine
**Language:** arabic
**Website:** http://tv.alfajertv.com/live-westbank-1-a.php
**Stream URL (optional):**

**Comment by Alstruit** [comment]
HD 1 [Geo-blocked]
https://vstream2.hadara.ps:8443/AlfajertvHDFull_web/web/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MTAvMS8yMDIyIDQ6MTA6MTMgQU0maGFzaF92YWx1ZT1oWGxuWmFUdFVFQjZQZjFYd1hxaGtRPT0mdmFsaWRtaW51dGVzPTE4MCZpZD0zZDAxZjQ1MGU5MDQ5NjRiYTczZjJhMDgwMGQxMTAxNA==

1 [Geo-blocked]
https://vstream4.hadara.ps:8443/AlfajertvHD1_web/web/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MTAvMS8yMDIyIDQ6MTA6NDEgQU0maGFzaF92YWx1ZT0rZldKWjA3cklWMjlRaTZ3d215OHlRPT0mdmFsaWRtaW51dGVzPTE4MCZpZD02MDNmOWQxNmExOWYzNTE4NWI3YWY5Zjc3MjNiNGU2Mg==

International
https://vstream3.hadara.ps:8443/AlfajertvUN_web/web/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MTAvMS8yMDIyIDQ6MDk6MjEgQU0maGFzaF92YWx1ZT1YbU5RMGRQYVRhaFNmYTVtQVFPd3lRPT0mdmFsaWRtaW51dGVzPTE4MCZpZD1hNjRmN2EyMDRlNDc0MTRjNDU3MGVjNGU5YTI0NjMyYg==

**Comment by freearhey** [comment]
Closed in favor #12253
