### ISSUE TITLE
xxx Request Channels

### ISSUE THREAD

**Issue by Davidcloner** [iptv-org/iptv#4977]
List of requests for XXX channels from other issues:

- [ #EXTINF:-1,ABC
http://61.68.127.183:9981/stream/channelid/67968123
#EXTINF:-1,SBS ONE
http://61.68.127.183:9981/stream/channelid/381724314
#EXTINF:-1,9 Toowoomba
http://61.68.127.183:9981/stream/channelid/2037318311
#EXTINF:-1,WIN Darling Downs
http://61.68.127.183:9981/stream/channelid/1919468014
#EXTINF:-1,ABC HD
http://61.68.127.183:9981/stream/channelid/43837816
#EXTINF:-1,ABC
http://61.68.127.183:9981/stream/channelid/36059125
#EXTINF:-1,ABC
http://61.68.127.183:9981/stream/channelid/1526855582
#EXTINF:-1,ABC Comedy/Kids
http://61.68.127.183:9981/stream/channelid/442790358
#EXTINF:-1,ABC ME
http://61.68.127.183:9981/stream/channelid/1062745230
#EXTINF:-1,ABC ME
http://61.68.127.183:9981/stream/channelid/1399479605
#EXTINF:-1,ABC NEWS
http://61.68.127.183:9981/stream/channelid/157596582
#EXTINF:-1,ABC Classic
http://61.68.127.183:9981/stream/channelid/1054591171
#EXTINF:-1,SBS HD
http://61.68.127.183:9981/stream/channelid/346456686
#EXTINF:-1,SBS VICELAND HD
http://61.68.127.183:9981/stream/channelid/1786038001
#EXTINF:-1,SBS World Movies
http://61.68.127.183:9981/stream/channelid/1460036566
#EXTINF:-1,SBS Food
http://61.68.127.183:9981/stream/channelid/1821838877
#EXTINF:-1,9HD Regional
http://61.68.127.183:9981/stream/channelid/1999970685
#EXTINF:-1,9HD Toowoomba
http://61.68.127.183:9981/stream/channelid/547197880
#EXTINF:-1,9 Toowoomba
http://61.68.127.183:9981/stream/channelid/1529879463
#EXTINF:-1,9Gem Regional
http://61.68.127.183:9981/stream/channelid/148734981
#EXTINF:-1,9Go! Regional
http://61.68.127.183:9981/stream/channelid/814806688
#EXTINF:-1,9Life
http://61.68.127.183:9981/stream/channelid/1023925982
#EXTINF:-1,9Life Regional
http://61.68.127.183:9981/stream/channelid/530544457
#EXTINF:-1,7HD – QLD
http://61.68.127.183:9981/stream/channelid/1413862548
#EXTINF:-1,7TWO
http://61.68.127.183:9981/stream/channelid/2010328197
#EXTINF:-1,7mate Toowoomba
http://61.68.127.183:9981/stream/channelid/1131748280
#EXTINF:-1,7mate HD
http://61.68.127.183:9981/stream/channelid/333841289
#EXTINF:-1,7flix
http://61.68.127.183:9981/stream/channelid/1234050967
#EXTINF:-1,WIN HD
http://61.68.127.183:9981/stream/channelid/1037557995
#EXTINF:-1,WIN Bold
http://61.68.127.183:9981/stream/channelid/1879734523
#EXTINF:-1,WIN Peach
http://61.68.127.183:9981/stream/channelid/1337729751
#EXTINF:-1,Sky News on WIN
http://61.68.127.183:9981/stream/channelid/1531314253
#EXTINF:-1,GOLD
http://61.68.127.183:9981/stream/channelid/595981124
#EXTINF:-1,ABC Jazz
http://61.68.127.183:9981/stream/channelid/1073866419
#EXTINF:-1,ABC KIDS Listen
http://61.68.127.183:9981/stream/channelid/226149762
#EXTINF:-1,BBC One HD
http://ckinguk.co:8080/mum/mum/95967
#EXTINF:-1,BBC ONE
http://ckinguk.co:8080/mum/mum/95954
#EXTINF:-1,BBC Two HD
http://ckinguk.co:8080/mum/mum/95975
#EXTINF:-1,BBC Two
http://ckinguk.co:8080/mum/mum/95719
#EXTINF:-1,ITV HD
http://ckinguk.co:8080/mum/mum/95747
#EXTINF:-1,ITV (SD)
http://ckinguk.co:8080/mum/mum/95751
#EXTINF:-1,Channel 5 HD
http://ckinguk.co:8080/mum/mum/95990
#EXTINF:-1,Channel 4 HD
http://ckinguk.co:8080/mum/mum/95986
#EXTINF:-1,Channel 4
http://ckinguk.co:8080/mum/mum/95984
#EXTINF:-1,Channel 5
http://ckinguk.co:8080/mum/mum/95722
#EXTINF:-1,Sky One HD
http://ckinguk.co:8080/mum/mum/95724
#EXTINF:-1,Sky One
http://ckinguk.co:8080/mum/mum/95723
#EXTINF:-1,Sky Witness HD
http://ckinguk.co:8080/mum/mum/95726
#EXTINF:-1,Sky Witness
http://ckinguk.co:8080/mum/mum/95926
#EXTINF:-1,Sky Atlantic FHD
http://ckinguk.co:8080/mum/mum/95728
#EXTINF:-1,Sky Atlantic
http://ckinguk.co:8080/mum/mum/95727
#EXTINF:-1,Comedy Central
http://ckinguk.co:8080/mum/mum/95736
#EXTINF:-1,Comedy Central HD
http://ckinguk.co:8080/mum/mum/95735
#EXTINF:-1,Universal Channel HD
http://ckinguk.co:8080/mum/mum/95827
#EXTINF:-1,Universal
http://ckinguk.co:8080/mum/mum/95826
#EXTINF:-1,BBC Four HD
http://ckinguk.co:8080/mum/mum/95779
#EXTINF:-1,BBC Four
http://ckinguk.co:8080/mum/mum/95778
#EXTINF:-1,ITV4
http://ckinguk.co:8080/mum/mum/95746
#EXTINF:-1,ITV3 HD
http://ckinguk.co:8080/mum/mum/95745
#EXTINF:-1,ITV3
http://ckinguk.co:8080/mum/mum/95744
#EXTINF:-1,ITV2 HD
http://ckinguk.co:8080/mum/mum/95743
#EXTINF:-1,ITV2
http://ckinguk.co:8080/mum/mum/95742
#EXTINF:-1,SYFY HD
http://ckinguk.co:8080/mum/mum/95739
#EXTINF:-1,SYFY
http://ckinguk.co:8080/mum/mum/95738
#EXTINF:-1,STV North
http://ckinguk.co:8080/mum/mum/95981
#EXTINF:-1,STV
http://ckinguk.co:8080/mum/mum/95980
#EXTINF:-1,UTV HD
http://ckinguk.co:8080/mum/mum/95978
#EXTINF:-1,UTV
http://ckinguk.co:8080/mum/mum/95977
#EXTINF:-1,TV Warehouse
http://ckinguk.co:8080/mum/mum/95940
#EXTINF:-1,Tyne & Wear TV
http://ckinguk.co:8080/mum/mum/95939
#EXTINF:-1,Aastha
http://ckinguk.co:8080/mum/mum/95937
#EXTINF:-1,Gems TV
http://ckinguk.co:8080/mum/mum/95934
#EXTINF:-1,GOD Channel
http://ckinguk.co:8080/mum/mum/95933
#EXTINF:-1,JML Direct
http://ckinguk.co:8080/mum/mum/95932
#EXTINF:-1,Leeds TV
http://ckinguk.co:8080/mum/mum/95931
#EXTINF:-1,Record TV
http://ckinguk.co:8080/mum/mum/95929
#EXTINF:-1,Thane
http://ckinguk.co:8080/mum/mum/95925
#EXTINF:-1,TJC
http://ckinguk.co:8080/mum/mum/95924
#EXTINF:-1,London Live
http://ckinguk.co:8080/mum/mum/95921
#EXTINF:-1,Craft Extra
http://ckinguk.co:8080/mum/mum/95916
#EXTINF:-1,TBN UK
http://ckinguk.co:8080/mum/mum/95914
#EXTINF:-1,True Crime
http://ckinguk.co:8080/mum/mum/95808
#EXTINF:-1,DMAX
http://ckinguk.co:8080/mum/mum/95806
#EXTINF:-1,BEN
http://ckinguk.co:8080/mum/mum/95804
#EXTINF:-1,BET
http://ckinguk.co:8080/mum/mum/95803
#EXTINF:-1,Real Lives
http://ckinguk.co:8080/mum/mum/95801
#EXTINF:-1,BBC ALBA
http://ckinguk.co:8080/mum/mum/95800
#EXTINF:-1,BBC ALBA HD
http://ckinguk.co:8080/mum/mum/95799
#EXTINF:-1,5select
http://ckinguk.co:8080/mum/mum/95795
#EXTINF:-1,5Spike
http://ckinguk.co:8080/mum/mum/95793
#EXTINF:-1,Quest Red
http://ckinguk.co:8080/mum/mum/95791
#EXTINF:-1,Quest HD
http://ckinguk.co:8080/mum/mum/95790
#EXTINF:-1,Quest
http://ckinguk.co:8080/mum/mum/95789
#EXTINF:-1,Really
http://ckinguk.co:8080/mum/mum/95787
#EXTINF:-1,5 USA
http://ckinguk.co:8080/mum/mum/95786
#EXTINF:-1,4Seven HD
http://ckinguk.co:8080/mum/mum/95785
#EXTINF:-1,4seven
http://ckinguk.co:8080/mum/mum/95784
#EXTINF:-1,E4 HD
http://ckinguk.co:8080/mum/mum/95783
#EXTINF:-1,E4
http://ckinguk.co:8080/mum/mum/95782
#EXTINF:-1,More 4 HD
http://ckinguk.co:8080/mum/mum/95781
#EXTINF:-1,More 4
http://ckinguk.co:8080/mum/mum/95780
#EXTINF:-1,S4C HD
http://ckinguk.co:8080/mum/mum/95777
#EXTINF:-1,S4C
http://ckinguk.co:8080/mum/mum/95776
#EXTINF:-1,alibi HD
http://ckinguk.co:8080/mum/mum/95773
#EXTINF:-1,alibi
http://ckinguk.co:8080/mum/mum/95772
#EXTINF:-1,5STAR
http://ckinguk.co:8080/mum/mum/95771
#EXTINF:-1,E!
http://ckinguk.co:8080/mum/mum/95766
#EXTINF:-1,Sky Arts HD
http://ckinguk.co:8080/mum/mum/95765
#EXTINF:-1,Sky Arts
http://ckinguk.co:8080/mum/mum/95764
#EXTINF:-1,ITVBe HD
http://ckinguk.co:8080/mum/mum/95741
#EXTINF:-1,ITVBe
http://ckinguk.co:8080/mum/mum/95740
#EXTINF:-1,SKY ACTION MEN HD
http://ckinguk.co:8080/mum/mum/92598
#EXTINF:-1,Sky Family
http://ckinguk.co:8080/mum/mum/95652
#EXTINF:-1,Sky Rom Coms
http://ckinguk.co:8080/mum/mum/95653
#EXTINF:-1,Sky Premiere
http://ckinguk.co:8080/mum/mum/95654
#EXTINF:-1,Sky Premiere 1hr
http://ckinguk.co:8080/mum/mum/95655
#EXTINF:-1,Sky Superhero
http://ckinguk.co:8080/mum/mum/95656
#EXTINF:-1,Sky ScFi Horror
http://ckinguk.co:8080/mum/mum/95657
#EXTINF:-1,Sky Drama
http://ckinguk.co:8080/mum/mum/95658
#EXTINF:-1,Sky Disney
http://ckinguk.co:8080/mum/mum/95659
#EXTINF:-1,Sky Action
http://ckinguk.co:8080/mum/mum/95660
#EXTINF:-1,Sky Thriller
http://ckinguk.co:8080/mum/mum/95661
#EXTINF:-1,Film4
http://ckinguk.co:8080/mum/mum/95665
#EXTINF:-1,Film4+1
http://ckinguk.co:8080/mum/mum/95666
#EXTINF:-1,TCM HD
http://ckinguk.co:8080/mum/mum/95850
#EXTINF:-1,TCM
http://ckinguk.co:8080/mum/mum/95849
#EXTINF:-1,horror channel
http://ckinguk.co:8080/mum/mum/95662
#EXTINF:-1,True Movies
http://ckinguk.co:8080/mum/mum/95663
#EXTINF:-1,CA: A&E | HD
http://ckinguk.co:8080/mum/mum/199308
#EXTINF:-1,CA: ABC SPARK |HD
http://ckinguk.co:8080/mum/mum/199309
#EXTINF:-1,CA: ABC | HD
http://ckinguk.co:8080/mum/mum/199310
#EXTINF:-1,CA: AHC |HD
http://ckinguk.co:8080/mum/mum/199312
#EXTINF:-1,CA: AMC | HD
http://ckinguk.co:8080/mum/mum/199313
#EXTINF:-1,CA: Animal Planet | HD
http://ckinguk.co:8080/mum/mum/199314
#EXTINF:-1,CA: APTN | SD
http://ckinguk.co:8080/mum/mum/199315
#EXTINF:-1,CA: BBC Canada | SD
http://ckinguk.co:8080/mum/mum/199316
#EXTINF:-1,CA: BBC WORLD NEWS | HD
http://ckinguk.co:8080/mum/mum/199317
#EXTINF:-1,CA: BEIN SPORTS | HD
http://ckinguk.co:8080/mum/mum/199318
#EXTINF:-1,CA: BET | SD
http://ckinguk.co:8080/mum/mum/199319
#EXTINF:-1,CA: BNN Bloomberg | HD
http://ckinguk.co:8080/mum/mum/199320
#EXTINF:-1,CA: BOOK TV | SD
http://ckinguk.co:8080/mum/mum/199321
#EXTINF:-1,CA: CablePulse 24 | HD
http://ckinguk.co:8080/mum/mum/199322
#EXTINF:-1,CA: Canal Savoir | SD
http://ckinguk.co:8080/mum/mum/199323
#EXTINF:-1,CA: CARTOON NETWORK  |  SD
http://ckinguk.co:8080/mum/mum/199324
#EXTINF:-1,CA: Cartoon Network | SD
http://ckinguk.co:8080/mum/mum/199325
#EXTINF:-1,CA: CBC CALGARY | HD
http://ckinguk.co:8080/mum/mum/199326
#EXTINF:-1,CA: CBC Montreal HD
http://ckinguk.co:8080/mum/mum/199327
#EXTINF:-1,CA: CBC Montreal | HD
http://ckinguk.co:8080/mum/mum/199328
#EXTINF:-1,CA: CBC News Network | HD
http://ckinguk.co:8080/mum/mum/199329
#EXTINF:-1,CA: CBC NOVA SCOTIA
http://ckinguk.co:8080/mum/mum/199330
#EXTINF:-1,CA: CBC Oshawa (CHEX2) | HD
http://ckinguk.co:8080/mum/mum/199331
#EXTINF:-1,CA: CBC OTTAWA | HD
http://ckinguk.co:8080/mum/mum/199332
#EXTINF:-1,CA: CBC St. John's (CBNT) | HD
http://ckinguk.co:8080/mum/mum/199333
#EXTINF:-1,CA: CBC Toronto (CBLT) | HD
http://ckinguk.co:8080/mum/mum/199334
#EXTINF:-1,CA: CBC TORONTO | HD
http://ckinguk.co:8080/mum/mum/199335
#EXTINF:-1,CA: CBC VANCOUVER | HD
http://ckinguk.co:8080/mum/mum/199336
#EXTINF:-1,CA: CBC | HD
http://ckinguk.co:8080/mum/mum/199337
#EXTINF:-1,CA: CBC3 | HD
http://ckinguk.co:8080/mum/mum/199338
#EXTINF:-1,CA: CBS | HD
http://ckinguk.co:8080/mum/mum/199339
#EXTINF:-1,CA: CHCH | HD
http://ckinguk.co:8080/mum/mum/199340
#EXTINF:-1,CA: CITY CALGARY | SD
http://ckinguk.co:8080/mum/mum/199341
#EXTINF:-1,CA: CITY MONTREAL | SD
http://ckinguk.co:8080/mum/mum/199342
#EXTINF:-1,CA: CITY TORONTO | SD
http://ckinguk.co:8080/mum/mum/199343
#EXTINF:-1,CA: CITY VANCOUVER | SD
http://ckinguk.co:8080/mum/mum/199344
#EXTINF:-1,CA: Citytv Toronto | HD
http://ckinguk.co:8080/mum/mum/199345
#EXTINF:-1,CA: CMT | SD
http://ckinguk.co:8080/mum/mum/199346
#EXTINF:-1,CA: CNBC | SD
http://ckinguk.co:8080/mum/mum/199347
#EXTINF:-1,CA: CNN | HD
http://ckinguk.co:8080/mum/mum/199348
#EXTINF:-1,CA: COOKING CHANNEL | SD
http://ckinguk.co:8080/mum/mum/199349
#EXTINF:-1,CA: COTTAGE LIFE | SD
http://ckinguk.co:8080/mum/mum/199350
#EXTINF:-1,CA: CP24 | HD
http://ckinguk.co:8080/mum/mum/199351
#EXTINF:-1,CA: CPAC EN | HD
http://ckinguk.co:8080/mum/mum/199352
#EXTINF:-1,CA: CPAC FR | SD
http://ckinguk.co:8080/mum/mum/199353
#EXTINF:-1,CA: Crave 1 | HD
http://ckinguk.co:8080/mum/mum/199354
#EXTINF:-1,CA: Crave 2 | HD
http://ckinguk.co:8080/mum/mum/199355
#EXTINF:-1,CA: Crave 3 | HD
http://ckinguk.co:8080/mum/mum/199356
#EXTINF:-1,CA: Crave 4 | HD
http://ckinguk.co:8080/mum/mum/199357
#EXTINF:-1,US: A&E | HD
http://ckinguk.co:8080/mum/mum/200982
#EXTINF:-1,US: ABC NEWS LIVE EAST | HD
http://ckinguk.co:8080/mum/mum/200983
#EXTINF:-1,US: ABC | HD
http://ckinguk.co:8080/mum/mum/200984
#EXTINF:-1,US: ACC NETWORK | HD
http://ckinguk.co:8080/mum/mum/200985
#EXTINF:-1,US: AMC | HD
http://ckinguk.co:8080/mum/mum/200986
#EXTINF:-1,US: ANIMAL PLANET | HD
http://ckinguk.co:8080/mum/mum/200987
#EXTINF:-1,US: BLOOMBERG | HD
http://ckinguk.co:8080/mum/mum/201014
#EXTINF:-1,US: BOOMERANG | HD
http://ckinguk.co:8080/mum/mum/201015
#EXTINF:-1,US: BOUNCE TV | HD
http://ckinguk.co:8080/mum/mum/201016
#EXTINF:-1,US: BRAVO WEST | HD
http://ckinguk.co:8080/mum/mum/201017
#EXTINF:-1,US: BRAVO | HD
http://ckinguk.co:8080/mum/mum/201018
#EXTINF:-1,US: BUZZR | SD
http://ckinguk.co:8080/mum/mum/201019
#EXTINF:-1,US: C-SPAN 2 | HD
http://ckinguk.co:8080/mum/mum/201020
#EXTINF:-1,US: C-SPAN 3 | SD
http://ckinguk.co:8080/mum/mum/201021
#EXTINF:-1,US: C-SPAN | HD
http://ckinguk.co:8080/mum/mum/201022
#EXTINF:-1,US: CNBC | HD
http://ckinguk.co:8080/mum/mum/201036
#EXTINF:-1,US: CNN INTERNATIONAL | HD
http://ckinguk.co:8080/mum/mum/201037
#EXTINF:-1,US: CNN | HD
http://ckinguk.co:8080/mum/mum/201038
#EXTINF:-1,US: COMEDY CENTRAL | HD
http://ckinguk.co:8080/mum/mum/201039
#EXTINF:-1,US: COMET TV | HD
http://ckinguk.co:8080/mum/mum/201040
#EXTINF:-1,US: COWBOY CHANNEL | HD
http://ckinguk.co:8080/mum/mum/201041
#EXTINF:-1,US: COZI TV | HD
http://ckinguk.co:8080/mum/mum/201042
#EXTINF:-1,US: CW | HD
http://ckinguk.co:8080/mum/mum/201044
#EXTINF:-1,US: DESTINATION AMERICA | HD
http://ckinguk.co:8080/mum/mum/201045
#EXTINF:-1,US: DISCOVERY CHANNEL | HD
http://ckinguk.co:8080/mum/mum/201046
#EXTINF:-1,US: E! WEST | HD
http://ckinguk.co:8080/mum/mum/201063
#EXTINF:-1,US: EL REY NETWORK | HD
http://ckinguk.co:8080/mum/mum/201064
#EXTINF:-1,US: ELEVEN SPORTS NETWORK | HD
http://ckinguk.co:8080/mum/mum/201065
#EXTINF:-1,US: EPIX 2 | HD
http://ckinguk.co:8080/mum/mum/201066
#EXTINF:-1,US: EPIX DRIVE IN | HD
http://ckinguk.co:8080/mum/mum/201067
#EXTINF:-1,US: EPIX HITS | HD
http://ckinguk.co:8080/mum/mum/201068
#EXTINF:-1,US: EPIX | HD
http://ckinguk.co:8080/mum/mum/201069
#EXTINF:-1,US: ESCAPE | HD
http://ckinguk.co:8080/mum/mum/201070
#EXTINF:-1,US: ESPN 2 | HD
http://ckinguk.co:8080/mum/mum/201071
#EXTINF:-1,US: FREEFORM | HD
http://ckinguk.co:8080/mum/mum/201098
#EXTINF:-1,US: FUSE | HD
http://ckinguk.co:8080/mum/mum/201099
#EXTINF:-1,US: FUSION | HD
http://ckinguk.co:8080/mum/mum/201100
#EXTINF:-1,US: FX WEST | HD
http://ckinguk.co:8080/mum/mum/201101
#EXTINF:-1,US: FX | HD
http://ckinguk.co:8080/mum/mum/201102
#EXTINF:-1,US: FXM | HD
http://ckinguk.co:8080/mum/mum/201103
#EXTINF:-1,US: FXX WEST | HD
http://ckinguk.co:8080/mum/mum/201104
#EXTINF:-1,US: FXX | HD
http://ckinguk.co:8080/mum/mum/201105
#EXTINF:-1,US: FYI | HD
http://ckinguk.co:8080/mum/mum/201106
#EXTINF:-1,US: MTV LIVE | HD
http://ckinguk.co:8080/mum/mum/201143
#EXTINF:-1,US: MTV U | HD
http://ckinguk.co:8080/mum/mum/201144
#EXTINF:-1,US: MTV | HD
http://ckinguk.co:8080/mum/mum/201145
#EXTINF:-1,US: NAT GEO WILD EAST | HD
http://ckinguk.co:8080/mum/mum/201146
#EXTINF:-1,US: START TV | HD
http://ckinguk.co:8080/mum/mum/201217
#EXTINF:-1,US: STARZ CINEMA | HD
http://ckinguk.co:8080/mum/mum/201218
#EXTINF:-1,US: STARZ COMEDY | HD
http://ckinguk.co:8080/mum/mum/201219
#EXTINF:-1,US: STARZ ENCORE BLACK | HD
http://ckinguk.co:8080/mum/mum/201220
#EXTINF:-1,US: STARZ ENCORE CLASSIC | HD
http://ckinguk.co:8080/mum/mum/201221
#EXTINF:-1,US: STARZ ENCORE FAMILY | HD
http://ckinguk.co:8080/mum/mum/201222
#EXTINF:-1,US: STARZ ENCORE SUSPENSE | HD
http://ckinguk.co:8080/mum/mum/201223
#EXTINF:-1,US: STARZ ENCORE WESTERNS | HD
http://ckinguk.co:8080/mum/mum/201224
#EXTINF:-1,US: STARZ IN BLACK | HD
http://ckinguk.co:8080/mum/mum/201225
#EXTINF:-1,US: STARZ WEST | HD
http://ckinguk.co:8080/mum/mum/201226
#EXTINF:-1,X18 | Hustler HD
http://ckinguk.co:8080/mum/mum/199585
#EXTINF:-1,X18 | Hustler TV
http://ckinguk.co:8080/mum/mum/199586
#EXTINF:-1,X18 | Bizzare
http://ckinguk.co:8080/mum/mum/199587
#EXTINF:-1,X18 | Passie X
http://ckinguk.co:8080/mum/mum/199588
#EXTINF:-1,X18 | Penthouse Passion HD
http://ckinguk.co:8080/mum/mum/199589
#EXTINF:-1,X18 | Pink Erotic
http://ckinguk.co:8080/mum/mum/199590
#EXTINF:-1,X18 | Pink O TV
http://ckinguk.co:8080/mum/mum/199594
#EXTINF:-1,X18 | Reality Kings TV
http://ckinguk.co:8080/mum/mum/199595
#EXTINF:-1,X18 | Redlight HD
http://ckinguk.co:8080/mum/mum/199596
#EXTINF:-1,X18 | Rough
http://ckinguk.co:8080/mum/mum/199597
#EXTINF:-1,X18 | Super One HD
http://ckinguk.co:8080/mum/mum/199598
#EXTINF:-1,X18 | XXL
http://ckinguk.co:8080/mum/mum/199599
#EXTINF:-1,X18  || VIVID X TV
http://ckinguk.co:8080/mum/mum/199600
#EXTINF:-1,X18  || PENTHOUSE 1 HD
http://ckinguk.co:8080/mum/mum/199601
#EXTINF:-1,X18  || XY TV
http://ckinguk.co:8080/mum/mum/199602
#EXTINF:-1,X18  || Babes TV
http://ckinguk.co:8080/mum/mum/199603] xxx

If you find a working link to a channel from the list you can add it directly to the playlist by making a pull request, just read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#add-or-replace-a-stream) before you do it.

**Comment by LaneSh4d0w** [comment]
The way of doing it isn't correct. Please look at the [Contribution Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md) before posting again.
