### ISSUE TITLE
Disney Junior Japan

### ISSUE THREAD

**Issue by nickjrukfan** [iptv-org/iptv#4983]
Could you directly Rip The Disney Junior Japan Livestream From MujiTv? If so I will be very happy
**Channel Name:** Disney Junior Japan
**Country:** Asia 
**Language:** Japanese
**Website:** Disney.jp

**Comment by LaneSh4d0w** [comment]
It's a paid service, so it's going to be difficult to get anything from there (I do even think that they're behind the "jpnettv.live" service (either them or JapanTV)

**Comment by Dum4G** [comment]
Duplicate of https://github.com/iptv-org/iptv/issues/3762
