### ISSUE TITLE
Één

### ISSUE THREAD

**Issue by Boxiet** [iptv-org/iptv#4989]
**Channel Name:** ÉÉN
**Channel ID:** Een.be
**Country:** Belgium
**Language:** Dutch
**Website:** https://www.een.be/
**Stream URL (optional):** https://www.vrt.be/vrtnu/livestream/
**Notes (optional):** xxx

**Comment by Alstruit** [comment]
Geo-blocked and DRMed.

**Comment by freearhey** [comment]
Closed in favor #12252
