### ISSUE TITLE
TVO Piura

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#4990]
**Channel Name:** TVO Piura
**Channel ID:** TVOPiura.pe
**Country:** PE
**Language:** Spanish
**Website:** https://tvopiura.com/tvonline/
**Stream URL (optional):** https://www.opencaster.com/tvocanal31-100-100
**Notes (optional):** Opencaster embed.

**Comment by LaneSh4d0w** [comment]
Sadly we can't deal with Opencaster links. Closing.
