### ISSUE TITLE
Tele Vida Moyobamba

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#4991]
**Channel Name:** TeleVida Moyobamba
**Channel ID:** TeleVida.pe
**Country:** PE
**Language:** Spanish
**Website:** -- (Facebook is https://es-la.facebook.com/TeleVidaMoyobamba/)
**Stream URL (optional):** http://www.opencaster.com/televidatv
**Notes (optional):** Opencaster embed.

**Comment by LaneSh4d0w** [comment]
Sadly we can't deal with Opencaster links. Closing.
