### ISSUE TITLE
Nubar TV

### ISSUE THREAD

**Issue by diaqad** [iptv-org/iptv#5001]
**Channel Name:** Nubar tv & Nubar Sport tv
**Channel ID:** NUBARtv.iq
**Country:** Iraq
**Language:** Kurdish
**Website:** https://www.nubar.tv/
**Stream URL (optional):** https://www.nubar.tv/
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
its possible on kodi 

if you use sendtokodi Addon  + Playlistloader  Addon

In a m3u list :
#EXTINF:-1 tvg-logo="" group-title="",  (STK) 
plugin://plugin.video.sendtokodi/?URLHERE

https://ok.ru/live/IDHERE|User-Agent=Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36


Exemple Final 
#EXTINF:-1 tvg-logo="https://i.imgur.com/TuhANd8.jpg" group-title="Kids",NUBAR tv  (STK) 
plugin://plugin.video.sendtokodi/?https://ok.ru/live/2401044471492|User-Agent=Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36

**Comment by freearhey** [comment]
Closed in favor #12251
