### ISSUE TITLE
DreamWorks TV Asia

### ISSUE THREAD

**Issue by serperiorblade** [iptv-org/iptv#5007]
Channel Name: DreamWorks Channel HD
Channel ID: DreamWorksChannelAsia.us
Country: Malaysia
Language: Malay
Website: http://www.dreamworks-asia.com/
Stream URL (optional): xxx
Notes (optional): xxx

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/13d2f470b7e5b647c0d24d4b6897c651d4b52971/streams/kr.m3u#L78-L79
https://github.com/iptv-org/iptv/blob/13d2f470b7e5b647c0d24d4b6897c651d4b52971/streams/vn_fptplay.m3u#L29-L31
