### ISSUE TITLE
please update the Macedonian channels

### ISSUE THREAD

**Issue by mojso** [iptv-org/iptv#501]
please update the Macedonian channels
MRT1, MRT2, Telma , Sitel , kanal 5 , 24 vesti , 1tv, Alfa

**Comment by freearhey** [comment]
- [x] [MRT 1](https://en.wikipedia.org/wiki/MRT_1)
https://github.com/iptv-org/iptv/blob/f90ed523efbdd93def0184776e632c8710ff28a0/channels/mk.m3u#L16-L17
- [ ] [MRT 2](https://en.wikipedia.org/wiki/MRT_2_(TV_channel))
- [x] [Telma](https://telma.com.mk/) (Телма)
https://github.com/iptv-org/iptv/blob/f90ed523efbdd93def0184776e632c8710ff28a0/channels/mk.m3u#L14-L15
- [ ] [Sitel](https://sitel.com.mk/) (Сител)
- [ ] [Kanal 5](https://kanal5.com.mk/) (Канал 5)
- [ ] [Televizija 24](https://24.mk/) (Телевизија 24)
- [ ] [1tv](https://1tv.mk/)
- [x] [Alfa TV](https://alfa.mk/) (Алфа ТВ)
https://github.com/iptv-org/iptv/blob/f90ed523efbdd93def0184776e632c8710ff28a0/channels/mk.m3u#L12-L13

**Comment by freearhey** [comment]
Closed in favor #1948
