### ISSUE TITLE
Fix: tv stations in every group

### ISSUE THREAD

**Issue by micha3008** [iptv-org/iptv#5060]
please can you fix the issue that a few channels appear in all countrys
Bloomberg Tv Asia live
blommberg tv asia (720p)
fox movies asia
national geo wild asia 
Bloomberg tv emealive
and other bloomberg stations

please can you check and disalble this channels in the wrong groups

thx

**Comment by LaneSh4d0w** [comment]
Bloomberg is on all groups because it is streamed internationally. There's no "bug" whatsoever behind it.

**Comment by micha3008** [comment]
ah reallly. north Korea and many others are little stupid. sorry..
in my opinion. a channel should have one country...
