### ISSUE TITLE
Country and category information not visible in VLC

### ISSUE THREAD

**Issue by khimaros** [iptv-org/iptv#507]
EXTINF "group-title" has no effect on VLC. The [M3U parser in VLC](https://github.com/videolan/vlc/blob/master/modules/demux/playlist/m3u.c) is extremely simple. It expects the format of #EXTINF lines to be one of:

```
/* *** "EXTINF:time,artist - name" */
/* *** "EXTINF:time,,name" */
/* *** "EXTINF:time,artist,name" */
/* *** "EXTINF:time,name" */
```

Unfortunately, the M3U format is not standardized. The closest we have is an [IETF draft for the M3U8 file format](https://tools.ietf.org/html/draft-pantos-http-live-streaming-08) and a [descriptive table on Wikipedia](https://en.wikipedia.org/wiki/M3U#Extended_M3U).

VLC also contains an [M3U8 parser](https://github.com/videolan/vlc/blob/9f14237d4f80dde123db7f752eae2d012287a0e6/modules/demux/hls/playlist/) but it doesn't seem to be at play here. IIUC, there is a bug in this code and `IsHLS` will never return true. I haven't dug deeply enough to understand how this impacts the rest of the playlist parsing logic.

The simplest and most compatible way I can think of to include this information such that it would work with most clients is to stuff it all into the title, for example:

```
#EXTINF:-1,Afghanistan - News - Ariana News
```

**Comment by khimaros** [comment]
Here is a simple workaround which makes this list usable in VLC:

```
$ wget https://iptv-org.github.io/iptv/index.full.m3u
$ sed -r 's/#EXTINF:-1.*? group-title="(.*?)",(.*?)/#EXTINF:-1,\1 - \2/g' index.full.m3u > index.fixed.m3u
$ vlc index.fixed.m3u
```

**Comment by freearhey** [comment]
You are right, the M3U format is not a standard, just like the IPTV playlists in particular, but if you look at examples of playlists distributed on the Internet, you will notice the following template:

```
#EXTINF:-1 tvg-id="exampletv.us" tvg-name="Example TV" tvg-logo="http://example.com/channel-logo.png" group-title="News",Example TV
```

According to this template, playlists were created in this repository.

And in fact, most well-known IPTV players support the "group-title" like all other attributes. As for the VLC, it is not an IPTV player and it would be strange to adapt to it.
