### ISSUE TITLE
ShirdiLive.in

### ISSUE THREAD

**Issue by yogi-savetman** [iptv-org/iptv#5099]
**Channel Name:** ShirdiLive.in
**Country:** India
**Language:** Hindi
**Website:** xxx
**Stream URL (optional):** https://cam.live-s.cdn.bitgravity.com/cdn-live/_definst_/cam/live/secure/saibaba/playlist.m3u8?e=0&h=2598445340a35f63eb211f81940d2525
**Notes (optional):** Cannot be received

**Comment by LaneSh4d0w** [comment]
> 
> Quite possibly, although not specifically given in the link. The marble statue of Sia Baba once was shown during different times of the day, each day, being dressed and cleaned.

Let me see. I might be able to get a fresh link all the time.
