### ISSUE TITLE
Channel not loading

### ISSUE THREAD

**Issue by hiddenpants-dr** [iptv-org/iptv#510]
Hi,

Some of the channel do not load at all, i am using Kodi with IPVR add-on.

Sorry im very new to these so any help that would be greate.

**Comment by freearhey** [comment]
Could you clarify which channels are not working?

**Comment by hiddenpants-dr** [comment]
hi freearhey,

I was browsing the vietnamese channel like HTV1 to HTV9 doesn't load. I haven't tested all channel but there are quite a few i have click on and has not load.

**Comment by freearhey** [comment]
Yes you are right, they do not work for me either. I already deleted all the broken links I could find. But as soon as a replacement appears, we will return them back.
