### ISSUE TITLE
PBA Rush

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#5123]
**Channel Name:** PBA Rush
**Channel ID:** PBARush.ph
**Country:** Philippines
**Language:** English, Filipino
**Website:** https://trueid.ph/livetv/XpjqQjb3YNwP/pba-rush/
**Stream URL (optional):** xxx
**Notes (optional):** There's a tokenized stream in the website,

**Comment by thedarkdragon11** [comment]
> 
> 
> More than this. I do not know if they have strong diplomacy ties with Singapore or Taiwan, but when using those IPs, I usually do not get blocked.

If IPs from SG or TW won't work, I can setup a VM with a natural PH IP.

**Comment by freearhey** [comment]
Closed in favor #12240
