### ISSUE TITLE
Fox Action Movies

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#5143]
**Channel Name:** Fox Action Movies
**Channel ID:** FoxActionMovies.us
**Country:** Middle East
**Language:** English
**Website:** xxx
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by freearhey** [comment]
The channel closed on 1 October 2021 (https://en.wikipedia.org/wiki/Fox_Action_Movies)
