### ISSUE TITLE
MBC 2

### ISSUE THREAD

**Issue by yosep2000** [iptv-org/iptv#5158]
**Channel Name:** MBC 2
**Country:** United Arab Emirates
**Language:** Arabic
**Website:** Dont know

**Comment by zthed** [comment]
https://tv.chachatv.tk/live/direct/direct/238.m3u8

this link is working just one minute and then no stream  why ?

**Comment by Mennaruuk** [comment]
`https://livestreams.tooli-tv.com/live/149010_.m3u8`

**Comment by LaneSh4d0w** [comment]
#EXTINF:-1,MBC2
http://source2.primetime.ch/play/a07q

**Comment by zthed** [comment]
#EXTINF:-1,MBC2
http://source2.primetime.ch/play/a07q

does not work

**Comment by jad222** [comment]
Added mbc2 #6160 @freearhey

**Comment by watchme247** [comment]
I tried a lot of m3u8 links none of them work. Does anyone have a working link?
The only link that worked for me is this:
http://tv.pure-onetv.com:25443/live/HAJG6/k7bKPqg05y/67517.ts
Is it possible to convert TS to m3u8?
