### ISSUE TITLE
MBC Max

### ISSUE THREAD

**Issue by yosep2000** [iptv-org/iptv#5159]
**Channel Name:** MBC MAX
**Country:** United Arab Emirates
**Language:** Arabic
**Website:** I dont know

**Comment by LaneSh4d0w** [comment]
> 
> 
> `https://tv.chachatv.tk/live/direct/direct/244.m3u8`

This one is now https://shls-mbcpersia-prod-dub.shahid.net/out/v1/bdc7cd0d990e4c54808632a52c396946/index.m3u8

**Comment by Mennaruuk** [comment]
`https://livestreams.tooli-tv.com/live/149015_.m3u8`

**Comment by aboode13579** [comment]
How do I use this link? I tried box it didn't work> https://livestreams.tooli-tv.com/live/149015_.m3u8

**Comment by Mennaruuk** [comment]
> How do I use this link? I tried box it didn't work> https://livestreams.tooli-tv.com/live/149015_.m3u8

Try this one for now: https://tv.chachatv.tk/live/direct/direct/244.m3u8

**Comment by LaneSh4d0w** [comment]
> > How do I use this link? I tried box it didn't work> https://livestreams.tooli-tv.com/live/149015_.m3u8
> 
> Try this one for now: https://tv.chachatv.tk/live/direct/direct/244.m3u8

403s after 5 seconds.

**Comment by jad222** [comment]
Added Mbc Max #6160 @freearhey
