### ISSUE TITLE
ACV Channels

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#5182]
**_Channel Name:_** ACV Channels
**_Country:_** IN
**_Broken Link (from playlist):_** xxx
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** xxx

**Comment by freearhey** [comment]
> IMPORTANT: the issue should contain a request for only one channel, otherwise it will be closed immediately

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel
