### ISSUE TITLE
Next TV

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#5189]
**Channel Name:** Next TV
**Country:** IN
**Language:** Malayalam
**Website:** https://www.mxplayer.in/live-tv/next-tv-live-channel-8072nexttvin
**Stream URL (optional):** 
**Notes (optional):** xxx

**Comment by Manipulativemachan** [comment]
Channel is live on both websites. But this m3u8 file is not working

**Comment by LaneSh4d0w** [comment]
![image](https://user-images.githubusercontent.com/30985701/139593216-50a4eb09-9f12-42e9-9b9d-d5c39e5436b9.png)

Maybe user-agent issue ?

**Comment by Manipulativemachan** [comment]
not working for me in vlc
