### ISSUE TITLE
Fox Türkiye

### ISSUE THREAD

**Issue by evrifaessa** [iptv-org/iptv#5200]
**Channel Name:** FOX
**Channel ID:** FoxTurkey.us
**Country:** tr
**Language:** tr
**Website:** https://www.fox.com.tr/
**Stream URL (optional):** xxx
**Notes (optional):** livestream: https://www.fox.com.tr/canli-yayin

**Comment by ceyhun-cahid** [comment]
https://foxtv-live-ad.ercdn.net/foxtv/foxtv_720p.m3u8?e=1649132453&st=eA67d_k8_9R_bsNCR_pS9w

**Comment by Alstruit** [comment]
Done #8941.
