### ISSUE TITLE
tv100

### ISSUE THREAD

**Issue by evrifaessa** [iptv-org/iptv#5202]
**Channel Name:** tv100
**Country:** tr
**Language:** tr
**Website:** https://www.tv100.com/
**Stream URL (optional):** xxx
**Notes (optional):** livestream: https://www.tv100.com/canli-yayin

**Comment by evrifaessa** [comment]
> https://www.youtube.com/channel/UCndsdUW_oPLqpQJY9J8oIRg/live

Not this actually. This one is a separate channel (tv100 ekonomi) owned by the same organization.

The correct link for tv100 is this: https://www.youtube.com/watch?v=8jEXHzMTR7s

However, I think you can add both as separate channels.

**Comment by LaneSh4d0w** [comment]
> > https://www.youtube.com/channel/UCndsdUW_oPLqpQJY9J8oIRg/live
> 
> Not this actually. This one is a separate channel (tv100 ekonomi) owned by the same organization.
> 
> The correct link for tv100 is this: https://www.youtube.com/watch?v=8jEXHzMTR7s
> 
> However, I think you can add both as separate channels.

If you check back, it is now TV100. It really depends on which program gets first in terms of live stream.

**Comment by UzunMuhalefet** [comment]
https://59c7ea6bec1c6.streamlock.net/filbox/tv100.stream/playlist.m3u8
