### ISSUE TITLE
FB TV

### ISSUE THREAD

**Issue by evrifaessa** [iptv-org/iptv#5204]
**Channel Name:** Fenerbahçe TV
**Country:** tr
**Language:** tr
**Website:** https://www.fenerbahce.org/fbtv
**Stream URL (optional):** xxx
**Notes (optional):** Also called as FBTV

**Comment by freearhey** [comment]
![image](https://user-images.githubusercontent.com/7253922/143616370-f55293ec-78c8-465e-968a-50d5ad5bb5f6.png)
