### ISSUE TITLE
Kids Zone

### ISSUE THREAD

**Issue by mayhair** [iptv-org/iptv#5205]
**Channel Name:** Kids Zone
**Channel ID:** KidsZone.pk
**Country:** Pakistan
**Language:** Urdu, English
**Website:** Currently down ...
**Stream URL (optional):** xxx
**Notes (optional):** Not sure if this is satellite-only or not, and if they air Urdu and English cartoons on the same feed.

**Comment by freearhey** [comment]
Closed in favor #12235

**Comment by Ghani201** [comment]
Closed Not Working Lets See What Happend
