### ISSUE TITLE
Habitat

### ISSUE THREAD

**Issue by evrifaessa** [iptv-org/iptv#5206]
**Channel Name:** Habitat TV
**Channel ID:** Habitat.tr
**Country:** tr
**Language:** tr
**Website:** http://habitattv.com.tr/ (only accessible over HTTP)
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by UzunMuhalefet** [comment]
https://59c7ea6bec1c6.streamlock.net/filbox/habibattv.stream/playlist.m3u8

**Comment by Dum4G** [comment]
http://istanbul.tvizlehd.com/live/habitattv.m3u8
https://ankara.tvizlehd.com/live/habitattv.m3u8
https://59c7ea6bec1c6.streamlock.net/live/habibattv.stream/playlist.m3u8

Are those working ? @evrifaessa

**Comment by LaneSh4d0w** [comment]
Upon testing, the first 2 work, the last one is a 403.
We shall precise that those are 2 different streams.

**Comment by freearhey** [comment]
Closed in favor #12234
