### ISSUE TITLE
Antena 3

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#5214]
**Channel Name:** Antena 3
**Channel ID:** Antena3.es
**Country:** Spain
**Language:** Spanish
**Website:** https://www.antena3.com/
**Stream URL (optional):** http://hls.webredirect.org/h4gs/mp_4953.php/https://directo.atresmedia.com/3c4f6df40f586ddb061fca1ff0ab0bf87973b442_1635468712/antena3/bitrate_4.m3u8
**Notes (optional):** It's an official Atresmedia stream. It has a token, but I think it has an automatic refresher for the https://photocall.tv page which is where I got it from. In this repository they do magic, so maybe they can make the token renew automatically. There are also other Atresmedia links, such as LaSexta, Neox, Nova, Mega & A3Series.
If you allow me and I can attach them, here they go:
LaSexta: http://hls.webredirect.org/h4gs/mp_4953.php/https://directo.atresmedia.com/70f935154f65972e9f244c54048105a07ea2409c_1635457355/lasexta/bitrate_4.m3u8
Neox: http://hls.webredirect.org/h4gs/mp_4953.php/https://directo.atresmedia.com/518d9463e7a2c3edfd16a2bcb72540814d3deec7_1635463091/geoneox/bitrate_4.m3u8
Nova: http://hls.webredirect.org/h4gs/mp_4953.php/https://directo.atresmedia.com/7908849782ea2fb912be8b7dc4fa25b8158150ca_1635463113/geonova/bitrate_4.m3u8
Mega: http://hls.webredirect.org/h4gs/mp_4953.php/https://directo.atresmedia.com/69271977a08cc6e26dd4b72ad7de47e406b48a38_1635453173/geomega/bitrate_4.m3u8
A3Series: http://hls.webredirect.org/h4gs/mp_4953.php/https://directo.atresmedia.com/7213eb9f0f6c91dea8cff0c3565828553e69e170_1635453132/geoa3series/bitrate_4.m3u8

**Comment by MapGuy11** [comment]
Try this: 
HD: https://cdn87.theus6tv.tk/Mexico/Antena_3HD.m3u8
SD: https://cdn87.theus6tv.tk/Mexico/Antena_3SD.m3u8

**Comment by LaneSh4d0w** [comment]
> Try this: 
> HD: https://cdn87.theus6tv.tk/Mexico/Antena_3HD.m3u8
> SD: https://cdn87.theus6tv.tk/Mexico/Antena_3SD.m3u8

Simply redirects to an IP with port on my side, works however it's Antena 3 Internacional. I believe that the spanish Antena 3 is a different channel with different programmation.

**Comment by MapGuy11** [comment]
> > Try this:
> > HD: https://cdn87.theus6tv.tk/Mexico/Antena_3HD.m3u8
> > SD: https://cdn87.theus6tv.tk/Mexico/Antena_3SD.m3u8
> 
> Simply redirects to an IP with port on my side, works however it's Antena 3 Internacional. I believe that the spanish Antena 3 is a different channel with different programmation.
> 
> ![Screenshot_20211031-085312.jpg](https://user-images.githubusercontent.com/30985701/139571925-c697ca07-0d9b-4b3c-ac4b-bc182d3930f4.jpg)

Ok then I'll remove sorry about that!

**Comment by LaneSh4d0w** [comment]
> 
> 
> > > Try this:
> > > HD: https://cdn87.theus6tv.tk/Mexico/Antena_3HD.m3u8
> > > SD: https://cdn87.theus6tv.tk/Mexico/Antena_3SD.m3u8
> > 
> > 
> > Simply redirects to an IP with port on my side, works however it's Antena 3 Internacional. I believe that the spanish Antena 3 is a different channel with different programmation.
> > ![Screenshot_20211031-085312.jpg](https://user-images.githubusercontent.com/30985701/139571925-c697ca07-0d9b-4b3c-ac4b-bc182d3930f4.jpg)
> 
> Ok then I'll remove sorry about that!

Don't remove it in fact. Not sure we got it.

**Comment by MapGuy11** [comment]
> > 
> > 
> > > > Try this:
> > > > HD: https://cdn87.theus6tv.tk/Mexico/Antena_3HD.m3u8
> > > > SD: https://cdn87.theus6tv.tk/Mexico/Antena_3SD.m3u8
> > > 
> > > 
> > > Simply redirects to an IP with port on my side, works however it's Antena 3 Internacional. I believe that the spanish Antena 3 is a different channel with different programmation.
> > > ![Screenshot_20211031-085312.jpg](https://user-images.githubusercontent.com/30985701/139571925-c697ca07-0d9b-4b3c-ac4b-bc182d3930f4.jpg)
> > 
> > Ok then I'll remove sorry about that!
> 
> Don't remove it in fact. Not sure we got it.
> 
> + found the panel behind the IP. Server indicates DirectTV Argentina. Just to point that you've put the wrong country :p

Yeah please don't be leaking those panels keep them behind a url like mine because there is alot of them. And some started putting keys on their streams.

**Comment by LaneSh4d0w** [comment]
> 
> 
> > > > > Try this:
> > > > > HD: https://cdn87.theus6tv.tk/Mexico/Antena_3HD.m3u8
> > > > > SD: https://cdn87.theus6tv.tk/Mexico/Antena_3SD.m3u8
> > > > 
> > > > 
> > > > Simply redirects to an IP with port on my side, works however it's Antena 3 Internacional. I believe that the spanish Antena 3 is a different channel with different programmation.
> > > > ![Screenshot_20211031-085312.jpg](https://user-images.githubusercontent.com/30985701/139571925-c697ca07-0d9b-4b3c-ac4b-bc182d3930f4.jpg)
> > > 
> > > 
> > > Ok then I'll remove sorry about that!
> > 
> > 
> > Don't remove it in fact. Not sure we got it.
> > 
> > * found the panel behind the IP. Server indicates DirectTV Argentina. Just to point that you've put the wrong country :p
> 
> Yeah please don't be leaking those panels keep them behind a url like mine because there is alot of them. And some started putting keys on their streams.

Yeah IK. Gonna see what I can do.

**Comment by robocopz** [comment]
> I might get some lives from Mitele ES, however it's going to cost lots of memory power, it scrapes a link for certain tokens, scrapes a link for a certain "cerbero" URL that changes over time, then sends a POST to it with both tokens to get the Akamai tokens, then you add it next to the Mitele link you're watching, and you're good to go.
> 
> Aaaaah, Mediaset...
> 
> For example : Telecinco.
> 
> 1. Mediaset server GET : https://caronte.mediaset.es/delivery/channel/mmc/telecinco/mtweb
> 
> Results = cerbero link + bbx token needed.
> 
> 1. Other Mediaset server GET : https://mab.mediaset.es/1.0.0/get?oid=mtmw&eid=%2Fapi%2Fmtmw%2Fv2%2Fgbx%2Fmtweb%2Flive%2Fmmc%2Ftelecinco
> 
> Results = gbx token
> 
> 1. POST on Cerbero links with bbx and gbx token
> 
> Results = our Akamai data
> 
> 1. paste it next to your Mitele live link (you can also get it from the 1st request, but that doesn't change)
> 2. enjoy

Good for local but not for remote. You can't bypass the ~ ip = in the URL now.

**Comment by LaneSh4d0w** [comment]
> 
> 
> > I might get some lives from Mitele ES, however it's going to cost lots of memory power, it scrapes a link for certain tokens, scrapes a link for a certain "cerbero" URL that changes over time, then sends a POST to it with both tokens to get the Akamai tokens, then you add it next to the Mitele link you're watching, and you're good to go.
> > Aaaaah, Mediaset...
> > For example : Telecinco.
> > 
> > 1. Mediaset server GET : https://caronte.mediaset.es/delivery/channel/mmc/telecinco/mtweb
> > 
> > Results = cerbero link + bbx token needed.
> > 
> > 1. Other Mediaset server GET : https://mab.mediaset.es/1.0.0/get?oid=mtmw&eid=%2Fapi%2Fmtmw%2Fv2%2Fgbx%2Fmtweb%2Flive%2Fmmc%2Ftelecinco
> > 
> > Results = gbx token
> > 
> > 1. POST on Cerbero links with bbx and gbx token
> > 
> > Results = our Akamai data
> > 
> > 1. paste it next to your Mitele live link (you can also get it from the 1st request, but that doesn't change)
> > 2. enjoy
> 
> Good for local but not for remote. You can't bypass the ~ ip = in the m3u8 now.

Yep, unless I put a proxy on both sides.

**Comment by freearhey** [comment]
Closed in favor #12233
