### ISSUE TITLE
AniPlus (English subtitles)

### ISSUE THREAD

**Issue by lokigryn** [iptv-org/iptv#5246]
**Channel Name:** aniplus
**Channel ID:** AniplusAsia.sg
**Country:** Philippines
**Language:** japan
**Website:** xxx
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/dfa0e06b6e22f99aa62e95c554d13742c4b13df1/streams/sg.m3u#L2-L3

**Comment by freearhey** [comment]
Closed in favor #12230
