### ISSUE TITLE
greek  2 music channel hd

### ISSUE THREAD

**Issue by georgoskar** [iptv-org/iptv#526]
#EXTINF:0 tvg-id="ext" group-title="channels",baraza 
https://5cc309e93b721.streamlock.net:443/8490/8490/playlist.m3u8
#EXTINF:0 tvg-id="ext" group-title="channels",baraza tv
https://5cc309e93b721.streamlock.net:443/8452/8452/playlist.m3u8

**Comment by boomski** [comment]
Thanks!
