### ISSUE TITLE
MTV East

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#5283]
**Channel Name:** MTV
**Channel ID:** MTVEast.us
**Country:** United States
**Language:** English
**Website:** xxx
**Stream URL (optional):** https://www.mtv.com/live-tv/xzq4o4
**Notes (optional):** There's a stream in the link above.

**Comment by LaneSh4d0w** [comment]
Most certainly PPV stream.

Needs an US IP with US ISP credentials to get in.

Asks for authorization (certainly based on IP) using https://auth.mtvnservices.com/access/authorization/mtv?clientId=mtv-web&countryCode=us

**Comment by freearhey** [comment]
Closed in favor #12229
