### ISSUE TITLE
KAZT-DT2

### ISSUE THREAD

**Issue by Gitbone94** [iptv-org/iptv#5294]
**Channel Name:** Me TV
**Country:** US
**Language:** English
**Website:** metv.com
**Stream URL (optional):** unknown
**Notes (optional):** You had Me TV Arizona and it disappeared. An eastern time zone feed like WJLP, WDIV, or WLWT would be preferred but I would like to see Me TV Arizona back too.

**Comment by MapGuy11** [comment]
> **Channel Name:** Me TV **Country:** US **Language:** English **Website:** metv.com **Stream URL (optional):** unknown **Notes (optional):** You had Me TV Arizona and it disappeared. An eastern time zone feed like WJLP, WDIV, or WLWT would be preferred but I would like to see Me TV Arizona back too.

It disappeared because someone attacked the way I was hosting them. They may come back though don't hold your breath.

**Comment by LaneSh4d0w** [comment]
https://github.com/iptv-org/iptv/discussions/5296

Take the la.zip file, choose either the 720 or 432 folder, and switch to channel 268.

**Comment by Gitbone94** [comment]
Please elaborate on how to find the "la.zip" file. By country that is Laos and there are few channels there.

**Comment by MapGuy11** [comment]
> Please elaborate on how to find the "la.zip" file. By country that is Laos and there are few channels there.

Sorry they are being worked on and not available yet.

**Comment by Gitbone94** [comment]
Any update is welcome. I would take MeTV from any city (preferably eastern time zone).

**Comment by Central302** [comment]
Close The Issuse (MeTV Added)
