### ISSUE TITLE
Arabic Channels that work!

### ISSUE THREAD

**Issue by iptvchecker** [iptv-org/iptv#530]
I am including a link from an IPTV site. They have much more Arabic links, but mostly do not work and do not update.

Can you please add these channels? Like Nile Cinema, Rotana Cinema. The list of Arabic channels is very skinny.

Thanks
https://www.iptv4sat.com/download-attachment/va6ocryB0FbNOh8n1Dy2oTnwTWHtsWoPUknx7ODleVk,

https://sites.google.com/site/uploadingy/Arabic%20M3u%20VIP%2003-04-2019.m3u?attredirects=0

**Comment by themak1985** [comment]
@iptvchecker the arabic list here is now pretty expansive - I went through and added a few of the working streams that were iraqi from playlist 5 in the zip file and submitted a pull request. The other playlists may have 1-2 working streams - but it would be helpful if you pulled out the working streams into one playlist - happy to create a pull request for you.
