### ISSUE TITLE
CBS East

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#5314]
**Channel Name:** Eastern Feed of CBS
**Country:** USA
**Language:** English
**Website:** https://www.cbs.com/
**Stream URL (optional):** xxx
**Notes (optional):** Need a Eastern Feed of CBS Station.

**Comment by FpFan65** [comment]
There are two that I know of:

WCBS New York
https://v-ny.mybtv.net/event/545/1920x1080.m3u8?start_time=2021-05-29T19%3A45%3A00%2B00%3A00&end_time=2029-05-29T23%3A00%3A00%2B00%3A00&env=prd&uid=25110

KYW Philadelphia
https://v-pi.mybtv.net/event/318/768x432.m3u8?start_time=2021-05-29T19%3A45%3A00%2B00%3A00&end_time=2029-05-29T23%3A00%3A00%2B00%3A00&env=prd&uid=25110

If anyone is in or around the Atlanta area, all I need are the two letters that go in front of the mybtv.net more importantly, any event number.  I can go from there
