### ISSUE TITLE
Change link to VIVA TV Russia

### ISSUE THREAD

**Issue by vasilyevmichail** [iptv-org/iptv#5315]
**_Channel Name:_** VIVARussia.ru
**_Country:_** RU
**_Broken Link (from playlist):_** https://live.prd.dlive.tv/hls/live/viva-russia.m3u8
**_Possible Replacement (optional):_** https://stream.funcontent.ru/hls/vivarussia/index.m3u8
**_Notes (optional):_** Information from https://viva-russia.ru/iptv.m3u

**Comment by LaneSh4d0w** [comment]
Both streams work on my side.

Certificate expired for funcontent.ru, use https://hls.myvideocontent.ru/hls/vivarussia/index.m3u8

**Comment by freearhey** [comment]
> https://live.prd.dlive.tv/hls/live/viva-russia.m3u8

The link is working again.

![image](https://user-images.githubusercontent.com/7253922/143620820-6a2c5483-666e-4079-9e66-fd126d0bf9f5.png)
