### ISSUE TITLE
Ken Tv 

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#5317]
**_Channel Name:_** Ken TV 
**_Country:_** IN
**_Broken Link (from playlist):_** https://stream.ufworldind.in/kentvlive/smil:kentv.smil/playlist.m3u8
**_Possible Replacement (optional):_** http://www.uomotv.live/live-tv/ken-tv.html
**_Notes (optional):_** xxx

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | https://stream.ufworldind.in/kentvlive/smil:kentv.smil/playlist.m3u8
-- | --
mediaManifest | https://stream.ufworldind.in/kentvlive/smil:kentv.smil/chunklist_w1514754968_b456000_sleng.m3u8


</body>
</html>

**Comment by freearhey** [comment]
![image](https://user-images.githubusercontent.com/7253922/143616751-317a5650-281b-4549-b01c-c43516d7485a.png)

**Comment by freearhey** [comment]
Broken link removed from playlist.

**Comment by Manipulativemachan** [comment]
http://www.uomotv.live/live-tv/ken-tv.html

**Comment by Manipulativemachan** [comment]
@freearhey this link works fine

**Comment by freearhey** [comment]
@Manipulativemachan same thing, now the stream works again for me too

**Comment by Manipulativemachan** [comment]
@freearhey @LaneSh4d0w can we add this channel now? the latest link works fine.

http://www.uomotv.live/live-tv/ken-tv.html

**Comment by LaneSh4d0w** [comment]
I will see for that.

**Comment by Dum4G** [comment]
Merged in https://github.com/iptv-org/iptv/pull/6111

**Comment by Manipulativemachan** [comment]
@Dum4G @LaneSh4d0w Not working on Kodi IPTV Client
