### ISSUE TITLE
Synergy TV

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#5318]
**Channel Name:** Synergy TV
**Channel ID:** SynergyTV.tt
**Country:** Trinidad and Tobago
**Language:** English
**Website:** https://webplayer.tegotv.com/tego-live-tv.php?channel=259
**Stream URL (optional):** N/A
**Notes (optional):** Wikipedia article: https://en.wikipedia.org/wiki/Synergy_TV Note: Like Trinidad and Tobago channels, this is broadcasting from TegoTV service with token.

**Comment by freearhey** [comment]
Closed in favor #12228
