### ISSUE TITLE
Trinidad and Tobago Television

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#5319]
**Channel Name:** Trinidad and Tobago Television (TTT)
**Channel ID:** TTT.tt
**Country:** Trinidad and Tobago
**Language:** English
**Website:** https://webplayer.tegotv.com/tego-live-tv.php?channel=255
**Stream URL (optional):** N/A
**Notes (optional):** Wikipedia article: https://en.wikipedia.org/wiki/Trinidad_and_Tobago_Television Note: Like Trinidad and Tobago channels, this is broadcasting from TegoTV service with token.

**Comment by LaneSh4d0w** [comment]
https://webplayer.tegotv.com/wms_auth.php POST with good UID.

**Comment by AntiPontifex** [comment]
Dead issue: please close.

**Comment by LaneSh4d0w** [comment]
> https://webplayer.tegotv.com/wms_auth.php POST with good UID then paste to link afterwards.
> 
> Might make an all in 1 solution if possible (if streams are defined by uid on streaming server, perfect for me)

Will try to make a plugin for this one.

**Comment by freearhey** [comment]
Closed in favor #12227
