### ISSUE TITLE
ATV+

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#5328]
**Channel Name:** ATV+
**Country:** PE
**Language:** Spanish
**Website:** https://www.atv.pe/envivo-atvmas
**Stream URL (optional):** N/A
**Notes (optional):** Geoblocked? The stream is tokenized

**Comment by robocopz** [comment]
Yes tokenized and only works with your IP.

**Comment by LaneSh4d0w** [comment]
https://d2tr4gdfol9ja.cloudfront.net/atv/smil:atv-mas.smil/playlist.m3u8

lol well it seems to work without token for me...

**Comment by GiovanniSebastian** [comment]
Any link for Global TV & LaTele (Both Channels from ATV)

**Comment by sguinetti** [comment]
> https://d2tr4gdfol9ja.cloudfront.net/atv/smil:atv-mas.smil/playlist.m3u8 https://d2tr4gdfol9ja.cloudfront.net/atv/smil:atv.smil/playlist.m3u8
> 
> lol well it seems to work without token for me...

Really? Without georestriction?

**Comment by LaneSh4d0w** [comment]
> 
> 
> > https://d2tr4gdfol9ja.cloudfront.net/atv/smil:atv-mas.smil/playlist.m3u8 https://d2tr4gdfol9ja.cloudfront.net/atv/smil:atv.smil/playlist.m3u8
> > lol well it seems to work without token for me...
> 
> Really? Without georestriction?

Not at all, using an Romanian IP right now.

**Comment by sguinetti** [comment]
These screenshots are Staff Médico (a local program from ATV+) and a programa for Cuatro TV (Spain). So these are OK.

**Comment by sguinetti** [comment]
> Any link for Global TV & LaTele? (Both Channels from ATV)

No. They were previously broadcast on tuteve but now there is no legal way to get them.

**Comment by LaneSh4d0w** [comment]
> 
> 
> > Any link for Global TV & LaTele? (Both Channels from ATV)
> 
> No. They were previously broadcast on tuteve but now there is no legal way to get them.

Didn't Global TV cease it's broadcasting in 2019 ? From what I read, it was changed to La Red, then was moved to NexTV (rights between ATV and América), changed name again to América Next, and ceased it's transmission on December 1st, 2019.

**Comment by LaneSh4d0w** [comment]
Limited to Peruvian people : https://dtv-latam-abc.akamaized.net/dash/live/2005172/dtv/dtvlatam_america_next_hd/master.mpd

**Comment by sguinetti** [comment]
> > > Any link for Global TV & LaTele? (Both Channels from ATV)
> > 
> > 
> > No. They were previously broadcast on tuteve but now there is no legal way to get them.
> 
> Didn't Global TV cease it's broadcasting in 2019 ? From what I read, it was changed to La Red, then was moved to NexTV (rights between ATV and América), changed name again to América Next, and ceased it's transmission on December 1st, 2019.
> 
> EDIT : My bad, it was **relaunched** in 2019. Weird things they made.

Global TV was also renamed Red TV, Red Global, NexTV, etc. Now is GlobaltTV.
