### ISSUE TITLE
TVS channel on malaysia

### ISSUE THREAD

**Issue by YukiRed** [iptv-org/iptv#5334]
I remember there's TVS on the list, but now it's gone?
I tried using different app to check, and all of it don't show it, while it still in the code.
So what's the problem?

**Comment by heroku-miraheze** [comment]
The problem is for cache, so, please clear cache and try again, and if the problem persists, you can try uninstalling the app and installing the app again. This solutions helps you. 👍

**Comment by heroku-miraheze** [comment]
And if the problem persists after reinstalling the app, you can try contacting our maintainer Freearhey.
Email to me and i will give to you an Freearhey email.

**Comment by YukiRed** [comment]
But it's freshly install app so theres no cache also
