### ISSUE TITLE
EPG info and more UK channels

### ISSUE THREAD

**Issue by cteq1** [iptv-org/iptv#534]
Hello
I recently came across your repository and am enjoying your hard work. I would like more UK contents inc UK Indian channels. Also EPG please

**Comment by freearhey** [comment]
If you think that playlists lack specific channels, please write their names. As for the EPG, the UK playlist already has a link to the program guide.

**Comment by cteq1** [comment]
Yes Like BBC/ITV/Ch4/5/Alibi/Forces/Gold/Dave/CBS crime/drama etc. I will check on EPG.

**Comment by thatnola6** [comment]
can I get those and ifollow if possible?

**Comment by freearhey** [comment]
- [x] BBC
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L134-L139
- [x] ITV
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L228-L237
- [x] Channel 4
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L162-L163
- [x] Channel 5
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L164-L165
- [x] Alibi
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L130-L131
- [x] Forces TV
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L216-L217
- [x] Gold
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L220-L221
- [x] Dave
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L182-L183
- [x] CBS Reality
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L158-L159
- [x] CBS Drama
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L156-L157
