### ISSUE TITLE
Star TV

### ISSUE THREAD

**Issue by Diomuzan247** [iptv-org/iptv#5343]
Channel Name: Star TV
Country: Turkey
Broken Link (from playlist):_** xxx
Possible Replacement (optional): https://www.startv.com.tr/canli-yayin
Notes (optional): We would appreciate it if the stream of the channel is fixed because my parents watch a lot to this channel

**Comment by Sphinxroot** [comment]
http://free.fullspeed.tv/query?url=http://www.dailymotion.com/video/x729whv

**Comment by Diomuzan247** [comment]
Thank you for your help!
