### ISSUE TITLE
Albanian channels 

### ISSUE THREAD

**Issue by besgjilani** [iptv-org/iptv#5350]
hi
can you plz try and fix Albanian channels as none of them working 
regards

**Comment by LaneSh4d0w** [comment]
Are you sure ? I've tested one random channel and it works. Are you talking about the TVMAK channels, by any chance ?

**Comment by besgjilani** [comment]
> Are you sure ? I've tested one random channel and it works. Are you talking about the TVMAK channels, by any chance ?

ive tested just now and from all of channels 3 are working

**Comment by freearhey** [comment]
@besgjilani Please specify the name of the specific channel that is not working for you.

**Comment by besgjilani** [comment]
RTKI1-2-3-4
klan kosova
tv dukagjini
koha vision
top channel
digitalb channels
tring channels 
alsat m
all that was working now they dont 
regards

**Comment by freearhey** [comment]
Everything still works for me.
![vlcsnap-2021-11-12-14h56m07s536](https://user-images.githubusercontent.com/7253922/141463441-84d042bf-8d27-47b1-899c-094306b2da3e.png)
