### ISSUE TITLE
RTB Sukmaindera

### ISSUE THREAD

**Issue by youngbluespring** [iptv-org/iptv#5351]
**Channel Name:** RTB Sukmaindera
**Country:** Brunei
**Language:** Malay
**Website:** https://www.rtbgo.bn/live/1229
**Stream URL (optional):** https://d19j8udk9agj55.cloudfront.net/smil:rtb1/chunklist_w1333328380_b1696000_sleng.m3u8
**Notes (optional):** xxx

**Comment by Sphinxroot** [comment]
http://www.rtb.gov.bn/Theme/Home.aspx

https://www.facebook.com/rtbbhes/live  NEWS Video Only

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="BN" tvg-language=""  tvg-logo="https://i.imgur.com/Mn7Asrz.png" group-title="",RTB Sukmaindera
https://d19j8udk9agj55.cloudfront.net/smil:rtb1/playlist.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="BN" tvg-language=""  tvg-logo="https://i.imgur.com/joZJneZ.jpg" group-title="",RTB Aneka
https://d19j8udk9agj55.cloudfront.net/smil:rtb2/playlist.m3u8

#EXTINF:-1 tvg-logo="https://i.imgur.com/VKc5GHi.png" group-title="",RTB Perdana (Missing)
http://www.rtb.gov.bn/SitePages/RTB%20Perdana.aspx

#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="BN" tvg-language=""  tvg-logo="https://i.imgur.com/4nZbuiY.png" group-title="",RTB GO
https://d19j8udk9agj55.cloudfront.net/smil:rtbgo/playlist.m3u8
