### ISSUE TITLE
Rede CNT (São Paulo)

### ISSUE THREAD

**Issue by eltoncomp** [iptv-org/iptv#5355]
**Channel Name:** Rede CNT (São Paulo)
**Country:** Brazil
**Language:** Portuguese
**Website:** www.cnt.com.br
**Stream URL (optional):** https://dd8umsy8yf96u.cloudfront.net/live/cnt-americana_240p414k/index.m3u8
**Notes (optional):** Repeater in São Paulo, the network is headquartered at Curitiba

**Comment by LaneSh4d0w** [comment]
Adaptive - https://dd8umsy8yf96u.cloudfront.net/live/cnt-americana.m3u8
