### ISSUE TITLE
Rede CNT (Curitiba)

### ISSUE THREAD

**Issue by eltoncomp** [iptv-org/iptv#5356]
**Channel Name:** Rede CNT (Curitiba)
**Country:** Brazil
**Language:** Portuguese
**Website:** www.cnt.com.br
**Stream URL (optional):** https://dd8umsy8yf96u.cloudfront.net/live/cnt-curitiba_240p414k/index.m3u8
**Notes (optional):** Stream from the network's headquarters

**Comment by LaneSh4d0w** [comment]
Adaptive - https://dd8umsy8yf96u.cloudfront.net/live/cnt-curitiba.m3u8
