### ISSUE TITLE
Villa Mantero TV

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#5368]
**Channel Name:** Villa Mantero TV
**Channel ID:** VillaManteroTV.ar
**Country:** AR
**Language:** Spanish
**Website:** https://tv.villamantero.com.ar/
**Stream URL (optional):** https://envivo.win/HLS/?canal=villamantero (?)
**Notes (optional):** no m3u8 stream link

**Comment by LaneSh4d0w** [comment]
> 
> 
> **Channel Name:** Villa Mantero TV **Country:** AR **Language:** Spanish **Website:** https://tv.villamantero.com.ar/ **Stream URL (optional):** https://envivo.win/HLS/?canal=villamantero (?) **Notes (optional):** no m3u8 stream link

no.ts file on answer.

**Comment by sguinetti** [comment]
This channel is not unique, there are more stream from http://envivo.win/. It would be useful for future testing.

**Comment by LaneSh4d0w** [comment]
> 
> 
> This channel is not unique, there are more stream from http://envivo.win/. It would be useful for future testing.

Best way would be to scrape it directly.

**Comment by fershady** [comment]
Work on vlc 
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
#EXTVLCOPT:http-referrer=https://envivo.win/HLS/?canal=villamantero
https://envivo.win/HLS/?canal=villamantero

**Comment by freearhey** [comment]
Closed in favor #9026
