### ISSUE TITLE
API = https://catalogapi.zee5.com/v1/channel/ *channel location on Zee5*

### ISSUE THREAD

**Issue by Achu2234** [iptv-org/iptv#5371]
API = https://catalogapi.zee5.com/v1/channel/ *channel location on Zee5*
Token = https://useraction.zee5.com/token/live.php

How to get them to work ?

-> Take the channel you want from the Zee5 Live TV (we'll say &Flix as an example)
-> Take this part of the URL ![image](https://user-images.githubusercontent.com/30985701/141470271-5da831a2-f91e-4e24-ad62-4e089cd2cb2f.png)
-> Paste it at the end of the API link, and you'll get all the results.
-> Scrape the stream URL, query the Token website and paste the result at the end of the stream
-> Enjoy !
![image](https://user-images.githubusercontent.com/30985701/141470612-4c7cf827-4617-4002-a4c5-8272a8d033a7.png)

_Originally posted by @LaneSh4d0w in https://github.com/iptv-org/iptv/discussions/5127#discussioncomment-1631542_

**Comment by LaneSh4d0w** [comment]
Wasn't needed to open an issue from this discussion. I'm already working on it.

**Comment by Achu2234** [comment]
> Wasn't needed to open an issue from this discussion. I'm already working on it.

by mistake sorry

**Comment by fotvnetwork** [comment]
Someone did this:
https://snehz5tv.herokuapp.com/?c=0-9-privéhd

**Comment by LaneSh4d0w** [comment]
> 
> 
> Someone did this: [https://snehz5tv.herokuapp.com/?c=0-9-privéhd](https://snehz5tv.herokuapp.com/?c=0-9-priv%C3%A9hd)

Yeah I've seen some implementations available.
