### ISSUE TITLE
Da Ai Television

### ISSUE THREAD

**Issue by youngbluespring** [iptv-org/iptv#5373]
**Channel Name:** Da Ai Television
**Channel ID:** DaAi1.tw
**Country:** Taiwan
**Language:** Chinese
**Website:** http://www.daai.tv/channel/1
**Stream URL (optional):** https://pulltv1.wanfudaluye.com/live/tv1.m3u8
**Notes (optional):** TV station owned by a Buddhist sect. There are two other "channels" but when I checked it was airing the same content

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/dfa0e06b6e22f99aa62e95c554d13742c4b13df1/streams/tw.m3u#L24-L25
