### ISSUE TITLE
Request more Vietnamese Channel Please

### ISSUE THREAD

**Issue by hiddenpants-dr** [iptv-org/iptv#538]
Would love more vietnamese channel please. :)

**Comment by freearhey** [comment]
Please specify which channels you mean.

**Comment by hiddenpants-dr** [comment]
sorry i dont no what channel has what and is available, would like vietnamese movie channel and tv channel if possible.

**Comment by freearhey** [comment]
I'm sorry, but without channel names, we won’t be able to help you.
