### ISSUE TITLE
Animax with english subtitles

### ISSUE THREAD

**Issue by reboot89** [iptv-org/iptv#539]
can you please upload a working Animax Asia HD channel with multi sub?

**Comment by freearhey** [comment]
Done.
https://github.com/iptv-org/iptv/blob/25a1f0698ed27d21baf7a57285e6487a3261c314/channels/id.m3u#L82-L85

**Comment by CHJ85** [comment]
This stream is dead. At least the URL has changed.
Here's one that actually does work. However, it does not have English subtitles. For now I guess it's better than nothing. But please reopen this ticket so that people can contribute here @freearhey .
https://cdn.jpus206.jpnettv.live/jptv/janimax_720/index.m3u8

**Comment by freearhey** [comment]
But just yesterday a new issue was created on this subject https://github.com/iptv-org/iptv/issues/1388 

And if you want to add a channel to the playlist it is not necessary for the issue to be active, you can just make pull request with it. If you don't know how to do it, here is guide: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#add-channel

**Comment by CHJ85** [comment]
Ah okay. Thank you! 😀

**Comment by DARKFIREX** [comment]
Hi !  How can watch it via ssiptv like convert this direct about animax japan channel please explain me I don’t understand I’m new in this

**Comment by DARKFIREX** [comment]
> This stream is dead. At least the URL has changed.
> Here's one that actually does work. However, it does not have English subtitles. For now I guess it's better than nothing. But please reopen this ticket so that people can contribute here @freearhey .
> https://cdn.jpus206.jpnettv.live/jptv/janimax_720/index.m3u8



> This stream is dead. At least the URL has changed.
> Here's one that actually does work. However, it does not have English subtitles. For now I guess it's better than nothing. But please reopen this ticket so that people can contribute here @freearhey .
> https://cdn.jpus206.jpnettv.live/jptv/janimax_720/index.m3u8 hi!! N new in this is possible to converter m3u format how ?? It’s because I’m new in this

**Comment by DARKFIREX** [comment]
I have a question the link about animax channel is possible to see via m3u list or no and I it possible how can I use it could you explain me please

**Comment by CHJ85** [comment]
> I have a question the link about animax channel is possible to see via m3u list or no and I it possible how can I use it could you explain me please
I don't think it will be added, dude. The stream is geo-locked to a select few parts of Asia.

**Comment by Tashrif24** [comment]
Kindly provide a link of Animax Asia with English subtitle
