### ISSUE TITLE
NBC  [KNBC-TV] 

### ISSUE THREAD

**Issue by rick999999** [iptv-org/iptv#5390]
Channel Name: western Feed of KNBC
Country: USA
Language: English
Website: https://www.nbclosangeles.com/
Stream URL (optional): xxx
Notes (optional): Need a western Feed of NBC Station.

not the news live

thx in advance!!!

**Comment by rick999999** [comment]
not the news live

**Comment by LaneSh4d0w** [comment]
We got it, some stuff is required before adding it.

**Comment by Central302** [comment]
[News Channel Added, Close and Clean The Issuse]

**Comment by MapGuy11** [comment]
Added
