### ISSUE TITLE
Teletoon

### ISSUE THREAD

**Issue by DetroitDevelopers** [iptv-org/iptv#5392]
**Channel Name:** Teletoon
**Country:** Canada
**Language:** French, English
**Website:** Teletoon.ca (English link)
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by gabrielbergeron** [comment]
@DetroitDevelopers Do you have a link to a page where you can stream it? Teletoon is usually hidden behind a paid wall I think.

**Comment by DetroitDevelopers** [comment]
I don't have stream links
