### ISSUE TITLE
Omega TV

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#5398]
**_Channel Name:_** Omega TV
**_Country:_** PE
**_Broken Link (from playlist):_** https://7.innovatestream.pe:19360/omega/omega.m3u8
**_Possible Replacement (optional):_** https://vaughn.live/omegatelevision
**_Notes (optional):_** Stream with flv format.

**Comment by LaneSh4d0w** [comment]
https://stream2-cdn.vaughnsoft.net/play/live_omegatelevision.flv

**Comment by LaneSh4d0w** [comment]
> 
> 
> **_Channel Name:_** Omega TV **_Country:_** PE **_Broken Link (from playlist):_** https://7.innovatestream.pe:19360/omega/omega.m3u8 **_Possible Replacement (optional):_** https://vaughn.live/omegatelevision **_Notes (optional):_** Stream with flv format.

something rather interesting, they have a radio stream on http://51.161.87.165:8008/listen.pls?sid=1

**Comment by trancer1994** [comment]
How do you scan websites? I want to scan teleosmedia.com to look for streams but don't know how.

**Comment by LaneSh4d0w** [comment]
> How do you scan websites? I want to scan teleosmedia.com to look for streams but don't know how.

I use https://search.censys.io
