### ISSUE TITLE
Court TV

### ISSUE THREAD

**Issue by Prajwal-Koirala** [iptv-org/iptv#5406]
**Channel Name:** CourtTV
**Country:** USA
**Language:** English
**Website:** [CourtTV](https://www.courttv.com/)
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by fotvnetwork** [comment]
https://cdn-katz-networks-01.vos360.video/Content/HLS/Live/channel(courttv)/index.m3u8

**Comment by Prajwal-Koirala** [comment]
Was this recently added?
I just found this on the channel list on my FireTV
