### ISSUE TITLE
EbS

### ISSUE THREAD

**Issue by youngbluespring** [iptv-org/iptv#5409]
**Channel Name:** Europe by Satellite
**Country:** European Union
**Language:** English
**Website:** https://audiovisual.ec.europa.eu/en/
**Stream URL (optional):** https://euc-live.fl.freecaster.net/live/eucom/ebs-audio_int=96000-video=2600000.m3u8
**Notes (optional):** Tried to find the region codes...

**Comment by Sphinxroot** [comment]
#EXTINF:-1,EBS
https://euc-live.fl.freecaster.net/live/eucom/ebs.m3u8
#EXTINF:-1,EBS+
https://euc-live.fl.freecaster.net/live/eucom/ebsp.m3u8

**Comment by freearhey** [comment]
Already on the playlist:

https://github.com/iptv-org/iptv/blob/4c572709d5952364058e5ef306eb4be6608ce1f3/channels/be.m3u#L12-L13
