### ISSUE TITLE
TVi24

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#5415]
Request:

Channel Name: TVI24
Country: Portugal
Language: Portugal

Thank you.

**Comment by LaneSh4d0w** [comment]
Assuming you've asked for TVI24.

**Comment by spotanjo3** [comment]
Yes. Typo. I will edit it now. :)

**Comment by LaneSh4d0w** [comment]
Code-way to get the streaming link, from my own service : 

```
app.get("/portugal/tvi24", function(req,res) {
    fetch("https://services.iol.pt/matrix?userId=")
        .then(response => response.text())
        .then(text => {
            res.redirect("https://video-auth2.iol.pt/live_edge/tvi24_abr/playlist.m3u8?wmsAuthSign=" + text)
        })
});
```

**Comment by spotanjo3** [comment]
Can you add it to:

https://iptv-org.github.io/iptv/countries/pt.m3u

**Comment by spotanjo3** [comment]
> Code-way to get the streaming link, from my own service :
> 
> ```
> app.get("/portugal/tvi24", function(req,res) {
>     fetch("https://services.iol.pt/matrix?userId=")
>         .then(response => response.text())
>         .then(text => {
>             res.redirect("https://video-auth2.iol.pt/live_edge/tvi24_abr/playlist.m3u8?wmsAuthSign=" + text)
>         })
> });
> ```

I can't view it. Is there a way I can see it ? Sorry about it.

**Comment by spotanjo3** [comment]
Thanks for added but it is not on my m3u file yet.

**Comment by LaneSh4d0w** [comment]
It'll appear on next bot update if it was added.

**Comment by spotanjo3** [comment]
Thanks. And it will increase the numbers according to Playlists by country in your link also ?

**Comment by LaneSh4d0w** [comment]
They will be changed on next update too, depending on the availability of the different channels.

**Comment by spotanjo3** [comment]
The channel is up to 48 but none of the channels I posted are available yet. I guess I will have to wait. Keep up the good work, thought.
