### ISSUE TITLE
Canal 11

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#5418]
Request:

Channel Name: Canal 11 
Country: Portugal
Language: Portugal

Thank you.

**Comment by LaneSh4d0w** [comment]
https://d2ve4fchffi4n1.cloudfront.net/out/v1/df356edd16f3434ab417f2c48cb1d516/index.m3u8

**Comment by spotanjo3** [comment]
Awesome. Work very well. Can you add it to:

https://iptv-org.github.io/iptv/countries/pt.m3u

**Comment by spotanjo3** [comment]
Test it on VLC Player. The video is glitch.
