### ISSUE TITLE
Diema sport link down inside bg.m3u

### ISSUE THREAD

**Issue by Haroldyolo** [iptv-org/iptv#5425]
**_Channel Name:_** Diema sport HD
**_Country:_** Bulgaria
**_Broken Link (from playlist):_** bg.m3u
**_Possible Replacement (optional):_** N/A
**_Notes (optional):_**

**Comment by LaneSh4d0w** [comment]
https://github.com/iptv-org/iptv/pull/3105#issuecomment-974670792

**Comment by freearhey** [comment]
"Diema Sport" channels cannot be added to the playlist due to claims of copyright holders: https://github.com/github/dmca/blob/master/2020/09/2020-09-16-dfl.md
