### ISSUE TITLE
iFILM English

### ISSUE THREAD

**Issue by samg80** [iptv-org/iptv#5426]
**_Channel Name:_** ifilm (English version)
**_Country:_** Iran
**_Broken Link (from playlist):_** N/A this is the online stream link https://en.ifilmtv.ir/
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** I had a request to add this channel back after it was missing from the list. It was added back to the list but now the channel is not working. When I play the channel, it things it is a music channel. It display a CD and there's a static wave going up and down the screen without sound. I have tried other ways to display the channel but it always shows the CD and then stops working. 
![2021-11-19 17 56 33](https://user-images.githubusercontent.com/40507207/142732996-4770185b-df33-4c6e-b907-96347d73fdb7.jpg)

**Comment by LaneSh4d0w** [comment]
Stream is offline on presstv.ir.

One .ts file is given, nothing else.

Since it's the only official source we have (there's some iFilm alternatives around but they're often in Persian only), the only thing we can do (like last time) is either wait, or notify PressTV via email about their stream being offline.

**Comment by samg80** [comment]
Thanks for the quick follow up and the info. I can follow up w/PressTV if you would like, just tell me what to ask.

**Comment by samg80** [comment]
Just an FYI, the channel is working. I believe the reason for the broken stream might be due to the fact that the ifilm English has been migrated to (.tv) rather than the (.ir). Just something that I thought I share, if that might be the reason.

**Comment by samg80** [comment]
This channel has stopped working again and I have similar issues as before, buffers constantly, shows music and CD track, no voice or pic.

**Comment by LaneSh4d0w** [comment]
Like last time, nothing much but to wait for it to come back.
