### ISSUE TITLE
US channels

### ISSUE THREAD

**Issue by thatnola6** [iptv-org/iptv#543]
Hi I love the work you have done! Is it possible to get USA channels, cinemax, showtime, starz, sundance, more local abc, cbs, nbc, fox for Texas, Louisiana, Georgia, Florida, south and north carolina? Thanks in advance!

**Comment by LibertyDrew13** [comment]
Arizona locals: Abc,FOX, Cbs, Nbc also I will just go ahead and request adult channels be added....for a friend

**Comment by emengard1968** [comment]
please give me some US sports playlist. thanks

**Comment by freearhey** [comment]
- [ ] ABC13 Houston (KTRK-TV)
- [ ] ABC Columbia (WOLO-TV)
- [x] CBS Dallas (KTVT)
- [ ] NBC 5 Dallas-Fort Worth (KXAS-TV)
- [x] Fox 4 Dallas-Fort Worth (KDFW)
- [x] WAFB 9 News
- [x] FOX 8 News (WJW)
- [x] CBS46 (WGCL-TV)
- [ ] FOX 5 Atlanta (WAGA-TV)
- [ ] WPLG Local 10
- [ ] WPEC CBS12 News
- [ ] NBC 6 South Florida (WTVJ)
- [ ] FOX 13 Tampa Bay (WTVT)
- [ ] ABC11 WTVD
- [ ] CBS 17 (WNCN)
- [ ] WRAL-TV
- [ ] WIS News 10
- [ ] FOX Carolina (WHNS)
- [x] Cinemax
https://github.com/iptv-org/iptv/blob/6abfa134b0988d6e8f61de55094982d502342904/channels/us.m3u#L970-L981
- [x] Showtime
https://github.com/iptv-org/iptv/blob/6abfa134b0988d6e8f61de55094982d502342904/channels/us.m3u#L982-L987
- [x] Starz 
https://github.com/iptv-org/iptv/blob/6abfa134b0988d6e8f61de55094982d502342904/channels/us.m3u#L1244-L1273
- [x] Sundance
https://github.com/iptv-org/iptv/blob/6abfa134b0988d6e8f61de55094982d502342904/channels/us.m3u#L1274-L1275

**Comment by Knrd2** [comment]
Hi, great work youre doing here! 
I would love to watch some US channels but i cant watch most of them on TV, VLC or GSE... do you have a hint how to get the channels to work?

**Comment by freearhey** [comment]
@Knrd2 unfortunately, most of the links added earlier stopped working and they had to be removed from the playlist.

**Comment by freearhey** [comment]
Closed in favor #1942

**Comment by Ctownpa** [comment]
How to usa local network channels not news networks. Thanks and please.
