### ISSUE TITLE
Chilevision

### ISSUE THREAD

**Issue by xfrcc** [iptv-org/iptv#5431]
**_Channel Name:_** Chilevision
**_Country:_** Chile
**_Broken Link (from playlist):_** http://186.67.117.178:8081/play/a00y
**_Possible Replacement (optional):_** http://chv-m3u.chorroaeboy.repl.co
**_Notes (optional):_** Before there were two alternatives, but they removed the last one apparently, though the other is not working

**Comment by LaneSh4d0w** [comment]
> **_Channel Name:_** Chilevision **_Country:_** Chile **_Broken Link (from playlist):_** http://186.67.117.178:8081/play/a00y **_Possible Replacement (optional):_** http://chv-m3u.chorroaeboy.repl.co **_Notes (optional):_** Before there were two alternatives, but they removed the last one apparently, though the other is not working

Second one is geo-locked to Chile only.

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/chv_003cl
