### ISSUE TITLE
Cozi TV

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#5435]
Request:

Channel Name: Cozi
Country: America
Language: English

Thank you.

**Comment by what-a** [comment]
We now have Cozi TV on IPTV-org.
@MapGuy11 Thank you!

![image](https://user-images.githubusercontent.com/88639906/150702148-7215a1a8-df6a-4228-b306-afb59992be5d.png)

**Comment by spotanjo3** [comment]
THANK YOU ! However.. something is wrong with it. The closed captioning is scramble somewhat. An antenna version on tv didn't. WCAU-DT2 is Philadelphia, Pennsylvania and seems to have a problem with closed captioning.

WYCN-LD - Boston, Massachusetts. Works fine but can you added that too? 
--


<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

**Comment by what-a** [comment]
Boston isn't in the cards, but we (esp. MapGuy11) are working on:
Cozi TV Los Angeles CA (KNBC2)   (432p)
Cozi TV San Jose CA (KNTV2)   (432p)
Cozi TV Philadelphia PA   (WCAU2) (432p)
Cozi TV San Diego CA (KNSD2)   (432p)
Cozi TV New York NY (WNBC2)   (432p)
Cozi TV Indianapolis IN   (WRTV3) (432p)

**Comment by spotanjo3** [comment]
I see. WYCN-LD in Boston works here. Why can't you find it ? That's strange.

**Comment by spotanjo3** [comment]
Unfortunately.. Both have some scramble closed captioning. As you said you are working on addition more COZI so I guess I can wait.

**Comment by spotanjo3** [comment]
I know this is old but I dont know if Cozi TV m3u8 is available somewhere ?
