### ISSUE TITLE
Lolly Kids

### ISSUE THREAD

**Issue by robocopz** [iptv-org/iptv#5439]
Channel Name: Lolly Kids
Channel ID: LollyKids.uk
Country: UK
Language: English
Website: https://www.lollykidstv.com/live

**Comment by LaneSh4d0w** [comment]
Streaming server seems to be mimyunimediagroup.com

Stream endpoint is sldp/LollyKids_720p

**Comment by freearhey** [comment]
Closed in favor #12222
