### ISSUE TITLE
BabyFirst TV

### ISSUE THREAD

**Issue by larsenv** [iptv-org/iptv#5440]
**Channel Name:** BabyFirst TV
**Country:** United States
**Language:** English
**Website:** https://www.babyfirsttv.com/
**Stream URL (optional):** https://babyfirst.akamaized.net/hls/live/2028842/bftvusaott/playlist.m3u8
**Notes (optional):** Grabbed from their mobile app by proxying.

**Comment by larsenv** [comment]
I didn't notice that this is already on the list. But this livestream seems higher quality than the stream currently used.

**Comment by MapGuy11** [comment]
@larsenv Could you go in-depth on how you sniffed this URL from their mobile app. I will remove your comment once I see it. Thanks. A iptv-org contributor/admin

**Comment by robocopz** [comment]
It stopped working
