### ISSUE TITLE
FOX 9 ST Paul Minneapolis MN (KMSP)

### ISSUE THREAD

**Issue by jhedfors** [iptv-org/iptv#5446]
**Channel Name:** FOX 9 ST Paul Minneapolis MN (KMSP)
**Country:** USA
**Language:** English
**Website:** https://www.fox9.com/live
**Stream URL (optional):**

**Comment by Sphinxroot** [comment]
https://dcs-live.mp.lura.live/server/play/p0dr1kQiGl4wtzj1/manifest.m3u8? + token and need to be streamlinked

**Comment by jhedfors** [comment]
It looks like this was fixed with #5640
