### ISSUE TITLE
Star Vijay India

### ISSUE THREAD

**Issue by Angu0083** [iptv-org/iptv#5452]
Channel Name: Star Vijay
Channel ID: StarVijay.in
Country: India
Language: Tamil

**Comment by LaneSh4d0w** [comment]
@freearhey https://en.wikipedia.org/wiki/Star_Vijay => Asianet Star Communications : https://en.wikipedia.org/wiki/Asianet_Star_Communications

**Comment by freearhey** [comment]
@LaneSh4d0w I used lyngsat as a source: https://www.lyngsat.com/tvchannels/hk/Star-Vijay-India.html

**Comment by LaneSh4d0w** [comment]
That's maybe because of a licencing agreement, i don't know.

To push things even further, we can even say it's US, Star being a Walt Disney subsidiary. (Asianet and Disney made an alliance, becoming Asianet Star Communications and they have control all over the Asianet channels.)

**Comment by freearhey** [comment]
Closed in favor #12220
