### ISSUE TITLE
NOS Comunicações SA (SPORT TV 1, 2, 3, 4, etc. BENFICA TV (BTV), and ELEVEN SPORT among others )

### ISSUE THREAD

**Issue by jo-a11y** [iptv-org/iptv#5453]
Hello,

I had posted a video on social media about your IPTV service.

I received a complaint from NOS Comunicações SA which accuses my video of allowing the illegal broadcasting of some of their TV channels (SPORT TV 1, 2, 3, 4, etc. BENFICA TV (BTV), and ELEVEN SPORT among others ).

What is it? Did you also receive a deletion request from them? Is this a legitimate request? What have you done ?

Thank you for your reply.

**Comment by spotanjo3** [comment]
Use VPN
