### ISSUE TITLE
Télé Liban

### ISSUE THREAD

**Issue by rydeontime** [iptv-org/iptv#5454]
**Channel Name:** tele liban
**Country:** lebanon
**Language:** arabic
**Website:** www.teleliban.com.lb
**Stream URL (optional):** http://teledunet.com:8080/live/azrotv/azrotv2021/10012.m3u8
  http://8.21.48.19:7777/TeleLiban_HD.m3u8
**Notes (optional):** dead url?? both

**Comment by LaneSh4d0w** [comment]
https://cdn.catiacast.video/abr/ed8f807e2548db4507d2a6f4ba0c4a06/playlist.m3u8

Most certainly referer locked.

**Comment by rydeontime** [comment]
tele liban appears on this downloadable link, certainly for android, im unsure for apple phones. but on android works fine, trying for iptv , thanks if anyone can help
watchlb.ddns.net/watchlb

**Comment by brossmee** [comment]
You can watch al Jadeed Now at : 
http://mobioui9.com/v/arabic/arab3/aljadeed.php
