### ISSUE TITLE
Fix: xxx

### ISSUE THREAD

**Issue by Johelectrix09** [iptv-org/iptv#5459]
Both the Japanese stream are unable to play for now I wish it is just by this day because I want to know if there's maintenance on your side ma'am/sir

**Comment by Central302** [comment]
Please Try This. (Linked to Nippon TV).
http://redlabmcdn.s.llnwi.net/nv02/ryowa3/index.mpd

Notice That Not Working on iOS. and Tested in Pot Player.

**Comment by Johelectrix09** [comment]
Well the link that you sent to me didn't work also

**Comment by Johelectrix09** [comment]
But do you have any ideas when would other channels in Japan or others etc. would stream again??

**Comment by freearhey** [comment]
@Johelectrix09 Please specify which channel you are talking about.

**Comment by Johelectrix09** [comment]
Animax and Aniplus

**Comment by Johelectrix09** [comment]
Because other channels like Fuji TV and TBS are back for now

**Comment by Johelectrix09** [comment]
That's why it can't be played in VLC

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel
