### ISSUE TITLE
TBS CS 1

### ISSUE THREAD

**Issue by Johelectrix09** [iptv-org/iptv#5460]
**CS-TBS 1:** xxx
**JAPAN :** xxx
`**Japanese:**` xxx
**Website:** xxx
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by 771725917** [comment]
اطلب قناه

**Comment by 771725917** [comment]
اين إشعار المشهده

**Comment by 771725917** [comment]
mstwrshwyhsyn@gmail.com

**Comment by freearhey** [comment]
Closed in favor #6755
