### ISSUE TITLE
Paramount+ or Paramount Plus

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#5466]
Request:

Channel Name: Paramount+ (Not Pluto related)
Country: America
Language: English

Thank you.

**Comment by freearhey** [comment]
As I know Paramount+ is a VOD service (https://en.wikipedia.org/wiki/Paramount%2B) and in this repository we only collect links to TV channels.

**Comment by spotanjo3** [comment]
I am not sure I understand.

**Comment by freearhey** [comment]
Paramount+ is not a TV channel but a service like Netflix, Disney+ or Apple TV+, that's why we can't add it to the playlist.

**Comment by spotanjo3** [comment]
Oh, yes. Sorry about that. Thank you.
