### ISSUE TITLE
Animax Japan

### ISSUE THREAD

**Issue by YOUDEADMOM** [iptv-org/iptv#5478]
**_Channel Name:_** Animax japan   and Animax japan (English Subs)
**_Country:_** Japan
**_Broken Link (from playlist):_**[ xxx](https://iptv-org.github.io/iptv/countries/jp.m3u)
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** [xxx](https://ibb.co/mBTfPYQ) Screenshot THe german text say  "The file cannot be loaded".

**Comment by LaneSh4d0w** [comment]
https://redlabmcdn.s.llnwi.net/nv02/bs14/index.mpd (in next incoming PR, waiting for approval)

**Comment by cloud90** [comment]
how to play this link: https://redlabmcdn.s.llnwi.net/nv02/bs14/index.mpd in vlc?
