### ISSUE TITLE
Newsmax TV

### ISSUE THREAD

**Issue by eltoncomp** [iptv-org/iptv#5509]
**_Channel Name:_** Newsmax TV
**_Country:_** US
**_Broken Link (from playlist):_** http://nmxlive.akamaized.net/hls/live/529965/Live_1/master.m3u8
**_Possible Replacement (optional):_** https://nmxlive.akamaized.net/hls/live/529965/Live_1/index_720.m3u8 https://nmxlive.akamaized.net/hls/live/529965/Live_1/index_288.m3u8 https://nmxlive.akamaized.net/hls/live/529965/Live_1/index.m3u8
**_Notes (optional):_** There was three Newsmax TV streams on the playlist, but only one remains, and it isn't working. I've added the XUMO stream (one of the two that have been removed) in my favorites on SSIPTV and it works. The three replacement links are different resolutions, but they are from the same sever. Consider also adding back the XUMO stream.

**Comment by Plus018** [comment]
https://newsmax.codeautoplaycdn2.workers.dev/ Opened
