### ISSUE TITLE
Junior TV

### ISSUE THREAD

**Issue by Agumonz98** [iptv-org/iptv#5510]
**Channel Name:** Junior TV
**Channel ID:** JuniorTV.al
**Country:** Albania
**Language:** Albanian
**Website:** http://www.digitalb.al/
**Stream URL (optional):** (Don't have one)
**Notes (optional):** Again I'm just look for a good working stream for this channel, doesn't matter if its a live-stream or m3u8. (Also all the Albanian/Macedonian streams from #4986 don't seem to work anymore)

**Comment by freearhey** [comment]
Closed in favor #12219
