### ISSUE TITLE
A-TX

### ISSUE THREAD

**Issue by Johelectrix09** [iptv-org/iptv#5515]
**_A-TX :_** xxx
**_Japan:_** xxx
**_Broken Link (from playlist):_** xxx
**_Possible Replacement (optional):_** xxx
**_Notes (optional):_** xxx

**Comment by Central302** [comment]
Error "SEC_ERROR_EXPIRED_CERTIFICATE" at Firefox.

**Comment by AstaFatherSatan666** [comment]
The stream started working suddenly

**Comment by AstaFatherSatan666** [comment]
https://sub2.neetball.net/live/neet.m3u8

**Comment by AstaFatherSatan666** [comment]
Ssl is broken tho

**Comment by Dum4G** [comment]
![image](https://user-images.githubusercontent.com/5430116/143780159-a45ae962-f6b0-49f0-9608-e4936b0abcfb.png)
Works now, takes a while to load and the server is probably experiencing high loads. Closing due to stream being Not 24/7
