### ISSUE TITLE
G4

### ISSUE THREAD

**Issue by EnigmaXtreme** [iptv-org/iptv#5520]
**Channel Name:** G4
**Channel ID:** G4.us
**Country:** USA
**Language:** English
**Website:** G4tv.com

**Comment by MapGuy11** [comment]
What's crazy is a gaming-focused channel is only on Cable? Who does cable anymore at least younger people? They event state it in their website.
"Cable TV: At your Aunt Edna’s house? There’s a good chance we’ll be on there (most likely an astronomically high numbered channel - check your local listings). Right now, we’re carried on Verizon Fios, Cox, and Xfinity TV and will be on many more soon!"
Even though they are on Twitch and YouTube that isn't the full schedule.

**Comment by EnigmaXtreme** [comment]
I mean, the network IS owned by Comcast.

**Comment by freearhey** [comment]
Closed in favor #12218
