### ISSUE TITLE
Playlists Grouped by Primary Language?

### ISSUE THREAD

**Issue by nathanmuccino** [iptv-org/iptv#554]
Are there any plans to implement playlists grouped by primary language? For example, I use the 'index.full.m3u' and It would be cool if it was grouped by country, content, and language. That way English/Spanish/French/etc could be selected to group channels regardless of each channel's physical location.

**Comment by freearhey** [comment]
There are such plans. But for this, in the description for each channel, we will need to add an attribute indicating the language. And since the playlist now has about 8000 channels, this can take a very long time.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv#playlists-by-language

Done.
