### ISSUE TITLE
Z Living USA

### ISSUE THREAD

**Issue by robocopz** [iptv-org/iptv#5546]
Channel Name: ZLiving
Country: USA
Broken Link: https://f8e7y4c6.ssl.hwcdn.net/zlivingusa_r/index.m3u8

**Comment by LaneSh4d0w** [comment]
Token can be found here : https://useraction.zee5.com/token/live.php

Basically this should be added to all streams.

**Comment by trancer1994** [comment]
How do you make it work with the referer?

**Comment by LaneSh4d0w** [comment]
> How do you make it work with the referer?

On streamlink, add "--http-header "Referer=https://zliving.com/" before putting the stream link.
On VLC : 

```
#EXTVLCOPT:http-referrer=https://zliving.com/
```

**Comment by trancer1994** [comment]
I still can't get it to open even on VLC even with the parameters you specified. Is there something I'm missing?

**Comment by LaneSh4d0w** [comment]
> I still can't get it to open even on VLC even with the parameters you specified. Is there something I'm missing?

Maybe there's also an user-agent to add. Let me check.
