### ISSUE TITLE
Fix: GEM Series

### ISSUE THREAD

**Issue by mrbooshehri** [iptv-org/iptv#5561]
**_Channel Name:_** GEM Series
**_Country:_** Iran
**_Broken Link (from playlist):_** https://stream-cdn.gemonline.tv/live/gemseries/index.m3u8
**_Possible Replacement (optional):_** http://65.21.196.79/gem_series/master.m3u8

**Comment by esi8bitman** [comment]
Still does not work!

I tried with https://ca-rt.onetv.app/gemseries/index-0.m3u8 and http://65.21.196.79/gem_series/master.m3u8 but still does not work!!

any idea??
