### ISSUE TITLE
Fix: GEM Fit

### ISSUE THREAD

**Issue by mrbooshehri** [iptv-org/iptv#5567]
**_Channel Name:_** GEM Fit
**_Country:_** Iran
**_Broken Link (from playlist):_** https://stream-cdn.gemonline.tv/live/gemfit/index.m3u8
**_Possible Replacement (optional):_** http://65.21.196.79/30tv/master.m3u8

**Comment by alireza1974** [comment]
On my Smart TV and on my android box I have broken stream for all channels of GEM group, would you please help me how can I fix it? I tried different apps also Televizio on my smartphone without success.

**Comment by Dum4G** [comment]
Some links are dead and we haven't found an alternative yet

**Comment by mrbooshehri** [comment]
> On my Smart TV and on my android box I have broken stream for all channels of GEM group, would you please help me how can I fix it? I tried different apps also Televizio on my smartphone without success. 

If you live in Iran try to stream whlie you are connected to a vpn service, maybe strame links are access denied from there. Personally I use the same app, Televizio, and it's work fine for me, then the only thing that comes to my mind is the link is unreachable.
