### ISSUE TITLE
TVA Montreal ( CFTM-HD)

### ISSUE THREAD

**Issue by SmogTDI** [iptv-org/iptv#5605]
Channel Name: TVA Montreal ( CFTM-HD)
Country: Canada GEOBLOCKED
Language: French
Website: https://www.qub.ca/tvaplus/tva/en-direct
Stream URL (optional):  https://tvalive-nondai.akamaized.net/Content/HLS/Live/channel(a7315e07-037c-12a8-bdc8-da7bd513da9d)/02.m3u8

**Comment by Dum4G** [comment]
![Screenshot_20211207-053903](https://user-images.githubusercontent.com/5430116/144956155-c404bc46-3cba-4ed5-bd38-028ab9a20624.jpg)
Confirm working

**Comment by fershady** [comment]
Video but no audio.

**Comment by Dum4G** [comment]
> Video but no audio.

Change 02 to index and it will be fixed

**Comment by Dum4G** [comment]
Already is in the playlist
