### ISSUE TITLE
NHL Centre Ice 1

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#5613]
**Channel Name:** NHL Center Ice
**Channel ID:** NHLCenterIce1.us
**Country:** USA
**Language:** English
**Website:** https://www.nhl.com/info/center-ice
**Stream URL (optional):**
**Notes (optional):** HD please!

**Comment by AntiPontifex** [comment]
Dead issue: please close.

**Comment by freearhey** [comment]
Closed in favor #12215
