### ISSUE TITLE
NHL Network

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#5614]
**Channel Name:** NHL Live
**Country:** USA
**Language:** English
**Website:** https://nhllive.com
**Stream URL (optional):**
**Notes (optional):** HD please!

**Comment by Intrudr-Sec** [comment]
You can watch on nhl66.ir

**Comment by jphilippe2017** [comment]
Thanks for that link Intrudr-Sec !

I will for sure check it out :)

**Comment by what-a** [comment]
Not resolved, but closing this while work continues on as #6304
