### ISSUE TITLE
bfmtv

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#5619]
**Channel Name:** bfmtv
**Country:** USA
**Language:** French
**Website:** https://www.bfmtv.com
**Stream URL (optional):** 
**Notes (optional):**

**Comment by LaneSh4d0w** [comment]
Not quite sure there's an existing US version of BFM TV that exists. It might be the French version (the same one we have in France) that's being redistributed to Canada.

**Comment by MapGuy11** [comment]
> Not quite sure there's an existing US version of BFM TV that exists. It might be the French version (the same one we have in France) that's being redistributed to Canada.

There isn't a US version can I close this?

**Comment by LaneSh4d0w** [comment]
Safe to close yes

**Comment by jphilippe2017** [comment]
Hi, Apparently, there is a BFM TV version in France, that is other than the
one now available, that is more of the normal, regular and main one of BFM
TV in france,
if ever you can find and add it to the France section.

Thank you and have a great day!!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by fotvnetwork** [comment]
BFMTV is French
https://bfmtvalive1-a.akamaihd.net/316e573c8855429887f65feb189fb5a7/eu-central-1/876450610001/7b4151e1e2434a7cacdb9936db7a7910/playlist_ssaiM.m3u8
