### ISSUE TITLE
WCBS

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#5620]
**Channel Name:** CBS
**Country:** USA
**Language:** English
**Website:** https://www.cbs.com
**Stream URL (optional):** 
**Notes (optional):** Not a local channel, the original main US CBS channel in HD please

**Comment by MapGuy11** [comment]
> 
> 
> 
> 
> **Channel Name:** CBS
> **Country:** USA
> **Language:** English
> **Website:** https://www.cbs.com
> **Stream URL (optional):** 
> **Notes (optional):** Not a local channel, the original main US CBS channel in HD please
> 

Working on it can't tell you when it will be done. Stay tuned :)

**Comment by jphilippe2017** [comment]
Thanks so much!
