### ISSUE TITLE
WNBC

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#5621]
**Channel Name:** NBC
**Country:** USA
**Language:** English
**Website:** https://www.nbc.com
**Stream URL (optional):** 
**Notes (optional):** Not the local channel, the original NBC US in HD please!

**Comment by MapGuy11** [comment]
> 
> 
> 
> 
> **Channel Name:** NBC
> **Country:** USA
> **Language:** English
> **Website:** https://www.nbc.com
> **Stream URL (optional):** 
> **Notes (optional):** Not the local channel, the original NBC US in HD please!
> 

Working on it can't tell you when it will be done. Stay tuned :)

**Comment by jphilippe2017** [comment]
Great, thank you so much!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MapGuy11** [comment]
You can watch NBC Boston for Eastern Time NBC programming.
