### ISSUE TITLE
RDI Sport

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#5622]
**Channel Name:** RDI Sport
**Channel ID:** RDSHD.ca
**Country:** Canada
**Language:** French
**Website:** https://ici.radio-canada.ca/sports
**Stream URL (optional):** 
**Notes (optional):** HD if possible! Please also add this channel in the USA Sport section, if at all possible :)

**Comment by gabrielbergeron** [comment]
@jphilippe2017 Do you have a membership to RDS? They seem to have some pages to stream it but you need to pay a membership. I can't find the stream link since I don't have a membership.
https://www.rds.ca/emissions/en-direct

**Comment by jphilippe2017** [comment]
I do not but if anyone reads this post and does, please share:)
Thanks

**Comment by freearhey** [comment]
Closed in favor #5956
