### ISSUE TITLE
KGO-TV News

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#5626]
**Channel Name:** KGO-TV News Live
**Country:** USA-San Francisco
**Language:** English
**Website:** 
**Stream URL (optional):**  https://api.abcotvs.com/v3/kgo/m3u8/url?id=530971&key=yuemix
**Notes (optional):** (https://github.com/iptv-org/iptv/discussions/5522)
Link Will Redirect to m3u8, and Please Remove this from Playlist After mybtv commit.

**Comment by LaneSh4d0w** [comment]
We still can keep it as alternative link I think.
