### ISSUE TITLE
Strange Paradise

### ISSUE THREAD

**Issue by what-a** [iptv-org/iptv#5631]
**Channel Name:** Strange Paradise
**Channel ID:** StrangeParadise.us
**Country:** USA
**Language:** English
**Website:** www.filmon.com/channel/strange-paradise
**Stream URL (optional):** https://edge-1282-ch-gv.filmon.com/live/3869.high.stream/playlist.m3u8?id=035bca1a71b11fce016d28acd3dbea51cbc96ddfe5b9ed3f8fe3286df6a738d31afee2380e236e0af112122a5c1df3a0203a51d8b3e4a4f9a7437cd070b7dd9e67d18821290ba7186e8e69608b09fcb4518dc9a9d0e9b0356147159e1bdd55df1aeb8ab0d8a864968f3e2a43f0c1553de885a6ea9417fc787fa604d1328e5e13e87c40d649b527981b73fd755f324b1b99c237cde5103a99
**Notes (optional):** As you guessed, the above link only worked for a few moments.

**Comment by LaneSh4d0w** [comment]
I *think* we can use streamlink for that.

http://free.fullspeed.tv/iptv-query?streaming-ip=http://www.filmon.com/channel/strange-paradise

**Comment by kiiiihunter** [comment]
Hey @LaneSh4d0w 
I've been having trouble getting a similar link to play without it stopping after a minute. If you might know the answer to this really would appreciate it. 

The filmon link is: https://www.filmon.com/channel/eri-tv

I tried doing what you mentioned and used this link below in VLC: http://free.fullspeed.tv/iptv-query?streaming-ip=http://www.filmon.com/channel/eri-tv   ,but when I play it on VLC it stops after a minute or so.  Is there a way I can somehow play/stream it without it stopping every minute. Am I missing something.

**Comment by freearhey** [comment]
Closed in favor #12212
