### ISSUE TITLE
Videoland Sport

### ISSUE THREAD

**Issue by inpot** [iptv-org/iptv#5632]
**Channel Name:** videoland sport / 纬来体育
**Channel ID:** VideolandSports.tw
**Country:** China Taiwan
**Language:** Chinese
**Website:** [纬来体育](http://sport.videoland.com.tw/#)
**Stream URL (optional):** not yet
**Notes (optional):** xxx

**Comment by JINPENG1144** [comment]
有吗

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/dfa0e06b6e22f99aa62e95c554d13742c4b13df1/streams/tw.m3u#L118-L119
