### ISSUE TITLE
MBC 2 HD broken, updated link here. Thanks

### ISSUE THREAD

**Issue by DrHurt** [iptv-org/iptv#5636]
**_Channel Name:_** MBC 2 HD
**_Country:_** ae
**_Broken Link (from playlist):_** xxx
**_Possible Replacement (optional):_** https://livestreams.tooli-tv.com/live/149010_.m3u8?session=
**_Notes (optional):_** online and not geoblocked. Should replace all three currently redundant entries in the list. Also, logo could use an update as current one looks awkward/too small on TV, suggested alternative: https://upload.wikimedia.org/wikipedia/commons/5/50/MBC2_Logo.png

Thanks

**Comment by DrHurt** [comment]
Same goes MBC Action HD: (updated, non-geoblocked link): https://livestreams.tooli-tv.com/live/149013_.m3u8?session=

And MBC Max HD: 
https://livestreams.tooli-tv.com/live/149015_.m3u8?session=

**Comment by LaneSh4d0w** [comment]
![image](https://user-images.githubusercontent.com/30985701/145386187-84efe2af-1412-4e09-90d4-fc1b235d0c7a.png)

Not from my point of view.

**Comment by DrHurt** [comment]
Oh shoot, it was working yesterday. Now has become geolocked as well. Darn it. 

Will see if I can find alternatives.
