### ISSUE TITLE
Animax japan 

### ISSUE THREAD

**Issue by YOUDEADMOM** [iptv-org/iptv#5642]
Channel Name: Animax japan 
Country: Japan
Broken Link (from playlist): xxx
Possible Replacement (optional): xxx
Notes (optional): All animax stream unfortunately do not go

**Comment by AstaFatherSatan666** [comment]
You're lying! Unfortunately they don't host or own the streams, you can't make another pull request demanding what you want. It's the third time. I understand you want it but you must wait. These developers are working really hard on getting content for everyone without getting paid. I give a huge amount of respect to them for this.

**Comment by YOUDEADMOM** [comment]
> Unfortunately they don't host or own the streams, you can't make another pull request demanding what you want. It's the third time. I understand you want it but you must wait. These developers are working really hard on getting content for everyone without getting paid. I give a huge amount of respect to them for this.

aha and
