### ISSUE TITLE
The CW East WPIX-DT1

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#5663]
### Channel Name

The CW East WPIX-DT1

### Country

USA-New York

### Language

English

### Website

[Inspected from Same Server]

### Stream URL

http://encodercdn1.frontline.ca/kamino/output/pix11_720p/playlist.m3u8

### Notes

Finally Found from Canadian Server!

**Comment by LaneSh4d0w** [comment]
480 in http://encodercdn1.frontline.ca/kamino/output/pix11/playlist.m3u8

**Comment by spotanjo3** [comment]
is THE CW working now ?

**Comment by ob1100** [comment]
> is THE CW working now ?

Looks like all the encodercdn1.frontline.ca channels are down now

**Comment by spotanjo3** [comment]
Hope you find THE CW EAST WPIX-DT1 soon.

**Comment by thodiamedia** [comment]
watch it on [Watch News Live ](https://watchnewslive.info/)

**Comment by spotanjo3** [comment]
> watch it on [Watch News Live ](https://watchnewslive.info/)

There is no CW in the list.
