### ISSUE TITLE
Space Shower TV

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#5664]
### Channel Name

Space Shower TV

### Channel ID

SpaceShowerTV.jp

### Country

Japan

### Language

Japanese

### Website

https://www.spaceshowertv.com/

**Comment by freearhey** [comment]
https://code.vthanhtivi.pw/getlink/jptv/P86mGOvGtsJuOiIBozlSTA==/playlist.m3u8
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/7253922/233870537-af2a437e-3d5d-4580-b181-c1d21159b054.png">
