### ISSUE TITLE
Space Shower TV Plus

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#5665]
### Channel Name

Space Shower TV Plus

### Channel ID

SpaceShowerTVPlus.jp

### Country

Japan

### Language

Japanese

### Website

https://www.spaceshowertvplus.com/

**Comment by freearhey** [comment]
https://code.vthanhtivi.pw/getlink/jptv/QhdGbVgbJKI-AuLKLoBlhw==/playlist.m3u8
<img width="791" alt="image" src="https://user-images.githubusercontent.com/7253922/233870491-f2832229-dff3-4de9-a61a-f42aaf27e3d4.png">
