### ISSUE TITLE
Music On! TV (M-ON!)

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#5666]
### Channel Name

Music On! TV (M-ON!)

### Channel ID

MusicOnTV.jp

### Country

Japan

### Language

Japanese

### Website

https://www.m-on.jp/

**Comment by freearhey** [comment]
https://code.vthanhtivi.pw/getlink/jptv/_RVyS6Uym1zs93N3KvDcsw==/playlist.m3u8
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/7253922/233870726-8b8e1288-dcbb-4507-9978-96a9866f11e7.png">

http://rip.hidari.moe/get/jptv/get.php?id=6eHaPTJd0NoBEwN6E9jArw==
<img width="784" alt="image" src="https://user-images.githubusercontent.com/7253922/233870767-1f15209d-e6e6-45c2-8abf-19e305e7736f.png">

https://stream01.willfonk.com/live_playlist.m3u8?cid=CS325&r=FHD&ccode=JP&m=d0:20:20:04:35:cc&t=0d6938cb3dcf4b79848bc1753a59daf1 
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/7253922/233870807-8abc1c11-8b6e-4bf4-bfcc-719a02558f84.png">
