### ISSUE TITLE
CBSN Sacramento

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#5670]
### Channel Name

CBSN Sacramento

### Country

USA-California

### Language

English

### Website

"https://www.cbsnews.com/live/cbsn-local-sac/" But Dumped From CBS News App

### Stream URL

https://dai.google.com/linear/hls/event/e7mp4YVGS7O_e7rqRNjKow/master.m3u8?iu=/8264/vaw-can/mobile_app/cbsnews_android_phone_app

### Notes

Souce XML Link:"http://feeds-cbsn.cbsnews.com/2.1/rundown/?edition=CBSN-SAC&partner=androidphone&type=live"

**Comment by LaneSh4d0w** [comment]
https://dai.google.com/linear/hls/pa/event/e7mp4YVGS7O_e7rqRNjKow/stream/0b0fedd1-b586-4a89-a2b6-646cb2a5f332:GRQ/master.m3u8 / https://cbsnews.akamaized.net/hls/live/2020607/cbsnsac_2/master.m3u8
