### ISSUE TITLE
WEAH-CA

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#5671]
### Channel Name

The Weather Network-CA

### Country

Canada

### Language

English

### Website

Official Site:"https://www.theweathernetwork.com/us"

### Stream URL

http://encodercdn1.frontline.ca/kamino/output/The_Weather_Network_720p/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
480 in http://encodercdn1.frontline.ca/kamino/output/The_Weather_Network/playlist.m3u8
720 in http://encodercdn1.frontline.ca/kamino/output/The_Weather_Network_720p/playlist.m3u8

**Comment by what-a** [comment]
Great logo...

![](https://s1.twnmm.com/images/en_ca/mobile/logos/twn-mobile-logo.png)

https://s1.twnmm.com/images/en_ca/mobile/logos/twn-mobile-logo.png
