### ISSUE TITLE
CBSN Baltimore

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#5681]
### Channel Name

CBSN Baltimore

### Country

USA-MaryLand Baltimore

### Language

English

### Website

https://www.cbsnews.com/live/cbsn-local-bal/, But I Found via XML

### Stream URL

https://dai.google.com/linear/hls/event/TMUt418sQMeu1QtneYJ9ag/master.m3u8?iu=/4128/CBS.BALTIMORE.OTT/androidphone

### Notes

CBSN Baltimore is Not Listed, So I Requested, Source XML Link:http://feeds-cbsn.cbsnews.com/2.1/rundown/?edition=CBSN-BAL&partner=androidphone&type=live

**Comment by LaneSh4d0w** [comment]
https://dai.google.com/linear/hls/pa/event/TMUt418sQMeu1QtneYJ9ag/stream/03fc4ece-6cac-47a7-9698-8f336e2456bc:GRQ/master.m3u8 / https://cbsnews.akamaized.net/hls/live/2020607/cbsnlineup_8/master.m3u8 (alternative)

**Comment by LaneSh4d0w** [comment]
@Dum4G @freearhey I'm starting to begin thinking about splitting the CBS streams to a us_cbs.m3u file. There's beginning to have lots and lots of them on the us playlist. What do you think ?

**Comment by Dum4G** [comment]
I'm always into splitting files when all the channels come from a single source

**Comment by freearhey** [comment]
I don't see the need for that.
