### ISSUE TITLE
Add: Canal de la Ciudad

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#5696]
### Channel Name

Canal de la Ciudad

### Country

Argentina

### Language

Spanish

### Website

https://www.buenosaires.gob.ar/canaldelaciudad

### Notes

Embed frame: https://vmf.edge-apps.net/embed/live.php?streamname=gcba_video4-100042&autoplay=true2&autoplay=true

**Comment by Sphinxroot** [comment]
<html><body>


masterManifest | https://g5.vxral-slo.transport.edge-access.net/a08/ngrp:gcba_video4-100042_all/Playlist.m3u8?sense=true
-- | --
mediaManifest | https://g5.vxral-slo.transport.edge-access.net/a08/ngrp:gcba_video4-100042_all/gcba_video4-100042_720p.m3u8


</body>
</html>

**Comment by LaneSh4d0w** [comment]
https://g5.proy-hor.transport.edge-access.net/a08/ngrp:gcba_video4-100042_all/Playlist.m3u8?sense=true

Same technique as América and A24, add iPhone useragent and referer to https://vmf.edge-apps.net/
