### ISSUE TITLE
Add: HCH

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#5720]
### Channel Name

HCH

### Country

Honduras

### Language

Spanish

### Website

https://hch.tv/

### Stream URL

https://stream-01.nyc.dailymotion.com/sec(JtO5HO8PrOFTKKYNhfGSpiOeWNKe412EyHIskeSAO24)/dm/3/x81za5c/d/live-3.m3u8

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x81za5c
