### ISSUE TITLE
Replace: TSI (Honduras)

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#5722]
### I have verified that

- [X] I use the GitHub playlist link and not a downloaded/cached version of the file
- [X] My TV player has updated this playlist after 0:00 GMT and is set to update it daily
- [X] I am aware that the channel source may have temporal outages. It is broken/absent from the playlist for couple of hours or days

### Channel Name

TSI

### What happened to the stream?

It is stuck at a single frame/the same segment

### Playlist

https://iptv-org.github.io/iptv/index.country.m3u

### Broken Link

https://bcovlive-a.akamaihd.net/5a4db02a43d645729f273b91c5ba9238/us-west-2/6056665196001/playlist.m3u8

### Possible Replacement

https://stream-04.nyc.dailymotion.com/sec(ekpi6JmRB5KslkTtNqtBmhwSD4XYoy2VvzcIvPhJ_To)/dm/3/x7xs2wx/s/live-3.m3u8

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/k3q8hF4Y9tzpTgwu26R
