### ISSUE TITLE
Replace: El Sembrador Nueva Evangelización (ESNE)

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#5723]
### I have verified that

- [X] I use the GitHub playlist link and not a downloaded/cached version of the file
- [X] My TV player has updated this playlist after 0:00 GMT and is set to update it daily
- [X] I am aware that the channel source may have temporal outages. It is broken/absent from the playlist for couple of hours or days

### Channel Name

El Sembrador Nueva Evangelización (ESNE)

### What happened to the stream?

It is stuck at a single frame/the same segment

### Playlist

https://iptv-org.github.io/iptv/index.country.m3u

### Broken Link

https://zypelive-lh.akamaihd.net/i/default_1@710948/master.m3u8

### Possible Replacement

https://zypelive-lh.akamaihd.net/i/default_1@44045/index_720_av-b.m3u8?F38b1dF4=60e7959fd188db0001afcac6&6pLKMQ3y=Sqi3Ng90&video_id=5f978263e036f600019f66c2&sd=10&dw=10800&rebase=on

**Comment by LaneSh4d0w** [comment]
It now works.
