### ISSUE TITLE
Replace: EWTN el Canal Católico (720p)

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#5724]
### I have verified that

- [X] I use the GitHub playlist link and not a downloaded/cached version of the file
- [X] My TV player has updated this playlist after 0:00 GMT and is set to update it daily
- [X] I am aware that the channel source may have temporal outages. It is broken/absent from the playlist for couple of hours or days

### Channel Name

EWTN el Canal Católico 

### What happened to the stream?

It is now offline (disappeared from the playlist)

### Playlist

https://iptv-org.github.io/iptv/index.country.m3u

### Broken Link

https://cdn3.wowza.com/1/SmVrQmZCUXZhVDgz/b3J3MFJv/hls/live/playlist.m3u8

### Possible Replacement

https://cdn3.wowza.com/1/SmVrQmZCUXZhVDgz/b3J3MFJv/hls/n8345n84/2728/chunklist.m3u8

**Comment by LaneSh4d0w** [comment]
It'll be re-added later if the bot sees that it's online. It indeed works on my side.

**Comment by Dum4G** [comment]
![image](https://user-images.githubusercontent.com/5430116/146390242-12b49f79-94b6-42ba-be64-65ad3b9e8675.png)
Confirmed working
