### ISSUE TITLE
Add: CCI Channel

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#5727]
### Channel Name

CCI Channel

### Country

Honduras

### Language

Spanish

### Website

https://www.ccichannel.tv/

### Stream URL

https://stream-02.nyc.dailymotion.com/sec(9adq8njh6Ix1Bfv2jmbm4xrgBVhN4b3ELmaKL9KQCm0)/dm/3/x836wjl/s/live-1.m3u8

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://dai.ly/x836wjl
