### ISSUE TITLE
Add: MeTV East (WJLP)

### ISSUE THREAD

**Issue by Gitbone94** [iptv-org/iptv#5730]
### Channel Name

WJLP (MeTV) New Jersey/New York  Ch 3 Digital 33.1

### Country

USA

### Language

English

### Website

https://www.newjerseynewsnetwork.com/

**Comment by Dum4G** [comment]
https://wjlp.akamaized.net/hls/live/2030290/WJLP_OUT/1/streamPlaylist.m3u8
Logo: https://i.imgur.com/tIazTgN.png

**Comment by MapGuy11** [comment]
> https://wjlp.akamaized.net/hls/live/2030290/WJLP_OUT/1/streamPlaylist.m3u8 Logo: https://i.imgur.com/tIazTgN.png

That is just WJLP-DT9 (News Net
![vlcsnap-2021-12-16-16h26m43s598](https://user-images.githubusercontent.com/43685307/146451278-efca4d23-2423-475b-b10f-73f3b39aa4fa.png)
)

**Comment by fotvnetwork** [comment]
An affiliate of NewsNet

**Comment by LaneSh4d0w** [comment]
https://wjlp.akamaized.net/hls/live/2030290/WJLP_OUT/master.m3u8 is the adaptive playlist.

That's the only official WJLP-maintained stream.

**Comment by MapGuy11** [comment]
> https://wjlp.akamaized.net/hls/live/2030290/WJLP_OUT/master.m3u8 is the adaptive playlist.
> 
> That's the only official WJLP-maintained (New Jersey News Network) stream.

Yeah that is WJLP-DT9 I think it's on the localbtv stuff too.

**Comment by LaneSh4d0w** [comment]
Yup, as for the MeTV channels, I think I've only stumbled upon Monterey so far.

**Comment by Gitbone94** [comment]
I would take any Me TV that can be found for the eastern time zone. WLWT Cincinnati, WDIV Detroit, KYAZ Houston (central time but on same sched as eastern) seem to be the three other popular choices. I am out of OTA range for Me TV or I would just bring it in over the air and not bother the iptv-org team. Thanks for trying.

**Comment by what-a** [comment]
Just added:   MeTV Tallahassee FL (WCTV2) (480p)

**Comment by what-a** [comment]
MeTV for eastern time zone on IPTV-org:
MeTV Tallahassee FL (WCTV2) (480p)
![image](https://user-images.githubusercontent.com/88639906/150265560-c9cb24a0-d57e-4f11-9b52-000b6104e419.png)

**Comment by Gitbone94** [comment]
Many thanks!

**Comment by spotanjo3** [comment]
This link isn't working.

**Comment by BellezaEmporium** [comment]
It's been 2 1/2 years, of course that won't work after that long xd
