### ISSUE TITLE
Add: 

### ISSUE THREAD

**Issue by t9nq** [iptv-org/iptv#5753]
### Channel Name

ssc1

### Country

Saudi Arabia

### Language

Arabic

### Website

https://www.akamaized.net

### Stream URL

https://ssc-5-ak.akamaized.net:443/out/v1/6ae0a2ebab224c72ab9c298afeec8d91/index_3.m3u8

### Notes

Ssc 1

**Comment by Dum4G** [comment]
Already present in
https://github.com/iptv-org/iptv/blob/24a753c67f189d5734fca9746d8f6967d135f921/channels/sa.m3u#L98-L99
