### ISSUE TITLE
Add: Viajar TV

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#5762]
### Channel Name

Viajar TV

### Channel ID

ViajarTV.ar

### Country

Argentina

### Language

Spanish

### Website

https://viajartv.tv/canal/

### Notes

HISPAM Channel. Frame from https://iframe.dacast.com/live/a2941b94379068262332f0407a4d6897/ba5ace20-9494-859b-bcf5-5dd211b1012c

**Comment by LaneSh4d0w** [comment]
grab the link from here as JSON : https://playback.dacast.com/content/access?contentId=a2941b94379068262332f0407a4d6897-live-ba5ace20-9494-859b-bcf5-5dd211b1012c&provider=universe

**Comment by freearhey** [comment]
Closed in favor #9025
