### ISSUE TITLE
Add: TeleDanlí Canal 9

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#5777]
### Channel Name

TeleDanlí Canal 9

### Country

Honduras

### Language

Spanish

### Website

http://teledanli.net/

### Stream URL

https://cloud2.streaminglivehd.com:1936/8224/8224/chunklist_w1763628339.m3u8

**Comment by LaneSh4d0w** [comment]
@sguinetti didn't we scan that host recently ?

Adaptive : https://cloud2.streaminglivehd.com:1936/8224/8224/playlist.m3u8

**Comment by sguinetti** [comment]
I guess not as I expected, even though the website ha the "streaming" name. I once asked about "cloud2" but we don't find online streams.

**Comment by LaneSh4d0w** [comment]
I guess i'm gonna scan this website for more.
