### ISSUE TITLE
Add: VTV

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#5778]
### Channel Name

VTV

### Channel ID

VTV.hn

### Country

Honduras

### Language

Spanish

### Website

https://www.vtv.com.hn/

### Stream URL

https://hn-vtv-vtv-live.ned.media/vtv/smil:vtv.smil/chunklist_b850000.m3u8?iut=eyJwYXJhbXMiOnsiZXhwIjoxNjM5ODUxNjc4LCJzZXNzaW9uIjoiMTkwLjAuMTQwLjI1NCIsIndoaXRlbGlzdCI6WyIxOTAuMC4xNDAuMjU0Il19LCJzaWduYXR1cmUiOiIxNzM2Yzg3MWRhNzk0ZjRhZDhjZmY1Yjc4N2M3ZDY1NWE3YTZjZGRmIn0%3D

**Comment by LaneSh4d0w** [comment]
Haven't found out yet how to deal with ned.media links.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/cac2f96962f43fcec08d835b0878ed36307d4bbe/streams/hn.m3u#L62-L63
