### ISSUE TITLE
Add: Hondured 13

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#5779]
### Channel Name

Hondured 13

### Country

Honduras

### Language

Spanish

### Website

https://hondured13.tv/

### Stream URL

https://stream-01.nyc.dailymotion.com/sec(9adq8njh6Ix1Bfv2jmbm46f6XfaKagRfMiKS_8lYyK0)/dm/3/x83axzj/s/live-1.m3u8

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://dai.ly/x83axzj
