### ISSUE TITLE
Add: Suyapa TV

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#5780]
### Channel Name

Suyapa TV

### Country

Honduras

### Language

Spanish

### Website

https://suyapamedios.hn/suyapa-tv/

### Stream URL

https://stream-01.nyc.dailymotion.com/sec(9adq8njh6Ix1Bfv2jmbm43eqUW_TR0fpDXE7-ynjTHo)/dm/3/x833e2b/s/live-1.m3u8

### Notes

Suyapa TV is a Catholic television station owned and operated by Suyapa Medios, a Honduran Catholic media organization based in Tegucigalpa, Francisco Morazán Department.

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://dai.ly/x833e2b
