### ISSUE TITLE
Add: Canal Luz

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#5783]
### Channel Name

Canal Luz

### Country

Argentina

### Language

Spanish

### Website

https://www.canalluz.org/index.html

### Stream URL

https://g2.vxral-slo.transport.edge-access.net/a11/ngrp:canal_luz01-100009_all/canal_luz01-100009_1080p.m3u8

### Notes

Christian/Religious TV station.

**Comment by Dum4G** [comment]
![image](https://user-images.githubusercontent.com/5430116/146591982-793f4f27-eb2f-4865-9c6f-d33b28477071.png)

We already have plenty of channels from your requests. Please use search to verify if the channel is present in repository. In case something went offline use the Broken Stream form

**Comment by LaneSh4d0w** [comment]
Valid, need to add user-agent iPhone to make it work.
