### ISSUE TITLE
Add: Alsacias TV

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#5784]
### Channel Name

Alsacias TV

### Country

Honduras

### Language

Spanish

### Website

http://www.canalesdehondurasenvivo.com/2017/09/canal-alsacias-tv-en-vivo.html

### Stream URL

https://emisoras.hn:8081/atv/tracks-v1a1/mono.m3u8

**Comment by LaneSh4d0w** [comment]
Adaptive : https://emisoras.hn:8081/atv/playlist.m3u8

**Comment by Dum4G** [comment]
Already present in playlist from that source
