### ISSUE TITLE
Add: Guatevisión

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#5786]
### Channel Name

Guatevisión

### Country

Guatemala

### Language

Spanish

### Website

https://www.guatevision.com/

### Stream URL

https://streannlive-lh.akamaihd.net/i/guatevision_1@870649/index_1_av-p.m3u8?sd=10&set-segment-duration=smoothest&rebase=on&hdntl=exp=1639853050~acl=*~data=hdntl~hmac=59402900c45cd6281887012ffeae2afa48da13838c51a76c51298cb7fabe408b

**Comment by LaneSh4d0w** [comment]
https://ott.streann.com/loadbalancer/services/public/channels/5d6821172cdced7698d5a329/playlist.m3u8
