### ISSUE TITLE
Replace: Teletica 7

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#5787]
### I have verified that

- [X] I use the GitHub playlist link and not a downloaded/cached version of the file
- [X] My TV player has updated this playlist after 0:00 GMT and is set to update it daily
- [X] I am aware that the channel source may have temporal outages. It is broken/absent from the playlist for couple of hours or days

### Channel Name

Teletica 7

### What happened to the stream?

It is now offline (disappeared from the playlist)

### Playlist

https://iptv-org.github.io/iptv/countries/cr.m3u

### Broken Link

http://201.220.141.118:8000/play/a02r/index.m3u8

### Possible Replacement

https://stream-04.nyc.dailymotion.com/sec(jlR0lJnpjfic8bXdlVDO5wNaIYzxio-ZTzdGE2CtROo)/dm/3/x29e3wg/s/live-1.m3u8

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x29e3wg
