### ISSUE TITLE
[Will Add]ABC West KXLY-TV1

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#5799]
### Channel Name

ABC West KXLY-TV1 PST.

### Country

USA-Spokane,WA (Canadian Server) 

### Language

English

### Website

Official Site:"https://www.kxly.com/"

### Stream URL

http://encodercdn1.frontline.ca/kamino/output/ABC_Spokane_720p/playlist.m3u8

### Notes

Will be add Next update of us.m3u(after # 5798). and Sorry, Eastern Feed of abc is Still Missing.

**Comment by what-a** [comment]
@Central302 You're on a roll!  Don't stop! 
I recommend naming the stream; ABC Spokane WA (KXLY-TV1) (720p)
