### ISSUE TITLE
Replace: Rewind TV US (WPIXDT4) NY

### ISSUE THREAD

**Issue by rick999999** [iptv-org/iptv#5811]
### I have verified that

- [ ] I use the GitHub playlist link and not a downloaded/cached version of the file
- [ ] My TV player has updated this playlist after 0:00 GMT and is set to update it daily
- [ ] I am aware that the channel source may have temporal outages. It is broken/absent from the playlist for couple of hours or days

### Channel Name

Rewind TV US (WPIXDT4) NY (432p)

### What happened to the stream?

It is now offline (disappeared from the playlist)

### Playlist

https://github.com/iptv-org/iptv/blob/master/channels/us.m3u

### Broken Link

mybtv.net/event/565/640x480.m3u8

### Notes

wnbc from 'mybtv.net' is also down now

**Comment by Central302** [comment]
it Looks Like Link Patched "Invaild Request"

**Comment by LaneSh4d0w** [comment]
https://v-ny.mybtv.net/event/565?start_time=2021-12-20T14%3A15%3A00%2B00%3A00&end_time=2021-12-20T17%3A00%3A00%2B00%3A00&env=prd

"OOTA" = Out of the Area

**Comment by Sophgirl41** [comment]
Will the Rewind TV US (WPIXDT4) NY  channel be able to be fixed

**Comment by Sophgirl41** [comment]
?

**Comment by MapGuy11** [comment]
@Sophgirl41 STOP TRYING TO MAKE NEW ISSUES YOU DO IT AGAIN THIS ONE WILL BE CLOSED AND YOU WILL BE BANNED. WE ARE TRYING OUR BEST. THIS IS A FREE SERVICE!!!!!!

**Comment by Sophgirl41** [comment]
I am just trying  to get the channel fixed so I can watch it there is no reason to be rude and tell me your going to banned me

**Comment by MapGuy11** [comment]
> I am just trying to get the channel fixed so I can watch it there is no reason to be rude and tell me your going to banned me

@Sophgirl41 Normally I would say no, but the amount of times you make issues that are the same one as this is crazy we have to manually go in and delete it costing us time. When you could just wait and when it's resolved this Issue with be closed and the channel will be added.

**Comment by MapGuy11** [comment]
@Sophgirl41 #6176 
You are in luck I found a way.
