### ISSUE TITLE
PBS Twin Cities (KTCA-TV)

### ISSUE THREAD

**Issue by jhedfors** [iptv-org/iptv#5826]
### Channel Name

KTCA-TV - Twin Cities PBS

### Channel ID

KTCADT1.us

### Country

USA

### Language

English

### Website

https://www.tpt.org/watch-live/

**Comment by LaneSh4d0w** [comment]
That would be https://ktcadt.lls.pbs.org/out/v1/d1c00d8051e543e2b42afafaa1ffd035/dash-drm.mpd

however, it's using Widevine and I'm not sure that a m3u8 playlist exists.

**Comment by jhedfors** [comment]
It is the same site as the recently resolved #5842 of that helps.

**Comment by jhedfors** [comment]
Not sure why this is closed. Was there a new working m3u8 that I missed?

**Comment by MapGuy11** [comment]
I quote "It is the same site as the recently resolved https://github.com/iptv-org/iptv/issues/5842 of that helps."

**Comment by MapGuy11** [comment]
Since that one was closed I closed this one also as your request was fulfilled.

**Comment by jhedfors** [comment]
It wasn't fullfilled. That was a link to different sub-channel on the same network.

**Comment by MapGuy11** [comment]
Oh well, you said the same site so I assumed it was ok. The main PBS feeds are all DRM'd so it's highly doubtful we will get a link but I will reopen this for you.

**Comment by jhedfors** [comment]
Thank you. 👍

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/cac2f96962f43fcec08d835b0878ed36307d4bbe/streams/us_pbs.m3u#L80-L81
