### ISSUE TITLE
Replace: DidikTV

### ISSUE THREAD

**Issue by Leejames2305** [iptv-org/iptv#5834]
### I have verified that

- [X] I use the GitHub playlist link and not a downloaded/cached version of the file
- [X] My TV player has updated this playlist after 0:00 GMT and is set to update it daily
- [X] I am aware that the channel source may have temporal outages. It is broken/absent from the playlist for couple of hours or days

### Channel Name

DidikTV

### What happened to the stream?

It is now offline (disappeared from the playlist)

### Playlist

https://iptv-org.github.io/iptv/countries/my.m3u

### Broken Link

http://194.233.86.5:5080/WebRTCApp/streams/didiktv.m3u8

### Possible Replacement

https://raw.githubusercontent.com/samleong123/tonton_dailymotion_php/main/m3u8/DidikTVKPM.m3u8

### Notes

DidikTV is actually the same as NTV7 / TV7
The replacement link **might be** Geo-blocked, need further confirmation.

**Comment by LaneSh4d0w** [comment]
Works for me, Serbian IP.

![snapshot](https://user-images.githubusercontent.com/30985701/147121130-79a4f327-e6f1-4da9-ae0b-9a74709b6497.jpg)
