### ISSUE TITLE
Replace: DramaSangat

### ISSUE THREAD

**Issue by Leejames2305** [iptv-org/iptv#5839]
### I have verified that

- [X] I use the GitHub playlist link and not a downloaded/cached version of the file
- [X] My TV player has updated this playlist after 0:00 GMT and is set to update it daily
- [X] I am aware that the channel source may have temporal outages. It is broken/absent from the playlist for couple of hours or days

### Channel Name

DramaSangat

### What happened to the stream?

It is now offline (disappeared from the playlist)

### Playlist

https://iptv-org.github.io/iptv/countries/my.m3u

### Broken Link

http://194.233.86.5:5080/WebRTCApp/streams/dsangat.m3u8

### Possible Replacement

https://raw.githubusercontent.com/samleong123/tonton_dailymotion_php/main/m3u8/Drama_Sangat.m3u8

### Notes

The replacement link  **might be** Geo-blocked, need further confirmation.

**Comment by LaneSh4d0w** [comment]
Not geo-blocked on my side, tested using a Serbian IP.

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/player/video/x6zvnex

**Comment by samleong123** [comment]
> Not geo-blocked on my side, tested using a Serbian IP.

just curious u never get 403 about the HLS inside?
![image](https://user-images.githubusercontent.com/58818070/147923741-e063f8e3-258c-4033-8915-1f2020e86399.png)
i get 403 if i access the HLS playlist using non Malaysia IP

**Comment by LaneSh4d0w** [comment]
> > Not geo-blocked on my side, tested using a Serbian IP.
> 
> just curious u never get 403 about the HLS inside?
> ![image](https://user-images.githubusercontent.com/58818070/147923741-e063f8e3-258c-4033-8915-1f2020e86399.png)
> i get 403 if i access the HLS playlist using non Malaysia IP 

It got to the stream just fine on my side.

**Comment by samleong123** [comment]
> > > Not geo-blocked on my side, tested using a Serbian IP.
> > 
> > 
> > just curious u never get 403 about the HLS inside?
> > ![image](https://user-images.githubusercontent.com/58818070/147923741-e063f8e3-258c-4033-8915-1f2020e86399.png)
> > i get 403 if i access the HLS playlist using non Malaysia IP
> 
> It got to the stream just fine on my side.

That's weird , i can't even access this HLS playlist via Singapore IP (both Oracle / Centerhop) and CMLink HK IP 
seems like dailymotion IP Database is having a problem maybe

**Comment by LaneSh4d0w** [comment]
> > > > Not geo-blocked on my side, tested using a Serbian IP.
> > > 
> > > 
> > > just curious u never get 403 about the HLS inside?
> > > ![image](https://user-images.githubusercontent.com/58818070/147923741-e063f8e3-258c-4033-8915-1f2020e86399.png)
> > > i get 403 if i access the HLS playlist using non Malaysia IP
> > 
> > It got to the stream just fine on my side.
> 
> That's weird , i can't even access this HLS playlist via Singapore IP (both Oracle / Centerhop) and CMLink HK IP 
> seems like dailymotion IP Database is having a problem maybe

Maybe stream is offline.

**Comment by samleong123** [comment]
> > > > > Not geo-blocked on my side, tested using a Serbian IP.
> > > > 
> > > > 
> > > > just curious u never get 403 about the HLS inside?
> > > > ![image](https://user-images.githubusercontent.com/58818070/147923741-e063f8e3-258c-4033-8915-1f2020e86399.png)
> > > > i get 403 if i access the HLS playlist using non Malaysia IP
> > > 
> > > 
> > > It got to the stream just fine on my side.
> > 
> > 
> > That's weird , i can't even access this HLS playlist via Singapore IP (both Oracle / Centerhop) and CMLink HK IP
> > seems like dailymotion IP Database is having a problem maybe
> 
> Maybe stream is offline.

Nope , its works fine with Malaysia IP , but for other countries IP (including SG / HK) i get 403
![image](https://user-images.githubusercontent.com/58818070/147924187-10307bf6-c105-4006-ad0b-5134cbca32a9.png)

**Comment by Dum4G** [comment]
Works from Russia

**Comment by LaneSh4d0w** [comment]
![y2](https://user-images.githubusercontent.com/30985701/147961444-d171f26c-e63c-4087-aed6-bbb7120102a1.jpg)

Works from Romania
