### ISSUE TITLE
Replace: BernamaTV

### ISSUE THREAD

**Issue by Leejames2305** [iptv-org/iptv#5841]
### I have verified that

- [X] I use the GitHub playlist link and not a downloaded/cached version of the file
- [X] My TV player has updated this playlist after 0:00 GMT and is set to update it daily
- [X] I am aware that the channel source may have temporal outages. It is broken/absent from the playlist for couple of hours or days

### Channel Name

BernamaTV

### What happened to the stream?

It is now offline (disappeared from the playlist)

### Playlist

https://iptv-org.github.io/iptv/countries/my.m3u

### Broken Link

http://50.7.161.82:8278/streams/d/Bernama/playlist.m3u8

### Possible Replacement

https://www.youtube.com/watch?v=5__HqL626Og

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCcZg5r9hBqK_VPUT2I7eYVw/live
