### ISSUE TITLE
Add: Canal 5 (MX)

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#5846]
### Channel Name

Canal 5

### Country

México

### Language

Spanish

### Website

https://www.televisa.com/canal5/

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/5mxt239

**Comment by GiovanniSebastian** [comment]
Thanks

**Comment by trancer1994** [comment]
"Could not get the URL, Streamlink could not read http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/5mxt230" is the error I'm getting when I open the link

**Comment by LaneSh4d0w** [comment]
new name for the stream.

**Comment by Dum4G** [comment]
http://45.174.77.243:8000/play/a0fl/index.m3u8
