### ISSUE TITLE
Add: Azteca 7 (MX)

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#5847]
### Channel Name

Azteca 7

### Country

México

### Language

Spanish

### Website

https://www.tvazteca.com/azteca7/

**Comment by LaneSh4d0w** [comment]
https://mdstrm.com/live-stream-playlist/609ad46a7a441137107d7a81.m3u8?uid=JQhsg89rRpocjsCJp893iHgvKyhbKiWE&sid=qU8yE0j427QDsDCuFSy1CB1lWdBtVu0o&pid=QSfKMyyVIUIILpiqay6GELErOmRut2hs&an=screen&at=web-app&av=v5.2.205&ref=https%3A%2F%2Fwww.tvazteca.com%2F&res=938x528&without_cookies=false&dnt=true

idk if https://mdstrm.com/live-stream-playlist/609ad46a7a441137107d7a81.m3u8 alone works.

Done using an Mexican IP.

**Comment by GiovanniSebastian** [comment]
I'm Chilean :'(

**Comment by Dum4G** [comment]
http://45.174.77.243:8000/play/a0fm/index.m3u8

Is that the channel you want?

**Comment by Dum4G** [comment]
Can't be added due to DMCA we have recieved
https://github.com/github/dmca/blob/master/2020/09/2020-09-16-dfl.md
