### ISSUE TITLE
Add: Cartoon Network Japan

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#5848]
### Channel Name

Cartoon Network Japan (カートゥーン ネットワーク)

### Country

Japan

### Language

Japanese

### Website

https://www.cartoonnetwork.jp/

### Stream URL

http://50.7.74.29:8080/hlsok/j00024/index.m3u8

**Comment by Central302** [comment]
Actual CN Japan, But Looping in Same Position.

**Comment by LaneSh4d0w** [comment]
Weirdly works. Gets image at a certain instant, then audio only with video freeze, and then cuts.

**Comment by GiovanniSebastian** [comment]
Works in SSIPTV (LG) and IPTV app (Android).

**Comment by what-a** [comment]
> Weirdly works. Gets image at a certain instant, then audio only with video freeze, and then cuts.

Same for me.

**Comment by LaneSh4d0w** [comment]
It seems the buggy channels came back. Kids Station from the same host had that issue before, now works fine.
