### ISSUE TITLE
Georgia Public Broadcasting - PBS (WGTV)

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#5854]
### Channel Name

GPB

### Country

USA-Atlanta,GA

### Language

English

### Website

https://www.gpb.org/television/live

### Stream URL

https://api.new.livestream.com/accounts/6264/events/8860817/broadcasts/228237298.m3u8

### Notes

They Only Using  livestream.com cdn, but PBS Member Station.

**Comment by what-a** [comment]
Working for me (in USA).  Please use this logo:
https://d1qbemlbhjecig.cloudfront.net/prod/filer_public/pbs-digital-studios-bento-live-pbs/icons/1fcc0dd46e_PBS_favicon.png

**Comment by MapGuy11** [comment]
Works But we should be using this logo: https://image.pbs.org/stations/wgtv-white-single-brand-logo-p7SbTvh.png
Not a generic PBS one. @what-a

**Comment by what-a** [comment]
@MapGuy11 No biggie either way. It just a matter of opinion. I prefer logos with the broadest audience recognition (national vs. local), as well as looking good when placed in front of a black or white background.

**Comment by MapGuy11** [comment]
> @MapGuy11 No biggie either way. It just a matter of opinion. I prefer logos with the broadest audience recognition (national vs. local), as well as looking good when placed in front of a black or white background.

Yeah I get you it's just easier when you have 10 pbs in a list when the logos are different. We can change the color to blue also.

**Comment by Central302** [comment]
It Looks Like Official Changes Stream ID. I Close the Issuse
Dump Data: https://player-api.new.livestream.com/accounts/6264/events/8860817/stream_info
