### ISSUE TITLE
The Ohio Channel (WOSU-DT3)

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#5855]
### Channel Name

The Ohio Channel, WOSU-DT3

### Country

USA-Ohio 

### Language

English

### Website

https://wosu.org/television/wosu-ohio-livestream/

### Stream URL

https://5ebe6889de541.streamlock.net/live/stream_10/playlist.m3u8

### Notes

Public Channel

**Comment by LaneSh4d0w** [comment]
Works for me.

**Comment by what-a** [comment]
Works for me as well.  Here's a logo:
https://a.thumbs.redditmedia.com/IoXfiVbzWSKlacdkf05KQbNa_4xeavHDe0QWbbgCMe8.jpg
