### ISSUE TITLE
Fix: Some channels have disappeared... again

### ISSUE THREAD

**Issue by eltoncomp** [iptv-org/iptv#5863]
### I have verified that

- [X] I use the GitHub playlist link and not a downloaded/cached version of the file
- [X] My TV player has updated this playlist after 0:00 GMT and is set to update it daily
- [X] I am aware that the channel source may have temporal outages. It is broken/absent from the playlist for couple of hours or days

### Channel Name

Brazilian Channels (TV Escola and TV Brasil)

### What happened to the stream?

It is now offline (disappeared from the playlist)

### Playlist

https://iptv-org.github.io/iptv/countries/br.m3u

### Notes

These channels were added by pull request #5554 and now are no longer available in the playlist.

**Comment by LaneSh4d0w** [comment]
TV Escola is now https://edge-mg-01.eduplay.rnp.br/media/ocp(r(SOtSyQ)t(AAAAAAAAAAA)p(d(ADo)k(EBE)m(WbdLZUjYCjx_8tRW2f3M1w)n(a(kLbutb9FljfAzjoWmXgS8Rnp6_GUlkq0)s(rRg)'a(T-aZqqGIQgBm6ZHJp3tHyyjZ)s(fvc)))s(t(eT8)b(6P9w9Nu8wcNIUaKqkTKqXRWNHWIhMz8mxUoA4mgo1tqnqVYwaZMCmldOaMbaZB0n33FR3ttihZ1JvOivSGdZIuAfecBVa16Et9eMjlLC13Rq6Cwwi8mycU0Iwr-66QiAe98vgBCT-AiPs61W_9bjrtb8ATEJw-JsxpVNlotY)'t(wDM)b(pbCqvGJQQWqY9cAtI-9-O9bngy67xc2Xu8ug)))/index.m3u8

TV Brasil geolocked https://eduplay-maestro.prd.apps.kloud.rnp.br/route/channel39285/index.m3u8?s=aHR0cHM6Ly9tZWRpYS1wcmQuZWR1cGxheS5ybnAuYnIvbWVkaWEvY2hhbm5lbDM5Mjg1L2luZGV4Lm0zdTg_eD0xJm09TDNuSnB1MExfSElNUXJzcVVTU2ZCUQ&x=1&p=1&m=8xYHT-eKYjbsb_GOLzyKFQ&nr=true

**Comment by freearhey** [comment]
@eltoncomp Please read the guide: https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream

**Comment by eltoncomp** [comment]
What's wrong with my request? But anyways it will be very hard to put these channels again in the playlist since the links provided are mantained by a government agency and Brazilian online applications are usually quite complicated.
