### ISSUE TITLE
Replace: FeiCuiTai81.hk

### ISSUE THREAD

**Issue by Polaris0112** [iptv-org/iptv#5869]
### I have verified that

- [X] I use the GitHub playlist link and not a downloaded/cached version of the file
- [X] My TV player has updated this playlist after 0:00 GMT and is set to update it daily
- [X] I am aware that the channel source may have temporal outages. It is broken/absent from the playlist for couple of hours or days

### Channel Name

翡翠台（81） (1080p)

### What happened to the stream?

It is now offline (disappeared from the playlist)

### Playlist

https://github.com/iptv-org/iptv/blob/master/channels/hk.m3u

### Broken Link

http://61.238.6.49:8000/bysid/1

### Notes

Please update if have replacement, thanks.

**Comment by Dum4G** [comment]
http://iptv.tvfix.org/hls/jade_a1.m3u8

**Comment by Dum4G** [comment]
http://185.207.176.189:8080/channels/tv-81/playlist.m3u8

and

http://185.207.176.189:8080/channels/tv-82/playlist.m3u8

also seem to be interesting but take a good while to load for me

**Comment by LaneSh4d0w** [comment]
> http://iptv.tvfix.org/hls/jade.m3u8

This link works better than the alternative one.

**Comment by Polaris0112** [comment]
> http://iptv.tvfix.org/hls/jade.m3u8

This link is awesome bro. Thanks for sharing.

**Comment by Dum4G** [comment]
Reopened till we get this link into the playlist
