### ISSUE TITLE
HK channels in Chinese playlist - Misleading placement

### ISSUE THREAD

**Issue by Lemonawa** [iptv-org/iptv#5876]
### Describe your issue

Some Hong Kong programs were incorrectly added to mainland China.
Such as 翡翠台.
(Taiwan Province, Macau also has the same problem)

**Comment by Dum4G** [comment]
Please specify each and every channel that you think are broadcasted from Hong Kong. In fact, all of them should have a studio in Hong Kong

**Comment by Lemonawa** [comment]
![图片](https://user-images.githubusercontent.com/69106050/147404680-96215471-c764-40d3-92af-dd1e97deaf75.png)
![图片](https://user-images.githubusercontent.com/69106050/147404688-e1eb2046-0c4d-4d5f-9aa6-11e0beb99555.png)

**Comment by Lemonawa** [comment]
And, some American and Japanese channels, because the channel name is Chinese, are also wrongly classified as Chinese

**Comment by Dum4G** [comment]
We need to know exact entries

**Comment by LaneSh4d0w** [comment]
> We need to know exact entries

I'll take a look, 2 seconds.

To be honest, the Chinese playlist really needs a clean-up. Some dead links are laying there since ages and some others are dupes.

**Comment by LaneSh4d0w** [comment]
https://github.com/iptv-org/iptv/blob/89c72ddf411749c491aaaa38be521210923296be/channels/cn.m3u#L574-L589

**Comment by freearhey** [comment]
Specified links removed from playlists.
