### ISSUE TITLE
[To Do]Cozi TV

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#5887]
### Channel Name

Cozi TV

### Country

USA-Nation Wide

### Language

English

### Website

Official Site:"https://www.cozitv.com/"

### Stream URL

http://212.102.60.76/s1/mono.m3u8

### Notes

After Deep Searching. 720p. H264-AAC

**Comment by LaneSh4d0w** [comment]
all downcase

B1 is The Tennis Channel
C1 is ?
D1 is PBS America
E1 is The NHL Network (we got a DMCA on this one, don't add it)
F1 is AMC
G1 is CNN
H1 is Animal Planet (Discovery Network, we got a DMCA on this one, don't add it)
I1 is ?
J1 is BBC World News
K1 is BET
L1 is ?
M1 is Bravo TV
N1 is B1G Network / ESPN
O1 is Cartoonito America
P1 is ?
Q1 is ?
R1 is The Cooking Channel (Tastemade affiliate ?)
S1 is COZI TV (you've already mentioned it on another issue)
T1 is ?
V1 is Destination America
W1 is Discovery (we got a DMCA in this one, don't add it)
X1 is Discovery Family (DMCA, don't add it)
Y1 is Discovery Life (DMCA, don't add it)
Z1 is Disney Channel America

A2 is TouchZone NFL Network (i think we also have a DMCA for this one, don't add it)
