### ISSUE TITLE
Fix: Tests getting time issues because of errors

### ISSUE THREAD

**Issue by LaneSh4d0w** [iptv-org/iptv#5900]
### Describe your issue

- Github's Actions services doesn't seem to get "ubuntu-latest" and is waiting indefinitely for something to get in, resulting in issues merging pull requests after everyone's approval.
- May be due to job overlapping (one job needs to be finished before all others can start

**Comment by freearhey** [comment]
I checked the logs and I don't see any errors in them. Could you give some example of such a pull request?

**Comment by LaneSh4d0w** [comment]
Not really an error, but job overlapping makes that one job stops all others from running. As an example : the Playlist Upgrades basically stops all other jobs from running, and takes a while.

**Comment by MapGuy11** [comment]
Just had this issue when trying to check my PR.

Can't find any online and idle self-hosted or hosted runner in the current repository, account/organization that matches the required labels: 'ubuntu-latest'

**Comment by LaneSh4d0w** [comment]
Stopped one of your attempts on checks, and it began checking Dum's BY PR.

**Comment by freearhey** [comment]
I'll check that later.

**Comment by freearhey** [comment]
As I found out, the reason for this is an organization-wide limit on the number of simultaneously running jobs: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits

This limitation could be bypassed by setting a higher priority for pull request checks, but unfortunately this feature has not been implemented yet: https://github.community/t/set-priority-for-workflow-execution/165628

So there's nothing I can do at this point.
