### ISSUE TITLE
Channels having multiple categories are badly sorted

### ISSUE THREAD

**Issue by allanf181** [iptv-org/iptv#5905]
### Describe your issue

Channels with multiple categories are not going to their categories in ``index.category.m3u`` (same in ``index.nsfw.m3u``), they are getting categories like ``Local;News``, ``Education;Local``, ``Education;Kids``.

The categories are getting unsorted too.

**Comment by LaneSh4d0w** [comment]
> ### Describe your issue
> 
> Channels with multiple categories are not going to their categories in `index.category.m3u` (same in `index.nsfw.m3u`), they are getting categories like `Local;News`, `Education;Local`, `Education;Kids`.
> 
> The categories are getting unsorted too.

Could be because of many factors : 

- If you add multiple categories (and shows that in the program you're using), it is most likely to prevent duplicate streams. Imagine having channels twice because you've added two categories and you decided to watch one then the other just after that.
- Could also be the program you're using not understanding multiple categories.

**Comment by allanf181** [comment]
https://github.com/iptv-org/iptv/blob/master/scripts/commands/generate-playlists.js#L181

the problem seems to be in this line, channels with multiple countries or multiple languages are added multiple times in the index, whereas channels with multiple categories are not

**Comment by LaneSh4d0w** [comment]
> https://github.com/iptv-org/iptv/blob/master/scripts/commands/generate-playlists.js#L181
> 
> the problem seems to be in this line, channels with multiple countries or multiple languages are added multiple times in the index, whereas channels with multiple categories are not

I think I get your reasoning.

To fix that, you should read every item, split their categories using the split function (in JS), and send back the newly made list.
To do this faster (and a bit more techy), add a condition that verifies if item.group_title contains ";".

Code would look like that : 

```
if (item.group_title.includes(";")) gp_title = item.group_title.split(";")
else item.group_title
```

Note that this code is for demonstration purposes, and wasn't tested it to see if it works.
