### ISSUE TITLE
Replace: MSNBC

### ISSUE THREAD

**Issue by jhedfors** [iptv-org/iptv#5907]
### I have verified that

- [X] I use the GitHub playlist link and not a downloaded/cached version of the file
- [X] My TV player has updated this playlist after 0:00 GMT and is set to update it daily
- [X] I am aware that the channel source may have temporal outages. It is broken/absent from the playlist for couple of hours or days

### Channel Name

MSNBC

### What happened to the stream?

It is stuck at a single frame/the same segment

### Playlist

USA

### Broken Link

http://1111296894.rsc.cdn77.org/LS-ATL-54548-10/tracks-v1a1/mono.m3u8

### Possible Replacement

https://msnbc1.akamaized.net/hls/live/2021744/MSNBC0f2497d0/clear/hdntl=exp=1640838119~acl=%2f*~data=hdntl~hmac=a0e7dc8326f3d902cb4d227b45e0dede52187ae7da88980c388f9096438320b7/VIDEO_1_4596000.m3u8

**Comment by Central302** [comment]
Working on My Side(Safari, iPhone)

**Comment by jhedfors** [comment]
Agreed. Looks like it is working again. Thanks.
