### ISSUE TITLE
NBC EAST HD

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#5915]
### Channel Name

WNBC (New York) NBC HD East

### Country

US

### Language

ENGLISH

### Website

https://www.directv.com/Channels/WNBC-New-York-NBC-East-392

### Notes

HD IF POSSIBLE!

**Comment by Central302** [comment]
It Meaning Request for "WNBC-DT1"?
If you need Simply Need "NBC East", You Can Use WBTS-CD Boston Stream in US Playlist.

**Comment by MapGuy11** [comment]
> It Meaning Request for "WNBC-DT1" (Full Channel of NBC New York)? If you need "NBC East", You Can Use Instead WBTS-CD Boston Stream in US Playlist.

I am going to close this.

**Comment by jphilippe2017** [comment]
Perfect, I totally appreciate your reply. I was not aware that this station was under WBTS

Thanks so much!
