### ISSUE TITLE
Fix: triple request approval kills the repository

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#5916]
### Describe your issue

We don't have 3 active maintainers to verify new submissions. As a result we have a queue of 14 PRs just in 3 days. And those that finally got 3 approvals have conflicts to be resolved now. Please revert it for 2 approvals needed

**Comment by MapGuy11** [comment]
@Dum4G also a lot of the PR can go but they have issues as an FYI but I do think 3 is a lot for a PR.

**Comment by freearhey** [comment]
Done.
