### ISSUE TITLE
Replace: Ronahî TV

### ISSUE THREAD

**Issue by TheRedEaglee** [iptv-org/iptv#5942]
### I have verified that

- [X] I use the GitHub playlist link and not a downloaded/cached version of the file
- [X] My TV player has updated this playlist after 0:00 GMT and is set to update it daily
- [X] I am aware that the channel source may have temporal outages. It is broken/absent from the playlist for couple of hours or days

### Channel Name

Ronahi tv

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://github.com/iptv-org/iptv/blob/master/channels/sy.m3u

### Broken Link

http://163.172.39.215:25461/live/line/C4@!a3a1@!w72A/26.m3u8

### Possible Replacement

http://51.89.6.117/LiveApp/play.html?name=912546730243290230820991

**Comment by Sphinxroot** [comment]
the broken link is a X-stream code and shouldnt be there 

replacment link will be hard because it use websocket 

maybe this one https://karwan.tv/live/ronahi-tv.php ( token )  could be streamlinked online if @LaneSh4d0w  or other , wanna host it

**Comment by LaneSh4d0w** [comment]
> the broken link is a X-stream code and shouldnt be there
> 
> replacment link will be hard because it use websocket
> 
> maybe this one https://karwan.tv/live/ronahi-tv.php ( token ) could be streamlinked online if @LaneSh4d0w or other , wanna host it

You just gave me an idea.

**Comment by TheRedEaglee** [comment]
Nothing worked?

**Comment by LaneSh4d0w** [comment]
> the broken link is a X-stream code and shouldnt be there
> 
> replacment link will be hard because it use websocket
> 
> maybe this one https://karwan.tv/live/ronahi-tv.php ( token ) could be streamlinked online if @LaneSh4d0w or other , wanna host it

By what i've seen transiting on the websocket, I have RTP A/V host 51.89.6.117;51575 popping.

**Comment by TheRedEaglee** [comment]
I guess nothing worked of that

**Comment by LaneSh4d0w** [comment]
> > the broken link is a X-stream code and shouldnt be there
> > replacment link will be hard because it use websocket
> > maybe this one https://karwan.tv/live/ronahi-tv.php ( token ) could be streamlinked online if @LaneSh4d0w or other , wanna host it
> 
> You just gave me an idea.

I am learning from the streamlink plugins, I think I can do something up.

**Comment by TheRedEaglee** [comment]
I hope it works with you and it be easy.

**Comment by LaneSh4d0w** [comment]
https://raw.githubusercontent.com/LaneSh4d0w/streamlink/master/src/streamlink/plugins/karwan.py @dct-infra

**Comment by dct-infra** [comment]
@LaneSh4d0w Try it now.

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://karwan.tv/live/ronahi-tv.php

**Comment by TheRedEaglee** [comment]
Yeah it's seems the stream works perfect but ig it need to get to m3u8 link which idk if its hard or not.

**Comment by TheRedEaglee** [comment]
@LaneSh4d0w https://live.karwan.tv/karwan.tv/ronahi-tv/playlist.m3u8 works on hls

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w https://live.karwan.tv/karwan.tv/ronahi-tv/playlist.m3u8 this could help

Indeed

**Comment by TheRedEaglee** [comment]
> > @LaneSh4d0w https://live.karwan.tv/karwan.tv/ronahi-tv/playlist.m3u8 this could help
> 
> Indeed

Isn't that working with you for me its working and all good ig you could replace it.

**Comment by TheRedEaglee** [comment]
![Screenshot_20220211-175934_Chrome](https://user-images.githubusercontent.com/89548092/153635220-3b31b08b-dd44-469f-9850-ac2d635a5775.jpg)
For me I have both

**Comment by TheRedEaglee** [comment]
Now not working for me idk like it was working before and today not which confuse me

**Comment by LaneSh4d0w** [comment]
Could be because channel is Not 24/7, or maybe it was a test from the
streaming service behind it.

Le sam. 12 févr. 2022 à 10:32, TheRedEagle ***@***.***> a
écrit :

**Comment by TheRedEaglee** [comment]
Yeah I think it's not 24/7 bcs it's working again now
