### ISSUE TITLE
Add: Todo Deportes TV Más (TDTV+)

### ISSUE THREAD

**Issue by fershady** [iptv-org/iptv#5943]
### Channel Name

Todo Deportes TV Más (TDTV+) 

### Country

Honduras

### Language

spanish

### Website

https://tododeportestv.com/tdtvplus_envivo

### Stream URL

https://5fe2654d6127d.streamlock.net/tododeportesplus/smil:tododeportesplus.smil/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MS8yLzIwMjIgOTozMTowOCBQTSZoYXNoX3ZhbHVlPTBYS0JFUWIzaU9GYmUwektLNlVrenc9PSZ2YWxpZG1pbnV0ZXM9MzYwMCZpZD0=

### Notes

Category: Sports

**Comment by LaneSh4d0w** [comment]
Ouch for the tokenized stream.

One of the many cases in which I can't tell if the links are gonna stay for long or not.

**Comment by MapGuy11** [comment]
> Ouch for the tokenized stream.
> 
> One of the many cases in which I can't tell if the links are gonna stay for long or not.
> 
> https://conceptoweb-studio.com/radio/video/tododeportesplus/ and a simple HTML lookup gives us the URL loud and clear.

What's funny is that token still works they may not have it where a token expires.

**Comment by LaneSh4d0w** [comment]
> > Ouch for the tokenized stream.
> > One of the many cases in which I can't tell if the links are gonna stay for long or not.
> > https://conceptoweb-studio.com/radio/video/tododeportesplus/ and a simple HTML lookup gives us the URL loud and clear.
> 
> What's funny is that token still works they may not have it where a token expires.

Can't tell, had a different token when getting in. Maybe they last a day, or two, or more, idk.

**Comment by LaneSh4d0w** [comment]
https://raw.githubusercontent.com/LaneSh4d0w/streamlink/master/src/streamlink/plugins/conceptoweb_mx.py @dct-infra

**Comment by LaneSh4d0w** [comment]
I see it was pulled out, works for me.

@fershady is it OK ?

**Comment by dct-infra** [comment]
403 for me

**Comment by LaneSh4d0w** [comment]
> 403 for me

Weird, works for me

![vlcsnap-2022-01-30-16h59m37s000](https://user-images.githubusercontent.com/30985701/151705021-28726dde-9ee3-49da-81ed-e371d7f4ebb9.png)

**Comment by dct-infra** [comment]
Yeah changed IP and works now, geoblocked probably.

**Comment by LaneSh4d0w** [comment]
> Yeah changed IP and works now, geoblocked probably.

Certainly.

**Comment by fershady** [comment]
Work fine for me
