### ISSUE TITLE
Replace: Iran International

### ISSUE THREAD

**Issue by alireza1974** [iptv-org/iptv#5951]
### Channel Name

Iran International 

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/countries/ir.m3u

### Broken Link

https://dev-live.livetvstream.co.uk/LS-63503-4/index.m3u8

### Notes

I can play this channel on VLC player on my PC, but not if I use an application for IPTV on my smart TV. The application tries to load the channel, but it gets the message channel error.

**Comment by Dum4G** [comment]
Have you tried Televizo?

**Comment by alireza1974** [comment]
I tried Televizo on my smartphone, and it works for the channel Iran International. But is that possible to have this application also on my smart TV? I tried to download the APK file from the website of Televizo on my smart TV, but I got a message that the format of the file is not supported. Can you give me a trustable website when I can download the APK file on my smart TV, or it is not possible at all to install this application on my smart TV ?

**Comment by Dum4G** [comment]
If you have Samsung or LG smart TV you should probably try SS IPTV

**Comment by alireza1974** [comment]
Unfortunately, I am unable to install SS IPTV on my smart TV. I asked a question about this on SS IPTV forum and so far I have not received any reaction. 
I do have Iran International channel on my android box when I use the same m3u list. If you haven't another solution, then I suggest that we close this issue.

**Comment by freearhey** [comment]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/7253922/159468200-b6451568-efc2-45e5-a876-72db28caf66b.png">
