### ISSUE TITLE
CBS ALBANY

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#5959]
### Channel Name

CBS ALBANY

### Country

US

### Language

ENGLISH

### Website

https://cbs6albany.com/

**Comment by Central302** [comment]
LIve News Channel is Already in US playlist.

**Comment by jphilippe2017** [comment]
I Yes but, none of the channels are CBS Albany and it does exist.

**Comment by trancer1994** [comment]
@jphilippe2017 Is this what you're looking for? https://content.uplynk.com/db5e4d299d4b41f59720c3d1d89dbe86.m3u8?tc=1&exp=1641402036&rn=227960&ct=a&cid=db5e4d299d4b41f59720c3d1d89dbe86&sig=342f7c6f7393b165a40e913cd686c39c02e65d290b2d39b9ce91ab676e8dfaf0

**Comment by jphilippe2017** [comment]
YES! Thank you so much, you are #1

I have a few more channel requests in the line up (jphilippe2017), if ever you have those too, I would greatly appreciate it!

**Comment by jphilippe2017** [comment]
Is there an m3u8 file for this station? Because the link you sent is a playback and not live?

**Comment by Dum4G** [comment]
https://content.uplynk.com/channel/bba3e7da884a49bba96341ecf5128f0f.m3u8

Shows a splash screen right now

**Comment by jphilippe2017** [comment]
Thanks so much Dum4G, I really wanted this one!

**Your awesome**!!!!
