### ISSUE TITLE
PBS Burlington VT (WETK)

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#5960]
### Channel Name

PBS BURLINGTON

### Channel ID

WETKDT1.us

### Country

US

### Language

ENGLISH

### Website

https://www.vermontpbs.org/

**Comment by LaneSh4d0w** [comment]
https://wetkdt.lls.pbs.org/out/v1/eab01328db844f10b27ede5eea206097/dash-drm.mpd is the only stream available.
URS gives a redirect from c0ebd1026c634ad298b4c8ba988e53dc but this ID gives us 403 if we try to get anything from it.

**Comment by jphilippe2017** [comment]
Thank you, I tried the link you gave but it does not load, perhaps because of your mentioned issue with the link.

Anyone? PBS BURLINGTON (HD if possible)

**Comment by jphilippe2017** [comment]
Excellent, thanks again!

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/cac2f96962f43fcec08d835b0878ed36307d4bbe/streams/us_pbs.m3u#L136-L137
