### ISSUE TITLE
TELE-MAG QUEBEC

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#5961]
### Channel Name

TELE-MAG QUEBEC

### Country

CANADA

### Language

FRENCH

### Website

https://tele-mag.tv/

**Comment by Central302** [comment]
Official Site Have Youtube CDN Stream.
https://youtu.be/R8HNcrnyrzs

**Comment by jphilippe2017** [comment]
That is perfect, thank you!

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCNKXYT-Nng5LBMUQrZJ9zWA/live

**Comment by jphilippe2017** [comment]
Thank you, this one works best: https://www.youtube.com/watch?v=R8HNcrnyrzs
