### ISSUE TITLE
Replace: CANAL DE L'ASSNAT

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#5962]
### Channel Name

CANAL DE L'ASSNAT

### Country

CANADA

### Language

FRENCH

### Website

http://www.assnat.qc.ca/fr/video-audio/canal-assemblee/semaine-cours.html

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-id="AssembleeNationale.ca" tvg-name="Assemblee Nationale CA" tvg-logo="https://i.imgur.com/xKNnoci.png" group-title="Affaires Publiques",Assnat (360p)
https://wowzaprod231-i.akamaihd.net/hls/live/1013830/177d227e/playlist.m3u8

**Comment by jphilippe2017** [comment]
Thank you Sphinx!

But the m3u8 link does not load and, is a link available in a higher resolution ?

**Comment by Sphinxroot** [comment]
nop sorry but not 24/7 for this one

**Comment by jphilippe2017** [comment]
Thank you!

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/ca.m3u#L6-L7

**Comment by freearhey** [comment]
The broken link has been removed from the playlist.

Closed in favor #8171
