### ISSUE TITLE
CBS USA

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#5968]
### Channel Name

CBS

### Country

USA

### Language

ENGLISH

### Website

https://www.cbs.com/

### Notes

THE ORIGINAL CBS IN USA - NOT THE LOCAL CHANNELS

**Comment by what-a** [comment]
These are already in the US playlist. Are they working for you?
![image](https://user-images.githubusercontent.com/88639906/148108599-7ba58d36-d88c-4ab1-bb8e-badf69762b18.png)

**Comment by jphilippe2017** [comment]
Thank you for your reply but like my posting reads, I am looking for the Original CBS News (preferably in 1080p)
that is **NOT local channels**, the original station. It does exist because I do see it in other iptv profiles other than on this website.

If anyone reads this posting and has a reliable CBS HD link, that would be great.

Thank you

**Comment by what-a** [comment]
Ha, I thought you wanted non-news.
Okay, how about...
![image](https://user-images.githubusercontent.com/88639906/148129756-ec2fc59d-3e3a-4a83-b457-fcf17fce1827.png)

**Comment by jphilippe2017** [comment]
Thank you for this, but I do see this one exists.

In other iptv packages, I have seen CBS News HD and a seperate and other link for the one you just mentioned
CBSN.

I am certain a link exists to CBS (hopefully in 1080p) that is not local channels, simply CBS HD
That would be the main CBS channel.

Again thank you, but not this link...

**Comment by Sphinxroot** [comment]
normaly this will be the only legit  web stream source
https://www.cbsnews.com/live/
other are local cbs / affiliate  many have token stream

other than that , it wont be  a legitimate stream

**Comment by jphilippe2017** [comment]
Great, thanks again Sphinx!
