### ISSUE TITLE
Replace: C-SPAN 3

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#5971]
### Channel Name

C-SPAN 3

### What happened to the stream?

I see visual artifacts

### Playlist

https://iptv-org.github.io/iptv/index.nsfw.m3u

### Broken Link

https://skystreams-lh.akamaihd.net/i/SkyC3_1@500808/master.m3u8

### Notes

Sound is missing, we only have visual?

**Comment by MapGuy11** [comment]
#6018
