### ISSUE TITLE
Replace: C-SPAN 1

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#5972]
### Channel Name

C-SPAN 1

### What happened to the stream?

I see visual artifacts

### Playlist

https://iptv-org.github.io/iptv/index.nsfw.m3u

### Broken Link

https://skystreams-lh.akamaihd.net/i/SkyC1_1@500806/master.m3u8

### Notes

We only have visual, sound is missing?

**Comment by MapGuy11** [comment]
@LaneSh4d0w check iptv-all

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w check iptv-all

On it

**Comment by MapGuy11** [comment]
#6018
