### ISSUE TITLE
Replace: Pluto TV Classic Movies (684p)

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#5982]
### Channel Name

Pluto TV Classic Movies (684p)

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/index.nsfw.m3u

### Broken Link

https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/561c5b0dada51f8004c4d855/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=561c5b0dada51f8004c4d855&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=106&terminate=false&userId=

### Notes

Does not load

**Comment by Sphinxroot** [comment]
no issue here  might depend on the player used

try this one  both work 
http://stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/561c5b0dada51f8004c4d855/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=%7BTARGETOPT%7D&deviceId=%7BPSID%7D&advertisingId=%7BPSID%7D&us_privacy=1YNY&samsung_app_domain=%7BAPP_DOMAIN%7D&samsung_app_name=%7BAPP_NAME%7D&profileLimit=&profileFloor=&embedPartner=samsung-tvplus

**Comment by jphilippe2017** [comment]
Tried you new link and this one does not load either?

Are you sure this channel is really working for you?

**Comment by jphilippe2017** [comment]
By the way Sphinx, what player are you using, so I can try it too, especially because your player seems to be better
at not causing issues?

**Comment by Sphinxroot** [comment]
i would say  that all stream scrapped by Matt Huisman are top notch  ,  i never had any issue  ,  try  these  , if nothing play , it something on your side 

https://github.com/matthuisman/i.mjh.nz/blob/master/PlutoTV/us.m3u8

**Comment by Sphinxroot** [comment]
work on kodi , potplayer , perfect player , vlc , progdvb

**Comment by jphilippe2017** [comment]
The file you send me: https://github.com/matthuisman/i.mjh.nz/blob/master/PlutoTV/us.m3u8

Is empty, it has 336 names inside without any of them having any links?

Sorry, I think you should check on your side, cant read an empty file?

![05-01-2022](https://user-images.githubusercontent.com/27918129/148165632-77c17479-956d-4d2e-aa22-dfadbb262846.jpg)

**Comment by jphilippe2017** [comment]
Here is a screenshot of your link replacement: Does not load

![Screenshot - 05_01_2022 , 12_36_09 AM](https://user-images.githubusercontent.com/27918129/148165968-457a0493-0335-4a84-a620-bfb248aa2280.jpg)

**Comment by jphilippe2017** [comment]
VLC does load it, you are correct. I will contact my supplier.

Thanks Sphinxroot

Closing all my other issues now, just in case.

**Comment by Sphinxroot** [comment]
test it in raw https://raw.githubusercontent.com/matthuisman/i.mjh.nz/master/PlutoTV/us.m3u8  but as i said no issue  and  it play also on tivimate

**Comment by jphilippe2017** [comment]
Yes, it does work in VLC. Totally an issue with my player (I paid for).

Sorry for my mistake and thanks again buddy!

**Comment by jphilippe2017** [comment]
Please leave this thread open for a few days, as the supplier of the player I just had issues with, needs to please
read this thread before it closes.

I will close this myself in a few days.

Thanks so much

**Comment by freearhey** [comment]
Don't worry, the thread will still be available via link even after it is closed.

**Comment by jphilippe2017** [comment]
Perfect, thanks so much!
