### ISSUE TITLE
Replace: Pluto TV Doctor Who Classic (720p)

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#5988]
### Channel Name

Pluto TV Doctor Who Classic (720p)

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/index.nsfw.m3u

### Broken Link

https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5ce4475cd43850831ca91ce7/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5ce4475cd43850831ca91ce7&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=532&terminate=false&userId=

### Notes

Does not load

**Comment by Joenzii** [comment]
cant get the doctor who stuff to work anymore
