### ISSUE TITLE
Add: An chat tarot 24/7 in Spain

### ISSUE THREAD

**Issue by joaquinito2048** [iptv-org/iptv#5998]
### Channel Name

An chat tarot 24/7 in Spain

### Country

Spain

### Language

Spanish

### Website

You find it. :)

**Comment by freearhey** [comment]
> You find it. :)

So it shouldn't be too hard for you, either.

And please read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel) before posting your next request.
