### ISSUE TITLE
Replace a bunch of japanese channels

### ISSUE THREAD

**Issue by dedarmstrong** [iptv-org/iptv#5999]
### Channel Name

NHK G NHK E  TV Tokyo Fuji TV TV Asahi

### What happened to the stream?

They don't work

### Playlist

jp.m3u

### Broken Link

All of the above

### Possible Replacement

None

### Notes

They don't work now

**Comment by freearhey** [comment]
Please read this: https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream
