### ISSUE TITLE
Replace: All Japanese Channels Doesn't Work

### ISSUE THREAD

**Issue by Getze56901** [iptv-org/iptv#6001]
### Channel Name

Animax Japan, AT-X, Fuji TV, TBS And More

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://iptv-org.github.io/iptv/countries/jp.m3u

**Comment by dedarmstrong** [comment]
Thanks for copying me

**Comment by dedarmstrong** [comment]
Though in all honesty I am happy I am not alone in having issues with japanese tv

**Comment by Dum4G** [comment]
Duplicate of #5999

**Comment by Dum4G** [comment]
We hear you loud and clear. We'll do our best to find an alternative (when and if possible tho)

**Comment by GiovanniSebastian** [comment]
Token: 
http://50.7.74.29:8080/hlsok/j00038/index.m3u8?key=aIq61Ui88wXMJKhDr-0x-Q&expires=1641511091&mac=38:80:df:0f:e4:c6

**Comment by GiovanniSebastian** [comment]
This link responds but don' work: http://50.7.74.29:8080/hlsok/j00038/index.ts
