### ISSUE TITLE
Replace: KBS1

### ISSUE THREAD

**Issue by ghost** [iptv-org/iptv#6004]
### Channel Name

KBS1

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://github.com/iptv-org/iptv/blob/master/channels/kr.m3u

### Broken Link

http://121.130.210.101:9981/stream/channelid/637185705

**Comment by trancer1994** [comment]
https://1tvhd.gscdn.kbs.co.kr/1tv-02/1tv-02_hd.m3u8?Expires=1641663010&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly8xdHZoZC5nc2Nkbi5rYnMuY28ua3IvMXR2LTAyLzF0di0wMl9oZC5tM3U4IiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjQxNjYzMDEwfX19XX0_&Signature=iO6sRrEn6C-MFzWpJQzKC9Zs8tn8RcM7MZ~ELVUrC-VC~VBRUiahqRZm18E9rn5ydh~ogYXkAH0kHU8dUU2q~tKxFr6o8Jl1RFGZOvrysNpjHEfN~o4Jf03JbBKVjK5jpG1LE5Dy8COqLqXbR4-e~TlBcum63B5mBaC0f8saTgcqaa5nqw1WXOxXa0bNh8KcByC59IlssLxnSSOBJjWLlJzcpIA8kbD3WlDlld8CcjCCjM2ZreY4lZ~r9ANLtTuqLgIfWR7bpsQ99J4JB4qOClz6-uO63aF~KCWjTR8wp19eBZIkagkvDD92aNuB~aaX47rfjz2jFenZDIl2We1BwQ__&Key-Pair-Id=APKAICDSGT3Y7IXGJ3TA

**Comment by LaneSh4d0w** [comment]
I had told that there is a way to get it, but you need to get it from their API, which needs some code to work.

**Comment by freearhey** [comment]
Closed in favor https://github.com/iptv-org/iptv/issues/7724
