### ISSUE TITLE
Add: MyTV Virginia (WZBJ-CD)

### ISSUE THREAD

**Issue by stanloonabelike** [iptv-org/iptv#6009]
### Channel Name

WZBJ-CD

### Country

USA

### Language

English

### Website

https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.wdbj7.com/page/wzbj24&ved=2ahUKEwiRrce7hJ71AhWWg3IEHdGXD0gQFnoECAUQAQ&usg=AOvVaw3I4Ui5p5o1rUvM-Fq0yzGx

### Stream URL

N/A

### Notes

Can't find WZBJ on my antenna nor online.

**Comment by LaneSh4d0w** [comment]
https://www.wdbj7.com/livestream/

https://dai2-playlistserver.aws.syncbak.com/playlist/13736704/master.m3u8?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkdyYXkyMDE2MDgyOSJ9.eyJtaWQiOjEzNzM2NzA0LCJtZDUiOiI1ZTJiYTE0NzUwZmZiYmZjMzdkNDhkNWRiMzg3ZWY5NSIsImlhdCI6MTUwMTYyMDcxOCwiaXNzIjoiU3luY2JhayIsInN1YiI6IkdyYXkifQ.yl9qw85OE2fPnoWZGo2N7cKQZXWOFwJnvEnZ80h5agw

**Comment by stanloonabelike** [comment]
that isn't the right one. WDBJ (CBS) owns WZBJ (Mynetwork)

**Comment by LaneSh4d0w** [comment]
I see.

**Comment by LaneSh4d0w** [comment]
@MapGuy11 any visibility on this one ? Being streamed from Danville/Roanoke/Lynchburg VA

**Comment by MapGuy11** [comment]
> @MapGuy11 any visibility on this one ? Being streamed from Danville/Roanoke/Lynchburg VA

I highly doubt it.
