### ISSUE TITLE
Add: Ici RDI

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#6011]
### Channel Name

Ici RDI

### Country

CANADA

### Language

FRENCH

### Website

https://ici.radio-canada.ca/rdi

### Stream URL

https://rcavlive.akamaized.net/hls/live/704025/xcanrdi/master.m3u8

### Notes

1080P (HD) PLEASE!

**Comment by LaneSh4d0w** [comment]
Works perfectly on my side, Serbian IP.

**Comment by LaneSh4d0w** [comment]
Since it's Canadian : 

Radio-Canada Ici-Télé : https://dai.google.com/linear/hls/event/ixE_JVvSSCWyxU7eXJoV-A/master.m3u8

Radio-Canada Ici-Télé Acadie : https://rcavlive.akamaized.net/hls/live/696615/xcancbft/master.m3u8

**Comment by jphilippe2017** [comment]
Thank you so much, that's fantastic guys!

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1d5ac2cfd591466086b3f97fc403163e45b16a74/streams/ca.m3u#L104-L105

**Comment by littlemoon-mini** [comment]
https://rcavlive.akamaized.net/hls/live/704026/canrdi/master_2500.m3u8

**Comment by michelmenard** [comment]
The signal cuts out as if it were in Canada. Before we had this message about “Great Documentaries” in the evenings, but now we still have this message. “**Sorry In accordance with broadcasting rights, this video is not accessible in your country**”.
![image](https://github.com/user-attachments/assets/8b51bc57-f663-4066-9100-772cec7e9400)

**Comment by Blackholer** [comment]
> They're not allowed to show Olympic highlights outside of Canada, so they have to blackout the newscasts on RDI's "xcan" international stream.

Is there anything to be done?

**Comment by Blackholer** [comment]
> Wait for the Olympics to end

Understood!  😜

**Comment by Blackholer** [comment]
Is there a new problem with RDI?  it's back like  during the Olympics... It worked for a while but it's not anymore.

**Comment by BellezaEmporium** [comment]
Paralympics.

**Comment by Blackholer** [comment]
Hi, RDI not working anymore. I don't even get the page like during the Olympics...  It just don't open anything....  I use a VPN set to Detroit.

**Comment by Tuizi** [comment]
https://rcavlive.akamaized.net/hls/live/704025/xcanrdi/*** returns 404

**Comment by BellezaEmporium** [comment]
Talking about this one ? https://rcavlive.akamaized.net/hls/live/696615/xcancbft/master.m3u8

**Comment by Tuizi** [comment]
Yes it works for me too now.
