### ISSUE TITLE
Add: BOUNCE XL 

### ISSUE THREAD

**Issue by stanloonabelike** [iptv-org/iptv#6023]
### Channel Name

BOUNCE XL

### Country

USA

### Language

English

### Website

https://pluto.tv/en/live-tv/bounce-xl 

### Notes

if you cannot pull from pluto, samsung tv plus has it i think.

**Comment by MapGuy11** [comment]
From Pluto:
https://siloh.pluto.tv/lilo/production/BounceXL/master.m3u8

From Samsung: 
https://c217322ca48e4d1e98ab33fe41a5ed01.mediatailor.us-east-1.amazonaws.com/v1/master/04fd913bb278d8775298c26fdca9d9841f37601f/Samsung_BounceXL/playlist.m3u8

**Comment by stanloonabelike** [comment]
THANK YOU!

**Comment by MapGuy11** [comment]
> THANK YOU! 

Why did you close this you didn't make a PR.

**Comment by MapGuy11** [comment]
#6041
