### ISSUE TITLE
Replace: MSNBC

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#6026]
### Channel Name

MSNBC

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/index.nsfw.m3u

### Broken Link

http://1111296894.rsc.cdn77.org/LS-ATL-54548-10/playlist.m3u8

### Notes

Does not load - Replace with HD link if possible :)

**Comment by Central302** [comment]
Connection Timeout "?" I'll Check Later.
