### ISSUE TITLE
Replace: History East

### ISSUE THREAD

**Issue by Intrudr-Sec** [iptv-org/iptv#6035]
### Channel Name

History

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/countries/us.m3u

### Broken Link

https://bk7l2w4nlx53-hls-live.5centscdn.com/HISTORY/961ac1c875f5884f31bdd177365ef1e3.sdp/playlist.m3u8

### Notes

We get wrong history channel, this one is anthym.tv

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/a4c2ca1dd8142efd17cd8f2a6f82bf2bfb46691c/streams/us.m3u#L536-L537
