### ISSUE TITLE
Replace: ARTE.FR

### ISSUE THREAD

**Issue by jphilippe2017** [iptv-org/iptv#6039]
### Channel Name

ARTE.FR

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/countries/fr.m3u

### Broken Link

http://stream.tvtap.net:8081/live/fr-arte.stream/playlist.m3u8

### Notes

Does not load, even after changing our IP to different France IP's

**Comment by jphilippe2017** [comment]
This Arte link does work: https://artesimulcast.akamaized.net/hls/live/2031003/artelive_fr/index.m3u8
But this link does **not** work: http://stream.tvtap.net:8081/live/fr-arte.stream/playlist.m3u8

Both of these links are in your fr.m3u file

**Comment by freearhey** [comment]
@Dum4G Please give a reason or link to PR when you close an issue, so others can see the result too.
