### ISSUE TITLE
It doesn't have any issues

### ISSUE THREAD

**Issue by PrinceJethe** [iptv-org/iptv#6051]
### Channel Name

Sony Marathi

### Country

India

### Language

Marathi

### Website

HD Streamz

### Stream URL

https://pubads.g.doubleclick.net/ssai/event/-_w3Jbq3QoW-mFCM2YIzxA/master.m3u8?t=35b39e3a66715770aac9481e113fb61dd50d7b22ba80f1e0b03efe12236a2762a7628c469ab7632da8bc1b874dee4cba6d14e87ebb1e5c07e8a9cdc750f5c405892b61c1d96813

### Notes

It is safe

**Comment by freearhey** [comment]
Duplicate #6037
