### ISSUE TITLE
Replace: Fox News Channel

### ISSUE THREAD

**Issue by zilvin** [iptv-org/iptv#6054]
### Channel Name

Fox News Channel

### What happened to the stream?

Poor bandwidth server-side (Long buffering in stream)

### Playlist

https://iptv-org.github.io/iptv/countries/us.m3u

### Notes

Picture quality is great. Buffering every 5-10-15 seconds. Gigabit internet, fibre optic to the flat, ethernet to android box. Other channels such as Fox 32 are fine without buffering

**Comment by zilvin** [comment]
It seems that Fox News has recently been replaced with an updated stream link. Previous link had worse picture quality, but did not suffer buffering. The new one has an amazing quality, but buffers every now and then, the stream is simply unwatchable. There are no connectivity issues on my end, as I have low latency (3ms ping to 8.8.8.8), and am able to pull 950mbps down/600mbps up. Android TV is connected via UTP rather than wireless. Other channels don't exhibit the buffering issue.

**Comment by LaneSh4d0w** [comment]
I'm gonna need to change OP to reflect the issue, stream works, but poor bandwidth can be seen.

**Comment by zilvin** [comment]
Thank you. Any idea on whether this will be fairly straightforward to resolve?

**Comment by LaneSh4d0w** [comment]
I cannot tell, if it's an official source we can't do much apart of giving alternatives. The original Fox News streams needs a provider ID to get access to the stream.

**Comment by zilvin** [comment]
Thank you, I leave this in your capable hands. I doubt it is the official source, as usually these companies have great bandwidth and employ a CDN. Would be great if an alternative source is found.

**Comment by Toei79** [comment]
you need dig and dig maybe found something i dont watch this channel but my step father does .
