### ISSUE TITLE
Replace: NHK E

### ISSUE THREAD

**Issue by herezajuno** [iptv-org/iptv#6064]
### Channel Name

NHK E Japan

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/languages/jpn.m3u

### Broken Link

http://50.7.74.29:8880/hls/j00034/index.m3u8

**Comment by Central302** [comment]
Link Responds Nothing, May Source Dead. (All Links From This Domain Are Not Work.)

**Comment by dedarmstrong** [comment]
I have the same isue

**Comment by Dum4G** [comment]
Port 61981 is the only one that responds with 404s now. Clearly they're not happy about us

**Comment by jplagden** [comment]
Channels from this IP are working again

**Comment by Nobodynumber1** [comment]
**It can work** 

@herezajuno

**Comment by herezajuno** [comment]
Thank you.

**Comment by LaneSh4d0w** [comment]
Closed issue after remarks telling that links work again.

**Comment by Nobodynumber1** [comment]
Now  port:8880 just open  around 8hours in one day. 
 US 05:00AM - 06:00PM not work (EST)
