### ISSUE TITLE
Canal 22 México

### ISSUE THREAD

**Issue by herezajuno** [iptv-org/iptv#6065]
### Channel Name

XEIMT-TDT (Canal 22)

### Country

Mexico

### Language

Spanish

### Website

https://www.canal22.org.mx/

**Comment by Sphinxroot** [comment]
https://5fc584f3f19c9.streamlock.net/canal22/smil:canal22.smil/playlist.m3u8 +?wmsAuthSign=Token

https://5fc584f3f19c9.streamlock.net/canal222/smil:canal222.smil/playlist.m3u8 +?wmsAuthSign=Token

but no mediamanifest found

could be ... not 24/7 ?

**Comment by herezajuno** [comment]
I don't know if the channel is 24/7, the only thing I know it is geoblocked

**Comment by LaneSh4d0w** [comment]
> 

Tokenized on my side indeed. Can't tell if the AuthSign is IP-related or not.

**Comment by LaneSh4d0w** [comment]
Since I've worked on a plugin using similar host : http://free.fullspeed.tv/iptv-query?streaming-ip=https://conceptoweb-studio.com/radio/video/canal22/
