### ISSUE TITLE
Add: WPXC-DT6 (Laff)

### ISSUE THREAD

**Issue by stanloonabelike** [iptv-org/iptv#6078]
### Channel Name

LAFF JACKSONVILLE FLORIDA

### Country

USA

### Language

English

### Website

https://www.iontelevision.com

### Stream URL

N/A

### Notes

Can't find LAFF on us.m3u

**Comment by LaneSh4d0w** [comment]
Planned to be added once we sort out certain issues. (Not WPXC, but another affiliate for sure).

**Comment by MapGuy11** [comment]
LAFF Added

**Comment by freearhey** [comment]
@MapGuy11 Yes, I changed your role to "Read" and it does not allow to manage issue. The full list of actions this role allows you to perform can be found here: https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role 

When GitHub opens up access for everyone to create [custom repository roles](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-peoples-access-to-your-organization-with-roles/managing-custom-repository-roles-for-an-organization), I'll change it to another one.

**Comment by MapGuy11** [comment]
> @MapGuy11 Yes, I changed your role to "Read" and it does not allow to manage issue. The full list of actions this role allows you to perform can be found here: https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role 
> 
> When GitHub opens up access for everyone to create [custom repository roles](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-peoples-access-to-your-organization-with-roles/managing-custom-repository-roles-for-an-organization), I'll change it to another one.

Ok sorry just wanted to ask I thought it was something on my end is this across the board or did I do something to change this? Thanks again.

**Comment by spotanjo3** [comment]
Laff m3u8 is dead.

**Comment by LaneSh4d0w** [comment]
Why was this one referenced when added channel is GetTV not Laff ?

**Comment by MapGuy11** [comment]
Watching LAFF right now working: 
![image](https://user-images.githubusercontent.com/43685307/156930454-b57cb7a6-433d-4250-974e-cb9b7298b188.png)

**Comment by spotanjo3** [comment]
Laff is GetTV ? I am confused.

**Comment by spotanjo3** [comment]
Me too. I am able to see LAFF. Thanks.

**Comment by spotanjo3** [comment]
Where is Laff m3u8 link ? Thanks.

**Comment by LaneSh4d0w** [comment]
We do not divulgate the mybtv links for a reason, please refrain from doing so.
