### ISSUE TITLE
Add: Nvision

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#6079]
### Channel Name

NVision

### Country

India

### Language

Malayalam

### Website

From App

### Stream URL

http://live.singamcloud.in:1935/nvision/nvision/chunklist_w931520852.m3u8

**Comment by LaneSh4d0w** [comment]
Valid.

Adaptive : http://live.singamcloud.in:1935/nvision/nvision/playlist.m3u8
