### ISSUE TITLE
Add: Vision Channel

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#6080]
### Channel Name

Vision Channel

### Country

India

### Language

Malayalam

### Website

From App

### Stream URL

http://stream.singamcloud.in:1935/visionchannel/visionchannel/chunklist_w1828785084.m3u8

**Comment by LaneSh4d0w** [comment]
Not 24/7

Adaptive : http://stream.singamcloud.in:1935/visionchannel/visionchannel/playlist.m3u8

**Comment by freearhey** [comment]
<img width="755" alt="image" src="https://user-images.githubusercontent.com/7253922/159008634-d7e4516a-f816-472b-b2a8-6c71303797dc.png">
