### ISSUE TITLE
Fix: 30 seconds viewing cutoff 

### ISSUE THREAD

**Issue by bzhdudu** [iptv-org/iptv#6081]
### Describe your issue

Hello
I have a problem with the M6 channel (720p) [Not 24/7], it cuts out after 30sec viewing.
http://flusonic-4.platinum-tv.com/M6/mono.m3u8?token=test
Do you have a solution?
Thanks for your work!
Thanking you!

**Comment by LaneSh4d0w** [comment]
Please make a proper "broken stream" issue instead of adding it as a bug. The "bug" issue report is only made for issues in the scripts of this repo, not for streams that cut off after X.
