### ISSUE TITLE
Add: Swantham Channel

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#6090]
### Channel Name

Swantham Channel

### Country

India

### Language

Malayalam

### Website

Playstore App

### Stream URL

http://125.99.241.180:1935/SWANTHAM/live/chunklist_w814322637.m3u8

### Notes

https://images.app.goo.gl/DArSBFBDh1Vcyv327

**Comment by Sphinxroot** [comment]
https://github.com/iptv-org/iptv/blob/master/channels/in.m3u  already in the list at line 646
