### ISSUE TITLE
Replace: Darshana TV 

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#6093]
### Channel Name

Darshana TV

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://streaming37.worldbbtv.com/hls/darshana.m3u8

### Broken Link

https://streaming37.worldbbtv.com/hls/darshana.m3u8

### Possible Replacement

https://www.yupptv.com/channels/darshanatv/live

**Comment by Manipulativemachan** [comment]
https://neestream.com/details/326

**Comment by Manipulativemachan** [comment]
@freearhey @LaneSh4d0w Can you guys get  a link from the above the website?

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/552de94eed297776b2e5a49a006e5503533f56e7/streams/in.m3u#L140-L141

<img width="640" alt="image" src="https://user-images.githubusercontent.com/7253922/159469040-0a4a2739-620a-4c19-b536-092c5be7b3fe.png">
