### ISSUE TITLE
Add: Vismaya News

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#6094]
### Channel Name

Vismaya News

### Country

India

### Language

Malayalam

### Website

https://www.vismayanews.in/

### Stream URL

http://live.singamcloud.in:1935/vismayanews/vismayanews/playlist.m3u8

**Comment by Sphinxroot** [comment]
https://github.com/iptv-org/iptv/blob/master/channels/in.m3u  already in the list at line  684
