### ISSUE TITLE
Add: Canal Antigua

### ISSUE THREAD

**Issue by Toei79** [iptv-org/iptv#6098]
### Channel Name

antigua tv

### Country

antigua

### Language

espanol

### Website

https://canalantigua.tv/

### Stream URL

https://streannlive-lh.akamaihd.net/i/canalantigua_1@429984/index_1_av-p.m3u8?sd=10&dw=3600&set-segment-duration=smoothest&rebase=on&hdntl=exp=1642444043~acl=*~data=hdntl~hmac=0b626eca8ffbb5998aaccdeac555e1d9ddcc468138af56c1ad56c3f9519ad66d

### Notes

its expire links every 10 minutes, i try streamlink without success

**Comment by Sphinxroot** [comment]
https://live.canalantigua.tv/CanalAntigua/myStream/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
http://ott.streann.com:8080/loadbalancer/services/public/channels/61aa4411e4b01dae72214ae5/playlist.m3u8 ?

**Comment by Toei79** [comment]
first one works , lane one not, 

thank you guys!
