### ISSUE TITLE
Add: EXTINF or M3U8 link for NewsNation U.S and Investigation Discovery Canada. Please Help! Unable to find links for these channels.  

### ISSUE THREAD

**Issue by JJincTV** [iptv-org/iptv#6116]
### Channel Name

NewsNation U.S and Investigation Discovery Canada 

### Country

Chicago for NewsNation formerly WGN America 

### Language

English 

### Website

no link 

### Notes

24/7

**Comment by Dum4G** [comment]
Please read our issue reporting guidelines https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#issue-reporting-guidelines

Speaking of Discovery owned channels they're banned from being in this playlist due to DMCA notice we have received from the channel owners
