### ISSUE TITLE
Add: Digi TV

### ISSUE THREAD

**Issue by benevenstanciano** [iptv-org/iptv#6118]
### Channel Name

Digi TV

### Country

United States

### Language

English

### Website

https://www.watchdigitv.com/watch-live

### Notes

Not geo-locked

**Comment by Central302** [comment]
[To Do]Source Using amagi tv Domain.

**Comment by Central302** [comment]
https://amg01443-netxholdingsllc-digitv200-ono-zzfy4.amagi.tv/playlist.m3u8
