### ISSUE TITLE
WSNS Noticias En Vivo

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#6126]
### Channel Name

WSNS Noticias En Vivo

### Country

USA-Chicago,IL

### Language

Spanish

### Website

https://www.telemundochicago.com/noticias/local/en-vivo-noticiero-telemundo-chicago-2/14818/

### Stream URL

https://wmaqlive-f.akamaihd.net/i/CHICAGO_STREAM4@24420/master.m3u8

### Notes

I Wonder Why Link Shows Even Normal Program. (Yes, Stream Should Only Local News)
[6am CT, Stream Shows "Hoy Dia", Network's Morning News]
![WSNSProod](https://user-images.githubusercontent.com/86145713/150133876-3010c78c-9228-4607-bfbf-021d14ff8456.PNG)

**Comment by LaneSh4d0w** [comment]
Telemundo WSNS, working in Romania

**Comment by what-a** [comment]
Stream works in VLC and IPTVnator in Windows 10 and Linux (from California).
Is this stream really the same an OTA (over the air) feed of Telemundo Chicago IL (WSNS-TV)?  I tried to confirm via EPG program listings but could not get a programing match. However, Spanish is not my language so I'll happily defer to what others determine.

**Comment by Central302** [comment]
@what-a No, Stream Should only Local News (Same to NBC Station's News Stream), I Still Wondering that Stream Showing Non-News Program.

**Comment by Central302** [comment]
[Confirmed] [Not 24/7]
