### ISSUE TITLE
Add: Contacto Bolivia

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#6129]
### Channel Name

Contacto Bolivia

### Country

Bolivia

### Language

Spanish

### Website

https://www.contactobolivia.com.bo/

### Stream URL

N/A

### Notes

Stream tokenized

**Comment by LaneSh4d0w** [comment]
Link would be https://ott.streann.com/loadbalancer/services/public/channels/5b8f018e2cdc0352b8e21aee/playlist.m3u8 with referrer to https://www.contactobolivia.com.bo/

or http://free.fullspeed.tv/iptv-query?streaming-ip=https://ott.streann.com/streaming/player.html?U2FsdGVkX18xEE5MKkmNvZA0H0sjfy6UiPdxPUfaIWBX1PHckPjx/EfePuAyi2ibo44K61WVNiELi4891ke7MedI20vCnLtKDkf9ETK1UL509203Zhxzwi3zMxrxDUkDEoyvouQ9cCSfyTMPNgHhXncgmkijxuT69+TDkXYhYVVKZbM7KZ14vtStA8j54y+YhXJ2C/j/kNtA3ZLSUIHCi1yGoe5XYTF6qqY97RI7pWOo/bNkVzi7kqRlp7XXTNUOpRfuunMJU1MSTMlKPane0PenWpzFDDhA7yA1pJrpno7TUB11/ODETb6fmGKe6FfNHj76w5w7QKzyyLgV8iZ25w==

**Comment by dct-infra** [comment]
Hey,
Let me look into this i'll get back to you

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w  For testing purposes, can you give me a stream url to test with?

Link above, if it works correctly the Streann iframe should be catched out and give a link.

**Comment by dct-infra** [comment]
Throws a 403
Try it on your end.

**Comment by dct-infra** [comment]
Have you seen the streann link on the page above? It doesn't seem to be valid for our use case...
Modified anyways, try it on your end and let me know.

**Comment by LaneSh4d0w** [comment]
Link redirection works, certainly is referrer-locked.

**Comment by LaneSh4d0w** [comment]
![image](https://user-images.githubusercontent.com/30985701/150381966-94c91a5b-3e00-412d-84fe-10c31a3b4543.png)

**Comment by LaneSh4d0w** [comment]
Indeed, doesn't seem to work on my side. Gives 403 Forbidden.

**Comment by LaneSh4d0w** [comment]
https://streannlivecontactobolivia.cachefly.net/contactobolivia1/contactobolivia1/playlist.m3u8
