### ISSUE TITLE
Replace: Latina TV

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#6130]
### Channel Name

Latina TV

### What happened to the stream?

Don't playing

### Playlist

https://iptv-org.github.io/iptv/countries/pe.m3u

### Broken Link

https://mdstrm.com/live-stream-playlist/5ce7109c7398b977dc0744cd.m3u8

### Possible Replacement

N/A

### Notes

Error from VLC: Failed to create demuxer (nil) Unknown

Official website: https://www.latina.pe/tvenvivo

**Comment by LaneSh4d0w** [comment]
In the Peruvian Latina website that's the one I have, so I don't understand why it doesn't work. Maybe issues in their side.

**Comment by sguinetti** [comment]
Yes, it does not work beyond the IPTV client. The same happens with Exitosa (which I will also report).

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/a4c2ca1dd8142efd17cd8f2a6f82bf2bfb46691c/streams/pe.m3u#L176-L177

**Comment by LaneSh4d0w** [comment]
Does it work if put via free.fullspeed.tv ? They've did a MDSTRM plugin.

**Comment by AntiPontifex** [comment]
Dead link: please close.
