### ISSUE TITLE
Add: TV Max

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#6151]
### Channel Name

TV Max

### Channel ID

TVMax.pa

### Country

Panama

### Language

Spanish

### Website

https://www.tvnpass.com/home

### Stream URL

https://bcovlive-a.akamaihd.net/a2e5e035037742ff8fd4bae79de16ad4/us-east-1/6058004209001/profile_1/chunklist_dvr.m3u8

**Comment by LaneSh4d0w** [comment]
https://bcovlive-a.akamaihd.net/a2e5e035037742ff8fd4bae79de16ad4/us-east-1/6058004209001/playlist_dvr.m3u8

**Comment by freearhey** [comment]
<img width="752" alt="image" src="https://user-images.githubusercontent.com/7253922/159007259-f937cef8-956c-4a27-8f44-0c91c050ba08.png">

**Comment by LaneSh4d0w** [comment]
Now https://bcovlive-a.akamaihd.net/0ba32a03db4349fd84387629e5fa8eb8/us-west-2/6058004209001/f726ba979e3d4ef88edaa486960eca2c/playlist_dvr_ssaiM.m3u8

**Comment by LaneSh4d0w** [comment]
https://ott.streann.com/web/services/external/season/channel-details/61295797e4b09f380655661d?web=true&r=5b749eab2cdc3a9d7757d2c5 You could use this with origin https://www.tvnpass.com to get stream data.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/pa.m3u#L22-L23
