### ISSUE TITLE
Magic TV

### ISSUE THREAD

**Issue by JohnyGR22** [iptv-org/iptv#6181]
### Channel Name

Magic TV (greek music)

### Country

Greece

### Language

Greek

### Website

https://greektv.org/movies/magic-music-tv-greece/

### Stream URL

https://itv.streams.ovh/magictv/magictv/playlist.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1d5ac2cfd591466086b3f97fc403163e45b16a74/streams/gr.m3u#L124-L125
