### ISSUE TITLE
Add: Mad TV 

### ISSUE THREAD

**Issue by JohnyGR22** [iptv-org/iptv#6182]
### Channel Name

MAD TV (geoblock)

### Channel ID

MadTV.gr

### Country

Greece

### Language

Greek

### Website

mad.tv

### Stream URL

 https://youtu.be/lG7cXqONBHg

**Comment by what-a** [comment]
![image](https://user-images.githubusercontent.com/88639906/151689638-34073949-ecf0-423d-b1e2-f7ec8676cf7b.png)

**Comment by JohnyGR22** [comment]
Stream URL updated

**Comment by freearhey** [comment]
https://ythls.onrender.com/channel/UCs3cho4vcDuCze0tk3W9iVQ.m3u8
<img width="788" alt="image" src="https://user-images.githubusercontent.com/7253922/233876200-13b3bf13-caa4-43f1-b3bc-9b8af8cf09e3.png">
