### ISSUE TITLE
Replace: Telepetróleo

### ISSUE THREAD

**Issue by dcuervog92** [iptv-org/iptv#6187]
### Channel Name

Telepetróleo

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://iptv-org.github.io/iptv/countries/co.m3u

### Broken Link

https://iptv-all.lanesh4d0w.repl.co/colombia/telepetroleo.m3u8

### Notes

This channel and Enlace Television, are not working anymore. Any solution for that?

**Comment by LaneSh4d0w** [comment]
They both need to be scraped from the teveo.co scripts to get them.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/a4c2ca1dd8142efd17cd8f2a6f82bf2bfb46691c/streams/co.m3u#L131-L132

**Comment by LaneSh4d0w** [comment]
Now can be put with free.fullspeed.tv, i've managed to make the correct fixes it seems, dct's streamlink source is now aligned with mine.
