### ISSUE TITLE
C8

### ISSUE THREAD

**Issue by vartaxe** [iptv-org/iptv#6191]
### Channel Name

C8

### Country

France

### Language

French

### Website

www.c8.fr

### Notes

https://www.canalplus.com/chaines/c8

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-id="C8.fr" tvg-country="FR" tvg-language="French" tvg-logo="https://i.imgur.com/C4ApWGr.jpg" group-title="General",C8
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x5gv5rr

fullspeed service seem down

**Comment by what-a** [comment]
> #EXTINF:-1 tvg-id="C8.fr" tvg-country="FR" tvg-language="French" tvg-logo="https://i.imgur.com/C4ApWGr.jpg" group-title="General",C8 http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x5gv5rr
> 
> fullspeed service seem down

For me, it plays for ~5 seconds and then rebuffers. Over and over.

**Comment by vartaxe** [comment]
That link seems to be working for me
