### ISSUE TITLE
Replace: This TV (network)

### ISSUE THREAD

**Issue by gatewayqw** [iptv-org/iptv#6194]
### Channel Name

This TV

### What happened to the stream?

It is stuck at a single frame/the same segment

### Playlist

https://github.com/iptv-org/iptv/blob/master/channels/us.m3u

### Broken Link

https://cdn.igocast.com/channel11_hls/channel11_master.m3u8

### Possible Replacement

Decided to do it myself. https://myiptvplayer.xyz/btv/la.php?channel=THISTV
Credit goes to @yims7

### Notes

Stuck on single frame for probably months or weeks. It seems iGoCast has silently shutdown as their website does not contain live channels, even with location spoofing as Kansas City. It's best to remove the channel from the playlist.

**Comment by spotanjo3** [comment]
My favorite channel. Frozen.

**Comment by Central302** [comment]
All Channels from This Domain are frozen.

**Comment by gatewayqw** [comment]
> All Channels from This Domain are frozen.

Because iGoCast seems to be shutdown. Their app is removed from their respective app stores (except for Amazon) and no channels are found on the site even with location spoofing as Kansas City. What a weird way to go silent.

**Comment by spotanjo3** [comment]
Have it been fixed?

**Comment by gatewayqw** [comment]
> 

Yes. The replacement so far is https://gatewayqw.tk/btv/la.php?channel=THISTV
It's hosted on a free web host using a [LocalBTV PHP script](https://github.com/iptv-org/iptv/discussions/5296) by @yims7.

**Comment by mememe0142** [comment]
NOT Thistv!  it is ARTS channel:   https://myiptvplayer.xyz/btv/la.php?channel=THISTV

**Comment by gatewayqw** [comment]
> NOT Thistv! it is ARTS channel: https://myiptvplayer.xyz/btv/la.php?channel=THISTV

I contacted LocalBTV about it and I got no response.
This stream works though: https://myiptvplayer.xyz/btv/ca.php?channel=KGODT3

**Comment by gatewayqw** [comment]
> NOT Thistv! it is ARTS channel: https://myiptvplayer.xyz/btv/la.php?channel=THISTV

It's back to This TV.

**Comment by spotanjo3** [comment]
Great then wait for the link m3u8

**Comment by spotanjo3** [comment]
It is dead.
