### ISSUE TITLE
Zee News Malayalam

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#6200]
### Channel Name

Zee News Malayalam

### Channel ID

ZeeNewsMalayalam.in

### Country

India

### Language

Malayalam

### Website

https://zeenews.india.com/malayalam

### Stream URL

https://zeenews.india.com/malayalam/live-tv/embed

**Comment by Central302** [comment]
[Memo]
https://d1vd9xhq6jlm48.cloudfront.net/out/v1/71fcc57c8fe74c5b938451bc2435a93e/index.m3u8?akes=[Insert Token]

**Comment by LaneSh4d0w** [comment]
https://d1vd9xhq6jlm48.cloudfront.net/out/v1/71fcc57c8fe74c5b938451bc2435a93e/index_2.m3u8 <- Specific quality playlists aren't protected, index however seems to be.

**Comment by Sphinxroot** [comment]
#EXTINF:-1,Zee News Malayalam Adaptative = Token
https://d1vd9xhq6jlm48.cloudfront.net/out/v1/71fcc57c8fe74c5b938451bc2435a93e/index.m3u8

https://english.cdn.zeenews.com/images/logo/zeenewsmalayalam_nav.png

#EXTINF:-1,Zee News Malayalam 720p
https://d1vd9xhq6jlm48.cloudfront.net/out/v1/71fcc57c8fe74c5b938451bc2435a93e/index_4.m3u8
#EXTINF:-1,Zee News Malayalam 480p
https://d1vd9xhq6jlm48.cloudfront.net/out/v1/71fcc57c8fe74c5b938451bc2435a93e/index_3.m3u8
#EXTINF:-1,Zee News Malayalam 360p
https://d1vd9xhq6jlm48.cloudfront.net/out/v1/71fcc57c8fe74c5b938451bc2435a93e/index_2.m3u8
#EXTINF:-1,Zee News Malayalam 240p
https://d1vd9xhq6jlm48.cloudfront.net/out/v1/71fcc57c8fe74c5b938451bc2435a93e/index_1.m3u8

**Comment by what-a** [comment]
Same results from me in California. Adaptive will not work, but the specific quality streams play fine.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/in.m3u#L267-L268
