### ISSUE TITLE
Futura

### ISSUE THREAD

**Issue by Nowadaysix** [iptv-org/iptv#6203]
### Channel Name

Futura

### Country

Brazil

### Language

Portugues

### Website

https://s.videos.globo.com/p3/amp/index.html?videosids=4500346

### Stream URL

https://live-cm-aq-21-39.video.globo.com/d/e/s/hls-futura24ha/playlist.m3u8?h=0411643255836379323368516431694363604070770kBQMV2RIpNUCxBQI5ZZtfA&k=html5&a=A&u=BR~

### Notes

Does anyone know a script that captures a url automatically? Because this token only lasts 24 hours.

**Comment by eltoncomp** [comment]
@Nowadaysix o Futura já está na playlist, porém o link não está funcionando. Esse link da Globo também não funciona.
Futura is already on the playlist, but the link isn't working. This link from Globo doesn't works too.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/198d0527f073c81119ccceaebdede8e79f542028/streams/br.m3u#L47-L48
