### ISSUE TITLE
Multimedios (Canal 6)

### ISSUE THREAD

**Issue by joaquinito2048** [iptv-org/iptv#6205]
### Channel Name

Multimedios (Canal 6)

### Country

México

### Language

Spanish

### Website

https://www.multimedios.com/television

### Notes

M3U8 is the URL-signed protected.

**Comment by Central302** [comment]
https://www.multimedios.com/video/monterrey-tv-en-vivo/v7567 : Mexican IP Only

**Comment by LaneSh4d0w** [comment]
https://github.com/iptv-org/iptv/blob/f7c78da1bb340e15937fe04ce5937618eb9ec29b/channels/mx.m3u#L82-L87
