### ISSUE TITLE
Replace: Nickelodeon East

### ISSUE THREAD

**Issue by jablinskisquare** [iptv-org/iptv#6210]
### Channel Name

Nickelodeon East

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://github.com/iptv-org/iptv/blob/master/channels/us.m3u

### Broken Link

 http://31.220.41.88:8081/live/us-nick.stream/playlist.m3u8

### Possible Replacement

http://sb1000.servegame.org:55050/zWBGGXy87P/349RZBxUEW/3696

**Comment by Central302** [comment]
Xtream-Codes Detected, Xtream-Code Stream Can't Add in Playlist.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/a4c2ca1dd8142efd17cd8f2a6f82bf2bfb46691c/streams/us.m3u#L897-L898

**Comment by freearhey** [comment]
Broken link removed from playlist.
