### ISSUE TITLE
Times Now

### ISSUE THREAD

**Issue by promtp** [iptv-org/iptv#6211]
### Channel Name

Times Now

### Country

India

### Language

English

### Website

https://www.timesnownews.com/live-tv

### Stream URL

https://pubads.g.doubleclick.net/ssai/event/1mR1QUQ3Tg-VuKfiyjwNuA/master.m3u8

### Notes

24x7 English News Channel

**Comment by Central302** [comment]
Link Says 403 Fobidden (ts file redirect)
