### ISSUE TITLE
Times Now Navbharat

### ISSUE THREAD

**Issue by promtp** [iptv-org/iptv#6212]
### Channel Name

Times Now Navbharat

### Country

India

### Language

Hindi

### Website

https://www.timesnownews.com/live-tv/times-now-navbharat

### Stream URL

https://pubads.g.doubleclick.net/ssai/event/nRWQsGoJSzmcErJFgAy67g/master.m3u8

### Notes

24x7 Hindi News Channel

**Comment by Central302** [comment]
[India IP Only]
