### ISSUE TITLE
Mirror Now

### ISSUE THREAD

**Issue by promtp** [iptv-org/iptv#6214]
### Channel Name

Mirror Now

### Country

India

### Language

English

### Website

https://www.timesnownews.com/live-tv/mirror-now

### Stream URL

https://pubads.g.doubleclick.net/ssai/event/DXkHhH2QSnma-HnE3QJqlA/master.m3u8

### Notes

24x7 English News Channel

**Comment by Central302** [comment]
[India IP Only]
