### ISSUE TITLE
ET Now Swadesh

### ISSUE THREAD

**Issue by promtp** [iptv-org/iptv#6215]
### Channel Name

ET Now Swadesh

### Channel ID

ETNowSwadesh.in

### Country

India

### Language

Hindi

### Website

https://www.timesnownews.com/live-tv/et-now-swadesh

### Stream URL

https://pubads.g.doubleclick.net/ssai/event/Pj6A7e21SN64xv6g4sssCA/master.m3u8

### Notes

24x7 Hindi Business News Channel

**Comment by Central302** [comment]
[India IP Only]

**Comment by what-a** [comment]
> https://dai.google.com/linear/hls/pa/event/Pj6A7e21SN64xv6g4sssCA/stream/311d6a87-359e-43f3-b916-fbd0fddf36d7:GRQ/master.m3u8
> 
> Works here in Romania.

Not working for me in California.

**Comment by LaneSh4d0w** [comment]
> > https://dai.google.com/linear/hls/pa/event/Pj6A7e21SN64xv6g4sssCA/stream/311d6a87-359e-43f3-b916-fbd0fddf36d7:GRQ/master.m3u8
> > Works here in Romania.
> 
> Not working for me in California. Perhaps Geo-blocked?

Use the Doubleclick link above, the other one seems that the "GUID-like" part changes

**Comment by what-a** [comment]
Testing in California; The doubleclick link does connect but it stutters and rebuffers too much.

**Comment by freearhey** [comment]
<img width="742" alt="image" src="https://user-images.githubusercontent.com/7253922/159004695-6d1ca616-3d69-4bf1-be6a-2e20f053485c.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/in.m3u#L212-L213
