### ISSUE TITLE
REQUEST: REW TV

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6217]
### Channel Name

REW TV

### Country

USA

### Language

English

### Website

https://rewindtv.com

**Comment by Dum4G** [comment]
https://github.com/iptv-org/iptv/blob/e6392f75d71a9045b4d035cb47b4f48da888d7a1/channels/us_localbtv.m3u#L107-L109

**Comment by what-a** [comment]
Solid as a rock for me...

![image](https://user-images.githubusercontent.com/88639906/151432919-d41539fe-4e0f-4c90-8140-e470baf7ae34.png)

**Comment by spotanjo3** [comment]
Oh I missed that. Thanks!
