### ISSUE TITLE
Replace: Medi 1 TV group

### ISSUE THREAD

**Issue by saidma** [iptv-org/iptv#6220]
### Channel Name

Medi 1 TV Afrique/Arabic/Maghreb

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/countries/ma.m3u 

### Possible Replacement

https://www.medi1tv.ma/fr/live-medi1tv-afrique / https://www.medi1tv.ma/fr/live-medi1tv-arabic / https://www.medi1tv.ma/fr/live-medi1tv-maghreb 

### Notes

I don't know if the m3u8 links can be taken out.  I don't have the tools. Tanks you !

**Comment by Sphinxroot** [comment]
#EXTINF:-1 ,Medi 1 TV Afrique 1080p
https://streaming2.medi1tv.com/live/smil:medi1fr.smil/playlist.m3u8?DVR

#EXTINF:-1 ,Medi 1 TV Maghreb 1080p
https://streaming1.medi1tv.com/live/smil:medi1tv.smil/playlist.m3u8?DVR

#EXTINF:-1 ,Medi 1 TV Arabic 1080p
https://streaming1.medi1tv.com/live/smil:medi1ar.smil/playlist.m3u8?DVR
