### ISSUE TITLE
Replace: 

### ISSUE THREAD

**Issue by cookie10123** [iptv-org/iptv#6226]
### Channel Name

animax japan 720p

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/index.m3u

### Broken Link

http://50.7.74.29:8880/hls/j00026/index.m3u8

### Notes

animax japan was working yesterday but now it won't even load

**Comment by Sphinxroot** [comment]
already requested #6224
