### ISSUE TITLE
REQUEST: ANTENNA TV

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6229]
### Channel Name

Antenna TV

### Country

USA

### Language

English

### Website

https://antennatv.tv/

**Comment by Central302** [comment]
[Note]Same Network Station (WPHL-TV2) Available in mybtv playlist.

**Comment by spotanjo3** [comment]
I don't see it. Can I see it ? My apologies.

**Comment by Central302** [comment]
Please Use in us_mybtv.m3u in Repository
