### ISSUE TITLE
FOX (1080p) [Geo-blocked]

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6231]
### Channel Name

FOX 1080

### What happened to the stream?

It is disappeared from the playlist

### Playlist

http://htv-drm-live-cdn.fptplay.net/CDN-FPT02/FOX-HD-1080p/playlist.m3u8

**Comment by Central302** [comment]
[Note] 403 Forbidden.

**Comment by fotvnetwork** [comment]
This was Fox Asia. Channel ceased operation last year.

**Comment by Central302** [comment]
Thanks. 
[To-Do]Disney LA Will Shutdown in March, 2022.

**Comment by what-a** [comment]
We should close this request, right?

**Comment by spotanjo3** [comment]
Please dont. We need this channel, don't we ?

**Comment by what-a** [comment]
Fox Asia stopped broadcasting:.
https://en.wikipedia.org/wiki/Fox_(Asian_TV_channel)

**Comment by spotanjo3** [comment]
Why closed ? Hope you find FOX English version. Dont want an Asian TV version, thought.

**Comment by what-a** [comment]
@spotanjo3 This Fox channel provided English language programming targeted for countries in Asia. Unfortunately, it no longer broadcasts so there is nothing more that can be done.
