### ISSUE TITLE
MGM HD USA 

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6232]
### Channel Name

MGM

### What happened to the stream?

It is disappeared from the playlist

### Playlist

http://c0.cdn.trinity-tv.net/stream/uq2t763988wmx82xs37vrzrtrvaz686y22jd9gcgvgbhu88g6dntdb82kggx9zgvpvwj5wisyi5mgwwgdqzm7d6xbf7yvctwzvhsu3t57ms3wa4qxwyeuqk3ayrdwx3k2b6cdtnrydx9qa3ezqzea===.m3u8

**Comment by Central302** [comment]
[Note] Ping : Couldn't Reach out to Target Host.

**Comment by MapGuy11** [comment]
Showing Color Bar
![vlcsnap-2022-01-30-13h06m08s287](https://user-images.githubusercontent.com/43685307/151711669-6247e775-5c1a-4e93-87d1-f2790fc36491.png)
s
