### ISSUE TITLE
Add: National Geographic East

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6233]
### Channel Name

National Graphic 

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://livecdn.fptplay.net/foxlive/natgeohd_hls.smil/playlist.m3u8

**Comment by MapGuy11** [comment]
Because the link doesn't work anymore.

**Comment by F640** [comment]
> https://livecdn.fptplay.net/foxlive/natgeohd_hls.smil/playlist.m3u8

https://livecdn.fptplay.net/hda2/natgeohd_hls.smil/chunklist.m3u8
Should work without referrer or referrer set to "https://fpyplay.vn/"
Is this National Geographic East or Asia?

**Comment by spotanjo3** [comment]
Its Asian to me because the closed caption isnt in English. English please?

**Comment by freearhey** [comment]
Closed in favor #5616
