### ISSUE TITLE
Broken Stream: NBC Boston  MA (WBTS-CD1) (720p)

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6234]
### Channel Name

NBC Boston MA

### What happened to the stream?

It is disappeared from the playlist

### Playlist

http://encodercdn1.frontline.ca/encoder183/output/NBC_Boston_720p/playlist.m3u8

**Comment by MapGuy11** [comment]
It's Working:
![vlcsnap-2022-01-29-10h11m34s860](https://user-images.githubusercontent.com/43685307/151666231-fe152208-3fb6-4f3c-9f61-0e1f3c13894c.png)

**Comment by spotanjo3** [comment]
Yes, it's working. I load it with VLC and wait for less than 30 seconds then finally. Its loading. Thanks! Closed!

**Comment by spotanjo3** [comment]
It is not working anymore again.
