### ISSUE TITLE
CNN Portugal

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6243]
### Channel Name

CNN Portugal

### Channel ID

CNNPortugal.pt

### Country

Portugal

### Language

Portuguese

### Website

https://cnnportugal.iol.pt

**Comment by Central302** [comment]
[Note]Did you Mean - "CNN Brazil"?

**Comment by spotanjo3** [comment]
Hello. Actually, no. CNN Portugal. Look at the site above. I went to Portugal and watched MEO. There is CNN Portugal. Not CNN Brazil.

**Comment by Central302** [comment]
Sorry, I Understand.
[To-Do] https://cnnportugal.iol.pt/direto . Working on USA IP.

**Comment by spotanjo3** [comment]
Yes! Add it to Portugal channels, please ? or post here so I can added it to my m38 file.

**Comment by Central302** [comment]
I'll Trying to Dump Later.

**Comment by Smark223** [comment]
https://video-auth2.iol.pt/live_edge/tvi24_abr/edge_servers/tvi24-480p/chunks.m3u8 still works for CNN Portugal. tvi24 rebranded to CNN Portugal, so the stream address may change in future but it works for now,

**Comment by spotanjo3** [comment]
> https://video-auth2.iol.pt/live_edge/tvi24_abr/edge_servers/tvi24-480p/chunks.m3u8 still works for CNN Portugal. tvi24 rebranded to CNN Portugal, so the stream address may change in future but it works for now,

I understand. I hope not. Just test it on my m38 file and it works fine. Thank you!

**Comment by Central302** [comment]
CNN Porutogal Official Stream

https://video-auth4.iol.pt/live_cnn/live_cnn/playlist.m3u8&wmsAuthSign=

wmsAuthSign = Token.

**Comment by what-a** [comment]
> or https://video-auth2.iol.pt/live_edge/tvi24_abr/edge_servers/tvi24-480p/playlist.m3u8 (Adaptive Version of @Smark223 's Link)

Works for me here in California. Tested fine under Windows 10 and Linux.

**Comment by LaneSh4d0w** [comment]
Haven't I already added that one some time ago ?

**Comment by Central302** [comment]
Sorry, Close The Issuse. (Already added.)

**Comment by spotanjo3** [comment]
Its dead

**Comment by LaneSh4d0w** [comment]
Making a streamlink workaround.

**Comment by spotanjo3** [comment]
I am not sure I understand. What do you mean ? ^_^;

**Comment by LaneSh4d0w** [comment]
> I am not sure I understand. What do you mean ? ^_^;

I'll add a workaround for streamlink, i'll give it to @dct-infra and it should normally be available for free.fullspeed.tv, meaning you'll get access to it, like in the way browsers do.

**Comment by spotanjo3** [comment]
Oh okay. Thank you kindly.

**Comment by spotanjo3** [comment]
CNN Portugal link isn't working anymore.

**Comment by LaneSh4d0w** [comment]
It seems they've cut the official stream for an alternate stream retransmitting war videos : https://video-auth8.iol.pt/ott1abr/Emissaoalt3876-popin/chunks.m3u8

**Comment by spotanjo3** [comment]
First link is poor quality. The 2nd link is good. Thanks.

Third link is forbidden link.

**Comment by spotanjo3** [comment]
https://video-auth8.iol.pt/ott1abr/Emissaoalt3876/ott1abr/Emissaoalt3876-3/chunks.m3u8 works fine but there is no CNN PORTUGAL ICON on the left.

**Comment by freearhey** [comment]
Closed in favor of #9524
