### ISSUE TITLE
Eleven Sport 1,2,3 

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6246]
### Channel Name

Eleven Sport

### Country

Portugal

### Language

Portuguese

### Website

https://aderir.elevensports.pt

**Comment by LaneSh4d0w** [comment]
Blacklisted, cannot be added.

https://github.com/iptv-org/iptv/blob/7a599c62d606ecea45aaf792436b661a8eb99f35/scripts/data/blocklist.json#L183-L186
