### ISSUE TITLE
Replace: SIC Noticias [Geo-blocked] 

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6247]
### Channel Name

SIC Noticias

### What happened to the stream?

Not loading

### Playlist

http://live.impresa.pt/live/sicnot/sicnot.m3u8

**Comment by LaneSh4d0w** [comment]
Link would be https://rr.cdnlab.vodafone.pt/shls_VTV_LIVE/LIVE$13/6.m3u8?start=LIVE&end=END&device=HLS_TMP_TST but it 404s

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/a4c2ca1dd8142efd17cd8f2a6f82bf2bfb46691c/streams/pt.m3u#L65-L66

**Comment by spotanjo3** [comment]
Good work but... Unfortunately, not working. And many of t hem included Sport TV doesn't worked. Can you double check them ? VLC Player here doesn't works.

**Comment by LaneSh4d0w** [comment]
https://sic.live.impresa.pt/sic540p.m3u8
https://sic.live.impresa.pt/sicnoticias540p.m3u8

**Comment by spotanjo3** [comment]
Grrr. Its not working as well.

**Comment by LaneSh4d0w** [comment]
http://93.152.174.144:4000/play/sicnotiacias/index.m3u8

**Comment by freearhey** [comment]
https://sic.live.impresa.pt/sic540p.m3u8 (offline)
<img width="302" alt="image" src="https://user-images.githubusercontent.com/7253922/232223608-59e805d6-8fd5-4a8c-b42c-7f1f6ebc9478.png">

http://93.152.174.144:4000/play/sicnotiacias/index.m3u8 (offline)
<img width="400" alt="image" src="https://user-images.githubusercontent.com/7253922/232223651-a49af3bc-7a2b-4b2c-9cc5-4eea04b7867a.png">

Broken link removed from playlist.
