### ISSUE TITLE
getTV 

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6248]
### Channel Name

getV

### Country

USA

### Language

English

### Website

https://www.get.tv

**Comment by MapGuy11** [comment]
Does this work? https://v-px.theus6tv.tk/hls/13.3/playlist.m3u8 

If so @what-a create a PR and submit it.

**Comment by spotanjo3** [comment]
Yes, it does work on my m38 list. Just added and thanks.

**Comment by MapGuy11** [comment]
> Yes, it does work on my m38 list. Just added and thanks.
> 
> Is it 480p ?

Yes it is 480p

**Comment by what-a** [comment]
> https://v-px.theus6tv.tk/hls/13.3/playlist.m3u8

I'm on it.
