### ISSUE TITLE
Fix: url-tvg blank

### ISSUE THREAD

**Issue by illie0** [iptv-org/iptv#6251]
### Describe your issue

All of the combined m3u files are missing links to the EPG content
#EXTM3U x-tvg-url=""

**Comment by illie0** [comment]
Any additional details I can provide to help with this?

Like https://iptv-org.github.io/iptv/countries/jp.m3u
used to contain:
#EXTM3U url-tvg="https://iptv-org.github.io/epg/guides/ae/osn.com.epg.xml,https://iptv-org.github.io/epg/guides/id/mncvision.id.epg.xml,https://iptv-org.github.io/epg/guides/us/directv.com.epg.xml"
But now has:
#EXTM3U x-tvg-url=""

So it has both changed from url-tvg to x-tvg-url but also empty.

**Comment by freearhey** [comment]
Thanks! I'll try to fix it as soon as I have some free time.
