### ISSUE TITLE
Replace: 2m Marroc

### ISSUE THREAD

**Issue by hamzawarudo** [iptv-org/iptv#6252]
### Channel Name

2m Marroc

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/countries/ma.m3u

### Broken Link

https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/2m_monde/hls_video_ts/2m_monde.m3u8

**Comment by LaneSh4d0w** [comment]
https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/2m_monde/hls_video_ts_hy217612tge1f21j83/2m_monde.m3u8
