### ISSUE TITLE
The CW (issue w/closed captions)

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6257]
### Channel Name

The CW

### Country

USA

### Language

English

### Website

https://www.cwtv.com

### Notes

#EXTINF:0,The CW Tallahassee FL (WTLF1) (720p) [Not 24/7] https://5e6cea03e25b6.streamlock.net/live/WTLHCW.stream/playlist.m3u8 doesn't have a closed captioning. Can you find other one ? I found one Is New York in your m3u list but it doesn't worked properly.

**Comment by what-a** [comment]
There is cc for the Tallahassee stream. However, like all of the CW affiliates, the cc is not 24/7. Are you able to see cc during prime time programming? I am...
![image](https://user-images.githubusercontent.com/88639906/151733470-c46281ca-dafb-4387-aca4-d4c6a0350ed7.png)

**Comment by Central302** [comment]
[Note] WPIX is Stable on My Side.

**Comment by spotanjo3** [comment]
Yeah, it is not 24 hours closed captioning, thought but on my tv it is closed captioning 24 hours. Maybe find other The CW according to site with zip code for better one ?

**Comment by Central302** [comment]
WPIX-CC is Currentry Works (Airing WPIX's Local News)
![WPIX-CC](https://user-images.githubusercontent.com/86145713/151797571-f673eedb-398c-42b4-8420-fda077e55dd1.PNG)

**Comment by spotanjo3** [comment]
It is not The CW. I understand that WPIX is New York CBS TV

**Comment by Central302** [comment]
[Note] WPIX is CW affiliate in New York.
https://www.cwtv.com/page/stations/ [US IP] or
https://en.wikipedia.org/wiki/List_of_The_CW_affiliates_(table)

**Comment by spotanjo3** [comment]
Oh... Interesting. I dont know NYC zip code lol. I am not around NYC, thought. :D My area is always have the logo "THE CW" on the bottom right.

**Comment by Central302** [comment]
Always CW Logo? You Mentioning CBS Owned Station of "CW" Likely WUPA(Atlanta's CW, Owned by CBS)
https://cwatlanta.cbslocal.com/

**Comment by spotanjo3** [comment]
Yep.. Here as an example from Florida and not a closed captioning, mind you because of not 24/7:
<img width="1278" alt="Screen Shot 2022-01-31 at 8 15 22 AM" src="https://user-images.githubusercontent.com/16481778/151800013-3066d01a-c05f-43b7-9a30-4904684d5ce3.png">

**Comment by spotanjo3** [comment]
I am watching tv right now in different state also showing THE CW Logo. Not like in New. York.

**Comment by Central302** [comment]
Tallahassee stream Showing CC Now. (Diffrent Station, But Same Network)
![WTLFSub](https://user-images.githubusercontent.com/86145713/151800448-93da9dc0-3851-4e5d-aa45-aad9078ac650.PNG)

**Comment by spotanjo3** [comment]
VLC ? I am using VLC and still didnt show CC on this one, thought. @_@

**Comment by spotanjo3** [comment]
Mine is showing WTLF1

**Comment by Central302** [comment]
[Memo] Please Check "Subtitle" - "Sub Track" - "Closed Caption 1"

**Comment by spotanjo3** [comment]
Thats what I am doing. I am not newbie, lol. Any closed captioning working fine on my m38u and this one didnt! Mine is **WTLF1** from Florida.

**Comment by Central302** [comment]
@what-a Closed Captioning Works on iPhone's Safari.
It's confused.

**Comment by spotanjo3** [comment]
WTLF1??

**Comment by Central302** [comment]
Yes. WTLF1.

**Comment by spotanjo3** [comment]
Give me the correct code so I can added and see what's happening ? See mine:

<img width="586" alt="Screen Shot 2022-01-31 at 8 59 10 AM" src="https://user-images.githubusercontent.com/16481778/151806828-37bc8bee-50d3-4694-884c-23e2e0900998.png">

**Comment by spotanjo3** [comment]
#EXTINF:0,The CW Tallahassee FL (WTLF1) (720p) [Not 24/7]
https://5e6cea03e25b6.streamlock.net/live/WTLHCW.stream/playlist.m3u8

**Comment by spotanjo3** [comment]
> Tallahassee stream Showing CC Now.
> ![WTLFSub](https://user-images.githubusercontent.com/86145713/151800448-93da9dc0-3851-4e5d-aa45-aad9078ac650.PNG)
> WJAC4 (Same Network) Showing Too.
> ![WJAC-CC](https://user-images.githubusercontent.com/86145713/151801038-662ef2d7-a67c-49ec-9bfb-512bf7c7b214.PNG)

What player do you use ? All I know is VLC for this kind of file.

**Comment by what-a** [comment]
> What player do you use ? All I know is VLC for this kind of file.

I'm using IPTVnator, VLC and Astronica. There are various apps available:
https://github.com/iptv-org/awesome-iptv#apps

**Comment by spotanjo3** [comment]
Thank you.
I test IPTVnator and Closed Captioning works fine. 
VLC doesn't as you seen above.

**Comment by what-a** [comment]
Excellent. I'm closing the issue.
