### ISSUE TITLE
Replace: Canal 5

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#6258]
### Channel Name

Canal 5

### Channel ID

Canal5.mx

### Country

México

### Language

Spanish

### Website

https://www.televisa.com/canal5/

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f4fe53831a7a46511d070f91cdcbb53464a32cbd/streams/mx.m3u#L10-L11

**Comment by AntiPontifex** [comment]
Link still broken as of 11/24/22

**Comment by freearhey** [comment]
Closed in favor of #9607
