### ISSUE TITLE
TV Land

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6259]
### Channel Name

TV Land

### Country

USA

### Language

English

### Website

https://www.tvland.com

**Comment by what-a** [comment]
I believe I have a working stream.

Suggested logo:
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-states/tv-land-us.png

**Comment by spotanjo3** [comment]
TV Land is available ? Which?

**Comment by spotanjo3** [comment]
Can you check if it is closed captioning ? I tried VLC, nope. And iptvnator, nope. Test them on macOS.

**Comment by what-a** [comment]
Same here. No closed captions.

**Comment by spotanjo3** [comment]
Maybe find other state with TV Land ? Here with TV Land having a closed caption just fine. 

According to TVLAND:

Are TV Land shows closed-captioned? All of our on-air programming is closed-captioned. On digital platforms, all full episodes and movies are captioned.

**Comment by spotanjo3** [comment]
Watch tv. Look! 
![0](https://user-images.githubusercontent.com/16481778/152625786-970afd5c-36d6-45a0-a6e9-d17533f9a90e.jpeg)

**Comment by what-a** [comment]
If I find another stream with cc, I will add it.
