### ISSUE TITLE
Multimedios Costa Rica (Canal 8)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6268]
### Channel Name

Multimedios/Telediario (Canal 8)

### Country

Costa Rica

### Language

Spanish

### Website

https://www.google.com/amp/s/amp.telediario.cr/television

### Stream URL

https://mdstrm.com/live-stream-playlist/5a7b1e63a8da282c34d65445.m3u8

**Comment by what-a** [comment]
Stream is 720p. Working fine here in California.
Logo: 
https://static.wikia.nocookie.net/logopedia/images/8/87/Canal_8_Costa_Rica.svg/revision/latest/scale-to-width-down/512?cb=20210312052039.png

**Comment by what-a** [comment]
Stream already exists at IPTV-org:

![image](https://user-images.githubusercontent.com/88639906/151859750-50b45777-48d1-49bc-9a77-5f4ec9c3fded.png)
