### ISSUE TITLE
Add: Omega TV Canal 40

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#6270]
### Channel Name

Omega TV Canal 40

### Country

Honduras

### Language

Spanish

### Website

https://omegaturadio.com/

### Stream URL

https://5caf24a595d94.streamlock.net:1937/8142/8142/chunklist_w1754720314.m3u8

**Comment by what-a** [comment]
Already exists:
![image](https://user-images.githubusercontent.com/88639906/151900844-77754a7e-a190-4022-be4d-823832f4b2df.png)
