### ISSUE TITLE
Taber TV

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#6272]
### Channel Name

Taber TV

### Country

El Salvador

### Language

Spanish

### Website

https://tabernaculo.net/tv/

### Stream URL

https://5ca9af4645e15.streamlock.net/tabertv/smil:tabertv.smil/playlist.m3u8

### Notes

Religious Christian Channel 24/7

**Comment by what-a** [comment]
Logo
https://logodix.com/logo/2116064.png
