### ISSUE TITLE
Canal 27

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#6273]
### Channel Name

Canal 27

### Channel ID

Canal27.gt

### Country

Guatemala

### Language

Spanish

### Website

https://www.canal27.org/

### Stream URL

https://dcunilive16-lh.akamaihd.net/i/dclive_1@330503/master.m3u8?hdnea=st=1643677373~exp=1643677493~acl=/i/dclive_1@330503*~hmac=9b431542aa0fc6e73fc3e18df14274f6c44e09aae8c776e91b3bbf5b31e03e8d

**Comment by what-a** [comment]
Link to the stream has expired.

**Comment by AntiPontifex** [comment]
Already on list: please close.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/gt.m3u#L22-L23
