### ISSUE TITLE
Replace: Teletica

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#6274]
### Channel Name

Teletica

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://iptv-org.github.io/iptv/index.country.m3u

### Broken Link

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x29e3wg

### Possible Replacement

https://stream-02.nyc.dailymotion.com/sec(jlR0lJnpjfic8bXdlVDO54NpxP2mlFtSrDnl8WJarbE)/dm/3/x29e3wg/s/live-1.m3u8

**Comment by what-a** [comment]
Back up and running:
![image](https://user-images.githubusercontent.com/88639906/151905133-832ff17f-050d-4c58-b2f0-9d3f89618f1c.png)
