### ISSUE TITLE
Discovery Asia

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6275]
### Channel Name

Discovery Asia

### Country

Singapore

### Language

English

### Website

http://discoverychannelasia.com/

### Stream URL

https://vips-livecdn.fptplay.net/hda2/discoveryasia_vhls.smil/chunklist_b5000000.m3u8

**Comment by what-a** [comment]
Unfortunately, IPTV-org is blocked from adding that channel.

![image](https://user-images.githubusercontent.com/88639906/151905508-1619c93a-365d-48da-9514-3cba4efe885a.png)
