### ISSUE TITLE
Add: DAZN F1

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6276]
### Channel Name

DAZN F1

### Country

Spain

### Language

Spanish

### Website

https://www.movistar.es/

### Stream URL

http://66.70.176.103:8081/SPAIN%7CMOVISTARF1/SPAIN%7CMOVISTARF1/playlist.m3u8

**Comment by Central302** [comment]
This Channel has been Blocklist(You Can't add This Channel Due to Avoid DMCA)
Reffer  : https://github.com/iptv-org/iptv/blob/master/scripts/data/blocklist.json
