### ISSUE TITLE
Golden Plus+

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6279]
### Channel Name

Golden Plus+

### Country

Mexico

### Language

Spanish

### Website

http://televisa-networks.com/portfolio-posts/golden

### Stream URL

http://51.79.18.128:8081/LATINO%7CGOLDENPLUS/LATINO%7CGOLDENPLUS/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
What's interesting is that the naming does take the "Xtream" style in the names, but isn't an Xtream-Codes server.

**Comment by R4IN2007** [comment]
The Stream m3u8 Link Doesn't Work Anymore So Here's A Replacement Link
http://181.65.154.170:8000/play/a053/index.m3u8
