### ISSUE TITLE
Museum TV FAST

### ISSUE THREAD

**Issue by erginozcan1993** [iptv-org/iptv#6283]
### Channel Name

Museum TV FAST

### Country

France

### Language

English

### Website

http://www.plex.tv

**Comment by what-a** [comment]
https://www.museumtv.art/en/

**Comment by erginozcan1993** [comment]
Hello again. Museum TV is Pay-TV. Although, specially in Europe, Museum TV FAST is available on Samsung TV Plus in selected markets and Plex on throughout Europe.

**Comment by what-a** [comment]
From Samsung TV Plus France:
https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg01492-secomsasmediart-museumtv-fr-samsungfr/playlist.m3u8

**Comment by erginozcan1993** [comment]
This stream is geoblocked. Only available to watching in France.

**Comment by what-a** [comment]
> This stream is geoblocked. Only available to watching in France.

It is playing fine here in California.

**Comment by erginozcan1993** [comment]
> @erginozcan1993 Do any of these work for you?
> 
> Samsung TV Plus Italy https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg01492-secomsasmediart-museumtv-eng-samsungit/playlist.m3u8 Samsung TV Plus Spain https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg01492-secomsasmediart-museumtv-eng-samsungspain/playlist.m3u8 Samsung TV Plus Switzerland https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg01492-secomsasmediart-museumtv-fr-samsungch/playlist.m3u8

None of them. All of these are geoblocking to Turkey.

**Comment by what-a** [comment]
@erginozcan1993 Does this work for you?
Plex Europe 
https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg01492-secomsasmediart-museumtv-en-plex/playlist.m3u8

**Comment by erginozcan1993** [comment]
> @erginozcan1993 Does this work for you? Plex Europe https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg01492-secomsasmediart-museumtv-en-plex/playlist.m3u8

Yes. This works to me fine.

**Comment by what-a** [comment]
> > @erginozcan1993 Does this work for you? Plex Europe https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg01492-secomsasmediart-museumtv-en-plex/playlist.m3u8
> 
> Yes. This works to me fine.

Also works for me in California, and via VPN to Europe. Seems to not be Geo-blocked. 👍
