### ISSUE TITLE
Add: +tdp (Teledeporte)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6284]
### Channel Name

+tdp (Teledeporte)

### Channel ID

Teledeporte.es

### Country

Spain

### Language

Spanish

### Website

https://www.rtve.es/play/videos/directo/canales-lineales/tdp/

### Stream URL

http://91.126.141.13:1935/live/91/1400-def.m3u8

**Comment by LaneSh4d0w** [comment]
alt being on http://91.126.141.13:8089/

**Comment by AntiPontifex** [comment]
Already on list: please close.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/es.m3u#L404-L405
