### ISSUE TITLE
Add: [To-do] WNBC-DT1

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#6286]
### Channel Name

NBC NY WNBC-DT1

### Country

USA, New York

### Language

English

### Website

offical site: https://www.nbcnewyork.com/

### Stream URL

http://38.91.57.12:2082/nbc/tracks-v1a1/mono.m3u8

### Notes

OTA Channel from @R4IN2007 Link

**Comment by R4IN2007** [comment]
ABC NEWS 
http://38.91.57.12:2082/abc/tracks-v1a1/mono.m3u8

**Comment by Central302** [comment]
Already in Playlist. (Official Link)
