### ISSUE TITLE
Add:  NBC NEW YORK 4 (WNBC-DT1)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6292]
### Channel Name

NBC NEW YORK 4

### Country

US

### Language

English

### Website

https://www.nbcnewyork.com

### Stream URL

https://v-ny.mybtv.net/live/548.m3u8

**Comment by Central302** [comment]
Already added to US.Playlist

**Comment by R4IN2007** [comment]
Oh
