### ISSUE TITLE
Add: CBSN SACRAMENTO

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6296]
### Channel Name

CBSN SACRAMENTO

### Country

US

### Language

English

### Website

cbsn.com

### Stream URL

http://dai.google.com/linear/hls/event/e7mp4YVGS7O_e7rqRNjKow/master.m3u8

**Comment by Central302** [comment]
Already in US Playlist.
(Notice That Renamed to CBS NEWS Sacramento).
