### ISSUE TITLE
MTV Lebanon

### ISSUE THREAD

**Issue by mbtrs** [iptv-org/iptv#6299]
### Channel Name

MTV Lebanon

### Country

Lebanon

### Language

Arabic

### Website

https://www.mtv.com.lb/vod/ar/live

### Notes

24/7, hard to track down a free stream

**Comment by mbtrs** [comment]
This website may help get it started: https://www.elahmad.com/tv/watchtv.php?id=mtv_lebanon

**Comment by what-a** [comment]
Let's see how long this works:
https://cllive.itworkscdn.net/mtvlebanonlive/token=nva=1643821400~~dirs=1~~hash=0048b0209f3f62b0077da/mtvlive.smil/playlist.m3u8

**Comment by mbtrs** [comment]
Link doesn't work on VLC or by clicking on it. Is it still working on your end?

**Comment by what-a** [comment]
Nope, the link is now dead. I was afraid of that. It probably requires a fresh token. Need to find a non-tokenized link.

**Comment by Shadizzz** [comment]
Hi guys, any luck with a working stream? Beside the daily token one?

**Comment by mbtrs** [comment]
> Hi guys, any luck with a working stream? Beside the daily token one?

Unfortunately, I haven't found anything else to help further this request. I've been relying on the link I provided above to watch it remotely in the interim.

**Comment by Shadizzz** [comment]
Yes using the elahmad link as well, now it seems LBCI link is having issues since yesterday, anyone has a different working stream?

https://shls-lbci-prod-dub.shahid.net/out/v1/d8cce30036e743318a7f338539689968/index.m3u8

**Comment by freearhey** [comment]
Closed in favor #7276
