### ISSUE TITLE
Add: BT Sport 1

### ISSUE THREAD

**Issue by Smark223** [iptv-org/iptv#6303]
### Channel Name

BT Sport 1

### What happened to the stream?

It is stuck at a single frame/the same segment

### Playlist

https://iptv-org.github.io/iptv/countries/uk.m3u

### Broken Link

https://sport.livedoomovie.com/02_BTSPORTHD_1_720p/chunklist.m3u8

### Notes

Same for BT Sport 2

**Comment by LaneSh4d0w** [comment]
Try https://smart-tv.livedoomovie.com:4431/02_BTSPORTHD_1_720p/chunklist.m3u8

**Comment by Smark223** [comment]
Unfortunately, they're exactly the same. They just replay the same 40 second or so loop from before Christmas.

**Comment by freearhey** [comment]
The channel was removed from the playlist due to claims of rights holders: https://github.com/iptv-org/iptv/issues/6973
