### ISSUE TITLE
NHL Network

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6304]
### Channel Name

NHL NETWORK

### Channel ID

NHLNetwork.us

### Country

US

### Language

English

### Website

https://www.nhl.com/

### Stream URL

http://38.91.57.12:2082/nhl/tracks-v1a1/mono.m3u8

**Comment by what-a** [comment]
I'm getting video but no audio. Seems a problem at the stream provider source. Will test again later today.

**Comment by R4IN2007** [comment]
Ok

**Comment by what-a** [comment]
Resolved IP to DNS (courtesy of LaneSh4d0w):
http://s1.mysportz.tv:2082/nhl/playlist.m3u8

Logo:
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-states/nhl-network-us.png

**Comment by what-a** [comment]
The issue is that AC3 audio is not supported in any browser. This means that for any IPTV player (or IPTV browser add on) that relies upon a browser (e.g. IPTVnator, HLS.js, etc.) the audio will not work. I'm thinking we need to hold out until a link can be found for a stream with audio other than AC3.

**Comment by MapGuy11** [comment]
> The issue is that AC3 audio is not supported in any browser. This means that for any IPTV player (or IPTV browser add on) that relies upon a browser (e.g. IPTVnator, HLS.js, etc.) the audio will not work. I'm thinking we need to hold out until a link can be found for a stream with audio other than AC3.

What they are doing is pulling a cable stream and just transcoding the video to h264 and not the audio to aac. AC3 works on most players so I am surprised it isn't working on yours. But AC3 will never work on the browser that is for sure.

**Comment by DRIV3R-amb** [comment]
is their a stream I can use fro putting in for iptv can I put the two in and nothing they say invalid

**Comment by what-a** [comment]
The steams mentioned in this thread no longer work.

**Comment by AntiPontifex** [comment]
Dead issue: please close.
