### ISSUE TITLE
NFL Network

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6306]
### Channel Name

NFL NETWORK

### Country

US

### Language

English

### Website

https://www.nfl.com/

### Stream URL

http://38.91.57.12:2082/nfl/tracks-v1a1/mono.m3u8

**Comment by what-a** [comment]
Some logo options:
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-states/nfl-network-us.png
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-states/nfl-network-hz-us.png
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-states/nfl-icon-us.png

**Comment by LaneSh4d0w** [comment]
isn't this in the blacklist ?

**Comment by what-a** [comment]
> isn't this in the blacklist ?

I checked but did not find it.
