### ISSUE TITLE
Fox News Channel 

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6308]
### Channel Name

Fox News Channel 

### Country

US

### Language

English

### Website

https://www.peacocktv.com/

### Stream URL

http://38.91.57.12:2082/foxnews/tracks-v1a1/mono.m3u8

### Notes

The WWE,NHL,NFL Channels Are From Peacock

**Comment by what-a** [comment]
Solid 720p stream. Audio works in VLC, but not in IPTVnator. More audio testing is needed...
![image](https://user-images.githubusercontent.com/88639906/152213823-6f522b75-a3f2-4168-bc11-4db05dd07e2c.png)

**Comment by R4IN2007** [comment]
MSNBC
http://38.91.57.12:2082/msnbc/tracks-v1a1/mono.m3u8

CNBC
http://38.91.57.12:2082/CNBC/tracks-v1a1/mono.m3u8

**Comment by what-a** [comment]
Video and audio for MSNBC and CNBC are working perfect! 👍

**Comment by spotanjo3** [comment]
Fox News Channel link is dead.

**Comment by txzpro** [comment]
CNBC link is also dead
