### ISSUE TITLE
Add: Real Madrid TV

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6311]
### Channel Name

Real Madrid TV

### Country

Spain

### Language

Spanish

### Website

https://www.realmadrid.com/en/real-madrid-tv

### Stream URL

http://154.62.74.11:1935/live/realmadridnntv/chunklist_w1062028841.m3u8

**Comment by Central302** [comment]
[Note]1.Tubi Including This Channel [USA IP],Also I'll Do Later.

**Comment by what-a** [comment]
Logo:
https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/179px-Real_Madrid_CF.svg.png

**Comment by R4IN2007** [comment]
New Stream m3u8 Link https://rmtv.akamaized.net/hls/live/2043153/rmtv-es-web/master.m3u8

**Comment by spotanjo3** [comment]
I am looking for an English version since I dont understand spanish.

**Comment by spotanjo3** [comment]
I found this. It's working http://luxtivi.k18.us/realmadrid.m3u8 but no CC (closed captioning or subtitle at all). I think it's speaking English. I don't know.

**Comment by R4IN2007** [comment]
There was a English version it's different from the original, I think
https://rmtv.akamaized.net/hls/live/2043154/rmtv-en-web/master.m3u8

**Comment by BellezaEmporium** [comment]
> There was a English version it's different from the original, I think https://rmtv.akamaized.net/hls/live/2043154/rmtv-en-web/master.m3u8
> 
> Website also changed: https://www.realmadrid.com/en-US/real-madrid-tv

Can confirm this link works, with an US VPN. Otherwise it's geo.

**Comment by spotanjo3** [comment]
This is not a LIVE REAL MADRID. I saw this link and its repeating because Real Madrid vs Barcelona is now live. Is there a live one ?

**Comment by spotanjo3** [comment]
Yeah, I noticed that. No wonder. Thanks for clarifying.

**Comment by Omar9Crds** [comment]
You won't find a better IPTV service than ( **KAVAFLIX . COM** )
