### ISSUE TITLE
The CW Los Angeles CA (KTLA)

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#6313]
### Channel Name

KTLA5

### Country

USA-Los Angels, CA

### Language

English

### Website

[Official Site] https://ktla.com/

### Notes

Sadly, Still Missing on My Side (even canada Server, teleuptv) Will Need For Suppot for Western Feed of CW.

**Comment by LaneSh4d0w** [comment]
https://access.mp.lura.live/anvacks/X8POa4zpGZMmeiq0wqiO8IP5rMqQM9VN?apikey=3hwbSuqqT690uxjNYBktSQpa5ZrpYYR0Iofx7NcJHyA News

**Comment by what-a** [comment]
I do believe MapGuy11 has this in the works as well as The CW Phoenix AZ (KNXV). Just give him some time to work his magic.

**Comment by MapGuy11** [comment]
> I do believe MapGuy11 has this in the works as well as The CW Phoenix AZ (KNXV). Just give him some time to work his magic.

Thank you to all these people who don't understand I am a one-man band and need to juggle work, school, and this!

**Comment by LaneSh4d0w** [comment]
Can confirm, in lists. Got working link, i'll let MapGuy work with the info I gave him.

**Comment by MapGuy11** [comment]
> Can confirm, in lists. Got working link, i'll let MapGuy work with the info I gave him.

Oh, I already knew about it.

**Comment by LaneSh4d0w** [comment]
> > Can confirm, in lists. Got working link, i'll let MapGuy work with the info I gave him.
> 
> Oh, I already knew about it.

Good to know, it works basically everywhere, some issues however on some channels, content not available it says

**Comment by MapGuy11** [comment]
> > > Can confirm, in lists. Got working link, i'll let MapGuy work with the info I gave him.
> > 
> > 
> > Oh, I already knew about it.
> 
> Good to know, it works basically everywhere, some issues however on some channels, content not available it says

Yeah, those are the ones where the channel was removed by the broadcaster and they haven't caught up and fixed it.

**Comment by LaneSh4d0w** [comment]
> > > > Can confirm, in lists. Got working link, i'll let MapGuy work with the info I gave him.
> > > 
> > > 
> > > Oh, I already knew about it.
> > 
> > 
> > Good to know, it works basically everywhere, some issues however on some channels, content not available it says
> 
> Yeah, those are the ones where the channel was removed by the broadcaster and they haven't caught up and fixed it.

Gonna need to rescan I suppose.

**Comment by Central302** [comment]
@MapGuy11 Thank you for Set Up This Channel. That's all for adding All 5 Major OTA Station(NBC,CBS,ABC,FOX,CW) , and Each Coast Feed.
