### ISSUE TITLE
History Channel

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6315]
### Channel Name

History Channel

### Channel ID

HistoryEast.us

### Country

US

### Language

English

### Website

https://www.history.com/

### Stream URL

http://38.91.57.12:2082/history/tracks-v1a1/mono.m3u8

**Comment by what-a** [comment]
Resolved IP to DNS  (courtesy of LaneSh4d0w):
http://s1.mysportz.tv:2082/history/playlist.m3u8

**Comment by chamby90** [comment]
is this really a US stream? I think it might be a Canadian feed (same with the other feeds from this domain)

**Comment by what-a** [comment]
Now everything from that domain seems to be offline.  😒

**Comment by what-a** [comment]
> is this really a US stream? I think it might be a Canadian feed (same with the other feeds from this domain)

Hard to tell regarding the stream, but the provider is in the US:
IP Address Location Information for 38.91.57.12
    City: Ashburn
    State: Virginia
    Country: United States of America
    Postal Code: 20147
    Time Zone: -05:00

**Comment by R4IN2007** [comment]
COZI TV
http://38.91.57.12:2082/cozi/tracks-v1a1/mono.m3u8

**Comment by what-a** [comment]
> COZI TV http://38.91.57.12:2082/cozi/tracks-v1a1/mono.m3u8

Rare to find Cozi in 720p.  I believe Cozi TV is not a cable network. It's a broadcast network, which means this stream must originate from an affiliate local station. So, what is the call sign of this affiliate?

**Comment by freearhey** [comment]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/7253922/159003519-ca5005ed-fdeb-4f41-a71b-2d744cb72420.png">

**Comment by freearhey** [comment]
Closed in favor #6035

**Comment by FindingChannel25** [comment]
How to find National Graphic guys m3u only ?

**Comment by spotanjo3** [comment]
HISTORY CHANNEL is dead.

**Comment by R4IN2007** [comment]
Issue too old 2022

**Comment by spotanjo3** [comment]
I know. Just inform that it was dead. ^_^
