### ISSUE TITLE
NBC Golf Channel

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6317]
### Channel Name

Golf Channel TV

### Country

US

### Language

English

### Website

https://www.nbcsports.com/live/golf

### Stream URL

http://38.91.57.12:2082/golf/tracks-v1a1/mono.m3u8

**Comment by what-a** [comment]
http://s1.mysportz.tv:2082/golf/playlist.m3u8

**Comment by gzxuyongfeng** [comment]
> Resolved IP to DNS (courtesy of LaneSh4d0w): http://s1.mysportz.tv:2082/golf/playlist.m3u8
> 
> Logo: https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-states/nbc-golf-3d-us.png

No redponse

**Comment by what-a** [comment]
All streams from http://s1.mysportz.tv appear dead.
