### ISSUE TITLE
Replace: La Red

### ISSUE THREAD

**Issue by ELProductions** [iptv-org/iptv#6319]
### Channel Name

La Red

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/countries/cl.m3u

### Broken Link

https://unlimited1-cl-movistar.dps.live/lared/lared.smil/playlist.m3u8

### Notes

Error from VLC: failed to open the MRL. Anyone can fix it? Thanks

**Comment by LaneSh4d0w** [comment]
https://unlimited1-us.dps.live/lared/lared.smil/playlist.m3u8

**Comment by freearhey** [comment]
<img width="703" alt="image" src="https://user-images.githubusercontent.com/7253922/159003293-cd29d309-e140-4ee5-81c3-d988b27a98b9.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/552de94eed297776b2e5a49a006e5503533f56e7/streams/cl.m3u#L140-L141

<img width="640" alt="image" src="https://user-images.githubusercontent.com/7253922/159470761-b12feecb-1583-4468-b567-ecdc2762d8f3.png">
