### ISSUE TITLE
 Disney Channel (Canada-English)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6331]
### Channel Name

Disney Channel

### Country

US

### Language

English

### Website

http://38.91.57.12:2082

### Stream URL

http://38.91.57.12:2082/disney/tracks-v1a1/mono.m3u8

**Comment by spotanjo3** [comment]
What resolution is it ? 720p ?

**Comment by what-a** [comment]
> What resolution is it ? 720p ?

Yes, 720p.

**Comment by R4IN2007** [comment]
Yep, its 720p
