### ISSUE TITLE
Remove: Domain *.unreel.me and us_bumblebee.m3u

### ISSUE THREAD

**Issue by peter-powr** [iptv-org/iptv#6345]
### Channel Names

All channels with *.unreel.me domains and Bumblebee.tv feeds.

### DMCA Notice

N/A

### Notes

Please remove all channels from channels/us_bumblebee.m3u and all channels served from the *.unreel.me domain in channels/us.m3u immediately. The sharing of these channels served from our infrastructure is unauthorized and these channels may only be distributed by approved and pre-authorized means.

**Comment by Dum4G** [comment]
Have you sent us a DMCA Notice somewhere? If not all DMCA requests are being proceeded through a public form that Github offers
https://github.com/contact/dmca-notice

**Comment by peter-powr** [comment]
> Have you sent us a DMCA Notice somewhere? If not all DMCA requests are being proceeded through a public form that Github offers @peter-powr https://github.com/contact/dmca-notice

I have not sent a DMCA yet. I was following Github's guidelines: "A great first step before sending us a takedown notice is to try contacting the user directly". Are you saying that you are unable to remove it without a DMCA? 

I think there's potentially a scenario where we could look at offering IPTV as a distribution path for our clients particularly in an AVOD model, but this needs to be in a controlled manner and with their consent and the ability to attribute and manage traffic as CDN is not free. Additionally ads are often targeted per platform. As IPTV is at this point an unknown quantity for clients, it is going to get identified as bad traffic even though this may not necessarily be the case. This can down the road lead to IPTV as a whole being subjected to blocks and blacklists by vendors. 

I would appreciate us just handling this without having to resort to a DMCA, but if you are saying that is necessary then I will get our legal team involved. At that point, I would think it would make it more difficult to look at working together in the future.

**Comment by Dum4G** [comment]
@freearhey

**Comment by Central302** [comment]
[Note]Provider Said According "https://docs.github.com/en/github/site-policy/guide-to-submitting-a-dmca-takedown-notice""

**Comment by LaneSh4d0w** [comment]
In my opinion I find it easier to directly contact us from here instead of putting a DMCA takedown too. @Dum4G I'll make a PR and ask for approval from Arhey.

**Comment by dct-infra** [comment]
Anyone can ask for anything to be taken down.
imho a DMCA is necessary.
Who is this person? Did he properly introduce himself? Who is he working for? Is he allowed to ask for anything on behalf of anyone? 

"At that point, I would think it would make it more difficult to look at working together in the future." I won't comment this part.

**Comment by LaneSh4d0w** [comment]
> Anyone can ask for anything to be taken down. imho DMCA is mandatory. Who is this person? Did he properly introduce himself? Who is he working for? Is he allowed to ask for anything on behalf of anyone?
> 
> "At that point, I would think it would make it more difficult to look at working together in the future." A copy of an ID, a notarized power of attorney stating he's actually representing anyone whose copy rights are offended and we'll think about the working together part afterwards. Else, DMCA!

I have found one person corresponding to the name and also working at POWr : https://rocketreach.co/peter-wilson-ferrer-email_84088948

**Comment by peter-powr** [comment]
Apologies for the lack of introduction. I am the former CTO of Powr, now Bitcentral. As mentioned in the thread, I was trying to follow the GitHub procedure of directly asking here first. Since it appears that won't be possible, we will proceed with the DMCA.

**Comment by dct-infra** [comment]
We'll be waiting for it impatiently. Meanwhile, work on your tone Mr. former CTO.

**Comment by freearhey** [comment]
Personally, I have nothing against removing these links, but I also agree with @LaneSh4d0w and @dct-infra that it would be much easier if @peter-powr somehow confirmed his identity.

**Comment by freearhey** [comment]
Closed due to lack of response from the author of the request.
