### ISSUE TITLE
ABC Me

### ISSUE THREAD

**Issue by robocopz** [iptv-org/iptv#6361]
### Channel Name

ABC

### Channel ID

ABCMe.au

### Country

Australia

### Language

English

### Website

https://iview.abc.net.au/show/abc3-live-stream

### Stream URL

https://c.mjh.nz/101002210224

### Notes

Where is the API to get the tokenized m3u8?

**Comment by what-a** [comment]
Is this it?
https://abc-iview-mediapackagestreams-2.akamaized.net/out/v1/6e1cc6d25ec0480ea099a5399d73bc4b/index_45.m3u8

**Comment by PD-TheKrazy0ne** [comment]
https://c.mjh.nz/101002210224 plays in VLC as is.

**Comment by LaneSh4d0w** [comment]
The person who's got these kind of links is @matthuisman. Not something we've took care of.

**Comment by matthuisman** [comment]
I generate the token server side.
If it's playing, then I don't see any issues?
Token generation etc I keep to myself. Last time I published any of the generator code, the service stopped / changed it. Better to keep under wraps.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/cac2f96962f43fcec08d835b0878ed36307d4bbe/streams/au.m3u#L18-L19
