### ISSUE TITLE
Replace: KBS 1

### ISSUE THREAD

**Issue by mrdannyarmstrong** [iptv-org/iptv#6363]
### Channel Name

KBS1

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://github.com/iptv-org/iptv/blob/master/channels/kr.m3u

### Broken Link

http://121.130.210.101:9981/stream/channelid/637185705

### Notes

Link is dead

**Comment by freearhey** [comment]
Duplicate #6004
