### ISSUE TITLE
G4

### ISSUE THREAD

**Issue by spongebob849** [iptv-org/iptv#6366]
### Channel Name

G4

### Country

America

### Language

English

### Website

G4tv.com

**Comment by Central302** [comment]
[Note]Original Program Only [Not24/7], But Available Here
https://www.twitch.tv/g4tv

Schedule : https://www.twitch.tv/g4tv/schedule

**Comment by what-a** [comment]
@Central302 I'm curious why you added a CA label rather than US?

**Comment by what-a** [comment]
👍

**Comment by LaneSh4d0w** [comment]
> [Note]Original Program Only [Not24/7], But Available Here https://www.twitch.tv/g4tv
> 
> Schedule : https://www.twitch.tv/g4tv/schedule

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/g4tv

**Comment by freearhey** [comment]
Duplicate #5520
