### ISSUE TITLE
Replace: Sport TV1

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6373]
### Channel Name

Sport TV 1

### What happened to the stream?

It is stuck at a single frame/the same segment

### Playlist

https://smart-tv.livedoomovie.com:4431/02_SPORTTV_1_720p/chunklist.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/a4c2ca1dd8142efd17cd8f2a6f82bf2bfb46691c/streams/pt.m3u#L71-L73

**Comment by spotanjo3** [comment]
Doesn't worked.

**Comment by freearhey** [comment]
Broken link removed from playlist.
