### ISSUE TITLE
Nick (Germany)

### ISSUE THREAD

**Issue by Spongebobsquarepants1** [iptv-org/iptv#6377]
### Channel Name

Nickelodeon German

### Country

Germany

### Language

Germany

### Website

Nick.co.de

### Stream URL

Nick.co.de

**Comment by trancer1994** [comment]
https://unilivemtveu-lh.akamaihd.net/i/nickde_1@448749/master.m3u8

**Comment by freearhey** [comment]
https://www.lyngsat.com/tvchannels/us/Nickelodeon-Deutschland.html
