### ISSUE TITLE
Replace: ORF Sport+

### ISSUE THREAD

**Issue by Smark223** [iptv-org/iptv#6379]
### Channel Name

ORF Sport+

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://github.com/iptv-org/iptv/blob/master/channels/at.m3u

### Broken Link

https://orfs.mdn.ors.at/out/u/orfs/qxb/manifest.m3u8

### Notes

Assumed all ORF HLS streams had migrated to MPEG-Dash but the ORF 3 one is still active. Maybe m3u8 streams are still available for the other channels but I haven't been able to find them

**Comment by LaneSh4d0w** [comment]
It already does the redirection somehow, here it's geo-protected (FR), i'll try moving to AT and check.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/a4c2ca1dd8142efd17cd8f2a6f82bf2bfb46691c/streams/at.m3u#L30-L31
