### ISSUE TITLE
Replace: SIC Internacional

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6381]
### Channel Name

SIC Internacional

### What happened to the stream?

It is stuck at a single frame/the same segment

### Playlist

http://live.impresa.pt/live/sicint/sicint.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/a4c2ca1dd8142efd17cd8f2a6f82bf2bfb46691c/streams/pt.m3u#L63-L64

**Comment by LaneSh4d0w** [comment]
http://93.152.174.144:4000/play/sic/index.m3u8 ?

**Comment by spotanjo3** [comment]
This is not SIC Internacional. It is SIC HD.

**Comment by freearhey** [comment]
Broken link removed from playlist.
