### ISSUE TITLE
Broken Stream Replace: Infowars Network

### ISSUE THREAD

**Issue by douknoukkem** [iptv-org/iptv#6389]
### Channel Name

Infowars Network

### What happened to the stream?

It is disappeared from the playlist (404 error)

### Playlist

https://iptv-org.github.io/iptv/index.m3u

### Broken Link

http://wpc.9ec1.edgecastcdn.net/249EC1/infowarshd-edgecast/hd720.m3u8

### Possible Replacement

https://freespeech.akamaized.net/hls/live/2016712/live1/playlist.m3u8

### Notes

Current URL is broken and gives 404 error. New working link is directly from Infowars and not a third party

**Comment by Central302** [comment]
[Note] Old Link is Working, No Geo-Block.

**Comment by MapGuy11** [comment]
Both are working
