### ISSUE TITLE
Request for more golf channels

### ISSUE THREAD

**Issue by devhyunjae** [iptv-org/iptv#639]
Golf channels have disappeared :(
(i.e SBS, JTBC golf)

Can you add some channels that are available?

Thanks!

**Comment by freearhey** [comment]
- [ ] [SBS Golf](https://golf.sbs.co.kr/)
- [ ] [JTBC Golf](http://jtbcgolf.joins.com/)

**Comment by freearhey** [comment]
Closed in favor #1949
