### ISSUE TITLE
Telefides

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#6390]
### Channel Name

Telefides

### Country

Costa Rica

### Language

Spanish

### Website

http://telefides.com/en-vivo/

### Stream URL

https://s2.cwebtv.net:4433/telefides/telefides/chunklist.m3u8

**Comment by what-a** [comment]
https://s2.cwebtv.net:4433/telefides/telefides/playlist.m3u8
Not 24/7
![image](https://user-images.githubusercontent.com/88639906/153651893-96becd3b-5921-4c0c-95b2-4f40c4f2c13d.png)
