### ISSUE TITLE
MeTV Tallahassee WCTV-TV2 gone

### ISSUE THREAD

**Issue by Gitbone94** [iptv-org/iptv#6420]
### Describe your issue

WCTV-TV2 MeTV Tallahassee looks like it was removed from the playlist. It was here:
https://5e6cea03e25b6.streamlock.net/live/WCTVDT2.stream/playlist.m3u8

Please bring it back if possible.

**Comment by Dum4G** [comment]
Please fill a proper form for a broken stream

**Comment by Gitbone94** [comment]
My apologies.
