### ISSUE TITLE
Replace: MeTV WCTVDT2

### ISSUE THREAD

**Issue by Gitbone94** [iptv-org/iptv#6422]
### Channel Name

MeTV Tallahassee FL (WCTV2) (480p)

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://iptv-org.github.io/iptv/countries/us.m3u

### Broken Link

https://5e6cea03e25b6.streamlock.net/live/WCTVDT2.stream/playlist.m3u8

### Notes

This channel was in the playlist on Feb 10

**Comment by LaneSh4d0w** [comment]
I see that https://5e6cea03e25b6.streamlock.net/live/WCTVDT.stream/playlist.m3u8 works.

**Comment by Central302** [comment]
"404 Not Found", That's Sad.

**Comment by spotanjo3** [comment]
I hope so.

**Comment by LaneSh4d0w** [comment]
> The link from LaneSh4d0w is not working and the channel has been removed from the US playlist. Every other Tallahassee channel is still there. Wondering why MeTV is the only one that got removed. I hope it comes back online.

Works on my side.

![image](https://user-images.githubusercontent.com/30985701/155495550-5fd9b482-5235-4d42-a61f-03d79920f3dd.png)

**Comment by spotanjo3** [comment]
Share?

**Comment by Gitbone94** [comment]
The link from LaneSh4d0w is not MeTV. I got it to work and it was showing a news feed.

**Comment by mememe0142** [comment]
> I see that https://5e6cea03e25b6.streamlock.net/live/WCTVDT.stream/playlist.m3u8 works.

working..but there is pixelation

**Comment by spotanjo3** [comment]
Thanks.. It's working and no pixelation using IINA player instead of VLC. VLC doesn't have closed captioning for it but IINA does. Weird. Added to USA m38 file. Thanks.

**Comment by Gitbone94** [comment]
Any chance of progress on this? I see it is in the EPG.

**Comment by trancer1994** [comment]
Sorry to comment on a closed issue but are these feeds official? Someone else tells me they seem to be bootlegged but I don't know for sure.

**Comment by MapGuy11** [comment]
@trancer1994 With FCC law anyone can rebroadcast stations if they are under a non profit they are and these are official streams from OTA antenna transcoded to H264 and AAC

**Comment by spotanjo3** [comment]
It is dead.

**Comment by LaneSh4d0w** [comment]
Not really "dead" but went restricted. Maybe a token is needed to get access to it;

**Comment by spotanjo3** [comment]
Oh LOL, ok. 

Anyway.. Cool. I will wait. Thanks.
