### ISSUE TITLE
Replace: all frontline.ca streams down

### ISSUE THREAD

**Issue by TKList** [iptv-org/iptv#6428]
### Channel Name

frontline.ca streams

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://github.com/iptv-org/iptv/blob/master/channels/us.m3u

### Broken Link

all frontline.ca streams down

**Comment by Central302** [comment]
404 Not Found, Remove in #6424 .

[ReplaceMent List] ABC-NBC-CBS-FOX - Already in Playlist (Same Network, Diffarent  Station) Reffer : us_localbtv.m3u
WGN9 - Already in Playlist
CW - You Can Use Instead WTXL (Same Network)
Peachtree TV - No Way

**Comment by LaneSh4d0w** [comment]
Done with #6424
