### ISSUE TITLE
Fix: All the link related with 50.7.74.29

### ISSUE THREAD

**Issue by luongz** [iptv-org/iptv#6429]
### Channel Name

NHK G and more (related to 50.7.74.29)

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/countries/jp.m3u

### Broken Link

http://50.7.74.29:8880/hls/j00033/index.m3u8

### Possible Replacement

Change the IP and Port to: 51.79.193.108:8080

**Comment by Nobodynumber1** [comment]
**Too Strong 
Fixed Got new IP**
Thanks

**Comment by Central302** [comment]
Fixed. I'll Close The Issue.
