### ISSUE TITLE
VLC 播放加载速度缓慢，部分其他国家频道无法直接观看，需要科学上网

### ISSUE THREAD

**Issue by WeskerC** [iptv-org/iptv#643]
1. 请问是否有相应的DNS地址以供更快地加载直播信号？
2. 请问是否有方法免科学上网观看电视节目？

**Comment by freearhey** [comment]
抱歉，我们无法控制广播本身。该存储库仅包含指向广播的链接。

**Comment by bbhxwl** [comment]
同是中国人

**Comment by WeskerC** [comment]
> 抱歉，我们无法控制广播本身。该存储库仅包含指向广播的链接。

好的，感谢回复
