### ISSUE TITLE
Fix: link related with IP 50.7.74.29

### ISSUE THREAD

**Issue by butatuli** [iptv-org/iptv#6432]
### Channel Name

MBS (Mainichi Broadcasting System) (related to 50.7.74.29)

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/countries/jp.m3u

### Broken Link

http://50.7.74.29:8880/hls/j00038/index.m3u8

### Notes

I'm not sure to putting an issue since the problem is same like the issuer before me below. The problem is that all link related to the 50.7.74.29 mostly down

**Comment by Central302** [comment]
Fixed. I'll Close The Issue.
