### ISSUE TITLE
Replace: Marvel HQ (now Super Hungama)

### ISSUE THREAD

**Issue by HuskyHunk** [iptv-org/iptv#6434]
### Channel Name

Marvel hq

### What happened to the stream?

It is buffering to unplayable point

### Playlist

No idea

### Broken Link

https://feed.play.mv/live/10005200/niZoVrR2vD/master.m3u8

### Notes

Please update marvel hq channel link in Indian m3u file

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/a4c2ca1dd8142efd17cd8f2a6f82bf2bfb46691c/streams/us.m3u#L796-L797
