### ISSUE TITLE
Remove: most indian channels

### ISSUE THREAD

**Issue by xtendtech** [iptv-org/iptv#6436]
### Your full legal name

Xtendtech

### Are you the copyright holder or authorized to act on the copyright owner's behalf?

No.

### Please describe the nature of your copyright ownership or authorization to act on the owner's behalf.

Half of links are old expired links in [in.m3u](https://github.com/iptv-org/iptv/blob/master/channels/in.m3u)

Please remove all bad links... These are very old links.Sites itself doesnt work

### Please provide a detailed description of the original copyrighted work that has allegedly been infringed. If possible, include a URL to where it is posted online.

no

### What content should be removed? Please specify the URL for each item or, if it is an entire file, the file's URL.

https://acv.asianetmobiletvplus.com/webstreams/8f8e72769cb3e3a6e27c220e1e3887b8.smil/playlist.m3u8
#EXTINF:-1 tvg-id="ACVJukebox.in" tvg-country="IN" tvg-language="Malayalam" tvg-logo="https://i.imgur.com/tYPn1lW.png" user-agent="AsianetMobileTVPlus" group-title="Music",ACV JukeBox (404p) [Offline]
#EXTVLCOPT:http-user-agent=AsianetMobileTVPlus
http://cdn.asianetmobiletvplus.com/channels/acvjukebox_awannbgiynqynhufohawnvbmlgglfpuc/playlist.m3u8
#EXTINF:-1 tvg-id="ACVNews.in" tvg-country="IN" tvg-language="Malayalam" tvg-logo="https://i.imgur.com/fP0g1np.jpg" user-agent="AsianetMobileTVPlus" group-title="News",ACV News (404p) [Offline]
#EXTVLCOPT:http-user-agent=AsianetMobileTVPlus
http://cdn.asianetmobiletvplus.com/channels/acvnews_3e85eb4c12bd2110d3f495676205d50a/playlist.m3u8
#EXTINF:-1 tvg-id="ACVPlus.in" tvg-country="IN" tvg-language="Malayalam" tvg-logo="https://i.imgur.com/DjtPQeg.jpg" user-agent="AsianetMobileTVPlus" group-title="",ACV Plus (404p) [Offline]
#EXTVLCOPT:http-user-agent=AsianetMobileTVPlus
http://cdn.asianetmobiletvplus.com/channels/acvplus_ef22daf97d61acb4bf52376c4105ad02/playlist.m3u8
#EXTINF:-1 tvg-id="ACVUtsav.in" tvg-country="IN" tvg-language="Malayalam" tvg-logo="https://i.imgur.com/LLN585Y.png" user-agent="AsianetMobileTVPlus" group-title="",ACV Utsav (404p) [Offline]
#EXTVLCOPT:http-user-agent=AsianetMobileTVPlus
http://cdn.asianetmobiletvplus.com/channels/acvutsav_021c9292219a98f899a7b74f0f34baa7/playlist.m3u8
#EXTINF:-1 tvg-id="ADNGold.in" tvg-country="IN" tvg-language="Malayalam" tvg-logo="https://i.imgur.com/UzPPjoH.jpg" user-agent="AsianetMobileTVPlus" group-title="",ADN Gold (404p) [Offline]
#EXTVLCOPT:http-user-agent=AsianetMobileTVPlus

These are jus t some

### Any additional information we need to know?

no

### Please confirm the following

- [X] I have read and understand iptv-org's [Legal Statement](https://github.com/iptv-org/iptv#legal)

**Comment by Central302** [comment]
Close The Issue. Please Remade Issue in [Broken Stream] Form.
