### ISSUE TITLE
VH1 (Italy)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6437]
### Channel Name

VH1 Italia (Italy)

### Country

Italy

### Language

Italian

### Website

vh1.it

### Stream URL

https://content.uplynk.com/channel/36953f5b6546464590d2fcd954bc89cf.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1d5ac2cfd591466086b3f97fc403163e45b16a74/streams/us.m3u#L1612-L1613
