### ISSUE TITLE
Add: GTV Ghana

### ISSUE THREAD

**Issue by southerndream56** [iptv-org/iptv#6443]
### Channel Name

GTV Ghana

### Channel ID

GTV.gh

### Country

Ghana

### Language

french,english

### Website

http://www.ghanatvon.com/gtv-live-ghana.html

### Stream URL

http://cdn.filmover.com/hls/gtv/index.m3u8?e=1645013689&st=CUCTXNwgSu1tCV3hjoSNkQ

### Notes

Could you please add this stream to the IPTV list or just make the IPTV lines so that we can add it to our playlist...thanks

**Comment by LaneSh4d0w** [comment]
Tokenized, needs special workaround.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/gh.m3u#L16-L17
