### ISSUE TITLE
RAI24news(720p) m3u link not working

### ISSUE THREAD

**Issue by cowboykb** [iptv-org/iptv#6448]
Greetings !
Since m3u path: "https://iptv-org.github.io/countries/it.m3u" was recently re-enabled\updated, I'm unable to view this channel as before with no issues.  I'm running Kodi 19.3's iptv simple pvr client and receiving the error: "OpenDemuxerStream - Error creating demuxer" when I attempt to view the channel, which is not geo-blocked. Can someome please look into this and reply back as to what the issue is and if it can & will be corrected? Thank you so much for your kind consideration.

![20220215_204825](https://user-images.githubusercontent.com/99828740/154328048-57c38371-4202-4db5-a39d-b112521404aa.jpg)

**Comment by Central302** [comment]
https://rainews1-live.akamaized.net/hls/live/598326/rainews1/rainews1/playlist.m3u8 ?
Yes. 404 Not Found (Confirmed)

**Comment by cowboykb** [comment]
Thanks Central302 for your comment. So this means that I can only watch that stream if using a VPN?  Is there a slightly lower resolution stream link that can be substituted within the larger path?

**Comment by Central302** [comment]
Streaming Site is geo-blocked. m3u8 is no check.

**Comment by cowboykb** [comment]
Thanks again for your input.
