### ISSUE TITLE
Teletica 2022 Febrero 16

### ISSUE THREAD

**Issue by Saprissa21** [iptv-org/iptv#6449]
### Channel Name

Teletica

### Country

Costa Rica

### Language

Español

### Website

Www.dailymotion.com

http://free.fullspeed.tv

**Comment by Saprissa21** [comment]
> ### Channel Name
> Teletica
> 
> ### Country
> Costa Rica
> 
> ### Language
> Español
> 
> ### Website
> Www.dailymotion.com
> 
> https://stream-01.nyc.dailymotion.com/sec(jlR0lJnpjfic8bXdlVDO54_WCDpv-bcfDIiGNFvAHV4)/dm/3/x29e3wg/s/live-2.m3u8
> 
> ### Notes
> _No response_



https://stream-01.nyc.dailymotion.com/sec(jlR0lJnpjfic8bXdlVDO54_WCDpv-bcfDIiGNFvAHV4)/dm/3/x29e3wg/s/live-2.m3u8

**Comment by LaneSh4d0w** [comment]
it seems that right it's https://www.dailymotion.com/cdn/live/video/x29e3wg.m3u8?sec=RRaQWohHhS0MzAc4pW5WUPHK5cJyqyCtkDN0XwpYOLMCd_w4WSukZQC4TPjy7Efe2WOIPNFor4uevDreZrEmIQ&dmTs=486299&dmV1st=EAC1177DE42B93A706FE6CF90CC8EAC4

but we'll need a VPN locked to Costa Rica (which I have) to get the link all the time. Maybe using a bot or proxy to get the link every 24 hours should be OK.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/cr.m3u#L58-L59
