### ISSUE TITLE
Release Package?

### ISSUE THREAD

**Issue by chezsick** [iptv-org/iptv#645]
hello, and if you post a release package in release tab, because in the first commits in the past, releases begin 0.0.4 to 0.4.0 and nothing, is possible to resume?

newa.

**Comment by freearhey** [comment]
I stopped making releases because they had nothing to do with updating the playlists themselves. The package version was changed only after updating the internal scripts. So I don’t really understand how this can be useful.

**Comment by chezsick** [comment]
it's your choice, just at the 14 november this repo has one year.

**Comment by freearhey** [comment]
if you could explain why this is necessary?

**Comment by chezsick** [comment]
it's just an idea, sorry, i think you resumed.
