### ISSUE TITLE
Replace: Guatevision

### ISSUE THREAD

**Issue by josepedro770** [iptv-org/iptv#6453]
### Channel Name

Guatevision

### What happened to the stream?

It is stuck at a single frame/the same segment

### Playlist

https://iptv-org.github.io/iptv/index.country.m3u; https://iptv-org.github.io/iptv/countries/gt.m3u

### Broken Link

https://ott.streann.com/loadbalancer/services/public/channels/5d6821172cdced7698d5a329/playlist.m3u8

### Possible Replacement

https://prensalibre-live.cdn.vustreams.com/live/cd8f5328-7a1c-49d9-b318-9190858d1826/live.isml/live-audio_track_0_0_und=128000-video_track=2800000.m3u8

**Comment by lesterguitarrista** [comment]
No funcionan mas los links. Gracias igual

**Comment by oshu-v** [comment]
Try this one https://video.radiozona3.com:3901/stream/play.m3u8

**Comment by BellezaEmporium** [comment]
https://www.dailymotion.com/video/x8lth64
