### ISSUE TITLE
MeTV Philadelphia PA (WDPN-DT1)

### ISSUE THREAD

**Issue by Gitbone94** [iptv-org/iptv#6459]
### Channel Name

MeTV Philadelphia

### Country

US

### Language

English

### Website

https://www.metv2.com

### Stream URL

https://v-pi.theus6tv.tk/hls/2.1/playlist.m3u8

### Notes

In the US.tv playlist I already see .m3u8 for DT 2.2 and 2.5 so I'm looking for 2.1 to be added.

**Comment by what-a** [comment]
I'm guessing it doesn't have to be WDPN-DT1, but rather any eastern time zone stream of MeTV in 720p.   Is my guess correct?

**Comment by MapGuy11** [comment]
Not available.

**Comment by Gitbone94** [comment]
what-a, Yes I would take MeTV from any eastern time zone city other than WLWT (plays news at 10 pm instead of Hogan's Heroes lol). 
IPTV-ORG had Tallahassee WCTVDT2 working along with the other Tallahassee stations, then it disappeared from the playlist but all the other Tallahassee stations remained. 
I saw someone was adding Philly channels and they already had DT1 and DT5 set up so I was hoping DT2.1 MeTV in that market could be added.

**Comment by MapGuy11** [comment]
> WCTVDT2

Yeah that was me it's my server .1 is not available and probably never will be sorry for the inconvenience.

**Comment by what-a** [comment]
Folks behind the Tallahassee MeTV stream intend to bring it back online. However, no ETA. In the meantime we shall continue to search for additional eastern time zone MeTV sources.

**Comment by Gitbone94** [comment]
Thanks MapGuy11, it was worth a shot to ask.

**Comment by what-a** [comment]
This probably won't last...
MeTV NY
http://96.242.237.206:8000/play/a05n/index.m3u8

**Comment by LaneSh4d0w** [comment]
> This probably won't last... MeTV NY http://96.242.237.206:8000/play/a05n/index.m3u8

Astra Control Panel. May check if there's more in this.

**Comment by LaneSh4d0w** [comment]
ABC, AZTECA, FOX 5, METV, NEWS NY, NYTV LIFE, PIX11, STARTV, TELEMUNDO, TELEX, UNIMAS, UNIVISION, WMBQ, WNBC, ALIENTOVISION, WCBS

Mostly NY channels, meTV might not be from Philly.

**Comment by what-a** [comment]
Yeah, not from Philly. It's MeTV from New Jersey/New York (WJLP). Same East coast feed though.

**Comment by Gitbone94** [comment]
Thanks guys. MeTV WJLP from New Jersey/New York is as good as Philly. I only asked for Philadelphia because all the other Philly locals appeared in the channel lineup. I was hoping to get Tallahassee back but only because I saw all the other locals from there too. That request was closed so I guess that won’t happen.

**Comment by Gitbone94** [comment]
It looks like WLWT-DT2 is now in the channel list. That's welcome, but it is the one station that injects a newscast into the 10:00 pm time slot instead of classic tv (see my post above). It is great WJLP seems to be holding and I hope some other cities can be added. Thanks IPTV-ORG team!

**Comment by MapGuy11** [comment]
WJLP is now added to the list.

**Comment by what-a** [comment]
Time to close this issue. As discussed above, any east coast stream will suffice and WJLP does not preempt for local news. Additionally, it looks great in 720p.

**Comment by Gitbone94** [comment]
Outstanding job! Thanks
