### ISSUE TITLE
Repretel canal 6

### ISSUE THREAD

**Issue by Saprissa21** [iptv-org/iptv#6462]
### Channel Name

Repretel canal 6

### Country

Costa Rica

### Language

Spanísh

### Website

www.repretel.com

### Stream URL

https://d30zjikdv9ntds.cloudfront.net/repretel/canal6/smil:live.smil/chunklist_b1248000.m3u8

**Comment by MapGuy11** [comment]
Adaptive is this: https://d30zjikdv9ntds.cloudfront.net/repretel/canal6/smil:live.smil/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
Haven't I already added that one in the CR playlist ?

**Comment by LaneSh4d0w** [comment]
https://github.com/iptv-org/iptv/blob/20afc030d2388bfc2218520dec3ed0d35e25fb0e/channels/cr.m3u#L14-L15

**Comment by MapGuy11** [comment]
> https://github.com/iptv-org/iptv/blob/20afc030d2388bfc2218520dec3ed0d35e25fb0e/channels/cr.m3u#L14-L15

Oh lol I am going to close this.
