### ISSUE TITLE
BOM Channel

### ISSUE THREAD

**Issue by francescorosi27** [iptv-org/iptv#6466]
### Channel Name

BOM Channel

### Country

Italy

### Language

Italian

### Website

BOM Channel's Android app: https://play.google.com/store/apps/details?id=it.mediastreaming.tvbomchannel

### Stream URL

https://5f22d76e220e1.streamlock.net/BOMCHANNEL/BOMCHANNEL/playlist.m3u8

**Comment by what-a** [comment]
Logo:
https://bomchannel.it/wp-content/uploads/2021/10/bom-channel-logo-vert.png
