### ISSUE TITLE
Broken Stream: TV LAND

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6468]
### Channel Name

TV LAND

### What happened to the stream?

It is disappeared from the playlist

### Playlist

 http://s1.mysportz.tv:2082/TVLand/playlist.m3u8

### Broken Link

 http://s1.mysportz.tv:2082/TVLand/playlist.m3u8

**Comment by what-a** [comment]
All streams from http://s1.mysportz.tv are down.

**Comment by LaneSh4d0w** [comment]
> All streams from http://s1.mysportz.tv are down.

Data : 38.91.57.12

Domain name : *.flextv.io

Possible ports : http://38.91.57.12:31210/

**Comment by thoudankeykang** [comment]
> > All streams from http://s1.mysportz.tv are down.
> 
> 
> 
> IP : 38.91.57.12
> 
> 
> 
> Domain name : *.flextv.io
> 
> 
> 
> Possible ports : http://38.91.57.12:31210/

Keep us updated on this PLEASE

**Comment by thoudankeykang** [comment]
after a bit of research, flextv.io and mysportz.tv seem to be used by an illegal iptv provider

**Comment by spotanjo3** [comment]
So TV Land is a no ?

**Comment by LaneSh4d0w** [comment]
> So TV Land is a no ? 

For now yes.
