### ISSUE TITLE
Broken Stream: WeatherSpy 

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6469]
### Channel Name

WeatherSpy (1080p)

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://jukin-weatherspy-1.vizio.wurl.com/manifest/playlist.m3u8

### Broken Link

https://jukin-weatherspy-1.vizio.wurl.com/manifest/playlist.m3u8

**Comment by what-a** [comment]
https://7eeb372ee2224dbf9138691d0f5d218b.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung_WeatherSpy/playlist.m3u8?ads.wurl_channel=387&ads.wurl_name=WeatherSpy&ads.coppa=0&ads.us_privacy=1YNY&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D

**Comment by spotanjo3** [comment]
Working! Thank you.

**Comment by LaneSh4d0w** [comment]
Alt : https://jukin-weatherspy-1-us.samsung.wurl.tv/playlist.m3u8
