### ISSUE TITLE
Broken Stream: MSNBC (720p)

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6470]
### Channel Name

MSNBC

### What happened to the stream?

Dead

### Playlist

http://encodercdn1.frontline.ca/encoder182/output/MSNBC_720p/playlist.m3u8

### Broken Link

[
](http://encodercdn1.frontline.ca/encoder182/output/MSNBC_720p/playlist.m3u8
)
)### Possible Replacement

_No response_

**Comment by PD-TheKrazy0ne** [comment]
Works for me

**Comment by spotanjo3** [comment]
Wrong channel. It is mean to be for MSNBC. :)

Your input can't be opened
VLC is unable to open the MRL 'http://encodercdn1.frontline.ca/encoder182/output/MSNBC_720p/playlist.m3u8'. Check the log for details.

Another player do not run it too.

**Comment by LaneSh4d0w** [comment]
Goes along with https://github.com/iptv-org/iptv/pull/6441

**Comment by PD-TheKrazy0ne** [comment]
https://hls.goodgame.ru/manifest/188429_master.m3u8 - MSNBC USA

**Comment by spotanjo3** [comment]
Its lag. If you watch it careful.

**Comment by PD-TheKrazy0ne** [comment]
sorry maybe you should subscribe to cable

**Comment by jhedfors** [comment]
> https://hls.goodgame.ru/manifest/188429_master.m3u8 - MSNBC USA

While this link works in Chrome, it does not work for me in VLC or iMPlayer.

**Comment by LaneSh4d0w** [comment]
> > https://hls.goodgame.ru/manifest/188429_master.m3u8 - MSNBC USA
> 
> While this link works in Chrome, it does not work for me in VLC or iMPlayer.

Most certainly asks for a browser user-agent

**Comment by PD-TheKrazy0ne** [comment]
> https://hls.goodgame.ru/manifest/188429_master.m3u8

works fine with user agent in m3u VLC and in Kodi

For VLC:

#EXTM3U
#EXTINF:0, MSNBC
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
https://hls.goodgame.ru/manifest/188429_master.m3u8

For Kodi Playlist:

<item>
<title>MSNBC</title>
<link>https://hlss.goodgame.ru/hls/188429.m3u8|User-Agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36</link>
<thumbnail></thumbnail>
<fanart></fanart>
</item>

**Comment by spotanjo3** [comment]
Not smoothly on VLC and no closed captioning. :(

**Comment by freearhey** [comment]
Closed in favor #6590
