### ISSUE TITLE
Broken Stream: NBC Boston (1080p)

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6471]
### Channel Name

NBC Boston

### What happened to the stream?

It is disappeared from the playlist

### Playlist

http://encodercdn1.frontline.ca/encoder183/output/NBC_Boston_720p/playlist.m3u8

### Broken Link

http://encodercdn1.frontline.ca/encoder183/output/NBC_Boston_720p/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
Goes along with https://github.com/iptv-org/iptv/pull/6441
