### ISSUE TITLE
Broken Stream: This Old House

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6472]
### Channel Name

This Old House

### What happened to the stream?

It is stuck at a single frame/the same segment

### Playlist

https://26487f8be0614420a64b6f5964563a75.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung_ThisOldHouse/playlist.m3u8

### Broken Link

https://26487f8be0614420a64b6f5964563a75.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung_ThisOldHouse/playlist.m3u8

### Notes

Sometimes flash and hiccup. You have to watch longer to noticed it.

**Comment by what-a** [comment]
Working fine:
![image](https://user-images.githubusercontent.com/88639906/154850980-29c51043-c531-49a2-834d-6ce37a192fa8.png)

**Comment by spotanjo3** [comment]
No. I said if you watch a little longer around 15 minutes.. Its hiccup or flash somehow. Here it goes again just now about 15 minutes. Again..its flash and swirl then back on again.

**Comment by spotanjo3** [comment]
It freeze after swirl so I have to change the channel then go back and its working fine again.. Seems to happen about 15 minutes or so.

**Comment by LaneSh4d0w** [comment]
Another link would be https://thisoldhouse-samsung-us.samsung.wurl.tv/playlist.m3u8

**Comment by what-a** [comment]
@spotanjo3 Could you test the stream suggested by LaneSh4d0w and provide feedback?

**Comment by spotanjo3** [comment]
I will be happy to. Be right back in fifteen minutes. I am watching it right now.

**Comment by spotanjo3** [comment]
Seems fine to me so far. Thanks you guys!

**Comment by spotanjo3** [comment]
REPORT: It's flash again. Only when there is ads is done then return to tv show and it got flash several time. Strange.
