### ISSUE TITLE
Fix: developers endpoint not working

### ISSUE THREAD

**Issue by Laurent-c4** [iptv-org/iptv#6476]
### Describe your issue

https://iptv-org.github.io/iptv/channels.json returns 404

**Comment by LaneSh4d0w** [comment]
Now is on https://iptv-org.github.io/api/channels.json

**Comment by freearhey** [comment]
Here is the updated API documentation: https://github.com/iptv-org/api#streams

**Comment by freearhey** [comment]
Just in case, I uploaded the old `channels.json` file back

https://iptv-org.github.io/iptv/channels.json

but it will no longer be updated. So if you can, I advise you to switch to the new API: https://github.com/iptv-org/api
