### ISSUE TITLE
Italy- RAI 1 & RAI 2

### ISSUE THREAD

**Issue by rdibiase** [iptv-org/iptv#648]
The previously available RAI 1 and RAI 2 are no longer listed in any playlists. All other RAI channels are still available. Will RAI 1 and RAI 2 be added back into this great repository?

Thanks

**Comment by freearhey** [comment]
As soon as there are working links to the broadcast of these channels, we will of course bring them back.

**Comment by rdibiase** [comment]
The two streams were functional at the time of removal

**Comment by freearhey** [comment]
I just double-checked the broadcast links that were deleted and they still don't work. If you wish, you can check them yourself: https://github.com/iptv-org/iptv/commit/a87b0cc5dc48e6158db92c713695a2a3f4d7bed3#diff-ff84259669312f3f20b0584a62969a49L210-L215

**Comment by rdibiase** [comment]
Thank you for looking into this.

This is an amazing project. Thanks for your efforts

**Comment by freearhey** [comment]
- [x] Rai 1
https://github.com/iptv-org/iptv/blob/17435f1af3c9b61616ad841d8e84931b875b5e4f/channels/it.m3u#L342-L343
- [ ] Rai 2

**Comment by Nintendocustom** [comment]
the stream says: "403 Forbidden"

**Comment by freearhey** [comment]
@Nintendocustom this is what I see:

<img width="779" alt="Captura de pantalla 2020-04-19 a las 4 41 52" src="https://user-images.githubusercontent.com/7253922/79677273-3c31f180-81f8-11ea-9c8b-890df9c7ff89.png">

Tested in Elmedia Video Player.

**Comment by rdibiase** [comment]
RAI 1 is working within IplayTV on my AppleTv

Thank you

**Comment by Nintendocustom** [comment]
I tested the stream with vlc, streamtest.in and chrome.

**Comment by Nintendocustom** [comment]
RAI 1 HD
http://stream-7b694ce7e.nmbs.top/m3u/Italy/cae2d46cf6.m3u8
RAI 2 HD
http://stream-7b694ce7e.nmbs.top/m3u/Italy/3207341b6b.m3u8
