### ISSUE TITLE
Add: Rotana Classic (1080p)

### ISSUE THREAD

**Issue by iptvchecker** [iptv-org/iptv#6480]
### Channel Name

Rotana Classic (1080p)

### Channel ID

RotanaClassic.sa

### Website

https://shls-rotanaclassic-prod-dub.shahid.net/out/v1/4eebed211c8441228321b4f67a46c5a5/index.m3u8

### Stream URL

https://shls-rotanaclassic-prod-dub.shahid.net/out/v1/4eebed211c8441228321b4f67a46c5a5/index.m3u8

### Notes

These two entries were in the list few days back. It seems that the first link works. I tested it. The second one does not work. Maybe someone was doing some housekeeping, thinking the link does not work so he removed both. Please reinstate the first link!

Thanks.

#EXTINF:-1 tvg-id="Rotana Classic" tvg-country="SA" tvg-language="Arabic" tvg-logo="https://rotana.net/assets/themes/TriTheme/images/channels/classic.png" group-title="Classic",Rotana Classic (1080p)
https://shls-rotanaclassic-prod-dub.shahid.net/out/v1/4eebed211c8441228321b4f67a46c5a5/index.m3u8

#EXTINF:-1 tvg-id="Rotana Classic" tvg-country="SA" tvg-language="Arabic" tvg-logo="https://rotana.net/assets/themes/TriTheme/images/channels/classic.png" group-title="Classic",Rotana Classic (1080p) [Geo-blocked]
https://hiplayer.hibridcdn.net/t/rotana-classical.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
I only have one it seems : https://dai.google.com/linear/hls/pa/event/Ow9HolmDThGX9-D9EOdrHw/stream/fd8360aa-cb95-48cf-b252-eb56d00a1aca:BRU/master.m3u8

**Comment by robocopz** [comment]
> I only have one it seems : https://dai.google.com/linear/hls/pa/event/Ow9HolmDThGX9-D9EOdrHw/stream/fd8360aa-cb95-48cf-b252-eb56d00a1aca:BRU/master.m3u8

Expired

**Comment by iptvchecker** [comment]
Why don't you PUT BACK the one that was there before and it works!

I have provided the link from a previous iptv-org list. It's here again. Please just put it as in my comments and here:
https://shls-rotanaclassic-prod-dub.shahid.net/out/v1/4eebed211c8441228321b4f67a46c5a5/index.m3u8

**Comment by LaneSh4d0w** [comment]
> Why don't you PUT BACK the one that was there before and it works!
> 
> I have provided the link from a previous iptv-org list. It's here again. Please just put it as in my comments and here: https://shls-rotanaclassic-prod-dub.shahid.net/out/v1/4eebed211c8441228321b4f67a46c5a5/index.m3u8

Indeed. May have stopped working at one moment in time, can't tell. From what I see, it works.

**Comment by iptvchecker** [comment]
Is it added back to the list? I will go check.

**Comment by iptvchecker** [comment]
The channel is not there!

Please use my ticket information to add Rotana Classics. The right channel URL is there.

**Comment by LaneSh4d0w** [comment]
Please note that :
1) This is *not automatic*. It is not my submitting an issue that it'll get automatically added
2) A PR (and it's approvals) need to be made to fix this issue.
3) Even if the PR is approved, there's a latency between channel addition onto the playlists and the bot pushing it onto the github.io playlists.

**Comment by iptvchecker** [comment]
Thank you for these three valuable point. I am fully aware of them and appreciate the great work you guys do. My previous comment was made when I felt that the my ticket was understood as a request to "research" a new channel. Merely I was "suggesting" restoring the link that I got from the previous release (obviously within your human process!)
Best regards and all appreciation!

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1d5ac2cfd591466086b3f97fc403163e45b16a74/streams/sa.m3u#L84-L85

**Comment by LaneSh4d0w** [comment]
> https://github.com/iptv-org/iptv/blob/1d5ac2cfd591466086b3f97fc403163e45b16a74/streams/sa.m3u#L84-L85

I'll also have to need to look after the different "faulio-backed" streams, as Nintendocustom's server is down
