### ISSUE TITLE
Remove: N1 TV Channel (all variants - CRO, SRB, BH, SLO)

### ISSUE THREAD

**Issue by UM-AntiPiracyTeam** [iptv-org/iptv#6486]
### Your full legal name

Ralf Manthey

### Are you the copyright holder or authorized to act on the copyright owner's behalf?

Yes, I am authorized to act on the copyright owner's behalf.

### Please describe the nature of your copyright ownership or authorization to act on the owner's behalf.

United Media (UM) is copyright and related rights owner, and has the broadcasting license for TV Channels: Sport Klub 1-10, HD, Sport Klub Golf, SK Fight, Sport Klub eSports, Lov i Ribolov, Pikaboo, Cinemania, Nova S, Nova Sport, Vavoom, Brainz. Moreover, UM is authorized, on behalf of its affiliated companies, to protect their copyrights and related rights over the following TV Channels: N1, Grand 1, Grand 2, NOVA TV, Doma, IDJTV, NOVA GR, NovaCinema 1-4, NovaLife, NovaSport 1-4, Nova Prime, Nova BG, Kino Nova, Nova Sport BG, Diema, Diema Family, Diema Sport 1-3 (hereinafter all referred as: the “Protected Work”). As such, UM is entitled to protect copyright and related rights over the Protected Work, on behalf of its affiliated companies that are all members of United Group and that have given us the power of representation in these matters.

More on United Media, United Group and our production house, tv channels and tv programs can be found on the following links:
https://united.group/
http://www.unitedmedia.net/
http://www.unitedmedia.net/channel/production/

### Please provide a detailed description of the original copyrighted work that has allegedly been infringed. If possible, include a URL to where it is posted online.

N1 is a 24-hour cable news channel launched on 30 October 2014. The channel has headquarters in Belgrade, Sarajevo, Ljubljana, and Zagreb and covers events happening in Southeastern Europe. 
Available on cable TV throughout former Yugoslavia, N1 is CNN International's local broadcast partner and affiliate via an agreement with the London-based Turner Broadcasting System Europe. 
As it is focused on the audiences of the four countries in which it is headquartered, it has four separate editorial policies, separate reporters, TV studios as well as internet and mobile platforms. 
In cases where news overlaps, it is presented jointly.

https://rs.n1info.com/
https://hr.n1info.com/
https://ba.n1info.com/
https://n1info.si/

### What content should be removed? Please specify the URL for each item or, if it is an entire file, the file's URL.

All the links can be found in this URL: https://github.com/iptv-org/iptv | https://iptv-org.github.io/iptv/index.m3u

#EXTINF:-1 tvg-id="N1.ba" tvg-country="BA" tvg-language="Bosnian" tvg-logo="https://www.lyngsat.com/logo/tv/nn/n1_rs.png" group-title="News",N1 BIH (576p)
https://best-str.umn.cdn.united.cloud/stream?channel=n1bos&p=n1Sh4redSecre7iNf0&sp=n1info&stream=sp1400&u=n1info
#EXTINF:-1 tvg-id="[N1.hr](http://n1.hr/)" tvg-country="HR" tvg-language="Croatian" tvg-logo="https://www.lyngsat.com/logo/tv/nn/n1_rs.png" group-title="News",N1 HRVATSKA (576p)
https://best-str.umn.cdn.united.cloud/stream?channel=n1hrv&p=n1Sh4redSecre7iNf0&sp=n1info&stream=sp1400&u=n1info
#EXTINF:-1 tvg-id="[N1.rs](http://n1.rs/)" tvg-country="RS" tvg-language="Serbian" tvg-logo="https://www.lyngsat.com/logo/tv/nn/n1_rs.png" group-title="News",N1 RS (576p) [Not 24/7]
https://best-str.umn.cdn.united.cloud/stream?channel=n1srp&p=n1Sh4redSecre7iNf0&sp=n1info&stream=sp1400&u=n1info
#EXTINF:-1 tvg-id="[N1.si](http://n1.si/)" tvg-country="SI" tvg-language="Slovenian" tvg-logo="https://www.lyngsat.com/logo/tv/nn/n1_rs.png" group-title="News",N1 SLOVENSKA (576p)
https://best-str.umn.cdn.united.cloud/stream?channel=n1slv&p=n1Sh4redSecre7iNf0&sp=n1info&stream=sp1400&u=n1info

### Any additional information we need to know?

You can contact us directly at our dedicated anti-piracy email address: anti-piracy@unitedmedia.net.

### Please confirm the following

- [X] I have read and understand iptv-org's [Legal Statement](https://github.com/iptv-org/iptv#legal)

**Comment by freearhey** [comment]
All links mentioned in the request have been removed from the repository.
