### ISSUE TITLE
>

### ISSUE THREAD

**Issue by ahmetxnight** [iptv-org/iptv#6493]
> 
> 
> List of 112.155.180.8 3 = Not Working 95 = CNN International 98 = CNBC Asia 105 = Nat-Geo(Chinese) 191 = Star Channel2 193 = Star Channel3 205 = WOWOW Live 207 = Nippon TV G+ 208 = Decode ERROR 209 = WOWOW Plus 210 = Sky A Sports 212 = Fuji TV One 213 = Commerical Playing 216 = KBS World Japanese 217 = TV Asahi Channel 2 219 = HISTORY Channel(Japanese) 220 = TBS NEWS 221 = TBS Channel 1 223 = TV Asahi Channel 1(Currentry Video Broken) 224 = WOWOW Cinema 261 = Not Working 263 = Nat-Geo Wild(Chinese Sub) - Japanese Channel Was Alreaady Shutdown 301 = NHK BS1 302 = BS12 303 = NHK BS Premium 304 = BS Nippon TV 305 = BS-TBS 306 = BS TV Tokyo 307 = BS Fuji TV 308 = BS Asahi 309 = NHK-G TOKYO 310 = NHK-E TOKYO 311 = TOKYO MX1 312 = Nippon TV 313 = TV Asahi 314 = TBS 315 = TV Tokyo 316 = Fuji TV 317 = NHK-G Osaka 318 = NHK-E Osaka 319 = MBS 320 = SUN Television 321 = ABC Asahi Broadcasting System 322 = TV Osaka 323 = Kansai-TV 324 = Yomiuri TV 325 = WOWOW Prime 326 = Star Channel 1 361 = Not Working 396 = TV5Monde Asia(No Sound) 408 = Samurai-TV 409 = GOLF Network 410 = J Sports 3 411 = J Sports 4 412 = Green Channel 413 = GAORA 415 = J Sports 1 416 = J Sports 2 418 = BBC World News 428 = Not Working 440 = Discovery Asia(Chinese Sub) 457 = Sci-fi Channel(Chinese Sub) 492 = Nippon TV Plus 493 = Family Gekijo 494 = Kids Station(But Have Japanese Captioning) 496 = Music Japan TV(Video ImageBroken) 496 = Discovery Channel Japan 497 = Commercial 498 = Animax Japan 499 = Disney Channel Japan

Sensibly similar to what the Redlab host had. Interesting find.

_Originally posted by @LaneSh4d0w in https://github.com/iptv-org/iptv/discussions/5297#discussioncomment-1657036_

**Comment by LaneSh4d0w** [comment]
?
