### ISSUE TITLE
Add: TUDN (Spanish Soccer Channel)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6495]
### Channel Name

TUDN 

### Website

https://tv.univision.com/channels?seoName=univision&utm_source=univisioncom&utm_medium=nav-watchbutton&utm_campaign=TVE-2019-seoName

### Stream URL

https://pubads.g.doubleclick.net/ssai/event/bQ2JGGVzTpqfCfcTZWay1Q/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Geo-locked. Redirection goes correctly.
