### ISSUE TITLE
Add: ABC / CBS 7 Jackson TN (WBBJ)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6498]
### Channel Name

ABC / CBS 7 Jackson TN (WBBJ)

### Website

https://www.wbbjtv.com/live/

### Stream URL

https://dai.google.com/linear/hls/event/HZ3JdLVcQ463l3b1BLXmmQ/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Excellent feed, working fine.

Alternative : https://uvodnt-i.akamaihd.net/hls/live/1019996/WBBJ/master.m3u8

**Comment by MapGuy11** [comment]
#6619
