### ISSUE TITLE
possibility to add my channel to your list

### ISSUE THREAD

**Issue by joelchavez777** [iptv-org/iptv#650]
I would like you to help me add my internet channel to your spectacular list, tell me what you need, and if you can do it
My channel is of solidarity theme, of ONG and projects for the benefit of the most needy, we broadcast from Madrid.

Thank you

**Comment by freearhey** [comment]
Here's a guide to adding channels to playlists: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#add-channel
