### ISSUE TITLE
Add: Metro Nashville Network

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6506]
### Channel Name

Metro Nashville Network

### Website

https://nashville.granicus.com/player/camera/2?publish_id=6&redirect=true

### Stream URL

http://granicusliveus10-a.akamaihd.net/nashville/G2157_002/chunks.m3u8

### Please confirm the following

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by MapGuy11** [comment]
Adaptive: http://granicusliveus10-a.akamaihd.net/nashville/G2157_002/playlist.m3u8
