### ISSUE TITLE
Add: Azteca 7 México

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6507]
### Channel Name

Azteca 7

### Channel ID

Azteca7.mx

### Website

https://www.tvplusgratis.com/azteca-7-en-vivo.html

### Stream URL

https://live.telelatinohd.com/hls/cu1as8e8mxraxmpll/1_.m3u8?token=whRwkufkQ-iny3yDnamZdw&expires=1645663511

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Should be added a bit later with what we got. Stay tuned.

**Comment by freearhey** [comment]
https://live.telelatinohd.com/hls/cu1as8e8mxraxmpll/1_.m3u8?token=whRwkufkQ-iny3yDnamZdw&expires=1645663511
<img width="751" alt="image" src="https://user-images.githubusercontent.com/7253922/185199163-28f039ac-e61b-4722-b73e-63f6d244e32c.png">

**Comment by AntiPontifex** [comment]
Dead link: please close.
