### ISSUE TITLE
Broken Stream: RTP2

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6508]
### Stream Title

RPT2

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://streaming-live.rtp.pt/liverepeater/rtpClean2HD.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Works for me 

![image](https://user-images.githubusercontent.com/30985701/155496085-84f7bb5b-a648-4c89-a02e-35050f924cb7.png)

**Comment by Smark223** [comment]
Yeah, works fine. It is down occasionally when certain programmes are being shown, I assume, for rights issues. So maybe just bad timing when you caught it.

**Comment by spotanjo3** [comment]
Yeah, I noticed. Thanks! :D

**Comment by LaneSh4d0w** [comment]
Closed due to stream working again.
