### ISSUE TITLE
Broken Stream: RTP Africa  

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6509]
### Stream Title

RTP Africa

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://streaming-live.rtp.pt/liverepeater/smil:rtpafrica.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Works for me

![image](https://user-images.githubusercontent.com/30985701/155496202-5ae2304a-8e3e-4224-8e36-fdeb549f2a76.png)

**Comment by LaneSh4d0w** [comment]
Closed due to stream working.
