### ISSUE TITLE
Broken Stream: RTP Memoria 

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6510]
### Stream Title

RTP Memoria

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://streaming-live.rtp.pt/liverepeater/smil:rtpmem.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Works, not 24/7.

**Comment by spotanjo3** [comment]
Yeah. And I hope they find one that is 24/7 because I disliked "not 24/7".

**Comment by spotanjo3** [comment]
Found RTP Memoria link?
