### ISSUE TITLE
Broken Stream: Fox News Channel 

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6511]
### Stream Title

Fox News Channel

### What happened to the stream?

It is disappeared from the playlist

### Playlist

http://encodercdn1.frontline.ca/encoder181/output/FOX_News_720p/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/552de94eed297776b2e5a49a006e5503533f56e7/streams/us.m3u#L671-L672

<img width="640" alt="image" src="https://user-images.githubusercontent.com/7253922/159473659-bfa2e00c-83a0-433b-b8f1-c68a501cdcb0.png">

**Comment by spotanjo3** [comment]
Thanks but no closed caption. :(
