### ISSUE TITLE
Broken Stream: CONtv (1080p) 

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6512]
### Stream Title

CONtv

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://cinedigm.vo.llnwd.net/conssui/amagi_hls_data_xumo123-contv/CDN/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by spotanjo3** [comment]
CONtv Anime works finee.

BUT…. Not CONtv (1080p)

**Comment by spotanjo3** [comment]
I didnt say Anime. I know and i am
In USA also.

**Comment by LaneSh4d0w** [comment]
The second one isn't Anime, it's the original ConTV.

**Comment by spotanjo3** [comment]
Oh you just posted and I missed. Thanks. It's working now.

**Comment by spotanjo3** [comment]
None of the links are working anymore. Anybody have the better link for CONtv ?
