### ISSUE TITLE
Broken Stream: BBC News

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6513]
### Stream Title

BBC News

### What happened to the stream?

It is disappeared from the playlist

### Playlist

http://www.filmon.com/vr-streams/27.high/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by PD-TheKrazy0ne** [comment]
https://cdnuk001.broadcastcdn.net/KUK-BBCNEWSHD/index.m3u8 - BBC NEWS

**Comment by spotanjo3** [comment]
This is UK (English) but isn't US m3u files.

**Comment by LaneSh4d0w** [comment]
Then you're talking about BBC America, there's no such thing as BBC "News" America for now.

**Comment by spotanjo3** [comment]
Okay. I am confused. Okay, now I got it. I am talking about both BBC America and BBC World news because I liked the news about America only and BBC World for any nations. Two are better than one. :D

**Comment by Francis141** [comment]
http://prox.x86.co.uk/index.php/https://cdnuk001.broadcastcdn.net/KUK-BBCNEWSHD/index.m3u8

Enjoy :)

**Comment by spotanjo3** [comment]
Good work, Francis141 but unfortunately.. no closed caption. :(

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/552de94eed297776b2e5a49a006e5503533f56e7/streams/uk.m3u#L50-L51

<img width="640" alt="image" src="https://user-images.githubusercontent.com/7253922/159474029-d6ce4868-c3a9-4e3e-88dc-8cccdad4899d.png">

**Comment by spotanjo3** [comment]
Access denied.

**Comment by Francis141** [comment]
cc won't work. In what language do you want to watch news or any channel?

**Comment by spotanjo3** [comment]
English. I always watch CC in English.
