### ISSUE TITLE
Broken Stream: AMC IFC Film Picks (1080p) 

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6514]
### Stream Title

AMC IFC Film Picks

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://amc-ifc-films-picks-1.vizio.wurl.com/manifest/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by PD-TheKrazy0ne** [comment]
https://amc-ifc-films-picks-1.imdbtv.wurl.com/manifest/playlist.m3u8

**Comment by spotanjo3** [comment]
Please change the subject. It is now working.

**Comment by LaneSh4d0w** [comment]
In playlist
