### ISSUE TITLE
Fix: tvg-country, tvg-language, tvg-logo are missing since #6488

### ISSUE THREAD

**Issue by cy8018** [iptv-org/iptv#6516]
### Describe your issue

tvg-country, tvg-language, tvg-logo are missing since #6488.
And a lot of tvg-id are emptied since this update, for example in cn.m3u:

![image](https://user-images.githubusercontent.com/26640957/155531332-e4c7e3b4-3321-4692-ad55-01ffc22601fe.png)

Is this by design or a bug?

Thank you.

**Comment by freearhey** [comment]
This is not a bug. Details: https://github.com/iptv-org/iptv/discussions/6340

**Comment by cy8018** [comment]
> This is not a bug. Details: #6340

@freearhey Thank you for the explanations. That is a good idea have the new API.
But there's another issue: this commit https://github.com/iptv-org/iptv/commit/7c524a0f990488784136e058fd6789d1de7f152a not only removed the tvg-country, tvg-language, tvg-logo tags, but also have other impact:
Most (1252 out of 1471) of the tvg-id are emptied in [cn.m3u](https://github.com/iptv-org/iptv/blob/b037c6c838bb38e5e320fc00f714494c5dd5f588/streams/cn.m3u). Which makes it impossible for me to link the channels to the database. I didn't check for all the files, but at least this has happened to cn.m3u

![image](https://user-images.githubusercontent.com/26640957/155636283-1dadea27-4e29-4e57-bc72-1cfb2254b677.png)


Would you please fix this? Thanks a lot.

**Comment by freearhey** [comment]
The repository now only uses ids from [iptv-org/database](https://github.com/iptv-org/database). Most `tvg-id` remained the same, but unfortunately in the case of Chinese channels it is not possible to automatically pick up the correct ID. So the remaining `tvg-id` will have to be filled in manually, which will take some time.

Meanwhile, you can generate tvg-ids based on the channel name yourself as it was done before like so:

```js
generate('东至影视', 'cn') => 'DongZhiYingShi.cn'
```

https://github.com/iptv-org/iptv/blob/78190eafb7560b8d95543d634b3f603473fa3cd3/scripts/core/id.js#L1-L19

or use the names themselves as an id.

**Comment by cy8018** [comment]
> The repository now only uses ids from [iptv-org/database](https://github.com/iptv-org/database). Most `tvg-id` remained the same, but unfortunately in the case of Chinese channels it is not possible to automatically pick up the correct ID. So the remaining `tvg-id` will have to be filled in manually, which will take some time.
> 
> Meanwhile, you can generate tvg-ids based on the channel name yourself as it was done before like so:
> 
> ```js
> generate('东至影视', 'cn') => 'DongZhiYingShi.cn'
> ```
> 
> https://github.com/iptv-org/iptv/blob/78190eafb7560b8d95543d634b3f603473fa3cd3/scripts/core/id.js#L1-L19
> 
> or use the names themselves as an id.

I'd like to help on fill in the Chinese ids, can you please let me know where should I make the changes?
Is it directly in the https://github.com/iptv-org/database/blob/master/data/channels.csv or in any other scripts?

Thanks.

**Comment by cy8018** [comment]
One question here, should the column "Name" attribute in the [channels.csv](https://github.com/iptv-org/database/blob/master/data/channels.csv) be in English or in their native languages?
If it is necessary to keep a English name here, then I would suggest to add another column "native_name" in the file, which would be very useful for developers to create user friendly apps.

**Comment by freearhey** [comment]
That's a great idea! I will try to add this field to the file in the next couple of days.

**Comment by freearhey** [comment]
Field `native_name` added to the table: https://github.com/iptv-org/database#channels

**Comment by cy8018** [comment]
Thank you for the notice, I will try to add/update the Chinese channels.
