### ISSUE TITLE
Broken Stream: True Premier Football HD 1 (720p) [Not 24/7]

### ISSUE THREAD

**Issue by pukozs75** [iptv-org/iptv#6519]
### Stream Title

True Premier Football HD 1 (720p) [Not 24/7]

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://smart-tv.livedoomovie.com:4431/02_PremierHD1_720p/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Closing in favor: #6520
