### ISSUE TITLE
Replace: True Premier Football HD 1

### ISSUE THREAD

**Issue by pukozs75** [iptv-org/iptv#6520]
### Stream Title

True Premier Football HD 1 (720p) [Not 24/7]

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/categories/sports.m3u

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f64eccb9362a086387cc16c8164d5ad211a7e424/streams/th.m3u#L51-L53
