### ISSUE TITLE
Add: Çufo (ALB)

### ISSUE THREAD

**Issue by Agumonz98** [iptv-org/iptv#6521]
### Stream Title

Çufo

### What happened to the stream?

Other

### Playlist

https://github.com/iptv-org/iptv/blob/master/streams/al.m3u

### Broken Link

http://93.157.62.180/Cufo/index.m3u8
http://us.bestvideostreaming.is/8738/playlist.m3u8

### Notes

The first stream stopped working yesterday while the second had not worked for a few months now.

### Please confirm the following

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Closed in favor #8131
