### ISSUE TITLE
Replace: Bang Bang (ALB)

### ISSUE THREAD

**Issue by Agumonz98** [iptv-org/iptv#6522]
### Stream Title

Bang Bang

### What happened to the stream?

Other

### Playlist

https://github.com/iptv-org/iptv/blob/master/streams/al.m3u

### Broken Link

http://93.157.62.180/BangBang/index.m3u8
http://us.bestvideostreaming.is/8737/playlist.m3u8

### Notes

The first stream stopped working yesterday while the second had not worked for a few months now.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f64eccb9362a086387cc16c8164d5ad211a7e424/streams/al.m3u#L90-L91

**Comment by freearhey** [comment]
The broken link has been removed from the playlist.

Closed in favor #8170
