### ISSUE TITLE
Replace: Animax Japan (Vietnamese Subs) (720p)

### ISSUE THREAD

**Issue by xinomp** [iptv-org/iptv#6529]
### Stream Title

Animax Japan (Vietnamese Subs) (720p)

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/categories/animation.m3u

### Broken Link

https://livecdn.fptplay.net/hda3/animaxport_hls.smil/playlist.m3u8

### Notes

This Animax stream from the Animation Playlist category buffers every 3 seconds and I have to wait around 15 seconds for the stream to come back, only for it to buffer again 3 seconds later.

### Please confirm the following

- [ ] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Works quite correctly on my side, it's most certainly a bandwidth issue on your side

**Comment by xinomp** [comment]
> Works quite correctly on my side, it's most certainly a bandwidth issue on your side

I used both ProgDVB and VLC, and both had lots of buffering. And regarding my internet, I have 500mbps of download and 100mbps of upload, so I don't believe that's the issue.

**Comment by what-a** [comment]
Working fine for me here in California.

**Comment by xinomp** [comment]
> Working fine for me here in California.

Do you watch on mobile or Android Box (Nvidia Shield Pro for example)?

**Comment by what-a** [comment]
I'm on my home wi-fi using laptops (Windows and Linux).

**Comment by xinomp** [comment]
> I'm on my home wi-fi using laptops (Windows and Linux).

Dang. I've read some posts of people saying it may be the person's PC, so it may actually be something on my PC. Either way, I plan on buying an Nvidia Shield, so I hope such problem doesn't persist by then.

**Comment by LaneSh4d0w** [comment]
> > I'm on my home wi-fi using laptops (Windows and Linux).
> 
> Dang. I've read some posts of people saying it may be the person's PC, so it may actually be something on my PC. Either way, I plan on buying an Nvidia Shield, so I hope such problem doesn't persist by then.

Depending on your wifi/ethernet card this might be the cause indeed.

**Comment by xinomp** [comment]
> > > I'm on my home wi-fi using laptops (Windows and Linux).
> > 
> > 
> > Dang. I've read some posts of people saying it may be the person's PC, so it may actually be something on my PC. Either way, I plan on buying an Nvidia Shield, so I hope such problem doesn't persist by then.
> 
> Depending on your wifi/ethernet card this might be the cause indeed.

Well, since I have a very good internet connection and PC, it might be the ethernet card indeed. I'll troubleshoot it one day. Thanks for everything guys.
