### ISSUE TITLE
Malta playlist and broken links

### ISSUE THREAD

**Issue by angelosa** [iptv-org/iptv#653]
All EVO IPTV domain channels in [Malta playlist](https://github.com/iptv-org/iptv/blob/master/channels/mt.m3u) are just short looping videos, most of them with an advertising popup. 

Additionally they seems to be in _debug mode_ so nothing of value is lost here?

**Comment by freearhey** [comment]
Thank you for drawing attention to this. I've already removed these links from the main playlist and made a PR #656
