### ISSUE TITLE
Add: WFMZ 2 (Weather and Traffic Channel)

### ISSUE THREAD

**Issue by FpFan65** [iptv-org/iptv#6530]
### Channel Name

WFMZ 69.2 (Weather and Traffic Channel)

### Website

https://www.wfmz.com/content/tncms/live/

### Notes

You offered the stream once before.  Any chance of bringing it back?

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by MapGuy11** [comment]
Does this help? #6531
