### ISSUE TITLE
Add: Aniplus

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6533]
### Channel Name

Aniplus

### Website

none

### Stream URL

http://210.210.155.35/session/05ca7a1e-5492-11eb-901e-b82a72d63267/dr9445/h/h02/01.m3u8

### Notes

Its A Different Channel From Animax Or Not

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
It's this basically : http://210.210.155.35/dr9445/h/h02/01.m3u8
