### ISSUE TITLE
Remove: some RU channels

### ISSUE THREAD

**Issue by BlenderLietuva** [iptv-org/iptv#6534]
### Your full legal name

BlenderLietuva

### Are you the copyright holder or authorized to act on the copyright owner's behalf?

No.

### Please describe the nature of your copyright ownership or authorization to act on the owner's behalf.

In some countries certain Russian channel was removed or banned due the geopolitical situation Ukraine-Russia conflict.
The decision is based on the dissemination by Russian-language TV channels of prohibited information, including warmongering and disinformation.

The TTJA notes that all television service providers in Estonia are obliged to stop broadcasting the following television channels as soon as possible: RTR Planeta, NTV Mir, NTV Mir Baltic, Belarus 24 Russia 24 and TV Center International (TVCI).

Free reception of six propaganda Russian-language TV programmes in the territory of Lithuania has been suspended, says the Lithuanian Radio and Television Commission. Planeta RTR“, „Rossija 24“, „NTV Mir“ ir „Belarus 24“ for 5 years. „Pirmais Baltijas Kanals Lietuva“ („PBK“) and „TVCi“ for 3 years.

Despite all that, that channels still available in IPTV provider list

### Please provide a detailed description of the original copyrighted work that has allegedly been infringed. If possible, include a URL to where it is posted online.

https://www.lrt.lt/naujienos/pasaulyje/6/1625831/estijoje-stabdomas-virtines-rusijos-ir-baltarusijos-televizijos-kanalu-rodymas

https://sekunde.lt/leidinys/sekunde/uzdraude-rusisku-ir-baltarusisku-televizijos-kanalu-retransliavima/

https://www.diena.lt/naujienos/lietuva/salies-pulsas/cgates-jungiasi-prie-tv3-grupes-kanalu-iniciatyvos-netransliuoti-propagandines-rusu-televizijos-1065903

https://www.vz.lt/rinkodara/medijos/2022/02/22/telia-tv-nerodys-dalies-rusisku-kanalu

https://www.delfi.lt/login/technologijos/naujienos/25-rusisku-kanalu-nebelieka-skaitmenineje-televizijoje-telia-tv-pasigedo-skaidrumo-standartu.d?id=89522319

### What content should be removed? Please specify the URL for each item or, if it is an entire file, the file's URL.

RTR, NTV, NTV Mir, NTV Mir Baltic, Belarus 24, Russia 24, TVCI

### Please confirm the following

- [X] I have read and understand iptv-org's [Legal Statement](https://github.com/iptv-org/iptv#legal)

**Comment by freearhey** [comment]
The repository simply contains user-submitted links to publicly available video stream URLs. We have no control over the broadcasts of any channels. To remove this content from the web, you should contact the web host that's actually hosting the content.
