### ISSUE TITLE
Replace: La Red

### ISSUE THREAD

**Issue by ELProductions** [iptv-org/iptv#6538]
### Stream Title

playlist.m3u8

### What happened to the stream?

I see visual artifacts

### Playlist

https://unlimited1-us.dps.live/lared/lared.smil/playlist.m3u8

### Notes

It keeps glitching. Anyone can fix it? Thanks

### Please confirm the following

- [ ] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Try the chilean server alt : https://unlimited10-cl.dps.live/lared/lared.smil/playlist.m3u8

**Comment by ELProductions** [comment]
This one is glitching.

**Comment by LaneSh4d0w** [comment]
Then it is an issue from the channel itself, not the servers. The only thing to do is wait for those to get fixed.

**Comment by R4IN2007** [comment]
https://pantera1-100gb-cl-movistar.dps.live/lared/lared.smil/playlist.m3u8

**Comment by ELProductions** [comment]
This link is dead. please try a new one.

**Comment by R4IN2007** [comment]
This Link Works https://d2tr4gdfol9ja.cloudfront.net/lared/lared.smil/.m3u8
