### ISSUE TITLE
Add: Peace TV English

### ISSUE THREAD

**Issue by fawazahmed0** [iptv-org/iptv#6539]
### Channel Name

Peace TV English

### Channel ID

PeaceTVEnglish.ae

### Website

https://peacetv.tv/streaming/en

### Notes

 1. Go to https://peacetv.tv
 2. Sign In 
 user: `sileke5019@naluzotan.com`
 pass: `1234ABCDabcd`
3. Go to https://peacetv.tv/streaming/en

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://livestream.peacetv.tv/live/english.smil/playlist.m3u8
https://livestream.peacetv.tv/live/urdu.smil/playlist.m3u8
https://livestream.peacetv.tv/live/bangla.smil/playlist.m3u8
https://livestream.peacetv.tv/live/chinese.smil/playlist.m3u8

**Comment by fawazahmed0** [comment]
Yeah, but that doesn't seem to work at VLC

**Comment by LaneSh4d0w** [comment]
add #EXTVLCOPT:http-user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0

**Comment by fawazahmed0** [comment]
I tried adding the user agent option, but it still doesn't play.
![Screenshot (506)](https://user-images.githubusercontent.com/20347013/155905013-c034604f-3396-460f-8812-e7c9ef71ebe3.png)

**Comment by LaneSh4d0w** [comment]
> I tried adding the user agent option, but it still doesn't play. ![Screenshot (506)](https://user-images.githubusercontent.com/20347013/155905013-c034604f-3396-460f-8812-e7c9ef71ebe3.png)

I'll take a look.

**Comment by LaneSh4d0w** [comment]
OK, found out it asks for session data inside Key-Pair data.

**Comment by fawazahmed0** [comment]
> OK, found out it asks for session data inside Key-Pair data. Unfortunately, VLC does not support anything like that.
> 
> And I don't think I can make a tool that would "work like this"

Thanks for looking into it though

**Comment by freearhey** [comment]
Closed in favor of #11207
