### ISSUE TITLE
Replace: Guangzhou/Guangdong Channel (CN)

### ISSUE THREAD

**Issue by Polaris0112** [iptv-org/iptv#6544]
### Stream Title

广州新闻 (720p) [Timeout]

### What happened to the stream?

Other

### Playlist

https://github.com/iptv-org/iptv/blob/master/streams/cn.m3u

### Broken Link

http://116.199.5.52:8114/00000000/index.m3u8?Fsv_CMSID=&Fsv_SV_PARAM1=0&Fsv_ShiftEnable=0&Fsv_ShiftTsp=0&Fsv_chan_hls_se_idx=00&Fsv_cid=0&Fsv_ctype=LIVES&Fsv_ctype=LIVES&Fsv_filetype=1&Fsv_otype=1&Fsv_otype=1&Fsv_rate_id=0&FvSeid=5abd1660af1babb4&Pcontent_id=&Provider_id=

### Notes

I check a few channels in cn.m3u (about guangzhou/guangdong), but a lot of them is failed (I use tivimate), if someone can give a link that can see these  channels, I can grap the m3u link out and share.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Reference:
https://github.com/iptv-org/iptv/blob/7d9bbc7fb2c9a8f595acf0944c111d4d705ced39/streams/cn.m3u#L1510-L1511
