### ISSUE TITLE
Replace: CNBC USA

### ISSUE THREAD

**Issue by jhedfors** [iptv-org/iptv#6547]
### Stream Title

CNBC (1080p) [Not 24/7]

### What happened to the stream?

Stream no longer works.

### Playlist

https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us.m3u

### Broken Link

http://s1.mysportz.tv:2082/CNBC/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by jhedfors** [comment]
@MapGuy11 - This was not fixed with the above merge. Can this be re-opened?

**Comment by MapGuy11** [comment]
> @MapGuy11 - This was not fixed with the above merge. Can this be re-opened?

Done

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f64eccb9362a086387cc16c8164d5ad211a7e424/streams/us.m3u#L327-L328
