### ISSUE TITLE
How to use all in one

### ISSUE THREAD

**Issue by makolomuswaswa2019** [iptv-org/iptv#655]
Hello,

I need to know how to use all channels in one repository for kodi or all channels in one m3u URL for other plate-forms. 

Steve MM.

**Comment by krisu5** [comment]
Install "PVR IPTV Simple Client" from Kodi's official repo.

Howto guide: https://kodibeginner.com/setup-pvr-iptv-simple-client-kodi/

**Comment by makolomuswaswa2019** [comment]
Good Afternoon!

Thank you for your email. I needed rather to be able to access all channels
in one installation or repository. cCloud is nothing and The other is okay
but missing many countries and channels. I need something like
https://iptv-org.github.io/iptv/alliptv/alliptv.m3u (this is an example
that will allow me to access all your free channels listed here).

Thank you in advance for a new answer!

MM.

**Comment by freearhey** [comment]
@makolomuswaswa2019 Have you tried this playlist: https://iptv-org.github.io/iptv/index.m3u ?

**Comment by makolomuswaswa2019** [comment]
Thank you for your email. This is what I was looking for. That worked. You
are the man!

MM.
