### ISSUE TITLE
Fix: [CA] "TVA [Geo-blocked]" is marked as status="blocked" but the stream itself seems to play fine?

### ISSUE THREAD

**Issue by m-p-3** [iptv-org/iptv#6557]
### Describe your issue

https://github.com/iptv-org/iptv/blob/86f0990f39e687e2e1fa1e1727f314f06f959593/streams/ca.m3u#L186-L187

Not sure what's causing this, as I can play that playlist URL just fine in VLC, although it takes roughly 10-12 seconds to begin playback on my end.

This makes the channel invisible in my current IPTV app ([IPTVnator](/4gray/iptvnator)), any idea what can be done to remediate this? Thanks :D

**Comment by freearhey** [comment]
Please use this [form](https://github.com/iptv-org/iptv/issues/new?assignees=&labels=broken+stream&template=-----broken-stream.yml&title=Replace%3A+) to report problems with streams.

**Comment by m-p-3** [comment]
Alright, I wasn't sure if I had to use the form since the stream itself would play fine. Created #6558
