### ISSUE TITLE
Status="blocked" on TVA [Geo-blocked] (CA)

### ISSUE THREAD

**Issue by m-p-3** [iptv-org/iptv#6558]
### Stream Title

TVA [Geo-blocked]

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://iptv-org.github.io/iptv/countries/ca.m3u

### Broken Link

https://tvalive-nondai.akamaized.net/Content/HLS/Live/channel(a7315e07-037c-12a8-bdc8-da7bd513da9d)/index.m3u8

### Notes

Not sure what's causing this stream to not show up in my IPTV app, as I can play that playlist URL just fine in VLC, although it takes roughly 10-12 seconds to begin playback on my end.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by MapGuy11** [comment]
@freearhey I think we should not delete streams that are [Geo-Bloacked] as if I am correct the testing server is in the United States. I do have an available VM in Canada if you would like to start testing there also.

**Comment by trancer1994** [comment]
I've just tried to open the link using a Canadian proxy I am connected to in Halifax and I can confirm that the link does indeed work. Or at least opens.

**Comment by PD-TheKrazy0ne** [comment]
could try adding a forwarder option perhaps.... works on CBC streams, the link works fine for me in Canada..

**Comment by MapGuy11** [comment]
> I've just tried to open the link using a Canadian proxy I am connected to in Halifax and I can confirm that the link does indeed work. Or at least opens.

Could you put a picture as proof so I can send this over to the Admins.

**Comment by m-p-3** [comment]
I live in Canada, and the stream does indeed load with the URL provided (see screenshot).
![image](https://user-images.githubusercontent.com/3731432/156832659-11b9e049-01c3-44f2-81af-312db0a676d2.png)

**Comment by LaneSh4d0w** [comment]
Because it only works in Canada, nowhere else, hence the Geo-blocked tag.

**Comment by m-p-3** [comment]
Not sure why, but the some of the channels like the one I provided above weren't showing up in IPTVnator but now they do.

**Comment by barragh** [comment]
Hi, I don't know if this counts as the same problem but all the channels that are actually from my country (Ireland) are listed as Geoblocked (which is hilarious but still madness). This includes ones I can't get on TV here in this part of Ireland  but should work on IPtvnator. A lot of other ones are Geoblocked from outside Ireland (UK included) which is why I'm reporting this. Is there any fix for this yet?

**Comment by LaneSh4d0w** [comment]
> Hi, I don't know if this counts as the same problem but all the channels that are actually from my country (Ireland) are listed as Geoblocked (which is hilarious but still madness). This includes ones I can't get on TV here in this part of Ireland  but should work on IPtvnator. A lot of other ones are Geoblocked from outside Ireland (UK included) which is why I'm reporting this. Is there any fix for this yet?

Channels that are flagged as "Geo-blocked" means they work **only** in their country of origin. You shouldn't see any issues watching the channels from your country if you live there. Though someone else from another country won't be able to see it there.

**Comment by barragh** [comment]
> > Hi, I don't know if this counts as the same problem but all the channels that are actually from my country (Ireland) are listed as Geoblocked (which is hilarious but still madness). This includes ones I can't get on TV here in this part of Ireland  but should work on IPtvnator. A lot of other ones are Geoblocked from outside Ireland (UK included) which is why I'm reporting this. Is there any fix for this yet?
> 
> Channels that are flagged as "Geo-blocked" means they work **only** in their country of origin. You shouldn't see any issues watching the channels from your country if you live there. Though someone else from another country won't be able to see it there.

This is my main problem which I mentioned; I can't watch the channels from my own country in my own country (where I am right now) as IPtvnator says they are geoblocked. I don't know why as I'm not using a VPN unless this has something to do with Cloudflare, would that affect it?

**Comment by LaneSh4d0w** [comment]
> > 
> > Channels that are flagged as "Geo-blocked" means they work **only** in their country of origin. You shouldn't see any issues watching the channels from your country if you live there. Though someone else from another country won't be able to see it there.
> 
> This is my main problem which I mentioned; I can't watch the channels from my own country in my own country (where I am right now) as IPtvnator says they are geoblocked. I don't know why as I'm not using a VPN unless this has something to do with Cloudflare, would that affect it?

Do you mean IPTVnator doesn't want to launch the channels we've flagged as "geo-blocked" ? I guess if this is the case, you'll need to ask the developer of IPTVnator directly. It should normally work using VLC or another program of some sort.
