### ISSUE TITLE
Reelz Channel 

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6564]
### Channel Name

Reelz Channel 

### Website

tubitv.com

### Stream URL

https://live-news-manifest.tubi.video/live-news-manifest/csm/extlive/tubiprd01,Reelz.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by R4IN2007** [comment]
I Have Channel IDs For ADN 40, Video Rola, CONtv And More
tvg-id="adn40.mx" (ADN 40)
https://mdstrm.com/live-stream-playlist/60b578b060947317de7b57ac.m3u8
tvg-id="CONtv.us" (CONtv)
https://cinedigm.vo.llnwd.net/conssui/amagi_hls_data_xumo123-contv/CDN/master.m3u8
tvg-id="VideoRola.mx" (Video Rola)
https://d3b2epqdk0p7vd.cloudfront.net/out/v1/8a448b5e16384af4a3c8146a7b049c32/index.m3u8
tvg-id="HSN.us" (HSN)
https://html5-lh.akamaihd.net/i/html5_01@182967/master.m3u8
tvg-id="HSN2.us" (HSN 2)
https://hsn2html5-lh.akamaihd.net/i/hsn2html5_01@13178/master.m3u8

**Comment by LaneSh4d0w** [comment]
> I Have Channel IDs For ADN 40, Video Rola, CONtv And More tvg-id="adn40.mx" (ADN 40) https://mdstrm.com/live-stream-playlist/60b578b060947317de7b57ac.m3u8 tvg-id="CONtv.us" (CONtv) https://cinedigm.vo.llnwd.net/conssui/amagi_hls_data_xumo123-contv/CDN/master.m3u8 tvg-id="VideoRola.mx" (Video Rola) https://d3b2epqdk0p7vd.cloudfront.net/out/v1/8a448b5e16384af4a3c8146a7b049c32/index.m3u8 tvg-id="HSN.us" (HSN) https://html5-lh.akamaihd.net/i/html5_01@182967/master.m3u8 tvg-id="HSN2.us" (HSN 2) https://hsn2html5-lh.akamaihd.net/i/hsn2html5_01@13178/master.m3u8

1) Already in list if not mistaken
2) Stopped working a while ago
3) We may add this one
4 and 5) Need to reconfirm but I think we don't have those ones too.
