### ISSUE TITLE
Add: NBC 40 (WTWC-DT1)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6565]
### Channel Name

NBC 40 Tallahassee FL

### Stream URL

https://5e6cea03e25b6.streamlock.net/live/WTWC-NB.stream/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by what-a** [comment]
Already in the us.m3u playlist:

![image](https://user-images.githubusercontent.com/88639906/156418167-b7b5d774-f72c-4b8f-a7c4-e1090517e2d4.png)
