### ISSUE TITLE
Add: FOX 49 (WTWC-DT2)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6566]
### Channel Name

FOX 49 Tallahassee FL

### Stream URL

https://5e6cea03e25b6.streamlock.net/live/WTWC-FX.stream/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by what-a** [comment]
Already in the us.m3u playlist:

![image](https://user-images.githubusercontent.com/88639906/156418433-ccd4efc0-8895-4a85-9c72-430e0c1f0e74.png)
