### ISSUE TITLE
NBC 40 / FOX 49 News Channel

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6567]
### Channel Name

NBC 40 / FOX 49 News Channel

### Stream URL

https://content.uplynk.com/channel/aa92b664ac5941de81cd410803329da2.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by MapGuy11** [comment]
#6619
