### ISSUE TITLE
Add: Multimedios Saltillo [Geo-Blocked] (México)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6569]
### Channel Name

Multimedios Saltillo

### Stream URL

http://mdstrm.com/live-stream-playlist/5d5d51a4e9a40e25f4a0332c.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Geo-blocked ?

![image](https://user-images.githubusercontent.com/30985701/156426235-a43d2c2f-a467-45e8-968e-644f85afbe71.png)

Maybe for copyrighted content then.

**Comment by R4IN2007** [comment]
The m3u8 link doesn't work In The US, Only Using A VPN With A Mexico IP

**Comment by LaneSh4d0w** [comment]
> The m3u8 link doesn't work In The US, Only Using A VPN With A Mexico IP

I'm in France and it works
