### ISSUE TITLE
Replace: Fox Orlando FL (WOFL-DT)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6571]
### Channel Name

Fox 35 Orlando FL

### Channel ID

WOFLDT1.us

### Stream URL

http://stream2.grandma.fit/fox.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by what-a** [comment]
I'm familiar with the suggested stream URL. It is very unreliable. It will be up for 8 hours and then dead for 8 hours, etc.

**Comment by LaneSh4d0w** [comment]
It's a website that scrapes an Uplynk link, let me retrieve it.

**Comment by LaneSh4d0w** [comment]
There you go : https://content.uplynk.com/channel/316e62a0ef29470dbb4c617e1de2f99d.m3u8

**Comment by freearhey** [comment]
Broken link:
https://github.com/iptv-org/iptv/blob/13d2f470b7e5b647c0d24d4b6897c651d4b52971/streams/us.m3u#L1175-L1176

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/9912e705a140feb961a9286181482f3ac346242f/streams/us_tubi.m3u#L92-L93
