### ISSUE TITLE
Add: Fox 35 Orlando FL (News) [Tubi]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6572]
### Channel Name

Fox 35 Orlando FL

### Stream URL

https://csm-e-cetubiausw2live204-0aef371f4a85b9245.csm.tubi.video/csm/extlive/tubiprd01,p-WOFL-Monetizer.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by what-a** [comment]
Already exists in the us_tubi.m3u playlist:

![image](https://user-images.githubusercontent.com/88639906/156462095-c88f6606-d5f9-4f38-85bc-c2a83de55cbe.png)
