### ISSUE TITLE
Univision West (KDTV, SF,CA)

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#6576]
### Channel Name

KDTV-CD1

### Channel ID

KDTVDT1.us

### Stream URL

 https://dai.google.com/linear/hls/event/lTSACKfkQNSrCSBM_hE-mg/master.m3u8

### Notes

Maybe [US IP Only]
Country : "USA San Francisco,CA"

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Central302** [comment]
Thanks, It Looks Like URL is Geo-Blocked to US.

**Comment by LaneSh4d0w** [comment]
> Playing fine for me in California.
> An example of the stream URL when playing is:
> https://unidfpclnlds167.akamaized.net/linear/hls/pa/event/lTSACKfkQNSrCSBM_hE-mg/stream/6caf0ad0-0998-4366-8c90-6b50687ff712:DLS/variant/5b5cc4d304da9e4b5173b8ce85322a4e/bandwidth/4500000.m3u8?hdntl=exp=1646414111~acl=*~id=c0abead9-64b6-4192-bb29-0f9a8c12d36e~data=hdntl~hmac=3e85eab12734f46985f52d1e23d73b635637b0f22707454f57da052c2c567988

Noted, thanks. Sounds like you could replace the akamaized.net name to dai.google.com and it still would work. Thought it had an identifier inside it, but all the Univision links are like that it seems.

**Comment by MapGuy11** [comment]
Works it redirects you to a tokenized akamai link: 
![image](https://user-images.githubusercontent.com/43685307/156669793-d2ba52ae-24c9-4251-9a4a-8765274dbd46.png)
