### ISSUE TITLE
Add: Sony SAB

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6577]
### Channel Name

Sony SAB

### Stream URL

http://103.72.179.30:1935/GECHindi/SONY_SAB.stream_720p/Playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Adaptive should be http://103.72.179.30:1935/GECHindi/SONY_SAB.stream/Playlist.m3u8
