### ISSUE TITLE
Add: ABC Localish [Tubi]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6579]
### Channel Name

ABC Localish

### Website

tubitv.com

### Stream URL

https://live-news-manifest.tubi.video/live-news-manifest/csm/extlive/tubiprd01,Localish.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
<img width="757" alt="image" src="https://user-images.githubusercontent.com/7253922/158996647-69591c56-077f-40bd-a7c0-8a866fbe6ecf.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/52c6ef2265296c5672250ba00c97db9d0431ff53/streams/us_tubi.m3u#L42-L43
