### ISSUE TITLE
Replace: All 51.79.193.108 streams

### ISSUE THREAD

**Issue by man-im-unoriginal-af** [iptv-org/iptv#6580]
### Stream Title

NHK G Tokyo (720p) [Not 24/7]

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/countries/jp.m3u

### Broken Link

http://51.79.193.108/*

### Notes

404 Error on all streams related to the address.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by luongz** [comment]
They change the IP and tokened the link. I can not solved the real link is so here

http://51.79.193.109:8080/hlsok/j00033/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp

**Comment by Nobodynumber1** [comment]
> They change the IP and tokened the link. I can not solved the real link is so here
> 
> http://51.79.193.109:8080/hlsok/j00033/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp

Thanks you for help.
Powerful.

I had checked and add tv icon on it.
as below:

#EXTINF:-1 tvg-id="ATX.jp" tvg-country="JP" tvg-language="Japanese" tvg-logo="https://www.at-x.com/favicon_android.png" group-title="Animation",AT-X (720p)
http://51.79.193.109:8880/hlsok/j00052/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp
#EXTINF:-1 tvg-id="ATX.jp" tvg-country="JP" tvg-language="Japanese" tvg-logo="https://www.at-x.com/favicon_android.png" group-title="Animation",AT-X (720p)
http://51.79.193.109:8880/hls/j00052/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp


#EXTINF:-1 tvg-id="ABC.jp" tvg-name="ABC" tvg-country="JP" tvg-language="Japanese" tvg-logo="https://img.isuper.tv/live-tv/jp-tv/jp-abc-live.jpg" group-title="Japan",Asahi Broadcasting Corporation
http://51.79.193.109:8880/hlsok/j00053/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp


#EXTINF:-1 tvg-id="SKYA.jp" tvg-name="SKY A" tvg-country="JP" tvg-language="Japanese" tvg-logo="https://americanfootball.jp/japan/sky_a.jpg" group-title="Japan", スカイA (Sky-A)
http://51.79.193.109:8880/hlsok/j00020/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp

#EXTINF:-1 tvg-id="SUN.jp" tvg-name="SUN" tvg-country="JP" tvg-language="Japanese" tvg-logo="https://upload.wikimedia.org/wikipedia/zh/thumb/0/0b/SUN_TV_logo.png/220px-SUN_TV_logo.png" group-title="Japan", SUN
http://51.79.193.109:8880/hlsok/j00021/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp

#EXTINF:-1 tvg-id="YTV.jp" tvg-name="YTV" tvg-country="JP" tvg-language="Japanese" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Yomiuri_Telecasting_Corporation_Logo.svg/1200px-Yomiuri_Telecasting_Corporation_Logo.svg.png" group-title="Japan", YTV 読売テレビ
http://51.79.193.109:8880/hlsok/j00007/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp

#EXTINF:-1 tvg-id="HomeDramaChannel.jp" tvg-name="HDC" tvg-country="JP" tvg-language="Japanese" tvg-logo="https://prtimes.jp/i/6470/11/ogp/d6470-11-639609-0.jpg" group-title="Japan", ホームドラマチャンネル (Home Drama Channel)
http://51.79.193.109:8880/hlsok/j00009/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp

#EXTINF:-1 tvg-id="BSAsahi.jp" tvg-name="BS Asahi" tvg-country="JP" tvg-language="Japanese" tvg-logo="https://company.tv-asahi.co.jp/saiyo/group/img/company/logo-bsasahi.png" group-title="Japan",BS Asahi
http://51.79.193.109:8880/hlsok/j00048/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp

#EXTINF:-1 tvg-id="BSFujiBS181.jp" tvg-name="BS Fuji (BS181)" tvg-country="JP" tvg-language="Japanese" tvg-logo="https://www.zne-iptv.com/wp-content/uploads/2017/10/22-BS-FUJI-770x480.jpg" group-title="Japan",BS Fuji (BS181)
http://51.79.193.109:8880/hlsok/j00049/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp

#EXTINF:-1 tvg-id="BSTVTokyoBS171.jp" tvg-name="BS TV Tokyo (BS171)" tvg-country="JP" tvg-language="Japanese" tvg-logo="https://tv-tokyo.imgix.net/information/blog/images/2604bab3907f11e8808dcbdce0444b13.jpg" group-title="Japan",BS TV Tokyo (BS171)
http://51.79.193.109:8880/hlsok/j00050/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp



#EXTINF:-1 tvg-id="KNTV.jp" tvg-name="関西テレビ" tvg-country="JP" tvg-language="" tvg-logo="https://img.isuper.tv/live-tv/jp-tv/jp-ktv-live.jpg" group-title="Japan",関西テレビ
http://51.79.193.109:8880/hlsok/j00006/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp
#EXTINF:-1 tvg-id="NitteleGPlus.jp" tvg-name="NTV G+ (日テレジータス)" tvg-country="JP" tvg-language="" tvg-logo=https://upload.wikimedia.org/wikipedia/commons/5/59/Nittele_G%2B_logo.svg" group-title="Japan",NTV G+ (日テレジータス)
http://51.79.193.109:8880/hlsok/j00005/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp
#EXTINF:-1 tvg-id="BSNipponTV.jp" tvg-name="BS 日テレ" tvg-country="JP" tvg-language="" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/BS4_logo.svg/400px-BS4_logo.svg.png" group-title="Japan",BS 日テレ
http://51.79.193.109:8880/hlsok/j00047/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp

#EXTINF:-1 tvg-id="BSTBS.jp" tvg-name="BS-TBS" tvg-country="JP" tvg-language="Japanese" tvg-logo="https://pbs.twimg.com/profile_images/1260862250295812096/a6-UyLc__400x400.jpg" group-title="Japan",BS-TBS
http://51.79.193.109:8880/hlsok/j00051/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp


#EXTINF:-1 tvg-id="NHKGeneralTV.jp" tvg-name="NHK General TV" tvg-country="JP" tvg-language="Japanese" tvg-logo="http://tv.itver.cc/wp-content/uploads/2014/09/NHK-General-TV.jpg" group-title="Japan",NHK General TV
http://51.79.193.109:8880/hlsok/j00033/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp


#EXTINF:-1 tvg-id="NHKGeneralTV.jp" tvg-name="NHK General TV OSA" tvg-country="JP" tvg-language="Japanese" tvg-logo="http://tv.itver.cc/wp-content/uploads/2014/09/NHK-General-TV.jpg" group-title="Japan",NHK General TV OSA
http://51.79.193.109:8880/hlsok/j00032/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp
