### ISSUE TITLE
Replace: RT en Español (And all the other ones)

### ISSUE THREAD

**Issue by diestro123** [iptv-org/iptv#6581]
### Stream Title

RTenEspañol

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/index.m3u

### Broken Link

https://rt-esp.gcdn.co/live/rtesp/playlist.m3u8

### Possible Replacement

https://rt-esp.rttv.com/live/rtesp/playlist_4500Kb.m3u8

### Notes

All the other streams of RT are broken, need to replace it.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Most certainly due to recent issues concerning Europe & Russia.

I'll check.

**Comment by fotvnetwork** [comment]
All of their streams are here:
https://www.rt.com/on-air/rt-player/

**Comment by LaneSh4d0w** [comment]
https://rt-esp.rttv.com/live/rtesp/playlist.m3u8
https://rt-glb.rttv.com/live/rtnews/playlist.m3u8
https://rt-uk.rttv.com/live/rtuk/playlist.m3u8
https://rt-fra.rttv.com/live/rtfrance/playlist.m3u8
https://rt-arb.rttv.com/live/rtarab/playlist.m3u8
https://rt-rtd.rttv.com/live/rtdoc/playlist.m3u8
https://hls.rt.com/hls/rtdru.m3u8

**Comment by diestro123** [comment]
It seems none of the streams worked from the EU

**Comment by LaneSh4d0w** [comment]
Almost sure it's because Russia banned European citizens for watching RT, following the recent bans and sanctions.

**Comment by diestro123** [comment]
It is,but at the same time,the RT english stream is working well. It seems like is specifically spanish stream which doesn’t work

**Comment by fotvnetwork** [comment]
Rumble feed:
https://rumble.com/c/RTNews

**Comment by freearhey** [comment]
Fixed via #6741
