### ISSUE TITLE
Add: CNN

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6586]
### Channel Name

CNN

### Stream URL

https://cnn-cnninternational-1-eu.rakuten.wurl.com/manifest/playlist_1280x720_3000k.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://cnn-cnninternational-1-eu.rakuten.wurl.com/manifest/playlist.m3u8 Adaptive, verified, works.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1d5ac2cfd591466086b3f97fc403163e45b16a74/streams/es_rakuten.m3u#L10-L11
