### ISSUE TITLE
Add: Fox Sports En Espanol

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6592]
### Channel Name

Fox Sports En Espanol

### Website

tubitv.com

### Stream URL

https://live-news-manifest.tubi.video/live-news-manifest/csm/extlive/tubiprd01,Fox-Sports-Espanol2.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
DMCA'd.

See https://github.com/iptv-org/database/blob/master/data/blocklist.csv#L386
