### ISSUE TITLE
Add: Fox Sports Premium | (Argentina)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6593]
### Channel Name

Fox Sports Premium 

### Stream URL

https://edge-live32-sl.cvattv.com.ar/live/c3eds/Fox_Sports_Premiun_HD/SA_SAGEMCOM/Fox_Sports_Premiun_HD.m3u8?NoxusPlus+.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://edge-live32-sl.cvattv.com.ar/live/c3eds/Fox_Sports_Premiun_HD/SA_SAGEMCOM/Fox_Sports_Premiun_HD.m3u8 No need for tagging in names. Works.

**Comment by LaneSh4d0w** [comment]
... but i'll also need to close it, for DMCA measures.

See https://github.com/iptv-org/database/blob/master/data/blocklist.csv#L386

**Comment by Nicolas1307** [comment]
No funciona :(
