### ISSUE TITLE
Add: TNT East

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6596]
### Channel Name

TNT East

### Stream URL

https://tve-live-lln.warnermediacdn.com/hls/live/2023168/tnteast/slate/VIDEO_0_3564000.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by what-a** [comment]
Already exists in the us.m3u playlist.

![image](https://user-images.githubusercontent.com/88639906/156870723-6408a256-ac6a-4039-a27d-053ce691f53e.png)
