### ISSUE TITLE
VPOD TV

### ISSUE THREAD

**Issue by trancer1994** [iptv-org/iptv#6597]
### Channel Name

VPOD TV

### Channel ID

VPODTV.us

### Website

https://www.vpodtv.com

### Stream URL

https://81988.global.ssl.fastly.net/6054f2db9a679c037cbbb2b2/live_7749cbc088e711eb99623595db260c33/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
<img width="754" alt="image" src="https://user-images.githubusercontent.com/7253922/158995954-94ce6fd6-8262-4e18-bfb8-eee181c66fcb.png">

**Comment by freearhey** [comment]
https://81988.global.ssl.fastly.net/6054f2db9a679c037cbbb2b2/live_7749cbc088e711eb99623595db260c33/index.m3u8
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/7253922/190885726-e9d1cf1e-4474-4c89-b35a-b047c67abefb.png">

**Comment by Alstruit** [comment]
Closing.
https://github.com/iptv-org/iptv/blob/12e598f2fac46d5737fb0f1ae016a89153010153/streams/us.m3u#L1262-L1263
