### ISSUE TITLE
Replace: CP24 (Toronto News)

### ISSUE THREAD

**Issue by WaQoYi** [iptv-org/iptv#6598]
### Channel Name

CP24

### Channel ID

CP24

### Website

https://www.cp24.com/

### Stream URL

https://iptv-org.github.io/iptv/countries/ca.m3u

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
The broken link has been removed from the playlist.

Closed in favor: #8169
