### ISSUE TITLE
PBS Boston MA (WGBH) 

### ISSUE THREAD

**Issue by WaQoYi** [iptv-org/iptv#6599]
### Channel Name

GBH

### Channel ID

WGBHDT1.us

### Website

https://www.wgbh.org/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
There's something up in https://www.wgbh.org/channel-2-live-stream however I'm not from the US and it asks for localisation.

**Comment by MapGuy11** [comment]
drm'ed just like all of PBS

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/cac2f96962f43fcec08d835b0878ed36307d4bbe/streams/us_pbs.m3u#L144-L145
