### ISSUE TITLE
Fox Sports 2 (Italy)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6601]
### Channel Name

Fox Sports 2

### Stream URL

http://170.82.200.38:8080/fox_sports_2/tracks-v1a1/mono.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by what-a** [comment]
http://170.82.200.38:8080/fox_sports_2/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
DMCAd. See https://github.com/iptv-org/database/blob/master/data/blocklist.csv
