### ISSUE TITLE
Add: NBC 5 Memphis, TN (WMC)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6608]
### Channel Name

NBC 5 Memphis, TN 

### Channel ID

WMCDT1.us

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Central302** [comment]
https://www.actionnews5.com/livestream/ ,
Gray Television, AWS Server. (Access Token)

**Comment by LaneSh4d0w** [comment]
https://dai2-playlistserver.aws.syncbak.com/media.m3u8?bitrate=3659760&session=3e0fb7eb09a174a12fc0c0e9bd54cdfb ?

**Comment by freearhey** [comment]
https://dai2-playlistserver.aws.syncbak.com/playlist/18497172/master.m3u8?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkdyYXkyMDE2MDgyOSJ9.eyJtaWQiOiIxODQ5NzE3MiIsIm1kNSI6IjYzOWYxNjJjOTZjZjJmZWFmYjQ1YWY1NTA4MzhmMGQ4IiwiaWF0IjoxNTk0MDU4Mjc4LCJpc3MiOiJTeW5jYmFrIChURykifQ.m34pXxraDlVLkgkAtFOwXbZ4DqUaAXQjOrumoMi2Fso
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/7253922/232225604-e082be21-debb-4c15-9f22-1cc40732d801.png">
