### ISSUE TITLE
Main playlists not updating

### ISSUE THREAD

**Issue by themak1985** [iptv-org/iptv#661]
https://iptv-org.github.io/iptv/index.full.m3u (grouped by country and category)
https://iptv-org.github.io/iptv/index.country.m3u (grouped by country)
https://iptv-org.github.io/iptv/index.category.m3u (grouped by category)
https://iptv-org.github.io/iptv/index.language.m3u (grouped by language)
https://iptv-org.github.io/iptv/index.m3u

All have not updated in atleast 5 days.

**Comment by themak1985** [comment]
Actually I wonder if its all the playlists - for example - arabic should have 389 channels - but the playlist only has 287

**Comment by freearhey** [comment]
You're absolutely right, something's wrong. I'll try to figure out exactly what it is like to have free time and then publish the updated playlists.

**Comment by themak1985** [comment]
Thanks for all your work on this @freearhey - I wish you all the free time in the world.  😉

**Comment by freearhey** [comment]
I think I found out what the problem was and I've already published the corrected version. Please try it now.

**Comment by themak1985** [comment]
@freearhey Looks to have updated. Thanks!

**Comment by freearhey** [comment]
Unfortunately, the problem hasn't disappeared and the playlist isn't being updated again. I'm already working on a solution, but I've decided to reopen this issue to keep everyone informed.

**Comment by freearhey** [comment]
Details: https://github.community/t5/GitHub-Pages/Cannot-Build-Page/m-p/37618

**Comment by freearhey** [comment]
It seems that the problem with automatic updating of playlists was finally solved and now everything should work fine. But if something changes again, I will let you know.
