### ISSUE TITLE
Add: RASD TV

### ISSUE THREAD

**Issue by TVSquisher** [iptv-org/iptv#6611]
### Channel Name

RASHTV

### Channel ID

rashtv.eh

### Website

rasd.tv

### Stream URL

https://cloud.streamingconnect.tv:455/rasdtv/rasdtv.m3u8

### Notes

Western Sahara Channel

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Not something we often see. Works.
