### ISSUE TITLE
KITV 4 Honolulu HI

### ISSUE THREAD

**Issue by PluHibiscus** [iptv-org/iptv#6615]
### Channel Name

KITV 4 Island Television

### Channel ID

KITVDT1.us

### Website

https://www.kitv.com/livestream/

### Stream URL

https://fuel-streaming-prod01.fuelmedia.io/v1/sep/34ca5b92-ae1b-4480-bd04-3dfc37b717bc/3500K720AWS/SM/content.m3u8

### Notes

I'm new to finding m3u8 urls, but this one I've been having trouble with, I think the stream/url might reset/change after x number of hours. Hopefully someone with more experience can find a stable continuous stream.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://fuel-streaming-prod01.fuelmedia.io/v1/sem/c4067ddc-0e67-4928-b7ec-624481f721a6.m3u8

**Comment by MapGuy11** [comment]
#6619
