### ISSUE TITLE
Add: CBS (WCBI)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6616]
### Channel Name

CBS (WCBI)

### Stream URL

https://dai.google.com/linear/hls/event/qLrnhs3RQUa2zMw9UBkroQ/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://wcbi.akamaized.net/hls/live/2029583/WCBI_INGEST/master.m3u8

**Comment by MapGuy11** [comment]
#6619
