### ISSUE TITLE
Add: News4Jax+ (WJXT)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6617]
### Channel Name

News4Jax (WJXT)

### Stream URL

https://dai.google.com/linear/hls/event/RDmbn03GRCOLNG1eetEKhg/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by MapGuy11** [comment]
#6619
