### ISSUE TITLE
Add: Unimás [Univision]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6624]
### Channel Name

Unimás

### Stream URL

https://dai.google.com/linear/hls/event/fQCAqHLkSPeYW0FmDm7aOQ/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Central302** [comment]
close the issue. (already added in https://github.com/iptv-org/iptv/pull/6585)
