### ISSUE TITLE
Broken Stream: True Premier Football HD 1

### ISSUE THREAD

**Issue by pukozs75** [iptv-org/iptv#6632]
### Stream Title

True Premier Football HD 1 (720p) [Not 24/7]

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/categories/sports.m3u

### Notes

All of True Premier Football and True sports channels don't work

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
I don't think they'll be back anytime soon.

**Comment by freearhey** [comment]
Duplicate #6520
