### ISSUE TITLE
Add: TNT West

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6633]
### Channel Name

TNT West

### Stream URL

https://tve-live-lln.warnermediacdn.com/hls/live/2023170/tntwest/slate/VIDEO_0_3564000.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://tve-live-lln.warnermediacdn.com/hls/live/2023170/tntwest/slate/master.m3u8 ?

**Comment by Central302** [comment]
Already in Playlist, Close The Issue.
