### ISSUE TITLE
Replace: Contacto Deportivo

### ISSUE THREAD

**Issue by pukozs75** [iptv-org/iptv#6635]
### Stream Title

Contacto Deportivo (720p) [Not 24/7]

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://iptv-org.github.io/iptv/categories/sports.m3u

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/552de94eed297776b2e5a49a006e5503533f56e7/streams/pe.m3u#L72-L73

<img width="640" alt="image" src="https://user-images.githubusercontent.com/7253922/159475609-d85c1cac-3827-4a26-916a-0ac0c48b041d.png">
