### ISSUE TITLE
Add: BVN

### ISSUE THREAD

**Issue by peaking2** [iptv-org/iptv#6639]
### Channel Name

BVN

### Channel ID

BVN.nl

### Website

https://www.bvn.tv/bvnlive/

### Notes

I had checked NL and BE stream lists but it wasn't listed there. I don't remember seeing it in the list.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
DRMed.

https://npobvn-prd.cdn.eurovisioncdn.net/live/npo/u/npo/drm/hls_fairplay/bvn/0/0/0/bvn.isml/playlist.m3u8

https://s3-eu-west-1.amazonaws.com/24i-npo-stream/fairplay.cer

https://npo-drm-gateway.samgcloud.nepworldwide.nl/authentication?custom_data=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJucG8iLCJpYXQiOjE2NDY3MjYzMjEsImRybV90eXBlIjoiZmFpcnBsYXkiLCJsaWNlbnNlX3Byb2ZpbGUiOiJ3ZWIiLCJjbGllbnRfaXAiOiIxOTUuMjUuODYuMTYxIn0.Wdf4LVZlQn_dMouqCJpU99Ed2fUswyzx0wbpr0jkzhs

**Comment by AntiPontifex** [comment]
Dead issue: please close.

**Comment by freearhey** [comment]
https://dumdumbullet.com/1011454237/dBHD6irSLV/79992129058
<img width="789" alt="image" src="https://user-images.githubusercontent.com/7253922/234012994-c2c5b87e-6f93-466b-a845-b003050d88a6.png">

**Comment by kaikyoofers** [comment]
> https://dumdumbullet.com/1011454237/dBHD6irSLV/79992129058 <img alt="image" width="789" src="https://user-images.githubusercontent.com/7253922/234012994-c2c5b87e-6f93-466b-a845-b003050d88a6.png">

Wait, is xtream servers allowed now?

**Comment by BellezaEmporium** [comment]
it's not a question of "allowed/not allowed". they're often illegal sources that aren't stable over time.

**Comment by kaikyoofers** [comment]
> it's not a question of "allowed/not allowed". they're often illegal sources that aren't stable over time.

You said before that xtream servers are not allowed

**Comment by BellezaEmporium** [comment]
yes, i consider them as not allowed due to the source, but there's no official classification of those streams.

**Comment by freearhey** [comment]
@kaikyoofers __BellezaEmporium__ has nothing to do with it, it's my mistake. I do not know how to distinguish between normal links and xtream, so I marked the issue incorrectly.

**Comment by kaikyoofers** [comment]
Xtream url are with username and password in the url

Em qua., 26 de abr. de 2023 15:45, Aleksandr Statciuk <
***@***.***> escreveu:

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/nl.m3u#L28-L29
