### ISSUE TITLE
Add: Vice Channel 

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6640]
### Channel Name

VICE

### Stream URL

https://d2do1g43aq7264.cloudfront.net/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
US, contains closed captions for the impaired. Works.

**Comment by trancer1994** [comment]
Official feed?

**Comment by LaneSh4d0w** [comment]
> Official feed?

It "seems".
