### ISSUE TITLE
Replace: Anime Zone TV

### ISSUE THREAD

**Issue by Wolfmasternas** [iptv-org/iptv#6642]
### Stream Title

Anime zone tv

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://iptv-org.github.io/iptv/index.category.m3u

### Broken Link

http://azxtv.com/hls/stream.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Fox Kids Latino : http://foxkidsjahh20.duckdns.org/hls/stream/index.m3u8
Jetix Latino : http://jetixjahh20.duckdns.org/hls/stream/index.m3u8
Anime Zone TV LA : http://locomotiontv.com/envivo/xtv/m3u

**Comment by LaneSh4d0w** [comment]
Interestingly enough it says : Sorry can't allow you access today

**Comment by Wolfmasternas** [comment]
> Fox Kids Latino : http://foxkidsjahh20.duckdns.org/hls/stream/index.m3u8 Jetix Latino : http://jetixjahh20.duckdns.org/hls/stream/index.m3u8 Anime Zone TV LA & Locomotion TV : http://locomotiontv.com/envivo/xtv/m3u

**Comment by EddieBrockk** [comment]
Can we get new link of 
Fox Kids Latino , Jetix Latino , Anime Zone TV LA & Locomotion TV !?
