### ISSUE TITLE
G4 Select (Pluto TV US)

### ISSUE THREAD

**Issue by Lucas-mother3** [iptv-org/iptv#6643]
### Channel Name

G4

### Notes

Not much that I know but I heard G4 is coming to Pluto TV

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Central302** [comment]
https://pluto.tv/en/live-tv/g4-select

https://service-stitcher-ipv4.clusters.pluto.tv/v2/stitch/hls/channel/61e718a821a4d20007c608ff/master.m3u8?advertisingId=&appName=web&appVersion=5.109.0-6577a51c82bdba0d9a0a2bab4950dd43d469ea83&app_name=web&clientDeviceType=0&clientID=ba98af36-74bc-4713-8716-8fdd0164b176&clientModelNumber=1.0.0&country=US&deviceDNT=false&deviceId=ba98af36-74bc-4713-8716-8fdd0164b176&deviceLat=41.8874&deviceLon=-87.6318&deviceMake=firefox&deviceModel=web&deviceType=web&deviceVersion=97.0.0&marketingRegion=US&serverSideAds=true&sessionID=abbcfe3b-9ec3-11ec-ab1f-0242ac110003&sid=abbcfe3b-9ec3-11ec-ab1f-0242ac110003&userId=&jwt=eyJhbGciOiJIUzI1NiIsImtpZCI6ImFmMjgwMzYwLWU1ZmUtNGUwNC05YzUxLTM5MWY3NDNmY2RjNSIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSUQiOiJhYmJjZmUzYi05ZWMzLTExZWMtYWIxZi0wMjQyYWMxMTAwMDMiLCJjbGllbnRJUCI6IjE1NC42LjIwLjE1OSIsImNpdHkiOiJDaGljYWdvIiwicG9zdGFsQ29kZSI6IjYwNjAyIiwiY291bnRyeSI6IlVTIiwiZG1hIjo2MDIsImFjdGl2ZVJlZ2lvbiI6IlVTIiwiZGV2aWNlTGF0Ijo0MS44ODc0LCJkZXZpY2VMb24iOi04Ny42MzE4LCJwcmVmZXJyZWRMYW5ndWFnZSI6ImphIiwiZGV2aWNlVHlwZSI6IndlYiIsImRldmljZVZlcnNpb24iOiI5Ny4wLjAiLCJkZXZpY2VNYWtlIjoiZmlyZWZveCIsImRldmljZU1vZGVsIjoid2ViIiwiYXBwTmFtZSI6IndlYiIsImFwcFZlcnNpb24iOiI1LjEwOS4wLTY1NzdhNTFjODJiZGJhMGQ5YTBhMmJhYjQ5NTBkZDQzZDQ2OWVhODMiLCJjbGllbnRJRCI6ImJhOThhZjM2LTc0YmMtNDcxMy04NzE2LThmZGQwMTY0YjE3NiIsImNtQXVkaWVuY2VJRCI6IiIsImlzQ2xpZW50RE5UIjpmYWxzZSwidXNlcklEIjoiIiwibG9nTGV2ZWwiOiJERUZBVUxUIiwidGltZVpvbmUiOiJBbWVyaWNhL0NoaWNhZ28iLCJzZXJ2ZXJTaWRlQWRzIjp0cnVlLCJlMmVCZWFjb25zIjpmYWxzZSwiZmVhdHVyZXMiOnsiYWRMb2FkIjp7ImNvaG9ydCI6IjMifX0sImZtc1BhcmFtcyI6eyJmd1ZjSUQyIjoiWGk2Mzk1dndGQ2N3enVON1VwY3VpY252SDdvMlJPVHJqWUVRcnlxU0YzZXNfT0p0NEZseDdCV0FoTmJkWWVLejB4SVVsYSIsImZ3VmNJRDJDb3BwYSI6ImJhOThhZjM2LTc0YmMtNDcxMy04NzE2LThmZGQwMTY0YjE3NiIsImN1c3RvbVBhcmFtcyI6eyJmbXNfbGl2ZXJhbXBfaWRsIjoiIiwiZm1zX2VtYWlsaGFzaCI6IiIsImZtc19zdWJzY3JpYmVyaWQiOiIiLCJmbXNfaWZhIjoiIiwiZm1zX2lkZnYiOiIiLCJmbXNfdXNlcmlkIjoiYmE5OGFmMzYtNzRiYy00NzEzLTg3MTYtOGZkZDAxNjRiMTc2IiwiZm1zX3ZjaWQydHlwZSI6ImxpdmVyYW1wIiwiZm1zX3JhbXBfaWQiOiJYaTYzOTV2d0ZDY3d6dU43VXBjdWljbnZIN28yUk9UcmpZRVFyeXFTRjNlc19PSnQ0Rmx4N0JXQWhOYmRZZUt6MHhJVWxhIiwiZm1zX2hoX3JhbXBfaWQiOiJVTk1BVENIRUQifX0sImF1ZCI6IioucGx1dG8udHYiLCJleHAiOjE2NDY3NjExNzcsImp0aSI6ImJkNDdmMjcyLWJjMzUtNDhhYy05ZmY5LWM0YTBkN2QyMDIzNCIsImlhdCI6MTY0NjczMjM3NywiaXNzIjoiYm9vdC5wbHV0by50diIsInN1YiI6InByaTp2MTpwbHV0bzpkZXZpY2VzOlVTOlltRTVPR0ZtTXpZdE56UmlZeTAwTnpFekxUZzNNVFl0T0daa1pEQXhOalJpTVRjMiJ9.SeDM0_DD0acOMqC3upjpEdHjLjTOoaNFmPP9WtKD3GY&masterJWTPassthrough=true

**Comment by spotanjo3** [comment]
Link is dead.

**Comment by Lucas-mother3** [comment]
@Central302 update link

**Comment by Central302** [comment]
or https://siloh-ns1.plutotv.net/lilo/production/G4EN/master.m3u8

**Comment by spotanjo3** [comment]
Yeah.. It's working. Thank you.

**Comment by Lucas-mother3** [comment]
EPG guide (please add this to the epg repo): https://i.mjh.nz/PlutoTV/
