### ISSUE TITLE
Add: Cartoon Network Asia

### ISSUE THREAD

**Issue by Lucas-mother3** [iptv-org/iptv#6646]
### Channel Name

Cartoon Network Asia 

### Channel ID

CartoonNetworkAsia.sg

### Notes

Cartoon Network Asia feed

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Lucas-mother3** [comment]
bump

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/cac2f96962f43fcec08d835b0878ed36307d4bbe/streams/us.m3u#L259-L260
