### ISSUE TITLE
Add: Kapamilya Channel 

### ISSUE THREAD

**Issue by Lucas-mother3** [iptv-org/iptv#6648]
### Channel Name

Kapamilya Channel 

### Website

https://iwant.tv

### Notes

A stream available on iWant TFC. 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3d9cce39dfcfe101ef2ff6e6a7f3f8ddd8ceb1c6/streams/ph.m3u#L16-L17

**Comment by Lucas-mother3** [comment]
> https://github.com/iptv-org/iptv/blob/3d9cce39dfcfe101ef2ff6e6a7f3f8ddd8ceb1c6/streams/ph.m3u#L16-L17

Non-working stream, I checked on VLC, hls.js and mpv-android.
