### ISSUE TITLE
Add: Fox Türkiye (Turkey)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6651]
### Channel Name

FOX

### Channel ID

FoxTurkey.tr

### Website

https://www.fox.com.tr/canli-yayin

### Stream URL

https://foxtv-live-ad.ercdn.net/foxtv/playlist.m3u8?st=xPtqXnSXUVYLl1PQhLiDsQ&e=1646753757

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Unfortunately, the link generated expires in 2 hours.

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.fox.com.tr/canli-yayin
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/7253922/190885945-6f5c30b4-ec20-4215-9b81-fc22daba0a08.png">

**Comment by R4IN2007** [comment]
This m3u8 Link Works Yall Can Use This Instead
https://foxtv.blutv.com/blutv_foxtv_live/live.m3u8
