### ISSUE TITLE
Add: FOX HD | (Russia)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6652]
### Channel Name

FOX HD

### Stream URL

https://sc.id-tv.kz/FOX_HD_34_35.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Adaptive : https://sc.id-tv.kz/FOX_HD.m3u8
