### ISSUE TITLE
Add: CINEMAX HD | (Asia)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6655]
### Channel Name

CINEMAX HD

### Channel ID

CinemaxAsia.sg

### Stream URL

https://livecdn.fptplay.net/hda1/cinemax_hls.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by spotanjo3** [comment]
It isn't working

**Comment by R4IN2007** [comment]
Try https://vips-livecdn.fptplay.net/hda1/cinemax_hls.smil/playlist.m3u8

**Comment by R4IN2007** [comment]
Maybe This Will Work  https://vips-livecdn.fptplay.net/hda1/cinemax_hls.smil/playlist.m3u8

**Comment by F640** [comment]
http://jkt2.roll.my.id/manifest/liveorigin/index.m3u8?id=max
No subtitle however and might only work for a while

**Comment by Pich1685** [comment]
http://50.7.220.74:8278/cinemax_twn/playlist.m3u8?ct=17874&tid=mf18038aaba6311485855&tsum=63ee6bcdb705ee72ea3d0f0d84ed6df1

This link work for cinemax asia CN sub

**Comment by Pich1685** [comment]
![Capture](https://user-images.githubusercontent.com/111278870/209315530-77a759e8-2813-4b97-b43d-f987381371de.PNG)

**Comment by freearhey** [comment]
https://livecdn.fptplay.net/hda1/cinemax_hls.smil/playlist.m3u8 (offline)
<img width="436" alt="image" src="https://user-images.githubusercontent.com/7253922/232226194-ca11975f-c503-4d1b-8b0f-b9bba54dd792.png">

https://vips-livecdn.fptplay.net/hda1/cinemax_vhls.smil/playlist.m3u8 (offline)
<img width="482" alt="image" src="https://user-images.githubusercontent.com/7253922/232226223-361f1fa9-74e1-4aef-bbfe-175f65ff148c.png">

http://50.7.220.74:8278/cinemax_twn/playlist.m3u8?ct=17874&tid=mf18038aaba6311485855&tsum=63ee6bcdb705ee72ea3d0f0d84ed6df1 (offline)
<img width="834" alt="image" src="https://user-images.githubusercontent.com/7253922/232226170-ad9bca5b-f4cc-40d4-98f8-5ec949968ab4.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/vn_fptplay.m3u#L20-L22
