### ISSUE TITLE
Add: 24h (Spain)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6657]
### Channel Name

24h

### Stream URL

https://hlsliveamdgl0-lh.akamaihd.net/i/hlslive_1@429494/master.m3u8?hdnts=exp=6969696969~hmac=91cafaca9374214cbe2502036bedb829cebe979a160432fdf381a9aeb17ccd17

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://hlsliveamdgl0-lh.akamaihd.net/i/hlslive_1@429494/master.m3u8
