### ISSUE TITLE
Replace: J Sports 1

### ISSUE THREAD

**Issue by Marcoreus89** [iptv-org/iptv#6659]
### Stream Title

J Sports 1 (720p)

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://raw.githubusercontent.com/iptv-org/iptv/master/streams/jp.m3u

### Broken Link

http://51.79.193.108:8080/hls/j00042/index.m3u8

### Notes

all the japan channels linked to http://51.79.193.108:8080 has broken since last week,not only this one channel，somebody who can fix it,please

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Well, it has been put as "Offline" since 2 days. I don't think we'll see them again for now.
For now, we're more onto a "RIP" than finding an alternative.

**Comment by luongz** [comment]
check in #6580

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/552de94eed297776b2e5a49a006e5503533f56e7/streams/jp.m3u#L73-L74

<img width="640" alt="image" src="https://user-images.githubusercontent.com/7253922/159476150-09e04710-1a29-405d-8713-7186e4391665.png">
