### ISSUE TITLE
Add: Pluto TV G4 Select

### ISSUE THREAD

**Issue by thoudankeykang** [iptv-org/iptv#6660]
### Channel Name

Pluto TV G4 Select

### Website

https://pluto.tv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Lucas-mother3** [comment]
#6643

**Comment by LaneSh4d0w** [comment]
Duplicate of #6643.
