### ISSUE TITLE
Replace: PBS Providence RI (WSBE) (1080p)

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6661]
### Stream Title

PBS Providence RI (WSBE)

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://hls-wsbedt.lls.pbs.org/out/v1/282a0653ed3341ebac0ff99c0f2a8137/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
DRMd.

**Comment by MapGuy11** [comment]
All PBS can now only be watched with their app they are DRM'd.

**Comment by Sphinxroot** [comment]
Kodi + slyguy.pbs.live  +  VPN if outside USA

**Comment by spotanjo3** [comment]
Providence PBS please ? Thanks.

**Comment by LaneSh4d0w** [comment]
> DRMd.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f64eccb9362a086387cc16c8164d5ad211a7e424/streams/us_pbs.m3u#L16-L17

**Comment by spotanjo3** [comment]
403 Forbidden
