### ISSUE TITLE
Add: Comedy Central (US)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6662]
### Channel Name

Comedy Central 

### Channel ID

ComedyCentralEast.us

### Website

https://www.cc.com/live-tv/77hs5c

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/13d2f470b7e5b647c0d24d4b6897c651d4b52971/streams/us_pluto.m3u#L208-L209

**Comment by spotanjo3** [comment]
Its dead.
