### ISSUE TITLE
Add: CNN (Philippines)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6669]
### Channel Name

CNN Philippines

### Stream URL

https://streaming.cnnphilippines.com/live/myStream/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
CNN is an US company, so it is classified as US.

**Comment by MapGuy11** [comment]
> CNN is an US company, so it is classified as US.

Yeah that makes literally no sense but that is how the owner wants it.

**Comment by MapGuy11** [comment]
https://streaming.cnnphilippines.com/live/myStream/playlist.m3u8

**Comment by fotvnetwork** [comment]
Owned by a Filipino company, licensed by US news network

**Comment by freearhey** [comment]
@MapGuy11 If you have any suggestions on how to improve the channel sorting it would be better to publish it [here](https://github.com/iptv-org/iptv/discussions/categories/ideas) so others can see it too.

**Comment by MapGuy11** [comment]
> @MapGuy11 If you have any suggestions on how to improve the channel sorting it would be better to publish it [here](https://github.com/iptv-org/iptv/discussions/categories/ideas) so others can see it too.

Will do. Thanks 👍
