### ISSUE TITLE
Add: TUDN (México)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6672]
### Channel Name

TUDN 

### Channel ID

TUDNMexico.mx

### Stream URL

http://190.61.102.67:2000/play/a08j/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Offline.

**Comment by MapGuy11** [comment]
404 Astra no way: 
![image](https://user-images.githubusercontent.com/43685307/157777278-57baf74d-9c2e-45ed-87ba-5ec4c73ecfae.png)

**Comment by R4IN2007** [comment]
Maybe the m3u8 stream went down

**Comment by LaneSh4d0w** [comment]
> The m3u8 stream link is working again 

Still not for me.

**Comment by MapGuy11** [comment]
> > The m3u8 stream link is working again
> 
> Still not for me.

It is but it's an Astra link so it is not showing TUDN anymore: 
![image](https://user-images.githubusercontent.com/43685307/157990047-7646c1aa-ed92-42ed-b4b1-55dea3a16cc1.png)

**Comment by LaneSh4d0w** [comment]
> > > The m3u8 stream link is working again
> > 
> > Still not for me.
> 
> It is but it's an Astra link so it is not showing TUDN anymore: 
> ![image](https://user-images.githubusercontent.com/43685307/157990047-7646c1aa-ed92-42ed-b4b1-55dea3a16cc1.png)
> 
> 

Try to get to the root URL and add "playlist.m3u8".

**Comment by R4IN2007** [comment]
It's Just Now Airing History Channel In Spanish 
![20220311_221037](https://user-images.githubusercontent.com/83226646/158003224-af6d5116-abf6-4126-b954-53ad8a5f5d4c.jpg)

**Comment by pukozs75** [comment]
It's working now.

**Comment by LaneSh4d0w** [comment]
Nope. Not for me.

**Comment by R4IN2007** [comment]
![20220314_170027](https://user-images.githubusercontent.com/83226646/158268430-5d9cad46-2374-4278-aa34-806058584e06.jpg)

**Comment by freearhey** [comment]
http://190.61.102.67:2000/play/a08j/index.m3u8
<img width="657" alt="image" src="https://user-images.githubusercontent.com/7253922/185198723-72a285c7-270f-48a4-ab3d-baf387d2dd67.png">

**Comment by freearhey** [comment]
http://45.182.21.251:33334/play/a07y/index.m3u8 (Offline)
<img width="360" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/464900eb-2038-45a0-8e68-2312513bcc3c">

http://45.228.234.77:4430/play/tudn (Offline)
<img width="271" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/06e317d7-6f7c-4d68-a592-caae693dbb72">

**Comment by R4IN2007** [comment]
> http://190.61.102.67:2000/play/a08j/index.m3u8 <img alt="image" width="657" src="https://user-images.githubusercontent.com/7253922/185198723-72a285c7-270f-48a4-ab3d-baf387d2dd67.png">

http://190.61.102.67:2000/play/a08j/index.m3u8
Works Fine
![Screenshot_20230609_143625_Chrome](https://github.com/iptv-org/iptv/assets/83226646/dbc04325-f576-4620-9cfe-aff5d983f03a)
![Screenshot_20230609_143733_Chrome](https://github.com/iptv-org/iptv/assets/83226646/0e8d6be6-f819-4d01-9f87-b5b19e8be015)

**Comment by freearhey** [comment]
http://190.61.102.67:2000/play/a08j/index.m3u8 

It really works.

But the message that covers most of the frame is still there:
![image translated](https://github.com/iptv-org/iptv/assets/7253922/025eb7d7-7832-43b6-9493-bf9b01353a4a)

**Comment by R4IN2007** [comment]
Not anymore 
![Screenshot_20230610_183902_Chrome](https://github.com/iptv-org/iptv/assets/83226646/cca71e1f-079e-4c2a-a6e0-f167d7d9e736)

**Comment by BellezaEmporium** [comment]
> Not anymore ![Screenshot_20230610_183902_Chrome](https://user-images.githubusercontent.com/83226646/244899557-cca71e1f-079e-4c2a-a6e0-f167d7d9e736.jpg)

Maybe the owners of the stream are watching this repo lol

**Comment by WilkinsCoffeeArchives** [comment]
Here https://live-api.vimeocdn.com/sessions/0b79ff02-5169-40c1-894d-2946b10822af/playlist/avc/hls.m3u8?cdn=fastly-fmp4&~exp=1756080000&~id=player&~sig=VW8tcP1OFePdSOqrRTED9Y8Qt-NvnKv9KuQtMVLLtMM
And if it does expire here is the vimeo link just use an m3u8 sniffer
