### ISSUE TITLE
Fix: language & icon info not set for channel "Arirang TV"

### ISSUE THREAD

**Issue by Owyn** [iptv-org/iptv#6678]
### Describe your issue

so that's why it's currently in `undefined` list instead of `english` where it should be, pls fix 

https://iptv-org.github.io/iptv/languages/undefined.m3u
````
#EXTINF:-1 tvg-id="" tvg-country="KR" tvg-language="" tvg-logo="" group-title="Undefined",Arirang (720p)
http://amdlive-ch01.ctnd.com.edgesuite.net/arirang_1ch/smil:arirang_1ch.smil/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-country="KR" tvg-language="" tvg-logo="" group-title="Undefined",Arirang (720p)
http://amdlive-ch02.ctnd.com.edgesuite.net/arirang_1ch/smil:arirang_1ch.smil/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-country="KR" tvg-language="" tvg-logo="" group-title="Undefined",Arirang (720p)
http://amdlive-ch03.ctnd.com.edgesuite.net/arirang_1ch/smil:arirang_1ch.smil/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-country="KR" tvg-language="" tvg-logo="" group-title="Undefined",Arirang (720p)
http://amdlive.ctnd.com.edgesuite.net/arirang_1ch/smil:arirang_1ch.smil/.m3u8
````

language should be set to `english`
and here's their icon: https://www.arax.md/assets/channels/102.png

sorry I'm not sure which branch I should PR to ( https://github.com/iptv-org/iptv/blob/master/streams/kr.m3u ) or if that's how editing streams works at all so I opened an issue here

**Comment by Owyn** [comment]
The channel is not in the undefined list anymore but it's also not in the english one either where it should be ? 

it's not in korean language tho, it's in english, it got put into the wrong place
![](https://user-images.githubusercontent.com/1309656/158016121-bbc120e9-092f-4185-a253-e2235961d757.png)

**Comment by freearhey** [comment]
All channel data is now loaded from a separate repository: [iptv-org/database](https://github.com/iptv-org/database). If you find any error, feel free to fix it by editing the [data/channels.csv](https://github.com/iptv-org/database/blob/master/data/channels.csv) file.
