### ISSUE TITLE
Add: TyC Sports

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6684]
### Channel Name

TyC Sports

### Stream URL

https://d3awnlgqz0szay.cloudfront.net:443/out/v1/b841c366cbe540e6a106c3ba83e5c8d6/index.m3u8

### Notes

Its A Spanish Sports Channel 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Mixed thoughts about this one : https://en.wikipedia.org/wiki/TyC_Sports

Could easily be DMCAd, the CONMEBOL A-P team is quite around flagging on Google.

**Comment by Nicolas1307** [comment]
No funciona

**Comment by R4IN2007** [comment]
> No funciona

Sí, el enlace m3u8 no funciona porque está fuera de servicio. Funciona cuando está en línea o el canal esta vivo

**Comment by Nicolas1307** [comment]
No funciona 😭😭😭

**Comment by PepeParada** [comment]
por favor necesito uno nuevo!! de TyC sports Argentina!
