### ISSUE TITLE
Broken Stream: Sport TV 1

### ISSUE THREAD

**Issue by pukozs75** [iptv-org/iptv#6694]
### Stream Title

Sport TV 1 (720p) [Not 24/7]

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/categories/sports.m3u

### Notes

All Portugal Sport TV Channels don't work

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Duplicate #6373
