### ISSUE TITLE
Televisa Estado's stream is detected as a virus by Avast

### ISSUE THREAD

**Issue by cssobral2013** [iptv-org/iptv#6698]
### Stream Title

Televisa Estado (1080p) [Not 24/7]

### What happened to the stream?

Other

### Playlist

https://iptv-org.github.io/iptv/index.m3u

### Notes

This issue is displayed with Kodi (maybe other players too)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/552de94eed297776b2e5a49a006e5503533f56e7/streams/mx.m3u#L148-L149

<img width="640" alt="image" src="https://user-images.githubusercontent.com/7253922/159476782-b33947f3-e65b-4b27-9010-48f1c1ff602d.png">
