### ISSUE TITLE
Add: CNN Portugal

### ISSUE THREAD

**Issue by cssobral2013** [iptv-org/iptv#6699]
### Channel Name

CNN Portugal

### Website

https://tviplayer.iol.pt/direto/CNN

### Stream URL

https://video-auth8.iol.pt/live_cnn/live_cnn/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9My8xMy8yMDIyIDk6Mzg6MzQgUE0maGFzaF92YWx1ZT1FdWRGUzlPUm9LZnI5V3R6c0JWU1V3PT0mdmFsaWRtaW51dGVzPTE0NDAmaWQ9NjVjNTIzODctZmU2Ni00ZjIxLThmMTUtYjg0NTk0MmUwYmEw

### Notes

It runs at 720p, and can be shown in every place of the world (for instance, I'm in Brazil)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fotvnetwork** [comment]
Token works for 24 hours

**Comment by cssobral2013** [comment]
https://video-auth4.iol.pt/live_cnn/live_cnn/edge_servers/cnn-480p/chunks.m3u8

**Comment by cssobral2013** [comment]
Edits:
- The stream link runs at 480p, not 720p as stated on OP;
- This channel is from Portugal, and in Portuguese.

**Comment by spotanjo3** [comment]
Not working.
