### ISSUE TITLE
BS241 SPTV (BS スカパー)

### ISSUE THREAD

**Issue by Marcoreus89** [iptv-org/iptv#6707]
### Channel Name

BS スカパー

### Channel ID

BSSKYPerfecTV.jp

### Notes

This is a japanese channel, who has the m3u of this channel, please tell me, thanks

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
According to https://www.skyperfectjsat.space/en/news/detail/notice_regarding_termination_of_bs241ch579_channel_name_bs_sky_perfectv_april_28_2022.html the channel will be closed on October 31, 2022.
