### ISSUE TITLE
Replace: CNN International

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6710]
### Stream Title

CNN International

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://cnn-cnninternational-1-eu.rakuten.wurl.com/manifest/playlist_1280x720_3000k.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Central302** [comment]
You Can Use This Instead.
https://cnn-cnninternational-1-gb.samsung.wurl.com/manifest/playlist.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/552de94eed297776b2e5a49a006e5503533f56e7/streams/uk_samsung.m3u#L8-L9

<img width="640" alt="image" src="https://user-images.githubusercontent.com/7253922/159477394-7cc5fec1-4b16-4312-b73e-24c64632a162.png">
