### ISSUE TITLE
Replace: CNN International Europe (720p)

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6711]
### Stream Title

CNN International Europe 

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://cnn-cnninternational-1-eu.rakuten.wurl.com/manifest/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Duplicate #6710
