### ISSUE TITLE
Add: Hechos Ecuador 

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6712]
### Channel Name

Hechos Ecuador

### Stream URL

http://37.187.7.106/hechostv/live.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Confirmed answering and working.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/2523a66b3a38b9dcebbdd43e0d94b34edd4b2da5/streams/ec.m3u#L14-L15
