### ISSUE TITLE
Add: Ecuavisa

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6713]
### Channel Name

Ecuavisa

### Stream URL

https://mdstrm.com/live-stream-playlist/603ea23f928cc5255563012c.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Geo-blocked to Ecuador citizens only.
