### ISSUE TITLE
Add: Canal RCN

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6714]
### Channel Name

RCN

### Channel ID

CanalRCN.co

### Stream URL

https://stream-01.nyc.dailymotion.com/sec(0HE75RGSqqnhnSdEMl12ZSmc3ztB857c944nbmJ6Hgc)/dm/3/x7vyv0z/s/live-3.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x7vyv0z

**Comment by AntiPontifex** [comment]
Dead issue: please close.

**Comment by freearhey** [comment]
Closed in favor of #9698
