### ISSUE TITLE
Add:  RCN Mas+

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6715]
### Channel Name

RCN Mas

### Stream URL

https://rcntv-rcnmas-1-us.roku.wurl.tv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Confirmed answering and working.

**Comment by Shiyaskn** [comment]
RCN Fútbol

**Comment by BellezaEmporium** [comment]
> RCN Fútbol

Not a channel.
