### ISSUE TITLE
Add: La Red (Chile)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6716]
### Channel Name

La Red

### Stream URL

https://d2tr4gdfol9ja.cloudfront.net/lared/lared.smil/.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Confirmed answering and working.
