### ISSUE TITLE
Add: TruTV (México)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6717]
### Channel Name

TruTV

### Stream URL

http://190.61.37.173:9001/play/a084/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Confirmed answering and working.
