### ISSUE TITLE
Add: A3Series Internacional (España)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6719]
### Channel Name

A3Series Internacional

### Stream URL

https://mdstrm.com/live-stream-playlist/5cae562e0ca2f30815231c0f.m3u8?access_token=DST4b676d7da5a2a92ee15f8efcbcd00606

### Notes

The m3u8 Will Not Work Without The Access Token
{"status":"ERROR","data":"CLOSED_ACCESS","message":"You are not allowed to watch this event: Invalid Token"}

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Works perfectly from here in France.
