### ISSUE TITLE
Add: Start TV

### ISSUE THREAD

**Issue by fotvnetwork** [iptv-org/iptv#6726]
### Channel Name

Start TV

### Channel ID

StartTV.us

### Stream URL

https://16live00.akamaized.net/START_TV/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Adding it with other PR.

**Comment by spotanjo3** [comment]
Hello. Hope you guys are doing well.

This link is officially dead. Have another link, please ?
