### ISSUE TITLE
CS309 FuJi NEXT

### ISSUE THREAD

**Issue by Marcoreus89** [iptv-org/iptv#6730]
### Channel Name

FuJi NEXT

### Channel ID

FujiTVNext.jp

### Notes

This is a japanese channel, who has the m3u of this channel, please tell me, thanks

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://code.vthanhtivi.pw/getlink/jptv/xPyiMHfxozuDu6vNznDdXA==/playlist.m3u8
<img width="789" alt="image" src="https://user-images.githubusercontent.com/7253922/233871258-d0ae6fd3-94a9-471f-9193-ee5e1ef8c6dc.png">

http://rip.hidari.moe/get/jptv/get.php?id=rhKOiZXma2k2EoIaL9RCmg==
<img width="785" alt="image" src="https://user-images.githubusercontent.com/7253922/233871273-82db34d8-367b-4f25-be3f-80279dd4ce1c.png">
