### ISSUE TITLE
Add: TVOKids (Canada)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6735]
### Channel Name

TVOKids

### Stream URL

https://bcsecurelivehls-i.akamaihd.net/hls/live/623607/15364602001/tvokids/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Works perfectly.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/2523a66b3a38b9dcebbdd43e0d94b34edd4b2da5/streams/ca.m3u#L190-L191

**Comment by asdfghiptvyde** [comment]
Does not work anymore
