### ISSUE TITLE
Add: SyFy (México)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6736]
### Channel Name

SyFy

### Stream URL

http://168.232.168.242:8000/play/a05k/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Dual Audio w/ closed captions. Nice one.
