### ISSUE TITLE
Replace: Az TV

### ISSUE THREAD

**Issue by pukozs75** [iptv-org/iptv#6742]
### Stream Title

Az TV (576p) [Not 24/7]

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/index.country.m3u

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
https://tv.myvideo.ge/vendor.html?lang=az&filterChannels=aztv,idman,medeniyet,radio-international,az-radiosu&epg=true&ads=false&watermark=false&channels=true&forceDesktop=false  down

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f64eccb9362a086387cc16c8164d5ad211a7e424/streams/az.m3u#L20-L21

**Comment by freearhey** [comment]
Broken link removed from playlist.
