### ISSUE TITLE
Add: SYFY US

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6743]
### Channel Name

SYFY

### Channel ID

SyfyEast.us

### [Website]
(https://www.syfy.com)

_No response_

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by R4IN2007** [comment]
https://16live00.akamaized.net/SYFY/index.m3u8

**Comment by spotanjo3** [comment]
Working great and closed captioning. Thanks so much, @R4IN2007

**Comment by spotanjo3** [comment]
By the way which is the best iptv for Android TV ? I have a OLED SONY ANDROID TV. I tried Televizo.. nice one and it is like TV. You can use remote to change the channels just like TV.  I tried TIVIMATE.. Nice one but you can't change the channel using remote like a TV.

**Comment by spotanjo3** [comment]
Is there other Syfy us ? Because yours work fine on VLC Media Player with closed captioning but on TELEVIZ doesn't have closed captioning for SYFY which is strange to me.

**Comment by spotanjo3** [comment]
Can you fix it ? It didn't work on Android tv. Only works on VLC Player. Something's not right. Can you find the correct link or something to run on Android TV properly ? Thanks.

**Comment by spotanjo3** [comment]
Anybody ? I want to watch it badly on TV. Not VLC Player. *SAD*

**Comment by spotanjo3** [comment]
What about SYFY issues ? It is working only for VLC .. VLC Only.

**Comment by spotanjo3** [comment]
Can you add for SYFY West ??

**Comment by spotanjo3** [comment]
Can't find it ?

**Comment by rochelryu** [comment]
Not Work at Now

**Comment by R4IN2007** [comment]
Old
