### ISSUE TITLE
Replace: L'EQUIPE (360p)

### ISSUE THREAD

**Issue by xTnK** [iptv-org/iptv#6749]
### Stream Title

L'EQUIPE (360p)

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/countries/fr.m3u

### Broken Link

https://s6.tntendirect.com/lequipe21/live/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/b1e550a81bd94bcb2d0468c79a05fc5e17541430/streams/fr.m3u#L127-L128
