### ISSUE TITLE
Replace: W9 (720p) [Not 24/7]

### ISSUE THREAD

**Issue by xTnK** [iptv-org/iptv#6750]
### Stream Title

W9 (720p) [Not 24/7]

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/countries/fr.m3u

### Broken Link

http://flusonic-2.platinum-tv.com/W9/mono.m3u8?token=test

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/b1e550a81bd94bcb2d0468c79a05fc5e17541430/streams/fr.m3u#L223-L224
