### ISSUE TITLE
Replace: Top Channel (720p) [Geo-blocked]

### ISSUE THREAD

**Issue by xTnK** [iptv-org/iptv#6752]
### Stream Title

Top Channel (720p) [Geo-blocked]

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/countries/al.m3u

### Broken Link

http://us.bestvideostreaming.is/8708/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Couldn't find the original link.
