### ISSUE TITLE
Replace: KLAN

### ISSUE THREAD

**Issue by xTnK** [iptv-org/iptv#6753]
### Stream Title

KLAN

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/countries/al.m3u

### Broken Link

http://79.106.73.244:4040/live/klanhdmob/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
http://51.210.0.169:8621/live/klanhdmob/playlist.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f64eccb9362a086387cc16c8164d5ad211a7e424/streams/al.m3u#L92-L93

**Comment by freearhey** [comment]
http://51.210.0.169:8621/live/klanhdmob/playlist.m3u8
<img width="491" alt="image" src="https://user-images.githubusercontent.com/7253922/185801738-19205276-ee12-43d0-bd58-8390caa46fab.png">

**Comment by freearhey** [comment]
The broken link has been removed from the playlist.

Closed in favor #8168
