### ISSUE TITLE
Replace: Klan HD (720p) [Geo-blocked]

### ISSUE THREAD

**Issue by xTnK** [iptv-org/iptv#6754]
### Stream Title

Klan HD (720p) [Geo-blocked]

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://iptv-org.github.io/iptv/countries/al.m3u

### Broken Link

http://us.bestvideostreaming.is/8704/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
http://178.33.11.6:8686/live/tvklanmob/index.m3u8

**Comment by freearhey** [comment]
Couldn't find the original link.
