### ISSUE TITLE
Add: canal+ france

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6769]
### Channel Name

canal+

### Channel ID

CanalPlusFrance.fr

### Website

https://www.dailymotion.com/video/x5gv6be

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x5gv6be
