### ISSUE TITLE
Add: c8 france

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6770]
### Channel Name

c8

### Website

https://www.dailymotion.com/video/x5gv5rr

### Stream URL

C8.fr

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x5gv5rr
