### ISSUE TITLE
Add: LCP FRANCE

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6771]
### Channel Name

LCP

### Website

https://www.dailymotion.com/video/xji3qy

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/47971717e7b7bec806c44a85a7b77772b5695808/streams/fr.m3u#L146-L147
