### ISSUE TITLE
Add: Tele SUD frane

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6772]
### Channel Name

Tele Sude

### Channel ID

Telesud.fr

### Website

https://www.dailymotion.com/video/x7wrxqb

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x7wrxqb
