### ISSUE TITLE
Add: Tele Grenoble France

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6773]
### Channel Name

Tele Grenoble

### Channel ID

TeleGrenoble.fr

### Website

https://www.dailymotion.com/video/x128fjo

### Stream URL

TeleGrenoble.fr

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x128fjo
