### ISSUE TITLE
Add: Tele Nantes France

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6774]
### Channel Name

Tele Nantes

### Channel ID

Telenantes.fr

### Website

https://www.dailymotion.com/video/x5so98l

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x5so98l
