### ISSUE TITLE
Add: canal algerie

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6775]
### Channel Name

canal algérie

### Website

http://www.giniko.com/watch.php?id=328

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/47971717e7b7bec806c44a85a7b77772b5695808/streams/dz.m3u#L14-L15
