### ISSUE TITLE
Broken: SYFY

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6786]
### Stream Title

SYFY

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://16live00.akamaized.net/SYFY/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by MapGuy11** [comment]
They are all 403 now.

**Comment by spotanjo3** [comment]
What does that mean ? A new one will be found soon ? Or it will be online again ?

**Comment by freearhey** [comment]
We can't replace this link because it wasn't added to the playlist: #6743

**Comment by freearhey** [comment]
This means that your previous request has not gone anywhere and there is no need to create a new one. When a working link to the broadcast appears, we'll add it to the playlist anyway.

**Comment by spotanjo3** [comment]
Oh okay. I got it. Apology. Thanks.

**Comment by R4IN2007** [comment]
The SyFy Channel m3u8 Works
![247_Chrome](https://user-images.githubusercontent.com/83226646/159796999-dd973387-9107-439d-ae24-f86deb37f2c0.jpg)

**Comment by MapGuy11** [comment]
> The SyFy Channel m3u8 Works ![247_Chrome](https://user-images.githubusercontent.com/83226646/159796999-dd973387-9107-439d-ae24-f86deb37f2c0.jpg)

Not this provided link

**Comment by R4IN2007** [comment]
That's Very Strange 🤔

**Comment by spotanjo3** [comment]
What player do you use ? @_@

**Comment by MapGuy11** [comment]
> What player do you use ? @_@

VLC, Chrome, and much more.

**Comment by spotanjo3** [comment]
What link ? The above is still dead on VLC And my favorite player on Sony Bravia OLED Android TV.

**Comment by R4IN2007** [comment]
Here Are Other Links That Works

#EXTINF:0 tvg-country="BR" tvg-logo="" group-title="Brazil",SYFY
http://main.webhostingtoto.xyz:2095/NEW_LIVE2711144451/7540066240/781

#EXTINF:0 tvg-country="BR" tvg-logo="" group-title="Brazil",SYFY HD
http://main.webhostingtoto.xyz:2095/NEW_LIVE2711144451/7540066240/914

#EXTINF:0 tvg-country="FR" tvg-logo="" group-title="FRANCE",SYFY FHD
http://stariptv.org:8080/wael2021/123456/56322

#EXTINF:0 tvg-country="FR" tvg-logo="" group-title="FRANCE",Syfy
http://stariptv.org:8080/wael2021/123456/4302

#EXTINF:0 tvg-country="DE" tvg-logo="" group-title="Undefined",SyFy
http://iptv.watchhd.cc:5050/kelevra321/UWqjWR89sRNT/154.ts

#EXTINF:0 tvg-country="DE" tvg-logo="" group-title="Undefined",SYFY HD
http://iptv.watchhd.cc:5050/kelevra321/UWqjWR89sRNT/10134.ts

#EXTINF:0 tvg-country="US" tvg-logo="" group-title="Entertainment",SYFY HD
http://stariptv.org:8080/wael2021/123456/148451

#EXTINF:0 tvg-country="US" tvg-logo="" group-title="Entertainment",USA | Syfy East
http://gtv23.xyz:80/rererere/rererere/175933.ts

#EXTINF:0 tvg-country="US" tvg-logo="" group-title="Entertainment",USA | Syfy West
http://gtv23.xyz:80/rererere/rererere/175934.ts

**Comment by MapGuy11** [comment]
> Here A Another Link That Works 
> 
> http://stariptv.org:8080/wael2021/123456/148451?.m3u8

We don't do Xtreme Codes url's

**Comment by spotanjo3** [comment]
I try those two on Televizo and iptvnator and it won't work. It only work on VLC Player.

 I want to use Televizo because I am watching it on my TV.

**Comment by spotanjo3** [comment]
> > Here A Another Link That Works
> > http://stariptv.org:8080/wael2021/123456/148451?.m3u8
> 
> We don't do Xtreme Codes url's

Can you get a link that works for Televizo and other popular android for TV ? This link only works for VLC Player

**Comment by R4IN2007** [comment]
http://38.127.211.18/live/c2eds/SYFY/HLS/index.m3u8

**Comment by spotanjo3** [comment]
> http://38.127.211.18/live/c2eds/SYFY/HLS/index.m3u8

Thanks but its the same.

Please correctly configure HLS media (manifest)/
I still get this error in Google video library: input does not start with the #EXTM3U header.

Please check. Thanks. ^_^

**Comment by spotanjo3** [comment]
I test two: Iptvnator for macOS as a test before import to Televizo for Sony TV Android. It doesn't worked at all. 

Only VLC Media Player works. That's strange.

I test your most files on Televizo which works fine on Sony TV Android. This link isn't working properly. Just want to make it clearly. Hope you find one working for Sony TV Android such as Televizo. I also test another famous android tv and it doesn't worked either.

**Comment by spotanjo3** [comment]
Can you do something about it ? It is for VLC only. Not working for Android TV.

**Comment by spotanjo3** [comment]
Now, its swirling nonstop. Its not working anymore starting yesterday. Still swirling today.

**Comment by spotanjo3** [comment]
Cam you add another link?  The sub (closed caption) isn't working.

**Comment by spotanjo3** [comment]
Can someone help ? I still watch it but I am frustrated because it is no longer closed caption somehow. Please help ? Thanks.

**Comment by spotanjo3** [comment]
> > Can someone help ? I still watch it but I am frustrated because it is no longer closed caption somehow. Please help ? Thanks.
> 
> Yeah, I Couldn't Find A m3u8 That Has Or Have Closed Captions

I dont understand. At my sister’s.. she paid cable and syfy with the closed captioning is fine.

Anyway, I found iptv online and there are good channels and  syfy is one of them and its working and i can read closed captioning but its online. Not VLC or anything. Only steaming online.  I dont know if i am allowed to post the link here. Not sure if you know what I mean.

**Comment by spotanjo3** [comment]
SYFY is dead. It is not working anymore. Swirl circle.
