### ISSUE TITLE
Add: California Music Channel (CMC-TV)

### ISSUE THREAD

**Issue by rrjanbiah** [iptv-org/iptv#6794]
### Channel Name

California Music Channel (CMC-TV)

### Channel ID

CaliforniaMusicChannel.us

### Website

https://cmc-tv.com/

### Stream URL

https://cmc-ono.amagi.tv/hls/amagi_hls_data_cmcAAAAAA-cmc-ono/CDN/playlist.m3u8?device[did]=%7BPSID%7D&device[dnt]=%7BDID%7D&us_privacy=%7BUS_PRIVACY%7D&coppa=%7BCOPPA%7D

### Notes

I think, above stream URL has to be used in place of https://github.com/iptv-org/iptv/blob/66892286541ac904d0993e52cbf750ab1de024d9/streams/us.m3u#L327

1. As per streamtest.in, it doesn't seem to be Geo-blocked
    1. https://streamtest.in/runtest/FpTxIEJAb5ejHCS0oWHxPg Singapore
    2. https://streamtest.in/runtest/q7BmLbAbII0JFQgKijTQzQ USA
3. It is having `360, 504, 720, 1080` resolutions

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by MapGuy11** [comment]
Works: https://cmc-ono.amagi.tv/hls/amagi_hls_data_cmcAAAAAA-cmc-ono/CDN/playlist.m3u8
![image](https://user-images.githubusercontent.com/43685307/159356444-fbd40d40-3703-457a-b0cc-8099fd5dff0c.png)

**Comment by rrjanbiah** [comment]
@MapGuy11 Sorry, can't understand. The link that works is the one that I proposed (taken from https://cmc-tv.com/). But the current link ` https://cmctv.ios.internapcdn.net/cmctv_vitalstream_com/live_1/CMC-TV/playlist.m3u8` doesn't work. Also, you may want to rename the channel name to `California Music Channel (CMC-TV)` for easy search.

**Comment by MapGuy11** [comment]
> @MapGuy11 Sorry, can't understand. The link that works is the one that I proposed (taken from https://cmc-tv.com/). But the current link ` https://cmctv.ios.internapcdn.net/cmctv_vitalstream_com/live_1/CMC-TV/playlist.m3u8` doesn't work. Also, you may want to rename the channel name to `California Music Channel (CMC-TV)` for easy search. 

Yes your link does work but you can remove the crap from the end. I am double checking that it does work. Before I put the tag that it does work.

**Comment by LaneSh4d0w** [comment]
Simpler : https://cmc-ono.amagi.tv/playlist.m3u8
