### ISSUE TITLE
Add: Kolkata Bangla Channel

### ISSUE THREAD

**Issue by debctg** [iptv-org/iptv#6795]
### Channel Name

Sun Bangla, Star Jalsha, Star Movies etc.

### Notes

Anybody can give me 100% working m3u file, Kolkata/Indian Bangla channel please,

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Do not make a request to request multiple channels at once, as it's counterproductive for us.
