### ISSUE TITLE
Add: C STAR france

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6797]
### Channel Name

C STAR

### Channel ID

CStar.fr

### Website

https://www.dailymotion.com/video/x5gv5v0

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x5gv5v0

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/13d2f470b7e5b647c0d24d4b6897c651d4b52971/streams/fr.m3u#L34-L35
