### ISSUE TITLE
Add: NBC 5 (WPTV-TV)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6801]
### Channel Name

NBC 5

### Stream URL

https://content.uplynk.com/channel/b02350ef854c4eef8358eead1f59a5cc.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by danielng620** [comment]
who can ren me know we projak name urs.. regiter.?
