### ISSUE TITLE
Please add more Swedish channels

### ISSUE THREAD

**Issue by HafMann** [iptv-org/iptv#682]
I would like you to add more Swedish channels such as "SVT1", "SVT2", "TV3", "Kanal 5", "TV6" and "Kunskapskanalen".

**Comment by fjanta** [comment]
Hello, can you please ad Swedish channels. I see you did but when I click on it it’s another foreign channel. So it was the right channel logo but not a Swedish channel. 

Here is a list of Swedish channels if you find any of them:
SVT1 
SVT2 
TV3 
TV4
Kanal 5 
TV6 
Sjuan 
TV8 
Kanal 9 
TV10 
Kanal 11 
TV12

**Comment by freearhey** [comment]
@fjanta Could you specify which channels in the playlist are not Swedish?

**Comment by HafMann** [comment]
The channels you see on the list are the Swedish channels I would like you
to add to the playlist Note: some Danish, Norwegian, and Swedish channels
have similar names, for example there is a "Kanal 5" that is Danish and a
"Kanal 5" that is Swedish

**Comment by freearhey** [comment]
I understand what you're asking, but you said that some channels in the Swedish playlist aren't Swedish. 

> I see you did but when I click on it it’s another foreign channel.

Could you write the names of these channels so we can fix it?

**Comment by fjanta** [comment]
Yes, for example the channels HafMan requested first, TV3, TV6, Kanal 5, they have the exact logo of the Swedish one and in the title  (Now watching:...) is corecct but then some other program shows up in turkish or spanish. Hope you understand what I mean.

**Comment by freearhey** [comment]
Sorry, but I still don't understand where in this playlist (https://github.com/iptv-org/iptv/blob/master/channels/se.m3u) you saw TV3, TV6 or Kanal 5?

**Comment by fjanta** [comment]
I used this link (https://iptv-org.github.io/iptv/index.m3u)

**Comment by fjanta** [comment]
It has catagories so it maybe a bit hard to find, I clicked on (All total: 6963) if it is okey I can somehow send you a photo of where I found it

**Comment by fjanta** [comment]
But I can see that there is only 11 Swedish channels. I’m not familiar with some of them, could you please add more Swedish channels. If you need help I’m glad to help.

**Comment by freearhey** [comment]
As soon as I have links to other Swedish channels, I will definitely add them.

**Comment by fjanta** [comment]
Okey, thank you so much.

**Comment by freearhey** [comment]
- [ ] SVT1
- [x] SVT2
https://github.com/iptv-org/iptv/blob/bf9db5c60f0a6edd649fa2d9bb5ce680f5d3faba/channels/se.m3u#L26-L27
- [ ] [TV3](https://en.wikipedia.org/wiki/TV3_(Sweden))
- [x] TV4
https://github.com/iptv-org/iptv/blob/7f6c5f9131158d0adb1d0f7e7a32379103cf369d/channels/se.m3u#L16-L17
- [ ] [Kanal 5](https://www.dplay.se/kanaler/kanal5)
- [ ] [TV6](https://en.wikipedia.org/wiki/TV6_(Sweden))
- [ ] [Sjuan](https://en.wikipedia.org/wiki/Sjuan)
- [ ] [TV8](https://en.wikipedia.org/wiki/TV8_(Swedish_TV_channel))
- [ ] [Kanal 9](https://www.dplay.se/kanaler/kanal9)
- [ ] [TV10](https://en.wikipedia.org/wiki/TV10_(Sweden))
- [ ] [Kanal 11](https://www.dplay.se/kanaler/kanal11)
- [ ] [TV12](https://sv.wikipedia.org/wiki/TV12_(TV-kanal))

**Comment by freearhey** [comment]
Closed in favor #1951
