### ISSUE TITLE
Add: Zed TV

### ISSUE THREAD

**Issue by hawrazsabr** [iptv-org/iptv#6820]
### Channel Name

Zed TV

### Channel ID

Zedtv.ku

### Website

http://www.zedtv.net/?m=1

### Stream URL

http://190.2.148.141:8080/bar7657/tracks-v1a1/mono.m3u8

### Notes

This is kurdish channel 
category : entertainment

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Adaptive : http://190.2.148.141:8080/bar7657/index.m3u8

**Comment by hawrazsabr** [comment]
Channel Name : Zed TV
Category: Entertainment
Language : Kurdish
Country : Kurdistan From Iraq

This is Logo Channel : 
![image](https://user-images.githubusercontent.com/64305984/159785145-376abdfe-c332-4192-a05f-d6dfb5ef7204.png)

**Comment by hawrazsabr** [comment]
@LaneSh4d0w but Correct locate is iraq not Netherlands

**Comment by freearhey** [comment]
@hawrazsabr We sort the channels by country of origin. According to the official Facebook page it is the Netherlands: https://github.com/iptv-org/iptv/issues/6820#issuecomment-1076766244

If you want you can add a channel description to our [database](https://github.com/iptv-org/database) and then we can sort the channel based on it.

**Comment by hawrazsabr** [comment]
This channel not Netherland country but please sorting from iraq because from there.
