### ISSUE TITLE
Add: CBS News Miami (CBSN)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6825]
### Channel Name

CBSN Miami

### Stream URL

https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/60fb299b79498900070b29e0/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=873&deviceId=5d14fc31252d35decbc4080b&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
I have this on redir : https://dai.google.com/linear/hls/event/_yODrBHESGSzPe3dqW4gGg/master.m3u8

**Comment by Central302** [comment]
Already in Playlist.
