### ISSUE TITLE
Add: PlanetaTV Kids | (Chile)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6827]
### Channel Name

PlanetaTV Kids

### Channel ID

PlanetaTVKids.cl

### Website

https://planetatv.online/

### Stream URL

https://mediacpstreamchile.com:1936/8152/8152/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/5b8ff1dc2f957c31e8010a47b56520f2bd31e67b/streams/cl.m3u#L174-L175

**Comment by R4IN2007** [comment]
New Stream Link 
https://scl.edge.grupoz.cl/planetatvkids/live/playlist.m3u8
