### ISSUE TITLE
Add: PlanetaTV Hits | (Chile)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6830]
### Channel Name

PlanetaTV Hits

### Website

https://planetatv.online/

### Stream URL

https://mediacpstreamchile.com:1936/8172/8172/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/7253922/163682871-ffdde658-78a6-4ba9-8bf4-f53fd7e21c29.png">
