### ISSUE TITLE
Add: PlanetaTV 90s | (Chile)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6831]
### Channel Name

PlanetaTV 90s

### Website

https://planetatv.online/

### Stream URL

https://mediacpstreamchile.com:1936/8102/8102/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/7253922/163682899-95ec35d8-6e4f-49c4-a41f-55e56df15150.png">

**Comment by freearhey** [comment]
https://mediacpstreamchile.com:1936/8102/8102/playlist.m3u8
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/7253922/190886710-efd2039b-6c8b-45fa-9194-3a0c725ac04c.png">
