### ISSUE TITLE
Add: PlanetaTV Karaoke | (Chile)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6832]
### Channel Name

PlanetaTV Karaoke

### Website

https://planetatv.online/

### Stream URL

https://mediacpstreamchile.com:1936/8092/8092/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
<img width="711" alt="image" src="https://user-images.githubusercontent.com/7253922/163682930-49e230ef-1f01-4a64-802e-10622df864bc.png">
