### ISSUE TITLE
Add: NBA TV (US)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6838]
### Channel Name

NBA TV

### Channel ID

NBATV.us

### Website

https://www.nba.com/watch/channel/nbatvlive

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://line.gofast-tv.me:80/play/live.php?mac=00:1A:79:6F:5A:5D&stream=749756&extension=ts
<img width="791" alt="image" src="https://user-images.githubusercontent.com/7253922/233880455-be2fd1b1-06bf-4bbe-b680-da93d04bde06.png">

**Comment by kaikyoofers** [comment]
Wait, @BellezaEmporium do you allow this link?

**Comment by kaikyoofers** [comment]
> Wait, @BellezaEmporium do you allow this link?

@BellezaEmporium

**Comment by BellezaEmporium** [comment]
> Wait, @BellezaEmporium do you allow this link?

this is an Xtream-Codes but works with a MAC adress... not my kind of link
