### ISSUE TITLE
Fuji TV Two

### ISSUE THREAD

**Issue by Natsuki2104** [iptv-org/iptv#6840]
### Channel Name

Fuji TV Two

### Channel ID

FujiTVTwo.jp

### Notes

This is a japanese channel, who has the m3u8 of this channel, please tell me, thanks

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by ZXArkin** [comment]
I have a link here:
https://code.vthanhtivi.pw/getlink/jptv/147/playlist.m3u8
 Thanks!

**Comment by freearhey** [comment]
https://code.vthanhtivi.pw/getlink/jptv/147/playlist.m3u8 (offline)
<img width="400" alt="image" src="https://user-images.githubusercontent.com/7253922/232226723-8f00e411-dc64-48e8-88e8-6eefaa869440.png">

**Comment by chris12012** [comment]
New M3U Link For FUJI TV TWO

**Comment by chris12012** [comment]
New M3U8 Link For FUJI TV TWO Please

**Comment by freearhey** [comment]
@chris12012 Please Stop Spamming

**Comment by freearhey** [comment]
https://code.vthanhtivi.pw/getlink/jptv/xU1ix5hIdSVM9DfWLcR0Mg==/playlist.m3u8
<img width="785" alt="image" src="https://user-images.githubusercontent.com/7253922/233871321-893dc5eb-1eb8-42c7-a814-97bcf7f95258.png">

http://rip.hidari.moe/get/jptv/get.php?id=3q1U1u-6q9QMDWuMuvpPUA==
<img width="788" alt="image" src="https://user-images.githubusercontent.com/7253922/233871336-994981e1-3f40-4fb3-9e5f-d9585bd9342e.png">

**Comment by vanyillalatte** [comment]
Any new link updates for Fuji TV TWO? None above is working
