### ISSUE TITLE
Replace: Fuji TV

### ISSUE THREAD

**Issue by pavlikmac** [iptv-org/iptv#6845]
### Stream Title

Fuji TV (720p) [Not 24/7]

### What happened to the stream?

Not loading

### Notes

http://51.79.193.108:8080/hls/j00010/index.m3u8?type=jp - 404 Not Found

All playlists, that contains ip address 51.79.193.108 are not responding

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by pavlikmac** [comment]
Also http://27.254.130.62/feed/LC38/playlist.m3u8 - 404 Not Found

**Comment by AstaFatherSatan** [comment]
Change .m3u8 to .ts
It downloads a file.

**Comment by luongz** [comment]
Now the link need : 

a vaild token + mac

i can give you application related to the link.

**Comment by Nobodynumber1** [comment]
> Now the link need :
> 
> a vaild token + mac
> 
> i can give you application related to the link.


Had expired
http://51.79.193.109:8080/hlsok/j00042/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp

Please help. Thank you so much

**Comment by luongz** [comment]
> > Now the link need :
> > 
> > a vaild token + mac
> > 
> > i can give you application related to the link.
> 
> 
> Had expired
> http://51.79.193.109:8080/hlsok/j00042/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp
> 
> Please help. Thank you so much

I can't

The app have 3-days trial , expired now.

> i can give you application related to the link.

**Comment by Nobodynumber1** [comment]
> > > Now the link need :
> > > a vaild token + mac
> > > i can give you application related to the link.
> > 
> > 
> > Had expired
> > http://51.79.193.109:8080/hlsok/j00042/index.m3u8?key=wjvoHroQnTQU6U1an8sIBw&expires=1646332508&mac=00:d2:79:xx:xx:xx&type=jp
> > Please help. Thank you so much
> 
> I can't
> 
> The app have 3-days trial , expired now.
> 
> > i can give you application related to the link.

I had find a 1080P  APP
when i got trial acc give you to test.

**Comment by AstaFatherSatan** [comment]
What's the app name?

**Comment by luongz** [comment]
> What's the app name?

AZTV

**Comment by Nobodynumber1** [comment]
> ### Stream Title
> Fuji TV (720p) [Not 24/7]
> 
> ### What happened to the stream?
> Not loading
> 
> ### Possible Replacement
> _No response_
> 
> ### Notes
> http://51.79.193.108:8080/hls/j00010/index.m3u8?type=jp - 404 Not Found
> 
> All playlists, that contains ip address 51.79.193.108 are not responding
> 
> ### Please confirm the following
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

It's work again

**Comment by luongz** [comment]
> > ### Stream Title
> > Fuji TV (720p) [Not 24/7]
> > ### What happened to the stream?
> > Not loading
> > ### Possible Replacement
> > _No response_
> > ### Notes
> > http://51.79.193.108:8080/hls/j00010/index.m3u8?type=jp - 404 Not Found
> > All playlists, that contains ip address 51.79.193.108 are not responding
> > ### Please confirm the following
> > 
> > * [x]   I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)
> 
> It's work again

and now its down

**Comment by Nobodynumber1** [comment]
> > > ### Stream Title
> > > Fuji TV (720p) [Not 24/7]
> > > ### What happened to the stream?
> > > Not loading
> > > ### Possible Replacement
> > > _No response_
> > > ### Notes
> > > http://51.79.193.108:8080/hls/j00010/index.m3u8?type=jp - 404 Not Found
> > > All playlists, that contains ip address 51.79.193.108 are not responding
> > > ### Please confirm the following
> > > 
> > > * [x]    I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)
> > 
> > 
> > It's work again
> 
> and now its down

Oh my god 
had down again.
Please check new app. Hope can to use.

**Comment by okonomitarou** [comment]
> > > > ### Stream Title
> > > > Fuji TV (720p) [Not 24/7]
> > > > ### What happened to the stream?
> > > > Not loading
> > > > ### Possible Replacement
> > > > _No response_
> > > > ### Notes
> > > > http://51.79.193.108:8080/hls/j00010/index.m3u8?type=jp - 404 Not Found
> > > > All playlists, that contains ip address 51.79.193.108 are not responding
> > > > ### Please confirm the following
> > > > 
> > > > * [x]     I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)
> > > 
> > > 
> > > It's work again
> > 
> > 
> > and now its down
> 
> Oh my god had down again. Please check new app. Hope can to use.

Want to contribute to iptv-org/iptv?
If you have a bug or an idea, read the [contributing guidelines](https://github.com/iptv-org/iptv/blob/56984ce58bbeea54a7e3610c26f719500b944fde/CONTRIBUTING.md) before opening an issue.

> > > > ### Stream Title
> > > > Fuji TV (720p) [Not 24/7]
> > > > ### What happened to the stream?
> > > > Not loading
> > > > ### Possible Replacement
> > > > _No response_
> > > > ### Notes
> > > > http://51.79.193.108:8080/hls/j00010/index.m3u8?type=jp - 404 Not Found
> > > > All playlists, that contains ip address 51.79.193.108 are not responding
> > > > ### Please confirm the following
> > > > 
> > > > * [x]     I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)
> > > 
> > > 
> > > It's work again
> > 
> > 
> > and now its down
> 
> Oh my god had down again. Please check new app. Hope can to use.

Is there anything you can do?

**Comment by freearhey** [comment]
Closed in favor #6959
