### ISSUE TITLE
Add: Libya One TV

### ISSUE THREAD

**Issue by fraudiay79** [iptv-org/iptv#6849]
### Channel Name

Libya One TV

### Website

https://www.twitch.tv/libyaonetv

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/libyaonetv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fraudiay79** [comment]
This should go under 'LY' (Libya) not 'LB' Lebanon

**Comment by latinotv** [comment]
Any similar to  http://free.fullspeed.tv/iptv-query  ?

**Comment by latinotv** [comment]
This one http://free.fullspeed.tv/iptv-query
is not working today  do you know another url working
