### ISSUE TITLE
Add: IFC

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6850]
### Channel Name

IFC

### Channel ID

IFCEast.us

### Stream URL

https://bcovlive-a.akamaihd.net/070ffdaa203f439cacbf0d45a1ddb356/us-east-1/6240731308001/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Central302** [comment]
[I'll Do]Not Work in Potplayer, Maybe Required User-Agent?
