### ISSUE TITLE
Fix: American Classics (432P)

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6851]
### Describe your issue

It swirl every 30 seconds or so. 

Here:

https://dai2.xumo.com/amagi_hls_data_xumo1212A-redboxamericanclassics/CDN/playlist.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/issues/new?assignees=&labels=broken+stream&template=-----broken-stream.yml&title=Replace%3A+
