### ISSUE TITLE
Broken Stream: CBN News

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6852]
### Stream Title

CBN News (1080p)

### What happened to the stream?

Not loading

### Possible Replacement

http://bcliveuniv-lh.akamaihd.net/i/news_1@194050/master.m3u8

### Notes

The link is dead. 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by fotvnetwork** [comment]
https://bcovlive-a.akamaihd.net/re8d9f611ee4a490a9bb59e52db91414d/us-east-1/734546207001/playlist.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/d94d3b49ba64c9e3985bf40bd5c5b9027f36b5bb/streams/us.m3u#L265-L268
