### ISSUE TITLE
Broken Stream: FOX 25 BOSTON NEWS

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#6853]
### Stream Title

FOX 25 BOSTON NEWS (1080p)

### What happened to the stream?

Not loading

### Possible Replacement

https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00327-coxmediagroup-boston25news-ono/76d97e06-1353-43cd-8998-96773bb0047a/1.m3u8

### Notes

The link is dead.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00327-coxmediagroup-boston25news-ono/playlist.m3u8 geo

**Comment by spotanjo3** [comment]
> https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00327-coxmediagroup-boston25news-ono/playlist.m3u8 geo

It works and closed caption work also. Thanks!

**Comment by LaneSh4d0w** [comment]
> > https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00327-coxmediagroup-boston25news-ono/playlist.m3u8 geo
> 
> It works fine for TELEVIZO on TV ANDROID and closed caption work also. Thanks!

Perfect then, we'll include that in the next batch of valid streams to put out.

**Comment by Central302** [comment]
Current Link Working Now.
