### ISSUE TITLE
Channels add request

### ISSUE THREAD

**Issue by rmkhalfay** [iptv-org/iptv#6859]
### Channel Name

Islam channel urdu (uk)

### Channel ID

Religious m3u 

### Stream URL

https://youtu.be/isAFxOjEWLY

### Notes

Request you to add below channels (free to air) below youtube live links are given:

Category- religious 
https://youtu.be/isAFxOjEWLY islam channel urdu (UK) 
Category- Indian Hindi news
https://youtu.be/MN8p-Vrn6G0 ndtv hindi live (india) 
Category- Indian English news
https://youtu.be/WB-y7_ymPJ4 ndtv 24x7 live (india)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel
