### ISSUE TITLE
Add: TVES

### ISSUE THREAD

**Issue by GiovanniSebastian** [iptv-org/iptv#6864]
### Channel Name

TVES

### Channel ID

TVes.ve

### Website

https://www.tves.gob.ve/en-vivo/

### Stream URL

https://edge1o.live.opencaster.com/caster/erCkqDzdGzpj.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
OpenCaster links cannot be used as they're origin-locked.

**Comment by LaneSh4d0w** [comment]
Sadly we can't deal with Opencaster links. Closing.
