### ISSUE TITLE
Add: Islam Channel Urdu (UK)

### ISSUE THREAD

**Issue by rmkhalfay** [iptv-org/iptv#6868]
### Channel Name

Islam Channel Urdu (UK)

### Channel ID

IslamChannelUrdu.uk

### Website

https://watch.islamchannelurdu.tv/live/

### Stream URL

https://watch.islamchannelurdu.tv/live/

### Notes

Please add the channel under Religious category - Country UK (need m3u link)

https://watch.islamchannelurdu.tv/live/

Youtube link - https://youtu.be/dt4EyIfsE0Y

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by R4IN2007** [comment]
Here A m3u8 Link For This Channel 
https://live-islamtv-urdu.simplestreamcdn.com:443/islamtv_urdu/1/prog_index.m3u8
Or
https://live-islamtv-urdu.simplestreamcdn.com/islamtv_urdu/live.m3u8

**Comment by rmkhalfay** [comment]
Thanks for m3u8 link. In iptv player it does not work. It works in VLC. Can you send me m3u link please? Thanks in advance

**Comment by rmkhalfay** [comment]
The resolution is low. Can I request help in getting at least 720p for this channel. Many thanks in advance

**Comment by LaneSh4d0w** [comment]
There's no 720p in this official stream.

**Comment by rmkhalfay** [comment]
Link not working now

**Comment by rmkhalfay** [comment]
Link not working now as it repeats again and again same video

**Comment by freearhey** [comment]
Closed in favor of #11921
