### ISSUE TITLE
Fort TV

### ISSUE THREAD

**Issue by Tabu12** [iptv-org/iptv#6871]
### Channel Name

Fort Tv (480p)

### Channel ID

Uganda 

### Website

https://www.lyngsat-stream.com/tvchannels/ug/Fort-TV.html

### Stream URL

http://fort.co-works.org:8080/hls/live.stream.m3u8

### Notes

Fort Tv is an entertainment Tv channel stationed in Uganda in a tourism city Fort portal.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Tabu12** [comment]
Let me know when added 😊

**Comment by Tabu12** [comment]
![image](https://user-images.githubusercontent.com/100039363/160450569-3ae205d7-c6af-4eb4-9e81-90dcc19102b9.png)

**Comment by Tabu12** [comment]
![image](https://user-images.githubusercontent.com/100039363/160450757-b874beb7-0e77-4851-a237-5844757fa134.jpeg) And also this. I don know what's the best for you.

**Comment by OscarAteenyi** [comment]
Awww. I can't wait for this to be added 😍

**Comment by Tabu12** [comment]
Hello 🥰

**Comment by Tabu12** [comment]
Hello

Here is Fort TV's new stream link: https://fort.co-works.org/memfs/87017643-274a-4bc0-a786-7767a0d159c2.m3u8

**Comment by Tabu12** [comment]
Please help me update. Thanks
