### ISSUE TITLE
Replace: M1

### ISSUE THREAD

**Issue by fjrider** [iptv-org/iptv#6875]
### Stream Title

"Hungary",M1

### What happened to the stream?

Not loading

### Notes

Stream won't load, tried a couple different IPTV clients.

https://github.com/Free-TV/IPTV/blob/dbdb273edd3eb2cf6adb75521d07475ac3aea292/hungary.md

#EXTINF:-1 tvg-name="M1" tvg-logo="https://i.imgur.com/neddXUd.png" group-title="Hungary",M1
--

http://78.109.104.240:8000/play/a0bs/index.m3u8?HasBahCa.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
I'm sorry, but we can't help you. We have nothing to do with the [Free-TV/IPTV](https://github.com/Free-TV/IPTV) project.
