### ISSUE TITLE
ARY QTV Channel 

### ISSUE THREAD

**Issue by rmkhalfay** [iptv-org/iptv#6886]
### Channel Name

ARY QTV

### Channel ID

ARYQTV.pk

### Website

http://live.aryqtv.tv/mobile/

### Stream URL

http://live.aryqtv.tv/mobile/

### Notes

Please add channel ARY QTV.  Need m3u link for iptv player

This channel is from PAKISTAN 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by trancer1994** [comment]
https://stream.arylive.com/aryqtv/myStream/index.m3u8

**Comment by rmkhalfay** [comment]
Thanks - the resolution is very less; Can it be at least 720p?

**Comment by R4IN2007** [comment]
https://stream.arylive.com:443/aryqtv/myStream/tracks-v1a1/mono.m3u8

**Comment by rmkhalfay** [comment]
Stream link not working?
