### ISSUE TITLE
Add: RTV Zenica

### ISSUE THREAD

**Issue by pukozs75** [iptv-org/iptv#6891]
### Channel Name

RTV Zenica

### Channel ID

RTVZenica.ba

### Website

https://zenicainfo.ba/televizija/

### Notes

Local Bosnian tv channel from Zenica city.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by R4IN2007** [comment]
https://stream.rtvze.ba/live/123/123.m3u8
