### ISSUE TITLE
Fix: Exitosa status is "error" but stream works

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#6898]
### Describe your issue

In [Exitosa website](https://exitosanoticias.pe/v1/tvenvivo/), the [stream](https://cu.onliv3.com/livevd1/user2.m3u8) is same with pe.m3u playlist. But the bot has problems with this stream while tagging as "error". 

On the web page it works normally, but in VLC it seems to show errors.

See its sublinks:

* https://cu.onliv3.com/livevd1/user2_low/index.m3u8
* https://cu.onliv3.com/livevd1/user2_hd720/index.m3u8

**Comment by LaneSh4d0w** [comment]
It is using the same base as VLC for channel verification, so it is not an "bug" *per-se*, but more of a user-agent issue I suppose.

**Comment by freearhey** [comment]
I do not know why this happened, but today the bot has already changed its status to "online".

https://github.com/iptv-org/iptv/blob/1218e5f7f904be2a1e0b54fb21947d72c44a2775/streams/pe.m3u#L86-L87

Perhaps the server was down at the time of the check.

Personally I have this link works fine through VLC and IINA without any changes.

<img width="640" alt="image" src="https://user-images.githubusercontent.com/7253922/161265654-bc81cbd3-2c9d-485f-91d8-367c1580e804.png">

**Comment by LaneSh4d0w** [comment]
Closing this since bot has put this back online.

**Comment by sguinetti** [comment]
Yes, it is already solved. Thanks for the report.
