### ISSUE TITLE
Add: Maspero Zaman

### ISSUE THREAD

**Issue by ayoodi** [iptv-org/iptv#6912]
### Channel Name

Maspero Zaman

### Channel ID

MasperoZaman.eg

### Website

https://iptv-org.github.io/epg/guides/eg-ar/elcinema.com.epg.xml

### Notes

Dear team, Its this time of the year, and I would like your assistance to find this channel to stream it in the Arabic package , or if you can share an M3u list to view it ? 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
576p

#EXTINF:-1,MASPERO ZAMAN (KODI)
https://channelsarabia.xyz/4_.m3u8|Referer=https://live.qanwat-live.com/2021/06/maspero-zaman.html

#EXTINF:-1,MASPERO ZAMAN (VLC)
#EXTVLCOPT:http-referrer=https://live.qanwat-live.com/2021/06/maspero-zaman.html
https://channelsarabia.xyz/4_.m3u8

**Comment by ayoodi** [comment]
Thanks for the quick reply Sphinxroot. 

I tried to open stream for the link above .m3u8 it kept looping and didn't work, also tried on Kodi player and didn't work, could you share another source m3u please :)  Many thanks

**Comment by Sphinxroot** [comment]
![Capture](https://user-images.githubusercontent.com/47762050/161366578-98d42dfc-95e8-4738-95c1-9a638de91407.PNG)

well will check but i got no problem with this stream no buffer no lag :/

**Comment by ayoodi** [comment]
Perfect, I tried the live stream and it worked nicely , Many thanks for your help :)

**Comment by awahid252** [comment]
Hey folks, does anyone have the updated information for this channel "Maspero Zaman"

**Comment by awahid252** [comment]
Anyone?!!
