### ISSUE TITLE
Replace: RUV2

### ISSUE THREAD

**Issue by Albirew** [iptv-org/iptv#6933]
### Stream Title

RUV2

### What happened to the stream?

Not loading

### Notes

Accessing RUV2 (iceland) on web browser shows "Run The Repl To see output." page. may be related.
feeds are still working on website https://www.ruv.is/sjonvarp/beint/ruv2

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
https://ruvlive.akamaized.net/out/v1/2ff7673de40f419fa5164498fae89089/index.m3u8

**Comment by freearhey** [comment]
<img width="751" alt="image" src="https://user-images.githubusercontent.com/7253922/185800671-3e9c5eef-c079-40b3-b1af-6e4b4e734672.png">

**Comment by freearhey** [comment]
The broken link has been removed from the playlist.

Closed in favor: #8165
