### ISSUE TITLE
Replace: MBC 1 KSA

### ISSUE THREAD

**Issue by Mohammednt0** [iptv-org/iptv#6939]
### Stream Title

MBC 1 KSA (1080p) [Geo-blocked]

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
https://shls-mbc1ksa-ak.akamaized.net/out/v1/2fa0d315bd134cb18050f73c3a2b683b/index.mpd

**Comment by KaramAlsammak1** [comment]
Please add mbc iraq back  in
 https://iptv-org.github.io/iptv/regions/arab.m3u

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/632adcf50dd94225be313e35cb3ef7ef2d42f2c0/streams/ae.m3u#L78-L79

**Comment by freearhey** [comment]
Broken link removed from playlist.

Closed in favor #8241
