### ISSUE TITLE
Replace: Al Magharibia TV

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6940]
### Stream Title

Al Magharibia

### What happened to the stream?

Not loading

### Possible Replacement

https://www.youtube.com/watch?v=xnUq9jP3Lmo&ab_channel=AlmagharibiaTV%D9%82%D9%86%D8%A7%D8%A9%D8%A7%D9%84%D9%85%D8%BA%D8%A7%D8%B1%D8%A8%D9%8A%D8%A9

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCwKS2U-DwjPZZvM6mSXPKgA/live

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCwKS2U-DwjPZZvM6mSXPKgA/live
<img width="559" alt="image" src="https://user-images.githubusercontent.com/7253922/185489054-c4e17f86-b316-4b68-8c84-2b5a57b3df89.png">

**Comment by freearhey** [comment]
Couldn't find the original link by the title given.
