### ISSUE TITLE
Add: Belmedia TV From Canada

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6941]
### Channel Name

Belmedia TV

### Channel ID

BelmediaTV.ca

### Website

https://www.youtube.com/watch?v=1FpEhO_vDJc&ab_channel=BelmediaTV-lesKabylesdeMontr%C3%A9al

### Notes

Need URL  for the channel 
a music channel from canada , streems algerians music " kabyle " 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCtj2xA6lW9BPE4BxnhxQQkw/live

**Comment by PD-TheKrazy0ne** [comment]
I get a 500 Internal Server Error on the above link

**Comment by Alstruit** [comment]
Looks like fullspeed.tv works now.
