### ISSUE TITLE
Add: Star TV Tanzania

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6942]
### Channel Name

Star TV

### Channel ID

StarTV.tz

### Website

https://www.twitch.tv/startvtanzania

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/startvtanzania
