### ISSUE TITLE
Add: TVC NEWS  Nigeria

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6943]
### Channel Name

TVC NEWS

### Channel ID

TVCNews.ng

### Website

https://www.youtube.com/watch?v=y4NRAF3cH3E&ab_channel=TVCNewsNigeria

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCgp4A6I8LCWrhUzn-5SbKvA/live

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/13d2f470b7e5b647c0d24d4b6897c651d4b52971/streams/ng.m3u#L8-L9
