### ISSUE TITLE
Add: BF1

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6946]
### Channel Name

BF1

### Channel ID

BF1.bf

### Website

https://bf1.tv/

### Stream URL

https://547f72e6652371c3.mediapackage.us-east-1.amazonaws.com/out/v1/7e66f389bec3463dac81e8d55e680431/index_3.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://547f72e6652371c3.mediapackage.us-east-1.amazonaws.com/out/v1/7e66f389bec3463dac81e8d55e680431/index.m3u8 adaptive
