### ISSUE TITLE
Add: Ivoire Channel

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6947]
### Channel Name

Ivoire Channel

### Channel ID

IvoireChannel.ci

### Stream URL

https://video1.getstreamhosting.com:1936/8244/8244/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
We had analysed getstreamhosting.com, the list is there.

8002 sounds like a test (relaxing sounds and landscapes)
8012 is Espacio Televisión
8018 is Ecclesia TV Côte d'Ivoire
8020 test
8022 is italian channel? (indeed, can't tell however which channel it is from looking at the logo)
8026 is basically a blue faded screen.
8032 is Beraca TV
8038 is Canal 31 CristoVision Costa Rica
8042 is an American radio host, there's no info.
8052 is Pleasant Grove Missionary Baptist Church
8055 is Kaidu TV (english language)
8064 number phone only, test?
8070 is unnamed channel from Africa?
8090 offline
8112 is la uni-k tv (Bolivia)
8130 is Tu Canal Music
8148 music (is name "Que4"?)
8154 music from Africa?
8172 RCG (El Gigante de Coahuila)
8178 Amber TV (Indian channel from USA)
8180 Religious
8192 Music channel from Congo?
8186 Music channel?
8210 Lintelligent.tv
8216 Phone number only
8220 Africa Gospel
8224 B logo (from Bolivia)
8226 InpakTV
8234 Lepanto (Greece)
8244 Ivoire Channel
8248 Lumiere (religious)
8250 ATV12 (French language?)
8252 Ecclesia (Europe?)
8254 white background
8260 Atesur+ (Bolivia)
8264 Waiterlandradio (NL) without image
8266 white background
8272 offline
8274 (I see a film from Arabia, logo is ilegible)
8276 offline
8282 test
8284 Novela Channel, french language
8290 (text and black background)
8296 test
8304 R logo
8308 Mtv HD (no MTV, with Genesis subtitle)
8312 African music
8318 Alpha Omega (italian language)
8326 is HMI hmipromznews.com
8332 Gimdev
8337 is french-language music channel from Africa?
8343 idem?
8348 music channel?
8352 not available
8364 not available: Conway.tv Home Delivery
8366 TMI E
8368 Welcome in several languages (UTRGV)
8392 Unknow (DJ Rook)
8394 music test channel (Mlife fidelity card)
8935 test
8398 Superscreen
8402 TVCariB
8404 BPX TV Reséau
8406 unknow
8408 white background
8410 white background
8418 Waterlandradio
8430 DJ Tony Daniels (test)
8458 Spanish language
8468 Stream
8476 DN Studio
8478 test
8482 CTVN.org
8552 The Biblie Channel
8560 Radio Tele Puissance (Brazil)
8858 (S logo)
8908 test
8964 offline
8975 test
8976 test

**Comment by freearhey** [comment]
https://video1.getstreamhosting.com:1936/8244/8244/playlist.m3u8
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/7253922/190886959-f9015cc5-b240-447d-a506-c828402afff1.png">
