### ISSUE TITLE
Add: NCI ivory coast

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6948]
### Channel Name

NCI

### Channel ID

NCI.ci

### Website

https://www.nci.ci/

### Stream URL

https://nci.cdn.easybroadcast.fr/NCI_HEVC/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://nci.cdn.easybroadcast.fr/NCI_HEVC/index.m3u8
<img width="324" alt="image" src="https://user-images.githubusercontent.com/7253922/186735112-01306899-0cfb-47b2-85dd-e930ab4a93aa.png">

**Comment by freearhey** [comment]
https://nci-live.secure2.footprint.net/nci/nci.isml/.m3u8
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/7253922/190887135-0884ebe6-b51a-49e3-aed9-a81685c600bc.png">
