### ISSUE TITLE
Add: RTI 1

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6949]
### Channel Name

RTI 1

### Channel ID

RTI1.ci

### Website

https://www.rti.ci/

### Stream URL

https://www.enovativecdn.com/rticdn/smil:rti1.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
403

**Comment by hemzaberkane** [comment]
> 403

![Capture d’écran 2022-04-04 121313](https://user-images.githubusercontent.com/79216791/161532437-ca4eb663-31b6-4229-ba71-4165026b4171.png)
WORK FINE

**Comment by LaneSh4d0w** [comment]
No idea, it's blocked in my IP, in France.

**Comment by hemzaberkane** [comment]
> No idea, it's blocked in my IP, in France.

im in algeria , work fine , it seems blocked in your ip

**Comment by Alstruit** [comment]
Works from US. Geo-blocked.
