### ISSUE TITLE
Add: Gabon 24

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6951]
### Channel Name

Gabon 24

### Channel ID

Gabon24.ga

### Website

https://gabon24.tv/

### Stream URL

https://www.youtube.com/channel/UC7E__Dp9FSIgt6iMa5_uvlw/live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UC7E__Dp9FSIgt6iMa5_uvlw/live

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UC7E__Dp9FSIgt6iMa5_uvlw/live (offline)
<img width="802" alt="image" src="https://user-images.githubusercontent.com/7253922/232226869-ba3f18bc-bb6f-43c3-8432-5119a5b433f8.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/ga.m3u#L4-L5
