### ISSUE TITLE
Replace: Nippon tv

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6952]
### Stream Title

Nippon Tv

### What happened to the stream?

Not loading

### Possible Replacement

https://ntv2.mov3.co/hls/ntv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by okonomitarou** [comment]
> ### Stream Title
> Nippon Tv
> 
> ### What happened to the stream?
> Not loading
> 
> ### Possible Replacement
> https://ntv2.mov3.co/hls/ntv.m3u8
> 
> ### Notes
> _No response_
> 
> ### Please confirm the following
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

thank you. It was helpful!

> ### Stream Title
> Nippon Tv
> 
> ### What happened to the stream?
> Not loading
> 
> ### Possible Replacement
> https://ntv2.mov3.co/hls/ntv.m3u8
> 
> ### Notes
> _No response_
> 
> ### Please confirm the following
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

thank you. It was helpful!

**Comment by okonomitarou** [comment]
> ### Stream Title
> Nippon Tv
> 
> ### What happened to the stream?
> Not loading
> 
> ### Possible Replacement
> https://ntv2.mov3.co/hls/ntv.m3u8
> 
> ### Notes
> _No response_
> 
> ### Please confirm the following
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)
thank you. It was helpful!

> ### Stream Title
> Nippon Tv
> 
> ### What happened to the stream?
> Not loading
> 
> ### Possible Replacement
> https://ntv2.mov3.co/hls/ntv.m3u8
> 
> ### Notes
> _No response_
> 
> ### Please confirm the following
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

thank you!
 It was helpful!

> ### Stream Title
> Nippon Tv
> 
> ### What happened to the stream?
> Not loading
> 
> ### Possible Replacement
> https://ntv2.mov3.co/hls/ntv.m3u8
> 
> ### Notes
> _No response_
> 
> ### Please confirm the following
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

thank you. It was helpful!
