### ISSUE TITLE
English only version has non-english channels

### ISSUE THREAD

**Issue by saeedahmed40** [iptv-org/iptv#6957]
### Describe your issue

The repository for the English only iptv channels has many channels from non-english speaking countries such as Hindi, Bangla, Spanish, Arabic and so on.

**Comment by freearhey** [comment]
The thing is that all channel data is taken from [@iptv-org/database](https://github.com/iptv-org/database) and some channels still have imperfect descriptions. As soon as the description is corrected the playlists will be updated. If you want you can do it yourself by editing the [data/channels.csv](https://github.com/iptv-org/database/blob/master/data/channels.csv).
