### ISSUE TITLE
Replace: Fuji TV

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6959]
### Stream Title

Fuji TV

### What happened to the stream?

Not loading

### Possible Replacement

https://fujitv2.mov3.co/hls/fujitv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/632adcf50dd94225be313e35cb3ef7ef2d42f2c0/streams/jp.m3u#L6-L7
