### ISSUE TITLE
Replace: NHK General

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#6961]
### Stream Title

NHK General

### What happened to the stream?

Not loading

### Possible Replacement

https://nhk2.mov3.co/hls/nhk.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by trancer1994** [comment]
Where did you get that link from?
