### ISSUE TITLE
Add: Bang Bang

### ISSUE THREAD

**Issue by WakeAP** [iptv-org/iptv#6970]
### Channel Name

Bang Bang

### Website

https://www.digitalb.al/

### Stream URL

http://199.127.60.117:8081/live/bangbang/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
If you want a BIG list of Albanian channels

#EXTINF:-1,Klan Plus
http://95.107.132.105/out/u/657_1.m3u8
#EXTINF:-1,Klan Kosova
http://95.107.132.105/out/u/694_1.m3u8
#EXTINF:-1,Alsat M
http://95.107.132.105/out/u/645_1.m3u8
#EXTINF:-1,RTV Ora
http://95.107.132.105/out/u/343_1.m3u8
#EXTINF:-1,Fax News
http://95.107.132.105/out/u/228_3.m3u8
#EXTINF:-1,RTSH 1
http://95.107.132.105/out/u/641_4.m3u8
#EXTINF:-1,RTK 1
http://95.107.132.105/out/u/327_1.m3u8
#EXTINF:-1,TV Kopliku
http://95.107.132.105/out/u/152_1.m3u8
#EXTINF:-1,RTV 21
http://95.107.132.105/out/u/490_1.m3u8
#EXTINF:-1,Syri Vision
http://95.107.132.105/out/u/205_1.m3u8
#EXTINF:-1,TV Dukagjini
http://95.107.132.105/out/u/198_3.m3u8
#EXTINF:-1,RTSH Sport
http://95.107.132.105/out/u/638_1.m3u8
#EXTINF:-1,ABC News
http://95.107.132.105/out/u/650_1.m3u8
#EXTINF:-1,Ora News
http://95.107.132.105/out/u/521_2.m3u8
#EXTINF:-1,Kanali 7
http://95.107.132.105/out/u/581_1.m3u8
#EXTINF:-1,News 24
http://95.107.132.105/out/u/660_2.m3u8
#EXTINF:-1,Report TV
http://95.107.132.105/out/u/647_2.m3u8
#EXTINF:-1,Tring Tring
http://95.107.132.105/out/u/353_1.m3u8
#EXTINF:-1,Folk Plus
http://95.107.132.105/out/u/44_1.m3u8
#EXTINF:-1,Elrodi TV
http://95.107.132.105/out/u/156_1.m3u8
#EXTINF:-1,Tring World
http://95.107.132.105/out/u/410_4.m3u8
#EXTINF:-1,KanalD Drama
http://95.107.132.105/out/u/549_1.m3u8
#EXTINF:-1,Jolly
http://95.107.132.105/out/u/463_3.m3u8
#EXTINF:-1,Living
http://95.107.132.105/out/u/480_2.m3u8
#EXTINF:-1,Tring Super
http://95.107.132.105/out/u/689_3.m3u8
#EXTINF:-1,Tring Family
http://95.107.132.105/out/u/673_3.m3u8
#EXTINF:-1,Tring Comedy
http://95.107.132.105/out/u/573_1.m3u8
#EXTINF:-1,3 Plus
http://95.107.132.105/out/u/31_3.m3u8
#EXTINF:-1,Tring Shqip
http://95.107.132.105/out/u/683_1.m3u8
#EXTINF:-1,Tring International
http://95.107.132.105/out/u/609_3.m3u8
#EXTINF:-1,Smile
http://95.107.132.105/out/u/349_2.m3u8
#EXTINF:-1,Klan TV
http://95.107.132.105/out/u/628_1.m3u8
#EXTINF:-1,Club TV
http://95.107.132.105/out/u/87_2.m3u8
#EXTINF:-1,Vizion Plus
http://95.107.132.106/out/u/646_5.m3u8
#EXTINF:-1,Syri TV
http://95.107.132.106/out/u/363_2.m3u8
#EXTINF:-1,Apollon TV
http://95.107.132.106/out/u/328_1.m3u8
#EXTINF:-1,Klan Macedonia
http://95.107.132.106/out/u/783_1.m3u8
#EXTINF:-1,AdriaNet
http://95.107.132.106/out/u/370_1.m3u8
#EXTINF:-1,BBF
http://95.107.132.106/out/u/425_2.m3u8
#EXTINF:-1,Tring Classic
http://95.107.132.106/out/u/842_5.m3u8
#EXTINF:-1,Tring Novelas
http://95.107.132.106/out/u/858_5.m3u8
#EXTINF:-1,Tring Collection
http://95.107.132.106/out/u/847_5.m3u8
#EXTINF:-1,Zjarr TV
http://95.107.132.106/out/u/420_1.m3u8
#EXTINF:-1,Tring Info
http://95.107.132.106/out/u/419_1.m3u8
#EXTINF:-1,Tring Sport 1
http://95.107.132.106/out/u/683_3.m3u8
#EXTINF:-1,Tring Sport 2
http://95.107.132.106/out/u/692_5.m3u8
#EXTINF:-1,Tring Sport 3
http://95.107.132.106/out/u/699_1.m3u8
#EXTINF:-1,Tring Sport 4
http://95.107.132.106/out/u/713_1.m3u8
#EXTINF:-1,Tring Sport News
http://95.107.132.106/out/u/811_1.m3u8
#EXTINF:-1,Tip TV
http://95.107.132.106/out/u/883_1.m3u8
