### ISSUE TITLE
DMCA takedown notices from Premier League

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#6973]
> Hi iptv-org,
> 
> I'm contacting you on behalf of GitHub because we've received a DMCA takedown notice regarding the following content:
> 
> https://github.com/iptv-org/iptv/blob/master/streams/uk.m3u
> 
> We're giving you 1 business day to make the changes identified in the following notice:
> 
> https://github.zendesk.com/attachments/token/F2OfDyHYpychP8uogZQPX7759/?name=2022-04-04-premier-league.rtf
> 
> If you need to remove specific content from your repository, simply making the repository private or deleting it via a commit won't resolve the alleged infringement. Instead, you must follow these instructions to remove the content from your repository's history, even if you don't think it's sensitive:
> 
> https://docs.github.com/articles/remove-sensitive-data
> 
> Once you've made changes, please reply to this message and let us know. If you don't tell us that you've made changes within the next 1 business day, we'll need to disable the entire repository according to our GitHub DMCA Takedown Policy:
> 
> https://docs.github.com/articles/dmca-takedown-policy/
> 
> If you believe your content on GitHub was mistakenly disabled by a DMCA takedown request, you have the right to contest the takedown by submitting a counter notice, as described in our DMCA Takedown Policy.
> 
> PLEASE NOTE: It is important that you reply to this message within 1 business day to tell us whether you've made changes. If you do not, the repository will be disabled.

**Comment by Central302** [comment]
I Thought that USA Network Should add to iptv-org's blacklist (League's Main Broadcaster in US, 
Game is Airing on CNBC and NBC [Selected Match])

**Comment by beibarysyerkin447-dotcom** [comment]
damn you all
