### ISSUE TITLE
Add: Azteca Honduras

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#6981]
### Channel Name

TV Azteca Honduras

### Channel ID

TVAztecaHonduras.hn

### Stream URL

http://190.122.96.187:8888/http/002

### Notes

The Link Work In VLC

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
In [IINA](https://iina.io/) this link also works.

**Comment by Alstruit** [comment]
https://mdstrm.com/live-stream-playlist/60b56be1000ea50835fa1e63.m3u8 -> Geo locked.
