### ISSUE TITLE
Replace: WGN Chicago IL (WGN-TV1)

### ISSUE THREAD

**Issue by PD-TheKrazy0ne** [iptv-org/iptv#6986]
### Stream Title

WGN Chicago IL (WGN-TV1) (720p)

### What happened to the stream?

Not loading

### Notes

#EXTINF:-1 tvg-id="WGNDT1.us" status="online",WGN Chicago IL (WGN-TV1) (720p)
http://trn03.tulix.tv/teleup-mBm5MQ50rA/playlist.m3u8

all http://trn03.tulix.tv/teleup- streams are now non-resposive

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Central302** [comment]
I'm Sad about WGN9 Link is Patched.
Official Stream Link https://wgntv.com/on-air/live-streaming/

https://tkx.mp.lura.live/rest/v2/mcp/video/adstJjQDmxajd3nl?anvack=vLroBA9ZBG3JwTvaOlibbtoPb6L4jqJl&anvtrid=w90632594dc9f0bc8bb33e043e518b505&rtyp=fp&X-Anvato-Adst-Auth=LSzAzlJ55yKR78cD71HKUVwx%2F5LyYH813ViM7w%2BUBXDYukJTBAQ0dLDfJsZZm26sRVDlQASHGjGggbjqBGL8kw%3D%3D
[Short:
https://tkx.mp.lura.live/rest/v2/mcp/video/adstJjQDmxajd3nl?anvack=vLroBA9ZBG3JwTvaOlibbtoPb6L4jqJl&anvtrid=w90632594dc9f0bc8bb33e043e518b505
.
Need a Magic of Someone. (I Wanted to m3u8 Link Even Only Local News)

**Comment by PD-TheKrazy0ne** [comment]
here is an m3u8 I pulled from the link above:
https://dcs-live-ue4.mp.lura.live/server/play/8AkZMW1F8omdfnE0/rendition.m3u8?track=video-2&anvsid=m177635095-n658640b1c39c6245e3da45f14915fae0&ts=1649424239&anvtrid=be323b7fac1ddbcde3d6fe1187ddd462

**Comment by Central302** [comment]
403 Forbidden. Mostly, Anvato Link is Tokened.

**Comment by PD-TheKrazy0ne** [comment]
https://cdn1-8p.teleuptv.net/3773db6d-881b-4096-b9cc-b4fe99ab68ac/index.m3u8

**Comment by PD-TheKrazy0ne** [comment]
https://cdn1-8p.teleuptv.net/3773db6d-881b-4096-b9cc-b4fe99ab68ac/index.m3u8
Referer=https://plus.teleup.com/
User-Agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36 OPR/65.0.3467.48

**Comment by what-a** [comment]
@PD-TheKrazy0ne  Thanks for the info regarding the referrer.  This is now working for me in IPTVnator:

#EXTM3U
#EXTINF:-1 tvg-id="",WGN Chicago
#EXTVLCOPT:http-referrer=https://plus.teleup.com/
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36 OPR/65.0.3467.48
https://cdn1-8p.teleuptv.net/3773db6d-881b-4096-b9cc-b4fe99ab68ac/index.m3u8

**Comment by freearhey** [comment]
Reference:
https://github.com/iptv-org/iptv/blob/7d9bbc7fb2c9a8f595acf0944c111d4d705ced39/streams/us.m3u#L1145-L1146
