### ISSUE TITLE
Add: MNB Family

### ISSUE THREAD

**Issue by fraudiay79** [iptv-org/iptv#7001]
### Channel Name

MNB Гэр бүл

### Website

https://www.mnb.mn/live/family

### Stream URL

https://live.mnb.mn/live/mnb_family.stream/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Not 24/7 ?

**Comment by fraudiay79** [comment]
No

**Comment by LaneSh4d0w** [comment]
OK, can't seem to load from where I am.

**Comment by fraudiay79** [comment]
Its working in the US, but it does buffer quite a but
