### ISSUE TITLE
All JP streams (51.xxxx down)

### ISSUE THREAD

**Issue by Marcoreus89** [iptv-org/iptv#7007]
### Stream Title

NHK G Osaka (720p HLS)

### What happened to the stream?

Shows looped video

### Notes

All playlists, that contains ip address 51.79.193.108 keep repeating the same content

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Duplicate #6845
