### ISSUE TITLE
NHK G Osaka (720p)

### ISSUE THREAD

**Issue by Marcoreus89** [iptv-org/iptv#7017]
### Stream Title

NHK G Osaka (720p HLS)

### What happened to the stream?

Shows looped video

### Notes

All playlists, that contains ip address 51.79.193.108 keep repeating the same content，please don't close,not the same issue

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
The way you wrote the stream title is a mix from our repo and from @luongz 's repo. 
Are you sure it is the correct repository you're mentioning ?

**Comment by Marcoreus89** [comment]
> The way you wrote the stream title is a mix from our repo and from @luongz 's repo. Are you sure it is the correct repository you're mentioning ?

He mentioned the problem that the channel cannot be played. Now the channel can be played, but the same content is played every time.

**Comment by pradolucassamuel-sys** [comment]
> ### Stream Title
> NHK G Osaka (720p HLS)
> 
> ### What happened to the stream?
> Shows looped video
> 
> ### Possible Replacement
> _No response_
> 
> ### Notes
> All playlists, that contains ip address 51.79.193.108 keep repeating the same content，please don't close,not the same issue
> 
> ### Please confirm the following
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

### Stream Title

NHK G Osaka (720p HLS)

### What happened to the stream?

Shows looped video

### Possible Replacement

_No response_

### Notes

All playlists, that contains ip address 51.79.193.108 keep repeating the same content，please don't close,not the same issue

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)
- [ ]
