### ISSUE TITLE
Add: AAJ TAK 

### ISSUE THREAD

**Issue by rmkhalfay** [iptv-org/iptv#7018]
### Channel Name

AAJ TAK (IN)

### Website

https://www.aajtak.in/livetv

### Stream URL

https://www.aajtak.in/livetv

### Notes

Please add this channel - need m3u link please (720p stream); Indian channel HINDI NEWS (FREE TO AIR) https://www.aajtak.in/livetv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://feeds.intoday.in/aajtak/api/master.m3u8
https://feeds.intoday.in/gnt/api/master.m3u8
https://indiatodaylive.akamaized.net/hls/live/2014320/indiatoday/indiatodaylive/playlist.m3u8

**Comment by rmkhalfay** [comment]
Thanks - where I can find all these links for FREE TO AIR channels: Is there any m3u listing?

**Comment by LaneSh4d0w** [comment]
> Thanks - where I can find all these links for FREE TO AIR channels: Is there any m3u listing?

They do not seem to be in our listings, i'll let someone else look after it too for potential geo-locks.

**Comment by rmkhalfay** [comment]
The resolution for above links is less. Can it be improved to 720p?

**Comment by LaneSh4d0w** [comment]
> The resolution for above links is less. Can it be improved to 720p? I think these are free to air channels without any region blocks (is it what you mean by GEO LOCKS?)

There is 720p on all 3 links, it might be your player not scaling through this point.
I meant on a global scape (around the world, it might be playable in India and not in Uzbekistan as an example)
