### ISSUE TITLE
Replace: TV Tokyo

### ISSUE THREAD

**Issue by pavlikmac** [iptv-org/iptv#7026]
### Stream Title

TV Tokyo

### What happened to the stream?

Shows looped video

### Notes

All streams from 51.79.193.108 shows looped video
playlist url: http://51.79.193.108:8080/hls/j00013/index.m3u8?type=jp

### Please confirm the following

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
We are aware of the issue, and this is not something we can deal with. Either we wait until it solves itself, either we totally take them down and search for a new source.

**Comment by F640** [comment]
http://203.162.235.41:16908/
I hope it will survive for long time. Do not play directly in browser's address bar, otherwise it will start download unless you played it on web video player or any standalone video player. It freezes at this time of writing though, hope it will be fixed soon. It also plays in 60 fps (usually achievable only by pure terrestrial and satellite stream).

Note: This it not HLS stream, maybe this is SATIP or something like transport stream to IP (NetUP maybe?).

**Comment by LaneSh4d0w** [comment]
> http://203.162.235.41:16908/
> I hope it will survive for long time. Do not play directly in browser's address bar, otherwise it will start download unless you played it on web video player or any standalone video player. It freezes at this time of writing though, hope it will be fixed soon. It also plays in 60 fps (usually achievable only by pure terrestrial and satellite stream).
> 
> Note: This it not HLS stream, maybe this is SATIP or something like transport stream to IP (NetUP maybe?).

iHome, well known host and very laggy.

**Comment by F640** [comment]
> > http://203.162.235.41:16908/
> > I hope it will survive for long time. Do not play directly in browser's address bar, otherwise it will start download unless you played it on web video player or any standalone video player. It freezes at this time of writing though, hope it will be fixed soon. It also plays in 60 fps (usually achievable only by pure terrestrial and satellite stream).
> > Note: This it not HLS stream, maybe this is SATIP or something like transport stream to IP (NetUP maybe?).
> 
> iHome, well known host and very laggy.

How about this one?
https://stream01.willfonk.com/live_playlist.m3u8?cid=BS297&r=FHD&ccode=JP&m=d0:20:20:04:35:cc&t=0d6938cb3dcf4b79848bc1753a59daf1

Forgot where i downloaded (or grabbed this url) this playlist, but still works as of now. If it's bad one then i'm out of idea for now.

**Comment by LaneSh4d0w** [comment]
> > > http://203.162.235.41:16908/
> > > I hope it will survive for long time. Do not play directly in browser's address bar, otherwise it will start download unless you played it on web video player or any standalone video player. It freezes at this time of writing though, hope it will be fixed soon. It also plays in 60 fps (usually achievable only by pure terrestrial and satellite stream).
> > > Note: This it not HLS stream, maybe this is SATIP or something like transport stream to IP (NetUP maybe?).
> > 
> > iHome, well known host and very laggy.
> 
> How about this one?
> https://stream01.willfonk.com/live_playlist.m3u8?cid=BS297&r=FHD&ccode=JP&m=d0:20:20:04:35:cc&t=0d6938cb3dcf4b79848bc1753a59daf1
> 
> Forgot where i downloaded (or grabbed this url) this playlist, but still works as of now. If it's bad one then i'm out of idea for now.

The owner of this stream reached out to us, asking for deletion. This is a paid subscription that has been hijacked almost 20 days ago it seems.

**Comment by F640** [comment]
> > > > http://203.162.235.41:16908/
> > > > I hope it will survive for long time. Do not play directly in browser's address bar, otherwise it will start download unless you played it on web video player or any standalone video player. It freezes at this time of writing though, hope it will be fixed soon. It also plays in 60 fps (usually achievable only by pure terrestrial and satellite stream).
> > > > Note: This it not HLS stream, maybe this is SATIP or something like transport stream to IP (NetUP maybe?).
> > > 
> > > 
> > > iHome, well known host and very laggy.
> > 
> > 
> > How about this one?
> > https://stream01.willfonk.com/live_playlist.m3u8?cid=BS297&r=FHD&ccode=JP&m=d0:20:20:04:35:cc&t=0d6938cb3dcf4b79848bc1753a59daf1
> > Forgot where i downloaded (or grabbed this url) this playlist, but still works as of now. If it's bad one then i'm out of idea for now.
> 
> The owner of this stream reached out to us, asking for deletion. This is a paid subscription that has been hijacked almost 20 days ago it seems.

Ok then

**Comment by AstaFatherSatan** [comment]
Please remove the link or private the thread. You never know if anyone finds it.

**Comment by LaneSh4d0w** [comment]
removed.

**Comment by AstaFatherSatan** [comment]
I forgotten to mention I have a link from Ihome. I forget if it still works as after I migrated to fedora (just after I learned the iHome link wasn't working I found one online, but the ports are different.) I will update
