### ISSUE TITLE
Please add: https://rotana.net/live

### ISSUE THREAD

**Issue by BountyChocolate123456** [iptv-org/iptv#7044]
### Channel Name

Rotana

### Notes

Can someone please add channels from https://rotana.net/live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Cannot be used as-is.

**Comment by BountyChocolate123456** [comment]
Thanks, it looks like there is temp IP address whitelisting as you can go to https://rotana.net/live-clip and then https://rotananet.hibridcdn.net/rotana/clip_abr/rotana/clip_1080p/chunks.m3u8 will work in VLC.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel
