### ISSUE TITLE
BBC World News 576p stream is in 4:3 stretched to 16:9

### ISSUE THREAD

**Issue by leapofazzam123** [iptv-org/iptv#7051]
### Stream Title

BBC World News (576p)

### What happened to the stream?

I see visual artifacts

### Notes

The 480p stream is in proper 16:9 aspect ratio 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by MapGuy11** [comment]
@LaneSh4d0w can we just remove this? Because we don't control stream URLs.

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w can we just remove this? Because we don't control stream URLs.
> 

It can be closed indeed, we're not responsible for the quality of the streams.

**Comment by MapGuy11** [comment]
We are not responsible for the quality, quantity, or smoothness of the streams. I hope you understand this.

Thanks,

IPTV-org Admins.
