### ISSUE TITLE
Add: NAT GEO , HBO , FOX , SPORT , KIDS CHANNEL

### ISSUE THREAD

**Issue by Rerererererere28** [iptv-org/iptv#7053]
### Channel Name

NAT GEO

### Channel ID

NAT GEO 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Don't make one issue to put multiple channels

**Comment by Rerererererere28** [comment]
okeey sorry

Pada tanggal Jum, 15 Apr 2022 13.36, LaneSh4d0w ***@***.***>
menulis:
