### ISSUE TITLE
Add: Makan 33

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#7057]
### Channel Name

makan tv

### Channel ID

Makan33.il

### Website

https://www.makan.org.il/live/tv.aspx?stationid=25

### Notes

need a long time url for this channel 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
https://www.dailymotion.com/video/x7ymw2l = Private

https://www.dailymotion.com/embed/video/k2slq6Tpsh2bm4wA43P?autoplay=1 = Working

working but will Change Overtime
https://stream-01.nyc.dailymotion.com/sec(8lOMYwOWJB0kD-8STcdDUE_oyvuwHWsfYvEA0sbgUDnWEalRHu6kumRwGDbzHqP3)/dm/3/x7ymw2l/d/live-4.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/13d2f470b7e5b647c0d24d4b6897c651d4b52971/streams/il.m3u#L18-L19
