### ISSUE TITLE
Replace: EarthTV

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#7059]
### Stream Title

Earth TV (1080p)

### What happened to the stream?

Not loading

### Notes

The link doesn't work now: https://iptv-all.lanesh4d0w.repl.co/germany/earth-tv

Live stream available here: https://www.earthtv.com/en

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
Website have tokenized Stream

main live channel = the white house cam
https://www.youtube.com/channel/UCRuyAVeVd7oUwh0LWmxxBBQ/live

THE WORLD LIVE = same as website
https://www.youtube.com/watch?v=3qdEMXmwTkQ
THE WORLD LIVE SHOWCASE
https://www.youtube.com/watch?v=4t96znzCcMQ
WHITE HOUSE LIVE CAM
https://www.youtube.com/watch?v=MvWjBmFt2Bs

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/632adcf50dd94225be313e35cb3ef7ef2d42f2c0/streams/de.m3u#L447-L448

**Comment by freearhey** [comment]
The broken link has been removed from the playlist.

Closed in favor: #8172
