### ISSUE TITLE
Replace: RT Arabic

### ISSUE THREAD

**Issue by saidma** [iptv-org/iptv#7060]
### Stream Title

Rt arabic 

### What happened to the stream?

Not loading

### Notes

https://vk.com/video-17534285_456241592 not geobloqued stream. 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Like ok.ru, those links are IP-locked.

**Comment by Sphinxroot** [comment]
https://rt-arb.rttv.com/live/rtarab/playlist.m3u8  working here   might be isp  mandatory  blocking

**Comment by BountyChocolate123456** [comment]
Already added
