### ISSUE TITLE
Add: MNB HD

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7072]
### Channel Name

MNB

### Channel ID

MNB.mn

### Stream URL

http://103.14.38.107:1935/live/mn2.stream/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by R4IN2007** [comment]
Its Looks Like The Channel Is Offline Or Not
![20220416_174155](https://user-images.githubusercontent.com/83226646/163693463-85b75622-30b2-4000-a339-f70c1fc6afe1.jpg)

**Comment by fraudiay79** [comment]
The channel is not down, it is just not 24/7. Also the channel is not from Russia. It is from Mongolia

**Comment by LaneSh4d0w** [comment]
available in playlist

**Comment by baldi0899** [comment]
> Its Looks Like The Channel Is Offline Or Not ![20220416_174155](https://user-images.githubusercontent.com/83226646/163693463-85b75622-30b2-4000-a339-f70c1fc6afe1.jpg)

Sorry for late, but this MNB News not MNB main
