### ISSUE TITLE
Add: Qazaqstan (International Feed)

### ISSUE THREAD

**Issue by fraudiay79** [iptv-org/iptv#7078]
### Channel Name

Qazaqstan

### Channel ID

Qazaqstan.kz

### Website

https://qazaqstan.tv/live

### Stream URL

https://qazaqstantv-stream.qazcdn.com/international/international/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
KZ stream being https://qazaqstantv-stream.qazcdn.com/qazaqstantv/qazaqstantv/playlist.m3u8 geo
