### ISSUE TITLE
Add: FailArmy

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#7088]
### Channel Name

FailArmy

### Website

https://failarmy-linear.samsung.wurl.com/manifest/playlist.m3u8

### Notes

I am looking for other channel because this link doesn't have closed captions. Thanks. 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
These kind of channels do not have closed captions, as it's basically YouTube compilations. I don't think we'll see this in the near future.
