### ISSUE TITLE
Channel request

### ISSUE THREAD

**Issue by sg1atlantis** [iptv-org/iptv#709]
Please add TBN USA, GOD TV UK, DISNEY CHANNEL INDIA AND HUNGAMA TV KIDS INDIA.

**Comment by anjaneekumar634** [comment]
Plese add more indian channel

**Comment by freearhey** [comment]
**US:**
- [ ] [TBN](https://www.tbn.org/)

**UK:**
- [x] GOD TV
https://github.com/iptv-org/iptv/blob/5f441b34660d903fbcd3832d26109d436378cc0f/channels/uk.m3u#L354-L355

**Indian:**
- [ ] [Disney Channel](http://disneychannel.disney.in/)
- [ ] [Hungama TV](https://hungamatv.ga/)
