### ISSUE TITLE
Add: Eri tv

### ISSUE THREAD

**Issue by kiiiihunter** [iptv-org/iptv#7090]
### Channel Name

Eri tv

### Channel ID

ERITV1.er

### Website

https://www.filmon.com/channel/eri-tv

### Notes

Please add channel and include it in the country category Eritrea. And post .m3u8 link to view in VLC

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.filmon.com/channel/eri-tv works for me.

![snapshot](https://user-images.githubusercontent.com/30985701/163971834-1b7d1c23-6798-46dc-8c6e-48e3acbaf8db.jpg)

**Comment by kiiiihunter** [comment]
I noticed that too. Is there a way to watch it without the 1 minute cut off point.

**Comment by Sphinxroot** [comment]
unsure if it would do the trick  #EXTVLCOPT:http-reconnect=true

**Comment by kiiiihunter** [comment]
Tried it but unfortunately it didn't stop it from cutting out after a minute

**Comment by kiiiihunter** [comment]
I know this channel is also on Nilesat. Is it possible to add this channel from there?

**Comment by Eyob111** [comment]
did you find a new way to use it ?

**Comment by freearhey** [comment]
Closed in favor of #10218
