### ISSUE TITLE
Add: Omega TV - Cyprus

### ISSUE THREAD

**Issue by fraudiay79** [iptv-org/iptv#7093]
### Channel Name

Omega TV

### Channel ID

Omega.cy

### Website

http://www.omegatv.com.cy/live/

### Stream URL

https://l1.cloudskep.com/omegatv/omcy/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9NC8xOS8yMDIyIDE6MDU6MzIgUE0maGFzaF92YWx1ZT1Ta0JVU2sxT3FXUDllR2VENlNxVlF3PT0mdmFsaWRtaW51dGVzPTY2MA==

### Notes

Stream is tokenized.  Was wondering if there was any workaround to get this to work.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://l1.cloudskep.com/omegatv/omcy/playlist.m3u8

**Comment by Sphinxroot** [comment]
server_time=4/20/2022 9:10:30 AM&hash_value=(XXXXXXXXXXXXXX)&validminutes=660

**Comment by LaneSh4d0w** [comment]
Not even the need for a token as far as I see from my side.

**Comment by fraudiay79** [comment]
Thank you.  I can verify from my end no token is needed.
