### ISSUE TITLE
Add: Nat Geo People

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#7096]
### Channel Name

Nat Geo People

### Channel ID

NatGeoPeople.us

### Notes

European feed, preferably the one with English audio.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by spotanjo3** [comment]
Where is the link ?
