### ISSUE TITLE
Add: Ontario Parliamentary Network

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7102]
### Channel Name

Ontario Parliamentary Network

### Channel ID

OntarioParliamentaryNetwork.ca

### Stream URL

http://origin-http-delivery.isilive.ca:80/live/_definst_/ontla/house-en/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
French version : http://origin-http-delivery.isilive.ca/live/_definst_/ontla/house-fr/playlist.m3u8
