### ISSUE TITLE
ARY QTV

### ISSUE THREAD

**Issue by rmkhalfay** [iptv-org/iptv#7107]
### Stream Title

Ary QTV - https://stream.arylive.com/aryqtv/myStream/tracks-v1a1/mono.m3u8

### What happened to the stream?

Not loading

### Notes

Refer to request 6886 the stream link provided is not working; The direct channel live is http://live.aryqtv.tv/ ; Please check

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by fraudiay79** [comment]
https://6zklx4wryw9b-hls-live.5centscdn.com/aryqtvweb/f7b44cfafd5c52223d5498196c8a2e7b.sdp/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
> https://6zklx4wryw9b-hls-live.5centscdn.com/aryqtvweb/f7b44cfafd5c52223d5498196c8a2e7b.sdp/playlist.m3u8
> 
> This is the new link from the website

Needs referer header located on http://live.aryqtv.tv/

**Comment by rmkhalfay** [comment]
The above does not open in VLC and error msg is:
Your input can't be opened:
VLC is unable to open the MRL 'https://6zklx4wryw9b-hls-live.5centscdn.com/aryqtvweb/f7b44cfafd5c52223d5498196c8a2e7b.sdp/playlist.m3u8'. Check the log for details.

**Comment by rmkhalfay** [comment]
Sir. Thanks for link it works fine with VLC but does not work with IPTV player (Perfect player). Is it possible to get link without any referer header needed for play?

**Comment by fraudiay79** [comment]
Try this one:  http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCE2oY4S4wOu6WofU2YbfWsw/live

**Comment by rmkhalfay** [comment]
Many thanks.  This link works
