### ISSUE TITLE
Sengals channels 

### ISSUE THREAD

**Issue by homayon50** [iptv-org/iptv#711]
Hello please can You add RTS 1, walf , sen  from SENGAL ? 
Thanks You!

**Comment by osmanlix** [comment]
western tv istyoruz

**Comment by freearhey** [comment]
Done.
- [x] [RTS1](http://live.rts.sn/livetv/rts1)
https://github.com/iptv-org/iptv/blob/75db9ae6ef79c371671fa01ade1c291e2676f06a/channels/sn.m3u#L14-L15
- [x] Walf TV
https://github.com/iptv-org/iptv/blob/75db9ae6ef79c371671fa01ade1c291e2676f06a/channels/sn.m3u#L10-L11
- [x] [Sen TV](http://sentv.sn/livetv/ledirect)
https://github.com/iptv-org/iptv/blob/75db9ae6ef79c371671fa01ade1c291e2676f06a/channels/sn.m3u#L12-L13
