### ISSUE TITLE
Add: AMC HD | (US)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7113]
### Channel Name

AMC

### Stream URL

https://bcovlive-a.akamaihd.net/ebf15ff84e98490e8b00209ed77c77f5/us-east-1/6240731308001/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by spotanjo3** [comment]
Test and works fine on Televizo for Sony Bravia Android TV. Closed Captioning works too. THANKS!

**Comment by what-a** [comment]
Already exists in the us.m3u playlist...

![image](https://user-images.githubusercontent.com/88639906/164556714-0b081a1c-dcc4-4863-abac-5e2cc0b3e367.png)

**Comment by spotanjo3** [comment]
Do you have or can you find AMCWest.us as well ?

**Comment by what-a** [comment]
I have not come across a stream for AMC West.

**Comment by spotanjo3** [comment]
> I have not come across a stream for AMC West.
[
](https://www.ontvtonight.com/guide/listings/channel/69021867/amc...)
