### ISSUE TITLE
Add: Sundance | (US)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7114]
### Channel Name

Sundance

### Stream URL

https://bcovlive-a.akamaihd.net/d2fcbeaead4b425fa13d4fec961fc47a/us-east-1/6240731308001/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by what-a** [comment]
This is already in the us.m3u playlist...

![image](https://user-images.githubusercontent.com/88639906/164556542-b19e2331-fa31-4f4f-b15e-259c9100fa75.png)
