### ISSUE TITLE
Add: Cartoon Network | Spanish

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7115]
### Channel Name

Cartoon Network 

### Channel ID

CartoonNetworkBrazil.br

### Stream URL

https://playout.cdn.cartoonnetwork.com.br/playout_02/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Sounds Spanish to me...
