### ISSUE TITLE
Not working: MeTV

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#7116]
### Stream Title

meTV

### What happened to the stream?

Not loading

### Possible Replacement

https://5e6cea03e25b6.streamlock.net/live/WCTVDT.stream/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by what-a** [comment]
Use this one instead...
![image](https://user-images.githubusercontent.com/88639906/164555225-7b96cccb-9e5a-444f-a7c8-48ec4871299d.png)
It's from New York, but features the exact same MeTV east coast feed. It's also better quality (720p) than the Tallahassee stream (480p).

**Comment by spotanjo3** [comment]
A link please ?
