### ISSUE TITLE
Not working: Fox News CHANNEL

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#7117]
### Stream Title

Fox News CHANNEL

### What happened to the stream?

Not loading

### Possible Replacement

http://trn03.tulix.tv/AsEAeOtIxz/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by what-a** [comment]
Closing. Same as #7118
