### ISSUE TITLE
Replace: Fox News Channel

### ISSUE THREAD

**Issue by djmu1329** [iptv-org/iptv#7118]
### Stream Title

Fox News Channel (720p)

### What happened to the stream?

Not loading

### Broken Link

http://trn03.tulix.tv/AsEAeOtIxz/playlist.m3u8

### Notes

Current link for Fox News Channel (720p) is no longer loading (http://trn03.tulix.tv/AsEAeOtIxz/playlist.m3u8 ). I have not been able to find a suitable replacement link. 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/632adcf50dd94225be313e35cb3ef7ef2d42f2c0/streams/us.m3u#L475-L476

**Comment by freearhey** [comment]
Closed in favor of #10526
