### ISSUE TITLE
Add:BBC WORLD NEWS 

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#7119]
### Channel Name

BBC WORLD NEWS 

### Stream URL

[_No response_
](http://103.199.161.254/Content/bbcworld/Live/Channel(BBCworld)/index.m3u8
)
### Notes

I have BBC WORLD NEWS (LOW QUALITY) but it is low quality. Looking for high quality. 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by spotanjo3** [comment]
Works fine and closed captioning works as well.

**Comment by LaneSh4d0w** [comment]
> http://gtv01.airlinktt.co/live/smil:BBC_WORLD.smil/playlist.m3u8

I don't know from where you got it, but it's a very rare host lol. Even Google is silent on this one.

**Comment by benevenstanciano** [comment]
Interesting. The link seems to generate a token but in a fairly predictable way? Not sure how you'd go about crawling for more.
