### ISSUE TITLE
Add: Cartoon Network | (Arabic)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7122]
### Channel Name

Cartoon Network 

### Stream URL

https://shls-cartoon-net-prod-dub.shahid.net/out/v1/dc4aa87372374325a66be458f29eab0f/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://github.com/iptv-org/iptv/blob/d6b16c08476ce9ed8ae22af239fe030c72868aed/streams/ae.m3u#L40-L41
