### ISSUE TITLE
Add: PHX TV - (Phoenix TV)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7129]
### Channel Name

PHXTV

### Website

https://www.phoenix.gov/phxtv

### Stream URL

https://granicusliveus8-a.akamaihd.net/phoenix/G1498_002/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
<img width="722" alt="image" src="https://user-images.githubusercontent.com/7253922/185239274-41a0225a-192c-469c-9963-cb52c0d5a8ea.png">

**Comment by R4IN2007** [comment]
https://cdn3.wowza.com:443/5/bGZUOHp2TnhudnM2/phoenix/G1498_002/chunklist.m3u8
