### ISSUE TITLE
Add: FILMEX PELÍCULAS - FILMEX | [XUMO]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7131]
### Channel Name

FILMEX

### Channel ID

Filmex.mx

### Stream URL

https://d26ryn1s9vxsg0.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod-xumo-linear-main-hlsv3/playlist.m3u8?ads.channelId=99951120&ads.caid=FilmexPeliculas&ads.csid=xumo_desktopweb_filmexpeliculas_ssai&ads._fw_is_lat=1&ads._fw_us_privacy=1YNY&ads._fw_coppa=0&ads._fw_did=dpid:1df7027f-55e9-fe11-75cb-998e74101338&ads._fw_vcid2=512116:1df7027f-55e9-fe11-75cb-998e74101338&ads._fw_app_bundle=&ads._fw_app_store_url=&ads._fw_content_category=IAB1-7&ads._fw_content_genre=Latino&ads._fw_content_language=en&ads._fw_content_length=&ads._fw_content_rating=&ads._fw_deviceMake=&ads._fw_device_model=&ads._fw_deviceType=3-Connected_TV&ads.appVersion=&ads.appName=xumo&ads.xumo_contentId=3535&ads.xumo_contentName=FilmexPeliculas&ads.xumo_providerId=3535&ads.xumo_providerName=FilmexPeliculas?.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://filmex-filmex-xumo.amagi.tv/playlist.m3u8 geo to mexico

**Comment by freearhey** [comment]
https://filmex-filmex-xumo.amagi.tv/playlist.m3u8
<img width="684" alt="image" src="https://user-images.githubusercontent.com/7253922/185197482-9ba372f8-5945-4597-9f5c-1c420e5a617c.png">

https://d26ryn1s9vxsg0.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod-xumo-linear-main-hlsv3/playlist.m3u8?ads.channelId=99951120&ads.caid=FilmexPeliculas&ads.csid=xumo_desktopweb_filmexpeliculas_ssai&ads._fw_is_lat=1&ads._fw_us_privacy=1YNY&ads._fw_coppa=0&ads._fw_did=dpid:1df7027f-55e9-fe11-75cb-998e74101338&ads._fw_vcid2=512116:1df7027f-55e9-fe11-75cb-998e74101338&ads._fw_app_bundle=&ads._fw_app_store_url=&ads._fw_content_category=IAB1-7&ads._fw_content_genre=Latino&ads._fw_content_language=en&ads._fw_content_length=&ads._fw_content_rating=&ads._fw_deviceMake=&ads._fw_device_model=&ads._fw_deviceType=3-Connected_TV&ads.appVersion=&ads.appName=xumo&ads.xumo_contentId=3535&ads.xumo_contentName=FilmexPeliculas&ads.xumo_providerId=3535&ads.xumo_providerName=FilmexPeliculas?.m3u8
<img width="406" alt="image" src="https://user-images.githubusercontent.com/7253922/185197581-37c628d9-1804-4978-af1a-ab8d5ae7aad3.png">
via VPN

**Comment by freearhey** [comment]
Both links working again.
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/7253922/190887279-71bf4960-1532-486e-8447-f3481986c175.png">
