### ISSUE TITLE
Add: FILMEX CLÁSICO | [XUMO]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7132]
### Channel Name

FILMEX CLÁSICO

### Channel ID

FilmexClasico.mx

### Stream URL

https://d26ryn1s9vxsg0.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod-xumo-linear-main-hlsv3/playlist.m3u8?ads.channelId=99981121&ads.caid=FilmexClasico&ads.csid=xumo_desktopweb_filmexclasico_ssai&ads._fw_is_lat=1&ads._fw_us_privacy=1YNY&ads._fw_coppa=0&ads._fw_did=dpid:1df7027f-55e9-fe11-75cb-998e74101338&ads._fw_vcid2=512116:1df7027f-55e9-fe11-75cb-998e74101338&ads._fw_app_bundle=&ads._fw_app_store_url=&ads._fw_content_category=IAB1-7&ads._fw_content_genre=Latino&ads._fw_content_language=en&ads._fw_content_length=&ads._fw_content_rating=&ads._fw_deviceMake=&ads._fw_device_model=&ads._fw_deviceType=3-Connected_TV&ads.appVersion=&ads.appName=xumo&ads.xumo_contentId=3536&ads.xumo_contentName=FilmexClasico&ads.xumo_providerId=3536&ads.xumo_providerName=FilmexClasico?.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Simpler : https://filmex-filmexclasico-xumo.amagi.tv/playlist.m3u8

Geo to Mexico

**Comment by freearhey** [comment]
https://filmex-filmexclasico-xumo.amagi.tv/playlist.m3u8
<img width="704" alt="image" src="https://user-images.githubusercontent.com/7253922/185196652-b5bbb860-8515-452c-b1b9-a242d8390bcb.png">

https://d26ryn1s9vxsg0.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod-xumo-linear-main-hlsv3/playlist.m3u8?ads.channelId=99981121&ads.caid=FilmexClasico&ads.csid=xumo_desktopweb_filmexclasico_ssai&ads._fw_is_lat=1&ads._fw_us_privacy=1YNY&ads._fw_coppa=0&ads._fw_did=dpid:1df7027f-55e9-fe11-75cb-998e74101338&ads._fw_vcid2=512116:1df7027f-55e9-fe11-75cb-998e74101338&ads._fw_app_bundle=&ads._fw_app_store_url=&ads._fw_content_category=IAB1-7&ads._fw_content_genre=Latino&ads._fw_content_language=en&ads._fw_content_length=&ads._fw_content_rating=&ads._fw_deviceMake=&ads._fw_device_model=&ads._fw_deviceType=3-Connected_TV&ads.appVersion=&ads.appName=xumo&ads.xumo_contentId=3536&ads.xumo_contentName=FilmexClasico&ads.xumo_providerId=3536&ads.xumo_providerName=FilmexClasico?.m3u8
<img width="409" alt="image" src="https://user-images.githubusercontent.com/7253922/185197173-1b23c33b-8674-4f57-88c5-97270698c07b.png">
via VPN

**Comment by freearhey** [comment]
Both links are working again.
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/7253922/190887530-255b20d2-351d-4aaa-a8d5-a190c4c678ac.png">
