### ISSUE TITLE
Add: SuperSport Kosova 1

### ISSUE THREAD

**Issue by WakeAP** [iptv-org/iptv#7133]
### Channel Name

SuperSport Kosova 1

### Channel ID

SuperSportKosova1.xk

### Website

http://www.digitalb.al

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/database/blob/master/data/blocklist.csv#L723
