### ISSUE TITLE
Add: Talk TV UK

### ISSUE THREAD

**Issue by DamosDub** [iptv-org/iptv#7153]
### Channel Name

Talk TV UK

### Website

https://watch.talk.tv/live?autoplay=true

### Notes

This channel just launched in the UK And can be viewed online at 

https://watch.talk.tv/live?autoplay=true

could someone add the m3u8 if possible? It seems to be geoblocked in ireland also. 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Smark223** [comment]
https://newsuk-talkradiotv-brightcove.amagi.tv/playlist.m3u8

But it keeps buffering for me. Hopefully someone will have a better link...

**Comment by LaneSh4d0w** [comment]
> https://newsuk-talkradiotv-brightcove.amagi.tv/playlist.m3u8 or
> 
> https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00738-newsuk-talkradiotv-ono/playlist.m3u8
> 
> But both keep buffering for me. Hopefully someone will have a better link...

Works perfectly on my side.

**Comment by Smark223** [comment]
> > https://newsuk-talkradiotv-brightcove.amagi.tv/playlist.m3u8 or
> > https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00738-newsuk-talkradiotv-ono/playlist.m3u8
> > But both keep buffering for me. Hopefully someone will have a better link...
> 
> Works perfectly on my side.

Yeah, seems fine now. Think they were having issues with the streams on launch day. Saw a few people mentioning buffering on forums.

**Comment by LaneSh4d0w** [comment]
> > > https://newsuk-talkradiotv-brightcove.amagi.tv/playlist.m3u8 or
> > > https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00738-newsuk-talkradiotv-ono/playlist.m3u8
> > > But both keep buffering for me. Hopefully someone will have a better link...
> > 
> > Works perfectly on my side.
> 
> Yeah, seems fine now. Think they were having issues with the streams on launch day. Saw a few people mentioning buffering on forums.

Certainly the time to stabilise the whole.

**Comment by BountyChocolate123456** [comment]
Even YouTube is choppy https://www.youtube.com/c/talktv/live

you should add it regardless as it will improve over time.
