### ISSUE TITLE
They stole my private m3u and now own my iptv sub

### ISSUE THREAD

**Issue by AstaFatherSatan** [iptv-org/iptv#7160]
[BS and CS channels - s01.zip](https://github.com/iptv-org/iptv/files/8548706/BS.and.CS.channels.-.s01.zip)
[BS and CS channels - s01 - with names.zip](https://github.com/iptv-org/iptv/files/8548765/BS.and.CS.channels.-.s01.-.with.names.zip)

_Originally posted by @LaneSh4d0w in https://github.com/iptv-org/iptv/discussions/7134_

**Comment by LaneSh4d0w** [comment]
@AstaFatherSatan You'll have to manually remove sensitive data from the first edit, following the tutorial here : https://docs.github.com/en/communities/moderating-comments-and-conversations/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history. I am not able to do it myself it seems.

**Comment by AstaFatherSatan** [comment]
@LaneSh4d0w "@[LaneSh4d0w](https://github.com/LaneSh4d0w) LaneSh4d0w changed the title They stole my private m3u and now own my iptv sub issue solved [30 minutes ago](https://github.com/iptv-org/iptv/issues/7160#event-6501991655)" I did what you said.

**Comment by AstaFatherSatan** [comment]
Done.

**Comment by LaneSh4d0w** [comment]
Perfect.
