### ISSUE TITLE
Add: MBC Drama Plus

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7168]
### Channel Name

MBC Drama Plus

### Stream URL

https://shls-mbcplusdrama-prod-dub.shahid.net/out/v1/97ca0ce6fc6142f4b14c0a694af59eab/index_1.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BountyChocolate123456** [comment]
Already there

https://github.com/iptv-org/iptv/blob/master/streams/ae.m3u#L99
