### ISSUE TITLE
Add: GBC Gibraltar

### ISSUE THREAD

**Issue by pukozs75** [iptv-org/iptv#7169]
### Channel Name

GBC TV

### Website

https://www.gbc.gi/tv/watch-live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by F640** [comment]
> https://www.gbc.gi/tv/watch-live

https://player-api.new.livestream.com/accounts/14143407/events/9828641/broadcasts/230962836.secure.m3u8 (1080p adaptive)
Tokenized but playable without token, so i just truncate it.

**Comment by F640** [comment]
Related to #5410. Forgot about that

**Comment by freearhey** [comment]
Duplicate #5410
