### ISSUE TITLE
[Request] [Samusung] ION Television

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#7177]
### Channel Name

Ion Television

### Channel ID

IonTelevision.us

### Website

[Samusung TV Plus (North America)]

### Notes

It Looks Like Samusung Adding Ion Television Channel (I Hope This is National Feed)
![IONTelevision](https://user-images.githubusercontent.com/86145713/165639596-584672d8-2c0e-4df0-b189-9e5af6170f2c.PNG)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by robocopz** [comment]
https://scripps-ion-1-us.samsung.wurl.tv/playlist.m3u8

**Comment by Central302** [comment]
Thanks!

**Comment by spotanjo3** [comment]
Thanks. And closed captions too! :D

**Comment by Delitants** [comment]
Ion Plus is dead on samsung

**Comment by spotanjo3** [comment]
dead
