### ISSUE TITLE
MTV

### ISSUE THREAD

**Issue by aliongminghao** [iptv-org/iptv#7178]
### Channel Name

MTV classic

### Stream URL

https://list.iptvcat.com/my_list/s/fa4eb28992c2c6627b4315405bc20bf2.m3u8

### Notes

Good morning. Can you help me to show the m3u of MTV classic. I'm sorry if my request to complicated. Because I'm still new using this application. Thank you very much.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by aliongminghao** [comment]
Ok ok. Thank you very much.

**Comment by aliongminghao** [comment]
> Link given is an Xtream-Codes server.
> 
> We might find it, but it is very unlikely we get it from official sources. Your best alternative would be looking at Pluto.tv channels.

Ok ok thank you very much.....thank you....thank you.....

**Comment by freearhey** [comment]
Closed in favor #8116
