### ISSUE TITLE
Add : SCTV

### ISSUE THREAD

**Issue by Rerererererere28** [iptv-org/iptv#7185]
### Channel Name

SCTV

### Channel ID

ID

### Website

https://www.sctv.co.id

### Stream URL

-

### Notes

-

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fotvnetwork** [comment]
http://38.127.211.18/live/c2eds/USA/HLS/index.m3u8

**Comment by spotanjo3** [comment]
Can you get other link ? No closed captioning here. My sister's cable for USA Network have closed caption. :(

**Comment by Rerererererere28** [comment]
No, sorry.

Pada tanggal Jum, 29 Apr 2022 18.07, spotanjo3 ***@***.***>
menulis:

**Comment by spotanjo3** [comment]
My mistake. Wrong thread because this is EUROPE. Not in America. Sorry.

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.vidio.com/live/204-sctv/embed?autoplay=false&player_only=true&live_chat=false&enable_websocket=false;

**Comment by Rerererererere28** [comment]
> https://q-s-l4n3sh4d0w.onrender.com/iptv-query?streaming-ip=https://www.vidio.com/live/204-sctv/embed?autoplay=false&player_only=true&live_chat=false&enable_websocket=false;



> https://q-s-l4n3sh4d0w.onrender.com/iptv-query?streaming-ip=https://www.vidio.com/live/204-sctv/embed?autoplay=false&player_only=true&live_chat=false&enable_websocket=false;

Thanks master

**Comment by Rerererererere28** [comment]
Thanks

#EXTINF:-1 group-title="[Live TV]-INDONESIA" logo="https://i.ibb.co/hFC9nw1/sctv-home-tv.png",[Nasional] SCTV
https://q-s-l4n3sh4d0w.onrender.com/iptv-query?streaming-ip=https://www.vidio.com/live/204-sctv/embed?autoplay=false&player_only=true&live_chat=false&enable_websocket=false
