### ISSUE TITLE
Add: Nicktoons

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7190]
### Channel Name

Nicktoons

### Stream URL

http://iptv.prosto.tv:7000/ch70/index.m3u8

### Notes

There Some Errors With This Link

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by R4IN2007** [comment]
Oh

**Comment by freearhey** [comment]
Closed in favor https://github.com/iptv-org/iptv/issues/6103
