### ISSUE TITLE
Add: Wipr Tv (Puerto Rico)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7191]
### Channel Name

Wipr

### Channel ID

WIPRDT1.us

### Stream URL

https://streamwipr.pr/hls/wipr/1_2/index.m3u8?PuertoRicoIPTV.m3u8

### Notes

I Think That This Channel Is Almost Similar To Mega TV

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/7253922/186712444-0b674de9-b4d4-43b2-a67e-b517761e99c1.png">

**Comment by AntiPontifex** [comment]
Added: please close.

**Comment by freearhey** [comment]
Closed in favor of #10767
