### ISSUE TITLE
Add: korean Central TV

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#7194]
### Channel Name

korean Central TV

### Website

https://www.twitch.tv/kctv_elufa

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/kctv_elufa

**Comment by LaneSh4d0w** [comment]
already in playlist
