### ISSUE TITLE
Add: Tele Liban

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#7196]
### Channel Name

Tele Liban

### Website

https://www.teleliban.com.lb/live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BountyChocolate123456** [comment]
Works fine

https://github.com/iptv-org/iptv/blob/master/streams/lb.m3u#L52
