### ISSUE TITLE
Add: AL KAHERA WALNESS

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#7197]
### Channel Name

AL KAHERA WALNESS

### Channel ID

AlKaheraWalNas.eg

### Website

https://www.youtube.com/watch?v=kGIQMgz-ZSY&ab_channel=%D8%A7%D9%84%D9%82%D8%A7%D9%87%D8%B1%D8%A9%D9%88%D8%A7%D9%84%D9%86%D8%A7%D8%B3

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BountyChocolate123456** [comment]
You need to scrape the url as it expires every few days

`curl -s 'http://alkaherawalnas.com/?page_id=14' | grep "youtube.com/embed" | sed -n 1p | sed 's/\"/\n/g' | grep "youtube.com/embed"`

**Comment by AntiPontifex** [comment]
Dead issue: please close.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/eg.m3u#L12-L13
