### ISSUE TITLE
Add Rotana Clip

### ISSUE THREAD

**Issue by BountyChocolate123456** [iptv-org/iptv#7199]
### Channel Name

Rotana Clip

### Channel ID

RotanaClip.sa

### Website

https://rotana.net/live-clip

### Stream URL

https://rotananet.hibridcdn.net/rotana/clip_abr/rotana/clip_1080p/chunks.m3u8

### Notes

You need to open https://rotana.net/live-clip before the m3u8 link works. Is there a way to make it work?

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://hiplayer.hibridcdn.net/p/rotana-kids.m3u8 for the adaptive playlist

I think it's loading a script that gives a valid __llvn_secret token, hence why you need to go to live-clip before accessing the link first.

**Comment by BountyChocolate123456** [comment]
@LaneSh4d0w Thanks for investigation. hiplayer support has been add to streamlink in https://github.com/streamlink/streamlink/pull/4507 so these links can work if you have https://github.com/back-to/liveproxy setup.

I guess https://linkastream.co/headless?url= will support it once a new version of streamlink is released

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w Thanks for investigation. hiplayer support has been add to streamlink in https://github.com/streamlink/streamlink/pull/4507 so these links can work if you have https://github.com/back-to/liveproxy setup.
> 
> I guess https://linkastream.co/headless?url= will support it once a new version of streamlink is released

I could add it to my release and test it.
