### ISSUE TITLE
Iranian Channel Request 

### ISSUE THREAD

**Issue by Alisina92** [iptv-org/iptv#720]
Please Add following channels:
ONYX HD
MBC PERSIA
BAMA TV
ZTV.live  its on satellite  please search it on instagram.
CineFilm 
CineSeries  
BBC PERSIAN

**Comment by freearhey** [comment]
**UK:**
- [ ] [BBC Persian](https://www.bbc.com/persian/tv-and-radio-37434377)

**UAE:**
- [ ] [Onyx](https://www.lyngsat.com/tvchannels/ae/Onyx.html)
- [ ] [MBC Persia](https://www.mbc.net/en/corporate/channels/mbc-persia.html)

**Iranian:**
- [ ] Bama TV
- [ ] [ZTV.live](http://ztv.live/)
- [x] Cine Film
https://github.com/iptv-org/iptv/blob/89f75c44bc346bbea077056fdbe827208e4fe9a1/channels/ir.m3u#L26-L27
- [x] Cine Series
https://github.com/iptv-org/iptv/blob/89f75c44bc346bbea077056fdbe827208e4fe9a1/channels/ir.m3u#L28-L29

**Comment by Hamidslv** [comment]
Pleas add this chanels
Bbc persian
Iran international
Gem onyx
Gem life
Gem junior 
Gem film
Ekran movie
Voa Persian
Khatereh

**Comment by MelalDev** [comment]
#EXTINF:-1,Iran International
https://live.livetvstream.co.uk/LS-63503-3/index.m3u8

#EXTINF:-1,BBC Persian
https://vs-hls-pushb-ww-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_persian_tv/pc_hd_abr_v2.m3u8

it's better to create .m3u file and past you channel in that fle , open that file by your player , even potplayer
