### ISSUE TITLE
Broken: Citra Drama [ID]

### ISSUE THREAD

**Issue by Rerererererere28** [iptv-org/iptv#7201]
### Stream Title

Citra Drama

### Stream URL
http://indo.on-site.x10.mx/Sebuah-Usee/chunklist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Rerererererere28** [comment]
> > http://indo.on-site.x10.mx/Sebuah-Usee/chunklist.m3u8
> 
> Infinite loading for me. Where did you get this link from? ~You also used wrong template, maybe.~

Sorry i replace the title, is the broken link

**Comment by F640** [comment]
> http://indo.on-site.x10.mx/Sebuah-Usee/chunklist.m3u8

You probably mean this: http://indo.on-site.x10.mx/Sebuah-Usee/chunklist.m3u8?id=cdrama&bandwidth=default&sync=0
Stream fragments have error 404.
