### ISSUE TITLE
Add: Nilesat - Eri tv

### ISSUE THREAD

**Issue by kiiiihunter** [iptv-org/iptv#7202]
### Channel Name

Eri tv / Eritrea tv

### Website

Nilesat 201 / Arabsat

### Notes

The channel Eri tv is part of Nilesat 201 and Arabsat. If possible could you please provide a link that would work on vlc that would be great. Thanks.

I know this channel is currently available on filmon but you can't view the link for more than a minute as it cuts off. If you can somehow add it from a different source like Nilesat 201

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kiiiihunter** [comment]
Is it possible to get it from some source like Nilesat 201

**Comment by BountyChocolate123456** [comment]
This is what is available
