### ISSUE TITLE
Add : K+ Life w/ Indonesian Subs

### ISSUE THREAD

**Issue by Rerererererere28** [iptv-org/iptv#7203]
### Stream Title

K+ Life

### What happened to the stream?

Not loading

### Possible Replacement

http://s8212.cdn.mytvnet.vn/pkg20/wrap/xlive.mpd?c=vstv340&offset=1&nodelay=1

### Notes

Please [ID] Sub

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by kirigizakazutovn** [comment]
As far as I know, K+ Life is a pay TV channel in Vietnam. When I looked at some Indonesian IPTV lists, I couldn't find K+ channel.

**Comment by freearhey** [comment]
Couldn't find the channel in the list by the specified title.
