### ISSUE TITLE
I don't see all the channels

### ISSUE THREAD

**Issue by Secret-chest** [iptv-org/iptv#7205]
### Describe your issue

In the database repository and on the website there are 28.665 channels.
Using your stream I get 13245. What is wrong?

My IPTV player is hypnotix.

**Comment by LaneSh4d0w** [comment]
Which URL are you using ?

**Comment by what-a** [comment]
28K sounds way too high.  I use Hypnotix. For reference, when using this URL...
https://iptv-org.github.io/iptv/index.m3u
One gets...
![image](https://user-images.githubusercontent.com/88639906/166116474-cca1de58-0ee5-4b03-92ff-66ec848ade0c.png)

**Comment by Secret-chest** [comment]
> Which URL are you using ?

The main one.

**Comment by Secret-chest** [comment]
> 28K sounds way too high

It says on the website.

**Comment by LaneSh4d0w** [comment]
> > 28K sounds way too high
> 
> It says on the website.

The website does not reflect the number of channels available on the playlists, but the channels available on the csv file.

**Comment by Secret-chest** [comment]
Ah, ok. I see the channels that are not listed are offline.
