### ISSUE TITLE
Add: Indosiar [ID]

### ISSUE THREAD

**Issue by Rerererererere28** [iptv-org/iptv#7208]
### Channel Name

Indosiar

### Channel ID

Indosiar.ID

### Website

-

### Stream URL

-

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by F640** [comment]
Indosiar
https://h1.intechmedia.net/nasional/ch3.m3u8
Geo-blocked, user agent needs to be spoofed to browser ones, and it must be referrerless otherwise it will play youtv app installation procedure.

**Comment by F640** [comment]
This one is even simpler, no need referrer and user agent spoofing.
http://210.210.155.35/qwr9ew/s/s04/index.m3u8

**Comment by Rerererererere28** [comment]
> This one is even simpler, no need referrer and user agent spoofing, but it's geo-blocked like the first one. http://210.210.155.35/qwr9ew/s/s04/index.m3u8

Thanks, u are the best.
