### ISSUE TITLE
Add: Nickelodeon Central and Eastern Europe

### ISSUE THREAD

**Issue by SpongeBu** [iptv-org/iptv#7214]
### Channel Name

Nickelodeon Central and Eastern Europe

### Notes

English
Romanian
Croatian
Bulgarian
Serbian
Czech
Hungarian
Slovenian
Kazakh
Russian
Estonian
Lithuanian
Latvian
Turkish
Polish
Are all of languages this channel broadcast in

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
> IMPORTANT: the issue should contain a request for only one channel, otherwise it will be closed immediately

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel
