### ISSUE TITLE
Please add more arabic sport channels

### ISSUE THREAD

**Issue by rushuckster** [iptv-org/iptv#722]
Hello. If you have time please add more arabic sport channels like:
Iraq sport
bein sports 1 - 10
Al Iraqiya Sports

Thank you and very hope to yours possibilities.

**Comment by themak1985** [comment]
I can help you contribute - but I can't find any streams or Iraq and Iraqiya sports.

**Comment by rushuckster** [comment]
> I can help you contribute - but I can't find any streams or Iraq and Iraqiya sports.

the same - I can't by now I can't find stable stream maybe freearhey can. I think such information maybe found at onion network.

**Comment by boomski** [comment]
For  Iraqiya sports , think  I found these 2 links, but can anyone confirm this is Iraqiya Sports?
https://edge-1192-ch-gv.filmon.com/live/1781.low.stream/playlist.m3u8
https://edge-1192-ch-gv.filmon.com/live/1781.high.stream/playlist.m3u8

**Comment by themak1985** [comment]
@boomski yes and submitted pull request #731

**Comment by themak1985** [comment]
Actually - I made a mistake - this is KSA (Saudi Arabia) Sports - I will make the proper pull requests

**Comment by bermufine** [comment]
Hi 
Please can you add more channels from DRC, mean democratic republic of Congo 
Please if you find any streaming working links with more channels please can you forward to me in my email: congomonpays243@gmail.com

**Comment by freearhey** [comment]
**Iraqi:**
- [ ] [Iraqia Sport](https://www.lyngsat.com/tvchannels/iq/Iraqia-Sport.html) (Al Iraqiya Sports)

**Qatari:**
- [x] BeIn Sports 1
https://github.com/iptv-org/iptv/blob/920f76bd8e9036c0b4588b1fe1a482cfe7fdccea/channels/qa.m3u#L24-L25
- [x] BeIn Sports 2
https://github.com/iptv-org/iptv/blob/920f76bd8e9036c0b4588b1fe1a482cfe7fdccea/channels/qa.m3u#L26-L27
- [x] BeIn Sports 3
https://github.com/iptv-org/iptv/blob/920f76bd8e9036c0b4588b1fe1a482cfe7fdccea/channels/qa.m3u#L28-L29
- [ ] BeIn Sports 4
- [ ] BeIn Sports 5
- [ ] BeIn Sports 6
- [ ] BeIn Sports 7
- [ ] BeIn Sports 8
- [ ] BeIn Sports 9
- [ ] BeIn Sports 10

**Comment by freearhey** [comment]
Closed in favor #1956 and #1955
