### ISSUE TITLE
Add: Streameast Streams

### ISSUE THREAD

**Issue by s66jones** [iptv-org/iptv#7228]
### Channel Name

StreamEast US

### Website

https://www.streameast.xyz

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://www.twitch.tv/streameastlive

**Comment by freearhey** [comment]
> IMPORTANT: the issue should contain a request for only one channel, otherwise it will be closed immediately

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel
