### ISSUE TITLE
Fix: HBO Asia

### ISSUE THREAD

**Issue by 32Dexter** [iptv-org/iptv#7236]
### Stream Title

US: HBO Asia channel not work

### What happened to the stream?

Not loading

### Notes

Hi,
Please can you fix HBO Asia channel in US list?
Thanks a lot

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by R4IN2007** [comment]
Maybe There Problems With The Channel That Doesn't Let It Load
![Screenshot_20220504-182153_TDT en vivo](https://user-images.githubusercontent.com/83226646/166840867-abdf2e82-f4ab-428c-a248-04392e8e9f41.jpg)

**Comment by CrAcK75** [comment]
> Maybe There Problems With The Channel That Doesn't Let It Load ![Screenshot_20220504-182153_TDT en vivo](https://user-images.githubusercontent.com/83226646/166840867-abdf2e82-f4ab-428c-a248-04392e8e9f41.jpg)

That channels needs the browser User Agent to work
could you append the 
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
to fix?

**Comment by F640** [comment]
> > Maybe There Problems With The Channel That Doesn't Let It Load ![Screenshot_20220504-182153_TDT en vivo](https://user-images.githubusercontent.com/83226646/166840867-abdf2e82-f4ab-428c-a248-04392e8e9f41.jpg)
> 
> That channels needs the browser User Agent to work could you append the #EXTVLCOPT:http-user-agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 to fix?
> 
> Thank you so mutch for your epic work!

It also applies to all channels with https://vips-livecdn.fptplay.net/ url, and referrer also must be empty or https://fptplay.vn/

**Comment by Rerererererere28** [comment]
Here


https://vips-livecdn.fptplay.net/hda1/hbo_vhls.smil/chunklist.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/vn_fptplay.m3u#L38-L40
