### ISSUE TITLE
Replace: MBC

### ISSUE THREAD

**Issue by jbcooter** [iptv-org/iptv#7265]
### Stream Title

대구 MBC (MBC Daegu) (480p) [Not 24/7]

### What happened to the stream?

Not loading

### Possible Replacement

MBC

### Notes

Just yesterday there was a working MBC stream (it was non-regional). Now only the regional MBC for South Korea remain but none of them work.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
MBC Daegu : https://5ee1ec6f32118.streamlock.net/live/livetv/playlist.m3u8

which is the same than the one we have on our playlists. It is working, tested right now.

![snapshot](https://user-images.githubusercontent.com/30985701/167806726-a2adbd1d-0089-474d-a957-471c641aeec3.jpg)

**Comment by jbcooter** [comment]
I use the Playlist by Countries and I use South Korea (https://iptv-org.github.io/iptv/countries/kr.m3u). The link you provided works, correct. But it is not the same one reflected in the South Korea playlist by country. 

This is the address of MBC Daegu https://5e04aba713813.streamlock.net/live/livetv/playlist.m3u8 which is different than the working link you provided. I get the same error for all regional MBC on the playlist by country.

**Comment by LaneSh4d0w** [comment]
I see. I'll update those.

**Comment by jbcooter** [comment]
Thanks so much. Yeah, and like I said. There was a working non-regional MBC up until like two days ago. Not sure why it was removed since it seemed fine.

**Comment by jbcooter** [comment]
It seems like you'll add MBC USA in addition to fixing the regional MBC so thank you so much. I appreciate the quick work and all the amazing Korean IPTV.

**Comment by jbcooter** [comment]
MBC Daejon was working until today and now it doesn't work. And now the only two regional MBC that remain are Daejeon and Daegu (a few of the other regionals were removed). I use: https://iptv-org.github.io/iptv/countries/kr.m3u.

**Comment by jbcooter** [comment]
#EXTINF:-1 tvg-id="MBCTV.kr" status="error",MBC (1080p)
http://123.254.72.24:1935/tvlive/livestream2/playlist.m3u8
#EXTINF:-1 tvg-id="ChuncheonMBCTV.kr" status="online",춘천MBC (MBC Chuncheon) (1080p) [Not 24/7]
https://stream.chmbc.co.kr/live/TV/playlist.m3u8
#EXTINF:-1 tvg-id="DaeguMBCTV.kr" status="online",대구 MBC (MBC Daegu) (480p) [Not 24/7]
https://5ee1ec6f32118.streamlock.net/live/livetv/playlist.m3u8
#EXTINF:-1 tvg-id="DaejeonMBCTV.kr" status="online",대전MBC (MBC Daejeon) (720p) [Not 24/7]
https://ns1.tjmbc.co.kr/live/myStream.sdp/playlist.m3u8
#EXTINF:-1 tvg-id="JejuMBCTV.kr" status="online",제주 MBC (MBC Jeju) (352p) [Not 24/7]
https://wowza.jejumbc.com/live/tv_jejumbc/playlist.m3u8

All of these work from my testing on VLC. When they get updated in the playlist for countries. I think all should be fine! Thanks so much.

**Comment by jbcooter** [comment]
There was a working MBC and MBC Daejeon earlier but now they've vanished as well.

**Comment by LaneSh4d0w** [comment]
> There was a working MBC and MBC Daejeon earlier but now they've vanished as well.

Mainly the bot flagging them as error.

**Comment by jbcooter** [comment]
Still not working despite this being closed. There is no working non-regional or regional MBC on https://iptv-org.github.io/iptv/countries/kr.m3u
