### ISSUE TITLE
Add: Seraj tv palestine

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#7267]
### Channel Name

Seraj TV

### Channel ID

SerajTV.ps

### Website

https://seraj.tv/live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by F640** [comment]
https://playback.dacast.com/content/access?contentId=5a3ac7d4-5f58-ec1b-41a7-edbc9c0400b7-live-7fa5c3a3-3790-dbb6-173d-beffdc3663a6&provider=universe
JSON-encoded URL, but you can get m3u8 link from there.

**Comment by LaneSh4d0w** [comment]
https://q-s.l4n3sh4d0w.onrender.com/iptv-query?streaming-ip=https://playback.dacast.com/content/access?contentId=5a3ac7d4-5f58-ec1b-41a7-edbc9c0400b7-live-7fa5c3a3-3790-dbb6-173d-beffdc3663a6&provider=universe

**Comment by LaneSh4d0w** [comment]
https://dacastmmd.mmdlive.lldns.net/dacastmmd/91fd19e6da5d4acd833174df1dd9344d/manifest.m3u8

**Comment by freearhey** [comment]
https://q-s-l4n3sh4d0w.onrender.com/iptv-query?streaming-ip=https://playback.dacast.com/content/access?contentId=5a3ac7d4-5f58-ec1b-41a7-edbc9c0400b7-live-7fa5c3a3-3790-dbb6-173d-beffdc3663a6&provider=universe

> This service has been suspended.

**Comment by LaneSh4d0w** [comment]
Limited in terms of working hours, coming back in September.

**Comment by freearhey** [comment]
https://live01.iflex.ps/Aqsa/index.m3u8
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/7253922/190887900-4225fa80-8320-45f6-8817-c294228c4e30.png">
