### ISSUE TITLE
Livestream.com Streams

### ISSUE THREAD

**Issue by themak1985** [iptv-org/iptv#727]
Trying to add live streams from livestream.com - such as this one
http://www.alfallujah.tv/live-streaming
that is hosted on livestream.com - pulling the link - i get a complex url like this
https://playback2.akamaized.net/streams/4671269_4213685_lsii6az2qrq5asvtfue_1/master.m3u8?dw=14400&hdnts=exp=1574916646~acl=/streams/4671269_4213685_lsii6az2qrq5asvtfue_1/master.m3u8*~hmac=98f4eff0583e3d8bff2f751fc652a0fa5ace9e11aabf207a14bd361cc141f80dc

looks like it expires after a period of time - is there a better way?

**Comment by themak1985** [comment]
Trying to add live streams from livestream.com - such as this one 
http://www.alfallujah.tv/live-streaming
that is hosted on livestream.com - pulling the link - i get a complex url like this 
https://playback2.akamaized.net/streams/4671269_4213685_lsii6az2qrq5asvtfue_1/master.m3u8?dw=14400&hdnts=exp=1574916646~acl=/streams/4671269_4213685_lsii6az2qrq5asvtfue_1/master.m3u8*~hmac=98f4eff0583e3d8bff2f751fc652a0fa5ace9e11aabf207a14bd361cc141f80dc

looks like it expires after a period of time - is there a better way?

**Comment by boomski** [comment]
-Click the share button in the player you get following link:
https://livestream.com/accounts/4671269/events/4213685/player?width=960&height=540&enableInfoAndActivity=true&defaultDrawer=feed&autoPlay=true&mute=false

-use this 
https://player-api.new.livestream.com/

-Then add this part of the share link
accounts/4671269/events/4213685/
-you have this
https://player-api.new.livestream.com/accounts/4671269/events/4213685/

-Add live.m3u8 behind it and you have the link that doesn't expire 

https://player-api.new.livestream.com/accounts/4671269/events/4213685/live.m3u8

**Comment by themak1985** [comment]
Thanks @boomski - that helps.
