### ISSUE TITLE
Add: MTV Lebanon

### ISSUE THREAD

**Issue by abormze** [iptv-org/iptv#7276]
### Channel Name

MTV,LEB

### Channel ID

MTVLebanon.lb

### Website

https://www.elahmad.com/tv/watchtv.php?id=mtv_lebanon

### Stream URL

https://cllive.itworkscdn.net/mtvlebanonlive/token=nva=1652371286~~dirs=1~~hash=0aa600a3219e0ac7d388c/mtvlive.smil/murrtelevision_chunks.m3u8

### Notes

https://cllive.itworkscdn.net/mtvlebanonlive/token 
THIS stream have token how to fix it? any one have fix

https://cllive.itworkscdn.net/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Original links : https://www.mtv.com.lb/OneTV/Live / https://www.mtv.com.lb/vod/ar/live

**Comment by LaneSh4d0w** [comment]
almost sure that if we catch the data for OneTV we might do the same for Murr

**Comment by LaneSh4d0w** [comment]
http://azrotv.com/m3u8/m/?id=mtvliban/hls has got the same too, but it's in clear, inside the hls code... i could try something up with azro links, as long as it is not those xtream-codes links.

**Comment by LaneSh4d0w** [comment]
https://q-s-l4n3sh4d0w.onrender.com/iptv-query?streaming-ip=http://azrotv.com/m3u8/m/?id=mtvliban/hls

**Comment by abormze** [comment]
bro i need it finsh with .m3u8 to working with app you can give me it m3u8?

**Comment by LaneSh4d0w** [comment]
I've pushed an update in which if you add "&noredirect=yes", you can have the URL in clear. That's the only thing I can do.

**Comment by abormze** [comment]
thx bro you can help me with this link
one-tv
http://azrotv.com/iphone/arabic/ch3/onemtvlebanon.php

**Comment by LaneSh4d0w** [comment]
> thx bro you can help me with this link one-tv http://azrotv.com/iphone/arabic/ch3/onemtvlebanon.php

https://q-s-l4n3sh4d0w.onrender.com/iptv-query?streaming-ip=http://azrotv.com/m3u8/m/?id=mtvone/hls&noredirect=yes

**Comment by abormze** [comment]
thx alot bro you good man

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/lb.m3u#L22-L26
