### ISSUE TITLE
Replace: Al Jadeed

### ISSUE THREAD

**Issue by abormze** [iptv-org/iptv#7281]
### Channel Name

jadeed lebanon

### Channel ID

AlJadeed.lb

### Website

http://www.elahmad.com/tv/newtv.php

### Stream URL

https://p-mysat-live.ercdn.net/aljadeed/aljadeed_1080p.m3u8?st=Aq8UrAoWBmt7zHxYlkdyXA&e=1652447318

### Notes

token change evert 10 mintes how fix it

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by abormze** [comment]
not working
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x7ztkw7

**Comment by freearhey** [comment]
Broken link:
https://github.com/iptv-org/iptv/blob/13d2f470b7e5b647c0d24d4b6897c651d4b52971/streams/lb.m3u#L8-L9

**Comment by Alstruit** [comment]
Looks like it's working now. Closing as resolved.

**Comment by brossmee** [comment]
Al Jadeed Lebanon Live
http://azrotv.com/iphone/arabic/ch3/aljadeed.php
