### ISSUE TITLE
Add: Blaze TV

### ISSUE THREAD

**Issue by trancer1994** [iptv-org/iptv#7285]
### Channel Name

Blaze TV

### Website

https://watch.blaze.tv/live/

### Stream URL

https://live.blaze.tv/blaze_live.m3u8?key=6Pr3Uj2Fo3Ix7Rb9Ze9Ro4Ez2Eq7Sy&platform=chrome&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9saXZlLmJsYXplLnR2L2JsYXplX2xpdmUubTN1OD9rZXk9NlByM1VqMkZvM0l4N1JiOVplOVJvNEV6MkVxN1N5JnBsYXRmb3JtPWNocm9tZSIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY1MjQ3MzE0Nn0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIyYTAyOmM3Zjo1YTQ2OjUyMDA6NTUwNjpiYzE1OjcyZjQ6ZGQyMS8zMiJ9fX1dfQ__&Expires=1652473146&Signature=NonFH-d5KTzqZYYlAwAjYNqHRpkhnt2qKmttVw9c89-0VDM7ypKC9zzTL9EZtVo3ZfID2ZUs5NiJuruhwVPkstVj16jYmaHg5X5p8~FMYXB2vG9g9ZtQj7G6qBFVwwgivryKsPdXQsC3NNKILyFS8UrXccdMQ66B8jHJIRKwZddkEHDHUofhMFkAMwgayYtycZ9J8TCi7W8kRN8c4qPz-iajFi6oqYS5~l10t3XUcW72NNnx7~T6rTYi79LZGQsTFn9-EWSc21wX0K055qRgQsfNa6tO0xLh~QZU-XRYLddHWAZ6Rrf5ADoGNPSjIJ4pztXiR5pruZVIKenQ5KMJbw__&Key-Pair-Id=APKAIRYDR7ZRJY4BSCYA

### Notes

This is a channel from the UK which airs documentaries and general entertainment programmes. You will most probably need to use lanesh4d0w5's proxy. The stream is tokened with a key, a policy and a pair id of some sort. Not sure how it's generated. Tried to use his proxy url thingy to generate it but nothing. Maybe it's generated a different way. 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BountyChocolate123456** [comment]
It's complex see https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/dev/resources/lib/channels/uk/blaze.py

**Comment by BountyChocolate123456** [comment]
@LaneSh4d0w label should be UK

**Comment by trancer1994** [comment]
@LaneSh4d0w  A streamlink plugin has now been implemented for this site but it still won't connect even through your proxy, it still says Streamlink reutnred nothing because it couldn't process my request.

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w  A streamlink plugin has now been implemented for this site but it still won't connect even through your proxy, it still says Streamlink reutnred nothing because it couldn't process my request.

I have updated my Streamlink branch, should be available. Had made a PR for USeeTV, that was redone (in a much better way) by their team.

**Comment by trancer1994** [comment]
> 
Still isn't working. What are you using to pipe requests through to Streamlink? I use http://free.fullspeed.tv/iptv-query?streaming-ip=https://watch.blaze.tv/live/ and https://q-s-l4n3sh4d0w.onrender.com/iptv-query?streaming-ip=https://watch.blaze.tv/live/ but they both don't work on VLC. Has your proxy changed or am I doing something wrong?
