### ISSUE TITLE
Al Resalah Arabic Channel Request

### ISSUE THREAD

**Issue by alialiwa2005** [iptv-org/iptv#729]
Hello,
I am requesting an Arabic, Islamic channel, by the name of "Al Resalah" (قناة الرسالة‎ in Arabic.)
Thank you, and have a wonderful day. 
Good luck on future upgrades and keep up the work.

Also, if you can, please add HD streams of al kuran al kareem/makkah live and al sunnah al nabawiah.

Thank you once again.

![image](https://user-images.githubusercontent.com/27908087/69828162-b7aeea00-11e8-11ea-8da7-bcee1a1a3c50.png)

**Comment by freearhey** [comment]
Done.
https://github.com/iptv-org/iptv/blob/25a1f0698ed27d21baf7a57285e6487a3261c314/channels/sa.m3u#L6-L7
