### ISSUE TITLE
Add: YouTV

### ISSUE THREAD

**Issue by eirsik** [iptv-org/iptv#7297]
### Channel Name

YouTV

### Website

https://tv.sikkylab.me

### Stream URL

https://sikkylab.me/tv/stream.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://tv.sikkylab.me/hls/stream.m3u8
