### ISSUE TITLE
Add:  Canal Savoir (French Canadian)

### ISSUE THREAD

**Issue by mikhoul** [iptv-org/iptv#7299]
### Channel Name

Canal Savoir

### Channel ID

CFTUDT.ca

### Website

https://savoir.tv/

### Stream URL

https://hls.savoir.media/live/stream.m3u8

### Notes

HD

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by mikhoul** [comment]
@LaneSh4d0w Canal Savoir have been put in English section instead of French section.

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w Canal Savoir have been put in English section instead of French section.

CA is only for the country, being Canada. Haven't done anything yet with this issue.

**Comment by mikhoul** [comment]
It's because I pull it from the URL sorted by language and it was showing up in English group instead of French group.

![image](https://user-images.githubusercontent.com/5678673/168819737-727845c9-9f0f-4bc8-96be-c9adad7b81dd.png)

**Comment by LaneSh4d0w** [comment]
> It's because I pull it from the URL sorted by language and it was showing up in English group instead of French group.
> 
> ![image](https://user-images.githubusercontent.com/5678673/168819737-727845c9-9f0f-4bc8-96be-c9adad7b81dd.png)

Ah, I see.

**Comment by LaneSh4d0w** [comment]
We found out that Canal Savoir already was in our playlists.

L22-23.
