### ISSUE TITLE
Add: 

### ISSUE THREAD

**Issue by SmogTDI** [iptv-org/iptv#7304]
### Channel Name

LCN.ca

### Channel ID

LCN

### Notes

Need to change the category of existing channel id "LCN.ca" to "News"

 Thank you,

id | "LCN.ca"
name | "LCN"
native_name | null
network | null
country | "CA"
subdivision | null
city | null
broadcast_area | ["c/CA"]
languages | ["fra"]
categories | []
is_nsfw | false
launched | null
closed | null
replaced_by | null
website | "https://www.tvanouvelles.ca/"

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Not an issue for this repo, but fits for [iptv-org/database](https://github.com/iptv-org/database)
