### ISSUE TITLE
Broken Channel: Syfy

### ISSUE THREAD

**Issue by Loading617** [iptv-org/iptv#7318]
### Stream Title

Syfy East (720p)

### What happened to the stream?

Other

### Notes

When I play the channel in IPTV Pro it says "Error playing channel"

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by spotanjo3** [comment]
No, just checking right now. It's working fine. I am watching it right now use TELEVIZ on my SONY OLED ANDROID TV.

**Comment by freearhey** [comment]
Couldn't find the original link by the title given.
