### ISSUE TITLE
Add: Saudi One/Saudi TV

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#7321]
### Channel Name

Saudi One/Saudi TV

### Channel ID

SaudiTV.sa

### Website

https://www.aloula.sa/live/saudiatv

### Notes

There's a tokenized stream in the website.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by BountyChocolate123456** [comment]
Exists https://github.com/iptv-org/iptv/blob/master/streams/sa.m3u#L26
