### ISSUE TITLE
Add: WGN

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#7322]
### Channel Name

WGN

### Channel ID

WGNHD.us

### Website

https://wgntv.com/on-air/live-streaming/

### Notes

There's a tokenized stream in the website.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Covered by https://github.com/iptv-org/iptv/pull/7317
