### ISSUE TITLE
Add: SEA Today

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#7323]
### Channel Name

SEA Today

### Channel ID

SEAToday.id

### Website

https://seatoday.com/live

### Notes

Therre's a tokenized stream in the website.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by F640** [comment]
It's already in this playlist actually, but in mpeg-dash. So this is HLS version: https://cdn-telkomsel-01.akamaized.net/Content/HLS/Live/channel(9ce3f094-4044-467e-84b7-b684a49571d5)/index.m3u8

**Comment by LaneSh4d0w** [comment]
USeeTV plugin has just been released by Streamlink.

https://q-s-l4n3sh4d0w.onrender.com/iptv-query?streaming-iptv=https://www.useetv.com/livetv/seatoday

**Comment by F640** [comment]
> USeeTV plugin has just been released by Streamlink.
> 
> https://q-s-l4n3sh4d0w.onrender.com/iptv-query?streaming-ip=https://www.useetv.com/livetv/seatoday

First try: 
> Streamlink returned nothing from query None, reason being You didn't give any URL

Second try: 
> Streamlink returned nothing from query https://www.useetv.com/livetv/seatoday, reason being Streamlink couldn't process https://www.useetv.com/livetv/seatoday, because of a Plugin error. Reason is as follows: Unable to open URL: https://www.useetv.com/livetv/seatoday (HTTPSConnectionPool(host='www.useetv.com', port=443): Max retries exceeded with url: /livetv/seatoday (Caused by ConnectTimeoutError(, 'Connection to www.useetv.com timed out. (connect timeout=20.0)')))

Usse TV geo-blocked to Indonesia and its base m3u8 as well as its segments refuse some user agent (like VLC).
Your proxy rate limiting is little annoying. Probably due to private WAN IP from my side.

**Comment by LaneSh4d0w** [comment]
> > USeeTV plugin has just been released by Streamlink.
> > https://q-s-l4n3sh4d0w.onrender.com/iptv-query?streaming-ip=https://www.useetv.com/livetv/seatoday
> 
> First try:
> 
> > Streamlink returned nothing from query None, reason being You didn't give any URL
> 
> Second try:
> 
> > Streamlink returned nothing from query https://www.useetv.com/livetv/seatoday, reason being Streamlink couldn't process https://www.useetv.com/livetv/seatoday, because of a Plugin error. Reason is as follows: Unable to open URL: https://www.useetv.com/livetv/seatoday (HTTPSConnectionPool(host='www.useetv.com', port=443): Max retries exceeded with url: /livetv/seatoday (Caused by ConnectTimeoutError(, 'Connection to [www.useetv.com](http://www.useetv.com) timed out. (connect timeout=20.0)')))
> 
> Usee TV is geo-blocked to Indonesia and its base m3u8 as well as its segments refuse some user agent (like VLC). Your proxy rate limiting is little annoying. Probably due to private WAN IP from my side.
> 
> EDIT: SEA Today does not geo-blocked in Usee TV using VPN (Singapore VPN IP).

Rate limiting is needed, due to number of persons spamming requests it seems.

For now, I have high peaks over TPA 1 and TV Zimbo (Angola).
