### ISSUE TITLE
Add: Dog TV

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#7333]
### Channel Name

Dog TV

### Channel ID

DogTV.us

### Website

http://api.new.livestream.com/accounts/29590904/events/9415369/

### Notes

The link above generates a tokenized m3u8 link that expires.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://q-s-l4n3sh4d0w.onrender.com/iptv-query?streaming-ip=http://api.new.livestream.com/accounts/29590904/events/9415369/
