### ISSUE TITLE
Add: TCT Kids

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#7334]
### Channel Name

TCT Kids

### Channel ID

TCTKids.us

### Website

https://api.new.livestream.com/accounts/29565692/events/9321713/

### Notes

The link above generates a tokenized m3u8 link that expires.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by trancer1994** [comment]
https://api.new.livestream.com/accounts/29565692/events/9321713/live.m3u8

**Comment by thedarkdragon11** [comment]
> 

Sadly, it doesn't work.

**Comment by LaneSh4d0w** [comment]
I've added a workaround for hidden streams, bear with me while I deploy the changes.

**Comment by LaneSh4d0w** [comment]
Should work pretty soon with https://q-s-l4n3sh4d0w.onrender.com/iptv-query?streaming-ip=https://api.new.livestream.com/accounts/29565692/events/9321713/
