### ISSUE TITLE
Food Network Canada | Channel Request

### ISSUE THREAD

**Issue by alialiwa2005** [iptv-org/iptv#734]
Hello, I am requesting the channel, Food Network Canada to be added when possible.
Thank you.
![food-network-canada](https://user-images.githubusercontent.com/27908087/69900810-46854900-1346-11ea-9e55-76dba25d66f2.jpg)

**Comment by freearhey** [comment]
We cannot add this channel to the playlist due to claims of the copyright holder. More details here: https://github.com/iptv-org/iptv/issues/1831
