### ISSUE TITLE
Add: Hope Channel Philippines

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#7346]
### Channel Name

Hope Channel Philippines

### Channel ID

HopeChannelPhilippines.ph

### Website

https://www.hopechannel.ph/watch/

### Notes

That's their new official streaming page. The stream link has token that changes.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fotvnetwork** [comment]
[Non-tokenized link still available](https://videodelivery.net/102633a56c6e158023dd195b6d117566/manifest/video.m3u8)
