### ISSUE TITLE
TruTV | Channel Request

### ISSUE THREAD

**Issue by alialiwa2005** [iptv-org/iptv#735]
Hello, I am requesting the channel, TruTV, to be added when possible.
Thank you.
![trutv-logo-1920x1080_75](https://user-images.githubusercontent.com/27908087/69900845-80eee600-1346-11ea-963b-8e46fa47bdbc.jpg)

**Comment by freearhey** [comment]
Done.
https://github.com/iptv-org/iptv/blob/6abfa134b0988d6e8f61de55094982d502342904/channels/us.m3u#L966-L969
