### ISSUE TITLE
Add: EGG Network

### ISSUE THREAD

**Issue by Rushdiey** [iptv-org/iptv#7357]
### Channel Name

EGG Network

### Channel ID

EggNetwork.my

### Stream URL

http://210.210.155.37/uq2663/h/h22/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/e30156eaa294ec32152101b0a8e1d35b92dbf67b/streams/my.m3u#L16-L17

**Comment by SonicPhoon** [comment]
Almost all astro related channel unable to connect

**Comment by LaneSh4d0w** [comment]
I preferred to wait before removing them. Going to do so in the maintenance PR.
