### ISSUE TITLE
Re-add A&E | Error-Found/Channel Re-Request

### ISSUE THREAD

**Issue by alialiwa2005** [iptv-org/iptv#736]
Hello, the current US channel, A&E, is not working correctly.
Please re-add a working stream when possible, and maybe remove the broken one.
Thank you.

![A E-Network-Logo svg](https://user-images.githubusercontent.com/27908087/69900878-f3f85c80-1346-11ea-91bd-0ed17f45626c.png)

**Comment by alialiwa2005** [comment]
Also not playing:
- History Channel HD

**Comment by freearhey** [comment]
Done.
https://github.com/iptv-org/iptv/blob/6abfa134b0988d6e8f61de55094982d502342904/channels/us.m3u#L958-L961
