### ISSUE TITLE
Add: UZ SPORT

### ISSUE THREAD

**Issue by pukozs75** [iptv-org/iptv#7361]
### Channel Name

Uzbekistan SPORT

### Website

https://spbtv.online/channels/sport-uz.html

### Notes

Can you please add this channel to the sports playlist?

### Please confirm the following

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
https://streaming.spbtv.com/ +base64 token /ip_v5/101.mpd .... channel id and so on

output come from 
https://api-cn.spbtv.com/v1/channels/2ec52cad-9358-410c-98ca-d2e3f0291649/stream.json?client_id=355de73b-ccd8-46a7-bd23-ea3d65d77f41&client_version=3.1.0.390&timezone=-14400&locale=fr&protocol=dash&video_codec=h264&audio_codec=mp4a&drm=spbtvcas&screen_width=1920&screen_height=1080&device_token=8f1d4137-7a1b-4ca9-ba71-c85825df89fc

**Comment by freearhey** [comment]
Duplicate #7229
