### ISSUE TITLE
Add: PIE Channel

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#7363]
### Channel Name

PIE Channel

### Channel ID

PIE.ph

### Website

https://pie.com.ph/join

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCAxAaFQnH5IK_ZTwiQWV-9A/live

### Notes

It's a new PH channel. The link works in the first 2 days. It displays an error now.

"Could not get the link, Streamlink couldn't read https://www.youtube.com/channel/UCAxAaFQnH5IK_ZTwiQWV-9A/live"

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fotvnetwork** [comment]
> > Stream is locked to Philippine territories
> 
> Any ways to bypass?

I think a VPN or some proxy

**Comment by LaneSh4d0w** [comment]
Geo-locked to PH, can't do anything about it.

https://www.youtube.com/watch?v=OVRAyUBd5Fg

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCAxAaFQnH5IK_ZTwiQWV-9A/live
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/7253922/190888018-cd396058-2fb9-4eb9-9552-7761684ce64c.png">
