### ISSUE TITLE
Cartoon Network USA and Cartoon Network Canada | Channel Requests

### ISSUE THREAD

**Issue by alialiwa2005** [iptv-org/iptv#737]
Hello, please add Cartoon Network USA and Cartoon Network Canada. Currently, there're only Cartoon Network Turkish and Arabic. So please, if and when possible, add the following channels:
- Cartoon Network Canada
- Cartoon Network United States

Thanks.
![image](https://user-images.githubusercontent.com/27908087/69902598-b7842b00-135d-11ea-9c4f-3c573e8aba58.png)

**Comment by freearhey** [comment]
**Canadian:**
- [ ] Cartoon Network

**US:**
- [x] Cartoon Network
https://github.com/iptv-org/iptv/blob/6abfa134b0988d6e8f61de55094982d502342904/channels/us.m3u#L954-L957

**Comment by freearhey** [comment]
Closed in favor #1942 and #1941

**Comment by cold360** [comment]
cartoon network (east feed)
https://z88.ubtvfans.com/live/rx3/1211/28866767ab5bb79ac1105c3918b957d2/index.m3u8
