### ISSUE TITLE
Add: A Spor

### ISSUE THREAD

**Issue by pukozs75** [iptv-org/iptv#7371]
### Channel Name

A Spor

### Channel ID

ASpor.tr

### Website

https://www.aspor.com.tr/webtv/canli-yayin

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Daion-backed service : https://trkvz-beta.daioncdn.net/aspor/aspor.m3u8?ce=3&app=45f847c4-04e8-419a-a561-2ebf87084765&st=ZzdkHYKEn7X6qT4aZnxrxQ&e=1653951043

https://q-s-l4n3sh4d0w.onrender.com/iptv-query?streaming-ip=https://www.aspor.com.tr/webtv/canli-yayin

**Comment by LaneSh4d0w** [comment]
> https://trkvz-beta.daioncdn.net/aspor/aspor_1080p.m3u8?sid=4gjogj74f6wi

works

**Comment by freearhey** [comment]
<img width="734" alt="image" src="https://user-images.githubusercontent.com/7253922/186713320-56c0a853-b1e4-46f9-b233-34ef192f56b3.png">

**Comment by freearhey** [comment]
https://trkvz-beta.daioncdn.net/aspor/aspor.m3u8?ce=3&app=45f847c4-04e8-419a-a561-2ebf87084765&st=ZzdkHYKEn7X6qT4aZnxrxQ&e=1653951043 (offline)
<img width="843" alt="image" src="https://user-images.githubusercontent.com/7253922/232227512-a591688d-3102-4266-a0c1-496502dcee67.png">

https://q-s-l4n3sh4d0w.onrender.com/iptv-query?streaming-ip=https://www.aspor.com.tr/webtv/canli-yayin (offline)
<img width="745" alt="image" src="https://user-images.githubusercontent.com/7253922/232227534-582674cb-260b-4d4e-9fbe-2d295b698e6d.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/tr.m3u#L484-L485
