### ISSUE TITLE
Boomerang US and Boomerang Canada | Channel Requests

### ISSUE THREAD

**Issue by alialiwa2005** [iptv-org/iptv#738]
Hello, please add Boomerang TV USA and Boomerang TV Canada. 
Currently, there's only a Boomerang UK. 
So please, if and when possible, add the following channels:

- Boomerang Canada
- Boomerang United States
Thanks.

![image](https://user-images.githubusercontent.com/27908087/69902628-029e3e00-135e-11ea-86cb-58b50a76237e.png)

**Comment by freearhey** [comment]
**Canadian:**
- [ ] Boomerang

**US:**
- [x] Boomerang
https://github.com/iptv-org/iptv/blob/6abfa134b0988d6e8f61de55094982d502342904/channels/us.m3u#L952-L953

**Comment by freearhey** [comment]
Closed in favor #1942 and #1941

**Comment by cold360** [comment]
uh? came here from boomerang? nothing? :c

**Comment by spotanjo3** [comment]
No boomerang USA channel ?

**Comment by voxelgit** [comment]
lmao

**Comment by nina1990ap-design** [comment]
> No boomerang USA channel ?

http://23.237.104.106:8080/USA_BOOMERANG/index.m3u8
