### ISSUE TITLE
Food Network United States | Channel Request

### ISSUE THREAD

**Issue by alialiwa2005** [iptv-org/iptv#739]
Hello,
Please add Food Network (US).
Currently there is only Food Network UK, so please add a USA channel when possible.
Thanks.
![image](https://user-images.githubusercontent.com/27908087/69902659-485b0680-135e-11ea-8f6c-96f78887a839.png)

**Comment by MapGuy11** [comment]
There Is GEOLOCK and encryption Discovery recently but very hard encryption so unless someone wants to run a ffmpeg server to restream there is no way around it. Sorry!

**Comment by freearhey** [comment]
Done.
https://github.com/iptv-org/iptv/blob/6abfa134b0988d6e8f61de55094982d502342904/channels/us.m3u#L948-L951
