### ISSUE TITLE
Add: Cablenoticias (Bogotà | Colombia)

### ISSUE THREAD

**Issue by LaneSh4d0w** [iptv-org/iptv#7392]
### Channel Name

Cablenoticias (Bogotà | Colombia)

### Channel ID

Cablenoticias.co

### Website

https://www.cablenoticias.tv

### Notes

Says they stream from their website, but I can't seem to find anything.

YouTube : https://www.youtube.com/cablenoticias

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Maybe a Colombian citizen (or close to Colombia) has got the answer. Most certainly @thetucan1 ?

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-logo="https://cnwebsite.blob.core.windows.net/files/2021/05/logo_cablenoticias.png" group-title="",Cablenoticias
https://5ea86ddd14ce7.streamlock.net/live/cable09061970/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
Well done @Sphinxroot , adding it.
