### ISSUE TITLE
Nickelodeon Channels USA | Channels Request

### ISSUE THREAD

**Issue by alialiwa2005** [iptv-org/iptv#740]
Hello, please add Nickelodeon (US), and its sister channels, when possible.
Please add, (US channels):

- Nick at Nite
- Nick Jr.
- Nicktoons
- TeenNick
- NickMusic

![image](https://user-images.githubusercontent.com/27908087/69902742-ec44b200-135e-11ea-8a16-89e753ba5d07.png)
![image](https://user-images.githubusercontent.com/27908087/69902745-f070cf80-135e-11ea-9d67-6a027c2a7447.png)

**Comment by freearhey** [comment]
Nick, Nick Jr. and Nicktoons:
https://github.com/iptv-org/iptv/blob/fd9752a9f09931f8a52342f97503430dd3c46d3b/channels/us.m3u#L920-L925

**Comment by alialiwa2005** [comment]
Not working.

**Comment by freearhey** [comment]
- [ ] Nick@Nite
- [ ] NickMusic
- [x] Nick Jr.
https://github.com/iptv-org/iptv/blob/6abfa134b0988d6e8f61de55094982d502342904/channels/us.m3u#L932-L935
- [x] Nicktoons
https://github.com/iptv-org/iptv/blob/6abfa134b0988d6e8f61de55094982d502342904/channels/us.m3u#L942-L945
- [x] TeenNick
https://github.com/iptv-org/iptv/blob/6abfa134b0988d6e8f61de55094982d502342904/channels/us.m3u#L936-L941

**Comment by freearhey** [comment]
Closed in favor #1942
