### ISSUE TITLE
myTV (KCWX-TV) w/closed captioning

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#7407]
### Channel Name

myTV

### Channel ID

KCWXDT1.us

### Stream URL

http://65.36.6.216:1935/live/kcwx.smil/playlist.m3u8

### Notes

You have myTV (KCWX-TV) (720p) [Not 24/7] but it didn't have closed captioning. I am looking for other channel. I watched regular antenna tv and it does have a closed captioning. I want to watch it on android. 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by MapGuy11** [comment]
This link comes from the provider of the channel and since they haven't added Closed Captioning there is nothing we can do on our end to add it back. Sorry for the inconvenience ;(

**Comment by spotanjo3** [comment]
> This link comes from the provider of the channel and since they haven't added Closed Captioning there is nothing we can do on our end to add it back. Sorry for the inconvenience ;(

No worries. Thats alright. What about SYFY off topic for the closed caption. It was worked before and now all the suddenly, no CC. I dont understand. Can you check cable ? I have free online and it works fine with CC but as I said before, I dont know if I can send you those lists streaming online. I think those are illegal included TLC and many more.

**Comment by MapGuy11** [comment]
> > This link comes from the provider of the channel and since they haven't added Closed Captioning there is nothing we can do on our end to add it back. Sorry for the inconvenience ;(
> 
> No worries. Thats alright. What about SYFY off topic for the closed caption. It was worked before and now all the suddenly, no CC. I dont understand. Can you check cable ? I have free online and it works fine with CC but as I said before, I dont know if I can send you those lists streaming online. I think those are illegal included TLC and many more.

You can send them and I will delete them here. For SYFY I don't know they seemed to just remove CC really no reason behind it but that's what you get with free.

**Comment by spotanjo3** [comment]
> > > This link comes from the provider of the channel and since they haven't added Closed Captioning there is nothing we can do on our end to add it back. Sorry for the inconvenience ;(
> > 
> > 
> > No worries. Thats alright. What about SYFY off topic for the closed caption. It was worked before and now all the suddenly, no CC. I dont understand. Can you check cable ? I have free online and it works fine with CC but as I said before, I dont know if I can send you those lists streaming online. I think those are illegal included TLC and many more.
> 
> You can send them and I will delete them here. For SYFY I don't know they seemed to just remove CC really no reason behind it but that's what you get with free.

Ok. There you go: 

https://ustvgo.tv/

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/aa1b83ea259229adf86ff2cebbf4ef281129e8e6/streams/us_local.m3u#L232-L233
