### ISSUE TITLE
Paramount Network (USA) | Channel Request

### ISSUE THREAD

**Issue by alialiwa2005** [iptv-org/iptv#741]
Hello, please add Paramount Network, when possible, to your list.
Paramount is an American-Based, English-Language Audio, channel.
Thank you.
![image](https://user-images.githubusercontent.com/27908087/69902777-4180c380-135f-11ea-97b4-c24d6f72eb7c.png)

**Comment by freearhey** [comment]
Done.
https://github.com/iptv-org/iptv/blob/6abfa134b0988d6e8f61de55094982d502342904/channels/us.m3u#L922-L923
