### ISSUE TITLE
Add: Manoto tv channel

### ISSUE THREAD

**Issue by peyman47** [iptv-org/iptv#7411]
### Channel Name

Manoto tv

### Website

manototv.com

### Notes

it worked 2 days ago

### Please confirm the following

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
# https://www.manototv.com/live
#EXTINF:-1 tvg-logo="https://i.imgur.com/w2Fiyq5.png" group-title="",ManotoTV
https://dh4wkqcyy8768.cloudfront.net/live.m3u8

**Comment by LaneSh4d0w** [comment]
per data, it should be in "uk.m3u" : https://en.wikipedia.org/wiki/Manoto

**Comment by peyman47** [comment]
> per data, it should be in "uk.m3u" : https://en.wikipedia.org/wiki/Manoto

persian language
it was in fas.m3u & ir. m3u last week

**Comment by peyman47** [comment]
manoto tv has been set to error
#EXTINF:-1 tvg-id="Manoto.uk" status="error",Manoto TV (1080p)
https://dh4wkqcyy8768.cloudfront.net/live.m3u8
set status to online
