### ISSUE TITLE
Add: Cartoon Network Japan 

### ISSUE THREAD

**Issue by omaromarver** [iptv-org/iptv#7412]
### Channel Name

Cartoon Network

### Channel ID

CartoonNetworkJapan.jp

### Website

https://www.cartoonnetwork.jp/

### Stream URL

http://iptv12k.com:35461/80301051401/878900/3152

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Xtream-Codes server, cannot be added.

**Comment by freearhey** [comment]
Closed in favor of #10807
