### ISSUE TITLE
Channel availible on "iptv-org.github.io" but not in index.m3u

### ISSUE THREAD

**Issue by amirbouraoui** [iptv-org/iptv#7415]
### Describe your issue

Why does the channel "TF1" can be found on "iptv-org.github.io" but not in the channel index?

<img width="1155" alt="Screenshot 2022-06-02 at 01 35 11" src="https://user-images.githubusercontent.com/48432425/171518687-b5c47343-c45f-4ab0-ba75-dc21abeb209c.png">

**Comment by freearhey** [comment]
Also if you click on "Streams" you will see a list of all the links with details.

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/7253922/171620411-6260a206-08ad-49ef-99ba-a9cd24c57a5b.png">

**Comment by rojasjordi02-spec** [comment]
https://github.com/iptv-org/iptv/issues/7415

**Comment by rojasjordi02-spec** [comment]
https://github.com/iptv-org/iptv/issues/7415#issue-1257296086
