### ISSUE TITLE
Add: france24 eng direct

### ISSUE THREAD

**Issue by jamie-203** [iptv-org/iptv#7424]
### Channel Name

france24 eng direct

### Website

https://www.france24.com 

### Notes

all links I hve are dead

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
now on youtube only

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/france24/live

**Comment by spotanjo3** [comment]
I am surprised that English version doesn't have a closed captioning. I wonder.

**Comment by LaneSh4d0w** [comment]
> I am surprised that English version doesn't have a closed captioning. I wonder.

Some do, some don't.

**Comment by spotanjo3** [comment]
> > I am surprised that English version doesn't have a closed captioning. I wonder.
> 
> Some do, some don't. Most of them don't, sometimes when FOX streams off YouTube, they do have CC afaik

Here: Not necessarily for deaf people and hard of hearing but good for hearing people who are foreigners can learn to read English. 

(https://www.france24.com/en/closed-caption-news

**Comment by LaneSh4d0w** [comment]
> > > I am surprised that English version doesn't have a closed captioning. I wonder.
> > 
> > 
> > Some do, some don't. Most of them don't, sometimes when FOX streams off YouTube, they do have CC afaik
> 
> Here: Not necessarily for deaf people and hard of hearing but good for hearing people who are foreigners can learn to read English.
> 
> (https://www.france24.com/en/closed-caption-news

It's not a live channel, it's simply a cut version of the news, subbed.

**Comment by spotanjo3** [comment]
Yeah, I noticed. I hope a live channel have subbed or something. It would be awesome!

**Comment by jamie-203** [comment]
Many thanx
