### ISSUE TITLE
TreeHouse TV (CA) | Channel Request

### ISSUE THREAD

**Issue by alialiwa2005** [iptv-org/iptv#743]
Please add Treehouse TV, a Canadian-based channel, to your list, when possible.
Thank you.
![image](https://user-images.githubusercontent.com/27908087/69902813-c075fc00-135f-11ea-80ac-f3865886c9ad.png)

**Comment by speedingcheetah** [comment]
Any update on this? I can't seem to find a place to view this channel anywhere. I have read that there is some IPTV site that has it, but don't know where.

**Comment by alialiwa2005** [comment]
I've found a stream today.
http://linux-app.tv:6204/60400655844704/32991126026152/30708

It may be unstable/go offline after a few days/weeks (like most other channels), but it works as of today.

**Comment by speedingcheetah** [comment]
> I've found a stream today.
> http://linux-app.tv:6204/60400655844704/32991126026152/30708
> 
> It may be unstable/go offline after a few days/weeks (like most other channels), but it works as of today.

neat!  Hopefully it still works later in the month, cause that is when i was hoping to have acces to the channel. thanks for the link

**Comment by speedingcheetah** [comment]
> I've found a stream today.
> http://linux-app.tv:6204/60400655844704/32991126026152/30708
> 
> It may be unstable/go offline after a few days/weeks (like most other channels), but it works as of today.

OK? but when i load that in vlc, i get 2 secs of video...and thats it.. how do u use this link?

**Comment by speedingcheetah** [comment]
> I've found a stream today.
> http://linux-app.tv:6204/60400655844704/32991126026152/30708
> 
> It may be unstable/go offline after a few days/weeks (like most other channels), but it works as of today.

Is there an actual .m3u8 index file for this stream? That url as it is not usable, it just streams for 2 sec.

**Comment by freearhey** [comment]
Closed in favor #1941
