### ISSUE TITLE
Add: fox news fox business??

### ISSUE THREAD

**Issue by jamie-203** [iptv-org/iptv#7432]
### Channel Name

fox news fox  business

### Notes

all links I have r dead --even geo blocked is fine (vpn)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Please read the [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream) before posting your next request.
