### ISSUE TITLE
Al Quraan al Kareem & Al Sunnah al Nabbaweiah HD | Channel Requests

### ISSUE THREAD

**Issue by alialiwa2005** [iptv-org/iptv#744]
Hello, I'm requesting an HD stream of the channels, al quraan al kareem and al sunnah al nabbaweiah.

I know there are already SD streams, but I'd like to have HD versions added soon.
Thank you.

![image](https://user-images.githubusercontent.com/27908087/69902900-ba344f80-1360-11ea-9303-c1b93c5ec66d.png)

![image](https://user-images.githubusercontent.com/27908087/69902893-b1dc1480-1360-11ea-93d2-2fa4b0532fd5.png)

**Comment by alialiwa2005** [comment]
Saudi Arabia.

**Comment by Link4K** [comment]
sunnah exists https://github.com/iptv-org/iptv/blob/master/channels/sa.m3u#L11
