### ISSUE TITLE
Broken: Cartoon Network Asia

### ISSUE THREAD

**Issue by Laptopforgothisaccagain** [iptv-org/iptv#7451]
### Stream Title

Cartoon Network Asia (720p)

### What happened to the stream?

Not loading

### Possible Replacement

https://liveanevia.mncnow.id/live/eds/CartoonNetwork/sa_dash_vmx/CartoonNetwork.mpd

### Notes

EDIT: it works, and found that through yt. anyways heres the link, and also the licsense thing: https://mrpw.ptmnc01.verspective.net/?deviceId=NjcwYWI2ZGEtYzE4Yi0zZWFlLTljOWYtZGEzOGIwYWFjN2I1

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Laptopforgothisaccagain** [comment]
it kept being stuck on 0 buffering on my iptv app, and after awhile it changed to another channel

**Comment by fotvnetwork** [comment]
Tested it on chrome, works. But it didn't work on my device using Kodi

**Comment by F640** [comment]
> Tested it on chrome, works. But it didn't work on my device using Kodi

Try add `||R{SSM}|` at license URL's end

They don't accept DRM'ed streams right now i guess, but we'll see.

**Comment by freearhey** [comment]
Closed in favor #7661
