### ISSUE TITLE
Replace: TF1

### ISSUE THREAD

**Issue by RONTVHD** [iptv-org/iptv#7458]
### Stream Title

TF1 (1080p)

### What happened to the stream?

Not loading

### Possible Replacement

https://s2.tntendirect.com/tf1/live/playlist.m3u8

### Notes

"https://s2.tntendirect.com" m3u8 streams (ex. France 3) is also can be found on tntendirect.com.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/fr.m3u#L197-L198
