### ISSUE TITLE
Disney Channels USA/CA | Channel Request

### ISSUE THREAD

**Issue by alialiwa2005** [iptv-org/iptv#746]
Please add Disney and its sister channels, to your list.
Please add Canada and United States versions.
Thank you.

- Disney Channel
- Disney Junior (UK is already present, please add US and CA)
- Disney XD (Current streams are not working, please replace them with US and CA)
- ABC Spark (CA only. No US channel)

![image](https://user-images.githubusercontent.com/27908087/69902971-9d4c4c00-1361-11ea-92c4-600821d53350.png)

**Comment by freearhey** [comment]
Done.
https://github.com/iptv-org/iptv/blob/640a9686ff8033d8f38a08ccb4cecf1d7e67c117/channels/us.m3u#L334-L343

**Comment by alialiwa2005** [comment]
English versions do not work.

**Comment by freearhey** [comment]
@alialiwa2005 Thank you for noticing! Broken links have already been removed.

**Comment by freearhey** [comment]
**CA:**
- [ ] Disney Channel
- [ ] Disney Junior
- [ ] Disney XD

**US:**
- [x] Disney Channel
https://github.com/iptv-org/iptv/blob/6abfa134b0988d6e8f61de55094982d502342904/channels/us.m3u#L924-L925
- [x] Disney Junior
https://github.com/iptv-org/iptv/blob/6abfa134b0988d6e8f61de55094982d502342904/channels/us.m3u#L928-L929
- [x] Disney XD
https://github.com/iptv-org/iptv/blob/6abfa134b0988d6e8f61de55094982d502342904/channels/us.m3u#L926-L927
- [ ] ABC Spark

**Comment by Nintendocustom** [comment]
ABC Spark
http://stream-7b694ce7e.nmbs.top/m3u/Canada/3da7947a18.m3u8

**Comment by freearhey** [comment]
Closed in favor #1942 and #1941
