### ISSUE TITLE
Add: regular TV4 Sweden

### ISSUE THREAD

**Issue by Sonicfan9** [iptv-org/iptv#7465]
### Channel Name

TV4 Sweden

### Channel ID

TV4.se

### Notes

When I used the se.m3u link on one of the iptv apps on my phone, it says that there is the regular tv4 right between the other channels, but when I tapped onto the channel to watch it, it shows me is the news version of TV4, not the regular version.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
it's inside this : https://playback-api.b17g.net/media/13770218?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&is_live=true&browser=MozillaFirefox but I cannot access it due to geolocalisation issues.

**Comment by Sonicfan9** [comment]
I did use the link with the help with a vpn, but when I use the link with the vpn, it knows that I'm using the vpn, and it blocks me.

**Comment by Sonicfan9** [comment]
I did use another vpn, which is expressvpn, but the issue still precise.

**Comment by Sonicfan9** [comment]
Can you please help me which vpn works for regular tv4

**Comment by trancer1994** [comment]
I get {"errorCode":"ASSET_NOT_PUBLISHED","message":"Asset is not published on platform 'tv4'"} when I use the link

**Comment by LaneSh4d0w** [comment]
If you look there, it sounds like the channel isn't streamed, but bits of it are. https://www.tv4play.se/program/live

**Comment by Sonicfan9** [comment]
I did went onto that link with a swedish server on expressvpn, but every time when I want to watch it, it just gives me is a you're using a vpn or proxy server message.

**Comment by Sonicfan9** [comment]
But that's for the regular programming. I can watch however are the live news one and not the regular ones.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/cac2f96962f43fcec08d835b0878ed36307d4bbe/streams/se.m3u#L34-L35

**Comment by Hammargren85** [comment]
> https://github.com/iptv-org/iptv/blob/cac2f96962f43fcec08d835b0878ed36307d4bbe/streams/se.m3u#L34-L35

Its not working
