### ISSUE TITLE
Add: Canal Trece +

### ISSUE THREAD

**Issue by diegorodriguezv** [iptv-org/iptv#7467]
### Channel Name

Canal Trece +

### Channel ID

TrecePlus.co

### Website

https://canaltrece.com.co/senal-en-vivo/canaltrece/

### Stream URL

https://canaltreceplus-live.logicideas.media/canaltreceplus-live/smil:live1plus.smil/playlist.m3u8

### Notes

This channel already exists in the DB, but has no stream.
The name of the channel is `Canal Trece +`. Although it appears as `Trece+` in [lyngsat](https://www.lyngsat.com/tvchannels/co/Trece-.html), you can see that they call themselves Canal Trece in their [press room page](https://canaltrece.com.co/sala-de-prensa/). And it's how people in Colombia refer to it.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://github.com/iptv-org/iptv/blob/07aa4ce566081a551c41dbd46500101a1328d774/streams/co.m3u#L93-L96

**Comment by diegorodriguezv** [comment]
I just found out that the channel is in the co.m3u8 but it doesn't appear at https://iptv-org.github.io/.
Can someone please explain me why? 
I thought that the site was generated automatically from the m3u8 files. Sorry for my ignorance, I just found this excellent resource and want to contribute. I read the guidelines but I'm not aware of the workflow here.

**Comment by diegorodriguezv** [comment]
Yep. And the streams in the co.m3u8 file work great.
Shouldn't they appear in there as a "1 stream" link?

**Comment by diegorodriguezv** [comment]
#7466 is in the same web page.

**Comment by diegorodriguezv** [comment]
Somewhat related: The two streams that say "(not working perfectly)" seem to be working ok for the past week. Those have been the links of the official web site for at least 2 years. Sometimes some programs have contracts behind that prohibit being broadcasted to the Internet so the stream refuses connection for the duration of the program. Typically half an hour.

**Comment by LaneSh4d0w** [comment]
> Somewhat related: The two streams that say "(not working perfectly)" seem to be working ok for the past week. Those have been the links of the official web site for at least 2 years. Sometimes some programs have contracts behind that prohibit being broadcasted to the Internet so the stream refuses connection for the duration of the program. Typically half an hour.

They were acting weird (loss of image and sound from their side) the time I had added them, and now I found they were dupes.
