### ISSUE TITLE
Replace: ERT 1 (Greece)

### ISSUE THREAD

**Issue by pitsi** [iptv-org/iptv#7470]
### Stream Title

ERT 1 (1080p) [Geo-blocked]

### Broken Link

https://ert1-live.ert.insyscd.net/out/v1/bc7e22e489c7452280769c91743cc2f3/ert1-live.m3u8 

### What happened to the stream?

Shows the wrong channel

### Possible Replacement

https://ert-live-bcbs15228.siliconweb.com/media/ert_1/ert_1.m3u8

### Notes

This is the second time in 10 days that I request a change due to a broken stream. Please do not blame me, I am not the one who does the changes in the channel's web tv. So here goes.

This is the old stream, the one that I requested to change 10 days ago. Today, the old stream works like before. The new one still works, but its program (as mentioned by the epg) is wrong. So it is not actually "shows the wrong channel" as I report above, but more like "shows wrong content".

Like last time, I do not know what happens with ert sports, as both new and old stream play the same "static" image with no program at all. I will report back when it will be actually broken.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Better keep both links as alternative and main streams.

**Comment by pitsi** [comment]
Although I agree with that, what is the point of keeping a stream that does not follow the epg schedule?
At least make the forementioned stream the default one for ert 1 (and the one on the other issue report the default for ert 2), so that the epg matches the correct stream.

**Comment by LaneSh4d0w** [comment]
> Although I agree with that, what is the point of keeping a stream that does not follow the epg schedule? At least make the forementioned stream the default one for ert 1 (and the one on the other issue report the default for ert 2), so that the epg matches the correct stream.

Well, which stream does follow the schedule, and which one does not ? The stream that doesn't won't have the tvg-id set in, so that it doesn't get any feed.

**Comment by pitsi** [comment]
Today, this one plays a 17 sec video which is probably from a Sunday morning show.
`https://ert1-live.ert.insyscd.net/out/v1/bc7e22e489c7452280769c91743cc2f3/ert1-live.m3u8`

Likewise, this one for ert 2 plays a 17 sec video from an old foreigh movie
`https://ert2-live.ert.insyscd.net/out/v1/617370f6ad1447ca8efdc795e4e960a3/ert2-live.m3u8`

Moreover, the this one (aka the new one that was changed 10 days ago) for ert sports plays the known "static" image, for 17 seconds as well. 
`https://ertsports-live.ert.insyscd.net/out/v1/db0b54e8d25a47dcb336cf114c4d1860/ertsports-live.m3u8`

Picture of the "static" image played by ert sports when no program is transmitted, so that everyone knows what I mean. The background actually moves and the logo gets bigger or smaller, depending on the animation.

![mpv-shot0001](https://user-images.githubusercontent.com/5880037/172797718-bcdb7eb9-0c6b-48b7-9cbe-e27a5397cc20.jpg)

I hope nothing will change by tomorrow... If so, I will file an issue report for ert sports as well.

**Comment by pitsi** [comment]
When will this (and the one for ert 2) be fixed? It has been 2 weeks now that the streams are broken.

**Comment by LaneSh4d0w** [comment]
I think we'll keep all links together.

**Comment by pitsi** [comment]
Why keep a link that plays a 17 sec video that has nothing to do with anything that is broadcasted?
Not to mention that, on my end (mpv player), it stops playing after that time and the player does not even exit!

**Comment by pitsi** [comment]
Well, you can say they are doing that, but not constantly. Let's just say that this month's incident was an exception.
To be honest, and as you may have read from the issue about ert sports, I am fed up with all those changes and I will soon quit that everyday "inspection" of urls and sites. I will be keeping an eye though if anything breaks so as to report it.

**Comment by pitsi** [comment]
I think it is time to completely remove those urls for ert 1, 2 and sports that come from the insyscd.net domain.
Forget those useless 17 second clips they used to play, today they return a 404 error in mpv, so they are are officially dead
```
$ mpv https://ert1-live.ert.insyscd.net/out/v1/bc7e22e489c7452280769c91743cc2f3/ert1-live.m3u8
[ffmpeg] https: HTTP error 404 Not Found
[ffmpeg/demuxer] hls: parse_playlist error Server returned 404 Not Found [https://ert1-live.ert.insyscd.net/out/v1/bc7e22e489c7452280769c91743cc2f3/ert1-live_1.m3u8]
[ffmpeg] https: HTTP error 404 Not Found
[ffmpeg/demuxer] hls: parse_playlist error Server returned 404 Not Found [https://ert1-live.ert.insyscd.net/out/v1/bc7e22e489c7452280769c91743cc2f3/ert1-live_2.m3u8]
[ffmpeg] https: HTTP error 404 Not Found
[ffmpeg/demuxer] hls: parse_playlist error Server returned 404 Not Found [https://ert1-live.ert.insyscd.net/out/v1/bc7e22e489c7452280769c91743cc2f3/ert1-live_3.m3u8]
[ffmpeg] https: HTTP error 404 Not Found
[ffmpeg/demuxer] hls: parse_playlist error Server returned 404 Not Found [https://ert1-live.ert.insyscd.net/out/v1/bc7e22e489c7452280769c91743cc2f3/ert1-live_4.m3u8]
[ffmpeg/demuxer] hls: Empty segment [https://ert1-live.ert.insyscd.net/out/v1/bc7e22e489c7452280769c91743cc2f3/ert1-live_1.m3u8]
[ffmpeg/demuxer] hls: Empty segment [https://ert1-live.ert.insyscd.net/out/v1/bc7e22e489c7452280769c91743cc2f3/ert1-live_2.m3u8]
[ffmpeg/demuxer] hls: Empty segment [https://ert1-live.ert.insyscd.net/out/v1/bc7e22e489c7452280769c91743cc2f3/ert1-live_3.m3u8]
[ffmpeg/demuxer] hls: Empty segment [https://ert1-live.ert.insyscd.net/out/v1/bc7e22e489c7452280769c91743cc2f3/ert1-live_4.m3u8]
No video or audio streams selected.

Exiting... (Errors when loading file)
```

**Comment by LaneSh4d0w** [comment]
according to https://www.ertflix.gr/epg/now-on-tv there's no EPT channel.

**Comment by pitsi** [comment]
Are you kidding me? I hope you do know the greek alphabet and that the letter "ρ" is the equivalent of "r".
If so, why did you wait for like ~3 weeks to say that irrelevant thing?

Moreover, the forementioned epg is not parsed at all by iptv-org, so why do you even mention it? If it was, it would contain the epg for ert sports, which is completely missing from any epg provided by iptv-org..

**Comment by LaneSh4d0w** [comment]
> Are you kidding me? I hope you do know the greek alphabet and that the letter "ρ" is the equivalent of "r". If so, why did you wait for like ~3 weeks to say that irrelevant thing?
> 
> Moreover, the forementioned epg is not parsed at all by iptv-org, so why do you even mention it? If it was, it would contain the epg for ert sports, which is completely missing from any epg provided by iptv-org..

1) I'm not Greek, so the Greek alphabet is something I do not master
2) There's simply **no reference** to any ERT channel said above on ERTFlix. (unless it's geo-locked and even I cannot force the page to show in).
3) The EPG will depend of the source it somes from. For ERT I do not think it uses ERTFlix to get the data, it gets it from somewhere else.

**Comment by pitsi** [comment]
(deep breath)

1-2. Now you know that "ERT" is actually "ΕΡΤ" in greek, so there is no typo or anything similar on everything I have said above. Ii is not my fault that all its channels except ert world use the greek version of the text for their logo. Yes, the site is geoblocked, but even if you switch the site to its english version, the epg below is still in greek

3. I know that. Yet, that epg, which is parsed from [here](https://www.cosmote.gr/cosmotetv/residential/program), does not include ert sports (and a set of other, cable channels like novasports, which are included in Cyprus' epg only), probably because it is a web-only channel.

4. I agree on that. I go to ertflix.gr on my browser, then I click on live button on the top left corner, then I select the channel and finally I hunt its stream under developer tools.

**Comment by pitsi** [comment]
Is there a site that I can test... another site for geoblocking? I tested all 10 of ert's streams (1, 2, 3, two for sports, two for sports 2, world, news and news 2)  on streamtest.in.
The ones for 1, 2, 3, sports non-ww and sports 2 non-ww are geoblocked according to the site, because they return offline when tested against a Singapore or United States ip.
On the other hand, the ones for news, news 2, world, sports ww and sports 2 ww do not seem geoblocked, because they work when tested against a Singapore or United States ip. 

As for ert sports, it no longer exists on cosmote's epg because it no longer is a channel that is broadcasted on the regular tv. It became a web-only channel on late November 2020 and it was a part of cosmote's epg until then.

**Comment by LaneSh4d0w** [comment]
Not for Greece AFAIK, apart of using a VPN.

**Comment by pitsi** [comment]
What does that mean? I am on Greece and my greek isp gives me a greek ip. I do not use a vpn (or even tor).
Thus, the results from all the sites and streams I can test without a vpn will be from my "greek point of view".

**Comment by LaneSh4d0w** [comment]
> What does that mean? I am on Greece and my greek isp gives me a greek ip. I do not use a vpn (or even tor). Thus, the results from all the sites and streams I can test without a vpn will be from my "greek point of view".

My bad, thought you were asking for a specific thing from outside Greece.

As for testing stream services, I'm afraid Greece is not the option they often think about when hosting a server of this sort.

**Comment by pitsi** [comment]
I do not mind that. All I can see and help with are greek channels anyway.

**Comment by LaneSh4d0w** [comment]
> I do not mind that. All I can see and help with are greek channels anyway.

Though the next changes will be to keep both links for both hosts, in case they do come back.

**Comment by pitsi** [comment]
With "both links" do you also mean the ones that played normally for like one week, then they played some old show or something and now they do not play at all?

**Comment by LaneSh4d0w** [comment]
> With "both links" do you also mean the ones that played normally for like one week, then they played some old show or something and now they do not play at all?
> 
> Btw, I can check ANY greek channel if needed, not only the ert ones. For instance, there is a url for alpha that has been dead for months now.

Yes, because it seems they switch all the time. It'll be more of a "rescue" link.

**Comment by pitsi** [comment]
Ok. At least make the new streams the default ones, you know the ones with working epg entries. And name the old ones as BUP.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/gr.m3u#L62-L63

**Comment by pitsi** [comment]
Whar does that in the code tags mean? It is the old, non working url that I asked to be replaced 2+ MONTHS ago and it is still there!
Since my last comment on the ert sports issue 1 month ago, I have completely given up on your list (and epg).

**Comment by freearhey** [comment]
This code is just to make it easier to find the broken link in the playlist. You can ignore these messages.

As soon as a replacement is available, we will notify about it separately.

**Comment by freearhey** [comment]
https://ert-live-bcbs15228.siliconweb.com/media/ert_1/ert_1.m3u8 (offline)
<img width="465" alt="image" src="https://user-images.githubusercontent.com/7253922/232227778-df3b1b47-c79c-4f15-8faf-b74a199c986b.png">
