### ISSUE TITLE
Replace: ERT 2 (Greece)

### ISSUE THREAD

**Issue by pitsi** [iptv-org/iptv#7471]
### Stream Title

ERT 2 (1080p) [Geo-blocked]

### Broken Link

https://ert2-live.ert.insyscd.net/out/v1/617370f6ad1447ca8efdc795e4e960a3/ert2-live.m3u8 

### What happened to the stream?

Shows the wrong channel

### Possible Replacement

https://ert-live-bcbs15228.siliconweb.com/media/ert_2/ert_2.m3u8

### Notes

This is the second time in 10 days that I request a change due to a broken stream. Please do not blame me, I am not the one who does the changes in the channel's web tv. So here goes.

This is the old stream, the one that I requested to change 10 days ago. Today, the old stream works like before. The new one still works, but its program (as mentioned by the epg) is wrong. So it is not actually "shows the wrong channel" as I report above, but more like "shows wrong content".

Like last time, I do not know what happens with ert sports, as both new and old stream play the same "static" image with no program at all. I will report back when it will be actually broken.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by pitsi** [comment]
So I was zapping through my channels last night and I found this.
The new (= the one I suggest above) stream is currently broken. It shows a ~20 minute video from the qualifiers of the British grand prix of formula 1, which was aired last weekend (1st - 3rd of July)!
The site's stream does play everything according to its epg, but all I can find is a manifest.mpd file. 

I won't waste more time trying to find a fix and I am really glad I stopped with all that.

**Comment by pitsi** [comment]
I just checked my urls and ert 2 is back (and probably has been since the start of the week).
And this time, ert world broke and it plays a 20 minute video from some news show.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/gr.m3u#L64-L65

**Comment by freearhey** [comment]
https://ert-live-bcbs15228.siliconweb.com/media/ert_2/ert_2.m3u8 (offline)
<img width="474" alt="image" src="https://user-images.githubusercontent.com/7253922/232227799-6d1d4b80-335f-464a-8a69-c81a5fb76aa0.png">
