### ISSUE TITLE
New York City Local Channels | Channel Request

### ISSUE THREAD

**Issue by alialiwa2005** [iptv-org/iptv#748]
- CBS 2 NY (Current CBS streams are not from NY)
- NBC 4 (Current NBC 4 is falsely labeled; actually streams NBC 6 instead.)
- ABC 7 NY
- WNET

**Comment by Sphinxroot** [comment]
CBS 2 NY 

https://dai.google.com/linear/hls/pa/event/rtcMlf4RTvOEkaudeany5w/stream/0171ad8a-e87c-4cfe-b385-c7f7d593207d:MRN/master.m3u8

https://dai.google.com/linear/hls/pa/event/rtcMlf4RTvOEkaudeany5w/stream/0171ad8a-e87c-4cfe-b385-c7f7d593207d:MRN/variant/91c45d85d4686323b5ad04e54cc36368/bandwidth/2209451.m3u8

https://dai.google.com/linear/hls/pa/event/rtcMlf4RTvOEkaudeany5w/stream/0171ad8a-e87c-4cfe-b385-c7f7d593207d:MRN/variant/b267e76115e47d65a09b5fcd779447cb/bandwidth/2768101.m3u8



NBC 4 

https://dcs-live.apis.anvato.net/server/play/O0b5YNpiqkMpTbo7/rendition.m3u8?track=video-0&anvsid=i177603976-nde331d71-5e9c-4510-a1f0-c1eee8d02606&ts=1589059829&anvtrid=wc0944ca1d3d74cbd0ca62b175e6c37c


ABC 7 NY abc7ny(.)com/watch/ link expire after a time and tokenize

WNET  geo

**Comment by alialiwa2005** [comment]
None of them work as of 5/15/2020. (On my end)

**Comment by freearhey** [comment]
Closed in favor #1942
