### ISSUE TITLE
Add: OCN Movies

### ISSUE THREAD

**Issue by jbcooter** [iptv-org/iptv#7484]
### Channel Name

OCN Movies

### Channel ID

OCNMovies.KR

### Website

http://51.81.66.195:1935/krtv/cgv_540/playlist.m3u8

### Stream URL

http://51.81.66.195:1935/krtv/cgv_540/playlist.m3u8

### Notes

There are a few other channels on this stream that aren't on South Korea like KBS Kids and KBS Joy and KBS2. Not sure how to find out the other streams on http://51.81.66.195:1935 but seems like could be a wealth of channels.

http://51.81.66.195:1935/krtv/kbs_joy_540/playlist.m3u8
http://51.81.66.195:1935/krtv/kbs_kids_540/playlist.m3u8
http://51.81.66.195:1935/krtv/kbs2_540/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
OCN Movies is inside kr.m3u.

**Comment by jbcooter** [comment]
I see them after I mentioned them.  There was OCN Thriller before as well, that was nice. I still don't see KBS Joy. Appreciate all the work that you do.
