### ISSUE TITLE
Add: KBS World

### ISSUE THREAD

**Issue by jbcooter** [iptv-org/iptv#7487]
### Channel Name

KBS World

### Channel ID

KBSWorld.kr

### Website

https://wms4-kortv.akamaized.net/a_live/63719963/smil:20ch011.smil/chunklist_b2500000.m3u8

### Stream URL

https://wms4-kortv.akamaized.net/a_live/63719963/smil:20ch011.smil/chunklist_b2500000.m3u8

### Notes

This stream doesn't have the Vietnamese subtitles and zaps a lot quicker. 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://wms4-kortv.akamaized.net/a_live/63719963/smil:20ch011.smil/playlist.m3u8

**Comment by jbcooter** [comment]
I guess the one with Vietnamese subtitles could just be used in the Vietnamese country section. I'm sure someone likes the Viet subs as well.
