### ISSUE TITLE
Replace: ERT Sports (Greece)

### ISSUE THREAD

**Issue by pitsi** [iptv-org/iptv#7489]
### Stream Title

ERT Sports (1080p) [Geo-blocked]

### Broken Link

https://ertsports-live.ert.insyscd.net/out/v1/db0b54e8d25a47dcb336cf114c4d1860/ertsports-live.m3u8 

### What happened to the stream?

Shows looped video

### Possible Replacement

https://ert-live-bcbs15228.siliconweb.com/media/ert_sports_ww/ert_sports_ww.m3u8

https://ert-live-bcbs15228.siliconweb.com/media/ert_sports/ert_sports.m3u8

### Notes

Because I am fed up writing the same stuff for the "new" url, like I did for ert 1 and 2, does it count if i say "it is the stream that plays on the official web page of the station"?

The old url plays a 17 second clip, stops at its last frame and stays there forever. Checked on kodi (libreelec, linux), vlc (android), mpv (linux) and 2 lg smart tvs with web os running ss iptv.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by pitsi** [comment]
And it changed again, to this, which seems to be "the stream that plays on the official web page of the station" today
`https://ert-live-bcbs15228.siliconweb.com/media/ert_sports/ert_sports.m3u8`

The one mentioned at the start still shows the "static" image I have mentioned in previous report, i.e. this
![mpv-shot0002](https://user-images.githubusercontent.com/5880037/173181736-e11d2aee-0923-4235-9eec-3b3ebbfe0fd3.jpg)

while the one above plays something different that mentions a formula one event in ~2 hours
![mpv-shot0001](https://user-images.githubusercontent.com/5880037/173181750-13295d68-addb-4da7-a2ea-e04ae0252ddf.jpg)

So, now that something is scheduled, in 2 hours I will know which one plays and which one is faulty.

**Comment by pitsi** [comment]
As I expected, the f1 event is now transmitted only in the latest stream, so I changed the url at the start.

**Comment by pitsi** [comment]
And it freaking changed again! Today, this one shows the static image
`https://ert-live-bcbs15228.siliconweb.com/media/ert_sports/ert_sports.m3u8`
while this one shows the scheduled program 
`https://ert-live-bcbs15228.siliconweb.com/media/ert_sports_ww/ert_sports_ww.m3u8`

**Comment by pitsi** [comment]
And it changed again! Although both streams show the static image I mentioned above, the url that is played from the page is this one
`https://ert-live-bcbs15228.siliconweb.com/media/ert_sports/ert_sports.m3u8`

I am fed up with all this. Can you keep both, as both are as official as it gets, and name one of them as BUP?
Like Skai, whose both urls are official and working and they are named like that so as to be distinguished.

**Comment by LaneSh4d0w** [comment]
I think we'll have to keep both links to make sure this issue doesn't happen again.

**Comment by pitsi** [comment]
Right now, 9.20 pm eest, ert sports shows shows the static image on 
`https://ert-live-bcbs15228.siliconweb.com/media/ert_sports_ww/ert_sports_ww.m3u8`
and some f1 qualifiers on 
`https://ert-live-bcbs15228.siliconweb.com/media/ert_sports/ert_sports.m3u8`

Let's see what happens tomorrow.

**Comment by pitsi** [comment]
So, its 8.20pm here and, according to the epg, more f1 qualifiers were supposed to start at ert sport at 8pm. None of the streams shows anything though. The first stream with the static image image still shows the static image and the second one what would show the f1, still shows an "ad" about "F1 on Saturday, June 18th, on 8pm".

The web page though shows the f1 qualifiers as it should. Upon close inspection from developer tools > network tab, I see a manifest.mpd file that is the actual stream, i.e. it plays fine on mpv. So why isn't it broadcasted on any of the above m3us and why isn't any of the above m3us now anywhere in the network tab? 
The same thing happened a few hours ago, at 5pm, when it was showing some swimming competition, buit I did not report it because I thought it may have been a glitch. All I can think is that the actual stream is transmitted differently due to copyright issues.

If this is true, please do not blame me for streams that do not follow the epg from now on. Thank you :)

**Comment by pitsi** [comment]
As it seems, sport events are only broadcasted from the webpage itself and use that manifest.mpd file for the duration they are broadcasted.
Same thing happened with the f1 race last night that was broadcasted from ert 2. Same thing happened with the swimming competition yesterday afternoon that was broadcasted from ert sports. It even happened on Friday night with a basketball game on ert 3.

The difference is that, unlike ert sports which was showing the "static" image while any of the sports event was broadcasted, ert 2 and 3 were showing some recorded program while the forementioned sports events were broadcasted. And all this happened these last 3 days. I know that because I have a friend who watches f1 and he said it was not available in any of the forementioned urls.

I assume that this will be the new status from now on for live sport events, so please do not blame me if any of the above urls does not broadcast what it is supposed to. I am now waiting for any of the ert channels to show a recorded sports program to check what happens then,

**Comment by pitsi** [comment]
I noticed yesterday afternoon that the swimming event which was live was shown as usual by ert sports. And ert 2 was also showing a different part of the swimming event at the same time. And this morning (its 12.10 pm local time), ert sports showed today's broadcast from the swimming and I hope it will show the one that is scheduled for afternoon (5pm local time).
All broadcasts were shown under the relevant urls with no issues, so I thought they abandoned the forementioned way of showing a recorded program while any sports event is live.
On the page however they still have those manifest.mpd files that play the live events, so nothing has changed on this part.

All the above refer to the new url of ert sports, i.e. this one
`https://ert-live-bcbs15228.siliconweb.com/media/ert_sports/ert_sports.m3u8`
The old one, the one that ends in "_ww.m3u8", i.e. this one
`https://ert-live-bcbs15228.siliconweb.com/media/ert_sports_ww/ert_sports_ww.m3u8`
today shows a 20 minute clip of the static image and nothing more.

Last but not least, some program (beach soccer) is shown right now on ert sports 2 on the web page, but it uses manifest.mpd so I am waiting for it to end and see if I can get the url for ert sports 2 because the current one, i.e. this one
`https://ert-live-bcbs15228.siliconweb.com/media/ert_sports_ww/ert_sports2_ww.m3u8`
shows the well known static image. Good thing it does not show a fixed length video like the one above.

**Comment by pitsi** [comment]
This is my last post on this issue, because I am done with ert sports and ert's channels in general. So, regardless whether they shows sports events or not (or if they use manifest.mpd or not for them) I am not going to investigate them any further. But I want to mention a couple of stuff.

The new url for ert sports, the one without ww at its end, did work yesterday afternoon and showed the swimming event. The one with ww at its end was showing the static image as usual. I am not removing any of the 2 urls above, although I consider the ww one broken. I leave it to the maintainers to decide.

On the other hand, ert sports 2 was broadcasting the beach soccer event from the page, but the list's url (which does end in ww too) was showing the static image only. Unfortunately, this means that the url for ert sports 2 is also broken, but I have no idea what the fixed one is.

Thank you for all your work :)

**Comment by pitsi** [comment]
Streams to laugh at.

Ert sports non-ww version now plays the static image, but without the bottom strip that lists ertflix's availability on several platforms. It also says "Sports 1" instead of just "Sports" on the red part of its logo on the static image.

Ert sports ww version shows the forementioned static image, so no boring changes here.

Ert sports 2 non-ww version now plays the static image, with the bottom strip that I mentioned above, plus it says "Sports 2" on the red part of the logo.

Ert sports 2 ww version is from another universe where time must have stopped and advertises a forthcoming event for Thursday 30th of JUNE!

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/gr.m3u#L212-L213

**Comment by LaneSh4d0w** [comment]
Those links are going red light green light... i highly doubt we can make something for those.

**Comment by pitsi** [comment]
Why don't you just remove all those links from the insyncd.net that do not work? They alllead to 404 for 1+ month now and the ones I suggested (and changed) have both geo-blocked and worldwide available versions (the ones that have ww in their url), althought the one for worldwide rarely broadcast anything.

Imho, since the channel has that big "geo-blocked" text on its name, I think there is no point in keeping the ww version as well. Well, you can make 2 versions of the same channel, one for the url that has ww on it, plays rarely but is available worldwide and one for the one without ww on it that plays regularly and it is geo restricted. But this means maintaining 2 different things.

Having said that, today I will unsubscribe from any issues I have opened here and let you do as you please. On my list, I have cherry picked the ones that work for my country and that's it. Close them any time you wish, regardless if you fix them or let them be problematic.

**Comment by freearhey** [comment]
If the link does show a looped video, it would be better to remove it from the playlist first, and then close the issue.

**Comment by AntiPontifex** [comment]
Dead issue: please close.

**Comment by pitsi** [comment]
Well, the url is still wrong. It is not my fault that the maintainers have not changed it after so many months.
That is why I gave up contributing on any issue here, it's a complete waste of my time.

p.s. ALL ERT urls have changed since then.

**Comment by AntiPontifex** [comment]
@pitsi Sorry to hear that; I've been trying to answer old requests, but I'm only one AntiPontifex. All I can type is please don;t feel discouraged: I was once in your shoes. Your input and suggestions ARE welcomed.

**Comment by pitsi** [comment]
Instead of me complaining for stuff like: "there are/were at least 150 maintainers of the project all those months, yet no one cared about this" and "the previous issues, which were about all 3 ert channels, had their urls corrected and were closed in a couple of days", do you agree if I post the new urls for ALL the ert channels (1, 2, 3, news, sports1, world), as used by the page of course, and close this?

**Comment by freearhey** [comment]
https://ert-live-bcbs15228.siliconweb.com/media/ert_sports_ww/ert_sports_ww.m3u8 (looped video)
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/7253922/232260794-a2f4c1ef-1031-4005-9e40-e656657c822d.png">

https://ert-live-bcbs15228.siliconweb.com/media/ert_sports/ert_sports.m3u8 (offline)
<img width="543" alt="image" src="https://user-images.githubusercontent.com/7253922/232260781-7d009aaa-0fb6-439e-9a89-d1a5c67f4b8e.png">
