### ISSUE TITLE
Incorrect/Broken Local News Channels | Error-Found

### ISSUE THREAD

**Issue by alialiwa2005** [iptv-org/iptv#749]
Hello,
There are multiple incorrectly labeled channels; mainly local news.
Some of the channels I've spotted as falsely named were:

- NBC 4 NY. It streams NBC 6 FL instead.
- CBS 2. It streams CBS Washington instead.
------------------------------------------------------------------------------
Some broken news channels were:
- Fios1 (All of the Fios1  Channels)

**Comment by themak1985** [comment]
Ahlan ya @alialiwa2005 - Lots of issues opened - just wanted to share the contribution guide. 
https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md
You can submit pull requests for the name changes and remove broken links.
