### ISSUE TITLE
Add:  YTN Science

### ISSUE THREAD

**Issue by jbcooter** [iptv-org/iptv#7491]
### Channel Name

YTN Science

### Channel ID

YTNScience.KR

### Website

http://slive.sciencetv.kr:1935/science/yslive_20140419_1/playlist.m3u8

### Stream URL

http://slive.sciencetv.kr:1935/science/yslive_20140419_1/playlist.m3u8

### Notes

This works

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://github.com/iptv-org/iptv/blob/9d4196abd8a5af6c76e58e95896090f5d1b1f2c4/streams/kr.m3u#L178-L179
