### ISSUE TITLE
Add: Playy Action Movies

### ISSUE THREAD

**Issue by jbcooter** [iptv-org/iptv#7492]
### Channel Name

Playy

### Channel ID

Playy

### Website

http://132.145.83.248:9981/stream/channelid/1143095935

### Stream URL

http://132.145.83.248:9981/stream/channelid/1143095935

### Notes

Playy Action
http://132.145.83.248:9981/stream/channelid/1143095935
Playy Premium
http://132.145.83.248:9981/stream/channelid/704310334
Playy Well Made
http://132.145.83.248:9981/stream/channelid/2066244260

Definitely not 24/7 and seems to be some amount of downtime but these channels are solid otherwise for Korea

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://132.145.83.248:9981/extjs.html for tvheadend data. self-hosted so expect LOTS of issues streaming those channels.
