### ISSUE TITLE
Broken: Open TV BUP, Alpha BUP, M.TV, Star BUP (Greece)

### ISSUE THREAD

**Issue by pitsi** [iptv-org/iptv#7499]
### Stream Title

Open TV BUP, Alpha BUP, M.TV, Star BUP

### What happened to the stream?

Not loading

### Possible Replacement

(none)

### Notes

All those 4 streams that broadcast from `http://78.83.87.222:9999` are now long dead and lead to 404.
It was obviously a selfhosted rebroadcast that just stopped one day, so they can be removed now.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Please read the [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream) before posting your next request.

**Comment by pitsi** [comment]
You are right, I missed the "one channel per report part". If I edit this one to only have one channel and open 3 more for the rest is it ok?
