### ISSUE TITLE
Add: jeel dz

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#7506]
### Channel Name

jeel dz

### Channel ID

JeelDZTV.dz

### Website

https://jeel.dz/

### Notes

need an m3u8 url 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by hemzaberkane** [comment]
https://vimeo.com/user167465839

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://vimeo.com/719857704

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://vimeo.com/750785314
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/7253922/190888261-69ec3ff5-d902-474d-a038-1460fc44ef54.png">

**Comment by Alstruit** [comment]
See #8938.
