### ISSUE TITLE
Broken: Fox News Channel

### ISSUE THREAD

**Issue by Kristal9** [iptv-org/iptv#7510]
### Stream Title

Fox News Channel (720p)

### What happened to the stream?

Not loading

### Notes

This channel doesn't work. Fix it, please.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
makes allusion / dupe of #7118
