### ISSUE TITLE
Add: TVI Ficcao 

### ISSUE THREAD

**Issue by ghost** [iptv-org/iptv#7514]
### Channel Name

TVI Ficcao 

### Channel ID

TVIFiccao.pt

### Website

https://tvi.iol.pt/tvificcao/

### Notes

Add to portugal catogory 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
I need to make the iol plugin for this one. Once this is made, we may add all of the iol.pt channels.

**Comment by VirtualMedia-IPTV** [comment]
> I need to make the iol plugin for this one. Once this is made, we may add all of the iol.pt channels.
Dear Lane,

Have you guys been able to create the IOL plugin yet?

**Comment by freearhey** [comment]
Closed in favor of #11615
