### ISSUE TITLE
Add: Portugal

### ISSUE THREAD

**Issue by AdminVirtual-Media** [iptv-org/iptv#7515]
### Channel Name

All Portugues Channels available on IPTV-ORG.GITHUB.IO

### Channel ID

All Portugues Channels available on IPTV-ORG.GITHUB.IO

### Website

All Portugues Channels available on IPTV-ORG.GITHUB.IO

### Stream URL

All Portugues Channels available on IPTV-ORG.GITHUB.IO

### Notes

All Portugues Channels available on IPTV-ORG.GITHUB.IO

Please add and update this ASAP as the Portugues channels don't work 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Irrelevant request.
