### ISSUE TITLE
Broken Disney Junior Streams | Error-Found/Channel Request

### ISSUE THREAD

**Issue by alialiwa2005** [iptv-org/iptv#752]
Hello, Disney Junior has gone offline recently and does not play.
Please remove and add new stable streams, as the current omes are no longer active.
Thank you.
Channels Not Playing: 
- Disney Jr. US
- Disney Junior CA

Please readd them... I have been using them personally so I would really love if they were up soon.
![disney-jr-post](https://user-images.githubusercontent.com/27908087/69906466-b5d45a80-1391-11ea-9fcf-9c3a2db5d037.jpg)

**Comment by freearhey** [comment]
Duplicate #746
