### ISSUE TITLE
Add:TV3.my 

### ISSUE THREAD

**Issue by Rushdiey** [iptv-org/iptv#7521]
### Channel Name

TV3

### Channel ID

TV3.my

### Stream URL

http://zalogitv.tech:8080/live/4587530/7530/1831.ts

### Notes

Please add this to Malaysia Channel

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
XTream-Codes server, won't be added.

**Comment by fotvnetwork** [comment]
https://tvmalaysiaonline.xyz:5443/LiveApp/streams/049308573816025645291571.m3u8

**Comment by AzeemHadzrie** [comment]
Here: https://api.samsam123.name.my/mediaprima_dailymotion/beta.php?channels=tv3

Needs a referrer: www.dailymotion.com

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/my.m3u#L18-L19
