### ISSUE TITLE
Fix: PT Streams M3U

### ISSUE THREAD

**Issue by AdminVirtual-Media** [iptv-org/iptv#7526]
### Describe your issue

Most of the Portuguese channels are not loading, I have already provided with m3u links of working channels but they were not added, can this please be reviewed and adjusted asap.

**Comment by LaneSh4d0w** [comment]
Not a bug, but a set of broken streams. Please say which streams are not available **one by one**. Telling that channels won't work won't help us.

**Comment by freearhey** [comment]
@AdminVirtual-Media Please read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#add-or-replace-a-stream) before posting your next request.
