### ISSUE TITLE
Add: Sonnenklar TV

### ISSUE THREAD

**Issue by pukozs75** [iptv-org/iptv#7530]
### Channel Name

Sonnenklar TV

### Channel ID

SonnenklarTV.de

### Website

https://mediathek.sonnenklar.tv/aktuell-auf-sonnenklartv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by pukozs75** [comment]
> https://edge0752-55mx1.flex-cdn.net/8e789d67d1e3a0ea42464d5e1bd043b59b76819225bd0a38d040/manifest.mpd

Can you please add this channel in the playlist?

**Comment by Sphinxroot** [comment]
wont be possible  because the link change 

https://edge0752-55mx1.flex-cdn.net/8e789d6793d6acb03618feed20d3f39d548510c52ef05094ec88/manifest.mpd

**Comment by LaneSh4d0w** [comment]
https://euvia.cdn.ses-ps.com/secure/DASH-Live/manifest.mpd

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be added in the next update.

**Comment by freearhey** [comment]
https://euvia.cdn.ses-ps.com/secure/DASH-Live/manifest.mpd
<img width="788" alt="image" src="https://user-images.githubusercontent.com/7253922/232228477-bd35e4c3-8258-40dd-9c68-78c2e242747b.png">
