### ISSUE TITLE
Broken: JOJ Family

### ISSUE THREAD

**Issue by Smark223** [iptv-org/iptv#7542]
### Stream Title

JOJ Family (540p)

### What happened to the stream?

Stuck at a single frame

### Notes

JOJ and JOJ Plus (with similar urls) are both still working but JOJ Family and JOJ Sport (which is actually in the list as Rik) are both stuck on a single frame

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/sk.m3u#L58-L61
