### ISSUE TITLE
Add: EMT Media TV - Los Angeles, CA

### ISSUE THREAD

**Issue by LPhilip1999** [iptv-org/iptv#7546]
### Channel Name

EMT Media TV

### Website

https://emtmediatv.com/watch-live-tv/

### Notes

Please adding the m3u8 link

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by trancer1994** [comment]
https://mediaplatform.streamingmediahosting.com/p/14135/sp/1413500/playManifest/entryId/0_lkq7fay8/format/applehttp/protocol/https/uiConfId/6710347/a.m3u8?referrer=aHR0cHM6Ly9lbXRtZWRpYXR2LmNvbQ==&playSessionId=85851bc0-fd37-a365-4004-da87b1d0035e

**Comment by LaneSh4d0w** [comment]
> https://mediaplatform.streamingmediahosting.com/p/14135/sp/1413500/playManifest/entryId/0_lkq7fay8/format/applehttp/protocol/https/uiConfId/6710347/a.m3u8?referrer=aHR0cHM6Ly9lbXRtZWRpYXR2LmNvbQ==&playSessionId=85851bc0-fd37-a365-4004-da87b1d0035e

Referer unnecessary but otherwise link works. Sounds a bit like Kaltura links.
