### ISSUE TITLE
Add: GEM (with English subs)

### ISSUE THREAD

**Issue by MeanXBeam** [iptv-org/iptv#7555]
### Channel Name

Sony GEM

### Channel ID

GEM.sg

### Website

https://www.gemtvasia.com/

### Stream URL

http://210.210.155.35/uq2663/h/h19/index.m3u8
but not in english sadly.

### Notes

Hello i was wondering if you could add GEM  but in English subtitle.
the ones you have currently are in some other language im not sure what.
https://www.lyngsat.com/tvchannels/in/Gem.html here is the lyngsat thing.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by MeanXBeam** [comment]
i couldnt find any with english subtitle im not really sure where to find.

**Comment by SonicPhoon** [comment]
Problem: new stream feed needed as their provider is going to drop out GEM due to contract issues

**Comment by MeanXBeam** [comment]
i did see that maybe someone could get it from mewatch as they have gem on there.

**Comment by Jitterdoomer** [comment]
I really wish they could transmit this channel but with English subtitles and announcer due to the fact that the 576 one got shut down as it was transmitted from Dens.TV.

**Comment by novalkomik** [comment]
They actually still active on UseeTV (Indihome - Indonesia), and some of the people still able to watch it on IPTV.
The only problem is that to get the m3u8 and other things for it's verification.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/sg.m3u#L16-L17
