### ISSUE TITLE
Broken: JP Channels stucking 

### ISSUE THREAD

**Issue by nikitaed** [iptv-org/iptv#7557]
### Stream Title

Animax Japan; BS-TBS; BS-Fuji; BS Nippon TV; NHK BS1; WOWOW Channels, etc. 

### What happened to the stream?

Constantly interrupts/lagging

### Notes

More Japanese channels get stuck/lagging every 10-20 seconds.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Please read the [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream) before posting your next request.

**Comment by nikitaed** [comment]
I wrote several channels to understand that the problem concerns channels with an IP address of 51.81.66.195. All channels with this IP has lagging/stucking

**Comment by nikitaed** [comment]
@freearhey 
I wrote several channels to understand that the problem concerns channels with an IP address of 51.81.66.195. All channels with this IP has lagging/stucking
