### ISSUE TITLE
Add: Al Aoula (Not Al Aoula Laayoune)

### ISSUE THREAD

**Issue by EA3H** [iptv-org/iptv#7566]
### Channel Name

Al Aoula

### Stream URL

http://snrtlive.ma/al-aoula-live-hd-%D8%A7%D9%84%D8%A8%D8%AB-%D8%A7%D9%84%D9%85%D8%A8%D8%A7%D8%B4%D8%B1-%D9%82%D9%86%D8%A7%D8%A9-%D8%A7%D9%84%D8%A3%D9%88%D9%84%D9%89

### Notes

The current channel list includes Al Aoula Laayoune and NOT Al Aoula. Both these channels are not the same despite the name similarity and they were both previously available but this is no longer the case. Please add the Al Aoula channel. Much appreciated!

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Should be around : https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/al_aoula_inter/hls_snrt/al_aoula_inter.m3u8

**Comment by EA3H** [comment]
![20220622_125253](https://user-images.githubusercontent.com/107959758/175022716-ae5355a6-bb7f-4cc1-a3fe-ed9e4786d821.jpg)

Unfortunately it's not there.

**Comment by LaneSh4d0w** [comment]
It's said to be blocked, so idk if it'll be shown.

**Comment by brahim024** [comment]
I cannot use this link for ffmpeg HTTP error 403 Forbidden
did u have an insecure link

**Comment by LaneSh4d0w** [comment]
FR : Non, les services de la SNRT ne possèdent que le lien sécurisé mentionné ci-dessus. Nous ne sommes pas à l'abri cependant d'un problème d'expiration de certficat.

EN : No, the SNRT services only possess the secured link mentioned above. However, we are not immune to certificate expiry issues.

**Comment by brahim024** [comment]
thank you @LaneSh4d0w
