### ISSUE TITLE
Replace: 3/24

### ISSUE THREAD

**Issue by Smark223** [iptv-org/iptv#7568]
### Stream Title

3/24 (1080p)

### What happened to the stream?

Not loading

### Possible Replacement

https://directes-tv-int.ccma.cat/live-content/canal324-hls/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
403 https://directes-tv-int.ccma.cat/live-content/canal324-hls/master.m3u8

**Comment by freearhey** [comment]
The broken link has been removed from the playlist.

Closed in favor: #8163
