### ISSUE TITLE
Replace: El 33

### ISSUE THREAD

**Issue by Smark223** [iptv-org/iptv#7569]
### Stream Title

El 33 (1080p) 

### What happened to the stream?

Not loading

### Possible Replacement

https://directes-tv-es.ccma.cat/live-content/c33-super3-hls/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
403 https://directes-tv-cat.ccma.cat/live-origin/c33-super3-hls/master.m3u8
403 https://directes-tv-es.ccma.cat/live-origin/c33-super3-hls/master.m3u8
403 https://directes-tv-int.ccma.cat/live-origin/c33-super3-hls/master.m3u8

**Comment by LaneSh4d0w** [comment]
Working channels for Catalunya are those : 

TV3 Cat https://directes-tv-int.ccma.cat/live-origin/tvi-hls/master.m3u8
3/24 https://directes-tv-int.ccma.cat/live-content/canal324-hls/master.m3u8
Bondía TV https://directes-tv-int.ccma.cat/live-content/bondia-hls/master.m3u8
33/S3 https://directes-tv-int.ccma.cat/live-origin/c33-super3-hls/master.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/es.m3u#L150-L151

**Comment by freearhey** [comment]
The broken link has been removed from the playlist.

Closed in favor: #8162
