### ISSUE TITLE
Replace: One Malta

### ISSUE THREAD

**Issue by Smark223** [iptv-org/iptv#7577]
### Stream Title

One (720p)

### What happened to the stream?

Not loading

### Possible Replacement

https://2-fss-1.streamhoster.com/pl_148/201830-1293592-1/playlist.m3u8

### Notes

Replace the stream url for One in the Malta playlist. URL has changed slightly

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by taodicakhia** [comment]
![image](https://user-images.githubusercontent.com/74099190/175946356-67013871-1dee-4d4a-855c-180c8f852f1b.png)
Working for me

**Comment by Smark223** [comment]
> ![image](https://user-images.githubusercontent.com/74099190/175946356-67013871-1dee-4d4a-855c-180c8f852f1b.png) Working for me

The one in the playlist or the one I've suggested as a replacement?

**Comment by taodicakhia** [comment]
> > ![image](https://user-images.githubusercontent.com/74099190/175946356-67013871-1dee-4d4a-855c-180c8f852f1b.png) Working for me
> 
> The one in the playlist or the one I've suggested as a replacement?

the one in the playlist

**Comment by Smark223** [comment]
Odd, I get this 

![image](https://user-images.githubusercontent.com/97887305/176135158-de1bc654-2c11-47b7-b126-527a928b8613.png)

**Comment by taodicakhia** [comment]
> Odd, I get this
> 
> ![image](https://user-images.githubusercontent.com/97887305/176135158-de1bc654-2c11-47b7-b126-527a928b8613.png)

Link stream is invalid, please check again

**Comment by Smark223** [comment]
It's the one from the mt.m3u playlist! The one I've suggested to replace it https://2-fss-1.streamhoster.com/pl_148/201830-1293592-1/playlist.m3u8 works perfectly.

**Comment by freearhey** [comment]
The broken link has been removed from the playlist.

Closed in favor: #8160
