### ISSUE TITLE
Add: OhoTV

### ISSUE THREAD

**Issue by jackdaous** [iptv-org/iptv#7579]
### Channel Name

OhoTV - Suomi

### Channel ID

Ohotv.fi

### Website

https://ohotv.fi

### Stream URL

https://5e4bcaad013b8.streamlock.net:443/live/Stream1_720p/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
having https://5e4bcaad013b8.streamlock.net/live/Stream1/playlist.m3u8 works too.
