### ISSUE TITLE
Help with Non Expiring Streams

### ISSUE THREAD

**Issue by themak1985** [iptv-org/iptv#758]
I am trying to figure out how to make these streams not expire - similar to how we handle livestream links. @boomski any idea? 
Edit: i have decided to use this post for all streams I find that expire.

JO: JOSAT - https://josat.tv/live/
IQ: Al Sumaria - https://www.alsumaria.tv/live/video
IQ: Ishtar TV - https://ishtartv.com/stream.html / https://vimeo.com/user105169573 / https://vimeo.com/event/18793/embed
QA: Al Jazeera - https://www.youtube.com/watch?v=YwxAMjL_JFs
SY: Halab Today TV - https://www.youtube.com/watch?v=lDHgsBulOHU
SY: Sham FM - https://ok.ru/live/1366568541799
SY: Souryana - https://ok.ru/video/1529600417398
SY: Nour El-Sham - https://ok.ru/video/1009878048374
SY: Syrian Educational TV - https://ok.ru/video/1472395222646
SY: Alikhbaria - https://ok.ru/video/1205591940726
YM: Balqees - https://www.youtube.com/watch?v=MybvnlEYogA
SA: SBC - https://www.shashatcom.sa/live/
EG: AlGhad - https://youtu.be/dDy6DSWMBQY
EG: Extra News - https://www.youtube.com/watch?v=zqEfxFJb9TY
EG: MeSat - https://www.youtube.com/watch?v=gX9NVzpp5Ac
DZ: Thalitha A3 - https://www.entv.dz/fr/live-thalitha-a3/
DZ: Canal Algérie - https://www.entv.dz/fr/live-canal-algerie/
DZ: 4 Amazigh - https://www.entv.dz/fr/live-tv-4-amazigh/
DZ: Echorouk: https://www.echoroukonline.com/multimedia/#live
DZ: Echorouk News: https://www.echoroukonline.com/multimedia/#live
DZ: Ennahar TV: http://www.1arablive.com/livetv/single-channel/30/ennahar-tv or https://www.ennaharonline.com/live/
DZ: TV5: https://www.entv.dz/fr/live-tv-5-coran/

**Comment by exodiver** [comment]
You might have to restream it yourself.

**Comment by themak1985** [comment]
@exodiver any guides on how to do that?

**Comment by themak1985** [comment]
Changed Issue to reflect a number of channels that I can't get non-expiring streams for - these are all directly from the broadcaster.

**Comment by Link4K** [comment]
@themak1985 If you have LiveProxy installed (https://liveproxy.github.io/) then you can create local urls (https://liveproxy.github.io/url.html#base64)

@freearhey Do you think it's a good idea to have a LiveProxy.m3u file for this project?

**Comment by freearhey** [comment]
@Link4K honestly, I still don't know what LiveProxy does.

**Comment by exodiver** [comment]
> @themak1985 If you have LiveProxy installed (https://liveproxy.github.io/) then you can create local urls (https://liveproxy.github.io/url.html#base64)
> 
> @freearhey Do you think it's a good idea to have a LiveProxy.m3u file for this project?

I don't think it is a good idea as it depends on the installation of the program. Not everyone is technical enough to set up liveproxy on their own.
