### ISSUE TITLE
Add: KCWX-TV

### ISSUE THREAD

**Issue by trancer1994** [iptv-org/iptv#7593]
### Channel Name

KCWX

### Channel ID

KCWXDT1.us

### Website

http://www.kcwx.com

### Notes

Doesn't appear to have a live stream on its website, but they do have an Android app. I'm specifically looking for the stream that app uses, which would start with https://ott.kcwx.com. The link floating around starts with http://65, which probably comes from elsewhere. 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
I do have something that begins with ott.kcwx.com, however I can't seem to find anything since it's blocked in the EU.

**Comment by trancer1994** [comment]
> 
Can you give me the link anyway? I have a proxy which allows me to mock my location and set it to the US.

**Comment by LaneSh4d0w** [comment]
> > 
> 
> Can you give me the link anyway? I have a proxy which allows me to mock my location and set it to the US.

I can't decrypt on mobile sadly. I know it's TLS and it starts with ott.kcwx.com. Link is a blackpage. I've tried https://ott.kcwx.com/live/kcwx/playlist.m3u8 and it gave me a 415 Unsupported Media Type.

**Comment by trancer1994** [comment]
Oh dear. The subdomain is there, but I just need to find it. Is there any way you connect the device you are using to a pc and somehow project your device's display to the computer screen or something, then you can see what's actually happening on the pc? You may be able to decrypt it then. I really, really don't know though. Why do they have to make these things so hard?

**Comment by trancer1994** [comment]
Maybe use Wireshark in some way to convert the traffic you are getting from your android to something else so you can decrypt it?

**Comment by LaneSh4d0w** [comment]
> Oh dear. The subdomain is there, but I just need to find it. Is there any way you connect the device you are using to a pc and somehow project your device's display to the computer screen or something, then you can see what's actually happening on the pc? You may be able to decrypt it then. I really, really don't know though. Why do they have to make these things so hard?

PCAPdroid w/rooted phone should do the trick if you manage to put everything to make it work. Was an idea from @sguinetti

**Comment by trancer1994** [comment]
> 

Yep that should definitely work. Do you have access to that from your end?

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/cac2f96962f43fcec08d835b0878ed36307d4bbe/streams/us.m3u#L656-L657
