### ISSUE TITLE
Add: VTC1 HD

### ISSUE THREAD

**Issue by kirigizakazutovn** [iptv-org/iptv#7594]
### Channel Name

VTC1 HD

### Channel ID

VTC1HD.vn

### Website

https://fptplay.vn

### Stream URL

https://vips-livecdn.fptplay.net/hda1/vtc1_vhls.smil/chunklist_b5000000.m3u8

### Notes

Add to vn.m3u & vn_fptplay.m3u

### Please confirm the following

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Unlike VTC2, this one is geo-blocked to Vietnam only. hdaX links are geoblocked, while hdb/hdc aren't.
