### ISSUE TITLE
Add:  TUDN USA

### ISSUE THREAD

**Issue by DanoGL** [iptv-org/iptv#7599]
### Channel Name

TUDN USA

### Channel ID

TUDNUS.us

### Website

https://www.tudn.com/tudn-livestream-24-7

### Notes

Geoblocked for US Only

Requires login 

### Please confirm the following

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://tkx.mp.lura.live/rest/v2/mcp/video/adstkZj0NvKqzB6e?anvack=NVQrq6a3oZfdBzkefWT1rvdRCoj9XOyx&token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJOVlFycTZhM29aZmRCemtlZldUMXJ2ZFJDb2o5WE95eCIsImV4cCI6MTY1NjE5ODE4NSwiYWRfcGFycyI6eyJkZnAiOnsiaXVfdmFsdWVfZnJvbV9wYWdlIjoiL3VuZGVmaW5lZC9yZC51bml2aXNpb25fdmlkZW9fZGVwb3J0ZXMvZGFpIiwidXJsIjoiaHR0cHM6Ly93d3cudHVkbi5jb20vdHVkbi1saXZlc3RyZWFtLTI0LTciLCJwbGF5ZXJfd2lkdGgiOiI3NTMiLCJwbGF5ZXJfaGVpZ2h0IjoiNDI0IiwicHAiOiJEZXNrdG9wQml0UmF0ZXMiLCJtdnBkIjoidGVtcF9wYXNzIn19LCJ2aWQiOiJhZHN0a1pqME52S3F6QjZlIiwidXNlcl9wYXJzIjp7InByZWZlcnJlZF9jZG4iOnsibmFtZSI6ImFrYW1haSIsImZvcmNlIjp0cnVlfX19.Y9JMF-b_SUsCZ3WMkjU1cmNkiHvT7lmvYLsVbCx-Dhg

**Comment by DanoGL** [comment]
> 

Help pls bro 🙏❤️

**Comment by spotanjo3** [comment]
This is spanish and not USA because the closed captioning is in Spanish only.

**Comment by LaneSh4d0w** [comment]
Southern part of the USA has got a large number of Hispanic people and do have Spanish televisions inside (Telemundo, Novelisima as a few examples). TUDN is based in the USA.

**Comment by spotanjo3** [comment]
Not fair. I dont speak Spanish. 😇

**Comment by LaneSh4d0w** [comment]
My Spanish is broken anyway lol. I do understand Spanish but I will have difficulties speaking it x)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/cac2f96962f43fcec08d835b0878ed36307d4bbe/streams/us.m3u#L1282-L1283
