### ISSUE TITLE
Broken: Disney Channel Japan

### ISSUE THREAD

**Issue by omaromarver** [iptv-org/iptv#7604]
### Stream Title

Disney Channel Japan

### What happened to the stream?

Not loading

### Notes

i dont have another link sorry :(

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
They've locked their streams again. Guess i'll have to delete them.
