### ISSUE TITLE
Add: Repretel Canal 2

### ISSUE THREAD

**Issue by KometaRS** [iptv-org/iptv#7608]
### Channel Name

Canal 2 Repretel 

### Channel ID

Repretel Canal 2.cr

### Website

https://www.repretel.com/envivo-canal2/

### Stream URL

http://190.7.192.164:8004/play/s46

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Nice Astra find.
