### ISSUE TITLE
Add: FUTV

### ISSUE THREAD

**Issue by KometaRS** [iptv-org/iptv#7612]
### Channel Name

FUTV CR

### Channel ID

FUTV.cr

### Website

https://www.futvcr.com/

### Stream URL

http://190.83.119.67:8000/play/a0t3/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Once again, nice Astra find.

Full playlist : http://190.83.119.67:8000/playlist.m3u8

**Comment by erickcm18** [comment]
> Once again, nice Astra find.
> 
> Full playlist : http://190.83.119.67:8000/playlist.m3u8

Link is down? Alternative?

**Comment by Bejab** [comment]
> 

When you find an alternative, let me know.

**Comment by rwrighta** [comment]
Hello any alternative? Thank you

**Comment by Atenciopz16** [comment]
Buenos días, lista de Costa Rica no funciona. Me pueden ayudar con una que traiga FUTV y TIGOSports 
 Gracias

**Comment by imarquitoo** [comment]
no longer working

**Comment by BellezaEmporium** [comment]
> Buenos días, lista de Costa Rica no funciona. Me pueden ayudar con una que traiga FUTV y TIGOSports Gracias

Because you've said thanks :p 

http://45.190.187.226:58092/play/a00q FUTV Costa Rica HD
Tigo Sports HD http://45.4.85.75:8000/play/a03h/index.m3u8

**Comment by CharlesElGriego** [comment]
> > Buenos días, lista de Costa Rica no funciona. Me pueden ayudar con una que traiga FUTV y TIGOSports Gracias
> 
> 
> 
> Because you've said thanks :p 
> 
> 
> 
> http://45.190.187.226:58092/play/a00q FUTV Costa Rica HD
> 
> Tigo Sports HD http://45.4.85.75:8000/play/a03h/index.m3u8

Hi the futv is not working for me?

**Comment by BellezaEmporium** [comment]
> > > Buenos días, lista de Costa Rica no funciona. Me pueden ayudar con una que traiga FUTV y TIGOSports Gracias
> > 
> > 
> > Because you've said thanks :p
> > http://45.190.187.226:58092/play/a00q FUTV Costa Rica HD
> > Tigo Sports HD http://45.4.85.75:8000/play/a03h/index.m3u8
> 
> Hi the futv is not working for me, any update?

Works on my side.

![image](https://github.com/iptv-org/iptv/assets/30985701/8486c49a-0588-4a66-91ae-51c14717b6fa)

**Comment by arturoguillen90** [comment]
Yes, I confirm FUTV CR, work fine in this URL: http://45.190.187.226:58092/play/a00q
But Tigo Sports CR is down.

Thanks for all ...

**Comment by Atenciopz16** [comment]
Ya no funciona FUTV, tigo funciona de maravilla

**Comment by alberthgr** [comment]
FUTV - no funciona.
tigo esta en todas

**Comment by Atenciopz16** [comment]
Hola buenas, me podrán ayudar. Ya no me funciona ninguno de los 2 y la verdad se ve muy bien esos enlaces
