### ISSUE TITLE
Replace: NFL Network

### ISSUE THREAD

**Issue by CODERX24** [iptv-org/iptv#7615]
### Stream Title

NFL Network (720p) [Not 24/7]

### What happened to the stream?

Not loading

### Possible Replacement

https://networkbest.ru.com/cdn/eplayerNFLNetwork/chunks.m3u8

### Notes

the stream loads for a minute on my m3u8 player then has a timeout and the link is still up but does not play on VLC
can someone find a fix to this link?

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/us.m3u#L893-L894

**Comment by freearhey** [comment]
The broken link has been removed from the playlist.

Closed in favor: #8159
