### ISSUE TITLE
Add: Disney ES

### ISSUE THREAD

**Issue by omaromarver** [iptv-org/iptv#7619]
### Channel Name

Disney Channel España

### Stream URL

http://line.eagletv.co/Cristal1/GRKJTFJY4R/1672

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Xtream-Codes server, not accepted.

**Comment by freearhey** [comment]
Closed in favor #7916
