### ISSUE TITLE
Romanian chanels

### ISSUE THREAD

**Issue by Arkashu86** [iptv-org/iptv#762]
Hello, can u update the romania chanel list? Or add more ? I've added the list yesterday and i cand find the important  programs .
Thanks for the effort !

**Comment by freearhey** [comment]
Could you clarify which channels are missing from the playlist?

**Comment by Arkashu86** [comment]
I only saw a printscreen from one of the users but no discovery no antena 1 no kanal d ... national geographic 

Sent from Yahoo Mail on Android 
 
  On Thu, Dec 5, 2019 at 6:06, Aleksandr Statciuk<notifications@github.com> wrote:   
Could you clarify which channels are missing from the playlist?

**Comment by willrock74** [comment]
Hello! 
I made a list of Romanian channels updated in 2020.

Acasa Gold RO	
AcasaTV.ro	
AMC.ro	
AnimalPlanet.ro	
Antena1.ro	
Boomerang.ro	
CartoonNetwork.ro	
ComedyCentralExtra.ro	
Digi24.ro	
DigiAnimalworld.ro	
Digi Life RO	
DigiSport1.ro	
DigiSport2.ro	
DigiSport3.ro	
DigiSport4.ro	
DigiWorld.ro	
DiscoveryChannel.ro	
DiscoveryID.ro	
DiscoveryScience.ro	
DisneyChannel.ro	
EEntertainment.ro	
Etno.ro	
Eurosport1.ro	
Eurosport2.ro	
FashionTV.ro	
Favorit.ro	
FilmBox.ro	
FilmBoxExtra.ro	
FilmBoxFamily.ro	
FilmBoxPlus.ro	
FilmBoxPremium.ro	
Filmcafe.ro	
Film Now RO	
FineLiving.ro	
FishingHunting.ro	
FoodTV.ro	
HappyChannel.ro	
HBO.ro	
HBO2.ro	
HBO3.ro	
HistoryChannel.ro	
HTMusic.ro	
KanalD.ro	
KissTV.ro	
LookPlus.ro	
Look Sport RO	
Look Sport 2 RO	
Look Sport 3 RO	
Megamax.ro	
Minimax.ro	
MusicChannel.ro	
Naşul TV RO	
NatGeo.ro	
NatGeoWild.ro	
Naţional 24 Plus RO	
NationalTV.ro	
NauticalChannel.ro	
NeptunTV.ro	
Nickelodeon.ro	
NickJr.ro	
ParamountChannel.ro	
PrimaTV.ro	
Pro2.ro	Pro 2 RO	
ProCinema.ro	
ProTV.ro	
RealitateaTV.ro	
RomaniaTv.ro	
Sportro.ro	
TarafTV.ro	
TelekomSport1.ro	
TelekomSport2.ro	
TelekomSport3.ro	
TelekomSport4.ro	
TelekomSport5.ro	
TelekomSport6.ro	
TLC.ro	
TNT.ro	
TopShopTV.ro	
TravelChannel.ro	
TravelMix.ro	
TV1000.ro	
TVPaprika.ro	
TVR1.ro	
TVR2.ro	
TVR3.ro	
UTV.ro	
ViasatExplore.ro	
ViasatHistory.ro	
ViasatNature.ro	 
ZUTV.ro	ZU TV RO

**Comment by Arkashu86** [comment]
Wow thx thumbs up!!!! 

Sent from Yahoo Mail on Android 
 
  On Sun, Jan 5, 2020 at 19:38, willrock74<notifications@github.com> wrote:   
Hello!
I made a list of Romanian channels updated in 2020.

Acasa Gold RO
AcasaTV.ro
AMC.ro
AnimalPlanet.ro
Antena1.ro
Boomerang.ro
CartoonNetwork.ro
ComedyCentralExtra.ro
Digi24.ro
DigiAnimalworld.ro
Digi Life RO
DigiSport1.ro
DigiSport2.ro
DigiSport3.ro
DigiSport4.ro
DigiWorld.ro
DiscoveryChannel.ro
DiscoveryID.ro
DiscoveryScience.ro
DisneyChannel.ro
EEntertainment.ro
Etno.ro
Eurosport1.ro
Eurosport2.ro
FashionTV.ro
Favorit.ro
FilmBox.ro
FilmBoxExtra.ro
FilmBoxFamily.ro
FilmBoxPlus.ro
FilmBoxPremium.ro
Filmcafe.ro
Film Now RO
FineLiving.ro
FishingHunting.ro
FoodTV.ro
HappyChannel.ro
HBO.ro
HBO2.ro
HBO3.ro
HistoryChannel.ro
HTMusic.ro
KanalD.ro
KissTV.ro
LookPlus.ro
Look Sport RO
Look Sport 2 RO
Look Sport 3 RO
Megamax.ro
Minimax.ro
MusicChannel.ro
Naşul TV RO
NatGeo.ro
NatGeoWild.ro
Naţional 24 Plus RO
NationalTV.ro
NauticalChannel.ro
NeptunTV.ro
Nickelodeon.ro
NickJr.ro
ParamountChannel.ro
PrimaTV.ro
Pro2.ro Pro 2 RO
ProCinema.ro
ProTV.ro
RealitateaTV.ro
RomaniaTv.ro
Sportro.ro
TarafTV.ro
TelekomSport1.ro
TelekomSport2.ro
TelekomSport3.ro
TelekomSport4.ro
TelekomSport5.ro
TelekomSport6.ro
TLC.ro
TNT.ro
TopShopTV.ro
TravelChannel.ro
TravelMix.ro
TV1000.ro
TVPaprika.ro
TVR1.ro
TVR2.ro
TVR3.ro
UTV.ro
ViasatExplore.ro
ViasatHistory.ro
ViasatNature.ro
ZUTV.ro ZU TV RO

**Comment by igorescu04** [comment]
I'm also interested in this playlist.

**Comment by jreman87** [comment]
Buna!Va rog frumos,puteti sa-mi trimiteti si mie lista m3u,cu programele romanesti?

**Comment by SileC** [comment]
lista de mai sus e doar o lista cu toate canalele romanesti. Cele free sunt in linkul github. Celelalte nu au linkuri. Pt PROTV un link e in lista de Moldova In github.

**Comment by willrock74** [comment]
s-a cerut mai sus o lamurire despre ce canale lipsesc din lista de streaming...cam acelea lipsesc...

**Comment by SileC** [comment]
Digi24.ro si KanalD.ro au live stream pe siteul lor.

**Comment by freearhey** [comment]
Animal Planet, Discovery Channel, Discovery ID, Discovery Science, Eurosport, Fine Living, Food TV, TLC and Travel Channel cannot be added to the playlist due to claims of the copyright holder. More details here: #1831

**Comment by freearhey** [comment]
Closed in favor #1957

**Comment by Irine1979** [comment]
Cum copiez și eu liste M3u românești ?

**Comment by AndyMinkYT** [comment]
puteti si voi sa gasesti tv city? daca poti, trimite-mi m3u8-ul.
