### ISSUE TITLE
Broken: TVP channels [PL]

### ISSUE THREAD

**Issue by trancer1994** [iptv-org/iptv#7625]
### Stream Title

TVP 1 (720p)

### What happened to the stream?

Not loading

### Notes

Some of the TVP streams (Polish state TV) are not working. For instance, TVP 1 (720p) says Error as the status in the list. Also, can you try to add the other TVP channels (TVP 2, TVP 3, TVP Info etc)? Note: the TVP channels are heavily tokened I think, and may be very difficult to implement but I'm really not sure on this. 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Couldn't find the original link by the title given.
