### ISSUE TITLE
Add: TVCG Parlamentarni

### ISSUE THREAD

**Issue by pukozs75** [iptv-org/iptv#7627]
### Channel Name

TVCG Parlamentarni

### Website

https://rtcg.me/tv/gledaj-tvcg-parlamentarni.html

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://parlament.rtcg.me:1936/pr/smil:parlament.smil/playlist.m3u8

**Comment by pukozs75** [comment]
> https://parlament.rtcg.me:1936/pr/smil:parlament.smil/playlist.m3u8

# Is it possible to add this channel to Montenegro playlist?
