### ISSUE TITLE
Add: Telecuracao

### ISSUE THREAD

**Issue by Boxiet** [iptv-org/iptv#7637]
### Stream Title

Telecuracao (720P)

### What happened to the stream?

Not loading

### Possible Replacement

https://cariflix.com/details?id=5ed71e232cdc24a3d08cd6de&type=channel

### Notes

The telecuracao website is down. you can use their new website cariflix.com

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
https://streannlivecariflix.cachefly.net/cariflix1/cariflix1/playlist.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/198d0527f073c81119ccceaebdede8e79f542028/streams/cw.m3u#L6-L9

**Comment by bigflorin** [comment]
hi please can you fix telecuracao its down

**Comment by LaneSh4d0w** [comment]
Became geo-restricted : https://ott3.streann.com/loadbalancer/services/public/channels/56992db2e4b045bf250ba13c/playlist.m3u8

**Comment by bigflorin** [comment]
ok thanks you for your help is any website can offer to buy just the channels in m3u8 file if possible let me know

**Comment by bigflorin** [comment]
https://directmediacuracao.com/index.php?page=tv

please can you give me m3u8 for this website
