### ISSUE TITLE
Add: Now TV

### ISSUE THREAD

**Issue by AzeemHadzrie** [iptv-org/iptv#7651]
### Channel Name

Now TV

### Channel ID

NowTVLive.hk

### Website

news.now.com/home/live

### Stream URL

https://ewcdnsite09.nowe.com/session/09-2a6fca582d05472e7ceb621f9ef6b/Content/HLS/LIVE/Channel(HLS_CH332N)/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Data is in there : https://d1jithvltpp1l1.cloudfront.net/getLiveURL?channelno=332&mode=prod&audioCode=&format=HLS&callerReferenceNo=20140702122500
