### ISSUE TITLE
Broken: TV Osaka

### ISSUE THREAD

**Issue by andrew-walthall** [iptv-org/iptv#7657]
### Stream Title

TV Osaka

### What happened to the stream?

Not loading

### Notes

TV Osaka was working fine until last week when it, MTV Japan, and several other Japanese streams suddenly stopped working. Upon attempting to load any of them an error message was shown saying, "Something went wrong with the stream."

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Couldn't find the original link by the title given.
