### ISSUE TITLE
Add: BOX Hits

### ISSUE THREAD

**Issue by RONTVHD** [iptv-org/iptv#7659]
### Channel Name

BOX Hits

### Channel ID

BoxHits.uk

### Website

https://www.intheboxtv.eu/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/13d2f470b7e5b647c0d24d4b6897c651d4b52971/streams/uk.m3u#L189-L192
