### ISSUE TITLE
Replace: Cartoon Network Asia

### ISSUE THREAD

**Issue by BBBURENEEBB** [iptv-org/iptv#7661]
### Stream Title

Cartoon Network Asia

### Broken Link

http://198.16.106.62:8278/streams/d/Cn/playlist.m3u8

### What happened to the stream?

Constantly interrupts/lagging

### Possible Replacement

https://stream-cdn.mncnow.id/live/eds/CartoonNetwork/sa_hls_vmx/CartoonNetwork.m3u8

### Notes

timed out stream url replaced with online stream url

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/us.m3u#L245-L246

**Comment by bbbureneecartoonz** [comment]
> https://www.youtube.com/channel/UC9hVEGaTpAYMVd-bRsOYKwA/live

tats not a live channel it's a cartoon

**Comment by Rxplicat3dStxr4ge** [comment]
> ### Stream Title
> Cartoon Network Asia
> 
> ### What happened to the stream?
> Constantly interrupts/lagging
> 
> ### Possible Replacement
> https://stream-cdn.mncnow.id/live/eds/CartoonNetwork/sa_hls_vmx/CartoonNetwork.m3u8
> 
> ### Notes
> timed out stream url replaced with online stream url
> 
> ### Please confirm the following
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

![image](https://user-images.githubusercontent.com/99167692/187384955-75e3bf85-1108-4e58-a9d0-0c5d4ba8920f.png)
stream isnt working sadly

**Comment by Rxplicat3dStxr4ge** [comment]
> > https://www.youtube.com/channel/UC9hVEGaTpAYMVd-bRsOYKwA/live
> 
> tats not a live channel it's a cartoon

what else would it fucking be
live action network?

**Comment by Rxplicat3dStxr4ge** [comment]
> https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/us.m3u#L245-L246

![image](https://user-images.githubusercontent.com/99167692/187385381-a2076f44-1b9a-4b4f-876c-f74bd2a71a9d.png)
this doesnt work on vlc, im not sure about other m3u8 players

**Comment by F640** [comment]
> ### Stream Title
> Cartoon Network Asia
> 
> ### What happened to the stream?
> Constantly interrupts/lagging
> 
> ### Possible Replacement
> https://stream-cdn.mncnow.id/live/eds/CartoonNetwork/sa_hls_vmx/CartoonNetwork.m3u8
> 
> ### Notes
> timed out stream url replaced with online stream url
> 
> ### Please confirm the following
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

You are giving drm'ed stream :v. Same as this one: https://liveanevia.mncnow.id/live/eds/CartoonNetwork/sa_dash_vmx/CartoonNetwork.mpd



> https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/us.m3u#L245-L246

Buffering indefinitely


> https://www.youtube.com/channel/UC9hVEGaTpAYMVd-bRsOYKwA/live

Not this one

**Comment by freearhey** [comment]
https://stream-cdn.mncnow.id/live/eds/CartoonNetwork/sa_hls_vmx/CartoonNetwork.m3u8 (offline)
<img width="634" alt="image" src="https://user-images.githubusercontent.com/7253922/232260838-e15488f5-c126-41f3-8b4a-045317cff0e0.png">
