### ISSUE TITLE
Add: HBO Indonesia

### ISSUE THREAD

**Issue by BBBURENEEBB** [iptv-org/iptv#7662]
### Channel Name

HBO Indonesia

### Channel ID

HBOIndonesia.id

### Website

https://hbogoasia.id

### Stream URL

https://stream-cdn.mncnow.id/live/eds/hbo-2/sa_hls_vmx/hbo-2.m3u8

### Notes

url

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/cac2f96962f43fcec08d835b0878ed36307d4bbe/streams/vn_fptplay.m3u#L35-L37
