### ISSUE TITLE
Add: Reelz Channel | (US)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7664]
### Channel Name

Reelz Channel

### Channel ID

ReelzChannel.us

### Website

reloltv.com

### Stream URL

https://bcovlive-a.akamaihd.net/c733a9aa448a4a44a10c527c6f5bf7a4/us-east-1/5245389775001/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by TKList** [comment]
No longer works

**Comment by industrystandard1** [comment]
Can confirm, no longer works, it is of the utmost importance that a replacement comes along.
