### ISSUE TITLE
Add: Nick Pluto TV (Ukraine)

### ISSUE THREAD

**Issue by jaigitrep159** [iptv-org/iptv#7668]
### Channel Name

Nick Pluto TV Ukraine

### Channel ID

NickUkraine.ua

### Website

https://www.pluto.tv/de/live-tv/nick-ukraine-de

### Stream URL

http://siloh-sp.plutotv.net/lilo/production/NickUkraine/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/d94d3b49ba64c9e3985bf40bd5c5b9027f36b5bb/streams/us_pluto.m3u#L2030-L2031

**Comment by Neolo** [comment]
Stream is dead
