### ISSUE TITLE
Add: Akili Kids

### ISSUE THREAD

**Issue by Laurent-c4** [iptv-org/iptv#7669]
### Channel Name

Akili Kids!

### Channel ID

AkiliKids.ke

### Website

https://akilikids.co.ke/

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x7tfayd

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x7tfayd
<img width="401" alt="image" src="https://user-images.githubusercontent.com/7253922/186715334-70f4d449-db3f-47db-99a9-5723cf6b485f.png">

**Comment by Alstruit** [comment]
Works on my vlc. Try installing aribb24 for that Failed to create demuxer 0x0 Unknown error
