### ISSUE TITLE
Lithuanian channels 

### ISSUE THREAD

**Issue by Liofka** [iptv-org/iptv#767]
Most of channels not working, or without sound please fix it.

**Comment by freearhey** [comment]
Thank you for bringing this to our attention! 

I've already removed all the broken links from the playlist. As soon as the replacement appears, we will return them back.

**Comment by boomski** [comment]
Updated the channel list with new url for the non working channels

**Comment by Liofka** [comment]
Still getting error playing channel are you sure you updated?

**Comment by boomski** [comment]
yes replaced them by these links

#EXTINF:-1 tvg-logo="https://i.imgur.com/OgZQTPy.png",LNK
https://185.176.117.243/live/eds/LNK/HLS_encr/index.m3u8
#EXTINF:-1 tvg-logo="https://i.imgur.com/jnfOI3O.png",TV3
https://185.176.117.243/live/eds/TV3_LT_HD/HLS_encr/index.m3u8
#EXTINF:-1 tvg-logo="https://i.imgur.com/TAeWSud.jpg",TV6
https://185.176.117.243/live/eds/TV6_LT_SD/HLS_encr/index.m3u8
#EXTINF:-1 tvg-logo="https://i.imgur.com/pYogpSY.png",TV8
https://185.176.117.243/live/eds/TV8_LT_SD/HLS_encr/index.m3u8
#EXTINF:-1 tvg-logo="https://i.imgur.com/tl9MZ9z.png",LRT
https://185.176.117.243/live/eds/LRT/HLS_encr/index.m3u8
#EXTINF:-1 tvg-logo="https://i.imgur.com/tl9MZ9z.png",LRT Lithuania
https://185.176.117.243/live/eds/LRT_Lithuania/HLS_encr/index.m3u8

For me they play.

**Comment by Liofka** [comment]
Oh so they probably didn't started because of protocol https cuz its not verified of certificate

**Comment by mcammm** [comment]
Vbk

**Comment by freearhey** [comment]
@Liofka I've replaced `https` protocol with `http` so now the broadcasts should run without errors.
