### ISSUE TITLE
Add: MTV HD / MTV HD+ | (India)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7670]
### Channel Name

MTV HD

### Channel ID

MTVIndia.in

### Stream URL

http://144.217.70.181:9587/hin2/MTVINDIA/tracks-v1a1/mono.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://144.217.70.181:9587/hin2/MTVINDIA/index.m3u8 adaptive

**Comment by LaneSh4d0w** [comment]
More from Astra channels : 

BOX CINEMA (IN)

http://14.199.164.20:4001/play/a0su/index.m3u8

DISHUM TV (IN)

http://14.199.164.20:4001/play/a0pe/index.m3u8

E24 (IN)

http://14.199.164.20:4001/play/a0pc/index.m3u8

FOOD FOOD (IN)

http://14.199.164.20:4001/play/a0qx/index.m3u8

MUSIC INDIA (IN)

http://14.199.164.20:4001/play/a0mt/index.m3u8

MASTIII (IN)

http://14.199.164.20:4001/play/a0my/index.m3u8

TEHZEEB TV (IN)

http://14.199.164.20:4001/play/a0p5/index.m3u8

TEHZEEB TV (IN)

http://14.199.164.20:4001/play/a0p5/index.m3u8

SARV DHARM SANGAM (IN)

http://14.199.164.20:4001/play/a0nn/index.m3u8

DHINCHAAK (IN)

http://14.199.164.20:4001/play/a0o5/index.m3u8

DHINCHAAK 2 (IN)

http://14.199.164.20:4001/play/a0tm/index.m3u8

M TUNES (IN)

http://14.199.164.20:4001/play/a0p2/index.m3u8
