### ISSUE TITLE
Add: CNN Turk

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#7680]
### Stream Title

CNN Turk

### What happened to the stream?

Not loading

### Possible Replacement

https://live.duhnet.tv/S2/HLS_LIVE/cnnturknp/track_1_320/playlist.m3u8

### Notes

Found on CNN Turk site

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by ztreamhd** [comment]
I've checked and it's still working.

Btw, here's the 720p link: https://live.duhnet.tv:443/S2/HLS_LIVE/cnnturknp/track_4_1000/playlist.m3u8
And here's the adaptive playlist link: https://live.duhnet.tv/S2/HLS_LIVE/cnnturknp/playlist.m3u8

**Comment by ghost** [comment]
now this stream in e and st.
