### ISSUE TITLE
Add: FX East for USA

### ISSUE THREAD

**Issue by RT5666** [iptv-org/iptv#7683]
### Channel Name

FX 

### Channel ID

FXEast.us

### Website

fxnetworks.com

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by RT5666** [comment]
Will this URL work for adding this channel? https://h2.ustvgo.la/FX/myStream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Ny8yMC8yMDIyIDExOjU0OjA2IFBNJmhhc2hfdmFsdWU9Y0NRZkIyV1JtdkQvK1lJZy9nbkZvQT09JnZhbGlkbWludXRlcz0yNDA=

**Comment by freearhey** [comment]
Closed in favor #8077
