### ISSUE TITLE
More France 24 English And other related channels streams

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#7689]
### Stream Title

France 24 English

### What happened to the stream?

Not loading

### Possible Replacement

https://p-alchimie-services-live.akamaized.net/france24_en/simple.isml/master.m3u8?hdnts=exp=1657434723~acl=/france24_en/simple.isml/*~id=ABiyjojs07cAOTXI~hmac=1307ccece8cd4d4b383bc5ffa03295da531bedc19f6a5af2f89d0a5fde3e386f

### Notes

Found on tvplayer
More:
France 24 French: https://p-alchimie-services-live.akamaized.net/france24_fr/simple.isml/master.m3u8?hdnts=exp=1657434986~acl=/france24_fr/simple.isml/*~id=ABiyjsqqlbwAOTX9~hmac=56e27b5d9129b940b4a48916fff7d28444a75472e84fd65ea4a2666d120e0245
France 24 Espanol: https://p-alchimie-services-live.akamaized.net/france24_es/simple.isml/master.m3u8?hdnts=exp=1657435039~acl=/france24_es/simple.isml/*~id=ABiyjtfMgBsAMnTo~hmac=81390a73e46f8e6cc95ed525c18f10fcac644f84e3ad84cbd558c661e8f53f9f
France 24 Arabic: https://p-alchimie-services-live.akamaized.net/ogl_group_1/france24_ar/simple.isml/master.m3u8?hdnts=exp=1657435070~acl=/ogl_group_1/france24_ar/simple.isml/*~id=ABiyjt-2vuwAYj5c~hmac=c295139f8ceb1756183bdc5c6821132881874dead7b3a6dbe767a2995b77b6f6

### Please confirm the following

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by darrencycheung** [comment]
https://p-alchimie-services-live.akamaized.net/france24_en/simple.isml/hdntl=exp=1657529804~acl=%2f*~id=ABiypRMCnzQAYkdV~data=hdntl~hmac=3a9a5aa18046060abe34578364827d724554e7d211faf246b26794b9c2426593/simple-audio_eng=128000-video=2600000.m3u8 (Work, English)

**Comment by darrencycheung** [comment]
https://p-alchimie-services-live.akamaized.net/france24_fr/simple.isml/hdntl=exp=1657530549~acl=%2f*~id=ABiypc0YC_YAYkeJ~data=hdntl~hmac=c51aaea06d21fdbe203af8a00f88fb6be415f26a5d03516c5386b8232fc2e267/simple-audio_fre=128000-video=2600000.m3u8 (Work, French)
https://p-alchimie-services-live.akamaized.net/france24_es/simple.isml/hdntl=exp=1657530606~acl=%2f*~id=ABiypdt1h_AAZiKo~data=hdntl~hmac=6fd6b373140c687417dd76d89bdbbba19a482900d5e763cc58238e08da4cc507/simple-audio_spa=128000-video=2600000.m3u8 (Work, Spanish)
https://p-alchimie-services-live.akamaized.net/ogl_group_1/france24_ar/simple.isml/hdntl=exp=1657530638~acl=%2f*~id=ABiypeNqQtkAMn5n~data=hdntl~hmac=cbcd18e8acec57195f133edee2606af80b6c9f2cb868fb6972ef4f44393125e0/simple-audio_ara=128000-video=2600000.m3u8 (Work, Arabic)
Anyone have others m3u8s for France 24?

**Comment by darrencycheung** [comment]
So I can use the files on my TV and beyond.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/fr.m3u#L97-L98

**Comment by MALUrbina** [comment]
> #EXTINF:-1 ,France 24 AR https://helga.iptv2022.com/France24_ar/index.m3u8 (YT Feed) https://www.youtube.com/channel/UCdTyuXgmJkG_O8_75eqej-w/live
> 
> #EXTINF:-1 ,France 24 ENG https://d4de59d01af447a498cb0565ad005588.mediatailor.us-east-1.amazonaws.com/v1/master/82ded7a88773aef3d6dd1fedce15ba2d57eb6bca/viewmedia-7/live_091/HD/playlist.m3u8 #EXTINF:-1 ,France 24 ENG http://n1.klowdtv.net/live2/france24_720p/chunks.m3u8 (YT Feed) https://www.youtube.com/channel/UCQfwfsi5VrQ8yKZ-UWmAEFg/live
> 
> #EXTINF:-1 ,France 24 ES http://n1.klowdtv.net/live2/france24sp_720p/chunks.m3u8 #EXTINF:-1 ,France 24 ES https://helga.iptv2022.com/France24_es/index.m3u8 (YT Feed) https://www.youtube.com/channel/UCUdOoVWuWmgo1wByzcsyKDQ/live
> 
> #EXTINF:-1 ,France 24 FR https://d4de59d01af447a498cb0565ad005588.mediatailor.us-east-1.amazonaws.com/v1/master/82ded7a88773aef3d6dd1fedce15ba2d57eb6bca/viewmedia-7/live_092/HD/playlist.m3u8 #EXTINF:-1 ,France 24 FR https://helga.iptv2022.com/France24_fr/index.m3u8 (YT Feed) https://www.youtube.com/channel/UCCCPCZNChQdGa9EkATeye4g

Working links. Thanks.

Can someone provide France 24 Español m3u8 like the link of France 24 English?
 https://d4de59d01af447a498cb0565ad005588.mediatailor.us-east-1.amazonaws.com/v1/master/82ded7a88773aef3d6dd1fedce15ba2d57eb6bca/viewmedia-7/live_091/HD/playlist.m3u8
