### ISSUE TITLE
Add: Fox Deportes (USA)

### ISSUE THREAD

**Issue by DanoGL** [iptv-org/iptv#7690]
### Channel Name

Fox Deportes

### Channel ID

FoxDeportes.us

### Website

https://www.capodeportes.fr/play/tudn.php

### Notes

The stream is from a pirate site, can´t get the m3u for some reason

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://yatn9ng5b2d6a9e4.cdnexpress37.net:8443/hls/oivvy1q.m3u8?s=psdGoBCOl_6CJRMJSk3uiQ&e=1657590777

Tokened + seems to be an alternative of Wigistream or things of some sort. Not easy to get them.

**Comment by freearhey** [comment]
Duplicate #7606
