### ISSUE TITLE
Add: LTO Televisión

### ISSUE THREAD

**Issue by ltocatamarca** [iptv-org/iptv#7699]
### Channel Name

LTO Televisión

### Website

https://lastejasonline.blogspot.com/p/lto-television.html

### Stream URL

https://ltocatamarca.github.io/ltotv.m3u8

### Notes

Our channel transmits from Catamarca, Argentina

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by ltocatamarca** [comment]
I already edited the github link. in case the channel is added, use the github link

**Comment by LaneSh4d0w** [comment]
@sguinetti made a PR adding your channel, I couldn't do it due to the fact that I'm busy since May.

I see you also have a radio, I plan adding it on my IPRD repository.

**Comment by ltocatamarca** [comment]
Hello, thanks for adding the channel. about the radio, no problem, any data you need, I'll pass it to you
