### ISSUE TITLE
Add: Change URL Canal 11 CR

### ISSUE THREAD

**Issue by KometaRS** [iptv-org/iptv#7713]
### Channel Name

Canal 11 Repretel.cr

### Channel ID

Canal 11 Repretel.cr

### Website

https://www.repretel.com/en-vivo-canal-11

### Stream URL

https://d3bgcstab9qhdz.cloudfront.net/hls/canal11_360.m3u8

### Notes

Please Change de URL

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://d3bgcstab9qhdz.cloudfront.net/hls/canal11.m3u8
