### ISSUE TITLE
Replace: Nickelodeon East (360p)

### ISSUE THREAD

**Issue by jaigitrep159** [iptv-org/iptv#7722]
### Stream Title

Nickelodeon East (360p)

### What happened to the stream?

Not loading

### Possible Replacement

https://h3.ustvgo.la/Nickelodeon/myStream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Ny8xNC8yMDIyIDEwOjM3OjU3IEFNJmhhc2hfdmFsdWU9Wk0wRVZYK0kyR25odWNzWUVkOFUxdz09JnZhbGlkbWludXRlcz0yNDA=

### Notes

from this: http://tv247us.com/watch/nickelodeon-tv/

did using an inspect element, copied the link, tested using Streamlink CLI v4.2.0, has a same quality (360p)

without a wmsAuthSign query parameter causes a 403 forbidden client error.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by ztreamhd** [comment]
Those links are /almost/ impossible to use, since the token includes a referer, cookie settings and the user's IP

**Comment by jaigitrep159** [comment]
hmmm yeah

**Comment by jaigitrep159** [comment]
as i noticed it, after expiring, the link goes different. This time it's h4 instead of h3

**Comment by spotanjo3** [comment]
Obviously this tv247us link is very useless ?

**Comment by LaneSh4d0w** [comment]
interestingly enough I have http://live.tv247.club/tv247/nickelodeon.m3u8

**Comment by spotanjo3** [comment]
> interestingly enough I have http://live.tv247.club/tv247/nickelodeon.m3u8 (with a big referer to http://tv247.us)

Not work.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/us.m3u#L897-L898

**Comment by LaneSh4d0w** [comment]
this link simply doesn't work afaik.

**Comment by freearhey** [comment]
https://h3.ustvgo.la/Nickelodeon/myStream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Ny8xNC8yMDIyIDEwOjM3OjU3IEFNJmhhc2hfdmFsdWU9Wk0wRVZYK0kyR25odWNzWUVkOFUxdz09JnZhbGlkbWludXRlcz0yNDA= (offline)
<img width="837" alt="image" src="https://user-images.githubusercontent.com/7253922/232229107-7fb23c87-f2ea-4bdc-a947-86b7381795ef.png">

http://live.tv247.club/tv247/nickelodeon.m3u8 (offline)
<img width="330" alt="image" src="https://user-images.githubusercontent.com/7253922/232229160-cdcbf632-bb2f-48d2-91bb-54da1b64f81f.png">

Broken link removed from playlist.
