### ISSUE TITLE
Add: KBS WORLD

### ISSUE THREAD

**Issue by jbcooter** [iptv-org/iptv#7723]
### Channel Name

KBS World

### Channel ID

kbsworld.kr

### Website

https://epg.pm/stream/395d673036d1fa1aba78f67dec15d116c50197216c4c6d0de9da30bd60a8f07f.m3u8

### Stream URL

https://epg.pm/stream/395d673036d1fa1aba78f67dec15d116c50197216c4c6d0de9da30bd60a8f07f.m3u8

### Notes

This is higher quality.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://kbsworld-ott.akamaized.net/hls/live/2002341/kbsworld/master.m3u8

**Comment by Nimuthu2021** [comment]
Those don't work

**Comment by BellezaEmporium** [comment]
![Screenshot_2024-02-05-09-58-17-26_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/iptv-org/iptv/assets/30985701/621744a4-fb5d-416c-8924-6d0d452373e7)

![Screenshot_2024-02-05-09-58-33-07_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/iptv-org/iptv/assets/30985701/adf94108-c775-4a36-a629-cd14a8d9139b)

Both work.

**Comment by NimuthuGanegoda** [comment]
It doesn't work
