### ISSUE TITLE
Add: JTBC

### ISSUE THREAD

**Issue by jbcooter** [iptv-org/iptv#7726]
### Channel Name

JTBC

### Channel ID

JTBC.kr

### Website

https://epg.pm/stream/163132c13e45ad9cc816eb14c951d5f0e114c38fe0a92687f178759747b306c1.m3u8

### Stream URL

https://epg.pm/stream/163132c13e45ad9cc816eb14c951d5f0e114c38fe0a92687f178759747b306c1.m3u8

### Notes

This works.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://apichvod19.seezntv.com/OTM/10010_M.m3u8?AdaptiveType=HLS&SessionID=3438d7e9-3e70-43b1-9fe6-b8290cd25403
