### ISSUE TITLE
Add: MNet

### ISSUE THREAD

**Issue by jbcooter** [iptv-org/iptv#7732]
### Channel Name

Mnet

### Channel ID

MNET.kr

### Website

https://epg.pm/stream/219abb07864abd493cabb6abfab26cbf926f7a0f45b5eb0c85bfcb8eaf5c5bdc.m3u8

### Stream URL

https://epg.pm/stream/219abb07864abd493cabb6abfab26cbf926f7a0f45b5eb0c85bfcb8eaf5c5bdc.m3u8

### Notes

This works.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://apichvod19.seezntv.com/OTM/10150_M.m3u8?AdaptiveType=HLS&SessionID=3438d7e9-3e70-43b1-9fe6-b8290cd25403

https://apichvod19.seezntv.com/OTM/10140_M.m3u8?AdaptiveType=HLS&SessionID=3438d7e9-3e70-43b1-9fe6-b8290cd25403

https://apichvod19.seezntv.com/OTM/10130_M.m3u8?AdaptiveType=HLS&SessionID=3438d7e9-3e70-43b1-9fe6-b8290cd25403

**Comment by LaneSh4d0w** [comment]
XXXXX_A is Audio only

XXXXX_V is Video only

XXXXX_M seems to refer to mux, both audio and video

**Comment by allanf181** [comment]
I found 110 channels in these urls, I believe that about 100 can be added because some are on the blacklist

**Comment by allanf181** [comment]
XXXXX_A is Audio only

XXXXX_L is 404p

XXXXX_M is 720p

XXXXX_H is 1080p

**Comment by LaneSh4d0w** [comment]
If you do not live in South Korea, I suggest using the L link. The quality is still correct for the bandwidth they allocate to their service. (I'm fibered, and it's really difficult to get at least 5 seconds of stream without cutting all the time with either the H or M stream)
