### ISSUE TITLE
Add: Gayo TV

### ISSUE THREAD

**Issue by jbcooter** [iptv-org/iptv#7733]
### Channel Name

Gayo TV

### Channel ID

G

### Website

http://gayotv.net:8080/live/gayotv.m3u8

### Stream URL

http://gayotv.net:8080/live/gayotv.m3u8

### Notes

This works.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
I think it was (or is) in our playlists.
