### ISSUE TITLE
Add: KBS Story

### ISSUE THREAD

**Issue by jbcooter** [iptv-org/iptv#7738]
### Channel Name

KBS Story

### Channel ID

KBSStory.kr

### Website

https://epg.pm/stream/743f9194f12ceaa9db7fd079517c2a394dfc98be18038a3017a0d7eb367202d3.php

### Stream URL

https://epg.pm/stream/743f9194f12ceaa9db7fd079517c2a394dfc98be18038a3017a0d7eb367202d3.php

### Notes

This works.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://ye23.vip/z7z8/2021/kbs2020.php?id=8
