### ISSUE TITLE
Add: KBS N Life

### ISSUE THREAD

**Issue by jbcooter** [iptv-org/iptv#7739]
### Channel Name

KBS N Life

### Channel ID

KBSNLife.kr

### Website

https://epg.pm/stream/a7c9be0d7309cf8615f05345c98cd19bf49e7b146b90c343322459f6abb07eaa.php

### Stream URL

https://epg.pm/stream/a7c9be0d7309cf8615f05345c98cd19bf49e7b146b90c343322459f6abb07eaa.php

### Notes

This works.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://ye23.vip/z7z8/2021/kbs2020.php?id=7
