### ISSUE TITLE
Add: KBS Drama

### ISSUE THREAD

**Issue by jbcooter** [iptv-org/iptv#7740]
### Channel Name

KBS Drama

### Channel ID

KBSdrama.kr

### Website

https://epg.pm/stream/d016f19bae4dec97ffdbd68c95307d5f60d710a738bd30552e40f852db705a51.php

### Stream URL

https://epg.pm/stream/d016f19bae4dec97ffdbd68c95307d5f60d710a738bd30552e40f852db705a51.php

### Notes

This works.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://ye23.vip/z7z8/2021/kbs2020.php?id=5
