### ISSUE TITLE
Add: KBS Joy

### ISSUE THREAD

**Issue by jbcooter** [iptv-org/iptv#7741]
### Channel Name

KBS Joy

### Channel ID

KBSJoy.kr

### Website

https://epg.pm/stream/11027e6b31fc7402597d895f14fbc6d7664a30a9cdc2d287794a0924bdce6c2b.php

### Stream URL

https://epg.pm/stream/11027e6b31fc7402597d895f14fbc6d7664a30a9cdc2d287794a0924bdce6c2b.php

### Notes

This works.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://ye23.vip/z7z8/2021/kbs2020.php?id=6
