### ISSUE TITLE
Add: SBS

### ISSUE THREAD

**Issue by jbcooter** [iptv-org/iptv#7744]
### Channel Name

SBS

### Channel ID

SBS.kr

### Website

https://epg.pm/stream/4c802668d96df7f50a4ca9276438b69ed9e7ee16af14e6fb47f414df0b89a2b1.php

### Stream URL

https://epg.pm/stream/4c802668d96df7f50a4ca9276438b69ed9e7ee16af14e6fb47f414df0b89a2b1.php

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://ye23.win/iptv/sbs5.1.php?id=S01

**Comment by Alstruit** [comment]
Ok, so I analyzed all of the SBS channels from that website. Some entries contain duplicates from that website, while others are already included in the kr.m3u. A few of the links point to the main SBS website, where there is a 3-minute preview restriction.

These are what seem new to me.

http://222.109.117.27:9981/stream/channelid/2096368258 -> SBS UHD 1080p

http://59.23.231.102:1935/live/UBCstream/playlist.m3u8 -> UBC SBS 540p

http://1.245.74.5:1935/live/tv/.m3u8 -> TJB SBS 1080p

**Comment by Alstruit** [comment]
Fixed #7765.
