### ISSUE TITLE
Add: Sky tg24

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#7757]
### Channel Name

Sky TG 24

### Channel ID

SkyTG24.it

### Stream URL

https://dai.google.com/linear/hls/pb/event/eG_v9uiRSoerzfv8aOJN3A/stream/88d354b3-63a7-40e0-8eb9-63d778246b81:TPE/variant/0aa43909bc50a18162cee1d9f5d71435/bandwidth/1972124.m3u8

### Notes

Found on Sky Video

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by darrencycheung** [comment]
Update it.m3u plz

**Comment by LaneSh4d0w** [comment]
DMCAd channel.
