### ISSUE TITLE
Add: Galavision East | (US)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7781]
### Channel Name

Galavision

### Website

https://piratilla.com/496042/uv?ch=galavision

### Stream URL

https://unidfp-nlds159.global.ssl.fastly.net/nlds/univisionnow/galavision_east/as/live/galavision_east_hd_pc.m3u8?ru=1&dfphmackey=1m1Sh5n3TuyxYDOjgHObWQ&t1=exp=1658082876~salt=p5GC3vc4u5CLfhUl~hash=d91b16a1fde477b6346d0ef328812c66d7f7d5e1~id=43e049cf-57e0-47e8-a0cf-426c98423bd6~acl=/nlds/univisionnow/galavision_east/as/live/*event=1m1Sh5n3TuyxYDOjgHObWQ~exp=1658083056~hmac=04c414b8d24f574042838ead3aeace861fe13dd41e0d3adc95c3e2d2c565d252

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by TKList** [comment]
No. They do work, but they probably expire at some point.

**Comment by ztreamhd** [comment]
That was kinda what I meant. They probably last about 24 hours and then expire

**Comment by TKList** [comment]
We will find out in about 6 hours.

**Comment by robocopz** [comment]
Univision https://unidfp-nlds155.global.ssl.fastly.net/nlds/univisionnow/univision_east2/as/live/univision_east2_hd_pc.m3u8?t1=
UniMás https://unidfp-nlds164.global.ssl.fastly.net/nlds/univisionnow/unimas_east2/as/live/unimas_east2_hd_pc.m3u8?t1=
TUDN https://unidfp-nlds141.global.ssl.fastly.net/nlds/univisionnow/udn2/as/live/udn2_hd_pc.m3u8?t1=
Galavisión https://unidfp-nlds159.global.ssl.fastly.net/nlds/univisionnow/galavision_east/as/live/galavision_east_hd_pc.m3u8?t1=
Fútbol https://unidfp-nlds153.global.ssl.fastly.net/nlds/univisionnow/futbol/as/live/futbol_hd_pc.m3u8?t1=
Despierta https://unidfp-nlds140.global.ssl.fastly.net/nlds/univisionnow/challenge28/as/live/challenge28_hd_pc.m3u8?t1=
Novelas https://unidfp-nlds166.global.ssl.fastly.net/nlds/univisionnow/novelas2plist/as/live/novelas2plist_hd_pc.m3u8?t1=
Delicioso https://unidfp-nlds139.global.ssl.fastly.net/nlds/univisionnow/cocina2/as/live/cocina2_hd_pc.m3u8?t1=

**Comment by LaneSh4d0w** [comment]
Going to try with an US VPN, as they return a weird 405 Not Allowed.

**Comment by LaneSh4d0w** [comment]
Galavision West : https://unidfp-nlds159.global.ssl.fastly.net/nlds/univisionnow/galavision_west/as/live/galavision_west_hd_pc.m3u8?t1=

**Comment by LaneSh4d0w** [comment]
> Univision https://unidfp-nlds155.global.ssl.fastly.net/nlds/univisionnow/univision_east2/as/live/univision_east2_hd_pc.m3u8?t1= UniMás https://unidfp-nlds164.global.ssl.fastly.net/nlds/univisionnow/unimas_east2/as/live/unimas_east2_hd_pc.m3u8?t1= TUDN https://unidfp-nlds141.global.ssl.fastly.net/nlds/univisionnow/udn2/as/live/udn2_hd_pc.m3u8?t1= Galavisión https://unidfp-nlds159.global.ssl.fastly.net/nlds/univisionnow/galavision_east/as/live/galavision_east_hd_pc.m3u8?t1= Fútbol https://unidfp-nlds153.global.ssl.fastly.net/nlds/univisionnow/futbol/as/live/futbol_hd_pc.m3u8?t1= Despierta https://unidfp-nlds140.global.ssl.fastly.net/nlds/univisionnow/challenge28/as/live/challenge28_hd_pc.m3u8?t1= Novelas https://unidfp-nlds166.global.ssl.fastly.net/nlds/univisionnow/novelas2plist/as/live/novelas2plist_hd_pc.m3u8?t1= Delicioso https://unidfp-nlds139.global.ssl.fastly.net/nlds/univisionnow/cocina2/as/live/cocina2_hd_pc.m3u8?t1=

All these links are tested and work on the US. VPNs seems to work too.
