### ISSUE TITLE
Add: NASA TV Public

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7782]
### Channel Name

NASA TV Public

### Stream URL

http://iphone-streaming.ustream.tv/uhls/6540154/streams/live/iphone/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/d94d3b49ba64c9e3985bf40bd5c5b9027f36b5bb/streams/us.m3u#L838-L839
