### ISSUE TITLE
Add: Beautiful Life TV (Taiwan)

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#7788]
### Channel Name

Beautiful Life TV

### Channel ID

BeautifulLifeTV.tw

### Stream URL

https://5ddce30eb4b55.streamlock.net/bltvhd/bltv1/chunklist_w511254805.m3u8

### Notes

人間衛視
Add it to tw.m3u

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://5ddce30eb4b55.streamlock.net/bltvhd/bltv1/playlist.m3u8
