### ISSUE TITLE
Add: Boomerang HD | (Slovenia)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7793]
### Channel Name

Boomerang

### Website

streamstat.net/videoplayer.cgi?sid=471583162&ext=.m3u8

### Stream URL

http://194.163.179.246/slovenci/djeciji/boomerang.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by SMM2LevelsIn30Seconds** [comment]
Dude, I do not think this works correctly, as when I tried both MPV and VLC, it just kept loading forever. Are you sure it actually works?

**Comment by r4inIsBack** [comment]
> Dude, I do not think this works correctly, as when I tried both MPV and VLC, it just kept loading forever. Are you sure it actually works?

This is old, it stopped working last year!
