### ISSUE TITLE
Add: History HD | (Slovenia)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7802]
### Channel Name

History Channel

### Stream URL

http://194.163.179.246/slovenci/doku/historyhd.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://streamer12.xploretv.si/qdcnm4/__cl/cg:prod/__c/A1_SI_HISTORYHD_ott/__op/dash-default/__dci/__f/index.m3u8?redirect=true&admin=xploreTv_test_user

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/d94d3b49ba64c9e3985bf40bd5c5b9027f36b5bb/streams/si.m3u#L20-L21

**Comment by R4IN2007** [comment]
👍
