### ISSUE TITLE
Add: DirecTV Sports | (Argentina)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7803]
### Channel Name

DirecTV Sports

### Stream URL

http://190.210.221.119/Processor3_9_chunklist_b1300000.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/d94d3b49ba64c9e3985bf40bd5c5b9027f36b5bb/streams/ar.m3u#L325-L326
