### ISSUE TITLE
Add: Win Sports+ | (Colombia) [VLC ONLY]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7805]
### Channel Name

Win Sports+

### Channel ID

WinSportsPlus.co

### Stream URL

http://190.61.41.182:8000/play/a2lo/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://190.61.41.182:8000/playlist.m3u8 Full Playlist

**Comment by freearhey** [comment]
The link works not only in VLC.

**Comment by LaneSh4d0w** [comment]
Works on browser but you get the audio only.

**Comment by Canner47** [comment]
Se volvió a caer el enlace, no entra

**Comment by BellezaEmporium** [comment]
Este caso fue repuestado en asunto https://github.com/iptv-org/iptv/issues/2301
