### ISSUE TITLE
Add: History 2 HD

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7806]
### Channel Name

History 2

### Stream URL

http://109.105.205.250:8081/live/HISTORY2/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
I have a doubt about this one... I think it's DMCAd.

**Comment by freearhey** [comment]
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/7253922/185465119-9c2bf698-6e0c-4d3e-b5e7-771748c11da1.png">
