### ISSUE TITLE
lyngsat stream

### ISSUE THREAD

**Issue by amirh123123** [iptv-org/iptv#781]
please add channels from lyngsat stream this address
http://www.lyngsat-stream.com/

**Comment by freearhey** [comment]
Feel free to add channels yourself. Here is an instruction how to do it: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#add-channel

**Comment by georgoskar** [comment]
please correct the list below please change channel addresses
greek list
#EXTINF:0 tvg-id="ext" group-title="channels",baraza tv HD pop & dance
https://video1.getstreamhosting.com:1936/8490/8490/playlist.m3u8
#EXTINF:0 tvg-id="ext" group-title="channels",baraza tv hd greek music
https://video1.getstreamhosting.com:1936/8452/8452/playlist.m3u8

Στις Κυρ, 8 Δεκ 2019 στις 4:28 μ.μ., ο/η Aleksandr Statciuk <
notifications@github.com> έγραψε:

**Comment by georgoskar** [comment]
thanks

Στις Κυρ, 8 Δεκ 2019 στις 5:18 μ.μ., ο/η barazaradio makis galinos <
tsirlokopio@gmail.com> έγραψε:

**Comment by bermufine** [comment]
Hello,
I am requesting an Congo channels, by the name of *digital_congo, Heritage tv, Nyota tv, RTVS1, RTNC2, Antenne A,  Rtg@.

Please Feel free To send me a work link in my gmail: Congomonpays243@gmail.com 

Thank you, and have a wonderful day.
Good luck on future upgrades and keep up the work.

Also, if you can, please add HD streams of Tele50, B-ONE, RTNC, Mwangaza. Don't Forget SPORTS channels like Bein Sport HD from 1 To 12

Thank you once again.
