### ISSUE TITLE
Replace: Teletoon Canada

### ISSUE THREAD

**Issue by XenmZV** [iptv-org/iptv#7820]
### Channel Name

Teletoon 

### Channel ID

N/a

### Website

https://www.teletoon.com/

### Stream URL

N/A

### Notes

Let me know when added 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/ca.m3u#L156-L157

**Comment by freearhey** [comment]
The broken link has been removed from the playlist.

Closed in favor: #8157
