### ISSUE TITLE
Add: MBS TV

### ISSUE THREAD

**Issue by Yunoxa** [iptv-org/iptv#7822]
### Channel Name

MBS TV

### Channel ID

JOOYDTV.jp

### Website

https://www.mbs.jp/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://rip.hidari.moe/get/jptv/get.php?id=R3W0ABMki1QGwd3TxPxjhA==
<img width="789" alt="image" src="https://user-images.githubusercontent.com/7253922/233871405-5b6b6acd-930b-4fee-ac78-75f35b89582a.png">

https://code.vthanhtivi.pw/getlink/jptv/ZOJu5avj3LIqoRXR9ogC0w==/playlist.m3u8
<img width="789" alt="image" src="https://user-images.githubusercontent.com/7253922/233871429-2bcb4f4b-9e6f-4d2c-b6a4-72282f5fb98e.png">
