### ISSUE TITLE
Add: Univision HD | (Colombia)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7827]
### Channel Name

Univision

### Stream URL

http://190.61.41.182:8000/play/a37m/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
That's a restream of the Mexican Univision (from the Tijuana antenna I believe ?) I think.
