### ISSUE TITLE
Broken: Defy (US)

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#7831]
### Stream Title

Defy TV WWPX DT (US)

### What happened to the stream?

Not loading

### Possible Replacement

https://scripps-defy-1-us.vizio.wurl.tv/playlist.m3u8

### Notes

Black screen and swirl circle. No longer working now. 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by ztreamhd** [comment]
I've checked Vizio's channel list and both Defy and TrueReal are no longer available through there, so I don't think these links are likely to work again, unfortunately.

**Comment by PD-TheKrazy0ne** [comment]
https://v-ca.mybtv.net/live/240.m3u8 - not HD but works

**Comment by spotanjo3** [comment]
> https://v-ny.mybtv.net/live/611.m3u8 - not HD but works

Thanks. It will do just fine. Closed Caption works fine too. Much obliged! I hope you find more channels too. Cheers!

**Comment by freearhey** [comment]
Couldn't find the original link by the title given.

**Comment by spotanjo3** [comment]
Defy link is dead.

**Comment by ztreamhd** [comment]
> Defy link is dead.

All myBTV and/or theus6tv links are not working since they are all now geoblocked and tokenized.
