### ISSUE TITLE
Add: Animax (English Sub)

### ISSUE THREAD

**Issue by Waterfall14** [iptv-org/iptv#7834]
### Channel Name

Animax (English Sub)

### Website

https://www.animax-asia.com/get-animax

### Notes

Please add Animax (English Sub) to your playlist 😊

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Duplicate #5246
