### ISSUE TITLE
Add: Aniplus (English Sub)

### ISSUE THREAD

**Issue by Waterfall14** [iptv-org/iptv#7835]
### Channel Name

Aniplus (English Sub)

### Website

https://www.aniplus-asia.com

### Notes

Please add Aniplus (English Sub) to your playlist 😊

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Duplicate #5246
