### ISSUE TITLE
Add: KFSN News Livestream (Fresno, CA)

### ISSUE THREAD

**Issue by LPhilip1999** [iptv-org/iptv#7836]
### Channel Name

KFSN News Livestream (Fresno, CA)

### Channel ID

KFSNDT1.us

### Website

https://abc30.com/watch/live/

### Notes

Need the m3u8 url please

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://content.uplynk.com/channel/ext/96195dc445894d079a91958abba8d3af/kfsn_24x7_news.m3u8
