### ISSUE TITLE
Add: V News Vietnam

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#7840]
### Channel Name

V News

### Channel ID

VNews.vn

### Stream URL

https://16371213858134.vnns.net/ttxvn_abr/vtc130121/ttxvn-360p/chunks.m3u8

### Notes

Found on the official site
Add it to vn.m3u update it

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://16371213858134.vnns.net/ttxvn_abr/playlist.m3u8
