### ISSUE TITLE
Broken: Animax Asia (Indonesian Subs)

### ISSUE THREAD

**Issue by AzeemHadzrie** [iptv-org/iptv#7842]
### Stream Title

Animax Asia (Indonesian Subs)

### What happened to the stream?

Other

### Notes

Dens tv recently dropped the channels because of contract expiration.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by hoodFX** [comment]
hi bro.. can you guide me.. how to open guide file with *.*epg.xml extension with Pot Player please?!
sorry if i ask a OOT. thanks in advanced.
