### ISSUE TITLE
Add: CM El Canal de la Musica (AR)

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#7857]
### Channel Name

CM El Canal de la Música

### Channel ID

CMElCanaldelaMusica.ar

### Website

https://www.cronica.com.ar/seccion/elcanaldelamusica/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by trancer1994** [comment]
https://g1.proy-hor.transport.edge-access.net/a09/ngrp:CM_CanaldelaMusica-100044_all/Playlist.m3u8?sense=true

**Comment by LaneSh4d0w** [comment]
Use iPhone user-agent to access it from VLC.

**Comment by freearhey** [comment]
<img width="753" alt="image" src="https://user-images.githubusercontent.com/7253922/186717560-e142164a-107d-4f56-bf24-8b6763b12897.png">

**Comment by AntiPontifex** [comment]
Already on list: please close.

**Comment by LaneSh4d0w** [comment]
> Already on list: please close.

wait before it gets merged to close it.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/ar.m3u#L214-L216
