### ISSUE TITLE
Add: A3SERIES HD

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7863]
### Channel Name

A3SERIES

### Channel ID

Atreseries.es

### Website

http://photocall.xyz/ks4g/a3m?ch=atreseries

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by MrGmaw** [comment]
https://live.atresmediainternacional.com/ATRESMEDIA/a3cine-720.m3u8

**Comment by freearhey** [comment]
Closed in favor of #9163
