### ISSUE TITLE
Replace: ViuTV

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#7864]
### Stream Title

ViuTV

### What happened to the stream?

Not loading

### Possible Replacement

https://cdn.hklive.tv/xxxx/99/index.m3u8 

### Notes

I had discovered so many related links. ViuTVSix: https://cdn.hklive.tv/xxxx/96/index.m3u8 
Update hk.m3u

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by darrencycheung** [comment]
ViuTV: http://uptv.alwaysdata.net/live/hk.php?id=08
ViuTVSix: http://uptv.alwaysdata.net/live/hk.php?id=07

**Comment by darrencycheung** [comment]
↑They're all dead

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/hk.m3u#L46-L47

**Comment by freearhey** [comment]
The broken link has been removed from the playlist.

Closed in favor #8156
