### ISSUE TITLE
Add: Cronica HD

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#7866]
### Channel Name

Conica TV

### Channel ID

CronicaTV.ar

### Stream URL

https://g4.mc-hor.transport.edge-access.net/b10/ngrp:cronicatv_video1-100044_all/Playlist.m3u8?sense=true

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
User-Agent iPhone + referer to the original website needed for this stream to work.

**Comment by AntiPontifex** [comment]
Already on list: please close.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/ar.m3u#L227-L229
