### ISSUE TITLE
Replace: Kapamilya Channel is not loading in

### ISSUE THREAD

**Issue by HansGCgamesYT** [iptv-org/iptv#7879]
### Stream Title

Kapamilya Channel

### What happened to the stream?

Not loading

### Notes

Please fix the kapamilya channel i cant watch the channel because its not loading in even tho my internet is fine please fix this issue thanks!

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/ph.m3u#L16-L17

**Comment by freearhey** [comment]
Closed in favor #8186
