### ISSUE TITLE
Add: Earthx TV

### ISSUE THREAD

**Issue by benevenstanciano** [iptv-org/iptv#7881]
### Channel Name

EarthxTV

### Website

https://earthx.org/earthxtv-schedule/

### Stream URL

https://ov.ottera.tv/live/master2300000.m3u8;session=earth_et

### Notes

There is an EPG on the website but I'm not sure how to extract it. I think it's American, but not sure either.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Rewriting the link gives me this : https://cdnapi.kaltura.com/p/3274183/sp/327418300/playManifest/entryId/1_42msnfrm/protocol/https/format/applehttp/a.m3u8

not quite sure you have the correct link.

**Comment by benevenstanciano** [comment]
Weird, the first link I posted still works for me but that might be device-specific? It's also testing on satellite in Europoe atm so I think it's pretty brand new so the link might settle at some point.

**Comment by LaneSh4d0w** [comment]
After verifying thoroughly the one you have was a chunklist basically, the one I gave is the master link.
