### ISSUE TITLE
Add: TV12 (Honduras)

### ISSUE THREAD

**Issue by ELProductions** [iptv-org/iptv#7884]
### Channel Name

TV12 (Honduras)

### Channel ID

Canal12TV.hn

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
I have no data on the existence of this channel. Has it changed name ?

**Comment by ELProductions** [comment]
I'm looking for a stream link with the screen bug that looks like this: https://logos.fandom.com/wiki/File:Canal_12_Honduras.png

**Comment by AntiPontifex** [comment]
Please close: dead issue.
