### ISSUE TITLE
Add: ICI Radio-Canada Télé (Regional Feeds)

### ISSUE THREAD

**Issue by K-Lys514** [iptv-org/iptv#7889]
### Channel Name

Ici Radio-Canada Télé

### Website

https://ici.tou.tv/en-direct/IciTele

### Notes

The Montreal feed is present but not the regionals feeds as they have different news broadcast and some have delays due to timezone, i don't know how to extract the links but you have a drop down list with all the feeds available on the link from Acadie to Terre-Neuve-Labrador.

Edit: Also the current feed available of ICI RC Télé on the playlist is stuck on "Due to broadcasting rights, this feed is not currently available" and the others feed not.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by PD-TheKrazy0ne** [comment]
https://rcavlive.akamaized.net/hls/live/704017/cancbuft/master.m3u8 - BC-Yukon
https://rcavlive.akamaized.net/hls/live/704020/cancbxft/master.m3u8 - Alberta
https://rcavlive.akamaized.net/hls/live/704019/cancbkft/master.m3u8 - Saskatchewan
https://rcavlive.akamaized.net/hls/live/704018/cancbwft/master.m3u8 - Manitoba
https://rcavlive.akamaized.net/hls/live/704022/cancblft/master.m3u8 - Ontario
https://rcavlive.akamaized.net/hls/live/664046/cancboft/master.m3u8 - Ottawa-Gatineau
https://rcavlive.akamaized.net/hls/live/664045/cancbvt/master.m3u8 - Quebec
https://rcavlive-dai.akamaized.net/hls/live/696614/cancbftprem/master.m3u8 - Montreal
https://rcavlive.akamaized.net/hls/live/704024/cancjbr/master.m3u8 - Eastern Quebec
https://rcavlive.akamaized.net/hls/live/704021/cancktm/master.m3u8 -  Mauricie–Centre-du-Québec
https://rcavlive.akamaized.net/hls/live/704016/cancksh/master.m3u8 - Estrie
https://rcavlive.akamaized.net/hls/live/704023/cancktv/master.m3u8 - Saguenay
https://rcavlive.akamaized.net/hls/live/704014/cancbaft/master.m3u8 - Acadia
https://rcavlive.akamaized.net/hls/live/704014/cancbaft/master.m3u8 - Nfld-Labrador

**Comment by freearhey** [comment]
Closed in favor #8663
