### ISSUE TITLE
Add: BEİN SPORT TUREKY 1-2-3

### ISSUE THREAD

**Issue by mamik1905** [iptv-org/iptv#7892]
### Channel Name

BEİN SPORT TUREKY 1-2-3

### Channel ID

beINSports1Turkey.tr

### Website

https://beinsports.com.tr/

### Notes

Thank you from now

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Won't be added I think, since it'll be an auto DMCA.
