### ISSUE TITLE
Add: Euronews Romania

### ISSUE THREAD

**Issue by mariano113** [iptv-org/iptv#7912]
### Channel Name

Euronews Romania

### Channel ID

EuronewsRomania.ro

### Website

https://euronews.ro/live-tv

### Stream URL

https://euronews.ro/playlist.m3u8

### Notes

Euronews in Romanian

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by ztreamhd** [comment]
YouTube links: https://www.youtube.com/c/euronewsro/live or https://www.youtube.com/watch?v=tdwXKd9Gqb8
So, using the repository's query-streamlink tool, the URL would look like this: https://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/euronewsro/live or https://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/watch?v=tdwXKd9Gqb8

`The 'live' one does not work properly on fullspeed.tv but it does on other query-streamlink tools. Feel free to pick whatever works best.`

**Comment by Alstruit** [comment]
Fullspeed.tv should be a bit more stable now.
