### ISSUE TITLE
Replace: Disney Channel España 

### ISSUE THREAD

**Issue by omaromarver** [iptv-org/iptv#7916]
### Stream Title

Disney Channel España

### Broken Link

http://5.255.90.184:2004/play/a006/index.m3u8 

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/us.m3u#L1870-L1871
