### ISSUE TITLE
Replace: Kuriakos Cine, Kids, TV Portugal

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#7921]
### Stream Title

Kuriakos Cine (1080p) [Not 24/7] 

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/pt.m3u#L8-L9
