### ISSUE TITLE
Broken: RTP Internacional PORTUGAL

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#7923]
### Stream Title

RTP Internacional 

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by ztreamhd** [comment]
The M3U8 link does not work 24/7. I don't know what kind of link is used here but the one on their page is this one: https://streaming-live.rtp.pt/liverepeater/smil:rtpi.smil/chunklist_b1290000_slpt.m3u8 (adaptive: https://streaming-live.rtp.pt/liverepeater/smil:rtpi.smil/playlist.m3u8)

**Comment by spotanjo3** [comment]
Not working.

**Comment by spotanjo3** [comment]
Which player ? I tried VLC Player.. Got an error.

**Comment by LaneSh4d0w** [comment]
![image](https://user-images.githubusercontent.com/30985701/182903761-6fd34593-f3ca-4631-8033-976803369af1.png)

You need a user-agent for it to work, a browser one.

**Comment by spotanjo3** [comment]
I don't want to use a user-agent a browser one. I prefer TELEVIZO ANDROID TV along with VLC Player.

**Comment by LaneSh4d0w** [comment]
> I don't want to use a user-agent a browser one. I prefer TELEVIZO ANDROID TV along with VLC Player.

With these official RTP links, you have no choice but to add an user-agent for it to work. VLC supports the user-agent changes.

**Comment by spotanjo3** [comment]
How ? What option do I see for VLC, please ?

**Comment by spotanjo3** [comment]
Please ? Thanks.

**Comment by Phawizzy** [comment]
Stop all

**Comment by LaneSh4d0w** [comment]
> Please ? Thanks.

Using the pt.m3u or the basic index files should be enough as it carries out the user agent.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/pt.m3u#L54-L56
