### ISSUE TITLE
Broken: WPHL 17.1

### ISSUE THREAD

**Issue by SocksAlots** [iptv-org/iptv#7931]
### Stream Title

WPHL-DT1 (PHL17) (720p)

### What happened to the stream?

Not loading

### Notes

It was working yesterday.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by MapGuy11** [comment]
#7955
