### ISSUE TITLE
Broken: Rewind TV Stream

### ISSUE THREAD

**Issue by gameshowrecaps** [iptv-org/iptv#7932]
### Stream Title

WPIX-DT4 (Rewind TV) (480p)

### What happened to the stream?

Not loading

### Possible Replacement

None afaik

### Notes

This also includes the entire localbtv us.m3u file.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by spotanjo3** [comment]
Yeah, its dead. Just swirl as well.
