### ISSUE TITLE
Broken: Star TV

### ISSUE THREAD

**Issue by kendallugurlu** [iptv-org/iptv#7941]
### Stream Title

Star TV (720p) [Not 24/7]

### What happened to the stream?

Not loading

### Possible Replacement

https://dogus.daioncdn.net/startv/startv_720p.m3u8?sid=4kx65o7sy17g&app=a20ac41e-bdc3-4aa1-934d-26b484480ac9&ce=3

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/tr.m3u#L262-L263
