### ISSUE TITLE
Add: Halk TV (TR)

### ISSUE THREAD

**Issue by kendallugurlu** [iptv-org/iptv#7942]
### Channel Name

Halk TV

### Channel ID

HalkTV.tr

### Website

https://halktv.com.tr/

### Stream URL

https://halktv-live.ercdn.net/halktv/halktv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/e30156eaa294ec32152101b0a8e1d35b92dbf67b/streams/tr.m3u#L109-L111
