### ISSUE TITLE
Broken: MeTV (WCTV2) (480p) USA

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#7946]
### Stream Title

MeTV 

### Broken Link

https://5e6cea03e25b6.streamlock.net/live/WCTVDT2.stream/playlist.m3u8 

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Problem is known.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/us.m3u#L1333-L1334

**Comment by LaneSh4d0w** [comment]
thing is this link either needs a token, either is geolocked, either itdoesn't work.
