### ISSUE TITLE
Broken: LAFF  (WPPX-DT5) (432p) USA

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#7947]
### Stream Title

Laff

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Problem is known.

**Comment by MapGuy11** [comment]
#7955
