### ISSUE TITLE
grouped by country is wrong

### ISSUE THREAD

**Issue by yqll** [iptv-org/iptv#795]
Both Hong Kong, Macao and Taiwan belong to China，Please correct them. Thank you

**Comment by freearhey** [comment]
The list of countries is based on [ISO 3166](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) standard and includes not only countries but also "...dependent territories, special areas of geographical interest, and their principal subdivisions (e.g., provinces or states)" (Source: https://en.wikipedia.org/wiki/ISO_3166)
