### ISSUE TITLE
Broken: Antenna TV (480p) WPHL-DT2 USA

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#7951]
### Stream Title

Antenna TV

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Problem is known.

**Comment by MapGuy11** [comment]
#7955

**Comment by spotanjo3** [comment]
What does that mean, may I ask ? ^_^

**Comment by MapGuy11** [comment]
> What does that mean, may I ask ? ^_^

I quoted the fix and closed the issue because it was fixed.
