### ISSUE TITLE
Broken: WCAU 10.1

### ISSUE THREAD

**Issue by SocksAlots** [iptv-org/iptv#7952]
### Stream Title

WCAU-DT1 (NBC 10) (1080p)

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Problem is known.

**Comment by MapGuy11** [comment]
#7955
