### ISSUE TITLE
Replace: WBAL 11.1

### ISSUE THREAD

**Issue by SocksAlots** [iptv-org/iptv#7953]
### Stream Title

NBC Baltimore MD (WBAL-DT1) (720p) [Not 24/7]

### What happened to the stream?

Constantly interrupts/lagging

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Problem is known.

**Comment by freearhey** [comment]
On my side this stream works perfectly.
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/us.m3u#L1323-L1324
