### ISSUE TITLE
Add: Ñanduti TV (Paraguay) py.m3u

### ISSUE THREAD

**Issue by fabiandv** [iptv-org/iptv#7957]
### Channel Name

Ñanduti TV

### Channel ID

ÑandutiTV.py

### Website

https://nanduti.com.py/nanduti-tv/

### Stream URL

https://tvdatta.com:3839/live/nandutitvlive.m3u8

### Notes

add into py.m3u

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/d94d3b49ba64c9e3985bf40bd5c5b9027f36b5bb/streams/py.m3u#L70-L71
