### ISSUE TITLE
Channel missing in canada

### ISSUE THREAD

**Issue by losemyminds** [iptv-org/iptv#796]
Can you add the channel missing from quebec,canada like ..

Rds
Rds2
Tva 
Tvasports1-2
CanalD
Addicktv
V
Radio canada
Super ecran

Thanks

**Comment by themak1985** [comment]
https://ssl.ustreamix.com/ch?embed=true has a lot of your channels - but I can't seem to get an hls link

**Comment by losemyminds** [comment]
Uh man do you want me to find you the  channel list from Canada,Quebec ?!?!

From the VIDEOTRON,the cable  service here in quebec


Or i could gave you my m3u Url code , i was use it for 1 year but,  he dont
work no more since 2 weeks ago...

Mayber you could do something you with that .....

Lot oF series,Vod  on this link ,holla back man thanks

Le mer. 11 déc. 2019 22 h 29, themak1985 <notifications@github.com> a
écrit :

**Comment by freearhey** [comment]
@themak1985 I think all the broadcasts on this site are geo-blocked. Personally, I couldn't run any of them. I only see "This channel is not available in your country" and a lot of ads.

**Comment by losemyminds** [comment]
Yeah i know ,, its Quebec here,so ma restriction for fuck alll,first time i
call my iptv provider he told Me same things then you,then was geo blocked..

Tha te s why we need  to use s good vpn ...

**Comment by freearhey** [comment]
@losemyminds The last message wasn't addressed to you.

**Comment by RetroGamer2020** [comment]
Can u add all Canada Channels thanks

**Comment by freearhey** [comment]
@RetroGamer2020 No, we can't. This repository contains only publicly available broadcasts.

**Comment by freearhey** [comment]
- [ ] [RDS](https://www.rds.ca/)
- [ ] [RDS 2](https://www.rds2.ca/)
- [ ] [TVA](https://video.tva.ca/)
- [ ] [TVA Sports](https://www.tvasports.ca/)
- [ ] [TVA Sports 2](https://www.tvasports.ca/)
- [ ] [Canal D](https://www.canald.com/)
- [ ] [Addik TV](http://www.addik.tv/)
- [ ] [V](https://noovo.ca/v)
- [x] [Radio-Canada](https://ici.radio-canada.ca/)
https://github.com/iptv-org/iptv/blob/5ba1b97d5c442c3a86d41280ec8de39384b68ba5/channels/ca.m3u#L24-L25
- [ ] [Super Écran](https://www.crave.ca/en/super-ecran)

**Comment by Sphinxroot** [comment]
RDS RDS 2 (TVA Sport 1-2)  Canal D ,Addik TV ,Super Ecran 1,2,3,4  all pay channel  all free to view are on my git

**Comment by edw18** [comment]
Ctv news channel with audio please

**Comment by edw18** [comment]
ABC news from Australia please

**Comment by freearhey** [comment]
Closed in favor #1941

**Comment by losemyminds** [comment]
Sphinxroot 

 Sa va big ?!? Je suis pas trop habituer avec ici ,mais peu tu m'envoyer un lien de t chaînes quebecoise STP!?!  
Ciao a plus dude

**Comment by misterdesigns** [comment]
im searchin quebec list m3u .. rds .. tva sport ... and everything ... just4ashow  t'as trouver de quoi de pas pire ???

**Comment by misterdesigns** [comment]
@Sphinxroot @Just4dashow  found some quebec m3u list ?
