### ISSUE TITLE
Add: Venus Media (Paraguay) py.m3u

### ISSUE THREAD

**Issue by fabiandv** [iptv-org/iptv#7962]
### Channel Name

Venus Media

### Channel ID

VenusMedia.py

### Website

https://www.venus.com.py/

### Stream URL

https://rds3gen.desdeparaguay.net/venusmedia/venusmedia/chunklist_w1962805979.m3u8?k=efa83de3f8c0f98747b277368901e8c4cc7fe3da3b8bd12b2d2f6a882f3dd72f&exp=1659668575

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Needs a streamlink process to make it work.

**Comment by fabiandv** [comment]
> Needs a streamlink process to make it work.

This link work use that

https://rds3gen.desdeparaguay.net/venusmedia/venusmedia/chunklist_w1962805979.m3u8?k=efa83de3f8c0f98747b277368901e8c4cc7fe3da3b8bd12b2d2f6a882f3dd72f&exp=1659668575

**Comment by LaneSh4d0w** [comment]
It is tokened, so it is made to expire after some time.

**Comment by fabiandv** [comment]
2 days and the streamlink still working

**Comment by robocopz** [comment]
https://rds3gen.desdeparaguay.net/venusmedia/venusmedia/.m3u8
