### ISSUE TITLE
Broken: WGTV

### ISSUE THREAD

**Issue by mrd176** [iptv-org/iptv#7977]
### Stream Title

PBS Athens GA (WGTV) (1080p)

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by MapGuy11** [comment]
Most PBS stations went to DRM which means they can be only accessed by their respective apps.
