### ISSUE TITLE
Replace: MBC 2

### ISSUE THREAD

**Issue by HadyTheDiabMan** [iptv-org/iptv#7979]
### Stream Title

MBC 2

### What happened to the stream?

Not loading

### Notes

This is the MBC 2 from the United Arab Emirates. 
I have found other sites with working streams for MBC 2, however I wasn't able to find usable m3u8 links within those sites. I can link these sites if needed.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/ae.m3u#L82-L83

**Comment by freearhey** [comment]
The broken link has been removed from the playlist.

Closed in favor #8155
