### ISSUE TITLE
Add: PBS Arkansas

### ISSUE THREAD

**Issue by blackhern** [iptv-org/iptv#7989]
### Channel Name

Arkansas PBS

### Channel ID

KETSDT1.us

### Website

https://www.myarkansaspbs.org/watch

### Stream URL

https://ketsdt.lls.pbs.org/out/v1/03c094dbd7874a4a8c3fe9fb10081bdb/index_3.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by MapGuy11** [comment]
https://ketsdt.lls.pbs.org/out/v1/03c094dbd7874a4a8c3fe9fb10081bdb/index.m3u8

**Comment by PD-TheKrazy0ne** [comment]
> https://ketsdt.lls.pbs.org/out/v1/03c094dbd7874a4a8c3fe9fb10081bdb/index.m3u8

GEO LOCKED I Think... Doesnt work for me in Canada, Works with US IP on VPN though.
