### ISSUE TITLE
Add: WSTO 

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#7993]
### Channel Name

WSTO

### Website

https://wsto.tv/

### Stream URL

https://5d80890572342.streamlock.net:1936/live/wstoLive/chunklist_w459911506.m3u8

### Notes

This is a valid American PEG station from Stoughton, WI; as such, it is not listed in your formal list.
I hope you accept it.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by TKList** [comment]
https://5d80890572342.streamlock.net:1936/live/wstoLive/playlist.m3u8
