### ISSUE TITLE
Add: Legislative Assembly of British Columbia

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#7995]
### Channel Name

Legislative Assembly of British Columbia

### Channel ID

LegislativeAssemblyofBritishColumbia.ca

### Website

https://www.leg.bc.ca/

### Stream URL

https://hbsprim-1be2a.kxcdn.com/legbcca-prim-chamber-httpo/ChamberP.smil/chunklist_b1296000_sleng.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by TKList** [comment]
https://hbsprim-1be2a.kxcdn.com/legbcca-prim-chamber-httpo/ChamberP.smil/playlist.m3u8
