### ISSUE TITLE
Broken: NBC NEWS NOW (1080p) USA

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#7997]
### Stream Title

NBC NEWS NOW

### What happened to the stream?

Constantly interrupts/lagging

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Couldn't find the original link by the title given.
