### ISSUE TITLE
Broken: WXTV-DT1 (Univision 41) [USA] 

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#7999]
### Stream Title

WXTV-DT1 (Univision 41)

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/us_localbtv.m3u#L257-L259
