### ISSUE TITLE
Broken: times now 

### ISSUE THREAD

**Issue by sonickap1399** [iptv-org/iptv#8002]
### Stream Title

times now 

### What happened to the stream?

Not loading

### Notes

the indian channel  times nows  and republic does not work  can you fix it please  

thanks 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Couldn't find the original link by the title provided.
