### ISSUE TITLE
Add: Nunavut Legislative Assembly

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8005]
### Channel Name

Nunavut Legislative Assembly

### Channel ID

LegislativeAssemblyTVNunavut.ca 	

### Website

https://www.assembly.nu.ca/

### Stream URL

https://temp7.isilive.ca/live/nunavut/live-flo/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://temp6.isilive.ca/live/nunavut/live-flo/index.m3u8
