### ISSUE TITLE
Add: Nova Scotia Legislature

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8006]
### Channel Name

Nova Scotia Legislature

### Channel ID

LegislativeTV.ca

### Website

https://nslegislature.ca/

### Stream URL

https://youtu.be/NgNaLVlzJSM?t=613

### Notes

Again, not listed; hope you include it.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Only when online : http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/NovaScotiaLegislature/live
