### ISSUE TITLE
Add: KTOO 360TV 3 (FNX)

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8007]
### Channel Name

KTOO DT3

### Channel ID

KTOODT3.us

### Website

https://www.ktoo.org/360TV/

### Stream URL

https://cdn3.wowza.com/5/ODB6NmF5K3l4T1h5/persis/2147483647_360tv_247/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://cdn3.wowza.com/5/ODB6NmF5K3l4T1h5/persis/2147483647_360tv_247/playlist.m3u8
