### ISSUE TITLE
Add: Star Chinese Channel Taiwan

### ISSUE THREAD

**Issue by AzeemHadzrie** [iptv-org/iptv#8012]
### Channel Name

Star Chinese Channel

### Channel ID

StarChineseChannel.hk

### Website

dngtw.tw/SCC

### Stream URL

http://61.219.170.95:18522/http/192.168.1.9:8081/hls/62/804/ch05.m3u8

### Notes

Chinese channel known as SCC owned by DNG Taiwan.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/hk.m3u#L51-L52
