### ISSUE TITLE
Add: Mobile County Public Schools TV Network (MCPSS)

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8018]
### Channel Name

Mobile County Public Schools TV Network

### Channel ID

MCPSSTV.us

### Website

https://www.mcpss.com/?DivisionID=2140&DepartmentID=1969&ToggleSideNav=ShowAll

### Stream URL

https://5b200f5268ceb.streamlock.net/MCPSS/MCPSS247.smil/chunklist_w1482206288_b946000.m3u8

### Notes

PEG Channel from Mobile, AL

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fotvnetwork** [comment]
https://5b200f5268ceb.streamlock.net/MCPSS/MCPSS247.smil/playlist.m3u8
