### ISSUE TITLE
Add: Celestial Channel Tagalize or eng sub

### ISSUE THREAD

**Issue by nae8ean** [iptv-org/iptv#8022]
### Channel Name

Celestial Channel Tagalize 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Could you provide the official name of the channel or a link to the website?

**Comment by AntiPontifex** [comment]
I'm not entirely sure, but I think the requester is asking for this channel:

https://cignal.tv/

**Comment by nae8ean** [comment]
here is the link
https://www.cmpinoy.com.ph/
