### ISSUE TITLE
Add: Fayetteville Public Access Television

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8030]
### Channel Name

Fayetteville Public Access Television

### Channel ID

FPTV.us

### Website

https://faypublic.tv/

### Stream URL

https://youtu.be/6oZhSdk2Mq4

### Notes

From Fayetteville, AR when available: PEG Channel

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fotvnetwork** [comment]
https://www.youtube.com/c/FayettevillePublicTelevision/live

**Comment by Alstruit** [comment]
Done 4b396b663baaeb1d4fef8e9ca8fb9c6ed25c4cca.
