### ISSUE TITLE
Add: Fayetteville Government Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8031]
### Channel Name

Fayetteville Government Channel

### Website

https://www.fayetteville-ar.gov/510/Media-Services-PEG-TV

### Stream URL

https://youtu.be/yg2B7Nzryek

### Notes

From Fayetteville, AR when available; PEG channel

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fotvnetwork** [comment]
https://www.youtube.com/c/FayettevilleArkansas/live

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/FayettevilleArkansas/live

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/FayettevilleArkansas/live

> Nothing to do for https://www.youtube.com/c/FayettevilleArkansas/live, reason being Streamlink couldn't process https://www.youtube.com/c/FayettevilleArkansas/live, because of a Plugin error. Reason is as follows: Unable to open URL: https://www.youtube.com/c/FayettevilleArkansas/live (429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.youtube.com/c/FayettevilleArkansas/live&q=EgRTijckGLSc9ZcGIhAm7AEH7BKPwTGXXEpFe4NnMgFy)

https://www.youtube.com/c/FayettevilleArkansas/live
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/7253922/185236562-f9efa8a3-e92c-4bf7-9dcf-81ad0fe79712.png">

**Comment by LaneSh4d0w** [comment]
https://q-s-l4n3sh4d0w.onrender.com/iptv-query?streaming-ip=https://www.youtube.com/c/FayettevilleArkansas/live ?
