### ISSUE TITLE
Add: USA Today (The Roku Channel)

### ISSUE THREAD

**Issue by LPhilip1999** [iptv-org/iptv#8041]
### Channel Name

USA Today (The Roku Channel)

### Channel ID

USAToday.us

### Notes

Need the m3u8 url please

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fotvnetwork** [comment]
Geo-blocked
https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00731-gannettcoinc-usatodaynews-rokuus/playlist.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/13d2f470b7e5b647c0d24d4b6897c651d4b52971/streams/us_tubi.m3u#L28-L29
https://github.com/iptv-org/iptv/blob/13d2f470b7e5b647c0d24d4b6897c651d4b52971/streams/us_stirr.m3u#L290-L291
https://github.com/iptv-org/iptv/blob/13d2f470b7e5b647c0d24d4b6897c651d4b52971/streams/us_xumo.m3u#L202-L203
