### ISSUE TITLE
Add: USA Today SportsWire (The Roku Channel)

### ISSUE THREAD

**Issue by LPhilip1999** [iptv-org/iptv#8042]
### Channel Name

USA Today SportsWire (The Roku Channel)

### Channel ID

USATodaySportswire.us

### Notes

Need the m3u8 url please

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by TKList** [comment]
Not on: https://therokuchannel.roku.com/search/usa-today
It is on: 
https://tubitv.com/live/613229/usa-today-sportswire
https://watch.plex.tv/live-tv/channel/usa-today-sportswire

**Comment by LPhilip1999** [comment]
So what is the m3u8 link for USA Today SportsWire (Tubi)?

**Comment by TKList** [comment]
https://live-news-manifest.tubi.video/live-news-manifest/csm/extlive/tubiprd01,Sportswire.m3u8
