### ISSUE TITLE
Broken: AXN East Asia (Indonesian subtitle)

### ISSUE THREAD

**Issue by AzeemHadzrie** [iptv-org/iptv#8046]
### Stream Title

AXN East Asia (Indonesian subtitle)

### What happened to the stream?

Other

### Possible Replacement

http://203.77.246.50:5000/udp/239.1.2.142:5000

### Notes

Dens tv removed 2 KCGM channels last month, then GEM and ONE in the coming months,

The link here in the Possible Replacement section is used as the UseeTV version.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/1dac5750caf728377c40cf13186b548c9584c135/streams/us.m3u#L1751-L1752

**Comment by skykhmer** [comment]
http://210.210.155.37/dr9445/h/h141/index.m3u8 
http://203.77.246.50:5000/udp/239.1.2.142:5000
Two are the link not working
