### ISSUE TITLE
Add: TV4 Bullhead City, AZ

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8047]
### Channel Name

TV4 Bullhead City, AZ

### Website

https://www.bullheadcity.com/government/tv4

### Stream URL

https://cdn3.wowza.com/5/UWpORHhLSEs5SkJs/bullheadcity/G0860_001/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://cdn3.wowza.com/5/UWpORHhLSEs5SkJs/bullheadcity/G0860_001/playlist.m3u8
