### ISSUE TITLE
Add: 11 Florence

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8048]
### Channel Name

11 Florence

### Channel ID

TownofFlorenceChannel11.us

### Website

https://www.florenceaz.gov/watch-live/

### Stream URL

https://youtu.be/Ew0vDJlTHOU

### Notes

From Florence, AZ

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fotvnetwork** [comment]
https://www.youtube.com/c/TownOfFlorence/live
