### ISSUE TITLE
Add: LHCAZTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8049]
### Channel Name

LHCAZTV

### Website

https://www.lhcaz.gov/channel-4

### Stream URL

https://cdn3.wowza.com/5/cHYzekYzM2kvTVFH/lakehavasucity/G0643_003/chunklist.m3u8

### Notes

From Lake Havasu, AZ

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://cdn3.wowza.com/5/cHYzekYzM2kvTVFH/lakehavasucity/G0643_003/playlist.m3u8
