### ISSUE TITLE
Add: CHCH

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8050]
### Channel Name

CHCH

### Channel ID

CHCHDT.ca

### Website

https://www.chch.com/live/

### Stream URL

https://flowcaster1-sh.cdn.clearcable.net/CHCH-OTT/smil:CHCH-OTT.smil/chunklist_w778337051_b3160000_sleng_tkaWltYWUwVUMyYWVuZHRpbWU9MTY2MDQ5MDYyMCZpaW1hZTBVQzJhaGFzaD1oS0lmOEQwNzlxNWhLLU43OW8wM1BNZkd0LWZBRG5reE9MVmZySTRua2w0PQ==.m3u8

### Notes

From Hamilton, ON

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://flowcaster1-sh.cdn.clearcable.net/CHCH-OTT/smil:CHCH-OTT.smil/playlist.m3u8 GEO

**Comment by freearhey** [comment]
<img width="758" alt="image" src="https://user-images.githubusercontent.com/7253922/185461833-fe06b8f4-835d-4c92-95dd-571d4ee2ccf9.png">
