### ISSUE TITLE
Blacklist : NHK Channels

### ISSUE THREAD

**Issue by LaneSh4d0w** [iptv-org/iptv#8052]
### Channel Name

NHK

Irdeto began flagging our GH links as an answer.

Lumen DB entry can be found here : https://lumendatabase.org/notices/27261712

I suggest we should blacklist all channels to prevent any issues.

**Comment by freearhey** [comment]
If rights holders want us to remove any content, they can send their request directly to us through this [form](https://github.com/iptv-org/iptv/issues/new?assignees=freearhey&labels=%E2%9D%8C+removal+request&template=--removal-request.yml&title=Remove%3A+). And if the request is approved, we will definitely put the channel on the block list.
