### ISSUE TITLE
Fix: After adding via PR, Congreso TV no longer available in the playlist

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#8054]
### Describe your issue

Before add Congreso TV via PR (#8014), the stream no longer available in pe.m3u (or other playlist) since daily update (#8051). I noticed that the bot autoremoved the stream with its id despite it does not carry some duplicate and is its title have [Not 24/7] tag. The stream is online.

**Comment by freearhey** [comment]
Thank you for pointing that out! 

Fixed in https://github.com/iptv-org/iptv/commit/61cac20ea03ad3ad716a72f71fd3e509ebbae7af
