### ISSUE TITLE
Add: PHXTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8062]
### Channel Name

PHXTV

### Website

https://www.phoenix.gov/phxtv

### Stream URL

https://cdn3.wowza.com/5/bGZUOHp2TnhudnM2/phoenix/G1498_002/chunklist.m3u8

### Notes

From Phoenix, AZ

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Duplicate #7129
