### ISSUE TITLE
Add: MeTV Plus USA

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#8065]
### Channel Name

MeTV Plus

### Website

https://www.metv.com/metvplus

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Could you specify the call sign of the desired channel?

https://iptv-org.github.io/?q=MeTV%20Plus

**Comment by LaneSh4d0w** [comment]
I'll tend to say that most of the times when they're referring to "USA", it's big cities like NY. We'll say it's WJLP-DT8

**Comment by princo17** [comment]
dead links all

**Comment by spotanjo3** [comment]
MeTV Plus USA please ?
