### ISSUE TITLE
Add: Raj News Malayalam 

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#8081]
### Channel Name

Raj News Malayalam

### Channel ID

RajNewsMalayalam.in

### Website

rajtv.in

### Stream URL

https://www.youtube.com/watch?v=Q8sCClSHwkQ

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCfPag4Qmnif6fw25HEIqF6w/live
