### ISSUE TITLE
Add: edTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8087]
### Channel Name

edTV

### Website

https://www.azwestern.edu/communications-and-marketing/television-services

### Stream URL

https://arizonawesterncol.secure.footprint.net/egress/bhandler/arizonawesterncol/streamb/chunklist_b2368512.m3u8

### Notes

From Yuma, AZ

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://arizonawesterncol.secure.footprint.net/egress/bhandler/arizonawesterncol/streamb/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
https://arizonawesterncol.secure.footprint.net/egress/bhandler/arizonawesterncol/streama/playlist.m3u8 too it seems
