### ISSUE TITLE
Add: Canal de Gobierno

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8088]
### Channel Name

Canal de Gobierno

### Channel ID

CanaldeGobierno.gt

### Website

https://guatemala.gob.gt/canal-de-gobierno/

### Stream URL

https://youtu.be/dy1Lw1quttQ

### Notes

From Guatemala City, Guatemala

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/user/GobiernodeGuatemala/live

**Comment by LaneSh4d0w** [comment]
ID : GobiernoTV.gt
