### ISSUE TITLE
Can I contribute Malaysia channel here ? 

### ISSUE THREAD

**Issue by chin8205** [iptv-org/iptv#809]

**Comment by freearhey** [comment]
Of course you can! Here's a guide on how to do this: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#add-channel

**Comment by chin8205** [comment]
How do I contribute in to Country list ? I can't found the file.

**Comment by chin8205** [comment]
I have updated channels\my.m3u,  but seem like still not update to the master...

**Comment by freearhey** [comment]
In order for the changes to reach the master branch, you just need to make a Pull Request. Here is a step-by-step instruction on how to do this - https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
