### ISSUE TITLE
Add: Knoxville Community Media

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8094]
### Channel Name

Knoxville Community Media

### Website

https://www.ctvknox.org/

### Stream URL

https://knoxville-tn.secure.footprint.net:443/egress/bhandler/knoxvilletn/streama/chunks.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Just in case : https://knoxville-tn.secure.footprint.net/egress/bhandler/knoxvilletn/streama/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
Knoxville, TN
