### ISSUE TITLE
Add: Court TV | [Website M3U8 Link] (US)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8098]
### Channel Name

Court TV

### Website

https://www.courttv.com/

### Stream URL

https://content.uplynk.com/channel/6c0bd0f94b1d4526a98676e9699a10ef.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/d94d3b49ba64c9e3985bf40bd5c5b9027f36b5bb/streams/us.m3u#L368-L369

**Comment by R4IN2007** [comment]
https://cdn-katz-networks-01.vos360.video/Content/HLS/Live/channel%28courttv%29/index.m3u8
