### ISSUE TITLE
Can i use this on KODI player on android

### ISSUE THREAD

**Issue by sajidmanzoor10p** [iptv-org/iptv#811]
Hello,
Can i use this with KODI player on android device. If yes, please tell me how can I do this. Also  confirm if there is any other android Ad free app on which I can use this repo for viewing TV

**Comment by themak1985** [comment]
@sajidmanzoor10p There are guides if you google "kodi iptv setup".  this works with any app that will use a playlist - use the link you want on this [repo homepage. ](https://github.com/iptv-org/iptv/)

TiviMate, PerfectPlayer, IPTV Extreme, XCIPTV Player are just a few - even VLC works.
