### ISSUE TITLE
Add: AT5, Netherlands (local channel)

### ISSUE THREAD

**Issue by K9-711** [iptv-org/iptv#8110]
### Channel Name

AT5

### Channel ID

AT5.nl

### Website

https://www.at5.nl/media

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://takeoff.jetstre.am/?account=atvijf&file=live&type=live&service=wowza&protocol=https&output=playlist.m3u8
