### ISSUE TITLE
Requesting Congo channels (Democratic Republic of Congo)

### ISSUE THREAD

**Issue by bermufine** [iptv-org/iptv#812]
Hello,
I am requesting an Congo channels, by the name of :
digital_congo
Heritage tv
Nyota tv
RTVS1
RTNC2
Antenne A
Rtg@.
Please Feel free To send me a working link in my gmail: Congomonpays243@gmail.com 

Thank you, and have a wonderful day.

Good luck on future upgrades and keep up the work.

Also, if you can, please add HD streams of Tele50
B-ONE
RTNC
Mwangaza
Don't Forget SPORTS channels like Bein Sport HD from 1 To 12

Thank you once again.

**Comment by freearhey** [comment]
**Kenyan:**
- [ ] [Heritage TV](https://www.lyngsat.com/tvchannels/ke/Heritage-TV.html)

**Congo:**
- [ ] [Digital Congo TV](https://www.digitalcongo.net/)
- [ ] [Nyota Radio Television](http://www.nyota.net/)
- [ ] [RTVS1](https://www.facebook.com/rtvs1/)
- [ ] [RTNC2](https://fr.wikipedia.org/wiki/RTNC2)
- [ ] [Antenne A](https://fr.wikipedia.org/wiki/Antenne_A)
- [ ] [RTG@](http://groupelavenir-rdc.info/index.php)

**Comment by Sphinxroot** [comment]
Congo Planète TV
http://www.centraltv.fr/wp-content/uploads/congo-planete-tv_logo.jpg
https://radio.congoplanet.com/Congo_Planet_TV.sdp/Congo_Planet_TV/playlist.m3u8
https://radio.congoplanet.com/Congo_Planet_TV.sdp/Congo_Planet_TV/playlist_480.m3u8
https://radio.congoplanet.com/Congo_Planet_TV.sdp/Congo_Planet_TV/playlist_720.m3u8
https://radio.congoplanet.com/Congo_Planet_TV.sdp/Congo_Planet_TV/playlist_1080.m3u8

Congo Planète TV2
http://www.centraltv.fr/wp-content/uploads/congo-planete-tv2_logo.jpg
https://radio.congoplanet.com/Congo_Planet_TV_Pop.sdp/Congo_Planet_TV_Pop/playlist.m3u8
https://radio.congoplanet.com/Congo_Planet_TV_Pop.sdp/Congo_Planet_TV_Pop/playlist_480.m3u8
https://radio.congoplanet.com/Congo_Planet_TV_Pop.sdp/Congo_Planet_TV_Pop/playlist_720.m3u8
https://radio.congoplanet.com/Congo_Planet_TV_Pop.sdp/Congo_Planet_TV_Pop/playlist_1080.m3u8

**Comment by bermufine** [comment]
Thanks a lot brother

But this one I have it already so please,
Can you try your best to stream another Channels?

Like:

👉Digital Congo
👉Héritage TV
👉Pstv
👉Rtga
👉Tele50
👉Rtnc2
👉B-one

please some one try to give each m3u8 link for each channel but did work
only for 2 days

I created android app so I wanna put all those channels in

**Comment by freearhey** [comment]
Closed in favor #1958 and #1959

**Comment by jaromir1978** [comment]
V D. Kongu zapli geoblokaci taky v senegalu a mozambiku je potřeba VPN v dané zemi,ale nikdo zatím neudělal VPN afrických zemí zdarma co znám je Bebra VPN.Taky nikdo ještě neudělal VPN oceánie aby jela nová caledonie 1.Všechy evropské země jdou odblokovat i nový zéland a austrálie přes VPN Expresen nebo Nord.

**Comment by bermufine** [comment]
Ok but keep trying maybe will be open

**Comment by jaromir1978** [comment]
Na Tv v mobilu je nejlepší aplikace OneTv z obchodu play jede v ní asi 100000 tisíc televizí z celého světa včetně konga dají se do ní přidat m3u playlisty a má hledáček podle státu nebo jména televize je to nejlepší aplikace na live televize co znám.

**Comment by bermufine** [comment]
Ok thanks
Let me search for OneTv in PlayStore as you say

But me I do have my App PlayStore BERO TV that is why I'm looking for more
m3u8 links to add channels from Africa and Europa French or English

**Comment by jaromir1978** [comment]
Výborná jedou televize z konga i státní RCTN

**Comment by jaromir1978** [comment]
Výborná jedou všechny tv z Konga

**Comment by jaromir1978** [comment]
https://i.mjh.nz/au/Perth/raw-tv.m3u8

**Comment by jaromir1978** [comment]
Austrálie všechny tv potřeba Austrálie vpn

**Comment by jaromir1978** [comment]
Nový zéland všechny tv potřeba nový zéland VPN
