### ISSUE TITLE
Add: Contra Costa College TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8123]
### Channel ID

ContraCostaTV.us

### Stream URL

https://reflect-contra-costa.cablecast.tv/live-7/live/WIFI-696k-360p/WIFI-696k-360p.m3u8

### Notes

From Contra Costa County, CA

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Sorry, but without an ID we can't add the channel to the playlist. 

You can leave your request to add the channel to the database [here](https://github.com/iptv-org/database/issues) or add it yourself via [pull request](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#how-to-add-a-channel-to-the-database-or-edit-its-description).
