### ISSUE TITLE
Add: Kern County Television

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8125]
### Channel ID

KernCountyTV.us

### Stream URL

https://cdn3.wowza.com/5/dk84U1p2UUdoMGxT/kern/G0169_003/chunklist.m3u8

### Notes

From Bakersfield, CA

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Sorry, but without an ID we can't add the channel to the playlist. 

You can leave your request to add the channel to the database [here](https://github.com/iptv-org/database/issues) or add it yourself via [pull request](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#how-to-add-a-channel-to-the-database-or-edit-its-description).

**Comment by LaneSh4d0w** [comment]
https://cdn3.wowza.com/5/dk84U1p2UUdoMGxT/kern/G0169_003/playlist.m3u8
