### ISSUE TITLE
Add: ABC 4 KOMO (KOMO NEWS) 180p

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8134]
### Channel ID

KOMODT1.us

### Stream URL

https://content.uplynk.com/d7ae2696e3c54d25a099dc4c0600ee60/c.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by MapGuy11** [comment]
https://content.uplynk.com/d7ae2696e3c54d25a099dc4c0600ee60.m3u8 (720p)

**Comment by LaneSh4d0w** [comment]
The only "Live" source I have from KOMO is their radio at https://live.wostreaming.net/manifest/sinclair-komoamaac-hlsc2.m3u8

**Comment by LaneSh4d0w** [comment]
see https://livevideostatus.sinclairstoryline.com/status/KOMO with referer https://komonews.com/ to know if their news cast is live or not
