### ISSUE TITLE
Questions on channels update

### ISSUE THREAD

**Issue by SileC** [iptv-org/iptv#814]
1. Is there a list of categories to be used for channels? (Music, News.....) This might help for sorting
2. For channel icon is only imgur accepted or any other link?
3. Are GEO (or server specific) channels allowed? How should they be marked? ..."Country name" + GEO?

**Comment by freearhey** [comment]
1. List of currently supported categories - https://github.com/iptv-org/iptv#playlists-by-category
2. There are no restrictions on the source of icons at this time.
3. At the moment we do not add geo-blocked channels to playlists as they are too difficult to maintain. More on that here: https://github.com/iptv-org/iptv/issues/379#issuecomment-540117333

**Comment by SileC** [comment]
Thanks
