### ISSUE TITLE
Add: Add TAP DMV channels please

### ISSUE THREAD

**Issue by Ariesandres** [iptv-org/iptv#8142]
### Channel ID

tapgo.tv

### Stream URL

tapgo.tv

### Notes

https://iptv-org.github.io/iptv/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
> IMPORTANT: the issue should contain a request for only one channel, otherwise it will be closed immediately

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel
