### ISSUE TITLE
Replace: TeleAmazonas (EC)

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#8150]
### Stream Title

Teleamazonas (720p) [Not 24/7]

### What happened to the stream?

Not loading

### Possible Replacement

https://api.new.livestream.com/accounts/1359588/events/9942377/live.m3u8

### Notes

This one is 24/7 and works fine.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Currently working.
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/7253922/185796388-dbfad9bb-7917-4de6-8802-b23aa312474d.png">
