### ISSUE TITLE
Add: Venezolana de Televisión (VE)

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#8151]
### Channel ID

VenezolanadeTelevision.ve

### Stream URL

https://www.dailymotion.com/embed/video/x828i6j?autoplay=1

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by R4IN2007** [comment]
Here The m3u8 links from the dailymotion stream

https://www.dailymotion.com/cdn/live/video/x828i6j.m3u8?sec=qtqHzmxevS4MQZsvVf_VtlFhtdr9iMOAclAZo5AwQdMuVhOOnVrmAQV6nCs9-hfyI8hcrSrkFu0-fTTGxa67Aw&dmTs=485557&dmV1st=F784FAF07C6C86AACD89FBE3D040D6DC

https://stream-03.nyc.dailymotion.com/sec(YDiRVmci6dFcTAVfdXnSLoEw92yO30ySSsMweEeRG7dGV5OMg9NsfY3gIC3b45SX)/dm/3/x828i6j/s/live-0.m3u8#cell=lnyc

https://stream-04.nyc.dailymotion.com/sec(YDiRVmci6dFcTAVfdXnSLoEw92yO30ySSsMweEeRG7dGV5OMg9NsfY3gIC3b45SX)/dm/3/x828i6j/s/live-2.m3u8#cell=lnyc

https://stream-02.nyc.dailymotion.com/sec(YDiRVmci6dFcTAVfdXnSLoEw92yO30ySSsMweEeRG7dGV5OMg9NsfY3gIC3b45SX)/dm/3/x828i6j/s/live-3.m3u8#cell=lnyc

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/embed/video/x828i6j?autoplay=1

**Comment by AngelJRomero21** [comment]
> http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/embed/video/x828i6j?autoplay=1


fullspeed.tv cerro alguna alternativa?

**Comment by BellezaEmporium** [comment]
ahora no
