### ISSUE TITLE
Add: WKAQ-DT1 (Telemundo Puerto Rico)

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#8152]
### Channel ID

WKAQDT1.us

### Stream URL

https://nbculocallive.akamaized.net/hls/live/2037499/puertorico/stream1/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Central302** [comment]
[To-Do] I'll Fix Entire NBC News Include This.

**Comment by juliannoagenjo6-oss** [comment]
There problems with Telemundo Puerto Rico WKAQ-DT1 
https://nbculocallive.akamaized.net/hls/live/2037499/puertorico/stream1/master.m3u8
