### ISSUE TITLE
Add: La 7 Castilla-León (ES)

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#8153]
### Channel ID

La7.es

### Stream URL

https://cdnlive.shooowit.net/la7live/smil:channel1.smil/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
interestingly enough they have a Channel 2 https://cdnlive.shooowit.net/la7live/smil:channel2.smil/master.m3u8

that contains nothing but "Output 4"
