### ISSUE TITLE
Add: Viu TV

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#8156]
### Channel ID

ViuTV.hk

### Notes

Original request: #7864

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by SonicPhoon** [comment]
suddenly cannot access to ViuTV and ViuTV6
requires login/password as i try to connect via PotPlayer

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/hk.m3u#L60-L64
