### ISSUE TITLE
Add: Teletoon English

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#8157]
### Channel ID

TeletoonEnglish.ca

### Notes

Original request: #7820

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by CoolCanuck** [comment]
Channel no longer exists.

**Comment by Sphinxroot** [comment]
https://en.wikipedia.org/wiki/Cartoon_Network_(Canadian_TV_channel)
