### ISSUE TITLE
Add: RUV 2

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#8165]
### Channel ID

RUV2.is

### Notes

Original request: #6933

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already in list: please close.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/is.m3u#L6-L7
