### ISSUE TITLE
Add: earthTV

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#8172]
### Channel ID

earthTV.de

### Notes

Website: https://www.earthtv.com/en

Original request: #7059

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://livecloud.earthtv.com/api/v1/media.getPlayerConfig?playerToken=EAIY6wE4l9r-G0gG.CgdlYXJ0aHR2EgtIaWNZMXlDQUJIMBoLSGljWUp6RUFCNUU.nEPMIRC8lusVqmgnT4_LmAUG-L0PLHdXTb3mzzc9QuETuJn2bbrCHxvPiJwHWLZAb-NLFqSUWnDsOQuqKXeEuQ (json) -> {streamUris : hls} m3u8 link generated. Not sure if there is a time limit or if token expires
