### ISSUE TITLE
Fix: A online channel was wrongly deleted in daily update

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#8174]
### Describe your issue

Tele 2000 is still online but this stream was wrongly deleted in this daily update. Since it was established that streams with "error" status for seven days are removed from the playlist, this stream does not seem to meet this condition, which is a bug.

_Originally posted by @sguinetti in https://github.com/iptv-org/iptv/pull/8154#discussion_r950886219_

**Comment by UltraHDR** [comment]
@freearhey these were also deleted https://github.com/iptv-org/iptv/pull/8167

**Comment by freearhey** [comment]
@UltraHDR could you be more specific about which channels you are talking about?

**Comment by UltraHDR** [comment]
> @UltraHDR could you be more specific about which channels you are talking about?


lb.m3u
```
#EXTINF:-1 tvg-id="TeleLiban.lb" status="online",Tele Liban (720p) [Not 24/7]
#EXTVLCOPT:http-referrer=https://www.teleliban.com.lb/live
https://cdn.catiacast.video/abr/ed8f807e2548db4507d2a6f4ba0c4a06/playlist.m3u8
```
iq.m3u
```
#EXTINF:-1 tvg-id="AlIraqiyaAl3ama.iq" status="online",Al Iraqiya Al 3ama (720p) [Geo-blocked]
https://cdn.catiacast.video/abr/8d2ffb0aba244e8d9101a9488a7daa05/playlist.m3u8
#EXTINF:-1 tvg-id="AlIraqiyaNews.iq" status="online",Al Iraqiya News (720p) [Geo-blocked]
https://cdn.catiacast.video/abr/78054972db7708422595bc96c6e024ac/playlist.m3u8
```

**Comment by freearhey** [comment]
@UltraHDR In this case, the script worked as expected. All of these links had "error" status at the time of deletion for more than a week.

https://cdn.catiacast.video/abr/ed8f807e2548db4507d2a6f4ba0c4a06/playlist.m3u8

```json
{"channel":"TeleLiban.lb","url":"https://cdn.catiacast.video/abr/ed8f807e2548db4507d2a6f4ba0c4a06/playlist.m3u8","http_referrer":"https://www.teleliban.com.lb/live","user_agent":null,"status":"error","added_at":"2022-08-13T04:41:45Z","updated_at":"2022-08-13T14:05:19Z","checked_at":"2022-08-21T04:55:23Z"}
```

https://cdn.catiacast.video/abr/8d2ffb0aba244e8d9101a9488a7daa05/playlist.m3u8

```json
{"channel":"AlIraqiyaAl3ama.iq","url":"https://cdn.catiacast.video/abr/8d2ffb0aba244e8d9101a9488a7daa05/playlist.m3u8","http_referrer":null,"user_agent":null,"status":"error","added_at":"2022-08-13T04:41:45Z","updated_at":"2022-08-13T14:05:19Z","checked_at":"2022-08-21T04:55:23Z"}
```

https://cdn.catiacast.video/abr/78054972db7708422595bc96c6e024ac/playlist.m3u8

```json
{"channel":"AlIraqiyaNews.iq","url":"https://cdn.catiacast.video/abr/78054972db7708422595bc96c6e024ac/playlist.m3u8","http_referrer":null,"user_agent":null,"status":"error","added_at":"2022-08-13T04:41:45Z","updated_at":"2022-08-13T14:05:19Z","checked_at":"2022-08-21T04:55:23Z"}
```

Run log: https://github.com/iptv-org/iptv/actions/runs/2898391167

**Comment by sguinetti** [comment]
Other example (Metro TV): https://github.com/iptv-org/iptv/pull/8180/files#r951951554

**Comment by freearhey** [comment]
Yes, I've already found hopefully all of them: 

https://github.com/iptv-org/iptv/pull/8180/files

ar.m3u

```
#EXTINF:-1 tvg-id="MetroTV.ar" status="online",Metro TV
https://streamtv12.ddns.net:5443/LiveApp/streams/193945633734205616732920.m3u8
```

ir.m3u

```
#EXTINF:-1 tvg-id="PressTV.ir" status="online",Press TV French (1080p) [Not 24/7]
https://live1.presstv.ir/live/presstvfr/index.m3u8
```

pl.m3u

```
#EXTINF:-1 tvg-id="TVRepublika.pl" status="online",TV Republika (540p) [Not 24/7]
http://m1-tvrepublika.4vod.tv/smil:premium_abr.ism/playlist.m3u8
```

sk.m3u

```
#EXTINF:-1 tvg-id="JOJ.sk" status="online",JOJ (720p) [Not 24/7]
https://nn.geo.joj.sk/hls/joj-720.m3u8
#EXTINF:-1 tvg-id="JOJ.sk" status="online",JOJ (720p) [Not 24/7]
https://nn.geo.joj.sk/live/hls/joj-720.m3u8
#EXTINF:-1 tvg-id="JOJ.sk" status="online",JOJ (540p) [Not 24/7]
https://nn.geo.joj.sk/hls/joj-540.m3u8
#EXTINF:-1 tvg-id="Plus.sk" status="online",Plus (540p) [Not 24/7]
https://nn.geo.joj.sk/live/hls/jojplus-540.m3u8
#EXTINF:-1 tvg-id="Rik.sk" status="online",Rik (540p) [Not 24/7]
https://nn.geo.joj.sk/live/hls/rik-540.m3u8
#EXTINF:-1 tvg-id="TVWAU.sk" status="online",TV WAU (540p) [Not 24/7]
https://nn.geo.joj.sk/hls/wau-540.m3u8
#EXTINF:-1 tvg-id="TVWAU.sk" status="online",TV WAU (540p) [Not 24/7]
https://nn.geo.joj.sk/live/hls/wau-540.m3u8
#EXTINF:-1 tvg-id="" status="online",JOJ Family (540p) [Not 24/7]
https://nn.geo.joj.sk/hls/family-540.m3u8
#EXTINF:-1 tvg-id="" status="online",JOJ Family (360p) [Not 24/7]
https://nn.geo.joj.sk/hls/family-360.m3u8
```

us_adultiptv.m3u

```
#EXTINF:-1 tvg-id="AdultIPTVnetBrunette.us" status="online",AdultIPTV.net Brunette (720p)
http://cdn.adultiptv.net/brunette.m3u8
```

Unfortunately, after that there were 3 more updates and it seems they also have such links and so far I have absolutely no idea what the reason is.

If until tomorrow it will not be possible to figure out what is wrong, I will temporarily disable the script.

**Comment by freearhey** [comment]
I temporarily disabled the `db:clear` script. https://github.com/iptv-org/iptv/commit/20f321cff95f314795ca8e023edae8365b71911b

As soon as the bug is fixed, all wrongly deleted links will be returned to the playlists.

**Comment by freearhey** [comment]
The bug should be gone by now.

All wrongly deleted links returned to playlists: #8229

**Comment by Brunisky14** [comment]
do i get make ric.today vlc for like english track and germany track for vlc
