### ISSUE TITLE
Replace: THE CW NETWORK USA

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#8179]
### Broken Link

https://cdn006.teleuptv.net/rTK2EQCVCX/playlist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Could not find this link in the playlists.
