### ISSUE TITLE
Replace: Kapamilya Channel

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#8186]
### Broken Link

https://github.com/iptv-org/iptv/blob/3d9cce39dfcfe101ef2ff6e6a7f3f8ddd8ceb1c6/streams/ph.m3u#L16-L17

### What happened to the stream?

Not loading

### Notes

> Non-working stream, I checked on VLC, hls.js and mpv-android.

https://github.com/iptv-org/iptv/issues/6648#issuecomment-1222468708

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Try this?

https://youtu.be/ar2O6AOQabA

**Comment by freearhey** [comment]
Broken link removed from playlist.
