### ISSUE TITLE
Add: KMTV

### ISSUE THREAD

**Issue by AzeemHadzrie** [iptv-org/iptv#8188]
### Channel ID

KMTV.kr

### Stream URL

https://fc411f09ac2840368cad3ceb953e0bc9.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Plex_KMTV/playlist.m3u8

### Notes

Channel that broadcast programming.

Available in Thailand (TrueVisions) and providers that carry the channel.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://kmtvnow-samsung-us.plex.wurl.tv/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
http://www.kmtvnow.com/

**Comment by AzeemHadzrie** [comment]
> K-Pop oriented channel, like many emerging new ones. https://kmtvnow-samsung-us.plex.wurl.tv/playlist.m3u8

Link works on VLC and streamtest.in
