### ISSUE TITLE
Add: Marin TV - Government Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8190]
### Channel ID

MarinTVGovernmentChannel.us

### Stream URL

https://dacastmmd.mmdlive.lldns.net/dacastmmd/ddf2a073e3da4acb9feb34bef6d58672/chunklist_b4628000.m3u8?p=79&s=1660937078&e=1660937198&h=2cd07dfac35ae6fb2fe20e5e40191ad6

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://dacastmmd.mmdlive.lldns.net/dacastmmd/ddf2a073e3da4acb9feb34bef6d58672/playlist.m3u8
