### ISSUE TITLE
Add: Marin TV - Education

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8191]
### Channel ID

MarinTVEducationalChannel.us

### Stream URL

https://dacastmmd.mmdlive.lldns.net/dacastmmd/8e6d110b223b4aca9dd6f7c368baec07/chunklist_b4628000.m3u8?p=79&s=1660937211&e=1660937331&h=11869bf01a80253d43af12bc41252506

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://dacastmmd.mmdlive.lldns.net/dacastmmd/8e6d110b223b4aca9dd6f7c368baec07/playlist.m3u8
