### ISSUE TITLE
Add: MCOE - METV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8192]
### Channel ID

METV.us

### Stream URL

https://mercedcouedu.secure.footprint.net/egress/bhandler/mercedcouedu/streamc/chunklist_b1192000.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by TKList** [comment]
Merced Educational Television
