### ISSUE TITLE
Add: MCAET

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8193]
### Channel ID

MCAETTV.us

### Stream URL

https://video-weaver.yto01.hls.ttvnw.net/v1/playlist/CooF5gWkH3-Ojmm0kbnTvkqSn2jdH7EZptKY_g8kG7k7rD2EKLfMTUuTvU8JBJWYbOBHEl2JLrfWqnRm2fx2j791G1SoDcKcNdHmfw9TMpoJXvV_2iD8pv7BwwRtPhUTrGe35E-sQ4aRfLen3gEaLVMtdC7lb_7tVGVBb58i_l5crNbr7CIcTvlT3SWl5VwiaU9zIPs63hAlrXm9u9y7hX_pIDwce_y4-GMcwXk0BfPRYIcBGXB93CKPqa0uJdPSenCQi17Fr5k-eHCHy8UloY-dSwZ8fegRlP90Rv5JOLpC6ICjvYk1F8Bj_d2iz0Yd-GPaNXrzLAwy8wdyRjursvwBJgjlgxAAE3LcX0O9yaBAVncsJ-MF7XQLe3QwiFn-oF9CpPi8XXDPho9bTXOL9MFNd6Ex6Q2TEJ9BLuRspQ2y7_pGBQ_4Ave0_vJf-gaWHn00M4QZzJFM1-9g61hhq2KFbvjXccFSSXFq1gUFTIyXvaYtWZFBIvJXAqCuTNLzngnBFDxiOOQnIrAySJsCF4ul1YghSKQZY7bgVMz8GdPV5C1t75ih3cCBjOPFjzGvL5WfVr_t8XJgGJ8S53xhkzxwUJSzljMel4h_bHAhbkcO0IN7_Q5jMoCwQym3SJkd15JdcOgpme2XTezLyIMYiXgbd0takiBItNmPVfpHAgoC8y68C1kyi3EIFYvrrCa-L2LEtDmi3Th0vLGuJmelRlCgylAyvBN4IcNi4BwZ3Hk7zBi_791Y5fzkRVDdSAGuLgiLkc4FpKoKucPIp1y8cn5sW1nYp__yr3gu0b61Qx2Ov1MDbbrBu3Gwy4wYSQmIap4vFHcNqQKJUhr9zmNevY5PfsdlSnviwSqC0dgaDGl2hJa1clx7Be4lriABKgl1cy13ZXN0LTIwvQQ.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/mcaettv
