### ISSUE TITLE
Add: NCM Main Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8194]
### Channel ID

NCMMainChannel.us

### Stream URL

https://cdn3.wowza.com/5/cHYzekYzM2kvTVFH/nevco/G0644_001/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://cdn3.wowza.com/5/cHYzekYzM2kvTVFH/nevco/G0644_001/playlist.m3u8
