### ISSUE TITLE
Add: NCM Government & Politics

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8195]
### Channel ID

NCMGovernmentPoliticsChannel.us

### Stream URL

https://cdn3.wowza.com/5/cHYzekYzM2kvTVFH/nevco/G0644_002/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://cdn3.wowza.com/5/cHYzekYzM2kvTVFH/nevco/G0644_002/playlist.m3u8
