### ISSUE TITLE
Add: Orange TV3

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8197]
### Channel ID

OrangeTV3.us

### Stream URL

https://cdn3.wowza.com/5/R09KQXpaMWlrRjly/cityoforange/G1025_004/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://cdn3.wowza.com/5/R09KQXpaMWlrRjly/cityoforange/G1025_004/playlist.m3u8
