### ISSUE TITLE
Add: Asamblea TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8198]
### Channel ID

AsambleaTV.ni

### Stream URL

https://youtu.be/qBT25Aix5lA

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
when it's online (not 24/7) http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/user/ASAMBLEATVNIC/live
