### ISSUE TITLE
Add: Access Sacramento - Channel 18

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8200]
### Channel ID

AccessSacramentoChannel18.us

### Stream URL

https://reflect-access-sacramento.cablecast.tv/live-8/live/WIFI-1896k-720p/WIFI-1896k-720p.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
I have https://reflect-access-sacramento.cablecast.tv/live-8/live/live.m3u8 as an adaptive link.
