### ISSUE TITLE
Add: Contra Costa TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8205]
### Channel ID

ContraCostaTV.us

### Stream URL

https://reflect-contra-costa.cablecast.tv/live-7/live/WIFI-696k-360p/WIFI-696k-360p.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Duplicate #8123
