### ISSUE TITLE
Add: Kern County Television

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8207]
### Channel ID

KernCountyTV.us

### Stream URL

https://cdn3.wowza.com/5/dk84U1p2UUdoMGxT/kern/G0169_003/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Duplicate #8125
