### ISSUE TITLE
Add: Fayetteville Public Access Television

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8213]
### Channel ID

FPTV.us

### Stream URL

https://www.youtube.com/c/FayettevillePublicTelevision/live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Duplicate #8030
