### ISSUE TITLE
Add: Mobile County Public Schools TV Network

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8215]
### Channel ID

MCPSSTV.us

### Stream URL

https://5b200f5268ceb.streamlock.net/MCPSS/MCPSS247.smil/chunklist_w1482206288_b946000.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Duplicate #8018
