### ISSUE TITLE
Add: Nova Scotia Legislature

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8216]
### Channel ID

LegislativeTV.ca

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/NovaScotiaLegislature/live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Duplicate #8006
