### ISSUE TITLE
Add: earthTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8217]
### Channel ID

earthTV.de

### Stream URL

https://livecdn-de-earthtv-com.global.ssl.fastly.net/edge3/cdnedge/HicYJzEAB5E/chunklist.m3u8?token=EAIY6wE41NLlRUCkIUgF.CgdlYXJ0aHR2EAEyC0hpY1lKeTZBQjVBOgtIaWNZSnpFQUI1RQ.e3fN43zeX9EXpHR5x3PWyogbo4j8GXCSrzgZMP4un6uRHi2dNOHNs0T4lFpi5EFJGZgAcK0d7nmJwAJMwgBSHg&domain=www.earthtv.com

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Duplicate #8172
