### ISSUE TITLE
Add: Kanal A Slovenia

### ISSUE THREAD

**Issue by pukozs75** [iptv-org/iptv#8221]
### Channel ID

KanalA.si

### Stream URL

http://194.163.179.246/slovenci/slonacionalni/akanalhd.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://streamer01.xploretv.si/qdcnm4/__cl/cg:prod/__c/A1_SI_AKANALHD_ott/__op/dash-default/__dci/__f/index.m3u8?redirect=true&admin=xploreTv_test_user

**Comment by Ulixes86** [comment]
https://streamer01.xploretv.si/qdcnm4/__cl/cg:prod/__c/A1_SI_AKANALHD_ott/__op/dash-default/__dci/__f/index.m3u8
does not work anymore (at least at this moment)
