### ISSUE TITLE
Add: 

### ISSUE THREAD

**Issue by galxyiotv** [iptv-org/iptv#8245]
### Channel ID

DESIFLEX 

### Stream URL

http://77.68.7.118:1935/Mystream/myStream/playlist.m3u8

### Notes

URBAN DESI MUSIC

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Author blocked for spamming: 

https://github.com/iptv-org/iptv/pulls?q=involves%3Agalxyiotv
https://github.com/iptv-org/iptv/pulls?q=involves%3AJATTRECORDS
https://github.com/iptv-org/iptv/pulls?q=involves%3Adesiflex
