### ISSUE TITLE
Add: Congress of The Republic of Colombia

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8249]
### Channel ID

ChamberofRepresentatives.co

### Stream URL

https://www.youtube.com/c/C%C3%A1maradeRepresentantes2020/live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCzescUFTh2jiZkYIx9uZtqAlive
Not 24/7.
