### ISSUE TITLE
Add: Republic of Costa Rica Legislative Assembly

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8250]
### Channel ID

TVLegislativa.cr

### Stream URL

https://www.youtube.com/user/parlamentocr/live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by aIemtro** [comment]
Stream: http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/user/parlamentocr/live
