### ISSUE TITLE
Add: Unife TV

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#8252]
### Channel ID

UnifeTV.pe

### Stream URL

https://dacastmmd.mmdlive.lldns.net/dacastmmd/acda902f73a646daac3fdc9dcddbc971/playlist.m3u 

### Notes

Official stream from website (https://universal.org.pe/canal-unife-tv/) is tokenized.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://dacastmmd.mmdlive.lldns.net/dacastmmd/acda902f73a646daac3fdc9dcddbc971/playlist.m3u8 works
