### ISSUE TITLE
Add: TBN UK

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8287]
### Channel ID

TBNUK.uk

### Stream URL

https://livestreamapis.com/v3/accounts/28567990/events/8919546/master.m3u8?token=0f6a2e07716d2b80af8d4ea3b03e9665&clientId=13929&timestamp=1661468530728

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://api.new.livestream.com/accounts/28567990/events/8919546 as it might be a hidden channel.
