### ISSUE TITLE
Add: TBN Africa 

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8288]
### Channel ID

TBNAfrica.za

### Stream URL

https://api.new.livestream.com/accounts/27460990/events/8787764/broadcasts/232661911.secure.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Link is 404 and reference is tokenized.
https://www.tbnafrica.org/vod/webcast

**Comment by AntiPontifex** [comment]
Dead stream: please close.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/za.m3u#L24-L25
