### ISSUE TITLE
Add: KALB Community Media

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8292]
### Channel ID

KALB.us

### Stream URL

https://cdn3.wowza.com/5/dk84U1p2UUdoMGxT/albanyca/G0327_002/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://cdn3.wowza.com/5/dk84U1p2UUdoMGxT/albanyca/G0327_002/playlist.m3u8
