### ISSUE TITLE
Add: Banning CityTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8293]
### Channel ID

BanningCityTV.us

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://vblive-c.viebit.com/072e341f-100d-4da1-9c18-65370ebf35c6/playlist.m3u8
