### ISSUE TITLE
Add: The Danish Parliament

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8294]
### Channel ID

TVfromtheDanishParliament.dk

### Stream URL

https://klive.kaltura.com/s/env/cluster-1-a.live.frp1/live/hls/p/2158211/e/1_24gfa7qq/tl/main/st/0/t/ys5JUGseQbAnuzkQ0G8Zzw/index-s32.m3u8?__hdnea__=st=1661400124~exp=1661486524~acl=/s/env/cluster-1-a.live.frp1/live/hls/p/2158211/e/1_24gfa7qq/tl/main/st/0/t/ys5JUGseQbAnuzkQ0G8Zzw/index-s*~hmac=47a364c53e08fac7f5ad8a2e4ed061610d6a322d6a809425b5f180b21b38a368

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://cdnapi.kaltura.com/p/2158211/sp/327418300/playManifest/entryId/1_24gfa7qq/protocol/https/format/applehttp/a.m3u8
