### ISSUE TITLE
Add: Senate TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8295]
### Channel ID

SenateTV.ar

### Stream URL

https://youtu.be/5DwCG7djsSQ

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
when online http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/SenadoTVArgentina/live
