### ISSUE TITLE
Add: Cartoon Network Philippines

### ISSUE THREAD

**Issue by bbbureneecartoonz** [iptv-org/iptv#8297]
### Channel ID

CartoonNetworkPhilippines.ph

### Stream URL

https://iptv-sniper.herokuapp.com/localtv.php?channel=29

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Link doesn't work.

**Comment by bbbureneecartoonz** [comment]
> Link doesn't work.

why
