### ISSUE TITLE
Add: Camara de Representantes

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8338]
### Channel ID

ChamberofRepresentatives.uy

### Stream URL

https://vxlive.cdn.antel.net.uy/auth_V_Camara_Representantes,vxttoken=cGF0aFVSST0lMkZhdXRoX1ZfQ2FtYXJhX1JlcHJlc2VudGFudGVzJTJGdnhmbXQlM0RobHMlMkYlMkEmZXhwaXJ5PTE2NjE1MDM3MDUmcmFuZG9tPTd5S0JoWk5WcmsmYy1pcD0yNC4yMzUuMTY0Ljk0JmlkX3JlZmVyZW5jaWE9JmlkX2Rpc3Bvc2l0aXZvPTAmaWRfZnJvbnRlbmQ9MTE5NiZwdWJsaWNfaWQ9MnM2OG0sZTRmYzdkYmU2MTY4ZTViY2EyNWRhYTNkZjhiM2I0MWZiNjQ1NzE0NzAwYWZjZDA2YTdhYmFmZWJiMTQyZmJmNw==/vxfmt=hls/h_dbaab24620f0deb7d178a8a9578e4a1d/var3000000/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
either http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCUxioxgZ7obrP3wVJApAK1w/live when they're online, or nothing because this is a tokened link, and i'm pretty sure it's IP-locked too.

**Comment by LaneSh4d0w** [comment]
in case someone wants to work on it : POST with https://veratv-be.vera.com.uy/api/sesiones data "tipo=anonima", keep token and authorisation.

get https://veratv-be.vera.com.uy/api/setup?token=*token*&public_id=2s68m and search on "suggested" for the streams, link is there.
