### ISSUE TITLE
Add: addikTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8339]
### Channel ID

addikTV.ca

### Stream URL

https://ctsaddiklive.akamaized.net/Content/HLS/Live/channel(850a43fa-51dd-9c54-b144-3bd6b9cd0983)/hdntl=exp=1661711382~acl=%2f*~data=hdntl~hmac=1d648d0470ef0a8daf2865e82199bbef8b906527f9e58f39cc5dc0110d1e519e/05.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Tokenized + TVA restricts everything (except one channel if I remember well) with geo-lock.
