### ISSUE TITLE
Add: The Burbank Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8346]
### Channel ID

TheBurbankChannel.us

### Stream URL

https://cdn3.wowza.com/5/djRwZmQvTEJidmZD/burbank/G0240_009/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://cdn3.wowza.com/5/djRwZmQvTEJidmZD/burbank/G0240_009/playlist.m3u8
