### ISSUE TITLE
Add: Cable 14 Live

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8351]
### Channel ID

Cable14Hamilton.ca

### Stream URL

https://flowcaster1-cl.cdn.clearcable.net/C14/smil:C14.smil/playlist.m3u8?iimae0UC2aendtime=1661690601&iimae0UC2astarttime=1661676201&iimae0UC2ahash=-1m-M_lPw2-U1W-rJTVg1PHe_-Ekt4ymjZOuE1g1xUI=

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by benevenstanciano** [comment]
I don't think this will work due to the token.

**Comment by R4IN2007** [comment]
Stream Link 1: https://flowcaster1-cl.cdn.clearcable.net:443/C14/smil:C14.smil/chunklist_w1544935958_b3160000_sleng_tkaWltYWUwVUMyYWVuZHRpbWU9MTY2MTczNjk2MiZpaW1hZTBVQzJhc3RhcnR0aW1lPTE2NjE3MjI1NjImaWltYWUwVUMyYWhhc2g9SXdDTTJvcU94RTFUdUw2MXlVX09TM0czQWRnLWtmVTdXeDFpSHJ1NDhIaz0=.m3u8

Stream Link 2:https://flowcaster1-cl.cdn.clearcable.net:443/C14LS2/smil:C14LS2.smil/chunklist_w1813838757_b3160000_sleng_tkaWltYWUwVUMyYWVuZHRpbWU9MTY2MTczNjk4MiZpaW1hZTBVQzJhc3RhcnR0aW1lPTE2NjE3MjI1ODImaWltYWUwVUMyYWhhc2g9YklyeTF0M2JmQXhjeWxjVlo3bGxuTnBrNVloOGpSRzk5ckk2aGx4R0FQVT0=.m3u8

**Comment by LaneSh4d0w** [comment]
Tokened, and I'm pretty sure this one's IP-locked. Used to have tried on this same Cable 14 channel.
