### ISSUE TITLE
Add: De Kamer/Le Chambre

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8362]
### Channel ID

ChamberofRepresentatives.be

### Stream URL

https://5f43d883c9907.streamlock.net/vod/_definst_/mp4:vod/55/014688-P200.mp4/chunklist_w912718927.m3u8?audioindex=1

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
VOD stream proposed, watch out.

**Comment by LaneSh4d0w** [comment]
From deduction and from how the URL looks like inside the livestream XML : https://5ecc011235cd2.streamlock.net/live/F0A/playlist.m3u8

**Comment by Alstruit** [comment]
Links are 404'd
