### ISSUE TITLE
Add: The Scenic City

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8366]
### Channel ID

TheScenicCity.ca

### Stream URL

https://flowcaster1-ch.cdn.clearcable.net/C14LS2/smil:C14LS2.smil/playlist.m3u8?iimae0UC2aendtime=1661690801&iimae0UC2astarttime=1661676401&iimae0UC2ahash=c2OyJNFrh6zIrS17mn0D6q0FMGVqQPdoKBF93_D0a1Q=

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Tokened.
