### ISSUE TITLE
Replace: Cartoon Network East

### ISSUE THREAD

**Issue by bbbureneecartoonz** [iptv-org/iptv#8379]
### Broken Link

https://tve-live-lln.warnermediacdn.com/hls/live/2023167/tooneast/slate/VIDEO_0_3564000.m3u8

### What happened to the stream?

Other

### Possible Replacement

http://live.tv247.club/tv247/cn.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Central302** [comment]
![CNCN](https://user-images.githubusercontent.com/86145713/187401894-7badf34d-3d29-4804-8ed2-271876d0794b.PNG)
(works at US IP)

**Comment by bbbureneecartoonz** [comment]
> ![CNCN](https://user-images.githubusercontent.com/86145713/187401894-7badf34d-3d29-4804-8ed2-271876d0794b.PNG) (works at US IP)

yes

**Comment by TKList** [comment]
The warnermediacdn streams sometimes throw a CORS error, but seem to work sooner later again.

**Comment by bbbureneecartoonz** [comment]
> The warnermediacdn streams sometimes throw a CORS error, but seem to work sooner later again.

no it's geo-blocked

**Comment by TKList** [comment]
That too.
