### ISSUE TITLE
Add: TVA Montreal

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8385]
### Channel ID

TVAMontreal.ca

### Stream URL

https://tvalive-nondai.akamaized.net/Content/HLS/Live/channel(a7315e07-037c-12a8-bdc8-da7bd513da9d)/02.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by takethis2165** [comment]
This stream work  https://tvalive-nondai.akamaized.net/Content/HLS/Live/channel(a7315e07-037c-12a8-bdc8-da7bd513da9d)/02.m3u8  maybe geo.I live in Quebec

**Comment by Alstruit** [comment]
Closing since stream already exists.
