### ISSUE TITLE
Add: ICI Montreal

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8386]
### Channel ID

CFHDDT.ca

### Stream URL

https://amdici.akamaized.net/hls/live/873426/ICI-Live-Stream/233bc8cf83124bde9c6d55842e5de3ab/1.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Smark223** [comment]
Adaptive: https://amdici.akamaized.net/hls/live/873426/ICI-Live-Stream/master.m3u8
