### ISSUE TITLE
Add: Global News BC1

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8388]
### Channel ID

GlobalNewsBC1.ca

### Stream URL

https://live.corusdigitaldev.com/groupd/live/49a91e7f-1023-430f-8d66-561055f3d0f7/live.isml/live-audio_1=96000-video=2499968.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by dtngfan85** [comment]
FYI this is not their local news cable channel BCNews1, it's their Global News BC stream which was previously DMCA'd by Corus

**Comment by takethis2165** [comment]
The first stream is ok in Quebec

**Comment by Alstruit** [comment]
Closing in favor #9374
