### ISSUE TITLE
Add: CHEK

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8389]
### Channel ID

CHEK.ca

### Stream URL

https://zypelive-amd-uswe.akamaized.net/hls/live/2041168/main/playlist.m3u8?6pLKMQ3y=pLK0uw32&F38b1dF4=630e2136d7894e000133fb86&video_id=62ec07c17176280001fd6aa4&hdnts=exp%3D1661956790%7Eacl%3D%2F*2041168%2F*%7Ehmac%3D79fef64f85c5cc9ef6ef92a0e11d62a810c688aab4095004b7f5035915448398

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by dtngfan85** [comment]
The stream is protected by a token that expires in 21 hours.
