### ISSUE TITLE
Add Two Channel Stream From Youtube

### ISSUE THREAD

**Issue by chezsick** [iptv-org/iptv#839]
hello, you can add channel nasa tv (us.m3u):::::: https://www.youtube.com/watch?v=21X5lGlDOfg and the stream know on this repo is poor, and the french channel FranceInfo: (fr.m3u) :::::: https://www.youtube.com/watch?v=wwNZKfBLAsc i hope is not blocked in your country.

Sick/Newa.

**Comment by freearhey** [comment]
Sorry, but we don't add YouTube streams to the playlist.
