### ISSUE TITLE
Add: NFL RedZone

### ISSUE THREAD

**Issue by mrtajniak** [iptv-org/iptv#8405]
### Channel ID

NFLRedZone.us

### Stream URL

https://list.iptvcat.com/my_list/s/8eef0ceed1ebe520e2b8447d7bdfc718.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by MapGuy11** [comment]
Xtreme Codes
