### ISSUE TITLE
Add: ESPN

### ISSUE THREAD

**Issue by mrtajniak** [iptv-org/iptv#8406]
### Channel ID

ESPN.us

### Stream URL

https://list.iptvcat.com/my_list/s/1433e7772fa233e72a61ed4b1ac73baa.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Xtream-Codes servers (even through such redirectors as IPTVCat) aren't accepted.
