### ISSUE TITLE
Request Channels of Democratic Republic of Congo 

### ISSUE THREAD

**Issue by bermufine** [iptv-org/iptv#842]
Hello,
I am requesting an Congo channels, by the name of :
digital_congo
Heritage tv
Nyota tv
RTVS1
RTNC2
Antenne A
Rtg@.
Please Feel free To send me a working link in my gmail: Congomonpays243@gmail.com

Thank you, and have a wonderful day.

Good luck on future upgrades and keep up the work.

Also, if you can, please add HD streams of Tele50
B-ONE
RTNC
Mwangaza
Don't Forget SPORTS channels like Bein Sport HD from 1 To 12

Thank you once again.

**Comment by freearhey** [comment]
Duplicate #812
