### ISSUE TITLE
Add: Encinitas City Council Meetings

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8420]
### Channel ID

MyEncinitasTV.us

### Stream URL

https://cdn3.wowza.com/5/RXJNMFI3VlVkOEFP/encinitas/G0322_002/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://cdn3.wowza.com/5/RXJNMFI3VlVkOEFP/encinitas/G0322_002/playlist.m3u8
