### ISSUE TITLE
Add: KFON TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8422]
### Channel ID

KFONTV.us

### Stream URL

https://watchkfon.fontana.org/CablecastPublicSite/?channel=1

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://reflect-watchkfon-fontana.cablecast.tv/live-3/live/live.m3u8

**Comment by LaneSh4d0w** [comment]
Geo for this one
