### ISSUE TITLE
Add: FV Television

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8423]
### Channel ID

FVTV.us

### Stream URL

https://fountainvalley.granicus.com/MediaPlayer.php?publish_id=2

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://cdn3.wowza.com/5/cHYzekYzM2kvTVFH/fountainvalley/G0806_001/playlist.m3u8
