### ISSUE TITLE
Add: EMCI TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8428]
### Channel ID

EMCITV.ca

### Stream URL

https://stream-01.nyc.dailymotion.com/sec(mOyh5XasEoxB2izGnZ4Ls9on0W3Iy5TKqlwGL79Bf6JcG2Pr-K-9EC8ahi_1r4jn)/dm/3/x8azdl4/s/live-4.m3u8#cell=lnyc

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x8azdk1

**Comment by thihazawsatellite** [comment]
thank

**Comment by armeltindo** [comment]
EMCI TV is not available in channels
