### ISSUE TITLE
Add: HollyWire

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8429]
### Channel ID

HollyWire.us

### Stream URL

https://bozztv.com/hwotta/playlist/HD3400/HD3400.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://bozztv.com/hwotta/playlist/playlist.m3u8 though it's been a while since I've seen that host around.
