### ISSUE TITLE
Add: Miracle Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8430]
### Channel ID

MiracleChannel.ca

### Stream URL

https://d9ruw6nhj5a52.cloudfront.net/live/live/chunklist_w1253946286.m3u8

### Notes

Strange one: if you load up the streaming URL in VLC it immediately crashes. Help with this one would be most appreciated.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://d9ruw6nhj5a52.cloudfront.net/live/live/playlist.m3u8

geo-locked to Canada

**Comment by AntiPontifex** [comment]
I'm in Canada: this channel and CityTV still crash with your url changes, LaneSh4d0w. Thanks for trying though.

**Comment by AntiPontifex** [comment]
Dead link.
