### ISSUE TITLE
Add: Citytv Toronto

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8431]
### Channel ID

CITYDT.ca

### Stream URL

https://citylive.citytv.com/b991d36a-7ed1-4a18-b771-562e1625a7c3/f9385d7e-c862-49aa-b806-f2ff5fcd5052.ism/QualityLevels(127000)/Fragments(audio=17264922141,format=mpd-time-csf)

### Notes

Same as Miracle Channel comment: immediately crashes. Please help.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://citylive.citytv.com/b991d36a-7ed1-4a18-b771-562e1625a7c3/f9385d7e-c862-49aa-b806-f2ff5fcd5052.ism/manifest.mpd

though i think the data inside changes + DRMd + geo-locked.
