### ISSUE TITLE
Add: TVB News Channel

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#8435]
### Channel ID

TVBNewsChannel.hk

### Stream URL

http://111.229.84.232/yulin/tvb.php?id=1

### Notes

And what about the other valid m3u8s?

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/hk.m3u#L55-L59
