### ISSUE TITLE
Add: UCTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8452]
### Channel ID

UCTV.us

### Stream URL

https://59e8e1c60a2b2.streamlock.net/509/509.stream/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
[Already Done](https://github.com/iptv-org/iptv/blob/c3ecac33aa203ee4d1ebaf4441677cfaf74fcd25/channels/us.m3u~master#L1815)
