### ISSUE TITLE
Add: KRSU-TV

### ISSUE THREAD

**Issue by Arkina1234** [iptv-org/iptv#8454]
### Channel ID

KRSUDT1.us

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by TiberiusZ** [comment]
The M3U8 for KRSUDT1 is https://2-fss-2.streamhoster.com/pl_118/amlst:202742-1432010/chunklist_b4500000.m3u8
