### ISSUE TITLE
Add: WVCY-TV

### ISSUE THREAD

**Issue by Arkina1234** [iptv-org/iptv#8457]
### Channel ID

WVCYDT1.us

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://livestream.com/accounts/30337923/events/9488449/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Are they really dealing with analogic there ? x)

**Comment by MapGuy11** [comment]
> Are they really dealing with analogic there ? x)

It's definitely a 480i cable stream not deinterlaced and downscaled to 360p.
