### ISSUE TITLE
Add: Glendale TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8461]
### Channel ID

GlendaleTV.us

### Stream URL

https://reflect-gtv6-glendale.cablecast.tv/live-2/live/WIFI-1296k-540p/WIFI-1296k-540p.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://reflect-gtv6-glendale.cablecast.tv/live-2/live/live.m3u8

**Comment by LaneSh4d0w** [comment]
Geo-blocked, but most certainly works.
