### ISSUE TITLE
Add: NACTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8470]
### Channel ID

NACTV.ca

### Stream URL

https://s3.amazonaws.com/cdn.pivotalelements.com/NACTV-HLS.xspf

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://stream.pivotalelements.com/nactv/stream.m3u8

**Comment by LaneSh4d0w** [comment]
Already in playlists.
