### ISSUE TITLE
Add: Greater Bay TV

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#8474]
### Channel ID

GreaterBayTV.cn

### Stream URL

https://nftctv.gdtv.cn/live/nfws.m3u8?auth_key=1662295303-0-0-63939b8a04b04b2958a16b7b340a6747

### Notes

New TV channel from China...... 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Tokened.

**Comment by AntiPontifex** [comment]
Dead stream: please close.
