### ISSUE TITLE
Add: BeachTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8478]
### Channel ID

BeachTVCSULB.us

### Stream URL

https://iptv-org.github.io/?q=Beach%20TV%20CSULB

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Already inside our playlists : http://stream04.amp.csulb.edu:1935/Beach_TV/smil:BeachTV.smil/playlist.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/c662ef7b63497ffbddcdaf8728fcda82ab1bec86/streams/us.m3u#L125-L126
