### ISSUE TITLE
Add: LBTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8479]
### Channel ID

LBTV.us

### Stream URL

https://cdn3.wowza.com/5/WDIrTW5sM1JEY1NN/longbeach/G0020_001/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://cdn3.wowza.com/5/WDIrTW5sM1JEY1NN/longbeach/G0020_001/playlist.m3u8
