### ISSUE TITLE
Add: LA CityView 35

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8481]
### Channel ID

LACityView35.us

### Stream URL

https://reflect-losangeles.cablecast.tv/live-3/live/WIFI-2096k-1080p/WIFI-2096k-1080p.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://reflect-losangeles.cablecast.tv/live-3/live/live.m3u8
