### ISSUE TITLE
Add: KCAT

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8482]
### Channel ID

KCAT.us

### Stream URL

https://reflect-kcat-live.cablecast.tv/live-2/live/WIFI-2096k-1080p/WIFI-2096k-1080p.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://reflect-kcat-live.cablecast.tv/live-2/live/live.m3u8
