### ISSUE TITLE
Fix: Issue linked to Nepal playlist.

### ISSUE THREAD

**Issue by ursmilan142** [iptv-org/iptv#8486]
### Broken Link

https://iptv-org.github.io/iptv/countries/np.m3u

### What happened to the stream?

Shows the wrong channel

### Notes

All the channels in this list are not from Nepal except KantipurHD 1080p. Please take all the other links from this m3u file. Thank You.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
The others are basically Internationally-streamed channels, hence why you have more than 40 channels, in contrary to the unique channel registered in Nepal.
