### ISSUE TITLE
Al Iraqiya 

### ISSUE THREAD

**Issue by samg80** [iptv-org/iptv#8490]
### Channel ID

AlIraqiaNews.iq

### Stream URL

https://imn.iq/%d8%a7%d9%84%d8%b9%d8%b1%d8%a7%d9%82%d9%8a%d8%a9-%d8%a7%d9%84%d8%a7%d8%ae%d8%a8%d8%a7%d8%b1%d9%8a%d8%a9-hd/

### Notes

This channel is missing in my IPTV Iraq channel list. I used to have it in my list long time ago, but I no longer see it in the channels lineup, regardless how many times I re-add the m3u URL.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://cdn.catiacast.video/abr/78054972db7708422595bc96c6e024ac/playlist.m3u8 Authorization Required

**Comment by samg80** [comment]
@LaneSh4d0w, Is that "Authorization Required" for me?

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w, Is that "Authorization Required" for me? 

No, it's the answer from the link next to it. I can't access the stream because it asks for an autorization.

**Comment by samg80** [comment]
Is there something that I can do?

**Comment by LaneSh4d0w** [comment]
Sadly not. I think it needs a referrer like all the other Catiacast links we have.

**Comment by UltraHDR** [comment]
works fine for me
