### ISSUE TITLE
Replace: Christian Youth Channel CYC

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8491]
### Broken Link

http://media.smc-host.com:1935/cycnow.com/cyc2/playlist.m3u8

### What happened to the stream?

Stuck at a single frame

### Possible Replacement

https://5d658d7e9f562.streamlock.net/cycnow.com/cyc.smil/chunklist_w1480867955_b928000_slar.m3u8

### Notes

Accessing from CA: a FBI warning-type screen appears with (rather humorously) a Though Shalt Not Steal reprimand. 
Found out about this by chance: just thought you'd like to know for completeness sake.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
At the moment the broadcast is working fine.

http://media.smc-host.com:1935/cycnow.com/cyc2/playlist.m3u8
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/7253922/189449820-9713f93d-f670-41eb-9b88-565faf6118df.png">
