### ISSUE TITLE
Add: TV Brasil [BR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#8504]
### Channel ID

TVBrasil.br

### Stream URL

https://5c483b9d1019c.streamlock.net/8022/8022/playlist.m3u8

### Notes

It's the brazilian public TV channel.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Link is Geo locked and probably tokenized.
https://rtpa-live-hls.flumotion.com/playlist.m3u8

**Comment by Alstruit** [comment]
For the OP Link to stream, the ID is possibly incorrect. Link for reference:
https://www.tvbejoinville.com.br/

**Comment by AntiPontifex** [comment]
Now is Record News: please close.
