### ISSUE TITLE
Add: Mega TV [US/PR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#8505]
### Channel ID

MegaTV.us

### Stream URL

https://livestream.lamusica.com/megatvP320/ngrp:megatvP320_all/chunklist_w1349839832_b478000.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Closing in favor #8760
