### ISSUE TITLE
Cartoon Network Mexico [MX]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#8507]
### Channel ID

CartoonNetworkMexico.mx

### Stream URL

https://playout.cdn.cartoonnetwork.com.br/playout_02/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://playout.cdn.cartoonnetwork.com.br/playout_02/playlist.m3u (404 Not Found)

**Comment by Alstruit** [comment]
Done #8273
