### ISSUE TITLE
Add: ETB 1 [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#8510]
### Channel ID

ETB1.es

### Stream URL

https://multimedia.eitb.eus/live-content/etb1hd-hls/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Duplicate #8309
