### ISSUE TITLE
Add: ETB 2 [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#8511]
### Channel ID

ETB2.es

### Stream URL

https://multimedia.eitb.eus/live-content/etb2hd-hls/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Duplicate #8310
