### ISSUE TITLE
Add: TPA 7 Asturias [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#8512]
### Channel ID

TPA7.es

### Stream URL

https://cdnlive.codev8.net/rtpalive/smil:directo.smil/fmt_token/W3doCkEYElsXrufewPR4EM9CGCQAcflcxAL3MrzhQPU/eyJleHBpcmUiOjE2NjI0ODM2MDIsInVybF9hbGxvdyI6WyIvcnRwYWxpdmUiXSwicmVmX2FsbG93IjpbIioucnRwYS5lcyIsInJ0cGEuZXMiXX0/chunklist_b1700000_DVR.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Link is tokenized.

**Comment by AntiPontifex** [comment]
Dead link: please close.
