### ISSUE TITLE
Add: 7 Televisión Región de Murcia [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#8514]
### Channel ID

7TelevisionRegiondeMurcia.es

### Stream URL

https://obelix.nopiensomas.com/stream/abr/first.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Multiple streams:
http://webtv.7tvregiondemurcia.es/
