### ISSUE TITLE
Add: El Toro TV [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#8515]
### Channel ID

ElToroTV.es

### Stream URL

https://streaming003.gestec-video.com/hls/eltoro_bal.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Possible multiple stream links: 
https://eltorotv.com/tv-en-directo
https://m3u8.deranet.com/index.php?television=eltorosd
