### ISSUE TITLE
Replace: Caracol Televisión [CO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#8517]
### Broken Link

https://mdstrm.com/live-stream-playlist/574463697b9817cf0886fc17.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://mdstrm.com/live-stream-playlist_800/58dc3d471cbe05ff3c8e463e.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Link given is Caracol Ahora, a 24/7 news broadcast that is, indeed, not restricted. However first link still works and is geo-restricted to people in Colombia only.

![image](https://user-images.githubusercontent.com/30985701/188736279-c052a999-a1ce-404e-bb79-b6b4fc61acf1.png)

**Comment by freearhey** [comment]
Reference:
https://github.com/iptv-org/iptv/blob/c662ef7b63497ffbddcdaf8728fcda82ab1bec86/streams/co.m3u#L44-L45

**Comment by freearhey** [comment]
Closed in favor #8617
