### ISSUE TITLE
Add: Today's Shopping Choice

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8532]
### Channel ID

TheShoppingChannel.ca

### Stream URL

https://tscamd.akamaized.net/hls/live/503340/TSCLive/video_0/video_0.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Dra19222** [comment]
QWERTYUII
