### ISSUE TITLE
Need more Indian Kids and Entertainment channels.

### ISSUE THREAD

**Issue by ThanosOP** [iptv-org/iptv#854]
It would be nice if you add Disney Hindi, Marvel HQ, Hungama, Cartoon Network Hindi, Zee TV, Colors in your playlist. Thanks for keeping this maintained and free :D.

**Comment by ThanosOP** [comment]
But there are no extra channels added which I requested. Sorry if I'm being bothersome. :(

**Comment by freearhey** [comment]
Hungama:
https://github.com/iptv-org/iptv/blob/fd9752a9f09931f8a52342f97503430dd3c46d3b/channels/in.m3u#L166-L167

**Comment by rmkhalfay** [comment]
Need News18urdu, SaamTv, Zee salaam, Zee24Taas, TV9 Marathi, Tehzeeb, Gulistan,

**Comment by Nintendocustom** [comment]
I think I found some of the channels
Disney Channel Hindi
http://stream-7b694ce7e.nmbs.top/m3u/Kids/c86abe8bd6.m3u8
Cartoon Network Hindi
http://stream-7b694ce7e.nmbs.top/m3u/Kids/1e0a653ba1.m3u8
Marvel HQ
http://stream-7b694ce7e.nmbs.top/m3u/Kids/c9878efeae.m3u8
Hungama TV
http://stream-7b694ce7e.nmbs.top/m3u/Kids/85a27ab7bf.m3u8

**Comment by freearhey** [comment]
@Nintendocustom feel free to add channels to the playlist yourself.

If you don't know how to do it, here is the guide: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#add-channel

**Comment by rmkhalfay** [comment]
Sir

I really don't know how to get this links. Can youtube streaming live channels be added?

Best regards,


Rayees M. Khalfay
________________________________

**Comment by Chakravarthy07** [comment]
I want the same channels in telugu. Please some one add them 🙏🏻

**Comment by amzadhsn** [comment]
I need Disney channel hindi (India) iptv m3u link.please help me

**Comment by tanvir8282** [comment]
> - [x] [Disney Channel](http://disneychannel.disney.in/)
> https://github.com/iptv-org/iptv/blob/08123cd12385dbb75c993a850edaf0f05e7c341e/channels/in.m3u#L142-L143
> - [x] [Marvel HQ](https://en.wikipedia.org/wiki/Marvel_HQ)
> https://github.com/iptv-org/iptv/blob/08123cd12385dbb75c993a850edaf0f05e7c341e/channels/in.m3u#L242-L243
> - [x] Hungama
> https://github.com/iptv-org/iptv/blob/fd9752a9f09931f8a52342f97503430dd3c46d3b/channels/in.m3u#L166-L167
> - [x] [Cartoon Network India](https://www.cartoonnetworkindia.com/)
> https://github.com/iptv-org/iptv/blob/08123cd12385dbb75c993a850edaf0f05e7c341e/channels/in.m3u#L86-L87
> - [x] [Zee TV](https://en.wikipedia.org/wiki/Zee_TV)
> https://github.com/iptv-org/iptv/blob/e402372f306226c3c274931832f71e701594ece7/channels/in.m3u#L112-L113
> - [ ] [Colors TV](https://www.colorstv.com/mena/)

Not working

**Comment by tanvir8282** [comment]
> I think I found some of the channel
> Disney Channel Hindi
> http://stream-7b694ce7e.nmbs.top/m3u/Kids/c86abe8bd6.m3u8
> Cartoon Network Hindi
> http://stream-7b694ce7e.nmbs.top/m3u/Kids/1e0a653ba1.m3u8
> Marvel HQ
> http://stream-7b694ce7e.nmbs.top/m3u/Kids/c9878efeae.m3u8
> Hungama TV
> http://stream-7b694ce7e.nmbs.top/m3u/Kids/85a27ab7bf.m3u8

Update new link please

**Comment by mehedi-18082001** [comment]
I would like to see the link for Star Jalsha.

**Comment by Achu2234** [comment]
Sir All links you send here are not working

**Comment by Achu2234** [comment]
Sir All links you send here are not working

**Comment by Riteshsir** [comment]
> I think I found some of the channel Disney Channel Hindi http://stream-7b694ce7e.nmbs.top/m3u/Kids/c86abe8bd6.m3u8 Cartoon Network Hindi http://stream-7b694ce7e.nmbs.top/m3u/Kids/1e0a653ba1.m3u8 Marvel HQ http://stream-7b694ce7e.nmbs.top/m3u/Kids/c9878efeae.m3u8 Hungama TV http://stream-7b694ce7e.nmbs.top/m3u/Kids/85a27ab7bf.m3u8

How can we stream these links

**Comment by dacait01** [comment]
need new links. not working.

**Comment by dheer99** [comment]
Please can someone update the links, these are not working anymore.
thanks

**Comment by anil-s-yadav** [comment]
> It would be nice if you add Disney Hindi, Marvel HQ, Hungama, Cartoon Network Hindi, Zee TV, Colors in your playlist. Thanks for keeping this maintained and free :D.

I have m3u8 link for colors -  "https://prod-sports-north-gm.jiocinema.com/bpk-tv/Colors_HD_voot_MOB/Fallback/index.m3u8" 100% working.

**Comment by Kingston8881** [comment]
> > It would be nice if you add Disney Hindi, Marvel HQ, Hungama, Cartoon Network Hindi, Zee TV, Colors in your playlist. Thanks for keeping this maintained and free :D.
> 
> I have m3u8 link for colors - "https://prod-sports-north-gm.jiocinema.com/bpk-tv/Colors_HD_voot_MOB/Fallback/index.m3u8" 100% working.

Can you pls give hungama tv bufferless m3u or m3u8 playlist

**Comment by josephjjoe** [comment]
Please fix this channel issue it comes daily and hungama channel link is not working on livenettv apk

**Comment by josephjjoe** [comment]
Perman epsiode timing Hungama tv channel india link is not working  on Livenettv apk please try to fix this network issue fast

**Comment by sabujm1** [comment]
https://d75dqofg5kmfk.cloudfront.net/bpk-tv/Andtvhd/default/andtvhd-audio_208482_und=208000-video=4237600.m3u8

and tv 2024 link

https://d75dqofg5kmfk.cloudfront.net/bpk-tv/Andpictureshd/default/andpictureshd-audio_208482_und=208000-video=4237600.m3u8

andpicture link 2024

**Comment by siddhant8523** [comment]
anybody have link for sony yay !

**Comment by dheer99** [comment]
Sony Yay
https://dai.google.com/ssai/event/40H5HfwWTZadFGYkBTqagg/master.m3u8

**Comment by Gauravishra** [comment]
Can Anyone Have Cartoon Hungama Tv Link

**Comment by MinorX** [comment]
> Can Anyone Have Cartoon Hungama Tv Link

Did you find any? I want it too

**Comment by Stupidanoynomous** [comment]
Hey can anyone find Disney channel hd india m3u8 link I really need it

**Comment by yashrajxchopra** [comment]
Any one got working Hungama tv link?

**Comment by JohnMathews223** [comment]
> I think I found some of the channel Disney Channel Hindi http://stream-7b694ce7e.nmbs.top/m3u/Kids/c86abe8bd6.m3u8 Cartoon Network Hindi http://stream-7b694ce7e.nmbs.top/m3u/Kids/1e0a653ba1.m3u8 Marvel HQ http://stream-7b694ce7e.nmbs.top/m3u/Kids/c9878efeae.m3u8 Hungama TV http://stream-7b694ce7e.nmbs.top/m3u/Kids/85a27ab7bf.m3u8

How can I watch the channels on pc?

**Comment by bhupesh05** [comment]
None work waste of energy

**Comment by adapala-akshay** [comment]
Bro any add new links with all languages I want hindi,telugu

**Comment by mahmadch22-cpu** [comment]
D

**Comment by waifuwows** [comment]
this was working - http://iptvcasomsapi.jprdigital.in/x-media/C0408/master.m3u8
