### ISSUE TITLE
Replace: TF1

### ISSUE THREAD

**Issue by kikar92** [iptv-org/iptv#8554]
### Channel ID

TF1.fr

### Notes

The channel stopped working few weeks ago can any one help thank you for you updating the channels to stay working.

Regards. 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Reference:
https://github.com/iptv-org/iptv/blob/c662ef7b63497ffbddcdaf8728fcda82ab1bec86/streams/fr.m3u#L168-L169

**Comment by LaneSh4d0w** [comment]
Since another post was made and link found, closing this one.
