### ISSUE TITLE
Add: KTOP

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8560]
### Channel ID

KTOP.us

### Stream URL

https://cdn3.wowza.com/5/cHYzekYzM2kvTVFH/oakland/G0219_002/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://cdn3.wowza.com/5/cHYzekYzM2kvTVFH/oakland/G0219_002/playlist.m3u8
