### ISSUE TITLE
Add: EWTN Canada

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8566]
### Channel ID

EWTNCanada.ca

### Stream URL

https://cdn3.wowza.com/1/YW5wSWZiRGd2eFlU/bGV0aVBq/hls/whb7tbvs/448/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
[Already Done](https://github.com/iptv-org/iptv/blob/c3ecac33aa203ee4d1ebaf4441677cfaf74fcd25/channels/us.m3u~master#L689-L690)
