### ISSUE TITLE
Add: ABS TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8567]
### Channel ID

ABSTV.ag

### Stream URL

https://cdn001.tegotv.com/liveabr/Live_TV~ABS_Television~ABS_TV/live/Live_TV~FHD~854~ABS_TV_480p/chunks_dvr_timeshift-0-7200.m3u8?nimblesessionid=7507491&wmsAuthSign=c2VydmVyX3RpbWU9OS83LzIwMjIgMTowNjo1NSBBTSZoYXNoX3ZhbHVlPVFUczFkUnFnU3grM3A0QjRmMng1TGc9PSZ2YWxpZG1pbnV0ZXM9MTIwJmlkPTI0MjM1MTY0OTQ=

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Tokenized.

**Comment by nadeembhutta1968** [comment]
> ### Channel ID
> ABSTV.ag
> 
> ### Stream URL
> https://cdn001.tegotv.com/liveabr/Live_TV~ABS_Television~ABS_TV/live/Live_TV~FHD~854~ABS_TV_480p/chunks_dvr_timeshift-0-7200.m3u8?nimblesessionid=7507491&wmsAuthSign=c2VydmVyX3RpbWU9OS83LzIwMjIgMTowNjo1NSBBTSZoYXNoX3ZhbHVlPVFUczFkUnFnU3grM3A0QjRmMng1TGc9PSZ2YWxpZG1pbnV0ZXM9MTIwJmlkPTI0MjM1MTY0OTQ=
> 
> ### Notes
> _No response_
> 
> ### Please confirm the following
> * [x]  I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/cac2f96962f43fcec08d835b0878ed36307d4bbe/streams/ag.m3u#L2-L3
