### ISSUE TITLE
looking uk and pakistani channels

### ISSUE THREAD

**Issue by mike1566** [iptv-org/iptv#857]
looking uk premium and more pakistani channels.
any chance to get it?

**Comment by freearhey** [comment]
please specify which channels you mean.

**Comment by mike1566** [comment]
skyuk sports,movies,kids,
n pakistani regional channels like hum tv package,ptv sports,geo super,

**Comment by alibakali987** [comment]
Tankssßsssssssssssssssssd

**Comment by sikandarkk** [comment]
I also need Pakistsni Iptv channels urls?

**Comment by haseebsaif** [comment]
Any update on this? Planning to watch PSL on PTV SPORTS but no channel found yet.

Does anyone know which channel is streaming it live?

**Comment by freearhey** [comment]
**UK:**
- [x] Sky
https://github.com/iptv-org/iptv/blob/b4c6df922733fac50d36f58b615909dca12e7470/channels/uk.m3u#L282-L305

**Pakistani:**
- [ ] [HUM TV](https://www.hum.tv/)
- [ ] [PTV Sports](https://en.wikipedia.org/wiki/PTV_Sports)
- [x] Geo Super
https://github.com/iptv-org/iptv/blob/591cc5e071007b0fb2c93449061eae5f83e5fdca/channels/pk.m3u#L48-L49

**Comment by mike1566** [comment]
hi Aleksandr Statciuk.
thanks for reply.i am getting a massage in uk streams.
(OOPS Limit reached u r using maximum number of connsction.)
can u pls solve it.thanks in advance

**Comment by freearhey** [comment]
Yes, I see the same message as you and this is why the links to these channels have been removed. And unfortunately I can't do anything about it until there's a replacement.

**Comment by mike1566** [comment]
hi thanks for your efforts.
pls update us.if something is new here.thanks

**Comment by mike1566** [comment]
Any Chance To Get It?

**Comment by freearhey** [comment]
@mike1566 Do you mean the `Hum TV` and `Geo Super` channels?

**Comment by loveyoursupport** [comment]
@freearhey  Yes `Hum TV` `Duniya News` `ARY TV and News` `GEO TV and News` and `PTV TV and News` , we really appreciate your efforts. thank you

**Comment by freearhey** [comment]
@loveyoursupport Added to the list (#1973)

**Comment by loveyoursupport** [comment]
@freearhey  thank you very much! :+1:
