### ISSUE TITLE
Add: Bay Voice TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8571]
### Channel ID

BayVoiceTV.us

### Stream URL

https://reflect-creatv.cablecast.tv/live-19/live/CELL-496k-270p/CELL-496k-270p.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://reflect-channel27-creatv.cablecast.tv/live/live.m3u8
