### ISSUE TITLE
Add: 3ABN French

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8576]
### Channel ID

3ABNFrench.us

### Stream URL

https://3abn-live.akamaized.net/hls/live/2010546-b/French/LQs/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://3abn-live.akamaized.net/hls/live/2010546/French/master.m3u8
https://3abn-live.akamaized.net/hls/live/2010546-b/French/master.m3u8 alt
