### ISSUE TITLE
Add: 3ABN Kids

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8577]
### Channel ID

3ABNKids.us

### Stream URL

https://3abn-live.akamaized.net/hls/live/2010550-b/Kids/LQs/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by thihazawsatellite** [comment]
thank

**Comment by AntiPontifex** [comment]
You're welcome

**Comment by LaneSh4d0w** [comment]
https://3abn-live.akamaized.net/hls/live/2010550-b/Kids/master.m3u8
