### ISSUE TITLE
albanian channels

### ISSUE THREAD

**Issue by BekimH** [iptv-org/iptv#858]

**Comment by freearhey** [comment]
Please specify channel names.

**Comment by radion1226** [comment]
Can I get Albania channel code

**Comment by radion1226** [comment]
Super sport 1
Super sport 2
Super sport 3
Super sport 4
Super sport 5

**Comment by aesywind** [comment]
Can I continue wishing channels here or make a new request!

**Comment by freearhey** [comment]
@aesywind If it is about Albanian channels, you can leave the list here.

**Comment by aesywind** [comment]
I'll get back at you with one long list :D

Den tors 20 feb. 2020 kl 12:33 skrev Aleksandr Statciuk <
notifications@github.com>:

**Comment by Nintendocustom** [comment]
Bang Bang would be great.

**Comment by freearhey** [comment]
- [ ] [Bang Bang](https://www.lyngsat.com/tvchannels/al/Bang-Bang.html)
- [x] SuperSport 1
https://github.com/iptv-org/iptv/blob/b7269ee3c822b44c2bbe45aa6a12c4725a46949a/channels/al.m3u#L52-L53
- [x] SuperSport 2
https://github.com/iptv-org/iptv/blob/b7269ee3c822b44c2bbe45aa6a12c4725a46949a/channels/al.m3u#L54-L55
- [x] SuperSport 3
https://github.com/iptv-org/iptv/blob/b7269ee3c822b44c2bbe45aa6a12c4725a46949a/channels/al.m3u#L56-L57
- [x] SuperSport 4
https://github.com/iptv-org/iptv/blob/b7269ee3c822b44c2bbe45aa6a12c4725a46949a/channels/al.m3u#L58-L59
- [x] SuperSport 5
https://github.com/iptv-org/iptv/blob/b7269ee3c822b44c2bbe45aa6a12c4725a46949a/channels/al.m3u#L60-L61

**Comment by themak1985** [comment]
Closing for now. Feel free to open a new issue for Bang Bang if you would like.
