### ISSUE TITLE
Replace: AMCEast.us (and AMC+)

### ISSUE THREAD

**Issue by hijuuijj** [iptv-org/iptv#8585]
### Broken Link

https://bcovlive-a.akamaihd.net/ebf15ff84e98490e8b00209ed77c77f5/us-east-1/6240731308001/playlist.m3u8

### What happened to the stream?

Not loading

### Notes

These streams need to be updated.

AMC East
https://bcovlive-a.akamaihd.net/ebf15ff84e98490e8b00209ed77c77f5/us-east-1/6240731308001/playlist.m3u8

AMC+
https://bcovlive-a.akamaihd.net/bdbdca51c15243fbaca92fd54c42d45a/us-east-1/6245817279001/playlist.m3u8

BTW what is the website of the first link? I can't find the live stream on AMC.com.
I'm also trying to use the 7 days trial in order to access AMC+ but I'm having problems with the VPN.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
https://bcovlive-a.akamaihd.net/ebf15ff84e98490e8b00209ed77c77f5/us-east-1/6240731308001/playlist.m3u8
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/7253922/189232438-62aa055c-8477-436f-8c1c-257dabd48ca4.png">

**Comment by hijuuijj** [comment]
> https://bcovlive-a.akamaihd.net/ebf15ff84e98490e8b00209ed77c77f5/us-east-1/6240731308001/playlist.m3u8 <img alt="image" width="1426" src="https://user-images.githubusercontent.com/7253922/189232438-62aa055c-8477-436f-8c1c-257dabd48ca4.png">

Did you wait 18 seconds?

**Comment by hijuuijj** [comment]
Closed? now allowed? I got these links from your US list.
