### ISSUE TITLE
Replace: AMC East

### ISSUE THREAD

**Issue by hijuuijj** [iptv-org/iptv#8586]
### Broken Link

https://bcovlive-a.akamaihd.net/ebf15ff84e98490e8b00209ed77c77f5/us-east-1/6240731308001/playlist.m3u8

### What happened to the stream?

Shows looped video

### Notes

Looped video/Not live

AMC East
https://bcovlive-a.akamaihd.net/ebf15ff84e98490e8b00209ed77c77f5/us-east-1/6240731308001/playlist.m3u8

AMC+
https://bcovlive-a.akamaihd.net/bdbdca51c15243fbaca92fd54c42d45a/us-east-1/6245817279001/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Reference:
https://github.com/iptv-org/iptv/blob/b421bdcba1d09134efda602a881cf11c759bac06/streams/us.m3u#L97-L98

**Comment by spotanjo3** [comment]
Watch it for 18 seconds then it stopped. Use VLC and any players too.

**Comment by Alstruit** [comment]
Closing in favor #10476
