### ISSUE TITLE
Add: WHPS-CD

### ISSUE THREAD

**Issue by Arkina1234** [iptv-org/iptv#8590]
### Channel ID

N/A

### Stream URL

https://hls-live-web-media.cdn01.net/default/stream_46366.m3u8?W7wkfkuim-jVrxU8_3ed4t1CfW8s-GvXq-o0hbKOrLgQUruy7i9OsAdaHQU-rDP4_8pGylYlDkBheaqBo7Wr-KQD3KqWeSeG4ur3jS-rOJ9NU77Hl8fK9E6IRG1sTmjl4erzgjLRFsXxaLbFEAyACrt1sq78y8cRxN9pyJ_O&channel_id=46366&source=Android&old_source=othermobile&device_id=8221657492-5b333415983b5e4478227c9aa1632c6b&lcp=2&play_id=1662709776879823

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
The link is tokened, though I don't have much time to allocate on making a streamlink plugin for it.

**Comment by freearhey** [comment]
@Arkina1234 There are several channels with this callsign: https://iptv-org.github.io/?q=WHPS. Please specify which one you are talking about.
