### ISSUE TITLE
Add: Advocate Broadcasting Network

### ISSUE THREAD

**Issue by booziebatsymbol** [iptv-org/iptv#8599]
### Channel ID

AdvocateBroadcastingNetwork.ng

### Stream URL

https://www.lyngsat-stream.com/tvchannels/ng/Advocate-Broadcasting-Network.html

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/abntvng
