### ISSUE TITLE
Add: Channels TV

### ISSUE THREAD

**Issue by booziebatsymbol** [iptv-org/iptv#8600]
### Channel ID

ChannelsTV.ng

### Stream URL

https://www.youtube.com/watch?v=-c8LoR84Xjs&ab_channel=ChannelsTelevision

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/ChannelsTelevision/live

Lucky you both streams are the same.
