### ISSUE TITLE
Add: Silverbird TV

### ISSUE THREAD

**Issue by booziebatsymbol** [iptv-org/iptv#8602]
### Channel ID

SilverbirdTV.ng

### Stream URL

https://silverbirdtv.com/live/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://dai.ly/x81uq2d

**Comment by Alstruit** [comment]
https://www.dailymotion.com/video/x81uq2d
