### ISSUE TITLE
Add: TVC Entertainment

### ISSUE THREAD

**Issue by booziebatsymbol** [iptv-org/iptv#8603]
### Channel ID

TVC.ng

### Stream URL

https://www.tvcentertainment.tv/livestream/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://tvce.gridpapaservers.com/TVCSEPT/ngrp:myStream_all/playlist.m3u8
