### ISSUE TITLE
Add: Wazobia Max TV Nigeria

### ISSUE THREAD

**Issue by booziebatsymbol** [iptv-org/iptv#8605]
### Channel ID

WazobiaMaxTVNigeria.ng

### Stream URL

https://www.wazobiamax.ng/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://wazobia.live:8333/channel/wmax.m3u8 Nigeria
https://wazobia.live:8333/channel/wmaxabuja.m3u8 Abuja
https://wazobia.live:8333/channel/wmaxph.m3u8 Port-Harcourt
