### ISSUE TITLE
Add: Wap TV

### ISSUE THREAD

**Issue by booziebatsymbol** [iptv-org/iptv#8607]
### Channel ID

WapTV.ng

### Stream URL

https://waptvchannel.com/live-tv-2/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://newproxy3.vidivu.tv/waptv/index.m3u8
