### ISSUE TITLE
Replace: CNN

### ISSUE THREAD

**Issue by randomguyfromAustria** [iptv-org/iptv#8610]
### Broken Link

https://iptv-org.github.io/iptv/countries/us.m3u

### What happened to the stream?

Other

### Possible Replacement

https://tve-live-lln.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_0_3564000.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Already in playlist : https://github.com/iptv-org/iptv/blob/6d22f2373a7af0472d20dcf62e0ada250c83789a/streams/us.m3u#L287-L288
