### ISSUE TITLE
Replace: BBC America

### ISSUE THREAD

**Issue by Smark223** [iptv-org/iptv#8611]
### Broken Link

https://bcovlive-a.akamaihd.net/8e64fad5ddbe4d3e95b23b0f9c062f03/us-east-1/6240731308001/playlist.m3u8

### What happened to the stream?

Shows looped video

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Reference:
https://github.com/iptv-org/iptv/blob/6e515bdba0c6e9b8ad99cf5e30a9b1c584ceb79d/streams/us.m3u#L123-L124

**Comment by jbtech1980** [comment]
It appears that several stations streaming recently have been pulled off free access and moved to "paid" groups. Thus far, noticed the following channels being impacted: MeTV, Cozi, ABC7NY and BBC America...

**Comment by Smark223** [comment]
https://bcovlive-a.akamaihd.net/c9bf201b06694453bb29282f97191f58/us-east-1/6240731308001/playlist.m3u8

Thanks to @what-a from a reply in #8612

**Comment by spotanjo3** [comment]
It doesnt work. Another link please?
