### ISSUE TITLE
Replace: Sundance East

### ISSUE THREAD

**Issue by Smark223** [iptv-org/iptv#8612]
### Broken Link

https://bcovlive-a.akamaihd.net/d2fcbeaead4b425fa13d4fec961fc47a/us-east-1/6240731308001/playlist.m3u8

### What happened to the stream?

Shows looped video

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Reference:
https://github.com/iptv-org/iptv/blob/6e515bdba0c6e9b8ad99cf5e30a9b1c584ceb79d/streams/us.m3u#L864-L865

**Comment by Smark223** [comment]
> https://bcovlive-a.akamaihd.net/4d972ec6f41241f2b4286f8bdcc8dae9/us-east-1/6240731308001/playlist.m3u8

That's great, thanks! Do you have similar new links for BBC America and AMC or are they now behind some sort of paywall/login authentication?

**Comment by what-a** [comment]
BBC America
https://bcovlive-a.akamaihd.net/c9bf201b06694453bb29282f97191f58/us-east-1/6240731308001/playlist.m3u8

I've yet to find AMC.

**Comment by dtngfan85** [comment]
Once again, you are pointlessly responding to tickets from 4 years ago. They already know it's dead, that's why it's no longer in the playlists.
