### ISSUE TITLE
Replace: IFC East

### ISSUE THREAD

**Issue by Smark223** [iptv-org/iptv#8613]
### Broken Link

https://bcovlive-a.akamaihd.net/070ffdaa203f439cacbf0d45a1ddb356/us-east-1/6240731308001/playlist.m3u8

### What happened to the stream?

Shows looped video

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Reference:
https://github.com/iptv-org/iptv/blob/6e515bdba0c6e9b8ad99cf5e30a9b1c584ceb79d/streams/us.m3u#L486-L487

**Comment by Smark223** [comment]
Fixed under #10475
