### ISSUE TITLE
Add: Trust TV

### ISSUE THREAD

**Issue by booziebatsymbol** [iptv-org/iptv#8614]
### Channel ID

TrustTV.ng

### Stream URL

https://trusttv.com/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCTlqstA2Wrt4fimd_VWKr8g/live
