### ISSUE TITLE
Replace: AMC+

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#8615]
### Broken Link

https://bcovlive-a.akamaihd.net/bdbdca51c15243fbaca92fd54c42d45a/us-east-1/6245817279001/playlist.m3u8

### What happened to the stream?

Shows looped video

### Notes

Original request: #8586

Reference: https://github.com/iptv-org/iptv/blob/c662ef7b63497ffbddcdaf8728fcda82ab1bec86/streams/us.m3u#L1301-L1302

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Dead issue: please close.
