### ISSUE TITLE
Add: Noticias Caracol Ahora

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#8617]
### Channel ID

NoticiasCaracolAhora.co

### Stream URL

https://mdstrm.com/live-stream-playlist_800/58dc3d471cbe05ff3c8e463e.m3u8

### Notes

Original request: #8517

https://www.youtube.com/c/noticiascaracol
https://noticias.caracoltv.com/ahora

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://mdstrm.com/live-stream-playlist/58dc3d471cbe05ff3c8e463e.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/bd10e51f909afb926138c59ed38d195131d389b3/streams/co.m3u#L124-L125
