### ISSUE TITLE
Add: TCT HD [24/7] | (US)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8620]
### Channel ID

TCTHD.us

### Stream URL

https://livestreamapis.com/v3/accounts/29565692/events/9276365/master.m3u8?token=9bfa600cf944aae6abaf595ca9051502&clientId=18436&timestamp=1662762442478

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://api.new.livestream.com/accounts/29565692/events/9276365/
