### ISSUE TITLE
Add: TCT KIDS [24/7] | (US)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8621]
### Channel ID

TCTKids.us

### Stream URL

https://livestreamapis.com/v3/accounts/29565692/events/9321713/master.m3u8?token=163b3c3c1c23fcc3d2517b11e83d723a&clientId=18436&timestamp=1662762649658

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://api.new.livestream.com/accounts/29565692/events/9321713
