### ISSUE TITLE
Add: Positiv

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8622]
### Channel ID

PositivTV.us

### Stream URL

https://tbn-jw.cdn.vustreams.com:443/live/positivtv/live.isml/live-audio_1=128000-video=2800000.m3u8 / https://tbn-jw.cdn.vustreams.com/live/positivtv/live.isml/952dda4a-bfff-407c-803d-000271d853b4.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://tbn-jw.cdn.vustreams.com/live/positivtv/live.isml/playlist.m3u8
