### ISSUE TITLE
Add: PCCtv

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8626]
### Channel ID

PCCtv.us

### Stream URL

https://pasadenamed.secure.footprint.net/egress/bhandler/pasadenamed/streamc/chunklist_b1192000.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://pasadenamed.secure.footprint.net/egress/bhandler/pasadenamed/streamc/playlist.m3u8
