### ISSUE TITLE
Please add some Algerian channels

### ISSUE THREAD

**Issue by Adam770** [iptv-org/iptv#863]

**Comment by freearhey** [comment]
Please specify channel names.

**Comment by Adam770** [comment]
Canal Algerie
Algerie 3
Ennahar TV
El Chourouk TV
El Chourouk News
Bahia TV
Algerie 5
Algerie 4
ENTV (Programme National)

**Comment by themak1985** [comment]
@Adam770 - With the exception of Bahia TV and ENTV - I added those channels to the list of channels I can stream - but cannot get a working / non-expiring link for: #758 

If you can figure out the links - that would be great.

**Comment by freearhey** [comment]
Canal Algérie:
https://github.com/iptv-org/iptv/blob/fd9752a9f09931f8a52342f97503430dd3c46d3b/channels/dz.m3u#L2-L3

**Comment by abourakba** [comment]
Hello Guys, 
Any Update on issues ?

**Comment by freearhey** [comment]
- [x] Canal Algerie
https://github.com/iptv-org/iptv/blob/62344f036a5676c81b438620853267cf9d53954e/channels/dz.m3u#L2-L3
- [x] Algerie 3 (Thalitha A3)
https://github.com/iptv-org/iptv/blob/167c23cd54e956f6c58375219ed42875bc9ca1ab/channels/dz.m3u#L10-L11
- [ ] [Algerie 4](https://www.lyngsat.com/tvchannels/dz/TV-4-Amazigh.html) (TV 4 Amazigh)
- [ ] [Algerie 5](https://www.lyngsat.com/tvchannels/dz/TV-5-Coran.html) (TV 5 Coran)
- [x] Ennahar TV
https://github.com/iptv-org/iptv/blob/62344f036a5676c81b438620853267cf9d53954e/channels/dz.m3u#L6-L7
- [x] Echorouk TV
https://github.com/iptv-org/iptv/blob/167c23cd54e956f6c58375219ed42875bc9ca1ab/channels/dz.m3u#L12-L13
- [x] Echorouk News
https://github.com/iptv-org/iptv/blob/167c23cd54e956f6c58375219ed42875bc9ca1ab/channels/dz.m3u#L14-L15
- [x] Bahia TV
https://github.com/iptv-org/iptv/blob/167c23cd54e956f6c58375219ed42875bc9ca1ab/channels/dz.m3u#L16-L17

**Comment by Sphinxroot** [comment]
tv-coran
https://edge-06.playmedia-cdn.net/origin02/amlst:tv-coran/chunklist_w765057915_b800000.m3u8?dar=sd&t=18ddf1b11ff0fbb27659a265b39d1126e87976e154f18fe11a37cc6daf22d9857e100ea6d80a4d02496154f6455788c41fbc927e7ed3c14be34e67e471bc0c8c8567cb9d56b2139a58459f4c7bc68d6c6fd20f5ebf0b024c69ebefdb676c164bd6095882b1aa7f8c0e054f1927153c376b3ad9728fabcca97a1f5231ab08caba2e0f0e089194a698b425d7124bee5acaa1e515b9a19ca5f1b3a97bb8dca899cb48504aa77fe3d14529a47d273048284c


Tamazight TV4
https://edge-05.playmedia-cdn.net/origin02/amlst:tv-tamazight/chunklist_w667077625_b800000.m3u8?dar=sd&t=18ddf1b11ff0fbb27659a265b39d1126b5261f45b785f0cd747bde46fbc52daa33fec832db4b8bf14edc0288295d3009708dcfc7b6e9545b88682e1086164a8261936741a4383801b8597e395b2127fcf492a228e600edd099a26d42dfed39436abc59e88bb8ecfafb83e5934d63a998cfb31c83bb8c2c651a92bba62a505e719eca7ee9e76ea7db8e46649088e1bb2b6c3bd6cfbfeb96372bc91239772060ca500e4906162b8a32245b2908f23b3375bd45bce2c852cdc0

Canal Algerie
https://edge-05.playmedia-cdn.net/origin02/amlst:canal-algerie/chunklist_w741041138_b800000.m3u8?dar=sd&t=18ddf1b11ff0fbb27659a265b39d1126b5261f45b785f0cd747bde46fbc52daa33fec
832db4b8bf14580367f28dbdb6a043b13d93eab15264cd53fa8889a6e26ef134db0cffc6526660
380bb1b8c9c6be36d18cb16c256ed0b7966a3ec820b215f6c240a4ecc8a864fe2573c23e6d828a
4e5c2d5144bef3afd94c4f4667889a9a94ead0423ff4df2eb3879663253c6dbaba080e60027f1f
ce8cb69a2287b0c8d946055bb43a29dd295e7e28d369346f5628d0b90a55dc6a5

**Comment by abourakba** [comment]
Thank you @freearhey @Sphinxroot !

**Comment by Sphinxroot** [comment]
AR-الوطن,AR:Watan TV,Watan TV
http://watantv.origin.technostreaming.net:8081/watantv_source2/live/chunks.m3u8
Canal Algérie
http://178.132.3.162:88/canal_algerie/video.m3u8?token=test

**Comment by freearhey** [comment]
Closed in favor #1961

**Comment by akramex-dz** [comment]
ENTV is crucial to watch sport event, can anyone help with that ?
