### ISSUE TITLE
Add: America Tucuman

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8630]
### Channel ID

AmericaTucuman.ar

### Stream URL

https://youtu.be/UcQRYiWPJtY

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/AmericaTucuman/live
