### ISSUE TITLE
Add: Barricada TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8631]
### Channel ID

BarricadaTV.ar

### Stream URL

https://live-ak.vimeocdn.com/exp=1662689801~acl=%2Fa6918eec-6492-4bcd-8e70-77f409a8afc0%2F%2A~hmac=2a24e7d6e03cb6b4adc02037ffdfe88b6aa612ca42d702713143b34a30773cef/a6918eec-6492-4bcd-8e70-77f409a8afc0/chunklist_b2056000.m3u8?max_segments=10

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://player.vimeo.com/video/748214742

**Comment by Alstruit** [comment]
Reference: https://www.barricadatv.org/?page_id=9173
