### ISSUE TITLE
Add: KLRN

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8632]
### Channel ID

KLRN.us

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://klrndt.lls.pbs.org/out/v1/2fe877a725bd4b6aaacba3a4cc54ae12/dash-drm.mpd DRMd
