### ISSUE TITLE
Add: Canal 10 Mar del Plata

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8636]
### Channel ID

Canal10MardePlata.ar

### Stream URL

https://g1.mc-hor.transport.edge-access.net/a15/ngrp:canal10mdq-100044_all/canal10mdq-100044_360p.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://g1.mc-hor.transport.edge-access.net/a15/ngrp:canal10mdq-100044_all/playlist.m3u8

should work with the iPhone user-agent set up.
