### ISSUE TITLE
Add: Canal10 Tucuman

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8637]
### Channel ID

Canal10Tucuman.ar

### Stream URL

https://cdntvstrm.s.llnwi.net/e1/livesec/canal10tuc.stream/chunklist.m3u8?e=1662814869&h=962bc753986b2e73abffcb2a072e6c78

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Tokened.
