### ISSUE TITLE
Add: VTN / Victory Television Network

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8638]
### Channel ID

KVTNDT1.us

### Stream URL

https://api.new.livestream.com/accounts/15669040/events/4554297/broadcasts/232863013.secure.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
KVTNDT1.us for the ID

**Comment by R4IN2007** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://api.new.livestream.com/accounts/15669040/events/4554297
