### ISSUE TITLE
Add: KBS Korea

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8641]
### Channel ID

KBSKorea.kr

### Stream URL

https://m.youtube.com/watch?v=HnfpTMtfFk8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/kbsworldtv/live

First time I see that channel up. Is it new ?
