### ISSUE TITLE
Add: Animax Asia (Indonesian Subtitles)

### ISSUE THREAD

**Issue by AzeemHadzrie** [iptv-org/iptv#8643]
### Channel ID

AnimaxAsia.sg

### Stream URL

https://liveanevia.mncnow.id/live/eds/Animax/sa_dash_vmx/Animax.mpd

### Notes

Needs license key: https://mrpw.ptmnc01.verspective.net/?deviceId=NjcwYWI2ZGEtYzE4Yi0zZWFlLTljOWYtZGEzOGIwYWFjN2I1

Found a MNC Vision feed, works with Native MPEG-DASH - HLS Playback

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Sadly this is not a channel we can put since it's DRMd, and that the information isn't inside the link. Most of the media players do not have DRM decryption systems. AFAIK only Kodi and this web extension has got it.

**Comment by bbbureneecartoonz** [comment]
> Sadly this is not a channel we can put since it's DRMd, and that the information isn't inside the link. Most of the media players do not have DRM decryption systems. AFAIK only Kodi and this web extension has got it.

pcs don't have drmed streams?

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/cac2f96962f43fcec08d835b0878ed36307d4bbe/streams/vn_fptplay.m3u#L2-L7

**Comment by LaneSh4d0w** [comment]
@freearhey the proposed stream is with Indonesian subs, not Vietnamese ones.

**Comment by freearhey** [comment]
Sorry, my mistake.

**Comment by freearhey** [comment]
Closing for now. 

If you find a working link without DRM protection, you can add it directly to the playlist via [pull request](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#pull-request-guidelines).
