### ISSUE TITLE
Add: Telediario I TdTV [AR]

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8660]
### Channel ID

Canal13.ar

### Stream URL

https://mediacp.hostradios.com.ar:19360/telediario/telediario.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
I think the ID for that stream is incorrect. Here is the website for reference.
https://telediariotelevision.com.ar/en-vivo/

**Comment by Alstruit** [comment]
Already exists: 8b5b201f3302c4cfe1356f6b193ac958f9a15c92.
