### ISSUE TITLE
Add: Live from Coyote Radio

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8666]
### Channel ID

CoyoteRadio.us

### Stream URL

http://axis1.csusb.edu/axis-cgi/mjpg/video.cgi?resolution=640x480&dummy=1662856804649

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
This doean't appear to be a valid m3u8. The stream doesn't have audio. Closing.
