### ISSUE TITLE
Add: 3ABN Russia

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8674]
### Channel ID

3ABNRussia.ru

### Stream URL

https://3abn-live.akamaized.net/hls/live/2010548/Russia/HQs/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Found an alternative stream
https://hls.tv.3angels.ru/stream.m3u8
