### ISSUE TITLE
Add: Cartoon network ukrain

### ISSUE THREAD

**Issue by bbbureneecartoonz** [iptv-org/iptv#8678]
### Channel ID

CartoonNetworkUkraine.ua

### Stream URL

http://saveukraine.only4.tv/802/video.m3u8?token=saveUkrain

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://saveukraine.only4.tv/802/video.m3u8?token=saveUkrain
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/7253922/190925267-162177be-4529-49e5-ae58-b658628693c6.png">
