### ISSUE TITLE
Some Chinese channel still not working in cn.m3u

### ISSUE THREAD

**Issue by kaifengw1501** [iptv-org/iptv#868]
Below channels still not working with the China ISP (China Unicom).Would you please update it ?

#EXTINF:-1 tvg-id="141" tvg-name="凤凰中文" tvg-language="Chinese" tvg-logo="" group-title="",凤凰中文HD
http://223.110.245.167/ott.js.chinamobile.com/PLTV/3/224/3221226922/index.m3u8
#EXTINF:-1 tvg-id="141" tvg-name="凤凰中文" tvg-language="Chinese" tvg-logo="" group-title="",凤凰中文HD
http://223.82.250.72/live/fhchinese/1.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Chinese" tvg-logo="" group-title="",凤凰卫视高清
http://221.179.217.70/PLTV/88888888/224/3221225942/1.m3u8
#EXTINF:-1 tvg-id="142" tvg-name="凤凰资讯" tvg-language="Chinese" tvg-logo="" group-title="",凤凰资讯
http://117.169.120.217:8080/live/fhzixun/.m3u8
#EXTINF:-1 tvg-id="142" tvg-name="凤凰资讯" tvg-language="Chinese" tvg-logo="" group-title="",凤凰资讯
http://183.207.249.35/PLTV/3/224/3221226923/index.m3u8
#EXTINF:-1 tvg-id="142" tvg-name="凤凰资讯" tvg-language="Chinese" tvg-logo="" group-title="",凤凰资讯HD
http://live.fengshows.com/live/PIN_500k/index.m3u8?ts=1534293674089&token=4b6d42d1074cfe540adbcbe0c1c34126
#EXTINF:-1 tvg-id="143" tvg-name="凤凰香港" tvg-language="Chinese" tvg-logo="" group-title="",凤凰香港
http://183.207.249.35/PLTV/3/224/3221226975/index.m3u8
#EXTINF:-1 tvg-id="143" tvg-name="凤凰香港" tvg-language="Chinese" tvg-logo="" group-title="",凤凰香港

**Comment by iswar1** [comment]
CCTV-1still not working

**Comment by freearhey** [comment]
@iswar1 Did you try this links? https://github.com/iptv-org/iptv/blob/fd9752a9f09931f8a52342f97503430dd3c46d3b/channels/cn.m3u#L38-L49
