### ISSUE TITLE
Add: TN (Todo Noticias)

### ISSUE THREAD

**Issue by JMVS** [iptv-org/iptv#8682]
### Channel ID

TNHD.ar

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/watch?v=wHn1_QVoXGM

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fotvnetwork** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/todonoticias/live
