### ISSUE TITLE
Add: A24

### ISSUE THREAD

**Issue by JMVS** [iptv-org/iptv#8684]
### Channel ID

A24HD.ar

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/watch?v=WIPjYtR2N6s

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fotvnetwork** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/A24com/live
