### ISSUE TITLE
Add: La Nación+

### ISSUE THREAD

**Issue by JMVS** [iptv-org/iptv#8685]
### Channel ID

LaNacionPlusHD.ar

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/watch?v=HlhZ0XZHHaw

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fotvnetwork** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/LaNacionMas/live
