### ISSUE TITLE
Add: KSHB-TV

### ISSUE THREAD

**Issue by dell3231** [iptv-org/iptv#8698]
### Channel ID

KSHBDT1.us

### Stream URL

http://user.scalecdn.co:8080/TVGlobe/41b2ec3fc3/89644

### Notes

This is the nbc affliate in the kansas city area

### Please confirm the following

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by dell3231** [comment]
Stream works

**Comment by Hitide2834** [comment]
How do we find the contact for http://user.scalecdn.co:8080
