### ISSUE TITLE
UK Channels 

### ISSUE THREAD

**Issue by khaldi777** [iptv-org/iptv#871]
is it possible to add more UK Channels on m3u
like >> Discovery, all sky Channels 
BBC 1,2 ,3, 4
Channel 4, and four7, National G
itv1, 2, 3, and 4 

thanks

**Comment by khaldi777** [comment]
thnXxX mate

**Comment by fireice240** [comment]
i cant see the link im a noob

**Comment by FXcodi** [comment]
I would also like to see links,
thanks

**Comment by sofianehamza** [comment]
how can we see the links?
thanks in advance

**Comment by nepalicana** [comment]
are these channels still available?

**Comment by J03lYuK** [comment]
Where is the link, thanks in advance

**Comment by freearhey** [comment]
- [x] Discovery
#EXTINF:-1 tvg-name="discovery.uk" tvg-id="discovery.uk" group-title="" tvg-logo="https://media.tv4.live/discovery.uk.png",Discovery UK
https://tv4.live/api/stream/fridrch4529@gmail.com/8u966/livetv.epg/discovery.uk.m3u8
- [x] Sky
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L296-L329
- [x] BBC 1
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L134-L135
- [x] BBC 2
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L136-L137
- [ ] BBC 3
- [x] BBC 4
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L138-L139
- [x] Channel 4
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L162-L163
- [x] 4seven
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L118-L119
- [x] National Geographic
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L266-L267
- [x] itv 1
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L228-L229
- [x] itv 2
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L230-L231
- [x] itv 3
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L232-L233
- [x] itv 4
https://github.com/iptv-org/iptv/blob/6a4d637cc70d0e7dbdfd799382205effa4e05592/channels/uk.m3u#L234-L235

**Comment by FXcodi** [comment]
No works this

**Comment by freearhey** [comment]
You're right. Unfortunately, none of the links are working anymore.

**Comment by freearhey** [comment]
Discovery Channel cannot be added to the playlist due to claims of the copyright holder. More details here: #1831

**Comment by freearhey** [comment]
Closed in favor #1943
