### ISSUE TITLE
Add: PBS 58 Create Los Angeles CA (KLCS-DT3)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8713]
### Channel ID

KLCSDT3.us

### Stream URL

https://d1mxoeplf1ak5a.cloudfront.net/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by benevenstanciano** [comment]
Geo-blocked

**Comment by freearhey** [comment]
https://d1mxoeplf1ak5a.cloudfront.net/index.m3u8
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/7253922/190889482-5538f9b0-ccc6-459e-84cf-e1ea372020da.png">
