### ISSUE TITLE
Add: Santa Barbara - CITY-TV 18

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8722]
### Channel ID

CityTVSantaBarbara.us

### Stream URL

https://youtu.be/7fqxe-6u6sY

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/Citytv18/live
