### ISSUE TITLE
Add: Canal 4 Posadas

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8726]
### Channel ID

Canal4Posadas.ar

### Stream URL

http://iptv.ixfo.com.ar:30443/live/C4POS/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
more like wss://iptv.ixfo.com.ar:30443/live/C4POS
