### ISSUE TITLE
Add: America's Auction Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8732]
### Channel ID

AmericasAuctionChannel.us

### Stream URL

https://youtu.be/qB2lqNq5oss

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/AACTelevision/live
