### ISSUE TITLE
Add: WHPS Detroit (WHPS-CD 2)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8737]
### Channel ID

WHPSCD2.us

### Stream URL

https://hls-live-web-media.cdn01.net/default/stream_46366.m3u8?IjzOecy0CCt7q4Vqr6cyFVvAk8IZD4OJ7brkfK3tUiUKmlRLxGce0gIxog76FLBYoZ2n3-4dMnCiwli0-KwSrv4FE-TMNpW-QXUWD_p8NROU3QYrwplxWjxAXKmzkJOkAz9cggFil4Rn-3dZr1SjNNAkKXu2tZkL5YpZWYZo&channel_id=46366&source=Android&old_source=othermobile&device_id=7877262621-8b7cfc18f04c477d897ef5eb929d2383&lcp=2&play_id=1663098903886043

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Tokened.

**Comment by LaneSh4d0w** [comment]
https://hls-live-media.cdn01.net/default/stream_46366.m3u8?source=othersites

**Comment by AntiPontifex** [comment]
Thank you for the stream; it will be included in the next update.

**Comment by freearhey** [comment]
https://hls-live-web-media.cdn01.net/default/stream_46366.m3u8?IjzOecy0CCt7q4Vqr6cyFVvAk8IZD4OJ7brkfK3tUiUKmlRLxGce0gIxog76FLBYoZ2n3-4dMnCiwli0-KwSrv4FE-TMNpW-QXUWD_p8NROU3QYrwplxWjxAXKmzkJOkAz9cggFil4Rn-3dZr1SjNNAkKXu2tZkL5YpZWYZo&channel_id=46366&source=Android&old_source=othermobile&device_id=7877262621-8b7cfc18f04c477d897ef5eb929d2383&lcp=2&play_id=1663098903886043 (offline)
<img width="835" alt="image" src="https://user-images.githubusercontent.com/7253922/232235119-2cb5ae2a-ab6c-405b-9101-6e6f97021541.png">

https://hls-live-media.cdn01.net/default/stream_46366.m3u8?source=othersites
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/7253922/232235158-1ca652d4-8094-4bac-96ae-cf50b66326f6.png">
