### ISSUE TITLE
Fox News/Fox Business (US)

### ISSUE THREAD

**Issue by acuaroyale** [iptv-org/iptv#874]
Both channels return "Invalid username/password"
m3u does not specify username/password

**Comment by freearhey** [comment]
Thank you for bringing this to our attention. I've already removed the broken links, but as soon as the replacement is available, we will return them.

**Comment by freearhey** [comment]
Done.
- [x] Fox News
https://github.com/iptv-org/iptv/blob/62344f036a5676c81b438620853267cf9d53954e/channels/us.m3u#L908-L909
- [x] Fox Business
https://github.com/iptv-org/iptv/blob/62344f036a5676c81b438620853267cf9d53954e/channels/us.m3u#L910-L911
