### ISSUE TITLE
Add: TVB Xing He (Chinese Subtitles) (720p)

### ISSUE THREAD

**Issue by AzeemHadzrie** [iptv-org/iptv#8742]
### Channel ID

TVBXingHe.hk

### Stream URL

http://123.253.32.125:9995/livestream/api/v1/long?channel_id=c20114 

### Notes

Found some URL

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
gets redirected to http://104.238.221.63:9138/stream/live/c20114.m3u8

**Comment by AzeemHadzrie** [comment]
There is the real link:

http://104.238.221.63:9138/stream/live/c20114.m3u8
