### ISSUE TITLE
Add: WBQP-CD

### ISSUE THREAD

**Issue by Arkina1234** [iptv-org/iptv#8761]
### Channel ID

WBQPCD1.us

### Stream URL

https://hls-live-web-media.cdn01.net/default/stream_46616.m3u8?wxiv5B5JgHYmOv5FWNr35eWYbr7koItMflv_qter2DvzVdNSJXoUTkRvxTsPJZs6ieVnxYHpEHop_AeS1qQqWQMt-DhPCqYCXRPtDMlUXIBsZ7ztDXvZnR_D-9Nq24z4jlTl_hBfxTkxcGutHm5DpDub1DiKvIMZ9eIu4mKa&channel_id=4661

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Tokened.

**Comment by Alstruit** [comment]
Reference: https://www.lightcast.com/embed/player.php?id=46616&type=live

**Comment by Sphinxroot** [comment]
@LaneSh4d0w 

https://hls-live-media.cdn01.net/default/stream_46616.m3u8?source=othersites

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w 
> 
> https://hls-live-media.cdn01.net/default/stream_46616.m3u8?source=othersites

Nice one @Sphinxroot didn't know we could do that.
