### ISSUE TITLE
Chanells request (Arabic channnels)

### ISSUE THREAD

**Issue by Kosay** [iptv-org/iptv#877]
Hi

There are some free Arabic channels
Al Jazeera Arabic 
[https://www.aljazeera.net/broadcastschedule](https://www.aljazeera.net/broadcastschedule)
Some Syrian TV (I found only one channel in the list) 
[http://www.ortas.online](http://www.ortas.online/)

Thank you

**Comment by freearhey** [comment]
I added "Al Jazeera Arabic" to the Qatari playlist. But for some reason I don't have to load the site http://www.ortas.online, so it would be great if you could specify the names of the Syrian channels in question.

**Comment by Kosay** [comment]
It is great if you add DramaTV
![download](https://user-images.githubusercontent.com/13199115/71779933-0c017280-2fbc-11ea-9e77-c9d46a63d284.jpeg)
I uploaded the logo because it is in Arabic

Thank you

**Comment by freearhey** [comment]
Drama TV is already on the Syrian playlist: https://github.com/iptv-org/iptv/blob/2df934cb5bb92afc4edee149cdae17e80ca88516/channels/sy.m3u#L6

**Comment by Kosay** [comment]
Yes I found it
I suggest to put it in group-title="Movies"

 #EXTINF:-1 tvg-id="Syria Drama ARB" tvg-name="Syria Drama ARB" tvg-language="Arabic" tvg-logo="https://i.imgur.com/ynwRIN4.png" group-title="Movies",Syria Drama

Also
DMC HD
DMC Drama
Dubai One

Change tvg-url="" to tvg-url="General" because when I use IPTV on android box it does not appear (it appears without any text icon 'empty')


EPG is the same for all channels tvg-url="http://195.154.221.171/epg/guidearab.xml.gz"

Thank you

**Comment by freearhey** [comment]
I added the missing group titles this time, but feel free to update the playlists yourself. Instructions on how to do this can be found here: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md
