### ISSUE TITLE
Add: Canal10 Tucuman

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8776]
### Channel ID

Canal10Tucuman.ar

### Stream URL

https://cdntvstrm.s.llnwi.net/e1/livesec/canal10tuc.stream/chunklist.m3u8?e=1663354020&h=e4aac11c7532298c2909e12715d3f3ea

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Tokened, though there's a JWPlayer plugin in Streamlink if I remember well...

**Comment by freearhey** [comment]
Duplicate #8637
