### ISSUE TITLE
Add: WGCL-TV

### ISSUE THREAD

**Issue by Arkina1234** [iptv-org/iptv#8777]
### Channel ID

WGCLDT1.us

### Stream URL

https://ad-playlistserver.aws.syncbak.com/cpl/20010010/dai2v5/1/7b2264657669636554797065223a2242726f77736572222c22616b616d61694d7670644b6579223a6e756c6c7d/master.m3u8?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjIwMTYwNDAxIn0.eyJkZXZpY2VUeXBlIjoiQnJvd3NlciIsInNpZCI6NzExLCJjaWQiOjIwNDcxLCJtaWQiOjIwMDEwMDEwLCJtayI6bnVsbCwib29tIjp0cnVlLCJpcCI6IjE1Ni4xNDYuNTEuMTMxIiwidWlwIjoiMTU2LjE0Ni41MS4xMzEiLCJkbWEiOjgxOSwic3NpZCI6IjM2MmU5MjJkNzUwZTQwNTNiZmE2YTVhZDE5ZGNjNmU3Iiwic24iOiJXZWIgNTE3ZDVlNTM4OSAoIG51bGwgKSIsInVpZCI6bnVsbCwiYXBzdCI6bnVsbCwic2JlcCI6ZmFsc2UsImNzYiI6ZmFsc2UsIm1kNSI6ImE0Zjk3ODI1NTg3OGM0MjAyYmU2MThiY2M2OTI0NDg0IiwiaWF0IjoxNjYzMzI0NTQzLCJleHAiOjE2NjMzMjQ4NDMsImF1ZCI6Imh0dHBzOi8vcGxheWxpc3RzZXJ2ZXIuYXdzLnN5bmNiYWsuY29tIiwiaXNzIjoiU3luY2JhayBHcmFwaFFMIEFQSSIsInN1YiI6Imptam9oNzA5NzN4dTNydzNrZmQyS3JUTmw4eDhlQm9QQThlSEtjUU8wVFJlR2J2ZmUtIn0.iLemiKP4v8fZKiJxiwUllHbqlG-QPbaf1D6XSVKSAnc

### Notes

Token

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Tokened + I can't seem to find the ID for this stream.

Token grabbing is possible, though it will need a separate plugin to read it.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/cac2f96962f43fcec08d835b0878ed36307d4bbe/streams/us.m3u#L1444-L1445
