### ISSUE TITLE
Add: 3ABN Latino

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8780]
### Channel ID

3ABNLatino.us

### Stream URL

https://3abn-live.akamaized.net/hls/live/2010547/Latino/SQs/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://3abn-live.akamaized.net/hls/live/2010547/Latino/playlist.m3u8
