### ISSUE TITLE
Add: China National Radio

### ISSUE THREAD

**Issue by BH6AOV** [iptv-org/iptv#8787]
### Channel ID

cnr.cn

### Stream URL

http://ngcdn001.cnr.cn/live/zgzs/index.m3u8

### Notes

This is China National Radio, not a television channel.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Geo-locked from where I am. @Central302 if it works for you, you can put it as valid.
