### ISSUE TITLE
Add: BEK Sports East

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8790]
### Channel ID

BekSportsEast.us

### Stream URL

https://cdn3.wowza.com/5/ZWQ1K2NYTmpFbGsr/BEK-WOWZA-1/smil:BEKPRIMEeast.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Closing in favor #8804
