### ISSUE TITLE
Add: PBS KET2

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8793]
### Channel ID

WKPCDT2.us

### Stream URL

https://2-fss-2.streamhoster.com/pl_140/amlst:200914-1315484/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Actually WKPCDT2.us
