### ISSUE TITLE
Add: PBS KET KY

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8794]
### Channel ID

WKPCDT3.us

### Stream URL

https://2-fss-2.streamhoster.com/pl_132/amlst:200914-1315486/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
FYI, this is WKPCDT1.us
