### ISSUE TITLE
Add: PBS KET World

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8795]
### Channel ID

WKMJDT3.us

### Stream URL

https://2-fss-1.streamhoster.com/pl_122/amlst:200914-2942150/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Is, in fact, WKMJDT3.us
