### ISSUE TITLE
Add: Canal 5 Corrientes

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8808]
### Channel ID

Canal5Corrientes.ar

### Stream URL

http://www.coninfo.net:1935/tvcinco/live1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Duplicate ID:
https://github.com/iptv-org/iptv/blob/c3ecac33aa203ee4d1ebaf4441677cfaf74fcd25/channels/ar.m3u~master#L4-L5
