### ISSUE TITLE
M3u8 doesn't play after some time

### ISSUE THREAD

**Issue by ardentinfo** [iptv-org/iptv#881]
Sir, I am a newbie. I don't have much knowledge about this. I am making my own IPTV list. I got a channel link which contain some special characters like nimblesessionid= and others. When I play it in my browser, it played but after some time, it's showing Forbidden. So can you please help me.
This is the link -
51.159.34.142:8081/lpcind1/starmovies/chunks.m3u8?nimblesessionid=2710547&wmsAuthSign=c2VydmVyX3RpbWU9MS81LzIwMjAgNjoyOToxMSBBTSZoYXNoX3ZhbHVlPUl2SDdEbFNVNDNzdVRLZ2gxTkVDbmc9PSZ2YWxpZG1pbnV0ZXM9Mg==

**Comment by freearhey** [comment]
This is a fairly common situation. Many sites protect their broadcasts by adding a unique token (letters and numbers) to the links and updating it periodically. Thus, such links are constantly outdated and can not be used outside this site.

**Comment by ardentinfo** [comment]
So what to do in such situation

**Comment by freearhey** [comment]
There's nothing you can do about it.

**Comment by ardentinfo** [comment]
But I have seen a live tv app which streams this link continuously 24/7 on
their app

**Comment by freearhey** [comment]
Well, you can also ask the administrator of this site to provide access to this broadcast and I think for a fee he will also give you a working link.
