### ISSUE TITLE
Add: MPT2

### ISSUE THREAD

**Issue by Arkina1234** [iptv-org/iptv#8822]
### Channel ID

WMPBDT2.us

### Notes

https://www.mpt.org/anywhere/live-stream-mpt2/
Location Access

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
On PBS Channel list: please close.
