### ISSUE TITLE
Add: M7h

### ISSUE THREAD

**Issue by mohdjuwaiser** [iptv-org/iptv#8829]
### Channel ID

M7

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Author blocked for spamming:

https://github.com/iptv-org/iptv/issues?q=involves%3Amohdjuwaiser
https://github.com/iptv-org/database/issues?q=involves%3Amohdjuwaiser+
