### ISSUE TITLE
Add: Canal 7 Salta

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8848]
### Channel ID

Canal7Salta.ar

### Stream URL

https://panel.dattalive.com/8074/8074/chunklist_w987069237.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Duplicate #8727
