### ISSUE TITLE
Add: Canal Santa María

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8855]
### Channel ID

CanalSantaMaria.ar

### Stream URL

https://streaming.telered.com.ar/santa-maria/streaming/mystreamSantaMariaHSMed.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://streaming.telered.com.ar/santa-maria/streaming/mystream.m3u8
