### ISSUE TITLE
Add: Cartoonito Argentina

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8872]
### Channel ID

CartoonitoArgentina.ar

### Stream URL

https://playout.cdn.cartoonnetwork.com.br/playout_04/playlist-720p.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by bbbureneecartoonz** [comment]
bb
