### ISSUE TITLE
Add: Crónica TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8874]
### Channel ID

CronicaTV.ar

### Stream URL

https://g5.vxral-slo.transport.edge-access.net/b16/ngrp:cronicatv_video1-100044_all/cronicatv_video1-100044_720p.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://g5.vxral-slo.transport.edge-access.net/b16/ngrp:cronicatv_video1-100044_all/playlist.m3u8 most certainly with the iPhone user-agent.
