### ISSUE TITLE
Guide Link for US won't resolve

### ISSUE THREAD

**Issue by MCTyler** [iptv-org/iptv#888]
I can't get the link for US EPG to resolve ....Thanks

http://epg.streamstv.me/epg/guide-usa.xml.gz

**Comment by freearhey** [comment]
Thank you for bringing this to our attention. I've already removed the broken link, but we'll get it back when the working one shows up.

**Comment by MCTyler** [comment]
Looks like you got it fixed!......just clicked on link and guide downloaded.
