### ISSUE TITLE
Add: CTVNewsChannel.tw

### ISSUE THREAD

**Issue by sonnykuo** [iptv-org/iptv#8882]
### Channel ID

CTVNewsChannel.tw

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/watch?v=TCnaIE_SAtM

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fotvnetwork** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/twctvnews/live
