### ISSUE TITLE
Add: Canal 5 Santa Fe

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8893]
### Channel ID

Canal5SantaFe.ar

### Stream URL

https://stream.arcast.com.ar/c5sf/c5sf/chunklist_w792829454.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://stream.arcast.com.ar/c5sf/c5sf/playlist.m3u8
