### ISSUE TITLE
Add: Doce Misones

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8894]
### Channel ID

DoceMisiones.ar

### Stream URL

https://g2.vxral-slo.transport.edge-access.net/a05/ngrp:c12_live01-100129_all/c12_live01-100129_360p.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://g2.vxral-slo.transport.edge-access.net/a05/ngrp:c12_live01-100129_all/playlist.m3u8 most certainly with the iPhone user-agent.
