### ISSUE TITLE
Add: El Nueve

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8895]
### Channel ID

ElNueve.ar

### Stream URL

https://2a1773fcc0c94a639b422d1cf7ba14b7.mediatailor.us-east-1.amazonaws.com/v1/manifest/4c8323052bc3dbd9aa2eba0b638d8495561e8377/JW-Octubre-Channel09/f25d92ce-f3ed-4e29-aa9c-5f10b1ed5455/0.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://octubre-live.cdn.vustreams.com/live/channel09/live.isml/live.m3u8
