### ISSUE TITLE
Add: CTN Lifestyle

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8896]
### Channel ID

CTNLifestyle.us

### Stream URL

https://ctntv.getstreamhosting.com:1936/Lifestyle/Lifestyle/chunklist_w1683850654.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://ctntv.getstreamhosting.com:1936/Lifestyle/Lifestyle/playlist.m3u8
