### ISSUE TITLE
Add: Cutlery Corner Network

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8897]
### Channel ID

CutleryCornerNetwork.us

### Stream URL

https://youtu.be/cJJp3GG8FZA

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/CutlerycornerNetwork/live
