### ISSUE TITLE
Add: CVTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8898]
### Channel ID

CVTV.us

### Stream URL

https://invintus-otfp.global.ssl.fastly.net/2917038973/487b842c8d9f8e9fc0b4043b9a49e65328650ac0_480p_30fps.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Not live. We shall precise it's Vancouver, Washington, not Vancouver in Canada.
