### ISSUE TITLE
Add: DanceStar TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8899]
### Channel ID

DanceStarTV.us

### Stream URL

https://vcndstv.teleosmedia.com/stream/dstv/dstv/seglist_360p.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://vcndstv.teleosmedia.com/stream/dstv/dstv/playlist.m3u8
