### ISSUE TITLE
Add: Nickelodeon Thailand And australia/new zealand

### ISSUE THREAD

**Issue by Joshuaj970** [iptv-org/iptv#8900]
### Channel ID

idk

### Stream URL

i dont have one

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
> IMPORTANT: the issue should contain a request for only one channel, otherwise it will be closed immediately

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel
