### ISSUE TITLE
Add: Foro TV | (MX / US)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8909]
### Channel ID

Foro.mx

### Stream URL

https://channel02dai-notusa.akamaized.net/hls/live/2023914/event01/index.m3u8?hdnea=st=1663715548~exp=1663715848~acl=*~id=ca1df4f5-119a-4813-99d2-a6504a581b3a~hmac=d4932c2b4d7363b31f131f386a67f5b2b72d309861efb5a7633939b0af4fb266&originpath=/linear/hls/pa/event/wkHu6QpATh6EUoHCaTDYPw/stream/7301ddb4-dbc5-42e1-869d-f56e02b940f7:CHS/master.m3u8&hdnea=exp=1663716148~acl=/*~hmac=3f6ef3d85333a3c292e9950c539e204199423c0f4b3baa203d14e4f1f902cbe5

### Notes

The Stream Is [Geo-Blocked] But The Stream Still Works And There A Foro TV YouTube Stream
The m3u8 Is From This Site 
https://www.nmas.com.mx/

Youtube Stream
www.youtube.com/watch?v=prpSI_M_rSA
![20220920_181324](https://user-images.githubusercontent.com/83226646/191380892-43fc43cf-a299-4d50-80b3-149fdc1036cb.jpg)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://dai.google.com/linear/v1/hls/event/wkHu6QpATh6EUoHCaTDYPw/stream though it needs a POST with data i don't know.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/mx.m3u#L46-L47
