### ISSUE TITLE
Add: Azteca UNO | (MX)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8911]
### Channel ID

AztecaUno.mx

### Stream URL

https://mdstrm.com/live-stream-gdai/609b243156cca108312822a6/linear/hls/pa/event/ZiyeO1LFRfG1k2-GZ5TgEg/stream/571e00be-d612-4cb4-961f-d5d444d7aff6:CHS/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Same as the last issue above.
https://mdstrm.com/live-stream-playlist/609b243156cca108312822a6.m3u8 as an alternative.
