### ISSUE TITLE
Add: A+ / A MÁS 7.2 | (MX)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8912]
### Channel ID

APlus.mx

### Stream URL

https://mdstrm.com/live-stream-gdai/60b56be1000ea50835fa1e63/linear/hls/pa/event/2tBalxaHTg-QN-GgSPzs-g/stream/86ca05bb-3ba6-4ed8-9377-2d85776820ba:MRN2/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Google DAI says Gone. MDSTRM says Geo.

**Comment by LaneSh4d0w** [comment]
Alternative link would be https://mdstrm.com/live-stream-playlist/60b56be1000ea50835fa1e63.m3u8
