### ISSUE TITLE
Add: ZooMoo

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8914]
### Channel ID

ZooMoo.nz

### Stream URL

https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg01553-blueantmediaasi-zoomoonz-samsungnz/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AzeemHadzrie** [comment]
https://rockentertainment-zoomoo-1-us.samsung.wurl.tv/2000.m3u8

**Comment by Sphinxroot** [comment]
https://github.com/iptv-org/iptv/blob/86f20a2bc40308501fe842ef40c31eb60849d704/streams/nz_samsung.m3u#L94

**Comment by LaneSh4d0w** [comment]
https://amg01553-blueantmediaasi-zoomoonz-samsungnz-rdufn.amagi.tv/playlist/amg01553-blueantmediaasi-zoomoonz-samsungnz/playlist.m3u8
