### ISSUE TITLE
Add: El Siete

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8925]
### Channel ID

ElSiete.ar

### Stream URL

https://youtu.be/41YAYbmRVq4

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
from Mendoza, AR http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/CanalSieteMendoza1/live

I am actively investigating the bad quality issue on the streams, should be fixed tonight if I have time.
