### ISSUE TITLE
Add: Garage TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8926]
### Channel ID

GarageTV.ar

### Stream URL

http://186.0.233.76:1935/Garage/smil:garage.smil/chunklist_w1317776673_b1296000_sleng.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Already Exists. Closing. https://github.com/iptv-org/iptv/blob/c3ecac33aa203ee4d1ebaf4441677cfaf74fcd25/channels/ar.m3u~master#L101-L102
