### ISSUE TITLE
Add: IP Noticias

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8927]
### Channel ID

IPNoticias.ar

### Stream URL

https://octubre-live.cdn.vustreams.com/live/ip/live.isml/live-audio_1=128000-video=2800000.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Fransito-Dev** [comment]
Holq
