### ISSUE TITLE
I couldn't change the broken links 

### ISSUE THREAD

**Issue by Kosay** [iptv-org/iptv#893]
Hi

I tried to change the broken links and add more Arabic TV channels but I couldn't because I don't have a permission and I got a new project in my profile (https://github.com/Kosay/iptv)
How can I contribute without get a new project?

Thank you

**Comment by freearhey** [comment]
This new project on the GitHub is called Fork. And this is just a copy of a main project. You make all the changes in it, and then send the result to us. 

More details on how to do it here: https://guides.github.com/activities/forking/.
