### ISSUE TITLE
Add: Daystar TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8933]
### Channel ID

DaystarTV.us

### Stream URL

https://hls-live-web-media.cdn01.net/dvr/stream_37099_1.m3u8?GGIv_jljEmpOAZOpzv0HBcgj2grBiwkJ53Ek8mz1E_3SmzqyXj4uvzrmrdizY5boWKi4DzP_isev6x2bTTUkNOCg8WhC9wGUB23CgTymzMCOejn3_iZOU2sBwGuQ5LByUKNCQLStSygTMx9YG5EXd9gYBIioS251A81hGyx6zZLvAP3h74hr7gUBR6x62u4ykRYaJQ&channel_id=37099&source=othersites&device_id=222690814-0888f2dbdff97923c3f5db94c62266ac&lcp=3&DVR&client_id=155386357870113117&play_id=1663785377834395

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Tokened.

**Comment by Sphinxroot** [comment]
in us_localbtv.m3u
#EXTINF:-1 tvg-id="WELLLD1.us" status="online" user-agent="Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36",WELL-LD1 (Daystar) (1080p)
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
http://v-pi.theus6tv.duckdns.org/hls/45.1/playlist.m3u8



#EXTINF:-1 ,Daystar
https://api.visionip.tv/live/ASHTTP/visiontvuk-christian-daystartv-hsslive-25f-16x9-MB/playlist.m3u8
#EXTINF:-1 ,Daystar
https://rebroadcast.mytvtogo.net/mytvtogo/rebroadcastdaystar/playlist.m3u8

http://www.giniko.com/watch.php?id=109

https://www.daystar.com/watch/live-stream/
https://www.lightcast.com/embed/player.php?id=37099&type=live&multiBitrate=1

https://daystar.tv/player/37099/37099
https://www.lightcast.com/embed/player.php?responsive=1&skinColor=000000&autoPlay=1&playlistPos=inside&playlistSize=350&tvButtonID=daystar&id=37099&type=live&timeout=360&multiBitrate=1&appId=3270&from_site=WebApp&site=webapp&autoStart=0&skipPreviewPlayer=1

Canada
https://daystar.tv/player/38389/38389
https://www.lightcast.com/embed/player.php?responsive=1&skinColor=000000&autoPlay=1&playlistPos=inside&playlistSize=350&tvButtonID=daystar&id=38389&type=live&timeout=360&appId=3270&from_site=WebApp&site=webapp&autoStart=0&skipPreviewPlayer=1

**Comment by LaneSh4d0w** [comment]
https://hls-live-web-media.cdn01.net/dvr/stream_37099_1.m3u8?source=othersites

**Comment by Alstruit** [comment]
This stream broadcasts similar if not the same as VTN.
