### ISSUE TITLE
Add: Didagh TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8936]
### Channel ID

DidgahTV.us

### Stream URL

https://playback2.akamaized.net/streams/27146356_8209491_lsi3hm213om2oocuhvj_1/exp=1663872280~acl=%2f*~data=hdntl~hmac=e7bf1ece24453cdd830c2149713f89a5d189145054e6828181ce3d1636795a09/media/27146356_8209491_lsi3hm213om2oocuhvj_1@446000p.m3u8?dw=14400&ts=1663783200

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
https://api.new.livestream.com/accounts/27146356/events/8209491/live.m3u8 
or
http://free.fullspeed.tv/iptv-query?streaming-ip=https://livestream.com/accounts/27146356/events/8209491/player
