### ISSUE TITLE
Add: Dr. Gene Scott

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8937]
### Channel ID

DrGeneScott.us

### Stream URL

https://wescottcc.piksel.tech/hls/live/2041995/adp/480p/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://wescottcc.piksel.tech/hls/live/2041995/adp/playlist.m3u8 sharing stream with pastor Melissa Scott.
