### ISSUE TITLE
Add: City of Louisville

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8943]
### Channel ID

CityofLouisville.us

### Stream URL

https://youtu.be/lxLPYfjwVx0

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCro5PeODE-MCnNzuWyxRJ6A/live
