### ISSUE TITLE
Add: City of Loveland TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8944]
### Channel ID

CityofLoveland.us

### Stream URL

https://reflect-cityofloveland-co.cablecast.tv/live-3/live/WIFI-1596k-540p/WIFI-1596k-540p.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://reflect-cityofloveland-co.cablecast.tv/live-3/live.m3u8
