### ISSUE TITLE
Add: TCSM.cv

### ISSUE THREAD

**Issue by provanumero1** [iptv-org/iptv#8952]
### Channel ID

TCSM.cv

### Stream URL

https://stream.internet.one:443/RadioCaboVerde/video.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by provanumero1** [comment]
Country: CV
Language: Portuguese
Website: https://tcsm.cv/

**Comment by provanumero1** [comment]
Channel id TCSM.cv

**Comment by freearhey** [comment]
#9022
