### ISSUE TITLE
Add: Dunya News USA

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8958]
### Channel ID

DunyaNewsUSA.us

### Stream URL

https://intl.dunyanews.tv/livehd/ngrp:dunyalivehd_2_all/chunklist_w748700449_b781072.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fraudiay79** [comment]
This already exists under .pk (Pakistan)

https://intl.dunyanews.tv/livehd/_definst_/ngrp:dunyalivehd_2_all/playlist.m3u8?dvr=
