### ISSUE TITLE
Add: El Sembrador Nueva Evangelización

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8963]
### Channel ID

ElSembradorNuevaEvangelizacionESNE.us

### Stream URL

https://zypelive-amd-uswe.akamaized.net/hls/live/2041519/main/defEvent_1_720/hdntl=exp=1663963247~acl=%2f*~data=hdntl~hmac=194a09793fd5c6fd808548a65d00d64bff9bef0946e63859087217b121d7b0ac/chunklist.m3u8?6pLKMQ3y=Sqi3Ng90&F38b1dF4=632cbeec024d0f0001884149&video_id=5f978263e036f600019f66c2&hdnts=exp%3D1663963244%7Eacl%3D%2F*2041519%2F*%7Ehmac%3Df2a7fd6051883ba4077dee94a53ea7635be430b1114f3bd37a7cee65223ea115

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
streamlink handle this https://player.zype.com/embed/5f978263e036f600019f66c2.html?api_key=6Ei5t4ymMF7G1XpMoB0ncYfISnbJ8IXpJarVHOqnitPyqJ3nQCgb0agwWe-XDKcM&controls=true

@LaneSh4d0w  does the online one work ?
![esne](https://user-images.githubusercontent.com/47762050/192096886-7dcf6b12-1075-4e00-a8b2-ab49d3aead96.PNG)

**Comment by LaneSh4d0w** [comment]
> streamlink handle this https://player.zype.com/embed/5f978263e036f600019f66c2.html?api_key=6Ei5t4ymMF7G1XpMoB0ncYfISnbJ8IXpJarVHOqnitPyqJ3nQCgb0agwWe-XDKcM&controls=true
> 
> @LaneSh4d0w  does the online one work ?
> ![esne](https://user-images.githubusercontent.com/47762050/192096886-7dcf6b12-1075-4e00-a8b2-ab49d3aead96.PNG)
> 

I'll check locally, but normally if zype's supported by Streamlink it should work on the online implementations, as I don't think Akamai has got ip-locked tokens

**Comment by LaneSh4d0w** [comment]
Just checked, Zype isn't supported by streamlink, so it won't work.

**Comment by Sphinxroot** [comment]
oh oki streamlink tester on kodi work
