### ISSUE TITLE
Add: Eternal Life TV Network

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8968]
### Channel ID

EternalLifeTVNetwork.us

### Stream URL

https://livecdn.live247stream.com/eternallife/tv/eternallife/stream1/chunks.m3u8?nimblesessionid=304557080

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://livecdn.live247stream.com/eternallife/tv/eternallife/stream1/playlist.m3u8
