### ISSUE TITLE
Add: Santa Fe Canal

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8976]
### Channel ID

SantaFeCanal.ar

### Stream URL

https://playback2.akamaized.net/streams/22636012_8242619_lsid1cvtha4jto8wkr6_1/master.m3u8?dw=14400&hdnts=exp=1663879002~acl=/streams/22636012_8242619_lsid1cvtha4jto8wkr6_1/master.m3u8*~hmac=11fd9f3f9c29be22d2f88b27591eb662e046f623a46d06e06a34be3095ebf477

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
Livestream.com hint

Detected Stream
https://playback2.akamaized.net/streams/22636012_8242619 ........

change it to https://livestream.com/accounts/22636012/events/8242619/ see if url is valid , some account are hidden , however they can be used in streamlink
note that event id might change over time , most common on hidden account

change link to https://api.new.livestream.com/accounts/22636012/events/8242619/live.m3u8 and get a hls stream , some work other not ... depending on account config setting
if hls dont work add a online Streamlinker
http://free.fullspeed.tv/iptv-query?streaming-ip=https://livestream.com/accounts/22636012/events/8242619/player


happy hunting
