### ISSUE TITLE
Add: RTP Memória

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#8979]
### Channel ID

RTPMemoria.pt

### Notes

Original request: #6510

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
#EXTINF:-1 ,RTP Memória
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
https://streaming-live.rtp.pt/liverepeater/smil:rtpmem.smil/playlist.m3u8

all rpt.pt link need the user-agent

**Comment by spotanjo3** [comment]
What is the user-agent ? Sorry.
