### ISSUE TITLE
Add: Faithlife TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#8994]
### Channel ID

FaithLifeTV.us

### Stream URL

https://biblescreen.faithlifecdn.com/biblescreen/faithlifetv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
i dont know if the one youre looking for

# https://faithlifetv.com/categories/live-streams
#EXTINF:-1 tvg-logo="" group-title="",Faithlife TV
https://biblescreen.faithlifecdn.com/biblescreen/faithlifetv/playlist.m3u8
#EXTINF:-1 tvg-logo="" group-title="",Faithlife TV - Bible Screen
https://biblescreen.faithlifecdn.com/biblescreen/bibleScreen/playlist.m3u8
#EXTINF:-1 tvg-logo="" group-title="",Faithlife TV - Christmas Music
https://vse2-na-us-ne24.secdn.net/logos-channel/live/christmas/playlist.m3u8
#EXTINF:-1 tvg-logo="" group-title="",Faithlife TV - The Family Center
https://resi.media/fcc-cc-hn/Manifest.m3u8

+ plenty of not 24/7 streams to grab when online

**Comment by AntiPontifex** [comment]
Thank you for sussing this one out; for now, we'll go with:

#EXTINF:-1 tvg-logo="" group-title="",Faithlife TV
https://biblescreen.faithlifecdn.com/biblescreen/faithlifetv/playlist.m3u8

As for the others, I'll make separate entries. Thanks again.
