### ISSUE TITLE
Add: VSCTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9001]
### Channel ID

VSCTV.us

### Stream URL

https://reflect-vsctv.cablecast.tv/live-3/live/WIFI-1296k-540p/WIFI-1296k-540p.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://reflect-vsctv.cablecast.tv/live-3/live/live.m3u8
