### ISSUE TITLE
Add: Cox Enfield Public Access

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9002]
### Channel ID

CoxEnfieldPublicAccess.us

### Stream URL

http://184.177.41.241/live-10/live/WIFI-2096k-720p/WIFI-2096k-720p.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://184.177.41.241/live-10/live.m3u8
