### ISSUE TITLE
Add: Hartford Public Access Television Educational Channel 95

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9006]
### Channel ID

HPATVEducationalChannel95.us

### Stream URL

https://hartford-ct.secure.footprint.net/egress/bhandler/hartfordct/streama/chunklist_b2192000.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://hartford-ct.secure.footprint.net/egress/bhandler/hartfordct/streama/playlist.m3u8
