### ISSUE TITLE
Add: Somos La Pampa

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9011]
### Channel ID

SomosLaPampa.ar

### Stream URL

https://stream.arcast.com.ar/somosnoticias/somosnoticias/chunklist_w209319684.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://stream.arcast.com.ar/somosnoticias/somosnoticias/playlist.m3u8 News

**Comment by Alstruit** [comment]
Done #9191.
