### ISSUE TITLE
Add: RTR-Planeta

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#9016]
### Channel ID

RTRPlaneta.ru

### Stream URL

https://vgtrksmotrim.cdnvideo.ru/live/smil:rtrp.smil/playlist.m3u8?md5=OXDlD3Xga2k7xn-dcSdF_g&e=1664042580

### Notes

There's a stream here: https://player.vgtrk.com/iframe/live/id/4941/showZoomBtn/false/isPlay/true/mute/true/sid/smotrim_rtr/

But it seems to have a token.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Dead issue: please close.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/ru.m3u#L419-L421
