### ISSUE TITLE
Add: Unife TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9023]
### Channel ID

UnifeTV.ar

### Stream URL

https://dacastmmd.mmdlive.lldns.net/dacastmmd/98adedd6dec04a2d8663899b927f9383/chunklist_b4628000.m3u8?p=79&s=1664070224&e=1664070344&h=ad43f21ba7f3eaaaa634ea304f6a5c64

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://iframe.dacast.com/live/928203024202811fc3bc6cbe26866ebf/adeed196-c997-05a9-430f-188d97dfe346 ->
https://player.dacast.com/js/player.js?contentId=928203024202811fc3bc6cbe26866ebf-live-adeed196-c997-05a9-430f-188d97dfe346 (Invokes to generate m3u8 link.)
https://playback.dacast.com/content/access?contentId=928203024202811fc3bc6cbe26866ebf-live-adeed196-c997-05a9-430f-188d97dfe346&provider=universe -> (json) hls m3u8 via xhr  ->
http://free.fullspeed.tv/iptv-query?streaming-ip=https://playback.dacast.com/content/access?contentId=928203024202811fc3bc6cbe26866ebf-live-adeed196-c997-05a9-430f-188d97dfe346&provider=universe
