### ISSUE TITLE
Add: Viajar TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9025]
### Channel ID

ViajarTV.ar

### Stream URL

https://24vod-adaptive.akamaized.net/exp=1664102059~acl=%2F3612aaff-e4c2-4401-92cc-9cced50773df%2F%2A~hmac=1dca24e0fb0286427828c99693cb08b52e7104dbec69362f665f224f04bb3506/3612aaff-e4c2-4401-92cc-9cced50773df/sep/video/25642664/playlist.m3u8?query_string_ranges=1

### Notes

No audio; perhaps someone would be kind enough to have a look. Thanks.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by joaquinito2048** [comment]
this URL is signed, please fix it and put URL non-signed.
