### ISSUE TITLE
Add: FPTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9027]
### Channel ID

FPTV.us

### Stream URL

https://youtu.be/6oZhSdk2Mq4

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/FayettevillePublicTelevision/live
