### ISSUE TITLE
Add: TVBS Asia

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#9034]
### Channel ID

TVBSAsia.tw

### Stream URL

http://38.64.72.148/hls/modn/list/4005/chunklist0.m3u8

### Notes

New m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://38.64.72.148/hls/modn/list/4005/playlist.m3u8
