### ISSUE TITLE
Add: CBS 12 KWCH Weather Channel / Always On Storm Team 12 | (US)

### ISSUE THREAD

**Issue by Arkina1234** [iptv-org/iptv#9037]
### Channel ID

KWCHDT1.us

### Stream URL

https://d2jni005khp8n7.cloudfront.net/out/gray-kwchwx-rtmp-v3/live.m3u8

### Please confirm the following

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
well, KWCH isn't that discreet when it comes to their streams. You can scrape all their links from there : https://www.kwch.com/pf/api/v3/content/fetch/site-service?query=%7B%22section%22:%22%2Fvideo%22,%22websiteOverride%22:%22kwch%22%7D&_website=kwch

**Comment by benevenstanciano** [comment]
The station's owner, Gray, formats all their links the same way it seems. I tried with WALB replacing the above and got a similar result.

**Comment by freearhey** [comment]
https://d2jni005khp8n7.cloudfront.net/out/gray-kwchwx-rtmp-v3/live.m3u8
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/7253922/232235436-dea67465-4adb-480a-bbff-98cf41a70223.png">
