### ISSUE TITLE
Add: Frisbee

### ISSUE THREAD

**Issue by MrRorls12** [iptv-org/iptv#9055]
### Channel ID

Frisbee.it

### Stream URL

http://144.2.106.87:8000/play/a06e/index.m3u8

### Notes

Frisbee is an Italian TV channel marketed towards a children audience of 4 to 14-year-olds. It's owned by Discovery Italia and broadcasts shows like Oggy and the Cockroaches, Zig and Sharko, ALVIIIIIIN!!! and the Chipmunks and Curious George.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AzeemHadzrie** [comment]
#1831
