### ISSUE TITLE
Add: Unitel Santa Cruz

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9062]
### Channel ID

UnitelSantaCruz.bo

### Stream URL

https://stream-01.nyc.dailymotion.com/sec(0HE75RGSqqnhnSdEMl12ZS9dFaQ2bW3i7cau3iAstR3PpnQdp7B3CN_syb_FvAQN)/dm/3/x7vsezg/d/live-2.m3u8#cell=lnyc

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
not 24/7

https://www.dailymotion.com/video/x7vsezg
