### ISSUE TITLE
Replace: 24 Hour Free Movies

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9063]
### Broken Link

https://d15690s323oesy.cloudfront.net/v1/master/9d062541f2ff39b5c0f48b743c6411d25f62fc25/UDU-Plex/158.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
/UDU-Plex2/145.m3u8

**Comment by freearhey** [comment]
Reference:
https://github.com/iptv-org/iptv/blob/af9b9b800746184eb44406e7613066326824ef53/streams/us_plex.m3u#L2-L3
