### ISSUE TITLE
Add: Geo USA

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9067]
### Channel ID

GeoUSA.us

### Stream URL

https://youtu.be/S2Oh4cqEmOg

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
should be pakistan
https://www.youtube.com/c/geonews/about

https://www.youtube.com/c/geonews/live

https://live.geo.tv/
https://jk3lz82elw79-hls-live.5centscdn.com/GEONEWS/3500ba09d0538297440ca620c9dd46bf.sdp/playlist.m3u8
