### ISSUE TITLE
Replace: NewsNet (720p) [Not 24/7]

### ISSUE THREAD

**Issue by Arkina1234** [iptv-org/iptv#9070]
### Broken Link

https://2-fss-2.streamhoster.com/pl_138/amlst:201950-1311088/playlist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Reference:
https://github.com/iptv-org/iptv/blob/1c4a148e04bb3d60eb193305591ca29a36d5761b/streams/us.m3u#L1042-L1043

**Comment by darrencycheung** [comment]
https://newsnetaa-newsnet-ono-hbpue.amagi.tv/playlist/newsnetAA-newsnet-ono/cb54381b6573668884cb3661cef343a5f9431fde1d6988693eb5518975d10724d4efa89da914ac30578f6680255f314120369809a11f11afce7ba83e357978738388c33b99c5476ee78a74736eac7f1d56e00d13c03d285aedc43644c531bc720053cf0c6d5d3dc4fd2af5340d98d5158a7f2c95adc361277d4a3cce0b0ca7f941a6fce64346de7eb5e5154cc32944b28a5fca8119be9dd55acb179b27f311c88ff189821683d29337f852e061532f481a98846addcd54b2a8f60353ae54186a3f76c39cbedb144cec2e4258ebb1c8b075ef12bcea4fe0306dc16af25a970f9a79a31fa6e257d2c1d1b570640988e57844188dc0fafc915332b975b5abeaaf1f16f3c431486be84efd1d061dca83a17a85c706d8a330baa47b142ec1925ce9f1d8e9dd95bd66bd06eff8d9bd673b240a05069513a59f63c92caf14c2a421046c61658ebf6ae9a383205a0c4e829310d5030b86d99e8ddb023eb80c7130da45e977244fe90b4159bf5a93fd3d689a680e8b214f97325fb267cc940dd682e4c82361c1b4a345fb7ffdc766b89c308c5d10782196cd017a1f3b17b7ef621e7e6cd14996bfa08b452c30c0d6eedbff7e1d5d417d3a0d8ff1a9779f9ed25b717cab610350583134b33bfb4c854123712fcd0d9dad1964ba153522f4a200484860e4a4dbebb5f3fa68945cf6f0d01c7547330fbc3716686fc3a6b257fc354e0c1637ea3d417391267967d5b8ecbfe5ea02c99874b807611b6dd6f519557b3e190938bea044f67dc7ac309cc18a36bcee89010b8238b3132f9ddfd27ffde395b52365fa9872294bb6f002fa5e08f525be58e057c8a3c0347c7e19650aa5ab47eb50b7d69bb55af04e887a73b26ee5d9e68596c37459f7943053796907531756074c6cd8bab5842d5b95dc47863d868b0f89083a162a55d1920511b2e97b10953b705a74c1a19e80c51919c662f53a9c2e53e61f202fe2c536fe8ca1fba1c7465a14dcbaeb61baa2c8aeff96f2662f5b5361cefe081c37f936e08002d6a81f57e69dc4b08939d926b475f3af9e1ac910ec8bb007a595ddd9fe741c511317dfc9e5f519def35b15ee358b037d56cccad7f563fac8b5482db90aaed6511cc1541a72faebc376af7ae8d9687fd8d0131ebf1215ceeff82a19ba4186302271f4b7ec4d33ddcc02960dd6d5d83c0cb44a79c0424d6ab873ea85f71b038bd6212561c12a24a948a9eda32433189cb756090b2e292a24f432361ec10e46843997dbcf946242dc54fa4dbf7f4a01dae868c63b95f66d3a78/25/1280x720_2964940/index.m3u8

**Comment by freearhey** [comment]
https://2-fss-2.streamhoster.com/pl_138/amlst:201950-1311088/playlist.m3u8
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/7253922/192965232-c1342e75-ecea-4c79-974b-3b2c3ac8b0ea.png">
