### ISSUE TITLE
Add: Skye XIII

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9080]
### Channel ID

SkyeXIII.us

### Stream URL

https://manifest-gce-us-east4-production.fastly.mux.com/y02XcdswaLRmawlRPJWt7F00db00yg800MhW5pDXMfpZcwozEYr1w1kmYp4GvyDZXsYWXhsrCYfbFT02jxiSt012FFFsSzJwLUpq01JJO2QpXBoqgI/rendition.m3u8?cdn=fastly&exclude_pdt=false&expires=1664751600&live=1&skid=default&signature=NjMzYTE3ZjBfNjc5ZjYwMjkxYTE0ZmFhMDZiNTQ1YjUxZDZkOGE3ZTVlY2E4MjIyYzU3MTA4YjZjZjNjNzFhNDFhZDk4ZDI3Yw==

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://stream.mux.com/j01Cei1gJ8Q2b4q02MplrfJK5ggnVsMv58BdsEaICZImQ.m3u8

**Comment by Alstruit** [comment]
Done #9191
