### ISSUE TITLE
Replace: France 24 Arabic

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9084]
### Broken Link

http://81.94.196.205/tsstreamer/France24Arabic_HD.ts

### What happened to the stream?

Not loading

### Possible Replacement

https://youtu.be/h3MuIUNCCzI

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
http://81.94.196.205/tsstreamer/France24Arabic_HD.ts
<img width="785" alt="image" src="https://user-images.githubusercontent.com/7253922/192481422-b88752cc-5893-47dd-9ae2-48d4cace00b9.png">
