### ISSUE TITLE
Replace: France 24 English

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9085]
### Broken Link

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/FRANCE24English/live

### What happened to the stream?

Not loading

### Possible Replacement

https://youtu.be/h3MuIUNCCzI

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/FRANCE24English/live
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/7253922/192481279-3db09b3e-494b-4f30-ac42-3f756c37a890.png">

**Comment by AntiPontifex** [comment]
Notwithstanding, it still is not loading. Geo-blocked?

**Comment by freearhey** [comment]
It works the same way for me with a Canadian IP (VPN)

**Comment by AntiPontifex** [comment]
Then what could be going on? I'm using LazyIPTV on an NVidia...as stated, the same applies
for all the other France24 channels. Black screen, no loading. Are you using VLC?

**Comment by freearhey** [comment]
I checked with [IINA](https://iina.io/), [VLC](https://www.videolan.org/vlc/) and [Native HLC Playback](https://chrome.google.com/webstore/detail/native-hls-playback/emnphkkblegpebimobpbekeedfgemhof) extension, the broadcast runs everywhere.

Try asking for help via [Discussions](https://github.com/iptv-org/iptv/discussions), maybe someone else has encountered this problem and can help.

**Comment by AntiPontifex** [comment]
Update: it was the programme I was using: LazyIPTV. I installed tiviMate and the streams ran perfectly. Thank you for your time and assistance in this matter. All the best.
