### ISSUE TITLE
Replace: France 24 Espanol

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9086]
### Broken Link

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/FRANCE24Espanol/live

### What happened to the stream?

Not loading

### Possible Replacement

https://youtu.be/XDJPzMznAjU

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/FRANCE24Espanol/live
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/7253922/192481126-7c81876e-3c63-44c5-9fe5-f92705fa76fc.png">
