### ISSUE TITLE
Replace: France 24 French

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9087]
### Broken Link

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/FRANCE24/live

### What happened to the stream?

Not loading

### Possible Replacement

https://youtu.be/gxG3pdKvlIs

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/FRANCE24/live
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/7253922/192481009-2861e4ed-87ff-4c08-9918-7aee2e69d547.png">
