### ISSUE TITLE
Add: Boa Vontade TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9090]
### Channel ID

BoaVontadeTV.br

### Stream URL

https://youtu.be/jTYD76rrbkw

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
private stream and must be logged to yt

**Comment by Alstruit** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCedt33latJW7StRfdF4-1FQ/live
