### ISSUE TITLE
Add: Olympic Channel

### ISSUE THREAD

**Issue by Smark223** [iptv-org/iptv#9102]
### Channel ID

OlympicChannelUSA.us

### Stream URL

https://ocshls-2-olympicchannel.akamaized.net/ocshls/OC1_71.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by MapGuy11** [comment]
This channel has ceased operating
