### ISSUE TITLE
Fix: PinkOTV.it

### ISSUE THREAD

**Issue by mpbejo** [iptv-org/iptv#9104]
### Describe your issue

I hope i am reporting in the right place
id: PinkOTV.it
is an adult channel, actually categories is empty, should be set to xxx 
so it can be filtered correctly

**Comment by LaneSh4d0w** [comment]
Interesting. We had it in our database but thought it was already tagged to XXX. Thank you for telling us. Will make the changes in the database.

**Comment by LaneSh4d0w** [comment]
After verification, it seems it's already tagged as NSFW. Have you seen it in the non-NSFW playlists ?

**Comment by mpbejo** [comment]
no i did not check NSFW, i did it https://iptv-org.github.io/api/channels.json
and in the response i see {"id":"PinkOTV.it","name":"Pink'O TV","native_name":null,"network":null,"country":"IT","subdivision":null,"city":null,"broadcast_area":["c/IT"],"languages":["ita"],"categories":[],"is_nsfw":true,"launched":null,"closed":null,"replaced_by":null,"website":"http://www.pinkotv.com/","logo":"https://i.imgur.com/QinRAGU.png"}
as You can see categories is [] instead should be "xxx", 
but as You told me is_nsfw is set true

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/database/commit/ed527a3acc2ce9e3e128edefced93372e11d2b43
