### ISSUE TITLE
Add: Watania Tv

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/iptv#9105]
### Channel ID

WataniaTv.dz

### Stream URL

https://stream.castr.com/62c18c3f14d09a0b7e5355a5/live_3949b8b03cc511edacc24fd73f3ea4db/index.m3u8

### Notes

Needs referer
https://player.castr.com/live_3949b8b03cc511edacc24fd73f3ea4db

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://github.com/iptv-org/iptv/discussions/9161#discussioncomment-3764380
