### ISSUE TITLE
Add: Medalhão Persa

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9128]
### Channel ID

MedalhaoPersa.br

### Stream URL

https://youtu.be/Nvh-j97bDLo

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCXzXFFbjUBIXKM7ONsIQAbw/live
