### ISSUE TITLE
Add: Barça TV [Spain]

### ISSUE THREAD

**Issue by ratros** [iptv-org/iptv#9134]
### Channel ID

BarcaTV.es

### Notes

I want Barca TV m3u8 link.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by R4IN2007** [comment]
Barça TV m3u8
https://streamamg-fcbar01.akamaized.net/hls/live/2040130/0_fcq6zq7g/master.m3u8?hdnea=st=1664404257~exp=1664404857~acl=/hls/live/2040130/0_fcq6zq7g/master.m3u8*~hmac=44a2070227e5563477356b4fabe33380f570b81b9e32e086b4255439fa16437e

(https://piratilla.com/693016/fcb?ch=es)

**Comment by LaneSh4d0w** [comment]
> Barça TV m3u8 https://streamamg-fcbar01.akamaized.net/hls/live/2040130/0_fcq6zq7g/master.m3u8?hdnea=st=1664404257~exp=1664404857~acl=/hls/live/2040130/0_fcq6zq7g/master.m3u8*~hmac=44a2070227e5563477356b4fabe33380f570b81b9e32e086b4255439fa16437e
> 
> (https://piratilla.com/693016/fcb?ch=es)

tokened.

**Comment by R4IN2007** [comment]
Here This m3u8 Link, it's not tokens
http://93.152.174.144:4000/play/barcatv/index.m3u8
![Screenshot_20221002-212658_VLC](https://user-images.githubusercontent.com/83226646/193491235-741e8541-497c-4f93-9756-d341267c7be0.jpg)
