### ISSUE TITLE
Add: Guatevisión

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#9135]
### Channel ID

Guatevision.gt

### Stream URL

http://190.122.96.187:8888/http/002

### Notes

The Channel Of TV Azteca Honduras Has Been Changed To Guatevision
https://github.com/iptv-org/iptv/issues/6981

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Already exists 946e23af545e32a603182b7eb9763d45a23df7a8. Closing.
