### ISSUE TITLE
Add: Antena 3 | [Spain]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#9162]
### Channel ID

Antena3.es

### Stream URL

https://atres-live.atresmedia.com/de1b7bac92e972761d016515289c3c4ce7499dea_ES_1664474298_1664503038/h264/live/antena3/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by joaquinito2048** [comment]
please close this PR, this URL is signed and it appears not works.

**Comment by freearhey** [comment]
Closed in favor of #12233
