### ISSUE TITLE
Add: Marin TV Community Channel 

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9189]
### Channel ID

MarinTVCommunityChannel.us

### Stream URL

https://dacastmmd.mmdlive.lldns.net/dacastmmd/8e6d110b223b4aca9dd6f7c368baec07/chunklist_b4628000.m3u8?p=79&s=1664505994&e=1664506114&h=be93d870c78ba3a0338aaf563eb0dc4b

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Dup of #8189 Will address.
