### ISSUE TITLE
Add: The Weather Channel

### ISSUE THREAD

**Issue by fir3z** [iptv-org/iptv#9199]
### Channel ID

TheWeatherChannel.us

### Stream URL

https://twcprod-live.twc-tv.com/v1/manifest/b4d4d63a49309cc5140171fb2e92485c31be1e9e/DSP_6228e4760505741a116f1ba2_twcprod-live/6bf09ce5-366b-463c-b67e-c4b799f73c3f/4.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by trancer1994** [comment]
Can somebody give me a link to the main index file? The link we seem to have is for the best quality.

**Comment by spotanjo3** [comment]
This is not The Weather Channel. I am looking for this one. And this link is what channel ?
