### ISSUE TITLE
Add: Pulsea

### ISSUE THREAD

**Issue by las-pen** [iptv-org/iptv#9201]
### Channel ID

Pulsea.fi

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCYzR7Jh-KkzXeHiZv7K-fbg/live

### Notes

Not 24/7

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCYzR7Jh-KkzXeHiZv7K-fbg/live

> No streams found.
