### ISSUE TITLE
Add: PBCTV Channel 20

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9207]
### Channel ID

PBCTVChannel20.us

### Stream URL

https://pbcmedia.pbcgov.org:1936/live/mp4live.sdp/chunklist_w1150244360.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://pbcmedia.pbcgov.org:1936/live/mp4live.sdp/playlist.m3u8
