### ISSUE TITLE
Add: Pasco TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9208]
### Channel ID

PascoTV.us

### Stream URL

https://cpcdn.azureedge.net/PASCOCOFLLIVE1/PASCOCOFLLIVE1/chunklist_w1707987742.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://cpcdn.azureedge.net/PASCOCOFLLIVE1/PASCOCOFLLIVE1/playlist.m3u8
