### ISSUE TITLE
Add: Access Sarasota

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9210]
### Channel ID

SarasotaCountyTV.us

### Stream URL

https://youtu.be/PdHVVz9hKas

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCqHDwKPPOhzLmtb4TvwIZZQ/live (1080p)
