### ISSUE TITLE
Add: SGTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9211]
### Channel ID

SGTV.us

### Stream URL

https://live.seminolecountyfl.gov/live-2/live/WIFI-1596k-540p/WIFI-1596k-540p.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://live.seminolecountyfl.gov/live-2/live/live.m3u8
