### ISSUE TITLE
Add: Pulsea

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9213]
### Channel ID

Pulsea.fi

### Stream URL

https://m.youtube.com/channel/UCYzR7Jh-KkzXeHiZv7K-fbg/live

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Duplicate #9201
