### ISSUE TITLE
Add: Mega TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9217]
### Channel ID

MegaTV.us

### Stream URL

https://sbsmegatv-live.cdn.vustreams.com/live/41adf852-5a63-44f0-8e92-e535b458c2e6/live.isml/.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by MapGuy11** [comment]
403
