### ISSUE TITLE
Add: TV Aratu

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9227]
### Channel ID

TVAratu.br

### Stream URL

https://cdn.jmvstream.com/w/LVW-8379/LVW8379_rIq6ZYiIiA/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Isn't it SBT?
