### ISSUE TITLE
Add: WABC-DT1

### ISSUE THREAD

**Issue by chammer977** [iptv-org/iptv#9231]
### Channel ID

WABCDT1.us

### Notes

Hi

The attatched stream is for ABC NY local news, not WABC-DT1. If possible, please could you add the normal broadcast channel?

Thanks

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
Duplicate of #8935

**Comment by freearhey** [comment]
Related #8935

**Comment by AntiPontifex** [comment]
Dead issue: please close.

**Comment by freearhey** [comment]
Closed in favor of #8935
