### ISSUE TITLE
Replace: All of the Cartoon Network streams are down.

### ISSUE THREAD

**Issue by SomeOrdinarySanya** [iptv-org/iptv#9233]
### Broken Link

Literally all of the Cartoon Network streams

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
> IMPORTANT: an issue should contain a report for only one channel, otherwise it will be closed immediately

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream
