### ISSUE TITLE
Add: Comarca TV

### ISSUE THREAD

**Issue by Hannaplus4** [iptv-org/iptv#9238]
### Channel ID

ComarcaTV.ar

### Stream URL

https://www.twitch.tv/comarca_tv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream does not work: please close.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/ar.m3u#L217-L218
