### ISSUE TITLE
Add: El Once

### ISSUE THREAD

**Issue by Hannaplus4** [iptv-org/iptv#9241]
### Channel ID

ElOnce.ar

### Stream URL

https://elonceovh.elonce.com/hls/live.m3u8

### Notes

Not 24/7

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream does not work: please close.
