### ISSUE TITLE
Add: Fernandina Beach Channel

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9246]
### Channel ID

FernandinaBeachChannel.us

### Stream URL

https://s59.ipcamlive.com/streams/3bheputnygqzjjeno/stream.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
The link contains CCTV footage:

https://s59.ipcamlive.com/streams/3bheputnygqzjjeno/stream.m3u8
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/7253922/193444789-2c03dc7a-1259-4d28-8246-f4ef49d2b2bc.png">

Link to the broadcast from the [official website](https://www.fbfl.us/815/City-Meeting-Videos) of the channel:

https://edge-f.swagit.com/live/fernandinabeachfl/live-1-a/playlist.m3u8
