### ISSUE TITLE
Add: TV Cachoeira

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9262]
### Channel ID

TVCachoeira.br

### Stream URL

https://stream.live.novotempo.com/tv/smil:tvnovotempo.smil/chunklist_b3628000_slpor.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
The link provided points to Main Novo Tempo instead of TV Cachoeira which already exists. https://github.com/iptv-org/iptv/blob/c3ecac33aa203ee4d1ebaf4441677cfaf74fcd25/channels/br.m3u~master#L78-L79
