### ISSUE TITLE
Add: TV Camara de Sao Paulo

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9263]
### Channel ID

TVCamaradeSaoPaulo.br

### Stream URL

https://cdn.jmvstream.com/w/LVW-8711/ngrp:LVW8711_tG0F3TEBDL_all/chunklist_b2690048.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Already Exists. Just need to add missing ID.
