### ISSUE TITLE
Add: TV Canção Nova 	 

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9264]
### Channel ID

TVCancaoNova.br

### Stream URL

https://youtu.be/vEfzGFVsLPA

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/user/tvcancaonova/live
