### ISSUE TITLE
Add: FOX 5 (New York) News

### ISSUE THREAD

**Issue by reneruiz** [iptv-org/iptv#9265]
### Channel ID

WNYWDT1.us

### Stream URL

https://csm-e-eb.csm.tubi.video/csm/extlive/tubiprd01,p-WNYW-Monetizer.m3u8

### Notes

The current URL is a stream to WNYW (likely TVEverywhere stream), but not WNYW-DT1 the local cast. The [old BTV URL](http://v-ny.theus6tv.duckdns.org/hls/5.1/playlist.m3u8) has gone offline, but that was the correct local cast.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Maybe he's having issues with his servers, with the hurricane kicking in he might have lost power or service in the area.

**Comment by MapGuy11** [comment]
The link works for the old BTV one and the new one.

**Comment by reneruiz** [comment]
BTV does seem to be working. I thought it was dead because it wasn’t
working at the time I posted this thread and the bot tagged it with
status “error” days prior.

On October 2, 2022, tmcknight ***@***.***> wrote:
> The link works for the old BTV one and the new one.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/iptv-org/iptv/issues/9265#issuecomment-1264675964>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AADAGZJYIPZSO6JUWBA3FPTWBGWSXANCNFSM6AAAAAAQ2Y2HAY>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/us_tubi.m3u#L90-L91
