### ISSUE TITLE
Add: San Pedro TV

### ISSUE THREAD

**Issue by Hannaplus4** [iptv-org/iptv#9280]
### Channel ID

SanPedroTV.ar

### Stream URL

https://srv2.zcast.com.br/sptv2/sptv2/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
I think i'll classify this one as XXX for now... weird 7:10 am programmation lol.
