### ISSUE TITLE
Add: Canal 13 Jujuy

### ISSUE THREAD

**Issue by Hannaplus4** [iptv-org/iptv#9281]
### Channel ID

Canal13Jujuy.ar

### Stream URL

https://genexservicios.com:19360/canal13jujuy/canal13jujuy.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Done #9216.
