### ISSUE TITLE
Add: Telefe [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9283]
### Channel ID

Telefe.ar

### Stream URL

https://is-tucuman.cdn.rcs.net.ar/mnp/telefe_hls/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Possible alternative link. https://mitelefe.com/Api/Videos/GetSourceUrl/694564/0/HLS -> m3u8 generated. Expires 1 hour.
