### ISSUE TITLE
Add: RBI TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9295]
### Channel ID

RBITV.br

### Stream URL

https://live-ak.vimeocdn.com/exp=1664723392~acl=%2Fd4548599-97a2-4cd0-9550-8d0ab4c105d0%2F%2A~hmac=6122ca6c5ce91253bf68704ac75772b23cbe692b1aa5d5262d36f0b0ec99fdfb/d4548599-97a2-4cd0-9550-8d0ab4c105d0/chunklist_b3256000.m3u8?max_segments=10

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://vimeo.com/user134025315
Url video changes every 2 days or so.
