### ISSUE TITLE
Add: RIT TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9299]
### Channel ID

RedeInternacionaldeTV.br

### Stream URL

https://youtu.be/4PDunzhYyvo?list=TLGGPabMxrmXTt4wMjEwMjAyMg

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCA0bOG0NUfJ855eDtHSxOkw/live
