### ISSUE TITLE
Add: TV Assembléia Ceará

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9300]
### Channel ID

TVAssembleiaCeara.br

### Stream URL

https://jjn5dkk9bd.zoeweb.tv/z404-live/stream/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Please check for any duplicates  before posting. Closing in favor #9228.
