### ISSUE TITLE
Add: Women's Sports Network

### ISSUE THREAD

**Issue by erginozcan1993** [iptv-org/iptv#9315]
### Channel ID

WomensSportsNetwork.us

### Stream URL

https://watch.plex.tv/live-tv/channel/womens-sports-network

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://amg01416-faststudios-womensnetwork-plex-rzxxu.amagi.tv/playlist.m3u8
