### ISSUE TITLE
Add: AXN.cz | (Czech Republic)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#9316]
### Channel ID

N/A

### Stream URL

http://37.49.230.48:8080/live/GenIptvLast/FaP6YswK77NaOPOF/21105.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
I smell the Xtream-Codes server...

**Comment by znelkytv** [comment]
> 
> EDIT: Bingo ![picture](https://user-images.githubusercontent.com/30985701/193477357-b19ef9bc-d7ee-4528-9e4e-e94a31c9fd0d.png)

what is the program

**Comment by BellezaEmporium** [comment]
> 
> > 
> > EDIT: Bingo ![picture](https://user-images.githubusercontent.com/30985701/193477357-b19ef9bc-d7ee-4528-9e4e-e94a31c9fd0d.png)
> 
> what is the program

Not a program, but it's Xtream's answer to an API call.

**Comment by znelkytv** [comment]
> > > EDIT: Bingo ![picture](https://user-images.githubusercontent.com/30985701/193477357-b19ef9bc-d7ee-4528-9e4e-e94a31c9fd0d.png)
> > 
> > 
> > what is the program
> 
> Not a program, but it's Xtream's answer to an API call.

Thanks. Can you give me a tutorial for this?
