### ISSUE TITLE
Add: Canal Educação Brasilia

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9324]
### Channel ID

CanalEducacao.br

### Stream URL

https://stream-03.nyc.dailymotion.com/sec(mOyh5XasEoxB2izGnZ4Ls9dkYRVZh53hzxxy5YhUmdDVTOMW7O2QotT5NPKggbdN)/dm/3/x8abdvf/s/live-2.m3u8#cell=lnyc

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/video/x8abdvf
