### ISSUE TITLE
Add: Canal Libras

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9325]
### Channel ID

CanalLibras.br

### Stream URL

https://stream-01.ix7.dailymotion.com/sec(mOyh5XasEoxB2izGnZ4Lsx8oENVd3BXuuM2IdVPaHhNJt84zvYWkb9T_R5S3dn24)/dm/3/x8a60g5/d/live-3.m3u8#cell=lcore

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://www.dailymotion.com/tvbrasilweb -> Canal Libras. Video url might change.
