### ISSUE TITLE
Add: PTL TV Network

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9331]
### Channel ID

PTLTVNetwork.us

### Stream URL

https://storage.sardius.media/archives/-KyMV-J0vDqnClcSXs8p/events/site_1a4721d3BA/playlistindex_5_av-p.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://storage.sardius.media/archives/-KyMV-J0vDqnClcSXs8p/events/site_1a4721d3BA/playlist.m3u8
