### ISSUE TITLE
Add: QVC 3

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9333]
### Channel ID

QVC3.us

### Stream URL

https://qvc-amd-live.akamaized.net/hls/live/2034113/lsqvc3us/high.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://qvc-amd-live.akamaized.net/hls/live/2034113/lsqvc3us/master.m3u8
