### ISSUE TITLE
Add: TV Culturado Para

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9335]
### Channel ID

TVCulturadoPara.br

### Stream URL

https://www.portalcultura.com.br/playerhtml/funtelpa/radio_funtelpa/chunklist_w584945864.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
http://www.portalcultura.com.br/playerhtml/funtelpa/tv_funtelpa/playlist.m3u8
