### ISSUE TITLE
Add: TV Diário

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9336]
### Channel ID

TVDiario.br

### Stream URL

https://stream-01.nyc.dailymotion.com/sec(IbeXB-fEZXft8Mu82uFOZcMveenzxntPuESvGE7v3rCXmDuOOPq7hxT-JA377mlE)/dm/3/x7txn7q/s/live-3.m3u8#cell=lnyc

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/TVDiario
