### ISSUE TITLE
Add: TV Diversa

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9337]
### Channel ID

TVDiversa.br

### Stream URL

https://tvdiversa.brasilstream.com.br/hls/tvdiversa/index.m3u8?token=8675013517055489000

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://tvdiversa.brasilstream.com.br/hls/tvdiversa/index.m3u8
