### ISSUE TITLE
Add: TV Futuro

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9338]
### Channel ID

TVFuturo.br

### Stream URL

https://streaming03.zas.media:1936/tvfuturo/tvfuturo/chunklist_w1774310485.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://streaming03.zas.media:1936/tvfuturo/tvfuturo/playlist.m3u8

**Comment by Alstruit** [comment]
Done #9216.
