### ISSUE TITLE
Add: TV Iguaçu

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9339]
### Channel ID

TVIguacu.br

### Stream URL

https://cdn-cdn-iguacu.ciclano.io:1443/cdn-iguacu/cdn-iguacu/chunklist_w2044439872.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://cdn-cdn-iguacu.ciclano.io:1443/cdn-iguacu/cdn-iguacu/playlist.m3u8

**Comment by Alstruit** [comment]
Already exists under Rede Massa c3ecac33aa203ee4d1ebaf4441677cfaf74fcd25. Closing
