### ISSUE TITLE
Add: TV Justiça

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9341]
### Channel ID

TVJustica.br

### Stream URL

https://youtu.be/nuSYEOOtX18

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UC0qlZ5jxxueKNzUERcrllNw/live
