### ISSUE TITLE
Add: PSL TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9342]
### Channel ID

PSLTV.us

### Stream URL

https://cdn3.wowza.com/5/UWpORHhLSEs5SkJs/psl/G0262_003/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://cdn3.wowza.com/5/UWpORHhLSEs5SkJs/psl/G0262_003/playlist.m3u8
