### ISSUE TITLE
Add: Riviera Beach TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9343]
### Channel ID

RBTV.us

### Stream URL

https://stream.swagit.com/live-edge/rivierabeachfl/live-1-b/chunklist_w1474149489.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UC-PJC58-FAYgQULlvSIKJeg/live
