### ISSUE TITLE
Add: SPTV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9344]
### Channel ID

SPTV.us

### Stream URL

https://cdn3.wowza.com/5/RXJNMFI3VlVkOEFP/stpete/G0187_002/chunklist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://cdn3.wowza.com/5/RXJNMFI3VlVkOEFP/stpete/G0187_002/playlist.m3u8
