### ISSUE TITLE
Add: Taroteame

### ISSUE THREAD

**Issue by joaquinito2048** [iptv-org/iptv#9353]
### Channel ID

Taroteame.es

### Stream URL

https://5d2733224ac48.streamlock.net/taroteame/tarot_web/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by suryanshsangwan** [comment]
I am working on this
