### ISSUE TITLE
Add: X24

### ISSUE THREAD

**Issue by Hannaplus4** [iptv-org/iptv#9355]
### Channel ID

X24.ar

### Stream URL

https://srv1.zcast.com.br/x24hd/x24hd/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Is this actually working? Seems to go into an endless loop video.

**Comment by AntiPontifex** [comment]
404s: thanks anyway Lane

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/ar.m3u#L395-L396
