### ISSUE TITLE
Add: Canal 9 Chabás

### ISSUE THREAD

**Issue by Hannaplus4** [iptv-org/iptv#9356]
### Channel ID

Canal9Chabas.ar

### Stream URL

https://player.twitch.tv/?channel=canal9chabas&enableExtensions=true&muted=false&parent=twitch.tv&player=popout

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/canal9chabas
