### ISSUE TITLE
Replace: GEM TV Asia aka GEM (576p)

### ISSUE THREAD

**Issue by Jitterdoomer** [iptv-org/iptv#9364]
### Broken Link

http://210.210.155.35/uq2663/h/h19/index.m3u8

### What happened to the stream?

Displays a shutdown screen from Dens.TV.

### Possible Replacement

Unknown

### Notes

![DAE6AAD4-6794-4873-A414-EE940709EA2B](https://user-images.githubusercontent.com/46933881/193608738-1b51627e-5d57-4be1-a286-5a58ec12ed74.png)

Before I went to work, I was able to watch GEM TV (Indonesian subs), but after I came back from work, this screen shows up (above) saying that the channel is no longer available on Dens.TV. Is there another feed of this channel that has an English subtitle and announcer so that I can enjoy J-Drama and variety in English subs?

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by paloma1222** [comment]
Gem channel removed from measat satellite, no longer broadcast

That is why

**Comment by AzeemHadzrie** [comment]
Still available on Unifi TV and Sirius in my country.

**Comment by AzeemHadzrie** [comment]
Still available on Unifi and Sirius in my country.

**Comment by Jitterdoomer** [comment]
GEM currently listed as "online" but still shows the same screen as the one above. Since this is on the Singapore category, will there be any chance to transmit either the English one or the Indonesian one from a different cable/satellite provider?

**Comment by AzeemHadzrie** [comment]
Ahh yes, I can see the screen now. Seems like GEM must have removed or both like ONE TV Asia.

**Comment by AzeemHadzrie** [comment]
> https://tglmp01.akamaized.net/out/v1/acd34a6d1e2540f888793461457b77e1/manifest.mpd

Link seems to be DRM'd

> http://103.47.132.164/PLTV/88888888/224/3221227187/index.m3u8

Failure or something

**Comment by Jitterdoomer** [comment]
Are these transmitted from non-Dens.TV satellite?

**Comment by AzeemHadzrie** [comment]
For the first link, yes but need license key, it's somewhere in the other repo. Second one is offline, Third one was K-Vision feed or something.

**Comment by Jitterdoomer** [comment]
As far as we really want this channel back for anyone, I'd say they should replace that link with the third one for now until Dens.TV put most of KC Global Media channels re-transmissioned again.

**Comment by paloma1222** [comment]
![image](https://user-images.githubusercontent.com/114854982/194266109-096c6307-0c85-4075-b04b-a371da6d6c79.png)
as you can see the Indonesian broadcast was removed from the satellite

**Comment by Jitterdoomer** [comment]
http://203.77.246.50:5000/udp/239.1.2.146:5000

That link is kinda dead.

**Comment by Jitterdoomer** [comment]
Any updates on workarounds for this channel?

**Comment by Jitterdoomer** [comment]
Update: The channel seems to be stuck on loading loop instead of showing the shut down screen above. I'm starting to wonder what they're trying to do next...

**Comment by novalkomik** [comment]
There's an alternative from USEE TV, but it's an RTP

`rtp://@239.1.1.86:8154`

Other than that, there's also GEM feed from USEE TV, but it is mistook as MTV Asia at another IPTV playlist `https://dukun.masuk.id/playlist` (Probably an MPD, so it won't be functional on DVB-T2 Set Top Boxes)

**Comment by Jitterdoomer** [comment]
I hope this works so I can close this thread...

**Comment by novalkomik** [comment]
> I hope this works so I can close this thread...
> 
> EDIT: It worked for the USEE TV link but it needs to be integrated to here replacing the old Dens.TV link so that it can be supported on GSE IPTV app.

I think it needs to be restreamed. So it could be use as an m3u8

**Comment by Jitterdoomer** [comment]
> > I hope this works so I can close this thread...
> 
> > 
> 
> > EDIT: It worked for the USEE TV link but it needs to be integrated to here replacing the old Dens.TV link so that it can be supported on GSE IPTV app.
> 
> 
> 
> I think it needs to be restreamed. So it could be use as an m3u8

Thank you so much for that! Will you do it for One, AXN, and Animax Asia? Hopefully these channels won't be removed in the future like how Dens.TV did to KCGM channels.

**Comment by novalkomik** [comment]
> Thank you so much for that! Will you do it for One, AXN, and Animax Asia? Hopefully these channels won't be removed in the future like how Dens.TV did to KCGM channels.

Just to clarify, what happened between Dens TV and KCGM was merely about the contract agreement they made in the past. It is also affected by how many people would like to watch the channel on that app.

Every channel you've asked were available on the second link I gave to you. The problems with that the playlist is:
- It's MPD-format (came from Vision+ or MNC Play, but the key are available on the playlist settings and can be used directly on the regular IPTV)
- It's not working for some Set Top Boxes/Converter Box with IPTV embedded (usual STB were only able to play M3U8).
- The playlist can only be scrapped by using IPTV app such as OTTNavigator. There's no way we could scrap all the MPD/M3U8 along with the keys from Desktop, since it would be redirected to an Error Page with some mocking quote there (For anyone who'd like to try, please try it)
- Possible monthly playlist refresh.

If you'd like to get AXN etc along with BBC, CNN, Nick, Disney, and others, u might want to scrap the data from that playlist

**Comment by novalkomik** [comment]
Any update on this?

**Comment by Jitterdoomer** [comment]
> Any update on this?

So which one is it on my part or this IPTV in general? I'm kinda noob on getting this to work but I will try as much as I can.

**Comment by Jitterdoomer** [comment]
> There's an alternative from USEE TV, but it's an RTP
> 
> 
> 
> `rtp://@239.1.1.86:8154`
> 
> 
> 
> Other than that, there's also GEM feed from USEE TV, but it is mistook as MTV Asia at another IPTV playlist `https://dukun.masuk.id/playlist` (Probably an MPD, so it won't be functional on DVB-T2 Set Top Boxes)

This whole thing got an error even on different channels meaning that it won't play due to DRM stuff.
