### ISSUE TITLE
Add: SPOTV

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#9365]
### Channel ID

SPOTV.kr

### Stream URL

https://bcovlive-a.akamaihd.net/99545824f51f4c1592b35314c6ece3b0/ap-northeast-1/6271486521001/playlist.m3u8

### Notes

The m3u8 Works but its sometimes goes offline 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Already exists 22eb837adebea14dbd46c21eca7462249b82802c
