### ISSUE TITLE
Add: Telehit Música PLUS | [MX]

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#9367]
### Channel ID

*N/A*

### Stream URL

http://181.65.154.170:8000/play/a054/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream does not work: please close.

**Comment by R4IN2007** [comment]
> Stream does not work: please close.

New Stream Link 
https://linear-419.frequency.stream/419/hls/master/playlist.m3u8

Channel ID EPG: TelehitMusicaPlus.mx

Stream Works In VLC
![20221206_211905](https://user-images.githubusercontent.com/83226646/206080320-6fb9d3aa-31aa-4f84-bad2-af0df010894c.jpg)

**Comment by AntiPontifex** [comment]
Again, likely geo-blocked.
