### ISSUE TITLE
Add: MTV Portugal

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#9371]
### Channel ID

MTVPortugal.pt

### Stream URL

http://176.79.76.155:8000/play/a01x/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Geo-blocked?

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/pt.m3u#L6-L7
