### ISSUE TITLE
Replace: https://cwseedlive.cwtv.com/ingest/playlist.m3u8

### ISSUE THREAD

**Issue by TKList** [iptv-org/iptv#9372]
### Broken Link

https://cwseedlive.cwtv.com/ingest/playlist.m3u8

### What happened to the stream?

Not loading

### Notes

404 error

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by TKList** [comment]
So they should remove it

**Comment by MapGuy11** [comment]
Please do a Pull Request to remove streams thanks.

**Comment by TKList** [comment]
How do I do a Pull Request? Can't seem to figure it out.
