### ISSUE TITLE
All Cartoon Network streams are broken, Specifically "Cartoon Network Asia"

### ISSUE THREAD

**Issue by emeraldongithub** [iptv-org/iptv#9373]
### Broken Link

literally every link

### What happened to the stream?

Not loading

### Notes

All of the Cartoon Network streams are broken, specifically CN Asia. Please fix, Thanks.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
https://www.youtube.com/c/cartoonnetworkasia/live

https://www.youtube.com/c/cartoonnetwork  channel NA , but stream work
https://www.youtube.com/watch?v=LXK0YpPIX3w

https://www.youtube.com/c/cartoonnetworkturkiye/live

**Comment by ironboy36** [comment]
Agree, but Cartoon Network East and West are working.
