### ISSUE TITLE
Add: TV La Verdad

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9383]
### Channel ID

TVLaVerad.br

### Stream URL

https://youtu.be/IgN9-znZKkk

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fotvnetwork** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/user/tvlaverdadoficial/live

**Comment by AntiPontifex** [comment]
Thanks, fotvetwork.
