### ISSUE TITLE
Add: TV Milagro

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9386]
### Channel ID

TVMilagro.br

### Stream URL

https://youtu.be/Fu0_HYcVuFQ

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fotvnetwork** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCi5T3ImS-P9fINN169sUdfQ/live

**Comment by AntiPontifex** [comment]
Thanks, fotvnetwork.
