### ISSUE TITLE
Add: TV Mundo Maior

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9387]
### Channel ID

TVMundoMaior.br

### Stream URL

https://youtu.be/d8KMdZ-AyUA

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by fotvnetwork** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UC5-IOBnk-mFdQgKS-niajYg/live
