### ISSUE TITLE
Replace: VH1

### ISSUE THREAD

**Issue by TKList** [iptv-org/iptv#9410]
### Broken Link

https://content.uplynk.com/channel/36953f5b6546464590d2fcd954bc89cf.m3u8

### What happened to the stream?

Other

### Possible Replacement

None

### Notes

This is not English. Sounds like Italian. 
2078 - #EXTINF:-1 tvg-id="" status="online",VH1 (1080p)
2079 - https://content.uplynk.com/channel/36953f5b6546464590d2fcd954bc89cf.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Alstruit** [comment]
Working on it see [#9216](https://github.com/iptv-org/iptv/pull/9216/files#diff-74b334e4156cbf6f9eb60b11b6806eabd0eddf3107ec1fda534abdab2a8b0b1aR355)

**Comment by Alstruit** [comment]
Done closing.
