### ISSUE TITLE
Canada Space No Sound

### ISSUE THREAD

**Issue by lokiberra** [iptv-org/iptv#944]
There is no sound for the Space stream in the Canada Playlist:
#EXTINF:-1 tvg-id="Space-CA" tvg-name="Space-CA" tvg-language="English" tvg-logo="https://i.imgur.com/9uFrMex.png" group-title="",Space
http://pe-ak-lp01a-9c9media.akamaized.net/live/Space/p/hls/00000201/689924a518f2c776/index/2176f3ac/live/stream/h264/v1/3500000/manifest.m3u8
Update if a new stream is found otherwise this can be closed.

**Comment by freearhey** [comment]
Thank you for bringing this to my attention. I already removed the link from the playlist.
