### ISSUE TITLE
Add: El Rey, 60 minutes, TED, UFC Reloaded, Hallmark

### ISSUE THREAD

**Issue by kinghenrick** [iptv-org/iptv#9440]
### Channel ID

Cannot find

### Notes

Looking for m3u8's for the following. Having great difficulty locating. Any help from community would be greatly appreciated. New to this platform and figuring it out, fyi. Thank you

El Rey - Plex
Hallmark Channel
TED - Plex
UFC Reloaded - Xumo
60 minutes - Pluto TV

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Please read the Contributing Guide again.
