### ISSUE TITLE
Fix:   WJLA  Washington DC, USA    ABC7 News

### ISSUE THREAD

**Issue by Newsaddict** [iptv-org/iptv#9441]
### Describe your issue

The link always shows the same clip of the weather report.   It's been the same weather clip for a month or two.

**Comment by AntiPontifex** [comment]
Perhaps this is stream?

https://content-ausw1-up-1.uplynk.com/0407b9a83487449ab1934c75ba859dfd/g.m3u8?tc=1&exp=1665174014&rn=231262&ct=a&cid=0407b9a83487449ab1934c75ba859dfd&sig=7641830f6814f2d9429278abdf1c4944e07d0a0391e1d80abdc409d6a9c3ca4b&pbs=28d4687e2cd14663a02707e036727b65

**Comment by LaneSh4d0w** [comment]
I don't think this one is the correct stream either.

**Comment by freearhey** [comment]
To report a broken stream, please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=%F0%9F%9B%A0+broken+stream&template=-----broken-stream.yml&title=Replace%3A+
