### ISSUE TITLE
Add: Fuji TV

### ISSUE THREAD

**Issue by baliebox4916** [iptv-org/iptv#9477]
### Channel ID

JOCXDTV.jp

### Notes

Some Other Channel Requests

This Time Regarding Anime

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://redlabmcdn.s.llnwi.net/nv02/ryowa7hd/index.m3u8
<img width="790" alt="image" src="https://user-images.githubusercontent.com/7253922/233871751-00edf4d3-ca0c-4a5b-8cdf-eed0091c5bdc.png">

http://rip.hidari.moe/get/jptv/get.php?id=dfVr67j-Iy_J5tM4jYI7gQ==
<img width="785" alt="image" src="https://user-images.githubusercontent.com/7253922/233871773-9769b1eb-b7f7-4724-8163-05c7d585c612.png">

https://code.vthanhtivi.pw/getlink/jptv/uAJJq7DD6hKyPLoaMOBSUA==/playlist.m3u8
<img width="788" alt="image" src="https://user-images.githubusercontent.com/7253922/233871804-0f801aa9-56e4-40ca-bb9f-7e5d36d5bdd2.png">
