### ISSUE TITLE
Add: Kids Station

### ISSUE THREAD

**Issue by baliebox4916** [iptv-org/iptv#9482]
### Channel ID

KidsStation.jp

### Notes

Some Other Channel Requests

This Time Regarding Anime

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://code.vthanhtivi.pw/getlink/jptv/xuRJ2NXuC2ezP38iwgYdXQ==/playlist.m3u8
<img width="788" alt="image" src="https://user-images.githubusercontent.com/7253922/233872138-c33571de-8e9c-44b8-a99c-99b594b8d055.png">

http://rip.hidari.moe/get/jptv/get.php?id=xh4GJxN8zJFL3SmJ1P6Xsg==
<img width="787" alt="image" src="https://user-images.githubusercontent.com/7253922/233872160-14569717-0bad-4de0-b6a0-d9ce837644ff.png">

https://stream01.willfonk.com/live_playlist.m3u8?cid=CS330&r=FHD&ccode=JP&m=d0:20:20:04:35:cc&t=0d6938cb3dcf4b79848bc1753a59daf1
<img width="790" alt="image" src="https://user-images.githubusercontent.com/7253922/233872256-73f91d81-a7b6-4c85-8d2a-36939efc3b68.png">
