### ISSUE TITLE
Add: Nippon TV

### ISSUE THREAD

**Issue by baliebox4916** [iptv-org/iptv#9483]
### Channel ID

NipponTV.jp

### Notes

Some Other Channel Requests

This Time Regarding Anime

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://github.com/iptv-org/iptv/blob/a9f1795e0334e033b763198682b9e7bd525375b0/streams/jp.m3u#L124-L131 ?
