### ISSUE TITLE
Add: CBN News

### ISSUE THREAD

**Issue by baliebox4916** [iptv-org/iptv#9484]
### Channel ID

CBNNews.us

### Notes

Adding this Because they Have Some Pretty Interesting and Funny Stuff

Including such Classics as

Christians Complaining about Sans From Undertale Being a Skeleton and Representing Death

Christians Getting Rapped Towards Via the Lyrics of The French Prince of Bel Air Theme on Their Hotline

Christians Complaining About How Harry Potter and Star Wars is Demonic Due to The Characters Using Spells/The Force

and My Personal Favorite

The Animation Memer Lupis Vulpus Getting Bashed by CBN Due to Not Allowing the Trans Flag in their TOS and Told to Stop Drawing in the Name of God (As Featured in Nawniis Video: Lupis Vulpus was on the NEWS)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AzeemHadzrie** [comment]
The link can be found somewhere. but the notes-

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/us.m3u#L206-L207
