### ISSUE TITLE
Add: Cable 14 Hamilton

### ISSUE THREAD

**Issue by baliebox4916** [iptv-org/iptv#9485]
### Channel ID

Cable14Hamilton.ca

### Stream URL

https://cable14now.com/live-streams/video/?videoId=104

### Notes

A Public Access Channel From My Hometown That Alot of Older Cord Cutters in My Area Need Due to Their Kiwanis TV Bingo Nights Airing Every Monday Night That They Have Been Playing Since the 80s

And We Need This Channel to Keep Cord Cutters in My City From Being Turned off From IPTV and Switching Back to Bell/Rogers and Paying High Prices (Some of Which Like My Mom Herself Even Are in a Poverty Level State When it Comes to Cable Bills Because its Either Play TV Bingo and Get Smokes, Play Video Games and Get a New Gaming Rig or Have Food on the Table)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by trancer1994** [comment]
This stream is also tokened. https://flowcaster1-ch.cdn.clearcable.net/C14/smil:C14.smil/playlist.m3u8?iimae0UC2aendtime=1665196120&iimae0UC2astarttime=1665181720&iimae0UC2ahash=NzcDbuotaJAVf1DsNxuGHBlfCXSvHDIt5sqMUMgrRMU=

**Comment by baliebox4916** [comment]
what does it mean when the stream is tokened

**Comment by trancer1994** [comment]
It effectively means that the stream link will only work for however long the website sets the token to work for in its api before it expires and you have to get a new link. For example, if the site sets the token to work for 24 hrs, that's how long the stream will work for before you have to get a new one. To get around that you have to find out how the token is generated, and I don't have enough technical knowledge to find out how this one works.

**Comment by freearhey** [comment]
https://flowcaster1-ch.cdn.clearcable.net/C14/smil:C14.smil/playlist.m3u8?iimae0UC2aendtime=1665196120&iimae0UC2astarttime=1665181720&iimae0UC2ahash=NzcDbuotaJAVf1DsNxuGHBlfCXSvHDIt5sqMUMgrRMU=
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/7253922/232237179-344ec4b3-3989-46a2-a66c-e60d0779bf9e.png">
