### ISSUE TITLE
TVR International Returned

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#9500]
### Channel ID

TVRInternational.ro

### Stream URL

https://mn-nl.mncdn.com/tvri_test/smil:tvri_test.smil/chunklist_b1048000.m3u8

### Notes

Grabbed from TVR Plus

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Added to list: please closed.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/ro.m3u#L79-L80
