### ISSUE TITLE
Add: Travelxp HD

### ISSUE THREAD

**Issue by seeCURE** [iptv-org/iptv#9502]
### Channel ID

Travelxp.in

### Stream URL

https://travelxp-travelxp-1-jp.rakutenjp.wurl.tv/playlist.m3u8

### Notes

Language: English
Resolution: 1080p

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://travelxp-travelxp-1-jp.rakutenjp.wurl.tv/playlist.m3u8 (offline)
<img width="429" alt="image" src="https://user-images.githubusercontent.com/7253922/232237265-9f8cb6d9-176d-4026-9a4f-91e7601b0cca.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3dc97cd8357878a0c268aeb99d4a3db41458fd20/streams/uk_rakuten.m3u#L22-L23

**Comment by atikur531205-afk** [comment]
https://travelxp-travelxp-1-jp.rakutenjp.wurl.tv/playlist.m3u8
