### ISSUE TITLE
Add: Asian Crush

### ISSUE THREAD

**Issue by seeCURE** [iptv-org/iptv#9503]
### Channel ID

AsianCrush.us

### Stream URL

https://ac-samsung-us.ono.wurl.tv/playlist.m3u8

### Notes

Language: Japanese
Resolution: 720p

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream; it will be included in the next update.

**Comment by freearhey** [comment]
https://ac-samsung-us.ono.wurl.tv/playlist.m3u8
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/7253922/232237287-1ead78d3-6480-46a1-be0c-ffb3cbad3638.png">
