### ISSUE TITLE
Add: AMC Absolute Reality

### ISSUE THREAD

**Issue by seeCURE** [iptv-org/iptv#9504]
### Channel ID

AbsoluteRealitybyWETV.us

### Stream URL

https://amc-absolutereality-1-us.plex.wurl.tv/playlist.m3u8

### Notes

Resolution: 1080p
Language English

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream; it will be included in the next release.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/us_imdbtv.m3u#L2-L3
