### ISSUE TITLE
Add: AMC All Weddings

### ISSUE THREAD

**Issue by seeCURE** [iptv-org/iptv#9505]
### Channel ID

AllWeddingsWEtv.us

### Stream URL

https://amc-allweddings-1-us.samsung.wurl.tv/playlist.m3u8

### Notes

Resolution: 720p
Language: English

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
