### ISSUE TITLE
Add: Made in Hollywood TV

### ISSUE THREAD

**Issue by seeCURE** [iptv-org/iptv#9507]
### Channel ID

MadeInHollywood.us

### Stream URL

https://connection3-ent-us.redbox.wurl.tv/playlist.m3u8

### Notes

Resolution: 720p
Language: English

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
