### ISSUE TITLE
Add: CG Entertainment

### ISSUE THREAD

**Issue by seeCURE** [iptv-org/iptv#9508]
### Channel ID

CGEntertainment.it

### Stream URL

https://cgentertainment-cgtv-1-it.samsung.wurl.tv/playlist.m3u8

### Notes

Language: Italian
Resolution: 720p

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3aef7cdbc4c159c043152f434a750bf4d63d837d/streams/it_samsung.m3u#L38-L39
