### ISSUE TITLE
Add: Fuengirola TV [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9509]
### Channel ID

FuengirolaTV.es

### Stream URL

https://secure.todostreaming.es/live/nerja-livestream.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next update.
