### ISSUE TITLE
Add: Canal Parlamento [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9511]
### Channel ID

CanalParlamento.es

### Stream URL

https://congresodirecto.akamaized.net/hls/live/2037973/canalparlamento/master.m3u8

### Notes

Channel dedicated to broadcast live coverage of Spanish Courts. (Not 24/7)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next update.
