### ISSUE TITLE
Add: Canal Super 3 [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9512]
### Channel ID

CanalSuper3.es

### Stream URL

https://directes-tv-es.ccma.cat/live-origin/c33-super3-hls/master.m3u8

### Notes

Geo-blocked

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
