### ISSUE TITLE
Replace: La Red [CL]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9514]
### Broken Link

https://unlimited1-cl-movistar.dps.live/lared/lared.smil/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://d2ab26kihxq8p0.cloudfront.net/hls/live.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment]
Fixed: thank you.
