### ISSUE TITLE
Add: US Weekly TV

### ISSUE THREAD

**Issue by seeCURE** [iptv-org/iptv#9518]
### Channel ID

UsWeeklyTV.us

### Stream URL

https://a360-usweeklytv-1-us.plex.wurl.tv/playlist.m3u8

### Notes

Resolution: 1080p
Language: English

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream; it will be included in the next release.
