### ISSUE TITLE
Add: CNN Portugal

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#9524]
### Channel ID

CNNPortugal.pt

### Stream URL

https://video-auth7.iol.pt/live_cnn/live_cnn/edge_servers/cnn-360p/chunks.m3u8?nimblesessionid=202367017&wmsAuthSign=c2VydmVyX3RpbWU9MTAvOS8yMDIyIDE6NTQ6MzEgQU0maGFzaF92YWx1ZT0xamNoMmIyN2wxWFZNMEZGbTVsdmxBPT0mdmFsaWRtaW51dGVzPTE0NDAmaWQ9ODE4MDdkZTgtYWYwYy00YTFkLWE4MzMtZWI4MjM5MTNhZWUz 

### Notes

Grabbed from official site

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Tokened.

**Comment by AntiPontifex** [comment]
Already on list: please close.

**Comment by freearhey** [comment]
https://video-auth7.iol.pt/live_cnn/live_cnn/edge_servers/cnn-360p/chunks.m3u8?nimblesessionid=202367017&wmsAuthSign=c2VydmVyX3RpbWU9MTAvOS8yMDIyIDE6NTQ6MzEgQU0maGFzaF92YWx1ZT0xamNoMmIyN2wxWFZNMEZGbTVsdmxBPT0mdmFsaWRtaW51dGVzPTE0NDAmaWQ9ODE4MDdkZTgtYWYwYy00YTFkLWE4MzMtZWI4MjM5MTNhZWUz (offline)
<img width="831" alt="image" src="https://user-images.githubusercontent.com/7253922/232237386-7364bc4b-5b22-46cd-88d6-70b9249f485a.png">

**Comment by freearhey** [comment]
https://video-auth7.iol.pt/live_cnn/live_cnn/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9NC8yMy8yMDIzIDExOjE1OjQ0IFBNJmhhc2hfdmFsdWU9QlhWUklOeStUSGs1QXBUMzJEVG9sdz09JnZhbGlkbWludXRlcz0xNDQwJmlkPWE2MDE1NmU0LWEzZWUtNDU1Ny1hYWMwLWUzMWMzZmRhMjc1OA==
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/7253922/233878713-af559bed-faaa-45b9-b2c5-fc7e922d91eb.png">

https://sktv-forwarders.7m.pl/get.php?x=CNN_Portugal
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/7253922/233879119-b2bafffb-0786-40e3-87af-ac71775b66a2.png">
