### ISSUE TITLE
Add: Macau Asia Satellite TV

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#9525]
### Channel ID

MacauAsiaSatelliteTV.mo

### Stream URL

https://live.mastvnet.com/lsdream/lY44pmm/2000/live.m3u8

### Notes

Founded

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AzeemHadzrie** [comment]
Note: VLC works with this link. Some players don't play it due to restrictions (or something)
