### ISSUE TITLE
Add: CTS News

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#9528]
### Channel ID

CTSNews.tw

### Stream URL

https://m.youtube.com/watch?v=wM0g8EoUZ_E

### Notes

Fullspeed TV plz

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AzeemHadzrie** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/CtsTw/live may not work in a moment.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/tw.m3u#L18-L19

**Comment by kaikyoofers** [comment]
Found a link: but this one is giving me a internal server error https://ythls.onrender.com/channel/UCDCJyLpbfgeVE9iZiEam-Kg.m3u8 @freearhey can you check?

**Comment by freearhey** [comment]
https://ythls.onrender.com/channel/UCDCJyLpbfgeVE9iZiEam-Kg.m3u8 (offline)
<img width="506" alt="image" src="https://user-images.githubusercontent.com/7253922/232243375-523e40ca-2c2c-4b46-9747-07c5261f1442.png">

**Comment by kaikyoofers** [comment]
> https://ythls.onrender.com/channel/UCDCJyLpbfgeVE9iZiEam-Kg.m3u8 (offline)
> <img width="506" alt="image" src="https://user-images.githubusercontent.com/7253922/232243375-523e40ca-2c2c-4b46-9747-07c5261f1442.png">
> 

I said it gives internal server error so it wont work
