### ISSUE TITLE
Add: UCL | (Uruguay)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#9540]
### Channel ID

UCL.uy

### Stream URL

(http://162.246.18.122:8081/telepuerto-master/ucl-abr/playlist.m3u8 / https://livedelta.cdn.antel.net.uy/out/u/url_canalu.m3u8) 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Both link works. First Antel link I see without a token.

**Comment by Alstruit** [comment]
Antel link does not have audio.

**Comment by R4IN2007** [comment]
> Antel link does not have audio.

That's Strange, It Had Had Audio Before
