### ISSUE TITLE
Add: A&E | (US)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#9541]
### Channel ID

*N/A*

### Stream URL

https://live.video.aetnd.com/brand_live_streams/aetv/primary/aetv.m3u8?token=aGRudHM9c3Q9MTY2NTM2MTE2OX5leHA9MTY2NTQxODc2OX5hY2w9Lyp+aG1hYz1jODM0NWJmZTk3YmMxOTM5ZTk1ZGQ4ZDgwYTM3Mzk5ZTZhMDVmZDBkYTczMTg3MjI4M2EwMGJhMTMzZGUzYWQw

### Notes

This m3u8 Stream Link Is From Photocall.tv, I Don't Know If This Is The West or East Signal Of A&E
(https://piratilla.com/693016/ae?ch=aetv)
![Screenshot_20221009-201758_Chrome](https://user-images.githubusercontent.com/83226646/194788456-8b1c7b2b-4627-4911-bc06-ef58c6665f33.jpg)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by ztreamhd** [comment]
This is a tokenized and geo-blocked stream that's generated through a script. I've tried to create one but the links that come out are invalid.

**Comment by AntiPontifex** [comment]
Stream does not work: please close.

**Comment by spotanjo3** [comment]
The stream link doesnt work. Please closed or uploading new link, thank you.
