### ISSUE TITLE
Add: Radio Realpolitik

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#9542]
### Channel ID

RadioRealpolitik.ar

### Stream URL

https://vivo.solumedia.com:19360/realpolitik/realpolitik.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream; it will be included in the next update.
