### ISSUE TITLE
Add: Red Visión Radio

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#9543]
### Channel ID

RedVisionRadio.ar

### Stream URL

https://www.twitch.tv/redvisionradiotv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Stream does not work: please close.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/ar.m3u#L317-L318
