### ISSUE TITLE
Add: Thunder Sports

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#9544]
### Channel ID

ThunderSports.hn

### Stream URL

https://emisoras.hn:8081/tsh/tracks-v1a1/mono.m3u8

### Please confirm the following

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already in list: please closed.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/hn.m3u#L70-L71
