### ISSUE TITLE
Add: TV Centro HD

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#9545]
### Channel ID

TVCentroHD.hn

### Stream URL

https://cloud2.streaminglivehd.com:1936/8032/8032/playlist.m3u8 / https://cloud2.streaminglivehd.com:1936/8004/8004/playlist.m3u8

### Notes

There 2 Two Live Streams One Of Them Is The Main Channel And Other Is A Different Channel From The Same Site
(https://centroradialhn.net/)
![20221009_212648](https://user-images.githubusercontent.com/83226646/194791683-8b6ac17d-8a13-46df-ba1f-8b180e2e5e68.jpg)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Neither streams are working: please close.
