### ISSUE TITLE
Add: SPOTV 2

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#9561]
### Channel ID

SPOTV2.kr

### Stream URL

https://bcovlive-a.akamaihd.net/48eee16919834d3b97df1082a649bcfa/ap-northeast-1/6271486521001/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
The stream does not appear to be broadcasting for South Korea, rather possibly in Hong Kong or South Eastern Asia.
Schedule Reference: https://www.spotvasia.com/schedule?country=11&channel=2&fromDt=20221019.

**Comment by Hebatgila** [comment]
Do you have spotv too?

**Comment by R4IN2007** [comment]
> Do you have spotv too?

SPOTV
https://bcovlive-a.akamaihd.net/99545824f51f4c1592b35314c6ece3b0/ap-northeast-1/6271486521001/playlist.m3u8
