### ISSUE TITLE
Replace: AVT Khyber

### ISSUE THREAD

**Issue by solo786** [iptv-org/iptv#9570]
### Broken Link

https://streamone.simpaisa.com:8443/pitvlive1/khyber.smil/playlist.m3u8

### What happened to the stream?

Other

### Notes

For the pk.m3u stream, this channel is not correct:

#EXTINF:-1 tvg-id="AVTKhyber.pk" status="online",AVT Khyber
https://streamone.simpaisa.com:8443/pitvlive1/khyber.smil/playlist.m3u8

This link is for middle east khyber tv : https://khyberme.tv/live-streaming/

The channel is meant to be for this channel: https://avtkhyber.tv/khyber-tv-live-streaming/

could this be corrected and the middle east one placed in its own channel?

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Alstruit** [comment]
ID for provided link: KhyberMiddleEastTV.pk.
Unfortunately the AVT Khyber is tokenized.
