### ISSUE TITLE
Add: Formosa TV (FTV)

### ISSUE THREAD

**Issue by thedarkdragon11** [iptv-org/iptv#9579]
### Channel ID

FTV.tw

### Notes

There's a stream here but there's a token: https://embed.4gtv.tv/ftv/FTV.html?player_autoplay=off&player_mute=off

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/tw.m3u#L50-L53
