### ISSUE TITLE
Add: Asian Food Network

### ISSUE THREAD

**Issue by stevenpandey** [iptv-org/iptv#9582]
### Channel ID

AsianFoodNetwork.sg

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AzeemHadzrie** [comment]
Blacklisted on #1831.

**Comment by Alstruit** [comment]
Closing.
