### ISSUE TITLE
Edit: Halk TV: Languages

### ISSUE THREAD

**Issue by kalligator** [iptv-org/iptv#9583]
### Channel ID

HalkTV.tr

### Notes

It's falsely tagged with "ell", "tur" languages while only "tur" is correct.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Please open an issue in [iptv-org/database](https://github.com/iptv-org/database).
