### ISSUE TITLE
Replace: AlJazeeraEnglish.qa

### ISSUE THREAD

**Issue by 40ZqTYY4ag3tAO4hdlxR1** [iptv-org/iptv#9593]
### Broken Link

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/aljazeeraenglish/live

### What happened to the stream?

Not loading

### Possible Replacement

https://live-hls-web-aje.getaj.net/AJE/index.m3u8

### Notes

The "AlJazeeraEnglish.qa" URL in https://iptv-org.github.io/iptv/categories/news.m3u AND https://iptv-org.github.io/iptv/countries/qa.m3u
is a 240p Youtube link redirect from "fullspeed.TV" instead of the offical url 
https://live-hls-web-aje.getaj.net/AJE/index.m3u8 
which has multiple resolutions and is delivered by a proper CDN

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AzeemHadzrie** [comment]
That also happens on IP-TV Player.
