### ISSUE TITLE
Add: 28.1 XHMNL TV Nuevo León Canal 28

### ISSUE THREAD

**Issue by 3guajardo** [iptv-org/iptv#9594]
### Channel ID

TVNuevoLeon28.mx

### Stream URL

https://60ed5b6d0df78.streamlock.net:1936/canal28/canal28/chunklist_w1716907486.m3u8

### Notes

28.1 XHMNL TV Nuevo León Canal 28

Logo
https://lh3.googleusercontent.com/-2pp3dwi-vkQ/XznLWR76sUI/AAAAAAAA4i0
/nJvPb7KyiCMp3v5JVHky6GjltlEMChz8ACK8BGAsYHg/s0/2020-08-16.jpg
Website
https://www.nl.gob.mx/envivo-canal28
Guide
https://www.nl.gob.mx/publicaciones/programacion-semanal-de-canal-28

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
ID: XHMNLTDT.mx
https://60ed5b6d0df78.streamlock.net:1936/canal28/canal28/playlist.m3u8
