### ISSUE TITLE
Add: Canal 22.2

### ISSUE THREAD

**Issue by 3guajardo** [iptv-org/iptv#9595]
### Channel ID

Canal222.mx

### Stream URL

https://5fc584f3f19c9.streamlock.net/canal222/videocanal222/playlist.m3u8

### Notes

XEIMT-TDT
Canal 22.2 (480i)
Icon
https://raw.githubusercontent.com/ivantapia882804/rasta12/main/Emblems/can222.png

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Id: XEIMTTDT2.mx
Link is Geo-blocked.
