### ISSUE TITLE
Replace: OnceMexico.mx

### ISSUE THREAD

**Issue by 3guajardo** [iptv-org/iptv#9596]
### Broken Link

https://d24sa4vr9gvjv.cloudfront.net/index.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://vivo.canaloncelive.tv/alivepkgr3/ngrp:cepro_all/chunklist_b1431072.m3u8

### Notes

OnceMexico.mx

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by R4IN2007** [comment]
The Link Loads But Its A Different Channel 
Once Internacional
https://d24sa4vr9gvjv.cloudfront.net/index.m3u8

**Comment by Alstruit** [comment]
https://vivo.canaloncelive.tv/alivepkgr3/ngrp:cepro_all/playlist.m3u8

**Comment by 3guajardo** [comment]
Ohhh ok is a diferent content 
Im from notrh of México 
Nuevo León 
In this link can find the TDT Channels

11 Once México
11.1 Once Cant find
11.2 Once Niños Cant find



https://buscadortdt.ift.org.mx/

![tdt](https://user-images.githubusercontent.com/115971038/196630000-f858e289-0ffc-46a5-acf5-7db3989c1605.png)

**Comment by R4IN2007** [comment]
> Ohhh ok is a diferent content Im from notrh of México Nuevo León In this link can find the TDT Channels
> 
> 11 Once México 11.1 Once Cant find 11.2 Once Niños Cant find
> 
> https://buscadortdt.ift.org.mx/
> 
> ![tdt](https://user-images.githubusercontent.com/115971038/196630000-f858e289-0ffc-46a5-acf5-7db3989c1605.png)

Oh Hey About The Channel 11.2 Once Niños
Here A Link To The Channel m3u8

Once Niñas Y Niños [XEIPN-TDT 11.2]
http://jjooliveclarovideo.akamaized.net/Content/hls/Live/Channel(tveducationch01)/Stream(05)/index.m3u8
