### ISSUE TITLE
Add: RT Español

### ISSUE THREAD

**Issue by 3guajardo** [iptv-org/iptv#9597]
### Channel ID

RTenEspanol.ru

### Stream URL

https://rt-esp.rttv.com/live/rtesp/playlist.m3u8

### Notes

Please change RT Documentary Russian to RT Español in the Mexico List.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by ztreamhd** [comment]
Blocked in EU countries, probably working in other countries.

**Comment by Alstruit** [comment]
Already Exists. https://github.com/iptv-org/iptv/blob/6782376c0a7e6064779c861ac63427c66cbe7cc5/streams/ru.m3u#L339-L340
Closing.
