### ISSUE TITLE
Add: 14.1 XHSPRMT Canal Catorce

### ISSUE THREAD

**Issue by 3guajardo** [iptv-org/iptv#9599]
### Channel ID

CanalCatorce.mx

### Stream URL

https://60ed5b6d0df78.streamlock.net:1936/segundo/segundo/chunklist_w115456558.m3u8

### Notes

14.1 XHSPRMT Canal Catorce

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://60ed5b6d0df78.streamlock.net:1936/segundo/segundo/playlist.m3u8

**Comment by AntiPontifex** [comment]
Included in the next update: thank you.
