### ISSUE TITLE
Add: 2.1 XHX Las Estrellas

### ISSUE THREAD

**Issue by 3guajardo** [iptv-org/iptv#9600]
### Channel ID

LasEstrellas.mx

### Stream URL

https://video-weaver.lax03.hls.ttvnw.net/v1/playlist/CosFoQg066SDVOleI4nfCKErfC7HPG_563jW4G9GiX3lHyH0WWQYyKrV91XH0wtAFfruHEYN6F5hTRbZY1plxWA0XgyW1xenR_IMi8jb-HT9NRykNB6-lCi7nVz19XjifdQQ69Z30F6xiubmBmufabKcCfJhW_JxStrxmFQoY4tvycSfSkT_Fr1OmMcAhg79xzqyZ6AaJzRAlv7yIYEG9aBQBSVLs72r-QQVY5-V94OkfPLClyCeFy6NpURfRvemLdKSQxMkNSrVNBu5xZzhuUEJrY9QQRjU6rp0-IAP1U90nrPnbufFsp8eRkMicBNVk8BC2bTiAQEFY1NeJt5X8os6wgSdSHEdeNH7j-DOwDt2USlQwlVzM0V0nf4ku79l4RiWlMKrl2yxUbWqfBTdMhd5eC8sht0ysNRlMdCbTvfgYD7_ZRZEb5FiRamLtQ8pzhWrgzpNIfoEj2s8BiRHtCLiYJMV5cmfqXlUdorlVFGYnlG2KwULAMLSVyTH25KIM0snfjLA8QgZgrbSh-stv2wQSlL_StTEl5hWJXfdw9puEL9S8ptN-BBwm6rBaKK5lkog5PnoogvihuB2DkaBdGuDdlP7X562-5dCO5XGRJbB08daos296bkrhKtNSeEsUhFbMLkkHJx7AkzbrejrziPxMXd623QLH7w3B4HDTlaoLPyWaPE8jolv-UJ2pOxLdeY_q2y5O1owXaroLJD6vXi3eXoI_snSjwQSBmMVk--Ylla2QeAgahLLBF4Rvm0a7FuLbAWXE8grKIvGoPXepRPDFDmftXyE5sDeQen4DjpLByQKIMx36M5-InRV6LtkEZlTSbiXZBiT3YpH4dL0htoxiYSlcgrwlE9Quht6GgxvFlhnAxx_rP5uzNMgASoJZXUtd2VzdC0yMPcE.m3u8

### Notes

2.1 XHX Las Estrellas

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Link no longer works: please close.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/mx.m3u#L178-L179
