### ISSUE TITLE
Hong Kong Open TV will change name to HOY TV

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#9602]
### Channel ID

HongKongOpenTV.hk

### Stream URL

http://uc6.i-cable.com/live_freedirect/opentvhd001_h.live/playlist.m3u8

### Notes

Change the name to HOY TV
![HOY](https://user-images.githubusercontent.com/106740926/196155291-5fd1c18d-413f-4ff4-a432-0356294c9691.jpeg)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AzeemHadzrie** [comment]
Is it that true? Never saw that.

**Comment by darrencycheung** [comment]
> Is it that true? Never saw that.
> 
> Edit: yes but. Changed from Open TV to Anime something

It's true. Changed name to HOY TV 77.
![p634dfde1be66d](https://user-images.githubusercontent.com/106740926/196407983-b7e82a81-5c93-435a-8c71-998a17308159.png)

**Comment by Alstruit** [comment]
480p : http://uc6.i-cable.com/live_freedirect/opentvhd001.live/playlist.m3u8
