### ISSUE TITLE
Add: 5.1 XET Canal 5*

### ISSUE THREAD

**Issue by 3guajardo** [iptv-org/iptv#9607]
### Channel ID

Canal5.mx

### Stream URL

https://video-weaver.lax03.hls.ttvnw.net/v1/playlist/Co0FMcOCfQNud7GWztDFBXtzwLtqDXc7x9ZZNYX35EgxMRePEwpYD4-azpF3RQ-EdLrZIGRJfQ0Znqc6qKhnAWS905EAGLZYmH-dRpMratOWZRKNUA1FHdOW245caih0yOFzTVZn_Q8BtU0K8_1B2UdVEGDB_ZLYnDsOQ8wdJC1NRrMh0u9nTJ-_GO-l9qL-6Vki9vk4MDpCNPep9Xyv1V66MYZV9AA8ZANwGvlkjfyll6dAJoevqXghra2sLaXSMCBsVsA2IBfjJYsSopBuIJOqh-8PeeQE0qWUV258G3xqd5Bd063o-yl5lpTDdU9KaR42c4PgNWosutxsnw22surP4mIPTXUbKnxT9CDWoWxPBoZbYGIKGB9a8BgakdfWTnIHJ60DWbMVTm3xDCdOIPxHmB55nXB3koCTSKl2_nWwpZFOrmR_T_uA9TbTjhdbBka1v0aS1IrrPg0OQzh-j1hE4FeEAYGshUuLANHqfOgowdJBSLcKfVNQ-v5E3Fq31sv-O7qRcFzg460srjNC8Xz5SszfUaqMMuFt4B2nP577iheD4p6OuXEKrOh68yDqM0wC9OqpDctmVwAVuWg3ysZPvQQvt7UkfO8Eet1323RfkCoE6VB_OgRdshxB0Ip4yqHVZbCmAHexkDWkvdYfib2ikFaBkB-LZPbu--YSE3A6yT0wn_AaWdZxW7n0R6-PemO4xD9OsONqHO6Twl8fs1kX7voJIjvmn4U2p5leVYpPKePOmuVOWxB5KidVeLheQSWjULb-5PYZakGGwrS351hTr6ZxY4cTN14n9YNqgLT3B0sh4WfBkeGW5M6U1PwOs0e08CkXWRl3IJVKwMLHnrme-tPfuUIoTT0PCTpIhE0aDFRN8rOtLbUYLaHlhiABKglldS13ZXN0LTIw9wQ.m3u8

### Notes

5.1 XET Canal 5*

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
On list: please close.

**Comment by freearhey** [comment]
https://video-weaver.lax03.hls.ttvnw.net/v1/playlist/Co0FMcOCfQNud7GWztDFBXtzwLtqDXc7x9ZZNYX35EgxMRePEwpYD4-azpF3RQ-EdLrZIGRJfQ0Znqc6qKhnAWS905EAGLZYmH-dRpMratOWZRKNUA1FHdOW245caih0yOFzTVZn_Q8BtU0K8_1B2UdVEGDB_ZLYnDsOQ8wdJC1NRrMh0u9nTJ-_GO-l9qL-6Vki9vk4MDpCNPep9Xyv1V66MYZV9AA8ZANwGvlkjfyll6dAJoevqXghra2sLaXSMCBsVsA2IBfjJYsSopBuIJOqh-8PeeQE0qWUV258G3xqd5Bd063o-yl5lpTDdU9KaR42c4PgNWosutxsnw22surP4mIPTXUbKnxT9CDWoWxPBoZbYGIKGB9a8BgakdfWTnIHJ60DWbMVTm3xDCdOIPxHmB55nXB3koCTSKl2_nWwpZFOrmR_T_uA9TbTjhdbBka1v0aS1IrrPg0OQzh-j1hE4FeEAYGshUuLANHqfOgowdJBSLcKfVNQ-v5E3Fq31sv-O7qRcFzg460srjNC8Xz5SszfUaqMMuFt4B2nP577iheD4p6OuXEKrOh68yDqM0wC9OqpDctmVwAVuWg3ysZPvQQvt7UkfO8Eet1323RfkCoE6VB_OgRdshxB0Ip4yqHVZbCmAHexkDWkvdYfib2ikFaBkB-LZPbu--YSE3A6yT0wn_AaWdZxW7n0R6-PemO4xD9OsONqHO6Twl8fs1kX7voJIjvmn4U2p5leVYpPKePOmuVOWxB5KidVeLheQSWjULb-5PYZakGGwrS351hTr6ZxY4cTN14n9YNqgLT3B0sh4WfBkeGW5M6U1PwOs0e08CkXWRl3IJVKwMLHnrme-tPfuUIoTT0PCTpIhE0aDFRN8rOtLbUYLaHlhiABKglldS13ZXN0LTIw9wQ.m3u8 (offline)
<img width="829" alt="image" src="https://user-images.githubusercontent.com/7253922/232237459-5427fa8e-e83c-492c-b503-b6407acbf1ba.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/0b298909973cc68f0251bc000213982f45427bcf/streams/mx.m3u#L10-L11
