### ISSUE TITLE
Add: 7.1 XHFN Azteca Siete

### ISSUE THREAD

**Issue by 3guajardo** [iptv-org/iptv#9608]
### Channel ID

Azteca7NuevoLeon.mx

### Stream URL

https://video-weaver.lax03.hls.ttvnw.net/v1/playlist/CowFuxInJReN_TauUBWnCvNoBAn6kHdp2vKCZ55yV3tmSUGeR1UiVCVY-Ju-PF3ntrYvxZvv1_JohdmwnNIp6R4MyJrSefti1MxMJwcUGVQEA6b_Vx70OXtKZ3tGmArR-NwZarTJWnATWXsW2h0QDyGpfYkbVTDl-ZHvCJUW8xk7EgcGC-hVAuQ9S1TKFDLby5oDY4gdtx0e9XBrHeSkNHto0JxBdnFHddCpiHr7-pjJs193Cx-4r6S_Zfy-R2ezYYfcmZmVyGvbq_bg3-MmjSjK5E4jES0CS7Bz8T-awBIu_TJpf2e9r5B7ewHUtM4NJoJTuscHRRbADIPGy7HF9nywOYmxNSCbKAsqhY2_05_PNtx6iZgXl_35ykXKD-5b359eYbGfRJT78ybzb7KjBc6BtIr43G70ZGf6dPWxt2WN99LueP3YpJetg9j0WCxh_w0N7TmXsXFU6B4t_mlQFwEUYETGt7PADuXBxEshRJHpXYr_rHXbVXUtHpJKaSyfULW84okFn7ePWIMWMRVzF6HDGMAOP9QFhCQUaHEMfWcsQvICaYaDnCKp2CMsK-FCM_tcaLo6-gPPwlX8EKzXc3N6C6PBUbYuo0gNYcvGyqzsy3jVjzFasO_ZFdastZklONU9iyQ1Q4zjRGOSBLj773dihxRWPaVcB3fAEJwMDG3jwqRFjb969IB-NOfGf_dlGIWJBVjkkqmqd2Dnfsbi42ln3tIJFSRGxylJ-kXdzAmIH8ZnxpMRO2KADmGbv5YCRK3IUrSK88n9LwF8tYf4eOKQdKZoM0W4ZCbH4fC5WNkXjjlM1VWuHR_tfIii5lSC18wi9x0vv94Xy-kO4QuBTA-pdU-Mm9Ap6dQ7EUv0oBoMReuLfhS_RD7kJOolIAEqCWV1LXdlc3QtMjD3BA.m3u8

### Notes

7.1 XHFN Azteca Siete

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://vimeo.com/event/2495359/embed ?

**Comment by AntiPontifex** [comment]
On list: please close.

**Comment by freearhey** [comment]
https://video-weaver.lax03.hls.ttvnw.net/v1/playlist/CowFuxInJReN_TauUBWnCvNoBAn6kHdp2vKCZ55yV3tmSUGeR1UiVCVY-Ju-PF3ntrYvxZvv1_JohdmwnNIp6R4MyJrSefti1MxMJwcUGVQEA6b_Vx70OXtKZ3tGmArR-NwZarTJWnATWXsW2h0QDyGpfYkbVTDl-ZHvCJUW8xk7EgcGC-hVAuQ9S1TKFDLby5oDY4gdtx0e9XBrHeSkNHto0JxBdnFHddCpiHr7-pjJs193Cx-4r6S_Zfy-R2ezYYfcmZmVyGvbq_bg3-MmjSjK5E4jES0CS7Bz8T-awBIu_TJpf2e9r5B7ewHUtM4NJoJTuscHRRbADIPGy7HF9nywOYmxNSCbKAsqhY2_05_PNtx6iZgXl_35ykXKD-5b359eYbGfRJT78ybzb7KjBc6BtIr43G70ZGf6dPWxt2WN99LueP3YpJetg9j0WCxh_w0N7TmXsXFU6B4t_mlQFwEUYETGt7PADuXBxEshRJHpXYr_rHXbVXUtHpJKaSyfULW84okFn7ePWIMWMRVzF6HDGMAOP9QFhCQUaHEMfWcsQvICaYaDnCKp2CMsK-FCM_tcaLo6-gPPwlX8EKzXc3N6C6PBUbYuo0gNYcvGyqzsy3jVjzFasO_ZFdastZklONU9iyQ1Q4zjRGOSBLj773dihxRWPaVcB3fAEJwMDG3jwqRFjb969IB-NOfGf_dlGIWJBVjkkqmqd2Dnfsbi42ln3tIJFSRGxylJ-kXdzAmIH8ZnxpMRO2KADmGbv5YCRK3IUrSK88n9LwF8tYf4eOKQdKZoM0W4ZCbH4fC5WNkXjjlM1VWuHR_tfIii5lSC18wi9x0vv94Xy-kO4QuBTA-pdU-Mm9Ap6dQ7EUv0oBoMReuLfhS_RD7kJOolIAEqCWV1LXdlc3QtMjD3BA.m3u8 (offline)
<img width="827" alt="image" src="https://user-images.githubusercontent.com/7253922/232237502-21e587ea-ff92-440b-8256-1786122d524b.png">

http://free.fullspeed.tv/iptv-query?streaming-ip=https://vimeo.com/event/2495359/embed (offline)
<img width="633" alt="image" src="https://user-images.githubusercontent.com/7253922/232237524-3a94df25-3730-4eeb-9eaa-bb665cb5cb18.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/database/blob/master/data/blocklist.csv#L30
