### ISSUE TITLE
Add: 8.1 HeraldoTV

### ISSUE THREAD

**Issue by 3guajardo** [iptv-org/iptv#9610]
### Channel ID

HeraldoTV.mx

### Stream URL

https://stream-04.sv4.dailymotion.com/sec(6TMM0QrMj9Q4IwNZkxGVRIjM3kpik2_ec3LPGuKK5Uj-6h6KN923GwlRbgx5SX7n)/dm/3/x88epch/d/live-0.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
ID: XHTRESTDT.mx
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/heraldodemexico
