### ISSUE TITLE
Add: KLNM-LD (Lufkin, TX)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#9645]
### Channel ID

KLNMLD1.us

### Stream URL

https://broadcast.mytvtogo.net/klmntv/klmntv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
The ID appears to be KLNMLD1.us.

**Comment by R4IN2007** [comment]
> The ID appears to be KLNMLD1.us.

Ok 👍

**Comment by R4IN2007** [comment]
New Link
https://59d39900ebfb8.streamlock.net/texasfamilytv/texasfamilytv/playlist.m3u8
