### ISSUE TITLE
Replace: Bulgaria On Air

### ISSUE THREAD

**Issue by Alstruit** [iptv-org/iptv#9665]
### Broken Link

http://hls.cdn.bg:2006/fls/bonair.stream/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://lb-hls.cdn.bg/2006/fls/bonair.stream/playlist.m3u8?at=

### Notes

https://i.cdn.bg/live/DUH6Ngk5qd -> clip: {sources: [src: (m3u8 link)}].
m3u8 link : //lb-hls.cdn.bg/2006/fls/bonair.stream/playlist.m3u8?at={token}.
Needs to prepend with http or https and a valid token to work.
Not sure how long the token will last.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Basically the same issue with Sportal.

**Comment by freearhey** [comment]
Broken link removed from playlist.
