### ISSUE TITLE
Add: Sinovision

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#9667]
### Channel ID

Sinovision.cn

### Stream URL

https://jpts.sinovision.net/livestream.m3u8

### Notes

Add it
Valid m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
URL already exists but will include missing ID.
