### ISSUE TITLE
Add: W14DK-D 14.1 TV Delmarva

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#9668]
### Channel ID

W14DKD1.us

### Stream URL

https://2-fss-2.streamhoster.com/pl_118/amlst:204972-1949480/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Maybe geo-blocked? Anyway, thank you for the stream; it will be added in my next update.
