### ISSUE TITLE
Add: W14DK-D 14.4 WX Channel - Weather Channel (Delmarva)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#9671]
### Channel ID

W14DKD4.us

### Stream URL

https://2-fss-2.streamhoster.com/pl_118/204972-1954030-1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream; will be added in my next update.
