### ISSUE TITLE
Add: W14DK-D 14.5 All Sports Television Network 

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#9672]
### Channel ID

W14DKD5.us

### Stream URL

https://2-fss-2.streamhoster.com/pl_118/204972-2205186-1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by eklins** [comment]
the stream url same with W14DK-D 14.4 WX Channel - Weather Channel (Delmarva).
Please take note, tq.

**Comment by AntiPontifex** [comment]
Now OAN Plus; thank you for the stream. Will be added in my next update.
