### ISSUE TITLE
Add: Lincolnwood Community Television

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9695]
### Channel ID

LWDTV.us

### Stream URL

Lincolnwood Community Television

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
https://stream2.earthchannel.com/LincolnwoodILLIVE/LincolnwoodILLIVE.stream/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you, Sphinxroot
