### ISSUE TITLE
Replace: CaracolTelevision.co

### ISSUE THREAD

**Issue by nomadmzl** [iptv-org/iptv#9697]
### Broken Link

https://mdstrm.com/live-stream-playlist/574463697b9817cf0886fc17.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
you need to add the caracoltv.com referrer over the link for it to work.

> {"status":"ERROR","data":"REFERRER","message":"No estás autorizado para utilizar la señal en vivo de Caracol Televisión."}
> 
> Here A New Link: https://mdstrm.com/live-stream-gdai/574463697b9817cf0886fc17/linear/hls/pa/event/3csP3jVSTr-D1F-4lpxWng/stream/e46ae03e-37c8-42b1-830e-ebc725e928ec:CHS/master.m3u8


![image](https://user-images.githubusercontent.com/30985701/197578871-24f5ac2f-4499-4eab-a940-07a9b7b739ed.png)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/pull/12353#discussion_r1167815903
