### ISSUE TITLE
Replace: Teleantioquia.co

### ISSUE THREAD

**Issue by nomadmzl** [iptv-org/iptv#9699]
### Broken Link

https://liveingesta118.cdnmedia.tv/teleantioquialive/smil:dvrlive.smil/playlist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by R4IN2007** [comment]
There's A 403 Forbidden Error

**Comment by LaneSh4d0w** [comment]
you need the cdningesta referrer for it to work.

**Comment by Alstruit** [comment]
Closing since the link works with referrer.
