### ISSUE TITLE
Replace: Telecafe.co

### ISSUE THREAD

**Issue by nomadmzl** [iptv-org/iptv#9700]
### Broken Link

https://liveingesta118.cdnmedia.tv/telecafelive/smil:dvrlive.smil/playlist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Alstruit** [comment]
Closing since the link works with referrer.
