### ISSUE TITLE
Add: 

### ISSUE THREAD

**Issue by kikar92** [iptv-org/iptv#9703]
### Channel ID

2m.maroc

### Notes

Hi,

Can any one add 2m from Morocco please.

Thank you

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by ztreamhd** [comment]
I'm pretty sure it's already in the `ma.m3u` list, but here it is:

2M Maroc (360p) - https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/2m_monde/hls_video_ts_tuhawxpiemz257adfc/index.m3u8?DVR

**Comment by kikar92** [comment]
> I'm pretty sure it's already in the `ma.m3u` list, but here it is:
> 
> 2M Maroc (360p) - https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/2m_monde/hls_video_ts_tuhawxpiemz257adfc/index.m3u8?DVR

I did try it i use https://iptv-org.github.io/iptv/languages/ara.m3u if any one can add it that will be great
