### ISSUE TITLE
Add: Ekiz TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9705]
### Channel ID

EkizTV.cl

### Stream URL

https://video-weaver.yto01.hls.ttvnw.net/v1/playlist/Cv0Eeu0N-1K9uysKEQak98mJ5txlynEOAOwWbUIcx47Lhi1m66cKY9O8yxv2J3UTnApkUfVuv3dfCE5WYGXRB5cDLE-nz_YTlYGXiaY73e8LtRcB0xg8EWdJLfw0UE8EkzcpppfKDIWe1pOUZrXBXA7n768jDerpIctzBvtu5dRkydA3Yae0XMTHYQoV9jgUN2YGos7RZPp9g52YLoKTJbUfC1BQ11LQo24gLkh3quObNkIgu3x_TevpKby5yYykuPYAWu-ofnjJehupM5acTnJmFbvN-hHnIFJSdPXGEoOyHGf_AbBWMbATkmxEeRfTZNNo-4mqSTOUaD9NIyTfpcr3RbWGQf7gFMj1gXszZ3pfke3zphiz3DSyMstZwZz8cKGeZ5rponURFsYM5Ywa3YIOitlTS-LHA5Az6GVy55c368sBJs2OK1QboTWjMtgHpSibaA9dFKaodl_U6vrm0Bl55yeRG2ZFT9wRJo9VC60Ytfh6WLwETwDwweERhckmN7KPUZ6EnJkKUuYEWLEfpbEuY3kpEkgNsRhPfy9pSISbHsKvnCUMO72RUrph1jPtfeD1ZLvMtJsJj9lYxbbUhCSiGyDpDs5itaXswj4wB4oWNOcd5NdONEX9aSWMhoAEv7UM17-76VGIhuA0PdMKU4wC_EIrMoAFeS1QJfIZ_4bLSayyI8q_leJ_6yYLJUcF9CJ-HVs-Vk8fUi0uz9VhPQqXrfZKpag_RbI4WTgQQSHd5KPPKxuCLIXcPvQJ5v_B5YZqUB4KP8azdJhWV3PLnlwjEiiyXUPuCRuRZJnKDOCRmp0BQMiHCij2xkE5fhk6QmIUJ4JhToWw62pWvE5qNRoMvSv9EQpMNKnY9ehdIAEqCXVzLWVhc3QtMTCzAw.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
Twitch-Tokened

**Comment by AntiPontifex** [comment]
Oh well. Thanks anyway.

**Comment by Sphinxroot** [comment]
free full speed + https://www.twitch.tv/ekiztelevision
