### ISSUE TITLE
Add: Generacion Kpop

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9709]
### Channel ID

GeneracionKpop.cl

### Stream URL

https://youtu.be/0-RirLdUYEE

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
LiveStream is from South Korea

**Comment by LaneSh4d0w** [comment]
ALL THE K-POP is already available, South Korean channel, I believe it's a big label from there that has it;
