### ISSUE TITLE
All Trace channels on FR.m3u not working

### ISSUE THREAD

**Issue by cybotx1024** [iptv-org/iptv#971]
Trace Afrika
Trace Kitoko
Trace Mziki
Trace Naija
Trace Toca
Trace Tropical
Trace Urban

All the Trace channels above just stopped working all at the same time. Looks like expired links
Is it possible to fix?

**Comment by freearhey** [comment]
Thank you for bringing this to our attention. I already removed the broken links. As soon as there's a replacement, we'll get them back.

**Comment by t-andre** [comment]
Hi,

For the Trace channel's have always worked and they still work.

Cheers

**Comment by Guegray** [comment]
Any news ?
