### ISSUE TITLE
DMCA takedown notices from Weather Group Television, LLC

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#9729]
> Hi iptv-org,
> 
> I'm contacting you on behalf of GitHub because we've received a DMCA takedown notice regarding the following content:
> 
> https://github.com/iptv-org/iptv/blob/master/streams/us.m3u
> https://github.com/iptv-org/iptv/blob/master/streams/us_tubi.m3u
> https://iptv-org.github.io/iptv/countries/us.m3u
> 
> We're giving you 1 business day to make the changes identified in the following notice:
> 
> https://github.zendesk.com/attachments/token/HcUVxYElaiEHGV7bPAKH8U2KO/?name=2022-10-25-the-weather-group.rtf
> 
> If you need to remove specific content from your repository, simply making the repository private or deleting it via a commit won't resolve the alleged infringement. Instead, you must follow these instructions to remove the content from your repository's history, even if you don't think it's sensitive:
> 
> https://docs.github.com/articles/remove-sensitive-data
> 
> Once you've made changes, please reply to this message and let us know. If you don't tell us that you've made changes within the next 1 business day, we'll need to disable the entire repository according to our GitHub DMCA Takedown Policy:
> 
> https://docs.github.com/articles/dmca-takedown-policy/
> 
> If you believe your content on GitHub was mistakenly disabled by a DMCA takedown request, you have the right to contest the takedown by submitting a counter notice, as described in our DMCA Takedown Policy.
> 
> PLEASE NOTE: It is important that you reply to this message within 1 business day to tell us whether you've made changes. If you do not, the repository will be disabled.

**Comment by baliebox4916** [comment]
somebody needs to fix this quick

my mom and i use this iptv client all the time

if this iptv service gets disabled, we will have nothing to watch

**Comment by freearhey** [comment]
> Hi IPTV,
> 
> Thanks for letting us know you've made changes! We'll pass them along to the copyright holder, and let you know if they have any other concerns.
> 
> Regards,
> 
> GitHub Trust & Safety
