### ISSUE TITLE
Add: Euronews Serbia

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9764]
### Channel ID

EuronewsSerbia.rs

### Stream URL

https://d1ei8ofhgfmkac.cloudfront.net/app-19518-1306/ngrp:QoZfNjsg_all/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Done.

**Comment by bumabacha** [comment]
no works :-(
