### ISSUE TITLE
Replace: AccessSarasota.us

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9775]
### Broken Link

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCqHDwKPPOhzLmtb4TvwIZZQ/live

### What happened to the stream?

Not loading

### Possible Replacement

https://youtu.be/QnwjTTAwNRY

### Notes

Does not seem to be geo-blocked, so...

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Alstruit** [comment]
Sometimes fullspeed.tv is down, but it does work now. Closing.

**Comment by AntiPontifex** [comment]
Thanks: I'll keep that in mind.
