### ISSUE TITLE
Replace: WPHL DT2 Antenna TV is not working 

### ISSUE THREAD

**Issue by Gitbone94** [iptv-org/iptv#9777]
### Broken Link

http://v-pi.theus6tv.duckdns.org/hls/17.2/playlist.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

Unknown

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment]
Broken link removed from playlist.
