### ISSUE TITLE
Add: Sport en France

### ISSUE THREAD

**Issue by Smark223** [iptv-org/iptv#9784]
### Channel ID

SportenFrance.fr

### Stream URL

https://sp1564435593.mytvchain.info/live/sp1564435593_720/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/f97f915f3e18a22b6fdce0077b47db22c269a128/streams/fr.m3u#L144-L145
