### ISSUE TITLE
Add: WPS-TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9791]
### Channel ID

WPSTV.us

### Stream URL

https://playback2.akamaized.net/streams/12013978_8776061_lsig1vpid82he2sa6xl_1/exp=1666991043~acl=%2f*~data=hdntl~hmac=a04ca5b0e42bae59eb6819f87c2aa0bcdf70a992c1a301b201cf3a7061d18763/media/12013978_8776061_lsig1vpid82he2sa6xl_1@1628000p.m3u8?dw=14400&ts=1666904400

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://api.new.livestream.com/accounts/12013978/events/8776061

**Comment by AntiPontifex** [comment]
Thank you, sir
