### ISSUE TITLE
Astro Awani Cloudfront m3u8

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#9802]
### Channel ID

AstroAwani.my

### Stream URL

https://d2idp3hzkhjpih.cloudfront.net/out/v1/4b85d9c2bf97413eb0c9fd875599b837/index.m3u8

### Notes

Better m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AzeemHadzrie** [comment]
Works via VLC, adding them via #9718.
