### ISSUE TITLE
Add: Cronica TV [AR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9807]
### Channel ID

CronicaTV.ar

### Stream URL

https://is-tucuman.cdn.rcs.net.ar/mnp/cronica_hls/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Link is unstable.
