### ISSUE TITLE
Add: Télévision Communautaire de Témiscaming-Kipawa

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#9808]
### Channel ID

tvcTK.ca

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/tvctklive

### Notes

Temiscaming-Kipawa Community television in Québec Canada.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next update.

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/tvctklive (offline)
<img width="554" alt="image" src="https://user-images.githubusercontent.com/7253922/232170349-bab22574-1926-4816-9e30-aa192a3c3473.png">
