### ISSUE TITLE
Add: TV Témis

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#9809]
### Channel ID

tvtemis.ca

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://youtu.be/IXBuj_NEY90

### Notes

Temiscamingue community television in Québec Canada.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/LaT%C3%A9l%C3%A9visionCommunautaireduT%C3%A9miscamingue/live

**Comment by albghost** [comment]
m3u8 sports europe?
