### ISSUE TITLE
Add: Corporation de Télévision Brandon (CTB TV)

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#9810]
### Channel ID

CTBTV.ca

### Stream URL

https://fl001.elpcinc.com/CTB-TV/tracks-v1a1/mono.m3u8

### Notes

Lanaudière Community television in Quebec Canada

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://fl001.elpcinc.com/CTB-TV/tracks-v1a1/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next update.
