### ISSUE TITLE
Add: TCFTV

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#9811]
### Channel ID

TCFTV.ca

### Stream URL

http://66.11.33.44:8081/live/TCF/chunks.m3u8

### Notes

Montréal community television
Edit : Full name is Télévision Communautaire Frontenac

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
http://66.11.33.44:8081/live/TCF/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next update.
