### ISSUE TITLE
Add: Assemblée Nationale du Québec

### ISSUE THREAD

**Issue by Time-Pare** [iptv-org/iptv#9812]
### Channel ID

CanaldelAssemblee.ca

### Stream URL

https://cdn3.wowza.com/5/SVEySlNEQ0FOWXlS/diffusion/canal17/chunklist.m3u8

### Notes

Quebec National Assembly Channel

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://cdn3.wowza.com/5/SVEySlNEQ0FOWXlS/diffusion/canal17/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next update.
