### ISSUE TITLE
Add: CMB Television

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9818]
### Channel ID

CMBTelevision.co

### Stream URL

https://customer-gllhkkbamkskdl1p.cloudflarestream.com/eyJhbGciOiJSUzI1NiIsImtpZCI6ImI3YmIwODNmMDhkNmQ5NWExZjIzZWE3ZWRhOWY4NTZhIn0.eyJzdWIiOiI3MWY4NTE3N2UwMmQ1NGFlMDY2N2U2Y2RhYWE2NmEyMiIsImtpZCI6ImI3YmIwODNmMDhkNmQ5NWExZjIzZWE3ZWRhOWY4NTZhIiwiZXhwIjoxNjY3MTE1OTA1LCJhY2Nlc3NSdWxlcyI6W3sidHlwZSI6ImlwLmdlb2lwLmNvdW50cnkiLCJhY3Rpb24iOiJibG9jayIsImNvdW50cnkiOlsiUlUiLCJCWSJdfV19.kkXVHIMHiiJcZop0SbCdWkMsHoSGElMsqzxxpbtXRqb2ThaLlWYlzmBX2Yj4ZZFj5kSSEpdMHKxU3mbRaAcvtjmVZTXYeOrpww0UZFul0OWrlUJiktBAYmjzryaVlfjUfuUdL1b6eOA1rQWrl_wt8ziRK89RqInoWfw5SbM5A5XRWT4ljNqnc1jXusAmlCQoo40XD05YyG0ykCwz2Sj0P83WMVuVLI35Z47kiotE-w-PXPnFGO0O0B6Qc94OumwXanl0bWZJru777pOcwe0zzeAA83YTXYZ1g2IE4ZVWVmVMw_PdaBBXGMJtwbmaevWt8yipScu4ROXg_m2G7rQLFw/manifest/stream_t2_r999999999.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by benevenstanciano** [comment]
The bit in the middle is a JWT, JSON Web Token, which has an expiry date. Also interesting that the bulk of the token is about blocking access from Russia and Belarus :)
