### ISSUE TITLE
Add: Cartoonito Italia

### ISSUE THREAD

**Issue by omaromarver** [iptv-org/iptv#9822]
### Channel ID

Cartoonito Italia

### Stream URL

https://mediasetinfinity.mediaset.it/diretta/kids_cLA

### Notes

1-i think its geo-blocked to italy only so you need an italy vpn to access the page and cartoonito

2-if you can extract the stream from there it would be great

thanks

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Link is Geo-blocked.

**Comment by cohendjdjd** [comment]
Has Any One Got Cartoonito Uk Stream

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/3620df8b680ea72493935000091b671570340619/streams/it.m3u#L571-L572
