### ISSUE TITLE
Add: Nex Panama

### ISSUE THREAD

**Issue by Lucoasan** [iptv-org/iptv#9827]
### Channel ID

NexCentralAmerica.pa

### Stream URL

https://nexpanama.com/en-vivo/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already in playlist: please close.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/pa.m3u#L12-L13
