### ISSUE TITLE
Add Arabic language list

### ISSUE THREAD

**Issue by MoonSyria** [iptv-org/iptv#984]
Hi

We can add or modify Arabic channels by countries but this is so confusing. I suggest making Arabic.m3u in channels folder, and we can add/remove/fix all channels in one file.

**Comment by freearhey** [comment]
I just feel like taking the Arabic channels to a separate playlist while all the others are sorted by country would be more confusing.

**Comment by Link4K** [comment]
We should keep it by country. https://iptv-org.github.io/iptv/languages/ar.m3u gets generated based on the tvg-language field
