### ISSUE TITLE
Add: Activa TV [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9840]
### Channel ID

ActivaTV.es

### Stream URL

https://streamtv.mediasector.es/hls/activatv/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
