### ISSUE TITLE
Add: Super3 [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9841]
### Channel ID

CanalSuper3.es

### Stream URL

https://directes-tv-es.ccma.cat/live-origin/super3-hls/master.m3u8

### Notes

(Geo-blocked)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be added in the next release.
