### ISSUE TITLE
Add: LATAM TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9848]
### Channel ID

LATAMTV.co

### Stream URL

https://playback2.akamaized.net/streams/29967371_9594543_lsi9cjcefp556nj0k45_1/exp=1667267595~acl=%2f*~data=hdntl~hmac=777e1463752a84c123d36a4dd16bc247e7f37e3e1cabaeb33734f2ac440aa29a/media/29967371_9594543_lsi9cjcefp556nj0k45_1@2256000p.m3u8?dw=14400&ts=1667178000

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
![image](https://user-images.githubusercontent.com/30985701/198981508-6f5f6d8c-39c4-437b-ac6c-a941bed8cec4.png)
