### ISSUE TITLE
Replace: astro channels (cricket, arena etc)

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9852]
### Broken Link

all of them

### What happened to the stream?

Not loading

### Notes

Simply do not work; geo-blocked?

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Planned for removal on my maintenance PR.

**Comment by AzeemHadzrie** [comment]
Well, those ones are supposed to work last time, but now they don't.

**Comment by trancer1994** [comment]
Can't you look on their IPTV platform and get the links from there?

**Comment by AntiPontifex** [comment]
Thanks, Lane
