### ISSUE TITLE
Add: Hamaika Telebista [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9853]
### Channel ID

HamaikaTelebista.es

### Stream URL

https://cdn3.wowza.com/1/RERMR282dnU5eE5Z/OHY0dVFs/hls/live/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
