### ISSUE TITLE
Add: Huelva TV [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9854]
### Channel ID

HuelvaTV.es

### Stream URL

https://5d8d85cf2c308.streamlock.net:1936/huelvatv/htvdirecto/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
