### ISSUE TITLE
Add: La Fabrica TV [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9855]
### Channel ID

LaFabricaTV.es

### Stream URL

https://mejorestrucos.com:5443/LiveApp/streams/854077030689510682594068.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next release.
