### ISSUE TITLE
Add: Lancelot TV [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9856]
### Channel ID

LancelotTV.es

### Stream URL

https://5c0956165db0b.streamlock.net:8090/directo/_definst_/lancelot.television/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
