### ISSUE TITLE
Add: PTV Málaga [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9857]
### Channel ID

PTV.es

### Stream URL

http://iptv.services.everywan.net:8080/martv-web/video.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
