### ISSUE TITLE
Add: Radio Television Mogan [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9859]
### Channel ID

RadioTelevisionMogan.es

### Stream URL

https://cloudvideo.servers10.com:8081/8028/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
