### ISSUE TITLE
Add: RTVCE [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9860]
### Channel ID

RTVCE.es

### Stream URL

https://cdnlive.shooowit.net/rtvcelive/channel1.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next update.
