### ISSUE TITLE
Add: Tac12 [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9861]
### Channel ID

Tac12.es

### Stream URL

https://ingest1-video.streaming-pro.com/nimble/tac12/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
