### ISSUE TITLE
Add: TEF [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9862]
### Channel ID

TEF.es

### Stream URL

https://5940924978228.streamlock.net/EIVISSA_1/EIVISSA_1/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
