### ISSUE TITLE
Add: Television Aranda [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9864]
### Channel ID

TelevisionAranda.es

### Stream URL

https://cloud.streamingconnect.tv/hls/telearanda/telearanda.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on the list: please close.
