### ISSUE TITLE
Add: TPA 7 [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9865]
### Channel ID

TPA7.es

### Stream URL

https://cdnlive.codev8.net/rtpalive/directo.smil/chunklist_b1000000_DVR.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by ztreamhd** [comment]
`https://cdnlive.codev8.net/rtpalive/directo.smil/chunklist_b1700000_DVR.m3u8` for 576p resolution and `https://cdnlive.codev8.net/rtpalive/directo.smil/playlist_DVR.m3u8` for the master file.
