### ISSUE TITLE
Add: TV L'Hospitalet [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9868]
### Channel ID

TVLHospitalet.es

### Stream URL

https://liveingesta118.cdnmedia.tv//tvhospitaletlive/smil:tvhospitalet.smil/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be added in the next update.
