### ISSUE TITLE
Add: Vivamovil [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9869]
### Channel ID

Vivamovil.es

### Stream URL

https://5d8d85cf2c308.streamlock.net:1936/AlcalaTV/endirecto/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.
