### ISSUE TITLE
Add: Torrevision [ES]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9870]
### Channel ID

Torrevision.es

### Stream URL

https://api.new.livestream.com/accounts/2614936/events/10365077/live.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already added to list: please close.
