### ISSUE TITLE
Add: CNA Akamaized m3u8

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#9871]
### Channel ID

CNAInternational.sg

### Stream URL

https://mediacorp-videosbclive.akamaized.net/dd724cfb0e8e4cdc921bbc4ac94614bf/ap-southeast-1/6057994443001/profile_1/chunklist.m3u8

### Notes

Akamaized one

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AzeemHadzrie** [comment]
This shares the same one as the normal feed, but the show "Japan Time" gets censored from that stream.
