### ISSUE TITLE
Add: GBC TV [GI]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9872]
### Channel ID

GBCTV.gi

### Stream URL

https://player-api.new.livestream.com/accounts/14143407/events/9828641/broadcasts/233548882.secure.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://api.new.livestream.com/accounts/14143407/events/9828641

**Comment by freearhey** [comment]
Closed in favor of #12225
