### ISSUE TITLE
Broken Stream: Bounce TV

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#9875]
### Broken Link

https://5e6cea03e25b6.streamlock.net/live/BOUNCE.stream/playlist.m3u8

### What happened to the stream?

Not loading

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
Where is it located ? Can't seem to remember we've wrote myBTV links in clear anywhere in our repos.

**Comment by MapGuy11** [comment]
Let's just close

**Comment by spotanjo3** [comment]
My mistake: Fix it. Look it up again. us.m3u8

**Comment by MapGuy11** [comment]
> That's normal for this one I believe, it's from the Talhassee server that used to be on here for some time.

Yeah, they are all 403 unless you live in that area.

**Comment by spotanjo3** [comment]
So this link is working ? VPN ? I am in the USA.. Up North.
