### ISSUE TITLE
Playlists not updating

### ISSUE THREAD

**Issue by Link4K** [iptv-org/iptv#988]
e.g: 

https://iptv-org.github.io/iptv/languages/ar.m3u still contains removed link https://github.com/iptv-org/iptv/commit/bbff4418931b3119c867e551a0103c65507cf4f4#diff-ad7681d83addf907e8b446b1ac3bc1f5

**Comment by freearhey** [comment]
You're right, there was an error during the daily automatic update. I'll try to fix it as soon as possible.

**Comment by Link4K** [comment]
Fixed
