### ISSUE TITLE
Add: PSC Television

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9889]
### Channel ID

PSCTelevision.co

### Stream URL

https://cloud28.vsgtech.co:3052/live/psctvlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://cloud28.vsgtech.co:3008/hybrid/play.m3u8 Tecno Films Stereo (same host)
