### ISSUE TITLE
Add: Suram TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9890]
### Channel ID

SuramTV.co

### Stream URL

https://livetv.305streamhd.com:3111/multi_live/play_360.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://livetv.305streamhd.com:3266/live/osoriollive.m3u8 Radio La Voz de Restauracion
