### ISSUE TITLE
Add: Tele Vid

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9892]
### Channel ID

TeleVid.co

### Stream URL

https://liveingesta119.cdnmedia.tv/televidtvlive/smil:dvrlive.smil/playlist.m3u8?DVR

### Notes

Need help with this stream: thanks.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
a referer to cdnmedia.tv is needed.
