### ISSUE TITLE
Add: NDR Fernsehen International

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#9895]
### Channel ID

NDRFernsehenInternational.de

### Stream URL

https://ndrint.akamaized.net/hls/live/2020766/ndr_int/index.m3u8

### Notes

Must-have channel

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by darrencycheung** [comment]
Streamtest.in tested error, maybe geo-blocked but still could work.

**Comment by AzeemHadzrie** [comment]
Tested on VLC, available in Malaysia also.
