### ISSUE TITLE
Add: Sports News Highlights

### ISSUE THREAD

**Issue by fotvnetwork** [iptv-org/iptv#9900]
### Channel ID

SportsNewsHighlights.us

### Stream URL

https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg01756-newsnet-sportsnewshigh-ono/playlist.m3u8

### Notes

New sports news channel, a sister station of NewsNet
https://sports.newsnetmedia.com/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream; it will be added in the next us.m3u update.
