### ISSUE TITLE
Add: Zuldemayda Canal 13

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9905]
### Channel ID

ZuldemayaCanal13.co

### Stream URL

https://movil.ejeserver.com/live/zuldemayda.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
https://github.com/iptv-org/iptv/blob/584670f45deae3c7079cf49de08b367b79816e94/streams/co.m3u#L108-L111

**Comment by AntiPontifex** [comment]
Thanks, Lane.
