### ISSUE TITLE
Add: Guatuso TV

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9914]
### Channel ID

GuatusoTV.cr

### Stream URL

https://5cf4a2c2512a2.streamlock.net/8162/8162/chunklist_w902657538.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://5cf4a2c2512a2.streamlock.net/8162/8162/master.m3u8
