### ISSUE TITLE
Add: Oldies Hits

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9919]
### Channel ID

OldiesHits,cr

### Stream URL

https://video01.logicahost.com.br/oldieshits/oldieshits/chunklist_w794351848.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://video01.logicahost.com.br/oldieshits/oldieshits/playlist.m3u8
