### ISSUE TITLE
Add: San Vito Television

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9922]
### Channel ID

SanVitoTelevision.cr

### Stream URL

https://stmv.streamingvip.click/sanvitotv/sanvitotv/chunklist_w2107163959.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://stmv.streamingvip.click/sanvitotv/sanvitotv/playlist.m3u8
