### ISSUE TITLE
Replace: CroTVHD.de

### ISSUE THREAD

**Issue by AntiPontifex** [iptv-org/iptv#9926]
### Broken Link

https://crotvhd.net/youtube/

### What happened to the stream?

Not loading

### Notes

Broken.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment]
https://www.twitch.tv/crotv385
