### ISSUE TITLE
Add: Superyacht TV

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#9928]
### Channel ID

SuperyachtTV.mc

### Stream URL

https://12858.cdn.mobibase.com/token/hls/733/254_1000k/playlist.m3u8?nva=20221102120655&service_id=12858&uuid=0e0a63624f4fce19b463472934&token=0045275998b7bb7524e18

### Notes

New channel to launch on IPTV ORG

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by kaikyoofers** [comment]
Tokened.

**Comment by freearhey** [comment]
https://12858.cdn.mobibase.com/token/hls/733/254_1000k/playlist.m3u8?nva=20221102120655&service_id=12858&uuid=0e0a63624f4fce19b463472934&token=0045275998b7bb7524e18 (offline)
<img width="837" alt="image" src="https://user-images.githubusercontent.com/7253922/232238344-86c8692b-fe71-40d7-a0e8-aaccf77a39da.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/861169502d1e8d6e9de628a930170308b7d0353a/streams/mc.m3u#L4-L5
