### ISSUE TITLE
MTV-LEB-

### ISSUE THREAD

**Issue by abormze** [iptv-org/iptv#9947]
### Channel ID

MTV

### Stream URL

https://www.elahmad.com/tv/watchtv.php?id=mtv_lebanon

### Notes

Stream URL
https://cllive.itworkscdn.net/mtvlebanonlive/token=nva=1652371286~~dirs=1~~hash=0aa600a3219e0ac7d388c/mtvlive.smil/murrtelevision_chunks.m3u8

Notes
https://cllive.itworkscdn.net/mtvlebanonlive/token
THIS stream have token how to fix it? any one have fix

https://cllive.itworkscdn.net/

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
https://live.3cd.io/live/v1/broadcast/mtv/tracks-v1a1/mono.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/36a81b417b9370c09d8800f6e0c0add543b95c19/streams/lb.m3u#L22-L26
