### ISSUE TITLE
Add: Now-TV [BW]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9964]
### Channel ID

NowTV.bw

### Stream URL

https://delivery.upictv.co.bw/NOW-TV-DNL/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment]
https://delivery.upictv.co.bw/NOW-TV-DNL/index.m3u8
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/7253922/232238446-2ce75ae5-6030-4f0c-8679-37ca51feb8e1.png">

**Comment by freearhey** [comment]
Shows only the provider logo:
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/7253922/233798966-1c6a05df-0ad3-4222-b9c2-214cfbf7dfb7.png">

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/861169502d1e8d6e9de628a930170308b7d0353a/streams/bw.m3u#L2-L3
