### ISSUE TITLE
Add: TVes [VE]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#9965]
### Channel ID

TVes.ve

### Stream URL

https://edge1o.live.opencaster.com/caster/erCkqDzdGzpj.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Sadly we can't deal with Opencaster links. Closing.
