### ISSUE TITLE
Add: Zhejiang TV International 

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#9967]
### Channel ID

ZhejiangSatelliteTVInternational.cn

### Stream URL

https://hw-m-l.cztv.com/channels/lantian/channel10/1080p.m3u8

### Notes

New channel

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next update.
