### ISSUE TITLE
Add: Record News Normal m3u8

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#9968]
### Channel ID

RecordNews.br

### Stream URL

https://stream.ads.ottera.tv/playlist.m3u8?network_id=2116

### Notes

New

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by DavidTerrassa** [comment]
https://rnw-rn.otteravision.com/rnw/rn/rnw_rn.m3u8

**Comment by darrencycheung** [comment]
It also has streamlock m3u8

**Comment by Nowadaysix** [comment]
> 

Where is the streamlock m3u8?

Is there any script that takes the m3u8 from the normal Record TV?

**Comment by darrencycheung** [comment]
https://5cf4a2c2512a2.streamlock.net/8016/8016/playlist.m3u8

**Comment by AntiPontifex** [comment]
Thank you for the stream: it will be included in the next update.
