### ISSUE TITLE
Add: CFJC News

### ISSUE THREAD

**Issue by BellezaEmporium** [iptv-org/iptv#9971]
### Channel ID

CFJCNews.ca

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://playback.dacast.com/content/access?contentId=22b92dbeebfb44a5a80085ba30599340-live-1817e1d6-9543-3cbf-102f-555b6fc40e50&provider=universe

### Notes

Dacast new link, from old project I have.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Dead stream: please close.
