### ISSUE TITLE
Add: KSA Sports 1

### ISSUE THREAD

**Issue by BellezaEmporium** [iptv-org/iptv#9972]
### Channel ID

KSASports1.sa

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.aloula.sa/en/live/ksa-sports1

### Notes

From old project data.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
can be extended to :

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.aloula.sa/live/saudiatv
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.aloula.sa/live/sbc-channel
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.aloula.sa/live/thikrayat-tv
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.aloula.sa/live/alekhbariya
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.aloula.sa/live/ksa-sports2
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.aloula.sa/live/qurantvsa
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.aloula.sa/live/sunnatvsa
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.aloula.sa/live/riyadhradio
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.aloula.sa/live/jeddahradio
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.aloula.sa/live/jeddahradio
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.aloula.sa/live/nidaalislam
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.aloula.sa/live/saudiaradio

**Comment by freearhey** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.aloula.sa/en/live/ksa-sports1 (offline)
<img width="626" alt="image" src="https://user-images.githubusercontent.com/7253922/232212087-2c21fd6d-2a4a-480d-b612-dd5ac0be1dd5.png">

https://github.com/iptv-org/iptv/blob/299c979aed4d48aa5b3ec4a05458725957af64cf/streams/sa.m3u#L62-L63
