### ISSUE TITLE
Add: IraneFarda TV

### ISSUE THREAD

**Issue by Rayrsn** [iptv-org/iptv#9974]
### Channel ID

IraneFardaTV.us

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Sphinxroot** [comment]
Its offices and studios are in London, UK. Its American branch is in Los Angeles, US

http://iranefardalive.com/livestream/
#EXTINF:-1 ,IraneFarda TV
https://hls.iranfarda.live/hls/stream.m3u8

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/861169502d1e8d6e9de628a930170308b7d0353a/streams/ir.m3u#L118-L119
