### ISSUE TITLE
Add: Seo TV Deportes

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/iptv#9975]
### Channel ID

SEOTV5Deportes.bo

### Stream URL

https://panel.seo.tv.bo:3314/live/seolive.m3u8

### Notes

The website is online. Also the stream works with HLS Player: https://www.hlsplayer.net/#type=m3u8&src=https%3A%2F%2Fpanel.seo.tv.bo%3A3314%2Flive%2Fseolive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment]
Already on list: please close.

**Comment by freearhey** [comment]
https://panel.seo.tv.bo:3314/live/seolive.m3u8 (offline)
<img width="347" alt="image" src="https://user-images.githubusercontent.com/7253922/233799753-b8771da8-ba42-4048-91e5-1777848ec33a.png">
