### ISSUE TITLE
Add: Suspline Pershyi

### ISSUE THREAD

**Issue by darrencycheung** [iptv-org/iptv#9977]
### Channel ID

SusplinePershyi.ua

### Stream URL

http://88.218.242.235:82/0196/video.m3u8?token=2qm9dRD427

### Notes

A public channel

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Alstruit** [comment]
Link doesn't have audio.
